### ISSUE TITLE
Locking files in node_modules

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#4578] opened 2016-03-22 18:52 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 2012 R2

Steps to Reproduce:
1. Open project and do some work
2. Update a npm package. e.g. `npm i -D typescript`

It errors with:
```sh
npm ERR! Error: EPERM: operation not permitted, rename 'E:\hwong\p4\projects\pandash\node_modules\typescript' -> 'E:\hwong\p4\projects\pandash\node_modules\.typescript.DELETE'
```

Once I close VSCode and retry `npm i -D typescript`, it works fine.

**Comment by bpasero** [comment] 2016-03-22 19:42
@unional are you configuring code to use typescript module for compiling or as sdk?

**Comment by unional** [comment] 2016-03-23 08:35
Only know of
```js
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```
So I guess it's sdk?

**Comment by bpasero** [comment] 2016-03-23 08:47
Yes, please report to TypeScript team: https://github.com/Microsoft/typescript

**Comment by unional** [comment] 2016-03-23 08:54
Ar, no.
This does not only occurs to `typescript`. It occurs to to other modules also, e.g. `npm i -D lodash`.

It is clearly vscode issue. Didn't have this in 0.10.10.

**Comment by unional** [comment] 2016-03-23 08:54
Unless you mean `ts language service` locking those files.

**Comment by bpasero** [comment] 2016-03-23 08:58
@unional does it reproduce when you start "code --disable-extensions"?

**Comment by unional** [comment] 2016-03-23 09:00
Will check tomorrow. Sleeping zz.zz...zz :smirk:

**Comment by unional** [comment] 2016-03-23 17:25
By the way, it is sporadic, so will talk a while to repo

**Comment by felixfbecker** [comment] 2016-03-29 20:19
I noticed this aswell. Always getting EPERM errors when updating/removing packages with VS Code running.

**Comment by bpasero** [comment] 2016-03-29 20:41
What workspace setup? Please give me hints how to reproduce the locking.

**Comment by unional** [comment] 2016-04-01 01:10
Just confirmed the issue persist with `--disable-extensions`.

What I tried is to click on the file under the folder before I delete the folder.

**Comment by bpasero** [comment] 2016-04-01 05:13
@unional @felixfbecker I need steps, something like:
- you start vscode by opening a folder with a node_modules folder
- you click on a JS file
- you open a terminal and use NPM to remove a package

Yes, no?

**Comment by unional** [comment] 2016-04-01 05:16
Yes.

**Comment by bpasero** [comment] 2016-04-01 05:26
I cannot reproduce:
- checked out the typescript project https://github.com/Microsoft/TypeScript.git
- npm install
- opened the project in vs code opened the files Jakefile.js and binder.ts
- opened a terminal and typed "npm uninstall iconv-lite"

Can you find a reproducible case with that workspace?
Does it reproduce with VSCode insiders release (http://code.visualstudio.com/Download#insiders)?

**Comment by unional** [comment] 2016-04-01 05:29
What I do is: Open a file under the folder that you are going to delete.
e.g. open `/build/a.js` and then delete `/build`

**Comment by bpasero** [comment] 2016-04-01 05:31
I am able to reproduce now, it seems related to opening a JS file.

**Comment by unional** [comment] 2016-04-01 05:34
Also TS files. My files are TS

**Comment by bpasero** [comment] 2016-04-01 05:35
@dbaeumer I can reproduce easily:
- open a project with node_modules folder (e.g. typescript)
- as soon as I open any JS or TS file, I cannot move the node_modules folder anywhere because it is used/locked
- I can move however when I did not open a TS/JS file
- also, when I disable TS/JS by setting the tssdk variable to bogus I can move

It seems either TypeScript and or Salsa lock files in node_modules again (I remember we had the issue before in https://github.com/Microsoft/TypeScript/issues/6337)

Please advise what to do, I think this is very bad.

**Comment by unional** [comment] 2016-04-01 05:41
Addition:
Not only in `node_modules`. The folder containing the file you are opening is also locked.

Feel free to update the title of this issue.

**Comment by dbaeumer** [comment] 2016-04-01 08:43
I open https://github.com/Microsoft/TypeScript/issues/7762 on the TS side.

**Comment by felixfbecker** [comment] 2016-04-01 11:26
Just happened again, I did not open any file in the node_modules directory. I just opened a folder (vscode-node-debug) in VS Code and ran npm install, which failed because of locked files:
```
388 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\vscode-debugadapter-testsupport' -> 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\.vscode-debugadapter-testsupport.DELETE'
388 verbose stack     at moveAway (C:\Program Files\NodeJS\latest\node_modules\npm\lib\install\action\finalize.js:38:5)
388 verbose stack     at destStatted (C:\Program Files\NodeJS\latest\node_modules\npm\lib\install\action\finalize.js:27:7)
388 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
388 verbose stack
388 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\vscode-debugadapter-testsupport' -> 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\.vscode-debugadapter-testsupport.DELETE'
388 verbose stack     at Error (native)
389 verbose cwd C:\Users\felix\git\opensource\vscode-node-debug
390 error Windows_NT 10.0.10586
391 error argv "C:\\Program Files\\NodeJS\\latest\\node.exe" "C:\\Program Files\\NodeJS\\latest\\node_modules\\npm\\bin\\npm-cli.js" "i"
392 error node v5.9.0
393 error npm  v3.8.3
394 error path C:\Users\felix\git\opensource\vscode-node-debug\node_modules\vscode-debugadapter-testsupport
395 error code EPERM
396 error errno -4048
397 error syscall rename
398 error Error: EPERM: operation not permitted, rename 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\vscode-debugadapter-testsupport' -> 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\.vscode-debugadapter-testsupport.DELETE'
398 error     at moveAway (C:\Program Files\NodeJS\latest\node_modules\npm\lib\install\action\finalize.js:38:5)
398 error     at destStatted (C:\Program Files\NodeJS\latest\node_modules\npm\lib\install\action\finalize.js:27:7)
398 error     at FSReqWrap.oncomplete (fs.js:82:15)
398 error
398 error Error: EPERM: operation not permitted, rename 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\vscode-debugadapter-testsupport' -> 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\.vscode-debugadapter-testsupport.DELETE'
398 error     at Error (native)
398 error  { [Error: EPERM: operation not permitted, rename 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\vscode-debugadapter-testsupport' -> 'C:\Users\felix\git\opensource\vscode-node-debug\node_modules\.vscode-debugadapter-testsupport.DELETE'] parent: 'node-debug' }
399 error Please try running this command again as root/Administrator.
400 verbose exit [ -4048, true ]
```

**Comment by dbaeumer** [comment] 2016-04-01 12:37
@felixfbecker as described in Microsoft/TypeScript#7762 this has nothing to do with the node_modules folder. It can easily happen with other folders as well. And it is not related to having a file open in the folder. It is enough to add any ts file which is part of a tsconfig.json which affects other directories.

**Comment by dbaeumer** [comment] 2016-04-21 09:28
Still waiting on TS team to provide a fix for this.

**Comment by dbaeumer** [comment] 2016-05-20 10:17
I will close this one as upstream. The fix has to come from TS team and is target for 2.0 TS release.

**Closed by dbaeumer** 2016-05-20 10:17 UTC
Labels: bug, important

**Comment by coreh** [comment] 2017-07-01 20:08
Just hit this with VSCode 1.13.1, closing it allowed npm to finish the installation normally:

```
npm ERR! path C:\Users\coreh\Projects\REDACTED\node_modules\typescript
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\coreh\Projects\REDACTED\node_modules\typescript' -> 'C:\Users\coreh\Projects\REDACTED\node_modules\.typescript.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by fedu** [comment] 2017-07-04 10:27
Yep, this is a common problem for me. Always need to close VS Code in order to install any npm packages. No matter what typescript/npm version.

npm ERR! Error: EPERM: operation not permitted, rename

**Comment by dbaeumer** [comment] 2017-07-05 07:29
@mjbvz FYI. Can you please follow up.

**Comment by mjbvz** [comment] 2017-07-05 22:11
See https://github.com/Microsoft/vscode/issues/28593#issuecomment-313238852
