### ISSUE TITLE
VScode on MacOS totally busted since recent update

### ISSUE THREAD

**Issue by resistorsoftware** [microsoft/vscode#139472] opened 2021-12-19 15:49 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.6.3.2
- OS Version: MacOS 12.0.1, X64

Steps to Reproduce:

1. Start VSCode
2. Watch the dock

For whatever reason, when using VSCode now, for every project that was opened under the one umbrella of VSCode the App, with a single object in the Dock, now, VSCode insists on opening each one as a separate instance, polluting the dock with one VSCode icon per project, and all of them are "Application Not Responding". 

Can we please make VSCode work like it used to? One nice instance, with one icon in the dock, and none of this locked up instance stuff.

**Comment by ghcpuman902** [comment] 2021-12-20 03:48
Can confirm this issue.

**Environment**
macOS Monterey Version 12.1
MacBook Pro (15-inch, 2018)
2.9 GHz 6-Core Intel Core i9

**VScode info**
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/3442976/146708883-07aead5a-80e2-4a30-b54c-0e86dcb816da.gif)

**Comment by kimmoahokas** [comment] 2021-12-20 05:58
might be duplicate of #138712

**Closed** 2021-12-20 14:36 UTC
Labels: triage-needed
