### ISSUE TITLE
[Debug] VSCode sends invalid frameId in `scopes` request

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#40189] opened 2017-12-14 01:47 UTC
```
Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Date 2017-11-16T18:34:22.110Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

When quickly stepping through source lines, the VSCode sometimes sends to debug adapter this sequence of requests:
- `stackTrace`
- `next`
- `scopes` using frameId it received in response to stackTrace

Since execution had already been resumed after `stackTrace`, the frameId is invalid.   
Well, that's my assumption that should be invalid.  I don't think this is mentioned in docs anywhere, but it's a logical assumption, since after stepping we might be stopped in a different stack frame.

**Comment by isidorn** [comment] 2018-01-05 11:44
I acknowledge that this issue can happen and not sure I will do something about it on the vscode side. Theoretically I could cancel all scheduled request as soon as the user presses `next`.
But the adapter can also easily handle this by ignoring the invalid frameId.

Assigning to backlog until some issue surfaces to the user regarding this.
fyi @weinand

**Comment by vadimcn** [comment] 2018-01-05 18:02
I think you should cover this in the debug protocol documentation then, because it has implications for design of the debug adapter.  At first sight, reusing the same stack frame ids on every stackTrace request seems like a viable option, but it won't allow the adapter to detect and reject stale frameIds.
Same goes for variable references, btw.   I've been assuming that they become invalid after resuming execution, but this isn't explicitly stated anywhere, as I recall.

**Comment by isidorn** [comment] 2018-06-06 09:59
Duplicate of https://github.com/Microsoft/vscode/issues/50896 which I plan to tackle today

**Closed by isidorn** 2018-06-06 09:59 UTC
Labels: debug, under-discussion
