### ISSUE TITLE
add a scrollbor into the integrated terminal 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#10096] opened 2016-08-03 20:11 UTC
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open an integrated terminal
2. Run an operation with the output that is longer than one screen
3. Try to scroll to beginning of it without a mouse wheel

Expected: there should be a visible scrollbar
Actual: none

**Comment by Tyriar** [comment] 2016-08-03 20:43
Duplicate of https://github.com/Microsoft/vscode/issues/6602, I'm working on it right now actually. Expect it in version 1.5.0.

**Closed by Tyriar** 2016-08-03 20:43 UTC
