### ISSUE TITLE
Stuck in Downloading VS Code Server for Remote SSH Connection

### ISSUE THREAD

**Issue by XIronMan0220** [microsoft/vscode#209607] opened 2024-04-05 08:24 UTC
v1.88 has this bug, I reinstall the v1.87.2 can fix this

**Comment by luckyyyyy** [comment] 2024-04-05 12:05
#209623

**Comment by rzhao271** [comment] 2024-12-19 19:19
Closing as duplicate of #209623 based on the comment above.
@XIronMan0220 let us know if you are still seeing the issue.

**Closed by rzhao271** 2024-12-19 19:19 UTC
