### ISSUE TITLE
Font weight is permanently bold after latest update just like in #214390

### ISSUE THREAD

**Issue by ahmadawais** [microsoft/vscode#224711] opened 2024-08-04 05:02 UTC
Same as reported a couple of months ago, in #214390 the font bold issue is back. 
<img width="616" alt="image" src="https://github.com/user-attachments/assets/d5c3639b-a376-4566-ab1f-1357b6e45482">

Please help fix this again. Super hard to work with this. 

cc: @deepak1556 

- VS Code Version: 
- OS Version: 
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

**Comment by gjsjohnmurray** [comment] 2024-08-04 06:11
/duplicate of #224496 which is currently pinned to the top of the Issues page.

**Closed** 2024-08-04 06:11 UTC
Labels: *duplicate

**Comment by michael-andreuzza** [comment] 2024-08-04 19:08
Same issue, same font. Goes also back to months ago...
