### ISSUE TITLE
VS Code hangs when building dotnet projects

### ISSUE THREAD

**Issue by quantitative-technologies** [microsoft/vscode#102573] opened 2020-07-15 06:43 UTC
Issue Type: <b>Bug</b>

I had been using Visual Studio Code with a netcore 3.1 project without any issues.

After being away for about a week, I tried to continue development. However, when I run the build task from VSCode, the terminal shows

    > Executing task: dotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

and hangs indefinitely. 

Running dotnet build from the console works fine, but I want to use VS Code for debugging again.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 5.4.0-7634-generic
Remote OS version: Linux x64 5.3.0-1030-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|62.77GB (20.91GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: ec2-54-82-194-7.compute-1.amazonaws.com|
|OS|Linux x64 5.3.0-1030-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 3241)|
|Memory (System)|30.91GB (26.33GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
csharp|ms-|1.22.1
vscode-postgresql|ms-|0.3.0
python|ms-|2020.6.91350
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0-insiders2

</details>

**Comment by alexr00** [comment] 2020-07-15 07:37
Can you please share your tasks.json file?

**Comment by james-netramark** [comment] 2020-07-15 09:01
Yes, here it is:

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "shell",
            "args": [
                "build",
                // Ask dotnet build to generate full paths for file names.
                "/property:GenerateFullPaths=true",
                // Do not generate summary otherwise it leads to duplicate errors in Problems panel
                "/consoleloggerparameters:NoSummary"
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}

**Comment by quantitative-technologies** [comment] 2020-07-16 02:55
I was logged in on another account when I responded to your request for further info.:

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "shell",
            "args": [
                "build",
                // Ask dotnet build to generate full paths for file names.
                "/property:GenerateFullPaths=true",
                // Do not generate summary otherwise it leads to duplicate errors in Problems panel
                "/consoleloggerparameters:NoSummary"
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}

**Comment by quantitative-technologies** [comment] 2020-08-02 18:22
There was a related issue: https://github.com/microsoft/vscode/issues/102907#issue-661119111

After system upgrades and restarting I can no longer reproduce either issue.

**Comment by alexr00** [comment] 2020-08-03 09:17
Interesting that system upgrades fixed it. If you have the issue again, please do reply to this issue.

**Comment by quantitative-technologies** [comment] 2020-08-03 14:28
> Interesting that system upgrades fixed it. If you have the issue again, please do reply to this issue.

Actually, it did happen again yesterday with a dotnet project, so the upgrade did not fix it. 

After closing VSCode and restarting it from a terminal, it was OK again.

**Comment by alexr00** [comment] 2020-08-03 14:54
How did you install VS Code?

**Comment by quantitative-technologies** [comment] 2020-08-08 19:34
From the ubuntu repository:

sudo apt-get install code

I just upgraded to version 1.47.3

**Comment by alexr00** [comment] 2020-08-10 10:11
Given that you're also seeing https://github.com/microsoft/vscode/issues/102907#issue-661119111, I'm going to close this issue as a duplicate of that one. Tasks depend on the terminal, so if after that issue is resolve you still see this, I'll investigate further.

**Closed** 2020-08-17 11:23 UTC
Labels: needs more info
