### ISSUE TITLE
[feature request]: Allow diff view (from select for compare command) to be used to edit both sides

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#4856] opened 2016-04-01 13:27 UTC
- VSCode Version: 0.10.13-insider
- OS Version: Windows 7 64-bit

It would be nice if the diff view in the select for compare can be used to edit both files being compared instead of just the file on the right side.

It would make it easy to edit two very similar files at the same time, that only differ in certain parts.

**Comment by Tyriar** [comment] 2016-04-01 16:38
Duplicate of https://github.com/Microsoft/vscode/issues/4180

**Closed by Tyriar** 2016-04-01 16:38 UTC
