### ISSUE TITLE
Terminal bug after VS Code is reopened

### ISSUE THREAD

**Issue by kovacevjosip** [Microsoft/vscode#26013] opened 2017-05-05 09:59 UTC
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04 (x64)

Steps to Reproduce:

1. Open VS Code
2. Go to View -> Integrated Terminal to show integrated terminal
3. Close VS Code
4. Open VS Code and terminal is closed

There is no bug if you are on any other tab (Problems, Output, Debug console), except Terminal.

**Comment by Tyriar** [comment] 2017-05-05 15:04
@kovacevjosip what's in your settings.json and what's your `$SHELL` environment variable set as?

**Comment by kovacevjosip** [comment] 2017-05-05 18:56
This issue happens on my home laptop (OS is also Ubuntu 16.04 x64) and on my working machine with same OS.

settings.json
```
{
    "editor.minimap.enabled": true,
    "workbench.welcome.enabled": false,
    "workbench.iconTheme": "vs-seti"
}
```

Shell variables are default ones:
```
"terminal.integrated.shell.linux": "/bin/bash",
"terminal.integrated.shellArgs.linux": [],
"terminal.integrated.shell.osx": "/bin/bash",
"terminal.integrated.shellArgs.osx": [
    "-l"
  ],
"terminal.integrated.shell.windows": "cmd.exe",
"terminal.integrated.shellArgs.windows": [],
"terminal.integrated.enableBold": true,
"terminal.integrated.cwd": "",
"terminal.integrated.commandsToSkipShell": [
    "editor.action.toggleTabFocusMode",
    "workbench.action.debug.continue",
    "workbench.action.debug.pause",
    "workbench.action.debug.restart",
    "workbench.action.debug.run",
    "workbench.action.debug.start",
    "workbench.action.debug.stop",
    "workbench.action.focusActiveEditorGroup",
    "workbench.action.focusFirstEditorGroup",
    "workbench.action.focusSecondEditorGroup",
    "workbench.action.focusThirdEditorGroup",
    "workbench.action.openNextRecentlyUsedEditorInGroup",
    "workbench.action.openPreviousRecentlyUsedEditorInGroup",
    "workbench.action.quickOpen",
    "workbench.action.showCommands",
    "workbench.action.terminal.clear",
    "workbench.action.terminal.copySelection",
    "workbench.action.terminal.focus",
    "workbench.action.terminal.focusAtIndex1",
    "workbench.action.terminal.focusAtIndex2",
    "workbench.action.terminal.focusAtIndex3",
    "workbench.action.terminal.focusAtIndex4",
    "workbench.action.terminal.focusAtIndex5",
    "workbench.action.terminal.focusAtIndex6",
    "workbench.action.terminal.focusAtIndex7",
    "workbench.action.terminal.focusAtIndex8",
    "workbench.action.terminal.focusAtIndex9",
    "workbench.action.terminal.focusNext",
    "workbench.action.terminal.focusPrevious",
    "workbench.action.terminal.kill",
    "workbench.action.terminal.new",
    "workbench.action.terminal.paste",
    "workbench.action.terminal.runActiveFile",
    "workbench.action.terminal.runSelectedText",
    "workbench.action.terminal.scrollDown",
    "workbench.action.terminal.scrollDownPage",
    "workbench.action.terminal.scrollToBottom",
    "workbench.action.terminal.scrollToTop",
    "workbench.action.terminal.scrollUp",
    "workbench.action.terminal.scrollUpPage",
    "workbench.action.terminal.toggleTerminal"
  ],
```

**Comment by kovacevjosip** [comment] 2017-05-05 19:37
Same thing happens on Windows 10 x64 with latest updates.
![ice_video_20170505-213150](https://cloud.githubusercontent.com/assets/14251756/25761379/eda7f994-31da-11e7-805a-cd6ceb28cfe1.gif)

**Comment by Tyriar** [comment] 2017-05-09 17:47
Thanks @kovacevjosip, this is a duplicate of https://github.com/Microsoft/vscode/issues/25664

**Closed by Tyriar** 2017-05-09 17:47 UTC
Labels: integrated-terminal, needs more info
