### ISSUE TITLE
Some extensions are not loaded correctly when VS Code is launched from WSL

### ISSUE THREAD

**Issue by MichaelTong** [microsoft/vscode#77434] opened 2019-07-16 00:36 UTC
- VSCode Version: 1.36.1
- OS Version: 18396

Steps to Reproduce:

1. Open any work folder from WSL by `code somefolder`
2. Wait it to load
3. The icons of some extension are not loaded to the left sidebar, such as Booksmarks, Latex-workshop, Live Share.
4. Some extensions that have UI effects shown in editor don't have the effects any more. Such as Bookmarks (there is a little bookmark icon to the left of the marked line), and Bracket Pair Colorizer 2 (There are different colors for bracket pairs)
    

Does this issue occur when all extensions are disabled?: Need to use extensions

The issue is also on insider build, but for what I remembered, I didn't see it on 1.35.

**Comment by fiveisprime** [comment] 2019-07-16 18:19
I'm seeing this for the Azure extensions with this in the log

![image](https://user-images.githubusercontent.com/1186948/61319189-914d5c80-a7bb-11e9-8b79-be30d3b931e6.png)

There are quite a few errors fetching icons.

**Comment by chrisdias** [comment] 2019-07-16 18:47
i see the same.  the icon isn't there, but the area is still click-able.

![image](https://user-images.githubusercontent.com/1487073/61320976-77ae1400-a7bf-11e9-8f40-3b46f2538e63.png)

**Comment by aeschli** [comment] 2019-07-18 10:37
duplicate of https://github.com/microsoft/vscode-remote-release/issues/966

**Closed by aeschli** 2019-07-18 10:37 UTC
Labels: extensions
