### ISSUE TITLE
command '' not found on dot (.) 

### ISSUE THREAD

**Issue by kurtextrem** [microsoft/vscode#179951] opened 2023-04-14 09:57 UTC
Type: <b>Bug</b>

1. Try typing a dot (.) somewhere in any window apart from e.g. the issue reporter modal (for some reason there it works)

This happens on my M1 Laptop in the latest Insider version (see the info), and on my Windows too. Using extension bisect with all extensions disabled, it also does not work.
I checked keybindings, and found nothing associated to "." only.

Curiously, entering a dot works when you have capslock enabled and press shift+dot.

VS Code version: Code - Insiders 1.78.0-insider (3ad5774eb8123d4224eb55629df9e5f82fe13b99, 2023-04-14T05:25:56.476Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X3D 8-Core Processor            (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.18GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id 20fc44d7-c7f8-4363-83e3-6649172aed0c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kurtextrem** [comment] 2023-04-14 09:58
![image](https://user-images.githubusercontent.com/502146/232013249-1723cd53-7502-4879-a861-e858d8fe43b1.png)
![image](https://user-images.githubusercontent.com/502146/232013314-f284420a-7fd1-4774-8db8-a49ab00501c8.png)

Has been like this before the version from the 14th as well.

**Comment by gjsjohnmurray** [comment] 2023-04-14 10:29
Does the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues lead anywhere?

**Comment by kurtextrem** [comment] 2023-04-14 11:25
![image](https://user-images.githubusercontent.com/502146/232031115-a05c2f1b-16f1-4abc-af4f-2be8730fc817.png)

> I have tried all of the above

[keybinds.txt](https://github.com/microsoft/vscode/files/11232214/keybinds.txt)

**Comment by kurtextrem** [comment] 2023-04-14 11:30
[keybinds (JSON).txt](https://github.com/microsoft/vscode/files/11232268/keybinds.JSON.txt)
[keybinds.txt](https://github.com/microsoft/vscode/files/11232269/keybinds.txt)

from my M1 Mac

**Comment by gjsjohnmurray** [comment] 2023-04-14 12:55
When you run the command `Preferences: Open Keyboard Shortcuts (JSON)` from Command Palette, what does the `keybindings.json` file contain?

**Comment by kurtextrem** [comment] 2023-04-15 11:09
On my Windows: [keybind prefs JSON.txt](https://github.com/microsoft/vscode/files/11239197/keybind.prefs.JSON.txt)

**Comment by gjsjohnmurray** [comment] 2023-04-15 11:25
:+1: Please close the issue.

**Closed** 2023-04-15 11:36 UTC
Labels: info-needed, triage-needed

**Comment by crankedguy** [comment] 2023-05-06 21:40
Exact same thing happened here on a WIN10 machine after updating to 1.78.0 today. 
Had to manually delete the assignment that I haven't done for sure myself... Who would assign . to ''??

```
Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by Evannguyen273** [comment] 2023-05-08 18:58
> Exact same thing happened here on a WIN10 machine after updating to 1.78.0 today. Had to manually delete the assignment that I haven't done for sure myself... Who would assign . to ''??
> 
> ```
> Version: 1.78.0 (user setup)
> Commit: 252e5463d60e63238250799aef7375787f68b4ee
> Date: 2023-05-03T20:09:00.748Z
> Electron: 22.4.8
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19045
> Sandboxed: No
> ```

I'm having the same issue except I can't find any line that assign "." or dot or period to anything

**Comment by crankedguy** [comment] 2023-05-08 19:07
> I'm having the same issue except I can't find any line that assign "." or dot or period to anything

Did you check your keybindings.json?
There was an entry like. This seems to be a very bad joke on WIN with this release in certain cases
```
{
		"key": ".",
		"command": ""
},
```

**Comment by ghaschel** [comment] 2023-05-08 19:21
There was an empty entry. Although i did remove it from keybindings.json it still happens.

**Comment by Evannguyen273** [comment] 2023-05-08 19:25
> > I'm having the same issue except I can't find any line that assign "." or dot or period to anything
> 
> Did you check your keybindings.json? There was an entry like this.
> 
> ```
> {
> 		"key": ".",
> 		"command": ""
> },
> ```
> 
> This seems to be a very bad joke on WIN with this release in certain cases

I have check and searched for every possible expression. But there's little no line that shows key with . alone.

**Comment by crankedguy** [comment] 2023-05-08 19:29
Sorry I can't help any further here as for me it was fixed after removing the entry shown in my last post from keybindings.json, which was clearly done by/during the update to 1.78.0

**Comment by Evannguyen273** [comment] 2023-05-08 19:36
> with 1.78 at least on Windows

Yeah. Thanks man. I'll open a new issue and just roll back to 1.73 and wait for a patch for 1.78

**Comment by starball5** [comment] 2023-05-08 22:25
Related: #181469

**Comment by kurtextrem** [comment] 2023-05-09 07:48
So I wasn't crazy after all and accidentally added that command twice to my JSON snippet. I'm using the Insider version, which explains why I had the issue a month earlier

**Comment by crankedguy** [comment] 2023-05-09 09:53
> So I wasn't crazy after all and accidentally added that command twice to my JSON snippet. I'm using the Insider version, which explains why I had the issue a month earlier

Nah this is real 😁

**Comment by kitety** [comment] 2023-05-13 02:03
> > I'm having the same issue except I can't find any line that assign "." or dot or period to anything我遇到了同样的问题，除了我找不到任何分配“。”的行。或点或句点到任何东西
> 
> Did you check your keybindings.json?你检查过你的 keybindings.json 了吗？ There was an entry like this.有一个条目是这样的。
> 
> ```
> {
> 		"key": ".",
> 		"command": ""
> },
> ```
> 
> This seems to be a very bad joke on WIN with this release in certain cases在某些情况下，对于此版本的 WIN，这似乎是一个非常糟糕的笑话

Yes,me too. It is annoying。

**Comment by starball5** [comment] 2023-05-14 06:00
duplicate of #181469?
