### ISSUE TITLE
Cursor not between quotes after autocomplete

### ISSUE THREAD

**Issue by neuronflicker** [Microsoft/vscode#11782] opened 2016-09-09 15:39 UTC
- VSCode Version: 1.5.1
- OS Version: Windows 7 and 10

Steps to Reproduce:

1. Open an html file
2. Type "<html lan" and then use autocomplete (Tab or Enter) to finish the lang="" bit
3. The cursor is now after the quotes instead of between them as in previous versions

I haven't checked this with other languages, or on other platforms.
I have no extensions related to html installed.

**Comment by mrmlnc** [comment] 2016-09-09 15:41
See #11763 and #11742.

**Comment by ramya-rao-a** [comment] 2016-09-09 20:56
Duplicate of #11719

**Closed by ramya-rao-a** 2016-09-09 20:56 UTC
