### ISSUE TITLE
Code Helper overloads CPU (100%+)

### ISSUE THREAD

**Issue by pim013** [Microsoft/vscode#41379] opened 2018-01-10 07:28 UTC
- VSCode Version: Version 1.19.1 aswell as Version 1.20.0-insider
- OS Version: macOS 10.13.1

Sometimes I can have up to 4 or 5 'Code Helper' processes running using all 99%+ CPU. 

Steps to Reproduce:

1. Open VS Code (or Insiders)
2. Open project (doesn't need to be a big one, simple HTML is sufficient)
3. Check Activity Monitor and see Code Helper being at 95+ CPU

Activity Monitor 'Open Files and Ports' txt: [https://www.dropbox.com/s/akjka8aojk2j7vy/codehelper.txt?dl=0](https://www.dropbox.com/s/akjka8aojk2j7vy/codehelper.txt?dl=0)

Does this issue occur when all extensions are disabled?: No, but there seems to be no pattern about which extensions are giving problems. I am now running the EXACT same extensions as a colleague and they are not having this problem.

**Comment by bpasero** [comment] 2018-01-10 07:36
@pim013 
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by pim013** [comment] 2018-01-10 08:44
@bpasero 
Here you go
[codehelper2.txt](https://github.com/Microsoft/vscode/files/1618075/codehelper2.txt)

**Comment by pim013** [comment] 2018-01-10 08:57
[codehelper_95percent.txt](https://github.com/Microsoft/vscode/files/1618115/codehelper_95percent.txt)

**Comment by bpasero** [comment] 2018-01-10 11:20
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by jcreamer898** [comment] 2018-01-10 16:42
I'm having a very similar issue currently.

When I run `code --status`, all it does is open VS Code?

I ran a ps against the helper and got...

![](https://d.pr/i/iZSnBz+)

**Comment by bpasero** [comment] 2018-01-10 17:00
@jcreamer898 you can only run `code --status` when an instance of code is already running.

**Comment by jcreamer898** [comment] 2018-01-10 17:07
It was running when I ran that.

**Comment by jcreamer898** [comment] 2018-01-10 17:08
I think I might have found the culprit, `import cost` was running hot when I ran the profile in the running extensions panel. If that didn't end up fixing it, I'll report back. :)

**Comment by ajmas** [comment] 2018-01-10 19:56
Is there any way to list the CPU load of a given extension, similar to what Google Chrome's 'Task Manager' can do?

**Comment by jcreamer898** [comment] 2018-01-10 21:31
I was thinking the same! ☝️

**Comment by jcreamer898** [comment] 2018-01-10 21:33
This was definitely my problem FYI... https://github.com/wix/import-cost/issues/47

**Comment by ajmas** [comment] 2018-01-10 21:52
BTW Opened #41432 to cover the 'Task Manager' suggestion.

**Comment by jrieken** [comment] 2018-01-11 16:54
re https://github.com/Microsoft/vscode/issues/41379#issuecomment-356718190

Yeah, go 'F1 > Show Running Extensions', then hit the profile button

**Comment by shahata** [comment] 2018-01-17 19:37
Issue is fixed in import-cost version 2.6.2, sorry for the trouble...

**Comment by jrieken** [comment] 2018-01-17 19:40
Ok, thanks for getting back to us.

**Closed by jrieken** 2018-01-17 19:40 UTC
Labels: extension-host, freeze-slow-crash, needs more info
