### ISSUE TITLE
HTML Language feature has failed 

### ISSUE THREAD

**Issue by nitti87** [microsoft/vscode#88372] opened 2020-01-09 15:54 UTC
Issue Type: <b>Bug</b>

Got an error when opening a HTML-file 

 **Error Text** 
[Error - 16:43:20] Error while computing semantic tokens for file:///c%3A/Users/NITTI/Desktop/vickie/workbench/login/index.html: Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at n (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:519889)
    at visitNode (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:17761:24)
    at Object.forEachChild (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:17951:24)
    at n (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:520182)
    at visitNode (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:17761:24)
    at Object.forEachChild (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:18012:24)
    at n (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:520182)
    at visitNodes (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:17770:30)
    at Object.forEachChild (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:18003:24)
    at n (c:\Users\NITTI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:520182)
[Error - 16:46:22] Error while computing semantic tokens for file:///c%3A/Users/NITTI/Desktop/vickie/workbench/login/index.html: Cannot read property '0' of undefined

VS Code version: Code - Insiders 1.42.0-insider (7e64866a703c83dcdd3b84a8b48dd1673895fb7d, 2020-01-09T05:41:05.676Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|31.12.0
csharp|ms-|1.21.9
vscode-icons|vsc|9.7.0

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment] 2020-01-09 16:05
Can you share the contents of the HTML file as well to help us debug?

**Comment by nitti87** [comment] 2020-01-09 16:07
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="./css/sign_in.css" />
    <link rel="stylesheet" type="text/css" href="./css/registrate.css" />
    <link rel="stylesheet" type="text/css" href="./css/popup-dialogs.css" />
  </head>
  <body>

      <div class="container">

        <header>
          <div class="titlebar">
            <div class="btn active" style="border-bottom-left-radius: 11px;" id="minimize" aria-label="Minimize the window">&#x2212;</div>
            <div class="btn inactive" id="maximize" aria-label="Maximize the window">&#128470;</div>
            <div class="btn active" style="border-bottom-right-radius: 11px;" id="close" aria-label="Close the window">&#10005;</div>
          </div>
        </header>
        
        <main class="centerContainer">
          <div class="loginContainer">

            <div class="loginForm">
              <div class="usernameHolder">
                  <input type="text" id="username" placeholder=" " />
                  <label for="username">Username</label>

                  <div class="bubbleHolder"><div class="bubble">Wrong username</div></div>

              </div>
    
              <div class="passwordHolder">
                  <input type="password" id="password" placeholder=" " />
                  <label for="password">Password</label>

                  <div class="bubbleHolder"><div class="bubble">Wrong password</div></div>

                  <div class="password_recoveryHolder">
                    <img src="./images/forgot.svg" alt="Recover your password" />
                    <div class="bubble">Recover your password</div>
                  </div>

              </div>

              <div class="rememberMe">
                <input type="checkbox" id="remember_checkbox" />  
                <label for="remember_checkbox">Remember me</label>
              </div>

              <div class="submitHolder">
                <button>Log in</button>
              </div>

            </div>

          </div>

          <div class="registrate_now">
            Not a member? <a href="#" aria-label="Registrate now">Registrate now</a>
          </div>

        </main>
      </div>

    <script>
      require('../global_funct/pre_funct.js');
      require('./services/main_login.js')
    </script>
  </body>
</html>

**Comment by gjsjohnmurray** [comment] 2020-01-09 18:48
Looks like a duplicate of #88366

**Comment by connor4312** [comment] 2020-01-09 19:06
Good catch

/duplicate #88366

**Closed** 2020-01-09 19:06 UTC
Labels: *duplicate, html
