### ISSUE TITLE
Extension Host crash

### ISSUE THREAD

**Issue by KodaCHC** [microsoft/vscode#149898] opened 2022-05-19 05:03 UTC
Since version 1.67 VSCode crashes every few minutes for me.
Now I have installed 1.67.2 and have the same issue

```
localProcessExtensionHost.ts:290 Extension Host
localProcessExtensionHost.ts:291 <--- Last few GCs --->[13820:000049CC00330000]   708856 ms: Mark-sweep (reduce) 3823.8 (3859.0) -> 3823.5 (3843.5) MB, 28.1 / 0.0 ms  (average mu = 0.990, current mu = 0.651) last resort GC in old space requested[13820:000049CC00330000]   708890 ms: Mark-sweep (reduce) 3823.5 (3843.5) -> 3823.5 (3843.5) MB, 33.5 / 0.0 ms  (average mu = 0.970, current mu = 0.000) last resort GC in old space requested<--- JS stacktrace --->FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 1: 00007FF766664A16 node::Buffer::New+50294 2: 00007FF766664C1F node::OnFatalError+463 3: 00007FF7691789DA v8::Data::IsFixedArray+842 4: 00007FF76917892C v8::Data::IsFixedArray+668 5: 00007FF769249FD3 v8::JSHeapConsistency::CheckWrapper+68179 6: 00007FF767C8F184 v8::CppHeap::GetHeapHandle+101364 7: 00007FF767C78F38 v8::CppHeap::GetHeapHandle+10664 8: 00007FF767B56CEB uv_random+6532091 9: 00007FF765CDECA1 v8::internal::OSROptimizedCodeCache::ClearEntry+26062510: 0000388A07F0B23C 
abstractExtensionService.ts:884 Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:884
log.ts:313   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
log.ts:301  INFO Automatically restarting the extension host.
log.ts:307  WARN Canceled: Canceled
    at Object.S [as canceled] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1172)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8442
    at Array.forEach (<anonymous>)
    at v.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8390)
    at Br.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1968:5930)
    at Ul.stopExtensionHosts (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:23897)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25337)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3171:5539)
    at Ul._onExtensionHostCrashOrExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25082)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:24823
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at U._onExtHostProcessExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:31904)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:26586
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at $ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:3413)
    at T.onResponse (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4386)
    at T.onBuffer (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4226)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:1817
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at EventEmitter.$ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:65:51237)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:881)
localProcessExtensionHost.ts:290 Extension Host
localProcessExtensionHost.ts:291 <--- Last few GCs --->[29496:0000684C00330000]    79159 ms: Mark-sweep (reduce) 3834.7 (3865.4) -> 3834.5 (3850.1) MB, 28.7 / 0.0 ms  (average mu = 0.976, current mu = 0.741) last resort GC in old space requested[29496:0000684C00330000]    79196 ms: Mark-sweep (reduce) 3834.5 (3850.1) -> 3834.5 (3849.9) MB, 36.4 / 0.0 ms  (average mu = 0.930, current mu = 0.000) last resort GC in old space requested<--- JS stacktrace --->FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 1: 00007FF766664A16 node::Buffer::New+50294 2: 00007FF766664C1F node::OnFatalError+463 3: 00007FF7691789DA v8::Data::IsFixedArray+842 4: 00007FF76917892C v8::Data::IsFixedArray+668 5: 00007FF769249FD3 v8::JSHeapConsistency::CheckWrapper+68179 6: 00007FF767C8F184 v8::CppHeap::GetHeapHandle+101364 7: 00007FF767C78F38 v8::CppHeap::GetHeapHandle+10664 8: 00007FF767B56CEB uv_random+6532091 9: 00007FF765CDECA1 v8::internal::OSROptimizedCodeCache::ClearEntry+26062510: 00006FA907F0B23C 
abstractExtensionService.ts:884 Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:884
log.ts:313   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
log.ts:301  INFO Automatically restarting the extension host.
log.ts:307  WARN Canceled: Canceled
    at Object.S [as canceled] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1172)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8442
    at Array.forEach (<anonymous>)
    at v.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8390)
    at Br.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1968:5930)
    at Ul.stopExtensionHosts (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:23897)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25337)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3171:5539)
    at Ul._onExtensionHostCrashOrExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25082)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:24823
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at U._onExtHostProcessExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:31904)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:26586
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at $ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:3413)
    at T.onResponse (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4386)
    at T.onBuffer (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4226)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:1817
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at EventEmitter.$ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:65:51237)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:881)
localProcessExtensionHost.ts:290 Extension Host
localProcessExtensionHost.ts:291 <--- Last few GCs --->[18960:000059FC00330000]   576034 ms: Mark-sweep (reduce) 3828.7 (3858.7) -> 3828.4 (3843.7) MB, 36.5 / 0.0 ms  (average mu = 0.987, current mu = 0.480) last resort GC in old space requested[18960:000059FC00330000]   576079 ms: Mark-sweep (reduce) 3828.4 (3843.7) -> 3828.4 (3843.7) MB, 45.1 / 0.0 ms  (average mu = 0.962, current mu = 0.000) last resort GC in old space requested<--- JS stacktrace --->FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 1: 00007FF766664A16 node::Buffer::New+50294 2: 00007FF766664C1F node::OnFatalError+463 3: 00007FF7691789DA v8::Data::IsFixedArray+842 4: 00007FF76917892C v8::Data::IsFixedArray+668 5: 00007FF769249FD3 v8::JSHeapConsistency::CheckWrapper+68179 6: 00007FF767C8F184 v8::CppHeap::GetHeapHandle+101364 7: 00007FF767C78F38 v8::CppHeap::GetHeapHandle+10664 8: 00007FF767B56CEB uv_random+6532091 9: 00007FF765CDECA1 v8::internal::OSROptimizedCodeCache::ClearEntry+26062510: 0000753E07F0B23C 
abstractExtensionService.ts:884 Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:884
log.ts:313   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
log.ts:301  INFO Automatically restarting the extension host.
log.ts:307  WARN Canceled: Canceled
    at Object.S [as canceled] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1172)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8442
    at Array.forEach (<anonymous>)
    at v.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8390)
    at Br.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1968:5930)
    at Ul.stopExtensionHosts (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:23897)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25337)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3171:5539)
    at Ul._onExtensionHostCrashOrExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25082)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:24823
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at U._onExtHostProcessExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:31904)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:26586
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at $ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:3413)
    at T.onResponse (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4386)
    at T.onBuffer (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4226)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:1817
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at EventEmitter.$ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:65:51237)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:881)
localProcessExtensionHost.ts:290 Extension Host
localProcessExtensionHost.ts:291 <--- Last few GCs --->[19056:0000455600330000]    24989 ms: Mark-sweep (reduce) 3838.9 (3866.0) -> 3838.6 (3851.0) MB, 28.9 / 0.0 ms  (average mu = 0.942, current mu = 0.740) last resort GC in old space requested[19056:0000455600330000]    25028 ms: Mark-sweep (reduce) 3838.6 (3851.0) -> 3838.6 (3850.7) MB, 38.7 / 0.0 ms  (average mu = 0.838, current mu = 0.000) last resort GC in old space requested<--- JS stacktrace --->FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 1: 00007FF766664A16 node::Buffer::New+50294 2: 00007FF766664C1F node::OnFatalError+463 3: 00007FF7691789DA v8::Data::IsFixedArray+842 4: 00007FF76917892C v8::Data::IsFixedArray+668 5: 00007FF769249FD3 v8::JSHeapConsistency::CheckWrapper+68179 6: 00007FF767C8F184 v8::CppHeap::GetHeapHandle+101364 7: 00007FF767C78F38 v8::CppHeap::GetHeapHandle+10664 8: 00007FF767B56CEB uv_random+6532091 9: 00007FF765CDECA1 v8::internal::OSROptimizedCodeCache::ClearEntry+26062510: 00003C7407F0B23C 
abstractExtensionService.ts:884 Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:884
log.ts:313   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
log.ts:301  INFO Automatically restarting the extension host.
log.ts:307  WARN Canceled: Canceled
    at Object.S [as canceled] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1172)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8442
    at Array.forEach (<anonymous>)
    at v.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8390)
    at Br.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1968:5930)
    at Ul.stopExtensionHosts (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:23897)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25337)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3171:5539)
    at Ul._onExtensionHostCrashOrExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25082)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:24823
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at U._onExtHostProcessExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:31904)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:26586
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at $ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:3413)
    at T.onResponse (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4386)
    at T.onBuffer (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4226)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:1817
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at EventEmitter.$ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:65:51237)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:881)
localProcessExtensionHost.ts:290 Extension Host
localProcessExtensionHost.ts:291 <--- Last few GCs --->[29780:00002C3C00330000]    20964 ms: Mark-sweep (reduce) 3826.2 (3853.7) -> 3826.0 (3838.7) MB, 33.9 / 0.0 ms  (average mu = 0.943, current mu = 0.622) last resort GC in old space requested[29780:00002C3C00330000]    21005 ms: Mark-sweep (reduce) 3826.0 (3838.7) -> 3826.0 (3838.5) MB, 41.4 / 0.0 ms  (average mu = 0.847, current mu = 0.000) last resort GC in old space requested<--- JS stacktrace --->FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 1: 00007FF766664A16 node::Buffer::New+50294 2: 00007FF766664C1F node::OnFatalError+463 3: 00007FF7691789DA v8::Data::IsFixedArray+842 4: 00007FF76917892C v8::Data::IsFixedArray+668 5: 00007FF769249FD3 v8::JSHeapConsistency::CheckWrapper+68179 6: 00007FF767C8F184 v8::CppHeap::GetHeapHandle+101364 7: 00007FF767C78F38 v8::CppHeap::GetHeapHandle+10664 8: 00007FF767B56CEB uv_random+6532091 9: 00007FF765CDECA1 v8::internal::OSROptimizedCodeCache::ClearEntry+26062510: 00001FCE07F0B23C 
abstractExtensionService.ts:884 Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:884
log.ts:313   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
notificationsAlerts.ts:42 Der Erweiterungshost wurde innerhalb der letzten 5 Minuten unerwartet dreimal beendet.
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:307  WARN Canceled: Canceled
    at Object.S [as canceled] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1172)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8442
    at Array.forEach (<anonymous>)
    at v.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8390)
    at Br.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1968:5930)
    at Ul.stopExtensionHosts (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:23897)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25337)
    at Ul._onExtensionHostCrashed (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3171:5539)
    at Ul._onExtensionHostCrashOrExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:25082)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3168:24823
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at U._onExtHostProcessExit (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:31904)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:26586
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at $ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:3413)
    at T.onResponse (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4386)
    at T.onBuffer (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4226)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:1817
    at m.invoke (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at EventEmitter.$ (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:65:51237)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:881)
```

**Comment by gjsjohnmurray** [comment] 2022-05-19 06:29
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by KodaCHC** [comment] 2022-05-20 12:27
Thank you, that was new to me.

https://marketplace.visualstudio.com/items?itemName=aswinkumar863.smarty-template-support
There is already an issue about it.

**Comment by gjsjohnmurray** [comment] 2022-05-20 13:52
:1: Please close this issue here.

**Closed** 2022-05-20 14:37 UTC
Labels: needs more info
