### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by FabioCarpi** [Microsoft/vscode#8106] opened 2016-06-24 14:04 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 10 x64

With the code:
<?php
$site = substr($site, strpos($site, "format-number"));
$site = substr($site, strpos($site, ">") + 1);?>
<tr><td>VQP</td></tr>
<tr><td style="text-align:right"><?php echo number_format(substr($site, 0, strpos($site, "<")), 0, ",", ".");?></td></tr>

Look the color on second <?php

**Comment by aeschli** [comment] 2016-07-19 14:45
duplicate of #8739

**Closed by aeschli** 2016-07-19 14:45 UTC
Labels: languages basic
