### ISSUE TITLE
[read-only]: cannot apply workspace edit for read-only workspace provider

### ISSUE THREAD

**Issue by legomushroom** [Microsoft/vscode#65324] opened 2018-12-18 20:39 UTC
In the latest `Insiders`, when trying to apply workspace edits to a **read-only** workspace, the applied edits have no effect. Works fine in the `read-write` mode. This breaks the co-editing scenarios for `VS Live Share` extension.

- VSCode Version: 1.31.0-insider <d85a16f2e4354f2850b4171f84fe0c94b0cea338> <2018-12-18T06:07:13.414Z>
- OS Version: Mas OSx 10.13.6

Steps to Reproduce:

1. Register a read-only workspace:

```javascript
vscode.workspace.registerFileSystemProvider(
  'test-authority',
  /* your file system provider */,
  { isCaseSensitive: true, isReadonly: true }
);
```

2. Apply workspace edit(s):

```javascript
const edits = /* edits */;
const workspaceEdit = new vscode.WorkspaceEdit();
workspaceEdit.set(uri, edits);
await vscode.workspace.applyEdit(workspaceEdit);
```

3. Observe that the edits are not applied with read-only file system provider.

Does this issue occur when all extensions are disabled?: Yes

---

*Alternative* repro:

1. Install `VS Live Share` extension from the marketplace on the latest Insiders(1.31.0-insiders).
2. Open a folder and click `Start read-only collaboration session...` in the Live Share viewlet.
3. Open another instance of the VSCode insiders and join the session.
4. On the host side, open a file and make some edits.
5. Notice that the edits don't get applied on the guest side.

**Comment by legomushroom** [comment] 2018-12-18 20:44
cc @IlyaBiryukov

**Comment by IlyaBiryukov** [comment] 2018-12-18 21:17
cc @jrieken, @isidorn This seems to be the same breaking change that was reverted in #57032 regressing again.

**Comment by isidorn** [comment] 2019-01-23 14:43
First of all, sorry for the slow response.

Can you reproduce this with latest vscode insiders?
If yes, do you see some errors in the vscode console? If yes can you please paste them here

Thanks for the steps but can you please create a full git hub sample repository for which we can reproduce this? You can start from our sample fs provider, modify it such that the issue is shown.
https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample

Thanks a lot

**Comment by isidorn** [comment] 2019-01-30 14:47
Ping @legomushroom @IlyaBiryukov

**Comment by legomushroom** [comment] 2019-02-11 19:37
@isidorn sorry, missed your reply. Yes, it is still reproducible in the current `Insiders`(1.32.0-insider) and `Stable`(1.31.0). This completely breaks our read-only scenarios for `VS Live Share`. Working on the repro for you.

**Comment by legomushroom** [comment] 2019-02-11 20:33
@isidorn there is the extension with the repro: [fsprovider-sample.zip](https://github.com/Microsoft/vscode/files/2852928/fsprovider-sample.zip)

1. Lunch the extension and run `MemFS: Workspace Setup` in command palette.
2. Run `MemFS: Create Files` in command palette.
3. Run `MemFS: Start Bash`.

The extension will try to insert a current timestamp string into beginning of the `file.yaml` in the root with interval of `1s`. It logs the same message to the `debug console` for testing purposes. Notice that if the `file.yaml` is open in background, the edits come through, but if user makes the file active, the edits no longer applied.

**Comment by isidorn** [comment] 2019-02-18 09:22
Thanks for repro steps, reopening and assinging to february.

**Comment by isidorn** [comment] 2019-02-18 14:16
Ok I see that you reopened the issue, closing this one

**Closed by isidorn** 2019-02-18 14:16 UTC
