### ISSUE TITLE
Removing Santa hat

### ISSUE THREAD

**Issue by americanhawk1** [microsoft/vscode#87319] opened 2019-12-19 06:31 UTC
I'm deeply offended that the Santa hat was removed. 

It's a disgrace to the Christmas holiday and to what it represents. "The most important thing about Christmas is that it invites us to reflect on the most important things in our life — our faith, our family, and our freedom. Our faith gives us hope, our family gives us love, and our freedom gives us the opportunity to practice our faith and to love each other — and of course the Holy Family." 

In removing this hat, you're deeply offending all Christians and their faith, as well as non-believers who look up to the Christmas holiday as much more than a holiday, but a symbol for love and passion as well as bringing family together. We are representing the "good" side of what Christmas and Santa represents. It's unbelievable that one person got offended and the hat was removed... at least make it a toggle... You guys probably made more people mad than you did happy about this decision.

I hope you reconsider, thanks!

**Comment by egamma** [comment] 2019-12-19 08:02
Duplicate of #87291

**Closed by egamma** 2019-12-19 08:02 UTC

**Comment by egamma** [comment] 2019-12-19 19:21
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
