### ISSUE TITLE
How do I supposed to migrate to the new User Setup on Windows?

### ISSUE THREAD

**Issue by KillyMXI** [Microsoft/vscode#56479] opened 2018-08-15 16:19 UTC
New installer says I have to uninstall previous installation.
Release notes contain no instructions on how to safely migrate to new User Setup and keep all my stuff in place (extensions, configuration).

Since it has no obvious benefits for me right now, and I don't want to waste time to discover myself where this road leads, I will just choose "Don't Show Again" and completely forget about it (most likely). I wonder what implications it may have in future. Will it receive updates still?

**Comment by davormas** [comment] 2018-08-16 11:10
This is probably duplicate of #56421.

As I commented there, it would be great to know is there something we're giving up with sticking to system installation.

**Closed** 2018-08-16 20:54 UTC
Labels: *duplicate, install-update
