### ISSUE TITLE
Auto indent should not do anything inside a string

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29663] opened 2017-06-27 18:52 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (15b579d13dbf6817bb493feff6f36cec87577929, 2017-06-27T05:11:33.154Z)
- OS Version: Linux x64 4.10.0-24-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.3
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.15.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#29492

![image](https://user-images.githubusercontent.com/2193314/27604699-f1468728-5b2e-11e7-91aa-8fe87e4de13d.png)

Move down twice:

![image](https://user-images.githubusercontent.com/2193314/27604711-f9968cc0-5b2e-11e7-8588-fdf4c3df6b8a.png)

**Comment by rebornix** [comment] 2018-09-19 22:04
Duplicate of #19420, let's track it here.

**Closed** 2018-09-19 22:04 UTC
Labels: *duplicate, bug, editor-autoindent, feature-request
