### ISSUE TITLE
tsserver process keeps holding on to file locks causing rush link to fail consistently

### ISSUE THREAD

**Issue by moizgh** [microsoft/vscode#87780] opened 2019-12-27 19:02 UTC
Issue Type: <b>Bug</b>

tsserver process keeps holding on to file locks causing rush link to fail consistently

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:59:13.638Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1680 v4 @ 3.40GHz (16 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.90GB (49.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
kusto-syntax-highlighting|jos|1.0.1
git-tree-compare|let|1.7.1
vscode-typescript-tslint-plugin|ms-|1.2.3
code-spell-checker|str|1.7.20

</details>

**Comment by mjbvz** [comment] 2019-12-29 23:44
What file or directory does it have locks for?

**Comment by moizgh** [comment] 2019-12-30 12:19
This is what the error looks like:
```
ERROR: Error: Error: EPERM: operation not permitted, mkdir 'C:\Users\moizgh\<package path>\node_modules'
Often this is caused by a file lock from a process such as your text editor, command prompt, or "gulp serve"
```

**Comment by mjbvz** [comment] 2019-12-30 18:05
Duplicate of https://github.com/microsoft/TypeScript/issues/32113

**Closed by mjbvz** 2019-12-30 18:05 UTC
Labels: javascript, needs more info, typescript
