### ISSUE TITLE
Scroll/Reveal when there are multiple cursors

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/vscode#6995] opened 2016-05-28 18:40 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10

Steps to Reproduce:
1. Create two or more cursors in a document
2. Move the cursors down using the down arrow key until the cursors go outside of the editor
3. If there is only one cursor, the document scrolls to keep the cursor visible but it doesn't if there are multiple cursors

**Comment by brandondrew** [comment] 2018-08-03 20:04
I think that https://github.com/Microsoft/vscode/issues/55780 would also help this problem (but they are certainly not mutually exclusive).

**Comment by andrei7777** [comment] 2018-11-26 17:51
the issue still exists in 1.29.1

**Comment by madprops** [comment] 2019-03-15 15:33
Just wanted to say this is possibly the most annoying bug for me right now, it really disrupts my workflow since doing multiple cursors operations and then undoing is very common. Please give this importance >_<

**Comment by builder7777** [comment] 2019-03-18 13:54
still an issue in 1.32.2

**Comment by nicolo-ribaudo** [comment] 2019-03-18 14:50
@builder7777 Rather than noticing that this issue still isn't fixed (which is obvious, it's still open 😛), I think that the VS Code team would welcome a pull request.
If you don't have time to do so (I don't), you can :+1: this issue and ask other people to do so.

**Comment by tuttieee** [comment] 2019-03-27 16:07
Hello, I'm in trouble with this issue too.

I investigated the code and found this is because of here:
https://github.com/Microsoft/vscode/blob/1afeb46cc4f2856ed6d0759fff85b13647c7ab83/src/vs/editor/common/controller/cursor.ts#L431-L436

Then, I looked for where this code came from and found that it was the very first commit of this repo:
https://github.com/Microsoft/vscode/commit/8f35cc4768393b25468416829e980d7550619fb1#diff-f8aa0da950270e2d56baecaf5819a4c5R871
but cannot find the reason from any commit messages.

I tested and confirmed that this issue would be resolved if the else-clause shown above is removed.
I want to fix this and commit it, but don't know whether it's OK. There should be some discussions on such a fundamental behavior.
How do you think, @alexandrudima ?

**Comment by borishere** [comment] 2020-02-04 10:35
The issue still exists.

**Comment by builder7777** [comment] 2020-02-04 14:14
almost 4 years later, still here in version 1.41.1.

**Comment by tuttieee** [comment] 2020-02-05 15:27
I finally created a PR for this issue.
I hope it will be merged, or at least, a discussion will start.

**Comment by alexdima** [comment] 2020-03-03 16:45
With bc5d1b1d0559ab081df847b5ce84ca1621d158e2, I have pushed a change that in the multicursor case, a conceptional rectangle/bounding box is computed around all the cursors.

If the bounding box fits in the viewport, it is revealed, but if the bounding box does not fit in the viewport, the editor does not scroll.

**Closed by alexdima** 2020-03-03 16:45 UTC
Labels: editor-multicursor, feature-request

**Comment by borishere** [comment] 2020-03-11 07:00
Still doesn't work for me. Can someone confirm that it is fixed?

**Comment by alexdima** [comment] 2020-03-11 07:05
@borishere Are you using insiders? Stable does not have that change yet.

**Comment by borishere** [comment] 2020-03-11 07:10
@alexdima I'm using a stable version. Thanks for clarification.

**Comment by maxbelyanin** [comment] 2020-03-16 17:57
Still doesn't work for me too
