### ISSUE TITLE
Markdown highlights wrong multiline bold and italics

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode#92923] opened 2020-03-18 12:50 UTC
Issue Type: <b>Bug</b>

Write this markdown:

```md
Some _italic text
in two lines_, **bold text
in two lines**, and ***bold italic text
in two lines***.
```

It is rendered like this:
![Captura de pantalla de 2020-03-18 12-48-28](https://user-images.githubusercontent.com/973709/76962337-f2af6780-6916-11ea-8922-b981f14cebd1.png)

It should be properly rendered, just like if it was one line:
![Captura de pantalla de 2020-03-18 12-49-14](https://user-images.githubusercontent.com/973709/76962348-f642ee80-6916-11ea-8b82-894406df7402.png)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:44:52.965Z)
OS version: Linux x64 5.5.8-200.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.48GB (2.34GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
language-hugo-vscode|bud|1.1.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.1
vsc-invoke|dch|0.0.12
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
vscode-pull-request-github|Git|0.15.0
gc-excelviewer|Gra|2.1.34
restructuredtext|lex|122.0.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.9.0
language-gettext|mro|0.1.1
vscode-docker|ms-|1.0.0
vscode-language-pack-es|MS-|1.43.6
python|ms-|2020.2.64397
qub-xml-vscode|qub|1.2.8
jinjahtml|sam|0.12.0
code-spell-checker|str|1.8.0
code-spell-checker-spanish|str|1.0.3
sass-indented|syl|1.7.5
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by mjbvz** [comment] 2020-03-19 04:33
Duplicate of https://github.com/microsoft/vscode-markdown-tm-grammar/issues/36

**Closed by mjbvz** 2020-03-19 04:33 UTC
