### ISSUE TITLE
Remapped Escape key doesn't work anymore with Linux / Ubuntu (Version 1.11)

### ISSUE THREAD

**Issue by GravesDevelopment** [Microsoft/vscode#24266] opened 2017-04-07 21:03 UTC
- VSCode Version: 1.11 and 1.11.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Remap Escape key to Caps Lock with "setxkbmap -option caps:escape" in .profile - This way both Caps Lock and Escape can be used as the Escape key. Log out of user and log back in, so the remapping is loaded.
2. Pressing the Caps Lock key used to work perfectly fine in VS Code before version 1.11, now it only works with the actual Escape key.

**Comment by Ashod** [comment] 2017-04-08 18:41
+1

Same issue here. Rather frustrating with the Vim plugin.

**Comment by alexandrudima** [comment] 2017-04-10 08:31
Duplicate of #23991

**Closed by alexandrudima** 2017-04-10 08:31 UTC
