### ISSUE TITLE
HTML Autoformat Empty Line Issue

### ISSUE THREAD

**Issue by djarekg** [Microsoft/vscode#21899] opened 2017-03-03 14:44 UTC
I have autoformat set to true on save for html and empty lines between are auto added. Here is a screen shot and my settings.

![image](https://cloud.githubusercontent.com/assets/671093/23555176/e440005c-fff5-11e6-9b95-3547d677c576.png)

"editor.formatOnSave": true,
    "vsicons.presets.angular": true,
    "html.format.wrapAttributes": "force-aligned",
    "html.format.indentHandlebars": false

**Comment by aeschli** [comment] 2017-03-03 19:55
@djarekg Can you paste the example code?

**Comment by finico** [comment] 2017-03-03 21:26
@aeschli maybe not exactly the same, but it happens when I press "format document"
![22](https://cloud.githubusercontent.com/assets/4924283/23569611/1b4bc6dc-0071-11e7-96af-fa597ddabe5e.gif)

**Comment by aeschli** [comment] 2017-03-05 19:55
duplicate of #21717

**Comment by djarekg** [comment] 2017-03-06 14:33
```
<product-select formControlName="product"
                                                                                        required
                                                                                        [defaultItem]="[{
                                                            productId: productItem.productId,
                                                            productName: productItem.productName,
                                                            extension: productItem.productMediaExtension
                                                        }]"
                                                                                        [disabled]="readonly || !productItem || !productItem.vendorId"
                                                                    
                                                                                        [duplicateThumbnailFrom]="productItemMediaThumbnail"
                                                                    
                                                                                        [employeeOfficeId]="productItem.employeeOfficeId"
                                                                    
                                                                                        [editing]="isProductEditMode"
                                                                                        [valuePrimitive]="true"
                                                                                        [vendorId]="productItem.vendorId">
                                                                        </product-select>
```

**Comment by aeschli** [comment] 2017-03-07 08:54
I'm no able to reproduce this with 1.9 or 1.10. I don't get any empty lines added.
Can you check that there's no other html formatter installed?
(run code with --disable-extensions) 


```
<product-select formControlName="product"
                required
                [defaultItem]="[{
                                                            productId: productItem.productId,
                                                            productName: productItem.productName,
                                                            extension: productItem.productMediaExtension
                                                        }]"
                [disabled]="readonly || !productItem || !productItem.vendorId"
                [duplicateThumbnailFrom]="productItemMediaThumbnail"
                [employeeOfficeId]="productItem.employeeOfficeId"
                [editing]="isProductEditMode"
                [valuePrimitive]="true"
                [vendorId]="productItem.vendorId">
    </product-select>
```

**Closed by aeschli** 2017-03-07 08:54 UTC

**Comment by jmatike** [comment] 2017-08-15 20:25
Hello! Hope am on the good section. Here is an exemple of code.
```
<?php



namespace KirooRebuntu\Http\Controllers;



use Illuminate\Http\Request;

use KirooRebuntu\Http\Controllers\Controller;

use KirooRebuntu\CustomerModel;

use KirooRebuntu\TransactionModel;

use Mail;

use KirooRebuntu\Mail\adminPaymentConfirmMail;

use KirooRebuntu\Mail\adminPaymentConfirmeAndValideMail;

use Barryvdh\Debugbar\Facade as Debugbar;

use Storage;

use Illuminate\Support\Facades\Log;

use GuzzleHttp\Client;

use GuzzleHttp\RequestOptions;
```
Every blank line you see are created by the editor, it's very very annoying. What setting am I suppose to edit in other to avoid that kind of format code please ?
Am using VSCode 1.15 with no formating code installed.

**Comment by jmatike** [comment] 2017-08-15 20:30
Hello! Hope am on the good section and sorry for re-open a closed ticket.
Here is an exemple of code.
```
<?php



namespace KirooRebuntu\Http\Controllers;



use Illuminate\Http\Request;

use KirooRebuntu\Http\Controllers\Controller;

use KirooRebuntu\CustomerModel;

use KirooRebuntu\TransactionModel;

use Mail;

use KirooRebuntu\Mail\adminPaymentConfirmMail;

use KirooRebuntu\Mail\adminPaymentConfirmeAndValideMail;

use Barryvdh\Debugbar\Facade as Debugbar;

use Storage;

use Illuminate\Support\Facades\Log;

use GuzzleHttp\Client;

use GuzzleHttp\RequestOptions;
```
Every blank line you see are created by the editor, it's very very annoying. What setting am I suppose to edit in other to avoid that kind of format code please ?
Am using VSCode 1.15 with no formating code installed.
