### ISSUE TITLE
Multiple suggestions: Relative clickable paths, Automatically switch to debug console after preTasks are done.

### ISSUE THREAD

**Issue by withmask** [microsoft/vscode#119338] opened 2021-03-19 16:34 UTC
Relative clickable paths:
VSC allows you to jump to a file if a full path is printed to terminal, this is a great feature and it would be better if you can click relative files (relative to the current workspace directory)

Automatically switch to debug console:
When debugging, when the preTask is done VSC does not automatically switch to the debug terminal; and so i miss some logs (for some reasons the debug console is very buggy about logs). And if the action is quick, i can't even look at logs and when i switch there is no output

**Comment by IllusionMH** [comment] 2021-03-19 19:42
Better to keep separate requests in separate issue so they will be discussed/tracked separately.

> Relative clickable paths:


Already works event if not relative. You can <kbd>Ctrl</kbd>+<kbd>Click</kbd> almost everything that looks like path or filename (and doesn't contain spaces). If VS Code can't find file it will trigger "Go To file..." prompt with this data.

> Automatically switch to debug console:

Is it with `"debug.internalConsoleOptions": "openOnSessionStart"` setting or you have different value?

>  (for some reasons the debug console is very buggy about logs)

You should create separate issue with detailed problem description and steps to reproduce

**Comment by withmask** [comment] 2021-03-20 09:13
> Is it with "debug.internalConsoleOptions": "openOnSessionStart" setting or you have different value?
My issues have been fixed when changing this value, thank you so much.

>Already works event if not relative. You can Ctrl+Click almost everything that looks like path or filename (and doesn't contain spaces). If VS Code can't find file it will trigger "Go To file..." prompt with this data.

Indeed it does work on the integrated terminal, but not on the debug console (example, src/index.ts is clickable in terminal but on debug console i can only click full paths such as /home/withmask/project/src/index.ts)

**Comment by isidorn** [comment] 2021-03-22 08:17
Great for the first issue is fixed via settings.
For better link detection in the debug console we already have an issue, thus closing as duplicate

**Closed** 2021-03-22 08:18 UTC
Labels: *duplicate, debug, feature-request
