### ISSUE TITLE
File search match behaviour

### ISSUE THREAD

**Issue by yudori** [microsoft/vscode#60514] opened 2018-10-10 13:43 UTC
Not sure if this is the intended behaviour or if this is a bug, However lets say I have a file in a drectory: /home/yudori/stuff/project/src/index.html

When I perform a file search via ctrl + p,  with keyword "src index", there is a match, but if i use the keyword "index src", there is no match.

Would be nice to have a match for both scenarios to avoid thinking too much about the directory structure when searching.

OS: Ubuntu 16.04
VSCode version: 1.27.2

**Comment by skprabhanjan** [comment] 2018-10-11 08:35
@roblourens , can i take this up ?

**Comment by roblourens** [comment] 2018-10-11 15:00
I appreciate your enthusiasm @skprabhanjan but I think this one would be a bit hard. There are a few places that need to be changed and I'm not sure how they interact. Also some more general issues around fuzzy matching.

**Comment by skprabhanjan** [comment] 2018-10-11 15:34
@roblourens, okay I understand:)
I shall keep looking for a suitable one to solve !
Thanks for your patience :)

**Comment by roblourens** [comment] 2019-10-09 02:31
Duplicate of https://github.com/microsoft/vscode/issues/30404

**Closed by roblourens** 2019-10-09 02:31 UTC
Labels: feature-request, search
