### ISSUE TITLE
Files disappear when scrolling on left sidebar sometimes

### ISSUE THREAD

**Issue by lijunray** [Microsoft/vscode#32250] opened 2017-08-10 19:16 UTC
- VSCode Version: 1.14.0
- OS Version: 10.12.5
Steps to Reproduce:
No very sure how this happens. It happens frequently but not every time when I (more frequently after open a directory and) scroll up or down, like in the gif.

Reproduces without extensions: Yes
![aug-10-2017 15-13-06](https://user-images.githubusercontent.com/14250009/29187665-8c42fd34-7dde-11e7-8400-5eb6f51fdb27.gif)

**Comment by bpasero** [comment] 2017-08-11 08:53
@lijunray is this reproducible? Is there any output in the developer console?

@joaomoreno looks like a tree bug!

**Comment by joaomoreno** [comment] 2017-08-11 13:07
Wow. I was pretty sure this was fixed. There must be another issue.

**Comment by lijunray** [comment] 2017-08-11 14:17
@bpasero @joaomoreno Sorry I don't know how to reproduce this. Like I said, it happened most frequently(not every time but almost) when I opened a directory on Explore. This has been happening since several days ago. Yesterday I restarted VSCode for the first time in a long term and it didn't happen again. But I'm pretty sure it also happened before last time I restarted(or update) VSCode. It may has something to do with the time I've been using it?

**Comment by joaomoreno** [comment] 2017-08-15 09:38
Could this be #32510?

**Comment by lijunray** [comment] 2017-08-15 14:53
@joaomoreno Yes, I guess my problem is the same as #32510, most likely, though I don't remember how to reproduce my problem, but I reproduced this one and found it has exactly the same behavior as mine.

**Comment by joaomoreno** [comment] 2017-08-16 07:58
Duplicate of #32510

**Closed by joaomoreno** 2017-08-16 07:58 UTC
Labels: bug, needs more info, tree
