### ISSUE TITLE
Self-closing curly braces {{ do not appear inside a tag

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#43039] opened 2018-02-06 14:17 UTC
- VSCode Version: 1.20.0-ins
- OS Version: win7x64

In .html file, you type a tag `<div></div>`, and type {{ inside of it ... and what you expect is that curly braces will auto-close. But they don't.

They want to auto-close only in situations when there is a space after your caret:

![ng - curly braces](https://user-images.githubusercontent.com/24613274/35863871-b9215816-0b58-11e8-9d93-cf502a7ace55.gif)

**Comment by aeschli** [comment] 2018-02-07 15:05
duplicate of https://github.com/Microsoft/vscode/issues/42956

**Closed by aeschli** 2018-02-07 15:05 UTC
Labels: html
