### ISSUE TITLE
Error getting dark and light value on MacOs

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#145918] opened 2022-03-23 18:34 UTC
Testing #145616'

On MacOs when i set appearance as "Dark Mode" the value that is being used is the "High Contrast Light Color Team". And when i switch to "Light Mode" appearance, the value being used is "High Contrast Color Team". So they are swapped.

**Comment by aeschli** [comment] 2022-03-23 20:54
The high contrast mode on the Mac is turned on by setting `Inverse Colors`. As a result, all windows are now using inverted colors. So while the appearance is configured to `light`, now all is dark. To match that we show the preferred High Contrast Dark theme.
With appearance as `Dark`, all is light and we show the preferred High Contrast Light theme.

**Comment by aeschli** [comment] 2022-03-25 21:03
Closing as intended,

**Closed by aeschli** 2022-03-25 21:03 UTC
