### ISSUE TITLE
Hex Editor: Unclear how to reopen file in regular editor

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#115183] opened 2021-01-27 04:46 UTC
Testing #114952

Once you open a file in the Hex Editor, it is unclear how to reopen the file in the regular editor.

Double-clicking in the File Explorer does not open the file.
There is no Hex Editor: Close File command

It seems the only way is to close the Hex Editor and reopen the file. 

Also is there a way to have the regular editor and the Hex Editor side by site are two open files, similar to Markdown Preview?

**Comment by lramos15** [comment] 2021-01-27 14:18
Duplicate of https://github.com/microsoft/vscode-hexeditor/issues/38

There is currently no way to have them side by side as the hex editor doesn't have a readonly mode so you would have two different type of editors open that are both editable.

**Closed by lramos15** 2021-01-27 14:18 UTC
