### ISSUE TITLE
Cannot read error message because error popup too small.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [Microsoft/vscode#31815] opened 2017-08-01 16:00 UTC
When building code that might fail for any number of reasons I am commonly unable to even read the error message that pops up because the window only shows part of the first line. The error does not appears in the Problems, Output or Debug panes.

Here I am attempting to execute a Typescript project.

![unreadableerror](https://user-images.githubusercontent.com/18445931/28834685-e28451ee-76da-11e7-8765-5f4d869c36c0.png)

Here's how I created the project:

Create a directory and open VSCode there.

Press F1, enter "Debug: Open launch.json" and when prompted select environment node.js. This will generate a launch.json file configured for node.js.

Press CTRL+' to open the command prompt. Enter "tsc --init" this will generate a tsconfig.json file.
NOTE: tsc must be version 1.6 or greater. Check with "tsc -v", upgrade with "npm install -g typescript".

In tsconfig.json uncomment "sourcemap": "true"
In tsconfig.json uncomment "outdir" and set to "./output".

Press CTRL+SHIFT+B to build, select nodejs build environment.

Press F5 to execute. Error message appears that cannot be read.

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.9.3
vscode-great-icons|emm|2.1.7
auto-close-tag|for|0.4.2
csharp|ms-|1.10.0
debugger-for-chrome|msj|3.1.4
vscode-css-peek|pra|1.2.4
html-css-class-completion|Zig|1.7.0

(1 theme extensions excluded)

**Comment by weinand** [comment] 2017-08-01 20:42
Please post your launch.json here.

**Comment by Neutrino-Sunset** [comment] 2017-08-03 09:48
`{
   // Use IntelliSense to learn about possible Node.js debug attributes.
   // Hover to view descriptions of existing attributes.
   // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
   "version": "0.2.0",
   "configurations": [
      {
         "type": "node",
         "request": "launch",
         "name": "Launch Program",
         "program": "${file}",
         "outFiles": [ "${workspaceRoot}/output/**/*.js" ]

      }
   ]
}
`

The problem isn't that I can't execute a Typescript project, I solved that easily enough. The problem is that whenever VSCode displays an error message, I can't read it.

**Comment by weinand** [comment] 2017-08-03 12:42
@Neutrino-Sunset So the error your are reporting is: VS Code error notification isn't usable with long paths because it cuts of the end of the message (instead of wrapping it).
I've reformatted your launch.json by using "3 backticks" which is the proper way to format multiline code.

@isidorn Is there a way to wrap messages in the error notification?
In addition I noticed that the path in the error message shows an underscore character '_' instead of a backslash. Do you know why? I remember we've seen something similar already.

**Comment by isidorn** [comment] 2017-08-03 12:56
Currently we have no API in the [message service](https://github.com/Microsoft/vscode/blob/isidorn/next/src/vs/workbench/services/message/browser/messageService.ts#L79) to wrap a message.
This should be tackled as part of https://github.com/Microsoft/vscode/issues/22388

As for the underscore character, there might be some issue with PII substition in the string. This is captured in https://github.com/Microsoft/vscode/issues/29408

Closing as duplicate of the issues above

**Closed by isidorn** 2017-08-03 12:56 UTC
Labels: bug, debug
