### ISSUE TITLE
Inconsistent Cursor Behavior with Auto-Closing Quotes in Attributes 

### ISSUE THREAD

**Issue by codez-test** [microsoft/vscode#228845] opened 2024-09-17 15:02 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0
- OS Version: [Windows 11]

Steps to Reproduce:

# Inconsistent Cursor Behavior with Auto-Closing Quotes in Attributes

## Current Behavior
When typing an HTML attribute (e.g., `id=`), the editor auto-completes it to `id=""` and places the cursor between the quotation marks. If the user then manually types a double quote (which is a common habit for some developers), the cursor jumps to the outside of the closing quote, resulting in `id=""|` (where | represents the cursor position).

## Expected Behavior
After auto-completion of `id=""` with the cursor between the quotes, if the user manually types a double quote, the cursor should remain between the quotation marks. The expected sequence would be:

1. User types: `id=`
2. Plugin auto-completes to: `id="|"` (where | is the cursor)
3. User types a double quote
4. Cursor should remain: `id="|"` 

Instead of the current behavior where it becomes: `id=""|`

## Why This Matters
This current behavior disrupts the workflow of developers who are accustomed to manually typing closing quotes, even when auto-completion is active. It requires an extra step (moving the cursor back) to continue editing the attribute value, which can be frustrating and reduce productivity, especially when working with numerous attributes.

## Additional Context
- This behavior is consistent across different file types (HTML, PHP, etc.) where attributes are used.

## Environment
- VS Code Version: 1.93.0
- PHP Extension Version: PHP Devsense -  v1.51.15986
- OS: [Windows 11]

**Comment by codez-test** [comment] 2024-09-17 15:57
Yes, I have upgraded the version but still facing the same issue.

**Comment by aeschli** [comment] 2024-09-19 08:20
duplicate of https://github.com/microsoft/vscode/issues/140698

**Closed by aeschli** 2024-09-19 08:20 UTC
