### ISSUE TITLE
Don't prompt for Remote-WSL on mac

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#110114] opened 2020-11-06 22:15 UTC
I think I installed Remote-WSL on a windows machine, got it settings sync'd over to my mac, now I see this on mac:
![image](https://user-images.githubusercontent.com/323878/98419658-67681b00-203a-11eb-8cbe-11545b610cc3.png)

**Comment by sana-ajani** [comment] 2020-11-06 22:17
Ah, I know I saw this too :(

**Comment by bamurtaugh** [comment] 2020-11-07 00:48
Thanks for pointing this out - this notification is part of the experiment. I'm wondering if we should filter in the experiment or in the extension itself to only show this to Windows users (I'm not immediately sure how to do that in the experiment, but I feel like there should be a way?).

**Comment by aeschli** [comment] 2020-11-09 10:17
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/3965.
I will fix it in the extension and push today

**Comment by bamurtaugh** [comment] 2020-11-13 21:54
I believe @aeschli fixed this issue at the beginning of this week- if this happens again or I'm mistaken, please just let me know. Thanks again!

**Closed by bamurtaugh** 2020-11-13 21:54 UTC
