### ISSUE TITLE
Freeze when typing some regex

### ISSUE THREAD

**Issue by mercury233** [microsoft/vscode#116028] opened 2021-02-07 11:42 UTC
Issue Type: <b>Bug</b>

1. Open a folder, open the Search panel, enable regex search
2. Type `var(.*\n?)+`, got some results
3. Type any char after the `+`, vscode freeze, got "The window is no longer responding" soon

![GIF 2021-2-7 19-39-50](https://user-images.githubusercontent.com/13391795/107145452-6bf1e780-6939-11eb-9c28-d21842c16bec.gif)

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.86GB free)|
|Process Argv|--folder-uri file:///f%3A/Works/ygo233-dl --crash-reporter-id fa242f2f-7933-4ee6-9e43-fc268fb16acb|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by IllusionMH** [comment] 2021-02-08 03:14
/duplicate of #30874

When you have opened tabs - global search will utilize JS based match on opened files. In your case its `(.*\n?)+` that causes Catastrophic Backtracking which freezes main thread on files that are more than couple of short lines.

If there are no open tabs ripgrep will be used that doesn't have such problem.

**Closed** 2021-02-08 03:15 UTC
Labels: *duplicate, new release
