### ISSUE TITLE
Add file extension to Vanilla ES6 imports

### ISSUE THREAD

**Issue by JacobCaron** [microsoft/vscode#80645] opened 2019-09-10 13:42 UTC
When importing files such as: `import AContainer from "../library/ExtendedObjects/AContainer"`, add the `.js` extension of the file so modern browsers can interpret the code. Currently, without the .js and without transpiling the code, modern browsers such as Chrome will throw the following error: `GET http://localhost:3000/js/library/ExtendedObjects/AContainer net::ERR_ABORTED 404 (Not Found)`. Implementing this change would allow for faster and more explicit code.

Example:
Change: 
`import AContainer from "../library/ExtendedObjects/AContainer"` 
to 
`import AContainer from "../library/ExtendedObjects/AContainer.js"`

**Comment by mjbvz** [comment] 2019-09-10 15:14
Duplicate of https://github.com/microsoft/TypeScript/issues/16577

**Closed by mjbvz** 2019-09-10 15:14 UTC
