### ISSUE TITLE
titleBarStyle: custom = Windows trackpad scrolling lag bug is back

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#53793] opened 2018-07-07 20:49 UTC
- VSCode Version:
Version: 1.26.0-insider
Commit: bd953248ad6a8e2f8896bfb78b3ae40e0fd47426
Date: 2018-07-06T05:17:37.386Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
- OS Version: Windows 10 x64 April 2018 update
- Surface Book 1

With these settings it works as expected:

>     "window.smoothScrollingWorkaround": true,
>     "window.titleBarStyle": "native"

But if I enable the custom titleBar:

>     "window.smoothScrollingWorkaround": true,
>     "window.titleBarStyle": "custom"

the famous #13612 bug is back :(

Steps to Reproduce:

1. enable scrolling workaround and custom titleBar
2. open a file which is long-enough to have scrolling
3. minimify VSCode by clicking on the title bar's minimize icon
4. maximize VSCode by clicking on VSCode's icon in the Windows taskbar
5. try to scroll with the trackpad: it's laggy

This is the same bug as #13612

**Comment by sbatten** [comment] 2018-07-10 21:38
@bpasero, I think the original fix was dependent on toggling the menubar but this will no longer work

**Comment by bpasero** [comment] 2018-07-11 05:54
Hm, thats also ugly, I have updated the workaround in https://github.com/Microsoft/vscode/issues/13612#issue-182568355 to mention this.

**Comment by warpdesign** [comment] 2018-07-11 12:14
I'm wondering: since the problem seems to be definitely fixed in Chrome/Chromium (which Electron is based on), why cannot it be definitely fixed in Electron too and why is this workaround is needed?

**Comment by bpasero** [comment] 2018-07-11 16:42
@warpdesign because we do not understand the problem in Electron yet. Feel free to investigate.

**Comment by warpdesign** [comment] 2018-07-11 16:48
@bpasero sure, I'll gitve it a try.

Can you tell me where I should start? Can you point me to the patch that was applied to chromium that is supposed to fix the problem?

**Comment by bpasero** [comment] 2018-07-12 05:56
The umbreally bug on the VSCode side is https://github.com/Microsoft/vscode/issues/13612 but the real issue is with Chrome (we use Electron and as such Chrome is our rendering engine) and a fix was pushed a while ago (https://chromium-review.googlesource.com/c/chromium/src/+/867070) but there are actually more related Chrome bugs still open (https://bugs.chromium.org/p/chromium/issues/detail?id=779372, https://bugs.chromium.org/p/chromium/issues/detail?id=765311).
 
There is a related discussion in https://github.com/electron/libchromiumcontent/pull/472 where the Chrome fix was backported to Electron. Unfortunately the fix does not seem to work for us as soon as you minimize the window and restore it. It looks like there are some issues with how windows are layered when restoring (see discussion from https://github.com/electron/libchromiumcontent/pull/472#issuecomment-372119471 onwards) but I am not an expert around this topic so I cannot really understand it.

PS: I forgot to mention that Windows is working on a fix and will have it in one of the future releases, but this will obviously take some time to land for users.

**Comment by nico-onmap** [comment] 2018-07-12 10:11
Thank you for the details.

I'm willing to try and make some more changes to libchrominiumcontent: what should I do to build VSCode using my own version of it?

**Comment by warpdesign** [comment] 2018-07-12 10:12
Thank you for the details.

I'm willing to try and make some more changes to libchrominiumcontent: what should I do to build VSCode using my own version of it?

**Comment by bpasero** [comment] 2018-07-12 12:47
@warpdesign that is great. here are the steps (given that you probably want to try this out with a more modern version of Electron - 2.0.x - we go with our VSCode exploration build that comes with Electron 2.0.x):
* download VSCode Exploration build ([link](https://az764295.vo.msecnd.net/exploration/3477633dd05a05469c7de27980d3a88e82ee05f8/VSCode-win32-x64-1.26.0-exploration.zip))
* compile Electron from the 2.0.x branch with your changes
* from the command line run `electron.exe "<path to VSCode exploration>\resources\app\out\main.js"`
* it should use your Electron and not the bundled one (verify by opening developer tools and typing "`process.execPath`" in the console, the output should point to the Electron executable from your build

Here are some more details from a mail conversation I had with a developer from the Windows team:

> I’ve been digging more into this, now that I have a solid repro and better tracing. It turns out that there are some input stack bugs here that are causing this, which I will ensure get fixed for the next version of Windows. However, in the meantime, you may be able to help Electron root cause it with the following info:
>  
> In the “good” setup (workaround active), there are three HWNDs:
> Toplevel: class=Chrome_WidgetWin_1, name is based on the tab’s file
> Child 1: class=Chrome_RenderWidgetHostHWND, name=Chrome Legacy Window
> Child 2: class=Intermediate D3D Window, no name
> In the “bad” setup (laggy touchpad), Child 1 doesn’t exist
>  
> The toplevel window and Child 1 are on the same thread; Child 2 is in a separate process (though they seem to share an input queue). When Child 1 doesn’t exist, there’s some weird interaction between Child 2 and the toplevel window that causes the laggy touchpad.
>  
> So if this “Chrome Legacy Window” is present, you’re good, and your workaround seems to make that happen. Perhaps you can take this info to the Electron team and they can solve it?

> To expand on my analysis – another way this could be solved is if the “Intermediate D3D Window” doesn’t get hit-tested – it’s really this window that messes everything up. The other child (“Chrome Legacy Window”) being present just makes us avoid the mess, but really the blame is on the D3D window.
> Here are ways (non-exhaustive, hit-testing is complex) on how the window could be made not hit-testable:
> Hide the window
> Change its client rect
> Add WS_EX_TRANSPARENT, I think
> The appropriate change depends on how the window is actually being used. Note that I’m not a Win32 expert, I can’t really say a lot about this topic.

> At this point, I think you should proceed in one of two directions:
> See if you can figure out what VSCode is doing on the minimize/restore path that is causing this to happen. Clearly you can influence the presence of that window, given that that’s what your workaround does.
> See if you can repro it in a different Electron app, to prove it’s not something VSCode is specifically doing.
>  
> Jianpeng had pointed out some Chromium breakpoints:
> views::NativeViewHost::Detach
> views::NativeViewHostAura::NativeViewDetaching
> views::NativeViewHostAura::RemoveClippingWindow
> aura::Window::Hide
>  
> These methods call in minimize and the restore methods are around. I think something prevent the window attaching in restore.

**Comment by warpdesign** [comment] 2018-07-15 08:47
Thanks for the details. I'll let you know if I can come up with something.

Right now I'm having a hard time building electron: the bootstrap script locks while downloading this lib:

> Downloading libchromiumcontent-static.tar.bz2...

No idea why, but my slow internet connection doesn't help for sure...

**Comment by bpasero** [comment] 2018-07-15 09:50
@warpdesign thats weird, it worked for me when I tried on Windows on Friday, even though it took a long time.

**Comment by warpdesign** [comment] 2018-07-15 11:53
It seems the download times out after some time: I'll try again with a faster connection.

**Comment by warpdesign** [comment] 2018-07-17 07:50
Ok, I figured out the last problem: I can now compile Electron. The interesting stuff starts :)

**Comment by JoelLisenby** [comment] 2018-08-16 17:15
I am still seeing this issue as well on Windows 10 vscode v1.26.0. Minimizing the window fixes the scrolling issue but sad that I have to go back to not using maximized windows again.

**Comment by bpasero** [comment] 2018-08-17 05:11
Windows is working on a fix and will release it soon to Windows 10 versions.

**Comment by Drae** [comment] 2018-09-02 11:08
Hopefully not getting ahead of myself but I'm running the the insider build of VSCode on the latest fast channel insider build of Windows 10 (17751.1) on a Surface Book. Smooth scrolling seems to have returned (both at start and when min/maxing) with and without the custom title bar style and with or without the smooth scrolling workaround.

**Comment by bpasero** [comment] 2018-09-02 15:15
@Drae thanks, that is good news. I can confirm that this fix should land in the October update and you seem to be on it already from the fast ring 💯

**Comment by bpasero** [comment] 2018-10-15 16:52
Closing this as the Windows 10 October update is rolling out to people. This bug is fixed as part of the Windows 10 RS5 update.

**Closed by bpasero** 2018-10-15 16:52 UTC
Labels: electron, trackpad/scroll, upstream, windows
