### ISSUE TITLE
 Model is disposed!

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#22926] opened 2017-03-21 03:07 UTC
Issue Id: <b>ee4a0c54-3c69-def6-7024-bd08594c0996</b><br /><br />*Versions* <br />- 1.10.2<br />*Stack* <br />Error: Model is disposed!<br />[/vs/editor/common/model/textModel.ts#L70:9](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/editor/common/model/textModel.ts#L70:9)<br />[/vs/editor/common/model/textModel.ts#L185:7 (_assertNotDisposed)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/editor/common/model/textModel.ts#L185:7 (_assertNotDisposed))<br />[/vs/workbench/api/node/mainThreadEditorsTracker.ts#L352:18 (getVersionId)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/api/node/mainThreadEditorsTracker.ts#L352:18 (getVersionId))<br />[/vs/workbench/api/node/mainThreadEditors.ts#L297:46 (applyEdits)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/api/node/mainThreadEditors.ts#L297:46 (applyEdits))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler))<br />    at _combinedTickCallback (internal/process/next_tick.js:67:7) <no sourcemaps><br />    at process._tickCallback (internal/process/next_tick.js:98:9) <no sourcemaps><br />

**Comment by alexandrudima** [comment] 2017-03-27 09:00
@jrieken Perhaps you can check if this is a recent regression...

**Comment by jrieken** [comment] 2017-04-05 13:28
closing because this was still with the old code that had potential for invalid state

**Closed by jrieken** 2017-04-05 13:28 UTC
Labels: error-telemetry
