### ISSUE TITLE
Tasks in VSCode insiders are now wrapped in quotes and are broken

### ISSUE THREAD

**Issue by ghiscoding** [Microsoft/vscode#46207] opened 2018-03-20 18:43 UTC
- VSCode Version: 1.22.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Create an npm script
2. Create a VSCode Tasks that references the `npm` script from step 1

For example, in my case, my Tasks is the following
```json
{
      "label": "Build Demo",
      "command": "npm",
      "type": "shell",
      "args": [
          "run build"
       ],
      "problemMatcher": []
},
```
and my npm script is the following
```json
"scripts": {
    "build": "ng build --prod",
}
```

In Stable version I see this
`> Executing task: npm run build-demo <`

but in Insiders version I see this 
`> Executing task: npm 'run build-demo' <` then `npm` just fail and shows up the `npm help`

#### The real issue
The problem is really because in my example, the `run build-demo` is wrapped in single quotes versus the Stable which is not. Why did that change since last version?

Does this issue occur when all extensions are disabled?: Yes

**Comment by ghiscoding** [comment] 2018-03-20 18:45
I don't think the issue that the bot found is the same since in my case it's really the wrap in single quote that causes the issue

**Comment by dbaeumer** [comment] 2018-03-20 21:25
@ghiscoding we fixed issue where args where not correctly quoted when containing blanks. You either need to build one command line or or need to sparate the one arg into two. So either
```json
{
      "label": "Build Demo",
      "command": "npm run build",
      "type": "shell",
      "problemMatcher": []
}
```
or
```json
{
      "label": "Build Demo",
      "command": "npm",
      "type": "shell",
      "args": [
          "run", "build"
       ],
      "problemMatcher": []
}
```

There should have been a message in the past in the task output channel that there is an issue with the blank in the arg and that a single command line should be used.

Closing the issue since this is now the expected behaviour.

**Closed by dbaeumer** 2018-03-20 21:25 UTC
Labels: tasks

**Comment by ghiscoding** [comment] 2018-03-20 23:34
Would have been nice to get an error in my JSON file from the start. Anyway thanks for the info, I will have to redo all my project tasks since I apparently didn't use them properly everywhere that is.

**Comment by dbaeumer** [comment] 2018-03-21 09:29
I agree that an error in the editor would have been nice here, but there should have been one in the task output channel.

I will definitely mention these quoting fixes in the release notes. We also added support to let users decided on the quoting.
