### ISSUE TITLE
Cursor jumps to various locations all by itself

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#68776] opened 2019-02-15 11:24 UTC
Issue Type: <b>Bug</b>

Latest VS Code Insiders build, with all extensions disabled. VS Code is basially totally broken for me. When  I try to enter some code, the cursor jumps to other locations in the file from time to time, so it is impossible to write code.
It seems that the cursors jumps to the beginning of the enclosing block most of the time.

Let me know if you need any additional info. I see this problem in JavaScript, Typescript, CSS files for sure.

VS Code version: Code - Insiders 1.32.0-insider (003521e715f2dbcf4f98be99a923097505859954, 2019-02-15T06:16:29.903Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (14.83GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|14%|

</details>Extensions disabled

**Comment by vvs** [comment] 2019-02-15 11:26
Some more info. This happens when the Outline Explorer section is expanded. I see that it is being refreshed, and when it does the cursor jumps!
When the Outline is closed, the editor is back to normal.

**Comment by chriswiley** [comment] 2019-02-19 07:13
I am having the same issue. I disabled all extensions to see if any of them were affecting it, but the only way to get the editor back to normal is to close the outline view. I think when the outline reference is created it moves the cursor to that reference.

**Comment by XcellMiguel** [comment] 2019-02-19 10:51
I just had this problem and spent a few time searching for the error : Outline enabled AND Outline's Follow Cursor enabled.
If I disable the "Follow cursor" setting it does not shift the cursor when typing, even if the Outline view is opened.

**Comment by chriswiley** [comment] 2019-02-20 13:42
@XcellMiguel I tried disabling "Follow cursor" but I still had the same problem.

**Comment by jduartedj** [comment] 2019-02-21 18:29
OMG, I just found this thread after 2 days of searching! I was about to report a bug in Visual Studio Code and this was suggested!
I'm going MAD over this, I was starting to get used to using the Outline.
The outline is not following the cursor, the cursor is following the outline O.O

**Comment by XcellMiguel** [comment] 2019-02-22 09:41
Well for some reason it was working without the "Follow cursor", but now it still jumps around.
Guess I have to close the outline for now.

**Comment by chriswiley** [comment] 2019-02-23 18:46
Same for me. It worked for a short time then started jumping again. The only short term solution is to close the outline.

**Comment by jrieken** [comment] 2019-02-25 09:34
This is a regression from migrating the outline to use the new tree widget. Sorry for the carnage.

**Comment by jduartedj** [comment] 2019-02-25 09:52
AH! Praise the Lord, Aleluia! 
From the changed milestone I understand it'll be deployed soon, correct?

**Comment by jrieken** [comment] 2019-02-25 09:56
Sure, sure! I was out ⛷ ⛰ last week, that's why this didn't happen yet.

**Comment by jduartedj** [comment] 2019-02-25 10:00
> Sure, sure! I was out ⛷ ⛰ last week, that's why this didn't happen yet.

Great, Awesome! Hope the trip went well! (so jealous!)

**Comment by jrieken** [comment] 2019-02-25 14:14
I actually cannot reproduce with todays insiders or from source. Can someone please try. @joaomoreno Did the tree change anything wrt to focus/selection events? This issue likely due to my workaround for https://github.com/Microsoft/vscode/issues/64743. I have a [`_treeFakeUIEvent`](https://github.com/Microsoft/vscode/blob/d2c6aa2ae00f50e4f79bee5cd02c9a5a6f155715/src/vs/workbench/contrib/outline/browser/outlinePanel.ts#L238) to know if it was the outline itself revealing an element or not. That must work or crazy jumping will happen...

**Comment by chriswiley** [comment] 2019-02-25 15:05
I turned back on outline after a couple updates and I could not reproduce the problem. I even set follow cursor and it still doesn't jump. I'll be playing around with it today and see if it starts jumping again.

Version: 1.32.0-insider (user setup)
Commit: 393b48d4a5de85b6fa1d2ad0a59588d6715e12ea
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment] 2019-02-25 15:28
@jrieken Up until last Friday, the tree would fire selection/focus change events even if the selected/focused element collection didn't actually change: https://github.com/Microsoft/vscode/commit/3946e3233baba153802680044654d605a03ce926#diff-a3991c7768fa71b7ffbcad3dea0b49c9

Maybe try to repro before that commit?

**Comment by jrieken** [comment] 2019-02-26 10:46
closing, this got fixed via 3946e32#diff-a3991c7768fa71b7ffbcad3dea0b49c9

**Closed by jrieken** 2019-02-26 10:46 UTC
Labels: bug, important, outline

**Comment by vvs** [comment] 2019-02-26 12:48
Hi, @jrieken , I can also confirm that the jumping cursor is fixed, even when I turn back the "Follow Cursor" option. But I noticed that the outline is not being scrolled into view when I move though my sources with "Follow Cursor" option enabled. I thought it worked that way before. Is this also a regression?

My expectation is that when I move my cursor to some function, the highlighted function name should be visible in the Outline view, and if the highlighted function is not currently visible, the view will be scrolled to make it visible to the user. Other views work that way (e.g., Open Editors view).

**Comment by jrieken** [comment] 2019-02-26 12:56
> I thought it worked that way before. Is this also a regression?

Yeah, that was another regression for which I have pushed a fixed today
