### ISSUE TITLE
Workspace Not Remembered

### ISSUE THREAD

**Issue by purplekrayons** [Microsoft/vscode#50846] opened 2018-05-30 22:34 UTC
Issue Type: <b>Bug</b>

**Summary:**

If you launch VS Code from the Windows Taskbar, or from the Start Menu, than any previously opened workspace, is automatically loaded. If right click a file from your computer, and click "Open with Code", than any previously opened workspace is lost, and you are forced to re-open the workspace again.

**Expected Behaviour:**

The workspace should automatically open even when opening a file in VS Code from the right-click context window.

**Steps to Reproduce:**

1. Open VS Code from either the Windows Taskbar, or from the Start Menu
2. Open/load in a Workspace (File > Open Workspace...)
3. Close VS Code
4. Open VS Code again from either the Windows Taskbar, or from the Start Menu -- you'll note it automatically opens the workspace again.

Up until this point, things work as expected.

5. Close VS Code
6. Right click a file on your desktop, a text file or anything, and click "Open with Code" from the context menu -- you'll find the workspace you previously opened/loaded, is now closed.

This is inconsistent and I can repeat this over and over with the same outcome.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (10.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-markdownlint|Dav|0.17.0
vscode-npm-script|eg2|0.3.4
php-debug|fel|1.12.3
gc-excelviewer|Gra|2.0.21
sftp|lix|1.1.11
mssql|ms-|1.3.1
python|ms-|2018.4.0
language-liquid|nei|0.0.3
highlight-matching-tag|vin|0.4.4

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-05-31 04:42
Duplicate of https://github.com/Microsoft/vscode/issues/15949

**Closed by bpasero** 2018-05-31 04:42 UTC
Labels: workbench-state
