### ISSUE TITLE
Scrolling does not work in markdown preview using touch screen

### ISSUE THREAD

**Issue by flyinggorilla** [Microsoft/vscode#14621] opened 2016-10-27 19:51 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: austin.code-gnu-global-0.2.1, donjayamanne.python-0.5.0, DotJoshJohnson.xml-1.6.0, hnw.vscode-auto-open-markdown-preview-0.0.3, ms-vscode.PowerShell-0.7.2, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:
1. edit "readme.md"
2. open markdown preview of readme.md
3. try to scroll the preview up/down with the finger (e.g. on a surface pro 4 touch display) and it wont work. however the source view on the left scrolls fine with the finger

**Comment by jrieken** [comment] 2016-10-28 06:36
@bpasero Is this a duplicate of the drag and drop issue? I remember that the workbench put some div above everything to allow editor arrangement

**Comment by bpasero** [comment] 2016-10-28 07:00
@jrieken I think this could be an Electron issue too. I remember @alexandrudima saying that something with touch scrolling was broken in the Chrome version we use, maybe he can chime in.

@flyinggorilla so you have a markdown preview open that shows a scrollbar and you can scroll clicking on the scrollbar but as soon as you try to use the mouse it does not scroll?

**Comment by flyinggorilla** [comment] 2016-10-28 08:18
@bpasero the markdown preview does scroll when using the cursor, and it does scroll with the mousepads two finger guesture and it does scroll with the mouse moving the scrollbar up and down. . however it does not scroll when using the finger on the touch screen.

**Comment by bpasero** [comment] 2016-10-28 08:34
Thanks for the clarification we should try to reproduce this with a touch screen.

**Closed** 2017-03-10 03:37 UTC
Labels: markdown, webview
