### ISSUE TITLE
vscode for web: custom view tree css style exception

### ISSUE THREAD

**Issue by godkite** [microsoft/vscode#164682] opened 2022-10-26 08:47 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.2
- OS Version: 

Steps to Reproduce:

1. open https://github.dev/xrxrjiang/test/pull/2
2. switch to github pr pannel, and expand `Commits` tree
3. Then custom view tree style exception
4. open developer tools, and find some tree view item element
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/13809539/197979284-f32a70e1-f021-41ee-b867-dd865f93b099.png">

@daviddossett , about this pr ? #160212

**Comment by alexr00** [comment] 2022-10-26 14:01
duplicate of https://github.com/microsoft/vscode/issues/163224

**Closed by alexr00** 2022-10-26 14:01 UTC
