### ISSUE TITLE
New Orange icon burns my eyes

### ISSUE THREAD

**Issue by neurot1cal** [Microsoft/vscode#36093] opened 2017-10-11 19:15 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.3

---

Steps to Reproduce:

1. Open VScode
2. Stare intensely at the orange icon.

Reproduces without extensions: Yes/No

**Comment by Smarticles101** [comment] 2017-10-11 19:17
agreed

**Comment by Reetik2000** [comment] 2017-10-11 19:19
The blue added to the simplicity which was what I really liked about VSCode. Blue and black looks calm, orange and blue makes me feel like I'm in prison and if I wanted to feel like that while I code, I would go back to using BlueJ. 😄

**Comment by jeffvandyke** [comment] 2017-10-11 19:25
:) My gripe with it is it now looks disturbingly close to Visual Studio's icon, instead of something more recognizable as the lightweight VSCode I've grown to love.

**Comment by franky47** [comment] 2017-10-11 20:39
Also, why the change in logo ? The infinite logo of the Visual Studio line was good, but now it looks like a weird fish about to get hooked..

**Comment by egamma** [comment] 2017-10-11 20:44
Duplicate of #35783

**Closed by egamma** 2017-10-11 20:44 UTC
Labels: duplicate

**Comment by Leedehai** [comment] 2017-10-13 03:21
Icons for VSCode 1.16 (the original one) is [here](https://github.com/Leedehai/nostalgia-vscode).
