### ISSUE TITLE
Hints popover: controls disappear the second time the popover is displayed

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#71692] opened 2019-04-03 23:15 UTC
- VSCode Version: 1.32.3
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Create a new typescript file
2. Type the following code:

```ts
function reverse<T>(items: T[]): T[] {
    var toreturn = [];
    for (let i = items.length - 1; i >= 0; i--) {
        toreturn.push(items[i]);
    }
    return toreturn;
}

var sample = [1, 2, 3];
var reversed = reverse(sample);
console.log(reversed); // 3,2,1

// Safety!
reversed[0] = '1';     // Error!
reversed = ['1', '2']; // Error!

reversed[0] = 1;       // Okay
reversed = [1, 2];     // Okay
```
 3. move the mouse over the first error: a popover will appear
 4. click on `peek problems`
 5. notice the nav arrows on the right of the popover  and the close button that appear
 6. click on the close button
 7. repeat steps 3/4

What happens?
===========
The popover that is opened the second time does not have the arrows/close buttons

What should happen?
===============

The popover should have the close button/arrows to navigate between each problem.

Video: https://www.youtube.com/watch?v=35mdvNlGPPw&feature=youtu.be

**Comment by sandy081** [comment] 2019-04-04 20:34
Duplicate of https://github.com/Microsoft/vscode/issues/70138

**Closed** 2019-04-04 20:34 UTC
Labels: *duplicate, editor-error-widget
