### ISSUE TITLE
Moving mouse over long lines in Javascript files uses 100% CPU for several seconds, and freezes

### ISSUE THREAD

**Issue by WilliamParks** [microsoft/vscode#106699] opened 2020-09-15 00:05 UTC
Version: 1.50.0-insider
Commit: cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
Date: 2020-09-12T00:58:03.476Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-47-generic snap

(reproduces on a friend's Windows 10 version as well)
This started happening on the main version of vscode ~3 days ago.

Sample: Needs to be renamed to .js 
[foo.txt](https://github.com/microsoft/vscode/files/5221679/foo.txt)

Steps to Reproduce:

1. Open a file with one long line. The file needs to have the JS extension (sample attached, but needs to have its extension changed to .js, as Github doesn't allow .js to be attached).
2. Click one spot in the file, and try to highlight a section.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment] 2020-09-16 12:11
Very interestingly, I don't see slowness in tokenizing the line, but there is significant slowness caused by hit testing to discover the mouse position:

![image](https://user-images.githubusercontent.com/5047891/93335279-77c3fc80-f826-11ea-804e-651e05c4f7e4.png)

**Comment by alexdima** [comment] 2020-09-16 12:12
I cannot reproduce if I execute with `--disable-features=LayoutNG`.

fyi @deepak1556

**Comment by alexdima** [comment] 2020-09-16 12:50
Here is a repro page -- clicking and selecting the text in Firefox & Safari is fast, while it is slow in Chromium  -- https://jsfiddle.net/eahj49d8/

**Comment by alexdima** [comment] 2020-09-16 13:44
I have created https://bugs.chromium.org/p/chromium/issues/detail?id=1128937

**Comment by deepak1556** [comment] 2020-09-16 13:53
Awesome, thanks @alexdima

**Comment by lramos15** [comment] 2021-01-28 20:45
I do not see my CPU usage change much with this file, but opening the file and selecting anything freezes VS Code for me for a couple of seconds.

**Comment by deepak1556** [comment] 2021-06-28 15:57
Upstream changes are available in latest insiders, closing for another round of verification.

**Comment by lramos15** [comment] 2021-07-01 14:01
@deepak1556 I'm not sure what level of performance we're looking for here. On my mac it is super sluggish selecting and clicking the mouse to different sections of the line still freezes the editor

**Comment by roblourens** [comment] 2021-07-02 01:14
I see this 

![image](https://user-images.githubusercontent.com/323878/124206352-0d6c0800-da98-11eb-8259-5e08253035e8.png)

Same stack, much faster than the original example but still slow. Is there anything else to be done or is that just as good as the browser can get?

**Comment by alexdima** [comment] 2021-07-02 12:52
Firefox can do it quicker (about 20ms):

<img width="1030" alt="Screen Shot 2021-07-02 at 14 50 38" src="https://user-images.githubusercontent.com/5047891/124277248-1f57b480-db45-11eb-82b5-1040916cf7f3.png">

**Comment by alexdima** [comment] 2021-07-02 12:57
Oh yeah, this is nowhere near what it was. I've downloaded VS Code 1.48 (one version before updating to Electron 9) and profiled moving the mouse:

![image](https://user-images.githubusercontent.com/5047891/124277822-c63c5080-db45-11eb-99c3-1f433503e8c7.png)

**Comment by alexdima** [comment] 2021-10-15 12:09
@deepak1556 Do you have any suggestion with what to do here? The upstream issue got fixed, but the perf issue remains, the `caretRangeFromPoint` call is still 100x slower for the same underlying HTML.

**Closed** 2023-12-12 05:08 UTC
Labels: bug, upstream, freeze-slow-crash-leak, editor-rendering, upstream-issue-linked, upstream-issue-pending
