### ISSUE TITLE
Very Slow

### ISSUE THREAD

**Issue by Sasicumaar** [Microsoft/vscode#52013] opened 2018-06-15 10:18 UTC
Latest version is very slow i cant work as normal ,JS files not loading,Intellisense not working

**Comment by Sasicumaar** [comment] 2018-06-15 10:18
Latest version is very slow i cant work as normal ,JS files not loading,Intellisense not working

**Comment by abhirathore2006** [comment] 2018-06-15 10:32
same here

**Comment by RMacfarlane** [comment] 2018-06-15 17:03
Duplicate of https://github.com/Microsoft/vscode/issues/51819

**Closed** 2018-06-15 17:19 UTC
Labels: editor
