### ISSUE TITLE
Auto update for module imports on rename is changing many npm imports to some obscure path

### ISSUE THREAD

**Issue by liranh85** [Microsoft/vscode#54717] opened 2018-07-20 11:19 UTC
Issue Type: <b>Bug</b>

After renaming a file in the project (a redux module this time), 17 other files in the project were automatically modified by VSCode, each file having most of its npm imports changed to some obscure path.

For example, in one file, `import { connect } from 'react-redux'` was changed to `import { connect } from '../../../../../../../Library/Caches/typescript/2.9/node_modules/@types/react-redux'`

Please advise.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
indent4to2|Com|0.1.2
vscode-quick-select|dba|0.2.5
reasonml|fre|1.0.38
beautify|Hoo|1.3.2
velocity|luq|0.7.1
rainbow-csv|mec|0.4.2
dotenv|mik|1.0.1
vscode-code-outline|pat|0.2.1
convert-css-in-js|pau|1.1.3
code-settings-sync|Sha|3.0.0
vscode-import-cost|wix|2.7.2
change-case|wma|1.0.0

</details>

**Comment by mjbvz** [comment] 2018-07-20 18:31
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-20 18:31 UTC
