### ISSUE TITLE
Allow files.eol as language specific option

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#39051] opened 2017-11-23 17:31 UTC
- VSCode Version:  1.18.1
- OS Version: Windows 10

Steps to Reproduce:

These are my current user settings
```json
{
    "explorer.openEditors.visible": 0,
    "workbench.activityBar.visible": false,
    "editor.minimap.enabled": false,
    "editor.renderWhitespace": "all",
    "[php]": {
        "files.eol": "\n",
        "files.encoding": "utf8",
        "editor.tabSize": 4,
        "editor.insertSpaces": true,
        "files.insertFinalNewline": true,
        "files.trimFinalNewlines": true
    }
}
```
2. The setting  **"files.eol": "\n"** isn't working. Every time I create or open a PHP file I want the line setting to be LF but Visual Code continues to put CRLF. Also I observe a strange error that I can't understand as we can observe on the image. 
![captura de ecra 5](https://user-images.githubusercontent.com/17036103/33184262-97fdae7a-d073-11e7-98ba-d6ca936507c9.png)

My conclusion is that the end of line option isn't working properly when using a specific language.

**Comment by joaomoreno** [comment] 2017-11-23 21:52
This is JSON. You need to escape that backslash with another backslash:

```
"\\n"
```

**Comment by joaomoreno** [comment] 2017-11-23 21:53
Actually I'm wrong... sending it to the right person.

**Comment by bpasero** [comment] 2018-09-14 16:15
Challenge is that [when the model is being created](https://github.com/Microsoft/vscode/blob/c77cc9898f389bd50d309d0162390fa2fd2e69d1/src/vs/editor/common/services/modelServiceImpl.ts#L500), it just gets `text/plain` as mode because the actual mode is a promise that can load later. Thus, configuration that relies on the proper mode to be there will not be acknowledged initially.

**Comment by anthonyvdotbe** [comment] 2019-09-13 12:53
This seems to be a duplicate of #34876

**Comment by aeschli** [comment] 2019-10-08 16:08
Fixed by https://github.com/microsoft/vscode/pull/82101

**Closed by aeschli** 2019-10-08 16:08 UTC
Labels: editor-core, feature-request, file-io
