### ISSUE TITLE
Opening bash on ssh remote development

### ISSUE THREAD

**Issue by TheDodo24** [microsoft/vscode#177981] opened 2023-03-22 08:20 UTC
Type: <b>Bug</b>

If you're working on a remote server via SSH connection in VS Code and you want to open the bash of the linux server you're working on everytime there comes an error:
"The terminal process failed to launch: A native exception occurred during launch (posix_spawn failed: No such file or directory)."
In VS Code 1.74.3 this error doesn't exists.
The linux machine is running with Nixos 22.05 (Quokka) 

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.30

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (8.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vmcore|
|OS|Linux x64 5.15.30|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (6 x 2693)|
|Memory (System)|31.36GB (7.32GB free)|
|VM|100%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Nix|bbe|1.0.1
vsc-material-theme|Equ|33.7.0
vsc-material-theme-icons|equ|2.7.3
vscode-language-pack-de|MS-|1.76.2023030809
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
jinja|who|0.0.8
isort|ms-|2022.8.0
vscode-pylance|ms-|2023.3.20
vscode-jupyter-slideshow|ms-|0.1.5

(2 theme extensions excluded)

</details>

**Comment by eleanorjboyd** [comment] 2023-03-22 17:01
Can you include full window and remote-ssh logs? Go to view -> output and select windows and remote-ssh logs from the dropdown on the right. What version of the remote-ssh extension do you have? And to confirm you have a local windows machine and remote linux machine right?

**Comment by TheDodo24** [comment] 2023-03-23 08:05
If I try to open the terminal there are no window logs.
Window logs at VS Code startup:

`2023-03-23 09:01:45.066 [info] Electron sandbox mode is enabled!
2023-03-23 09:01:45.084 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-23 09:01:45.085 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-23 09:01:45.085 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-23 09:01:45.085 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-23 09:01:45.348 [info] Invoking resolveAuthority(ssh-remote)...
2023-03-23 09:01:45.348 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
2023-03-23 09:01:45.779 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][430ms] invoking...
2023-03-23 09:01:46.756 [error] [Extension Host] (node:13340) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created)
2023-03-23 09:01:46.772 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1421ms] returned 127.0.0.1:60403
2023-03-23 09:01:46.772 [info] resolveAuthority(ssh-remote) returned '127.0.0.1:60403' after 1422 ms
2023-03-23 09:01:46.773 [info] Creating a socket (renderer-Management-bcb4ee6f-5e3f-410e-95d7-0d2f42f19a51)...
2023-03-23 09:01:46.773 [info] Creating a socket (renderer-ExtensionHost-c262291f-ba47-42e5-9ff1-08b28beb6a6e)...
2023-03-23 09:01:46.783 [info] Creating a socket (renderer-Management-bcb4ee6f-5e3f-410e-95d7-0d2f42f19a51) was successful after 10 ms.
2023-03-23 09:01:46.801 [info] Creating a socket (renderer-ExtensionHost-c262291f-ba47-42e5-9ff1-08b28beb6a6e) was successful after 28 ms.
2023-03-23 09:01:48.132 [info] [perf] Render performance baseline is 32ms
`
Same at Remote-SSH logs.
Remote-SSH logs at startup:

`[09:03:13.690] Log Level: 2
[09:03:13.693] SSH Resolver called for "ssh-remote+vmcore", attempt 1
[09:03:13.693] "remote.SSH.useLocalServer": false
[09:03:13.694] "remote.SSH.showLoginTerminal": false
[09:03:13.694] "remote.SSH.remotePlatform": {"vmcore":"linux"}
[09:03:13.694] "remote.SSH.path": undefined
[09:03:13.695] "remote.SSH.configFile": undefined
[09:03:13.695] "remote.SSH.useFlock": true
[09:03:13.695] "remote.SSH.lockfilesInTmp": false
[09:03:13.695] "remote.SSH.localServerDownload": auto
[09:03:13.695] "remote.SSH.remoteServerListenOnSocket": false
[09:03:13.696] "remote.SSH.showLoginTerminal": false
[09:03:13.696] "remote.SSH.defaultExtensions": []
[09:03:13.696] "remote.SSH.loglevel": 2
[09:03:13.696] "remote.SSH.enableDynamicForwarding": true
[09:03:13.696] "remote.SSH.enableRemoteCommand": false
[09:03:13.696] "remote.SSH.serverPickPortsFromRange": {}
[09:03:13.697] "remote.SSH.serverInstallPath": {}
[09:03:13.700] VS Code version: 1.77.0-insider
[09:03:13.700] Remote-SSH version: remote-ssh@0.98.0
[09:03:13.700] win32 x64
[09:03:13.705] SSH Resolver called for host: vmcore
[09:03:13.705] Setting up SSH remote "vmcore"
[09:03:13.710] Using commit id "a5bd844beddef8ca5f9ccfdb1bb7b3b4f8e5204e" and quality "insider" for server
[09:03:13.714] Install and start server if needed
[09:03:13.717] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[09:03:13.724] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[09:03:13.724] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[09:03:13.727] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[09:03:13.728] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[09:03:13.731] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[09:03:13.731] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[09:03:13.735] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[09:03:13.735] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[09:03:13.741] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[09:03:13.741] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[09:03:13.830] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[09:03:13.848] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 60419 vmcore bash
[09:03:13.852] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:03:14.473] > ]0;C:\WINDOWS\System32\cmd.exe
[09:03:14.474] Got some output, clearing connection timeout
[09:03:14.607] > 29a702292c07: running
[09:03:14.628] > Warning: Can't find libstdc++.so or ldconfig, can't verify libstdc++ version    
> Acquiring lock on /home/domenic/.vscode-server-insiders/bin/a5bd844beddef8ca5f9c
> cfdb1bb7b3b4f8e5204e/vscode-remote-lock.domenic.a5bd844beddef8ca5f9ccfdb1bb7b3b4
> f8e5204e
[09:03:14.644] > Found existing installation at /home/domenic/.vscode-server-insiders/bin/a5bd844
> beddef8ca5f9ccfdb1bb7b3b4f8e5204e...
> Checking /home/domenic/.vscode-server-insiders/.a5bd844beddef8ca5f9ccfdb1bb7b3b4
> f8e5204e.log and /home/domenic/.vscode-server-insiders/.a5bd844beddef8ca5f9ccfdb
> 1bb7b3b4f8e5204e.pid for a running server
> Looking for server with pid: 1993792
[09:03:14.661] > Found running server...
> 
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> nse) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> atement).
> *
> 
> Checking server status on port 39951 with wget
> 29a702292c07: start 
> SSH_AUTH_SOCK====   
> DISPLAY====
> webUiAccessToken====
> listeningOn==39951==
> osReleaseId==nixos==
> arch==x86_64==
> tmpDir==/run/user/9030==
> platform==linux==
[09:03:14.667] > 
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==a11a1aa1-aa11-1111-a1a1-11a1a111a111==
> 29a702292c07: end
[09:03:14.668] Received install output:  
SSH_AUTH_SOCK====   
DISPLAY====
webUiAccessToken====
listeningOn==39951==
osReleaseId==nixos==
arch==x86_64==
tmpDir==/run/user/9030==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==a11a1aa1-aa11-1111-a1a1-11a1a111a111==

[09:03:14.668] Remote server is listening on 39951
[09:03:14.668] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":39951},"osReleaseId":"nixos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/9030","platform":"linux","connectionToken":"a11a1aa1-aa11-1111-a1a1-11a1a111a111"},"installUnpackCode":""}
[09:03:14.673] Starting forwarding server. localPort 60425 -> socksPort 60419 -> remotePort 39951
[09:03:14.674] Forwarding server listening on 60425
[09:03:14.674] Waiting for ssh tunnel to be ready
[09:03:14.675] [Forwarding server 60425] Got connection 0
[09:03:14.677] Tunneled 39951 to local port 60425
[09:03:14.677] Resolved "ssh-remote+vmcore" to "127.0.0.1:60425"
[09:03:14.689] ------




[09:03:14.710] [Forwarding server 60425] Got connection 1
[09:03:14.730] [Forwarding server 60425] Got connection 2
`

Remote - SSH Extension Version v0.98.0
My local machine is windows and the remote one is a linux machine right.

**Comment by meganrogge** [comment] 2023-03-23 16:14
Thanks for that info.

Can you do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by heikopanjas** [comment] 2023-03-23 16:46
Sure. Not sure though what you mean by `while creating a terminal`.


[exthost.log](https://github.com/microsoft/vscode/files/11053455/exthost.log)

**Comment by meganrogge** [comment] 2023-03-23 17:21
Looks like those logs are from the extension host. We'll need the `Pty Host` logs

**Comment by heikopanjas** [comment] 2023-03-23 17:30
[ptyhost.log](https://github.com/microsoft/vscode/files/11053912/ptyhost.log)

Sorry, didn't know that.

**Comment by meganrogge** [comment] 2023-03-23 18:05
Okay thanks for that. It looks like the shell path we're using for `bash` is `/usr/bin/bash`. I also see that your `$SHELL` is `/usr/bin/zsh`. Do both of those exist? What happens if you run `/usr/bin/bash` directly in a terminal?

**Comment by meganrogge** [comment] 2023-04-05 16:14
Do you know if that path is a symlink?

Also, @deepak1556 any thoughts?

**Comment by heikopanjas** [comment] 2023-04-05 17:25
It's not. 

UPDATE: I was trying to reproduce the issue and while I was connecting to the remote machine via ssh, the vscode-server on the remote machine was updated. Now the connection to the remote machine works flawlessly as it was before (I tried several times). 

I'm adding the most recent log file.

Thank you very much and please excuse me for causing so much trouble.

[ptyhost.log](https://github.com/microsoft/vscode/files/11161481/ptyhost.log)

**Comment by meganrogge** [comment] 2023-04-05 20:54
Ok, I'll close this for now. Lmk if you see an issue again

**Closed by meganrogge** 2023-04-05 20:54 UTC
Labels: remote, terminal-process
