### ISSUE TITLE
does not support the proxy setting

### ISSUE THREAD

**Issue by arbindchandra** [microsoft/vscode#142377] opened 2022-02-07 07:56 UTC
Issue Type: <b>Bug</b>

Getting an error while attaching vs code to docker container. 
[4950 ms] Exit code 1
[4950 ms] Installing VS Code Server for commit 5554b12acf27056905806867f251c859323ff7e9
[4951 ms] Start: Downloading VS Code Server
[4951 ms] 5554b12acf27056905806867f251c859323ff7e9 linux-x64 stable 
[8926 ms] Error: connect ECONNREFUSED 152.199.19.160:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[8926 ms] Exit code ECONNREFUSED

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by gjsjohnmurray** [comment] 2022-02-07 08:06
Looks like a duplicate of #142201

**Comment by chrmarti** [comment] 2022-02-07 13:22
Continuing in https://github.com/microsoft/vscode/issues/142201.

**Closed by chrmarti** 2022-02-07 13:22 UTC
Labels: triage-needed, new release
