### ISSUE TITLE
Focus vanishes after refactoring in GO

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#9314] opened 2016-07-15 06:16 UTC
- VSCode Version: 1.3.1 Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open a GO project
2. Select a symbol
3. Press F2
4. Rename symbol
5. Symbol is renamed, but focus is somewhere outside the editor.

You can press 18 times TAB or 5 times Shift+TAB to get the focus back to where it was.
ALso Ctrl+TAB two times works.

**Comment by weinand** [comment] 2016-07-15 10:13
@DasJott I could not reproduce this.
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by kieferrm** [comment] 2016-07-21 14:38
Closing due to missing response.

**Closed by kieferrm** 2016-07-21 14:38 UTC
Labels: needs more info, not-reproducible

**Comment by DasJott** [comment] 2016-07-22 06:44
I am sorry, I had too much to do the last days.
The issue is still existing.
Additionally not only the focus is away but the editor is not updated. So the renaming was made, but you have to change the editor and go back to see the changes.

If I start with --disable-extensions, F2 is not doing anything at all.

Can someone reopen this issue?
