### ISSUE TITLE
Autocomplete shows node, node, node, node for import

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#41864] opened 2018-01-19 12:16 UTC
- VSCode Version: Code - Insiders 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 2017-12-21T16:27:29.385Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
sort-lines|Tyr|1.4.1
react-pure-to-class-vscode|ang|1.1.2
markdown-emoji|bie|0.0.7
vscode-eslint|dba|1.4.4
gitlens|eam|7.5.5
tslint|eg2|1.0.24
prettier-vscode|esb|1.1.2
flow-for-vscode|flo|0.7.3
intellij-idea-keybindings|k--|0.2.18
debugger-for-chrome|msj|4.0.0
annotator|ryu|0.11.0
vscode-fileutils|sle|2.7.1
code-spell-checker|str|1.6.2

---

Steps to Reproduce:

I don't know how I can in this state but thought it was important to log an issue.  Let me know if you can't reproduce.

![image](https://user-images.githubusercontent.com/2301847/35150492-cc4f91c6-fcd7-11e7-91a6-26489d2d56ea.png)
![image](https://user-images.githubusercontent.com/2301847/35150526-ef6aa5e2-fcd7-11e7-9650-56a0ac6954d5.png)

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2018-02-12 19:17
Thanks! I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/13373

**Closed by mjbvz** 2018-02-12 19:17 UTC
