### ISSUE TITLE
Commit message losing focus

### ISSUE THREAD

**Issue by nelsonec87** [microsoft/vscode#92734] opened 2020-03-15 19:53 UTC
Issue Type: <b>Bug</b>

Recently the commit message input started to loose focus while I'm typing the message, usualy  right after I add the files to the commit. If I keep typing it start to filter the files filter. It's pretty annoying :)

VS Code version: Code - Insiders 1.43.0-insider (5996fb81591e92fd0c547dc45e3f0350026d5962, 2020-03-06T23:17:52.931Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.82GB (6.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
dotenv|mik|1.0.1
vscode-docker|ms-|1.0.0
remote-wsl|ms-|0.42.3
vscode-scss-formatter|sib|1.4.3

</details>

**Comment by Romalouz** [comment] 2020-03-17 18:44
Same issue experienced since the latest update.
It happens when adding a file using the + and starting to type the commit message.
Focus get lost when the Git view is done with the refresh.

**Comment by jschwanz** [comment] 2020-03-17 20:09
Same issue.

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by DonPavlov** [comment] 2020-03-19 19:02
To specify how the bug actually occurs:

* Add files into staging
* Before files are shown in the staging area, start typing the commit message, because it is already in focus for typing
* after the files are added into staging, the focus gets lost and the typed in text is used for search in the commitable files

**Comment by icharge** [comment] 2020-03-22 08:19
Same to me.

```
Version: 1.43.1 (user setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by mck1117** [comment] 2020-03-24 23:33
@DonPavlov yes - these are the exact steps that cause it for me too on:

Version: 1.43.0 (system setup)
Commit: 78a4c91
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by pvdstel** [comment] 2020-03-25 13:40
This appears to be a duplicate of #92401. And I agree, it's mildly infuriating.

**Comment by arielkuzminski** [comment] 2020-03-26 15:36
Same here. It's the most annoying thing in history!!! Fix it please....

**Comment by PairedPrototype** [comment] 2020-03-26 23:53
I also have this problem. I've noticed it happening since version `1.43.0`. Before that, I could type my commit message without it ever losing input focus on the message box.

<details>
<summary>Bug report template</summary>
<p>

- VSCode Version: 1.43.2 (system setup)
- OS Version: Windows_NT x64 10.0.18363
- Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
- Date: 2020-03-24T07:38:38.248Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0

Steps to Reproduce:

1. Launch Code in a directory with a git repository
1. Make a change i.e. add a new file or edit a file
1. Open the source control tab
1. Stage the changed file
1. Click inside the commit message box 
1. Begin typing a commit message before Code has detected the file been staged
1. Observe focus switching to the Changes panel and an active filter now present


Does this issue occur when all extensions are disabled?: Yes

</p>
</details>

**Comment by iansan5653** [comment] 2020-03-27 15:39
Yes, this is a duplicate of #92401. Please go :+1: that one so this gets noticed.

**Closed** 2020-03-31 15:11 UTC

**Comment by joelharkes** [comment] 2020-04-29 08:32
IS it fixed or not? or will we have to live with this for the rest of our lives?

**Comment by iansan5653** [comment] 2020-04-29 15:41
@joelharkes This is fixed in the latest (March) release.
