### ISSUE TITLE
Extensions - infinite update

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#53389] opened 2018-07-01 07:27 UTC
- VSCode Version: 1.25.0-ins
- OS Version: win7x64

![ext - update](https://user-images.githubusercontent.com/24613274/42132079-3c8a6ee0-7d19-11e8-85c6-8df1d41b0f6d.gif)

Is that ok?

**Comment by sandy081** [comment] 2018-07-02 09:46
Duplicate of #53426

**Closed** 2018-07-02 09:46 UTC
Labels: *duplicate, extensions
