### ISSUE TITLE
Is that possible [color theme] mapping to [opened file type] ?

### ISSUE THREAD

**Issue by krishna116** [microsoft/vscode#90772] opened 2020-02-16 02:10 UTC
Issue Type: <b>Feature Request</b>

when I open a C++ file I wish it using a "white color theme";
when I open a javascript file I with it using a "dark color theme";
when I open a "xxx.g4" file I with it using another color theme...;
Is that possible [color theme] mapping to [opened file type] ?

thanks.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by tomByrer** [comment] 2020-02-16 05:54
You could edit a theme that completely revamped all colors based on language.
If you go to `Command Palliate`, then choose `Developer: Inspect Editor Tokens & Scopes`, you can look at all the tokens you need to edit.

**Comment by aeschli** [comment] 2020-02-18 10:22
duplicate of https://github.com/microsoft/vscode/issues/20652

**Closed by aeschli** 2020-02-18 10:22 UTC
