### ISSUE TITLE
layoutEditorGroups keybindings do wrong thing when the editors are already in the desired layout

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50731] opened 2018-05-29 18:47 UTC
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

Keybinding:

```json
{
	"key": "ctrl+0",
	"command": "layoutEditorGroups",
	"args": {
		"orientation": 1,
		"groups": [
			{ "size": 0.2 },
			{ "size": 0.6 },
			{ "size": 0.2, "groups": [{"size": 0.4}, {"size": 0.6}] }
		]
	}
}
```

First ctrl+0:

![image](https://user-images.githubusercontent.com/2193314/40678596-c9b0b28c-6335-11e8-9b13-083a62d29ee9.png)

Second ctrl+0:

![image](https://user-images.githubusercontent.com/2193314/40678609-d302e8e6-6335-11e8-88fd-35400fd3afdb.png)

**Comment by bpasero** [comment] 2018-05-30 04:38
Duplicate of https://github.com/Microsoft/vscode/issues/50674

**Closed by bpasero** 2018-05-30 04:38 UTC
Labels: bug, insiders, workbench-grid
