### ISSUE TITLE
Predefined variables didn't work with bash

### ISSUE THREAD

**Issue by liaoyeguo** [microsoft/vscode#74317] opened 2019-05-25 06:55 UTC
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

When `terminal.integrated.shell.windows` is set to `bash.exe`, VS code predefined variable in task.json didn't work correctly. For example, this is my task.json to build active cpp file.
```
{
  "tasks": [
    {
      "type": "shell",
      "label": "g++.exe build active file",
      "command": "g++",
      "args": [
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}.exe"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ],
  "version": "2.0.0"
}
```
When I try to build cpp file, g++ throw an error.
```
> Executing task: g++ -g c:\project\t.cpp -o c:\project/t.exe <

g++.exe: error: c:projectt.cpp: No such file
or directory
g++.exe: fatal error: no input files
compilation terminated.
The terminal process terminated with exit code: 1
```
I guess this may be caused by the backslash used in VS code predefined variable. How can I fix this?

**Comment by alexr00** [comment] 2019-05-27 12:47
On Windows we assume Windows path separators. If you are interested in developing in a Linux environment on Windows checkout https://code.visualstudio.com/docs/remote/remote-overview 
Otherwise this is dupe of https://github.com/microsoft/vscode/issues/38381

**Closed by alexr00** 2019-05-27 12:47 UTC
Labels: tasks

**Comment by heartacker** [comment] 2019-06-30 06:52
I change my default console from cmd.exe to git-bash.exe, that why it fail, but, Is there any that can fix this problem between diff platform about path.
