### ISSUE TITLE
Marker (circle) is not removed when removing breakpoint

### ISSUE THREAD

**Issue by torjuss** [Microsoft/vscode#38497] opened 2017-11-16 10:33 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
react-native-react-redux|EQu|1.4.1
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
vscode-redux-devtools|jin|0.0.11
resharper9-keybindings|ms-|1.1.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1

---

Steps to Reproduce:

1. When I try to remove an existing breakpoint by clicking on the red circle in my code the red marker is not removed from the code line.
2. However the breakpoint is actually removed in the list of breakpoints. So it seems like this is only a graphics update error and that breakpoints work.

Reproduces without extensions: Yes/No

**Comment by torjuss** [comment] 2017-11-16 10:35
Just to clarify: I had no issues until I installed the latest update. Not certain if I have skipped some previous updates, but I use VS Code dialy and update often.

**Comment by weinand** [comment] 2017-11-16 10:56
Duplicate of #37880. Please try Insiders. Fix will appears in Stable soon.

**Closed by weinand** 2017-11-16 10:56 UTC
Labels: debug, new release
