### ISSUE TITLE
Bizarre frosting over of visual interface

### ISSUE THREAD

**Issue by Baldur-Dash** [microsoft/vscode#122748] opened 2021-04-30 18:23 UTC
We have written the needed data into your 
Issue Type: <b>Performance Issue</b>

This problem occurs whenever I use the editor. It's easier to show in a screenshot, but thin white lines like a spiderweb grow out of the text and other visual elements and it looks like a window frosting over. When I move the cursor over the lines they vanish. I've tried changing the settings on my Nvidia but that hasn't changed it.  Any help would be greatly appreciated . Thanks!

![image](https://user-images.githubusercontent.com/64432065/116737674-b9b54380-a9ae-11eb-9572-631eb67df3cb.png)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.48GB free)|
|Process Argv|--crash-reporter-id 3c382507-ff1c-443a-a385-2724b55a202d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   115	 18796	code main
    0	    92	 17220	   shared-process
    0	    68	 23100	     ptyHost
    0	     5	 23480	       C:\Windows\System32\cmd.exe
    0	     7	 23988	       console-window-host (Windows internal process)
    0	    25	 22680	   crashpad-handler
    0	    40	 22812	   utility
    0	   197	 23516	   window (Untitled (Workspace) - Visual Studio Code)
    0	    15	 17116	     watcherService 
    0	    11	 23376	       console-window-host (Windows internal process)
    0	   118	 24920	     extensionHost
    0	   115	  5172	       electron_node tsserver.js 
    0	    88	 23388	         electron_node typingsInstaller.js typesMap.js 
    0	   123	  7892	       "C:\Users\12089\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\12089\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=24920
    0	    78	 18328	       "C:\Users\12089\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\12089\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=24920
    0	    72	 19972	       "C:\Users\12089\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\12089\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=24920
    0	    69	 22940	       electron_node serverMain.js 
    0	   112	 24004	       electron_node tsserver.js 
    0	   263	 24144	   gpu-process
    0	    85	 25236	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled (Workspace) - Visual Studio Code)
|    Folder (maggiePortfolio): 9 files
|      File types: jpg(5) css(1) html(1) txt(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-babel-coloring|dza|0.0.4
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment] 2021-04-30 19:21
/duplicate of #92379 which is some upstream issue

Should work with `--disable-gpu` flag or more permanent disable https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration 

Also check https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687 look like Nvidia drivers may also affect rendering of Electron apps, however looks like it doesn't help in your case.

**Closed** 2021-04-30 19:22 UTC
Labels: *duplicate
