### ISSUE TITLE
Php syntax highlighting in dark (defaul dark) theme

### ISSUE THREAD

**Issue by Andi-Lo** [Microsoft/vscode#7483] opened 2016-06-09 15:19 UTC
- VSCode Version: 1.2.0
- OS Version: Win10

Steps to Reproduce:

1. Create a new file e.g. test.php
2. Copy this:

```html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<title>Test</title>
</head>
<body>

<?php $someVar = 'hello'; ?>

<?php $someVar = 'hello'; 

?>

</body>
</html>
```

3. Set the language mode to PHP
4. Select Theme: Dark+ (default dark)
5. You will notice now, that there is some miss matching between a one line of code or when you expand it.

I'm not sure if this just a problem with the theme, how ever the problem appeared when I installed to update to version 1.2 today.

**Comment by pufanalexandru** [comment] 2016-06-10 06:51
After updating to 1.2, I've lost PHP highlighting completely
![screenshot_1](https://cloud.githubusercontent.com/assets/10388839/15956394/e929c192-2ef0-11e6-9553-76e2d3d41847.png)

**Comment by aeschli** [comment] 2016-06-13 07:50
@pufanalexandru Your issue seems to be a dup of #7245. Please see the instructions in there. Try to start without extensions to find out what cases the issue.

**Comment by pufanalexandru** [comment] 2016-06-13 08:01
@aeschli yes, it seems that this was the problem. Thanks!

**Comment by Andi-Lo** [comment] 2016-06-13 09:08
@aeschli I think my problem is a little different. I did not lose complete syntax highlighting like @pufanalexandru did. For me the problem is just when the <?php ?> code is one line of code.

I disabled the extensions and restarted VSC but the problem persists.
You can see what I mean in that screenchast:

![phpbug](https://cloud.githubusercontent.com/assets/7545568/16002247/f2e26d16-3156-11e6-8224-6a3626dfd2bd.gif)

**Comment by aeschli** [comment] 2016-06-15 14:09
@Andi-Lo I see what you mean, I can reproduce it. Looks like a minor issue to me, so removed the 'important' tag. Do you agree?

**Comment by Andi-Lo** [comment] 2016-06-15 18:24
I agree :+1: it is not the biggest of a deal

**Comment by aeschli** [comment] 2016-07-19 14:42
duplicate of #8739

**Closed** 2016-07-19 14:45 UTC
Labels: bug, php
