### ISSUE TITLE
Emmet change direction modifier doesn't work

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#96977] opened 2020-05-05 10:21 UTC
- VSCode Version: Insiders 1.45.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. On an HTML file, write `div>li.item$@-3*5` and press `Tab`
2. Notice that the change direction modifier `@-` did not apply

Does this issue occur when all extensions are disabled? Yes

**Comment by rzhao271** [comment] 2020-10-05 20:55
Duplicate of #69168

**Closed by rzhao271** 2020-10-05 20:55 UTC
Labels: emmet
