### ISSUE TITLE
Unable to commit from VSCode UI with MiniConda and Pre-Commit

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [microsoft/vscode#169100] opened 2022-12-14 07:48 UTC
Type: <b>Bug</b>

Manually running pre-commit from the python or powershell terminal is working, both on the base and the projects custom conda environment (environment have pre-commit, pytest, mypy,... installed). However a commit from VSCodes UI is not possible, if VSCode was started normally. 

**It only works, if VSCode is started using the Anaconda Prompt!**
Seems like a different python interpreter is used during the pre-commit checks otherwise. Weirdly enough project code runs normally with the correct conda environment being enabled before runs. 

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.02GB free)|
|Process Argv|--crash-reporter-id 9a5c97e3-ae8b-4fd1-86a4-75c3456e616d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by bpasero** [comment] 2022-12-14 16:04
How come the version of the python interpreter can prevent Git commit from running?

**Comment by brettcannon** [comment] 2022-12-14 19:34
This is a duplicate of https://github.com/microsoft/vscode-python/issues/10165 .

> How come the version of the python interpreter can prevent Git commit from running?

https://pre-commit.com/ is a project that lets you configure commit hooks for git. Some of them require Python to run and if you don't have that set up appropriately before you run your hooks, they can fail.

And in this specific case, conda environments **must** be activated to work appropriately or run via `conda run`. Since the Python extension doesn't participate in git hooks, git just runs `python` which can easily fail in this situation as `python` may not point at the right binary or have the environment set up as required (in the case of conda).

**Closed by brettcannon** 2022-12-14 19:34 UTC
Labels: info-needed
