### ISSUE TITLE
Add a command to "Toggle Side Bar" without moving focus

### ISSUE THREAD

**Issue by lkarlslund** [Microsoft/vscode#46092] opened 2018-03-19 08:59 UTC
Issue Type: <b>Bug</b>

Pressing Ctrl-B to "Toggle Side Bar" while having focus in editor and side bar is visuble: hides side bar and focus stays in editor as expected.

Pressing Ctrl-B to "Toggle Side Bar" while having focus in editor and side bar is hidden:  shows side var and focus is moved to now visible sidebar.

VS Code version: Code - Insiders 1.22.0-insider (112670122d3acf863aa9542b1642d64c69be10bf, 2018-03-13T05:16:22.707Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|31.82GB (20.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.14.0
gitlens|eam|8.1.1
RunOnSave|eme|0.0.16
vscode-great-icons|emm|2.1.29
githd|hui|1.1.3
vscode-sciter|lon|0.0.2
Go|luk|0.6.77
code-beautifier|mic|1.7.2
vscode-clang|mit|0.2.2
vscode-code-outline|pat|0.0.13
material-icon-theme|PKi|3.2.6
vscode-icons|rob|7.21.0
go-test-outline|Rom|0.1.4
ignore-gitignore|stu|1.0.1
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by bpasero** [comment] 2018-03-19 09:33
Duplicate of https://www.github.com/Microsoft/vscode/issues/41043

**Comment by lkarlslund** [comment] 2018-03-19 09:36
How is this a duplicate of the other issue? This has nothing to do with the "Reveal Active File In Side Bar", this is about focus moving around when showing/hiding other parts of the IDE via keyboard shortcuts.

**Comment by bpasero** [comment] 2018-03-19 09:46
@lkarlslund true, I got confused.

**Comment by usernamehw** [comment] 2018-03-19 17:58
Maybe it could be done by passing an argument to `workbench.action.toggleSidebarVisibility`: 

**`shiftFocus`**: true(default) | false

I hit this issue occasionally while toggling sidebar with focus fixed on terminal.

**Closed** 2018-09-21 10:56 UTC
Labels: *out-of-scope, feature-request, workbench-layout
