### ISSUE TITLE
Impssible to Switch between windows quickly on chromebook

### ISSUE THREAD

**Issue by m1ckc3b** [microsoft/vscode#116146] opened 2021-02-08 22:32 UTC
With new version I cannot split window quixkly by clicking on 🔲 + < || >
For more information about this chromebook feature => [Multitask with windows & tabs](https://support.google.com/chromebook/answer/177891?hl=en) 

- VSCode Version: 1.53
- OS Version: Google Chrome | 88.0.4324.109 (Build officiel) (64 bits)

**Comment by bpasero** [comment] 2021-02-09 06:39
@mickceb 

> With new version I cannot split window

This is splitting the entire application window, not an editor in VSCode?

**Comment by mickceb** [comment] 2021-02-09 10:09
The app works well. Just the chromebook feature doesn't.
it's a detail but this function is so practical that when you no longer have it you are frustrated.

**Comment by bpasero** [comment] 2021-02-09 10:10
@mickceb and so how would VSCode fix this if it is a Chromebook feature?

**Comment by mickceb** [comment] 2021-02-09 10:22
because this feature no longer work only on the vscode app window since I updated.
The problem is not the feature but what the new vscode update has broken.

**Comment by bpasero** [comment] 2021-02-09 10:31
If this worked in version 1.52, this could hint to a electron update issue, but I am not convinced this can be fixed in VSCode itself.

**Comment by deepak1556** [comment] 2021-02-09 22:07
I don't have a chromebook to test this, does this work when you enable native titlebar `"window.titleBarStyle": "native"`.

**Comment by maucaro** [comment] 2021-02-12 16:00
This is broken regardless of the "window.titleBarStyle" setting; I just tried it. I have the same environment as @mickceb and am experiencing the same broken behavior since upgrading to 1.53.1.

**Comment by deepak1556** [comment] 2021-02-12 19:00
Can you try with `--disable-gpu` ?

**Comment by maucaro** [comment] 2021-02-12 19:42
--disable-gpu doesn't make a difference either. In case it helps, Crome OS reports "App does not support split screen" when using the Crome OS F4 equivalent that @mickceb refers to.

**Comment by deepak1556** [comment] 2021-02-12 23:13
Window operations are handled by Electron, if you can repro the issue with https://www.electronjs.org/fiddle then we can confirm the issue is with the runtime and not vscode.

**Comment by maucaro** [comment] 2021-02-13 00:07
Yes, I was able to repro the issue with Electron. Info from the Electron Hello World! app: 
We are using node 12.18.3, Chrome 87.0.4280.141, and Electron 11.2.3.

**Comment by deepak1556** [comment] 2021-02-13 01:21
Does it work when switch the version to 9 or 10 ?

**Comment by maucaro** [comment] 2021-02-13 01:59
I'm sorry; I've never used Electron. Is that the Chrome Dev tools that you are showing? I don't see where I can chose the Electron version. Can you please let me know how to get there?

**Comment by deepak1556** [comment] 2021-02-15 21:38
Great, thanks for narrowing it down. Does it work when you use versions greater than 11 ?

**Comment by maucaro** [comment] 2021-02-16 00:27
Same (broken) behavior with electron@12.0.0-beta.25.

**Comment by deepak1556** [comment] 2021-02-16 00:42
Can you help filing the issue with what you have found at https://github.com/electron/electron/issues . Thanks!

**Comment by maucaro** [comment] 2021-02-16 01:56
https://github.com/electron/electron/issues/27737

**Comment by deepak1556** [comment] 2022-12-12 18:44
Closing as upstream issue has been closed.

**Closed by deepak1556** 2022-12-12 18:44 UTC
Labels: upstream, electron, upstream-issue-linked
