### ISSUE TITLE
background color bug in manjaro-gnome

### ISSUE THREAD

**Issue by sewerganger** [microsoft/vscode#87977] opened 2020-01-02 08:42 UTC
1. each theme displays different background color  in editor and  dark theme is easy to see and i tried all the themes 

shade of purple
![image](https://user-images.githubusercontent.com/45007226/71658082-7bd5ea00-2d7d-11ea-9abf-ce0f801b38d6.png)

material theme
![image](https://user-images.githubusercontent.com/45007226/71658245-44b40880-2d7e-11ea-9dde-3f755b09742f.png)

OS: Manjaro Linux x86_64 
Host: HP ENVY Laptop 13-ad1xx 
Kernel: 5.4.6-2-MANJARO 
DE: GNOME 3.34.2 
WM: Mutter 
WM Theme: Matcha-sea 
Theme: Matcha-sea [GTK2/3] 
Icons: Papirus-Dark-Maia [GTK2/
Terminal: gnome-terminal

**Comment by IllusionMH** [comment] 2020-01-02 10:23
/duplicate of #85452

See https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562 for fix

**Closed** 2020-01-02 10:23 UTC
Labels: *duplicate, themes
