### ISSUE TITLE
Git - install git "for windows" when in remote linux

### ISSUE THREAD

**Issue by jonnytest1** [microsoft/vscode#230045] opened 2024-09-28 15:03 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. connect to remote ssh machine  that doesnt have git installed yet + linux
2. go to source control tab
3. get popup about "install git for windows" even though the remote system is using linux

**Comment by lszomoru** [comment] 2024-12-20 07:50
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/10188

**Closed by lszomoru** 2024-12-20 07:50 UTC
Labels: bug, git
