### ISSUE TITLE
Regular expression breaks syntax highlighting

### ISSUE THREAD

**Issue by KostyaTretyak** [microsoft/vscode#92904] opened 2020-03-18 06:55 UTC
```text
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-40-generic
```

If we place the cursor to the right of the last parenthesis in the following code, then we will see that the syntax highlight is not working properly.

```ts
if (!/(\/)/.test('text')) {
  const one = '';
}
```

Rusult highlighting:

![image](https://user-images.githubusercontent.com/2286306/76933017-da2e5580-68f4-11ea-82e3-fcf078292118.png)

Also, as you can see, the syntax for the keyword `const` is incorrectly highlighted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-03-18 09:27
/duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed by IllusionMH** 2020-03-18 09:27 UTC
Labels: *duplicate
