### ISSUE TITLE
[Accessibility]A11y_VSCode_GoToSymbolInFile_ScreenReader:NVDA reads @ twice which is in the placeholder

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#51899] opened 2018-06-14 11:49 UTC
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10
**Additional Details**:
ScreenReader [NVDA2018.2],,MAS1.3.1
**Repro Steps:**
1)Launch VS Code.
2)Navigate   to Go(Alt+G) menu option and select "Go To Symbol in File" from   dropdown
3)Start NVDA.
Actual:
NVDA reads @ twice which is inappropriate
**Expected:**
NVDA should not read @ twice.
**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx
**User Impact:**
Such an activity would create Confusion for the user.
**MAS Reference:**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}
Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference:**
[[Accessibility]A11y_VSCode_GoToSymbolInWorkSpace_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2102162/Accessibility.A11y_VSCode_GoToSymbolInWorkSpace_Keyboard.pptx)

**Comment by isidorn** [comment] 2018-07-03 15:31
Can not repro this issue.
Video is unrelated to this issue, it is a duplicate of https://github.com/Microsoft/vscode/issues/51850

**Closed by isidorn** 2018-07-03 15:31 UTC
Labels: accessibility
