### ISSUE TITLE
Javascript: Open symbol (Ctrl+T) and files.exclude settings

### ISSUE THREAD

**Issue by markus-brt** [Microsoft/vscode#5885] opened 2016-04-27 09:55 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 8

Steps to Reproduce:

1. Open symbol by name (Ctrl+T)
2. It finds stuff in Javascript files that match a "files.exclude" entry in the settings.json

Shouldn't the global symbol search take into account the "files.exclude" list from the settings.json?
It seems this is not the case.

**Comment by egamma** [comment] 2016-04-27 13:29
The `files.exclude` only affects what is shown in the explorer. 

To exclude files from the JavaScript language service you can use the `jsconfig.json` exclude attribute https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson.

Closing as works as intended.

**Closed by egamma** 2016-04-27 13:29 UTC
