### ISSUE TITLE
Shift+Option+F does not work on US extended kb layout

### ISSUE THREAD

**Issue by hafuta** [Microsoft/vscode#8914] opened 2016-07-08 08:47 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:52:42.674Z)
- OS Version: Darwin x64 15.5.0

In last few versions the code format feature (shift+alt+f) is not working, I've tried to change to other key combination for the format command but it's not working, when I install v1.0 it seems to work okay, I've tried mainly on JavaScript files but it doesn't seem to work for other types also (css, json).

I don't have any other program who uses this combination or any os command that uses this key combination, I've no installed extensions and I've also tried to load the program with the '--disable-extensions' cli argument.

Thanks

**Comment by joaomoreno** [comment] 2016-07-11 07:45
If you open the Developer Tools, do you see any errors there?

Does running the `Format` command from the Command Palette work?

What are the contents of your keybindings file?

**Comment by alexandrudima** [comment] 2016-07-11 11:09
@hafuta Also what appears when you go to customize keybindings and use the `Define Keybinding` widget?

![shift-alt-f](https://cloud.githubusercontent.com/assets/5047891/16728755/f032a9b6-4770-11e6-869f-68369d979254.gif)

**Comment by mbilling** [comment] 2016-07-11 11:54
I just reported about the same issue but just for typescript .tsx files under certain circumstances but with concrete sourcefile that make is repro possible - weee :)
Maybe there is a bug in common here...
Issue #9067

**Comment by Treri** [comment] 2016-07-12 08:54
@joaomoreno @alexandrudima 
I have the same problem.
I use vscode from the Command Palette to format a javascript file uglified by uglify-js, but it failed. It not format code correctly, and only format partially.

**source file**
![2016-07-12 4 47 08](https://cloud.githubusercontent.com/assets/2631733/16760863/5b438ccc-4850-11e6-87de-4c2475b08d60.png)

**sublime jsFormat formated**
![2016-07-12 4 47 29](https://cloud.githubusercontent.com/assets/2631733/16760887/69fc490c-4850-11e6-9279-2b79e4f6c87f.png)

**vscode formated**
![2016-07-12 4 47 45](https://cloud.githubusercontent.com/assets/2631733/16760892/72414f4a-4850-11e6-9ce5-72e2633bb317.png)

You see, It seems like, vscode only add some spaces around brackets, letters, commas etc.

I opened vscode's ChromeDevTools, but not error msg showed.

**Comment by alexandrudima** [comment] 2016-07-12 09:07
I think that is how tsserver decides to format. The fact that the whitespace changes indicates the integration works correctly and that tsserver simply decides to not insert newlines. Perhaps @dbaeumer knows of some config options that might help.

**Comment by Treri** [comment] 2016-07-12 09:13
@alexandrudima 

But if I have this file(see the first line of this file)
![image](https://cloud.githubusercontent.com/assets/2631733/16761670/b6fa63da-4853-11e6-895a-70925f83d066.png)

Then I use code to fromat, I get this
![image](https://cloud.githubusercontent.com/assets/2631733/16761694/d4c27a56-4853-11e6-8c0f-0565c7744146.png)

I upload my file
[app_01886e5b.js.zip](https://github.com/Microsoft/vscode/files/358947/app_01886e5b.js.zip)

**Comment by dbaeumer** [comment] 2016-07-13 10:25
@Treri to help tracking this down, can you please enable tsserver tracing using the following setting:

```json
	"typescript.tsserver.trace": "verbose"
```

Then switch to the output view and select the TypeScript channel and format. Could you provide the created trace?

**Comment by Treri** [comment] 2016-07-14 03:34
@dbaeumer 
[output.txt](https://github.com/Microsoft/vscode/files/362973/output.txt)

**Comment by Treri** [comment] 2016-07-14 03:38
Maybe you can use my uploaded file to reproduce?

**Comment by Treri** [comment] 2016-07-14 03:49
@dbaeumer 
this is my second file.
step:
1. use sublime jsFormat to format entire file.
2. join the first two lines to one line. like my above screentshot
3. use code to format, then get the trace.
[output2.txt](https://github.com/Microsoft/vscode/files/362980/output2.txt)

**Comment by hafuta** [comment] 2016-07-16 20:44
@joaomoreno  please see attached screen recording with the developer tools on the right side. 
Pressing shift+alt+f does not working, same when trying to format code from the command palette, no errors in the console in both cases.

@alexandrudima I've also tried using the Define keybinding widget to define different key combination, same thing, it identifies the keys correctly but does not work.

At the moment I've installed beautify plugin in order to have the format functionality until I'll understand the issue with the built-in feature.

My keybindings.json content is:
`// Place your key bindings in this file to overwrite the defaults
 []
`

![6scpu5xwcn](https://cloud.githubusercontent.com/assets/3253259/16896980/5d9b6468-4bac-11e6-94b1-e8f7a0a2115c.gif)

Thanks

**Comment by Treri** [comment] 2016-07-28 06:59
Any progress on this issue?

**Comment by dbaeumer** [comment] 2016-08-03 14:42
Was on vacation for two weeks.

**Comment by dbaeumer** [comment] 2016-08-04 07:31
@Treri for your issue I created https://github.com/Microsoft/TypeScript/issues/10126 to track this since it is a TS/JS server issue.

Assigning this issue back since the original reported problem from @hafuta is not addressed by this.

**Comment by alexandrudima** [comment] 2016-08-05 08:29
@hafuta Any more information from you? -- otherwise I will close this issue.

**Comment by ramamurthynagaraj** [comment] 2016-08-12 17:28
Hi,
I am also facing the same issue, VS code version: Version 1.4.0 (1.4.0)
Trying out shift+alt+f in keybindings gives the following.
![shift+alt+f](https://cloud.githubusercontent.com/assets/1949807/17630902/33f9358e-60df-11e6-9563-2caae75d7a29.png)

I am able to right click -> format and the command palette Format Code also works. Just the keybindings. 
Also was trying out if any other bindings shows the same unknown, the following does,
shift+alt+s, shift+alt+f, shift+alt+g, shift+alt+y.

**Comment by alexandrudima** [comment] 2016-08-15 09:17
@ramamurthynagaraj What keyboard layout do you use? Do you press `AltGr` (usually the one on the right hand side of the space bar) or do you press `Alt` (usually the one on the left hand side of the space bar) ?

**Comment by acdha** [comment] 2016-09-09 15:30
I think this depends on the configured keyboard input system. Using the U.S. layout, Shift-Option-f is the shortcut for the Ï (LATIN CAPITAL LETTER I WITH DIAERESIS). Using the ABC Extended layout, that shortcut starts the process of entering a COMBINING TILDE BELOW with whatever key you hit next.

If I enable the default U.S. layout, the default formatting shortcut works instead of inserting an Ï. If I use a different layout, it does not work because the text entry system swallows the keystroke and waits for you to enter the character which which the tilde below will be combined, which is visible but rather subtly as an underlined tilde beneath the cursor.

This behaviour is standard across all system text inputs and so I'd guess that VS Code would either need to use a lower-level interface to get the raw keyboard events or simply pick shortcuts which don't conflict. See https://support.apple.com/en-us/HT201236, http://symbolcodes.tlt.psu.edu/accents/codemacext.html, etc. or simply open the keyboard viewer (https://support.apple.com/kb/PH18449) and hold down modifier keys – the combining diacritics will display as orange.

**Comment by alexandrudima** [comment] 2016-09-12 11:59
Ok, so the action for us is to change the default keybinding for format code from `Shift+Option+F` to something else. Anyone has any ideas?

**Comment by Treri** [comment] 2016-09-12 13:23
#11810

**Comment by alexandrudima** [comment] 2017-03-24 11:00
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's Insiders build) detect correctly this keypress under the US layout on OSX.

![image](https://cloud.githubusercontent.com/assets/5047891/24291430/3862e20a-1089-11e7-99c9-6c78379d26de.png)

Furthermore, I have checked in a JSON file that `shit+alt+f` correctly triggers the `editor.action.formatDocument` action and the JSON file gets formatted.

**Closed by alexandrudima** 2017-03-24 11:00 UTC
Labels: bug, keybindings, keyboard-layout, mac

**Comment by carl-parrish** [comment] 2017-04-07 16:14
The shift+alt+f keybinding doesn't work for me what steps do I need to do to get it working?

**Comment by alexandrudima** [comment] 2017-05-20 11:34
If your keyboard layout is ABC - extended, shift+option+f goes into composition mode (drive by the OS), similar how composition works for CJK languages. If you don't care about such type of compositions, change your keyboard layout to ABC or pick a language-country keyboard layout that works for you.
