### ISSUE TITLE
Cannot filter out problems in Problems panel 

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#63522] opened 2018-11-20 19:34 UTC
_Re-posting from https://github.com/Microsoft/vscode/issues/63303#issuecomment-440272898, @roblourens suggested that the issue might be for @sandy081. This relatively fresh issue seems somewhat related as well but I'm not sure: https://github.com/Microsoft/vscode/issues/62216._

- VSCode Version: 1.29 and 1.30
- OS Version: macOS Mojave

Steps to Reproduce:

1. Generate any problem in the workspace
2. In the Problems panel, try to filter out this problem by using `!*.<ext>` or `!**/*.<ext>` – neither seems to work.

Example:

<img width="349" alt="screenshot 2018-11-20 at 14 24 34" src="https://user-images.githubusercontent.com/101152/48776456-33ba4c00-ecd0-11e8-8442-0da7dde053da.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment] 2018-11-21 10:57
Duplicate of https://github.com/Microsoft/vscode/issues/63490

**Closed by sandy081** 2018-11-21 10:57 UTC
Labels: extensions
