### ISSUE TITLE
ANSI codes don't all work in console

### ISSUE THREAD

**Issue by richtera** [Microsoft/vscode#65930] opened 2019-01-02 23:06 UTC
Issue Type: <b>Bug</b>

Hi
I am outputting my log messages with a start of line tag because I have some code that output progress to the console. When I try to run the code within visual studio it seems to truncate part of the output rather than going to the beginning of the line. I suppose it should either ignore the ansi code (which wouldn't be great but a bit more predictable) or implement the correct CR without a LF
export const START_OF_LINE = '\u001b[2K\u001b[0G';
Right now what it's doing it removing the text between this mark and the next ANSI control sequence.
Thanks
Andy

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-jq|dan|1.0.0
vscode-jq-playground|dav|1.8.0
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.7.3
code-runner|for|0.9.5
gc-excelviewer|Gra|2.1.26
vscode-language-babel|mgm|0.0.21
dotenv|mik|1.0.1
python|ms-|2018.12.1
vscode-typescript-tslint-plugin|ms-|0.2.1
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.4.0
sass-indented|rob|1.5.1
gitconfig|sid|2.0.0
mdx|sil|0.1.0
quokka-vscode|Wal|1.0.174

</details>

**Comment by richtera** [comment] 2019-01-03 00:19
FYI Output capture is set to ```"outputCapture": "std"```

**Comment by egamma** [comment] 2019-01-04 18:22
@richtera 

>I am outputting my log messages with a start of line tag because I have some code that output progress to the console. 

can you please clarify whether you refer to the 'Output' or 'Terminal' tab of the panel.

The Output channels do not support ANSI Code https://github.com/Microsoft/vscode/issues/571. 
To handle ANSI Code the recommendation is to use the Terminal API and show your logging messages in the terminal.

**Comment by richtera** [comment] 2019-01-04 18:37
I am using the output tab and that is what I am seeing. If it were to just ignore the ansi codes that would be fine but it seems to have a partially broken implementation.

**Comment by egamma** [comment] 2019-01-04 18:42
Thanks for the clarification. Then this feature request is a duplicate of #571 and mentioned above the recommendation is to show the output in a terminal, there is API available to do so.

**Comment by richtera** [comment] 2019-01-04 19:11
@egamma this is not a duplicate because the output seems to attempt to support ansi and doesn't work. I would rather if it just output the text as is if it can't support full ansi. As it is now it truncates output if there are ansi sequences within. Maybe there is a cleanup expression which is too greedy.

**Comment by isidorn** [comment] 2019-01-07 09:22
Duplicate of some of these https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+debug+console+ansi+

**Closed by isidorn** 2019-01-07 09:22 UTC
Labels: editor-contrib

**Comment by isidorn** [comment] 2019-01-07 10:37
Becuase I believe it is a duplicate
