### ISSUE TITLE
Right click copy does not copy a url in the body of an extension

### ISSUE THREAD

**Issue by DEVNULLDNE** [microsoft/vscode#137407] opened 2021-11-18 02:01 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: Windows 10

Steps to Reproduce:

1. View an extension that has links
2. right click on a link and press copy
3. paste and notice how it's not the url

Also, the cut and paste on the right click menu are useless when viewing an extension, so might as well prevent those from showing too.

**Comment by mjbvz** [comment] 2021-11-19 00:23
Duplicate of #131964

**Closed by mjbvz** 2021-11-19 00:23 UTC
