### ISSUE TITLE
Go To Definition too slow on 1.33

### ISSUE THREAD

**Issue by oquirozm** [Microsoft/vscode#71894] opened 2019-04-07 23:12 UTC
The bug is also present for me in the latest insiders build and when running without extensions on both builds.

- VSCode Version: 1.33
- OS Version: Mac OS 10.14.3

Steps to Reproduce:

1. Update VS Code to 1.33
2. Try to click on Go To Definition in a .tsx in a create-react-app project (it's a large project, 928mb, including node_modules. Most of it in TypeScript). The operation will take around 2 minutes. I downgraded to 1.32 and the behavior was gone.

Also, the Code Helper process goes to 100% while the operation is going on. Not sure if related to the issue stated.

**Comment by svipas** [comment] 2019-04-08 07:47
As mentioned here: https://github.com/Microsoft/vscode/issues/71886 try to delete TS cache.

Windows
```
C:\Users\(your username)\AppData\Local\Microsoft\TypeScript\
```

Mac
```
/Users/(your username)/Library/Caches/typescript
```

**Comment by mityabeldii** [comment] 2019-04-08 11:40
It's actually helped me. Thanks a lot to @svipas!

**Comment by oquirozm** [comment] 2019-04-08 11:43
@svipas will try it out after work and will update the issue accordingly.

**Comment by bibblebabl** [comment] 2019-04-08 14:56
@svipas It worked, thanks! But it's still noticeably slower than before. I'll have to go back to the previous version.

**Comment by alexknipfer** [comment] 2019-04-08 15:56
I was noticing slowness as well around "go to definition" along with intellisense, rolling back a version was the solution I had to take as well. Deleting TS cache didn't work for me.

**Comment by mjbvz** [comment] 2019-04-08 21:51
Duplicate of #71751

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for workarounds

**Closed** 2019-04-08 21:51 UTC
Labels: *duplicate, javascript

**Comment by oquirozm** [comment] 2019-04-10 22:53
Just for the record, running `npm install @types/styled-components@4.1.5` on my project, as suggested in #71751 solved my problem.
