### ISSUE TITLE
Feature request: Allow grouping of items in the QuickPick input just like the git branches view

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode#16276] opened 2016-11-30 16:33 UTC
It would be nice to allow grouping of QuickPickItems.
Currently one can see this in the `git checkout` branch list. There are the local and the remote branches grouped and separated with a small line.

**Comment by jrieken** [comment] 2016-12-09 13:52
dupe of  #11468

**Closed by jrieken** 2016-12-09 13:52 UTC
Labels: api, feature-request
