### ISSUE TITLE
"window.zoomLevel" stop working

### ISSUE THREAD

**Issue by FernandoMiguel** [Microsoft/vscode#61414] opened 2018-10-20 22:57 UTC
Issue Type: <b>Bug</b>

When trying to zoom the text, Code complains with
> Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

When trying to change the settings of 
`"window.zoomLevel": 0` it fails to safe the file

VS Code version: Code - Insiders 1.29.0-insider (45d5d153bbebed743b77e426615aade34971eb46, 2018-10-19T06:50:39.461Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
spellright|ban|3.0.5
better-toml|bun|0.3.2
githistory|don|0.4.3
gitlens|eam|8.5.6
mdhelper|jos|0.0.11
vscode-github|Kni|0.30.0
terraform|mau|1.3.7
prettify-json|moh|0.0.3
vscode-docker|Pet|0.3.1
vscode-nginx|sha|0.5.0
sort-lines|Tyr|1.7.0

</details>

```json
{
    "editor.minimap.enabled": false,
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1000,
    "editor.wordWrap": "on",
    "editor.tabCompletion": "on",
    "editor.fontSize": 14,
    "editor.trimAutoWhitespace": true,
    "editor.formatOnSave": true,
    "editor.folding": false,
    "editor.glyphMargin": false,
    "editor.renderWhitespace": "all",
    "json.format.enable": true,
    "window.restoreWindows": "all",
    "window.restoreFullscreen": true,
    "window.newWindowDimensions": "fullscreen",
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "markdown.preview.scrollEditorWithPreview": true,
    "workbench.editor.labelFormat": "default",
    "workbench.startupEditor": "newUntitledFile",
    "git.autofetch": true,
    "files.associations": {
        "Dockerfile-*": "dockerfile",
        "*.yml.*": "yaml"
    },
    "[terraform]": {
        "editor.formatOnSave": true
    },
    "terraform.format": {
        "enable": true,
        "formatOnSave": true
    },
    "terraform.path": "/usr/local/bin/terraform",
    "terraform.lintPath": "/usr/local/bin/tflint",
    "terraform.codelens.enabled": true,
    "terraform.indexing": {
        "enabled": true,
        "liveIndexing": true,
    },
    "git.enableCommitSigning": false,
    "git.detectSubmodulesLimit": 100,
    "editor.foldingStrategy": "indentation",
    "editor.showFoldingControls": "always",
    "editor.insertSpaces": false,
    "breadcrumbs.enabled": false,
    "gitlens.defaultDateStyle": "absolute",
    "gitlens.settings.mode": "advanced",
    "terraform.telemetry.enabled": false,
    "workbench.colorTheme": "Default Dark+",
}
```

**Comment by usernamehw** [comment] 2018-10-20 23:42
Duplicate of #61341

**Closed** 2018-10-22 19:05 UTC
Labels: *duplicate, insiders
