### ISSUE TITLE
Resizing split terminals makes content wrap weirdly, no way to get back

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44666] opened 2018-02-27 22:40 UTC
Testing #44446 in Mac

Below, I split the terminal 4 times. Then picked one of the boundaries between 2 of the resulting terminals and moved left and right. All text flows around weirdly and getting the size back to the original size doesn't make the text go back to the original layout

![terminal-use-flow](https://user-images.githubusercontent.com/16890566/36759400-17b0e8a0-1bcc-11e8-8609-785d92aa9af8.gif)

**Comment by Tyriar** [comment] 2018-02-28 16:28
Pretty sure the weird text on the right that's hanging around is because of the temporary "reflow" workaround of keeping the text around when the terminal's resized but not shown, so that particular problem will probably be fixed with https://github.com/Microsoft/vscode/issues/23688.

**Comment by Tyriar** [comment] 2018-02-28 16:29
This issue made me realize this is the first time terminals can go below like 30 columns or so due to the minimum width of the panel.

**Comment by Tyriar** [comment] 2018-02-28 16:31
Good news (I guess) is I can pretty easily break the most popular Linux terminal by fiddling with narrow widths when the prompt is up:

![image](https://user-images.githubusercontent.com/2193314/36799313-b35ed506-1c61-11e8-8945-b7db086a2e81.png)

**Comment by Tyriar** [comment] 2018-02-28 16:33
We seem to do about as good of a job with this as other terminals (checked gnome-terminal, terminator, iterm), it's just we allow the terminal to be more narrow then them. I think I'll increase the min width even more and call this a shell bug :smiley:

**Comment by Tyriar** [comment] 2018-02-28 16:35
To verifier: check that the min width is larger (120px) and the situation has improved as a result.

**Closed** 2018-02-28 16:34 UTC
Labels: bug, integrated-terminal

**Comment by gushuro** [comment] 2018-03-01 20:55
I see the improvement and the min width increase.
There's still unexpected behavior when getting a terminal size back to the original. That's being tracked on https://github.com/Microsoft/vscode/issues/23688
