### ISSUE TITLE
Voice extension fails when extensions path has non-ASCII characters

### ISSUE THREAD

**Issue by RafalSkorka** [microsoft/vscode#206512] opened 2024-02-29 08:08 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

I am using Windows 10 Polish interface, however I have the English (US) configured in Settings -> Speech and two languages installed in Settings -> Language (Anglish and Polish).
When trying to use Speech extension I get this error:

```
2024-02-29 08:58:45.594 [trace] [vscode-speech-0] starting speech-to-text session (language: en-US, model: Microsoft Speech Recognizer en-US FP Model V8.1)
2024-02-29 08:58:45.699 [error] [vscode-speech-0] error: Invalid argument exception: Cannot find an embedded speech recognition model by name "Microsoft Speech Recognizer en-US FP Model V8.1". Check that the arguments for FromPath or FromPaths are valid model paths and SetSpeechRecognitionModel is called with a valid model name.
[CALL STACK BEGIN]

    > recognizer_create_speech_recognizer_from_config
    - recognizer_create_speech_recognizer_from_config
    - 00007FFE65676B44 (SymFromAddr() error: Próbowano uzyskać dostęp do nieprawidłowego adresu.)
    - 00007FFE656781A4 (SymFromAddr() error: Próbowano uzyskać dostęp do nieprawidłowego adresu.)
    - 00007FFE65680E1B (SymFromAddr() error: Próbowano uzyskać dostęp do nieprawidłowego adresu.)
    - 00007FFE656735F5 (SymFromAddr() error: Próbowano uzyskać dostęp do nieprawidłowego adresu.)
    - uv_dlerror
    - uv_dlerror
    - uv_cancel
    - uv_thread_create_ex
    - Cr_z_adler32
    - BaseThreadInitThunk
    - RtlUserThreadStart

[CALL STACK END]


2024-02-29 08:58:45.704 [trace] [vscode-speech-0] disposed speech-to-text session
2024-02-29 08:59:02.906 [trace] [vscode-speech-0] disposing speech-to-text session
```

**Comment by bpasero** [comment] 2024-03-01 13:06
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

And then please also install the pre-release speech extension

**Comment by RafalSkorka** [comment] 2024-03-05 07:57
unfortunately the same results are on the vs code insiders release and the pre-release vs code speech extension (v0.7.2024022820 (pre-release)):

```
2024-03-05 08:54:10.467 [trace] [vscode-speech-0] starting speech-to-text session (language: en-US, model: Microsoft Speech Recognizer en-US FP Model V8.1)
2024-03-05 08:54:10.569 [error] [vscode-speech-0] error: Invalid argument exception: Cannot find an embedded speech recognition model by name "Microsoft Speech Recognizer en-US FP Model V8.1". Check that the arguments for FromPath or FromPaths are valid model paths and SetSpeechRecognitionModel is called with a valid model name.
[CALL STACK BEGIN]

    > recognizer_create_speech_recognizer_from_config
    - recognizer_create_speech_recognizer_from_config
    - 00007FFA04236B44 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FFA042381A4 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FFA04240E1B (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FFA042335F5 (SymFromAddr() error: Attempt to access invalid address.)
    - uv_dlerror
    - uv_dlerror
    - uv_cancel
    - uv_thread_create_ex
    - Cr_z_adler32
    - BaseThreadInitThunk
    - RtlUserThreadStart

[CALL STACK END]


2024-03-05 08:54:10.570 [trace] [vscode-speech-0] disposed speech-to-text session
2024-03-05 08:54:14.569 [trace] [vscode-speech-0] disposing speech-to-text session
```
One thing I notices is there is a bit different version of Language displayed in the Speech Properties in Control Panel:
![image](https://github.com/microsoft/vscode/assets/3476094/15ed2982-f39a-49f0-85b5-3bf41f02b517)
v8.0 vs expected v8.1 but I don't know if that matters.

**Comment by bpasero** [comment] 2024-03-05 13:40
@RafalSkorka what is your extensions folder, can you "Open Extensions Folder" command:



![Image](https://github.com/microsoft/vscode/assets/900690/6a1fadd7-50dd-4919-84de-c990b8dd46d6)


Is that maybe a network share or UNC path? That is where we would load the model from, specifically from here:



![Image](https://github.com/microsoft/vscode/assets/900690/7869784b-d5f1-4224-a071-d5482d7e3e6d)

**Comment by bpasero** [comment] 2024-03-06 08:59
Thanks, I can reproduce and reported as upstream: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2288

**Comment by ifirdavs** [comment] 2024-04-26 09:12
Hasn't this issue been resolved yet?
Cause I updated the extension and it's still there.

**Comment by bpasero** [comment] 2024-12-28 06:01
It still seems to be present but is reported upstream and not under our control unfortunately. Closing until we can adopt a newer version with a fix.

**Closed by bpasero** 2024-12-28 06:01 UTC
Labels: bug, upstream, confirmed, workbench-voice

**Comment by bpasero** [comment] 2025-05-22 13:53
This has been fixed in the upstream SDK and you can try it out from the pre-release extension version `0.15.2025052212`
