### ISSUE TITLE
Changing multiple occurrences when they are adjacent loses one of the occurrences

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode#11150] opened 2016-08-30 01:24 UTC
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Note how `11` turns into `2`.

![](https://cl.ly/203h0f0v0N2A/Screen%20Recording%202016-08-29%20at%2006.22%20PM.gif)

**Comment by alexandrudima** [comment] 2017-03-31 07:19
Duplicate of #6661

**Closed by alexandrudima** 2017-03-31 07:19 UTC
Labels: bug, editor, editor-multicursor
