### ISSUE TITLE
Keybindings for project tasks

### ISSUE THREAD

**Issue by albertosml** [microsoft/vscode#140105] opened 2022-01-04 16:34 UTC
**Requested feature**

As a user, I would like to set my own keybindings to run my project tasks through a shortcut. Currently, I need to set them in a global `keybindings.json` file. However, if I want to use the same shortcut for several tasks, which are located in different projects, I cannot do that, because shortcuts must be defined globally, so a keybinding can be only used by only one task.

A good solution to solve this problem would be to define keybindings per project. By doing that, I could use the same shortcut for running all the project servers. For example, if we have a web application with a front-end and a back-end server in separated projects, `ctrl+shift+1` shortcut could be set in both servers to run their applications.

Besides, this was a functionality requested in a previous [issue](https://github.com/microsoft/vscode/issues/101182), so I think it would be worth to add it to improve the IDE.

**Possible solutions**

1. As proposed in the mentioned issue above, we could set a local keybinding file inside the project worskpace, which would be ubicated in `.vscode/keybindings.json` and overwrite the configuration defined in the global `keybindings.json` file. By doing that, we could set any action to run in the project. 

2. Add a new option for task content in the `tasks.json` file. It would be called `keybinding` and have the shortcut as a value. With this option, we could establish the same shortcut for tasks located in different projects. An example task would be this one:

```
{
     "label": "Example task",
     "type": "shell",
     "command": "echo \"Example task\"",
     "options": {
          "cwd": "${workspaceFolder}"
     },
     "keybinding": "ctrl+e"
},
```

**Comment by albertosml** [comment] 2022-01-04 16:38
Personally, I would prefer the second option as this would allow to associate more easily the shortcut with the created task. However, if we would want to extend this to any action, I would choose the first option.

I think that this would be a functionality that would be worth adding it. For that, I would be open to contribute in the development for this desired functionality.

**Comment by alexr00** [comment] 2022-01-05 10:26
All keybindings should live in the same place. Duplicate of https://github.com/microsoft/vscode/issues/101182.

**Closed by alexr00** 2022-01-05 10:26 UTC
