### ISSUE TITLE
Allow working tab to be a draggable file

### ISSUE THREAD

**Issue by Solid89** [Microsoft/vscode#29967] opened 2017-06-30 18:46 UTC
A great feature MS Word & Excel have is the file icon at the top of the said window is draggable into a drop zone for attachments in emails etc. This eliminates the necessity for digging around my hard drive for the files location. 
Code does not have this feature. Please add it for ease of accessibility. 

- VSCode Version:
1.14.0-insider

**Comment by bpasero** [comment] 2017-11-17 08:06
@Solid89 is this on macOS in the title?

**Comment by Solid89** [comment] 2017-11-21 21:14
@bpasero  On macOS, in the title bar in Microsoft Word, next to the files name there is a mini icon of a paper with an even smaller ms word icon on it.  This entire icon is draggable and acts as if it is the actual file being presently worked on.

Visual Studio Code has no icon adjacent to the title of the file. There is simply the name of the file. A draggable icon in the title bar would be a major enhancement in my productivity flow. 
Please refer to the screenshots to see the difference.

Visual Studio Code
<img width="372" alt="visual studio code title bar" src="https://user-images.githubusercontent.com/12763868/33096592-84bd39ba-ced5-11e7-903d-4d2bf642065d.png">
Microsoft Word
<img width="448" alt="ms word title bar" src="https://user-images.githubusercontent.com/12763868/33096607-91290d0a-ced5-11e7-9c6d-d78637bc92f9.png">

**Comment by Solid89** [comment] 2017-11-21 21:16
Did not mean to close it :/

**Comment by bpasero** [comment] 2017-11-22 06:13
@Solid89 yeah, that is because we do our own custom title header. You can get the native one back with the support for the icon by configuring: `"window.titleBarStyle": "native"`

/duplicate of https://github.com/Microsoft/vscode/issues/17664

**Closed by bpasero** 2017-11-22 06:13 UTC
Labels: feature-request, needs more info, workbench-dnd, workbench-title
