### ISSUE TITLE
Ability to create a file with that uses a custom editor without needing to have an open workspace 

### ISSUE THREAD

**Issue by kkukshtel** [microsoft/vscode#108532] opened 2020-10-12 14:51 UTC
A file that has an extension type that uses a custom editor currently requires a workspace to be open in order to create new files of that custom editor type. This is evidenced by the PawDraw sample project:

![image](https://user-images.githubusercontent.com/7715279/95759827-3cc3b600-0c78-11eb-9ba8-dcfae92ca7cc.png)

It would be great if users would be able to create new files that use custom editors without needing a workspace to be open. I'm imagining the flow would be like this:

1. Provide (via the extension) the template string text that would be the MVP to have your custom editor properly render.
2. User issues command to create new file type that uses the custom editor.
3. Code writes the template text to a virtual document, and sets the file as dirty.
4. Code opens that virtual document in the custom editor.

I'm running into issues with this with my custom editor extension already (https://github.com/kkukshtel/Depot/issues/15), and my current "fix" is to just gracefully handle the edge case in the same way PawDraw does.

**Comment by mjbvz** [comment] 2020-10-20 14:56
Duplicate of #93441

**Closed by mjbvz** 2020-10-20 14:56 UTC
