### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by ShaneDesmondONeill** [microsoft/vscode#93364] opened 2020-03-25 08:29 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3

Cannot reproduce 

**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (tsserver.js:112241:13)
    at Object.releaseDocument (tsserver.js:112236:20)
    at tsserver.js:135319:45
    at Object.forEach (tsserver.js:167:30)
    at Proxy.dispose (tsserver.js:135318:20)
    at InferredProject.Project.close (tsserver.js:139542:38)
    at InferredProject.close (tsserver.js:140420:40)
    at ProjectService.removeProject (tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.44.0-insider (073a24de05773f2261f89172987002dc0ae2f1cd, 2020-03-24T07:05:24.597Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|32.00GB (4.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|11.0.0
cucumberautocomplete|ale|2.14.1
jest-snippets|and|1.8.0
gitstash|art|3.2.0
toml|be5|0.4.0
css-compressor|bes|0.0.2
refactor-jsx|chi|0.0.1
path-intellisense|chr|1.4.2
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.1
eslint-disable-snippets|drK|1.2.0
es7-react-js-snippets|dsz|2.7.0
vscode-wasm|dts|1.3.1
gitlens|eam|10.2.1
LogFileHighlighter|emi|2.7.1
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
vscode-postman|eri|1.0.2
prettier-vscode|esb|3.20.0
jira-plugin|gio|0.19.0
vscode-pull-request-github|Git|0.15.0
todo-tree|Gru|0.0.170
kubernetes-snippets|ipe|0.1.9
better-cpp-syntax|jef|1.14.27
webpack|jer|2.2.0
vscode-peacock|joh|3.6.0
react-native-snippet|jun|0.5.6
chat|kar|0.33.0
csstriggers|kis|0.12.1
graphql-for-vscode|kum|1.15.3
node-module-intellisense|lei|1.5.0
web-component-snippets|Luc|0.1.0
metago|met|3.4.3
vscode-language-babel|mgm|0.0.26
git-graph|mhu|1.22.0
vscode-exec-node|mir|0.5.1
easy-less|mrc|1.6.3
vscode-azurefunctions|ms-|0.21.0
vscode-azurestorage|ms-|0.9.0
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.15
vscode-aks-tools|ms-|0.0.4
vscode-kubernetes-tools|ms-|1.1.0
azure-account|ms-|0.8.8
cpptools|ms-|0.26.3
vsliveshare|ms-|1.0.1783
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.2
vscode-json-editor|nic|0.2.3
snippet-creator|nik|0.0.5
ios-snippets|orn|0.0.15
jest-cucumber-code-generator-extension|pio|1.0.2
material-icon-theme|PKi|4.0.1
bitbucket-pull-requests|Ram|0.3.10
vscode-yaml|red|0.7.2
html-to-jsx|ria|0.0.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.2
sonarlint-vscode|Son|1.15.0
es6-mocha-snippets|spo|0.2.2
git-prefix|srm|1.2.0
cucumber|ste|0.12.0
code-spell-checker|str|1.8.0
node-chakracore-time-travel-debugger|ttd|0.2.4
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-03-25 18:52
Duplicate of https://github.com/microsoft/TypeScript/issues/37500

**Closed by mjbvz** 2020-03-25 18:52 UTC
