### ISSUE TITLE
VScode Update 1.32.1 

### ISSUE THREAD

**Issue by jayklaus** [Microsoft/vscode#70105] opened 2019-03-09 02:19 UTC
Issue Type: <b>Bug</b>

Since the update hot reload isn't functioning.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3309)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.24.0
flutter|Dar|2.24.0
dart-import|lua|0.1.2
python|ms-|2019.2.5558
dart-syntax-highlighting-only|osc|1.0.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by coder137** [comment] 2019-03-09 08:32
+1 Having the same issue.

**Comment by RedQuark** [comment] 2019-03-10 13:12
I also have the same issue. Like @coder137 I do not get a hot reload on Save on Windows 10 (Ctrl-S), but I do get a hot reload on Restart (Ctrl-Shift-F5) with the default settings. I should add that hot reloading on Save was working for me in the 32-bit VSCode (1.31.1), but broke when I uninstalled that version (preserving settings and extensions) and then installed the 64-bit VSCode (1.32.1). Restarting OS and VSCode and reinstalling extensions made no difference. No issues found in flutter doctor. Hot reload on save works fine in Android Studio (3.3).

**Comment by sjy0w0** [comment] 2019-03-11 07:26
Same for me, after I start debugging by (F5) and run Dart: Run DevTools, it will show "**Dart DevTools requires an active debug session."**

**Comment by isidorn** [comment] 2019-03-11 08:58
This should be fixed with the latest insiders which should be out soon
@DanTup this is basically a dup of #69534 correct?

**Comment by DanTup** [comment] 2019-03-11 09:09
Yep, this is a dupe of #69534 / https://github.com/Dart-Code/Dart-Code/issues/1518 and is fixed in the Insiders build that was pushed just now 👍

**Comment by isidorn** [comment] 2019-03-11 09:10
Awesome, closing

**Closed by isidorn** 2019-03-11 09:10 UTC
Labels: needs more info, new release
