### ISSUE TITLE
Select + Delete causes unexpected selection

### ISSUE THREAD

**Issue by eknkc** [Microsoft/vscode#7228] opened 2016-06-05 15:44 UTC
- VSCode Version: 1.1.1
- OS Version: OSX 10.11.5 (El Cap)

Steps to Reproduce:
1. Select a code block
2. Hit backspace fast after completing the selection.

Result:

VSCode goes ahead and carries over the selection to whatever is occupying the same space now. If you wait a little after selection, the problem does not happen.

Sample:

![gif](http://d.ekin.io/17Ge0+)

**Comment by eknkc** [comment] 2016-06-05 15:58
I believe this only happens when I set ```"editor.scrollBeyondLastLine": false```

**Comment by alexandrudima** [comment] 2016-06-06 08:02
@eknkc Is it possible that you still have the mouse button pressed at the time when you press Delete?

**Comment by eknkc** [comment] 2016-06-06 11:50
@alexandrudima I don't think so. I captured the gif while using my notebooks touchpad so I was lifting my hand from it to hit backspace. Thought about trying a mouse instead to make sure it's not some hardware / physical issue but could not find one yet :). 

However, after setting `scrollBeyondLastLine` back to true, this never happened again so it's gotta be the editor doing something weird.

**Comment by zhouanbo** [comment] 2016-10-27 19:32
+1, this happens even when I have "editor.scrollBeyondLastLine": true

**Comment by crazzle** [comment] 2017-04-05 20:33
+1 too, happens for me also regardless of the value of "scrollBeyondLastLine"

**Comment by hhking** [comment] 2017-04-11 04:27
+1, happens for me too

**Comment by alexandrudima** [comment] 2017-05-10 19:41
Duplicate of #6478.

**Closed by alexandrudima** 2017-05-10 19:41 UTC
Labels: needs more info
