### ISSUE TITLE
Missing the opportunity to create a branch from the status bar

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#24124] opened 2017-04-06 18:54 UTC
VSCode Version: 1.11.1
OS Version: win7-pro

Steps to Reproduce:

1. click to status bar
![image](https://cloud.githubusercontent.com/assets/3082812/24770677/79cc1894-1b13-11e7-9a4a-8a9740c35914.png)

2. enter new branch name
![image](https://cloud.githubusercontent.com/assets/3082812/24770681/7d6f93e0-1b13-11e7-9f35-cb042a1265df.png)

PS: it worked in the previous version

**Comment by neild3r** [comment] 2017-04-06 20:05
I also miss this feature. You can still create a branch through the command palette by selecting the create branch command but seems more inconvenient.

**Comment by jsynowiec** [comment] 2017-04-06 20:51
Duplicate of #21439

**Closed** 2017-04-06 22:27 UTC
