### ISSUE TITLE
Keybinding recorder doesn't recognize ctrl+shift+u on Linux

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#119691] opened 2021-03-23 19:07 UTC
Testing #119503

record a keybinding as: ctrl+k, ctrl+shift+u

expected: a keybinding is set for ctrl+k, ctrl+shift+u

actual:

it says "unknown"

![image](https://user-images.githubusercontent.com/2644648/112203859-385cdb00-8bd0-11eb-99b2-cb1ec3308d44.png)

I'm on ubuntu 20.04. I doubt this is the fault of the new widget... but maybe.

**Comment by sandy081** [comment] 2021-03-24 09:37
@alexdima your insights would be helpful here

**Comment by alexdima** [comment] 2021-03-24 13:29
AFAIK, caused by the OS eating up that keybinding (i.e. no application receives this keybinding).

Duplicate of #96536
Duplicate of #81955
Duplicate of #73003

**Comment by waynebloss** [comment] 2021-03-30 20:27
This is not an OS problem, it's a GTK problem. Since VS Code depends on Electron, which depends on GTK - this is really an Electron issue since Electron should be able to make GTK default to a different input method.

The workaround that I found is to set `GTK_IM_MODULE` before lauching `code` as shown below. To make this permanent, I think you can put it in your launcher or in a shell file somewhere.

```sh
GTK_IM_MODULE="xim" code
```

However, I [have read](https://unix.stackexchange.com/a/262220/345742) that "XIM is a pretty obsolete input method protocol which both ibus and fcitx implement for legacy support reasons only".

**Comment by waynebloss** [comment] 2021-03-30 20:37
Other notes:

[A comment](https://github.com/microsoft/vscode/issues/48480#issuecomment-399891328) in #4840 mentions that GTK removed `ctrl+shift+e` as one of the shortcuts, leaving only `ctrl+shift+u`.

This is only for "gtkimcontextsimple" though, which is not "ibus" or "xim" as I used in the workaround above.

I believe that apps like Electron should be able to affect which input context could be used by setting [a property](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-im-module) but I actually have no idea, I'm just fishing around for solutions.

**Comment by alexdima** [comment] 2021-03-30 22:11
FYI @deepak1556 
https://github.com/microsoft/vscode/issues/119691#issuecomment-810555005
https://github.com/microsoft/vscode/issues/119691#issuecomment-810561072

**Comment by deepak1556** [comment] 2022-12-12 19:19
Closing as upstream issue has been closed.

**Closed by deepak1556** 2022-12-12 19:19 UTC
Labels: upstream, linux, upstream-issue-linked
