### ISSUE TITLE
The “go to definition” link will be abnormal when the id is with "-"

### ISSUE THREAD

**Issue by longque** [Microsoft/vscode#18637] opened 2017-01-17 07:49 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10 1607

![8](https://cloud.githubusercontent.com/assets/8530043/22011760/a48b10e8-dccb-11e6-8809-a65a7c36165b.PNG)

Steps to Reproduce:
1.Create a .ts file, define "vue-router" and input `import * as Router from "vue-router";`.
2.Move the mouse onto the "vue-router" as you press the "Ctrl".

The “go to definition” link will be abnormal, only "vue" or "router" turn blue.

**Comment by longque** [comment] 2017-01-17 07:56
Also it's abnormal when the id is with "\"
![9](https://cloud.githubusercontent.com/assets/8530043/22012048/3005d71a-dccd-11e6-877c-d8301e096158.PNG)
When I click the blue link "vuex", the "./vuex/store" will be opened but not "vuex".

**Comment by mjbvz** [comment] 2017-01-17 19:43
@longque Do you have any extensions installed? I don't think our builtin functionality provides links for TypeScript imports.

**Comment by longque** [comment] 2017-01-18 01:17
@mjbvz I don't think it's a problem caused by my extensions.

4 extensions installed

- C/C++
- C#
- Python
- Python for VSCode

It also appears in a .js file.
![10](https://cloud.githubusercontent.com/assets/8530043/22046863/656ef54e-dd5e-11e6-8541-3c379635d3c6.PNG)
"vue-router" is defined in a .d.ts file.

**Comment by mjbvz** [comment] 2017-01-18 01:59
@longque Thanks,  I'm able to repo this now. 

After investigating, this looks like a duplicate of #10037. We need a new API on the VSCode side to define the range of a definition in the source document

**Closed by mjbvz** 2017-01-18 01:59 UTC
Labels: needs more info, typescript
