### ISSUE TITLE
I get a problem when open the extension tab

### ISSUE THREAD

**Issue by voiddog** [Microsoft/vscode#20503] opened 2017-02-12 08:34 UTC
When I open the extension, I got a error: `connect ENOENT /var/folders/9f/yyj8mshd4m5ccwy1v_10hrj80000gn/T/Code-1.9.1-shared.sock`

- VSCode Version: 1.9.1
- OS Version: 10.12.3

Steps to Reproduce:

1. open visual studio code
2. switch plugin tab or install a extension

**Comment by joaomoreno** [comment] 2017-02-13 07:35
Can you restart your machine?

**Comment by voiddog** [comment] 2017-02-13 09:21
Sorry it did not work.
[Screen Shot](http://voiddog.qiniudn.com/github/issure/WX20170213-171615@2x.png)
File `Code-1.9.1-shared.sock` not exist

**Comment by joaomoreno** [comment] 2017-02-13 10:14
Duplicate of #13561

Fixed in the latest Insiders release

Workaround: start from the command line `code .`

**Closed by joaomoreno** 2017-02-13 10:14 UTC
Labels: needs more info
