### ISSUE TITLE
How to tabify code?

### ISSUE THREAD

**Issue by acterhd** [Microsoft/vscode#2776] opened 2016-02-07 14:18 UTC
Hello. How to tabify code? How to replace spaces to tabs?

**Comment by LKorowicki** [comment] 2016-02-07 15:02
#1228 it is not implemented yet

**Comment by moostad** [comment] 2016-02-08 00:37
It's on February plan list. #2616

**Comment by egamma** [comment] 2016-02-08 08:18
The current answer is to use one of the extensions, e.g., https://marketplace.visualstudio.com/items?itemName=ilich8086.Untabify.

We will see whether we can collaborate with an existing extension provider.

**Comment by egamma** [comment] 2016-02-08 08:22
Closing as a duplicate of #1228

**Closed by egamma** 2016-02-08 08:22 UTC
