### ISSUE TITLE
Multiple open instances, same PWD env

### ISSUE THREAD

**Issue by kaleb** [Microsoft/vscode#11691] opened 2016-09-08 13:57 UTC
- VSCode Version: 1.4.0
- OS Version: Ubuntu 14.04.5 LTS

Steps to Reproduce:

1. From path A, e.g. ~/projects/foo/bar, open code with the following command: `code .` We'll call this *vscode A*.
2. From path B, e.g. ~/projects/baz/qux, open code with the following command: `code .` We'll call this *vscode B*.
3. Setup runtasks for both workspaces as follows:

        {
            // See https://go.microsoft.com/fwlink/?LinkId=733558
            // for the documentation about the tasks.json format
            "version": "0.1.0",
            "command": "env",
            "isShellCommand": true,
            "args": [],
            "showOutput": "always"
        }
4. Run the task (<kbd>Ctrl+Shift+B</kbd>) from *vscode A* and notice the value of `PWD`. It should be `/home/user/projects/foo/bar`.
5. Run the task from *vscode B* and notice the value of `PWD`.

    It is **EXPECTED** to be `/home/user/projects/baz/qux`, but it isn't.

    Instead, it is **OBSERVED** as `/home/user/projects/foo/bar`, the same value as the *vscode A* instance.

**Comment by ramya-rao-a** [comment] 2016-09-08 18:23
Was able to repro this in Mac as well

**Comment by dbaeumer** [comment] 2016-09-09 13:04
This is not tasks specific. IMO this is the result of having one main process which starts a renderer process per workspace.

@bpasero moving to you to clarify this. If you think this is a tasks problem, please move back.

**Comment by bpasero** [comment] 2016-09-09 13:15
No I think this is about us not doing the right thing when copying environment values over, though I thought @joaomoreno and @sandy081 cleaned this up recently.

**Comment by joaomoreno** [comment] 2016-09-09 14:01
You are right @bpasero, this has been fixed. It does not reproduce in 1.5.0.

**Comment by kaleb** [comment] 2016-09-09 14:02
My main issue was that when running a task which was running a Makefile, it was failing because it was give the wrong PWD. Tasks has an option cwd, but I did not try that.

**Closed by joaomoreno** 2016-09-09 14:01 UTC
Labels: bug, workbench

**Comment by dbaeumer** [comment] 2016-09-11 19:39
@kaleb can you check whether you still see this in 1.5. Since the environment wasn't passed correctly pwd was not correctly set in the process from which the tasks are spawned. Hence the value was incorrect.

**Comment by kaleb** [comment] 2016-09-14 13:00
@dbaeumer Confirmed. My make files no longer blow up when multiple instances are opened.

**Comment by dbaeumer** [comment] 2016-09-14 13:36
@kaleb Great.
