### ISSUE TITLE
Drag and Drop to Browser

### ISSUE THREAD

**Issue by Ocraftyone** [microsoft/vscode#164117] opened 2022-10-20 08:52 UTC
Currently, drag and drop fails if you try to drag a file to a browser (like a drop field in a website to upload the file). I know that other IDEs like JetBrain's suite support this, but I know they are written in an entirely different language/manner. IDK much about electron or even if this is possible, but I think it would be a great feature to add!

**Comment by mjbvz** [comment] 2022-11-02 07:51
Duplicate of #164

**Closed by mjbvz** 2022-11-02 07:51 UTC
