### ISSUE TITLE
Pinned tabs do not scroll top bar when switched to active tab

### ISSUE THREAD

**Issue by Polantaris** [microsoft/vscode#110035] opened 2020-11-05 18:27 UTC
I have about 4-5 files pinned. When I select a file that causes the scrolling of the top bar with my open tabs to scroll away from these pinned items, the scroll bar does not scroll back when opening the pinned tabs again.

Sorry if this is the wrong location, I didn't see a repo related to the tabs in VSCode repo list.

System Information:
Windows 10 Enterprise v1809, OS Build 17763.1457

VSCode Information:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

I was able to reproduce on a clean app instance with no workspace/folder/etc loaded and no extensions on.

Reproduction steps:
Open 10-15 files.
Pin 2-3 of them.
Switch one of the later tabs to your active tab, so that the pinned tabs are no longer visible on the bar.
Switch back to a pinned tab.

Screenshots with untitled files and no workspace open showing this issue:
Untitled-3, 4, and 7 are pinned. All other files are not.

Screenshot 1: Untitled-14 is open.
![image](https://user-images.githubusercontent.com/47165739/98280671-57303d00-1f61-11eb-90d2-6876b219d118.png)

Screenshot 2: I switched Untitled-3. Note that Untitled-3 is open but nowhere to be found on the tab bar.
![image](https://user-images.githubusercontent.com/47165739/98280754-76c76580-1f61-11eb-9797-38199f46b1b9.png)

Screenshot 3: Shows I had to scroll to the left to see Untitled-3 on the list. Also shows how tiny the scrollbar is that honestly isn't an issue except for the fact that this bug exists.
![image](https://user-images.githubusercontent.com/47165739/98280813-9068ad00-1f61-11eb-86fb-9faac5076697.png)

The bar does not scroll to bring the tab into view like an unpinned tab would. Additionally, the scroll bar for the tab view is so tiny that it's almost pixel perfect to grab and scroll with.

**Comment by gjsjohnmurray** [comment] 2020-11-06 02:21
> Additionally, the scroll bar for the tab view is so tiny that it's almost pixel perfect to grab and scroll with.

Try `"workbench.editor.titleScrollbarSizing": "large"`

**Comment by gjsjohnmurray** [comment] 2020-11-06 02:24
Looks like a duplicate of #108561 which is apparently fixed in the upcoming 1.51 release.

**Closed** 2020-11-06 06:50 UTC
Labels: *duplicate
