### ISSUE TITLE
Panel opens when resizing side bar if both are set to render on the right

### ISSUE THREAD

**Issue by peter-applydigital** [microsoft/vscode#198701] opened 2023-11-20 19:05 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Sonoma 14.1.1

Steps to Reproduce:
1. Open VS Code with the `"workbench.sideBar.location": "right",` and `"workbench.panel.defaultLocation": "right",` settings
2. Resize the side bar and observe the panel opening.
3. Close the panel by clicking the garbage can icon or by using the "Kill Active Terminal Instance" command
4. Resize the side bar and observe the panel opening.

Notes:
* Changing the `workbench.sideBar.location` and then resizing the side bar seems to fix the issue but only as long as VS Code is open. After restarting the application the issue reappears.
* I've been using the side bar and panel locations set to the right for a couple years and if I remember correctly this issue was introduced sometime in the last year.

**Comment by sbatten** [comment] 2023-12-18 23:24
duplicate of #190972, please let me know if the comments in that issue resolve your issue.

**Closed by sbatten** 2023-12-18 23:24 UTC
