### ISSUE TITLE
 Windows Terminal under VSCode under Windows 10 ，TUI does not recognize mouse actions

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode#164800] opened 2022-10-27 11:42 UTC
The mouse can work normally under the windows terminal, but TUI (textual) the menu cannot be clicked with the mouse under the vscode windows terminal. I am using the demo program (python -m textual)
https://github.com/Textualize/textual/issues/1031

**Comment by meganrogge** [comment] 2022-11-07 17:58
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed** 2022-11-07 17:59 UTC
Labels: upstream, windows, terminal-conpty
