### ISSUE TITLE
Unchecking "Apply Setting to all Profiles" reverts setting in non-default profile

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#188794] opened 2023-07-25 14:32 UTC
Testing #188614

- Default and testing profiles.
- In default profile change color theme and enable "Apply Setting to all Profiles".
- Switch to testing profile and uncheck "Apply Setting to all Profiles". The color theme reverts to the previous one. Maybe this is intentional, but I expect it to stay the same.

**Comment by amunger** [comment] 2023-07-27 21:11
1. selected a new theme
2. selected "Apply settings to all profiles"
3. switched profiles
🐛 theme reverted

:bug: Now I can't uncheck "Apply settings to all profiles"

![Recording 2023-07-27 at 14 09 46](https://github.com/microsoft/vscode/assets/2019016/801dabd6-6d66-43a9-971f-72f3bc72ebb0)

**Comment by amunger** [comment] 2023-07-27 21:16
I noticed after posting the gif that the toggle did turn off at some point, but that wasn't happening very often. Reloading seems to have fixed it though

**Comment by amunger** [comment] 2023-07-27 21:19
Here was the first bug, the second one in the gif above isn't happening anymore
![Recording 2023-07-27 at 14 18 48](https://github.com/microsoft/vscode/assets/2019016/eb720ecd-77ce-43cc-a2a2-26b1b1170f89)

**Comment by amunger** [comment] 2023-07-27 21:31
I also tried with only built-in themes - once I had the OP behavior, and on the second try I was unable to uncheck the "Apply settings to all profiles" again

**Comment by sandy081** [comment] 2023-07-28 07:23
> I noticed after posting the gif that the toggle did turn off at some point, but that wasn't happening very often. Reloading seems to have fixed it though

I could not reproduce this. Can you please check if the setting you are toggling is getting updated in the setting `workbench.settings.applyToAllProfiles` correctly in the application settings file? To open this file you can use following commands

- If you are in default profile, "Open User Settings (JSON)"
- If you are in non default profile, "Open Application Settings (JSON)"

If the setting is getting updated correctly then it could be a UI bug. Please check and if you can repro, file a separate issue with steps. Thanks.

> Regarding first issue

selected a new theme
selected "Apply settings to all profiles"
switched profiles
🐛 new theme setting did not apply to the profile I switched to

I can repro and it seems to be a separate issue and not related to this. Hence filed a new issue for it - https://github.com/microsoft/vscode/issues/189129. Lets track this there.

I will close this and update the verification steps for this bug/fix.

**Comment by sandy081** [comment] 2023-07-28 07:25
To verify:

- Have Default and Testing Profile
- In Default profile change files.autoSave to afterDelay and enable "Apply Setting to all Profiles".
- Switch to Testing profile and uncheck "Apply Setting to all Profiles". 
- files.autoSave value should remain to afterDelay

**Closed** 2023-07-28 08:13 UTC
Labels: bug, verification-found, candidate, user-profiles
