### ISSUE TITLE
Support inspecting large data structures on 4.x and 5.x versions of node.js

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4951] opened 2016-04-05 10:02 UTC
test item for Microsoft/vscode-node-debug#11:

- [x] Windows - @jrieken 
- [x] OS X - @kieferrm 
- [x] Linux - @vsccarl 

Inspecting large data structures results in slowness (unresponsiveness) issues in node.js because the v8 debugger protocol does not provide a way to access large data structures in chunks. Always the full thing travels over the wire. A particular nasty issue is that local variables are included in the stack frame object "for free" even if nobody requested them. A consequence is that stepping through code with large arrays or buffers in local variables or parameters results in slowness and timeouts.

In node 0.12.x VS Code started to dynamically inject code into the node runtime to improve the v8 debugging protocol but this stopped working after the io.js/node.js reunion for 2.x and 3.x versions. After fix https://github.com/nodejs/node/pull/4328 code injection started to work again in node.js 4.3.1 in the LTS stream. For the 5.x stable stream the code injection has to use a slightly different approach that started to work in node 5.6.
 
Verify for node.js >= 4.3.1 and node.js >= 5.6 that:
- you can inspect large (~ 100000) arrays and buffers without node.js becoming unresponsive

Please note: this feature is not about objects with many properties. Objects with many properties will be addressed in Microsoft/vscode-node-debug#18.

**Comment by joewood** [comment] 2016-04-20 14:10
The debugger for node is pretty much unusable right now. Will this be fixed any time soon? This is using node 4.4.2. VS Code 1.0.  I don't see this related to large data structures, I see this when stepping any code, nothing in the watch window.

**Comment by weinand** [comment] 2016-04-20 16:47
@joewood could you please try to debug the same code with node-inspector?

**Comment by weinand** [comment] 2016-04-20 22:03
@joewood since you are the first who reports that node debug "is unusable in VS Code 1.0" it cannot be a wide spread issue. Could you please share some details about your problem so that we can investigate.

**Comment by joewood** [comment] 2016-04-22 14:15
Hi @weinand, I did a bit of investigation.

I tried node-inspector and didn't see the issue. But, I did see the problem when I added my data structure to the watch window. Background here is that this module that I'm debugging has a large data structure loaded into memory. If I add this structure explicitly to node-inspector I see a similar timeouts. 

However, in VSCode I see the problem consistently, even with an empty watch window.  So I assume the issue is related to what VSCode is watching by default (locals and context scope etc..) and what it's transferring each time I step through the debugger.

With that in mind I did a quick repro:
```javascript
const faker = require("faker");

let data = {};

console.log("Running");

for(let n=0; n<100000; n++) {
    data["1" +n] = faker.name.firstName();
}

console.log("Breakpoint");
console.log("Breakpoint1");
console.log("Breakpoint2");
console.log("Breakpoint3");
```

Setting the breakpoint on the first `console.log("Breakpoint")`, then stepping over causes the problem consistently. Without anything in the watch window.

I'm running on an intel i7 4GHz, 16GB RAM.

**Comment by weinand** [comment] 2016-04-22 20:55
@joewood thanks for your investigation.
Since this is a test plan item which is unrelated to your problem, I have moved your comment to https://github.com/Microsoft/vscode/issues/5645.

**Comment by kieferrm** [comment] 2016-04-26 23:29
I tested with 5'000'000 items in an array on node v4.4.3 and node v5.9.1. It works beautifully. Even expanding the array in the variables view worked without issues (and nice progress icon).

**Comment by joewood** [comment] 2016-04-26 23:50
I think arrays are fine, did you try an object?

**Comment by kieferrm** [comment] 2016-04-27 00:59
@joewood I tried your test case from #5645. Stopping on a break point is reasonably fast although no data is presented (I'm guessing that is when the timeout is happening.) Using Step Over next fails immediately. 

<img width="1188" alt="screen shot 2016-04-26 at 5 57 17 pm" src="https://cloud.githubusercontent.com/assets/4674940/14838690/9b2d2f0a-0bd8-11e6-8816-151e5200366a.png">

**Comment by weinand** [comment] 2016-04-27 10:58
@joewood @kieferrm this feature is not about objects with many properties. Objects with many properties will be addressed in https://github.com/Microsoft/vscode-node-debug/issues/18.

**Comment by kieferrm** [comment] 2016-04-27 14:16
@weinand thanks for clarifying.

**Closed** 2016-04-27 21:43 UTC
Labels: testplan-item
