### ISSUE TITLE
Pty host is unresponsive after opening and closing terminal. Happens quite often.

### ISSUE THREAD

**Issue by asdfgh5889** [microsoft/vscode#202219] opened 2024-01-11 06:05 UTC
Type: <b>Bug</b>

Launching terminal and closing it causes Pty host to become unreponsive. I've tried disabling all extension but didn't help and I've tried VSCode insider version too.
Here is pty host log after opening and closing terminal:
```
[H]0;C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe[?25h
2024-01-11 08:52:59.349 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":1,"event":"\u001b[?9001h\u001b[?1004h\u001b[?25l\u001b[2J\u001b[m\u001b[H\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\u001b[H\u001b]0;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\u0007\u001b[?25h"})
2024-01-11 08:52:59.353 [trace] [RPC Request] PtyService#input(1, "\u001b[I")
2024-01-11 08:52:59.353 [debug] MutationLogger "Persistent process "1" interaction state" set to "Session", reason: input
2024-01-11 08:52:59.353 [trace] node-pty.IPty#write [I
2024-01-11 08:52:59.354 [trace] [RPC Response] PtyService#input undefined
2024-01-11 08:52:59.824 [trace] [RPC Request] PtyService#setTerminalLayoutInfo({"workspaceId":"1704952365603","tabs":[{"isActive":true,"activePersistentProcessId":1,"terminals":[{"relativeSize":1,"terminal":1}]}]})
2024-01-11 08:52:59.824 [trace] [RPC Response] PtyService#setTerminalLayoutInfo undefined
2024-01-11 08:52:59.824 [trace] [RPC Request] PtyService#updateIcon(1, false, {"id":"terminal","defaults":{"fontCharacter":"\\ea85"}}, )
2024-01-11 08:52:59.824 [trace] [RPC Response] PtyService#updateIcon undefined
2024-01-11 08:52:59.869 [trace] [RPC Request] PtyService#updateTitle(1, "powershell", 2)
2024-01-11 08:52:59.869 [trace] [RPC Response] PtyService#updateTitle undefined
2024-01-11 08:53:00.179 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":1,"property":{"type":"shellType","value":"pwsh"}})
2024-01-11 08:53:00.179 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":1,"property":{"type":"title","value":"powershell.exe"}})
2024-01-11 08:53:00.333 [trace] node-pty.IPty#onData ]633;P;IsWindows=True
2024-01-11 08:53:00.339 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":1,"event":"\u001b]633;P;IsWindows=True\u0007"})
2024-01-11 08:53:00.695 [trace] node-pty.IPty#onData ]633;A]633;P;Cwd=C:\x5cUsers\x5casdfgh5889PS C:\Users\asdfgh5889> ]633;B
2024-01-11 08:53:00.706 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":1,"event":"\u001b]633;A\u0007\u001b]633;P;Cwd=C:\\x5cUsers\\x5casdfgh5889\u0007PS C:\\Users\\asdfgh5889> \u001b]633;B\u0007"})
2024-01-11 08:53:00.722 [debug] CommandDetectionCapability#handlePromptStart 0 0
2024-01-11 08:53:00.753 [debug] CommandDetectionCapability#_tryAdjustCommandStartMarker adjusted promptStart 0 -> 0
2024-01-11 08:53:00.753 [debug] CommandDetectionCapability#_tryAdjustCommandStartMarker adjusted commandStart 0 -> 0:24
2024-01-11 08:53:00.753 [debug] CommandDetectionCapability#_handleCommandStartWindows 24 0
2024-01-11 08:53:04.096 [trace] [RPC Request] PtyService#input(1, "\u001b[O")
2024-01-11 08:53:04.096 [trace] node-pty.IPty#write [O
2024-01-11 08:53:04.096 [trace] [RPC Response] PtyService#input undefined
2024-01-11 08:53:10.022 [trace] [RPC Request] PtyService#input(1, "\u001b[I")
2024-01-11 08:53:10.022 [trace] node-pty.IPty#write [I
2024-01-11 08:53:10.022 [trace] [RPC Response] PtyService#input undefined
2024-01-11 08:53:10.527 [trace] [RPC Request] PtyService#setTerminalLayoutInfo({"workspaceId":"1704952365603","tabs":[{"isActive":true,"activePersistentProcessId":1,"terminals":[{"relativeSize":1,"terminal":1}]}]})
2024-01-11 08:53:10.528 [trace] [RPC Response] PtyService#setTerminalLayoutInfo undefined
2024-01-11 08:53:11.480 [trace] [RPC Request] PtyService#shutdown(1, false)
2024-01-11 08:53:11.481 [trace] TerminalProcess#shutdown 
    at t.shutdown (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:19046)
    at V.shutdown (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:37644)
    at D.shutdown (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:28377)
    at T.<computed> (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:22735)
    at Object.call (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:34:5041)
    at q.s (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:32:5153)
    at q (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:32:4662)
    at a.value (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:32:4064)
    at i.y (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:27:1906)
    at i.z (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:27:1976)
    at i.fire (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:27:2192)
    at MessagePortMain.ce (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:25:10117)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2024-01-11 08:53:11.481 [trace] TerminalProcess#_queueProcessExit 
    at t.X (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:18210)
    at t.shutdown (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:19140)
    at V.shutdown (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:37644)
    at D.shutdown (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:28377)
    at T.<computed> (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:43:22735)
    at Object.call (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:34:5041)
    at q.s (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:32:5153)
    at q (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:32:4662)
    at a.value (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:32:4064)
    at i.y (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:27:1906)
    at i.z (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:27:1976)
    at i.fire (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:27:2192)
    at MessagePortMain.ce (c:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:25:10117)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2024-01-11 08:53:11.482 [trace] [RPC Response] PtyService#shutdown undefined
2024-01-11 08:53:11.746 [trace] node-pty.IPty#kill
2024-01-11 08:53:11.758 [trace] [RPC Event] PtyService#_onProcessExit.fire({"id":1,"event":0})
```

Here is Main logs related to pty:
```
2024-01-11 08:52:57.405 [trace] resolveShellEnv(): skipped (Windows)
2024-01-11 08:52:58.936 [debug] Terminal profile not validated bash (MSYS2) [{"path":"C:\\msys64\\usr\\bin\\bash.exe","isUnsafe":true}]
2024-01-11 08:52:58.937 [debug] Terminal profile not validated Cygwin [{"path":"C:\\cygwin64\\bin\\bash.exe","isUnsafe":true},{"path":"C:\\cygwin\\bin\\bash.exe","isUnsafe":true}]
2024-01-11 08:52:59.006 [trace] [UtilityProcess type: ptyHost, pid: <none>]: creating new...
2024-01-11 08:52:59.006 [trace] PtyHostService#_startPtyHost 
    at g.U (C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:103:2969)
    at g.h (C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:103:1428)
    at C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:103:2488
    at $.value (C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:33:28425)
    at a.y (C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:35:1902)
    at a.fire (C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:35:2119)
    at m.r (C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:105:62696)
    at C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:105:61381
    at IpcMainImpl.u (C:\Users\asdfgh5889\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:18858)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88654)
    at WebContents.emit (node:events:513:28)
2024-01-11 08:52:59.018 [trace] [UtilityProcess type: ptyHost, pid: 24332]: successfully created
```

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.26020 (W11 Canary Channel 26020.1000)
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (19.27GB free)|
|Process Argv|--disable-extensions --log trace .\\rtsp\\ --crash-reporter-id fdcc50ab-16d6-475d-9c33-3a36ebbde26a|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019a:30933241

```

</details>

**Comment by meganrogge** [comment] 2024-01-11 13:58
likely duplicate of https://github.com/microsoft/vscode/issues/201129

**Closed by meganrogge** 2024-01-11 13:58 UTC

**Comment by asdfgh5889** [comment] 2024-01-12 13:58
> likely duplicate of #201129

How is it duplicate? While I'm also having same issue while using remote-ssh extension in this issue I'm talking about windows launches not remote linux. It is happening more often compared to remote linux connection, just closing single terminal causes the issue on windows while in remote linux it happens when I close one of vscode instances.

**Comment by asdfgh5889** [comment] 2024-02-03 14:21
This might be related to the fact that I'm running the windows insider canary build. Using winpty backend instead of conpty solved the problem.
