### ISSUE TITLE
Extension installation keeps in status "installing"

### ISSUE THREAD

**Issue by wellsluo** [Microsoft/vscode#13796] opened 2016-10-15 09:32 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: ms-vscode.PowerShell-0.7.2, robertohuertasm.vscode-icons-3.0.4

Steps to Reproduce:

1. Start Code.exe
2. Search extension, like "Chef"
3. Click "install" button.  The status keeps in "installing" for hours. 

Elevation mode doesn't help.

**Comment by joaomoreno** [comment] 2016-10-20 12:51
Are you behind a proxy? I also see you are in China, closing as duplicate of #7853

**Closed by joaomoreno** 2016-10-20 12:51 UTC
