### ISSUE TITLE
Opening tab does not redirect to folder in explorer

### ISSUE THREAD

**Issue by gohar94** [Microsoft/vscode#68747] opened 2019-02-14 23:29 UTC
Issue Type: <b>Bug</b>

When I open a new file using Ctrl-P, it is no more taking me to that folder in the side file explorer whereas it used to do this probably before the latest update. Seems like a bug.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (12.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
todo-tree|Gru|0.0.118
vscode-nmake-tools|Mic|1.1.190201002
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
vim|vsc|1.0.8

</details>

**Comment by yume-chan** [comment] 2019-02-18 06:50
Possible duplicate of #68597?

**Closed** 2019-03-05 19:55 UTC
Labels: *duplicate, integrated-terminal
