### ISSUE TITLE
Source control graph detail info disapear

### ISSUE THREAD

**Issue by mmradtke** [microsoft/vscode#235483] opened 2024-12-06 11:43 UTC
Type: <b>Bug</b>

When i hover over a item in source control graph, the deails are shown. If i want to go with my mouse pointer to the detail popup (straight to the right), the info popup disaper when i enter it. If you move the mouse pointer very fast, then perhaps you can enter the info popup. 

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id aa1adc25-e589-40a7-b7a3-c63979a888b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-django|bat|1.15.0
gitignore|cod|0.9.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
xml|Dot|2.5.1
prettier-vscode|esb|11.0.0
todo-tree|Gru|0.0.226
rest-client|hum|0.25.1
rainbow-csv|mec|3.13.0
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
pylint|ms-|2024.0.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.12.1
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
vscode-remote-extensionpack|ms-|0.26.0
live-server|ms-|0.4.15
remote-explorer|ms-|0.4.3
vsliveshare|ms-|1.0.5941
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.15.0
vscode-css-peek|pra|4.4.1
vscode-yaml|red|1.15.0
easy-compile|ref|1.2.5
errorlens|use|3.20.0
vscodeintellicode|Vis|1.3.2
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by sandy081** [comment] 2024-12-06 13:05
I verified that on extensions view since it shares the same problem

**Comment by lszomoru** [comment] 2024-12-09 13:20
@mmradtke, this should be fixed. Could you please provide a recording while reproducing the issue (https://gifcap.dev). Thanks!

**Comment by mmradtke** [comment] 2024-12-10 11:30
Sure, no problem.

![Image](https://github.com/user-attachments/assets/42f5f629-419a-4cf5-8b55-e05c6d6300f8)

**Comment by lszomoru** [comment] 2024-12-10 14:44
Adding @Tyriar and @benibenj since this is a hover issue and not specific to the SCM graph.

**Comment by benibenj** [comment] 2024-12-10 16:03
@Tyriar made a fix which is available in Insiders but not in `1.95.3`. @mmradtke you should see this fixed in the next update.

@gjsjohnmurray you mentioned this is still happening for you in insiders. Do you mean it is still theoretically possible to happen or does it actually regularly disappear when you try to move your mouse over the hover? 
The fix is based on a timeout. We are aware that this means it is still possible to hide, but our experience has shown that this hardly ever happens on accident.

**Comment by gjsjohnmurray** [comment] 2024-12-10 17:03
@benibenj I can't really tell because on Insiders I use a layout with Primary Sidebar on the right. This means that the graph hover tips aren't on the scrollbar side of the view, and consequently the problem doesn't occur.

**Closed** 2024-12-11 07:45 UTC
Labels: info-needed, workbench-hover

**Comment by Tyriar** [comment] 2024-12-11 09:02
> The fix is based on a timeout. We are aware that this means it is still possible to hide, but our experience has shown that this hardly ever happens on accident.

:+1: it's definitely still possible to hide if the cursor moves slow enough.
