### ISSUE TITLE
Github Authentication failed 

### ISSUE THREAD

**Issue by Generation4** [microsoft/vscode#137348] opened 2021-11-17 07:13 UTC
Issue Type: <b>Bug</b>

After updating vscode version the connection to github getting errors.
When running git pull I got this error:
remote: Repository not found.
fatal: Authentication failed for xxxxxxxx

Tried to logout, login, restart and more..
In linux terminal it's working. only on vscode terminal I get this error.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.11.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 1977)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.43GB (5.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id f0e903eb-9761-4aac-87f9-8cbb35421942|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.4.0
laravel-blade-vscode|ami|2.0.3
vscode-intelephense-client|bme|1.7.1
gitignore|cod|0.7.0
vscode-mysql-client2|cwe|4.2.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
vscode-npm-script|eg2|0.3.23
php-debug|fel|1.22.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.205.2
vetur|oct|0.35.0
laravel5-snippets|one|1.13.0
autoimport|ste|1.5.4
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-17 08:13
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Closed** 2021-11-17 08:14 UTC
Labels: *duplicate

**Comment by pinkedge** [comment] 2021-11-17 08:38
degrade to Version: 1.62.1, then world peace.
It took me almost an afternoon to locate the problem and thought there is a wrong configuration somewhere.

**Comment by Generation4** [comment] 2021-11-18 05:59
> degrade to Version: 1.62.1, then world peace. It took me almost an afternoon to locate the problem and thought there is a wrong configuration somewhere.

You saved me alot of time
Thanks!

**Comment by heyjoe1984** [comment] 2021-11-18 18:36
for those of you who need to downgrade because of this huge bug, download 1.6.1 here:

https://code.visualstudio.com/updates/v1_61

just uninstall 1.6.2 and then install this version (1.6.1) and the GitHub pushing issues go away

**Comment by gjsjohnmurray** [comment] 2021-11-18 20:31
1.62.3 has been published and contains the fix for this.
