### ISSUE TITLE
Blurry UI on Wayland + GNOME 200% scaling

### ISSUE THREAD

**Issue by PHLAK** [microsoft/vscode#192590] opened 2023-09-08 15:35 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.0
- OS Version: Arch Linux (rolling) + Wayland (v1.22.0)

Steps to Reproduce:

1. Run a Linux distribution + Wayland + GNOME
2. Set display scaling to 200%
3. Launch VS Code (with or without `--ozone-platform-hint=auto`)
4. Observe the UI is blurry

I am running this on a 4K (3840 x 2160) monitor with 200% scaling configured in the GNOME display settings. I also observed the following warnings that may or may not be relevant here.

```
[7962:0908/080844.064895:WARNING:wayland_surface.cc(165)] Server doesn't support zcr_alpha_compositing_v1.
[7962:0908/080844.064905:WARNING:wayland_surface.cc(180)] Server doesn't support overlay_prioritizer.
[7962:0908/080844.064908:WARNING:wayland_surface.cc(194)] Server doesn't support surface_augmenter.
[7962:0908/080844.064911:WARNING:wayland_surface.cc(209)] Server doesn't support wp_content_type_v1
[7962:0908/080844.064913:WARNING:wayland_surface.cc(228)] Server doesn't support zcr_color_management_surface.
```

**Comment by asuka909** [comment] 2023-09-09 03:45
VS Code Version: 1.82.0
Reproduced this on fedora 38 silverblue + wayland + gnome 44  with --ozone-platform-hint=auto.

**Comment by hummerd** [comment] 2023-09-09 09:11
Same problem exists on Chrome 114+ (under gnome's wayland). But on chrome it can be fixed with `--disable-features=WaylandFractionalScaleV1` flag which is not working with vscode.

**Comment by claytonwramsey** [comment] 2023-09-10 22:18
Same issue here, using Fedora 38 / Wayland / GNOME 44. It happened both with `--ozone-platform-hint=auto` and `--ozone-platform=wayland`. This kind of sucks, since Wayland is far more performant than X11, which means I either get blurry text or a bad framerate :(.

**Comment by deepak1556** [comment] 2023-09-11 10:25
Looks like the issue is already tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=1356014

> But on chrome it can be fixed with --disable-features=WaylandFractionalScaleV1 flag which is not working with vscode.

Since we maintain a disable list from the application code, it overrides the ones from command line. I will address this so that the flag can be used as workaround in VSCode as well.

**Comment by thrashwerk** [comment] 2023-09-11 14:43
I noticed that VS Code (and other XWayland apps like Firefox and Chromium) become blurry after enabling Gnome experimental fractional scaling `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"` (but still leaving scaling at 200%).

Without that experimental feature those apps are crisp.

**Comment by PHLAK** [comment] 2023-09-11 15:27
> I noticed that VS Code (and other XWayland apps like Firefox and Chromium) become blurry after enabling Gnome experimental fractional scaling `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"` (but still leaving scaling at 200%).
> 
> Without that experimental feature those apps are crisp.

I do not have fractional scaling enabled.

```
$ gsettings get org.gnome.mutter experimental-features
@as []
```

**Comment by PHLAK** [comment] 2023-09-11 15:29
Also, I believe this is the relevant upstream (Chromium) issue.

https://bugs.chromium.org/p/chromium/issues/detail?id=1356014

However, the `--disable-features=WaylandFractionalScaleV1` flag does not help when I pass it to Code.

**Comment by marco-qed** [comment] 2023-09-12 19:57
VS Code Version: 1.82.0
Reproduced this on Arch Linux (Hyprland with Wayland) with --ozone-platform-hint=auto. Font is blurry both on fractional scaled monitor and monitor at native 100% scaling.

Downgrading to version 1.81.1 fixed the issue temporarily for me.

**Comment by hazzus** [comment] 2023-09-13 10:22
Kind of the same isssue on 1.82.0 with Sway
Previously I was launching VS Code like this in order to launch prefectly on wayland+scaling:
`code --enable-features=UseOzonePlatform --ozone-platform=wayland`
Now this crashes code and logs are empty, downgraded.

**Comment by claytonwramsey** [comment] 2023-09-14 16:08
I just updated to 1.82.1. The same issue occurs (Fedora, Wayland, GNOME 44, 200% DPI scaling).

**Comment by deepak1556** [comment] 2023-09-22 12:11
`--disable-features=WaylandFractionalScaleV1` will work with tomorrow's insider, please use that as a workaround until the upstream issue is resolved.

**Comment by v-tibi** [comment] 2023-09-26 14:55
So my issue got merged into this one, it probably has something in common with this issue. 

In my case I run a multi monitor setup where I have a monitor on my desk which I run at 100% scaling and it is connected to my laptop which I run at 150% scaling. I start Vscode with the usual --ozone-platform=wayland flag so it runs in native wayland mode. 
Everything looks great and sharp when I have the screens positioned so that the one with fractional scaling is to the left or on top of the other screen. Fonts are blurry if the screens are positioned in the other two possible locations.

Using the reload window command from the palette solves the issue in these cases.

**Comment by bigkrp** [comment] 2023-10-10 07:16
> Also, I believe this is the relevant upstream (Chromium) issue.
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=1356014
> 
> However, using the `--disable-features=WaylandFractionalScaleV1` flag as suggested does not help when I pass it to Code.

For google-chrome, it doesn't help as well.
I have same problem. Additional monitor with scale 100% and laptop 3200x1800 scaled to 200%. On monitor, google-chrome displays well, for laptop's display everything is blurred.

**Comment by avinashkanaujiya** [comment] 2023-11-30 06:09
Whe trying to use `--disable-features=WaylandFractionalScaleV1`, I am getting a below warning and it is not workin for me.
```
Warning: 'disable-features' is not in the list of known options, but still passed to Electron/Chromium.

```

**Comment by deepak1556** [comment] 2023-11-30 06:27
Upstream issue closed it as resolved, per https://bugs.chromium.org/p/chromium/issues/detail?id=1356014#c58 seems like GNOME 45 and higher should work fine.

I will close this issue out as it is outside VSCode.

**Closed by deepak1556** 2023-11-30 06:27 UTC
Labels: bug, upstream, linux, upstream-issue-linked, chromium, mitigated, wayland
