### ISSUE TITLE
Simple CSS Editor Customization

### ISSUE THREAD

**Issue by rauschmerscen** [microsoft/vscode#106750] opened 2020-09-15 11:51 UTC
It would be nice if VS Code was styleable like Atom. A simple CSS file that would allow developers to customize the Layout, Design, Fonts etc.
There are hacks to achieve this but they are Hacks, they affect the stability of VS Code. The workbench css file can also be editted to achieve this but it's a pain. So an official way of doing things right would be nice.

**Comment by aeschli** [comment] 2020-09-16 09:15
We want to control the ways that VSCode can be customized. For that we offer by well defined APIs such as color and icons themes. That way we keep the freedom to refactor and can change internals and the UI without breaking any extension.
So allowing custom css is not planed. 

Duplicate of https://github.com/microsoft/vscode/issues/1833

**Closed by aeschli** 2020-09-16 09:15 UTC
