### ISSUE TITLE
Changing tasks command does not actually change command

### ISSUE THREAD

**Issue by freed2003** [microsoft/vscode#140179] opened 2022-01-05 18:42 UTC
Issue Type: <b>Bug</b>

1. Pick a task in tasks.json and change the command from a to b
2. Run the task

Expected: command b is performed
Actual: command a is still used

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1500X Quad-Core Processor           (8 x 3493)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.00GB free)|
|Process Argv|--crash-reporter-id 9b119bdf-56dc-424b-bc0f-2969ca4c99da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
exe-runner|bra|0.2.1
doxdocgen|csc|1.3.2
code-runner|for|0.11.6
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614
py55gd98cf:30419166
vscexrecpromp3t2:30407763

```

</details>

**Comment by alexr00** [comment] 2022-01-06 14:07
I'm not able to reproduce this issue. Can you share the exact tasks.json files you use for command a and command b?

**Comment by hengkx** [comment] 2022-01-07 01:05
Any open ts or js files cannot work

**Comment by freed2003** [comment] 2022-01-07 03:00
> 

The issue seems to have fixed itself somehow as I am no longer able to reproduce it as well. The command was replacing "cl.exe" with the full path to itself (I am aware I should run the bat scripts for MSVC, I just wanted to test it), but the tasks still run just "cl.exe". I was able to change other parts of the task such as the lable. Though, it seems to work as expected now.

**Comment by alexr00** [comment] 2022-01-07 08:46
There was a much older version (maybe 10+ versions ago?) where I saw this problem and fixed it. Closing, and we can re-open if the issue occurs.

**Closed by alexr00** 2022-01-07 08:46 UTC
Labels: needs more info
