### ISSUE TITLE
vscode freezes on start on Redhat 7.9

### ISSUE THREAD

**Issue by abhinav1592** [microsoft/vscode#120087] opened 2021-03-29 09:32 UTC
- VS Code Version: code-1.54.3-1615806453.el7.x86_64
- OS Version: 

[abcd@oc3sdfdgsd Documents]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Workstation"
VARIANT_ID="workstation"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Workstation 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:workstation"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

Steps to Reproduce:

1. Install vscode using yum 
2. Start vscode. It freezes immediately.

Does this issue occur when all extensions are disabled?:  Yes

![image](https://user-images.githubusercontent.com/2583022/112817112-b6712400-909f-11eb-9db6-054c663d4bc0.png)

**Comment by gjsjohnmurray** [comment] 2021-03-29 13:20
/duplicate of #115784. Subscribe to it if you want to be notified of any change to the status of VS Code's compatibility with CentOS 7.

**Closed** 2021-03-29 13:21 UTC
Labels: *duplicate
