### ISSUE TITLE
Allow files explorer navigation by typing name

### ISSUE THREAD

**Issue by quasarea** [Microsoft/vscode#29325] opened 2017-06-23 12:45 UTC
I would like to be able to type a name of a file to navigate to it using explorer. 

Example:
* pressing 'w' when focus is in explorer window will select first file that begins with 'w' 
* pressing 'a' later selects first file that name begins with 'wa' 
* this 'wa' buffer is cleared when arrow key is pressed.

**Comment by isidorn** [comment] 2017-06-23 14:25
Duplicate of an already opened issue, please search our issues to find the duplicate if you want to upwote it

**Closed by isidorn** 2017-06-23 14:25 UTC
Labels: workbench
