### ISSUE TITLE
interface scaling problem

### ISSUE THREAD

**Issue by nmagretov** [Microsoft/vscode#23072] opened 2017-03-23 05:35 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.2.5|
|vscode-svgviewer|cssho|1.4.0|
|vscode-icons|robertohuertasm|7.4.0|
|code-settings-sync|Shan|2.6.1|
|stylelint|shinnn|0.23.0|
|Material-theme|zhuangtongfa|2.3.3|
|html-css-class-completion|Zignd|1.0.3|;

---
My workscreen has limits in some views/settings

Steps to Reproduce:
I use  

"window.zoomLevel": 1,

setting to set scale up (15.6 inch 1920*1080 screen)

1. That`s how it looks: 
https://yadi.sk/i/Brlk-68m3GGFwi 
https://yadi.sk/i/3hT0xBAH3GGG5B

**Comment by mjbvz** [comment] 2017-03-23 05:47
This is a duplicate of #5745

**Closed by mjbvz** 2017-03-23 05:47 UTC
Labels: duplicate, webview

**Comment by nmagretov** [comment] 2017-03-23 10:27
Sorry, i didn`t get: how can i fix it? Or i can`t do it for now?
