### ISSUE TITLE
Asterisks No Longer Triggering Italics with Markdown

### ISSUE THREAD

**Issue by insaneirish** [Microsoft/vscode#45012] opened 2018-03-04 13:44 UTC
For some reason, text bounded by asterisks is no longer triggering italics syntax highlighting in Markdown.

```
_this still works to make italics_
```

```
*while this does not*
```
<img width="680" alt="screen shot 2018-03-04 at 08 40 52" src="https://user-images.githubusercontent.com/612204/36946269-463b05ec-1f88-11e8-9d94-c24cd2aa240d.png">

**Comment by insaneirish** [comment] 2018-03-05 00:16
Comment there says: "Thanks! This will be in the next insiders build and is on track for VS Code 1.20". Did it get included in 1.20? I'm on 1.20.1.

**Comment by mjbvz** [comment] 2018-03-05 07:19
Duplicate of #43629

@insaneirish This is fixed in 1.21 (the current insiders builds)

**Closed by mjbvz** 2018-03-05 07:19 UTC
Labels: markdown
