### ISSUE TITLE
Autocomplete for folders macOS

### ISSUE THREAD

**Issue by radostnomne** [Microsoft/vscode#25238] opened 2017-04-24 17:38 UTC
not working autocomplete in path.
Mac os sierra 10.12.4
step to reproduce:
1. open js or ts project.
2. try to import any module (using import or require)
Expected result: autocomplete in path or autocomplete from folder node_modules.

**Comment by mjbvz** [comment] 2017-04-24 23:01
Can you manually trigger intellisense for the path using the `Trigger Suggest` command, <kbd>ctrl</kbd><kbd>space</kbd> by default? If so, this may be a duplicate of  #23962

**Comment by radostnomne** [comment] 2017-04-26 07:25
It helps me, thank you.
`"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
}`

**Closed** 2017-04-26 07:25 UTC
Labels: javascript, needs more info, typescript
