### ISSUE TITLE
Extension host restarting 

### ISSUE THREAD

**Issue by Baz00k** [microsoft/vscode#177069] opened 2023-03-14 11:08 UTC
Type: <b>Bug</b>

I saw multiple issues regarding extension host quiting unexpectedly and restarting multiple times and I tried to narrow down the problem. I ran extension bisect multiple times and could not pinpoint any extension that could be the root cause of the problem. What I found is that when autocompletion is active and you select an option that requires additional import (I tested it in TypeScript codebase) extension host restarts. 
It also sometimes restarts with no apparent reason.
Reinstalling VSC did not solve the issue.
Issue does not persist with all extensions disabled.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (18.40GB free)|
|Process Argv|--crash-reporter-id e0cd9488-ca55-48f1-b408-5f94d1f2f6b5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
user-secrets|adr|2.0.1
vscode-essentials|agu|1.0.3
TabOut|alb|0.2.2
html-end-tag-labels|ant|0.11.0
change-color-format|bbu|1.2.0
vscode-tailwindcss|bra|0.9.8
vscode-toggle-quotes|Bri|0.3.6
directory-files|cas|0.0.5
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
cssrem|cip|3.1.0
quasar-docs|Cod|1.4.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
vscode-faker|dee|2.0.0
vscode-notes|dio|1.1.0
githistory|don|0.6.20
xml|Dot|2.5.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
comment-anchors|Exo|1.10.3
vscode-solution-explorer|fer|0.8.1
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.77.9225
copilot-labs|Git|0.12.791
vscode-pull-request-github|Git|0.60.0
gc-excelviewer|Gra|4.2.56
hungry-delete|jas|1.7.0
unity-code-snippets|kle|1.3.0
i18n-ally|lok|2.8.1
regexp-preview|Lou|0.1.5
vscode-language-babel|mgm|0.0.37
vscode-checkpoints|mic|1.3.3
dotenv|mik|1.0.1
goto-next-previous-member|mis|0.0.6
vue-volar-extention-pack|Mis|1.1.8
vscode-duplicate|mrm|1.2.1
csharp|ms-|1.25.4
vscode-dotnet-pack|ms-|1.0.12
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vsliveshare|ms-|1.0.5834
vscode-twoslash-queries|Ort|1.1.0
material-icon-theme|PKi|4.24.0
vscode-yaml|red|1.12.1
vscode-sort-json|ric|1.20.0
gi|rub|0.2.11
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
vue-vscode-snippets|sdr|3.1.1
autoimport|ste|1.5.4
sass-indented|syl|1.8.26
sort-lines|Tyr|1.9.1
vscode-mdx|uni|1.2.5
errorlens|use|3.8.0
learn-vim|vin|0.0.28
gistfs|vsl|0.4.1
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0
vscode-wakatime|Wak|24.0.7
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
vscode-surround|yat|1.5.0
markdown-all-in-one|yzh|3.5.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsccsb:30677849
pythonb192cf:30669361
funwalk2:30682974

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-14 18:55
A lot of similar recent issues have pointed to the GitHub Copilot extension as a cause.

**Comment by isidorn** [comment] 2023-03-15 11:11
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:11 UTC
Labels: freeze-slow-crash-leak, extension-host, triage-needed
