### ISSUE TITLE
all extensions uninstalled from settings sync when started using remote tunnel

### ISSUE THREAD

**Issue by glekner** [microsoft/vscode#169761] opened 2022-12-21 16:34 UTC
Type: <b>Bug</b>

Once enabled Remote tunnel.
and coding a bit with vscode.dev
I returned to my primary machine and saw all my extensions disabled, uninstalled and not available in my settings sync

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:32:21.587Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|64.00GB (19.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.11
beardedicons|Bea|1.2.0
vscode-tailwindcss|bra|0.9.1
multi-cursor-case-preserve|Car|1.0.5
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
prettier-vscode|esb|9.10.3
copilot|Git|1.65.7705
remotehub|Git|0.48.0
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.95.2022121915
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
anycode-c-sharp|ms-|0.0.5
anycode-cpp|ms-|0.0.5
anycode-go|ms-|0.0.5
anycode-java|ms-|0.0.5
anycode-php|ms-|0.0.6
anycode-python|ms-|0.0.5
anycode-rust|ms-|0.0.6
anycode-typescript|ms-|0.0.5
azure-repos|ms-|0.24.0
remote-explorer|ms-|0.1.2022121209
remote-repositories|ms-|0.26.0
remote-server|ms-|1.0.0
hex-to-tailwind|Ted|1.1.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment] 2022-12-22 15:15
May I know if you can reproduce it consistently? If so can you please share the steps? Also share following logs when you reproduce?

- F1 > Open View... > Remote Server
- F1 > Open View... > Shared

**Comment by glekner** [comment] 2022-12-22 15:31
do you have access to my github sync logs? if not i'm afraid to reproduce it and rather avoid it.

could settings sync see the tunnel as a new environment and override the config of the user?

anyway, feel free to close the issue if u cant reproduce

**Comment by sandy081** [comment] 2022-12-26 08:36
We do not have access to any of our data. Sorry that I cannot reproduce it and closing it. Thanks for sharing.

**Closed by sandy081** 2022-12-26 08:36 UTC
Labels: info-needed, extensions
