### ISSUE TITLE
Settings on when suggestions are showing up

### ISSUE THREAD

**Issue by oiiiiiiii** [microsoft/vscode#145603] opened 2022-03-21 18:28 UTC
Currently, the suggestion menu is not showing up if my custom snippet begins with a non-letter character. For example when I have a snippet with the prefix "->", or "=>" (which is supposed to insert an arrow in LaTeX) the suggestions menu is not showing. I see that it makes sense not to view any suggestions there when programming, but I would like to have an option to activate it anyways for certain file types (e.g. .tex).

**Comment by jrieken** [comment] 2022-03-22 07:41
Today, quick suggestion only happens at word ends. Not at non-words nor inside words. Closing this as dupe of https://github.com/microsoft/vscode/issues/33591 tho for snippets you also use the `"editor.tabCompletion": "onlySnippets"` setting to expand any snippet with `Tab` whenever its prefix has been typed

**Comment by jrieken** [comment] 2022-03-22 07:41
/duplicate of https://github.com/microsoft/vscode/issues/33591

**Closed** 2022-03-22 07:42 UTC
Labels: *duplicate, suggest

**Comment by oiiiiiiii** [comment] 2022-03-22 08:06
wow really? that's it? how is that a duplicate on "showing snippets in the middle of a word" though. I want to show snippets at the end of a word, only that "word" doesn't start with a letter.
