### ISSUE TITLE
File, New, Project

### ISSUE THREAD

**Issue by diogoeichert** [microsoft/vscode#107150] opened 2020-09-21 10:27 UTC
As a VS Code user, I'd like to have a new menu under File, New called "Project", which would provide useful entry-level templates for the most common types of projects VS Code excels at, e.g. "TypeScript". There are currently too many different tutorials about how to start a new TypeScript project, but no clear out-of-the box basic template.

**Comment by mjbvz** [comment] 2020-09-21 16:56
Duplicate of #3680

**Closed by mjbvz** 2020-09-21 16:56 UTC

**Comment by diogoeichert** [comment] 2020-09-21 18:43
I'm not sure this is a duplicate. The concept of New Project goes beyond simply creating a new file with boilerplate.

It should present a wizard with a few options, e.g. "New Browser TypeScript project, New Node.js TypeScript project", etc. Then, based on user choice, it would generate a complete new skeleton project, with usually means a tree of directories and files, not just a single file.
