### ISSUE TITLE
Debug toolbar not always updating to reflect debug state

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#115275] opened 2021-01-27 23:15 UTC
Issue Type: <b>Bug</b>

This seems to be nondeterministic, but today I've now had this happen 4 times. 3 of those times, when I was debugging something, I used the "Stop" button in the debug toolbar, and the debug viewlet immediately updated state, but the toolbar remained open. It did eventually disappear, but it was after significant delay, maybe more than 30 seconds. The last time, I was paused on a breakpoint, and the call stack view reflected this, but the debug toolbar showed the opposite.

Please let me know if there's an logs I can collect to help narrow down the issue! This has been happening the vscode-pull-request-github and vscode repo.

VS Code version: Code - Insiders 1.53.0-insider (7b0cfdd04ad530a9c8d782c618afd79290be3d64, 2021-01-27T08:57:30.935Z)
OS version: Darwin x64 19.6.0

**Comment by isidorn** [comment] 2021-01-28 17:30
Thanks for creating this issue.
I have fixed a "somewhat" similar bug 30 minutes ago. In order to know if it is the same bug: does you application have some deemphasize stack frames (they appear grayed out in the CALL STACK)? If answer is yes -> please wait for next Insiders and it should be fixed, if not let me know.

If your application does not have any "grayed out" stack frames, then is it possible that I just clonse the repo and try to reproduce on my own?
If not, we can also involve Connor. But maybe you first answer the first question.

**Comment by isidorn** [comment] 2021-01-28 17:35
Closing in favor of since that one is older https://github.com/microsoft/vscode/issues/115254

**Closed by isidorn** 2021-01-28 17:35 UTC
Labels: bug, debug, needs more info
