### ISSUE TITLE
Breakpoints' icon don't disappear

### ISSUE THREAD

**Issue by Gappa88** [Microsoft/vscode#38233] opened 2017-11-13 16:51 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|hbe|0.17.0
vs-deploy|mkl|10.0.0
debugger-for-chrome|msj|3.5.0
debugger-for-edge|msj|0.4.1

Steps to Reproduce:
There are 2 issues with breakpoints' icon:
1_ when you add a breakpoint the red circle appear but you cannot remove it anymore
2_ when a breakpoint is already active, go to the end of its line and start a new line. Another red circle appear in this very line but it isn't active. 
They seem a gui issues.

**Comment by weinand** [comment] 2017-11-13 17:01
Duplicate of #37880. Please try Insiders.

**Closed by weinand** 2017-11-13 17:01 UTC
Labels: debug, new release
