### ISSUE TITLE
Bracket Pair Colorizer

### ISSUE THREAD

**Issue by Pramod-Devireddy** [microsoft/vscode#133383] opened 2021-09-18 16:42 UTC
Issue Type: <b>Feature Request</b>

The inbuilt bracket pair colorizer is awesome. But the only problem I am facing and I think everyone facing is that it is even colorizing '<' '>' . 

This makes a html file look not so pretty. I feel that the bracket pair colorizer should not consider the html content where each line will have tags with these symbols. And the main purpose of bracket pair colorizer is to find matching brackets. I feel for HTML language it is not required. If there is any feature where we can turn off this bracket pair colorizer for specific languages, it will be great.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 3.10.0-1160.el7.x86_64
Restricted Mode: No

**Comment by vBread** [comment] 2021-09-18 17:49
As an alternative, adding a setting for which brackets get colorized would probably work too.

**Comment by gjsjohnmurray** [comment] 2021-09-18 18:30
/duplicate of #132476 and will be fixed in Monday's Insiders build.

**Closed** 2021-09-18 18:31 UTC
Labels: *duplicate
