### ISSUE TITLE
Git: status bar lacks indication that it will push

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8655] opened 2016-07-01 23:07 UTC
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:26:22.011Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Create commit, ready to be pushed
2. Click on Git part of status bar
3. -> Commit is pushed, which is unexpected

**Comment by chrmarti** [comment] 2016-07-02 00:03
Not a regression (also in 1.2.1).

**Comment by joaomoreno** [comment] 2016-07-04 13:43
There are two actions in the status bar:

![image](https://cloud.githubusercontent.com/assets/22350/16562554/d91787a6-41fd-11e6-8c0b-c854d571a788.png)

The first one will only list and let you check out branches. The second one is the **sync** action which will **pull** and **push**.

I am very reluctant in adding a confirmation dialog when clicking the sync action. If there are no better suggestions, I suggest to close this as designed.

**Comment by joaomoreno** [comment] 2016-07-05 13:12
Actually, #2397

**Comment by chrmarti** [comment] 2016-07-05 15:33
"Synchronize" isn't clear on what it will do. I initially assumed it would just fetch (or pull) and was surprised it pushed.

Is there telemetry on how often these actions are used? I'd guess that pull (and pull with rebase) are used more often than push or sync.

**Comment by joaomoreno** [comment] 2016-07-05 15:53
Since they are actions, we do have telemetry for it. Hey @seanmcbreen can we get some rough numbers here?

**Comment by chrmarti** [comment] 2016-07-16 06:21
@joaomoreno: I'm concerned about the first-timer experience. I was trying all actions in the status bar as part of our smoke test and didn't expect anything to happen without me being aware of it beforehand. I then inadvertently pushed a bogus change.

First-timers won't have the confirmation enabled. The confirmation doesn't help in that regard as long as it's disabled by default. I'm not necessarily suggesting to enable it by default, although that might be one option to avoid having this surprise.

**Comment by chrmarti** [comment] 2016-07-16 06:30
Also: "Synchronize" is not a well-understood term for someone familiar with git where "pull", "rebase", "merge", "push" are common.

**Comment by madjos** [comment] 2016-07-16 19:16
I have never seen an action that can be this destructive without a confirmation prompt.
No one on my team likes this sync button behavior. It does some weird combination of pull auto resolve and push. If I had ten votes I'd use them all to just remove this button altogether. 
Right now it gets accidentally clicked by some team member and our entire branch gets into a messed up state. This is easily our least favorite part of an otherwise great ide.

**Comment by joaomoreno** [comment] 2016-07-18 07:05
@madjos It literally runs `git pull` followed by `git push`, no further _weird_ magic.

There is now a `"git.confirmSync"` which your team can set to `true` that will cause a confirmation dialog to come up every time the action is clicked. This is already released in the Insiders build and will be released in the July stable release.

**Comment by joaomoreno** [comment] 2016-07-18 07:09
@chrmarti Agree with the _synchronize_ term. I believe it was brought up 4 years ago when git wasn't known by most of our clients (Monaco) and we wanted a term people could relate to.

What we could do, once the work of programmatically changing the user settings is in, is to always prompt the user but give him a checkbox to never prompt him again. This choice would then be remembered in the `git.confirmSync` user setting.

**Comment by chrmarti** [comment] 2016-07-18 17:02
(Reopening for the discussion about the Sync action not properly indicating what it will do.)

Another option might be to replace the Sync action with the Push action, so the user's expectation are set correctly. To retain the current functionality when there are remote changes, the Push action could ask for confirmation to first Pull and then Push, but only if remote changes exist. This would have the advantage of only showing a confirmation dialog when it matters. CC: @egamma @chrisdias

**Comment by aharpervc** [comment] 2016-07-18 17:42
Could the button be redefined as "performs a configured series of git commands"? The default series of commands could be today's behavior. But then I could do what I want, which is, `git stash 'vscode-sync'`, `git fetch --all`, `git rebase`, `git stash pop`, bailing out of any command fails. Note that my example here doesn't push, but also doesn't pull. I can't use today's button at all, but I'd love to be able to. Currently this process is a custom git alias (or, almost is).

**Comment by joaomoreno** [comment] 2016-10-10 07:52
Fixed by 96010725e5b3e3035174b0cfc85898add1d79159

**Closed by joaomoreno** 2016-10-10 07:52 UTC
Labels: bug, git, ux

**Comment by ramya-rao-a** [comment] 2016-10-26 23:52
@joaomoreno @chrmarti Am late to the party, but how about changing the tooltip from "Synchronize Changes" to "Pull and push changes" ?

**Comment by joaomoreno** [comment] 2016-10-27 07:06
cc @chrisdias @egamma @gregvanl on the wording

**Comment by chrmarti** [comment] 2016-10-27 14:20
Related: #13360 asks for renaming the command.
