### ISSUE TITLE
Pinch to zoom on an image is inverted [SurfaceBook/Windows 10]

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#73986] opened 2019-05-20 11:03 UTC
- VSCode Version: 1.34.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open an image inside VSCode
2. Perform a pinch to zoom on the **trackpad**

Notice that doing a zoom-in gesture will actually zoom out the image: pinch to zoom gestures are inverted.

The bug is fixed in the latest insider builds (my guess is that it's fixed in 4c1b302 and/or da5f838 by @hwhung0111).

I opened up an issue to keep track of it: maybe this fix could be included in a minor version?

**Comment by gjsjohnmurray** [comment] 2019-05-20 11:35
Duplicate of #73676 ?

**Comment by mjbvz** [comment] 2019-05-21 17:54
Duplicate of #73775 / #73676

**Closed by mjbvz** 2019-05-21 17:54 UTC
