### ISSUE TITLE
updated to 1.13.0，embedded cmd work wrong

### ISSUE THREAD

**Issue by heekei** [Microsoft/vscode#28479] opened 2017-06-12 02:05 UTC
- VSCode Version: 1.13.0
- OS Version: Win 10 Education

Steps to Reproduce:

1.
![tim 20170612095544](https://user-images.githubusercontent.com/10609199/27016835-1dd31a3e-4f56-11e7-84e3-855fc4d5ef22.png)

2. Chinese word is duplicate in embedded cmd.
3.And flash between normal and duplicate during typing letters into embedded  cmd.

**Comment by heekei** [comment] 2017-06-12 08:06
is anybody here? @vscodebot[bot]

**Comment by ramya-rao-a** [comment] 2017-06-12 18:30
Closing as duplicate of #26038

cc @Tyriar

**Closed by ramya-rao-a** 2017-06-12 18:30 UTC
Labels: new release
