### ISSUE TITLE
proplem

### ISSUE THREAD

**Issue by jjmendezrodriguez** [microsoft/vscode#230668] opened 2024-10-07 01:41 UTC
Type: <b>Performance Issue</b>

every time i go to file, open folder program close.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 4100)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 2, 1|
|Memory (System)|38.95GB (35.89GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id b79b4886-6f3d-4ce6-aff6-b314513e84ed|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   160	  7492	code main
    0	    40	  7494	   zygote
    0	    40	  7495	   zygote
    0	   199	  7561	window [1] (Welcome - Visual Studio Code)
    0	    40	  7537	   utility-network-service
    0	    80	  7604	   gpu-process
    0	    80	  7631	shared-process
    0	     0	  7909	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  7910	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    80	  7633	fileWatcher [1]
    0	   160	  7662	extensionHost [1]
    0	    80	  7784	     electron-nodejs (languageserver.js )
    0	    80	  7729	ptyHost
    0	     0	  7821	     /usr/bin/bash --init-file /snap/code/170/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-tailwindcss|bra|0.12.11
path-intellisense|chr|2.9.0
dbclient-jdbc|cwe|1.3.6
vscode-myssql-client2|cwe|7.6.2
vscode-markdownlint|Dav|0.56.0
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
vscode-test-explorer|hbe|2.22.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
test-adapter-converter|ms-|0.2.0
sqltools|mtx|0.28.3
autodocstring|njp|0.6.1
vscode-thunder-client|ran|2.27.6
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vim|vsc|1.28.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31150323
notype1cf:31151524
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-10-07 02:25
/duplicate of https://github.com/microsoft/vscode/issues/230454

**Closed** 2024-10-07 02:25 UTC
Labels: *duplicate, new release

**Comment by jjmendezrodriguez** [comment] 2024-10-28 04:21
i fix it. sorry for late answer!! love vsc!!
