### ISSUE TITLE
Collapsed grid did not expand on click.

### ISSUE THREAD

**Issue by p3pp8** [Microsoft/vscode#53952] opened 2018-07-10 10:51 UTC
Hello, i noticed that in version 1.25 when i click on a collapsed frame it did not expand, i've to manually use the mouse to drag it full screen. That is slow and really annoying! Why di you removed this feature? Is there any alternative?

Regards,
Giuseppe

VS-Code 1.25.
Mac OS X High Sierra.

**Comment by bpasero** [comment] 2018-07-10 15:16
Duplicate of https://github.com/Microsoft/vscode/issues/51614

You can try out the insider release to verify the fix works for you: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2018-07-10 15:16 UTC
Labels: editor, editor-folding

**Comment by p3pp8** [comment] 2018-07-10 15:42
Thanx!

**Comment by p3pp8** [comment] 2018-07-11 08:13
Insiders version works perfectly!
