### ISSUE TITLE
Empty box in package.json intellisense

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14682] opened 2016-10-28 22:42 UTC
Probably related to #14679
- Type "micro" fast
- This bar shows up which is the same width as the intellisense popup, when it does show up

If I type slowly, I see useful suggestions.

![image](https://cloud.githubusercontent.com/assets/323878/19824491/e5c22772-9d24-11e6-8ac4-165e56dda29e.png)

**Comment by jrieken** [comment] 2016-10-31 11:17
This is a dupe of #14679. We would not redo the request

**Closed by jrieken** 2016-10-31 11:17 UTC
