### ISSUE TITLE
Double-click the border of the side bar now expands it much too large

### ISSUE THREAD

**Issue by KexyBiscuit** [microsoft/vscode#77797] opened 2019-07-23 06:04 UTC
Issue Type: <b>Bug</b>

1. Double-click the border of the side bar.
2.  It expands much too large.

VS Code version: Code - Insiders 1.37.0-insider (e1d3dd53d17fb1529a002e4d6fb066db0a0bd385, 2019-07-23T05:23:48.960Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.28.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.12
docs-preview|doc|0.3.24
docs-yaml|doc|0.2.3
githistory|don|0.4.6
gitlens|eam|9.9.1
EditorConfig|Edi|0.13.0
git-project-manager|fel|1.7.1
powershell|ms-|2019.5.0
vsliveshare|ms-|1.0.540
team|ms-|1.149.2
vscode-xml|red|0.7.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.4.1
code-spell-checker|str|1.7.17
vscodeintellicode|Vis|1.1.8
vscode-icons|vsc|8.8.0

</details>

**Comment by isidorn** [comment] 2019-07-30 13:30
It depends on the length of the names of your files. Vscode is behaving like this since day one and this is not someting which we will change. Closing as designed.

**Comment by KexyBiscuit** [comment] 2019-07-31 05:52
@isidorn However, it'll currently reduce the width too much if all file names are short, instead of a pre-defined minimum width, is this also by design?

**Comment by isidorn** [comment] 2019-07-31 09:30
Yeah. It sets the size depending on the size of the names, so if the names are too short it will decrease it too much.
Would you like that it always sets the size to a constant?
I would not change this since many users are used to the current behavior.

**Comment by KexyBiscuit** [comment] 2019-08-01 02:49
I do discover a difference between Insider ver. and Exploration ver., and the Exploration ver. reflects not only the behavior what I prefer, but also the behavior has been there for months, so I believe the behavior in Insider ver. is wrong. Could you please test this on all three channels?

**Comment by isidorn** [comment] 2019-08-02 16:13
Can you please provide a .gif showing these differences. Because on my machine i see no difference between vscode stable and insiders

**Comment by KexyBiscuit** [comment] 2019-08-05 03:02
@isidorn The behavior is OK on VS Code Insider for now, I have no idea why but it works for me after updating to 0bd57ac. For now, if you want to debug this, please test Azure Data Studio Insider build, it shows the same problem. Anyway, thanks for your time 👍.

**Comment by KexyBiscuit** [comment] 2019-08-05 03:03
Might related to https://github.com/microsoft/vscode/commit/23875a287e854eb558172c757ff4c6ac6df0eefe.

**Comment by KexyBiscuit** [comment] 2019-08-05 03:09
Confirmed, if workbench.useExperimentalGridLayout is true the layout would be a mess, and this option had been active for days.

**Comment by isidorn** [comment] 2019-08-05 08:36
fyi @sbatten

**Comment by KexyBiscuit** [comment] 2019-08-13 08:33
@isidorn Could you please reopen this? The problem is now back with b6843f92d0428bb182ce858e6dbee1f1ac3f7e2c, it's really annoying.

**Comment by isidorn** [comment] 2019-08-13 08:41
@KexyBiscuit of course. Assigning to @sbatten since he is changing the grid layout
fyi @joaomoreno

**Comment by sbatten** [comment] 2019-08-13 23:26
@KexyBiscuit I've updated the behavior to match the old behavior where double clicking will not reduce the width below 300px. I do not see any old behavior limiting how large it will make it however. Please test in tomorrow's build and let me know if you still have issues. If so, please provide a gif showing the difference.

**Closed** 2019-08-13 23:25 UTC
Labels: bug, workbench-layout

**Comment by KexyBiscuit** [comment] 2019-08-15 02:01
@sbatten LGTM, thanks a lot!

**Comment by isidorn** [comment] 2019-08-15 09:29
Great, adding verified label since @KexyBiscuit confirmed it is good now.
