### ISSUE TITLE
CodeLens can't determine references for TS properties ended with $

### ISSUE THREAD

**Issue by etatuev** [Microsoft/vscode#27468] opened 2017-05-29 18:31 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-simpler-icons|davidbabel|1.3.0|
|githistory|donjayamanne|0.2.0|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.15.0|
|vscode-great-icons|emmanuelbeziat|2.1.6|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.12|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|beautify|HookyQR|1.0.2|
|docthis|joelday|0.4.4|
|Angular2|johnpapa|2.3.1|
|spellcheck|JuliaBay|1.1.4|
|code-beautifier|michelemelluso|1.7.2|
|vscode-scss|mrmlnc|0.6.2|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.1.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|tsimporter|pmneo|1.2.14|
|partial-diff|ryu1kn|0.3.1|
|html-preview-vscode|tht13|0.1.1|;

---

Steps to Reproduce:

1. Open **TypeScript** file
2. Add any property which can be targeted by **CodeLens**
3. End variable name with `$`, like `public foo$: number;`

[Screenshot](https://i.imgur.com/PhPomUc.png)

I think it's a bug, as `$` sign was always allowed for variable naming in **TypeScript**.

**Comment by mjbvz** [comment] 2017-05-30 22:27
Duplicate of #27211

Should be fixed in current insiders builds

**Closed by mjbvz** 2017-05-30 22:27 UTC
Labels: duplicate, javascript, typescript
