### ISSUE TITLE
Terminal link detection only works after scrolling

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#36072] opened 2017-10-11 15:08 UTC
- VSCode Version: 1.17.0 
- OS Version: OS X 10.12.6

Steps to Reproduce:

1. On the terminal, run a command that outputs a URL
2. Hover the link with the mouse. VSCode will not recognize it as clickable
3. Scroll the terminal up/down
4. VSCode will now recognize the link and Cmd+Click will work

Also tested on Windows 10, same results.

Edit: Just got the 1.17.1 update, the bug is still present

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-10-28 08:53
This was mostly fixed in 1.17.1 (https://github.com/Microsoft/vscode/issues/35662) but it occasionally still doesn't work.

**Comment by scorredoira** [comment] 2017-10-30 16:50
I am using 1.17.2 and the problem is still present. 
Also after scrolling the problem disappears.

**Comment by Tyriar** [comment] 2017-10-30 17:00
Was the terminal hidden before hovering the link? If so this could be https://github.com/Microsoft/vscode/issues/37103

**Comment by scorredoira** [comment] 2017-10-30 17:02
No, it was visible all the time. Also I checked for errors in the Developer Tools Console and has none.

**Comment by scorredoira** [comment] 2017-10-30 17:06
It seems totally random. I'm doing all kind of tests to reproduce it but I can't find a pattern.

**Comment by scorredoira** [comment] 2017-10-30 17:11
It's also present in Version 1.18.0-insider. I have done now ~50 tests and it is random.

**Comment by coreh** [comment] 2017-10-31 13:14
It's not happening randomly for me, I get it consistently every single time

**Comment by gwk** [comment] 2017-11-02 01:37
@scorredoira @coreh my experience (with file paths, not urls) is that it seems reproducible, and has to do with the the terminal buffer filling up enough to scroll. However just a couple of times I didn't quite see what I was expecting, so I'm not sure if the bug is totally deterministic. Are you able to see the same behavior as I described in #37453?

**Comment by scorredoira** [comment] 2017-11-02 06:08
@gwk my experience is also with file paths. The behavior I see like #37453 but only about 10-20% of the times

**Comment by scorredoira** [comment] 2017-11-02 06:18
I thought I had narrowed it and that links only stopped working the moment there was enough content for the scrollbar to appear. I did multiple tests with a fresh terminal each time. It behaved that way for 5 or 6 times but then It started to fail the first link and not the following until the scroll kicked in. Worked the same way a few times and the a different pattern. So it is definitely random for me.

**Comment by coreh** [comment] 2017-11-03 17:41
One interesting thing that I noticed is that even links that were previously correctly detected as URLs (by scrolling up/down) stop working as soon as a new line gets added, even if that newline doesn't itself contain any links.

Using something like `tmux` (that hijacks the new line command and instead draws characters at specific positions via curses) completely bypasses the issue.

**Comment by matt-tingen** [comment] 2017-12-11 21:46
This is 100% reproducible for me on 1.19.0-insider (22b70efaa7abc2d120e3aef972cf8df01337b4a7) by switching to another terminal or another pane such as Problems or Output and then back to the terminal with the URL/path. I can also reproduce it by resizing the terminal panel.

The other workaround besides scrolling that works for me is to right click and paste. Typing and pasting with cmd+v do not resolve it.

**Comment by Tyriar** [comment] 2017-12-12 01:12
> Using something like tmux (that hijacks the new line command and instead draws characters at specific positions via curses) completely bypasses the issue.

This is probably the case because tmux never actually scrolls. Scrolling within tmux just redraws the viewport.

**Closed** 2018-01-22 20:00 UTC
Labels: bug, help wanted, integrated-terminal, upstream
