### ISSUE TITLE
Keyboard shortcuts do not respect keyboard layout preference.

### ISSUE THREAD

**Issue by jasenj1** [Microsoft/vscode#24894] opened 2017-04-17 15:45 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|plantuml|jebbs|1.5.0|;

---

Steps to Reproduce:

1. Open MacOS Preferences.
2. Open Keyboard preference pane.
3. Select Dvorak-Qwerty keyboard layout
4. Try keyboard commands in Visual Studio Code. 
5. Command-S should be Save even though the "S" key is mapped to "O", instead Command-S is Open. Same for all other keyboard shortcuts.

**Comment by alexandrudima** [comment] 2017-04-18 15:29
Duplicate of #23964

**Closed by alexandrudima** 2017-04-18 15:29 UTC
