### ISSUE TITLE
Go to file from replace preview

### ISSUE THREAD

**Issue by MathiasKandelborg** [microsoft/vscode#68610] opened 2019-02-13 10:34 UTC
I have been using the search functionality quite a lot lately, it works great! I often have to search twice when looking for a keyword: once in search and once to look up the file. In my perception, this functionality has changed over the past few months. I think I remember searching keywords and then accessing the files directly from search - although, I might have been 'lucky' and had the files open every time I searched in the past.

Possible solutions:

1. Right clicking the file has a 'go to file /open in editor'
1. Double clicking the file opens the file
1. Keyboard command that opens the file when in 'Replace Preview'
  - A combination of 1 _or_ 2 & 3

**Comment by MathiasKandelborg** [comment] 2019-02-14 15:57
I've tinkered a bit and quickly found that files open normally when there are no characters in the replace field. I think this is quite unintuitive, but something I'll remember for now.

**Comment by roblourens** [comment] 2019-02-17 20:27
Thought there was an issue to add a button to open the file directly from the replace preview, but I can't find it. You can disable the replace preview, if that helps. `"search.useReplacePreview": false`

**Comment by MathiasKandelborg** [comment] 2019-02-19 10:48
Nice with the disable option, I'm gonna use that. Thanks for the help.

I think the default should be reversed, that would make more sense when beginning to customize - maybe it needs some guide or something along those lines... Because I'd never think that my text-editor had a replace view unless I've specifically added/enabled it.

There might be reasoning behind the current default which I'm not aware of - I'm basically just sharing my thoughts on the subject :slightly_smiling_face:

**Comment by roblourens** [comment] 2019-10-27 23:37
Dupe of https://github.com/microsoft/vscode/issues/35337

**Closed by roblourens** 2019-10-27 23:37 UTC
Labels: feature-request, help wanted, search
