### ISSUE TITLE
Tab Names as First Line of File if Unsaved

### ISSUE THREAD

**Issue by cbjjensen** [Microsoft/vscode#44890] opened 2018-03-02 05:42 UTC
## Issue Type
Feature Request

## Description

I use code for writing code, but also use it for my note taking. I'd like to have the tab names on 'new files' use the first line of the file. I take a lot of notes, and open multiple tabs at a time. Clicking through each of the 'Untitled' tabs makes it difficult to quickly find my notes. I don't always need to save them, or am in a rush and don't want to have to save them before being able to open the next tab to stay organized. Having the title default to the first line would be helpful in finding them. I can see how some users wouldn't like this, but if this was configurable so that users could turn it on/off, that would work!

I think this _could_ solve the same feature request as https://github.com/Microsoft/vscode/issues/44835 , as long as I wouldn't need to manually type a tab name.  

Thanks!

## VS Code Info
- VSCode Version: 1.20.1 
- Commit: f88bbf9
- OS Name	Microsoft Windows 10 Enterprise
- Version	10.0.15063 Build 15063

**Comment by bpasero** [comment] 2018-03-02 06:21
/duplicate of https://github.com/Microsoft/vscode/issues/37414

**Closed** 2018-03-02 06:22 UTC
Labels: *duplicate, workbench-tabs
