### ISSUE TITLE
Key binding on view item command doesn't provide the view item

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#72442] opened 2019-04-16 21:34 UTC
Issue Type: <b>Bug</b>

This is easily reproducible using the `tree-view-sample` repo.

1. Add a key binding for `nodeDependencies.editEntry`
1. Open the package explorer view and click on one of the nodes
1. 🐛 execute the key binding and notice the command fails (while if you click the pencil icon it will work fine)

When the command gets executed from the key binding it isn't getting the proper context. This breaks most key bindings for commands on view items.

/cc @jrieken 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (15.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by phmngocnghia** [comment] 2020-05-31 08:52
Any news on this? I Hope to see this on a near future mile-stone. This have been in `On deck` for too long...

**Comment by katelynienaber** [comment] 2020-06-09 10:27
This is not working for me as well, when trying to bind a command to a viewItem, ie:
````
      {
        "command": "custom.extension.command",
        "key": "ctrl+alt+z",
        "mac": "cmd+alt+z",
		"when": "sideBarFocus && focusedView == custom.view && viewItem =~ /nodeContextHere/"
      },
````
But this works if I remove ` && viewItem =~ /contextHere/`

**Comment by eamodio** [comment] 2020-12-06 06:30
🤣 I was about to file this issue again and found that I already had. This is very problematic for extensions wanting to allow key bindings tree items. And it is likely confusing to users -- because if they set a key binding for a command that is in a tree item's context menu, then the shortcut key shows up in the context menu, but it won't work -- because the command will get executed without any context.

**Comment by eamodio** [comment] 2020-12-06 06:32
@alexr00 can you point to the likely place where changes would need to be made to make this happen?

**Comment by alexr00** [comment] 2020-12-07 10:30
I'm not sure where the changes would need to be made. Maybe @alexdima or @joaomoreno knows.

**Comment by joaomoreno** [comment] 2020-12-08 09:48
> When the command gets executed from the key binding it isn't getting the proper context. 

What the the expected context? That somehow `viewItem` is the selected/focused tree item? If so, the custom tree view needs to create a scoped context key service in which it sets the `viewItem` context as the tree selection/focus changes. That way, the context will be set when the user invokes the keybinding and has DOM focus inside the custom tree view DOM element.

**Comment by alexr00** [comment] 2020-12-08 09:51
Thanks @joaomoreno!

**Comment by eamodio** [comment] 2020-12-08 16:53
@joaomoreno is this something the list widget could do itself? Since this issue affects all our trees, whether custom or not. (Though I guess the actual context is different for each)

**Comment by joaomoreno** [comment] 2020-12-09 15:21
Yes. We could potentially have a sort of `IContextKeysProvider` feature at the `Workbench(List|Tree)` level which would do this for you. Something like:

```ts
interface IContextKeysProvider<T> {
    getContextKeys(element: T) { key: string, value: string }[];
}
```

Or so.

**Comment by eamodio** [comment] 2021-01-04 22:58
@joaomoreno who should own that? Should we turn this issue into that?

**Comment by joaomoreno** [comment] 2021-01-05 10:11
I wouldn't mind a contribution! ;)

**Comment by alexr00** [comment] 2024-12-12 13:49
The way we do keyboard shortcuts for elements like this is by providing API to get the active item. Duplicate of https://github.com/microsoft/vscode/issues/170248

**Closed by alexr00** 2024-12-12 13:49 UTC
Labels: bug, tree-views
