### ISSUE TITLE
这次的更新太愚蠢了！

### ISSUE THREAD

**Issue by ahliyo** [Microsoft/vscode#13464] opened 2016-10-11 03:13 UTC
为了提高我的编程效率，所以我选择了vscode。
同时也是出于效率的考虑，我把需要自己常用的函数写进了lua.json里面
因为vscode愚蠢的补全排序，我不得不给自己的函数prefix加上 ` 字符以快速选中它
在今天的版本更新之前，这种做法是有效的
然而今天的更新把这一切都摧毁了！！！

现在即使我在prefix前面加上 ` 字符，也不是默认选中我自己的函数了
诅咒这次更新

- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: XavierCHN.dota-reborn-code-0.1.3

Steps to Reproduce:

1.
2.

**Comment by leaxoy** [comment] 2016-10-11 03:18
...

**Comment by ahliyo** [comment] 2016-10-11 03:19
My english is not very good, and I am very angry...

so,please pardon me for I using chinese.

**Comment by mouhong** [comment] 2016-10-11 03:47
I'm also a Chinese but I really feel ashamed for you. I'm also not quite good at English. But can you at least try Google Translate before creating a ticket?

And how can you use word “curse” here? Why you wrote 2 empty steps? Shame on you! Please note that this is a place to report issues and make the produce better.

**Comment by rebornix** [comment] 2016-10-11 05:01
Hmm, I choose not to translate his words directly.

Seems we changed the way we order custom code snippets. Previously he put a backtick before his often used code snippet and then they always came first. But now seems we changed the logic, his favorite snippets no longer come first, which makes him angry.

**Comment by isidorn** [comment] 2016-10-11 08:46
@rebornix can you please follow up on this, regarding getting steps, what exact snippet he is missing and so on. After the issue has some useful data please assign it to Joh.

**Comment by rebornix** [comment] 2016-10-11 16:47
@ahliyo 你能够提供更多的信息给我们吗？比如你的 snippet 文件内容，你如何复现这个问题，谢谢！

**Comment by ahliyo** [comment] 2016-10-12 06:20
@rebornix 
谢谢你的回复，我将继续使用中文回复你。

我还没办法掌握vscode版本的回退，所以我没有办法把之前的流程截图给你看，在经过多次尝试之后，我把prefix前面的`字符改为了1，同样实现了我之前的效果，只是看上去稍有点怪：

lua.json中的内容


按下1for给出的默认补全提示（没有移动光标）

执行补全后得到的结果


这是目前的实现过程。在上一个版本中把lua.json中的1改为`是同样的效果，但是现在你看是这样的

lua.json中的内容

按下`for给出的默认补全提示（没有移动光标）

可以看到，并不优先出现在`for位置上
![1](https://cloud.githubusercontent.com/assets/21235146/19299410/c436ee80-9086-11e6-87e4-95d3e4047e3e.png)
![2](https://cloud.githubusercontent.com/assets/21235146/19299411/c439c588-9086-11e6-8962-88ea2933b2eb.png)
![3](https://cloud.githubusercontent.com/assets/21235146/19299412/c43a2546-9086-11e6-84b7-d610079e6ba9.png)

![5](https://cloud.githubusercontent.com/assets/21235146/19299413/c46d08c6-9086-11e6-8a13-39c1b54d8c13.png)

**Comment by rebornix** [comment] 2016-10-12 06:28
@jrieken @isidorn not sure who is the owner of this feature. The problem is clear right now, per his description, we changed the way we sort code snippets. In order to have his favorite snippet as the first one on the list, he put a backtick as prefix of snippet name. But after we released 1.6, snippet whose name is prefixed with backtick is no longer the first one.

**Comment by jrieken** [comment] 2016-10-12 07:44
dup of #13498

**Closed by jrieken** 2016-10-12 07:44 UTC
Labels: needs more info
