### ISSUE TITLE
Mac title bar has incorrect size after reload

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#103591] opened 2020-07-29 22:46 UTC
Issue Type: <b>Bug</b>

**Repro**
1. With a non default zoom level on MacOS
1. Reload with the window

**Bug**

The window title bar has the incorrect height (it should match that of the window control icons) :

![Screen Shot 2020-07-29 at 2 47 18 PM](https://user-images.githubusercontent.com/12821956/88861327-9442a180-d1b2-11ea-8579-1237fbb80e20.png)

This is fixed after zoom

VS Code version: Code - Insiders 1.48.0-insider (15e798e081984a17eae00de91adf4479190d5ed2, 2020-07-28T10:40:03.139Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 3, 3|
|Memory (System)|32.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|17%|
</details>

**Comment by misolori** [comment] 2020-08-06 19:59
I've been encountering this for the past week and it's been a bit annoying when you reload and forget your zoom changed. Then when you want to zoom in again it dramatically changes. 

![Kapture 2020-08-06 at 12 57 15](https://user-images.githubusercontent.com/35271042/89576715-7ee9fa80-d7e4-11ea-82b1-1377b02128cb.gif)

**Comment by mjbvz** [comment] 2020-08-06 20:02
Marking this for July since I expect it to generate a lot of issue reports

**Comment by deepak1556** [comment] 2020-08-06 20:18
This is a regression from the recent zoom change https://github.com/microsoft/vscode/commit/c7fe3b41ae4c22de8b84a95076b8fe43aa259635 , we now set a default zoom factor on the browser window, when you reload it always seems to take preference over the current zoom level set on the webContents. Most likely a bug in electron, will check.

**Comment by deepak1556** [comment] 2020-08-06 20:32
confirmed the behavior in electron https://gist.github.com/deepak1556/ff263abf30277e0a2c7333f2e5789305, will have to check if this is intended or a bug.

**Comment by joaomoreno** [comment] 2020-08-07 13:31
Talked to @deepak1556, he will bring in the fix in Electron.

**Comment by deepak1556** [comment] 2020-08-07 19:15
After a bit more investigation the issue is not in electron, we are using the wrong api to set persistent zoom levels. There are 3 different ways to set zoom level for a page.

1) Setting `zoomFactor` option on the `BrowserWindow` constructor
   - This will be the default zoom level for a page if set

2) using `webframe.setZoom(Level|Factor)` api
   - This is the renderer side api available to set the zoom levels, but a thing to not here is webFrame api are only meant to make changes for the current frame. So if a navigation occurs these values will not be persisted. In short these can be treated as temporary zoom levels.

3) using `webContents.setZoom(Level|Factor)` api
  - This only difference from 2) in that the values set through this api will be persisted across navigations or restarts on a origin basis similar to how zoom works in the browser domain.

When an app quits if there is any persistent zoom level during its lifetime, it will be written to `Preferences` file under the user data dir. So next time an app starts it will be applied, but if 1) is set then it will take precedence over the persisted preference value.

Order of precedence when app starts:

persisted preference value < BrowserWindow zoom factor option < webContents/webFrame zoom api

**Comment by deepak1556** [comment] 2020-08-07 19:17
I am gonna revert the change from https://github.com/microsoft/vscode/commit/c7fe3b41ae4c22de8b84a95076b8fe43aa259635 and follow up with the fix in a separate PR for next iteration, mainly because endgame week is closing and only limited testing can be done.

**Closed** 2020-08-07 20:06 UTC
Labels: bug, regression, zoom

**Comment by bpasero** [comment] 2020-08-12 13:16
It is not clear to me why this caused issues. Given my change and yours, it looks like we are now setting both `zoomFactor` on the browser window and `zoomLevel` on the frame. Is the issue that upon reload the browser window `zoomFactor` is not applied anymore?

The intent of my change was to reduce sync IPC on startup, so maybe there is a way to configure this all from `electron-main`?

**Comment by deepak1556** [comment] 2020-08-13 04:05
> Is the issue that upon reload the browser window zoomFactor is not applied anymore?

No its the other way, on reload the browser window zoomfactor take effect, because we use `webFrame` zoom apis to set zoom level in the editor, values set via this api are temporary (i-e) will not be preserved across navigations https://github.com/microsoft/vscode/issues/103591#issuecomment-670671633 has context as to why.

The ideal fix here would be to use `webContents` zoom api in electron-main which are permanent and will be applied across navigations.

**Comment by bpasero** [comment] 2020-08-13 06:20
@deepak1556 another intent of my change was to reduce zoom flicker by applying the zoom level before the window is created, I often see our splash screen appearing in non-zoomed state and then zooming in, but maybe that issue is fixed by the `zoomFactor` being set on the browser window now.

How would it work if we set zoom in `webContents`? What if the user changes the zoom level from within VSCode, would it not have to then go back to `electron-main` to update it?

Maybe easier to discuss in our 1on1.

**Comment by deepak1556** [comment] 2020-08-13 06:27
yup lets discuss this in the call 👍
