### ISSUE TITLE
powershell.exe terminated with exit code: 259

### ISSUE THREAD

**Issue by sujayun** [microsoft/vscode#114291] opened 2021-01-13 17:21 UTC
Issue Type: <b>Bug</b>

**Steps To Reproduce :**

- Goto Terminal 
- New Terminal

Terminal Closes with a notification saying 

`"The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 259."`

----

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.28GB free)|
|Process Argv|--crash-reporter-id 0da01979-fae7-4d97-8e38-b592c70d1412|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0

</details>

**Comment by TylerLeonhardt** [comment] 2021-01-13 17:38
Duplicate of https://github.com/microsoft/vscode/issues/113738

in that issue I have questions for the issue filer. Can you please answer those same questions in that issue?

**Closed by TylerLeonhardt** 2021-01-13 17:38 UTC
