### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by Y-A-K-E** [microsoft/vscode#94652] opened 2020-04-08 04:54 UTC
```    
if (SPIFFS.begin())
 {
        Dir dir = SPIFFS.openDir("/");
#if defined(IS_DEBUG)
        USE_SERIAL.println("run spiffs");
#endif

        size_t ok_count = 0;
}
```

c or c++ 

#If defined(), folding will not work

**Comment by aeschli** [comment] 2020-04-09 07:45
duplicate of https://github.com/microsoft/vscode-cpptools/issues/407

**Closed by aeschli** 2020-04-09 07:45 UTC
