### ISSUE TITLE
import of sqlite3 is incomplete

### ISSUE THREAD

**Issue by hgconrad** [microsoft/vscode#103521] opened 2020-07-28 22:48 UTC
- VSCode Version:1.47.3
- OS Version:Win 10

Steps to Reproduce:
The following code produces this error:
import sqlite3
print(sqlite3.version)

1.Exception has occurred: AttributeError
partially initialized module 'sqlite3' has no attribute 'version' (most likely due to a circular import)
  File "C:\Users\howar\Google Drive\PythonCode\database\sqlite3.py", line 5, in <module>
    sqlite3.version
  File "C:\Users\howar\Google Drive\PythonCode\database\sqlite3.py", line 3, in <module>
2.From the terminal console the code works correctly
hgc@HP-Z440-MX:~
$ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> print(sqlite3.version)
2.6.0
>>> 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2020-07-28 23:24
Duplicate of https://github.com/microsoft/vscode/issues/103512

Again, this is not a VS Code problem. Please don't open duplicate issues

**Closed by mjbvz** 2020-07-28 23:24 UTC
