### ISSUE TITLE
http web page window is small when (Ctrl+= )resize font size.使用缩放功能时网页窗口区域太小了

### ISSUE THREAD

**Issue by emanruoy** [Microsoft/vscode#17116] opened 2016-12-13 13:25 UTC
- VSCode Version: Code 1.7.1 and 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|2.3.2|

---

Steps to Reproduce:

1.Ctrl+= 
2.open any window that contains web page, extension details page for example.

**Comment by kieferrm** [comment] 2016-12-13 18:52
Duplicate of #5745.

**Closed by kieferrm** 2016-12-13 18:52 UTC
Labels: duplicate, webview
