### ISSUE TITLE
Debug extension failed

### ISSUE THREAD

**Issue by RenRongrong** [Microsoft/vscode#40501] opened 2017-12-19 08:59 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:44.860Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.16.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.0.0
markdown-all-in-one|yzh|0.11.2
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.Generate a new extension
2.Click debug-start

Reproduces without extensions: Yes

I generated an extension following the doc  [here](https://code.visualstudio.com/docs/extensions/example-hello-world). When I click the debug-start it throws an error : 无法连接到运行中的进程，将在10000毫秒后超时 - （原因：目标的响应似乎无效:...

![](http://www.muyao.site/Images/vscextension.png)

Is there anyting wrong in my project?

**Comment by isidorn** [comment] 2017-12-19 10:26
We do not speak chinesse can you please translate the message to english?
Do you see some errors when you `F1 > developer tools`?

**Comment by RenRongrong** [comment] 2017-12-20 01:07
The message says "Can't connect to the running process. It will be timeout after 10000ms. (Reason: target's response seems invalid)". The developer tools gives errors as below:
![](http://www.muyao.site/Images/vscExtensionError.png)
Anyway, I tried it on another computer and it works fine. Maybe it's due to the environment of the computer?

**Comment by isidorn** [comment] 2017-12-20 09:17
@RenRongrong if it works on the other computer then it means we will not be able to reproduce this. However forwarding to @roblourens so he can decide if he wants to close this or investigate further

**Comment by roblourens** [comment] 2017-12-20 16:52
Could you copy and paste the full error message from devtools here? (all the text with `"description": "node.js instance"` and everything below). The error message implies that it wasn't able to parse that text as JSON but it looks correct to me.

**Comment by RenRongrong** [comment] 2017-12-21 00:45
The message is here:
[ {
  "description": "node.js instance",
  "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:10309/2e42e8f4-f7f0-472b-952a-f07180cabef8",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "2e42e8f4-f7f0-472b-952a-f07180cabef8",
  "title": "qcu(",
  "type": "node",
  "url": "file://",
  "webSocketDebuggerUrl": "ws://127.0.0.1:10309/2e42e8f4-f7f0-472b-952a-f07180cabef8"
} ]
Yes, it can't be parsed as json. There's messy code in "title".

**Comment by roblourens** [comment] 2017-12-21 02:48
That's a problem. Do you have any idea where the "title" might be coming from? Mine always says something like `"title": "/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper"`

**Comment by g8up** [comment] 2017-12-21 13:19
I'm from China.
I came across the same issue under Windows7 64bit/VScode v1.18.0 and v1.19.0.
My launch.json:
```
// A launch configuration that compiles the extension and then opens it inside a new window
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}" ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/out/**/*.js" ],
            "preLaunchTask": "npm: watch",
            "trace": "verbose"
        },
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}", "--extensionTestsPath=${workspaceRoot}/out/test" ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/out/test/**/*.js" ],
            "preLaunchTask": "npm: watch"
        }
    ]
}
```
popup message :
```
Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: [ {
```
Error in `Developer Tools`:
```
workbench.main.js:sourcemap:2744 Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: [ {
  "description": "node.js instance",
  "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:16630/3afe2a45-8cdc-4601-b54e-666bb225569e",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "3afe2a45-8cdc-4601-b54e-666bb225569e",
  "title": "flv(",
  "type": "node",
  "url": "file://",
  "webSocketDebuggerUrl": "ws://127.0.0.1:16630/3afe2a45-8cdc-4601-b54e-666bb225569e"
} ]

).
```
Log from vscode-node-debug.txt
```
OS: win32 ia32
Adapter node: v7.9.0 ia32
vscode-chrome-debug-core: 3.20.3
20:55:57, 2017-12-21
node-debug2: 1.19.4
From client: initialize({"clientID":"vscode","adapterID":"extensionHost","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true},{"label":"Promise Rejects","filter":"promise_reject","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true}}
From client: attach({"name":"Extension","type":"extensionHost","request":"attach","runtimeExecutable":"D:\\Program Files (x86)\\Microsoft VS Code\\Code.exe","args":["--extensionDevelopmentPath=d:\\code\\sigma\\oschina\\quickopen-autofill"],"stopOnEntry":false,"sourceMaps":true,"outFiles":["d:\\code\\sigma\\oschina\\quickopen-autofill/out/**/*.js"],"preLaunchTask":"npm: watch","trace":"verbose","__sessionId":"d673cda1-260a-43af-8f65-76b35b3a647a","port":16630})
SourceMaps: preloading sourcemaps for scripts in globs: ["d:\\code\\sigma\\oschina\\quickopen-autofill/out/**/*.js"]
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"request":"attach","args":["name","type","request","runtimeExecutable","args","stopOnEntry","sourceMaps","outFiles","preLaunchTask","trace","__sessionId","port","sourceMapPathOverrides","showAsyncStacks"]}}}
Discovering targets via http://127.0.0.1:16630/json
SourceMaps: expanded globs and found 3 scripts
SourceMaps: sourcemap url parsed from end of generated content: extension.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for d:\code\sigma\oschina\quickopen-autofill\out\extension.js by URI: extension.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from d:\code\sigma\oschina\quickopen-autofill\out\extension.js.map
SourceMaps: sourcemap url parsed from end of generated content: index.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for d:\code\sigma\oschina\quickopen-autofill\out\test\index.js by URI: index.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from d:\code\sigma\oschina\quickopen-autofill\out\test\index.js.map
SourceMaps: sourcemap url parsed from end of generated content: extension.test.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for d:\code\sigma\oschina\quickopen-autofill\out\test\extension.test.js by URI: extension.test.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from d:\code\sigma\oschina\quickopen-autofill\out\test\extension.test.js.map
SourceMap: creating for d:\code\sigma\oschina\quickopen-autofill\out\extension.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../src/extension.ts"]
SourceMap: no sourceRoot specified, using script dirname: d:\code\sigma\oschina\quickopen-autofill\out
SourceMap: creating for d:\code\sigma\oschina\quickopen-autofill\out\test\index.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../../src/test/index.ts"]
SourceMap: no sourceRoot specified, using script dirname: d:\code\sigma\oschina\quickopen-autofill\out\test
SourceMap: creating for d:\code\sigma\oschina\quickopen-autofill\out\test\extension.test.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../../src/test/extension.test.ts"]
SourceMap: no sourceRoot specified, using script dirname: d:\code\sigma\oschina\quickopen-autofill\out\test
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
Discovering targets via http://127.0.0.1:16630/json
To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":false,"message":"Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: [ {\n  \"description\": \"node.js instance\",\n  \"devtoolsFrontendUrl\": \"chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:16630/3afe2a45-8cdc-4601-b54e-666bb225569e\",\n  \"faviconUrl\": \"https://nodejs.org/static/favicon.ico\",\n  \"id\": \"3afe2a45-8cdc-4601-b54e-666bb225569e\",\n  \"title\": \"\u0019flv(\u0004\",\n  \"type\": \"node\",\n  \"url\": \"file://\",\n  \"webSocketDebuggerUrl\": \"ws://127.0.0.1:16630/3afe2a45-8cdc-4601-b54e-666bb225569e\"\n} ]\n\n).","body":{"error":{"id":2010,"format":"Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Response from the target seems invalid: [ {\n  \"description\": \"node.js instance\",\n  \"devtoolsFrontendUrl\": \"chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:16630/3afe2a45-8cdc-4601-b54e-666bb225569e\",\n  \"faviconUrl\": \"https://nodejs.org/static/favicon.ico\",\n  \"id\": \"3afe2a45-8cdc-4601-b54e-666bb225569e\",\n  \"title\": \"\u0019flv(\u0004\",\n  \"type\": \"node\",\n  \"url\": \"file://\",\n  \"webSocketDebuggerUrl\": \"ws://127.0.0.1:16630/3afe2a45-8cdc-4601-b54e-666bb225569e\"\n} ]\n\n","_timeout":"10000"}}}}
From client: disconnect({"restart":false})
Terminated: Got disconnect request. Waiting for any pending steps or log messages
To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
Current step and log messages complete
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Got disconnect request"}}}
To client: {"seq":0,"type":"event","event":"terminated"}
```

**Comment by roblourens** [comment] 2017-12-21 17:05
I'll have to look at where the 'title' is coming from, and probably file a bug upstream.

**Comment by g8up** [comment] 2017-12-22 06:48
I have been interrupted by this issue for almost a month.
Thanks for your reply. @roblourens 

I analytic on of the title in error message: 
```
for( let char of "�flv(�"){
    console.log( char.charCodeAt( 0) );
}
25
102
108
118
40
4
```

**Comment by roblourens** [comment] 2017-12-24 04:57
Have you ever tried to debug a node app or Chrome from vscode on this computer? If not, can you see whether basic node debugging works?

I've tried changing the computer locale to Chinese but I haven't seen "title" as anything but "Node.js".

**Comment by RenRongrong** [comment] 2017-12-25 05:44
I have tried to debug a node app and a webpage just now. The node app is ok while the webpage in chrome throws an error: Cannot connect to runtime process, timeout after 10000 ms(reason: cannot connect to the target. connect ECONNREFUSED 127.0.0.1:9222). But the debugger for chrome still works.
![chromedebugger](https://user-images.githubusercontent.com/20409578/34333454-e9c0a542-e977-11e7-90d0-d94bb23f7079.png)
Here, the node app has no error:
![nodedebug](https://user-images.githubusercontent.com/20409578/34333478-25eb8db6-e978-11e7-9e3f-90dbe27f0901.png)

**Comment by roblourens** [comment] 2017-12-25 05:53
Can you try debugging the Node app, then look up the port from the debug console - you will see the command it used to start Node, with a port number, like `--inspect-brk=1234`. Then open `http://localhost:1234/json`, and post the output here? I just want to see if that's something unusual. And post your Node version too.

**Comment by RenRongrong** [comment] 2017-12-25 06:10
Here is the message in debug console:
`Debugging with legacy protocol because Node.js v6.10.0 was detected.
'D:\Program Files\node-v6.10.0-win-x86\node-v6.10.0-win-x86\node.exe' --nolazy --debug-brk=23178 server.js 
Debugger listening on [::]:23178
开始执行监听！`
Node version is 6.10.0. And I opened `http://localhost:23178/json` and recieved ERR_INVALID_HTTP_RESPONSE.
![nodejson](https://user-images.githubusercontent.com/20409578/34334000-2c8801cc-e97d-11e7-86af-4fdd42e66747.png)

**Comment by roblourens** [comment] 2017-12-25 15:07
With a Node version that old, you will also have to add `"protocol": "inspector"` to your launch config, or upgrade to a newer Node version, for this test to work.

**Comment by RenRongrong** [comment] 2017-12-26 01:49
I updated my Node to version 8.9.3 but the error is still thrown. 
`[ {
  "description": "node.js instance",
  "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:38246/b5c809c3-41a4-4680-ba06-004e211ec269",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "b5c809c3-41a4-4680-ba06-004e211ec269",
  "title": "q�v(",
  "type": "node",
  "url": "file://",
  "webSocketDebuggerUrl": "ws://127.0.0.1:38246/b5c809c3-41a4-4680-ba06-004e211ec269"
} ]`
This message can be responsed in browser opening `http://localhost:38246/json`.
I also tried to debug a node app and get a message as below:
`[ {
  "description": "node.js instance",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "5b4710a6-5aa6-4afb-8c5a-bb5edb4b9305",
  "title": "server.js",
  "type": "node",
  "url": "file://D:_OneDrive_Documents_NodeStudy_server.js"
} ]`

**Comment by roblourens** [comment] 2017-12-26 15:33
Thanks. So it's showing the correct title when you run Node manually, the problem is only when debugging Node in Electron.

**Comment by roblourens** [comment] 2017-12-26 15:56
I opened https://github.com/electron/electron/issues/11524 upstream. Can you run `chcp` in the vs code terminal and tell me what the output is?

**Comment by RenRongrong** [comment] 2017-12-27 01:19
Running chcp returns 936. My vscode path is "D:\Program Files\Microsoft VS Code\Code.exe", and My project path is "D:\projects\Repo\minibrowser"

**Comment by roblourens** [comment] 2017-12-27 05:11
Could you try installing vscode to the C drive, to check whether that makes a difference? Upstream issue says 

> It looks like that user has a non-utf8 compliant path to VSCode.exe (this absolute path is what would be in the title on Windows). I'd suggest trying to get the path for VSCode changed on that users machine (or at least figure out what it is at the moment).

**Comment by g8up** [comment] 2017-12-27 14:01
I reinstall a new version `VS code v1.19.1`, and all goes well.

**Comment by RenRongrong** [comment] 2017-12-27 15:35
I have a meeting next two days so I can't operate the computer which is in my office. I will reinstall vscode when I come back to work.

**Comment by RenRongrong** [comment] 2018-01-03 04:05
I reinstalled vscode to C drive, but the issue still exists. The "title" now is qCw(, seems a little different from before.

**Comment by roblourens** [comment] 2018-01-03 05:47
Thanks for trying that. Is it in the default install location? So the path now is something like `C:\Program Files\Microsoft VS Code\Code.exe`?

Earlier you tried debugging with node. Could you try that again, but launch node with an absolute path to the .js file? I think then node will put the full path in the title like electron is doing, and I'm curious whether that will break it.

**Closed** 2018-01-10 06:00 UTC
Labels: debug, needs more info, upstream
