### ISSUE TITLE
AddConfigurations does not respect `{` on the same line as `[`

### ISSUE THREAD

**Issue by nicolehaugen79** [Microsoft/vscode#22624] opened 2017-03-14 20:02 UTC
- VSCode Version: 1.11.0-insider
- OS Version: Win 10

I can't quite figure out exactly what seems to cause this, but a common factor seems to be when the launch.json file is hand-edited as mentioned in the repro steps.  Once VS code gets into a state where the Node.js specific debug config options are displayed, I can't figure out how to get them back - the only way I have found is to delete the launch.json file and start over which obviously isn't ideal.

Steps to Reproduce:

1. In VS Code, clone the following node.js project: https://github.com/scotch-io/node-todo
2. Open the above project, click the debug button in the left hand pane, and then in the debug configuration drop-down menu, choose to "Add configuration" (note that at this point, you shouldn't have any configurations created).
3. From the configuration popup menu, notice that you are presented with a list of common Node.js configurations - select the "Node.JS: Launch Program" configuration.
4. In the first configuration option, change the "program" value to "${workspaceRoot}/server.js" - don't change anything else in the file and then save.
6. Open the debug configuration drop-down menu again and choose "Add configuration".

This time, when the configuration popup menu is displayed, all of the Node.js configuration options are missing.  Refer to the first attached screen shot shows the actual list; the second screenshot shows what should be displayed instead.

![actual](https://cloud.githubusercontent.com/assets/10600161/23920024/15274ca0-08c7-11e7-9739-f99c971ccd44.png)
![expected](https://cloud.githubusercontent.com/assets/10600161/23920023/150e10b4-08c7-11e7-8609-3aec8e643e2a.png)

**Comment by weinand** [comment] 2017-03-14 21:22
@nicolehaugen79 the first screenshot shows 'attribute intellisense' whereas the second shows 'launch configuration snippets'. The first is only available inside a launch config ('x' in the following json), the second is only available on the array level, that is between launch configs or at the top of the array ('y' in the following json):
```json
 {
	"configurations": [
		y
		{
			x
		},
		y
		{
			x
		}
	]
}
```

Having said that, I'm not really sure that I have understood the problem you are seeing.

**Comment by nicolehaugen79** [comment] 2017-03-14 21:27
To clarify, I only see the 'attribute intellisense' regardless of where I put my cursor in the launch.json file - I made sure that I tried both 'x' and 'y' locations that you showed above, and no matter what, I only see the attribute intellisense.  I can't figure out how to get the 'launch configuration snippets' back - they never show no matter where the cursor is positioned in the launch.json.

**Comment by weinand** [comment] 2017-03-14 21:32
@nicolehaugen79 are there any squigglies showing up in the launch.json? This could indicate that there is a syntactical problem which prevents VS Code from showing the snippet intellisense.

**Comment by nicolehaugen79** [comment] 2017-03-14 21:36
No, there are no squigglies - I've also verified that I can run the app fine using the launch.json...it's just that I've lost the snippet intellisense.

**Comment by weinand** [comment] 2017-03-14 21:38
I've just tried editing a huge launch.json with the latest Insiders on Windows 10 and I was able to confuse VS Code.
Could you share the launch.json that produces the problem for you?

**Comment by nicolehaugen79** [comment] 2017-03-14 21:41
When you say that you were able to confuse VS Code - you were able to repro this issue?  

Here's the contents of my file: 
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
        
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/server.js"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "address": "localhost",
            "port": 5858
        }
    ]
}

**Comment by weinand** [comment] 2017-03-14 21:53
@nicolehaugen79 oops, I forgot a 'not'. I was **not** able to confuse VS Code. I've fixed my previous comment.

**Comment by nicolehaugen79** [comment] 2017-03-14 21:55
ok - if you still have issues repro'ing, let me know and I can show you on my machine to make sure that I'm not overlooking something here.

**Comment by weinand** [comment] 2017-03-14 21:59
Thanks for the launch.json, but I cannot reproduce the problem with it.

@isidorn will continue the investigation tomorrow (I'm just doing bug triage).

**Comment by nicolehaugen79** [comment] 2017-03-14 22:00
ok, ping me tomorrow then and I can share my machine and show what I'm doing - my alias is nicolela.

**Comment by isidorn** [comment] 2017-03-15 09:07
The issue is that you have a curly bracket on end of line 6 in your `launch.json`.
Put that curly bracket on the next line and everything will work fine.

The bottom line issue is that the addConfigurations action searches for the opening `[` and adds a new line after that line - this does not cover tha case when `{` is on the same line as `[`

Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L431

**Comment by nicolehaugen79** [comment] 2017-03-15 16:40
I am not sure when the backlog milestone will occur is - but I think this issue should be fixed as a higher priority.  The reason is, that as soon as I made an edit to the launch.json file and save, by default the launch.json automatically formats so that the '{' and '[' are on the same line which then breaks the 'configuration snippets' from appearing.

**Comment by isidorn** [comment] 2017-03-15 16:43
@nicolehaugen79 that is just the way you have your json formater setup - possibly by an extension.
Our json formater out of the box does not format that way - as I am not seeing the behavior you are describing

**Comment by nicolehaugen79** [comment] 2017-03-15 16:47
yes... you are right...I realized that I had the extension "JS-CSS-HTML Formatter" installed which I believe is the culprit here.

**Comment by isidorn** [comment] 2017-03-15 17:01
That extension has 200 000 installs, so we might want to do something here, assigning to march to investigate if there is a nice fix, if we do not get a pr in the meantime

**Closed** 2017-03-16 14:53 UTC
Labels: bug, debug
