### ISSUE TITLE
Application freezes after pasting information

### ISSUE THREAD

**Issue by kypmmhoff** [Microsoft/vscode#266] opened 2015-11-19 18:10 UTC
After install the last update:
Version 0.10.1
Commit df352367df2efcfa9d602d471e4e2f42140a0f05
Shell 0.34.1
Render 45.0.2454.85
Node 4.1.1
With only paste a text in a new file the entire screen freezes, only the menu bar response but don't work.
Operating system windows 8.1.

**Comment by bpasero** [comment] 2015-11-19 18:13
@kypmmhoff can you share the data you pasted to make this happen, e.g. in a Gist? If it does not contain sensitive data of course!

**Comment by Dev-P** [comment] 2015-11-19 18:27
I think it is related to the extensions! The VSCode always freezes after I have updated to the version 0.10.1 and sometimes it gives me a message that something happened to the extensions and restart the VSCode.

**Comment by kypmmhoff** [comment] 2015-11-19 19:30
Not is a complex code, after edit an existent file, freezes to write a function name.
Note: Before a freezes don't display intellisense

![error](https://cloud.githubusercontent.com/assets/495616/11281622/fb8113d4-8ec0-11e5-9719-8ce49509301e.jpg)

**Comment by Dev-P** [comment] 2015-11-19 19:40
I think we are on the same boat! I've faced this problem hundred times today while coding in PHP.

**Comment by bingzheyuan** [comment] 2015-11-19 22:54
I believe this is the same issue as #160. Check that post and downgrade will be the best choice so far.

**Comment by bpasero** [comment] 2015-11-20 20:34
Closing as duplicate of #160.

**Closed by bpasero** 2015-11-20 20:34 UTC
Labels: Bug
