### ISSUE TITLE
Organize imports erroneously removes needed imports

### ISSUE THREAD

**Issue by iosdev-republicofapps** [Microsoft/vscode#49729] opened 2018-05-12 01:16 UTC
- VSCode Version: 1.23.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1.
2.

Hi, I'm seeing this issue still in VSCode 1.23.1 and I'm not using either Typescript or aliases.  For example in simple code like:
```
// VSCode erroneously removes this import and breaks my app with "Can't find variable: reducer" errors.  Every time I add the import and save, VSCode removes the import (and it should NOT as the import is provably needed).
import reducer from "./firebaseApi";

const allReducers = combineReducers({
  // import needed
  reducer,
});
```
I can confirm that this has nothing to do with ESLint or Prettier and the only remedy is to set
```
  "editor.codeActionsOnSave": {
    "source.organizeImports": false
  },
```
However I want organizeImports on in general - this is the only file that it's screwing up.  Any way to turn it off for just this file?

Is there an ETA on a fix?

Thanks!

Does this issue occur when all extensions are disabled?: Yes

**Comment by no-stack-dub-sack** [comment] 2018-05-12 01:27
@iosdev-republicofapps as a temporary workaround, you can write your code as:

```ts
const allReducers = combineReducers({
  reducer: reducer,
});
```
which will prevent the import for being deleted on save.

**Comment by iosdev-republicofapps** [comment] 2018-05-12 01:34
Thanks @no-stack-dub-sack .

**Comment by iosdev-republicofapps** [comment] 2018-05-12 01:35
Also, I can confirm that this has been fixed in the following insiders build:

Version 1.24.0-insider (1.24.0-insider)
987c3dccf45ef0447b7b4c52c81794fab2b6dad5
2018-05-11T05:05:10.476Z

**Comment by iosdev-republicofapps** [comment] 2018-05-12 01:37
@no-stack-dub-sack - just curious why this happens here?  I use `{ userId, userProfile }` instead of `{userId: userId, userProfile: userProfile}` all the time and VSCode has no problem with it.  Why is the `keyName: keyName` necessary here do you think?  Thanks again.

**Comment by no-stack-dub-sack** [comment] 2018-05-12 02:25
@iosdev-republicofapps wait, is there a way to get the insiders build?

**Comment by deadcoder0904** [comment] 2018-05-12 07:09
Can confirm. It removed my import.

# Before Organise Import

```js
import React from "react";
import ApolloClient from "apollo-boost";
import { withClientState } from "apollo-link-state";
import { ApolloProvider } from "react-apollo";

import { defaults, resolvers } from "./resolvers/todos";
```

# After Organise Import

```js
import React from "react";
import ApolloClient from "apollo-boost";
import { withClientState } from "apollo-link-state";
import { ApolloProvider } from "react-apollo";
```

**Comment by mjbvz** [comment] 2018-05-14 15:13
Thanks. This is a duplicate of #49193 

It is fixed in vscode insiders

**Closed by mjbvz** 2018-05-14 15:13 UTC
Labels: new release
