### ISSUE TITLE
Getting `command 'markdown.showPreview' not found` and `command 'markdown.showPreviewToSide' not found`

### ISSUE THREAD

**Issue by dulajdilshan** [microsoft/vscode#166830] opened 2022-11-21 02:52 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: MacOS Ventura (13.0)

Steps to Reproduce:

1. Open a directory with markdown file
2. Open the markdown file in the editor
3. Try clicking the markdown preview button (on right-hand side top corner

**Comment by gjsjohnmurray** [comment] 2022-11-21 03:00
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by dulajdilshan** [comment] 2022-11-21 03:08
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Thanks found the buggy extension (our own extension). We will work on it

**Comment by gjsjohnmurray** [comment] 2022-11-21 10:20
@dulajdilshan please close this issue.

**Closed** 2022-11-21 11:33 UTC
