### ISSUE TITLE
Code-Insiders Crashes and won't open

### ISSUE THREAD

**Issue by a-sajjad72** [microsoft/vscode#213859] opened 2024-05-29 22:15 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0-insider 0ead1f80c9e0d6ea0732c40faea3095c6f7f165a x64
- OS Version: Ubuntu 24.04 LTS and Pop!_OS

Steps to Reproduce:

1. Install Code Insiders snap from Snapcraft
2. Launch Code Insiders by `code-insiders` on terminal or from Applications

Verbose Output:
[code-insiders_verbose.txt](https://github.com/microsoft/vscode/files/15491044/code-insiders_verbose.txt)

Screen recording:
[Screencast from 2024-05-30 02-08-59.webm](https://github.com/microsoft/vscode/assets/90617891/35ed073d-aef8-4a9e-8fc2-8139cdbeb7be)

_The apps works soomothly when installed with a local .deb file. issue only exists when installed as snap_

**Comment by Rexogamer** [comment] 2024-05-30 03:53
duplicate of #212494

**Comment by a-sajjad72** [comment] 2024-05-30 07:49
> duplicate of #212494

@Rexogamer any update on this issue. not resolved yet.

**Comment by a-sajjad72** [comment] 2024-05-30 07:52
> duplicate of #212494

@Rexogamer any update on this issue. not resolved yet.

**Comment by deepak1556** [comment] 2024-05-31 03:47
Merging to https://github.com/microsoft/vscode/issues/212494

**Closed by deepak1556** 2024-05-31 03:47 UTC
