### ISSUE TITLE
Implement an overflow design for the status bar

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12941] opened 2016-09-28 21:05 UTC
Testing #12519 

Change window.zoomLevel in settings to 3, and shrink the window a bit until the "responsive" design starts kicking in. Pressing Ctrl+M then toggles the UI between the following two states:
![image](https://cloud.githubusercontent.com/assets/762848/18932111/d3f702dc-8583-11e6-833f-42df3a6fbdd0.png)

This is problematic because
-  there's no indication to the user what just happened or that the mode switch was successful.
- It's unclear (from a user perspective) why stuff just disappeared from the status bar

**Comment by mousetraps** [comment] 2016-09-28 21:07
Also, if you toggle into the tab-moves-focus mode, and start tabbing through the UI, eventually the remainder of the status bar will appear (sort of)
![image](https://cloud.githubusercontent.com/assets/762848/18932310/a9e62292-8584-11e6-8c82-c834d5de1d6e.png)

**Comment by joaomoreno** [comment] 2016-09-28 21:29
Oh my.

**Comment by bpasero** [comment] 2016-09-29 05:46
I think this is a general issue with the statusbar overflow design that we need to revisit. I think no matter how small the status bar is, we should always show the "Tab Moves Focus" indicator.

**Comment by bpasero** [comment] 2016-10-03 07:34
@mousetraps no matter how small I make the window and zoom, the indicator always has enough space to show (tried on Windows and Mac):

![screen shot 2016-10-03 at 09 33 36](https://cloud.githubusercontent.com/assets/900690/19030217/86d701e2-894c-11e6-8742-9256dcb6ab7c.png)

**Comment by bpasero** [comment] 2016-10-03 07:38
@mousetraps needs more info how to reproduce, maybe you hit a corner case where this happened or maybe you have some extension installed that contributes to the status bar?

**Comment by bpasero** [comment] 2016-10-13 09:58
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by roblourens** [comment] 2016-10-27 00:58
I can repro this fairly easily. This is with no zoom. But you have to play around with the size a little, and it's different if you have other status bar items. Disabled all the status bar item extensions here.
![oct-26-2016 17-57-24](https://cloud.githubusercontent.com/assets/323878/19750405/ae823930-9ba5-11e6-8005-4e4bd139e779.gif)

**Comment by roblourens** [comment] 2016-10-27 01:04
I haven't been able to make the status bar scroll up like in the second picture though. #14565 though.

**Comment by sean-mcmanus** [comment] 2017-01-28 03:45
The C++ extension shows the current class/method in the status bar and we want to take up as much space as possible, but when the text is too long it disappears, which is not good because the UI is no longer clickable to invoke the navigation dropdown. It would be great if you guys could implement some text overflow solution that could solve this (e.g. abridge text with "..." instead of removing all of it). Currently, we hard code a string length but we can't tell how much space is available, so the next easy fix is for us to add a user setting for this length.

**Comment by bpasero** [comment] 2017-11-17 08:29
https://github.com/Microsoft/vscode/issues/6651

**Closed by bpasero** 2017-11-17 08:29 UTC
Labels: feature-request, ux, workbench-status
