### ISSUE TITLE
Format HTML code not working

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#57503] opened 2018-08-29 12:42 UTC
Version: 1.27.0-insider
Commit: 47d0584301d16d4efd6618f6f33ef14099c92561
Date: 2018-08-29T05:18:47.523Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Open a file called 'Test.html'
2. Go to the command palette and select 'Format document'. Notice nothing happens.

User settings:
```
{
    "editor.formatOnType": true,
    "editor.formatOnPaste": true,
    "editor.wordWrap": "on",
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
    "window.zoomLevel": 0,
    "git.ignoreMissingGitWarning": true,
    "editor.fontSize": 12,
    "html.format.enable": true
}
```

```html
<!DOCTYPE html>
<html><head><style type="text/css">
body {font-family:verdana;background-color:white;}
h1 {background-color:black;color:white;margin-bottom:10px;text-indent:10px;page-break-before: always;}
h2 {background-color:lightGrey;margin-bottom:10px;text-indent:10px;page-break-before: always;}
h3 {background-color:lightGrey;margin-bottom:10px;font-size:16px;text-indent:10px;page-break-before: always;}
p {font-size: 14px;margin-left:10px;}
p.italic {font-style: italic;font-size: 12px;}
table {font-size:14px;border-collapse:collapse;border:1px none;padding:3px;text-align:left;padding-right:10px;margin-left:10px;}
td, th {font-size:14px;border-collapse:collapse;border:1px none;padding:3px;text-align:left;padding-right:10px}
li {font-size: 14px;}
base {target="_blank"}
</style></head><body>
<h1>Permission matrix (BNL Weekly)</h1>
<h2>The following has been reported:</h2>
<p>This report contains an overview of the Excel files .</p>
<style>
	            a {
					color: Black;
                    text-decoration: none;
				}
                a:hover {
                    text-decoration: underline;
                }
                #TableStd {
	                border: 1px solid Black;
	                border-collapse: collapse;
					background-color: Gray;
                }
				#TableStd th {
					text-align:center;
                }
                #TableStd td {
                    border-bottom: 1px solid Black;
                }
				#TableInside td{
					    border: none;
				}
                #TableMatrix {
	                border: 1px solid Black;
	                border-collapse: collapse;
	                width: 600px;
                }
                #TxtLeft{
                    border: 1px solid Black;
	                text-align:left;
					padding: 4px;
                }
                #TxtRight{
                    border: 1px solid Black;
	                text-align:right;
					padding:4px;
                }
                #TxtCentered {
                    border: 1px solid Black;
	                text-align: center;
					padding: 4px;
                }
                #TxtTitle {
                    border: 1px solid Black;
	                background-color: LightGreen;
	                text-align: center;
					padding: 6px;
                }
                #LegendTable {
                    border-collapse: collapse;
                    table-layout: fixed;
                    width: 600px;
                }
                #LegendRow {
	                text-align: center;
	                width: 150px;
	                border: 1px solid Black;
                }
                </style>                <h3>Summary</h3>
                <table id="TableStd">
                    <tr>
	                    <th>File</th>
						<th>E</th>
						<th>W</th>
					    <th>GoTo</th>
                    </tr>                     <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Brussels Distrib.xlsx">BEL FLD-AGG-Comp Brussels Distrib</a></td>
						<td>0</td>
						<td>0</td>
	                    <td><a href="#BEL FLD-AGG-Comp Brussels Distrib">Settings</a></td>
                    </tr>                    <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Brussels Logistics Belgium France.xlsx">BEL FLD-AGG-Comp Brussels Logistics Belgium France</a></td>
	                    <td>0</td>
						<td>0</td>
	                    <td><a href="#BEL FLD-AGG-Comp Brussels Logistics Belgium France">Settings</a></td>
                    </tr>                    <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Brussels QSE System.xlsx">BEL FLD-AGG-Comp Brussels QSE System</a></td>
	                    <td>0</td>
						<td>0</td>
	                    <td><a href="#BEL FLD-AGG-Comp Brussels QSE System">Settings</a></td>
                    </tr>                    <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Brussels QualDev.xlsx">BEL FLD-AGG-Comp Brussels QualDev</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL FLD-AGG-Comp Brussels QualDev">Settings</a></td>
                    </tr>                    <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Kust.xlsx">BEL FLD-AGG-Comp Kust</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL FLD-AGG-Comp Kust">Settings</a></td>
                    </tr>                    <tr style="background-color: Orange;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Sites.xlsx">BEL FLD-AGG-Comp Sites</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL FLD-AGG-Comp Sites">Settings</a></td>
                    </tr>                    <tr style="background-color: Orange;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-AEM-HTC.xlsx">BEL MTX-AEM-HTC</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL MTX-AEM-HTC">Settings</a></td>
                    </tr>                    <tr style="background-color: Orange;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-CEM-CBR Gent.xlsx">BEL MTX-CEM-CBR Gent</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL MTX-CEM-CBR Gent">Settings</a></td>
                    </tr>                    <tr style="background-color: Orange;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-CEM-CBR Gent2.xlsx">BEL MTX-CEM-CBR Gent2</a></td>
	                    <td>0</td>
						<td>0</td>
	                    <td><a href="#BEL MTX-CEM-CBR Gent2">Settings</a></td>
                    </tr>                    <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-IMSO-MAT.xlsx">BEL MTX-IMSO-MAT</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL MTX-IMSO-MAT">Settings</a></td>
                    </tr>                    <tr style="background-color: Orange;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-STAFF-GM.xlsx">BEL MTX-STAFF-GM</a></td>
	                    <td>0</td>
						<td>0</td>
	                    <td><a href="#BEL MTX-STAFF-GM">Settings</a></td>
                    </tr>                    <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-Staff-HR.xlsx">BEL MTX-Staff-HR</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL MTX-Staff-HR">Settings</a></td>
                    </tr>                    <tr style="background-color: Orange;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-TEAM-AFRICA.xlsx">BEL MTX-TEAM-AFRICA</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL MTX-TEAM-AFRICA">Settings</a></td>
                    </tr>                    <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-TEAM-LEGAL.xlsx">BEL MTX-TEAM-LEGAL</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL MTX-TEAM-LEGAL">Settings</a></td>
                    </tr>                    <tr style="background-color: Orange;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-WSE-HTC.xlsx">BEL MTX-WSE-HTC</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#BEL MTX-WSE-HTC">Settings</a></td>
                    </tr>                    <tr style="background-color: LightGrey;">
	                    <td><a href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\FRA FLD-AGG-Comp Loos.xlsx">FRA FLD-AGG-Comp Loos</a></td>
	                    <td>0</td> 						<td>0</td>
	                    <td><a href="#FRA FLD-AGG-Comp Loos">Settings</a></td>
                    </tr>                </table>                <h3>Settings</h3>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL FLD-AGG-Comp Brussels Distrib" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Brussels Distrib.xlsx">BEL FLD-AGG-Comp Brussels Distrib</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">DISTRIB</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:13:07</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Brussels Distrib\2018-05-21 0400 (Monday) - Distrib{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL FLD-AGG-Comp Brussels Logistics Belgium France" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Brussels Logistics Belgium France.xlsx">BEL FLD-AGG-Comp Brussels Logistics Belgium France</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Logistics</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:02:08</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Brussels Logistics Belgium France\2018-05-21 0400 (Monday) - Logistics{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL FLD-AGG-Comp Brussels QSE System" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Brussels QSE System.xlsx">BEL FLD-AGG-Comp Brussels QSE System</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">QSE System</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:03:42</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Brussels QSE System\2018-05-21 0400 (Monday) - Qse system{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL FLD-AGG-Comp Brussels QualDev" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Brussels QualDev.xlsx">BEL FLD-AGG-Comp Brussels QualDev</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">QualDev</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:00:54</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Brussels QualDev\2018-05-21 0400 (Monday) - Qualdev{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL FLD-AGG-Comp Kust" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Kust.xlsx">BEL FLD-AGG-Comp Kust</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Kust</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">01:24:49</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Kust\2018-05-21 0400 (Monday) - Kust{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL FLD-AGG-Comp Sites" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL FLD-AGG-Comp Sites.xlsx">BEL FLD-AGG-Comp Sites</a></th>
                    </tr>                        <tr style="background-color: Orange;">
	                        <td id="TxtLeft">Antoing</td>
	                        <td id="TxtCentered">BELSFANTC0149</td>
	                        <td id="TxtLeft">Permissions incorrect</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">01:18:55</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Sites\2018-05-21 0400 (Monday) - Antoing{0}- Overview.html">Log</a></td>
                        </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Beez</td>
	                        <td id="TxtCentered">BELSFBEEZ0133</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:13:03</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Sites\2018-05-21 0400 (Monday) - Beez{0}- Overview.html">Log</a></td>
                        </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Chanxhe</td>
	                        <td id="TxtCentered">BELSFCHAN0137</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:07:16</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Sites\2018-05-21 0400 (Monday) - Chanxhe{0}- Overview.html">Log</a></td>
                        </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Lustin</td>
	                        <td id="TxtCentered">BELSFLUST0132</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:10:11</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Sites\2018-05-21 0400 (Monday) - Lustin{0}- Overview.html">Log</a></td>
                        </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Monceau</td>
	                        <td id="TxtCentered">BELSFMONC0138</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:11:35</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Sites\2018-05-21 0400 (Monday) - Monceau{0}- Overview.html">Log</a></td>
                        </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Quenast</td>
	                        <td id="TxtCentered">BELSFQUEN0140</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:21:54</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Sites\2018-05-21 0400 (Monday) - Quenast{0}- Overview.html">Log</a></td>
                        </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Tellier des Prés</td>
	                        <td id="TxtCentered">BELSFTELL0139</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:08:13</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Sites\2018-05-21 0400 (Monday) - Tellier des prés{0}- Overview.html">Log</a></td>
                        </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Vaulx</td>
	                        <td id="TxtCentered">BELSFVAUL0142</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:31:56</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL FLD-AGG-Comp Sites\2018-05-21 0400 (Monday) - Vaulx{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-AEM-HTC" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-AEM-HTC.xlsx">BEL MTX-AEM-HTC</a></th>
                    </tr>                        <tr style="background-color: Orange;">
	                        <td id="TxtLeft">HTC</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions incorrect</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:29:45</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-AEM-HTC\2018-05-21 0400 (Monday) - Htc{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-CEM-CBR Gent" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-CEM-CBR Gent.xlsx">BEL MTX-CEM-CBR Gent</a></th>
                    </tr>                        <tr style="background-color: Orange;">
	                        <td id="TxtLeft">Gent</td>
	                        <td id="TxtCentered">BELSFGENT0129</td>
	                        <td id="TxtLeft">Permissions incorrect</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">03:01:46</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-CEM-CBR Gent\2018-05-21 0400 (Monday) - Gent{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-CEM-CBR Gent2" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-CEM-CBR Gent2.xlsx">BEL MTX-CEM-CBR Gent2</a></th>
                    </tr>                        <tr style="background-color: Orange;">
	                        <td id="TxtLeft">Gent2</td>
	                        <td id="TxtCentered">BELSFGENT2001</td>
	                        <td id="TxtLeft">Permissions incorrect</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:10:57</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-CEM-CBR Gent2\2018-05-21 0400 (Monday) - Gent2{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-IMSO-MAT" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-IMSO-MAT.xlsx">BEL MTX-IMSO-MAT</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">MAT</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:01:55</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-IMSO-MAT\2018-05-21 0400 (Monday) - Mat{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-STAFF-GM" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-STAFF-GM.xlsx">BEL MTX-STAFF-GM</a></th>
                    </tr>                        <tr style="background-color: Orange;">
	                        <td id="TxtLeft">GM</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions incorrect</td>
	                        <td id="TxtCentered">Check</td>
	                        <td id="TxtCentered">00:02:40</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-STAFF-GM\2018-05-21 0400 (Monday) - Gm{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-Staff-HR" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-Staff-HR.xlsx">BEL MTX-Staff-HR</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">HR</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:35:15</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-Staff-HR\2018-05-21 0400 (Monday) - Hr{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-TEAM-AFRICA" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-TEAM-AFRICA.xlsx">BEL MTX-TEAM-AFRICA</a></th>
                    </tr>                        <tr style="background-color: Orange;">
	                        <td id="TxtLeft">Africa</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions incorrect</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:03:46</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-TEAM-AFRICA\2018-05-21 0400 (Monday) - Africa{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-TEAM-LEGAL" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-TEAM-LEGAL.xlsx">BEL MTX-TEAM-LEGAL</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Legal</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:02:27</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-TEAM-LEGAL\2018-05-21 0400 (Monday) - Legal{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="BEL MTX-WSE-HTC" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\BEL MTX-WSE-HTC.xlsx">BEL MTX-WSE-HTC</a></th>
                    </tr>                        <tr style="background-color: Orange;">
	                        <td id="TxtLeft">HTC</td>
	                        <td id="TxtCentered">Server2</td>
	                        <td id="TxtLeft">Permissions incorrect</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:21:10</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\BEL MTX-WSE-HTC\2018-05-21 0400 (Monday) - Htc{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                    <table id="TableMatrix">
                    <tr>
	                    <th id="TxtTitle" colspan="6"><a name="FRA FLD-AGG-Comp Loos" href="\\Somewhere\MatrixManagement\Matrix Docs\3. Weekly\FRA FLD-AGG-Comp Loos.xlsx">FRA FLD-AGG-Comp Loos</a></th>
                    </tr>                        <tr style="background-color: LightGrey;">
	                        <td id="TxtLeft">Loos</td>
	                        <td id="TxtCentered">FRASALOOS0001</td>
	                        <td id="TxtLeft">Permissions ok</td>
	                        <td id="TxtCentered">Fix</td>
	                        <td id="TxtCentered">00:12:31</td>
	                        <td id="TxtCentered"><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)\FRA FLD-AGG-Comp Loos\2018-05-21 0400 (Monday) - Loos{0}- Overview.html">Log</a></td>
                        </tr>                    </table>
                    <br>                <table id="LegendTable">
                <tr>
	                <td style="background-color: Orange;" id="LegendRow">Warning</td>
	                <td style="background-color: Red;" id="LegendRow">Error</td>
                </tr>
                </table>
<h2>About</h2>
<table>
<colgroup><col/><col/></colgroup>
<tr><th>Start time</th><td>21/05/2018 04:00 (Monday)</td></tr>
<tr><th>Total runtime</th><td>03:02:53 </td></tr>
<tr><th>Log folder</th><td><a href="\\Server1\Log\Permission matrix\Permission matrix (BNL Weekly)">Open log folder</a></td></tr>

<tr><th>Script location</th><td>S:\Prod\Permission matrix\Permission matrix.ps1</td></tr>
<tr><th>Launched from</th><td>Scheduled task or console (not ISE)</td></tr>
<tr><th>Server</th><td>Server1</td></tr>
<tr><th>Whoami</th><td>GROUPHC.NET\SrvBatch</td></tr>
</table>
<p class=italic>"When Chuck Norris writes a book the letters order themselves in fear."</p>
</body></html>
```

**Comment by V-ed** [comment] 2018-08-29 13:08
Duplicate of #57445 (which should've been fixed 7 minutes ago!)

**Comment by aeschli** [comment] 2018-08-29 19:28
dup of #57445

**Closed by aeschli** 2018-08-29 19:28 UTC
