### ISSUE TITLE
Shortkeys - Add a "when clause" for "focus is in panel"

### ISSUE THREAD

**Issue by brunetton** [Microsoft/vscode#33672] opened 2017-09-01 12:10 UTC
Hi all, I'm using vscode (1.15.1) for a few days and I've a very good impression about it ! 
However, I'm writing a simple extension and playing with interactive js shell (debug console) and I missed a keyboard shortcut to jump between text editor and panel.
The solution given in [this StackOverflow thread](https://stackoverflow.com/questions/42796887/switch-focus-between-editor-and-integrated-terminal-in-visual-studio-code) is great for swapping between **integrated terminal** and code editor, but here I'm not using terminal, but debug console.

So I tried something very similar (using `ctrl+e` (but no matters)) and tried to add 2 rules like that :

    {
        "key": "ctrl+e",
        "command": "workbench.action.focusPanel",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+e",
        "command": "workbench.action.focusActiveEditorGroup",
        "when": "!editorTextFocus"
    }

But this doesn't work: I can focus from the text edition to the panel, but I can't focus back. I figured out after some tests that when the focus is in panel, `editorTextFocus` is still true (in contrary to `terminalFocus`).

So, to find a solution to my problem, I need a *when clause* that let me know whether the focus is on panel or not. As far as I can see in vscode'code, I can't find any `RawContextKey` that looks like that.

Did I missed something ? (I hope I didn't opened an issue for nothing)
Thanks !

**Comment by Tyriar** [comment] 2017-09-06 15:22
Duplicate of https://github.com/Microsoft/vscode/issues/19400

**Closed by Tyriar** 2017-09-06 15:22 UTC
Labels: integrated-terminal

**Comment by brunetton** [comment] 2017-09-07 08:23
This isn't exactly a duplicate of #19400
<https://github.com/Microsoft/vscode/issues/19400> as #19400
<https://github.com/Microsoft/vscode/issues/19400> is taking about the
shortkey and the automatic show/hide of the panel.
All those tickets are of course related but here I'm not only asking for
the "when" context clause. Maybe they can indeed be merged together.

**Comment by Tyriar** [comment] 2017-09-07 17:26
Ah, I don't think we want to make the shortcuts toggle between the editor and the panels by default but do as described in #19400. You're always free to add your own keybinding tweaks like this though.

**Comment by brunetton** [comment] 2017-09-07 19:42
Exactly
