### ISSUE TITLE
Download dependency package

### ISSUE THREAD

**Issue by DeanHH** [Microsoft/vscode#18217] opened 2017-01-06 09:46 UTC
I'm a Chinese developer.I'd love to work with VScode while coding in c#. But what really bother me it,I have been spending 2 days for downloading the damn C# dependency, especially the Mono 4.6 I never download over 50%.Plz do some policies to make sure the download will goes well even if the net work just very bad, just like china,you know that!!

**Comment by sandy081** [comment] 2017-01-06 10:41
Assuming this is related to market place

**Comment by joaomoreno** [comment] 2017-01-06 10:42
@DeanHH Just to confirm, you were able to install the C# extension, correct? And it fails to download its dependencies, correct?

**Comment by DeanHH** [comment] 2017-01-06 12:03
@joaomoreno Yes.C# extension has installed well.And the dependencies never finish download in these two days。And I think I have found an other way to fixed my [problem,](https://github.com/OmniSharp/omnisharp-vscode/issues/1028) ,but the moment I write this comment, I still downloading three of the dependencies from github(i really don't know why it will like that slow....), so I don't know if it will works?
Hopefully you will improve the update procedure, and thank you so much for following my issue.

**Comment by joaomoreno** [comment] 2017-01-06 14:01
Yes, this is indeed a duplicate of OmniSharp/omnisharp-vscode#1028

**Closed by joaomoreno** 2017-01-06 14:01 UTC
Labels: needs more info
