### ISSUE TITLE
Allow tree views to have a search box

### ISSUE THREAD

**Issue by sketchbuch** [microsoft/vscode#88897] opened 2020-01-18 12:12 UTC
Tree views would be more useful if they could have a search box to enable dynamic display of tree items.

I know there is the stupid search within the current views, but I want to populate my treeviews based on user input and not just search through existing items - and no, some kind of command from the command palette isn't good enough. There should be an option for this in all tree views. Like the extension tree provider has.

This surely can't be very difficult to add as you already have it in several built-in tree view providers

**Comment by gjsjohnmurray** [comment] 2020-01-18 17:51
/duplicate of #70646

If that issue doesn't cover everything you are looking for please add your comments there.

**Closed** 2020-01-18 17:51 UTC
Labels: *duplicate, search
