### ISSUE TITLE
Click F5 several times on startup causes duplicated debug sessions

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#36044] opened 2017-10-11 09:39 UTC
When a previous debug session is still on starting, click `F5` once again will cause duplicated debug sessions for the same debug configuration. 

For example, the first activation of the java debug server may cost several seconds to start up. During this period, if user clicks `F5` for several times, VSCode will launch duplicated debug sessions for the same debug configuration. 

Can VSCode client have the possible to fix it? or passing a configuration id for the selected debug config in the API `resolveDebugConfiguration` so that the debugger can check duplicate by itself?

**Comment by isidorn** [comment] 2017-10-11 10:22
This should be fixed and I cannot reproduce this.
Notice that the start debug action is disabled if the state is INITIALIZING https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActions.ts#L143
Or if there is already a session running with the same name 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActions.ts#L149

If you can always reproduce this on your machine please place some breakpoints in the debug action which I linked and check why does he return true. And what is the debug state at that point.

**Comment by testforstephen** [comment] 2017-10-12 06:31
i tried it by adding a breakpoint in `debugAction.ts#isEnabled()`.
When click F5, the state changes like the following:

1. VSCode stop at `debugAction#isEnabled()`, and state is `Inactive`, this function will return `true`.
2. Then `DebugConfigurationProvider#resolveDebugConfiguration` is executed.
3. After the step 2 returned, VSCode stop at `debugAction#isEnabled()` again. state is changed to `Initializing`, and it will return `false`.

`resolveDebugConfiguration` could be async, it may take a long time to return. When the last F5 is still on resolveDebugConfiguration, and click F5 again, apparently the state is still `Inactive` and VSCode will launch a duplicated debug session.

It can be reproduced like the following. You can add a breakpoint at `DebugConfigurationProvider#resolveDebugConfiguration` to mock the long time operation.

Click 1st F5
&nbsp;&nbsp;&darr;
&nbsp;&nbsp;Inactive -> [execute a long time job in resolveDebugConfiguration func ... ] -> Initializing
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &darr;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Click 2nd F5
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&darr;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Inactive  ---------------------------------------------------------> [ resolveDebugConfiguration ...] -> Initailzing

**Comment by isidorn** [comment] 2017-10-12 13:04
@testforstephen I acknowledge this bug. Thanks for providing more details, I will try to get it fixed

**Comment by jrieken** [comment] 2017-11-02 11:54
<img width="908" alt="screen shot 2017-11-02 at 12 53 49" src="https://user-images.githubusercontent.com/1794099/32324812-e5a58448-bfcc-11e7-9016-c18919a0ebe8.png">

**Comment by isidorn** [comment] 2017-11-17 17:29
Can not reproduce this.
@jrieken I will have to drop by your machine to investigate further

**Comment by isidorn** [comment] 2018-01-05 18:07
Still can not repro this.
@jrieken can you please try with latest insiders and let me know if you are doing something special?

**Comment by jrieken** [comment] 2018-01-12 20:53
Still repros for me these steps: https://github.com/Microsoft/vscode/issues/36044#issuecomment-341398643

**Comment by isidorn** [comment] 2018-03-14 11:21
After investigating with @jrieken this happens only if the action is triggered in the startup phase of the workbench.
@bpasero is there some elegent approach to register a workbench action only in the WorkbenchPhase.RUNNING.
Or do I need to have a dependency to the lifecycleService to check what is the current phase in my enablement - which feels a bit ugly?

**Comment by bpasero** [comment] 2018-03-14 12:02
@isidorn the knowledge of lifecycle phase does not exist when registering workbench actions (only when registering workbench contributions).

**Comment by isidorn** [comment] 2018-03-14 13:56
@bpasero I would need something like that in order to fix this, in the meantime backlog.
Since I can not seem to get an instance of `lifecycleService` on statup (might not be inititaed yet).

**Comment by bpasero** [comment] 2018-03-14 14:00
@isidorn can you not check for the lifecycle phase from your action that gets executed?

**Comment by isidorn** [comment] 2018-03-14 14:12
@bpasero not when the workbench asks if my action is enabled since the `lifecycleService` seems to be undefined.
I could probably check when it gets executed but that feels hacky (what is the point of my enabled method then).

**Comment by bpasero** [comment] 2018-03-14 14:31
There are [so many registries involved](https://github.com/Microsoft/vscode/blob/tyriar/electron-2.0.x/src/vs/workbench/common/actions.ts#L36) when registering a workbench action that I see no direct way to delay that for a specific lifecycle phase....

**Comment by jrieken** [comment] 2018-03-14 15:02
> There are so many registries involved when registering

Well, it is three: you register a command, a keybinding, and menu entry. I know @bpasero is a friend of tight coupling but I won't know what of those three to merge...

@isidorn The fake action instance that is being created should be having a lifecycle service: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/actions.ts#L103

**Comment by isidorn** [comment] 2018-03-14 15:06
> @isidorn The fake action instance that is being created should be having a lifecycle service: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/actions.ts#L103

Not what I see when I run out of source, the lifecycleService is undefined if I press F5 really fast on startup.

**Comment by jrieken** [comment] 2018-03-14 15:10
The [that instance](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/actions.ts#L112) is not? I would expect that it explodes before calling your command. Actually I would expect injection to bail out when a service cannot be found... 

How do you ask for the service? Normal constructor injection?

**Comment by jrieken** [comment] 2018-03-14 16:20
> Not what I see when I run out of source, the lifecycleService is undefined if I press F5 really fast on startup.

Tried it out, don't believe you. If the service isn't there the injector would explode. What I do see is that  two instances of the `StartAction` are created on reload (with the viewlet visible) which is unexpected but into both I can inject the lifecycle service

**Comment by isidorn** [comment] 2018-03-14 17:19
@jrieken thanks for trying it out. By looking at the code you provided I seem to have found the bottom of the issue:
* User hit F5 on startup 5 times -> my actions is asked is it enabled 5 times and all say yes [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/actions.ts#L103)
* When the workspace is actually running all the actions are run from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/actions.ts#L114) - even though they might be disabled now

It feels to be me like each action should re-check if it is enabled before being run at that position.

As for the `lifecycleService` not being there, I understand that the lifecycleService must exist at that point, but it does not seem to be in my action when isEnabled is called on startup. I can show you tomorrow in the office, or I can create a PR demonstrating this - I might also be doing something wrong so it would be interesting to see what.

As for the action being created two times, it is due to the fact that the SplitView decides to update the title area after all the views are there. Not sure what the reason for that is, maybe @sandy081 can clarify

**Comment by sandy081** [comment] 2018-03-15 07:46
Title area is updated when the number of panels changes from 1 to n or from n to 1 (n > 1). Since custom views show up bit late, there is a jump seen in the viewlet title. To avoid this jump, it is stored and read from the cache. But if some of the extensions contributing views gets uninstalled/disabled cache is not valid. So title area is updated again when all extensions are registered. 

Hence title area is updated twice. I think, I can make it more smarter by checking the previous state before second update and decide to update it again or not. It might not be trivial. @isidorn How about reusing the actions instead of creating them again? For example like [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L302)

**Comment by isidorn** [comment] 2018-03-15 13:55
@sandy081 action creation should be very fast so I never bothered to cache them. But thanks for suggestion.

**Closed** 2018-03-15 13:55 UTC
Labels: bug, debug, verification-found
