### ISSUE TITLE
Multiple instances of incorrect tokenization in Sass

### ISSUE THREAD

**Issue by whizkydee** [Microsoft/vscode#38997] opened 2017-11-23 01:47 UTC
Hi guys,

First off, I must say you guys are doing a really great job with `vscode`. Its goodies never seize to amaze me -- Great work guys!!

However, since the release `v1.8.0+`, I've noticed that a bunch of components in the **Sass** language are incorrectly tokenized and this eventually affects proper syntax higlighting. See the images for more info. 

cc @aeschli 

- VSCode Version: 1.8.1
- OS Version: Windows 10

### Steps to Reproduce:
_No need, The image below make it obvious already._

![Imgur](https://i.imgur.com/4JuPBiU.png)

See more occurences at:
[https://i.imgur.com/EomunIL.png](https://i.imgur.com/EomunIL.png)
[https://i.imgur.com/Te9kAAk.png](https://i.imgur.com/Te9kAAk.png)
[https://i.imgur.com/4cUYbeu.png](https://i.imgur.com/4cUYbeu.png)
[https://i.imgur.com/I67nwft.png](https://i.imgur.com/I67nwft.png)

Interstingly, I was able to reproduce this with other themes too, including the **Default Dark** theme, it's the same result. I'm currently using a theme I built [vscode-material-palenight-theme](https://github.com/whizkydee/vscode-material-palenight-theme).

**Reproduces without extensions:** Yes

'Would be glad to have it fixed soon.

Thanks!

**Comment by aeschli** [comment] 2017-11-23 08:53
duplicate of #38001 and #38838, fixed in the 1.19 insiders. If you can check it out, that would be great: https://code.visualstudio.com/insiders/

**Closed by aeschli** 2017-11-23 08:53 UTC

**Comment by whizkydee** [comment] 2017-11-23 12:47
Awesome! 'Would love to have that in stable soon.
