### ISSUE TITLE
When typing, the intellisence window is stuck on the screen

### ISSUE THREAD

**Issue by olebg** [Microsoft/vscode#23403] opened 2017-03-28 11:59 UTC
- VSCode Version: 1.11.0-insiders
- OS Version: Windows 10 Creators Update RTM build

Steps to Reproduce:

1. start typing, for example "func" and the intellisence window offering the completion "function" becomes black and stuck on the screen. The only way to remove it is to restart the VS Code app.
2.
![screenshot 3](https://cloud.githubusercontent.com/assets/11273726/24404022/2553ae1e-13c8-11e7-8371-7156cebe8da2.png)

**Comment by donaldpipowitch** [comment] 2017-03-28 12:18
Can confirm that for 
* OS Version: Mac OS 10.12.3

**Comment by aeschli** [comment] 2017-03-28 13:04
duplicate of #23414

**Closed by aeschli** 2017-03-28 13:04 UTC
