### ISSUE TITLE
Transfer tmGrammar ownership

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#20160] opened 2017-02-08 02:08 UTC

**Comment by aeschli** [comment] 2017-02-08 09:40
Thanks @mjbvz. Here's what to do.
Look at incoming issues regarding TypeScript & JavaScript coloring.
  - make sure the issue is complete and includes the sample sample code
  - reproduce the issue to see if it is still an issue
  - use the 'Developer: Inspect TM Scopes' command to look at the generated scopes to see if the issue is with the grammar or with our theming.
   - If it's a grammar issue, move to https://github.com/Microsoft/TypeScript-TmLanguage
   - If it is a theming issue, assign to me

From time to time, ideally a week before we start testing, check if an update of the grammar is available at https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScript.tmLanguage
- in `extensions/typescript`, run `npm run update-grammars`. This updates 3 files: the Typescript and the TypeScriptReact grammar as well as the JavaScript grammar. The JavaScript grammar is a copy of the TypeScriptReact grammar with scope names renamed from tsx to js.
Check out [update-grammars.js](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/build/update-grammars.js) for details.
- run `script/test-integration.sh` to run the grammar tests. The test takes the entries in [test/colorize-fixtures](https://github.com/Microsoft/vscode/tree/master/extensions/typescript/test/colorize-fixtures) and runs the grammar and theme rule matching on it. The result is written to [test/colorize-result](https://github.com/Microsoft/vscode/tree/master/extensions/typescript/test/colorize-result).
If the written result is identical to the previous result, the test is green, else it is red. Use the Git diff viewer to see the differences in the result. If all changes make sense, accept the new result by committing it. If not, get back to the TypeScript grammar team or to me (for theming issues).
```json
	{
		"c": ">=",
		"t": "source.ts meta.block.ts meta.class.ts meta.method.declaration.ts meta.block.ts keyword.operator.relational.ts",
		"r": {
			"dark_plus": "keyword.operator: #D4D4D4",
			"light_plus": "keyword.operator: #000000",
			"dark_vs": "keyword.operator: #D4D4D4",
			"light_vs": "keyword.operator: #000000",
			"hc_black": "keyword.operator: #D4D4D4"
		}
	}
```
c: Token content, t: TextMate scope stack, r: Colorizer rules matches.
If there are just changes to the TextMate scope stack but coloring stays the same all is fine.
If there are coloring changes, be alert (I'm happy to help)...

**Closed** 2017-02-16 15:11 UTC
Labels: plan-item
