### ISSUE TITLE
Screen reader constantly speaks activating extensions

### ISSUE THREAD

**Issue by daniel-montalvo** [microsoft/vscode#95524] opened 2020-04-17 12:10 UTC
Issue Type: <b>Performance Issue</b>

I tried with both JAWS and NVDA. Even with all extensions disabled, from time to time, JAWS and NVDA speak "Info. Activating extensions. Occured X times". Where X is a number that increases subsequently as the message is spoken.

Steps to reproduce.

1. Open VSCode with either NVDA or JAWS.
2. Have a piece of text or code.
3. Write some more code and then move through the file using the arrow keys.
4. The screen reader You will hear the message "Info... Activating extensions" but you would not be able to tell why this message is triggered.

Getting rid of the whole workspace and using the "Open folder" in a new workspace seems to fix the issue.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (9.21GB free)|
|Process Argv|C:\Users\daniel\Desktop\wai-curricula.code-workspace|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   113	 12652	code main
    0	    68	  6384	   window (Issue Reporter)
    0	    27	  7940	   utility
    0	   203	  8368	   window (● 2-6.md - wai-curricula (Workspace) - Visual Studio Code)
    0	    67	  6192	     extensionHost
    0	    14	  7880	     watcherService 
    0	    11	 13544	       console-window-host (Windows internal process)
    0	   196	 11608	   gpu-process
    0	    16	 12792	   electron-crash-reporter
    0	    74	 15272	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● 2-6.md - wai-curricula (Workspace) - Visual Studio Code)
|    Folder (wai-curricula): 272 files
|      File types: js(65) png(58) woff(19) woff2(18) md(16) html(14) yml(7)
|                  svg(7) json(5) css(3)
|      Conf files: grunt.js(1) package.json(1);
```

</details>
Extensions: none

**Comment by isidorn** [comment] 2020-04-20 09:34
@daniel-montalvo hi. Thanks for filling this issue. However this is a duplicate of https://github.com/microsoft/vscode/issues/95357
Thus it is fixed with latest vscode insiders and due to that I recommend you use vscode insders as this issue is a pain and you will have a nicer experience
https://code.visualstudio.com/insiders/

**Closed by isidorn** 2020-04-20 09:34 UTC
Labels: new release

**Comment by daniel-montalvo** [comment] 2020-04-20 14:50
Many thanks for this suggestion!
