### ISSUE TITLE
Can extensions override default configurations other than editor configurations?

### ISSUE THREAD

**Issue by itiut** [Microsoft/vscode#38027] opened 2017-11-10 05:54 UTC
There is contribution point `configurationDefaults` to override default configurations, but configurations which can be overridden are limited to those about editor configurations. Is there a way for extensions to override default configurations other than editor configurations?

### Background

I used extension [vscode-standardjs](https://github.com/chenxsan/vscode-standardjs), which lints and formats JavaScript codes according to [JavaScript Standard Style](https://github.com/standard/standard), and made built-in JavaScript formatter run on typing (set `editor.formatOnType` to `true`). And I came across a problem about on-type formatting because some default formatting configurations are not appropriate for JavaScript Standard Style (chenxsan/vscode-standardjs#47).

This problem can be avoided by manually overriding default formatter configurations in `settings.json`, but it would be helpful if vscode-standardjs can override default configurations like this:

```
    "configurationDefaults": {
      "[javascript]": {
        "javascript.format.insertSpaceAfterConstructor": true,
        "javascript.format.insertSpaceBeforeFunctionParenthesis": true
      }
    }
```

**Comment by mjbvz** [comment] 2017-11-10 19:07
Possible duplicate of #26707

@sandy081, can you please take a look

**Comment by sandy081** [comment] 2017-11-13 09:30
Yes, Duplicate of #26707

**Closed by sandy081** 2017-11-13 09:30 UTC
Labels: settings
