### ISSUE TITLE
freezes while working in jupyter notebook

### ISSUE THREAD

**Issue by kishan1000** [microsoft/vscode#149471] opened 2022-05-13 14:35 UTC
Does this issue occur when all extensions are disabled?: Didn't try

- VS Code Version: 1.67.1
- OS Version: windows 11

Steps to Reproduce:

1. Open new python Jupyter notebook
2. Write few lines of code
3. VS code  #freezes
4.

**Comment by eo1989** [comment] 2022-05-13 17:00
more notebook issues. tried creating a python file and working in that but then get "Command 'pythonindent.newlineAndIndent' not found",  "command 'python.execSelectionInTreminal' not found". like god damn. install the daily updates and they just break more of the things!

**Comment by dmbaker** [comment] 2022-05-13 22:27
This started happening to me today. Yesterday Notebooks were working fine. 

On Windows, add a new cell then start adding code or add new lines to an old cell, get a dialog that says the app is not responding. 

Was there an update yesterday?

**Comment by rebornix** [comment] 2022-05-16 18:44
Can anyone try disabling all extensions and see if you can stably reproduce? It would also help if we can get some logs by following https://github.com/microsoft/vscode/wiki/Performance-Issues , thank you all in advance

**Comment by rebornix** [comment] 2022-05-16 18:45
I also wonder if this is a duplicate of https://github.com/microsoft/vscode/issues/149412, can you try disable the Pylance extension and see if this still reproduces?

**Comment by membranepotential** [comment] 2022-05-19 11:51
I disabled everything and step-by-step enabled the extensions. Unfortunately I could not reproduce the issue, i. e. now with all extensions back to enabled the issue did not persist.

**Closed** 2022-05-23 03:10 UTC
Labels: freeze-slow-crash-leak, notebook, nb-golden
