### ISSUE TITLE
First char is 0 or 1?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#46784] opened 2018-03-27 23:52 UTC
Testing https://github.com/Microsoft/vscode/issues/46572

- Add a normal column breakpoint on the first column of a line
- The debug adapter gets setBreakpoints with character=1 ✔️ 
- Have an extension that sets a column breakpoint at the cursor location
- `vscode.window.activeTextEditor.selection.start` has character=0
- The debug adapter gets setBreakpoints with character=0, problem because it assumed they were 1-indexed

**Comment by isidorn** [comment] 2018-03-28 09:20
This sounds like some conversion sohuld be in in extHostDebugService, assigning to @weinand

**Comment by weinand** [comment] 2018-03-28 13:06
The problem is that the VS Code debugger distinguishes between an explicit specified column '0' and a missing column but that the breakpoint API does not surface this.

You can easily see this distinction if you create one breakpoint:
- by clicking in the gutter and,
- by using the "Column Breakpoint" action when the cursor is at the beginning of a line.

The breakpoints view shows this:
![2018-03-28_13-13-33](https://user-images.githubusercontent.com/1898161/38025775-e14a5678-3289-11e8-806e-bace3168b98c.png)

The breakpoints are passed to the DA in these distinct shapes: 
- `{ line: 1 }`
- `{ line: 1, column: 1}`

So far, so good.

Since the breakpoint API has no way to specify a breakpoint with a missing column attribute, I was special casing breakpoints with a column '0' coming from the breakpoint API. This resulted in the illegal '0' passed to the DA.

Proposed fix: 

A breakpoint created via the extension API with the values `{ line: x, column: 0}` always results in an internal breakpoint with a missing column attribute: `{ line: x}`. As a consequence no column info is shown in the Breakpoints view (which is desired for "normal" line breakpoints) and a breakpoint with missing column attribute is passed to the DA (which is the desired behaviour too).

However, there is still the problem that the VS Code UI allows to set a column breakpoint in column 0 which is distinct from a line breakpoint. Since this cannot be expressed in the extension API, I propose that we change the VS Code UI so that a column breakpoint in column 0 is represented internally as a breakpoint with missing column attribute. With this VS Code UI and breakpoint API would be on par.

Since this is a change with a bit of a risk (and the issue is not a regression), I suggest to fix this for April.

**Comment by isidorn** [comment] 2018-03-28 14:09
@weinand thanks for the analysis. Makes sense, let's tackle it in April.

**Comment by roblourens** [comment] 2018-03-28 17:58
Is there a difference between the debugger and the editor api on whether columns are 1-indexed or 0-indexed? Do we need to + 1 every column on a bp set via the breakpoint API?

**Comment by roblourens** [comment] 2018-03-28 18:26
Added a workaround for March to keep the adapter from breaking in this case

**Comment by weinand** [comment] 2018-03-28 21:02
@roblourens 
- the extension API is consistently 0-based because everything relies on class "Position" which defines being 0-based. 
- the VS Core debugger is 1-based (because it is much older than anything else). It announces this fact against the DAP in the "initialize" request.
- A debug adapter that uses our npm modules can announce whether it wants to use a 0- or a 1-based locations.
 
All necessary conversion are done automatically.

**Comment by roblourens** [comment] 2018-03-28 21:08
Right, and I think I'm not following your explanation above, did this happen because we are missing the conversion for breakpoints set via the API? Will all breakpoints set via the API be off by 1 column?

**Comment by weinand** [comment] 2018-03-28 21:19
No the conversion is properly done for all but one case:
https://github.com/Microsoft/vscode/blob/4b55e2d7de5b8feafe913b20d7f2844b28acc8dc/src/vs/workbench/api/electron-browser/mainThreadDebugService.ts#L101-L102
and
https://github.com/Microsoft/vscode/blob/4b55e2d7de5b8feafe913b20d7f2844b28acc8dc/src/vs/workbench/api/electron-browser/mainThreadDebugService.ts#L145-L146

My proposal fix would drop the column attribute whenever the extension API adds a breakpoint with column === 0:

![2018-03-28_23-15-07](https://user-images.githubusercontent.com/1898161/38056823-de81367e-32dd-11e8-8462-3120a1030da6.png)

A breakpoint without the "column" attribute would be passed to the DA without the column attribute too. So you would never receive a value of 0.

However, without Isi's UI fix the UI would still allow to create a column breakpoint **with** a 0-column attribute. That's the reason why we should really fix both.

**Comment by roblourens** [comment] 2018-03-28 21:41
Oh, I understand. Thanks

**Comment by weinand** [comment] 2018-04-17 10:16
@isidorn I will push this change:
![image](https://user-images.githubusercontent.com/1898161/38863843-30e6838c-4239-11e8-9c37-1998937d1e46.png)

**Closed** 2018-04-18 10:36 UTC
Labels: bug, debug

**Comment by weinand** [comment] 2018-04-25 10:51
Verified via exercising breakpoints API in a test extension.

@roblourens you can remove your March workaround now (see https://github.com/Microsoft/vscode/issues/46784#issuecomment-376988256).
