### ISSUE TITLE
Files under symlinked folders get different uri if parent of the symlinked folder is opened vs the symlinked folder itself

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#49315] opened 2018-05-06 18:12 UTC
- VSCode Version: All
- OS Version: Mac

Steps to Reproduce:

Run the below to get the folder set up
```
mkdir -p ~/test-symlink-source/folder1
touch ~/test-symlink-source/folder1/file1.txt
mkdir ~/test-symlink-destination
ln -s ~/test-symlink-source/folder1/ ~/test-symlink-destination/
```

1. `code-insiders ~/test-symlink-destination/`
Open `file1.txt` and hover on file tab. The path that appears is `~/test-symlink-destination/folder1/file1.txt`
2. `code-insiders ~/test-symlink-destination/folder1`
Open `file1.txt` and hover on file tab. The path that appears is `~/test-symlink-source/folder1/file1.txt`

This is probably because in the second case, the symlink gets resolved and the original folder is opened by VS Code. A similar issue was logged before (#32649) which didn't get much traction.

This is especially troublesome for extensions that rely on the file uri as exposed by `vscode.window.activeTextEditor.document.uri`. The 2 cases above get different uris.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-05-07 04:06
@ramya-rao-a and so how is this issue not a duplicate of https://github.com/Microsoft/vscode/issues/32649 then?

**Comment by ramya-rao-a** [comment] 2018-05-07 04:58
@bpasero Honestly, when I created this issue, I hadn't found #32649 yet. When I did, I updated the issue description above. You mentioned that #32649 itself is a duplicate, but no issue was linked to it, so I opted to keep this open.

I am ok closing this in favor of any existing open issues.

**Comment by bpasero** [comment] 2018-05-07 06:26
@ramya-rao-a oh I did not see the issue was closed. It is https://github.com/Microsoft/vscode/issues/18837 actually.

**Closed by bpasero** 2018-05-07 06:26 UTC
Labels: needs more info
