### ISSUE TITLE
Extension fails with pnpm command not found

### ISSUE THREAD

**Issue by doubleplusc** [microsoft/vscode#148903] opened 2022-05-04 22:20 UTC
I previously commented on microsoft/vscode-eslint#1462 but OP's problem was fixed so the issue closed. My problem persists even after a restart, so I am creating a new issue.

I have pnpm installed on Linux via `npm install -g pnpm`. pnpm works fine in the vscode integrated terminal and standalone terminals.

The extension fails with the following error on load:
```
Uncaught exception received.
Error: Command failed: pnpm root -g
/bin/sh: line 1: pnpm: command not found

    at checkExecSyncError (node:child_process:835:11)
    at execSync (node:child_process:909:15)
    at node:electron/js2c/asar_bundle:5:12692
    at Object.get (/home/doubleplusc/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:172258)
    at /home/doubleplusc/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:174308
    at /home/doubleplusc/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:174323
```
`pnpm root -g` returns
/home/doubleplusc/.local/share/pnpm/global/5/node_modules

Thanks!

**Comment by dbaeumer** [comment] 2022-05-06 12:34
@joaomoreno not sure anymore if this is you or @bpasero.

What they actually see is when the start VS Code from the Desktop the environment setup is not complete hence result in cases where ESLint doesn't see `pnpm` although it is on the path in the terminal. Everything works fine if VS Code is started from within the terminal.

**Comment by Asesjix** [comment] 2022-05-06 21:05
I start vs code always via `code .` from my zsh (wsl).

**Comment by dbaeumer** [comment] 2022-05-09 07:53
@Asesjix does `pnpm` work in the terminal you start code from

**Comment by Asesjix** [comment] 2022-05-09 08:17
@dbaeumer Yes absolutely, hence my suggestion to use the shell from the automation profile.

**Comment by Asesjix** [comment] 2022-05-09 08:34
My setup is quite simple and not extensively configured.

I am using Windows with WSL running Debian.
In Debian I installed zsh and set it as the default terminal.

Then I installed NVM.
With NVM I install Node in the version in which I need it.
Typically with `nvm install --lts --default`.
It means that the last LTS version will be installed and set as the default.

This means that in my shell `node -v` specifies the version installed via NVM.
Then I install pnpm with `npm install -g pnpm`.

To develop, I then start VS Code with `code .` via the terminal in which `node` and `pnpm` work.

That's it.

**Comment by darthsoup** [comment] 2022-05-09 11:23
Did you guys update to the newest pnpm version? It now needs a alias in the bash config

Try this in your console:
`pnpm setup`

**Comment by Asesjix** [comment] 2022-05-09 19:06
I know and already did that.

**Comment by MIchaelJier** [comment] 2022-05-18 02:52
reload vscode is working for me

**Comment by joaomoreno** [comment] 2022-05-18 13:26
@doubleplusc Do you still hit this?

**Comment by joaomoreno** [comment] 2022-05-20 13:14
The problem here is somewhere in your bashrc (or equivalent). There's something in your rc shell script which makes loading it very slow. Do you not get a warning about that on startup?

**Comment by doubleplusc** [comment] 2022-05-20 15:43
I don't see any warnings except pnpm. The below image is all I see. Problems, Terminal, and Debug Console don't have any information.

I just cleared everything in my .bashrc except for 3 lines related to setting node and pnpm paths and restarted the system, but it didn't do anything.
![the only thing](https://user-images.githubusercontent.com/5291803/169559716-a9b02509-7ae4-453e-9948-f06b07c4571b.png)

**Comment by 524c** [comment] 2022-05-21 20:31
Hello, here the problem is with eslint. When I try to save any file I get an error. When I run the same command in terminal, everything works fine.
<img width="1097" alt="print1" src="https://user-images.githubusercontent.com/527641/169668071-e705ef8d-e316-40ab-8103-c3c942ec3357.png">

<img width="1099" alt="print2" src="https://user-images.githubusercontent.com/527641/169668078-c7eecdb9-be9c-4c5a-937b-8a5dbb83cf30.png">

**Comment by joaomoreno** [comment] 2022-05-23 07:30
@doubleplusc Can you check the `Log (Main)` output?

![image](https://user-images.githubusercontent.com/22350/169766747-e77cb0ff-74f1-457c-9bfc-ae3e86a525d8.png)

**Comment by devyourcar** [comment] 2022-05-23 08:17
Here's my output:

```
[Info  - 20:16:14] ESLint server is starting
[Info  - 20:16:14] ESLint server running in node v16.13.0
[Info  - 20:16:14] ESLint server is running.
Uncaught exception received.
Error: Command failed: pnpm root -g
    at checkExecSyncError (node:child_process:846:11)
    at execSync (node:child_process:920:15)
    at node:electron/js2c/asar_bundle:5:12704
    at Object.get (/Users/igimanaloto/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:175173)
    at /Users/igimanaloto/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:177223
    at /Users/igimanaloto/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:177238
Uncaught exception received.
Error: Command failed: pnpm root -g
    at checkExecSyncError (node:child_process:846:11)
    at execSync (node:child_process:920:15)
    at node:electron/js2c/asar_bundle:5:12704
    at Object.get (/Users/igimanaloto/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:175173)
    at /Users/igimanaloto/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:177223
    at /Users/igimanaloto/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:177238
```

**Comment by doubleplusc** [comment] 2022-05-23 15:03
> @doubleplusc Can you check the `Log (Main)` output?

@joaomoreno 
I get the same output below whether I am opening from application menu (pnpm fails) or from terminal (pnpm does not fail). These lines are probably not part of the problem.
```
[2022-05-23 07:52:43.480] [main] [info] window#load: attempt to load window (id: 1)
[2022-05-23 07:52:43.539] [main] [info] update#setState idle
[2022-05-23 07:52:43.560] [main] [info] ExtensionHostStarterWorker created
[2022-05-23 07:52:43.566] [main] [error] SyntaxError: Unexpected string in JSON at position 171
    at JSON.parse (<anonymous>)
    at St.afterWindowOpen (/opt/vscodium-bin/resources/app/out/vs/code/electron-main/main.js:75:75767)
[2022-05-23 07:52:44.483] [main] [info] window#load: window reported ready (id: 1)
[2022-05-23 07:52:44.627] [main] [info] Starting extension host with pid 35273 (fork() took 31 ms).
[2022-05-23 07:52:44.627] [main] [info] ExtensionHostStarterWorker.start() took 33 ms.
[2022-05-23 07:53:13.541] [main] [info] update#setState checking for updates
[2022-05-23 07:53:13.600] [main] [info] update#setState idle
```

**Comment by joaomoreno** [comment] 2022-05-24 14:04
@[doubleplusc](https://github.com/doubleplusc) I see you're using VSCodium. Can you reproduce this with VS Code? Or VS Code Insiders? If so, can you please send that output instead?

**Comment by doubleplusc** [comment] 2022-05-24 14:41
> @doubleplusc I see you're using VSCodium. Can you reproduce this with VS Code? Or VS Code Insiders? If so, can you please send that output instead?

@joaomoreno Same output on VSCode. The others in this thread who posted their error messages are using VSCode and VSCode Server, so this is not a distribution-specific problem.

![image](https://user-images.githubusercontent.com/5291803/170061653-a8716dd3-8dd2-43a5-bee9-abe61940047d.png)

**Comment by kelly-tock** [comment] 2022-05-24 20:04
I have a slightly different scenario, but seems related:

```
[Info  - 3:01:42 PM] ESLint server is starting
[Info  - 3:01:42 PM] ESLint server running in node v16.13.2
[Info  - 3:01:42 PM] ESLint server is running.
[Info  - 3:01:43 PM] ESLint library loaded from: /Users/kelly/admin-pnpm/node_modules/.pnpm/eslint@8.16.0/node_modules/eslint/lib/api.js
2022-05-24T20:01:43.838Z eslint:rules Loading rule 'brace-style' (remaining=286)
2022-05-24T20:01:43.843Z eslint:rules Loading rule 'comma-dangle' (remaining=285)
2022-05-24T20:01:43.849Z eslint:rules Loading rule 'dot-notation' (remaining=284)
2022-05-24T20:01:43.853Z eslint:rules Loading rule 'indent' (remaining=283)
2022-05-24T20:01:43.855Z eslint:rules Loading rule 'init-declarations' (remaining=282)
2022-05-24T20:01:43.856Z eslint:rules Loading rule 'keyword-spacing' (remaining=281)
2022-05-24T20:01:43.858Z eslint:rules Loading rule 'lines-between-class-members' (remaining=280)
2022-05-24T20:01:43.870Z eslint:rules Loading rule 'no-dupe-class-members' (remaining=279)
2022-05-24T20:01:43.872Z eslint:rules Loading rule 'no-duplicate-imports' (remaining=278)
2022-05-24T20:01:43.874Z eslint:rules Loading rule 'no-empty-function' (remaining=277)
2022-05-24T20:01:43.877Z eslint:rules Loading rule 'no-extra-parens' (remaining=276)
2022-05-24T20:01:43.880Z eslint:rules Loading rule 'no-extra-semi' (remaining=275)
2022-05-24T20:01:43.899Z eslint:rules Loading rule 'no-invalid-this' (remaining=274)
2022-05-24T20:01:43.901Z eslint:rules Loading rule 'no-loop-func' (remaining=273)
2022-05-24T20:01:43.902Z eslint:rules Loading rule 'no-loss-of-precision' (remaining=272)
2022-05-24T20:01:43.902Z eslint:rules Loading rule 'no-magic-numbers' (remaining=271)
2022-05-24T20:01:43.927Z eslint:rules Loading rule 'no-restricted-imports' (remaining=270)
2022-05-24T20:01:43.961Z eslint:rules Loading rule 'no-unused-expressions' (remaining=269)
2022-05-24T20:01:43.964Z eslint:rules Loading rule 'no-useless-constructor' (remaining=268)
2022-05-24T20:01:43.969Z eslint:rules Loading rule 'object-curly-spacing' (remaining=267)
2022-05-24T20:01:43.993Z eslint:rules Loading rule 'quotes' (remaining=266)
2022-05-24T20:01:44.003Z eslint:rules Loading rule 'semi' (remaining=265)
2022-05-24T20:01:44.006Z eslint:rules Loading rule 'space-before-blocks' (remaining=264)
2022-05-24T20:01:44.007Z eslint:rules Loading rule 'space-infix-ops' (remaining=263)
Uncaught exception received.
Error: Failed to load plugin 'jsx-a11y' declared in '.eslintrc.js » @tock/eslint-config': Cannot find module 'eslint-plugin-jsx-a11y'
Require stack:
- /Users/kelly/admin-pnpm/consumer/__placeholder__.js
Referenced from: /Users/kelly/admin-pnpm/tock-eslint-config/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.resolve (/Users/kelly/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2325:46)
    at ConfigArrayFactory._loadPlugin (/Users/kelly/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3376:33)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/kelly/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3196:29)
    at ConfigArrayFactory._loadExtends (/Users/kelly/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3117:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/kelly/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3058:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/kelly/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3003:20)
    at _normalizeObjectConfigData.next (<anonymous>)
```

pnpm version 7.1.5, installed via `npm i -g`. 


settings.json:

```
 "eslint.runtime": "/Users/kelly/Library/Caches/fnm_multishells/9686_1653421493848/bin/node",
  "eslint.alwaysShowStatus": true,
  "eslint.workingDirectories": [ "./consumer", "./dashboard" ],
  "eslint.packageManager": "pnpm",
```

**Comment by joaomoreno** [comment] 2022-05-25 06:55
@bpasero I can't seem to find the necessary steps to debug a bad user env. Can you give @doubleplusc instructions on how he can debug it further? I'll make sure to add it to my Saved Replies so I don't send these issues to you anymore.

**Comment by doubleplusc** [comment] 2022-05-25 21:13
@joaomoreno If reproducing is a problem, I've uploaded a VM image (3.5GB download, 7.7GB once imported) that can reproduce the error. It's a fresh OS with pnpm installed and the .bashrc cleared except for some path setting lines. user/pass is test/test.

https://drive.google.com/file/d/1LMcQ0qClLVzn__2Dt_pNJMfadCc8OinW/view?usp=sharing

Open EndeavourOS menu on the bottom left -> Development -> Visual Studio Code. asd.js should be opened on launch, and Output will eventually show the error.

![image](https://user-images.githubusercontent.com/5291803/170366349-91894b9e-e69d-4993-9fde-eb99a9758046.png)

**Comment by bpasero** [comment] 2022-05-27 07:01
If you run `code --verbose` we print shell env related messages to the console. Look for `resolveShellEnv` and `getUnixShellEnvironment`.

**Comment by doubleplusc** [comment] 2022-05-28 14:50
I added --verbose into the .desktop file Exec line and added `Terminal=true`.
I have attached the output.

[verbose.log](https://github.com/microsoft/vscode/files/8791327/verbose.log)


These are the lines with `resolveShellEnv`. There are no log lines for `getUnixShellEnvironment`.
```[main 2022-05-28T14:30:27.840Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2022-05-28T14:30:27.995Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2022-05-28T14:30:30.722Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2022-05-28T14:30:31.087Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[2508:0528/103031.675230:INFO:CONSOLE(29)] "%cTRACE color: #888 resolveShellEnv(): skipped (VSCODE_CLI is set)", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
[main 2022-05-28T14:30:57.800Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
```

**Comment by bpasero** [comment] 2022-05-29 05:36
If you run VSCode from a terminal, we do not resolve the shell environment (as indicated by `VSCODE_CLI`). This makes sense because we only need to resolve the shell environment when you run from the dock for example. So I do not think this is related to shell environment resolution at all.

**Comment by joaomoreno** [comment] 2022-06-02 05:55
> So I do not think this is related to shell environment resolution at all.

It is shell environment resolution specific because:

> I have pnpm installed on Linux via `npm install -g pnpm`. pnpm works fine in the vscode integrated terminal and standalone terminals.

And:

> I did what you suggested, I opened a terminal (with working pnpm) and opened VSCode. The extension now works as intended.

---

@doubleplusc Can you try `code --verbose --force-user-env`?

**Comment by doubleplusc** [comment] 2022-06-02 07:01
@joaomoreno Good news! I added `--force-user-env` into my .desktop file, and it worked! ESLint is now running. Thanks for your help.

Is this something that should be fixed in VSCode or the downstream packaging?

**Comment by bpasero** [comment] 2022-06-02 08:09
@doubleplusc to clarify, when you reported the output where `VSCODE_CLI is set`, how do you launch VSCode in that case? From the command line? And if so, anything special about the command line?

**Comment by joaomoreno** [comment] 2022-06-02 15:38
What does `/usr/bin/code` point to? Is it a symlink?

**Comment by doubleplusc** [comment] 2022-06-02 15:45
It's a shell script.
```
#!/bin/bash

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

# Allow users to override command-line options
if [[ -f $XDG_CONFIG_HOME/code-flags.conf ]]; then
   CODE_USER_FLAGS="$(sed 's/#.*//' $XDG_CONFIG_HOME/code-flags.conf | tr '\n' ' ')"
fi

# Launch
exec /opt/visual-studio-code/bin/code $CODE_USER_FLAGS "$@"
```

**Comment by joaomoreno** [comment] 2022-06-08 05:44
If `VSCODE_CLI` perhaps set in your usual user environment?

**Comment by doubleplusc** [comment] 2022-06-08 17:35
I don't see `VSCODE_CLI` in my bash configurations and I've never touched it myself.

The log has only one line with `resolveShellEnv` this time.
```
[main 2022-06-08T17:16:53.219Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
```

**Closed** 2022-06-10 09:59 UTC
Labels: needs more info, workbench-os-integration

**Comment by Gastonite** [comment] 2022-06-12 07:57
Hello, from a fresh installation in Ubuntu 22.04, I'm not able to make eslint extension work anymore.

I've the same problem as @doubleplusc, but when I add the `--force-user-env` flag, nothing changes and the message in output panel is the same:

> Error: Command failed: pnpm root -g
    at checkExecSyncError (node:child_process:835:11)
    at execSync (node:child_process:909:15)
    at node:electron/js2c/asar_bundle:5:12704
    at Object.get (/home/user/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:172258)
    at /home/user/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:174308
    at /home/user/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:174323
Uncaught exception received.

How can I make eslint work again?

**Comment by Gastonite** [comment] 2022-06-12 08:15
Ok, I solved the problem:

I removed the `"eslint.packageManager": "pnpm"`  line from my settings file and voilà

**Comment by ifiknew** [comment] 2022-06-13 08:31
run
```
pnpm root -g
pnpm setup
```
and restart your vscode may solve this

**Comment by RafaelVidaurre** [comment] 2022-06-21 07:43
I am getting this issue too, I had to disable `"eslint.packageManager": "pnpm"` but this causes issues for other team members.

**Comment by hlspablo** [comment] 2022-07-09 13:26
I had the same error, upgrade VSCode to latest version1.69.0 version solved the problem
