### ISSUE TITLE
"Intl.DateTimeFormat().resolvedOptions().locale" returns different values in extension host to VS Code process

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#85675] opened 2019-11-27 09:25 UTC
I'm using MacBook with its system language set to en-GB. I launched VS Code (from the dock, not the terminal) and if I run:

```ts
Intl.DateTimeFormat().resolvedOptions().locale
```

in the Chrome dev tools console, I see this:

<img width="424" alt="Screenshot 2019-11-27 at 9 23 00 am" src="https://user-images.githubusercontent.com/1078012/69710555-860a2600-10f7-11ea-8e1b-ecb629b70b34.png">

However, in an extension's activate function if I do this:

```ts
console.log(Intl.DateTimeFormat().resolvedOptions().locale);
```

Then I see this:

![Screenshot 2019-11-27 at 9 23 44 am](https://user-images.githubusercontent.com/1078012/69710620-a20dc780-10f7-11ea-8239-b931a4829e5a.png)

I need to get the system language in order to set the `LANG` env variable for spawned processes because CocoaPods crashes if `LANG` is not set to something-UTF-8, and there's no way to set it without a language part so I need to get at the system language.

**Comment by alexandrudima** [comment] 2019-12-05 23:56
I don't think we have any code to reset/remove things. @deepak1556 Do you have any ideas?

**Comment by DanTup** [comment] 2019-12-06 08:51
FWIW we've worked around this in Flutter. It still seems weird these don't line up and it might be useful for the extension host to have access to it, but it's not pressing for me anymore. Thanks!

**Comment by deepak1556** [comment] 2019-12-07 04:58
I can confirm this issue,

@alexandrudima here are my observations.

1) Renderer process prints the proper locale
2) Extension host reports incorrect locale
3) Running the Code executable from command line with `export ELECTRON_RUN_AS_NODE=1` set `code -e 'console.log(Intl.DateTimeFormat().resolvedOptions().locale)'` prints the correct locale.

To make things more concrete, v8 and icu are shared between node and electron so behavior being different between these two processes are highly unlikely unless we are intervening.

**Comment by deepak1556** [comment] 2019-12-07 05:47
Okay I have narrowed down the issue, it seems to be a problem with `child_process` module that is messing with the locale. Tried the following sample

```
const { spawn } = require('child_process');
const locale = spawn("/Users/demohan/Downloads/electron-v6.1.5-darwin-x64/Electron.app/Contents/MacOS/Electron", ['-e', 'console.log(Intl.DateTimeFormat().resolvedOptions().locale)'], {env: {
	'ELECTRON_RUN_AS_NODE': 1
}});

locale.stdout.on('data', (data : any) => {
  console.log(`stdout: ${data}`);
});

locale.stderr.on('data', (data : any) => {
  console.error(`stderr: ${data}`);
});
```

prints `en-US` while running on the command line prints the proper system locale used at the moment, in my case `de`

**Comment by rzhao271** [comment] 2021-12-30 17:46
Confirmed the issue still occurs on the latest Insiders on Big Sur.

**Comment by rzhao271** [comment] 2021-12-30 18:21
I copied the code from https://github.com/microsoft/vscode/issues/85675#issuecomment-562817154 to a file `main.js` (with a different Electron spawn path) and did the following:
1. I added a line `console.log(Intl.DateTimeFormat().resolvedOptions().locale)` at the end.
2. In the terminal, I ran `export LANG='fr_CA.UTF-8'`
3. :bug: `node main.js` results in `fr-CA` as the locale, but `en-US` as the spawned locale.
4. I changed the spawn call to spawn `node` directly instead.
5. ✅ `node main.js` results in both locales to be `fr-CA`.

**Comment by rzhao271** [comment] 2021-12-30 18:57
Electron actually reports the locale properly if one changes the `env` parameter above to the following:
```js
{
    ...process.env,
    'ELECTRON_RUN_AS_NODE': 1
}
```

**Comment by rzhao271** [comment] 2022-01-13 19:08
So I first thought the issue was as-designed, and then I thought it was specific to the extension host, but it's actually a more generic upstream issue.
When spawning processes, the child process somehow loses the locale information.

Minimal repro:

main.js
```js
const { app, BrowserWindow } = require('electron');
const cp = require('child_process');

app.whenReady().then(() => {
    console.log(Intl.DateTimeFormat().resolvedOptions().locale);
    const proc = cp.fork(__dirname + '/child.js');
    proc.on('exit', () => app.quit());
})
```

child.js
```
console.log(Intl.DateTimeFormat().resolvedOptions().locale);
```

Output on macOS with the language set to Spanish (Latin America):
```
es-MX
en-US
```

**Comment by rzhao271** [comment] 2022-03-03 17:28
Here's the current situation:

1. The original poster of this issue has already found a workaround (https://github.com/flutter/flutter/pull/45710)
2. I already tried passing in `Intl.DateTimeFormat().resolvedOptions().locale` as the locale to the extension host, but we end up with locales such as `fr` that do not correspond to anything available on the OS, causing a regression in several extensions (https://github.com/microsoft/vscode/issues/142857).
3. Non-web extensions can instead use https://www.npmjs.com/package/os-locale to detect the OS locale. If we use this module ourselves, then the extension host becomes slower to spawn in general, and in the worst case, we might break some extensions again.

Therefore, I'll mark this issue as a wontfix for now.

**Closed by rzhao271** 2022-03-03 17:28 UTC
Labels: bug, upstream, macos, electron, confirmed
