### ISSUE TITLE
">Fold Recursively" function only works partially When there are many paragraphs that can be folded.

### ISSUE THREAD

**Issue by wbfw109** [microsoft/vscode#139744] opened 2021-12-25 14:59 UTC
Does this issue occur when all extensions are disabled?: Yes/No
  Yes

- VS Code Version: 1.64.0-insider
  with no Extension
- OS Version: Windows 11 21H2 (OS Build 22000.376)

Steps to Reproduce:
1. write paragraphs that can be folded with depth level "d".
  in current testing, I set "d" as 19.
2. copy them so that the last line of the file is "x"
  in current testing, I set "x" as 10261.
3.  use ">Fold Recursively" and navigate deeper sequentially, in a paragraph unfolding indent level by one.
  If it's normal, I have to unfold nineteen times.
  but it's not folded after the 10th, so I can see all elements in a paragraph with ten times unfolding.
  also, icon of meaning "foldable" not shows when hover mouse on the left of line numbers. that is, it can not be foldable no longer.

As "x" of second step increases, the base level of non-folding indents decreases.
As "x" of second step decreases, the base level of non-folding indents increases.

  >I repeated steps 1 ~ 3 following conditions:
    - "d" of first step: 19
    - "x" of second step: 19341
  so on third step,  it's not folded after the 6th, 

 > I repeated steps 1 ~ 3 following conditions:
    - "d" of first step: 4
    - "x" of second step: 19341
  so on third step,  it's not folded after the 2th, 

  >I repeated steps 1 ~ 3 following conditions:
    - "d" of first step: 19
    - "x" of second step: 7421
  so on third step,  it's not folded after the 14th, 

please fix it.. :) 

[![IMAGE ALT TEXT]](https://user-images.githubusercontent.com/37881026/147387787-0cdca3d5-9d8e-4456-9ac2-dbb446c5b732.mp4 "[bug] Fold Recursively")

<details markdown="1">
<summary>updated history</summary>
2021/12/26
  write additional information to third step
</details>

**Comment by aeschli** [comment] 2022-01-02 19:00
There's a maximum of folding regions that can be in a file. That number is currently 5000. That's done for performance reasons.

All regions above 5000 are filtered. The innermost regions are filtered first. That's what you are seeing.

**Comment by wbfw109** [comment] 2022-01-02 22:23
> There's a maximum of folding regions that can be in a file. That number is currently 5000. That's done for performance reasons.
> 
> All regions above 5000 are filtered. The innermost regions are filtered first. That's what you are seeing.

It's so reasonable.
but I'm using the file to take notes instead of other note application.
When it combined with bookmarks and "> fold/unfold Recursively" function, I think VS code could be very strong tool.
I'm also currently using it like that.

So, can you please tell me how to turn off the limit for a specific file?
If not, can you create a new feature?

I'm pretty desperate. This approach can be combined with other extensions and built-in function as well as being able to use emojis, so in my experience so far, I think it will be an incomparable good note-taking tool.

**Comment by PieterBranderhorst** [comment] 2022-01-03 00:44
I agree. I'd like to see that limit configurable too.' I would also prefer that when vscode encounters the limit it:

- Shows the user a warning.
- Stops folding at the point in the file where it reaches the limit.
The current approach is smart. It recursively drops the deepest layer of folding until the number of fold regions is under the limit. But this might not work out well for the user. What if there's a very large log file with just one or two layers of folding? Almost all of the folding regions could disappear with the current approach. I'd rather it just went as far as it can in the source and then stop.

Martin, what do you think of doing the following:

1. Change the default limit to 10,000.
2. Rework some of the code so that it performs at least as well at 10,000 regions as it currently does at 5,000.
3. Make the limit a configuration parameter. With a warning note that increasing it might result in janky performance.
4. When the limit is reached, discard folds from that point to the end of the source.
5. Display a warning when a file exceeds the limit on the number of fold regions.

If you like I could propose code for the above. I guess that depends on what you think of what I submitted already for hidden region tracking :)

**Comment by aeschli** [comment] 2022-01-03 09:40
Yes, I like the suggestion to make this configurable. And a notification would be good too.
If you want to look into that that would be great. After that e can look into improving the performance (I haven't yet looked in detail at the other PR)

**Comment by aeschli** [comment] 2022-01-03 09:41
We already have https://github.com/microsoft/vscode/issues/72994 to make the folding limit configurable. I marke this as duplicate of that one. As said, help is very welcome!

**Closed by aeschli** 2022-01-03 09:41 UTC

**Comment by PieterBranderhorst** [comment] 2022-01-09 01:15
Martin, I've added code for configurable folding limit and a notification when limit is exceeded to the existing PR for keeping collapsed regions, i.e. to [#139779](https://github.com/microsoft/vscode/pull/139779)
