### ISSUE TITLE
`titleBarStyle=custom` breaks Alt+ Keyboard shortcuts

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#54005] opened 2018-07-11 01:42 UTC
- VSCode Version: 1.25.0
- OS Version: Win10ProX64

`"window.titleBarStyle": "custom"` prevents you from assigning any of the <kbd>Alt+X</kbd> keyboard shortcuts where <kbd>X</kbd> is a keyboard shortcut for one of the file menus - F, E, S, V, G, D, T, H

Steps to Reproduce:

1. Enable `"window.titleBarStyle": "custom"`

2. Create a keyboard shortcut with the keybinding as <kbd>Alt+E</kbd>

Expected: <kbd>Alt+E</kbd> should carry out the command. 

Actual: The `Edit` menu pops up

Does this issue occur when all extensions are disabled?: Yes

**Comment by laggingreflex** [comment] 2018-07-11 01:49
Not a dupe of #53100 since there it seems OP was using <kbd>Alt+Shift</kbd> which seems to work.. although only if you manually set `alt+shift+` in `keybindings.json`. 

If you try to do it from `Preferences > Keyboard Shortcuts` tab you can't assign the shortcut <kbd>Alt+Shift+F</kbd> -- the File menu pops up.

**Comment by sbatten** [comment] 2018-07-11 17:10
duplicate of #53654

**Closed by sbatten** 2018-07-11 17:10 UTC
