### ISSUE TITLE
`test.runTests` does not take effect

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#125712] opened 2021-06-08 02:25 UTC
Version: 1.57.0-insider (user setup)
Commit: bf84ee619e0b67443d0307c04348fa575bc3c363
Date: 2021-06-07T12:46:22.208Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Hi @connor4312, 

It seems that `test.runTests()` does not take effect. Does that mean this API is not aiming to finalize for the first stable iteration?

In Java we have existing features that user can trigger tests from other view(e.g. Java Project explorer). I guess this API is for such purpose?

Or can we directly use `test.createTestRun(request)` to achieve that? If yes, how to get the cancellation token?

**Comment by connor4312** [comment] 2021-06-09 17:44
Yea, my logic for not finalizing it was that it would mostly be called by other extensions. But it's reasonable to want to call it yourself, I'll fix it up and move it for finalization.

**Comment by connor4312** [comment] 2021-06-09 19:01
I don't reproduce this issue: https://memes.peet.io/img/21-06-e8b99a9a-a862-4dfb-92b4-a057b9ed18eb.mp4

Can you add instructions?

**Comment by jdneo** [comment] 2021-06-10 02:03
Is it because the test item passed to this API must be the item in the test explorer?

Use the following code can repro the issue:

```ts
vscode.commands.registerCommand('test-provider-sample.runTests', async tests => {
      const root = WorkspaceTestRoot.create(vscode.workspace.workspaceFolders![0]);
      await vscode.test.runTests({ tests: [root], debug: false });
      vscode.window.showInformationMessage('Test run complete');
})
```

#### More background

In Java we have a explorer called `Java Project` explorer which provides the `package view` similar to other Java IDEs.

Meanwhile, there are some 'shortcut' commands registered to that view, like `run tests`

![image](https://user-images.githubusercontent.com/6193897/121452889-0ea48c00-c955-11eb-870f-ad7cda1d033e.png)

my original attempt is trying to create a new test item for the node in `Java Project` explorer then pass it to `test.runTests()`

**Comment by connor4312** [comment] 2021-06-10 02:16
Ah, I see. Currently this works only for tests that are "attached" to an existing item, returned from the TestController, and this probably won't change. There are some reasons for this:

- Given a free-floating TestItem, we don't know what Controller it's associated with. If your extension registered multiple TestControllers, we'd have no idea which one to invoke.
- `runTests` can be called from any extension. We guarantee to the `TestController` that we will only ask it to run tests that it created, which allows it to depend on the custom `data` in the test. Other extensions may not fulfill this contract. Even barring that, we don't require `data` to be serializable since it's never transferred to other extension hosts, but that would have to change to make this work.

However, I realize that there's an additional difficulty for you in this scenario: the test items are requested in a "pull" model from VS Code. If it happens that someone is using your project explorer but never opened the Test Explorer or any documents, it's impossible for you to provide a test item. I'll have to think about how to fix this. Suggestions welcome as well.

**Comment by jdneo** [comment] 2021-06-10 03:00
Just an idea come up in my mind: make test request has an optional field that can associate with the test controller(s), like a id or something?

**Comment by connor4312** [comment] 2021-06-10 15:54
I think having an option for making test runs cancellable would work. The _runs_ don't actually require "attached" test items, so you could just create a run manually and do what you need with it, and cancellation provides the necessary control for users.

**Comment by jdneo** [comment] 2021-06-11 01:55
> I think having an option for making test runs cancellable would work. The runs don't actually require "attached" test items, so you could just create a run manually and do what you need with it, and cancellation provides the necessary control for users.

Sounds good. Does that mean the cancellation token will be provided when calling `test.createTestRun`?

**Comment by connor4312** [comment] 2021-06-14 23:45
There's now a cancellation `token` on the TestRun object.

**Closed** 2021-06-14 23:46 UTC
Labels: api, testing
