### ISSUE TITLE
Scroll bar looks broken in intelli-sense documentation widget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2271] opened 2016-01-26 08:56 UTC
This is linux, though it is prolly everywhere 

![screen shot 2016-01-26 at 09 55 19](https://cloud.githubusercontent.com/assets/1926584/12576299/fe16dc1e-c412-11e5-8b4b-327400e1f74f.png)

**Comment by joaomoreno** [comment] 2016-01-26 09:00
Duplicate of #1928

**Closed by joaomoreno** 2016-01-26 09:00 UTC
Labels: bug
