### ISSUE TITLE
Git merge conflicts not showing

### ISSUE THREAD

**Issue by souvikbiswas1998** [microsoft/vscode#112713] opened 2020-12-17 08:24 UTC
Issue Type: **### Bug**

SCM panel not showing the conflict files.

**Comment by AlphaJuliettOmega** [comment] 2020-12-18 06:48
@souvikbiswas1998 can you give more symptom information?

Yesterday when I had to merge, when I clicked on the blue highlight 'merge conflict' files, it wouldn't open them, but because they're highlighted I could switch from Source Control tab to Project Files tab, and could then select the file from there.

Files that were irregular (I had 10 png's and 8 ttf fonts) didn't want to open at all until the merge was complete. 
My merge was a Folder rename.

My side it could be to do with the bug of VS Code not letting go of files after closing, but that doesn't explain Merge Conflict files not being open-able.

**Comment by zhengyn0001** [comment] 2020-12-21 10:00
![image](https://user-images.githubusercontent.com/51322469/102764434-188dff00-43b6-11eb-8d76-fe7e684390b2.png)
I merged the code,and the screen showed that has merge conflicts,but i can't see any conflicts message
![image](https://user-images.githubusercontent.com/51322469/102764658-71f62e00-43b6-11eb-85e6-d355f6603aee.png)

**Comment by zhengyn0001** [comment] 2020-12-21 10:01
mainThreadExtensionService.ts:65 [[object Object]]Should never happen
$onExtensionRuntimeError @ mainThreadExtensionService.ts:57
_doInvokeHandler @ rpcProtocol.ts:396
_invokeHandler @ rpcProtocol.ts:330
_receiveRequest @ rpcProtocol.ts:269
_receiveOneMessage @ rpcProtocol.ts:208
(anonymous) @ rpcProtocol.ts:90
fire @ event.ts:525
fire @ ipc.net.ts:449
_receiveMessage @ ipc.net.ts:785
(anonymous) @ ipc.net.ts:642
fire @ event.ts:525
acceptChunk @ ipc.net.ts:191
(anonymous) @ ipc.net.ts:191
t @ ipc.net.ts:925
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
mainThreadExtensionService.ts:66 Error: Should never happen
	at D.getRightResource (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1)
	at D.getResources (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1)
	at C.get resources (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1)
	at C.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1)
	at C.get leftUri [as leftUri] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1)
	at D.resolveChangeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1)
	at D.resolveDefaultCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1)
	at C.get command [as command] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:824
	at Array.map (<anonymous>)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:824
	at Array.map (<anonymous>)
	at w._takeResourceStateSnapshot (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:824)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:828
	at Set.forEach (<anonymous>)
	at y.eventuallyUpdateResourceStates (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:828)
	at Timeout._onTimeout (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:8)
	at listOnTimeout (internal/timers.js:531)
	at processTimers (internal/timers.js:475)

**Comment by infinnie** [comment] 2020-12-22 03:44
Solution here.
https://github.com/microsoft/vscode/issues/112717#issuecomment-749321371

**Comment by infinnie** [comment] 2020-12-22 08:43
The `should never happen` error, as displayed in the screenshot, comes from

https://github.com/microsoft/vscode/blame/0c947cb4ee4a35f04aa6c5117a9727be35b3c828/extensions/git/src/repository.ts#L680

Even though we’re only trying to access the `leftUri` in a rename/delete conflict, the `getRightResource()` method is nevertheless called, which throws the error.

**Comment by eamodio** [comment] 2021-01-05 06:10
Duplicate of #112537 (which will be fixed in tomorrow's insiders)

**Closed by eamodio** 2021-01-05 06:10 UTC

**Comment by AlphaJuliettOmega** [comment] 2021-01-05 08:43
@eamodio that's epic, thanks for cleaning up.
