### ISSUE TITLE
Laptop's touchpad scroll doesn't smooth

### ISSUE THREAD

**Issue by flawless0714** [Microsoft/vscode#38679] opened 2017-11-18 11:59 UTC
- VSCode Version: 1.18.1
- OS Version: Win10 1709

Problem:
when you scrolling with laptop's touchpad, it just doesn't smooth,
but it was smoothly in other software like chrome.

Regards.

Reproduces without extensions: Yes/No

**Comment by Talljoe** [comment] 2017-11-18 19:44
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.15063
- Hardware: Lenovo Yoga 910
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-instant-markdown|dba|1.3.0
solidity|Jua|0.0.31
cpptools|ms-|0.14.2
vetur|oct|0.11.3
node-tdd|pra|0.2.4

(11 theme extensions excluded)


---

Steps to Reproduce:

1. Open a file (larger than one screen)
2. Scroll down with touchpad
3. Scroll up with touchpad

Expected Results:
Should scroll smoothly

Actual Results:
Scrolling halts for a second or two. Basically anytime you stop scrolling you can't immediately scroll again.

Dragging the scroll bar does _not_ reproduce the problem.


Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-11-19 00:16
/duplicate of https://github.com/Microsoft/vscode/issues/35191

**Closed by roblourens** 2017-11-19 00:16 UTC
Labels: *duplicate, editor, new release
