### ISSUE TITLE
Pattern / wildcards support for fileNames for custom file icons

### ISSUE THREAD

**Issue by marlongerson** [microsoft/vscode#114605] opened 2021-01-20 02:06 UTC
From https://code.visualstudio.com/api/extension-guides/file-icon-theme

> fileNames associates file names to icons. The key in the set is the full file name, not including any path segments. **Patterns or wildcards are not supported.** File name matching is case insensitive. A 'fileName' match is the strongest match, and the icon associated to the file name will be preferred over an icon of a matching fileExtension and also of a matching language Id.

It would be nice if patterns and wildcards were supported. For example, I have `.env` associated with some svg icon. I can hard code `.env.local`, `.env.development`, `.env.staging`, `.env.production` to use the same icon, but what if someone has a file `.env.somethingelse`? It should have the same icon. Currently, vscode will give it the default icon under `files` property.

Therefore it would be a nice feature to have patterns such as `.env.*`.

```
{
    "iconDefinitions": {
        "_env": "./icons/env-icon.svg"
    },
    "fileNames": {
        ".env.*": "_env"
    }
}
````

**Comment by aeschli** [comment] 2021-01-21 15:30
duplicate of https://github.com/microsoft/vscode/issues/12493

**Closed by aeschli** 2021-01-21 15:30 UTC
