### ISSUE TITLE
1.52 reintroduced bug on Big Sur terminal slow

### ISSUE THREAD

**Issue by jvanderaa** [microsoft/vscode#112361] opened 2020-12-12 14:21 UTC
- VSCode Version: 1.52
- OS Version: Big Sur 11.0.1

Steps to Reproduce:

1. Rebooted VSCode, auto updated to 1.52
2. Use the terminal, response time is slow

This may be the same as #105446, not sure if the update is intended to re-introduce slowness. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by nomo-nomad** [comment] 2020-12-12 14:26
I'm experiencing this issue as well

**Comment by ertankara** [comment] 2020-12-12 17:31
Same issue, also slower transition between editor and the terminal

**Comment by ertankara** [comment] 2020-12-12 17:36
Applied previous solution for myself and it solved again. The new updated must have revoked it maybe

https://github.com/microsoft/vscode/issues/107103#issuecomment-731664821

Executing the following fixes lag but not really sure if it is a safe way. Better than lagging 24 / 7

`codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`

**Comment by meganrogge** [comment] 2020-12-14 16:59
Duplicate of #105446

**Closed by meganrogge** 2020-12-14 16:59 UTC

**Comment by jvanderaa** [comment] 2020-12-15 14:47
@meganrogge -> So the latest update of VS Code was intended to re-introduce #105446? I had the fix applied that was recommended in the thread. Then the update happened for VS Code. I had to re-apply the fix again.

**Comment by deepak1556** [comment] 2020-12-15 18:48
Updating vscode will replace the binaries, so if you had removed the codesign previously they will not be preserved during updates.

**Comment by ivands** [comment] 2020-12-22 11:08
If this is just a temporary fix, will there be a permanent one?

**Comment by joostshao** [comment] 2020-12-28 03:48
Same issue

**Comment by deepak1556** [comment] 2021-01-04 21:22
Please follow https://github.com/microsoft/vscode/issues/105446 for updates on the fix.
