### ISSUE TITLE
Incorrect highlight after ctrl + click in vscode.dev

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#186760] opened 2023-06-30 16:34 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.79.2

- OS Version: Windows 11

Steps to Reproduce:

1. Reviewing a pr in github.dev by clicking . in the github repo
2. Trying to go to the imported file by clicking Ctrl + click but it does not put underline under whole word

https://github.com/microsoft/vscode/assets/50770619/9986e6a3-3ffa-4169-99a9-f2dd6aeb5c61

**Comment by abhijit-chikane** [comment] 2023-06-30 16:45
sorry this is in github.dev and not in vscode.dev
Don't know if it is different or same
May be you can close this if not the same :)

**Comment by mjbvz** [comment] 2023-07-10 21:36
Duplicate of #172314

**Closed by mjbvz** 2023-07-10 21:36 UTC
