### ISSUE TITLE
Multi-line caret affects wrapped lines

### ISSUE THREAD

**Issue by linvain** [Microsoft/vscode#61132] opened 2018-10-17 11:23 UTC
- VSCode Version: Last Insiders
- OS Version: Win 10

Steps to Reproduce:
(Say you want to indent html code)

1. Make long lines wrap: `Editor: Word Wrap`
2. Use `Ctrl + Alt + Up` / `Ctrl + Alt + Down` to make caret multi-line (covering wrapped lines)
3. Try to indent: `Tab`
4. The indentation appears where the lines wrap (in the middle of the text in `p` tags)
5. This is not desired behavior

Does this issue occur when all extensions are disabled?: Yes

**Comment by linvain** [comment] 2018-10-17 11:34
The third issue (#41152) is related to this one.
I think `Ctrl + Alt + Up` / `Ctrl + Alt + Down` commands should skip wrapped pseudo-lines (the ones without number) if the initial caret wasn't placed on such pseudo-line.

**Comment by alexandrudima** [comment] 2018-10-24 07:32
Duplicate of #26393

**Closed by alexandrudima** 2018-10-24 07:32 UTC
Labels: editor-multicursor
