### ISSUE TITLE
mixin less error

### ISSUE THREAD

**Issue by linedotwww** [Microsoft/vscode#8150] opened 2016-06-26 07:51 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. create mixin in less file
I enter with no parameters, all is well
![2016-06-26_10-44-08](https://cloud.githubusercontent.com/assets/15665678/16361086/9c880464-3b8b-11e6-9eb9-8b6ba9b72791.png)

2. and here is errors
![2016-06-26_10-50-15](https://cloud.githubusercontent.com/assets/15665678/16361101/f9169f42-3b8b-11e6-9dda-4abeade7a945.png)

**Comment by mrmlnc** [comment] 2016-06-26 09:16
This is a historical problem #1778 :)

**Comment by aeschli** [comment] 2016-07-20 14:48
duplicate of  #1778

**Closed by aeschli** 2016-07-20 14:48 UTC
Labels: css-less-sass
