### ISSUE TITLE
Add ability to add a custom CSS

### ISSUE THREAD

**Issue by yhojann-cl** [microsoft/vscode#221502] opened 2024-07-11 19:18 UTC
I understand that there is a plugin to add custom css and js to the editor, the problem is that this plugin does not always work well and when trying to enable it from flatpak it tries to add files that are not native and cause conflicts when restarting or updating the editor.

I would like to apply some customizations such as changing the font size of the file tree and the tabs, for example, since Ubuntu 24.04 text editors like gedit and the new gtk components tend to use larger fonts, this is especially in My case because I use a 4K monitor with 200% zoom and most of the apps look very comfortable, except for visual studio code that maintains small typography that breaks the harmony of the rest of the system. I understand that visual studio does not want to adapt to the styles of each system since I support the idea that it is agnostic and that is why it uses themes, but in very special cases like mine and in some cases like in mac retina we need to make some minor adjustments :

![Screenshot from 2024-07-11 15-19-21](https://github.com/microsoft/vscode/assets/2144779/661cb85a-6202-440d-867d-24256449ef91)

The problem is that these minor adjustments cannot be made from `settings.json`, if it is possible to customize the code editor but not the interface, it is possible to change the colors of the interface but not the typography.

To avoid having to add new features to the `settings.json` and wait for the releases to release these features little by little, it would be a good idea for each user to be able to make their own customizations to the editor, understanding that it is an open source solution, it would be good to maintain These customizations are separate from each update since in my case I could add these modifications to the code and compile but I would also have to apply all the changes from the visual studio code releases.

That's why I think it would be a good idea for the possibility of customizing the interface with CSS code to be native and not part of an external plugin, for example, creating a default CSS base file and for the user to modify it as desired, just like as is done with settings.css, it could be called `user.css`.

**Comment by aeschli** [comment] 2024-07-12 08:26
See my comment on https://github.com/microsoft/vscode/issues/168856#issuecomment-1346662409

If you change the zoom level of VS Code, is that not good enough?

**Comment by aeschli** [comment] 2024-07-12 08:27
Closing as duplicate of https://github.com/microsoft/vscode/issues/459

**Closed by aeschli** 2024-07-12 08:27 UTC

**Comment by yhojann-cl** [comment] 2024-07-20 21:51
About your response:

> Sorry, a user style sheet goes against a design philosophy of VS Code. A user style sheet would work against a DOM structure and class names that is not documented and we consider internal. To evolve, refactor or improve VS Code, we need the freedom to make changes to the UI. Each change would break user style sheets. This would result in frustration with user style sheet providers and a bad user experience: User style sheets that are half broken, resulting in potentially strange UI glitches that are hard to debug on our side.
> Instead, we aim to a well-designed extension API. This one is documented, comes with tooling and samples, and is kept stable across all upcoming releases of VS Code.

I think that your response is not enough to cancel an idea or close a ticket, unfortunately the referenced ticket that you have marked as duplicate does not accept more responses.

> Sorry, a user style sheet goes against a design philosophy of VS Code.

This is completely understandable.

> A user style sheet would work against a DOM structure and class names that is not documented and we consider internal. To evolve, refactor or improve VS Code, we need the freedom to make changes to the UI. Each change would break user style sheets. This would result in frustration with user style sheet providers and a bad user experience: User style sheets that are half broken, resulting in potentially strange UI glitches that are hard to debug on our side.

It is not a good excuse, developers can continue working with the default layout of Visual Studio Code and skip the internal support and debugging for custom style sheets, for example, if someone wants to use large texts because they have problems with the view, it is understandable. , if the texts go outside of each component it is a problem of the user who made the style sheet, you should not have any responsibility for personal modifications.

> Instead, we aim to a well-designed extension API. This one is documented, comes with tooling and samples, and is kept stable across all upcoming releases of VS Code.

I'm sorry, but there is no API that can help me improve the sizes of the controls and texts and there is no future work on it, apparently the API is complete in some aspects but deficient in others, the architectural design in the use of apis and configurations has many deficiencies, such as the need to include space names as text in properties instead of using an object tree, among other things. Your message saying that "we are working on it" sounds like a cheap excuse to me that will never arrive. Will I have to use extensions to be able to change the design?

I think that the development of Visual Studio Code has not lived up to what Atom Editor was, it is true that it has created many improvements, but it has ruined others, Microsoft has always been at the tail end of innovation and has always fought against of developers throughout history (the failure of Windows Mobile Store along with Lumia and Windows Store affirms this), Atom provided multiple customization channels so that creating software was as per the needs of the individual layer, I understand that this is not the philosophy of Visual Studio, but rather "work with what we give you and if you don't like it, look for another one", that would have been fine if they hadn't discontinued Atom, but instead of creating a good fork they eliminated a completely different editor with a different philosophy that provided us with different tools, for this reason I feel that if Microsoft wanted to replace Atom editor with Visual Studio Code, I feel I have the right to make comparisons and talk about both and talk about what they have eliminated in a completely unnecessary way.
