### ISSUE TITLE
Suggestion: Add option for Beautify / Format on Save

### ISSUE THREAD

**Issue by jayrosen1576** [Microsoft/vscode#3588] opened 2016-03-01 15:51 UTC
The beautifier works great as text is edited or if "editor.action.format" is initiated however for simplicity and efficiency, an option to automatically invoke the formatting on save would be a great addition.

**Comment by isidorn** [comment] 2016-03-01 21:52
There is already an option for that, open your user preferences and add
```
	"editor.formatOnType": true
```

**Comment by jayrosen1576** [comment] 2016-03-02 12:27
format on type is not the same as format on save. why was this closed? the feature request was to have the formatter run on the full document when it is saved regardless of whether it was edited.

**Comment by isidorn** [comment] 2016-03-02 13:53
My mistake, reopening

**Comment by mrmlnc** [comment] 2016-08-09 17:32
@alexandrudima, hello,

My question relates to this issue, so I'll ask it here.

Some users of my extension want to be able to format code when saving. For example **vscode-csscomb**, **vscode-autoprefixer**, **vscode-postcss-sorting** or **vscode-stylefmt**. And rightly so, because it's so much easier.

The problem is that VS Code does not provide an API for this. Almost all extensions now use the following method:

```js
function activate(context) {
    // ...
    const onSave = vscode.workspace.onDidSaveTextDocument((document) => {
        const onDidSave = vscode.workspace.getConfiguration('csscomb').autoFormatOnSave;
        if (onDidSave) {
            init(document, true);  // True - notifies that the required auto-save
        }
    });

    context.subscriptions.push(onSave);
}
```

The document goes in a cycle of saving and to break the cycle, you want to add a flag to the `document`. In the `init` function, the following occurs:

```js
function init(document, onDidSaveStatus) {
    // Code ...

    // Out of the loop
    if (document.csscomb) {
        delete document.csscomb;
        return;
    }

    if (onDidSaveStatus) {
        const we = new vscode.WorkspaceEdit();
        we.replace(document.uri, range, combedStyles);

        // Flag for exit
        document.csscomb = true;

        vscode.workspace.applyEdit(we).then(() => {
            document.save();
        });
    } else {
        editor.edit((builder) => {
            builder.replace(range, combedStyles);
        });
    }
}
```

For example, this method used by [vscode-go](https://github.com/Microsoft/vscode-go/blob/master/src/goMain.ts#L177-L212). And they too do not like the current situation.

Maybe you advise a solution? :panda_face:

**Comment by jrieken** [comment] 2016-08-12 08:41
I'd say this related or even a dupe of #239

**Comment by bpasero** [comment] 2016-09-28 17:26
This is coming for September.

**Closed by bpasero** 2016-09-28 17:26 UTC
Labels: api, feature-request, workbench
