### ISSUE TITLE
"Open With Code" fails when Code.exe is running as administrator

### ISSUE THREAD

**Issue by aajackson** [microsoft/vscode#86968] opened 2019-12-14 01:06 UTC
Issue Type: <b>Bug</b>

Run Code.exe as administrator
From an Explorer window, right click a file and choose the "Open with Code" option from the context menu.
Observe no file opened.
Expected result: file opened in currently running Code.exe process.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by nikonso** [comment] 2020-07-22 13:38
Any news or updates on this issue?

The environment in which I'm coding makes me have to run code as an admin so I'm hitting this issue pretty hard.

Also is not just the context menu that doesn't work, trying to open a file that is associated with code also fails silently, so this is a very serious issue, that affects VS CODE usage severely when needing to run one instance of it as an admin. As you can only start new instances from code and not from any interaction with the explorer..

Are there any workarounds available?

**Comment by bpasero** [comment] 2020-11-17 07:31
Duplicate of https://github.com/microsoft/vscode/issues/6560

**Closed** 2020-11-23 07:24 UTC
Labels: bug, windows, workbench-os-integration
