### ISSUE TITLE
Flaky test: Terminal sendText immediately after createTerminal should not throw

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#91263] opened 2020-02-24 08:33 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=68166&view=logs&j=935a53e5-ce00-51d1-185d-b2f737723cea&t=78251e6f-ceae-58b8-b69e-6d3a7d24b6bc

This just broke the integration tests on Windows 32bit.

**Comment by joaomoreno** [comment] 2020-06-21 18:20
@Tyriar Is this still an issue?

**Comment by meganrogge** [comment] 2021-02-04 18:18
Duplicate of #92826

**Closed** 2021-02-04 18:19 UTC
Labels: *duplicate, bug, integrated-terminal, integration-test-failure
