### ISSUE TITLE
bundle  the intergrated terminal from vscode to another app

### ISSUE THREAD

**Issue by apawn** [microsoft/vscode#121619] opened 2021-04-19 07:10 UTC
Hi

i found that the integrated  terminal is more fluent than both windows cmd and windows terminal Preview.

is there a plan to bundle the terminal to another app, like "VscodeTerminal" ?

i don't mean  to change the vscode, just want to have an another separated terminal app.

Thanks

**Comment by yume-chan** [comment] 2021-04-20 08:15
Duplicate of #34442

**Comment by meganrogge** [comment] 2021-04-22 20:22
Duplicate of #34442

**Closed** 2021-04-22 20:23 UTC
Labels: *duplicate
