### ISSUE TITLE
Windows Store Release?

### ISSUE THREAD

**Issue by itshaydendev** [microsoft/vscode#88709] opened 2020-01-15 20:29 UTC
There are several issues similar to this. Like #19887, #30577 and #40195.

However, I was wondering. Now that the Microsoft store is slowly letting more and more non-UWP apps in (like Python, Notepad++, etc.), does it not make sense to re-open this question? 2020 could be the year of 5-click VSCode install. Open MS store -> search for VS Code -> Click VS Code, -> Click "Get" -> Open it.

Just wondered if this was any closer to being able to be done.

**Comment by mjbvz** [comment] 2020-01-15 20:59
Duplicate of #10759

**Closed by mjbvz** 2020-01-15 20:59 UTC
