### ISSUE TITLE
Intelliphense can't identify some classes in laravel.

### ISSUE THREAD

**Issue by umersheikh1** [microsoft/vscode#86579] opened 2019-12-09 09:38 UTC
Issue Type: <b>Bug</b>

intelliphense is giving errors for my valid Laravel's Route syntax and other Classes.

E.g.

Undefined symbol Route

in web.php on following line

Route::get('/', '\Corals\Foundation\Http\Controllers\PublicBaseController@welcome');

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.64GB free)|
|Process Argv|E:\DynamoLogic\repo\website|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
vscode-phpstorm-formatter|ani|0.0.3
vscode-intelephense-client|bme|1.3.2
gitignore|cod|0.6.0
laravel-goto-view|cod|1.3.2
git-extension-pack|don|0.1.3
githistory|don|0.4.11
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
pdf|fri|0.0.6
gc-excelviewer|Gra|2.1.32
vscode-position|jtr|1.0.1
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.1293
vscode-angularjs-snippet|Nic|0.0.3
indent-rainbow|ode|7.4.0
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.7.0
laravel-artisan|rya|0.0.27
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by whizsid** [comment] 2019-12-09 10:33
This issue is duplicate of https://github.com/bmewburn/vscode-intelephense/issues/775

**Closed** 2019-12-09 16:01 UTC
Labels: *caused-by-extension, integrated-terminal
