### ISSUE TITLE
Start slowly, lost frame

### ISSUE THREAD

**Issue by lynx-seu** [Microsoft/vscode#32860] opened 2017-08-21 02:06 UTC
- VSCode Version: <code>Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)</code>
- OS Version: <code>Windows_NT x64 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)</code>
- Memory (System): <code>7.34GB (3.65GB free)</code>
- Memory (Process): <code>231.82MB working set (231.93MB peak, 180.78MB private, 65.69MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>50%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|30|
|main|app.isReady => window.loadUrl()|14291|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|10141|
|renderer|require(workbench.main.js)|617|
|renderer|create extension host => extensions onReady()|1144|
|renderer|restore viewlet|441|
|renderer|restore editor view state|863|
|renderer|overall workbench load|1442|
|main + renderer|start => extensions ready|26335|
|main + renderer|start => workbench ready|26551|

---

Additional Steps to Reproduce (if any):

1.When start the Tool ,it needs about 10+ seconds , note: my cpu core version is I5 7th
2.Some times , the tool stop for seconds ,you can do nothing with it , then it turns ok.

**Comment by jrieken** [comment] 2017-08-21 07:34
@lynx-seu Please start VS Code from the command line like this: `vscode --prof-startup`. It will attach a CPU provider during startup. Please attach the profile files here. Thanks

**Comment by lynx-seu** [comment] 2017-08-23 03:28
@jrieken Thanks for your reply, please refer the attach


[675c_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1244049/675c_main.cpuprofile.txt)
[675c_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1244050/675c_renderer.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-08-23 07:02
Thanks, by looking at the profiles we can identify #24884 and https://github.com/Microsoft/vscode/issues/17108. Closing as dupe of those


@joaomoreno please stop spawning the machine id process on startup

<img width="630" alt="screen shot 2017-08-23 at 09 01 56" src="https://user-images.githubusercontent.com/1794099/29602762-d05b06da-87e1-11e7-8b91-1d1ff4b2398e.png">

**Closed by jrieken** 2017-08-23 07:02 UTC
Labels: new release, perf-profile
