### ISSUE TITLE
Horizontal Scroll Wheel Not Working

### ISSUE THREAD

**Issue by waldronmatt** [microsoft/vscode#150068] opened 2022-05-21 00:43 UTC
Issue Type: <b>Bug</b>

Using the horizontal scroll wheel on the Gameball trackball mouse doesn't horizontally scroll, but does when I press ctrl key at the same time. Currently using Windows 11. However, using the same settings on Windows 10 PC, the horizontal scroll wheel works without issue.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (7.95GB free)|
|Process Argv|--crash-reporter-id 316d8cb0-3bac-4a24-9bd1-52c9eceb07f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
lit-plugin|run|1.2.4
vscode-stylelint|sty|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549

```

</details>

**Comment by alexdima** [comment] 2022-10-22 17:07
Duplicate of #84136

**Closed by alexdima** 2022-10-22 17:07 UTC
Labels: upstream
