### ISSUE TITLE
The editor adds automatically a wrong space character at the beginning of every new line in a .js file containing a tab inside comments

### ISSUE THREAD

**Issue by kripper** [microsoft/vscode#211079] opened 2024-04-23 10:57 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Create a new .js file
2. Type the code of the image and make sure to **press the TAB key** before typing "test".
3. Make sure to press ENTER twice after ending the comment
4. Notice the space character added automatically by the editor starting line 5.

![image](https://github.com/microsoft/vscode/assets/1479804/9f593276-3ee4-4fbf-adcd-a0a06d1f0a4c)

**Comment by mjbvz** [comment] 2024-06-26 23:47
Duplicate of #121004 I believe

Seems fixed in the latest VS Code insiders

**Closed by mjbvz** 2024-06-26 23:47 UTC
