### ISSUE TITLE
attaching a custom keyword  to a specific command to retrieve it more easily in the command palette

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode#80769] opened 2019-09-12 05:22 UTC
Sometime the keyword needed to find a specific command is badly chosen and difficult to remember.  
So it will be great if we could attach a custom keyword to a specific command (or to change it's name) to find it more easily in the command palette.

**Comment by usernamehw** [comment] 2019-09-12 05:25
Duplicate of #50836

**Closed** 2019-09-12 07:24 UTC
