### ISSUE TITLE
[Debug] Wrong launch configuration is selected when trying to launch a compound configuration when launch.json become opened in editor

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#19677] opened 2017-02-01 15:56 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 8.1 x64

Wrong launch configuration is selected for debugging when trying to launch a compound configuration if `launch.json` become opened in the editor. VS Code often opens `launch.json` automatically after starting a compound configuration (have never seen the same for a regular, not compound configuration). But in some cases it doesn't open, and when it doesn't the correct configuration is selected. But when `launch.json` becomes open, the wrong configuration is selected and an info message bubbles up:
> Please set up the launch configuration file for your application.

Right before the start of `multi` configuration:

![untitled](https://cloud.githubusercontent.com/assets/4777512/22514304/f37f0c50-e8af-11e6-88ea-aba27237bc86.png)

Right after the start of `multi` configuration:

![untitled2](https://cloud.githubusercontent.com/assets/4777512/22514029/0f3d95ca-e8af-11e6-8acb-4af8b7affd89.png)

Moving to different sections of navbar, reopening the `launch.json` file, restarting VS Code - doesn't help.

Contents of `.vscode\launch.json` file:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "main",
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}/src/app.ts",
            "outFiles": [
                "${workspaceRoot}/built/**/*.js"
            ],
            "sourceMaps": true,
            "smartStep": true,
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd",
            "runtimeArgs": [
                "${workspaceRoot}",
                "--enable-logging",
                "--remote-debugging-port=9222"
            ],
            "preLaunchTask": "build"
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "renderer",
            "port": 9222,
            "webRoot": "${workspaceRoot}/built",
            "sourceMaps": true,
            "smartStep": true
        }
    ],
    "compounds": [
        {
            "name": "multi",
            "configurations": [
                "main",
                "renderer"
            ]
        }
    ]
}
```

Contents of `.vscode\tasks.json` file:
```
{
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "args": ["run", "build"]
        }
    ]
}
```

**Comment by isidorn** [comment] 2017-02-02 09:28
@Deilan there have been a lot of improvements in this area. Please try this with latest vscode-insiders build. Let us know if you can reproduce with the insiders build - thanks!

**Comment by Deilan** [comment] 2017-02-03 08:46
@isidorn I've recently updated VS Code to the latest stable v1.9.0 and Debugger for Chrome to v2.5.1. Now I receive the following error message:

> Cannot read property 'windows' of null

![untitled](https://cloud.githubusercontent.com/assets/4777512/22584817/7ba506ba-ea05-11e6-84b3-5712b77fc9d8.png)

I've also tried the insiders build as you requested. I encounter the different message in it:

> Configuration 'renderer' is missing in 'launch.json'.

![untitled2](https://cloud.githubusercontent.com/assets/4777512/22584961/57b61be4-ea06-11e6-85cf-5e8678b72312.png)

Hope that helps!

**Comment by isidorn** [comment] 2017-02-06 14:41
Yes, thanks for providing additional data.
The first error message is now fixed, thus you no longer see it in vscode insiders.
The second error message is coming from the chrome debug adapter, thus forwarding to @roblourens

**Comment by roblourens** [comment] 2017-02-06 18:37
@Deilan so you're saying that you see that error (`Cannot read property 'windows' of null`) when you start debugging with the Chrome extension? I have no clue where that would be coming from. Is there an error in the debug console?

**Comment by isidorn** [comment] 2017-02-07 08:17
@roblourens no, cannot read property windows of null is coming from vscode and that is fixed and @Deilan does not see it on insiders. The error 'Configuration 'renderer' is missing in 'launch.json'' is coming from chrome I believe

**Comment by roblourens** [comment] 2017-02-07 16:29
I doubt that's coming from chrome-debug, it doesn't read the launch.json. It looks like he's launching the compound config, and it doesn't know where the 'renderer' config is.

**Comment by Deilan** [comment] 2017-02-09 14:49
@roblourens's right, I launched compound `multi` configuration, which in turn consists of `main` and `renderer` configurations.

**Comment by isidorn** [comment] 2017-05-10 09:50
@Deilan sorry for the slow response this somehow slipped through my radar.
I acknowledge that "Configuration 'renderer' is missing in 'launch.json'' is coming from the vscode side. However I was not able to reproduce this with the latest insiders

Can you please try to reproduce this one more time with the insiders and if you can than could you please share a reproducable repository on GitHub for which I could inspect this problem deeper. This is the only way for me to proceed since I can not reproduce this locally using the launch.json and tasks.json you provided

**Comment by isidorn** [comment] 2017-05-15 08:18
Closing since we need more infor to investigate further. Will reopen if more data is provided.

**Closed by isidorn** 2017-05-15 08:18 UTC
Labels: debug, needs more info

**Comment by Deilan** [comment] 2017-05-21 08:34
@isidorn I confirm that I have stopped experiencing the issue on the latest VS Code version (1.12.2) as well as on the latest VS Code Insiders (1.13.0).

Actually now I experience a different issue:
`Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222` upon launching compound configuration. But I believe it is a different story for a different issue. :)

**Comment by isidorn** [comment] 2017-05-22 07:45
@Deilan thanks for confiriming. And yes that sounds like a different issue
