### ISSUE TITLE
The scrollbar overlays text in the modal window on hover

### ISSUE THREAD

**Issue by kamil-tekiela** [Microsoft/vscode#69624] opened 2019-02-28 23:29 UTC
The issue is similar to https://github.com/Microsoft/vscode/issues/18330
It was originally reported to intelephense:
https://github.com/bmewburn/vscode-intelephense/issues/291

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Install [intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)
2. Create new PHP file and create instance of DateTime()
3. Hover over the constructor. The scrollbar, even though transparent, still overlays the text. This is literally unusable.
![image](https://user-images.githubusercontent.com/6583064/53605655-1ee33380-3bb0-11e9-9d05-7b37036b724b.png)

Does this issue occur when all extensions are disabled?: No, duh

**Comment by sandy081** [comment] 2019-04-01 12:36
Duplicate of #69391

**Closed** 2019-04-01 12:36 UTC
Labels: *duplicate, bug, editor-hover
