### ISSUE TITLE
Reverting Emmet's Remove Tag command results in autoclosing opening tag

### ISSUE THREAD

**Issue by evenfrost** [Microsoft/vscode#40903] opened 2017-12-28 15:30 UTC
- VSCode Version: 1.19.1
- OS Version: Ubuntu 17.10

If `html.autoClosingTags` is set to `true`, reverting `Emmet: Remove Tag` command (e.g. with <kbd>Ctrl</kbd>+<kbd>Z</kbd>) results in duplicate closing tag.

Steps to Reproduce:

1. Make sure that `"html.autoClosingTags": true` in Settings.
2. Write some HTML tags:
```html
<div>
  <span></span>
</div>
```
2. Move cursor to the opening (or closing) `div` tag.
3. Run `Emmet: Remove Tag` command. Tag is properly removed.
4. Press <kbd>Ctrl</kbd>+<kbd>Z</kbd>.
5. Stare at:
```html
<div></div>
  <span></span>
</div>
```

Reproduces without extensions: Yes, as Emmet is a built-in extension.
Not reproduced in Sublime Text with the same Emmet command, so it is more related to VSCode than to Emmet I believe.

Workaround: set `"html.autoClosingTags": false` in Settings.

**Comment by ramya-rao-a** [comment] 2017-12-28 20:02
Duplicate of #39545 with root cause being #34484

**Closed by ramya-rao-a** 2017-12-28 20:02 UTC
Labels: emmet

**Comment by evenfrost** [comment] 2017-12-28 20:05
Bah, sorry, missed that.
