### ISSUE TITLE
Snippets: allow to provide list of values for a tab stop

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3763] opened 2016-03-07 07:58 UTC
I would like to describe a snippet where at a certain tab stop there is a finite list of possible values. They should show up from the intellisense widget.

Alternatively being able to describe that intellisense should popup once you tab into a tab stop would also work for me.

@aeschli fyi

**Comment by mjbvz** [comment] 2018-03-08 05:43
Duplicate of #17545 I believe

**Closed by mjbvz** 2018-03-08 05:43 UTC
Labels: feature-request
