### ISSUE TITLE
Terminal is slow on the latest version of insiders

### ISSUE THREAD

**Issue by PooLP** [Microsoft/vscode#48182] opened 2018-04-19 07:39 UTC
Hi,

The terminal, when performing a gulp or webpack task is extremely slow on the latest version of insiders.

Do you have the same problem?

- VSCode Version: 1.23-insiders
- OS Version: Windows 10 Pro 1709 - 16299.371

Does this issue occur when all extensions are disabled?: Yes

Thanks,
PooLP

**Comment by bpasero** [comment] 2018-04-19 17:36
Duplicate of https://github.com/Microsoft/vscode/issues/48193 then.

**Closed by bpasero** 2018-04-19 17:36 UTC
Labels: electron-update, integrated-terminal
