### ISSUE TITLE
When connected to SharePoint folder I get an error that the Typescript Language Service died

### ISSUE THREAD

**Issue by msterlingjones** [Microsoft/vscode#18527] opened 2017-01-13 19:16 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|beautify|HookyQR|0.7.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|code-beautifier|michelemelluso|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.2|

---

Steps to Reproduce:

1. Open visual Studio Code
2. Open folder
3. Select a mapped drive that is connected to SharePoint.

I see several open bugs on this, but I don't see any solutions.  Please help.

**Comment by waderyan** [comment] 2017-01-18 16:16
Thank you for opening this issue. this is a duplicate of https://github.com/Microsoft/vscode/issues/13665

**Closed by waderyan** 2017-01-18 16:16 UTC
Labels: typescript
