### ISSUE TITLE
Emmet descending order list is not working

### ISSUE THREAD

**Issue by lelouch-I** [microsoft/vscode#109826] opened 2020-11-02 05:18 UTC
Issue Type: <b>Bug</b>

the descending order list shortcut in emmet is not working.

Expected:
```
ul>li.item$@-*5
<ul>
    <li class="item5"></li>
    <li class="item4"></li>
    <li class="item3"></li>
    <li class="item2"></li>
    <li class="item1"></li>
</ul>
```

but I get this:

```
ul>li.item$@-*5
<ul>
    <li class="item1@-"></li>
    <li class="item2@-"></li>
    <li class="item3@-"></li>
    <li class="item4@-"></li>
    <li class="item5@-"></li>
</ul>
```

I don't know what's wrong I search through this but this problem was present 2 years ago.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
lit-html|bie|1.11.1
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|0.2.3
auto-rename-tag|for|0.1.5
live-html-previewer|hdg|0.3.0
LiveServer|rit|5.6.1
html-preview-vscode|tht|0.2.5
html-css-class-completion|Zig|1.19.0

(4 theme extensions excluded)

</details>

**Comment by rzhao271** [comment] 2020-11-02 17:02
This is a duplicate of https://github.com/microsoft/vscode/issues/69168 but it's definitely a popular issue.

**Closed** 2020-11-02 17:03 UTC
Labels: *duplicate, bug, emmet
