### ISSUE TITLE
Github extension fails to push (invalid password) with 35 length password

### ISSUE THREAD

**Issue by kidandcat** [Microsoft/vscode#1965] opened 2016-01-12 22:28 UTC
The github extension fails doing push with (authentication failed) 35 characters only alphanumeric password, the git bash client in cmd does the push (and the authentication) correctly.

**Comment by joaomoreno** [comment] 2016-01-13 10:41
Which OS?

**Comment by kidandcat** [comment] 2016-01-13 10:59
Windows 10

**Comment by lv7777** [comment] 2016-02-05 12:17
I think this bug related #1138

**Comment by joaomoreno** [comment] 2016-02-25 14:43
Closing as duplicate of #1138

**Closed by joaomoreno** 2016-02-25 14:43 UTC
Labels: bug, git
