### ISSUE TITLE
setting sync: environment/os specific settings

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#95302] opened 2020-04-15 07:36 UTC
Issue Type: <b>Feature Request</b>

for the setting sync extension if used for separate OS environment then some os specific settings needs to be edited before the I can start to work on the code.
ex: i use windows (my local environment) and Ubuntu as my remote environment. i switch between these enviroment often
there are environment specific settings such as path to property files or config files , compilers that needs to be changed with environments.
is there a possible solution to this in the settings.json file to use these settings for Ubuntu and these for windows without manual intervention?

if not, is this feature worth consideration?

VS Code version: Code - Insiders 1.45.0-insider (92ff20ac39c7507fdf4164e2bedfdfb700805fe1, 2020-04-14T18:09:06.015Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-96-generic

**Comment by yume-chan** [comment] 2020-04-15 09:06
Duplicate of #5595

For machine specific settings, you can untick this "Sync this setting" menu item.

![image](https://user-images.githubusercontent.com/1330321/79319774-58553a80-7f3b-11ea-82e8-07ec739d1479.png)

**Closed** 2020-04-16 15:08 UTC
