### ISSUE TITLE
Initializing JS/TS languages still doesn't work 

### ISSUE THREAD

**Issue by montselozanod** [Microsoft/vscode#71620] opened 2019-04-02 21:55 UTC
Issue Type: <b>Bug</b>

Every 5 minutes VS Code becomes unusable. The progress bar shows a message saying initializing JS/TS language features. This is very painful, I've had to open/close VS code every 5 minutes to keep on working. Also it's my birthday, can you fix it as a birthday gift PLEASEE!!!!

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.90GB (40.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
git-tree-compare|let|1.6.1
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
code-spell-checker|str|1.6.10

</details>

**Comment by mjbvz** [comment] 2019-04-02 22:58
Duplicate of #68896

But as a birthday present, you should try the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) which should fix this (except for windows network drives I believe). Let me know if you still see this in insiders

**Closed by mjbvz** 2019-04-02 22:58 UTC
Labels: integrated-terminal
