### ISSUE TITLE
git extension can not input text

### ISSUE THREAD

**Issue by huangmeihui** [microsoft/vscode#115171] opened 2021-01-27 02:37 UTC
Issue Type: <b>Bug</b>

can not edit git commit message

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (20.18GB free)|
|Process Argv|--crash-reporter-id 34347812-b06b-4736-94f4-ceae099f713d|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
vscode-great-icons|emm|2.1.64
todo-tree|Gru|0.0.196
vscode-styled-components|jpo|1.5.0
nextjs-snippets|Pul|0.0.3
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
vstry914:30250197
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600:30247031

```

</details>

**Comment by tamuratak** [comment] 2021-01-27 23:44
Duplicate of #112621

**Closed** 2021-04-26 11:28 UTC
Labels: needs more info
