### ISSUE TITLE
Crash from sqlite3 module with remote integration tests

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#143186] opened 2022-02-16 09:22 UTC
CI runs from yesterday are starting to see occasional crashes in the remote integration tests due to sqlite3 module.

Example Runs:

https://github.com/microsoft/vscode/runs/5198249180?check_suite_focus=true#step:17:323
https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_apis/build/builds/156227/logs/126

Symbolicated trace:

```
Operating system: Mac OS X
                  11.6.3 20G415
CPU: amd64
     family 6 model 58 stepping 9
     3 CPUs

GPU: UNKNOWN

Crash reason:  0x00000000 / 0x00000000
Crash address: 0x7fff204bb92e
Process uptime: 10 seconds

Thread 0 (crashed)
 0  libsystem_kernel.dylib!__pthread_kill + 0xa
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x00007ffee97ab348   rbx = 0x0000000113276e00
    rsi = 0x0000000000000006   rdi = 0x0000000000000103
    rbp = 0x00007ffee97ab370   rsp = 0x00007ffee97ab348
     r8 = 0x00007fff807e20e8    r9 = 0x0000000000000000
    r10 = 0x0000000000000000   r11 = 0x0000000000000246
    r12 = 0x0000000000000103   r13 = 0x000000010e63c2c0
    r14 = 0x0000000000000006   r15 = 0x0000000000000016
    rip = 0x00007fff204bb92e
    Found by: given as instruction pointer in context
 1  libsystem_pthread.dylib!pthread_kill + 0x107
    rbx = 0x0000000113276e00   rbp = 0x00007ffee97ab370
    rsp = 0x00007ffee97ab350   r12 = 0x0000000000000103
    r13 = 0x000000010e63c2c0   r14 = 0x0000000000000006
    r15 = 0x0000000000000016   rip = 0x00007fff204ea5bd
    Found by: call frame info
 2  libsystem_c.dylib!abort + 0x7d
    rbx = 0x0000000000000003   rbp = 0x00007ffee97ab3b0
    rsp = 0x00007ffee97ab380   r12 = 0x00007fff80816ae0
    r13 = 0x000000010e63c2c0   r14 = 0x0000000113276e00
    r15 = 0x00007ffee97ab388   rip = 0x00007fff2043f406
    Found by: call frame info
 3  Electron Framework!std::__1::__shared_ptr_emplace<node::RealEnvStore, std::__1::allocator<node::RealEnvStore> >::~__shared_ptr_emplace() [shared_ptr.h : 280 + 0xa]
    rbx = 0x00007fff80816ae0   rbp = 0x00007ffee97ab3d0
    rsp = 0x00007ffee97ab3c0   r12 = 0x00007fff80816ae0
    r13 = 0x000000010e63c2c0   r14 = 0x00007fa86e873400
    r15 = 0x00007fa86e549000   rip = 0x000000010cc71dd2
    Found by: call frame info
 4  Electron Framework!std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::remove(std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*>) [__hash_table : 2575 + 0x2]
    rbp = 0x00007ffee97ab450   rsp = 0x00007ffee97ab3e0
    rip = 0x000000010cc71f6f
    Found by: previous frame's frame pointer
 5  Electron Framework + 0x67d1de9
    rbp = 0x00007ffee97ab460   rsp = 0x00007ffee97ab460
    rip = 0x000000010cc71de9
    Found by: previous frame's frame pointer
 6  Electron Framework!napi_add_finalizer [js_native_api_v8.cc : 432 + 0x3]
    rbp = 0x00007ffee97ab4c0   rsp = 0x00007ffee97ab470
    rip = 0x000000010cc1ec1a
    Found by: previous frame's frame pointer
 7  vscode-sqlite3.node!Napi::Error::Fatal(char const*, char const*) + 0x1a
    rbp = 0x00007ffee97ab4d0   rsp = 0x00007ffee97ab4d0
    rip = 0x000000012018751a
    Found by: previous frame's frame pointer
 8  vscode-sqlite3.node!Napi::Error::New(napi_env__*) + 0x169
    rbp = 0x00007ffee97ab520   rsp = 0x00007ffee97ab4e0
    rip = 0x000000012018cb49
    Found by: call frame info
 9  vscode-sqlite3.node!Napi::Function::MakeCallback(napi_value__*, unsigned long, napi_value__* const*, napi_async_context__*) const + 0x42
    rbx = 0x00007ffee97ab548   rbp = 0x00007ffee97ab580
    rsp = 0x00007ffee97ab530   r12 = 0x0000000000000000
    r14 = 0x00007fa871556930   r15 = 0x00007fa86e48de30
    rip = 0x000000012018cfe2
    Found by: call frame info
10  vscode-sqlite3.node!node_sqlite3::Statement::CleanQueue() + 0x508
    rbx = 0x00007fa87060ef01   rbp = 0x00007ffee97ab680
    rsp = 0x00007ffee97ab590   r12 = 0x0000000000000000
    r14 = 0x00007fa871556930   r15 = 0x00007fa86e48de30
    rip = 0x000000012019e588
    Found by: call frame info
11  vscode-sqlite3.node!node_sqlite3::Statement::~Statement() + 0x2a
    rbx = 0x00007fa871556930   rbp = 0x00007ffee97ab6a0
    rsp = 0x00007ffee97ab690   r12 = 0x00000001201aa0f0
    r13 = 0x0000000000000000   r14 = 0x00007fa87060ef30
    r15 = 0x00007fa871556930   rip = 0x00000001201ab70a
    Found by: call frame info
12  vscode-sqlite3.node!node_sqlite3::Statement::~Statement() + 0xe
    rbx = 0x00007fa871556930   rbp = 0x00007ffee97ab6c0
    rsp = 0x00007ffee97ab6b0   r12 = 0x00000001201aa0f0
    r13 = 0x0000000000000000   r14 = 0x00007fa87060ef30
    r15 = 0x00007fa871556930   rip = 0x00000001201a76de
    Found by: call frame info
13  vscode-sqlite3.node!Napi::ObjectWrap<node_sqlite3::Statement>::FinalizeCallback(napi_env__*, void*, void*) + 0x32
    rbx = 0x00007fa871556930   rbp = 0x00007ffee97ab6f0
    rsp = 0x00007ffee97ab6d0   r12 = 0x00000001201aa0f0
    r13 = 0x0000000000000000   r14 = 0x00007fa87060ef30
    r15 = 0x00007fa871556930   rip = 0x00000001201aa122
    Found by: call frame info
14  Electron Framework!napi_create_external_buffer [js_native_api_v8.h : 337 + 0x7]
    rbx = 0x00007fa87060ef30   rbp = 0x00007ffee97ab750
    rsp = 0x00007ffee97ab700   r12 = 0x00000001201aa0f0
    r13 = 0x0000000000000000   r14 = 0x0000000000000000
    r15 = 0x00007fa871556930   rip = 0x000000010cc20a9f
    Found by: call frame info
15  Electron Framework!node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags) [node.cc : 1016 + 0x2]
    rbp = 0x00007ffee97ab770   rsp = 0x00007ffee97ab760
    rip = 0x000000010cc1509f
    Found by: previous frame's frame pointer
16  Electron Framework!napi_create_buffer [js_native_api_v8.h : 160 + 0x8]
    rbp = 0x00007ffee97ab790   rsp = 0x00007ffee97ab780
    rip = 0x000000010cc208d6
    Found by: previous frame's frame pointer
17  Electron Framework!node::Environment::NearHeapLimitCallback(void*, unsigned long, unsigned long) [env-inl.h : 448 + 0x4]
    rbp = 0x00007ffee97ab9c0   rsp = 0x00007ffee97ab7a0
    rip = 0x000000010cc02190
    Found by: previous frame's frame pointer
18  Electron Framework!node::ShouldAbortOnUncaughtException(v8::Isolate*) [env-inl.h : 373 + 0x7]
    rbp = 0x00007ffee97aba50   rsp = 0x00007ffee97ab9d0
    rip = 0x000000010cbcb2c4
    Found by: previous frame's frame pointer
19  Electron Framework!electron::TracingControllerImpl::~TracingControllerImpl() [javascript_environment.cc : 231 + 0x7]
    rbp = 0x00007ffee97aba70   rsp = 0x00007ffee97aba60
    rip = 0x00000001065a0765
    Found by: previous frame's frame pointer
20  Electron Framework!electron::ElectronBrowserMainParts::PostMainMessageLoopRun() [new : 245 + 0x3]
    rbp = 0x00007ffee97abae0   rsp = 0x00007ffee97aba80
    rip = 0x0000000106588629
    Found by: previous frame's frame pointer
21  Electron Framework!content::BrowserMainLoop::PostCreateThreadsImpl() [browser_main_loop.cc : 1177 + 0xc]
    rbp = 0x00007ffee97abb90   rsp = 0x00007ffee97abaf0
    rip = 0x000000010762c067
    Found by: previous frame's frame pointer
22  Electron Framework!content::(anonymous namespace)::BindHidManager(mojo::PendingReceiver<device::mojom::HidManager>) [browser_main_loop.cc : 418 + 0xa]
    rbp = 0x00007ffee97abbe0   rsp = 0x00007ffee97abba0
    rip = 0x000000010762d98a
    Found by: previous frame's frame pointer
23  Electron Framework!void mojo::internal::BinderContextTraits<content::ServiceWorkerVersionBaseInfo const&>::BindGenericReceiver<blink::mojom::PeriodicBackgroundSyncService>(base::RepeatingCallback<void (content::ServiceWorkerVersionBaseInfo const&, mojo::PendingReceiver<blink::mojom::PeriodicBackgroundSyncService>)> const&, content::ServiceWorkerVersionBaseInfo const&, mojo::ScopedHandleBase<mojo::MessagePipeHandle>) [handle.h : 166 + 0x1]
    rbp = 0x00007ffee97abc30   rsp = 0x00007ffee97abbf0
    rip = 0x00000001076296f6
    Found by: previous frame's frame pointer
24  Electron Framework!content::ContentMainRunnerImpl::Initialize(content::ContentMainParams const&) [content_main_runner_impl.cc : 681 + 0x3]
    rbp = 0x00007ffee97abd10   rsp = 0x00007ffee97abc40
    rip = 0x00000001074bdd83
    Found by: previous frame's frame pointer
25  Electron Framework!std::__1::unique_ptr<base::mac::ScopedNSAutoreleasePool, std::__1::default_delete<base::mac::ScopedNSAutoreleasePool> >::reset(base::mac::ScopedNSAutoreleasePool*) [unique_ptr.h : 313 + 0x2]
    rbp = 0x00007ffee97abdb0   rsp = 0x00007ffee97abd20
    rip = 0x00000001074bd81b
    Found by: previous frame's frame pointer
26  Electron Framework!bool mojo::internal::ValidateParams<display::mojom::internal::Display_Data>(mojo::internal::Pointer<display::mojom::internal::Display_Data> const&, mojo::internal::ValidationContext*) [validation_util.h : 0 + 0x7]
    rbp = 0x00007ffee97abfb0   rsp = 0x00007ffee97abdc0
    rip = 0x00000001074bc1eb
    Found by: previous frame's frame pointer
27  Electron Framework!remote_cocoa::mojom::internal::TextInputHost_HasCompositionText_Params_Data::Validate(void const*, mojo::internal::ValidationContext*) [text_input_host.mojom-shared.cc : 416 + 0x2]
    rbp = 0x00007ffee97abfe0   rsp = 0x00007ffee97abfc0
    rip = 0x00000001074bcae9
    Found by: previous frame's frame pointer
28  Electron Framework!ElectronMain [electron_library_main.mm : 32 + 0x5]
    rbp = 0x00007ffee97ac080   rsp = 0x00007ffee97abff0
    rip = 0x00000001064ba566
    Found by: previous frame's frame pointer
29  Electron + 0xd36
    rbp = 0x00007ffee97ac130   rsp = 0x00007ffee97ac090
    rip = 0x0000000106451d36
    Found by: previous frame's frame pointer
30  libdyld.dylib!start + 0x1
    rbp = 0x00007ffee97ac140   rsp = 0x00007ffee97ac140
    rip = 0x00007fff20505f3d
    Found by: previous frame's frame pointer
```

**Comment by deepak1556** [comment] 2022-02-16 09:27
Looks like there are calls from the sqlite3 module that tries to execute JS callback after main process shutdown has been triggered.

**Comment by bpasero** [comment] 2022-02-16 09:29
This sounds familiar right? Can we patch this in our fork?

**Comment by deepak1556** [comment] 2022-02-16 09:53
We already do that https://github.com/microsoft/vscode-node-sqlite3/blob/8494d7b0a6c2a9b3efb39ccd9e34f102a77c67ad/binding.gyp#L62

This is mostly a case that one of the test is not properly shutting down the sqlite database, since all of module operations happen in a background thread, the response from one of the threads like executing a sqlite statement causes a callback to trigger on the main thread and in this case it happens after the node environment tear down has been triggered.

We might want to track which test caused this regression and fix it there, not much we can do in the module for this crash.

**Comment by bpasero** [comment] 2022-02-16 09:58
Can we distill whether this is the remote server producing the crash or Electron?

**Comment by deepak1556** [comment] 2022-02-16 10:25
Given the thread trace contains `Electron Framework!content::ContentMainRunnerImpl::Initialize`, the crash is triggered from the client

**Comment by bpasero** [comment] 2022-02-16 10:42
Our integration tests trigger an abnormal exit from the run: 

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L526

and that goes to:

https://github.com/microsoft/vscode/blob/ef70f99af7c90bb37f6dbb797c36de76a51ba73b/src/vs/platform/lifecycle/electron-main/lifecycleMainService.ts#L598-L637

The underlying reason is that `app.quit` does not allow to return an exit code. 

It is quite possible that this form of termination leaves sqlite in a bad state?

**Comment by bpasero** [comment] 2022-02-16 10:43
Actually we do orderly shutdown storage service it seems given we await the `onWillShutdown`:

https://github.com/microsoft/vscode/blob/44047c7637b0669395a2de7afee2cf23d5f19b0d/src/vs/platform/storage/electron-main/storageMainService.ts#L80-L89

**Comment by deepak1556** [comment] 2022-02-18 11:03
yup they are the same.

**Comment by bpasero** [comment] 2022-02-19 17:01
Re https://github.com/microsoft/vscode/issues/143186#issuecomment-1041308043

If we swallow native exceptions, how does this still end up as a native crash in our CI? And couldn't this also be a crash that occurs for our normal users? To clarify: the call that shuts down storage before `app.exit` is the same we trigger for `app.quit` when normally shutting down (not from extension tests).

**Comment by deepak1556** [comment] 2022-02-21 11:39
> If we swallow native exceptions, how does this still end up as a native crash in our CI?

This is not an exception but rather a fatal error, from the stack this is what seems to be happening

`Napi::ObjectWrap<node_sqlite3::Statement>::FinalizeCallback` gets triggered, which indicates that the Javascript object associated with the native instance of `node_sqlite3::Statement` is ready for GC and we are free to delete this class. `FinalizeCallback` is something that gets registered by default when you inherit [Napi::ObjectWrap<T>](https://github.com/nodejs/node-addon-api/blob/b7659db9457e2fa674fff1b6a2a84e8d39edea1c/napi-inl.h#L4114)

`Napi::ObjectWrap<T>::FinalizeCallback` basically allows cleanup for the sub classes via the virtual method [Napi::ObjectWrap<T>::Finalize](https://github.com/nodejs/node-addon-api/blob/b7659db9457e2fa674fff1b6a2a84e8d39edea1c/napi-inl.h#L4559). `node_sqlite3::Statement` class does not provide a custom implementation for the `Finalize` method, so we just end up on the next line of [deleting the native instance](https://github.com/nodejs/node-addon-api/blob/b7659db9457e2fa674fff1b6a2a84e8d39edea1c/napi-inl.h#L4560).

`node_sqlite3::Statement::~Statement` calls [node_sqlite3::Statement::Finalize_](https://github.com/microsoft/vscode-node-sqlite3/blob/8494d7b0a6c2a9b3efb39ccd9e34f102a77c67ad/src/statement.cc#L898-L907) and one of the actions it performs is to [clean the statement queue of pending operations](https://github.com/microsoft/vscode-node-sqlite3/blob/8494d7b0a6c2a9b3efb39ccd9e34f102a77c67ad/src/statement.cc#L913-L941) (basically JS callbacks of get, bind etc operations). When trying to invoke one such [callback](https://github.com/microsoft/vscode-node-sqlite3/blob/8494d7b0a6c2a9b3efb39ccd9e34f102a77c67ad/src/statement.cc#L930) it [fails](https://github.com/nodejs/node-addon-api/blob/b7659db9457e2fa674fff1b6a2a84e8d39edea1c/napi-inl.h#L2337) because the node environment has started to shut down. 

`NAPI_RETURN_OR_THROW_IF_FAILED` will eventually end up in the non-exception version [NAPI_THROW_IF_FAILED](https://github.com/nodejs/node-addon-api/blob/b7659db9457e2fa674fff1b6a2a84e8d39edea1c/napi.h#L89) since we disabled cpp exceptions. But `Error::New` construction will fail because the environment has shutdown leading to the first fatal call at [napi_get_last_error_info](https://github.com/nodejs/node-addon-api/blob/b7659db9457e2fa674fff1b6a2a84e8d39edea1c/napi-inl.h#L2526-L2530)

Since we know that there is an active prepared statement and from https://github.com/mapbox/node-sqlite3/wiki#documentation

> Database#close() function will wait until all pending queries are completed before closing the database.

The question is why was the statement finalized after the process started shutting down ? This could either mean the database close was not performed https://github.com/microsoft/vscode/issues/143186#issuecomment-1041351221 or is the above argument about `Database#close` incorrect and should we explicitly call `finalize` https://github.com/mapbox/node-sqlite3/wiki/API#statementfinalizecallback ?

**Comment by deepak1556** [comment] 2022-02-21 11:40
I will add some logs to the module to track down what state the database was in when the `node_sqlite3::Statement::Finalize_` got triggered and also try to print what active statement was being executed, which give some more ideas on where the problem might be.

**Comment by bpasero** [comment] 2022-02-21 12:24
Oh nice analysis, if it helps I could add more verbose logging for what is going on in the SQLite3 DB at least from our storage service and how the DB is used and closed. Maybe there is some race condition where a statement is still being executed after we have started the process of `close`.

**Comment by deepak1556** [comment] 2022-02-21 12:28
@bpasero that would be helpful, can you add those logging so that they are only enabled for CI environment ? Thanks!

**Comment by bpasero** [comment] 2022-02-21 15:50
Added via https://github.com/microsoft/vscode/commit/361c94253de6bbefea4d09e46970390ba7da9e43. I once locally was able to see a suspicious `open` logged after `app.exit` but now was not able to reproduce, but that could well be the crash reason.

Btw noticed that we operate SQLite in `memory` mode in integration tests, meaning there is no local DB on disk to write to, everything is in memory (but SQLite native module is still being used).

**Comment by bpasero** [comment] 2022-02-21 17:07
Looks like https://dev.azure.com/monacotools/Monaco/_build/results?buildId=157033&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d&l=917 is a run with logging enabled and that crash.

Observing the output:

```
[main 2022-02-21T16:28:02.740Z] Lifecycle#kill()
[main 2022-02-21T16:28:02.743Z] storageMainService#onWillShutdown()
[main 2022-02-21T16:28:02.744Z] GlobalStorageMain#close() - begin
[main 2022-02-21T16:28:02.744Z] WorkspaceStorageMain#close() - begin
[main 2022-02-21T16:28:02.747Z] Waiting for extension host with pid 9426 to exit.
[main 2022-02-21T16:28:02.779Z] [storage :memory:] close()
[main 2022-02-21T16:28:02.779Z] [storage :memory:] close()
[main 2022-02-21T16:28:02.779Z] GlobalStorageMain#close() - end
[main 2022-02-21T16:28:02.783Z] WorkspaceStorageMain#close() - end
[main 2022-02-21T16:28:02.785Z] [storage :memory:] open(:memory:, retryOnBusy: true)
[main 2022-02-21T16:28:02.785Z] [storage :memory:] open - source: Error
    at m.connect (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:34227)
    at new m (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:31524)
    at g.doCreate (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:67:42527)
    at async /Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:67:40409
    at async D.withStorageInitialized (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:67:39428)
    at async D.call (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:67:38984)
[main 2022-02-21T16:28:02.903Z] [storage :memory:] updateItems(): insert(Map(4) {__$__isNewStorageMarker => true, __$__targetStorageMarker => {"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"~remote.forwardedPortsContainer":1,"debug.selectedconfigname":1,"debug.uxstate":0,"workbench.panel.placeholderPanels":1,"workbench.panel.repl":1,"terminal.integrated.environmentVariableCollections":1}, terminal.integrated.environmentVariableCollections => [], workbench.explorer.views.state => {"outline":{"collapsed":true,"isHidden":false},"timeline":{"collapsed":true,"isHidden":false},"workbench.explorer.openEditorsView":{"collapsed":false,"isHidden":true},"workbench.explorer.fileView":{"collapsed":false,"isHidden":false},"npm":{"collapsed":true,"isHidden":true}}}), delete(Set(0) {})
```

So indeed it looks like a DB is opened and written to after we have called `close` on it.

**Comment by bpasero** [comment] 2022-02-21 18:52
It looks like after we have closed all storage, the window is sometimes racing to get hold of a workspace storage database from here:

https://github.com/microsoft/vscode/blob/44047c7637b0669395a2de7afee2cf23d5f19b0d/src/vs/platform/storage/electron-main/storageIpc.ts#L84

But since we have closed all storage databases before, we create now a new one and start a transaction. And so we race this transaction against `app.exit`. I think this would not happen in a normal shutdown because we only close a window after all handlers have finished. 

The culprit is `window.destroy` that will bypass our handlers to orderly shutdown:

https://github.com/microsoft/vscode/blob/361c94253de6bbefea4d09e46970390ba7da9e43/src/vs/platform/lifecycle/electron-main/lifecycleMainService.ts#L629

The only way out I see is to block all access for SQLite after `onWillShutdown` but in theory there can be many other things the window is trying to do on the main side not knowing that it is being destroyed...

**Comment by deepak1556** [comment] 2022-02-22 04:12
@bpasero in `Lifecycle#kill()` what is the reason for the `1s` timeout ? If we don't do that, then `app.exit` won't race against the window destruction right ?

In Electron, test suites are terminated after [each runner completes](https://github.com/electron/electron/blob/fa7461685dfec20208b21b91accad641ec8c577d/spec-main/index.js#L126-L142) its execution which includes teardown of the windows that got setup via [helpers](https://github.com/electron/electron/blob/fa7461685dfec20208b21b91accad641ec8c577d/spec-main/window-helpers.ts#L25-L47)

**Comment by bpasero** [comment] 2022-02-22 06:09
The more I think about it, the more I wonder why we would call `BrowserWindow.destroy` to begin with. This is somewhat asking for trouble because it is a non-tested, abnormal shutdown of the window. Instead, we could gracefully close the window, like we do in a normal shutdown, maybe with some extra code to prevent dialogs from popping up, potentially blocking the closing of the window...

**Comment by bpasero** [comment] 2022-02-22 06:39
Will explore https://github.com/microsoft/vscode/issues/143186#issuecomment-1047458228 in march but have pushed a change to not attempt to create new SQLite databases when the application goes down with `app.kill`.

**Closed** 2022-02-22 06:38 UTC
Labels: freeze-slow-crash-leak, engineering, integration-test-failure
