### ISSUE TITLE
vscode.dev doesn't load in Chromium on Ubuntu

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#163148] opened 2022-10-10 06:29 UTC
* Ubuntu 20.04
* Chromium 106.0.5249.91
* (no extensions)

Opening `https://vscode.dev` or `https://insiders.vscode.dev` just shows our background image. There are no erros in the console:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/5047891/194808957-c1a00204-88c5-4cfb-b9d6-3bd78a86ede4.png">

**Comment by joaomoreno** [comment] 2022-10-17 12:43
Duplicate of #145647

**Closed by joaomoreno** 2022-10-17 12:43 UTC
