### ISSUE TITLE
Terminal on start up

### ISSUE THREAD

**Issue by JohannAx** [microsoft/vscode#132984] opened 2021-09-13 12:28 UTC
Issue Type: <b>Bug</b>

Hi, all together,

after last update to version 1.60.0 it is always powershell terminal that appeares on VSCode start. I have cmd set as default.

BG.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.01GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.47.1
xml|Dot|2.5.1
gitlens|eam|11.6.0
code-runner|for|0.11.5
plantuml|jeb|2.15.1
Lua|key|0.0.9
git-graph|mhu|1.30.0
csharp|ms-|1.23.15
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.6.0
powershell|ms-|2021.9.0
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
markdown-preview-enhanced|shd|0.6.0
vscode-fileutils|sle|3.4.5
code-spell-checker|str|2.0.4
vscode-lua|tri|0.12.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by IllusionMH** [comment] 2021-09-13 12:30
/duplicate of #132150 and other for open in internal terminal

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-13 12:31 UTC
Labels: *duplicate
