### ISSUE TITLE
Images with relative path not shown in markdown preview

### ISSUE THREAD

**Issue by scullhead** [Microsoft/vscode#45757] opened 2018-03-14 12:20 UTC
![vs_code_markdown_preview_images_not_shown](https://user-images.githubusercontent.com/10958573/37401956-1b7cb5b2-278a-11e8-9857-f6d64ca60f6f.png)
Issue Type: <b>Bug</b>

* Open a markdown file containing an image with a relative path in VS Code.
* Open the markdown preview - the image is not shown
* When you view the readme.md file on the web interface of a git server (in our case Gitblit) the image is shown.

* It worked in VS Code version 1.20.1 (images where shown)
* It does no longer work with VS Code version 1.21.0

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|Memory (System)|15.88GB (10.23GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\GIT\Tools\DelphiProjectConfigurator\README.md|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|0.10.0
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
vs-color-picker|lih|0.7.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment] 2018-03-14 15:04
Duplicate of #45155

**Closed by mjbvz** 2018-03-14 15:04 UTC
