### ISSUE TITLE
VSC won't download on IOS Catalina

### ISSUE THREAD

**Issue by miekesmith** [microsoft/vscode#84635] opened 2019-11-12 23:53 UTC
Why won't VSC download to my brand new, fully updated MacBook Pro? When I try to open it after install, error message is Visual Studio Code can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information." ?????

**Comment by miekesmith** [comment] 2019-11-12 23:55
I checked those and no one ever addresses why VSC won't run on Catalina. This is absurd.

**Comment by gjsjohnmurray** [comment] 2019-11-13 00:51
/duplicate of #74782

Not absurd. Just be patient - https://github.com/microsoft/vscode/issues/74782#issuecomment-542047829

**Closed** 2019-11-13 00:51 UTC
Labels: *duplicate
