### ISSUE TITLE
Integrated terminal breaks sometimes on window resize

### ISSUE THREAD

**Issue by yogesh-aggarwal** [microsoft/vscode#98140] opened 2020-05-19 07:06 UTC
- VSCode Version:
- OS Version: Windows 10 2004 (19624.1000) Insiders

Steps to Reproduce:
1. Resize the window when something is going on in the terminal. For example, the Angular app is compiling (`ng serve`).
2. Minimize the window quickly.

Does this issue occur when all extensions are disabled?: Yes

Here's an example: 
![vscode-bug](https://user-images.githubusercontent.com/47052128/82295873-02f2ca00-99ce-11ea-9423-b77c6f92f012.gif)

**Comment by enovezuli** [comment] 2020-05-19 10:34
* VSCode version: 1.45.1 (system setup)
* OS version: Windows NT x64 10.0.19041
* Integrated Terminal wsl (Ubuntu) bash.exe
In my case it just falls down:
![vscodeTerminalBug](https://user-images.githubusercontent.com/57828630/82316443-17829280-99cd-11ea-9a7e-4183c331cd79.gif)

**Comment by yogesh-aggarwal** [comment] 2020-05-19 12:37
> * VSCode version: 1.45.1 (system setup)
> * OS version: Windows NT x64 10.0.19041
> * Integrated Terminal wsl (Ubuntu) bash.exe
>   In my case it just falls down:
>   ![vscodeTerminalBug](https://user-images.githubusercontent.com/57828630/82316443-17829280-99cd-11ea-9a7e-4183c331cd79.gif)

I have faced it too 😄

**Comment by rzhao271** [comment] 2020-11-04 21:21
@enovezuli that issue's being tracked here #97808

@yogesh-aggarwal I can't reproduce the issue while running yarn watch on Windows 10 on the latest Insiders. Are you still facing this issue after upgrading?

**Comment by yogesh-aggarwal** [comment] 2020-11-05 11:42
Let me tell you my scenario, I use angular's "ng serve" command to produce the problem. It sometimes doesn't persist but it needs to be fixed ASAP!! Let me know if you want more information regarding this!!

**Comment by rzhao271** [comment] 2020-11-05 16:59
Is the output of ng serve supposed to stay on one line, or is it supposed to generate multiple lines? It seems to be doing both in your example.

**Comment by Tyriar** [comment] 2020-11-05 20:59
I think this issue is seeing both https://github.com/microsoft/vscode/issues/109479 and #97808, so closing as a duplicate of them

/duplicate

**Closed by Tyriar** 2020-11-05 20:59 UTC
Labels: bug, integrated-terminal, needs more info
