### ISSUE TITLE
Sticky Scroll feature - that works with XML (this case being AAD B2C Custom Policies - when working with User Journeys, Technical Profiles etc.)

### ISSUE THREAD

**Issue by nzcoderguy** [microsoft/vscode#157720] opened 2022-08-09 22:45 UTC
When working with AAD B2C Custom Policies using VSC - the Stick Scroll feature would be nice to have - but it doesn't appear to make any difference for Xml files when writing/reading Technical Profiles/User Journeys etc. would help immensely.

**Comment by gjsjohnmurray** [comment] 2022-08-10 03:59
@nzcoderguy how does your XML look in the Outline view?

@aiday-mar my guess is that the `SymbolKind`s assigned to a document in XML language mode don't intersect with the hardcoded sticky set. Elsewhere I have suggested that the sticky set could be specified in the language configuration file. Perhaps fall back to the current hardcoded set if the specification is completely absent from the language configuration file. But treat an empty spec as meaning no symbol kinds are sticky.

**Comment by nzcoderguy** [comment] 2022-08-10 04:16
Outline view - doesn't show anything:

![image](https://user-images.githubusercontent.com/2540432/183814616-19b5f58c-93de-45a8-b5d0-8f137e40f8de.png)

**Comment by gjsjohnmurray** [comment] 2022-08-10 04:39
I suggest you look for an extension which provides an XML language server.

**Comment by nzcoderguy** [comment] 2022-08-10 04:40
Do you recommend any XML extensions that would provide the same type of feature/functionality?

**Comment by aiday-mar** [comment] 2022-08-10 10:03
You may install the XML Language Support by Red Hat from the market place

**Comment by gjsjohnmurray** [comment] 2022-08-10 10:03
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml is popular and populates the Outline, as shown in its first screenshot. Unfortunately it classifies the symbols as `SymbolKind.Field`, which isn't sticky in 1.70.

**Comment by gjsjohnmurray** [comment] 2022-08-10 10:05
I'm getting some stickiness in XML that I'm testing with the current 1.71 Insiders, so something is changing in this area. @aiday-mar can you share any information yet about this?

**Comment by aiday-mar** [comment] 2022-08-10 10:07
Hi thank you for all your feedback on all the open issues. I am currently testing the changes proposed by the PR https://github.com/microsoft/vscode/pull/157466 on all kinds of files. So far it would seem the correct sticky lines are stuck (no longer comments or decorators). I am still in the process of testing, but will make a PR soon.

**Comment by aiday-mar** [comment] 2022-08-10 12:10
@gjsjohnmurray Indeed with the latest refactoring of the sticky scroll (specifically after removing the comparison against different symbol kinds), the sticky scroll sticks XML headers to the top.

![sticky-scroll-xml](https://user-images.githubusercontent.com/61460952/183897453-4c85b94d-7b20-49dc-a717-ef587795432f.gif)

As the issue does not have a specific example, I am currently not able to reproduce it.

**Closed** 2022-08-10 13:39 UTC
Labels: editor-sticky-scroll

**Comment by alexdima** [comment] 2022-08-10 13:40
Our suggestion is to install an extension that registers a document symbol provider for XML (such as the redhat xml extension). Otherwise, we also have https://github.com/microsoft/vscode/issues/157165 which tracks using a different method for computing sticky lines, based on indentation.

**Comment by nzcoderguy** [comment] 2022-08-10 22:30
I have the RedHat XML Extension installed - 
![image](https://user-images.githubusercontent.com/2540432/184031597-d3ec89a1-a22a-40a5-a419-5d45c2842780.png)

but its not behaving like @aiday-mar 's snipping clip - or is that in the latest build not released yet of VSC?

**Comment by gjsjohnmurray** [comment] 2022-08-10 22:37
You need to be using Insiders edition. Download it from https://code.visualstudio.com/insiders/

You can install it alongside the general release version, aka Stable.

**Comment by nzcoderguy** [comment] 2022-08-10 22:46
Thank you so much. Insiders version + RedHat XML extension + B2C extension, and enabling this sticky scroll = working brilliantly. 
Assuming its a matter of time when the public release will incorporate these changes?

The Outline window is populating with the XML structure/tree now, along with the breadcrumb/current selected branch too - looks great!

![image](https://user-images.githubusercontent.com/2540432/184034511-6b199163-b6aa-40e6-bd79-948beb7fb8f9.png)

**Comment by gjsjohnmurray** [comment] 2022-08-11 03:43
Excellent! 1.71 is expected to ship in early September. See #157454.
