### ISSUE TITLE
Typo in settings s/weather/whether/

### ISSUE THREAD

**Issue by aaegic** [microsoft/vscode#111856] opened 2020-12-04 01:18 UTC
- VSCode Version:Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134
- OS Version:10.0.17134 N/A Build 17134

Steps to Reproduce:

1.CTRL+,
2.search for weather 

Editor › Smart Select: Select Leading And Trailing Whitespace
**Weather** leading and trailing whitespace should always be selected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-12-04 01:27
/duplicate of #110661 and fixed in upcoming release, due out next week.

**Closed** 2020-12-04 01:28 UTC
Labels: *duplicate
