### ISSUE TITLE
Autocomplete NodeJS modules

### ISSUE THREAD

**Issue by grandsilence** [Microsoft/vscode#23186] opened 2017-03-24 21:45 UTC
1. VSCODE 1.10.2
2. Windows 10

Typings installed globaly. Typings packages installed too, some local, some global. Creation of jsconfig.json didn't help.
Typescript version 2.2.1.

Autocomplete for any modules not working absolutely...
Help please.

![image](https://cloud.githubusercontent.com/assets/9817522/24314698/ff8b3a8e-10f3-11e7-9878-0d910155c3d6.png)

**Comment by mjbvz** [comment] 2017-04-03 23:08
I'm unable to reproduce this. Can you share your workspace?

**Comment by mjbvz** [comment] 2017-04-11 01:21
Closing as we need more info to investigate. @grandsilence Please share a small example project and some additional information about your workspace so that we can try to understand what is going wrong here

**Closed by mjbvz** 2017-04-11 01:21 UTC
Labels: javascript, needs more info, typescript
