### ISSUE TITLE
Math support in native notebook markdown cells

### ISSUE THREAD

**Issue by ctokun** [microsoft/vscode#108551] opened 2020-10-13 00:31 UTC
Math is supported in markdown files and in markdown cells in the notebook editor but does not render in markdown cells in the native notebooks. Math support in markdown cells of the native notebook would be nice to have.

**Comment by jmahlers** [comment] 2021-02-08 21:26
Any chance of this being implemented? Right now this is the biggest thing that stops me from using the native editor as opposed to the normal Jupyter editor.

**Comment by jmahlers** [comment] 2021-03-04 20:02
For anyone else like me who very much wants to use the native editor but needs math support see [#106701](https://github.com/microsoft/vscode/issues/106701). With the rendering setting set to true, math works well enough.

**Comment by mjbvz** [comment] 2021-06-02 00:11
Duplicate of #119536

Also released publicly with https://code.visualstudio.com/updates/v1_56#_math-support-in-markdown-cells

**Closed by mjbvz** 2021-06-02 00:11 UTC
Labels: feature-request, notebook
