### ISSUE TITLE
[folding] Make hiding of the folding gutter configurable

### ISSUE THREAD

**Issue by adamcrossland** [Microsoft/vscode#6563] opened 2016-05-20 00:07 UTC
- VSCode Version: all
- OS Version:all

When I use Code on a touch-enabled device with a stylus rather than a mouse, it is very difficult to use the folding gutter, as it is hidden unless the pointer is hovering over it. While having that gutter hidden when I am not using it nicely reduces visual noise, there are times that I need it to always be there.

Why not provide a configuration item that allows the user to switch between having it be always visible or only visible on hover?

**Comment by jchannon** [comment] 2017-02-08 17:20
+1

**Comment by 23doors** [comment] 2017-04-14 11:10
seems like a duplicate of https://github.com/Microsoft/vscode/issues/3911

**Comment by aeschli** [comment] 2017-04-18 07:09
correct, duplicate of #3911

**Closed by aeschli** 2017-04-18 07:09 UTC
Labels: editor-folding, feature-request
