### ISSUE TITLE
Completely broken Code

### ISSUE THREAD

**Issue by PiniH** [Microsoft/vscode#24669] opened 2017-04-13 10:20 UTC
Visual Studio completely broken
- VSCode Version: 1.11.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. No clue, but I think this might be severe enough to try and track down, I am ready to help investigating.

The last thing I remember doing is installing git history extension, not sure if it worked right after or not, left for the day, came today to the computer visual studio code is completely empty, black window, no command works except for dev tools (which show no console error whatsoever).

Tried restarting, uninstalling, removing extensions from the folder and more, to no avail.

**Comment by joaomoreno** [comment] 2017-04-13 12:48
Can you provide a screenshot?

**Comment by PiniH** [comment] 2017-04-13 13:24
http://pasteboard.co/3NUJvdjE7.png

It's just black, the dev tools look like this:
http://pasteboard.co/nAQFgLBe.png

**Comment by chrisdothtml** [comment] 2017-04-13 13:42
Did you try uninstalling the app, deleting `~/.vscode`, then reinstalling?

**Comment by PiniH** [comment] 2017-04-13 13:45
Yep, even restarted the computer and all the regular stuff, nothing seemed to help.

Tried to look for any references to vscode on my computer as well.

**Comment by chrisdothtml** [comment] 2017-04-13 13:47
Does the [Insiders Build](https://code.visualstudio.com/insiders) work?

**Comment by PiniH** [comment] 2017-04-13 13:50
Yep.

**Comment by joaomoreno** [comment] 2017-04-13 14:17
Dupe of #23639

Update should be coming any moment now!

**Closed by joaomoreno** 2017-04-13 14:17 UTC
Labels: needs more info
