### ISSUE TITLE
Inlay hints should be invalidated quicker when lines are deleted

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129512] opened 2021-07-27 12:10 UTC
Testing #129381

This seems ugly, can we invalidate the faster since the content surrounded them was deleted?

![recording (47)](https://user-images.githubusercontent.com/2193314/127151141-5c3ad9bb-64c6-400d-8bd9-f6b4ceb031ff.gif)

**Comment by hediet** [comment] 2021-07-27 12:16
Duplicate of #125995.

**Closed by hediet** 2021-07-27 12:16 UTC
Labels: *duplicate
