### ISSUE TITLE
VS Code Insiders (Users) not opening

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#55353] opened 2018-07-30 08:32 UTC
- Visual Studio Code - Insiders (User): 1.26.0
- OS Version: Windows 10

Steps to Reproduce:

1. Download the [VS Code Insiders (Users)](https://code.visualstudio.com/updates/v1_25#_user-setup-for-windows)
2. Open the Insider build

![2018-07-30_13-52-39](https://user-images.githubusercontent.com/29014463/43386179-7ec877c2-9400-11e8-82a1-19d8b6298166.gif)

**Comment by guiohm** [comment] 2018-07-30 14:39
Same here. (also from command line)

**Comment by pdfowler** [comment] 2018-07-30 17:21
On MacOS too :

```
Applications pdfowler$ ./Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron --verbose
[main 10:20:08 AM] Starting VS Code
[main 10:20:08 AM] from: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app
[main 10:20:08 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 10:20:08 AM] Resolving machine identifier...
[main 10:20:08 AM] Resolved machine identifier: 75981006e5caffec60741792b31b0563aaa20fb42a70405229a457d78aa456bb
[main 10:20:08 AM] update#setState idle
[main 10:20:08 AM] TypeError: Cannot read property 'length' of undefined
    at e.getRecentlyOpenedFromStorage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:378:354)
    at e.getRecentlyOpened (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:377:582)
    at e.insertRecentMenuItems (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:368:537)
    at e.setFallbackMenuById (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:365:925)
    at e.setFallbackMenuById (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:365:626)
    at e.install (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:361:76)
    at e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:359:218)
    at t.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:52:694)
    at e._createInstance (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:209:10)
    at e.createInstance (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:208:269)
    at e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:380:442)
    at t.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:52:694)
    at e._createInstance (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:209:10)
    at e._createAndCacheServiceInstance (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:209:957)
    at e._getOrCreateServiceInstance (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:209:147)
    at Object.get (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:207:794)
    at t.openFirstWindow (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:488:769)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:486:363
    at e.invokeFunction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:207:920)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:486:327
    at n.Class.define.cancel.then (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:91:201)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:486:246
    at n.Class.define.cancel.then (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:91:201)
    at t.startup (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:485:604)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:497:539
    at Object.v [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:572)
    at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:924)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:89:790)
    at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:89:231)
    at Server.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:170:657)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[main 10:20:08 AM] Lifecycle#kill()
[main 10:20:08 AM] telemetry/optInStatus { optIn: true }
```

**Comment by isidorn** [comment] 2018-07-30 18:44
Seems to be an null pointer when reading the recently opened list to populate the menu. Assigning to @sbatten 
There is a slight chance this the uri label work I did, but looking at the stack trace it looks like the menu.

**Comment by sbatten** [comment] 2018-07-30 21:55
@isidorn The second stack shows a crash in a function with no parameters passed from the menubar. Did your work affect the `HistoryMainService`?

**Comment by isidorn** [comment] 2018-07-31 13:29
@sbatten my work changed the `HistoryMainService` such that it now depends on the UriDisplayService. However this should not affect this error.

Stack trace 2 points the following:
The issue seems to be in the [`getRecentlyOpenedFromStorage`](https://github.com/Microsoft/vscode/blob/f35b6ce8d8a24f2dcf756d8bd6e2069dd4f25cc9/src/vs/platform/history/electron-main/historyMainService.ts#L248) - `storedRecents.workspaces` is undefined and that method was heavily changed with refactoring done by @sandy081 
Due to that also assigning to @aeschli and @sandy081 to investigate if the workspace path refactoring broke this as I believe.

Stack trace 1 points the following:
[Here](https://github.com/Microsoft/vscode/blob/f35b6ce8d8a24f2dcf756d8bd6e2069dd4f25cc9/src/vs/code/electron-main/menubar.ts#L540) you are passing a workspace which has a `configPath` `undefined`. This seems invalid

@mittalyashu can you please also attach your stack trace if you start vscode verbose as the other two users. Thanks a lot

**Closed** 2018-07-31 14:55 UTC
Labels: bug, important, workbench-menu

**Comment by mittalyashu** [comment] 2018-08-01 07:56
> stack trace if you start vscode verbose.

And, how to do that?

**Comment by mittalyashu** [comment] 2018-08-01 07:58
@aeschli, can we try downloading and installing the VS Code Insider (Users), due to this changes https://github.com/Microsoft/vscode/commit/77d90a9de6e5b81c74e5174f3260b62dbc9d5d99

**Comment by isidorn** [comment] 2018-08-01 13:15
The insiders from today should have a fix for this.
@mittalyashu @guiohm @pdfowler can you please verify if the issue is fixed for you? Thank you

**Comment by pdfowler** [comment] 2018-08-01 18:29
@isidorn Works for me! Many thanks! 🎉

**Comment by isidorn** [comment] 2018-08-02 09:57
@pdfowler great, adding verified label

**Comment by mittalyashu** [comment] 2018-08-02 10:04
The update works for me too.
