### ISSUE TITLE
Allow to rename untitled buffers

### ISSUE THREAD

**Issue by anothergituser** [Microsoft/vscode#50303] opened 2018-05-22 20:07 UTC
Hello,
Can new and unsaved files be renamed? For when you just need a throw away buffer for what ever and there's no reason to save it. It's difficult to remember what you had in there when all are named Untitled-1, 2, 3
Thanks.

**Comment by Cryonis** [comment] 2018-07-03 19:08
Is there any update to this feature? It would be immensely helpful for when you're dealing with a lot of scrap code.

**Comment by bpasero** [comment] 2018-09-13 05:52
Duplicate of https://github.com/Microsoft/vscode/issues/37414

**Closed by bpasero** 2018-09-13 05:52 UTC
Labels: feature-request, workbench-editors
