### ISSUE TITLE
Loaded scripts shows empty tree node

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31534] opened 2017-07-27 09:19 UTC
testing #31107

* debugging an extensions
* looking the tree and see an empty node (representing the root folder on my machine I believe)

<img width="409" alt="screen shot 2017-07-27 at 11 18 23" src="https://user-images.githubusercontent.com/1794099/28663357-6db0785a-72bd-11e7-8309-021c581b1790.png">

**Comment by weinand** [comment] 2017-07-27 09:21
most likely a duplicate of #31523

**Comment by weinand** [comment] 2017-07-28 13:27
Not a duplicate of #31523.
On unix and macOS the first segment of a path is '/' which results in an empty string when using a `path.split('/')`.

**Closed** 2017-07-28 13:29 UTC
Labels: bug, debug
