### ISSUE TITLE
Error: Unable to open 'Release Notes: 1.15.1': Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#33721] opened 2017-09-02 07:37 UTC
Error:

![visual studio code 2017-09-02 15 35 12](https://user-images.githubusercontent.com/3880497/29993817-7c2c96d0-8ff4-11e7-85d6-1c45f8443608.png)

Version:

![visual studio code 2017-09-02 15 37 07](https://user-images.githubusercontent.com/3880497/29993819-9aac238c-8ff4-11e7-98b8-064a9ade31cd.png)

**Comment by rcjsuen** [comment] 2017-09-02 20:26
Sounds like a duplicate of #22107.

**Comment by joaomoreno** [comment] 2017-09-04 07:46
Yeah, this was fixed in 1.10.

**Closed by joaomoreno** 2017-09-04 07:46 UTC
