### ISSUE TITLE
Interactive Playground "Cannot read property 'other' of null."

### ISSUE THREAD

**Issue by StrippedPenguin** [microsoft/vscode#95572] opened 2020-04-17 22:27 UTC
Issue Type: <b>Bug</b>

Hello there! I have recently downloaded this app and apparently it is unable to run (despiste it running before.) It produces the error message "'Interactive Playground': Cannot read property 'other' of null." I dont know why it produces this message, and it will not run/create files, producing similiar error messages

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.46GB (8.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chrmarti** [comment] 2020-04-20 10:54
Could you attach a screenshot? Is there anything in the dev console? (`Help` > `Toggle Developer Console`) Have you tried reinstalling?

**Comment by bpasero** [comment] 2020-04-20 14:24
This sounds like https://github.com/microsoft/vscode/issues/94931

**Comment by alexdima** [comment] 2020-04-24 21:05
@StrippedPenguin Can you please try using the [Insiders build](https://code.visualstudio.com/insiders/)? Does the Insiders build start up?

**Comment by alexdima** [comment] 2020-04-25 13:42
Duplicate of #94931. 

The workaround is to install [VS Code Insiders](https://code.visualstudio.com/insiders/) and then open the file at `C:\Users\[your-name]\AppData\Roaming\Code\User\settings.json` and remove any settings that were set to be `null`. Some people report that they have `"editor.quickSuggestions": null` in there. If that is the case, can you please comment here the list of extensions that you have installed? It appears that an extension might be mistakenly adding that to the `settings.json`.

**Closed** 2020-04-25 13:42 UTC
Labels: needs more info
