### ISSUE TITLE
TypeScript color issue without semicolon

### ISSUE THREAD

**Issue by pirix-gh** [microsoft/vscode#73549] opened 2019-05-09 21:15 UTC
- VSCode Version: 1.33.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

![Screenshot from 2019-05-09 23-09-11](https://user-images.githubusercontent.com/18401805/57487076-e77bbc00-72af-11e9-82c2-c053ab0bca3a.png)
![Screenshot from 2019-05-09 23-08-57](https://user-images.githubusercontent.com/18401805/57487077-e8145280-72af-11e9-86e3-dbf83fdd1528.png)

**JavaScript / TypeScript programming style supports semicolon-less, so should VS**

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by mjbvz** [comment] 2019-05-10 00:19
Please share the text of the code along with screenshots

**Comment by mjbvz** [comment] 2019-05-22 22:56
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/723

**Closed by mjbvz** 2019-05-22 22:56 UTC
Labels: needs more info
