### ISSUE TITLE
File has unexpected size (17609 != 17534). Mirror sync in progress: Version 1.87.0

### ISSUE THREAD

**Issue by scienmanas** [microsoft/vscode#207031] opened 2024-03-07 04:50 UTC
- VS Code Version: 1.87.0
- OS Version: Kali Linux 2024.1

Steps to Reproduce:

1.  On doing `sudo apt-get update` , this is what it appears

![image](https://github.com/microsoft/vscode/assets/99756067/58f1a5bc-a8e8-4b5b-bf90-8d825ae0bfad)

**Comment by levihuayuzhang** [comment] 2024-03-07 04:58
same here in Ubuntu 22.04.

```
Fetched 3,589 B in 2s (1,663 B/s)                       
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/repos/code/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (17609 != 17534). Mirror sync in progress? [IP: 198.18.0.13 443]
   Hashes of expected file:
    - Filesize:17534 [weak]
    - SHA512:360e0337f96e838bfcaed87271b59487225dc41ba4847e745c38bd47cab1765a84ecb7ebfd97ee5c01020063827e6620001015d7cd79b1a9da3d2d94565c844d
    - SHA256:c4a59335fd516d7c2e6013fba043142e4a46d8f149fb674f8067688f81d19724
   Release file created at: Tue, 05 Mar 2024 07:14:51 +0000
E: Failed to fetch https://packages.microsoft.com/repos/code/dists/stable/main/binary-armhf/Packages.gz  
E: Failed to fetch https://packages.microsoft.com/repos/code/dists/stable/main/binary-arm64/Packages.gz  
E: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by scienmanas** [comment] 2024-03-07 05:00
I think this happened because of some issue in recent update, @moderators pls look into it

**Comment by levihuayuzhang** [comment] 2024-03-07 05:02
Right, it has been more than 24 hours.

**Comment by deepak1556** [comment] 2024-03-07 06:59
Issue is in the publishing repo, assigning to you both.

**Comment by rzhao271** [comment] 2024-03-08 01:18
I'm unable to repro the issue with Ubuntu 22.04.
Let me know if the issue is still happening.

**Comment by scienmanas** [comment] 2024-03-08 05:30
I think, the issue is now resolved, there was some problem when get request was sent to update the vs-code, but now, I am also not encountering any error

**Closed** 2024-03-08 10:32 UTC
Labels: info-needed, upstream, linux, deb
