### ISSUE TITLE
💩💩 `import { log } from "console"` 💩💩

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#211025] opened 2024-04-23 06:21 UTC
Hi 👋

Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.88.1 (user setup)
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

https://github.com/microsoft/vscode/assets/44144724/3af04e2f-c561-4455-8845-98de9c330cf6

Get rid of the first suggestion in the list (I mean the second suggestion shown in the video that adds `import { log } from "console"`).

I hate it. It's annoying. Why does it even exist? No one uses it.

**Comment by doubaodoubao** [comment] 2024-04-23 08:01
hahahahah

**Comment by gjsjohnmurray** [comment] 2024-04-23 09:27
Looks like a duplicate of #179355 which @mjbvz originally closed as out of scope, then subsequently moved to Backlog but didn't reopen.

**Comment by babakfp** [comment] 2024-04-23 11:33
I found similar issues too: https://github.com/Microsoft/vscode/issues/49308, https://github.com/Microsoft/vscode/issues/51567, https://github.com/microsoft/TypeScript/issues/30471.

I don't know how this issue is going to be fixed by the vsCode team, however, what I know is, that `console.log` (without import) must be the first option by default! It's a built-in language thing, so I guess that can be a logical desition making this...

Workaround is adding this to vsCode config (find this from https://github.com/microsoft/vscode/issues/179355, Thank you @gjsjohnmurray):

```json
"editor.snippetSuggestions": "top",
```

However, I don't know how positive or negative this is going to affect DX in the future.

**Closed** 2024-04-23 17:42 UTC

**Comment by babakfp** [comment] 2024-04-23 22:03
This must also be an expected behavior too! LOL.

https://github.com/microsoft/vscode/assets/44144724/e425df60-ed73-429e-97ef-65699d69f3bb
