### ISSUE TITLE
Panels always on top in Gnome 3.20

### ISSUE THREAD

**Issue by echpiel** [Microsoft/vscode#5533] opened 2016-04-20 07:42 UTC
- VSCode Version: 1.0.0
- OS Version: Any Linux with Gnome 3.20 (tested with Arch Linux and OpenSUSE Tumbleweed, both up to date, Wayland deactivated)

Steps to Reproduce:

1. Install VS Code and open it.
2. Try to change focus to any other application or go to the Activities. See that only the title bar and menu are sent to the back, the panels stay on top.

The error must be an Electron one because Atom Editor shows the same behaviour. I am reporting it here because I can see the symptoms shown by VS Code and could not fill a proper bug report for Electron.

**Comment by bpasero** [comment] 2016-04-20 09:19
@echpiel please report this to Electron.

**Comment by echpiel** [comment] 2016-04-24 10:39
As I have explained in the linked Electron issue, I have been working on this issue and the report is wrong. I thought that I had ruled all the other possibilities before reporting the error, but finally it is related to Chromium 3D rendering inside Gnome 3.20 in my installation (specifically, I think the culprit is the display card driver). Disabling 3D rendering in Chromium works as a workaround. If I could disable it for VS Code, I would be able to use it until a fix is provided.

You can close the issue.

Best regards.

**Comment by bpasero** [comment] 2016-04-24 12:03
@echpiel it is fine to keep issues open here labeled as "upstream" so that we can keep track.

You say that you cannot disable 3d rendering in VS Code. Is this some flag we could expose to users? If so, can you provide guidance where this can be flipped in Chromium?

**Comment by echpiel** [comment] 2016-04-24 16:54
@bpasero Sorry if I was not specific enough. The hardware accelerated rendering can be deactivated in the Chromium browser, that uses the Chromium rendering engine. I know how to disable it in the Chromium browser (it is under the advanced options) but I do not know the connection with the Chromium rendering engine. So I cannot provide guidance about the Chromium rendering engine.

**Comment by BorisJineman** [comment] 2016-05-04 04:18
Hi team, I try to supplement some info about this issue, I also meet this issue in GNOMO 3.14 on debian VM ( in virtual box), the vscode's gui always on the top of the desktop, and obscure all other applications ( include terminal),,
I also try the latest vscode-insiders, the vscode can be launched successly, bu the UI of vscode-insiders cannot be shown( it will only shown a black area). after I disable the 3d feature of the VM, It works well.

Hope those info can help this issue,

Is there any way to get a previous version vscode deb release file?

**Comment by bpasero** [comment] 2016-09-18 07:13
I am closing this because I believe this is fixed, otherwise please report back. If you can reproduce I would appreciate if you could try to reproduce with our insiders build: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Closed by bpasero** 2016-09-18 07:13 UTC
Labels: bug, upstream
