### ISSUE TITLE
High CPU usage on MacOS after upgrading to March 2019 release (v1.33)

### ISSUE THREAD

**Issue by leantide** [Microsoft/vscode#71831] opened 2019-04-05 23:58 UTC
- VS Code Version: 1.33
- OS Version: macOS Mojave v10.14.3 

Steps to Reproduce:
1. Upgrade VS Code to March 2019 release
2. Observe very high constant CPU usage
3. Disable all VS Code add-ons
4. Continue to observe very high constant CPU usage

CPU usage is by electron_node tsserver.js under extensionHost.

Mitigation: 
Downgrade to VS Code Feb 2010 release. No more high CPU usage.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-04-06 00:54
Duplicate of #71751

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for workarounds

If that doesn't solve the issue for you, please let me know

**Closed by mjbvz** 2019-04-06 00:54 UTC

**Comment by leantide** [comment] 2019-04-06 01:09
Duplicate indeed. Clearing the automatic typings cache at ~/Library/Caches/TypeScript/3.4 resolved the issue for me. Thanks.
