### ISSUE TITLE
Default code formatter for JSON should not remove blank lines

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#91596] opened 2020-02-26 17:28 UTC
**Default** code formater for JSON removes blank lines. This is a pretty destructive behavior, and should be avoided by default. I am aware that I can install prettier for formatting JSON documents, but I do believe that the default should be conservative: I hit `ctrl+shift+I` automatically, and I don't want to install 3rd party tools/explicitly change config just to make my editor not to do bad stuff.

**Comment by aeschli** [comment] 2020-02-27 09:54
duplicate of #23260

**Closed by aeschli** 2020-02-27 09:54 UTC
