### ISSUE TITLE
Color highlight of JS gets confused after regex

### ISSUE THREAD

**Issue by neiljvr1** [microsoft/vscode#90881] opened 2020-02-18 12:23 UTC
Issue Type: <b>Bug</b>

create .js file with this content:

var myWindowsDriveLabel = "D:\\";
console.log("This is colour coded");
if (!/^[d-zD-Z]\:\\?$/.test(myWindowsDriveLabel)) {
  console.log("This is NOT colour coded anymore");
} 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment] 2020-02-19 02:14
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed by mjbvz** 2020-02-19 02:14 UTC
