### ISSUE TITLE
Failed to save 'thefilename': A system error occured (ENOTSUP: operation not supported on socket, fdatasync)

### ISSUE THREAD

**Issue by russgalloway** [Microsoft/vscode#10408] opened 2016-08-10 20:29 UTC
- VSCode Version:
VSCode Insiders - since August 9th build

- OS Version:
OS X 10.11.4, working with files in a VMware Fusion 8.1.1 hosted Windows 7 (6.1.7601) mounted volume

I know this is a strange setup, but it has worked nearly flawless for me for quite some time, and still works in the most recent standard VSCode edition as well as other editors such as Sublime Text 2 & 3.

Steps to Reproduce:

1. Using VMware Fusion, create a Windows 7 VM
2. Share a folder in Windows 7 containing text files
3. In OS X, mount the Windows shared folder as a volume (i.e. `cd /Volumes && mkdir /Volumes/winsrc && mount_smbfs //username@windowshostname/sharedfolder /Volumes/winsrc`)
4. Open the VSCode Insiders build from August 9th (or 10th) and open a file from the newly mounted volume.
5. Make a change to the file and save.
6. You should see the error: "Failed to save 'thefilename': A system error occured (ENOTSUP: operation not supported on socket, fdatasync)" -- (side note: "occured" is misspelled in the error text)

From what little related information I've been able to find, I suspect it might be an upstream issue with Electron and/or NodeJS, but I've been unable to track down the issue/forum post that led me to believe that was the case yesterday.

If there's anything else I can provide, please let me know.

Thank you all for all your incredibly hard work.  In a very short amount of time, VSCode has become my immediate go-to for all things text edit related and has been a pleasure to use since its first public release.

-Russ

**Comment by bpasero** [comment] 2016-08-11 05:59
@russgalloway thanks for reporting I know where to look for.

**Comment by russgalloway** [comment] 2016-08-11 19:09
@bpasero nadaprob -- glad to help any way I can!

**Comment by bpasero** [comment] 2016-08-12 05:06
@russgalloway pushed a fix, would be nice if you could try if the issue is solved from our insider update today.

**Closed** 2016-08-12 05:05 UTC
Labels: bug, important

**Comment by russgalloway** [comment] 2016-08-12 17:44
@bpasero the fix worked for me -- much appreciated 👍
