### ISSUE TITLE
Markdown: Hard-wrapped lines aren't lightlighed properly

### ISSUE THREAD

**Issue by john-cj** [microsoft/vscode#151113] opened 2022-06-02 14:51 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: win7

Steps to Reproduce:

1. Create the following Markdown file:
   ```
   **some text
   goes here**
   ```
2. Notice that text is not highlighed as it should be.

**Comment by mjbvz** [comment] 2022-06-02 16:45
Duplicate of https://github.com/microsoft/vscode-markdown-tm-grammar/issues/36

**Closed by mjbvz** 2022-06-02 16:45 UTC
