### ISSUE TITLE
Testing API: Allow custom height when contributing "test" views 

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode#185636] opened 2023-06-20 07:48 UTC
We at Playwright contribute a custom WebView view into the "test" section of VSCode. This looks like this:

https://github.com/microsoft/vscode/assets/17984549/e59b6522-bfdf-44b3-8005-9e958a135620

The issue is that our content there is larger than the default height of the view. So its scrollable.

Is it possible to set a minimum height somewhere? I found `InitialSize` on the view itself, not sure if its related or just not working.

This is what we do as of today:

https://github.com/microsoft/playwright-vscode/blob/95aabb062c42d647b910dad3107576a0e0694119/package.json#L89-L97

**Comment by alexr00** [comment] 2023-06-21 08:52
`initialSize` should work, though I don't know if the Test view container does anything special that would prevent it from working. @connor4312 maybe you would know.

`initialSize` only works until the user has resized the view though. So that is likely why you do not see an effect from it. 

We have a feature request here to have a "fit" option for the initial size, which I think this is a duplicate of: https://github.com/microsoft/vscode/issues/163043

**Closed by alexr00** 2023-06-21 08:52 UTC
