### ISSUE TITLE
Tasks.json option to overwrite build shell doen't work 

### ISSUE THREAD

**Issue by v-andrew** [microsoft/vscode#83117] opened 2019-10-23 00:56 UTC
- VSCode Version: 1.39.2
- OS Version: Windows 10

Steps to Reproduce:

1. Set default shell to `bash` so your build tasks fails as VSCode recently started passing incorrect build path to `bash`
2. Set a build shell which is different than default as you want to build your TypeScript project. `powershell` works.
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558 
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "windows": { // this is the only place where VSCode allows to add `windows`
        "options": {
            "shell": {
                "executable": "C:/Windows/System32/WindowsPowershell/v1.0/powershell.exe"
            }
        }
    },
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ],
            "group": "build",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": false
            },
            "windows": { // this is incorrect option suggested by person who closed issue, VSCode marks it with warning
				"options": {
					"shell": {
						"executable": "c:\\windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe"
					}
				}
			}
        }
    ]
}
```
3. Run build and see that it is using original shell, not one defined in `.vscode\tasks.json`

Does this issue occur when all extensions are disabled?: Yes

It is a repeat of incorrectly closed https://github.com/microsoft/vscode/issues/83021

https://github.com/microsoft/vscode/issues/83021#issuecomment-544836509 ans https://github.com/microsoft/vscode/issues/83021#issuecomment-544988734 **are not true**

When copied code to my `tasks.json` VSCode marked it as incorrect:
![image](https://user-images.githubusercontent.com/12078150/67346662-781c2080-f50d-11e9-9232-628a182b9923.png)

When I'm trying to build it doesn't affect my default shell set to `bash` and ignores option suggested by person, who incorrectly closed previous issue:
![image](https://user-images.githubusercontent.com/12078150/67346774-d0ebb900-f50d-11e9-8409-406dd6768c3b.png)

OS option is unavailable in Windows and MacOS at the level suggested. Here is screenshot on Mac:
![Screen Shot 2019-10-22 at 10 36 47 AM](https://user-images.githubusercontent.com/12078150/67347135-296f8600-f50f-11e9-8add-0bd85fff9298.png)
As you can see, there is no OS option at that level. The same behavior as on Windows.

**Comment by alexr00** [comment] 2019-10-23 08:03
duplicate of  #83021

**Closed by alexr00** 2019-10-23 08:03 UTC
