### ISSUE TITLE
Select and Start Debugging missing

### ISSUE THREAD

**Issue by cdacamar** [microsoft/vscode#116800] opened 2021-02-16 19:27 UTC
- VS Code Version: 1.53.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open directory with a simple .cpp file.
2. Add launch.json.
3. Add at least two configurations.
4. `ctrl+shift+P` (no option to select configuration).

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment] 2021-02-17 19:38
Duplicate of https://github.com/microsoft/vscode/issues/116299  Fixed in Insiders already.

**Comment by cdacamar** [comment] 2021-02-17 21:26
Are there any workarounds in the current released version?

**Closed** 2021-10-11 18:28 UTC
