### ISSUE TITLE
Smart Select no longer works in some languages/file types

### ISSUE THREAD

**Issue by ellielle** [microsoft/vscode#144427] opened 2022-03-04 18:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: Windows 10 Pro 10.0.19044

Steps to Reproduce:

1. Install the latest version of VS Code
2. Create a Vue single file component and attempt to smart select any text.

<details>
<summary>Expected Results</summary>

https://user-images.githubusercontent.com/40385743/156818452-ef9dcd1b-49dc-4eb3-8e02-699586df32a9.mp4

</details>

<details>
<summary>Actual Results</summary>

https://user-images.githubusercontent.com/40385743/156818694-d868442f-35bc-4258-986c-40c40f97f948.mp4

</details>

Smart Select works as intended when using 1.64.2

**Comment by tamuratak** [comment] 2022-03-05 02:24
Duplicate of #144370 and #144297

**Comment by ryanhsin0508** [comment] 2022-03-09 02:06
I can't expand selection in vue

**Comment by alexdima** [comment] 2022-03-09 08:52
I can reproduce in `.c` files. After using the insiders bisect, the commit range is pretty large: https://github.com/microsoft/vscode/compare/5554b12acf27056905806867f251c859323ff7e9...921264bfe3ffbbfe5ec8c4b08214b88e2148fa3e

**Comment by alexdima** [comment] 2022-03-09 09:19
After `git bisect`, 05a6debf1838c3b54ac36570392d0e8ac0fa739b is the first bad commit

**Comment by jrieken** [comment] 2022-03-09 09:20
/duplicate of https://github.com/microsoft/vscode/issues/144297

**Closed** 2022-03-09 09:21 UTC
Labels: *duplicate
