### ISSUE TITLE
Search large files

### ISSUE THREAD

**Issue by FarhangF** [Microsoft/vscode#21699] opened 2017-03-02 06:08 UTC
- VSCode Version: 1.10.0 insider
- OS Version: win 10

Steps to Reproduce:

1. create a large file like +100,000 lines
2. double click a word (-> locations will be marked in right scroll) -> issued
3. press ctrl+F (-> locations will be marked in different color) -> issued
 issue: markings in scroll or in the file will not continue after line 20,000 (or so)

i dont think attaching would be necessary. you got what i meant!

**Comment by alexandrudima** [comment] 2017-03-02 09:23
All the functionality is there, it is just the highlights stop after 1k. Duplicate of #496 , #1110

**Closed by alexandrudima** 2017-03-02 09:23 UTC

**Comment by FarhangF** [comment] 2017-03-02 09:30
Duplicate of #496 , #1110
https://github.com/Microsoft/vscode/issues/496
https://github.com/Microsoft/vscode/issues/1110

thanks to Alexandru Dima
