### ISSUE TITLE
Can start default build tasks many times

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#134430] opened 2021-10-05 09:11 UTC
1. Open our selfhost repo: microsoft/vscode
2. Press <kbd>Ctrl Shift B</kbd> twice very quickly

🐛 Sometimes you get 2 build tasks (normal), sometimes you get 3, if you're fast you can get 4:

![image](https://user-images.githubusercontent.com/22350/135994795-95e42de8-a84a-4c11-9039-c8937430aa2d.png)

**Comment by Tyriar** [comment] 2021-10-05 10:36
I believe this is a tasks issue, it could have been introduced as a result of `createTerminal` becoming async recently

https://github.com/microsoft/vscode/blob/d68d40ae8e36d0beb2c617ae1f15d0ce5f1ff04b/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L1207

**Comment by alexr00** [comment] 2021-11-11 15:49
Duplicate of https://github.com/microsoft/vscode/issues/118238

**Closed by alexr00** 2021-11-11 15:49 UTC
Labels: bug, tasks, terminal
