### ISSUE TITLE
Git view throws error: 'Path must be a string. Received null'

### ISSUE THREAD

**Issue by web-dave** [Microsoft/vscode#13496] opened 2016-10-11 11:56 UTC
- VSCode Version:1.6.0
- OS Version:Win 10 

Steps to Reproduce:

1.  Open Git view
2. select file to view changes
Popup errormessage says:
Path must be a string. Received null

**Comment by joaomoreno** [comment] 2016-10-11 14:14
I can't reproduce this. Do you have extensions installed? Does it reproduce with `--disable-extensions`?

**Comment by lrs** [comment] 2016-10-11 14:44
For me it was an issue with ESLint. After uninstalling the extension the error doesn't appear. 

However it wasn't the extension at fault: I had an old version (1.10.3) of the eslint node_module globally installed. After re-installing to version 3.7.1 the error stopped.

Needless to say, the error didn't appear for non JavaScript files.

**Comment by lrs** [comment] 2016-10-11 15:40
Just to be sure, I uninstalled ESLint and re-installed with `npm install -g eslint@1.10.3` and the error re-appeared.

**Comment by joaomoreno** [comment] 2016-10-11 16:11
cc @dbaeumer

**Comment by nguymin4** [comment] 2016-10-12 06:45
I have the same issue with vscode 1.6 with latest eslint@3.7.1 installed globally.
After that, I had to go back to vscode 1.5 and everything has been working just fine.

**Comment by dbaeumer** [comment] 2016-10-12 08:59
The problem is caused by the Electron update we did. This moved the node version we use up to 6.5.0 which throws if you call any path.* features with undefined / null. Old versions of node simply returned '' in this case.

Now if you have on old eslint version then eslint will call path.* feature with undefined hence causing this exception (surfaced via the ESLint extensions). The only way out is to use the latest eslint version which fixed this.

**Comment by nguymin4** [comment] 2016-10-12 09:05
- VSCode: 1.6
- OS: Ubuntu 16.04
- ESLint: **3.7.1**

Hi, like I commented earlier, with those I still have the error

**Comment by dbaeumer** [comment] 2016-10-12 09:09
@nguymin4 very strange. Can you enable eslint tracing to see from where we take the eslint version. I am pretty sure we find another version somewhere else before. You can enable tracing by adding the workspace setting `	"eslint.trace.server": "verbose"`. The go to the output panal and select the ESLint channel and provide the output here.

**Comment by nguymin4** [comment] 2016-10-12 09:26
```
[Trace - 12:25:43 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "inmemory://model/10",
        "languageId": "javascript",
        "version": 1,
        "text": "//Code here"
    }
}


[Trace - 12:25:43 PM] Received notification 'eslint/noConfig'.
Params: {
    "state": 3
}
```

**Comment by dbaeumer** [comment] 2016-10-12 09:53
Which version of ESLint extension are you on. The trace should look something like this.

 ```
[Trace - 11:49:19 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 13500,
    "rootPath": "p:\\mseng\\VSCode\\Playgrounds\\bugs\\13575",
    "capabilities": {},
    "initializationOptions": {
        "legacyModuleResolve": false,
        "nodePath": null
    },
    "trace": "verbose"
}


[Trace - 11:49:21 AM] 'npm config get prefix' value is: C:\Program Files\nodejs
[Trace - 11:49:21 AM] NODE_PATH value is: C:\Program Files\nodejs\node_modules
[Trace - 11:49:21 AM] Received response 'initialize - (0)' in 1635ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "codeActionProvider": true
    }
}


[Info  - 11:49:21 AM] ESLint server is running.
[Trace - 11:49:21 AM] Sending notification '$/setTraceNotification'.
Params: {
    "value": "verbose"
}


[Trace - 11:49:21 AM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "eslint": {
            "enable": true,
            "nodePath": null,
            "_legacyModuleResolve": false,
            "options": {},
            "trace": {
                "server": "verbose"
            },
            "run": "onType"
        }
    }
}


[Trace - 11:49:21 AM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///p%3A/mseng/VSCode/Playgrounds/bugs/13575/test.js",
        "languageId": "javascript",
        "version": 1,
        "text": "const tt = 'fff';\r\ntt=44;"
    }
}


[Trace - 11:49:21 AM] Received notification 'eslint/noConfig'.
Params: {
    "state": 1
}


[Trace - 11:49:21 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///p%3A/mseng/VSCode/Playgrounds/bugs/13575/test.js",
    "diagnostics": [
        {
            "message": "'tt' is defined but never used. (no-unused-vars)",
            "severity": 2,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 0,
                    "character": 6
                },
                "end": {
                    "line": 0,
                    "character": 6
                }
            },
            "code": "no-unused-vars"
        },
        {
            "message": "'tt' is constant. (no-const-assign)",
            "severity": 2,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 1,
                    "character": 0
                },
                "end": {
                    "line": 1,
                    "character": 0
                }
            },
            "code": "no-const-assign"
        }
    ]
}


[Trace - 11:49:21 AM] Received notification 'eslint/noConfig'.
Params: {
    "state": 1
}
```

Ensure that you have reloaded code after enabling tracing that the load of eslint is traced as well.

And can you please tun `node -p "require.resolve('eslint');"` from a terminal in the workspace folder showing the problem.

**Comment by nguymin4** [comment] 2016-10-12 10:21
I have the latest version of eslint extension
```
[Trace - 1:16:25 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 25487,
    "rootPath": "/home/nguymin4/test-app",
    "capabilities": {},
    "initializationOptions": {
        "legacyModuleResolve": false,
        "nodePath": "/home/nguymin4/Programs/NodeJS/lib/node_modules"
    },
    "trace": "verbose"
}


[Trace - 1:16:26 PM] 'npm config get prefix' value is: /home/nguymin4/.nvm/versions/node/v4.6.0
[Trace - 1:16:26 PM] NODE_PATH value is: /home/nguymin4/Programs/NodeJS/lib/node_modules:/home/nguymin4/.nvm/versions/node/v4.6.0/lib/node_modules
[Trace - 1:16:26 PM] Received response 'initialize - (0)' in 1440ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "codeActionProvider": true
    }
}


[Info  - 1:16:26 PM] ESLint server is running.
[Trace - 1:16:26 PM] Sending notification '$/setTraceNotification'.
Params: {
    "value": "verbose"
}


[Trace - 1:16:26 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "eslint": {
            "enable": true,
            "nodePath": "/home/nguymin4/Programs/NodeJS/lib/node_modules",
            "_legacyModuleResolve": false,
            "options": {},
            "trace": {
                "server": "verbose"
            },
            "run": "onType"
        }
    }
}


[Trace - 1:16:26 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/nguymin4/test-app/databases.js",
        "languageId": "javascript",
        "version": 1,
        "text": "'use strict';\n\nconst _ = require('lodash');"
    }
}


[Trace - 1:16:26 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "inmemory://model/6",
        "languageId": "javascript",
        "version": 1,
        "text": "'use strict';\n\nconst _ = require('lodash');"
    }
}


[Trace - 1:16:26 PM] Received notification 'eslint/noConfig'.
Params: {
    "state": 1
}


[Trace - 1:16:28 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/nguymin4/test-app/databases.js",
    "diagnostics": [
        {
            "message": "Strict mode is not permitted. (strict)",
            "severity": 1,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "code": "strict"
        }
    ]
}

[Trace - 1:16:28 PM] Received notification 'eslint/noConfig'.
Params: {
    "state": 1
}

[Trace - 1:16:28 PM] Received notification 'eslint/noConfig'.
Params: {
    "state": 3
}
```

**Comment by web-dave** [comment] 2016-10-12 10:44
I reinstalled eslint (3.7.1) now the error is gone.

**Comment by dbaeumer** [comment] 2016-10-12 12:10
@nguymin4 could you please also post the output of executing the command `node -p "require.resolve('eslint');"` in a terminal opened on the workspace that shows the problem

**Comment by nguymin4** [comment] 2016-10-12 12:33
The situation like this, I have a folder structure like `~/folder_a/folder_b`
In both of them there is `node_modules` folder with their owns `eslint` package inside.
So when I ran `node -p "require.resolve('eslint');` in `folder_b` the output is `~/folder_a/node_modules/eslint/lib/api.js`. Now I removed the `node_modules` in `folder_a` then the output is `~/folder_a/folder_b/node_modules/eslint/lib/api.js`.

However I did set `"eslint.nodePath": "/global_path_to_node_folder/lib/node_modules"` in user settings, so I just don't understand why the global `eslint` is not used

**Comment by dbaeumer** [comment] 2016-10-12 13:32
Actually I have no idea right now why the global eslint is not taken into consideration. It should looking at the NODE_PATH uses. Need to see how we can track this down further.

Just to double check: which version do you have installed in /home/nguymin4/Programs/NodeJS/lib/node_modules and which version in :/home/nguymin4/.nvm/versions/node/v4.6.0/lib/node_modules

**Comment by nguymin4** [comment] 2016-10-12 13:40
All global eslint versions are v3.7.1

**Comment by dbaeumer** [comment] 2016-10-14 12:17
Wait, we always prefer local version over global version (this is how node module lookup works). So which version do you have install locally in the workspace showing the problem?

**Comment by nguymin4** [comment] 2016-10-16 09:15
Yes, upgrade the eslint locally solves the problem. I just wonder why even though I set the `nodePath` in workspace setting to the global path, it doesn't work.

**Comment by lrs** [comment] 2016-10-16 13:32
Is it because you are just setting the global path if different from what's expected and local instances will always override regardless?

**Comment by nguymin4** [comment] 2016-10-16 13:41
I think because there is option `eslint.nodePath` so the checking order should be like
workspace settings => local node_modules => user settings => NODE_PATH

**Comment by lrs** [comment] 2016-10-16 13:47
Ah, gotcha - workspace settings should trump anything else.

**Comment by dbaeumer** [comment] 2016-10-17 18:39
@Irs agree. Can you please open an issue against vscode-eslint.

**Comment by lrs** [comment] 2016-10-18 09:32
#156

@nguymin4 This okay?

**Comment by nguymin4** [comment] 2016-10-18 10:20
@lrs It's okay. Thank you

**Comment by dbaeumer** [comment] 2016-10-25 11:06
Thanks. Closing this issue then.

**Closed by dbaeumer** 2016-10-25 11:06 UTC
Labels: bug
