### ISSUE TITLE
Can't open the second instance of VS Code when the first one with administration rights is launched

### ISSUE THREAD

**Issue by ArturGudiev** [microsoft/vscode#114802] opened 2021-01-23 00:09 UTC
- VSCode Version: 1.52.1
- OS Version: Windows 10, build 18363

Steps to Reproduce:

1. Open VS Code with administration rights (for example, using the powershell console with administration rights)
2. Try to open the second instance from the Windows menu (without administration rights) 
3. The second instance isn't launched. The following error is shown - "A second instance of Code is already running as administrator. Please close the other instance and try again".

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2021-01-23 01:04
Duplicate of #6560

**Closed** 2021-01-25 09:45 UTC
