### ISSUE TITLE
Function completion does not work across multiple cursors

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#5578] opened 2016-04-20 22:24 UTC
_From @sparrc on April 20, 2016 5:10_

First off, thanks for the great vscode plugin!

Here's a full dummy script to reproduce my problem:

``` go
package main

import "bytes"

func main() {
    var buf bytes.Buffer
    buf.WriteString("mystring")
    var mylen int
    if true {
        mylen = 8
    } else {
        mylen = 8
    }
}
```

steps are:
1. select the first `8`
2. ctrl+d or cmd+d to select both `8` variables
3. begin typing `buf.Le...` and wait for completion of `buf.Len()` to appear
4. select `buf.Len()` with tab or enter

When I do this, only the first of the `8` variables gets completed to buf.Len()

I'm on OSX using VSCode 1.0

_Copied from original issue: Microsoft/vscode-go#305_

**Comment by lukehoban** [comment] 2016-04-20 22:24
It appears this only happens for your repro steps if you have `"go.useCodeSnippetsOnFunctionSuggest": true`.  

In that case, the item you are selecting in the completion list is a snippet.  

It appears that when there are multiple cursorts, and a user tries to complete on a snippet, VS Code only inserts it in the first location.

That appears to be a bug/limitation in VS Code.  I'll move over to that repo.

**Comment by sparrc** [comment] 2016-04-20 23:56
thanks @lukehoban, here's my full user settings config for reference:

```json
// Place your settings in this file to overwrite the default settings
{
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,

    "diffEditor.renderSideBySide": false,
    "explorer.workingFiles.maxVisible": 12,

    "git.autofetch": false,

    "editor.rulers": [80],
    "editor.roundedSelection": true,
    "editor.wrappingColumn": 0,
    "editor.acceptSuggestionOnEnter": false,
    "editor.renderWhitespace": false,
    "editor.folding": false,
    "editor.quickSuggestionsDelay": 200,
    "editor.selectionHighlight": false,

    "files.trimTrailingWhitespace": true,
    "files.autoSave": "onFocusChange",
    "files.associations": {
        "*.sls": "yaml",
        "telegraf*.conf": "toml",
        "influxd*.conf": "toml"
    },

    "go.buildOnSave": false,
    "go.lintOnSave": false,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.formatOnSave": true,
    "go.formatTool": "gofmt",
    "go.gopath": "/Users/sparrc/ws/go",
    "go.gocodeAutoBuild": false
}
```

**Comment by dbaeumer** [comment] 2016-04-21 06:53
@alexandrudima not sure if this is you or @aeschli

**Comment by alexandrudima** [comment] 2017-03-01 17:33
fyi @jrieken

**Comment by jrieken** [comment] 2017-03-01 17:56
closing this as dupe of #16037

**Closed by jrieken** 2017-03-01 17:56 UTC
Labels: editor, feature-request, suggest
