### ISSUE TITLE
Gaps and overlaps in diff view modified line backgrounds

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#106297] opened 2020-09-08 16:16 UTC
As I scroll, sometimes the diff view background color blocks seem to have slight gaps or overlappings.

![image](https://user-images.githubusercontent.com/8586769/92501826-e31d2700-f1b3-11ea-8235-8e1b74346a2d.png)
![image](https://user-images.githubusercontent.com/8586769/92501867-f203d980-f1b3-11ea-853f-28f8dd34e210.png)

**Comment by usernamehw** [comment] 2020-09-08 16:46
If zoom is not default `0` then it's a duplicate of #85581

**Comment by JacksonKearl** [comment] 2020-09-08 16:57
@usernamehw thanks, just got a new monitor and changed some settings for it so I hadn't seen this before.

**Closed** 2020-09-08 16:56 UTC
