### ISSUE TITLE
Add a setting terminal.integrated.automationShellAgs.*

### ISSUE THREAD

**Issue by 10y** [microsoft/vscode#119391] opened 2021-03-20 20:46 UTC
- VS Code Version: 
1.54.2
fd6f3bce6709b121a895d042d343d71f317d74e7
x64
- OS Version: 
Windows 10 20H2

Steps to Reproduce:
1. make very special Linux shell setup under Windows 😂🔫
<pre>
"terminal.integrated.shell.windows": "C:/mingw64/bin/busybox.exe",
"terminal.integrated.shellArgs.windows": ["bash","-i"], // https://www.in-ulm.de/~mascheck/various/ash/#busybox
"terminal.integrated.env.windows": {"ENV":"$HOME/.profile"}, // read rc file https://linux.die.net/man/1/dash
</pre>

2. make package.json
```json
"scripts": {
"serv": "php -S dev.lo:5566"
}
```
3. "Run the script as a task"  or click ▶️ in NPM SCRIPTS view
![image](https://user-images.githubusercontent.com/16976424/111884479-2f96ba00-89c2-11eb-895b-33804ce22206.png)

```sh
> Executing task: pnpm run serv <

bash: can't open '/d': No such file or directory
The terminal process "C:\mingw64\bin\busybox.exe bash -i /d /c pnpm run serv" failed to launch (exit code: 2).

Terminal will be reused by tasks, press any key to close it.
```

# why is _vs code_ injecting those pesky `/d /c` flags?! I am obviously not running *cmd.exe* as shell!
and also I have found no way to set or change this behavior after intense research 😢 

4.  Bonus 🤪 "Run the script under the debugger" works flawlessly as expected in my configured shell setup
```bash
user@machine:C:/project/src $ pnpm run serv

> @ serv C:\project\src
> php -S dev.lo:5566

[Sat Mar 20 21:18:21 2021] PHP 7.4.16 Development Server (http://dev.lo:5566) started
```

# help🥺

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment] 2021-03-30 14:04
@zkxwpdam Tasks in VS Code doesn't really support using the level of indirection you have here (busybox.exe running bash.exe). Tasks looks at the shell you're using (busybox.exe) and tries to add the appropriate arguments. Since tasks doesn't support a shell called "busybox.exe", we default to the arguments we usually need for tasks running on Windows. 

Do you need to use busybox for you tasks? If not, then you could just set `"terminal.integrated.automationShell.windows": "bash.exe"` and be good to go.

**Comment by zkxwpdam** [comment] 2021-04-09 22:03
> @zkxwpdam Tasks in VS Code doesn't really support using the level of indirection you have here (busybox.exe running bash.exe). Tasks looks at the shell you're using (busybox.exe) and tries to add the appropriate arguments. Since tasks doesn't support a shell called "busybox.exe", we default to the arguments we usually need for tasks running on Windows.
> 
> Do you need to use busybox for you tasks? If not, then you could just set `"terminal.integrated.automationShell.windows": "bash.exe"` and be good to go.

@alexr00 First, thank you for your time looking into this.

Unfortunately, I cannot just set `"terminal.integrated.automationShell.windows": "bash.exe"`, since said bash.exe is absolutely not installed on my system!
I am specifically using busybox.exe's bash!

## Sadly, I ran into more problems caused by this defaulting shenanigans...

Debugging also broken!

E.g. **Run -> Start Debugging -> Python File** works totally fine the first time and opens a *1: Python Debug Console* with my "busybox bash" running the script.

But as I hit the "Restart 🔄" debugging, VS Code executes a totally bogus command in that console:
```
user@machine:C:/project1 $  c: && cd c:\project1 && cmd /C "C:\PATH_TO_PYTHON\pythonFiles\lib\python\debugpy\launcher 54768 -- c:\project1\script.py "
bash: c:: not found
``` 

What the heck  
This is completely unacceptable and a mindbogglingly bad way of shell implementation.

## May I suggest a solution:

To keep things easy on your end, keep all the default guessing🤷‍♀️

However also enable the user to explicitly set what should be returned from this guessing as default/fallback,
like a "compatibility mode", instead of breaking everything using a wrong default!

Some option along those lines
`"terminal.integrated.automationShell.windows.compatibility": "bash.exe"`
`"terminal.integrated.shell.windows.compatibility": "bash.exe"`

**Comment by alexr00** [comment] 2021-04-12 12:07
For this case then, can you modify your tasks.json to specify specific arguments? (If you don't already have a tasks.json, then run the Tasks: Configure Task command to create one):

```json
{
	"version": "2.0.0",
	"options": {
		"shell": {
			"args": ["-c"] // use whatever the equivalent of -c is for your shell.
		}
	},
}
```

I can also see this as a feature request to have a setting `terminal.integrated.automationShellAgs.windows`.

**Comment by thorn0** [comment] 2021-04-18 17:12
Duplicate of 96732

**Closed** 2021-04-19 09:30 UTC
Labels: *duplicate, feature-request, tasks
