### ISSUE TITLE
bug: console unicode problem

### ISSUE THREAD

**Issue by pandasjw** [Microsoft/vscode#13808] opened 2016-10-15 17:59 UTC
- VSCode Version: 1.6.1
- OS Version: macOS Sierra 10.12

Steps to Reproduce:
![image](https://cloud.githubusercontent.com/assets/11087172/19412218/a8c3acfa-9343-11e6-9f12-0cf1d6ecf5b6.png)

how should i fix this unicode problem, the font run well oh-my-zsh Item2.

**Comment by Tyriar** [comment] 2016-10-17 15:27
@pandasjw can you check the output of `echo $LANG`? This might be a duplicate of https://github.com/Microsoft/vscode/issues/13834

**Comment by pandasjw** [comment] 2016-10-18 02:05
![image](https://cloud.githubusercontent.com/assets/11087172/19461804/4c879f72-951a-11e6-94d8-e31431df6ceb.png)

It look like this.

**Comment by pandasjw** [comment] 2017-02-23 11:40
I got this problem, the name of agnoster theme had  problem , you should restore theme to d6a36b1 ```git reset --hard d6a36b1 ```
![image](https://cloud.githubusercontent.com/assets/11087172/23257682/da5dba76-f9ff-11e6-8a79-374bbbf23e07.png)
That's ok ~
@Tyriar

**Closed** 2017-02-23 17:26 UTC
Labels: integrated-terminal, needs more info
