### ISSUE TITLE
Interactive window cells auto-collapsing and not rendering errors correctly

### ISSUE THREAD

**Issue by Jakoviz** [microsoft/vscode#139610] opened 2021-12-21 12:06 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

A recent update to VS code insider or extensions changed the behavior of the interactive window as follows:
1) The output cells are always collapsed, although I have the "Jupyter: Collapse Cell Input Code By Default" checkbox unticked for both User and Workspace.
![image](https://user-images.githubusercontent.com/7263106/146925173-db04a7a1-9473-40ae-8ff5-c2d8344f998e.png)
2) When I expand the output cell I get:
![VSCodeJupyterError2](https://user-images.githubusercontent.com/7263106/146925475-507c19d9-1fe1-468a-83da-bf8e76569ddf.png)
in which what I have blacked out is my username on my machine.
3) If I press the three dots next to the cell and choose change presentation, I get
![image](https://user-images.githubusercontent.com/7263106/146925122-ce4ab40c-9217-4e16-8d81-ca7d16b214fa.png)
4) Selecting the top one makes no difference, but selecting the bottom one gives me what I expect:
![image](https://user-images.githubusercontent.com/7263106/146925833-017c46cd-1c4b-4254-ab61-6b7538514ea0.png)
This effect does not last though, but I need to do the whole procedure every time there is an error.

### VS Code Version

1.64.0-insider

### Jupyter Extension Version

v2022.1.100160240

### Jupyter logs

```shell
Info 13:54:26: Execute Cells request 0
Info 13:54:26: Execute Cell 0 vscode-interactive:Interactive-1.interactive
Info 13:54:26: Cancel all remaining cells true || Error
Info 13:54:26: Cancel pending cells
Info 13:54:26: Cell 0 executed with state Error
```

### Coding Language and Runtime Version

Python 3.9.7

### Language Extension Version (if applicable)

Python extension v2022.0.1589021501-dev

### Anaconda Version (if applicable)

Miniconda3 py39_4.10.3

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2021-12-22 00:47
@rebornix @roblourens This isn't a remote issue, however the renderers arent loading here

**Comment by kevingoh** [comment] 2021-12-22 19:08
have the same issue

**Comment by jaymegordo** [comment] 2022-01-11 05:05
I'm getting the error still very frequently, even after rolling back to 1.0.3

**Comment by rchiodo** [comment] 2022-01-11 17:35
This is a dupe of #139545. Hopefully fixed in today's insiders.

**Closed by rchiodo** 2022-01-11 17:35 UTC

**Comment by repied** [comment] 2022-01-13 18:34
I'd like to report the same problematic behavior of input cells being collapsed in Jupyter interactive window with regular vscode (not insider) while using the remote extension.

VScode 1.63.2
Jupyter Notebook renderer: issue with both 1.0.3 and 1.0.4
Jupyter Version: 2021.11.1001550889

After executing from a cell in a python file
![image](https://user-images.githubusercontent.com/15749663/149388803-146d8904-de7f-4b6a-b160-3fcfab9d42b0.png)

After double clicking, I see all the inputs

![image](https://user-images.githubusercontent.com/15749663/149388865-afe6b2b2-6f18-48ac-9774-41767ce17b5d.png)

**Comment by rchiodo** [comment] 2022-01-13 19:10
@repied that is by design. Interactive window cells are collapsed by default. 

This new setting (available in tomorrow's insiders VS code) allows you to disable this:

```json
"notebook.interactiveWindow.collapseCellInputCode" : "always"
```
You'd set it like so to have input code always expanded:
```json
"notebook.interactiveWindow.collapseCellInputCode" : "never"
```

**Comment by repied** [comment] 2022-01-14 12:53
Thanks,
Is there a way in current stable version to have input cells not collapsed by any chance? 
Setting   
`"jupyter.collapseCellInputCodeByDefault": false,`
is not changing anything (input cells are still collapsed).

**Comment by rchiodo** [comment] 2022-01-14 17:08
> Is there a way in current stable version to have input cells not collapsed by any chance?

Sorry there is no workaround. You need the new changes to be able to do so.
