### ISSUE TITLE
update 1.74.0 show this err

### ISSUE THREAD

**Issue by Zxxxxxl** [microsoft/vscode#168828] opened 2022-12-12 07:10 UTC
- VS Code Version:1.74.0 
- OS Version: macOS 12.6.1

Steps to Reproduce:

1.  open *.js file，show “Initializing js/ts language features”
2. open jsconfig.json
<img width="1014" alt="Snipaste_2022-12-12_15-00-16" src="https://user-images.githubusercontent.com/45777921/206982728-ee01f365-3039-4457-ac6f-4b5056eac19d.png">

**Comment by mjbvz** [comment] 2022-12-12 23:07
Duplicate of #168420

**Closed by mjbvz** 2022-12-12 23:07 UTC
