### ISSUE TITLE
I can pull the terminal at bottom of the editor area

### ISSUE THREAD

**Issue by linbingquan** [Microsoft/vscode#42695] opened 2018-02-01 02:11 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|1.13.2
debugger-for-chrome|msj|4.1.0
java|red|0.18.0
sonarlint-vscode|Son|1.2.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.I can pull the terminal at bottom of the editor area
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment] 2018-02-01 05:20
@linbingquan you'll need to provide more information on what the problem is. Do you have a screenshot showing it?

**Comment by linbingquan** [comment] 2018-02-01 07:59
@Tyriar I'm not sure it's a problem. Mouse pulls the integrated-terminal in this screenshot. 

![tim 20180201155131](https://user-images.githubusercontent.com/23699926/35667302-15e0868e-0768-11e8-915b-b499b1214d67.jpg)

**Comment by Tyriar** [comment] 2018-02-01 18:49
I think this is a feature 😄 

@isidorn

**Comment by isidorn** [comment] 2018-02-02 08:32
Haha yeah it is a feature
If more users find it confusing I will remove it. For now closing as-designed

**Closed by isidorn** 2018-02-02 08:32 UTC
Labels: workbench
