### ISSUE TITLE
IntelliSense doesn't work if I open a SVG file

### ISSUE THREAD

**Issue by abhagsain** [microsoft/vscode#79352] opened 2019-08-17 07:50 UTC
Issue Type: <b>Bug</b>

If I open a SVG file it used to show something about maximum line warning, but now intellisense don't work if I open a SVG file. 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-react-documentation|avr|1.2.1
turbo-console-log|Cha|1.2.31
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.4.3
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
remote-wsl|ms-|0.39.2
react-proptypes-intellisense|OfH|1.0.3
LiveServer|rit|5.6.1
autoimport|ste|1.5.3
highlight-matching-tag|vin|0.9.3
vscode-icons|vsc|9.2.0
vscode-wakatime|Wak|2.2.0
vscode-import-cost|wix|2.12.0
save-and-run|wk-|0.0.21

</details>

**Comment by octref** [comment] 2019-08-19 14:16
Duplicate of #66053.

**Closed by octref** 2019-08-19 14:16 UTC
Labels: new release
