### ISSUE TITLE
Git authentication failed, but it didn't ask for credentials

### ISSUE THREAD

**Issue by jungsunkyo1** [microsoft/vscode#137264] opened 2021-11-16 00:30 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: Ubuntu 20.04.3 LTS

Steps to Reproduce:

1.Source control -> Git(AWS codecommit, https) -> fetch or pull or push -> authentication failed (didn't ask for username/password)
2.In vscode Terminal -> git fetch or pull or push -> authentication failed (didn't ask for username/password)
3. Set git:Terminal authentication to  false -> In vscode Terminal -> git fetch or pull or push -> ask username / password

It happened suddenly after the version 1.62.2 update.

**Comment by adriandelgg** [comment] 2021-11-16 01:38
The way I solved it was by downgrading it to 1.62.1 & now it works perfectly again.

I'm on Linux, so this may not apply or work for you, but it should if all VS Code versions are the same across all OSs.

If you use openSUSE Tumbleweed like me, you can run the following command to downgrade:
$ sudo zypper in --oldpackage code-1.62.1

**Comment by Laethaka** [comment] 2021-11-16 04:26
`sudo apt install code=1.62.1-1636111026` also downgrades

**Comment by gjsjohnmurray** [comment] 2021-11-16 05:55
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Closed** 2021-11-16 05:56 UTC
Labels: *duplicate, new release
