### ISSUE TITLE
Code Helper running at >300% CPU when starting VS Code.

### ISSUE THREAD

**Issue by ariffinbaharum** [Microsoft/vscode#71262] opened 2019-03-27 07:06 UTC
- VSCode Version: 1.32.3
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Freshly installed VS Code with all extensions uninstalled.
<img width="563" alt="Screen Shot 2019-03-27 at 5 58 31 pm" src="https://user-images.githubusercontent.com/48778372/55056424-31bb2c00-50ba-11e9-9211-b818146ccffa.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment] 2019-03-27 11:38
Is VS Code configured to automatically open the same folder as last time?
Is this folder your home directory?

**Comment by ariffinbaharum** [comment] 2019-03-27 23:27
@weinand yes VS Code is configured to open my home directory.

**Comment by bpasero** [comment] 2019-03-28 06:53
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by songyule** [comment] 2019-04-01 10:07
Version:          Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS Version:       Darwin x64 18.2.0
CPUs:             Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)
Memory (System):  8.00GB (0.34GB free)
Load (avg):       2, 4, 4
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    5       90   91249  code main
    1       66   91250     gpu-process
    2      147   91251     window (_app.js — op-ui)
    0       25   91271       watcherService
   94       25   91272       extensionHost
    0       25   91303         electron_node server.js 
    0       25   91306         electron_node server.js 
    0       33   91367         electron_node tsserver.js 
    0       25   91383           electron_node typingsInstaller.js typesMap.js 
    0       25   91368         electron_node eslintServer.js 
    0       25   91369         electron_node tslintServer.js 
    0       25   91385         electron_node server.js 
    0       25   91686         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=91272
    0        0   91277       /bin/zsh -l
    0       16   91323         npm
    0       74   91324           node server.js
    0       25   91305       searchService
    0        8   92281       /bin/zsh -l
    1        0   92306         bash /usr/local/bin/code --status
   16       41   92316           electron_node cli.js 
    0       66   91273     shared-process
    0       16   91274     utility
    0       82   91489     window (BasicLayout.js — ant-design-pro)
    0       25   91490       watcherService
    0       33   91491       extensionHost
    0       25   91495         electron_node server.js 
    0       25   91499         electron_node server.js 
    0       33   91544         electron_node tsserver.js 
    0       25   91565           electron_node typingsInstaller.js typesMap.js 
    0       25   91547         electron_node eslintServer.js 
    0       25   91548         electron_node tslintServer.js 
    0       25   91564         electron_node server.js 
    0       25   91618         extensionHost
    0       25   91660         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=91491
    0       25   91497       searchService
Workspace Stats: 
|  Window (BasicLayout.js — ant-design-pro)
|  Window (_app.js — op-ui)
|    Folder (ant-design-pro): 302 files
|      File types: js(130) md(72) less(52) ts(33) json(2) yml(2) prettierrc(1)
|                  stylelintrc(1) ga(1) prettierignore(1)
|      Conf files: package.json(1)
|    Folder (op-ui): 116 files
|      File types: js(55) map(29) json(21) md(2) css(2) babelrc(1)
|                  eslintignore(1) gitignore(1) prettierignore(1) ico(1)
|      Conf files: jsconfig.json(1) package.json(1)

same as problem

**Comment by bpasero** [comment] 2019-04-01 13:36
@ariffinbaharum can you attach a screenshot from the process explorer (Help > process) when the CPU is high?

**Comment by matthamil** [comment] 2019-04-03 20:23
I also seem to be running into this problem. When I run the latest Insiders Build without any extensions, the Code - Insiders Helper spikes to ~20% CPU instead of >100%.

**Comment by bpasero** [comment] 2019-04-04 05:14
Ping

**Comment by vasilev-alex** [comment] 2019-04-06 11:02
Same issue after updating VSCode to the latest version

**Comment by bpasero** [comment] 2019-04-07 06:30
@ariffinbaharum can you attach a screenshot from the process explorer (Help > process) when the CPU is high?

**Comment by vasilev-alex** [comment] 2019-04-08 10:13
@bpasero I'm not @ariffinbaharum but as I have the same issue you may still be interested

<img width="1126" alt="vscode-cpu" src="https://user-images.githubusercontent.com/4973437/55716581-a2861080-59f7-11e9-9f21-4d94b5269a23.png">

**Comment by mjbvz** [comment] 2019-04-08 21:54
@vasilev-alex Please open a separate issue

Closing this one as we need more information from @ariffinbaharum

**Closed by mjbvz** 2019-04-08 21:54 UTC
Labels: freeze-slow-crash, typescript

**Comment by ariffinbaharum** [comment] 2019-04-09 22:59
@vasilev-alex @mjbvz Apologies for the late response. Have been away from the office for two weeks. It seems like the problem was that it happens only when I opened VS Code on my home folder. Otherwise, no.

**Comment by mjbvz** [comment] 2019-04-12 21:30
@ariffinbaharum Can you please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Please share the output of `code --status` to provide more information about your workspace and the cause of the perf issue
