### ISSUE TITLE
Clickable file paths in Debug Console.

### ISSUE THREAD

**Issue by lazyfingers** [Microsoft/vscode#41053] opened 2018-01-02 19:37 UTC
This would be a huge usability boost if file paths would be clickable:
i.e. filename:linenum:charnum

instead, I have to either cmd+p and type the filename:line myself or copy/paste the very line from the debug console.

**Comment by usernamehw** [comment] 2018-01-02 20:18
Duplicate of https://github.com/Microsoft/vscode/issues/27713 ?

**Comment by lazyfingers** [comment] 2018-01-02 21:14
Duplicate or not, this is an obvious usability upgrade. It can literally save a ton of time wasted on code navigation between the problematic code points via clicking/typing. But thanks for pointing that duplicate out!

**Closed** 2018-01-03 08:07 UTC
Labels: *duplicate, debug

**Comment by lazyfingers** [comment] 2018-01-03 09:38
"Happy Coding!", coding will be happier with a previously stated improvement :)
