### ISSUE TITLE
Two source control panes (One works fine, but the other shows nothing)

### ISSUE THREAD

**Issue by Biswas-N** [microsoft/vscode#106564] opened 2020-09-13 02:47 UTC
Issue Type: <b>Bug</b>

- VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
- OS version: Windows_NT x64 10.0.19041
Steps to Reproduce:

1. Source Control pane appears twice
2. One shows the expected file changes, but the other shows nothing

![VSCODE_ISSUE](https://user-images.githubusercontent.com/24390015/93009042-3e3d8800-f5bf-11ea-99d5-8b114335ede6.png)

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.51GB free)|
|Process Argv|--crash-reporter-id ed8ac75a-5bab-4432-89df-bc7a172b1f38|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.6.0
go|gol|0.16.2
vscode-nuget-package-manager|jmr|1.1.6
vscode-styled-components|jpo|0.0.31
sftp|lix|1.12.9
rainbow-csv|mec|1.7.1
vscode-language-babel|mgm|0.0.29
csharp|ms-|1.23.2
python|ms-|2020.8.108011
remote-wsl|ms-|0.44.5
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
LiveServer|rit|5.6.1
mdx|sil|0.1.0
vscodeintellicode|Vis|1.2.10
vim|vsc|1.16.0
gitmoji-vscode|Vtr|0.2.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2020-09-13 07:11
Are you certain that all extensions were disabled when you took that screenshot? Your status ba contains items that I don't recognise.

**Comment by Biswas-N** [comment] 2020-09-13 08:51
Sorry about that, I just checked it again after disabling all the extensions. And the problem seems to be solved. I will try activating all my extensions again to be sure.

**Comment by Biswas-N** [comment] 2020-09-13 08:55
Even after disabling all extensions, I am seeing two source control panes.

![DisabledExtensions](https://user-images.githubusercontent.com/24390015/93014209-7ca06a80-f5f2-11ea-9a86-a3f6f55c3c8c.png)

**Comment by sbatten** [comment] 2020-09-14 16:50
@Biswas-N can you right click next to the "Source Control" text in the empty pane and share the context menu that is shown? Same with right-clicking the icon?

**Comment by Ttou** [comment] 2020-09-16 08:07
same issue, the first one can't use

![WX20200916-160437](https://user-images.githubusercontent.com/4298437/93309888-a8ac2d80-f836-11ea-98d6-fc3be0ded1a1.png)

**Comment by Biswas-N** [comment] 2020-09-25 23:42
@sbatten with the latest update of VS Code (1.49.2 on Windows), this bug seems to be fixed.

**Comment by jdforsythe** [comment] 2020-09-28 18:30
I had the same issue (started with 1.49.1, I believe, as it's only been happening since last week), and upon upgrading to the newest update (1.49.2), the second Source Control tab also disappeared. The problem is, the one that disappeared was the only one that worked.

When there were two tabs, I noticed that when I right-clicked in the tab bar, there were two entries for Source Control - one with the keyboard shortcut listed (that's the one that had nothing inside it) and a duplicate (the one that actually listed the files).

Now after the update, the sole remaining Source Control tab has no files inside of it. I *can* right-click in the empty pane and turn on the "Source Control Repositories" option, which shows a single entry for the repository, but does not list any changed files. Now that I've turned on "Source Control Repositories", it is grayed out and I can no longer turn it off.

I did notice a new Source Control pane in the Explorer tab, which does work exactly as the old Source Control tab did, however I prefer using it in it's own tab.

**Comment by sbatten** [comment] 2020-09-28 18:54
@jdforsythe that is helpful. I'm not sure what the steps taken were to get you into this state, either bug in code or UX was unclear; however, you should be able to get into your desired state by right-clicking the `Source Control` view in `Explorer` and clicking `Reset Location`.

Let me know if this works for you.

**Comment by jdforsythe** [comment] 2020-09-28 19:11
@sbatten This did return the functionality to the Source Control tab. Thank you.

**Comment by sbatten** [comment] 2020-09-28 20:19
thanks @jdforsythe, i will close this issue as it seems the duplicate icon issue is resolved and hopefully our discussion will provide support for anyone seeing their view moved without knowing how to return it home

**Closed by sbatten** 2020-09-28 20:19 UTC
Labels: needs more info
