### ISSUE TITLE
Markdown Preview following a file rename errors on old filename.

### ISSUE THREAD

**Issue by james-cxx** [Microsoft/vscode#12033] opened 2016-09-14 16:50 UTC
- VSCode Version: 1.5.2
- OS Version:  Windows 7 Professional Service Pack 1

Steps to Reproduce:
1.  Rename a Markdown file in Explorer panel that is currently open in an Editor tab.  Note that the filename shown on the Editor tab is properly updated.
2.  With the Editor tab for the file selected, click the Preview button.

Result:  An error message is shown stating that the file (referring to the filename before it was renamed) cannot be opened.

**Comment by bpasero** [comment] 2016-09-15 04:55
I can reproduce.

**Comment by herecydev** [comment] 2017-04-03 17:58
Additional steps to reproduce:

1. Open markdown file
2. Ctrl+K V
3. Move file to subfolder
4. Begin modifying the markdown file
5. Observe that changes are not reflected

**Comment by mjbvz** [comment] 2018-04-27 22:46
This is fixed in current vscode builds because previews are now [dynamic](https://code.visualstudio.com/Docs/languages/markdown#_dynamic-previews-and-preview-locking) The preview is not updated if you locked it the file that is renamed

Furthermore, even if the preview's file is deleted on disk, we no longer error but keep the preview open until you close it

**Closed by mjbvz** 2018-04-27 22:46 UTC
Labels: bug, help wanted, markdown
