### ISSUE TITLE
Allow users to fold & expand imports

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#18571] opened 2017-01-15 15:54 UTC
Currently all versions of vscode does not have the ability to fold imports in typescript files.

It would make the code look much cleaner if the editor allows the ability to fold/expand the imports in languages such as typescript & java

**Comment by aeschli** [comment] 2017-01-19 10:02
duplicate of #3422

**Closed by aeschli** 2017-01-19 10:02 UTC
Labels: editor, editor-folding
