### ISSUE TITLE
When selecting reviewers based on filtered input, it's not possible to go back to the input field

### ISSUE THREAD

**Issue by daniel-montalvo** [microsoft/vscode#229811] opened 2024-09-09 08:58 UTC
Type: <b>Bug</b>

I've came across this on the reviewers list, there might be other lists affected, such as the assignees list.

With a screen reader running:

Open a PR on VS Code and navigate to the reviewers button.
Expand it with space or Enter.
Type a string to search for a specific person.
Then use the down arrow key to move to the first result.
Select it with space or Enter.
Then type a different string to search for a second person. You'd want to move back to the input field to write out a different string that filters the list

Expected behavior: Either the up arrow key or the tab key will eventually put focus back on the input field.
Obtained behavior: Neither of these put back focus on the input field. It's only screen reader's dedicated functionality to explore the sccreen (such as NVDA's navigator object) what eventually gets focus back to the input field.

This is important when dealing with large GitHub teams, where it's easier and more efficient to type out the first letters of a given person, then arrow down and press space or enter to select, then go back to the input field and repeat these steps as many times as needed to select several people on a list.

Extension version: 0.97.2024090514
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.74GB (49.18GB free)|
|Process Argv|--crash-reporter-id 5cd24c78-daef-41a6-93ba-9dfb6fafae88|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 0)|
|Memory (System)|31.22GB (29.02GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by daniel-montalvo** [comment] 2024-09-26 20:29
Thanks @alexr00  for looking into this!

**Comment by TylerLeonhardt** [comment] 2024-09-27 00:18
This is a duplicate of https://github.com/microsoft/vscode/issues/214053

**Closed by TylerLeonhardt** 2024-09-27 00:18 UTC
Labels: quick-pick
