### ISSUE TITLE
Cannot read property 'properties' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26636] opened 2017-05-15 06:15 UTC
Found this in my "running out of sources" log, I was clicking through extensions I had in that version, which may be related:

```
Cannot read property 'properties' of null: TypeError: Cannot read property 'properties' of null
    at ExtensionGalleryService.loadCompatibleVersion (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/platform/extensionManagement/node/extensionGalleryService.js:334:26)
    at ExtensionGalleryService.getAllDependencies (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/platform/extensionManagement/node/extensionGalleryService.js:329:25)
    at ExtensionsWorkbenchService.loadDependencies (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/extensions/node/extensionsWorkbenchService.js:418:40)
    at Cache.task (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/extensions/browser/extensionEditor.js:156:116)
    at Cache.get (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/cache.js:18:32)
    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/extensions/browser/extensionEditor.js:290:52
    at ExtensionEditor.loadContents (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/extensions/browser/extensionEditor.js:493:27)
    at ExtensionEditor.openDependencies (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/extensions/browser/extensionEditor.js:289:25)
    at ExtensionEditor.onNavbarChange (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/extensions/browser/extensionEditor.js:220:62)
    at CallbackList.invoke (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:58:43)
```

**Comment by sandy081** [comment] 2017-09-25 13:09
@bpasero Not able to reproduce it. May I know the extension on which you saw this error?

**Comment by bpasero** [comment] 2017-09-25 13:30
I can not reproduce here at work either, sorry.

**Comment by sandy081** [comment] 2017-09-25 13:47
Ok closing it for now. Please reopen it if you see again.

**Closed by sandy081** 2017-09-25 13:47 UTC
Labels: extensions, needs more info
