### ISSUE TITLE
Intra-document links in extension Readme are broken.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#17754] opened 2016-12-23 00:50 UTC
- VSCode Version: 1.8.1
- OS Version: OSX

Steps to Reproduce:
1. Find an extension that uses intra-document links in its Readme (e.g. 'vscode-lldb').
2. Click on one such link.

Instead of taking you to the link destination, VSCode displays HTML source of "webview.html".

-----

Related: https://github.com/Microsoft/vscode-vsce/issues/118

**Comment by joaomoreno** [comment] 2017-01-03 14:28
Duplicate of Microsoft/vscode-vsce#118

**Closed by joaomoreno** 2017-01-03 14:28 UTC

**Comment by vadimcn** [comment] 2017-01-03 17:11
Wait, this one is about VSCode itself, not the website.

**Comment by joaomoreno** [comment] 2017-01-04 08:10
It's the same underlying issue.
