### ISSUE TITLE
Incorrect latex preview in markdown

### ISSUE THREAD

**Issue by oponkork** [microsoft/vscode#130409] opened 2021-08-09 13:41 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Arch linux

Steps to Reproduce:

1. Open a new jupyter notebook.
2. Paste the following in a markdown.
```markdown
$$ \nabla P = \partial_{r} P \hat{r} + \frac{1}{r}\partial_{\theta} P  \hat{\theta} $$

$$
\nabla \mathbf{u} = \partial_{j}u_{i} = 
\begin{bmatrix}
    \partial_{1}u_1 & \partial_{2}u_1 \\
    \partial_{1}u_2 & \partial_{2}u_2 \\
\end{bmatrix}
=\frac{1}{r}
\begin{bmatrix}
     r \partial_r  u_r &  \partial_{\theta}  u_r -  u_{\theta} \\
     r \partial_r  u_{\theta} &  \partial_{\theta}  u_{\theta} +  u_r \\
\end{bmatrix}
$$

```
Preview output

![image](https://user-images.githubusercontent.com/58289453/128715316-2c4896a3-6dfc-4880-8a90-0eb5c9ccd759.png)

Expected output (from jupyterlab)

![image](https://user-images.githubusercontent.com/58289453/128715678-1beb7812-2399-4fa8-b76d-d99ea7eeca62.png)

**Comment by mjbvz** [comment] 2021-08-09 20:53
Duplicate of #128490

Please test in the latest VS Code insiders build

**Closed by mjbvz** 2021-08-09 20:53 UTC
Labels: new release
