### ISSUE TITLE
Split Terminal not working on Arch

### ISSUE THREAD

**Issue by yagehu** [Microsoft/vscode#63330] opened 2018-11-16 20:24 UTC
I have the same issue described in #62991. OP closed the issue, but the problem is still there.

To summarize, the default setting:

```
"terminal.integrated.splitCwd": "inherited",
```

breaks Split Terminal (Ctrl+\\). It seems to be only on Arch.

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- VSCode Version: 1.29.1
- OS Version: Arch Linux

Does this issue occur when all extensions are disabled?: Yes

**Comment by yagehu** [comment] 2018-11-18 04:23
Not only on Arch apparently:

https://github.com/Microsoft/vscode/issues/62991#issuecomment-439604667

**Comment by erdembircan** [comment] 2018-11-19 07:56
Hello _tmux_, my old friend...

**Comment by ytimenkov** [comment] 2018-11-20 05:15
Have same issue (CenOS). although #62991 is closed but the bug is still in 1.29.1 Terminal Split does nothing when `terminal.integrated.splitCwd` set to `inherited`.
Unfortunately there are no messages in the logs even when I set level to trace...

**Comment by erdembircan** [comment] 2018-11-20 06:17
On Arch. "terminal.integrated.splitCwd": "initial" worked for me.

**Comment by ytimenkov** [comment] 2018-11-20 06:21
Yes. Initial and workspaceroot work. Inherited doesn't.

**Comment by alexr00** [comment] 2018-11-20 09:33
Thanks for making sure we don't forget about this! Dupe of #62991.

**Closed by alexr00** 2018-11-20 09:33 UTC
Labels: new release
