### ISSUE TITLE
When entering snippets, allow autocomplete

### ISSUE THREAD

**Issue by ThinkSalat** [microsoft/vscode#91175] opened 2020-02-21 19:49 UTC
In snippets, it would be nice to allow autocomplete. At the moment, it doesn't have autocomplete or anything.

If it's because you the tab button is used to go to the next spot for input in the snippet, you could just make it so tab autocompletes if the autocomplete dialog is up, or goes to the next spot if it's not.

**Comment by ThinkSalat** [comment] 2020-02-21 19:56
Yes that's not related

**Comment by gjsjohnmurray** [comment] 2020-02-21 20:56
/duplicate of #89997, which points to the `editor.suggest.snippetsPreventQuickSuggestions` setting.

**Closed by gjsjohnmurray** 2020-02-21 20:56 UTC
Labels: *duplicate

**Comment by ThinkSalat** [comment] 2020-02-21 23:50
> /duplicate of #89997, which points to the `editor.suggest.snippetsPreventQuickSuggestions` setting.

Thanks!
