### ISSUE TITLE
Expand selection doesn't work in Golang

### ISSUE THREAD

**Issue by dodalovic** [microsoft/vscode#144370] opened 2022-03-04 06:57 UTC
When I invoke 
![image](https://user-images.githubusercontent.com/6358061/156714630-95ab7e0f-c03e-4021-b0b0-b333714b71dd.png)
nothing happens.

Works in Java, Rust, etc.

Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:36.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.11-76051611-generic

**Comment by tamuratak** [comment] 2022-03-04 09:35
Duplicate of  #144297. This is not specific to Go language.

**Comment by eqinox76** [comment] 2022-03-04 16:14
This feature has been working fine for at least 2 years with .go files. 
In version 1.65.0 (snap version  b5205cc8 2022-03-03) it stopped working for .go files but still works fine in .json and similar simple files.
Former version 1.64.2 ( snap version f80445ac) works fine. The go language plugin is unchanged.
Any idea why?

**Comment by dodalovic** [comment] 2022-03-04 17:24
Even worse - `yaml` doesn't work either.

**Closed** 2022-03-07 10:44 UTC
Labels: triage-needed
