### ISSUE TITLE
Bump `applicationinsights`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#135360] opened 2021-10-19 08:00 UTC
When I open dev tools of shared process, I am always greeted with these warnings:

```
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/DataPoint.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/DataPointType.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Envelope.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/EventData.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/ExceptionData.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/ExceptionDetails.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/MessageData.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/PageViewData.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/MetricData.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/RemoteDependencyData.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/RequestData.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/SeverityLevel.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/TelemetryType.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Declarations/Contracts/Generated/StackFrame.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/AutoCollection/RequestParser.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Library/CorrelationIdManager.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/AutoCollection/HttpRequests.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/AutoCollection/HttpRequestParser.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Library/NodeClient.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Library/Config.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Library/TelemetryClient.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Library/Context.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Library/Channel.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/TelemetryProcessors/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Library/Sender.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/TelemetryProcessors/SamplingTelemetryProcessor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/node_modules/applicationinsights/out/Library/EnvelopeFactory.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Even in stable. Makes me wonder if something broke with source map generation. This seems to be specific to the application insights module though.

//cc @joaomoreno

**Comment by joaomoreno** [comment] 2021-12-02 19:49
Actually this is a "new" problem. @aeschli introduced it here: https://github.com/microsoft/vscode/commit/975408db6b4d8601b050341c8fc73233d5f42607

**Comment by joaomoreno** [comment] 2021-12-02 19:56
And the problem is specific to the `applicationinsights` module:

- All their JS files have a source map footer
- But they ship no sourcemap files at all 🤷

**Comment by joaomoreno** [comment] 2021-12-02 19:58
This is a dupe of https://github.com/microsoft/ApplicationInsights-node.js/issues/523. Which was closed in 2019. Which points to the fact that we should probably bump `applicationinsights`.

Moving it to you @lramos15: maybe we update to the latest `applicationinsights` version in early December?

**Comment by lramos15** [comment] 2021-12-03 13:58
@joaomoreno The downside to updating app insights is that they don't really support us which means we have a hacky workaround to suppress a different warning. Read https://github.com/microsoft/vscode/issues/129727 to see what we must do for the `vscode-extension-telemetry` module

**Closed** 2021-12-07 16:50 UTC
Labels: engineering
