### ISSUE TITLE
Cannot attach to worker threads (node 11)

### ISSUE THREAD

**Issue by sbalko** [microsoft/vscode#67484] opened 2019-01-18 10:21 UTC
VSCode's node debugger cannot attach to node 11's "worker threads". Our debug configuration is this:

```
   {
        "type": "node",
        "request": "launch",
        "name": "Mocha Tests",
        "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
        "runtimeArgs": [
            "--experimental-wasm-threads",
            "--experimental-worker"
        ],
        "args": [
            "-u", "tdd",
            "--timeout", "100000",
            "--colors", "${workspaceFolder}/test"
        ],
        "internalConsoleOptions": "openOnSessionStart",
        "autoAttachChildProcesses": true
   }
```

We use worker threads over sub processes in order to pass a SharedArrayBuffer to the worker thread and have it as a [shared memory](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) with the main node thread.

**Comment by DrPizza** [comment] 2019-03-26 14:29
FWIW, as of 11.7.0, Workers are no longer behind an experimental flag, they're on by default (albeit still with experimental-level stability).

**Comment by gauravmahto** [comment] 2019-07-14 07:59
I know it is a lot to ask. But it would be a great feature to support.
Let's say if I want to work on this then where should I start from?  Any help would be much appreciated.

**Comment by roblourens** [comment] 2019-10-07 18:36
/duplicate of https://github.com/microsoft/vscode-chrome-debug-core/issues/529

**Closed** 2019-10-07 18:36 UTC
Labels: *duplicate, debug, feature-request
