### ISSUE TITLE
Code interferes with long(ish)-running 'git rebase' from CLI

### ISSUE THREAD

**Issue by nwgh** [Microsoft/vscode#5661] opened 2016-04-22 16:07 UTC
- VSCode Version: 1.0.1-insider (85f337ee0851a464d5459ce9a354d05f94f0b9a4)
- OS Version: OS X 10.11.4 (15E65)

Steps to Reproduce:

1. Have code open with git enabled on a repository (in particular, I'm working with @mozilla/gecko-dev)
2. Do a `git rebase -i` that will take a while (my case had 11 commits that I was squashing into 1)

A few times during the rebase, my rebase stopped because it couldn't create index.lock, saying it already existed. If I then did `git rebase --continue` things would carry on. (FTR, git also totally messed up the squashing in this case, but that's a git bug, not a code bug.) I realized that code's git integration was interfering with my rebase, quit code, `git reset --hard` to the original commit, and redid my rebase, and everything worked fine. My best guess is that the periodic `git status` (or similar) that code does was racing with the various commits of `git rebase`, and when code won, it would mess up the rebase. Code should probably avoid updating its internal knowledge of the working directory status while a rebase (or similar) is running. (Not sure if that's entirely possible, but it's at least something to think about.)

**Comment by joaomoreno** [comment] 2016-04-25 06:47
Thanks for the details, you are absolutely right!

Duplicate of #901

**Closed by joaomoreno** 2016-04-25 06:47 UTC
Labels: git
