### ISSUE TITLE
quickOpen - parse args variables (keybind)

### ISSUE THREAD

**Issue by dimateos** [microsoft/vscode#210064] opened 2024-04-10 14:51 UTC
Atm `workbench.action.quickOpen` does not parse arguments like ${selectedText}. Given that is quite a powerful command it would be nice to at least parse selected text. This would allow something like the following to trigger quick search:

    {
        "key": "ctrl+shift+alt+f",
        "command": "workbench.action.quickOpen",
        "args": "%${selectedText}" // does not work
    },

Other possibility is to work on https://github.com/microsoft/vscode/issues/140136 and parse all variables before executing the command. This would solve https://github.com/microsoft/vscode/issues/82306, https://github.com/microsoft/vscode/issues/151311... many open issues.

> Given the relevance of  `workbench.action.quickOpen` I thought it might be worth at least parsing the args for it for the time being. But close this issue at your discretion.

Best regards!

**Comment by TylerLeonhardt** [comment] 2024-04-10 17:23
Couple things:
* The latest version of quick search does what you want to set up: it takes the selected text, and put it in the query:
```json
{
    "key": "ctrl+shift+alt+f",
    "command": "workbench.action.experimental.quickTextSearch"
}
```
* I don't want to do this handling of variables just for this one command so I'd rather see https://github.com/microsoft/vscode/issues/140136

making as dupe of https://github.com/microsoft/vscode/issues/140136

**Closed by TylerLeonhardt** 2024-04-10 17:23 UTC
