### ISSUE TITLE
[regression] re-saving an open file that was deleted does not remove the (deleted) marker

### ISSUE THREAD

**Issue by asklar** [microsoft/vscode#113781] opened 2021-01-04 21:26 UTC
- VSCode Version: 1.51.1
- OS Version: Windows 10 21265

Steps to Reproduce:

1. open a file in vscode
2. delete the file outside vscode. Note that vscode correctly shows a the string "(deleted)" in the tab name.
3. re-save the file. The tab title does not get updated.
4. Switch to another tab and then back, the tab title gets updated.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment] 2021-01-05 08:40
Can someone else try to reproduce?

**Comment by bpasero** [comment] 2021-01-06 16:39
![recording](https://user-images.githubusercontent.com/900690/103795309-1bd7ea80-5046-11eb-82d1-f2d5f6cc2961.gif)

Does not reproduce for me.

**Comment by asklar** [comment] 2021-01-06 19:19
![vscode_refresh](https://user-images.githubusercontent.com/22989529/103810951-f54b8c80-5010-11eb-828f-a30cbb40c46d.gif)

**Comment by bpasero** [comment] 2021-01-07 06:41
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jeanp413** [comment] 2021-01-07 11:29
This happens for a file that is outside of the currently opened workspace folder, in the above gift `package.json` is in a parent folder of the `MidIRT` workspace folder

**Comment by bpasero** [comment] 2021-01-07 12:54
Ah thanks for clarifying. Yes, we currently do not detect when a file comes back for files outside of the workspace because that would mean we had to watch pretty much the entire disk. But I pushed a fix to clear the "deleted" upon successful save.

**Closed** 2021-01-07 12:54 UTC
Labels: bug, workbench-editors
