### ISSUE TITLE
History using typed editors results in issues when navigating

### ISSUE THREAD

**Issue by gautams3** [microsoft/vscode#138452] opened 2021-12-04 22:51 UTC
Issue Type: <b>Bug</b>
Video (screen capture) reproduction :movie_camera:  [here](https://drive.google.com/file/d/1LoDyhfvtHvLMlSHr2wxEdmC9fABl37HS/view?usp=sharing).

1. Create new terminal
2. Move terminal to editor area, 
3. Drag terminal to the right, creating new editor group
4. Back to edited file on the left editor group
5. Move back in navigation history (Menu Go -> Back)
6. Notice that you see the terminal in both panes, only one of them is rendering the bash prompt
7. Show the terminal tab in both editor groups, then close the terminal that doesn't display the bash prompt. Note that it affects the terminal in the other pane

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.11.0-41-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz (20 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.07GB (21.73GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 9db08de4-effc-4a5c-a76c-fa3625c55e01|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
LogFileHighlighter|emi|2.13.0
copilot|Git|1.7.4016
latex-workshop|Jam|8.22.0
rainbow-csv|mec|1.10.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
postscript|mxs|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30405811
vscop804cf:30404767
vscop341:30404997
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by Tyriar** [comment] 2021-12-06 19:40
This also happens with custom editors:

![image](https://user-images.githubusercontent.com/2193314/144911156-d323cb54-37da-4d95-97ac-3bf366e22363.png)

**Comment by Tyriar** [comment] 2021-12-06 20:25
Can get even more broken, not sure how I did this but the webview switched sides, I closed it and was left with a tabless editor group with a webview still present:

![image](https://user-images.githubusercontent.com/2193314/144917062-1255dcbf-7165-481a-bb33-17ab82f675a6.png)

**Comment by lramos15** [comment] 2021-12-06 20:28
Yeah I can repro these. @bpasero any chance this was caused by the splitting custom editors that can't be split work?

@Tyriar I see something even more annoying but only for terminal editors which is I can't drag them to new groups
![recording (1)](https://user-images.githubusercontent.com/4544166/144917600-99d4bf79-ddaf-4231-8500-594a150301bd.gif)

**Comment by bpasero** [comment] 2021-12-07 06:25
@lramos15 I think the underlying issue here is that in the history component we have some logic to decide whether an entry to the history stack is added as `IUntypedEditorInput` or `EditorInput`. Looks like terminals end up being stored as `EditorInput` and then when `openEditor` is called, we `singlePerResource` instruction is not applied (I suppose), because no editor is resolved.

Btw this is much easier to reproduce:
* open terminal to the side
* focus the left side
* open quick open
* select the terminal
* 🐛  terminal opens in the current group and shows the same issue

I am not entirely sure, but is terminal editor fit for being used as untyped editor? That would be a pre-req to fix this. I.e. we should only have untyped resource inputs when terminals open, not typed terminals.

**Comment by Tyriar** [comment] 2021-12-07 15:03
@lramos15 thanks for letting me know, created https://github.com/microsoft/vscode/issues/138603 and https://github.com/microsoft/vscode/issues/138601

**Comment by bpasero** [comment] 2021-12-14 08:57
Turns out this is a regression from a change I did earlier where we would no longer reveal an editor if it was opened in a different group. Surprised this was not reported by users earlier (or maybe I missed it).

With https://github.com/microsoft/vscode/commit/6c89a38cfcc8d6ae4b4804302b709f5256e4a02b#diff-abb838672aa73d278824d84d0706f4292632f526fd898d216c590696a10ddf4aR405 we go back to opening an editor through editor service respecting the `revealIfOpened` flag. This flag makes sure that when you navigate in history, we always prefer to open the editor that is opened in any group before making an attempt to open it in the active group.

**Closed** 2021-12-14 09:05 UTC
Labels: bug, workbench-history, confirmed, terminal-editors
