### ISSUE TITLE
Editor Sticky Scroll highlighting does not kick in after reload

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#201728] opened 2024-01-03 16:25 UTC
Reproduce:
1. Open a file and scroll to a location where sticky scroll appears in the editor
2. Reload Window
3. See that sticky scroll highlighting does not kick in until the user scrolls

<img width="908" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/15ce8cc9-fe07-4b83-9e8d-853ba5eb6439">

**Comment by benibenj** [comment] 2024-01-12 13:06
I've also seen it happen without reloading. I think this is an important bug to fix before it's released as on default.

**Comment by aiday-mar** [comment] 2024-01-17 10:36
This issue appears to be a duplicate of https://github.com/microsoft/vscode/issues/201728. This issue will be closed in favor of the other issue.

**Closed by aiday-mar** 2024-01-17 10:36 UTC
Labels: bug, important, editor-sticky-scroll
