### ISSUE TITLE
Back and Forward on the mouse stopped working

### ISSUE THREAD

**Issue by LukaszGrela** [microsoft/vscode#76959] opened 2019-07-09 09:05 UTC
Issue Type: <b>Bug</b>

With the latest update the back/forward button on my mouse that I've used to navigate in the code.

Open the VSCode, navigate to definition then try to use back button on the mouse to come back - it doesnt work. the shortcur ALT+LEFT works.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-eslint|dba|1.9.0
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.2
prettier-vscode|esb|1.9.0
todo-tree|Gru|0.0.138
react-native-snippet|jun|0.5.2
vscode-postcss-sorting|mrm|3.0.1
vsliveshare|ms-|1.0.488
vscode-jest|Ort|3.0.2
stylelint|shi|0.51.0
vscode-todo-highlight|way|1.0.4
glean|wix|4.11.0

</details>

**Comment by gjsjohnmurray** [comment] 2019-07-09 09:23
/duplicate of #71318 and will be fixed in upcoming recovery release

**Closed** 2019-07-09 09:23 UTC
Labels: editor-contrib
