### ISSUE TITLE
Can't collapse the code of .js file in the 1.24 and 1.25 version

### ISSUE THREAD

**Issue by hankaibo** [Microsoft/vscode#53827] opened 2018-07-09 03:11 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10 Pro N 1803

Steps to Reproduce:

1.
![_20180709110907](https://user-images.githubusercontent.com/5361465/42428869-938d6936-8368-11e8-9013-129cd3a84126.png)

2. I can't collapse in the red box.

Can you help me?
thanks!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roshad** [comment] 2018-07-09 03:31
woo secret codes.

**Comment by aeschli** [comment] 2018-07-10 10:36
@hankaibo Can you paste a sample code that shows the problem?

**Comment by hankaibo** [comment] 2018-07-12 09:17
``
I use voscode.
![_20180712171418](https://user-images.githubusercontent.com/5361465/42624060-0a6f8512-85f7-11e8-9e6f-9273363672b6.png)
On the left is my plugins,right is my code.
In version 1.23, I can collapse in the red box, but not work now.

**Comment by mjbvz** [comment] 2018-07-16 19:45
Duplicate of https://github.com/Microsoft/TypeScript/issues/23273

Should be fix in insiders when using TS 3.0+

**Closed by mjbvz** 2018-07-16 19:45 UTC
Labels: needs more info
