### ISSUE TITLE
Feature Request: Horizontal split in addition to the vertical split

### ISSUE THREAD

**Issue by Xoph** [Microsoft/vscode#9443] opened 2016-07-18 14:59 UTC
I am submitting a feature request here, because the page to do feature requests does not work (https://visualstudio.uservoice.com/forums/293070-visual-studio-code).

My feature request is for a horizontal split in addition to a vertical split. Currently, you can only view tabs next to each other, but I'd like to be able to view them top and bottom. This would be especially helpful when you have files that have really long lines of code.

**Comment by kieferrm** [comment] 2016-07-21 01:05
Duplicate of #1749.

**Closed by kieferrm** 2016-07-21 01:05 UTC
Labels: duplicate

**Comment by eddiemonge** [comment] 2016-11-17 23:17
This is not a duplicate issue. #1749 was implemented as "Horizontal split instead of vertical split". This is "in addition to". Thus not a duplicate. @kieferrm

**Comment by tgalkowski7ninjas** [comment] 2016-11-28 18:03
Yes, I would also love this feature.

It would look something like:

```
=====================
|         |         |
|         |         |
|         |---------|
|         |         |
|         |         |
=====================
```

Instead of:
```
=====================
|                   |
|                   |
|-------------------|
|                   |
|                   |
=====================
```

It's not a duplicate. Hope my awesome ASCII art helps to see the difference. :D

**Comment by avoliva** [comment] 2016-12-06 01:10
I support this

**Comment by Kluskey** [comment] 2017-02-02 19:22
@kieferrm Any update since this is **not** a duplicate of #1749? @tgalkowski7ninjas describes the differences well, as you can see a number of other people support and agree with. Atom does this feature well and I think it's a big selling point for coders, who often use multiple monitors with split views.

**Comment by Justus-Maier** [comment] 2017-02-09 12:11
Yes, please implement mixed/grid splitting!
For now as, a workaround, one can use two windows of VS Code beside eachother with horizontal splitting to achieve a grid or mixed split views - but this has other navigation downsides.

**Comment by andfaulkner** [comment] 2017-02-22 05:01
Seconding what @Kluskey, @Justus-Maier @tgalkowski7ninjas, and @eddiemonge have said: this is not a duplicate of #1749.

This is in fact one of the main reasons I haven't switched from Sublime to Visual Studio Code.

**Comment by kieferrm** [comment] 2017-02-22 21:31
Thanks for the feedback. I'll keep this on closed in favor of #14909. Please have a look there and let us know if it's not covering what you expressed here.

**Comment by cdelorme** [comment] 2017-03-01 14:31
Was trying out vscode on a 21:9 monitor, and wish for this feature as well.

**Comment by yosefrow** [comment] 2017-03-29 11:39
This is one of the only features that I would miss if I left Sublime or Atom and is keeping me from using VSCode

**Comment by Viskazz** [comment] 2017-04-04 20:38
I'm very agree with this request. I'm bassicaly use Atom, it's came with this grid functionality from the box. But i want to jump to VS Code, because i have a 27'' inch monitor and want to use it on 100%. I'm wonder why this in not implemented yet.

**Comment by f3rno** [comment] 2017-04-21 21:01
+1 guys, this is a no-brainer. Any self-respecting code editor needs to support grid splits.

**Comment by basicBrogrammer** [comment] 2017-04-28 20:09
This is the only thing keeping me from using VS Code

**Comment by Dazing** [comment] 2017-06-04 08:24
Miss this too!

**Comment by Ribhu-** [comment] 2017-08-14 06:26
Need this.

**Comment by churcho** [comment] 2017-08-14 21:09
Can't stress enough how much I NEED this feature. Window management becomes such a breeze.

**Comment by gyansoft786** [comment] 2017-08-17 09:21
hmm....

**Comment by Dogyunjeong** [comment] 2017-08-28 03:14
+1  I hope it will come soon to us

**Comment by basicBrogrammer** [comment] 2017-09-12 19:27
So no update to this?

**Comment by VincentPuget** [comment] 2017-09-15 09:43
+1

**Comment by slaby93** [comment] 2017-09-18 09:30
+1

**Comment by gh378684988** [comment] 2017-09-19 08:00
+1

**Comment by marcosomma** [comment] 2017-09-21 09:34
+1

**Comment by azoni** [comment] 2017-09-21 16:12
+1

**Comment by techcrewe** [comment] 2017-09-21 18:45
Yep, wanted here too!

**Comment by tamowicz** [comment] 2017-09-23 16:57
yup, bring it on! should be as easy as setting `flex-direction: column`..

**Comment by Bat-Orshikh** [comment] 2017-09-25 06:41
+1.

**Comment by samumist** [comment] 2017-09-26 02:46
+1

**Comment by derekyau** [comment] 2017-09-26 21:01
+1

**Comment by deividasjackus** [comment] 2017-09-28 11:39
+1

**Comment by marinhero** [comment] 2017-09-28 19:38
+1

**Comment by dk0r** [comment] 2017-10-03 14:29
+1

**Comment by KevinHurts** [comment] 2017-10-10 14:39
+1

**Comment by SystemR** [comment] 2017-10-11 03:35
+2e10

**Comment by dolebas** [comment] 2017-10-11 09:44
+1

**Comment by dolebas** [comment] 2017-10-11 09:48
Try this: 
ALT+SHIFT+1 PC (Windows, Linux)
⌘+⌥+1 Mac
https://stackoverflow.com/questions/40709351/vscode-how-to-split-editor-vertically

**Comment by jnicholls** [comment] 2017-10-12 14:58
+2e500

**Comment by potaty** [comment] 2017-10-16 03:40
+10086

**Comment by kelvinadhoc** [comment] 2017-10-16 21:53
+1 as well

**Comment by phaberest** [comment] 2017-10-19 11:17
We need something like https://github.com/SublimeText/Origami

+1

**Comment by JediMarcinC** [comment] 2017-10-22 07:47
+1

**Comment by sr-ix** [comment] 2017-10-23 16:50
+1

this is not a duplicate

**Comment by achen0115** [comment] 2017-10-26 04:02
+1

**Comment by seriousManual** [comment] 2017-11-03 11:41
+1

**Comment by kevinye1** [comment] 2017-11-03 16:26
+1

**Comment by alphawaseem** [comment] 2017-11-03 17:17
while(!gridLayoutSupported){
    +1
}

**Comment by DavidLyhedDanielsson** [comment] 2017-11-04 16:14
+1, this feature would be great to have on monitors larger than full-HD!

**Comment by iamchriswick** [comment] 2017-11-06 03:44
Still my #1 reason for not changing from Atom to VS Code :(

**Comment by OktayGardener** [comment] 2017-11-08 09:55
What's going on with this situation? Could the team at least hit us with a reply if you guys are working on this, if not, why? VSCode is seriously a lifesafer and I love it, but I can't be splitting 3by3, I need more.

**Comment by y-usuzumi** [comment] 2017-11-09 03:36
This thread is dead. Let's open 10 more issues on this.

**Comment by basicBrogrammer** [comment] 2017-11-13 18:52
Well now that i started using spacemacs with Magit ... Someone would have to implement Magit in Vscode for me to make a switch 😁  But y'all should really push for this. So Basic. I'd plus one for the cause 👍

**Comment by RyanBryce** [comment] 2017-11-14 06:57
+1

**Comment by rick-schubert** [comment] 2017-11-16 10:05
I would support such a feature! :)

**Comment by y-usuzumi** [comment] 2017-11-16 10:22
![2017-11-16 18-11-17](https://user-images.githubusercontent.com/1560189/32885799-90675a28-caf9-11e7-9bef-461c03e8c76c.png)
