### ISSUE TITLE
redirecting test results output to file instead of debug console

### ISSUE THREAD

**Issue by guillermooo** [Microsoft/vscode#416] opened 2015-11-21 17:08 UTC
VS Code test results are output to the debug console in VS Code. Is it possible to intercept the output being printed to the console or to redirect the test output to a file?

This would allow for running the test suite for extensions in a CI environment. The CI in question can run windowed processes.

**Comment by bpasero** [comment] 2015-11-23 07:13
dupe of #118

**Closed by bpasero** 2015-11-23 07:13 UTC
