### ISSUE TITLE
Support for Angular 2 special selectors in CSS

### ISSUE THREAD

**Issue by Tsmith18256** [Microsoft/vscode#15695] opened 2016-11-18 05:59 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:
1. Open a new SCSS or CSS file
2. Attempt to add a selector that uses [Angular 2's special selectors](https://angular.io/docs/ts/latest/guide/component-styles.html#!#special-selectors)
3. Observe that VS Code considers this syntax an error.

An example selector would be: 
```
/deep/ .my-class {
  width: 0.75em;
  height: 0.75em;
}
```

Not only does it consider the `/deep/` to be an error, but it also gets really confused and marks other errors on the colon of `height: 0.75em;` and the closing brace.

**Comment by kpaxton** [comment] 2016-11-18 13:29
This is not just specific to Angular 2. This is for Web Components Support. The actual /deep/ attribute is deprecated and should instead use CSS3 Variables and @apply.   

https://www.polymer-project.org/1.0/blog/2015-12-01-deprecating-deep

**Comment by kpaxton** [comment] 2016-11-18 13:38
Found a CSS3 editors draft on the @apply rule and mixins.
https://tabatkins.github.io/specs/css-apply-rule/

**Comment by aeschli** [comment] 2016-11-22 20:11
duplicate of #14999

**Closed by aeschli** 2016-11-22 20:11 UTC
