### ISSUE TITLE
Hide code blocks completely

### ISSUE THREAD

**Issue by AravK** [Microsoft/vscode#22293] opened 2017-03-09 13:09 UTC
Please hide code blocks like this:
`void foo(string name) {`
`   printf(name.c_str());`
`}`
TO
`void foo(string name) { ... }`
NOT
`void foo(string name) { ...`
`}`

**Comment by aeschli** [comment] 2017-09-06 10:01
duplicate of #3352

**Closed by aeschli** 2017-09-06 10:01 UTC
Labels: editor-folding, feature-request
