### ISSUE TITLE
React app azure deployment

### ISSUE THREAD

**Issue by Rohanfulzele** [microsoft/vscode#147090] opened 2022-04-08 14:38 UTC
Issue Type: <b>Bug</b>

##React App Azure Deployment not Working

When I am trying to build and deploy my React app using the VS Code Azure extension, then the deployment starts but never ends.

Tried multiple times but had no luck.

Can someone help me out here ?? ( VS code version - 1.66.1 )

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.78GB free)|
|Process Argv|--folder-uri file:///d%3A/DCR/P360DCR --crash-reporter-id c1667f61-be73-4825-b4dc-6479104c5c20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.6
es7-react-js-snippets|dsz|4.4.3
vscode-great-icons|emm|2.1.85
prettier-vscode|esb|9.5.0
azure-pipelines|ms-|1.202.0
vscode-azureappservice|ms-|0.23.1
vscode-azurefunctions|ms-|1.6.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.4.1318
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.21.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.6
vetur|oct|0.35.0
LiveServer|rit|5.7.5
cors-browser|Wsc|1.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by IllusionMH** [comment] 2022-04-08 15:00
Looks like duplicate of #146470 do you see same error?

**Comment by Rohanfulzele** [comment] 2022-04-08 15:29
Yes, kinda same. 

I have now tried downgrading the VS code version. Then it worked for me.

**Comment by IllusionMH** [comment] 2022-04-08 15:42
Please follow that issue for updates, will close this one as duplicate.

/duplicate

**Closed** 2022-04-08 15:42 UTC
Labels: *duplicate, new release
