### ISSUE TITLE
The terminal cannot display characters normally

### ISSUE THREAD

**Issue by meowao** [microsoft/vscode#119401] opened 2021-03-21 06:09 UTC
![1)T2IDPSD~(@~$NPCGZO__H](https://user-images.githubusercontent.com/13918627/111895781-cb223c00-8a4f-11eb-9917-424ac17a359c.png)

Issue Type: <b>Bug</b>

The terminal cannot display characters correct

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6402P CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.54GB free)|
|Process Argv|--crash-reporter-id 72b97092-876d-404f-a2ba-551f3f338a8a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meowao** [comment] 2021-03-23 04:40
same problam #119409

**Comment by meganrogge** [comment] 2021-03-29 17:06
Duplicate of #119409

**Closed** 2021-03-29 17:06 UTC
Labels: *duplicate, integrated-terminal
