### ISSUE TITLE
Extensions view/editor should have a open settings editor for that extension

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#70959] opened 2019-03-22 14:12 UTC
As part of https://github.com/Microsoft/vscode/issues/41882#issuecomment-475281706 we open the extensions viewlet with the intention that user disable/configure formatter extensions. Disablement is already very prominent but there is no configure-link from an extension. 

The idea is to: 

* have a `configure...`-action in the context of an extension - @sandy081
* have a way to open the settings editor so that it only shows the settings of an extension (this is similar to `@id:my.ext` and the extensions viewlet) - @roblourens

<img width="1075" alt="Screenshot 2019-03-22 at 15 07 45" src="https://user-images.githubusercontent.com/1794099/54828419-6c852480-4cb4-11e9-94a1-c69aea9e4cfe.png">

**Comment by jrieken** [comment] 2019-03-22 14:16
cc @aeschli

**Comment by sandy081** [comment] 2019-03-22 16:56
Duplicate of https://github.com/Microsoft/vscode/issues/25012

**Comment by roblourens** [comment] 2019-03-22 17:20
I don't think it's a duplicate of #25012. That one is about editing settings inside the extension tab. @jrieken suggests that we add a filter mode for extensions and open the real settings gui with a link from the extension page. I think that's a good idea, and #25012 should probably be closed.

**Comment by sandy081** [comment] 2019-03-25 08:04
@roblourens #25012 also talks about the same as we concluded to open the settings editor from the extensions editor - https://github.com/Microsoft/vscode/issues/25012#issuecomment-424073078

It was confusing because of the summary. Will update it.

**Closed by sandy081** 2019-03-25 08:04 UTC
Labels: extensions, feature-request
