### ISSUE TITLE
Consider moving entries in search view into overflow by default

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228953] opened 2024-09-18 13:48 UTC
Default state:

![Image](https://github.com/user-attachments/assets/da056350-b232-4714-996c-56d5d8cddc9d)

![Image](https://github.com/user-attachments/assets/2ed22527-275a-46d0-85de-ebc98cf56b45)

To reduce complexity, I think we should hide the less important items into an overflow. For example this:

![Image](https://github.com/user-attachments/assets/a01b6fca-c1e3-4c87-a8d1-19ee8db4b0bd)

Or:

![Image](https://github.com/user-attachments/assets/1b89673b-e6ff-4880-ac9f-fa037d7b0da9)

**Comment by andreamah** [comment] 2024-09-23 23:25
Makes sense. It sort of messes with muscle memory, though. I wonder if there's a way that we can customize what goes there, sort of like the icons near the markdown preview icon. 🤔

**Comment by Tyriar** [comment] 2024-09-24 15:15
I wouldn't want to remove them outright, I'm suggesting just like in the terminal view that there are some hidden entries by default:

![Image](https://github.com/user-attachments/assets/33539848-01b2-4e62-809d-9e3ec0659f2b)

Some of these were popular requests (clear/run) that I refused to show by default due to the noise, some were added to increase discoverability (scroll). So a user that wants them can right click to add them back, but the default user who probably doesn't want to use them or very rarely does, will get a simpler UI.

This is done via the `isHiddenByDefault` flag I added:

https://github.com/microsoft/vscode/blob/1e80dd664a0e5346012ebe4097a3d32079ac050c/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1011-L1019

**Comment by daviddossett** [comment] 2024-09-24 21:41
I'd be happy to have fewer icons there by default too. `Clear Search Results` and `Collapse All` feel like must-haves. The others not so much but that could just be my usage.

**Comment by andreamah** [comment] 2024-09-24 23:44
We could explore this. Maybe hiding the tree/list toggle and also the refresh.

**Comment by osortega** [comment] 2024-12-18 22:41
Duplicate of https://github.com/microsoft/vscode/issues/188781
Closing this one in favor of the older one

**Closed by osortega** 2024-12-18 22:41 UTC
Labels: search, polish
