### ISSUE TITLE
Settings GUI

### ISSUE THREAD

**Issue by shreyas-a** [Microsoft/vscode#12079] opened 2016-09-15 13:58 UTC
Provide GUI for settings.

**Comment by mrmlnc** [comment] 2016-09-15 14:00
Duplicate of #3355.

**Closed** 2016-09-15 14:17 UTC

**Comment by shreyas-a** [comment] 2016-09-15 14:18
Hello, I would also like to contribute to the code base. How can I get started. Can you help.

**Comment by mrmlnc** [comment] 2016-09-15 14:26
You can use this instruction: https://github.com/Microsoft/vscode/wiki/How-to-Contribute
