### ISSUE TITLE
Search symbol

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#47071] opened 2018-04-02 04:55 UTC
Issue Type: <b>Bug</b>

Does not work when no files are open, I have to open a .ts file before symbols are shown.

1. Press: CMD + T
2. Type a symbol name

Nothing shows up.

![screen shot 2018-04-02 at 12 52 55 am](https://user-images.githubusercontent.com/439226/38183663-38811416-3610-11e8-9d83-403460b355bc.png)

3. Open a .ts file do the same and symbols show up.

![screen shot 2018-04-02 at 12 53 59 am](https://user-images.githubusercontent.com/439226/38183679-5a563580-3610-11e8-9e8d-88c8cab6eb89.png)

4. Also it would make sense to display symbols from the project at the top first before those from other libraries of npm modules.

VS Code version: Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:10:29.002Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
ng-template|Ang|0.1.9
vscode-markdownlint|Dav|0.14.1
EditorConfig|Edi|0.12.1
vsc-material-theme|Equ|1.5.1
material-icon-theme|PKi|3.2.6
sort-lines|Tyr|1.5.0
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.28
sort-typescript-imports|mic|1.4.1
angular2-inline|nat|0.0.17
npmsmartimporter|ref|3.0.0
language-stylus|sys|1.9.1
vim|vsc|0.11.3
better-align|wwm|1.1.6
markdown-pdf|yza|0.1.8

(8 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-04-02 22:12
Thanks. Duplicate of #17022

**Closed by mjbvz** 2018-04-02 22:12 UTC
Labels: insiders
