### ISSUE TITLE
Product icon for debug-stackframe-dot is not overwritten by designated icon in product icon theme

### ISSUE THREAD

**Issue by DeltaRazero** [microsoft/vscode#208343] opened 2024-03-21 23:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Windows_NT x64 10.0.22621 (Windows 11 Professional)

Steps to Reproduce:

1. Create a product icon theme that replaces the product icon with identifier `debug-stackframe-dot`
2. Load product icon theme
3. Start debug session in a file/language with debugger support (e.g. Python)
4. The icon is not replaced. In developer tools I can see that the CSS property for `content` is incorrect (it uses the default VSCode product icon font and the font glyph content ID) as well as that the `font-family` property is not set.

---

I am in the middle of making a product icon theme and I happened to notice the described behaviour.

Either the documentation at https://code.visualstudio.com/api/references/icons-in-labels is (no longer?) incorrect or the logic to replace this icon is not present. All the other debug and debug-stackframe icons seem to be working just fine.

**Comment by daviddossett** [comment] 2024-03-22 17:26
cc @hbons who has been working on icons. This might not be a trivial change for design to make though. Possibly @aeschli can advise re: icon theme logic?

**Comment by DeltaRazero** [comment] 2024-03-24 12:08
@connor4312 I've found some two more icons that are not (properly) replaced. Would you like me to edit the issue or create a new issue? Would it be of any value to provide the icon theme replacing the icons in question and a small repo to generate it for further validation?

**Comment by aeschli** [comment] 2024-03-25 10:30
The problem is here: https://github.com/microsoft/vscode/blob/c115d644bb7ae916d19d9ff9e6d4bb39b7261b0d/src/vs/workbench/contrib/debug/browser/media/debug.contribution.css#L39

this hardcoded fontCharacter prevents the icon from being themable.

**Comment by sandy081** [comment] 2024-04-16 00:05
Reopened as the fix is reverted

**Comment by connor4312** [comment] 2024-04-16 00:10
This was re-merged

**Closed by connor4312** 2024-04-16 00:10 UTC
Labels: bug, debug

**Comment by aeschli** [comment] 2024-04-25 10:52
This doesn't work yet as the the fix uses `circleSmallFilled` instead of `debugStackframeDot`
I created #211334, PR #211335
