### ISSUE TITLE
A blocking process freezes entire ide.

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#11805] opened 2016-09-09 22:35 UTC
- VSCode Version:`1.5.1`
- OS Version:`ubuntu 16.4`

Steps to Reproduce:
1. execute a script with long for or something blocks the process 
2. in a native terminal the loop will not freeze the terminal  and stream the output of the loop however in vscode this process freezes the entire ide not even just terminal so you cannot even terminate the terminal without terminating entire vscode which can cost serious data loss in an unsaved workspace

**Comment by Tyriar** [comment] 2016-09-10 06:11
@NikosEfthias is this only happening with a large amount of output? I believe this is due to a perf regression when the scroll bar was introduced.

If this is like the past performance issue then the keystrokes probably are being sent to the terminal, it's just taking too long for the renderer to catch up.

**Comment by NikosEfthias** [comment] 2016-09-10 19:02
this is only happening with a large loop without any pause doing something something like 
```bash
a=1
while [[ true ]] 
 do echo $((a++))
done
```
this will freese the entire ide however in xterm it does not have any issue printing values and receiving interrupts

**Comment by Tyriar** [comment] 2016-09-11 00:55
xterm seems so snappy because it syncs the renderer with the shell process. A PR done to xterm.js (https://github.com/sourcelair/xterm.js/pull/146) to do this, however the a side effect of it was that it took an enormous amount of time to print all the output due to each page of data having to be replicated in the DOM and displayed. Improvements to performance are still being explored in https://github.com/sourcelair/xterm.js/issues/134 and https://github.com/sourcelair/xterm.js/issues/150

**Comment by NikosEfthias** [comment] 2016-09-11 07:46
can't puttting small delay between each node creation help something like 10 ms is difficult to feel as a user i think

**Comment by Tyriar** [comment] 2016-09-12 02:53
@NikosEfthias currently I think there's max 30 updates to the DOM per second, but all that text still needs to be processed. So the scroll bar added in 30 scroll events a second in addition to everything else which I'm guessing was enough to lock it up.

**Comment by Tyriar** [comment] 2016-12-31 22:18
Should be fixed by https://github.com/sourcelair/xterm.js/pull/438 :fireworks:

**Comment by Tyriar** [comment] 2017-01-20 03:49
Fixed with all the performance improvements made this version, Insiders should be silky smooth. https://github.com/Microsoft/vscode/issues/17875

**Closed by Tyriar** 2017-01-20 03:49 UTC
Labels: freeze-slow-crash, integrated-terminal
