### ISSUE TITLE
feature request: add a TM_FILENAME_BASE and TM_FILENAME_EXT or similar variables for snippets

### ISSUE THREAD

**Issue by dmccaffery** [Microsoft/vscode#25173] opened 2017-04-22 06:03 UTC
- VSCode Version:

```sh
$ code --version
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
```

- OS Version:

```sh
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195
```

Feature Request:

Currently, the TM_FILENAME includes the extension and their is no way to strip this within a snippet. For snippets such as those that insert a class definition in languages where the file name is conventionally relevant to the class / module / function within, it would be great to get access to the filename with the extension stripped.

I can't think of a scenario with the filename extension is relevant, honestly, but if you're going to split the string on the first occurrence of a `.`, you might as well join everything to the right of that dot and have a var for that as well. :)

**Comment by jrieken** [comment] 2017-04-27 15:19
Transformations is what we need. Closing as dupe of #6920

**Closed by jrieken** 2017-04-27 15:19 UTC
Labels: feature-request, snippets
