### ISSUE TITLE
Cannot copy and paste from/to a webview's iframe

### ISSUE THREAD

**Issue by mrmeku** [Microsoft/vscode#68799] opened 2019-02-15 19:39 UTC
- VSCode Version: all
- OS Version: all

Steps to Reproduce:

1. Create a webview with an iframe in it. It can point to http://localhost:8080
2. Create an http server to serve from http://localhost:8080. It can serve an `index.html` file with the text 'copy me'
3. Try to load the iframe in the vscode webview. The text will appear. 
4. Try to copy the text
5. Try to paste the text. The text wasn't copied

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment] 2019-02-15 19:54
Duplicate of #65452

**Closed by mjbvz** 2019-02-15 19:54 UTC
Labels: editor-clipboard
