### ISSUE TITLE
Incorrect CodeLens position when using Mouse Wheel Zoom

### ISSUE THREAD

**Issue by Brandon-Gui123** [microsoft/vscode#96891] opened 2020-05-04 03:48 UTC
**EDIT:** My apologies for not disabling all extensions first before attempting this. So I launched VS Code with all extensions disabled and managed to reproduce the issue by typing in some random JavaScript code and with `editor.codeLens`, `javascript.referencesCodeLens.enabled` and `javascript.referencesCodeLens.showOnAllFunctions` all enabled.

Issue Type: <b>Bug</b>

Using mouse wheel zooming can result in CodeLens being positioned incorrectly. This is corrected on the next key entered into the editor window though.

Here's a gif to show this:
![Incorrect CodeLens positioning](https://user-images.githubusercontent.com/34325463/80934940-034f6a80-8dfd-11ea-8a96-c231646558f7.gif)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.86GB (4.56GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by tabaddor** [comment] 2020-06-14 14:30
I'm not sure if that is a bug, it seems like expected behavior. Until the user is satisfied with the zoom, the position of the CodeLens shouldn't matter too much, however, it does make sense to at least position it reasonably. Any progress on this @Brandon-Gui123?

**Comment by Brandon-Gui123** [comment] 2020-06-14 16:57
Sorry. I have no experience with how VS Code works internally and can only give suggestions and report bugs.

It's currently VS Code 1.46.0 and the issue is still present. I tried adjusting `window.zoomLevel` but it didn't fix it.

What I noticed was when changing `window.zoomLevel`, the CodeLens text tries to remain where it is (i.e. if it is above the code, it remains above the code; if it is misaligned, it remains misaligned). Probably the intended effect of scaling.

![CodeLens position and window zoom](https://user-images.githubusercontent.com/34325463/84599230-19902200-aea3-11ea-8331-31e288f94e70.gif)

**Comment by jrieken** [comment] 2020-06-15 07:07
> It's currently VS Code 1.46.0 and the issue is still present.

Sure - when an issue's state is "Open" it means that the issue isn't fixed yet

**Comment by tabaddor** [comment] 2020-06-15 13:39
> What I noticed was when changing `window.zoomLevel`, the CodeLens text tries to remain where it is (i.e. if it is above the code, it remains above the code; if it is misaligned, it remains misaligned). Probably the intended effect of scaling.

Interesting. But even when the user is zooming in or out, when the user stops this action, doesn't the CodeLens return to the correct position?

**Comment by Brandon-Gui123** [comment] 2020-06-15 16:56
> Interesting. But even when the user is zooming in or out, when the user stops this action, doesn't the CodeLens return to the correct position?

Zooming in with your mouse scroll wheel first, then zooming in with `window.zoomLevel` will not set CodeLens position to how it is supposed to be. So far, CodeLens stayed at where it is.

As far as I saw, CodeLens resets its position when I:
- Typed a key into the editor with the glitched positioning of CodeLens in place;
- Switched the opened editor to another one in the same group (basically switching tabs)
- Toggle the `editor.codeLens` option (or for any other option which enables/disables CodeLens for a specific language)

**Comment by tabaddor** [comment] 2020-06-15 22:16
Understood. So this issue only occurs when zooming with your mouse scroll wheel, correct?

**Comment by Brandon-Gui123** [comment] 2020-06-16 03:32
Yep.

**Comment by tabaddor** [comment] 2020-06-16 15:28
My thoughts thus far: 
- CodeLens fails to scale with the zoom as the code written by the user in the editor does so
- This behavior may be due to the mouse scroll event (if it exists) that is accounted for in the general case (code), but not for CodeLens

I'd like to hear others thoughts on this issue as well.

**Comment by jrieken** [comment] 2020-11-09 21:01
This got fixed via 51eb090

**Comment by jrieken** [comment] 2020-11-09 21:03
\closedWith 51eb090

**Closed** 2020-11-09 21:02 UTC
Labels: author-verification-requested, bug, code-lens
