### ISSUE TITLE
Folding button icons are reversed

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89894] opened 2020-02-03 02:20 UTC
Whereas the folding button icons normally used on source editors (including VS Code, according to the docs) logically depict the effect of a click ([+] to expand, [-] to collapse), the ones actually present in the VS Code program are illogically reversed - the button to expand has the icon ">" depicting collapse, and the button to collapse has the icon "v" depicting expand.

**Comment by gjsjohnmurray** [comment] 2020-02-03 10:41
They are functioning as designed. When #79130 arrives you will be able to change them. I suggest you upvote that issue and close this one.

**Comment by chrisjj** [comment] 2020-02-03 13:59
> They are functioning as designed.

Source?

**Comment by gjsjohnmurray** [comment] 2020-02-03 14:01
@misolori

**Comment by misolori** [comment] 2020-02-03 15:40
Agreed that this by design and matches other paradigms where `>` indicates a collapsed state. We also use this treatment in all of our trees. As @gjsjohnmurray mentioned, you can upvote #79130 if you want custom icons. I'll be closing this one.

![image](https://user-images.githubusercontent.com/35271042/73666831-3d6f6b80-4658-11ea-8a4c-da0195a782ff.png)

**Closed by misolori** 2020-02-03 15:40 UTC

**Comment by chrisjj** [comment] 2020-02-03 17:39
> matches other paradigms where > indicates a collapsed state.

This is a button icon and the primary function is not to indicate the state. It is to indicate the button function which is to change the state and hence. as in Visual Studio and every other folding editor I have seen, the icon for the collapse command button should depict collapse - not expand as currently.

> We also use this treatment in all of our trees.

Not any trees in your standard dialogs on Windows, note. E.g.

![image](https://user-images.githubusercontent.com/6157073/73676093-a207e600-46ab-11ea-8018-667ee35d2783.png)

And what's the source of that screenshot? The button icons do not accord with those I see on Windows (added to root post). Mac perhaps?

**Comment by misolori** [comment] 2020-02-03 18:18
@chrisjj the screenshot above is Chrome dev tools. When I mentioned that we use this treatment in all of our trees, I meant the VS Code product:

VS Code explorer
![image](https://user-images.githubusercontent.com/35271042/73678950-53882680-466e-11ea-89a1-67672f8a14fc.png)

And a few other examples that use the same paradigm:

Windows explorer
![image](https://user-images.githubusercontent.com/35271042/73678594-87af1780-466d-11ea-981d-ea3dc3768746.png)

Outlook
![image](https://user-images.githubusercontent.com/35271042/73678837-12901200-466e-11ea-941a-b7e0077e8f08.png)


Sublime
![image](https://user-images.githubusercontent.com/35271042/73678621-94cc0680-466d-11ea-9880-f4dde82c8865.png)

Atom
![image](https://user-images.githubusercontent.com/35271042/73678656-aa413080-466d-11ea-904d-ec877a939c07.png)
