### ISSUE TITLE
Block select

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#412] opened 2015-11-21 14:50 UTC
Please consider adding block-selection like VS proper; shift-alt-cursor manages selection.
Certain kinds of edits are very repetitive or tedious without it.

**Comment by glen-84** [comment] 2015-11-21 18:00
Duplicate of #84?

**Comment by aloisdg** [comment] 2016-02-10 16:35
@glen-84 looks like a duplicate indeed.

**Closed** 2016-04-07 12:26 UTC
Labels: feature-request
