### ISSUE TITLE
TypeScript syntax highlighting

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#1917] opened 2016-01-11 06:47 UTC
As you can see in the attached image, the syntax highlighting for TypeScript doesn't work correct anymore. Neither the module nor the type definitions are highlighted. This is a complete new installation I did two days ago. Current version is 0.10.6

![image](https://cloud.githubusercontent.com/assets/7260053/12228114/4541e4e0-b837-11e5-8c31-9eb6bbecffee.png)

**Comment by joaomoreno** [comment] 2016-01-11 08:49
@egamma @aeschli @bpasero ping

**Comment by aeschli** [comment] 2016-01-11 09:51
duplicate of #1470 + https://github.com/Microsoft/TypeScript-TmLanguage/issues/37

**Closed by aeschli** 2016-01-11 09:51 UTC
