### ISSUE TITLE
scss syntax highlighting broken on nested selectors

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#38599] opened 2017-11-17 09:24 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
code-settings-sync|Sha|2.8.5
indenticator|Sir|0.4.2
quokka-vscode|Wal|1.0.80
project-manager|ale|0.23.0
markdown-preview-github-styles|bie|0.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
gitlens|eam|6.1.1
prettier-vscode|esb|0.24.0
file-icons|fil|1.0.7
search-node-modules|jas|1.2.0
vscode-text-pastry|jkj|1.2.0
svg|joc|0.0.9
expand-region|let|0.1.2
vscode-duplicate|mrm|1.2.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
sublime-keybindings|ms-|3.0.3
gremlins|nho|0.6.2
vscode-subword-navigation|ow|1.1.5
vscode-sort-json|ric|1.10.2
markdown-preview-enhanced|shd|0.3.0
stylelint|shi|0.30.0
vscode-hexdump|sle|1.6.0
vscode-djaneiro|the|1.3.0
transpose|v4r|0.0.5
vscode-arduino|vsc|0.2.10
babelrc|wad|1.0.0
vscode-todo-highlight|way|0.5.11
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
better-align|wwm|1.1.6
markdown-all-in-one|yzh|0.11.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Write scss
2. 
![image](https://user-images.githubusercontent.com/2827047/32939952-7d0a0ad8-cb81-11e7-8809-e57f8e3673cb.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-11-20 09:52
duplicate of #38398, fixed in 1.19-insiders

**Closed by aeschli** 2017-11-20 09:52 UTC
Labels: new release
