### ISSUE TITLE
Adds Schema Mapping

### ISSUE THREAD

**Issue by Acelator** [microsoft/vscode#78735] opened 2019-08-08 22:13 UTC
I think that we can use [SchemaStore](SchemaStore.org) to import Schemas and then used it to offer autocompletion.

It can save a lot of time writing code.

**Comment by aeschli** [comment] 2019-08-20 06:49
duplicate of https://github.com/microsoft/vscode/issues/26289

**Closed by aeschli** 2019-08-20 06:49 UTC
