### ISSUE TITLE
Extremely laggy and janky window resizing when custom title

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#165441] opened 2022-11-03 23:11 UTC
Type: <b>Performance Issue</b>

Have a split editor with a notebook and settings page, terminal open.  Resizing takes more than a second of aweful slow layouts.

https://user-images.githubusercontent.com/8599/199852450-0b128491-de95-4a7b-b2b6-19d8a46be5a0.mov

Chrome performance profile: [Profile-20221103T160646.json.zip](https://github.com/microsoft/vscode/files/9933610/Profile-20221103T160646.json.zip)

- Resize handlers that keep triggering layouts.
- Something causes the page be styled and layouted on every frame (but the each cycle takes 40ms)

Tried reproducing in Firefox (Profile: https://share.firefox.dev/3hbnpj7), but the expensive painting only seems to happen in Electron.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/8599/199852348-5f1225e0-9ceb-425d-9221-896d72deab86.png">

With *just* Extensions view open (no editor window), each style calculation takes 14ms:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/8599/199853248-1815c3e9-799c-4a93-8e17-daf4c4553b59.png">

With *just* Explorer open (no editor window), each style calculation takes 6.8ms:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/8599/199853078-22e96b89-39d6-4c67-9176-64d9479c9492.png">

VS Code version: Code - Insiders 1.74.0-insider (e8eb39bac26ddc87f27ed69fa06c54cd230d18f9, 2022-11-03T19:00:34.330Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (1.93GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3|
|OS|Linux x64 5.15.49-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 x 2400)|
|Memory (System)|11.70GB (10.01GB free)|
|VM|0%|
</details>

**Comment by jrieken** [comment] 2022-12-09 15:55
This even reproduces with just the explorer open, not editor esp no notebook or any other custom editor. It seems like every resize event causes really expensive "Recalculate Style" operations. I'm involving more folks here, I don't really know how to drill into this

<img width="1543" alt="Screenshot 2022-12-09 at 16 53 19" src="https://user-images.githubusercontent.com/1794099/206741091-0d774551-ac2b-49ca-a652-32ef1093970d.png">

**Comment by bpasero** [comment] 2022-12-09 17:26
This was just also reported as https://github.com/microsoft/vscode/issues/168547 however is not really a new issue. I remember that I even once reported this to Electron like 5y ago.

However, if there is something we can do to improve it, even better. For that: @digitarald does it reproduce in our web version as well? So far in previous issues it felt exclusive to Electron and not web.

**Comment by jrieken** [comment] 2022-12-09 17:39
> I remember that I even once reported this to Electron like 5y ago.

I don't believe this is specific to Electron because I see the same on https://vscode.dev using Chrome. So, if at all it's an issue with Chromium. It's also noteworthy that resizing just the explorer width (with the grid sash) is snappy

**Comment by bpasero** [comment] 2022-12-09 17:43
What I am referring to is a lag when resizing the window and it has been reported and confirmed, though never really investigated:
* https://github.com/electron/electron/issues/3615
* https://github.com/electron/electron/issues/23980

**Comment by rebornix** [comment] 2022-12-10 04:19
I don't think it's this bad before. A resize causing multiple recalculate style feels wrong

<img width="524" alt="image" src="https://user-images.githubusercontent.com/876920/206828558-b5e6f57c-4036-4e95-8f13-4eeb01067bee.png">

@deepak1556 any suggestion for us to troubleshoot if it's a chromium issue?

**Comment by bpasero** [comment] 2022-12-10 06:20
From the performance trace it seems to me that this is code that requires a style recalculation in a scheduled task (i.e. run at next animation frame). I think we have quite a few places where we schedule work like that away from the current loop to free up frame rendering pressure.

@sbatten this seems to be worse with custom title enabled vs not:

**Custom Title**
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/900690/206835187-21b42859-9ddc-421b-8170-b0b9f672ae66.png">

**Native Title**
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/900690/206835206-2301ebba-4e90-43ee-ab4b-2034012808fa.png">

My first suspicion was this piece of code:

https://github.com/microsoft/vscode/blob/d1f42f4857c638aa1580f0ea6d0855618f7d47ad/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L449

When I comment it out it looks like this:

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/900690/206835270-e846796d-1aa3-4152-8d21-7289148b7512.png">

Maybe we start with an investigation of the custom title first and then see if other parts in the workbench also contribute to this issue?

**Comment by bpasero** [comment] 2022-12-10 06:21
This is with command center and layout controls removed:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/900690/206835321-12571043-233c-48fa-b9e3-d85491ccbf06.png">

**Comment by bpasero** [comment] 2022-12-10 06:24
Time it takes to recalculate style:
`0.2ms`: native title
`5.75ms`: custom title without command center, layout controls and the scheduled job
`7.00ms`: custom title without the scheduled job
`8.00ms`: custom title fully enabled

**Comment by sbatten** [comment] 2022-12-12 19:11
Thanks for the investigation. The custom title bar having multiple widgets and not really being able to leverage a fully css based approach is costly. I'll dig into what optimizations we can have there. Any tips appreciated

**Comment by bpasero** [comment] 2022-12-15 11:07
More really bad examples in https://github.com/microsoft/vscode/issues/169142, I wonder why this got worse in our last release 🤔

**Comment by digitarald** [comment] 2022-12-15 17:16
Looks like this was introduced in https://github.com/microsoft/vscode/pull/164882 .

<details><summary>vscode-bisect log …</summary>

```
❯ npx vscode-bisect
✔ Commit of released insiders build that reproduces the issue (leave empty to pick the latest build) …
✔ Commit of released insiders build that does not reproduce the issue (leave empty to pick the oldest build) …
[build] total 200 builds with roughly 8 steps
[build] starting build f5c96e2db885f43fe1adb4a6ebbdfecf095430a8...
✔ Is f5c96e2db885f43fe1adb4a6ebbdfecf095430a8 good or bad? › Good
[build] starting build 6455bf1608dfa1b955717f66295f0f9200db0f73...
✔ Is 6455bf1608dfa1b955717f66295f0f9200db0f73 good or bad? › Good
[build] starting build edccbd1307ef8055f26778c5a86f9eef885bc6ff...
✔ Is edccbd1307ef8055f26778c5a86f9eef885bc6ff good or bad? › Bad
[build] starting build 3544aabd5a2b0da2cd3a6f3fa3f00759aa9d9709...
✔ Is 3544aabd5a2b0da2cd3a6f3fa3f00759aa9d9709 good or bad? › Good
[build] starting build 96db0b339360bc72d27d869d81a557540ad5f800...
✔ Is 96db0b339360bc72d27d869d81a557540ad5f800 good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/e8eb39bac26ddc87f27ed69fa06c54cd230d18f9/VSCode-darwin.zip...
[build] unzipping build to /var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T/vscode-bisect/.builds/e8eb39bac26ddc87f27ed69fa06c54cd230d18f9...
[build] starting build e8eb39bac26ddc87f27ed69fa06c54cd230d18f9...
✔ Is e8eb39bac26ddc87f27ed69fa06c54cd230d18f9 good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/VSCode-darwin.zip...
[build] unzipping build to /var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T/vscode-bisect/.builds/8fa188b2b301d36553cbc9ce1b0a146ccb93351f...
[build] starting build 8fa188b2b301d36553cbc9ce1b0a146ccb93351f...
✔ Is 8fa188b2b301d36553cbc9ce1b0a146ccb93351f good or bad? › Good
[build] downloading build from https://az764295.vo.msecnd.net/insider/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/VSCode-darwin.zip...
[build] unzipping build to /var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T/vscode-bisect/.builds/86f0f9bfa268fe21af7efae37d8f0da1dba8137f...
[build] starting build 86f0f9bfa268fe21af7efae37d8f0da1dba8137f...
✔ Is 86f0f9bfa268fe21af7efae37d8f0da1dba8137f good or bad? › Bad
[build] 86f0f9bfa268fe21af7efae37d8f0da1dba8137f is the first bad commit after 8fa188b2b301d36553cbc9ce1b0a146ccb93351f.
✔ Would you like to open GitHub for the list of changes? … yes

Run the following commands to continue bisecting via git in a folder where VS Code is checked out to:

git bisect start && git bisect bad 86f0f9bfa268fe21af7efae37d8f0da1dba8137f && git bisect good 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
```

</details>

**Comment by jrieken** [comment] 2022-12-19 15:19
@sbatten I see a much better experience by replacing [`height: env(titlebar-area-height, 28px);`](https://github.com/microsoft/vscode/blob/be0068767a283daa35c93b6c4bcb2a396cd85528/src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css#L245) with either nothing or with fixed `28px`. I think the `env()` function is just too slow for us and I wonder what made us use it. I don't see any noticeable different when remove its usage. Is it an oversight that we use this for mac/desktop? AFAIK this is only useful for PWA applications

**Comment by jrieken** [comment] 2022-12-19 15:32
https://github.com/microsoft/vscode/pull/169549 is up to remove WCO styling for native mac. 


Apart from that it seems more work is needed for for PWA mac, this is what I am getting with Edge ⬇️ 

<img width="1277" alt="Screenshot 2022-12-19 at 16 29 49" src="https://user-images.githubusercontent.com/1794099/208461815-cd81b8c2-52e9-4f0f-87d9-769a746bd247.png">

**Comment by jrieken** [comment] 2022-12-22 16:40
Closing this as fixed  but I have seen @sbatten refactorings which are going to make this better than before this regression

**Closed by jrieken** 2022-12-22 16:40 UTC
Labels: bug, freeze-slow-crash-leak, perf, titlebar
