### ISSUE TITLE
Can't running with manual

### ISSUE THREAD

**Issue by llHoYall** [Microsoft/vscode#55620] opened 2018-08-02 03:22 UTC
- VSCode Version: 1.25.1
- OS Version: Windows 10 Pro 17134.112

Steps to Reproduce:

1. Create project with `yo code`
2. Press `F5` follows the manual.
3. Display "Building..." message in status bar.
4. But, it doesn't create out folder. So, extension does not work.
5. Type `yarn compile` into integrated terminal.
6. out folder is created and work properly.

Few months ago, the manual is correct. But, now is incorrect. 
The old version of projects are successfully building when I press `F5` key.

Does this issue occur when all extensions are disabled?: Yes

**Comment by llHoYall** [comment] 2018-08-16 01:04
I upgrade all package for test.

```
vscode @1.26.0
Electron @2.0.5
Chrome @ 61.0.3163.100
Node.js @8.9.3
V8 @6.1.534.41

generator-code@1.1.37
yo@2.0.5
```

And, create project *helloworld* with `yo code`

Press `F5` and execute `Hello World` command. It produces error message like below

> command 'extension.sayHello' not found
>
> Activating extension 'llHoYall.helloworld' failed: Cannot find module 'C:\Users\blahblah\helloworld\out\extension'.1

And then, main vscode's debug console shows a message.

```
C:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\Code.exe --debugBrkPluginHost=48493 --debugId=c4eadda7-ffd0-4019-8adb-029af4373322 --extensionDevelopmentPath=C:\Users\hoya128\hWorkspace\helloworld 
Activating extension 'llHoYall.helloworld' failed: Cannot find module 'C:\Users\hoya128\hWorkspace\helloworld\out\extension'.
Activating extension `llHoYall.helloworld` failed:  Cannot find module 'C:\Users\hoya128\hWorkspace\helloworld\out\extension'
Here is the error stack:  Error: Cannot find module 'C:\Users\hoya128\hWorkspace\helloworld\out\extension'
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.t._load (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:831:951)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:781:881)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
	at c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:807:367
	at t._doActivateExtension (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:807:479)
	at t._activateExtension (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:806:337)
	at Object.actualActivateExtension (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:804:204)
	at e._activateExtension (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:459:446)
	at c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:459:65
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:459:40)
	at e.activateByEvent (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:457:321)
	at t.activateByEvent (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:804:568)
	at t.$activateByEvent (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:809:54)
	at e._doInvokeHandler (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:983)
	at e._invokeHandler (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:701)
	at e._receiveRequest (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:767)
	at e._receiveOneMessage (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:536)
	at c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:669:452
	at c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:672:575
	at c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:903
	at e.fire (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at a (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:713)
	at Socket.n._socketDataListener (c:\Users\hoya128\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

When I did `Task > Show Running Tasks', it was `no task is running`.

I think it does not execute `preLaunchTask`.

------

This is a part of my electron project.

```json
# .vscode/launch.json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "preLaunchTask": "compile",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "args": [".", "--enable-logging"]
    }
  ]
}

# .vscode/tasks.json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "compile",
      "type": "shell",
      "command": "${workspaceRoot}/node_modules/.bin/webpack"
    }
  ]
}
```

This code works for me.

Thanks.

**Comment by dbaeumer** [comment] 2018-08-16 08:05
You extension doesn't register a command handler for the `extension.sayHello`. How does your main code look like.

**Comment by llHoYall** [comment] 2018-08-16 08:49
```typescript
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "helloworld" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        // The code you place here will be executed every time your command is executed

        // Display a message box to the user
        vscode.window.showInformationMessage('Hello World!');
    });

    context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

This is `extension.ts` code. It was generated by `yo code`.

I didn't modify at all.

**Comment by llHoYall** [comment] 2018-08-16 08:59
This is a generated `./vscode/launch.json` file.

```json
// A launch configuration that compiles the extension and then opens it inside a new window
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
	"version": "0.2.0",
    "configurations": [
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ],
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        },
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/out/test"
            ],
            "outFiles": [
                "${workspaceFolder}/out/test/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        }
    ]
}
```

And this is a generated `./vscode/tasks.json` file.

```json
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "watch",
            "problemMatcher": "$tsc-watch",
            "isBackground": true,
            "presentation": {
                "reveal": "never"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

If I launch project, vscode should execute preLaunchTask. But, vscode doesn't execute this task.

Probably, this is the main issue.

**Comment by dbaeumer** [comment] 2018-08-16 10:42
Which OS locale are you on?

When you open the workspace folder and do Task > Run Task is the `npm: watch` task listed?

**Comment by llHoYall** [comment] 2018-08-17 02:39
My windows10 is Korean, and vscode is english.

```json
// locale.json
{
	"locale":"en"
}
```

When I select the menu `Task > Run Task`, it will show to me a list.

- npm: watch
- npm: compile
- npm: install
- npm: postinstall
- npm: test
- npm: vscode:prepublish

And I did `npm: watch` through the menu. There is nothing happened.

Finally, I typed 'npm run watch` into the integrated terminal, it works perfectly.

**Comment by dbaeumer** [comment] 2018-08-17 08:34
Can you open the developer console (Help > Toogle Developer Tools) and see if there are any exceptions.

After exexuting the task there should be a little hammer icon in the left lower corner showing that one task is running. You don't see this?

**Comment by llHoYall** [comment] 2018-08-20 02:38
This is console logs of project vscode.

```
INFO no standard startup: panel is active    /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1397 

[Extension Host] activating extension    console.ts:136
```

This is console logs of debug vscode.

```
INFO no standard startup: not just one window    /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1397 

Loading development extension at c:\Users\blahblah\helloworld    /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3225

[Extension Host] STOPPED on first line for debugging on port 25599    /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3119

Extension Host    /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3117 

Debugger listening on ws://127.0.0.1:25599/f1c10926-5910-40d2-acac-f3f061f6f805    /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3117 

For help see https://nodejs.org/en/docs/inspector

Extension Host    /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3117 

Debugger attached.    /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3117 
```

And, I see only git, error, warning and start debug in the left lower corner.

**Comment by llHoYall** [comment] 2018-08-21 00:37
Nope. There is only `1: powershell' both of them.

**Comment by dbaeumer** [comment] 2018-08-21 14:53
I have no idea why this is failing since it works for me following your steps. Can you check your extension into GitHub so I can clone the repository. May be something else broke.

**Comment by llHoYall** [comment] 2018-08-22 00:44
This is repository url "https://github.com/HoYaProject/helloworld"

And, I'm using these extensions together.

- ms-vscode.cpptools
- ms-python.python
- ms-vscode.powershell
- alefragnani.bookmarks
- esbenp.prettier-vscode
- keroc.hex-fmt
- slevesque.vscode-hexdump
- formulahendry.auto-rename-tag
- formulahendry.auto-close-tag

**Comment by dbaeumer** [comment] 2018-08-22 08:47
@llHoYall I cloned the repository, ran `npm install` in the folder and then opened VS Code on it and everything works as expected for me.

Can you try to see if you can reproduce your problem with all extensions disabled. To disable them start VS Code from a terminal and pass `--disable-extensions`

**Comment by llHoYall** [comment] 2018-08-23 13:48
I also do like you. But it was same as before.
So, I try to another windows 10 computer. I was failure also.
Finally, I try to my Macbook Air and it works good by the manual.
Then, why it doesn't work on windows?

**Comment by dbaeumer** [comment] 2018-08-23 13:52
That is very strange since I am testing this under Windows only. I am really puzzeled here. Anything that you can think of is different between Windows and Mac for you?

**Comment by llHoYall** [comment] 2018-08-24 00:39
I found one thing. 

1. Press `F5` key,
2. Click Terminal and dropdown menu very very very fast.
  Then, I can see a menu.
  ```
  1: powershell
  2: task: watch
  ```

But I can see it very short time. It is clearly disappear. 
So, I don't see messages at all.
Is there any method to see these messages?

**Comment by dbaeumer** [comment] 2018-08-24 07:58
If you execute the `npm: watch` task from the task menu, does the entry stay in the terminal drop down?

If not all I could think about tracking this down is to compile VS Code from source and debug it on your machine. Would you be willing to do so?

**Comment by llHoYall** [comment] 2018-08-24 10:32
FInally, I success to capture the screen. I will type here.

```javascript
> Executing task: npm run watch <

npm ERR! path C:\Users\myid\package.json    // This is wrong!!!!
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\myid\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Right path should be "C:\Users\myid\project\package.json".
Can you solve this?

**Comment by llHoYall** [comment] 2018-08-24 14:18
+
On my mac, the path is the same as windows.
`~/project/package.json` i.e. `/Users/myid/project/package.json`.

**Comment by llHoYall** [comment] 2018-08-29 00:39
`C:\Users\hoya128\hWorkspace\helloworld` is my project path on Windows.

**Comment by dbaeumer** [comment] 2018-08-29 08:15
The trace in https://github.com/Microsoft/vscode/issues/55620#issuecomment-415720793 shows that VS Code starts the task correctly, however for some reason npm can't find the `package.json`. Are there any special characters in the path `C:\Users\hoya128\hWorkspace\helloworld`. It looks like the working directory is incorrect.

**Comment by dbaeumer** [comment] 2018-08-29 08:17
Can you provide me with the npm log file?

**Comment by llHoYall** [comment] 2018-08-30 00:34
The string has only pure ascii character. There is nothing special.
Then, how can I create a npm log file?

**Comment by dbaeumer** [comment] 2018-08-30 09:00
If npm fails it is usually generating the log file and prints its location to the console.

**Comment by llHoYall** [comment] 2018-08-31 00:29
Yes, you are right. But, it is a usual case when use a npm.
This case, there is no npm log file anywhere.

**Comment by llHoYall** [comment] 2018-08-31 09:16
I run a `$ yarn install` at vscode project folder.
It gives to me this.
```
error An unexpected error occurred: "C:\\Users\\hoya128\\AppData\\Local\\Yarn\\Cache\\v2\\npm-vscode-nls-3.2.4-2166b4183c8aea884d20727f5449e62be69fd398\\.yarn-metadata.json: Unexpected token \u0000 in JSON at position 0".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\hoya128\\hWorkspace\\vscode\\extensions\\configuration-editing\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I'm getting dislike a Windows....

**Comment by llHoYall** [comment] 2018-08-31 14:06
When I install it, I got blue screen. 😞 
So, I removed `node_modules/` folder.
Next, Installing again, I faced the error messages.
I will try to install with you gave method.

**Comment by dbaeumer** [comment] 2018-09-03 08:26
Something seems to be really wired with your machine.

**Comment by llHoYall** [comment] 2018-09-05 00:32
```
hoya128 ~\hWorkspace\vscode\scripts
[master ≡] > ./code C:\Users\hoya128\hWorkspace\helloworld\
[09:30:14] Syncronizing built-in extensions...
[09:30:14] You can manage built-in extensions with the --builtin flag
[09:30:14] [marketplace] ms-vscode.node-debug@1.27.6 ✔︎
[09:30:14] [marketplace] ms-vscode.node-debug2@1.27.1 ✔︎

[main ?ㅼ쟾 9:30:17] update#ctor - updates are disabled
[25280:0905/093024.894:INFO:CONSOLE(182)] "%c INFO", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/platform/log/common/log.js (182)
[25280:0905/093025.935:INFO:CONSOLE(237)] "%c[Extension Host] %cdebugger listening on port 5870", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (237)
[25280:0905/093026.639:INFO:CONSOLE(146)] "%c[Extension Host] %cdebugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/939f4993-43de-4508-b51b-8b3f172c417c", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (146)
Debugger listening on ws://127.0.0.1:5876/fdc2e57c-1ea5-4fc2-b773-98bd13b6a046
For help see https://nodejs.org/en/docs/inspector
[25280:0905/093102.826:INFO:CONSOLE(182)] "%c INFO", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/platform/log/common/log.js (182)
[25280:0905/093103.008:INFO:CONSOLE(861)] "Loading development extension at c:\Users\hoya128\hWorkspace\helloworld", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js (861)
[25280:0905/093103.759:INFO:CONSOLE(234)] "%c[Extension Host] %cSTOPPED on first line for debugging on port 10818", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (234)
[25280:0905/093104.347:INFO:CONSOLE(149)] "Extension Host", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (149)
[25280:0905/093104.355:INFO:CONSOLE(150)] "%cD%cebugger listening on ws:%c//127.0.0.1:10818/36377664-88e4-4d09-8fb4-e2be34034fe1
For help see https://nodejs.org/en/docs/inspector
", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (150)
[25280:0905/093104.356:INFO:CONSOLE(151)] "console.groupEnd", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (151)
[25280:0905/093105.367:INFO:CONSOLE(149)] "Extension Host", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (149)
[25280:0905/093105.367:INFO:CONSOLE(150)] "%cDebugger attached.
", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (150)
[25280:0905/093105.367:INFO:CONSOLE(151)] "console.groupEnd", source: file:///C:/Users/hoya128/hWorkspace/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (151)
```
This is all I have messages.

**Comment by dbaeumer** [comment] 2018-09-05 09:26
These messages are OK. Did the VS Code window open (e.g. the instance compiled from source)

**Comment by llHoYall** [comment] 2018-09-07 00:17
That is same before. What am I do next?

**Comment by dbaeumer** [comment] 2018-09-07 07:53
So VS Code starts when executing code in the scripts folder. Right? Then do

- Help > Toggle Developer tools
- select source tab
- Ctrl+O and type terminalTaskSystem.js.
- select the file
- set a breakoing on line 614 (e.g. `var result = this.terminalService.createTerminal(shellLaunchConfig);`
- execute your task
- when the breakpoint gets hit, got to the console in the dev tools
- type `shellLaunchConfig` <enter>
- expand the node.
- post the content here.

You should see somethink like this:

```
{name: "Task - compile", executable: "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe", args: "-Command npm run compile", waitOnExit: "Terminal will be reused by tasks, press any key to close it.", initialText: "[1m> Executing task: npm run compile <[0m↵", …}
args
:
"-Command npm run compile"
cwd
:
"c:\Users\dirkb\Projects\mseng\VSCode\vscode"
executable
:
"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe"
initialText
:
"[1m> Executing task: npm run compile <[0m↵"
name
:
"Task - compile"
waitOnExit
:
"Terminal will be reused by tasks, press any key to close it."
__proto__
:
Object
```

**Comment by llHoYall** [comment] 2018-09-10 01:51
1. cd ~/hWorkspace/vscode
2. git pull
3. ./scripts/code .
4. `CTRL+p`  and select `terminalTaskSystem.ts` file.
5. Set breakpoint on the line.

And next, I don't know how to execute my extension with this.

**Comment by dbaeumer** [comment] 2018-09-10 07:30
@llHoYall 

- open the workspace that contains out extension code
- try to execute the task that fails executing.

**Comment by dbaeumer** [comment] 2018-09-11 08:39
Does it break if you set a breakpoint into the beginning of the function `TerminalTaskSystem.prototype.run`.

**Comment by llHoYall** [comment] 2018-09-18 00:41
It is the same not only extension but also normal react project.
This is a tasks.json file.
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "yarn: start",
      "type": "shell",
      "command": "yarn start",
      "options": {
        "cwd": "${workspaceRoot}/"
      }
    }
  ]
}
```
And, error message like below.
```sh
> Executing task: yarn start <

yarn run v1.9.4
error Couldn't find a package.json file in "C:\\Users\\hoya128"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


Terminal will be reused by tasks, press any key to close it.
```
There is a problem on path.

**Comment by llHoYall** [comment] 2018-09-18 04:52
How can I open the integrated terminal with path of workspace?

**Comment by dbaeumer** [comment] 2018-09-18 07:05
Glad you were able to track it down. Any objection to close the issue.

**Closed** 2018-09-25 15:08 UTC
Labels: needs more info, tasks
