### ISSUE TITLE
Source control tree-view mode collapse on source-control action

### ISSUE THREAD

**Issue by Nerigal** [microsoft/vscode#115238] opened 2021-01-27 16:59 UTC
Issue Type: **Bug**

When I manually un-collapse all folders in the source control view and make some change, for example commit a modified file, the view collapse all folders again which makes the view too packed (tons of unversioned files in unversioned folders)

**VS Code info:**
**version**: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
**OS:** Linux x64 5.4.0-58-generic

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment] 2021-01-27 18:13
Duplicate of https://github.com/microsoft/vscode/issues/114204

**Closed by eamodio** 2021-01-27 18:13 UTC

**Comment by Nerigal** [comment] 2021-01-27 18:20
i would be curious to know what make you think this is the same issue as  #114204
there is absolutely nothing in common

**Comment by eamodio** [comment] 2021-01-27 18:30
Wrong link, it should have been: https://github.com/microsoft/vscode/issues/112487

The fix there changes the behavior of expanding/collapsing of the tree nodes.
