### ISSUE TITLE
Cursor click on line doesn't respect indentation

### ISSUE THREAD

**Issue by dnistreanu** [microsoft/vscode#52614] opened 2018-06-21 13:44 UTC
**VsCode:**
```
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**OS:** Windows 10 Pro x64

**My settings:**
```
{
    "editor.fontSize": 16,
    "editor.wordWrap": "on",
    "terminal.integrated.fontSize": 16,
    "workbench.iconTheme": "vscode-icons",
    "editor.formatOnSave": true,
    "workbench.colorTheme": "Seti Monokai",
    "window.zoomLevel": 0,
    "liveServer.settings.donotShowInfoMsg": true,
    "editor.suggestSelection": "first",
    "editor.snippetSuggestions": "top"

}
```

**Actual Result:**  Instead of respecting indentation, cursor will move at the beginning of the empty line when clicking on it.
**Expected Result:** Cursor will respect the indentation after clicking on empty line.

**Comment by dnistreanu** [comment] 2018-07-02 19:01
The issue is annoying and after some research I see that there are other issues like that reported. I updated description because in fact scenario is very simple. 
Please fix, for me it can result in a switch to other editor.

**Comment by alexandrudima** [comment] 2019-10-25 14:37
Duplicate of #13960

**Closed by alexandrudima** 2019-10-25 14:37 UTC
Labels: editor, feature-request
