### ISSUE TITLE
Debugger API - threadsRequest method is fired even after TerminatedEvent is sent

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#38440] opened 2017-11-15 18:49 UTC
In the [Python extension](/Microsoft/vscode-python) we're seeing the threadsRequest method is being invoked even after the TerminatedEvent is sent by the Debug Apdater.

The flow is as follows:
- Debug a python program
- The python program ends, and this is detected by the debug adapter
- The debug adapter then sends a `TerminatedEvent`, 
- Next the `disconnectRequest` gets invoked and a response is sent to this
- Immediately after the above, the `threadsRequest` method is invoked

This causes the code to fall over, as the process no longer exists.

I've checked out the [sample debugger code](https://github.com/Microsoft/vscode-mono-debug/blob/master/src/MonoDebugSession.cs#L706) and can see we have a check to see whether the process exists.

Shouldn't VS Code, stop sending these requests to the debug adapter. 
Or is it merely a timing issue (i.e. the `threadsRequest` had already been dispatched by vscode before it received the `TerminatedEvent`?

If it's the latter, then please feel free to close this issue.

**Comment by weinand** [comment] 2017-11-15 21:27
Yes, VS Code should not send any  `threadsRequest` after it has received a `TerminatedEvent`.
@isidorn please verify this and then close this issue.

However, it is always possible that a `threadsRequest` had already been dispatched by VS Code before the `TerminatedEvent` has been received. So DAs should protect themselves against that.

**Comment by DonJayamanne** [comment] 2017-11-15 21:34
@weinand thanks. In that case, please feel free to close this issue, I'm being more defensive in the code as a solution. 
I'm choosing not to close the issue myself, due to some followup work for @isidorn.

**Comment by isidorn** [comment] 2017-11-15 22:45
VSCode should not send an threadsRequest after a terminatedEvent, it might be a timing issue.
@DonJayamanne Since you have a reproducable on your machine feel free to place a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L364) and check the callstack

Though looking at all the possible callers it can only be a timing issue. Thus closing until proven otherwise.

**Closed by isidorn** 2017-11-15 22:45 UTC
Labels: bug, debug
