### ISSUE TITLE
Turn off Intellisense by file type and scope

### ISSUE THREAD

**Issue by nathanhammond** [Microsoft/vscode#10819] opened 2016-08-23 06:40 UTC
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.3

Steps to Reproduce:
1. Create Markdown file.
2. Begin typing.
3. After writing enough you end up getting Intellisense prompts for every new word you write:

![screen shot 2016-08-22 at 11 29 45 pm](https://cloud.githubusercontent.com/assets/20542/17882396/087a66dc-68c1-11e6-858d-c1091422bcf4.png)

This makes for a _terrible_ Markdown editing experience.

**Comment by jrieken** [comment] 2016-08-23 07:59
@nathanhammond As a global workaround you can turn off all textual completions with `editor.wordBasedCompletion: false`

**Comment by nathanhammond** [comment] 2016-08-23 16:18
@jrieken Indeed, but that cure is worse than the malady since the majority of the time I _do_ want (and benefit tremendously) from textual completions.

So rather than do that I simply moved my markdown editing into a different tool (also suboptimal).

**Comment by zachCatalyst** [comment] 2016-08-24 15:52
I've notice the same behaviour editing markdown that actually drove me to another tool (just for Markdown). Often I'll have a short todo list or notes in a plain text file this will happen to also, less often / irritating but similar.

I would love to see something like:

// blanket disabled for everything
editor.wordBasedCompletion: false

// blanket enabled for everything
editor.wordBasedCompletion: true

// on for everything except for file types in the exclude list.
editor.wordBasedCompletion: {
  exclude: [".md", ".txt", ".text"]
}

// off for everything except for file types in the inclusion list.
editor.wordBasedCompletion: {
  include: [".js", ".cs"]
}

**Comment by jrieken** [comment] 2016-08-24 16:22
Understood - I will tackle this in September. With it we should also think about configuring word based completions wrt  strings and comments. Tho not interesting for markdown folks like or hate it...

**Comment by nathanhammond** [comment] 2016-08-24 16:58
A "grand unified plan" of configuring it would be fantastic and I'm in no particular rush. Blacklists or whitelists at a global level provide some alleviation as a quick fix, but if instead everything were context aware you could provided completions inside of a Markdown code block that is annotated for a language.

```Markdown
```javascript
setTimeout(...
```

So your proposal for taking context into account is valuable in _many_ scenarios. So please don't feel unnecessarily pressured into the "quick fix" solution and take the time to design the solution that you actually want.

**Comment by jrieken** [comment] 2017-01-27 10:25
@nathanhammond fyi with the January release we have enabled language specific settings, so you could have:

```json
"editor.wordBasedCompletion": true,
"[markdown]": {
  "editor.wordBasedCompletion": false
}
```

**Comment by nathanhammond** [comment] 2017-01-31 12:39
@jrieken Thanks for the ping, that does make life far smoother. The _language_ specific settings actually work as a simple but elegant design. Regardless of how it is implemented now (maybe as a file type switch?) it allows for a future in which you detect the scope.

Given you're closing things as duplicates of this issue I'll leave it open as a tracking issue for the thoughts you have on this. 😄

**Comment by jrieken** [comment] 2017-01-31 15:38
dupe of #1657

**Closed** 2017-01-31 15:38 UTC
Labels: duplicate, editor, feature-request, suggest
