### ISSUE TITLE
Feature request: Set document language with parameter for changeLanguageMode command

### ISSUE THREAD

**Issue by Livven** [Microsoft/vscode#21826] opened 2017-03-02 20:08 UTC
It would be useful if you could optionally pass a parameter to the `workbench.action.editor.changeLanguageMode` command to directly set the desired language instead of opening the language list.

See also the following questions regarding this issue:

- http://stackoverflow.com/questions/40200788/how-to-change-language-mode-of-vscode-programmatically
- http://stackoverflow.com/questions/41639887/how-can-i-create-a-custom-keybinding-to-change-syntax-highlighting-to-a-specific
- https://social.msdn.microsoft.com/Forums/vstudio/en-US/25fd8d95-9de3-4465-8c64-82d68dcd2e47/shortcut-how-to-switch-between-typescript-and-html-with-one-or-two-shortcuts

And this comment: https://github.com/Microsoft/vscode/issues/8729#issuecomment-277838057

Ideally you would also be able to set a specific language with a keyboard shortcut, though I'm not sure if passing command parameters is possible in `keybindings.json`. If not that would be another issue I guess.

**Comment by jrieken** [comment] 2017-03-03 12:58
closing this as dupe of #1800. Tho it talks about a command this will be an API call like `document.languageId = 'foolang'`

**Closed by jrieken** 2017-03-03 12:58 UTC
