### ISSUE TITLE
Redo is not working

### ISSUE THREAD

**Issue by thiagofmleite** [Microsoft/vscode#18732] opened 2017-01-18 12:49 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-todo|MattiasPernhult|0.8.0|
|csharp|ms-vscode|1.6.2|
|mono-debug|ms-vscode|0.12.0|
|node-modules-resolve|naumovs|1.0.2|

---

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment] 2017-01-19 07:53
@thiagofmleite could you please provide steps on how to reproduce this. Redo works for me.

**Comment by alexandrudima** [comment] 2017-01-21 00:03
Closing until steps are provided.

**Closed by alexandrudima** 2017-01-21 00:03 UTC
Labels: editor, needs more info
