### ISSUE TITLE
Adding a js alias to jsconfig.json does not work.

### ISSUE THREAD

**Issue by zdrummond** [microsoft/vscode#64762] opened 2018-12-11 01:07 UTC
Issue Type: <b>Bug</b>

I have added an alias for our common library. I got it working with Webpack and Jest, but not in vscode, 

```
{
  "description":
    "This is to config VS Code to recongnise our aliases, ala https://medium.com/@justintulk/solve-module-import-aliasing-for-webpack-jest-and-vscode-74007ce4adc9",
  "compilerOptions": {
    "target": "es2017",
    "allowSyntheticDefaultImports": false,
    "baseUrl": "./",
    "paths": {
      "@lib/*": ["app/javascript/lib/*"]
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

Note the item in paths is the alias for @lib

I used to be able to righ click, go to defintion on this line

`import MustacheValidator from '../../../../../../lib/forms/MustacheValidator';`

and it worked, but now when I do it with 

`import MustacheValidator from '@lib/forms/MustacheValidator';`

it says No Defintion Found

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.17.1
Bookmarks|ale|10.0.0
react-pure-to-class-vscode|ang|1.1.7
vscode-color|ans|0.4.5
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
gitlens|eam|9.0.3
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.7.2
nasc-touchbar|fel|1.11.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
vscode-pull-request-github|Git|0.2.3
vscode-github|Kni|0.30.1
dotenv|mik|1.0.1
ruby-rubocop|mis|0.7.1
python|ms-|2018.11.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.7.0
mono-debug|ms-|0.15.8
node-debug2|ms-|1.30.0
debugger-for-chrome|msj|4.11.1
vscode-icons|rob|7.28.0
code-settings-sync|Sha|3.2.2
slim|sia|0.1.2
code-spell-checker|str|1.6.10
tabnine-vscode|Tab|1.0.3
vscode-jss-snippets|vis|0.2.2
ReactSnippets|xab|2.2.1
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-12-15 01:12
In VS Code 1.30, can you please confirm that both files are part of your `jsconfig.json` project. To do this:

1. Open the file in VS Code
1. Run the `JavaScript: go to project configuration` command
1. This should open the `jsconfig` with your `paths` defined.

I see paths working as expected in a simple workspace

**Comment by philiiiiiipp** [comment] 2018-12-15 18:36
I had a similar problem after updating. There seemed to have been an issue with having another node project inside my workspace. 

At least I got a ts error when opening the jsconfig file. It worked again after removing that project.

**Comment by mjbvz** [comment] 2019-01-03 00:31
@zdrummond Can you please explain your project structure more or provide some example code:

- Where is the jsconfig?
- Where is the file that is being imported (`MustacheValidator `)?
- Where is the file that you are adding the import in?

**Comment by zdrummond** [comment] 2019-01-03 20:56
Sure 

**jsconfig**
Is in the root directory 

**MustacheValidator**
app/javascript/lib/forms/MustacheValidator.js

**File importing MustacheValidator**
app/javascript/bundles/Templates/LegalHoldTemplates/Form/components/lib/ValidatingRichEditor.js

**Comment by elegos** [comment] 2019-02-25 09:28
I've got the same problem.

`.vscode/jsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "es6",
        "baseUrl": "./",
        "paths": {
            "audiensRoot/*": ["${workspaceRoot}/app/Resources/assets/js/*"],
            "audiensComponents/*": ["${workspaceRoot}/app/Resources/assets/js/react-components/*"],
        },
        "outFile": "${workspaceRoot}/build/js/**/*.js",
        "mapRoot": "${workspaceRoot}/build/js",
        "sourceMap": true
    },
    "include": [
        "app/Resources/assets/js/**/*"
    ],
    "exclude": [
        "node_modules",
        "test-js/**/*"
    ]
}
```

(note: I've tried with and without `${workspaceRoot}`, replacing it with a dot)
When importing whatever from audiensRoot, the eslint plugin works as expected and doesn't throw me an exception, but IntelliSense is not able to go to the definition.

**Comment by publicJorn** [comment] 2019-04-08 07:54
I have a situation where the alias/paths seem to work, but only for `.js` files and not `.jsx` files.

Directory structure:
```
./
  jsconfig.js
  webpack.config.js
  src/
    js/
      lib/
        cookies.js
        ErrorBoundary.jsx
```

Calling file, somewhere else in the tree:
```javascript
import React from 'react'
import { createCookie, readCookie } from 'lib/cookies'
import ErrorBoundary from 'lib/ErrorBoundary'
```

Webpack config that matters:
```javascript
  resolve: {
        extensions: ['.js', '.jsx'],
        alias: {
            lib: path.join(__dirname, 'src/js/lib'),
        }
    }
```

jsconfig.json
```json
{
    "compilerOptions": {
        "target": "esnext",
        "allowSyntheticDefaultImports": true,
        "checkJs": false,
        "baseUrl": "./",
        "paths": {
            "lib/*": [
                "src/js/lib/*"
            ]
        }
    },
    "include": [
        "./src/**/*"
    ]
}
```

> Removing the `checkJs` property and/or changing `allowSyntheticDefaultImports` to `false` doesn't seem to have effect.

Have to test with yet another extension.. But this seems to indicate that only `.js` files are indexed..

**Comment by publicJorn** [comment] 2019-04-08 08:16
Actually, writing down all this above, helped me rubber duck this issue 🦆 .  I Googled more specifically and found: https://javascriptplayground.com/vscode-go-to-definition-jsx/

For me the issue is resolved by adding `"jsx": "react"` to jsconfig.json. I found that I can remove some other properties, so it becomes:

```
{
    "compilerOptions": {
        "target": "esnext",
        "baseUrl": "./",
        "jsx": "react",
        "checkJs": false,
        "paths": {
            "lib/*": [
                "src/js/lib/*"
            ],
            "theme/*": [
                "src/theme/*"
            ]
        }
    },
    "include": [
        "./src/js/**/*"
    ],
}
```

On a sidenote: searching does take forever. It doesn't matter if I `include` ony the folder that I'm interested in, or `exclude` all others. It does become faster though after you "Go to definition" a few times. VScode probably caches it lazily.

**Comment by tmkasun** [comment] 2019-05-14 09:47
Thanks @publicJorn , adding `"jsx": "react"` to the `jsconf.json` file fixed the  jsx file resolution issue :pray:

**Comment by mjbvz** [comment] 2019-05-25 22:10
@zdrummond Can you please share a small example project that demonstrates this issue?

**Closed** 2019-06-01 22:19 UTC
Labels: javascript, needs more info

**Comment by bm-stschneider** [comment] 2019-06-05 07:28
As an alternative tsconfig seems to work in multi root envs
