### ISSUE TITLE
Explorer: drag and drop of files and folders to other window explorer only copies files

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#104793] opened 2020-08-17 08:34 UTC
I think I would expect the same behaviour when I drag and drop files and folders from the finder where I am asked if the folders are added to the workspace or copied into.

We might not be able to do this given Electron, but I still wonder why files copy while folders do not.

Steps:
* open 2 windows
* drag and drop a selection of files and folders to the other window explorer
* only files get copied in

**Comment by isidorn** [comment] 2020-08-18 09:29
The issue here is that we simply do not allow DnD of folders between VS Code windows currently. So files have no influence here. Simply take one folder in Win A and drag it over to Win B and it will not work.

The issue is that we currently disable it [here](https://github.com/microsoft/vscode/blob/8a9659f3e352001e048937a775ebd04c3a69a104/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L847)
And the original drag event does not contain the data needed to do the folder copy. Thus `extractResources` [here](https://github.com/microsoft/vscode/blob/8a9659f3e352001e048937a775ebd04c3a69a104/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L1212) does not handle it.

Maybe we could change the dragged data such that it just contains the `uri` of dragged folders and when they get dropped we simply do `fileService.copy`?

**Comment by bpasero** [comment] 2020-08-18 13:03
@isidorn yeah I think this code maybe originates from a time where we did not ask the user to copy or add the folder, so it was potentially a dangerous operation with lots of files getting copied. Now that we have this check I would think we can remove it and get the dialog, no?

Given it already works with files, I would expect it would just work for folders too?

**Comment by isidorn** [comment] 2020-08-18 13:12
@bpasero I removed the check and it did not just work. Though assigning to August to investigate more.

**Comment by isidorn** [comment] 2020-09-03 13:41
Moving to debt week.

**Closed** 2020-11-23 11:12 UTC
Labels: bug, file-explorer

**Comment by isidorn** [comment] 2020-11-23 11:13
Pushed a fix for this, it should now work nicely.
Bonus: I handle the explorer drop as a potential adding of a workspace root only if it dropped top level. Which I think makes this flow nicer. Anyways try it out and let me know how it goes
