### ISSUE TITLE
file name with `$(xx)` displayed incorrectly in folder view 

### ISSUE THREAD

**Issue by OpportunityLiu** [microsoft/vscode#77747] opened 2019-07-22 10:08 UTC
Issue Type: <b>Bug</b>

1. create folder with a file named `$(test).txt` in it
2. open the folder in vs code
![图片](https://user-images.githubusercontent.com/13471233/61624724-c241fb80-acab-11e9-93b2-4dfdf8af36cb.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment] 2019-07-29 15:40
Weird. I can reproduce this.
Assigning to next milestone to investigate

**Comment by OpportunityLiu** [comment] 2019-07-30 14:15
try filename `$(bold)`, it will be displayed as a `B` icon.

**Comment by isidorn** [comment] 2019-08-08 15:10
The issue is that the `octiconLabel` `expand` function strips the `$(test)` from the file name [here](https://github.com/Microsoft/vscode/blob/079aef1ec5549171717decf30a9cb3e5b8aeee18/src/vs/base/browser/ui/octiconLabel/octiconLabel.ts#L11).
This happens for all `highlightedLabels`.
Assigning to @jrieken and @joaomoreno as the authors of the regex.

**Comment by jrieken** [comment] 2019-08-08 15:33
Nothing to be tweak in the regex. @isidorn you must encode those characters or disable octicons-support when using the labels.

**Comment by isidorn** [comment] 2019-08-08 15:45
@jrieken thanks. 
I have disabled ocitcon support in the explorer.
I do not think anyone was relying on this. I might be wrong though.

**Closed** 2019-08-08 15:46 UTC
Labels: bug, file-explorer

**Comment by jrieken** [comment] 2019-08-08 15:52
> I might be wrong though.

I'd say you are right because you don't control the input strings and if my file is called $(zap).txt it shouldn't show as ⚡️.txt

**Comment by jrieken** [comment] 2019-08-08 16:57
ping @bpasero I believe that `ResourceLabels` should never default to supporting octicons, esp. when it shows uris/paths

**Comment by isidorn** [comment] 2019-08-09 07:49
Yeah fixing it on that layer makes more sense.
@bpasero let me know if you want me to change the ResourceLabel

**Comment by bpasero** [comment] 2019-08-09 08:38
@isidorn this does not seem to originate from `ResourceLabel` but rather `HighlightedLabel` which probably originally was only used in quick open where we always supported octicons. Imho I would start there and disable octicons everywhere it does not make sense. 

For example, I can see the `HighlightedLabel` being used in markers view as well, outside of the `ResourceLabel`. I am not sure how much sense Octicons make sense there either.

**Comment by isidorn** [comment] 2019-08-09 08:45
@bpasero I have changed that the supportsOcticons is by default false.

I went through all the clients. Here are the only clients which I set to support octicons: quick open, suggest widget.

Clients which do not support octicons: explorer, custom trees (as before), outline tree, call hierarchy tree, references tree.

Let me know if you want me to change some clients to support octicons @jrieken
