### ISSUE TITLE
Terminal: ANSI escape sequences no longer display correctly on Windows

### ISSUE THREAD

**Issue by rewrking** [microsoft/vscode#146474] opened 2022-03-31 20:14 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Set `"terminal.integrated.minimumContrastRatio": 1`:
2. All terminal colors and most ansi sequences would be expected, but this is not the case.
3. Get this file: https://gist.github.com/rewrking/f797bd19e9ecc44fa1c646b3f7b795c0

Steps for Git Bash inside of VS Code:

4. Run `cat print_term.txt` where the file in step 3 was saved

Steps for Powershell inside of VS Code:

4. Run `Get-Content -Path .\print_term.txt` where the file in step 3 was saved

Right now, my VS Code and Windows Terminal setup use the same color scheme. Both Git Bash and Powershell display the same way in each. In order to test this correctly, all 16 colors need to be unique.

This is what displays in VS Code on Windows:

![ansi_vscode](https://user-images.githubusercontent.com/4885461/161136824-b49f1d8e-218b-4827-870f-af953cc390d0.png)

This is what displays in Windows Terminal:

![ansi_windows_terminal](https://user-images.githubusercontent.com/4885461/161136874-33c45530-5394-4e5f-92cd-9fdae033590c.png)

I would expect underlined, strikethrough, dim and italic to be consistent, but also it seems the ansiBlack background is ignored entirely. blink never worked in VS Code, so I have no expectations there. I also tested this on MacOS and Linux (zsh) and the output seems correct on those platforms.

Maybe relates to: https://github.com/microsoft/vscode/issues/146406

**Comment by Salloom99** [comment] 2022-03-31 20:51
I noticed this issue with oh-my-posh module which changes the way powershell looks and it seems to look fine in the terminal and not on vs code integrated pwsh

**Comment by Tyriar** [comment] 2022-04-01 10:25
I don't think https://github.com/microsoft/vscode/issues/146406 relates to this. This looks like the older version of conpty that you're on due to being on Windows 10 just lacks those features that Windows Terminal added later (which bundles the latest version of conpty). See my generic response to these types of issues below:

---

This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2022-04-01 10:25 UTC
Labels: new release

**Comment by rewrking** [comment] 2022-04-01 11:21
???

I have the latest Windows 10 updates and Windows Terminal updates. What do I need to do to fix the problem?

**Comment by rewrking** [comment] 2022-04-01 11:55
@Tyriar 

> Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)

Did you read my post? It's not a problem in Windows Terminal at all. 

I'm on Windows 10 Version 10.0.19041.1415. 
Windows Terminal Preview Version 1.13.10733.0 (again, this works perfectly)

Why would I need to open the issue with that team? At a loss as to what I can actually do here. You're literally asking me to open an issue with them and say there's a problem with VS Code. Sounds like a MS process issue to me.

**Comment by Tyriar** [comment] 2022-04-01 12:33
Please re-read what _I_ said:

> If you cannot reproduce in Windows Terminal, chances are **it's fixed in a later version of Windows**. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

I followed the first paragraph with my generic response to conpty issues to save time. You can't do anything until you update Windows to get the later version of conpty we use, it's a system utility that is provided by Windows but Windows Terminal bundles the latest version in their package.

**Comment by levrik** [comment] 2022-04-01 12:34
@rewrking I think you misunderstood the comment by @Tyriar. Windows Terminal seems to bundle a version of ConPTY while VS Code uses the version that ships with the OS which has a bug.

**Comment by rewrking** [comment] 2022-04-01 12:42
> You can't do anything until you update Windows to get the later version of conpty we use, it's a system utility that is provided by Windows but Windows Terminal bundles the latest version in their package.

That makes 10x more sense than your canned response... but it's still frustrating. Why can't VS Code bundle its own version too? Why can't that component be updated when Windows Terminal gets installed? Why can't it get updated when VS Code gets installed? This kind of thing burdens users with the responsibility of figuring out why unrelated software has issues, when the problem at at hand (terminal colors/styles) is so small by comparison.

**Comment by Tyriar** [comment] 2022-04-01 12:53
@rewrking I get the frustration. The reasons are:

- When we evaluating this possibility we determined it would involve more effort than we're willing to invest.
- It would be more risk than it's worth, IIRC when I reached out to their team they recommended against it.

If their team provided an easy way for us to consume and bundle the latest version it would be a different story, but the model they went for was to ship it in Windows and Windows Terminal is basically their platform for testing early versions before they hit Windows.

So currently you need to update to Windows 11 and we sometimes have to wait up to a year before a fix lands for VS Code in the Windows 11. Luckily most issues at this point are non-critical like this one.

**Comment by rewrking** [comment] 2022-04-01 13:03
Got it. Thanks for explaining that part. Guess I'll sulk and consider upgrading my PC for a better terminal experience... 😂

**Comment by Tyriar** [comment] 2022-04-01 13:08
Yeah, I was forced to upgrade my CPU recently. Greatly improved my overall coding experience jumping 8 Intel generations though 🤯

**Comment by rewrking** [comment] 2022-04-01 15:28
For anyone else looking for a "fix", this is what you have to do right now:

Copy `conhost.exe` and `ConhostV1.dll` (in System32) from a Windows 11 machine (version >= 10.0.22000) to the Windows 10 machine (version < 10.0.22000). Obviously not for everybody, but it seems to work so far.

**Comment by jenewland1999** [comment] 2022-04-01 19:17
Hi @Tyriar, I wanted to chime in on this issue as I believe I'm experiencing the same thing, but unlike @rewrking, I'm on Windows 11 (specifically v21H1 OS Build 22000.556). If, as you say, this is an issue with an older version of conpty that is bundled with Win10, why am I facing the same issue in Win11? 

Can this be explained by something else or is there a later build of conpty in insider builds of Win 11 that aren't in public version I'm using?
