### ISSUE TITLE
VSCode incorrectly treats a division as part of a regexp

### ISSUE THREAD

**Issue by ZEDCWT** [Microsoft/vscode#15725] opened 2016-11-18 12:54 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 7, x86

Steps to Reproduce:

Open any js file and insert `2 / 1 + (3 / (3))` into a single line
![r](https://cloud.githubusercontent.com/assets/7867810/20430443/495a7a4a-adcf-11e6-9ef1-49b6cd6e44c4.png)
It is obvious that it failed to judge whether it is a division operator or a mark for regexp

**Comment by ramya-rao-a** [comment] 2016-11-18 18:26
Closing as duplicate of #15334. The fix would be in in the insiders build by tomorrow. Please give it a try

**Closed by ramya-rao-a** 2016-11-18 18:26 UTC
