### ISSUE TITLE
Files created from Explorer ignore files.encoding setting

### ISSUE THREAD

**Issue by PrzemyslawKlys** [microsoft/vscode#112377] opened 2020-12-12 22:24 UTC
I have following settings 

```json
    "files.encoding": "utf8bom",
```

![image](https://user-images.githubusercontent.com/15063294/101996198-80668a80-3cd0-11eb-8a9e-d1b5dd0edd26.png)

I expect all my files created with UTF8 with BOM. 

It seems creating files via Explorer ignores setting UTF 8 with BOM and sets it always to UTF8. It would seem UTF 8 equals UTF 8 with BOM according to Explorer create file process. Changing in options utf8 to utf16 works correctly tho so it reads configuration properly. 

- VSCode Version: 1.52
- OS Version: Windows 10

Steps to Reproduce:

1. Create any file via Explorer 
2. Notice it's UTF 8

What works correctly:

1. Create a file via File -> New File
2. Notice it's UTF8 with BOM

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment] 2020-12-14 10:28
@bpasero I think I am not doing anything special from the explorer, is there some flag I shoud pass to repsect the flag.
Anyways also assigning this issue to you, since it might be on your side

**Comment by bpasero** [comment] 2020-12-14 10:50
@isidorn this is a regression, previously the explorer was using `ITextFileService` when creating a file and this would properly set the encoding. I think you are not doing this anymore when you adopted the bulk edit service.

https://github.com/microsoft/vscode/blob/e5a624b788d92b8d34d1392e4c4d9789406efe8f/src/vs/workbench/contrib/files/browser/fileActions.ts#L899

**Comment by bpasero** [comment] 2020-12-14 10:52
The text file service is encoding the value that it gets here:

https://github.com/microsoft/vscode/blob/3517c02303b6f54de940fe32f523e3fc865b8042/src/vs/workbench/services/textfile/browser/textFileService.ts#L151-L155

**Comment by isidorn** [comment] 2020-12-14 11:02
I think we can live with this regression without puting it in the recovery build.
@jrieken I can look into adding this in the `CreateOperation` in the `BulkFileEdits` if that works for you

**Comment by isidorn** [comment] 2020-12-18 19:01
@bpasero glanced a bit into this, and the only method that the `TextFileService`exposes for encodings is `encoding.getPreferredWriteEncoding`. So I can get the encoding but how do I combine it with my `VSBuffer` `content` so I pass the right thing when I call the `workingCopyFileService.create`?

Or alternativly is it possibe to expose `getEncodedReadable` from the `textFileService` to the outside?

**Comment by bpasero** [comment] 2020-12-21 06:54
@isidorn if you deal with text files, you should use `ITextFileService`, in this case:

https://github.com/microsoft/vscode/blob/3517c02303b6f54de940fe32f523e3fc865b8042/src/vs/workbench/services/textfile/common/textfiles.ts#L97-L97

This will eventually call the working copy file service with the correct `VSBuffer`:

https://github.com/microsoft/vscode/blob/3517c02303b6f54de940fe32f523e3fc865b8042/src/vs/workbench/services/textfile/browser/textFileService.ts#L151-L155

**Comment by isidorn** [comment] 2021-01-07 16:50
@bpasero This makes sense, however the `textFileService` currently only supports to `create` one resource. So I would need to change the `create` method to accept multiple resources, since otherwise too many events will get fired.
Alternative is to add a new method in the `textFileService` which would accept mulitple resources.

Let me know what you think and what you prefer. Thanks!

**Comment by bpasero** [comment] 2021-01-08 07:26
I think it would be quite easy to change `ITextFileService#create` to allow for an array of resources.

**Closed** 2021-01-12 15:34 UTC
Labels: bug, file-explorer, file-io, regression
