### ISSUE TITLE
Have a serious issue here not able to save any file

### ISSUE THREAD

**Issue by NTPLThavarajan** [Microsoft/vscode#13944] opened 2016-10-18 13:46 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: AESSoft.aessoft-class-autocomplete-0.1.0, AndersEAndersen.html-class-suggestions-1.0.1, andischerer.theme-atom-one-dark-0.0.1, christian-kohler.npm-intellisense-0.1.4, christian-kohler.path-intellisense-1.1.0, cssho.vscode-svgviewer-1.2.0, danwahlin.angular2-snippets-0.10.15, donjayamanne.githistory-0.1.0, EditorConfig.EditorConfig-0.3.3, eg2.tslint-0.5.39, euntaik.theme-etinum-0.1.3, felixfbecker.php-debug-1.9.7, fknop.vscode-npm-3.3.0, hdg.live-html-previewer-0.0.1, HookyQR.beautify-0.4.1, HvyIndustries.crane-0.2.1, JaimeOlivares.yuml-2.8.0, jakethashi.vscode-angular2-emmet-1.0.9, johnpapa.Angular2-1.0.2, Kasik96.format-php-1.1.2, linyang95.php-symbols-0.1.2, lonefy.vscode-JS-CSS-HTML-formatter-0.2.1, ms-vscode.PowerShell-0.7.2, msjsdiag.debugger-for-chrome-1.2.2, Persephona.theme-dreamweaverweb-1.5.4, robertohuertasm.vscode-icons-3.0.5, seanmcbreen.Spell-0.8.6, self-technologies.plant-uml-ext-1.0.0, sidthesloth.svg-snippets-1.0.0, spywhere.guides-0.5.1, UVBrain.Angular2-0.3.5, vstirbu.vscode-mermaid-preview-0.4.1

Steps to Reproduce:

1.change the file and save
2. it just flicker save continuously
The worst part is if i closed the flikkering file , the content is updated in another file
if you want a gif i will share it

**Comment by roblourens** [comment] 2016-10-18 15:13
A gif would be helpful. Not sure I understand the flickering.

**Comment by bpasero** [comment] 2016-10-19 05:45
@NTPLThavarajan 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by NTPLThavarajan** [comment] 2016-10-19 05:52
this is the problem with extensions
[Vscode save preoblem.gif](https://github.com/NTPLThavarajan/MyFiles/blob/master/vscodeproblem.gif)

i think @bpasero  is right
after i run the code with specified command it is not happen
but how could i found which extension cause this bug

**Comment by bpasero** [comment] 2016-10-19 06:04
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by bpasero** [comment] 2016-10-19 06:05
@jrieken fyi since you are hunting down extensions that cause save issues

**Closed by bpasero** 2016-10-19 06:04 UTC
Labels: needs more info

**Comment by NTPLThavarajan** [comment] 2016-10-19 06:12
dear @bpasero  thanks but how could i found the trouble causing extension,
i have nearly 20 plus extensions, can you suggest a way fo find that problamatic extension, it's really annoying, if i found it, i can uninstall that particular extension

**Comment by jrieken** [comment] 2016-10-19 07:19
Pretty sure it's this one: https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/30
