### ISSUE TITLE
[Insider/1.53.0] Find editor.action.nextSelectionMatchFindAction seeds from the Nearest Word, not from the last searched word/string

### ISSUE THREAD

**Issue by swinder0161** [microsoft/vscode#113830] opened 2021-01-05 16:08 UTC
- VSCode Version: 1.53.0-insider
- Commit: a48ef56fbf7767f55a193d7d5687addd1fc9239c
- Date: 2021-01-05T05:22:22.983Z
- Electron: 11.1.0
- Chrome: 87.0.4280.88
- Node.js: 12.18.3
- V8: 8.7.220.29-electron.0
- OS Version: Darwin x64 20.2.0:

Steps to Reproduce:
1. Double click on a function name in the code say "function1", press F3.
2. On the found part, move the cursor and click beside any other string say "string1", without selecting it, I would expect VSCode shall still be searching for "function1".
3. Press F3, **VSCode will go to the next occurence of "string1" and not "function1"**
**Example:**
`Void function1( type arg1, type string1 );`

Does this issue occur when all extensions are disabled?: Yes

Not sure why https://github.com/microsoft/vscode/issues/107144 was closed without resolving the issue.

VSCode will force to seed the word near cursor in normal editor, which is not expected. Reference: UltraEdit.

https://user-images.githubusercontent.com/397543/103669402-4ff7d080-4f9e-11eb-9673-537c5c8866e8.mov

**Comment by swinder0161** [comment] 2021-01-05 16:52
@aeschli Hi Friend, adding you here based on interaction in https://github.com/microsoft/vscode/issues/107144

**Comment by swinder0161** [comment] 2021-01-06 16:46
@alexdima @bpasero please help to review the pull request: https://github.com/microsoft/vscode/pull/113923

**Comment by swinder0161** [comment] 2021-01-07 21:26
@rebornix Please provide your plan on this PR #113923

**Comment by hediet** [comment] 2021-01-09 19:47
I cannot reproduce your issue:

![f75142b4-bb2e-4c2a-afc9-906504b26143](https://user-images.githubusercontent.com/2931520/104107360-cd338600-52bb-11eb-8a97-334301e50314.gif)

Version: 1.53.0
Commit: Unknown
Date: Unknown
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by swinder0161** [comment] 2021-01-11 11:38
I am not sure what settings you have, but in default version, problem is there.
But as pointed in #107144 I am not alone who pointed this issue and I actually confirmed from code that problem is there and made a PR also.

**Comment by swinder0161** [comment] 2021-01-11 11:39
Here is my settings.json

{
    "editor.wordWrap": "on",
    "editor.renderLineHighlightOnlyWhenFocus": true,
    "search.seedWithNearestWord": false,
    "files.autoGuessEncoding": true,
    "files.eol": "\n",
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "window.title": "${dirty}${activeEditorLong}${separator}${rootName}${separator}${appName}",
    "window.openWithoutArgumentsInNewWindow": "off",
    "window.doubleClickIconToClose": true,
    "window.nativeTabs": true,
    "search.showLineNumbers": true,
    "workbench.editor.closeOnFileDelete": false,
    "workbench.editor.wrapTabs": true,
    "workbench.editor.openPositioning": "last",
    "workbench.editor.highlightModifiedTabs": true,
    "editor.find.globalFindClipboard": true,
    "search.seedOnFocus": false,
    "editor.occurrencesHighlight": true,
    "editor.selectionHighlight": true,
    "editor.fontSize": 16,
    "window.zoomLevel": -0.5,
    "editor.find.seedSearchStringFromSelection": true,
}

**Comment by hediet** [comment] 2021-01-11 12:05
> I am not sure what settings you have, but in default version, problem is there.
> But as pointed in #107144 I am not alone who pointed this issue and I actually confirmed from code that problem is there and made a PR also.

Note that (1) `editor.action.moveSelectionToNextFindMatch` (ctrl+k ctrl+d) is not (2) `editor.action.nextMatchFindAction` (F3)!
I don't know how these actions are specified, but I cannot reproduce your issue with (2). However, I can reproduce it with (1) and the issue you linked is only about (1)!
I think your linked issue was precisely closed as there is (2) if you don't wan't the behavior of (1).

**Comment by swinder0161** [comment] 2021-01-11 17:46
I know now why you cannot reproduce:

editor.action.nextSelectionMatchFindAction does 2 things instead of 1
1) seeds search string from current selection
2) if no selection, it seeds the search string from the work near cursur, by near i mean, in start of word, in middle of work or in end of word.

My Patch will separate these 2 actions of same key (ctrl+F3) or (cmd+F3) based on new setting I added.

Know you try ctrl+F3 on the string and provide your feedback.

**Comment by swinder0161** [comment] 2021-01-15 16:36
@rebornix This is genuine usecase and a flaw which can be corrected. May I know your feedback on this.

@bpasero @rebornix @aeschli

**Comment by swinder0161** [comment] 2021-01-20 04:50
@bpasero It is quite discouraging to not get any feedback, good or bad, for genuine issues.

**Comment by swinder0161** [comment] 2021-02-06 16:05
@bpasero @rebornix Is there any scope of getting this patch merged?
Not a big change but really needed.

Please consider

**Comment by hediet** [comment] 2021-02-06 16:10
What happens if you do this:

keybindings.json
```
{
"key": "f3",
"command": "editor.action.nextMatchFindAction",
"when": "editorFocus"
},
```

**Comment by swinder0161** [comment] 2021-02-06 16:50
@hediet it actually stopped seeding the find from selection

see video


https://user-images.githubusercontent.com/397543/107124350-6c529a00-68c9-11eb-8fa1-dd83704a74a4.mov

**Comment by swinder0161** [comment] 2021-02-17 18:38
Is there any scope for merging my patch? @bpasero

**Comment by swinder0161** [comment] 2021-03-01 12:25
I am too confused why a small change has so much resistance.

believe me, this is a required feature.

I have checked in UltraEdit and it works as I have explained.

**Closed** 2021-07-28 01:01 UTC

**Comment by rebornix** [comment] 2021-07-28 01:02
The value of `editor.find.seedSearchStringFromSelection` is now changed to `'never', 'always', 'selection'`.
