### ISSUE TITLE
Custom editor right mouse button

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#49291] opened 2018-05-06 02:04 UTC
Can DIY the editor right mouse button? Allows users to customize their own menu; for example, remove some unused, add some commonly used extended shortcuts to the editor right-click menu。

![tim 20180506095442](https://user-images.githubusercontent.com/20437381/39669060-97b4f218-5113-11e8-85e0-8d4883ed6b53.png)

E.g：
"editorRightdiymenu":"true",//Function switch（When it is true, only the system default menu is displayed, and the following settings are enabled）
"editorRighthotkeymenu":{
  "crl+alt+f":"快速格式/Quick format",//hotkey+Language
  "......":"..........",
  "......":"..........",
  "......":"..........",
}

**Comment by rebornix** [comment] 2018-05-07 02:46
Duplicate of https://github.com/Microsoft/vscode/issues/3130

**Closed** 2018-05-07 02:46 UTC
Labels: *duplicate
