### ISSUE TITLE
New Quick Open widget cannot search for full path to file

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#94871] opened 2020-04-10 06:33 UTC
- VSCode Version: 1.44.0
- OS Version: Windows 10 Pro 1809 (and VS Code Remote host: Ubuntu 16.04.5)

Steps to Reproduce:

1. Press `ctrl+e` or `ctrl+p` to search for a file. Enter a full path like `server/path/to/file.js`
2. No results are shown.

This is a common scenario where you might get a link to a file from e.g. output logs in CI machinery, and you want to open that file quickly, you copy&paste the path from the console into `ctrl+p`. This worked perfectly fine before 1.44.0 so I assume the new "Quick Open rewrite" is in works here: https://code.visualstudio.com/updates/v1_44#_quick-open-rewrite

Does this issue occur when all extensions are disabled?: Yes

**Comment by poebrand** [comment] 2020-04-10 06:43
Same issue here.

**Comment by bpasero** [comment] 2020-04-10 08:15
@thernstig @poebrand I would appreciate a complete instruction for me how to reproduce, preferably with a sample repo to clone, or even using `vscode` repo itself. 

It seems to me you are trying on Windows and you are using slash instead of backslash. Though I do not see an issue:

![image](https://user-images.githubusercontent.com/900690/78975353-36f7e700-7b14-11ea-8e23-93eb6a258b3d.png)

**Comment by thernstig** [comment] 2020-04-10 08:46
I cannot provide a repro of my repo, since it is private.

But you are correct in your assertion. I am using forward slash because I am using remote SSH to an Ubuntu host, where they are forward slash.

**Comment by bpasero** [comment] 2020-04-10 09:13
@thernstig a minimal repro would still be great and especially of interest if this reproduces only against a remote (such as SSH) or locally as well. Thans

**Comment by poebrand** [comment] 2020-04-10 21:55
My repo is also a private. However, in my case I wasn't entering a path. I was just typing in the name of a JavaScript file: `NotifyMe.js`

The animation under the search bar just kept going. Indefinitely. I tried closing VS Code and restarting the computer... issue did not go away.

**Comment by bpasero** [comment] 2020-04-11 06:18
I really need a repro, sorry. Otherwise I cannot be of any help.

**Comment by thernstig** [comment] 2020-04-12 15:03
@bpasero This is a minimum repro that does not work, see image.

![path](https://user-images.githubusercontent.com/30827238/79072057-411a1100-7cdf-11ea-9bc6-88a54e024278.png)

Windows 10 Pro 1809 (17763.1131)
Remote: Ubuntu 16.04.5 LTS

**Comment by bpasero** [comment] 2020-04-13 06:00
This looks like a remote issue to me, given the SSH decoration.

**Comment by bpasero** [comment] 2020-04-16 05:27
A regression, but not sure this being a candidate or not. Will push a fix for April and people can switch over to insiders to benefit. 

Previously we would allow a file to appear in quick open, even if our fuzzy scorer produced no match. This became more strict with the rewrite. Suggested fix is to treat "`/`" and "`\`" equal in the scoring logic.

**Closed** 2020-04-16 05:43 UTC
Labels: bug, remote, search

**Comment by ThiefMaster** [comment] 2020-04-17 09:35
Works fine in the latest insiders, thanks for the quick fix!
