### ISSUE TITLE
smartSelect.grow not working in HTML Files

### ISSUE THREAD

**Issue by abderrahmane-tj** [Microsoft/vscode#7211] opened 2016-06-04 11:25 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. open html file
2. alt+shift+RightArrow

works for me in other language modes, but not in HTML

**Comment by aeschli** [comment] 2016-06-15 19:42
duplicate of #4101

**Closed by aeschli** 2016-06-15 19:42 UTC
