### ISSUE TITLE
Extension Development Host messes up layout after going to debug tab

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5582] opened 2016-04-20 23:27 UTC
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Create a VS Code extension following the [guide doc](https://code.visualstudio.com/docs/extensions/example-hello-world)
2. Debug 'Launch Extension'
3. In the Dev Host click the debug tab to open it
4. Click Explorer tab, click search tab

Actual:
The layout of the explorer and search sections are not in the right place. Also if you click too fast from debug to explorer, it will not change the view to the explorer.

![extensiondevhost1](https://cloud.githubusercontent.com/assets/12900364/14693543/a0109138-0714-11e6-81b3-16e83bce30f3.PNG)

![extensiondevhost2](https://cloud.githubusercontent.com/assets/12900364/14693545/a61432b0-0714-11e6-8ba7-a4c0a89a0078.PNG)

**Comment by dbaeumer** [comment] 2016-04-21 06:49
@bpasero assigning to you since all views seem to be affected. Looks like a workbench issue.

**Comment by bpasero** [comment] 2016-04-21 06:59
I can reproduce for any empty folder. @isidorn could it be that debug viewlet crashes in empty folder setup?

shell.ts:454 Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/parts/debug/browser/debugViewlet.js:4:6062
    at __dirname.undefined.t.Class.define.then (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:28372)
    at t.setVisible (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/parts/debug/browser/debugViewlet.js:4:6016)
    at file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:87:27329
    at __dirname.undefined.t.Class.define.then (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:28372)
    at t.showComposite (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:87:26524)
    at file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:87:24776
    at Object.h [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:21887)
    at Object.__dirname.undefined.M.enter (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:25049)
    at __dirname.undefined.t.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:26875)

**Closed** 2016-04-21 07:46 UTC
Labels: important, v-test

**Comment by isidorn** [comment] 2016-04-21 07:48
@bpasero yes, debug crashed for no folder workspace
This is a serious regression, not sure if we want to push it out to our insiders - marking as candidate to consider it.

ping @egamma

**Comment by egamma** [comment] 2016-04-22 14:16
@isidorn 

Using the debug viewlet in the empty folder setup is a corner case. We will do another insider update on Monday and this can wait until then.
