### ISSUE TITLE
CompletionItem - conflict between commitCharacters and a SnippetString insertText

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#79373] opened 2019-08-17 21:28 UTC
Issue Type: <b>Bug</b>

1. In a language extension implement a CompletionItemProvider that returns the following CompletionItem:

```
{
 label: '$Piece()',
 kind: vscode.CompletionItemKind.Function,
 filterText: '$Piece',
 commitCharacters: ['('],
 insertText: new vscode.SnippetString('\\$Piece(${1:expr}, ${2:dlm}, ${3:int})$0')
}
```
2. Enter the keystrokes shown in the following animation:
![junk](https://user-images.githubusercontent.com/6726799/63217342-ae6ba700-c13c-11e9-9d17-1ef3f0863fc7.gif)

In the first part of the recording, when the `(` specified in `commitCharacters` accepts the suggestion notice how VSCode injects that character into the first field of the `insertText` snippet. This is unwanted.

In contrast, see how the CompletionItem behaves as intended if the suggestion is accepted by pressing 'Tab'.

I acknowledge that altering this behaviour would result in a breaking change. So I propose enhancing `commitCharacters` to accept as an alternative an array of objects structured as `{character: string, inject: boolean}`

@jrieken what do you think?

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment] 2019-08-17 21:59
Another strategy might be to add an `insertSnippet` method to [`TextEdit`](https://code.visualstudio.com/api/references/vscode-api#TextEdit) (equivalent to that method that already exists on `TextEditor`). Then my `CompletionItem` could invoke this via `additionalTextEdits` and specify a suitably-shortened snippet e.g.

`new vscode.SnippetString('${1:expr}, ${2:dlm}, ${3:int})$0')`

**Comment by jrieken** [comment] 2019-08-19 16:44
/duplicate of https://github.com/microsoft/vscode/issues/42544

**Closed** 2019-08-19 16:45 UTC
Labels: *duplicate, new release, suggest

**Comment by gjsjohnmurray** [comment] 2019-08-19 17:02
@jrieken thanks for finding the dup. What do you think of my proposal about enhancing `commitCharacters`? Would you accept a PR? I'm asking here rather than on #42544 because that one is locked despite being open.

**Comment by jrieken** [comment] 2019-08-20 07:34
Ops, unlocked. Yeah, the proposal does seem reasonable but I didn't spend too much time thinking of it. Tho, it won't be easy to implement because commit characters work with a typing listener that has no chance of preventing. Some "delete that character before inserting the snippet" logic will be needed...
