### ISSUE TITLE
TypeScript: Code completion for string literal property does not honor quote style

### ISSUE THREAD

**Issue by unional** [microsoft/vscode#81138] opened 2019-09-19 05:04 UTC
- VSCode Version: 1.38.1
- OS Version: Windows 2016

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/3254987/65214765-0cebb400-da60-11e9-9374-5afe8ba23e04.png)

The quote style is set to single quote (you can see that on the right), but for completing `@type`, it uses double quote.

```ts
type X = {
  '@type': string
}
let x: X = { /* code complete here */ }
```

**Comment by mjbvz** [comment] 2019-09-19 15:14
Duplicate of https://github.com/microsoft/TypeScript/issues/33377

**Closed by mjbvz** 2019-09-19 15:14 UTC
