### ISSUE TITLE
Hyper-V Windows VM: Hangs after updating to 1.6.1

### ISSUE THREAD

**Issue by nikoudel** [Microsoft/vscode#13882] opened 2016-10-17 12:57 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 2012 R2

Steps to Reproduce:
1. Click "Upgrade" from the top menu (gets upgraded from x to 1.6.1)
2. When Code restarts, it hands (menus still get opened but nothing happens) and CPU goes to 100%

![codehang](https://cloud.githubusercontent.com/assets/1636683/19438374/4be1a362-9482-11e6-9067-059129539f66.png)

**Comment by bpasero** [comment] 2016-10-17 13:16
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by nikoudel** [comment] 2016-10-17 13:22
`code --verbose` outputs this:
`[main 4:18:15 PM] Starting VS Code in verbose mode
[main 4:18:15 PM] from: c:\Program Files (x86)\Microsoft VS Code\resources\app
[main 4:18:15 PM] args: { _: [],
  paths: [],
  performance: false,
  verbose: true,
  debugPluginHost: undefined,
  debugBrkPluginHost: undefined,
  logExtensionHostCommunication: false,
  'new-window': false,
  'reuse-window': false,
  goto: false,
  diff: false,
  extensionHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  'disable-extensions': false,
  'open-url': undefined,
  locale: undefined,
  wait: false }`

but I can't open the console - nothing happens when clicking **Help | Toggle Developer Tools**

**Comment by bpasero** [comment] 2016-10-17 13:43
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by crussell85** [comment] 2016-10-17 14:41
Im getting this problem too, also running Windows 2012 R2. When loading VS Code its process hits 100% and never loads.

I tried disabling extensions, this didnt help.

**Comment by crussell85** [comment] 2016-10-17 14:44
Ive noticed that in task manager "Processes" tab VS Code runs a process in the Apps and the Background processes section, its the one running as a background process that utilises 100% processor

**Comment by bpasero** [comment] 2016-10-17 15:00
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by crussell85** [comment] 2016-10-17 15:41
Hi,

The command line for the high usage process is - 
"C:\Program Files (x86)\Microsoft VS Code\Code.exe" --type=renderer --no-sandbox --primordial-pipe-token=76E48D40E143D3C279C5759BC25F3B58 --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --node-integration=true --background-color=#1E1E1E --enable-pinch --device-scale-factor=1 --num-raster-threads=1 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --mojo-channel-token=F7DD78D7CB6E0A00743E68ED7D5287A3 --mojo-application-channel-token=ABA33A8650F3722F9E8BE582CA43B601 --channel="4004.0.325943118\2062908526" --mojo-platform-channel-handle=1556 /prefetch:1


Something else to note - I had to power up the problem machine to get this information and the first time i loaded VS Code it opened perfectly. I closed it and then re-created the problem when trying to load VS Code for the second time.

Thanks

**Comment by nikoudel** [comment] 2016-10-18 04:59
Disabling extensions didn't help me either. The exact command line is `"C:\Program Files (x86)\Microsoft VS Code\Code.exe" --type=renderer --no-sandbox --primordial-pipe-token=C1FAC92AAA2C67F7C262339F942BE816 --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --node-integration=true --background-color=#1E1E1E --enable-pinch --device-scale-factor=1 --num-raster-threads=1 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --mojo-channel-token=470B4CF465EBBD1A82AE8FE1A481297B --mojo-application-channel-token=0600547F98587953AFD20F70AEE582E3 --channel="8048.0.268205701\998817174" --mojo-platform-channel-handle=1584 /prefetch:1`.

**Comment by bpasero** [comment] 2016-10-18 05:08
@nikoudel @crussell85 does this happen for any folder you open or only a specific folder? Does it reproduce when you do not open a folder but just a file?

**Comment by nikoudel** [comment] 2016-10-18 05:22
It hangs in any case. Something new just happened when I ran `code someFile.txt` - the toolbar suggesting to open release notes appeared but it's empty too. And high CPU as usual.

![codehangreleasenotes](https://cloud.githubusercontent.com/assets/1636683/19465296/ad828ecc-950b-11e6-80b2-aa4bda1e666f.png)

**Comment by bpasero** [comment] 2016-10-18 05:35
@nikoudel @crussell85 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by nikoudel** [comment] 2016-10-18 06:08
Both stable and nightly builds apper to behave the same way. I've downloaded and extracted the zip archives (stable and nightly). Code starts fine (no hanging, can open files) for the first time but when restarted (one or more times), it hangs.

**Comment by bpasero** [comment] 2016-10-18 08:23
@nikoudel does this mean when you restart the OS and start Code once, everything is fine and then when you exit Code and start it again it behaves bad until you restart the OS?

**Comment by nikoudel** [comment] 2016-10-18 08:33
Not quite. It starts fine only the first time after extracting the archive. Then it hangs after exiting and starting the editor again (I don't have permission to restart OS). Then it works again (once) if I delete the folder where I previously extracted the archive and extract it from scratch again. The installation must be changing its state upon first run which results in hanging on following startups.

**Comment by bpasero** [comment] 2016-10-18 08:39
Are you able to bring up developer tools for a CPU profile?

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by nikoudel** [comment] 2016-10-18 10:36
No, I can't Toggle Developer Tools - nothing happens when I click that menu item.

**Comment by bpasero** [comment] 2016-10-18 12:56
@nikoudel when you start it for the first time, does it reproduce if you open additional windows? or do you really need the full act of exit and start again?

**Comment by nikoudel** [comment] 2016-10-18 14:05
Yes, one of the Code.exe process seems to go into infinite loop even on the first start when I do some stuff in the editor (like open new tabs, edit and save text).

I tried to run the profiler like you described but it doesn't record whatever is causing the high cpu usage. Saving the profile doesn't work (outputs empty file) so I attach the screenshot - it's idle all the time although the cpu is constantly at 100%.

![codehangsprofile](https://cloud.githubusercontent.com/assets/1636683/19480949/ff2c06b0-9554-11e6-8434-4843f2ff6a56.png)

**Comment by bpasero** [comment] 2016-10-19 05:04
@nikoudel does it reproduce if you run `code --disable-gpu` from the command line?

**Comment by nikoudel** [comment] 2016-10-19 06:00
Yes, still hangs.
Btw, don't know if it matters, but the OS runs in a Microsoft Hyper-V virtual machine.

**Comment by bpasero** [comment] 2016-10-19 06:04
@nikoudel does this not reproduce with 1.5.x our previous version?

**Comment by nikoudel** [comment] 2016-10-19 06:13
Yes, it did not reproduce before 1.6.1. But I can check again. Where can I get an older version as zip archive so I don't need to install it?

**Comment by nikoudel** [comment] 2016-10-19 06:33
I've uninstalled 1.6.1 and installed 1.5.3 - no hanging.

**Comment by crussell85** [comment] 2016-10-19 07:38
If it helps im running in an EC2 instance

**Comment by bpasero** [comment] 2016-10-19 07:43
@crussell85 I assume that is also Hyper-V VM?

**Comment by crussell85** [comment] 2016-10-19 07:53
Its an amazon VM running Windows 2012 R2

**Comment by bpasero** [comment] 2016-10-19 09:05
Does this reproduce with Atom editor (pick the beta version please)? If so this would point to an Electron issue.

**Comment by nikoudel** [comment] 2016-10-19 09:47
Yes, I can reproduce it with Atom too.

**Comment by bpasero** [comment] 2016-10-19 11:02
Then I suggest to report this to https://github.com/atom/electron

**Comment by nikoudel** [comment] 2016-10-20 19:52
I've created a [bug report](https://github.com/electron/electron/issues/7685).

**Comment by p0macs** [comment] 2016-11-03 22:10
I have the same issue even after upgrading to 1.7.1.
I'm using Code on Hyper-V guest too.
I it helps, the thread using the CPU can be seen here:
![code_cpu_usage](https://cloud.githubusercontent.com/assets/23247869/19987253/7f57863a-a21a-11e6-9887-e6454b2bd1de.JPG)

**Comment by bpasero** [comment] 2016-11-11 17:57
@nikoudel @p0macs @crussell85 I am playing around with a newer version of Electron and was wondering if you could give this build a try that includes it to see if something has changed with this issue: https://az764295.vo.msecnd.net/insider/d47c8ba23ff35913052db316aaeef1bb92b0dd99/VSCode-win32-1.8.0-insider.zip

Thanks

**Comment by p0macs** [comment] 2016-11-11 23:14
@bpasero Thank you for the new version, but for me is no change - even slightly worser. Still 100% CPU usage. 
But I have very interesting new infos: tried this version on other Hyper-V guests: running fine on Windows 10 guest. AND: it is running fine on a differest guest which is Windows Server 2012 R2 too!!!!
I still have to find out what the difference is between the two 2012 R2 guests.

**Comment by bpasero** [comment] 2016-11-12 06:55
Ok keep us posted 👍

**Comment by if-igor** [comment] 2016-11-14 20:02
I was having a similar issue, and I was able to resolve it [(thanks to this post)](https://discuss.atom.io/t/electron-cpu-performance-on-windows-server-2012-r2/34573/2) by going from single to dual core CPU on the VM.

**Comment by nikoudel** [comment] 2016-11-14 20:35
Same here - I tried to run VS Code 1.7.1 and 1.8.1 insider builds on a similar VM but with 4 virtual processors instead of 1 and no hanging occured.

**Comment by p0macs** [comment] 2016-11-14 20:51
Great news, thank you very much! No more high CPU usage after increasing the processor cores of the VM.

**Comment by bpasero** [comment] 2016-11-15 05:30
Great news, closing then.

**Closed by bpasero** 2016-11-15 05:30 UTC
Labels: electron-update, freeze-slow-crash, upstream

**Comment by m-brian** [comment] 2017-02-10 02:26
It remains unusable on a single core VPS though. The issue persists through 1.9.1.

**Comment by bpasero** [comment] 2017-02-10 07:10
Yes, known issue: https://github.com/Microsoft/vscode/issues/17097
