### ISSUE TITLE
editor.mouseWheelScrollSensitivity has no effect

### ISSUE THREAD

**Issue by RalfJung** [Microsoft/vscode#29051] opened 2017-06-19 20:43 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.11.0+
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.15.2|
|vscode-rust|kalitaalexey|0.3.14|;

---

Steps to Reproduce:

1. Change `editor.mouseWheelScrollSensitivity` to something extreme, like 20
2. Restart vscode (just to make sure the setting is applied)
3. Turn the scroll wheel

Expected behavior:

It should scroll by much more than it used to.

Actual behavior:

Scrolling didn't change compared to the default settings.

**Comment by cyrilmesvayn** [comment] 2017-06-25 22:10
Can confirm it also does the same in Windows 10 Pro x64, VSCode release 1.13.1

**Comment by alexandrudima** [comment] 2017-06-28 10:43
Duplicate of #28412

**Closed by alexandrudima** 2017-06-28 10:43 UTC
