### ISSUE TITLE
Markdown preview doesn't render math in fenced code blocks

### ISSUE THREAD

**Issue by kajott** [microsoft/vscode#201582] opened 2023-12-28 10:23 UTC
Type: <b>Feature Request</b>

There's a difference in how GitHub and the VS Code Markdown preview handle math in Markdown documents.

As documented in https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions, math blocks can be delimited either with double dollar signs (`$$`) or with a fenced code block using the `math` pseudo-language.

I assume that VS Code's Markdown preview is supposed to mimic GitHub syntax as closely as possible; however, VS Code does **not** support the fenced code block syntax; it just renders the block verbatim as code, not math.

**Example Screenshot:**

![image](https://github.com/microsoft/vscode/assets/18756274/9e356ffd-0505-484f-9a1f-9113eef33ff2)

**Note:** This issue is certainly similar to #174731, but it's about a different thing (preview behavior vs. syntax highlighting in the editor).

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.5.0-10-generic

**Comment by mjbvz** [comment] 2024-01-03 16:55
Duplicate of #174731

**Closed by mjbvz** 2024-01-03 16:55 UTC
