### ISSUE TITLE
Openmode doubleclick

### ISSUE THREAD

**Issue by Eventyret** [microsoft/vscode#116958] opened 2021-02-18 16:17 UTC
Issue Type: <b>Bug</b>

by default workbench.list.openMode is set to single click, but after the latest update it seems it's forced to double click to open any folders or files etc.

https://imgur.com/a/VxZxqtG
VS Code version: Code - Insiders 1.54.0-insider (6eaef7d42f982a0e9b22ac465245fc2c27721fd0, 2021-02-18T05:13:24.586Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.79GB free)|
|Process Argv|--crash-reporter-id b78743f7-cd04-49f7-a253-ea39295f5cec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
ignoregit|And|1.0.1
ng-template|Ang|11.2.1
atlascode|atl|2.8.5
vscode-tailwindcss|bra|0.5.9
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.10.1
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
bootstrap-4-cdn-snippet|eve|1.11.0
json2ts|Gre|0.0.6
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
vscode-android-webview-debug|mpo|1.1.1
vscode-docker|ms-|1.10.0
vsliveshare|ms-|1.0.3784
debugger-for-chrome|msj|4.12.12
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.5.0
vscode-yaml|red|0.15.0
code-settings-sync|Sha|3.4.3
simontest|Sim|1.9.7
errorlens|use|3.2.4
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.11
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30251590
core-portspanel:30257802
pythontb:30258533
openwslfolder:30257850

```

</details>

**Comment by IllusionMH** [comment] 2021-02-18 16:58
/duplicate of #116804

See #115873 for details

/cc @joaomoreno as this isn't first king of this issue

**Closed** 2021-02-18 16:59 UTC
Labels: *duplicate

**Comment by Eventyret** [comment] 2021-02-18 21:02
Just to add for people reading this a workaround now is to set
`"workbench.tree.expandMode": "singleClick"` in `settings.json`

_Originally posted by @dhruvit-r in https://github.com/microsoft/vscode/issues/115873#issuecomment-781106275_

**Comment by joaomoreno** [comment] 2021-02-19 09:56
https://github.com/microsoft/vscode/issues/115873#issuecomment-781967348
