### ISSUE TITLE
New empty cells have copilot prompt in diff view

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#226819] opened 2024-08-27 17:13 UTC
Testing #226664

![image](https://github.com/user-attachments/assets/f77dee7e-0f17-46c7-aa3c-bfb540e7611f)

**Comment by DonJayamanne** [comment] 2024-08-27 23:42
Existing issue in stable as well.

**Comment by DonJayamanne** [comment] 2024-09-02 00:43
Duplicate of https://github.com/microsoft/vscode/issues/227336

**Closed by DonJayamanne** 2024-09-02 00:43 UTC
Labels: bug, notebook, notebook-diff
