### ISSUE TITLE
Provide option to only show leading/trailing whitespace

### ISSUE THREAD

**Issue by babychoux** [Microsoft/vscode#8991] opened 2016-07-09 07:55 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. side bar icons ,at screen 11" i think its too big ,its consumption area.
2.whitespace not display if not leading/trailing space ,can has menu to toggle this ?

**Comment by joaomoreno** [comment] 2016-07-11 08:07
Thanks for the feedback.

I did not understand point number 2.

**Comment by babychoux** [comment] 2016-07-11 10:31
ss
![2016-07-11_172602](https://cloud.githubusercontent.com/assets/11227831/16727842/430f7ee0-478d-11e6-87d6-ad7a0706efe9.png)

**Comment by jrieken** [comment] 2016-07-12 08:12
duplicate of #3828

**Closed by jrieken** 2016-07-12 08:12 UTC
Labels: feature-request
