### ISSUE TITLE
[v1.96] possible regression with `showHover` behavior

### ISSUE THREAD

**Issue by ahrjarrett** [microsoft/vscode#235979] opened 2024-12-12 17:05 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96
- OS Version: macOS Sonoma 14.6.1

Caused by https://github.com/microsoft/vscode/pull/235806

Steps to Reproduce:

I attached a gif below these steps as well, in case it helps. As of v1.96:

1. trigger a hover with a keyboard shortcut (e.g. `cmd+k cmd+i`)
2. note that the editor panel cannot be closed unless it is first focused (this seems to be the root cause of the issue)
3. scroll so the editor panel is out of view (see gif below)
4. attempt to trigger a hover with the panel out of view
5. scroll the editor panel back into view
6. note that only when the hover panel is both in view and focused are you able to close it

![Image](https://github.com/user-attachments/assets/5a0e72b7-368f-4214-93f8-b8d160fa3d2b)

Also I'm not seeing a way to call the `hideHover` action -- is it possible to do that? I imagine that would give me a workaround in the meantime.

**Comment by ahrjarrett** [comment] 2024-12-12 17:16
Updating:

I was wrong when I said this:

> note that the editor panel cannot be closed unless it is first focused (this seems to be the root cause of the issue)

While it's true that the editor panel cannot be closed until it is focused, this doesn't seem to be the root cause.

After downgrading to v1.95, I'm able to close the hover panel with `Escape`, without the hover panel being focused.

This is the behavior that's important to me (being able to close a hover with `Escape`)

**Comment by aiday-mar** [comment] 2024-12-13 08:48
Hi @ahrjarrett thank you for filing this issue. The hideHover action has been added but it is only available for the moment in the nightly Insiders release until the next stable release comes out in roughly 2 months. I am trying to reproduce the issue and am having trouble, so I want to ask a couple of questions. 

When you talk about the editor panel are you taking about the editor hover? 
Are you saying you can not focus the editor hover unless it is focused?

I am able to focus out of the hover and close it using the Escape key on the latest stable release as in the screen recording below:

https://github.com/user-attachments/assets/f0ebd846-cd7c-4c35-9d8c-5e17107c4bac

**Comment by nathanb** [comment] 2024-12-13 20:58
Good afternoon!

Today, I re-installed 1.96 to test this further because I've seen the same issue. I noticed that it's only affected when the automatic hover disabled by default. (So work around: Enable the Editor Hover)

I prefer to keep the hover disabled and then open it selectively with the hot keys. `Esc` has always closed this in the past. 

To replicate this issue in 1.96:
 1. Disable the automatic hover with the setting: `"editor.hover.enabled": false`
 2. Navigate to any expression, and open the hover with `cmd-k,cmd-i`
 3. The hover appears, but does not have focus. So `Esc` does not close it. (THIS is the bug; we want Esc to close the hover)
 4. Press `cmd-k,cmd-i`again, and the hover gains focus. `Esc` now closes the hover.

**Comment by aiday-mar** [comment] 2024-12-16 09:12
Hi @nathanb thank you for filing this issue. Indeed I am able to reproduce this issue. I will look into it.

**Closed** 2024-12-16 10:40 UTC
Labels: bug, candidate, editor-hover

**Comment by aiday-mar** [comment] 2024-12-16 13:18
Candidate label has been removed. This fix will be shipped next iteration.

**Comment by synalice** [comment] 2024-12-24 13:41
@aiday-mar, the issue still exists for me. Am I doing something wrong? 
```
Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-50-generic
```

**Comment by codart1** [comment] 2024-12-26 09:05
I'm unsure if my bug is related to this but I have to downgrade to version `1.95.3` to resolve it. As you can see, the code hint popup is stuck on the screen across my files until I reload the editor.|

https://github.com/user-attachments/assets/6f613ac7-d25c-434e-ac8f-40a05f1d466b

**Comment by synalice** [comment] 2024-12-26 09:26
@codart1, yep, absolutely related. This is the exact same bug being  discussed in this issue.

Release notes for `1.96.2` say that this bug should be fixed, but it's not :(

Right now the only solution is to stick to downgraded version.

**Comment by aiday-mar** [comment] 2025-01-06 09:09
Hi this will be fixed in the next stable release. You are on the nightly release which does not contain the fix yet.

**Comment by hgaiser** [comment] 2025-01-06 09:16
@aiday-mar thanks for the update! I'm just curious, why isn't this in a nightly release since it seems to be a regression from the previous stable release?

**Comment by aiday-mar** [comment] 2025-01-06 09:20
We discussed whether we wanted to add this into the nightly release as a team and decided to release this in the next stable release. Perhaps we should have added this after all to the nightly release instead.

**Comment by hgaiser** [comment] 2025-01-06 13:51
> We discussed whether we wanted to add this into the nightly release as a team and decided to release this in the next stable release. Perhaps we should have added this after all to the nightly release instead.

Alright 👍 thanks again :).
