### ISSUE TITLE
Horizontal scroll in file explorer

### ISSUE THREAD

**Issue by egoiste84** [Microsoft/vscode#44119] opened 2018-02-21 13:03 UTC
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

1. Open any folder with huge amount of files
2. File names are partially hidden/overlapped by workplace, no ability to horizontal scroll (http://prntscr.com/ihsov3)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment] 2018-02-21 19:33
You can drag the edge of the file explorer to resize it so that it's wider
![resize-explorer](https://user-images.githubusercontent.com/3672607/36501068-fbc6ae02-16fa-11e8-952f-bf74054e3f31.gif)

**Comment by egoiste84** [comment] 2018-02-22 09:01
Hello, yes I know that I can drag that edge, but it will reduce size of working area, especially when there are opened 2 or more windows

**Comment by usernamehw** [comment] 2018-02-22 18:50
Duplicate of https://github.com/Microsoft/vscode/issues/15539

**Closed** 2018-02-22 18:52 UTC
Labels: feature-request, file-explorer
