### ISSUE TITLE
autoReveal, but only when a file is explicitly selected

### ISSUE THREAD

**Issue by Rich-Harris** [microsoft/vscode#38899] opened 2017-11-21 18:21 UTC
Per #3062, the `explorer.autoReveal` setting controls whether the explorer will jump to the active file whenever it changes. That's good, because autoReveal is infuriating when the active file changes as a result of a tab being closed (whether because the user hit Cmd-W or clicked the 'x', or because the file was deleted via the explorer).

But autoReveal can be very useful when the active file changed because the user explicitly selected an existing tab.

I'd like to propose a third option besides `"explorer.autoReveal": true` and `"explorer.autoReveal": false` — perhaps something like `"explorer.autoRevealSelected": true`? With this option, clicking on a tab in the main view (even for the currently active file) would reveal the file in the explorer.

**Comment by equinusocio** [comment] 2018-04-22 09:52
Same issue. I disabled `explorer.autoReveal` to avoid editor jumps each time i select a file in the explorer panel, but now when i select a tab the explorer does not highlight the selected tab. 

I think this is an important UX issue since if you work with many files, you can't recognise where is it or keep it highlighted if you have many files with similar names.

**Comment by ndeviant** [comment] 2019-01-08 18:32
I agree wth equinusocio. I enabled autoReveal just to prevent scroll of sidebar, but i want to see the actually active tab in sidebar. 
Looks like you disabled this since [https://github.com/Microsoft/vscode/issues/14745](url) issue. But it was really fine before, and I expect the selection to show the active file.

**Comment by equinusocio** [comment] 2019-01-08 18:38
No news after almost 14 months...

**Comment by isidorn** [comment] 2019-10-08 10:00
Somewhat duplicate of https://github.com/microsoft/vscode/issues/23902

**Comment by Rich-Harris** [comment] 2019-10-08 15:05
Is it a dupe? I think we're describing different requests — the other issue is about having `autoReveal` but without scrolling, whereas this one is about preserving the existing behaviour (`autoReveal` causes a scroll) *except* in the situation where a tab is activated 'implicitly' (i.e. not as a result of the user clicking on it).

**Comment by isidorn** [comment] 2019-10-09 08:26
Got it, ti is not a dupe. I can reopen this one, though I do not see us tackling this in the near future.

**Comment by isidorn** [comment] 2020-07-30 15:14
You can now set 	`"explorer.autoReveal": "focusNoScroll"`
And this should somewhat be tackled.
Let me know if this does not fit this use case and I can reopen this issue

**Closed by isidorn** 2020-07-30 15:14 UTC
Labels: feature-request, file-explorer
