### ISSUE TITLE
Weird character when typing "l l"

### ISSUE THREAD

**Issue by CookieThemes** [microsoft/vscode#144508] opened 2022-03-06 13:33 UTC
Issue Type: <b>Bug</b>

Theres a weird character when typing "l l".

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
sidebar-markdown-notes|ass|1.0.4
vscode-intelephense-client|bme|1.8.2
cookie-consolelog|und|0.0.1
cookie-fix-text-prepositions|und|0.0.1
cookie-wp-lang-wrapper|und|0.0.1
vscode-eslint|dba|2.2.2
php-intellisense|fel|2.3.14
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.10
todo-tree|Gru|0.0.215
ftp-simple|hum|0.7.6
smarty|imp|0.3.0
latte|Kas|0.18.0
l13-projects|L13|1.1.1
MagicPython|mag|1.1.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
brackets-keybindings|ms-|0.1.1
indent-rainbow|ode|8.2.2
vscode-css-peek|pra|4.2.0
vscode-scss-formatter|sib|2.3.3
vscode-fileutils|sle|3.5.0
mtasa-lua|sub|2.3.6
footsteps|Wat|0.1.0
php-debug|xde|1.25.0
php-pack|xde|1.0.3
material-theme|zhu|3.13.20
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.0.5

(13 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2022-03-06 21:41
/gifPlease

Please also use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by CookieThemes** [comment] 2022-03-06 22:05
Hi,

I tried the Bisect now, and it didn't help. Not extension related.

The problem is whenever I type L L with one space between I get a weird character. It looks like to Ls smash into each other.
It doesn't matter if it is lower or capital case, but needs to be same. It even happens when word ends with letter L and another starts with L. See attached screenshot.

Texts on the screenshot should be:
testl l
TESTL L
L L
l l


Thanks


<img width="163" alt="Screenshot 2022-03-06 at 23 04 50" src="https://user-images.githubusercontent.com/8009623/156944056-07906351-24ab-46d3-9008-9412a9e37aa2.png">

**Comment by gjsjohnmurray** [comment] 2022-03-06 22:15
Maybe a duplicate of #106583

**Closed** 2022-03-07 11:23 UTC
Labels: needs more info, *duplicate
