### ISSUE TITLE
Command palette's camel case matching does not work for non ASCII characters

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4691] opened 2016-03-26 15:59 UTC
From @espresso3389 in https://github.com/Microsoft/vscode/issues/4679:

> I'm on Windows 10 and the IME is ATOK; a Japanese thirdparty IME.
> Even with MS-IME, the behavior is same.
> Typing "git: プル" correctly works but doing "git プル" does not work.
> The search function does not seem to work with Japanese characters.

![eea0c49e-f3a0-11e5-9726-32dff53190f6](https://cloud.githubusercontent.com/assets/2193314/14063489/67b2e16e-f388-11e5-8539-ff5dbf2efb3a.gif)

Is there an optimization to not recheck characters if the last character is replaced? While not being shown here, Japanese IMEs can also transforms multiple Japanese characters into an even smaller number of characters, by going from English -> Kana -> Kanji.

**Comment by Tyriar** [comment] 2016-03-28 19:55
@mysticatea ran into this issue too:

![c4e20786-f480-11e5-852c-4a46e97ff853](https://cloud.githubusercontent.com/assets/2193314/14088414/46e01dd2-f4e4-11e5-9b2e-1192b3748db3.gif)

**Comment by dbaeumer** [comment] 2016-03-29 09:32
@bpasero assigning to you since this is quick box related. Marking as candidate since we should look into fixing this for 1.0. Let me know if there is something I can do from the translation side.

**Comment by bpasero** [comment] 2016-03-29 11:03
Looked into this and I think the issue is not about finding Japanese input in general but rather how the filtering works in the command palette. There are different matchers being used and one of them is a camel case matcher that would match for a given input of `git pull` on `Git: Pull` only because we think `Git: Pull` is a valid camel case word with `G` and `P`. This however is not the case when using Japanese labels because our check for camel case only considers ASCII characters. 

Matching on camel case in the command palette is questionable and should probably be revisited. I quickly checked to use another matcher approach with fully fuzzy matching (similar to files) and could not reproduce the issue there. However, changing our filtering for commands like that can have quite an impact and we also need to revisit the sorting in that case.

I would not do this for GA, but @egamma and @chrisdias should speak up.

**Comment by egamma** [comment] 2016-03-29 12:27
makes sense

**Comment by bpasero** [comment] 2016-03-30 07:21
Related: https://github.com/Microsoft/vscode/issues/1964

**Comment by Tyriar** [comment] 2016-03-30 15:59
Another user who wants either English back or supports English in addition to their native language. https://github.com/Microsoft/vscode/issues/4785

> How can i switch back to the English commands or the console can support both 'English' and 'Chinese'?When i'm coding, I have to switch the IME.
>
> ![67cf555e-f664-11e5-9c1d-072d51adf8d0](https://cloud.githubusercontent.com/assets/2193314/14148727/7ea3b8ba-f655-11e5-9eb3-af55093c3194.png)
>
> ![753ae82a-f664-11e5-8968-a89819e031ac](https://cloud.githubusercontent.com/assets/2193314/14148730/8180d89c-f655-11e5-82a1-9c8feaa5ef1b.png)

**Comment by bpasero** [comment] 2016-03-31 06:50
I changed our matching in the commands quick open to also match non-ascii beginning of words. This is not yet fuzzy matching, but returns a lot more results that make sense.

Basically the matching is now supporting any beginning of a word (e.g. "gp" matches "Git: Pull" as well as "g p" does).

**Closed** 2016-03-31 06:49 UTC
Labels: bug, i18n, important

**Comment by bpasero** [comment] 2016-04-21 06:32
A fix has landed in insiders. You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

Happy for feedback!
