### ISSUE TITLE
VS Code intellisencse not working

### ISSUE THREAD

**Issue by MrityunjayIITRPR** [microsoft/vscode#230783] opened 2024-10-08 09:16 UTC
Type: <b>Bug</b>

type any html,react code no suggestions coming

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.30GB free)|
|Process Argv|C:\\Users\\admin\\Desktop\\Netlix-GPT\\my-app --crash-reporter-id 973eb077-e1bf-4e70-8bbe-a83acd704680|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-toggler|dzh|0.0.3
gitlens|eam|15.6.0
prettier-vscode|esb|11.0.0
js-debug-nightly|ms-|2024.10.417

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
notype1:31151523
controlgs:31153265
cc771715:31146322

```

</details>

**Comment by Sov3rain** [comment] 2024-10-08 10:05
Encountering the issue too. It's related to the Automatic Type Acquisition not working on 1.94. I rolled back to 1.93.1 and everything is back to normal.

**Comment by BlazeInferno64** [comment] 2024-10-08 12:18
@Sov3rain same here dude intellisense isn't working

**Comment by noelhibbard** [comment] 2024-10-08 19:46
I wasted the past 6 hours trying to figure out why IntelliSense stopped working. I installed 1.94 a few days ago and it was working fine. I installed some Windows updates and restarted and it hasn't worked since. I pulled my hair out for 6 hours before coming across this issue. Rolling back to 1.93.1 fixed the issue for me.

FYI, 1.94.1 has the same issue.

**Comment by IllusionMH** [comment] 2024-10-08 20:14
/duplicate of #230596

Needs TS release and then VS Code recovery built to include fixed TS version. But current workarounds posted in linked issue.

**Closed** 2024-10-08 20:15 UTC
Labels: *duplicate
