### ISSUE TITLE
Syntax Highlighting Broken on New Release

### ISSUE THREAD

**Issue by epiqueras** [Microsoft/vscode#30443] opened 2017-07-12 00:04 UTC
Syntax highlighting for object properties and JSX is broken.

- VSCode Version: 1.14
- OS Version: OSX El Capitan 10.11.6

Reproduces without extensions: Yes

**Comment by chrmarti** [comment] 2017-07-12 00:13
Could you open a separate issue for git? We prefer to track one problem per issue.

Could you attach a screenshot of the broken syntax highlighting? Which theme are you using?

**Comment by epiqueras** [comment] 2017-07-12 00:37
@chrmarti 
I edited the issue to remove the git comment.

The theme is Monokai Dimmed, but I see it happen with all of the built in themes. If I remember correctly, object references used to have a different color from their property accessors.

![sample](https://user-images.githubusercontent.com/19157096/28096642-418a9360-665f-11e7-8f33-3826defa2716.png)

**Comment by mjbvz** [comment] 2017-07-12 05:01
Duplicate of #30428 I believe. Should be fixed in next 1.15 insiders build. Looking into taking this into 1.14.1 as well

**Closed by mjbvz** 2017-07-12 05:01 UTC
Labels: duplicate, new release, typescript
