### ISSUE TITLE
Text overlapping on the Quick Fix floating dialog 

### ISSUE THREAD

**Issue by numToStr** [microsoft/vscode#93133] opened 2020-03-21 13:40 UTC
Text is overlapping on the *Quick Fix* dialog box when using `@Decorator()` in the typescript project.

#### ScreenShot:
![Screenshot_20200321_190108](https://user-images.githubusercontent.com/24727447/77227610-85663580-6ba7-11ea-897a-bd507971cc89.png)

- VSCode Version: 1.43.1
- OS Version: Manjaro Linux 19.0.2
- Kernel: 5.5.8

**Comment by alexdima** [comment] 2020-03-29 18:29
@jrieken The text in there looks like actions from the quick fix menu:
![image](https://user-images.githubusercontent.com/5047891/77857092-d7d4d100-71fb-11ea-8bd6-bedb83953355.png)

The rendering is different than what I'm used to on mac/windows, perhaps quick fixes are painted with a custom menu on Linux?

**Comment by mjbvz** [comment] 2020-03-31 00:32
@sbatten Looks like our custom context menu may be overlapping with the hover

**Comment by sbatten** [comment] 2020-03-31 19:58
iirc hovers use the context view service which only has a single dom element that is reused for all consumers. that means a menu and a hover cannot be shown at the same time.

**Comment by alexdima** [comment] 2020-03-31 20:56
@numToStr  Can you please provide some clear steps to reproduce?

**Comment by numToStr** [comment] 2020-04-01 07:16
@alexdima 
- Add this `"strictPropertyInitialization": true` in the `tsconfig.json`.
- If needed restart the ts server.
- This issue only occurs on class properties w/ decorators that don't have an initial value (as shown in the image above). 
- If you get ts errors as above, pop up the Quick Fix dialog, you will see the text overlapping (as shown in the image above)

Hope this helps :v:

**Comment by sbatten** [comment] 2020-10-21 21:14
This isn't the combination of the the menu and hover but the code action has special text that should be stripped. It essentially has a ton of new lines because it includes the full decoration as part of the property name. resolving as dupe of https://github.com/microsoft/vscode/issues/105428

**Closed by sbatten** 2020-10-21 21:14 UTC
