### ISSUE TITLE
Debugger doesn't step into

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15253] opened 2016-11-09 17:41 UTC
* open VS Code sources
* set a breakpoint in `strings.test.ts`, like [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/test/common/strings.test.ts#L25)
* run the `Unit Tests` launch config
* see the breakpoint is being hit
* select *step into*, 🐛 execution resumes instead

![nov-09-2016 18-40-49](https://cloud.githubusercontent.com/assets/1794099/20148252/17242712-a6ac-11e6-8fa6-60c8f264ddfe.gif)

**Comment by weinand** [comment] 2016-11-09 17:49
@isidorn I cannot reproduce this. Can you?

**Comment by rebornix** [comment] 2016-11-09 18:14
Can not reproduce on macOS.

**Comment by octref** [comment] 2016-11-09 18:16
Can't repro. I'm on macOS too.

**Comment by isidorn** [comment] 2016-11-10 08:46
Can not repro both on insiders and stable, macOS

**Comment by jrieken** [comment] 2016-11-10 11:53
I am not accepting a majority vote here

**Comment by weinand** [comment] 2016-11-10 12:12
@jrieken let me know when we can debug this at your laptop.

**Comment by jrieken** [comment] 2016-11-11 10:57
Add these two watch expressions `this._scanner.tokenText(this._token)` and `this._scanner.tokenText(this._prevToken)`

**Comment by weinand** [comment] 2016-11-14 11:50
Any watch expression will trigger this problem.

**Comment by weinand** [comment] 2016-12-05 15:18
Haven't found fix for this. Needs more investigation...

**Comment by edvinv** [comment] 2017-01-18 09:08
Having the same problem. After removing all watch expression, step into starts to work. With watch expressions step into behaves like continue execution.

**Comment by lmessinger** [comment] 2017-03-19 13:06
same here, problem still exists on  ver 1.10.2

**Comment by weinand** [comment] 2017-03-19 16:20
@lmessinger could you please confirm that the problem only occurs if you have at least one watch expression.

**Comment by lmessinger** [comment] 2017-03-21 13:15
confirmed. running for 2 days now w/out issues (at last)

**Comment by weinand** [comment] 2017-03-21 13:25
@lmessinger now I'm confused. 
So you can confirm that the problem only occurs if you have at least one watch expression and that it does not occur if you remove all watch expressions?

But what does "running for 2 days now w/out issues (at last)" then mean?

**Comment by lmessinger** [comment] 2017-03-21 13:52
correct for the first paragraph.

For second, what I meant is that i removed it two days ago and have been developing for the last 2 days, and all works well.

**Comment by edvinv** [comment] 2017-03-23 09:34
I can also confirm that after adding single watch expression Step into (F11) behaves like Continue (F5). 
So I'm not using watch expressions at all, because I lose basic stepping options.

**Comment by weinand** [comment] 2018-09-17 15:58
Does not seem to be an issue any more.

**Closed by weinand** 2018-09-17 15:58 UTC
Labels: bug, debug

**Comment by weinand** [comment] 2018-09-17 16:06
works fine now (even in the presence of watches).
