### ISSUE TITLE
pre-config template Program.cs code file.

### ISSUE THREAD

**Issue by Woutercode** [microsoft/vscode#96249] opened 2020-04-27 12:07 UTC
Issue Type: <b>Feature Request</b>

If available where can I find it? Otherwise a productive feature:

The ability to edit or change the template config file for Program.cs
This is when the User creates a new project with dotnet new console.
The C# .NET Core project created, adds the Program.cs code file.
Most of the time creating a new console project the Program.cs has the necessary code.
It would be more productive and time-saving if the user can pre-configure the template Program.cs
to their liking. by adding or removing code lines example public,  private, ReadKey(), Clear() etc.

Also, allow the ; to automatically jump out from () when pressing ; inside () . or is there a way to change it?

Regards
Wouter Lombard
developer@haloda.com
  

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

**Comment by alexr00** [comment] 2020-04-27 13:31
This is caused by the C# extension

**Comment by Woutercode** [comment] 2020-04-27 17:14
The request is to be able to change the code inside the default Program.cs, is it possible? if so where to change it?

**Comment by Tyriar** [comment] 2020-05-05 18:31
Please report to https://github.com/OmniSharp/omnisharp-vscode

**Comment by Tyriar** [comment] 2020-05-05 18:31
@JacksonKearl caused by extension not closing the issue above

**Closed by Tyriar** 2020-05-05 18:31 UTC
Labels: *caused-by-extension

**Comment by Woutercode** [comment] 2020-05-25 11:02
The extension Autoend is the solution I was looking for
