### ISSUE TITLE
References not showing correctly

### ISSUE THREAD

**Issue by ammarsabir26** [Microsoft/vscode#15496] opened 2016-11-15 05:56 UTC
![screen shot 2016-11-15 at 10 52 26 am](https://cloud.githubusercontent.com/assets/12556439/20294709/015f4cfc-ab22-11e6-9532-700a0a5a2feb.png)
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.1.0|
|unity-snippets|YclepticStudios|0.1.2|
|csharp|ms-vscode|1.5.1|
|mono-debug|ms-vscode|0.11.0|
|omnisharp|ms-vscode|0.3.3|
|colonize|vmsynkov|1.0.1|

---

Steps to Reproduce:

1. Just installed c# 1.5.1 and seeing this
![screen shot 2016-11-15 at 10 52 26 am](https://cloud.githubusercontent.com/assets/12556439/20294722/188b4f2a-ab22-11e6-9391-ce29d1841395.png)

2.

**Comment by kisstkondoros** [comment] 2016-11-15 18:24
Duplicate of #15389

**Comment by ramya-rao-a** [comment] 2016-11-15 22:26
Closing as duplicate. Please use the insiders build until the next VS Code update

**Closed by ramya-rao-a** 2016-11-15 22:26 UTC
