### ISSUE TITLE
Behavior changed for middle click window title in linux

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#92346] opened 2020-03-10 11:47 UTC
**ENVIRONMENT:**
linux ubuntu 19
vscode 1.43.0 (released today)

**WHAT USED TO WORK:**
I'm using the mouse middle click to lower a window - so I can easily cycle through open windows. This setting is set via the shell, or the gnome tweaks tool.

**HOW IT WORKS NOW:**
That changed in this latest update. It doesn't honor that gnome setting anymore. So a middle click on the vscode titlebar does nothing.

Has anyone else encountered this, and did you find a solution?

**Comment by kladnik** [comment] 2020-03-10 13:10
Just noticed the same issue. Hopefully there is an easy solution.

**Comment by deepak1556** [comment] 2020-03-11 01:19
I am not aware of change on the electron side responsible for this, can you see if the issue repros when running electron fiddle application https://github.com/electron/fiddle/releases/tag/v0.12.0 ? Thanks!

/cc @bpasero

**Comment by bpasero** [comment] 2020-03-11 06:30
@lonix1 @kladnik do clarify, you middle-click into the window title? Are you using the native title or the custom one?

**Comment by kladnik** [comment] 2020-03-11 08:05
@bpasero Yes exactly. I was using custom and it was working in the previous version, but not in 1.43. Just tested using the native title and there the function still works. So this can be a current workaround until a proper solution is found.

**Comment by lonix1** [comment] 2020-03-11 08:24
@bpasero Yes, I middle click on the window title. (Just for reference: in gnome there's an option to "lower" the window, so the result is you can quickly cycle between open windows on that workspace by just middle clicking on the window title).

@kladnik Please tell me how you did the workaround? I'm not sure what is meant by "native title" - where do I find that option?

**Comment by bpasero** [comment] 2020-03-11 08:31
//cc @sbatten on the fact that this does not work with custom title.

**Comment by deepak1556** [comment] 2020-11-05 09:27
Is this still an issue with latest stable ?

**Comment by kladnik** [comment] 2020-11-05 09:30
@deepak1556 In version `1.50.1` (possible that it was fixed in previous versions already)  works as intended again. Thanks.

**Comment by deepak1556** [comment] 2020-11-05 09:36
thanks for confirming!

**Closed by deepak1556** 2020-11-05 09:36 UTC
Labels: linux, needs more info, titlebar
