### ISSUE TITLE
Can't scroll a markdown preview using touch

### ISSUE THREAD

**Issue by codefoster** [Microsoft/vscode#39195] opened 2017-11-27 15:56 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.17025
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-opennewinstance|chr|0.0.4
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
vscode-npm-source|dku|1.0.0
githistory|don|0.2.3
gitlens|eam|6.2.0
tslint|eg2|1.0.24
vscode-reveal|evi|1.0.0
rest-client|hum|0.16.1
search-node-modules|jas|1.2.0
Angular2|joh|2.11.2
markdown-shortcuts|mdi|0.8.1
quicksnippet|mou|0.0.1
windowsiot|ms-|0.0.20
python|ms-|0.8.0
azure-account|ms-|0.2.2
azurecli|ms-|0.3.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.22
vscode-icons|rob|7.18.1
sharecode|Rol|0.4.1
partial-diff|ryu|0.5.0
MDTools|sea|1.0.1
code-settings-sync|Sha|2.8.6
azure-iot-toolkit|vsc|0.4.2
vscode-arduino|vsc|0.2.10
JavaScriptSnippets|xab|1.5.0
---

Steps to Reproduce:

1. Create a markdown file longer than a single page
2. Preview the markdown file
3. Attempt to scroll the markdown preview using a vertical swipe gesture

Expect scrolling of the preview, but the file holds still.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-12-08 23:57
duplicate of #21812

**Closed by mjbvz** 2017-12-08 23:57 UTC
Labels: markdown
