### ISSUE TITLE
How can I use white backgroung with .ipynb file，and black with other file?

### ISSUE THREAD

**Issue by ColaDrill** [microsoft/vscode#106846] opened 2020-09-16 09:41 UTC
Issue Type: <b>Bug</b>

How can I use white background with .ipynb file，and black with other file?

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_135201|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-psl|ing|1.11.3
vscode-edit-csv|jan|0.4.2
python|ms-|2020.8.109390
azure-account|ms-|0.9.3
azure-hdinsight|msh|1.1.10

</details>

**Comment by aeschli** [comment] 2020-09-16 12:28
White background where? The editor background?

**Comment by ColaDrill** [comment] 2020-09-16 12:30
> White background where? The editor background?

yes

**Comment by aeschli** [comment] 2020-09-16 13:08
Duplicate of https://github.com/microsoft/vscode/issues/20652

**Closed by aeschli** 2020-09-16 13:08 UTC
Labels: needs more info

**Comment by ColaDrill** [comment] 2020-09-16 13:36
the tool "Theme by language" is not work for .ipynb file.

**Comment by ColaDrill** [comment] 2020-09-16 13:36
> Duplicate of #20652

the tool "Theme by language" is not work for .ipynb file.
