### ISSUE TITLE
Add Sass support

### ISSUE THREAD

**Issue by sharedrory** [microsoft/vscode#132894] opened 2021-09-10 22:15 UTC
VSCode ships with css, less, and scss language support

Sass is the preprocessor for Sass and Scss
Scss is a flavor of Sass which is more like css (valid css is valid Scss)
Sass is also a flavor of Scss without braces and semicolons (indentation based)

VSCode does not support Sass

https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented is the _best_ (relative) third party support available
It has lots of bugs and does not fully support the Sass syntax. Examples:
```sass
html
//v hovering over this will show something different than in an equivalent css file
  width: 10px
  font: // no autocomplete for nested property declarations
//  v hovering over this wont show anything
    size: 10px
//  v or this
    style: italic
```

It would be nice to see Sass support in VSCode
I believe it won't be hard to implement as Sass is just a flavor of Sass so the Sass engine VSCode uses probably already supports it

**Comment by AlanHeckinJohnston** [comment] 2021-09-10 23:08
There are plenty of SASS extensions on the market. Just install an extension. VScode natively does not support any language. Everything is done through extensions.

**Comment by sharedrory** [comment] 2021-09-11 00:33
@AlanHeckinJohnston I don't need to compile sass which is what all the other extensions in the marketplace do. I am using webpack and sass-loader to take care of that. The extension I linked is the only one I know of that provides EDITOR support for Sass.

To be clear, I want:
Syntax Highlighting
Outline
Intellisense
Hovers
And all the other things for css/less/scss

I don't want:
A sass compiler

**Comment by aeschli** [comment] 2021-09-13 07:27
duplicate of #123150
The VS Code team neither has the resources nor the insights to provide and maintain language support for SASS. That's why we added the extension API and provide infrastructure for extensions. We can share the workload and also provide choice to users.
Please support the extension authors of the available SASS extensions to make their extensions better.
Thanks for your understanding!

**Closed by aeschli** 2021-09-13 07:27 UTC
