### ISSUE TITLE
Prompt buttons do not work with tap

### ISSUE THREAD

**Issue by Codedevlo** [Microsoft/vscode#65024] opened 2018-12-13 19:23 UTC
when a notification/prompt pops up I tap it on my touchscreen laptop nothing happens
https://waders.tech/vscode-tap_error.zip

**Comment by bpasero** [comment] 2018-12-14 11:54
I can reproduce and it seems to impact any button. 

@isidorn moving to you because I see there is https://github.com/Microsoft/vscode/blob/2808fee/src/vs/base/browser/ui/button/button.ts#L66 but maybe it is not properly wired in for buttons.

**Comment by isidorn** [comment] 2018-12-27 11:08
The wireing in seems good. That is what we are doing everywhere.

@bpasero if you have a touch machine can you put a breakpoint [here](https://github.com/Microsoft/vscode/blob/2804e0d20511f6d0a826739efda3a5e0a75091a8/src/vs/base/browser/touch.ts#L115) and check if it is hit
Also does it help if you add a `container` instead of `this._element` [here](https://github.com/Microsoft/vscode/blob/2804e0d20511f6d0a826739efda3a5e0a75091a8/src/vs/base/browser/ui/button/button.ts#L66). I think it should not make a difference.

@Codedevlo you can also tryout what I asked @bpasero to do, that would help

**Comment by bpasero** [comment] 2019-01-14 14:43
@isidorn the breakpoint is hit and it works if I first hit the breakpoint and then press play. Using `container` does not make it work.

**Comment by isidorn** [comment] 2019-01-14 15:13
@bpasero let's look into this together once you are in the office

**Comment by bpasero** [comment] 2019-01-15 08:55
I broke this with https://github.com/Microsoft/vscode/commit/ad972a1d3ea04f539cc20250365cb53427358068 5 months ago :scream:

**Closed** 2019-01-15 08:56 UTC
Labels: accessibility, bug

**Comment by isidorn** [comment] 2019-01-15 08:57
Thanks for fixing
