### ISSUE TITLE
Line staging loose encoding

### ISSUE THREAD

**Issue by pa0694** [microsoft/vscode#149635] opened 2022-05-16 11:59 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.1
- OS Version: Windows 11

When we do a line stage from a Windows 1252 file, the encoding is lost.

Steps to Reproduce:

1. Create a new file.c with encoding "Windows 1252"
2. Add some text with some special chars (é, è, à etc) to file.c
3. Commit file.c
4. Modify file.c

![1](https://user-images.githubusercontent.com/70905569/168587895-f0444462-5f0a-4411-bfd1-f0e3393b3423.png)
5. Do a line stage from the previous modifications

![2](https://user-images.githubusercontent.com/70905569/168587933-ca83d01a-97b1-4c02-9d57-39526b646fc2.png)
6. In source control, check the stage file.c. The encoding is lost 

![3](https://user-images.githubusercontent.com/70905569/168588253-ac9fc933-9d7f-49b8-a247-83b8a41242a2.png)
![4](https://user-images.githubusercontent.com/70905569/168588255-47723765-16e0-47b2-9a3f-f77505df39ca.png)

**Comment by pa0694** [comment] 2022-05-16 12:04
Note that this issue is similar to this one:
https://github.com/microsoft/vscode/issues/36219#issuecomment-555939520

**Comment by lszomoru** [comment] 2022-12-12 15:26
Closing this as duplicate of [#155658](https://github.com/microsoft/vscode/issues/155658)

**Closed by lszomoru** 2022-12-12 15:26 UTC
Labels: bug, git
