### ISSUE TITLE
custom multiple language support for syntax highlighting and autocompletion (emmet)

### ISSUE THREAD

**Issue by GaitaBenone** [microsoft/vscode#118554] opened 2021-03-09 16:18 UTC
Very good app - been using it for the latest 3yrs BUT please add multiple language support per file extension (maybe custom) like smarty + js + css for emmet autocompletion and syntax highlighting

**Comment by rzhao271** [comment] 2021-03-09 17:04
Duplicate of https://github.com/microsoft/vscode/issues/62910

**Closed** 2021-03-09 17:09 UTC
Labels: *duplicate, emmet, feature-request
