### ISSUE TITLE
Open Editors view doesn't react on mouse clicks

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#26019] opened 2017-05-05 10:49 UTC
- VSCode Version: Insiders 1.13.0
- OS Version: macOS or Windows 10

Steps to Reproduce:

- click on item in "Open Editors" view

Observe: nothing happens. The item is not selected.

**Comment by egamma** [comment] 2017-05-05 12:00
Duplicate of #26021

**Closed by egamma** 2017-05-05 12:00 UTC
Labels: bug, duplicate, important
