### ISSUE TITLE
extension host crashes

### ISSUE THREAD

**Issue by egeaybars123** [microsoft/vscode#176845] opened 2023-03-11 10:50 UTC
Type: <b>Bug</b>

Whenever I open VS Code, the extensions work fine for a few minutes. Then, the extension host crashes. 

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (6.01GB free)|
|Process Argv|--crash-reporter-id b69cd0f9-91e3-4493-9b9d-99660331fbb3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
rust-syntax|dus|0.6.1
copilot|Git|1.77.9225
go|gol|0.38.0
discord-vscode|icr|5.8.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
solidity|Jua|0.0.149
kite|kit|0.147.0
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5834
vsliveshare-audio|ms-|0.1.93
vsliveshare-pack|ms-|0.4.0
rust-analyzer|rus|0.3.1426
vscode-styled-components|sty|1.7.5
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
funwalk2:30682974
pythonms35:30680984

```

</details>

**Comment by molaycule** [comment] 2023-03-11 12:55
I get this same issue too on VS Code Version: 1.76.1

**Comment by Keroxen** [comment] 2023-03-11 13:36
Same issue here, same version.

**Comment by egeaybars123** [comment] 2023-03-11 15:37
I have found out that when I uninstalled GitHub CoPilot extension, the error is fixed. I hope that this error gets fixed soon!

**Comment by etothepii** [comment] 2023-03-13 00:45
I had the same issue in VSCode 1.75.1, as it started for me on Wednesday last week. Only established today that it was Github Copilot that was extension that was causing the extension host to crash.

After disabling Copilot, I was able to work without issue for several hours. After turning it back on, the extension host was crashing within 30 seconds.

**Comment by egeaybars123** [comment] 2023-03-13 07:49
> I had the same issue in VSCode 1.75.1, as it started for me on Wednesday last week. Only established today that it was Github Copilot that was extension that was causing the extension host to crash.
> 
> After disabling Copilot, I was able to work without issue for several hours. After turning it back on, the extension host was crashing within 30 seconds.

I tried turning on the CoPilot again. The extension crashed as described in the issue description.

**Comment by isidorn** [comment] 2023-03-15 10:52
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

**Closed by isidorn** 2023-03-15 10:52 UTC
Labels: freeze-slow-crash-leak, extension-host
