### ISSUE TITLE
UI Document Pane doesn't match container size when VSCode's Zoom level is not at 100%

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#20607] opened 2017-02-14 18:24 UTC
- VSCode Version: 1.9.1
- OS Version: Win10

Steps to Reproduce:

Just opened VSCode after Upgrade.  I saw this issue before too with some other document, but I'm reporting it now that I'm still seeing it.  Resizing the window doesn't fix it.  Resetting the zoom does seem to make the size match exactly.  Any other zoom level seems to make the region _off_ proportionally.

![image](https://cloud.githubusercontent.com/assets/17498172/22942546/f46f0482-f2b7-11e6-85cc-9a4041daea85.png)

**Comment by joaomoreno** [comment] 2017-02-15 09:28
Duplicate of #5745

**Closed by joaomoreno** 2017-02-15 09:28 UTC
