### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by ransfordarthurjr** [microsoft/vscode#104450] opened 2020-08-11 19:28 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200809

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:102665:161)
    at resolveModuleNamesWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:102888:26)
    at resolveModuleNamesReusingOldState (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103038:19)
    at processImportedModules (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104461:35)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104197:17)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104431:21
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104426:16)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104194:21)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104431:21
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104426:16)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104194:21)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104431:21
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104426:16)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104194:21)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104431:21
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104426:16)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104194:21)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104431:21
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104426:16)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104194:21)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104431:21
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104426:16)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104194:21)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104431:21
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104426:16)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104194:21)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104431:21
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104426:16)
    at findSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104194:21)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:85
    at getSourceFileFromReferenceWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103993:34)
    at processSourceFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:104026:13)
    at processRootFile (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:103849:13)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:102766:60
    at Object.forEach (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:102766:16)
    at synchronizeHostData (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:143379:26)
    at Proxy.getProgram (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:143471:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:148328:53)
    at ConfiguredProject.Project.updateGraph (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:148261:42)
    at ConfiguredProject.updateGraph (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:149195:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:150899:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:151806:44)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:152133:97
    at Object.flatMap (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:152133:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:153152:46)
    at /Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:155024:88
    at IOSession.Session.executeWithRequestId (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:155015:28)
    at IOSession.Session.executeCommand (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:155024:33)
    at IOSession.Session.onMessage (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:155048:35)
    at Interface.<anonymous> (/Users/ransfordarthurjr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200809/node_modules/typescript/lib/tsserver.js:157264:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
node-essentials|afr|1.1.0
ng-template|Ang|0.1000.7
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-tailwindcss|bra|0.4.1
node-snippets|chr|1.1.1
path-intellisense|chr|2.2.1
vcard|cst|1.0.1
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
vscode-deno|den|2.0.4
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
php-intellisense|fel|2.3.14
file-icons|fil|1.0.25
vscode-firefox-debug|fir|2.9.0
vscode-pull-request-github|Git|0.18.0
vscode-drawio|hed|0.7.2
helium-icon-theme|hel|1.0.0
beautify|Hoo|1.5.0
vscode-pigments|jas|2.0.0
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.8.0
vscode-phpfmt|kok|1.0.30
vscode-jsonp|luy|1.0.1
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-docker|ms-|1.4.1
vscode-kubernetes-tools|ms-|1.2.1
mssql|ms-|1.9.0
vscode-typescript-next|ms-|4.1.20200810
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2478
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
angular-console|nrw|13.0.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.2.0
fabric8-analytics|red|0.1.0
java|red|0.65.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
java-generate-setters-getters|soh|5.3.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0
quokka-vscode|Wal|1.0.312
wg-getters-and-setters|Wil|2.0.0
vscode-import-cost|wix|2.12.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-08-11 19:34
Caused by the  deno extension

Duplicate of https://github.com/denoland/vscode_deno/issues/89

**Closed by mjbvz** 2020-08-11 19:34 UTC
