### ISSUE TITLE
explorer.autoReveal: true doesn't work

### ISSUE THREAD

**Issue by esmultivac** [microsoft/vscode#110103] opened 2020-11-06 18:50 UTC
Issue Type: <b>Bug</b>

After updating to 1.51, when I edit a file it's not revealed on the sidebar even if explorer.autoReveal is true

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.93GB free)|
|Process Argv|--crash-reporter-id 09216cec-e766-4e65-9981-817e4c1c7e4a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|1.6.2
goto-documentation|cxf|0.0.1
vscode-eslint|dba|2.1.13
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
todo-tree|Gru|0.0.186
mysql-syntax|jak|1.3.1
sftp|lix|1.12.9
gitignore|mic|1.0.1
vscode-apache|mrm|1.2.0
vscode-language-pack-es|MS-|1.51.2
php-formatter|Sop|0.2.4
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by esmultivac** [comment] 2020-11-06 18:52
Maybe I'm being a little obscure. It's not revealed in the sidebar file explorer as it happened before this update.

**Comment by YunHsiao** [comment] 2020-11-07 09:03
bumping this, autoReveal feature has been so helpful, that we can not live without

**Comment by abdulkareemnalband** [comment] 2020-11-08 09:39
For me reveal in sidebar itself is not working. I tested this for a typescript file , and starting vscode in disabled extension mode

```
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

I tested it by running `code --disable-extensions a.code-workspace`

**Comment by isidorn** [comment] 2020-11-09 08:24
This works just fine for me.
Can you reproduce using vscode insiders https://code.visualstudio.com/insiders/
Is there something special about this file that is not revelead? Or you can reproduce with every file?

**Comment by isidorn** [comment] 2020-11-09 08:26
Closing in favor of https://github.com/microsoft/vscode/issues/110188
Since I think that one has more exact steps

**Closed by isidorn** 2020-11-09 08:26 UTC
Labels: file-explorer, needs more info

**Comment by isidorn** [comment] 2020-11-09 10:08
Please let me know if that issue is not actually what you are doing and than I can reopen this.

**Comment by ChezMose** [comment] 2020-11-10 08:40
Same issue here, but I found a few clues.

1/ I believe the issue in not with autoReveal but with 'reveal in side bar'
=> the file that are not auto-revealed cannot be right-click 'reveal in sidebar' either

2/ It happens when opening the files from the search
- open files from the workspace explorer => no problem
- open files from the search => reveal does not work

**Comment by YunHsiao** [comment] 2020-11-10 08:44
* open files from 'go to file' (ctrl + p) => reveal does not work
* 'go to file' lookup speed slowed down drastically
