### ISSUE TITLE
The change of branches in the status bar works badly

### ISSUE THREAD

**Issue by DonatoRM** [microsoft/vscode#112838] opened 2020-12-18 19:18 UTC
Having created a branch in any project on a web page, if we click on the option of the selected branch in the status bar, a window appears where all the active branches of the project should appear. However the master branch does not appear.
Please, how can I configure the vscode so that this branch appears ?.
Regards.

**Comment by DonatoRM** [comment] 2020-12-18 21:13
I have read the previous cases and the information provided has nothing to do with what I present. Please, if someone can help me I thank you.

**Comment by pamtbaau** [comment] 2020-12-24 08:56
Happend since upgrading to November releases. [Downgrading to 1.51](https://code.visualstudio.com/updates/v1_51) solved the issue.

**Comment by DonatoRM** [comment] 2020-12-27 11:51
Thank you very much Pamtbaau

**Comment by pamtbaau** [comment] 2020-12-27 12:00
@DonatoRM, I think this is a genuine bug and the issue should therefor not be closed... If you close it, Msft will not have a look at it.

**Comment by DonatoRM** [comment] 2020-12-27 12:07
Thank you Pamtbaau for your comments. I'm sorry I closed it. I am a newbie. I hope Microsoft fixes the problem since in this latest update I have already detected multiple problems such as breakpoints in debugging not working well. Regards.

**Comment by joaomoreno** [comment] 2021-01-07 11:01
What does `git branch` return in your repository, in the command line?

**Comment by pamtbaau** [comment] 2021-01-07 11:06
@joaomoreno, If I click on the current branch in the lower left corner of VScode, a list of all branches appear except the master branch.

![image](https://user-images.githubusercontent.com/5120011/103885738-c43a8d00-50e0-11eb-9cc4-d36b4a5bb869.png)

**Comment by joaomoreno** [comment] 2021-01-07 11:43
And what does `git branch` return?

**Comment by pamtbaau** [comment] 2021-01-07 11:55
Ah sorry...

```
$ git branch
* @kleas
  develop
  fetch
  master
```

**Comment by joaomoreno** [comment] 2021-01-07 15:42
What about:

```
git for-each-ref --sort -committerdate --format "%(refname)"
```

**Comment by pamtbaau** [comment] 2021-01-07 15:52
```
$ git for-each-ref --sort -committerdate --format "%(refname)"
refs/heads/Jrbdog
refs/heads/fetch
refs/heads/@kleas
refs/heads/develop
refs/heads/master
grav/site-dev
```

Note: I just discovered it does not happen on all repos... On further investigation it only happens on one... plus the one from @DonatoRM

**Comment by DonatoRM** [comment] 2021-01-07 19:23
Hello again. In the end, do you know how to solve this problem in VSCode? Thank you

**Comment by Wacheee** [comment] 2021-01-08 01:39
I have the same issue, downrading to 1.51 VSCode shows correctly all the branches. Please fix it in the next update.
Thank you

**Comment by joaomoreno** [comment] 2021-01-08 10:30
> Note: I just discovered it does not happen on all repos... On further investigation it only happens on one... plus the one from @DonatoRM

Can you repro on those repos if you clone them again? If so, can you send me a link to them, so I can reproduce locally?

**Comment by pamtbaau** [comment] 2021-01-08 11:25
Repo was a local one...

**Created Github repo:**
- Created public repo on Github (https://github.com/pamtbaau/test-master)
- Added remote to local repo
- Pushed all branches to Github
  - Github lists all branches

**Cloned to fresh local folder:**
- Created empty folder locally
- Ran: `git clone --mirror https://github.com/pamtbaau/test-master ./.git`
- Ran `git config --unset core.bare`
- Ran `git branch`
  ```
  $ git branch
    @kleas
  * Jrbdog
    develop
    fetch
    master
  ```
- Opened vscode on new repo -> master does not show

**Comment by joaomoreno** [comment] 2021-01-08 13:05
> git config --unset core.bare

Why do you do this? Does it still reproduce if you run a simple `git clone` instead of `git clone --mirror`?

**Comment by pamtbaau** [comment] 2021-01-08 13:15
If I run a simple `git clone` only the selected branche on github will be downloaded. I found above script somewhere and it clones the entire repo.

Don't ask me what `git config --unset core.bare` does, because I don't know... :-)

**Comment by joaomoreno** [comment] 2021-01-08 13:17
If you run a simple `git clone`, does the `master` branch appear?

**Comment by pamtbaau** [comment] 2021-01-08 13:21
No. 
```
git branch
* Jrbdog
```

**Comment by Wacheee** [comment] 2021-01-08 13:21
From StackOverflow: "Using the --mirror option seems to copy the remote tracking branches properly. However, it sets up the repository as a bare repository, so you have to turn it back into a normal repository afterwards."

By the way i tried to clone pamtbaau repo with `git clone`
This is what i got in Git Bash:
![image](https://user-images.githubusercontent.com/77031418/104019984-3bccf280-519b-11eb-8c8a-689a7bbd9a4d.png)

This i what i got in VScode, no master:
![image](https://user-images.githubusercontent.com/77031418/104020041-4edfc280-519b-11eb-8265-b9e5e7bea666.png)

**Comment by joaomoreno** [comment] 2021-01-08 14:13
Related to https://github.com/microsoft/vscode/commit/9b6aaf1e86c8fec4c86c664edf5f713583c70fe5 https://github.com/microsoft/vscode/issues/112481

@eamodio I can still repro the steps in @Wacheee's last post in `master`.

**Comment by eamodio** [comment] 2021-01-08 17:10
@joaomoreno I can't reproduce it on master (can prior to https://github.com/microsoft/vscode/commit/9b6aaf1e86c8fec4c86c664edf5f713583c70fe5 though), but it put in a better fix https://github.com/microsoft/vscode/commit/6828ae1ab50a2785aefc49353da037faf92f7fed. That should resolve it.

**Comment by eamodio** [comment] 2021-01-08 17:10
Closed in https://github.com/microsoft/vscode/commit/6828ae1ab50a2785aefc49353da037faf92f7fed

**Closed by eamodio** 2021-01-08 17:10 UTC
Labels: needs more info

**Comment by eamodio** [comment] 2021-01-08 17:13
\closedWith 6828ae1

**Comment by DonatoRM** [comment] 2021-01-27 08:06
I have installed the new Insider version and it seems that now everything **works correctly**. Thank you so much everyone. Regards.

**Comment by joaomoreno** [comment] 2021-01-27 08:47
@DonatoRM Make sure you leave a comment with the text `/verified`, so we automate the verification process. Thanks!

**Comment by DonatoRM** [comment] 2021-01-27 08:51
verified. Thanks.
