### ISSUE TITLE
Show @deprecated methods in the PROBLEM panel

### ISSUE THREAD

**Issue by SomeBottle** [microsoft/vscode#141209] opened 2022-01-22 11:53 UTC
![image](https://user-images.githubusercontent.com/12976469/150637066-229680db-3f87-4c43-ae79-2da34e0733f6.png)

There are some ```@deprecated```  annotated methods in my JavaScript code , I wonder if there's any way to find out all of the deprecated methods in the current file...However, when I turned to the PROBLEM panel, I found no information about the deprecated methods.  

So I think maybe **showing all of the deprecated methods of the current file in the PROBLEM panel** is a good way. As it is possible to mark strikethroughs over these methods, I think it's of no problem to show them in the panel.  

Sorry for my poor English...

**Comment by mjbvz** [comment] 2022-01-25 02:07
Duplicate of https://github.com/microsoft/TypeScript/issues/40604

**Closed by mjbvz** 2022-01-25 02:07 UTC
