### ISSUE TITLE
[json] RangeError when parsing GeoJSON

### ISSUE THREAD

**Issue by jrmistry** [microsoft/vscode#91854] opened 2020-03-01 18:10 UTC
Hello,

I am trying to open a GeoJSON file that I downloaded to my computer from the link below:
https://data.torontopolice.on.ca/datasets/bicycle-thefts?orderBy=Occurrence_Date&orderByAsc=false

Although I can read the file as text, the OUTPUT in VSCODE keeps saying that there is a RangeError as maxium call stack size is exceded. With the exact error message below (the error keeps repeating itself as it keeps trying to parse the file over and over again):

```
[Error - 12:53:46 p.m.] Error while computing document colors for file:///c%3A/Users/Jaydeep-PC/Downloads/Bicycle_Thefts.geojson: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at e.merge (c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:36168)
    at p (c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:49154)
    at c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:49252
    at X (c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:50490)
    at e.getMatchingSchemas (c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:39117)
    at c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:89371
[Error - 12:54:00 p.m.] Error while computing document colors for file:///c%3A/Users/Jaydeep-PC/Downloads/Bicycle_Thefts.geojson: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at e.merge (c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:36168)
    at p (c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:49154)
    at c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:49252
    at X (c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:50490)
    at e.getMatchingSchemas (c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:39117)
    at c:\Users\Jaydeep-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain.js:9:89371
[Error - 12:54:10 p.m.] Error while computing document colors for file:///c%3A/Users/Jaydeep-PC/Downloads/Bicycle_Thefts.geojson: Maximum call stack size exceeded`
```

- VSCode Version: 1.42.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Download the geojson file
2. Open the file on VSCode and keep getting the error message

Does this issue occur when all extensions are disabled?: Yes

I know that there are VSCode extensions that can read geojson files, however it would be great if there could be a Language Mode option that can read geojson natively, because right now only option I have is to just change the Language Mode to Plain Text.

Thank you.

**Comment by aeschli** [comment] 2020-03-02 11:37
I'm not able to reproduce
- I downloaded https://opendata.arcgis.com/datasets/22bfc3619d69447fadd984fcf77a5550_0.geojson and saved it a `foo.json`
- opened in in VSCode. No errors.

From the error it seems there's a problem with a JSON schema. Do you have a schema association to a `geojson` schema? Maybe an extension installed that does that?

**Comment by jrmistry** [comment] 2020-03-02 21:58
I do not have an extension installed that has an association with the .geojson schema, or any extension that I could find in the current marketplace options that can do it

I was able to rename the file to .json and at least stop the RangeError message in the output from happening, however I was hoping to get the colors of the json items available when I view the file in VSCode; as in blue for variable names and red for values. As well as get to auto-format the entire document.

From what I understood, the content of the file follows standard JSON schema, so why would the file name's extension of being either .json instead of .geojson be the issue?

Another source of the issue is that the entire content of the file is written on a single line. As I manually add newlines, the JSON Language Features (Extension) keeps attempting to read the file and get the RangeError. I am thinking that maybe the file is just too long?

There was another .geojson dataset about cyclists at [this link](https://opendata.arcgis.com/datasets/76e09310ce98403eb622c802756f5a1b_0.geojson) that I downloaded and it does not have the RangeError. The content of this file follows the same geojson format as the other file, however it only has 1K+ records instead of 17K+ records. Since this cyclist file is shorter than bicycle file in length, the JSON Language Features (Extension) was able to do whatever it needed to do without an issue. I was even able to  get the colors of the variables to show up again after auto-formatting the document. I only got 2 minor issues which are listed below:

1. Cyclist.geojson: For performance reasons, document symbols have been limited to 5000 items. Use setting 'json.maxItemsComputer' to configure the limit
2. Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via 'editor.maxTokenizationlineLength'

The JSON Language Server from the default JSON Language Features (Extension) is having trouble for some reason to read through the longer file and I don't know why?  what do you recommend?

**Comment by aeschli** [comment] 2020-03-03 08:59
By default `geojson` is not associated with JSON. So you probably have the https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.geo-data-viewer extension installed.
I can reproduce the issue with that extension and found the problem.

**Comment by RMacfarlane** [comment] 2020-04-02 17:33
I'm still able to reproduce this on 1.44.0-insider d8e3cca049b1baa317ab9ef0d3f673b08e53d8fa

I downloaded https://opendata.arcgis.com/datasets/cb7ccc6addcb4923a8414d3a8ab978fc_0.geojson and installed the geo-data-viewer extension, and still see "Maximum call stack size exceeded" errors

**Comment by aeschli** [comment] 2020-04-03 08:49
Pushed a fix.

**Comment by roblourens** [comment] 2020-04-06 22:59
I still see this

**Comment by roblourens** [comment] 2020-04-06 23:00
I think maybe your fix just didn't make it into the release branch. Can probably just put this in April?

**Closed by roblourens** 2020-04-06 23:00 UTC
Labels: bug, json, verification-found

**Comment by roblourens** [comment] 2020-04-29 21:46
Now when I open the file, I don't get the error from before but vscode is using lots of CPU and not responding, but I think that's just because the file is huge.
