### ISSUE TITLE
Pull Request Template ignored when creating a Pull Request from Web UI

### ISSUE THREAD

**Issue by pjbollinger** [microsoft/vscode#135973] opened 2021-10-27 18:47 UTC
Steps to reproduce:
* Open a GitHub repository in the web version of VSCode by using `.`
* Make a new branch
* Make some changes
* Commit said changes
* Click the `Create Pull Request` button

Expected behavior:
* The `Description` field should pull from a pull request template, if one exists, and the commit message; like it does in the GitHub UI.

Actual behavior: 
* The `Description` field pulls from the commit message.

I verified that committing the code changes and then using the standard GitHub UI to create the Pull Request will use the Pull Request Template, so I'm guessing there are tweaks needed to pull the Pull Request Template into VSCode Web UI.

Please let me know if you need any further information! 😄 

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Embedder: github.dev

**Comment by lszomoru** [comment] 2021-11-08 09:32
@alexr00, @joyceerhl, could you please take a look at this issue? Thank!

**Comment by alexr00** [comment] 2021-11-08 10:17
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3055

**Closed by alexr00** 2021-11-08 10:17 UTC
