### ISSUE TITLE
Make it possible to use drag and drop in a webview

### ISSUE THREAD

**Issue by f111fei** [microsoft/vscode#8794] opened 2016-07-06 10:11 UTC
- VSCode Version: 1.3.0-insider
- OS Version: windows7

Steps to Reproduce:
1.  Download My extension:  https://github.com/f111fei/test-files/raw/master/webview-test-0.0.1.vsix
2.  Run command `Hello Webview` to open my webview.

Problem:
1.  Drag Button into TextArea. Dragfeedback overlay will prevent  my dragging action.
2.  Typing some text in the textarea. Use `Ctrl+A` to select all, Nothing happen.

Reason
1. see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L91, the default drag handler is prevented.
2. see https://github.com/Microsoft/vscode/blob/master/src/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L380, `selectAll` handler is prevented.

![1](https://cloud.githubusercontent.com/assets/7069719/16614676/14cd3018-43a5-11e6-9d5b-0335069faf9e.png)

**Comment by bpasero** [comment] 2016-07-06 10:43
Taking out the preventDefault() from the dragover allows to drop any file/url into the window to open it and replace all of VS Code, so I am not easy to make a change there...

**Comment by bpasero** [comment] 2016-07-06 10:43
@jrieken for the second issue.

**Comment by jrieken** [comment] 2016-07-06 13:46
Problem is that `Cmd+A` is not guarded by `when` and which is done [here](https://github.com/Microsoft/vscode/blame/master/src/vs/editor/common/config/config.ts#L405)

**Comment by alexandrudima** [comment] 2016-07-12 11:44
@jrieken @bpasero As I am working on a Windows machine, I can definitely remove that.

IIRC there was something inherently broken on the Mac (`cmd+a` not working in dev tools or something weird like that) that made @bpasero and I do that change and not have a `when` for `cmd+a`.

**Comment by alexandrudima** [comment] 2016-07-12 11:46
Moreover, regardless of our changing the rule for `cmd+a`, I think the problem on the mac is that:
* `cmd+a` appears in the menu
* the menu natively captures the keydown
* the menu sends to the **wrong** renderer process the command invocation

But maybe things have changed since we last looked at this.

**Comment by bpasero** [comment] 2016-07-12 12:04
My workaround to make it happen in dev tools is in https://github.com/Microsoft/vscode/blob/fix-8324-8569/src/vs/code/electron-main/menus.ts#L790

**Comment by alexandrudima** [comment] 2016-07-15 07:26
@bpasero @jrieken I have pushed the fix you suggested, but I don't have a mac to try it out. Please try to do Ctrl+A in a native input such as the find widget or the git commit input box and check if it still works. If it does not work, then please revert 151d236

**Comment by bpasero** [comment] 2016-07-15 07:37
@alexandrudima I can confirm that Cmd+A selects all in input fields and still in the editor. It does not select all in the <webview> though.

There is another bug where Undo/Redo do no work in native input fields and I guess that is related. Can we apply your fix for these commands too?

**Comment by jrieken** [comment] 2016-07-15 07:58
@alexandrudima  I see an issue when selecting an item in the explorer and pressing `Cmd+A` it selects all of the editor tho it doesn't have focus. Is that the intent?

![jul-15-2016 09-57-52](https://cloud.githubusercontent.com/assets/1794099/16867531/996ef4fe-4a72-11e6-9f9a-b9cf6f3b328c.gif)

**Comment by alexandrudima** [comment] 2016-07-15 08:03
@jrieken That is what I'm trying to explain here unsuccessfully. It is not the keybindings service that executes `editor.action.selectAll`, but on the mac `cmd+a` is captured by the menu (because it appears as an accelerator in the menus) and then the menu sends a `vscode:runAction` ipc message to the focused renderer process and executes `editor.action.selectAll`.

**Comment by alexandrudima** [comment] 2016-07-15 08:03
In fact, that is the case with all accelerators that appear in the menu on the mac. This is not the case under windows.

**Comment by alexandrudima** [comment] 2016-07-15 08:04
The select all code falls back as a last chance to select last active editor:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/config.ts#L397

**Comment by alexandrudima** [comment] 2016-07-15 08:05
It also does the manual select all on input fields:
```
        // Ignore this action when user is focussed on an element that allows for entering text
	let activeElement = <HTMLElement>document.activeElement;
	if (activeElement && ['input', 'textarea'].indexOf(activeElement.tagName.toLowerCase()) >= 0) {
		(<any>activeElement).select();
		return;
	}
```

**Comment by bpasero** [comment] 2016-07-15 08:08
The select all behaviour in the explorer has been like that before already.

**Comment by jrieken** [comment] 2016-07-15 09:42
yeah - we should either focus the editor after selecting all or ignore the command if the editor isn't focused

**Comment by bpasero** [comment] 2016-07-15 09:46
I would just focus the editor, many people actually find it useful that Ctrl+A always goes to the editor, so I would not disable that.

**Comment by bpasero** [comment] 2016-07-15 09:49
![untitled](https://cloud.githubusercontent.com/assets/900690/16870489/1a933fb8-4a82-11e6-930d-facefc477ce1.gif)

I like it.

@alexandrudima what do you think? seems as easy as adding `editor.focus()` before https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/config.ts#L401

**Comment by alexandrudima** [comment] 2016-07-15 10:38
@bpasero :+1: Please do the change, we wrote that code together at your machine a long time ago :)

**Comment by bpasero** [comment] 2016-07-15 10:57
Pushed via https://github.com/Microsoft/vscode/issues/9329

**Comment by alexandrudima** [comment] 2016-07-15 11:07
@jrieken It is not clear to me if my change fixed this issue.

**Comment by jrieken** [comment] 2016-07-21 07:37
@f111fei Did the changes resolve your issue?

**Comment by f111fei** [comment] 2016-07-21 07:45
@jrieken  `selectAll` is ok now. But Problem1(drag in webview) is still unresolved.

**Comment by jrieken** [comment] 2016-07-21 08:23
Thanks for the feedback. Assigning to @bpasero for the dnd part

**Comment by bpasero** [comment] 2016-08-08 11:47
@f111fei I tried your suggested change from https://github.com/f111fei/vscode/commit/36a8dcda5548ab61dbd3f15de993b2e2688f27fb and it causes an issue as you can see from the GIF below. Worse, it opens the actual file as source into the webview.

Please feel free to provide another PR with a solution, I am not sure though it is that easy. Your change is preventing all DND operations from happening in the webview and this means you cannot drop a tab or file anymore onto the editor area to open it. 

![editors](https://cloud.githubusercontent.com/assets/900690/17478796/8a63cfca-5d6e-11e6-9276-8397312c480e.gif)

**Comment by f111fei** [comment] 2016-08-08 12:03
> it opens the actual file as source into the webview.

We maybe can add some code in [webview.html] ?(https://github.com/Microsoft/vscode/blob/f165bc60395537ed9bd9a56880feb81064329e92/src/vs/workbench/parts/html/browser/webview.html)

```
// Prevent some events
window.addEventListener('dragover', (e) => {
    e.preventDefault();
});

window.addEventListener('drop', (e) => {
    e.preventDefault();
});
```

**Comment by bpasero** [comment] 2016-08-08 12:06
Also, I find it bad UX if it blocks a user from dropping a tab into the editor area because to a user it might totally not obvious that something inside the webview accepts the drop and we will get many bugs for that.

**Comment by f111fei** [comment] 2016-08-08 12:10
yeah, this issue is contradictory. it impossible to meet all requirements simultaneously.

**Comment by bpasero** [comment] 2016-08-08 14:53
The Ctrl+A issue is back on the table and if you find a solution via PR that does not break the world, we would be happy to review :)

**Comment by Huachao** [comment] 2016-09-19 09:04
@bpasero, can we also have the function to use mouse right click in webview, and I also want native support ctrl+F to find

**Comment by bpasero** [comment] 2016-09-19 09:29
@Huachao yes, but please follow our issue guidelines and create separate issues for separate isuses.

**Comment by Huachao** [comment] 2016-09-19 09:31
@bpasero I already include this request in my original issue, however you closed it...

**Comment by bpasero** [comment] 2016-09-19 09:47
@Huachao trying to teach you how to write good isses :)

**Comment by Huachao** [comment] 2016-09-19 10:03
@bpasero , sorry for the inconvenience, I thought the title and the description is easy to read, while in fact it's poor. Anyway, is this feature request in your recent schedule?

**Comment by bpasero** [comment] 2016-09-19 10:12
@Huachao currently not, but if someone is willing to help, we accept pull requests.

**Comment by Huachao** [comment] 2016-09-19 10:14
@bpasero thanks 😃

**Comment by Huachao** [comment] 2017-10-30 14:37
@mjbvz any progress about this?

**Comment by mjbvz** [comment] 2018-07-23 18:18
Reopening this to track just the drag and drop part. Select all was added by #54851

**Comment by donaldoakes** [comment] 2020-10-09 18:41
It would be fantastic to enable drag and drop into webviews. This screenshot shows how my extension's toolbox palette is able to render in the sidebar thanks to #46585. However, that doesn't do much good unless the user can drag items from the palette onto the canvas webview displayed in the editor.

Is this enhancement so foundational a change that it's unlikely to be considered?

![Uploading Screen Shot 2020-10-09 at 12.38.48 PM.png…]()

**Comment by magrawa** [comment] 2020-10-10 13:38
I have a similar problem as Donald is having above. This looks like a fundamental problem with this framework. Are there any design patterns or workaround to drag and drop functionality in webview? What was the rationale to not support this kind of feature?

**Comment by mjbvz** [comment] 2021-05-22 00:17
The original example seems to work for me in iframe based webviews (which are now the default in the latest VS Code insiders)

![Screen Shot 2021-05-21 at 5 14 54 PM](https://user-images.githubusercontent.com/12821956/119208654-12c94200-ba58-11eb-8d2f-43da42b94877.png)

The original linked extension no longer works since `previewHTML` was removed so I pasted this in the webview sample extension instead:

```html
<style type="text/css">
    #div1 {
        width: 488px;
        height: 70px;
        padding: 10px;
        border: 1px solid #aaaaaa;
    }
</style>

<script type="text/javascript">
    function dragover(ev) {
        ev.preventDefault();
    }

    function dragstart(ev) {
        ev.dataTransfer.setData("Text", ev.target.id);
    }

    function drop(ev) {
        ev.preventDefault();
        var data = ev.dataTransfer.getData("Text");
        ev.target.value = 'The element\'s id is \"' + data + '\"';
    }
</script>

<p>Please Drag Button into here：</p>

<textarea id="div1" ondrop="drop(event)" ondragover="dragover(event)"></textarea>
<br />
<button id="button" draggable="true" ondragstart="dragstart(event)">
    Button
</button>
```

If you are still seeing issues with drag/drop in webviews, please open a new issue with an example extension so we can investigate

**Comment by connor4312** [comment] 2021-06-03 17:15
That doesn't work for me:

![](https://memes.peet.io/img/21-06-1ea30c55-248e-494a-a90f-d3bce906dfa8.gif)

**Closed** 2021-06-03 17:19 UTC
Labels: feature-request, help wanted, verification-found, verification-needed, webview
