### ISSUE TITLE
Search bar covered first 2 lines

### ISSUE THREAD

**Issue by cxbig** [Microsoft/vscode#13950] opened 2016-10-18 17:09 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.0.0
- Extensions: DotJoshJohnson.xml-1.6.0, EditorConfig.EditorConfig-0.3.3, HookyQR.beautify-0.4.1, HvyIndustries.crane-0.2.1, Kasik96.format-indent-1.3.0, PeterJausovec.vscode-docker-0.0.6, abusaidm.html-snippets-0.0.17, akamud.vscode-theme-onedark-0.2.7, alefragnani.project-manager-0.10.0, chenxsan.vscode-standard-format-0.0.12, christian-kohler.path-intellisense-1.1.0, donjayamanne.githistory-0.1.0, donjayamanne.jquerysnippets-0.0.1, donjayamanne.python-0.4.2, ecmel.vscode-html-css-0.0.28, eg2.vscode-npm-script-0.0.21, felixfbecker.php-debug-1.9.7, fknop.vscode-npm-3.3.0, lukehoban.Go-0.6.45, mohsen1.prettify-json-0.0.3, ms-vscode.Theme-MarkdownKit-0.1.1, msjsdiag.debugger-for-chrome-1.2.2, rebornix.Ruby-0.9.0, robinbentley.sass-indented-1.1.0, seanmcbreen.Spell-0.8.6, wcwhitehead.bootstrap-3-snippets-0.0.7

Steps to Reproduce:
1. Open a file with a few lines
2. <Cmd> + <F> open search bar
3. First 2 lines have been covered. If finding contents are inside, we couldn't see them.
   _Especially for those uglified files._

<img width="473" alt="settings_json" src="https://cloud.githubusercontent.com/assets/1363706/19488135/e4a64146-9565-11e6-8dc1-d0064f48f5d2.png">

**Comment by roblourens** [comment] 2016-10-18 17:58
I typically don't use the editor that narrow, but I see the problem.

**Comment by chrisdias** [comment] 2016-12-04 12:42
dupe of #11102

**Closed by chrisdias** 2016-12-04 12:42 UTC
Labels: feature-request, ux
