### ISSUE TITLE
vscode.d.ts: return value of TextEditor.edit and TextEditor.insertSnippet - Promise or Thenable

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#97410] opened 2020-05-10 15:32 UTC
- VSCode Version: 1.44.2

Snip from `vscode.d.ts`
```
/**
* Perform an edit on the document associated with this text editor.
*
* The given callback-function is invoked with an [edit-builder](#TextEditorEdit) which must
* be used to make edits. Note that the edit-builder is only valid while the
* callback executes.
*
* @param callback A function which can create edits using an [edit-builder](#TextEditorEdit).
* @param options The undo/redo behavior around this edit. By default, undo stops will be created before and after this edit.
* @return A promise that resolves with a value indicating if the edits could be applied.
*/
edit(callback: (editBuilder: TextEditorEdit) => void, options?: { undoStopBefore: boolean; undoStopAfter: boolean; }): Thenable<boolean>;

/**
* Insert a [snippet](#SnippetString) and put the editor into snippet mode. "Snippet mode"
* means the editor adds placeholders and additional cursors so that the user can complete
* or accept the snippet.
*
* @param snippet The snippet to insert in this edit.
* @param location Position or range at which to insert the snippet, defaults to the current editor selection or selections.
* @param options The undo/redo behavior around this edit. By default, undo stops will be created before and after this edit.
* @return A promise that resolves with a value indicating if the snippet could be inserted. Note that the promise does not signal
* that the snippet is completely filled-in or accepted.
*/
insertSnippet(snippet: SnippetString, location?: Position | Range | ReadonlyArray<Position> | ReadonlyArray<Range>, options?: { undoStopBefore: boolean; undoStopAfter: boolean; }): Thenable<boolean>;
```

The `@return` says it returns a Promise but the type description says a `Thenable`.

Which one is correct?

**Comment by jrieken** [comment] 2020-05-12 08:42
/duplicate of https://github.com/microsoft/vscode/issues/91552

**Closed** 2020-05-12 08:43 UTC
Labels: *duplicate
