### ISSUE TITLE
Salsa preview doesn't seem to work

### ISSUE THREAD

**Issue by NickClark** [Microsoft/vscode#3005] opened 2016-02-14 09:53 UTC
Setting `export VSCODE_TSJS=1` in my `.bash_profile` and updating my project to use the latest Typescript@next doesn't work. I've noticed that sometimes I see the `(Salsa)` indicator show up very briefly when starting up the editor, but it disappears right away.

**Comment by meritozh** [comment] 2016-02-15 03:52
Do you install `TypeScript@next` locally or globally? Maybe `Salsa` will work after setting `typescript.tsdk`.

<img width="545" alt="screen shot 2016-02-15 at 11 47 25 am" src="https://cloud.githubusercontent.com/assets/7543300/13039446/f6921004-d3d9-11e5-9982-e49cec645d95.png">

I install `TypeScript` globally.

[VSCode Docs](https://code.visualstudio.com/Updates#_javascript-salsa-preview)

**Comment by egamma** [comment] 2016-02-17 07:46
Thanks @meritozh 
Some additional things to observe:
- The Salsa indicator shows up only when a .js file is open in the editor.
- When hovering over the Salsa indicator you can see the path to the tsdk that is used. Verify that it is valide and that it is a tsdk > 1.8

Closing as cannot reproduce.

**Closed by egamma** 2016-02-17 07:46 UTC

**Comment by NickClark** [comment] 2016-02-17 17:47
Ah, that was my error, I was expecting it to show for .ts files
