### ISSUE TITLE
error when copying and pasting file in the same folder

### ISSUE THREAD

**Issue by Jusys** [Microsoft/vscode#35931] opened 2017-10-09 21:07 UTC
- VSCode Version: 1.17.0 (issue present in both 32bit and 64bit)
- OS Version: Windows 7 32bit, Windows 10 64bit
- Project is on the mapped network drive
- File server is Synology Diskstation DSM 5.2-5967 Update 4

Steps to Reproduce:

1. Open sidebar -> file explorer;
2. In file explorer on selected file open context menu (right mouse click);
3. choose copy;
4. then open context menu again and paste in the same folder;
5. file copy is created correctly but vs code shows error;

All previous VS code versions worked correctly.

![image](https://user-images.githubusercontent.com/30110941/31358573-d4207268-ad4e-11e7-964e-df90845963ad.png)
![image](https://user-images.githubusercontent.com/30110941/31358578-d9e9a05c-ad4e-11e7-8eff-b91ec6dfcd1c.png)
![image](https://user-images.githubusercontent.com/30110941/31358584-df715f06-ad4e-11e7-9635-a4d173d9a8e8.png)
![image](https://user-images.githubusercontent.com/30110941/31358591-e40760c4-ad4e-11e7-884b-b1b52365dcbc.png)

Reproduces without extensions: I have no extensions installed

**Comment by dlong500** [comment] 2017-10-09 21:50
Duplicate of #35743

**Comment by ramya-rao-a** [comment] 2017-10-10 17:12
Thanks @dlong500, closing as duplicate this issue as duplicate of #35743

cc @bpasero @isidorn

**Closed by ramya-rao-a** 2017-10-10 17:12 UTC
Labels: bug, duplicate, workbench
