### ISSUE TITLE
Issues with Terminal Shell Integration on Windows with Zsh

### ISSUE THREAD

**Issue by EnderturtleOrz** [microsoft/vscode#233822] opened 2024-11-14 07:08 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.95.2 (user setup)
- OS Version:  Windows_NT x64 10.0.22631

I have installed zsh, oh-my-zsh through msys2. 

Steps to Reproduce:

1. I cannot directly use `[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"` in my .zshrc, it returns a Windows-formatted path. This path is not accepted by MSYS2's Unix environment, requiring me to manually locate and modify the path.

2. After successfully locating the path, the command decorations are misaligned. They may shift positions, sometimes appearing on the line above the command, and then correct themselves after some time.

![Image](https://github.com/user-attachments/assets/93ba1a06-2cad-4869-97e0-af221a5af2f5)

**Comment by meganrogge** [comment] 2024-12-19 22:16
For the path problem, you probably need to change your .zshrc script to format it correctly. Maybe msys2 has a helper for that like wslpath.

The misalignment issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-12-19 22:16 UTC
Labels: bug, polish, terminal-shell-zsh
