### ISSUE TITLE
Git status indicators disappear briefly, e.g., when staging a file

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#136049] opened 2021-10-28 17:56 UTC
Does this issue occur when all extensions are disabled?: Yes, although less prominently

![image](https://user-images.githubusercontent.com/12128514/139309570-2f35591d-54de-4f4d-82aa-cc26f8a0636e.png)

- VS Code Version: 1.61.2
- OS Version: Windows 10, Remote SSH into OpenSUSE Leap 15.2

As a result, due to all icons moving left briefly, I sometime click "Discard" rather than "Stage" when staging multiple files. Fortunately, there is an additional confirmation, but staging multiple files in a row is unnecessary difficult.

Steps to Reproduce:

![9FXK0defFH](https://user-images.githubusercontent.com/12128514/139308059-4dc04d52-a840-44e1-9c27-620cc067eeca.gif)

**Comment by lszomoru** [comment] 2022-12-09 13:45
Closing this as duplicate of #[136366](https://github.com/microsoft/vscode/issues/136366) as the underlying problem is the same.

**Closed by lszomoru** 2022-12-09 13:45 UTC
Labels: bug, scm
