### ISSUE TITLE
Outline filter no input box, confusing, can we add it?

### ISSUE THREAD

**Issue by Mingliang2018** [microsoft/vscode#84338] opened 2019-11-09 01:56 UTC
Issue Type: <b>Feature Request</b>

Hi VSCode Team,
Recently I switched to MAC VSCode from Windows SourceInsight, I see VSCode is pretty good is most cases, but can't understand why there is no input box in outline mode. To get it focused, I must click something unwanted for me and the UI jumped elsewhere which is not expected, then I can see the floating search box which is too small ... and not easy to focus on what I'm looking.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

**Comment by usernamehw** [comment] 2019-11-09 07:51
Possible duplicate of #70646 (which is closed now).

**Comment by gjsjohnmurray** [comment] 2019-11-09 08:20
> Possible duplicate of #70646 (which is closed now).

...but not yet locked, so can still be up voted by anyone in favour of the request.

**Closed** 2019-11-13 08:54 UTC
