### ISSUE TITLE
The options of "Quick fix..." is invalid.

### ISSUE THREAD

**Issue by EminemRap** [microsoft/vscode#78536] opened 2019-08-06 02:25 UTC
- VSCode Version:1.36.1
- OS Version:Windows_NT x64 10.0.17134

Steps to Reproduce:

1.When the code goes wrong, hover the mouse pointer where the error occurred.
2.Clicking on "Quick fix..." will result in multiple options, but no matter which option you click is invalid.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment] 2019-08-06 09:38
/needsMoreInfo

>no matter which option you click is invalid

What do you mean here? Nothing happens, code changes but error doesn't go away (is it still same error).

Also code and errors examples will help to determine what can cause this?

**Comment by EminemRap** [comment] 2019-08-07 07:37
My English is not good, and the description may not be clear. I mean, when I found the error in the code, clicking the "Quick fix..." pop-up option didn't work, but today I found that clicking the "yellow light bulb" pop-up option works.

**Comment by mjbvz** [comment] 2019-08-11 09:52
Duplicate of #77018

**Closed by mjbvz** 2019-08-11 09:52 UTC
Labels: needs more info
