### ISSUE TITLE
Select all on hover selects stuff from global search

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#65174] opened 2018-12-16 21:51 UTC
Issue Type: <b>Bug</b>

Trying to do https://github.com/Microsoft/vscode/issues/63296#issuecomment-439553039

1. Open global search viewlet and execute search
1. Put cursor inside editor in place where hover is available
1. `editor.action.showHover`
1. `editor.action.selectAll`
1. 🐛 The text from search results and tab titles and even some opened editor text is selected

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment] 2018-12-17 18:58
I see this, but strangely, I can only get "select all" in the hover to work at all on Windows as described in https://github.com/Microsoft/vscode/issues/63296#issuecomment-439820773.

On Mac I see

- cmd+K cmd+I to show the hover and focus it
- cmd+A to select all the hover content
- But the editor text is selected instead, and hover text is not selected.

Any idea why @alexandrudima? I can debug if you know how the keypress is supposed to be intercepted.

**Comment by alexandrudima** [comment] 2018-12-19 20:23
@roblourens The weird behaviour that you see on macOS shares the same root cause as #35225 i.e. I think cmd+A is dispatched by the Electron menu and then we invoke `editor.action.selectAll` even if `textInputFocus` is not defined in the context. Since we just merged #64228 you should not see the weirdness anymore, i.e. cmd+A will be dispatched by our keybindings service even on macOS... But I haven't really tested...

AFAICT on Windows the ctrl+A falls back to execute what ctrl+A would execute in a browser (i.e. nobody calls preventDefault). That ends up selecting anything that is selectable, including inputs. I am thinking @usernamehw wishes that ctrl+A when the focus is in the hover would select only the hover contents. That would need to be implemented, i.e. a feature request for the editor hover.

**Comment by roblourens** [comment] 2018-12-21 23:00
Yeah, now cmd+A on mac does nothing in this case, which I guess is correct.

I think your explanation makes sense, I'll assign this to you for

> That would need to be implemented, i.e. a feature request for the editor hover.

**Comment by alexandrudima** [comment] 2019-01-07 11:34
Due to how the native menu dispatches keybindings, there are still differences between Windows and macOS when focus is in the hover:
 - on macOS, pressing cmd+A does nothing (because it ends up executing `editor.action.selectAll` due to the dynamic menu items)
 - on Windows, pressing ctrl+A selects all (i.e. the default browser select all, including the search input, etc.)

Let's keep this issue as a feature request to implement a new action that would select all inside a hover.

**Closed** 2021-11-13 15:14 UTC
Labels: feature-request, editor-hover
