### ISSUE TITLE
Code Does not respect system tab bind

### ISSUE THREAD

**Issue by Warfields** [microsoft/vscode#82936] opened 2019-10-20 18:28 UTC
- VSCode Version: 1.39.2
- OS Version: Fedora 31 (Linux)

Steps to Reproduce:

1. `$ setxkbmap us 3l`
2. launch code, in us-3l tab is mapped to caps lock. Code only accepts the regular tab key, the one physically printed on the keyboard. Thus the system tab bind does not work in code.

The proper behaviour should be to respect the system's tab key bind. Every other application on the system does not have this problem so it's specific to VS Code.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment] 2019-10-20 22:20
You can check this page to see if there are any relevant tips: https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexandrudima** [comment] 2019-10-22 22:05
Duplicate of #23991

**Closed by alexandrudima** 2019-10-22 22:05 UTC
