### ISSUE TITLE
VSCode cannot git push to a personal SSH origin, terminal can

### ISSUE THREAD

**Issue by Thibibi** [microsoft/vscode#182123] opened 2023-05-10 22:06 UTC
Hello, I precise that I use the "stock" VSCode 1.77.3 on Windows.
My git repository's origin is not on github, it is on a personal SSH URL:

```
$ git config --get remote.origin.url
ssh://user@host:321/path/git/project

```
I use a special port 321 and not the classic ssh one.

From VSCode terminal window, a classic git push command prompts for the password and everything goes fine:

```
$ git push
user@host's password: (here I enter manually the password)
Enumerating objects: 159, done.
Counting objects: 100% (159/159), done.
Delta compression using up to 12 threads
Compressing objects: 100% (113/113), done.
Writing objects: 100% (113/113), 19.23 KiB | 1.92 MiB/s, done.
Total 113 (delta 96), reused 0 (delta 0), pack-reused 0
To ssh://host:321/path/git/project
   90fa33d..aebda77  master -> master
$
```

But if instead of doing a terminal git push, I try the "Sync changes 1 ↑" button.

It takes some seconds to fail, the error message reads:

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at d:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:1703
    at d:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:1922
    at d:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:1938
    at Object.<anonymous> (d:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:2044)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
Permission denied, please try again.
d:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1
(()=>{"use strict";var e={4516:(e,s,r)=>{Object.defineProperty(s,"__esModule",{value:!0}),s.IPCClient=void 0;const t=r(8605);s.IPCClient=class{constructor(e){this.b=e;const s=process.env.VSCODE_GIT_IPC_HANDLE;if(!s)throw new Error("Missing VSCODE_GIT_IPC_HANDLE");this.a=s}call(e){const s={socketPath:this.a,path:`/${this.b}`,method:"POST"};return new Promise(((r,n)=>{const o=t.request(s,(e=>{if(200!==e.statusCode)return n(new Error(`Bad status code: ${e.statusCode}`));const s=[];e.on("data",(e=>s.push(e))),e.on("end",(()=>r(JSON.parse(Buffer.concat(s).toString("utf8")))))}));o.on("error",(e=>n(e))),o.write(JSON.stringify(e)),o.end()}))}}},5747:e=>{e.exports=require("fs")},8605:e=>{e.exports=require("http")}},s={};function r(t){var n=s[t];if(void 0!==n)return n.exports;var o=s[t]={exports:{}};return e[t](o,o.exports,r),o.exports}var t={};(()=>{var e=t;Object.defineProperty(e,"__esModule",{value:!0});const s=r(5747),n=r(4516);function o(e){console.error("Missing or invalid credentials."),console.error(e),process.exit(1)}!function(e){if(!process.env.VSCODE_GIT_ASKPASS_PIPE)return o("Missing pipe");if(!process.env.VSCODE_GIT_ASKPASS_TYPE)return o("Missing type");if("https"!==process.env.VSCODE_GIT_ASKPASS_TYPE&&"ssh"!==process.env.VSCODE_GIT_ASKPASS_TYPE)return o(`Invalid type: ${process.env.VSCODE_GIT_ASKPASS_TYPE}`);if("fetch"===process.env.VSCODE_GIT_COMMAND&&process.env.VSCODE_GIT_FETCH_SILENT)return o("Skip silent fetch commands");const r=process.env.VSCODE_GIT_ASKPASS_PIPE,t=process.env.VSCODE_GIT_ASKPASS_TYPE,i="https"===t?e[2]:e[3];let c,p,a;"https"===t&&(c=e[4].replace(/^["']+|["':]+$/g,"")),"ssh"===t&&(/passphrase/i.test(i)?p=e[6].replace(/^["']+|["':]+$/g,""):(c=e[6].replace(/^["']+|["':]+$/g,""),a=e[15])),new n.IPCClient("askpass").call({askpassType:t,request:i,host:c,file:p,fingerprint:a}).then((e=>{s.writeFileSync(r,e+"\n"),setTimeout((()=>process.exit(0)),0)})).catch((e=>o(e)))}(process.argv)})();var n=exports;for(var o in t)n[o]=t[o];t.__esModule&&Object.defineProperty(n,"__esModule",{value:!0})})();

```

I'm not asked the password to my ssh URL.

I can't imagine I'm the only one with this kind of problem, thanks for your help :-)

**Comment by vimalgorasiya** [comment] 2023-07-21 05:16
Hi,

I am using VSCode 1.80.1 on Windows. I ma exact save issue as described by @Thibibi. VSCode isn't asking for password and just failed. 

@lszomoru  Is there any update on the issue? approx. time when it will be fixed?

Thanks.

**Comment by lszomoru** [comment] 2023-12-05 10:43
Closing this as duplicate of https://github.com/microsoft/vscode/issues/179517

**Closed by lszomoru** 2023-12-05 10:43 UTC
Labels: bug, git, ssh
