### ISSUE TITLE
editor.action.quickFix command cannot be completed using the keyboard

### ISSUE THREAD

**Issue by boris-ilijic** [Microsoft/vscode#24204] opened 2017-04-07 09:32 UTC
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:
1. In editor (typescript file) use editor.action.quickFix command (ctrl+.) to automatically generate import statement for certain type
2. Pop-up window is shown with the one or more options (e.g. Import xxx from 'yyy')
3. It is not possible to select any popup menu item using keyboard (arrow keys). So in my case, I need to use touchpad or mouse to choose the menu item.

**Comment by chrmarti** [comment] 2017-04-07 14:55
Which color theme are you using? The selection color seems to be more subtle than it used to be. Maybe it still works without the selected item being highlighted?

**Comment by boris-ilijic** [comment] 2017-04-07 15:24
So I am using: Monokai Dimmed.
You are right, it is working, but the selected item is highlighted very subtle. It is very confusing in case when only one menu item is in the popup list (basically you cannot see the difference in transition from non-selected to selected item).

Basically, for light themes the difference is obvious, but for dark group of themes is not.

**Comment by aeschli** [comment] 2017-04-07 15:42
I think it's a native menu, not sure if we have controls over the colors

**Comment by jrieken** [comment] 2017-04-10 07:18
Yes, it's the native context menu

**Comment by jrieken** [comment] 2017-04-10 09:24
![apr-10-2017 11-23-56](https://cloud.githubusercontent.com/assets/1794099/24854892/37eaaee8-1de0-11e7-887b-7d4a12db27b7.gif) I can also not reproduce on windows

**Comment by jrieken** [comment] 2017-04-11 13:44
Closing because this issue is without actionable information.

**Closed by jrieken** 2017-04-11 13:44 UTC
Labels: needs more info, not-reproducible
