### ISSUE TITLE
Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined   Code: -32603 

### ISSUE THREAD

**Issue by 13308080401** [Microsoft/vscode#30895] opened 2017-07-18 02:22 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.7
debugger-for-chrome|msj|3.1.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment] 2017-07-18 08:17
duplicate of #30774

**Closed by aeschli** 2017-07-18 08:17 UTC
Labels: new release

**Comment by JkSue** [comment] 2017-07-26 14:28
excuse me.
why does it happen?

**Comment by JkSue** [comment] 2017-07-27 08:07
ok
i fund the reason.
if you are confused.
remember!
your code has no bugs,
it is the bug of vs.

**Comment by xjy666** [comment] 2017-08-09 09:53
How do you solve this problem?
