### ISSUE TITLE
Proxy Authentication dialog does not work properly

### ISSUE THREAD

**Issue by vacvvn** [microsoft/vscode#104790] opened 2020-08-17 08:23 UTC
- VSCode Version: 1.48
- OS Version: Xubuntu 18.04

Proxy authentication dialog does not work properly. After filling login and pass fields clicks on buttons Ok or Cancel do nothing and dialog does not close after that. You can only close the dialog with close button.

Steps to Reproduce:

1. Open VS Code 1.48 with proxy authentication
2. Try to fill login and pass fields and click on Ok or Cancel buttons.

Does this issue occur when all extensions are disabled?: Yes

**Comment by vacvvn** [comment] 2020-08-17 08:37
Proxy authentication dialog does not work properly. After filling login and pass fields clicks on buttons Ok or Cancel do nothing and dialog does not close after that. You can only close the dialog with close button.

**Comment by orthoxerox** [comment] 2020-08-17 09:00
I have the same issue on Win32-x64

**Comment by nihlete** [comment] 2020-08-17 09:20
Same Issue with Manjaro x86-64.
Also there is rendering problem with dialog window in 70% of time: wrong paddings and dissapearing file menu.

![pic](https://user-images.githubusercontent.com/9762164/90379778-d78e8280-e083-11ea-8e70-cd9c0eca5196.png)

**Comment by gjsjohnmurray** [comment] 2020-08-17 09:53
/duplicate of #104603 which offers a workaround

**Closed** 2020-08-17 09:54 UTC
Labels: *duplicate
