### ISSUE TITLE
Changes view does not update when opening a symbolic link folder

### ISSUE THREAD

**Issue by antheas** [microsoft/vscode#143034] opened 2022-02-14 17:44 UTC
Issue Type: <b>Bug</b>

When working on a server I typically have access to a large drive share where I can place my experiments (ex. /mnt/myuser).

However, I prefer working on my user path so I usually soft link it.

```bash
ln -s /mnt/ext ~/ext
code ~/ext
```

When code is running on the soft linked directory (such as a subdirectory of ~ext), the file watcher doesn't work correctly.

Git won't update with new changes and I have to click refresh, the explorer won't lint ignored files with gray, changed files with green/orange.

This happens both on SSH hosts and locally.

To reproduce:
```bash
mkdir -p tst/target && cd tst
ln -s . ln
code target
code ln/target
```

VS code opened with `code target` works correctly, whereas `code ln/target` has the missing features. Clone a repository to make it more obvious.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.16.8-arch1-1
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-99-generic
Remote OS version: Linux arm64 5.11.0-1027-oracle
Remote OS version: Linux x64 5.4.0-99-generic
Remote OS version: Linux x64 5.4.0-99-generic

Extensions: none

**Comment by bpasero** [comment] 2022-02-15 08:22
Our file watcher supports symlinks, we even have a unit test for that:

https://github.com/microsoft/vscode/blob/b03fe7a97c06ae1906efd62e616d383704ee95e7/src/vs/platform/files/test/node/parcelWatcher.integrationTest.ts#L440-L448

Does this issue reproduce on Linux with these condition:
* no remote involved
* no mounted drive involved
* just a folder symlinked to another folder

**Comment by bpasero** [comment] 2022-02-15 09:47
> The watcher does kind of work to be fair.

How do you know actually? If you run code with `--verbose` you get detailed file event output from developer tools (from Help menu):

![image](https://user-images.githubusercontent.com/900690/154036287-61130af1-8aae-46ec-aa0f-3a432f0ab2a4.png)

**Comment by renkun-ken** [comment] 2022-02-17 15:05
We observed something similar too (https://github.com/REditorSupport/vscode-R/issues/986). In my case, when a PNG file is created in a temp folder, and I open the file in the editor. When the PNG file is updated, the editor tab does not refresh. It works since the beginning, but from a recent release (not sure which exactly) it no longer refreshes automatically.

I tried using a non-symlink path but it won't work if the file is in system temp folder no matter if it is symlink folder.

**Comment by bpasero** [comment] 2022-02-17 15:20
That sounds like an issue independent from Git and please report it as a separate one. Would also be interesting if that only reproduces for PNG files or for normal text files as well because maybe it is not an issue with file watching but with the editor that shows the file not updating properly.

**Comment by renkun-ken** [comment] 2022-02-17 16:04
Reported as an separate issue #143291. Looks like image file in temp folder won't update, but text file works normally.

**Comment by lszomoru** [comment] 2022-12-07 11:52
At the moment VS Code does not fully support Git repositories that have a symbolic link on their path. Here is the issue tracking this feature request - https://github.com/microsoft/vscode/issues/5970. I will be closing this as duplicate and I would like to suggest that you subscribe to the linked issue to get notified when the work is being scheduled. Thank you!

**Closed by lszomoru** 2022-12-07 11:52 UTC
Labels: git
