### ISSUE TITLE
"Go to definition" still broken in after updating to 1.25

### ISSUE THREAD

**Issue by frednomoon** [Microsoft/vscode#53725] opened 2018-07-06 15:32 UTC
- VSCode Version: 1.25
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. Use `export default` to export an unnamed function from a javascript file
2. Import the function from another file
3. Cmd-click an instance of the function in the file where you imported it.

![screenshot 2018-07-06 16 16 18](https://user-images.githubusercontent.com/23635508/42387504-5a8badee-813a-11e8-817d-17cb7e12c7d2.png)
![screenshot 2018-07-06 16 16 28](https://user-images.githubusercontent.com/23635508/42387505-5aa1b5b2-813a-11e8-9a6a-2b38bf007255.png)

Does this issue occur when all extensions are disabled?: Yes

I've been following various issues relating to this bug, mostly now suggesting that it has been fixed. But clearly in the most recent update it is still a problem! Please fix this asap as am forced to downgrade to March release until it is.

**Comment by mjbvz** [comment] 2018-07-06 20:29
Duplicate of #51918

**Closed by mjbvz** 2018-07-06 20:29 UTC
Labels: javascript
