### ISSUE TITLE
Emmet does not expand for reverse number syntax $@-

### ISSUE THREAD

**Issue by riturajshakti** [microsoft/vscode#87657] opened 2019-12-24 17:36 UTC
Issue Type: <b>Bug</b>

ul>li{my list $@-}*5
not working correctly

Im talking about reverse numbering in emmet

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.15.0-72-generic

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
auto-rename-tag|for|0.1.1
rest-client|hum|0.23.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.2
vscode-css-peek|pra|3.0.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by octref** [comment] 2020-01-08 10:10
It should generate 

```html
<ul>
	<li>my list 5</li>
	<li>my list 4</li>
	<li>my list 3</li>
	<li>my list 2</li>
	<li>my list 1</li>
</ul>
```

**Comment by rzhao271** [comment] 2020-10-05 20:50
Duplicate of #69168

**Closed by rzhao271** 2020-10-05 20:50 UTC
Labels: bug, emmet
