### ISSUE TITLE
Clicking into debug console editor updates status bar with some entries

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16478] opened 2016-12-05 06:37 UTC
Just click on the debug console editor and notice the status bar updating weird:

![view-picker](https://cloud.githubusercontent.com/assets/900690/20875770/a0947bf8-babd-11e6-86d6-0ff1fc298457.gif)

**Comment by isidorn** [comment] 2016-12-05 10:57
This is coming from the typescirpt extension.
The extension should not remove the typescript version if the other opened editor has also mode typesciprt.

Forwarding to @mjbvz and @dbaeumer

**Comment by dbaeumer** [comment] 2016-12-05 11:42
@isidorn which other `opened editor`. The TS extension (in line with all the other extensions showing status in the status bar) only shows the status bar item if a TS/JS file is active?

**Comment by isidorn** [comment] 2016-12-05 11:56
@dbaeumer the debug console input is an editor. And once it gets focused the ts extension hides the status bar item

**Comment by dbaeumer** [comment] 2016-12-05 13:07
@isidorn which language mode does the console input have. It is not JS or TS then that behavior is expected. ESLint, TSLint, C# all behave that way

**Comment by isidorn** [comment] 2016-12-05 13:17
@dbaeumer it has 'plaintext' as a mode

**Comment by dbaeumer** [comment] 2016-12-06 09:49
Discussed with @bpasero. The problem is that the extension received and event that the active editor has changed and the new active editor doesn't show a TS file. Hence we remove the status bar item.

As discussed moving to @bpasero

**Comment by bpasero** [comment] 2016-12-06 18:03
I looked into it and there seems to be a `vscode.window.onDidChangeActiveTextEditor` event fired as soon as you click into the input field of the repl. This causes the status bar to think that a TypeScript file is no longer active. Once you click into the repl, somehow the extension is back to thinking that a TypeScript file is active.

No matter where I click in the UI, I would assume that the active editor is always the editor that is active in the editor part and not the debug repl input.

As to why there is such a difference between repl input and repl editor, I am not sure. So I assign this back to some people that might have more insight.

**Comment by bpasero** [comment] 2016-12-06 18:11
Actually much more obvious repro:
* open a TS file and have TS lint extension installed
* you see the TS lint status and the mode of the file being typescript
* open an output channel

=> the mode is still typescript
=> 🐛  the TS lint status bar is gone

**Comment by jrieken** [comment] 2016-12-06 18:22
> No matter where I click in the UI, I would assume that the active editor is always the editor that is active in the editor part and not the debug repl input. 

No, the workbench API isn't sufficient because it doesn't capture things like embedded editors (zone widgets) nor does it differentiate between left/right in diff editors. That's the reason why there is an `ICodeEditorService` (ever wondered how keybindings work?)

If the debug repl, output etc are supposed to show as editor has been discussed before. There is no easy answer and there are extension relying on this.

**Comment by jrieken** [comment] 2016-12-07 07:12
This isn't 'as-designed'. The TS extension should for the correct active editor.

**Comment by bpasero** [comment] 2016-12-07 07:26
@jrieken and how would the TS extension be able to do that if the `onDidChangeActiveTextEditor` event is fired when clicking on the output channel?

**Comment by jrieken** [comment] 2016-12-07 08:09
it can check on the document language and/or uri

**Comment by bpasero** [comment] 2016-12-07 08:22
@jrieken I do not think that this would be enough information for the TS extension to make the call because it can not distinguish that the user clicked from the TS editor into the output editor. The user might have as well clicked into another real editor in the editor area and so the TS extension is doing the right thing of updating its status.

As I said earlier, I would not expect `onDidChangeActiveTextEditor` to fire for the output editor or any other editor that is not inside the editor area. I would even argue that it should not fire for when you move focus into an editor that is inside a viewzone. I would not expect the TS language indicator to change if I click from my main active editor into a viewzone.

Btw, since `onDidChangeActiveTextEditor` does not fire when you put the cursor into the repl input field (which is also an editor) I think we already do some filtering.

**Comment by jrieken** [comment] 2016-12-07 09:36
> Btw, since onDidChangeActiveTextEditor does not fire when you put the cursor into the repl input field (which is also an editor) I think we already do some filtering.

It does fire. With the snippet below I see `uri: debug:input` and `lang: plaintext` being printed.

```ts
    vscode.window.onDidChangeActiveTextEditor(editor => {
        if (editor) {
            console.log('uri: ' + editor.document.uri.toString());
            console.log('lang: ' + editor.document.languageId);
        }
    })
```

<img width="527" alt="screen shot 2016-12-07 at 10 35 27" src="https://cloud.githubusercontent.com/assets/1794099/20962249/e8642b84-bc68-11e6-8440-0063718b8a19.png">


With the output channel it shows `lang: Log` and `inmemory://model/N`. So while it might be questionable that they show as (active) editor at all it is at least consistent and provides enough information to identify them (scheme, lang-id, etc). I'd say for TypeScript there is enough information to make the decision. 

>  I would even argue that it should not fire for when you move focus into an editor that is inside a viewzone. I would not expect the TS language indicator to change if I click from my main active editor into a view zone.

The active editor is used for more then that language indicator. Think of a "sort lines" extension: When focus is in an embedded editor it should sort the lines selected in there. Everything else would be confusing.

**Comment by dbaeumer** [comment] 2016-12-07 17:17
The TS extension does listen to the onDidChangeActiveTextEditor and since the language mode isn't `typescript` or `javascript` hides the status item.

I am not sure what @jrieken and @bpasero suggest to do here. Should we hard code that we keep the status item even if the document uri is debug:input. Then all extensions having some status bar item (ESLint, TSLint, ...) have to do the same and I think this is not feasible given that not all extensions have to be under our control. Wouldn't it be more consistent if the language mode switcher would show something like `Debug Repl` especially since the reply is the active text editor / input. Cut, Copy, Paste, and other editor actions traget the repl input box and not the visible text editor anymore.

**Comment by jrieken** [comment] 2016-12-07 17:22
The easiest change TS/JS can do is to check if the [`viewColumn`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L955) of the active editor is defined

**Comment by dbaeumer** [comment] 2016-12-07 17:26
Nice trick. But with an enabled other extension showing status we will still might have flicker :-)

**Comment by jrieken** [comment] 2016-12-08 08:23
That's true. I'd think we should fold it into the language status provider story which is about a language being able to tell something about a language, like "typescript, version information", "javascript, eslint lib missing" etc

**Comment by dbaeumer** [comment] 2016-12-08 08:59
I like that suggestion. I will move the item to January when @jrieken plans to work on this.

**Comment by dbaeumer** [comment] 2017-01-23 20:18
Moving to February. Didn't have time to look into the new language status provider.

@mjbvz would you have time to look into this in Feb.

**Closed** 2017-03-07 00:45 UTC
Labels: bug, verification-needed
