### ISSUE TITLE
Tasks slow since 1.29.0

### ISSUE THREAD

**Issue by admvx** [Microsoft/vscode#63055] opened 2018-11-13 20:04 UTC
Issue Type: <b>Performance Issue</b>

Since installing the update to 1.29.0, I've noticed a significant delay in task actions, in two distinct spots:
- Between summoning the task list and the list becoming populated
- Between selecting a task and that task starting to execute (as indicated on the status bar)

In both cases, the delay lasts around 1.5 to 2 seconds, and is consistent across several attempts, with and without extensions enabled, before and after system restarts. Prior to this issue, the duration of these actions was normally less than 0.5 seconds.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (24 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (52.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	 13240	code main
    0	   151	  4616	   window (Redacted)
    0	    13	  1916	     electron-crash-reporter
    0	    81	 14008	     extensionHost
    0	    62	 17068	       electron_node server.js 
    0	    35	 17248	       C:\Users\avernon\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.953\dotnet_modules\vsls-agent.exe --autoexit --pipe 63fc90e5aed54aceb947f4348020384b --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	     9	 17292	         console-window-host (Windows internal process)
    0	   199	 11452	   window (Redacted (Workspace))
    0	    42	  3172	     watcherService
    0	    63	 17280	     extensionHost
    0	    37	 22748	     searchService
    0	    98	 15056	   gpu-process
    0	    65	 16784	   shared-process
    0	    67	 23216	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window - (Redacted (Workspace))
|    Folder (pre-apt): 34 files
|      File types: as(14) fla(5) swf(5) js(3) json(2) p4ignore(1) html(1)
|                  editorconfig(1) md(1) css(1)
|      Conf files: package.json(1)
|    Folder (ui): more than 40781 files
|      File types: png(32027) swf(2844) as(2366) fla(1870) xml(1389) nav(138)
|                  ttf(110) PNG(20) txt(7) json(2)
|      Conf files: settings.json(1) tasks.json(1);
```

</details>
Extensions: none

**Comment by skarcha** [comment] 2018-11-15 08:15
Same problem here. Using a network filesystem it takes about 14 seconds! We've had to return to 1.28.2.

**Comment by skarcha** [comment] 2018-11-15 08:43
@dbaeumer Yes, it still reproduces.

**Comment by skarcha** [comment] 2018-11-15 08:45
@dbaeumer Well, we use our own extension for the language we use. It's no public, sorry, but worked fine until now.

**Comment by dbaeumer** [comment] 2018-11-15 08:57
@skarcha what does the extension do. Provide tasks ?

**Comment by Co0sh** [comment] 2018-11-15 10:08
I'm having the same issue. When trying to run a task it takes several seconds for the selection dropdown to show and then roughly the same time for the task to start. The delay is longer on bigger projects, especially in multi-root workspaces. I disabled all extensions and it's still happening. I also downgraded to 1.28.2 and the problem doesn't appear there, but comes back when updating to 1.29.0 again.

I noticed the `System and compressed memory` process (on Windows 10) taking a lot of CPU time both when waiting for the dropdown and for the task to start. Hope it helps 😄

**Comment by dbaeumer** [comment] 2018-11-15 14:42
@skarcha & @Co0sh which OS version are you on.

**Comment by dbaeumer** [comment] 2018-11-15 14:43
@skarcha how does the tasks.json look like?

**Comment by DarthSpock** [comment] 2018-11-15 14:46
I'd like to report the same issue of tasks running slow using a Win 7 VM.

**Comment by Co0sh** [comment] 2018-11-15 14:48
I'm on Windows 10 Pro, 64-bit, version 1511, build 10586.79

**Comment by dbaeumer** [comment] 2018-11-15 14:49
Actually I forgot on task provider. Can you disable that one as well. It is:

```json
"typescript.tsc.autoDetect": "off"
```

**Comment by Co0sh** [comment] 2018-11-15 14:55
@dbaeumer yes, that's probably it. Now tasks run instantly.

**Comment by franklin-ross** [comment] 2018-11-15 22:40
I have been seeing the same thing (except more like 30-60 seconds for the list to populate), and `"typescript.tsc.autoDetect": "off"` also fixes it for me.

Some more info:

* The slowdown seems to be caused by Windows Defender going completely nuts and pegging my CPU at 100% when the task list opens.
* If I don't disable my extensions, just opening VSCode has the same effect, causing Defender to sit my CPU at 100% for about a minute. I now realise it's probably the fact that we have a lot of TypeScript in our project.

**Comment by skarcha** [comment] 2018-11-16 07:05
@dbaeumer `"typescript.tsc.autoDetect": "off"` solves the problem for me.

O.S: Windows 10 Home, 64 bits, 1803. Build: 17134.407

**Comment by alexr00** [comment] 2018-11-16 10:29
Duplicate of #63078

**Closed by alexr00** 2018-11-16 10:29 UTC
Labels: new release, tasks

**Comment by wangfuxiong** [comment] 2018-11-28 03:33
@dbaeumer I'm using typescript so i can't off this "typescript.tsc.autoDetect": "off". it will take about 3-5 minutes fetching build tasks.

**Comment by dbaeumer** [comment] 2018-11-28 10:10
@wangfuxiong TS is working on fixing this.
