### ISSUE TITLE
PHP: Bugged syntax highlightning for a class variable when concatenating with string.

### ISSUE THREAD

**Issue by min0rr** [microsoft/vscode#78767] opened 2019-08-09 08:05 UTC
**Example :**
const A_DBNAME = 'BROADCAST_archive';

$sql = "SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME LIKE 'zip%' AND TABLE_SCHEMA ='".ArchivationConfig::A_DBNAME."'";

**Problem is :**
There is no syntax highlightning for constant ArchivationConfig::A_DBNAME. It is shown as a part of string.

**Here it is:**
![image](https://user-images.githubusercontent.com/43531018/62763906-50ccc000-ba95-11e9-86f5-f2dfe1deb03c.png)

**Comment by alexr00** [comment] 2019-08-09 08:49
Duplicate of https://github.com/atom/language-php/issues/365

**Closed** 2019-08-09 08:50 UTC
Labels: bug, grammar
