### ISSUE TITLE
File System provider: calling sequence changed

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#71302] opened 2019-03-27 16:40 UTC
I have a custom file system provider that registers for the schema `lsif`. In the past I got a stat call with the folder-uri value I passed to `--folder-uri` command line parameter. E.g for 
```
--folder-uri=lsif:///c:/Users/dirkb/Projects/mseng/VSCode/vscode-lsif-extension/server/jsonrpc.db
```

the first stat call my FS provider recieved was for `lsif:///c:/Users/dirkb/Projects/mseng/VSCode/vscode-lsif-extension/server/jsonrpc.db`. This doesn't happen anymore. Instead the explorer shows

<img width="748" alt="capture" src="https://user-images.githubusercontent.com/1931590/55094528-d89dc900-50b6-11e9-913d-4aa851ad916d.png">

Please note the first folder `jsonrpc.db`. Clicking on it correctly gives

<img width="376" alt="capture" src="https://user-images.githubusercontent.com/1931590/55094992-b22c5d80-50b7-11e9-8567-c5f7d891be49.png">

since the stat call handled by the FS provider tells the system that the jsonrpc.db is a folder.

Please note that `c:/Users/dirkb/Projects/mseng/VSCode/vscode-lsif-extension/server/jsonrpc.db` is actually a file on disk, but the URI has no `file` schema.

I guess we have code somewhere now that takes the fspath and stats it on the file system without checking the schema.

Refreshing the explorer brings everything pack into order.

<img width="295" alt="capture" src="https://user-images.githubusercontent.com/1931590/55094814-68437780-50b7-11e9-8b10-64d9ccd32669.png">

Marking as important since this might affect other FS providers as well.

**Comment by dbaeumer** [comment] 2019-03-27 16:43
@jrieken FYI. May be it is me using the FS provider API incorrectly

**Comment by bpasero** [comment] 2019-03-27 17:36
> I guess we have code somewhere now that takes the fspath and stats it on the file system without checking the schema.

Unlikely...

**Comment by jrieken** [comment] 2019-03-27 17:55
@bpasero Is this maybe strict error handling that you talked about?

**Comment by dbaeumer** [comment] 2019-03-27 19:25
Steps to reproduce:

- clone c:/Users/dirkb/Projects/mseng/VSCode/vscode-lsif-extension/server/jsonrpc.db
- cd `vscode-lsif-extension`
- npm install
- npm compile
- ping me and I can provide you with the DB. Can't attach.
- change the launch config to point to the local db
- start the extension.

**Comment by dbaeumer** [comment] 2019-03-27 19:29
May be easier we debug this together tomorrow.

**Comment by dbaeumer** [comment] 2019-03-27 20:25
OK. I debugged this further and I now receive verz wired stat calls. The first one  is `lsif:///c:/Users/dirkb/Projects/mseng/VSCode/vscode-lsif-extension/server/jsonrpc.db/.git/config` and the new one is for `lsif:/// c:/Users/dirkb/Projects/mseng/VSCode/vscode-lsif-extension/server/jsonrpc.db/node_modules`.

I return `throws FileSystemError.FileNotFound(uri)` for these. @jrieken is this a problem?

**Comment by dbaeumer** [comment] 2019-03-27 20:34
Actually my last comment doesn't seem true. I couldn't see this a second time :-)

**Comment by dbaeumer** [comment] 2019-03-27 21:03
I could track this down further. The problem is that the first stat call I receive now is for `"lsif:/c%3A/Users/dirkb/Projects/mseng/VSCode/vscode-lsif-extension/server/jsonrpc.db/.vscode"` and not the root. Are there any assumptions about the first stat call?

**Comment by dbaeumer** [comment] 2019-03-27 21:22
I fixed this on my end to correctly handle this first stat. However if the first stat fails (in this case it was a DB error, not a FileNotFound error) then the explorer should indicate this and not simply show the last segement as a node. We should also make clear that the root folder might not be the first thing that gets stat.

Removing the important label.

**Comment by bpasero** [comment] 2019-03-28 06:59
@dbaeumer please do not make any assumptions about which stat call comes first or second. The `IFileService` is a service that is now being used in lots of places, e.g. to load the configuration very early on (which probably is the call you see for the `.vscode` folder). The explorer is coming only a lot later to resolve itself and even other services might use the file service to resolve things (like output channels).

As for how the explorer reacts to this, I leave this up to @isidorn to decide who I think pushed a change to not leave the explorer empty in case of an error.

**Comment by isidorn** [comment] 2019-03-28 10:06
The explorer will now show an error item which imho is better than being empty since it gives context to the user as to what went wrong.
Closing as designed.

**Closed by isidorn** 2019-03-28 10:06 UTC
Labels: file-explorer

**Comment by dbaeumer** [comment] 2019-03-29 16:43
@isidorn in my setup it didn't show an error. It shows the last path segment with an exclamation mark. Is this expected ?

**Comment by isidorn** [comment] 2019-04-01 12:33
@dbaeumer yeah. But I can change that to also show the error via the notification service. Would you prefer that experience?

**Comment by dbaeumer** [comment] 2019-04-03 08:35
No, I would expect to see a more descriptive explanation in the explorer itself. Could the folder have a sub node explaining what went wrong?

**Comment by isidorn** [comment] 2019-04-03 08:56
@dbaeumer yeah we could do that. However so far we decided not to show errors like that.
Another example when we show it like this is when a user has a broken .code-workspace file which points to wrong paths. In that case we still use explorer decorations like this + hover message to show error.
Anyways created this feature request and we can see if we implement this in the future https://github.com/Microsoft/vscode/issues/71646
