### ISSUE TITLE
have an extension with user interface?

### ISSUE THREAD

**Issue by cwtuan** [Microsoft/vscode#33597] opened 2017-08-31 14:08 UTC
Google chrome extensions can have custom UI built with HTML/CSS/JAVASCRIPT.
Could vscode have the same ability?

**Comment by jrieken** [comment] 2017-08-31 14:38
duplicate of #1833

**Closed by jrieken** 2017-08-31 14:38 UTC
Labels: extensions

**Comment by cwtuan** [comment] 2017-08-31 14:40
@jrieken Actually, I'm not sure if my requirement is custom extension. What I want is custom menu item
