### ISSUE TITLE
Title bar min/max/close button area blocks the context menu

### ISSUE THREAD

**Issue by Paper-Folding** [microsoft/vscode#197988] opened 2023-11-11 06:15 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: windows 10

Steps to Reproduce:

1. Right click on title bar near the top right corner;
2. See the context menu was blocked by min/max/close buttons:  
<img width="403" alt="image" src="https://github.com/microsoft/vscode/assets/49343539/dfa27f74-6fde-46b9-9eac-739fac3bbf7e">

Trivia:  
There seems to have a `window.experimental.windowControlsOverlay.enabled` config that can make title bar min/max/close buttons to have transparent background (see https://stackoverflow.com/a/73595132/14963554), but it's gone in recent versions, can we bring back the feature in other ways?

**Comment by sbatten** [comment] 2023-12-18 23:55
dupe of https://github.com/microsoft/vscode/issues/160518

**Closed by sbatten** 2023-12-18 23:55 UTC
