### ISSUE TITLE
This damn thing is too difficult to use, it can't even be turned off

### ISSUE THREAD

**Issue by xubinglove** [microsoft/vscode#225241] opened 2024-08-09 12:45 UTC
This damn thing is too difficult to use, it can't even be turned off

![image](https://github.com/user-attachments/assets/fb3b8ebe-69b8-43c2-ab0c-0293403b9638)

**Comment by gjsjohnmurray** [comment] 2024-08-09 12:50
Did you try the setting `"scm.showHistoryGraph": false` that the release notes mention?

**Comment by gjsjohnmurray** [comment] 2024-08-09 12:51
Or the options on the overflow menu on the Incoming / Outgoing line?

**Comment by suttonb** [comment] 2024-08-10 13:53
> Or the options on the overflow menu on the Incoming / Outgoing line?

What options do you see? All I have is the choice to select/deselect certain branches, nothing about turning it off or hiding it.

**Comment by suttonb** [comment] 2024-08-10 13:56
The ability to expand/collapse it would be nice, instead of having to go into the settings and turn it on or off entirely.

**Comment by gjsjohnmurray** [comment] 2024-08-10 15:52
@suttonb in the current Insiders you can toggle the`scm.showHistoryGraph` setting from that menu.

**Comment by gogokd** [comment] 2024-08-11 04:08
> Did you try the setting `"scm.showHistoryGraph": false` that the release notes mention?

Thank goodness, you saved my life.

If a setting requires searching on Google to figure out how to turn it off, it means it's not user-friendly enough.

**Comment by gjsjohnmurray** [comment] 2024-08-11 04:40
> If a setting requires searching on Googl

To be fair, the setting is documented in the Release Notes of the VS Code version in which the history graph first appeared. It is mentioned alongside a screenshot of that feature.

**Comment by suttonb** [comment] 2024-08-12 13:44
> @suttonb in the current Insiders you can toggle the`scm.showHistoryGraph` setting from that menu.

Good to know, thank you!

**Comment by lszomoru** [comment] 2024-08-19 11:08
Closing as duplicate of https://github.com/microsoft/vscode/issues/224517

**Closed by lszomoru** 2024-08-19 11:08 UTC
