### ISSUE TITLE
SCROLL TO FAST AND LAG

### ISSUE THREAD

**Issue by lavensoft** [microsoft/vscode#146685] opened 2022-04-04 03:01 UTC
Issue Type: <b>Bug</b>

After Update new version, my workspace scroll to fast

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|16.00GB (2.87GB free)|
|Process Argv|--crash-reporter-id 681bf267-c944-4e0c-b9b5-5cc25685455c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.4
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
fileheadercomment|doi|0.0.5
copilot|Git|1.11.5453
vscode-drawio|hed|1.6.4
beautify|Hoo|1.5.0
cpptools|ms-|1.9.7
material-icon-theme|PKi|4.15.0
java|red|1.4.0
LiveServer|rit|5.7.5
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-maven|vsc|0.35.1
vscode-spring-initializr|vsc|0.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30465021
pynewfile477:30463512

```

</details>

**Comment by O4epegb** [comment] 2022-04-08 12:06
Probably duplicate of https://github.com/microsoft/vscode/issues/146403?

**Comment by deepak1556** [comment] 2022-04-08 12:35
Merging to https://github.com/microsoft/vscode/issues/146403

**Closed by deepak1556** 2022-04-08 12:35 UTC
Labels: needs more info, triage-needed
