### ISSUE TITLE
drop down menu

### ISSUE THREAD

**Issue by MiloshBo** [microsoft/vscode#80232] opened 2019-09-02 19:44 UTC
When I click on File, Edit or any other drop down menu instead of being black and opaque it's gray and transparent so it interferes with background content and it's less visible. It happened after I installed several extension. Don't know if it's related to that.

**Comment by MiloshBo** [comment] 2019-09-02 19:45
![vscode](https://user-images.githubusercontent.com/37314311/64131741-e9233f80-cdca-11e9-940b-4413355ef240.png)

**Comment by usernamehw** [comment] 2019-09-02 20:57
Possible duplicate of #60543

**Comment by MiloshBo** [comment] 2019-09-02 21:10
> 
> 
> Possible duplicate of #60543

I don't think that #60543 also offered a solution. Did I miss anything?

**Comment by weinand** [comment] 2019-09-02 21:55
Please disable all extensions and see whether the problem persists. If not, then file an issue against the extension that triggers the problem.

**Comment by MiloshBo** [comment] 2019-09-03 20:03
> 
> 
> Please disable all extensions and see whether the problem persists. If not, then file an issue against the extension that triggers the problem.

I disabled all extensions, the issue was solved, and then enabled one by one. The one that brought trouble is PlasticAB. After I uninstalled it things are ok again.

**Closed** 2019-09-11 08:16 UTC
Labels: needs more info

**Comment by weinand** [comment] 2019-09-11 08:18
great, thanks for finding the culprit.
