### ISSUE TITLE
Typescript died upon attempting to view release notes.

### ISSUE THREAD

**Issue by gogosphere** [Microsoft/vscode#26032] opened 2017-05-05 13:16 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|format-php|Kasik96|1.1.2|
|python|donjayamanne|0.6.3|
|Go|lukehoban|0.6.59|;

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment] 2017-05-05 13:43
Cannot reproduce and need more detailed steps.

Can you please reproduce with typescript logging turned on. Set "typescript.tsserver.log" to "verbose" and include the log?

**Comment by mjbvz** [comment] 2017-05-10 05:46
Closing as there is not enough information to investigate this issue

**Closed by mjbvz** 2017-05-10 05:46 UTC
Labels: needs more info, typescript
