### ISSUE TITLE
Intellisense preview tooltip stuck after a while - remains open

### ISSUE THREAD

**Issue by juristr** [Microsoft/vscode#66203] opened 2019-01-08 09:06 UTC
- VSCode Version: Version 1.31.0-insider (1.31.0-insider)
- OS Version: macOS Mojave 10.14.2

**Steps to Reproduce:** . 

Unfortunately it's rather hard to give step-by-step reproduction as it starts happening "after a while". When writing the code after a bit, the intellisense preview of the function gets stuck and remains above the course until a restart. Using ESC or any other try to close it doesn't work. Also, it's not always the same, did multiple tries (also with extensions disabled).

![vscode-intellisensepreview-bug](https://user-images.githubusercontent.com/542458/50819246-c4ed8c80-1329-11e9-8138-72d4b9c80dbf.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by juristr** [comment] 2019-01-08 10:00
This seems even worse. A side-effect of this is that in case you get multiple overloads of a function, the cursor seems to be trapped inside the tooltip, so navigating around with the keyboard arrow keys doesn't work anymore.

![image](https://user-images.githubusercontent.com/542458/50823568-945f2000-1334-11e9-94cb-c499f58d3e06.png)

**Comment by juristr** [comment] 2019-01-08 10:07
@bpasero @joaomoreno is it possible to somehow get a console trace or something from VSCode to help you guys identify what the problem here could be? Insiders version isn't really usable with this right now as I keep getting my cursor trapped by this tooltip 😅

**Comment by damir-sirola** [comment] 2019-01-08 10:15
I'm experiencing the same issue on Windows (same version of VSCode).
Instead of restarting VSCode you can just run "Reload Window" from Command Palette.

**Comment by juristr** [comment] 2019-01-08 11:06
> restarting VSCode you can just run "Reload Window" from Command Palette.

@damir-sirola Yep, that's what I meant with restarting 😁, however it stops my devserver etc..

**Comment by juristr** [comment] 2019-01-08 14:06
Latest Insider update Version 1.31.0-insider (1.31.0-insider) (7b375fcb821bee9342656c39492223c7b5fc8830) seems to have fixed this. Leaving the issue open for a couple of hours to verify it doesn't pop up again

**Comment by juristr** [comment] 2019-01-08 16:00
for me it is solved with the latest Insider. @damir-sirola can you confirm?

**Comment by mjbvz** [comment] 2019-01-08 19:38
Duplicate of #66202

**Closed by mjbvz** 2019-01-08 19:38 UTC
