### ISSUE TITLE
SCM commit message is lost if I press up or down while typing it

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#109121] opened 2020-10-22 00:24 UTC
- Type some text in the commit box
- Press up or down arrow on accident
- The text I typed is gone from history

You might have mentioned this case in standup, but I wasn't sure. Feel free to close it as a duplicate if there is already an issue for it

**Comment by joaomoreno** [comment] 2020-10-27 16:07
Duplicate of https://github.com/microsoft/vscode/issues/109443

**Closed by joaomoreno** 2020-10-27 16:07 UTC
