### ISSUE TITLE
The panel bar hides important features!

### ISSUE THREAD

**Issue by moshe5342** [microsoft/vscode#160149] opened 2022-09-06 07:41 UTC
Hey
The pane bar (where there is the "close" "minimize"...) hides the option of "file" "edit" and half of "selection"...
I use Windows in the Hebrew language, maybe that's why I have a problem, but until the last update there was no problem!!
Thank you.
![image](https://user-images.githubusercontent.com/94039555/188575696-9c36bb42-343b-4256-9c72-fa8b5aa76a99.png)

**Comment by yume-chan** [comment] 2022-09-06 10:12
Duplicate of #159813

**Closed** 2022-09-06 10:14 UTC
