### ISSUE TITLE
html in php not highlight elements

### ISSUE THREAD

**Issue by sorinpopescu** [Microsoft/vscode#8609] opened 2016-07-01 10:08 UTC
- VSCode Version: 1.3.0-insider and 1.2.1
- OS Version: W8.1

Steps to Reproduce:

1. Open an php file that has both php and html and the file type is PHP - the html brackets highlight not workingas it should

You should add the option to select html brackets including in php file not only html
The right selection - http://prntscr.com/bnfaaa
The bad selection and that should be combined - http://prntscr.com/bnfaym

Thanks

**Comment by aeschli** [comment] 2016-07-19 14:45
duplicate of #2915

**Closed by aeschli** 2016-07-19 14:45 UTC
Labels: bug
