### ISSUE TITLE
Arrow keys completely stopped working in Code

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#24562] opened 2017-04-12 02:09 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.59|;

---

Steps to Reproduce:

I was typing, and all of a sudden my arrow keys no longer work inside VS Code.  They work in every other application, just not Code.  I've tried:

1) Signing off/in
2) rebooting the Linux machine
3) rebooting my Windows host machine (I'm using VS Code inside a Linux machine via Remote Desktop)
4) Pressing all the shift/control/etc keys on my keyboard
5) Scroll lock etc
6) Num lock
7) Checked that I don't have key mapping overrides

Still can't use the arrow keys at all.  This makes it nearly impossible to use.

**Comment by alexandrudima** [comment] 2017-04-12 08:16
Duplicate of #24107 -- the latest insiders release contains a fix, would you mind validating?

**Closed by alexandrudima** 2017-04-12 08:16 UTC

**Comment by StephenWeatherford** [comment] 2017-04-12 19:32
Sure, if you can tell me what/where to install from.

**Comment by alexandrudima** [comment] 2017-04-12 20:30
The Insiders release can be found at https://code.visualstudio.com/insiders

**Comment by StephenWeatherford** [comment] 2017-04-12 21:14
I get a window saying “Starting Visual Studio Code – Insiders”, but after several seconds it goes away and the app never shows.
