### ISSUE TITLE
Make possible to opt in individual extesions to see large files

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode#58291] opened 2018-09-09 12:52 UTC
Please make possible to opt in individual extensions to see files larger than the maximum allowed. I've created an extension which purpose is to filter large log files, but as it is stated in #3147, exensions can't see large files. As allowing all extensions to see all files may lead to performance degradation and huge memory usage, so I'm not proposing to increase this limit, but there should be an option for extension developers and end users to allow extensions to see these large files, maybe enable to do basic edit operations or have a readonly view of the content of the file.

**Comment by alexandrudima** [comment] 2018-09-12 12:47
Duplicate of #58290

@qcz The problem is easy. VS Code can (with some flags until we update to a newer v8 version) open huge files (>1GB). Depending on some factors, this results in a lot of memory usage and sometimes in OOM crashes. I think it would be great if we could remove the limit, but the limit is there to prevent a crash. I agree the limit should be configurable, as people might have varying hardware with varying amount of RAM, let's track that in #58290.

**Closed by alexandrudima** 2018-09-12 12:47 UTC
Labels: extensions
