### ISSUE TITLE
Extension missing - Live Share

### ISSUE THREAD

**Issue by Comradin** [microsoft/vscode#124552] opened 2021-05-25 05:06 UTC
Issue Type: <b>Bug</b>

I would like to install the Live Share extension for collaborative work with my colleagues. But the extension does not appear in the extensions overview.

Executing the "ext install MS-vsliveshare.vsliveshare" command as suggested on the homepage does not work. Most probably because the extension isn't listed.

Could there be some kind of filter active? Im on ArchLinux with i3 as window manager.

VS Code version: Code - OSS 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-16T15:21:33.370Z)
OS version: Linux x64 5.12.6-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|15.45GB (7.29GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.8
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
vscode-go-test-adapter|eth|0.1.5
go|gol|0.25.0
terraform|has|2.10.2
vscode-test-explorer|hbe|2.20.1
file-downloader|min|1.0.11
mindaro|min|1.0.120200919
vscode-aks-tools|ms-|0.0.7
vscode-kubernetes-tools|ms-|1.3.2
azure-account|ms-|0.8.9
vscode-yaml|red|0.19.2

</details>

**Comment by tamuratak** [comment] 2021-05-26 02:52
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Closed** 2021-06-08 17:11 UTC
