### ISSUE TITLE
[js] 'type aliases' can only be used in a .ts file

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#25737] opened 2017-05-01 15:31 UTC
- VSCode Version: 1.11
- OS Version: Linux Ubuntu 16.04

Even if I use this `"javascript.validate.enable": false` it says `[js] 'type aliases' can only be used in a .ts file`, but after re-opening file everything will be fine, no error. But it's annoying, because it happens not all the time, but sometimes...

Code:
```
// `Props` type aliases.
type Props = {
  ipAddress: string,
  os: string
};
```

Settings:
```
  // JavaScript validation.
  "javascript.validate.enable": false
```

**Comment by mjbvz** [comment] 2017-05-02 00:54
This sounds like a duplicate of #25219

If you have repo steps, please share them in that issue. I have not been able to reproduce this yet

**Closed by mjbvz** 2017-05-02 00:54 UTC
Labels: bug, javascript
