### ISSUE TITLE
All my snippets stopped to work after update to VSC 1.20.0

### ISSUE THREAD

**Issue by BFSzymanski** [Microsoft/vscode#43613] opened 2018-02-13 19:43 UTC
- VSCode Version: 1.20.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Update to VSC 1.20.0
2. Try to use any html snippet

Does this issue occur when all extensions are disabled?: Yes

Today I have updated VSC to 1.20.0 and suddenly all my html snippets stopped to work.

I have disabled all the extensions.

Here are my settings:

{
    // Controls if quick suggestions should show up while typing
    "editor.quickSuggestions": true,
    // Controls if suggestions should be accepted with "Enter" - in addition to "Tab". Helps to avoid ambiguity between inserting new lines and accepting suggestions.
    "editor.acceptSuggestionOnEnter": false,
    // Controls the delay in ms after which quick suggestions will show up.
    "editor.quickSuggestionsDelay": 10,
    // Enable word based suggestions
    "editor.wordBasedSuggestions": true,
    "editor.wordWrap": "on",
    // Controls whether the editor should render indent guides
    "editor.renderIndentGuides": true,
    "window.zoomLevel": 0,
    "editor.tabCompletion": true,
    "editor.snippetSuggestions": "top",
}

What can be a problem?

**Comment by shaneknysh** [comment] 2018-02-14 05:13
I am experiencing the same symptoms. When I use the "Insert Snippet" command from the command palette the snippets work but when I try using the prefix the snippets do not work.

**Comment by BFSzymanski** [comment] 2018-02-14 09:17
I have noticed it stopped to work with html snippets. Javascript snippets work fine.

Is it possible that this issue is related to the New Global Snippet?

**Comment by BFSzymanski** [comment] 2018-02-14 09:17
Btw, for me it doesn't work even with "Insert Snippet" command

**Comment by egamma** [comment] 2018-02-15 09:15
@BFSzymanski can you please provide more precise steps so that we can reproduce the issue.

- give an example of an HTML snippet that fails
- does the snippet come from an extension
- in what editing context does the snippet fail, please provide a screenshot

**Comment by JoeShep** [comment] 2018-02-23 20:03
Here is an example of what I am experiencing:
in `javascripr.json` I have 
``
  "console log": {
    "prefix": "con",
    "body": ["console.log('$1', $2);", "$0"]
  }
```
The snippet outputs the initial syntax properly, but tabbing from `$1` to `$2` no longer works. This is the case in all snippets with multiple cursor points.

**Comment by MattGoldwater** [comment] 2018-02-24 04:36
@JoeShep Did you just misspell javascript above or in your file?

My json.json snippet also isn't working for me.

**Comment by 199621** [comment] 2018-02-24 05:02
At 07:20 PM 5/30/2006 +0300, Vladimir Iliev wrote:
>hi,
>i've just upgraded my peak to the latest trunk, and when i tried to
>start my python, i've got this:
>
>'import site' failed; traceback:
>   File "c:\python24\lib\site.py", line 135, in addpackage
>     exec line
>   File "<string>", line 1
>     importing-1.9.1-py2.4.egg
>                   ^
>SyntaxError: invalid syntax
>
>ideas ?

Edit your C:\Python24\Lib\site-packages\easy-install.pth file, and change 
that line to read './importing-1.9.1-py2.4.egg' instead.  Then upgrade to 
the latest setuptools, either 0.7a1dev:

     ez_setup.py setuptools==dev

or 0.6b2dev:

     ez_setup.py setuptools==dev06

Sorry about the bug, it's a side effect of the package name.  I didn't 
discover it on my local machine because I was using "develop" mode, which 
uses an absolute path.  I've now fixed setuptools to always use 
'./whatever' for paths in .pth files, so this should not reoccur once you 
upgrade setuptools.

**Comment by 199621** [comment] 2018-02-24 05:02
At 07:20 PM 5/30/2006 +0300, Vladimir Iliev wrote:
>hi,
>i've just upgraded my peak to the latest trunk, and when i tried to
>start my python, i've got this:
>
>'import site' failed; traceback:
>   File "c:\python24\lib\site.py", line 135, in addpackage
>     exec line
>   File "<string>", line 1
>     importing-1.9.1-py2.4.egg
>                   ^
>SyntaxError: invalid syntax
>
>ideas ?

Edit your C:\Python24\Lib\site-packages\easy-install.pth file, and change 
that line to read './importing-1.9.1-py2.4.egg' instead.  Then upgrade to 
the latest setuptools, either 0.7a1dev:

     ez_setup.py setuptools==dev

or 0.6b2dev:

     ez_setup.py setuptools==dev06

Sorry about the bug, it's a side effect of the package name.  I didn't 
discover it on my local machine because I was using "develop" mode, which 
uses an absolute path.  I've now fixed setuptools to always use 
'./whatever' for paths in .pth files, so this should not reoccur once you 
upgrade setuptools.

**Comment by 199621** [comment] 2018-02-24 05:03
At 06:57 PM 5/30/2006 +0200, Ronald Oussoren wrote:

>On 30-mei-2006, at 18:20, Vladimir Iliev wrote:
>
>>hi,
>>i've just upgraded my peak to the latest trunk, and when i tried to
>>start my python, i've got this:
>>
>>'import site' failed; traceback:
>>Traceback (most recent call last):
>>   File "c:\python24\lib\site.py", line 397, in ?
>>     main()
>>   File "c:\python24\lib\site.py", line 382, in main
>>     paths_in_sys = addsitepackages(paths_in_sys)
>>   File "c:\python24\lib\site.py", line 203, in addsitepackages
>>     addsitedir(sitedir, known_paths)
>>   File "c:\python24\lib\site.py", line 166, in addsitedir
>>     addpackage(sitedir, name, known_paths)
>>   File "c:\python24\lib\site.py", line 135, in addpackage
>>     exec line
>>   File "<string>", line 1
>>     importing-1.9.1-py2.4.egg
>>                   ^
>>SyntaxError: invalid syntax
>
>That's a "feature" of site.py, if a line in a .pth file starts with
>"import" it is executed as a line of python code.

Yipes.  Looks like I need to fix this as a bug in setuptools.

**Comment by 199621** [comment] 2018-02-24 05:05
| EasyInstall | UserPreferences
-- | -- | --

**Comment by 199621** [comment] 2018-02-24 05:06
i dont no if this help but i think its how made the code

**Comment by jrieken** [comment] 2018-02-26 10:28
@BFSzymanski re https://github.com/Microsoft/vscode/issues/43613#issuecomment-365542493

Can you share the file and the snippet you are trying to insert? Is this a user-snippet or a built-in snippet?

**Closed** 2018-03-05 10:36 UTC
Labels: editor, editor-core, needs more info
