### ISSUE TITLE
`Go To Definition` several definitions per one instance issue

### ISSUE THREAD

**Issue by tehSLy** [Microsoft/vscode#52572] opened 2018-06-21 09:20 UTC
- VSCode Version: 1.24.1
- OS Version: Microsoft Windows [Version 10.0.17134.112]
- Libraries and Typescript - all have it's latest version and typings (also, tested with ts 2.9.1)
- node_modules excluded from both tsconfig.json & User Settings (files.exclude section)

Problem: Some instances of Styled Component or React.Component causes `Go To Definition` command to include libraries's index.d.ts file, which outputs several definitions per one entity:
![image](https://user-images.githubusercontent.com/25362218/41709058-f2753a54-754a-11e8-9c99-08aeacbf5421.png)

Steps to Reproduce:

1. Create React.Component or Styled Component instance
2. Go to Definition

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-06-21 16:53
Duplicate of https://github.com/Microsoft/TypeScript/issues/24861

You can workaround it by manually upgrading your workspace to typescript@next by following [these instructions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2018-06-21 16:53 UTC
Labels: typescript

**Comment by tehSLy** [comment] 2018-06-22 07:42
@mjbvz as I mentioned earlier, installed TypeScript has it's latest available version (3.0.0-dev.20180622 atm, which is typescript@next) and the issue still seem to be. Also, I 'd want to point out, that the definitions provided are not similar, it contained in different files, different types aswell (first is `interface`, second is `const` assignment)

**Comment by jeanmaried** [comment] 2018-06-23 13:43
I used typescript@2.2.1 and it finally went away!

**Comment by kayleighbray** [comment] 2018-06-29 18:06
@mjbvz I am also still seeing this issue despite upgrading my workspace to the latest "next" version more than a week after the intended fix was added.  I've not seen anyone say the fix worked for them but I also haven't seen anyone else but @tehSLy say it didn't work for them. Have even tried restarting my VSCode and still the little bugger won't go away
