### ISSUE TITLE
Test Disassembly view

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#129161] opened 2021-07-22 08:58 UTC
Refs: #124163, #125737

- [x] anyOS @lramos15
- [x] anyOS: @isidorn

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129161%0A%0A&assignees=weinand)

---

Thanks to the C++ team (especially @yuehuang010, @xisui-MSFT) we've received PR #125737 which adds the frequently requested **Disassembly View** to VS Code.

The **Disassembly View** supports a single instance only and can be opened from an editor of an active debug session if the corresponding debug extension supports it. The view shows the disassembled source of the editor's content and supports instruction stepping and instruction breakpoints.

Today two debug extensions support the **Disassembly View**: "C++" and "Mock Debug" (shown in the following recording).

![2021-07-22_10-31-24 (1)](https://user-images.githubusercontent.com/1898161/126980062-78b0cb2b-3ffd-4320-9f23-5d8866920a48.gif)

### C++ setup

- Use one of the following links to setup VS Code for C++ coding:
  - **Step by Step CMake for Linux**: https://code.visualstudio.com/docs/cpp/cmake-linux#_create-a-cmake-hello-world-project
  - **Walkthrough for Mac**: https://medium.com/@sam.romano18/visual-studio-code-setup-for-beginners-using-c-and-cmake-e92ab4f1fba1
  - **Walkthrough for Windows**: https://code.visualstudio.com/docs/cpp/config-msvc
- once you have the debugger running, have it hit a breakpoint
- right-Click in the source cpp and run the "Open Disassembly View" action from the context menu.

### Mock Debug Setup
- install latest "Mock Debug" extension from the Marketplace.
- create a Markdown file "test.md" and copy the contents of this [link](https://raw.githubusercontent.com/microsoft/vscode-mock-debug/main/sampleWorkspace/readme.md) into it.
- set a breakpoint in line 51
- from the editor's title area select the "Debug File" action from the drop down item:
   <img width="176" alt="2021-07-26_13-37-15" src="https://user-images.githubusercontent.com/1898161/126982743-8446915e-576c-454e-83ad-4ba8827379ef.png">
- once you hit the breakpoint, run the "Open Disassembly View" action from the markdown editor's context menu.

### What to test:
- Right Click menu in the editor should show "Open Disassembly View" only for supported debuggers in an active debug session.
- Disassembly View:
  - Scrolling up and down should be smooth and infinite, text content should expand
  - Current instruction marker (yellow left pointing arrow) should match with source code event while stepping.
  - When disassembly view is in focus, stepping In/out/back will step individual instructions. 
  - Switch back to source code resume normal stepping behavior.
  - Click on callstack should jump to that instruction address (if possible), when disassembly view is in focus.
- Add and Remove Instruction Breakpoints with the Disassembly View.
  - Added breakpoints should appear in the Breakpoint View List.
  - Remove instruction breakpoint or by breakpoint view list, both should update.
  - Click on address should open to breakpoint. 
  - Instruction breakpoints should survive debug sessions (but not VS Code restarts).

### Reference Links
- **CMake Reference** https://vector-of-bool.github.io/docs/vscode-cmake-tools/getting_started.html#cmake-tools-quick-start
- **VSCode C++ Extension** https://code.visualstudio.com/docs/languages/cpp
- **CMake Extension** https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools

**Comment by yuehuang010** [comment] 2021-07-22 10:05
### Use one of the following links to setup VSCode for C++ coding.
**Step by Step CMake for Linux**
https://code.visualstudio.com/docs/cpp/cmake-linux#_create-a-cmake-hello-world-project

**Walkthrough for Mac**
https://medium.com/@sam.romano18/visual-studio-code-setup-for-beginners-using-c-and-cmake-e92ab4f1fba1

**Walkthrough for Windows**
https://code.visualstudio.com/docs/cpp/config-msvc

### Reference Links
**CMake Reference**
https://vector-of-bool.github.io/docs/vscode-cmake-tools/getting_started.html#cmake-tools-quick-start

**VSCode C++ Extension** 
https://code.visualstudio.com/docs/languages/cpp

**CMake Extension** 
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools


Once you have the debugger running and have it hit a breakpoint hit.  Right-Click on the source cpp and the "Open Disassembly View".

**Comment by yuehuang010** [comment] 2021-07-22 10:26
### What to Test
1) Right Click menu should show "Open Disassembly View" for supported debuggers.  
1) Disassembly View
  a) Scrolling up and down should be smooth and infinite, text content should expand
  b) Current instruction marker (yellow left pointing arrow) should match with source code event while stepping.
  c) When disassembly view is in focus, stepping In/out/back will step individual instructions.
  d) Switch back to source code resume normal stepping behavior.
  d) Click on callstack should jump to that instruction address (if possible), when disassembly view is in focus.
1) Add and Remove Instruction Breakpoints with the Disassembly View.
  a) Added breakpoints should appear in the Breakpoint View List.
  b) Remove instruction breakpoint or by breakpoint view list, both should update.
  c) Click on address should open to breakpoint.

**Comment by weinand** [comment] 2021-07-22 10:38
@yuehuang010 please edit the initial comment from above with all information and delete your subsequent comments. We want to make life easier for testers.

**Comment by yuehuang010** [comment] 2021-07-22 18:25
> @yuehuang010 please edit the initial comment from above with all information and delete your subsequent comments. We want to make life easier for testers.

I don't have permission to edit.  @xisui-MSFT , do you have permission?

**Comment by xisui-MSFT** [comment] 2021-07-22 19:11
No, I don't have access either.

**Comment by weinand** [comment] 2021-07-22 20:29
@yuehuang010 I will try to fix permissions.

Do you have permissions to edit your own comments?
If yes, please create a new comment with all your test item information and let me know when I should move it into the initial comment.

**Comment by weinand** [comment] 2021-07-26 11:57
@yuehuang010, @xisui-MSFT please let me know if my editing has resulted in omissions or errors that needs to be fixed.

**Comment by isidorn** [comment] 2021-07-27 13:10
@yuehuang010, @xisui-MSFT I have created some issues and have pinged you all on those issues.
For fixing them feel free to create a PR per issue and ping me on the PR, that way the review process will be easier.
I think none of the issues are super critical, but we should address all of them in order to get this view to production quality.
Thanks a lot!

**Comment by isidorn** [comment] 2021-07-27 13:50
@yannickowow  @vadimcn @Trass3r feedback is very welcome if you got a chance to try the disassembly view out. Thanks a lot!

**Comment by yannickowow** [comment] 2021-07-27 14:13
Hi, first of all, thanks for your work! 
Unfortunately, I will not be able to test this feature using my extension since I finished my apprenticeship. These observations are done using C/C++ Extensions.

What I've encountered currently is:
- Instruction Breakpoints does not support `condition` / `hitCondition` updates
- Current line is not highlighted in green when you switch in a deeper call from the `callStack` (should be yellow in first and then green for others)
- We are missing a command to open this view from the `Command Palette` or directly from the `Call Stack` (if needed ?) [you figured it out and opened an issue]
- Disabled Breakpoint does not show as `disabled` in glyph margin from the Disassembly View
- Missing the ability to do a step by step (this might be a limitation to current C/C++)

Suggestions
- Ability to reorder columns
- New command to execute a `step instruction` ? If not, we might override the current stepping icon to describe as an instruction step
- For C/C++ Dev., Breakpoints should have a `instructionReference`, this will allow `Source Breakpoints` to be linked directly in the Assembly View.

**Comment by Trass3r** [comment] 2021-07-27 15:53
It doesn't work at all for me on a simple WSL2 hello world CMake project.
```json
<--   C (disassemble-14): {"command":"disassemble","arguments":{"memoryReference":"0x0000000000202118","offset":0,"instructionOffset":-50,"instructionCount":100,"resolveSymbols":true},"type":"request","seq":14}
--> R (disassemble-14): {"type":"response","request_seq":14,"success":false,"command":"disassemble","message":"Unable to disassemble. The method or operation is not implemented.","body":{},"seq":668}
```
So somewhere in `HandleDisassembleRequestAsync` a `NotImplementedException` gets thrown.

```
Version: 1.59.0-insider (user setup)
Commit: 955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7
Date: 2021-07-26T05:13:58.801Z
OS: Windows_NT x64 10.0.19043, WSL2
```

**Comment by isidorn** [comment] 2021-07-27 16:57
@yannickowow thanks a lot for your help, really appreciate it. Out of your findings:

> Instruction Breakpoints does not support condition / hitCondition updates

This is a fair feature request, but I would not add it yet. Too advanced IMHO and can be later added

> Current line is not highlighted in green when you switch in a deeper call from the callStack (should be yellow in first and then green for others)

Good catch. Created

> We are missing a command to open this view from the Command Palette or directly from the Call Stack (if needed ?) [you figured it out and opened an issue]

This is captured via https://github.com/microsoft/vscode/issues/129540

> Disabled Breakpoint does not show as disabled in glyph margin from the Disassembly View

Created https://github.com/microsoft/vscode/issues/129571

> Missing the ability to do a step by step (this might be a limitation to current C/C++)

Can you please create an issue in the C++ repo? This works for mock debug

> Remove all breakpoints does not remove Instruction Breakpoints

Created https://github.com/microsoft/vscode/issues/129572

> Instruction Breakpoints are toggled but seems to not work (C/C++ Extension logging remains empty after instruction breakpoint toggled)
I think this should be fixed as part of https://github.com/microsoft/vscode/issues/129571

@Trass3r that sounds like a C++ issue. Can you please open a new issue in this repo https://github.com/microsoft/vscode-cpptools

**Closed** 2021-07-27 17:46 UTC
Labels: debug, testplan-item

**Comment by Trass3r** [comment] 2021-07-27 18:16
> @Trass3r that sounds like a C++ issue. Can you please open a new issue in this repo https://github.com/microsoft/vscode-cpptools

It works with my `main` build so let's wait for the next release.
Just the performance is very bad when single stepping.

**Comment by yannickowow** [comment] 2021-07-27 19:04
I did some retries using disassembly and source and yeah, it toggles the `instruction granularity`, all fine 👍. 
It looks more like an issue with C/C++.

@Trass3r It looks like the issue is coming from C/C++ Extension. 
Here is an example, when I use a Step Into command from Disassembly View:
```
<--   C (stepIn-39): {"command":"stepIn","arguments":{"threadId":1,"granularity":"instruction"},"type":"request","seq":39}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (56131) <-1159-exec-step\r\n"},"seq":2633}
1: (56131) <-1159-exec-step
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (56146) ->1159^running\r\n"},"seq":2635}
1: (56146) ->1159^running
```
I think, in this case, that you should use `-exec-step-instruction` instead.

**Comment by Trass3r** [comment] 2021-07-27 19:16
Ah yes my step granularity PR has only recently been merged.

**Comment by yuehuang010** [comment] 2021-07-28 00:55
FYI.
- Condition/Disable BP will be added next milestone.
- The C++ Debugger for GDB or Linux (MIEngine) will needs some patching to support instruction Stepping and Breakpoint.  Using MSVC works.
- Stepping is based on which panel has focus.  If this is confusing, will consider adding some visual queues.
