### ISSUE TITLE
Add a command to prune non-existent workspaces / folders in Open Recent

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56592] opened 2018-08-16 17:04 UTC
Let's say I have opened 10 projects under `/project` from VS Code. One day I decided to rename `/project` to `/projects`. Now VS Code's Open Recent includes 10 dead links that'll always clog my search result.

**Comment by usernamehw** [comment] 2018-08-16 17:49
Duplicate of #49056

**Comment by octref** [comment] 2018-08-16 18:00
Related I guess, but this one is for projects.

**Comment by isidorn** [comment] 2018-08-17 07:37
fyi @bpasero

**Comment by bpasero** [comment] 2018-09-12 17:04
I think if we had such a command it should consistently across all history. Closing as duplicate of https://github.com/Microsoft/vscode/issues/49056

**Closed by bpasero** 2018-09-12 17:04 UTC
Labels: feature-request, workbench-history
