### ISSUE TITLE
No debug adapter found on termination of the debug session after update 1.42

### ISSUE THREAD

**Issue by ParOvBroadcom** [microsoft/vscode#90511] opened 2020-02-12 10:05 UTC
When trying to stop an already started debug session of DAP the session is stopped normally, also there are no errors reported in the debug console, but an error message is popping up in "no debug adapter found". This started directly after the VSCode updated to v. 1.42
![image](https://user-images.githubusercontent.com/54706061/74324234-00f1ed00-4d87-11ea-8d16-73a8091cf66e.png)

The language that is debugged in this occasion is COBOL.
No other extension are used at the same time except the one that we are implementing. They were disabled for the sake of clarity.

- VSCode Version: 1.42
- OS Version: Win 10

Steps to Reproduce:

1. Start a debug session
2. Stop the debug session

I should be able to see the debug session to finish with no errors.
The actual result was that, the debug session finished but with an unexpected error message

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-02-12 10:16
/needsMoreInfo including what language you are debugging, and what extensions you are using.

**Comment by ParOvBroadcom** [comment] 2020-02-12 10:37
I updated the description, hoping it will suffice.

**Comment by ParOvBroadcom** [comment] 2020-02-14 09:23
The problem appears when we are trying to terminate the debug session. We first use the "exited" method with the expected ExitedEventArguments and directly after that, the "terminated" method with the expected TerminatedEventArguments. The error comes from the terminated method. I repeat that the problem appeared directly when the version of VSCode was updated to 1.42. By the way this problem doesn't appear on Theia.

**Comment by weinand** [comment] 2020-02-14 10:08
@isidorn please investigate

**Comment by isidorn** [comment] 2020-02-14 10:12
Let's close as duplicate of https://github.com/microsoft/vscode/issues/89658
And continue the investigation there

**Closed by isidorn** 2020-02-14 10:12 UTC
Labels: debug
