### ISSUE TITLE
CPU usage when changing computer time

### ISSUE THREAD

**Issue by Xavier-Do** [Microsoft/vscode#51218] opened 2018-06-06 11:49 UTC
- VSCode Version: 1.23.1
- OS Version: Tested on windows 10/ Ubuntu 16

Steps to Reproduce:

1. Change computer time (10:43 AM to 00:43 AM in my case) while VSCode is open
2. Fry some eggs on your cpu. (or check cpu usage if you don't like eggs)

This issue was reproduced on two computer, one on windows 10
, the other on Ubuntu 16

Does this issue occur when all extensions are disabled?: 
Yes, on the second tries

**Comment by SaadQais** [comment] 2018-06-06 11:57
yes this issue also happened with me

**Comment by aeschli** [comment] 2018-06-06 12:53
duplicate of #50597

**Closed by aeschli** 2018-06-06 12:53 UTC
