### ISSUE TITLE
The vscode breakpoint panel cannot be fully expanded, and the vertical scroll bar is always displayed even with few breakpoints. Is this a bug?

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#123452] opened 2021-05-10 09:57 UTC
Issue Type: <b>Bug</b>

The vscode breakpoint panel cannot be fully expanded, and the vertical scroll bar is always displayed even with few breakpoints. Is this a bug?
![Snipaste_2021-05-07_10-56-18](https://user-images.githubusercontent.com/54253524/117641727-14257f80-b1b9-11eb-9e4f-0d14e8d6b966.png)

VS Code version: Code - Insiders 1.57.0-insider (54d33cf14cf6c0e86880b5b74a5a3628de42bce9, 2021-05-10T05:15:52.500Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (2.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by isidorn** [comment] 2021-05-10 12:36
@zhouxinghong this looks like a bug. However I can not reproduce it. Do you see this for every repository?
The view should grow until 9 breakpoints are shown and only then show the scrollbar.

Do you maybe have the setting?
`"workbench.list.horizontalScrolling": true,`

**Comment by zhouxinghong** [comment] 2021-05-11 03:16
Thank you for your kind help

**Comment by isidorn** [comment] 2021-05-12 09:48
This is working as designed. If you disable horizontal scroll you can not horizontal scroll.
If you enable horizontal scroll, we have to leave space to render it.

Thus closing as no plans to change

**Closed by isidorn** 2021-05-12 09:48 UTC
Labels: debug, needs more info
