### ISSUE TITLE
Feature request: Ability to open the integrated terminal drawer from the right side of editor

### ISSUE THREAD

**Issue by chris-schmitz** [Microsoft/vscode#25329] opened 2017-04-25 19:07 UTC
It would be fantastic if the drawer that the integrated terminal lives in could be opened from the right side of the editor window like a vertical split. 

I end up running into this situation from time to time:

![screen shot 2017-04-25 at 2 03 58 pm](https://cloud.githubusercontent.com/assets/2437424/25402943/1b64d88e-29c0-11e7-805e-2b27af483764.png)

I have ton of empty space on the right side of my editor, I'd like to have my editor and terminal open at the same time, and I have to scroll up and down in my editor to see everything or close the terminal. 

It's not a problem, def don't mind doing it, but it would be cool if I could change what side of the editor the drawer opens on. 

It would be _super great_ if that configuration could be bound to a hot key or updated from the command palette so that the direction could be changed on the fly. 

Thanks for considering the request!

**Comment by ajitid** [comment] 2017-04-25 22:11
need that!

**Comment by JustinPainter** [comment] 2017-05-05 17:22
A vertical terminal tray is a feature I've desired for a while and one that would remove my dependence on an external tool. 

> It would be super great if that configuration could be bound to a hot key or updated from the command palette so that the direction could be changed on the fly.

To add to this, it would be fantastic to have the option of binding separate hotkeys for each side. Say, `cmd+someKey` to open the bottom tray and `cmd+otherKey` to open a tray on the right. 

For my use case, it would be most useful if each tray held a different terminal session, rather than rendering the same session in different places. That said, I'll be pleased as punch either way; just the ability to open a vertical terminal will be extremely helpful.

**Comment by Tyriar** [comment] 2017-08-21 18:24
Duplicate of https://github.com/Microsoft/vscode/issues/2806

**Closed by Tyriar** 2017-08-21 18:24 UTC
Labels: feature-request, integrated-terminal, workbench
