### ISSUE TITLE
Notebooks and references odd behavior

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#99496] opened 2020-06-05 23:45 UTC
Version: 1.46.0-insider
Commit: b1ef2bf05f90dd0e6438782411ab84756f97d8f1
Date: 2020-06-05T12:27:56.662Z (10 hrs ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Have a notebook that provides references:
![image](https://user-images.githubusercontent.com/2644648/83929380-0dd88900-a748-11ea-8009-b0fb9c11c33b.png)

2. Hit F12 on the reference of the `fffff` function to "Go to definition"...

**Expected**

I move to the first `fffff` in that cell.

**Actual**

I'm moved to a new file that _just_ contains the code in the cell I hit F12 in:
![image](https://user-images.githubusercontent.com/2644648/83929440-39f40a00-a748-11ea-98e2-73a0c2b29e45.png)

This odd behavior also happens when I click "3 references":
![image](https://user-images.githubusercontent.com/2644648/83929524-7fb0d280-a748-11ea-8801-8930f1ce754c.png)

![image](https://user-images.githubusercontent.com/2644648/83929539-8c352b00-a748-11ea-9c94-888820dd6ba0.png)

I looked at the results from the language server:

```jsonc
// WHAT VS CODE SEND'S

[Trace - 4:27:59 PM] Sending request 'textDocument/definition - (28)'.
Params: {
    "textDocument": {
        "uri": "vscode-notebook-cell:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1#0000015"
    },
    "position": {
        "line": 6,
        "character": 3
    }
}

// WHAT WE REPLY

[Trace - 4:27:59 PM] Received response 'textDocument/definition - (28)' in 37ms.
Result: {
    "uri": "vscode-notebook-cell:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1#0000015",
    "range": {
        "start": {
            "line": 0,
            "character": 9
        },
        "end": {
            "line": 0,
            "character": 14
        }
    }
}
```

So that looks totally fine from my perspective which means how vscode handle's this result is likely the problem.

**Comment by TylerLeonhardt** [comment] 2020-06-05 23:46
cc @rebornix @jrieken

**Comment by jrieken** [comment] 2020-06-08 07:09
Hm, this looks all wrong. The peek window shouldn't show two entries with `notebook.ps1` but all references should appear as if they come from a single "file". 

Any change that the LSP-2-vscode layer changes those uris? Is this on a remote machine? Is there any chance I can reproduce this?

**Comment by TylerLeonhardt** [comment] 2020-06-08 16:01
@jrieken 

1. I would ignore the second entry of `notebook.ps1` this is likely coming from how we look at the filesystem for references in addition to the open file... it sees that the function is listed in a file called:
```
vscode-notebook-cell:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1#0000015
```
and then on the filesystem it finds:
```
/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1
```

I've got to polish that up so that for notebook files it doesn't count the same file twice... but this leads me to...

2. I'm not using the concat document so each cell is its own document from the language server side

3. I verified [our middleware code](https://github.com/PowerShell/vscode-powershell/blob/master/src/session.ts#L279-L320) which fixes vscode's handling of our result of the references codelens doesn't mess up any Uri's. (I don't really understand why we have to do this... but vscode don't show the references at all if we don't)

**Comment by jrieken** [comment] 2020-06-08 16:12
> I would ignore the second entry of notebook.ps1 this is likely coming from how we look at the filesystem for references in addition to the open file

Hm... So there is two set of results? One saying that the `fffff` symbol is defined in the notebook-cell and one saying it's defined in a file on disk, right? That would explain it - we always merge all results from all providers and I'd guess that the "first" entry ends up being the one on disk. Can you suppress the none-notebook language support and give it another try?

**Comment by TylerLeonhardt** [comment] 2020-06-08 16:45
@jrieken why is the presence of the results from the "search on disk" important?

**Comment by TylerLeonhardt** [comment] 2020-06-08 17:33
Same results if I suppress those items:

```jsonc
// WHAT VSCODE SENDS

[Trace - 10:14:32 AM] Sending request 'codeLens/resolve - (10)'.
Params: {
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 16,
            "character": 1
        }
    },
    "data": {
        "data": {
            "uri": "vscode-notebook-cell:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1#0000007",
            "providerId": "ReferencesCodeLensProvider"
        },
        "$$___handlerType___$$": "Microsoft.PowerShell.EditorServices.Handlers.PsesCodeLensHandlers",
        "$$___handlerKey___$$": "[powershell], [pwsh], [ps1], [psm1], [psd1], [**/*.ps*1]"
    }
}

// WHAT WE RESPOND

[Trace - 10:14:33 AM] Received response 'codeLens/resolve - (10)' in 957ms.
Result: {
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 16,
            "character": 1
        }
    },
    "command": {
        "title": "1 reference",
        "command": "editor.action.showReferences",
        "arguments": [
            "vscode-notebook-cell:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1#0000007",
            {
                "line": 0,
                "character": 0
            },
            [
                {
                    "uri": "vscode-notebook-cell:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1#0000007",
                    "range": {
                        "start": {
                            "line": 17,
                            "character": 0
                        },
                        "end": {
                            "line": 17,
                            "character": 16
                        }
                    }
                }
            ]
        ]
    },
    "data": {
        "uri": "vscode-notebook-cell:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1#0000007",
        "providerId": "ReferencesCodeLensProvider"
    }
}
```

![image](https://user-images.githubusercontent.com/2644648/84061804-6c357f80-a973-11ea-95c8-d316426a3b49.png)

**Comment by jrieken** [comment] 2020-06-18 16:12
Pushed a fix. @TylerLeonhardt please check with next Insiders. Also, to confirm my theory: in your package.json contribution for notebooks you use `"priority": "option"`, right? And this doesn't repo with `"default"`

**Comment by TylerLeonhardt** [comment] 2020-06-18 16:23
> Also, to confirm my theory: in your package.json contribution for notebooks you use "priority": "option", right? 

I have not tried this yet but I will give this a go as well.

**Comment by jrieken** [comment] 2020-06-24 07:31
Optimistically closing this

**Comment by TylerLeonhardt** [comment] 2020-06-25 23:34
@jrieken sorry I just got a chance to try this. I can still repro. Clicking on the codelens shows the same behavior.

![Screen-Cast-2020-06-25-at-42603](https://user-images.githubusercontent.com/2644648/85805618-a76cd800-b701-11ea-870e-d5bfc0e6b3f1.gif)

Is there something I can provide to be more helpful?

**Comment by jrieken** [comment] 2020-07-01 08:22
> Is there something I can provide to be more helpful?

Yeah, please extract a repo snippet. I have the snippet below and everything is working as expected

```ts
	vscode.languages.registerCodeLensProvider(
		{ scheme: 'vscode-notebook-cell', language: '*' },
		new class implements vscode.CodeLensProvider {
			provideCodeLenses(document: vscode.TextDocument, token: vscode.CancellationToken): vscode.ProviderResult<vscode.CodeLens[]> {
				let result: vscode.CodeLens[] = [];
				for (let line = 0; line < document.lineCount; line++) {
					let word = document.getWordRangeAtPosition(new vscode.Position(line, 0));
					if (word) {
						result.push(new vscode.CodeLens(word, {
							title: 'I am a lens',
							command: 'editor.action.showReferences',
							arguments: [document.uri, word.start, [new vscode.Location(document.uri, word)]]
						}))
					}
				}
				return result;
			}
		}
	)
```

**Comment by TylerLeonhardt** [comment] 2020-07-01 15:51
@jrieken I don't use that API because my result comes from a Language Server... does VS Code use it under the hood?

**Comment by jrieken** [comment] 2020-07-01 15:54
Yeah, the LSP client is using those APIs

**Comment by TylerLeonhardt** [comment] 2020-07-01 15:57
@jrieken did you happen to see the code on our end that gets run?:
https://github.com/PowerShell/vscode-powershell/blob/master/src/session.ts#L279-L320

It's fairly old code... and can use some polish... but maybe something calls out to you there. I'd love to understand why this is needed at all and why vscode can't handle the serialized `vscode.Command` coming from the LS

**Comment by jrieken** [comment] 2020-07-01 16:10
That code look about right. You are calling and API command (`editor.action.showReferences`) and that expects arguments of certain types, like `vscode.Range` or `vscode.Location`. That why you need this un- and re-boxing. LSP won't help you because it travels as command arguments and they aren't spec'd

**Comment by TylerLeonhardt** [comment] 2020-07-01 16:18
Here's what one of those CodeLen's look like after they're fixed.

![image](https://user-images.githubusercontent.com/2644648/86267473-9d246100-bb7b-11ea-9ee4-39824a5631f8.png)

**Comment by TylerLeonhardt** [comment] 2020-07-01 16:28
whoa this is weird, that random file that opens is readonly.

**Comment by TylerLeonhardt** [comment] 2020-07-01 16:30
![image](https://user-images.githubusercontent.com/2644648/86268728-76ffc080-bb7d-11ea-8960-4a2db2702341.png)

**Comment by jrieken** [comment] 2020-08-17 08:54
Please update if the original issue still exists/reproduces

**Closed** 2020-08-17 08:54 UTC
Labels: needs more info, notebook

**Comment by TylerLeonhardt** [comment] 2020-08-17 19:00
@jrieken I can still repro this with the same issue as above.

**Comment by jrieken** [comment] 2020-08-18 07:10
Funny, to much info above...  Can you please file a new clean issue, with your extension and your sample files.
