### ISSUE TITLE
Closing tag for style showing in intellisense when not needed

### ISSUE THREAD

**Issue by CraigWarford** [Microsoft/vscode#1145] opened 2015-12-09 18:23 UTC
While typing in the properties for a style block, it keeps showing the </style> closing tag as an option, when one is already included.  Having to avoid pressing "Enter" so that the tag is not inserted again:
![image](https://cloud.githubusercontent.com/assets/2633521/11694389/7877d734-9e6f-11e5-8ed0-63fc81108a7c.png)

**Comment by aeschli** [comment] 2015-12-11 15:55
@CraigWarford  This got already fixed for the last release (> 0.10.0). The closing tag for script no longer shows inside css. I also can't reproduce it.
On what build are you?
Do you have a code snippet?

**Closed by aeschli** 2015-12-11 15:55 UTC
Labels: bug, needs more info
