### ISSUE TITLE
Unable to scroll in the integrated terminal

### ISSUE THREAD

**Issue by mslourens** [Microsoft/vscode#8473] opened 2016-06-29 07:22 UTC
- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:07:11.483Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. toggle the terminal open (ctrl+`)
2. press enter a couple of times, until the text starts scrolling
--> no scrollbar appears

**Comment by Tyriar** [comment] 2016-06-29 18:48
Duplicate of https://github.com/Microsoft/vscode/issues/6602, see that issue for advice.

**Closed by Tyriar** 2016-06-29 18:48 UTC
Labels: bug, integrated-terminal
