### ISSUE TITLE
Cannot open devcontainer in WSL in Insider Preview 21354

### ISSUE THREAD

**Issue by mauve** [microsoft/vscode#120846] opened 2021-04-08 15:47 UTC
- VS Code Version: 1.55.0
- OS Version: Win10 Insider Preview 21354

Steps to Reproduce:

1. enter wsl: `wsl`
2. cd into repo with devcontainer json file: `cd ~/repos/rigg`
3. open code `code .`
4. when prompted to reopen in container press reopen in container
5. error:

```
docker: Error response from daemon: \\wsl.localhost\Ubuntu-20.04\home\mikae\repo
s\rigg%!(EXTRA string=is not a valid Windows path).
See 'docker run --help'.
```

Entire remoteContainers.log:

```
[2021-04-08T15:34:58.164Z] [PID 19272] [7 ms] Remote-Containers 0.166.1 in VS Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f).
[2021-04-08T15:34:58.607Z] [PID 19272] [450 ms] Start: Resolving Remote
[2021-04-08T15:34:58.608Z] [PID 19272] [451 ms] Setting up container for folder or workspace: \\wsl.localhost\Ubuntu-20.04\home\mikae\repos\rigg
[2021-04-08T15:34:58.611Z] [PID 19272] [454 ms] Start: Check Docker is running
[2021-04-08T15:34:58.611Z] [PID 19272] [454 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[2021-04-08T15:34:59.011Z] [PID 19272] [854 ms] Server API version: 1.41
[2021-04-08T15:34:59.150Z] [PID 19272] [993 ms] Start: Run: git rev-parse --show-cdup
[2021-04-08T15:34:59.257Z] [PID 19272] [1100 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl.localhost\Ubuntu-20.04\home\mikae\repos\rigg --filter label=vsch.quality=stable
[2021-04-08T15:34:59.638Z] [PID 19272] [1481 ms] Start: Run: docker events --format {{json .}} --filter event=start
[2021-04-08T15:34:59.688Z] [PID 19272] [1531 ms] Start: Starting container
[2021-04-08T15:34:59.689Z] [PID 19272] [1532 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=\\wsl.localhost\Ubuntu-20.04\home\mikae\repos\rigg,target=/workspaces/rigg,consistency=cached --mount source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl.localhost\Ubuntu-20.04\home\mikae\repos\rigg -l vsch.quality=stable -l vsch.remote.devPort=0 -e DISPLAY= -e PYTHONPATH=cur8/typelib --privileged=true --network=host --entrypoint /bin/sh REMOVED.azurecr.io/REMOVED/REMOVED:REMOVED -c echo Container started ; trap "exit 0" 15; while sleep 1 & wait $!; do :; done
[2021-04-08T15:34:59.863Z] [PID 19272] 
[2021-04-08T15:35:00.129Z] [PID 19272] docker: Error response from daemon: \\wsl.localhost\Ubuntu-20.04\home\mikae\repo
s\rigg%!(EXTRA string=is not a valid Windows path).
See 'docker run --help'.
[2021-04-08T15:35:00.164Z] [PID 19272] [2007 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl.localhost\Ubuntu-20.04\home\mikae\repos\rigg --filter label=vsch.quality=stable
[2021-04-08T15:35:00.600Z] [PID 19272] [2443 ms] Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=\\wsl.localhost\Ubuntu-20.04\home\mikae\repos\rigg,target=/workspaces/rigg,consistency=cached --mount source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl.localhost\Ubuntu-20.04\home\mikae\repos\rigg -l vsch.quality=stable -l vsch.remote.devPort=0 -e DISPLAY= -e PYTHONPATH=cur8/typelib --privileged=true --network=host --entrypoint /bin/sh REMOVED.azurecr.io/REMOVED/REMOVED:REMOVED -c echo Container started ; trap "exit 0" 15; while sleep 1 & wait $!; do :; done

```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by udovenkoav1981** [comment] 2021-04-09 10:42
I have same situation, i working on windows 10 dev channel, previous version 10.0.21343.1000 - working okay.
Yesterday  windows was updated to 10.0.21354.1  - and i can't run docker container via VSCode plugin Remote-Containers.

in previous version of windows log was:
[8 ms] Remote-Containers 0.166.1 in VS Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f).
[320 ms] Start: Resolving Remote
[321 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\**wsl$**\Ubuntu-20.04\home\user\ar13\trunk
but now:
[5 ms] Remote-Containers 0.166.1 in VS Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b).
[291 ms] Start: Resolving Remote
[293 ms] Setting up container for folder or workspace: \\**wsl.localhost**\Ubuntu-20.04\home\udovenko\ar13_trunk

all **wsl$** now looks like **wsl.localhost**  - this is broke docker run

**Comment by mauve** [comment] 2021-04-11 19:14
@aeschli @connor4312 ping?

**Comment by connor4312** [comment] 2021-04-11 19:46
Please do not ping

**Comment by mauve** [comment] 2021-04-12 20:05
Sorry for pinging, I was a bit frustrated because it has been broken for the last two insider previews and I spent a few hours trying to locate the code and couldn't find it.

Where is it code btw?

**Comment by chrmarti** [comment] 2021-04-12 20:54
Please give Remote-Containers 0.167.0 a try. That currently requires VS Code Insiders available here: https://code.visualstudio.com/insiders/

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4789.

**Closed by chrmarti** 2021-04-12 20:54 UTC
