### ISSUE TITLE
Resizing of Markdown preview performs very poorly

### ISSUE THREAD

**Issue by cfjedimaster** [microsoft/vscode#75140] opened 2019-06-08 16:13 UTC
Issue Type: <b>Bug</b>

I tried to resize the Markdown preview by clicking on the border and dragging. It refused to shrink in size, but would increase. I tried again and again and saw very laggy behavior. I also saw it "lock" in resizing mode, by that I mean I had stopped my mouse press but the panel would continue to resize as I moved my mouse. 

This video shows it in action. Note that the first ten seconds or so don't really show something. Also note the last 5 seconds or so I did NOT have my trackpad pressed. Also note, after I stopped recording and was using a small window in front VSC, the preview *still* moved with my mouse.

This video (as of 11:13AM CST) is still processing so if someone views it *immediately*, give it a minute. :)

https://youtu.be/Uqi3BIUUHjU

VS Code version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T05:19:15.188Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.38
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
simple-timer|bur|1.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
vscode-great-icons|emm|2.1.47
vscode-mysql|for|0.4.0
coldfusion|ili|1.0.1
search-node-modules|jas|1.3.0
vscode-sshfs|Kel|1.16.2
wordcounter|kir|1.9.0
dotenv|mik|1.0.1
vetur|oct|0.21.0
material-icon-theme|PKi|3.8.0
polacode|pnp|0.3.2
htmlescape-vscode-extension|ray|0.0.6
java|red|0.46.0
nativescript|Tel|0.10.1
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-maven|vsc|0.17.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-06-10 17:57
Duplicate of #75090

**Closed by mjbvz** 2019-06-10 17:57 UTC
Labels: electron-4.0.x-update
