### ISSUE TITLE
Can't rearrange tabs anymore

### ISSUE THREAD

**Issue by rdcastro86** [Microsoft/vscode#45303] opened 2018-03-08 14:34 UTC
Issue Type: <b>Bug</b>

Hi,
 I don't know if it accidentally changed a setting but I can no longer sort and order my open tabs. Is this a bug or an options somewhere?

Thanks,
Roy

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.886Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.67GB (2.66GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.1.0

</details>
Reproduces only with extensions

**Comment by bpasero** [comment] 2018-03-08 16:50
@rdcastro86 could it be that in your settings you have `"workbench.editor.showTabs": false` ?

**Comment by rdcastro86** [comment] 2018-03-09 08:51
Hi bpasero,

Nope, that setting is set to true. 

Thanks,
Roy

**Comment by bpasero** [comment] 2018-03-09 09:29
@rdcastro86 can you somehow record a video to show what you are doing?

**Comment by rdcastro86** [comment] 2018-03-09 22:09
Hi Ben,
[video.zip](https://github.com/Microsoft/vscode/files/1798586/video.zip)
I'm trying to click and hold on the tabs so I can move them, but they stay fixed.

Thanks,
Roy

**Comment by bpasero** [comment] 2018-03-10 07:45
@rdcastro86 crazy, I have no explanation why it does not work anymore. Does other drag and drop work, e.g. in the files explorer?

**Comment by davidonstate** [comment] 2018-03-13 13:38
I would like to confirm that I've noticed since updating to 1.21.0 (could have surfaced earlier but I just noticed today) I can no longer drag to rearrange editor tabs. Trying to drag results in tab selection but there's no feedback after that nor does dragging to another location change any order.

Thanks,
David.

**Comment by bpasero** [comment] 2018-03-13 14:04
@rdcastro86 @davidonstate 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by davidonstate** [comment] 2018-03-13 14:12
Hi @bpasero,

Nope, still unable to reorder tabs by dragging in the insider build.

Kind regards,
David.

**Comment by bpasero** [comment] 2018-03-13 16:08
@davidonstate are you on windows as well? Can you drag and drop in the file explorer or "open editors" view list?

**Comment by rdcastro86** [comment] 2018-03-14 15:10
@bpasero I am on windows as well and noticed that I cannot drag files on the file explorer. I am also having this issue with my firefox and explorer tabs. Tabs on chrome are working however.

**Comment by bpasero** [comment] 2018-03-14 15:30
@rdcastro86 could it be that you are running as a different user/administrator?

**Comment by rdcastro86** [comment] 2018-03-19 20:32
No, but after a windows update, it is now working. If it happens again i'll let ya'll know.

Thanks,
Roy

**Comment by bpasero** [comment] 2018-03-20 05:50
Ok, closing then as this seems Windows related.

**Closed by bpasero** 2018-03-20 05:50 UTC
Labels: needs more info, upstream, windows

**Comment by davidonstate** [comment] 2018-03-20 09:32
Just confirming that this issue now appears to be resolved when still running version 1.21.0.
