### ISSUE TITLE
Part of terminal contents disappears

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#218401] opened 2024-06-26 14:41 UTC
1. ctrl + in in the terminal
2. Submit a prompt
3. See that the terminal content shifts around and some of it disappears.

![Image](https://github.com/user-attachments/assets/1e708743-7ed0-472a-9c48-ca9e4a86f256)

**Comment by Tyriar** [comment] 2024-06-26 15:15
I cannot reproduce this on pwsh 5 or 7. What version of Windows are you using and do by chance have `terminal.integrated.windowsEnableConpty` set?

**Comment by alexr00** [comment] 2024-06-26 15:25
Windows 11: 10.0.22631 Build 22631
`terminal.integrated.windowsEnableConpty` is set to `true`
Also `"terminal.integrated.gpuAcceleration": "on"` in case that matters.

**Comment by meganrogge** [comment] 2024-12-09 18:28
This should now be fixed, thus closing. @alexr00 pls reopen if you can reproduce it.

**Closed by meganrogge** 2024-12-09 18:28 UTC
Labels: confirmation-pending, terminal-chat
