### ISSUE TITLE
Organize imports inserts copyright comments in the middle of imports

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46697] opened 2018-03-27 13:44 UTC
#46589

1. Open any typescripts file in vscode repo, for example BreakpointWidget.ts
2. Organize imports -> copyright coments in the middle of imports

![screen shot 2018-03-27 at 15 44 34](https://user-images.githubusercontent.com/1926584/37971246-c1e0ebd0-31d5-11e8-97ad-d9d8192dc7c7.png)

**Comment by mjbvz** [comment] 2018-03-27 17:43
Duplicate of https://github.com/Microsoft/TypeScript/issues/22731

**Closed by mjbvz** 2018-03-27 17:43 UTC
