### ISSUE TITLE
Remote Containers forwardPorts Broken in recent insiders build

### ISSUE THREAD

**Issue by aressler38** [microsoft/vscode#124736] opened 2021-05-27 05:34 UTC
Issue Type: <b>Bug</b>

After an update of vscode-insiders, my project will not open in a remote container.

1. Create an empty project.
2. Run the task called **Remote Containers: Add Development Container Configuration Files...** from the remote-containers extension.
3. Edit the devcontainer.json file and add forwardPorts.
4. Build the container. ... Error.

Log: 
``` 
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 36103

[6410 ms] Start: Run in container: echo 36103 >/home/vscode/.vscode-server-insiders/data/Machine/.devport
[6411 ms] 
[6411 ms] 
[6411 ms] Port forwarding for container port 36103 starts listening on local port.
[6412 ms] Port forwarding local port 36103 to container port 36103
[6427 ms] TypeError: Cannot read property 'port' of null
    at m.waitForReady (file:///C:/Users/alexander/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2844:1471)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async P.forward (file:///C:/Users/alexander/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:26348)
    at async S.$openTunnel (file:///C:/Users/alexander/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:35965)
```

VS Code version: Code - Insiders 1.57.0-insider (a18ea9c9ec25c59e599ba3c2eb668315546dd269, 2021-05-26T05:14:06.346Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4080)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (22.80GB free)|
|Process Argv|--crash-reporter-id 29b1ed8f-7ad1-487b-979b-4170434ba65d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.5
better-toml|bun|0.3.2
systemd-unit-file|coo|1.0.6
vscode-eslint|dba|2.1.20
EditorConfig|Edi|0.16.4
php-intellisense|fel|2.3.14
vscode-jasmine-test-adapter|hbe|1.7.1
vscode-test-explorer|hbe|2.20.1
rpm-spec|Lau|0.3.2
vscode-python-test-adapter|lit|0.6.8
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.22.0
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.0
vscode-azurevirtualmachines|ms-|0.4.0
vscode-bicep|ms-|0.3.539
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
vscode-dotnet-runtime|ms-|1.1.0
python|ms-|2021.6.864643163-dev
vscode-pylance|ms-|2021.5.5-pre.1
jupyter|ms-|2021.6.880641647
remote-containers|ms-|0.179.0
remote-wsl|ms-|0.56.3
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
cmake-tools|ms-|1.7.3
cpptools|ms-|1.3.1
powershell-preview|ms-|2021.5.0
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.1
debugger-for-chrome|msj|4.12.12
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
vscode-yaml|red|0.19.2
cmake|twx|0.0.17
azure-iot-toolkit|vsc|2.16.6
vim|vsc|1.20.3
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674

```

</details>

**Comment by aressler38** [comment] 2021-05-27 05:41
This seems to happen when I use the forwardPorts in the .devcontainer.json file.

```
	"forwardPorts": [
		4200,
		7075
	],
```

If I comment out that section, then it works. Something recently must have broke this because right after my vscode-insiders updated, my project started failing to open in the remote container.

**Comment by aressler38** [comment] 2021-05-27 05:53
Definitely it is related to forwardPorts. I created a new empty project and ran the task to generate devcontainer files. It's called *Remote Containers: Add Development Container Configuration Files...*

This fails with an empty project when I use forwardPorts. It doesn't seem related to specific ports.

![image](https://user-images.githubusercontent.com/2053500/119773040-14e33480-be8e-11eb-8ad5-d5c22870da8c.png)

**Comment by chrmarti** [comment] 2021-05-31 12:16
Should be fixed in latest VS Code Insiders. (Duplicate of https://github.com/microsoft/vscode-remote-release/issues/5102)

**Closed by chrmarti** 2021-05-31 12:16 UTC
