### ISSUE TITLE
Opening VS Code starts with powershell instead of default selcted

### ISSUE THREAD

**Issue by Skriptach** [microsoft/vscode#132878] opened 2021-09-10 18:10 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.60.0 (system setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Switch default terminal profile to bash
2. Close VS Code
3. Open VS code

Expected result: Bash terminal is active

What happens instead: Powershell is active

Maybe relative to #125898

**Comment by IllusionMH** [comment] 2021-09-10 18:13
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Closed** 2021-09-10 18:14 UTC
Labels: *duplicate
