### ISSUE TITLE
Whitespace added after Commenting and Uncommenting in HTML, CSS

### ISSUE THREAD

**Issue by sarthak7gupta** [Microsoft/vscode#30729] opened 2017-07-14 19:00 UTC
- VSCode Version: 10.14.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. I have only tried it HTML and CSS. Probably for other file types, too.
2. Comment a line by CMD+/, then uncomment using the same key combination.
3. You will notice a white space added to start and end of the part commented.
4. Checked with disabling all extensions, too.

**Comment by cleidigh** [comment] 2017-07-16 20:14
@rebornix 
Duplicate of #30656 
Fixed with PR #30818 
All Languages

**Closed** 2017-07-18 00:02 UTC
Labels: editor, editor-core
