### ISSUE TITLE
Some Ctrl+Alt+ shortcuts no longer work when AltGr+ is pressed

### ISSUE THREAD

**Issue by Gooseman** [microsoft/vscode#68787] opened 2019-02-15 14:53 UTC
I have several shortcuts defined using Ctrl+Alt+<letter>.  The ones that have a vowel no longer execute the shortcut, but instead insert an accented character.  This started with the latest update -

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

The keyboard shortcuts that no longer work
{
        "key": "ctrl+alt+e",
        "command": "cursorLineEnd",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+a",
        "command": "cursorLineStart",
        "when": "editorTextFocus"
    },

I've tried this with extensions disabled and in insiders and the result is the same.  When I try to add the shortcut using the "Define Keybinding" button, when I type the 'e', the Ctrl and Alt disappear from the editor and only the 'e' is left.  The language set in the OS has not changed, nor has the keyboard setup - standard UK keyboard.

How do I restore the shortcuts and remove the accented characters?

Thanks
Craig

**Comment by kieferrm** [comment] 2019-02-15 18:54
@Gooseman This happens on the right <kbd>Alt</kbd> key? Or on both?

**Comment by Gooseman** [comment] 2019-02-16 10:55
On both.

**Comment by richard-scott** [comment] 2019-02-17 09:19
I have the same problem with the PlatformIO extension. It uses CTRL+ALT+u to upload code to an Arduino. On my old laptop this works (outside of the App I get ú when I press those keys, but in the app, the shortcut takes precedence.

On a fresh install of Windows 10 Pro, with a fresh install of VS Code, and the PlatformIO extension I get ú when I press the shortcut keys.

On the OS that works, I have v10.0.17134, and the one that doesn't work has v10.0.17763. All other apsects of VS Code are exactly the same as in the original post

**Comment by leandro86** [comment] 2019-02-17 14:55
I also have the same problem: the right CTRL+ALT keys doesn't work for a shortcut. It works if I press the left CTRL+ALT keys.

**Comment by Gooseman** [comment] 2019-02-17 18:20
Leandro - not quite the same problem.  I get the same behaviour regardless
of which Ctrl and Alt keys I use.  Also, for combinations that don't result
in accented characters in other applications, I get the configured shortcut
executing in VS Code.  It's only some Ctrl+Alt shortcuts that don't work.

**Comment by richard-scott** [comment] 2019-02-19 20:18
It seems to be the shortcuts that would have inputted a unicode character that now fail.
Such as:

```
CTRL+ALT+o = ó
CTRL+ALT+a = á
CTRL+ALT+o = é
CTRL+ALT+u = ú
```
However, CTRL+ALT+u is a short cut for "upload" with the PlatformIO extension.

On a different (older) Windows 10 install with VS Code, the shortcut works, but on a fresh install -completed in the last couple of days - the shortcut doesn't work, and the unicode character overrides it.

**Comment by Gooseman** [comment] 2019-03-08 16:54
With the latest release, 1.32.0, Ctrl+alt+<vowel> works, but
Ctrl+alt+shift+<vowel> (which was working) is now broken...

**Comment by richard-scott** [comment] 2019-03-12 12:26
I've had to write a new windows keyboard map to get round this ;-(

On [here](https://superuser.com/questions/592970/can-i-make-ctrlalt-not-act-like-altgr-on-windows) it suggests this procedure to create a new keyboard layout.

1. Download [The Microsoft Keyboard Layout Creator](http://msdn.microsoft.com/en-us/goglobal/bb964665.aspx). It is a simple tool that lets you modify your keyboard layout. ([Download link](http://www.microsoft.com/en-us/download/confirmation.aspx?id=22339))

2. Open to tool and File -> Load Existing Keyboard and choose your keyboard layout.
3. Select File -> Save source as and give it a new name.
4. Tick the Alt+Ctrl (AltGr). You might want to select File -> Save as Image to make a note of the original assignments.
5. Remove all assigned keys, by clicking them, deleting the symbol, and click OK. Do not clear any dead keys! (The grey ones). Check for all modifiers i.e. AltGr, Ctrl, Alt, or none!
6. Go to Project -> Properties and give it a decent name and description.
7. Save it: File -> Save Source File so you can edit it later
8. Export setup: Project -> Build DLL and Setup Package

Then we need to apply this new keyboard layout.
1. Find the exported setup files in you Documents folder, and double click setup.exe. This will install your new keyboard layout.
2. Open the input setting by going to Control Panel -> Change keyboards and other input methods -> Change keyboards.
3. Click Add select you own keyboard and make it default.

**Comment by entozoon** [comment] 2019-10-05 20:50
Intricate solution @richard-scott, but perhaps a little bit of overkill..
For example, with the Platformio issue, you could just re-assign the keyboard shortcut to `ctrl-alt-y` or whatever.
Publishing a plugin with a shortcut always comes with the risk of OS incompatibility for one daft reason or another

**Comment by brunorodriguesdecarvalho** [comment] 2019-10-10 15:06
My problem was related to run MySQL queries inside VSCode, by pressing ctrl + alt + E. My solution was to change the keyboard shortcut from ctrl + alt + E to ctrl + alt + backspace, which is easier to type. =] 

I followed the instructions on this video (image): https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif

**Comment by CanisLupus** [comment] 2020-01-05 20:10
This issue is still happening as of today (i.e. using shortcuts like `Ctrl+Alt+A`or `Ctrl+Alt+E` inserts `á` and `é`). I'm using the "United Kingdom Extended keyboard" layout in Windows.

What is strange is that I have the same exact layout in a different computer, and this problem does NOT happen there. Is this something that can be fixed/broken by a Windows update? I currently have no clue about what could fix this.

VSCode info;
```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by nishnat-rishi** [comment] 2020-01-31 05:45
This doesn't seem to be a VS Code issue. Rather, Windows seems to have made it a bit easier to input regional Unicode characters. Any sort of 'extended' or 'international' version of the keyboard will reproduce this issue with specific characters. Just change keyboard layout to 'US' or 'United Kingdom' to at least have access to non-vowel shortcuts.

Steps to fix consonants:

- Go to 'Advanced keyboard settings'. Ensure the drop-down menu option under 'Override for default input method' is set to 'Use language list (Recommended)'.
- Go to 'Language settings', Make sure under 'Preferred languages', first option is set to 'English (United States)'. or 'English (United Kingdom)' Click on it. Click on 'Options'.
- Under 'Keyboards', remove whatever keyboard is there, and add 'US' or 'United Kingdom' keyboard instead.

At least the consonants should be fixed now.

**Comment by Gooseman** [comment] 2020-01-31 10:06
Nishnat-Rishi - I haven't seen anyone complaining about problems with
consonants, only vowels.

The problem is not  related to the keyboard layout.  I don't switch my
keyboard layout and sometimes when I use a key combination that includes
Ctrl, Alt and a vowel I don't get the shortcut I've configured, but rather
an accented vowel.  Sometimes I get the keyboard shortcut.  I can go for
hours or days having no problems and then I'll have hours or days during
which all my keyboard shortcuts that include Ctrl, Alt and a vowel give me
the accented vowel instead.  This behaviour is also happening across
keyboards as well as computers.  I'm not changing keyboard layouts while
I'm working and my computers use the same UK keyboard layout.  The idea of
doing things like changing keyboard layouts was brought up when I first
reported this problem.  Changing keyboard layouts and languages didn't work
then and it doesn't work now.  There's also the fact that VS Code is the
only application in which this happens.  All my shortcuts in Visual Studio
work as expected all the time.  All my shortcuts in IntelliJ work as
expected all the time.  All my shortcuts in VIM work as expected all the
time.

The consonants work anyway in general since Ctrl + Alt + consonant doesn't
generally give an accented consonant, it'll just run the shortcut if one is
configured.

**Comment by moluoyu** [comment] 2020-03-16 16:12
it's 2020 3.7 .it has the same question.

`Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-40-generic snap`

**Comment by Lucide** [comment] 2020-03-18 12:53
Other programs, like CLion, are able to discern between `Ctrl`+`Alt` and `AltGr`, VSCode should do the same.
Being unable to reach shortcuts because of the keyboard layout is nonsense, and changing it isn't really a solution. The layout is there to _write_, a text editor is exactly where I would want to use it.

**Comment by colski** [comment] 2020-06-03 17:01
Just to add this problem is biting me too - almost certain it is caused by a windows update / rebuild... I am now on version 1909, build 18363.836)

thx.

**Comment by ank1traj** [comment] 2020-06-04 05:36
> This issue is still happening as of today (i.e. using shortcuts like `Ctrl+Alt+A`or `Ctrl+Alt+E` inserts `á` and `é`). I'm using the "United Kingdom Extended keyboard" layout in Windows.
> 
> What is strange is that I have the same exact layout in a different computer, and this problem does NOT happen there. Is this something that can be fixed/broken by a Windows update? I currently have no clue about what could fix this.
> 
> VSCode info;
> 
> ```
> Version: 1.41.1 (user setup)
> Commit: 26076a4de974ead31f97692a0d32f90d735645c0
> Date: 2019-12-18T14:58:56.166Z
> Electron: 6.1.5
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Windows_NT x64 10.0.18362
> ```

Just change your keyboard to US layout. It works for me.

**Comment by Gooseman** [comment] 2020-06-04 06:46
" Just change your keyboard to US layout. It works for me."

Ah, yes, the old, "Do the wrong thing to sort out a problem that shouldn't
exist."  I mean, it's not like anyone should expect software to work, after
all.  I'm going to try that with my employer.  "Just type in the correct
numbers, that works for me when the calculated value is incorrect."

**Comment by colski** [comment] 2020-06-05 20:20
> Just change your keyboard to US layout. It works for me.

well that's a work around, thanks for mentioning it.

**Comment by atifraza** [comment] 2020-07-27 21:47
> Nishnat-Rishi - I haven't seen anyone complaining about problems with consonants, only vowels. The problem is not related to the keyboard layout. I don't switch my keyboard layout and sometimes when I use a key combination that includes Ctrl, Alt and a vowel I don't get the shortcut I've configured, but rather an accented vowel.


I can confirm this problem with consonants. For example, on a US International keyboard `Ctrl+K` `Ctrl+Alt+S` does not work if the right `Alt` key is used.

**Comment by ViniDalvino** [comment] 2020-08-29 15:24
I amhaving the issue aswell. I tried what @nishnat-rishi [said here](https://github.com/microsoft/vscode/issues/68787#issuecomment-580591615) but it didn't worked out.

**Comment by kebbleytea** [comment] 2020-09-04 14:16
> I amhaving the issue aswell. I tried what @nishnat-rishi [said here](https://github.com/microsoft/vscode/issues/68787#issuecomment-580591615) but it didn't worked out.

This is the same for me, I have also tried this. I am unable to bind CTRL + ALT + UP and the same with CTRL + ALT + DOWN.
It works with numpad up & down keys though.

Would be nice to see a solution to this!

**Comment by adam-stamand** [comment] 2020-09-05 02:16
> > I amhaving the issue aswell. I tried what @nishnat-rishi [said here](https://github.com/microsoft/vscode/issues/68787#issuecomment-580591615) but it didn't worked out.
> 
> This is the same for me, I have also tried this. I am unable to bind CTRL + ALT + UP and the same with CTRL + ALT + DOWN.
> It works with numpad up & down keys though.
> 
> Would be nice to see a solution to this!
> 
> Although I'm not entirely sure if my issue is related, might not be 🤔. I can bind UP + DOWN separately, but not when using CTRL + ALT

I'm having the exact same issue as @kebbleytea. I can bind UP and DOWN separately, but I can't bind then when using CTRL+ALT.

**Comment by ViniDalvino** [comment] 2020-09-05 02:44
I noticed the issue also happened in visual studio. I think it's not related to vs code. It somehow got fixed after the latest windows update.

**Comment by hugoblanc** [comment] 2020-09-11 15:01
> > > I amhaving the issue aswell. I tried what @nishnat-rishi [said here](https://github.com/microsoft/vscode/issues/68787#issuecomment-580591615) but it didn't worked out.
> > 
> > 
> > This is the same for me, I have also tried this. I am unable to bind CTRL + ALT + UP and the same with CTRL + ALT + DOWN.
> > It works with numpad up & down keys though.
> > Would be nice to see a solution to this!
> > Although I'm not entirely sure if my issue is related, might not be 🤔. I can bind UP + DOWN separately, but not when using CTRL + ALT
> 
> I'm having the exact same issue as @kebbleytea. I can bind UP and DOWN separately, but I can't bind then when using CTRL+ALT.

Facing the same problem, but LEFT and RIGHT are also affected

**Comment by yedhrab** [comment] 2020-09-11 19:19
Intel Graphic Commands Center use ✲ Ctrl ⎇ Alt commands, try to disable or toggle these commands. Check [here](https://stackoverflow.com/a/63853013/9770490)

**Comment by mukaschultze** [comment] 2020-09-12 19:29
I'm having the same problem, this has something to do with the input method. Currently, I'm using a customized version of `US-Intl`, changing to `US` fixes the problem.

**Comment by carct** [comment] 2020-09-14 17:10
> Intel Graphic Commands Center uses ✲ Ctrl ⎇ Alt commands, try to disable or toggle these commands. Check [here](https://stackoverflow.com/a/63853013/9770490)

💥 although i had those options already OFF, after i have turned them ON and then back OFF, issue was solved in VSCode without restarting it even :)) 💥

**Comment by hugoblanc** [comment] 2020-09-22 07:29
> > Intel Graphic Commands Center uses ✲ Ctrl ⎇ Alt commands, try to disable or toggle these commands. Check [here](https://stackoverflow.com/a/63853013/9770490)
> 
> 💥 although i had those options already OFF, after i have turned them ON and then back OFF, issue was solved in VSCode without restarting it even :)) 💥

You both saved my day !! Thanks a lot

**Comment by ethzero** [comment] 2020-10-12 18:16
> > > Intel Graphic Commands Center uses ✲ Ctrl ⎇ Alt commands, try to disable or toggle these commands. Check [here](https://stackoverflow.com/a/63853013/9770490)
> > 
> > 
> > 💥 although i had those options already OFF, after i have turned them ON and then back OFF, issue was solved in VSCode without restarting it even :)) 💥
> 
> You both saved my day !! Thanks a lot

👍; Found out this myself then found this thread to report then found people had the same solution.
*sigh* Thanks Intel 💩

**Comment by PheelaV** [comment] 2020-10-22 11:05
> > Intel Graphic Commands Center uses ✲ Ctrl ⎇ Alt commands, try to disable or toggle these commands. Check [here](https://stackoverflow.com/a/63853013/9770490)
> 
> 💥 although i had those options already OFF, after i have turned them ON and then back OFF, issue was solved in VSCode without restarting it even :)) 💥

This is such a major fup. Same thing helped me.

**Comment by clshortfuse** [comment] 2020-10-22 15:16
Came here to report the same. I got a new Dell laptop and `Ctrl`+`Alt` refused to work. I figured it might be a BIOS thing, but yep, it's Intel. Turning "Enable System HotKeys" on and then off fixed it.

![image](https://user-images.githubusercontent.com/9271155/96892763-f7fa0500-1457-11eb-9687-8624a0461006.png)

**Comment by colski** [comment] 2021-01-03 12:15
I updated today. The work around for this issue with the keyboard settings discussed above no longer works for me. I found that by adding a vscode setting to my system the problem has gone away.
The setting I used was {"keyboard.dispatch":"keyCode"}.

in the end I added a settings.json file to my windows user profile (in c:\users\<username>\AppData\Roaming\Code\) restarted vscode and the shortcuts are working again.

btw: no intel GCC on my system, but I do run logitech options and I wonder if that related.

**Comment by Lucide** [comment] 2021-01-23 17:44
I don't know if the bug label got removed because of the igcc workaround, but I have no "system hotkey" option to disable, in fact, I've got no igcc at all! But still experiencing the issue like I was a year ago. I understand that we are too few to suggest a systematic VSCode bug, but the issue is still here nonetheless. All I can do is edit some markdown readmes from time to time, as every shortcut behind `ctrl`+`alt` is inaccessible.
VSCode is the first *text editor* I've seen that has troubles with ..keyboard input.

**Comment by hhendrikk** [comment] 2021-04-03 06:25
Turn on the NumLock.
Worked for me!

**Comment by Gooseman** [comment] 2021-04-05 19:32
I don't have a keyboard with a number pad, so I have no numlock key.

**Comment by KaushalDokania** [comment] 2021-05-18 09:08
As suggested by previous comment from @Gooseman https://github.com/microsoft/vscode/issues/68787#issuecomment-638638842

I just had to change the Language to English(US). I was using English(India) earlier.
![image](https://user-images.githubusercontent.com/11616866/118624304-abf12200-b7e6-11eb-925f-0ebcabb1c25b.png)

**Comment by ank1traj** [comment] 2021-07-23 03:40
> As suggested by @ankit1raj comment [#68787 (comment)](https://github.com/microsoft/vscode/issues/68787#issuecomment-638613225)
> 
> I just had to change the Language to English(US). I was using English(India) earlier.
> ![image](https://user-images.githubusercontent.com/11616866/118624304-abf12200-b7e6-11eb-925f-0ebcabb1c25b.png)

Glad to know that my suggestion worked for you!!

**Comment by atorr0** [comment] 2021-10-15 20:04
Integrated Terminal + Cygwin (or Git Bash) exhibits a similar problem:
* Cygwin/MinTTY: CTRL + (up key) send `^[[1;5A` . VSCode too :+1:
* Cygwin/MinTTY: ALT + (up key) send `^[[1;3A` . VSCode `^[[1;5A` :-1:
* Cygwin/MinTTY: CTRL + (left key) send `^[[1;5D` . VSCode too :+1:
* Cygwin/MinTTY: ALT + (left key) send `^[[1;3D` . VSCode `^[[1;5D` :-1:

So it seems that ALT key is interpreted as CTRL key.
Enabled extension:

Extension | Author (truncated) | Version
-- | -- | --
increment-selection | alb | 0.2.0
insertnumbers | Asu | 0.9.1
gitlens | eam | 11.6.1
vscode-highlight | fab | 1.5.1
vscode-lombok | Gab | 1.0.1
rest-client | hum | 0.24.5
azure-pipelines | ms- | 1.191.0
vscode-apimanagement | ms- | 1.0.3
vscode-azureresourcegroups | ms- | 0.4.0
vscode-azurestorage | ms- | 0.12.1
vscode-azurevirtualmachines | ms- | 0.4.1
vscode-cosmosdb | ms- | 0.18.1
vscode-docker | ms- | 1.17.0
vscode-dotnet-runtime | ms- | 1.3.0
vscode-aks-tools | ms- | 0.0.9
vscode-kubernetes-tools | ms- | 1.3.3
remote-ssh | ms- | 0.65.8
remote-ssh-edit | ms- | 0.65.8
azure-account | ms- | 0.9.9
azurecli | ms- | 0.5.0
azurerm-vscode-tools | msa | 0.15.4
material-icon-theme | PKi | 4.10.0
highlight-counter | ram | 1.6.0
fabric8-analytics | red | 0.3.4
java | red | 0.82.0
vscode-commons | red | 0.0.6
vscode-xml | red | 0.18.0
vscode-yaml | red | 0.23.0
vscodeintellicode | Vis | 1.2.14
vscode-java-debug | vsc | 0.36.0
vscode-java-dependency | vsc | 0.18.8
vscode-java-pack | vsc | 0.18.5
vscode-java-test | vsc | 0.32.0
vscode-maven | vsc | 0.34.0
markdown-all-in-one | yzh | 3.4.0

**Comment by LouDnl** [comment] 2022-04-06 11:43
Had this exact issue today all of a sudden, everything worked fine yesterday. I assigned the key combination `ctrl + alt + shift + n` to the shortcut to open a new window with a copy of the workspace and this and some Calva shortcuts didn't work didn't work anymore today. Changing my keyboard layout to `US Keyboard` instead of `United-States International keyboard` solved it.
Still an issue that it worked fine yesterday on the `United-States International keyboard` layout and today it doesn't.

**Comment by alexdima** [comment] 2022-04-07 21:25
@LouDnl The problem on macOS is tracked at https://github.com/microsoft/vscode/issues/41024

**Comment by erikvullings** [comment] 2022-06-16 07:45
> Turn on the NumLock. Worked for me!
As @hhendrikk suggested, I also needed to turn the numeric keylock on to make it work. However, as my keyboard doesn't have a numeric keypad (same as @Gooseman ), it wasn't so simple to turn it on. I basically followed this [video](https://www.youtube.com/watch?v=riCpODXlSWM), so go to WINDOWS Settings | Ease of Access | Keyboard menu item | Use the On-Screen Keyboard.
![image](https://user-images.githubusercontent.com/3140667/174018969-09bf4830-a6e2-4dfe-87db-86c65cc5698e.png)

When the On-Screen keyboard is open, go to Options | Turn on numeric key pad | Num Lock.
![image](https://user-images.githubusercontent.com/3140667/174018833-a6ae7f96-6cf7-48b7-895f-6f6bb0f695e0.png)

That's all...

**Comment by Mardenf** [comment] 2022-07-24 00:59
> **[erikvullings](/erikvullings) ** commented [on 16 Jun](#issuecomment-1157343210)

Thanks a lot!!! It Worked for me!!!!

**Comment by LouDnl** [comment] 2022-09-30 06:17
It is caused by the keyboard layout language. I fixed it for myself by making sure I use 'US English' layout when working with Calva in VSCode.
If and when they do not work it's 95% of the time caused by using the wrong keyboard layout.
For some reason, which I cannot explain, it doesn't always stop working when on another layout 🤷🏻‍♂️

**Comment by alexdima** [comment] 2022-12-09 11:26
Trying to summarise what I know on this topic:
* this behavior depends on the keyboard layout.
* under some keyboard layouts, like the US-International keyboard layout, the right <kbd>Alt</kbd> key becomes <kbd>AltGr</kbd>.
* [Wikipedia does a great job explaining what is the purpose of this new modifier](https://en.wikipedia.org/wiki/AltGr_key).
* <kbd>AltGr</kbd> is a completely separate modifier key than <kbd>Alt</kbd>.
* for example, when using the US-International keyboard layout:
  * <kbd>Alt</kbd>+<kbd>c</kbd> (i.e. <kbd>AltLeft</kbd> + <kbd>c</kbd>) produces no text
  * <kbd>AltGr</kbd>+<kbd>c</kbd> (i.e. <kbd>AltRight</kbd> + <kbd>c</kbd>) produces ©.
* we are built with Electron, which is built with Chromium, and we dispatch keybindings based on the keyboard events we receive from Chromium. Under Windows we use the `.keyCode`, `.ctrlKey`, `.shiftKey`, `.altKey` properties on the keydown event to dispatch our keybindings.
* When pressing <kbd>AltGr</kbd>+<kbd>c</kbd>, Chromium would send an event for `C`, with the modifiers `.ctrlKey: true` and `.altKey: true`.
* This is what allowed that in past versions of VS Code, a keybinding for `Ctrl+Alt+E` could be triggered by pressing:
  * `AltGr+E` (i.e. <kbd>AltRight</kbd> + <kbd>E</kbd>)
  * `Ctrl+AltGr+E` (i.e. <kbd>Ctrl</kbd> + <kbd>AltRight</kbd> + <kbd>E</kbd>)
  * `Ctrl+Alt+E`  (i.e. <kbd>Ctrl</kbd> + <kbd>AltLeft</kbd> + <kbd>E</kbd>)
* Chromium [has changed this in version 67](https://chromestatus.com/feature/5059438092222464) and now no longer set `e.ctrlKey` and `e.altKey` to true when pressing <kbd>AltGr</kbd>.
* This Chromium change reached VS Code with the 1.31 update [documented here](https://code.visualstudio.com/updates/v1_31#_nodejs-update).

**Closed** 2022-12-09 15:06 UTC
Labels: feature-request, keybindings, windows

**Comment by rzhao271** [comment] 2023-01-25 22:27
I verified that the keyboard shortcuts in https://github.com/microsoft/vscode/issues/68787#issue-410804317 work again for the US-International layout after `keyboard.mapAltGrToCtrlAlt` was enabled.
