### ISSUE TITLE
Undo delete of a folder in explorer only restores folder, not files

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140100] opened 2022-01-04 16:19 UTC
Steps to Reproduce:

1. have 1 folder with 1 file
2. right click -> delete the folder
3. hit undo

=> 🐛  only the folder is restored, not the file

//cc @isidorn @jrieken

**Comment by isidorn** [comment] 2022-01-04 17:28
I think this was a known limitation, and there might already be an issue for this.

**Comment by JacksonKearl** [comment] 2022-01-04 17:38
duplicate of #111022

**Closed by JacksonKearl** 2022-01-04 17:38 UTC
