### ISSUE TITLE
Visual Studio Malfunctioning

### ISSUE THREAD

**Issue by Adeyemi-Timilehin** [microsoft/vscode#109993] opened 2020-11-05 02:09 UTC
Issue Type: <b>Bug</b>

All the functionality of the visual studio are not responding. It was  display error   
messages which 've being trying to fix. Some of the  errors are;
1. net::ERR_TIMED_OUT
2.Error while starting Settings Sync: No authentication provider 'microsoft' is currently registered.
3. Extension error

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.67GB free)|
|Process Argv|--crash-reporter-id ba835180-c7b5-445f-819e-fa804e5f983e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
simple-react-snippets|bur|1.2.3
vscode-eslint|dba|2.1.13
javascript-ejs-support|Dig|1.3.1
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|5.7.1
file-icons|fil|1.0.26
auto-close-tag|for|0.5.9
todo-tree|Gru|0.0.183
live-html-previewer|hdg|0.3.0
stylelint-plus|hex|0.52.10
vscode-placeholder-images|Jak|0.1.0
vs-media-player|mkl|3.1.0
vscode-edge-devtools|ms-|1.1.1
remote-wsl|ms-|0.50.1
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.3046
color-highlight|nau|2.3.0
vscode-react-snippet|Nic|0.0.5
open-html-in-browser|pea|2.1.3
itunes-vscode|Psy|0.16.5
LiveServer|rit|5.6.1
music-time|sof|2.0.21
swdc-vscode|sof|2.3.14
html-preview-vscode|tht|0.2.5
emmet-live|yse|1.0.0

</details>

**Comment by Adeyemi-Timilehin** [comment] 2020-11-05 02:10
Please help me try and resolve this issue

**Comment by RMacfarlane** [comment] 2020-11-05 16:27
Closing as a duplicate of https://github.com/microsoft/vscode/issues/108319, this will be fixed in the next release. In the mean time, you can use the [Insider's version](https://code.visualstudio.com/insiders/) of VS Code

**Closed by RMacfarlane** 2020-11-05 16:27 UTC
