### ISSUE TITLE
Closing a markdown preview by keyboard shortcut also closes the main file

### ISSUE THREAD

**Issue by Instagit** [microsoft/vscode#83231] opened 2019-10-24 14:37 UTC
**Version:**
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.11-050211-generic
```

**Steps to Reproduce:**

1. Create a markdown file and set the language mode to markdown
2. Open a preview (CTRL+SHIFT+V)
3. Close the preview with CTRL+W

**Result:** Both files are closed.
**Expected behaviour:** The main file should stay open.

**Does this issue occur when all extensions are disabled?:** Yes

This is either a plain bug or inconsistent behaviour, because closing the preview by clicking does exactly what it's supposed to (only close the preview and leave the main file open for editing).

There have been several similar issues (all closed), but none of them describe this exact problem.

**Comment by mjbvz** [comment] 2019-10-25 23:49
Duplicate of #82670

**Closed by mjbvz** 2019-10-25 23:49 UTC
Labels: bug, webview
