### ISSUE TITLE
Formatting nor working properly

### ISSUE THREAD

**Issue by okansarica** [Microsoft/vscode#18638] opened 2017-01-17 07:59 UTC
![1](https://cloud.githubusercontent.com/assets/1814720/22012152/5cca910a-dc9b-11e6-8eda-636c4581803b.png)
![2](https://cloud.githubusercontent.com/assets/1814720/22012153/5ccef7cc-dc9b-11e6-8774-327a04f66658.png)

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|tsimporter|pmneo|1.2.13|
|seti-icons|qinjia|0.1.3|

---

Steps to Reproduce:

1.After formatting a document it doesnt look good am i doing wrong something
i deleted all extensions about formatting code but the result is the same

i have attached two images 
1:before format
2:after format

![1](https://cloud.githubusercontent.com/assets/1814720/22012161/66c55956-dc9b-11e6-90ea-796a49e792d0.png)
![2](https://cloud.githubusercontent.com/assets/1814720/22012162/66c5a97e-dc9b-11e6-8252-17ea957e8f74.png)

2.

**Comment by aeschli** [comment] 2017-01-23 15:41
duplicate of #17849

**Closed by aeschli** 2017-01-23 15:41 UTC
