### ISSUE TITLE
Vscode is unable to operate.

### ISSUE THREAD

**Issue by marco0305** [Microsoft/vscode#40406] opened 2017-12-18 02:32 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
django-html|bib|1.2.0
MagicPython|mag|1.0.12
python|ms-|0.9.0
vscode-icons|rob|7.19.0
bootstrap4-vscode|the|3.0.0
html-preview-vscode|tht|0.1.1
python|tht|0.2.3

---

Steps to Reproduce:

When the open vscode is complete, only the black screen and menu, and can not open and browse the file Explorer. 
1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment] 2017-12-18 03:53
Most likely this is the same as #40329 with root cause of #40339

 Can you check if you have `editor.tokenColorCustomizations` set to `null` in your settings file (you can find it at ~/Library/Application Support/Code/User/settings.json). If yes, then set it to `{}` instead and then try opening VS Code.

**Comment by marco0305** [comment] 2017-12-18 06:11
Thank you for your reply!
I have tried to use your method, but it does not work.
Because of the trouble I've tried to clear all settings and reinstall vscode.
So the setting in all setting.json is empty.

Later I reference [# 40329](https://github.com/Microsoft/vscode/issues/40329) and try the "code --disable-gpu" command.
Vscode can be opened normally, thank you very much for your information!
Thank you.

**Comment by bpasero** [comment] 2017-12-18 06:32
ok closing as duplicate of https://github.com/Microsoft/vscode/issues/40009

**Closed by bpasero** 2017-12-18 06:32 UTC
Labels: freeze-slow-crash, needs more info

**Comment by marco0305** [comment] 2017-12-19 03:09
Today, I opened vscode, this bug occurrent again. so I tried to command "code --disable-gpu", but does not work.
Finally, deleted the folder ("~\username\appData\Roaming\code\*.*") and commanded "code --disable-gpu". It worked.
So this bug is not fixed accuractly at this moment.

**Comment by bpasero** [comment] 2017-12-19 05:38
@marco0305 after you deleted the folder, does it also work when you run without "--disable-gpu"?

**Comment by marco0305** [comment] 2017-12-19 05:57
Yes, must run "--disable-gpu"!!!
When I deleted the folder, it does not work.

**Comment by bpasero** [comment] 2017-12-19 06:06
@marco0305 in that folder do you have any settings.json file configured in the .vscode folder?

**Comment by marco0305** [comment] 2017-12-19 06:17
NO! It's default folder when vscode running. After using I must redo the same method to start vscode.
