### ISSUE TITLE
Scrollbar and text selection no longer working after reseting powershell integrated terminal

### ISSUE THREAD

**Issue by BeardInASuit** [Microsoft/vscode#31913] opened 2017-08-02 13:12 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment] 2017-08-02 15:57
Duplicate of https://github.com/Microsoft/vscode/issues/20505

**Closed by Tyriar** 2017-08-02 15:57 UTC
Labels: integrated-terminal
