### ISSUE TITLE
Malposition after layout change

### ISSUE THREAD

**Issue by Fan-iX** [microsoft/vscode#174273] opened 2023-02-11 05:46 UTC
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1000421627
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: win11 professional 22H2 22623.1255
-   Python and/or Anaconda version: Python 3.9.10, without conda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote - SSH, Local
-   Remote - SSH version: v0.96.0

## Actual behaviour

Malposition of the jupyter content

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a interactive window (or open a notebook) in a editor group, with an empty group on its side
![step1](https://user-images.githubusercontent.com/61686936/218242182-14f8cb93-ad78-4f71-8e59-3c88a619dc16.png)

2. Split the jupyter editor down
![step2](https://user-images.githubusercontent.com/61686936/218242189-ac82a390-5c25-4e3a-820c-4ea4e48dfce1.png)

3. Close the empty group
![step3](https://user-images.githubusercontent.com/61686936/218242187-12dd195a-466d-4ba0-8790-122414aa75fb.png)

4. See malposition of the jupyter content
![step4](https://user-images.githubusercontent.com/61686936/218242185-0012a0c1-538f-497b-b17b-480ccb4dd15f.png)

Also seen if the editor group near by have editor tabs(for example, closing an existing editor).

Seems having something todo with the vertical split layout, since split the editor right or left do not cause the malposition

**Comment by rebornix** [comment] 2023-02-13 18:41
I'm wondering if it's related to our grid view position optimization.

**Comment by mjbvz** [comment] 2023-02-20 16:18
@rebornix I only merged that optimization back in this iteration (#172466) so that's unlikely to be the cause of this particular issue

**Closed** 2023-02-27 22:51 UTC
Labels: bug, notebook-layout
