### ISSUE TITLE
JSDoc suggestions do not appear if autoClosingBrackets is disabled

### ISSUE THREAD

**Issue by josh18** [microsoft/vscode#94084] opened 2020-03-31 23:12 UTC
Issue Type: <b>Bug</b>

1. Set setting `editor.autoClosingBrackets: "never"`
2. Attempt to generate a JSDoc comment by typing `/**`

**Expected**
JSDoc comment is suggested

**Actual**
No suggestions

I'm not sure if this is by design but it would be nice to get JSDoc suggestions even if you have autoClosingBrackets disabled. I believe there is already another setting if you want to disable JSDoc suggestions.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-42-generic snap

**Comment by mjbvz** [comment] 2020-04-09 23:40
Duplicate of #82814

**Closed by mjbvz** 2020-04-09 23:40 UTC
