### ISSUE TITLE
Can not write commit message on git panel

### ISSUE THREAD

**Issue by gholami-mohammad** [microsoft/vscode#135204] opened 2021-10-16 06:50 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.61.1
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:15:35.620Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-generic

- OS Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

Steps to Reproduce:

I have a workspace that contains multiple folders. Each folder has git.

When I try to write a commit on the git panel, after typing some characters, the pointer jumps on the next git commit text area that belongs to another git folder.

This problem started occurring when I updated my Vscode 2 days ago. Last night I updated to 1.61.1 but the problem still exists.

https://user-images.githubusercontent.com/13257674/137577703-acc7f92e-9242-4d8a-a81f-d5fbaf17eeae.mp4

**Comment by gjsjohnmurray** [comment] 2021-10-16 07:22
Maybe a duplicate of #135143

Does setting `"scm.showActionButton": false` make any difference?

**Comment by joywaves** [comment] 2021-10-16 15:31
Having the same issue on my VSC. Sorry, do I have to disable showActionButton btn on workspace level or repo level?
in my case having more than 15 repos in my workspace, it's drives me so mad...

**Comment by kitos9112** [comment] 2021-10-17 13:26
@gjsjohnmurray Thanks for pointing to that WA - I've been facing this issue for quite a long time now. !I considered opening an issue today, however, there's #135143 which I'm monitoring too

**Closed** 2021-10-18 16:18 UTC
