### ISSUE TITLE
Windows drive letter case different between ${workspaceFolder} and integratedTerminal

### ISSUE THREAD

**Issue by farrago** [Microsoft/vscode#42159] opened 2018-01-25 16:38 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

# Steps to Reproduce:

1. Create trivial js file to log `__dirname` and the first argument to your program. e.g.
    ```javascript
    console.log('__dirname', __dirname);
    console.log('${workspaceFolder}', process.argv[2]);
    ```
2. "File" -> "Open Folder", then navigate to and select the directory with the above file in it.
2. Create a default node debug config in launch.json
3. Add `"args": ["${workspaceFolder}"]` to pass it as the first param (which will be logged above
4. Add `"console": "integratedTerminal"` to use integrated terminal.  This gives a launch.json of:
    ```javascript
        {
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Program",
                "program": "${workspaceFolder}/test.js",
                "args": [
                    "${workspaceFolder}"
                ],
                "console": "integratedTerminal"
            }
        ]
    }
    ```

---
# Actual Output:
```
D:\test>cd d:\test && node --inspect-brk=15398 test.js d:\test
Debugger listening on ws://127.0.0.1:15398/5d5674d0-9a73-4e7a-bb58-658d7ca0d24f
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
__dirname D:\test
${workspaceFolder} d:\test
Waiting for the debugger to disconnect...

D:\test>
```

Notes:
1. The path in the terminal window uses a capital "D".
2. The internal path appears to use a lower case "d".  This can be seen in both the logged value of ${workspaceFolder}, and in the command line that launches the debug session.
3. If using, "Command Prompt" console, it is possible to manually change the current directory to a lowercase drive letter to make them match, but that is not the default.

---
# Expected Output:

The drive letter case used by the integrated terminal and that used by the integrated terminal should match.  

This is important because node considers files with a different case to be different files during `require()`.  Passing paths to a node script that are built using ${workspaceFolder} and using them to require files causes different casing between otherwise identical filepaths.

Given that:
1. The file explorer with which the folder was selected in "File" -> "Open Folder" showed upper case "D"
2. AFAIK, upper case is the canonical form in Windows (as enforced in Explorer, Powershell, etc.) 
3. I believe it is impossible to make Powershell (the default integratedTerminal) use lower case drive letters.

Then **VSCode should internally use the uppercase form**.

---
# Notes

- This DOES NOT happen using the `"internalConsole"`.  The drive letter is lowercase in both cases.
- This DOES happen with both "Powershell" and "Command Prompt" consoles.
- This may be related to #12448

**Comment by isidorn** [comment] 2018-01-25 16:46
@bpasero duplicate of #12488 ?
Since the workspace folder path should not enter lowercase in our sistem in the first place. When I am replacing in the configuration resovler service I simply take what the context service gives me

**Comment by bpasero** [comment] 2018-01-25 17:06
@isidorn do you mean https://github.com/Microsoft/vscode/issues/12448 ?

**Comment by bpasero** [comment] 2018-01-25 17:08
@isidorn as far as I know we do some normalization of drive letters in the URI class (@jrieken can correct me if I am wrong), so I would assume that at least as long as URIs are being used, we are consistent everywhere.

It is true however that we have a helper method [`normalizeDriveLetter`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/labels.ts#L93) that we use whenever a URI path is being displayed in the UI because indeed on Windows the default seems to be uppercase.

**Comment by isidorn** [comment] 2018-01-26 10:17
@bpasero yes I meant that issue number (just edited my mistake)

**Comment by jrieken** [comment] 2018-01-26 13:58
> I know we do some normalization of drive letters in the URI class (@jrieken can correct me if I am wrong)

We lower-case it for some historic reason... I am not brave enough to change that TBH

**Comment by bpasero** [comment] 2018-01-26 14:10
Yeah it could break quite a bit of things. @isidorn maybe at your point you should just normalize the drive letter then? It does not seem to be an issue in any other places so far except this one.

**Closed** 2018-01-29 15:50 UTC
Labels: bug, config
