### ISSUE TITLE
completeFunctionCalls does not work properly with commit characters

### ISSUE THREAD

**Issue by SamVerschueren** [microsoft/vscode#19820] opened 2017-02-03 09:56 UTC
It looks like the autocompletion is broken. At least, it's pretty annoying.

- VSCode Version: VSCode 1.9.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. Create a new javascript file
2. Start typing `console.log` and press the <kbd>(</kbd> key. It will autocomplete to the following.

```js
console.log((message), optionalParams)
```

I also don't want the autocompletion kicking in because it's really annoying. I don't want to always remove the `, optionalParams` manually. It works counter productive in my opinion.

**Comment by bpasero** [comment] 2017-02-03 10:20
Not for me:

![image](https://cloud.githubusercontent.com/assets/900690/22587627/b4aab2dc-ea02-11e6-9b0a-d31942e186e9.png)

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by SamVerschueren** [comment] 2017-02-03 10:24
Still failing here. Another use case where it is failing.

![sinon](https://cloud.githubusercontent.com/assets/1913805/22587749/44bea22a-ea03-11e6-9bb7-bb10b0c4de15.gif)

I removed all my custom keybindings as well, no dice.

**Comment by jrieken** [comment] 2017-02-03 10:40
@SamVerschueren We change how suggestions can be accepted when typing certain commit characters, like `(` which should accept a proposal and insert that character. Other samples are `.` or `;`. Because they are very context sensitive (function, statement, member) the extension can now define that.

I assume this is in TypeScript - fyi @mjbvz 

If this is getting to annoying you can turn this off with the `acceptSuggestionOnCommitCharacter` setting

**Comment by jrieken** [comment] 2017-02-03 10:41
Also, are you using the TypeScript setting to insert function completions with parens and params filled in?

**Comment by SamVerschueren** [comment] 2017-02-03 11:52
@jrieken Aha, I found out that I had added this rule to my `settings.json`

```
"typescript.useCodeSnippetsOnMethodSuggest": true
```

I turned it off and things seem to work fine now. This happened both in JavaScript and TypeScript.

**Comment by jrieken** [comment] 2017-02-03 12:06
That could impact this but I have issues reproducing this. @mjbvz I am not able to use `useCodeSnippetsOnMethodSuggest` anymore. I see some guard have been added, but the simple test (`console.log`) fails for me...

**Comment by SamVerschueren** [comment] 2017-02-03 12:12
@jrieken Are you using macOS as well? Not sure if I can run a command to show more details of my system that might be of interest.

**Comment by jrieken** [comment] 2017-02-03 14:02
Ok, I was able to reproduce. This is what happens step by step:

* use `"typescript.useCodeSnippetsOnMethodSuggest": true`
* type `console.log`
* see `log` being suggested, type `(`
* the suggestion inserts `log(message, optionalParams)` *and* put the cursor around `message` because the suggestion is a snippet
* because `(` was a commit character we still insert it at the start of the selection
* because `(` is also an electric character we also insert `)` at the end of the selection
* :bug: `log` has been completed to `log((message), optionalParams)`

@mjbvz We shouldn't make `(` a commit character when the suggestion is also being inserted as method/function/ctor snippet.

**Comment by SamVerschueren** [comment] 2017-02-03 14:09
Wow, thanks for looking into this @jrieken! Much appreciated!

**Comment by mjbvz** [comment] 2017-02-03 22:56
@jrieken Similar behavior exists in 1.8 when you type a `.` to complete a method signature. You'd end up with something like `console.log(.)`

I think we need to make `useCodeSnippetsOnMethodSuggest` or the completion items smarter in these cases. Or we could rethink the entire flow so that only `(` completes a method signature when `useCodeSnippetsOnMethodSuggest` is enabled. The current behavior of `useCodeSnippetsOnMethodSuggest` just feels broken in  many instances today.

**Comment by SamVerschueren** [comment] 2017-02-03 23:04
@mjbvz I added this rule to my `keybindings.json` which prevents the `.` from doing that.

```json
{
		"key": ".",
		"command": "-acceptSelectedSuggestion",
		"when": "editorTextFocus && suggestWidgetVisible && suggestionSupportsAcceptOnKey && editorLangId == 'typescript'"
	}
```

**Comment by jrieken** [comment] 2017-02-06 15:30
Yes, we should turn off commit characters when completing a method/function/ctor with its invocation.  Agreed, this was already bad in 1.8 but now it's worst because we added `(` as commit character and only since the latest api tweak you can actual have instance-based commit characters. 

I would still push this the Jan recovery release because it is a regression that makes the feature unusable, tho arguable no one uses that feature anyways

**Comment by SamVerschueren** [comment] 2017-02-06 18:06
Thanks @jrieken ! If there's anything I can help you with like testing the nightly build, let me know!

**Comment by atiqorin** [comment] 2017-02-07 23:33
Autocomplete for java is also not working. For java, (,[,{,'," none of these auto complete anymore in MacOS Sierra 10.12.3. On my windows 10 After I closed folder, and restarted VSCode it worked once. Now it doesn't work at all, even after closing folder and restarting.

**Comment by mjbvz** [comment] 2019-11-25 23:52
Removing milestone. Will do this whenever #42544 is completed

**Comment by mjbvz** [comment] 2022-12-05 17:34
Moving to https://github.com/microsoft/TypeScript/issues/51758

**Closed by mjbvz** 2022-12-05 17:34 UTC
Labels: bug, typescript, suggest
