### ISSUE TITLE
Spelling errors (diagnostics) prevent debugging

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#29730] opened 2017-06-28 09:19 UTC
When debugging, if there are errors (diagnostics), vscode will say

![image](https://user-images.githubusercontent.com/7588612/27628964-476add9e-5c23-11e7-83a2-3340dea4e1f9.png)

The problem is that, most of the spell check extensions will show spell errors as diagnostics in the Problems panel

![image](https://user-images.githubusercontent.com/7588612/27629298-78436a98-5c24-11e7-80bb-95e89a0eb97f.png)

But these 'spelling errors' are not 'build errors'. It's not good to have one more `debug anyway` click just because those 'spelling errors'.

**Comment by isidorn** [comment] 2017-06-28 09:20
Duplicate of an already open issue - you can search for it in our issues. Thanks

**Closed by isidorn** 2017-06-28 09:20 UTC
Labels: debug

**Comment by neilsustc** [comment] 2017-06-28 09:30
Okay. I find it #8493. Thanks
