### ISSUE TITLE
I think that this tools should show in activity bar

### ISSUE THREAD

**Issue by roadhub** [Microsoft/vscode#48314] opened 2018-04-21 05:51 UTC
- VSCode Version: Version 1.22.2 
- OS Version: macOs

Steps to Reproduce:
![fda21287-ba4e-45b1-88fb-f1832f0ad514](https://user-images.githubusercontent.com/18000037/39081015-2b4c80bc-456c-11e8-966e-7310d24adec0.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roadhub** [comment] 2018-04-21 05:56
The space between `setting` and  `extension` is wasted, but in fact , it is useful for same tool

**Comment by usernamehw** [comment] 2018-04-21 06:57
Duplicate of #43645 ?

**Comment by ramya-rao-a** [comment] 2018-04-21 08:40
Thanks @usernamehw 
@roadhub This is covered in #43645

**Closed** 2018-04-21 08:40 UTC
Labels: *duplicate
