### ISSUE TITLE
VS Code becomes unresponsive during every Angular CLI build

### ISSUE THREAD

**Issue by ryanbuening** [Microsoft/vscode#42325] opened 2018-01-29 14:32 UTC
- VSCode Version: 1.19.3
- OS Version: Windows 10 version 1709

Steps to Reproduce:

1. Open my Angular 5.2.2 CLI 1.6.6 project.
2. Start Without Debugging
3. Towards the end of the build, VS Code becomes unresponsive.

Does this issue occur when all extensions are disabled?: **Yes**

My JavaScript CPU Profile can be downloaded here: https://drive.google.com/file/d/1VIRYl19Z3GZt4itI6wzQY9Izm4z-9GkU/view?usp=sharing

**Comment by isidorn** [comment] 2018-01-29 15:44
@ryanbuening can you also reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/

If yes can you share your Angular project so we can try to repro on our machine.

**Comment by ryanbuening** [comment] 2018-01-29 17:00
@isidorn I can't start my project without debugging with the Insiders build because of this issue: https://github.com/Microsoft/vscode/issues/42198

However, Debug > Start Debugging doesn't cause Visual Studio to become unresponsive the Insiders build or VS Code 1.19.3 either. It is only when running *Without* Debugging.

Can I get your email so I can privately send you my project?

**Comment by isidorn** [comment] 2018-01-30 09:34
@ryanbuening that issue is fixed in latest insiders. So try in latest insiders
Here is my email so you can share your repository with repro steps in case you can repro on insiders
inikolic@microsoft.com

**Comment by ryanbuening** [comment] 2018-01-30 13:19
@isidorn I updated to the latest Insiders build and I am unable to reproduce my issue when I run without debugging. Was something fixed with the Insiders build? Would completely uninstalling and reinstalling VS Code 1.19.3 have any effect in resolving this?

**Comment by isidorn** [comment] 2018-01-30 13:25
@ryanbuening lot's of things changed in latest insiders since we did not have a full stable release in 2 months.
A new stable will be out in 10 days. Let me know if you still see this then and I will reopen.

Thanks

**Closed by isidorn** 2018-01-30 13:25 UTC
Labels: needs more info
