### ISSUE TITLE
Slow startup opening a large workspace over the network

### ISSUE THREAD

**Issue by davidsantos-br** [Microsoft/vscode#70045] opened 2019-03-08 11:32 UTC
Issue Type: <b>Performance Issue</b>

My workspace directory sits on a server in the network, which I access using a mapped network drive. It has about 470,000 files (~36GB) pertaining to about 500 websites. Each website is contained within a folder in the workspace top level, e.g. “T:\vm_sites\example.com", "T:\vm_sites\otherwebsite.org", and so on.

I open the parent folder (“T:\vm_sites”) instead of just the folder of the website I'll be working on because then I don't have to copy workspace settings (including FTP settings for upload) to each of the hundreds of website folders.

Earlier today I started VS Code as usual, by right-clicking on the folder containing all the websites on the network drive and selecting “Open with Code”. VS Code started as usual and, as I was about to start working, I saw a blue mark over the gear icon on the bottom left. Upon hovering it, a tooltip appeared: “Restart to update”, or something to that effect. I clicked on it, VS Code closed, updated to version 1.32.1, and restarted.

Once VS Code started, the file browser pane stayed empty, with a blue bar scrolling horizontally above it (which I believe is a “loading” indicator). Only after a few minutes did the file pane get populated. From then on, VS Code was back to normal.

Just to be sure, once the files pane was populated, I opened a .cshtml file, closed VS Code (leaving the file open), and opened VS Code again. The exact same thing happened (took minutes to load the file pane), but syntax highlighting and the effects of the “indent-rainbow” extension didn't appear in the editor pane of the opened file until after the files pane was populated.

The issue still happens even if VS Code is started from the command line with “--disable-extensions”.

It seems to me that VS Code is now recursively (and, up to a point, synchronously) scanning the whole workspace directory before populating the files pane and loading/running extensions, which I believe is a change from its behavior up until now. With so many files, over the network, it takes a while. And, while it happens, the files pane can't be used to open files.

Now, this wouldn't be as much of an issue if VS Code could open just a subfolder of the workspace and still detect the workspace settings. Then I could just open the folder of the website I'll be working on instead of the parent folder with all websites, without having to make each and every website a separate workspace—which would bring on the hassle of keeping the settings of hundreds of workspaces in sync.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (9.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   119	 17004	code main
    0	   236	  5416	   window (● _Layout.cshtml - vm_sites - Visual Studio Code)
    0	    11	  1696	     watcherService 
    0	    11	 16064	       console-window-host (Windows internal process)
    0	    13	 12536	     electron-crash-reporter
    0	    60	 16820	     extensionHost
    0	    79	 13884	   gpu-process
    0	    67	 16672	   window (Issue Reporter)
    0	    65	 19136	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● _Layout.cshtml - vm_sites - Visual Studio Code)
|    Folder (vm_sites): more than 64723 files
|      File types: jpg(15098) js(14499) dll(12581) css(5861) png(5081)
|                  config(1580) map(1513) pdb(1214) xml(791) mno(791)
|      Conf files: csproj(3) sln(2) package.json(2) settings.json(1)
|                  tsconfig.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|8.0.0
pascal-formatter|ale|2.1.0
haml|kar|1.1.0
ftp-sync|luk|0.3.9
vscode-apache|mrm|1.2.0
indent-rainbow|ode|7.2.4
ruby|reb|0.22.3
sass-indented|rob|1.5.1

</details>

**Comment by donaggio** [comment] 2019-03-08 14:51
The very same thing as described by the OP is happening to me under a similar scenario: Ubuntu Linux using a workspace with some remote directories mounted locally using gvfs. Except that  VS Code becomes unresponsive and I'm forced to kill its process to close it.
If I start a clean session and I create a new workspace adding back the same directories from the old one, I can work just fine, but as soon as I exit VS Code and I relaunch it, it happens again.

VS Code version 1.32.1 (.deb version 1.32.0-1551898681 from http://packages.microsoft.com/repos/vscode stable/main)

OS: Ubuntu Linux 18.10 X86_64

**Comment by citrus-thunder** [comment] 2019-03-08 17:12
I'm experiencing the same issue here:
* VS Code Version 1.32.1
* Ubuntu 18.10 X86_64

When attempting to load a mapped drive mounted through sshfs the explorer window never even populates with folders -- I've been working with this large filespace in VS Code for two years now and this is the first version that showed any slowness at all loading it up, let alone being seemingly unable to load it entirely.

To test I even mounted a personal webserver's /var/www/ directory to the same drive and attempted to open it with VS Code and while the folders did eventually appear in the explorer this time, it took several minutes, and this is a server with about five small personal websites on it.

I've ended up reinstalling version 1.31 and I'm able to continue working.

**Comment by bpasero** [comment] 2019-03-11 14:14
According to https://github.com/Microsoft/vscode/issues/70143 this is not only from the explorer but also opening normal files.

People hitting this, are you all on the same OS?

**Comment by isidorn** [comment] 2019-03-11 14:31
@bpasero lookint at the comments I see two people on Ubuntu and one person on Windows_NT

**Comment by bpasero** [comment] 2019-03-11 14:59
Can people try to reproduce with our insiders builds:  https://code.visualstudio.com/insiders/

**Comment by davidsantos-br** [comment] 2019-03-11 15:11
Still happens (on Win10 x64) with insiders build 1.33.0 (d77d8d5).

**Comment by psilonmarko** [comment] 2019-03-11 15:22
Running debian 9. Purged 1.31 and installed 1.33 (insiders). No extensions.
Opened folder from mount via VPN. Populating file list (left pane explorer) takes about 2-3 minutes - just to list files the root folder. Additional minutes to open any subfolder.
Clicking on a file and waiting to show in editor... too long. And I had to kill it because it stopped responding.

**Comment by bpasero** [comment] 2019-03-11 15:27
Can people just check if node.js 10.2.0 shows the same issue when trying to e.g. `fs.readdir` a remote folder?

**Comment by davidsantos-br** [comment] 2019-03-11 16:02
I used this:

```js
{
    let start = process.hrtime();
    fs.readdir("T:\\vm_sites\\", function(e, f) {
        console.log("Callback: ", process.hrtime(start), "Files: ", f.length);
    });
    process.hrtime(start);
}
```

The results were always around 40 µs for fs.readdir to return and around 36 ms for the callback to be called, with a list of 493 entries (the folder in question contains 487 directories and 6 files at that level).

![Node readdir](https://user-images.githubusercontent.com/39162/54138088-952c3500-43fd-11e9-9f30-bf21404662b8.PNG)

Neither {withFileTypes: true} nor using fs.readdirSync changes the times significantly (± a couple ms).

**Comment by bpasero** [comment] 2019-03-11 16:36
@davidsantos-br thanks for testing, I forgot to ask people to try out our exploration builds that come with a much newer Electron/node.js version to see if it could help:

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by psilonmarko** [comment] 2019-03-11 16:46
@bpasero tried code-exploration, same problem(s)

**Comment by mightypenguin** [comment] 2019-03-11 20:13
Mac OS host to SSHFS on Linux. Same issue.
What's weird is that this doesn't happen if I remove and create a new workspace (right after creating the new workspace).
It only has the constantly moving blue bar and fails to open files if I reopen a workspace to a large SSHFS filesystem.
It won't even load locally stored files after I close and relaunch the workspace.

**Comment by bpasero** [comment] 2019-03-12 07:07
Maybe about time that we get some profiling information to see where most time is spend. 
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by martbean** [comment] 2019-03-13 15:58
Just to add I am also experiencing this issue on Windows 10 Home connecting via OpenVPN to a remote server running Ubuntu.

I've downgraded to VS Code 1.31.1 for now and that's working fine.

**Comment by psilonmarko** [comment] 2019-03-13 21:36
I tried one more thing today in code-insiders 1.33 - opening mounted folder on another server over cisco vpnc connection and it took some time to index all items (file explorer), but not nearly as long as over openvpn. Clicking on any file or subfolder opened it immediately.
Looks like there is a problem with openvpn

**Comment by m33ts4k0z** [comment] 2019-03-14 01:11
Hello,

Trying to reproduce the issue and upload the text file requested, produced empty files. I'm also suffering from this issue that appears to be VPN related since accessing the same folder from a computer on the same LAN works without delays. However I don't have 500 projects as the OP so I'm certain the root of the problem is still there.

Using either SoftEther VPN or OpenVPN makes things really REALLY slow without an obvious reason.

**Comment by bpasero** [comment] 2019-03-14 07:15
People that see this issue, are you opening the network folder directly (e.g. via File > Open Folder), or is it part of a multi-root workspace file you open? Does it reproduce if you use the UNC on localhost scheme, e.g. when opening a path such as `\\localhost\c$\my_dir`?

**Comment by derekwallace** [comment] 2019-03-14 07:49
In my case i mount as a drive letter.
             P:        \\xxxx\yyyyyy\derek

in my .code-workspace file that i open
{
   "folders": [
      {
         "path": "P:\\AAAA\\BBBB"
      },
   ],

**Comment by donaggio** [comment] 2019-03-14 09:09
I'm under Linux Ubuntu 18.10 x86_64 and I've several locally-mounted network folders added to a multi-root workspace.

My .code-workspace file looks like this:

{
	"folders": [
		{
			"path": "/run/user/1000/gvfs/sftp:host=my.host.name,user=username/path"
		}
       ]
}

**Comment by bpasero** [comment] 2019-03-14 09:32
@derekwallace @donaggio so does this only reproduce when you open a workspace file with these folders but not when opening the folders individually?

**Comment by donaggio** [comment] 2019-03-14 10:20
Just tried with the new code 1.32.2: it happens when opening individual folders too.

**Comment by davidsantos-br** [comment] 2019-03-14 11:37
This issue does not happen for me for a local large folder, even when using a localhost UNC path or an UNC path using my computer's network name. It does happen when accessing a directory on another PC in the 100-megabit LAN, both via a mapped network drive and via an UNC path, regardless of whether I open VS Code by right-clicking on the folder and choosing “Open with Code”, if I open it from the command line with `code T:\vm_sites` or `code \\teste\sites\vm_sites` (T: is mapped to \\teste\sites), or if I just open VS Code without a workspace and use File → Open Folder.

Now, if I don't have any files left open from the previous session, the initial level of the folder does show up rather quickly. But then if I try to expand a subfolder, it takes a while. And while it's loading the subfolder I can't open any files that are already visible.

Those tests were performed with VS Code 1.32.2 which was released two days ago.

**Comment by donaggio** [comment] 2019-03-14 12:00
Same behaviour as @davidsantos-br here under Ubuntu: first level of a folder opens quickly, navigating into subdirectories seems to take longer and longer along with how deeply nested a subdir is or how many files it contains. Just with a two levels deep subdir code seems to hang (it becomes unresponsive and I'm forced to kill it).

**Comment by bpasero** [comment] 2019-03-14 13:00
To rule out the possibility that this was caused by an Electron update, can people try the following builds and see if it reproduces:
- Windows: https://az764295.vo.msecnd.net/insider/4983e81de5bec42b684a0d7868b06c54e6075738/VSCode-win32-x64-1.32.2-insider.zip
- Linux: https://az764295.vo.msecnd.net/insider/4983e81de5bec42b684a0d7868b06c54e6075738/code-insider-1552566866.tar.gz

Please verify from the about dialog that you see an Electron version of 3.1.2.

**Comment by davidsantos-br** [comment] 2019-03-14 13:11
Still happens with that build.

**Comment by bpasero** [comment] 2019-03-14 13:17
@davidsantos-br and it is fast with 1.31? Get it from here: https://az764295.vo.msecnd.net/stable/1b8e8302e405050205e69b59abb3559592bb9e60/VSCode-win32-ia32-1.31.1.zip

**Comment by davidsantos-br** [comment] 2019-03-14 13:48
With 1.31 it takes a few seconds for the files pane to initially load the folder, then expanding subfolders and opening files happens immediately (I didn't notice a delay even randomly expanding several subfolders one after the other).

[Video comparing 1.31 with 1.32](http://www.youtube.com/watch?v=WuQaEBr91fU)

**Comment by bpasero** [comment] 2019-03-14 13:50
@davidsantos-br thanks, besides the slower file explorer, is there any difference when you click a file to open in the editor? E.g. is that action same speed as it was in 1.31?

**Comment by bpasero** [comment] 2019-03-14 14:19
@davidsantos-br btw this video is just great, @isidorn @joaomoreno you might wanna watch it too

**Comment by m33ts4k0z** [comment] 2019-03-14 15:10
The definition of "Large folders" can vary from situation to situation :) I'm opening a laravel project in PHP that has about 6700 subfolders. This is a single project having that many folders and it ships like that with composer. I'm experiencing the exact same situation as the video but only when using it over a VPN connection.

**Comment by sherryyshi** [comment] 2019-03-14 16:37
This also happens with large repos using [GVFS ](https://www.vfsforgit.org/). In case this is helpful - when the virtualization service is disabled (i.e. when GVFS is unmounted), the issue does not repro. However, when the virtualization service is active, it always repros, even on subsequent launches of VS Code.

**Comment by GabeDeBacker** [comment] 2019-03-14 16:40
I was just debugging VSCode and expanded folder "X" in the explorer pane, and it appears that VSCode is enumerating files well outside of folder "X" (meaning not even within it).

For example:
I expanded the folder
"e:\repos\osNew\src\minkernel"
and vscode is enumerating
"e:\repos\osNew\src\base\PerfTest\MemRe\AppLifecycle"

**Comment by bpasero** [comment] 2019-03-14 16:59
i have an idea and will ask people to try a new build once its ready

**Comment by GabeDeBacker** [comment] 2019-03-14 17:16
Looking through the commits and debugging VSCode, I am wondering if these strict null checks changes somehow changed the decision of the file service on whether to enumerate all directories or just the one the explorer view is asking for:

https://github.com/Microsoft/vscode/commit/a6c498b74a33b3e219ff957cee1b7d37170c2102#diff-a63388ce79427f16181b4686359ff685

Debugging through VSCode certainly shows that when the explorer view asks to expand a directory, the entire workspace contents are enumerated.

**Comment by bpasero** [comment] 2019-03-14 18:16
Can people please try with this build if it still reproduces:
* Windows: [Download](https://az764295.vo.msecnd.net/insider/be2662eaf64094f549650bc35e89cf5675528d3d/VSCode-win32-x64-1.32.2-insider.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/insider/be2662eaf64094f549650bc35e89cf5675528d3d/code-insider-1552583659.tar.gz)

This build removes the changes from https://github.com/Microsoft/vscode/pull/67269 that for me put a lot of pressure right on startup due to extensive file scanning.

**Comment by sherryyshi** [comment] 2019-03-14 18:24
@bpasero the build seems to have fixed the issue for me

**Comment by psilonmarko** [comment] 2019-03-14 18:30
@bpasero this latest build (code-insider-1552583659, debian9) works for me as well

**Comment by bpasero** [comment] 2019-03-14 18:44
Awesome thanks for the quick turn around!

**Comment by m33ts4k0z** [comment] 2019-03-14 18:46
@bpasero This build greatly improved things. Opening the folder in a workspace or "open folder" makes eveyrthing open almost instantly even over VPN. I have a folder with over 1000 subfolders and this build needed about 20 seconds to open it which was great improvement since before I had to wait about 5 minutes.

Generally, the experience is still not the same as the local one but its a great improvement in comparison to other builds.

**Closed** 2019-03-14 23:44 UTC
Labels: candidate, file-explorer, freeze-slow-crash, important

**Comment by roblourens** [comment] 2019-03-15 00:30
We verified it by the following steps:

- Open task manager
- Open `\\localhost\c$` on windows using the latest Insiders that has the bug
- See that disk/CPU usage spikes a ton. Try to kill vscode, it won't die

Repeat the same steps with 1.32.3, see that disk/cpu doesn't spike and it's responsive very soon after starting.

**Comment by donaggio** [comment] 2019-03-15 08:35
Confirming that the latest insider's build from @bpasero resolved the issue under Linux, too.

**Comment by martbean** [comment] 2019-03-15 08:57
Looks good to me on Windows 10 as well. Thanks for sorting this!

**Comment by mightypenguin** [comment] 2019-03-15 13:47
1.32.3 appears to have fixed it for me!
