### ISSUE TITLE
Show quick pick always in context where it was opened

### ISSUE THREAD

**Issue by lukaszpolowczyk** [microsoft/vscode#26596] opened 2017-05-13 13:28 UTC
- VSCode Version:1.12.1
- OS Version:Linux

Steps to Reproduce:

1. When mouse click on "Indentation" in statusbar, the "Command Palette" should appear next to the clicked button.
![contextshowing-commandpalettepopup](https://cloud.githubusercontent.com/assets/16800535/26025820/1d047850-37f0-11e7-95b0-85640caf9154.png)

2. The same should happen when you click on other buttons that call up the "Command Palette". Of course not all but the ones that fit. For example, from the menu> View> Command Palette, it should be old.
3. The popup with the "Command Palette" should adjust to the width of the content. It will look aesthetically.
4. It could create a new Extension API that will pop up a Command Palette contextually, with the addition of a button extension.

**Comment by stevencl** [comment] 2017-05-25 11:06
@chrisdias @bpasero - what are your thoughts on this? I think it makes sense UX wise.

**Comment by bpasero** [comment] 2017-05-25 12:02
+1 on all of the points including the ability for extensions to set the context where the picker opens (e.g. useful when an extension contributes a status bar entry that opens a picker).

**Comment by lukaszpolowczyk** [comment] 2017-06-20 15:12
@bpasero You have renamed the topic. I just hope that the contextual display will also affect buttons in other places? Not just in the context of the Statusbar?

For example, from "Bookmarks: list" ("Bookmarks" extension) which is in Tabsbar>More.
Same in the context of any other button that fits.

**Comment by bpasero** [comment] 2017-06-20 15:23
@lukaszpolowczyk my thinking currently is that only when the picker is invoked from the status bar it should be rooted there but in any other cases not because then the action is triggered from the top, isn't that right?

**Comment by lukaszpolowczyk** [comment] 2017-06-20 19:19
@bpasero My idea was contextual display.
The menu appears where the icon is clicked. Just like being on a mockup.

This is not a new idea in the field of interface design. Just a menu should be as close as possible.

**Comment by bpasero** [comment] 2017-06-21 04:21
@lukaszpolowczyk how would that work in this case for the "Opened Editors":

![image](https://user-images.githubusercontent.com/900690/27366962-e6746340-5649-11e7-9a6e-228a8c1eb969.png)

You would show the picker right next to the menu?

**Comment by lukaszpolowczyk** [comment] 2017-06-21 10:23
@bpasero Like this.
And width should always be matched to the content.
![openededitors](https://user-images.githubusercontent.com/16800535/27379505-bdbe01d6-567b-11e7-922b-4f643298b032.gif)

**Comment by bpasero** [comment] 2017-06-21 10:30
I find that a very confusing UX to be honest, why restrict the space so much?

The pain point we want to tackle is that you click somewhere in the status bar and something opens very far away to the top. I do not think we want to change the location of the picker for any other invocation.

**Comment by lukaszpolowczyk** [comment] 2017-06-21 12:21
Actually, you can do wider. If it's about it?
You can do so that Picker returns to the middle of the window when you delete the command and start typing another one. Could this solve a problem?

Displaying the menu at the place of the button is a natural thing, so it is everywhere when it comes to menus. Picker can do that too.
After all, it is much more convenient that you do not need to wave your cursor.

In fact, the place of appearing picker was absurd to me from the beginning. Yet as I saw it in the Atom editor.
View in the middle when the Command Palette is called with a keyboard shortcut - it's ok.
But wherever the mouse is used, the picker should be as close as possible to the cursor. It's natural.

**Comment by bpasero** [comment] 2017-06-21 12:29
@lukaszpolowczyk the current position of the picker is not random, it is in the center to the top for a reason: because it should draw attention to it. 

All of our pickers can also be triggered via keybindings or from the command palette, so with your suggestion you would suddenly see a picker sometimes at its current position, sometimes close to a button and sometimes close to the status bar.

I think it is fine to show the picker close to the status bar if it was triggered with the mouse from there but I am not convinced for the other places.

**Comment by lukaszpolowczyk** [comment] 2017-06-21 13:09
@bpasero
It may thus:
From the keyboard shortcut - in center.
From Command Paletter - in center.
From menu bar - in center.
From "More" menu on tabsbar - in center.
From other menu - in center.
From editor context menu - in center.
From sidebar - in center.
And:
From buttons on tabsbar (perhaps only the buttons added by extensions, because I do not see built-in buttons that call Picker) - in context (bypassing "More", because "More" is a menu).
From buttons on statusbar - in context.

In context - means that you want to be right at the click of a button.
This will probably be fairly transparent, because when displayed in the context of the button, it will look almost like a normal menu.

**Comment by bpasero** [comment] 2017-06-21 13:16
I reverted the summary to how it was and extracted https://github.com/Microsoft/vscode/issues/29193

**Comment by lukaszpolowczyk** [comment] 2017-06-21 13:30
@bpasero Oh... very sad.

**Comment by Tekbr** [comment] 2017-07-13 15:09
-- Sorry for the English, I used Google Translator --

An idea, I do not know if that would be ...

About this [comment](https://github.com/Microsoft/vscode/issues/26596#issuecomment-310036384)

@bpasero , on the thought of @lukaszpolowczyk , maybe viewing the open files next to the menu, could work to similar or Firefox:

![firefox](https://user-images.githubusercontent.com/19866231/28172900-43f2223e-67c3-11e7-83f1-bec96973d94d.gif)

and/or Eclipse:

![eclipse](https://user-images.githubusercontent.com/19866231/28172908-48585e38-67c3-11e7-8ac4-0abe747c16a6.gif)


That is, "Show Opened Editors" could be a new button. But it would be up to you to always be fixed, or only when scrolling begins to appear in the open files.


Was it something like this, @lukaszpolowczyk ?

Making it clear that it is not to remove the scroll bar.

**Comment by bpasero** [comment] 2017-11-17 08:33
/duplicate of https://github.com/Microsoft/vscode/issues/29193

**Comment by lukaszpolowczyk** [comment] 2017-11-17 10:29
@bpasero 
Your topic is a duplicate of my topic. I wrote my first.
And not vice versa.

We have come to the conclusion that they are different.
My idea is better because it is supposed to display in the place of click, closer.

**Comment by bpasero** [comment] 2017-11-17 10:33
@lukaszpolowczyk I remember.

**Closed** 2020-11-03 11:15 UTC
Labels: *out-of-scope, feature-request, quick-pick
