### ISSUE TITLE
Markdown anchor tabs not working as intended

### ISSUE THREAD

**Issue by Zoxjib** [microsoft/vscode#143055] opened 2022-02-14 13:10 UTC
## Environment data

-   VS Code version: 1.64.2
-   Jupyter Extension version: v2022.1.1201831736
-   Python Extension version: v2022.0.1814523869
-   OS and version: Windows 10, 10.0.19043, Build 19043
-   Python: 3.10.2
-   Jupyter server running: Local

## Expected behaviour

When using the following Markdown syntax:
```
[Custom foo description](#foo)
# Foo
```
A link named "Foo" is created and should take the user to the anchor `# Foo` when clicked.

## Actual behaviour

Inside VSCode:
When clicking any link in any cell, the file is scrolled down all the way to the bottom.
![](https://i.imgur.com/tbVvuf8.gif)

When pushed to Github:
The links create a new URL that leads out of the file and into the folder where the file is stored.
![](https://i.imgur.com/trfHHCs.gif)

## Steps to reproduce:

1. Create .ipynb file
2. Create Markdown cell
3. Create header with `# any header name`
4. Create link with `[Custom link description](#any-header-name)`
5. Click link

**Comment by mjbvz** [comment] 2022-02-16 22:40
Duplicate of #141024

**Closed by mjbvz** 2022-02-16 22:40 UTC
Labels: bug, needs-triage
