### ISSUE TITLE
Node not found after upgrading the IDE

### ISSUE THREAD

**Issue by ejf-coders51** [microsoft/vscode#105128] opened 2020-08-21 06:00 UTC
- VSCode Version: 1.48.0
- OS Version: elementary OS 5.1 Hera

Steps to Reproduce:
I use asdf to have a specific node version for each workspace.  When i run the mocha test laucher i receive this error.
![image](https://user-images.githubusercontent.com/67055839/90857222-f347a080-e383-11ea-9576-0280ed79b477.png)
If I downgrade the version to 1.46.1 it restart to work

Does this issue occur when all extensions are disabled?: Yes

**Comment by ejf-coders51** [comment] 2020-08-24 06:46
yes it exists and is not a simbolic link
![image](https://user-images.githubusercontent.com/67055839/91012380-4c167380-e5e6-11ea-9948-295738a147c8.png)

**Comment by connor4312** [comment] 2020-08-24 16:45
Thanks @ejf-coders51. Unfortunately trying `asdf` in a container locally, I didn't hit this. I made a build of the extension that adds additional information to the error message, can you give it a shot? https://memes.peet.io/img/105128-js-debug.vsix You can install it by hitting F1 and then `Install from VSIX`.

Also, as a workaround, you can set `debug.javascript.usePreview: false` in your user settings to use the old debugger until we get this fixed.

**Comment by ejf-coders51** [comment] 2020-08-25 07:08
![image](https://user-images.githubusercontent.com/67055839/91143193-6cabff80-e6b2-11ea-88d2-9e4fd79d9b82.png)

i've installed the vsix. In the terminal npm is working. it seams that the debugger is not runned in the project folder

**Comment by connor4312** [comment] 2020-08-25 15:02
Ah, I see, thanks. Two things, in addition to `usePreview: false`, you can use to get around it:

1. Set `nodeVersionHint: 12` in your package.json
1. Start `code` from a terminal so that in inherits its environment, rather than from the UI

I will close this as a dupe of https://github.com/microsoft/vscode-js-debug/issues/717, which should fix this.

/duplicate

**Closed** 2020-08-25 15:03 UTC
Labels: *duplicate, debug
