### ISSUE TITLE
Installing extension results in the progress bar in Extensions view never going away

### ISSUE THREAD

**Issue by paulxtiseo** [Microsoft/vscode#48069] opened 2018-04-17 18:03 UTC
VSCode: 1.22.1
OS: Windows 10 64-bit

I recently installed VSCode about 2 weeks ago, and gleefully installed a bunch of extensions. Today, I am trying to install Docker (PeterJausovec.vscode-docker) but I get an error. Bringing up the Shared Process viewer, I get this:

![2018-04-17 13_59_20-code](https://user-images.githubusercontent.com/2977050/38887687-8b21bdd6-4247-11e8-9169-3954767a2f87.png)

Normally, I see this because we use Forcepoint at work, which presents a different (FP) cert to my system than the site. This affected me with apps (like FF) that don't seem to use the Windows cert store. In most cases, you can add the cert to the app's store. But not sure how to do this with VSCode?

Running `code --ignore-certificate-errors` doesn't help. I still get the local issuer error.

**Comment by paulxtiseo** [comment] 2018-04-17 18:05
Some of the more recent posters in #34385 might be having the same issue.

**Comment by paulxtiseo** [comment] 2018-04-17 18:13
Issue #30871 is likely the same.

**Comment by ramya-rao-a** [comment] 2018-04-23 23:52
@paulxtiseo the error in the shared process points to ApplicationInsights module, but since this has nothing to do with extension installation itself, I doubt that this is the reason for the failure in installing extension.

You mentioned that when installing the extension you get an error and then you see the above in the shared process viewer. Can you share what that initial error is?

**Comment by paulxtiseo** [comment] 2018-04-26 17:54
I think I may have been confusing Atom and VSCode. Atom is doing the same thing, giving me local issuer errors, but their interface presents it in their search window. VSCode just has the progress bar continuously moving left to right, and stuck in "Installing" mode.

**Comment by ramya-rao-a** [comment] 2018-04-26 18:57
Well, the screenshot you have shared above is definitely VS Code and not Atom :)
Can you try the latest [Insiders](https://code.visualstudio.com/insiders) ?

**Comment by paulxtiseo** [comment] 2018-04-27 13:53
The v1.23.0-insider does the same thing. The little blue progress bar under "Extensions Marketplace" just keeps on progressing forever.

**Comment by paulxtiseo** [comment] 2018-04-27 20:14
Which logs would you like? (And, instructions to get them for you, please.)

**Comment by ramya-rao-a** [comment] 2018-04-27 23:35
F1 -> Developer: Open Log File.. -> Shared

**Comment by paulxtiseo** [comment] 2018-05-07 14:06
Ok, today I went to download the Docker extension to get screenshots and logs, but it worked. I did not change anything on my side, to the best of my knowledge. But, it does mean I am unable to prepare any data for you to consider.

**Comment by sandy081** [comment] 2018-05-09 12:56
Ok. Closing this issue for now since it cannot be reproduced. Please reopen this issue when you see it again and also provide logs.

**Closed by sandy081** 2018-05-09 12:56 UTC
Labels: extensions
