### ISSUE TITLE
Line after braceless if statement doesn't auto-indent

### ISSUE THREAD

**Issue by mccreeker** [Microsoft/vscode#41702] opened 2018-01-16 20:27 UTC
- VSCode Version: 1.19.1
- OS Version: Win10

Steps to Reproduce:

1. If I type a valid if statement (in PHP for example) without an opening brace then hit Enter, the cursor doesn't further indent the next line like in other editors.
2. It just puts the cursor right below the beginning of the if indent, indicating it's a new line completely unrelated to its if statement.

![image](https://user-images.githubusercontent.com/33667567/35010662-d77b1a8e-fac0-11e7-915e-1f87866436df.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment] 2018-09-19 23:33
Duplicate of https://github.com/Microsoft/vscode/issues/43244, let's track it here.

**Closed** 2018-09-19 23:42 UTC
Labels: *duplicate, editor, editor-autoindent, feature-request
