### ISSUE TITLE
sync my global setting and installed extension with cloud account

### ISSUE THREAD

**Issue by uxitten** [Microsoft/vscode#60755] opened 2018-10-12 08:53 UTC
sync my global setting and installed extension with cloud account

**Comment by egamma** [comment] 2018-10-12 11:58
duplicate of https://github.com/Microsoft/vscode/issues/53453

There is the sync extension  https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Closed by egamma** 2018-10-12 11:58 UTC
Labels: extensions
