### ISSUE TITLE
Window display is hazy/blurry

### ISSUE THREAD

**Issue by BoscoDomingo** [microsoft/vscode#148592] opened 2022-05-02 22:22 UTC
Issue Type: <b>Bug</b>

When using the new v1.66.2 the display becomes blurry, and text is ineligible.

I have tested and everything works fine on 1.65.2

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.77GB free)|
|Process Argv|--crash-reporter-id 612cc11a-7156-41f0-a4cc-ca1286985fda|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.46.0
gitlens|eam|12.0.5
vscode-great-icons|emm|2.1.84
prettier-vscode|esb|9.3.0
auto-close-tag|for|0.5.14
vscode-pull-request-github|Git|0.38.1
gc-excelviewer|Gra|4.2.53
better-shellscript-syntax|jef|1.1.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.20
vscode-docker|ms-|1.18.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.2
remote-containers|ms-|0.224.3
remote-wsl|ms-|0.64.2
vsliveshare|ms-|1.0.5449
material-icon-theme|PKi|4.14.1
ayu|tea|1.0.5
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0

(8 theme extensions excluded)

</details>

**Comment by BoscoDomingo** [comment] 2022-05-02 22:30
v1.66.2 with the issue

https://user-images.githubusercontent.com/46006784/166336820-1aa8de37-5abb-467c-a3c9-7ad9b3bf8e04.mp4

v1.65.2 with no issue

https://user-images.githubusercontent.com/46006784/166337109-23bd0a47-2612-4d13-8864-a5a6cd1b1649.mp4



<img width="1920" alt="Code_4EIRwRIiwr" src="https://user-images.githubusercontent.com/46006784/166336836-f5b528ea-742a-436a-8229-0cc7aa987e16.png">
<img width="1920" alt="Code_rHiHkphgWS" src="https://user-images.githubusercontent.com/46006784/166336838-73569ba3-70a4-424a-a5db-7c518c85ee96.png">

**Comment by gjsjohnmurray** [comment] 2022-05-03 09:46
Probably a duplicate of #147982

Please try launching VS Code from a Windows command prompt (not a VS Code Terminal), adding the --disable-gpu switch:

```
code --disable-gpu
```

**Comment by deepak1556** [comment] 2022-05-04 10:18
Merging to https://github.com/microsoft/vscode/issues/146381, please follow the issue for updates. Thanks!

**Closed by deepak1556** 2022-05-04 10:18 UTC
