### ISSUE TITLE
Can't trigger "Load more Stack Frames" with keyboard

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64834] opened 2018-12-12 00:36 UTC
- Debug a large stack
- Use arrow keys to move selection to the "Load more Stack Frames" frame
- Press enter or space bar
- The frame becomes selected but otherwise nothing happens

Regression from 1.29

**Comment by isidorn** [comment] 2018-12-12 11:49
It is not only the load more stack frames, but everything in the call stack view does not react to keyboard open. So you can not open stack frames
The issue is that the TreeResourceNavigator2 which was custom made for the markers panel.

This issue is also visible in the other client of the TreeResourceNavigator2 the Loaded Scripts view.
Since this is an accessibility issue and a clear regression I am adding a candidate label and assigning to november.

To verify:

1. Start debugging
2. Navigate using the keyboard in the call stack view, make sure that pressing Enter opens the stack frame. Also pressing enter on the Load More Stack Frames loads more stack frames

**Comment by isidorn** [comment] 2018-12-12 13:40
Fixed in master, closing
There is a PR for the release branch

**Comment by isidorn** [comment] 2018-12-13 09:50
PR merged and fixed

**Closed by isidorn** 2018-12-13 09:50 UTC
Labels: bug, candidate, debug
