### ISSUE TITLE
Notebook with Markdown Cells Not Loading in VS Code when Attached to a Pod Instance

### ISSUE THREAD

**Issue by francisco-perez-sorrosal** [microsoft/vscode#129868] opened 2021-07-29 19:21 UTC
Hi there! I've detected a problem when loading/rendering Jupyter Notebooks that include Markdown cells when loaded in a VSCode instance that is attached to a K9s Pod instance.  The same notebook renders perfectly in my local (Mac) VSCode instance. There are similar rendering problems described in the issues (e.g. microsoft/vscode-jupyter#6330, microsoft/vscode-jupyter#6369) but not exactly the same as this (at least I couldn't find the specific log errors I put below.) 

**Note**: Not sure if the problem is about the Jupyter extension or any other related problem, so please let me know if I should post it in the project specific page of a different VSCode Extension after you review the behavior and logs below. Thanks!

## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1054968649
-   Python Extension version (available under the Extensions sidebar): v2021.7.1060902895
-   Pylance Extension version (available under the Extensions sidebar): v2021.7.7
-   OS (Windows | Mac | Linux distro) and version: MacOS BigSur (11.4)
-   Python and/or Anaconda version: 3.6.8
-   Kubernetes Extension version: 1.3.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): VSCode attached to a Kubernetes pod with docker image with python installed
-   Jupyter server running: Local in the Pod

## Expected behaviour

Properly load, render and execute cells in a `.ipynb` file that includes regular code cells and markdown cells in a pod-attached Visual Studio Code instance.

## Actual behaviour

When a `.ipynb` file includes ONLY code cells, the Pod-attached VSCode instance properly loads and renders the notebook, and it is able to  execute the cells with no problem. HOWEVER, when a `.ipynb` file INCLUDES any Markdown cells in it, the behavior observed is similar to what is described in microsoft/vscode-jupyter#6330, in the sense that a `.ipynb` file loaded in a pod-attached Visual Studio Code instance, gets stuck when trying to render the notebook on the screen. 

Despite the `.ipynb` file is not rendered in the VSCode editor, if you click the `Run All` button the notebook seems to be executing normally. It seems to be only a render problem/bug (See logs below.)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install Kubernetes extension in VSCode
2. Select target Pod to attach in the Kubernetes cluster
3. Attach VSCode to the Pod selected
4. Install in the attached pod the Python and Jupyter Extensions
5. Load or create a `.ipynb` notebook file and add a Markdown cell into it. When doing this the Markdown files are not rendered.
6. Close the file created in step 5
7. Try to reopen the file created and the "Actual behavior" described above appears

## Logs

<details>

<summary>Output for Developer Tools panel (Help | Toggle Developer Tools, and View | Output)
</summary>

```
[Extension Host] Starting WebSocket: ws://localhost:8888/api/kernels/959448af-d9d1-45b3-b6ea-3aebbd45b4cf
5notebookWebviewPreloads.js:3 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from https://vscode-remote%2Bk8s-container%2Bcontext%3Domega.ygrid1.gq1%2Bpodname%3Ddefault-home-fperez-satancisco%2Bnamespace%3Dhome-fperez%2Bname%3Dscience-pod%2Bimage%3Ddocker.ouroath.com%253a4443%252fml%252fml-bundle4-lab%253a20210621-30570951.vscode-resource.vscode-webview.net/home/default/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/markdown-language-features/notebook-out/index.js
    at S (VM14 notebookWebviewPreloads.js:3)
    at r (VM14 notebookWebviewPreloads.js:3)
    at x._load (VM14 notebookWebviewPreloads.js:3)
    at x.load (VM14 notebookWebviewPreloads.js:3)
    at VM14 notebookWebviewPreloads.js:3
    at Array.map (<anonymous>)
    at Object.render (VM14 notebookWebviewPreloads.js:3)
    at H.updateContentAndRender (VM14 notebookWebviewPreloads.js:3)
    at new H (VM14 notebookWebviewPreloads.js:3)
    at Object.createMarkupCell (VM14 notebookWebviewPreloads.js:3)
S @ VM14 notebookWebviewPreloads.js:3
r @ VM14 notebookWebviewPreloads.js:3
_load @ VM14 notebookWebviewPreloads.js:3
load @ VM14 notebookWebviewPreloads.js:3
(anonymous) @ VM14 notebookWebviewPreloads.js:3
render @ VM14 notebookWebviewPreloads.js:3
updateContentAndRender @ VM14 notebookWebviewPreloads.js:3
H @ VM14 notebookWebviewPreloads.js:3
createMarkupCell @ VM14 notebookWebviewPreloads.js:3
ensureMarkupCell @ VM14 notebookWebviewPreloads.js:3
(anonymous) @ VM14 notebookWebviewPreloads.js:3
(anonymous) @ VM14 notebookWebviewPreloads.js:3
Promise.then (async)
H @ VM14 notebookWebviewPreloads.js:3
createMarkupCell @ VM14 notebookWebviewPreloads.js:3
ensureMarkupCell @ VM14 notebookWebviewPreloads.js:3
(anonymous) @ VM14 notebookWebviewPreloads.js:3
(anonymous) @ VM14 notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ VM7 main.js:116
P @ VM7 main.js:116
(anonymous) @ VM7 main.js:116
load (async)
H @ VM7 main.js:116
(anonymous) @ VM7 main.js:116
setTimeout (async)
L @ VM7 main.js:116
(anonymous) @ VM7 main.js:116
notebookWebviewPreloads.js:3 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from https://vscode-remote%2Bk8s-container%2Bcontext%3Domega.ygrid1.gq1%2Bpodname%3Ddefault-home-fperez-satancisco%2Bnamespace%3Dhome-fperez%2Bname%3Dscience-pod%2Bimage%3Ddocker.ouroath.com%253a4443%252fml%252fml-bundle4-lab%253a20210621-30570951.vscode-resource.vscode-webview.net/home/default/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/markdown-language-features/notebook-out/index.js
    at S (VM14 notebookWebviewPreloads.js:3)
    at r (VM14 notebookWebviewPreloads.js:3)
    at x._load (VM14 notebookWebviewPreloads.js:3)
    at x.load (VM14 notebookWebviewPreloads.js:3)
    at VM14 notebookWebviewPreloads.js:3
    at Array.map (<anonymous>)
    at Object.render (VM14 notebookWebviewPreloads.js:3)
    at H.updateContentAndRender (VM14 notebookWebviewPreloads.js:3)
    at new H (VM14 notebookWebviewPreloads.js:3)
    at Object.createMarkupCell (VM14 notebookWebviewPreloads.js:3)
notebookWebviewPreloads.js:3 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from https://vscode-remote%2Bk8s-container%2Bcontext%3Domega.ygrid1.gq1%2Bpodname%3Ddefault-home-fperez-satancisco%2Bnamespace%3Dhome-fperez%2Bname%3Dscience-pod%2Bimage%3Ddocker.ouroath.com%253a4443%252fml%252fml-bundle4-lab%253a20210621-30570951.vscode-resource.vscode-webview.net/home/fperez/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1054968649/out/datascience-ui/notebook/fontAwesomeLoader.js
    at S (notebookWebviewPreloads.js:3)
    at h (notebookWebviewPreloads.js:3)
    at Object.load (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
```
</details>

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

Despite the `.ipynb` file is not rendered in the VSCode editor, if you click the `Run All` button the notebook seems to be executing normally. It seems to be only a render problem/bug.

<p>

```
Info 2021-07-29 19:07:31: Attempting to start a server because of preload conditions ...
Info 2021-07-29 19:07:31: No controller, hence notebook communications cannot be initialized for editor file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:31: Creating server with settings : {"baseUrl":"http://localhost:8888/","appUrl":"","wsUrl":"ws://localhost:8888/","token":"qD9Fi3QGIpx2o4C8RAZ4ZVJx0w4Tfc94AhWDgh3eSmBxCvNS","init":{"cache":"no-store","credentials":"same-origin"}}
Info 2021-07-29 19:07:31: Disposing session manager
Info 2021-07-29 19:07:31: SessionManager - dispose contents manager
Info 2021-07-29 19:07:31: ShutdownSessionAndConnection - dispose session manager
Info 2021-07-29 19:07:31: Finished disposing jupyter session manager
Info 2021-07-29 19:07:31: Creating server with settings : {"baseUrl":"http://localhost:8888/","appUrl":"","wsUrl":"ws://localhost:8888/","token":"qD9Fi3QGIpx2o4C8RAZ4ZVJx0w4Tfc94AhWDgh3eSmBxCvNS","init":{"cache":"no-store","credentials":"same-origin"}}
Info 2021-07-29 19:07:31: Disposing session manager
Info 2021-07-29 19:07:31: SessionManager - dispose contents manager
Info 2021-07-29 19:07:31: ShutdownSessionAndConnection - dispose session manager
Info 2021-07-29 19:07:31: Finished disposing jupyter session manager
Info 2021-07-29 19:07:31: Find preferred kernel for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb with metadata {"interpreter":{"hash":"e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a"},"kernelspec":{"name":"python3","display_name":"Python 3.6.8 64-bit"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.6.8"}} & preferred interpreter {}
Info 2021-07-29 19:07:31: Preferred kernel for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb is undefined
Info 2021-07-29 19:07:31: findPreferredKernel score for Scala (2.12) is -1
Info 2021-07-29 19:07:31: findPreferredKernel score for Scala (2.13) is -1
Info 2021-07-29 19:07:31: findPreferredKernel score for Spark (Scala) is -1
Info 2021-07-29 19:07:31: findPreferredKernel score for speclanguage=python, Python 3 is -1
Info 2021-07-29 19:07:31: findPreferredKernel score for Python 3 is 1
Info 2021-07-29 19:07:31: findPreferredKernel score for speclanguage=python, Python 3.6 (XPython) is -1
Info 2021-07-29 19:07:31: findPreferredKernel score for Python3, Python 3.6 (XPython) is 2
Info 2021-07-29 19:07:31: findPreferredKernel score for Python 3.6 (XPython) is 2
Info 2021-07-29 19:07:31: Find remote kernel spec, Class name = y, completed in 15ms, has a truthy return value, Arg 1: <Uri:/home/fperez/persistent_drive/dev/nbdev_test/index.ipynb>, Arg 2: {"type":"jupyter","baseUrl":"http://localhost:8888/","token":"qD9Fi3QGIpx2o4C8RAZ4ZVJx0w4Tfc94AhWDgh3eSmBxCvNS","hostName":"localhost","localLaunch":false,"valid":true,"displayName":"http://localhost:8888/?token=qD9Fi3QGIpx2o4C8RAZ4ZVJx0w4Tfc94AhWDgh3eSmBxCvNS","rootDirectory":"","url":"http://localhost:8888/?token=qD9Fi3QGIpx2o4C8RAZ4ZVJx0w4Tfc94AhWDgh3eSmBxCvNS"}, Arg 3: {"interpreter":{"hash":"e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a"},"kernelspec":{"name":"python3","display_name":"Python 3.6.8 64-bit"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.6.8"}}, Arg 4: {"_isCancelled":false,"_emitter":null}, Return Value: {"kind":"startUsingKernelSpec","kernelSpec":{"name":"xpython","argv":["python3.6","-m","xpython_launcher","-f","{connection_file}"],"language":"python","path":"python3.6","display_name":"Python 3.6 (XPython)","metadata":{"debugger":true},"env":{}},"id":".xpython.python3.6..-m#xpython_launcher"}
Info 2021-07-29 19:07:31: PreferredConnection: .xpython.python3.6..-m#xpython_launcher found for NotebookDocument: file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:31: TargetController found ID: .xpython.python3.6..-m#xpython_launcher for document file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:31: Setting controller affinity for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb .xpython.python3.6..-m#xpython_launcher
Info 2021-07-29 19:07:32: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-07-29 19:07:53: Setting setActiveController for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: Intiailize notebook communications for editor file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: Resolving notebook UI Comms (resolve) for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: initialize CommonMessageCoordinator
Info 2021-07-29 19:07:53: Execute Cells request 6 0, 1, 2, 9, 10, 11
Info 2021-07-29 19:07:53: Execute Cell 0 file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: Starting Notebook in kernel.ts id = .xpython.python3.6..-m#xpython_launcher
Info 2021-07-29 19:07:53: Cell Index:0, state:undefined, exec: undefined. User queued cell for execution
Info 2021-07-29 19:07:53: Execute Cell 1 file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: Cell Index:1, state:undefined, exec: 5. User queued cell for execution
Info 2021-07-29 19:07:53: Execute Cell 2 file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: Cell Index:2, state:undefined, exec: 6. User queued cell for execution
Info 2021-07-29 19:07:53: Execute Cell 9 file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: Cell Index:9, state:undefined, exec: 7. User queued cell for execution
Info 2021-07-29 19:07:53: Execute Cell 10 file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: Cell Index:10, state:undefined, exec: 8. User queued cell for execution
Info 2021-07-29 19:07:53: Execute Cell 11 file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:53: Cell Index:11, state:undefined, exec: undefined. User queued cell for execution
Info 2021-07-29 19:07:53: Compute Launch Info uri = /home/fperez/persistent_drive/dev/nbdev_test/index.ipynb, kernelConnection id = .xpython.python3.6..-m#xpython_launcher
Info 2021-07-29 19:07:53: Compute Launch Info uri = /home/fperez/persistent_drive/dev/nbdev_test/index.ipynb, changed false, .xpython.python3.6..-m#xpython_launcher
Info 2021-07-29 19:07:53: Computed Launch Info uri = /home/fperez/persistent_drive/dev/nbdev_test/index.ipynb, changed false, .xpython.python3.6..-m#xpython_launcher
Info 2021-07-29 19:07:53: Starting a new session for kernel id = .xpython.python3.6..-m#xpython_launcher, name = xpython
http://localhost:8888/: Kernel started: 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:53: Waiting for idle on (kernel): 4474b1d5-417a-4149-a2ba-ddae9872b613 -> unknown
Info 2021-07-29 19:07:54: KernelProvider switched kernel to id = .xpython.python3.6..-m#xpython_launcher
Info 2021-07-29 19:07:54: Finished waiting for idle on (kernel): 4474b1d5-417a-4149-a2ba-ddae9872b613 -> idle
Info 2021-07-29 19:07:54: Started session 3aa28d1e-1569-4dfb-a48c-8dd64cd524b7
Info 2021-07-29 19:07:54: Waiting for idle (session) 3aa28d1e-1569-4dfb-a48c-8dd64cd524b7
Info 2021-07-29 19:07:54: Waiting for idle on (kernel): 4474b1d5-417a-4149-a2ba-ddae9872b613 -> idle
Info 2021-07-29 19:07:54: Finished waiting for idle on (kernel): 4474b1d5-417a-4149-a2ba-ddae9872b613 -> idle
Info 2021-07-29 19:07:54: Initial setup for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb starting ...
Info 2021-07-29 19:07:54: UpdateWorkingDirectoryAndPath
Info 2021-07-29 19:07:54: Kernel switching to busy
Info 2021-07-29 19:07:54: Initial setup complete for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:54: Finished connecting 3aa28d1e-1569-4dfb-a48c-8dd64cd524b7
http://localhost:8888/: Creating new notebook 
Info 2021-07-29 19:07:54: Updating preferred kernel for remote notebook 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:54: Preferred kernel for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb is 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:54: UpdateWorkingDirectoryAndPath
Info 2021-07-29 19:07:54: [32mQueuing messages (no listenerts)
Info 2021-07-29 19:07:54: Registering commtarget jupyter.widget
Info 2021-07-29 19:07:54: IPyWidgetMessageDispatcher.initialize
Info 2021-07-29 19:07:54: Created and initailized CommonMessageCoordinator
Info 2021-07-29 19:07:54: IPyWidgetScriptSource.initialize
Info 2021-07-29 19:07:54: Attach Coordinator for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: IPyWidgetMessageDispatcher.initialize
Info 2021-07-29 19:07:54: Waiting for idle on (kernel): 4474b1d5-417a-4149-a2ba-ddae9872b613 -> busy
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_kernelOptions
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: Kernel switching to idle
Info 2021-07-29 19:07:54: Notebook Session status file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb # Idle
Info 2021-07-29 19:07:54: Finished waiting for idle on (kernel): 4474b1d5-417a-4149-a2ba-ddae9872b613 -> idle
Info 2021-07-29 19:07:54: Hooked up kernel restart handler
Info 2021-07-29 19:07:54: Cell Index:0, state:2, exec: undefined. Ready to execute
Info 2021-07-29 19:07:54: Cell Index:1, state:2, exec: undefined. Ready to execute
Info 2021-07-29 19:07:54: Cell Index:2, state:2, exec: undefined. Ready to execute
Info 2021-07-29 19:07:54: Cell Index:9, state:2, exec: undefined. Ready to execute
Info 2021-07-29 19:07:54: Cell Index:10, state:2, exec: undefined. Ready to execute
Info 2021-07-29 19:07:54: Cell Index:11, state:2, exec: undefined. Ready to execute
Info 2021-07-29 19:07:54: Cell Index:0, state:2, exec: undefined. Before Execute individual cell
Info 2021-07-29 19:07:54: Cell Index:0, state:2, exec: undefined. Start execution
Info 2021-07-29 19:07:54: Starting a new session for kernel id = .xpython.python3.6..-m#xpython_launcher, name = xpython
http://localhost:8888/: Kernel started: 8e795cd1-7802-411f-9a3e-b17fb4708ae6
Info 2021-07-29 19:07:54: Waiting for idle on (kernel): 8e795cd1-7802-411f-9a3e-b17fb4708ae6 -> unknown
Info 2021-07-29 19:07:54: Updating preferred kernel for remote notebook 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:54: Preferred kernel for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb is 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:54: Cell Index:0, state:3, exec: undefined. Send code for execution
Info 2021-07-29 19:07:54: Cell Index:0, state:3, exec: undefined. Empty cell execution
Info 2021-07-29 19:07:54: Cell Index:0, state:3, exec: undefined. Completed successfully
Info 2021-07-29 19:07:54: Cell Index:0, state:3, exec: undefined. Completed successfully & resolving
Info 2021-07-29 19:07:54: Cell Index:0, state:3, exec: undefined. After Execute individual cell 2
Info 2021-07-29 19:07:54: Cell Index:1, state:2, exec: undefined. Before Execute individual cell
Info 2021-07-29 19:07:54: Cell Index:1, state:2, exec: undefined. Start execution
Info 2021-07-29 19:07:54: Cell Index:0, state:3, exec: undefined. Execution disposed
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: undefined. Send code for execution
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: undefined. Wait for jupyter execution
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: undefined. Kernel switching to busy
Info 2021-07-29 19:07:54: Notebook Session status file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb # Busy
Info 2021-07-29 19:07:54: Updating preferred kernel for remote notebook 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:54: Preferred kernel for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb is 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: undefined. Update output
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-29 19:07:54: [32mPosting message to Notebook UI 
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: 2. Kernel switching to idle
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: 2. Jupyter execution completed
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: 2. Completed successfully
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: 2. Completed successfully & resolving
Info 2021-07-29 19:07:54: Notebook Session status file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb # Idle
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: 2. After Execute individual cell 4
Info 2021-07-29 19:07:54: Cancel all remaining cells true || 4
Info 2021-07-29 19:07:54: Cancel pending cells
Info 2021-07-29 19:07:54: Cell Index:2, state:2, exec: undefined. Execution cancelled
Info 2021-07-29 19:07:54: Cell Index:9, state:2, exec: undefined. Execution cancelled
Info 2021-07-29 19:07:54: Cell Index:10, state:2, exec: undefined. Execution cancelled
Info 2021-07-29 19:07:54: Cell Index:11, state:2, exec: undefined. Execution cancelled
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: 2. Executed successfully in executeCell
Info 2021-07-29 19:07:54: Updating preferred kernel for remote notebook 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:54: Preferred kernel for file:///home/fperez/persistent_drive/dev/nbdev_test/index.ipynb is 4474b1d5-417a-4149-a2ba-ddae9872b613
Info 2021-07-29 19:07:54: Cell Index:2, state:2, exec: undefined. Completed due to cancellation
Info 2021-07-29 19:07:54: Cell Index:2, state:2, exec: undefined. Cell cancelled & resolving
Info 2021-07-29 19:07:54: Cell Index:9, state:2, exec: undefined. Completed due to cancellation
Info 2021-07-29 19:07:54: Cell Index:9, state:2, exec: undefined. Cell cancelled & resolving
Info 2021-07-29 19:07:54: Cell Index:10, state:2, exec: undefined. Completed due to cancellation
Info 2021-07-29 19:07:54: Cell Index:10, state:2, exec: undefined. Cell cancelled & resolving
Info 2021-07-29 19:07:54: Cell Index:11, state:2, exec: undefined. Completed due to cancellation
Info 2021-07-29 19:07:54: Cell Index:11, state:2, exec: undefined. Cell cancelled & resolving
Info 2021-07-29 19:07:54: Cell Index:2, state:2, exec: undefined. Execution disposed
Info 2021-07-29 19:07:54: Cell Index:9, state:2, exec: undefined. Execution disposed
Info 2021-07-29 19:07:54: Cell Index:10, state:2, exec: undefined. Execution disposed
Info 2021-07-29 19:07:54: Cell Index:11, state:2, exec: undefined. Execution disposed
Info 2021-07-29 19:07:54: Cell Index:1, state:3, exec: 2. Execution disposed
Info 2021-07-29 19:07:54: Finished waiting for idle on (kernel): 8e795cd1-7802-411f-9a3e-b17fb4708ae6 -> idle

```

</p>
</details>

**Comment by francisco-perez-sorrosal** [comment] 2021-08-06 18:41
After updating VSCode to Version 1.59.0 (Universal), now the error rendering the .ipynb files in the Pod (from the Output for Developer Tools panel) is:

```
notebookWebviewPreloads.js:2 Uncaught (in promise) TypeError: Failed to resolve module specifier 'https://vscode-remote%2Bk8s-container%2Bcontext%3Domega.ygrid1.gq1%2Bpodname%3Ddefault-home-fperez-satancisco%2Bnamespace%3Dhome-fperez%2Bname%3Dscience-pod%2Bimage%3Ddocker.ouroath.com%253a4443%252fml%252fml-bundle4-lab%253a20210621-30570951.vscode-resource.vscode-webview.net/home/default/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/extensions/markdown-language-features/notebook-out/index.js'
    at __import (notebookWebviewPreloads.js:2)
    at O._load (notebookWebviewPreloads.js:3)
    at O.load (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
    at Array.map (<anonymous>)
    at Object.render (notebookWebviewPreloads.js:3)
    at z.updateContentAndRender (notebookWebviewPreloads.js:3)
    at new z (notebookWebviewPreloads.js:3)
    at Object.createMarkupCell (notebookWebviewPreloads.js:3)
    at Object.ensureMarkupCell (notebookWebviewPreloads.js:3)
```

**Comment by mjbvz** [comment] 2021-08-11 23:34
Possible a duplicate of #123494. Does this still reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by francisco-perez-sorrosal** [comment] 2021-08-12 00:28
I've just checked with the insider version below and it works for me. Notebooks are no longer stuck when loading Markdown cells, which now are rendered properly:

```
Version: 1.60.0-insider (Universal)
Commit: 7c25c174726ab969db3f99058cdf24bcfae1cfbe
Date: 2021-08-11T05:13:17.497Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Comment by mjbvz** [comment] 2021-08-12 00:35
Thanks for testing! Closing as a duplicate of #123494

**Closed by mjbvz** 2021-08-12 00:35 UTC
Labels: needs more info, webview, notebook-markdown
