### ISSUE TITLE
Bug: File explorer not showing files after restarting in Zen mode

### ISSUE THREAD

**Issue by MarkSMT** [Microsoft/vscode#32326] opened 2017-08-11 13:15 UTC
- VSCode Version: 1.15.0
- OS Version: macOS 10.13 beta 4 (high sierra)

Steps to Reproduce:

1. Enable `"zenMode.restore": true` in settings
2. Close editor, open it again
3. Check your file explorer, it will not expand

Reproduces without extensions: Yes/No did not check

Whenever zenMode restore is enabled and you open vscode again, the file explorer in the side bar will not be expandable. Exiting zen mode and restarting vscode will show the file exporer and the files..

**Comment by weinand** [comment] 2017-08-11 15:32
I cannot reproduce (or I do not really understand your steps and the problem).
What do you mean by "file explorer in the side bar will not be expandable"?

**Comment by MarkSMT** [comment] 2017-08-11 17:38
<img width="391" alt="screen shot 2017-08-11 at 19 37 49" src="https://user-images.githubusercontent.com/20295793/29224938-a943e7a6-7ecc-11e7-8a4c-83febb1a14dd.png">

**Comment by MarkSMT** [comment] 2017-08-11 17:40
In the sidebar 'SMT-EDITOR' is not collapsed. Yet i can not see the contents of that project. Quitting zen mode and restarting fixes it.

There might be something wrong when vscode starts up in zen mode.

**Comment by weinand** [comment] 2017-08-11 19:26
And this problem reproduces without extensions?

**Comment by MarkSMT** [comment] 2017-08-11 19:32
Nope, found the culprit, Git History (git-log) extension. Will open a issue there.

**Comment by weinand** [comment] 2017-08-11 19:33
Great, thanks for investigating this.

**Comment by DonJayamanne** [comment] 2017-08-12 00:21
Not sure how an extension can cause the file explorer not to show? We (extension authors) don't have control over such things!

**Comment by bpasero** [comment] 2017-08-12 06:06
This could be an issue with contributed views? Reopening for @sandy081 and @isidorn to investigate.

**Comment by bpasero** [comment] 2017-08-16 05:10
@MarkSMT 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by MarkSMT** [comment] 2017-08-16 18:08
@bpasero 
Here you go.

Output from `vscode --verbose`
[vscode --verbose.txt](https://github.com/Microsoft/vscode/files/1229099/vscode.--verbose.txt)

Output in dev console
[vscode --console.txt](https://github.com/Microsoft/vscode/files/1229109/vscode.--console.txt)

If you need more info just ask. I'll check out the logs myself as well, try to resolve the errors and check if those were the culprits.

**Comment by MarkSMT** [comment] 2017-08-18 10:31
@bpasero i dont have the issue any more..
(i removed some extensions and updated to the recovery update)

**Comment by sandy081** [comment] 2017-08-21 15:00
I doubt this could be due to view height overflow.

**Comment by lgdkad** [comment] 2017-08-23 02:05
same issue. 
@weinand said 
> Just launch code with --disable-extensions flag.

I am not quite sure how to do that. I did the following things:
1. cd /Applications/Visual Studio Code.app/Contents/MacOS
2. ./Electron --disable-extensions
then I found all extensions in extension list are disabled.
but files are still not showed in file explorer. :(

here is my run log. 
`➜  MacOS ./Electron --verbose --disable-extensions
GVA info: Successfully connected to the Intel plugin, offline Gen75 
[main 上午10:02:09] Starting VS Code in verbose mode
[main 上午10:02:09] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 上午10:02:09] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false }
[main 上午10:02:09] Unable to read folders in /Users/xxxx/Library/Application Support/Code/Workspaces (Error: ENOENT: no such file or directory, scandir '/Users/xxxx/Library/Application Support/Code/Workspaces').
[main 上午10:02:10] IPC#vscode-machineId
[main 上午10:02:11] IPC#vscode-workbenchLoaded
`

please help me. thank you very much!

**Comment by sandy081** [comment] 2017-08-23 06:44
@lgdkad Can you please try resizing your sections in the explorer and check?

**Comment by lgdkad** [comment] 2017-08-23 07:08
![vscode_issue](https://user-images.githubusercontent.com/18627838/29602941-c760b43e-8814-11e7-9b81-ed8735b7a7b2.gif)

@sandy081 

FYI. thank you!

**Comment by sandy081** [comment] 2017-08-23 12:58
@lgdkad Can you please right click on the header and see if files explorer is selected or not

![image](https://user-images.githubusercontent.com/10746682/29616998-93336072-8813-11e7-80b9-271601f1d05b.png)

**Comment by lgdkad** [comment] 2017-08-24 01:14
![snapshot](https://user-images.githubusercontent.com/18627838/29644816-e8141c06-88ab-11e7-9c4d-266503ce6f74.png)
@sandy081 it works! thank you so much! It's nice of you.

I never thought that the header can pop a menu when it's right clicked.  it's my bad.
For a better user experience, to those new to vscode like me, I suggest to add an icon to give a hint of changing the display mode of file explorer. What do you think?
![snapshot2](https://user-images.githubusercontent.com/18627838/29644895-96e32baa-88ac-11e7-9e03-78ff943a3de9.png)

**Comment by sandy081** [comment] 2017-08-24 06:59
@lgdkad It seems you have hidden/removed the view by right clicking on the header of the view. Will think if it is easy to show the view.

FYI this behaviour is similar to toggling viewlets in the activity bar.

**Comment by lgdkad** [comment] 2017-08-24 12:23
@sandy081 I didn't know the header of the file explorer can be right clicked until you told me.So I came here for help.
I know what you mean. However, I just thought that header is same as the area next to file tab. In general, it can not be right clicked.
<img width="1022" alt="1" src="https://user-images.githubusercontent.com/18627838/29665964-f5e62f42-8908-11e7-9fb9-89ae0c023852.png">

A tab is thought to be an area which can be right clicked in general.
<img width="641" alt="2" src="https://user-images.githubusercontent.com/18627838/29665994-1ac19d4c-8909-11e7-9d3b-19bf7ce74753.png">

Because English is not my first language, maybe there is something I didn't express clearly.
I hope you can understand what I mean.

Anyway, that's just my suggestion. If your team thinks that vscode should add an icon, just add it. If not, it's also OK. 
:)

Thank you for your help.

**Comment by sandy081** [comment] 2017-08-25 13:41
@MarkSMT I kind of lost what is the real issue here. Can you please let me know what is the issue that this item is created for and steps to reproduce it?

**Comment by MarkSMT** [comment] 2017-08-26 09:12
@sandy081 the issue is that the file explorer will not expand when opening the editor. This happens when you have some extensions that put some other 'tabs' where the file explorer is and you have the setting 'start in zen mode when closed in zen mode' on. Its really hard to reproduce since it looks like it breaks because of some extensions. (Exiting zen mode and restarting the vscode fixes the issue)

I don't have the issue anymore since i uninstalled lots of extensions i didn't use. So i don't think i can be of any further help.. I'll try to help though anyway i can.

**Comment by sandy081** [comment] 2017-08-28 08:31
@MarkSMT Thanks for the reply. 

Since there are no steps to reproduce this issue I am closing it. Will reopen it when we get the steps.

**Closed by sandy081** 2017-08-28 08:31 UTC
Labels: explorer-custom, needs more info, workbench
