### ISSUE TITLE
Cannot open folder, V. June2020, Manjaro 4.14

### ISSUE THREAD

**Issue by teixeirajpf** [microsoft/vscode#103649] opened 2020-07-30 17:51 UTC
- VSCode Version: 1.47 - June2020
- OS Version: Manjaro Linux 4.14

Steps to Reproduce:

Since its first auto-install :
1. Open VScode either via terminal or menu and it opens without an issue
2. Go for changing directory via File->Open Folder
3. It "hangs" for a few seconds and the editor crashes.

I have been working around it by uninstalling and reverting to version code-stable-1592429541 (May2020, v1.46, I believe). However, this does not sufficientely solve my issue as, even with all the update settings (on the menu) disabled (both vsc and extensions), it always manages to auto-update after I turn off the computer.

Thanks in advance.
João

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment] 2020-07-30 17:55
Are you using snap package?

Looks like duplicate of #100940

**Comment by teixeirajpf** [comment] 2020-07-30 18:05
Yes, originally used the snap package (the Jan2020 package if not mistaken, and now the May2020 revert). 
Now it just auto-updates.

The system's the package updater doesn't ask me for any update for vscode, nor have I done any system update check in the meantime. 

About #100940, from what I gathered it seems to differ. I'm not trying to update at all about now. I just want to have a stable editor, so I stay clear from the update options.

**Comment by IllusionMH** [comment] 2020-07-30 18:13
> About #100940, from what I gathered it seems to differ. 

Could you specify then how it's different?
Looking on your description - v1.47 crashes when native "Open Folder" is called, same as described in #100940, and 1.46 doesn't crash.

Or this is issue not about crash but updates?

**Comment by teixeirajpf** [comment] 2020-07-30 20:16
I may be in the wrong here, but I feel that "Open Folder" vs "Go to Help -> Check for Updates..." or "Help -> About" are quite different features that one may try to use. Hence, the differing behaviour towards #100940 I mentioned.

**Comment by IllusionMH** [comment] 2020-07-30 20:37
/duplicate

> Snap crashes when **native dialogs open**

Title was updated to reflect that it will crash on any native dialog. As well as confirmed in comments below for Open Folder action as well.

While that issue is worked on you can stay on 1.46 or if you need latest features - try workaround suggested in https://github.com/microsoft/vscode/issues/100940#issuecomment-651225395

**Closed** 2020-07-30 20:38 UTC
Labels: *duplicate
