### ISSUE TITLE
Extension Management View

### ISSUE THREAD

**Issue by prasannavl** [Microsoft/vscode#423] opened 2015-11-21 20:15 UTC
Add a view for extension management like Atom with detailed lists, extension download / update progress.

**Comment by DickvdBrink** [comment] 2015-11-30 14:37
Kinda like #637 (this one was earlier though ;))

**Comment by andrew-w-ross** [comment] 2015-12-04 10:49
+1 this is really needed

**Comment by joaomoreno** [comment] 2016-03-30 13:14
Treating this as duplicate of #637. Sorry for closing this earlier one.

**Closed by joaomoreno** 2016-03-30 13:14 UTC
Labels: feature-request
