### ISSUE TITLE
Ctrl+Tab behavior not working as expected on Linux

### ISSUE THREAD

**Issue by tobico** [Microsoft/vscode#26176] opened 2017-05-08 01:50 UTC
- VSCode Version: 1.12.1
- OS Version: Linux Mint 18.1 Serena (based on Ubuntu 16.04.4)

Steps to Reproduce:

1. Hold Ctrl and press Tab to display list of recent files and select the last open file
2. Release the Tab key

Expected behavior:

The file list closes, and the editor switches to the selected file in the list, which is the previously open file.

Actual behavior:

The list remains open. Editor does not close the list until and open the selected file until the Enter key is pressed.

Notes:

I've tested this with the same version of Code on both Linux and Windows, and the incorrect behavior only seems to occur under Linux.

Screenshot:

![ctrl-tab-switcher](https://cloud.githubusercontent.com/assets/125108/25787401/67fc188c-33e4-11e7-9cd7-3610ee8754fe.png)

**Comment by rmunn** [comment] 2017-05-08 06:55
I can't reproduce this. I'm also on Linux Mint 18.1 Serena, using VS Code 1.12.1, but for me, the active tab switches as soon as I release the Ctrl key. I can hit Ctrl+Tab, then release Ctrl right away, to switch to the previously-open editor tab, or I can hold down Ctrl while I continue to hit Tab to cycle through the tabs, then release Ctrl when I reach the one I want. Either way, as soon as I release Ctrl the tab opens immediately, which is the expected behavior -- I don't have to press Enter at all.

What extensions do you have installed? It's possible that one of them may be interfering with Ctrl+Tab somehow. The extensions I have installed, on my Linux Mint 18.1 system where Ctrl+Tab is working as expected, are:


|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-Paket|Ionide|1.6.3|
|Ionide-fsharp|Ionide|2.25.11|
|Bookmarks|alefragnani|0.14.1|
|python|donjayamanne|0.6.4|
|json-tools|eriklynd|1.0.2|
|php-intellisense|felixfbecker|1.2.1|
|csharp|ms-vscode|1.9.0|
|mono-debug|ms-vscode|0.15.5|
|vscode-icons|robertohuertasm|7.6.0|
|Align|steve8708|0.2.0|

**Comment by tobico** [comment] 2017-05-08 07:29
@rmunn just investigated this some more, and was able to see the issue with all extensions disabled.

It looks like this is specifically an issue with using the Caps Lock key as an additional Control key with that setting in Keyboard Layout Options enabled. If I use my regular Control key the editor behaves as expected.

![capslock](https://cloud.githubusercontent.com/assets/125108/25794338/c1701844-3413-11e7-861b-0618ee5eb3dc.png)

**Comment by DasJott** [comment] 2017-05-08 12:56
For me, ctrl+tab simply does nothing. Using playin 16.04 Ubuntu here.

**Comment by Tyriar** [comment] 2017-05-08 20:31
Moving to @alexandrudima as it's related to keybindings, it might be a problem with the keyboard layout sending the caps lock ctrl a little differently to regular ctrl?

**Comment by alexandrudima** [comment] 2017-05-08 21:26
Let's track in #23991

**Closed by alexandrudima** 2017-05-08 21:26 UTC
Labels: keybindings
