### ISSUE TITLE
Linux: VS Code needs to be restarted before Emmet preferences take effect

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8457] opened 2016-06-28 22:10 UTC
#8207

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to Reproduce:

1. Add to settings:

  ```json
  "emmet.syntaxProfiles": {
    "html": {
      "attr_case": "upper"
    }
  }
  ```
2. Open HTML editor
3. Type `.foo` and press <kbd>tab</kbd> to expand, the setting doesn't apply
4. Reload the window and repeat 2-3, the setting doesn't apply

I needed to do a full restart to get the settings to take effect.

**Comment by mrmlnc** [comment] 2016-06-29 14:53
I can't reproduce this on Windows 10 with version based on 798b41ab1cf3636a27042020a54ddfb4cfb8d23c.

**Comment by egamma** [comment] 2016-06-29 18:21
I cannot reproduce it neither on OS X. Please reopen when you still the issue in your setup.

**Comment by Tyriar** [comment] 2016-06-29 18:35
Definitely happening on Ubuntu 16.04:


Version 1.3.0-insider
Commit 798b41ab1cf3636a27042020a54ddfb4cfb8d23c
Date 2016-06-29T05:14:50.570Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by mrmlnc** [comment] 2016-06-29 21:07
I cannot reproduce it on Manjaro 16 and Ubuntu 16.04 LTS. But I found a problem with cancelling settings.

Steps to Reproduce:

  1. Open VS Code
  2. Add to settings:

  ```json
  "emmet.syntaxProfiles": {
    "html": {
      "attr_case": "upper"
    }
  }
  ```

  3. Type `.foo` and press <kbd>tab</kbd> to expand. Settings are applied. Result: `<div CLASS="test"></div>`
  4. Delete added settings.
  5. Type `.foo` and press <kbd>tab</kbd> to expand, the setting doesn't apply. Result: `<div CLASS="test"></div>`

![2016-06-30_00-06-28](https://cloud.githubusercontent.com/assets/7034281/16468879/b13e7cbc-3e56-11e6-8494-672f606e09ec.gif)

**Comment by mrmlnc** [comment] 2016-06-29 22:41
@Tyriar, i did a PR that is guaranteed to apply Emmet preferences. Please, try on your machine.

**Comment by Tyriar** [comment] 2016-06-29 23:38
I believe this is actually due to https://github.com/Microsoft/vscode/issues/8547, not sure if your PR is still useful if so. I think a change was made to not watch symlinks.

**Comment by mrmlnc** [comment] 2016-06-30 00:13
@Tyriar, in any case, my PR corrects the situation with «freeze» settings profiles. Described above.

**Comment by egamma** [comment] 2016-06-30 07:10
This is not an emmet specific preference issue it is more general. I'll mark it as a duplicate of #8547. 
I'll still look into the preferences PR, I want to revisit the current code anyways.

**Closed by egamma** 2016-06-30 07:10 UTC
Labels: bug, duplicate, linux
