### ISSUE TITLE
Go To Symbol in workspace *folder*

### ISSUE THREAD

**Issue by 3v1n0** [Microsoft/vscode#67976] opened 2019-02-06 12:29 UTC
It's currently possible to navigate to a symbol in the whole workspace, but when the same symbol part is used multiple times in a sub-folder/project of a workspace, it's not easy to find it

Make possible to search for symbols only for a given workspace project, as it happens for building tasks, the project where to search should be used to filter the results.

**Comment by mjbvz** [comment] 2019-02-09 00:36
Duplicate of #17022

**Closed by mjbvz** 2019-02-09 00:36 UTC
