### ISSUE TITLE
Native titlebar render issue (white box then fills) on Ubuntu 18.04

### ISSUE THREAD

**Issue by sharksforarms** [microsoft/vscode#80798] opened 2019-09-12 12:37 UTC
- VSCode Version:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-1050-oem
```
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open VSCode and mouse hover over title bar, the box render will appear white then fill in 
2. This does NOT happen when I set `window.titleBarStyle` to `custom` (but I wish I could use native)
3. I have also tried `--disable-gpu` and same issue.

GIF:
![vscode-white](https://user-images.githubusercontent.com/10912917/64784589-70458580-d538-11e9-89da-82ce5a00f46f.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by charbelnicolas** [comment] 2020-03-11 23:00
This happens on Arch Linux and gnome 3.36 on nvidia's latest drivers 440.64 too. Is there a fix coming soon?

**Comment by kjeremy** [comment] 2020-03-16 18:29
I am seeing this too on a vmware system.

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic

**Comment by deepak1556** [comment] 2020-03-17 22:36
@charbelnicolas @kjeremy are you also seeing the issue even with hardware acceleration disabled https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration ?

**Comment by charbelnicolas** [comment] 2020-03-18 02:42
Yes, this happens with the "disable-hardware-acceleration": true as well as with --disable-gpu.

**Comment by sarbikbetal** [comment] 2020-03-19 09:43
Happens with me too on Ubuntu 19.10.

Version: 1.44.0-insider
Commit: 708b019bb4e20f07cf89df9f1d943af3d38d7a70
Date: 2020-03-18T05:46:17.067Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic


![vsc](https://user-images.githubusercontent.com/41508422/77053309-2e6c2f00-69f4-11ea-8fbf-e64322b04404.gif)

**Comment by raul75sh** [comment] 2020-03-19 23:11
Ubuntu 18.04.4 LTS
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:17:38.324Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-40-generic
![issue-2020-03-19_18 07 13](https://user-images.githubusercontent.com/47665483/77122983-f3c2c080-6a0c-11ea-86d8-b6b251953ca4.gif)

**Comment by deepak1556** [comment] 2020-03-31 20:39
Upstream issue https://github.com/electron/electron/issues/18184

**Comment by greenday2** [comment] 2020-05-04 06:49
have the same behaviour on xubuntu 20.04

**Comment by rafalagoon** [comment] 2020-05-09 17:37
There is no workaround? It makes VSCode so hard to use in Linux...

**Comment by sharksforarms** [comment] 2020-05-09 20:48
> There is no workaround? It makes VSCode so hard to use in Linux...

If you set `window.titleBarStyle` to `custom` it seems to be better

**Comment by yankee14** [comment] 2020-05-12 20:04
Confirmed issue on Debian Testing:

```
$ uname -a
Linux ibn5100 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux

$ code --version
1.45.0
d69a79b73808559a91206d73d7717ff5f798f23c
x64
```

**Comment by ocumo** [comment] 2020-05-18 20:33
Same problem on xubuntu 18.04.
Context menus are affected as well. In this state, the program is extremely annoying to use.

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-101-generic

Setting `window.titleBarStyle` to `custom` seems to mitigate or avoid the bug. Still, I would like to be able to use the native option.

**Comment by sergiocntr** [comment] 2020-05-31 06:44
[mergin from #98837 
Same here
Debian 10 buster  LXDE as windows manager
Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

Last version without issue is 
1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
I switched to this for now.

Thanks  developers, code is amazing!

**Comment by superiums** [comment] 2020-06-14 02:45
same in Arch , xfce4.
not happen in my previous xubuntu 18.04.

**Comment by derekjhunt** [comment] 2020-06-24 17:07
The flash is still present in Ubuntu 20.04

> 1.46.1
> cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
> x64

Switching the Title Bar Style to custom does work for me. Thanks!

**Comment by dvdantunes** [comment] 2020-07-04 21:56
This flash is present also in Fedora 31

Some details:

``` 
- Fedora release 31 (Thirty One) x86_64
- GNOME Shell 3.34.5 - Adwaita-dark (GKT2/3)

- Visual Code:
  code-1.46.1-1592429042.el7.x86_64
  1.46.1
  cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
  x64
```

I also switched `Title bar style` to `custom` and it worked for me. Thanks you all!

**Comment by seichodev** [comment] 2020-07-06 10:46
-Pop!_OS 20.04 @ ThinkPad W541 w/ NVIDIA K2100M

Can confirm `"window.titleBarStyle": "custom"` fixed everything. Thank you!

**Comment by avemilia** [comment] 2020-08-07 07:53
Additionally, when vscode is using the whole screen space (i.e. launched as the only application on a virtual desktop in the environment like i3wm) it segfaults. Changing titleBarStyle fixes it. Coredump attached, but I don't have debug symbols, so I guess it's pretty useless.

```
           PID: 1564525 (code)
           UID: 1000 (ave)
           GID: 1000 (ave)
        Signal: 11 (SEGV)
     Timestamp: Fri 2020-08-07 09:37:38 CEST (9min ago)
  Command Line: /opt/visual-studio-code/code --no-sandbox
    Executable: /opt/visual-studio-code/code
 Control Group: /user.slice/user-1000.slice/session-21.scope
          Unit: session-21.scope
         Slice: user-1000.slice
       Session: 21
     Owner UID: 1000 (ave)
       Boot ID: 9eb8c3fef1ab49389112b1d4068e434a
    Machine ID: c20fc4ed4ae14930ac57ea11927f6dfd
      Hostname: ave-pc
       Storage: /var/lib/systemd/coredump/core.code.1000.9eb8c3fef1ab49389112b1d4068e434a.1564525.1596785858000000000000.lz4
       Message: Process 1564525 (code) of user 1000 dumped core.
                
                Stack trace of thread 1564525:
                #0  0x0000559b003f68d8 n/a (code + 0x17f08d8)
                #1  0x0000559b020dd9e5 n/a (code + 0x34d79e5)
                #2  0x0000559b020dd56e n/a (code + 0x34d756e)
                #3  0x0000559b020a0567 n/a (code + 0x349a567)
                #4  0x00007fab2fa0143c g_main_context_dispatch (libglib-2.0.so.0 + 0x5243c)
                #5  0x00007fab2fa4f1d9 n/a (libglib-2.0.so.0 + 0xa01d9)
                #6  0x00007fab2fa00221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                #7  0x0000559b02098042 n/a (code + 0x3492042)
                #8  0x0000559b020de5a9 n/a (code + 0x34d85a9)
                #9  0x0000559b020b35e7 n/a (code + 0x34ad5e7)
                #10 0x0000559b00cf7fe3 n/a (code + 0x20f1fe3)
                #11 0x0000559b00cf9662 n/a (code + 0x20f3662)
                #12 0x0000559b00cf52d2 n/a (code + 0x20ef2d2)
                #13 0x0000559b00bec341 n/a (code + 0x1fe6341)
                #14 0x0000559b00bebf26 n/a (code + 0x1fe5f26)
                #15 0x0000559b0364dd9c n/a (code + 0x4a47d9c)
                #16 0x0000559b00bea5f1 n/a (code + 0x1fe45f1)
                #17 0x0000559b0022c27b n/a (code + 0x162627b)
                #18 0x00007fab2e4f4002 __libc_start_main (libc.so.6 + 0x27002)
                #19 0x0000559b0022c02a _start (code + 0x162602a)
                
                Stack trace of thread 1564589:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x0000559b021292f0 n/a (code + 0x35232f0)
                #2  0x0000559b02129a32 n/a (code + 0x3523a32)
                #3  0x0000559b020e9388 n/a (code + 0x34e3388)
                #4  0x0000559b020e96a8 n/a (code + 0x34e36a8)
                #5  0x0000559b020e95c4 n/a (code + 0x34e35c4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564541:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x0000559b021292f0 n/a (code + 0x35232f0)
                #2  0x0000559b02129a32 n/a (code + 0x3523a32)
                #3  0x0000559b020e9388 n/a (code + 0x34e3388)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e95c4 n/a (code + 0x34e35c4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564588:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x0000559b021292f0 n/a (code + 0x35232f0)
                #2  0x0000559b02129a32 n/a (code + 0x3523a32)
                #3  0x0000559b020e9388 n/a (code + 0x34e3388)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e95c4 n/a (code + 0x34e35c4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564698:
                #0  0x00007fab2e5c771d syscall (libc.so.6 + 0xfa71d)
                #1  0x00007fab2fa49c9b g_cond_wait_until (libglib-2.0.so.0 + 0x9ac9b)
                #2  0x00007fab2f9d1803 n/a (libglib-2.0.so.0 + 0x22803)
                #3  0x00007fab2fa2dd5b n/a (libglib-2.0.so.0 + 0x7ed5b)
                #4  0x00007fab2fa29511 n/a (libglib-2.0.so.0 + 0x7a511)
                #5  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564526:
                #0  0x00007fab2e5c205f __poll (libc.so.6 + 0xf505f)
                #1  0x0000559b010347f2 n/a (code + 0x242e7f2)
                #2  0x0000559b02133b75 n/a (code + 0x352db75)
                #3  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564529:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x0000559b021292f0 n/a (code + 0x35232f0)
                #2  0x0000559b02129a32 n/a (code + 0x3523a32)
                #3  0x0000559b020e9388 n/a (code + 0x34e3388)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e95c4 n/a (code + 0x34e35c4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564533:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b0535b489 uv_cond_wait (code + 0x6755489)
                #2  0x0000559b052da238 n/a (code + 0x66d4238)
                #3  0x0000559b052d7fab n/a (code + 0x66d1fab)
                #4  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564537:
                #0  0x00007fab2e5c205f __poll (libc.so.6 + 0xf505f)
                #1  0x00007fab2fa4f168 n/a (libglib-2.0.so.0 + 0xa0168)
                #2  0x00007fab2f9ffc03 g_main_loop_run (libglib-2.0.so.0 + 0x50c03)
                #3  0x00007fab2f8f51a8 n/a (libgio-2.0.so.0 + 0x1001a8)
                #4  0x00007fab2fa29511 n/a (libglib-2.0.so.0 + 0x7a511)
                #5  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564540:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x0000559b021292f0 n/a (code + 0x35232f0)
                #2  0x0000559b02129a32 n/a (code + 0x3523a32)
                #3  0x0000559b020e9388 n/a (code + 0x34e3388)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e95c4 n/a (code + 0x34e35c4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564528:
                #0  0x00007fab2e5ccf3e epoll_wait (libc.so.6 + 0xfff3e)
                #1  0x0000559b021cba1b n/a (code + 0x35c5a1b)
                #2  0x0000559b021c9360 n/a (code + 0x35c3360)
                #3  0x0000559b02131ad9 n/a (code + 0x352bad9)
                #4  0x0000559b020de5a9 n/a (code + 0x34d85a9)
                #5  0x0000559b020b35e7 n/a (code + 0x34ad5e7)
                #6  0x0000559b020e1e37 n/a (code + 0x34dbe37)
                #7  0x0000559b020edbc0 n/a (code + 0x34e7bc0)
                #8  0x0000559b02133b75 n/a (code + 0x352db75)
                #9  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #10 0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564536:
                #0  0x00007fab2e5c205f __poll (libc.so.6 + 0xf505f)
                #1  0x00007fab2fa4f168 n/a (libglib-2.0.so.0 + 0xa0168)
                #2  0x00007fab2fa00221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                #3  0x00007fab2fa00272 n/a (libglib-2.0.so.0 + 0x51272)
                #4  0x00007fab2fa29511 n/a (libglib-2.0.so.0 + 0x7a511)
                #5  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564553:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b0535b489 uv_cond_wait (code + 0x6755489)
                #2  0x0000559b0534c3ca n/a (code + 0x67463ca)
                #3  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564534:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b0535b489 uv_cond_wait (code + 0x6755489)
                #2  0x0000559b052da238 n/a (code + 0x66d4238)
                #3  0x0000559b052d7fab n/a (code + 0x66d1fab)
                #4  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564545:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b021291b2 n/a (code + 0x35231b2)
                #2  0x0000559b0318925d n/a (code + 0x458325d)
                #3  0x0000559b02133b75 n/a (code + 0x352db75)
                #4  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564539:
                #0  0x00007fab2fb4e87c read (libpthread.so.0 + 0x1387c)
                #1  0x0000559b002ac4cf n/a (code + 0x16a64cf)
                #2  0x0000559b02133b75 n/a (code + 0x352db75)
                #3  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564542:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x0000559b021292f0 n/a (code + 0x35232f0)
                #2  0x0000559b02129a32 n/a (code + 0x3523a32)
                #3  0x0000559b020e9388 n/a (code + 0x34e3388)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e95c4 n/a (code + 0x34e35c4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564543:
                #0  0x00007fab2e5c44fb __select (libc.so.6 + 0xf74fb)
                #1  0x0000559b02092216 n/a (code + 0x348c216)
                #2  0x0000559b02133b75 n/a (code + 0x352db75)
                #3  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564538:
                #0  0x00007fab2e5ccf3e epoll_wait (libc.so.6 + 0xfff3e)
                #1  0x0000559b021cba1b n/a (code + 0x35c5a1b)
                #2  0x0000559b021c9360 n/a (code + 0x35c3360)
                #3  0x0000559b02131ad9 n/a (code + 0x352bad9)
                #4  0x0000559b020de5a9 n/a (code + 0x34d85a9)
                #5  0x0000559b020b35e7 n/a (code + 0x34ad5e7)
                #6  0x0000559b020edbc0 n/a (code + 0x34e7bc0)
                #7  0x0000559b02133b75 n/a (code + 0x352db75)
                #8  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #9  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564551:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b0535b489 uv_cond_wait (code + 0x6755489)
                #2  0x0000559b0534c3ca n/a (code + 0x67463ca)
                #3  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564550:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b0535b489 uv_cond_wait (code + 0x6755489)
                #2  0x0000559b0534c3ca n/a (code + 0x67463ca)
                #3  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564546:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b02129adb n/a (code + 0x3523adb)
                #2  0x0000559b0212979f n/a (code + 0x352379f)
                #3  0x0000559b02097d98 n/a (code + 0x3491d98)
                #4  0x0000559b020de5a9 n/a (code + 0x34d85a9)
                #5  0x0000559b020b35e7 n/a (code + 0x34ad5e7)
                #6  0x0000559b020edbc0 n/a (code + 0x34e7bc0)
                #7  0x0000559b02133b75 n/a (code + 0x352db75)
                #8  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #9  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564584:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b02129adb n/a (code + 0x3523adb)
                #2  0x0000559b0212979f n/a (code + 0x352379f)
                #3  0x0000559b020e937a n/a (code + 0x34e337a)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e95f4 n/a (code + 0x34e35f4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564532:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b0535b489 uv_cond_wait (code + 0x6755489)
                #2  0x0000559b052da238 n/a (code + 0x66d4238)
                #3  0x0000559b052d7fab n/a (code + 0x66d1fab)
                #4  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564555:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x00007fab1fb528a4 _ZN6spdlog7details16async_log_helper16process_next_msgEv (spdlog.node + 0x298a4)
                #2  0x00007fab1fb52d98 _ZN6spdlog7details16async_log_helper11worker_loopEv (spdlog.node + 0x29d98)
                #3  0x00007fab1fa1bf12 execute_native_thread_routine_compat (libstdc++.so.6 + 0xcff12)
                #4  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564552:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b0535b489 uv_cond_wait (code + 0x6755489)
                #2  0x0000559b0534c3ca n/a (code + 0x67463ca)
                #3  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564547:
                #0  0x00007fab2e5ccf3e epoll_wait (libc.so.6 + 0xfff3e)
                #1  0x0000559b00324d26 n/a (code + 0x171ed26)
                #2  0x0000559b003246c7 n/a (code + 0x171e6c7)
                #3  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564566:
                #0  0x00007fab2e5ccf3e epoll_wait (libc.so.6 + 0xfff3e)
                #1  0x0000559b021cba1b n/a (code + 0x35c5a1b)
                #2  0x0000559b021c9360 n/a (code + 0x35c3360)
                #3  0x0000559b02131ad9 n/a (code + 0x352bad9)
                #4  0x0000559b020de5a9 n/a (code + 0x34d85a9)
                #5  0x0000559b020b35e7 n/a (code + 0x34ad5e7)
                #6  0x0000559b020edbc0 n/a (code + 0x34e7bc0)
                #7  0x0000559b02133b75 n/a (code + 0x352db75)
                #8  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #9  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564531:
                #0  0x00007fab2e5ccd56 epoll_pwait (libc.so.6 + 0xffd56)
                #1  0x0000559b0535d7a4 n/a (code + 0x67577a4)
                #2  0x0000559b0534f971 uv_run (code + 0x6749971)
                #3  0x0000559b052da138 n/a (code + 0x66d4138)
                #4  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564530:
                #0  0x00007fab2e5ccf3e epoll_wait (libc.so.6 + 0xfff3e)
                #1  0x0000559b021cba1b n/a (code + 0x35c5a1b)
                #2  0x0000559b021c9360 n/a (code + 0x35c3360)
                #3  0x0000559b02131ad9 n/a (code + 0x352bad9)
                #4  0x0000559b020de5a9 n/a (code + 0x34d85a9)
                #5  0x0000559b020b35e7 n/a (code + 0x34ad5e7)
                #6  0x0000559b00cfec34 n/a (code + 0x20f8c34)
                #7  0x0000559b020edbc0 n/a (code + 0x34e7bc0)
                #8  0x0000559b02133b75 n/a (code + 0x352db75)
                #9  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #10 0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564544:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x0000559b021292f0 n/a (code + 0x35232f0)
                #2  0x0000559b02129a32 n/a (code + 0x3523a32)
                #3  0x0000559b020e9388 n/a (code + 0x34e3388)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e95c4 n/a (code + 0x34e35c4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564548:
                #0  0x00007fab2fb4ae32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x0000559b02129adb n/a (code + 0x3523adb)
                #2  0x0000559b0212979f n/a (code + 0x352379f)
                #3  0x0000559b020e937a n/a (code + 0x34e337a)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e9624 n/a (code + 0x34e3624)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564535:
                #0  0x00007fab2fb4d8f4 do_futex_wait.constprop.0 (libpthread.so.0 + 0x128f4)
                #1  0x00007fab2fb4d9f8 __new_sem_wait_slow.constprop.0 (libpthread.so.0 + 0x129f8)
                #2  0x0000559b0535b2e7 uv_sem_wait (code + 0x67552e7)
                #3  0x0000559b0531a632 n/a (code + 0x6714632)
                #4  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1564557:
                #0  0x00007fab2fb4b158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                #1  0x0000559b021292f0 n/a (code + 0x35232f0)
                #2  0x0000559b02129a32 n/a (code + 0x3523a32)
                #3  0x0000559b020e9388 n/a (code + 0x34e3388)
                #4  0x0000559b020e98fb n/a (code + 0x34e38fb)
                #5  0x0000559b020e95c4 n/a (code + 0x34e35c4)
                #6  0x0000559b02133b75 n/a (code + 0x352db75)
                #7  0x00007fab2fb44422 start_thread (libpthread.so.0 + 0x9422)
                #8  0x00007fab2e5ccbf3 __clone (libc.so.6 + 0xffbf3)
```
[core.code.1000.9eb8c3fef1ab49389112b1d4068e434a.1564525.1596785858000000000000.lz4.zip](https://github.com/microsoft/vscode/files/5040013/core.code.1000.9eb8c3fef1ab49389112b1d4068e434a.1564525.1596785858000000000000.lz4.zip)

**Comment by avemilia** [comment] 2020-09-11 07:36
As of 1.49.0 visual-studio-code-bin from AUR on Manjaro Linux 20.1 this bug is "fixed". No more flashing, just some delay with blanks until text comes up. Not ideal as there is noticeable delay before text comes on, but certainly better. This could have been fixed in an earlier version, this is just the version I'm retesting right now.

Also, vscode does no longer segfault when it's in fullsize window mode (the only window on virtual desktop in an environment like i3wm). However, there is still a problem that when it is in such mode, the titlebar buttons are not clickable. I will open a separate issue about it.

**Comment by ThomasLobker** [comment] 2020-09-11 08:49
For me the issue is completely fixed in the latest `1.49` version :tada:

**Comment by SkeLLLa** [comment] 2020-09-17 10:23
After update to 1.49 version on ubuntu 20 this issue appeared. No flashing, just all menus are white.

**Comment by straycoders** [comment] 2020-10-21 13:08
In my case, I found a workaround. Simply create or modify existing launcher with below command. Use any dark-theme (Adwaita-dark, Greybird-dark, etc) as the vscode theme.  I'm using Greybird-dark:

`env GTK_THEME=Greybird-dark /usr/share/code/code --unity-launch --disable-gpu %F`

For me, this solved issue #93869, and also works for `"window.titleBarStyle": "native"`

**Comment by drewm1980** [comment] 2020-11-27 09:55
Reproduced on 1.51.1 on Ubuntu 18.04.4

**Comment by 12gabriel3** [comment] 2021-03-01 15:54
Reproduced on VSCode 1.53 on Ubuntu 20.04
Setting `window.titleBarStyle` to `custom` fixed it

![bug](https://user-images.githubusercontent.com/16885097/109522350-f5a25a00-7a8c-11eb-8051-377226f8ee99.gif)

**Comment by deepak1556** [comment] 2022-12-12 15:26
Closing since native titlebar is rendered by the runtime and upstream issue has been closed.

**Closed by deepak1556** 2022-12-12 15:26 UTC
Labels: bug, upstream, linux, electron, titlebar, menus, upstream-issue-linked
