### ISSUE TITLE
Could not install typings files for JavaScript language features.

### ISSUE THREAD

**Issue by CyberiumShadow** [Microsoft/vscode#26538] opened 2017-05-12 09:06 UTC
Title says all, NPM is in path etc

- VSCode Version:  [](https://my.mixtape.moe/wwadfq.png)
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode via Start Menu or Desktop Icon
2. Receive said error

Turns out opening VSCode from Command Prompt or Powershell fixes this issue, but its a pain to have to open cmd or PS to do so.

**Comment by mjbvz** [comment] 2017-05-13 04:09
Duplicate of #24961  We're looking into a mitigation for VS Code 1.13 and also into moving away from requiring npm longer term

To help investigate your issue:
* Did you install npm using nvm or n?
* Can you also please run the `Developer: Toggle Developer Tools` command and then evaluate `process.env['PATH']` in the console and see if the correct path is included

Thanks

**Comment by CyberiumShadow** [comment] 2017-05-13 04:27
Hey there,

I installed npm directly using the binary installer for windows.

And yes I can confirm that the correct path is included

**Comment by mjbvz** [comment] 2017-05-31 06:56
See https://github.com/Microsoft/vscode/issues/24961#issuecomment-305040579

The latest insiders build adds a `typescript.npm` setting that you can use to tell VSCode where you have npm installed if it is not getting picked up correctly from your PATH.

Closing as duplicate of #24961

**Closed by mjbvz** 2017-05-31 06:56 UTC
Labels: duplicate, needs more info

**Comment by itashraffaheem** [comment] 2017-07-08 21:17
i install the node js and when i open the templete then i faced the same issue.
any one is there who help me.
