### ISSUE TITLE
VSCode takes ages to startup up on 16GB ram PC but starts in seconds on 8GB ram pc

### ISSUE THREAD

**Issue by CookieCrumbles** [Microsoft/vscode#67986] opened 2019-02-06 15:03 UTC
Issue Type: <b>Performance Issue</b>

* VSCode Version: 1.30.2

OS: | Windows 10 Enterprise  (64 bit)
Build: | 10.0.16299.904
Version: | 1709

Hardware specs:

Memory: | 8 GB
Processor: | Intel Core i5-8250U CPU @ 1.60GHz
Motherboard: | HP 83B2

So i have 2 cleans pc's with a basic configuration (portable version) of the latest VS code.
I have 2 identical computers a part from the amount of memory.
The computer with only 8GB of Ram opens VS Code in a matter of seconds whereas the powerful computer with 16 GB (same CPU and MOBO) takes minutes, 3 to 5 !

Is there a fix for this ? My main machines has 16 GB so this is an issue for me.
My older version 1.25 fires up in seconds on the 16GB machines so i'm using that as a "solution". But since i code mainly powershell i now can't update the PS extension.

Version:          Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)
Memory (System):  15.85GB (9.75GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    unavailable_software
                  checker_imaging:              disabled_off
                  flash_3d:                     unavailable_software
                  flash_stage3d:                unavailable_software
                  flash_stage3d_baseline:       unavailable_software
                  gpu_compositing:              unavailable_software
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                unavailable_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        enabled_readback
                  webgl2:                       unavailable_off

CPU %   Mem MB     PID  Process
    0      126   12652  code main
    0       10    1048     window (Visual Studio Code)
    0       66    6724     shared-process
    0       27   10176     utility
    0       10   11948     gpu-process
    0       72   13380     window (Issue Reporter)
    0      183   15184     window (Welcome - Visual Studio Code)
    0        8    7572       winpty-process
    0       10   10412         console-window-host (Windows internal process)
    0       79   14752         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0       16   12220       electron-crash-reporter
    0       72   13904       extensionHost

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.85GB (9.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	 12652	code main
    1	   151	  1048	   window (Welcome - Visual Studio Code)
    0	    69	 10844	     extensionHost
    1	    62	  4736	   window (Issue Reporter)
    0	    69	  6724	   shared-process
    0	    26	 10176	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by kieferrm** [comment] 2019-02-06 16:57
Can you pls collect a profile as described here: 
https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly. Thanks!

**Comment by jrieken** [comment] 2019-02-06 17:05
Also, on the slow machine, run `F1 > Startup Performance`. I show dev tools with some number, please paste them here

**Comment by CookieCrumbles** [comment] 2019-02-07 10:02
> Also, on the slow machine, run `F1 > Startup Performance`. It open dev tools and prints some numbers, please paste them here.

Startup Performance Measurement
workbench.main.js:5246 OS: win32(10.0.16299)
workbench.main.js:5246 CPUs: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz(8 x 1800)
workbench.main.js:5247 Memory(System): 15.85 GB(9.33GB free)
workbench.main.js:5247 Memory(Process): 199.21 MB working set(205.33MB peak, 171.05MB private, 51.81MB shared)
workbench.main.js:5247 VM(likelyhood): 0% 
workbench.main.js:5247 Initial Startup: true 
workbench.main.js:5247 Has 0 other windows
workbench.main.js:5247 Screen Reader Active: false 
workbench.main.js:5247 Empty Workspace: true 
workbench.main.js:5247 
workbench.main.js:5247 Extension Activation Stats
workbench.main.js:5248 
workbench.main.js:5248 Raw Startup Timers (CSV)
workbench.main.js:5248 Name	Start
main:started 	1549533639552 
main:appReady 	1549533639612 
nlsGeneration:start 	1549533639629 
nlsGeneration:end 	1549533639630 
willRequireSQLite 	1549533639898 
main:willInitGlobalStorage 	1549533639899 
didRequireSQLite 	1549533639910 
willSetupSQLiteSchema 	1549533639911 
didSetupSQLiteSchema 	1549533639912 
main:didInitGlobalStorage 	1549533639912 
main:loadWindow 	1549533640029 
renderer/started 	1549533660561 
willShowPartsSplash 	1549533660568 
willReadLocalStorage 	1549533660568 
didReadLocalStorage 	1549533660574 
didShowPartsSplash 	1549533660575 
willLoadWorkbenchMain 	1549533660598 
didLoadWorkbenchMain 	1549533661338 
main/startup 	1549533661339 
willInitWorkspaceService 	1549533661357 
willInitGlobalStorage 	1549533661357 
willCheckWorkspaceStorageExists 	1549533661360 
didInitWorkspaceService 	1549533661360 
didCheckWorkspaceStorageExists 	1549533661365 
willInitWorkspaceStorage 	1549533661365 
willRequireSQLite 	1549533661365 
didInitGlobalStorage 	1549533661366 
didRequireSQLite 	1549533661373 
willSetupSQLiteSchema 	1549533661376 
didSetupSQLiteSchema 	1549533661421 
didInitWorkspaceStorage 	1549533661422 
willStartWorkbench 	1549533661424 
willRestoreEditors 	1549533661531 
LifecyclePhase/Ready 	1549533661671 
didRestoreEditors 	1549533661735 
LifecyclePhase/Restored 	1549533661735 
didStartWorkbench 	1549533661743 
willLoadExtensions 	1549533661791 
LifecyclePhase/Eventually 	1549533663251 
extensionHostReady 	1549533663362 
didLoadExtensions 	1549533663367

**Comment by CookieCrumbles** [comment] 2019-02-07 10:05
> Can you pls collect a profile as described here:
> https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly. Thanks!

VS Code will start and create two profile-files in your home-directory. Please attach these files to your issue or create a new issue with these two files

Can you tell me the extension or possible name of these files? Can't seem to locate them.

**Comment by jrieken** [comment] 2019-02-07 10:52
Thanks for the info. This is /duplicate of #56644

**Closed** 2019-02-07 10:52 UTC
Labels: *duplicate, needs more info, perf

**Comment by CookieCrumbles** [comment] 2019-02-07 11:17
> Thanks for the info. This is /duplicate of #56644

So i took the time to do all that, you could be so kind to say what the issue or possible fix is tho.
I see that there is a possible fix by downloading VSCodeUserSetup. What exactly would i be installing with that?
