### ISSUE TITLE
git bash terminal is acting wierd in vscode

### ISSUE THREAD

**Issue by Tom89757** [microsoft/vscode#184719] opened 2023-06-09 12:18 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.80.0-insider (user setup)
Commit: db6bcdf309cc1565c502a54b73c33a63bdabfbd8
Date: 2023-06-09T05:21:13.157Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. install oh-my-zsh according to [install zsh windows git bash](https://gist.github.com/fworks/af4c896c9de47d827d4caa6fd7154b6b) with `plugins=(extract zsh-autosuggestions zsh-syntax-highlighting wd sudo z tldr)`. 
2. use [p10k theme](https://github.com/romkatv/powerlevel10k) as my zsh theme.
3. everything is ok when I open and use a git bash terminal prompt.
4. my git bash terminal is acting wierd when I use it as my vscode terminal. When I type some word, backspace, and retype some characters, it acts like below:
![image](https://github.com/microsoft/vscode/assets/44827483/e0643438-8c81-439b-a862-480ff6d931f6)
It's a bit similiar like [My terminal is acting weird in vs-code, there is a space between every character?](https://stackoverflow.com/questions/66910984/my-terminal-is-acting-weird-in-vs-code-there-is-a-space-between-every-character), but  different.

Thank you for your reply.

**Comment by SergioChizhikov** [comment] 2023-06-09 16:41
I see a similar problem when upgrading to version 1.79

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

Before (version 1.78.2 ):
![2023-06-09 19_21_56-template_main php - flagf - Visual Studio Code](https://github.com/microsoft/vscode/assets/57985484/a47fe268-80fc-44e5-b1ea-4a74bc9083b7)
After upgrade:

![2023-06-09 19_38_47-Release Notes_ 1 79 0 - flagf - Visual Studio Code](https://github.com/microsoft/vscode/assets/57985484/78f8b35f-58be-49c3-8863-63297857756e)

**Comment by Tom89757** [comment] 2023-06-13 14:11
disabling both   "terminal.integrated.shellIntegration.enabled" or   "terminal.integrated.shellIntegration.decorationsEnabled" or both does not work. Besides, using wsl2 (Ubuntu) with oh-my-zsh works.

**Comment by Tom89757** [comment] 2023-06-13 14:13
> does disabling shell integration fix it? `terminal.integrated.shellIntegration.enabled`

disabling both "terminal.integrated.shellIntegration.enabled" or "terminal.integrated.shellIntegration.decorationsEnabled" or both does not work. Besides, using wsl2 (Ubuntu) with oh-my-zsh works.

**Comment by Tom89757** [comment] 2023-06-13 14:27
new wierd actions. I keep typing `l` and `s`, some `[/?/`` appears. I keep typing `f`, cursor jumps to new line before line end.
![image](https://github.com/microsoft/vscode/assets/44827483/154a59ad-d038-480a-8ad2-99099d6803b2)

**Comment by meganrogge** [comment] 2023-06-14 16:13
does this reproduce in windows terminal?

**Comment by meganrogge** [comment] 2023-06-14 16:14
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-06-14 16:14 UTC
Labels: info-needed

**Comment by Tom89757** [comment] 2023-06-15 02:06
> does this reproduce in windows terminal?

Windows terminal means cmd or powershell? I don't know if powershell or cmd can install oh-my-zsh but I'll try.

**Comment by Tom89757** [comment] 2023-06-15 02:11
> > does this reproduce in windows terminal?
> 
> Windows terminal means cmd or powershell? I don't know if powershell or cmd can install oh-my-zsh but I'll try.

if you means wsl2, it works well.

**Comment by Tyriar** [comment] 2023-06-15 12:26
@Tom89757 there's a link to Windows Terminal in the comment above.

**Comment by Tom89757** [comment] 2023-06-15 15:57
> @Tom89757 there's a link to Windows Terminal in the comment above.

Thanks for your reply. I understand what you mean. I update my git from 2.33 to 2.41 and add it to windows terminal. It works well in terminal and also in vscode. It seems to be a git version issue.
