### ISSUE TITLE
Outline JSDoc @memberOf tag support

### ISSUE THREAD

**Issue by sunset-cf** [Microsoft/vscode#53717] opened 2018-07-06 14:07 UTC
Would it be possible for the Outline to detect the structure of a Javascript class through JSDoc tags such as '@class', '@memberOf', '@property', '@method', etc? If I paste in [this example](http://usejsdoc.org/tags-memberof.html) from Use JSDoc, the VSCode Outline ignores the JSDoc tags and only detects the methods.

```js
/** @class Observable */
create(
    'Observable',
    {
        /**
         * This will be a static member, Observable.cache.
         * @memberof Observable
         */
        cache: [],

        /**
         * This will be an instance member, Observable#publish.
         * @memberof Observable.prototype
         */
        publish: function(msg) {},

        /**
         * This will also be an instance member, Observable#save.
         * @memberof Observable#
         */
        save: function() {},

        /**
         * This will also be an instance member, Observable#end.
         * @memberof Observable
         * @instance
         */
        end: function() {}
    }
);
```

**Comment by mjbvz** [comment] 2018-07-06 21:02
Duplicate of https://github.com/Microsoft/TypeScript/issues/7237

IntelliSense also does not currently work properly for those jsdoc tags

**Closed by mjbvz** 2018-07-06 21:02 UTC
Labels: javascript
