### ISSUE TITLE
Custom file dialog: text typed gets removed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76084] opened 2019-06-25 10:41 UTC
![grid-tw](https://user-images.githubusercontent.com/900690/60092146-8bc59f00-9746-11e9-8de6-4c4afd2bc8c3.gif)

Setup:
* macOS
* type over "/"
* 🐛 text I type gets removed easily

**Comment by alexr00** [comment] 2019-07-11 10:46
I think this was fixed by since I cannot reproduce anymore 9b28638e8c7e6fefb458016342563f90c28fdfd2

**Closed by alexr00** 2019-07-11 10:46 UTC
Labels: bug, simple-file-dialog
