### ISSUE TITLE
ctrl+enter shortcut key is not working for git commit

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#89074] opened 2020-01-22 10:08 UTC
Issue Type: <b>Bug</b>

ctrl+enter shortcut key is not working for git commit.
this happend after vscode insiders update. i can see the keybiding for commit is set to "-".

VS Code version: Code - Insiders 1.42.0-insider (68615717819b3731705d92ec06b52edd47665291, 2020-01-22T05:31:57.634Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-64-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (3.51GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.6.1
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.97.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.19.0
debugger-for-chrome|msj|4.12.5
ng-template|Ang|0.900.4
atlascode|atl|2.3.1
jshint|dba|0.10.21
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
vscode-docker|ms-|0.9.0
anaconda-extension-pack|ms-|1.0.1
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
cordova-tools|msj|1.9.1
angular-console|nrw|10.0.0
vscode-xml|red|0.10.1
vscode-yaml|red|0.6.1
vscodeintellicode|Vis|1.2.4

</details>

**Comment by pdanpdan** [comment] 2020-01-22 11:18
It looks like `scm.acceptInput` processing is not working.
Maybe related to this: https://github.com/microsoft/vscode/commit/b5e9cb53874ea9bc22a395ab3499ed771604163b

**Comment by gjsjohnmurray** [comment] 2020-01-22 17:59
/duplicate of #89087, now closed, so should be fixed in tomorrow's build.

**Closed** 2020-01-22 17:59 UTC
Labels: *duplicate
