### ISSUE TITLE
Integrated git problems rename or delete branch with "

### ISSUE THREAD

**Issue by Adjilino** [microsoft/vscode#128657] opened 2021-07-14 13:55 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1 (Universal)
- OS Version: MacOS BigSur 11.4

Steps to Reproduce:

1. Create new branch via VS Code with **"**, for example: "new_branch"
2. When try to rename from **"new_branch"** to **new_branch** don't find the branch
3. To resolve I manually on terminal delete with git branch --delete --force \\"new_branch\\"
_The VS Code is not converting " to \\"_

**Comment by lszomoru** [comment] 2022-12-13 12:46
I am unable to reproduce this issue with the latest version of VS Code Insiders so I will go ahead and close this issue as resolved.
In case you are still able to reproduce this issue please feel free to reopen the issue. Thanks!

**Closed by lszomoru** 2022-12-13 12:46 UTC
Labels: bug, git

**Comment by Adjilino** [comment] 2022-12-14 19:14
@lszomoru I now this is just a minor issue. 
Is the VS Code Insiders version above of public one?

**Comment by lszomoru** [comment] 2022-12-15 07:58
@Adjilino, absolutely! You can download it from https://code.visualstudio.com/insiders/.

**Comment by Adjilino** [comment] 2022-12-15 14:34
I will try on that version. Anything I open a new issue and add some footage
