### ISSUE TITLE
Shell syntax highlight not work

### ISSUE THREAD

**Issue by jeynmann** [microsoft/vscode#219980] opened 2024-07-04 15:32 UTC
Type: <b>Bug</b>

Shell syntax highlight not works if using `<<` in `$(())`. It works for previous version, not sure for which.

e.g.
``` sh
x=$((1<<10))
```

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.6.12-200.fc39.x86_64
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (10.73GB free)|
|Process Argv|--crash-reporter-id 126facd6-1f01-4a1e-8c5a-4277a3a57b1d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mtr-vdi-309|
|OS|Linux x64 6.6.12-200.fc39.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (4 x 0)|
|Memory (System)|7.75GB (1.89GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 0)|
|Memory (System)|15.49GB (13.87GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
scala|sca|0.5.7
metals|sca|1.36.0
vscode-markdownlint|Dav|0.55.0
gitlens|eam|15.1.0
go|gol|0.41.4
jvm-bytecode-viewer|mnx|0.3.1
vscode-language-pack-zh-hans|MS-|1.91.2024070309
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
highlight-words|rsb|0.1.4
scala|sca|0.5.7
metals|sca|1.36.0
vscode-java-dependency|vsc|0.23.7
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by alexr00** [comment] 2024-07-04 16:09
Duplicate of the upstream issue https://github.com/jeff-hykin/better-shell-syntax/issues/93

**Closed by alexr00** 2024-07-04 16:09 UTC
Labels: new release
