### ISSUE TITLE
version 1.18 onwards requires DNS and online connectivity to install VSIX files

### ISSUE THREAD

**Issue by Mataris** [Microsoft/vscode#38827] opened 2017-11-21 01:16 UTC
- VSCode Version: 1.18.1
- OS Version: Windows 10 Enterprise Version 1703

Steps to Reproduce:

1.  Without an internet connection, attempt to install Powershell 1.5.1 vsix file either in Application or by running "code --install-extension "D:\installs\PowerShell-1.5.1.vsix"
2.  The following error occurs when going from command line:
Error: getaddrinfo EAI_AGAIN marketplace.visualstudio.com:443
    at Object.exports._errnoException (util.js:1050:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)

If you enter in a hosts file entry you get an error connecting.  I am using this in an environment with no internet connectivity capabilities.

If I downgrade to version 1.17.2 I am able to install the 1.5.1 Powershell extension fine.  This online check seems to be part of the new version

Reproduces without extensions: Yes

**Comment by ejheeres** [comment] 2017-11-22 09:10
I'm experiencing the same issue. We have administrative servers without an active internet connection. On previous versions i could manually update the plugins just fine, now it does not work anymore. Please fix this.

**Comment by joaomoreno** [comment] 2017-11-22 09:15
@sandy081 Notice that if we can't reach the Marketplace, the installation of a VSIX should still work.

**Comment by sandy081** [comment] 2017-11-22 09:35
Duplicate of #37973

**Closed** 2017-11-22 09:35 UTC
Labels: *duplicate, extensions, new release
