### ISSUE TITLE
Slow VS Code 1.63.2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by GeorgiKarapetrov** [microsoft/vscode#140482] opened 2022-01-11 08:29 UTC
Issue Type: <b>Performance Issue</b>

Any action VS Code has a noticeable lag, e.g. typing, opening a menu, deleting text, switching to another window or back to the VS Code window. The issue persists across application restarts and OS reboots. It first appeared a couple of weeks ago or so. I can't identify what changed when this issue appeared, possibly I could have updated to the current version.

Please, help. Please, let me know if I can provide any sort of debug log for you.

P.S. I already opened this issue yesterday, from another account which I deleted. I can't find the issue any longer. Pardon the duplication.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.10.0-1049-oem
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2897)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|15.38GB (0.43GB free)|
|Process Argv|--crash-reporter-id 408aa303-de17-42b9-8c3f-af6a8ca63b39|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|bspwm|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|bspwm|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   126	808840	code main
    0	    16	808843	   zygote
    0	   110	808876	     gpu-process
    0	    16	808844	   zygote
    0	     0	808846	     zygote
    0	    79	809649	       issue-reporter
    0	    32	808890	   utility-network-service
    0	   110	808923	   shared-process
    0	    47	809460	     ptyHost
    0	   110	809535	     watcherServiceParcelSharedProcess
    0	     0	829169	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	829170	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   158	809510	   window (Get Started - georgi.karapetrov - Visual Studio Code)
    0	    63	809543	   extensionHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Get Started - georgi.karapetrov - Visual Studio Code)
|      Error: Unable to collect workspace stats for folder /home/georgi.karapetrov (TypeError: t is not iterable);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30416617

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-01-11 08:54
Is #140427 your duplicate?

**Comment by HSadeghein** [comment] 2022-01-11 13:05
I have the same problem, and if I use its integrated terminal to log large text it will crash.

**Comment by tanhakabir** [comment] 2022-01-11 18:02
@HSadeghein if you don't mind I'll close this issue as a duplicate so all the changes can be tracked in the other issue.

Duplicate of #140427

**Closed by tanhakabir** 2022-01-11 18:02 UTC

**Comment by GeorgiKarapetrov** [comment] 2022-01-25 16:08
The other one is #140427
I don't mind either way.
