### ISSUE TITLE
Typescript: Organize Imports Treats Named Aliased Import as Un-used Dependency - removes it incorrectly

### ISSUE THREAD

**Issue by petermetz** [Microsoft/vscode#47596] opened 2018-04-10 16:24 UTC
- VSCode Version: Version 1.22.1 (1.22.1) 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd 2018-04-06T00:15:18.165Z
- OS Version: macOS High Sierra 10.13.4 (17E199)

Steps to Reproduce:

1. Issue a named import statement with the aliasing syntax such as this one below.  (this is the original one from my test case)

```typescript
import { Connection, ConnectionManager, createConnection as typeOrmConnectionFactoryMethod, getConnectionManager } from "typeorm";
```

2. Perform `Typescript: Organize Imports`
3. Observe that the `createConnection as typeOrmConnectionFactoryMethod` named import gets removed even though the `typeOrmConnectionFactoryMethod` method is referenced (invoked, to be exact) in your code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-04-10 17:26
Duplicate of #47310

**Closed by mjbvz** 2018-04-10 17:26 UTC
Labels: new release
