### ISSUE TITLE
crashing 

### ISSUE THREAD

**Issue by hevily** [Microsoft/vscode#34126] opened 2017-09-11 08:51 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
project-manager|ale|0.21.1
htmltagwrap|bra|0.0.3
python|don|0.7.0
autofilename|Jer|0.1.3
code-beautifier|mic|1.7.2
easy-less|mrc|1.4.5
sublime-keybindings|ms-|2.9.1
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.3
python|tht|0.2.3
html-snippets|wge|0.1.5
change-case|wma|1.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by patrys** [comment] 2017-09-11 09:43
This is a duplicate of #34128

**Closed** 2017-09-11 11:20 UTC
Labels: duplicate, new release
