### ISSUE TITLE
Squirrel automatically changes the bits while Code is running

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#20863] opened 2017-02-18 17:35 UTC
Every few days I get this message. I follow the steps and days later it is corrupt again.

- VSCode Version: 

![image](https://cloud.githubusercontent.com/assets/1202528/23095350/82f447c8-f5d6-11e6-9519-9afaea6e3262.png)

- OS Version: OSX 

![image](https://cloud.githubusercontent.com/assets/1202528/23095358/990f7320-f5d6-11e6-942d-b2fd466a43da.png)

Steps to Reproduce:

Difficult to reproduce. It happens every few days on insiders. Reporting as per chat with @waderyan and @chrisdias 

![image](https://cloud.githubusercontent.com/assets/1202528/23095346/70610f7e-f5d6-11e6-83a8-a15a4a5106db.png)

**Comment by chrisdias** [comment] 2017-02-18 17:37
What extensions do you have installed?

**Comment by johnpapa** [comment] 2017-02-18 17:40
![image](https://cloud.githubusercontent.com/assets/1202528/23095406/79955ac2-f5d7-11e6-93e2-d27ec7df0cc7.png)

**Comment by alexandrudima** [comment] 2017-02-22 20:59
@johnpapa Something is touching (editing) one of the following files:

```
	"checksums": {
		"vs/workbench/electron-browser/workbench.main.js": "p/oafswCsde1Ah5Azh7J8A",
		"vs/workbench/electron-browser/workbench.main.css": "ETkuj2b90jI0pDJgLwuazQ",
		"vs/workbench/electron-browser/bootstrap/index.html": "B2YnbpSsSnrsst5zD5yy4w",
		"vs/workbench/electron-browser/bootstrap/index.js": "t36wsZINwW0Vo2XnNHnpkQ"
	}
```

What we're doing:
* we read from `resources/app/product.json` the files that we should checksum and the expected checksum of the files at the time they were shipped.
* the checksum is a base64 encoded md5 hash of the file:
```js
let hash = crypto
			.createHash('md5')
			.update(buff)
			.digest('base64')
			.replace(/=+$/, '');
```
* we compute this ~10s after window startup
* if the computed value from the file on disk does not match the expected value we prompt (once per version. If you are on insiders this might mean once per day)

I believe there is something on your machine editing one of those 4 files (likely) or perhaps the auto-update fails somehow (unlikely)... When this happens, can you please save those 4 files somewhere else so we can have a look at their content and check if they've been edited somehow compared to the shipped versions?

**Comment by alexandrudima** [comment] 2017-03-24 14:10
We have been able to reproduce this. It appears that on OSX, when we show the update available pop-up, the underlying update mechanism already applies the update. That means that it is possible that we start up with version N, read the product.json from version N, and then 10s after startup we try to validate the files are OK, and we end up reading files from version N+1 (under the same path). 

This can have serious consequences, especially in cases when the main process is started at version N and a new window is opened with code from version N+1.

**Comment by bpasero** [comment] 2017-05-28 17:34
@joaomoreno you mentioned this no longer reproduces since we updated electron?

**Comment by joaomoreno** [comment] 2017-06-13 14:57
Yes I verified this is fixed with the latest Electron update.

**Comment by joaomoreno** [comment] 2020-05-06 08:31
This seems obsolete now.

**Closed** 2020-05-06 08:31 UTC
Labels: bug, install-update, mac
