### ISSUE TITLE
Unable to annotate the block code

### ISSUE THREAD

**Issue by a-little-boy** [Microsoft/vscode#41154] opened 2018-01-04 15:42 UTC
![2018-01-04 23-38-59](https://user-images.githubusercontent.com/27721311/34571167-c25c1b38-f1a8-11e7-800e-c76a30590d8d.png)

**Comment by a-little-boy** [comment] 2018-01-04 15:44
I use ctrl+/   and then it turns out to be like this

**Comment by mjbvz** [comment] 2018-01-04 21:13
Does this still repo if you disable all extensions?

**Comment by a-little-boy** [comment] 2018-01-05 02:09
@mjbvz thank you

**Comment by mjbvz** [comment] 2018-01-05 19:00
Did that fix the issue? Any idea what extension may have caused it?

**Comment by a-little-boy** [comment] 2018-01-06 01:38
@mjbvz    I delete all the extensions and restore the personal settings, then   it is ok

**Comment by mjbvz** [comment] 2018-01-09 19:01
Thanks. Closing as caused by extension

**Closed by mjbvz** 2018-01-09 19:01 UTC
Labels: javascript, needs more info
