### ISSUE TITLE
Stable to insiders smoke test: Can't restore remote repo

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#148188] opened 2022-04-26 17:44 UTC
Testing #147702

- Open [remote GH repo](https://github.com/bamurtaugh/python-tuples) in VS Code Stable through GitHub Repositories extension
- Launch VS Code Insiders with same Stable user-data-dir
- Prompted to sign into GH to use GH Repositories extension
- Directed to new browser tab to sign in. Accept prompt from browser tab to sign in and reopen VS Code Insiders.
- New VS Code Insiders instance opens, without the same user-data-dir (i.e. dark theme instead of user-data-dir's light theme). It doesn't open the repo. The first Insiders instance is stuck in a loading state.

First Insiders instance (with error after some time, `You have not yet finished authorizing this extension to use GitHub. Would you like to keep trying?`):

![image](https://user-images.githubusercontent.com/25310137/165360235-5eae1e59-b723-412b-8019-e6a4c0e4b3a8.png)

Second Insiders instance:
![image](https://user-images.githubusercontent.com/25310137/165360275-e207a680-6981-4999-bb1a-c19ac14a573e.png)

***

I closed the second Insiders instance and selected `Yes` from prompt in first Insiders instance to keep trying.

I'm redirected to this browser page:
![image](https://user-images.githubusercontent.com/25310137/165360579-98de46b8-75cf-4d36-82b1-7dada73f6b6d.png)

VS Code Insiders reloads and gets further as it shows the notebook top bar (i.e. Code, Markdown, and Run All buttons), but it now shows error: `Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`:
![image](https://user-images.githubusercontent.com/25310137/165360517-013ed380-6c75-4464-bd92-f050fec1bac2.png)

**Comment by bpasero** [comment] 2022-04-27 06:25
My speculation is that the protocol handler from the browser opens VSCode insiders by default, and not the instance that is already running. In other words:
* you run code with `--user-data-dir`
* a browser opens for login
* the protocol handler opens code
* a normal code instance launches without `--user-data-dir`

So at this point you have 2 instances running, the normal one with default user data dir and the one you had started.

On macOS I actually also see this happening but only when Code is already running.

Moving to auth/remote owners, but maybe we just close this as designed and accept this as a limitation of how protocol handlers work. I do not think there is a way to handle protocol links any different, because we just register them with the OS.

The last error with regards to the service worker seems already reported at https://github.com/microsoft/vscode/issues/148114

**Comment by bpasero** [comment] 2022-04-27 06:28
Actually the relevant code for registering Code to Windows seems to be this:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/platform/url/electron-main/electronUrlListener.ts#L54-L58

I am not suggesting to change this code, but we could probably detect the `--user-data-dir` argument and then register with different window parameters, but that might just ask for trouble.

@joaomoreno I think you added that a long time ago.

**Comment by TylerLeonhardt** [comment] 2022-04-27 22:16
I added a bunch of fallback logic in GitHub Auth this milestone which is why you see the "you are signed in and can close this page" window. You use to just end up in a bad state. I agree with @bpasero that this should be closed as "as designed" because I feel like users shouldn't really be using `--user-data-dir` unless for troubleshooting.... but that's my 2 cents.

**Comment by joaomoreno** [comment] 2022-04-28 12:02
> I am not suggesting to change this code, but we could probably detect the `--user-data-dir` argument and then register with different window parameters, but that might just ask for trouble.

Oh wow yeah good observation. But I'm also too afraid to change it at this point.

**Closed** 2022-12-06 21:33 UTC
Labels: remote, authentication, wont-fix
