### ISSUE TITLE
Broken action menu in insider

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#199556] opened 2023-11-29 15:25 UTC
Steps:
1. Right click in editor
2. Click on (...Refactor)
and this is what I see

![image](https://github.com/microsoft/vscode/assets/50770619/11fdd01c-1de6-4010-a1a6-6580706d9f74)

**Comment by justschen** [comment] 2023-11-29 17:02
duplicate of https://github.com/microsoft/vscode/issues/198881

however, i've been unable to reproduce. do you have a reliable repro for this?

**Comment by abhijit-chikane** [comment] 2023-11-29 18:20
Well I can reproduce it every time. But this I observed 3-4 days back in insider but I thought it's bug at my end but today after updating to the latest insider as well I was getting this issue.

**Comment by justschen** [comment] 2023-12-05 00:52
closing and tracking in https://github.com/microsoft/vscode/issues/198881

**Closed by justschen** 2023-12-05 00:52 UTC
Labels: bug, editor-code-actions
