### ISSUE TITLE
TS Server fatal error:  Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by cdimascio** [microsoft/vscode#133345] opened 2021-09-17 18:07 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.4.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:2064:20)
    at isNodeModulesOrScopedPackageDirectory (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:19715:65)
    at guessDirectorySymlink (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:19704:14)
    at processResolution (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:19692:22)
    at /home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:19683:162
    at Map.forEach (<anonymous>)
    at Object.setSymlinksFromResolutions (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:19683:123)
    at ConfiguredProject.Project.getSymlinkCache (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:161077:35)
    at Object.getSymlinkCache (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:114006:29)
    at Object.host.compilerHost.realpath (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:114071:36)
    at realPath (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:41680:42)
    at Object.resolveTypeReferenceDirective (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:41044:74)
    at /home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:162436:112
    at Object.map (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:455:29)
    at Function.AutoImportProviderProject.getRootFileNames (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:162436:42)
    at Function.AutoImportProviderProject.create (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:162468:38)
    at ConfiguredProject.Project.getPackageJsonAutoImportProvider (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:162270:77)
    at ConfiguredProject.Project.updateGraph (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:161693:26)
    at ConfiguredProject.updateGraph (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:162637:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:164361:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:165444:44)
    at /home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:165784:97
    at Object.flatMap (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:519:25)
    at ProjectService.applyChangesInOpenFiles (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:165784:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:166942:46)
    at /home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:168873:88
    at IOSession.Session.executeWithRequestId (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:168864:28)
    at IOSession.Session.executeCommand (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:168873:33)
    at IOSession.Session.onMessage (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:168899:35)
    at Interface.<anonymous> (/home/user.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js:171504:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No
Remote OS version: Linux x64 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_90134 --crash-reporter-id 0d402e30-ed3e-4911-bc79-2943a7cfa875|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: myuser.myhost.com|
|OS|Linux x64 |
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 3100)|
|Memory (System)|30.91GB (4.25GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.24
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-peacock|joh|3.9.1
dotenv|mik|1.0.1
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.10.0
code-settings-sync|Sha|3.4.3
ayu|tea|1.0.5
vscode-ruby|win|0.28.0
material-theme|zhu|3.11.4
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
java|red|0.82.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224cf:30367820
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by IllusionMH** [comment] 2021-09-17 18:34
/duplicate of https://github.com/microsoft/TypeScript/issues/44953

**Closed** 2021-09-17 18:34 UTC
Labels: *duplicate
