### ISSUE TITLE
[yaml] highlighting issue of single quotes in a value

### ISSUE THREAD

**Issue by JacobGunther12** [Microsoft/vscode#10746] opened 2016-08-20 17:15 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

When you put a ' symbol in a YML file variables, it will syntax color everything until it reaches another '. Usually this isn't an issue while doing double (''), but the game Minecraft recognizes the single ' as a ' and you don't have to put double '.

Steps to Reproduce:
1. Open a .YML file
2. Make a variable and include a ' in the value (examplevalue: This is an example's value)

**Comment by aeschli** [comment] 2016-08-29 07:05
@JacobGunther12 Can you add an example?
I tried this
```yaml
# An employee record
martin:
    name: Martin D'vloper
    job: Developer
    skill: Elite
```
and it seems to colorize fine

**Comment by JacobGunther12** [comment] 2016-08-29 07:14
Yes, @aeschli that is exactly what I mean. It turns out that it works differently on my MacBook. Possibly my MacBook updated VSCode and my PC didn't? By the way, I saw this in Minecraft YAML configuration, there must of been something that triggered a syntax error... Oh well :/

**Comment by aeschli** [comment] 2016-08-29 07:56
Do you have any extension installed that might replace the Yaml grammar?
Do you have a URL of the Minecraft Yaml file?

**Comment by JacobGunther12** [comment] 2016-08-29 12:59
@aeschli Nope, just a couple of extensions for PHP debug and C++ C# stuff that I might use in the future. The file I'm editing is on my PC.

**Comment by aeschli** [comment] 2016-09-07 19:45
Closing as I can't reproduce...

**Closed by aeschli** 2016-09-07 19:45 UTC
