### ISSUE TITLE
'surround selection with quotes' deletes last character on Mac / US Int. Layout

### ISSUE THREAD

**Issue by craPkit** [Microsoft/vscode#16648] opened 2016-12-06 13:43 UTC
- VSCode Version: 1.7.2
- OS Version: OS X El Capitan 10.11.6
- Keyboard: layout: US International

Steps to Reproduce:
1. Set the keyboard layout to US International 
2. Select any range in any editor.
3. Type single or double quotes " ' (once)
4. Finish the operation with any of [second quote | Esc | mouse click]

Symptom: Though the text wrapping operation works, a third quote will replace the last character of the selection.

**Comment by alexandrudima** [comment] 2016-12-08 16:34
Note: only reproduces on languages which have configured surround brackets (e.g. `.js`)

**Comment by craPkit** [comment] 2016-12-20 09:13
This works as expected on Windows (7) though.

**Comment by mmazzarolo** [comment] 2017-02-22 08:41
I'm still having the same issue, any hints on how to fix it? Is it still being worked on? Thank you :)

**Comment by mpguedes** [comment] 2017-03-05 14:15
Have same issue VS Code Version 1.10.1 (1.10.1) macOS Sierra 10.12.3

**Comment by alexandrudima** [comment] 2017-03-24 16:13
Since `'` and `"` are used for input building (composition) under the US Intl kb layout, we cannot distinguish the user intent after pressing a single `'`. e.g.:
* when wanting to insert `ç` one would type <kbd>'</kbd> and <kbd>c</kbd>
* when wanting to insert `'` one could type <kbd>'</kbd> and <kbd>'</kbd> (press it twice for example).

We receive the `'` typed immediately after the first keypress. This is needed in order to support other composition cases such as CJK languages.

With the fix for #15825, we now no longer do any smartness of surrounding character pairs, auto closing characters, etc. when inside a composition. In other words, selecting a block of text and typing <kbd>'</kbd> will now replace the block of text with `'`.

**Closed by alexandrudima** 2017-03-24 16:13 UTC
Labels: bug, editor-core, editor-input, keyboard-layout, mac
