### ISSUE TITLE
Suspension prompt box cannot change size

### ISSUE THREAD

**Issue by xiaok0928** [microsoft/vscode#81091] opened 2019-09-18 09:17 UTC
I have adjusted the font size of vscode. The content in the suspension prompt box is not fully displayed, and there is no way to change the size of the suspension prompt box.What should I do?
我调整了vscode的字体大小,悬浮提示框中的内容显示不全,也没有办法更改悬浮提示框的大小.要怎么处理?
![image](https://user-images.githubusercontent.com/22540410/65135252-309b0400-da38-11e9-9774-87079e826d42.png)

**Comment by IllusionMH** [comment] 2019-09-18 11:25
You should be able to click on Read more button ( `i` in circle at the end of suggestion) to see more info or press <kbd>Ctrl+Space</kbd> (of keybinding special to your OS)

**Comment by octref** [comment] 2019-09-18 21:03
Duplicate of #29126.

**Closed by octref** 2019-09-18 21:03 UTC
