### ISSUE TITLE
Autocomplete interrupts spread operators in Javascript

### ISSUE THREAD

**Issue by curxxx** [microsoft/vscode#130283] opened 2021-08-06 19:14 UTC
Issue Type: <b>Bug</b>

1. Open any javascript file

2. Attempt to use spread operator by typing something like:
`let arr = [...array]
`
3. After the first period in the spread operator, Visual Studio Code will bring up autocomplete and interrupt the developer, resulting in something like:
`let arr = [.React.React.array];
`
Unless the developer closes autocomplete after each period...

This never happened before the latest update. please undo whatever change brought this awful monstrosity of a UX issue upon us.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (1.61GB free)|
|Process Argv|-psn_0_53261 --crash-reporter-id 27b54582-e992-42c0-a0c2-50453d693540|
|Screen Reader|no|
|VM|13%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|1.10.2
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.12
beautify|Hoo|1.5.0
vscode-dashboard|kru|2.3.2
linecounter|lyz|0.2.7
es6-css-minify|olb|3.3.2
code-complexity-report-generator|sel|1.1.7
unique-window-colors|stu|1.0.51
html-preview-vscode|tht|0.2.5
highlight-matching-tag|vin|0.10.1
html-css-class-completion|Zig|1.20.0

</details>

**Comment by IllusionMH** [comment] 2021-08-06 19:39
/duplicate of #130096

See comments there for possible workarounds.

**Closed** 2021-08-06 19:40 UTC
Labels: *duplicate, new release
