### ISSUE TITLE
Application icon shows the original one from the Electron framework.

### ISSUE THREAD

**Issue by fabiopolimeni** [Microsoft/vscode#36781] opened 2017-10-23 21:58 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (c1be82537d9fda852a258851f48ea78b7fc8a7a3, 2017-10-23T04:18:13.902Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
python|don|0.7.0
xml|Dot|1.9.2
gitlens|eam|5.7.1
beautify|Hoo|1.1.1
node-module-intellisense|lei|1.4.0
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.4.0
vscode-icons|rob|7.16.0
cmake|twx|0.0.17
unity-debug|Uni|1.2.1
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-23 22:16
Duplicate of #36665

**Closed by mjbvz** 2017-10-23 22:16 UTC
Labels: debug, duplicate
