### ISSUE TITLE
"alt+w "can't enable "Match Whole World" in terminal

### ISSUE THREAD

**Issue by StaringInfinity** [microsoft/vscode#186118] opened 2023-06-25 14:48 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: win

Steps to Reproduce:

1. Switch to terminal
2. Press Ctrl + F
3. Press Alt+w, it enables "Match case" instead of "Match whole word". Alt + R can't work either
![image](https://github.com/microsoft/vscode/assets/49320365/05f02d3f-4e82-4b40-8870-07bbedaf315c)

**Comment by jeanp413** [comment] 2023-07-13 02:06
Already fixed in insiders https://github.com/microsoft/vscode/pull/186665, duplicate of https://github.com/microsoft/vscode/issues/186375

**Closed** 2023-07-13 16:54 UTC
Labels: bug, terminal-find
