### ISSUE TITLE
Doesn't save file in diff-view when sudo is needed

### ISSUE THREAD

**Issue by hansu** [microsoft/vscode#121539] opened 2021-04-17 08:24 UTC
Assume comparing two files that you could only access via sudo.
If I  make a change inside the diff view to one file and then save it, vscode correctly notifies my "Failed to save ... insufficient permissions" and offers me to "Retry as Sudo". If I select this it doesn't saves the changes.

See also  [**this**](https://user-images.githubusercontent.com/67957916/115106777-e5740a80-9f66-11eb-8f9d-d082ce40f2e1.gif) screen record.

**Comment by hansu** [comment] 2021-04-17 09:55
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [linux system vscode save file (#120216)](https://www.github.com/microsoft/vscode/issues/120216)

No, the mentioned issue is a feature request, doesn't treat this bug.

**Comment by bpasero** [comment] 2021-04-18 10:15
Hm, I am not able to reproduce this, I wonder if you are on the latest version?

**Comment by hansu** [comment] 2021-04-18 11:33
I installed the latest nightly build version. The same behaviour.

It seems only to happen when comparing files with the same name.
Steps to reproduce: 
1. Create a file in e.g. /usr/share.
2. Copy this file to a sub folder.
3. Open vscode and add the files and compare them.
4. Add something and save. Sometimes this happens only on the second insertion and saving.


![vscode_diff_save_sudo_2](https://user-images.githubusercontent.com/67957916/115143802-b7b3c200-a049-11eb-8c4d-6b3512763eb2.gif)

Another thing that's maybe related to this:   
Assume opening two files in directory which needs sudo. Then compare and save. Although there are no changes, vscode marks both a changed and needs the sudo password for each file.
Not sure if this is intended. ([vscode_diff_save_unchanged_sudo.gif](https://user-images.githubusercontent.com/67957916/115143946-43c5e980-a04a-11eb-8d64-16d340721c6f.gif))

**Comment by bpasero** [comment] 2021-04-19 04:36
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by hansu** [comment] 2021-04-19 06:24
I ran it with extensions disabled and deleted also my settings.json. But still there. I tested on a Debian 10 and on an Ubuntu 18.
You still can't reproduce this?

**Comment by hansu** [comment] 2021-04-19 06:50
In this context something related to Settings Sync showed up.
When I deleted the settings.json it was directly synced. So on the machine this file was also synced, so it was empty. Ok up to here.
But the diff isn't correct I think. The entry "Settings 15 mins ago" is showing no difference ([screenshot](https://user-images.githubusercontent.com/67957916/115193149-10d43200-a0ec-11eb-945a-53e37e89d861.png)). The action where the settings were deleted are shown as "6 days ago" ([screenshot](https://user-images.githubusercontent.com/67957916/115193232-2ba6a680-a0ec-11eb-9193-e8562b57f6b7.png)). But that should definitely go into the change 15 mins ago. I definitely had the full settings.json yesterday. Should I raise this as a bug as this feature is just experimental?

**Comment by bpasero** [comment] 2021-04-19 06:58
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by hansu** [comment] 2021-04-19 07:11
Unfortunately that didn't change anything.

Does your file also have this permissions?
`-rw-r--r-- 1 root root 9 Apr 19 09:07 testfile`

**Comment by bpasero** [comment] 2021-04-19 07:19
Is this a Linux system?

**Comment by hansu** [comment] 2021-04-19 07:34
Yes, like I [mentioned](https://github.com/microsoft/vscode/issues/121539#issuecomment-822204280).

**Comment by bpasero** [comment] 2021-04-19 16:15
Maybe this needs more accurate steps, here is what I tried in the video below:
* open an empty insiders vscode on ubuntu 20
* open a `/etc/hosts` file
* open a `~/Desktop/hosts` file
* change the `/etc/hosts` file
* File > Save

This seems to work even after the second time.

![recording](https://user-images.githubusercontent.com/900690/115268999-291f6d80-a13b-11eb-8115-b647741342fa.gif)

**Comment by hansu** [comment] 2021-04-19 19:32
Yes that behaves on my system exactly like yours. But have you also tried when **both** files are in a directory that needs root permissions?

My steps:

1. open an empty insiders vscode on ubuntu 18
2. create a /usr/share/testfile
3. create a /usr/share/vscode-test/testfile
4. change one of the file
5. File > Save

**Comment by bpasero** [comment] 2021-04-20 08:00
Ok I can reproduce now, the thing is: saving a file from the menu is considered an explicit save which will try to save both the left hand and the right hand editor. It looks like the left hand editor does not properly go through the permission flow though and thus fails to save. Any editor that fails to save is then marked as dirty.

**Comment by hansu** [comment] 2021-04-20 08:12
And maybe the permission dialog for the second file doesn't show up because the file name is identical?
Compare to the behaviour when saving diff view of two different named files ([record](https://user-images.githubusercontent.com/67957916/115143946-43c5e980-a04a-11eb-8d64-16d340721c6f.gif)).
But why does it saves both sides even when there are no changes?

**Comment by bpasero** [comment] 2021-04-20 08:36
Yeah spot on, this is an issue with how we decide whether a notification is already showing:

https://github.com/microsoft/vscode/blob/6d468a59f694f9a13e968cce7d2fc75f38ea3447/src/vs/workbench/common/notifications.ts#L682-L702

**Comment by bpasero** [comment] 2021-04-20 09:42
via https://github.com/microsoft/vscode/commit/be6a9027041c6136dfdf2571fa7a5092cbbf31d2

**Closed by bpasero** 2021-04-20 09:42 UTC
Labels: bug, workbench-editors

**Comment by hansu** [comment] 2021-04-21 09:52
Thanks for immediately fixing it!

Another suggestion at this point: Could you also show the path when the filenames are identical?
If I want to save only one file in this case, I have to chance to select the chosen (the modified) one:
![Screenshot_2021-04-21_11-31-15](https://user-images.githubusercontent.com/67957916/115533869-787ab080-a297-11eb-93fc-35aabf6ff99e.png)

**Comment by hansu** [comment] 2021-04-23 05:53
@bpasero did you get a notification message about his?

**Comment by bpasero** [comment] 2021-04-23 06:11
I suggest to open a new issue on that matter 👍

**Comment by isidorn** [comment] 2021-04-30 15:16
@hansu can you please try https://code.visualstudio.com/insiders/ and let us know if this issue is fixed? Thanks!

**Comment by hansu** [comment] 2021-04-30 18:05
Yes this issue is fixed as mentioned in https://github.com/microsoft/vscode/issues/121539#issuecomment-823934863
