### ISSUE TITLE
New vscode icon is horrible

### ISSUE THREAD

**Issue by dcbrwn** [Microsoft/vscode#36767] opened 2017-10-23 17:37 UTC
- VSCode Version: 1.17.2
- OS Version: Win 10

Steps to Reproduce:

1. Install fresh VSCode
2. Suffer

Reproduces without extensions: Yes

Solution: Just use the old one. If the similarity to the visual studio icon is an issue, google "vscode icon" for tons of great alternatives as a source for inspiration.

P.S. Sorry guys, I know this issue is kinda silly but I couldn't resist: new icon looks terrible. Especially the color is bad.

**Comment by dcbrwn** [comment] 2017-10-23 17:38
Just in case I'm talking about this one:
![image](https://user-images.githubusercontent.com/12214069/31903828-16814270-b832-11e7-8dc1-cb33e28b8c72.png)

**Comment by mjbvz** [comment] 2017-10-23 17:51
Duplicate of #35783

**Closed by mjbvz** 2017-10-23 17:51 UTC
Labels: duplicate, new release
