### ISSUE TITLE
All kind of preview fail to load when VSCode is executed as administrator

### ISSUE THREAD

**Issue by yenlui** [microsoft/vscode#173859] opened 2023-02-08 18:47 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0
- OS Version: Windows 10

Steps to Reproduce:

1. Run VSCode as administrator
2. Click on preview button of `.md` file, or display extension description page, or some csv file preview tool (list goes on...)
3. Tab is empty/blank/no content

It seems that anything that use content preview fail to display/render.

Note 1 : DevTool also wont show up in Administrator.
Note 2 : I've tried both User and System VSCode Installation in case there were a difference.
Note 3 : I'm forced to run as administrator because of "group policies" ...

**Comment by mjbvz** [comment] 2023-02-09 00:32
Duplicate of #122951

**Closed by mjbvz** 2023-02-09 00:32 UTC
