### ISSUE TITLE
Cannot create a file or a folder in left pane.

### ISSUE THREAD

**Issue by tostca** [Microsoft/vscode#47937] opened 2018-04-16 07:36 UTC
Issue Type: <b>Bug</b>

Below steps was done on a VM with clean an installation and no extensions.

1. Create test folder 'TestScripts' on C:\.
2. On VS Code select **File** -> **Open Folder** and choose the folder you just created.
3. Right click in the left pane for the opened folder and try to create a file or a folder and nothing happens.

VS Code version: Code - Insiders 1.23.0-insider (dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b, 2018-04-16T05:17:45.591Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (16.02GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by GBarkhatov** [comment] 2018-04-16 07:42
Same here

**Comment by NateLing** [comment] 2018-04-16 07:53
Same here, macos

**Comment by fenglinzeng** [comment] 2018-04-16 08:24
same here, macOS

**Comment by perlun** [comment] 2018-04-16 09:48
Can also verify this on macOS, these buttons are now defunct. This is actually the first time I've been hit by a pretty critical bug in VSCode Insiders. ❤️ 

<img width="87" alt="image" src="https://user-images.githubusercontent.com/630613/38802209-7fecd24e-4174-11e8-997e-d39235d84faf.png">

**Comment by thomasmichaelwallace** [comment] 2018-04-16 10:44
Fixed in the latest build (update just came through).

Good work whoever did that ❤️

**Comment by perlun** [comment] 2018-04-16 11:58
Confirmed - 2227c70736ecaf2e1dd027be9fc6198d542a95ab works correctly for me.

**Comment by michaeldunnOMM** [comment] 2018-04-16 12:14
How do I get this latest build? I've checked for updates but nothing coming up.

**Comment by pharrisee** [comment] 2018-04-16 12:25
@michaeldunnOMM I simply downloaded the insiders release from the vscode website, works fine now.

**Comment by marvinhagemeister** [comment] 2018-04-16 12:27
@michaeldunnOMM Seems like the update is now live. Got an update notification right inside vscode.

**Comment by michaeldunnOMM** [comment] 2018-04-16 12:33
@marvinhagemeister @pharrissee Very odd. I've used the direct link on the site and same result (the version numbers are exactly the same as well). I'll just have to use the regular release of VSC for now.

**Comment by Tyriar** [comment] 2018-04-16 13:39
Should be fixed now, I just published the fix to the apt repo for Linux as well.

**Closed by Tyriar** 2018-04-16 13:39 UTC
Labels: bug, file-explorer, important

**Comment by icyJoseph** [comment] 2018-04-16 14:20
Still dead on Windows :( No update available.

**Comment by bpasero** [comment] 2018-04-17 04:56
@isidorn please check the builds next time you re-trigger insiders, it looks like the Windows 64 build failed. 

Everyone else it should get fixed today with our new regular insider builds, sorry for the trouble.

**Comment by isidorn** [comment] 2018-04-17 08:08
@bpasero will do, thanks.

**Comment by michaeldunnOMM** [comment] 2018-04-17 08:26
Windows version now updated and working great. Thanks, everyone.
