### ISSUE TITLE
There is a space character located between every character displayed in the termnal

### ISSUE THREAD

**Issue by DeveloperGY** [microsoft/vscode#120689] opened 2021-04-07 04:23 UTC
Issue Type: <b>Bug</b>

It started once I updated to the latest version of vscode, im using chromeOS's linux(beta) system or "crostini" 

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 5.4.88-12224-gf05236dbdecf

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|2.74GB (2.73GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 3afaf97a-49fa-42da-95ad-08e0a80f87be|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.1.0
vscode-pull-request-github|Git|0.25.0
cpptools|ms-|1.2.2
java|red|0.76.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30283811
openwslfolder:30282073
vsget980cf:30284046
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by IllusionMH** [comment] 2021-04-07 09:09
Sound like duplicate of #120004
Do you see same problem?

**Closed** 2021-04-07 16:08 UTC
Labels: *duplicate

**Comment by DeveloperGY** [comment] 2021-04-08 19:53
Yes, it is very similar to #120004
