### ISSUE TITLE
when will the menu can support switch theme or customizable ?

### ISSUE THREAD

**Issue by lizhuangs** [Microsoft/vscode#32940] opened 2017-08-22 09:45 UTC
like idea,subline text.change all the menu black or other.
now It looks incongruous.
Tks.

**Comment by Tyriar** [comment] 2017-08-22 18:52
Duplicate of https://github.com/Microsoft/vscode/issues/16363

**Closed by Tyriar** 2017-08-22 18:52 UTC
Labels: workbench

**Comment by lizhuangs** [comment] 2017-08-23 08:50
@Tyriar Is that any plan for this?Tks.

**Comment by Tyriar** [comment] 2017-08-30 18:11
Not sure if we have access to this through [the platform](https://http://github.com/electron/electron) yet.
