### ISSUE TITLE
Ports are still forwarded when process is killed

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#180872] opened 2023-04-25 19:56 UTC
Testing #180696

I'm not clear on what unforwarding a port means so this maybe expected, but we do detect that the process is no longer running but it still appears in the list:

![image](https://user-images.githubusercontent.com/13199757/234388586-988fc7c1-5a6a-4a7f-a3be-81aaab84dfbe.png)

**Comment by alexr00** [comment] 2023-04-26 10:10
@karrtikr can you please provide the steps you used to get here? If `hybrid` port forwarding is properly set (setting `"remote.autoForwardPortsSource": "hybrid"` + reload) then yes, the port should be unforwarded and no longer appear in the list.

**Comment by karrtikr** [comment] 2023-04-26 16:33
```python
import socket

# Define the host and port to listen on
host = 'localhost'
port = 3000

# Create a socket object
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Bind the socket to the host and port
s.bind((host, port))

# Listen for incoming connections
s.listen(5)
print(f"[*] Listening on https://{host}:{port}")

# Accept incoming connections
while True:
    conn, addr = s.accept()
    print(f"[*] Connection from {addr[0]}:{addr[1]}")

    # Send a message to the connected client
    message = f"https://localhost:{port}"
    conn.sendall(message.encode())

    print(f"[*] Sent: {message}")

    # Close the connection
    conn.close()
```

Run the above Python script in integrated terminal when using Remote-SSH, it should start appearing in the list along with process ID under "Running process" column. Kill process using `kill <pid>` in a separate terminal.

**Comment by karrtikr** [comment] 2023-04-26 16:35
> If hybrid port forwarding is properly set (setting "remote.autoForwardPortsSource": "hybrid" + reload)

Confirming I made sure this was done as well.

**Comment by alexr00** [comment] 2023-04-27 07:36
Thank you for the steps!

**Comment by alexr00** [comment] 2023-04-27 10:08
When verifying, please test that the port is unforwarded with both `"remote.autoForwardPortsSource": "process"` and `"remote.autoForwardPortsSource": "hybrid"` are used.

**Comment by joyceerhl** [comment] 2023-04-28 16:21
The port is not unforwarded when `"remote.autoForwardPortsSource": "hybrid"` is used. It is however unforwarded when `"remote.autoForwardPortsSource": "process"` is used. I'm testing with the vscode-remote-try-node repo and the default launch config.

**Comment by karrtikr** [comment] 2023-04-28 23:17
The fix works for me though, with the original Python script I provided.

**Comment by alexr00** [comment] 2023-05-02 07:03
> The port is not unforwarded when `"remote.autoForwardPortsSource": "hybrid"` is used. It is however unforwarded when `"remote.autoForwardPortsSource": "process"` is used. I'm testing with the vscode-remote-try-node repo and the default launch config.

I'm not able to reproduce this. It's possible for what you describe to occur if the process is terminated before we have a chance notice that it's running. If you see this again can you please set the log level to debug, repro, and share logs from Remote Extension Host and Window?

Closing again for testing.

**Closed** 2023-05-02 08:38 UTC
Labels: bug, verification-found, remote-explorer

**Comment by rzhao271** [comment] 2023-05-02 18:34
I am unable to reproduce the issue with vscode-remote-try-node on Codespaces or Dev Containers, though it did take a bit longer for the port to close on Codespaces. Marking as verified.
