### ISSUE TITLE
Outline: Delay when outline is visible

### ISSUE THREAD

**Issue by chmielcode** [microsoft/vscode#98680] opened 2020-05-27 20:26 UTC
- VSCode Version: 1.45.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Open large (2k+ lines on my system) Python or JS file (those I can check)
2. Make sure Outline is visible and expanded in the sidebar
3. Type anything or hold backspace/delete button
4. Notice the delay (e.g. holding backspace will actually remove characters only when released)

Does this issue occur when all extensions are disabled?: No. There is no Outline without extensions.

I've first created an issue concerning the Python extension, but then figured out it wasn't related to that extension at all. Seeing code outline in the Sidebar is handy, so this is very inconvenient. Now I use breadcrumbs that provide similar information instantly, but do not cause the slowdown.
Expanding/folding Outline in the sidebar turns the problem on and off.

**Comment by IllusionMH** [comment] 2020-05-27 20:28
> There is no Outline without extensions.

For JS/TS Outline doesn't require any extensions installed. Are you sure this is built-in outline view and not old extension?

**Comment by mfmayer** [comment] 2020-05-28 04:42
I can experience the same delay while typing with the go plugin and while editing json files. When outline is collapsed the delay is gone. It also seems that the insiders version isn't affected (anymore?).

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by chmielcode** [comment] 2020-05-28 17:11
> 
> 
> > There is no Outline without extensions.
> 
> For JS/TS Outline doesn't require any extensions installed. Are you sure this is built-in outline view and not old extension?

Yes, the builtin one. I'm sorry, I opened a Python file with  --disable-extensions and made a wrong assumption about Outline's availability. Still with  --disable-extensions and a .js file (bokeh-api.js for example) opened the same happens. Collapsing Outline in the sidebar makes the huge delay go away immediately.

**Comment by jrieken** [comment] 2020-05-29 10:23
> Type anything or hold backspace/delete button

Esp. holding backspace shouldn't be an issue because outline requests are debounced (at the rate of average response time). Can you please craft a profile so that we can investigate. Do the following

1. F1 > Toggle Developer Tools
1. Select the Performance tab
1. Hit record
1. Reproduce the slowdown
1. Stop recording
1. Save the profile (the ⬇️-ish icon) and share it with us

**Comment by chmielcode** [comment] 2020-05-29 17:33
[Profile-20200529T192842.zip](https://github.com/microsoft/vscode/files/4703308/Profile-20200529T192842.zip)

@jrieken Recorded with --disable-extensions and bokeh-api.js file.

**Comment by jrieken** [comment] 2020-06-02 07:52
Thanks! Turns out this is a duplicate of https://github.com/microsoft/vscode/issues/96914 for which a fix exists already in Insiders. The June stable release (~10 days from today) will also have the fix

**Comment by jrieken** [comment] 2020-06-02 07:52
/duplicate of https://github.com/microsoft/vscode/issues/96914

**Closed** 2020-06-02 07:52 UTC
Labels: *duplicate, needs more info, outline
