### ISSUE TITLE
Broken character rendering

### ISSUE THREAD

**Issue by aleics** [Microsoft/vscode#44851] opened 2018-03-01 16:18 UTC
- VSCode Version: 1.20.1
- OS Version: Ubuntu 18.04 Bionic Beaver

Steps to Reproduce:

1. Open a document
2. Type something in a file

Does this issue occur when all extensions are disabled?: Yes

For the last two or three weeks I'm experiencing some kind of noisy rendering in vscode. Sadly, I can't really remember at which point this started. I've tried to uninstall vscode (and purge), disabling all the extensions, using different formats, etc. But this problem is still there. I attach you an screenshot:

![screenshot from 2018-03-01 17-03-38](https://user-images.githubusercontent.com/6661743/36855506-f45a195e-1d73-11e8-834c-cd00706d251a.png)

I'm just experiencing this on visual studio code. No other program, or text editor can reproduce this issue (tested in IntelliJ Idea, Netbeans, Vim, Firefox, gedit).

I can still work with the editor, but it has been a really annoying bug.

Maybe there's some kind of graphical dependency of the vscode that produces this issue. If so, could you please tell me which, and maybe I can use an older version of this.

Thanks.

**Comment by alexandrudima** [comment] 2018-03-02 09:44
Duplicate of #35675

**Closed by alexandrudima** 2018-03-02 09:44 UTC
Labels: editor, editor-core

**Comment by aleics** [comment] 2018-03-03 09:54
@alexandrudima thanks! couldn't find the issue ticket related to this.
