### ISSUE TITLE
Visual Studio Code PHP/HTML Intellisense Issue?

### ISSUE THREAD

**Issue by FeaRCODE** [Microsoft/vscode#2768] opened 2016-02-06 18:37 UTC
I have noticed when editing HTML files that Visual Studio does a very good job with auto complete; however, when I am using HTML within a PHP file, tags and tag attributes don't show up in the intellisense menu. Is this by design or something that was accidentally looked over?

Thanks,
Hunter Mitchell

**Comment by alexandrudima** [comment] 2016-02-08 21:02
fyi @aeschli

**Comment by aeschli** [comment] 2016-02-09 10:00
duplicate of #670

**Closed by aeschli** 2016-02-09 10:00 UTC
Labels: feature-request

**Comment by jhashailesh3108** [comment] 2017-11-15 19:25
I don't feel that anyone is interested in solving this issue in VS code. Please add this fix for next update.
