### ISSUE TITLE
Custom File Dialog doesn't handle clicks properly 

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#83597] opened 2019-10-29 23:18 UTC
Testing https://github.com/microsoft/vscode/issues/83296

Windows+FF

Use open file dialog with the mouse to navigate around.

🐛 => it doesn't navigate

**Comment by alexr00** [comment] 2019-10-30 08:52
Duplicate of https://github.com/microsoft/vscode/issues/83292

**Closed** 2019-10-30 08:52 UTC
Labels: *duplicate, bug, firefox, simple-file-dialog, web
