### ISSUE TITLE
Regular expression caused VSC to completely freeze (multiple installations are affected)

### ISSUE THREAD

**Issue by verschaevesiebe** [microsoft/vscode#111241] opened 2020-11-24 16:40 UTC
- VSCode Version: 1.51
- OS Version: 1909 OS Build 18363.1198 (Windows 10)

Steps to Reproduce:

1. Open a file which has a few lines of text or code. (Error for me happened with 1800 characters separated over 60 lines,  can occur with more or less as well.) 
2. Ctrl + F and turn on the **regex search**
3. Start typing into the searchbox the following (.*)+( ----)
4. This was just a small use case where I wanted to match all the lines ending with that " ----" but it ended up crashing VSC completely meaning nothing was clickable.
5. Cause could be the .* as it tries to match all which is asking for some performance. But I believe it should not be crashing your VSC. 
6. Having multiple instances open freeze all of them.

Does this issue occur when all extensions are disabled?: Yes

**Comment by msftrncs** [comment] 2021-01-16 05:03
Seeing this while looking for another regex based issue, on 1.52.1 this only locks up the window in which the search is triggered on, and the freeze occurs as soon as the closing `)` is entered, and I only tried a very small (maybe 200 character file).

Albeit, this regex is malformed...   you are asking for a 0 to unlimited length greedy group to be greedily repeated at least 1 time but as many times as possible.  I think what happens is that the engine in the process of failing on a line, backtracks down to where no characters match the `(.*)` and then sits there repeating the empty match indefinitely.  This is easily confirmed.  If all the lines in the file match the condition, the freeze does not occur.  I do consider that an engine failure, because the situation is easily detected and should technically be considered an error.  At least at run-time, a repeating quantifier should not be permitted to match a non-advancing condition.

If you use `(.*)( ----)` or even `.+ ----`, it seems to work fine.

**Comment by msftrncs** [comment] 2021-01-23 08:51
This appears to be similar to #30874 (original issue).

This is not a backtracking issue.   The issue is that the engine is failing to notice that it is not advancing, that it is repeating an empty match, and fail the pattern.

**Comment by verschaevesiebe** [comment] 2021-01-27 23:43
My computer has a 32cores and an RTX2080, unsure if that's considered a bad/slow computer 🗡️ 
It is still occurring but as you say'd I think this might indeed be an engine issue where it is just infinitely trying to match in a loop.

Shouldn't there be a catch for VSC to check whether you're looking for a regex and if it is freezing the process it kills the search instead? Because it looks inconvenient to just close the window all in one.  👍

**Comment by msftrncs** [comment] 2021-01-28 23:22
32 cores and a graphics card won't help.    Regex is a single thread task (at least in VS Code).

The regex you are requesting is bad performing.   When you ask regex to execute a poorly constructed expression, it results in poor performance.  Your sequence has a potential execution iteration of something like x! (factorial) where x is the number of characters on the line, for each line.  That means a 12 character line that doesn't end with ' ----' has nearly 500 million iterations (character combination comparisons), and that is assuming it is being broken down by line (due to `.` not matching `\n`) and I might have the math wrong, it might be 500 million squared, since you gave it a wrapping iterator.

I do think engines should (and I believe that some do) be able to detect poorly constructed expressions, or have time limit mechanisms available, and your example shows why; it is easy to create a poor expression.   

The problem here in VS Code is that VS Code and the regular expression in the find tool are in the same thread.  That said, I think that anywhere regex is made available to the user, it needs to be behind a safety net to keep the app responsive and the user in control, I am just not sure what options VS Code has here.

**Closed** 2021-10-12 23:29 UTC
Labels: *duplicate, editor-find
