### ISSUE TITLE
Feedback about preview WorkspaceEdit api

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#94593] opened 2020-04-07 09:29 UTC
Have a play at the preview WorkspaceEdit API, below are some feedbacks.

1. In the 1.44.0-insider, i didn't see the preview feature for rename operation even though i enabled `editor.rename.enablePreview` user setting. Tried both typescript and java, preview for renaming is not enabled.
2. Add "Check All"/"Uncheck All" buttons to select/unselect all edits. Currently i had to check one by one manually, not happy when there are many items in the tree.
3. Select all by default. Currently the api uses "needsConfirmation" flag to control whether to preview, but it unselects the item by default, can you keep it selected by default. IMO, the preview is just a quick preview of all the changes, and these changes are usually all needed to be applied at the end.
4. The diff view is not smart and cannot scroll for long changes. Cannot see the full change if it's long.
5. The api document for [WorkspaceEditEntryMetadata](https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2918) says `The editor groups edits with equal labels into tree nodes, for instance all edits labelled with "Changes in Strings" would be a tree node`. In my samples, all items have label with same word, but i don't see they are grouped to a same parent node.

![image](https://user-images.githubusercontent.com/14052197/78649658-531b3e80-78f0-11ea-9932-8c9eda0c88ed.png)

// @jrieken

**Comment by jrieken** [comment] 2020-04-07 09:38
> ried both typescript and java, preview for renaming is not enabled.

That setting is on by default and it will show a new entry in the rename input box, e.g Shift+Enter will rename with preview, Enter will just do it. Extensions cannot force a preview onto users except changes need confirmation

<img width="520" alt="image" src="https://user-images.githubusercontent.com/1794099/78653983-2f420380-78c4-11ea-937d-2da1ab2b99cb.png">

**Comment by jrieken** [comment] 2020-04-07 09:38
For all the other things, file separate issue for separate topic, include reproducible steps or a sample.

**Comment by testforstephen** [comment] 2020-04-07 09:48
My bad, the tooltip is grey, i didn't notice it. So what's the meaning of that user setting? Used to control whether to display "shift + enter" tooltip?

**Comment by jrieken** [comment] 2020-04-07 09:55
Yes, this allows to turn off the preview-button (this is mostly because c++ still rolls their own UI for this)

**Comment by testforstephen** [comment] 2020-04-07 09:56
i see. Maybe that user setting is not so intuitive. At first glance it looks like it's controlling whether to display preview ui.

**Comment by testforstephen** [comment] 2020-04-08 03:49
Please see new issue for the enhancement. https://github.com/microsoft/vscode/issues/94650

**Comment by jrieken** [comment] 2020-04-28 15:51
closing as dupe of #94650

**Closed by jrieken** 2020-04-28 15:51 UTC
Labels: needs more info
