### ISSUE TITLE
Enter key no longer works in the settings editor

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#52881] opened 2018-06-26 09:01 UTC
Version: 1.25.0-insider
Commit: 368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8
Date: 2018-06-26T05:18:29.183Z

Ubuntu 16.04

Open the classic settings editor, go to the user settings editor, try the enter a new line. Nothing happens, enter key is swallowed. any other key or `Ctrl + Enter` works

**Comment by sandy081** [comment] 2018-06-26 09:28
Duplicate of #52887

**Closed** 2018-06-26 09:28 UTC
Labels: *duplicate, settings-editor
