### ISSUE TITLE
cant preview images icon

### ISSUE THREAD

**Issue by klokoleva** [microsoft/vscode#128631] opened 2021-07-14 09:41 UTC
Issue Type: <b>Bug</b>

when i press ctrl+space, icon images not displayed

![image](https://user-images.githubusercontent.com/11715564/125600563-6add8146-8b79-44b9-8f7c-7dfc0c870910.png)

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

**Comment by misolori** [comment] 2021-07-16 16:03
This is a duplicate of https://github.com/microsoft/vscode/issues/119786

**Closed by misolori** 2021-07-16 16:03 UTC
Labels: needs more info, new release
