### ISSUE TITLE
Bug in extension tab

### ISSUE THREAD

**Issue by leslieeilsel** [Microsoft/vscode#57559] opened 2018-08-30 02:19 UTC
- VSCode Version:1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Windows 10 1803

Steps to Reproduce:
Please see this gif picture:
![error](http://m.qpic.cn/psb?/V12ol6gx2nrILn/p7Feg5GodB7Qp9RgH4F5zKNWCI0leDa2rYkOPmJEvPA!/b/dDEBAAAAAAAA&bo=jgFlAY4BZQECSW0!&rf=viewer_4&t=5)

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment] 2018-08-30 15:01
@leslieeilsel I am not able to reproduce it. Are there any steps?

**Comment by leslieeilsel** [comment] 2018-09-01 03:54
@sandy081 
- You can see vaguely that there are four numbers in the place where the problem occurs, 0010, which is the version number of the ‘Terminal’plugin. Maybe it has something to do with this.
- As for the specific steps, I tested it normal this morning, which is very strange. I think it may be related to using a widescreen display while I am working. So, you can put this question on hold and reply to you after I verify it.
- Sorry for my english.

**Comment by sandy081** [comment] 2018-09-03 13:11
@leslieeilsel Thanks for the response.

I would close it for now and wait for the steps to reproduce.

**Closed by sandy081** 2018-09-03 13:11 UTC
Labels: extensions, needs more info
