### ISSUE TITLE
Unable to Scroll Horizontally in Jupyter Notebook Using Shift + Mouse Wheel

### ISSUE THREAD

**Issue by IVSpretender** [microsoft/vscode#228808] opened 2024-09-17 09:30 UTC
![bug report](https://github.com/user-attachments/assets/76459ed6-92a1-4c27-9695-ef744e7d3f12)

# Bug details
Does this issue occur when all extensions are disabled?: Yes
- Avoiding ambiguity: In the current version of VScode (1.93.0-1.93.1), I am unable to ***use Shift + mouse wheel*** to scroll horizontally in Jupyter Notebook, but I can still achieve horizontal scrolling through other methods (such as dragging the scroll bar at the bottom of the cell).
- I was able to use Shift + mouse wheel to scroll horizontally in Jupyter Notebook in previous versions of VScode (1.92.2).
- In any versions of VScode, I can use Shift + mouse wheel to scroll horizontally in any text file (e.g., .py).

# Versions
- VS Code Version: 1.93.1 (system setup)
- OS Version: Windows_NT x64 10.0.19045

# Method to reproduce the bug
1. Create any `.ipynb` file, for example `test.ipynb`
2. Open `test.ipynb`
3. Add a Code cell and input code long enough until a scrollbar appears below the cell, for example 
```python
a = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
```
4. Hold down the Shift key on the keyboard and scroll the mouse wheel, you'll find that the code inside the cell doesn't scroll horizontally, this is a bug

**Comment by GBuenvar** [comment] 2024-09-18 10:41
I am experiencing the same issue

VS Code Version: 1.93.1
38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
x64
Fedora 40
Kernel: 6.10.9-200.fc40.x86_64

**Comment by DanielOstyn-Maas** [comment] 2024-09-24 21:25
Experiencing this also. What compounds the issue is that the horizontal scrollbar isn't always visible. For some reason when the top edge of a code cell is visible, the horizontal scrollbar disappears. 
As soon as I scroll down such that the top of the code cell is above the edge of my view, the scrollbar becomes visible again.

**Comment by amirrazmjoo** [comment] 2024-09-27 15:13
+1. Although everything works fine in other editor environments, I’ve recently encountered issues with the tab key not functioning properly for autocompletion in VS Code. I managed to resolve that problem, but this current issue still persists and is quite bothersome.

VS Code version: 1.93.1
Ubuntu 22.04

**Comment by janisshin** [comment] 2024-10-04 19:41
experiencing the same issue

Windows 11
VS Code version 1.93.1

**Comment by Harmxn02** [comment] 2024-10-16 12:55
I am also experiencing the same issue

VS Code version: 1.94.2
Windows 10 Version 22H2 (Build 19045.5011)

**Comment by seanmamasde** [comment] 2024-10-19 17:29
same

Version: 1.94.2
OS: Windows_NT x64 10.0.26120

**Comment by reesekneeland** [comment] 2024-10-22 14:59
I am also having the issue

Version: 1.94.2
OS: Windows 11

**Comment by rebornix** [comment] 2024-10-24 04:23
This is fixed in Insiders and will be available in next Stable.

**Closed by rebornix** 2024-10-24 04:23 UTC
Labels: bug
