### ISSUE TITLE
[0214/134412.467:ERROR:registration_protocol_win.cc(102)] CreateFile: The system cannot find the file specified. (0x2) - Again

### ISSUE THREAD

**Issue by TotallyInformation** [microsoft/vscode#116642] opened 2021-02-14 13:58 UTC
- VS Code Version: 1.53.0 (System Setup)
- OS Version: Windows 10 

Steps to Reproduce: 

1. Open more than one VScode instance with overlapping folders
2. Access a folder
3. `debug.log` file is created spuriously whenever a folder is accessed.

Does this issue occur when all extensions are disabled?: Yes

This problem has occurred previously but seems to have recently reappeared.

https://github.com/microsoft/vscode/issues/105191

Checking with LockHunter just shows that code.exe is locking the debug.log file.

**Comment by gjsjohnmurray** [comment] 2021-02-14 19:48
Please update to the current release, 1.53.2

**Comment by weinand** [comment] 2021-02-15 11:32
/duplicate of #115874

Fix already released in 1.53.2

**Closed** 2021-02-15 11:33 UTC
Labels: *duplicate

**Comment by TotallyInformation** [comment] 2021-02-15 11:41
Thanks. I can confirm that it doesn't happen in 1.53.2
