### ISSUE TITLE
Allow extensions to open editors in the background

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#22847] opened 2017-03-19 08:29 UTC
My extension opens new tab / page which i want to hide.
workbench.action.nextEditorInGroup works for some scenario but doesnt work on mine.

**First Scenario : ( works fine )**

settings.json is only opened.
My extension create new page and add text and through this command i am switched to settings.json - works Fine !

**Second Scenario : ( does not work )**

settings.json is opened, 2nd file , say abc.txt is opened and switched current tab from settings.json to abc.txt , and when my extension create new page and when this command hits, it should remain in abc.txt but it goes to settings.json

I originally posted on https://github.com/Microsoft/vscode/issues/15319#issuecomment-285861406 but issue is closed so opening new one.

**Comment by bpasero** [comment] 2017-03-20 03:58
@shanalikhan try with setting  `"workbench.editor.enablePreview": false` in settings?

**Comment by shanalikhan** [comment] 2017-03-25 17:35
actually i dont want to depend on the  user settings to do such task.
Extension needs to revert to last tab when new tab is opened so user will keep work on current tab quietly and smoothly

**Comment by bpasero** [comment] 2017-03-25 17:52
@shanalikhan can you maybe share a demo what you expect to do, having a bit of a hard time to follow. You want to open an editor and hide it? Aka, you want to open it in the background?

**Comment by shanalikhan** [comment] 2017-03-25 18:08
> you want to open it in the background

Exactly i want to open it in background, even the user is typing in some tab. It shouldn't stop anything like cursor etc but open a new tab in background ( on which i am adding text ) so when ever user want he can switch to that tab and see that text document.

**Comment by jrieken** [comment] 2017-04-11 13:36
closing as dupe of https://github.com/Microsoft/vscode/issues/11247

**Closed by jrieken** 2017-04-11 13:36 UTC
Labels: api, feature-request
