### ISSUE TITLE
visual studio code not saving files that are modified

### ISSUE THREAD

**Issue by inward-eye** [microsoft/vscode#162764] opened 2022-10-05 18:05 UTC
using visual studio code to edit markdown files. For a particular folder VSC is not saving the files. When shutting down VSC and re-opening then it shows the files as not saved. When hitting save it says "failed to save" "the content of the file is newer" and then asks to Overwrite

Type: <b>Bug</b>

using visual studio code to edit markdown files. For a particular folder VSC is not saving the files. When shutting down VSC and re-opening then it shows the files as not saved. When hitting save it says "failed to save" "the content of the file is newer" and then asks to Overwrite

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (20.16GB free)|
|Process Argv|--crash-reporter-id 3c35b0d2-c44b-48c5-b175-29492b09d9db|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.2
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.48.1
docs-article-templates|doc|0.2.13
docs-authoring-pack|doc|0.1.18
docs-build|doc|0.4.0
docs-images|doc|0.0.10
docs-linting|doc|0.0.13
docs-markdown|doc|0.2.114
docs-metadata|doc|1.0.9
docs-preview|doc|0.3.60
docs-scaffolding|doc|0.0.16
docs-yaml|doc|0.2.9
vscode-yaml|red|1.10.1
code-spell-checker|str|2.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
i497e931:30553904
vscccc:30566498
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by mjbvz** [comment] 2022-10-05 18:45
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by inward-eye** [comment] 2022-10-05 18:52
hi @mjbvz .. yes tested that. this happens also with all the extensions disabled. So it looks like an issue in VS Code

**Comment by mjbvz** [comment] 2022-10-05 18:55
Did you try on VS Code insiders?

**Comment by inward-eye** [comment] 2022-10-05 18:56
no. given what I do I need a stable environment that has been tested thoroughly

**Comment by inward-eye** [comment] 2022-10-05 19:21
It does not seem to be happening on the insiders build with extensions disabled

**Comment by mjbvz** [comment] 2022-10-05 20:01
Thanks for testing. Closing since this was likely already fixed then

**Closed by mjbvz** 2022-10-05 20:01 UTC
