### ISSUE TITLE
Terminal breaks when resizing vscode window

### ISSUE THREAD

**Issue by doge-lord** [Microsoft/vscode#31412] opened 2017-07-25 19:09 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
tslint|eg2|0.17.0
docthis|joe|0.4.7
csharp|ms-|1.11.0
vscode-icons|rob|7.11.0
vscode-coverage-gutters|rya|1.1.1
bootstrap-3-snippets|wcw|0.1.0
local-history|xyz|1.2.1

---

Steps to Reproduce:

1. Open a project with vscode
2. Open terminal
3. Resize width to a smaller value

Reproduces without extensions: Yes

Screenshot:
![image](https://user-images.githubusercontent.com/10230290/28589246-e3c3602a-71af-11e7-8896-4168683020b9.png)

**Comment by cleidigh** [comment] 2017-07-25 20:12
@doge-lord 
cc @Tyriar 
This is by design and a function of the way xterm interacts with the shell.
Duplicate of #30430
See discussion there as well.

**Closed** 2017-07-28 18:41 UTC
Labels: integrated-terminal, new release
