### ISSUE TITLE
Visual Studio Code (new feature)

### ISSUE THREAD

**Issue by EmreKose99** [microsoft/vscode#85597] opened 2019-11-26 12:30 UTC
(English)
For example; < h1 > < / h1 > If I want to change this tag to h2, change the closing tag to h2 when I change < h1 > to h2. This feature also has phpstorm.

(Turkish)
Editör harika. Sizden bir isteğim var. Örneğin; < h1 >< /h1 > bu etiketi h2 olarak değiştirmek istediğimde sade < h1 > 'in içini h2 olarak değiştidiğim zaman <  /h1 > bu etiketin içininde h2 olarak değişmesini sağlarsanız çok iyi olur. Bu özellik php stormda da var. Bu özellik aynı zamanda phpstorm var.

<h5>I'm sorry I wrote in Turkish.</h5>

**Comment by gjsjohnmurray** [comment] 2019-11-26 12:46
Courtesy of translate.google.com (other services are available):

> The editor is great. I have a request for you. For example; ```<h1>``` ```</ h1>``` When I want to change this tag to ```h2```, it's best if you change ```<h1>``` to ```h2``` when you change ```<h1>``` to ```h2``` inside this tag. This feature is also available in the php storm.

**Comment by whizsid** [comment] 2019-11-26 12:48
Hy @EmreKose99  install [this](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) extension.

**Comment by EmreKose99** [comment] 2019-11-26 12:50
Hemen ingilizce olarak düzeltiyorum @whizsid @gjsjohnmurray one minute

**Comment by gjsjohnmurray** [comment] 2019-11-26 12:54
Take a look at https://github.com/microsoft/vscode/issues/47069#issuecomment-555666038 and maybe try this out in [Insiders](https://code.visualstudio.com/insiders/)

**Comment by whizsid** [comment] 2019-11-26 12:56
Install the extension "Auto rename tag" from [here](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)

**Comment by EmreKose99** [comment] 2019-11-26 12:59
I updated. I hope I can tell you exactly. my english is not very good. @gjsjohnmurray @whizsid Look again.

**Comment by octref** [comment] 2019-11-26 18:30
As @gjsjohnmurray said, you can use the [Insiders](https://code.visualstudio.com/insiders/) to get this feature now:

![auto-selection](https://user-images.githubusercontent.com/4033249/69450026-0e13b880-0d11-11ea-8505-9fbc2a8fc6ba.gif)

Or you can wait a few weeks for the next release.

Closing as duplicate of #47059.

**Closed by octref** 2019-11-26 18:30 UTC

**Comment by EmreKose99** [comment] 2019-11-26 19:11
Thank you @octref . Just as I wanted.
