### ISSUE TITLE
Improve @import SCSS Navigate

### ISSUE THREAD

**Issue by mclenney** [microsoft/vscode#79444] opened 2019-08-19 12:22 UTC
Hello, I just updated to the most recent vscode:

Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

And it looks like in the release notes there was a message about improvement to the searched locations for @import scss statements.  This is a suggestion to provide additional support for ~ syntax.  In the app portion of my project, I have a generalized sass folder that holds common sass files for the application.  Throughout stylesheets in components, I reference these common sass files via imports using the ~ syntax to resolve the folder location regardless of the current depth of the component that calls these stylesheets:

@import '~app/sass/mixins';
@import '~app/sass/forms';

It would be nice if vscode was also be able to parse this as trying to navigate to the stylesheet yields an error:  

Unable to open 'mixins': Unable to read file (Error: File not found (d:\Projects\MyProjectName\MyAppName\Angular\src\app\component-name\component-name\component-name\component-name\app\sass\mixins)). (folder path replaced with generic names i.e. component-name, MyProjectName, and MyAppName for anonymity)

**Comment by octref** [comment] 2019-10-22 19:32
Duplicate of #78894.

**Closed by octref** 2019-10-22 19:32 UTC
Labels: css-less-scss, feature-request
