### ISSUE TITLE
Cannot select multiple files in workspace explorer

### ISSUE THREAD

**Issue by eByte23** [Microsoft/vscode#9557] opened 2016-07-21 01:39 UTC
- VSCode Version: 1.4.0-insider - SHA: 0aa920
- OS Version: Win10x64-insider build 1607.14383

Steps to Reproduce:

1. Open folder with plus >1 files
2. click on the first file, hold shift click the last file you want to select.

Actual Result:
Only the first file is selected.

Expect Result:
Should have the same result as windows explorer when selecting multiple files with shift held.

Reason:
Trying to copy a group of files with out leaving vs code

**Comment by kieferrm** [comment] 2016-07-21 21:48
Duplicate of #1023.

**Closed by kieferrm** 2016-07-21 21:48 UTC
Labels: duplicate
