### ISSUE TITLE
PlatformIO tasks doesn't work

### ISSUE THREAD

**Issue by sstaub** [Microsoft/vscode#63165] opened 2018-11-14 19:42 UTC
- VSCode Version: 1.30 insider
- OS Version: macOS 10.14.1 Mojave
- PlatformIO IDE 1.4.3

I'm using platformIO for development, with the insider version most of the task doesn't work anymore.
<img width="1258" alt="platformio" src="https://user-images.githubusercontent.com/6450325/48507989-aef1ad00-e84d-11e8-9166-bf68e9f2c48e.png">

**Comment by sstaub** [comment] 2018-11-14 21:30
The problem has nothing to do with the other issue (I now about the problem with Arduino plugin from MS). The problem occurs with the new insider version (1.30) and works PlatformIO works without a problem with 1.29 insider and release.

**Comment by sstaub** [comment] 2018-11-14 22:38
@Ivankravetz from PlatformIO knows about it.

**Comment by alexr00** [comment] 2018-11-15 09:19
Seems to be related to #63104, which I'm looking into now.

**Comment by alexr00** [comment] 2018-11-15 10:09
Duplicate of #63104

**Closed by alexr00** 2018-11-15 10:09 UTC
Labels: insiders
