### ISSUE TITLE
Find in terminal breaks with reflow

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#67468] opened 2019-01-29 19:29 UTC
Issue Type: <b>Bug</b>

While testing #67307.

1) `ls -R` in the terminal in `vscode` folder
2) <kbd>CMD</kbd>+<kbd>F</kbd> in terminal
3) type `.js` 
4) use next match arrow to jump to additional matches in the same line 
-> all good
5) resize window to make terminal smaller
6) try step 4 again
-> all matches are in the wrong place; matches are limited to the same line

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|-psn_0_83337077|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kieferrm** [comment] 2019-01-29 19:31
It doesn't seem that all matches are wrong. It seems that only those in the current viewport are wrong.

**Comment by Tyriar** [comment] 2019-01-30 20:39
This is probably caused by the search addons cache, it's not being invalidated when a resize happens.

**Comment by lohxx** [comment] 2019-03-04 22:47
Can i work on this issue?

**Comment by Tyriar** [comment] 2019-03-05 16:02
@lohxx sounds good, the fix for this will be in the xterm.js repo and I think it's related to the line cache: https://github.com/xtermjs/xterm.js/blob/ce1c45fb18af8ba7a88ee148e10a76eed070357f/src/addons/search/SearchHelper.ts#L155

**Comment by thebradbain** [comment] 2019-04-28 21:48
Hello! 

I've submitted a PR (which has now been merged) on the relevant xterm.js issue [#1915](https://github.com/xtermjs/xterm.js/issues/1915). 

Does anything else need to be done (specifically with the vscode-xterm repo), or will the fix be applied to VSCode the next time its dependency version pinning is regularly updated?

**Comment by Tyriar** [comment] 2019-04-28 22:23
@thebradbain it's too late for the April release but I will likely update xterm in May, thanks again for the contribution 🙂

**Closed** 2019-05-13 18:17 UTC
Labels: bug, good first issue, help wanted, integrated-terminal
