### ISSUE TITLE
Import File wrong syntax and position

### ISSUE THREAD

**Issue by suryasarafe2** [Microsoft/vscode#61170] opened 2018-10-17 20:25 UTC
closed but not clear to me - [#27317](https://github.com/Microsoft/TypeScript/issues/27317) i am not working on TypeScript, so i don't understand how to change the version of TypeScript.

#Expected result : 
`import SaeHeader from '../global/header';`

#Result: 
`import('../global/header').SaeHeader`

after upgrade to 1.28.1 import is error, and previously i can import from anywhere and the import is place on the bottom list of import

#Expected Result: 
`import ... from '...';
import SaeHeader from '../global/header';
...// other code
return (
<SaeHeader
)`

#Result
`
 return (
<import('../global/header').SaeHeader
)
`
#find solution on comment
> I have downgraded from 1.28.1 to 1.27.2 but VSCode keep updating, regard I don't event select to Install Update. It's very inconvenient 😢

#my solution now
> For now i install v 27.2 and disable auto update

#question
is there any setting to use this feature correctly.?

**Comment by mjbvz** [comment] 2018-10-17 21:13
Duplicate of #60216 

Should be fixed in 1.28.2

**Closed by mjbvz** 2018-10-17 21:13 UTC
Labels: javascript

**Comment by suryasarafe2** [comment] 2018-10-19 09:13
issue is Fix, thanks

and after update i realize that i have 2 version now, 
shortcut on start : version 1.27.1 (user setup)
shortcut on taskbar : version 1.28.2 (system setup)
