### ISSUE TITLE
git repos not detected in sub-folders of the open folder

### ISSUE THREAD

**Issue by kattkieru** [Microsoft/vscode#11827] opened 2016-09-10 11:51 UTC
- VSCode Version: 1.5.1
- OS Version: macOS, Windows 10

If you add a folder that contains multiple folders of git repos, the git integration does not work.  It only seems to work if you open a folder that is a git repo directly (and then it's pretty brilliant).

It would be great if the root didn't need to be a repo, but Code were intelligent enough to detect that sub-folders contain different repos and still have all the features work.

**Comment by ramya-rao-a** [comment] 2016-09-11 16:41
Closing as duplicate of #10450 
@kattkieru Don't forget to up vote the original issue logged.

**Closed by ramya-rao-a** 2016-09-11 16:41 UTC
