### ISSUE TITLE
macOS: Font weight is permanently bold after latest update

### ISSUE THREAD

**Issue by jgarber623** [microsoft/vscode#224496] opened 2024-08-01 17:44 UTC
#214390 appears to be back in the just-released v1.92.0. I'm experiencing the issue as previously reported (and later resolved in v1.90.1):

> I use Operator Mono first this issue occurred in Insider release, and now with the latest release both versions of VS Code only show bold font weight. 300 is too thin. 400 is too bold. This wasn't the case before.

```
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by trevorwright** [comment] 2024-08-01 19:53
Appears to be a regression of this issue: https://github.com/microsoft/vscode/issues/214390

The same fix from last time works again. Quit out of VSCode and then launch it from your terminal with the following command

```
open -a "Visual Studio Code" --args --disable-blink-features=FontMatchingCTMigration
```

**Comment by leademeule** [comment] 2024-08-02 03:08
I am also experiencing this regression. [See this comment for documentation and screenshots.](https://github.com/microsoft/vscode/issues/214390#issuecomment-2153055011)

**Comment by leademeule** [comment] 2024-08-02 03:09
@trevorwright thank you for sharing, this fixes it on my side. Hopefully this can be properly patched sometime soon.

**Comment by rigobauer** [comment] 2024-08-02 04:03
Same problem here

**Comment by kowsar89** [comment] 2024-08-02 11:32
I'm using Ubuntu 22.04 and font looks funny and bigger after the update (v1.92.0), screenshot: https://prnt.sc/Twi3ckgzi0YA

```
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.6.22-060622-generic
```

**Comment by guymarshall** [comment] 2024-08-02 21:48
I am using Linux Mint and the font has also suddenly increased in size after the update like @kowsar89

**Comment by JMadgwick** [comment] 2024-08-04 16:18
I also have this problem. I also see the bolded font in the right click menu. I never previously had this problem in any version I'd used before.

**Comment by michael-andreuzza** [comment] 2024-08-04 19:06
Been also having this issue, using same font, but it actually goes back to a few...not from the latest update.

MacOS Sonoma.

**Comment by michael-andreuzza** [comment] 2024-08-04 19:12
> Appears to be a regression of this issue: #214390
> 
> The same fix from last time works again. Quit out of VSCode and then launch it from your terminal with the following command
> 
> ```
> open -a "Visual Studio Code" --args --disable-blink-features=FontMatchingCTMigration
> ```

Thank you for sharing this.

**Comment by helloromero** [comment] 2024-08-05 08:13
@michael-andreuzza THANK YOU!!! I can't express how much I was about to give up on being a developer lol

**Comment by dylandifilippo** [comment] 2024-08-05 12:24
I'm experiencing the same issue. I did everything. 
Uninstall the app completely
Tried the command in the terminal.
Nothing is working.

**Comment by BABA983** [comment] 2024-08-05 15:03
@deepak1556 The latest VSCode already uses Electron 30, this [TODO](https://github.com/microsoft/vscode/commit/7640672f4ff8a24c7c5444c0c0ae8ce3ce082b7f) can be removed safely at this point?

**Comment by mrwigster** [comment] 2024-08-05 15:34
Same issue as last time, my fix from last time seems to work:
https://github.com/microsoft/vscode/issues/214390#issuecomment-2154931444
For anyone else wondering, open VS using terminal with the below command:

```open -a "Visual Studio Code" --args --disable-blink-features=FontMatchingCTMigration```

**Comment by michael-andreuzza** [comment] 2024-08-05 19:42
> @michael-andreuzza THANK YOU!!! I can't express how much I was about to give up on being a developer lol

it wasn't my my man...it was @trevorwright solution :-)

**Comment by deepak1556** [comment] 2024-08-06 05:32
https://chromium.googlesource.com/chromium/src/+/98eb1392b060711dc30dbc9d1b07fe6c4147e0ff was confirmed to address the postscript name matching in https://github.com/microsoft/vscode/issues/214390#issuecomment-2154822715. However the font weight matching is still regressed with the core text path for certain fonts and seems like https://chromium.googlesource.com/chromium/src/+/3bef104fb08126b6b68bab46b0ce132e1cc574a7 accidentally addresses it by using the appkit path as default which is available from Chromium 125. Issue is however present with the core text path in latest canary `--enable-blink-features=FontFamilyStyleMatchingCTMigration`. I will disable the CT engine again as candidate fix and follow-up in upstream to address the root issue.

**Comment by deepak1556** [comment] 2024-08-06 05:44
**Steps for verification:**

* Install the font variants from [PP_Neue_Montreal_Mono.zip](https://github.com/user-attachments/files/16505757/PP_Neue_Montreal_Mono.zip)
* Set `"editor.fontFamily": "PP Neue Montreal Mono", "editor.fontWeight": 400`
* Verify that `Book` variant is chosen over `thin` variant

**Comment by KoreSamuel** [comment] 2024-08-06 09:25
```
Version: 1.92.0 (Universal)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.3.0
```
same issue, it looked like have appeared before. And `open -a "Visual Studio Code" --args --disable-blink-features=FontMatchingCTMigration` works for me after  using `Command + Q` to quit vscode.

**Comment by deepak1556** [comment] 2024-08-06 12:41
Closing for verification.

**Closed by deepak1556** 2024-08-06 12:41 UTC
Labels: bug, upstream, macos, candidate, font-rendering, confirmed, regression, chromium

**Comment by jgarber623** [comment] 2024-08-06 14:16
@deepak1556 Thanks for sorting this one out!

**Comment by isidorn** [comment] 2024-08-07 11:41
Adding verified. 

Before (broken) it looked like


![Image](https://github.com/user-attachments/assets/d980005e-2a9e-4cea-aa9b-618cd50a2963)



Now with the fix it looks like



![Image](https://github.com/user-attachments/assets/19d10fb6-94db-4aa7-80f0-0c78d4901517)



Users - if something is off in this image do let us know!

**Comment by isidorn** [comment] 2024-08-08 12:24
@dannyuk1982 the fix has not yet been released in stable. Should be out in next 24h

**Comment by bpasero** [comment] 2024-08-09 06:40
Should be out now.

**Comment by dannyuk1982** [comment] 2024-08-09 09:12
@bpasero yup that is working fine for me! thanks

**Comment by kowsar89** [comment] 2024-08-11 06:24
> I'm using Ubuntu 22.04 and font looks funny and bigger after the update (v1.92.0), screenshot: https://prnt.sc/Twi3ckgzi0YA
> 
> ```
> Version: 1.92.0
> Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
> Date: 2024-07-31T23:26:45.634Z
> Electron: 30.1.2
> ElectronBuildId: 9870757
> Chromium: 124.0.6367.243
> Node.js: 20.14.0
> V8: 12.4.254.20-electron.0
> OS: Linux x64 6.6.22-060622-generic
> ```

I don't think it's fixed for me after the update ie.
```
Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
```

**Comment by deepak1556** [comment] 2024-08-12 10:53
@kowsar89 this issue is specific to macOS, can you open a separate issue for your case. Thanks!

**Comment by guymarshall** [comment] 2024-08-12 17:55
> @kowsar89 this issue is specific to macOS, can you open a separate issue for your case. Thanks!

Multiple people (me included) have said this issue also affects Linux but for some reason macOS was put in the title and other OSes were ignored.

**Comment by jgarber623** [comment] 2024-08-12 18:19
I'm not impacted by the Linux issues, but taking up @deepak1556's suggestion above and opened an issue for y'all: https://github.com/microsoft/vscode/issues/225434
