### ISSUE TITLE
The on-screen keyboard opens anytime i click on anything inside VS Code

### ISSUE THREAD

**Issue by murckee** [microsoft/vscode#76560] opened 2019-07-04 04:12 UTC
Since the 1.36 update, every single time i click on anything inside VS Code, the onscreen keyboard pops up and the VS code window resizes to fit the screen that's left.

I tried reinstalling 1.35 and that fixed the issue. I also tried installing the insider build and the issue was there too. VS Code is the only program or window it seems that makes the onscreen keyboard appear so it's not an issue with the keyboard. Plus going to the earlier version fixed it.

I am using a 2-in-1 tablet pc and this is happening when the screen is docked with a keyboard attached.  Basically, it seems like VS code doesn't know a keyboard is attached and keeps making the onscreen keyboard pop up when it thinks you want to enter text.

- VSCode Version: 1.36
- OS Version: Windows 10 32-bit

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment] 2019-07-04 08:23
@bpasero @rebornix did we do anything special here for the Web.

**Comment by bpasero** [comment] 2019-07-04 09:14
@murckee can you check if this happens in other applications too? E.g. Chrome?

**Comment by murckee** [comment] 2019-07-04 09:38
They on-screen keyboard only comes up with the newest VS code version. 1.36 and the insider build which i tried. It's really consistent with just this program. And every time i click on anything where it might expect me to enter text. 

I made sure the setting for "Show the touch keyboard when not in tablet mode " is set to off in typing settings.

I tried turning it on and when i do, the onscreen keyboard still pops up all the time in VS code but for other programs, it only pops up if i click something with my finger on the touchscreen and not the mouse.

I also tried the trackpad on the keyboard and its the same with the onscreen keyboard popping up in just VS Code.

**Comment by bpasero** [comment] 2019-07-04 09:46
Somewhat related: https://github.com/electron/electron/issues/6430

**Comment by bpasero** [comment] 2019-07-04 10:27
@deepak1556 any clues?

**Comment by deepak1556** [comment] 2019-07-04 11:08
@murckee whats the build version of windows 10 you are running ? Also can you try launching vscode with the following flag see if there is a difference. Thanks!

```
> code <file/path> --enable-features=InputPaneOnScreenKeyboard
```

**Comment by murckee** [comment] 2019-07-04 18:52
I tried launching vscode insiders from the command line with those flags and it didn't make a difference.
The only thing that seems to stop the keyboard from popping up is disabling the touch keyboard from services but then I cant use it for anything else.

Im using windows version 1511
build 10586.1176

Its an older computer with an Atom processessor. Z3735F 2GB Ram.

**Comment by deepak1556** [comment] 2019-07-05 03:55
@murckee based on this chromium issue comment https://bugs.chromium.org/p/chromium/issues/detail?id=497381#c135 , it seems there are issues with windows version less than RS4 . But the fact that you are seeing this issue only with vscode and not chrome is a bit confusing. I will get a touch device tomorrow and try to narrow down the source of this issue. In the meantime is it possible for you to update the windows version ?

**Comment by murckee** [comment] 2019-07-05 20:09
I didn't realize my windows version was so old. I'm using an old tablet. It doesn't seem to be able to update windows beyond what I have now.

**Comment by deepak1556** [comment] 2019-07-05 21:41
@itbgcthate @Yeppoh can you also mention the windows 10 build version you are running ? Also can you download the chromium browser from here https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/576753/ which is the same version `1.36` stable release uses and check if the issue is present. Thanks!

I tried to verify the issue on Lenovo thinkpad X1 Carbon with windows 10 build version 1903 but wasn't able to.

**Comment by deepak1556** [comment] 2019-07-05 22:03
Can you also see if you are able to workaround the issue temporarily by launching vscode with

```
> code <file/path> --disable-usb-keyboard-detect
```

**Comment by murckee** [comment] 2019-07-05 22:38
I couldn't run the version of chromium you linked because i'm using 32-bit windows but I did find a version with a similar date that was 32 bit and it's causing the same issue of the on-screen keyboard popping up.

I downloaded win32_rel_579575_chrome-win32.zip.

Also i tried launching vscode the way you said to disable usb keyboard input and it made no difference.

Im using windows version 1511
build 10586.1176

**Comment by Yeppoh** [comment] 2019-07-05 22:45
@deepak1556 I'm using Windows 8.1 - Windows_NT x64 6.3.9600

**Comment by deepak1556** [comment] 2019-07-05 23:02
Thanks for testing! I was able to find a similar issue in upstream https://bugs.chromium.org/p/chromium/issues/detail?id=871756 , will try to backport the fix and see if it resolves the issue.

**Comment by itbgcthate** [comment] 2019-07-06 03:15
Thanks for replying so quickly.

Version: 1.35.1 (system setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.3.9600

Sorry, but I had to downgrade to 1.35.1 so that I could continue development. Let me know if Yeppoh's feedback isn't sufficient and I'll try the other things you suggested.

Regards,

itbgcthate
________________________________

**Comment by itbgcthate** [comment] 2019-07-15 19:24
Should this have been fixed in 1.36.1? I'm seeing the same behavior.

**Comment by deepak1556** [comment] 2019-07-17 20:25
@itbgcthate the fix from electron has not been released yet, will update here once we have a release with the fix. Thanks!

**Comment by joelzehring** [comment] 2019-07-18 05:14
Same issue here. I'm also using an older Windows tablet with an older 32-bit build. Thanks for investigating this!

**Closed** 2019-07-24 21:45 UTC
Labels: electron, electron-4.0.x-update, upstream

**Comment by dseeker** [comment] 2019-07-31 08:10
Same issue, downgraded to 1.35.1 and the issue went away
