### ISSUE TITLE
Broken filemenu after new-file timeout's

### ISSUE THREAD

**Issue by xeor** [Microsoft/vscode#42936] opened 2018-02-04 20:20 UTC
- VSCode Version: 1.19.2
- OS Version: osx 10.12.6

Steps to Reproduce:

1. Make sure you have a long list of files in the file-list
2. Click the header-button called "new file" (the one on the top of the segment in the filelist)
3. Don't enter anything, but scroll up and down with the mouse in the filelist, some times, you need to scroll slowly..
4. The new-file suddenly cancels itself, and now the menu is broken, when you scroll.

With broken, I mean:
* There are many visual artifacts that doesnt fit the rest of the view.
* If you try to select a file, another file is selected instead.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment] 2018-02-04 20:38
Duplicate of https://github.com/Microsoft/vscode/issues/22269

**Closed** 2018-02-04 20:48 UTC
Labels: editor, editor-core
