### ISSUE TITLE
Coloring Folder Manually and Individually

### ISSUE THREAD

**Issue by Jervi-sir** [microsoft/vscode#161415] opened 2022-09-21 16:19 UTC
Would be perfect to Colorize each folder as wanted, Especially when you use a system design Like DDD.
so example, I set up Advertiser's folder with color green, Client's folder will be Yellow ....
and each subfiles will take same color maybe, even in tabs

**Comment by aeschli** [comment] 2022-09-22 09:35
duplicate of https://github.com/microsoft/vscode/issues/38857

**Closed by aeschli** 2022-09-22 09:35 UTC
Labels: triage-needed
