### ISSUE TITLE
Controls Incorrectly Coded as Checkboxes Instead of Tabs

### ISSUE THREAD

**Issue by Bluefish0558** [microsoft/vscode#227514] opened 2024-09-04 03:01 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: 14.6.1 (23G93)

**Description:**
Controls such as "User" and "Workspace" are incorrectly coded as checkboxes rather than tabs, which makes them inaccessible to screen reader users who cannot determine which panels are revealed.

**Steps to Reproduce:**

1. Navigate to the "User" and "Workspace" controls in VSCode.
2. Use a screen reader to interact with these controls and notice they are treated as checkboxes instead of tabs.

**User Impact**: Screen reader users cannot identify that these controls reveal panels of content or determine which panel is currently active.

**Expected Behavior**: The controls should be coded as tabs with appropriate roles and states, including tablist, tab, and tabpanel, and use ARIA attributes like aria-controls and aria-selected.

**Actual Behavior**: The controls are coded as checkboxes, preventing screen readers from providing the necessary context for navigation.

**Recommendation**: Ensure proper tab structure by assigning `role="tablist"`, `role="tab"`, and `role="tabpanel"` where needed, and include ARIA attributes such as aria-controls and aria-selected to indicate the active panel.

<img width="822" alt="Checkboxes Instead of Tabs" src="https://github.com/user-attachments/assets/ee240b35-99c6-4d3d-a426-07da353c29e3">

**Comment by meganrogge** [comment] 2024-09-06 17:41
Using VoiceOver on MacOS, it says tabs for me.

**Comment by rzhao271** [comment] 2024-09-06 21:31
Unable to reproduce this issue on 1.93.0 on Windows.
The issue should have been fixed with https://github.com/microsoft/vscode/issues/214227.

**Closed** 2024-09-14 11:24 UTC
Labels: info-needed
