### ISSUE TITLE
✨ symbol obscures variable name

### ISSUE THREAD

**Issue by dharmatech** [microsoft/vscode#213702] opened 2024-05-26 14:34 UTC
Type: <b>Bug</b>

# Behaviour

The '✨' symbol obscures variable name.

## Steps to reproduce:

Place cursor under line in python file.

Extension version: 2024.6.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.3
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|.NET Install Tool|ms-dotnettools.vscode-dotnet-runtime|2.0.5|
|Apache Conf|mrmlnc.vscode-apache|1.2.0|
|C#|ms-dotnettools.csharp|2.30.28|
|Even Better TOML|tamasfe.even-better-toml|0.19.2|
|fantomas-fmt|paolodellepiane.fantomas-fmt|0.3.0|
|GistPad|vsls-contrib.gistfs|0.6.0|
|GitHub Copilot|GitHub.copilot|1.195.0|
|GitHub Copilot Chat|GitHub.copilot-chat|0.15.2|
|HTML Preview|george-alisson.html-preview-vscode|0.2.5|
|Ionide for F#|Ionide.Ionide-fsharp|7.20.1|
|JavaScript Debugger|ms-vscode.js-debug|1.89.0|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.2|
|Jupyter|ms-toolsai.jupyter|2024.4.0|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Keymap|ms-toolsai.jupyter-keymap|1.1.2|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.17|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|Org Mode|tootone.org-mode|0.5.0|
|Pine Script Syntax Highlighter|ex-codes.pine-script-syntax-highlighter|1.0.5|
|Polyglot Notebooks|ms-dotnettools.dotnet-interactive-vscode|1.0.5229040|
|PowerShell|ms-vscode.powershell|2024.2.2|
|Pylance|ms-python.vscode-pylance|2024.5.1|
|Python|ms-python.python|2024.6.0|
|Python Debugger|ms-python.debugpy|2024.6.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.9|
|WSL|ms-vscode-remote.remote-wsl|0.88.2|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (29.96GB free)|
|Process Argv|-n . --crash-reporter-id b6d73a27-f3ba-4196-9923-d0fd548cad16|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31049070
a69g1124:31058053
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by justschen** [comment] 2024-05-29 23:10
duplicate of https://github.com/microsoft/vscode/issues/213807

**Closed by justschen** 2024-05-29 23:10 UTC
