### ISSUE TITLE
paste absolute file path after update from version 1.63.2

### ISSUE THREAD

**Issue by aaronhd** [microsoft/vscode#159525] opened 2022-08-30 05:54 UTC
When I copy a file in the folder, past version VS code can paste an absolute path of the file, while newer version VS code can only get the filename with extension.

**Comment by mjbvz** [comment] 2022-08-30 22:45
@alexdima Assigning you since this was introduced by [827e180017064f6e676e0fb8c9e501cc3564d75b](https://github.com/microsoft/vscode/commit/7c542ab78e52cbd1fc3afed7c465a81aa3e1c48b)

**Comment by aaronhd** [comment] 2022-09-04 11:34
> @alexdima Assigning you since this was introduced by [827e180017064f6e676e0fb8c9e501cc3564d75b](https://github.com/microsoft/vscode/commit/7c542ab78e52cbd1fc3afed7c465a81aa3e1c48b)

It seems not the problem what I meet. The newest version can only paste filename with extension instead of full absolute path.  The full absolute path of a file when copying can be pasted in the editor by older version VS code or other editor (such as sublime) on Ubuntu 16/18 .04.

**Comment by jimjoh** [comment] 2022-09-23 00:00
I also have this issue with VS Code on Linux (CentOS 7).  There are several similar bug reports, most were merged into 
issue [146770](https://github.com/microsoft/vscode/issues/146770).  However, issue [146770](https://github.com/microsoft/vscode/issues/146770) is closed and this problem persists.

**Comment by jimjoh** [comment] 2022-09-24 16:20
> A more complete solution would be to provide a context menu option to paste absolute or relative and in that manner, everybody gets what they need. Allow for customizing keybindings to either option as user desires.

In addition to an enhanced context menu, a new setting called something like "Default filename paste behavior" that would allow you to choose items like "filename only, relative path, absolute path" would be great.  That way when you use a keyboard shortcut to paste it'd be in the format you prefer.

**Comment by hengwang322** [comment] 2022-10-23 10:41
> Please see [#146770 (comment)](https://github.com/microsoft/vscode/issues/146770#issuecomment-1109439182) . This was a regression introduced by updating to Electron 16, most likely coming from Chromium. We will not downgrade Electron. So the change in [bc9189b](https://github.com/microsoft/vscode/commit/bc9189b22ebfe65e7b14a702431fff66f35bd45f) tries to workaround the regression. It looks like the workaround is not working very well on Linux.

From the looks of it, it's not that it's not working well on Linux, the line at 658 returns the names of the files, which is exactly the current behaviour. It looks like changing `file => file.name` to something like `file => file.absolute_path` should yield desired behaviour. Unfortunately, I'm a noobie, I don't know about VS code's API, what properties the `file` object has, or even how to compile a build.

**Comment by sxsong1207** [comment] 2022-11-29 19:29
The same issue here, which is very annoying. I need to open a note pad to get the full path and copy it again to vscode.

My system is Linux Mint 20.3 Cinnamon.

**Comment by ingo-m** [comment] 2023-01-29 00:48
For me the problem of not being able to paste an absolute filepath (with Ctrl + V) still persists on Ubuntu 22.04.1 LTS. I did not encounter this problem in any other text editor.

**Comment by chazo1994** [comment] 2023-02-17 07:24
This issue is very annoyed. I have to copy from nautilius and paste into the terminal, then copy/paste from terminal to vscode.

**Comment by jimjoh** [comment] 2023-04-08 20:10
> For those on Linux looking for a workaround, see https://github.com/ronen25/nautilus-copypath.
> 
> I followed the instructions for Ubuntu (22.04 LTS) to install nautilus-copypath.py and after a logoff/logon, Nautilus displays a "Copy Path" option in the context menu. This is in addition to the default Copy option which still works to copy just the object (file/directory) name itself.

This is the best workaround I've seen so far, thanks for sharing.

Another workaround from https://github.com/microsoft/vscode/issues/177337 is to paste the filename into VS Code's Find box (CTRL+F) which will paste the full path.  Then you can copy and paste the full path from the Find box to your document.

**Comment by hengwang322** [comment] 2023-05-19 03:03
Huh, it looks like this is fixed in the latest insider release.

Version: 1.79.0-insider
Commit: 2946b1ee55db1d406526d3fd1df49250b2f8322d
Date: 2023-05-18T05:26:08.467Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-41-generic

**Comment by ingo-m** [comment] 2023-05-19 12:52
@hengwang322 That would be great, I'm looking forward for a fix to make it into the stable release.

**Comment by deepak1556** [comment] 2023-12-15 18:19
I am unable to repro the issue with latest stable `1.85`, please confirm if this is still an issue.

**Comment by ingo-m** [comment] 2023-12-16 21:57
@deepak1556 thanks for bringing it up, I can confirm that the issue does not occur anymore ✅

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-39-generic

**Closed** 2023-12-19 02:20 UTC
Labels: info-needed, linux
