### ISSUE TITLE
Timline: bad progress location exception

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96045] opened 2020-04-24 08:28 UTC
I see this out of source in the developer console.
Let me know if you need more details and I can look into exact steps

```
 ERR Bad progress location: timeline: Error: Bad progress location: timeline
    at ProgressService.withProgress (file:///Users/isidor/Development/vscode/out/vs/workbench/services/progress/browser/progressService.js:47:27)
    at TimelinePane.handleRequest (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:449:59)
    at TimelinePane.loadTimelineForSource (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:430:22)
    at TimelinePane.loadTimeline (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:382:44)
    at TimelinePane.setUriCore (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:220:22)
    at TimelinePane.onActiveEditorChanged (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:269:22)
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:460:45)
    at EditorService.doHandleActiveEditorChangeEvent (file:///Users/isidor/Development/vscode/out/vs/workbench/services/editor/browser/editorService.js:104:47)
    at EditorService.handleActiveEditorChange (file:///Users/isidor/Development/vscode/out/vs/workbench/services/editor/browser/editorService.js:97:22)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/editor/browser/editorService.js:110:30
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:457:42)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:671:56
    at async EditorGroupView.openEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:593:52)
    at async DelegatingEditorService.editorOpenHandler (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/explorerViewlet.js:162:36)
    at async DelegatingEditorService.openEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/services/editor/browser/editorService.js:900:40)
    at async file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:307:25
```

**Comment by bpasero** [comment] 2020-04-24 12:09
Saw this often in error telemetry too:

![image](https://user-images.githubusercontent.com/900690/80211065-3a6f9000-8635-11ea-9369-a945781c6ce8.png)

**Comment by eamodio** [comment] 2020-04-24 15:16
@isidorn yeah if you could provide steps that would be great. I haven't been able to figure out how this would happen

**Comment by isidorn** [comment] 2020-04-24 17:57
@eamodio I do not have steps. However if it happens again I will keep my eyes open and report back here.

**Comment by usernamehw** [comment] 2020-05-08 07:21
Possible duplicate of #97222

**Closed** 2020-06-02 05:51 UTC
Labels: *duplicate, timeline
