### ISSUE TITLE
"Cannot read property 'adapter' of undefined"

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#69147] opened 2019-02-21 14:49 UTC
I saw this previously in #66322 in provideCodeActions which was fixed, but I've just seen the same thing on stable in provideDocumentSymbols:

```
ERR Cannot read property 'adapter' of undefined: TypeError: Cannot read property 'adapter' of undefined
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:553:140)
	at e.$provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:554:184)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644:118)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643:744)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:256)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:155)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:960
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38:994
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:113)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

I guess it should have the same fix (and based on the comments in that issue, Hovers may also need it?).

I was more aware of what I was doing to repro it this time... The Dart extension has code to restart itself when certain config changes (for example, the path to the Dart SDK). We run through all of the providers we created and dispose them, and then re-create them using the new SDK server client.

Based on @jrieken's comment at https://github.com/Microsoft/vscode/issues/66322#issuecomment-453110213 I guess that if this happens while there are outstanding requests, this error could occur.

**Comment by jrieken** [comment] 2019-02-25 15:31
@DanTup does this reproduce with insiders? Since two weeks that should handle missing adapter more graceful

**Comment by DanTup** [comment] 2019-02-25 17:10
With Insiders I see this instead:

```
ERR no adapter found: Error: no adapter found
	at $._withAdapter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:575:316)
	at $provideCodeActions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:580:395)
	at h._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:593:118)
	at h._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:777)
	at h._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:383)
	at h._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:279)
	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:588:565)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:39:64)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at s (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:754)
	at Socket.define.constructor._socketDataListener.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:960)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

Is that expected?

**Comment by jrieken** [comment] 2019-02-26 08:18
What are you steps to reproduce this?

**Comment by DanTup** [comment] 2019-02-26 08:23
When you switch SDK in the Dart extension, we dispose all of the providers and re-create them. We do it by enumerating through them calling dispose, then just re-calling the `activate` method for the extension:

```ts
context.subscriptions.push(vs.commands.registerCommand("_dart.reloadExtension", (_) => {
		log("Performing silent extension reload...");
		deactivate(true);
		const toDispose = context.subscriptions.slice();
		context.subscriptions.length = 0;
		for (const sub of toDispose) {
			try {
				sub.dispose();
			} catch (e) {
				logError(e);
			}
		}
		activate(context, true);
		log("Done!");
	}));
```

**Comment by jrieken** [comment] 2019-02-26 13:29
So, from looking at both stack traces this happens with code actions *and* document symbols

**Comment by jrieken** [comment] 2019-02-26 13:41
Adding @mjbvz for code actions. @DanTup I have pushed a change that should make this better for document symbols. Tho, it's a blind fix 🙈

**Comment by DanTup** [comment] 2019-02-26 13:52
Oh yeah, I didn't even spot the stacks were different. I'll do some testing tomorrow when the next Insiders build is available. Thanks!

**Comment by DanTup** [comment] 2019-02-27 09:59
The "no adapter found" message from Code Actions is the only error I seem to be able to repro today in Insiders. I'll do some more testing once that's fixed to see if I can find any more. Thanks!

**Comment by jrieken** [comment] 2019-03-01 13:03
I will revert my change because of a regression it introduced

**Comment by jrieken** [comment] 2019-03-05 10:28
I have pushed another change for document symbols

**Comment by DanTup** [comment] 2019-03-06 08:55
Document symbols still looks good to me in latest Insiders - with Outline + Breadcrumb visible and constantly switching SDK, the only one printing errors is CodeActions.

**Comment by mjbvz** [comment] 2019-03-15 22:07
Repo in main VS Code codebase:

1. Running and building VS Code from master
1. In the file `extensions/typescript-language-features/src/features/quickFix.ts`, apply the following patch

```diff
diff --git a/extensions/typescript-language-features/src/features/quickFix.ts b/extensions/typescript-language-features/src/features/quickFix.ts
index 91c3f3b326..7ac5e5dc79 100644
--- a/extensions/typescript-language-features/src/features/quickFix.ts
+++ b/extensions/typescript-language-features/src/features/quickFix.ts
@@ -326,8 +326,17 @@ export function register(
 	diagnosticsManager: DiagnosticsManager,
 	telemetryReporter: TelemetryReporter
 ) {
-	return new VersionDependentRegistration(client, API.v213, () =>
-		vscode.languages.registerCodeActionsProvider(selector,
-			new TypeScriptQuickFixProvider(client, fileConfigurationManager, commandManager, diagnosticsManager, telemetryReporter),
-			TypeScriptQuickFixProvider.metadata));
+	let sub: undefined | vscode.Disposable = undefined;
+
+	setInterval(() => {
+		if (sub) {
+			sub.dispose();
+		}
+		sub = new VersionDependentRegistration(client, API.v213, () => {
+			return vscode.languages.registerCodeActionsProvider(selector,
+				new TypeScriptQuickFixProvider(client, fileConfigurationManager, commandManager, diagnosticsManager, telemetryReporter),
+				TypeScriptQuickFixProvider.metadata);
+		});
+	}, 10);
+
 }
```

**Bug**
See errors every few seconds in developer console

**Comment by mjbvz** [comment] 2019-03-16 23:33
@jrieken I can't seem to fix this error fully for the example above that re-registers a provider every 10 milliseconds. The same pattern also still breaks document symbol providers. Is this worth worrying about?

**Comment by jrieken** [comment] 2019-03-18 08:11
> Is this worth worrying about?

I'd ignore it, since everything is async between two processes it's the way it is. We should maybe be more graceful when a provider isn't around, like resolving with `undefined` which I believe is an accepted return value for all providers. Or handle (read swallow) those errors

**Comment by mjbvz** [comment] 2019-03-18 17:48
@DanTup Can you please test the latest insiders build to see if you can still hit these errors in more normal scenarios

**Comment by DanTup** [comment] 2019-03-19 08:48
Unfortunately on the very first SDK switch I got this error for both Code Actions and Document Symbols.

However, there are also other errors I got, I don't know if they're related.

![Screenshot 2019-03-19 at 8 46 52 am](https://user-images.githubusercontent.com/1078012/54592144-aa1f4e80-4a23-11e9-8f5f-8984bcb6f051.png)

<img width="1312" alt="Screenshot 2019-03-19 at 8 47 04 am" src="https://user-images.githubusercontent.com/1078012/54592153-af7c9900-4a23-11e9-9f96-7c4176a711f8.png">

**Comment by DanTup** [comment] 2019-03-19 08:48
I was using this Insiders from today:

1d191e8909535aaee3389f89b96422a774188ed2

2019-03-19T06:07:09.890Z

**Closed** 2019-03-21 07:50 UTC
Labels: bug, editor-code-actions, outline

**Comment by DanTup** [comment] 2019-03-25 11:06
Thanks, not seeing any errors switching Dart SDKs in insiders now 👍
