### ISSUE TITLE
`Command+C` and `Command+V` does not work in Simple browser on MacOS

### ISSUE THREAD

**Issue by OrkunTokdemir** [microsoft/vscode#212609] opened 2024-05-13 15:21 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

Steps to Reproduce:

1. Run `Simple Browser: Show` with `https://doc.qt.io/`
2. Try to copy something inside the opened tab and paste it.

It is possible to do that on `Linux` but it doesn't work on `MacOS`.

**Comment by mjbvz** [comment] 2024-12-13 17:21
Duplicate of #180234

**Closed by mjbvz** 2024-12-13 17:21 UTC
