### ISSUE TITLE
React native, QR Code not showing on terminal

### ISSUE THREAD

**Issue by rahmatfajar15** [Microsoft/vscode#32648] opened 2017-08-16 16:59 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.2.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
gitlens|eam|4.3.3
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
php-pack|fel|1.0.1
code-runner|for|0.6.33
vscode-yarn|gam|1.2.0
azure-functions-tools|joh|0.3.0
vscode-codemetrics|kis|1.9.0
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.1.8
material-icon-theme|PKi|2.1.0
java|red|0.8.0
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|2.8.2
php-ci|sma|0.2.2
vscode-gulp|tan|0.0.4
vscode-todo-highlight|way|0.5.8
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.4.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Run `yarn start`. Wait till QR generated.
2. Show only blank space

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment] 2017-08-16 17:26
What's the problem? Need more details.

**Comment by rahmatfajar15** [comment] 2017-08-17 09:43
The QR code is not shown. I think the character is not rendered on build in terminal.

**Comment by roblourens** [comment] 2017-08-17 14:54
I don't know what QR code you're talking about, I need steps to repro this.

**Comment by rahmatfajar15** [comment] 2017-08-18 04:39
Step to reproduce:
1. `yarn global create-react-native-app`
2. `create-react-native-app helloWorld`
3. `cd helloWorld`
4. `yarn start`

Using VS Code Terminal:
![2017-08-18 11_35_26-app js helloworld visual studio code](https://user-images.githubusercontent.com/16524713/29444452-ea69a850-8409-11e7-801f-cb6b99b82cfb.png)


Using Conemu:
![2017-08-18 11_38_36-npm](https://user-images.githubusercontent.com/16524713/29444460-f2d7e63c-8409-11e7-91d3-7624dbf6da8c.png)

**Comment by roblourens** [comment] 2017-08-18 06:21
@Tyriar?

**Comment by Tyriar** [comment] 2017-08-18 23:11
Works on macOS, this is likely related to the escape sequence going through winpty and powershell.

@rahmatfajar15 what shell are you using?

**Comment by rahmatfajar15** [comment] 2017-08-19 06:41
@Tyriar I'm using cmd

**Comment by dav-ell** [comment] 2017-09-01 17:16
I'm also experiencing this issue. I created a react native app using `create-react-native-app` and opened the project in VS Code for the first time, typed `npm start` in the integrated terminal using Powershell on Windows 10.

![vs code expo qr bug](https://user-images.githubusercontent.com/17986781/29980294-38b73096-8f17-11e7-9b6a-e15cce0979de.PNG)

Using powershell outside of VS Code:
![powershell expo qr code](https://user-images.githubusercontent.com/17986781/29980379-9ed9f8fe-8f17-11e7-84bc-518233c7b4ef.PNG)

**Comment by breakpoint25** [comment] 2017-09-16 01:25
same issue with vs code not showing qr code ion the integrated powershell on win 10

**Comment by SecondProfessionalLife** [comment] 2017-09-23 20:47
same issue with vs code version 1.16.1 not showing the qr code using cmd on Windows 8.1

**Comment by jovelromeo** [comment] 2017-10-10 04:18
same issue 1.17 on windows 10, hope get fixed soon.

**Comment by hfmm99** [comment] 2017-10-17 04:23
I have the same issue:  Windows 10, Visual Studio Code, and either Powershell or CMD terminal.

**Comment by xunilog** [comment] 2017-11-10 14:29
Same issue, Windows 7, Visual Studio Code integrated Terminal. Tried several themes (bright, dark), same issue.

**Comment by saintplay** [comment] 2017-11-18 16:32
I can successfully see the QR Code now.
Don't know if it's because of the vscode or expo latest update

**Comment by KrallXZ** [comment] 2017-12-08 16:08
I have VSCode 1.18.1 and newest create-react-native-app and have same problem.

**Comment by MauricioLudwig** [comment] 2017-12-10 11:10
I've also got the exact same problem. Whether I use yarn start or npm start I'm unable to see the QR code. Using Powershell currently but I've tried cmd which also fails.

**Comment by vijaysutaria** [comment] 2017-12-13 18:34
I have same issue with VS Code 1.18.1, Windows 10, not able to see QR Code in Terminal

**Comment by cankatabaci** [comment] 2017-12-14 18:52
I have the same problem. 
![adsiz](https://user-images.githubusercontent.com/16356798/34009058-75fcc30a-e118-11e7-99df-bd88f1cdf771.jpg)
I experienced this problem after such a use-case:

1.  run `npm start`
2.  > 21:43:26: Starting packager...
Packager started!
3. `Your phone will need to be on the same local network as this computer.
For links to install the Expo app, please visit https://expo.io.

Logs from serving your app will appear here. Press Ctrl+C at any time to stop.

 › Press a to open Android device or emulator.
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)`
4. i'm press q then it's like in the attached photo

if it helps, I can share system properties and package.json or  something like that

**Comment by Tyriar** [comment] 2017-12-14 18:55
I think this is easily reproducible, it just needs someone to dig deeper and investigate. I suspect the problem lies within winpty and may be tricky to fix. https://github.com/rprichard/winpty

**Comment by nlucero** [comment] 2018-01-13 20:44
Same issue on vs code `1.19.1`, Windows 10 Pro 64 Bit.

**Comment by joshkmartinez** [comment] 2018-01-15 00:36
I got the same problem... This is super annoying

**Comment by bondansebastian** [comment] 2018-01-17 13:09
Same problem on vs code `1.19.2`, Windows 10 Education 64 Bit, `Git Bash` as console

**Comment by Tyriar** [comment] 2018-01-17 23:51
This is an issue with upstream https://github.com/rprichard/winpty, going to close this off as we have no plans on attempting to fix. By all means look into it upstream though.

**Closed** 2018-01-17 23:51 UTC
Labels: *out-of-scope, bug, help wanted, integrated-terminal, upstream, windows

**Comment by himanshu-9419** [comment] 2018-01-28 14:26
I think this is a small issue, it wont take much time and should be fixed earliest.
