### ISSUE TITLE
OSX rendering issues

### ISSUE THREAD

**Issue by matejkramny** [Microsoft/vscode#21834] opened 2017-03-02 21:48 UTC
- VSCode Version: 1.10.1
- OS Version: 10.12

I don't know how to explain this, gif attached, demonstrates the issue well..

![gif](https://cloud.githubusercontent.com/assets/797608/23528467/dbdc8d1a-ff4e-11e6-9f0d-1307e7eec9a1.gif)

**Comment by joaomoreno** [comment] 2017-03-03 10:44
Is it the problem that it jumps around?

**Comment by matejkramny** [comment] 2017-03-03 17:56
Yes right

**Comment by matejkramny** [comment] 2017-03-04 02:30
@joaomoreno the jumping happens when scrolling in the file explorer and other areas..

I'd guess it's some sort of rendering issue due to scaling of the retina screen. It has been around for a few versions, is nobody else seeing it?

**Comment by matejkramny** [comment] 2017-03-04 02:31
![gif](https://cloud.githubusercontent.com/assets/797608/23575288/a941eb06-003f-11e7-8856-a1ec81b5fde6.gif)

**Comment by joaomoreno** [comment] 2017-03-06 09:29
Can you reproduce when setting your zoom level to 1?

**Comment by matejkramny** [comment] 2017-03-06 19:22
I've set the display to various zoom levels, but doesn't seem to affect this issue

**Comment by joaomoreno** [comment] 2017-03-07 08:57
I wanted to say 0, actually. Any other value will get rounding errors. Duplicate of #18355

**Closed by joaomoreno** 2017-03-07 08:57 UTC
Labels: needs more info

**Comment by matejkramny** [comment] 2017-03-07 18:27
Sorry I thought you had meant the display resolution
