### ISSUE TITLE
Lost color for 'yield' for ES 6 in the default dark theme in latest update

### ISSUE THREAD

**Issue by jnystrom** [Microsoft/vscode#1541] opened 2015-12-21 14:40 UTC
I assume this is also the case of the light theme.

<img width="612" alt="screen shot 2015-12-21 at 9 39 11 am" src="https://cloud.githubusercontent.com/assets/1293142/11932929/c371b40c-a7c6-11e5-8ddc-8fb8705438d4.png">

**Comment by egamma** [comment] 2015-12-21 19:52
@jnystrom to narrow whether this is a grammer or a theme issue, please try the sample with a more color ful theme, e.g., monokai.

**Comment by ElfenLiedGH** [comment] 2015-12-22 06:31
+ it's appeared in last version 0.10.05 & it's not theme
![1](https://cloud.githubusercontent.com/assets/9973357/11949314/bcc4754a-a88e-11e5-849a-5d16e8264dad.png)

for 1 file.

**Comment by jnystrom** [comment] 2015-12-22 06:47
I will try a different theme, but there was syntax color highlighting for 'yield' on previous build.

**Comment by ElfenLiedGH** [comment] 2015-12-22 06:48
it's break with "_"
![1](https://cloud.githubusercontent.com/assets/9973357/11949492/e6961dcc-a890-11e5-84ff-33b05aa9a9c8.png)
![2](https://cloud.githubusercontent.com/assets/9973357/11949494/e9cb6362-a890-11e5-8db0-388de5407722.png)
![3](https://cloud.githubusercontent.com/assets/9973357/11949495/ebb4664c-a890-11e5-8e5b-cd44a87aabc9.png)

1. Связные_серверы - don't work break "extends"
2. Связныесерверы - ok
3. Базовая_выборка break this. super... to the first ""

**Comment by ElfenLiedGH** [comment] 2015-12-22 06:49
@jnystrom do you have "_"  before?

**Comment by jnystrom** [comment] 2015-12-22 06:59
No undersxore, and not sure these are the same issues.  Mine is an ES 6 yield syntax highlighting issue.

**Comment by ElfenLiedGH** [comment] 2015-12-22 07:13
@jnystrom yes, it's different issue... I made it.

**Comment by jnystrom** [comment] 2015-12-22 07:20
@egamma I changed the theme to Monakai, and still the same issue.
<img width="664" alt="screen shot 2015-12-22 at 2 16 55 am" src="https://cloud.githubusercontent.com/assets/1293142/11950003/98c33ece-a852-11e5-9c86-152b8c901664.png">

**Comment by aeschli** [comment] 2016-01-13 14:21
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/29

**Closed by aeschli** 2016-01-13 14:21 UTC
