### ISSUE TITLE
When VSC in Full Screen, double clicking on Console Msg in Unity, VSG does not get active before one selects 'Window' -> Bring all to Front

### ISSUE THREAD

**Issue by Fritsl** [Microsoft/vscode#26155] opened 2017-05-07 11:30 UTC
- VSCode
<img width="1018" alt="skaermbillede 2017-05-07 kl 13 25 28" src="https://cloud.githubusercontent.com/assets/15021408/25780489/b7ccfdc0-3328-11e7-830c-b90548752512.png">
 Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.2.0|
|unity-snippets|YclepticStudios|0.1.2|
|theme-dracula|dracula-theme|1.14.0|
|eppz-code|eppz|1.2.22|
|theme-material-theme|jprestidge|1.0.1|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

1. One Monitor only / Laptop: VSC in full / Maximized window
2. Run Unity, (does not matter if Unity is maximized)
3. get Console output in Unity, Double click on Console output
4. VSC Opens as should, but then again it does not: It's active in Task bar, but it's window do not appear before one force as in Screenshot.

Problem: One cannot run VSC in full screen and then just get to code from unity by clicking on Unity console output..

**Comment by bpasero** [comment] 2017-05-08 04:41
@Fritsl and in 1.11 it worked fine? Might be electron update related.

**Comment by Fritsl** [comment] 2017-05-08 06:14
@bpasero I'm sorry, I cannot help with any back tracing, I've been on Monodevelop till a couple of days ago. Just fired VSC up, it's great but the lack of smooth full Screen workflow is a killer when on Laptop.

**Comment by bpasero** [comment] 2017-05-08 08:15
Hm, how is that related to my question?

**Comment by Fritsl** [comment] 2017-05-08 12:09
@bpasero Ha, I'm sorry if I did not read you right, I read this as your question:

> in 1.11 it worked fine?

and since I'm on 1.12, I figured you asked if this was an issue in 1.11, and I tried to aswer that question qith

> I'm sorry, I cannot help with any back tracing, I've been on Monodevelop till a couple of days ago.

Cheers

**Comment by bpasero** [comment] 2017-05-08 15:05
@Fritsl can you do me the favour of seeing if this reproduces with Code 1.11 (get it from here: https://az764295.vo.msecnd.net/stable/6eaebe3b9c70406d67c97779468c324a7a95db0e/VSCode-darwin-stable-unsigned.zip)

**Comment by Fritsl** [comment] 2017-05-08 20:41
I'm sorry, it was pretty messy to install 1.12 as it was, I'm still occasionally getting a blue CLI-error, and I need to work on my project, don't have the resources to take on task of going back forth right now. Sorry.

**Comment by bpasero** [comment] 2017-05-20 06:04
Closing due to lack of reproducible steps.

**Closed by bpasero** 2017-05-20 06:04 UTC
Labels: needs more info
