### ISSUE TITLE
Workspace settings are not applied when duplicated in a new window

### ISSUE THREAD

**Issue by alanrgan** [Microsoft/vscode#57105] opened 2018-08-23 20:04 UTC
- VSCode Version: 1.26.1
- OS Version: macOS High Sierra 10.13

Steps to Reproduce:

1. Open a workspace in VSCode
2. Use the command 'Duplicate Workspace in New Window'
3. Open Workspace settings.

Does this issue occur when all extensions are disabled?: Yes

Not sure if this is intended behavior, but when you use the command 'Duplicate Workspace in New Window' none of the workspace settings are applied. If this is intended behavior, what is the rationale for not applying workspace settings in the duplicate window?

**Comment by bpasero** [comment] 2018-08-24 05:37
@alanrgan I cannot reproduce this behaviour for me the contents of the "settings" node in the workspace file are copied over. What is not copied over for you?

**Comment by alanrgan** [comment] 2018-08-24 19:52
@bpasero My workspace settings look like this:

```
{
	"folders": [
		{
			"path": "website"
		}
	],
	"settings": {
		"files.exclude": {
			"migrations": true,
			"**/*.sass-cache": true,
			"**/*.map": true,
			"**/*.pyc": true,
			"**/*.vscode": true,
			"**/*.egg-info": true,
			"**/*.sqlite*": true,
			"**/__init__.py": true,
			"tests/coverage": true,
			"static/dist": true
		},
		"search.exclude": {
			"**/node_modules": true,
			"**/bower_components": true
		}
	}
}
```

But in the duplicated window, the workspace settings are empty:

```
{
	"folders": [
		{
			"path": "/Users/alanrgan/Documents/Programming/webdev/website",
			"name": "website"
		}
	],
	"settings": {}
}
```

**Comment by bpasero** [comment] 2018-08-25 06:31
@alanrgan thanks I can reproduce

@sandy081 there is a check to not include settings of scope `ConfigurationScope.RESOURCE` when copying over to the workspace file. Do you have any clue why we did that? Seems to be there for a long time:

https://github.com/Microsoft/vscode/blob/02420dbede10d10a5020bd5228a0244fb82fba21/src/vs/workbench/services/workspace/node/workspaceEditingService.ts#L253

Maybe we added the `ConfigurationScope.RESOURCE` only later and then forgot to adopt it there?

I also wonder if the `notMultiRootAdopted` property should still be used, it seems to do a questionable check on the keywords of an extension for `multi-root ready` which is probably not being used anymore by now.

**Comment by sandy081** [comment] 2018-08-27 08:27
This `copySettings` method was added to support migrating a folder workspace to multi-root workspace when a folder is added to single folder workspace. In this case, to retain the window UI state I copy only window specific settings. 

This was called `migrateSettings` before and looks like it got renamed to `copySettings` and got used for `Duplicating Workspace` action.

**Comment by bpasero** [comment] 2018-08-27 09:35
Oke will check.

**Comment by bpasero** [comment] 2018-08-27 12:11
@sandy081 fixed via https://github.com/Microsoft/vscode/commit/3a2b2b27cde6010cc04afb498a285720c2c37491. I will leave it up to you if we want to keep `notMultiRootAdopted` around. I find the name a bit weird too...

**Closed** 2018-08-27 12:10 UTC
Labels: bug, multi-root

**Comment by sandy081** [comment] 2018-08-27 14:08
@bpasero Removed `notMultiRootAdopted` attribute
