### ISSUE TITLE
Variable not updating in variables view after setValue

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#14362] opened 2016-10-25 08:49 UTC
Testing #14305 (Might not be related)

- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:

1. Create a snippet that contains an Array. Say:
```
let myArray = [1, 2, 3, 4, 5]
....
```
2. Put a break point after array definition. Start debugging 
3. After break point is hit, change the length of myArray to say `0`

Expected:
Array values should be updated

Actual:
Array values remain as before.
Confirmed in the debug console that array values are modified

**Comment by weinand** [comment] 2016-10-26 10:45
@sandy081 how are you changing the length of myArray to 0? in the REPL or code?

When changing the length to length in code, the VARIABLEs view is updated properly,
when doing this in the REPL the VARIABLEs view is not updated (but the WATCH view is).

This works as designed.

**Comment by isidorn** [comment] 2016-10-26 11:04
This is a duplicate of https://github.com/Microsoft/vscode/issues/2399

**Comment by sandy081** [comment] 2016-10-26 11:23
@weinand I am changing the value from the variables view using `Set Value`

**Comment by isidorn** [comment] 2016-10-26 12:04
Then not a duplicate -> reopening

**Comment by isidorn** [comment] 2016-10-26 12:58
Works for me.
@sandy081 please provide details on what you are doing differently than me

![sandeep](https://cloud.githubusercontent.com/assets/1926584/19726741/acc8a0de-9b8c-11e6-8842-2239aa9ad3fd.gif)

**Comment by sandy081** [comment] 2016-10-26 13:03
@isidorn I am doing the same.. After setting the length value to zero.. Check the values of the array in the console. 

`myArray[0]` gives undefined

But the variable view still shows the previous values.

**Comment by isidorn** [comment] 2016-10-26 13:12
Got it now. Ok it is actually a subset of the issue I closed as the duplicate.
It is just that the variables view needs a full refresh whenever something is reveealuated and that other issue describes that quite well. Fixing that will also fix this corner case

**Closed by isidorn** 2016-10-26 13:12 UTC
Labels: debug, needs more info
