### ISSUE TITLE
Using a generic like `Omit` on a `@deprecated` field in TS removes its strikethrough

### ISSUE THREAD

**Issue by Ayc0** [microsoft/vscode#133886] opened 2021-09-27 18:01 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: I'm using the last version of TS (4.4) and the last version of VSCode
- OS Version: Same on macOS and in the web version of VSCode so I don't think that it's relevant here

In this code snippet, we can see that `world` is deprecated. But in the interface `B`, as we are using `Omit`, we are loosing the strike trough afterwards:

![image](https://user-images.githubusercontent.com/22725671/134960732-ab3593c0-08ab-48cb-bca2-efe862e1b412.png)

The weird thing is that `@deprecated` is still in the description when we hover on the variable:

![image](https://user-images.githubusercontent.com/22725671/134960843-d96dd1e1-07b7-444d-ab10-5675175d4e08.png)

Here is the snippet to reproduce: [TypeScript Play](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QegCpDkABAEwgAcoIE5JzlKBnBKYKsYAexGUL4ceABYQANuJ4AuZCzAcQAc2G4A7jyjjyAflkgArgFsARtCwBfLFlCRYiFACFkEAB6QQ5FsgDyR4GAAPKgANMgA5Bpa5OEAfJiqyFHasvKKSgDclta20PBIyADCLu4Qnt7o2HjIMDwyyIam5lZYCHzyyEoQYOgAvMgAFBjIYpI8yBayqACUyL3xQ6NSFtNZbSAdcFNzmEv14WmgSuEt6x1dYM79QyMSUhOyjrPzgxh7K2vtYMgmjztvd32h2U4TCyXIsgOCiOJ2sZ2+F2K12GeweRWeCwBYw+rS+yAQsiRu0BkOBxzCtXqAEYWkA)

I don't know if that's a bug in TypeScript or in VSCode, but as `@deprecated` is present in the description, I think that it might be a VSCode error

**Comment by IllusionMH** [comment] 2021-09-27 19:28
`Omit` uses `Pick` which is mapped type. 
/duplicate of https://github.com/microsoft/TypeScript/issues/42609

You should add your use case in that issue but with more real world examples.

**Closed** 2021-09-27 19:29 UTC
Labels: *duplicate

**Comment by Ayc0** [comment] 2021-09-30 09:39
Thanks @IllusionMH!
I looked for a similar issue but I didn't find it. Sorry for the noise
