### ISSUE TITLE
IME candidate window is misplaced on Ubuntu 18.04

### ISSUE THREAD

**Issue by atsuoishimoto** [microsoft/vscode#58735] opened 2018-09-15 13:35 UTC
- VSCode Version: 1.28.0-insider
- OS Version: Ubuntu 18.04

Usually, when I enter Japanese text with IME, candidate window is placed at same position with caret.

But when I use HiDPI Display (Dell xps 13 3840*2160) and I set scale to 200%, then candidate window is misplaced as screenshot below.  

![screenshot from 2018-09-15 22-15-18](https://user-images.githubusercontent.com/1088786/45586607-08645b00-b935-11e8-80a6-fffe801c15f7.png)

1. Close running vscode.
2. On HiDPI Display environment, set scale to 200% (Settings->Devices->Displays).
3. Start vscode
4. Enter Japanese text with IME. I reproduced this issue with two ime package, ibus-mozc and fcitx-mozc. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by krupenja** [comment] 2018-11-26 15:21
I think this is a duplicate of #34079.

**Closed** 2019-10-09 10:11 UTC
Labels: *out-of-scope, editor-ime, electron, linux, upstream
