### ISSUE TITLE
can't install any extension

### ISSUE THREAD

**Issue by onlyhasbi** [microsoft/vscode#173761] opened 2023-02-08 07:17 UTC
Type: <b>Bug</b>

why my vscode cant install extension. no proxy, dns, or extra configuration

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.90GB free)|
|Process Argv|--crash-reporter-id 3587f428-e108-4ba2-897a-c80205b2af50|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
jest-snippets|and|1.9.1
vscode-tailwindcss|bra|0.9.7
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.10.4
vscode-firefox-debug|fir|2.9.8
vscode-jest-runner|fir|0.4.60
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-language-babel|mgm|0.0.36
code-beautifier|mic|2.3.3
inline-fold|moa|0.2.2
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.23.1
LiveServer|rit|5.7.9
autoimport|ste|1.5.4
ayu|tea|1.0.5
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.20
vscode-icons|vsc|12.2.0
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
89544117:30613380
pythonsymbol12:30657548

```

</details>

**Comment by simonamc** [comment] 2023-02-10 12:11
Possible duplicate of https://github.com/microsoft/vscode/issues/173684

**Comment by sandy081** [comment] 2023-02-15 15:29
> why my vscode cant install extension

Can you please elaborate more? Do you see any error or something?

**Comment by onlyhasbi** [comment] 2023-02-21 01:55
I thought there was a problem with the network I was using, after getting a stable network, the problem didn't happen again.

**Comment by sandy081** [comment] 2023-02-21 08:52
Closing this as you cannot reproduce it anymore.

**Closed by sandy081** 2023-02-21 08:52 UTC
Labels: info-needed, extensions
