### ISSUE TITLE
Allow opening the same folder in the same workspace in two separate windows

### ISSUE THREAD

**Issue by ChristopherJTrent** [microsoft/vscode#201939] opened 2024-01-06 22:56 UTC
All I want to do is have a feature complete second window including the file explorer that will allow me to work on the same folder on both monitors without having to manually drag tabs between the two windows. 
I additionally don't want the stupid "save these workspace settings" popup that comes from using "duplicate workspace" preventing me from closing that second window later.

**Comment by ChristopherJTrent** [comment] 2024-01-06 22:58
OK, there is a current workaround. 
Open the folder I want to use in a tab, ignore the warnings that it cannot be displayed, drag it onto monitor 2, click open folder, close the slave window that contained the tab, close the tab that got dumped back into the first window, then move the window that got opened by pressing open folder onto my second monitor.

**Comment by bpasero** [comment] 2024-01-10 11:36
This is a duplicate of https://github.com/microsoft/vscode/issues/2686 which we closed as out of scope.

You can use the command to duplicate a workspace into a new window:

<img width="716" alt="image" src="https://github.com/microsoft/vscode/assets/900690/16aef771-fe83-471b-b20d-ff2481de716a">

We made some decisions in the beginning of the project around workspace identity and unfortunately allowing to open the same folder in multiple windows requires to use this command for now. You cannot just open a new window and then open a folder or workspace that is already opened.

**Closed by bpasero** 2024-01-10 11:36 UTC

**Comment by ChristopherJTrent** [comment] 2024-01-10 16:27
You'd think a multi-billion dollar company like microsoft could figure out how to implement this simple feature, but apparently not.
