### ISSUE TITLE
Terminal opens automatically when resizing output panel

### ISSUE THREAD

**Issue by sh00kti** [microsoft/vscode#194254] opened 2023-09-27 06:17 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.82.2
- OS Version: Ubuntu 22.04 LTS

Steps to Reproduce:

1. Install [Microsoft's Arduino extension](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino) (however, I do not think this bug is extension dependent)
2. Specify sketch and microcontroller in arduino.json corresponding to that extension. Essentially, you should be able to use the 'upload' button correctly once setup.
3. Whenever VS Code is launched, the Arduino extension automatically opens up an output panel at the position remembered from the last VS Code session.
4. When trying to resize this output panel using the mouse, a terminal opens up next to it unprompted.
![annoyingTerminal](https://github.com/microsoft/vscode/assets/75242984/fa8b012a-4993-472d-b0b0-b41fe91a22a4)

**Comment by sbatten** [comment] 2023-09-27 19:08
seems to be a duplicate of https://github.com/microsoft/vscode/issues/194254. maybe we can figure something out with 2 reproers

**Closed by sbatten** 2023-09-27 19:08 UTC

**Comment by sh00kti** [comment] 2023-09-28 08:18
@sbatten #194254 is this issue itself, was that a typo?

**Comment by sbatten** [comment] 2023-09-28 21:30
yes, oops https://github.com/microsoft/vscode/issues/190972
