### ISSUE TITLE
Mouse cursor dissapears when i move it to the editor area.

### ISSUE THREAD

**Issue by ashen92** [microsoft/vscode#204181] opened 2024-02-02 19:04 UTC
Type: <b>Bug</b>

Actual - Move mouse cursor to the editor area.
Expected - Cursor should be always visible.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5625U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.36GB (9.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
composer-php-vscode|DEV|1.43.14858
intelli-php-vscode|DEV|0.12.14619
phptools-vscode|DEV|1.43.14858
profiler-php-vscode|DEV|1.43.14858
copilot|Git|1.156.0
copilot-chat|Git|0.12.0
vscode-drawio|hed|1.6.6
twig-language|mbl|0.9.4
git-graph|mhu|1.30.0
vscode-azurecache|ms-|0.1.0
vscode-azureappservice|ms-|0.25.1
vscode-azureresourcegroups|ms-|0.8.3
vscode-docker|ms-|1.28.0
autopep8|ms-|2023.8.0
debugpy|ms-|2024.0.0
python|ms-|2024.0.0
vscode-pylance|ms-|2023.12.1
remote-containers|ms-|0.338.1
azure-account|ms-|0.11.6
vscode-speech|ms-|0.4.0
sqltools|mtx|0.28.1
sqltools-driver-mysql|mtx|0.6.0
material-icon-theme|PKi|4.33.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.1
php-debug|xde|1.34.0
material-theme|zhu|3.16.2

</details>

**Comment by KamilEterna** [comment] 2024-02-03 10:54
I have the issue too, also not visible in terminal (bottom panel).
I found that it gets visible after ~2 seconds spent in the same editor. If I move it to another (split) editor then it is invisible for 2 seconds.

**Comment by RyanZhou416** [comment] 2024-02-08 19:56
Under the Light Modern theme in VSCode, the cursor becomes white, making it indistinguishable from the background.  However, it briefly changes back to black when right-clicking.

https://github.com/microsoft/vscode/assets/132639254/9621d5ab-cf99-45fd-bc2f-8ff7b548413c

**Comment by ashen92** [comment] 2024-02-09 05:59
This happens with other default light themes too. Only in light themes not dark themes.

**Comment by KamilEterna** [comment] 2024-02-09 07:56
It seems to me that it happened after a windows update. This issue also appears for me on Google Docs where the page is white.

**Comment by bvazx** [comment] 2024-02-09 23:03
I have the same problem with the cursor. I had to roll back to version 1.85.2, this problem does not exist there.
As far as I know, VSCode is built on the basis of Chromium. Just like Edge. Such a bug exists in this browser. It used to be more noticeable, now less… Apparently, this needs to be fixed somewhere deeper, in the same Chromium.

**Comment by AnWeber** [comment] 2024-02-15 17:28
I also observed the problem in the current Chrome Version (121.0.6167.161). After a short wait, the cursor turns black for me (in VSCode and Chrome). 
A rollback to the previous VSCode version also prevents the problem for me.

![chrome_issue](https://github.com/microsoft/vscode/assets/13434739/d71d500e-bf22-454d-9f33-fa1ee8934181)

**Comment by MikuAuahDark** [comment] 2024-02-16 10:52
Same thing happend to me. A workaround is to use dark theme but I don't want to use dark theme when coding.

**Comment by jeanfgagnon** [comment] 2024-02-26 15:08
Had the same issue.  Using a dark theme and a larger, orange, mouse cursor.  Reverting to 1.85.2 fixed the issue.

**Comment by AnWeber** [comment] 2024-02-26 16:28
Disabling GPU acceleration works for me AS workaround
```
1. Open command pallete (Ctrl + Shift + P)
2. Enter "Preferences: Configure Runtime Arguments"
3. Add config: "disable-hardware-acceleration": true
4. Restart VS Code
```

**Comment by MikuAuahDark** [comment] 2024-02-29 02:06
Still reproducible in 1.87 stable and Insiders 1.88 (8c2b09c0443b94d75a73819ed35610f7e09375ae).

**Comment by sowodev** [comment] 2024-02-29 13:03
As I commented on #204103. I'm having the same issue. It seems to come from the OS (idk how it behaves in other OSs, rather than Windows), and it intensifies terrebly with VSCode.

Workaround: 

The best (and easiest) way around this on Windows, without changing the settings of the VSCode is through the mouse setting on the Operating System. Go to 'Start -> Settings -> Accessibility -> Mouse pointer and touch', under 'Mouse pointer style', change the style to 'Black', it will fix it. Or under 'Size', change the size of the pointer, it will also fix it.

![vscode-cursor-fix-for-light-themes](https://github.com/microsoft/vscode/assets/49458298/2a420fff-f5d3-4a31-ab21-204559533951)

**Comment by david-morris** [comment] 2024-03-07 12:48
I am also affected.  I notice that snapping the window into another screen can make this temporarily stop.
Here's a weird part: when I record the screen with the built-in windows tool that seems to be intended for gaming, it strips this bug and the cursor finder from PowerToys!

**Comment by arisudesu** [comment] 2024-04-05 20:20
This happens on my setup too. This is very annoying and disorienting.

**Comment by MikuAuahDark** [comment] 2024-04-06 01:51
After more investigation, it looks like this is AMD's fault. For now, the best solution would be:
* Allow `--disable_direct_composition=1` in `argv.json`
* Downgrade Chromium to version that was used in 1.85 where it doesn't occur.

**Comment by arisudesu** [comment] 2024-04-09 22:38
@MikuAuahDark you guessed right, I have Radeon RX 6750, Adrenalin Software ver. 24.3.1. `"disable-hardware-acceleration": 1` in argv.json fixes the problem for the time being.

**Comment by MikuAuahDark** [comment] 2024-04-14 03:20
`"disable-hardware-acceleration": 1` completely disables hardware acceleration, resulting in higher CPU usage, while `--disable-direct-composition=1` keeps them enabled with slightly increased power usage (important for laptops).

Also changing the pointer is not an option for me because larger cursor size looks ugly and it takes time to get used to.

Perhaps someone can send PR to allow "disable_direct_composition` in argv.json? Probably the best method for now without downgrading Chromium.

**Comment by bvazx** [comment] 2024-04-20 11:07
More information [here](https://forums.guru3d.com/threads/solution-fix-checkerboard-like-patterns-randomly-appearing-in-chromium-based-applications.449341/).

**Comment by bvazx** [comment] 2024-04-20 11:26
> After more investigation, it looks like this is AMD's fault and it's been a thing for 1-2 years.

No, this is a Windows bug that has already been fixed in the dev and canary builds. Microsoft is about to roll out updates for stable.

**Comment by arisudesu** [comment] 2024-04-20 11:38
I hope that this fix gets to Windows 10 before it reaches EOL, not only Win 11.

**Comment by bbyby** [comment] 2024-05-27 10:31
Same problem appeared and it's very annoying. Tried to apply such thing, I changed cursor theme - made it dark. Maybe it will help someone.

**Comment by alexdima** [comment] 2024-06-12 19:02
Let's track in https://github.com/microsoft/vscode/issues/204103

**Closed by alexdima** 2024-06-12 19:02 UTC
