### ISSUE TITLE
Request: Command to view all snippets

### ISSUE THREAD

**Issue by Phrohdoh** [Microsoft/vscode#45110] opened 2018-03-06 05:11 UTC
Seeing all snippets available is useful especially when showing how an extension can make development faster and easier.

**Comment by DanTup** [comment] 2018-03-06 07:52
@jrieken This came about from Dart Code. I recently moved my snippets to the completion provider so I could enable them for the correct project type (based on our discussions in #41202) but this means Code doesn't know about them and therefore they don't appear in the `Insert snippets` list.

It would be great if we could have context-aware snippets without having to have them drop off this list (they're somewhat undiscoverable by users now).

**Comment by jrieken** [comment] 2018-03-06 08:01
closing this as dupe of #45039. While that talks about filtering an implementation might add some kind of dynamic buttons to the suggest widget itself

**Closed by jrieken** 2018-03-06 08:01 UTC
Labels: suggest
