### ISSUE TITLE
Codespace fails to show readme with unexpected error while restoring Markdown preview

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#165669] opened 2022-11-06 23:10 UTC
The readme.md in my codespace is reliably failing to load on reload:

`An unexpected error occurred while restoring the Markdown preview.`

<img width="987" alt="image" src="https://user-images.githubusercontent.com/8599/200200423-0bd7fed5-b44b-41e6-b6f7-3fa6a62fd455.png">

```
[Extension Host] TypeError: Cannot read properties of undefined (reading 'resource')
    at _.deserializeWebviewPanel (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/extensions/markdown-language-features/dist/extension.js:1:1740155)
    at o.$deserializeWebviewPanel (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:94:199942)
    at l._doInvokeHandler (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:13680)
    at l._invokeHandler (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:13362)
    at l._receiveRequest (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:12132)
    at l._receiveOneMessage (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:10834)
    at /vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:8941
    at h.invoke (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2559)
    at g.fire (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2137)
    at r.fire (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:16518)
    at /vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:118:17000
    at h.invoke (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2559)
    at g.fire (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2137)
    at r.fire (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:16518)
    at o._receiveMessage (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:21330)
    at /vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:18773
    at h.invoke (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2559)
    at g.fire (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2137)
    at g.acceptChunk (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:13342)
    at /vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:12472
    at Socket.i (/vscode/bin/linux-x64/e764c5b816a99eb8673b2fc4fc028827f202872f-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:24597)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

Version: 1.74.0-insider
Commit: e764c5b816a99eb8673b2fc4fc028827f202872f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.10
Embedder: codespaces

**Comment by tamuratak** [comment] 2022-11-10 08:17
It might be a duplicate of #165590.

@digitarald I guess you see the same error on VS Code Insiders (Desktop).

CC: @mjbvz

**Comment by mjbvz** [comment] 2022-11-10 19:58
Thanks  @tamuratak.  Yes the is a duplicate of https://github.com/microsoft/vscode/issues/165590. Taking a look now

**Closed by mjbvz** 2022-11-10 19:58 UTC
Labels: web
