### ISSUE TITLE
macOS BigSur 11.1 - VSCode won't update without admin credentials 

### ISSUE THREAD

**Issue by ezequiel2611** [microsoft/vscode#115805] opened 2021-02-04 23:42 UTC
- VSCode Version: 1.52.1
- OS Version: macOS BigSur 11.1

Steps to Reproduce:

1. Check for updates using an standard user account on macOS

I have seen another issues report from past years and tried the fixes doing:

sudo chown -R $USER  ~/Library/Caches/com.microsoft.VSCode.ShipIt/*
sudo xattr -dr com.apple.quarantine "/Applications/Visual Studio Code.app"

None of this worked, after launching VSCode again and checking for updated, it ask for admin credentials to install it 
![Screen Shot 2021-02-04 at 20 41 31](https://user-images.githubusercontent.com/31822784/106969354-6faf1f80-6729-11eb-87f3-f6570e8a1de3.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by deepak1556** [comment] 2021-02-05 21:34
@ezequiel2611 which user owns the VSCode app ? If it is not owned by your user account then this pop-up will show.

**Comment by ezequiel2611** [comment] 2021-02-05 21:44
Hi! @deepak1556 the app is owned by root:wheel like other apps that are installed. This need of the user being owner of the app to be able to update it is a special need of VSCode? 
Other apps like O365 are owned by root and every user can update them without problems.

**Comment by ezequiel2611** [comment] 2021-02-05 21:56
Anyway, I tried what you recommended, I change the ownership to my standard user and the popup is still shown when I try to update VSCode 
![Screen Shot 2021-02-05 at 18 55 42](https://user-images.githubusercontent.com/31822784/107093373-e3156780-67e3-11eb-8b85-fc363a26118b.png)

**Comment by deepak1556** [comment] 2021-02-05 22:14
> This need of the user being owner of the app to be able to update it is a special need of VSCode?

It comes from the updater runtime, this issue is dupe of https://github.com/microsoft/vscode/issues/95534 and users there have seemed to resolved it by fixing the permissions on the app.

Is `~/Library/Caches/com.microsoft.VSCode.ShipIt` owned by the same user ?

**Comment by ezequiel2611** [comment] 2021-02-05 23:54
Interesting! But all permissions seems to be OK, VSCode app is owned by my user and "~/Library/Caches/com.microsoft.VSCode.ShipIt/" too. Restarted the mac and the same ocurrs. you will see also the temp file generated by the update in that moment, is owned by my user.

Only thing to consider is that my user is an standard user, no sudo, no wheel group.


![Screen Shot 2021-02-05 at 18 55 42](https://user-images.githubusercontent.com/31822784/107100752-0cd68a80-67f4-11eb-9dce-ddbbb1c7f1b4.png)

**Comment by MaxGraey** [comment] 2021-02-12 14:00
In my case ShipIt takes 100% cpu until I manually terminate this

**Closed** 2021-05-12 11:28 UTC
Labels: install-update, macos-big-sur, needs more info
