### ISSUE TITLE
decreaseIndentPattern and autocomplete cause autocomplete to replace word incorrectly

### ISSUE THREAD

**Issue by SteelPhase** [Microsoft/vscode#36928] opened 2017-10-25 18:33 UTC
- VSCode Version: 1.17.2 b813d12980308015bcd2b3a2f6efa5c810c33ba5 2017-10-16T13:43:44.213Z
- OS Version: macOS Sierra 10.12.6

There seems to be a race condition with decreaseIndentPattern and autocomplete where the autocomplete window doesn't close when typing the next character.

### Example script used with steps
```golang
package main

import "fmt"

func do(i interface{}) {
	switch v := i.(type) {
	case int:
		fmt.Printf("Twice %v is %v\n", v, v*2)
	case string:
		fmt.Printf("%q is %v bytes long\n", v, len(v))
	default:
		fmt.Printf("I don't know about type %T!\n", v)
	}
}

func main() {
	do(21)
	do("hello")
	do(true)
}
```

Steps to Reproduce:

1. Go to Ln 6, Col 27 located at the end of line 6 `switch v := i.(type) {`
2. hit enter
    - Cursor should go to Ln 7, Col 9
3. type `case float64:`
    - make sure to type everything out without using autocomplete
    - as `:` is typed, `decreaseIndentPattern` should kick in and move the line left 1 tab
    - the cursor now moves, but vscode still displays the autocomplete for `float64'
4. hit enter
    - vscode replaces `loat64:` with `float64` and the line looks like `case ffloat64`

Reproduces without extensions: Yes

**Comment by SteelPhase** [comment] 2017-10-25 18:50
This may be related to #29210

**Comment by jrieken** [comment] 2017-11-13 11:29
dupe of https://github.com/Microsoft/vscode/issues/34897

**Closed by jrieken** 2017-11-13 11:29 UTC
Labels: editor, editor-autoindent, suggest
