### ISSUE TITLE
git integration cannot work when the filepath inclues combining character on Mac OS

### ISSUE THREAD

**Issue by yumetodo** [microsoft/vscode#123108] opened 2021-05-06 10:50 UTC
- VS Code Version: 1.56.0 (Universal)
- OS Version: Mac OS X 10.15.7 19H2
- git version: 2.31.1 via homebrew
Steps to Reproduce:

1. create directory named with `ポ`(`"\u30DB\u309A"`)
2. create git repo with `git init` command
3. open the directory with vscode
4. create some file
5. stage the file using vscode  
   ![image](https://user-images.githubusercontent.com/10869046/117293112-f94ac680-aeab-11eb-97a5-b42af86a7aa9.png)
6. you can see `Git: fatal: /Users/<name>/ポ/foo.txt: '/Users/<name>/ポ/foo.txt' is outside repository`

Does this issue occur when all extensions are disabled?: Yes

**Comment by yumetodo** [comment] 2021-05-06 11:36
On Windows10 2004(19041.928), no problem.

Investigate steps:

1. create C++ program like below, compile with msvc(`_MSC_FULL_VER: 192829913`, `/std:c++17`)
   
   ```cpp
   #include <filesystem>
   #include <iostream>
   #include <iomanip>
   namespace fs = std::filesystem;
   int main()
   {
       fs::create_directories(U"test\\\u30DB\u309A");
       for (const fs::directory_entry& x : fs::directory_iterator("test")) {
           const auto p = x.path().u32string();
           if (const auto pos = p.find(U"\u30D2\u309A"); std::u32string::npos != pos) {
               std::cout << "found" << std::endl;
           }
           std::cout << p.length() << std::endl;
           bool flg = false;
           for (auto&& c : p) {
               if (std::exchange(flg, true)) std::cout << ", ";
               std::cout << std::hex << c;
           }
           std::cout << std::endl;
       }
   }
   ```
2. check the output. my output is below so that correctly the directory includes combining charactor was created.
   
   ```
   found
   7
   74, 65, 73, 74, 5c, 30db, 309a
   ```
3. In the directory, follow steps showing first post, no problem.

**Comment by yumetodo** [comment] 2021-05-06 12:01
@yoshi389111 says, Ubuntu on WSL on Windows + VSCode(Remote develop) env, no problem.
> https://qiitadon.com/@yoshi389111/106188133990173313
>
> LinuxのGUIは持っていないので、単なるにぎやかしですが
>
>Windows + WSL(Ubuntu) で、vscode のリモート接続でも、結合文字の"ポ"のディレクトリで、ステージングはできますね。
>
> 確認済なのかもしれませんけど

**Comment by manzyun** [comment] 2021-05-06 12:46
**IMHO**

# Summary

I can't reproduce this issue 😢 

However, I ran VSCode on [Flatpak](https://flatpak.org) and installed [Flathub repository](https://flathub.org/apps/details/com.visualstudio.code)... This repository is not unofficial.

And, Git version is `2.30.2` .

So, my reproduce is *not perfect* 🙇🏼 

# My Environments

<details>
<summary>VSCode's About</summary>

```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.0-18.1-liquorix-amd64
```

</details>
<details>
<summary>Any Environment</summary>

``` shell-session
$ git --version
git version 2.30.2

$ flatpak --version
Flatpak 1.11.1
```

</details>

# Suggestion to @yumetodo 

My environment git output log in VSCode at near `git add`:

```
> git ls-files --stage -- /home/<name>/ポ/poyo.py
git.stage 1
git.stage.scmResources 1
> git add -A -- /home/<name>/ポ/poyo.py
> git status -z -u
```

I hope this helps you if you check your logs.

**Comment by yumetodo** [comment] 2021-05-06 12:58
According to these investigations, we can sey that this issue occurs only on mac.

**Comment by yumetodo** [comment] 2021-05-07 02:51
It might be related with #41246...

**Comment by lszomoru** [comment] 2022-12-13 14:47
Closing this as duplicate of https://github.com/microsoft/vscode/issues/41246

**Closed by lszomoru** 2022-12-13 14:47 UTC
Labels: bug, git
