### ISSUE TITLE
Show dirty indicator close to file name if tabs are disabled

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29428] opened 2017-06-26 07:41 UTC
This piece of extension code will open a new file in the workbench and write `hello` inside.

```ts
const edit = new WorkspaceEdit();
const file = Uri.file('hello.txt').with({ scheme: 'untitled' });
const document = await workspace.openTextDocument(file);
const editor = await window.showTextDocument(document);
edit.insert(editor.document.uri, new Position(0, 0),'hello');
workspace.applyEdit(edit);
```

I have these settings:

```json
  "workbench.editor.showTabs": false,
  "workbench.editor.enablePreview": false,
  "files.autoSave": "afterDelay",
```

When that code runs, my workbench looks like this:

![image](https://user-images.githubusercontent.com/22350/27529082-7e47f990-5a53-11e7-8885-b1ad63f7a933.png)

Aside from the `1` badge in the Explorer, there is nothing that indicates that the file is indeed not saved. I have to press <kbd>Cmd S</kbd> to save it.

**Comment by bpasero** [comment] 2017-06-26 10:15
@joaomoreno can you share the full snippet please.

**Comment by bpasero** [comment] 2017-06-26 12:46
Related: https://github.com/Microsoft/vscode/issues/19531

**Comment by bpasero** [comment] 2017-10-12 16:08
Closing as duplicate of https://github.com/Microsoft/vscode/issues/19531

**Closed by bpasero** 2017-10-12 16:08 UTC
Labels: feature-request, workbench, workbench-tabs
