### ISSUE TITLE
Integrated terminal doesn't open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#42415] opened 2018-01-30 10:23 UTC
Windows

See attach screen cast. Nothing in the log

![cast](https://user-images.githubusercontent.com/1931590/35561256-0133f540-05b0-11e8-9415-7d7a2f5c75f3.gif)

**Comment by sandy081** [comment] 2018-01-30 13:52
This is blocking testing https://github.com/Microsoft/vscode/issues/42278

**Comment by aeschli** [comment] 2018-01-30 13:52
I see the same

**Comment by will-l-h** [comment] 2018-01-30 15:14
From the Developer Tools

![image](https://user-images.githubusercontent.com/14348617/35573887-52473d16-05a6-11e8-895d-b6aacbc91b0b.png)

**Comment by Tyriar** [comment] 2018-01-30 18:23
Should be fixed in latest insiders, was caused by asar changes

**Closed by Tyriar** 2018-01-30 18:23 UTC
Labels: bug, important, integrated-terminal

**Comment by maxibanki** [comment] 2018-01-30 18:48
@Tyriar it works, thanks!

**Comment by jtleaming** [comment] 2018-01-31 15:38
I'm still getting this behavior with 1.20.0-insider 648c46deeeda61fad44ce188684dcb61838b724a.

**Comment by ciruz** [comment] 2018-02-01 08:43
I just updated insiders, and it's still not working (I'm on commit: 9affae559e7b6dd46acfe2ac3123fb0ea87c6615)

**Comment by dbaeumer** [comment] 2018-02-01 11:34
Verified under 

```
Version 1.20.0-insider
Commit 9affae559e7b6dd46acfe2ac3123fb0ea87c6615
Date 2018-02-01T05:15:24.027Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
