### ISSUE TITLE
Terminal should be aware when a command execution finishes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#13351] opened 2016-10-07 14:04 UTC
Currently we support having a `preLaunchTask` specified in 'launch.json' to run a task before a user starts debugging (more details [here](https://code.visualstudio.com/docs/editor/debugging)). There are [requests](https://github.com/Microsoft/vscode/issues/10211) that we support running a `preLaunchTask` even if a user does not have 'tasks.json' setup.

My proposal for this is that the user could specify a full command in his 'launch.json' which we would just forward to our terminal via the `send` api. The only missing piece for this would be for the terminal to be aware when a command has finished running - or when it becomes idle. Currently this problem is solved in the task framewrok by @dbaeumer so maybe we could do something similar in our terminal.

I think @jrieken might be also interested in something similar for the passing of errors from our terminal to the marker service.

@Tyriar let me know what you think and if this request makes sense
@weinand fyi

**Comment by Tyriar** [comment] 2016-10-07 19:09
This is basically a duplicate of https://github.com/Microsoft/vscode/issues/11422, I'll reply over there.

**Closed** 2016-10-07 19:12 UTC
Labels: duplicate, feature-request, integrated-terminal
