### ISSUE TITLE
VS Code integrated terminal shows white blocks in replacement of cursor block

### ISSUE THREAD

**Issue by altjx** [microsoft/vscode#121133] opened 2021-04-12 18:42 UTC
- VS Code Version: Version: 1.55.1
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T18:22:52.186Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
- OS Version: macOS Big Sur version 11.2.3

Steps to Reproduce:

1. Open VS Code
2. Launch the integrated terminal
3. Use the "black" cursor (rather than line or underline)
4. Click anywhere outside of the integrated terminal to lose focus
5. Click back inside of the terminal and hit "Enter"
6. On the previous line, you'll notice a white square block

Does this issue occur when all extensions are disabled?: Yes

I have had this issue for quite some time, but it's become a lot more problematic lately. After using VS Code's integrated terminal for several hours, I notice that the "block' cursor tends to leave behind "outlined shadows" of itself. For example, if you click inside of the terminal, click outside of the terminal, go back to the terminal and hit "Enter", you'll notice the previous line leaves behind a "cursor shadow". Check this out:

![video](https://user-images.githubusercontent.com/4023423/114444849-5305ec80-9b9d-11eb-9182-73ed5990a9e2.gif)

I have been able to reproduce this even without any extensions being enabled at all (as shown in the above example)

**Comment by IllusionMH** [comment] 2021-04-12 19:36
Looks like duplicate of #106981

Do you have `window.zoomLevel` which is less than `0` in your settings?

Is it reproducible with if you launch VS Code as `code --disable-gpu`?

**Comment by altjx** [comment] 2021-04-12 19:51
Ahh wow!! Cannot believe it was due to the zoom level settings. @IllusionMH does this mean that we can't go below 0 and have it working? For me, zoom level 0 is a bit too big and -1 is absolutely perfect. Any thoughts?

Thanks so much for helping me pinpoint this issue.

**Comment by meganrogge** [comment] 2021-04-14 15:47
duplicate of #106981

**Closed by meganrogge** 2021-04-14 15:47 UTC
