### ISSUE TITLE
Walkthrough step card missing background color

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166044] opened 2022-11-10 20:16 UTC
Ref #165846

Likely related to the move to CSS variables.

## Before

<img width="387" alt="CleanShot 2022-11-10 at 12 14 35@2x" src="https://user-images.githubusercontent.com/25163139/201196695-029d365f-7f0f-4320-92fa-def9fc417d5f.png">

## Current 

<img width="373" alt="CleanShot 2022-11-10 at 12 13 53@2x" src="https://user-images.githubusercontent.com/25163139/201196563-c4cde173-6091-414b-b6f7-f1cd649e0196.png">

**Comment by bhavyaus** [comment] 2022-11-15 22:52
Dupe of [#165526](https://github.com/microsoft/vscode/issues/165526). Should be fixed with: https://github.com/microsoft/vscode/pull/166402

**Closed** 2022-11-15 22:52 UTC
Labels: getting-started
