### ISSUE TITLE
Allow to duplicate files from Side Bar

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#57922] opened 2018-09-05 01:48 UTC
Instead of copying and pasting files all the time which is 2 clicks, VS Code should be able to duplicate a file.

**Comment by mjbvz** [comment] 2018-09-05 02:39
Duplicate of #55127

**Closed by mjbvz** 2018-09-05 02:39 UTC

**Comment by zavr-1** [comment] 2018-09-05 08:13
@mjbvz I'm sorry I tried to search but so many things came up.
