### ISSUE TITLE
Long time before file is saved

### ISSUE THREAD

**Issue by louagej** [microsoft/vscode#140404] opened 2022-01-10 10:40 UTC
Issue Type: <b>Performance Issue</b>

Open file and save

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.66GB free)|
|Process Argv|--crash-reporter-id a0a8abb0-3b98-4321-86e5-2ab55d45c9c0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	  7828	code main
    0	    39	  6644	   utility-network-service
    1	   317	  7504	   extensionHost
   39	   575	  2104	     "c:\Users\Job Louage\.vscode\extensions\ms-dynamics-smb.al-8.2.552672\bin\win32\Microsoft.Dynamics.Nav.EditorServices.Host.exe" /browser:SystemDefault /logLevel:Normal
    0	    11	  6284	       console-window-host (Windows internal process)
    0	    64	  7896	     "c:\Users\Job Louage\.vscode\extensions\ms-mssql.mssql-1.12.0\sqltoolsservice\3.0.0-release.174\Windows\MicrosoftSqlToolsServiceLayer.exe"
    0	    11	  4784	       console-window-host (Windows internal process)
    0	    35	  8464	     "c:\Users\Job Louage\.vscode\extensions\ms-mssql.mssql-1.12.0\sqltoolsservice\3.0.0-release.174\Windows\SqlToolsResourceProviderService.exe" --log-file "c:\Users\Job Louage\AppData\Roaming\Code\logs\20220110T113540\exthost1\ms-mssql.mssql\resourceprovider.log" --tracing-level Critical
    0	    11	 28128	       console-window-host (Windows internal process)
    0	    70	 14340	     "C:\Users\Job Louage\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Job Louage\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js" --node-ipc --clientProcessId=7504
    0	   259	 16368	     "c:\Users\Job Louage\.vscode\extensions\andrzejzwierzchowski.al-code-outline-3.0.26\bin\netcore\win32\AZALDevToolsServer.NetCore" "c:\Users\Job Louage\.vscode\extensions\ms-dynamics-smb.al-8.2.552672"
    0	    11	 13004	       console-window-host (Windows internal process)
    0	    74	 17148	     "C:\Users\Job Louage\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Job Louage\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js" --node-ipc --clientProcessId=7504
    0	    70	 25200	     "C:\Users\Job Louage\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Job Louage\.vscode\extensions\rasmus.al-var-helper-2.4.0\node_modules\vscode-languageclient\lib\utils\electronForkStart" "c:\Users\Job Louage\.vscode\extensions\rasmus.al-var-helper-2.4.0\server\server.js" --node-ipc --clientProcessId=7504
    0	     4	 29720	     C:\WINDOWS\system32\cmd.exe /d /s /c "docker ps -a --format "{{.ID}} {{.Names}} {{.Image}} {{.Status}}""
    0	    11	 20644	       console-window-host (Windows internal process)
    0	    27	 30668	       docker  ps -a --format "{{.ID}} {{.Names}} {{.Image}} {{.Status}}"
    0	    73	 30240	     "C:\Users\Job Louage\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Job Louage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7504
    2	   256	 13380	   window (● PurchaseOrder.Report.al - Reports (Workspace) - Visual Studio Code)
    0	    81	 13748	   issue-reporter
    2	   169	 19988	   gpu-process
    0	    25	 20220	   crashpad-handler
    0	   113	 20896	   shared-process
    0	    93	  4472	     ptyHost
    0	    73	  4092	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "Import-Module 'c:\Users\Job Louage\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Job Louage\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.12.0 <=====
' -LogLevel 'Verbose' -LogPath 'c:\Users\Job Louage\.vscode\extensions\ms-vscode.powershell-2021.12.0\logs\1641804839-e69feff5-2772-41d5-9954-da3052b3cf4f1641804133854\EditorServices.log' -SessionDetailsPath 'c:\Users\Job Louage\.vscode\extensions\ms-vscode.powershell-2021.12.0\sessions\PSES-VSCode-14224-322591' -FeatureFlags @() "
    0	     7	  4116	       console-window-host (Windows internal process)
    0	     7	 12616	       console-window-host (Windows internal process)
    0	     7	 13052	       console-window-host (Windows internal process)
    0	    70	 13504	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    69	 14644	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 15284	       console-window-host (Windows internal process)
    0	    71	 26628	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    67	 25184	     watcherServiceParcelSharedProcess
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● PurchaseOrder.Report.al - Reports (Workspace) - Visual Studio Code)
|    Folder (test): 18 files
|      File types: json(3) md(3) png(2) al(2)
|      Conf files: launch.json(1)
|      Launch Configs: al
|    Folder (app): 150 files
|      File types: al(57) app(22) rdlc(13) json(8) ps1(8) dll(5) png(4) md(4)
|                  xml(1) docx(1)
|      Conf files: launch.json(1)
|      Launch Configs: al;
```

</details>
<details><summary>Extensions (102)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
nugetpackagemanagergui|ali|1.1.9
al-code-outline|and|3.0.26
ACF-Snippet|ant|1.9.0
odatatools|apa|2.0.1
vscode-subtitles|ast|0.4.0
vscode-browser-preview|auc|0.7.2
azurite|Azu|3.15.0
al-toolbox|Bar|2.0.18
phpserver|bra|3.0.2
vscode-expo|byC|0.7.4
woocommerce|cla|1.1.0
wpcs-whitelist-flags|cla|1.1.0
dynamics-nav-scm|clo|0.2.0
vscode-dgmlviewer|cod|2.2.2
doxdocgen|csc|1.3.2
al-codeactions|dav|1.0.18
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
vscode-pandoc|Dou|0.0.8
gitlens|eam|11.7.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
php-code-sniffer|ETu|1.0.6
php-pack|fel|1.0.2
code-runner|for|0.11.6
docker-explorer|for|0.1.7
vscode-yarn|gam|2.0.0
todo-tree|Gru|0.0.214
vscode-guid|hea|1.4.20
rest-client|hum|0.24.6
phpcs|ika|1.0.5
RelativePath|jak|1.4.0
al-test-runner|jam|0.6.2
plantuml|jeb|2.17.0
mdal|jon|0.4.1
wordpress-vscode-extensionpack|jpa|1.2.0
vscode-insertdatestring|jsy|2.3.0
al-object-designer|mar|0.2.4
git-graph|mhu|1.30.0
code-beautifier|mic|2.3.3
fluent-icons|mig|0.0.15
docfx-toc-generator|Mom|0.0.3
azure-pipelines|ms-|1.195.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.18.0
vscode-logicapps|ms-|1.0.26
csharp|ms-|1.23.17
al|ms-|8.2.552672
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.12.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
azure-account|ms-|0.9.11
azurecli|ms-|0.5.0
node-debug2|ms-|1.43.0
powershell|ms-|2021.12.0
vscode-react-native|msj|1.8.1
sqltools|mtx|0.23.0
nab-al-tools|nab|1.10.0
sftp|Nat|1.15.10
php-docblocker|nei|2.6.1
gulptasks|nic|1.3.1
snippet-creator|nik|0.0.5
createGUID|nwa|0.0.2
vetur|oct|0.35.0
fix-json|oli|0.1.2
al-var-helper|ras|2.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
xliff-sync|rva|1.2.0
partial-diff|ryu|1.4.3
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.1
vscode-scss-formatter|sib|2.3.3
prism-al|sta|1.1.0
businesscentral-lintercop|ste|0.1.0
vscode-microsoftteams|ste|1.0.6
alrunner|tfe|3.3.3
umlet|the|1.0.4
html-preview-vscode|tht|0.2.5
graphviz-interactive-preview|tin|0.0.12
errorlens|use|3.4.1
vjeko-al-objid|vje|2.2.0
vscode-icons|vsc|11.8.0
al-extension-pack|wal|1.0.19
crs-al-language-extension|wal|1.4.11
vscode-todo-highlight|way|1.0.5
al-navigator|wbr|0.4.8
wordpress-toolbox|wor|1.3.11
ReactSnippets|xab|2.4.0
gulp-run|yod|0.0.2
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vscexrecpromp3t1:30407762

```

</details>

**Comment by IllusionMH** [comment] 2022-01-10 10:49
/needsMoreInfo

Does it depen on type of the file to see slowdown?
Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by louagej** [comment] 2022-01-10 11:17
Hi,
Se my answers blow the questions:

1. Does it depend on type of the file to see slowdown?

    > Yes, this only happen with filetype *.al ([AL Development](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-reference-overview))


2. Is it reproducible with all extensions disabled? You can try this with F1 and >Developer: Reload Window With Extensions Disabled

    > No, not reproducible  with extensions disabled

**Comment by IllusionMH** [comment] 2022-01-10 11:59
/causedByExtension

Looks like it's related to extension and not VS Code editor itself, as it's happens only to files that are not supported by VS Code out of the box and not reproducible without extensions

You can try to check settings available for AL related extension or other enabled settings with `onSave` in them (e.g. `editor.codeActionsOnSave`).

You can try [extensions bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to find exact extension, but I guess it's "AL Language" and this might be duplicate of https://github.com/microsoft/AL/issues/6394 and/or https://github.com/microsoft/AL/issues/5664

Try to disable this extension and see if those issues have some workarounds mentioned.

**Closed** 2022-01-10 12:00 UTC
Labels: needs more info, *caused-by-extension, triage-needed
