### ISSUE TITLE
Reveal selected launch config when selecting configure

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27850] opened 2017-06-01 14:04 UTC
* have a complex `launch.json`-file (like ours)
* have one entry select, like "Attach To Main process"
* select the configure gear icon
* the file opens but reveal my last edit location and I have to hunt for the current config. I'd say usability can be improved by revealing the source of "Attach to Main process"

**Comment by isidorn** [comment] 2017-06-01 14:31
I think this makes somewhat sense, but not a huge fan as it can lead to undesired behavior as it will behave differently from how we open other files (last edit location).
The good thing about last edit location is that it is almost always right, even in this case.

Would you also prefer this behavior when you open launch.json via command palette action?

**Comment by jrieken** [comment] 2017-06-01 14:42
> Would you also prefer this behavior when you open launch.json via command palette action?

No, because that says edit the file, but in other case I way "Edit 'Attach to Main Process'" and then I want to see that. It is different from an ordinary editor imo

**Comment by isidorn** [comment] 2017-08-04 15:29
Duplicate of 31544

**Closed by isidorn** 2017-08-04 15:29 UTC
Labels: under-discussion
