### ISSUE TITLE
file is very large ....

### ISSUE THREAD

**Issue by brovarminski** [Microsoft/vscode#18936] opened 2017-01-20 19:25 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|CppSnippets|hars|0.0.5|
|cpptools|ms-vscode|0.9.3|

---

Steps to Reproduce:

1. Try to load 100MB text file 
2. Got this error: The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding.

Guys, even Notepad was able to load the file.

**Comment by alexandrudima** [comment] 2017-01-21 15:22
Please use the github issue search functionality before creating a new issue. Duplicate of #6474

**Closed by alexandrudima** 2017-01-21 15:22 UTC
Labels: editor
