### ISSUE TITLE
Funktioniert nach Update nicht mehr mit folgedem Fehler

### ISSUE THREAD

**Issue by gizzmo25** [microsoft/vscode#142777] opened 2022-02-10 22:12 UTC
Issue Type: <b>Bug</b>

Fehler beim Laden der Webansicht: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (18.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.7
vscode-database|baj|2.2.3
vscode-language-pack-de|MS-|1.64.6
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1001821375
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
powershell|ms-|2021.12.0
vscode-xml|red|0.18.3
vscode-yaml|red|1.4.0

</details>

**Comment by joaomoreno** [comment] 2022-02-15 10:32
Can you share a screenshot of the error?

**Comment by gizzmo25** [comment] 2022-02-15 19:19
Hi @joaomoreno I found the solution... It happens, after a Visual Code update, that was done with "runas admin". After it was successfully reloaded, nothing works anymore. The fix was, to rerun Visual Code as admin and wait till the update notification was shown and at the end I could work as a standard user again.

**Comment by bpasero** [comment] 2022-02-16 06:59
Duplicate of https://github.com/microsoft/vscode/issues/122951

**Closed** 2022-02-17 09:57 UTC
Labels: needs more info
