### ISSUE TITLE
Extension Debugee does not start when there is a preLaunchTask

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#57346] opened 2018-08-28 09:09 UTC
Testing #56822

- Open the hello-world extension in VS Code
- Have a watch npm script in package.json
```json
"watch": "tsc -watch -p ./"
```
- Have the following launch configuration with preLaunchTask to debug the extension
```json
{
    "name": "Launch Extension",
    "type": "extensionHost",
    "request": "launch",
    "runtimeExecutable": "${execPath}",
    "args": [
        "--extensionDevelopmentPath=${workspaceRoot}"
    ],
    "stopOnEntry": false,
    "sourceMaps": true,
    "outFiles": [
        "${workspaceRoot}/out/src/**/*.js"
    ],
    "preLaunchTask": "npm: watch"
}
```
- Start Debugging "Launch Extension"
🐛 It gets stuck in preLaunchTask

It resumes only when I kill the terminal. See the attached video

![kapture 2018-08-28 at 11 11 15](https://user-images.githubusercontent.com/10746682/44713332-33385d80-aab3-11e8-9be4-7b5856a411ec.gif)

**Comment by weinand** [comment] 2018-08-28 09:36
Sandeep's generated launch.json looks old, so the hello world extension was not created with a recent version of the yeoman generated.
However, it should still work fine.
Pressing F5 compiles and launches the extension, but fails down the road because of the JSON language server issue:
![2018-08-28_11-36-25](https://user-images.githubusercontent.com/1898161/44714862-a8596200-aab6-11e8-880d-078d20610eb4.png)

**Comment by sandy081** [comment] 2018-08-28 10:08
@isidorn 

@weinand is correct. It is a test extension which I had it for testing from past.

**Comment by isidorn** [comment] 2018-08-28 10:10
@sandy081 then the issue is that you are using some old task framework which does not emit events so I never start it seems. Also assigning to @dbaeumer 
@sandy081 can you repro with using a new extension?

**Comment by sandy081** [comment] 2018-08-28 11:27
No issues with new extension.

**Comment by weinand** [comment] 2018-08-28 12:06
@isidorn did you already remove support for old-style tasks?
@dbaeumer is it expected that old style tasks are no longer supported and make EH debugging fail?

**Comment by dbaeumer** [comment] 2018-08-28 12:34
No, the output runner emits these events as well. @sandy081 how does the tasks.json look like?

**Comment by isidorn** [comment] 2018-08-28 12:43
@weinand I did not remove any support. I am simply listening on `taskService` events.
More details [here](https://github.com/Microsoft/vscode/blob/02fa928b20080bf69f12f320b1f31522812a6df5/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L850)

**Comment by isidorn** [comment] 2018-08-28 12:52
@dbaeumer I see in the release channel that you broke preLaucnTasks, so could you @sandy081 try to repro this once you get the insiders update in 15 minutes?

**Comment by sandy081** [comment] 2018-08-28 13:33
@dbaeumer There is no `tasks.json` file in the workspace. Is it required if I have `prelaunchTasks`?

**Comment by dbaeumer** [comment] 2018-08-28 13:39
No, and the problem got fixed. I broke something this morning with tasks. Latest insider has a fix for it. I think we can close this issue.

**Comment by isidorn** [comment] 2018-08-28 13:47
Ok, closing. @sandy081 please reopen if you still see it with latest insiders. Thanks

**Comment by sandy081** [comment] 2018-08-29 09:56
@isidorn I still see this issue

**Comment by isidorn** [comment] 2018-08-29 09:57
@sandy081 I am not sure how old of an extension you have. Would you be so kind to create a repository on github with it, so I try to repro with exactly that extension (or mail it to me)

**Comment by sandy081** [comment] 2018-08-29 10:31
@isidorn I can reproduce also with new hello world extension that is generated with yo code. 

- Delete tasks.json file
- Kill all open terminals in Terminal view
- Start debugging and then it stuck eventually

Let me know if you are able to reproduce it

**Comment by isidorn** [comment] 2018-08-29 10:46
@sandy081 thanks a lot for these great steps. The issue is deleting `tasks.json` - now the task service does not know this is a background task.
However we have a fallback for this situation, so the actuall issue is that the fallback is not triggered.

@dbaeumer please note that I say that a task is started if I get an active event [here](https://github.com/Microsoft/vscode/blob/828d2179178549c744ea3d7f78e5086252713cf5/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L883) and also if the task promise has completed [here](https://github.com/Microsoft/vscode/blob/828d2179178549c744ea3d7f78e5086252713cf5/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L895)

I believe we have written this code together, why is the first event needed, because it seems like in this case I shuold [throw an error](https://github.com/Microsoft/vscode/blob/828d2179178549c744ea3d7f78e5086252713cf5/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L900) and since I recieved the first event I think all is good which is wrong.
So either reciving the active event is the same as the promise comlpeting (in which case I should just successfuly return). Or I should simply ignore the active event

**Comment by dbaeumer** [comment] 2018-08-29 13:15
OK. Here is what is happening. The task is actually started successful even if the tasks.json is delete. Reason is that it is a npm script and the npm script extension contributes the task programmatically. However the task system doesn't know that the task is a background task and not matcher is associated (this information got added in the tasks.json file). Hence the promise doesn't complete nor reject (since that task runs forever, it is tsc in watch mode) nor will an inactive event fire.

@isidorn I thought you added a time out that ask the user to start debugging if the task doesn't complete in n seconds. I see nothing the task framework can do better here.

**Comment by isidorn** [comment] 2018-08-29 13:47
@dbaeumer I did add it. But the issue here is that the task.Active event comes but the promise never finishes.
I have created a PR that fixes this issue https://github.com/Microsoft/vscode/pull/57512
@dbaeumer can you please review if this is the right thing to do. Thank you.

**Closed** 2018-09-21 13:12 UTC
Labels: bug, debug, verification-found

**Comment by isidorn** [comment] 2018-09-21 13:13
@sandy081 now you should get a prompt after some time asking if you would like to continue

**Comment by sandy081** [comment] 2018-09-27 12:58
Verified that now I see the prompt but the prompt keeps coming even when I configured the task - https://github.com/Microsoft/vscode/issues/59550
