### ISSUE TITLE
Unable to find VsCode

### ISSUE THREAD

**Issue by DD-2703** [microsoft/vscode#138939] opened 2021-12-12 13:37 UTC
- VS Code Version: November 2021
- OS Version: Windows 10

Steps to Reproduce:
1. I opened Vscode, used it for some time and then closed it.
2. I was about to shutdown my computer when a Vscode popup appeared saying:

> `Updating Visual Studio Code`

3. I had already clicked on the shutdown button by the time the popup appeared.
4. But when I turned on my computer the next time, the shortcut I had for Vscode on my Taskbar was not working! It said:

> The item 'Code.exe' that this shortcut refers to is either changed or moved, so this shortcut will no longer work properly.

Even when I checked my AppData folder, I couldn't find it anywhere. The environment variables that were set during the installation also weren't working.

**UPDATE**: I had to re-install Vscode and somehow everything(from the directory that was last open, to all the installed extensions) were recovered!

**Comment by Tamtam00** [comment] 2021-12-12 14:09
Need vs code for dyncing

**Comment by yume-chan** [comment] 2021-12-13 08:15
Duplicate of #52855

**Closed** 2021-12-14 21:23 UTC
Labels: *duplicate
