### ISSUE TITLE
Explorer left; Outline right

### ISSUE THREAD

**Issue by gossi** [Microsoft/vscode#53701] opened 2018-07-06 11:46 UTC
Yay, the outline is here! As a dev I must choose do I have the explorer OR the outline opened, but not both at the same time. Something which I find extremely helpful when working with big IDEs (such as eclipse).

I wish, something similarly to the editor grid layout, to have multiple/custom panes in vscode, which I can move around and where I can decide what I'd like to see in these panes. E.g. I'd have the explorer on the left and the outline to the right, in between the editor.

Thanks

**Comment by jrieken** [comment] 2018-07-06 11:59
/duplicate of https://github.com/Microsoft/vscode/issues/49923

**Closed** 2018-07-06 12:00 UTC
Labels: *duplicate
