### ISSUE TITLE
typescript: 'move to new file' removes blank lines

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#90709] opened 2020-02-14 17:46 UTC
Issue Type: <b>Bug</b>

when moving a typescript function to a new file, it removes all the blank lines. please don't.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (8.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
vscode-nginx|sha|0.6.0

</details>

**Comment by mjbvz** [comment] 2020-02-14 19:56
Duplicate of https://github.com/microsoft/TypeScript/issues/27294

**Closed by mjbvz** 2020-02-14 19:56 UTC
