### ISSUE TITLE
Editor keeps changing my import paths without me knowing

### ISSUE THREAD

**Issue by AlastairTaft** [Microsoft/vscode#54706] opened 2018-07-20 04:04 UTC
Issue Type: <b>Bug</b>

The editor keeps changing this line 
```
import config from 'config'
```
to this line
```
import config from '../../../../../Library/Caches/typescript/2.9/node_modules/@types/config'
```

without warning me or giving me any undo history.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.2
cucumberautocomplete|ale|2.11.0
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.8.0

</details>

**Comment by Jayphen** [comment] 2018-07-20 08:47
At the moment I believe the only way to fix this (short of downgrading VSCode) is to force VSCode to use a newer version of Typescript.

https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

**Comment by mjbvz** [comment] 2018-07-20 18:32
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-20 18:32 UTC
Labels: typescript
