### ISSUE TITLE
Closing Markdown preview closes all other editors.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#44633] opened 2018-02-27 19:06 UTC
- VSCode Version: 1.21.0 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Markdown file and create the preview either in the same editor group or to the side
2. Close the Markdown preview

All open editors are closed.
The following error is displayed in the DevTools console:
ERR Cannot read property 'input' of null: TypeError: Cannot read property 'input' of null
    at e.onEditorsChanged (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3330:597)
    at t.e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:238)
    at t.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:191:46)
    at t.doCloseGroup (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4314:200)
    at t.doCloseActiveEditor (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4313:765)
    at t.doCloseAllEditorsInGroup (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4316:366)
    at t.doCloseEditors (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4317:287)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4315:820
    at Array.forEach (native)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4315:570

Found during testing #44463

**Comment by gregvanl** [comment] 2018-02-27 19:08
This is turning out to be a little hard to reproduce.

**Comment by mjbvz** [comment] 2018-02-27 19:12
Thanks! Duplicate of #44547. Should be fixed in the next build

**Closed by mjbvz** 2018-02-27 19:12 UTC
Labels: insiders
