### ISSUE TITLE
GIT decorations missing

### ISSUE THREAD

**Issue by sebastianarena** [microsoft/vscode#98241] opened 2020-05-20 12:52 UTC
Issue Type: <b>Bug</b>

I have been having a lot of troubles with a project that doesn't apply the git color decorations. Basically any other project that I have would show colors when adding files, or editing files. Even more important to me, graying out files that are included in .gitignore. I first noticed the issue of the Explorer not graying out and struggled thinking I had a bad .gitignore. Tried everything. But the .gitignore is fine, the files were not previously added to the repo, etc.

I tried removing the folder, and re-cloning the repository. That worked at first, and after rebooting VSCode it no longer works. It's the only project that I have this problem with. In case it may help, the repository is the following (open source): https://github.com/futurorandomico/aprendiendo-js

I'm here to try anything to get this problem fixed
Thanks

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.3.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
nasc-touchbar|fel|1.12.0
rust|rus|0.7.8
markdown-preview-enhanced|shd|0.5.4
sort-lines|Tyr|1.9.0

</details>

**Comment by sebastianarena** [comment] 2020-05-20 13:09
Just to answer the bot :) I do not have any other branches... it's just a single master branch. I'm attaching a preview of the Explorer to show the node_modules is not grayed out.

<img width="335" alt="Screen Shot 2020-05-20 at 10 09 00" src="https://user-images.githubusercontent.com/640406/82449713-08115100-9a82-11ea-827d-d4debd078e65.png">

**Comment by sebastianarena** [comment] 2020-05-20 20:24
Well, I fixed the problem by myself.
Though it should be noted that the bug still exists
The repository above was cloned inside this parent folder `~/Futuro randómico/`
It seems either the space or the accent breaks this feature completely
I moved the folder to another location, and everything is working fine now

**Comment by isidorn** [comment] 2020-05-26 08:49
Seems like git decorations get broken for repositories with accets / whitespaces.
Forwarding to @joaomoreno @jrieken

**Comment by mhanuszh** [comment] 2020-06-14 14:27
Also doesn't work with Symbolic links on Windows

I have
- Microsoft Windows [Version 10.0.18363.900]
- git version 2.27.0.windows.1
- vscode 1.46.0 a5d1cc28bb5da32ec67e86cc50f84c67cc690321 x64 with ```--disable-extensions```
- "git.decorations.enabled": true

I tried these paths:
```/d/gitDecorBug/original/mnb``` - **Works**

```/d/gitDecorBug/original with spaces/mnb``` - **Works**

```/d/gitDecorBug/original_with_funky_chars_öőóüűúáé_´_'_`_/mnb``` - **Works**

```/d/gitDecorBug/original with spaces and funky chars öőóüűúáé ´ ' `/mnb``` - **Works**

```/d/gitDecorBug/symlink/mnb``` - **Doesn't work**

**Comment by joaomoreno** [comment] 2020-06-17 07:45
Yes we've seen other users complaining about the same on macOS, but I could never reproduce.

@isidorn Can you please try to reproduce this in macOS? Just put the repo on a folder with accented characters.

**Comment by isidorn** [comment] 2020-06-17 07:54
Works for me

![Screenshot 2020-06-17 at 09 53 50](https://user-images.githubusercontent.com/1926584/84871161-785ec280-b080-11ea-956e-9629bab2b70a.png)

**Comment by airtonix** [comment] 2020-06-21 03:24
same.

```
Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```
![image](https://user-images.githubusercontent.com/61225/85215962-4d48db80-b3be-11ea-94bf-9f473ab9fc7c.png)

**Comment by joaomoreno** [comment] 2020-06-21 15:24
Moving to https://github.com/microsoft/vscode/issues/100524

**Closed by joaomoreno** 2020-06-21 15:24 UTC
Labels: needs more info
