### ISSUE TITLE
Trusted Domains is ignored for Trusted Workspaces

### ISSUE THREAD

**Issue by a1291762** [microsoft/vscode#127282] opened 2021-06-28 02:08 UTC
Does this issue occur when all extensions are disabled?: No (presumably yes, but my issue stems from the git blame extension opening a URL)

- VS Code Version: 1.57.1
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Trust a folder.
2. Do an action that opens a link (in my case, the waderyan.gitblame extension was used).

I filed this against the extension originally. Please see https://github.com/Sertion/vscode-gitblame/issues/106 for some more comments and screenshots. But the issue isn't the extension, rather it's VSCode. The Trusted Workplace has apparently superseded the Trusted Domains config, which breaks my workflow.

Because I am WFH, I cannot have VSCode just open browser links because my work windows are all in private sessions. Copying the URL (as I could previously do) to a private window works fine.

It looks like maybe I can whitelist ALL of my extensions, and then not trust the folder, in order to get the previous behaviour? But doing that removes any security that trusted folders was supposed to give, since now any old untrusted folder will have access to everything? That does not feel very logical.

**Comment by JacksonKearl** [comment] 2021-06-28 12:55
Duplicate of https://github.com/microsoft/vscode/issues/126108, in Insiders you can enable `workbench.trustedDomains.promptInTrustedWorkspace` , this will come out to Stable in the next release (about 2 weeks).

**Closed by JacksonKearl** 2021-06-28 12:55 UTC
Labels: workspace-trust
