### ISSUE TITLE
Word wrap settings ('on') are completely ignored

### ISSUE THREAD

**Issue by euk-anthonyb** [Microsoft/vscode#29578] opened 2017-06-27 11:37 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|fresh-material|2ndshift|2.2.1|
|Bookmarks|alefragnani|0.15.2|
|project-manager|alefragnani|0.18.1|
|htmltagwrap|bradgashler|0.0.3|
|gotemplate|casualjim|0.1.1|
|bracket-pair-colorizer|CoenraadS|0.10.7|
|mustache|dawhite|1.0.0|
|gitlens|eamodio|4.2.0|
|vscode-html-css|ecmel|0.1.7|
|json-tools|eriklynd|1.0.2|
|beautify|HookyQR|1.1.1|
|automagic-code|jairzjunior|0.0.2|
|theme-material-dark-soda|jbw91|1.2.0|
|theme-atomic-dark|kimkwanka|0.2.0|
|git-indicators|lamartire|1.2.1|
|vs-color-picker|lihui|0.6.0|
|start-git-bash|McCarter|1.2.1|
|code-beautifier|michelemelluso|1.7.2|
|prettify-json|mohsen1|0.0.3|
|vscode-scss|mrmlnc|0.6.2|
|atom-keybindings|ms-vscode|2.9.0|
|subtle-brackets|rafamel|2.0.0|
|vscode-icons|robertohuertasm|7.10.1|
|vscode-theme-superonedark|seansassenrath|0.0.15|
|code-settings-sync|Shan|2.8.1|
|vscode-todo-highlight|wayou|0.5.5|
|vscode-material-syntax-dark|woodywoodsta|0.1.1|
|Material-theme|zhuangtongfa|2.8.9|;

---

Steps to Reproduce:

1. Open an editor (i.e. js file)
2. Type code normally
3. Go to a website and copy HTML text
4. Return to editor and paste text
5. Pasted text ignores word wrap settings!

![image](https://user-images.githubusercontent.com/14346320/27585690-2e072888-5b35-11e7-860f-2cab691ec92f.png)

![image](https://user-images.githubusercontent.com/14346320/27585749-5a1ffe86-5b35-11e7-9176-c04f79624e54.png)

**Comment by euk-anthonyb** [comment] 2017-06-27 11:40
Toggling Word Wrap (Alt+Z) also has no effect. :(

**Comment by euk-anthonyb** [comment] 2017-06-28 09:08
Further to my last comment, It appears that the editor is ignoring any settings that configure wrapping to be on. It stays off regardless and I have to manually scroll left to right all the time so see my code. :(

**Comment by alexandrudima** [comment] 2017-06-29 08:40
Duplicate of #29752

When a Screen Reader is detected, it is impossible at this time for us to communicate to the Screen Reader the wrapping points of the editor. We therefore disable word wrapping when a Screen Reader is attached.

**Closed by alexandrudima** 2017-06-29 08:40 UTC

**Comment by euk-anthonyb** [comment] 2017-06-29 11:11
Thanks. This makes sense as my problems all seemed to stem from the screen reader detection.
