### ISSUE TITLE
'editor.action.showHover'-window doesn't disapear pressing ESC

### ISSUE THREAD

**Issue by slukits** [microsoft/vscode#237099] opened 2024-12-30 16:47 UTC
Type: <b>Bug</b>

(without any extensions active)

- bind 'editor.action.showHover' to a key
- go over a function call (for example) and press that key
- then when the info window has popped up press ESC

I would expect the info window to vanish as it did in the previous version.
But it doesn't.

I have the hunch that in the previous version the popping up info window also gets the focus and that this is not happening anymore.  Because if I press the "editor.action.showHover"-key an other time  the info window seems to get the focus and the ESC works.

VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Linux x64 6.11.11-1-MANJARO
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 x 3499)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.49GB (8.71GB free)|
|Process Argv|. --crash-reporter-id 530147e1-ac5a-4d1d-b6e0-d4f14e09761e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by gjsjohnmurray** [comment] 2024-12-30 17:00
/duplicate of #235979 that will be fixed in the next release.

pinging @aiday-mar

**Closed** 2024-12-30 17:01 UTC
Labels: *duplicate
