### ISSUE TITLE
Hide tabs

### ISSUE THREAD

**Issue by Waldemar-Dassler** [Microsoft/vscode#42887] opened 2018-02-03 15:35 UTC
Please add one more param `none` to:
```
"workbench.editor.showTabs": false,
```
For full hide tab bar. In all text editors its work but in VSCode line do not hide =(

**Comment by usernamehw** [comment] 2018-02-03 15:51
Duplicate of https://github.com/Microsoft/vscode/issues/33607

**Closed** 2018-02-03 17:32 UTC
Labels: *duplicate
