### ISSUE TITLE
Allow placement of caret after end of line - like IntelliJ IDEA

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#43616] opened 2018-02-13 20:28 UTC
Setting "Allow placement of caret after end of line" in IntelliJ IDEA allows one to move caret to any location by mouse-click or arrow keys.

![image](https://user-images.githubusercontent.com/611746/36171919-f2b21388-10c9-11e8-9ea9-e7e23f9927ef.png)

**Comment by flo2k** [comment] 2019-09-13 09:28
This feature would be very nice to have.

**Comment by usernamehw** [comment] 2019-09-27 20:05
Duplicate of #13960

**Closed** 2019-10-24 16:54 UTC
Labels: *duplicate, editor-core, feature-request
