### ISSUE TITLE
cannot fold namespaces in c++ files

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#18491] opened 2017-01-13 05:39 UTC
- VSCode Version: 1.8.1
- OS Version: Linux

Steps to Reproduce:

1. Write following code
```
#include <iostream>

namespace someName{
    void someMethod1(){
        int n = 6;
        return n;
    }

    void someMethod2(){
        int n = 6;
        return n;
    }
}

int main(){}
```

2. Try to fold code b/w namespace, no [+] icon is shown in gutter.

**Comment by aeschli** [comment] 2017-01-19 09:32
duplicate of #3422

**Closed by aeschli** 2017-01-19 09:32 UTC
Labels: editor-folding, languages basic
