### ISSUE TITLE
 Cannot read property 'getControl' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2893] opened 2016-02-10 15:14 UTC
Issue Id: <b>b633d420-1fcd-6703-2221-63797bcca19c</b><br /><br />*Versions* <br />- 0.10.7-insider<br />*Stack* <br />TypeError: Cannot read property 'getControl' of null<br />[/vs/workbench/api/node/mainThreadEditors.ts#L226:16 (MainThreadTextEditor.matches)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/workbench/api/node/mainThreadEditors.ts#L226:16 (MainThreadTextEditor.matches))<br />[/vs/workbench/api/node/extHostEditors.ts#L640:34 (MainThreadEditors._tryShowTextDocument)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/workbench/api/node/extHostEditors.ts#L640:34 (MainThreadEditors._tryShowTextDocument))<br />[/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />[/vs/workbench/api/node/extHostEditors.ts#L627:5 (MainThreadEditors._tryShowTextDocument.contd)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/workbench/api/node/extHostEditors.ts#L627:5 (MainThreadEditors._tryShowTextDocument.contd))<br />[/vs/workbench/api/node/extHostEditors.ts#L630:5 (MainThreadEditors._tryShowTextDocument)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/workbench/api/node/extHostEditors.ts#L630:5 (MainThreadEditors._tryShowTextDocument))<br />[/vs/base/common/callbackList.ts#L63:26 (CallbackList.invoke)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/base/common/callbackList.ts#L63:26 (CallbackList.invoke))<br />[/vs/base/common/event.ts#L107:26 (Emitter.fire)](https://github.com/microsoft/vscode/blob/6c2d51a4b7b81753a3a4c46f9de9a15179e20304/src/vs/base/common/event.ts#L107:26 (Emitter.fire))<br />

**Comment by alexandrudima** [comment] 2016-02-11 08:31
The problem is in `_tryShowTextDocument`

**Comment by jrieken** [comment] 2016-04-25 12:39
duplicate of #2239

**Closed by jrieken** 2016-04-25 12:39 UTC
Labels: error-telemetry
