### ISSUE TITLE
auto closing bracket and single as well as double quote is not working like atom text editor

### ISSUE THREAD

**Issue by saileshkush95** [Microsoft/vscode#51676] opened 2018-06-12 08:12 UTC
when there is no space  after the cursor auto closing bracket and single as well as double quote is not working. I found solution of this problem in atom text editor. Atom text editor help me to write code very smoothly as well as faster than vs code. 

i tried to solve this problem using key binding features it helps me little bit but not for what I am searching....

Vs code is faster than atom but it not working like atom so please 

If there is any solution related to this problem let me know and I requested you to please fix this bug as soon as possible 

Thank You.....

**Comment by RMacfarlane** [comment] 2018-06-12 19:16
@saileshkush95 Thank you for reporting! Autoclosing should be working like this:
![autoclosing](https://user-images.githubusercontent.com/3672607/41311748-0e618fc8-6e3a-11e8-8a70-370c36b80f19.gif)


Can you please give us some more details to help investigate?
- VSCode version
- OS
- What types of files does this happen for?
- Exact steps to reproduce

**Comment by saileshkush95** [comment] 2018-06-16 13:46
Yeah! its working fine when there is space available after cursor
But not working when there is no any  space available after cursor.
like between single quote or double quote auto close bracket features are not working and vice versa.

**Comment by RMacfarlane** [comment] 2018-06-17 17:28
Duplicate of  https://github.com/Microsoft/vscode/issues/41891, please see https://github.com/Microsoft/vscode/issues/41891#issuecomment-359464727

**Closed by RMacfarlane** 2018-06-17 17:28 UTC
Labels: editor, editor-autoclosing, needs more info
