### ISSUE TITLE
VS Code uninstalled itself??

### ISSUE THREAD

**Issue by SebasSBM** [microsoft/vscode#96748] opened 2020-05-01 01:30 UTC
- VSCode Version: Unknown (either 1.36.0 or 1.36.1)
- OS Version: W10 Home 

Steps to Reproduce:
I have absolutely no idea...
some Windows Update triggered and VS Code is no more in the system...

Does this issue occur when all extensions are disabled?: I don't know…

MORE INFO
--------------
I found a similar closed issue from 1 year ago: #68688

**Comment by yume-chan** [comment] 2020-05-02 14:37
You linked to #68688 but that one had been marked as a duplicate of #52855.

Basically, Code wants to upgrade itself, so it first deleted itself, but some how failed to install the new version., leaving no Code in your computer.

You have a pretty old version, do you keep the auto update on?

**Comment by joaomoreno** [comment] 2020-05-04 10:00
☝️

**Closed** 2020-05-11 11:22 UTC
Labels: needs more info
