### ISSUE TITLE
Dealing with extension dependencies in Restricted Model

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#125337] opened 2021-06-02 20:47 UTC
I got the following notification. This only looks at the enablement state of the upstream dependency but does not consider that this is happening because of restricted mode. I.e. the proposal of enabling is wrong.

![image](https://user-images.githubusercontent.com/4674940/120385637-8717a700-c2dc-11eb-8947-d7b2ca5cc089.png)

**Comment by lszomoru** [comment] 2021-06-03 05:30
@sandy081, was looking into this though I am not sure that there is an easy fix right now.

**Comment by sandy081** [comment] 2021-06-03 17:17
/duplicate

Duplicate of https://github.com/microsoft/vscode/issues/122448

For current milestone I fixed the prompt - https://github.com/microsoft/vscode/issues/125395. The actual fix will be done via #122448

**Closed** 2021-06-03 17:18 UTC
Labels: *duplicate, bug, workspace-trust
