### ISSUE TITLE
Alt command tooltips don't appear on tree item "inline" commands

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#62064] opened 2018-10-29 16:14 UTC
Issue Type: <b>Bug</b>

Originally reported here: https://github.com/Microsoft/vscode/issues/61970#issuecomment-433779072

When specifying an `alt` command for a tree item's "inline" group, holding down `alt` does switch to the alternate command icon, but the alt command's tooltip fails to ever appear.

For example:
```json
{
    "command": "gitlens.copyShaToClipboard",
    "when": "viewItem =~ /gitlens:(file:)?commit\\b/",
    "group": "inline@98",
    "alt": "gitlens.copyMessageToClipboard"
},
```

VS Code version: Code - Insiders 1.29.0-insider (4a29bd3731e40c07622bae0e9b0ac3b422b5672a, 2018-10-25T05:48:41.485Z)
OS version: Windows_NT x64 10.0.18267

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (17.09GB free)|
|Process Argv|c:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment] 2018-10-29 18:41
@eamodio Is this true only in custom view or also in other locations like when you contribute actions to editor title?

**Comment by eamodio** [comment] 2018-10-29 20:43
@sandy081 you are right -- it happens all the time. Though I swear that worked prior to 1.28.

**Comment by sandy081** [comment] 2018-10-30 09:09
@bpasero May I know who is responsible to fix this?

**Comment by bpasero** [comment] 2018-10-30 09:28
@sandy081 seems to work in the editor, not sure. @jrieken ?

**Comment by jrieken** [comment] 2018-10-30 09:38
depends on how it is implemented. the `MenuItemActionItem` does at least call [`updateTooltip`](https://github.com/Microsoft/vscode/blob/d150c48f7b8ae77f84936130da8fd48760f014d4/src/vs/platform/actions/browser/menuItemActionItem.ts#L171-L172). that is being used in the editor in which it seems to work...

**Comment by sandy081** [comment] 2018-10-30 10:35
I am also using `MenuItemActionItem` in custom views. 

https://github.com/Microsoft/vscode/blob/48282551ec2762209c69713d819ffae11b3b7862/src/vs/workbench/browser/parts/views/customView.ts#L357

Will investigate who is consuming the `alt` key.

**Comment by jrieken** [comment] 2018-10-31 08:01
This might be a browser thing. We use the `title` attribute and I think that doesn't update when changing while it is visible...

**Comment by sandy081** [comment] 2018-10-31 15:42
@eamodio Looks like it works for me

![kapture 2018-10-31 at 16 41 04](https://user-images.githubusercontent.com/10746682/47800053-d0ba4280-dd2b-11e8-97ed-933981ddfe78.gif)

**Comment by eamodio** [comment] 2018-10-31 16:14
@sandy081 hrm, its probably a Windows only issue then 😢

**Comment by eamodio** [comment] 2018-10-31 18:53
@sandy081 it seems that holding down the `alt` key regardless if there is and `alt` command causes all tooltips to not show up.

**Comment by eamodio** [comment] 2019-07-11 16:29
I've tried setting `window.customMenuBarAltFocus` to `false` and while it makes the command behave better (the alt doesn't seem to stick anymore), it still stops any tooltips from showing.

**Comment by sandy081** [comment] 2019-07-12 13:56
I do not think this is an issue at custom view level.

@bpasero any insights?

**Comment by eamodio** [comment] 2019-07-12 14:24
@sandy081 you are correct - it isn't custom view specific

**Comment by bpasero** [comment] 2019-07-13 06:11
> seems that holding down the alt key regardless if there is and alt command causes all tooltips to not show up.

I am not sure why that would happen. If it reproduces in Chrome it is probably an upstream thing.

**Comment by bpasero** [comment] 2019-10-09 05:09
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Closed by bpasero** 2019-10-09 05:09 UTC
Labels: electron, upstream
