### ISSUE TITLE
Support to manually sort snippets by extension id

### ISSUE THREAD

**Issue by natqe** [microsoft/vscode#66319] opened 2019-01-10 07:42 UTC
When i created this request it was a suggest to look in [Control over snippets](https://github.com/Microsoft/vscode/issues/9286)
and i see it, and its good, but not enough.
i think better to give to the user option to order the snippets by where is come from.
for example:
suggestionsOrder: [
"name-of-very-cool-extension-that-i-was-install",
"extension-with-snippets-that-i-less-need",
"ext"
]
i be glad if it's happened, because it is give to the user a complete control in compare what we have right now, that is good but not enough.

"google complete me" for example, is very good extension, but i cannot install it because is taking all the space, and i want it in the bottom, but i can't do it without move all snippets suggestions to the bottom, so i prefer to skip the benefits of this extension, and its very sad.

**Comment by natqe** [comment] 2019-01-10 08:45
@jrieken option to sort the snippets by where they come from.
right now, i not have the control to give to specific vscode extension high level from other extension, and is requested by nature.

**Comment by jrieken** [comment] 2019-10-07 11:01
/duplicate of https://github.com/microsoft/vscode/issues/74213

**Closed** 2019-10-07 11:01 UTC
Labels: *duplicate, feature-request, snippets
