### ISSUE TITLE
Two notifications when renaming an element that I can't rename

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34666] opened 2017-09-19 23:48 UTC
- Have a variable that isn't defined
- F2 to rename it
- See a warning and an error. I think I just expect the warning

![image](https://user-images.githubusercontent.com/323878/30620442-3e0321f8-9d5a-11e7-859e-f56cbc8932e7.png)

**Comment by mjbvz** [comment] 2017-09-20 16:15
I believe this was introduced by dbe0f89264dc6e9d38cf8723e358741ce9e8a131

Not TS specific. The bug is that `_prepareRename` will always return an error. We show a warning for this error and then rethrow it which triggers the error message in the UI

**Comment by mjbvz** [comment] 2017-09-30 16:21
Duplicate of #35177. I believe Ramya fixed this already

**Closed by mjbvz** 2017-09-30 16:21 UTC
Labels: bug, duplicate, editor, typescript
