### ISSUE TITLE
Standalone editor: strange code assist behaviour

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#8320] opened 2016-06-28 11:16 UTC
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10.

Code complete triggered after c. Observe no proposals.
![capture](https://cloud.githubusercontent.com/assets/1931590/16413479/7979042a-3d32-11e6-9821-a86162d9d3c6.png)

Code complete triggered after co. Observer there are proposals.
![capture](https://cloud.githubusercontent.com/assets/1931590/16413494/91d247d4-3d32-11e6-822f-0aea98a8a084.png)

**Comment by dbaeumer** [comment] 2016-06-28 11:38
Same seems to happened with less and scss

**Comment by aeschli** [comment] 2016-06-29 14:08
Duplicate of #8325

**Closed by aeschli** 2016-06-29 14:08 UTC
Labels: monaco-editor
