### ISSUE TITLE
Source Control

### ISSUE THREAD

**Issue by rodrigoayalau** [microsoft/vscode#84641] opened 2019-11-13 00:47 UTC
Issue Type: <b>Bug</b>

I have installed Visual Studio Code (updated until Nov, 11 2019) and the issue is that source control does not recognize changes in my code, it shows the count notification but when I click on it the source control is in blank.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
Angular-BeastCode|Mik|8.0.10
python|ms-|2019.10.44104
csharp|ms-|1.21.7
vscode-typescript-tslint-plugin|ms-|1.2.3
java|red|0.52.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1

</details>

**Comment by joaomoreno** [comment] 2019-11-14 07:17
Can you reproduce this in the [insider release](https://code.visualstudio.com/insiders)?

**Comment by misolori** [comment] 2019-11-14 07:24
I can repro: 

![gif](https://user-images.githubusercontent.com/35271042/68835320-9c7e9f00-066c-11ea-8c3a-f384a48680d1.gif)

This is likely due to the fact that we use icon fonts now and the ellipsis is applied to the icon and the animation class is applied to the icon font, so the text container animates 🙃.

**Comment by joaomoreno** [comment] 2019-11-14 07:47
Ahaha that's awesome.

**Comment by joaomoreno** [comment] 2019-11-14 07:47
Why does the sync transform into an ellipsis? If it does shouldn't it become a drop down menu instead?

**Comment by misolori** [comment] 2019-11-14 17:32
It's part of the css overflow text, for when you have pending changes and the sidebar is small:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/35271042/68881237-9ebf1880-06c1-11ea-83c2-9e74bcbfa632.png">

<img width="206" alt="image" src="https://user-images.githubusercontent.com/35271042/68881249-a4b4f980-06c1-11ea-9651-06fffab2161e.png">

**Comment by joaomoreno** [comment] 2019-11-15 19:25
Always learning with CSS.

**Comment by joaomoreno** [comment] 2019-11-18 16:25
@misolori I don't understand the spinning issue relates to what the user says... Closing this issue and moving to https://github.com/microsoft/vscode/issues/84632

**Closed by joaomoreno** 2019-11-18 16:25 UTC
Labels: bug, icons-product, scm

**Comment by misolori** [comment] 2019-11-18 16:38
@joaomoreno sorry, responded to the wrong issue 🙈
