### ISSUE TITLE
Scroll bar should stick to the bottom when it is scrolled up

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#177791] opened 2023-03-21 11:15 UTC
Testing #177719

Using the "streaming output" example the scrollbar keeps jumping to the bottom also when I scroll by dragging the scrollbar or using the mouse wheel.

**Comment by rebornix** [comment] 2023-03-21 18:39
/duplicate of https://github.com/microsoft/vscode/issues/177721

**Closed by rebornix** 2023-03-21 18:39 UTC
