### ISSUE TITLE
Theme Dark+ (default dark) syntax highlight error

### ISSUE THREAD

**Issue by fegg** [Microsoft/vscode#17792] opened 2016-12-24 10:29 UTC
- VSCode Version: 1.8.1
- OS Version: MacOS 10.12.2

hi, this error screenshot: [Show Image](http://p1.bpimg.com/567571/7d689c3a434f5c73.jpg)

**Comment by egamma** [comment] 2016-12-24 16:20
@fegg thanks for the issue, the screenshot shows a code snippet, please also include the code snippet in the issue report so that we do not have to type it in to reproduce the issue. Please see also our [issue reporting guidelines](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-great-issues-and-suggestions).

**Comment by fegg** [comment] 2016-12-26 06:38
ok.

```javascript

function _setDefaultRowWidth(){
    let width = (Math.floor(100000/defaultRows.length)/1000)+'%';
    _.forEach(defaultRows, (name)=>{
        widthInfo[name] = width;
    });
}

```

error code: 

```javascript

let width = (Math.floor(100000/defaultRows.length)/1000)+'%';

```

I think this bug is analysis between `/` and `/` not space, error analysis it is RegExp, so highlight not   good.

English is not very good, hope you can understand...

**Comment by egamma** [comment] 2016-12-26 09:35
@fegg thanks for providing the additional information.

I'm still not able to reproduce it. 

![image](https://cloud.githubusercontent.com/assets/172399/21479660/6d5b83ae-cb56-11e6-9847-affd34ccb00c.png)

You mention:

>Language is: JavaScript(Babel)

This is not a grammar we ship with VS Code and I assume you have an extension installed. 

Can you reproduce when you switch the language to `JavaScript` in the bottom right corner?

**Comment by mjbvz** [comment] 2016-12-29 00:53
Closing as I'm also not able to reproduce this issue.

@fegg Please try the steps the @egamma suggested to check if one of the extensions is causing this issue. Thanks.

**Closed by mjbvz** 2016-12-29 00:53 UTC
Labels: javascript, languages basic, needs more info
