### ISSUE TITLE
My extensions marketplace does not load 

### ISSUE THREAD

**Issue by glezin97** [microsoft/vscode#115712] opened 2021-02-03 20:12 UTC
I downloaded the Visual Studio Code about a week ago and had issues with the program from the start. My Python editor would not recognise the simplest function to sum two parameters. The issue in the output window informed me that I cannot edit from the read only editor. I tried tried to move the application from downloads folder to applications folder. Later on, I discovered that functions run if I "run and debug" them first. However, now I cannot connect to the extensions marketplace and no links on the welcome page work. I tried to delete and reinstall the programm several time, but it does not help. I am working of MacBook Pro that runs on BigSur software. I am hoping you can tell me what to do to make VSCode work. Thank you for your time.

**Comment by mjbvz** [comment] 2021-02-04 02:19
Duplicate of #115713

**Closed by mjbvz** 2021-02-04 02:19 UTC
