### ISSUE TITLE
peek showing 2 definitions on functions with one assignment

### ISSUE THREAD

**Issue by tyrsius** [Microsoft/vscode#51918] opened 2018-06-14 17:34 UTC
- VSCode Version: Version 1.24.0 (1.24.0)
- OS Version:  10.12.6 (16G1314)

Steps to Reproduce:

1. Create a JS function declared as `const func = () => {}` or `const obj = { func: () => {}}`
2. Create call site for that function
3. Go to Definition

Does this issue occur when all extensions are disabled?: Yes

-----------------

Since the latest update when I go to definition the editor goes to the correct location but _also_ opens PEEK on top of the definition. It happens consistently with arrow functions assigned to vars or object keys. It doesn't seem to be happening with function declarations.

This has never happened before, and its happening consistently since the last update, which leads me to believe it isn't an issue with the language provider.

![image](https://user-images.githubusercontent.com/1187432/41428290-6f6ebc3e-6fbe-11e8-9c22-9cffd18116a0.png)

You can see here that VS code has found 2 definitions, even though they are for the same line and assignment. Peek is showing the function _on top of the function in the editor_

**Comment by tyrsius** [comment] 2018-06-14 17:36
This is not a duplicate of the provided issues

**Comment by mjbvz** [comment] 2018-06-14 17:38
Duplicate of https://github.com/Microsoft/TypeScript/issues/24861

**Closed by mjbvz** 2018-06-14 17:38 UTC
Labels: javascript

**Comment by tyrsius** [comment] 2018-06-14 17:50
@mjbvz This is not happening in typescript files, its happening in js files. Is there some way I can stop TS bugs from affecting my JS code?

**Comment by mjbvz** [comment] 2018-06-14 17:56
Typescript powers both JS and TS intellisense. This is the correct duplicate bug. You can workaround it by manually upgrading your workspace to typescript@next by following [these instructions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions)

**Comment by tyrsius** [comment] 2018-06-14 19:33
Good to know, thank you for the fix instructions
