### ISSUE TITLE
Settings UI: Can't configure `Default Dark+` in the workspace settings if theme is already set in user

### ISSUE THREAD

**Issue by DiegoBM** [microsoft/vscode#84943] opened 2019-11-15 20:47 UTC
Issue Type: <b>Bug</b>

1. Go to User Settings and set a color theme different than the default one, for example "Kimbie Dark"
2. Go to Workspace Settings and set "Default Dark+"
* Expected Result: Use the "Default Dark+" color theme for the current workspace/folder/project
* Current Result: Uses the "Kimbie Dark" color theme for the current workspace/folder/project.

If you make Workspace Settings' color theme point to any color theme other than "Default Dark+", it will work just fine. It seems like the "Default Dark+" color theme is not a color theme itself (even though it seems to have its own and unique syntax and interface styles) but a pointer to "default", and "default" is whatever value that is selected in User Settings.

We should be to be able to use the "Default Dark+" color theme for certain projects, regardless of the color theme selected globally in User Settings

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.1
remote-wsl|ms-|0.40.3
cpptools|ms-|0.26.1
material-icon-theme|PKi|3.9.1

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2019-11-18 08:07
It's a bug in the settings UI. I says Default Dark+ is the default, which is not correct when the user settings have a different theme set. So clearing the setting doesn't result in having the `Default Dark+` theme.

**Comment by roblourens** [comment] 2019-11-19 02:47
Dupe of https://github.com/microsoft/vscode/issues/58038

**Closed by roblourens** 2019-11-19 02:47 UTC
