### ISSUE TITLE
File is Missing From Menu On Insiders

### ISSUE THREAD

**Issue by largeDachshund** [Microsoft/vscode#55714] opened 2018-08-02 23:26 UTC
- VSCode Version: Can't tell because that Menu is missing 
![image](https://user-images.githubusercontent.com/7054672/43616295-aebc8596-9670-11e8-935b-5b19d7f7e2dd.png)

- OS Version: Windows 10

I took the latest update and a couple of Menu items are missing.
File and Help? are missing.

![image](https://user-images.githubusercontent.com/7054672/43616277-8fcb10c6-9670-11e8-8d3e-b5c1ee8b0b18.png)

Steps to Reproduce:

1.  Take Latest Insiders Update
2.  Shut Down VS Code
3. Re-Open VS Code

**Comment by sean-mcmanus** [comment] 2018-08-03 01:00
Yikes. The workaround I'm using is file commands: 


![image](https://user-images.githubusercontent.com/19859882/43618559-de799f50-967d-11e8-9f87-51b02ee5d1d7.png)

**Comment by xieaoran** [comment] 2018-08-03 01:06
Same Problem, really causing inconvenience.

**Comment by rohitkrishna12** [comment] 2018-08-03 01:10
Same problem.

**Comment by mjbvz** [comment] 2018-08-03 09:24
Duplicate of #55624

**Closed** 2018-08-03 09:24 UTC
