### ISSUE TITLE
Cursor does not align to indent when clicking empty line

### ISSUE THREAD

**Issue by nicolasjinchereau** [Microsoft/vscode#9241] opened 2016-07-13 22:18 UTC
- VSCode Version:1.3.1
- OS Version: OSX

Example:

```
void foo()
{
    bar();
    | <-- cursor should be here on click.
|<-- Not here.
}
```

Clicking under 'bar()' should align cursor to the beginning of the word 'bar', not to the left of the document, regardless of whether there are actually tab characters there or not. Also, hitting 'enter' with the cursor to the right of bar() should insert a new empty line under bar(). Only when something is actually typed, should tabs be inserted.

**Comment by alexandrudima** [comment] 2016-07-14 13:46
At this point, by design, cursors are not allowed to float where there is nothing, they are clamped to the buffer shape.

**Comment by bitwise-github** [comment] 2016-07-14 16:43
@alexandrudima Does this mean you don't intend to implement this? Because every other editor works as I've described. To be honest, this is such an annoyance that I've switched back to XS for now.

**Comment by bitwise-github** [comment] 2016-07-14 17:34
Creating new files in VSCode is fine, because indents will be added to new lines as you write. But, a much more important use case is people migrating from editors like Xamarin Studio, which do not insert tabs on empty lines. Now, literally every single time I want to add a line to my code, I have tab over to indent before I start writing because VSCode is missing this feature.

**Comment by alexandrudima** [comment] 2016-07-15 08:37
I've only described what the current state is. It does not mean the current state cannot be changed.

**Comment by bitwise-github** [comment] 2016-07-15 19:19
Ok thanks. I would really appreciate if this was fixed soon.

Currently, the 'Esc' key has completely stopped working in Xamarin Studio(OS X), meaning that pressing it will not dismiss intellisense popups, or the "Find" window, which is only slightly more tolerable than this indentation problem ;)

**Comment by JohnWeisz** [comment] 2017-03-03 18:50
As a user coming from Visual Studio, I would really like to see this made possible through a setting.

**Comment by alexandrudima** [comment] 2017-11-23 09:46
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Closed by alexandrudima** 2017-11-23 09:46 UTC
Labels: editor, editor-core, feature-request
