### ISSUE TITLE
Debug Console has lost highlighting in 

### ISSUE THREAD

**Issue by tomq42** [Microsoft/vscode#213] opened 2015-11-19 13:27 UTC
Don't know whether this is deliberate or not. In the previous version to 0.10 when I ran mocha tests, the output had highlighting, red, green etc.
In 0.10, this appears to have been lost.

**Comment by isidorn** [comment] 2015-11-19 13:30
@tomq42 can you please attach some pictures?

**Comment by tomq42** [comment] 2015-11-19 13:39
Not particularly easily. Partly because I now longer have the older version (its been upgraded obviously) and partly because I would have to set up a new project with dummy examples in to avoid posting pictures of confidential stuff. I don't know whether I have the skills to do that or not, I didn't set the project up originally.

Do you think there *should* be red and green highlighting in the debug console if I run Mocha tests?

**Comment by tomq42** [comment] 2015-11-19 13:46
Ah.
What's changed is that now it it runs the program in an internal console that DOESN'T have highlighting whereas previously it used an external console window.  The external console highlighted things red and green as presumably mocha generates ANSI control characters to configure the colours.

So you appear to have added "externalConsole" to the launch configuration, but the default appears to be false if the value isn't specified in the configuration, so it runs it in the Debug Console instead.
That's what's changed.

So the request is that the Debug Console honour the ANSI control chars, and that the default appears wrong, from an upgrade migration point of view.

**Comment by isidorn** [comment] 2015-11-19 13:54
Yeah, but our internal debug console supports basic ansi coloring

**Comment by weinand** [comment] 2015-11-19 14:00
@isidorn yes, our internal debug console supports basic ansi colours but it is not a real "tty". Some programs (IIRC mocha is one of them) check explicitly whether they are running in a "tty" and only then use colours.

**Comment by isidorn** [comment] 2015-11-19 14:06
Oh yes, Ben has overcome this issue by passing in some arguments to mocha.
@tomq42 please checkout https://github.com/Microsoft/vscode/blob/master/.vscode/launch.json our Unit Tests configuration where we pass --colors arguments to mocha.

Closing this as desgined for now. Feel free to reopen if you feel like something is missing still.

**Closed by isidorn** 2015-11-19 14:06 UTC
Labels: Needs More Info

**Comment by tomq42** [comment] 2015-11-19 14:17
The thing that confused me primarily was the change in behaviour of launching internally verses externally. Is that deliberate?

**Comment by tomq42** [comment] 2015-11-19 14:19
Passing --colours does indeed make it work.

What's a bit annoying though is that it keeps creating the Debug Console along side my editor. So unless the Debug Console is actually displaying, it will create a new one to the side of the editor, and there doesn't seem to be a way to configure that?

**Comment by isidorn** [comment] 2015-11-19 14:27
Yes the change was delibarte to launch in internal, you can easily change that behaviour.
Hmm if I set `externalConsole: true` the Debug Console does not get open on the side for me. Do you see different behavior? If yes, do you just get an empy Debug Console?

**Comment by tomq42** [comment] 2015-11-19 14:41
Sorry, maybe I didn't describe very well.
I have extrernalConsole:false, or unspecified, and when I then run, the Debug Console always gets created to the side. There seems to be no way to have it just bring to the front the already existing Debug Console that might exist. So if I Ctrl-Tab, Debug Console is in the list of open windows. Yet when I run, rather than just swapping to that, it brings it up to the side, which I find annoying.

**Comment by isidorn** [comment] 2015-11-19 14:44
We always have one instance of the debug console, and when you launch we will not open a new one but use the one already there.
What I think is the cause of confusion is that on each debug start we clear the contents of the console

**Comment by tomq42** [comment] 2015-11-19 14:46
But it doesn't reuse the one that's there, or at least if it does, it always moves it and splits the screen and puts the Debug Console on the right. *Thats* what I fine annoying. The splitting of the screen.

**Comment by isidorn** [comment] 2015-11-19 14:52
Ok, I will need an actual setup and reproducable steps
Where do you have the Debug console before starting the debug session? Invisible, or if visible in which of the 3 slots?
Where does it end up after the debug session start?

**Comment by tomq42** [comment] 2015-11-19 15:04
I just created a new folder, opened VSCode, clicked on the debug icon, then by the launch dropdown clicked on the great icon. It generated me a new launch.json. I then authored app.js with 
console.log(hello world). Click on the launch, it opens the DEbug Console to the right.

So then close the Debug Console so I only have my app.js showing. Shift tab though and the Debug Console is still in the list and I can cycle through to it. However if I run the app.js again, with the app.js showing, then the Debug Console pops up again on the right, rather than just dong the equivalent of Ctrl-tab and cycling through to the file.

I personally find this behaviour annoying, as neither the source window nor the debug console window are then wide enough to see all I need to see (I have a widescreen monitor).

**Comment by isidorn** [comment] 2015-11-19 16:02
Thank you for the detailed steps. However this is as designed for now.
In the future we plan to render the debug console horizontally which should fix your issue.

In the meantime if you dislike it I would suggest using `"externalConsole": true` option.

**Comment by sbusayarat** [comment] 2016-04-16 00:38
The internal console doesn't show color set by the popular `colors` package.    https://www.npmjs.com/package/colors    It works on the external console.

Is there a way to make this work?

**Comment by isidorn** [comment] 2016-04-16 09:03
@sbusayarat not right now, feel free to file a new feature request. In the meantime please use the external console as a workaround for this
