### ISSUE TITLE
Overtyping not working for css pseudo-classes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#78200] opened 2019-07-30 17:22 UTC
Testing https://github.com/microsoft/vscode/issues/78118

**Steps to reproduce**
1. Open a CSS file
2. Use any of the pseudo-class tags that have a parenthesis (ex: `nth`, `not`, `matches`)
3. Attempt to close the parenthesis
4. 🐛 Overtyping does not work

![Screen Recording 2019-07-30 at 10 11 29 AM 2019-07-30 10_16_47](https://user-images.githubusercontent.com/35271042/62150584-3f283300-b2b3-11e9-876e-365c35f4bbc5.gif)

VS Code version: Code - Insiders 1.37.0-insider (cf03ea3729dc37e439d724267ad29dc5840f903a, 2019-07-30T07:10:53.695Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.93GB free)|
|Process Argv|-psn_0_536707|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-profile-switcher|aar|0.3.3
chalice-icon-theme|art|0.2.1
vscode-opennewinstance|chr|0.0.6
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
es7-react-js-snippets|dsz|2.4.0
gitlens|eam|9.9.1
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|1.9.0
vscode-pull-request-github-insiders|Git|2019.7.36902
todo-tree|Gru|0.0.139
rest-client|hum|0.21.3
svg|joc|0.1.6
all-symbol-kinds|jri|0.0.1
vscode-colorize|kam|0.8.11
graphql-for-vscode|kum|1.15.0
git-graph|mhu|1.12.1
theme-monokai-pro-vscode|mon|1.1.13
vscode-scss|mrm|0.6.2
vscode-azureappservice|ms-|0.15.0
remote-containers|ms-|0.67.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.39.1
azure-account|ms-|0.8.4
cpptools|ms-|0.24.1
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.614
debugger-for-chrome|msj|4.11.6
vscode-gatsby-snippets|nic|1.1.2
material-icon-theme|PKi|3.8.1
vscode-graphql|Pri|0.2.1
try-material-icon-theme|raf|3.9.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.4.1
stylelint|shi|0.51.0
notification-tester|svi|2.1.2
ayu|tea|0.18.0
sort-lines|Tyr|1.8.0
markdown-all-in-one|yzh|2.4.2
vscode-open-in-github|ziy|1.3.6

(8 theme extensions excluded)

</details>

**Comment by sana-ajani** [comment] 2019-07-30 23:26
Overtyping works for me in this case. (on Windows machine)

**Comment by alexandrudima** [comment] 2019-07-31 14:51
@misolori I also cannot reproduce. I wonder if this reproduces when you disable all your extensions?

**Comment by misolori** [comment] 2019-07-31 15:14
This still repros after disabling all of my extensions and also tested this on Win10 with the same result.

Just to clarify what I'm seeing:

- Typing `.foo:not` then hitting enter on intellisense gives you `.foo:not(|)`
- When I type `".button"` overtyping on the quotes work
- Then I proceed to close the parenthesis of the `:not` attribute, even though it's already there and this is where the bug appears and overtyping does not work, so I end up with `.foo:not(".button"))`

**Comment by misolori** [comment] 2019-07-31 15:17
Here's an example on Windows when extensions are disabled and just trying to close the parenthesis when there's one already there:

![Untitled 3 2019-07-31 08_16_24](https://user-images.githubusercontent.com/35271042/62224434-883bbe00-b36b-11e9-9a79-724200fd09bc.gif)

**Comment by sana-ajani** [comment] 2019-07-31 16:46
Ah, okay. I'm able to repro that. The ending ) doesn't overtype.

**Comment by misolori** [comment] 2019-08-07 17:25
Ping @alexandrudima 😄

**Comment by alexandrudima** [comment] 2019-08-08 15:50
The `)` in this cases comes from intellisense (not from the auto-closing feature)... that's why it is not getting overtyped... The editor overtypes only parens that got inserted via auto-closing.

**Comment by alexandrudima** [comment] 2019-08-15 15:26
Let's track in #78975

**Closed by alexandrudima** 2019-08-15 15:26 UTC
Labels: editor-autoclosing
