### ISSUE TITLE
Wrong behaviour of checkboxes in Settings UI when the name of the setting starts with the name of another setting

### ISSUE THREAD

**Issue by theNestruo** [microsoft/vscode#197013] opened 2023-10-30 18:04 UTC
Does this issue occur when all extensions are disabled?: No (as it is related to extension settings)

- VS Code Version: Version: 1.83.1 (user setup)
- OS Version: Microsoft Windows [Version 10.0.19045.3636]

Steps to Reproduce:

1. Install one extension with boolean settings whose name (e.g.: "foo.bar.baz") start with another setting name (e.g.: "foo.bar")
2. Open Settings UI
3. Scroll the checkbox for the "foo.bar.baz" setting in and out of the view.
4. The checkbox is shown as checked or unchecked randomly, instead of showing the value of the property (expected behaviour)

Also:

3. Click the checkbox for the "foo.bar.baz" setting.
4. Other checkboxes get checked/unchecked at the same time.

A video of the issue in a real life extension: https://github.com/theNestruo/z80-asm-meter-vscode/issues/150#issuecomment-1784626152

A minimal extension that can be used to reproduce the issue: https://github.com/theNestruo/settingsui-checkbox-issues-vscode

**Comment by rzhao271** [comment] 2023-10-30 19:57
Settings where the name of one starts with the name of another aren't supported at this time.
Duplicate of #176373

**Closed by rzhao271** 2023-10-30 19:57 UTC
