### ISSUE TITLE
files.exclude isn't respected by QuickOpen

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#2788] opened 2016-02-08 13:30 UTC
Trying to exclude some directories from `workbench.action.quickOpen` but it doesn't seem to apply.

```
"files.exclude": {
    ".svn": true,
    "out/": true
}
```

It takes effect under SEARCH though.

**Comment by bpasero** [comment] 2016-02-08 13:31
@csholmq attach screen shot where it does not work in quick open please

**Comment by csholmq** [comment] 2016-02-08 13:35
![image](https://cloud.githubusercontent.com/assets/1297882/12886927/20c71478-ce71-11e5-9f69-9e93851add4f.png)

**Comment by bpasero** [comment] 2016-02-08 13:40
@csholmq I think it does not work because it is not root, try **/out/

**Comment by csholmq** [comment] 2016-02-08 13:42
@bpasero Confirmed to work. Is this by design?

**Comment by bpasero** [comment] 2016-02-08 14:31
I just tried and for me explorer, search and quick open behave all the same when I try to ignore a root folder. If you can provide me with a repro?

**Comment by csholmq** [comment] 2016-02-08 14:53
Yes, excluding root folders using `root-folder/` work. But not for sub folders.

No public repo for this. But I can set up a demo if needed.

**Comment by bpasero** [comment] 2016-02-08 15:24
@csholmq ah ok I thought you said it would exclude in one area but not in the other. so as long as it does not exclude anywhere, we are at least consistent.

**Comment by bpasero** [comment] 2016-02-08 15:25
Actually I am closing this as designed because as a user I want to distinguish between a root folder and a sub folder.

**Closed by bpasero** 2016-02-08 15:25 UTC
Labels: feature-request, search

**Comment by csholmq** [comment] 2016-02-08 18:31
That seems to be the case. I was initially confused by this (and false positives from "recently opened" files) that led me to believe the behaviour to be inconsistent. But by the looks of it, I was mistaken.

But I do think it's a little picky with the expressions:

- `*/subdir` **No**
- `*/subdir/` **No**
- `*/subdir/*` **No**
- `**/subdir` **Yes**
- `**/subdir/*` **Yes**

**Comment by bpasero** [comment] 2016-02-09 06:08
That is very normal glob pattern behavior, * is for one character, ** for any.

**Comment by csholmq** [comment] 2016-02-09 06:35
Oh, ok. This is different from Atom behavior. Hence my confusion.

**Comment by bpasero** [comment] 2016-02-09 06:38
To be more specific: * matches one or more characters in a path segment, and ** spans multiple path segments.

**Comment by csholmq** [comment] 2016-02-09 07:25
Got it. In Atom, `subdir` is sufficient to exlude any path or file with that string in it. `subdir/` to specify directory.
