### ISSUE TITLE
vs-code 1.11.0- insider - Scroll bar with touch pad it solved but it weird

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#22817] opened 2017-03-18 02:37 UTC
The problem is scroll bar with touch-pad is very jumpy and lagging which is very bad experience

The solution:
--------------------
When I restore down the vs-code and then maximized again the scroll work fine which is very weird. 

..
>Dell laptop - windows 10

**Comment by weinand** [comment] 2017-03-18 10:01
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by pixieaka** [comment] 2017-03-18 15:17
same result without any extensions, same issue here https://github.com/electron/electron/issues/8960

**Comment by weinand** [comment] 2017-03-20 10:28
@pixieaka thanks for the additional info. I've close this because this is an upstream issue.

**Closed** 2017-03-20 10:27 UTC
Labels: bug, upstream
