### ISSUE TITLE
Source Control

### ISSUE THREAD

**Issue by JosueSO** [microsoft/vscode#142893] opened 2022-02-12 00:07 UTC
Issue Type: <b>Bug</b>

After last update, the source control panel doesn´t work

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.93GB free)|
|Process Argv|--crash-reporter-id 9dfb5e93-8631-40cb-8f8b-16d889e86875|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.6
bracket-pair-colorizer|Coe|1.0.62
react-redux-react-router-snippets|dis|0.4.29
es7-react-js-snippets|dsz|4.3.2
prettier-vscode|esb|9.2.0
vs-code-xml-format|fab|0.1.5
styled-snippets|fer|1.0.3
vscode-react-typescript|inf|1.3.1
styled-components-snippets|jon|0.10.0
vscode-styled-components|jpo|1.7.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.4
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|11.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30437039
vsrem710:30416614
dsvsc008:30436278
pythonvsnew555:30436484
vsbas813:30436447
vscscmwlcmt:30436993

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-02-12 05:10
Please explain "doesn't work".

/needsMoreInfo

**Comment by deefdragon** [comment] 2022-02-13 06:16
I am experiencing this same issue. "Doesn't work" honestly is a reasonable description, but to provide more exact details, the only thing that shows up is the "Initialize Repository" stuff.
The button is grayed out, but still clickable, however, clicking does nothing. 

This was tested on multiple Repo's, and having restarted multiple times.
![source](https://user-images.githubusercontent.com/3053654/153741273-b8bcfc25-21ac-4eff-9196-fc4e51f1fdb3.png)

**Comment by deefdragon** [comment] 2022-02-13 06:48
I just went through and disabled/enabled all of my extensions until it worked again, vscode-Icons was the one that, when disabled, allowed it to work again.

**Comment by gjsjohnmurray** [comment] 2022-02-13 07:39
@JosueSO it looks like you are also using the extension which caused a problem for @deefdragon

When investigating VS Code problems the Start Extension Bisect command is often useful.

**Comment by lszomoru** [comment] 2022-02-16 11:16
@deefdragon, very interesting. Could you please share the contents of the contents of the `Log (Extension Host)` output channel. I would really like to track down the reason why an extension (`vscode-icons`) interferes with the SCM viewlet. Thank you very much.

**Comment by deefdragon** [comment] 2022-02-18 09:46
I'm actually no longer able to get the issue to trigger, even on the old version of the extension.

**Comment by jonrimmer** [comment] 2022-02-25 12:28
I had the same issue, but in my case it was caused by the [Peakcock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension.

There is nothing suspicious in the extension host log AFAICS:

```
[2022-02-25 12:26:16.998] [exthost] [info] Extension host with pid 19455 started
[2022-02-25 12:26:17.540] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:typescriptreact'
[2022-02-25 12:26:17.551] [exthost] [info] ExtensionService#_doActivateExtension clinyong.vscode-css-modules, startup: false, activationEvent: 'onLanguage:typescriptreact'
[2022-02-25 12:26:17.613] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-02-25 12:26:17.628] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-02-25 12:26:17.640] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.github
[2022-02-25 12:26:17.659] [exthost] [info] ExtensionService#_doActivateExtension redhat.vscode-yaml, startup: true, activationEvent: '*', root cause: 42Crunch.vscode-openapi
[2022-02-25 12:26:17.713] [exthost] [info] ExtensionService#_doActivateExtension johnpapa.vscode-peacock, startup: true, activationEvent: '*'
[2022-02-25 12:26:17.750] [exthost] [info] ExtensionService#_doActivateExtension KnisterPeter.vscode-github, startup: true, activationEvent: '*'
[2022-02-25 12:26:17.869] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare, startup: true, activationEvent: '*', root cause: ms-vsliveshare.vsliveshare-audio
[2022-02-25 12:26:18.062] [exthost] [info] ExtensionService#_doActivateExtension RobbOwen.synthwave-vscode, startup: true, activationEvent: '*'
[2022-02-25 12:26:18.221] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-02-25 12:26:18.668] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-02-25 12:26:18.874] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-02-25 12:26:27.516] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-02-25 12:26:27.521] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-02-25 12:26:27.526] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
```

**Comment by lszomoru** [comment] 2022-03-10 11:05
We have tracked down a problem with the extension activation code (https://github.com/microsoft/vscode/issues/144518) that has been fixed yesterday. Tomorrow's (2022-03-11) Insiders release should contain the fix to the extension activation code.

**Comment by lszomoru** [comment] 2022-03-10 11:05
Closing as duplicate of #144518

**Closed by lszomoru** 2022-03-10 11:05 UTC
Labels: needs more info, git

**Comment by spinicist** [comment] 2022-04-01 09:56
I am having a similar but different problem. When running VS Code on our Linux cluster my source control panel looks like this:
<img width="268" alt="Screenshot 2022-04-01 at 10 52 00" src="https://user-images.githubusercontent.com/11050744/161240598-64f3b8aa-18b1-4a08-87d8-72cd42453918.png">

The source control panel works correctly on my local laptop with the same repo. I have disabled all extensions and the problem persists.

The only pertinent information I can think of is that the particular server I am running VS Code on cannot talk to github (due to credentials problems). To push/pull to github I have to use the command-line on a different server. However, it used to work for showing the local repo changes.

What other information can I provide?

**Comment by lszomoru** [comment] 2022-04-01 10:31
@spinicist, are you running the same version of VS Code on all the machines? 
Could you please open dev tools (`Developer: Toggle Developer Tools` command) and see if there are any errors?

**Comment by spinicist** [comment] 2022-04-01 12:21
On both Linux servers the VS Code version is 1.63.2

There is an error, but this seems to be present on both remote servers:

ERR [Extension Host] (node:117619) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:77 [Extension Host] (node:117619) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)

**Comment by lszomoru** [comment] 2022-04-11 12:01
@spinicist, could you please file a separate issue to track this problem? Thank you!

**Comment by spinicist** [comment] 2022-04-20 13:35
Hi @lszomoru, sorry for the delayed response.

Today I was trying to diagnose a different problem, and during that I deleted the `~/.config/Code` directory. I restarted Code after doing that, and source-control appears to work again. So consider this closed again for now!
