### ISSUE TITLE
'Type aliases can be used only in a .ts file' error popping up in Flow enabled files

### ISSUE THREAD

**Issue by gcazaciuc** [Microsoft/vscode#15171] opened 2016-11-08 13:18 UTC
- VSCode Version:
1.7.1
- OS Version:
Ubuntu 16

Steps to Reproduce:
Create a .js file and add the following code in it(the file will be processed by Flowtype):
```js
// @flow
type LogActionsType = { type: 'NEW_LOG', payload: Array<Object> } | { type: 'LOGS_PUSHED', payload: null };
export type LogType = Object
```
Whenever I define a type alias the error 'Type aliases can be used only in a .ts file'  keeps showing up and is highlighed in the 'Problems' panel.
Is there any way to disable typescript ? Or prevent this kind of validation of running ?

**Comment by lee-fu** [comment] 2016-11-08 15:18
Got the same issue:

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0

`// @Flow` annotation at top of file.

and `javascript.validate.enable": false` in my Workspace settings.

Error highlighted:
```
[js] 'types' can only be used in a .ts file.
[Flow]
string: (object: Object) => Array<string>
```

**Comment by waderyan** [comment] 2016-11-11 22:42
Confirmed on latest bits. Moving to TS Server repo.

**Comment by waderyan** [comment] 2016-11-11 22:42
This issue was moved to Microsoft/TypeScript#12186

**Comment by waderyan** [comment] 2016-11-14 22:28
Reopening here. The suggestion from TS team recommends this be handled on VS Code's side. 

The recommendation is for VS Code to check to see the Flow annotation and not pass it on to the TS Server. 

@dbaeumer this looks like something we should look into soon as it can be a poor experience for flow users.

**Comment by dbaeumer** [comment] 2016-11-15 00:57
@waderyan this should not go into the TS extension. We shouldn't parse the first line. There are two ways to deal with this:

- users disable JS validation using `javascript.validate.enable": false`
- users install a flow extension which add  flow language mode. Then these files will not be synced over to the tsserver.

**Comment by dbaeumer** [comment] 2016-11-15 01:00
I tested that if I set `javascript.validate.enable": false` that the error is not shown.

![capture](https://cloud.githubusercontent.com/assets/1931590/20288962/41f77eb0-aad7-11e6-8326-bce748232f16.png)

**Comment by dbaeumer** [comment] 2016-11-15 01:00
@waderyan recommend to close.

**Closed** 2016-11-15 17:19 UTC
Labels: intellisense, js, not-reproducible

**Comment by xareelee** [comment] 2017-04-11 05:53
I still got this error with `Flow 0.40` using `VSCode 1.10.2`.

**Comment by FezVrasta** [comment] 2017-05-24 17:27
I still get this error even if I disable the option and restart VS Code..

**Comment by coremessage** [comment] 2017-07-07 10:54
> I still got this error with Flow 0.40 using VSCode 1.10.2.

I still got this issue with VSCode 1.13.1.
After restarting VSCode, the issue is going away. But it's only a matter of time before it comes back. I find myself having to restart VSCode at least once per hour, which is quite annoying.
I've got `javascript.validate.enable` set to `false`.

**Comment by cdimascio** [comment] 2017-07-16 19:31
I was able to resolve by:
1. Set `javascript.validate.enable` to `false`
2. Moved `.flowconfig` from my `src` dir to the workspace root
Hope this helps.

**Comment by foobar8675** [comment] 2017-07-24 22:27
I am also still getting this error. I have the .flowconfig in my root and set `javascript.validate.enable` to false. Any troubleshooting steps would be appreciated.

![foo1](https://user-images.githubusercontent.com/1685700/28547570-55741cdc-7084-11e7-8856-dd1cc9a1726c.png)
![foo2](https://user-images.githubusercontent.com/1685700/28547584-639647c2-7084-11e7-952a-ba525e7d60a2.png)

I'm on vscode Version 1.14.2 (1.14.2) and flow ^0.42.0

**Comment by foobar8675** [comment] 2017-08-16 14:16
Maybe this will be helpful for someone, ... what I did (i think) to finally get ts to stop was adding `.tsconfig` 
```
{
    "compilerOptions": {
        "module": "system",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "outFile": "../../built/local/tsc.js",
        "sourceMap": true
    },
    "include": [
    ],
    "exclude": [
        "**/*.js"
        "node_modules",
    ]
}
```

**Comment by johnunclesam** [comment] 2017-10-29 17:26
@foobar8675 the problem is still there:

![image](https://user-images.githubusercontent.com/21275217/32146330-296a8a2e-bcd6-11e7-9571-cccb2a9983ec.png)

I writed this file: ".tsconfig" in root folder (tried also in just "./src" folder), reloaded VSCode and still the problem.

**.tsconfig**:

```
{
  "compilerOptions": {
    "module": "system",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "outFile": "../../built/local/tsc.js",
    "sourceMap": true
  },
  "include": [],
  "exclude": ["**/*.js", "node_modules"]
}
```

**Comment by foobar8675** [comment] 2017-10-29 18:45
@johnunclesam sorry, i have no idea what the issue is then.
