### ISSUE TITLE
check mark emoji ✔ isn't delete but change it appearance

### ISSUE THREAD

**Issue by Its-Just-Nans** [microsoft/vscode#109812] opened 2020-11-01 15:46 UTC
- VSCode Version: **1.50.1**
- OS Version: **Windows 10 - 1909**

Steps to Reproduce:

1.Copy this emoji ✔️(or here https://emojipedia.org/check-mark/)
2.Put your cursor before the emoji and delete it with the 'delete' key -> it will be delete
3.Put your cursor after the emoji and delete it with the 'backSpace' key  (the delete key) -> it will change

The fact that it isn't delete appear in other software like chrome is quite "normal" but the fact that its appearance change is weird

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by alexdima** [comment] 2020-11-06 10:25
Duplicate of #99629

**Closed by alexdima** 2020-11-06 10:25 UTC
