### ISSUE TITLE
Cant change Shorcuts/Keybinding

### ISSUE THREAD

**Issue by victorst79** [microsoft/vscode#173280] opened 2023-02-03 10:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.75.0
- OS Version: Elementary OS 6.1 (Ubuntu 20.04.5)

Steps to Reproduce:

1.  Open the shortcuts configuration tab.
2. Change '**Toggle Block Comment**' keybinding (Default -> ctrl + ç)

When I change the **Toggle Block Comment** bind from default to [_ctrl + ç_] it appears when I press enter as [_ctrl + y_].
I have tried with the extensions disabled and it does not allow to replace the shortcut correctly either. Of course this shortcut [_ctrl + ç_] is not in use in any other shortcut.

**Comment by benj2k** [comment] 2023-02-03 11:22
All my customs shortcuts are reset (or nor working).
My keybindings.json file is correctly set (at least it used to work with the previous VSCode version)
```
[
    {
        "key": "ctrl+d",
        "command": "-editor.action.addSelectionToNextFindMatch",
        "when": "editorFocus"
    },
    {
        "key": "ctrl+d",
        "command": "editor.action.duplicateSelection"
    },
    {
        "key": "ctrl+k ctrl+c",
        "command": "-editor.action.addCommentLine",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+alt+[Period]",
        "command": "editor.action.removeCommentLine",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+k ctrl+u",
        "command": "-editor.action.removeCommentLine",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "alt+left",
        "command": "workbench.action.navigateBack"
    },
    {
        "key": "alt+right",
        "command": "workbench.action.navigateForward",
        "when": "canNavigateForward"
    },
    {
        "key": "ctrl+shift+6",
        "command": "-workbench.action.navigateForward",
        "when": "canNavigateForward"
    },
    {
        "key": "ctrl+[Period]",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+shift+[Period]",
        "command": "-editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "alt+f9",
    {
        "key": "alt+f9",
        "command": "-editor.action.nextCommentThreadAction",
        "when": "editorFocus"
    },
    {
        "key": "ctrl+[Period]",
        "command": "-breadcrumbs.focus",
        "when": "breadcrumbsPossible && breadcrumbsVisible"
    },
    {
        "key": "ctrl+[Period]",
        "command": "workbench.action.terminal.sendSequence",
        "when": "terminalFocus"
    },
    {
        "key": "ctrl+shift+[Period]",
        "command": "-workbench.action.terminal.sendSequence",
        "when": "terminalFocus"
    }
]
```
But no effect after update to latest version 
Ubuntu 22.04
VSCode 1.75.0

**Comment by fardolieri** [comment] 2023-02-03 11:25
I have a similar problem with my custom keybind `CTRL + #` to toggle line comments. I am on linux and use a german layout. My setting before worked fine.
```js
{
    "key": "ctrl+[Backslash]", // <-- I don't know why it's called Backslash, but it got correctly bound to '#'
    "command": "editor.action.commentLine",
    "when": "editorTextFocus && !editorReadonly"
  },
```

But with the new update it strangely binds to `CTRL + Y`.

![Recording 2023-02-03 at 12 14 48](https://user-images.githubusercontent.com/56280926/216591636-5fe4fc2a-2df3-44e3-9977-df796ec9eb62.gif)

![image](https://user-images.githubusercontent.com/56280926/216591830-c45f1f60-7e0e-4125-a214-8d7a247aa30f.png)

**Comment by marcfilleul** [comment] 2023-02-04 11:43
Same issue with the last update

**Comment by alexdima** [comment] 2023-02-05 21:00
Duplicate of #173325

**Closed by alexdima** 2023-02-05 21:00 UTC
Labels: new release
