### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by Dr-Fabian** [microsoft/vscode#98806] opened 2020-05-29 13:35 UTC
Issue Type: <b>Bug</b>

Installing an extension doesn't work anymore.

VS Code version: Code - Insiders 1.46.0-insider (1d268b701376470bc638100fbe17d283404ac559, 2020-05-28T08:35:19.384Z)
OS version: Linux x64 5.3.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3310)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 2, 1|
|Memory (System)|7.73GB (3.14GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-eslint|dba|2.1.5
vscode-great-icons|emm|2.1.47
vsc-material-theme-icons|equ|1.1.4
file-icons|fil|1.0.24
discord-vscode|icr|3.14.0
easy-icons|jam|0.3.1
vscode-simple-icons|Lau|1.13.2
vscode-react-native|msj|0.16.0
deepdark-material|Nim|3.2.1
sass-indented|syl|1.8.4
vscode-icons|vsc|10.1.1

(13 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-05-29 14:15
/duplicate of #98726

Latest Insiders version has fix for this issue.
Version: 1.46.0-insider (user setup)
Commit: cd41dd1f6065db76c77c6e2f659bb50e6f558dec
Date: 2020-05-29T05:51:32.662Z

**Closed** 2020-05-29 14:16 UTC
Labels: *duplicate
