### ISSUE TITLE
About smart tips and completion

### ISSUE THREAD

**Issue by xhonker** [Microsoft/vscode#17575] opened 2016-12-20 02:17 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-onedark|azemoh|0.4.1|
|npm-intellisense|christian-kohler|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.0.30|
|auto-rename-tag|formulahendry|0.0.8|
|rest-client|humao|0.11.2|
|docthis|joelday|0.3.5|
|vue|liuji-jim|0.1.5|
|debugger-for-chrome|msjsdiag|2.4.1|
|cssclasshint|nicolasalcaraz|0.0.3|
|indenticator|SirTori|0.2.1|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.2.4|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.alt+f12  and f12 Intelligent prompt and completion  On failure 
![_20161220101613](https://cloud.githubusercontent.com/assets/20201169/21335983/82495a88-c69d-11e6-8db8-b78f4bfae317.png)
![_20161220101645](https://cloud.githubusercontent.com/assets/20201169/21335984/8249bdca-c69d-11e6-9c8c-07c9f56a8551.png)

2.all of  , Above is just an example,This problem was long ago. Be sure to restart vsc Just normal

**Comment by waderyan** [comment] 2016-12-20 17:09
@xhonker thank you for opening this issue. I'm having a hard time understanding what the error is. 

From what you've shown it looks like <kbd>F12</kbd> is taking you to the correct location. 

Can you clarify what you are seeing? Can you share your workspace so I can recreate it on my end?

**Comment by xhonker** [comment] 2016-12-21 01:44
Is in the right place. but Intelligent induction  and Intelligent prompt is none

**Comment by xhonker** [comment] 2016-12-23 07:43
测试了下，只有在window 上有这个问题。苹果是没有的。 插件什么的都装一样的 window就是不行。

**Comment by waderyan** [comment] 2017-01-03 22:26
@xhonker I'm not able to reproduce on my end. Can you share your workspace?

**Comment by mjbvz** [comment] 2017-01-13 01:37
Closing as we need more info to investigate this.

@xhonker Please provide:

* Some example code
* steps to reproduce this issue
* Expected behavior
* Actual behavior

Thanks

**Closed by mjbvz** 2017-01-13 01:37 UTC
Labels: intellisense, javascript, needs more info
