### ISSUE TITLE
Sparkle overlays text

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#196065] opened 2023-10-20 06:13 UTC
<img width="282" alt="image" src="https://github.com/microsoft/vscode/assets/900690/c7fe12f3-2ea8-4717-964e-57453ccdc237">

**Comment by lszomoru** [comment] 2023-10-23 20:41
Closing as duplicate of https://github.com/microsoft/vscode-copilot/issues/2040.

**Closed by lszomoru** 2023-10-23 20:41 UTC
