### ISSUE TITLE
search.useIgnoreFilesByDefault should explain in description that this is used for quick open

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37213] opened 2017-10-31 07:56 UTC
Refs: #37179

Currently useIgnoreFilesByDefault never mentions that this is actually used for quick open. From the description the user would get a feeling that this is only used for search viewlet.
I propose to update the description and clarify that this setting is for quick pick.

Also why the phrase "new workspace"?

**Comment by chrmarti** [comment] 2017-11-02 22:40
Closing this as a duplicate of #37291 which introduced a new setting. The old setting is now described as "for text search" and the new as "for file search". The idea is to replace the old setting with the new one in the future together with a change to the buttons in the search viewlet.

**Closed by chrmarti** 2017-11-02 22:40 UTC
