### ISSUE TITLE
Editor has a dynamic grey box

### ISSUE THREAD

**Issue by jxe142** [microsoft/vscode#94971] opened 2020-04-11 04:33 UTC
Issue Type: <b>Bug</b>

Each time I use the editor there is a grey box that moves around on the screen as I type, where there is usally black text editor

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.7.1
prettier-vscode|esb|4.2.0
vscode-styled-components|jpo|0.0.29
python|ms-|2020.3.71659
remote-wsl|ms-|0.44.2
LiveServer|rit|5.6.1
code-spell-checker|str|1.8.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by jxe142** [comment] 2020-04-11 04:34
![image](https://user-images.githubusercontent.com/26750289/79035399-2aaf7080-7b8c-11ea-9a57-cdca4ca6137a.png)

**Comment by RMacfarlane** [comment] 2020-04-11 06:43
@jxe142 Does this reproduce when extensions are disabled as well? You can temporarily disable them with the `Developer: Reload with Extensions Disabled` command

**Comment by jxe142** [comment] 2020-04-11 07:02
Yes it does still show up with extensions disabled.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gjsjohnmurray** [comment] 2020-04-11 09:59
@jxe142 try launching with the --disable-gpu option on the command line

`code --disable-gpu `

**Comment by jxe142** [comment] 2020-04-11 16:38
Did not solve the issue unfortunately 😞

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RMacfarlane** [comment] 2020-04-12 16:15
@jxe142 Can you run `Developer: Toggle Developer Tools` and use the inspector tool to find the HTML that defines the gray box? What does it look like?

**Comment by lengthmin** [comment] 2020-04-13 14:17
try https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562

disable hardware acceleration

**Comment by jxe142** [comment] 2020-04-16 02:16
@RMacfarlane Here is a line of HTML that has a grey box 

`<div style="top:988px;height:19px;" class="view-line"><span><span>&nbsp;</span></span></div>`

![image](https://user-images.githubusercontent.com/26750289/79407132-bcd9bf00-7f66-11ea-8ef7-1511480f2081.png)

**Comment by jxe142** [comment] 2020-04-16 02:20
@lengthmin We gave that a shot and it did not seem to work

**Comment by gjsjohnmurray** [comment] 2020-04-20 10:00
@jxe142 does https://github.com/microsoft/vscode/issues/95675#issuecomment-616407635 help you?

**Comment by jxe142** [comment] 2020-04-24 23:33
@gjsjohnmurray Unfortunately, not it did not seem to work.

**Comment by Sejsel** [comment] 2020-05-05 17:22
I also have this issue, and https://github.com/Microsoft/vscode/issues/12473 used to be the exact same thing. 

I have the same CPU, so I am guessing gpu drivers cause this. No extensions.

-- | --
CPUs | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled

**Comment by makluv** [comment] 2020-05-06 19:17
I have the exact same issue and also have the i7-1065G7 like @Sejsel.

**Comment by jxe142** [comment] 2020-05-06 20:56
Agreed @makluv the whole viewport seems way darker than the rest of my applications. I had a feeling it was with the new iris plus graphics.

**Comment by Sejsel** [comment] 2020-05-13 13:30
This seems to only happen if "Play HDR games and apps" is enabled in "Windows HD Color Settings". Disabling that fixes it, and also removes the annoying dynamic brightness changes that I've been seeing with this.

**Comment by jxe142** [comment] 2020-05-13 13:37
@Sejsel You're right that does work now. Which is odd since it didn’t work before. I was having the same issue with chrome and it fixed some of the bugs as well. Mainly taking screenshots was blown out.

**Comment by bryanhunwardsen** [comment] 2020-05-31 07:59
I have this issue as well (threadripper+rx7 - so its not an intel proc/gpu or integrated drivers issue)
I had this issue once before maybe a year or 2 ago on insiders build on a lenovo x1carbon, --disable-gpu worked then, eventually a new build came and the flag was nolonger required.

Once i recalled the --disable-gpu flag I tried it again, and again the issue stopped, I then tried disabling HDR (3x 4kHDR Monitors) via DisplayProperties for a single monitor, but it did not work on that or any monitor, I then disabled just the "Stream HDR Video" but kept "Use HDR" for the default first listed #1 display which immediately stopped the issue.

Of course I turned it back on, posting here to get eyes on because disabling gpu, or turning HDR off is not a solution.

CPUs	AMD Ryzen Threadripper 2920X 12-Core Processor (24 x 3493)
VS Code version: Code - Insiders 1.46.0-insider (cd41dd1f6065db76c77c6e2f659bb50e6f558dec, 2020-05-29T05:51:32.662Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 2920X 12-Core Processor  (24 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (20.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.15.1
prettier-vscode|esb|4.7.0
code-sync|gol|2.7.2
vscode-line-endings|jha|0.2.0
solidity|Jua|0.0.73
csharpfixformat|Leo|0.0.84
rainbow-csv|mec|1.7.0
render-crlf|med|1.5.3
git-graph|mhu|1.23.0
nc-gcode|ML|0.13.0
vscode-cosmosdb|ms-|0.13.0
csharp|ms-|1.22.0
mssql|ms-|1.9.0
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.11
cpptools|ms-|0.28.1
powershell|ms-|2020.4.0
azure-hdinsight|msh|1.1.9
sqltools|mtx|0.22.2
platformio-ide|pla|1.10.0
usql-vscode-ext|usq|0.2.15
highlight-bad-chars|wen|0.0.3


</details>

**Comment by remidebette** [comment] 2020-06-21 10:01
Hi, I have the same issue on VSCode 1.46.1 since I switched to a HDR screen this week.
I enabled HDR features in windows and my screen and started to get this grey box.

The issue disappears when running VSCode with: 
`code --force-color-profile srgb`

**Comment by JPcorona14** [comment] 2020-07-29 07:57
@remidebette what i did to help get around this was create a cmd file that launches code.exe with start Code.exe --force-color-profile srgb. It was the only way to get around it or having to toggle HDR everytime i want to game or code which i didn't like. Having this cmd file and then creating a shortcut to it seemed to be the best options and hasn't gave me any issues as of yet. Hope this helps out anyone else.

**Comment by gjsjohnmurray** [comment] 2020-07-29 08:58
https://github.com/microsoft/vscode/issues/88491#issuecomment-600288632 gives details of how argv.json can be used to do this. And a recent update on that issue reports the problem is fixed in Insiders, which will become the new general release in August.

**Closed** 2020-08-05 11:23 UTC
Labels: needs more info
