### ISSUE TITLE
Collapse disappears

### ISSUE THREAD

**Issue by Zawgar** [Microsoft/vscode#13957] opened 2016-10-18 18:55 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: abusaidm.html-snippets-0.0.17, donjayamanne.githistory-0.1.0, donjayamanne.jquerysnippets-0.0.1

Steps to Reproduce:
1. The widget code to collapse disappear in some places
2. If you edit any part of the code, the code to collapse buttons reappear.

**Comment by roblourens** [comment] 2016-10-18 21:43
Are you talking about these code folding buttons? 
![image](https://cloud.githubusercontent.com/assets/323878/19497460/37e9c1a4-9541-11e6-8325-dbb1bd7bee20.png)

They only appear when you hover over them. I don't quite understand your issue.

**Comment by Zawgar** [comment] 2016-10-19 15:02
Gracias por responder.
En algúnos momentos, estos botones no aparecen cuando pongo el cursor
sobre la barra donde deberían estar. Lo mas raro es que algunos no
aparecen y otros sí.
Es mas, cuando edito cualquier cosa, por ejemplo, agrego un espacio en
el archivo que estoy editando, estos botones vuelven a aparecer.

/*Google Traductor*/

Thanks for answering.
At times, these buttons do not appear when I put the cursor on the bar
where they should be. The strangest thing is that some do not appear
and others do. What's more, when I edit anything, for example, I add a
space in the file that I'm editing, these buttons reappear.

Gracias/Thanx

2016-10-18 18:44 GMT-03:00 Rob Lourens <notifications@github.com>:

**Comment by roblourens** [comment] 2016-10-19 16:27
Could you record a gif or something when they don't appear? I'm not sure whether it's a bug or not.

**Comment by Zawgar** [comment] 2016-10-21 14:59
Dentro de el circulo rojo debería Aparecer un Botón para Expandir el Código. El puntero del mouse esta sobre la barra.

Inside the red circle should appear a button to Expand Code. The mouse pointer is over the bar.

Gracias/Thanx
![vsc_error](https://cloud.githubusercontent.com/assets/13787811/19602912/69c6e1fc-9785-11e6-981a-1aced900892a.jpg)

**Comment by roblourens** [comment] 2016-10-21 16:24
Actually I'm not sure that it should appear there, since that function is empty. If it was collapsed, there would be a '...' at the end of the line like you see at the bottom.

**Comment by aeschli** [comment] 2016-10-21 19:06
Yes, it looks like that's an empty function, and there's nothing collapsed there.

**Comment by Zawgar** [comment] 2016-10-24 19:52
Última oportunidad de que entiendan cual es el error.
El puntero esta sobre la barra lateral. (no aparece en la captura)

![vsc_error](https://cloud.githubusercontent.com/assets/13787811/19661442/20e78bd0-9a0a-11e6-856e-2ca0dbf3e65e.jpg)

**Comment by roblourens** [comment] 2016-10-24 20:20
@aeschli Seems like there should be one in that case?

**Comment by aeschli** [comment] 2016-10-24 20:43
Please paste a (small) code example that demonstrates the bug....

**Comment by Zawgar** [comment] 2016-10-24 20:52
Está a sólo una manzana no depende del tipo de código o lenguaje.
También me pasó hace unos minutos con el código CSS.
Creo que la ventana de VSC perdió el "foco" y por lo tanto no detecta que el puntero del ratón se sitúe la barra lateral.
/*********************************/
Is just a block does not depend on the type of code or language.
I also happened a few minutes ago with CSS code.
I think the window of VSC lost the "focus" and therefore not detect that the mouse pointer is hover the sidebar.

**Comment by roblourens** [comment] 2016-10-24 21:17
Yes, if the window isn't focused, the expand buttons won't appear. You'll have to click on the window again to focus it.

**Comment by Zawgar** [comment] 2016-10-25 00:57
Yessss, i know, but "I AM IN FOCUS" in this screenshots.

**Comment by aeschli** [comment] 2016-10-25 07:50
Can you add a complete code example that shows the bug?

**Comment by DasJott** [comment] 2016-10-31 09:43
Might be a duplicate of #14748 or the other way around

**Comment by aeschli** [comment] 2016-11-04 16:18
Closing do to lack of information.

**Closed by aeschli** 2016-11-04 16:18 UTC
Labels: editor-folding, needs more info
