### ISSUE TITLE
Feature Request: Extending the Problems Tab

### ISSUE THREAD

**Issue by Glober777** [Microsoft/vscode#33497] opened 2017-08-30 09:28 UTC
It would be really great if there was a possibility to extend the Problems tab in VSCode. In particular, there should be a way to control the context menu items for each selected item or items. That would allow applying fixes (where applicable) directly from the tab, and not clicking on the light bulb next to every issue in the code (i.e. PowerShell/vscode-powershell#717).

**Comment by sandy081** [comment] 2017-10-25 09:21
Added support for contributing actions to problems view context menu - https://github.com/Microsoft/vscode/issues/36881

**Comment by jrieken** [comment] 2017-10-25 09:57
> hat would allow applying fixes (where applicable) directly from the tab,

@Glober777 Do you mean all possible fixes for all possible locations/errors?

**Comment by sandy081** [comment] 2018-07-12 14:55
@Glober777 @jrieken Can I assume that this is a feature request for showing quick fixes in Problems view and make duplicate of #52627 ? Unless @Glober777 still wants to customise other actions to problems tab.

**Comment by sandy081** [comment] 2018-07-16 14:09
Thanks @Glober777 

Closing this as supporting quick fixes is handled.

**Closed by sandy081** 2018-07-16 14:09 UTC
Labels: editor-code-actions, error-list, feature-request
