### ISSUE TITLE
[JavaScript] Broken syntax highlight for multiple variable definition using single 'var'

### ISSUE THREAD

**Issue by mubaidr** [Microsoft/vscode#4474] opened 2016-03-20 17:14 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. Open Any JS File
2. Define multiple variables using single var. i.e.
`var a = 0,
b = 1,
c = 3;`
3. Syntax highlighting for b,c will be broken. (Tested on multiple themes)

![capture](https://cloud.githubusercontent.com/assets/2222702/13905695/0007b90c-eee9-11e5-827d-e655b6309b5c.PNG)

**Comment by aeschli** [comment] 2016-03-21 11:04
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/121

**Comment by aeschli** [comment] 2016-03-21 11:05
The screenshot seems to be for a different issue, can you confirm?

**Closed by aeschli** 2016-03-21 11:04 UTC

**Comment by mubaidr** [comment] 2016-03-21 12:06
In the screen-shot, 'last_mouse' variable should have been highlighted same as 'mouse' var.
