### ISSUE TITLE
indentation error on the line with color code

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/vscode#32744] opened 2017-08-17 23:34 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
regex|chr|0.1.0
vscode-html-css|ecm|0.1.7
vscode-great-icons|emm|2.1.14
vsc-material-theme|Equ|1.0.2
json-tools|eri|1.0.2
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
auto-rename-tag|for|0.0.14
mdhelper|jos|0.0.11
debugger-for-chrome|msj|3.1.8
material-icon-theme|PKi|2.1.0
vscode-css-peek|pra|1.3.1
markdown-preview-enhanced|shd|0.2.5
html5-boilerplate|sid|1.0.1
quokka-vscode|Wal|1.0.50
wallaby-vscode|Wal|1.0.56
html-css-class-completion|Zig|1.8.0

(3 theme extensions excluded)

---

Steps to Reproduce:

![2017-08-17_113210](https://user-images.githubusercontent.com/12824616/29394883-e0bc084a-833f-11e7-948e-c0bbaa30a2a2.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-08-18 08:15
Can you add the code sample and a screenshot that shows the folding markers?

**Comment by ITSecMedia** [comment] 2017-08-18 10:03
I can verify this error, noticed it today.

![image](https://user-images.githubusercontent.com/3316334/29454353-234142ac-840d-11e7-85e0-50fa10bb19a5.png)

**Comment by deepkolos** [comment] 2017-08-18 11:25
@aeschli  i have post a screenshot , but i don't know why you can't see it , so post it again , with different indention , dot and tab

### dot

![2017-08-18_192256](https://user-images.githubusercontent.com/12824616/29457062-efc6ae42-844a-11e7-985e-7920c4cdb791.png)

### tab

![2017-08-18_192321](https://user-images.githubusercontent.com/12824616/29457070-f6fd4112-844a-11e7-8666-1930933a6605.png)

**Comment by alexandrudima** [comment] 2017-08-18 14:18
Duplicate of #32436

**Closed by alexandrudima** 2017-08-18 14:18 UTC
Labels: new release
