### ISSUE TITLE
Regions / Folding is broken because it's always unfolded by default c#

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Microsoft/vscode#60668] opened 2018-10-11 17:55 UTC
Regions should either remember their last state between sessions or default to all folded when a file is opened.  Currently they are all open by default (at least in c# files for me) which is utterly useless as the whole point is to hide that complexity to make it fast to visually find things in the files but as they are always unfolded when I open a file in a new editing session they seem to only be useful temporarily while working in a file.

**Comment by aeschli** [comment] 2018-10-12 08:09
duplicate of #40338

**Closed by aeschli** 2018-10-12 08:09 UTC
Labels: editor-folding

**Comment by WhatFreshHellIsThis** [comment] 2018-10-12 14:44
I respectfully disagree, this is different.  That person is asking for a setting to be added, I'm asking that the prior state be persisted or default to all folded.  You have closed this in error.

**Comment by aeschli** [comment] 2018-10-14 19:03
The prior state is already persisted (fold some ranges, close editor, reopen editor, ranges are still folded).
If this doesn't work for you, please create a new issue with a sample that shows the problem.

You want that certain ranges are folded by default. That's what is covered by issue #40338 `configure initial collapse state`

**Comment by WhatFreshHellIsThis** [comment] 2018-10-15 05:04
Ahh..ok, must be a bug then, thank you, I'll pursue that.
