### ISSUE TITLE
NVDA is frequently unable to gain focus when alt-tabbing back into VS Code

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#28316] opened 2017-06-09 08:51 UTC
NVDA is (quite frequently) unable to focus on the control with keyboard focus in VS code when alt tabbing into it from another application. What fixes it is pressing alt+f to bring upu the file menu, then pressing escape. 

When this occurs, Code is completely unuseable with NVDA (pressing tab and arrow keys doesn't do anything)

**Comment by Neurrone** [comment] 2017-06-10 12:30
This just happened to me. Whenever this occurs, it's persistent (alt-tabbing away and coming back won't fix the problem), and normal commands like ctrl+a to select text will work, but are not registered by NVDA. Alt+f1 does say that its detected a screen reader.

**Comment by Neurrone** [comment] 2017-06-11 06:50
cc @jcsteh

When my focus is on Vs Code and this occurs, restarting NVDA produces the following error:

```
ERROR - virtualBuffers.VirtualBuffer._loadBuffer (14:46:54.456):
Traceback (most recent call last):
  File "virtualBuffers\__init__.pyc", line 375, in _loadBuffer
WindowsError: [Error 1702] The binding handle is invalid
```

**Comment by jcsteh** [comment] 2017-06-11 22:56
Possibly nvaccess/nvda#5758. This will occur if Code is focused when NVDA starts. If that's the case, restarting NVDA while focused in an app which does not use a web control will work around it. For example, start Notepad, restart NVDA and then alt+tab back into Code. Does that resolve the problem?

**Comment by Neurrone** [comment] 2017-06-12 06:41
@jcsteh yeah, that error might be a separate issue from this, since it does occur in normal usage without me having to resart NVDA - maybe me seeing the invalid binding handle was just coincidental. When this invalid binding handle occurs and when I use that workaround, I'm still unable to do anything in Vs Code. Using object navigation also doesn't workk - it doesn't see anything inside the window. This is what NVDA+f1 says

```
Developer info for navigator object:
name: u'\u25cf Untitled-1 - Visual Studio Code'
role: ROLE_WINDOW
states: STATE_FOCUSABLE
isFocusable: True
hasFocus: False
Python object: <NVDAObjects.Dynamic_Ia2WebGenericWindowIAccessible object at 0x04DD0810>
Python class mro: (<class 'NVDAObjects.Dynamic_Ia2WebGenericWindowIAccessible'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.GenericWindow'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (0, 22, 1280, 668)
value: None
appModule: <'appModuleHandler' (appName u'code', process ID 8600) at address 4df2050>
appModule.productName: u'Visual Studio Code'
appModule.productVersion: u'1.12.2'
TextInfo: <class 'displayModel.DisplayModelTextInfo'>
windowHandle: 3933174L
windowClassName: u'Chrome_WidgetWin_1'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 9380
windowText: u'\u25cf Untitled-1 - Visual Studio Code'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x5dc114 at 4d02da0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=3933174, objectID=-4, childID=0
IAccessible accName: u'\u25cf Untitled-1 - Visual Studio Code'
IAccessible accRole: ROLE_SYSTEM_WINDOW
IAccessible accState: STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048576)
IAccessible accDescription: None
IAccessible accValue: None
IAccessible2 windowHandle: 3933174
IAccessible2 uniqueID: -1
IAccessible2 role: ROLE_SYSTEM_WINDOW
IAccessible2 states: IA2_STATE_OPAQUE (1024)
IAccessible2 attributes: u''
```

**Comment by Neurrone** [comment] 2018-01-09 18:11
Can confirm that NVDA is intermittently unable to read anything inside the editor when alt-tabbing back into it, with the only solution being a VS Code restart, seems separate from the restarting NVDA in a web view problem. Tested on latest insider.

**Comment by Neurrone** [comment] 2018-01-12 20:19
@jcsteh hm, any ideas since https://github.com/nvaccess/nvda/pull/7535 fixed the original error above?

**Comment by jcsteh** [comment] 2018-01-15 01:31
Based on the developer info you provided in https://github.com/Microsoft/vscode/issues/28316#issuecomment-307703175, NVDA thinks focus is on a window object, not within the document. That either means a focus event wasn't fired (most likely) or NVDA rejected the focus event for some reason (less likely). You'd need to use a win event monitoring tool to be certain. Spotify (which also uses Chromium, though not Electron) misbehaves in a similar way, so it's probably some bug in Chromium or the embedding layer; I don't see this in Chrome the browser.

I hacked around this in NVDA's Spotify app module, so a similar hack might be an interim (though not ideal) solution if this can't be fixed properly in VS Code. See the `event_gainFocus` implementation in NVDA `source/appModules/spotify.py`. I don't really have time to work on this, though, especially as I can't reproduce it quickly myself (I don't really use VS Code).

**Comment by Neurrone** [comment] 2018-01-15 03:34
@jcsteh thanks a lot for the help. 

I've been meaning to learning add-on development, so this seems simple enough for me to try.

You mentioned a win event monitoring tool. Is this buit into NVDA, or is this a third party program? Are there other tools that might be useful for add-on development?

**Comment by jcsteh** [comment] 2018-01-15 03:57
Generally, to ensure your result isn't affected by NVDA code, you'd use something outside of NVDA such as [Accessible Event Watcher](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317979(v=vs.85).aspx) (AKA AccEvent, distributed with the Windows SDK) or [AccProbe](http://accessibility.linuxfoundation.org/a11yweb/util/accprobe/). Personally, I just hack NVDA's low level win event callback to log or beep the relevant info, since that's less tedious for me, but that's a total hack and requires some understanding of NVDA's low level code. :)

**Comment by Neurrone** [comment] 2018-01-15 04:13
@jcsteh thanks, taking a look at MSDN now. I noticed that MSDN doesn't say anything about IAccessible2 at all. Is IAccessible2 a superset of MSAA? If so, then I'm assuming those tools will work for e.g firefox or electron.

**Comment by jcsteh** [comment] 2018-01-15 04:44
Yes, IA2 is a superset of MSAA. For basic stuff like focus changes, name, description, etc., accEvent will be just fine. If you need IA2 specific stuff, you need Accprobe.

Looking briefly, the hack I used for Spotify isn't quite going to work because you can't get to the document when you walk down the hierarchy from the root, which is annoyingly buggy. However, it seems the focus HWND gets set correctly, so you could try just using NVDA's `api.getDesktopObject().objectWithFocus()`.

**Comment by Neurrone** [comment] 2018-01-15 08:18
@jcsteh I used AckProbe and filtered for the focus events. It fired 3 focus events - focusing on editable text, a read only document followed by the window. Doesn't seem to be any difference between the focus events captured when this bug happens. Maybe NVDA is rejecting the first 2 focus events - will try to put some speech logs in the on focus event in NVDA to compare later.

Capture for when focus works properly:

```sh
time = 16:01:59:439 type = EVENT_OBJECT_FOCUS name = Untitled-1. Untitled file text editor., Group 1. role = text state = [opaque, editable, multiLine, selectable, focused, focusable] miscData = hwnd=80B32 ;objectId=-4; childId=-112; threadId=3604; windowClass=Chrome_RenderWidgetHostHWND; 

time = 16:01:59:439 type = EVENT_OBJECT_FOCUS name = ? Untitled-1 - rust-libaudioverse - Visual Studio Code - Insiders role = document state = [opaque, focusable, readOnly] miscData = hwnd=80B32 ;objectId=-4; childId=-8; threadId=3604; windowClass=Chrome_RenderWidgetHostHWND; 

time = 16:01:59:439 type = EVENT_OBJECT_FOCUS name = ? Untitled-1 - rust-libaudioverse - Visual Studio Code - Insiders role = window state = [normal, opaque] miscData = hwnd=1D0A4E ;objectId=-4; childId=0; threadId=3604; windowClass=Chrome_WidgetWin_1; 
```

When the bug occurs:

```sh
time = 16:06:35:553 type = EVENT_OBJECT_FOCUS name = Untitled-1. Untitled file text editor., Group 1. role = text state = [opaque, editable, multiLine, selectable, focused, focusable] miscData = hwnd=1E0C38 ;objectId=-4; childId=-148; threadId=2672; windowClass=Chrome_RenderWidgetHostHWND; 

time = 16:06:35:553 type = EVENT_OBJECT_FOCUS name = ? Untitled-1 - rust-libaudioverse - Visual Studio Code - Insiders role = document state = [opaque, focusable, readOnly] miscData = hwnd=1E0C38 ;objectId=-4; childId=-8; threadId=2672; windowClass=Chrome_RenderWidgetHostHWND; 

time = 16:06:35:553 type = EVENT_OBJECT_FOCUS name = ? Untitled-1 - rust-libaudioverse - Visual Studio Code - Insiders role = window state = [normal, opaque] miscData = hwnd=90AEE ;objectId=-4; childId=0; threadId=2672; windowClass=Chrome_WidgetWin_1; 
```

**Comment by jcsteh** [comment] 2018-01-15 09:57
Curious. That would seem to suggest the event is being rejected for some reason. The only thing I can think is that perhaps the events are being fired in the wrong order. It's hard to tell because the timestamps are the same, and I'm also not sure whether that list is supposed to be ordered with most recent first or most recent last. The last event really should be the one on the editable text field, since that's what has focus. If that event was earlier for some reason, it would be trumped by the later events. NVDA has some fairly complex logic to deal with silliness like this, but there's only so much it can do.

**Comment by Neurrone** [comment] 2018-01-15 11:58
@jcsteh yeah its weird I couldn't figure out the order of the logs were in as well. I was using AckProbe. I'll try using the tool from Microsoft.

**Comment by Neurrone** [comment] 2018-05-12 07:52
@jcsteh when this occur, NVDA's ignoring correct focus events being sent for some reason. This is the log for the events in the order that Code sends out:

```sh
time = 15:27:38:039 type = EVENT_OBJECT_FOCUS name = ? Untitled-1 - Visual Studio Code - Insiders role = window state = [normal, opaque] miscData = hwnd=80A20 ;objectId=-4; childId=0; threadId=4604; windowClass=Chrome_WidgetWin_1; 
time = 15:27:38:039 type = EVENT_OBJECT_FOCUS name = ? Untitled-1 - Visual Studio Code - Insiders role = document state = [opaque, focusable, readOnly] miscData = hwnd=40D4A ;objectId=-4; childId=-8; threadId=4604; windowClass=Chrome_RenderWidgetHostHWND; 
time = 15:27:38:039 type = EVENT_OBJECT_FOCUS name = Explorer (Ctrl+Shift+E) - 1 unsaved file role = pushButton state = [opaque, focused, focusable] miscData = hwnd=40D4A ;objectId=-4; childId=-26; threadId=4604; windowClass=Chrome_RenderWidgetHostHWND; 
```

When I continue tabbing around, it continues to send the focus events I'd expect.

This is the code I have in the app module to see what NVDA sees:

```python
class AppModule(appModuleHandler.AppModule):
    def event_gainFocus(self, obj, nextHandler):
        ui.message("focusing on")
        ui.message(obj.name)
        ui.message(str(obj.role))
        ui.message(obj.windowClassName)
```

I only hear NVDA announcing the Chrome_WidgetWin_1 window getting focus, but not the other events.

Any idea why NVDA might be doing this?

I also tried triggering the onFocus event on `obj = api.getDesktopObject().objectWithFocus()` which works to an extent. 
For e.g, if focus was previously in an edit field, I can still edit text fine, or use the arrow keys to move about in browse mode. However, enough things break due to the ignoring of focus events that restarting is still required often.

**Comment by jcsteh** [comment] 2018-05-14 02:49
Honestly, I don't know. You'd need to dig into the various places where NVDA could filter events and add some specific debug logging:

1. Raw win events are received in `IAccessibleHandler.winEventCallback`. You could log all EVENT_OBJECT_FOCUS events right near the top to make sure NVDA is getting them.
2. It could be rejected by `eventHandler.shouldAcceptEvent`, which is called by `IAccessibleHandler.pumpAll`. You could do logging at various stages (before shouldAcceptEvent, after it, at various points during it) to see where it gets dropped.
3. Failing that, other places in `IAccessibleHandler` where you might want to shove some debug logging include `processFocusWinEvent` and `processFocusNVDAEvent`. There might also be other places in `pumpAll` where a focus event could get rejected, but that's far less likely.

**Comment by Neurrone** [comment] 2018-05-14 06:06
@jcsteh thanks for the pointers. I guess there's no facility for logging these without actually modifying NVDA's source code?

**Comment by jcsteh** [comment] 2018-05-14 07:00
Not at present. It'd be nice to have, but it's difficult to do without
being ridiculously verbose, since you need to log the possibilities in so
many places.

**Comment by jcsteh** [comment] 2018-05-14 09:06
My first question is why this is the case. The fact that it isn't a descendant of the foreground is very odd. That rule is there to stop events from apps in the background from impacting performance. If it isn't a descendant of the foreground, what's the foreground? And why did it change?

Is this only for the events when you alt+tab back in, or is this for all focus events, even after you've alt+tabbed back there? I think the former from reading earlier comments, but am not entirely sure. If the latter, it's possible Windows just handles the foreground change a little too late.

As for hacking around this in an app mod, I think you might be able to use eventHandler.requestEvents to get all events for that process and class, if that's possible. Not in front of PC, and believe it or not, I can't remember what arguments that function takes even though I wrote it. :(

**Comment by Neurrone** [comment] 2018-05-14 09:44
@jcsteh it not only ignores the initial focus events when alt-tabbing back in, but all subsequent events as well. I think this might be related to the fact that the tree is annoyingly buggy - you can only walk to the root from the document in one direction, but you can't walk back down from the foreground window to the document, at least using object navigation. I've seen cases where objects show up in the console when they don't in object nav. Strangely, pressing alt+f to go to the file menu does have focus announced correctly and when escaping, it works properly again.

Another thing I'm not sure is related, I saw the following warning as Code was initializing, just after receiving multiple events from objects with Window class: `Chrome_RenderWidgetHostHWND`

```sh
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (16:05:42.387):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
```

The foreground window handle doesn't change before and after this starts happening.

Something else I just noticed. If you start the program, switch to other windows and switch back, this bug doesn't happen. If you move focus to the desktop (e.g windows+d), then switch back to VS Code (whether immediately or after going to other applications first), this bug occurs reliably for me.

**Comment by Neurrone** [comment] 2018-05-14 09:52
@jcsteh `eventHandler.requestEvents(eventName=None, processId=None, windowClassName=None)` lets you ask that a single event type get accepted, but right now, it will ignore all other events, not just the focus. Is there a way for me to specify that all events, except the ones that are normally filtered out like hide, show, reorder,  etc should be processed, without stating every event type?

**Comment by jcsteh** [comment] 2018-05-14 11:51
Does the document's window handle change?
Is the document's window even valid any more (winUser.isWindow)? I wonder
if the document's HWND gets changed but accessibility reports the wrong
window or something weird like that.
Does restarting NVDA fix this?

No, you can't do a catch all for eventHandler.requestEvents. It was never
really designed to be used in this hammer-like fashion. :)

**Comment by Neurrone** [comment] 2018-05-14 11:57
@jcsteh restarting NVDA doesn't help. By document if you mean the things that fire focus events, then I can take a look.

Hm, so that means short of an upstream fix (probably Electron or maybe Chromium?) the only way to fix this properly is to add another special cased exception to that function, if no additional APIs are used.

I guess callbacks that the app module would implement have been considered but weren't implemented due to e.g performance reasons? I hate changing it here though, since every event processed passes through here.

Is there a way for me to know the name of the .exe that generated the event to only apply this to Code itself? Don't want to accidentally break other Electron apps.

**Comment by Neurrone** [comment] 2018-05-14 12:09
@jcsteh winUser.isWindow still returns 1 even when it breaks.

I can add more logging to figure out what the ancestors of the document is when NVDA rejects its event. Are there convenience functions for doing this?

**Comment by Neurrone** [comment] 2018-05-14 13:11
@jcsteh winUser.isWindow still returns 1 even when it breaks.

The foreground window is set correctly for the events, but is not a parent of the offending object when it breaks.

```
Window class: Chrome_RenderWidgetHostHWND, eventName: gainFocus
window handle is descendant of foreground window: 1, root owner of window handle is descendant of foreground: 1, foreground window handle: 7210056, foreground class name: Chrome_WidgetWin_1
DEBUG - eventHandler.logRecursiveAncestors (21:03:07.984):
parents of this object:
window class: Chrome_WidgetWin_1, handle: 7210056, control ID: 0
window class: #32769, handle: 65552, control ID: 0
```

When it breaks:

```
Window class: Chrome_RenderWidgetHostHWND, eventName: gainFocus
window handle is descendant of foreground window: 0, root owner of window handle is descendant of foreground: 0, foreground window handle: 7210056, foreground class name: Chrome_WidgetWin_1
parents of this object:
window class: Chrome_WidgetWin_0, handle: 13894624, control ID: 0
window class: #32769, handle: 65552, control ID: 0
```

Have you seen this before in other apps? The spottify one doesn't seem to be as broken as this is.

**Comment by Neurrone** [comment] 2018-05-17 15:13
@jcsteh how does the detection of live regions work, in terms of the events that it uses to detect changes? NVDA is not reading new terminal text when this happens (I assume a live region is being used)

The workaround I used is to force NVDA to process almost all events even if it breaks.

```python
        eventsToRequest = { v for k, v in IAccessibleHandler.winEventIDsToNVDAEventNames.items() }
        # NVDA normally ignores these events in EventHandler.shouldAcceptEvent to prevent flooding
        eventsToRequest.remove("reorder")
        eventsToRequest.remove("show")
```   
     
The window class is still the same when using the terminal, so I'm not sure why this wouldn't work for it.

**Comment by jcsteh** [comment] 2018-05-17 21:06
The live region code is in-process C++ code. The foreground check is
hard-coded for that case, since we obviously can't make it query Python in
a performant way.

**Comment by Neurrone** [comment] 2018-05-18 02:57
@alexandrudima does Code do anything unusual when using Electron? Haven't seen this happening in other electron apps.

**Comment by alexandrudima** [comment] 2018-05-25 14:40
@Neurrone Not that I know of.

@bpasero are you aware of us doing anything funny when focus is gained via alt-tab ?

**Comment by Neurrone** [comment] 2018-05-25 14:46
I did a bit more digging, and this doesn't happen in the issue reporter window (help -> report issue), but the code for that window is likely a lot simpler.

**Comment by bpasero** [comment] 2018-05-25 16:04
@alexandrudima no, not to my knowledge. At least I do not think we have code that does something specific when window focus is gained that could have an impact on NVDA.

@Neurrone do you see this with other Electron applications (like Slack or Atom for example)?

**Comment by Neurrone** [comment] 2018-05-25 16:12
@bpasero just tried Atom, it doesn't happen at all there. I haven't tried others like Spotify, but have never heard of it happening there.

Perhaps it might not be code that does something on focus, but the way that the windows were initialized?

**Comment by bpasero** [comment] 2018-05-26 05:10
@Neurrone do you see the same in this other version of  VSCode that is using a different Electron version: https://az764295.vo.msecnd.net/exploration/163e64ca7bbd0a69c727cfd9f5610e7546207a71/VSCode-win32-x64-1.24.0-exploration.zip ?

**Comment by Neurrone** [comment] 2018-05-26 08:18
@bpasero still happens for me using this version.

**Comment by Neurrone** [comment] 2018-09-28 15:37
@alexandrudima when will Electron 3 be tested for insider builds? Wondering if the much more recent version of Chrome would have a fix for this.

**Comment by bpasero** [comment] 2018-09-28 16:30
@Neurrone 
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by Neurrone** [comment] 2018-09-29 09:49
@bpasero still happens for me :(. I can reproduce very easily.

**Comment by tyrylu** [comment] 2018-09-29 09:52
Same there, Win 10 64-bit, latest NVDA. The steps are maybe strange, but work and are as follows:
1. Open vs code
2. Open current firefox
3. Return to vs code, focus is lost
No idea what firefox (or all the mozilla apps) have to do with this and they're not alone in the camp of troublemakers, but they're the ones i identified with certainty.

**Comment by camlorn** [comment] 2018-09-29 18:09
I can duplicate this issue sporadically on my machine.  Maybe 1 in 20 or less.  I also use desktop Skype (also Electron), and haven't seen it there, but I don't use Skype heavily enough to guarantee that it's not triggering because all I use it for is phone calls.  That said, I do use the desktop Slack app (Chromium, not Electron) on a daily basis for at least the last 4 months and haven't seen something like this once ever.

I believe @Neurrone is getting it 100% of the time. I'm not sure what's different in our setups.  On mine, alt-tabbing between Firefox and VSCode was how I triggered it the first few times, but then I was able to see it without Firefox open, so I doubt it's that specific combination.

It'd be good to figure out if this is VSCode, Electron, something in the accessibility API itself, or something the screen readers all get wrong.

**Comment by Neurrone** [comment] 2018-12-06 05:00
Just saw anotherr report of this in the NVDA issue tracker.

I'm wondering if this can be looked at. Though only some users are affected, the program is virtually unuseable if you are.

**Comment by tayarndt** [comment] 2019-01-24 23:53
Hi, I am also having this issue.
Hi, I am Taylor Arndt and I am also having this issue.
Hardware setup is as follows
OS windows 10 latest version
NVDA version latest 
VS code version latest
I hope this helps, because I want to use this product more than I am able to now

**Comment by snufas** [comment] 2019-02-09 21:45
@bpasero  Are there any plans to look in to this problem? other then that i love vscode. i have a suspicion that it is dificult to track this issue to the root of the problem.

**Comment by snufas** [comment] 2019-02-09 22:04
@jcsteh  @Neurrone  interesting things hapining  when using f1 to search for settings nvda gets back the focus around the aplication accept the actual code editor window. test your selfs press f1 type something and then nvda starts to speek something up and you can use tab key to navigate around the aplication

**Comment by snufas** [comment] 2019-02-09 22:08
it is possable to reed the code  in browsing view how ever when ever you go back to focus view it is gon even if you go back to the brows view.

**Comment by snufas** [comment] 2019-02-09 22:34
hi I  know i posted to many comments how ever i found a working method how to get the focus back without exiting the aplication.
please make sure that you are on the vscode window 
instructions 
press ctrl pluss home and then press enter  
and it should go back to focus.

it should be done automatikly how ever it works. nvda is just not refocusing for some reason.

**Comment by Neurrone** [comment] 2019-02-10 00:22
I suspect this might be a problem with Electron; I think I might have seen this before in Cypress. I'll need to have it happen again to confirm.

**Comment by snufas** [comment] 2019-02-10 13:20
@Neurrone  there is defintlly wrong something with electron, how ever skype seams to work fine and it is writne in electron, so it leavs the problem in vscode rather then  eelectron. .

**Comment by bpasero** [comment] 2019-02-11 13:34
@snufas what are you doing in Skype that works but does not work in VSCode?

**Comment by tyrylu** [comment] 2019-02-11 15:23
You never get the lost focus issue in Skype 8.x, however Vs code is frequent enough to be sometimes annoying.

**Comment by Neurrone** [comment] 2019-02-11 15:38
@bpasero I don't think that Skype is doing anything special. It also never happens to me on Skype; so my guess is that Code is doing something that most other apps are not that is exposing this bug in Electron.

I'm not sure how to go about finding the root cause of the editor window not being a child of the foreground window; it might require help from someone on the Electron or Chromium teams.

**Comment by bpasero** [comment] 2019-02-11 15:47
> I'm not sure how to go about finding the root cause of the editor window not being a child of the foreground window

It is interesting that you mention this because I remember there where fixes around the window ordering on Windows to enable smooth scrolling for high precision touch devices. But Skype should by now be on the same version off Electron that we are in (Electron 3).

**Comment by snufas** [comment] 2019-02-11 17:13
@bpasero  The problem is that when nvda  loses focus on code editing window it does not reed any menus in vscode eather.  when i manage to get the focus back on code editor window it still does not read the menu items at a top.  other interesting point is that nvda does not lose the focus if you are just using alt tab how ever if you use windows d shortkut to go to the desktop it loses the focus immediately.  I say it is something wrong in screenreader mode in vscode, because without a screanreder mode enabled the code edditor  is not accessible at all.  I wonder how come everything works at a start and then  doesn’t  work after windows d shortkut is used. Something hapins in the bacground that  brakes something.   I really hope some developer of vscode could  fix this.

**Comment by bpasero** [comment] 2019-02-11 17:24
@snufas any difference if you configure `"window.titleBarStyle": "native"`?

**Comment by snufas** [comment] 2019-02-15 18:34
@bpasero  i am not sure what you meen by  "window.titleBarStyle": "native" i am asooming that is related to the vscode settings. i didin't played much with json settings in vscode.

**Comment by bpasero** [comment] 2019-02-18 08:04
Please do.

**Comment by Neurrone** [comment] 2019-05-18 14:54
Hope this can be prioritized for fixing due to its extremely high impact. Just heard from someone that was experiencing this issue again.

I've just created an add-on with the workaround I mentioned for this issue. Source code is at https://github.com/Neurrone/Nvda-Vs-Code-Focus-Workaround.

Until I can sort out why appveyor isn't generating github releases, use this [link to download the add-on](https://ci.appveyor.com/project/Neurrone/nvda-vs-code-focus-workaround/builds/24640369/artifacts).

**Comment by tayarndt** [comment] 2019-05-18 15:03
Thank you, thank you, thank you so much.

Sent from my iPhone

On May 18, 2019, at 10:56 AM, Dickson Tan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hope this can be prioritized for fixing due to its extremely high impact. Just heard from someone that was experiencing this issue again.

I've just created an add-on with the workaround I mentioned for this issue. Source code is at https://github.com/Neurrone/Nvda-Vs-Code-Focus-Workaround.

Until I can sort out why appveyor isn't generating github releases, use this link to download the add-on<https://ci.appveyor.com/project/Neurrone/nvda-vs-code-focus-workaround/builds/24640369/artifacts>.

**Comment by Neurrone** [comment] 2019-05-19 07:28
Trying to narrow down the cause of this issue.

After commenting out the `domContentLoaded` handler in `src\vs\workbench\electron-browser\main.ts` which creates the various parts of the UI by running `this.workbench.startup()`, this issue is still occuring. So at least none of the code that creates the various UI components is causing this, leaving code that runs before this point.

**Comment by isidorn** [comment] 2019-06-18 14:41
@bpasero @deepak1556 reading the above discussion I could not figure out if it is an electron issue
@bpasero might you have some ideas / pointers I could look into experiment with to try to get this fixed

**Comment by snufas** [comment] 2019-06-18 15:15
@Neurrone 
there is a strange thing though,  if nvda lost the focus i can go to the very end of the code and press enter and focus comes back  to the code window, but not the menu windows.   i wonder what hapins in  the vs code that gets back the focus partially  though.

**Comment by bpasero** [comment] 2019-06-18 15:45
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by snufas** [comment] 2019-06-18 15:58
I am getting this error when trying llatest nightly   build:

The setup files are corrupted. Please obtain a new copy of the
program.

**Comment by camlorn** [comment] 2019-06-18 17:39
Saw the notifications of this.  Figured it might be worth chiming in again to note that I have in the past seen this bug but have recently been doing development of my own Electron app across multiple machines and haven't seen it in my code.  Things I've used, usually in isolation at least for this stage of the project:

- React
- `aria-live`, `aria-posinset`, `aria-setsize`, `aria-expanded`, and the treeview roles in combination.
- Tabindex on weird elements (i.e. a p tag, which seemed like a good idea at the time).
- React, and whatever react does to the DOM.
- Some very heavy DOM manipulations as a stress test.

The only bug I found so far in the stack accessibility-wise is that you can't do `ole="treeview" without `tabindex` or something between NVDA and Chrome will eliminate the treeview from virtual navigation.  Which would seem to maybe be related, but I doubt it.

I'm doing some pretty complex custom controls basically, and given the fear around this issue popping up that I got from a lot of people, it so far hasn't.  SO I'm assuming that there's probably some very complicated sort of thing between all 3 pieces that's not playing nice--but between my own development and Slack working, Electron alone doesn't seem to be enough to trigger it.

As a last note, however, electron's accessibility tree seems slightly odd. You can go up to the ancestors with NVDA object nav, but going back down isn't symmetric.  So there is at least something odd, just perhaps not broken odd.

I'm developing some custom data editing stuff that should exercise most of the rest of Aria, etc, over the next few months. If I end up reproducing this I'll try to remember that this issue exists.

**Comment by bpasero** [comment] 2019-06-18 18:26
@snufas that is weird and should not happen, here is a direct link for just the archive without setup: https://az764295.vo.msecnd.net/insider/7f53e50cbf316dff94fbbe5406d8f352dac99a6b/VSCode-win32-x64-1.36.0-insider.zip

**Comment by snufas** [comment] 2019-06-18 20:21
@bpasero  the setup you provided worked,  saime problem though.  this needs to be investigated , because even blind people want to code and this issue persists  for a while now.   it would be nice if someone  who have contacts and influence would solve this problem with nvda developers.  people can comment as long as they want and nothing would hapin if there is nno action taken. I am not that advanced yet to do troubleshooting for this issue.

**Comment by bpasero** [comment] 2019-06-19 05:31
Understood, thanks for trying 👍

**Comment by snufas** [comment] 2019-06-19 21:04
for nvda screen reader   users i found a temporary  solution how to solve this problem. it is not related to the vs code it self so to avoid losing focus just move vscode to the separate desktop for example you can use desktop 3 for vscode and nothing else and when you want to work with other applications use ctrl+win+left arrow to switch  between desktops.  it is not perfect but better then nothing. i used to  lose focus when win+d command is used. but when the instance of vs code is in the  separate window it does not affect  vscode if it is located in other desktop.

**Comment by camlorn** [comment] 2019-06-23 20:25
@Neurrone 
I know you can reproduce this semi-reliably (or could). Can you confirm @snufas's solution? I could only ever reproduce it 1 in 20 or less and don't have the same machine configuration as last time I tried to do so.

I know I'm not actively working on this but "works reliably when switching virtual desktops" is this side of plausible so I  want to make sure someone who can repro sees it.

@snufas and anyone else blind who might find this:

notepad++ works reliably as long as you don't use the 64-bit version (there's an outstanding bug being fixed in the next NVDA release). You may be able to switch to that instead, plus a command line for building/running.

**Comment by snufas** [comment] 2019-06-23 21:28
@camlorn   
so are you suggesting to use notepad++   instead vs code???  that is not a very good idea it does not have saime features it is just bearly better then actual notepad, just with more functions.  virtual desktops works quite whell how ever the code terminal is not accesible at all.  i am using cmd as my terminal  instead powershell  but it opens in saime window,  as a usual terminal does not in the usual cmd window.   
@bpasero
i wonder can i make to open the code in the cmd console window   rather then the usual terminal window?  when i run the code? 
i have the folowing string in my json 
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"

**Comment by camlorn** [comment] 2019-06-24 17:39
I use Notepad++ professionally. I may try VSCode seriously one day but haven't so far had the need and people tend to stick religiously to their editors (plus, this issue does occur for me enough to be annoying, just not enough that I can quickly test).  Ymmv but there is at least a way to get your job done in a professional context if necessary, and that's worth having documented.

I don't want to take this issue any more off topic. If people need help I may be able to do so, but my time is limited; contact me privately but be aware that I may be slow to respond and may not be able to invest a lot of time in it.

**Comment by Neurrone** [comment] 2019-07-07 09:33
I'm no longer able to replicate this issue, I think something either in NVDA or Code changed within the last month or so that might have fixed it. I'm using the latest insider build.

**Comment by bpasero** [comment] 2019-07-07 17:50
@Neurrone cool, we updated Electron from 3 to 4, maybe that had an impact? Ok to close?

**Comment by snufas** [comment] 2019-07-08 00:49
yes the issue has been fixed.  thanks.

**Closed** 2019-07-08 06:40 UTC
Labels: accessibility, important, upstream

**Comment by isidorn** [comment] 2019-07-08 08:05
Awesome this got fixed 🎉
