### ISSUE TITLE
F10 and F11 not working when debugging and the focus is in internal terminal

### ISSUE THREAD

**Issue by gkusnir** [Microsoft/vscode#39672] opened 2017-12-05 12:35 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-101-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
vscode-markdownlint|Dav|0.12.0
beautify|Hoo|1.1.1
code-settings-sync|Sha|2.8.6
Bookmarks|ale|0.18.0
code-gnu-global|aus|0.2.2
line-counter|dol|0.3.0
svn-scm|joh|1.4.3
sublime-babel-vscode|jos|0.2.9
python|ms-|0.8.0
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
trailing-spaces|sha|0.2.11
vscode-hexdump|sle|1.6.0
pdf|tom|0.2.0
markdown-pdf|yza|0.1.7

(3 theme extensions excluded)

---

Steps to Reproduce:

1. load any python file into editor
2. set launch.json configuration "console": "integratedTerminal"
3. start debugging by pressing F5, the focus jumps to integrated terminal
4. now if you press F10 or F11 this is not interpreted as debug hotkey but rather as directly written to terminal producing the some escape sequences for those keys (^[[21~, ^[[23~) 
5. F5 and F6 with all modifiers work
6. when focus is switched back to the edited document the F10 and F11 keys work properly.

Reproduces without extensions: N/A (can't debug without the python extension)

**Comment by weinand** [comment] 2017-12-05 13:22
duplicate of #38023

**Closed by weinand** 2017-12-05 13:22 UTC
Labels: debug
