### ISSUE TITLE
Some emmet css abbreviations with ":n" value don't work as expected

### ISSUE THREAD

**Issue by danaigus** [microsoft/vscode#84608] opened 2019-11-12 16:59 UTC
Issue Type: <b>Bug</b>

Abbreviations like list:n, bdt:n, bgi:n, q:n are expanded into properties with value of "n" instead of "none", bg:n expands into "no-clip" instead of "none". I haven't tested all abbreviations, so it's likely that there are more cases like these.

VS Code version: Code - Insiders 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37, 2019-11-12T05:39:58.193Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.96GB (6.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
godot-tools|gee|0.3.7
beautify|Hoo|1.5.0
nim|kos|0.6.4
vscode-language-pack-pt-BR|MS-|1.40.2
cpptools|ms-|0.26.1
LiveServer|rit|5.6.1
vscode-icons|vsc|9.5.0

</details>

**Comment by devanshj** [comment] 2019-11-26 14:20
@octref It's not a bug, [rather a feature request](https://github.com/microsoft/vscode/issues/73627#issuecomment-558645664). Also you might want to label this as upstream.

**Comment by rzhao271** [comment] 2020-10-22 22:40
@sergeche should the default values all be `none` in these cases?

**Comment by sergeche** [comment] 2020-10-23 06:41
For `n` abbreviation value the output should be `none`

**Comment by rzhao271** [comment] 2021-01-06 20:27
Some of the abbreviations have been fixed, though I just did a test and realized `bg:n` still expands to `background: no-clip;` so I will have to configure the upstream snippets file some more.

**Comment by rzhao271** [comment] 2021-02-05 23:33
This is more of a note-to-self, but some of the properties are compound properties, which means `none` can possibly show up in those properties too.
For example `bg:n` implies `bgi:n` (https://stackoverflow.com/a/20784582).

Therefore, I'd have to adjust my CSS none property scraper https://github.com/rzhao271/css-none-scraper to check those cases.

Switching task to backlog as it's low-pri.

**Comment by rzhao271** [comment] 2021-03-29 23:49
The upstream issue has been fixed, so now what's left is to figure out why `vscode-emmet-helper` isn't handling the cases properly. There is most likely a configuration issue somewhere, e.g. see https://github.com/emmetio/emmet/commit/5f8782bc84cd28169b11eb05ea05291d735d8ae9#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012R329 for reference.

**Comment by kelleyneubauer** [comment] 2021-07-15 19:21
@TylerLeonhardt successfully reproduced and looking into this (AnitaB OSD)

**Comment by TylerLeonhardt** [comment] 2021-07-15 19:27
@kelleyneubauer it looks like this issue is marked as "upstream" which means that the problem is in https://github.com/emmetio/emmet/issues/628#issuecomment-810522830 as @rzhao271 mentioned. You _could_ try to investigate that, but we don't know too much about that source code so it could be harder than expected.

@rzhao271 correct me if I'm wrong

**Comment by kelleyneubauer** [comment] 2021-07-15 20:14
@TylerLeonhardt looking at the [prior fix](https://github.com/emmetio/emmet/commit/5f8782bc84cd28169b11eb05ea05291d735d8ae9#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012R329) before the issue was reopened, it seems that the solution might be just one line of code in test/stylesheet.ts: `equal(expand('bn:n'), 'background: none;');` ...this is my first time working with open source, not sure how or if I should proceed

**Comment by rzhao271** [comment] 2021-07-15 20:25
I haven't looked at this issue in a while, and would have to reconfirm the tests upstream fail.
If they do, then the issue is still in the upstream repo.

**Comment by theperfectpunk** [comment] 2023-02-25 14:06
@rzhao271 got the bg:n css abbreviation closed vide [PR](https://github.com/emmetio/emmet/pull/696)

**Comment by rzhao271** [comment] 2023-12-08 22:09
The original issue is fixed now.

**Closed by rzhao271** 2023-12-08 22:09 UTC
Labels: bug, help wanted, upstream, good first issue, emmet, upstream-issue-linked

**Comment by rzhao271** [comment] 2024-01-24 20:04
1. Paste the following in a CSS file
```css
.test {
	
}
```
2. Place the cursor between the braces and type bg:n
3. Emmet should suggest `background: none` instead of `background: no-clip;`
4. Accept the completion just to confirm it works, but delete it after
5. Repeat steps 2 to 4 with the abbreviation bdt:n, which should expand to `border-top: none;`
