### ISSUE TITLE
Datalist options in Webview Extension webview are showing up incorrectly

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode#180253] opened 2023-04-18 19:39 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
![image](https://user-images.githubusercontent.com/86264750/232885113-b1d72f52-060d-4564-82fa-34efe0d163fb.png)

Steps to Reproduce:

1. Clone the [vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples) repository, and navigate to the `webview-sample` directory. It has a simple webview titled `CatCoding`.
2. Modify `src/extension.ts` on line 187 to return the following value

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="container">
        <table>
            <tr>
                <th></th>
                <th>Key</th>
                <th>Value</th>
            </tr>
            <tr class="content-tr">
                <td></td>
                <td title="Testing">Testing</td>
                <td><datalist id="CHOICES_TEST">
                        <option value="OBJECT">
                        <option value="STATIC">
                    </datalist><input id="TEST" value="OBJECT" type="text" list="CHOICES_TEST"></td>
            </tr>
        </table>
    </div>
</body>

</html>
```

3. Then, run the extension, run the command `Cat coding: start cat coding session` to open the view
4. Open the dropdown in the `Value` column.

Expected: 
The dropdown values appear directly under, for example, see the following screenshot:
![image](https://user-images.githubusercontent.com/86264750/232886340-ea1ce799-171b-4423-96b0-627dab41cb2b.png)

Actual:
![image](https://user-images.githubusercontent.com/86264750/232887086-979ff593-cb68-4760-9aff-eb9b89a81870.png)
![image](https://user-images.githubusercontent.com/86264750/232887143-3a00b7ed-761e-4fcc-b437-c15cd4c73457.png)

It seems like VSCode is forgetting to account for / add the margin of where the webview starts for some styling for `datalist` option elements. 

Additionally, it seems that navigating the datalist options with downward keypresses don't navigate through the options. Thanks!

**Comment by mjbvz** [comment] 2023-04-18 21:18
Duplicate of #129999

**Closed by mjbvz** 2023-04-18 21:18 UTC
Labels: *duplicate
