### ISSUE TITLE
Insider using different color profile than Stable

### ISSUE THREAD

**Issue by Kosai106** [Microsoft/vscode#52057] opened 2018-06-15 15:18 UTC
- VSCode Version: 1.25.0-insider
- OS Version: macOS High Sierra 10.13.5

Colours appear muted in the Insider build when compared to Stable.

For example, my current theme of choice, `One Dark Pro`, has a red colour of `#F06372`, but in the Insider build, this colour is `#E06D75`. The same is happening to all other colours too of course.

#### Example:
<img width="1680" alt="screen shot 2018-06-15 at 16 32 08" src="https://user-images.githubusercontent.com/6379824/41475478-31df7686-70bf-11e8-9ac5-4a67902f9c8d.png">

_(Insider build on the left, Stable build on the right.)_

----

I've tried the fix suggested here, but no luck. https://github.com/Microsoft/vscode/issues/51791#issuecomment-397527146

**Comment by RMacfarlane** [comment] 2018-06-15 16:45
Upstream electron bug: https://github.com/electron/electron/issues/10732

**Comment by bpasero** [comment] 2018-06-15 16:50
Duplicate of https://github.com/Microsoft/vscode/issues/51791

**Closed by bpasero** 2018-06-15 16:50 UTC
Labels: electron, electron-update, upstream
