### ISSUE TITLE
Problem w/ Commit & Push to a cloned GitHub repositpry

### ISSUE THREAD

**Issue by ojuarapaul** [microsoft/vscode#168262] opened 2022-12-07 03:01 UTC
Type: <b>Bug</b>

I keep getting an error messages when I try to "commit & push"or "commit & sync" to cloned repositories on GitHub. The repositories cloning process works normally. As I'm used to do this all the time, and it suddenly stopped worked (as soon as I clone the repository, it works, and after some time I get the errors), I believe it could be a bug after the last VS Code update. I'm using a MacBook Pro  2017 Dual Core Intel I5 8GB Ram MacOS Ventura 13.0.1

The last error message is as follows:
fatal: Need to specify how to reconcile divergent branches.
2022-12-06 18:49:55.460 [info] > git remote --verbose [26ms]
2022-12-06 18:49:55.462 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [29ms]
2022-12-06 18:49:55.463 [info] > git status -z -uall [27ms]
2022-12-06 18:49:55.467 [info] > git config --get commit.template [25ms]
2022-12-06 18:49:55.475 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [29ms]
2022-12-06 18:49:55.559 [info] > git ls-files --stage -- /Users/pauloaraujo/Dropbox/00-IT_2022-2023/Git_Cloned/myportfolio/.git/COMMIT_EDITMSG [25ms]
2022-12-06 18:49:55.580 [info] > git show --textconv :.git/COMMIT_EDITMSG [15ms]

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id aad956e2-9744-4496-857d-f20c7a719ff8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|0.7.9
python-preview|don|0.0.4
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.40
jupyter|ms-|2022.9.1303220346
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
LiveServer|rit|5.7.9
ayu|tea|1.0.5
vscode-icons|vsc|12.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by lszomoru** [comment] 2022-12-07 08:32
@ojuarapaul, couple of questions which would hopefully help us track down the root cause:
* Are you able to reproduce the same error if you just invoke the "Git: Push" or "Git: Sync" commands?
* Are you able to reproduce the same error with multiple repositories or it is specific to one repository?
* Are you seeing the same error if you run `git pull` and `git push` from a terminal window?

Sharing the complete contents of the git output window would also help. Thank you!

**Comment by ojuarapaul** [comment] 2022-12-08 21:56
Hi Ladislau,

The issue seems to be related to the HEAD branch (which I haven’t created
nor exists in my repository). Can you tell me what it is?

I was using both [commit & push] and [commit & sync] from the dropdown
menu, and both give me the same results. I did not use the terminal
commands, but if the issue shows up again, I'll give it a try.

For some reason, it seems to be working fine right now. I'll keep trying,
and if the issue appears again I'll let you know (I've just updated VSCode,
so it might have gone now).


Thanks for your help,

Paulo ***@***.***)

Em qua., 7 de dez. de 2022 às 00:32, Ladislau Szomoru <
***@***.***> escreveu:

**Comment by lszomoru** [comment] 2022-12-09 10:27
@ojuarapaul, thanks for the update. I will close the issue now but please feel free to reopen it in case the issue reoccurs.

**Closed by lszomoru** 2022-12-09 10:27 UTC
Labels: info-needed, git
