### ISSUE TITLE
Accessibility: Intellisense/autocomplete alerts contains superfluous words when using a screenreader

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#59571] opened 2018-09-27 18:31 UTC
Reported by Rob Gallo:

The text of intellisense/autocomplete needs to be much shorter, perhaps containing only the suggestion and insertion.
 
In a typescript file in VS Code, using jaws as my screen reader, when I type the letter ‘c’, I hear “’console’ suggestion”. And when I then press enter, I hear, “accepting ‘console’ did insert the following text.”
 
Every word in both strings is superfluous except for the two instances of ‘console’. The meaning would be perfectly clear if ‘console’ were the only word spoken. In fact, as it stands, the verbosity of these strings is so long that it actually slows me down.
 
I understand the urge to provide context. However, the distraction and speed bump caused by the repetition of these strings vastly outweighs the benefits of the extra context over time.
 
I have used intellisense for many years in VisualStudio where it only reads the names of the symbols. I probably know as many blind developers as anyone out there. And I can tell you that this will drive us all crazy.

**Comment by jrieken** [comment] 2019-03-05 09:19
closing this as dupe of #65499

**Closed** 2019-03-05 09:19 UTC
Labels: *duplicate, accessibility, bug, suggest, ux
