### ISSUE TITLE
The explorer panel renders contents only in half of its available space

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#92440] opened 2020-03-11 07:46 UTC
Issue Type: <b>Bug</b>

Install latest insider. check the explorer pane contents

VS Code version: Code - Insiders 1.44.0-insider (eb4ebee6a3310df8ff5f36f78f209c2658cfcdfc, 2020-03-11T05:31:25.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 19, 34|
|Memory (System)|16.00GB (1.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sanket-bhalerao** [comment] 2020-03-11 09:01
possible duplicate of #92430

**Closed** 2020-03-11 10:42 UTC
Labels: *duplicate
