### ISSUE TITLE
[Debugging] RunInTerminal doesn't use the specified integrated terminal from workspace settings

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#108559] opened 2020-10-13 03:02 UTC
If my default integrated terminal in Visual Studio Code is git-bash then an error happens. I found out that a workaround is to change the default integrated terminal to cmd or powershell. I tried changing the current terminal in my workspace settings to cmd.exe, but when I hit F5 to start debugging it incorrectly uses git-bash.

If I change the global settings files, then the debugger works as expected... but I don't want to change it globally as I work with git-bash in most of my other projects.

If I press the + button to create a new terminal, it creates a new cmd terminal as expected, using the workspace settings file definition for the default terminal.

##### Environment
- Operating System: Windows 10
- JDK version: 14
- Visual Studio Code version: 1.48.2
- Java extension version: 0.10.0
- Java Debugger extension version: 0.28.0

##### Steps To Reproduce
1. Set git-bash as default integrated terminal in your global settings.
2. Set cmd as default integrated terminal in your workspace settings.
3. Press F5 to launch and start debugging

##### Current Result

It starts debugger using git-bash (which does not work for me):

![image](https://user-images.githubusercontent.com/1653710/92139170-c19ff200-ede5-11ea-99e7-015eae56994d.png)

##### Expected Result

Start debugging in a cmd.exe terminal (which works nicely):

![image](https://user-images.githubusercontent.com/1653710/92139371-09267e00-ede6-11ea-8133-85f0a611713c.png)

(to get this screenshot I had to set the global default terminal)

_Originally posted by @masbicudo in https://github.com/microsoft/vscode-java-debug/issues/877#issue-692107303_

**Comment by connor4312** [comment] 2020-11-13 00:15
This looks like more a bug in the terminal API side of things. I can repro this as well using `vscode.window.createTerminal` from an extension (which is the API that debug also uses internally).

**Comment by connor4312** [comment] 2020-11-13 00:31
Nevermind, I missed the permission banner in the corner. I'm able to repro this -- except it appears to ignore all user settings, not just workspace settings. Could be related https://github.com/microsoft/vscode/issues/109111

**Comment by weinand** [comment] 2020-11-17 18:07
I don't quite understand the issue...

But may be the following FYIs help:  
- #109111 and #81345 are fixed in the next Insiders
- VS Code has specific settings ("automationShell") for configuring the integrated terminal that is used for debug and tasks: e.g. "terminal.integrated.automationShell.windows".

**Comment by connor4312** [comment] 2020-11-17 18:17
I poked at it a little bit. I thought it wasn't pulling the workspace, and pinged Daniel about it

https://github.com/microsoft/vscode/blob/63e42d414bf0867ba57a7c8f843744933087d911/src/vs/workbench/api/node/extHostTerminalService.ts#L33

He said:

> It should be getting set still: https://github.com/microsoft/vscode/blob/af6843bacfd7da2f8f4485e8f992e6d69661158b/src/vs/workbench/api/node/extHostTerminalService.ts#L238-L240
> Not sure if the todo is valid anymore but I think it was around setting the initial state and maybe pulling it from main instead of pushing

I haven't looked at it again since

**Comment by connor4312** [comment] 2021-03-31 21:50
This seems to work now after clicking the "allow workspace shell" prompt.

**Comment by alexr00** [comment] 2021-04-29 14:12
@connor4312 It looks like default shell settings are no longer respected at all in workspace settings. I've verified that the original behavior in the bug occurs still. Seems like this is probably by design.

**Comment by connor4312** [comment] 2021-04-29 15:59
Yea it looks like the new profiles are only applied on a per-user basis. So this would now be as designed.

![](https://memes.peet.io/img/21-04-7485be7c-c07f-4866-adf1-2950283a6a74.png)

**Closed by connor4312** 2021-04-29 15:59 UTC
Labels: bug, confirmed, debug, verification-found
