### ISSUE TITLE
Closing HTML tags with hyphens are not deindented properly

### ISSUE THREAD

**Issue by mdickin** [Microsoft/vscode#6811] opened 2016-05-24 14:56 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Open an HTML file
2. Type "someTag" and hit Tab, Enter
3. Closing tag is placed on newline at same indentation level as opening tag
4. On a new line, type "some-tag" and hit Tab, Enter
5. Closing tag is indented from opening tag

![hyphenated tags](https://cloud.githubusercontent.com/assets/16612667/15508609/c48257e0-2195-11e6-9376-7e71915b2b8a.gif)

**Comment by aeschli** [comment] 2016-05-25 07:08
duplicate of #6371

**Closed by aeschli** 2016-05-25 07:08 UTC
