### ISSUE TITLE
"electron_node server.js" doesn't quit after closing VS Code

### ISSUE THREAD

**Issue by kwmlodozeniec** [microsoft/vscode#88854] opened 2020-01-17 15:07 UTC
Issue Type: <b>Bug</b>

What I am eperiencing quite often is that Code Helper (Renderer) process doesn't stop after I quit VS Code on MacOS Catalina. Also, majority of the time that process takes 100% of the CPU and just starts cooking my MacBook and I have to go into system monitor and kill it manually. I have seen simillar issues being raised surrounding high CPU usage but I couldn't find one which replicated my experience exactly.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (2.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-search|bur|1.0.1
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
vscode-pull-request-github|Git|0.14.0
rest-client|hum|0.23.0
kite|kit|0.102.0
vs-external-tools|lih|1.3.0
git-graph|mhu|1.21.0
theme-monokai-pro-vscode|mon|1.1.14
vscode-docker|ms-|0.9.0
python|ms-|2020.1.58038
Go|ms-|0.12.0
debugger-for-chrome|msj|4.12.5
autodocstring|njp|0.4.0
vscode-sort-json|ric|1.18.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
code-spell-checker|str|1.7.20
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2020-01-19 15:21
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by jarvisluong** [comment] 2020-01-19 16:28
I'm having the same issue, and even more weird that my mac automatically restart (I guess the memory usage was too much). After the restart, VSCode isn't running but I'm seeing lots of Code Helper (Renderer) and Code Helper (GPU) running.

**Comment by bpasero** [comment] 2020-01-19 18:20
See https://github.com/microsoft/vscode/issues/88854#issuecomment-576015286

**Comment by kwmlodozeniec** [comment] 2020-01-21 09:46
I'm trying to catch this again but at the moment I am only getting the first part of this symptom, i.e. the Code Helper (Renderer) process staying behind after I quit VS Code.

**Comment by bpasero** [comment] 2020-01-21 09:57
Ok

**Comment by kwmlodozeniec** [comment] 2020-01-21 14:45
Okay I caught the 100% CPU usage, and here is the output from `code --status` command
```
Version:          Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS Version:       Darwin x64 19.2.0
CPUs:             Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)
Memory (System):  16.00GB (1.86GB free)
Load (avg):       5, 4, 3
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    98	 85180	code main
    0	    66	 85181	   gpu-process
    0	    98	 85222	   shared-process
    0	   295	 97868	   window (framework/general/test_facility.py — firmware-systemtest)
    0	   147	 97871	     extensionHost
   54	    66	 97885	       electron_node server.js
    0	    33	 97888	       electron_node server.js
    0	   311	 98104	       /Users/krzysztof/.vscode/extensions/ms-python.python-2020.1.58038/languageServer.0.5.30/Microsoft.Python.LanguageServer
    0	    33	 97872	     watcherService

Workspace Stats:
|  Window (framework/general/test_facility.py — firmware-systemtest)
|    Folder (firmware-systemtest): 7725 files
|      File types: pyc(2965) py(2579) txt(170) yml(145) rsp(112) json(108)
|                  pyi(91) so(73) pem(54) h(40)
|      Conf files: makefile(2) settings.json(1)
```

**Comment by kwmlodozeniec** [comment] 2020-01-21 15:35
this is just a snapshot, so the CPU is not 100%, but the average I see in system monitor is in the high 95%

**Comment by kwmlodozeniec** [comment] 2020-01-21 16:13
I quit VS Code and tried running the command again, but it obviously doesn't work as VS Code needs to be running, but the Code Helper (Renderer) process has been left behind and it's still chewing through CPU
```
[main 2020-01-21T16:12:25.731Z] Warning: The --status argument can only be used if Code is already running. Please run it again after Code has started.
```

**Comment by bpasero** [comment] 2020-01-21 16:37
@kwmlodozeniec looking at the processes it seems to be caused by the Python extension, would you agree?

`/Users/krzysztof/.vscode/extensions/ms-python.python-2020.1.58038/languageServer.0.5.30/Microsoft.Python.LanguageServer`

**Comment by kwmlodozeniec** [comment] 2020-01-21 16:39
I don't agree, I would say it's the `54	    66	 97885	       electron_node server.js`

**Comment by kwmlodozeniec** [comment] 2020-01-21 16:42
Also, since the process lingers behind after quitting it means it's not the extension by the server itself

**Comment by bpasero** [comment] 2020-01-21 16:58
I am not 100% sure who owns that server, moving to @dbaeumer and @aesch

**Comment by dbaeumer** [comment] 2020-01-22 09:50
This is none of our servers since we gave them all descriptive names. 

@kwmlodozeniec in which context are you seeing this. And when it happens could you run the command `Developer: Show running extensions` so that we know which of your installed extensions are activated.

**Comment by kwmlodozeniec** [comment] 2020-01-22 10:16
I work on various projects throughout the day, sometimes I might have two or three open in separate windows. At some point, I notice CPU usage is high even though I might just have VS Code open but not being used. I quit VS Code but often a single Code Helper (Renderer) process is left behind and it keeps chewing through the CPU until I kill it through the system monitor. This is what I get when I run the command you asked for during my normal development work.
![image](https://user-images.githubusercontent.com/1453791/72885625-319eb380-3d00-11ea-8efe-338eb03735f3.png)

**Comment by kwmlodozeniec** [comment] 2020-01-23 16:47
It happened again, I noticed high CPU usage by Code Helper (Renderer) process. I quit VS Code but the offending process stayed behind. I dumped this from the system monitor utility for this process
```cwd
/Users/krzysztof/GitHub/firmware-systemtest
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
txt
/Library/Preferences/Logging/.plist-cache.pixFUHGc
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
txt
/usr/share/icu/icudt64l.dat
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.bin
txt
/usr/lib/dyld
0
->(none)
1
->(none)
2
->(none)
3
->(none)
4
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
5
count=1, state=0x8
6
->0xef02a7a16b56b9ee
7
->0x857cc6697bcbbb8b
8
->0x96b55c3dc7a31108
9
->0x8ad2d837d0527e65
10
->0xd7d4ba6204e8052b
11
->0x511556e4ba366e98
12
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.bin
13
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
14
count=0, state=0x12
15
count=0, state=0
16
->0x5879e33f4e07dbc7
17
->0xfe1486199542bfc1
18
->0x8103deb89271467c
19
->0x941c4da4190af550
20
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.bin
21
->(none)
22
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
23
count=0, state=0xa
24
->0xa77dfc1e9080a50d
25
->0x627bf32e70c9af02
26
->0xf33c5873ed7efcc2
27
/Applications/Visual Studio Code.app/Contents/Resources/electron.asar
28
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar
29
->0xddf1d14475002a21
30
/dev/urandom
31
/dev/null
40
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar
41
[ctl com.apple.netsrc id 7 unit 31]
45
/Users/krzysztof/GitHub/firmware-systemtest/.git/refs/remotes/origin/dev-kwm
```

**Comment by dbaeumer** [comment] 2020-01-24 08:36
Thanks for all the information. Unfortunately it doesn't help with identifying the extension that starts server.js. What I would need it the full path of the server.js file. @weinand do you know which OS tools to use on the Mac to get this information for a process:

![capture](https://user-images.githubusercontent.com/1931590/73055420-0b5a4e80-3e8d-11ea-855d-bf36298f5912.png)

**Comment by kwmlodozeniec** [comment] 2020-01-27 16:40
Any ideas about this issue?

**Comment by dbaeumer** [comment] 2020-01-28 08:27
@kwmlodozeniec but the server.js doesn't come from VS Code itself. It must come from an extension. In VS Code we gave the servers all descriptive names (e.g eslintServer.js). When you see this again can you provide more details about the process (e.g. its full command line) so that we can identify the extension.

**Comment by kwmlodozeniec** [comment] 2020-01-28 08:47
How can I get a full command line of some child process from the editor/extension? I have no idea how to do this on macos

**Comment by weinand** [comment] 2020-01-28 09:31
On macOS you can see the full command line with `ps -ax`. If you have difficulties finding the correct process I recommend to install the `htop` tool (e.g. via `brew`).

**Closed** 2020-02-04 09:39 UTC
Labels: freeze-slow-crash, needs more info

**Comment by kwmlodozeniec** [comment] 2020-02-17 09:28
Just for the sake of closure on this issue, the offending process is actually one of the extensions, in this case, a spell check.

`12:32.19 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/krzysztof/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.22/server/server.js --node-ipc --clientProcessId=85640`

**Comment by dbaeumer** [comment] 2020-02-17 09:45
@kwmlodozeniec thanks.

**Comment by easterjd** [comment] 2020-03-05 18:46
Not sure if it's a faux pas since this is closed, but I've been experiencing the exact same issue. I've made sure to uninstall and reinstall VSCode using the scripts provided on their website. My new install has no extensions but is still opening these "electron_node server.js" processes that are crashing my new MacBook. Really weirds me out since I have a 6-core i7 processor and 16gb of memory.

**Comment by dbaeumer** [comment] 2020-03-09 09:04
@easterjd can you follow the steps from https://github.com/microsoft/vscode/issues/88854#issuecomment-579156921 to give us the full command line of the node process causing this.
