### ISSUE TITLE
Task spinner doesn't go away when task is terminated

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31788] opened 2017-07-31 22:28 UTC
Using tasks 2.0

- Start a long-running task that **isn't** marked as a "background" task
- Task spinner starts spinning in the status bar
- Terminate the task before it completes
- Spinner is still spinning until the window reloads

Regression from 1.14

**Comment by Lixire** [comment] 2017-08-01 00:18
Does the task show up in the terminate task list still? Or is everything correct except for the status bar. Could you run other tasks after?

**Comment by roblourens** [comment] 2017-08-01 00:26
Yeah, it shows up in the list of tasks to terminate, so I guess vscode thinks it was not terminated.

**Comment by Lixire** [comment] 2017-08-01 00:30
I believe that https://github.com/Microsoft/vscode/commit/91985475706caa3b1692c532dc116995cf804199 fixes this issue

**Comment by roblourens** [comment] 2017-08-01 00:30
Excellent. I'll try it tomorrow.

**Comment by dbaeumer** [comment] 2017-08-03 14:05
I can't reproduce this. Closing.

**Closed by dbaeumer** 2017-08-03 14:05 UTC
Labels: bug, tasks
