### ISSUE TITLE
Auto-fill timeline to visible area

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#95019] opened 2020-04-11 19:28 UTC
By default the timeline view should load the first page of all available items based on its height (it would be ideal if we can show a scroll bar to indicate the amount of items available). And automatically load more items as user scroll down. This way we can get rid of the "Load more" button.

**Comment by eamodio** [comment] 2020-04-13 18:24
I'm going to implement the first request -- set the page size based on the visible viewport. But the auto-load on scroll is a duplicate of #94258. So follow that issue for that request.

**Closed** 2020-04-13 18:26 UTC
Labels: timeline
