### ISSUE TITLE
Integrated terminal - undock into separate window 

### ISSUE THREAD

**Issue by georgebatalinski** [microsoft/vscode#111300] opened 2020-11-25 13:00 UTC
Having integrated terminal, ability to undock 
Use case: running tests on a dual screen setup, where Screen 1 - is used for writing code, Screen 2 - is used for running tests 

![vscode](https://ketu9-yahoo.tinytake.com/media/ea143d?filename=1606309031743_TinyTake_25-11-2020-07-54-23_1606309031.png)

similar to Google Chrome 

![chrome](https://ketu9-yahoo.tinytake.com/media/ea1465?filename=1606309133932_TinyTake_25-11-2020-07-58-45.png)

**Comment by meganrogge** [comment] 2020-11-25 16:38
Duplicate of #34442

**Closed by meganrogge** 2020-11-25 16:38 UTC
