### ISSUE TITLE
Do Not Show for overwriting extension message

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#62316] opened 2018-10-31 18:37 UTC
![image](https://user-images.githubusercontent.com/4033249/47810635-04cc3e00-dd01-11e8-952d-de53c4320f70.png)

I'm in a debug session, so I'm perfectly aware that the extension I'm developing might be overwriting an existing one. I hope I can turn this message off.

**Comment by sandy081** [comment] 2018-11-15 11:48
@alexandrudima This request looks sense to me. I am planning to add `Do not show again` action to the message and the user can opt in not to show this again.

What's your opinion?

**Comment by siegebell** [comment] 2019-03-16 12:12
I'm debugging several extensions at once, so I use `--extensions-dir my-exts/` and `--extensionDevelopmentPath=my-exts/foo`. Because `foo` is in `my-exts/`, I get the message *"[my-exts/foo]: Overwriting extension my-exts/foo with my-exts/foo."* This is silly :/

**Comment by alefragnani** [comment] 2019-04-10 04:21
I'm not sure which issue will remain, but there is an older issue, which is still opened (#26276).

**Comment by connorshea** [comment] 2019-05-15 18:16
When 'Do Not Show Message' is used, should the message be dismissed just for that specific extension or for all extensions forever?

**Comment by sandy081** [comment] 2019-05-15 18:41
It will be for all extensions

**Comment by alexandrudima** [comment] 2019-07-22 10:51
Duplicate of #26276

**Closed by alexandrudima** 2019-07-22 10:51 UTC
Labels: extensions, feature-request
