### ISSUE TITLE
Got a 'bug' in language configuration.

### ISSUE THREAD

**Issue by shockw4ver** [Microsoft/vscode#29002] opened 2017-06-19 06:10 UTC
**VSCode Version:** 1.13.1;
**Platform:** win10;

I tried to set the language of vscode as Chinese, so I opened the language configuration and modified the value from 'en' to 'zh'. Then I reloaded the vscode, it didn't work, even can't open the app window, but created a progress in system.
Absolutely I didn't wrong thing in set, **Chinese setting should corresponding to 'zh-cn', I did 'zh'**, so the app ran with error.  
Then I created a issue here and got a way to resolve from @kongyuan that just delete the folder 'Code/User', finally I found the problem at 'locale' file there. Three days to resolve this! What a fool am I...
But I think a invalid language value setting should not cause a breakdown, may giving some tips to tell users how to set the value correctly is better.
So I suggest if some improvement should be made there. 
**I love vscode!** 
Hope it get better and better!

**Comment by dbaeumer** [comment] 2017-06-21 08:49
I can't reproduce this. Any additional info:

![cast](https://user-images.githubusercontent.com/1931590/27375371-3e31088e-566f-11e7-839f-134240baab24.gif)

**Comment by shockw4ver** [comment] 2017-06-21 09:52
I met it when I closed the application and load agian.
But now I can't reproduce this, either.....
Others also have met this problem, and I resolved this from their experienment, may it just will happen in after a update?



发自我的小米手机
在 Dirk Bäumer <notifications@github.com>，2017年6月21日 下午4:50写道：

I can't reproduce this. Any additional info:

[cast]<https://user-images.githubusercontent.com/1931590/27375371-3e31088e-566f-11e7-839f-134240baab24.gif>

**Comment by dbaeumer** [comment] 2017-06-21 12:59
Sorry to hear. But without additional information this is very hard to fix. I will close the issue for now. If zou encounter it again please ping and I will help to diagnose this.

**Closed by dbaeumer** 2017-06-21 12:59 UTC
Labels: i18n, needs more info, new release

**Comment by shockw4ver** [comment] 2017-06-22 02:02
Okay，thanks for your checking~

发件人: Dirk Bäumer<mailto:notifications@github.com>
发送时间: 2017年6月21日 21:01
收件人: Microsoft/vscode<mailto:vscode@noreply.github.com>
抄送: Sameul Zhang<mailto:asambojur@live.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [Microsoft/vscode] Got a 'bug' in language configuration. (#29002)


Sorry to hear. But without additional information this is very hard to fix. I will close the issue for now. If zou encounter it again please ping and I will help to diagnose this.
