### ISSUE TITLE
Korean characters beginning with 가 with a non-empty final consonant display incorrectly

### ISSUE THREAD

**Issue by mcognetta** [microsoft/vscode#89853] opened 2020-02-02 00:59 UTC
- VSCode Version: 1.41.1
- OS Version: Ubuntu 19.04

I was also able to reproduce on VSCode 1.38.1 on a Linux desktop. Note that these had different Korean IMEs (I could reproduce it using ibus-hangul, fctix-hangul, and nabi).

A number of Korean characters beginning with 가 (ㄱ + ㅏ) that include a final consonant display incorrectly. No other initial consonant/vowel pairs seem to be affected.

Below are a few examples (not exhaustive but enough to get the pattern), as well as some notes.

| Character | How it displays | Note
|----|------|----|
| 각  |   가ㄱ   |
|  감  | 가ㅁ     |
| 갖   |   가ㅉ   | Final consonant ㅈ turns into its double consonant form ㅉ.
| 갓   |   가ㅆ   | Final consonant ㅅ turns into its double consonant form ㅆ.
| 강   |   가ㅈ   | Final consonant ㅇ turns into ㅈ.
| 값   |   가ㅅ   | To type this one you type ㄱ + ㅏ + ㅂ + ㅅ, it appears as 가ㅂ until you type the ㅅ. Then it turns into 가ㅅ.
| 갔  |  가ㅇ  |  To type this one you type ㄱ + ㅏ + shift-ㅅ.

My hunch is that this is an off by one error in the [unicode codepoint computation](https://en.wikipedia.org/wiki/Korean_language_and_computers#Hangul_Syllables_block). For the cases of 갖, 갓, 강, and 갔 above, the codepoint for ㅈ is the codepoint for ㅇ + 1. Similarly, ㅈ + 1 = ㅉ,  ㅅ + 1 = ㅆ, and ㅆ + 1 = ㅇ.

One other potentially useful piece of information is that ㄱ is the alphabetically first consonant and ㅏ is the alphabetically first vowel.

Steps to Reproduce:

1. Open a plain text file (utf-8 encoding)
2. Type the Korean characters 각 (or 간, 갇, ...). This incorrectly displays as 가ㄱ (가ㄴ, 가ㄷ, ...).

Does this issue occur when all extensions are disabled?: Yes

**Comment by hatsunearu** [comment] 2020-02-02 01:12
Hi, a few more observations:

- I can reproduce on my desktop (VSC 1.40.0, Kernel is 5.3.0-26)
- My laptop running VS Code 1.36.1 and Ubuntu 19.04 (OP also runs 19.04) does **NOT** have this issue. Possible regression?
- A better way to test this is to make a file. Here's an example:

```
echo \xea\xb0\x81\xea\xb0\x91\xea\xb0\x95\xea\xb0\x96\xea\xb0\x92\xea\xb0\x91\xea\xb0\x93 | xxd -r -p | tee "test"
```

If your terminal works correctly, you should see `각갑강갖값갑갓`. Try opening this in VS Code.

**Comment by hatsunearu** [comment] 2020-02-02 01:16
Accidentally finished my message.

If you open that file in VS Code, you will see `가ㄱ가ㅂ가ㅈ가ㅉ가ㅅ가ㅂ가ㅆ` and interestingly if you press backspace with the cursor at the end it should delete `가ㅆ` as if it was a single glyph (correct behavior). 

Furthermore if you (attempt to) type `각갑강갖값갑갓` and save it it actually saves the correct binary data. This might be some sort of display problem.

As OP said, this issue seems to only happen with 가+consonant, but not with anything else.

**Comment by mcognetta** [comment] 2020-02-02 01:18
Thanks to @hatsunearu for helping test this. His example is roughly how I first found this (opening a text file with incorrectly rendered Korean, not typing it).

One more case against it being an IME issue:

1. Open a text file
2. Type 강 (which will display as 가ㅈ)
3. control-f search for 강 (interestingly, 강 displays correctly in this text box)

The correct word is highlighted, implying vscode knows that that syllable block is supposed to be 강 and it is just incorrectly rendered.

![vscode_korean](https://user-images.githubusercontent.com/6856636/73601447-af3f9c00-4516-11ea-9b73-b5a099fdb1b4.png)

**Comment by hatsunearu** [comment] 2020-02-02 01:41
Ok hold up, there is something interesting going on... I just updated my laptop with VS Code 1.36.1 to 1.14.1 and I still don't have this issue. Let me get a fresh install on a VM and see if I see this issue.

**Comment by hatsunearu** [comment] 2020-02-02 05:18
https://github.com/microsoft/terminal/issues/4226 Possibly related?

**Comment by alexdima** [comment] 2020-02-03 12:07
@hatsunearu @mcognetta Does this issue reproduce with any font family?

**Comment by hatsunearu** [comment] 2020-02-03 15:50
Doesn't seem to happen when the Font Family is removed, or an invalid font is put down (such as `monospace` or `asdfasdfasdf` for me). Happens when a valid font is used (`'Monaco``, `'Droid Sans Mono'`, etc)

**Comment by hatsunearu** [comment] 2020-02-03 16:21
I've tested way more than what is reasonable to try and guess what the pattern is, but it looks like *when `'Droid Sans Mono'` is anywhere within the Font Family string, it will cause the repro.*

What repros:

* `'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` 

* `'Monaco', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` (I have Monaco installed)

* `'Ubuntu', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` 

* `'Ubuntu Mono', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` 

* `'NotAValidFont', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` 

* `'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback', 'NotAValidFont'` 

* `'Droid Sans Mono', 'Ubuntu', 'monospace', monospace, 'Droid Sans Fallback'`

* `'Droid Sans Mono', 'monospace', 'Ubuntu', monospace, 'Droid Sans Fallback'`

* `'Droid Sans Mono', 'monospace', monospace, 'Ubuntu', 'Droid Sans Fallback'`

* `'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback', 'Ubuntu'`

* `'Droid Sans Mono', 'monospace', 'Droid Sans Fallback'`

* `'Droid Sans Mono', 'Droid Sans Fallback'`

* `'Droid Sans Mono', monospace, 'Droid Sans Fallback'`

* `'Droid Sans Fallback'`

* `'Droid Sans Fallback', 'Monaco'`

* `'Monaco', 'Droid Sans Fallback'`



What doesn't repro

* `'Droid Sans Mono'`(I don't have this font installed)

* `'monospace'`

* `monospace`

* `'Ubuntu'`

* `'Monaco'`

* `'Droid Sans Mono', 'monospace', 'Monaco'`

* `'Droid Sans Mono', 'monospace'`

* `'Droid Sans Mono', 'monospace', monospace`

**Comment by alexdima** [comment] 2020-02-04 08:46
@hatsunearu Thank you for your thorough testing, this might be something that is defined by the font. VS Code is built with Electron, which is built with Chromium. For the rendering of the text in the code editor, we delegate the font rendering to Chromium.

I have created a test page at https://jsfiddle.net/6dsh2bva/ . Can you please open that in Chromium and in Firefox on your machine and check if there are any differences. Especially if there are rendering differences, I would like to ask you that you please create an issue against Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to it here. The Chromium developers can then provide further guidance.

Thank you!

**Comment by hatsunearu** [comment] 2020-02-06 03:35
Sorry for the late reply. Looks like this is an upstream chromium issue.

**Comment by alexdima** [comment] 2020-02-06 11:07
@hatsunearu Thank you for following through. Did you find an existing issue in the Chromium issue tracker or did you create a new one? It would be good to link to it here and then close this issue as reported upstream.

**Comment by hatsunearu** [comment] 2020-02-07 04:44
https://bugs.chromium.org/p/chromium/issues/detail?id=1049912 Posted upstream

**Closed** 2020-02-10 12:57 UTC
Labels: linux, needs more info, upstream, upstream-issue-linked
