### ISSUE TITLE
[PHP] Syntax highlighting broken by part of my code.

### ISSUE THREAD

**Issue by realee94** [Microsoft/vscode#11057] opened 2016-08-27 23:17 UTC
- VSCode Version: 1.5.0-insider (had this issue in older builds as well)
- OS Version: Windows 10 64bit (Anniversary Update)

**I tried with different color themes as well. Same issue.**

First of all, I know that having such long php files is not a good thing. BUT the syntax highlighting breaks in my php file after a certain section (which has a lot of quotation marks and apostrophes).

My file is 389 lines but it breaks at line 303. I don't want to copy-paste the whole code, but I can copy the section which seems to break my syntax highlighting.

```php
<div class="row">
	<div class="col-md-6" style="padding-right: 5px">
		<input name="value<?=($plan['col'])?>[]" value="<?=$data[$plan['col']]['value']?>" type="text" class="form-control">
	</div>
	<div class="col-md-6" style="padding-left: 0px">
		<select name="unit<?=($plan['col'])?>[]" class="form-control">
			<option value="-1"<?=($data[$plan['col']]['unit'] == -1 ? ' selected' : '')?>>-</option>
			<option value="1"<?=($data[$plan['col']]['unit'] == 1 ? ' selected' : '')?>>Ft</option>
			<option value="2"<?=($data[$plan['col']]['unit'] == 2 ? ' selected' : '')?>>%</option>
			<option value="3"<?=($data[$plan['col']]['unit'] == 3 ? ' selected' : '')?>>kbit/s**</option>
			<option value="4"<?=($data[$plan['col']]['unit'] == 4 ? ' selected' : '')?>>perc</option>
			<option value="5"<?=($data[$plan['col']]['unit'] == 5 ? ' selected' : '')?>>MB</option>
			<option value="6"<?=($data[$plan['col']]['unit'] == 6 ? ' selected' : '')?>>GB</option>
			<option value="7"<?=($data[$plan['col']]['unit'] == 7 ? ' selected' : '')?>>db</option>
		</select>
	</div>
</div>
```

Copying this section in itself doesn't break syntax highlighting, but if I take this part out, the syntax starts working again. I tried to add extra code to stretch the file out to 390+ lines again after taking out this part of the code and it still worked. I didn't find any issues like this (tried with and without extensions as well).

Here is where it breaks:
![issue1](https://cloud.githubusercontent.com/assets/6963476/18030617/e2b03152-6cbc-11e6-82a3-24453ced78ad.jpg)

I take out the "bad" part:
![issue2](https://cloud.githubusercontent.com/assets/6963476/18030618/e2b20982-6cbc-11e6-9c6a-6b37c11da0d6.jpg)

I add the "bad" part at the end of the file and yet it breaks the syntax highlight again:
![issue3](https://cloud.githubusercontent.com/assets/6963476/18030620/e2b67166-6cbc-11e6-949b-e33e3c84db1a.jpg)

I completely take out the "bad" part (end of my file):
![issue4](https://cloud.githubusercontent.com/assets/6963476/18030619/e2b591ec-6cbc-11e6-9974-99cc2fbab7e0.jpg)

Leaving the "bad" code where it was, this is the end of my file (file in original state):
![issue5](https://cloud.githubusercontent.com/assets/6963476/18030629/26a2463e-6cbd-11e6-85b4-6f82d7f18945.jpg)

**Comment by faustinoaq** [comment] 2016-08-27 23:22
related? #11043

**Comment by realee94** [comment] 2016-08-27 23:28
Definitely looks familiar.

**Comment by mrmlnc** [comment] 2016-08-27 23:32
Most likely all of these issues relate to https://github.com/Microsoft/vscode/issues/9937#issuecomment-242934557, where there are answers from developers.

**Comment by sandy081** [comment] 2016-08-29 07:00
@aeschli Could be related to #9937, assigning to you initially so that you can take a look from php side and dup it if it is.

**Comment by aeschli** [comment] 2016-08-30 07:00
The reason for the colorization stop is that the colorizer grammar has too any states on the scope stack, same as in #9937.
The reason for this can be a bug in the grammar, but just a very nested example and our limit is too small.
I wasn't able to reproduce it with the provided snippet. @realee94 If you have a link (e.g. in a GitHub repo) that has the whole file, then I gladly investigate if it is a bug in the PHP grammar.
Otherwise, we plan to increase the limit, so hopefully this won't be seen anymore so easily.

**Closed by aeschli** 2016-08-30 07:00 UTC
Labels: php
