### ISSUE TITLE
Unable to open 'Release Notes: 1.10.0-insider':

### ISSUE THREAD

**Issue by FjVillar** [Microsoft/vscode#20077] opened 2017-02-06 20:29 UTC
- VSCode Version: Code - Insiders 1.10.0-insider (723b20093d2f525e84cdf94a52f7695d1d539273, 2017-02-03T07:11:59.289Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|Angular2|johnpapa|1.0.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|typescript-hero|rbbit|0.12.0|

---

Steps to Reproduce:

1. Just launched VS Code Client.
2. Got the new version available popUp at the top of the screen. I clicked on Read Release Notes
3. This message appeared: "Unable to open 'Release Notes: 1.10.0-insider': Cannot read property 'replace' of null"

I can read the releases notes by navigating through the menus anyway. ¿Are you aware of this little bug?

**Comment by joaomoreno** [comment] 2017-02-07 09:26
Duplicate of #20029

**Comment by FjVillar** [comment] 2017-02-11 12:13
I don't know if this issue is duplicated because I get the error from the popup bar it apeears at the top of the screen. Not from the Help Menu as the other Issue. Just to say. Probably is the same bug.

Thanks!

**Comment by joaomoreno** [comment] 2017-02-13 07:26
Got it!!!

**Comment by joaomoreno** [comment] 2017-02-22 15:50
I can't repro this, even when clicking in the _popup bar it apeears at the top of the screen_.

**Closed by joaomoreno** 2017-02-22 15:50 UTC
Labels: bug
