### ISSUE TITLE
Should provide a specific codeActionContext for code actions issued by textDocument changes

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#105407] opened 2020-08-26 09:50 UTC
When i'm editing the document endlessly, VS Code client will keep sending code action request to the language server.

Below is a sample code action request during editing document.
```
[Trace - 4:42:50 PM] Sending request 'textDocument/codeAction - (2186)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/myName/Work/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MoveHandler.java"
    },
    "range": {
        "start": {
            "line": 643,
            "character": 13
        },
        "end": {
            "line": 643,
            "character": 13
        }
    },
    "context": {
        "diagnostics": []
    }
}
```

 But in the code action context part, it doesn't provide the `only` field in the `context`. From the [codeActionContext](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) definition in the LSP wiki, the `only` field is used to tell the language server the code action kinds the client is requesting. The question is **"if it's empty, what kind of code actions are expected here by VS Code client?"**

Currently Java language server will return `quickfix`, `refactor`, `source` actions if the `only` field is empty. But it seems VS Code only respects the `quickfix` and `refactor` to the light bulb, and ignore source actions. If this is right, can VS Code change `only` field to `[quickfix, refactor]`, that will avoid some unnecessary calculation at the language server side.

From my profiling on the language server, calculating the source action takes 60% time cost of total codeActionHandler in some bad case.
![image](https://user-images.githubusercontent.com/14052197/91282600-20e57d00-e7bc-11ea-9190-c1c5d030e5d4.png)

**Comment by dbaeumer** [comment] 2020-08-27 07:44
Assigning to @mjbvz since this is more a question regarding code action in VS Code and not LSP. To my knowledge the context is undefined to be backwards compatible to the version when no context existed.

**Comment by mjbvz** [comment] 2020-08-27 18:57
This is the expected behavior.

When the cursor moves (or a document is edited) we want to show code actions at the new location however there is not a specific type of code action we are interested in. Your extension should determine what kind of code actions to return in this case. JS/TS for example returns both quick fixes and some refactorings, but not a complete list of all possible refactorings

**Closed by mjbvz** 2020-08-27 18:57 UTC

**Comment by mjbvz** [comment] 2020-08-27 18:58
BTW you should not return source actions in this case. Source actions are treated by the VS Code UI as document level actions so they will not show up in the normal lightbulb menu. Returning them won't hurt but it's a waste of resources to compute them

**Comment by testforstephen** [comment] 2020-08-28 01:25
Thanks for the clarification.
