### ISSUE TITLE
"Update imports" prompt is slow to appear

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62402] opened 2018-11-01 17:47 UTC
- Open vscode workspace
- In file explorer, move `src/vs/platform/search/common/replace.ts` from 'common' to the sibling 'test'
- Wait 5s or more
- "Would you like to update imports?" prompt finally appears

**Comment by roblourens** [comment] 2018-11-01 17:49
- Move it a second time before the prompt appears
- The prompt appears once
- Click "no"
- The prompt appears again immediately

**Comment by mjbvz** [comment] 2019-01-02 23:17
Duplicate of #65112. Root cause is upstream: https://github.com/Microsoft/TypeScript/issues/29031

**Closed by mjbvz** 2019-01-02 23:17 UTC
