### ISSUE TITLE
Look into adding `Mosh` as an option for Remote Development extension

### ISSUE THREAD

**Issue by dwdozier** [microsoft/vscode#75100] opened 2019-06-07 21:23 UTC
Not sure if `Mosh` https://mosh.org/ is a viable option to be able to select as a 'way' to SSH and work remotely.

It's pretty useful in terms of closing up for the day and coming right back to where I left off or keep a running process going (even inside a screen) and not lose connectivity per se.

I haven't done a deep dive yet, but really digging the concept of the Remote Development extension, client-side caching seems like that would be a good idea too, especially for poor connectivity or offline work.

Thanks, Dave

**Comment by egamma** [comment] 2019-06-09 12:24
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/334

**Closed by egamma** 2019-06-09 12:24 UTC
Labels: *duplicate
