### ISSUE TITLE
Integrated terminal shows no command prompt and no cursor

### ISSUE THREAD

**Issue by micage2** [Microsoft/vscode#35842] opened 2017-10-08 19:18 UTC
Integrated terminal shows no command prompt and no cursor.
Code Version 1.17.0, OS X 10.11.6

I think the last update ruined it.

**Comment by timothyvictor** [comment] 2017-10-10 18:42
Have same issue on OS X 10.11.6 since updating to 1.17.0 - other machine that runs Sierra does not have this issue with 1.17.0

**Comment by Tyriar** [comment] 2017-10-10 19:53
@micage2 @timothyvictor sorry to hear that, I have some questions 😃

- Does resizing the terminal bring it back?
- Does this only happen when extensions launch terminals?
- Are there any errors in the devtools console? (Help > Toggle Developer Tools)

Might be https://github.com/Microsoft/vscode/issues/35728

**Comment by quanterion** [comment] 2017-10-12 07:06
I have the same problem. On VS start I have Powershell terminal that works good. Then I start task with multiple dependencies then only terminal of the last dependent task display correct text, others are empty. Resizing terminal bring it back and everything works ok. There are no errors in devtools.

**Comment by Tyriar** [comment] 2017-10-12 15:23
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/34554

It would be great if you could verify the issue is fixed on *tomorrows* [insiders build](https://code.visualstudio.com/insiders/).

**Closed by Tyriar** 2017-10-12 15:23 UTC
Labels: integrated-terminal, needs more info

**Comment by timothyvictor** [comment] 2017-10-23 09:57
Hello @Tyriar 
Sorry, only just back on the machine on which I've experienced the issue. 

- Does resizing the terminal bring it back? **No**
- Does this only happen when extensions launch terminals? **No**
- Are there any errors in the devtools console? (Help > Toggle Developer Tools) **No**

> It would be great if you could verify the issue is fixed on tomorrows insiders build.
**It is.** 

Thank you. I love vscode. Just saying. 

Tim.
