### ISSUE TITLE
Format Code and IntelliSense not working at all

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#3652] opened 2016-03-02 22:48 UTC
For some reason Format Code and IntelliSense stopped working in my project (IntelliSense justs shows Loading... F12 or go to definition never resolves, etc...). I'm guessing that something about my configuration makes the language service crash or something.
I don't currently have any extensions installed.
It happens both in the stable and latest alpha version.
I don't see any errors on the output console.

Any idea how to give you more information so you can diagnose and fix this issue?

**Comment by aeschli** [comment] 2016-03-03 10:56
@digeff What language are you working with? JavaScript, C#...

**Comment by digeff** [comment] 2016-03-03 14:17
Typescript. This is the project https://github.com/Microsoft/vscode-react-native although I wasn't on master when it happened.

**Comment by enzoaeneas** [comment] 2016-03-15 11:30
I am getting the same behavior, except that my project is JavaScript (nodejs and browser). I have eslint, jshint and beautify plugins loaded as well.

**Comment by c4milo** [comment] 2016-06-09 15:34
I'm working on Go and having the same issue.

**Comment by dbaeumer** [comment] 2016-06-10 09:01
@c4milo this issue is about Intellisense in TypeScript. Please file the issue against https://github.com/microsoft/vscode-go which host the go extension for VS Code.

**Comment by timfish** [comment] 2016-07-01 11:11
I'm seeing this in 1.2.1 on Windows 10 with JavaScript. JSON intellisense in my project appears to be working fine.

**Comment by dbaeumer** [comment] 2016-11-15 21:25
Tried to reproduce using https://github.com/Microsoft/vscode-react-native but wasn't able to do so. I will close the issue. @digeff  Please ping if this is still an issue you are seeing.

**Closed by dbaeumer** 2016-11-15 21:25 UTC
Labels: bug, typescript

**Comment by tavotavotavo** [comment] 2017-01-20 14:19
having the same problem with javascript, format and intellisense not working for a node project.

as a workaround i installed beautify for formatting, have to find some other plugin for intellisense. it's a pitty that they closed the issue.

**Comment by dbaeumer** [comment] 2017-01-23 08:53
@tavotavotavo can you provide a GitHub repository that demonstrates the problem. I tried with the one from @digeff and without steps or a test case it is hard to fix.

**Comment by slender9168** [comment] 2017-05-13 12:01
I've had the same issue & managed to find the cause in this issue link:
https://github.com/Microsoft/vscode/issues/26594
