### ISSUE TITLE
New Code Action control breaks original flow

### ISSUE THREAD

**Issue by alber70g** [microsoft/vscode#161404] opened 2022-09-21 14:15 UTC
Does this issue occur when all extensions are disabled?: **Yes**

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:07:15.900Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

## Context

The ["New Code Action control"](https://code.visualstudio.com/updates/v1_71#_new-code-action-control) as presented in the release notes of August 2022, breaks the flow of using it.

Steps to Reproduce:

1. Hit cmd + . on something you want to get an "Action" on. (e.g. `console.log("this string that I want to convert to template literal"`)
2. Press `r`

Expected: jumps to `Replace with template string`
Actual: nothing happens

2. press `tab` (or anything that is bound to "selectNextSuggestion")

Expected: selects next option in the list
Actual: nothing happens

This is what I use so that I don't have to move to the arrow keys with my right hand
```json
  {
    "key": "tab",
    "command": "selectNextSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
  },
```

Yes, there are new options available (see below), but the starting character selection should probably (?) still work in the new situation.

```
selectNextCodeAction
selectPrevCodeAction
acceptSelectedCodeAction
```

**Comment by mjbvz** [comment] 2022-09-21 17:40
Duplicate of #157719

**Closed by mjbvz** 2022-09-21 17:40 UTC
