### ISSUE TITLE
Add default choices in the integrated terminal dropdown menu.

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#9353] opened 2016-07-15 15:53 UTC
It can be a pain trying to help someone properly setup a 64 bit cmd or PowerShell terminal. Since Code uses %comspec% as it's default terminal, this breaks a lot of things on 64 bit machines. 

To make dealing with this easier, I think there should be a drop down similar to the terminal selection one where we can configure multiple terminals.  Then Code can add some of the native ones as default values and allow users to add new ones.

Example on windows 64bit:
```json
"terminal.integrated.shell.windows.options": { 
    "PowerShell (x64)": "C:\\WINDOWS\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
    "PowerShell (x86)": "C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "Cmd (x64)": "C:\\WINDOWS\\sysnative\\cmd.exe",
    "Cmd (x86)": "C:\\WINDOWS\\system32\\cmd.exe"
}
```

Example on windows 32bit:
```json
"terminal.integrated.shell.windows.options": { 
    "PowerShell": "C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "Cmd": "C:\\WINDOWS\\system32\\cmd.exe"
}
```

You could also do something to add Shell Args in there as well, which I am really hoping Windows gets some day.

**Comment by Tyriar** [comment] 2016-07-15 18:03
Since it's just a one-time configuration I wouldn't want to add chrome to the UI for this, especially since settings aren't applied anywhere on the UI. It would go against the minimalistic/lightweight value of VS Code. The documentation was just updated yesterday which recommends sysnative for cmd, powershell and bash. https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

Closing this as designed, let's continue the conversation over in #7095

**Closed by Tyriar** 2016-07-15 18:03 UTC

**Comment by gerane** [comment] 2016-07-17 16:53
Is there any plans for supporting multiple types of terminals? Say I have 1 terminal for  CMD, another for PS and maybe a 3rd custom that are all open and can be switched between.

**Comment by Tyriar** [comment] 2016-07-17 19:52
No plans, you can probably accomplish this by running powershell from within cmd and vice versa.

**Comment by Tyriar** [comment] 2017-08-21 18:42
Support for multiple terminal configs s deferred to this extension for now https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
