### ISSUE TITLE
Feature Request: Save language set on hot exit

### ISSUE THREAD

**Issue by phamquocthang** [Microsoft/vscode#17769] opened 2016-12-23 10:47 UTC
Currently when closing unsaved tabs with hot exit, the programming language applied for those tabs will be gone and code will display with no color. Please add the feature to keep language set on hot exit

**Comment by mrmlnc** [comment] 2016-12-23 10:52
Please use search before submitting a new issue.

Duplicate of #17115, #17724, #17681, #17319, #17402, #17520, #17702 & e.t.c.

**Comment by egamma** [comment] 2016-12-23 15:15
@mrmlnc thanks! Closing.

**Closed by egamma** 2016-12-23 15:15 UTC
Labels: duplicate
