### ISSUE TITLE
Tab key no longer works in HTML or CSS or LESS files

### ISSUE THREAD

**Issue by ayyash** [Microsoft/vscode#20179] opened 2017-02-08 08:27 UTC
- VSCode Version: Code - Insiders 1.10.0-insider (eff9148502fd3edf42573beb16006bee533c3cf9, 2017-02-08T07:10:29.700Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:
Disabled all extensions
---

Steps to Reproduce:

1. Tab key in HTML and CSS/LESS files no longer work

**Comment by zech** [comment] 2017-02-08 08:46
For me it doesn't work in JavaScript files as well.

**Comment by crewone** [comment] 2017-02-08 09:10
Doesn't work in PHP either.

**Comment by markheron91** [comment] 2017-02-08 10:01
I'm having this problem as well - seems to work in Typescript files though

**Comment by janhancic** [comment] 2017-02-08 11:14
I have the same problem. I did manage to find a workaround. I copied (without changing anything) the keybinding setting for `tab` from the defaults to my personal keybindings setting file.

So just add this:

```
{
  "key": "tab",
  "command": "tab",
  "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus"
},
```

To your `keybindings.json` file and tab should start working again.

**Comment by markheron91** [comment] 2017-02-08 11:26
@janhancic works for me, thanks!

**Comment by ciwyaitd** [comment] 2017-02-08 14:03
@janhancic thanks,but emmet is not working yet.

**Comment by edmundtfy** [comment] 2017-02-09 03:11
+1, solved by solution by @janhancic 
Version 1.10.0-insider (1.10.0-insider)

**Comment by ayyash** [comment] 2017-02-09 08:27
I would like to add another issue, not sure it is related but I guess it is, when I F2 a file name to rename it, the left-right arrow keys, don't respond.

**Comment by crewone** [comment] 2017-02-09 08:33
Duplicate of #20209

**Comment by ayyash** [comment] 2017-02-09 09:06
I think this came first :) but hey, as long as it gets a solution who cares which came first

**Comment by ramya-rao-a** [comment] 2017-02-09 09:53
@20209 happened to get triaged first, so will close this on as duplicate of #20209.

We have found the root cause, the fix will be out soon.

As a workaround set `"emmet.triggerExpansionOnTab": false` in your settings.

This should enable TAB again. Once the next update for insiders rolls out, you no longer need to have this setting.

**Closed by ramya-rao-a** 2017-02-09 09:53 UTC

**Comment by ramya-rao-a** [comment] 2017-02-09 17:08
The fix is in the latest insiders.
