### ISSUE TITLE
When using Profiles, a lot of Extensions is not loaded

### ISSUE THREAD

**Issue by bwa** [microsoft/vscode#180676] opened 2023-04-24 09:31 UTC
Type: <b>Bug</b>

I have utilized the Profiles feature. So I have a lot of different profiles. as a example some profiles are using Java and some are not.  So with Spring Boot.

Very often, when I open a project it seems like extension, disabled by some (other?) profiles, are lost when project are loaded.

Typical message is : 

Cannot activate the 'Spring Boot Dashboard' extension because it depends on the 'Spring Boot Tools' extension, which is not installed. Would you like to install the extension and reload the window?

I also get sometimes a message that the extensions could not be installed because of the extentions folder is not there or is in use

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.71GB (38.35GB free)|
|Process Argv|--crash-reporter-id 20917981-573b-440b-b671-e861aa1e63be|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal-commands|adr|1.0.5
terminal-loader|ari|1.2.1
gitlens|eam|13.5.0
rest-client|hum|0.25.1
git-graph|mhu|1.30.0
jupyter-keymap|ms-|1.1.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.0.0
fabric8-analytics|red|0.3.6
java|red|1.17.0
vscode-yaml|red|1.12.2
vscode-boot-dev-pack|vmw|0.2.1
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.10
vscode-java-test|vsc|0.38.2
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.41.0
vscode-spring-boot-dashboard|vsc|0.12.0
vscode-spring-initializr|vsc|0.11.2
terminal-all-in-one|yas|1.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30713944

```

</details>

**Comment by sandy081** [comment] 2023-04-24 14:41
Can you please share your profiles and provide us the steps to reproduce? This will be much helpful to diagnose and fix the issue.

**Comment by bwa** [comment] 2023-04-24 19:44
@sandy081 That's one of the problem. It's not so easy to reproduce. It's just happening, kinda out of nowhere.

But I see a pattern. I do work with very many projects at same time. Have a powerful machine with a lot of RAM, so it's not holding be back. I do see that when I open projects concurrently with the same extension disabled in one profile and enabled in other, this tend to occur.

So I basically wonder if there is something in the design getting in trouble if one loaded profile is disabling one extension and an another is enabling it ?

My profiles as a zip is uploaded.


[profiles.zip](https://github.com/microsoft/vscode/files/11314074/profiles.zip)

**Comment by sandy081** [comment] 2023-04-25 16:23
Thanks

**Comment by bwa** [comment] 2023-04-25 17:49
was able to recreate

![image](https://user-images.githubusercontent.com/170977/234360208-b2712296-ca72-4a93-8fc7-6b8b9fe40d7f.png)

**Comment by bwa** [comment] 2023-04-25 17:53
steps to reproduce:

1. open all 10 projects in 10 different windows
2. just randomly set a different profile on each project, should be ish 2 projects per profile
3. close ALL windows with File, Exit
4. open VSCode so all 10 projects are loaded
5. repeat step 3 and 4 a couple of times, then is braks down as shown in the picture

[vscode-issue.zip](https://github.com/microsoft/vscode/files/11325429/vscode-issue.zip)

**Comment by bwa** [comment] 2023-05-09 09:37
Any progress here ?

Still getting different issues regarding to extensions loaded or not. Still no pattern other than it seems to happen when new projects are loaded, and the current profile seems to not having the extension.

Looks like extension are removed from VSCode instead of beeing disabled for that profile

![image](https://user-images.githubusercontent.com/170977/237056394-d1436b77-7118-4084-9471-26730358ea89.png)

**Comment by bwa** [comment] 2023-05-10 05:07
@sandy081 
Here's another example. I had several windows active with different profiles loaded , and exited all with File, Exit.

On next start of VSCode all was opened again, but fail completely handling extenstion.

VSCode simply breaks down. This is not happening every time, so a reproducable case is not very easy to provide.

It seems like eiter extensions are not there anymore, or they are falsely detected as not installed.

It's obviously an issue for VSCode to handle different profiles where one has an extention active and an another profile has same extension disabled

![image](https://github.com/microsoft/vscode/assets/170977/c06ce871-2259-4639-b966-02b18082283b)

**Comment by bwa** [comment] 2023-06-08 05:14
@sandy081 I little experience from the last week with lot of issues of this kind.

All issues seems to be connected to my current setup where I work with probably 4-6 projects (in 4-6 different windows) where there is a mix of 2-3 profiles, where some profiles has a extension active and another does not use ( but still holding folders?) the same extension.

Normally I close all these windows with File, Exit. That saves the state, so when I open VSCode next morning, all 4-6 windows loads at once, and the 'conflict' or race condition is on....

**Comment by bwa** [comment] 2023-06-20 05:07
@sandy081  Here's another example that shows it's a serious issue with how VSCode is managing the extensions

I saw that there was a update on Spring Boot Extension, and clicked on update. But it went wrong, obviously the reason is that some other VSCode instance also running is holding that folder.

So the way of work here, must be rethougth. VSCode simply does not work when using several instances/windows

![image](https://github.com/microsoft/vscode/assets/170977/6fe90ce2-7ecb-472a-825e-ea1c2c7733fc)

**Comment by sandy081** [comment] 2023-06-20 09:14
@bwa Thanks for lot for sharing info. I believe the root cause for these issues is https://github.com/microsoft/vscode/issues/180482 - I fixed this yesterday and the fix is available in insiders. It would be great if you can try our insider and see if the bug is fixed for you - https://code.visualstudio.com/insiders/

**Comment by bwa** [comment] 2023-06-20 10:40
@sandy081  Nice, I assume insiders can coexist with VSCode GA ?

**Comment by sandy081** [comment] 2023-06-20 12:01
Yes

**Comment by bwa** [comment] 2023-06-21 05:05
Ok, I have switched to Insiders version 1.80 and will report back my findings

**Comment by bwa** [comment] 2023-06-23 13:46
So far not seeing the reported issue with Insiders. Vacation up next, så further reporting is after summer

**Comment by sandy081** [comment] 2023-06-27 17:38
Closing this because @bwa is not seeing this issue with insiders.

**Closed by sandy081** 2023-06-27 17:38 UTC
Labels: bug, user-profiles
