### ISSUE TITLE
Cannot switch away from webview when  retainContextWhenHidden is true

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44679] opened 2018-02-27 23:36 UTC
Testing #44466

```ts
import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

export function activate(context: vscode.ExtensionContext) {
  const htmlPath = path.resolve(context.extensionPath, 'media/index.html');

  vscode.commands.registerCommand('extension.sayHello', () => {
    const wv = vscode.window.createWebview(vscode.Uri.parse(`foo:${new Date().toTimeString()}`), vscode.ViewColumn.One, {
      enableScripts: true,
      retainContextWhenHidden: true
    });
    wv.html = fs.readFileSync(htmlPath, 'utf-8');
    wv.title = 'hello'
  });
}
```
![error](https://user-images.githubusercontent.com/4033249/36761443-ea6ee5e2-1bd3-11e8-8e79-2b225b2cd77b.gif)

**Comment by mjbvz** [comment] 2018-02-27 23:43
Thanks. Duplicate of #44589

**Closed by mjbvz** 2018-02-27 23:43 UTC
Labels: bug, webview
