### ISSUE TITLE
Object spread operator on new line breaks formatting

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/vscode#5128] opened 2016-04-10 10:26 UTC
- VSCode Version: Latest insiders
- OS Version: Win10

see gif
i have settings javascript.validation.enable set to false

![record](http://g.recordit.co/uUlER7N6Jr.gif)

**Comment by egamma** [comment] 2016-04-11 07:37
duplicate of #4889

**Closed by egamma** 2016-04-11 07:37 UTC
