### ISSUE TITLE
Intellisense not working for react-native

### ISSUE THREAD

**Issue by DonkeyTronKilla** [Microsoft/vscode#34342] opened 2017-09-14 03:11 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
gitignore|cod|0.5.0
vscode-eslint|dba|1.3.1
githistory|don|0.2.3
python|don|0.7.0
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.23.1
auto-close-tag|for|0.5.0
vscode-nuget-package-manager|jmr|1.1.4
mssql|ms-|1.1.0
vscode-mongodb|ms-|0.0.1
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
debugger-for-chrome|msj|3.3.0
color-highlight|nau|2.3.0
vscode-icons|rob|7.12.0
vscode-react-native|vsm|0.4.1

---

Steps to Reproduce:

. Create react native app:

<img width="355" alt="screen shot 2017-09-13 at 3 45 05 am" src="https://user-images.githubusercontent.com/6686474/30373481-42357254-9836-11e7-9c27-8ba2d8a1875c.png">

2. Making sure VSCode is not already open, launch from new app:

<img width="274" alt="screen shot 2017-09-13 at 3 52 25 am" src="https://user-images.githubusercontent.com/6686474/30373699-0bf1ae3c-9837-11e7-9ec7-8de7d5016654.png">

3. No react native intellisense:

<img width="701" alt="screen shot 2017-09-13 at 8 09 14 pm" src="https://user-images.githubusercontent.com/6686474/30410371-7f8a3714-98bf-11e7-9a1d-1898aaaf12b2.png">

<img width="634" alt="screen shot 2017-09-13 at 8 10 00 pm" src="https://user-images.githubusercontent.com/6686474/30410381-901be5aa-98bf-11e7-8f31-a62fa2799a98.png">

4. However intellisense for react itself works:

<img width="906" alt="screen shot 2017-09-13 at 8 07 47 pm" src="https://user-images.githubusercontent.com/6686474/30410330-4386372c-98bf-11e7-9155-68387a5b2be2.png">

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-09-14 23:45
Hm, I'm unable to reproduce this:

![screen shot 2017-09-14 at 4 44 25 pm](https://user-images.githubusercontent.com/12821956/30460484-0461d6f2-996c-11e7-9781-453e120327e2.png)

If you run `go to definition` on `Linking`, does it open a `d.t.s` file? If you add `/// @ts-check` to the very top of the file to enable type checking, do you see any errors reported in the file?

**Comment by DonkeyTronKilla** [comment] 2017-09-15 03:24
So it turns out I did not have the d.ts definitions for react-native. I didn't think I would have to do this manually since I don't have to for react or many other npm installed libraries but I guess apps created with `react-native init` command don't include typescript type definition files but instead rely on the Flow type annotations within the npm installed library. After running `npm install @types/react-native --save-dev` I have the intellisense available to me. I also noticed there is a vscode extension for using Flow, but it seemed like that had more involved setup. I'm wondering if this is just something everyone else is aware of or is this a recent change? Are others choosing to install Flow and the associated vscode plugin to get this to work?

**Comment by mjbvz** [comment] 2017-09-15 03:30
The typings should be downloaded automatically since you are working in JavaScript: https://code.visualstudio.com/Docs/languages/javascript#_automatic-type-acquisition

Did you ever see a message in the VSCode status bar about typings install failing? Have you configured a custom `"typescript.tsdk"` setting in VSCode? 

You can also check the typings installer logs:

1. Set `"typescript.tsserver.log": "verbose"` in your user settings
2. Restart VSCode and open the js file again
3. Wait 10 seconds or so
4. Run the `TypeScript: Open TS Server Log` command in VSCode
4. This should open a folder with a file called `ti-xxx.log`

That `ti-xxx.log` file has info about automatic typings installation. Look for any error messages in this file (they would probably be near the top)

**Comment by DonkeyTronKilla** [comment] 2017-09-15 04:08
I do not have a custom setting for `typescript.tsdk` nor am i getting a vscode status bar about the install failing (at least none that I noticed). However checking the log as you instructed I do see an error at the end having to do with the npm package `@types/big-integer@ts2.5`

<img width="1127" alt="screen shot 2017-09-14 at 9 04 23 pm" src="https://user-images.githubusercontent.com/6686474/30466179-c63ae754-9990-11e7-89a9-9424705d0f07.png">

```
npm install #1 took: 1378 ms
stdout: 
stderr: npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/big-integer@ts2.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donkeytronkilla/.npm/_logs/2017-09-15T04_00_17_439Z-debug.log

install request failed, marking packages as missing to prevent repeated requests: ["react-native","react-test-renderer","big-integer","denodeify","isomorphic-fetch","qs","ua-parser-js"]
Sending response: {"kind":"event::endInstallTypes","eventId":1,"projectName":"/Users/donkeytronkilla/Development/test2/jsconfig.json","packagesToInstall":["@types/react-native@ts2.5","@types/react-test-renderer@ts2.5","@types/big-integer@ts2.5","@types/denodeify@ts2.5","@types/isomorphic-fetch@ts2.5","@types/qs@ts2.5","@types/ua-parser-js@ts2.5"],"installSuccess":false,"typingsInstallerVersion":"2.5.2"}
Response has been sent.
```

**Comment by Mellemel** [comment] 2017-09-21 15:57
I am getting the same thing you are 

`stderr: npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/Mel/.nvm/versions/node/v7.10.1/bin/node" "/Users/Mel/.nvm/versions/node/v7.10.1/bin/npm" "install" "--ignore-scripts" "@types/lodash@ts2.5" "@types/react@ts2.5" "@types/react-native@ts2.5" "@types/jest@ts2.5" "@types/react-test-renderer@ts2.5" "@types/async@ts2.5" "@types/big-integer@ts2.5" "@types/denodeify@ts2.5" "@types/isomorphic-fetch@ts2.5" "@types/qs@ts2.5" "@types/sprintf@ts2.5" "@types/superagent@ts2.5" "@types/ua-parser-js@ts2.5" "--save-dev" "--user-agent=typesInstaller/2.5.2"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: @types/big-integer@ts2.5
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.15-alpha, 0.0.16-alpha, 0.0.21-alpha, 0.0.22-alpha, 0.0.23-alpha, 0.0.24-alpha, 0.0.25-alpha, 0.0.26-alpha, 0.0.27-alpha, 0.0.28, 0.0.29, 0.0.30, 0.0.31
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Mel/.npm/_logs/2017-09-21T15_46_36_376Z-debug.log

install request failed, marking packages as missing to prevent repeated requests: ["lodash","react","react-native","jest","react-test-renderer","async","big-integer","denodeify","isomorphic-fetch","qs","sprintf","superagent","ua-parser-js"]
Sending response: {"kind":"event::endInstallTypes","eventId":1,"projectName":"/Users/Mel/Documents/Projects/shade51/jsconfig.json","packagesToInstall":["@types/lodash@ts2.5","@types/react@ts2.5","@types/react-native@ts2.5","@types/jest@ts2.5","@types/react-test-renderer@ts2.5","@types/async@ts2.5","@types/big-integer@ts2.5","@types/denodeify@ts2.5","@types/isomorphic-fetch@ts2.5","@types/qs@ts2.5","@types/sprintf@ts2.5","@types/superagent@ts2.5","@types/ua-parser-js@ts2.5"],"installSuccess":false,"typingsInstallerVersion":"2.5.2"}
Response has been sent.
`

**Comment by harisvsulaiman** [comment] 2017-10-20 00:17
This has been bothering me for a while.

**Comment by mjbvz** [comment] 2017-10-20 03:36
@andy-ms Can you please take a look at these typings installer logs errors

**Comment by andy-ms** [comment] 2017-10-20 16:04
@mjbvz Looks like we forgot to tag the new version on NPM. Should be fixed now. Made an issue #19375.

**Comment by mjbvz** [comment] 2017-10-20 20:59
Thanks @andy-ms! Closing this as upstream

**Closed by mjbvz** 2017-10-20 20:59 UTC
Labels: javascript, upstream
