### ISSUE TITLE
SPLIT SCREEN FOR EXTENSION WINDOW

### ISSUE THREAD

**Issue by arknmaulana** [microsoft/vscode#81054] opened 2019-09-17 14:37 UTC
Issue Type: <b>Bug</b>

when i open an extension window, then i click on the split screen button, it say error idk what it say, then the window is closed and blank, i cant open my file window again

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.95GB (5.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
node-snippets|chr|1.0.0
bracket-pair-colorizer|Coe|1.0.61
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|2.2.2
snippet|Irv|1.0.0
chat|kar|0.22.1
vscode-language-babel|mgm|0.0.24
mssql|ms-|1.6.0
csharp|ms-|1.21.2
vsliveshare|ms-|1.0.809
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
LiveServer|rit|5.6.1

(4 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-09-17 15:30
/duplicate of https://github.com/microsoft/vscode/issues/80296

**Closed** 2019-09-17 15:30 UTC
Labels: *duplicate
