### ISSUE TITLE
macOS dock icon is miniscule

### ISSUE THREAD

**Issue by samuela** [microsoft/vscode#63068] opened 2018-11-14 00:17 UTC
If you zoom way, way in you can see that it's in between VirtualBox and Activity Monitor:
<img width="1134" alt="screen shot 2018-11-03 at 3 43 10 pm" src="https://user-images.githubusercontent.com/226872/48451437-488e6100-e75f-11e8-9953-0cf57e38fb8c.png">

- VSCode Version: Version 1.30.0-insider (1.30.0-insider) c72cb129f2a0b8117c9b01f3767026041d7d1d31
- OS Version: macOS 10.14.

Steps to Reproduce:
1. Launch VSCode.
2. Observe the dock icon.

Does this issue occur when all extensions are disabled?: Yes

**Comment by samuela** [comment] 2018-11-14 00:19
Restarting the dock with `killall Dock` seems to have reset the icon to normal size. Still not sure how or why it ended up tiny in the first place.

**Comment by roblourens** [comment] 2018-11-14 01:43
That's... weird. Let us know if that happens again.

**Comment by Elijen** [comment] 2018-11-16 12:22
Happens to me too. Restarting VS Code does not help. `killall Dock` does.

**Comment by Nitive** [comment] 2018-11-18 17:46
Just happened to me on stable version. Lots of time could not figure out what it is.

VSCode Version: 1.29.1
OS Version: macOS 10.14

**Comment by sameeragrawal** [comment] 2018-11-23 08:44
This just happened to me, just after upgrading and restarting VS Code.

**Comment by alistaircom** [comment] 2018-12-05 03:09
I am also having this issue.  I have:

* disabled all extensions 
* ensured I am running the current stable build: 1.29.1
* removed all themes, am running the default Light (Visual Studio) 
* removed all custom settings from settings.json
* quit the app and relaunched

See screenshot:

<img width="373" alt="screenshot 2018-12-04 19 05 20" src="https://user-images.githubusercontent.com/855160/49487531-9dba1180-f7f7-11e8-9879-874a212cac90.png">

**Comment by roblourens** [comment] 2018-12-05 03:14
Anyone still seeing it, try `killall dock` or restarting the mac.

**Comment by alistaircom** [comment] 2018-12-05 03:49
Yes, `killall Dock` fixes it. 

Here's hoping there will be a fix that doesn't include restarting your dock or your Mac to have an icon work.

**Comment by roblourens** [comment] 2018-12-05 04:16
Is there an open dupe for this @bpasero or @joaomoreno? I also see https://github.com/Microsoft/vscode/issues/59578

**Comment by bpasero** [comment] 2018-12-05 05:58
Sounds like a bug in Mojave to me, but I never saw that.

Are people seeing any suspicious output when running "code --verbose"?

**Comment by roblourens** [comment] 2018-12-05 06:12
And has anyone seen it with any other apps?

**Comment by alistaircom** [comment] 2018-12-05 06:47
I have not seen it in any other apps. This post on Stack Exchange seems to be indicating an identical issue:

https://apple.stackexchange.com/questions/338881/there-is-a-tiny-icon-on-macos-dock-that-is-not-clickable

**Comment by samuela** [comment] 2019-01-09 23:33
This just happened to me again after the whole restart-to-upgrade process to Version 1.31.0-insider.

**Comment by Robotex** [comment] 2019-01-23 18:00
Happened to me 2-3 times already this month, in my case it happened mostly after my MacBook awakened from sleep/after a hard shutdown

**Comment by samuela** [comment] 2019-02-02 19:49
Just got this again on VSCode Version 1.31.0-insider (1.31.0-insider) and macOS 10.14.2.

**Comment by leggsimon** [comment] 2019-02-15 11:02
@roblourens I took a copy of my `com.apple.Dock.plist` before and after. I have diffed it but if I'm honest I have no idea what I'm looking at!

It seems as though some of the different lines might be caused by the fact that the order changed but they’re both here for you if they might mean anything to you

https://gist.github.com/leggsimon/58e9da1708a2d0f4c47f83fde1e1f5da

**Comment by japhillips87** [comment] 2019-03-02 02:07
It's happening for me too. `killall Dock` does work, but it's an annoying bug.

**Comment by bfinlay** [comment] 2019-03-07 17:38
Experiencing this issue still with macOS 10.14.2 and VS Code 1.31.1

**Comment by rallerG** [comment] 2019-03-22 13:40
I have this issue with macOS 10.14.3 and VS code 1.32.3

**Comment by mirceagrelus** [comment] 2019-04-12 11:40
This issue continues to pop up, and it's very annoying. Latest versions of everything.

**Comment by qinfeng** [comment] 2019-04-23 07:23
Same issue here with macOS 10.14.4 and VS code 1.33. `killall Dock` fix it.

**Comment by hacker** [comment] 2019-05-11 15:00
Not much of a difference upon Dock restart. I was expecting a lot of noise, but no:

```diff
--- b.plist	2019-05-11 16:56:15.000000000 +0200
+++ a.plist	2019-05-11 16:56:22.000000000 +0200
@@ -1,27 +1,27 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
 	<key>autohide</key>
 	<false/>
 	<key>last-messagetrace-stamp</key>
 	<real>579029752.02692497</real>
 	<key>loc</key>
 	<string>en_GB</string>
 	<key>mod-count</key>
-	<integer>2173</integer>
+	<integer>2174</integer>
```

**Comment by plamenh** [comment] 2019-05-23 10:20
Me too, just updated.

**Comment by a-x-** [comment] 2019-06-13 19:17
Fix it please.

Yes, I can do `killall Dock` and it works,
but issue catches humans again and again

**Comment by darkheartfelt** [comment] 2019-07-01 16:04
This is extremely annoying.

**Comment by nikhil-cdac** [comment] 2019-07-04 05:45
I am having the same issue. macOs 10.14.5 VS Code: Version 1.36.0 (1.36.0)

**Comment by samuela** [comment] 2019-07-10 23:46
Ever since the icon rebrand recently I haven't had this issue. (I'm on 1.37.0-insider at the moment.) No idea if that means it's actually been resolved, but for whatever reason it hasn't happened to me yet.

**Comment by plamenh** [comment] 2019-07-11 05:34
@samuela , I similarly thought so just as well, before this morning, since when I have the same problem as with the old icon. So, no worries, it will happen eventually. killall Dock is our friend.

**Comment by Gullintani** [comment] 2019-07-11 08:52
"Watching the Earth between the Saturn and the Jupiter"

**Comment by achingbrain** [comment] 2019-08-09 12:07
I get this all the time. Doesn't happen to any other app, just VSCode.

**Comment by bstaudacher** [comment] 2019-08-20 20:21
Still happening macOS 10.14.5, VS Code Version: 1.37.1

Screenshot (adorable but annoying):

<img width="290" alt="Screen Shot 2019-08-20 at 1 15 49 PM" src="https://user-images.githubusercontent.com/52678091/63381364-5952af80-c34d-11e9-9e36-3d4ffeeacde4.png">

**Comment by darkheartfelt** [comment] 2019-09-09 21:16
LOL @ this still happening on 1.38.0

**Comment by michaelneale** [comment] 2019-09-17 07:26
`killall Dock` works - showed up after a macos restart recently.

**Comment by tsunami42** [comment] 2019-09-24 02:37
`killall Dock` works
VSCode version `1.38.1`
MacOS version `10.14.6 (18G95)`

**Comment by zenwong** [comment] 2019-10-04 00:51
killall Dock works
VSCode version 1.38.1
MacOS version 10.14.6

noticed it happening after a hard reboot of the system.

**Comment by Pixeleyes** [comment] 2019-10-15 12:44
Same for me 
1.39.1
10.14.6

**Comment by bpasero** [comment] 2019-10-15 15:12
I added the "help wanted" label recently as I am clueless what this is. If anyone has contacts to Apple devs to ask for help that would be cool 👍

**Comment by yiyizym** [comment] 2019-10-16 02:06
Same for me
1.39.2
10.15

**Comment by aliblackwell** [comment] 2019-10-16 12:51
Same for me 
VS Code: 1.39.2
Mac: 10.14.5

Here's a repo with a before and after of ~/Library/Preferences/com.apple.Dock.plist. It's in binary so git diff wasn't very helpful, but hopefully it's of use to someone (@roblourens): https://github.com/aliblackwell/vscode-broken-icon

**Comment by bpasero** [comment] 2019-10-16 13:42
@aliblackwell can you explain what exactly this diff is telling? Are you suggesting that the diff would reveal what setting the dock was changing to to make the issue go away?

**Comment by aliblackwell** [comment] 2019-10-25 09:26
Hey @bpasero this was posted in response to @roblourens' request (https://github.com/microsoft/vscode/issues/63068#issuecomment-444548823) for a diff. I'm not a Mac developer so I couldn't really tell you what it's telling – I just posted it on the off-chance it was helpful to someone qualified to fix this bug!

**Comment by aliblackwell** [comment] 2019-10-25 09:27
But yes @bpasero, it's essentially a before and after of my com.apple.Dock.plist where in the state before running `killall Dock` the icon was tiny, and the state after it was fixed.

**Comment by anandshenoy14** [comment] 2019-11-01 16:49
Happens to me on VSCode Version 1.39.2

```
Details Here:
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```
It gets resolved `only` by doing killall Dock

**Comment by dannew** [comment] 2019-11-14 15:49
Haven't seen it for a while but after updating to 1.40.1 it happened again. killall Dock fixed it.

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by nantunes** [comment] 2019-11-18 17:22
Same thing.

VS Code 1.40.1
macOS 10.15

**Comment by gurghet** [comment] 2019-11-25 14:40
Happened to me as well, super cute. (but slightly unproductive)

**Comment by oisindev** [comment] 2019-11-29 08:30
Happened over here too 
MacOS 10.14.5
VS Code:
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

`killall Dock` fixed it

**Comment by phillipbroberts** [comment] 2019-12-04 18:14
Happened to me today: 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.4.0
python|ms-|2019.11.50794


</details>

**Comment by alistaircom** [comment] 2019-12-04 18:45
I have returned to the error after `killall Dock` previously "fixed" it. I noticed that the icon is tiny once again after a number of months where it didn't appear to be happening.  However, I often don't use the dock, and use Alfred to launch apps, then Cmd+Tab to switch between them.  I just happened to notice it today when the Dock popped up.

- VS Code 1.40.2
- OS 19.0.0

**Comment by winsome** [comment] 2019-12-05 14:03
Add me to the list of those experiencing it

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by bfinlay** [comment] 2019-12-17 18:30
Still experiencing tiny icon problem in dock with version information below.  `killall Dock` repairs the problem until the next time it occurs.

![image](https://user-images.githubusercontent.com/1757856/71023531-88ddb280-20c8-11ea-88f2-c39fc3f46a79.png)

Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by alexsergin** [comment] 2019-12-18 15:48
It happened just now after vscode update. Dock restart has fixed the problem

**Comment by fengyc** [comment] 2019-12-29 01:28
Same for me. 

![image](https://user-images.githubusercontent.com/4906850/71551243-814dd000-2a1d-11ea-87e2-e68358b4109b.png)

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by pavelloz** [comment] 2020-01-08 00:25
Is this normal?

<img width="330" alt="image" src="https://user-images.githubusercontent.com/546845/71940194-b2649800-31b5-11ea-9319-eaff69c761ee.png">


```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by vgrafe** [comment] 2020-01-09 02:54
I had this happen regularly, but now the icon is not in the dock at all. Not even the running indicator underneath it.

**Comment by ZuBB** [comment] 2020-01-15 10:54
I am having this right now.

@joaomoreno @deepak1556 I can provide any info you need or do some debug

<img width="126" alt="Screen Shot 2020-01-15 at 12 54 26" src="https://user-images.githubusercontent.com/597016/72428362-2db9e100-3796-11ea-930f-b2118c01c1c9.png">

**Comment by n13** [comment] 2020-01-21 09:15
Same here

Sure killall Dock fixes it but how about VS Code behaves like a normal application? After all, I've never seen that with any app, this is the second time I've had it happen with VS Code.

<img width="104" alt="image" src="https://user-images.githubusercontent.com/65412/72791037-9bbc4780-3c71-11ea-9b35-af593b9217be.png">

**Comment by LucasMW** [comment] 2020-01-23 17:44
Happened to me in Mac OS Catalina. Have never happened before 
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

killall Dock works, however.

**Comment by codepo8** [comment] 2020-01-24 19:07
Keeps happening here, too.

**Comment by danashurst** [comment] 2020-01-26 01:37
Happened to me as well. killall Dock command seems to rectify the issue.

**Comment by nikhil-ravi** [comment] 2020-01-27 17:14
Happened here as well. `killall Dock` did the trick.

**Comment by jupp0r** [comment] 2020-01-28 22:11
Happens to me frequently, which is really annoying. `killall Dock` works.

**Comment by rhukster** [comment] 2020-02-02 02:58
#metoo I have never seen this with any other app in all my years running macOS, and it just happened to me also. No one has a clue?

**Comment by softgandhi** [comment] 2020-02-05 15:08
happens to me as well. `killall Dock` works. Thanks.

**Comment by djalmaaraujo** [comment] 2020-02-07 11:59
I just had this issue. `killall Dock` fixed. Thanks.

**Comment by pcolazurdo** [comment] 2020-02-16 10:03
same here on:
Version: 1.43.0-insider
Commit: 4c9161a3f125f5a788aafa73a4ecfcb27dcfc319
Date: 2020-02-14T05:26:38.779Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

*killall Dock* fixed it, but really annoying - and this thread wasn't easy to find :)

**Comment by jflyup** [comment] 2020-02-16 19:48
same issue:

> Version: 1.42.1
> Commit: c47d83b293181d9be64f27ff093689e8e7aed054
> Date: 2020-02-11T14:44:27.652Z
> Electron: 6.1.6
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Darwin x64 19.2.0

`killall Dock` fixed it

**Comment by 019a** [comment] 2020-02-19 16:22
Same here. killall Dock fixed it too.

**Comment by newlegendmedia** [comment] 2020-02-24 19:27
I am seeing this issue too. I just started evaluating whether I to switch to VS Code from Sublime and this is not a good start. Ive used Macs for 20+ years and never had this happen with an app.

**Comment by codepo8** [comment] 2020-02-24 19:31
Well, that's a bit unfair, @newlegendmedia, I've used macs for 10 years and discovered all kind of weird things. I moved from Sublime to VSCode, too, and I would not go back ever again. It is so much more lightweight and there is an extension for everything!

**Comment by newlegendmedia** [comment] 2020-02-24 19:37
@codepo8 I would agree except this appears to have been reported over a year ago.

**Comment by jeremymika** [comment] 2020-03-05 21:57
It's ridiculous. Took me a few days to understand what was actually happening. It's funny, I'm looking at switching back to Sublime. My text is rendering weird, and this seems like just another item in a growing list of weird things that this web-app-pretending-to-be-an-app does poorly (and seemingly unfixable) that native apps do not.

Of course, I say that, but fast-forward to 3 days after switching: "I'm BAAACK!" We'll see...

**Comment by gerwim** [comment] 2020-03-17 08:14
Same issue here. Running `killall Dock` fixed it (for now).

```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by morningstarwang** [comment] 2020-03-18 16:05
> Restarting the dock with `killall Dock` seems to have reset the icon to normal size. Still not sure how or why it ended up tiny in the first place.

happen to me either on the latest stable version

**Comment by AkuSilvenius** [comment] 2020-03-22 10:05
I experienced this first time now, in macOS Mojave 10.14.6. As for others, ```killall Dock``` fixes the issue for me too.

vscode:
```
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

<img width="120" alt="Screenshot 2020-03-22 at 11 56 04" src="https://user-images.githubusercontent.com/17451320/77246985-4ed6fc00-6c35-11ea-8e8a-d1e68dc61f63.png">

**Comment by lllvantis** [comment] 2020-03-23 02:11
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

Happened again.

**Comment by piyushwadhwani** [comment] 2020-03-23 17:34
it happens for me too 

Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0


killall Dock fixes it

**Comment by maibatsu** [comment] 2020-03-25 09:47
I have the same issue :D

```
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

Running `killall Dock` fixed it.

**Comment by jhoughjr** [comment] 2020-03-26 17:03
First time for me seeing this issue. But I have no running indicator, but the icon does appear in the app switcher. Nice to see this has been an issue for two years.

**Comment by Kristof-Mattei** [comment] 2020-03-31 18:16
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
``` same issue here. Spent 2 hours finding the icon on my Dock.

**Comment by junjizhi** [comment] 2020-04-06 18:20
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```
Had the same issue. Running `killall Dock` fixed it.

**Comment by alectrocute** [comment] 2020-04-07 23:49
This is an issue with Electron. Colleague ran into this today after reinstalling our newly built Electron 8.x app in production. If I find a workaround before the VS Code team does, I'll make certain to share.

We currently utilize Electron's `app.dock` API which is not playing too nicely with macOS Catalina. A random combination of `app.dock.show()`, `app.dock.hide()` and `app.dock.*` can trigger this dock-breaking payload. Needless to say, this API's are critical to an Electron app feeling like an app and we can't just stop using them.

A very humous albeit frustrating bug. Hope to see it through soon.

**Comment by austinjhunt** [comment] 2020-04-14 13:44
I've been bitten as well: 


Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z (6 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

macOS Catalina v 10.15.4

Something interesting to note in my case is that it started happening immediately after adding a secondary monitor.

**Comment by dannew** [comment] 2020-04-14 13:57
> I've been bitten as well:
> 
> Version: 1.44.0
> Commit: [2aae1f2](https://github.com/microsoft/vscode/commit/2aae1f26c72891c399f860409176fe435a154b13)
> Date: 2020-04-08T08:23:56.137Z (6 days ago)
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 19.4.0
> 
> macOS Catalina v 10.15.4
> 
> Something interesting to note in my case is that it started happening immediately after adding a secondary monitor.

I also use both the internal screen and an external monitor.

**Comment by alectrocute** [comment] 2020-04-15 17:29
I'm using an external monitor and have nearly identical specs to @austinjhunt, which leaves me scratching my head as to why I can't trigger this bug?

**Comment by CapsAdmin** [comment] 2020-04-16 08:31
It happened to me on a macbook pro. It's been like this for a while actually,  but I just didn't see the small icon and I thought vscode was just gone from the taskbar for some obscure macos reason and so I got kind of used to it. (I tried googling vscode missing from dock)

I tried to diff the plist mentioned above but the only thing that changed was an increment of `<integer>` in the dict entry. (I had to convert the binary plist to xml)

I have no external monitor.

```
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z (1 wk ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0
```

**Comment by jrr** [comment] 2020-04-23 14:04
Just thought I'd share this with the internet:

![image](https://user-images.githubusercontent.com/164652/80107984-c7d5b600-8549-11ea-8fbb-7ef12256de42.png)

**Comment by Glaydson** [comment] 2020-04-23 16:32
I'm using Catalina 10.15.5 (beta) and the problem persists. Issuing killall Dock fixes it fortunately.

**Comment by mmsoon** [comment] 2020-04-27 17:22
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

killall dock fixes this

**Comment by BenKHoward** [comment] 2020-04-29 19:24
For the record, I just had a similar issue where the vs code icon didn't appear in the dock at all. There was no tiny icon and no dot on the bottom to indicate a running app (so I wasn't just overlooking the icon). com.apple.dock.plist did show that there should've been something there for vs code.

killall Dock fixed it.

Just thought I'd mention it in case someone outright has no icon.

**Comment by premkash** [comment] 2020-05-09 21:51
Happened to my mac too. 
![image](https://user-images.githubusercontent.com/442902/81485759-85012700-9247-11ea-88f3-b802d0adc39d.png)

See that miniscule vscode in the dock.

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by bpasero** [comment] 2020-05-13 09:40
Can people seeing this issue please report back if it reproduces in todays insider build were a change went in yesterday:
* Download or update from https://code.visualstudio.com/insiders/
* Check Help > About you are on `Commit: e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb`

Thanks

**Comment by bpasero** [comment] 2020-05-15 15:33
ping @samuela

**Comment by samuela** [comment] 2020-05-15 16:44
@bpasero I'll keep a look out for it!

**Comment by bpasero** [comment] 2020-05-19 06:07
Closing optimistically, we can reopen if this comes back.

**Closed by bpasero** 2020-05-19 06:07 UTC
Labels: bug, help wanted, mojave

**Comment by kenklin** [comment] 2020-05-19 18:39
> Can people seeing this issue please report back if it reproduces in todays insider build were a change went in yesterday:
> 
> * Download or update from https://code.visualstudio.com/insiders/
> * Check Help > About you are on `Commit: e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb`
> 
> Thanks

@bpasero Thanks. Looks good for me so far ...
Version: 1.46.0-insider
Commit: da3bf754c3c0eabda1dc80ed9d627679ee560697
Date: 2020-05-19T10:04:14.981Z (8 hrs ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by niyazpk** [comment] 2020-05-26 18:25
I am not on insider build, so cannot check the above commit. Still happening for me with the latest update though:
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by alexdmiller** [comment] 2020-05-27 03:06
+1

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by bpasero** [comment] 2020-05-27 04:57
You need our insiders version to benefit from the fix: https://code.visualstudio.com/insiders/

**Comment by worc** [comment] 2020-05-29 15:15
what's the timeline for this fix to drop outside the insiders build?

**Comment by bpasero** [comment] 2020-05-29 15:23
~1.5weeks from today.

**Comment by olegueret** [comment] 2020-06-03 10:28
Just to mention it happened to me but with Azure Data Studio, also based on VSCode.

Their issue: https://github.com/microsoft/azuredatastudio/issues/8107

I tried uninstalling the app, download again and reinstall, but that doesn't fix it. 
**When it was uninstalled, the icon still appeared in the Dock** (in the **Recents** list).

Reopening Finder doesn't work. killall Dock works tough.

I'm on Mojave 10.14.6 (18G4032)

**Azure Data Studio**
Version: 1.18.1
Commit: 5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa
Date: 2020-05-26T21:11:42.467Z (1 wk ago)
VS Code: 1.45.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

![Captura de Pantalla 2020-06-03 a les 12 07 10](https://user-images.githubusercontent.com/49993/83625604-7e3ea900-a594-11ea-92f5-963c51d49c4e.png)

**Comment by slyang-git** [comment] 2020-06-04 05:34
`killall Dock `helps

**Comment by isidorn** [comment] 2020-06-04 13:43
Optimistically adding verified label based on users comments with VS Code insiders

**Comment by Pixelatex** [comment] 2020-06-11 14:17
This has just occured to me for the very first time. Only happens when I have certain plugins installed. (postgres ones)

**Comment by alectrocute** [comment] 2020-06-11 19:52
@bpasero For others affected with this issue in Electron, would you kindly point to the specific commit or code changed?

**Comment by bpasero** [comment] 2020-06-12 06:05
@alectrocute the change is https://github.com/microsoft/vscode/commit/f8f0c0ec5499cf5d210b12672d71784e93d42f0d and it was basically not using any `app.dock.*` methods whatsoever.

**Comment by worc** [comment] 2020-06-19 21:33
got a recent update and the issue went away for me:

```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (1 wk ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```
