### ISSUE TITLE
Pasting into code line below a jsdoc block comment auto-indents by one space character

### ISSUE THREAD

**Issue by danielrentz** [microsoft/vscode#119225] opened 2021-03-18 05:22 UTC
- VS Code Version: 1.54.3
- OS Version: Win 10

Steps to Reproduce:

1. Have the following code snippet in a JS editor
```js
/**
 * doc
 */
x = 1;
```
2. copy a word to clipboard, e.g. "var"
3. place cursor before "x", paste

Result: The pasted word indents the line by one space. This should not happen below such a jsdoc comment block.

Does this issue occur when all extensions are disabled?: Yes

**Comment by DavidSvetlik** [comment] 2021-04-06 12:42
Yes, please fix it, it's really annoying and wasn't happening couple of versions back.

**Comment by danielrentz** [comment] 2021-04-07 11:48
Alternative steps to reproduce, most likely the same root cause:

Copy the following block, pate it into an empty line. Everything following the first jsdoc comment will be indented.

```javascript
/**
 * doc
 */
var x = 1;

/**
 * doc
 */
var y = 1;
```

**Comment by adamreisnz** [comment] 2021-09-17 21:22
I can also confirm this is happening consistently in Javascript, and that this didn't use to happen in earlier versions.
Note that Format on Paste is **disabled**, and no extensions have been enabled.

### Example 1
```js

/**
 * Block comment
 */
class Test {

  /**
   * Block comment
   */
  someMethod() {
    doSomething()
  }
}
```

To reproduce:
Select and copy the whole block of code (including block comment) of `someMethod` as follows:
![image](https://user-images.githubusercontent.com/490562/133854362-a01d1b78-692a-41f2-8a45-4e6f790cb310.png)

Paste the block 2 rows below and observe that there is an extra space added before `someMethod`:

![image](https://user-images.githubusercontent.com/490562/133854429-65b9001d-4156-4c15-8496-26e024faf4e6.png)

### Example 2
Same code as below, but this time paste the block outside of the class. The whole comment block gets wrecked, and the extra space is still there:

![image](https://user-images.githubusercontent.com/490562/133854755-03f7bc01-9608-48ab-b1a1-1220c6f035fb.png)

There are more examples with subtly different behaviour, but these are the most aggravating and I don't remember the others at this moment. I will update this comment and post again once I encounter them again.

Fun fact, I switched from Atom to VSCode precisely because it was [riddled](https://github.com/atom/atom/issues/11995) with [these](https://github.com/atom/atom/issues/5362) minor [annoyances](https://github.com/atom/atom/issues/15098) which would never get fixed and are still an issue 5 years later. I was so excited that VSCode didn't have any of the annoying paste bugs that Atom had, but now they have appeared here as well, and don't seem to be getting a lot of traction to fix 😢

**Comment by ssigwart** [comment] 2021-11-07 00:32
I found a better solution that I had in #128812.  It's in #136579.  I just need to get someone to review and merge it.

**Comment by gene-pavlovsky** [comment] 2022-07-15 08:01
Hope this can be reviewed/merged

**Comment by dandeancook** [comment] 2022-11-01 14:17
Merged the fix yet? i still see the extra space after pasting, i guess it is so due to autoformat after pasting

**Closed** 2022-11-18 10:15 UTC
Labels: bug, editor-autoindent

**Comment by seebz** [comment] 2022-12-09 15:35
This issue also applies to other languages, at least PHP.
