### ISSUE TITLE
Menu items not localized

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#6927] opened 2016-05-26 18:00 UTC
- VSCode Version:1.1.0-alpha
- OS Version:Windows 8.1, OS X

Steps to Reproduce:

1. Configure Language to anything beside english
2. Restart VS Code

The top menu items and their dropdowns are not localized (show as English). The status bar, view bar and command palette show the correct localized strings.

This repros whether you are on a localized OS or not.

**Comment by gregvanl** [comment] 2016-05-26 18:04
Doesn't repro on last Insiders so a regression in the last two weeks.

**Comment by dbaeumer** [comment] 2016-05-27 07:58
This is caused by a code reorganization done by Joao. We need to get the translations strings back from the translation team which will happen today or beginning of next week.

**Comment by gregvanl** [comment] 2016-05-27 15:20
I think we should keep the issue open until the translation strings are in the product so it can be verified.

**Comment by dbaeumer** [comment] 2016-05-30 08:50
Surprisingly we haven't received any translations. So I restored the old translations. The menu bat is fine now. 

In a monthly agile rhythm there will always be cases were not all of the UI is translated since we don't want to lock down on strings. We only do this for major releases. Since the menu bar is so prominent and was translated before it should be fixed. But new or improved features might always ship with some English text.

**Closed by dbaeumer** 2016-05-30 08:50 UTC
