### ISSUE TITLE
VSCode JavaScript Auto Import

### ISSUE THREAD

**Issue by billydarmawan** [Microsoft/vscode#60739] opened 2018-10-12 06:51 UTC
- VSCode Version: 1.28.0 (1.28.0)
- OS Version: macOS Mojave

Steps to Reproduce:

1. Open React Native App
2. Have Auto Import Configuration Enabled
3. Try to use Auto Import feature

![screenrecording20181012at1](https://user-images.githubusercontent.com/8708519/46852540-8e38d080-ce25-11e8-90e1-b88238147d2b.gif)

I am expecting the import statement to be appended on top of files, but instead it got inline.

I try to find some configuration that might related to this but didn't found any.

**Comment by zzzorgo** [comment] 2018-10-12 09:15
All duplicate issues are closed but this bug is still there. Catching it on every component import in every JSX file (using JS).

**Comment by n-sviridenko** [comment] 2018-10-12 16:04
Have same issue. It's also here https://github.com/Microsoft/vscode/issues/60786

**Comment by mjbvz** [comment] 2018-10-12 18:35
This is a duplicate of the issues the bot identified. Root cause is https://github.com/Microsoft/TypeScript/issues/27317. #60216 on our side tracks brining this fix in for 1.28.2 which will go out next week

This should already be fixed in the insiders builds too

**Closed by mjbvz** 2018-10-12 18:35 UTC
Labels: javascript
