### ISSUE TITLE
Intellisense no longer highlights best match

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/vscode#74192] opened 2019-05-23 10:21 UTC
- VSCode Version:  1.35.0-insider (Commit: 94f7de61ece171f4390ece488a220d22cbb0fddd)
- OS Version: Win 10 x64 1803

Steps to Reproduce:

1. Create a new TypeScript file and import anything with a type/interface
2. Use intellisense (autocomplete) and write a character that exists in the beginning of a match and also in exists in the middle of match above the previous one in the list.

Does this issue occur when all extensions are disabled?: Yes

Result:
![image](https://user-images.githubusercontent.com/5993909/58245338-d8d3e100-7d54-11e9-8ccd-1856682dab8c.png)

Expected behavior: 
 (Current one in VS Code 1.34.0)
![image](https://user-images.githubusercontent.com/5993909/58245384-f30dbf00-7d54-11e9-9e43-ec7816498168.png)
or
![image](https://user-images.githubusercontent.com/5993909/58245373-edb07480-7d54-11e9-8e3a-d5fcd16b6683.png)

**Comment by mjbvz** [comment] 2019-05-23 17:55
Duplicate of #74203 I believe

**Closed by mjbvz** 2019-05-23 17:55 UTC
