### ISSUE TITLE
Display current zoom level

### ISSUE THREAD

**Issue by ahdung** [Microsoft/vscode#10642] opened 2016-08-18 02:25 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Original title: How i know zoom level? ctrl+=/- | ctrl+mouseWheel

**Comment by alexandrudima** [comment] 2016-08-18 05:56
fyi @bpasero

**Comment by ahdung** [comment] 2016-08-18 06:41
Thanks for editing. and how to reset zoom level by ctrl+mousewheel?

**Comment by ahdung** [comment] 2016-08-18 06:41
Thanks for editing. and how to reset zoom level by ctrl+mousewheel?

**Comment by ahdung** [comment] 2016-08-18 06:41
Thanks for editing. and how to reset zoom level by ctrl+mousewheel?

**Comment by alexandrudima** [comment] 2016-08-18 08:51
Sorry, there is currently no way except `F1 > Reload window`.

**Comment by blaylockbk** [comment] 2016-11-04 18:29
Could show the zoom level for a short time when the zoom level is changed (similar to the chrome browser)

**Comment by mjbvz** [comment] 2017-11-09 00:29
Duplicate of #12318

**Closed by mjbvz** 2017-11-09 00:29 UTC
Labels: duplicate, editor-core, feature-request, workbench
