### ISSUE TITLE
disable bracket auto closing in string?

### ISSUE THREAD

**Issue by towry** [Microsoft/vscode#736] opened 2015-11-27 06:48 UTC
Bracket auto closing in string will make string concat in JS difficult.

For example, `|` is the cursor position:

`'translate'` -> `'translate(|)'` -> `'translate(' + '|')'`

What I want is `'traslate(' + ')'`, I have to remove a quote to wrap the last `)` in string.

**Comment by rebornix** [comment] 2017-07-14 18:03
Closing this first as now I can't reproduce this issue and it has been more than 1 year. Feel free to reopen it if you still have this issue.

**Closed by rebornix** 2017-07-14 18:03 UTC
Labels: bug, editor-brackets

**Comment by towry** [comment] 2017-07-15 01:20
Confirm bug fixed.
