### ISSUE TITLE
Clicking on the text of a file after doing a global search sometimes pastes the search term into the file

### ISSUE THREAD

**Issue by sundriftproductions** [Microsoft/vscode#49634] opened 2018-05-10 17:17 UTC
Issue Type: <b>Bug</b>

Hello --

I have been using Visual Studio Code for over a year and have seen this problem on multiple computers and every version of Visual Studio Code that I've tried.

Before I describe the issue, I should mention that I use a Wacom Intuos 3 graphics tablet/pen instead of a mouse. I don't know if this problem also appears with using a mouse, but, as you'll see, it's tricky to trigger -- but it *is* repeatable, as I've accidentally done this many times and it has caused a fair amount of lost productivity.

The steps to repeat the bug are this:

1) Do a global find for some search term.
2) Double-click on one of the search results. I believe the file has to NOT already be open in Visual Studio Code for this to be triggered.
3) Single-click *just* a little bit to the right of the highlighted word in the file that has been opened in Visual Studio Code. This is the tricky part -- it appears to be perhaps a specific number of pixels to the right. If you don't click the EXACT right spot, nothing will happen.
4) A copy of the search term is magically pasted directly after the highlighted word.

You can see this bug in action here: https://www.youtube.com/watch?v=1o2WhDFBtbo
 
Note that I try to trigger the bug several times but finally get it to happen at the 45 second mark.

I don't think this is a special "feature" of the Wacom pen/tablet -- Visual Studio Code is the only application that exhibits this sort of automatic copy/paste behavior. I can't tell you how many times my global search terms have been accidentally pasted into otherwise legitimate code, so getting a fix for this would be terrific.

Thank you!

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (9.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
git-easy|bib|1.9.1
vscode-toggle-quotes|Bri|0.3.1
githistory|don|0.4.0
gitlens|eam|8.2.4
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
sass-lint|gle|1.0.1
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|6.0.0
docomment|k--|0.1.0
vscode-scss|mrm|0.6.2
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.4.3
code-spell-checker|str|1.6.10
html-css-class-completion|Zig|1.17.1

</details>

**Comment by roblourens** [comment] 2018-05-12 19:01
Weird, I have no clue what that would be. Search doesn't copy or paste or insert anything automatically.

Is the string actually on your clipboard? If you press ctrl+v after this happens, does it paste again?

**Comment by sundriftproductions** [comment] 2018-05-14 12:29
No, the string isn't on the clipboard.

I found another characteristic that makes this bug easier to replicate. Make sure you do a global search where the search term is likely to end at the end of the line. For example, if you have a c# code base, do a search for "use System;" (sans quotes). Also, I may have incorrectly stated that it appears to happen a certain number of pixels to the right. You just have to click over to the right somewhat -- beyond the area where a newline has already happened in the code.

**Comment by sundriftproductions** [comment] 2018-05-14 12:52
I was able to replicate this bug with a mouse, so this is not a Wacom pen tablet-specific issue. The trick is to do this: when single-clicking with the mouse to the right of the highlighted text, move the mouse _down_ slightly. It seems that clicking and dragging down slightly in the area beyond the newline triggers some sort of automatic copy-and-paste of the highlighted search term. This copy-and-paste doesn't appear to involve the clipboard at all.

**Comment by roblourens** [comment] 2018-05-14 16:33
I haven't been able to, and can't think of any way this would happen... Can you start with `--disable-extensions` and see if you can still repro it?

**Comment by roblourens** [comment] 2018-05-14 16:38
I was just reminded that we have a feature that lets you drag to duplicate selected text. Could you be pressing the alt key when this happens? Maybe the tablet triggers the alt key somehow?

**Comment by sundriftproductions** [comment] 2018-05-16 15:14
I'm not intentionally pressing the alt key. I'm not ruling out that some other piece of software is doing this in the background, but I would think that I would have seen side effects in applications other than Visual Studio Code.

How do you trigger the ability to copy/paste via dragging the selected text plus pressing the alt key? Is it really that simple? I can't seem to make Visual Studio Code do that on its own.

**Comment by roblourens** [comment] 2018-05-16 16:14
You have to click and hold, then press alt, then drag. So if that's the cause of this, then maybe something is sending "alt" immediately after your click.

It seems to be the only possibility to me. Strange problem though.

**Comment by sundriftproductions** [comment] 2018-05-21 12:33
OK, I was able to do the copy/paste via dragging as you described. Is there an option in settings where I can turn that behavior off, just to see if it makes the original issue go away?

**Comment by roblourens** [comment] 2018-05-21 15:12
You can try settings `"editor.dragAndDrop": false`

**Comment by sundriftproductions** [comment] 2018-05-21 15:35
Thanks! That definitely turns off the copy/paste via dragging as you described. I can't get the original behavior I described to show up with that setting disabled, but then again, the problem always seemed intermittent. I'll keep using Visual Studio Code with that setting disabled and will report back if the original behavior shows up again.

**Comment by roblourens** [comment] 2018-05-21 23:06
Thanks! Will close this for now.

**Closed by roblourens** 2018-05-21 23:06 UTC
Labels: needs more info
