### ISSUE TITLE
Incoherent source control counter icon 

### ISSUE THREAD

**Issue by IperStan** [microsoft/vscode#140408] opened 2022-01-10 11:57 UTC
Issue Type: <b>Bug</b>

Hello,
since the VScode build number 1.63.x I found out the blue icon of source control tab to be incoherent with the actual situation I'm working with.
For instance, when I update a file, it appears in the list of "Changes" and the diff tool works between "before" and "after" files, BUT the round icon appears to be in the "loading" state instead of the simple number "1".

I use SVN as my main source control manager.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/43338672/148762494-19cdb13b-a2c7-4a27-b440-067c01307846.png)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
indent4to2|Com|0.1.2
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|11.7.0
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.5.13
vscode-drawio|hed|1.6.4
beautify|Hoo|1.5.0
svn-scm|joh|2.15.2
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.4
HTMLHint|mka|0.10.0
vscode-filesize|mkx|3.1.0
prettify-json|moh|0.0.3
sublime-keybindings|ms-|4.0.10
color-highlight|nau|2.5.0
vscode-ant|nic|0.3.1
vetur|oct|0.35.0
vscode-yaml|red|1.2.2
sass-indented|rob|1.5.1
vscode-paste-and-indent|Rub|0.0.8
vscode-sql-beautify|sen|0.0.4
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.8.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by IllusionMH** [comment] 2022-01-10 12:02
/causedByExtension

Most likely bug with SVN extension and should be reported there first.
Probably duplicate of https://github.com/JohnstonCode/svn-scm/issues/1551

**Closed** 2022-01-10 12:02 UTC
Labels: *caused-by-extension
