### ISSUE TITLE
Terminal in Editor Area duplicates/hides content when switching between multiple terminals

### ISSUE THREAD

**Issue by asw101** [microsoft/vscode#131136] opened 2021-08-18 23:12 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0-insider
- OS Version: macOS Big Sur (11.4)

I am a heavy user of the [Terminals in Editor Area](https://code.visualstudio.com/updates/v1_58#_terminals-in-the-editor-area). 

I often find the terminal duplicates/hides content when switching between multiple terminals. When switching from one terminal, to another, the same content will be visible. Occasionally clearing the terminal (via Ctrl+L) will not work. A simple `echo "hello"` in one terminal will sometimes cause it to re-paint/render and fix the issue.

When scrolling it will also hide the input line (the last line of the terminal) which causes issues entering commands.

I am working to get a good video repro of this and will update this issue with the best version of it as available.

Steps to Reproduce:

1. Open two terminals.
2. Output a reasonable amount of text in one terminal.
3. Switch to the second terminal.

**Comment by meganrogge** [comment] 2021-08-19 15:14
Thanks, a gif would be very helpful because I can't reproduce the issue

**Comment by jeanp413** [comment] 2021-08-19 21:50
Duplicate of #130110.
Created a PR #131211 fixing it

**Closed** 2021-08-20 02:08 UTC
Labels: needs more info, *duplicate
