### ISSUE TITLE
Can't select text in extension details page

### ISSUE THREAD

**Issue by isometriq** [Microsoft/vscode#24642] opened 2017-04-12 23:27 UTC
There is a lot of instructions and documentation in these pages, sometime they show commands to use. It's counter-productive to have to go on the original repo just to be able to copy-paste... Seems like an issue to me.

- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Go to an extension details page
2. Try to select some text and copy-paste anywhere

**Comment by mjbvz** [comment] 2017-04-13 04:15
I'm able to copy text just fine from these pages using cmd+c on MacOS. #12034 tracks adding copy to the context menu for webviews.

I'll test on windows too but could you also explain how are you trying to copy the text here?

**Comment by isometriq** [comment] 2017-04-15 17:34
Yes, you are right, I can select and use CTRL+C to copy and there is indeed no context menu, on the "Details" tab. I can't do that on the "Contributions" tab.

**Comment by mjbvz** [comment] 2017-04-15 18:39
Thanks for the update.

Closing this bug as a duplicate of #12034. That bug tracks the markdown preview specifically but any fix should also apply to other webviews (which is how extension details are displayed as well)

**Closed by mjbvz** 2017-04-15 18:39 UTC
Labels: duplicate, webview
