### ISSUE TITLE
[code assist] let the user choose whether to overwrite the following word or only insert.

### ISSUE THREAD

**Issue by Meaix88** [Microsoft/vscode#30107] opened 2017-07-04 23:03 UTC
- VSCode Version: 1.13.1
- OS Version: Win 10 Pro

Steps to Reproduce:

1. When I start typing a tag right before text that already exists, it will bring up the suggestions and when I select the tag that I want (whether by pressing "Enter", "Tab", or by selecting it with the cursor), then the word next to it is overwritten by the tag. 

It does this with any suggested tag as far as I can tell.

I have attached 3 pictures where I am trying to add the emphasis tag to the word "website". The first picture is before I have started to tag, the 2nd is as I start to type the tag (you will notice that the word "website" is being highlighted in blue), and then after I have selected the emphasis tag from the suggestions you can see the word "website" is gone and replaced with just the tag.

![capture](https://user-images.githubusercontent.com/11046720/27844107-25e544e6-60da-11e7-917a-561e90f731ae.PNG)

![capture1](https://user-images.githubusercontent.com/11046720/27844123-6e190f86-60da-11e7-88b2-f3d9c257a8c4.PNG)

![capture2](https://user-images.githubusercontent.com/11046720/27844124-75a35f86-60da-11e7-8378-2e4b1fdae7f7.PNG)

Reproduces without extensions: Yes (I think, I am new to vsc and programming in general, so I think that I hadn't added any extensions to begin with. Someone else suggested the extension htmltagwrap, but that was the first extension I installed and it was doing it before. With that wrapper installed, I would highlight the text I wanted to tag and when I typed "<" it would add angled brackets to the beginning and end, but as soon as I typed anything else then it would overwrite the highlighted portion.

**Comment by hexrcs** [comment] 2017-07-07 15:11
This happens in macOS Sierra as well.

**Comment by jrieken** [comment] 2017-07-10 08:01
The extension can decide what it wants to replace/overwrite. By default the current word is being used, tho there is a desire to stream line that for all extensions

**Comment by aeschli** [comment] 2017-07-11 09:40
What you see is the currently expected behavior in HTML. It's a duplicate of #19560.
In Eclipse the user can choose with a modifier key whether code assist should replace the following word, or just insert the proposals. Alternatively, this could be done on a language basis, with a setting, but I think it would be better to do this consistently across languages, without a new setting.

**Comment by jrieken** [comment] 2017-07-11 10:36
https://github.com/Microsoft/vscode/issues/10266

**Closed** 2017-07-11 10:36 UTC
Labels: duplicate, editor, editor-brackets
