### ISSUE TITLE
about vscode: why not working offline give me fix reason what to do give me final solution please

### ISSUE THREAD

**Issue by muhammadYunas** [Microsoft/vscode#66466] opened 2019-01-14 07:32 UTC
Issue Type: <b>Bug</b>

please help me how to fix this issue

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (4.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
bracket-pair-colorizer|Coe|1.0.61
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
code-runner|for|0.9.5
python|ms-|2018.10.1
view-in-browser|qin|0.0.5
LiveServer|rit|5.1.1
vscode-icons|rob|7.28.0

</details>

**Comment by RMacfarlane** [comment] 2019-01-14 16:38
Hi @muhammadYunas, this is a duplicate of https://github.com/Microsoft/vscode/issues/7570. Please try using the  [insiders](https://code.visualstudio.com/insiders/) version of VSCode

**Closed by RMacfarlane** 2019-01-14 16:38 UTC
