### ISSUE TITLE
Terminal left padding is missing in latest insiders

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#136773] opened 2021-11-09 18:21 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Open terminal, left padding for content is gone, terminal contents are flush against the panel
![image](https://user-images.githubusercontent.com/30305945/140981806-fac804e2-256a-4df5-ae55-26093df38e57.png)

Compare to stable:
![image](https://user-images.githubusercontent.com/30305945/140981863-b2ce444d-6ec2-4d7b-be49-233b72f9f044.png)

**Comment by IllusionMH** [comment] 2021-11-09 18:44
/duplicate of #136514

Should be fixed in next Insiders build with #136522 merged few hours ago.

**Closed** 2021-11-09 18:45 UTC
Labels: *duplicate
