### ISSUE TITLE
collapse blocks of code from closing curly braces

### ISSUE THREAD

**Issue by msh-shf** [microsoft/vscode#157598] opened 2022-08-09 05:15 UTC
Hello,
It is a very practical feature to collapse code blocks from closing curly brace like PHPStorm.

![image](https://user-images.githubusercontent.com/12235182/183569713-9e958abf-f452-445c-aae3-140f50a67eb8.png)

**Comment by Jacobify** [comment] 2022-08-09 05:18
this is a very practical feature, since i dont always want to fold my blocks using "fold" key shortcuts. With this feature i dont need to scroll up the beginning of my block every time i need to collapse it.

**Comment by gjsjohnmurray** [comment] 2022-08-09 07:13
Meanwhile you may like to try this extension I wrote.

https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff

**Comment by Jacobify** [comment] 2022-08-09 08:22
> Meanwhile you may like to try this extension I wrote.
> 
> https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff

thanks a lot but this still does not provide what we mentioned. jet brains already did this for their editors as you can see below .

**Comment by msh-shf** [comment] 2022-08-09 08:24
Hi @gjsjohnmurray,
When the cursor is located at the end of the block and I fold the block, the parent block will be folded!

**Comment by RedCMD** [comment] 2022-08-09 08:31
So you want a upwards facing arrow at the bottom of a folding range as well as the top?
what should happen if there are 2 folding ranges that end/start on the same line?
```c
∨   if {
        // code
∧   }


∨   if {
        // code
∧   } else {    // what should happen here? 
        // code
∧  }
```

**Comment by msh-shf** [comment] 2022-08-09 09:19
Hi @RedCMD,
If 2 blocks start/end on the same line, the priority would be with the closing curly bracket, like below:
```
if {...} else {

}
```

**Comment by gjsjohnmurray** [comment] 2022-08-09 10:31
> When the cursor is located at the end of the block and I fold the block, the parent block will be folded!

@msh-shf I suggest you right-click one line higher up then. 

@Jacobify it isn't possible for extensions to achieve what you want, but the extra context menu items are a workaround.

**Comment by gjsjohnmurray** [comment] 2022-08-09 10:36
/duplicate of #60670

@aeschli that issue links to a PR that has been languishing for several years. Can it get some love?

**Comment by Jacobify** [comment] 2022-08-10 06:18
> 

as much as i find the context menu great to use , i still feel like adding an arrow at the end of each block won't be asking for overkill . the down-side arrow is there folding/unfolding blocks, all is need is a up-side arrow doing the same thing only located at the end of the block
![test](https://user-images.githubusercontent.com/39615077/183829142-8b06f1b0-e5c0-4670-8209-12a12cf1b68e.png)

**Comment by Jacobify** [comment] 2022-08-20 03:00
@gjsjohnmurray Hello there . Sorry to mention you here again ,but I just wanted to see if this issue is getting any progress ? Thanks in advance for your time

**Comment by aeschli** [comment] 2022-08-26 13:39
Duplicate of https://github.com/microsoft/vscode/issues/60670

**Closed by aeschli** 2022-08-26 13:39 UTC
