### ISSUE TITLE
Only able to open VSCode from within ~/.config/Code directory

### ISSUE THREAD

**Issue by gillyhl** [microsoft/vscode#95632] opened 2020-04-19 10:46 UTC
Version: 1.44.2
OS: Ubuntu 18.04.4

VSCode fails to open when I run it in any directory outside of ~/.config/Code. I run `code --verbose` to see what is happening and get this output:
```
[main 2020-04-18T18:22:55.750Z] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Code/User'
[main 2020-04-18T18:22:55.752Z] Error: ENOENT: no such file or directory, mkdir
[main 2020-04-18T18:22:55.752Z] Lifecycle#kill()
```

I can work around this at the moment by navigating to `~/.config/Code/` and running `code` there. I can't start code using the Applications Launcher. 

This is after doing a clean install of VSCode using the `.deb` file.

**Comment by chrmarti** [comment] 2020-04-20 11:43
Does `code ~` work?

If not, does `code --user-data-dir ~/tmpvscodeuserdir` work?

**Comment by gillyhl** [comment] 2020-04-20 12:22
`code ~` didn't work, spat out the same error message, but `code --user-data-dir ~/tmpvscodeuserdir` did start up successfully.

**Comment by bpasero** [comment] 2020-04-20 14:27
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by gillyhl** [comment] 2020-04-20 14:44
I get the same results when running with insider build. Have I just mangled something on my file system to get it like this, as it's not been reported by anyone else.

**Comment by bpasero** [comment] 2020-04-20 14:52
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by gillyhl** [comment] 2020-04-20 15:56
The `--verbose` output is similar for the insider's build
```
[main 2020-04-18T18:22:55.750Z] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Code - Insiders/User'
[main 2020-04-18T18:22:55.752Z] Error: ENOENT: no such file or directory, mkdir
[main 2020-04-18T18:22:55.752Z] Lifecycle#kill()
```

**Comment by bpasero** [comment] 2020-04-20 17:36
@gillyhl it looks like on your system VSCode cannot create a user data dir. This is required though, is this a permission problem?

I do not think VSCode can solve this. Closing as such.

**Closed by bpasero** 2020-04-20 17:36 UTC
Labels: needs more info

**Comment by gillyhl** [comment] 2020-04-20 19:44
Oh I've realised what I've done (being an absolute idiot) was writing Kustomize plugins and was setting 'XDG_CONFIG_HOME' env var which was playing havoc with loading Code.

Sorry for the raising the non issue, and thanks for looking at it!
