### ISSUE TITLE
Closing all active editors and collapsing all folders leads to a file being opened

### ISSUE THREAD

**Issue by docbiz** [Microsoft/vscode#68790] opened 2019-02-15 16:14 UTC
I am running 1.13.1 (x64) on Ubuntu 16.04.

I am finding that if I execute "View: Close All Editors" and then "File: Collapse Folders in Explorer" in the command palette, one of the files that I have closed is reopened.

If you can't reproduce this, please let me know and I'll provide more details!

**Comment by frobinsonj** [comment] 2019-02-16 11:05
I can reproduce on Windows 10.

Same issue when toggling side bar visibility:
![2019-02-16_11-02-48](https://user-images.githubusercontent.com/16726902/52898818-968d8780-31da-11e9-8e76-90d35090d57d.gif)

**Comment by yume-chan** [comment] 2019-02-18 06:40
Similar to #52638 where @isidorn, one of the developers, says it's [by design](https://github.com/Microsoft/vscode/issues/52638#issuecomment-399409985):

> However this behavior is designed and we do it explicitly [here](https://github.com/Microsoft/vscode/blob/2ae783aebe5a8c9bdddddbcb6dccbdedd166e348/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L309)

**Comment by docbiz** [comment] 2019-02-18 08:10
Thanks for drawing my attention to the prior issue. It seems to violate the principle of least astonishment for collapsing all folders to open a file, though...

**Comment by JosiahWitt** [comment] 2019-02-21 16:09
I think the issue @docbiz is describing is separate from the issue @frobinsonj is showing in the GIF. The issue in the GIF was fixed (#68132) and is working in the latest insiders build.

**Comment by isidorn** [comment] 2019-02-21 16:54
This is fixed now. Check out insiders tomorrow it will have the fix

**Closed by isidorn** 2019-02-21 16:54 UTC
Labels: feature-request, file-explorer
