### ISSUE TITLE
Debugging of source files with source maps in subfolders work, but not in project root

### ISSUE THREAD

**Issue by Zjaaspoer** [Microsoft/vscode#35566] opened 2017-10-04 10:04 UTC
- VSCode Version: 1.16.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. First create a project with typescript files being compiled to javascript **not in** the project root
2. Configure launch.json like so:
```{
  "configurations": [
    {
      "name": "app",
      "outFiles": [
        "${workspaceRoot}/app/app.js"
      ],
      "program": "${workspaceRoot}/app/app.ts",
      "request": "launch",
      "sourceMaps": true,
      "type": "node"
    }
  ],
  "version": "0.2.0"
}
```
3. The debugging works without the problem
4. Then create a project with typescript files being compiled to javascript **in** the project root
5. Configure launch.json like so:
```{
  "configurations": [
    {
      "name": "app",
      "outFiles": [
        "${workspaceRoot}/app.js"
      ],
      "program": "${workspaceRoot}/app.ts",
      "request": "launch",
      "sourceMaps": true,
      "type": "node"
    }
  ],
  "version": "0.2.0"
}
```
6. Now the debugging doesn't work: `Cannot launch program '/Techs/projects/bleeve/frontend-router/app.ts'; setting the 'outDir or outFiles' attribute might help.`

Reproduces without extensions: Yes

**Comment by isidorn** [comment] 2017-10-04 10:39
@Zjaaspoer can you also reproduce this with vscode insiders https://code.visualstudio.com/Insiders/
What node version are you using?
Do you get the same if you use `"protocol": "inspector"` or `"protocol": "leagcy"` in your `launch.json`

**Comment by Zjaaspoer** [comment] 2017-10-04 11:02
@isidorn thanks for your quick reply
my node version is v8.6.0

when I use `"protocol": "inspector"` I get the same error

when I use `"protocol": "leagcy`I get the error `(node:28571) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.` in my Debug Console, but not the above mentioned error. The program also doesn't run

**Comment by Zjaaspoer** [comment] 2017-10-04 11:03
And just tried the insiders edition. Same problem unfortunately

**Comment by isidorn** [comment] 2017-10-04 12:01
@Zjaaspoer thanks for providing more details. Assigning to @roblourens since this error is coming from node2 debug adapter

**Comment by roblourens** [comment] 2017-10-04 16:46
That particular error should only show when you haven't set `outFiles`, and you clearly have, so I'm not sure what the problem is.

Can you set `"trace": true` in your launch config, then upload the log file from the path it prints in the debug console? Thanks

**Comment by Zjaaspoer** [comment] 2017-10-04 17:45
Gladly!

You can find it [here](https://gist.github.com/Zjaaspoer/ca97a466c9171cae9de67ddcf1cc96cb)

**Comment by roblourens** [comment] 2017-10-04 18:01
Thanks. Your sourcemaps have paths like `"/app.ts"`. That is currently interpreted as an absolute path, but I guess if it doesn't exist there I could fall back on resolving it relative to the sourcemap's location.

What tools are you using to build your ts?

**Comment by Zjaaspoer** [comment] 2017-10-04 20:42
I'm building in webpack, with the `awesome-typescript-loader`, which eventually relies on `tsc` I guess?

**Comment by roblourens** [comment] 2017-10-04 21:21
Is this a project you can share? Or can you share your webpack config?

**Comment by Zjaaspoer** [comment] 2017-10-05 09:01
Good morning!

[Here](https://gist.github.com/Zjaaspoer/1b376eaf5954e71483cd3fc41cd08cc5) is my webpack.config.js (a bit of a summary, eg. I've got all my node_modules packages listed as externals so they don't get included in the build)

[Here](https://gist.github.com/Zjaaspoer/11b8c0c337a673fc17ce38458b0b5b2c) I've also uploaded my tsconfig.json as I thought you might be interested in that one too.

**Comment by roblourens** [comment] 2018-09-12 18:37
Sorry for dropping out, I don't know if this is still a problem, but I don't have an answer other than, source map paths should be correct. 

sourceMapPathOverrides can be used to map incorrect paths to correct ones. If some library is putting out incorrect paths, hopefully we can have them fix it upstream.

**Closed by roblourens** 2018-09-12 18:37 UTC
Labels: debug, feature-request
