### ISSUE TITLE
Closing backtick is not deleted (in JavaScript)

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#140772] opened 2022-01-15 11:54 UTC
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.63.2 (Insiders 1.64.0)
- OS Version: macOS 12.1 (Monterey)

Steps to Reproduce:
1. On a JS file, write a backtick between the parenthesis in a `console.log()`
2. Notice the closing backtick shows up correctly and the cursor between them: ```console.log(`|`)```
3. Delete the first backtick
4. Notice the closing backtick was not deleted: ```console.log(|`)```

**Comment by joeljose350** [comment] 2022-01-15 15:15
I am unable to reproduce this issue on my Windows 11 machine.

![2022-01-15 19-33-11](https://user-images.githubusercontent.com/53969297/149626877-8d06cfb6-8039-47c8-b746-ecad0a13a49c.gif)

**Comment by andrecasal** [comment] 2022-01-15 15:27
Issue still presents itself on macOS.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/22457463/149627315-a0b5e7e6-9688-457b-8655-faea4fe051aa.gif)

**Comment by joeljose350** [comment] 2022-01-15 19:07
Since the closing quote does not appear when you enter the opening one, I think the following setting is misconfigured.

![image](https://user-images.githubusercontent.com/53969297/149634719-520317f0-78d5-4a00-9184-d2143ce36ede.png)

Can you confirm if this setting is set to `languageDefined`?

**Comment by andrecasal** [comment] 2022-01-15 22:08
I believe it's correct.
<img width="771" alt="Screen Shot 2022-01-15 at 22 04 42" src="https://user-images.githubusercontent.com/22457463/149639109-b38e85bc-e7c0-484c-b0b1-a27eaa9fa49b.png">

Maybe it's because I have a Portuguese keyboard (we have words with accents like "às" which means "ace") and both backticks show up at once.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/22457463/149639189-eb2054f7-2f45-44c7-af9d-5d2bcf12519c.gif)

**Comment by alexdima** [comment] 2022-01-26 20:30
@andrecasal I have installed the Portuguese keyboard layout, but I'm having trouble reproducing. What precise keys are you pressing? Here I press <kbd>shift</kbd>+<kbd>BracketRight</kbd> followed by <kbd>Space</kbd>, which then inserts two ` `` `. Pressing <kbd>Backspace</kbd> then removes both backticks. Please also try with the latest Insiders:

https://user-images.githubusercontent.com/5047891/151242051-dd19bf4a-d4db-49aa-bff4-d9286349345a.mp4

**Closed** 2022-02-03 11:25 UTC
Labels: needs more info
