### ISSUE TITLE
Integrated terminal wrapping issue

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8588] opened 2016-06-30 19:40 UTC
- VSCode Version: insiders 6/30
- OS Version: MacOs

Everything still OK:
![screen shot 2016-06-30 at 12 37 47 pm](https://cloud.githubusercontent.com/assets/4674940/16501710/9aec73e2-3ebf-11e6-8178-d5532483a708.png)

Now enter `c` and the prompt string is wrapped:
![screen shot 2016-06-30 at 12 39 30 pm](https://cloud.githubusercontent.com/assets/4674940/16501745/cc415200-3ebf-11e6-8208-3f61cc673a54.png)

**Comment by Tyriar** [comment] 2016-07-01 19:30
@kieferrm do you have any terminal or font family/size/lineheight settings in settings.json? Can you also copy and paste the output of `echo $PS1`

**Comment by kieferrm** [comment] 2016-07-01 19:43
No special settings. Here is the output: `\s-\v\$`

**Comment by Tyriar** [comment] 2016-08-10 01:18
Duplicate of https://github.com/Microsoft/vscode/issues/9902

**Closed by Tyriar** 2016-08-10 01:18 UTC
Labels: bug, integrated-terminal, needs more info
