### ISSUE TITLE
Reverting change from quick diff provider does not work

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172059] opened 2023-01-23 19:28 UTC
1. Make changes in git repo
2. From gutter, open quick diff
3. Click revert button
4. :bug: nothing happens, see error message below (no errors in dev tools console log)

![image](https://user-images.githubusercontent.com/30305945/214131501-d8f10ea6-5d9f-4dcd-927c-18505260d72e.png)

**Comment by lszomoru** [comment] 2023-01-23 19:48
Duplicate of https://github.com/microsoft/vscode/issues/171863.

**Closed by lszomoru** 2023-01-23 19:48 UTC
