### ISSUE TITLE
TSServer crash

### ISSUE THREAD

**Issue by ttony** [Microsoft/vscode#13335] opened 2016-10-07 08:40 UTC
- VSCode Version: 1.6.0-insider and 1.5.3
- OS Version: Windows 7

Steps to Reproduce:
1. start VS Code IDE
2. open the typescript file, open Output Panel for Typescript:

[Info  - 4:39:12 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:13 PM] TSServer exited with code: 3221226356
[Info  - 4:39:13 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:14 PM] TSServer exited with code: 3221226356
[Info  - 4:39:14 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:15 PM] TSServer exited with code: 3221226356
[Info  - 4:39:15 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:16 PM] TSServer exited with code: 3221226356
[Info  - 4:39:16 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:17 PM] TSServer exited with code: 3221226356
[Info  - 4:39:17 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:18 PM] TSServer exited with code: 3221226356
[Info  - 4:39:18 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:19 PM] TSServer exited with code: 3221226356
[Info  - 4:39:19 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:19 PM] TSServer exited with code: 3221226356
[Info  - 4:39:19 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:20 PM] TSServer exited with code: 3221226356
[Info  - 4:39:20 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:21 PM] TSServer exited with code: 3221226356
[Info  - 4:39:21 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:22 PM] TSServer exited with code: 3221226356
[Info  - 4:39:22 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:23 PM] TSServer exited with code: 3221226356
[Info  - 4:39:23 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Error - 4:39:24 PM] TSServer exited with code: 3221226356
[Info  - 4:39:24 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\tsserver.js

any help?

**Comment by Tyriar** [comment] 2016-10-07 18:01
Some questions:

- Any details on your workspace?
- What is in the dev tools console when this happens (Help > Toggle Developer Tools)
- Is it 100% reproducible? Have you tried with a different folder/file?

**Comment by dbaeumer** [comment] 2016-10-10 12:26
@ttony could you share your workspace. This would ease tracking this down.

**Comment by dbaeumer** [comment] 2016-11-15 17:54
Closing since no response have been received in 10 days. Please ping with additional information can be provided.

**Comment by slyadams** [comment] 2017-02-17 10:59
I am also experiencing this problem:
```

[Info  - 10:27:35] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Error - 10:48:36] TSServer exited with code: 3221226356
[Info  - 10:48:36] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
```

Even though the last line implies the language service is still running, it isn't actually functional in the interface. Most likely this is related to the fact I'm using sshfs to mount my workspaces.

**Comment by dbaeumer** [comment] 2017-02-17 16:58
@mjbvz FYI.

Reopening

**Comment by mjbvz** [comment] 2017-02-17 19:52
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/13874 and https://github.com/Microsoft/TypeScript/issues/13997 . Current code insiders has a fixed version of TypeScript

**Closed by mjbvz** 2017-02-17 19:52 UTC
Labels: duplicate, External, typescript

**Comment by slyadams** [comment] 2017-02-19 00:14
Note: Using 1.10.0-insider and TypeScript 2.2.1-insiders.20170216 getting the error message

The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

With constantly generating errors in console

```
[Error - 00:13:51] TSServer exited with code: 3221226356
[Info  - 00:13:51] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
```

I can only assume this is due to workplace vs embedded typescript versions?

**Comment by mjbvz** [comment] 2017-02-22 01:37
@slyadams Those error codes are what we expect for https://github.com/Microsoft/TypeScript/issues/13874 and https://github.com/Microsoft/TypeScript/issues/13997 . Please try out the latest insiders build and make sure you are using TS 2.2.1-insiders.20170217. If you still see this crash, open a new issue and we can investigate further.

Thanks

**Comment by slender9168** [comment] 2017-05-13 11:25
I've had the same issue & I this is how i solved it 

https://github.com/Microsoft/vscode/issues/26594
