### ISSUE TITLE
Jupyter Color Scheme Broken For Remote 

### ISSUE THREAD

**Issue by AnakinShieh** [microsoft/vscode#206921] opened 2024-03-05 21:28 UTC
Type: <b>Bug</b>

Both in windows and macs, when connecting to a remote server/wsl and using jupyter notebook, the color scheme for jupyter only works for the past existing codes but not new written one.

Such issues don't appear on python script file.

Some photos example:

<img width="1026" alt="image" src="https://github.com/microsoft/vscode/assets/11189830/4dfbaa8c-cf5e-48cb-94d2-f5e5b3dc7870">

updated:

It seems that the insider preview version doesn't have this bug.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:51.279Z)
OS version: Darwin arm64 23.2.0
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (0.70GB free)|
|Process Argv|--crash-reporter-id 8fca4627-aebc-4903-b62d-261e3dedd8dd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 42.200.124.45|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|Memory (System)|117.92GB (114.98GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
stata-enhanced|kyl|1.6.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
pdf|tom|1.2.2
copilot|Git|1.171.0
copilot-chat|Git|0.13.0
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:30979542
d34g3935:30971562
a89i1917:30973842
bg6jg535:30979843
ccp2r3:30958157
dsvsc020:30976470
666c4381:30973075

```

</details>

**Comment by li-naiju** [comment] 2024-03-06 05:19
After uprading to 1.87.0 today, I met same problem when coding on WSL2
Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by ODAncona** [comment] 2024-03-06 07:48
[Are you ready for this ?](https://www.youtube.com/watch?v=DJ6CcEOmlYU)

![image](https://github.com/microsoft/vscode/assets/71207824/d084c647-1616-4646-854f-1a1cc80db2ae)

Since the update this morning

```txt
Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621
```

Connected on a remote server with ssh, in a jupyter notebook, with `Pylance` as a linter 

Thank you !

**Comment by UrkoAT** [comment] 2024-03-06 08:41
Im encountering the same problem. Also, I was debugging and found this in the python language server Output everytime I change something on a notebook. Maybe is relevant:
```
2024-03-06 09:35:42.609 [info] [Info  - 9:35:42 AM] (3965183) Indexing finished(3).
2024-03-06 09:36:44.513 [info] [Info  - 9:36:44 AM] (3965183) Auto-excluding /home/[REDACTED]/env
2024-03-06 09:36:44.521 [info] [Info  - 9:36:44 AM] (3965183) Found 35 source files
2024-03-06 09:37:45.265 [info] [Error - 9:37:45 AM] (3965183) Received change text document command for closed file file:///home/[REDACTED].ipynb.py#X14sdnNjb2RlLXJlbW90ZQ%3D%3D
2024-03-06 09:37:45.579 [info] [Error - 9:37:45 AM] (3965183) Received change text document command for closed file file:///home/[REDACTED].ipynb.py#X14sdnNjb2RlLXJlbW90ZQ%3D%3D
2024-03-06 09:37:45.579 [info] [Error - 9:37:45 AM] (3965183) Received change text document command for closed file file:///home/[REDACTED].ipynb.py#X14sdnNjb2RlLXJlbW90ZQ%3D%3D
2024-03-06 09:37:45.598 [info] [Error - 9:37:45 AM] (3965183) Received change text document command for closed file file:///home/[REDACTED].ipynb.py#X14sdnNjb2RlLXJlbW90ZQ%3D%3D
```

And this on Main everytime I reaload the window:
```
2024-03-06 09:30:57.784 [info] Extension host with pid 23658 exited with code: 0, signal: unknown.
2024-03-06 09:30:57.791 [error] [UtilityProcessWorker]: terminated unexpectedly with code 15, signal: unknown
2024-03-06 09:30:57.791 [error] [UtilityProcess id: 1, type: fileWatcher, pid: 23688]: crashed with code 15 and reason 'killed'
```

**Comment by marcoabrate** [comment] 2024-03-06 10:03
same problem here
```
Version: 1.87.0 (Universal)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
```
host: macos 14.2.1 (23C71)
server: Pop!_OS 22.04 LTS

and a cute picture
![Screenshot 2024-03-06 at 10 59 22](https://github.com/microsoft/vscode/assets/43387597/f3a42027-e9f6-42f5-b406-eacecb523d0e)

**Comment by XiaomoWu** [comment] 2024-03-06 12:07
Same here. Haven't confirmed if the Insider Preview will fix the issue.

<img src="https://github.com/microsoft/vscode/assets/26643668/e517bd03-c2d7-48fd-a667-de802262549a" width="600">

<img src="https://github.com/microsoft/vscode/assets/26643668/a46ff34d-53c5-47bc-adf9-9674c2bcd926" width="300">


VS Code: 1.87.0
Pylance: v2024.2.3
Python Extension: v2024.2.1
Jupyter Extension: v2024.2.0
Client: MacOS 14.3.1
Host: Ubuntu 22.04 (connected via SSH)

**Comment by svher** [comment] 2024-03-06 12:11
https://github.com/microsoft/vscode/issues/206487

**Comment by DonJayamanne** [comment] 2024-03-06 20:31
Duplicate of https://github.com/microsoft/vscode/issues/206487

**Closed by DonJayamanne** 2024-03-06 20:31 UTC
