### ISSUE TITLE
Support to open multiple folders in one window

### ISSUE THREAD

**Issue by sumonto** [Microsoft/vscode#5869] opened 2016-04-26 23:08 UTC
- VSCode Version:1.0
- OS Version: OS X

Steps to Reproduce:

1. Open a git folder in explorer
2. Open a 2nd one, the first one is closed.

VS Code Explorer should support multiple Git folders.

**Comment by bpasero** [comment] 2016-04-27 19:19
Closing as duplicate of #2686

**Comment by bpasero** [comment] 2016-04-27 19:20
https://github.com/Microsoft/vscode/issues/396

**Closed by bpasero** 2016-04-27 19:20 UTC
Labels: feature-request, workbench
