### ISSUE TITLE
[WelcomeUX] Improve welcome screen on smaller screens

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18911] opened 2017-01-20 18:55 UTC
Testing #18091

![image](https://cloud.githubusercontent.com/assets/2193314/22161332/c1b76c86-defe-11e6-9673-40b655e3b89b.png)

**Comment by bgashler1** [comment] 2017-01-20 22:07
Is the string of the filename too long?

@chrmarti not much I can do with CSS, perhaps a programmatic truncation of the middle of the string if the string size is more than 81 characters (which seems to be about all we can comfortably fit) in the max welcome screen size of 1200px that I'm now using.

We probably can't do this this milestone.

**Comment by Tyriar** [comment] 2017-01-20 22:26
@bgashler1 actually talking about the height on this one, "Visual Studio Code" is cut off. A lot of laptops would probably hit this experience, especially if the panel is open.

**Comment by bgashler1** [comment] 2017-01-20 22:33
@Tyriar I can't reproduce.  What platform are you testing on?  Are you seeing this issue still when using the correct font (to test, remove the `font-family: "Segoe UI"` rule from the DOM inspector on the class `welcomePage`, or pull the latest).

**Comment by Tyriar** [comment] 2017-01-20 22:41
@bgashler1 Ubuntu 16.10. Imagine a small laptop, this is what you could be greeted with:

![image](https://cloud.githubusercontent.com/assets/2193314/22167974/7a524594-df1e-11e6-904e-e028853fb010.png)

See the buttons and test is cut off on both directions as the page isn't responsive on the height of the page.

**Comment by bgashler1** [comment] 2017-01-20 22:56
This will require some logic from @chrmarti to enable this.  There is a class we can listen to called `no panel` that is an ancestor of the welcomePage.  However, we can't get the size of the panel or adjust to it with a media query.

This seems to be an edge case, since I don't think people will likely use a panel immediately upon the Welcome page.  However, with some logic changes we could improve this.

**Comment by Tyriar** [comment] 2017-01-20 23:00
@bgashler1 the recent/open shortcuts are meant to make it generally useful so the panel would have a good change of showing on 2nd+ launch.

**Comment by chrmarti** [comment] 2017-01-21 00:48
@bgashler1 I have pushed a change turning the previous media query into a class selector earlier today. There is just one class currently, but we can easily add to that.

**Comment by chrmarti** [comment] 2017-02-02 21:35
Much improved by the above mentioned change, scrollbars and the updated layout. Closing.

**Closed by chrmarti** 2017-02-02 21:35 UTC
