### ISSUE TITLE
clear the 'multi cursor' please

### ISSUE THREAD

**Issue by wu67** [Microsoft/vscode#37115] opened 2017-10-30 04:24 UTC
- VSCode Version: 1.17.2
- OS Version: Mac OS 10.13

The 'multi cursor' work when i press 'ctrl + alt + up/down'(my key bindings). But it doesn't work with mouse.

Steps :

1. Holding the 'alt' key
1. Holding the 'main' key(in mouse) and drag the mouse cursor vertically, and it's behavior is same as holding the 'command' key at `step 1`. It is just a 'multi line', not 'multi cursor'!

**Comment by alexandrudima** [comment] 2017-10-30 09:28
@wu67 Not sure what you mean.

You can get box selection via `shift+alt+` and mouse click:
![37115](https://user-images.githubusercontent.com/5047891/32163606-1d4eed84-bd5d-11e7-95a0-901eb0b4415d.gif)

**Comment by wu67** [comment] 2017-10-30 09:53
@alexandrudima 
emmmmm, now we have 2 way get those selection
- holding alt and then click each point
- holding alt + shift ,then drag the cursor

i want to merge the 2 way ----> holding alt key, and then select multi point by drag or click

**Comment by alexandrudima** [comment] 2017-10-30 09:55
So you would like to change the modifier keys for box selection from `shift+alt+` to `alt+` ?

**Comment by wu67** [comment] 2017-10-30 09:57
@alexandrudima Yes!!!

**Comment by alexandrudima** [comment] 2017-10-30 10:00
Thank you, duplicate of #3130

**Closed by alexandrudima** 2017-10-30 10:00 UTC
Labels: editor, editor-multicursor, needs more info
