### ISSUE TITLE
升级之后已三次出现无响应

### ISSUE THREAD

**Issue by xiyionxiong** [Microsoft/vscode#63112] opened 2018-11-14 09:47 UTC
Issue Type: <b>Bug</b>

如标题。
开发一段时间之后，出现无响应的情况。 必须将vscode 重启才能再使用。

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|-psn_0_7321339|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
solis|caz|1.1.0
vscode-tomcat|ada|0.11.0
Bookmarks|ale|9.2.0
QML|bbe|1.0.0
ng-zorro-vscode|cip|2.4.1
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
vscode-ant-design-pro|han|0.1.0
beautify|Hoo|1.4.7
rest-client|hum|0.20.3
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.12.0
intellij-idea-keybindings|k--|0.2.28
vscode-sciter|lon|0.0.2
Kotlin|mat|1.7.0
Angular-BeastCode|Mik|7.0.15
vscode-language-pack-zh-hans|MS-|1.29.2
cpptools|ms-|0.20.1
Go|ms-|0.7.0
debugger-for-chrome|msj|4.11.0
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
seti-icons|qin|0.1.3
remote-vscode|raf|1.1.0
java|red|0.33.0
bash-debug|rog|0.3.3
jinjahtml|sam|0.4.0
bash-beautify|sha|0.1.1
background|sha|1.1.19
vscode-nginx|sha|0.6.0
stylelint|shi|0.46.1
pdf|tom|0.4.1
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-spring-initializr|vsc|0.4.2
vscode-import-cost|wix|2.9.0
ReactSnippets|xab|2.2.1
local-history|xyz|1.7.0
file-size|zh9|0.1.3
pyqt-integration|zho|0.2.0
html-css-class-completion|Zig|1.17.1

(3 theme extensions excluded)

</details>

**Comment by joseph1125** [comment] 2018-11-14 15:10
Use English next time, duplicate of #62970

**Closed** 2018-11-15 12:55 UTC
Labels: *duplicate, freeze-slow-crash, new release
