### ISSUE TITLE
Organize Imports does a bad job at organizing when License header is present at the top of the file

### ISSUE THREAD

**Issue by amarzavery** [Microsoft/vscode#48142] opened 2018-04-18 15:36 UTC
**Before**
```js
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

import * as rhea from "rhea";
import * as debugModule from "debug";
import * as uuid from "uuid/v4";
import * as rheaPromise from "./rhea-promise";
import * as rpc from "./rpc";
import { translate, ErrorNameConditionMapper } from "./errors";
import * as Constants from "./util/constants";
import { EventEmitter } from "events";
import { ReceiveOptions, EventData, EventHubsError } from ".";
import { ConnectionContext } from "./connectionContext";
import { defaultLock, Func } from "./util/utils";

const debug = debugModule("azure:event-hubs:receiver");
```
**After**
```js
import * as debugModule from "debug";
import { EventEmitter } from "events";
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
import * as rhea from "rhea";
import * as uuid from "uuid/v4";
import { EventData, EventHubsError, ReceiveOptions } from ".";
import { ConnectionContext } from "./connectionContext";
import { ErrorNameConditionMapper, translate } from "./errors";
import * as rheaPromise from "./rhea-promise";
import * as rpc from "./rpc";
import * as Constants from "./util/constants";
import { Func, defaultLock } from "./util/utils";

const debug = debugModule("azure:event-hubs:receiver");
```

**Comment by andy-ms** [comment] 2018-04-18 15:37
Duplicate of Microsoft/TypeScript#22731 (organize imports is a TypeScript feature, you had the right repo the first time)

**Comment by amarzavery** [comment] 2018-04-18 15:38
Ohh. I thought this was a vscode feature.

**Closed** 2018-04-18 15:39 UTC
Labels: javascript
