### ISSUE TITLE
Debugger icon promotes insect extinction a request to change it.

### ISSUE THREAD

**Issue by ex1tium** [microsoft/vscode#87548] opened 2019-12-22 01:18 UTC
I'm deeply troubled about how the various debugger icons seem to promote animal cruelty and insect extinction that is currently happening around the world. To further educate yourself about this ongoing but rarely spoken crisis here are some scientific evidence and news articles. 

- Insect apocalypse: German bug watchers sound alarm - https://phys.org/news/2019-07-insect-apocalypse-german-bug-watchers.html
- Immediate, science-based community action can stop insect decline - https://phys.org/news/2019-06-science-based-action-insect-decline.html
- Bee populations in trouble following EPA pesticide decision - https://phys.org/news/2019-06-bee-populations-epa-pesticide-decision.html
- Why insect populations are plummeting—and why it matters - https://www.nationalgeographic.com/animals/2019/02/why-insect-populations-are-plummeting-and-why-it-matters/
- The Insect Apocalypse Is Here
What does it mean for the rest of life on Earth? -https://www.nytimes.com/2018/11/27/magazine/insect-apocalypse.html

Remember that your food supply is wholly dependent on insects doing pollination of the crops you consume. Therefore this is an issue that should touch each one of you in the community.

Now about the icons.

![](https://i.imgur.com/mYulZ3M.png)

![](https://i.imgur.com/sJxW61N.png)

The first example shows a beetle being crossed out. Now this symbolism is clearly an example of promoting genocide. I would even go as far to compare it to yellow stars the Jews were forced to pin on their clothing during Nazi rule in Germany. 

The second example shows a beetle being poked with an arrow head in order to torture it. 

I can't believe one of the largest companies in the world stays silent about the issue and even promotes an anti-bug attitude while an entire class of animals in in danger. I'm a grandson of a bee keeper and this whole thing is deeply offensive for me as it should be for everyone. I hope Microsoft reacts fast to this issue before PETA gets involved.

As a community we need to find a proper debugger icon as soon as possible. I welcome discussion about alternate icons.

Recently I have adopted a style of developing that promotes bugs instead of squashing them. I truly believe this is a better approach that will create more job opportunities for all developers. And when those bug reports start to pile up in your repos, don't forget to link the evidence for the ongoing bug extinction.

**Comment by docyx** [comment] 2019-12-22 04:34
Joke or not, the fact that you even took the time to type this is embarrassing.

**Comment by ex1tium** [comment] 2019-12-22 10:23
> Joke or not, the fact that you even took the time to type this is embarrassing.

Oh... I thought the [policy](https://github.com/microsoft/vscode/issues/87440) is  same for everyone. If a one guy feels offended about Santa hat I think I got right to be offended/worried about this and demand an investigation about the issue. After all in todays wicked world it's okay to be offended about anything it seems. And no, this was not joke. I want equal justice for all.

**Comment by amis92** [comment] 2019-12-22 13:10
I had a great laugh, thank you @ex1tium.

But also, deeply - I do believe that there's a point to be made and this issue is a well-done attempt. As we strive to be tolerant, we cannot tuck our heads on the slightest signal of someone being offended by anything. One *chooses* to be offended, not the other way around. Why is religion such a *snowflake* for offensiveness? People with no religious views could be offended because they *don't get the chance* to report religious-offensive content; maybe they'd like to join in the fun (inclusiveness!).

**Comment by brlebtag** [comment] 2019-12-22 17:55
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by xternal7** [comment] 2019-12-23 00:09
Since the author didn't provide any ideas, here's a mockup:

![mockup](https://user-images.githubusercontent.com/12505802/71329071-69a7b080-2520-11ea-823b-80f9216a6661.png)

Of course, this needs to be reviewed by sensitivity teams. While most people might understand that magnifying glass signifies taking a closer look at a bug instead of squashing or torturing it, some may mistake the icon as promoting frying bugs by using a magnifying glass or sunlight.

**Comment by shogerr** [comment] 2019-12-23 07:08
Consider leaving the bugs in VS Code. The act of removing and squashing the bugs themselves from source promotes, and inspires violence against bugs in the corporeal world.

I would further suggest that a feature be added to help increase the propagation of bugs within the source as to position MS as an industry leader in the domain of insect rights.

**Comment by alexandernst** [comment] 2019-12-23 09:38
I guess this is what happens when you start honouring random requests that don't make any sense at all... (yeah, it was *just a hat*, get over it).

**Comment by egamma** [comment] 2019-12-23 14:52
closing as a duplicate of https://github.com/microsoft/vscode/issues/87376. 
Please see also this comment https://github.com/microsoft/vscode/issues/87376#issuecomment-568041363.

**Closed** 2019-12-23 14:53 UTC
Labels: *duplicate

**Comment by ex1tium** [comment] 2019-12-26 14:45
> Since the author didn't provide any ideas, here's a mockup:
> 
> ![mockup](https://user-images.githubusercontent.com/12505802/71329071-69a7b080-2520-11ea-823b-80f9216a6661.png)
> 
> Of course, this needs to be reviewed by sensitivity teams. While most people might understand that magnifying glass signifies taking a closer look at a bug instead of squashing or torturing it, some may mistake the icon as promoting frying bugs by using a magnifying glass and sunlight.

After returning from holidays and finding this issue closed I'd still like to comment that this style of icon would be appropriate for a new debugger icon. Thanks for the discussion that ensued and I hope everyone enjoyed their holidays what ever they may have celebrated!

**Comment by lviggiano** [comment] 2019-12-29 21:49
Please don't hate insect, they have every right to live. 
I propose to use an icon with an insect and a lovely heart <3

**Comment by therealkungfury** [comment] 2020-01-13 16:53
See Microsoft... we're all touched in the head. Some more than others but still it is a fact.

While I'm not in the mood to articulate my answer as well as my sarcastic comrades before me I would still like to throw my gasoline can into the blazing inferno.
People are idiots, a sad fact of life on our little pretty blue ball hauling ass through the infinite vastness of space, time and all dimensions in between.

This does not mean you can't have a spine. Please offend people who are easily offended. It builds character.

Let's all be as offensive as we can so we can go back to the good ol days of beer commercials with busty babes and not this soy boy light beer BS we have now. And I want people to smoke in movies more, so I could see what I'm missing.

Maybe for cancer awareness day, you can stick a ciggy in that gear icon? Or at least give it lung cancer so it will not work half the time or something. Use your imagination!
