### ISSUE TITLE
bracket pair colorization horizontal guides display bug when opening bracket is at the end of a wrapped line

### ISSUE THREAD

**Issue by jc9108** [microsoft/vscode#136474] opened 2021-11-05 00:01 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0
- OS Version: ![image](https://user-images.githubusercontent.com/31039318/140435730-16f935c0-9ce4-4395-ae9f-d0821fea03b4.png)

Steps to Reproduce:

1. `"editor.wordWrap": "on"`
2. `"editor.bracketPairColorization.enabled": true`
3. `"editor.guides.bracketPairs": "active"`
4. bracket pair colorization horizontal guides display bug when opening bracket is at the end of a wrapped line
![image](https://user-images.githubusercontent.com/31039318/140436415-52ea7c7d-4b38-43ef-9e17-20d0bfb14282.png)

**Comment by nataliemckee** [comment] 2021-12-13 01:22
I have been working on this issue and isolated the buggy lines of code to lines 501 - 512 of of vscode/src/vs/editor/common/model/guidesTextModelPart.ts

The issue is that each part of a wrapped line is treated as its own line when when a the horizontal line is being added. This results in each wrapped part having an horizontal line up to the start of the opening bracket, rather than just the part of the wrapped line that contains the opening bracket. 

My issue is that I cannot tell if a line is wrapped or not based on the variables I see when debugging-- is there a way to distinguish a wrapped line from an unwrapped line that I do not know of?

**Comment by hediet** [comment] 2021-12-13 10:03
> is there a way to distinguish a wrapped line from an unwrapped line that I do not know of?

I am very sure that there is a way.
But I'm very sure this also has to addressed in the view model. The text model is not aware of wrapped lines (and `guidesTextModelPart` is about the text model).
In the screenshot, if it was not wrapped, it would be correct, so this should not be fixed in the text model.

**Comment by hediet** [comment] 2022-04-01 07:00
Fixed in next insiders:

![image](https://user-images.githubusercontent.com/2931520/161211945-ddb9a12e-552c-4e05-b95c-a89cf080b353.png)

**Closed** 2022-04-01 07:27 UTC
Labels: bug, bracket-pair-guides

**Comment by hediet** [comment] 2022-04-27 12:25
@jc9108 it would be awesome if you could verify that this feature works in the latest vscode insider build!

**Comment by jc9108** [comment] 2022-04-28 03:43
can confirm it works in insiders::
![image](https://user-images.githubusercontent.com/31039318/165671562-b0c347a4-1896-4321-b1f7-9b6ecc315a59.png)

thank you for the good work!
