### ISSUE TITLE
Terminal: Text color error

### ISSUE THREAD

**Issue by clitetailor** [Microsoft/vscode#22963] opened 2017-03-21 16:56 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|vscode-theme-onedark|akamud|1.3.1|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|theme-jsfiddle-like-syntax-vscode|davidmart|0.0.6|
|EditorConfig|EditorConfig|0.6.2|
|Theme-Amber|gerane|0.0.2|
|vscode-ghc-mod|hoovercj|1.2.0|
|hopscotch|idleberg|0.1.4|
|spacegray-vscode|ionutvmi|1.1.4|
|theme-material-theme|jprestidge|1.0.1|
|language-haskell|justusadam|2.1.0|
|cpptools|ms-vscode|0.10.4|
|Theme-MaterialKit|ms-vscode|0.1.1|
|material-icon-theme|PKief|2.0.1|
|language-stylus|sysoev|1.6.0|
|ayu|teabyii|0.2.1|;

---

Steps to Reproduce:

1. 
![image](https://cloud.githubusercontent.com/assets/16368559/24158938/5740d998-0e90-11e7-92cf-f710e3c7c97d.png)
![image](https://cloud.githubusercontent.com/assets/16368559/24159529/d7d88348-0e91-11e7-9cf4-3bf092f0d7de.png)

2.
![image](https://cloud.githubusercontent.com/assets/16368559/24158981/7a23d5fa-0e90-11e7-9f28-acaf502ddbc1.png)

Everytime i run mocha or npm, it results in very bad color output, so i try to run it on cmd or powershell, everything is still ok. i have changed the color theme and font-family but it does not work

**Comment by Tyriar** [comment] 2017-03-22 19:30
The contrast on the cmd window at the end is terrible?

Regardless, it looks like mocha is making the background yellow. Do you have any settings in your User settings.json file?

**Comment by clitetailor** [comment] 2017-03-23 12:28
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 16,
	"editor.fontLigatures": true,
    "editor.fontFamily": "Fira Code",
    
	"editor.quickSuggestions": true,

	"typescript.check.tscVersion": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\system32\\cmd.exe",

    "languageStylus.useSeparator": false,

	"workbench.iconTheme": "material-icon-theme",
	"workbench.editor.showTabs": false,

    "files.exclude": {
        "**/.git": false
	},
	"editor.minimap.renderCharacters": false,
	"editor.minimap.enabled": true,
	"editor.formatOnType": true,
	"editor.formatOnPaste": true,
	"editor.cursorBlinking": "blink",

    "editor.insertSpaces": false,
	"editor.cursorStyle": "block",
    "editor.wrappingIndent": "same",
	"editor.renderIndentGuides": true,
	"editor.renderWhitespace": "none",
	"window.zoomLevel": 0,
	"workbench.colorTheme": "JSFiddle-like-syntax-vscode"
}

**Comment by clitetailor** [comment] 2017-03-23 12:47
It's marked as xterm-bg-color-11
![image](https://cloud.githubusercontent.com/assets/16368559/24248322/70282f7a-1001-11e7-87cf-9fb953d9e8f6.png)

**Comment by Tyriar** [comment] 2017-03-23 20:34
What's this `$Yeild` thing in your prompt?

**Comment by clitetailor** [comment] 2017-03-24 11:02
it's just the command prompt. sorry about that! 😃

**Comment by Tyriar** [comment] 2017-03-24 17:25
How did you set that up? It's possible that is related to this, I notice the line in between the regular prompt and $Yeild has a yellow background in one of the screenshots.

**Comment by clitetailor** [comment] 2017-03-24 17:33
I just change the environment variable. But when i change it back to default cmd prompt or even delete the variable, it still remains error!
![image](https://cloud.githubusercontent.com/assets/16368559/24306092/e67955e6-10f1-11e7-8c6f-c8a078894b32.png)
![image](https://cloud.githubusercontent.com/assets/16368559/24306206/5a747354-10f2-11e7-8fb6-149ea2a51fad.png)

**Comment by Tyriar** [comment] 2017-03-29 21:00
Maybe try updating mocha? Have you experienced this with any other programs other than mocha?

**Comment by clitetailor** [comment] 2017-03-30 06:16
Yeap, it usually happens when webpack or npm logs out some warnings or errors

**Comment by clitetailor** [comment] 2017-03-30 06:27
I think that it change the background color when it logs warrning but somehow it forgets to turn back to normal
Or maybe it can not receive the correct signal from the external terminal

**Comment by clitetailor** [comment] 2017-05-30 10:15
Yeah, i've just found an interesting info. That color comes from cmd default properties. When i change the background color back to black, everything is ok! ;v
![image](https://cloud.githubusercontent.com/assets/16368559/26578730/4aca2c58-455b-11e7-918c-505efa81628a.png)

**Comment by Tyriar** [comment] 2017-05-31 19:58
@clitetailor good to know, closing as designed then as there's no way we can determine cmd's color scheme.

**Closed by Tyriar** 2017-05-31 19:58 UTC
Labels: integrated-terminal, needs more info
