### ISSUE TITLE
CSS: do not show origin of warning

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62159] opened 2018-10-30 14:54 UTC
Refs: https://github.com/Microsoft/vscode/issues/62049

Have the following css:
```css
a {
	isidor: 5;
}
```

Notice the hover. There is too much redundant information here, why do we show [css.lint.unknownProperties] and [unkownProperties] at the end?
I would not expect this to be rendered as it feels like an implementaiton detail to me.

![screenshot 2018-10-30 at 15 52 59](https://user-images.githubusercontent.com/1926584/47727050-01cb4200-dc5c-11e8-9ac1-8606f0871bbc.png)

**Comment by octref** [comment] 2018-10-31 20:40
This is a regression on the diagnostics display.

1.28:

![image](https://user-images.githubusercontent.com/4033249/47816972-b83d2e80-dd11-11e8-92ea-97763e51688e.png)

Insiders:

![image](https://user-images.githubusercontent.com/4033249/47817088-00f4e780-dd12-11e8-8b0c-2d45c561fbf4.png)

In both case, the diagnostics returned are:

```js
const diagnostics = {
  code: "unknownProperties",
  source: "css.lint.unknownProperties",
  message: "Unknown property: 'foo1'"
}
```

**Comment by sandy081** [comment] 2018-11-01 10:16
@octref This is a feature and not a regression. Here is some context

Last milestone we started showing error codes in the problems view (https://github.com/Microsoft/vscode/issues/49215)

![image](https://user-images.githubusercontent.com/10746682/47845815-4ecb2780-ddc6-11e8-9b31-652a7dc69a34.png)

Some extensions like `tslint` were already showing error codes in the message (since they were not shown) and now it got duplicated but they could not remove the error codes from message because error codes are not shown in inline and hovers in the editor yet. So this milestone we also started showing them at all places we show errors. 

https://github.com/Microsoft/vscode/issues/60749

Issue here is that the CSS diagnostics are having redundant information. `source` should just be `css` and not include additional information like error codes. Then the message looks as follows

`[css] Unknown property: 'foo1' [unknownProperties']`

This is way better than what it is now. I would leave up to you to remove or retain the error code.

**Comment by octref** [comment] 2018-11-01 16:04
I enjoy things lined up in the left, so I hope you can consider @joaomoreno's idea in #62370. I can also just not return `code` for lint diagnostics, since it's covered in the `source`.

![image](https://user-images.githubusercontent.com/4033249/47863321-410ca680-ddb4-11e8-8b5f-ef2b3d53646b.png)

My problem is: As someone who's writing a LSP, there is no place I can find information & track breaking changes on how each property is surfaced in the interface. This is true for `Hover`, `Diagnostics`, `CompletionItem` etc. This probably breaks my end-to-end test I have for Vue too.

**Comment by octref** [comment] 2018-11-02 03:57
Don't want to change back & forth, so waiting for #62370's discussion and moving to November.

**Comment by sandy081** [comment] 2018-11-02 08:38
> I enjoy things lined up in the left, so I hope you can consider @joaomoreno's idea in #62370. 

Sure, we can improve how to show `source` & `code` properties. But I do not think it is not related to this issue. This issue is about not to include additional details in `source` and use `code` for codes or rules.

> I can also just not return `code` for lint diagnostics, since it's covered in the `source`.

Please do not do that. Source should be the origin of the diagnostic which is `css` in your case. Again, use `code` for codes or rules.

> My problem is: As someone who's writing a LSP, there is no place I can find information & track breaking changes on how each property is surfaced in the interface. This is true for `Hover`, `Diagnostics`, `CompletionItem` etc. This probably breaks my end-to-end test I have for Vue too.

@dbaeumer I suppose above comment is for you.

**Comment by dbaeumer** [comment] 2018-11-02 10:12
@octref I see the point however from a pure LSP point of view we can only spec the data and not the rendering of it. There could have already been a client that renders the source and error code in which the UI would have looked bad. 

The thing we can do in the LSP is adding comments that this data is `usually` presented in a user interface. So for diagnostics something like this:

```
	/**
	 * The diagnostic's code, which usually appear in the user interface.
	 */
	code?: number | string;

	/**
	 * A human-readable string describing the source of this
	 * diagnostic, e.g. 'typescript' or 'super lint'. It usually
	 * appears in the user interface.
	 */
	source?: string;

	/**
	 * The diagnostic's message. It usually appears in the user interface
	 */
	message: string;
```

This would make it more clear that someone has to think about not duplicating the information.

**Comment by octref** [comment] 2018-11-02 16:38
@dbaeumer 

> which usually appear in the user interface.
This is not clear to the user. Where in the interface? How is it presented? Monospace font or default UI font? 

I would appreciate an illustration that shows **association between the data and the UI**. Here's a simple one I made in 1 minute:

![image](https://user-images.githubusercontent.com/4033249/47925000-50562780-de7a-11e8-8e77-5a5eff8b1163.png)

I think this is a doc issue: We should document the UI behaviors of our LSP Client / VS Code UI, and when we introduce changes, inform people who depend on it.

Discussed with @sandy081. We'll change CSS back for this milestone and look for a way to improve the UI display in the next milestone.

**Closed** 2018-11-02 16:40 UTC
Labels: bug, css-less-scss

**Comment by dbaeumer** [comment] 2018-11-05 08:31
@octref I see your point but the only thing we can do in the LSP to improve the doc and give examples on how the values of these strings should usually look like (in terms of their content). The goal of the LSP is to not define any UI. So if a client decides to never render an error code of a diagnostic in the UI and does this consistently this is fine with the LSP spec. If a client decides to render the source in a post-fix fashion this is fine as well. The LSP spec can not be a UI guideline for client tools.

Thinks are however different for the VS Code API.

**Comment by octref** [comment] 2018-11-05 15:33
> Thinks are however different for the VS Code API.

Exactly, my point is it's hard to track the changes in VS Code client implementation of LSP. As a language extension author, the data I'm sending back are the same but the user experience are changed. Sometimes it's good, like the file icon completion when `CompletionItemKind` is `File`, some changes might result in undesirable behaviors for users, like this one.

**Comment by dbaeumer** [comment] 2018-11-06 12:03
But then I think this is not LSP specific. An extension using directly the VS Code language API is affected the same way by this. I didn't change any VS Code LSP client code :-)
