### ISSUE TITLE
VSCode very slooow when opening minified css file

### ISSUE THREAD

**Issue by dfberry** [Microsoft/vscode#94] opened 2015-11-18 20:00 UTC
Mac OS X El Capitan, 10.11.1, 
VSCode 0.10.1
css file size: 116,198 bytes (119 KB on disk)

The attached file was built with a minifier as part of a grunt task to build the distributable files of a website. Tried to open the file several times to make sure that file is the issue. The app eventually shows a dialog that says "Visual Studio is no longer responding" 

When I reopen VSCode after the crash, the folder has been forgotten, it opens to a different folder. When is the "current" folder updated to the existing folder?

I added the .txt extension in order to add it here. The file extension was originally just .css

[main.08642f99.css.txt](https://github.com/Microsoft/vscode/files/38262/main.08642f99.css.txt)

**Comment by bpasero** [comment] 2015-11-19 07:27
Sounds like out of memory to me.

**Comment by alexandrudima** [comment] 2015-11-25 09:31
Cannot reproduce on windows (for VSCode master and 0.10.1). We need to check on OSX El Capitan

**Comment by alexandrudima** [comment] 2015-11-25 09:32
@dfberry 

Just to rule out there's nothing else in your folder interfering (having JS files might cause a lot of memory pressure). Does VSCode crash when you open a new window of VSCode (without any folder - purple status bar) and open just this file?

**Comment by alexandrudima** [comment] 2015-11-25 09:34
@egamma Can you please try to repro on OSX El Capitan

**Comment by egamma** [comment] 2015-11-25 09:58
I can repro this on OS X. VS Code hangs. Before it hangs I could observe some activity in the tokenizer. Could this be a dupe of a bug you showed us some time ago. Where there was some funny unicode character in the text and then Oniguruma becomes very inefficient on OS X?

**Comment by jwulf** [comment] 2015-11-25 10:29
Electron Helper CPU usage goes up to 100%. Memory is not the issue. Opened in a new window. Looks like it's biting off more than it can parse.

**Comment by alexandrudima** [comment] 2015-11-25 12:59
@egamma That must be it! 

Long line with at least one multi-byte character that takes forever to tokenize in posix.

**Comment by alexandrudima** [comment] 2015-11-25 13:02
The problem is in atom/node-oniguruma, more specifically:
https://github.com/atom/node-oniguruma/blob/master/src/onig-searcher.cc#L11
going into
https://github.com/atom/node-oniguruma/blob/master/src/unicode-utils-posix.cc#L38

which makes tokenizing strings with multi-byte characters O(N^2) under posix

**Comment by seixasfelipe** [comment] 2015-11-27 00:24
I have the same problem having 99% cpu editing an js file. Electron Helper on top of consuming process on my MacOS. Anyway to avoid that? Any kind of useful info that I could provide here?

thanks

**Comment by alexandrudima** [comment] 2015-11-27 09:30
@seixasfelipe Will try to raise awareness and possibly contribute a PR to atom/node-oniguruma. The problem occurs on mac or linux when there is a long line with multi-byte UTF8 characters.

**Comment by rjucf** [comment] 2015-12-03 21:47
+1

**Comment by alexandrudima** [comment] 2015-12-07 10:03
Submitted atom/node-oniguruma#46 that addresses the slow tokenization of long strings with multi-byte characters. Until they accept the PR, I have published a forked module on npm and adopted it in 0f49124c93854f8ac44256a0d7111f74aa88446e .

Tried out the original CSS file and it now opens fine.

**Closed** 2015-12-07 10:06 UTC
Labels: bug, freeze-slow-crash, upstream

**Comment by alexandrudima** [comment] 2015-12-16 16:07
@isidorn This is the long line with multi byte characters case that you also hit some time ago
