### ISSUE TITLE
Terminal: setting splitCwd setting: workspaceRoot description should cover multi-root workspace case

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#62263] opened 2018-10-31 10:45 UTC
Testing #62096 on Windows

I didn´t expect the prompt in the multi-root case given the description.

![image](https://user-images.githubusercontent.com/172399/47782940-bcf9e680-dd01-11e8-80cb-96fd49dd4bed.png)

Suggest something like

>A new split terminal will use the workspace root or prompt when there are multiple roots as the cwd.

**Comment by alexr00** [comment] 2018-10-31 13:20
Duplicate of #62179

**Closed by alexr00** 2018-10-31 13:20 UTC
Labels: integrated-terminal
