### ISSUE TITLE
problem with RTL Language

### ISSUE THREAD

**Issue by hesan911** [microsoft/vscode#146822] opened 2022-04-05 14:21 UTC
there is some problem in RTL Language.
when typed a RTL (farsi ) charcter, the editor change the </>
to other side

before:
![image](https://user-images.githubusercontent.com/20174389/161775289-c8cec27f-4c40-42da-95cc-afa41cbf7e8b.png)

after 
![image](https://user-images.githubusercontent.com/20174389/161775401-bd8ce2cf-d7de-450c-b184-11a371668d95.png)

**Comment by alexdima** [comment] 2022-04-05 18:17
@hesan911 Could you please provide the code as text so I can copy-paste it and try it out?

**Comment by NinjaRaiden** [comment] 2022-04-06 04:29
@alexdima 
This problem did not occur in previous versions.
`<small>سلام</small>`
Also there is some issue in selecting or highlighting those lines,
![ScreenKeep(1)](https://user-images.githubusercontent.com/22851562/161895845-ee7e3980-2c54-43bd-b199-6c3d9e49b5c6.jpg)
![ScreenKeep(2)](https://user-images.githubusercontent.com/22851562/161895852-bff41f8d-51da-4eb5-b28e-838c0d14a635.jpg)

**Comment by alexdima** [comment] 2022-04-06 10:36
I could reproduce this on Stable by making sure to tweak the theme in such a way that the `>` and `</` characters of the HTML tag get the same color as the text. If they have the same color as the text, then their tokens are merged.

So I could reproduce with the following settings:
```json
"workbench.colorTheme": "Default Dark+",
"editor.tokenColorCustomizations": {
  "textMateRules": [
    { "scope": "punctuation.definition.tag", "settings": { "foreground": "#D4D4D4" } }
  ]
},
"editor.renderWhitespace": "none",
```
and the following HTML code:
```html
<small>سلام</small>
```

<img width="151" alt="image" src="https://user-images.githubusercontent.com/5047891/161956127-92dabfd0-169f-4692-a50f-c2c25809217d.png">

I then verified that the fix for https://github.com/microsoft/vscode/issues/146354 also fixes this issue:

<img width="149" alt="image" src="https://user-images.githubusercontent.com/5047891/161956388-bb699c86-98cb-4473-ab0f-86116a73af39.png">

So this is a duplicate of #146354 and a fix is already available in today's build of [VSCode Insider](https://code.visualstudio.com/insiders/)

**Closed by alexdima** 2022-04-06 10:36 UTC
Labels: needs more info, editor-RTL
