### ISSUE TITLE
Fix Outline of Markdown files that contain "Includes"

### ISSUE THREAD

**Issue by sdwheeler** [microsoft/vscode#131427] opened 2021-08-23 16:54 UTC
## Problem description

The Microsoft Docs platform includes several extensions to the Markdown language. One of these is the ability to have include files. For example:

```markdown
[!INCLUDE [Alpine support](../../includes/alpine-support.md)]
```

See https://docs.microsoft.com/en-us/contribute/markdown-reference#included-markdown-files for documentation on the feature.

Include files are used extensively in the Microsoft docs. When an include file is used the Outline view of the file does not render.

Here is an example:

![image](https://user-images.githubusercontent.com/19415881/130486026-c00031e4-5d3c-4748-a40b-7d2155f39a62.png)

See the include statement on line 17 of the file and not that the outline is empty. If I delete the include statement I see the following:

![image](https://user-images.githubusercontent.com/19415881/130486209-fcbacc2f-1135-4d35-ae5e-42c3a2574c3f.png)

## Suggested behavior

I don't need the contents of the include file to be included in the Outline rendering, I just want the outline to show the Header tree for the current document. I assume that any Markdown extension would cause this same rendering problem. I just want the outline renderer to ignore the non-standard markdown and continue rendering the header hierarchy.

**Comment by sdwheeler** [comment] 2021-08-23 16:56
Here is my version information
```
Version: 1.59.1 (system setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by mjbvz** [comment] 2021-08-23 20:39
Marking this as an extension candidate since we target standard markdown and this seems like an extension to the language

Would also take a PR to fix the outline not being generated (but without adding full support for the `includes` syntax)

**Closed** 2021-08-23 20:38 UTC
Labels: *extension-candidate

**Comment by sdwheeler** [comment] 2021-08-23 21:06
@mjbvz All I am suggest here is that we fix the outline generation. Just ignore the non-standard markdown element and continue down the AST to the next node in the Header tree. Not try to handle includes.

**Comment by mjbvz** [comment] 2021-08-30 21:14
Should be fixed in the first 1.61 insiders that comes out later this week. Please give it a try and let me know if the issue has been fixed

**Comment by gjsjohnmurray** [comment] 2021-09-03 08:29
@mjbvz it works for me in today's 1.61-insider

@sdwheeler  please verify it resolves your case too.

**Comment by sdwheeler** [comment] 2021-09-03 17:16
@mjbvz it works for me in 1.61-insider.

Thanks for the fix.

**Comment by yhatt** [comment] 2021-09-12 10:11
I'll give a feedback as a one of extension authors: This change will break existing extensions that are extending Markdown outline renderer for right reason (as mentioned at #132741).

I'm looking for how to keep providing the outline extension to users because this contribution can give more organized outline view and an abillity of folding the section in the editor. But it looks like there is no way when markdown contributions are disabled to the outline engine. It's like a pity for Markdown extension users.

I wonder if the outline engine may keep to allow contributable by giving a simple engine as a fallback, only when the engine has thrown any errors or returns invalid AST.

**Comment by mjbvz** [comment] 2021-09-14 23:00
@gjsjohnmurray I'm going to revert the PR due to the feedback from  #132741

I think it makes sense for the output to be extensible. For the original issue here, I believe that a markdown extension could contribute support for the includes syntax so that it renders properly

**Comment by gjsjohnmurray** [comment] 2021-09-17 07:04
@mjbvz fair enough about reverting this so as not to break extensions such as @yhatt's

But I think the root cause of the broken outline seen by @sdwheeler is that the include extension typically renders a document with more lines than the original .md file has. This means that headers in the original .md file which come after the include statement can send line numbers into the Outline which exceed the total number of lines in the .md file. When this happens the Outline reports that no information is available. In other cases the Outline appears but clicking on a header which follows an include will position you too far down the .md file.

Would it work for me to check the line-count of the rendered document, and if it isn't equal to the line-count of the .md document then re-render with the unextended engine to give Outline its information?
