### ISSUE TITLE
Word wrap  now won't 'unwrap'

### ISSUE THREAD

**Issue by GregCaldock** [Microsoft/vscode#21552] opened 2017-02-28 10:47 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (799198928b772d1def661d3cd7962f04b7f38b98, 2017-02-28T07:09:02.848Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|format-indent|Kasik96|1.3.0|
|php-intellisense|felixfbecker|1.1.3|
|phpcs|ikappas|0.7.0|
|vscode-spotify|shyykoserhiy|1.1.0|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Go to View -> Toggle Word Wrap
2. Hit Alt-z

Text remains wrapped no regardless of attempts to toggle word wrapping. Have also tried the following settings:

"editor.wordWrap": "on"
"editor.wordWrap": "off"

Which did nothing.

This used to work in 1.8. The behaviour changed in 1.9 and early versions of 1.10 and I could 'toggle' word wrapping by manually changing these settings:

"editor.wordWrap": true,
"editor.wrappingColumn": -1

But trying either Alt-z or going to View -> Toggle Word Wrap had no effect.

With the latest version of 1.10 I can no longer toggle word wrapping - no matter what I try the text remains wrapped.

Contrary to claims made in previous reports of this problem #21291 and #21487 something HAS changed since 1.8 as toggling word wrap used to work perfectly, it then went to having to be changed by going to File -> Preferences -> Settings and manually changing the settings to now where the settings cannot be changed at all.

**Comment by isidorn** [comment] 2017-02-28 11:23
A lot has changed, more details about it can be found here
https://github.com/rubyide/vscode-ruby

fyi @alexandrudima

**Comment by GregCaldock** [comment] 2017-02-28 11:38
@isidorn 

If I use the setting editor.wordWrap: "off" my text wraps, ALt-z does nothing, View -> Toggle Word Wrap does nothing

If I use the setting editor.wordWrap: "on" my text wraps, Alt-z does nothing, View -> Toggle Word Wrap does nothing

If I use the settings editor.wordWrap: "wordWrapColumn" and "editor.wordWrapColumn": 10000 my text wraps, Alt-z does nothing, View -> Toggle Word Wrap does nothing

If I use the settings editor.wordWrap: "wordWrapColumn" and "editor.wordWrapColumn": 1 my text wraps, Alt-z does nothing, View -> Toggle Word Wrap does nothing

If I use the settings editor.wordWrap: "wordWrapColumn" and "editor.wordWrapColumn": 3333333 my text wraps, Alt-z does nothing, View -> Toggle Word Wrap does nothing

If I use the settings editor.wordWrap: "bounded" and "editor.wordWrapColumn": 10000 my text wraps, Alt-z does nothing, View -> Toggle Word Wrap does nothing

If I use the settings editor.wordWrap: "bounded" and "editor.wordWrapColumn": 1 my text wraps, Alt-z does nothing, View -> Toggle Word Wrap does nothing

If I use the settings editor.wordWrap: "bounded" and "editor.wordWrapColumn": 333333 my text wraps, Alt-z does nothing, View -> Toggle Word Wrap does nothing

Is this the expected new behaviour?

**Comment by alexandrudima** [comment] 2017-02-28 15:56
@GregCaldock 

Here are the default relevant settings we ship with:
```
"editor.wordWrap": "off",
"editor.wordWrapColumn": 80,
"[markdown]": {
    "editor.wordWrap": "on",
    ...
}
```
Short of you opening a markdown file, in which case the language specific setting overrides, I can only think of one other case where this can happen, namely "minified code".

i.e. is this perhaps happening only with a certain file? (could you share this file to validate this?)

In case a file appears to be "minified code", we will forcefully wrap it and there's no way to work around. Specifically:

```
	/**
	 * Splits characters in two buckets. First bucket (A) is of characters that
	 * sit in lines with length < `LONG_LINE_BOUNDARY`. Second bucket (B) is of
	 * characters that sit in lines with length >= `LONG_LINE_BOUNDARY`.
	 * If count(B) > count(A) return true. Returns false otherwise.
	 * @internal
	 */
	where LONG_LINE_BOUNDARY = 1000
```

Is it possible you are opening a file where more than half of the lines are longer than 1000 characters? (this would make us think you've opened a minified file). Is your file a source file that you edit by hand or is it a generated file that is not meant to be edited by humans?

**Comment by GregCaldock** [comment] 2017-02-28 16:08
@alexandrudima there's one line which is possibly over 1000 characters in the file I was looking at and this may well be the case in other files I edit. Prior to 1.9 I was able to toggle wrapping on these - now I know that this restriction exists I'll use another editor in specific cases - it's not something I do everyday but enough for it to be an occasional pain - however one I can work around.

Thanks for your help.

**Comment by alexandrudima** [comment] 2017-02-28 16:43
Ok, I can reproduce with a file with the following content:
```
asdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asfasdfadsfasdfasf asf asf asf saf saf asf asf sa asf asdfadsfasdfasf asf asf asf saf saf asf asf sa asf
asd
asd
asd
```
There are 2222 characters on the long line and only 9 characters on the short/regular lines. This causes the `isDominatedByLongLines()` to switch on and the file is forcefully wrapped. It is true, in 1.10 there is no way to turn off wrapping, not even via the action. To consider if we want to fix this, at least the action should be able to turn off wrapping.

**Comment by alexandrudima** [comment] 2017-03-01 14:04
In today's standup we have decided to not include this fix on the stable branch (February release). The fix is in the insiders channel (starting with tomorrow's build) and consists of allowing the Toggle Word Wrap action to unwrap "minified" files

**Closed by alexandrudima** 2017-03-01 14:04 UTC
Labels: bug, candidate, important

**Comment by refkotay** [comment] 2017-03-02 19:09
0bc62d1 `"editor.wordWrapMinified": false` gets an 'Unkown configuration setting' warning (and is not in settings). But it does work.

Is this an unrelated bug? I already tried closing the settings tab, rebooting, then reopening. It's not very important since it's working but I thought I'd point it out.
