### ISSUE TITLE
Closing automatic brackets/strings doesn't work for dead keys on macOS

### ISSUE THREAD

**Issue by GiveMeZeny** [microsoft/vscode#68103] opened 2019-02-07 13:53 UTC
- VSCode Version: 1.31
- OS Version: macOS High Sierra

Typing the closing part of automatic brackets through a dead key doesn't overwrite the second bracket:

![screen capture](https://user-images.githubusercontent.com/10136484/52415431-38c8b380-2ae7-11e9-992a-f2c9880c69b4.gif)

It does work as expected for `(` and `)`, which are on regular keys.
It doesn't work for `"`, `{`, `}`, `[` and `]`, which are all on dead keys (note the `,` shortly appearing before the actual symbol).

Steps to Reproduce:
Use a keyboard layout that has any symbol that gets automatically closed (like `"` or brackets) on dead keys.

Does this issue occur when all extensions are disabled?: Yes

**Comment by GiveMeZeny** [comment] 2019-02-08 21:28
Strangely, writing brackets via dead keys also make them apparently count as quotes (the other way around, however, is not the case: writing quotes via dead keys doesn't make them count as brackets):

1. Starting vscode with `code --disable-extensions` and having `editor.autoClosingQuotes` set to `never` disables auto-closing `{`, which is written via a dead key:
![screen capture](https://user-images.githubusercontent.com/10136484/52493078-ebbe0d80-2bca-11e9-848b-c15ab5324746.gif)

2. And then setting `editor.autoClosingBrackets` to `never` (with `editor.autoClosingQuotes` set to `always`)  doesn't stop `{` from getting auto-closed:
![screen capture](https://user-images.githubusercontent.com/10136484/52493270-51aa9500-2bcb-11e9-8d4a-3e8df88c296c.gif)

I have created a keyboard layout for testing purposes:
* `q` is the dead key
* `w` is mapped to `"`, either directly or via `q`
* `e` is mapped to `(`, either directly or via `q`
* `r` is mapped to `)`, either directly or via `q`
* `t` is mapped to `{`, either directly or via `q`
* `y` is mapped to `}`, either directly or via `q`

```sh
cat <<HERE >~/Library/Keyboard\ Layouts/DeadKeyBracketsTest.keylayout
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "file://localhost/System/Library/DTDs/KeyboardLayout.dtd">
<keyboard group="0" id="-9986" name="DeadKeyBracketsTest" maxout="2">
	<layouts>
		<layout first="0" last="0" mapSet="ANSI" modifiers="commonModifiers"/>
	</layouts>
	<modifierMap id="commonModifiers" defaultIndex="0">
		<keyMapSelect mapIndex="0">
			<modifier keys=""/>
		</keyMapSelect>
	</modifierMap>
	<keyMapSet id="ANSI">
		<keyMap index="0">
			<key code="12" action="q"/>
			<key code="13" action="w"/>
			<key code="14" action="e"/>
			<key code="15" action="r"/>
			<key code="17" action="t"/>
			<key code="16" action="y"/>

			<key code="36" output="&#x000D;"/>
			<key code="49" action="space"/>
			<key code="51" output="&#x0008;"/>
		</keyMap>
	</keyMapSet>
	<actions>
		<action id="q">
			<when state="none" next="deadkeystate"/>
			<when state="deadkeystate" output=","/>
		</action>
		<action id="w">
			<when state="none" output="&#x0022;"/>
			<when state="deadkeystate" output="&#x0022;"/>
		</action>
		<action id="e">
			<when state="none" output="("/>
			<when state="deadkeystate" output="("/>
		</action>
		<action id="r">
			<when state="none" output=")"/>
			<when state="deadkeystate" output=")"/>
		</action>
		<action id="t">
			<when state="none" output="{"/>
			<when state="deadkeystate" output="{"/>
		</action>
		<action id="y">
			<when state="none" output="}"/>
			<when state="deadkeystate" output="}"/>
		</action>
		<action id="space">
			<when state="none" output=" "/>
			<when state="deadkeystate" output=", "/>
		</action>
	</actions>
	<terminators>
		<when state="deadkeystate" output=","/>
	</terminators>
</keyboard>
HERE
```

**Comment by alexandrudima** [comment] 2019-10-10 10:10
Duplicate of #34407

**Closed by alexandrudima** 2019-10-10 10:10 UTC
Labels: bug, editor-ime, editor-input, mac
