### ISSUE TITLE
Circular dependency between remote.ts and tunnelView.ts: VS Code 1.41.0, Debian Buster amd64

### ISSUE THREAD

**Issue by Levitator1** [microsoft/vscode#87144] opened 2019-12-17 04:18 UTC
When building on amd64 Debian Linux "Buster" with node.js=v12.13.1
Running: yarn run gulp vscode-linux-amd64

Reports that there is a circular reference between "vs/workbench/contrib/remote/browser/remote"
and "vs/workbench/contrib/remote/browser/tunnelView".

Submitted PR #87143

**Comment by alexr00** [comment] 2019-12-17 09:59
Duplicate of https://github.com/microsoft/vscode/issues/86924

**Closed** 2019-12-17 09:59 UTC
Labels: *duplicate
