### ISSUE TITLE
Autocomplete is still annoying in some cases

### ISSUE THREAD

**Issue by gjuchault** [Microsoft/vscode#55949] opened 2018-08-07 14:56 UTC
Hello,

This is related to https://github.com/Microsoft/vscode/issues/9504

- VSCode Version: 1.25.1
- OS Version: macOS Mojave  10.14

Steps to Reproduce:

1. Create a new JS file. Let's say you're working with Redux or vuex
2. Start typing:

```js
export const SET_FOO = (state
```

If I press comma, I get:
```js
export const SET_FOO = (ListeningStateChangedEvent,
```

If you start typing:

```js
function foo(state
```

and press comma, everything is fine, autocomplete is not replacing the parameter. _Edit_: so it seems that's just arrow functions / ES2015+ features that are not handled correctly

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-08-07 21:01
Duplicate of #54386

**Closed by mjbvz** 2018-08-07 21:01 UTC
Labels: javascript
