### ISSUE TITLE
Integrated terminal prompt disappear when pressing tab for suggestion 

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#28453] opened 2017-06-11 11:26 UTC
- VSCode Version:1.13.0
- OS Version: Ubuntu 16.04
![screenshot from 2017-06-11 19-19-02](https://user-images.githubusercontent.com/8751130/27010652-cf0bc204-4edb-11e7-8967-460195966097.png)
![screenshot from 2017-06-11 19-19-18](https://user-images.githubusercontent.com/8751130/27010654-cf0ca318-4edb-11e7-9cee-c2abc2685a9b.png)
![screenshot from 2017-06-11 19-19-33](https://user-images.githubusercontent.com/8751130/27010653-cf0c0a3e-4edb-11e7-869b-99ad9fed969a.png)

Steps to Reproduce:

1. 
2.

**Comment by cmpute** [comment] 2017-06-11 11:33
Similar Problem
- VSCode Version:1.13.0
- OS Version: Ubuntu 16.04

terminal print the path twice when using (may related to chinese Characters?)

the current path is `D:\编程\Lidar`
however the header in console shows `D:\编程\Lidar编程\Lidar>`

**Comment by alexsomesan** [comment] 2017-06-12 07:13
I'm having this exact problem on the Mac, with 1.13.0
It's a regression, it only started happening after upgrading to 1.13.0.

**Comment by jamesseanwright** [comment] 2017-06-12 09:41
Same issue here on macOS Sierra (10.12.2)

**Comment by ramya-rao-a** [comment] 2017-06-12 17:25
Closing as duplicate of #28304

cc @Tyriar

**Closed by ramya-rao-a** 2017-06-12 17:25 UTC
Labels: new release
