### ISSUE TITLE
Crashes every day with "Code: '5'"

### ISSUE THREAD

**Issue by JaimeObregon** [microsoft/vscode#143101] opened 2022-02-15 12:20 UTC
Issue Type: <b>Performance Issue</b>

My VSCode instance crashes every day. I have switched recently, so I cannot state since when exactly. I cannot bind these chrases to any specific set of reproducible actions — it looks just random.

I can somewhat predict it's going to crash soon because it starts to respond sluggishly seconds or a couple of minutes before a crash. For example, switching to a different tab takes ~2-5 seconds to complete when this happens. That usually signals it's about to crash soon.

The crash dialog doesn't provide any meaningful information, just a laconic, cryptic `reason: 'crashed', code: '5'` line.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (1.02GB free)|
|Process Argv|--crash-reporter-id 1004a7b4-dd6b-4c5b-97a9-c41af381dd3c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	    90	 39780	code main
    0	    33	 39783	   gpu-process
    0	     8	 39785	   utility-network-service
    0	    49	 40144	   shared-process
    0	    25	 40160	     ptyHost
    0	     0	 40457	       node /Users/jaime/.nvm/versions/node/v17.2.0/bin/yarn run start:web
    0	     0	 40477	         /Users/jaime/.nvm/versions/node/v17.2.0/bin/node --require /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/vcc.js /Users/jaime/.node/corepack/yarn/3.1.1/yarn.js run start:web
    0	     0	 40553	           /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/yarn.js workspace @c20/web dev
    0	     0	 40554	             /Users/jaime/.nvm/versions/node/v17.2.0/bin/node --require /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/vcc.js /Users/jaime/.node/corepack/yarn/3.1.1/yarn.js workspace @c20/web dev
    0	     0	 40566	               /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/Code/c20/.yarn/releases/yarn-3.1.1.cjs workspace @c20/web dev
    0	     8	 40570	                 /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/Code/c20/node_modules/next/dist/bin/next dev
    0	     0	 40580	       node /Users/jaime/.nvm/versions/node/v17.2.0/bin/yarn run start:api
    0	     0	 40582	         /Users/jaime/.nvm/versions/node/v17.2.0/bin/node --require /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/vcc.js /Users/jaime/.node/corepack/yarn/3.1.1/yarn.js run start:api
    0	     0	 40589	           /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/yarn.js workspace @c20/api start
    0	     0	 40590	             /Users/jaime/.nvm/versions/node/v17.2.0/bin/node --require /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/vcc.js /Users/jaime/.node/corepack/yarn/3.1.1/yarn.js workspace @c20/api start
    0	     0	 40597	               /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/Code/c20/.yarn/releases/yarn-3.1.1.cjs workspace @c20/api start
    0	     0	 40601	                 /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/Code/c20/node_modules/nodemon/bin/nodemon.js src/server.ts
    0	     8	 47554	                   /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/Code/c20/node_modules/ts-node/dist/bin.js src/server.ts
    0	    25	 62305	       node /Users/jaime/.nvm/versions/node/v17.2.0/bin/yarn run start:api
    0	    82	 62308	         /Users/jaime/.nvm/versions/node/v17.2.0/bin/node --require /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/vcc.js /Users/jaime/.node/corepack/yarn/3.1.1/yarn.js run start:api
    0	    25	 62314	           /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/yarn.js workspace @c20/api start
    0	    25	 62317	             /Users/jaime/.nvm/versions/node/v17.2.0/bin/node --require /Users/jaime/.nvm/versions/node/v17.2.0/lib/node_modules/corepack/dist/vcc.js /Users/jaime/.node/corepack/yarn/3.1.1/yarn.js workspace @c20/api start
    0	    82	 62320	               /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/Code/c20/.yarn/releases/yarn-3.1.1.cjs workspace @c20/api start
    0	    33	 62324	                 /Users/jaime/.nvm/versions/node/v17.2.0/bin/node /Users/jaime/Code/c20/node_modules/nodemon/bin/nodemon.js src/server.ts
    0	    25	 62260	     fileWatcher
    0	     0	 62374	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   156	 62254	   window (company.ts — c20)
    0	    49	 62257	   extensionHost
    0	    25	 62264	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/jf/y8xgq9yd6yv3bn0wr2mwpxhw0000gn/T/vscode-typescript501/351cc628b6420b13b793/tscancellation-a155a17769e33a7e0c8d.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    1	    33	 62265	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/jf/y8xgq9yd6yv3bn0wr2mwpxhw0000gn/T/vscode-typescript501/351cc628b6420b13b793/tscancellation-0dc703249f57b491be5d.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	    33	 62268	       /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/jaime/Library/Caches/typescript/4.5 --enableTelemetry --typesMapLocation /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	    49	 62286	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/jaime/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js --node-ipc --clientProcessId=62257
    0	    33	 62302	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=62257
    1	    66	 62369	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (company.ts — c20)
|    Folder (c20): 10757 files
|      File types: gz(6678) zip(2595) js(519) json(213) ts(105) mdx(92)
|                  pack(44) map(40) html(29) md(25)
|      Conf files: package.json(6) tsconfig.json(5) github-actions(2)
|                  settings.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
unique-lines|bib|1.0.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.2.0
vscode-pull-request-github|Git|0.36.1
customize-ui|ioc|0.1.58
monkey-patch|ioc|0.1.16
rainbow-csv|mec|2.0.0
dotenv|mik|1.0.1
vscode-language-pack-es|MS-|1.64.6
remote-containers|ms-|0.217.4
emoji|Per|1.0.1
vscode-sort-json|ric|1.20.0
vscode-sort-package-json|uni|1.2.2

(2 theme extensions excluded)

</details>

<img width="1440" alt="Captura de pantalla 2022-02-11 a las 12 26 29" src="https://user-images.githubusercontent.com/417226/154061089-4481e78c-54bd-4118-8b77-8390a6d2c14e.png">

**Comment by gjsjohnmurray** [comment] 2022-02-15 12:22
Maybe disable all non-essential extensions and see if the problem still occurs.

**Comment by JaimeObregon** [comment] 2022-02-15 12:39
Thank you, John. Seems like a good starting point. I have just disabled all the 13 non-essential extensions I have installed. I will slowly re-enable them during the following days. That may provide insight. For the record, I jot down here the essential four I am starting with.

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.2.0
vscode-language-pack-es|MS-|1.64.6
</details>

**Comment by JaimeObregon** [comment] 2022-02-15 18:42
It just crashed again. I have disabled two of my remaining extensions, and now I am running only two, both authored by Microsoft.

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
vscode-language-pack-es|MS-|1.64.6
</details>

**Comment by JaimeObregon** [comment] 2022-02-16 12:28
Got today's crash. Only the two aforementioned extensions were enabled (as well as GitHub's official theme for VSCode, which I pressume innocuous):

<img width="504" alt="Captura de pantalla 2022-02-16 a las 13 00 09" src="https://user-images.githubusercontent.com/417226/154262020-cfacd59e-a109-46c8-8d93-e2ad712045df.png">

So I have enabled back all of my 17 extensions and I am abandoning this road and driving my attention to the running tasks. I have several configured but only one running continuosly. This is how my workspace's `tasks.json` file looks like:

```json
{
  "tasks": [
    {
      "isBackground": true,
      "label": "Starts the API",
      "runOptions": { "runOn": "folderOpen" },
      "script": "start:api",
      "type": "npm"
    },
    // ...
  ],
  "version": "2.0.0"
}
```

The referenced `script` property justs invokes a simple Express server written in TypeScript: `nodemon src/server.ts`.

It is not so simple for me to disable this task without affecting my workflow, so any hint about how to further diagnose this issue will be welcome.

**Comment by JaimeObregon** [comment] 2022-02-18 11:18
Yesterday it didn't crash, but today it crashed early 🙂.

Would love to provide a more detailed report, such as a stack trace or a core dump, but the error dialog doesn't provide any, nor a hint about where to action.

**Comment by JaimeObregon** [comment] 2022-02-18 16:24
Crashed again. This time I saw it coming because it started to respond in a sluggish way seconds before it collapsed, and I could jump over the activity monitor and take this screenshot an instant before the crash. Probably not very useful, but just in case it helps…

<img width="1302" alt="Captura de pantalla 2022-02-18 a las 16 58 32" src="https://user-images.githubusercontent.com/417226/154721227-1fe8be9e-81b2-498d-a887-2fc59f71835f.png">

**Comment by JaimeObregon** [comment] 2022-02-19 14:02
Got my daily crash. VS Code's logs don't detail much:

On `main.log`:
```log
[2022-02-19 14:20:26.664] [main] [error] CodeWindow: renderer process crashed (reason: crashed, code: 5)
[2022-02-19 14:20:26.995] [main] [info] Extension host with pid 67864 exited with code: 0, signal: null.
```

On `sharedprocess.log`:
```
[2022-02-19 14:20:31.373] [sharedprocess] [info] Worker process with pid 67866 terminated normally (type: fileWatcher, window: 6).
```

The latter might be related to the restart and not the crash itself, as I killed a task just upon restart.

**Comment by JaimeObregon** [comment] 2022-02-24 11:17
Today It's five days without a crash. I can't tell what has happened, but it feels more stable since a few days ago. No significant changes in my setup. In hindsight, the only relevant thing I can think of, is that I did a full computer shut down and restart exactly 2,5 days ago.

```
$ uptime
12:11  up 2 days, 12:41, 3 users, load averages: 2,25 3,85 3,59
```

My VS Code's version (as per commit) and setup remains exactly the same, though.

**Comment by JaimeObregon** [comment] 2022-02-26 19:52
It crashed again today. I won't keep reporting, as I cannot attach more specific insights useful to identify the cause.

**Comment by andresfjobs** [comment] 2022-03-07 20:35
I have the same issue but the problem is when I try to do an npm i using a private server to get the dependencies, so in my case is related to the terminal, I'm using a MAC Pro 2019 Intel and this issues started suddenly without any new configuration.

**Comment by b055man** [comment] 2022-03-16 12:49
I started seeing crashes as well (crashed, code 5), a few days ago (?)- I'm not sure if something has changed in the VS or in my dev environment.
It happens extremely frequently, esp. when working with unit tests and assessing failed cases (when the peek dialog is displayed) - VS Code crashes every couple of minutes :/ 

It's really easy to reproduce, so if anyone is willing, I can grab some logs, but I need instructions.

FWIW, I'm on MacOS 11/Big Sur

```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Comment by rafo** [comment] 2022-06-10 21:00
Maybe "[Creating and symbolicating local crash reports](Creating and symbolicating local crash reports)" can help? 

I have the same issue right now, but only when

1. I open my home folder in vscode (macOS Monterey M1).
2. Adding a new folder
3. Adding some files from somewhere else

**Comment by 2019geguangpu** [comment] 2022-10-20 06:33
And then, is this problem have any solutions？When I debug jest files, this problem always appears.

**Comment by bsassoli** [comment] 2022-11-07 06:34
I am experiencing the same issue. I noticed the following message upon reopening: 
>The isort server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by JaimeObregon** [comment] 2022-11-07 16:07
I am the OP and I haven't experienced any crash in the last six months. 🎉

Whatever caused this, it is already gone for me. I will leave this issue open because there seem to be others facing this instability.

**Comment by idevmans** [comment] 2022-11-18 14:41
Ventura 13.0.1 crashing all the time 
Disabled every extension styll.

**Comment by deepak1556** [comment] 2022-12-07 10:45
Closing per https://github.com/microsoft/vscode/issues/143101#issuecomment-1305837100

**Closed by deepak1556** 2022-12-07 10:45 UTC

**Comment by memiux** [comment] 2022-12-15 15:00
I'm having the same issue, what was the solution?

**Comment by hypeofpipe** [comment] 2022-12-28 19:02
Same stuff, crashed today several times with the next error:
```
(reason: 'crashed', code: '5')
```
M1 Pro, Ventura 13.X.X

<img width="258" alt="image" src="https://user-images.githubusercontent.com/14982064/209860073-528cc759-694c-47bb-a6da-5398ee3a80bf.png">

**Comment by jimmyddalton** [comment] 2023-01-08 19:07
I'm having the same issue, not sure why it was closed.

**Comment by deepak1556** [comment] 2023-01-09 04:34
If you are facing similar crashes, please open a new issue with crash dumps following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report. Thanks!
