### ISSUE TITLE
Initialize JS/TS extension takes forever.

### ISSUE THREAD

**Issue by CamWang** [microsoft/vscode#121783] opened 2021-04-21 03:16 UTC
When I open a folder of remote wsl and a js file from local windows I found that it takes forever for JS/TS extension to load.

VS Code Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z 
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1. Open a folder located on a wsl2 ubuntu 20.04 using VSCode.
2. Open a js file located on Windows in the same VSCode window.
3. Reload the window

Temporary Solution:
Initialize JS/TS extension immediately gone once I close the js file on Windows in the current VSCode window. And reopen the js file on Windows using the same VSCdoe window worked perfectly without JS/TS extension loading message.

Does this issue occur when all extensions are disabled?: No

This is the TS server log file. I think it's around Info 42 that the Initializing JS/TS notification starting to show.
The project file I opened called mirage at WSL2 Ubuntu /home/work/mirage directory
The js file I opened called judge_data.js at Windows D:\judge_data.js
[tsserver.log](https://github.com/microsoft/vscode/files/6347777/tsserver.log)

**Comment by adjenks** [comment] 2021-04-22 02:49
Same issue?
https://github.com/microsoft/vscode/issues/109847

**Comment by mjbvz** [comment] 2021-04-24 00:10
Duplicate of #119268

Please let me know if you still see this in VS Code insiders

**Closed by mjbvz** 2021-04-24 00:10 UTC
