### ISSUE TITLE
 Running the contributed command:'emmet.expandAbbreviation' failed.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#32567] opened 2017-08-15 15:15 UTC
Issue Id: <b>aa9793d7-6da9-7f9a-616d-d4a3251c2de4</b><br /><br />*Versions* <br />- 1.15.0<br />-  6feff11ed03402cf77e04e74e13c55529fdb4d09<br />-  1af52c0470d6f445966b5c8a3065233b34303d9a<br />*Stack* <br />Error: Running the contributed command:'emmet.expandAbbreviation' failed.<br />[/vs/workbench/api/node/extHostCommands.ts#L134:32](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/api/node/extHostCommands.ts#L134:32)<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler))<br />    at _combinedTickCallback (internal/process/next_tick.js:67:7) <no sourcemaps><br />    at process._tickDomainCallback (internal/process/next_tick.js:122:9) <no sourcemaps><br />

**Comment by ramya-rao-a** [comment] 2017-08-15 15:37
Duplicate of #32507

**Closed by ramya-rao-a** 2017-08-15 15:37 UTC
Labels: emmet

**Comment by Opelar** [comment] 2017-08-16 11:37
I met this problem today.....

I'll just clear these two options  !!!

{
  "command": "editor.emmet.action.expandAbbreviation",
  "key": ""
}
{
  "command": "emmet.expandAbbreviation",
  "key": ""
}
