### ISSUE TITLE
Can not load installed extension and recommend extension

### ISSUE THREAD

**Issue by Bleichroder** [microsoft/vscode#109640] opened 2020-10-29 04:39 UTC
- VSCode Version:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (2 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
- OS Version: 10.15.7 

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/16949131/97526130-72d89800-19e3-11eb-8dcf-f6d6a1f2ec31.png)

When I open extension window vscode can not load any installed extension and recommend extension, I've already installed some extension but I cannot see them in the list. This happen recently

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Bleichroder** [comment] 2020-10-29 05:18
And when I search some extension there is no http request in developer tools

**Comment by sandy081** [comment] 2020-10-29 10:46
Please follow these steps

- Help -> Toggle Developer Tools -> Console - Check if there are any errors
- View -> Command Pallette... -> Toggle Shared Process -> Console - Check if there are any errors
- View -> Open View… -> Log (Shared) - Check if there are any errors
- View -> Open View… -> Log (Window) - Check if there are any errors

**Comment by Bleichroder** [comment] 2020-10-29 12:58
Help -> Toggle Developer Tools -> Console show this
![image](https://user-images.githubusercontent.com/16949131/97576227-d9cc7000-1a28-11eb-9ee7-2843ab1c03bd.png)
There is no response when click View -> Command Pallette... -> Toggle Shared Process -> Console
And there is no Log (Shared) option
![image](https://user-images.githubusercontent.com/16949131/97576420-1c8e4800-1a29-11eb-8f13-fa811a48b7e8.png)
View -> Open View… -> Log (Window) - Check show this
![image](https://user-images.githubusercontent.com/16949131/97576292-f072c700-1a28-11eb-9c4d-1ef08628199d.png)

**Comment by sandy081** [comment] 2020-10-29 13:43
This explains - there is no shared process.

Assigning to @deepak1556 / @joaomoreno - not sure who owns the shared process now.

**Comment by joaomoreno** [comment] 2020-10-29 14:02
@Bleichroder Can you reproduce with a branch new user data dir? `--user-data-dir NEW_FOLDER`

**Comment by Bleichroder** [comment] 2020-10-30 02:30
> @Bleichroder Can you reproduce with a branch new user data dir? `--user-data-dir NEW_FOLDER`

Yes it reproduce when I open vscode with user data dir. I can use some of the extensions I have Installed, like gitlens, but cannot see installed or search extension in list
![image](https://user-images.githubusercontent.com/16949131/97653081-e5587f00-1a9a-11eb-9335-72145d2e1eed.png)

**Comment by deepak1556** [comment] 2020-10-30 02:43
This might very well be a corrupted launch service state, @Bleichroder can you restart your system and this time open vscode  via the dock or finder or use `open -a <path-to-app>` for command line. Let me know if the issue still repros.

**Comment by Bleichroder** [comment] 2020-10-30 02:52
> This might very well be a corrupted launch service state, @Bleichroder can you restart your system and this time open vscode via the dock or finder or use `open -a <path-to-app>` for command line. Let me know if the issue still repros.

I've restart the system several times and reinstall vscode with other version, but this still happen....

**Comment by deepak1556** [comment] 2020-10-30 03:37
How are you launching the app ?

**Comment by Bleichroder** [comment] 2020-10-30 03:54
> How are you launching the app ?

I have try launching vscode via finder and dock, both are same situation

**Comment by deepak1556** [comment] 2020-10-30 04:08
Can you provide the output of `code --verbose`

**Comment by Bleichroder** [comment] 2020-10-30 04:17
[verbose.log](https://github.com/microsoft/vscode/files/5462958/verbose.log)

> Can you provide the output of `code --verbose`

**Comment by deepak1556** [comment] 2020-10-30 05:21
Did you try to search for extensions in the above launch ? I don't see any error wrt shared process creation.

**Comment by deepak1556** [comment] 2020-10-30 05:21
As a follow-up, see if you can get the following traces

1) `xcrun xctrace record --template 'System Trace' --output <some-path>/code_system.trace --launch /Applications/Visual\ Studio\ Code.app/`
2) Once the editor opens, click the extension tab and try to search for extensions
3) Quit the app
4) `xcrun xctrace record --template 'File Activity' --output <some-path>/code_file.trace --launch /Applications/Visual\ Studio\ Code.app/`
5) Repeat steps 2) and 3)
6) Attach the traces code_system.trace and code_file.trace either here or you can send them to Deepak.Mohan@microsoft.com since they contain sensitive data.

**Comment by Bleichroder** [comment] 2020-10-30 07:59
I have send you a email. Thanks

**Comment by deepak1556** [comment] 2020-10-30 21:06
Thanks will look into them, today.

**Comment by Bleichroder** [comment] 2020-11-05 04:19
Is there any new development?

**Comment by joaomoreno** [comment] 2021-01-25 15:18
ping @deepak1556

**Comment by deepak1556** [comment] 2021-01-25 16:57
@Bleichroder can you try the latest insiders https://code.visualstudio.com/insiders that contains a refactor for spawning shared process.

**Comment by Bleichroder** [comment] 2021-01-28 09:25
new version has resolve this problem, thanks all

**Closed** 2021-01-28 09:25 UTC
Labels: macos-catalina, needs more info
