### ISSUE TITLE
Select Default Profile does not actually open gitbash. After relaunch, on startup, it just keeps opening PowerShell

### ISSUE THREAD

**Issue by evaera** [microsoft/vscode#132795] opened 2021-09-09 20:09 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows_NT x64 10.0.19042

This is the same issue as #123684. That issue was locked after another person reported it as not being fixed. Unfortunately, I can confirm that the issue is still not fixed. VS code opens Powershell every time I open a new window as of the August release instead of my configured default of Git Bash. If I open a new terminal with the plus button manually, it correctly opens git bash.

**Comment by IllusionMH** [comment] 2021-09-09 20:12
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release(delayed from today).

**Closed** 2021-09-09 20:13 UTC
Labels: *duplicate
