### ISSUE TITLE
"Sticky Scroll" problem with C# classes/methods that contain Attributes

### ISSUE THREAD

**Issue by gusbzs** [microsoft/vscode#157840] opened 2022-08-10 21:02 UTC
Type: <b>Bug</b>

After enabling the "Sticky Scroll" feature, C# classes and methods that contain Attributes are displayed incorrectly on the "sticky line".
The definition of one of the attributes is displayed on the "sticky line", instead of the class/method name.

![cOl4SojLk7](https://user-images.githubusercontent.com/7851513/184019323-99203993-8e6f-4b76-8c90-9faa24859a10.png)

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.15.57.1-microsoft-standard-WSL2

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.66.3
vscode-icons|vsc|11.15.0
namespace|adr|1.1.2
prettier-vscode|esb|9.5.0
rest-client|hum|0.25.0
jwt-decoder|jfl|1.2.0
csharp|ms-|1.25.0
hexeditor|ms-|1.9.8
markdown-preview-enhanced|shd|0.6.3
stately-vscode|sta|1.9.2

</details>

**Comment by gjsjohnmurray** [comment] 2022-08-10 21:56
A change in this area will appear in tomorrow's Insiders release. If you are able to test your use case in that please report back gere.

**Comment by aiday-mar** [comment] 2022-08-11 07:06
Thank you @gjsjohnmurray for commenting that. Indeed this is a duplicate of issue https://github.com/microsoft/vscode/issues/157405.

**Closed by aiday-mar** 2022-08-11 07:06 UTC
Labels: new release
