### ISSUE TITLE
stuck at Initializing JS/TS language features

### ISSUE THREAD

**Issue by vikrant-pune** [microsoft/vscode#83357] opened 2019-10-26 16:59 UTC
VSCode Version:
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.0-19-generic
- OS Version: Ubuntu 19.10

Steps to Reproduce:
* Open VS Code 
* Navigate to Interactive Playground

status bar is stuck at Initializing JS/TS language features

Console from Developer tools shows:

```
/usr/share/code/reso…esktop.main.js:1521   ERR <semantic> TypeScript Server Error (3.6.3)
Cannot read property 'lineOffsetToPosition' of undefined
TypeError: Cannot read property 'lineOffsetToPosition' of undefined
    at IOSession.Session.getStartAndEndPosition (tsserver.js:135093:48)
    at IOSession.Session.extractPositionOrRange (tsserver.js:135002:35)
    at IOSession.Session.getApplicableRefactors (tsserver.js:135013:87)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133868:61)
    at tsserver.js:135256:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135247:28)
    at IOSession.Session.executeCommand (tsserver.js:135256:33)
    at IOSession.Session.onMessage (tsserver.js:135279:35)
    at Interface.<anonymous> (tsserver.js:136594:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <semantic> TypeScript Server Error (3.6.3)
````

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-10-28 18:22
Duplicate of #81059

Fixed in current insiders builds

**Closed by mjbvz** 2019-10-28 18:22 UTC
