### ISSUE TITLE
Refresh causes a crash 1.31.1

### ISSUE THREAD

**Issue by Topthinking** [Microsoft/vscode#69631] opened 2019-03-01 03:40 UTC
Refresh causes a crash
As shown in figure
Often appear

vscode version: 1.31.1

![image](https://user-images.githubusercontent.com/13382821/53614976-b7ac9a00-3c16-11e9-9a44-260496826427.png)

**Comment by rebornix** [comment] 2019-03-01 04:46
Duplicate of 
https://github.com/Microsoft/vscode/issues/68424

**Closed** 2019-03-01 04:47 UTC
Labels: *duplicate
