### ISSUE TITLE
Align buttons in the scm panel

### ISSUE THREAD

**Issue by eunjae-lee** [microsoft/vscode#90719] opened 2020-02-14 19:28 UTC
Hi all,
There are buttons in the scm panel like, stage change, discard change, etc. 
They are on the same x coordinate. Could you align them?
It's hard to describe in words. The following GIF should make more sense.
https://twitter.com/eunjae_lee/status/1228265926027599872?s=21

**Comment by IllusionMH** [comment] 2020-02-14 22:51
Duplicate of #88556

**Closed** 2020-02-18 07:58 UTC
