### ISSUE TITLE
VS Code Marketplace blocked by the Indonesian government

### ISSUE THREAD

**Issue by reinhart1010** [microsoft/vscode#196147] opened 2023-10-21 03:37 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1 (accessed from https://github.dev)
- OS Version: macOS Sonoma 14.0

Steps to Reproduce:

1. Install an extension from the official Visual Studio Marketplace using an Indonesian ISP, most preferred using those with [deep packet inspection enabled](https://github.com/bebasid/KominFudge#memilih-isp-yang-tidak-ketat) (e.g. CBN, Telkom Indonesia).
2. Note that the extension repository is browseable, but attempting to download them will return an error.

A small investigation suggests that this is caused by a SSL error, and a DNS scan clearly suggests that this blocking has been done on behalf of the Indonesian government. However, neither `ms-vscode.vscode-unpkg.net` nor `vscode-unpkg.net` is mentioned on the [official blocklist](https://trustpositif.kominfo.go.id).

<img width="758" alt="Screenshot 2023-10-21 at 10 30 22 AM" src="https://github.com/microsoft/vscode/assets/17312341/e68e6f6d-ecc9-4fe5-99a2-fbc7b6929301">

![image](https://github.com/microsoft/vscode/assets/17312341/32ae2fa1-ebfa-4850-adc6-e44503192fca)

<img width="1122" alt="image" src="https://github.com/microsoft/vscode/assets/17312341/ce9874bf-31c0-4c47-872a-9510b4bd1fa5">

![image](https://github.com/microsoft/vscode/assets/17312341/b79eaef5-0d16-4aa6-b035-77e8e90876b6)

**Comment by isidorn** [comment] 2023-10-26 09:33
@joaomoreno looks like Indonesia is blocking `vscode-unpkg`. Thoughts on what to do?

@reinhart1010 can you confirm that if you download the VS Code app, and you install the extension in the app from the Marketplace everything works fine? You only see issues from `github.dev`?

**Comment by reinhart1010** [comment] 2023-10-30 08:29
Hi, I can localize root cause this problem into one specific ISP (CBN). Since this is no longer an issue for other Indonesian ISPs (tested on Indosat, Moratelindo, Smartfren, XL Axiata), feel free to close this issue if necessary.

**Comment by isidorn** [comment] 2023-10-30 09:01
Ok, so it sounds like the issue is fixed. Thank you. Closing this.
If needed, @joaomoreno can still reopen

**Closed by isidorn** 2023-10-30 09:01 UTC
