### ISSUE TITLE
Why are string values when copied from the debug pane surounded with quotation marks?

### ISSUE THREAD

**Issue by escamoteur** [microsoft/vscode#81051] opened 2019-09-17 14:09 UTC
Hi,

currently when I select copy value from the context menu of the debug pane on a String variable it adds a `"` at the beginning and end of the real value.
For me this is wrong behavior because the value of the variable is just the string and nothing else.
Especially if you copy an url and paste it into the browser/postman you always have to remove the quotes.

Can this be changed?
Cheers
Thomas 

https://github.com/Dart-Code/Dart-Code/issues/1990

**Comment by isidorn** [comment] 2019-09-18 16:05
We are not adding " at the begging and end of the real value. We are simply copying what the debug adapter is giving us.
In this case it seems the debug adapter is giving the value with the quotes thus we write the quotes.
Code pointer if you want to investigate more https://github.com/Microsoft/vscode/blob/9c85ca3757812664246e009403320ea54bbdd89c/src/vs/workbench/contrib/debug/browser/debugActions.ts#L401

Point being, I disagree and I think the value should be full as presetned by the debug adapter. The copy value should not massage it.

**Comment by escamoteur** [comment] 2019-09-18 16:18
@DanTup What do you think?

**Comment by DanTup** [comment] 2019-09-18 16:27
It *is* the Dart extension adding these quotes, however the behaviour is exactly the same in TypeScript. The issue is that VS Code doesn't allow "Copy Value" to have a different representation from what's shown in the watch/variables window.

It is *good* that debug adapters wrap quotes around them, so you can see when they are strings:

<img width="176" alt="Screenshot 2019-09-18 at 5 24 17 pm" src="https://user-images.githubusercontent.com/1078012/65166727-29282a80-da39-11e9-9934-8273ccb72e25.png">

However if the user chooses "Copy Value" from the context menu, the quotes (and any escaping, like `\n` instead of literal newlines) are *probably* unwanted.

I think this is what https://github.com/microsoft/vscode/pull/71666 was trying to solve, but it was rejected as something to fix in extensions when they can contribute their own commands to the menu.

Personally I think it is a gap in Code - I think having quotes wrapped around quotes but copying the value without them is something that all languages would like and not something that should be implementing ad-hoc (and potentially differently) by them all.

@isidorn how about allowing the DA to return two strings, or some additional metadata that would allow VS Code to better present the data without affecting copying the value (for example allowing us to declare it's a string and should be wrapped in quotes)?

**Comment by isidorn** [comment] 2019-09-19 08:22
fyi @weinand for DA request for two strings.
This is a fair feature request, however not currently on the plan, thus assigning to backlog.

**Closed** 2019-10-09 10:38 UTC
Labels: *out-of-scope, debug, feature-request

**Comment by escamoteur** [comment] 2019-10-09 10:50
@isidorn why do close this? I still think an absolute reasonable request.
Would it be so difficult to implement this?

**Comment by isidorn** [comment] 2019-10-09 10:54
Hi. We close this since we have no plans to address it in the forseable future. 
Just because something might be easy to implement does not mean we want it to be part of VS Code.
I do not think this should be in the core functionality, however we might reconsider and reopen this in the future.
Hope that makes sense

**Comment by escamoteur** [comment] 2019-10-09 11:08
The problem is that plugins like Dart Code cannot address this without infrastructure from code like @DanTub explained.
