### ISSUE TITLE
Non-native full screen mode not working with external monitor

### ISSUE THREAD

**Issue by ferdaber** [microsoft/vscode#98844] opened 2020-05-29 23:02 UTC
Issue Type: <b>Bug</b>

I have two monitors:
- A standard Macbook Pro Retina display (lowest scaling settings, highest DPI)
- A 4K external monitor (27")

When I try to enter non native fullscreen mode on my external monitor, it will go into full screen, and then suddenly switch back to my laptop's monitor and full screen there. Attempting to retry it will always "snap" the app back into the laptop's monitor.

Restarting the app doesn't seem to help. The thing that I can consistently do is move the unmaximized window into one monitor, and then toggle off the non-native full screen setting in that window to force a restart of VS Code, and then retoggle it back on in that monitor and it will stay. Once it's on that monitor it seems to "stick" to it and the reverse issue will happen (attempting to enter full screen on the laptop monitor snaps the app back to the external monitor).

Exact steps in list form for the workaround (given monitors A and B):
- in **monitor A**, enter non-native fullscreen mode.
- Code maximizes, and snaps into _monitor B_ maximized.
- go into User Settings, and toggle on the Native Full Screen setting
- have Code restart, and when it restarts, enter native fullscreen mode in **monitor A**
- while in native fullscreen mode in **monitor A**, toggle off the Native Full Screen setting
- have Code restart again, and now Code's window is reloaded into non-native fullscreen mode in **monitor A**
- attempting to maximize Code in _monitor B_ now results in Code snapping back into **monitor A** maximized

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 4|
|Memory (System)|16.00GB (1.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.21.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
prettier-vscode|esb|4.7.0
file-icons|fil|1.0.24
auto-rename-tag|for|0.1.3
code-runner|for|0.10.0
vscode-pull-request-github|Git|0.16.0
gc-excelviewer|Gra|2.1.35
rest-client|hum|0.23.2
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|0.0.29
endwise|kai|1.4.2
terraform|mau|1.4.0
vscode-language-babel|mgm|0.0.27
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.2.1
python|ms-|2020.5.80290
debugger-for-chrome|msj|4.12.8
show-offset|ram|0.0.4
ruby|reb|0.27.0
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|0.12.3
code-settings-sync|Sha|3.4.3
shader|sle|1.1.4
guides|spy|0.9.3
sort-lines|Tyr|1.9.0
vscode-ruby|win|0.27.0
markdown-all-in-one|yzh|3.0.0

(5 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2020-05-30 07:15
@deepak1556 we have code for non-native fullscreen to detect when monitor change:

https://github.com/microsoft/vscode/blob/b2cb8682f9c589e8e05e21621d98745c5314bd55/src/vs/code/electron-main/window.ts#L438-L460

With the following explanation:

> Simple fullscreen doesn't resize automatically when the resolution changes so as a workaround
> we need to detect when display metrics change or displays are added/removed and toggle the
> fullscreen manually.

I see that a `display-metrics-changed` is fired as soon as I enter fullscreen, even native fullscreen. I would not expect that to happen. My understanding was that this event is only fired when the display resolution or metrics change?

**Comment by bpasero** [comment] 2020-06-03 06:56
The fix for https://github.com/microsoft/vscode/commit/7fe821d6d6663b4465a175eb8ff0b2bdf1f82994 actually should also fix this issue. But needs verification.

**Comment by bpasero** [comment] 2020-06-09 07:16
**To verify:** follow steps as outlined in https://github.com/microsoft/vscode/issues/98844#issue-627588485 on macOS.

**Comment by dbaeumer** [comment] 2020-06-09 07:18
@sandy081 @weinand @isidorn Is someone of you able to verify this (needs a specific setup on the Mac). Is the last unverified bug we have for May. Thanks!

**Comment by weinand** [comment] 2020-06-09 10:04
@ferdaber this issue should be fixed in Insiders. It would be great, if you could verify that this works for you now.

**Comment by weinand** [comment] 2020-06-09 10:05
I'll try to verify this too (but might fail because my setup is slightly different).

**Comment by ferdaber** [comment] 2020-06-09 12:58
I was able to verify that the fix worked, but I did notice that when exiting fullscreen on my external monitor, the non-maximized window jumps back to my previous monitor (the one where the app first opened).

**Comment by bpasero** [comment] 2020-06-09 15:39
@weinand this requires `"window.nativeFullScreen": false`, forgot to explicitly mention that, sorry.

@ferdaber to clarify, you say the same window that leaves fullscreen jumps to the first monitor? Or another window jumps?

**Comment by ferdaber** [comment] 2020-06-09 16:53
The same window that leaves fullscreen jumps to the first monitor.

So if you open VS Code from scratch, and it opens on monitor A, if you move that VS Code window to monitor B, and go into fullscreen, and exit it, it will jump to monitor A. (The previous issue of the window going into fullscreen and jumping into monitor A is now fixed).

**Comment by bpasero** [comment] 2020-06-09 16:56
Ok then maybe another case to look into.

**Comment by bpasero** [comment] 2020-06-10 10:01
I was able to reproduce the issue even with standalone Electron and filed https://github.com/electron/electron/issues/24048

Since the original issue is fixed and verified, closing again.

**Closed by bpasero** 2020-06-10 10:01 UTC
Labels: bug, workbench-window
