### ISSUE TITLE
Getting error message "Failed to terminate running task" when trying to terminate the running task.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4684] opened 2016-03-25 22:58 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1.  launch app and open a folder which contains .less file.
2. Configure task runner from command palette and update task.json for below section:
"tasks": [
        {
            "taskName": "install",
            "args": ["install","less"]
        },
3. Now save the updated file and press F1 and type : Run task
4. Select "Install" option from the list.
5. Verify you can see task running icon display in the status bar.
6. Now try to terminate the current running task. (Try to execute new task and it will show the pop-up to terminate running task. ).
7. Click on "Terminate Running task".
![image](https://cloud.githubusercontent.com/assets/17735796/14055818/32e56542-f2a2-11e5-87f8-cac54c12f9dd.png)

Actual:
1. Throwing error message like :  Failed to terminate running task
2. Output window it is displaying message like: 
The task 'install' was terminated per user request.
![image](https://cloud.githubusercontent.com/assets/17735796/14055710/449fa55a-f2a1-11e5-900a-bca04289fcc2.png)

**Comment by dbaeumer** [comment] 2018-10-16 15:11
The happened with the old task 0.1.0 and I am not able to reproduce with the new 2.0.0 task system. Closing as obsolete.

**Closed** 2018-10-16 15:12 UTC
Labels: tasks
