### ISSUE TITLE
Issue Reporter jumps to 500 screen after clicking on Preview on Github

### ISSUE THREAD

**Issue by doogie99** [microsoft/vscode#73542] opened 2019-05-09 17:19 UTC
- VSCode Version: 1.33.1
- OS Version: Windows 10 (1809)

Steps to Reproduce:

1. Click Help | Report Issue
2. Select Bug Report, Visual Studio Code
3. Enter Title and some details under Steps to Reproduce.
4. Click Preview on Github

Does this issue occur when all extensions are disabled?: 
No

![extensions](https://user-images.githubusercontent.com/877070/57473035-26782600-724c-11e9-8b1a-98f2327e8f5d.PNG)

**Comment by RMacfarlane** [comment] 2019-05-09 20:48
Duplicate of https://github.com/microsoft/vscode/issues/70343, I've reached out to GitHub about this

**Closed by RMacfarlane** 2019-05-09 20:48 UTC
Labels: extensions
