### ISSUE TITLE
Does tasks.json load from outside the .vscode folder

### ISSUE THREAD

**Issue by aeos** [microsoft/vscode#41589] opened 2018-01-14 03:50 UTC
From the documentation https://code.visualstudio.com/docs/editor/tasks it hints that Visual Code will autodetect various project tasks such as gulp, grunt and npm. However it is not clear whether or not Visual Code will detect task.json files nested inside a project.

Currently, I can only define the task.json file in .vscode/ which is not distributed within the repository. Is there a way to include project specific task.json files outside of .vscode?

**Comment by dbaeumer** [comment] 2018-01-15 07:56
It currently only detects gulp, grunt and npm file in the root folder of the workspace.

**Comment by alexr00** [comment] 2019-10-08 14:52
Duplicate of https://github.com/microsoft/vscode/issues/60043

**Closed by alexr00** 2019-10-08 14:52 UTC
Labels: feature-request, tasks
