### ISSUE TITLE
Corrupted VS Code terminal after window resized.

### ISSUE THREAD

**Issue by RoadToDream** [microsoft/vscode#178190] opened 2023-03-24 02:31 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:  1.76.2
- OS Version: Windows 11 22H2 build 22621.1413

Steps to Reproduce:

1. Open VS Code from any folder 
2. Enter any command and click enter.
3. Maximize VS Code window(not maximize integrated terminal window, which will corrupt the output also but is tracked in another issue).
4. Cursor will be off-position and overwrite my primary prompt. 
Video attached below:

https://user-images.githubusercontent.com/8088354/227409270-91d7e697-fa35-4f0e-b265-6bbb24eebb7e.mp4

**Comment by Tyriar** [comment] 2023-03-24 17:17
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2023-03-24 17:17 UTC
Labels: terminal-rendering

**Comment by RoadToDream** [comment] 2023-03-24 18:02
Thank you for pointing out the root cause to the issue, will forward to terminal.
