### ISSUE TITLE
A Javascript error occurred in the main process.

### ISSUE THREAD

**Issue by lingshf** [microsoft/vscode#137842] opened 2021-11-25 03:26 UTC
Does this issue occur when all extensions are disabled?: Yes

While search this, we can find many others raise this issue before, but no solution....
e.g. https://github.com/microsoft/vscode/issues/137046

Reinstall can resolve this issue. However, it happens again after installing updates. It is annoying as always need to reinstall...

Can someone help to check and get a solution?

![image](https://user-images.githubusercontent.com/41336377/143374651-b50ecad3-e451-44e5-98e3-7f376f4e4b7c.png)

**Comment by lingshf** [comment] 2021-11-25 03:35
It is unbelievable an editor cannot event been launched. The issue is so huge and so many user run into, but no solution... UNBELIEVABLE!

**Comment by egamma** [comment] 2021-11-25 08:17
/duplicate of #137353 @lingshf pls see this issue for how you can help us to track down the issue.

**Closed by egamma** 2021-11-25 08:17 UTC
