### ISSUE TITLE
Terminal does not handel long commands, breaks line into same line even though there is more space.

### ISSUE THREAD

**Issue by soerendip** [microsoft/vscode#123003] opened 2021-05-05 15:37 UTC
- VS Code Version: I am on Win10 remotely connected to a Linux (Ubuntu) server
- OS Version: Win10 Pro (19042.928) , 4.15.0-74-generic #84-Ubuntu

Steps to Reproduce:

1. Type a longer command in the terminal having the window open for some time
2. v1.55.2 (cannot copy-paste from About popup).

![image](https://user-images.githubusercontent.com/3391614/117168189-2b153d80-ad85-11eb-8730-c8a03d419765.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment] 2021-05-05 17:30
Duplicate of #120810

**Closed by meganrogge** 2021-05-05 17:30 UTC
