### ISSUE TITLE
Notification for New Color Theme Installation

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#68362] opened 2019-02-10 14:36 UTC
If I install a new File lcon Theme, there will be a notification at the bottom right corner, so I can easily and directly enable it. However, there won't be any prompt if I install a new Color Theme.

I noticed that there would be more than one theme for a theme extension. I think it is still necessary to give a notification, at least let the user know the theme is installed successfully.

* VS Code version: Code - Exploration 1.32.0-exploration (9a424426327a0662529fd8c5d7e0d476f67f6aab, 2019-02-08T07:31:22.415Z)
OS version: Windows_NT x64 10.0.18334

**Comment by sandy081** [comment] 2019-02-12 14:49
Duplicate of https://github.com/Microsoft/vscode/issues/68408

**Closed** 2019-02-12 14:49 UTC
Labels: *duplicate, themes

**Comment by byyxx128** [comment] 2019-02-15 20:57
I opened the issue earlier... OK, it doesn't matter.
But what I expect is **not** like the one mentioned here https://github.com/Microsoft/vscode/issues/68408.
Actually, this one is good. But I still support to use a notification/prompt at right-bottom corner.
Because the is not easy to attract.
