### ISSUE TITLE
Formatting HTML documents broken after today's update

### ISSUE THREAD

**Issue by lorenjerickson** [Microsoft/vscode#57549] opened 2018-08-29 22:12 UTC
Issue Type: <b>Bug</b>

Open an HTML document, attempt to format it (Alt+Shift+F).  Not that difficult.

I get the following error every time.  The HTML document in question is perfectly valid. 

ReferenceError: last_token is not defined
    at m.beautify (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:93697)
    at e.exports (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:87722)
    at t.indent_size (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:105314)
    at Object.$e [as format] (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:105328)
    at Object.format (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:179024)
    at Object.t.format (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:182069)
    at Object.<anonymous> (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:122231)
    at c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:115360
    at Object.next (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:115465)
    at a (c:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:7:114211)

If you are gong to entice me onto the Insider train, and then nag me EVERY DAY to update VS Code DO NOT break my dev enviornment in the process.  If you can't catch something like this through some kind of test automation then you haven't earned the right (or trust necessary) to update my environment. 

VS Code version: Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:18:47.523Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (7.77GB free)|
|Process Argv|C:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.38
code-beautifier|mic|2.1.0
debugger-for-chrome|msj|4.9.0

</details>

**Comment by dbaeumer** [comment] 2018-08-30 07:39
@aeschli the second complaining about missing HTML formatter.

**Comment by aeschli** [comment] 2018-08-30 12:46
duplicate of #57445

**Closed by aeschli** 2018-08-30 12:46 UTC
Labels: html, important
