### ISSUE TITLE
VSCode changed my colors

### ISSUE THREAD

**Issue by webdeveloperpr** [microsoft/vscode#94857] opened 2020-04-10 02:39 UTC
My colors are all messed up after updating. Can we revert that change? I don't care about color semantics. Please do not change theme colors!

**Comment by webdeveloperpr** [comment] 2020-04-10 02:44
How can you disable this?

**Comment by webdeveloperpr** [comment] 2020-04-10 02:51
Here is an image that shows how to disable this crap. Hopefully it saves someone 30 minutes of searching through settings.



<img width="1100" alt="Screen Shot 2020-04-09 at 10 49 07 PM" src="https://user-images.githubusercontent.com/7534346/78957812-5d863580-7ab4-11ea-9a33-afcd84a14e58.png">

**Comment by RMacfarlane** [comment] 2020-04-10 05:14
Duplicate of https://github.com/microsoft/vscode/issues/90379

**Closed** 2020-04-10 05:14 UTC
Labels: *duplicate
