### ISSUE TITLE
No information about errors displayed in Problems panel or Explorer when document is not open

### ISSUE THREAD

**Issue by fantaclaus** [microsoft/vscode#78511] opened 2019-08-05 15:19 UTC
Issue Type: <b>Bug</b>

1. open Problems panel
2. create document 1.ts
3. enter any incorect code

Now you can see some errors in Problems panel. 

Also, the Explorer displays the file name in red with number of errors at right side.

4. close document

All inforamtion about errors disappears: Problems panel is empty, file list displays file name with default color and no number of errors at the right.

**What I expect (and what was before):**

Information about any error is displayed until the error is fixed, even if document is not open.

Also I expect that errors are displayed when I open a folder (project) and no documents open yet.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:58:59.274Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.43GB free)|
|Process Argv|D:\tmp\tstest|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-icons|jam|0.3.1
classic-asp-html|jtj|0.1.1
python|ms-|2019.6.24221
seti-icons|qin|0.1.3

</details>

**Comment by IllusionMH** [comment] 2019-08-05 16:01
Looks like duplicate of #13953

**Closed** 2019-08-05 16:32 UTC
Labels: *duplicate

**Comment by fantaclaus** [comment] 2019-08-05 16:37
It is not a duplicate!
It worked in version Version: 1.28.2
but now it is broken. So it's a bug.

**Comment by octref** [comment] 2019-08-05 17:02
> But the only thing I've forgot to mention: You have to compile the project at least once to have errors not hidden.

That's how it's designed. When you run a task, if it outputs errors, they'd always be shown at problems panel. If you run a project compilation in a.ts, it should show the error even if a.ts is closed.

https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher

**Comment by fantaclaus** [comment] 2019-08-05 17:19
@octref,

> That's how it's designed. When you run a task, if it outputs errors, they'd always be shown at problems panel. If you run a project compilation in a.ts, it should show the error even if a.ts is closed.
> 
> https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher

but it doesn't work anymore.

When I close all documents, Problems panel gets empty.

**Comment by octref** [comment] 2019-08-05 17:36
@fantaclaus I see the behavior. Upvote and subscribe to #47386 please.

**Comment by gjsjohnmurray** [comment] 2019-08-05 17:38
@fantaclaus I think it was changed in #59363
