### ISSUE TITLE
ClearType not used for all visible text

### ISSUE THREAD

**Issue by rblath** [Microsoft/vscode#13662] opened 2016-10-13 09:47 UTC
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: ms-vscode.cpptools-0.9.2, ms-vscode.csharp-1.4.1

Steps to Reproduce:
1. Open VS Code
2. E.g. Select Extensions and compare text in Search Field with text in the list

Screenshot:
![visualstudio_cleartype_issue](https://cloud.githubusercontent.com/assets/11315009/19344487/ab1a7070-913a-11e6-8aae-5b8aa0299d97.png)

**Comment by rblath** [comment] 2016-10-13 09:51
Here is a magnification of the issue:
![visualstudio_cleartype_issue2](https://cloud.githubusercontent.com/assets/11315009/19344650/4f7a749e-913b-11e6-9ea2-d6908dd37417.png)

**Comment by bpasero** [comment] 2016-10-13 16:10
Electron update?

**Comment by joaomoreno** [comment] 2016-10-14 06:24
So it seems. @rblath Do you see the same behaviour in 1.5?

**Comment by bpasero** [comment] 2016-10-14 06:44
@rblath and how about other trees like the explorer, does it look ok there? what about the editor?

**Comment by rblath** [comment] 2016-10-14 15:22
@bpasero here are a few more screenshots:

![visualstudio_cleartype_issue3](https://cloud.githubusercontent.com/assets/11315009/19392627/df011662-9231-11e6-9059-779fedf18f9a.png)

![visualstudio_cleartype_issue4](https://cloud.githubusercontent.com/assets/11315009/19392832/b00ee770-9232-11e6-8525-14f5966ae6fb.png)

**Comment by rblath** [comment] 2016-10-14 15:26
The terminal is interesting, the header is using ClearType but the content is not:

![visualstudio_cleartype_issue5](https://cloud.githubusercontent.com/assets/11315009/19393007/427a6b48-9233-11e6-8deb-96b19221ad35.png)

**Comment by rblath** [comment] 2016-10-14 15:34
@joaomoreno I don't have the zip of this version laying around anymore, but I am pretty sure the issue existed there as well.
I also noticed that the plain electron shell has had the same problem for some time.

**Comment by bpasero** [comment] 2016-10-14 15:50
If this reproduces with electron then this should be reported to their repository https://github.com/electron/electron

**Comment by rblath** [comment] 2016-10-18 14:41
Sure, this is probably an electron problem at the core, but it also matters how electron is used to render the text. Why else would a headline or text field be rendered correctly but normal text is not?

**Comment by bpasero** [comment] 2016-11-11 17:58
@rblath I am playing around with a newer version of Electron and was wondering if you could give this build a try that includes it to see if something has changed with this issue: https://az764295.vo.msecnd.net/insider/d47c8ba23ff35913052db316aaeef1bb92b0dd99/VSCode-win32-1.8.0-insider.zip

Thanks

**Comment by rblath** [comment] 2016-11-25 16:03
@bpasero Hi Benjamin, I am still having the same issues as described before with the build you provided. Some texts are ClearType enabled and some are not.
![vscode_cleartype_issue1](https://cloud.githubusercontent.com/assets/11315009/20630298/6ba1833a-b330-11e6-8b37-39dd658dba9e.png)
Here is a portion of the screenshot magnified where you can see that the "Terminal" text is ClearType enabled and the "Microsoft" text is not.
![vscode_cleartype_issue2](https://cloud.githubusercontent.com/assets/11315009/20630386/ee5135b4-b330-11e6-8521-1b83bd3bddbf.png)

**Comment by bpasero** [comment] 2016-11-25 16:07
@rblath thanks, I wonder if this issue is now scoped to the terminal alone or do you see it in more places?

**Comment by rblath** [comment] 2016-11-25 16:12
It is also visible in the Explorer, Search, Git, Debug and Extensions view on the left side. The title is always correct but the content is not. The Code Editor however is always correct.

**Comment by bpasero** [comment] 2017-04-10 17:09
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by rblath** [comment] 2017-04-10 18:42
Just tested the new version. Unfortunately the issue is not gone, instead it is now visible in all other areas except the code editor:

![image](https://cloud.githubusercontent.com/assets/11315009/24877033/20cf9914-1e2e-11e7-9a5f-03019a3a254b.png)

**Comment by bpasero** [comment] 2017-04-11 05:19
@rblath I just checked our stable release and I am also not getting sub-pixel anti-aliasing for the tree and other parts, can you compare with stable? When I check back with 1.10, it seems we lost sub-pixel anti-aliasing already with the update to 1.11. Maybe related to our theming work, I have to check...

**Comment by rblath** [comment] 2017-04-11 08:48
@bpasero Actually the screenshot above is from the stable version 1.11.1. Somehow the link you gave me pointed to stable not insider. But anyway, I downloaded the insider version 1.12 and it shows the same behaviour:

![image](https://cloud.githubusercontent.com/assets/11315009/24900517/69cb7d6a-1ea4-11e7-8f78-08021e89230c.png)

**Comment by bpasero** [comment] 2017-04-11 16:01
I looked into it and it seems our work on the theming has made it worse for people. Specifically https://github.com/Microsoft/vscode/commit/7db643a5bbf1f633939adf30ff7cd43b7cc29c5e seems to have caused this by no longer setting a background on the workbench container. I am extracting https://github.com/Microsoft/vscode/issues/24532 to at least try to get back to our previous state.

The list widget and terminal is still an open issue.

**Comment by bpasero** [comment] 2017-04-12 12:06
@joaomoreno looks like the list widget is also using `translate3d`, would it possible to apply a similar fix as we do now in the editor to disable it when we are running scaled? see https://github.com/Microsoft/vscode/issues/24483#issuecomment-293521870 for more details.

Given that we use the list widget more and more (SCM, IntelliSense) it seems odd that we have fuzziness in those when the rest looks ok.

**Comment by joaomoreno** [comment] 2017-04-12 13:50
Created #24599

**Comment by bpasero** [comment] 2017-04-12 14:09
@joaomoreno awesome ❤️

**Comment by Tyriar** [comment] 2017-04-17 19:53
It's never worked in the terminal, tracked in https://github.com/Microsoft/vscode/issues/17827

**Comment by bpasero** [comment] 2017-04-18 14:09
Closing since the original issue in the list is now fixed. Opened https://github.com/Microsoft/vscode/issues/24957 for remaining parts.

**Closed by bpasero** 2017-04-18 14:09 UTC
Labels: bug, upstream, workbench
