### ISSUE TITLE
CSS hover shows "<element>" in error red

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59510] opened 2018-09-27 01:09 UTC
Issue Type: <b>Bug</b>

**Repo**
1. In a css file with the contents: 

```css
.foo {
  
}
```

1. Hover over `.foo`

**Bug**
The hover shows `<element>` in a bright red:

![screen shot 2018-09-26 at 6 06 28 pm](https://user-images.githubusercontent.com/12821956/46117639-2775af00-c1b7-11e8-8bfb-f2476d35841a.png)

This is because it is scoped as `invalid.illegal.unrecognized-tag.html`

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:25:01.336Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|

</details>

**Comment by aeschli** [comment] 2018-09-27 07:29
Caused by https://github.com/textmate/html.tmbundle/issues/92

**Comment by aeschli** [comment] 2018-10-12 08:43
fixed in lastest

**Closed by aeschli** 2018-10-12 08:43 UTC
Labels: insiders
