### ISSUE TITLE
Vertical scroll is not smooth in dell inspiron 5577

### ISSUE THREAD

**Issue by sundar-pacehcm** [Microsoft/vscode#44279] opened 2018-02-23 15:35 UTC
### Issue Type
Bug

### Description

Hello,

The vertical scroll is not smooth in my dell inspiron 5577 gaming laptop. Scroll works fine in my other laptop. 

Just open any lengthy file in a dell inspiron  5577

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|7.87GB (2.26GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by RMacfarlane** [comment] 2018-02-25 19:35
Duplicate of https://github.com/Microsoft/vscode/issues/13612

As a workaround, try launching code from a terminal with the `--disable-gpu` flag. This is an upstream issue with electron, we're working on upgrading to a new version.

**Closed by RMacfarlane** 2018-02-25 19:35 UTC

**Comment by sundar-pacehcm** [comment] 2018-02-26 01:49
@RMacfarlane  Thanks for the temporary solution. Works perfectly
