### ISSUE TITLE
Exploration icons: Focus on icons is invisible

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#74538] opened 2019-05-29 11:14 UTC
Testing https://github.com/microsoft/vscode/issues/74320

With the X not selected:
![image](https://user-images.githubusercontent.com/38270282/58552789-88a4c500-8213-11e9-836d-baad0ce64e77.png)
Focus on X:
![image](https://user-images.githubusercontent.com/38270282/58552831-9eb28580-8213-11e9-91eb-c136322d6f6d.png)

This is what focus on the X looks like in insiders:
![image](https://user-images.githubusercontent.com/38270282/58552864-b1c55580-8213-11e9-9241-e50b1d02cc50.png)

**Comment by alexr00** [comment] 2019-05-29 11:16
The view toolbar has the same problem. Its easy to check in the outline view.

**Comment by bpasero** [comment] 2019-05-29 13:18
@alexr00 can you check if this reproduces when you pick "None" as file icon theme? Wondering if this is too related to the icon exploration.

**Comment by alexr00** [comment] 2019-05-29 14:07
Does not repro with file icon theme none.

**Comment by misolori** [comment] 2019-06-04 02:48
After looking into this more it turns out that I can't use `mask` and `outline` together (the mask applies to the entire element). That means that the icons can't have a focus element. There is a way around this which is to apply the mask on a pseudo element like `::before` but that means having to rewrite my entire stylesheet, which I'm not sure I'll have time for. 

However, this is just for the exploration to cut down on having to export multiple icons. So when we go to implement the icon changes I'll be using the `background-image` (like we do now) and avoid the mask.

**Comment by misolori** [comment] 2019-07-01 16:18
This is now fixed on master:

<img width="209" alt="image" src="https://user-images.githubusercontent.com/35271042/60451587-3b848c00-9be1-11e9-9f6a-72ac82f85083.png">

**Closed by misolori** 2019-07-01 16:18 UTC
Labels: icons, ux
