### ISSUE TITLE
Make "Code collapse buttons" also visible at the end

### ISSUE THREAD

**Issue by RUSshy** [microsoft/vscode#84837] opened 2019-11-14 15:15 UTC
_I did my best to look and find if there is no similar issue, but i don't know exactly how this "code collapse button" is called, my apologies if this was already requested_

In long methods, it is annoying to have to scroll up to find the collapse code button..

I know there is a shortcut for everything, but i can never remember them, so i prefer having UI guides

In Jetbrains IDEs it is possible, take a look at this screenshot:

![image](https://user-images.githubusercontent.com/18348637/68869723-ecf00e00-06f9-11ea-89b2-94bcc632f589.png)

You can see the buttons are visible for both begin, and end, as well as a visual guide for the right scope

It would be cool to have same thing in vscode

**Comment by RUSshy** [comment] 2019-11-14 15:16
If you know how the buttons are called please let me know, or edit the title, thanks

**Comment by gjsjohnmurray** [comment] 2019-11-14 15:23
/duplicate of #60670 - the commonly used term is 'folding'. Thanks anyway for trying to find similar issues before you posted this.

**Closed** 2019-11-14 15:23 UTC
Labels: *duplicate

**Comment by RUSshy** [comment] 2019-11-14 15:33
thanks @gjsjohnmurray
