### ISSUE TITLE
css synchronize changes(git)

### ISSUE THREAD

**Issue by gustavoalves145** [microsoft/vscode#172801] opened 2023-01-30 13:38 UTC
Type: <b>Bug</b>

When you click in synchronize changes from gitHub, loading animation goes off axis

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.00GB free)|
|Process Argv|--crash-reporter-id cbab1e19-cc0f-4b58-b812-2acfbca56f0b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
GetterAndSetterGenerator|afm|1.0.3
simple-react-snippets|bur|1.2.7
vscode-postgres|cko|1.4.0
bracket-pair-colorizer-2|Coe|0.2.4
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
todo-tree|Gru|0.0.222
error-gutters|Igo|1.0.1
vscode-language-pack-pt-BR|MS-|1.74.12140933
vscode-react-native|msj|1.10.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.23.1
java|red|1.14.0
LiveServer|rit|5.7.9
code-spell-checker|str|2.15.0
code-spell-checker-portuguese-brazilian|str|2.0.10
in-your-face-incredible|TTO|1.1.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
vscode-icons|vsc|12.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30647092
89544117:30613380
pythonsymbol12:30652348

```

</details>

**Comment by lszomoru** [comment] 2023-01-30 20:13
@daviddossett, is this something that you could take a look? Thanks!

**Comment by daviddossett** [comment] 2023-01-31 18:58
Possibly— @gustavoalves145 could you post a recording? Not able to reproduce this on my end.

https://user-images.githubusercontent.com/25163139/215856447-6a078385-b70b-4f2d-b566-ad3a07af3912.mp4

**Comment by gustavoalves145** [comment] 2023-02-01 12:25
notice that the rotation movement is not circular, but oval.
Sorry for the bad quality recording, I couldn't focus only on the specific.

![image](https://user-images.githubusercontent.com/108953623/216041118-aa3a158c-c71b-4efc-8bff-d60461124246.png)
link for recording: https://drive.google.com/file/d/1iGK_6_dvtuWKdWfUm6YFDWxzo5_bmA5i/view?usp=sharing

**Comment by lszomoru** [comment] 2024-12-12 19:10
Duplicate of [#181245](https://github.com/microsoft/vscode/issues/181245)

**Closed by lszomoru** 2024-12-12 19:10 UTC
Labels: bug, git, ux
