### ISSUE TITLE
JavaScript syntax highlighting - ternary operator and string literal 

### ISSUE THREAD

**Issue by 2color** [Microsoft/vscode#7479] opened 2016-06-09 14:19 UTC
- VSCode Version: 1.2.0
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Enter the following syntax into vscode:
```javascript

exports.listNames = (request, reply) => {
  const family = request.params.family
  const status = request.params.status || 'done'
  const branch = (status === 'done') ? `master` : `fixes/${family}`

  const listNames = github.listNames.bind(github, branch)

  listNames(family)
  .then((locales) => { reply(locales) })
  .catch((err) => {
    request.log(['error', 'github'], err)
    reply(err)
  })
}

```
2. Anything following the ```const branch = (status === 'done') ? `master` : `fixes/${family}``` is not highlighted properly

<img width="704" alt="screen shot 2016-06-09 at 16 20 14" src="https://cloud.githubusercontent.com/assets/1992255/15932967/13e4dff4-2e5e-11e6-86f3-0e500428c330.png">

**Comment by nibblesnbits** [comment] 2016-06-09 17:07
+1.  Just noticed this today.

**Comment by aeschli** [comment] 2016-06-13 07:11
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81

**Closed by aeschli** 2016-06-13 07:11 UTC
