### ISSUE TITLE
unexpected debug.log file start to appear again

### ISSUE THREAD

**Issue by lautarobock** [microsoft/vscode#116353] opened 2021-02-10 17:22 UTC
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. open a project (my case angular 11)
2. debug.log files start to appear in the foldes

Does this issue occur when all extensions are disabled?: Yes/No

The bug reported here https://github.com/microsoft/vscode/issues/105191 start to happen again :(

**Comment by gjsjohnmurray** [comment] 2021-02-10 17:35
/duplicate of #115874 and will be fixed in upcoming 1.53.2

**Closed** 2021-02-10 17:36 UTC
Labels: *duplicate
