### ISSUE TITLE
Duplicate using Shift + Alt not Working

### ISSUE THREAD

**Issue by yc9274** [microsoft/vscode#84783] opened 2019-11-14 07:56 UTC
Issue Type: <b>Bug</b>

Recently Updated Code Insiders and this feature looks missing or buggy

VS Code version: Code - Insiders 1.41.0-insider (b6a486e34fe3715f6edec0cdb11138b1672d33bd, 2019-11-14T05:35:51.486Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|2.0.0
vscode-intelephense-client|bme|1.2.3
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
prettier-vscode|esb|3.5.0
adb-interface-vscode|vin|0.6.0

</details>

**Comment by Cow258** [comment] 2019-11-14 10:53
Same issue here

**Comment by IllusionMH** [comment] 2019-11-14 10:54
/confirmed

Looks like new `Go to Next/Previous Symbol" has conflicting shortcuts. Implemented in #84578
In meantime workaround will be to remove shortcut for this command
```json
    {
        "key": "shift+alt+up",
        "command": "-editor.action.gotoPrevSymbol",
        "when": "editorFocus && editorHasDocumentSymbolProvider"
    },
    {
        "key": "shift+alt+down",
        "command": "-editor.action.gotoNextSymbol",
        "when": "editorFocus && editorHasDocumentSymbolProvider"
    }
```
or assigning other shortcut
/cc @jrieken

**Comment by jrieken** [comment] 2019-11-14 11:07
Sorry, for that. I have only checked on Mac. There is a new insiders version (`eccf417b72fc0a632ec2cbd7855a681cdb8c81fa`) which included a fix, commit eccf417b72fc0a632ec2cbd7855a681cdb8c81fa

**Comment by IllusionMH** [comment] 2019-11-14 11:12
@jrieken that was quick! Thanks!
Works as expected in the latest build!

**Comment by jrieken** [comment] 2019-11-14 11:16
Thanks for getting back to me. Closing and verifying.

**Closed by jrieken** 2019-11-14 11:16 UTC
Labels: bug, verified
