### ISSUE TITLE
Git URL not properly resolved

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#36236] opened 2017-10-13 15:41 UTC
I had another instance of this issue https://github.com/Microsoft/vscode-tslint/issues/271. Please see the screen shot and explanation over there.

The git URL resolves to a package.json, but the contents of the package.son shown when opening the URL is the contents of the Changelog.md. This then triggers a JSON validation for a markdown file.

**Comment by egamma** [comment] 2017-10-13 16:20
![image](https://user-images.githubusercontent.com/172399/31555935-32cbfb74-b043-11e7-9abf-9e80c2ff960d.png)

**Comment by egamma** [comment] 2017-10-26 14:55
It happens when I open the files in this sequence

![image](https://user-images.githubusercontent.com/172399/32060210-68d715b6-ba6e-11e7-87cf-05c23da47cc4.png)

**Comment by joaomoreno** [comment] 2017-11-02 08:17
@egamma I can't reproduce. I even tried installing TSLint and checking whether this would surface due to it.

I am pretty sure [this is the only code path](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/uri.ts#L17) in which I create git URIs; and those are always perfectly constructed: the uri path matches the path within the query parameters. I did a code review on the git extension and there's no URI-magic happening (eg: `uri.with({ path: 'something' })`).

So this URI must be generated somewhere else. What extensions do you have installed?

@dbaeumer @aeschli Is the language server/client doing any URI-magic, like taking an existing URI and changing its path (eg: `uri.with({ path: 'something' })`)?

**Comment by dbaeumer** [comment] 2017-11-02 08:37
@joaomoreno there is support to do that but it is off by default. Usually the URI go over the wire using Uri.toString().

**Comment by joaomoreno** [comment] 2017-11-02 08:39
What does that support look like? Do you know if someone uses it?

**Comment by dbaeumer** [comment] 2017-11-02 08:43
If someone does that he passes converter functions to the LanguageClient using the LanguageClientOptions. May be we can use @sandy081 tool to see if this is the case in one of the extensions.

I am not aware of an extension doing this and usually it is not necessary.

**Comment by chrmarti** [comment] 2018-07-17 14:58
I see this when I have changes in the package.json and the CHANGELOG.md:
- Reload window
- Open diff editor for CHANGELOG.md
- Error about package.json shows up in problems panel
- Click on error in problems panel
- 'package.json' with CHANGELOG.md content opens

Doesn't the `git:` URI showing the wrong content imply that the document provider for that scheme got it wrong?

![image](https://user-images.githubusercontent.com/9205389/42825577-9849cf98-89e2-11e8-87ea-09c203936da5.png)

**Comment by joaomoreno** [comment] 2018-07-17 15:30
Excellent @chrmarti huge thanks for the repro steps, I could repro there too.

**Comment by joaomoreno** [comment] 2018-07-17 16:19
This comes from this magic here:

https://github.com/Microsoft/vscode/blob/32bebd313efc979c9dd9d34d87c0671fe5ba4022/extensions/extension-editing/src/extensionLinter.ts#L138-L144

That code is running for any open documents. It should only run for `file` scheme documents.

Assigning to you @chrmarti since it seems you were the last person in here.

**Comment by chrmarti** [comment] 2018-07-23 10:59
@joaomoreno It would seem wrong to only run on 'file' URIs, after all with the file system providers files can have any scheme. I think the 'git' document provider should either provide the correct content for the `git:.../package.json` URI or bail out. Currently it returns the CHANGELOG.md content, which is unexpected.

**Comment by joaomoreno** [comment] 2018-08-02 10:46
Unfortunately, git relies heavily on case sensitivity. I was forced to not use the `path` component of a URI, because it is case insensitive. The git extension gets the actual file path from the `query` component, which is case sensitive.

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/uri.ts

At best, the git extension could throw an error if it detects `path` does not match the expected value from `query`, but I'm not so sure this would fix anything. You'd just get an error.

**Closed** 2018-08-02 13:10 UTC
Labels: bug, extensions

**Comment by ramya-rao-a** [comment] 2018-08-02 18:44
Verified by running from source.
