### ISSUE TITLE
VSCode stays stuck loading autocomplete suggestions on lodash chain method

### ISSUE THREAD

**Issue by RPDeshaies** [Microsoft/vscode#47253] opened 2018-04-05 18:59 UTC
**Description**
When writing the following code

```ts
import * as _ from 'lodash';

const result = _.ma // press autocomplete shortcut
```
You get autocomplete suggestions from VSCode

When writing the following code

```ts
import * as _ from 'lodash';

const result = _.chain([]).ma // press autocomplete shortcut
// or
const result = _([]).ma // press autocomplete shortcut
```
You don't get autocomplete suggestions from VSCode
VSCode gets stuck in a `loading` state for dozens of seconds
The autocomplete shortcut just doesn't work anywhere after that

![image](https://user-images.githubusercontent.com/6224111/38385983-5d2c6e18-38e1-11e8-9b04-ed2b493bee37.png)

- VSCode Version: 1.21
- OS Version: MacOS High Siera 10.13.2

**Steps to Reproduce:**

1. Create a project that uses typescript and NodeJS
2. Add  lodash to your dependencies (I don't think the version matters, but I'm using 4.17.5)
3. Write
```ts
import * as _ from 'lodash';

const result = _.chain([]).ma
```
4. Press the autocomplete shortcut (CTRL+SPACE on my Mac)
5. You see a loading tooltip that doesn't go away, autocomplete doesn't work anywhere and everything feels kinda stuck

**Does this issue occur when all extensions are disabled?: Yes/No**
Yes

**Comment by mjbvz** [comment] 2018-04-09 18:55
I'm unable to reproduce this:

![screen shot 2018-04-09 at 11 54 21 am](https://user-images.githubusercontent.com/12821956/38516765-dc7dbbf0-3bec-11e8-90ae-133fbf9ffa3a.png)

If you run `Go to definition` on `_` in the import, what file is opened?

**Comment by RPDeshaies** [comment] 2018-04-09 19:01
How much time did it take for the intellisense to show up?

> If you run Go to definition on _ in the import, what file is opened?
Here you go: 

```
myrepo/node_modules/@types/lodash/index.d.ts
```

**npm packages versions**

```
    "@types/lodash": "^4.14.106",
    "lodash": "^4.17.5",
```

**Comment by mjbvz** [comment] 2018-04-09 20:42
Thanks. I now see this ts files that are not part of a tsconfig project. @RPDeshaies do you have a `tsconfig.json`?

**Comment by RPDeshaies** [comment] 2018-04-09 20:53
>Thanks. I now see this ts files that are not part of a tsconfig project.

What do you mean?

> @RPDeshaies do you have a tsconfig.json?

I do!

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "skipLibCheck": true,
    "noUnusedLocals": true,
    "jsx": "react",
    "lib": ["es2015", "dom"],
    "outDir": "dist/_temp/typescript"
  }
}

```

**Comment by mjbvz** [comment] 2018-04-09 21:03
Thanks again! I've opened https://github.com/Microsoft/TypeScript/issues/23285 to track this upstream. We'll keep investigating it there

Closing as upstream

**Closed by mjbvz** 2018-04-09 21:03 UTC
Labels: javascript
