### ISSUE TITLE
Exiting in zen mode

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#46040] opened 2018-03-17 22:08 UTC
When closing VSCode in zen mode and opening back up again, you have to reset settings to get back to a non-zen state (e.g. disable centered layout, open sidebar and terminal again, etc.). This occurs even with `"zenMode.restore": false`.

- VSCode Version: 1.21.1
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Open VSCode
2. Ensure zen mode and centered layout is disabled
3. Open sidebar and terminal
4. Enable zen mode
5. Close VSCode
6. Open VSCode
7. Notice that although zen mode is disabled, the sidebar and terminal are hidden, and centered layout is enabled.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2018-03-19 09:34
@jabacchetta thanks for reporting this issue however I can not reproduce in latest since I have pushed some fixes in this area which I believe solve this issue.
Can you please try reproducing this behavior in latest vscode insiders?

**Comment by jabacchetta** [comment] 2018-03-21 14:57
Yes, confirmed, this appears to be fixed in the Insiders build.

**Comment by isidorn** [comment] 2018-03-21 16:00
Thanks for trying it out, closing and adding verified label

**Closed by isidorn** 2018-03-21 16:00 UTC
Labels: needs more info, workbench-layout
