### ISSUE TITLE
Ability to search integrated terminal

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#11507] opened 2016-09-04 02:43 UTC
It would be great if one could search within integrated terminal and debug console

**Comment by isidorn** [comment] 2016-09-05 07:14
Unassigning mysels since this fro debug console this is a dup of https://github.com/Microsoft/vscode/issues/4338

**Comment by Tyriar** [comment] 2017-01-17 22:54
Duplicate of https://github.com/Microsoft/vscode/issues/15198

**Closed by Tyriar** 2017-01-17 22:54 UTC
Labels: feature-request, integrated-terminal
