### ISSUE TITLE
Now way to create a new file in this empty directory

### ISSUE THREAD

**Issue by Klaim** [Microsoft/vscode#72084] opened 2019-04-10 14:58 UTC
Issue Type: <b>Bug</b>

Right now if I try to create a new file in this directory:

 - right click, then "New File": I see the text box open for a fraction of a second and it disappear immediately;
 - clicking on the "New File" button: does nothing.

I'm in an empty directory.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (19.12GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
gitlens|eam|9.6.0
languague-renpy|Luq|0.0.5
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
rewrap|stk|1.9.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
renpy-language-vscode|wil|0.3.0

</details>

**Comment by KexyBiscuit** [comment] 2019-04-11 03:13
I can't repro this on 1.33.0, could you disable all extensions and try again?

**Comment by Klaim** [comment] 2019-04-11 11:20
It looks like it appears randomly: with or without extensions, I manage to reproduce it very rarely when I 
 - create a new directory
 - right click and select "Open in Code"
 - try to create the new file

I'm not sure yet what trigger the issue but so far I managed to reproduce it 1 / 5 times, so it's pretty rare.

I'll update if I find the right repro.

**Comment by isidorn** [comment] 2019-04-11 11:57
Please update with exact repro steps.
Also try to reproduce with vscode insiders https://code.visualstudio.com/insiders/
Since I also can not repro

**Comment by zolamusic** [comment] 2019-04-12 04:19
This behavior also appears in vscode 1.33.1, when GitLens extension enabled.

**Comment by Klaim** [comment] 2019-04-12 11:45
I probably forgot to remove that extension when I tried.

**Comment by isidorn** [comment] 2019-04-12 11:56
Please update with exact repro steps.
Also try to reproduce with vscode insiders https://code.visualstudio.com/insiders/
Since I also can not repro

**Comment by isidorn** [comment] 2019-04-12 11:56
If you can only preoduce with GitLens please file it against that extension

**Comment by Klaim** [comment] 2019-04-12 12:04
Yes, I'll try to confirm soon.

The repro steps are exactly:

1. create a new (empty) directory in window's explorer;
2. right click the directory and select "Open in Code";
3. try to create a new file, either by:
  a. right click the filesystem window, then click "New File": the text area to type the new file name appears then disappear in a frame;
  b. clicking on the "New File" button in the filesystem window: nothing happen;
4. If you dind't see the issue, close Code and retry from step 2 as the issue seems to happen randomly.

**Comment by isidorn** [comment] 2019-04-12 13:41
I can not reproduce with vscode insiders on windows.
Steps 1 and 2 should be completely unrelated. If you can repro you should be able to repro no matter how you open vscode

**Comment by isidorn** [comment] 2019-04-12 13:49
Let's treat as duplicate of #72139
Comment there with more details

**Closed by isidorn** 2019-04-12 13:49 UTC
Labels: file-explorer, needs more info
