### ISSUE TITLE
Syntax highlighting in C++ mode broken by macro

### ISSUE THREAD

**Issue by artagnon** [Microsoft/vscode#11248] opened 2016-08-30 20:19 UTC
- VSCode Version: 1.4
- OS Version: El Capitan

Steps to Reproduce:
Paste this in, and watch the syntax highlighter break:

```c++
#undef _R_
#define ASSERT_OR_NOTE                                                  \
    _R_(opts & NOTEODDITY, opts & NEGATIVE, NOTE_ODDITY, doesNotContainTokens) \
    _R_(opts & NOTEODDITY, !(opts & NEGATIVE), NOTE_ODDITY, containsTokens) \
    _R_(!(opts & NOTEODDITY), opts & NEGATIVE, ASSERT_THAT, doesNotContainTokens) \
    _R_(!(opts & NOTEODDITY), !(opts & NEGATIVE), ASSERT_THAT, containsTokens)
```

**Comment by dbaeumer** [comment] 2016-08-31 07:26
Not sure if we ship the textmate grammar or whether it comes from the C++ extension.

**Comment by aeschli** [comment] 2016-09-01 10:07
Duplicate of https://github.com/atom/language-c/issues/160

**Closed by aeschli** 2016-09-01 10:07 UTC
