### ISSUE TITLE
Creation of debug console slower

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71366] opened 2019-03-28 10:58 UTC
* check https://msit.powerbi.com/groups/2bb9c256-c8ed-47a3-b1be-ebf0c050fb85/reports/2f5bed71-2607-4e0c-8a83-d0f9de023342/ReportSection1f5ac8ab4f061b4a1f8d
* the creation time for the debug console is slower than before

<img width="414" alt="Screenshot 2019-03-28 at 11 58 34" src="https://user-images.githubusercontent.com/1794099/55152497-d25c2b00-5150-11e9-8de4-9092b691a2d8.png">

**Comment by isidorn** [comment] 2019-03-28 11:02
This should be related to us using the new tree.
Assigning to April to investigate.

**Comment by isidorn** [comment] 2019-04-02 14:30
I confirm this. When running out of sources I see a slowdown of 40ms. 
Looking at my changes I could not figure out what caused this, so I went to our good old friend bisect and it points to this commit https://github.com/Microsoft/vscode/commit/4e583c455ad8fd99d482f7502cacb070ee0f8c67

@bpasero can you elaborate on what that commit does and how it could affect startup time of Debug Console? Looking at the changes we are measuring exactly the same thing however we are initialising the services differently so that could affect it, right?

![Screenshot 2019-04-02 at 16 25 57](https://user-images.githubusercontent.com/1926584/55410449-2b1e3000-5564-11e9-8c6b-178e7761d6c5.png)

**Comment by bpasero** [comment] 2019-04-02 16:31
It is possible that there is now stuff happening before the restoring that puts pressure on the UI thread that was not happening before. I suggest to look at the debug viewlet restore time individually in the profiler and see if there is something new popping up in the trace.

**Comment by isidorn** [comment] 2019-04-03 09:49
The difference in the profiles is that in the slow one the `layout` is part of the time (takes around 40ms).

With your commit I see you have changed where the `layout` is being called in the shell. So what happened in the fast version: we were not measuring the layout of the debug repl since this check would not pass [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositePart.ts#L295) 
`ContentAreaSize` would only be set [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositePart.ts#L486) and then we would layout the repl and this layout would not be part of the perf numbers.

With the change in shell you first call layout on the composite part, the `ContentAreaSize` gets set and the `showComposite` of the REPL actually does the layout as it should. Resulting in larger but correct time.

Due to the above closing as will not fix. The change is actually good, since previously we were not measuring the layout costs of the repl.

I did not investigate deeper into why this is not effecting so much the other panels. Might be their layout calls are not so expensive.
fyi @sandy081 since I know there is an issue for the output which might have the same root cause.

Cpu profiles for reference. Remove .zip at end
[fastRepl.cpuprofile.zip](https://github.com/Microsoft/vscode/files/3037997/fastRepl.cpuprofile.zip)
[slowRepl.cpuprofile.zip](https://github.com/Microsoft/vscode/files/3037998/slowRepl.cpuprofile.zip)

**Closed by isidorn** 2019-04-03 09:49 UTC
Labels: debug, debug-console, perf
