### ISSUE TITLE
Debug preLaunchTask halted by {0} process

### ISSUE THREAD

**Issue by wgj** [Microsoft/vscode#24376] opened 2017-04-09 18:38 UTC
Note: I was able to repro many times in a row, but my last two attempts were successful.  glfh.

- VSCode Version: 1.11.1
- OS Version: macOS 10.12.4

Trying to run launch a debug sessions will _sometimes_ be prevented by an unknown running process 

Steps to Reproduce:

1. Attempt to launch debugger with `PreLaunchTask: Build` on non-compiling code. In my case, it was just the wrong file, and no edits are needed to compile:

![screen shot 2017-04-09 at 11 13 28 am](https://cloud.githubusercontent.com/assets/463564/24839773/99e6961e-1d15-11e7-98d3-6de70f6fb671.png)

2. Attempt to launch debugger with the correct/implementation/compiling code

3. Observe error:

![screen shot 2017-04-09 at 11 01 53 am](https://cloud.githubusercontent.com/assets/463564/24839740/067a45ec-1d15-11e7-968e-1f50292513db.png)

4. Observe output of `>Tasks: Show Task Log`:

![screen shot 2017-04-09 at 11 02 27 am](https://cloud.githubusercontent.com/assets/463564/24839747/357946fe-1d15-11e7-9eae-9db3da04fc25.png)

5. Run `>Tasks: terminate Running Task` (but there's no observable output).

6. Subsequent Debug `Launch` attempts fail with same output.

Launch.json snippet:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "preLaunchTask": "build",
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": true,
            "osx": {
                "MIMode": "lldb"
            }
        },
```

Tasks.json snippet:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "isBuildCommand": true,
            "command": "cc",
            "isShellCommand": true,
            "args": ["-Wall", "-Wextra", "-Werror", "-g", "${fileDirname}/${fileBasename}", "-o", "${fileDirname}/${fileBasenameNoExtension}"],
            "showOutput": "always",
            "dependsOn": "clean"
        },

...

        {
            "taskName": "clean",
            "command": "saferm",
            "isShellCommand": true,
            "args": ["${fileDirname}/${fileBasenameNoExtension}", "${fileDirname}/${fileBasenameNoExtension}.dSYM"],
            "showOutput": "never"
        }
    ]
}
```

**Comment by wgj** [comment] 2017-04-09 22:45
The issue goes away upon closing the window, and I suspect it's related to processes with infinite loops that are stoped with ctrl-c/sigint.

Please let me know what I can do to troubleshoot or to find a more reliable STR.

**Comment by dbaeumer** [comment] 2017-04-10 08:22
The first error message show is IMO correct since the task really failed.

The second (and third as a follow up) is a dup of #24146 which is fixed in master and for the 1.11 recovery build.

**Comment by wgj** [comment] 2017-04-10 17:52
Thank you :)

**Comment by wgj** [comment] 2017-04-13 20:15
@dbaeumer Is the "1.11 recovery build" 1.11.2? I'm still running into this issue with 1.11.2 and wondering if it should have been resolved.

**Comment by dbaeumer** [comment] 2017-04-14 13:54
@wgj yes 1.11.2 

What do you see with that build ?

**Comment by wgj** [comment] 2017-04-14 18:59
Same issue, intermittent, and always goes away after closing and reopening the window (i.e., not exiting Code). Still don't know the root cause (e.g., previously mentioned failed builds are not likely the cause), but once the issue happens it can reliably reproduce.

1. Start Debugging
2. Observe error:
![screen shot 2017-04-14 at 11 47 41 am](https://cloud.githubusercontent.com/assets/463564/25052898/02798a64-2109-11e7-84c6-3cc40b13d230.png)
3. Task log is empty:
![screen shot 2017-04-14 at 11 55 07 am](https://cloud.githubusercontent.com/assets/463564/25052926/3b191de4-2109-11e7-9948-47ceca78622b.png)
4. Terminate running task appears to do nothing (which might be the correct behavior? Don't think I've ever used it outside of this issue)
5. Start debugging, same error.

Developer Tools console log is empty throughout the above steps.

**Comment by wgj** [comment] 2017-04-14 20:22
I can reliably reproduce this issue when running a task that segfaults. I do not believe this is a duplicate of #24146.

When running `test` with `cl` (`cl` is a helper function for `clear`) looks like this:
![screen shot 2017-04-14 at 1 07 51 pm](https://cloud.githubusercontent.com/assets/463564/25054871/5e05fda8-2114-11e7-866a-64124ccac235.png)

test:
```
        {
            "taskName": "test",
            "command": "cl",
            "args": ["${fileDirname}/${fileBasenameNoExtension}_test"],
            "isShellCommand": true,
            "showOutput": "always",
            "dependsOn": "build"
        },
```
cl:
```
scratch $ grep "function cl" ~/.bash_profile -A5
function cl {
  clear
  echo $@
  $@;
}
```
build:
```
        {
            "taskName": "build",
            "isBuildCommand": true,
            "command": "cl",
            "isShellCommand": true,
            "args": ["cc", "-Wall", "-Wextra", "-Werror", "-g", "${fileDirname}/${fileBasename}", "${fileDirname}/${fileBasenameNoExtension}_test.c", "-o", "${fileDirname}/${fileBasenameNoExtension}_test"],
            "showOutput": "always",
            "dependsOn": "clean"
        },
```

clean:
```
{
            "taskName": "clean",
            "command": "saferm",
            "isShellCommand": true,
            "args": ["${fileDirname}/${fileBasenameNoExtension}", "${fileDirname}/${fileBasenameNoExtension}_test", "${fileDirname}/${fileBasenameNoExtension}.dSYM"],
            "showOutput": "never"
        }
```

Running `test` without `cl` looks like this:
![screen shot 2017-04-14 at 1 19 22 pm](https://cloud.githubusercontent.com/assets/463564/25054962/fc72ff40-2114-11e7-9230-c4febdbb45ff.png)


test:
```
        {
            "taskName": "test",
            //"command": "cl",
            //"args": ["${fileDirname}/${fileBasenameNoExtension}_test"],
            "command": "${fileDirname}/${fileBasenameNoExtension}_test",
            "isShellCommand": true,
            "showOutput": "always",
            "dependsOn": "build"
        },
```

**Comment by dbaeumer** [comment] 2017-04-25 10:07
I am reopening the issue.

@wgj would you be able to provide me with your workspace so that I can try to reproduce this. It is hard to fix something that I can't reproduce.

**Comment by dbaeumer** [comment] 2017-04-25 10:25
I tried with a task that seg faults and I can still not reproduce this with a simple setup.

**Comment by wgj** [comment] 2017-04-26 22:11
@dbaeumer https://github.com/wgj/vscode24376

**Comment by dbaeumer** [comment] 2017-04-27 13:01
@wgj thanks for the GitHub repository. I looked into it looks like that the following is happening:

- when change launch.json or tasks.json we receive the file events in the original file (the file the link points to). 
- this result in VS Code thinking that the configuration has not changed and therefore we don't reread the config
- this is why reloading the workbench fixes the problem.

**Comment by dbaeumer** [comment] 2017-04-27 13:16
I opened https://github.com/Microsoft/vscode/issues/25547 for this since this is a more general issue in our settings story and file eventing.

@wgj any object to close the issue. In the task land there is little I can do to fix this.

**Comment by wgj** [comment] 2017-04-30 03:45
Interesting. Thanks for the explanation!

Yes, it is okay to close this issue, and I'll follow @25547 instead.

**Comment by dbaeumer** [comment] 2017-05-02 07:50
@wgj thanks. Closing the issue.

**Closed by dbaeumer** 2017-05-02 07:50 UTC
Labels: bug, needs more info, tasks
