### ISSUE TITLE
ES6 syntax support isn't working in VSCode

### ISSUE THREAD

**Issue by 0xdeafcafe** [Microsoft/vscode#2394] opened 2016-01-26 18:53 UTC
I cloned the ES6 example repo (https://github.com/jrieken/es6-vscode-sample), but when I open it, the syntax support is broken
![code_2016-01-24_15-53-22](https://cloud.githubusercontent.com/assets/2768524/12589493/fe4a7a72-c455-11e5-9f6c-3dd66efb0f56.png)

**Comment by wxqqh** [comment] 2016-01-27 08:13
I checkout the same code, but there is nothing wrong with this~~~

**Comment by dbaeumer** [comment] 2016-01-27 08:49
@jrieken can you please comment. It is 'your' GitHub repository.

**Comment by waderyan** [comment] 2016-02-23 22:51
I'm seeing this same issue in the latest Alpha build 1.9.0. 

Hovering over "import" shows "Parsing error: the import keyword is reserved (null)".
Hovering over "export" shows "export= can only be used in a .ts file."

![image](https://cloud.githubusercontent.com/assets/2449568/13269431/dfab69f0-da44-11e5-9429-761c06c780af.png)

I tried creating a `jsconfig.json` file to fix the issue. Here are the contents. 

```javascript
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    }
}
```

Didn't solve the syntax highlighting issue. 

Additionally, I would expect a syntax error that isn't shown. In my example above `<Navigation />` should be highlighted but it is not.

**Comment by egamma** [comment] 2016-02-24 20:35
The error message comes from `eslint` and the corresponding `vscode-eslint` extension. Uninstalling the extension makes the error goes away. 

@waderyan can you check your eslint configuration and whether you enabled ecmaVersion 6, see below? (I fail to install `vscode-eslint` on our latest, but this is another issue).

```json
    "parserOptions": {
        "ecmaVersion": 6
        },
    },
```

@dbaeumer has the change prefix error by the source been delivered to `vscode-eslint`.

**Comment by waderyan** [comment] 2016-02-24 21:19
@egamma I did not have the options for eslint set, however it does not fix the issue.

**Comment by egamma** [comment] 2016-02-24 21:31
@waderyan but with the eslintrc config the error for the `import` goes away? This worked for me.

The error message for the `export` looks like it is from TS/Salsa. Can you include the snippet and the jsconfig.json pls.

**Comment by waderyan** [comment] 2016-02-24 22:02
Creating .eslintrc fixed it. We also have eslint.options in preferences. I assumed they performed the same function, but they don't in this case. 

Snippet:

```
import React, {Component} from 'react';
import Navigation from '../Navigation';
import styles from './App.scss';
import Viewport from '../Viewport';

class App extends Component {
    
    render() {
        return (
            <div className={styles.app}>
                <Navigation />
                <Viewport />
            </div>
        );
    }
}

export default App;
```

jsconfig.json
```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    }
}
```

**Comment by waderyan** [comment] 2016-02-24 22:04
Here is a new issue. I'm getting unused var issues. This makes sense for React, but Navigation and Viewport are being used in the JSX syntax. 

![image](https://cloud.githubusercontent.com/assets/2449568/13302571/c5254e3e-db07-11e5-824c-b836181d999b.png)

**Comment by egamma** [comment] 2016-02-25 11:52
@waderyan 
>We also have eslint.options in preferences. I assumed they performed the same function, but they don't in this case.

Actually, the eslint options in the settings are `command line arguments` for eslint [cliengine](http://eslint.org/docs/developer-guide/nodejs-api#cliengine), these are not config options or rules. I can see the potential for confusion

**Comment by egamma** [comment] 2016-02-25 12:17
>I'm getting unused var issues. This makes sense for React, but Navigation and Viewport are being used in the JSX syntax.

These are false positives reported by eslint. I suggest to disable the rule `no-unused-vars`

**Comment by egamma** [comment] 2016-02-25 12:23
>Hovering over "export" shows "export= can only be used in a .ts file."

I could reproduce this with TS 1.8.0. I can no longer reproduce in the latest vscode-alpha that has TS 1.8.2 bundled. Can pls update code-alpha and verify that the version of TS shown in the bottom right corner when a JS file is open is 1.8.2
![image](https://cloud.githubusercontent.com/assets/172399/13319543/af2033c2-dbc2-11e5-9995-5a987c99db7f.png)

Closing and all the issues can either been explained or have been addressed.

**Closed by egamma** 2016-02-25 12:23 UTC
Labels: js

**Comment by egamma** [comment] 2016-02-25 21:03
@waderyan 
actually you can disable an eslint rule on a per line basis using:
```javascript
//eslint-disable-line //eslint-disable-line no-unused-vars
```

**Comment by waderyan** [comment] 2016-02-25 21:06
Good to know. I talked to @gregvanl today about some of this in a doc for React / ES6 developers. Wasn't easy for me to figure out.

**Comment by egamma** [comment] 2016-02-25 21:11
>Wasn't easy for me to figure out.

fully agreed, this is why I was much interested into this issue. I'll cover setting up eslint in the change notes, deferring to @gregvanl to add this to the main docs.

**Comment by waderyan** [comment] 2016-02-25 21:12
Great. I've created [an issue in vscode-docs](https://github.com/Microsoft/vscode-docs/issues/182) to track this.

**Comment by waderyan** [comment] 2016-02-27 05:02
I found another issue and want to keep it documented. Do you think this is the best place? I can create a separate issue or find another place to track these es6 issues. 

![image](https://cloud.githubusercontent.com/assets/2449568/13370881/dcaeb502-dccb-11e5-943d-4c73f9a72ba4.png)

This is from ReactStarterKit. Here is the code not in an image. 

```
import React, { Component, PropTypes } from 'react';

function withStyles(...styles) {
  return (BaseComponent) => class StyledComponent extends Component {
    static contextTypes = {
      insertCss: PropTypes.func.isRequired,
    };

    componentWillMount() {
      this.removeCss = this.context.insertCss.apply(undefined, styles);
    }

    componentWillUnmount() {
      this.removeCss();
    }

    render() {
      return <BaseComponent {...this.props} />;
    }
  };
}

export default withStyles;
```

The error message I see is 'property declarations can only be used in a .ts file'

**Comment by waderyan** [comment] 2016-02-27 05:05
Error message on hover: 'decorators' can only be used in a .ts file. 

![image](https://cloud.githubusercontent.com/assets/2449568/13370900/9857e148-dccc-11e5-954f-acc843e472f8.png)

**Comment by waderyan** [comment] 2016-02-27 05:09
Ah ... I think I got it. Decorators are an ES7 feature.

**Comment by egamma** [comment] 2016-02-27 17:37
In general, given that we transition to Salsa the TypeScript repository is the right place to file ES6 issues.

>property declarations can only be used in a .ts file

This is issue Microsoft/TypeScript#6997

>Error message on hover: 'decorators' can only be used in a .ts file.

This is Microsoft/TypeScript#6872. This should be in TS 1.8.2 according the bug report. Can you confirm that you are using TS 1.8.2 (which now the default in the code-alpha channel).

**Comment by waderyan** [comment] 2016-02-29 08:41
```
tsc -v
Version 1.9.0-dev.20160130
```

I'll file a bug.

**Comment by jerryf196** [comment] 2016-05-11 18:30
Has this been fixed? I am not sure how to fix this.

**Comment by jerryf196** [comment] 2016-05-11 18:30
I am using version 1.1.0

**Comment by andyhu** [comment] 2016-05-26 04:59
@waderyan Same issues here. Have you found a solution?

**Comment by CaRDiaK** [comment] 2016-05-31 17:59
@waderyan I've tried following this and the related conversations but I can't seem to find a way to resolve the warnings in VSCode Version 1.1.1 (1.1.1)

**Comment by reggieboyYEAH** [comment] 2016-06-22 03:10
any update on this? i am using v1.2.1

**Comment by arakno** [comment] 2016-06-22 12:30
@reggieboyYEAH , have you tried creating an .eslintrc file at the root dir of your project with 
`{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    }
}`

in it?

That solved it for me as suggested above

**Comment by thepauleh** [comment] 2016-08-24 13:52
.eslintrc.json *

**Comment by kevinbarabash** [comment] 2016-12-28 05:19
I sometimes run into this issue.  Restarting seems to fix this for a while.  I'm not sure what triggers it.  I'm running VSCode 1.8.1 and version 1.2.1 of the ESLint plugin.

**Comment by hielfx** [comment] 2017-01-23 09:37
I can't really get this to work. I am using VSCode 1.8.1 too, I tried with the ESLint plugin enabled and disabled, with the jsconfig.json file and the .eslintr but none of them are working to me

**Comment by marcusbesjes** [comment] 2017-04-20 16:27
I hit `ctrl-shift-p` and typed `eslint` then selected `create .eslintrc.json file` and it made the file with `es6: true`
![image](https://cloud.githubusercontent.com/assets/3897729/25241654/12ac2c78-25f7-11e7-82b5-7ed6f842cfb2.png)

**Comment by ImaginaryDevelopment** [comment] 2017-04-27 00:24
I don't have eslint installed, and I am getting in the Problems panel `[js] 'types' can only be used in a .ts file.`

![image](https://cloud.githubusercontent.com/assets/121276/25462642/5edc459e-2abe-11e7-8ffc-871acfaf41fc.png)

**Comment by rohmanhm** [comment] 2017-04-28 09:22
I got this problem too,
I'm using Flow, not Typescript

**Comment by JherVonArbanel** [comment] 2017-05-23 15:35
Hey guys, i have downloaded this project 
https://github.com/Microsoft/vscode-react-sample

i just tried to declare "const" in any file and is not recognized, i already checked the esLint but it doesnt works,, is not recognized .... COME ON GUYS EVERY DELIVER OF VSCODE, COMES WITH MORE AND MORE ISSUES

**Comment by david1asher** [comment] 2017-07-14 21:05
That did the trick for me: I installed ESLint so I get the valid javascript validation warnings from ESLint, and I disabled the default VSCode javascript validation so I don't get the "falsy" javascript validation warnings from VSCode.

[https://code.visualstudio.com/docs/languages/javascript](url)

> Tip You can disable default JavaScript validation by setting "javascript.validate.enable": false in your settings.

**Comment by gopaldevra** [comment] 2017-07-24 07:04
Try to add const in any method.
