### ISSUE TITLE
HTML: some part of big file is parsed wrong

### ISSUE THREAD

**Issue by Alexey-T** [microsoft/vscode#144479] opened 2022-03-05 17:32 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65
- OS Version: Ubuntu 20 x64

Steps to Reproduce:

1. open big HTML file, it is valid html page from Yahoo site. File in zip -
[https _www.yahoo.com_.zip](https://github.com/microsoft/vscode/files/8191132/https._www.yahoo.com_.zip)

2. go to lines 1242 ... 1244 and see RED parts - they must not be red.

![Screenshot from 2022-03-05 20-31-59](https://user-images.githubusercontent.com/4154978/156893881-c753f61f-7325-438e-b33e-754b571f117c.png)

**Comment by aeschli** [comment] 2022-03-07 13:59
I can reproduce the issue, but I was unable to extract it in a smaller, reproducible sample.

@alexdima Any idea why some parts are rendered in red although the `Inspect Tokens and Scopes` hover can compute a scope (although it takes a very long time to compute)

**Comment by aeschli** [comment] 2022-12-09 16:04
@aledima See question above...

**Comment by alexdima** [comment] 2022-12-19 16:14
@aeschli Here is a reduced repro:


```html
<script>window.$_mod_ybar={
</script>
<script type="text/javascript">
    console.log(`hello world`);
</script>
```

<img width="302" alt="image" src="https://user-images.githubusercontent.com/5047891/208470276-864f31b7-9129-40c7-9f4e-4838b771629e.png">

I believe this is caused by embedding a complex JS grammar inside HTML. The JS grammar inside HTML needs to be a grammar which at every step of the way checks if a `</script>` tag appears. The one we use inside HTML currently doesn't do this like in this example. There are many other JS patterns which reproduce this.

**Comment by aeschli** [comment] 2022-12-19 16:49
Thanks @alexdima. What your are mentioning is https://github.com/microsoft/vscode/issues/20488

Interestingly, the JavaScript in the example [https _www.yahoo.com_.zip](https://github.com/microsoft/vscode/files/8191132/https._www.yahoo.com_.zip) is not incomplete or missing any closing brackets.

But it is all JavaScript code one one line. So I guess we stop and then get stuck in a rue that does not contain `</script>`

Closing as dup of https://github.com/microsoft/vscode/issues/20488

**Closed by aeschli** 2022-12-19 16:49 UTC
Labels: html

**Comment by alexdima** [comment] 2022-12-19 16:56
:+1: The builtin bracket matcher thinks that some brackets are not closed:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/5047891/208478782-f54e0b2b-4672-4ad5-96b7-b36ead9fde7f.png">

It is possible that they are closed correctly on a long line which gets skipped during tokenization.
