### ISSUE TITLE
CallHierarchyOutgoingCall and CallHierarchyIncomingCall properties should have comments

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#81809] opened 2019-10-01 23:54 UTC
Testing #81655

Confusing with CallHierarchyOutgoingCall having sourceRanges and a target.

**Comment by jrieken** [comment] 2019-10-03 06:45
/duplicate of https://github.com/microsoft/vscode/issues/81746

**Comment by jrieken** [comment] 2019-10-03 06:45
Folding into https://github.com/microsoft/vscode/issues/81746 - the needs docs or and diagram explaining how things link up. The domain just happens to be complex...

**Closed** 2019-10-03 06:45 UTC
Labels: *duplicate
