### ISSUE TITLE
Unexpected suggestions on an array - it suggests the indices of contained elements

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#11197] opened 2016-08-30 12:06 UTC
- VSCode Version: 1.5.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1.  With this code:
var _ = require('lodash');

var hello = _.capitalize('hello world');

var users = [
  { 'user': 'barney', 'age': 36, 'active': false },
  { 'user': 'fred',   'age': 40, 'active': true }
];

_.reject(users, function(o) { return !o.active; });

// ➜ objects for ['fred']

// The `_.matches` iteratee shorthand.
_.reject(users, { 'age': 40, 'active': true });
// ➜ objects for ['barney']

// The `_.matchesProperty` iteratee shorthand.
_.reject(users, ['active', false]);
// ➜ objects for ['fred']

2.  Break in the debugger and type users. in the debug.console. I see suggestions labeled 0 and 1. Choosing either of these results in an invalid expression.

**Comment by stevencl** [comment] 2016-08-30 12:07
Found while testing #10997

**Comment by weinand** [comment] 2016-08-31 09:12
duplicate of https://github.com/Microsoft/vscode/issues/11191

**Closed by weinand** 2016-08-31 09:12 UTC
Labels: bug, debug
