### ISSUE TITLE
refactor.extract should respect project's semicolon policy

### ISSUE THREAD

**Issue by ris58h** [Microsoft/vscode#57154] opened 2018-08-24 14:53 UTC
I don't use semicolon as line separator in my project. I have `"semi": [2, "never"]` in rules section in my `esling.json`. `refactor.extract.constant` works but adds a redundant semicolon at the end of the extracted line (same for the other `refactor.extract` actions I believe).
I would be great if `refactor.extract` could respect eslint.json rules.

**Comment by mjbvz** [comment] 2018-08-24 14:59
Duplicate of https://github.com/Microsoft/TypeScript/issues/18780

**Closed by mjbvz** 2018-08-24 14:59 UTC
