### ISSUE TITLE
Formatting code inserts carriage returns

### ISSUE THREAD

**Issue by xucaen** [Microsoft/vscode#11959] opened 2016-09-13 13:35 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Press Shift+Alt+F several times
2. Marvel at all the new blank lines that have been entered.

**Comment by ionutvmi** [comment] 2016-09-13 13:49
Can you please provide more details and maybe some sample code.
I'm not able to reproduce this in a javascript file for example.

**Comment by xucaen** [comment] 2016-09-13 14:39
I am very sorry. It turns out the issue is being caused by an extension by Martin Kase. So, I guess VSCode doesn't format php code by default then? Is there a way to just have it follow the same rules as Javascript for .php extensions?

**Comment by bpasero** [comment] 2016-09-14 04:47
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2016-09-14 04:47 UTC
