### ISSUE TITLE
Controls Missing Menu Structure and Expanded/Collapsed State Information

### ISSUE THREAD

**Issue by Bluefish0558** [microsoft/vscode#227518] opened 2024-09-04 03:56 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: 14.6.1 (23G93)

**Description:** Controls such as "Manage" lack proper menu structure and expanded/collapsed state information, making it difficult for screen reader users to determine whether the content is expanded or collapsed.

**Steps to Reproduce:**

1. Navigate to the "Manage" control in VSCode.
2. Use a screen reader to interact with the control and observe that there is no indication of expanded or collapsed state.
User Impact: Screen reader users are unable to determine whether these controls expand or collapse content, and they cannot identify the current state of the control.

**Expected Behavior**: The control should use role="menuitem" and include aria-expanded="true" when content is expanded and aria-expanded="false" when collapsed.

**Actual Behavior:** The control is missing the necessary menu structure and state information, limiting its accessibility.

**Recommendation**: Ensure that custom controls provide proper name, role, and state information. For this case, implement role="menuitem" and aria-expanded attributes to reflect the expanded or collapsed state.
<img width="422" alt="Missing menu" src="https://github.com/user-attachments/assets/e117bf50-7103-48d3-aa5b-728ba9deee6c">

**Comment by meganrogge** [comment] 2024-09-06 23:39
This works for me, I imagine you're using JAWS? Closing as I cannot reproduce.

**Closed by meganrogge** 2024-09-06 23:39 UTC
