### ISSUE TITLE
Add event information in `onDidSaveTextDocument`

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#5305] opened 2016-04-15 06:42 UTC
- VSCode Version: 1.0.0
- OS Version: Mac OSX

It would be nice if extensions are able to distinguish the `autoSave` event from a manual `save`. We need this information in our [EditorConfig](https://github.com/editorconfig/editorconfig-vscode/issues/47) extension.

// @bpasero @jrieken

**Comment by jrieken** [comment] 2016-04-15 08:48
This is a duplicate of https://github.com/Microsoft/vscode/issues/239

**Comment by SamVerschueren** [comment] 2016-05-11 07:08
Is this actually really a duplicate of that issue? That issue is about adding new event types like `onPreSaveTextDocument`. This is more about adding extra information to the event being dispatched.

As you said before, it's quite difficult to change that without breaking the API. Currently only the `TextDocument` is being dispatched. It would be possible to attach an event type to the `TextDocument` but that's not perfect. It would make more sense if it was an event object, something like

```js
interface EventObject {
    document: TextDocument,
    action: string
}
```

Where `action` is something like `autoSave` or `save`. But that will off course break the entire API.

**Comment by jrieken** [comment] 2016-05-11 07:31
Sorry, I was wrong here... yeah, it's on*Will* and on*Did*... Will be hard to make it work in a nice way...

**Comment by NinoFloris** [comment] 2016-09-19 23:09
How is everything doing here?

**Comment by jrieken** [comment] 2016-09-23 14:57
Since we are facing API breakage with this, it might help if we expose the required data in the `onWillSaveTextDocument`-event. The *save reason* is something we try to squeeze in for Sep (https://github.com/Microsoft/vscode/issues/239#issuecomment-249189815)

**Comment by SamVerschueren** [comment] 2016-09-23 17:32
@jrieken Would this still be considered in VS Code 2.0.0 or something? It feels a little like a design flaw to pass in the TextDocument directly as event instead of an event object with the property `document` and some extra properties like the save reason? I'm ok if not, just want to make sure you guys did consider it :).

**Comment by jrieken** [comment] 2016-09-26 06:52
It clearly is a design flaw and could not come up with a back-wards compatible way to introducing such an event unless its like `SaveEvent extends TextDocument` which is a little weird. Maybe some TS/JS trickery ala `Event<TextDocument & SaveEvent>`

**Comment by SamVerschueren** [comment] 2016-09-26 07:03
If VS Code 2.x means breaking changes (major semver change), it might be possible to push this through. BUT, I understand that this is very hard to do because that means that every extension relying on this behaviour (which is probably 99% of all the extensions), will not work on VS Code 2.x.

> Maybe some TS/JS trickery ala Event<TextDocument & SaveEvent>

Yes, if that would be backwards compatible AND if somehow, we could force in the type definitions, that in the next version the object returned is an Event object with properties `document` and some extra's (which under the hood actually still is a `TextDocument` with just some extra properties). Then, one day, we might be able to get rid of the hack.

I think it might be worth exploring as this might allow to add new features more easily in the future.

**Comment by jrieken** [comment] 2017-04-11 13:52
Closing this because it would require API breakage and because the information asked for is available in the `onWillSave`-event

**Closed by jrieken** 2017-04-11 13:52 UTC
Labels: api
