### ISSUE TITLE
Not detecting Closing Tags (JSX)

### ISSUE THREAD

**Issue by ankitjt** [microsoft/vscode#90213] opened 2020-02-07 09:54 UTC
- VSCode Version: 1.42.0
- OS Version: Windows 10

Steps to Reproduce:
While working with react,I am getting "corresponding JSX tag missing", though it is mentioned.
Refer snippet-
![image](https://user-images.githubusercontent.com/48979824/74019425-9bd07d00-49bd-11ea-8438-cce094226a3d.png)

This I have encountered with the recent update of VS code.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment] 2020-02-07 19:40
Where does this error come from? Probably an extension you have installed?

To check, in the problems view, right click on the error, `copy`, and post the full error info

**Comment by mjbvz** [comment] 2020-02-15 00:59
Closing this as likely caused by an extension

**Closed by mjbvz** 2020-02-15 00:59 UTC
Labels: needs more info
