### ISSUE TITLE
New Version setting its own unremovable breakpoints

### ISSUE THREAD

**Issue by macasas** [Microsoft/vscode#38407] opened 2017-11-15 11:40 UTC
Steps to reproduce.
Open Code on macbook
Read message that tells me it updated itself. Thanks

Now I have breakpoints added all over the place in my code and Remove all breakpoints does nothing.
When I run Debug I get Error: Set breakpoints request timed out
presumably because there are so many of them.

How do I remove them, click on them, Remove All Breakpoints, does nothing.

![screen shot 2017-11-15 at 12 39 16](https://user-images.githubusercontent.com/910082/32834220-0d6da962-ca02-11e7-8f0b-f418c463344c.png)

**Comment by macasas** [comment] 2017-11-15 11:53
Closing the app and reopening did nothing to remove the breakpoints.
But I could delete them from the Breakpoint properties panel.
With no breakpoints listed the red dots remained.
So closed the file and reopened and now they have gone, and once again I can debug.

Good job I could just remove all, because the app automatically added over a hundred, so I didn't have to go through and find any I wanted to keep.

**Comment by Fire-Brand** [comment] 2017-11-15 12:05
Same here

**Comment by weinand** [comment] 2017-11-15 12:17
Duplicate of #37880. Please try Insiders.

**Closed by weinand** 2017-11-15 12:17 UTC
Labels: debug

**Comment by macasas** [comment] 2017-11-15 13:05
Just to complete the picture, these breakpoints appeared while pasting a code block copied from the same .js file. Nothing too taxing!

**Comment by weinand** [comment] 2017-11-15 13:44
Please don't spend more time discussing this stupid bug.
It is fixed in Insiders and will appear in Stable soon.
