### ISSUE TITLE
‘Report issue’ button on ‘Running extensions’ causes tens of duplicate issues

### ISSUE THREAD

**Issue by kachkaev** [Microsoft/vscode#70492] opened 2019-03-14 14:50 UTC
- VSCode Version: 1.31.1
- OS Version: macOS 10.14.3

## Steps to Reproduce

1. Open _Running extensions_
  
<img width="536" alt="Screenshot 2019-03-14 at 14 45 27" src="https://user-images.githubusercontent.com/608862/54366047-d9bb0900-4667-11e9-8f82-2f234aedb8a6.png">

2. Press _Report Issue_. You are now just one step away from creating an army of these: https://github.com/prettier/prettier-vscode/issues?utf8=✓&q=is%3Aissue+Extension+causes+high+cpu+load. 

## Expected behaviour

I'd like VSCode to search for _Extension causes high cpu load_ in the repo and show _Report issue_ button only if no open issues are found. Otherwise, I'd like it to take me to the exiting issue so that I could +1 it or add a comment. I remember Atom following this logic when there is an unhandled exception coming out of an extension.

**Comment by roblourens** [comment] 2019-03-14 18:02
I would close any of these which don't have a profile attached, but personally I find it annoying when I am investigating one issue involving high cpu, and many other people with different issues pile on just because their issue also involves high cpu.

**Comment by jrieken** [comment] 2019-03-27 16:45
Yes, this is very good feedback. I have also thought about it and I feel bad for extensions that get spammed this these issues. Totally +1 for closing issues without profiles and also +1 for making performance fixes but by now I think that we should collect perf issues and file them

**Comment by jrieken** [comment] 2019-03-28 13:48
https://github.com/Microsoft/vscode/issues/71290 and https://github.com/Microsoft/vscode/issues/71381 are both issues with extensions we ship. Ironically we don't encourage users to file issues for them... I would love to be able to simple collect those profile on our behalf but I am unsure if telemetry is fit for that

**Comment by jrieken** [comment] 2019-04-01 14:45
We should look at `total_count` of this `https://api.github.com/search/issues?q=is:issue+in:title+repo:prettier/prettier-vscode+state:open+Extension+causes+high+cpu+load`

**Comment by kachkaev** [comment] 2019-04-01 15:15
I thought one could get the same result via the GitHub's GraphQL endpoint and thus avoid massive overfetching, but unfortunately the [only works for authenticated users](https://developer.github.com/v4/guides/forming-calls/#authenticating-with-graphql) 😢

https://api.github.com/graphql?query={search(type:%20ISSUE,%20query:%20%22repo:prettier/prettier-vscode%20state:open%20in:title%20Extension+causes+high+cpu+load%22){issueCount}}

### Query

```graphql
{
  search(type: ISSUE, query: "repo:prettier/prettier-vscode state:open in:title Extension+causes+high+cpu+load") {
    issueCount
  }
}
```

### Result

```json
{
  "data": {
    "search": {
      "issueCount": 29
    }
  }
}
```

You can try this out in the [Github GraphQL API explorer](https://developer.github.com/v4/explorer/). Shame that the authentication requirement renders use of GraphQL inapplicable in this case, but it might be useful elsewhere 🤷‍♂️

**Comment by jrieken** [comment] 2019-04-02 10:47
We now show existing issues when some exist. We also show a modal message to remind folks to upload cpu-profiles

**Closed by jrieken** 2019-04-02 10:47 UTC
Labels: extensions, feature-request, under-discussion

**Comment by kachkaev** [comment] 2019-04-02 10:50
Many thanks @jrieken! Hope this reduces the number of duplicate issues created in repos like prettier-vscode :)

**Comment by kachkaev** [comment] 2019-04-15 10:55
Still [quite some](https://github.com/prettier/prettier-vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Extension+causes+high+cpu+load
) new issues in the last two weeks. At the time of writing, [six](https://github.com/prettier/prettier-vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Extension+causes+high+cpu+load+33) of them are from VSCode version 1.33.

**Comment by jrieken** [comment] 2019-04-15 11:04
This change is for 1.34 and active in 1.34-insider, not yet in stable

**Comment by DanTup** [comment] 2019-05-14 16:31
I've been getting many more of these (again without profiles, and no response when I ask for them), so good to see improvements! (I'm pretty sure they're all the same thing, the module loading due to no bundling).

FWIW - I think the message is a little misleading, since if the issue is module loading (which I suspect is most), there's no high CPU, it's just blocked sync file access which trips the 3s timer.
