### ISSUE TITLE
JavaScript syntax highlighting problem with React's source code

### ISSUE THREAD

**Issue by ltodorov** [Microsoft/vscode#6350] opened 2016-05-13 13:46 UTC
- VSCode Version: 1.1.0
- OS Version: Windows 8.1 Pro

Steps to Reproduce:

1. Download React.js v15.0.2 (https://fb.me/react-15.0.2.js).
2. Open the file in Visual Studio Code.
3. Problem with JavaScript syntax highlighting. It is fine in Sublime Text 3 or VS Studio 2015.

![image](https://cloud.githubusercontent.com/assets/1941826/15249377/e23e0c82-1927-11e6-9f5b-2c7b61cbf5bf.png)

**Comment by aeschli** [comment] 2016-05-13 18:15
The problem is with the '<' operator.

![image](https://cloud.githubusercontent.com/assets/6461412/15257611/716c60c4-1947-11e6-96b4-f351bd759fd3.png)

**Comment by aeschli** [comment] 2016-05-13 18:16
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-05-13 18:16 UTC
