### ISSUE TITLE
[FR] Allow augmenting existing themes/syntaxes with entries provided by an extension

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#26725] opened 2017-05-16 08:04 UTC
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4

My extension is for a language with lexemes that don't appear in other languages. In order to add coloring support for them I have to create a full theme and my extension users are forced to either have no coloring for these elements or have to say good bye to their beloved current theme. Instead it would be much better if I could augment the current theme (whatever it is) with additional entries from my extension's syntax definition and the colors for them. The `workbench.colorCustomizations` won't help here because it doesn't know what lexemes to color actually (in addition to the commonly used ones).

**Comment by Tyriar** [comment] 2017-05-16 18:52
The Aurelia extension actually ships a theme due to this issue. https://marketplace.visualstudio.com/items?itemName=AureliaEffect.aurelia

**Comment by aeschli** [comment] 2017-05-17 07:50
I agree that we should extend the `workbench.colorCustomizations` with the possibility to also overwrite and define tokens colors. But I don't think that solves your problem, as each user would have to add that to its settings. Also, you would want colors that match the current theme. 

So, in the end, I think there's no way around having extended themes that you can ship along with the language.
What about changing your grammar to use only the standardized scopes?

**Comment by mike-lischke** [comment] 2017-05-17 08:20
Using one of the "standardized" scopes is indeed an option (and should be prefered to avoid inventing an endless number of custom scopes), but that might not always be feasible, because it would lead to colorizations that don't really reflect the intention of the extension author (e.g. wrong color similarities or no significant coloring at all, sometimes you want a scope stand out, so you can more easily spot it etc.).

Also allowing `workbench.colorCustomizations` to overwrite token colors is not a good option, as you said. We don't want our users to manually have to change that.

I imagine a very simple implementation: instead of a full color theme an extension could deliver a map that defines default colors for scopes, which are only used if there is no definition by the theme. They key here is that an extension doesn't have to replace the full theme, but just add a few entries.

**Comment by aeschli** [comment] 2017-05-17 09:02
But what you suggest still has the problem that these default colors might not match the colors of the theme at all. Also, some themes decide to be very sparse with colors.
And there are hundreds of themes around, with new ones coming out every day. You can't cover these all.

**Comment by mike-lischke** [comment] 2017-05-17 09:41
I agree with you and have no real answer. The risk to use a non-matching color exists, no doubt. In order to minimize ugly color combinations we could have a user setting to allow or deny color adjustments by an extension. Another (or additional) option could be to derive colors from existing colors. So, my extension could say: use the color currently defined for `entity.other.rule`, increase saturation and use for `my.special.scope`. However, this can also lead to ugly colors. Still I consider this the lesser evil than replacing the entire theme.

There's this general problem with themes anyway that they should be language dependent, because very often a theme looks nice for one language but really bad for another. If you would introduce themes per language my FR would be void :-)

**Comment by Tyriar** [comment] 2017-05-18 19:51
This is heavily related to the core problem my theme generator tries to solve https://github.com/Tyriar/vscode-theme-generator/blob/331a1e8ee14f1f9f03e7e3299780fd13c0940a49/src/interfaces.ts#L18

How it works is it maps these keywords to a bunch of scopes known by the generator to be used by the language extensions. For example `functionCall` maps to:

```
entity.name.function, support.function
source.cs meta.method-call meta.method, source.cs entity.name.function
entity.other.attribute-name
```

The last one is for HTML attributes which is part of the "messiness".

**Comment by aeschli** [comment] 2017-07-18 00:43
duplicate of #27894

**Closed by aeschli** 2017-07-18 00:43 UTC
Labels: feature-request, themes
