### ISSUE TITLE
Softwrap for markdown

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#17270] opened 2016-12-15 08:32 UTC
I find it very hard to edit markdown files. There is no softwrap that makes the line continue on the next line if it's "overflowing" the current line. You have to scroll right, which is not the most UX friendly option.

**Comment by mjbvz** [comment] 2016-12-15 18:58
Closing as a duplicate of #15921

Until we implement this, you can [use custom css in the markdown preview](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css) to add a `white-space`, `word-wrap`, or `word-break` properties to get better wrapping.

**Closed by mjbvz** 2016-12-15 18:58 UTC
Labels: duplicate, markdown
