### ISSUE TITLE
Markdown preview doesn't show SVG

### ISSUE THREAD

**Issue by inliquid** [Microsoft/vscode#68368] opened 2019-02-10 17:02 UTC
- VSCode Version: 1.31
- OS Version: Windows 10

1.
![default](https://user-images.githubusercontent.com/6797881/52536656-a4708200-2d6e-11e9-974b-27a6a8c50c17.png)

2.
![default](https://user-images.githubusercontent.com/6797881/52536657-aa666300-2d6e-11e9-8497-f0d82d8abb1f.png)

**Comment by mjbvz** [comment] 2019-02-11 16:25
Duplicate of #68033

**Closed by mjbvz** 2019-02-11 16:25 UTC
Labels: markdown
