### ISSUE TITLE
Fix word-wrap for the new SCM "Sync changes" button

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#135336] opened 2021-10-18 21:36 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.1
- OS Version: Win 21H1

Steps to Reproduce:

1. Clone a git repo
2. Make a commit

View the new changes button. Depending on the localization, its label can be pretty long (German):

![image](https://user-images.githubusercontent.com/38782922/137808067-bd87ebbc-60a7-426b-9f35-a2eaad2cd274.png)

This does not really look nice, the text should be word-wrapped. Looks like some simple CSS task.

**Comment by lszomoru** [comment] 2021-11-22 20:44
@misolori, what's the guideline in such a case? Warp the text or use ellipsis?

**Comment by lszomoru** [comment] 2022-01-24 14:19
Closing as duplicate of https://github.com/microsoft/vscode/issues/136275.

**Closed by lszomoru** 2022-01-24 14:19 UTC
Labels: bug, ux, scm
