### ISSUE TITLE
Code Helper uses 180% CPU (Settings Sync extension)

### ISSUE THREAD

**Issue by anarotela18** [microsoft/vscode#161494] opened 2022-09-22 14:51 UTC
I have uninstalled the extensions that I had, leaving only these 3.

![Captura de Pantalla 2022-09-22 a la(s) 10 03 04](https://user-images.githubusercontent.com/15462407/191779609-199b22fa-75bc-4306-8269-f1dfe4527d9d.png)

I have removed the sync.

I read that they also recommended adding this in the settings.json
![Captura de Pantalla 2022-09-22 a la(s) 09 59 50](https://user-images.githubusercontent.com/15462407/191779842-daa076de-a4d5-4a14-9cac-2cb79ac43adc.png)

I have removed and reinstalled visual studio code but unfortunately nothing changed.

What else could I do to prevent it from using so much CPU % ?

![Captura de Pantalla 2022-09-22 a la(s) 10 02 10](https://user-images.githubusercontent.com/15462407/191779471-dba8d3f6-eb0f-4b77-bc8b-044a047a6c72.png)

**Comment by bpasero** [comment] 2022-09-23 04:02
Can you please find the full arguments of the process or identify it in process explorer?

**Comment by cbserra** [comment] 2022-10-07 08:38
<img width="1412" alt="Screen Shot 2022-10-07 at 1 27 31 AM" src="https://user-images.githubusercontent.com/789723/194508760-429fecf8-8b61-4356-828d-79acefe12e8a.png">

For me, it's the `extensionHost` process, which is usually always running at least 120-130% -- hope that's of some help.

I also have probably wayyy too many extensions installed and enabled -- I get lured in way too easily.

**Comment by alexdima** [comment] 2022-11-28 19:54
It is definitely the Settings Sync extension. Multiple issues complain that it runs at 100% CPU. Also look at https://github.com/shanalikhan/code-settings-sync/issues

cc @isidorn

**Comment by isidorn** [comment] 2022-12-12 10:37
Closing as duplicate of https://github.com/microsoft/vscode/issues/147707

**Closed by isidorn** 2022-12-12 10:37 UTC
Labels: upstream, freeze-slow-crash-leak
