### ISSUE TITLE
Disable more editor features for large files

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#64095] opened 2018-12-01 00:06 UTC
From https://github.com/Microsoft/TypeScript/issues/28723

**Repo**
Open a  javascript file that triggers `largeFileOptimization`. 

**Bug**
Tokenization is disabled but many other editor features are not. I think we should disable these features by default in large files as many language providers will not work well for huge files like this.

Features that I've noticed that are enabled:

- Outline
- Document symbols
- IntelliSense
- Code actions 
- Signature help
- Diagnostics? (This seems up the extension but I'm not sure how to prevent TS from computing these)

**Comment by alexandrudima** [comment] 2018-12-03 08:35
But... we already do this. The limit is 50MB. Is 10MB a better number, is 5MB a better number? It is difficult to drive this number from a single language server. This number drives the fact that a file is synced to the extension host or not. So, for files over 50MB, vim doesn't work anymore... Bringing down that number is not a real option IMHO.

IMHO this specific bug should be fixed in the TS Server. If it cannot deal with a large (generated) JS file, then it can act appropriately. TS can fall back gracefully, like e.g. using only the AST and not semantic information one can produce an outline, or intellisense can be downgraded to suggest keywords and local variables (etc.)

Furthermore, how is this not a bug that they suffer from in Sublime? Or in Visual Studio? Wouldn't the language server lock up in both of those with those files too?

**Closed** 2019-05-17 23:11 UTC
