### ISSUE TITLE
Hover should not wrap words partially

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183101] opened 2023-05-22 08:31 UTC
<img width="627" alt="image" src="https://github.com/microsoft/vscode/assets/900690/d9941e26-5815-4b63-aa17-5cbb6930b283">

I think there is CSS rules how to wrap only full words.

**Comment by StephenChips** [comment] 2023-05-22 08:42
Yeah, I'll take a look. do you know which part of code should I look into?

**Comment by Tyriar** [comment] 2023-05-22 14:16
Weird, never seen this before:

![image](https://github.com/microsoft/vscode/assets/2193314/29b1be01-e8f0-43b4-876d-202e41177c93)

(this one is wrapping because the word is larger than the line)
![image](https://github.com/microsoft/vscode/assets/2193314/a179c173-35da-42b8-9133-99726d8c6755)

**Comment by bpasero** [comment] 2023-05-22 14:32
👍 , to reproduce:
* run out of sources
* open the local test resolver (from the remote menu in the status bar)
* run the command to slowdown the connection in the target window
* wait a bit
* you should see the warning hover

**Comment by bpasero** [comment] 2023-05-22 15:04
@Tyriar oh wow, how so? I am using a markdown string here:

https://github.com/microsoft/vscode/blob/558e126e53389dd6c9b3c714478ef1cfa28046de/src/vs/workbench/contrib/remote/browser/remoteIndicator.ts#L496-L511

**Comment by Tyriar** [comment] 2023-05-22 15:05
Debugging now to see where that's happening

**Comment by Tyriar** [comment] 2023-05-22 15:07
![image](https://github.com/microsoft/vscode/assets/2193314/f2234de7-18ce-415c-bbb4-93c77dc40c92)

**Comment by Tyriar** [comment] 2023-05-22 15:08
I think you need to use `appendMarkdown` instead of `appendText`?

https://github.com/microsoft/vscode/blob/123deca535bf37148424440b502ac5160bfba323/src/vs/base/common/htmlContent.ts#L59-L66

**Comment by Tyriar** [comment] 2023-05-22 15:10
Looks like this regressed in 8ee75c19bb39c7433a042647d29d34327a3d55f6 @alexr00

**Comment by Tyriar** [comment] 2023-05-22 15:15
+ @mjbvz as it's related to markdown, `appendText` converts all spaces to nbsp which seems wrong

**Comment by bpasero** [comment] 2023-05-22 15:38
Addressing my usage in https://github.com/microsoft/vscode/pull/183126

We still use `appendText` in `remoteIndicator.ts` but that was there before. Not clear to me when to use what, JSDoc would help 🤷

**Comment by alexr00** [comment] 2023-05-23 13:59
I will defer to @mjbvz on if `appendText` is doing the right thing. But based on the discussion in https://github.com/microsoft/vscode/issues/106095 I would expect `appendText` to preserve spaces.

**Comment by alexr00** [comment] 2023-05-26 13:46
@Tyriar I think the problem with `appendText` is that if you're appending text, not markdown, then the number of spaces should be preserved.

**Comment by alexr00** [comment] 2023-05-26 14:56
Because it is text that you're appending, not markdown, it seems like the spaces should be preserved. I would expect this because text has no special rendering (i.e., spaces are not removed), whereas markdown does have special rendering for spaces.

**Comment by Tyriar** [comment] 2023-05-26 15:18
I interpret "text" here as it would be rendered in HTML, where spaces are merged together. Ben made that mistake so this will probably happen in the future if we keep it as is, I would also make it, assuming it's doing exactly what it says and just escaping the characters so you can do something like:

```ts
appendText('` <- escaped backticks <escaped brackets>`')
```

https://github.com/microsoft/vscode/blob/37ad81ccd96b6f814edce6b427ba202c8d98b42e/src/vscode-dts/vscode.d.ts#L2823-L2827

If it's important for certain use cases we could have an optional arg that also explains how it impacts on wrapping of words and double click selection. But currently, I can see bugs continually coming in where the word is wrapping incorrectly and also double click to select a word is selecting multiple words due to the nbsp.

Here are a few other places that should probably also change due to potential bad wrapping (just skimmed, not complete):

https://github.com/microsoft/vscode/blob/37ad81ccd96b6f814edce6b427ba202c8d98b42e/extensions/npm/src/features/packageJSONContribution.ts#L226

https://github.com/microsoft/vscode/blob/37ad81ccd96b6f814edce6b427ba202c8d98b42e/src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts#L190

https://github.com/microsoft/vscode/blob/37ad81ccd96b6f814edce6b427ba202c8d98b42e/src/vs/editor/contrib/inlayHints/browser/inlayHintsHover.ts#L99

https://github.com/microsoft/vscode/blob/37ad81ccd96b6f814edce6b427ba202c8d98b42e/src/vs/workbench/contrib/preferences/browser/keybindingsEditorContribution.ts#L208

**Comment by legomushroom** [comment] 2024-12-10 17:49
Was not able to reproduce today on stable 1.95.3(f1a4fb), Windows 11 so closing as fixed. Please reopen if you think that the issue still exists.

**Closed by legomushroom** 2024-12-10 17:49 UTC
Labels: bug, markdown, workbench-hover
