### ISSUE TITLE
JSDoc completion should not open automatically when setting the caret

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21172] opened 2017-02-22 17:42 UTC
Testing #21031
- Create a .js file with this contents:
  ```js
  /**
   *
   */
  ```
- Set the caret to the right of the two asterisks. 

Observe: JSDoc completion pops up.

**Comment by mjbvz** [comment] 2017-02-22 19:09
Duplicate of #21056.

**Closed by mjbvz** 2017-02-22 19:09 UTC
Labels: duplicate
