### ISSUE TITLE
Stylesheet color preview display issue

### ISSUE THREAD

**Issue by itsakt** [Microsoft/vscode#11365] opened 2016-09-01 06:39 UTC
- VSCode Version: 1.5.0-insider
- OS Version: Win 10 build 1607

Color preview used to be in line with code but now it shows up like this

![image](https://cloud.githubusercontent.com/assets/8027805/18157754/f00a9814-703c-11e6-88ed-19664a4c2eae.png)

**Comment by dbaeumer** [comment] 2016-09-01 07:03
@aeschli starting with you and setting to August since it looks like a regression.

**Comment by aeschli** [comment] 2016-09-01 07:13
duplicate of #11296

**Closed by aeschli** 2016-09-01 07:13 UTC
Labels: css-less-sass
