### ISSUE TITLE
[Extension API] window.showQuickPick with { canPickMany: true } option has the wrong return type

### ISSUE THREAD

**Issue by tetchel** [Microsoft/vscode#64014] opened 2018-11-29 18:58 UTC
- VSCode Version: 1.29.1
- OS Version: MacOS Mojave 10.14.1

Steps to Reproduce:

The return type for `showQuickPick` depends on the type of the first argument. For simplicity, in the code snippets below, I'm just using `vscode.QuickPickitem` as my type, but the behaviour is of course the same for any object implementing this interface.

Since the user can select multiple items for this QP, I want to be able to capture those items in an array. So I would expect the following to work:

![image](https://user-images.githubusercontent.com/8888438/49244932-f98f2f80-f3de-11e8-88df-267511459932.png)

However, the return type doesn't match this. The return type is always declared as `<T> | undefined`.

I change my code so that it can compile (just changed the typing of `selection`)

![image](https://user-images.githubusercontent.com/8888438/49244734-81c10500-f3de-11e8-8029-eadd2c4084cd.png)

At runtime, however, an array is in fact returned (whether I select 1 or multiple items):
![image](https://user-images.githubusercontent.com/8888438/49244537-095a4400-f3de-11e8-96dd-eb11020baaea.png)

So if I want to call Array methods on `selection`, I have to mark it as "any" type and use `as`.

In terms of potential solutions:
I'm still pretty new to TypeScript, but I would be shocked to learn that it's possible to change the return type of this function depending on the `canPickMany` option :)
It's possible the VSCode team has already discussed solutions to this such as adding a new function or overloading this one, but decided that leaving this as-is is better for simplicity. I would be OK with that, but I wanted to bring attention to this in case you all weren't aware.

**Comment by tetchel** [comment] 2018-11-29 19:16
Sorry, realizing now I probably should have raised this against https://github.com/Microsoft/vscode-extension-vscode

**Comment by chrmarti** [comment] 2018-12-03 08:08
It works when you remove the explicit declaration of the options' type. E.g.:

```ts
const selection = await vscode.window.showQuickPick(['one', 'two'], {
	canPickMany: true
});
```

Closing as duplicate of #50692.

**Closed by chrmarti** 2018-12-03 08:08 UTC

**Comment by tetchel** [comment] 2018-12-03 15:05
It doesn't work, because the inferred type of `selection` will still be the single item, not an array. But that other issue covers it, so thanks :)
