### ISSUE TITLE
Notebook leftovers

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#98657] opened 2020-05-27 14:37 UTC
Not sure if it has been fixed already, but before I forget. Last Thursday, when I prepared a demo, I ended up several times in a state in which notebooks (I'm guessing the webview) was still around while all editors where closed. I was unable to reproduce it reliably, but it happened multiple times over the course of 1h.

**Comment by rebornix** [comment] 2020-06-02 22:47
/duplicate of #98260 and let's track it there.

**Closed by rebornix** 2020-06-02 22:47 UTC
Labels: bug, notebook
