### ISSUE TITLE
Freezing and slow since the last update

### ISSUE THREAD

**Issue by jerome281** [Microsoft/vscode#36073] opened 2017-10-11 15:19 UTC
Since the last update, the editor is really slow and keep freezing

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
jshint|dba|0.10.15
tslint|eg2|1.0.11
auto-close-tag|for|0.5.1
beautify|Hoo|1.1.1
Angular2|joh|2.7.0
color-highlight|nau|2.3.0
vscode-icons|rob|7.15.0
sass-indented|rob|1.4.2
code-settings-sync|Sha|2.8.3
autoimport|ste|1.2.2
cordova-tools|vsm|1.2.12
html-css-class-completion|Zig|1.10.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-12 09:32
I see that you have this extension installed html-css-class-completion. This looks like a duplicate of #35996. Can you confirm and try to reproduce this the CSS Intellisense extension disabled?

**Comment by queueseven** [comment] 2017-10-12 09:34
I have the same problem. Since the last update (1.17.1), VS Code is nearly unusable when coding in Typescript. 

I downgraded to 1.16.1 and it works again. I'll run some more tests to see if it's a specific plugin or not.

**Comment by egamma** [comment] 2017-10-12 09:35
@queueseven please see https://github.com/Microsoft/vscode/issues/36073#issuecomment-336074616

**Comment by egamma** [comment] 2017-10-13 07:41
@jerome281 the extensioin html-css-class-completion got updated with a performance fix in version 1.10.2, can you please verify that this addresses your problem.

**Comment by egamma** [comment] 2017-10-16 06:52
Closing as a duplicate of #36073

**Closed by egamma** 2017-10-16 06:52 UTC
Labels: caused-by-extension
