### ISSUE TITLE
Bad coloring in .scss files

### ISSUE THREAD

**Issue by Miralo** [Microsoft/vscode#38859] opened 2017-11-21 10:03 UTC
In the nested rules (for example inside an existing class that is colored in "orange") the code coloring seems to be broken, and the nested css classes appears in white color.

Sorry for my bad english,
Michele

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
semantic-ui-snippets|4tr|0.0.7
html-snippets|abu|0.1.0
vscode-twig-pack|baj|1.0.0
vue-snippets|hol|0.1.5
vetur|oct|0.11.3
vscode-icons|rob|7.18.1
twig|wha|1.0.2

---

Steps to Reproduce:

1. Open a .scss file
2. Write a nested rule inside a .example css class

Reproduces without extensions: Yes/No

**Comment by coisnepe** [comment] 2017-11-21 11:06
Same issue here:
![image](https://user-images.githubusercontent.com/13304454/33069291-5e8c1188-ceb4-11e7-8add-c671528f487b.png)
Happens with and without any css/scss related extensions

**Comment by aeschli** [comment] 2017-11-23 08:37
duplicate of #38001, fixed in 1.19

**Closed by aeschli** 2017-11-23 08:37 UTC
Labels: new release
