### ISSUE TITLE
Question: Any plans to add CodeLens to JavaScript/TypeScript?

### ISSUE THREAD

**Issue by Kurtz1993** [Microsoft/vscode#4831] opened 2016-03-31 15:01 UTC
Hi!

I was wondering if there are any plans to add this awesome feature to JavaScript/TypeScript language in future releases. That'll be awesome!

**Comment by egamma** [comment] 2016-03-31 17:41
@Kurtz1993 we like the feature too, it is on the backlog.

**Comment by waderyan** [comment] 2016-11-21 19:50
Duplicate of https://github.com/Microsoft/vscode/issues/10717

**Closed by waderyan** 2016-11-21 19:50 UTC
Labels: feature-request, typescript
