### ISSUE TITLE
Remote SSH  always disconnect and show ERROR 403: Forbidden.

### ISSUE THREAD

**Issue by fjh352** [microsoft/vscode#76844] opened 2019-07-08 08:16 UTC
Remote SSH  always disconnect, sometime i can login, but something i can't connect to server.
output like delow:
```
> Checking server status with wget
> 
> http://127.0.0.1:39670/delay-shutdown: 2019-07-08 04:32:08 ERROR 403: Forbidden.
> 
```
![image](https://user-images.githubusercontent.com/20621275/60794220-de1dab80-a19b-11e9-918c-aa4399f3fd6e.png)

**Comment by koba-z33** [comment] 2019-07-09 05:58
I had same probrem.

In my environment, I solved it.

I wrote the following environment variables in .bashrc.

```
export no_proxy="127.0.0.1,localhost"
```

When I had same problem, I wrote only http_proxy/https_proxy environment variables.

**Comment by koba-z33** [comment] 2019-07-09 06:34
I found Similar problem.

https://github.com/microsoft/vscode-remote-release/issues/895

**Comment by roblourens** [comment] 2019-07-10 17:32
Yes a duplicate of that issue, thanks

**Closed** 2019-07-10 17:32 UTC
Labels: *duplicate
