### ISSUE TITLE
Custom menu bar: clicking a menu has no effect with menuBarVisibility = toggle

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#52788] opened 2018-06-25 10:13 UTC
With the following settings:
```json
    "window.titleBarStyle": "custom",
    "window.menuBarVisibility": "toggle"
```
1. Maximize the window
1. Move the cursor so that it is located inside the title bar
2. Press the ´Alt´ key
3. Click a menu item -> the menu doesn´t pull up.

**Comment by sbatten** [comment] 2018-06-25 23:46
dupe of #52522

**Closed by sbatten** 2018-06-25 23:46 UTC
Labels: bug, workbench-menu
