### ISSUE TITLE
Program freezes after clicking 'Add workspace folder...' on welcome screen

### ISSUE THREAD

**Issue by DavidSampson** [microsoft/vscode#66342] opened 2019-01-10 14:13 UTC
In the version of Code - Insiders that I am running, I have found that if I click 'Add workspace folder...' on the welcome screen, the program freezes entirely.  Occasionally it will pop up with an 'extension host terminated unexpectedly' message after awhile.  In either case, none of the UI is functional, and even the built in task manager is completely unresponsive (though I noted that the information on it was still changing).  Having the dev tools open to the console shows nothing, it freezes as well.  And this is all while running --disable-extensions as well.

CPUs | Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledsurface_synchronization: enabled_onvideo_decode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 15.86GB (10.25GB free)
Process Argv | --disable-extensions
Screen Reader | no
VM | 0%

Extensions are disabled

Version: 1.31.0-insider (user setup)
Commit: 344f4fa361e098b49aeace9602e89275fbbd17bf
Date: 2019-01-10T06:21:21.472Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment] 2019-01-11 09:45
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by DavidSampson** [comment] 2019-01-11 14:08
Downloaded the exploration build and I can confirm that the bug DOES NOT appear in it. 'Add workspace folder...' works as expected.

```
Version: 1.31.0-exploration (user setup)
Commit: 37818ac3597b4afda264b05226b0b77fb8e85f41
Date: 2018-12-13T07:43:53.389Z
Electron: 4.0.0-beta.9
Chrome: 69.0.3497.106
Node.js: 10.11.0
V8: 6.9.427.24-electron.0
OS: Windows_NT x64 10.0.17134
```

I also downloaded the stable version and can confirm that it does not appear there either, 'Add workspace folder...' works fine.

```
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
````

Are there any log files you need?

**Comment by DavidSampson** [comment] 2019-01-11 14:13
I received an update to Insiders and can confirm that the bug DOES still appear in it, though it seems to have the same versions of all of the libraries so that's not surprising.

```Version: 1.31.0-insider (user setup)
Commit: ccdd2997a66965c7104fe180207d9a710ea50fa5
Date: 2019-01-11T06:19:08.621Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134```

**Comment by bpasero** [comment] 2019-01-11 14:35
@DavidSampson it might be unrelated to Electron 4 actually, can you run from the command line "`code --user-data-dir <some empty folder>`" to start with fresh data and see if it still reproduces?

**Comment by DavidSampson** [comment] 2019-01-11 14:39
Cannot reproduce, it seems to work with an empty user data directory.

**Comment by bpasero** [comment] 2019-01-11 14:47
@DavidSampson then I can only assume that something goes wrong when we try to restore the last opened folder in that dialog (we store that as UI state). Is that a network folder maybe?

**Comment by DavidSampson** [comment] 2019-01-11 14:52
![vscodebug](https://user-images.githubusercontent.com/11844890/51040829-1b530900-157e-11e9-9c08-396a5f855178.PNG)

This is the window I get when I open Code.  No folders open, just the welcome tab.

**Comment by bpasero** [comment] 2019-01-11 14:53
@DavidSampson yeah but can you do that action this issue is about to see if it reproduces?

**Comment by DavidSampson** [comment] 2019-01-11 14:53
Yes if I click 'Add workspace folder...' from that screen, I get a freeze.

**Comment by bpasero** [comment] 2019-01-11 15:14
@DavidSampson wow ok, so it indeed looks like something in Electron 3 is triggering it. Not sure what that is though. Do other dialogs work, like "File > Open Folder"?

**Comment by DavidSampson** [comment] 2019-01-11 15:21
So it seems like on the welcome screen page:
* New File - WORKS
* Open Folder - DOES NOT WORK
* Add Workspace Folder - DOES NOT WORK
* Recent -> More... - WORKS
* Everything else - WORKS

Which makes me think it has to do with opening the Windows file dialog, since 'Recent -> More...' opens the internal Code file dialog and that works fine.

Interestingly, 
* File -> Open File
* File -> Open Folder
* File -> Open Workspace
* File -> Add Folder to Workspace

 **all work at least *some* of the time**, though I could swear I've had freezes on those actions before.

It's just on the Welcome tab that file/folder dialog actions fail 100% of the time.

**Comment by DavidSampson** [comment] 2019-01-11 15:23
Alright so I closed the 'Welcome' tab and reopened it, and now everything seems to work on the Welcome tab.  Is the Welcome tab regenerated fresh on every start or is it a state that is saved and loaded from that save each time?  It seems like that one instance of the Welcome tab got corrupted, and forcibly closing it and reopening it regenerated a fresh state.

**Comment by bpasero** [comment] 2019-01-11 16:34
@DavidSampson no that should really not make any difference (maybe @chrmarti can chime in). Can you not reproduce now anymore at all?

**Comment by chrmarti** [comment] 2019-01-11 16:57
These actions on the Welcome page are always the same, reopening does not affect how the Welcome page triggers the underlying commands.

**Comment by DavidSampson** [comment] 2019-01-11 17:06
@bpasero @chrmarti 

Alright so I can reproduce now.  

Workflow 1: 
1. With VS Code configured to always open on the 'Welcome' page
2. Open VS Code
3. Attempt to click 'Open folder' or 'Add workspace folder' on the 'Welcome' page
FREEZES

Workflow 2:
1. Open VS Code
2. Close 'Welcome' page if it is open.
3. Help -> Welcome
4. Click on 'Open folder' or 'Add workspace folder' on Welcome page
WORKS FINE

**Comment by bpasero** [comment] 2019-01-14 11:43
Ok thanks, I am out of ideas and think this is an issue with the Windows file dialog, not VSCode.

**Comment by bpasero** [comment] 2019-10-09 08:21
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Closed by bpasero** 2019-10-09 08:21 UTC
Labels: electron, electron-3.0.x-update, freeze-slow-crash, upstream, windows
