### ISSUE TITLE
Disable useless suggestions in Javascript and Typescript files

### ISSUE THREAD

**Issue by madiodio** [microsoft/vscode#80016] opened 2019-08-28 21:38 UTC
Hi there, is there any way/chance we could disable/control these useless suggestions showing in javascript and typescript files?

<img width="860" alt="Screen Shot 2019-08-28 at 21 07 31" src="https://user-images.githubusercontent.com/15022248/63893057-b4814380-c9d8-11e9-9783-b13baec46b22.png">

I know this is not the first time this issue is being reported (See #10565, #54971, #22372, #15750, #27899, #37982, #26624, #26340, #45039 and I could go on). There are a couple of offered solutions that don't solve the problem or are not satisfactory enough to control the quality of the suggestions. So to this date, is there anything we could do to not show at all these suggestions ?

This really my biggest frustration about VSCode now.

**Comment by mjbvz** [comment] 2019-08-28 23:14
Duplicate of https://github.com/microsoft/TypeScript/issues/29921

**Closed by mjbvz** 2019-08-28 23:14 UTC
