### ISSUE TITLE
"code --install-extension" sometimes prompt the user, making it unsuitable for batch use

### ISSUE THREAD

**Issue by smarter** [Microsoft/vscode#58965] opened 2018-09-19 15:45 UTC
When running:
```shell
% code --install-extension a.b
```

If `a.b` has already been installed and a newer version exists, a prompt appears:
```shell
a.b ... is already installed, but a newer version 4.8.2 is available in the marketplace. Would you like to update? Yes(Y) | No(N)
```

It'd be nice if there was a command option like `--yes` that answered yes to all questions. There's already `--force` but it doesn't fit exactly: if the extension has already been installed and no newer version exists, it will redownload the extension from the marketplace anyway.

**Comment by smarter** [comment] 2018-09-19 15:46
Relevant code: https://github.com/Microsoft/vscode/blob/1dd732608fa588652d4f01aa16e54e8695b0320a/src/vs/code/node/cliProcessMain.ts#L141-L157

**Comment by sandy081** [comment] 2018-09-21 15:28
Duplicate of #58434

**Closed by sandy081** 2018-09-21 15:28 UTC
Labels: *duplicate, extensions

**Comment by smarter** [comment] 2018-09-21 15:47
@sandy081 As I mentioned in the description of this issue, --force is not good enough because it will reinstall an already installed extension. Would you be open to changing --force to not do that, or add a --yes that simply responds yes to every question?

**Comment by sandy081** [comment] 2018-09-24 07:37
@smarter Good point, Updated to not to reinstall when --force is used
