### ISSUE TITLE
TypeScript JSDoc auto complete snippet doesn't work in current version of VS Code

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#82776] opened 2019-10-17 14:46 UTC
### VSCode/OS Version:
```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Datum: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.17763
```
Steps to Reproduce:

1. Open a TypeScript project
1. Set `"javascript.suggest.completeJSDocs": true`
   and `"typescript.suggest.completeJSDocs": true`
1. Open a TypeScript file and create a function.
1. Position cursor above function definition and hit `/**`

### Expected result:
A JSDoc auto complete snippet should appear and fill in the appropriate fields.

### Actual result:
Nothing happens.

![TypeScript JSDoc Auto completion](https://user-images.githubusercontent.com/9283914/67019822-8927f480-f0fd-11e9-8a82-738304b8497b.gif)

**Comment by HaveSpacesuit** [comment] 2019-10-17 14:57
Can confirm. This used to work since [this release](https://code.visualstudio.com/updates/v1_10#_auto-jsdoc-comments), but it stopped working maybe sometime around the August release.

**Comment by mjbvz** [comment] 2019-10-17 17:39
Works fine for me in latest insiders. Does manually triggering suggestions with ctrl+space work? Did you perhaps disable snippet completions?

**Comment by SetTrend** [comment] 2019-10-17 19:34
Snippet suggestions are enabled on my machine:

![image](https://user-images.githubusercontent.com/9283914/67041177-5db90000-f125-11e9-8508-c190ace2c38e.png)

Hitting <kbd>CTRL</kbd>+<kbd>SPACE</kbd> doesn't yield the desired result:

![image](https://user-images.githubusercontent.com/9283914/67041371-cef8b300-f125-11e9-9721-52ad24ad5578.png)

**Comment by mjbvz** [comment] 2019-10-17 20:07
Please share some example code where you don't see the suggestions

**Comment by SetTrend** [comment] 2019-10-18 10:13
@mjbvz: This issues isn't code agnostic. You may type anything you like, e.g.

```typescript
export default class C
{
	public F(a: string, b: number): void
	{ }
}
```

**Comment by mjbvz** [comment] 2019-10-18 23:00
![Screen Shot 2019-10-18 at 3 57 32 PM](https://user-images.githubusercontent.com/12821956/67133135-64488580-f1c0-11e9-9216-5c172c58e8bc.png)

Have you configured `editor.autoClosingBracket`?  If so, this is a duplicate of #82814

**Comment by SetTrend** [comment] 2019-10-22 10:31
Confirmed. Yes, my settings show `"editor.autoClosingBrackets": "never"`.

@mjbvz : Would you suggest I add my issue to /microsoft/TypeScript/issues/24468 or to create a new issue as it's already closed for discussion.

**Comment by mjbvz** [comment] 2019-10-22 18:39
Thanks for confirming. Closing this issue as duplicate of #82814

Yes please open a new issue against TS upstream so that it gets attention (but include a link to the previously reported TS issue)

**Closed by mjbvz** 2019-10-22 18:39 UTC
Labels: javascript, needs more info, suggest

**Comment by SetTrend** [comment] 2019-10-30 13:47
@mjbvz : FYI: I created the TypeScript issue now.
