### ISSUE TITLE
Content in Notebook Cells Intermittenly Fails to Display

### ISSUE THREAD

**Issue by dtoliver** [microsoft/vscode#173951] opened 2023-02-09 14:55 UTC
Type: <b>Bug</b>

I've experienced issues where the cell contents don't display. I'll collapse and expand the container to see if that helps, but it rarely works (if that's even what actually fixed it).

Only things that stand out are (1) I have around 20+ cells with fair amount of Python code, and (2) Chrome is open with a few dozen tabs. (Lots of research and exploration going on.)

Thanks for looking into this.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
yaml2json|ahe|0.0.4
Bookmarks|ale|13.3.1
jsoncrack-vscode|Ayk|1.0.8
markdown-mermaid|bie|1.17.4
mermaid-markdown-syntax-highlighting|bpr|1.5.0
vscode-markdownlint|Dav|0.49.0
mustache|daw|1.1.1
parquet-viewer|dvi|2.2.2
gitlens|eam|13.2.0
json-tools|eri|1.0.2
vscode-pull-request-github|Git|0.58.0
todo-tree|Gru|0.0.223
vscode-drawio|hed|1.6.6
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.7.2
vsc-python-indent|Kev|1.18.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
autodocstring|njp|0.6.1
vscode-drawio-plugin-mermaid|nop|0.1.5
vscode-thunder-client|ran|2.4.1
scala|sca|0.5.6
markdown-preview-enhanced|shd|0.6.7
pdf|tom|1.2.2
vscode-mermaid-editor|tom|0.17.1
vscode-json-stable-stringify|Tra|1.2.1
vscode-icons|vsc|12.2.0

(14 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2023-02-09 17:32
Thanks for reporting. /duplicate of https://github.com/microsoft/vscode/issues/173590, it's fixed in latest Insiders and will be fixed in the Recovery build that will be released today.

**Closed by rebornix** 2023-02-09 17:32 UTC

**Comment by dtoliver** [comment] 2023-02-09 17:52
Thanks @rebornix!
