### ISSUE TITLE
Go to definition not working for JavaScript

### ISSUE THREAD

**Issue by jkrems** [Microsoft/vscode#70992] opened 2019-03-23 00:13 UTC
Issue Type: <b>Bug</b>

1. Use a library like `send` that has known type definitions.
2. Try to jump to its implementation.
3. Get stuck in the type definition file with no way to get to the actual code.

I tried "go to to implementation" but it seems to have the same behavior, it only shows the type definition file.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.0
vscode-eslint|dba|1.8.2
json-tools|eri|1.0.2
graphql-for-vscode|kum|1.13.0
vscode-kubernetes-tools|ms-|0.1.18
python|ms-|2019.2.5558
Go|ms-|0.9.2
vscode-docker|Pet|0.6.1
java|red|0.41.0
vscode-yaml|red|0.3.0
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2

</details>

**Comment by mjbvz** [comment] 2019-03-28 03:02
Duplicate of #68782

**Closed by mjbvz** 2019-03-28 03:02 UTC
Labels: javascript

**Comment by jkrems** [comment] 2019-03-28 03:23
@mjbvz I assume closing this as a duplicate of that (closed) issue means "working as expected"? The only solution is to prevent the type definitions from being loaded? :(

**Comment by jsumners** [comment] 2019-04-03 18:26
@jkrems they just don't care. i wish there was another editor that did everything the same _except_ for this. I would switch.
