### ISSUE TITLE
supportsFunctionBreakpoints: false is ignored

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#3830] opened 2016-03-08 10:33 UTC
See https://github.com/felixfbecker/vscode-php-debug/issues/21
I am not currently sending `supportsFunctionBreakpoints: true`, but users are still able to set function breakpoints, resulting in errors.

I just worked on implementing `setFunctionBreakpoints` and it works without having to send the flag in `InitializeResponse`.

**Comment by weinand** [comment] 2016-03-08 14:32
duplicate of #3848

**Closed by weinand** 2016-03-08 14:33 UTC
Labels: bug, debug
