### ISSUE TITLE
`Unknown file extension ".ts"` error debugging typescript app in Node app when upgrading from 1.46.1 to 1.47.2

### ISSUE THREAD

**Issue by nynj** [microsoft/vscode#102873] opened 2020-07-18 18:07 UTC
- VSCode Version: 1.47.2
- OS Version: Windows 10

Steps to Reproduce:

1. In 1.46.1 click F5 in folder with Node app using Typescript
2. App runs in debug mode fine
3. Upgrade to 1.47.2
4. click F5 in folder with Node app using Typescript
5. Error occurs (see below)

This happens with multiple projects.

Does this issue occur when all extensions are disabled?: Yes

Error message:
```
"C:\Program Files\nodejs\node.exe" "c:\........\app.ts"
Debugger listening on ws://127.0.0.1:60898/8098207d-8ea6-4dc0-9893-7cedba10fb1f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for c:\........\app.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
Process exited with code 1
```

launch.json:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
  {
    "type": "node",
    "sourceMaps":true,
    "request": "launch",
    "name": "Launch Program",
    "skipFiles": [
        "<node_internals>/**"
    ],
    "program": "${workspaceFolder}/src/app.ts",
    "outFiles": [
        "${workspaceFolder}/out/**/*.js"
    ],
    "env": {
    }            
  }
  ]
}
```

**Comment by connor4312** [comment] 2020-07-19 02:51
```
    "program": "${workspaceFolder}/src/app.ts",
```

You should be able to get around this by pointing at your compiled rather than source files. We make some effort to run the compiled files instead if we can find them easily, but this may not be working with your setup.

**Comment by weinand** [comment] 2020-08-07 16:20
@connor4312 in node-debug we were accepting an *.ts entry point as long as we could find a generated *.js file in "outFiles" that would map back to it via a source map. Is using js-debug the same approach?

**Comment by connor4312** [comment] 2020-08-07 16:39
It is, and we have some tests for it, but it looks like there's something that might not work at parity with node-debug's treatment.

Since I know it works in some cases and this is an uncommon case with an easy workaround, I didn't triage it for July, but will tackle it during debt week or the upcoming iteration.

**Comment by connor4312** [comment] 2020-08-10 23:00
@andreafdaf / @nynj I'm having some trouble getting this to happen with my TS projects locally.

Are you able to share an application or small example where this reproduces?

Alternatively, can you describe a little more about your build setup to help me simulate it -- are you just running tsc or using something like webpack or babel to build?

/needsMoreInfo

**Comment by jbialobr** [comment] 2020-08-15 07:19
@connor4312 Here is a minimum repro project:
[repro-102873.zip](https://github.com/microsoft/vscode/files/5078302/repro-102873.zip)

**Comment by connor4312** [comment] 2020-08-17 16:48
awesome, thank you! I will take care of this today

**Comment by connor4312** [comment] 2020-08-17 17:05
Thank @jbialobr. For you it looks like `outFiles` is set to `${workspaceRoot}/dist/src/main/js/index.js`, however the actual generated file is `${workspaceRoot}/dist/index.js` -- therefore we don't look at it and don't have any way to map back to the source. Setting your outFiles to `"${workspaceRoot}/dist/**/*.js"` should fix the issue.

Interestingly it looks like specifying a single file in the outFiles patterns doesn't work (e.g. `"${workspaceRoot}/dist/index.js"`. Definitely an edge case but I'll look at that.

**Comment by connor4312** [comment] 2020-08-17 17:13
Closing as the original reporters have not provided additional information in our 7 day window. @andreafdaf / @nynj please let me know if you're able to provide info and I can reopen this.

**Closed by connor4312** 2020-08-17 17:13 UTC
Labels: bug, debug, needs more info

**Comment by EvanCahill** [comment] 2020-08-24 23:19
We are seeing similar errors in our project after switching to 1.48. In our case it looks like the issue is with the outfiles being in a directory outside of the workspaceFolder. Moving the typescript output directory to be under the workspaceFolder fixed the issue.
