### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by danielcastilho** [Microsoft/vscode#32897] opened 2017-08-21 17:13 UTC
- VSCode Version: Code - Insiders 1.16.0-insider (0626479859787fa87c7c57ba19195b939050a843, 2017-08-21T07:17:17.874Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
ng-template|Ang|0.1.4
vscode-node-readme|ben|1.1.0
git-easy|bib|1.9.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
vscode-material2-snippets|dee|2.0.0
githistory|don|0.2.3
gitlens|eam|4.4.0
vscode-html-css|ecm|0.1.8
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-great-icons|emm|2.1.14
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
code-runner|for|0.7.0
beautify|Hoo|1.1.1
rest-client|hum|0.15.1
Angular2|joh|2.4.0
vscode-icon-theme|jtl|1.5.0
vscode-jade-snippets|mrm|1.0.1
vscode-scss|mrm|0.6.2
mssql|ms-|1.1.0
csharp|ms-|1.12.1
vs-keybindings|ms-|0.1.7
team|ms-|1.122.0
debugger-for-chrome|msj|3.1.8
vscode-docker|Pet|0.0.16
material-icon-theme|PKi|2.1.0
angular-cli|pko|1.0.1
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
todotasks|san|0.5.0
code-settings-sync|Sha|2.8.3
stylelint|shi|0.28.0
vscode-autohotkey|sle|0.2.1
nativescript|Tel|0.7.2
Angular2|UVB|0.4.1
cordova-tools|vsm|1.2.10
vscode-todo-highlight|way|0.5.8
html2jade|wma|0.2.0
nativescript-ng2-snippets|www|2.0.1
maple|yjt|1.1.6

(33 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment] 2017-08-23 18:14
Duplicate of https://github.com/Microsoft/vscode/issues/32530

**Closed by Tyriar** 2017-08-23 18:14 UTC
Labels: insiders
