### ISSUE TITLE
Unable to un-sync deprecated extensions

### ISSUE THREAD

**Issue by poa00** [microsoft/vscode#209735] opened 2024-04-06 23:27 UTC
### Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.88.0
- OS Version: 11 Enterprise

### Steps to Reproduce:

1. Find a `[DEPRECATED]` extension in the list of extensions that was previously installed and synced.
2. Right click on the extension.
3. Select (the already checked) "`✓ Sync This Extension`" option from the Context Menu that appears.

#### Expected Behavior:
The selected option is unchecked.

#### Actual Behavior:
![image](https://github.com/microsoft/vscode/assets/134162878/403fc64b-bfc5-4c79-a047-b0532a4c9fd8)

**Comment by sandy081** [comment] 2024-04-09 11:14
It seems to work for me. Does it happen only for deprecated or also for other normal extensions? Do you see any errors in the logs? 

- F1 > Open View... > Window
- F1 > Open View... > Shared

Can you please open your settings file `F1 > Open User Settings (JSON)` and check if `settingsSync.ignoredExtensions` setting is getting updated when you toggle the above action?

**Comment by poa00** [comment] 2024-04-14 15:29
It does show them as ignored.  It just doesn't uncheck them in the context menu.

**Comment by sandy081** [comment] 2024-04-18 16:37
> It does show them as ignored

Where do you see this?

**Comment by sandy081** [comment] 2024-04-18 16:37
Can you please share a gif/video of what you are seeing with the settings.json opened/

**Comment by poa00** [comment] 2024-04-19 18:39
Sorry I take that back, I misread your original message. It does NOT update my settings.json file when I toggle any deprecated extensions.  I'm currently working so I don't have time to sanitize the file, but I will when I get home this evening and share a screengrab.

**Comment by sandy081** [comment] 2024-04-25 10:26
Since I have not received the necessary information to reproduce the issue I am closing it. Please reopen it with information requested. Thanks.

**Closed by sandy081** 2024-04-25 10:26 UTC
Labels: info-needed
