### ISSUE TITLE
Icon `Synchronize changes` doesn't spin 

### ISSUE THREAD

**Issue by anhnc54** [Microsoft/vscode#24216] opened 2017-04-07 11:51 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|smarty|imperez|0.2.0|
|ejs-language-support|QassimFarid|0.0.1|;

---

Steps to Reproduce:

1. Icon `Synchronize changes` doesn't spin ( I don't know when it complete )

**Comment by jsynowiec** [comment] 2017-04-07 12:56
Duplicate of #23975. Not a bug, it's by design.

**Closed** 2017-04-07 15:06 UTC
Labels: duplicate
