### ISSUE TITLE
Search not respecting `search.exclude`

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#94702] opened 2020-04-08 17:43 UTC
When I use global search it's not respecting my workspace `settings.exclude`. I have a notes folder in my workspace with a bunch of txt files. In my workspace I have `"search.exclude": { "**/*.txt": true }`. However, when I have an editor open with one of those text files it shows up in search results. It looks like search now considers all open editors but doesn't apply my explicit settings when doing so.

I think this behavior changed at some point, because I don't recall this being an issue before.

**Comment by gjsjohnmurray** [comment] 2020-04-08 18:23
/duplicate of #31819 so apparently it's behaved this way for a long time.

**Closed** 2020-04-08 18:24 UTC
Labels: *duplicate

**Comment by maxathanja** [comment] 2020-04-09 11:11
I'm experiencing exactly the same issue. It happened after the latest VS Code for Mac update `1.44.0`. Working fine in the previous version.

<img width="1280" alt="vscode_1 44 0" src="https://user-images.githubusercontent.com/25719815/78889225-efb61b80-7a6b-11ea-96c1-25be8a5ab43b.png">
