### ISSUE TITLE
Code Reference Text Foreground & Background are in the same color (not readable)

### ISSUE THREAD

**Issue by NERO-113** [microsoft/vscode#214939] opened 2024-06-12 11:18 UTC
Type: <b>Bug</b>

press Ctrl+K Ctrl+T > Select Dark High Contrast 
Issue example at: press Ctrl+, > search > files.associations

What you normally see:
Files: Associations
Configure glob patterns of file associations to languages (for example `"*.extension":` "html"`). Patterns will match on the absolute path of a file if they contain a path separator and will match on the name of the file otherwise. These have precedence over the default associations of the languages installed.

What I see:
Files: Associations
Configure glob patterns of file associations to languages (for example▐██████████). Patterns will match on the absolute path of a file if they contain a path separator and will match on the name of the file otherwise. These have precedence over the default associations of the languages installed.
![image](https://github.com/microsoft/vscode/assets/112952933/5dc5d0ce-9aab-4ed0-b7ce-3ab0ee74e381)

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (17.45GB free)|
|Process Argv|--crash-reporter-id 95163a2c-de9d-46c4-9ec3-ca5e549ffcbb --crash-reporter-id 95163a2c-de9d-46c4-9ec3-ca5e549ffcbb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
csvtojson-converter|Chu|1.0.2
intelli-php-vscode|DEV|0.12.15062
copilot|Git|1.200.0
copilot-chat|Git|0.16.1
gc-excelviewer|Gra|4.2.59
rainbow-csv|mec|3.12.0
test-my-code|moo|3.0.3
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
debugpy|ms-|2024.7.11591013
isort|ms-|2023.10.1
python|ms-|2024.9.11641010
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.2.2
platformio-ide|pla|3.3.3
sqlite-viewer|qwt|0.5.8
iconfont-preview|stx|0.0.5
md-contents|the|1.2.3
cmake|twx|0.0.17
vscode-mdx|uni|1.8.8
php-debug|xde|1.34.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by rzhao271** [comment] 2024-06-17 18:18
Probable duplicate of https://github.com/microsoft/vscode/issues/214412

The issue should be fixed in 1.90.1.

**Closed by rzhao271** 2024-06-17 18:18 UTC
Labels: bug, settings-editor
