### ISSUE TITLE
Regex not supporting balance groups or subroutines

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/vscode#136983] opened 2021-11-11 19:04 UTC
Issue Type: <b>Bug</b>

1. Edit a file or open a new file.
2. Go to find (Ctrl+F).
3. Select regex in search (Alt+R).
4. Type in either of the following: 
```
  (?<A>abc)(?<-A>)  # balance group: invalid capture group name
  (abc)(?0)         # numbered subroutine call: invalid group
  (abc)(?R)         # resume match from begining: invalid group
  (?<A>abc)\g<A>    # named subroutine call: invalid escape
  (?<A>abc)(?&A)    # named subroutine call: invalid group
```
I've marked it as a bug because most newer regex engines have a subroutine or balanced group syntax.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.38GB (1.64GB free)|
|Process Argv|--crash-reporter-id ff847a9c-5b94-44a0-b759-b62cfb7fa79c|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
cortex-debug|mar|0.4.7
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
comment-wrap|nex|0.0.2
code-spell-checker|str|2.0.12
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by IllusionMH** [comment] 2021-11-12 09:45
Not a bug. Editor data lives in JS therefore JS regexp engine used for Find, so you rely on features that are supported for JS regexps (by V8) and should use JS syntax. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet

I guess "numbered subroutine call" and "named subroutine call" should translate to "capturing group" and "named capturing group" and work as expected when you use proper syntax.

I don't think that JS has "balancing groups" or "resume match from begining".

**Comment by Ma-XX-oN** [comment] 2021-11-13 20:02
Oh, that's too bad. Looks like the libraries out there aren't capable either.  I guess this should be closed then?

**Comment by IllusionMH** [comment] 2021-11-14 00:51
I guess that this one can be closed as it works as supposed for current implementation, however I'm not a team member so you can wait for official resolution.

If these features are supported by PRCE2 compliant engine, you can try to use Find in Files which utilizes `ripgrep` (make sure you close editors as JS RegExp engine is used for open editors even during Find in Files).

I think there might be requests or investigations to use different RE engine for open editors that you can upvote, however I haven't found anything open quickly.

**Comment by Ma-XX-oN** [comment] 2021-11-14 17:34
Ok. Waiting for an official response.

**Comment by rebornix** [comment] 2021-11-16 06:06
@IllusionMH thanks for your help, you are correct. We don't support this now since we are using JS engine.

**Closed by rebornix** 2021-11-16 06:07 UTC
