### ISSUE TITLE
[go] General comment after type, var tokens mis-colored

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode#80522] opened 2019-09-08 01:27 UTC
It appears white instead of green:

<img width="383" alt="Screen Shot 2019-09-04 at 10 48 25 AM" src="https://user-images.githubusercontent.com/63830/64278416-8a141680-cf01-11e9-837b-886055af697c.png">

- VSCode Version: 1.38.0
- OS Version: macOS Mojave 10.14.6 (18G87)

Steps to Reproduce:

1. Enter this text into a .go file:

```go
/**/ type /**/ x /**/ int /**/
/**/ var /**/ x /**/ int /**/ = /**/ 123 /**/
/**/ const /**/ x /**/ int /**/ = /**/ 123 /**/
```

Does this issue occur when all extensions are disabled?: Yes

Originally reported as https://github.com/microsoft/vscode-go/issues/2732.

**Comment by alexr00** [comment] 2019-09-10 10:45
Duplicate of https://github.com/atom/language-go/issues/149

**Closed by alexr00** 2019-09-10 10:45 UTC
