### ISSUE TITLE
High startup latency waiting for WSL2 filesystem to be available

### ISSUE THREAD

**Issue by trama** [microsoft/vscode#121283] opened 2021-04-14 13:04 UTC
Dear all,

my VS code installation started to be really slow on opening.
After I start the app, just the window border appears, that it sits there for ~10 seconds and then the loading process continues.
This started happening after two events:
1) install of WSL extension (I worked on a git repo within my WSL2 installation)
2) update to last 21354 insider preview

About point 2) I noticed, in general, the system has a noticeable higher latency in several actions. Maybe acceptable for most, but visibly appreciable. However, I have no elements to say the VSCode slow down is due to 2), maybe it is independent.

In general, during load of VSCode, the app remains stuck at waiting for WSL2 distro to become accessible to do I don't know what :)
This is recognized using the ProcessMonitor utility.
I already tried to i) delete the WSL extension, ii) delete any reference to previous projects within the wsl distro, iii) as a last resort, delete most of the content of APPData - Roaming - Code folder.

I have not been able to solve this issue.
Below you can find the log obtained with the code cmd line.

I hope that someone is able to understand what is happening and help me solve this annoying issue.

As a side question, why the WSL2 distro takes so long to become accessible? Even from within the Explorer, if I would like ot access my linux data, I have to wait (and I don't think it is a coincidence) ~10 seconds before getting them available.

Thank you to anyone who may take care of answering and help.

Best regards

Federico

## System Info

* Code: 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b)
* OS: win32(10.0.21354)
* CPUs: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz(12 x 2592)
* Memory(System): 15.75 GB(7.55GB free)
* Memory(Process): 176.73 MB working set(155.09MB private, 1.71MB shared)
* VM(likelihood): 29%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                     |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------- |
| start => app.isReady                                            | 67       | [main]                    | initial startup: true                    |
| nls:start => nls:end                                            | 1        | [main]                    | initial startup: true                    |
| require(main.bundle.js)                                         | 98       | [main]                    | initial startup: true                    |
| app.isReady => window.loadUrl()                                 | 167      | [main]                    | initial startup: true                    |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 9295     | [main->renderer]          | NewWindow                                |
| require(workbench.desktop.main.js)                              | 701      | [renderer]                | cached data: NO, node_modules took 0ms   |
| wait for shell environment                                      | 1        | [renderer]                | -                                        |
| init storage (global & workspace)                               | 30       | [renderer]                | -                                        |
| init workspace service                                          | 41       | [renderer]                | -                                        |
| register extensions & spawn extension host                      | 494      | [renderer]                | -                                        |
| restore viewlet                                                 | 0        | [renderer]                | -                                        |
| restore panel                                                   | 0        | [renderer]                | -                                        |
| restore editors                                                 | 270      | [renderer]                | 1: workbench.editors.untitledEditorInput |
| overall workbench load                                          | 541      | [renderer]                | -                                        |
| workbench ready                                                 | 10820    | [main->renderer]          | -                                        |
| renderer ready                                                  | 1296     | [renderer]                | -                                        |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                        |
| extensions registered                                           | 11109    | [renderer]                | -                                        |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                                                 | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | ----------------------------------------------------- | --------------------------------------- |
| vscode.debug-auto-launch                | true  | 8         | 0             | 7               | *                                                     | vscode.debug-auto-launch                |
| vscode.git                              | true  | 109       | 7             | 78              | *                                                     | vscode.github                           |
| vscode.github                           | true  | 12        | 0             | 0               | *                                                     | vscode.github                           |
| vscode.emmet                            | false | 25        | 3             | 4               | onStartupFinished                                     | vscode.emmet                            |
| vscode.github-authentication            | false | 33        | 1             | 34              | onAuthenticationRequest:github                        | vscode.github-authentication            |
| vscode.merge-conflict                   | false | 4         | 1             | 3               | onStartupFinished                                     | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 44        | 3             | 75              | onAuthenticationRequest:microsoft                     | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 26        | 3             | 1               | onStartupFinished                                     | ms-vscode-remote.remote-wsl-recommender |
| ms-vscode.js-debug                      | false | 239       | 11            | 0               | onCommand:extension.js-debug.clearAutoAttachVariables | ms-vscode.js-debug                      |
| vscode.testing-editor-contributions     | false | 1         | 0             | 2               | onStartupFinished                                     | vscode.testing-editor-contributions     |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1618404285149	0	0
code/didStartMain	1618404285255	106	106
code/mainAppReady	1618404285322	67	173
code/willGenerateNls	1618404285323	1	174
code/didGenerateNls	1618404285324	1	175
code/willLoadMainBundle	1618404285324	0	175
code/fork/willLoadCode	1618404285340	16	191
code/registerFilesystem/file	1618404285419	79	270
code/didLoadMainBundle	1618404285422	3	273
code/willOpenNewWindow	1618404285489	67	340
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1618404285490	0	0
code/didStartRenderer	1618404294779	9289	9289
code/willShowPartsSplash	1618404294780	1	9290
code/didShowPartsSplash	1618404294781	1	9291
code/willLoadWorkbenchMain	1618404294784	3	9294
code/willWaitForShellEnv	1618404295484	700	9994
code/didWaitForShellEnv	1618404295485	1	9995
code/didLoadWorkbenchMain	1618404295485	0	9995
code/registerFilesystem/file	1618404295489	4	9999
code/registerFilesystem/vscode-userdata	1618404295489	0	9999
code/willInitWorkspaceService	1618404295492	3	10002
code/willInitStorage	1618404295493	1	10003
code/didInitStorage	1618404295523	30	10033
code/didInitWorkspaceService	1618404295533	10	10043
code/willStartWorkbench	1618404295534	1	10044
code/LifecyclePhase/Ready	1618404295537	3	10047
code/registerFilesystem/trustedDomains	1618404295626	89	10136
code/willRestoreEditors	1618404295804	178	10314
code/willLoadExtensions	1618404295870	66	10380
code/didRestoreEditors	1618404296074	204	10584
code/LifecyclePhase/Restored	1618404296075	1	10585
code/didStartWorkbench	1618404296075	0	10585
code/didRemovePartsSplash	1618404296075	0	10585
code/willConnectSharedProcess	1618404296090	15	10600
code/willHandleExtensionPoints	1618404296239	149	10749
code/didHandleExtensionPoints	1618404296356	117	10866
code/didLoadExtensions	1618404296364	8	10874
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1618404297907	0	0
code/fork/start	1618404298311	404	404
code/fork/willLoadCode	1618404298351	40	444
code/extHost/willConnectToRenderer	1618404298719	368	812
code/extHost/didConnectToRenderer	1618404298720	1	813
code/extHost/didWaitForInitData	1618404298769	49	862
code/extHost/didCreateServices	1618404298776	7	869
code/extHost/willWaitForConfig	1618404298779	3	872
code/extHost/didWaitForConfig	1618404298810	31	903
code/extHost/didInitAPI	1618404298816	6	909
code/extHost/didInitProxyResolver	1618404298817	1	910
code/extHost/ready	1618404298817	0	910
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1618404298823	6	916
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1618404298867	44	960
code/extHost/willLoadExtensionCode/vscode.debug-auto-launch	1618404298868	1	961
code/extHost/didLoadExtensionCode/vscode.debug-auto-launch	1618404298876	8	969
code/extHost/willLoadExtensionCode/vscode.git	1618404298876	0	969
code/extHost/didLoadExtensionCode/vscode.git	1618404298985	109	1078
code/extHost/willActivateExtension/vscode.microsoft-authentication	1618404298989	4	1082
code/extHost/willActivateExtension/vscode.debug-auto-launch	1618404298992	3	1085
code/extHost/willActivateExtension/vscode.git	1618404298992	0	1085
code/extHost/didActivateExtension/vscode.debug-auto-launch	1618404298999	7	1092
code/extHost/didActivateExtension/vscode.microsoft-authentication	1618404299067	68	1160
code/extHost/didActivateExtension/vscode.git	1618404299077	10	1170
code/extHost/willLoadExtensionCode/ms-vscode.js-debug	1618404299078	1	1171
code/extHost/didLoadExtensionCode/ms-vscode.js-debug	1618404299317	239	1410
code/extHost/willLoadExtensionCode/vscode.github	1618404299331	14	1424
code/extHost/didLoadExtensionCode/vscode.github	1618404299343	12	1436
code/extHost/willActivateExtension/ms-vscode.js-debug	1618404299343	0	1436
code/extHost/didActivateExtension/ms-vscode.js-debug	1618404299354	11	1447
code/extHost/willLoadExtensionCode/vscode.github-authentication	1618404299382	28	1475
code/extHost/didLoadExtensionCode/vscode.github-authentication	1618404299415	33	1508
code/extHost/willActivateExtension/vscode.github	1618404299415	0	1508
code/extHost/didActivateExtension/vscode.github	1618404299415	0	1508
```

### cached data created (lazy, might need refreshes)

[prof-5ae6.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/6310951/prof-5ae6.extHost.cpuprofile.txt)
[prof-5ae6.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6310954/prof-5ae6.main.cpuprofile.txt)
[prof-5ae6.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6310955/prof-5ae6.renderer.cpuprofile.txt)

**Comment by aeschli** [comment] 2021-04-14 15:24
The 9 seconds for `window.loadUrl() => begin to require(workbench.desktop.main.js)` are of the chart. But also some of the other numbers are very high.
Can be that Defender is scanning in the background? That's normally happening after an update. Check the task manager for processes running.

You write `High startup latency waiting for WSL2 filesystem`. In VSCode, WSL only comes into the play once the window is up and the Remote indicator says `Opening Remote...`. The WSL Log (`Remote-WSL: Show Log..`) will have more information.

If other applications also take very long, then this could be ab issue with the Windows Insiders build. You could look into reverting to the previous version.

I'm currently running the insider build from the dev channel (21354_co_release.21042-1630) and speed seems to be ok.

**Comment by trama** [comment] 2021-04-14 16:45
Actually, I am using exactly the same build.
And since this build I started noticing this behavior with VSCode and, notably, all the Office apps.
In the caso of Word, Powerpoint and Excel, the behavior is slightly different: the window of the relevant app appears quite soon, but the app starts to be responsive more or less those 10 seconds after.

Maybe I may try to revert the upgrade (never done before) or just wait some days to the next update.

Indeed, the defender is working in the background a lot (it is taking my resources around 10/15% steadily, but may it delay the opening of applications so much?

Thanks

Federico

**Comment by aeschli** [comment] 2021-04-19 09:14
I'm closing this, as other applications are running slower, this is unlikely to be a VSCode or Remote-WSL issue. Also I'm not able to reproduce with the same setup.
I suggest to raise the issue with the Windows Feedback Hub. (see https://docs.microsoft.com/en-us/windows-insider/troubleshooting)

**Closed by aeschli** 2021-04-19 09:14 UTC
