### ISSUE TITLE
"Problem Matcher -> Background/Watching Tasks" reports the fixed syntax error.

### ISSUE THREAD

**Issue by stuartZhang** [Microsoft/vscode#32437] opened 2017-08-14 01:42 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
workbench|and|0.1.6
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
open-html-in-browser|cod|0.1.21
vscode-faker|dee|1.1.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
RunOnSave|eme|0.0.16
prettier-vscode|esb|0.22.1
tortoise-svn|fan|0.1.1
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.14
vscode-firefox-debug|hbe|0.15.3
beautify|Hoo|1.1.1
icon-fonts|idl|1.8.0
docthis|joe|0.4.7
vscode-rust|kal|0.4.2
vscode-annotations|mez|0.1.6
HTMLHint|mka|0.3.3
debugger-for-chrome|msj|3.1.7
debugger-for-edge|msj|0.4.1
vscode-css-peek|pra|1.3.1
project-snippets|reb|0.5.0
vscode-icons|rob|7.12.0
html5-boilerplate|sid|1.0.1
vscode-todo-highlight|way|0.5.8
bootstrap-3-snippets|wcw|0.1.0
debug|web|0.21.2
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Create a Task for associating the Problem Matcher with my local Grunt-script output. The task configuration is as below:
{
  "version": "0.1.0",
  "args": ["--no-color"],
  "command": "grunt",
  "isShellCommand": true,
  "runner": "process",
  "tasks": [
    {
      "taskName": "watch",
      "args": ["--eslint-output-format=compact", "--web-server-origin=http://192.168.85.154:8887"],
      "isBuildCommand": true,
      "isBackground": true,
      "problemMatcher": {
        "owner": "javascript",
        "fileLocation": "absolute",
        "pattern": {
          "regexp": "^(?:stylelint: )?(.+)(?:: line |:)(\\d+)(?:, col |:)(\\d+)(?:, (Error|Warning) -|:) (.+)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        },
        "background": {
          "activeOnStart": true,
          "beginsPattern": "^Running \"wait_async:(?:eslint|postcss)\" \\(wait_async\\) task$",
          "endsPattern": "^(?:(Completed in (\\d+)(\\.\\d+)?s at .+ GMT.+ - )?Waiting\\.\\.\\.|Warning: Rollup Fails!)$"
        }
      }
    }
  ]
}

2. Type "ctrl + shift + b" to start the tasks.

3. Open a JavaScript file in a text editor.

4. Make the 1st syntax error. And then, the Problem Matcher captures it and highlight in the text editor. The Grunt log is as such:

Running "wait_async:eslint" (wait_async) task
waiting for an async task
Running "eslint:moduleWatch" (eslint) task
Add an ESLint plugin eslint-plugin-connect-es6
Add an ESLint plugin eslint-plugin-sweetjs
c:\Users\stzhang\SVN\tj-map12\user\stuartzhang\vectorMap\main\js\map\sources\nbmVector\tileLoader\fetch-nbm-pojo.bbjs: line 26, col 26, Error - Multiple spaces found before '{'. (no-multi-spaces)
1 problem
Warning: Task "eslint:moduleWatch" failed.
Running "watch" task
Waiting...

5. Make the 2nd syntax error. And then, the Problem Matcher captures it and highlight in the text editor. The Grunt log is as such:

Running "wait_async:eslint" (wait_async) task
waiting for an async task
Running "eslint:moduleWatch" (eslint) task
Add an ESLint plugin eslint-plugin-connect-es6
Add an ESLint plugin eslint-plugin-sweetjs
c:\Users\stzhang\SVN\tj-map12\user\stuartzhang\vectorMap\main\js\map\sources\nbmVector\tileLoader\fetch-nbm-pojo.bbjs: line 26, col 26, Error - Multiple spaces found before '{'. (no-multi-spaces)
c:\Users\stzhang\SVN\tj-map12\user\stuartzhang\vectorMap\main\js\map\sources\nbmVector\tileLoader\fetch-nbm-pojo.bbjs: line 29, col 11, Error - Multiple spaces found before '{'. (no-multi-spaces)
2 problems
Warning: Task "eslint:moduleWatch" failed.
Running "watch" task
Waiting...

6. At this time, there are two highlighting points in the text editor.

7. [**# Error lives here**] Fixed the 1st syntax error. However, in the text editor, the highlighting point for the 1st error is still present. The Grunt log is as such:

Running "wait_async:eslint" (wait_async) task
waiting for an async task
Running "eslint:moduleWatch" (eslint) task
Add an ESLint plugin eslint-plugin-connect-es6
Add an ESLint plugin eslint-plugin-sweetjs
c:\Users\stzhang\SVN\tj-map12\user\stuartzhang\vectorMap\main\js\map\sources\nbmVector\tileLoader\fetch-nbm-pojo.bbjs: line 29, col 11, Error - Multiple spaces found before '{'. (no-multi-spaces)
1 problem
Warning: Task "eslint:moduleWatch" failed.
Running "watch" task
Waiting...

8. Fixed the 2nd syntax error. Both highlighting points for all syntax errors are erased.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment] 2017-08-14 08:35
@stuartZhang thanks for the detailed issue report. Do you have a GitHub repository I could clone that demos the problem. This would help tracking this down since I don't know what exactly your grunt script does.

**Comment by stuartZhang** [comment] 2017-08-14 09:43
1.  This is the JavaScript program for Grunt script and its dependency: 
[Gruntfile.zip](https://github.com/Microsoft/vscode/files/1221800/Gruntfile.zip)

2. The snapshot for the build success:
![success](https://user-images.githubusercontent.com/13935927/29266408-3f757bb2-8117-11e7-8118-f64ec1040253.png)

3. The snapshot for the build failure:
![failure-1](https://user-images.githubusercontent.com/13935927/29266611-1773f908-8118-11e7-9660-477228d090d5.png)

**Comment by dbaeumer** [comment] 2017-08-14 09:46
Can you provide the test file as well?

**Comment by stuartZhang** [comment] 2017-08-14 09:52
[test-files.zip](https://github.com/Microsoft/vscode/files/1221836/test-files.zip)

The command: 
$ grunt watch --eslint-output-format=compact --web-server-origin=http://192.168.85.154:8887

And then, edit any of *.bbjs files. The extension name "bbjs" means the Babel JavaScript file.

**Comment by Ciantic** [comment] 2017-08-16 17:19
I'm having issues about problems not clearing in TypeScript project. This same configuration worked with earlier versions.

**Comment by stuartZhang** [comment] 2017-08-17 00:55
You are right. In the earlier version, the <Problem Matcher> for watching is working very well. However, it's problematic in the latest 64-bit version.

**Comment by dbaeumer** [comment] 2017-08-17 08:13
@Ciantic do you have an example demoing the TS case ?

**Comment by dbaeumer** [comment] 2017-08-24 10:03
Reopening.

**Comment by bobzhang** [comment] 2017-09-04 01:32
This is a blocking issue to me, anyway how can I resintall an old release?

**Comment by dbaeumer** [comment] 2017-10-30 20:50
I was able to reproduce this and it got fixed already a while ago. The corresponding issue is #34412

Closing as dup.

**Closed by dbaeumer** 2017-10-30 20:50 UTC
Labels: tasks
