### ISSUE TITLE
Markdown preview view

### ISSUE THREAD

**Issue by avaid96** [Microsoft/vscode#18238] opened 2017-01-06 19:12 UTC
- VSCode Version: 1.6.0
- OS Version: OSX 10.12

Steps to Reproduce:

1. Type in MD (Markdown) doc with Preview to the side 
   - open .md file
   - cmd + shift + p and search from preview
   - open preview to the side
2. When you start typing beyond the range of preview - doesn't auto-scroll as you add new content

Would be awesome to have it autoscroll down 😄

**Comment by mjbvz** [comment] 2017-01-06 20:00
Closing as duplicate of #5047

**Closed by mjbvz** 2017-01-06 20:00 UTC
Labels: duplicate, markdown
