### ISSUE TITLE
Search occurences with (ctrl +f) : initial position of selected occurence displays wrong value

### ISSUE THREAD

**Issue by Manaril** [microsoft/vscode#158464] opened 2022-08-18 10:03 UTC
Type: <b>Bug</b>

Open a file with multiple occurences of the same string
eg. XML with 2000 "\</node\>" tags

Select the last "\</node\>" of the file and hit search shortcut (ctrl + f)

The search widget display 1999 of 2000 occurences whereas it should be 2000 of 2000. Navigating forward jump immediately to 1 of 2000 and navigating backward goes to the actual 1999 of 2000, fixing the counter

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (5.26GB free)|
|Process Argv|--crash-reporter-id 6f0a27a5-440e-421d-8a19-351c1ab77b14|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
xml|Dot|2.5.1
LogFileHighlighter|emi|2.16.0
vscode-diff|fab|1.4.2
vscode-language-pack-fr|MS-|1.70.8170921
vscode-auto-scroll|pej|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by amunger** [comment] 2022-12-14 20:52
duplicate of https://github.com/microsoft/vscode/issues/121527

**Closed by amunger** 2022-12-14 20:52 UTC
Labels: bug, editor-find
