### ISSUE TITLE
Undo History wiped after "Save As <newname>"

### ISSUE THREAD

**Issue by aleemb** [microsoft/vscode#95339] opened 2020-04-15 14:14 UTC
- VS Code Version: 1.44.1
- OS Version: 10.15.4 (19E266)

Steps to Reproduce:

1. Open any existing file
2. Make some changes
3. Save As <different name>
4. Hit undo. It doesn't undo your last change

Does this issue occur when all extensions are disabled?: Yes

Expected Behavior:

Undo history should not be wiped out an existing file is saved as a different name. Interestingly, if I Save As <original filename>, then the undo history comes back.

**Comment by alexdima** [comment] 2020-04-24 15:06
Duplicate of #17977

**Closed by alexdima** 2020-04-24 15:06 UTC
