### ISSUE TITLE
Vertical scroll bar jump to end of file

### ISSUE THREAD

**Issue by bjakic-c4** [microsoft/vscode#108294] opened 2020-10-08 10:01 UTC
Steps:
1. change to another application with ALT-TAB
2. back again to VCS with ALT-TAB
3. scroll down a little with mouse wheel
4. vertical scrollbar jumps to end of file

NOTE: cursor position remains correct and unchanged

**Comment by alexdima** [comment] 2020-10-26 13:53
Duplicate of #28795

**Closed by alexdima** 2020-10-26 13:53 UTC
