### ISSUE TITLE
Flicker when installing SSH

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#186286] opened 2023-06-27 09:18 UTC
Testing #186222

In an empty profile, lots of flicker in the picker:

![Recording 2023-06-27 at 11 18 07](https://github.com/microsoft/vscode/assets/900690/07e5bc24-cf4a-4394-bd4e-9c08c12a95b2)

**Comment by bhavyaus** [comment] 2023-06-27 22:37
Dupe of https://github.com/microsoft/vscode/issues/186286

**Closed by bhavyaus** 2023-06-27 22:37 UTC
