### ISSUE TITLE
Infinite saving after edit .svg files

### ISSUE THREAD

**Issue by Tirro** [microsoft/vscode#93004] opened 2020-03-19 11:37 UTC
Infinite saving after edit .svg file

`Saving 'foo': Getting code actions from ''Vetur', 'TSLint Vue''` 

- VSCode Version: 1.43.1
- OS Version: Windows 10

Steps to Reproduce:
1. Open project
2. Drop `.svg` file from the file system project folder to the vscode
2. Edit `.svg` file
3. Try changing any file that has handlers involved

Does this issue occur when all extensions are disabled?: Yes

**Comment by jdahdah** [comment] 2020-03-20 13:24
I've been having the same issue for a few weeks now, especially for SVG files, but I just noticed it happening for an .erb file as well, which does reference .svg files but only as `<img>` tags. I have to restart VSCode every few minutes at this rate and it sends my computer's fans into overdrive.

The message I receive has other extensions listed:

```
Saving 'foo': Getting code actions from ''ESLint', 'GitHub Pull Requests''
```

![vscode_crash](https://user-images.githubusercontent.com/5282190/77167388-3e4c4780-6ab6-11ea-836d-519083f20d45.jpg)

**Comment by octref** [comment] 2020-03-20 17:12
Vetur does not support svg files. You can try disabling TSLint Vue, I guess that's the cause. Anyway it's not a VS Code issue so I'm closing.

**Closed by octref** 2020-03-20 17:12 UTC
Labels: new release

**Comment by octref** [comment] 2020-03-20 17:14
@jdahdah I think your issue is related to ESLint. Please try to create a minimal reproducible case and open an issue for ESLint.
