### ISSUE TITLE
Same file with two different names open in vscode

### ISSUE THREAD

**Issue by MalikBagwala** [microsoft/vscode#78426] opened 2019-08-03 11:18 UTC
Issue Type: <b>Bug</b>

there are two files namely
header.jsx
Header.jsx
as evident from the open editors. but in the file system it is clearly visible that there is a single header.jsx file. by the way these two also appear in the command panel (ctrl + p)

![Code - 03-08-2019-505](https://user-images.githubusercontent.com/23068029/62411330-dae8d480-b60e-11e9-967b-d43404b783fc.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.90GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.28
dart-code|Dar|3.3.0
flutter|Dar|3.3.0
gitlens|eam|9.9.2
prettier-vscode|esb|1.9.0
vscode-highlight|fab|1.3.4
styled-snippets|fer|1.0.3
vscode-styled-components|jpo|0.0.26
python|ms-|2019.6.24221
debugger-for-chrome|msj|4.11.7
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.8.1
remove-comments|pli|1.2.2
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
ayu|tea|0.18.0
markdown-all-in-one|yzh|2.4.2

(4 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-08-03 20:47
/confirmed

Steps to reproduce:

1. Create file `test.js` and open it
2. Use terminal to echo filename in wrong case `echo "./Test1.js"`
3. <kbd>Ctrl + Click</kbd> on link to open same file.

However there these files are out of sync. Using Rename (or any other file editing) in `test1.js` won't update `Test1.js` version, while using Rename in `Test1.js` file will update `test1.js`, but not in `Test1.js` 😆 

VS Code version: Code - Insiders 1.37.0-insider (0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b, 2019-08-02T21:22:13.578Z)
OS version: Windows_NT x64 10.0.18950

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment] 2019-08-05 09:26
Sounds like a famous duplicate of https://github.com/microsoft/vscode/issues/12448
Leaving up to @bpasero to decide if to close as dup.

**Closed** 2019-08-05 13:20 UTC
Labels: *duplicate
