### ISSUE TITLE
Autocomplete in Visual Studio Code not working correctly (SASS,CSS,LESS)

### ISSUE THREAD

**Issue by htar** [Microsoft/vscode#26127] opened 2017-05-06 17:49 UTC
Hello

I have problems with auto complete, when I write for Emmet autocomplete displays options that are not acceptable in css 'box-decoration-break' 'stroke-dashoffset' and another. You can view this in screenshots.
so I can't using quickly   Emmet or another snippet 

Will be very good that I can disable default 'auto complete - snippet' in the settings or you turn off all bad autocomplete snippet in css scss less
![scss3](https://cloud.githubusercontent.com/assets/4822479/25449966/1a5a735c-2ac6-11e7-81fb-48912e9bcc3a.jpg)
![scss2](https://cloud.githubusercontent.com/assets/4822479/25449967/1a7362fe-2ac6-11e7-810b-bb7bc015015b.jpg)
![scss](https://cloud.githubusercontent.com/assets/4822479/25449968/1a82a552-2ac6-11e7-83f3-63d5dacfb35f.jpg)

![css](https://cloud.githubusercontent.com/assets/4822479/25449946/148ccc9a-2ac6-11e7-8879-c8863f3b3136.jpg)

**Comment by mrmlnc** [comment] 2017-05-06 19:16
```json
{
  "key": "tab",
  "command": "-acceptSelectedSuggestion"
},
```

**Comment by htar** [comment] 2017-05-06 19:28
Thank  you

**Comment by aeschli** [comment] 2017-05-08 15:55
@htar I don't understand from your description and screenshots what is the problem.
You don't like that tab picks a suggestion?

**Comment by htar** [comment] 2017-05-08 16:25
Hello, I have  problem with my previous post  https://github.com/Microsoft/vscode/issues/25092

option that proposed @mrmlnc, solves my problem

if you suggest some other options to solve the problem,its be grateful

**Comment by aeschli** [comment] 2017-05-08 17:01
@htar Also see https://github.com/Microsoft/vscode/issues/1952#issuecomment-293770991

Closing as duplicate of #1952

**Closed by aeschli** 2017-05-08 17:01 UTC

**Comment by ramya-rao-a** [comment] 2017-05-08 17:14
Thanks @mrmlnc !

@htar Use what @mrmlnc  has shared or https://github.com/Microsoft/vscode/issues/1952#issuecomment-293770991 as work-around for now.

We are working on getting emmet abbreviations in the suggestion list which will solve your problem in the long term and that work is being tracked here : https://github.com/Microsoft/vscode/issues/21943

**Comment by htar** [comment] 2017-05-08 17:21
Thank you

**Comment by ramya-rao-a** [comment] 2017-06-01 05:25
@htar

See https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464 for updates on this issue. You can now get emmet abbreviation expansion in the suggestion list without giving up on quick suggestions
