### ISSUE TITLE
Backslash incorrectly escapes single quote in MSSQL language

### ISSUE THREAD

**Issue by poenn** [Microsoft/vscode#12278] opened 2016-09-19 18:23 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. Create a new .sql file
2. Add a line similar to SELECT \* from MyTable WHERE Value = 'C:\path\to\file\' AND 1 = 1
3. The trailing backslash is incorrectly escapes the ending single quote, resulting in the rest of the line being displayed as quoted text

Screen capture of incorrect behaviour in VS Code
![vscodescreencap](https://cloud.githubusercontent.com/assets/13856906/18643700/397629f6-7e74-11e6-9875-6aac27c12726.PNG)

Screen capture of correct behaviour in SQL Server Management Studio
![ssmsscreencap](https://cloud.githubusercontent.com/assets/13856906/18643701/3977a556-7e74-11e6-913b-87d762fa7466.PNG)

**Comment by poenn** [comment] 2016-09-19 18:26
Screen capture of correct behaviour in Visual Studio 2015
![vs2015screencap](https://cloud.githubusercontent.com/assets/13856906/18643869/f1902550-7e74-11e6-8b98-fe36b8bd5412.PNG)

**Comment by aeschli** [comment] 2017-02-01 17:05
duplicate of #5223

**Closed by aeschli** 2017-02-01 17:05 UTC
Labels: bug, upstream
