### ISSUE TITLE
`git.path` fails in workspace settings

### ISSUE THREAD

**Issue by diablodale** [microsoft/vscode#98517] opened 2020-05-25 13:34 UTC
Issue Type: <b>Bug</b>

1. Have working VSCode and working git functionality in VSCode
2. menu file/preferences/settings
3. In json or UI, go to workspace settings
4. attempt to set `"git.path"`

## Result

The UI and json do not recognize `git.path` at the workspace settings.  
Entering a `git.path` in the workspace settings, reload the window, can see it has no effect and is ignored.
This setting is only settable from the master top-level settings file.

## Expected

`git.path` to be settable at the workspace settings level as the majority of other settings. Having this functionality is important so that a developer can set a specific git to be used for a specific project/workspace. Windows and VSCode are no longer a single OS, single environment. Now projects and the editors (e.g. vscode) for them span multiple OS, environments, etc.

In my specific scenario, I use the Win32 git.exe only on one project. For all other projects, I use the WSL git.exe due to its extensive integration into auth, gpg signing, and portable settings. ✔

## Workaround

Editing the master settings.json every time vscode is launched to match the project's needs for `git.path` ☹

## Additional info

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.35.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
todo-tree|Gru|0.0.176
vscode-random|jre|1.6.1
rainbow-csv|mec|1.7.0
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.1
vscode-sort-json|ric|1.18.0
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.0.0

</details>

**Comment by kieferrm** [comment] 2020-05-25 22:49
`git.path` is a user setting to avoid potentially running unauthorized code.

**Comment by diablodale** [comment] 2020-05-26 01:33
@kieferrm , I don't understand your comment. Did you mistype or missing a word? As a guess, did you intend to write "git.path is *not* a user setting..."?

If that was your intention, then a restriction like that doesn't protect anyone with any actual beneficial effect. That's like putting a red velvet rope around something. Or security through obscurity. Its meaningless and only hinders normal users. It is no barrier to actual evil hackers/virus. 🙈

As an example, I took 5 minutes (really...only 5 minutes) and I found 11 dangerous workspace settings that can point to dangerous unauthorized code. As I see the ecosystem, the issue of "protecting against evil hackers" is not solvable by workspace settings.

* everything task.json
* everything launch.json
* `python.pythonPath`
* `python.linting.mypyPath`
* `docker.certPath`
* `eslint.nodePath`
* `C_Cpp.default.compilerPath`
* `terminal.integrated.shell.*`
* `cmake.cmakePath`
* `cmake.ctestpath`, 
* and a bonus `phpcs.executablePath`

**Comment by joaomoreno** [comment] 2020-05-26 12:44
As @kieferrm mentioned, this is both a security implementation as well as designed, since it's not trivial to have the git extension work with multiple git installations at once. Closing this as won't fix.

Though I'd be interested in your **specific** scenario that drove you to this feature request.

**Closed by joaomoreno** 2020-05-26 12:44 UTC

**Comment by diablodale** [comment] 2020-05-26 14:39
Unclear why this issue is closed if we are having a discussion. I request it be reopened until we complete our investigation...or open a new issue.

**Comment by joaomoreno** [comment] 2020-05-26 14:43
We can keep having the discussion. Again, I'm **very** interested in your specific scenario that drove you to this feature request, can you elaborate on that?
