### ISSUE TITLE
Seti file icons are no longer shown

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#40636] opened 2017-12-21 11:00 UTC
- VSCode Version: Code - Insiders 1.20.0-insider (8f015e56dbd0b2a51d562538d7d12599ab9fc0f9, 2017-12-21T08:34:32.639Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
(1 theme extensions excluded)
---

Steps to reproduce:
1. Select the `Seti (Visual Studio Code)` file icon theme.

There is still an offset for the icon on tabs, but not in the explorer tree.
Selecting `None` or `Minimal` still works normally.

**Comment by Nickforall** [comment] 2017-12-21 12:23
I am having the same problem with `Material Icon Theme`.

**Comment by aeschli** [comment] 2017-12-21 14:09
@Nickforall Please report that against https://github.com/PKief/vscode-material-icon-theme

**Comment by aeschli** [comment] 2017-12-21 16:11
The seti font issue is caused by https://github.com/jesseweed/seti-ui/issues/464

**Comment by aeschli** [comment] 2017-12-21 16:16
I patched the seti font on our side and pushed the fix.

**Closed** 2017-12-21 16:15 UTC
Labels: insiders, themes

**Comment by Nickforall** [comment] 2017-12-21 16:34
Okay I will, thanks.

Op do 21 dec. 2017 om 15:10 schreef Martin Aeschlimann <
notifications@github.com>
