### ISSUE TITLE
Unable to see the full package path

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#82214] opened 2019-10-10 07:44 UTC
Unable to see the full package path
vscode
![11111111](https://user-images.githubusercontent.com/27546390/66548732-68e3bd00-eb74-11e9-81ca-58e65dbf2703.png)
idea
![idea1](https://user-images.githubusercontent.com/27546390/66548824-93357a80-eb74-11e9-8f7a-9a22cf28a31f.png)
![idea2](https://user-images.githubusercontent.com/27546390/66548842-9af51f00-eb74-11e9-8614-287ec8e28891.png)
![idea3](https://user-images.githubusercontent.com/27546390/66548852-a21c2d00-eb74-11e9-95ed-5e6e8323c9bc.png)

**Comment by octref** [comment] 2019-10-17 17:54
Duplicate of #29126.

**Closed by octref** 2019-10-17 17:54 UTC

**Comment by 395053994** [comment] 2019-10-18 15:24
For the writing of the java language, this is a fatal bug, because you can't see the complete package namespace, which makes it impossible to select the correct class for code writing. This fatal bug has been proposed for more than two years. Why no one has priority to solve this problem? The problem, if it is a technical problem, you can refer to the relevant implementation and source code of Eclipse!




------------------ 原始邮件 ------------------
发件人: "Pine"<notifications@github.com>;
发送时间: 2019年10月18日(星期五) 凌晨1:57
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "青春！"<395053994@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] Unable to see the full package path (#82214)




Duplicate of #29126.
