### ISSUE TITLE
Cannot profile during reload

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#112643] opened 2020-12-16 09:54 UTC
* run from master `./scripts/code.sh`
* open dev tools
* start CPU profiling (more tools > JavaScript profiler)
* (alternatively start performance profiling from the performance tab)
* reload the window via ctrl+r
* profiling doesn't work, reload does work

This is somewhat severe because it doesn't allow us to profile startup properly

**Comment by bpasero** [comment] 2020-12-16 09:59
Cannot reproduce on macOS 10.15.6, possibly Big Sur related?

**Comment by jrieken** [comment] 2020-12-16 10:01
related to https://github.com/microsoft/vscode/issues/111827?

**Comment by jrieken** [comment] 2020-12-16 10:33
Seems to be an issue with MSFT Defender ATP for mac...

**Comment by jrieken** [comment] 2020-12-16 10:34
I reported this to them, lets see what we hear back

**Comment by deepak1556** [comment] 2022-12-12 18:19
Closing as issue is not with the runtime.

**Closed by deepak1556** 2022-12-12 18:19 UTC
Labels: upstream
