### ISSUE TITLE
Shell task without environment variables.

### ISSUE THREAD

**Issue by carlos-piloto** [Microsoft/vscode#72323] opened 2019-04-15 08:40 UTC
- VSCode Version: 1.33.0
- OS Version: Windows 10 17134.706

We are using VSCode to build an IoT project for STM32 products using cmake. We need to build it using a toolchain and normally we can compile it from the cmd by using several environment variables with the different tools path.
We created several tasks to build and run the project, but the problem is that the cmd/powershell shell is launching VSCode does not have any environment variables.

For the moment we created a config variable in the settings to specify the root folder of all the compilation tools, but we do not think ois the best solution.

Steps to Reproduce:

1. Run a task
2. Try to read an environment variable by using: ${env:ENV_VAR_NAME} in the task or from the programe running in the shell.

You can see the images below of the winpty process that launch the shell:

![image](https://user-images.githubusercontent.com/30349992/56118701-cc48b580-5f6a-11e9-992f-dd6f27cf1f24.png)

![image](https://user-images.githubusercontent.com/30349992/56118721-d5398700-5f6a-11e9-9632-f2b2d9ade6d7.png)

You can see that the process is launched without the environment variables.

**Comment by alexr00** [comment] 2019-04-15 09:09
duplicate of https://github.com/Microsoft/vscode/issues/72029
If you update to 1.33.1 you will have the fix.

**Comment by alexr00** [comment] 2019-04-15 09:12
That other issue is about ${env:ENV_VAR_NAME} not expanding in tasks, not about no environment being given to the terminal. I can't reproduce that though. Can you try updating to 1.33.1 and running this task:
````
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo path",
            "type": "shell",
            "command": "Write-Host '${env:PATH}'",
        }
    ]
}
````

**Comment by carlos-piloto** [comment] 2019-04-15 09:26
Hi @alexr00 ,

Indeed I updated the VSCode to 1.33.1 and I can access env variables right now ;-)

Thanks a lot for the quick response and support.

**Closed** 2019-04-15 10:06 UTC
Labels: needs more info, tasks

**Comment by Clecius** [comment] 2019-04-24 14:24
Cannot use additional environment variables in task.

VSCode Version: 1.33.1
OS: Windows_NT x64 6.1.7601

**tasks.json**
```
{
  "options": {
    "env": {
      "ENVAR": "VALUE"
    }
  },
  "tasks": [
    {
      "type": "shell",
      "label": "SHOWVAR",
      "command": "echo",
      "args": [
        "ENVAR[${env:ENVAR}] - OS[${env:OS}] / ENVAR[%ENVAR%] - OS[%OS%]"
      ],
      "problemMatcher": [],
    }
  ],
  "version": "2.0.0"
}
```
**Terminal:**
```
> Executing task: echo "ENVAR[] - OS[Windows_NT] / ENVAR[%ENVAR%] - OS[%OS%]" <
ENVAR[] - OS[Windows_NT] / ENVAR[VALUE] - OS[Windows_NT]
```

**Comment by alexr00** [comment] 2019-04-26 15:01
That is correct! This needs to be better documented. Please see the new documentation here: https://github.com/Microsoft/vscode-docs/pull/2603

**Comment by idanpa** [comment] 2019-04-28 09:37
@alexr00, thanks for this update of the documentation, but is there any plan to change this behavior of "env" in task.json?
See #47985 and #22374.

**Comment by alexr00** [comment] 2019-04-29 10:01
#47985 is for overwriting env vars and #22374 is for global scope tasks only. There is no plan to change the behavior [here](https://github.com/Microsoft/vscode/issues/72323#issuecomment-487089255). Feel free to open a feature request for it. However, it doesn't seem strictly necessary to expand env vars that are defined in the task in the task command like this. Since you are defining the value in the tasks.json, you already know the expanded value and you could easily just include the expanded value in the task command.
