### ISSUE TITLE
Save Workspace As... function doesn't save .code-workspace extension anymore.

### ISSUE THREAD

**Issue by shinebayar-g** [microsoft/vscode#85299] opened 2019-11-21 13:16 UTC
- VSCode Version: 1.40.1
- OS Version: Ubuntu 18.04.3 LTS

Steps to Reproduce:

1. Open VsCode.
2. File - Save Workspace As... - Select path to save workspace settings.

Problem:

VsCode workspace settings files must have `.code-workspace` extension. After recent update new created VsCode workspaces no longer have this extension. Workspace files created without any extension now.

**Comment by gjsjohnmurray** [comment] 2019-11-21 14:04
/duplicate of #84818 and will be fixed in upcoming October 2019 Recovery 2

**Closed** 2019-11-21 14:04 UTC
Labels: *duplicate

**Comment by shinebayar-g** [comment] 2019-11-21 14:05
Oh thanks, I didn't see that duplicate. my bad.
