### ISSUE TITLE
JIRA/Bitbucket screens stay blank on insiders with WSL2, work on regular release.

### ISSUE THREAD

**Issue by crewone** [microsoft/vscode#101338] opened 2020-06-30 06:09 UTC
Issue Type: <b>Bug</b>

The official JIRA/Bitbucket extension works as expected on the regular VSCode - both in WSL2 (Ubuntu) and native windows 10.

However in the newly released insiders, when connected to WSL2, the screens stay blank. When in native windows 10 mode, it does work.

VS Code version: Code - Insiders 1.47.0-insider (7923112cdd20575406ec547b55a99c289dd7d7e2, 2020-06-29T05:53:43.438Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (11.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|25.01GB (19.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|25.01GB (19.62GB free)|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
better-comments|aar|2.0.5
Bookmarks|ale|11.3.1
atlascode|atl|2.6.5
vscode-twig-pack|baj|1.1.0
auto-align|bla|0.0.13
vscode-intelephense-client|bme|1.4.1
vscode-git-grep|bok|0.0.7
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
vscode-style-formatter|dwe|1.0.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.0
php-debug|fel|1.13.0
auto-close-tag|for|0.5.7
lintlens|ghm|3.0.0
go|gol|0.15.0
go-nightly|gol|2020.6.2914
package-watcher|Gre|0.0.2
beautify|Hoo|1.5.0
php-cs-fixer|jun|0.1.155
nullish-coalescing-operator-grammar|Lev|0.0.1
vscode-xslt-snippets|mar|0.1.0
twig-language-2|mbl|0.9.1
vscode-language-babel|mgm|0.0.29
prettify-json|moh|0.0.3
vscode-scss|mrm|0.9.0
php-docblocker|nei|2.1.0
material-icon-theme|PKi|4.2.0
seti-icons|qin|0.1.3
quicktype|qui|12.0.46
vscode-yaml|red|0.8.0
iferrblocks|rst|1.1.1
vs-code-prettier-eslint|rve|0.3.2
vscode-javascript-booster|sbu|14.0.1
git-merger|sha|0.4.1
stylelint|shi|0.51.0
vscode-fileutils|sle|3.0.1
sass-indented|syl|1.8.7
errorlens|use|3.1.1
vscodeintellicode|Vis|1.2.9
change-case|wma|1.0.0
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.2
html-css-class-completion|Zig|1.19.0
better-comments|aar|2.0.5
bracket-pair-colorizer-2|Coe|0.1.4
auto-close-tag|for|0.5.7
nullish-coalescing-operator-grammar|Lev|0.0.1
vscode-xslt-snippets|mar|0.1.0
remote-wsl|ms-|0.44.4
js-debug-companion|ms-|1.0.2
debugger-for-chrome|msj|4.12.8
material-icon-theme|PKi|4.2.0
seti-icons|qin|0.1.3
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|10.1.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.2

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2020-07-01 09:16
I can reproduce with the latest VSCode in WSL. Webviews stay empty.
Works with the TestResolver and SSH.

This looks like https://bitbucket.org/atlassianlabs/atlascode/issues/424/views-not-working-in-vscode-insiders
referring to https://github.com/microsoft/vscode/issues/97962

@mjbvz Could that be related? Any idea how to debug this?

**Comment by mjbvz** [comment] 2020-07-01 18:59
Duplicate of #101272

**Closed by mjbvz** 2020-07-01 18:59 UTC
