### ISSUE TITLE
Auto-import autocomplete with "dummy" suggestions

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#43777] opened 2018-02-15 19:12 UTC
- VSCode Version: 1.20.1
- OS Version: macOS

![image](https://user-images.githubusercontent.com/10441177/36275613-fecd25f6-1293-11e8-82e8-8eb410644d23.png)

I don't even know how `ReactiveTest` is here, but seems it's from `rx` lib which isn't downloaded into `node_modules`. Also if it helps I tried to do it with workspaces (with 3 projects) and without workspaces just opened my project. I only have downloaded `ESLint` and `Jest`.  I really like auto import, but it really annoys when you have a lot of "dummy" suggestions in the list.

**Comment by svipben** [comment] 2018-03-15 06:26
@mjbvz Let me know if I could help you somehow.

**Comment by mjbvz** [comment] 2018-03-23 22:41
@svipben Do you have a small example project that shows this problem?

Looks like this was also reported here: https://github.com/Microsoft/TypeScript/issues/13373

**Comment by svipben** [comment] 2018-03-25 12:47
It happens to me even if I opened new untitled with JavaScript language mode.

**Comment by mjbvz** [comment] 2018-04-17 22:33
Ok, this looks like the same symptoms at the upstream issue but it is pulling in entries from from your automatically acquired typings instead of your local ones. In the latest vscode insiders, can you please look in the tsserver log to see where these entries may be coming from:

1. With `"typescript.tsserver.log": "verbose"` enabled
1. Restart vscode
1. Reproduce the problem
1. Run the vscode command `TypeScript: Open TS Server logs`
1. Look in the `tsserver.log` file that is opened

If you can share the logs I or someone on the typescript can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by svipben** [comment] 2018-04-18 05:11
@mjbvz Hi, I can't reproduce it, tried in 1.22.2 version of Stable. I'm not using Insiders. So we can keep it open for some time if someone reproduces it.
Maybe it was fixed after TS 2.8?

**Comment by mjbvz** [comment] 2018-04-19 06:11
Possibly. 2.8 did have a lot of fixed in this area, but I don't know which one could have fixed this specifically. If see it again, please let me know

**Closed by mjbvz** 2018-04-19 06:11 UTC
Labels: javascript, needs more info
