### ISSUE TITLE
[VSC-Web] [Regression] Close without saving seems to cause misbehavior

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#230624] opened 2024-10-06 06:45 UTC
Introduced right by 1.94.

    |1| May interfere Untitled files counting:
    Create new file -> Type whatsoever -> Close (choose "Cancel") -> Close ("Don't Save"):
    Create new file again and note the abnormally incremented Untitled count.

    |2| Abnormal behavior when opening a local file, edit (or just try like |1| without even edit), discard change then reopen:
    The reopened file would be blank..?
    Though Undo may work to restore the file to initial state.

    The browser Dev console carped a lot "Canceled" error messages meanwhile.
    Besides, nothing unusual.

\----

Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
User Agent: Firefox 132, Chrome 124
Embedder: vscode.dev

**Comment by MasterInQuestion** [comment] 2024-10-06 06:54
For strange cause, this update also forced me to clean browser cache, to solve some peculiar bug:
    Diff infinite loading with a similar "Canceled" error message in Console.

**Comment by bpasero** [comment] 2024-10-06 11:09
I cannot reproduce using Chrome 129.x on https://vscode.dev

**Comment by bpasero** [comment] 2024-10-06 12:44
Ah, so the first issue seems to be confirmed by https://github.com/microsoft/vscode/issues/230635 and we will try to fix it asap.

**Comment by bpasero** [comment] 2024-10-06 13:05
Yes, closing as duplicate.

**Closed by bpasero** 2024-10-06 13:05 UTC
Labels: info-needed

**Comment by MasterInQuestion** [comment] 2024-10-06 15:08
Seems not VSC-Web specific...
    [ https://github.com/microsoft/vscode/issues/230635#issuecomment-2395433332](https://github.com/microsoft/vscode/issues/230635#issuecomment-2395433332)

    Undo still works for reopened files even if the "Restore Undo Stack" is disabled
    [ https://github.com/microsoft/vscode/issues/230453](https://github.com/microsoft/vscode/issues/230453)

    ----

    Period workaround:
    Close all files and restart (reload) VSC shall correct it.
