### ISSUE TITLE
Find/Replace with Regular Expression hanging the window

### ISSUE THREAD

**Issue by Brawlence** [microsoft/vscode#91216] opened 2020-02-23 01:22 UTC
Issue Type: <b>Performance Issue</b>

I was doing text replacement
<details>
<summary>by this template</summary>  

quote@Author ＜br /＞  

→

＜blockquote cite="" ＞＜span ＞quote ＜/span＞  

＜author＞Author＜/author＞  

＜/blockquote＞

</details>
using the Find/Replace tool with the following inputs:

Search field:  
```
(.)+@(.)+<br />
```
Replace field:   
```
<blockquote cite=""><span>$1</span>
    <author>$2</author>
</blockquote>
```
After the first check I noticed that I included only one sybol in the RegExp selector `(.)+`, so I typed a plus sign inside the bracket `(.+)+` (was going to remove the second plus), at which point the window become unresponsive, freezing the VSCode for several minutes. (The second window with an unrelated project was unaffected).

Please add a check for a way-too-greedy selector.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.34GB free)|
|Process Argv|C:\Users\Phil\Creations\CODE\Pathfinder|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    84	  6904	code main
    0	   255	  6292	   gpu-process
    0	    11	  6440	   electron-crash-reporter
    0	    77	  6576	   shared-process
   17	   278	  6780	   window (Drunken_in_the_Dark.html - Pathfinder - Visual Studio Code)
    0	   110	  6036	     extensionHost
    0	    96	  5444	       "C:\Users\Phil\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Phil\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=6036
    0	    45	  6952	       "C:\Users\Phil\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Phil\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=6036
    0	    13	  6560	     watcherService 
    0	   185	  7216	   window (oc_the_curators_part_3.html - Localroger-The-Curators - Visual Studio Code)
    0	    97	  7328	     extensionHost
    0	   104	  7588	       "C:\Users\Phil\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Phil\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=7328
    0	    11	  7392	     watcherService 
    2	    83	  8044	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Drunken_in_the_Dark.html - Pathfinder - Visual Studio Code)
|  Window (oc_the_curators_part_3.html - Localroger-The-Curators - Visual Studio Code)
|    Folder (Pathfinder): 21 files
|      File types: html(11) svg(3) css(2) md(1) gif(1) js(1)
|      Conf files:
|    Folder (Localroger-The-Curators): 24 files
|      File types: html(8) js(3) css(2) gitattributes(1) gitignore(1) jpg(1)
|                  md(1) json(1) txt(1) exe(1)
|      Conf files: tasks.json(1);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
copy-relative-path|ale|0.0.2
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.5.3
vscode-html-css|ecm|0.2.3
todo-tree|Gru|0.0.167
reg|ion|1.0.1
mediawiki|jas|0.0.1
cpptools|ms-|0.26.3
csharp|ms-|1.21.12
indenticator|Sir|0.6.0
vscode-make|tec|1.0.2
unity-debug|Uni|2.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-02-23 06:08
Looks related to #88539 so pinging @JacksonKearl

**Comment by IllusionMH** [comment] 2020-02-23 13:02
With `(.+)+` it looks like duplicate of #30874

**Comment by JacksonKearl** [comment] 2020-02-23 22:00
Yes this seems like a catastrophic backtracking situation. Closing as duplicate of #30874.

**Closed by JacksonKearl** 2020-02-23 22:00 UTC
