### ISSUE TITLE
"Extensions have been modified on disk" warning after upgrading to latest insiders

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#39758] opened 2017-12-06 06:55 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (bd11a1f64eb870a927f3d0e5e4628b3fa066d90c, 2017-12-06T06:07:57.990Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.0.13
color-info|bie|0.5.0
emojisense|bie|0.3.0
speech|bie|0.0.1
vscode-reveal|evi|1.0.0
python|ms-|0.8.0
wordcount|ms-|0.1.0

---

Steps to Reproduce:

1. Update from yesterday's insiders build to today's

**Bug**
<img width="453" alt="screen shot 2017-12-05 at 10 49 25 pm" src="https://user-images.githubusercontent.com/212305/33648475-e82ff408-da0e-11e7-9621-179c3d8fa97a.png">

It's possible one of the extensions could have triggered this but I'm not sure.  After restarting, I do not see this warning again. Filing this issue because I also saw this warning on a dev build today but didn't think too much of it at the time. Interested to see if anyone else hits it

**Comment by sandy081** [comment] 2017-12-06 13:49
I also saw that when I updated to latest insiders today

![image](https://user-images.githubusercontent.com/10746682/33664648-a59dc292-da94-11e7-94d7-bf436fffd47b.png)

Guessing related to extensions caching feature.

**Comment by egamma** [comment] 2017-12-06 18:28
Duplicate of #39765

**Closed** 2017-12-07 09:28 UTC
Labels: *duplicate, insiders
