### ISSUE TITLE
Bash for Windows terminals wrapping over 80 characters, terminals aren't sized correctly

### ISSUE THREAD

**Issue by Ivan-Kouznetsov** [microsoft/vscode#106668] opened 2020-08-29 21:46 UTC
- VSCode Version:
1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
- Local OS Version: Windows_NT x64 10.0.19041
- Remote OS Version: N/A
- Remote Extension/Connection Type: Not using a remote connection

Steps to Reproduce:

1. Enable Remote - WSL extension (I have version 0.44.4)
2. Set Bash for Windows as default terminal
3. Restart VS Code
4. Open the terminal and type more than 80 characters in one line 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2020-09-14 16:04
This is nothing to do with remote-wsl, it happens when it's disabled as well.

**Comment by Tyriar** [comment] 2020-09-14 16:10
I'm guessing this is related to the fact that the initial size of the terminal is 0x0 and immediately after start we send the correct dimensions:

![image](https://user-images.githubusercontent.com/2193314/93110401-1d7e3c80-f66a-11ea-8cd5-60ffe796941b.png)

**Comment by Tyriar** [comment] 2020-09-14 17:31
The fact that 0x0 is used initially followed by the actual dimensions right after is indeed the reason this doesn't work only for git bash under conpty.

The reason 0x0 is used (which falls back to 80x30) is a little more complicated. Historically we have provided the terminal container in order to get the dimensions of the terminal when we can, which may or may not have happened depending on how the terminal was created. Basically we could only get the dimensions if the terminal panel had been shown before and it was not going to be a split. But this seems to have fallen apart I think after integrating the terminal with the new "view" system.

Quick fix: Disallow `IPty.resize` to be called on Windows immediately after process creation
Proper fix: https://github.com/microsoft/vscode/issues/106672

**Comment by Tyriar** [comment] 2020-09-14 17:41
To verifier:

1. On windows 19041 (or verify in stable you can repro)
2. Set default shell to Git Bash via the Select Default Shell command
3. Restart VS Code
4. Create the first terminal 
5. Write characters and make sure it fills the viewport's width
6. Create the second terminal
7. Verify 5 again

**Comment by connor4312** [comment] 2020-10-01 19:16
I was able to reproduce this in the recent insiders using a single terminal: https://memes.peet.io/img/20-10-3d8a2c7c-818b-4921-9c84-d78cf33d217e.mp4

**Comment by alexr00** [comment] 2020-10-02 09:15
@connor4312 I repro'd the issue on stable, then tried in insiders and verified that it was fixed. 

Given that this is intended to be a quick fix, and that there's an intended thorough fix (#106672), I'm going to close this and call it verified, since it does solve the issue for me.

**Closed by alexr00** 2020-10-02 09:15 UTC
Labels: bug, integrated-terminal, verification-found, windows
