### ISSUE TITLE
TS Server fatal error:  Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by philipbjorkebro** [microsoft/vscode#116734] opened 2021-02-15 22:33 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.parsePackageName (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:39472:30)
    at ConfiguredProject.Project.enablePlugin (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:151962:24)
    at ConfiguredProject.enablePluginsWithOptions (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:152477:30)
    at ProjectService.loadConfiguredProject (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154206:25)
    at ProjectService.createAndLoadConfiguredProject (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154145:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154150:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
    at /home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155395:97
    at Object.flatMap (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
    at /home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
    at IOSession.Session.executeCommand (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
    at IOSession.Session.onMessage (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
    at Interface.<anonymous> (/home/pille/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 5.8.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.03GB free)|
|Process Argv|--crash-reporter-id 1736c620-60f7-4d95-ad02-9601c9751d97|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: BombeeSimon|
|OS|Linux x64 5.8.0-43-generic|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 1493)|
|Memory (System)|15.55GB (0.47GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by IllusionMH** [comment] 2021-02-15 22:39
/duplicate of #116219
Fix released with VS Code 1.53.2

**Closed** 2021-02-15 22:40 UTC
Labels: *duplicate
