### ISSUE TITLE
Code OSS hangs with debugger

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153303] opened 2022-06-27 12:48 UTC
Having seen this a few time lately. This is what the sample prints: [proc_sample.txt](https://github.com/microsoft/vscode/files/8992089/proc_sample.txt)

**Comment by jrieken** [comment] 2022-06-27 12:52
Another one, right after starting debug...

[Sample of Code - OSS.txt](https://github.com/microsoft/vscode/files/8992114/Sample.of.Code.-.OSS.txt)

**Comment by hediet** [comment] 2022-06-27 12:56
Thanks for reporting such issues and using the debugger!
I didn't experience any freezes lately though (Windows).

**Comment by jrieken** [comment] 2022-06-27 12:59
Worked great for the last week but now I am in a state where it 100% freezes right after startup.

**Comment by jrieken** [comment] 2022-07-08 09:55
More crashing [Sample of Code - OSS.txt](https://github.com/microsoft/vscode/files/9070948/Sample.of.Code.-.OSS.txt)

**Comment by connor4312** [comment] 2022-07-08 15:46
@deepak1556 have you have a chance to look at these?

**Comment by deepak1556** [comment] 2022-07-08 15:55
Not yet, working on some candidate issues. I will get back to this on Monday.

**Comment by deepak1556** [comment] 2022-07-14 08:23
Sample from https://github.com/microsoft/vscode/issues/153303#issue-1285757365 and https://github.com/microsoft/vscode/issues/153303#issuecomment-1167314678 share the same stack,

```
Analysis of sampling Electron (pid 50450) every 1 millisecond
Process:         Electron [50450]
Path:            /Users/USER/*/Code - OSS.app/Contents/MacOS/Electron
Load Address:    0x100eb8000
Identifier:      com.visualstudio.code.oss
Version:         1.69.0 (1.69.0)
Code Type:       ARM64
Platform:        macOS
Parent Process:  Code - Insiders Helper [44624]

Date/Time:       2022-06-27 14:46:37.872 +0200
Launch Time:     2022-06-27 14:35:32.961 +0200
OS Version:      macOS 12.4 (21F79)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         81.0M
Physical footprint (peak):  101.8M
----

Call graph:
    2344 Thread_11628135   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2344 start  (in dyld) + 520  [0x100fd908c]
    +   2344 ElectronMain (in Electron Framework) (electron_library_main.mm:0) [0x108a7d688]
    +     2344 content::ContentMain(content::ContentMainParams) (in Electron Framework) (content_main.cc:433) [0x108cf3684]
    +       2344 content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) (in Electron Framework) (content_main.cc:405) [0x108cf31b8]
    +         2344 content::ContentMainRunnerImpl::Run() (in Electron Framework) (content_main_runner_impl.cc:0) [0x108cf46b0]
    +           2344 content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) (in Electron Framework) (content_main_runner_impl.cc:1172) [0x108cf4b14]
    +             2344 content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) (in Electron Framework) (content_main_runner_impl.cc:639) [0x108cf3af4]
    +               2344 content::BrowserMain(content::MainFunctionParams) (in Electron Framework) (browser_main.cc:30) [0x10a6120e0]
    +                 2344 content::BrowserMainRunnerImpl::Run() (in Electron Framework) (browser_main_runner_impl.cc:156) [0x10a615bd0]
    +                   2344 content::BrowserMainLoop::RunMainMessageLoop() (in Electron Framework) (browser_main_loop.cc:1058) [0x10a614420]
    +                     2344 base::RunLoop::Run(base::Location const&) (in Electron Framework) (run_loop.cc:143) [0x10b1caa80]
    +                       2344 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) (in Electron Framework) (thread_controller_with_message_pump_impl.cc:500) [0x10b1faeec]
    +                         2344 base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_mac.mm:164) [0x10b232e64]
    +                           2344 base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_mac.mm:759) [0x10b234268]
    +                             2344 -[NSApplication run]  (in AppKit) + 596  [0x19a0f2250]
    +                               2344 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]  (in AppKit) + 1328  [0x19a100084]
    +                                 2344 _DPSNextEvent  (in AppKit) + 860  [0x19a10178c]
    +                                   2344 _BlockUntilNextEventMatchingListInModeWithFilter  (in HIToolbox) + 72  [0x1a01d2e68]
    +                                     2344 ReceiveNextEventCommon  (in HIToolbox) + 564  [0x1a01d30b4]
    +                                       2344 RunCurrentEventLoopInMode  (in HIToolbox) + 292  [0x1a01d3338]
    +                                         2344 CFRunLoopRunSpecific  (in CoreFoundation) + 600  [0x19759ab24]
    +                                           2344 __CFRunLoopRun  (in CoreFoundation) + 828  [0x19759b600]
    +                                             2344 __CFRunLoopDoSources0  (in CoreFoundation) + 268  [0x19759cc80]
    +                                               2344 __CFRunLoopDoSource0  (in CoreFoundation) + 208  [0x19759cf80]
    +                                                 2344 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__  (in CoreFoundation) + 28  [0x19759d034]
    +                                                   2344 base::MessagePumpCFRunLoopBase::RunWorkSource(void*) (in Electron Framework) (message_pump_mac.mm:377) [0x10b233374]
    +                                                     2344 base::mac::CallWithEHFrame(void () block_pointer) (in Electron Framework) + 16 [0x108a36670]
    +                                                       2344 invocation function for block in base::MessagePumpCFRunLoopBase::RunWorkSource(void*) (in Electron Framework) (message_pump_mac.mm:375) [0x10b233adc]
    +                                                         2344 non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() (in Electron Framework) (thread_controller_with_message_pump_impl.cc:0) [0x10b1fa630]
    +                                                           2344 base::TaskAnnotator::RunTaskImpl(base::PendingTask&) (in Electron Framework) (task_annotator.cc:135) [0x10b1e0ca0]
    +                                                             2344 base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message), scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>, mojo::Message>, void ()>::RunOnce(base::internal::BindStateBase*) (in Electron Framework) (bind_internal.h:748) [0x10b6ad600]
    +                                                               2344 mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*) (in Electron Framework) (interface_endpoint_client.cc:658) [0x10b4c2e58]
    +                                                                 2344 mojo::MessageDispatcher::Accept(mojo::Message*) (in Electron Framework) (message_dispatcher.cc:48) [0x10b4c56b0]
    +                                                                   2344 mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept(mojo::Message*) (in Electron Framework) (interface_endpoint_client.cc:332) [0x10b4c1b3c]
    +                                                                     2344 blink::mojom::LocalFrameHostStubDispatch::Accept(blink::mojom::LocalFrameHost*, mojo::Message*) (in Electron Framework) + 2616 [0x1095f91a8]
    +                                                                       2344 content::RenderFrameHostImpl::DidAddMessageToConsole(blink::mojom::ConsoleMessageLevel, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&, unsigned int, absl::optional<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > > const&, absl::optional<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > > const&) (in Electron Framework) + 232 [0x10a8db234]
    +                                                                         2344 content::LogConsoleMessage(blink::mojom::ConsoleMessageLevel, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&, int, bool, bool, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&) (in Electron Framework) (log_console_message.cc:41) [0x10a7c48e4]
    +                                                                           2344 logging::LogMessage::~LogMessage() (in Electron Framework) (logging.cc:840) [0x10b1a8394]
    +                                                                             2344 write  (in libsystem_kernel.dylib) + 8  [0x1974966f8]
```

**Comment by deepak1556** [comment] 2022-07-14 08:26
Basically main process is blocked when attempting to write to `stderr` https://source.chromium.org/chromium/chromium/src/+/main:base/logging.cc;l=828-841, a workaround would be to start the application with `--disable-features="LogJsConsoleMessages"`

@connor4312 I thought this particular issue was addressed in js-debug previously.

**Comment by deepak1556** [comment] 2022-07-14 09:20
https://github.com/microsoft/vscode/issues/153303#issuecomment-1178791363 has lot of stacks from JIT compiled code which cannot be symbolicated, but most of the time is spent where the main process is trying to process `uncaughtexception`. We should check the logs to know more about the exception.
[Symbolicated_Sample.txt](https://github.com/microsoft/vscode/files/9110471/Symbolicated_Sample.txt)

**Comment by connor4312** [comment] 2022-07-14 16:18
Yes, we do consume stderr just like we do stdout 

https://github.com/microsoft/vscode-js-debug/blob/812a259f1f09a5c6527f0940f81e5efb6f1eb0da/src/targets/browser/launcher.ts#L127-L128

@jrieken can you confirm that you were on js-debug-nightly when you observed that issue?

**Comment by jrieken** [comment] 2022-07-15 06:01
Sorry, I am not 😶‍🌫️  I am using code insiders and I am assuming that it includes latest and greatest js-debug (for the sake of easy feedback). I also wonder why it is still two extensions - aren't we doing stable/insiders variants of single extensions these days?

**Comment by connor4312** [comment] 2022-07-15 15:56
We are, I just have not had the chance to move js-debug over yet 😬  it's on my plate for a debt week, but those have been consumed by CLI stuff recently.

I would encourage you to use nightly in the meantime though, as that's the fastest way to get all the fixes 🙂

**Comment by jrieken** [comment] 2022-07-15 16:19
> I would encourage you to use nightly in the meantime though, 

Totally!

**Comment by connor4312** [comment] 2022-12-05 20:12
I think this was caused by not having the fix that was only on nightly at that point.

**Closed by connor4312** 2022-12-05 20:12 UTC
Labels: papercut :drop_of_blood:
