### ISSUE TITLE
Views moved to panel do not open on reload

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#89567] opened 2020-01-28 22:06 UTC
testing #89384

Have search in panel, and have it be the active panel entry. Reload. Now some other panel item is active (for me, Terminal). Similar happens with Outline/etc. I think persisting the active panel is important.

**Comment by sandy081** [comment] 2020-01-30 09:50
I also see this with other custom views. Marking this as regression because it used to work for Search view.

**Closed** 2020-01-30 16:05 UTC
Labels: bug, regression, workbench-views

**Comment by sbatten** [comment] 2020-01-30 16:07
@sandy081 added the behavior that viewlet has to panel where its `openViewlet` api is async to wait for extension load. I made it a separate api to limit impact for endgame, but I will make a debt item to remove the non-async version after release.

**Comment by sandy081** [comment] 2020-01-30 17:28
Makes sense
