### ISSUE TITLE
Broken MacOS native tabs mode in the new Vs Code version

### ISSUE THREAD

**Issue by Ivandotweb** [microsoft/vscode#126130] opened 2021-06-12 13:31 UTC
- VS Code Version: 1.57
- OS Version: MacOS 11.4 (Big Sur)

When i open projects in native tabs mode vs code behaves like this:

<img width="1203" alt="Снимок экрана 2021-06-12 в 16 22 20" src="https://user-images.githubusercontent.com/40368223/121777372-608a2380-cb9a-11eb-80d0-c1ab0bac5a17.png">

<img width="573" alt="Снимок экрана 2021-06-12 в 16 20 32" src="https://user-images.githubusercontent.com/40368223/121777345-3df80a80-cb9a-11eb-9a1a-5ebe81f5e281.png">

<img width="1440" alt="Снимок экрана 2021-06-12 в 16 20 16" src="https://user-images.githubusercontent.com/40368223/121777338-33d60c00-cb9a-11eb-8498-c45e6cddae34.png">

So, one of the workspases is just empty black window
And in place of the tabs, now there is an empty space

All extensions are disabled
This bug showed after new release update

**Comment by bpasero** [comment] 2021-06-12 17:07
Duplicate of https://github.com/microsoft/vscode/issues/126025

**Comment by btechn01** [comment] 2021-06-15 09:38
+

**Comment by deepak1556** [comment] 2021-06-21 04:28
Merging to https://github.com/microsoft/vscode/issues/126016

**Closed by deepak1556** 2021-06-21 04:28 UTC
