### ISSUE TITLE
Unable to get checkbox changes in a TreeView when using 'manageCheckboxStateManually'

### ISSUE THREAD

**Issue by gaelwilson** [microsoft/vscode#234087] opened 2024-11-18 10:38 UTC
Type: <b>Bug</b>

This simple test extension https://github.com/gaelwilson/treeviewdemo shows creation of a treeview with 'manageCheckboxStateManually' set to true. 
The onDidChangeCheckboxState handler always gets an empty list when an item is checked/unchecked so there is no indication of which item has changed state. 
If that is by design when the option is set to true, what is the mechanism for determining what has changed? The example also tries checking the items but the checkboxState property does not change.
Thanks in advance. 

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor                 (8 x 2445)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.58GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id ac11cafa-59bc-46e3-b2c7-7122f6be302f|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31181874

```

</details>

**Comment by alexr00** [comment] 2024-11-19 09:55
Duplicate of https://github.com/microsoft/vscode/issues/233304#issuecomment-2477495155

**Closed** 2024-11-19 09:55 UTC
Labels: *duplicate
