### ISSUE TITLE
How to insert time in the Snippets

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#17054] opened 2016-12-12 01:36 UTC
I want to insert current time in my Snippets, like this:
<img width="325" alt="2016-12-12 9 35 42" src="https://cloud.githubusercontent.com/assets/18381153/21085545/6d0a21ac-c04e-11e6-8628-526ac83a4dc3.png">

**Comment by jrieken** [comment] 2017-06-02 10:42
I am closing this as dupe of #10561 which about allowing to execute functions during snippet expansion. With that an extension can insert the current date/time. In addition an extension can already today be a completion item provider that proposed the date/time

**Closed by jrieken** 2017-06-02 10:42 UTC
Labels: feature-request, snippets
