### ISSUE TITLE
VS Code is hard to use on a shared user account and multiple RDP sessions

### ISSUE THREAD

**Issue by cori** [Microsoft/vscode#15674] opened 2016-11-17 21:11 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Steps to Reproduce:

1. log into an RDP session with a shared user account. 

1. open a file in code.

1. log in to another session as the same user

1. try to open another file

1. no code windows appears in the current session

1. a window with the 2nd file opens in the 1st rdp session

**Comment by yoisel** [comment] 2016-12-05 11:51
The exact same thing happens on ubuntu linux with xrdp by the way.

**Comment by bpasero** [comment] 2017-09-28 09:32
@joaomoreno didn't you fix this with your named pipe fix on Windows?

**Comment by bpasero** [comment] 2017-09-28 11:47
@cori 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment] 2017-11-15 16:12
Closing due to needs more info.

**Closed by bpasero** 2017-11-15 16:12 UTC
Labels: bug, workbench
