### ISSUE TITLE
Warn for unknown configuration settings

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#115957] opened 2021-02-06 05:33 UTC
Currently, unknown configuration settings in `settings.json` are greyed out, it's hard to find them if I don't read `settings.json` line by line. It would be better if they are warned and shown in the `problems` panel, this way, I could quickly find them.

![image](https://user-images.githubusercontent.com/28700378/107110038-9ed7a500-687f-11eb-9baa-98b9a872055f.png)

**Comment by yume-chan** [comment] 2021-02-07 02:57
They used to, but got changed in #33931

I guess there is no way to differentiate between "settings from disabled extensions" and "deprecated settings from enabled extensions"

**Comment by usernamehw** [comment] 2021-02-07 07:25
It would be a great feature to be able to see all the hints in one place. Problems panel is missing only hint level diagnostics and they would be just disabled by default

![Screenshot (431)](https://user-images.githubusercontent.com/9638156/107139692-43182500-692e-11eb-9d83-e29720b4e7a4.png)

**Comment by yume-chan** [comment] 2021-02-07 07:47
@usernamehw Same problem, Code doesn't recognize configurations from disabled extensions, when you have several extensions disabled there can be tens or even hundreds of "hint" level errors.

**Comment by usernamehw** [comment] 2021-02-07 08:56
Well, I guess we are talking about different features. 

1. Acknowledge disabled extensions and do not show `Unknown` for such extensions
2. Ability to see all hint level diagnostics (disabled by default)

Both would be improvements over the current system.

---

There's a way to make them warnings, though. Extension author can add `"deprecationMessage"` or `"markdownDeprecationMessage"` and the setting will be of warning level.

**Comment by yume-chan** [comment] 2021-02-07 09:30
My bad, I thought it might be a purely invalid setting ID, but in fact "esbenp.prettier-vscode" extension has removed this setting several versions ago.

> 2. Ability to see all hint level diagnostics (disabled by default)

I mean these "hint"s are not that useful today, you may get many of them and all of them says "unknown configuration settings", it doesn't matter whether they are scattered or grouped.

It still requires "1. Acknowledge disabled extensions and do not show Unknown for such extensions" to function porperly. But with 1. implementated, Code can confidently tell you it's an "Invalid" setting, there is no such thing as "Unknown" settings anymore.

**Comment by usernamehw** [comment] 2021-02-07 10:40
There are also hidden settings, such as `editor.disableMonospaceOptimizations` or `editor.scrollbar.verticalScrollbarSize` and the issue about showing different warning for them was closed with the solution of using hint diagnostics: https://github.com/microsoft/vscode/issues/40070#issuecomment-513953921 

> I mean these "hint"s are not that useful today

They are useful, and often have a quick fix. Disabled by default and with the ability to show them on demand (filter icon) and the ability to filter them (filter input already there) they would be useful.

**Comment by sandy081** [comment] 2021-02-09 18:14
It seems there are too many things discussed in one issue which actually deviating or distracting the issue. So I would focus about the issue reported in the description. Since it is designed to represent unconfigured settings like this I am closing this as designed.

I would request to file separate issue for each of the requirements you are asking for, so that it will be easy to see if ti is already reported or not and track it

**Closed** 2021-02-09 18:27 UTC
Labels: *as-designed
