### ISSUE TITLE
不能识别出jsx的react文件，其中jsx格式的语言显示不正确。javascript react才是正确的，需要手动选择

### ISSUE THREAD

**Issue by txiaocao** [Microsoft/vscode#11746] opened 2016-09-09 07:36 UTC
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.10240

"files.associations": {
        "*.jsx": "react"
    },
Steps to Reproduce:

1.打开一个jsx文件
2.其格式显示为jsx，但理想情况应该显示成 javascript react
3.可是配置files.associations为react却显示为纯文本

**Comment by ramya-rao-a** [comment] 2016-09-09 08:35
@txiaocao Can you please update the issue title and steps to reproduce in english?

**Comment by glen-84** [comment] 2016-09-11 16:34
Google Translate:

**Title:**

Can not identify jsx too react file format in which language jsx displayed incorrectly. javascript react is correct, you need to manually select

**Steps to Reproduce:**

1. Open a js file
2. The format appears as jsx, but ideally it should be displayed as javascript react
3. Configure files.associations to react, but it appears as plain text

---

The first step should probably read `jsx` and not `js`.

BTW, maybe the team should mention English-only issues in the contribution guidelines?

**Comment by ramya-rao-a** [comment] 2016-09-11 20:24
@glen-84 May be we should. A lot gets lost during translation too. And it does make the job of the inbox tracker easier when we need to sort through sound 30 to 40 new issues every day :)

**Comment by ramya-rao-a** [comment] 2016-09-11 20:29
@txiaocao Without any file associations, when I open a jsx file, the language mode in the bottom right corner shows "Javascript React"

Are you working on a js file or a jsx file?

Is this a problem in the new update or did you have the same issue in 1.4.0 as well?

**Comment by bpasero** [comment] 2016-09-13 13:18
I am closing this due to insufficient information of the issue.

**Closed by bpasero** 2016-09-13 13:18 UTC
Labels: needs more info

**Comment by ramya-rao-a** [comment] 2016-09-13 15:30
@txiaocao Also if you want to associate a file for react you should use "javascriptreact" not "react"
```
"files.associations": {
        "*.jsx":"javascriptreact"
    }
```

**Comment by txiaocao** [comment] 2016-09-19 05:50
Thanks! use "**javascriptreact**" is right...
I try "react","jsx","Javascript React","babel","javascript(babel)" is wrong...
if display is  real field,It's good
