### ISSUE TITLE
Custom editor reopens files with dirty icon when restarting VS code

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#99326] opened 2020-06-04 00:49 UTC
- VSCode Version: 1.46.0 insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Build the pawDraw [sample ](https://github.com/microsoft/vscode-extension-samples/tree/master/custom-editor-sample)
1. Run 
1. Edit a pawdraw file
1. Save it.
1. Reload VS code

Expected: pawdraw file opens
Actual: vs code issues an error saying it can't load the backup file. 

In the API I can see the ```openCustomDocument``` parameters containing a backup id in the context when it's not expected.

If instead you don't reload VS code, but just reopen the edited pawdraw file, it works fine.

Does this issue occur when all extensions are disabled?: N/A

**Comment by rchiodo** [comment] 2020-06-04 15:49
For the python extension we're not loading the backup file in this case (we don't fail to load if the file isn't there), but the tab for the editor looks as if an edit has occurred.

**Comment by mjbvz** [comment] 2020-06-04 23:43
Duplicate of #99293 I believe

**Closed by mjbvz** 2020-06-04 23:43 UTC
