### ISSUE TITLE
Markdown Preview does not regain focus on app activation

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/vscode#50257] opened 2018-05-22 05:31 UTC
Issue Type: <b>Bug</b>

1) Open a long Markdown preview window for my Markdown file.
2) Scroll the markdown file using the arrow keys or page up/down after focusing the preview panel.
3) Use Alt-Tab to navigate to another app (or click on another app, etc...)
4) Re-activate VS Code (through Alt-Tab or clicking on taskbar)

Actual: Can no longer scroll markdown preview with keyboard until refocus preview window with mouse again.

Expect: Markdown preview to maintain keyboard focus on app reactivation so I can continue scrolling from where I left off when I come back from a context switch.  (Other apps like Edge maintain this type of focus.)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T17:28:16.777Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by mjbvz** [comment] 2018-05-22 17:46
Duplicate of #49998

Fixed in insiders

**Closed by mjbvz** 2018-05-22 17:46 UTC
Labels: markdown
