### ISSUE TITLE
100% core CPU usage withou apparent reason

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#68963] opened 2019-02-19 08:59 UTC
Issue Type: <b>Bug</b>

I do not know exactly how to reproduce this, but several times a day, after  while of running code, my coputer starts spinning the cpu fan and code is the culprit.

I believe this has been happening since the last update.

![image](https://user-images.githubusercontent.com/821272/53002448-01ce9800-342d-11e9-8eb6-accb53e10391.png)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (1.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
vscode-django|bat|0.19.0
vscode-bad-code-highlighter|bha|0.1.6
unique-lines|bib|1.0.0
featurehighlight|Blo|1.7.0
bracket-pair-colorizer|Coe|1.0.61
jupyter|don|1.1.4
find-related|eam|0.8.0
sort-lines-by-selection|ear|0.0.3
php-intellisense|fel|2.3.10
gc-excelviewer|Gra|2.1.29
dupchecker|jia|0.0.9
vscode-random|jre|1.5.0
MagicPython|mag|1.1.0
id-generator|mat|1.0.0
xml-format|mik|1.0.1
vscode-duplicate|mrm|1.2.1
oracle-plsql|myc|1.0.3
indent-rainbow|ode|7.2.4
selectline-statusbar|tom|0.0.2
vscodeintellicode|Vis|1.1.3
gitblame|wad|2.6.3
twig|wha|1.0.2
jinja|who|0.0.8
cursor-align|yo1|1.0.4

</details>

**Comment by bpasero** [comment] 2019-02-19 09:10
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by PunchyRascal** [comment] 2019-02-20 09:04
```
Version:          Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  15.87GB (2.24GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       64   21200  code main
    0       55    2648     shared-process
   26      262   13000     window (foo.sqlt Z:\foo.sqlt - verotel - Visual Studio Code)
    0        9   15924       electron-crash-reporter
   14     2427   17184       extensionHost
    0        9   16304         c:/users/x/wamp/php/php.exe c:\Users\x\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:52772 --memory-limit=4095M
    0        4   12164           console-window-host (Windows internal process)
    0       12   20080       watcherService
    0        4    1056         console-window-host (Windows internal process)
    0      110   15896     gpu-process

Workspace Stats:
|  Window (Visual Studio Code)
|    Folder (verotel): 10024 files
|      File types: t(2167) pm(1876) tt(688) js(670) sql(594) yml(385) gif(329)
|                  png(328) py(306) feature(260)
|      Conf files: makefile(36) settings.json(1) package.json(1)

```

**Comment by bpasero** [comment] 2019-02-20 09:21
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by PunchyRascal** [comment] 2019-02-20 11:50
Without extensions:
```
Version:          Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  15.87GB (4.82GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --disable-extensions
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    9       76   10892  code main
    0       92    3524     gpu-process
   12      223    5844     window (post_to_mundus Z:\verotel\util\mundus\post_to_mundus - verotel - Visual Studio Code)
    0       12    2016       electron-crash-reporter
    0       35   10572       searchService
    0       11   12856       watcherService
    0        8    6560         console-window-host (Windows internal process)
    0       56   17312       extensionHost
    0       67   20364     shared-process

```

**Comment by PunchyRascal** [comment] 2019-02-20 11:51
Without extensions:
```
Version:          Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  15.87GB (4.82GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --disable-extensions
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    9       76   10892  code main
    0       92    3524     gpu-process
   12      223    5844     window (xxx - Visual Studio Code)
    0       12    2016       electron-crash-reporter
    0       35   10572       searchService
    0       11   12856       watcherService
    0        8    6560         console-window-host (Windows internal process)
    0       56   17312       extensionHost
    0       67   20364     shared-process

```

**Comment by bpasero** [comment] 2019-02-20 11:53
@PunchyRascal do you still see 100% usage then?

**Comment by PunchyRascal** [comment] 2019-02-20 11:55
I suppose it only hogs one core, thsi is what I see:

![image](https://user-images.githubusercontent.com/821272/53090110-ad9be480-350e-11e9-8eb5-9919e1b79207.png)

**Comment by bpasero** [comment] 2019-02-20 13:02
@PunchyRascal and that is constant, never going down?

**Comment by PunchyRascal** [comment] 2019-02-20 13:08
Nope, it kept running for at least 20 minutes now and still fuming until I turned it off as I didn't care for the fan noise.

**Comment by bpasero** [comment] 2019-02-20 14:28
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by rtxg** [comment] 2019-02-21 03:16
I've been experiencing the same issue, right down to waking from hibernation triggering it every time. CPU usage in the instance below is around 27%, but I have seen it up around 50% previously. Closing and relaunching vscode reduces the usage back to normal levels for a while. Will give one of the suggested insider builds a try.

`
Version:          Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS Version:       Windows_NT x64 10.0.17763
CPUs:             Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)
Memory (System):  31.86GB (19.53GB free)
VM:               29%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    6       83   17136  code main
   12      247   15972     window (input_number.yaml - docker - Visual Studio Code)
    0      194    9984       extensionHost
    0       51   11444         electron_node server.js
    0       17   16488         C:\python3\python3.exe completion.py
    0       11   19708           console-window-host (Windows internal process)
    0       16   22056           C:\python3\python3.exe lib\python\jedi\evaluate\compiled\subprocess\__main__.py lib\python
    0       11   16540             console-window-host (Windows internal process)
    2       41   18316         c:\Users\rt\.vscode\extensions\ms-vscode.cpptools-0.21.0\bin\Microsoft.VSCode.CPP.Extension.exe
    0       11   16748           console-window-host (Windows internal process)
    0       33   21512         electron_node server.js
    0       13   21068       watcherService
    0       11   21740         console-window-host (Windows internal process)
    0      520   19468     gpu-process
    0       71   21472     shared-process

Workspace Stats:
|  Window (input_number.yaml - docker - Visual Studio Code)
`

**Comment by bpasero** [comment] 2019-02-21 07:13
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by rtxg** [comment] 2019-02-22 22:34
Have installed an insider build and waking from hibernate no longer seems to trigger the high CPU usage. Will keep an eye on the CPU usage under normal use, but so far it seems to be an improvement.

**Comment by bpasero** [comment] 2019-02-23 07:14
Ok good, we will release this in about 1 week.

**Closed by bpasero** 2019-02-23 07:14 UTC
Labels: needs more info

**Comment by PunchyRascal** [comment] 2019-02-26 09:50
It is happening to me again with the insiders version, too. 

```
Version:          Code - Insiders 1.32.0-insider (b64026839eed3dd03a6d6fe0ba3910255490c279, 2019-02-22T08:37:25.309Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  15.87GB (5.57GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    8       48     240  code-insiders main
    0       30    5156     gpu-process
   15      242   12196     window (jobs.data - verotel - Visual Studio Code - Insiders)
    0        4   11600       watcherService
    0        1    5688         console-window-host (Windows internal process)
    0       35   20644       searchService
    0       17   21272       extensionHost
    0        4   11224         "C:\Users\frantisek\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\frantisek\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=21272
    0       35   12820     shared-process
    0        1   19080     C:\Users\FRANTI~1\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-393b48d4a5de85b6fa1d2ad0a59588d6715e12ea.exe /verysilent /update="C:\Users\FRANTI~1\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-393b48d4a5de85b6fa1d2ad0a59588d6715e12ea.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0        2   17812       "C:\Users\FRANTI~1\AppData\Local\Temp\is-ERPCF.tmp\CodeSetup-insider-393b48d4a5de85b6fa1d2ad0a59588d6715e12ea.tmp" /SL5="$7210CA,49272025,159744,C:\Users\FRANTI~1\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-393b48d4a5de85b6fa1d2ad0a59588d6715e12ea.exe" /verysilent /update="C:\Users\FRANTI~1\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-393b48d4a5de85b6fa1d2ad0a59588d6715e12ea.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon

```

**Comment by rtxg** [comment] 2019-02-28 21:18
> It is happening to me again with the insiders version, too.

Same here. Seemed to be fine for a day or two, but now it's showing the same symptoms as the regular version.

**Comment by PunchyRascal** [comment] 2019-03-04 09:55
Well it seems this was closed prematurely.
