### ISSUE TITLE
Initializing JS/TS language features spinning constantly

### ISSUE THREAD

**Issue by nad182** [microsoft/vscode#103740] opened 2020-08-01 04:25 UTC
Issue Type: <b>Bug</b>
**The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.**
I had this issue before, it was temporarily resolved by installing **Insiders** version. When this issue happens (and at some other times) intellisense stops working, I'm not able to "dive into/navigate to" methods/components with `cmd+click`, and in `Problems` tab it can show some syntax error that I already fixed, but, I guess, VS Code freezes, so the tab doesn't update.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3697)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 9, 7|
|Memory (System)|32.00GB (2.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
vscode-docker|ms-|1.4.1
debugger-for-chrome|msj|4.12.9
mdx|sil|0.1.0
vscode-icons|vsc|10.2.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-08-01 05:28
Disable each of your extensions in turn until you find which one is crashing the EH process.

**Comment by mjbvz** [comment] 2020-08-03 20:07
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Tielem** [comment] 2020-08-04 14:04
I am running into this issue as well.

```
Version: 1.48.0-insider (user setup)
Commit: 459610f3ef11b956968afadff704bad3bc1a0de2
Date: 2020-08-04T12:40:10.231Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

I have 1 extension enabled, Remote - Containers (outside of the container, none inside)
I am opening a project in a container on a Docker backend with the default Node.js Docker image (mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14)

The "Initializing JS/TS language features" status shows in the bottom bar and doesn't go away. Language server features are not working.

The project dependencies are installed, so tsc is available. I can build the project in terminal.

I updated vscode today and this is the first project I try to run in a remote container. If desired, I can check whether the project works without the remote container, but obviously the goal is to get it working in it.

Any other information I can provide you?

**Comment by mjbvz** [comment] 2020-08-06 21:01
@Tielem  Can you please open a new issue. It looks like @nad182 isn't using remote

**Comment by nad182** [comment] 2020-08-06 21:30
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

@mjbvz , I don't see this error message with the insiders build, even with extensions enabled. I do feel like the memory (ram) is leaking somehow. Because when I periodically check activity monitor, the "used memory" increases by itself over time, meaning I leave VS Code open and stop working for several hours, and when I come back the amount of memory used is higher than it was before I stopped working.

**Comment by mjbvz** [comment] 2020-08-06 21:32
Thanks for testing. closing this as not reproducible

If you have steps that can reproduce the increasing memory usage, please file a new issue and we will take a look

**Closed by mjbvz** 2020-08-06 21:32 UTC
Labels: needs more info

**Comment by nad182** [comment] 2020-08-06 21:34
> Thanks for testing. Closing this as not reproducible
> 
> If you have steps that can reproduce the increasing memory usage, please file a new issue and we will take a look

Does it mean I have to use the insider's build from now on?

**Comment by mjbvz** [comment] 2020-08-06 21:35
The insiders build tracks the next VS Code release, which would be 1.48 currently

**Comment by mihrich** [comment] 2020-08-20 09:24
I don't know why, but on Aug 19, 2020 I ran into this problem. I had a problem with the **"Import cost"** extension
