### ISSUE TITLE
Add predictable order and state awareness to NPM Scripts Tab

### ISSUE THREAD

**Issue by jpSimkins** [microsoft/vscode#109501] opened 2020-10-27 15:47 UTC
When dealing with projects that have many `package.json` files, every time you make a save to one, this regenerates the NPM Scripts tab. The issue with this is that the order of the scripts is apparently random. Just when I get the scripts tab in the state I like for current development, it is all lost the second I save any changes to a `package.json` file.

Dealing with a mono repo with numerous packages, this actually can take a bit of time to resolve, not to mention the increased risk of messing something up since it rearranges your scripts order. I cannot count how many times I forgot what I needed to run because it took me a few mins to fix the scripts tab...

I would prefer an alphabetical order as this would also keep packages and other workspaces organized in a clear, predictable manner. Also, state awareness of what is minimized and what is not would be very beneficial. When adding a new script to a project I lose the current order and they all are open again. Having over 50 `package.json` files... this is becoming an issue.

**Comment by alexr00** [comment] 2020-10-27 15:52
Duplicate of https://github.com/microsoft/vscode/issues/92773

**Closed by alexr00** 2020-10-27 15:52 UTC
