### ISSUE TITLE
Cannot save credentials on KDE Plasma

### ISSUE THREAD

**Issue by olegoid** [microsoft/vscode#117425] opened 2021-02-23 15:53 UTC
Issue Type: *Bug*

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS Version: Linux x64 5.10.15-1-MANJARO snap

When trying to login on KDE Plasma I get an error message when VSCode tries to save my credentials (see screenshot below).
Ideally, VSCode would use KWallet on KDE to save credentials. I know I could install gnome-keyring, but seeing as I'm not using Gnome, I'd prefer not to.

Steps to Reproduce:

1. Click the button to login in VSCode
2. After being directed to the GitHub auth page, authorize the application
3. Get redirected to VSCode again and confirm
4. The message shows up

Translated: "Writing the credentials into the keyring failed with the error ..."
https://user-images.githubusercontent.com/20151081/108825442-4dd7e880-75c3-11eb-9b4c-ff3be326f706.png

The original issue in LS repo:
https://github.com/MicrosoftDocs/live-share/issues/4129

**Comment by RMacfarlane** [comment] 2021-02-23 16:01
Duplicate of https://github.com/microsoft/vscode/issues/104319 and https://github.com/atom/node-keytar/issues/74

**Closed by RMacfarlane** 2021-02-23 16:01 UTC
