### ISSUE TITLE
Add ability to create custom toolbars for beginners

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#69567] opened 2019-02-28 00:50 UTC
Currently the VSC UI can be very daunting and complicated for beginners to Programming.
I believe this is where the [Mu editor](https://codewith.mu/) wins for Python Programming.

It would be great if we could have a similar UI in VSC, or one that is customizable. I believe it will help in the education sector as well (not that VSC isn't already popular in the education sector).

<img width="1271" alt="screen shot 2019-02-27 at 9 56 12 am" src="https://user-images.githubusercontent.com/1948812/53511878-3fa76e00-3a76-11e9-932d-28625664f26e.png">

**Comment by usernamehw** [comment] 2019-02-28 01:32
I believe this is a duplicate of #41309.

Shameless plug (helps with less useful commands / temporary bindings):

[Run Commands View](https://marketplace.visualstudio.com/items?itemName=usernamehw.run-commands-view)

![screenshot 80](https://user-images.githubusercontent.com/9638156/53534750-391a0480-3b11-11e9-88b3-5b56b888bf43.png)

**Closed** 2019-02-28 17:27 UTC
Labels: *duplicate
