### ISSUE TITLE
Corrupted errors in TypeScript files

### ISSUE THREAD

**Issue by tills13** [Microsoft/vscode#35848] opened 2017-10-08 22:20 UTC
- VSCode Version: 1.17
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Create a `.ts/x` file

<img width="747" alt="screen shot 2017-10-08 at 2 49 58 pm" src="https://user-images.githubusercontent.com/1269421/31321294-9880ed26-ac38-11e7-8ad2-ac678342ded9.png">

I can't figure out how to capture the popups without them closing - but, In the above example above: 

- the error on `import` is 

```
[ts]
Cannot find name 'import
'.
```

(note the newline)

- the errors on line 18 are 

```[ts] Cannot find name 'con '.```
and
```[ts] Cannot find name 'icon '.```

etc...

If I add lines above, the errors stay in place (character count wise). i.e. if I were to add `let x = 1` after `const mClassName...` the errors would offset 9 characters (flowing up lines if necessary).

Reproduces without extensions: Yes

**Comment by tills13** [comment] 2017-10-09 19:42
I disagree with the "New Release" label - I've had this happen to me on a couple versions of VSCode over the last couple months.

Also, further information - I've had this happen on all three major platforms (Windows 10, Ubuntu 16.04, and macOS Sierra).

**Comment by mjbvz** [comment] 2017-10-11 23:20
I've seen similar problems. The root cause for me seemed to be https://github.com/Microsoft/TypeScript/issues/16540

@tills13 If you're able to reliably reproduce this, can you please try installing `typescript@next` in your workspace and [enabling it](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) to see if the problem has been resolved upstream

**Comment by tills13** [comment] 2017-10-12 23:50
I played around with `TS 2.6.0-dev.20171012` a little bit today and it seems to have fixed it. I will keep my eye on it over the next couple days and post here if I run into anything (or if I don't)

**Comment by mjbvz** [comment] 2017-10-25 20:48
Closing this as one of the possible root causes was addressed by TS 2.6. Please let me know if you start seeing this issue again

**Closed by mjbvz** 2017-10-25 20:48 UTC
Labels: needs more info, typescript
