### ISSUE TITLE
Add Rename to filename tab context menu

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#40782] opened 2017-12-24 14:31 UTC
- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3302.0 Safari/537.36

It would be really helpful to add Rename to the tab content menu.  You want this behavior because -

1. You don't want to disturb the left stuff like search.
2. Navigating on the left requires multiple clicks

A keyboard shortcut would even be better!

![image](https://user-images.githubusercontent.com/2301847/34327207-d2a4a568-e87b-11e7-98e1-48cdefdad6c6.png)

![image](https://user-images.githubusercontent.com/2301847/34327214-02c1e81e-e87c-11e7-9e8c-24a4746181b3.png)

![image](https://user-images.githubusercontent.com/2301847/34327233-404e9240-e87c-11e7-9346-baefbd79b124.png)

**Comment by usernamehw** [comment] 2017-12-24 15:32
Duplicate of https://github.com/Microsoft/vscode/issues/21919

**Comment by joshunger** [comment] 2017-12-24 15:35
Dang it I swear I searched thanks @usernamehw

**Comment by joshunger** [comment] 2017-12-24 15:53
How do you determine what features to bring into vscode? At this point three different people have logged this issue (including myself 😄 ) and I'm wondering it would be more favorable and a better user experience if this is moved into vscode. Just a guess, but since Atom and WebStorm include this out of the box then users are probably expecting the same thing in vscode.

**Comment by usernamehw** [comment] 2017-12-24 17:52
@joshunger, I do not determine anything.

**Closed** 2017-12-27 17:52 UTC
Labels: *duplicate, workbench, workbench-tabs
