### ISSUE TITLE
Markdown: slight flickering in preview while editing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19475] opened 2017-01-27 05:58 UTC
Follow up from https://github.com/Microsoft/vscode/issues/19351, there is still a little bit of flickering when editing a markdown file while having the preview open.

My setup:
* editing our release notes (that is some good amount of text with images)
* zoom level 1

Would be awesome if it was possible to avoid flicker alltogether.

**Comment by mjbvz** [comment] 2017-04-20 23:33
This at least partially seems to be caused by the badge icons in the release notes being reloaded on each update. I have noticed it more in documents that have images, especially when those images cannot be cached

**Comment by mjbvz** [comment] 2017-08-03 06:59
This should be fixed by recent changes to how the markdown previews replaces its contents

**Closed by mjbvz** 2017-08-03 06:59 UTC
Labels: bug, markdown
