### ISSUE TITLE
Modify/disable built-in snippet

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#19952] opened 2017-02-05 02:28 UTC
vscode: 1.9.0

From discussion: https://github.com/Microsoft/vscode/issues/18963

The copy and override way is not optimal as it creates two identical entries in the list:
![image](https://cloud.githubusercontent.com/assets/3254987/22623233/ac729890-eb07-11e6-89bf-6466f0db9e22.png)

It would be better if we can edit or remove the built-in snippet directly.

**Comment by jrieken** [comment] 2017-02-06 08:48
We have similar discussions about other non-code extension contributions, like keybindings

**Comment by unional** [comment] 2017-02-06 08:54
@jrieken would you consider re-open https://github.com/Microsoft/vscode/issues/18963 also?
The `editor.snippetSuggestions: 'top'` solution is not good enough.

**Comment by jrieken** [comment] 2017-02-16 07:46
dupe of #10565

**Closed by jrieken** 2017-02-16 07:46 UTC
Labels: feature-request, snippets
