### ISSUE TITLE
Issue reporter not working

### ISSUE THREAD

**Issue by neilw73** [Microsoft/vscode#45307] opened 2018-03-08 15:48 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 8.1

Steps to Reproduce:

1.Click on smilie face, select performance from dropdown
2.Select to 'submit a bug'

After filling in title then contents, clicking on 'preview on github' nothing happens, no browser opens or updates (via twitter opens twitter page just fine).

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2018-03-08 17:19
Sorry for the inconvenience, I think this is a duplicate of https://github.com/Microsoft/vscode/issues/44245. This should be fixed in the newest version of code,  content that is too long to open in a browser window will now be copied to clipboard so that you can paste it into the issue.

**Closed by RMacfarlane** 2018-03-08 17:19 UTC
