### ISSUE TITLE
Hover doesn't render sub/sup html elements in Markdown text

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#21141] opened 2017-02-22 14:41 UTC
Hover doesn't render sub/sup html elements in Markdown text. 

- VSCode Version: 1.9.1/1.10.0-insider
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. hover over some text returning `x<sup>x+1</sup>.  x<sub>i+1</sub>`
2. Text should be rendered as x<sup>x+1</sup>.  x<sub>i+1</sub>

This follows up on https://github.com/redhat-developer/vscode-java/issues/155, where I'm now trying to make Javadoc return sub/sub HTML tags as-is, in the Markdown text (unreleased WIP):

<img width="578" alt="screen shot 2017-02-22 at 9 34 42 am" src="https://cloud.githubusercontent.com/assets/148698/23216104/c76ef2cc-f8e2-11e6-8ac9-eb1e228fa7ba.png">

The Markdown rendering engine in VS Code supports it, as can be seen in the Markdown preview pane, just not in hover mode.

**Comment by jrieken** [comment] 2017-02-23 08:50
The `MarkedString` is strictly markdown without embedded html or scripts. Closing as dupe of #11877. The idea is to allow Html (w/o scripts and styles) in addition to Markdown. I think that would suite javadoc well because it often html-elements frequently

**Closed by jrieken** 2017-02-23 08:50 UTC
