### ISSUE TITLE
git-bash integration truncate some multiline command outputs

### ISSUE THREAD

**Issue by Jule-** [Microsoft/vscode#19370] opened 2017-01-25 14:43 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- VSCode Version: Code - Insiders 1.9.0-insider (fbea777a881523bc01a1358d115b16673dc5942e, 2017-01-25T07:12:18.506Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
fake-extension-1|author|0.0
fake-extension-2|author|0.0
---

Steps to Reproduce:

1. Install some extensions, or be sure you already have at least 2.
2. If you want you can deactivate all extensions in order to be sure none of them can interfere with the test.
3. Set in your settings:
`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`
4. Then open new integrated terminal
`Terminal: Create New Integrated Terminal`
5. Execute command:
`$ code --list-extensions`

As you can see only the first line is shown. You can see expected output with command `$ code --list-extensions | cat`.

I don't know why this command show bad output while others like `code --help`  works well.

**Comment by mousetraps** [comment] 2017-01-26 00:51
Thanks for reporting! It actually looks like `code --list-extensions` is only listing the first line even outside of the terminal window! Looks like a duplicate of https://github.com/Microsoft/vscode/issues/17343, which was just recently fixed, and should be available in our next insiders build! 🎉

**Closed** 2017-01-26 01:16 UTC
Labels: bug, duplicate, extensions

**Comment by Jule-** [comment] 2017-01-26 08:50
Ok this is really strange because outside is ok for me, and even inside `code --list-extensions | cat` show the right output (multiple extensions listed).
But if you think this is ok in next insider build well done! :smile: :tada:
