### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by masonicboom** [Microsoft/vscode#5045] opened 2016-04-06 17:53 UTC
I'm interested in support for printing out code files.

Is there a way to cause the editor to render the full file into the DOM (as opposed to only the visible set of rows)? That seems like the main hurdle.

**Comment by alexandrudima** [comment] 2017-05-29 12:14
This can be somewhat achieved by copying and pasting into a software that can accept HTML from the clipboard e.g. Word

**Comment by mjbvz** [comment] 2017-11-02 20:33
Duplicate of #5953

**Closed by mjbvz** 2017-11-02 20:33 UTC
Labels: duplicate, editor, feature-request
