### ISSUE TITLE
how to get file name and modification time in snippets json

### ISSUE THREAD

**Issue by yaochx** [Microsoft/vscode#14897] opened 2016-11-03 08:38 UTC
- VSCode Version:1.6.1
- OS Version:ubuntu gnome 16.04

I want to add an author header template by snippet
so I write a snippet like this
`	"Author info": {
		"prefix": "author",
		"body": [
			"/**",
    		"	ULSee.com Copyright(c) 2016",
    		"	${file:File name}",
    		"	Purpose: ${purpose:File description}",
			"	",
    		"	@author  ${author:collin@ulsee.com}",
    		"	@version ${version:0.10} ${day:1}/${month:10}/2016", 
			"*/"
		],
		"description": "add author info and file description at the head of file"
	}`
It's not very efficient to type file name and time once I create a file,
so, is there some ways to do this, like predefined variables.
Thanks

**Comment by jrieken** [comment] 2016-11-03 15:15
dupe of #13047

**Comment by jrieken** [comment] 2016-11-03 15:15
dupe of #13047

**Closed by jrieken** 2016-11-03 15:15 UTC
Labels: duplicate
