### ISSUE TITLE
Errors Throughout 

### ISSUE THREAD

**Issue by radascuta** [microsoft/vscode#118506] opened 2021-03-09 04:45 UTC
No commands are working from the PowerShell Extension. e.g.: "Error running command PowerShell.InsertCommand: Running the contributed command: 'PowerShell.InsertCommand' failed.. This is likely caused by the extension that contributes PowerShell.InsertCommand."

No commands are working from the FaunaDB Extension. e.g.: "command 'faunadb.refreshEntry' not found" 

No auto-complete code is working in PowerShell. 

Not sure what's going on, the installation doesn't show any problems. 
Any ideas? I installed as admin on Windows 10. 

__
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (6.92GB free)|
|Process Argv|--crash-reporter-id 84ba2234-c25b-4080-bfce-4381c7462d07|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
faunadb|fau|1.6.0
powershell|ms-|2021.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by radascuta** [comment] 2021-03-09 21:29
At least if someone can give me an idea how to make the auto-complete work in VSCode, that would be great. I am moving from PowerShell ISE, which worked great for me for years, to VSCode, and auto-complete has to work.

**Comment by TylerLeonhardt** [comment] 2021-03-09 22:39
/extPowershell

This is likely a dupe of https://github.com/microsoft/vscode/issues/117649
discussed further in the PowerShell extension here: 
https://github.com/PowerShell/vscode-powershell/issues/3227#issuecomment-793192452

**Closed** 2021-03-09 22:39 UTC
Labels: *caused-by-extension, new release
