### ISSUE TITLE
Request: Webstorm Like Editors(Horizontal and Vertical) 

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#47737] opened 2018-04-12 14:00 UTC
Would be great if you could have 4 editors open at one time.  2 rows, 2 editors on each row.  This feature is very helpful in WebStorm and Visual Studio.

**Comment by mjbvz** [comment] 2018-04-12 15:51
Duplicate of #14909

**Closed by mjbvz** 2018-04-12 15:51 UTC
