### ISSUE TITLE
empty explorer "open folder" location 

### ISSUE THREAD

**Issue by raydleemsc** [microsoft/vscode#115462] opened 2021-01-30 14:44 UTC
clicking "open folder" from empty explorer opens on the user profile - please can this be added as a config location so there isn't a tremendous scrabbling around to find the source location. really don't want it fiddled with by last file/folder, mru, or anything like that so it can be relied upon not to wander unnecessarily, but handily configured when needed

thank you

**Comment by gjsjohnmurray** [comment] 2021-01-30 15:05
/duplicate of #114119

I suggest you upvote that by putting a 👍 on the first post there.

**Closed** 2021-01-30 15:06 UTC
Labels: *duplicate
