### ISSUE TITLE
New rgb standard

### ISSUE THREAD

**Issue by DanRotaru** [microsoft/vscode#138402] opened 2021-12-03 13:28 UTC
Recently Chrome forces new rgb standard with alpha (opacity) support: 
`rgb(0 0 0 / 15%)` = `rgba(0, 0, 0, .15)`
or without
`rgb(0 0 0)` = `rgb(0, 0, 0)`
Now when I'm changing value of color (in rgb/rgba) in chromium devtools I'm receiving a new rgb standard value, but vscode don't understand the new standard and dont see and don't display a color picker & viewer
![image](https://user-images.githubusercontent.com/7759507/144610150-dfc8463a-cf77-4a69-9d33-21e7bea22d82.png)

**Comment by aeschli** [comment] 2021-12-06 15:10
duplicate of https://github.com/microsoft/vscode/issues/111337

**Closed by aeschli** 2021-12-06 15:10 UTC
