### ISSUE TITLE
Syntax highlight failing on variable names starting with 'var'

### ISSUE THREAD

**Issue by huttarichard** [Microsoft/vscode#4496] opened 2016-03-21 11:08 UTC
- VSCode Version: Version 0.10.11 / Build f291f4ad600767626b24a4b15816b04bee9a3049
- OS Version: OSX 10.11

Do I need to explain more? 

<img width="489" alt="snimek obrazovky 2016-03-21 v 12 05 14" src="https://cloud.githubusercontent.com/assets/1809268/13916877/82495d98-ef5d-11e5-87a3-abef041d2345.png">

**Comment by aeschli** [comment] 2016-03-21 14:17
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by aeschli** 2016-03-21 14:17 UTC
