### ISSUE TITLE
ReleaseNotes tab reloading when switching back to it from another tab

### ISSUE THREAD

**Issue by dubeg** [Microsoft/vscode#21658] opened 2017-03-01 22:05 UTC
- VSCode Version: 1.10.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Open VSCode
2. Open the Release Notes tab.
3. Open another tab.
4. Switch back to the Release Notes tab.
5. Notice how it reloaded and lost your current scroll position in it. 

Note:  
I just noticed this while checking out release 1.10.0's notes. I got to the Minimap section, opened my Preferences in another tab to enable the minimap, then I went back to the ReleaseNotes tab and it reloaded, losing my current scroll/viewport/whatever-you-call-it position in it.

**Comment by mjbvz** [comment] 2017-03-01 22:21
Duplicate of #15214

**Closed by mjbvz** 2017-03-01 22:21 UTC
Labels: duplicate

**Comment by dubeg** [comment] 2017-03-01 22:23
Sorry about that, I guess I need to work on my terms I use to search.
