### ISSUE TITLE
[Feature Request] VSCode TypeScript extension exported things + auto import

### ISSUE THREAD

**Issue by DevoidCoding** [Microsoft/vscode#34594] opened 2017-09-18 21:52 UTC
The intellisense doesn't show the exported classes, functions, enums, ... in the actual workspace.
I know there's extension that allow to make that, but the native extension working with the great TSServer running will be amazing for that !
Also, the diagnostic logic of typescript already proprose to import something with the bulblight after we type the complete name of the exported thing, and it works like a charm with baseUrl and already imported section. Why don't propose an option to autoimport after hitting the completion key on the intellisense window ?

**Comment by mjbvz** [comment] 2017-09-18 22:31
Auto importing is tracked by #2635

Can you please explain the first issue more? Please include a small code example and description of the expected behavior

**Comment by DevoidCoding** [comment] 2017-09-19 00:58
Thank you for the issue, I'm gonna subscribe on it.

For the first one, here's an example : 
MyClass.ts
```ts
export class MyClass {

}
```
index.ts
```ts
var myClass = new MyClass();
```

If we look at the IntelliSense here, we can't see "MyClass" : https://i.imgur.com/ZTMb1C6.png
But, if we import it, we can see it here : https://i.imgur.com/QSmEauG.png
The goal is to have the "MyClass" intellisense before importing the file, like that : https://i.imgur.com/9pEn6TV.png
For sure, not showing that this is an alias but a class that can be auto-imported.

**Comment by mjbvz** [comment] 2017-09-19 01:04
Thanks. Showing suggestions for `MyClass` in `index.ts` before the import is added is what #2635 is tracking

Closing a duplicate of #2635

**Closed by mjbvz** 2017-09-19 01:04 UTC
Labels: duplicate, typescript
