### ISSUE TITLE
Failed to connect to the remote extension host server

### ISSUE THREAD

**Issue by cossio** [microsoft/vscode#195986] opened 2023-10-19 11:19 UTC
Type: <b>Bug</b>

Trying to reconnect to a remote server with the Remote Tunnels extension, gives the following error:

```
Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)
```

If I then login by other means to the server and restart the vscode server running there, then the remote tunnel connection works again. But the same error 1006 appears some time later, when I disconnect and reconnect.

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.0.0
Modes:
Connection to 'SSH: sibyl' could not be established  Canceled
Remote OS version: Linux x64 5.15.0-84-generic
Connection to 'lecuona' could not be established  WebSocket close with status code 1006

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 15, 11|
|Memory (System)|24.00GB (0.73GB free)|
|Process Argv|--crash-reporter-id 4622632d-a8b5-4bc6-8627-2ad0ef2866ee|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: sibyl' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|gonzaga|
|OS|Linux x64 5.15.0-84-generic|
|CPUs|Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz (48 x 2400)|
|Memory (System)|125.53GB (106.81GB free)|
|VM|0%|

Connection to 'lecuona' could not be established  WebSocket close with status code 1006
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pyreplss1:30865275
pythoncet0:30859751
h48ei257:30864973
pythontbext0:30864172

```

</details>

**Comment by rebornix** [comment] 2023-10-20 17:51
This is a duplicate of https://github.com/microsoft/vscode/issues/195617 and we are working on a fix now. Let's track this in https://github.com/microsoft/vscode/issues/195617, thank you!

**Closed by rebornix** 2023-10-20 17:51 UTC
Labels: *duplicate, triage-needed
