### ISSUE TITLE
Partial blurry Font (Menu, Navigator, Code)

### ISSUE THREAD

**Issue by TheMasterFX** [Microsoft/vscode#57200] opened 2018-08-25 15:40 UTC
Since the last update I have issues with blurry fonts in parts of the VS Window, especially when it is out of focus. Moving the Cursor over the affected area it get partially away. See the attached image.

Graphics Card is an Nvidia GTX 1070 with driver Version 398.36
![visualstudio_code](https://user-images.githubusercontent.com/12451336/44619998-e32c8180-a88d-11e8-9e0b-ba4a5a82a491.png)

- VSCode Version: 1.26.1
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Start vscode
2. open a project
3. don't move mouse

Does this issue occur when all extensions are disabled?: Yes

**Comment by abrad1212** [comment] 2018-08-25 17:54
I'm experience the same issues after the most recent update

![Blurry Editor](https://imgur.com/a/YZcIdNz)

**Comment by abrad1212** [comment] 2018-08-25 18:04
# Work-around
After closing all Visual Studio Code windows, I opened a terminal and ran **`code.exe --disable-gpu`**

So far haven't observed the blurring effect after disabling the gpu.

**Comment by maccster** [comment] 2018-08-25 22:38
Workaround fixed it for me, GTX 1080, driver version: 398.82 VSC: 1.26.1 W10x64

**Comment by bpasero** [comment] 2018-08-27 04:41
Duplicate of https://github.com/Microsoft/vscode/issues/51789

**Closed by bpasero** 2018-08-27 04:41 UTC
Labels: editor, electron-2.0.x-update

**Comment by TheMasterFX** [comment] 2018-09-13 16:56
Okay.. disabling FXAA fixed it for me too... thanks
