### ISSUE TITLE
Snippets suppress string auto completions

### ISSUE THREAD

**Issue by tangentyh** [microsoft/vscode#100196] opened 2020-06-15 13:43 UTC
Issue Type: <b>Bug</b>

After updating to the new version 1.46.0, I found string auto completions got suppressed by snippets, as the gif shows, and this problem persists in insider version. By saying "suppressed" I mean that when there are snippet candidates in auto completions, the string candidates disappear.
![Jun-15-2020 21-19-35](https://user-images.githubusercontent.com/13913131/84663154-59144800-af4f-11ea-8682-e0cd808db97a.gif)

In contrast, before the update, the behavior in version 1.45.1 is as below gif, where string candidates remain intact, which should be expected imo.
![Jun-15-2020 21-03-58](https://user-images.githubusercontent.com/13913131/84663358-a0023d80-af4f-11ea-9eaf-243c54a85536.gif)

Of course, below settings are required for auto completions in comments.
```JSON
{
    "editor.quickSuggestions": {
        "comments": true,
        "other": true,
        "strings": true
    }
}
```

VS Code version: Code - Insiders 1.47.0-insider (0288447572790f983c350905bd1fc5b754970a0a, 2020-06-15T05:32:43.514Z)
OS version: Darwin x64 19.5.0

Extensions: none

**Comment by jrieken** [comment] 2020-06-15 15:13
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by tangentyh** [comment] 2020-06-15 15:20
@jrieken I think I mentioned in the description that I also tried in the insider version, from which I initialized this issue. And the insider version is newly installed with no extension installed, as the last line shows:
> Extensions: none

**Comment by jrieken** [comment] 2020-06-15 15:42
This is what I see from master... 

<img width="654" alt="Screenshot 2020-06-15 at 17 42 03" src="https://user-images.githubusercontent.com/1794099/84677809-88b35800-af2f-11ea-954d-3dcab65c1e9a.png">

**Comment by tangentyh** [comment] 2020-06-15 15:53
![image](https://user-images.githubusercontent.com/13913131/84678555-bbc30f00-af62-11ea-8936-58db47cf1ba0.png)

@jrieken Very strange then... Try the version I am on?
> VS Code version: Code - Insiders 1.47.0-insider (0288447, 2020-06-15T05:32:43.514Z)

**Comment by jrieken** [comment] 2020-06-15 15:54
well, master is what builds insiders...

**Comment by tangentyh** [comment] 2020-06-15 15:59
@jrieken I installed the insider version from `brew` and as you can see it is on `0288447`, which is from yesterday and I guess the problem may be fixed in later commits. Will try the cutting edge build to see if the problem persists.

**Comment by tangentyh** [comment] 2020-06-19 08:12
Hi @jrieken, some updates: sadly, the problem still persists in the new release version 1.46.1 and the insider version 8cd3fe080bee38d28ba01d0d71713d6ec22b254e. Below screenshot taken from the insider version 8cd3fe080bee38d28ba01d0d71713d6ec22b254e.
![image](https://user-images.githubusercontent.com/13913131/85111286-b1489400-b246-11ea-9ec2-98e704c88767.png)

**Comment by tangentyh** [comment] 2020-06-23 16:06
Hello, any updates? This problem still haunts me...
I see the tag "need more information", what information should I further provide?

**Comment by jrieken** [comment] 2020-06-23 16:37
Ok - I was able to reproduce and debug now. What's happening is there there are multiple providers: snippets, typescript, and words. The TS provider has a higher priority than the word provider and since it returns a result (which then gets filtered) we don't ask for word suggestion.

**Comment by jrieken** [comment] 2020-06-23 16:38
This is unfortunate and already known as

/duplicate of https://github.com/microsoft/vscode/issues/21611

**Closed** 2020-06-23 16:39 UTC
Labels: *duplicate, needs more info, suggest
