### ISSUE TITLE
Problem of display while using Visual Studio COde

### ISSUE THREAD

**Issue by Fonzy-dev** [microsoft/vscode#93678] opened 2020-03-29 08:11 UTC
Hi,

While i'm using Visual Studio Code, white pixels like a problem of glitchings are appearing.

When i moove the mouse on these pixels, they disappear. This is really annoying as i have my visual studio code windows which is becoming full of white pixels when i don't have my cursor in the window.

I also had the same problem with Slack so i don't know if it's because of the GeForce Drivers or Whatever but this problem appear for theses 2 applications only.

If you have ever encounter this problem and have solutions please let me know.
![Capture](https://user-images.githubusercontent.com/62830060/77844241-505c7300-71a5-11ea-8532-88515310e17e.PNG)

Thank you,
François B

**Comment by EvilDentist** [comment] 2020-03-29 14:17
I also have this issue. Tried reinstalling and messing with the setting but the problem persists.. It worked fine a few months ago

**Comment by IllusionMH** [comment] 2020-03-29 18:47
/duplicate of #93356

For more details and current solution see https://github.com/microsoft/vscode/issues/93356#issuecomment-604657278

**Closed** 2020-03-29 18:48 UTC
Labels: *duplicate
