### ISSUE TITLE
Block scrolling on intellicode!

### ISSUE THREAD

**Issue by padi18** [microsoft/vscode#116894] opened 2021-02-17 23:31 UTC
Issue Type: <b>Feature Request</b>

My suggestion is because when i'm searching for snippet in the intellicode (CTRL+SPACE) when arrive at final scroll, editor continues scrolling down, and move all the screen! I hope my suggestion help!

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.21313

**Comment by yume-chan** [comment] 2021-02-18 04:18
Duplicate of #113389

It's already been fixed in insiders build.

**Closed** 2021-02-18 06:34 UTC
Labels: *duplicate
