### ISSUE TITLE
Nonstop "Initializing JS/TS language features" if you only open interactive playground

### ISSUE THREAD

**Issue by GeoJunkie** [microsoft/vscode#82424] opened 2019-10-12 12:16 UTC
Issue Type: <b>Bug</b>

Summary: When installing on Catalina, MacOS gives warnings about being unable to open, JS/TS features don't fully initialize, and Typescript commands aren't available.

1. Brand new install of VS Code on MacOS Catalina. 
2. Try to open VS. Get an error.
3. Open via menu, click `Open` on prompt
2. Go to the Interactive Playground
3. "Initializing JS/TS language features" shows at the bottom and never goes away
4. Look in the `Errors and Warnings` embedded editor on the Interactive Playground. No errors or warnings are highlighted (or showing anywhere else).

I also followed the steps from #82130, but the `Typescript:` commands aren't available, so I couldn't retrieve the logs. This was just downloaded, dragged to Applications, and started. No other configurations or updates were made. I did uninstall, clear settings, and reinstall just to be sure, but it still didn't work.

## Screenshots:

When first opening VS Code:

<img width="432" alt="Screen Shot 2019-10-12 at 07 54 16" src="https://user-images.githubusercontent.com/7596032/66701185-8c6b4c80-ecc7-11e9-8401-2b15b3718a90.png">

There's an option to choose "Open" from Finder:

<img width="388" alt="Screen Shot 2019-10-12 at 07 54 35" src="https://user-images.githubusercontent.com/7596032/66701191-98efa500-ecc7-11e9-9886-a360d6d99a80.png">

This brings up this dialog, which enables it to be opened:

<img width="489" alt="Screen Shot 2019-10-12 at 07 54 45" src="https://user-images.githubusercontent.com/7596032/66701197-a4db6700-ecc7-11e9-8772-02bedf0c2bf7.png">

The Interactive Playground (note the spinning `Initializing JS/TS language features` status at the bottom and the complete lack of error/warning highlighting:

![](https://cld.wthms.co/SO5Pyt+)
Image Link: https://cld.wthms.co/SO5Pyt

I did set `"typescript.tsserver.log": "verbose"`:
<img width="1036" alt="Screen Shot 2019-10-12 at 07 58 15" src="https://user-images.githubusercontent.com/7596032/66701252-3cd95080-ecc8-11e9-864b-7113f80d4589.png">

However, after restarting and going back into Interactive Playground, I found that there's no `Typescript:` commands available:

![](https://cld.wthms.co/jq4W4A+)
Image Link: https://cld.wthms.co/jq4W4A

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (11.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment] 2019-10-13 02:36
What if you open a normal js or typescript file?

**Comment by GeoJunkie** [comment] 2019-10-14 12:02
Thanks for pointing that out @mjbvz ! It actually does work fine if I load a normal JS file. And not that I have, it's no longer doing the spinning `Initializing JS/TS language features`, but the errors are still not highlighting in the Interactive Playground.

With this and by creating a TS file, I was able to locate some errors that may be pertinent:

`Info 39   [7:58:3.744] Open files: 
Info 39   [7:58:3.744] 	FileName: walkThroughSnippet:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/browser/editor/^vs_code_editor_walkthrough.md?{"moduleId":"vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough"}#1.js ProjectRootPath: undefined
Info 39   [7:58:3.744] 		Projects: /dev/null/inferredProject1*
Info 39   [7:58:3.744] 	FileName: walkThroughSnippet:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/browser/editor/^vs_code_editor_walkthrough.md?{"moduleId":"vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough"}#3.js ProjectRootPath: undefined
Info 39   [7:58:3.744] 		Projects: /dev/null/inferredProject2*
Info 39   [7:58:3.744] 	FileName: walkThroughSnippet:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/browser/editor/^vs_code_editor_walkthrough.md?{"moduleId":"vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough"}#4.js ProjectRootPath: undefined
Info 39   [7:58:3.744] 		Projects: /dev/null/inferredProject3*
Info 39   [7:58:3.744] 	FileName: walkThroughSnippet:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/browser/editor/^vs_code_editor_walkthrough.md?{"moduleId":"vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough"}#6.js ProjectRootPath: undefined
Info 39   [7:58:3.744] 		Projects: /dev/null/inferredProject4*
Info 39   [7:58:3.744] 	FileName: walkThroughSnippet:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/browser/editor/^vs_code_editor_walkthrough.md?{"moduleId":"vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough"}#7.js ProjectRootPath: undefined
Info 39   [7:58:3.744] 		Projects: /dev/null/inferredProject5*
Info 39   [7:58:3.744] 	FileName: walkThroughSnippet:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/browser/editor/^vs_code_editor_walkthrough.md?{"moduleId":"vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough"}#9.js ProjectRootPath: undefined
Info 39   [7:58:3.744] 		Projects: /dev/null/inferredProject6*
Perf 39   [7:58:3.744] 1::updateOpen: elapsed time (in milliseconds) 10.0830
Info 40   [7:58:3.744] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":1,"success":true,"body":true}
`

**Comment by mjbvz** [comment] 2019-10-15 18:38
Duplicate of #81059

**Closed by mjbvz** 2019-10-15 18:38 UTC
Labels: bug, new release
