### ISSUE TITLE
Emmet: dl, dt and dd not working when used alone

### ISSUE THREAD

**Issue by miau715** [Microsoft/vscode#33255] opened 2017-08-28 11:52 UTC
- VSCode Version: 1.15.1
- OS Version:OS X 10.11.6

Steps to Reproduce:

In html:

```
  dl     // not working correctly. It turns into <dialog></dialog>  
  dt     // not working  
  dd     // not working  
  dl>dt  // working  
  dt+dd  // working
```

**Comment by ramya-rao-a** [comment] 2017-08-28 20:18
Fixed with https://github.com/Microsoft/vscode-emmet-helper/commit/4eace9c17f5718ae7d9e71f1deb176bd4b8d5e1d

**Root cause**: We maintain a white list of commonly used Html5 tags. dl, dd, dt were missing in this list. On their own only items in the white list trigger emmet suggestions. This was done to avoid emmet from getting triggered when user types simple words. For eg: `hello` should not trigger `<hello></hello>`

@miau715 Here are your options

- Use the latest Insiders tomorrow which will have this fix or
- Use custom snippets in VS Code 1.15.1
     - Create a file `snippets.json` with the following contents and add the setting `emmet.extensionsPath`. The value for this setting should be the path to the folder in which the `snippet.json` file lives
 ```
{
	"html": {
		"snippets": {
			"dl": "dl",
			"dt": "dt",
			"dd": "dd"
		}
	}
}
```

**Comment by miau715** [comment] 2017-08-29 10:55
Today I found that "tr", "th", "td", "thead", "tbody", "tfoot" are not working either. Maybe the white list need a careful review.

**Comment by ramya-rao-a** [comment] 2017-08-29 15:14
@miau715 tr, th, td work in the Insiders. I'll add the rest.

The idea was to curate the most commonly used ones and then keep incrementing it as per user feedback.

Note: All of these still work regardless of the whitelist when you use the `Emmet: Expand Abbreviation` command or set `emmet.triggerExpansionOnTab` to `true.

**Comment by ramya-rao-a** [comment] 2017-08-30 02:03
Tonight's Insiders build will have all the above discussed tags

**Closed** 2017-08-30 02:03 UTC
Labels: emmet, new release
