### ISSUE TITLE
How I can set default size for the popup when I inspect a variable with mouse over? (In Visual Studio Code) 

### ISSUE THREAD

**Issue by pookdeveloper** [microsoft/vscode#77809] opened 2019-07-23 09:59 UTC
How I can set default size for the popup when I inspect a variable with mouse over? (In Visual Studio Code) Thanks

**Comment by rebornix** [comment] 2019-07-26 22:43
/duplicate of https://github.com/microsoft/vscode/issues/29126

**Closed** 2019-07-26 22:43 UTC
Labels: *duplicate, editor-hover, feature-request
