### ISSUE TITLE
Microsoft Visual Code - Suggestion

### ISSUE THREAD

**Issue by JohnMagdy** [Microsoft/vscode#30383] opened 2017-07-11 09:22 UTC
_Hello sir, really i love this Project its amazing and it 'd be much better if you added a feature which alerts us when our Opened files is edited/opened with any kind of another Editors... and then shows a Dialog with 2 optians to tell us to reload opened file (edited one)'s content or just keep current content as its..._

**Comment by mjbvz** [comment] 2017-07-12 06:31
Duplicate of #14298

**Closed by mjbvz** 2017-07-12 06:31 UTC
Labels: duplicate, explorer-files, feature-request, workbench
