### ISSUE TITLE
Terminal default profile is not respected

### ISSUE THREAD

**Issue by Dreadlord1981** [microsoft/vscode#132845] opened 2021-09-10 07:56 UTC
Issue Type: <b>Bug</b>

1. Start VS code
2. New terminal
3. Select Default profile
4. Chose terminal other then powershell.
5. Close vscode with terminal open
6. Start VS Code

Expects default terminal to start as new terminal
result.. powershell starts as default terminal..

![image](https://user-images.githubusercontent.com/22214181/132820576-35145eb8-d836-40dd-875c-fb27e5728054.png)
![image](https://user-images.githubusercontent.com/22214181/132820612-e46e06ef-c017-420b-9e56-820e3c433068.png)

**After restart of vscode:**
![image](https://user-images.githubusercontent.com/22214181/132820685-f4776568-f002-4c05-96c3-71985547e89a.png)

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (21.22GB free)|
|Process Argv|--crash-reporter-id bf07662a-6585-497f-9028-42b2a59bde4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.11.0
vscode-eslint|dba|2.1.25
prettier-vscode|esb|8.1.0
vs-code-xml-format|fab|0.1.5
go|gol|0.27.2
vscode-docker|ms-|1.16.1
remote-containers|ms-|0.194.0
remote-wsl|ms-|0.58.2
js-debug-nightly|ms-|2021.9.417
rpg|Nie|0.2.1
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.27.0
java|red|0.81.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30364559
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30363604

```

</details>

**Comment by IllusionMH** [comment] 2021-09-10 08:04
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Closed** 2021-09-10 08:05 UTC
Labels: *duplicate

**Comment by Dreadlord1981** [comment] 2021-09-10 08:08
Thank you for the quick response 👍

**Comment by anzuj** [comment] 2021-09-10 14:30
What's the September recovery release ETA?

**Comment by quyenvsp** [comment] 2021-09-10 17:49
> What's the September recovery release ETA?

They planning release it yesterday but the fix for another issue took a little longer "so expect it Monday probably around 11-12 PST unless something goes wrong" https://github.com/microsoft/vscode/issues/132150
