### ISSUE TITLE
Terminal filename linkifier fails on lines that no not have a space after last column

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vscode#110938] opened 2020-11-19 11:06 UTC
- VSCode Version: 1.15.1
- OS Version: MacOS 11.0

Steps to Reproduce:

1. Open terminal and use any command line tool that reports filenames as results, like find/grep tools, linters, compilers.
2. Try to click the filename

If working it should open the mentioned file at the line and optionally column mentioned in the line clicked, the format is very easy `filename:line:column:...`.

The feature works fine only if the is a space after the last colon: `filename:line:column: foo` will work but ``filename:line:column:bar` will not.

![](https://sbarnea.com/ss/Screen-Shot-2020-11-19-11-00-03.png)

In example above clicking on the first match will fail as the "class" does not have a space before it, but the second line will work as it happens to be a line starting with a space.

Note: I tested the same feature in other terminals and they seem to be working fine.

**Comment by meganrogge** [comment] 2020-11-19 17:16
Thanks for the issue. Closing it as a duplicate of #21125

**Comment by ssbarnea** [comment] 2020-11-19 17:21
@meganrogge I am afraid that is not a duplicate of the mentioned ticket. It is a very simple bug cause by a broken regex that has nothing to do with other extensions.

**Comment by meganrogge** [comment] 2020-11-20 21:44
@ssbarnea oh yeah I see that now thanks

**Comment by meganrogge** [comment] 2020-11-20 22:17
![recording (47)](https://user-images.githubusercontent.com/29464607/99855172-0c0a5280-2b3b-11eb-9312-dafd1b93186f.gif)

here's your other example working as expected

**Closed** 2020-11-22 02:18 UTC
Labels: bug, integrated-terminal

**Comment by ssbarnea** [comment] 2020-12-21 15:23
@meganrogge I was able to narrow down the bug the issue happens only when the file is at the root of the repository, basically when you have no path component on the first element:

```
$ rg console_
setup.cfg:82:1:console_scripts =
lib/ansiblelint/__main__.py:37:40:from ansiblelint.color import console, console_stderr
lib/ansiblelint/__main__.py:118:9:        console_stderr.print(Markdown(msg))
lib/ansiblelint/color.py:15:1:console_stderr = Console(file=sys.stderr, theme=_theme)
```

In this case clicking fails to work as expected only of the first item, what happens is that vscode prompts to check which file to open, something like screenshot below:

![](https://sbarnea.com/ss/Screen-Shot-2020-12-21-15-22-09.png) 

PS. I tested it with vscode-insiders too.
