### ISSUE TITLE
Review the contents of `notebook.indentation` 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#209496] opened 2024-04-03 22:44 UTC
Based on the code it seem the message can contain the text `Spaces: true` or `Tab Size: true`
Not sure thats correct, but I have no idea, if it is, please feel free to close this issue.

`src/vs/workbench/contrib/notebook/browser/contrib/editorStatusBar/editorStatusBar.ts`

```typescript
		const cellEditorOverridesRaw = editor.notebookOptions.getDisplayOptions().editorOptionsCustomizations;
		const indentSize = cellEditorOverridesRaw?.['editor.indentSize'] ?? cellOptions?.indentSize;
		const insertSpaces = cellEditorOverridesRaw?.['editor.insertSpaces'] ?? cellOptions?.tabSize;
		const tabSize = cellEditorOverridesRaw?.['editor.tabSize'] ?? cellOptions?.insertSpaces;

		const width = typeof indentSize === 'number' ? indentSize : tabSize;

		const message = insertSpaces ? `Spaces: ${width}` : `Tab Size: ${width}`;
		const newText = message;
		if (!newText) {
			this._accessor.clear();
			return;
		}

		const entry: IStatusbarEntry = {
			name: nls.localize('notebook.indentation', "Notebook Indentation"),
			text: newText,
			ariaLabel: newText,
			tooltip: nls.localize('selectNotebookIndentation', "Select Indentation"),
			command: SELECT_NOTEBOOK_INDENTATION_ID
		};

```

**Comment by Yoyokrazy** [comment] 2024-04-09 18:47
Caused by a typo where `insertSpaces` read from `tabSize` and vice versa. Resolved by #209493

**Closed by Yoyokrazy** 2024-04-09 18:47 UTC
Labels: debt, notebook-format
