### ISSUE TITLE
Error while starting Settings Sync: No authentication provider 'microsoft' is currently registered.

### ISSUE THREAD

**Issue by LilHang** [microsoft/vscode#106589] opened 2020-09-13 14:22 UTC
- VSCode Version: 1.49.0
- OS Version: win10 1909

Steps to Reproduce:

1. at first, sign in and start syncing, it works fine
2. after changing password  of Microsoft account，error message shows up when I start syncing. 

![image](https://user-images.githubusercontent.com/42541380/93020419-7ec4f200-f60f-11ea-9d99-34045324a3ee.png)
![image](https://user-images.githubusercontent.com/42541380/93020431-8f756800-f60f-11ea-9097-0afb587f8bda.png)

same issue: https://github.com/microsoft/vscode/issues/106321

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment] 2020-09-16 15:10
Closing as a duplicate of https://github.com/microsoft/vscode/issues/106321

**Closed by RMacfarlane** 2020-09-16 15:10 UTC
