### ISSUE TITLE
[WebView API] Web view not render: could not access window.localStorage

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#54338] opened 2018-07-15 07:52 UTC
Steps to Reproduce:

1. Get source code from https://github.com/formulahendry/vscode-node-red/tree/webview
2. npm install
3. Press `F5` to start project
4. Press `F1`, then type `Node-RED: Open`

In `WebView Developer Tool`, you would see below error: 
![image](https://user-images.githubusercontent.com/1050213/42731200-d93982f4-883a-11e8-8cfe-0b2487d8e729.png)

BTW, if I use previewHTML API (https://github.com/formulahendry/vscode-node-red/tree/master), the web view could render normally.

**Comment by mjbvz** [comment] 2018-07-16 17:30
Duplicate of #52246

**Closed by mjbvz** 2018-07-16 17:30 UTC
Labels: *duplicate, webview
