### ISSUE TITLE
File Watcher - Source control doesn't show changes automatically

### ISSUE THREAD

**Issue by MarcoB-Personio** [microsoft/vscode#226045] opened 2024-08-20 10:20 UTC
Type: <b>Bug</b>

VS Code detaiils:

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z (5 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Details:

Source control does not show changes automatically after making a change in a file and saving it. 

The only way to make it work is by manually pressing the Refresh icon in the Source Control tab.

I've followed the [File Watcher wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-remote), and after opening a file, editing it and saving it, the Output is the following:

2024-08-20 10:24:05.489 [info] [main] Log level: Info
2024-08-20 10:24:05.534 [info] [main] Validating found git in: "/usr/bin/git"
2024-08-20 10:24:05.582 [info] [main] Using git "2.39.3 (Apple Git-146)" from "/usr/bin/git"
2024-08-20 10:24:05.582 [info] [Model][doInitialScan] Initial repository scan started
2024-08-20 10:24:05.814 [info] > git rev-parse --show-toplevel [229ms]
2024-08-20 10:24:05.896 [info] > git rev-parse --git-dir --git-common-dir [65ms]
2024-08-20 10:24:05.898 [info] [Model][openRepository] Opened repository: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:05.992 [info] > git config --get commit.template [91ms]
2024-08-20 10:24:05.999 [info] > git rev-parse --show-toplevel [98ms]
2024-08-20 10:24:06.071 [info] > git rev-parse --show-toplevel [71ms]
2024-08-20 10:24:06.154 [info] > git rev-parse --show-toplevel [81ms]
2024-08-20 10:24:06.226 [info] > git rev-parse --show-toplevel [70ms]
2024-08-20 10:24:06.269 [info] > git rev-parse --show-toplevel [41ms]
2024-08-20 10:24:06.313 [info] > git rev-parse --show-toplevel [42ms]
2024-08-20 10:24:06.344 [info] > git rev-parse --show-toplevel [30ms]
2024-08-20 10:24:06.385 [info] > git rev-parse --show-toplevel [40ms]
2024-08-20 10:24:06.434 [info] > git rev-parse --show-toplevel [48ms]
2024-08-20 10:24:06.485 [info] > git rev-parse --show-toplevel [50ms]
2024-08-20 10:24:06.539 [info] > git rev-parse --show-toplevel [53ms]
2024-08-20 10:24:06.540 [info] > git check-ignore -v -z --stdin [107ms]
2024-08-20 10:24:06.580 [info] > git rev-parse --show-toplevel [40ms]
2024-08-20 10:24:06.617 [info] > git rev-parse --show-toplevel [36ms]
2024-08-20 10:24:06.656 [info] > git rev-parse --show-toplevel [38ms]
2024-08-20 10:24:06.709 [info] > git rev-parse --show-toplevel [52ms]
2024-08-20 10:24:06.787 [info] > git rev-parse --show-toplevel [77ms]
2024-08-20 10:24:06.885 [info] > git rev-parse --show-toplevel [96ms]
2024-08-20 10:24:06.943 [info] > git rev-parse --show-toplevel [56ms]
2024-08-20 10:24:06.944 [info] [Model][doInitialScan] Initial repository scan completed - repositories (1), closed repositories (0), parent repositories (0), unsafe repositories (0)
2024-08-20 10:24:07.175 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/main refs/remotes/main [1270ms]
2024-08-20 10:24:11.413 [info] > git status -z -uall [4235ms]
2024-08-20 10:24:11.462 [info] > git config --get commit.template [45ms]
2024-08-20 10:24:11.869 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/main refs/remotes/main [450ms]
2024-08-20 10:24:11.869 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/main refs/remotes/main [455ms]
2024-08-20 10:24:11.904 [info] > git config --local branch.main.vscode-merge-base [34ms]
2024-08-20 10:24:11.987 [info] > git rev-parse --show-toplevel [62ms]
2024-08-20 10:24:12.027 [info] > git rev-parse --show-toplevel [38ms]
2024-08-20 10:24:12.063 [info] > git rev-parse --show-toplevel [35ms]
2024-08-20 10:24:12.099 [info] > git rev-parse --show-toplevel [35ms]
2024-08-20 10:24:12.336 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/origin/main refs/remotes/origin/main [431ms]
2024-08-20 10:24:12.379 [info] > git merge-base refs/heads/main refs/remotes/origin/main [41ms]
2024-08-20 10:24:12.418 [info] > git rev-list --count --left-right refs/heads/main...refs/remotes/origin/main [38ms]
2024-08-20 10:24:12.461 [info] > git diff --name-status -z --diff-filter=ADMR 261315563bd0f98e0a8dc57f6b44e4da946b358c...refs/remotes/origin/main [36ms]
2024-08-20 10:24:13.813 [info] [main] Log level: Trace
2024-08-20 10:24:14.495 [info] > git status -z -uall [2623ms]
2024-08-20 10:24:14.497 [trace] [GitHistoryProvider][onDidRunGitStatus] HEAD: {"type":0,"name":"main","upstream":{"name":"main","remote":"origin","commit":"261315563bd0f98e0a8dc57f6b44e4da946b358c"},"commit":"261315563bd0f98e0a8dc57f6b44e4da946b358c","ahead":0,"behind":0}
2024-08-20 10:24:14.497 [trace] [GitHistoryProvider][onDidRunGitStatus] repository.HEAD: {"type":0,"name":"main","upstream":{"name":"main","remote":"origin","commit":"261315563bd0f98e0a8dc57f6b44e4da946b358c"},"commit":"261315563bd0f98e0a8dc57f6b44e4da946b358c","ahead":0,"behind":0}
2024-08-20 10:24:14.497 [trace] [OperationManager][start] GetBranch (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:14.497 [trace] [Model][open] Opening submodule: '/Users/marco.brito/dev/personio-web/rest-apis/workflow-apis'
2024-08-20 10:24:14.497 [trace] [Model][open] Opening submodule: '/Users/marco.brito/dev/personio-web/rest-apis/analytics-and-reporting-apis'
2024-08-20 10:24:14.497 [trace] [Model][open] Opening submodule: '/Users/marco.brito/dev/personio-web/rest-apis/groups-service'
2024-08-20 10:24:14.497 [trace] [Model][open] Opening submodule: '/Users/marco.brito/dev/personio-web/rest-apis/task-management-service-api'
2024-08-20 10:24:14.497 [trace] [OperationManager][end] Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2024-08-20 10:24:14.762 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/main refs/remotes/main [266ms]
2024-08-20 10:24:14.763 [trace] [OperationManager][end] GetBranch (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:14.764 [trace] [OperationManager][start] Config (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:14.793 [info] > git config --local branch.main.vscode-merge-base [29ms]
2024-08-20 10:24:14.793 [trace] [OperationManager][end] Config (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:14.794 [trace] [OperationManager][start] GetBranch (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:14.830 [trace] [OperationManager][start] Config (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:14.863 [info] > git config --local branch.main.merge [33ms]
2024-08-20 10:24:14.863 [trace] [OperationManager][end] Config (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:15.000 [trace] [Model][openRepository] Repository: /Users/marco.brito/dev/personio-web/rest-apis/workflow-apis
2024-08-20 10:24:15.035 [info] > git rev-parse --show-toplevel [34ms]
2024-08-20 10:24:15.035 [trace] [Model][openRepository] Repository root for path /Users/marco.brito/dev/personio-web/rest-apis/workflow-apis is: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:15.035 [trace] [Model][openRepository] Repository for path /Users/marco.brito/dev/personio-web already exists: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:15.035 [trace] [Model][openRepository] Repository: /Users/marco.brito/dev/personio-web/rest-apis/analytics-and-reporting-apis
2024-08-20 10:24:15.069 [info] > git rev-parse --show-toplevel [33ms]
2024-08-20 10:24:15.069 [trace] [Model][openRepository] Repository root for path /Users/marco.brito/dev/personio-web/rest-apis/analytics-and-reporting-apis is: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:15.069 [trace] [Model][openRepository] Repository for path /Users/marco.brito/dev/personio-web already exists: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:15.069 [trace] [Model][openRepository] Repository: /Users/marco.brito/dev/personio-web/rest-apis/groups-service
2024-08-20 10:24:15.103 [info] > git rev-parse --show-toplevel [33ms]
2024-08-20 10:24:15.103 [trace] [Model][openRepository] Repository root for path /Users/marco.brito/dev/personio-web/rest-apis/groups-service is: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:15.104 [trace] [Model][openRepository] Repository for path /Users/marco.brito/dev/personio-web already exists: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:15.104 [trace] [Model][openRepository] Repository: /Users/marco.brito/dev/personio-web/rest-apis/task-management-service-api
2024-08-20 10:24:15.117 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/origin/main refs/remotes/origin/main [323ms]
2024-08-20 10:24:15.117 [trace] [OperationManager][end] GetBranch (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:15.117 [trace] [GitHistoryProvider][onDidRunGitStatus] HEAD has not changed
2024-08-20 10:24:15.145 [info] > git rev-parse --show-toplevel [41ms]
2024-08-20 10:24:15.145 [trace] [Model][openRepository] Repository root for path /Users/marco.brito/dev/personio-web/rest-apis/task-management-service-api is: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:15.145 [trace] [Model][openRepository] Repository for path /Users/marco.brito/dev/personio-web already exists: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:31.793 [trace] [OperationManager][start] CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:31.957 [info] > git check-ignore -v -z --stdin [164ms]
2024-08-20 10:24:31.957 [trace] [OperationManager][end] CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:33.776 [trace] [Model][onDidChangeVisibleTextEditors] Repository for editor resource /Users/marco.brito/dev/personio-web/apps/attendance/frontend/src/shared/hooks/queries/useValidateAndCalculateDay.ts already exists: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:33.944 [trace] [OperationManager][start] Show (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:33.945 [trace] [OperationManager][start] GetObjectDetails (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:34.027 [info] > git ls-files --stage -- /Users/marco.brito/dev/personio-web/apps/attendance/frontend/src/shared/hooks/queries/useValidateAndCalculateDay.ts [82ms]
2024-08-20 10:24:34.043 [info] > git show --textconv :apps/attendance/frontend/src/shared/hooks/queries/useValidateAndCalculateDay.ts [99ms]
2024-08-20 10:24:34.043 [trace] [OperationManager][end] Show (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:34.086 [info] > git cat-file -s 6b06db458f4a17ac85a4eee248b6a712c42c010b [58ms]
2024-08-20 10:24:34.086 [trace] [OperationManager][end] GetObjectDetails (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:42.789 [trace] [OperationManager][start] CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:42.822 [info] > git check-ignore -v -z --stdin [33ms]
2024-08-20 10:24:42.822 [trace] [OperationManager][end] CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:44.832 [trace] [OperationManager][start] Config (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:44.856 [info] > git config --local branch.main.merge [24ms]
2024-08-20 10:24:44.856 [trace] [OperationManager][end] Config (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:47.325 [trace] [OperationManager][start] CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:47.358 [info] > git check-ignore -v -z --stdin [33ms]
2024-08-20 10:24:47.359 [trace] [OperationManager][end] CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:48.036 [trace] [Model][onDidChangeVisibleTextEditors] Repository for editor resource /Users/marco.brito/dev/personio-web/apps/attendance/frontend/src/pages/AttendancePage/AttendancePageUnconnected.tsx already exists: /Users/marco.brito/dev/personio-web
2024-08-20 10:24:48.246 [trace] [OperationManager][start] Show (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:48.248 [trace] [OperationManager][start] GetObjectDetails (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:48.327 [info] > git ls-files --stage -- /Users/marco.brito/dev/personio-web/apps/attendance/frontend/src/pages/AttendancePage/AttendancePageUnconnected.tsx [79ms]
2024-08-20 10:24:48.351 [info] > git show --textconv :apps/attendance/frontend/src/pages/AttendancePage/AttendancePageUnconnected.tsx [105ms]
2024-08-20 10:24:48.352 [trace] [OperationManager][end] Show (blocking: false, readOnly: true; retry: false; showProgress: false)
2024-08-20 10:24:48.396 [info] > git cat-file -s 37ca57871c3b733db2f0adbf88ea3d5597069214 [68ms]
2024-08-20 10:24:48.396 [trace] [OperationManager][end] GetObjectDetails (blocking: false, readOnly: true; retry: false; showProgress: false)

I've tried it with the Insider version, which worked for some time (couple of hours), then the same problem.

**Comment by lszomoru** [comment] 2024-08-20 13:32
While I review the logs, could you check if setting `typescript.tsserver.experimental.useVsCodeWatcher` to `false` in settings and restarting VS Code helps? Thanks!

**Comment by MarcoB-Personio** [comment] 2024-08-20 17:43
@lszomoru thank you so much for getting back to it so quickly! I have added the change and initially seems to work, however I'd like to try it for more time (like a whole day). I can later come back to you, if that is ok. :)

**Comment by MarcoB-Personio** [comment] 2024-08-21 14:51
@lszomoru I've used it for almost 10 hrs, and it seems to keep working as normal. Curious to know what you found on the logs I shared, and if this is a temporal fix or something that is gonna be fixed in the future for all VS code users having this issues?
Thanks agains for the support!

**Comment by lszomoru** [comment] 2024-08-25 19:34
Glad to hear that toggling the setting resolved the issue. Looking at the logs I can confirm that the git extension never receives the file system event that would trigger the refresh of the "Source Control" view. Closing this issue as a duplicate of https://github.com/microsoft/vscode/issues/222098.

**Closed by lszomoru** 2024-08-25 19:34 UTC
