### ISSUE TITLE
Terminal view in vscode.dev not rendering correctly in German

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode#185158] opened 2023-06-14 19:56 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.79.1
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:07:39.228Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

The experience added to the terminal view in vscode.dev and github.dev seems to be broken when changing the language to German.

Steps to Reproduce:

1. Go to `https://vscode.dev/github/microsoft/vscode`
2. Execute command `Terminal: Focus on Terminal View`
3. You should see this:
<img width="1165" alt="Screenshot 2023-06-14 at 12 51 35 PM" src="https://github.com/microsoft/vscode/assets/48293249/805fdc78-991b-444a-a24a-f75318c98bfd">
4. Execute command `Configure Display Langauge`
5. Change language to `Deutsch`
6. The terminal experience is sort of broken and you see this:
<img width="1140" alt="Screenshot 2023-06-14 at 12 51 26 PM" src="https://github.com/microsoft/vscode/assets/48293249/907bab74-836c-4ddb-84a1-9ab323113737">

**Comment by meganrogge** [comment] 2023-06-15 15:39
I think the issue is `command` is getting translated here

**Comment by TylerLeonhardt** [comment] 2023-06-15 15:49
The string needs to include some lock comments to make sure they don't get translated 👍

**Comment by lramos15** [comment] 2023-06-29 16:34
I'm still seeing this on insiders.vscode.dev. Has all this been deployed?

**Comment by TylerLeonhardt** [comment] 2023-06-29 16:52
It'll take some time for the translation to flow. I'll close this and mark it for July for verification

**Closed** 2023-06-29 16:52 UTC
Labels: bug, verification-found
