### ISSUE TITLE
Mac: After update of VS Code, app wont start - endless error loop.

### ISSUE THREAD

**Issue by ajsondev** [Microsoft/vscode#19104] opened 2017-01-24 04:16 UTC
Greetings.

I had VS Code working fine on Mac.
On starting today it informed me of update, it also advised me to install one of the top rated  python parsers - I allowed it to go ahead.
Download is of: 'VSCode-darwin-stable', file size 53.5mb.
After install, it asked for a restart of the app.
I allowed this.
On restart, it gave an error dialog - both dialog options, on clicking, result in the application simply crashing out. [See this tweet for screenshot](https://twitter.com/ajsondev/status/823472623661117441)
I have tried uninstalling/reinstalling - same thing happens.
I assume therefore that there is some left over config/settings somewhere that need to be cleaned out to allow it to start cleanly again ... can you direct you direct to where this can be done?

cheers.

**Comment by mousetraps** [comment] 2017-01-24 19:23
Oh no! That's no good - try also clearing `/Users/<user-name>/Library/Application Support/Code`

**Comment by mousetraps** [comment] 2017-01-24 21:38
Also, another couple ideas to try:
1. try running w/ `code --disable-extensions`
2. run w/ `code --verbose`, which produce some error to help us narrow down the issue

fyi @joaomoreno

**Comment by jonand** [comment] 2017-01-26 10:30
I'm running Sierra and Code worked fine yesterday. Today it wouldn't start, it just silently closed before showing the GUI. I had not updated Code.

- Updating Code didn't work
- Launching Code from `~\Downloads` or moving it from `\Applications` to `~\Applications` didn't work
- I couldn't launch code from terminal since I had not installed the shell plugin and couldn't launch code to install it
- Moving `/Users/<user-name>/Library/Application Support/Code` did work

I launched Code, installed the shell plugin, exited code, moved the `Code` folder back to `Application Support` and ran `code --verbose`. It wouldn't launch and I got the message:

    [48891:0126/110511:WARNING:dns_config_service_posix.cc(152)] dns_config has unhandled options!
    Startup error: Error: ENOENT: no such file or directory, stat '/Users/<user-name>/Library/Application Support/Code/User'

**Comment by joaomoreno** [comment] 2017-01-26 12:55
Does it really say `<user-name>` there, or did you change it for privacy issues?

**Comment by jonand** [comment] 2017-01-26 13:17
@joaomoreno I changed it. Not so much due to privacy, mostly to be consistent with @mousetraps.

**Comment by joaomoreno** [comment] 2017-01-26 13:27
And the folder does exist? `'/Users/<user-name>/Library/Application Support/Code/User'`

**Comment by jonand** [comment] 2017-01-26 14:53
It's hard to verify at this point since I don't have the old broken `Code` folder any more. But I do have vague memories of attempting to synchronize my code settings using Dropbox and symlinks a long time ago. This could very well have caused my problems which would make my problem unrelated to @ajsondevs problem. I have not tampered with my dropbox nor my VScode settings recently so the question is why this would cause problems now?

**Comment by joaomoreno** [comment] 2017-01-26 15:01
I just realised you are not the original poster. Glad to know it's fixed for you.

@ajsondev Let us know how this turned out for you.

**Comment by ajsondev** [comment] 2017-01-26 17:01
@joao ...Still the same, however I'm dropping it as killing my Mac this
weekend for a nix/windows dual boot laptop....

**Comment by r3nya** [comment] 2017-01-30 22:52
Hey mates!

Unfortunately, I can't run vscode too. :(

```
~ » code -v
1.8.1
ee428b0eead68bf0fb99ab5fdc4439be227b6281
~ » code --verbose --disable-extensions
[main 01:51:07] Sending env to running instance...
[main 01:51:07] Sent env to running instance. Terminating...
```

OS: macOS Sierra 10.12.3

PS: I tried to remove `'/Users/<user-name>/Library/Application Support/Code/User'` directly.

**Comment by r3nya** [comment] 2017-01-30 23:37
So … I fixed the problem. I found a lot of `Code Helper` zombie processes … After this I killed it and now everything is ok! :)

**Comment by joaomoreno** [comment] 2017-01-31 08:30
Closing.

**Closed by joaomoreno** 2017-01-31 08:30 UTC
Labels: needs more info

**Comment by rshkv** [comment] 2017-06-27 12:17
@joaomoreno Killing `Code Helper` zombies in activity monitor didn't do it for me. I had to look at `ps` and kill by process id.

I'm not sure how to reproduce, I ran Code from inside tmux and logged out of my computer. When I came back the session was detached and Code wouldn't start, instead giving me:
```
[66626:0627/130156.564538:WARNING:dns_config_service_posix.cc(152)] dns_config has unhandled options!
[main 13:01:56] Sending env to running instance...
[main 13:01:56] Sent env to running instance. Terminating...
```
