### ISSUE TITLE
NVDA And JAWS Get Very Sluggish When Text Has Very Long Lines

### ISSUE THREAD

**Issue by jhomme** [microsoft/vscode#101715] opened 2020-07-04 13:10 UTC
Issue Type: <b>Bug</b>

1. Create a Markdown file with several long paragraphs with JAWS or NVDA. 
2. Writing in VS Code becomes very sluggish on my machine and the fan starts to run.

Note: I was able to cure this problem by using the Rewrap extension. When I wrapped my Markdown file with it, I could edit with no difficulty.

VS Code version: Code - Insiders 1.47.0-insider (376d9d9d785ccca128fdbb16f001446d0ad64d32, 2020-07-03T10:27:06.804Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2397)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (4.14GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
author-stats|ada|1.0.1
Bookmarks|ale|11.3.1
spellright|ban|3.0.50
json-tree-view|Cha|2.6.0
vscode-markdownlint|Dav|0.36.1
vscode-pandoc|Dou|0.0.8
vscode-hugo-snippets|fiv|0.4.1
readabilitycheck|jem|1.3.0
markdown-shortcuts|mdi|0.12.0
python|ms-|2020.6.91350
vscode-hugo|rus|0.24.0
rewrap|stk|1.12.0
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by isidorn** [comment] 2020-07-27 09:28
This is a chrome issue, captured by https://bugs.chromium.org/p/chromium/issues/detail?id=1001591&q=10000%20chars&can=2
Closing this as duplicate of https://github.com/microsoft/vscode/issues/96153 and some other issues we have

**Closed by isidorn** 2020-07-27 09:28 UTC
