### ISSUE TITLE
Configure foreground match count in Find/Replace widget

### ISSUE THREAD

**Issue by jx22** [microsoft/vscode#76350] opened 2019-06-29 20:03 UTC
VS Code version: 1.35.1

Your operating system: Mac OS 10.14.6 Beta (18G48f)

List of extensions that you have installed: Advanced New File, C/C++, Color Highlight, Python, SpellChecker, Studio Icons, Word Count

Reproducible steps (1... 2... 3...) that cause the issue:
1) Create new file
2) Open settings.json and set "editor.foreground" to some high-contrast color. I'll use #3daef3 as an example
3) Enter some string of text into the editor. I'll use "code" for example
4) Open Find/Replace
5) Type "code" into the Find/Replace search box
6) Observe that foreground of the "1 of 1" text to the right of the search box in Find/Replace uses #3daef3 as foreground

What you expected to see, versus what you actually saw: I expected to find a setting that would let me change the foreground color of the "1 of 1" text — or any other permutation of search results/match counts in a file other than "No Results" — to something other than the editor.foreground color. But I could not find anything along those lines. I checked to see if there was an editorWidget.foreground setting just as there is an editorWidget.background setting. But there does not seem to be such an option. It would be nice to be able to customize this element of the Find/Replace widget in order to further enhance color themes.

Images, animations, or a link to a video showing the issue occurring:
![Screen Shot 2019-06-29 at 12 34 01 PM](https://user-images.githubusercontent.com/14957748/60388893-0a834a80-9a6d-11e9-97ec-130861228c07.png)

A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally
"editor.foreground": "#3daef3",

Thanks!

**Comment by jx22** [comment] 2019-06-29 20:15
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Not possible to explicitly change the foreground text color for widgets (#76274)](https://www.github.com/microsoft/vscode/issues/76274)

Thanks for flagging that issue, vscodebot! And thank you @mkanet -- yours and mine are very similar but slightly different. That one points to instances of "No Results," whereas mine points to instances in which there are matches to text entered in the search box within the Find/Replace widget. However, we both propose the same solution, which is to expose an editorWidget.foreground setting option.

**Comment by mkanet** [comment] 2019-06-30 03:31
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> Not possible to explicitly change the foreground text color for widgets (#76274)
> 
> 
> Thanks for flagging that issue, vscodebot! And thank you @mkanet -- yours and mine are very similar but slightly different. That one points to instances of "No Results," whereas mine points to instances in which there are matches to text entered in the search box within the Find/Replace widget. However, we both propose the same solution, which is to expose an editorWidget.foreground setting option.

@jx22 It's good to know that I'm not the only person to notice this.  Hopefully, we'll see an editorWidget.foreground setting option in the not-so-distant future.

**Comment by roblourens** [comment] 2019-07-01 00:46
I will call this a dupe of https://github.com/microsoft/vscode/issues/76274 because I think that any solution to that one would cover this as well.

**Closed by roblourens** 2019-07-01 00:46 UTC
Labels: editor-find
