### ISSUE TITLE
[Error] ENOENT: no such file or directory, lstat 'C:\d'

### ISSUE THREAD

**Issue by netjune** [Microsoft/vscode#10281] opened 2016-08-08 01:56 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Yestoday I add a directory and use the git in vscode. Everything was OK.
2. Today vscode reports this error after it is launched everytime.

**Comment by netjune** [comment] 2016-08-08 01:58
And the git panel just shows a progress bar looping forever.

**Comment by joaomoreno** [comment] 2016-08-08 12:15
Which folder do you have open in VS Code?

**Comment by netjune** [comment] 2016-08-09 00:54
The only folder opened in VS Code was D:\stm8\iar1 with about 10 files in it.

git commands is in c:\msys64\usr\bin\.

**Comment by netjune** [comment] 2016-08-09 00:55
I added  c:\msys64\usr\bin to system PATH.

**Comment by joaomoreno** [comment] 2016-08-09 07:51
Can you show me a screenshot of the error?

**Comment by netjune** [comment] 2016-08-10 00:45
![vscode_error2](https://cloud.githubusercontent.com/assets/17109782/17538312/cc643c66-5ed6-11e6-94ef-7313ab07f4a0.png)



![vscode_error](https://cloud.githubusercontent.com/assets/17109782/17538241/410f2856-5ed6-11e6-8633-352cac08cd6c.png)

**Comment by netjune** [comment] 2016-08-10 01:01
No git process in task manager then.

**Comment by joaomoreno** [comment] 2016-08-10 09:18
Do you have any extensions installed?

**Comment by netjune** [comment] 2016-08-10 15:08
I have only installed the following two extensions:
(1) c/c++ (0.8.1)
(2) Toggle Header/Source (0.1.2)

**Comment by joaomoreno** [comment] 2016-08-10 16:23
And do you get the same error when running `code --disable-extensions`?

**Comment by netjune** [comment] 2016-08-11 10:44
Yes. The same error even after I uninstall the two extensions.

**Comment by joaomoreno** [comment] 2016-08-11 12:53
@bpasero There seems to be some confusion in which the user's workspace (`D:\stm8\iar1`) seems to be parsed in some way to make FS calls into `C:\d`... any idea?

**Comment by bpasero** [comment] 2016-08-11 13:53
@netjune would you be able to run vs code out of its sources so that we can do some instrumentation in the places where we call lstat?

@joaomoreno I do not understand where we call lstat in the renderer that could produce such a message, a quick search I could not find such.

**Comment by joaomoreno** [comment] 2016-08-11 14:51
Yes that beats me too. But errors from the ext host and shared proc both get propagated back, so it could come from anywhere.

**Comment by bpasero** [comment] 2016-08-11 15:26
@netjune can you also open the developer console (from help menu) to see if something gets logged?

**Comment by netjune** [comment] 2016-08-13 05:14
> @netjune would you be able to run vs code out of its sources so that we can do some instrumentation in the places where we call lstat?
I don't have enough time to try this now.

> @netjune can you also open the developer console (from help menu) to see if something gets logged?
![vscode_error3](https://cloud.githubusercontent.com/assets/17109782/17641557/ca6b8210-6157-11e6-9f17-ea373315e993.png)

**Comment by bpasero** [comment] 2016-08-13 06:56
@joaomoreno funky, looks like gitApp.js???

**Comment by joaomoreno** [comment] 2016-08-15 09:25
@netjune What git version do you have installed?

**Comment by netjune** [comment] 2016-08-16 04:57
git version: 2.8.2

**Comment by joaomoreno** [comment] 2016-08-16 05:26
Can you try opening another folder? Maybe one inside `C:`? Do you get the same error?

**Comment by netjune** [comment] 2016-08-22 00:55
> Can you try opening another folder? Maybe one inside C:? Do you get the same error?

ENOENT: no such file or directory, lstat 'C:\c'

**Comment by joaomoreno** [comment] 2016-08-22 06:09
Which folder did you try to open?

**Comment by netjune** [comment] 2016-08-22 12:53
C:\ti\0730

**Comment by joaomoreno** [comment] 2016-08-22 13:12
Can you open some folder in your User home? For example `C:\Users\joao\Desktop`?

**Comment by netjune** [comment] 2016-08-23 00:46
> Can you open some folder in your User home? For example C:\Users\joao\Desktop?

ENOENT: no such file or directory, lstat 'C:\d'

**Comment by joaomoreno** [comment] 2016-08-23 05:59
Does it reproduce with the [latest Insiders release](http://code.visualstudio.com/insiders)?

**Comment by netjune** [comment] 2016-08-27 04:13
> Does it reproduce with the latest Insiders release?
No. Same error as 1.4.0.

**Comment by joaomoreno** [comment] 2016-08-29 08:10
Do you have another machine you can try VS Code on?

I have a feeling your machine has a very strange setup somehow.

**Comment by netjune** [comment] 2016-08-31 00:59
Yes, I use git in command line everyday. And git works well  in visual studio 2015. Both on the same computer.

Maybe it is because I installed vscode of a new version upon a very old version. But I have removed and reinstalled it then, and it didn't help.

How to remove vscode cleanly?

**Comment by joaomoreno** [comment] 2016-08-31 06:08
Run the uninstaller, then also check for Visual Studio Code folders in `%APPDATA%`. And in your home directory, check for `.vscode-*` folders.

**Comment by joaomoreno** [comment] 2016-08-31 06:09
Also are you willing to do a live screen sharing chat where we can debug this together?

**Comment by netjune** [comment] 2016-09-01 01:00
> Run the uninstaller, then also check for Visual Studio Code folders in %APPDATA%. And in your home directory, check for .vscode-* folders.

I just found "Code - Insiders" in %APPDATA% and delete it. No .vscode-* in my home directory.
Then I reinstalled vscode and the error is the same.

**Comment by netjune** [comment] 2016-09-01 01:01
> Also are you willing to do a live screen sharing chat where we can debug this together?

Yes. Then what should I do?

**Comment by joaomoreno** [comment] 2016-09-01 06:24
Let me know your availability and I'll see when I can fit. We'll set up a time and I'll send you a conference call link.

**Comment by netjune** [comment] 2016-09-05 11:01
Too busy the last saveral days. Sorry for the delayed reply.
I am available the the next 1~2 hours today. What about you?

**Comment by joaomoreno** [comment] 2016-09-05 12:14
Me too: https://hangouts.google.com/hangouts/_/joaomoreno.com/vscode10281

**Comment by joaomoreno** [comment] 2016-09-05 12:28
I saw you joined by left right after.

**Comment by netjune** [comment] 2016-09-05 12:43
Network problem. Google is hardly accessed in Chinese.

**Comment by netjune** [comment] 2016-09-05 12:46
Maybe I can make a screencast, and upload it to some place like www.youku.com. Is it usefull?

**Comment by joaomoreno** [comment] 2016-09-05 12:51
Please, yes.

**Comment by netjune** [comment] 2016-09-06 00:42
Finally upload the screencast here: https://drive.google.com/file/d/0B3c99U0nm3QXUjJJaEU4TkJLbWM/view?usp=sharing

**Comment by netjune** [comment] 2016-09-06 01:27
I can create a git repo and use git functions for the first time.
After reopenning the git repo folder, git functions are abnormal in vscode.

screencast: https://drive.google.com/file/d/0B3c99U0nm3QXcUtXUmZzWlV2Qjg/view?usp=sharing

Maybe vscode lost something of the project(folder) between saving and loading it?

**Comment by joaomoreno** [comment] 2016-09-06 09:29
Can you search your whole machine for all `git.exe` files? Maybe you have more than one git installed. What are the ones you find?

**Comment by netjune** [comment] 2016-09-06 10:01
I searched my whole machine and found 2.
C:\msys64\usr\bin\git.exe
C:\msys64\usr\lib\git-core\git.exe

I compared the two files. They have the same content.

**Comment by netjune** [comment] 2016-09-06 10:12
In vscode, a new git repo can be created, and all git functions work well BEFORE reopenning the same git repo folder.  

When git function is not usable, I can close the current folder and create another git repo in the same vscode instance.

So git.exe can be found and properly used by vscode.

**Comment by joaomoreno** [comment] 2016-09-06 14:33
Hm... Can you try using the [official git release](https://git-scm.com/) and see whether it reproduces there? We don't support msys git.

**Comment by joaomoreno** [comment] 2016-09-29 14:19
@tapir Can you try with the official git instead of msys, which we don't support?

**Comment by tapir** [comment] 2016-09-29 14:47
@joaomoreno I'll do one better.
I've tried with the official git.exe by appointing the git.path to "C:\\Program Files\\Git\bin\git.exe" and it worked. Then I copied the mingw-w64 git.exe over to "C:\\Program Files\\Git\bin\git.exe", restarted VSCode and it still worked! So the problem is somehow with the path it self. Not the exe. For some reson it just doesn't like "C:\\msys64\\usr\\bin\\git.exe"

**Comment by joaomoreno** [comment] 2016-09-29 15:49
Might be much more than that since git uses many other tools that live in that path.

Closing as we don't support msys git.

**Comment by tapir** [comment] 2016-09-29 16:00
I don't know what you mean. This is a VScode bug. Not MSYS2.
What if I were to install official Git in C:\msys64 ? Because that's what I just did and it doesn't work.

I also copied mingw git.exe to any other path and again it worked. So it's not the git it self. It only happend when it's in msys64. And if some other thing in that path make it not work that's VSCode's bug because VSCode should only use git.exe and nothing else.

**Comment by tapir** [comment] 2016-09-29 16:01
Also please stop with "we don't support msys git" thing. MSYS2 is the major player when it comes to C/C++ in Windows after Visual Studio. Not supporting it is not a great idea.

**Comment by joaomoreno** [comment] 2016-09-29 19:54
Reopening due to:

> What if I were to install official Git in C:\msys64 ? Because that's what I just did and it doesn't work.

I will install it in that path to confirm this.

We don't support msys git. But you are free to contribute a PR which makes it work.

**Comment by tapir** [comment] 2016-09-29 19:58
If there is anything to support I will make a PR. But I really don't understand what you mean by that? How do you think both executables behave differently? To my understanding they work exactly the same way.

Also why should VSCode care about where the exe comes from? 
It all seems pretty straight-forward to me. We have a "git.exe". Regardless of where it comes from  if it works on terminal, it should work with VSCode.

**Comment by joaomoreno** [comment] 2016-09-29 20:02
I could not reproduce:

![image](https://cloud.githubusercontent.com/assets/22350/18970027/f17fc2fa-868f-11e6-99ac-d8d0c776d72a.png)

So it obviously doesn't have to do with _where the exe comes from_.

It is my understanding that they work the same way too. But clearly they don't. So someone needs to look into it. Since I don't even estimate 0.01% of our users using this version of git, I don't think it is wise to dedicate my time for it.

Let's track that here: #13037

**Closed by joaomoreno** 2016-09-29 20:02 UTC
Labels: bug

**Comment by ItachiSan** [comment] 2016-11-09 13:28
I have also this bug, but the git binary is the one bundled inside MSYS2.

**Comment by pthalacker** [comment] 2016-11-15 20:33
I just opened Code and am experiencing exactly the same problem.

**Comment by at15** [comment] 2016-11-25 19:21
if you just don't want see the annoying warning and don't need the to use git inside vscode, just disable it.
````
// Place your settings in this file to overwrite the default settings
{
    "git.enabled": false
}
````
Also change `git.path` may also help, but I never find the git integration very useful (just personal taste) so I didn't give it a try.
 
And VSCode does not have any problem with both the old (msysgit) and new git for windows, which is a fork of msys2, and that's why they can't reproduce it. When you use the original [msys2](http://msys2.github.io/) and install git with pacman, VSCode will have trouble with git.

And if you just want to use git on windows, stick with git for windows, it has more friendly default settings and works well with most editor and IDEs, while for the raw msys2, sometimes you mess up with PATH and other environment variables.

**Comment by cjun714** [comment] 2016-12-23 17:05
I think vscode(or its dependant lib) has issue on handling code path, when using git from msys2 or cygwin.
For example:
1. When project path is  Z:\proj,  and
2. git.exe in D:\tool\msys64\bin,
vscode will apear error of "ENOENT: no such file or directory, lstat 'D:\z'"

mklink /j "D:\z" z:  can resolve this, and then any other projects in z:\  or sub directory in z:\ like z:\projects\proj1 will also benefit.

But if project path is in other partition, like E:\porj, issue will apear again:"ENOENT: no such file or directory, lstat 'D:\e'"
mklink /j "D:\e" e:  can resolve this.

Hope it can be fixed soon, why:
1. It has been reported again and again by msys2 and cygwin users.
2. Lots of them use Sublime/Emacs based on msys and cygwin to create cross platform web/c++/go/rust projects, they use package manager like pacman in msys2 to install(or update) mingw+clang+gdb+lldb+git+make, which support VCS greatly if they can keep consistent.
3. Git for window includes another mingw, also is not inclueded in msys/cygwin toolchain or shell PATH.
4. Sublime/Eclipse and its git plugins work well on both msys git or window git, it's not a Git issue, its an editor issue.

**Comment by jamesqo** [comment] 2016-12-25 03:11
I was also experiencing this issue! `lstat C:\home: No such file or directory` would constantly pop up in the top of the editor window, and would reappear whenever I closed it. (I, as well, use Git for Windows/msysgit.) I ended up following @at15's advice and disabled git within vscode.

**Comment by joaomoreno** [comment] 2017-01-03 09:00
Does this help anyone? #4651

**Comment by rdcoe** [comment] 2017-01-10 18:56
Have the same bug and I don't use msysgit, I use cygwin64.  If I have open in vscode my c:\cygwin64\home\...\git folder and then restart vscode, I will, after several seconds of waiting, see the ENOENT: no such file or directory, lstat 'C:\home' error.

If I click on the "collapse" icon for the folder, I will see the same error message.
If I click on the Git icon on the left of vscode, I get the same error.

**Comment by joaomoreno** [comment] 2017-01-11 06:44
Cygwin is not yet supported #7998

**Comment by malluri19** [comment] 2017-01-18 21:36
Make sure that the .json file doesnt have a path to an invalid directory under files:

I had path pointing to 
                  "path": "scripts", "addressable": true
                  "path": "sdk/scripts", "addressable": true

which I copy/pasted from a tutoria.
In fact I do not have Scripts folder under Home. Removing it packaged the project without errors.

It took some time to figure out, but the error description states what is missing. Please read it clearly and you can resolve on your own.

**Comment by masaeedu** [comment] 2017-02-25 11:02
@joaomoreno #4651 solves it for me, might want to stick it somewhere in the official docs where crawlers will find it.

**Comment by bviktor** [comment] 2017-04-20 18:54
I'd like to add a few points.

1) I'm pretty sure that "I don't know, therefore msysgit" is not the proper approach to this issue.

2) This error is reproducible with zero Git involved. To me it occurs with `go build`.

Steps to reproduce:

1) Get a VM image for win10 15.15063 from [modern.ie](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)

2) start it up, install updates, restart

3) install vs code with defaults

4) install [go runtime ](https://golang.org/dl/) with defaults

5) start vs code

6) install go extension, restart vs code

7) create a new .go file:

~~~
package main
import "fmt"
func main() {
	fmt.Println("foobar")
}
~~~

8) ctrl+f5

Expected output: `foobar` printed

Actual output: 

~~~
The program "${file}" does not exist: Error: ENOENT: no such file or directory, lstat 'C:\Program Files (x86)\Microsoft VS Code\${file}'
~~~

**Comment by joaomoreno** [comment] 2017-04-21 06:38
@bviktor This user's issue was indeed related to git. You have another issue, so can you please open a new issue? Ping me in it please.

**Comment by bviktor** [comment] 2017-04-21 12:00
Alright, #25138 opened.
