### ISSUE TITLE
View is flickering when scrolling

### ISSUE THREAD

**Issue by daB0bby** [Microsoft/vscode#25941] opened 2017-05-04 22:35 UTC
- VSCode Version: 1.12
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Open  Code
2. Start scrolling

The complete view is flickering when scrolling. 
Happens since the update to 1.12

**Comment by jrnail23** [comment] 2017-05-04 22:38
possibly related to #25934

**Comment by kieferrm** [comment] 2017-05-04 22:42
@daB0bby do you start code with `--disable-gpu` ?

**Comment by kieferrm** [comment] 2017-05-04 23:07
Duplicate of #25934.

**Closed by kieferrm** 2017-05-04 23:07 UTC
