### ISSUE TITLE
@supports (-ms-ime-align:auto) at-rule or selector expected

### ISSUE THREAD

**Issue by jcperez-ch** [Microsoft/vscode#23306] opened 2017-03-27 19:41 UTC
![screen shot 2017-03-27 at 3 37 19 pm](https://cloud.githubusercontent.com/assets/439618/24374619/8573e414-1303-11e7-91f0-1441a613ffab.png)

- VSCode Version: 1.10.2
- OS Version: MacOS Sierra 10.12.3

Not sure if this is the best way to target only edge features, but at least vscode less linting complains about it.  Not a less issue, since my lessc command works fine.

**Comment by aeschli** [comment] 2017-03-28 09:33
duplicate of #1505

**Closed by aeschli** 2017-03-28 09:33 UTC
Labels: css-less-sass
