### ISSUE TITLE
`import React` removed when saving TSX file (when source.organizeImports is enabled)

### ISSUE THREAD

**Issue by yanghuanrong** [microsoft/vscode#152150] opened 2022-06-15 06:24 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Code 1.68.0   
- OS Version: win10

Steps to Reproduce:

Hi,

If I enable `source.organizeImports` in my `settings.json` like so:
```
{
    "[typescript][typescriptreact]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }
}
```
Then on save, VS Code will automatically remove the React import line from files like this TSX file, even though importing React is required for JSX/TSX files:

```
import React from 'react'; // This line gets removed on file save
function App() {
  return (
    <div className="app"></div>
  );
}
```  
export default App;
For large JSX files, this is especially apparent because ESLint will output a plethora of "'React' must be in scope when using JSX" errors.
![image](https://user-images.githubusercontent.com/18067120/173756700-defa121f-96ed-4298-9a86-4b183e57d8ac.png)
Naturally, the only way to get the React import to stick is to reference something like React.memo or React.MouseEvent in my code, although this is not ideal.

```
import React from 'react'; // This no longer gets removed on file save

const App = React.memo(() => {
  return (
    <div className="app"></div>
  );
});
```
export default App;
I believe this behavior to be the result of the 1.68.0 release, since I only started experiencing this issue a day or two ago, and the 1.68 release made some changes to organizeImports (per the release notes).

I tried digging into the settings and reading online—it doesn't seem that the source.organizeImports setting is very configurable beyond specifying which language mode(s) it applies to. I have already searched open issues, disabled all my extensions, and tried the Insider build, to no avail in any case.

Can someone please confirm if this is a 1.68 bug, and if there are any workarounds in the interim?

**Comment by IllusionMH** [comment] 2022-06-15 08:46
This looks like duplicate of #152018

And in this case depends on `jsx` setting in `tsconfig.json`/`jsconfig.json`

**Comment by suprsidr** [comment] 2022-06-15 14:50
This is happening in .js files as well. Just started since last update.
same as this thread which is locked
https://github.com/microsoft/vscode/issues/47287

I have "jsx": "react", in compilerOptions in tsconfig and jsconfig seems to be ignored

**Comment by suprsidr** [comment] 2022-06-15 16:22
my jsconfig.json:
```{
  "compilerOptions": {
    "target": "ES2018",
    "allowJs": true,
    "checkJs": true,
    "jsx": "react"
  }
}```

**Comment by IllusionMH** [comment] 2022-06-15 17:00
> The tsconfig from create-react-app had...

If it's recent version I think it was already configured to use new JSX emit that doesn't require explicit import and it can be safely removed.

Import is needed for old react versions (<16.8) or if babel configured to emit old `React.createElement`

**Comment by mjbvz** [comment] 2022-06-15 21:29
Reopening to track changing VS Code's default `jsx` setting for June

**Closed** 2022-06-15 21:41 UTC
Labels: bug

**Comment by Norcy** [comment] 2022-06-16 09:14
Same problem

Adding ``jsconfig.json` in my project root directory can solve it

```js
{
  "compilerOptions": {
    "jsx": "react",
  }
}
```
