### ISSUE TITLE
Recent folders are not displayed.

### ISSUE THREAD

**Issue by viclunam** [microsoft/vscode#191267] opened 2023-08-24 23:42 UTC
Type: <b>Bug</b>

Recent folders are not displayed when clicking on the "More" option.

but if you use the default shortcut in MacOs (^r) it does show the list of recent folders.

<img width="339" alt="image" src="https://github.com/microsoft/vscode/assets/98234382/a2ef5a10-7961-4321-a41a-7b013d00cc02">

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 6, 7|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 7f577b2e-5722-44ee-b8d2-aeb2f44365e9|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by bhavyaus** [comment] 2023-08-29 17:10
I'm unable to repro this on insiders.

**Comment by viclunam** [comment] 2023-09-01 17:44
@bhavyaus How can I help you to repoduce the error, I searched all the logs of the OUTPUT panel, without finding any error.

**Comment by bhavyaus** [comment] 2023-09-01 17:57
Could you please try it on the insiders build https://code.visualstudio.com/insiders ? Thank you.

**Comment by bhavyaus** [comment] 2023-12-19 22:14
I'm unable to reproduce this on the mac also. Closing this issue. Please reopen issue if you see this issue again.

**Closed by bhavyaus** 2023-12-19 22:14 UTC
Labels: bug, workbench-welcome
