### ISSUE TITLE
Online profile to backup your preferences and extensions

### ISSUE THREAD

**Issue by Kreshnik** [Microsoft/vscode#34492] opened 2017-09-15 19:08 UTC
One functionality which is missing throughout all code editors is the ability to backup / restore your preferences and extensions on different devices. 

It would be really helpful If users would have some kind of "vCode account" in which they could log into, and back up their preferences and extensions, and maybe also through a sync functionality do this automatically.

I am basically describing the standard sync functionality that Chrome and Firefox have. This would save sooo much time since you could switch devices and sync your editor's configuration with your last synced one, you'd have an up and running dev environment in minutes.

**Comment by dhekimian** [comment] 2017-09-15 20:53
@Kreshnik Is this what you're looking for? 

[Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)

**Comment by Kreshnik** [comment] 2017-09-15 23:05
@dhekimian indeed that is what I am looking for, however, this requires still external factors to be set (GitHub auth token). I am thinking more something native, build into VisualCode

**Comment by diminutivesloop** [comment] 2018-02-20 18:30
I too would appreciate a built-in solution. I've tried the aforementioned settings sync extension but it's been so buggy and unreliable that I've had to disable it.

**Comment by SmoshySmosh** [comment] 2018-04-11 18:33
👍 I would like to see a built-in solution as well.

**Comment by HRK44** [comment] 2018-08-28 14:51
Any updates on this? Some 'Sign-in via GitHub' or other OAuth authentifications to retrieve all our settings/extensions would be great.

**Comment by mjbvz** [comment] 2019-05-01 23:40
Duplicate of #2743

**Closed by mjbvz** 2019-05-01 23:40 UTC
Labels: config, feature-request
