### ISSUE TITLE
outdated extensions are hard to find

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9256] opened 2016-07-14 07:40 UTC
Everyday I get extensions that I need to update and that is very prominently indicated by the badge. Tho when I open the extensions viewlet I need to find them in the list of installed extensions which is painful. 

* either open filtered `@oudated` and only show outdated extension (ideally with a way to update them all)
* or sort outdated extensions to the top

![screen shot 2016-07-14 at 09 38 03](https://cloud.githubusercontent.com/assets/1794099/16831763/03263a14-49a7-11e6-8dd8-f1d722d0b1c8.png)

**Comment by bpasero** [comment] 2016-07-14 07:45
+1 for sorting to the top, maybe show a little separator between "up to date extensions" and "outdated extensions"?

**Comment by joaomoreno** [comment] 2016-08-26 08:27
I'll close this as duplicate of #8124, let me know if that's not enough.

**Closed by joaomoreno** 2016-08-26 08:27 UTC
Labels: bug

**Comment by jrieken** [comment] 2016-08-26 08:52
@joaomoreno Extensions should just update automatically.. Why do I have to press buttons all the time...
