### ISSUE TITLE
provideCompletionItems not invoked if inside Dockerfile string

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode#95924] opened 2020-04-22 21:53 UTC
- VSCode Version: VS Code 1.44.2
- OS Version: macOS Catalina 10.15.1

Steps to Reproduce:

1. Clone the https://github.com/Microsoft/vscode-extension-samples repository.
1. Open VS Code in the `completions-sample` folder.
1. Invoke `npm install` to install the relevant dependencies.
1. Open `src/extension.ts`.
1. Paste the provided TypeScript code below to overwrite `src/extension.ts`.
1. Launch the "Run Extension" config.
1. Create a `Dockerfile`.
1. Paste the Dockerfile content below into the file.
1. Follow the instructions in the file. If you look at the output in your original VS Code's instance "Debug Console", you will see that print statements only appear for two of the lines and not all three of the lines. I can reproduce a similar bug with Monaco.

```TypeScript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

	const provider = vscode.languages.registerCompletionItemProvider('dockerfile', {
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position) {
			console.log(`provideCompletionItems ${position.line}`);
			return [
			];
		}
	});

	context.subscriptions.push(provider);
}
```

```Dockerfile
# type on line 4, it works
# type on line 6, it fails
# type on line 7 after the apostrophe, it works

RUN \'e\'

'
```

<img width="644" alt="image" src="https://user-images.githubusercontent.com/15629116/80037628-f14aff00-84c1-11ea-83a3-e39aae00a8ea.png">

Does this issue occur when all extensions are disabled?:
Not sure since when I launch it just includes all my extensions anyway.

**Comment by rcjsuen** [comment] 2020-04-22 21:56
Opened microsoft/monaco-editor#1935 which is slightly different (probably because of the Monarch grammar)?

**Comment by jrieken** [comment] 2020-04-23 13:49
IntelliSense-as-you-type only works at word ends (I am assuming that's what you're trying, not pressing ctrl+space). What a word is depends on the word definition of the language, and a word is always smaller or equal to token. So, I'd say it is one of those two things not working here

**Comment by rcjsuen** [comment] 2020-04-23 13:51
> IntelliSense-as-you-type only works at word ends (I am assuming that's what you're trying, not pressing ctrl+space).

@jrieken Correct, I am typing into the editor. I am **not** manually invoking <kbd>Control</kbd>+<kbd>Space</kbd>.

**Comment by alexdima** [comment] 2020-04-27 08:59
@jrieken I think this is an issue for `suggest` since the code in `vs/editor/contrib/suggest/*` is triggering auto-completion. Is there some kind of core editor problem here?

**Comment by jrieken** [comment] 2020-04-27 12:48
>  Is there some kind of core editor problem here?

Maybe that or a problem with the grammar. On line 6 we detect being inside a string and quick suggestions is disabled inside strings (by default). 

<img width="555" alt="Screenshot 2020-04-27 at 14 44 16" src="https://user-images.githubusercontent.com/1794099/80373595-93d5fa00-8895-11ea-863e-6b303c5a0921.png">

**Comment by alexr00** [comment] 2020-04-27 14:02
Yes, the grammar is calling that a string. However, @rcjsuen why are you trying to escape those single quotes? I'm not sure that's valid outside of a string in a dockerfile.

**Comment by rcjsuen** [comment] 2020-04-27 14:17
> However, @rcjsuen why are you trying to escape that first single quote? I'm not sure that's valid outside of a string in a dockerfile.

@alexr00 If you are working with files that have an apostrophe in them, then you will need to escape them. Naturally, this depends on the shell being used for the Docker image.
```Dockerfile
FROM alpine
WORKDIR /tmp
COPY . .
RUN ls
RUN cat a\'.txt
RUN cat a'.txt
```
```
$ ls
Dockerfile  a'.txt

$ docker build --no-cache .
Sending build context to Docker daemon  38.15MB
Step 1/6 : FROM alpine
 ---> f70734b6a266
Step 2/6 : WORKDIR /tmp
 ---> Running in a9e1877e3cf2
Removing intermediate container a9e1877e3cf2
 ---> f6001e1415b1
Step 3/6 : COPY . .
 ---> 7a7394153d6d
Step 4/6 : RUN ls
 ---> Running in 60152d05e1ec
Dockerfile
a'.txt
Removing intermediate container 60152d05e1ec
 ---> 439dd2d72002
Step 5/6 : RUN cat a\'.txt
 ---> Running in b9af3dab198c
Hello, world!
Removing intermediate container b9af3dab198c
 ---> e9de662f7516
Step 6/6 : RUN cat a'.txt
 ---> Running in e5a1bd741de4
/bin/sh: syntax error: unterminated quoted string
The command '/bin/sh -c cat a'.txt' returned a non-zero code: 2
```

**Comment by alexr00** [comment] 2020-04-27 14:19
Makes sense! Then yes, this appears to be an issue with the dockerfile grammar.

**Comment by rcjsuen** [comment] 2020-04-27 14:27
@alexdima @jrieken Can I use semantic tokens to somehow workaround such grammar limitations?

Even if I highlight `a` as a keyword, it still think it's inside a string when the text caret is after the `a`.

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/15629116/80383426-8f97e580-8871-11ea-9268-2e4cec963764.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/15629116/80383272-5e1f1a00-8871-11ea-9962-dae288ae21aa.png">

**Comment by alexdima** [comment] 2020-04-27 19:20
@rcjsuen No, the token type `string` / `regex` / `comment` is driven always by the TM grammar. We have debated for some time to make that be overwritable by the semantic tokens, but since semantic tokens are async, it means that a certain character can be considered a `string` and after some unknown time, it can become a `comment`, etc. This might lead to unexpected end-user behavior, where something is typed the same way twice, but once it does something, and another time something else happens, etc... Long story short, we've decided to avoid that and let TM grammars own the embedded language id and the token type.

**Comment by rcjsuen** [comment] 2020-04-28 12:09
@alexdima Thank you for your information.

> > Is there some kind of core editor problem here?
> 
> Maybe that or a problem with the grammar. On line 6 we detect being inside a string and quick suggestions is disabled inside strings (by default).

@jrieken Is it possible to enable quick suggestions inside strings on a per-language basis?

**Comment by jrieken** [comment] 2020-04-28 12:12
> @jrieken Is it possible to enable quick suggestions inside strings on a per-language basis?

Sure - language specific default configs are the way to go here

**Comment by alexr00** [comment] 2020-04-28 13:37
For example
```
	"[dockerfile]": {
		"editor.quickSuggestions": {
			"strings": true
		}
	}
```
I've created an issue for the grammar: https://github.com/moby/moby/issues/40861
Since the problem is over there I'll close this issue and pick up any grammar fixes as they become available.

**Comment by alexr00** [comment] 2020-04-28 13:38
Actually, I'll put this as a default in the built in docker extension.

**Comment by rcjsuen** [comment] 2020-04-28 13:38
@alexr00 I was just about to post that JSON snippet. You were one step ahead of me. :P

**Closed** 2020-04-28 13:47 UTC
Labels: grammar, upstream-issue-linked
