### ISSUE TITLE
Column Selection by Middle Mouse Button (Sublime Style)

### ISSUE THREAD

**Issue by domske** [Microsoft/vscode#28186] opened 2017-06-07 14:53 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 10 Pro 64-bit

Currently column select is available by pressing `Alt + Shift + Mouse Left` to drag colum selection from current cursor position. Or by `Alt + Ctrl + Shift + Arrows` without the mouse. 

Nice feature, but horrible to use.
I think it would be better if the behaviour is the same like in sublime text or atom package: 
https://atom.io/packages/Sublime-Style-Column-Selection

Just press the middle mouse button (mouse wheel) to select from every position. 
The middle click also sets the start position (cursor) dynamically. 
Optional set other keys for example `Alt + Mouse Left`.

Look this clip: (Only controlled by the mouse middle button with the package (link above) in Atom.)
![columnselect](https://user-images.githubusercontent.com/28209992/26884862-174f2562-4ba1-11e7-8da7-c0f56baeea4b.gif)

**Comment by insin** [comment] 2017-06-09 08:51
Easy mouse selection of multiple cursors and Sublime's behaviour when you select off the right hand edge with Middle Click drag or Shift+Right Click drag are some of my most-missed features (works the same dragging upwards if the mouse is off to the right):

![2017-06-09_09-41-23](https://user-images.githubusercontent.com/226692/26967999-5335ed9c-4cf8-11e7-94bb-4bbf6dc34a16.gif)

Currently in VS Code (1.13.0) you have to place an initial cursor, then hold the hotkeys and drag, but it acts like a box anchored at the start point regardless of where the mouse is.

![2017-06-09_09-44-29](https://user-images.githubusercontent.com/226692/26968127-c39914d8-4cf8-11e7-96c3-f96da9e6364e.gif)

**Comment by jnm2** [comment] 2017-06-09 11:14
Yes! I've been wanting the same thing for months. I want to be able to `Alt` + left mouse drag a rectangle without being affected by the cursor position prior to starting the drag, just like in editors like Visual Studio or Notepad++ or even Word and Outlook.

**Comment by jnm2** [comment] 2017-06-09 11:16
Duplicate of https://github.com/Microsoft/vscode/issues/27916?

**Comment by jnm2** [comment] 2017-06-09 11:16
Duplicate of https://github.com/Microsoft/vscode/issues/5402?

**Comment by Dominik-Andreas-Geng** [comment] 2017-06-09 12:31
Yes it's seems like a duplicate. I overlooked that. But, in my option it's important to have options for the column selection like "select only by middle mouse button" or "select with alt + left mouse button". etc.

**Comment by mrksdiehl** [comment] 2017-12-18 16:53
Is there a chance that this is going to be added? I come from sublime and love the middle mouse over there. I really use it all the time. Would love to see it available in vscode.

**Closed** 2018-04-17 22:05 UTC
Labels: editor-columnselect, feature-request

**Comment by akinnee** [comment] 2018-05-21 20:52
Thank you so much for implementing this! ❤️
