### ISSUE TITLE
Update icons when language of file is changed

### ISSUE THREAD

**Issue by robertohuertasm** [Microsoft/vscode#11806] opened 2016-09-09 23:16 UTC
- VSCode Version: 1.5.0
- OS Version: W10

Steps to Reproduce:
FYI @aeschli 
1. I create a languageId association
   ![lang1](https://cloud.githubusercontent.com/assets/696981/18405623/d52b2438-76f3-11e6-9811-904dc3b7fcf7.PNG)
2. I can see the icon in my .js file but I decide to change the language to c#
   ![lang2](https://cloud.githubusercontent.com/assets/696981/18405628/e8b5f74e-76f3-11e6-88cd-ba785a149281.PNG)
3. I continue to see the js icon. Is this the expected behavior?

Finally, another question. How can I find the language contribution ids?

Thanks! :grinning:

**Comment by raztd** [comment] 2016-09-10 14:40
Something similar. I associated the .pl extension with Prolog in the User Settings
```json
"files.associations": {
        "*.pl": "prolog"
}
```

Now when I open a .pl file it shows "Prolog" in the status bar, but in file explorer still appears the Perl logo. 
I have the Prolog extension installed https://marketplace.visualstudio.com/items?itemName=rebornix.prolog

**Comment by aeschli** [comment] 2016-09-13 11:05
The language id for c# is `csharp`.
We have currently no list of all used language ids. We are also only in control of the ones we have a built-in extension.

@raztd Which icon theme?

**Comment by mrmlnc** [comment] 2016-09-13 11:13
@aeschli, we have a similar problem with Emmet in `emmet.syntaxProfiles`.  Please, see https://github.com/Microsoft/vscode/issues/11329#issuecomment-245029574. I think you need to discuss this problem with @egamma, because end users do not know the Language id's and how to get them.

**Comment by aeschli** [comment] 2016-09-13 14:06
I created https://github.com/Microsoft/vscode-docs/issues/572 for a table of language Ids.

Closing as the original issue is likely the wrong language id for csharp.

**Comment by robertohuertasm** [comment] 2016-09-13 14:12
@aeschli, this is not an issue with csharp id. My example may be misleading. Let's say I don't associate my .js file with C# but with php. I will continue to see the JS icon. Is this the expected behavior? Or should I see the default icon? I understood that the later would be the default but it's not working like that.

**Comment by aeschli** [comment] 2016-09-13 16:48
Ah , now I see, you change the editor association to C#.

@bpasero What's the expected behaviour here?

**Comment by bpasero** [comment] 2016-09-13 17:15
@robertohuertasm can you explain in words that I understand what you did and what you expect? preferably in a way that I can apply those steps to my test environment.

**Comment by robertohuertasm** [comment] 2016-09-13 17:37
1. I was testing the LanguageId associations so I associated certain icon "JS" to the JavaScript language.
2. This worked as expected and I got the "JS" icon.
3. Now I change the language of the file (which was previously associated to JavaScript) and I associate it to C#.
4. I'm expecting to see the "default blank icon" or the C# icon (in case the author has defined one) but I still see the "JS" icon.

My question is about step 4. What's the correct behavior? Show the blank icon in case no C# icon has been defined? Show the "JS" icon in case nothing is defined for C# (as it seems to be happening now)? 

Let me know if it's not clear enough.

**Comment by robertohuertasm** [comment] 2016-09-13 17:49
5. I've just check it out and even the C# icon would exists (implying that we have a LanguageId association between C# lang and a C# icon) if I change the language association of a "JS" file to C#, it will continue showing the "JS" icon.

6. By my last test, it seems that it's working as expected if I change the `file association` in the settings and reload the window. It's not working if I change the language mode
![capture](https://cloud.githubusercontent.com/assets/696981/18484996/38c465dc-79eb-11e6-9345-6d44889743c2.PNG)
 by using the lower right language option.

**Comment by bpasero** [comment] 2016-09-13 17:59
@robertohuertasm so the issue is basically that you expect the icons to update when you change the language of the file from the status bar?

**Comment by robertohuertasm** [comment] 2016-09-13 18:00
@bpasero yes, that's it.

**Comment by bpasero** [comment] 2016-09-13 18:04
Not implemented atm.

**Comment by raztd** [comment] 2016-09-15 14:26
@aeschli I use Seti icon theme

![prolog](https://cloud.githubusercontent.com/assets/6805609/18553531/712e0d0e-7b69-11e6-8426-026e03bf009a.png)

**Comment by bpasero** [comment] 2016-10-03 10:10
Pushed a change so that icons will update for the open editor at least. Making this work across all places is a bit more work due to missing events, but I think this change comes very close 👍

**Comment by bpasero** [comment] 2017-11-16 13:45
Seems to work now.

**Closed by bpasero** 2017-11-16 13:45 UTC
Labels: feature-request, workbench
