### ISSUE TITLE
formatting (Shift + Alt + F) stopped working the insiders build as of April 1, 2017 (no jokes)

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#23802] opened 2017-04-01 19:39 UTC
- VSCode Version: Code Insiders 
![image](https://cloud.githubusercontent.com/assets/937933/24581847/4df71064-16f1-11e7-975f-d2dfcac49a41.png)

- OS Version: Windows 10 insiders preview

Steps to Reproduce:

1. Get insiders build on April 1, 2017
2. Open TypeScript file
3. Try to format by running the `Format` command (Shift + Alt + F)
4. Observe nothing happens

**Comment by whitecolor** [comment] 2017-04-02 06:22
Yes, I can confirm that this, spend a lot time being testing what goes wrong. 

*Sh\*t happens* sometimes with vscode insiders.
BTW because of such problems I would return to the Idea of official way rolling back insiders release https://github.com/Microsoft/vscode/issues/11084

There just need to keep list of releases/commits and links for them to download.

I found that this link in some messages in the repo, at least it works:
https://az764295.vo.msecnd.net/insider/c995ecf2e94a00aa7eda81ed842e787b999e83ae/VSCodeSetup-1.11.0-insider.exe

**Comment by alexandrudima** [comment] 2017-04-03 07:28
@aleksey-bykov The problem could be in two independent places:
a) keyboard dispatching (i.e. shift+alt+f is not correctly triggering the format action on the language service)
b) the TypeScript language service cannot format in a specific case

To try to narrow in on the root cause, could you please open a JSON file that is unformatted and press `shift+alt+f`. Does `shift+alt+f` invoke the JSON format action?

**Comment by whitecolor** [comment] 2017-04-03 08:09
@aleksey-bykov Also there is a third case
c) VScode doesn't handle TS language service at should. 

In ts server logs (verbose) I see that requests are made and response are got but VSCode doen't apply formatting. As I said I have to rollback to previous build which work.

**Comment by mjbvz** [comment] 2017-04-05 22:02
@aleksey-bykov /@whitecolor  Do you see still see this in the latest insiders? If so, can you please share typescript server trace of the issue:

* Set `"typescript.tsserver.log": "verbose",`
* Restart VSCode and reproduce the issue
* Go to the output panel and share the output from the `TypeScript` section.

Thanks

**Comment by mjbvz** [comment] 2017-04-14 20:55
Closing as we need more information to investigate this. Please out try the latest vscode release and let me know if you still see this issue

**Closed by mjbvz** 2017-04-14 20:55 UTC
Labels: format, javascript, needs more info, typescript
