### ISSUE TITLE
 Data tree node not found: [object Object]

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#79182] opened 2019-08-15 08:07 UTC
Issue Id: <b>667c5f9a-5815-3747-e1b2-7a2a6b80d7c8</b><br /><br />*Versions* <br />- 1.38.0-insider (8/13/2019 7:19:46 AM)<br />*Stack* <br />Error: Data tree node not found: [object Object]<br />[/vs/base/browser/ui/tree/asyncDataTree.ts#638:9 (getDataNode)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/base/browser/ui/tree/asyncDataTree.ts#L638:9 (getDataNode))<br />[/vs/base/browser/ui/tree/asyncDataTree.ts#612:24 (reveal)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/base/browser/ui/tree/asyncDataTree.ts#L612:24 (reveal))<br />[/vs/workbench/contrib/files/browser/views/explorerView.ts#530:14](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L530:14)<br />    at Generator.next (<anonymous>)<br />[/vs/base/common/errors.ts#184:9](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/base/common/errors.ts#L184:9)<br />

**Comment by sbatten** [comment] 2019-08-15 08:08
@bpasero created while testing

**Comment by bpasero** [comment] 2019-08-15 08:34
This is still our number 1 crash.

**Comment by falsandtru** [comment] 2019-08-17 19:03
I got this error on 1.37.1 stable and this bug severely breaks TypeScript. Please fix and update soon.

```
[2019-08-18 03:39:10.051] [renderer1] [error] Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at X.getDataNode (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:978:433)
    at X.<anonymous> (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:976:765)
    at Generator.next (<anonymous>)
    at file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:35:237)
    at X.expand (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:976:532)
    at e.<anonymous> (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5553:500)
    at Generator.next (<anonymous>)
    at r (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:35:293)
```

**Comment by isidorn** [comment] 2019-08-19 12:50
@falsandtru this bug is unrelated to typescript.
Do you have reproducable steps. That would help greatly in order to get this fixed. Thanks

**Comment by falsandtru** [comment] 2019-08-20 10:13
I'll report it if I find. However, I can really find no other errors after restarting tsserver.

**Comment by isidorn** [comment] 2019-08-20 12:49
@joaomoreno I do not understand how this could happen.
We properly await the expansion of the folder so all the children are shwn [here](https://github.com/Microsoft/vscode/blob/ea7f62fa08586faad64007fde11dfe7d281b5f6d/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L524)
And only then we call `reveal` on one of the children which throws.
How is it possible that we have expanded the parent, and that the child is still not known to the tree?

**Comment by joaomoreno** [comment] 2019-08-30 06:37
> This is still our number 1 crash.

@bpasero That's because it's the same message everywhere. We need to distinguish the tree usages: https://github.com/microsoft/vscode/issues/80097

**Comment by joaomoreno** [comment] 2019-08-30 06:38
@isidorn Should not be possible. Like always, a repro would get us there.

**Comment by levani** [comment] 2019-09-02 16:48
I'm getting this error when I pressed "Reveal in Side Bar" action from opened file tab's context menu. This file was inside `node_modules` folder.

> ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
>     at X.getDataNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:978:433)
>     at X.reveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:978:23)
>     at e.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5553:604)
>     at Generator.next (<anonymous>)
>     at r (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:293)

**Comment by isidorn** [comment] 2019-10-09 09:59
We now have a more precise error message, thus closing this.
We aslo tackled some errors in this area

**Closed by isidorn** 2019-10-09 09:59 UTC
Labels: error-telemetry
