### ISSUE TITLE
highlighting of matching react tags

### ISSUE THREAD

**Issue by franckstifler** [Microsoft/vscode#18278] opened 2017-01-08 17:10 UTC
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Click on the closing tag, all the other tags get highlighted.
![image](https://cloud.githubusercontent.com/assets/11504867/21751816/aa1f8bb0-d5cd-11e6-9228-fba60dfd9bd3.png)

**Comment by aeschli** [comment] 2017-01-10 01:54
Has to be implemented in the typescript server...

**Comment by aeschli** [comment] 2017-01-10 01:56
duplicate of https://github.com/Microsoft/TypeScript/issues/10138

**Closed by aeschli** 2017-01-10 01:56 UTC
