### ISSUE TITLE
Extensions issues after update to vscode 1.47.0

### ISSUE THREAD

**Issue by Wav3** [microsoft/vscode#102082] opened 2020-07-10 08:53 UTC
Issue Type: <b>Bug</b>

Every installed extension is gone after I've installed the latest vscode update.  
The extensions pane loads infinite until i enter a search term and even the detailled page of an selected extension loads infinite.  
The installation of a new extension is also impossible. After hitting `Install` the button changes to `Installing` and after two seconds to the settings "gear", so it seems that the extension is now installed.  But the extensions seems not to be installed (Couldn't find it in the `enabled` section).  
The context menu of the "installed" extension also does not work.  
  
When I exit vscode, some processes remain running on the system without any CPU usage.  
![grafik](https://user-images.githubusercontent.com/6506725/87138173-554dba00-c29e-11ea-888b-d72dcd089d53.png)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (4 x 2197)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.99GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Wav3** [comment] 2020-07-10 09:00
This issue also occurs on another machine (see details below).  
The crazy thing is that the extensions are still recognized at least in the bug report.
  
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
syncify|arn|4.0.4
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.1
xml|Dot|2.5.0
gitlens|eam|10.2.2
rainbow-csv|mec|1.7.0
git-graph|mhu|1.24.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
powershell|ms-|2020.6.0
trailing-spaces|sha|0.3.1
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|3.1.0
material-theme|zhu|3.8.3


</details>

**Comment by Hello-GitHubs** [comment] 2020-07-10 09:16
I also have this problem. How can I solve it

**Comment by Wav3** [comment] 2020-07-10 09:16
After installing the previous version of vscode ([1.46.1](https://code.visualstudio.com/updates/v1_46)) all installed extensions are available again and can be used as expected.

**Comment by liangjiancang** [comment] 2020-07-10 09:44
Same problem for me.

**Comment by danforejtek** [comment] 2020-07-10 10:28
I have same problem.

**Comment by sandy081** [comment] 2020-07-10 12:18
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by sandy081** [comment] 2020-07-10 12:25
Can you also please confirm that if you just do not see the extensions in the view and they are running/enabled properly?

**Comment by Wav3** [comment] 2020-07-10 13:29
The requested logs:
<details>
<summary>Developer Tools -> Console</summary>
```
  ERR Cannot read property 'uuid' of undefined: TypeError: Cannot read property 'uuid' of undefined
    at o (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1638:272)
    at file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:140
    at Array.some (<anonymous>)
    at n (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:132)
    at Object.t.groupByExtension (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:202)
    at C.scanUserExtensions (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3890:698)
    at async C.scanExtensions (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3889:705)
    at async Promise.all (index 1)
    at async V._scanAllLocalExtensions (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5000:85)
    at async V._scanAndHandleExtensions (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5002:652)
    at async V._initialize (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4273:805)
log.ts:197   ERR Cannot read property 'uuid' of undefined: TypeError: Cannot read property 'uuid' of undefined
    at o (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1638:272)
    at file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:140
    at Array.some (<anonymous>)
    at n (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:132)
    at Object.t.groupByExtension (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:202)
    at C.scanUserExtensions (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3890:698)
    at async C.scanExtensions (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3889:705)
    at async Promise.all (index 1)
    at async V._scanAllLocalExtensions (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5000:85)
    at async Object.getInitData (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5000:358)
    at async Promise.all (index 1)
    at async z._createExtHostInitData (file:///C:/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4619:345)
```
</details>
<details>
<summary>Shared Process -> Console</summary>
```
No messages in Console.
```
</details>
<details>
<summary>Log (Shared)</summary>
```
[2020-07-10 15:16:29.382] [sharedprocess] [info] main {"machineId":"2e898c528ac17e5d8051bd0bcfb0625b949dfa0231dfad4bbff5d5c63a459717","windowId":2}
[2020-07-10 15:17:10.148] [sharedprocess] [info] Starting to clean up unused language packs.
```
</details>
<details>
<summary>Log (Main)</summary>
```
[2020-07-10 15:16:25.860] [main] [info] update#setState idle
[2020-07-10 15:16:55.861] [main] [info] update#setState checking for updates
[2020-07-10 15:16:56.181] [main] [info] update#setState idle
```
</details>

---

> Can you also please confirm that if you just do not see the extensions in the view and they are running/enabled properly?

Is I can see, the extensions do not run properly. No commands on the command pallette are available, the syntax highlighting and the linter does not work, etc.  
If I perform a downgrade to v1.46.1, everything is working fine, all extensions are back again and they seem to work properly.

**Comment by vishusandy** [comment] 2020-07-10 15:00
I have a similar issue (in Linux however), #98765, with extensions not loading in the extension bar (indicates its trying to load, but never actually loads); however the extensions are running.  This affects multiple computers for me.  The issue persists after reinstalling VS Code.  After reinstalling the operating system it seems to work for a short amount of time (maybe a few days or so) and is broken again.

**Comment by gjsjohnmurray** [comment] 2020-07-10 19:48
See also #102125 which contains a couple of log postings. Look to me like some people maybe have a faulty extension (or more than one) that's causing 1.47 to trip up when scanning user extensions.

**Comment by sandy081** [comment] 2020-07-13 21:01
Those who are having this issue, can you please open your user data directory ie., where your `settings.json` exist and see if you have a file named `extensions.json` ?

**Comment by sandy081** [comment] 2020-07-13 21:31
I can confirm that this is being caused by having `extensions.json` in the directory that contains `settings.json`. Generally this folder is owned by VS Code and creating any files there could lead to these kind of issues.

I am working on a fix for this (ie., to retain 1.46 behaviour) will be provided in our next recovery release.

**Comment by sandy081** [comment] 2020-07-13 21:55
To verify:

- Create an `extensions.json` file next to `settings.json` in your user data dir with following content
```
[
	{
		"id": "a"
	},
	{
		"id": "b"
	}
]
```
- Open VS Code and make sure extensions are loaded and running. Check extensions view and running extensions editor. Also check console for no errors.

**Comment by Wav3** [comment] 2020-07-14 05:45
Yes, a `extensions.json` file exists next to `settings.json` in `%APPDATA%\Code\User`.  

In my case [Syncify](https://github.com/arnohovhannisyan/vscode-syncify) creates the `extensions.json` file when it tries to synchronize the vscode configuration. Removing the `extensions.json` file and disabling the synchronisation of this extension prevents me from running in this bug again.  

I've created the [Issue#53](https://github.com/arnohovhannisyan/vscode-syncify/issues/53) in the Syncify repository.

**Closed** 2020-07-14 12:27 UTC
Labels: bug, candidate, extension-host, extensions
