### ISSUE TITLE
Refresh Images In Markdown On Change

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#109002] opened 2020-10-20 09:34 UTC
It is really nice that the markdown preview renders local images!
However, the preview does not update if those local images are changed.

This is a very handy feature for various scenarios, in particular when custom editors for images are involved (like the drawio editor).

Currently, if you change a drawio diagram, you need to close and reopen the preview of any markdown file that includes the drawio diagram as SVG-image:

![81238327-6ea2-4b34-bba0-5adaf3c938ca](https://user-images.githubusercontent.com/2931520/96567889-9e62d080-12c7-11eb-8fd7-2df426b50549.gif)

It would be awesome if the markdown preview would use the file system watcher to watch for file changes of included images and reload those on change!

I'm willing to try implementing this feature by myself.
This feature is hard to be implemented by extensions, as extensions cannot send commands into the markdown preview webview without spawning a websocket server.

**Comment by mjbvz** [comment] 2020-10-20 14:53
Duplicate of #65258

**Closed by mjbvz** 2020-10-20 14:53 UTC
