### ISSUE TITLE
Opening custom context menu can fire multiple onDidChangeActiveTextEditor events

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#55309] opened 2018-07-28 18:52 UTC
Issue Type: <b>Bug</b>

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

![](https://i.imgur.com/h4g04D5.gif)

In the above .gif, the following actions are performed:

 1. Clicking the output panel to focus it: a single `onDidChangeActiveTextEditor` event is fired with `output:tasks` (correct so far)
2. Right-clicking to open the context menu: _three_ events are fired at once: the active editor changes to `extension.js`, then to `output:tasks`, then back to `extension.js`.

For the second step, it seems like the correct behavior would be for no event to be fired at all, since at no point does the active editor change.

Extension code to reproduce:

```ts
import * as vscode from "vscode";

export function activate(context: vscode.ExtensionContext) {
	vscode.window.onDidChangeActiveTextEditor(editor => {
		var uri = null;
		if (editor != null) {
			uri = editor.document.uri;
		}
		console.log(uri);
	});
}
```

This also reproduces with the latest Insider's build (1.26.0-insider (dae69dbf00357ff8a3fe740a1f211d66b0b4681c, 2018-07-27T05:17:55.890Z)).
_____

It would be reasonable to ask why this is even a problem / how I came across this. In the Haxe extension, some output is generated in the Haxe output channel when the active editor changes to a `.hx` file. This effectively breaks the context menu, since the scrolling seems to cause it to immediately close again:

![](https://i.imgur.com/krI4LH5.gif)

The context menu closing there might be considered a separate bug?

**Comment by jrieken** [comment] 2018-08-06 10:59
That doesn't happen on the mac (using native menus). There is see a change to the 'real' editor but then it correctly changes back to the output 'editor'.

**Comment by jrieken** [comment] 2018-08-06 11:00
This is mostly driven by focus... @sbatten The custom menu takes dom focus, right? So the editor isn't focused in anyway anymore, right? Also the menu is a 'global' dom node, not a descendant of the editor right?

**Comment by sbatten** [comment] 2018-08-07 21:13
@jrieken for context menus they are descendants of a context-view node sibling to the other workbench parts. yes, context menus should take dom focus in the custom case

**Comment by jrieken** [comment] 2018-08-23 15:44
@sbatten Is the plan that the menu continues to take focus?

**Comment by sbatten** [comment] 2018-08-23 23:48
@jrieken yes

**Comment by jrieken** [comment] 2018-08-27 15:31
This needs support from the workbench. Currently, there can be an active editor *and* and an active panel which makes it impossible for the API to know what's 'more recently active'.

**Comment by bpasero** [comment] 2018-08-28 08:55
@jrieken can you elaborate what the behaviour of this method would be? Maybe a wrapper around `IEditorService` and `ICodeEditorService` that would check for the latter that the editor is within the bounds of the editor-part-container to rule out any editor that is elsewhere?

**Comment by jrieken** [comment] 2018-08-28 09:19
I want the workbench to tell me what the active thing is, be it an editor, a panel, a viewlet or whatever but there shouldn't the notion of multiple active things. With that I can find the active editor despite it having focus

**Comment by bpasero** [comment] 2018-08-28 09:41
@jrieken 

To clarify: active means, "last focused" I assume? Because  this is essentially what the editor service provides and does not exist currently for viewlets or panels.

Why do you ever need to know if panel or viewlet is active? Isn't all logic tied to editors in the editor part? Or are extensions allowed to participate in editors in other places like the panel.

**Comment by jrieken** [comment] 2018-08-28 09:48
> Why do you ever need to know if panel or viewlet is active? Isn't all logic tied to editors in the editor part? 

Yeah, we try to ignore workbench mechanisms as long as possible and we try to build everything based on code editor focus (and focus of it descendants). Only when no code editor has focus we ask the editor service. The challenge is that the menu now steals focus and that the "real" active part is the output panel. However, both services (editor service and panel service) claim to have an active thing I cannot make a decision. So, what's missing is an workbench things that knows the truly active part.

**Comment by bpasero** [comment] 2018-08-28 09:53
@jrieken the code editor service is already implemented specially in the workbench land. wouldn't it be enough to beef it up a little bit to always store the last code editor that had focus and then you do not even ever need to use the `IEditorService`?

**Comment by jrieken** [comment] 2018-08-28 09:59
>  had focus and then you do not even ever need to use the IEditorService?

Unfortunately no, when opening an editor from the explorer the code editor widget never receives focus and that would mean we have no active editor in the API.

**Comment by bpasero** [comment] 2018-08-28 10:26
Let's discuss in debt week how that could work.

**Comment by bpasero** [comment] 2018-09-11 08:05
@jrieken this is not limited to the output panel, I can reproduce the same when right clicking into an embedded code editor with the custom menu, multiple events are fired:

![peek 2018-09-11 10-04](https://user-images.githubusercontent.com/900690/45346671-1ff4ba00-b5aa-11e8-8cb8-d7459e66afea.gif)

**Comment by bpasero** [comment] 2018-09-11 08:06
Maybe a better approach would be to have a way to figure out that the context menu is visible and during that period ignore any editor change events (in terms of focus)?

**Comment by jrieken** [comment] 2018-09-11 08:14
> @jrieken this is not limited to the output panel, I can reproduce the same when right clicking into an embedded code editor with the custom menu

Yes, the underlying issue is that there is no one notion of an active editor in the workbench.

**Comment by bpasero** [comment] 2018-09-18 09:37
I experimented with adding and using `IContextMenuService#isVisible()` but unfortunately the editor blur event fires before the menu shows up. Unless we want to add an ugly `setTimeout(0)` to `mainThreadDocumentsAndEditors` I think this would not be a solution that helps.

**Comment by jrieken** [comment] 2018-09-18 09:41
> Unless we want to add an ugly setTimeout(0) to mainThreadDocumentsAndEditors I think this would not be a solution that helps.

That's impossible to do because everything depends on a correct document and editor state

**Comment by jrieken** [comment] 2018-09-18 09:42
Also, I don't think that `IContextMenuService#isVisible()` is enough because this problem will also occur with the global menu (which I assume isn't implemented via the context menu service)

**Comment by bpasero** [comment] 2018-09-18 13:45
Fixed via https://github.com/Microsoft/vscode/pull/58887/commits/fd73b5b8dd6a92927352002128c29071a378ef21

**Closed by bpasero** 2018-09-18 13:45 UTC
Labels: api, bug, editor, menus, windows
