### ISSUE TITLE
VSCode is not compatible with Ubuntu 24.04 with wayland default

### ISSUE THREAD

**Issue by liheyuan** [microsoft/vscode#212430] opened 2024-05-10 10:26 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Ubuntu 24.04 (wayland enabled)

Steps to Reproduce:

1. Fresh install Ubuntu 24.04
2. apt install code latest version (have try many version back to 1.85 or deb from official side or snap)
3. open a exist folder contains file
4. open file / terminal , vscode 
5. VSCode began to experience many strange behaviors, including not responding to shortcut keys, clicking buttons on the UI was not respond, and click button on dialog box but automatically switched to other app UI. It's basically unavailable...

I upload the following video to show parts of the issue

[Screencast from 2024-05-10 18-43-29.webm](https://github.com/microsoft/vscode/assets/776423/3f04abfd-f502-469b-9e35-ef4143e05209)

When my mouse is hovering over the popup or terminal, I actually click a lot of mouse or type a lot of keyboard, but vscode does not respond.

However, I disable wayland by editing '/etc/gdm3/custom.conf' , add following line
```
WaylandEnable=false
```
And reboot, everything works like charms.

Not sure if it's wayland bug or vscode problem, seems not compatible with wayland under linux.

**Comment by liheyuan** [comment] 2024-05-10 10:34
https://askubuntu.com/questions/1512758/window-cursor-wont-lock-in-games-with-ubuntu-24-04-multi

This article says that maybe Ubuntu 24.04 wayland + multi-screen is the cause, I will try it

**Comment by liheyuan** [comment] 2024-05-10 10:45
> https://askubuntu.com/questions/1512758/window-cursor-wont-lock-in-games-with-ubuntu-24-04-multi
> 
> This article says that maybe Ubuntu 24.04 wayland + multi-screen is the cause, I will try it

24.04 wayland + single screen, not work

**Comment by skbtwiz** [comment] 2024-05-10 20:50
Working just fine on 24.04 LTS with wayland enabled by adding flags to the .desktop file. I have installed using .deb package from official website and not a snap package.

Device is a Macbook Pro 13,2 (2016 Touchbar 13"). Using internal display.

**Comment by liheyuan** [comment] 2024-05-11 02:02
> Working just fine on 24.04 LTS with wayland enabled by adding flags to the .desktop file. I have installed using .deb package from official website and not a snap package.
> 
> Device is a Macbook Pro 13,2 (2016 Touchbar 13"). Using internal display.

I tried deb from official webside / apt / snap , Unfortunately, it's still the same problem.

**Comment by mistletoe235** [comment] 2024-05-11 03:23
I also encountered the same problem

**Comment by mrskycriper** [comment] 2024-05-14 11:00
> with wayland enabled by adding flags to the .desktop file

@skbtwiz Hi, can you please share those flags? I'm hoping that forcing Wayland will fix the blurriness when using fractional scaling. I've googled the problem but all the issues are from 1-2 years ago and the flags from them seem to be removed in the current version of Chromium.

**Comment by liheyuan** [comment] 2024-05-14 11:28
> > with wayland enabled by adding flags to the .desktop file
> 
> @skbtwiz Hi, can you please share those flags? I'm hoping that forcing Wayland will fix the blurriness when using fractional scaling. I've googled the problem but all the issues are from 1-2 years ago and the flags from them seem to be removed in the current version of Chromium.

This is work for me:

/usr/share/applications/code.desktop
```
[Desktop Entry]
...
#Exec=/usr/share/code/code %F
Exec=/usr/share/code/code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto %F
...

[Desktop Action new-empty-window]
...
#Exec=/usr/share/code/code --new-window %F
Exec=/usr/share/code/code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto --new-window %F
...

```

**Comment by siashish** [comment] 2024-05-15 06:39
Same issue on ubuntu 24.04
[Screencast from 2024-05-15 12-07-24.webm](https://github.com/microsoft/vscode/assets/45603733/1fa56328-35f2-4c40-b9a0-cd13075ee979)

**Comment by mrskycriper** [comment] 2024-05-15 12:55
@liheyuan Thank you! It worked, the window is not blurry anymore.

**Comment by jaime-ez** [comment] 2024-05-15 20:02
I'm having the same issue, vscode and vscode-insiders installed from snap store. Using two displays with different resolution. chromium adjusts scale factor automatically after running `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland` but vscode does not.

Ubuntu 22.04 using wayland
Vscode 1.89.1

Tried running :
`code --enable-features=UseOzonePlatform --ozone-platform=wayland` code did not launch
`code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland` did not launch
`code-insiders --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` did not launch

Any help is appreciated

**Comment by liheyuan** [comment] 2024-05-16 02:18
> I'm having the same issue, vscode and vscode-insiders installed from snap store. Using two displays with different resolution. chromium adjusts scale factor automatically after running `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland` but vscode does not.
> 
> Ubuntu 22.04 using wayland Vscode 1.89.1
> 
> Tried running : `code --enable-features=UseOzonePlatform --ozone-platform=wayland` code did not launch `code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland` did not launch `code-insiders --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` did not launch
> 
> Any help is appreciated

@jaime-ez 

Have you tried single screen and is it working properly?

**Comment by arbabkhalil** [comment] 2024-05-16 14:35
@liheyuan Thanks, this seems to fix my issue.

**Comment by jaime-ez** [comment] 2024-05-16 18:30
@liheyuan code nor code-insiders don´t launch on ubuntu 22.04.4 when running any of the commands I described earlier, independently if I have external displays or not.

**Comment by liheyuan-kanyun** [comment] 2024-05-17 02:39
> @liheyuan code nor code-insiders don´t launch on ubuntu 22.04.4 when running any of the commands I described earlier, independently if I have external displays or not.

It may be caused by other reasons, the phenomenon is not similar.

**Comment by youngqqcn** [comment] 2024-05-22 09:22
I 

> > > with wayland enabled by adding flags to the .desktop file
> > 
> > 
> > @skbtwiz Hi, can you please share those flags? I'm hoping that forcing Wayland will fix the blurriness when using fractional scaling. I've googled the problem but all the issues are from 1-2 years ago and the flags from them seem to be removed in the current version of Chromium.
> 
> This is work for me:
> 
> /usr/share/applications/code.desktop
> 
> ```
> [Desktop Entry]
> ...
> #Exec=/usr/share/code/code %F
> Exec=/usr/share/code/code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto %F
> ...
> 
> [Desktop Action new-empty-window]
> ...
> #Exec=/usr/share/code/code --new-window %F
> Exec=/usr/share/code/code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto --new-window %F
> ...
> ```
> 
> @mrskycriper

It's work , but after fixed this issue,  I couldn't input Chinese in vscode by using fcitx5.  

I disabled wayland mode by uncomment this config in `/etc/gdm3/custom.conf`

```
WaylandEnable=false
```

It's work for me

**Comment by zamoosh** [comment] 2024-06-05 08:10
> Does this issue occur when all extensions are disabled?: Yes
> 
> * VS Code Version: 1.89.1
> * OS Version: Ubuntu 24.04 (wayland enabled)
> 
> Steps to Reproduce:
> 
> 1. Fresh install Ubuntu 24.04
> 2. apt install code latest version (have try many version back to 1.85 or deb from official side or snap)
> 3. open a exist folder contains file
> 4. open file / terminal , vscode
> 5. VSCode began to experience many strange behaviors, including not responding to shortcut keys, clicking buttons on the UI was not respond, and click button on dialog box but automatically switched to other app UI. It's basically unavailable...
> 
> I upload the following video to show parts of the issue
> 
>  Screencast.from.2024-05-10.18-43-29.webm 
> When my mouse is hovering over the popup or terminal, I actually click a lot of mouse or type a lot of keyboard, but vscode does not respond.
> 
> However, I disable wayland by editing '/etc/gdm3/custom.conf' , add following line
> 
> ```
> WaylandEnable=false
> ```
> 
> And reboot, everything works like charms.
> 
> Not sure if it's wayland bug or vscode problem, seems not compatible with wayland under linux.


Hello, I'm not sure this is related to vscode or any other app, also after logging out every thing fixes. may wayland is the problem...

**Comment by WaKeMaTTa** [comment] 2024-06-06 07:23
When I try to open VSCode it opens for a 1s and it closes automatically.

In Ubuntu 24.04.4 LTS (Windows system: XOrg) + VSCode 1.90.0

```
Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:43:07.605Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-35-generic snap
```

---

Using Ubuntu 24.04.4 LTS (Windows system: Wayland) works fine.

**Comment by liheyuan** [comment] 2024-06-06 10:25
I have a new discovery

When in ubuntu 24.04 with wayland, vscode opens as a smaller & non-full screen window by default, and there are basically no problems at this time.

Once enter the maxium window mode, it will easily trigger problems I mentioned, including unresponsive UI, mouse confusion, etc.

**Comment by liheyuan** [comment] 2024-06-06 10:28
> I found that
> 
> When in ubuntu 24.04 with wayland, vscode opens as a smaller & non-full screen window by default, and there are basically no problems at this time.
> 
> Once enter the maxium window mode, it will easily trigger problems I mentioned, including unresponsive UI, mouse confusion, etc.

Seems can be resolved by change in configuration, Window: Title Bar Style to Custom instead of Native

**Comment by alextdel** [comment] 2024-06-06 11:23
I have a similar problem to many of the symptoms below.

- VSCode (flathub) - on current 1.90.0 and previous version
- Ubuntu 24.04 (gnome)
- AMD GPU.

**Process:**
Open VSCode - typically an HTML and a CSS file open in adjacent split panes - has happened on tabbed single pane also.
Edit for a while with all functions working OK then

- clicking in an edit window stops working.
- when split view ... one edit window will work (click, select, type etc) the other will not respond to click, selection or any mouse interaction
- application controls (close/maximise etc) will not respond
- menus still seem to work OK (save/exit etc).

Can be after a reasonable period of working fine.
Only solution is to continue working in the functioning pane or close the application and reopen.
Hope this information helps.

**Comment by liheyuan** [comment] 2024-06-06 11:32
> Title Bar Style

Have you tried "Change Title Bar Style" above?

@alextdel

**Comment by WaKeMaTTa** [comment] 2024-06-06 14:58
@liheyuan I tried. Didn't work for me.

**Comment by liheyuan** [comment] 2024-06-07 02:24
> When I try to open VSCode it opens for a 1s and it closes automatically.
> 
> 💥 In Ubuntu 24.04.4 LTS (Windows system: XOrg) + VSCode 1.90.0
> 
> ```
> Version: 1.90.0
> Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
> Date: 2024-06-04T19:43:07.605Z
> Electron: 29.4.0
> ElectronBuildId: 9593362
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Linux x64 6.5.0-35-generic snap
> ```
> 
> ✔️ Using Ubuntu 24.04.4 LTS (Windows system: Wayland) works fine.

@WaKeMaTTa open vscode then crash seems to be Electron related problem

try this https://github.com/electron/electron/issues/41066

**Comment by WaKeMaTTa** [comment] 2024-06-07 08:07
@liheyuan I tried the temporal solution that they propose in https://github.com/electron/electron/issues/41066

```
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```

but doesn't work :boom:

**Comment by Ruhiddin** [comment] 2024-06-07 20:16
> When I try to open VSCode it opens for a 1s and it closes automatically.
> 
> 💥 In Ubuntu 24.04.4 LTS (Windows system: XOrg) + VSCode 1.90.0
> 
> ```
> Version: 1.90.0
> Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
> Date: 2024-06-04T19:43:07.605Z
> Electron: 29.4.0
> ElectronBuildId: 9593362
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Linux x64 6.5.0-35-generic snap
> ```
> 
> ✔️ Using Ubuntu 24.04.4 LTS (Windows system: Wayland) works fine.

I also have the same issue.

VS code: version: 89de5a8d (5th June 2024)
laptop:

# System Details Report
## Report details
- **Date generated:**                              2024-06-08 01:14:13

## Hardware Information:
- **Hardware Model:**                              HP HP Laptop 15-ef2xxx
- **Processor:**                                   AMD Ryzen™ 5 5500U with Radeon™ Graphics × 12
- **Graphics:**                                    AMD Radeon™ Graphics

## Software Information:
- **Firmware Version:**                            F.27
- **OS Name:**                                     Ubuntu 24.04 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.0-35-generic

**Comment by jhnwsk** [comment] 2024-06-08 06:36
Hi, just wanted to report VSCode used to work until yesterday when all of a sudden...

```
$ uname -a
Linux master-blaster 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 
$ code --verbose
```

results in

```
[41120:0608/083307.662052:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=133
[41120:0608/083307.662085:WARNING:gpu_process_host.cc(1364)] The GPU process has crashed 6 time(s)
[41120:0608/083307.662102:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
[0608/083307.670109:ERROR:process_memory_range.cc(75)] read out of range
[0608/083307.670131:ERROR:process_memory_range.cc(75)] read out of range
[0608/083307.670137:ERROR:process_memory_range.cc(75)] read out of range
[0608/083307.670146:ERROR:process_memory_range.cc(75)] read out of range
[0608/083307.670151:ERROR:process_memory_range.cc(75)] read out of range
[0608/083307.670155:ERROR:process_memory_range.cc(75)] read out of range
```

I'm thinking... nvidia?

**Comment by zed-wong** [comment] 2024-06-08 09:13
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

$ echo $XDG_SESSION_TYPE
wayland

$ code -v                                           
1.90.0
89de5a8d4d6205e5b11647eb6a74844ca23d2573
x64

Encountered same problem here. When I open the vscode it stuck for 2 seconds and closed like crashed

**Comment by ken999999999999999** [comment] 2024-06-08 20:32
Hi, I had the same issue with installing vscode from snap store i ubuntu 24.04. 

I solved this issue by
1. Download vscode from https://code.visualstudio.com/Download, and install it.
2. Change window. titleBarStyle in userSetting.json from "native" to "custom" 
3. Disable wayland by follow this article https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop 

Hope it can help.

**Comment by zed-wong** [comment] 2024-06-09 05:13
> Hi, I had the same issue with installing vscode from snap store i ubuntu 24.04.
> 
> I solved this issue by
> 
>     1. Download vscode from https://code.visualstudio.com/Download, and install it.
> 
>     2. Change window. titleBarStyle in userSetting.json from "native" to "custom"
> 
>     3. Disable wayland by following this article https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop
> 
> 
> Hope it can help.

Thanks a lot! I uninstalled vscode using snap, downloaded and installed it from the your link and it's working now! In my case, the first step is enough to solve the problem. I haven't disable wayland.

**Comment by ken999999999999999** [comment] 2024-06-09 05:29
> > Hi, I had the same issue with installing vscode from snap store i ubuntu 24.04.
> > I solved this issue by
> > ```
> > 1. Download vscode from https://code.visualstudio.com/Download, and install it.
> > 
> > 2. Change window. titleBarStyle in userSetting.json from "native" to "custom"
> > 
> > 3. Disable wayland by following this article https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope it can help.
> 
> Thanks a lot! I uninstalled vscode using snap, downloaded and installed it from the your link and it's working now! In my case, the first step is enough to solve the problem. I haven't disable wayland.

I disabled Wayland because I couldn't resize some application windows with the mouse. Wayland seems causing many problems in Ubuntu 24.04.

**Comment by CodeZobac** [comment] 2024-06-11 20:36
Do a snap remove of vscode and pull the official repo from Microsoft
#Add the microsoft GPG key

```sh
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
rm packages.microsoft.gpg

sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

sudo apt update

sudo apt install code
```
This should make you able to use VScode again in version 24.04 of Ubuntu in any template you have running ubuntu.

**Comment by copinta** [comment] 2024-06-12 10:02
> Do a snap remove of vscode and pull the official repo from Microsoft 1-Add the microsoft GPG key 2-Add the official repo of Vscode 3-Update 4-Install
> 
> ```shell
> curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
> sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
> rm packages.microsoft.gpg
> 
> sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
> 
> sudo apt update
> 
> sudo apt install code
> ```
> 
> This should make you able to use VScode again in version 24.04 of Ubuntu in any template you have running ubuntu.

It did work for me. thanks

**Comment by tro-nic** [comment] 2024-06-13 14:36
Hi I can´t fix it, just uninstall snap and install via apt-get and done VS code work perfect.

**Comment by invy** [comment] 2024-06-17 09:53
Installing without snap did help

**Comment by thediveo** [comment] 2024-06-17 18:51
nope, installing from .deb does **not fix** vscode hanging on using the file open dialog, including trying to open a different workspace.

**Comment by abhijeetps** [comment] 2024-07-03 08:19
> Hi, I had the same issue with installing vscode from snap store i ubuntu 24.04.
> 
> I solved this issue by
> 
>     1. Download vscode from https://code.visualstudio.com/Download, and install it.
> 
>     2. Change window. titleBarStyle in userSetting.json from "native" to "custom"
> 
>     3. Disable wayland by following this article https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop
> 
> 
> Hope it can help.

Thanks @ken999999999999999 . 
I tried removing snap version and reinstalling via Microsoft's official repo inititally, but I was still facing the crashing issue.
However, your solution of using custom titleBar and disabling Wayland helped. 
Thanks! 🙌🏽

**Comment by youngqqcn** [comment] 2024-07-05 03:07
my vsocde version `1.91.0` , vscode on Ubuntu24.04  has many issues, sometimes all is fine, but sometimes occurs many issues as below: 
- sometimes  click on vscode's terminal console but show other application's window which is the behind the vscode window,  WTF!  I can't use terminal in vscode!
- sometimes when I max scale the vscode window,  I can't click and type words in vscode's terminal console
- sometims vsocde cat't be scaled and closed by top right button , when click "close" button on top right, it's close other application window which behind the vscode , WTF?

**Comment by aldolammel** [comment] 2024-07-05 18:53
> ```
> WaylandEnable=false
> ```

It is working fine so far. Thanks.

**Comment by sanbei011** [comment] 2024-07-18 23:50
Oh my god, I thought my computer was broken, but it turns out it's Electron that hasn't been updated for 24.04.

**Comment by EichiUehara** [comment] 2024-07-19 11:32
Title Bar Style setting from native to custom works for me

![Screenshot from 2024-07-19 20-29-28](https://github.com/user-attachments/assets/4889369b-963e-4706-8065-65f2cdff2338)

![Screenshot from 2024-07-19 20-30-03](https://github.com/user-attachments/assets/5d9afee9-f416-42d4-8be8-aafc556cdbe9)

**Comment by youngqqcn** [comment] 2024-07-22 04:28
> Title Bar Style setting from native to custom works for me
> 
> ![Screenshot from 2024-07-19 20-29-28](https://private-user-images.githubusercontent.com/75198000/350374231-4889369b-963e-4706-8065-65f2cdff2338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjIzNDcsIm5iZiI6MTcyMTYyMjA0NywicGF0aCI6Ii83NTE5ODAwMC8zNTAzNzQyMzEtNDg4OTM2OWItOTYzZS00NzA2LTgwNjUtNjVmMmNkZmYyMzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA0MjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjdkYmQ4NDAyY2I2ZWRlNTU3OGU5YTFjNGYzNTFkM2U2N2ZkZjE3Y2QyODdlOTUxZDJhNjJiNWJlMGJjOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MRGcks23tFTXMfuTFV_Iz_ADlE8ry-8-Y-NcOFgYaaI)
> 
> ![Screenshot from 2024-07-19 20-30-03](https://private-user-images.githubusercontent.com/75198000/350374266-5d9afee9-f416-42d4-8be8-aafc556cdbe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjIzNDcsIm5iZiI6MTcyMTYyMjA0NywicGF0aCI6Ii83NTE5ODAwMC8zNTAzNzQyNjYtNWQ5YWZlZTktZjQxNi00MmQ0LThiZTgtYWFmYzU1NmNkYmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA0MjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YTYwMjdmZGRmZTM4OTEwYWE5NDRlYjc4MTEyODU3YmY1MjcxMDI4MzBiMjNiNzE1ZjlhYThhODM5NzkxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FFEveJ3NNK-fZJp0lYvw0pDn74_3JV_kXTTwrSNNPVk)

Currently , it's also works for me ,  thanks!

**Comment by chaituskc** [comment] 2024-07-24 04:45
> Title Bar Style setting from native to custom works for me
> 
> ![Screenshot from 2024-07-19 20-29-28](https://private-user-images.githubusercontent.com/75198000/350374231-4889369b-963e-4706-8065-65f2cdff2338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTYyOTQsIm5iZiI6MTcyMTc5NTk5NCwicGF0aCI6Ii83NTE5ODAwMC8zNTAzNzQyMzEtNDg4OTM2OWItOTYzZS00NzA2LTgwNjUtNjVmMmNkZmYyMzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA0Mzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NDQwYTY2MDg0NmM2ZjYwMmQ1MTMxZDNmNTE2YjBhNjVkNDVmZDQwMDBlNjIwNzk2Zjc4YzE5NTU5NDNiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mwa74x8pd5noUha6byXTSzaTcFICPbzJkkAKPH1e7ls)
> 
> ![Screenshot from 2024-07-19 20-30-03](https://private-user-images.githubusercontent.com/75198000/350374266-5d9afee9-f416-42d4-8be8-aafc556cdbe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTYyOTQsIm5iZiI6MTcyMTc5NTk5NCwicGF0aCI6Ii83NTE5ODAwMC8zNTAzNzQyNjYtNWQ5YWZlZTktZjQxNi00MmQ0LThiZTgtYWFmYzU1NmNkYmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA0Mzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZWFkZDUzMTIwOTUxY2RiMDI4MWJhYTI4YzRiOTQ0YmUxYWI0YTU2YTZkZjc4NGIyZGY3YWJhNDI1OWQ5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J3uteMQCNcBbtkom8sHuy9ydSpzjM1AW_Sn0WL1YmE4)

With this, it works for me thanks

**Comment by liheyuan** [comment] 2024-08-12 10:42
Try upgrade to latest Ubuntu 24.04.1

It seems mutter ralated pkg fix this problem

mutter (46.2-1ubuntu0.24.04.1) noble; urgency=medium

[ Daniel van Vugt ]

New upstream release 46.2 (LP: #2068598)
Fixed mouse clicks falling through to the window behind (LP: #2026194)
...

**Comment by aldolammel** [comment] 2024-08-13 14:51
With Windows 10 Pro the PyCharm 2024.2 is working properly to rename interpreters. Finally! But now I'm using VSCode with custom extensions and I'm loving it. hehe

**Closed** 2024-08-22 02:48 UTC
Labels: bug, upstream, linux, electron, confirmation-pending, wayland

**Comment by doug65536** [comment] 2024-09-01 16:47
Lucky you. If I disable Wayland, it freezes at black screen before logon screen. I don't have a workaround. Try not to completely downplay your own bug report, implying that you should just leave Wayland off and it's not a bug.

**Comment by hildogjr** [comment] 2024-09-09 21:25
Also disable Wayland can create issues in other software used. IMHO, this still a issue to be addressed. Disable it is just a workaround that works for some users.

**Comment by hildogjr** [comment] 2024-09-09 21:29
https://github.com/microsoft/vscode/issues/193165

Appear to be related.

**Comment by hildogjr** [comment] 2024-09-09 21:43
I deleted the `~\.config\code` and `~\.vscode` folders and made a fresh extension reinstall. So far, appear fixed.

**Comment by icew4y** [comment] 2024-10-02 07:41
> titleBarStyle

Thanks, finally this works for me on ubuntu 24
