### ISSUE TITLE
Custom editors fail to restore if contributing extension is disabled

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#161008] opened 2022-09-15 18:42 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Create an excalidraw file with the excalidraw extension installed
2. Disable the excalidraw extension
3. Reload VS Code with the excalidraw file still open 
4. :bug: editor progress spins forever with no indication that I need to do something to get it to load

**Comment by mjbvz** [comment] 2022-09-15 18:54
Duplicate of #125582

**Closed by mjbvz** 2022-09-15 18:54 UTC
