### ISSUE TITLE
Don't hide breakpoint dot in gutter

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85427] opened 2019-11-23 00:54 UTC
Issue Type: <b>Bug</b>

We should not be hiding the breakpoint dot in the gutter, even when it is only an inline breakpoint. It is easy to miss the inline decoration and you can still toggle the breakpoint on an off via the gutter.

![image](https://user-images.githubusercontent.com/641685/69469978-ba7d8b00-0d61-11ea-92df-7463bbc110ad.png)

VS Code version: Code - Insiders 1.41.0-insider (599c076d91be1374cf51004cec610f3bcaf4c9cd, 2019-11-22T07:25:24.031Z)
OS version: Windows_NT x64 10.0.19028

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment] 2019-11-25 10:19
We are not hidding it on purpose, this is a bug which is a duplicate of https://github.com/microsoft/vscode/issues/85148

**Closed by isidorn** 2019-11-25 10:19 UTC
Labels: bug, debug
