### ISSUE TITLE
code fails to launch if DNS is unavailable since 1.29.1

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/vscode#63585] opened 2018-11-21 15:07 UTC
- VSCode Version: 1.29.1
- OS Version: 10.0.17763.0

Steps to Reproduce:

Turn off wifi and then run:

    $ code --disable-extensions
    dns.js:246
        this._handle = new ChannelWrap();
                    ^

    Error: EFILE
        at new Resolver (dns.js:246:20)
        at dns.js:377:25
        at dns.js:431:3
        at NativeModule.compile (bootstrap_node.js:606:7)
        at NativeModule.require (bootstrap_node.js:550:18)
        at net.js:45:13
        at net.js:1730:3
        at NativeModule.compile (bootstrap_node.js:606:7)
        at NativeModule.require (bootstrap_node.js:550:18)
        at internal/child_process.js:6:13

Does this issue occur when all extensions are disabled?: Yes

**Comment by dzsoundnirvana** [comment] 2018-11-21 15:18
This is likely going to be closed as a duplicate. Although all of the "duplicates" are closed without resolution and the issue still exists as of version 1.29.1, Electron version 2.0.12. (11/21/2018) Seems they are solely relying on the duplicate detection bot too much. I reported the same thing yesterday.

**Comment by mikemaccana** [comment] 2018-11-21 16:18
Yes this is a current issue, that affects stable VScode, and which is not
solved.

Microsoft: I'm fine for this to be labelled as a duplicate BUT: can you
please mark one of these as active?

**Comment by dzsoundnirvana** [comment] 2018-11-21 17:20
@michaelchiche It appears they are staching this issues under https://github.com/Microsoft/vscode/issues/7570 and it is open.
It did not show for me when I searched for it but someone responded to me on twitter with this information.
For right now the suggested workaround was "In the meantime you can install a loopback adapter to workaround" and this can be found in the comments of issue #7570

Hope this helps.

**Comment by bpasero** [comment] 2018-11-24 07:46
/duplicate of https://github.com/Microsoft/vscode/issues/7570

**Closed** 2018-11-24 07:46 UTC
Labels: *duplicate, javascript

**Comment by hossmf** [comment] 2018-12-01 11:15
same issue!
