### ISSUE TITLE
Focus outline cut off in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117349] opened 2021-02-23 10:01 UTC
Testing #116559

![image](https://user-images.githubusercontent.com/900690/108827887-6eee0880-75c6-11eb-9686-3c786804b3bb.png)

**Comment by bpasero** [comment] 2021-02-23 10:13
Same here:

![image](https://user-images.githubusercontent.com/900690/108829195-27687c00-75c8-11eb-943b-833def59d7a3.png)

**Comment by isidorn** [comment] 2021-02-23 10:30
I can repro.

There is nothing special that the action bar is doing here. But this was working in stable so I did break this. Thus assigning to this milestone.

@sandy081 and @sbatten was there something special that you were doing here to make this work previously? If you have time can you also take a look?

**Comment by bpasero** [comment] 2021-02-23 10:46
Maybe an artefact from the fact that this view is not to the top.

**Comment by sandy081** [comment] 2021-02-24 12:17
It seems this is happening only with some themes like Light, Light+, Dark, Dark+. These themes have top border for views headers instead of bgcolor. This border is pushing the outline.

**Comment by isidorn** [comment] 2021-02-24 12:39
Oh yeah, I can also reproduce with Stable.
Let's also assign to @misolori and you @sandy081 and move out of endgame. You can assign it back if you prefer

**Comment by misolori** [comment] 2021-03-08 18:40
One alternative is to change the `box-sizing` property to `content-box` which means that border will be placed on the outside making the header 1px taller. This will cause a slight shift in views where certain themes that don't use a border but only noticeable when switching themes.

**Comment by misolori** [comment] 2021-03-08 21:15
Trying out the second option since it's the less-obtrusive solution, we can re-visit if it doesn't work.

**Closed** 2021-03-08 21:15 UTC
Labels: bug, layout

**Comment by isidorn** [comment] 2021-03-09 08:30
@misolori thanks for tackling this 👏
