### ISSUE TITLE
Errors in console each time parameter hints are ignored in typescript

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#46852] opened 2018-03-28 13:48 UTC
* on VSCode master

Have a file `test.js`:
```js
function blabla()
{
}

blabla()
```

* open parameter hints at the call site
* press <kbd>End</kbd>

![kapture 2018-03-28 at 15 45 36](https://user-images.githubusercontent.com/5047891/38032952-1a54e95a-329f-11e8-9a23-4870757a9d08.gif)

---

I don't know who is at blame here: the UI side for not adding an error listener, or the extension side for generating errors in the call for `$provideSignatureHelp`, or both. Most likely both.

![image](https://user-images.githubusercontent.com/5047891/38033062-5eee018c-329f-11e8-9414-8178389106c6.png)

**Comment by jrieken** [comment] 2018-03-28 14:09
>  the UI side for not adding an error listener,

It is handled but not swallowed and default for those errors that are caused by extensions. See https://github.com/Microsoft/vscode/blob/e754b2f54417796e0457a4a938556db9b5e6e16d/src/vs/editor/contrib/parameterHints/provideSignatureHelp.ts#L36

Not sure if we should change that, leaving it up to @ramya-rao-a how added that

**Comment by ramya-rao-a** [comment] 2018-03-28 17:41
@jrieken Even though we have the `onUnexpectedExternalError` there to handle the errors from the promise, https://github.com/Microsoft/vscode/blob/e754b2f54417796e0457a4a938556db9b5e6e16d/src/vs/base/common/errors.ts#L13 still gets called. Any idea why?

Adding a `if (!error.error && !error.exception) return;` at https://github.com/Microsoft/vscode/blob/e754b2f54417796e0457a4a938556db9b5e6e16d/src/vs/base/common/errors.ts#L42 should fix this.

**Comment by ramya-rao-a** [comment] 2018-03-28 22:18
Also, this only started happening in the last release, so I dont think the problem is with how `onUnexpectedExternalError` or any other generic error handling is done.


I dont see this happening in 1.20.
In 1.21 only the "ERR An unknown error occurred. Please consult the log for more details." appears.
In the Insiders we have both the above and the "Promise with no error callback"

@jrieken @joaomoreno  Did something change in the signature help area?

**Comment by jrieken** [comment] 2018-03-29 07:35
> @jrieken @joaomoreno Did something change in the signature help area?

Not that I know - the real problem (the source of the exception) is TypeScript which keeps changing versions

**Comment by alexandrudima** [comment] 2018-03-29 08:25
We have discussed this in today's standup and have concluded it is not critical for March.

**Comment by mjbvz** [comment] 2018-04-24 00:49
Fixed by 93ff0d0

**Closed by mjbvz** 2018-04-24 00:49 UTC
Labels: bug, editor-symbols, typescript
