### ISSUE TITLE
fontFamily Consolas, Use space but not ALIGN

### ISSUE THREAD

**Issue by archi1016** [Microsoft/vscode#36386] opened 2017-10-17 05:16 UTC
![untitled 2](https://user-images.githubusercontent.com/10942241/31647866-49a6db00-b33d-11e7-96d7-21de891794fc.png)
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.16
material-icon-theme|PKi|2.2.2

(6 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-17 06:50
Duplicate of #36385

If you do not feel this is a duplicate, please provide some additional information about this issue such as the expected behavior and some steps to reproduce the problem

**Closed by mjbvz** 2017-10-17 06:50 UTC
Labels: duplicate, extensions, new release
