### ISSUE TITLE
Find All References / Shift F12 Not Working across project

### ISSUE THREAD

**Issue by jeffschwartz** [Microsoft/vscode#1416] opened 2015-12-17 14:53 UTC
Invoking "Find All References" in a project .ts file only yields results for that file and not for all the other files in the project that also contain the reference, which is what I would expect it to have done.

I can also confirm that it the same behavior is also present in Atom's Typescript plugin.

My environment is:
Mac OS X 10.9.5
Code Version 0.10.3 (0.10.3)
Atom 1.3.2

**Comment by egamma** [comment] 2015-12-17 15:00
You need to define a `tsconfig.json` file to define the scope of your project, pls see the [vscode ts doc](https://code.visualstudio.com/docs/languages/typescript).

**Comment by jeffschwartz** [comment] 2015-12-17 15:07
Hi @egamma. Thanks for the quick response. My project does have a tsconfig.json file and its contents are as follows:
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "filesGlob": [
        "**/*.ts",
        "**/*.tsx",
        "!node_modules/**"
    ],
    "compileOnSave": true,
    "buildOnSave": true,
    "atom": {
        "rewriteTsconfig": true
    },
    "files": [
        "src/core/api/CallStack.ts",
        "src/core/api/describe.ts",
        "src/core/api/it.ts",
        "src/core/environment/environment.ts",
        "src/core/queue/iqueueitem.ts",
        "src/core/queue/queue.ts",
        "src/core/queue/QueueManager.ts",
        "src/main.ts",
        "typings/q/Q.d.ts",
        "typings/tsd.d.ts"
    ]
}

**Comment by egamma** [comment] 2015-12-17 15:12
`filesGlob` is an extension to tsconfig.json that is specific to 'atom-typescript' it is not supported by the TypeScript Server and therefore by vscode. Could that be the cause that the scope is only a single file?

A reference search from src/main.ts should find the references in the files listed under the `files` section.

**Comment by jeffschwartz** [comment] 2015-12-17 15:51
Hi @egamma and thanks again for your quick response. I did some sherlocking. I removed all atom specific json entries from the tsconfig.json file and restarted Code. The results were identical. Then I invoked Find All References for a number of variables and types and noticed that it didn't work for interfaces, such as

interface IQueueItem {
    path: string,
    callback: () => void
}

which is the interface I was looking for originally and which raised the issue for me.

Please see the 2 images I have provided. One shows the results of plain old search for IQueueItem which finds it in numerous files. The other shows the results of Find All References for IQueueItem which finds it in only the current file.
![screen shot 2015-12-17 at 10 40 20 am](https://cloud.githubusercontent.com/assets/271288/11874008/6f4f27ec-a4ab-11e5-98a6-126d2ee9b3ae.png)
![screen shot 2015-12-17 at 10 41 24 am](https://cloud.githubusercontent.com/assets/271288/11874007/6f4768cc-a4ab-11e5-9415-c24099dcbe18.png)

I would expect that Find All References for IQueueItem to yield all the files in which the interface was used but that isn't the case.

**Comment by jrieken** [comment] 2015-12-17 16:02
By using `export =` you lose tracking of the `IQueueItem` cos it won't be referenced by that name anymore

**Comment by jeffschwartz** [comment] 2015-12-17 16:19
Hi @jrieken and thank you for your quick response. OK I understand but it still smells like a bug to me :). Find All References and even Change All Occurrences should be able to resolve export = value, object and type across files otherwise project-wide refactoring is severely hobbled IMHO.

**Comment by jrieken** [comment] 2015-12-18 09:39
I agree, but this very likely an issue on the TypeScript server side. I will wait for@dbaeumer to confirm.

**Comment by jeffschwartz** [comment] 2015-12-18 12:26
@jrieken thank you.

**Comment by dbaeumer** [comment] 2016-01-04 11:16
As @jrieken already pointed out this is an issue in the tsserver not reporting the reference. Moving to the TypeScript team.

**Comment by dbaeumer** [comment] 2016-01-04 11:17
This issue was moved to Microsoft/TypeScript#6341

**Closed by dbaeumer** 2016-01-04 11:17 UTC
