### ISSUE TITLE
Extension host crash

### ISSUE THREAD

**Issue by vorty123** [microsoft/vscode#176949] opened 2023-03-13 10:30 UTC
Type: <b>Bug</b>

Extension host always crashes since the last update. I did not modified any extension. Tried disabling extensions. Some days it doesn't crash. Some days it does. It is unusable.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.26GB (4.82GB free)|
|Process Argv|--crash-reporter-id b80aae7f-1f83-4976-8cbb-5e341800d3d3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
lualinter|dcr|1.0.3
file-icons|fil|1.0.29
copilot|Git|1.77.9225
todo-tree|Gru|0.0.224
vscode-lua-format|Koi|1.3.8
hexeditor|ms-|1.9.11
comment-divider|sta|0.4.0
sort-lines|Tyr|1.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30677850
pythonb192cf:30669361
funwalk2cf:30682975

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-13 11:30
Does this still happen after you disable the Copilot extension? If yes, please re-enable it and use the `Start Extension Bisect` command to investigate other causes.

**Comment by vorty123** [comment] 2023-03-13 11:49
I've done Start Extension Bisect the other day, disabled the "Vue Language Extension", solved the problem for a brief time, but the problems started again.

Btw, getting these errors in the extension host log:
2023-03-13 12:48:40.607 [error] Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)

**Comment by gjsjohnmurray** [comment] 2023-03-13 11:52
Recently I have seen a lot of similar reports that have the Copilot extension in common. Please try disabling this for a while.

**Comment by vorty123** [comment] 2023-03-13 12:13
Any other ideas? Copilot really helps me, my coworker has the same work laptop as me, same VSC and same Copilot version, yet he doesn't experience any issues at all.

**Comment by ulugbekna** [comment] 2023-03-13 18:02
@vorty123 maybe you could try Copilot Nightly extension?

**Comment by isidorn** [comment] 2023-03-15 11:15
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:15 UTC
Labels: freeze-slow-crash-leak, extension-host, triage-needed
