### ISSUE TITLE
Crash and stop working

### ISSUE THREAD

**Issue by saqib00786** [microsoft/vscode#177047] opened 2023-03-14 06:56 UTC
Type: <b>Bug</b>

Again and again it stop working and crashed accidently

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.42GB (2.81GB free)|
|Process Argv|--crash-reporter-id 0b2dcbf8-3e86-49b6-8d22-219be9e0bf63|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.9.8
turbo-console-log|Cha|2.7.1
npm-intellisense|chr|1.4.4
js-codeformer|cms|2.6.1
es7-react-js-snippets|dsz|4.4.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|13.3.2
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
copilot|Git|1.77.9225
remotehub|Git|0.52.0
gitlab-workflow|Git|3.60.0
todo-tree|Gru|0.0.224
remote-repositories|ms-|0.30.0
vscode-typescript-next|ms-|5.1.20230313
vscode-react-native|msj|1.10.2
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.24.0
vscode-react-refactor|pla|1.1.3
typescript-hero|rbb|3.0.0
snippets|rne|4.1.0
vscode-standard|sta|2.1.3
code-spell-checker|str|2.19.0
highlight-matching-tag|vin|0.11.0
glean|wix|5.2.2
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
pythonb192cf:30669361
funwalk2:30682974

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-14 19:05
I suggest you try disabling the GitHub Copilot extension to see if that helps.

**Comment by isidorn** [comment] 2023-03-15 11:12
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:12 UTC
Labels: freeze-slow-crash-leak, extension-host
