### ISSUE TITLE
Pressing enter before a closing tag that was just created indents it in a level

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12971] opened 2016-09-29 05:09 UTC
- VSCode Version: Insiders
- OS Version: Windows 10

Regarding test plan item #12100

Steps to Reproduce:

1. Type `<div` and press tab repeatedly until it completes it for you to have an opening and closing tag: `<div></div>`
2. Your cursor will be between this pair of tags.  Now hit enter/return to send the closing tag to the next line.
3. Note that the newest build of Insiders puts this tag indented in a level, whereas stable more correctly has it at the same indent level.

**Insiders**
![insiders2 add div](https://cloud.githubusercontent.com/assets/11839736/18941683/f0be06ce-85c7-11e6-81c4-194055f1e6b4.gif)

**Stable**
![stable - add div](https://cloud.githubusercontent.com/assets/11839736/18941682/f0bcc714-85c7-11e6-9c47-e20bd650869a.gif)

Sorry for the motion sickness of watching these 2 gifs side-by-side 🌊

**Comment by bgashler1** [comment] 2016-09-29 05:32
This does not seem to affect Razor cshtml :)

**Comment by dbaeumer** [comment] 2016-09-29 09:05
The problem seems to be the superfluous >. If it is not there indentation works correctly. 

Discussed with @egamma and this seems to be emmet related.

**Comment by egamma** [comment] 2016-09-29 12:38
duplicate of #12975

**Closed by egamma** 2016-09-29 12:38 UTC
Labels: bug
