### ISSUE TITLE
Slowdown on extended use

### ISSUE THREAD

**Issue by othebe** [Microsoft/vscode#1799] opened 2016-01-05 19:53 UTC
The editor starts turning very laggy after its been used a while, needing a restart.

**Comment by alexandrudima** [comment] 2016-01-14 10:06
@othebe Can you help me with more specific steps so that I could reproduce. What is your OS? Do you open files individually, do you open a folder, what is the predominant languages you use, do you work with very large files, for how many hours do you leave it running before opening again, etc. Do you close the working file set from time to time (to free up memory -- to clean all the undo stacks?). 

Also, what do you mean by laggy, do you have something specific in mind (like typing or scrolling) or rich language features (such as go to definition, squiggles, etc.).

Please share anything that could help us reproduce.

**Comment by othebe** [comment] 2016-01-16 01:44
Yep! Using OSX 10.10.5, 2.5 GHz i7 w/16GB RAM. I usually have 2 windows open, one that has a Javascript folder open, and the other with a Ruby on Rails folder open. 90% of my work happens in Javascript though. Individual files aren't that large averaging at I would say 500 LOC. However is a very large number of files within the folders and I tend to search for files a lot. I leave my windows open so I don't free memory.

What I meant by laggy was that things go unresponsive for a few seconds before spewing everything in the buffer. I could type a few words and nothing would appear on screen nor would the cursor blink. A few seconds all my words would appear suddenly and this repeats. This is the same for other actions such as scrolling.

I'm attaching a few screen captures if it helps any. Cheers.

Video capture:
https://vid.me/c4Wa

<img width="834" alt="screen shot 2016-01-15 at 5 32 54 pm" src="https://cloud.githubusercontent.com/assets/2115270/12369587/23557088-bbaf-11e5-8d4a-5422e95a8893.png">

**Comment by alexandrudima** [comment] 2016-01-19 10:41
@othebe That is really horrible! It should really not be like that. To help me track the root cause, would you please be willing to do the following:

* `F1` > `Developer: Toggle Developer Tools`
* Go to the `Profiles` tab
* Choose `Collect JavaScript CPU Profile`
* Target: `Main` > `Start`
* type in the editor (basically what you do in the above video)
* Hit `Stop`
* Next to Profile 1 hit `Save`
* Share the file with me

Here is me doing it:
![cpu-profiling](https://cloud.githubusercontent.com/assets/5047891/12416392/efa94478-bea9-11e5-98d7-0b8bb7ab56fd.gif)

**Comment by othebe** [comment] 2016-01-20 23:52
Attaching profile of when things started to go bad. Things went slower after but VSCode crashed when I was recording so wasn't able to capture that. Hope this helps - will send you another profiling when it happens again.

[CPU-20160120T154639.cpuprofile.zip](https://github.com/Microsoft/vscode/files/98389/CPU-20160120T154639.cpuprofile.zip)

**Comment by alexandrudima** [comment] 2016-01-21 08:38
@othebe Thank you!

From looking at the profile, it does not appear any code in particular is going haywire, but that there must be a huge memory pressure, as the GC uses 73% of the time.

**Comment by alexandrudima** [comment] 2016-01-21 08:43
@jrieken fyi This is a project with many small JS files. Do you have any tips on using `jsconfig.json` to limit the number of files we load or other ideas that could reduce memory pressure?

**Comment by jrieken** [comment] 2016-01-21 11:28
@othebe In jsconfig.json you can define excludes. Often small project bring in a lot of dependent JS code (node_modules or build & bundled stuff) which makes VS Code chew on it. Can you check that this isn't the case you? And iff can you try by excluding things?

**Comment by alexandrudima** [comment] 2016-07-05 07:35
@othebe We have made lots of improvements over the past months that might incidentally help your use-case. Would you care to give it another try and report if things are still painfully slow...

You can grab the latest from the insiders channel - https://code.visualstudio.com/insiders

**Comment by alexandrudima** [comment] 2016-09-14 17:21
@othebe Do you have a laptop with a touchscreen?

**Comment by alexandrudima** [comment] 2016-10-27 20:43
Closing after a number of days without a reply.

**Closed by alexandrudima** 2016-10-27 20:43 UTC
Labels: needs more info
