### ISSUE TITLE
TS/JS general missing features

### ISSUE THREAD

**Issue by rehberbey** [microsoft/vscode#159272] opened 2022-08-26 08:53 UTC
Type: <b>Bug</b>

I don't know if you are adding missing features manually, but you better make a system that automates it.

Even though I opened this topic under the TS/JS title, I think this topic is also valid for other languages.

```ts
// @ts-expect-error - Property 'getCanonicalLocales' does not exist on type 'typeof Intl'.(2339)
console.log(Intl.getCanonicalLocales('EN-US')); // ["en-US"]

type INTL = keyof typeof Intl;
/*
| "Collator"
| "NumberFormat"
| "DateTimeFormat" 
| "PluralRules" 
| "RelativeTimeFormat" 
| "Locale" 
| "DisplayNames" 
| "ListFormat" 
| "Segmenter"
 */
 ```

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by yume-chan** [comment] 2022-08-26 10:21
Duplicate of https://github.com/microsoft/TypeScript/issues/29129

**Closed** 2022-08-26 14:59 UTC
