### ISSUE TITLE
Color picker not available while editing Stylus

### ISSUE THREAD

**Issue by guidolarosa** [Microsoft/vscode#46115] opened 2018-03-19 15:16 UTC
Issue Type: <b>Bug</b>

The color picker is working right with CSS files, but when I'm editing Stylus files, it doesn't show up when I hover over the color code.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 x 2800)|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
vsc-material-theme|Equ|1.5.1
vscode-simple-icons|Lau|1.8.2
vscode-jade-snippets|mrm|1.0.1
vscode-icons|rob|7.21.0
sass-indented|rob|1.4.8
language-stylus|sys|1.9.1

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by usernamehw** [comment] 2018-03-19 17:42
Duplicate of #32678

**Comment by aeschli** [comment] 2018-03-19 21:19
Thanks @usernamehw !

**Closed** 2018-03-19 21:19 UTC
Labels: new release
