### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zengzhangtong** [Microsoft/vscode#20003] opened 2017-02-06 03:49 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vue|liuji-jim|0.1.5|
|debugger-for-chrome|msjsdiag|2.4.2|
|vetur|octref|0.2.0|
|guides|spywhere|0.6.1|

---

Steps to Reproduce:
![image](https://cloud.githubusercontent.com/assets/23078758/22634112/d75258f6-ec61-11e6-9024-e3fa1021f83e.png)

1.Tips always pop,  never stop
2.

**Comment by bpasero** [comment] 2017-02-06 05:32
This looks like a TypeScript warning. @zengzhangtong can you translate the message?

**Comment by zengzhangtong** [comment] 2017-02-06 05:38
I reinstall vscode so I don't have this bug in anymore.

**Comment by innerlee** [comment] 2017-02-06 07:20
translate:

```txt
warn: path c:\Prog......\lib do not point to a valid tsserver installation. will disable TypeScript...
warn: in the past 5 minutes, TypeScript terminated unexpectedly 5 times. please consider reporting a bug.
```

**Comment by mjbvz** [comment] 2017-02-06 18:40
From the symptoms, this looks like a duplicate of #19814. Some terrible antivirus program keeps deleting VSCode's TypeScript server files. Reinstalling VSCode should fix this.

If you see this again, please add the `typescript` path mentioned in the error message to the exemption list for the antivirus program. You can also bring your own version of TypeScript: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Closed by mjbvz** 2017-02-06 18:40 UTC
Labels: duplicate, javascript, typescript
