### ISSUE TITLE
Lots of output when running notebook integration tests

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120423] opened 2021-04-02 13:39 UTC
./scripts/test-integration.sh:

```
FileOperationError: Unable to read file '/Users/daimms/dev/Microsoft/vscode/extensions/markdown-language-features/notebook-out/index.js' (Error: Unable to resolve non-existing file '/Users/daimms/dev/Microsoft/vscode/extensions/markdown-language-features/notebook-out/index.js')
    at FileService.doReadFileStream (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/files/common/fileService.js:411:23)
    at async readFileStream (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/common/resourceLoader.js:60:28)
    at async loadLocalResource (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/common/resourceLoader.js:108:30)
    at async WebviewProtocolProvider.handleWebviewResourceRequest (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/electron-main/webviewProtocolProvider.js:172:36) {
  fileOperationResult: 1,
  options: { etag: undefined }
}
FileOperationError: Unable to read file '/Users/daimms/dev/Microsoft/vscode/extensions/notebook-markdown-extensions/notebook-out/katex.js' (Error: Unable to resolve non-existing file '/Users/daimms/dev/Microsoft/vscode/extensions/notebook-markdown-extensions/notebook-out/katex.js')
    at FileService.doReadFileStream (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/files/common/fileService.js:411:23)
    at async readFileStream (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/common/resourceLoader.js:60:28)
    at async loadLocalResource (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/common/resourceLoader.js:108:30)
    at async WebviewProtocolProvider.handleWebviewResourceRequest (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/electron-main/webviewProtocolProvider.js:172:36) {
  fileOperationResult: 1,
  options: { etag: undefined }
}
FileOperationError: Unable to read file '/Users/daimms/dev/Microsoft/vscode/extensions/notebook-markdown-extensions/notebook-out/emoji.js' (Error: Unable to resolve non-existing file '/Users/daimms/dev/Microsoft/vscode/extensions/notebook-markdown-extensions/notebook-out/emoji.js')
    at FileService.doReadFileStream (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/files/common/fileService.js:411:23)
    at async readFileStream (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/common/resourceLoader.js:60:28)
    at async loadLocalResource (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/common/resourceLoader.js:108:30)
    at async WebviewProtocolProvider.handleWebviewResourceRequest (/Users/daimms/dev/Microsoft/vscode/out/vs/platform/webview/electron-main/webviewProtocolProvider.js:172:36) {
  fileOperationResult: 1,
  options: { etag: undefined }
}
    ✓ #115855 onDidSaveNotebookDocument (216ms)
```

**Comment by mjbvz** [comment] 2021-04-02 21:12
Duplicate of #120213

**Closed by mjbvz** 2021-04-02 21:12 UTC
Labels: notebook-markdown, polish
