### ISSUE TITLE
Support multi tsconfig.json files

### ISSUE THREAD

**Issue by gilamran** [microsoft/vscode#94261] opened 2020-04-02 08:12 UTC
In our project I want to be able to put the test file near the component that I'm testing.
For example, near `Todo.tsx` I would put the `Todo.test.tsx`

I've created 2 `tsconfig.json` files, one for the application, and one for the tests. I've separated them because they run on two different environments., they have different types and libs.

The problem with that is that vscode can't tell which `tsconfig.json` the current file is related to.
Probably it's looking up the directory tree for a `tsconfig.json` file, and uses it. (I think)

The current way to solve this, is to have a `tsconfig.json` file for both the app and the tests, for vscode to detect issues. a `tsconfig.app.json` for the application without the tests libs and types. and a `tsconfig.tests.json` for tests.

The problem with that, is that I might import a tests/node/jest files to my app my mistake.
Note that I would be able to detect that while compiling against the `tsconfig.app.json`

It would be great if I could tell vscode what are my tsconfig files to use.

**Comment by mjbvz** [comment] 2020-04-02 17:40
Duplicate of https://github.com/microsoft/TypeScript/issues/33094

**Closed by mjbvz** 2020-04-02 17:40 UTC
