### ISSUE TITLE
Markdown preview doesn't work at all on vscode.dev

### ISSUE THREAD

**Issue by kzvi** [microsoft/vscode#143035] opened 2022-02-14 17:56 UTC
1. Go to insiders.vscode.dev 
2. Create new markdown file
3. Press cmd-k v to open the markdown preview
4. Start typing in the markdown editor
5. The markdown preview will either not update at all, or will display a few characters and then stop updating

Update: It seems that on insiders.vscode.dev, this only happens in private mode in Firefox. But if you use vscode.dev then it also happens outside of private mode.

Version: 1.65.0-insider
Commit: 50089c3f92c17584a4aca179f51f220b56c22020
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0
Embedder: vscode.dev

**Comment by mjbvz** [comment] 2022-02-14 21:09
Duplicate of 142817 or #142813 depending on the specific error

**Closed by mjbvz** 2022-02-14 21:09 UTC
