### ISSUE TITLE
Terminal leaves rendering "cruft"

### ISSUE THREAD

**Issue by ahernsean** [microsoft/vscode#107899] opened 2020-10-01 16:29 UTC
Issue Type: <b>Bug</b>

My terminal constantly leaves rendering "cruft" on the lowest line of the terminal. The rendering artefacts disappear if I resize the terminal, requiring a full refresh.

I expect it has to do with fonts. I'm using "Menlo for powerline". A screenshot will best show this problem.

![image](https://user-images.githubusercontent.com/1649300/94837010-b25e9500-03e1-11eb-99c4-ba3607f08eef.png)

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.76GB (44.50GB free)|
|Process Argv|--crash-reporter-id 8a0cac66-751e-4c2e-8f51-0e08bc8b12f1|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment] 2020-10-02 08:56
Duplicate of https://github.com/microsoft/vscode/issues/106981

**Closed by alexr00** 2020-10-02 08:56 UTC
