### ISSUE TITLE
Nested objects are not shown on JS debugger

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#2772] opened 2016-02-07 06:06 UTC
I find it quite hard to debug things when I cannot see the values of the properties below:

<img width="284" alt="screen shot 2016-02-07 at 14 00 29" src="https://cloud.githubusercontent.com/assets/1324476/12871106/ab98e032-cda3-11e5-9949-ba35c55b2e9b.png">

**Comment by tinganho** [comment] 2016-02-07 14:28
This turns out to only happen on some cases and not all. Randomly also.

**Comment by isidorn** [comment] 2016-02-08 08:35
Can you please provide steps on how to reproduce this? Or at least a case where it randomly happens?

**Comment by weinand** [comment] 2016-02-08 08:58
@tinganho what version of node and VSCode are you using? Do you have a reproducible case with steps? Thanks.

**Comment by tinganho** [comment] 2016-02-08 09:13
@weinand @isidorn this happened when I wanted to contribute to the TypeScript project. It happens all the time, just set a break point with a debugger statement(it seems like adding break points on VSCode also don't work all the time). And run the following command: 
```
jake runtests debug=true
```
You might want to just run a specific test with `t=name` also:
```
jake runtests t=nameoftest debug=true
```
After that, just attach to the node process.

Also, the debugging process is super slow on the TypeScript project. Though, I don't know if this is wrong with nodejs or wrong with VSCode. And clicking on the debug button(next, step into, step out) too fast will just break the debugging experience. It accumulates all the actions and fires them all at once, and you might miss the "destination point". There is also a timeout error for the debugger that occurs all the time.

I'm on a Mac with the following settings:
```
$ node -v
v5.0.0

VSCode:
Version 0.10.6 (0.10.6)
```

**Comment by weinand** [comment] 2016-02-08 09:42
@tinganho you are probably running in some large data-structure slowness issues of the node debugger protocol (e.g. there is no way to access arrays or dicts in chunks, you always get the full thing...). Up to node 0.12.x we did some code injection into the debugger to work around these issues and they were quite effective. If possible, just try to use node 0.12.9 and you will notice the difference. For node  4.x and 5.x we haven't figured out how to do the same trick, but we are working on it.

**Comment by tinganho** [comment] 2016-02-08 10:08
Ok thanks, good to know.

**Comment by weinand** [comment] 2016-02-12 23:33
Duplicate of https://github.com/Microsoft/vscode-node-debug/issues/11

**Closed by weinand** 2016-02-12 23:33 UTC
Labels: bug, debug
