### ISSUE TITLE
Console log disappeared 

### ISSUE THREAD

**Issue by cc5zhenhua** [Microsoft/vscode#6630] opened 2016-05-22 15:48 UTC
- VSCode Version: 1.1.1 
- OS Version: Enu Win7 x64

Steps to Reproduce:
1.  Open a Typescript projects based on nodejs.
2.  
   strike F1 and type rub to get run build tasks  and strike enter to build the project.
3. No console logs show now.
4. Strike F5 to run the project, no console log any more.
5. Relaunch the VS Code will resolve the issue but happen again when repeater step 2.

**Comment by dbaeumer** [comment] 2016-05-24 09:20
@cc5zhenhua  I can't reproduce this with my project. Can you share the TypeScript based nodejs project you are seeing this in.

**Comment by cc5zhenhua** [comment] 2016-05-26 13:23
Sorry, can share you my project. I 've got it repro on another machine.


Install old version VScode,  maybe the previous version before 1.1.1.  and open a typescript - project . Then new version prompt shows when I launch the VS Code.
I click the update prompt link directly and Update VS Code to 1.1.1. The issue happens.


Open Same typescript project.
 Click F5 to run with NodeJS. (Actually it's a protractor project)
Then Strike F1 ---Run build project ---Here no build logs now.
Click F5 again after build complete.  ----- Here no Run logs at all.




Thanks
JEN.LEE







At 2016-05-24 17:21:25, "Dirk Bäumer" <notifications@github.com> wrote:


@cc5zhenhua I can't reproduce this with my project. Can you share the TypeScript based nodejs project you are seeing this in.

**Comment by mjbvz** [comment] 2017-01-11 23:20
Closing since we have not heard any follow up on this.

@cc5zhenhua If you are still seeing this issue with VSCode 1.8+, please let me know and we can reopen this to investigate

Thanks

**Closed by mjbvz** 2017-01-11 23:20 UTC
Labels: needs more info, tasks
