### ISSUE TITLE
Autocompletition with Tab key behaves more like Bash auto completition

### ISSUE THREAD

**Issue by sdrsdr** [microsoft/vscode#71711] opened 2019-04-04 09:05 UTC
When working in complex projects (in C/C++) it's often s good idea to "namespace" the symbols in module with common name prefix. This leads to inefficiency of autocompletition as you start to type the common prefix allot of symbols are selected and  displayed. Currently there is no way to complete the common part of currently selected symbols and start typing (eventual) starts for needed symbol. We have a Tab auto completition that behaves exactly as if  user presses "Enter" but in most shells pressing tab completes just to the next ambiguous character position which if borrowed as semantics in VSCode autocompletition will be useful in C/C++ world. 

Example use case:

Assume flowing symbols are known for autocompletition:

module1_task_start
module1_task_stop
module1_task_restart
module1_foo
module2_bar

User starts to type: mod

User get autocompletition hints with all the symbols above

User presses Tab 

mod is auto completed to  module, hints remain the same 

User types:  1_t and presses Tab

the input is completed to module1_task_ and sybols filtered to 

module1_task_start
module1_task_stop
module1_task_restart

A much efficient way to select symbols that will encourage using of longer and meaningful names for symbols.

**Comment by jrieken** [comment] 2019-04-05 07:34
Cool idea but some work to get this in. What you could try till then is `"editor.tabCompletion": "on"` - that will insert the best matching suggestion when pressing tab and cycling through the rest when pressing tab again.

**Comment by jrieken** [comment] 2019-05-08 15:23
also to describe the fast-filter-approach that we have implemented and how that work with your sample above: simply type `mod1t` and you have what you need. I would argue that's faster then expanding common prefixes before narrowing down

**Comment by sdrsdr** [comment] 2019-05-09 08:55
this works only if you know the code base and if you know how to narrow  down the letters to the least common. this is a non-trivial mind-task of its own. I'm not sure this fits in the definition of "ease of use"

**Comment by jrieken** [comment] 2019-05-09 12:32
/duplicate of https://github.com/microsoft/vscode/issues/61426

Turns out this has been asked before...

**Closed** 2019-05-09 12:32 UTC
Labels: *duplicate, feature-request, suggest
