### ISSUE TITLE
Cannot scroll in integrated terminal unless hovering over text

### ISSUE THREAD

**Issue by avarun42** [Microsoft/vscode#7679] opened 2016-06-14 23:07 UTC
- VSCode Version: 1.2.1
- OS Version: macOS 10.11.5

Steps to Reproduce:

1. Open integrated terminal
2. Try to scroll while hovering to the right of text, but still inside terminal.

This issue becomes particularly annoying when there are long lines of text in the terminal at a point but short lines before and after. You can scroll at column 110(for example) at a specific area, but only at column 60 everywhere else.

**Comment by Tyriar** [comment] 2016-06-15 02:04
Duplicate of https://github.com/Microsoft/vscode/issues/6743, coming in v1.3.0

**Closed by Tyriar** 2016-06-15 02:04 UTC
