### ISSUE TITLE
Fluent Design

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#26572] opened 2017-05-12 20:56 UTC
I love VS Code. I love it so much that I have made like 12+ extensions for it and reported 20+ issues and gave talks about it. In Emacs vs Vim fights, I always talk about vscode and  I find everything about it amazing and better than any other editor. It has exactly all that is needed and has removed exactly all that is junk. So it's awesome, but when it comes to design it's not the best UI on the planet and so many people just use Atom because it's cute:

<img width="989" alt="screen shot 2017-05-13 at 1 01 42 am" src="https://cloud.githubusercontent.com/assets/2157285/26016088/d5ddd0e2-3778-11e7-95ea-205618f95b4a.png">

If you look at them they have round corners in the tabs, they have multi-layers of borders and shadows and sci-fi like coloring and huge paddings. This makes it very cute

Ever since the first leak photos of Microsoft's new design language, I thought what if VS Code be redesigned in it and just as I heard that Microsoft finally announced it I felt like talking about it here.

I know that UI is one of the biggest parts of VS Code. Just recently #3112: "Support to theme the entire workbench" issue was closed that was one of the biggest features and I get it that it's really a huge task but I feel like a pretty and cute editor can be the final act.

Issues like #12377 show that this is not only my request. I know how the tiniest of details can sometimes be hard to implement (#26113) and I know how much of a big request this is. However, I think is so much worth it if a cuter prettier VSCode is out there.

For example. Look at the auto-complete in Atom vs VS Code:

<img width="336" alt="screen shot 2017-05-13 at 1 21 21 am" src="https://cloud.githubusercontent.com/assets/2157285/26016514/a27f9f80-377a-11e7-9674-b93bb29defac.png">

<img width="533" alt="screen shot 2017-05-13 at 1 21 43 am" src="https://cloud.githubusercontent.com/assets/2157285/26016521/aa90bcea-377a-11e7-9002-6da863fb3372.png">

Atom actually has very bad icons and VS Code has some of the best, cutest best-colored icons that could be in the application. However, just because of better shadows, round corners and no border design in the Atom, it looks better there. If only some basic design concepts are changed within VS Code and if it is implemented in the way of Fluent Design Language it could be much better than any other editor/IDE.

**Comment by FeaRCODE** [comment] 2017-05-18 06:34
I also completely agree with above. I would also like to see the Workbench (file explorer) to have slightly larger icons and some more padding (cozy looking) rather than the current cramp design. Changing the arrow/expand icons to something similar to atom would also be a plus! 

Should i create another issue for this (feature request)? @bpasero

**Comment by bpasero** [comment] 2017-05-18 06:36
Please don't, we have a lot of issues already for more theming support.

**Comment by FeaRCODE** [comment] 2017-05-18 06:37
I thought so, I assume this would be a good place to put it considering the issue is asking for a more fluent cozy design in general :). How would I go about contributing in this area? Mockups?

**Comment by bpasero** [comment] 2017-05-20 16:34
We welcome any kind of UX feedback that we can look at within issues (e.g. screenshots) 👍

**Comment by DRSDavidSoft** [comment] 2018-05-19 21:58
Some progress here: https://github.com/Microsoft/vscode/issues/32257

**Comment by stevencl** [comment] 2018-09-11 10:05
We're pruning the list of open issues at the moment. Given the scope of this request and the progress that has been made on another similar issue (https://github.com/Microsoft/vscode/issues/32257), I'm going to close this issue.

**Closed by stevencl** 2018-09-11 10:05 UTC
Labels: feature-request, ux
