### ISSUE TITLE
Copy from terminal should not retain new line characters for wrapped lines

### ISSUE THREAD

**Issue by tomintaiga** [Microsoft/vscode#23142] opened 2017-03-24 08:51 UTC
- VSCode 1.10.2 
Fixation 8076a19fdcab7e1fc1707952d652f0bb6c6db331 
Date 2017-03-08T14:00:46.854Z 
Shell 1.4.6  
Handler 53.0.2785.143 
Node 6.5.0:
- OS Version: Linux user 4.4.0-67-generic #88-Ubuntu SMP Wed Mar 8 16:34:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux:

Steps to Reproduce:

1. Create python script:
```python
#!/bin/env python3

line = """ "{ \"package\": {\"type\": \"tcp\", \"total_length\" :0, \"header_length\": 0, \"body_length\": 0, \"TCP\": {\"source_port\": -1, \"dest_port\": -1, \"seq_num\": -1, \"ack_num\": -1, \"flag_urgent\": false, \"flag_ack\": false, \"flag_push\": false, \"flag_reset\": false, \"flag_sync\": false, \"flag_finish\": false, \"window\": -1, \"checksum\": -1, \"urgent_pointer\": -1 }}}" """

print(line.replace('\"', '"'))
```

2. Right click->Run python file in terminal
3. Copy data from terminal:
```
"{ "package": {"type": "tcp", "total_length" :0, "header_length": 0, "body_length": 0, "TCP": {"source
_port": -1, "dest_port": -1, "seq_num": -1, "ack_num": -1, "flag_urgent": false, "flag_ack": false, "fl
ag_push": false, "flag_reset": false, "flag_sync": false, "flag_finish": false, "window": -1, "checksum
": -1, "urgent_pointer": -1 }}}"
```
Words "source_port" and "flag_push" and quotes on ' "checksum" ' are changed. So when I copy this text to https://jsonformatter.curiousconcept.com/ I've got invalid json. 

What words are broken, depends on VSCode window size. When I made it large or small, different words became corrupted.

**Comment by rmunn** [comment] 2017-03-27 09:16
I can also reproduce this behavior in F#, with the Ionide F# plugin. Looks like copying a wrapped line from the terminal (that is, a long line that was visually wrapped) ends up copying real LF or CR/LF characters from the terminal, when they were not present in the original line.

Related: if I print a long line to the terminal, then resize VS Code, the line does NOT re-wrap, because the terminal has already inserted linefeeds into the text it printed. This results in remarkably ugly terminal output: either some part of the long line is no longer visible, or there are huge sections of whitespace when the line is wrapped too early. Perhaps that should be tracked as a separate (but related) bug?

**Comment by Tyriar** [comment] 2017-03-27 17:01
Upstream issue: https://github.com/sourcelair/xterm.js/issues/443

Related: https://github.com/sourcelair/xterm.js/pull/609

**Comment by Tyriar** [comment] 2017-06-13 17:58
Merged https://github.com/sourcelair/xterm.js/pull/693 into release branch, fix should come in tomorrow's insiders.

**Closed** 2017-06-13 18:05 UTC
Labels: bug, integrated-terminal, upstream

**Comment by dbaeumer** [comment] 2017-06-29 13:26
Verified, however under Windows the newline is \n which doesn't let you paste into notepad. Opened https://github.com/Microsoft/vscode/issues/29856
