### ISSUE TITLE
Incorrect language scopes (javascript)

### ISSUE THREAD

**Issue by astanciu** [Microsoft/vscode#45308] opened 2018-03-08 15:49 UTC
- VSCode Version: 1.21.0
- OS Version: 10.13.3

The javascript language definition seems to apply the wrong scopes to object properties if the properties are named the same as html types. For ex:
```
let stuff = {name: 'pete', color:'blah', something: 'stuff', id: 1, href='blah'}
stuff.name = 'test'
stuff.color = 'blue'
stuff.id
stuff.href
stuff.something
```

Only `.something` has the correct scopes of `source.js, variable.other.property.js`. 

All the others have `source.js, support.variable.property.dom.js`.

**Comment by mjbvz** [comment] 2018-03-08 19:51
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/523

See the discussion there for the background

**Closed by mjbvz** 2018-03-08 19:51 UTC
Labels: grammar, new release
