### ISSUE TITLE
Markdown Preview only is display on the part of workspace

### ISSUE THREAD

**Issue by SamBlakeKing** [Microsoft/vscode#15872] opened 2016-11-22 09:59 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. When I use  **VSCode** for **Preview function of Markdown** , as the picture shows, the result of Preview only is display on **the part of workspace**. 
![image](https://cloud.githubusercontent.com/assets/15683489/20519200/f4c32318-b0dc-11e6-99e3-ba07b5d9fe81.png)
This is my “**Workspace settings**“. Because I just install VSCode and install "Instant Markdown" and "Markdown Theme Kit" plug-in. Beside, I try to reinstall VSCode and remove ".vscode" folder in current user directory.It likes water off a duck's back.
```
{
    // "markdown.styles": [
    //     ""
    // ]
    "window.zoomLevel": 1
}
```
2. I have use **Debugger for Chrome** plugin for a demo project which only include a html file. There exist some errors.
This is showed in the **console of Chrome**.
```
>Failed to load resource: net::ERR_CONNECTION_REFUSED
>Failed to load resource: the server responded with a status of 404 (Not Found)
```
This is showed in the **console of VSCode**.
```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).

Verbose logs are written to C:\Users\tlm\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\vscode-chrome-debug.txt
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.6.3
debugger-for-chrome: 2.2.1
spawn('C:\Users\tlm\AppData\Local\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://localhost:8080"])
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
```
But It is no error When I try to use **IIS Express** to run the project. 

Ps:
     I use **Windows 10** and the version of **Nodejs** is v6.9.1 which the version of **npm** is 3.10.8.

**Comment by jrieken** [comment] 2016-11-22 12:40
@SamBlakeKing Please file issues in English

**Comment by jrieken** [comment] 2016-11-22 14:34
dupe of https://github.com/Microsoft/vscode/issues/5745

**Closed by jrieken** 2016-11-22 14:34 UTC
Labels: duplicate
