### ISSUE TITLE
Breadcrumbs: should be able to interact with folders in unfocused list

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#54490] opened 2018-07-17 16:38 UTC
Issue Type: <b>Bug</b>

While typing, the search box maintains focus, but users can still use `Enter` to open files from the unfocused list view. However, you cannot operate on folders in the unfocused list view. It would be nice if you could use `Enter` or `RightArrow` to unfold a collapsed folder in the unfocused list view.

VS Code version: Code - Insiders 1.26.0-insider (b48367a8652bd0aa862638bbc24555a70823d3bd, 2018-07-17T05:18:46.758Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.77GB free)|
|Process Argv|C:\Users\t-jakea\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.0
gitlens|eam|8.5.0
tslint|eg2|1.0.34
Go|ms-|0.6.85-symbol-optimized
debugger-for-chrome|msj|4.8.0
subtle-brackets|raf|2.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment] 2018-07-17 16:51
> It would be nice if you could use Enter or RightArrow to unfold a collapsed folder in the unfocused list view.

Tricky... Left/RightArrow has a meaning in text boxes because it moves the cursor.

**Comment by jrieken** [comment] 2018-09-11 09:17
closing as designed

**Closed** 2018-09-11 09:17 UTC
Labels: as-designed, breadcrumbs, under-discussion
