### ISSUE TITLE
Inline styles in HTML files breaks indentation.

### ISSUE THREAD

**Issue by zfor** [Microsoft/vscode#18581] opened 2017-01-15 22:04 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.0.3|
|latex-preview|ajshort|0.5.0|
|jsrefactor|cmstead|0.5.3|
|theme-dracula|dracula-theme|1.2.5|
|vscode-great-icons|emmanuelbeziat|1.1.6|
|monokai-light|ethansugar|0.2.1|
|latex-fania|fania|0.5.0|
|vscode-theme-sunrise|finico|1.0.3|
|Theme-peel|gerane|0.0.2|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|theme-jo-light|ivanzusko|0.0.1|
|Angular1|johnpapa|0.1.15|
|theme-material-theme|jprestidge|1.0.1|
|vscode-icon-theme|jtlowe|1.1.9|
|theme-karyfoundation-themes|karyfoundation|5.0.0|
|Theme-3024Kit|ms-vscode|0.1.1|
|Theme-MaterialKit|ms-vscode|0.1.1|
|Theme-SquirrelsongLight|sapegin|0.0.2|
|html5-boilerplate|sidthesloth|1.0.1|
|theme-bracketslight|ullissescastro|1.0.2|
|html2jade|wmaurer|0.2.0|
|JavaScriptSnippets|xabikos|1.0.0|

---

Steps to Reproduce:

1. Create a new HTML file.
2. Write some HTML in it.
3. Put an inline style on an element e.g.: `<div style="background: red;"></div>`
4. Indentation breaks when auto-indenting the file after the element that has the CSS

```
<body>
	<div>
		<h1 style="color: red;">I'm indented correctly</h1>
<h3>I'm not indented correctly :(</h3>
<span>...</span>
</div>
</body>
```

**Comment by aeschli** [comment] 2017-01-19 10:00
duplicate of #17849

**Closed by aeschli** 2017-01-19 10:00 UTC
