### ISSUE TITLE
[sass] Incorrect validation when using @error directive

### ISSUE THREAD

**Issue by Dervanil** [Microsoft/vscode#24885] opened 2017-04-17 13:44 UTC
- VSCode Version: 
  Version 1.11.2
  Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
  Date 2017-04-13T08:03:11.395Z
  Shell 1.4.6
  Renderer 53.0.2785.143
  Node 6.5.0
- OS Version: Windows 10 Creators Update

Steps to Reproduce:

1. Create a Sass file '.scss'
2. Add a Mixin

```scss

@mixin bp-small {

  @error 'Error';

}

```
The following error occurs:

![image](https://cloud.githubusercontent.com/assets/2516266/25090491/e5beec4a-2359-11e7-856f-c1d7255f4fd4.png)

![image](https://cloud.githubusercontent.com/assets/2516266/25090560/4b50e32e-235a-11e7-8fd4-a55eee119f81.png)

The order doesn’t  affect the error:

![image](https://cloud.githubusercontent.com/assets/2516266/25090417/71518dc2-2359-11e7-8aa4-84383d212def.png)

![image](https://cloud.githubusercontent.com/assets/2516266/25090376/2f335196-2359-11e7-9e7b-916e30edb8a0.png)

**Comment by aeschli** [comment] 2017-04-18 07:53
duplicate of #22735

**Closed by aeschli** 2017-04-18 07:53 UTC
