### ISSUE TITLE
Intellisense sometimes doesn't work

### ISSUE THREAD

**Issue by haani104** [Microsoft/vscode#25289] opened 2017-04-25 12:27 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|flow-for-vscode|flowtype|0.5.0|
|vscode-icons|robertohuertasm|7.5.1|
|Align|steve8708|0.2.0|;

---
Hi guys, first of all, vscode is a very powerful tool. I use it for my frontend development, Lately I have been facing issues with iIntellisense, i.e. sometimes it doesn't work. When I hover over a variable, it just show loading text. When I cmd + click on a particular function, it doesn't go to the it's definition.
Whenever I encounter it I have to restart the vscode to make it working.

I don't have steps to reproduce, but I suspect |vscode-eslint|dbaeumer|1.2.8| is impacting the intellisense.

**Comment by mjbvz** [comment] 2017-04-25 22:02
To check if an extension is the root cause here, try running code using the `--disable-extensions` flag.

If you still see this issue, you may also want to try the current VSCode insiders build. This includes a number of fixes for these sort of hangs while working with JS/TS files. 

Let me know if either of those solve the problem for you

**Comment by mjbvz** [comment] 2017-05-02 00:50
Closing as we need more information to investigate this.

@haani104 Please try out the latest vscode insiders build with extensions disabled and let me know if you are still seeing this issue

**Comment by haani104** [comment] 2017-05-05 06:17
Hi,
I have installed the insiders build, i.e. Version 1.12.0-insider (1.12.0-insider) and when intellisense doesn't work below errors I see in dev console.

```
Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at e.onModelDecorationsChanged (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:651773)
    at t._onEvents (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:661808)
    at t.onEvents (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:659485)
    at file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:657461
    at r (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:40311)
    at t._emitEvents (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:44047)
    at t.e._emitCollected (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:43392)
    at t.e.endDeferredEmit (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:43135)
    at t.changeDecorations (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:957491)
    at t.deltaDecorations (file:////Users/haani/Downloads/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:958244)
```

**Comment by mjbvz** [comment] 2017-05-05 06:32
@haani104 Did you try disabling extensions? That an exception is hit seems like a bug on our side, but an extension may be causing this in the first place

**Comment by haani104** [comment] 2017-05-05 06:37
Ok, I am having themes installed. Will disable all extension and if the error comes again, will update here.

**Comment by haani104** [comment] 2017-05-05 10:02
Still getting the same error after disabling the extensions

**Comment by mjbvz** [comment] 2017-05-18 01:33
@haani104  Can you give the latest VSCode 1.12.2 a try and also the latest insiders builds to see if this was fixed.

Also, this looks like the same stack trace as in #25822. Is that the case? The javascript intellisense getting disabled may just be a symptom of some other problem here

**Closed** 2017-05-25 03:30 UTC
Labels: javascript, needs more info
