### ISSUE TITLE
Font-Family and Font-Size Option for Explorer

### ISSUE THREAD

**Issue by ashupanwar10** [microsoft/vscode#231468] opened 2024-10-16 07:15 UTC
Hi,

Can we also have the options to change the font-family font-size option in the settings for explorer as well?

**Comment by lramos15** [comment] 2024-10-16 13:43
Duplicate of 3519

**Closed by lramos15** 2024-10-16 13:43 UTC

**Comment by manuartero** [comment] 2024-10-17 07:52
@lramos15 can you pin the team to take a look to a ~10 years issue (#519), since it's provoking the request to be "\*marked as duplicated\*" maybe you can consider this a11y request.
