### ISSUE TITLE
Indentation setting changes when Code loses focus

### ISSUE THREAD

**Issue by patik** [microsoft/vscode#84701] opened 2019-11-13 15:33 UTC
Issue Type: <b>Bug</b>

1. Open a file that is recognized as being indented with 2 spaces (in my case, a Java file)
2. Use the command pallette to change the indentation to 4 spaces
3. Notice that the faint vertical guides have changed (there's one every 4 characters now, instead of every 2, which is correct)
4. Optionally format the file (with command pallette or by saving)
5. Switch to another window (besides Code)
6. Switch back to Code
7. The indentation has been reverted to 2 spaces

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 7|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|-psn_0_90134|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
indenticator|Sir|0.6.0
html-snippets|abu|0.2.1
cucumberautocomplete|ale|2.14.1
npm-intellisense|chr|1.3.0
regex|chr|0.2.0
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|10.1.2
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|3.4.1
flow-for-vscode|flo|1.5.0
auto-rename-tag|for|0.1.1
macros|ged|1.2.1
vscode-pull-request-github|Git|0.13.0
gc-excelviewer|Gra|2.1.32
vscode-text-pastry|jkj|1.2.0
yelpcheetah|joe|1.0.1
node-module-intellisense|lei|1.5.0
git-graph|mhu|1.18.0
theme-monokai-pro-vscode|mon|1.1.14
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|4.0.3
vsliveshare|ms-|1.0.1123
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
typescript-hero|rbb|3.0.0
java|red|0.52.0
duplicatetext|riv|0.0.3
code-settings-sync|Sha|3.4.3
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.5.0
twig|wha|1.0.2
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2020-11-04 19:43
I'm not able to reproduce this issue in latest VS Code stable on macOS. closing it for now but we can reopen if you are seeing it still.

**Closed by rebornix** 2020-11-04 19:43 UTC
Labels: bug, editor-indent-detection

**Comment by jjjjeeffff** [comment] 2020-12-05 05:33
I'm experiencing this now with latest VS Code on macOS. Specifically with a YAML file. I select 2 space indentation and switch window focus to another app and come back to 4 space indentation.

**Comment by villlem** [comment] 2020-12-05 06:07
I had the same problem and for me it was caused by another extension
(editor config) was misconfigured.
