### ISSUE TITLE
code-insiders: copypasta not working

### ISSUE THREAD

**Issue by noahehall** [microsoft/vscode#187337] opened 2023-07-08 01:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0-insider ad791ef3d26b99963da31636af697afd86575435x64
- OS Version: Ubuntu 22.04.2 LTS

Steps to Reproduce:

- copy text, and it pastes as a markdown link

https://github.com/microsoft/vscode-eslint/assets/10324554/bf642eb4-a1bb-4b7d-97ea-f5eda7c15084

```[tasklist]
### Tasks
- [ ] make copilot free again ;)~
```

**Comment by noahehall** [comment] 2023-07-08 01:29
interestingly can only reproduce randomly; started occuring with this latest update

**Comment by MeghanKulkarni** [comment] 2023-07-20 01:07
duplicate of https://github.com/microsoft/vscode/issues/187201

**Closed by MeghanKulkarni** 2023-07-20 01:07 UTC
Labels: markdown
