### ISSUE TITLE
Missing screen redraw after resize

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8451] opened 2016-06-28 21:40 UTC
Testing #8222.

1. Open the terminal
2. cd to a directory with some entries
3. `ls -lasi`
4. use the left border to horizontally resize the window
5. make the console so narrow that text is 'cut off' on the right (scrolls out of the window)
6. resize console back to its original size
-> text that was cut off in step 5 remains cut off

**Comment by Tyriar** [comment] 2016-06-29 06:50
Duplicate of https://github.com/Microsoft/vscode/issues/8336

**Closed by Tyriar** 2016-06-29 06:50 UTC
Labels: bug, integrated-terminal, upstream
