### ISSUE TITLE
vscode occur error when i save 973M txt file

### ISSUE THREAD

**Issue by FayuanLi** [Microsoft/vscode#32601] opened 2017-08-16 01:50 UTC
- VSCode Version: 1.15.0 64bit
- OS Version: windows 10 1703 64bit

Steps to Reproduce:

1.open 973m txt file
2.del last empty line and save
3.occur error:Invalid string length

**Comment by alexandrudima** [comment] 2017-08-19 10:43
Duplicate of #32503

**Closed by alexandrudima** 2017-08-19 10:43 UTC
Labels: new release, workbench
