### ISSUE TITLE
Show 'Last updated' on the extension page inside of VSCode.

### ISSUE THREAD

**Issue by Yzrsah** [Microsoft/vscode#67900] opened 2019-02-05 02:30 UTC
It would be very good if we could see release dates for extensions, right inside of VSCode.

Currently the extension page has no information about release or update dates.
- No information about 'Released on' or 'Last updated'
- The changelog has no dates

We have to go to the web page to get that information, but it should be available inside of VSCode.
This could make it easier to know when extensions are older or unmaintained

It should show:
- Released on 1/1/2019, 9:00:00 AM
- Last updated 2/1/2019, 9:00:00 AM

**Comment by sandy081** [comment] 2019-02-12 11:53
Duplicate of #41404

**Closed** 2019-02-12 11:53 UTC
Labels: *duplicate, extensions
