### ISSUE TITLE
Feature Request: Is it possible to get a search feature in Debug Console and Terminal?

### ISSUE THREAD

**Issue by bansalvks** [Microsoft/vscode#32316] opened 2017-08-11 11:51 UTC
Hi Team,

I am a fan of VS Code and it the only IDE that I use for web and server development. however I always miss a feature which is a basic search in terminal window and debug console.

It is possible to expect such a feature in future?

Your Fan,
Vikas Bansal

**Comment by weinand** [comment] 2017-08-11 12:25
Search exists already for Terminal.

**Comment by bansalvks** [comment] 2017-08-14 17:13
Hi @weinand 

Thanks for replying dear, and great to know that terminal already has a option to find.

I would just say that I will be very comfortable for developers, if they can search in the logs that are printed on the debug console as have to check manually or got to copy paste the whole debug console into some text editor.

As ever, VS Code Fan,
Vikas Bansal

**Comment by isidorn** [comment] 2017-08-28 12:57
Thanks for feedback however this is a duplicate of https://github.com/Microsoft/vscode/issues/4338

**Closed by isidorn** 2017-08-28 12:57 UTC
Labels: debug, feature-request
