### ISSUE TITLE
Icon Design Unification

### ISSUE THREAD

**Issue by streamich** [microsoft/vscode#79529] opened 2019-08-20 17:59 UTC
Great work on unifying icon designs: #8017 🎉🙏❤️👏

Would VSCode also consider designing icons for popular extensions? For example, it could provide a pool of icons that extensions could use.

Below is an icon provided I believe by Git Lens, which has much thicker strokes than the rest of the icons:

![image](https://user-images.githubusercontent.com/9773803/63371601-a736da00-c384-11e9-8414-4150583a089f.png)

In the same screenshot you can see similar but different Git icons:

![image](https://user-images.githubusercontent.com/9773803/63371713-e6fdc180-c384-11e9-8afd-9ed41b3417b6.png)

**Comment by importnetminecraft** [comment] 2019-08-20 21:28
In #77411 they are updating extension icons. You should submit a bug report to the extension if you want their icons to change. Octicons already provide an icon pool for extensions to use which they are planning on updating.

**Comment by RMacfarlane** [comment] 2019-08-20 22:18
Duplicate of https://github.com/microsoft/vscode/issues/77411, there's also now a library of icons extensions can use, see #74974

**Closed by RMacfarlane** 2019-08-20 22:18 UTC
