### ISSUE TITLE
Visual Studio Code Server

### ISSUE THREAD

**Issue by Adiqq** [Microsoft/vscode#30817] opened 2017-07-16 19:34 UTC
Hi,

I'd like to ask about feature that came recently to my mind.
Let's say that we have Vagrant or just plain VM.
Let's say we use Rust or similiar programming language where we have appropriate extensions for VSCode, but they require some time and knowledge to setup (Rust Language Server etc.).
Let's say that we have beginner programmers that may use Windows, Linux or Mac and it's cumbersome for them to setup development environment themselves, so it should be possible to just download code, run prepared Vagrant VM and have everything up and running.

Now, it would be nice if this virtual machine had some "Visual Studio Code Server" (and that's my requested feature), so we would have Visual Studio Code on our host machine that can connect to this server on VM (ssh?), use server's configuration, plugins and allow to browse file, folders, execute commands provided by extensions, use terminal, remotely.

I can see huge value in this feature, because it would allow to provide seamless, friendly experience, even for most complicated projects.

**Comment by kumarharsh** [comment] 2017-07-17 06:25
@Adiqq in the meanwhile, check out the [recommended extensions](http://go.microsoft.com/fwlink/?LinkId=827846) section for adding recommendations for new users. I use it in my repo, and it saves a lot of headache while onboarding new people.

**Comment by mjbvz** [comment] 2017-11-03 21:39
Duplicate of #29194

**Closed by mjbvz** 2017-11-03 21:39 UTC
Labels: duplicate, feature-request
