### ISSUE TITLE
workbench.action.nextEditor and/or workbench.action.previousEditor changes webview-based extension active element

### ISSUE THREAD

**Issue by janisdd** [microsoft/vscode#101750] opened 2020-07-05 13:15 UTC
### Issue Type: Bug

When a web-base extension is open and one uses `workbench.action.nextEditor` and/or `workbench.action.previousEditor` to switch tabs/editor the `document.activeElement` switches from iframe to body.
As a result the extension has no longer focus and no keypresses are registered by the extension.

- VSCode Version: 1.46.1
- OS Version: mac 

Steps to Reproduce:

1. Open an webview-based extension (that uses `retainContextWhenHidden: true`)
2. Open the Developer Tools for the extension and execute in the console `var handle = setInterval(() => console.log(document.activeElement), 1000)`
2. Open other tabs/editors
3. Use the commands (View: Open Next Editor, workbench.action.nextEditor) and/or (View: Previous Editor, workbench.action.previousEditor) to switch between the tabs/editors  
   *sometimes the commands must be executing multiple times*

4. At some point the `document.activeElement` switches from the iframe (extension) to the body (outside the extension)
5. (Use `clearInterval(handle)` to clear the interval or close the extension tab)

I tried this for 3 extensions and can reproduce it for all. At least one (my own extension) uses `retainContextWhenHidden: true` when creating the web view (the others probably too).

When I use the mouse to open the tabs the `document.activeElement` stays on the iframe.

I'm not sure if this is intended or a bug but I think the active element should not change (same as using the mouse to switch tabs).

**Comment by mjbvz** [comment] 2020-10-20 03:43
Duplicate of #84216 I believe

**Closed by mjbvz** 2020-10-20 03:43 UTC
Labels: help wanted, webview
