### ISSUE TITLE
editor.actions.findWithArgs to resolve variables such as ${selectedText}

### ISSUE THREAD

**Issue by dimateos** [microsoft/vscode#180835] opened 2023-04-25 15:28 UTC
At the momment `editor.actions.findWithArgs` does not solve variables when executed.

* This also used to be the case with `workbench.action.findInFiles noted previously`, as noted in https://github.com/microsoft/vscode/issues/173653 and solved in https://github.com/microsoft/vscode/pull/175715.

Although in this command there is nothing interesting to do with relative paths etc, I personally found a use case:
```jsonc
{
    "key": "ctrl+r ctrl+f",
    "when": "editorFocus || editorIsOpen",

    // Regular editor.action.startFindReplaceAction does not touch the replace field
    //  and when replacing I prefer to start with the original text.
    "command": "editor.actions.findWithArgs",
    "args": {
        "searchString": "${selectedText}",
        "replaceString": "${selectedText}",
    }
},
```
![image](https://user-images.githubusercontent.com/26868611/234323962-cfaabf05-627b-4dff-b192-6f5f65a192ad.png)

**Comment by amunger** [comment] 2023-12-13 20:43
closing as dupe of https://github.com/microsoft/vscode/issues/151311

**Closed by amunger** 2023-12-13 20:43 UTC
Labels: bug, editor-find
