### ISSUE TITLE
Native Notebooks - Scroll Broken? 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#123578] opened 2021-05-11 14:44 UTC
VS Code Version: 1.57.0-insider

Open a notebook and scroll - get chopped scrolling and takes time to catch up and align with correct spot again 
![image](https://user-images.githubusercontent.com/19276747/117835244-aca91780-b22c-11eb-88ff-3df280006a77.png)

**Comment by claudiaregio** [comment] 2021-05-11 16:33
Stable Recording

![Scroll Broken](https://user-images.githubusercontent.com/19276747/117852188-f0574d80-b23b-11eb-966b-9467204349c2.gif)

**Comment by claudiaregio** [comment] 2021-05-11 16:58
Issue solved by completely uninstalling vs code and reinstalling

**Comment by rzhao271** [comment] 2021-07-06 20:09
Closing for now, as I'm unable to reproduce the issue. Feel free to comment on this issue, or create a new one, if it happens again.

**Closed** 2021-07-06 20:10 UTC
Labels: *not-reproducible, notebook
