### ISSUE TITLE
Paths in Debug Console output are not linked

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#39063] opened 2017-11-23 22:17 UTC
Raised in https://github.com/Dart-Code/Dart-Code/issues/451; filenames in the debug console don't seem to be being linked. I've tried a bunch of different formats/categories to try and make this work, but none seem to:

```ts
this.sendEvent(new OutputEvent(`Danny3 (lib/test.dart:1:1)\n`, "stdout"));
this.sendEvent(new OutputEvent(`Danny3 (lib/test.dart:1:1)\n`, "console"));
this.sendEvent(new OutputEvent(`Danny3 (lib/test.dart:1:1)\n`, "stderr"));
this.sendEvent(new OutputEvent(`Danny3 lib/test.dart:1:1\n`, "stdout"));
this.sendEvent(new OutputEvent(`Danny3 lib/test.dart:1:1\n`, "console"));
this.sendEvent(new OutputEvent(`Danny3 lib/test.dart:1:1\n`, "stderr"));
this.sendEvent(new OutputEvent(`Danny3 ./lib/test.dart:1:1\n`, "stdout"));
this.sendEvent(new OutputEvent(`Danny3 ./lib/test.dart:1:1\n`, "console"));
this.sendEvent(new OutputEvent(`Danny3 ./lib/test.dart:1:1\n`, "stderr"));
```

<img width="479" alt="screen shot 2017-11-23 at 22 11 41" src="https://user-images.githubusercontent.com/1078012/33189539-83653af0-d09b-11e7-9986-de7854e9be84.png">

The file does exist relative to the workspace root, though from what I've read in related cases, it seems that you no longer do `fs.stat` when deciding to link. I've found many cases suggesting there have been improvements/fixes to this and screenshots showing it working, so I'm not sure what's different about ours.

Are the rules about what formats are detected documented anywhere for me to check? If not, what's the best way to debug?

**Comment by isidorn** [comment] 2017-11-24 09:06
Hey @DanTup yeah the file detection is not in the best shape and I will close this as a duplicate of the file detection umbrela item. https://github.com/Microsoft/vscode/issues/34026
In the meantime here's a code pointer and we accpet PRs that improve this
You can always put a breakpoint there and check what is going on
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/linkDetector.ts#L13

**Closed by isidorn** 2017-11-24 09:06 UTC
Labels: debug

**Comment by DanTup** [comment] 2017-11-24 10:54
Cool thanks; I found a bunch of cases suggesting it should all work but didn't come across that one.

> Also consider a way for extensions to contribute link detection rules

That would solve another issue I have too! :-)

I'll see if I can find some time to dig into why the simple case isn't working for us currently. Thanks!
