### ISSUE TITLE
VS Code doesn't use default terminal profile on startup

### ISSUE THREAD

**Issue by Lubjan** [microsoft/vscode#132953] opened 2021-09-12 17:37 UTC
Issue Type: <b>Bug</b>

I've use a custom cmder profile for the terminal, since the last patch (after the terminal profile migration) it always starts with Powershell 6 profile instead. If I kill the terminal and open a new terminal or open a second instance of VS Code, the right profile is loaded.

Expected behaviour: Use the default terminal profile on startup of VS Code

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800XT 8-Core Processor             (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (20.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-nginx-conf|ahm|0.1.3
Handlebars|and|0.4.1
ng-template|Ang|12.2.0
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.6.14
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
angular2-snippets|dan|1.0.21
vscode-eslint|dba|2.1.25
vscode-deno|den|3.8.1
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
apacheconf-snippets|eim|1.3.0
prettier-vscode|esb|8.1.0
go|gol|0.27.2
vscode-graphql|Gra|0.3.18
todo-tree|Gru|0.0.214
vscode-nginx-conf-hint|han|0.1.0
vscode-power-mode|hoo|2.2.0
composer|ika|0.7.1
phpcs|ika|1.0.5
search-node-modules|jas|1.3.0
angular-essentials|joh|12.0.0
Angular1|joh|0.2.1
Angular2|joh|12.0.0
vscode-codemetrics|kis|1.24.0
tailwind-sass-syntax|mac|1.3.0
VS-code-vagrantfile|mar|0.0.7
openapi-lint|mer|1.2.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.10.0
vscode-language-pack-de|MS-|1.60.3
jupyter-keymap|ms-|1.0.0
powershell|ms-|2021.9.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4836
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
angular2-inline|nat|0.0.17
php-docblocker|nei|2.4.0
vscode-for-node-js-development-pack|nod|2.0.1
laravel-blade|one|1.25.0
laravel5-snippets|one|1.13.0
vscode-css-navigation|puc|1.10.7
nginx-formatter|ray|0.0.13
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
rust|rus|0.7.8
laravel-artisan|rya|0.0.28
code-settings-sync|Sha|3.4.3
vscode-autohotkey|sle|0.2.2
lua|sum|2.3.7
language-stylus|sys|1.13.0
vscode-icons|vsc|11.6.0
nodejs-extension-pack|wad|0.1.9
vscode-nginx|wil|0.7.2
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by corshidan** [comment] 2021-09-12 20:34
Following !!
Since this is quite annoying to have to change terminal everytime I re-open VScode

**Comment by IllusionMH** [comment] 2021-09-13 09:36
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-13 09:36 UTC
Labels: *duplicate
