### ISSUE TITLE
Quick File Navigation as you type

### ISSUE THREAD

**Issue by imperez** [Microsoft/vscode#6132] opened 2016-05-05 14:09 UTC
It would be great when I want to perform a Quick Open on a file that VSCode would search as I type. Atom and Sublime do this and it makes finding files so much easier.

**Comment by bpasero** [comment] 2016-05-06 06:08
@imperez can you clarify? VS Code does search as you type.

**Comment by imperez** [comment] 2016-05-06 14:03
Sure I can give more info comparing how Atom and VSCode both work in this situation.

In Atom, when you first search for a file it will index all of your files. Then, when you start typing a couple characters you instantly see file suggestions. This is great because it gives you a chance to see if you mistyped something or quickly see the file you want.

As for VScode, yes it does search as you type for files it previously indexed but if you start typing a filename that hasn't been indexed yet VSCode waits until you stop typing or hit enter before it performs a search. On small projects this is not terrible but for large projects that scan can take some time and cause some extra wait time.

Is there a way to make VSCode index periodically in the background? That way Quick Open would be faster and there would less chances of waiting for suggestions to show?

**Comment by bpasero** [comment] 2016-05-06 14:09
Ok, lets close this one as duplicate of https://github.com/Microsoft/vscode/issues/55 which is about introducing a faster search in general.

**Closed by bpasero** 2016-05-06 14:09 UTC
Labels: needs more info
