### ISSUE TITLE
JS Intellisense/Document Formatter not working in SSH/remote workspace

### ISSUE THREAD

**Issue by TunaLatte** [Microsoft/vscode#51700] opened 2018-06-12 14:19 UTC
As the title suggests, its easy to reproduce the problem in the new FileSystemProvider, added in version 1.23.0 of Visual Studio Code. From my testing javascript file right click context menu behaves the same way with unknown extension (no formatting option, syntax highlight works), suggesting that JS formatter only works with local filesystem?
Extension issue ticket reference: https://github.com/SchoofsKelvin/vscode-sshfs/issues/16

**Comment by mjbvz** [comment] 2018-06-12 16:41
@jrieken We limit the js/ts providers to `untitled` and `file` schemes. Is this still the correct thing to do?

**Comment by jrieken** [comment] 2018-06-13 13:43
Shouldn't be needed anymore, We gave LS a special overwrite to steel certain document from you...

**Comment by SchoofsKelvin** [comment] 2018-06-22 16:52
Any progress on this? I've done a quick check and both intellisense and formatting .js files provided by a FileSystemProvider don't work. Trying to format shows `There is no document formatter for 'javascript'-files installed.` as an information message.

The same happens for TypeScript (`.ts`) files, namely no intellisense or type and even syntax checking. Formatting produces the same message, although with `typescript` instead of `javascript` of course.

**Comment by jdwieber** [comment] 2018-07-11 21:17
I'm experiencing the same problem with intellisense in c++ projects. I'm using the same vscode-sshfs extension with vscode-cpptools. In my c_cpp_properties.json file I specify paths like this:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}",
                "ssh://path/to/search/"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "clang-x64"
             "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by foorschtbar** [comment] 2018-12-19 16:48
Same problem here with sshfs and Extensions like PHP IntelliSense. Wait for a fix...

**Comment by julien-moreau** [comment] 2019-02-26 20:44
Hey @mjbvz 
Just for information, do you have any news about this issue? Or an ETA as to when this issue will be addressed?
Thanks for your answer :)

**Comment by mjbvz** [comment] 2019-02-26 22:07
Duplicate of #59650

**Closed by mjbvz** 2019-02-26 22:07 UTC
Labels: bug, javascript
