### ISSUE TITLE
Duplicate inconsistent files created on typescript refactor.

### ISSUE THREAD

**Issue by waratah** [Microsoft/vscode#49590] opened 2018-05-10 02:43 UTC
Issue Type: <b>Bug</b>

When doing a quick fix refactor of a file inside a directory with an upper case character I get a duplicate file open with the fix but the copy I am working on is not fixed.

Result is I end up with file fred.ts open twice with different content after a mouse over refactor.   NOTE this issue is inconsistent,  mostly works.

This only appears to happen when I search for files and select the file from the search (in this case I searched for console.error)

The file roleEntryComponent.ts exists in the Common directory.

I get into the code and I add the notification service to the constructor in the typescript file:

```
class RolesEntryComponent {

  static $inject = ['rolesService', 'translationService', 'SchoolAssignTypeApi'];

  constructor(
    private rolesService : IRolesService,
    private translationService : ITranslationService,
    private assignedType: SchoolAssignTypeApi,
  ) {
  }
```

I add:

```
 private notificationService : INotificationService,
```

The system highlights INotificationService with a red underline.   I then click within the text and I get a mouse prompt on the left somewhere.

I mouse over and select Quick Fixes

I then select `"import { INotificationService } from '../interface';`

A second copy of the file is open with the changes and not focussed.  roleEntryComponent.ts is open twice.   The first filename has a directory name of '../Common',   the second (newer) file has a directory name of '../common'.   Note the lower case.

If I miss the duplication then I often get inconsistent saves and have to redo work.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
beautify|Hoo|1.3.0
gitlens|eam|8.2.4
tslint|eg2|1.0.28
auto-rename-tag|for|0.0.15
mssql|ms-|1.3.1
csharp|ms-|1.14.0
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-05-21 21:35
Duplicate of #40682

**Closed by mjbvz** 2018-05-21 21:35 UTC
