### ISSUE TITLE
code-alpha --install-extension: How to know the id

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6805] opened 2016-05-24 13:48 UTC
Testing #6099

When installing an extension with `code-alpha --install-extension` I need to pass the id that includes publisher and name.
It's not easy to find that id out. Especially the publisher part is not mentioned on the marketplace page itself: https://marketplace.visualstudio.com/items?itemName=donjayamanne.python
It is in the URL of that page though.

It would be good if it where as easy as described here
![image](https://cloud.githubusercontent.com/assets/6461412/15506189/fd130920-21c6-11e6-8c12-6a2785110bd7.png)

**Comment by joaomoreno** [comment] 2016-05-24 14:00
Duplicate of #6768

**Closed by joaomoreno** 2016-05-24 14:00 UTC
