### ISSUE TITLE
Improvement Request: Explorer Find should automatically unfold folders

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#167181] opened 2022-11-24 14:31 UTC
To get an overview of a new project's structure I was searching for a particular file extension in Explorer.

I was very surprised to see that the Explorer Find "filter" option (`"workbench.list.defaultFindMode": "filter"`) doesn't automatically unveil files in folded directories:

![Explorer find should unfold folders](https://user-images.githubusercontent.com/9283914/203806283-81a38a3b-16ed-4b41-94c2-68b169f84d77.gif)

I believe this is confusing as in larger projects it's easy to have a directory folded and miss files when using the Explorer Find operation.

So, I'd like to propose to add a new option to File Explorer to have Find mode "filter" …
1. automatically unfold folders containing matched files (with a detain delay of 300 ms to keep the unfolding algorithm from expanding all folders when the first letter has been typed by the user)
2. automatically restore all folders fold/unfold state when Find input dialog is closed; except when one or more of these files are currently selected. Then the folders of the selected files should be expanded after restoring the previous folded/unfolded state.

The name of that enum setting may be similar to: `"workbench.list.expandMatchingFolders"` and possible values may be:
- `no`  -- current behaviour, no folder expansion is taking place
- `yesAndRestore`  -- unfold all matching folders; restore all folders when Find dialog is closed, but keep selected files' folders expanded
- `yesAndKeepExpanded`  -- unfold all matching folders; keep all folders containing matched files open when Find dialog is closed (regardless of files being selected), restore all other folders to their previous state

**Comment by IllusionMH** [comment] 2022-11-24 22:21
This is essentially duplicate of #66971 with additional text and options.

**Comment by SetTrend** [comment] 2022-11-25 11:06
Ah, yes. I guess someone at GitHub needs to invent semantic search. I'd never have searched for "resolve folders".

**Comment by SetTrend** [comment] 2022-11-26 00:09
The suggested algorithm would be quite simple and easy to implement:

<br/>

1. **_Filter dialog opens, initialize:_**
  - Store the paths (resp. Ids) of all folders currently being expanded in Explorer into an array (e.g. `expandedFolders: string[] = …;`).

<br/>

2. **_While searching:_**
  - When the first character is being typed into Filter text input box, expand all folders in Explorer. (This will boost overal filtering performance.)
  - Perform filtering as you do already.

<br/>

3. **_Filter dialog closes, finalize:_**
  - ```ts
    switch (config.workbench.list.expandMatchingFolders)
    {
      case expandMatchingFoldersType.yesAndRestore:
        expandedFolders.concat(selectedFolders);
        break;

      case expandMatchingFoldersType.yesAndKeepExpanded :
        expandedFolders.concat(matchingFolders);
        break;
    }
    ```
  - Collapse all folders. (This task already exists in the Explorer toolbar.)
  - Expand all folders listed in `expandedFolders`.
  - Select all matching files.

**Comment by lramos15** [comment] 2022-11-28 14:14
Will close as duplicate of #66971 here these folders have already been resolved, but the filter is still just a visual one meaning collapsed nodes aren't acted upon. This is highly requested fix and it is on our radar.

**Closed by lramos15** 2022-11-28 14:14 UTC
