### ISSUE TITLE
showing html file as django file

### ISSUE THREAD

**Issue by Amrut-47** [microsoft/vscode#137817] opened 2021-11-24 19:21 UTC
Issue Type: <b>Bug</b>

The html file is showing as django file in VScode. When  I try to write in that file it automatically taking django syntax in html file and didn't showing html syntax correctly.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.37GB (1.52GB free)|
|Process Argv|--crash-reporter-id 0c344217-6874-4e9c-8b54-48266dc8b247|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|1.6.0
vscode-tailwindcss|bra|0.7.2
bracket-pair-colorizer|Coe|1.0.61
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-env|Iro|0.1.0
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.10.0
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.5.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246cf:30401891
vscexrecpromptt2:30404948
vscop804:30404766
vs360cf:30404996

```

</details>

**Comment by aeschli** [comment] 2021-11-25 07:59
This is caused by the `vscode-django` extension. It reassigns `.html` to the language django.

You need to uninstall the extension or reassign `.html` to HTML again.

**Closed by aeschli** 2021-11-25 07:59 UTC
