### ISSUE TITLE
更新之后，就跳不过去了。上一个版本点击连接能直接跳过去那个文件，现在直接找不到了

### ISSUE THREAD

**Issue by hasubasora** [Microsoft/vscode#40959] opened 2017-12-30 02:55 UTC
<link href="/views/Game/dist/style.css" rel="stylesheet" />
这种类型
更新之后，就跳不过去了。上一个版本点击连接能直接跳过去那个文件，现在直接找不到了
![image](https://user-images.githubusercontent.com/22046081/34450840-cf171010-ed4f-11e7-829c-927540db372d.png)

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
pug|ama|1.0.1
vscode-babel-coloring|dza|0.0.4
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
code-beautifier|mic|1.7.2
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-scss|mrm|0.6.2
vetur|oct|0.11.5
vscode-html-scss|P-d|0.0.42
sass-indented|rob|1.4.6
JavaScriptSnippets|xab|1.5.0

(9 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by morland96** [comment] 2017-12-31 09:14
If you want more comments. Please use English.
For your problem. Plese double check you path. Mine is works fine.

**Comment by rebornix** [comment] 2018-09-05 00:46
I can't reproduce this with latest version. Close it for now and feel free to reopen if you still have issues.

**Closed by rebornix** 2018-09-05 00:46 UTC
Labels: editor-links
