### ISSUE TITLE
The Git Viewlet refreshes when doing file operations outside of the main folder

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29720] opened 2017-06-28 08:37 UTC
Testing #29176

* on Windows
* open a folder `working_dir` that is using `.git`
* add an unrelated root folder
* in the explorer, copy-paste a file
* observe how the git viewlet refreshes, even though nothing happened in `working_dir`.

fyi @jrieken -- I'm not sure what the root cause of this could be (w.r.t. file events), I would assume the git extension (being correct in the single folder case) would not suffer from this issue.

**Comment by joaomoreno** [comment] 2017-06-28 09:13
Yeah surely related to the API: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/model.ts#L379

**Comment by jrieken** [comment] 2017-06-28 09:15
No, the API just forwards whatever comes from the backend. Surely file watcher related.

**Comment by Tyriar** [comment] 2017-06-28 19:42
This is what I see in the file watcher logs when running via `--verbose`:

```
[IPC Library: Watcher] [CREATED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git\index.lock
ipc.cp.ts:164 [IPC Library: Watcher] [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [ADDED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git\index.lock
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git
ipc.cp.ts:164 [IPC Library: Watcher] [DELETED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git\index.lock
ipc.cp.ts:164 [IPC Library: Watcher] [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [DELETED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git\index.lock
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git
ipc.cp.ts:164 [IPC Library: Watcher] [CREATED] c:\Users\daimms.REDMOND\Documents\dev\test-folder\gulpfiles.js
ipc.cp.ts:164 [IPC Library: Watcher] [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\test-folder\gulpfiles.js
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [ADDED] c:\Users\daimms.REDMOND\Documents\dev\test-folder\gulpfiles.js
ipc.cp.ts:164 [IPC Library: Watcher] [CREATED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git\index.lock
ipc.cp.ts:164 [IPC Library: Watcher] [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [ADDED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git\index.lock
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git
ipc.cp.ts:164 [IPC Library: Watcher] [DELETED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git\index.lock
ipc.cp.ts:164 [IPC Library: Watcher] [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [DELETED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git\index.lock
ipc.cp.ts:164 [IPC Library: Watcher]  >> normalized [CHANGED] c:\Users\daimms.REDMOND\Documents\dev\vscode\.git
```

The `.git` and `.git\index.lock` events are fired because of vscode pinging for `git` status periodically, and the ignore pattern includes:

```js
"**/.git/objects/**": true,
"**/.git/subtree-cache/**": true
```

Also what does it mean for the git viewlet to refresh? The progress bar up the top showing?

**Comment by joaomoreno** [comment] 2017-06-29 07:28
Note that I already ignore the right stuff:

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/model.ts#L631

**Comment by alexandrudima** [comment] 2017-06-29 07:30
Here are my expectations:

---

#### 1. When working with two folders using two separate VS Code windows
* Open a window with a folder `A` **with** a git repository 
* Open another window with a different folder `B` **without** a git repository
* Configure the windows to be shown side-by-side
* Create a new file in folder `B`
* Observe: the git viewlet in folder `A` does not refresh (the icon does not change to indicate refreshing); **there is no CPU or FS burden on my machine because I am not touching something impacting folder `A`**. This is correct.

---

#### 2. When working with two folders using a single VS Code window
* Open a window with a folder `A` **with** a git repository
* Add a root folder `B` **without** a git repository
* Create a new file in folder `B`
* Observe: the git viewlet refreshes (the icon changes to indicate refreshing); **there is CPU and FS burden on my machine for no good reason**. This is unexpected.

---

Since the git extension functions correctly in the single root folder case and does not consume needless CPU when editing files in a different folder, I would expect the git extension to continue functioning correctly and not consume needless CPU also in the multi root folder case. That's why I pinged @jrieken as this is IMHO a breaking change: here is a case where an extension is **broken** by the multi-root case through the seemingly innocuous file watching API.

---

Here are gifs for your convenience demonstrating the problem (hopefully this helps in reproducing):

#### 1. Observe no git process is executed
![two-windows](https://user-images.githubusercontent.com/5047891/27676181-47c65ef0-5cad-11e7-80e8-9133ddc0947f.gif)

#### 2. Observe the viewlet gets updated and git processes are executed
![one-window](https://user-images.githubusercontent.com/5047891/27676194-56fbde2c-5cad-11e7-93c9-1d4d24e6234f.gif)

---

This issue is about two things:
* the git extension needs to change something (of course it will at one point)
* but also about that all the extensions that use the `vscode.d.ts` file watching API and that operate correctly on a single folder case, no longer operate correctly on the multi folder case.

**Comment by jrieken** [comment] 2017-06-29 07:58
Tricky. The API was always about *full file paths*  and never scoped to the root path, workspace, or anything. From https://github.com/Microsoft/vscode/issues/20184 @joaomoreno could have known that, tho I guess, like most others, the *fix* was to the watch for `**/myfiles` instead of `${rootPath}/myfiles`.

**Comment by jrieken** [comment] 2017-06-29 08:34
I am not very keen on adding a second file watcher API for the multi-root-case but what we could do is to have a new option to watch only on files in the `rootPath`. That option would be on by default to get the behaviour we have today. Extensions that do support multi-root must flip that option (or maybe we flip it depending on the vscode-version they program against?). Still, a little error prone tho. At the end it's a behavioural change in our system and we somehow need to make sure extension authors understand that and adjust their extensions accordingly...

**Comment by bpasero** [comment] 2017-06-29 09:46
I suggest to filter out file events for file which are not belonging to the workspace. Today you can end up receiving them by:
* open a file which is not inside the workspace
* change the file while it is open

I am not sure about multi-root though. We could introduce a new option to opt-in to getting those events, but imho eventually the default should be to get these events.

**Comment by joaomoreno** [comment] 2018-03-19 09:32
This has nothing to do with workspaces but rather with the ability to create a watcher for arbitrary folders. The git repository root may not be a workspace folder, nor even within the workspace!

Closing as a duplicate of #3025, since that fix would fix this

**Closed by joaomoreno** 2018-03-19 09:32 UTC
Labels: bug, git
