### ISSUE TITLE
Button to add an extension to the exensions.json file

### ISSUE THREAD

**Issue by daveparslow** [Microsoft/vscode#70349] opened 2019-03-13 01:55 UTC
Issue Type: <b>Feature Request</b>

There should be a button to add an extension to the exensions.json file from the extension's marketplace page.  Would make it easier not to forget to add a great extension to that file  

Basically the reverse of "This extension is recommended by the users of the current workspace"

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment] 2019-03-13 05:39
duplicate of #68702 ?

**Closed** 2019-03-15 15:11 UTC
Labels: *duplicate, extensions
