### ISSUE TITLE
`var` is highlighted too aggressively

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#4581] opened 2016-03-22 20:14 UTC
- VSCode Version: (0.10.11) f291f4ad600767626b24a4b15816b04bee9a3049
- OS Version: Mac OS X 10.10.5 (14F1605)

![js snippet](https://cloud.githubusercontent.com/assets/829827/13966482/fa497a58-f048-11e5-96bf-b6364f28cc80.png)

The first `var` is highlighted as I expect. But those letters should not be highlighted in a name like `variableTimeMs`.

Thanks!

**Comment by aeschli** [comment] 2016-03-23 10:54
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by aeschli** 2016-03-23 10:54 UTC
