### ISSUE TITLE
Toggle line comment, comment as block in scss files

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/vscode#15013] opened 2016-11-04 18:40 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 10 AU

Steps to Reproduce:

1. Open a SCSS file
2. Toggle line comment

I expect to be comment as a line with `//`, but it get surrounded by `/* */` instead.
If I have a line commented with `//` it just surround again the line with `/* */`.
If I have the line surrounded with `/* */` it toggle.

**Comment by rebornix** [comment] 2016-11-04 18:48
This one might be related to #14661 as well.

**Comment by michaeljota** [comment] 2016-11-04 19:07
Yep. I think it is. I would edit that an say that it does not matter where you try to toggle, it will use CSS style to comment instead of the SASS ones, cause if you invoke that from the command pallete it will have the same behavior.

**Comment by mrmlnc** [comment] 2016-11-04 21:13
@michaeljota, @rebornix,

Yes, this is fully related to #14661. VS Code 1.7.0/1.7.1 has incorrect behaviour with finding scopes at the cursor position. See @aeschli comment: https://github.com/Microsoft/vscode/issues/14661#issuecomment-257577514

**Comment by mrmlnc** [comment] 2016-11-04 23:25
@alexandrudima, If I fully understand your code, this should help:

```ts
function toModeTransitions(topLevelModeId: string, modeTransitions: ModeTransition[], tokens: Token[]): ModeTransition[] {

	if (!modeTransitions || modeTransitions.length === 0) {
		return null;
	} else if (modeTransitions.length === 1 && modeTransitions[0].startIndex === 0 && modeTransitions[0].modeId === topLevelModeId) {
		return null;
	}

	// If tokens has embedded scopes, then return the transition modes
	for (let i = 0; i < tokens.length; i++) {
		if (tokens[i].type.indexOf('embedded') !== -1) {
			return modeTransitions;
		}
	}

	return null;
}
```

**Comment by alexandrudima** [comment] 2016-11-08 09:15
Duplicate of #14661

**Closed by alexandrudima** 2016-11-08 09:15 UTC
Labels: bug
