### ISSUE TITLE
First hover is no longer syntax-highlighted since 1.25

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#53723] opened 2018-07-06 15:10 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10

We noticed a regression in the Haxe extension where the first time a hover hint is shown after VSCode is loaded, it's missing syntax highlighting. For subsequent hovers after that it works fine.

![](https://i.imgur.com/SElC8gf.gif)

This didn't happen in 1.24:

![](https://i.imgur.com/coEOMpb.gif)

____

I think this might be related to using a different grammar / language ID than the text document itself in hover hints (as it seems fine in TS for instance). We have some special language IDs for hover to get it to use a specific scope of the Haxe grammar (`haxe.type` and `haxe.argument` instead of `haxe`):

![](https://i.imgur.com/a5cZ7q1.png)

This issue also affects the [vscode-reasonml](https://github.com/reasonml-editor/vscode-reasonml) extension, [which does the same thing](https://github.com/reasonml-editor/vscode-reasonml/blob/2fc9d5b334b584435b8643aa0ced671f43755d08/package.json#L160-L169):

![](https://i.imgur.com/beKNYsf.png)

**Comment by aeschli** [comment] 2018-07-10 13:41
Reproduces and debuged. The markdownRenderer (used by the hover for the code block) accesses the TokenizationRegistry at a time when the grammar is still loaded.
- the TokenizationRegistry has a synchronous get
- new ITokenizationSupport's are registered to the TokenizationRegistry after a mode are created

Looks like there has been a timing change due to the change to load the grammar files asynchronously.

**Comment by jrieken** [comment] 2018-07-10 15:35
Looks like @aeschli removed support for this and we don't support this any longer. Closing as out-of-scope.

**Comment by Gama11** [comment] 2018-07-10 16:02
To clarify, what exactly is it that's not supported anymore? Syntax highlighting in hover hints that uses language IDs different from the document language itself?

Note that this isn't limited to the Haxe and OCaml extensions, there are even instances of this in `vscode.d.ts` itself. There are a number of doc comments there with `javascript` / `js` / `json` code blocks that are now only highlighted the second time you hover over them (and the respective grammar hasn't been loaded yet at that point by e.g. opening a JS file):

![](https://i.imgur.com/KdOrXA6.gif)

(there also appears to be a separate issue with leading `*` characters in code blocks not being removed)

**Comment by jrieken** [comment] 2018-07-10 17:08
> Syntax highlighting in hover hints that uses language IDs different from the document language itself?

No, we still support that. The issue is about loading a new language via the hover for the first time. Getting tokenisation for a language used to be coupled with loading it (there is something called `getOrCreateMode`) and once that resolved we would have tokenisation support. With some recent refactorings tokenisation got decoupled from loading a language and this "trick" doesn't work anymore. So, this is just about the first time and the hover.

**Comment by Gama11** [comment] 2018-07-10 17:14
I see... Is there any workaround, perhaps something that would trigger loading the language grammar in an extension's `activate()` method? If the Haxe extension is activated, I think it's fair to say it will pretty much always need these hover language IDs sooner or later since hover is used so commonly.

**Comment by aeschli** [comment] 2018-07-11 08:15
I'll see what I can do to fix this.

**Comment by gingerbeardman** [comment] 2018-09-11 10:34
@aeschli thank you

**Closed** 2018-09-17 15:06 UTC
Labels: bug
