### ISSUE TITLE
Source control incoming/outgoing is not showing changes when using old git versions

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/vscode#200940] opened 2023-12-15 09:53 UTC
Type: <b>Bug</b>

My machine has an old git version installed, 2.25. This version does not yet understand the --diff-merges=first-parent argument that the incoming/outgoing view uses.
So when I try to view the changes, I click on the ">" symbol, which changes for a second or so, and then folds back to ">".
In the git output, I see the error message 
```
    [info] fatal: unrecognized argument: --diff-merges=first-parent
   [info] > git diff --shortstat 6423a9fd343e6847db49539058745aad90344658...2c4b17dfb8311d95b3ecd5936ceb535561e0f097 [6ms]
    [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z --shortstat --diff-merges=first-parent --author-date-order 6423a9fd343e6847db49539058745aad90344658..
```
Instead of silently failing, it would be better to display an error message.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-88-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (14.99GB free)|
|Process Argv|--crash-reporter-id 5721c94c-fdd7-4143-aab7-ce5aadbe6563|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: gcr|
|OS|Linux x64 5.15.0-88-generic|
|CPUs|AMD EPYC 7742 64-Core Processor (128 x 1500)|
|Memory (System)|995.53GB (980.31GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
remote-explorer|ms-|0.4.1
rewrap|stk|1.16.3
errorlens|use|3.15.0
copilot|Git|1.143.601
copilot-chat|Git|0.12.2023120701
vscode-pull-request-github|Git|0.78.1
rainbow-csv|mec|3.9.0
vscode-docker|ms-|1.28.0
black-formatter|ms-|2023.6.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
mypy-type-checker|ms-|2023.6.0
pylint|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
makefile-tools|ms-|0.8.22
autodocstring|njp|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by lszomoru** [comment] 2023-12-15 11:03
Closing as duplicate of https://github.com/microsoft/vscode/issues/200488

**Closed by lszomoru** 2023-12-15 11:03 UTC
Labels: new release
