### ISSUE TITLE
Extensions not loaded the first time a remote workspace is trusted (when Azure ML ext is installed)

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode#128573] opened 2021-07-13 20:50 UTC
Issue Type: <b>Bug</b>

1. Install Azure Machine Learning and Azure Machine Learning - Remote extensions
2. Connect to remote Compute Instance using Azure Machine Learning - Remote
3. Open a python file and try to run it

Expected: Python extension gets loaded and you can run the file using pyhton extension

Failure: Python extension is not loaded and its commands are not found

**Findings**
1. Azure Machine Learning - Remote require reload
![image](https://user-images.githubusercontent.com/56176070/125522747-1c53dc6f-1642-4dc4-a4f9-a9d9859fe721.png)
2. Log: [2021-07-13 13:21:27.207] [renderer9] [error] ENOENT: no such file or directory, access 'c:/Users/sevillal/.vscode-insiders/extensions/ms-toolsai.vscode-ai-remote-0.3.0': Error: ENOENT: no such file or directory, access 'c:/Users/sevillal/.vscode-insiders/extensions/ms-toolsai.vscode-ai-remote-0.3.0'
3. Reloading the window fixes the issue, python extension is loaded and its commands are available
4. If "Azure Machine Learning - Remote" extension is installed in the remote target, and you connect with SSH - Remote, the same issue happens the first time a workspace is trusted

VS Code version: Code - Insiders 1.59.0-insider (807dfb817fef0d0c5729c1924bd4889b04fa405b, 2021-07-13T09:24:20.727Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-1098-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (0.73GB free)|
|Process Argv|--crash-reporter-id 2b925b84-77da-4382-9d6c-89a345fc2762 --crash-reporter-id 2b925b84-77da-4382-9d6c-89a345fc2762 --crash-reporter-id 2b925b84-77da-4382-9d6c-89a345fc2762 --crash-reporter-id 2b925b84-77da-4382-9d6c-89a345fc2762 --crash-reporter-id 2b925b84-77da-4382-9d6c-89a345fc2762|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Azure ML: sevillal-dev-ci|
|OS|Linux x64 4.15.0-1098-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2397)|
|Memory (System)|6.81GB (2.40GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ai-remote|ms-|0.3.0
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1025925145
vscode-ai-remote|ms-|0.3.0
azure-account|ms-|0.9.8

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805cf:30301675
bridge0708:30335490

```

</details>

**Comment by roblourens** [comment] 2021-07-13 22:52
@sbatten @lszomoru why doesn't the Azure ML extension get activated right away here, I'm not sure what's different about it. Is it because the capabilities section isn't filled out? https://code.visualstudio.com/api/extension-guides/workspace-trust#onboarding You could see if that makes a difference @sevillal

**Comment by lszomoru** [comment] 2021-07-23 16:18
I was able to reproduce the issue and I will reach out to @sandy081 in order to track down the issue.

**Comment by lszomoru** [comment] 2021-07-26 13:44
@sandy081 and myself have looked at this and there indeed seems to be a problem when the `Azure Machine Learning - Remote` extension is being enabled as part of trusting a workspace. While we are working to track that down, we would like to suggest that you try the following:
1. is there any reason why this extension defines both `workspace` and `ui` as extensionKind in the package.json? If there is no specific reason, we would like to suggest to only specify `ui` as the extensionKind in the package.json.
2. since this extension implements a resolver, we would suggest that you enable support for untrusted workspaces as documented here: https://code.visualstudio.com/api/extension-guides/workspace-trust#onboarding

**Comment by sevillal** [comment] 2021-08-04 21:54
@lszomoru, 

1. @shsuman can speak more about the need of [workspace, ui]
2. Just tried the untrusted workspace config and that seems to fix the issue

**Comment by shsuman** [comment] 2021-08-05 06:49
Hey @lszomoru,
Azure ML extension has a hard dependency on the Azure ML - Remote extension because the remote connection feature although executed in the remote extension, is exposed in the main extension. Further, we also use the API exposed by the Remote extension in the main extension. Now since we have taken this hard dependency, we need the Remote extension and its API in the remote context as well.

**Comment by sbatten** [comment] 2021-08-05 16:36
Am I correct in understanding that the issue is resolved by adding `untrusted workspace config`

**Comment by sevillal** [comment] 2021-08-06 18:10
@sbatten that's correct.

**Comment by sevillal** [comment] 2021-08-09 16:57
@lszomoru couple of questions?
1. Is "enabling support for untrusted workspaces" the best practice for remote extensions? My hypothesis is that's because the remote extension knows the folder to land that should be "trusted".
2. Is there any security implication we need to be aware of by "enabling support for untrusted workspaces"?

**Comment by alexdima** [comment] 2021-08-20 13:09
@sevillal Here is what you need to do in the `package.json` of `ms-toolsai.vscode-ai-remote`:
* `"extensionKind": ["ui"]` (because a resolver cannot run on the workspace)
* `"capabilities": { "untrustedWorkspaces": { "supported": true } }` (because resolvers need to execute before workspace trust is established)
* `"api": "none"` (because the main extension that needs to run on the workspace side takes a dependency on this extension which runs on the ui side). this blocks the extension from exposing any API.

**Comment by sevillal** [comment] 2021-08-20 21:20
@alexdima I tried the above changes but it fails when the main extension (ms-toolsai.vscode-ai) tries to use the api of the remote extension (ms-toolsai.vscode-ai-remote). I think the problem might be the "api": "none".

So our workflow would be:
1. User in local context opens vscode and activates ms-toolsai.vscode-ai and ms-toolsai.vscode-ai-remote
2. User starts remote connection
3. ms-toolsai.vscode-ai extension uses ms-toolsai.vscode-ai-remote api to set some secrets used later by the resolver
4. ms-toolsai.vscode-ai opens a remote uri (vscode-remote://...) that the ms-toolsai.vscode-ai-remote can resolve

**Comment by alexdima** [comment] 2021-08-23 07:29
@sevillal I am really sorry, but I am afraid you have ended up taking a dependency on a vscode bug. As it is right now, the `ms-toolsai.vscode-ai-remote` executes twice, once on the ui side and again on the workspace side. To clarify, running the same extension on two extension hosts at the same time has unforeseen consequences, like for example, commands are registered twice, views are registered twice, etc, and is completely untested, and unforeseen. The fact that anything works at all is more of a big coincidence, and IMHO we really need to fix this.

Here is what you can do to avoid having an api dependency:
- continue having `ms-toolsai.vscode-ai-remote` as an extensionDependency for `ms-toolsai.vscode-ai`. This will ensure that the extension `ms-toolsai.vscode-ai-remote` is installed, enabled, and always activated before the extension `ms-toolsai.vscode-ai` (even if the two extensions execute on distinct extension hosts).
- in `ms-toolsai.vscode-ai-remote`, use `"api": "none"`. This forbids the extension from exporting API.
- in `ms-toolsai.vscode-ai-remote`, register a command e.g. `command1`
- from `ms-toolsai.vscode-ai`, invoke the command `command1`.

An alternative would be to change the extension kind of `ms-toolsai.vscode-ai` and make it a `ui` extension, but I don't know if your feature set would be compatible with running the extension on the ui side.

**Comment by alexdima** [comment] 2021-09-03 12:15
@sevillal Did you have a chance to try this?

**Comment by sevillal** [comment] 2021-09-16 01:40
@alexdima I was off, sorry for the late response.

I have tried your suggestion of using commands (instead of calling the extension API directly) and that seems to work.

I am curious about the following:
1. Correct me if I am wrong but if we update to [ui] the extension does not need to be installed in remote and having it locally will be enough. Since "ms-toolsai.vscode-ai-remote" was [workspace, ui] we have users that have the extension installed in the remote target, could this represent an issue?

**Comment by sevillal** [comment] 2021-09-17 19:48
@alexdima @roblourens I was testing how other extensions behave with Remote SSH and found the following:

1. Using Remote SSH connect to a target and open a folder
2. Trusted workspace prompt appears, then select "Yes, I trust the authors"
3. Open a python file and try to run it, nothing happens (no error is shown)
4. If you go to extensions tab, the Python extension needs a reload

The issue we have faced with users is that they don't have any sort of indication that the reload is required until they go to the extensions tab. 

Shouldn't VS Code show a notification that reload is required or reload after the workspace is trusted?

**Comment by alexdima** [comment] 2021-09-20 15:28
> I have tried your suggestion of using commands (instead of calling the extension API directly) and that seems to work.

This is great! Please let me know when these changes are published, such that I can fix things on our side (better enforce that an extension can be at most activated once).

> Correct me if I am wrong but if we update to [ui] the extension does not need to be installed in remote and having it locally will be enough. Since "ms-toolsai.vscode-ai-remote" was [workspace, ui] we have users that have the extension installed in the remote target already, once we release the new version (with [ui] only) and the user tries to connect to thre remote, could this represent an issue?

In this situation, the first time a user connects to such a remote, the user will have locally the `ms-toolsai.vscode-ai-remote` extension at a newer version with extension kind `[ui]`. When scanning the remote extensions, the old version of `ms-toolsai.vscode-ai-remote` will be probably hit, with the extension kind `[workspace, ui]`. From [reading the code](https://github.com/microsoft/vscode/blob/1632a12f6fd70c710c70e672bac6d22b655fc2a1/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L999-L1000), I think the extension kind defined for the remote extension will "win" and overwrite the extension kind defined by the local extension. So for the first connection, the old version of the extension will activate remotely (as it does today). So the extension will be activated twice (as it does today). Once the remote extension is updated (should happen quickly after the first connection), subsequent connections will work as we want them. So, overall, yes, this is problematic, but I don't think it is a blocker.

@lszomoru ⬆️ Please see above comment

**Comment by alexdima** [comment] 2021-09-23 07:18
@sevillal I have pushed a change in https://github.com/microsoft/vscode/commit/275039827db297c3018dfd61e351b5b53a11eab7 where priority would be given to the `extensionKind` defined in the local extension, which has a higher chance of being up-to-date.

**Comment by lszomoru** [comment] 2021-09-28 19:39
@sevillal, sorry for the delay in getting back to you on this. Trusting a workspace should enable all extensions that were disabled due to their workspace trust requirement without the need to reload the window. I will take a look at this first thing tomorrow morning and update the issue with my findings.

**Comment by lszomoru** [comment] 2021-09-29 09:13
@sevillal, I have tried to reproduce the behaviour that you have described with the latest `insiders` release without any luck. Could you please ping me when you get online in the morning so that we get a screen sharing session going so that I can take a closer look at your setup? Thank you!

**Comment by sevillal** [comment] 2021-09-29 16:24
@lszomoru I was testing in latest stable, sorry about that. I tested latest insider and seems to be working fine.  Is there any tentative date for the next vscode release with this fix? Thanks!

**Comment by lszomoru** [comment] 2021-09-30 11:10
We are wrapping up [the September endgame](https://github.com/microsoft/vscode/issues/133861) this week, so we expect the next Stable release to happen in the second half of next week.

**Closed** 2021-10-04 22:19 UTC
Labels: workspace-trust
