### ISSUE TITLE
Search box in the sidebar file explorer.

### ISSUE THREAD

**Issue by gostavee** [microsoft/vscode#98662] opened 2020-05-27 16:23 UTC
Hello there, 
I was wondering if this can be done in the future, adding a search box in the sidebar to quickly filter files in the file explorer (something similar to ctrl +p but always open on the sidebar).
![2020-05-27_18-22-14](https://user-images.githubusercontent.com/12511748/83046310-227d9880-a047-11ea-85f7-4f8c1df1dd25.png)

**Comment by IllusionMH** [comment] 2020-05-27 16:46
/duplicate of #70646

You can already use Filter on type feature (without input, just typing while Explorer focused, using arrows to navigate matches or just filter tree from flyout), however it won't filter collapsed folders #66971

**Closed** 2020-05-27 16:47 UTC
Labels: *duplicate

**Comment by gostavee** [comment] 2020-05-28 15:07
> You can already use Filter on type feature (without input, just typing while Explorer focused, using arrows to navigate matches or just filter tree from flyout), however it won't filter collapsed folders

First, sorry about posting a duplicate feature request, I tried to search for something similar but I didn't find it, maybe because there is too many requests there that's why I missed it. 
Now about the way you suggest I'm a ware of it and I gotta say this is a very very bad way to search for files, it could cause a lot of issues, I'm not even sure how did such a thing was added, I'd say the one who invented this feature should be hanged on a tree (jk) :D
