### ISSUE TITLE
Weird coloring

### ISSUE THREAD

**Issue by GrbavaCigla** [microsoft/vscode#98325] opened 2020-05-21 13:40 UTC
- VSCode Version: 1.45.1
- OS Version: ArchLinux

Steps to Reproduce:
1. Install dracula theme (this happens on almost all theme other than default)

Screenshot:
![Screenshot from 2020-05-21 15-39-17](https://user-images.githubusercontent.com/23121814/82564598-52292e00-9b79-11ea-9bce-98eb827d1583.png)

Does this issue occur when all extensions are disabled?: No

**Comment by usernamehw** [comment] 2020-05-21 15:44
Possible duplicate of #93977

**Closed** 2020-05-21 20:07 UTC
