### ISSUE TITLE
Annoying fullscreen mode with macos-status-bar hiding the top content of the editor

### ISSUE THREAD

**Issue by aakrem** [Microsoft/vscode#41155] opened 2018-01-04 15:43 UTC
Steps to Reproduce:

1. Bring a MacOS machine
2. Put VSCode in full screen
3. Put the cursor in the top part of the window and the status bar will hide the top level of the editor that contains also the debug ui tool.

This is super annoying each time you want to select another tab and especially during debugging as it will hide the debug tool. Each time the status bar appears we need to wait until it disappears again (that could appear again if the cursor reach the top of the screen 😭).

VSCode in fullscreen and debug tool visible:
![screen shot 2018-01-04 at 16 21 50](https://user-images.githubusercontent.com/6608260/34570874-5c12e662-f16d-11e7-8c1a-bedad866204c.png)

VSCode in fullscreen and status bar hiding the debug tool:
![screen shot 2018-01-04 at 16 22 03](https://user-images.githubusercontent.com/6608260/34571140-06f3fb84-f16e-11e7-950b-be291e2a4874.png)

We don't find this issue in most build-in macos apps and also google chrome; the tabs bar and the address bar there is lowered altogether with the os status bar.

<img width="555" alt="screen shot 2018-01-04 at 16 39 32" src="https://user-images.githubusercontent.com/6608260/34571083-ebb1fc68-f16d-11e7-8aea-962e6c42e174.png">

- VSCode Version:1.19.1
- OS Version: 10.13.2

**Comment by bpasero** [comment] 2018-01-08 09:36
Let's treat this as duplicate of https://github.com/Microsoft/vscode/issues/5344 where a simple fullscreen support is proposed that would not have this flaw.

**Closed by bpasero** 2018-01-08 09:36 UTC
