### ISSUE TITLE
debug window is unexpectedly considered a "text editor"

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45188] opened 2018-03-07 09:31 UTC
There are some events and properties related to text editors:

- `window.activeTextEditor`
- `window.onDidChangeActiveTextEditor`

These sound perfect for something I'm doing - rendering an explorer tree with an outline of the current document. The docs describe the active editor as "The active editor is the one that currently has focus or, when none has focus, the one that has changed input most recently".

However, they fire for things I wouldn't consider "text editors". When I click the debug window the event fires and the `activeTextEditor` is updated to something with a document that has the URI `debug:input`.

This makes it difficult to track the last actual document the user interacted with (which is what the description of `window.activeTextEditor` suggests it does). While we could skip over changes from non-documents it then would be difficult to track when the last document we're tracking was closed (since it could be closed without firing another `window.activeTextEditor`.

I don't know if this is a bug, but if it's not, I think there shoud be a way to track what the user would consider a text document.

**Comment by DanTup** [comment] 2018-03-07 09:55
Looks like this has been discussed before:

https://github.com/Microsoft/vscode/issues/16478

The suggestion is to use `vscode.window.activeTextEditor.viewColumn` to decide whether the event is for a real document or not. I think this is a bad fix, as `window.activeTextEditor` won't give you what you want.

**Comment by DanTup** [comment] 2018-03-07 10:00
The workaround seems flawed. If you click in the debug window and then click `File -> Close Editor` then you don't get notification of that editor going away.

As such, #16478 is still somewhat reproducible in TypeScript even after @mjbvz's fix in 
379da6bc8d8511eae3f9a75ebd072d579ece9ee4.

1. Open a single typescript file
2. Observe version number on status bar
3. Click into debug window
4. Observe version number still on status bar
5. `File -> Close Editor`
6. TypeScript version is still on status bar, but there is no active TypeScript file

If this isn't fixed in the API, extension authors are all going have to put nasty hacks in to handle these things properly :(

**Comment by mjbvz** [comment] 2018-03-07 19:10
@jrieken This may be a good case for the proposed generic editor APIs (such as `onDidChangeActiveEditor`) to handle. Debug console could have its own distinct type

**Comment by jrieken** [comment] 2018-03-08 08:34
closing as dupe of #16478 and flagging 'as-design' because we currently cannot change these things, esp the debug console want to be an editor for support vim and language smart, e.g. IntelliSense in the debug console uses the well-known concepts

**Comment by DanTup** [comment] 2018-03-08 08:56
@jrieken Understood, but there's still a bug that the ts extension can't easily fix. Should I raise a case for the ts extension to add a workaround or is there a future feature that will address this? Although the ts bug is minor (it's just status text) I'm using the same functionality for a contributed tree and having stale content there is far worse, it feels really broken.

**Comment by DanTup** [comment] 2018-03-08 09:02
@mjbvz Feel free to rename this if your intention is to fix in the ts extension, but lmk if you find a reliable fix (ideally that works globally, not just for the one instance I managed to find with a quick test) since I desperately need it too! ;(

**Comment by mjbvz** [comment] 2018-03-08 10:27
@jrieken I think the point is that we need a new API or an API change. Extensions can't solve this problem without maintaining their own model of the editor UI

@DanTup You'll probably need to look into a workaround on your side as I don't see myself getting around to the TS-specific issue in the near term. The TS problem is very low impact and it self corrects as soon as you go back to an editor

**Comment by DanTup** [comment] 2018-03-08 10:38
@mjbvz Understood, thanks! Our feature is blocked by quite a few issues in Code (listed [here](https://github.com/Dart-Code/Dart-Code/issues/605)) so it might be a while before we can ship this anyway, so I'll leave finding a workaround till later in the hope a better solution comes along.

**Comment by DanTup** [comment] 2018-04-07 10:52
I saw this in the release notes; is it a fix for this issue?

> ### Simple editors are not passed to extensions
> Inputs that use the editor like the debug REPL input are no longer passed to extensions as editors. This means that both the onDidChangeActiveTextEditor will not trigger when user focuses the debug REPL, and that the onDidChangeTextDocument will also not fire. The reason behind this change is that the REPL input uses the editor as an implementation detail and extension should not be notified of this since it is not a "real editor".

**Comment by jrieken** [comment] 2018-04-09 06:46
Yes

**Closed by jrieken** 2018-04-09 06:46 UTC
