### ISSUE TITLE
Git commit does not work when message begins with hashtag (#) in 1.40

### ISSUE THREAD

**Issue by joelhal** [microsoft/vscode#84263] opened 2019-11-08 13:25 UTC
- VSCode Version: 1.40
- OS Version: macOS Catalina 10.15.1

Steps to Reproduce:

1. Type a commit message beginning with '#'
2. Try to click commit (or keyboard shortcut)
3. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

This worked fine before 1.40. It's frustrating especially when linking work items from Azure DevOps through the associate work item feature.

**Comment by stephanebouget** [comment] 2019-11-08 13:29
same issue on Windows

**Comment by gjsjohnmurray** [comment] 2019-11-08 13:48
/duplicate of #84201 and it looks like there'll be a fix in the upcoming October Recovery release, 1.40.1

**Closed** 2019-11-08 13:48 UTC
Labels: *duplicate
