### ISSUE TITLE
Indentation highlighting when selected line is off-screen

### ISSUE THREAD

**Issue by zforbus** [Microsoft/vscode#49636] opened 2018-05-10 18:14 UTC
Issue Type: <b>Bug</b>

The selected indent highlight disappears if the selected line is scrolled off the top of the screen. It remains if the selected line is scrolled to below the screen.

To reproduce:
- Click into a code block to highlight its indentation guide
- Scroll down until the selected line is no longer visible, but the indentation guide is
- The guide unhighlights

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kpdonn** [comment] 2018-05-10 19:47
I also ran into this. It looks like there is already an existing issue with someone assigned to it at https://github.com/Microsoft/vscode/issues/49572.

**Comment by alexandrudima** [comment] 2018-05-11 08:08
Duplicate of #49173

**Closed by alexandrudima** 2018-05-11 08:08 UTC
Labels: editor, editor-core
