### ISSUE TITLE
No symbols found in document

### ISSUE THREAD

**Issue by mda-jobs** [microsoft/vscode#187004] opened 2023-07-04 18:30 UTC
Type: <b>Bug</b>

I have a reoccuring issue with getting symbol information in the OUTLINE panel of EXPLORER. I recently did a clean uninstall and reinstall to fix this problem, and now its back again. Please advise.

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|64.00GB (26.66GB free)|
|Process Argv|--crash-reporter-id c70b06a5-7346-4c52-a932-38395ba97cf9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
bash-ide-vscode|mad|1.37.0
mongodb-vscode|mon|1.0.2
vscode-edge-devtools|ms-|2.1.2
live-server|ms-|0.4.8
bash-debug|rog|0.3.9
svg-preview|Sim|2.8.3
icons|tal|3.6.3
javascriptsnippets|tal|2.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxptcf:30772540
pythonnoceb:30776495
e537b577:30772215

```

</details>

**Comment by jrieken** [comment] 2023-07-05 06:57
/info-needed

This issue lacks

* copy-paste friendly source code sample
* mentioning of the programming language that's being used
* mentioning of the language extension that you have installed for that

**Comment by mda-jobs** [comment] 2023-07-08 08:11
/*
 * Primary file for API
 *
 */

// Dependencies
var http = require('http');
var https = require('https');
var url = require('url');
var StringDecoder = require('string_decoder').StringDecoder;
var config = require('./config');
var fs = require('fs');


 // Instantiate the HTTP server
var httpServer = http.createServer(function(req,res){
  unifiedServer(req,res);
});

// Start the HTTP server
httpServer.listen(config.httpPort,function(){
  console.log('The HTTP server is running on port '+config.httpPort);
});

 // Instantiate the HTTPS server
var httpsServer = https.createServer(function(req,res){
  unifiedServer(req,res);
});

// Start the HTTPS server
httpsServer.listen(config.httpsPort,function(){
 console.log('The HTTPS server is running on port '+config.httpsPort);
});

// All the server logic for both the http and https server
var unifiedServer = function(req,res){

  // Parse the url
  var parsedUrl = url.parse(req.url, true);

  // Get the path
  var path = parsedUrl.pathname;
  var trimmedPath = path.replace(/^\/+|\/+$/g, '');

  // Get the query string as an object
  var queryStringObject = parsedUrl.query;

  // Get the HTTP method
  var method = req.method.toLowerCase();

  //Get the headers as an object
  var headers = req.headers;

  // Get the payload,if any
  var decoder = new StringDecoder('utf-8');
  var buffer = '';
  req.on('data', function(data) {
      buffer += decoder.write(data);
  });
  req.on('end', function() {
      buffer += decoder.end();

      // Check the router for a matching path for a handler. If one is not found, use the notFound handler instead.
      var chosenHandler = typeof(router[trimmedPath]) !== 'undefined' ? router[trimmedPath] : handlers.notFound;

      // Construct the data object to send to the handler
      var data = {
        'trimmedPath' : trimmedPath,
        'queryStringObject' : queryStringObject,
        'method' : method,
        'headers' : headers,
        'payload' : buffer
      };

      // Route the request to the handler specified in the router
      chosenHandler(data,function(statusCode,payload){

        // Use the status code returned from the handler, or set the default status code to 200
        statusCode = typeof(statusCode) == 'number' ? statusCode : 200;

        // Use the payload returned from the handler, or set the default payload to an empty object
        payload = typeof(payload) == 'object'? payload : {};

        // Convert the payload to a string
        var payloadString = JSON.stringify(payload);

        // Return the response
        res.setHeader('Content-Type', 'application/json');
        res.writeHead(statusCode);
        res.end(payloadString);
        console.log("Returning this response: ",statusCode,payloadString);

      });

  });
};

// Define all the handlers
var handlers = {};

// Sample handler
handlers.sample = function(data,callback){
    callback(406,{'name':'sample handler'});
};

// Not found handler
handlers.notFound = function(data,callback){
  callback(404);
};

// Define the request router
var router = {
  'sample' : handlers.sample
};

**Comment by mda-jobs** [comment] 2023-07-08 08:22
Language is JavaScript, exclusively Node.js. The soure file is not the problem. I was viewing it earlier in OUTLINE panel.

My list of installed extensions is as follows:

Atom One Dark Theme (akamud.vscode-theme-onedark)
Bash Debug (rogalmic.bash-debug)
Bash IDE (hartmann.bash-ide-vscode)
Bracket Pair Color DLW (bracketpaircolordlw.bracket-pair-color-dlw)
Composer (devsense.composer-php-vscode)
Icons (tal7aouy.icons)
JavaScript (ES6) code snippets (tal7aouy.javascr)
Live Preview (ms-vscode.live-server)
Microsoft Edge Tools for VS Code (ms-edgedevtools.vscode-edge-devtools)
MongoDB for VS Code (mongodb.mongodb-vscode)
PHP (devsense.phptools-vscode)
PHP Profiler (devsense.profiler-php-vscode)
Svg Preview (simonsiefke.svg-preview)
Theme (tal7aouy.theme)

-M

**Comment by mjbvz** [comment] 2023-07-10 18:55
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mda-jobs** [comment] 2023-07-10 21:51
Thank you Matt. I will attempt that and get back to you within 24 hours.

**Comment by mjbvz** [comment] 2023-07-18 23:12
Closing since we need more information to investigate. Issues like this are usually caused by one of the following issues:

- The file is in the wrong language mode (it should be `javascript` or `typescript`)
- Another extension is causing issues
- The built-in JavaScript and TypeScript extension has been disabled

**Closed by mjbvz** 2023-07-18 23:12 UTC
Labels: info-needed
