### ISSUE TITLE
Found Modules or Symbols no longer have IntelliSense priority [BUG]

### ISSUE THREAD

**Issue by tarekis** [Microsoft/vscode#26924] opened 2017-05-19 09:03 UTC
# Description
When importing a symbol from another module, IntelliSense detects importable modules.
Before 1.12.1 found modules or symbols (of modules) were prioritized in the suggestion display, as of 1.12.1, they no longer are.
Code snippets now seem to have the same priority, and all suggestions are sorted alphabetically.

If **nothing was typed yet**, symbol suggestions are prioritized as expected, modules are still ordered alphabetically.

# Spec information
- VSCode Version:
1.12.1 & 1.12.2
- OS Version:
Ubuntu 16.04 x64

# Steps to Reproduce:

1. Create any typescript module with any exported symbol
2. Import the symbol from another typescript file

# Screenshot Documentation:
For modules:
![selection_078](https://cloud.githubusercontent.com/assets/16593597/26240311/d92ec5aa-3c80-11e7-90c5-dc283decd89f.png)
For symbols:
![selection_076](https://cloud.githubusercontent.com/assets/16593597/26240313/d931fe28-3c80-11e7-9ffb-45992bea2bb5.png)
Does not appear if nothing was typed yet:
![selection_077](https://cloud.githubusercontent.com/assets/16593597/26240312/d930ca08-3c80-11e7-93df-30666f655456.png)
Module import not affected:
![selection_079](https://cloud.githubusercontent.com/assets/16593597/26240922/19cdf110-3c83-11e7-8e60-b56f0980d9c8.png)

**Comment by mjbvz** [comment] 2017-05-19 21:42
What do you have `editor.snippetSuggestions` set to?

**Comment by tarekis** [comment] 2017-05-22 07:48
Hi, sorry for the delay on my reply.
I don't have that option set, and never had, but it seems to be `inline` by default.
Did the default change in 1.12? Because the behaviour changed without me having the option set.

**Comment by mjbvz** [comment] 2017-05-22 15:26
yes, I believe we changed the default from `bottom` to `inline` at some point

Really, snippets should not be shown at all in this case thought. We are tracking smarter snippets contexts with #1304

Closing as a duplicate of #1304

**Closed by mjbvz** 2017-05-22 15:26 UTC
Labels: as-designed, duplicate, intellisense, javascript

**Comment by tarekis** [comment] 2017-05-23 07:32
Thank you for resolving, it indeed changed from `bottom` to `inline`, overwriting it back to `bottom` brings back pre-1.12 behavior.
