### ISSUE TITLE
Command Panel translated command to other language

### ISSUE THREAD

**Issue by holmescn** [Microsoft/vscode#5373] opened 2016-04-16 01:49 UTC
- VSCode Version: 1.0
- OS Version: Mac OS X 10.11.4

Steps to Reproduce:

1. Open the Command Panel which is translated to Chinese
2. Cannot type English command, only Chinese are accepted

Command should be in English, or add an option to switch that.

**Comment by Ikuyadeu** [comment] 2016-04-16 05:54
Related #4679

**Comment by egamma** [comment] 2016-04-17 12:08
Closing as a duplicate of #4679 that is on the April plan.

**Closed by egamma** 2016-04-17 12:08 UTC
