### ISSUE TITLE
Do not seen js files placed in folder with name starts with 'js'

### ISSUE THREAD

**Issue by sunify** [Microsoft/vscode#17892] opened 2016-12-29 06:44 UTC
- VSCode Version: 1.8.1
- OS Version: macOS 10.12

Steps to Reproduce:

1. Create folder with name starts with 'js', for example `js` or `jsfolder`
2. Create file with extension '.js' in that folder
3. Try to view file in sidebar treeview

http://take.ms/0bmFX

Same folder with different name: http://take.ms/G2KFq

**Comment by bpasero** [comment] 2017-01-02 10:11
@sunify I cannot reproduce, can you share your user and workspace settings? do you have `files.exclude` configured?

**Comment by bpasero** [comment] 2017-01-23 13:16
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2017-01-23 13:16 UTC
Labels: explorer-files, needs more info
