### ISSUE TITLE
webviews should preserve their context when they are moved between view columns

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141001] opened 2022-01-19 17:30 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=150844&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=88928627-a399-54e7-2f20-a03c2cf00dcd&l=460

```
1) vscode API - webview
       webviews should preserve their context when they are moved between view columns:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/extensions/vscode-api-tests/out/singlefolder-tests/webview.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

```

**Comment by Tyriar** [comment] 2022-01-19 18:06
Still https://github.com/microsoft/vscode/blob/71b164aac018a033b9cc35a355cae8392a5cabac/extensions/vscode-api-tests/src/singlefolder-tests/webview.test.ts#L218 remaining which chances are is flaky as well.

**Comment by mjbvz** [comment] 2022-08-04 21:29
Duplicate of #153066

**Closed by mjbvz** 2022-08-04 21:29 UTC
Labels: integration-test-failure, web
