### ISSUE TITLE
keep getting "You have been signed out because reading stored authentication information failed."

### ISSUE THREAD

**Issue by GreyElec** [microsoft/vscode#145189] opened 2022-03-16 07:27 UTC
Does this issue occur when all extensions are disabled?: Yes/No Yes

- VS Code Version: 1.65.2
- OS Version: Windows_NT x64 10.0.19044

I get 3 devices sharing the same configuration, one day, I changed my Microsoft account password on one of my devices, after then I keep getting this message every time opening the vscode on the other two devices. 

![image](https://user-images.githubusercontent.com/33427038/158538028-a88e67b5-a284-4c70-86b2-8037f2ad9672.png)

Steps to Reproduce:

1. Change the MS account password
2. Open vscode.

**Comment by GreyElec** [comment] 2022-03-16 07:42
I tried to reinstall the vscode but it didn't help, maybe there are some cache exists but don't know how to clean up. 
thought re-install completely might help on this.

**Comment by GreyElec** [comment] 2022-03-16 08:25
haha, Guess what.. I tried to update my password on the device with this popup, now all my 3 devices will have this popup..

**Comment by TylerLeonhardt** [comment] 2022-03-16 14:53
Can you follow these steps so that we can get more information on what's going on?

* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `Microsoft Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel

**Comment by GreyElec** [comment] 2022-03-17 01:31
> Microsoft Authentication
[Info  - 01:28:50.209] Reading sessions from secret storage...
[Info  - 01:28:50.354] Got 2 stored sessions
[Trace  - 01:28:50.354] Read the following stored session with scopes: email offline_access openid profile
[Info  - 01:28:50.354] Refreshing token for scopes: email offline_access openid profile
[Trace  - 01:28:50.355] Read the following stored session with scopes: email offline_access openid profile
[Info  - 01:28:50.355] Refreshing token for scopes: email offline_access openid profile
[Error  - 01:28:51.316] Refreshing token failed (for scopes: email offline_access openid profile): {"error":"invalid_grant","error_description":"AADSTS50132: The session is not valid due the following reasons: password expiration or recent password change, SSO Artifact is invalid or expired, session is not fresh enough for application, or a silent sign-in request was sent but the user's session with Azure AD is invalid or has expired.\r\nTrace ID: a6eae0ef-54a1-4b8f-b6dd-530327321e00\r\nCorrelation ID: 92363cb6-5fe3-431a-a360-d6c52528db92\r\nTimestamp: 2022-03-17 01:28:51Z","error_codes":[50132],"timestamp":"2022-03-17 01:28:51Z","trace_id":"a6eae0ef-54a1-4b8f-b6dd-530327321e00","correlation_id":"92363cb6-5fe3-431a-a360-d6c52528db92","error_uri":"https://login.microsoftonline.com/error?code=50132"}
[Error  - 01:28:51.316] Error: Refreshing token failed
[Info  - 01:28:51.316] Logging out of session 'f8cdef31-a31e-4b4a-93e4-5f571e91255a/1:live.com:00037FFE0647EDAC/4d5aa5cf-560c-475a-be2c-dfca3c7d6e82'
[Info  - 01:28:51.316] Session not found 'f8cdef31-a31e-4b4a-93e4-5f571e91255a/1:live.com:00037FFE0647EDAC/4d5aa5cf-560c-475a-be2c-dfca3c7d6e82'
[Info  - 01:28:51.542] Setting token for scopes: email offline_access openid profile
[Info  - 01:28:51.542] Token refresh success for scopes: email offline_access openid profile
[Info  - 01:28:51.544] Getting sessions for the following scopes: email offline_access openid profile
[Info  - 01:28:51.544] Got 1 sessions for scopes: email offline_access openid profile
[Info  - 01:28:51.544] Token available from cache (for scopes email offline_access openid profile), expires in 5361998 milliseconds

> Log (Settings Sync)
[2022-03-17 09:28:48.881] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-03-17 09:28:48.882] [settingssync] [info] Auto Sync is enabled.
[2022-03-17 09:28:48.882] [settingssync] [info] Auto Sync: Suspended until auth token is available.
[2022-03-17 09:28:51.555] [settingssync] [info] Auto Sync: Started
[2022-03-17 09:28:51.555] [settingssync] [info] Auto Sync: Triggered by Interval
[2022-03-17 09:28:51.812] [settingssync] [info] Deleting from backup /C:/Users/perseusw/AppData/Roaming/Code/User/sync/settings/20220214T205428.json
[2022-03-17 09:28:52.639] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-03-17 09:28:52.653] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-03-17 09:28:52.658] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-03-17 09:28:52.661] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-03-17 09:28:55.534] [settingssync] [info] GlobalState: Updated remote ui state
[2022-03-17 09:28:55.540] [settingssync] [info] GlobalState: Updated last synchronized ui state
[2022-03-17 09:28:55.618] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-03-17 09:28:55.621] [settingssync] [info] Sync done. Took 3026ms
[2022-03-17 09:30:29.811] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-03-17 09:30:29.968] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-03-17 09:30:29.973] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-03-17 09:30:29.978] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-03-17 09:30:29.983] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-03-17 09:30:29.989] [settingssync] [info] GlobalState: No changes found during synchronizing ui state.
[2022-03-17 09:30:30.075] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-03-17 09:30:30.076] [settingssync] [info] Sync done. Took 147ms

> Log (Window)
[2022-03-17 09:28:48.828] [renderer1] [error] [Extension Host] (node:26284) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)

**Comment by TylerLeonhardt** [comment] 2022-03-19 20:34
@GreyElec do you see the account you changed here in the list of accounts?
<img width="493" alt="image" src="https://user-images.githubusercontent.com/2644648/159137576-62e98f2b-b247-4357-8b36-7fb8e3cc5113.png">

If so, if you sign out and sign back in does that help?:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/2644648/159137583-ab6f208b-28e3-4c70-a2e7-572b15f8ff28.png">

**Comment by TylerLeonhardt** [comment] 2022-03-19 20:40
It's somewhat expected that you see this notification because the error message says it all:

> The session is not valid due the following reasons: password expiration or **recent password change**, SSO Artifact is invalid or expired, session is not fresh enough for application, or a silent sign-in request was sent but the user's session with Azure AD is invalid or has expired.

But I would expect that you would see this notifications on any existing open windows across your devices and then never again.

**Comment by GreyElec** [comment] 2022-03-20 02:32
Hi @TylerLeonhardt , Yes, I changed the password, I do understand I should see the notification but my issue is, the message shows up every time I opened the VSCODE on any of the devices after the password change. this doesn't looks right to me. 

it seems there is an outdated cache and it was never replaced.

**Comment by TylerLeonhardt** [comment] 2022-03-21 16:37
Can you do this and let me know what you see:
https://github.com/microsoft/vscode/issues/145189#issuecomment-1073077050

**Comment by GreyElec** [comment] 2022-03-22 01:26
![image](https://user-images.githubusercontent.com/33427038/159388673-689eaba2-2310-42f2-9d31-cab955e3397c.png)
tried dozens of times but I am OK to do it one more time, as shown in the figure,  after logout, login, and restarting VSCODE, the message shows up and tells about this error.

**Comment by Chikitosexi87** [comment] 2022-03-22 05:11
Me abian robado el dispositivo me podrian dejar ingresar otra ves

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by capegreg** [comment] 2022-03-22 13:20
I am having this issue too, after changing my Microsoft account password. I tried above to sign out and re-launch but notification keeps showing. "You have been signed out because reading stored authentication information failed." I then choose to sign in with Microsoft account. This launched browser and response is "You are signed in now and can close this page." But does not resolve the issue. I will try to re-install VSCode.

![image](https://user-images.githubusercontent.com/1051118/159490698-29b30c37-b337-4ecd-a3e6-66100b3a36b3.png)

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by capegreg** [comment] 2022-03-22 20:22
This link helped me.

How to fix:

1. Exit Visual Studio Code application
2. Open: Credential Manager ("Start → Settings" → then search for "Credential Manager")
3. Click on the Windows Credentials tab.
4. Remove all credentials start with vscode.vscode, git:, ada:
5. Open Visual Studio Code application and login again. Done

https://xenvn.com/threads/vscode-fix-you-have-been-signed-out-because-reading-stored-authentication-information-failed.2584/#post-3139

![image](https://user-images.githubusercontent.com/1051118/159569075-eafd7fc9-4c5c-4305-a188-ba2897d55245.png)

**Comment by GreyElec** [comment] 2022-03-23 07:20
Wow, really nice tips. this workaround helped on my side. 

> This link helped me.
> 
> How to fix:
> 
> 1. Exit Visual Studio Code application
> 2. Open: Credential Manager ("Start → Settings" → then search for "Credential Manager")
> 3. Click on the Windows Credentials tab.
> 4. Remove all credentials start with vscode.vscode, git:, ada:
> 5. Open Visual Studio Code application and login again. Done
> 
> https://xenvn.com/threads/vscode-fix-you-have-been-signed-out-because-reading-stored-authentication-information-failed.2584/#post-3139
> 
> ![image](https://user-images.githubusercontent.com/1051118/159569075-eafd7fc9-4c5c-4305-a188-ba2897d55245.png)

**Comment by luis-guilherme** [comment] 2022-03-23 08:31
This sorted it out for Windows. Also interesting to see how many tokesn/password I needed to cleanup. Now the question is, what is the equivalent in macos, has I still have the issue there

**Comment by luis-guilherme** [comment] 2022-03-23 08:36
> This sorted it out for Windows. Also interesting to see how many tokesn/password I needed to cleanup. Now the question is, what is the equivalent in macos, has I still have the issue there

Answering my own question, it is in Keychain Access. In Keychain Access, select 'login' on the left side, then you can filter on the top right search box for 'vscode' and just delete all entries. Sorted.

**Comment by jpixy** [comment] 2022-03-24 06:59
I got same issue on Linux .so how to deal with it ?

**Comment by luis-guilherme** [comment] 2022-03-24 13:54
> I got same issue on Linux .so how to deal with it ?

That may depend on the distro used. Gnome Wallet? KDE Wallet? Just guessing here, will give a look next time I boot into Linux

**Comment by TylerLeonhardt** [comment] 2022-03-24 13:59
This is all great information, folks. I'm curious to know if you all get into a bad state again if you change your password once more.

When I tried, I was unable to reproduce.. which leads me to believe that you all got into a bad state from a previous change I made, and that new customers won't be affected by this.

If my theory is true, I will at least document these steps to clear the vscode specific items out of the keychain.

**Comment by TylerLeonhardt** [comment] 2022-03-24 14:01
@jpixy on Ubuntu with gnome, there's an app called "Passwords & Keys" and from there the steps are similar to what others have shown on macOS and Windows.

**Comment by luis-guilherme** [comment] 2022-03-24 14:03
as an FYI, in my case I was running on multiple computers with different OS (a Win11, a Win10, a MacOS an Ubuntu machine). Once I changed the password issue was on all machines. I did notice I had multiple entries for vscode, I believe one for each time I logged out and logged in again.

**Comment by Rahsna** [comment] 2022-04-08 05:07
Finally a fix! Thank you for the workaround @capegreg! I had been dealing with this issue for about as long as @GreyElec  😅

> This link helped me.
> 
> How to fix:
> 
> 1. Exit Visual Studio Code application
> 2. Open: Credential Manager ("Start → Settings" → then search for "Credential Manager")
> 3. Click on the Windows Credentials tab.
> 4. Remove all credentials start with vscode.vscode, git:, ada:
> 5. Open Visual Studio Code application and login again. Done
> ...

**Comment by zhihaoy** [comment] 2022-04-11 16:51
I got the same issue and solved it in the same way.

Note that maybe it's only me: I left Visual Studio Code UI on while deleting Windows Credentials. After reopening the UI, Sync says it is enabled and syncing, but not. It "synced" 0 profiles. You have to turn off sync and turn it back on.

**Comment by rodrigoespinozadev** [comment] 2022-04-13 17:50
> > This sorted it out for Windows. Also interesting to see how many tokesn/password I needed to cleanup. Now the question is, what is the equivalent in macos, has I still have the issue there
> 
> Answering my own question, it is in Keychain Access. In Keychain Access, select 'login' on the left side, then you can filter on the top right search box for 'vscode' and just delete all entries. Sorted.
> 
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/5901087/159658092-f2418314-c707-465c-8817-aa400281bfa5.png">

Thank you so much this worked for me

**Closed** 2022-04-14 22:21 UTC
Labels: bug, authentication

**Comment by TylerLeonhardt** [comment] 2022-04-14 22:23
Ahh I see what I was doing wrong. Those sessions from your password change weren't being removed properly. Now they should be! This will be in VS Code Insiders tomorrow and VS Code stable early next month.

**Comment by Bruno2049** [comment] 2022-04-26 14:25
> > This sorted it out for Windows. Also interesting to see how many tokesn/password I needed to cleanup. Now the question is, what is the equivalent in macos, has I still have the issue there
> 
> Answering my own question, it is in Keychain Access. In Keychain Access, select 'login' on the left side, then you can filter on the top right search box for 'vscode' and just delete all entries. Sorted.
> 
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/5901087/159658092-f2418314-c707-465c-8817-aa400281bfa5.png">

Thank you @rodrigoespinozadev, that solve the problem.

**Comment by rzhao271** [comment] 2023-01-23 19:57
I'll mark this issue as verified as part of https://github.com/microsoft/vscode/issues/172064. Please file a new issue if the bug continues to occur on the latest Stable and/or Insiders versions of VS Code.
