### ISSUE TITLE
Font display is weird.

### ISSUE THREAD

**Issue by lukelucode** [Microsoft/vscode#38680] opened 2017-11-18 12:01 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.13.0-kali1-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
cpptools|ms-|0.14.2
markdown-all-in-one|yzh|0.11.1

---

Steps to Reproduce:
1. just startup code software
2.
![selection_003](https://user-images.githubusercontent.com/29792493/32980056-f643e30a-cc9a-11e7-95cb-65da6df8963b.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment] 2017-11-19 00:25
/duplicate of https://github.com/Microsoft/vscode/issues/35675

**Closed by roblourens** 2017-11-19 00:25 UTC
Labels: *duplicate, extensions, new release
