### ISSUE TITLE
please add enable emmet expand abbreviations in customlanguage

### ISSUE THREAD

**Issue by izcream** [Microsoft/vscode#6191] opened 2016-05-07 18:08 UTC
- VSCode Version: 1.0.0
- OS Version: Windows

I love this editor. it's awesome, very fast response, open, edit.
but it's not support emmet expand abbreviations in custom syntax eg .blade, .vue 

 i try to add "files.associations": {"*.blade.php": "html"}, emmet work but my extension blade syntax hilighting not working. if it's can work together i think my heart is got by vscode :+1: 

if next release has settings about enable emmet expand abbreviations in settings.json or other place.
i think it's wonderful text editor in this world.

Best regard

ps. sorry for my bad english

**Comment by Namek** [comment] 2016-08-10 23:33
I'd like to also see such setting.

FYI `.vue` is for [Vue.js](https://vuejs.org/), `.blade.php` is for [Laravel](https://laravel.com/).

**Comment by mrmlnc** [comment] 2016-08-24 22:21
Duplicate #4700.

@izcream or @egamma close this issue, please.

**Comment by egamma** [comment] 2016-08-25 06:10
duplicate of #9500

**Closed by egamma** 2016-08-25 06:10 UTC
Labels: feature-request
