### ISSUE TITLE
Terminal: ^[[D cheese when opt-click on link

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#114057] opened 2021-01-08 21:02 UTC
Version: 1.53.0-insider
Commit: ed6c343edb720d91ee0859e566c84b5687f5a9d5
Date: 2021-01-08T10:44:29.135Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 19.6.0

When option-clicking on a URL in the terminal, I get some string cheese before the terminal opens:

![image](https://user-images.githubusercontent.com/1487073/104063715-6fb31280-51b1-11eb-9f5b-20a7127412a0.png)

to repo

- simple node server app that spits out the url its listening on:

``` javascript
const express = require('express');
const app = express();
app.listen(3005, function() {
  console.log('server listening on http://localhost:3005');
});
```

- run from the terminal with `node server.js`
- option + click on `http://localhost:3005`

Results

```
^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D
```

**Comment by meganrogge** [comment] 2021-01-15 18:06
Duplicate of #101136

**Closed** 2021-01-15 18:07 UTC
Labels: *duplicate, bug, integrated-terminal
