### ISSUE TITLE
Regression: Markdown preview editor is scrolling to random locations

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#30080] opened 2017-07-04 07:13 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (cea00a71bef01a5ecbae39a8dd4f1bd08fd50c57, 2017-07-03T11:05:04.616Z)
- OS Version: Darwin x64 16.6.0

---

Steps to Reproduce:
* configure the markdown preview to never scroll by itself:
  * configure `"markdown.preview.scrollEditorWithPreview": false`
  * configure `"markdown.preview.scrollPreviewWithEditorSelection": false`
* try to edit the 1.14 release notes
  * go to the Notable Changes section and press a space;
  * then delete the space.
* observe: the markdown preview is scrolling by itself to random locations, making the side-by-side editing-preview experience broken:
 > Note: I think this worked last endgame when I wrote my release notes.

![markdown-jumpy](https://user-images.githubusercontent.com/5047891/27819016-93e3b8de-6098-11e7-9ad4-22a2c696184f.gif)

**Comment by kieferrm** [comment] 2017-07-05 16:37
I can not reproduce the random scrolling, but I do get full page reloads with every single modification.

**Comment by mjbvz** [comment] 2017-07-05 18:27
Fix for the flickering https://github.com/Microsoft/vscode/commit/af2757c1f64e1a2921d67b7df56b4d62d3adc9ef

**Comment by mjbvz** [comment] 2017-07-05 18:42
Cherry picked flicked fix into 1.14: 767eea0 

The scroll one does not seem like a regression from 1.13. Moving this out of June

**Comment by mjbvz** [comment] 2017-09-05 22:54
I believe this was fixed by some work I did to improve scroll sync with webviews. I tested on the VS Code docs but was not able to reproduce this issue anymore

Please let me know if you still see this in a specific document

**Closed by mjbvz** 2017-09-05 22:54 UTC
Labels: bug, insiders, markdown

**Comment by alexandrudima** [comment] 2017-09-28 13:45
Nice!
