### ISSUE TITLE
import intellisense not working v1.11.2 or higher

### ISSUE THREAD

**Issue by sdey0081** [Microsoft/vscode#28852] opened 2017-06-16 01:28 UTC
- VSCode Version: 1.11.2 and higher (now 1.13.1)
- OS Version: Windows 10 x64, macOS 12

Steps to Reproduce:

1. Open a angular 2(4) or Ionic 2 project.
2. Type `import`, and select `import statement` on the hint list, then it generates import template like bellow:
` import {  } from "module";`
3. Once typed any text in the `"module"`, it shows module list related with the text (This is what I expected, and worked less than v1.10.2), but not working newest version. 

Here are the screenshots I faced.

New version( v1.11.2 or higher)

![image](https://user-images.githubusercontent.com/22894033/27207777-da5abb60-5273-11e7-8fe7-932ace24fc7e.png)

Old version(v1.10.2 or lower), what I expected
![image](https://user-images.githubusercontent.com/22894033/27207991-7bffacc2-5275-11e7-9ac4-d17c08e708a9.png)
![image](https://user-images.githubusercontent.com/22894033/27208026-c7183396-5275-11e7-9a54-8e26547fc29d.png)

**Comment by mjbvz** [comment] 2017-06-16 21:17
This is a duplicate of #23962. The root cause was a change to our default `editor.quickSuggestions` setting See [this comment](https://github.com/Microsoft/vscode/issues/23962#issuecomment-292079416) for a workaround

**Closed by mjbvz** 2017-06-16 21:17 UTC
Labels: new release
