### ISSUE TITLE
Extreemely slow performance at random

### ISSUE THREAD

**Issue by cobalt88** [microsoft/vscode#184071] opened 2023-06-01 14:28 UTC
Type: <b>Performance Issue</b>

Im not sure how to reproduce this since as it does not appear to be happening consistently, however, it does happen on every machine I have synchronised with my vs code profile so I assume its settings thing, even though I dont recall making any changes before it started about a month ago. 

When saving a document - even when as little as 1 line of code has been changed, I see the "Saving <document name here>" modal at the bottom right of the screen, often times for several minutes before the file is actually saved. If I cancel the save the file usually appears to have been saved normally but not always. This doesnt happen every time I got to save a document though, maybe 50% of the time. On other occasions it will do this while running Prettier Code Formatter, again not every single time but often enough to be a perfomance hinderance. Ive tried reducing the number of plugins, reloading vs-code, making sure everything is up to date, working on different projects on different machines with different operating systems (windows 10 and windows 11) , and am not sure what to try next. Hopefully its just some setting on my end that I can change.

I am including all data that I can with this, and if you have any suggestions on how to troubleshoot the problem that would be awesome, as this has become more and more of an interruption in my workflow. 

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (40 x 2993)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (38.95GB free)|
|Process Argv|E:\\21-15\\Unsolved --crash-reporter-id 6d1c655f-1070-4343-a03f-63b6ebb11c63|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   116	 36352	code main
    0	     7	 12556	   crashpad-handler
    0	   258	 12928	extensionHost [6]
    0	    23	  3792	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.74.0\dist\src\ssmDocument\ssm\ssmServer.js --node-ipc --clientProcessId=12928)
    0	   130	  7464	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\Vincent\AppData\Local\Temp\vscode-typescript\5a3b47b5af336b7c4547\tscancellation-e30bb6080d19d6ec143c.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    31	   756	       electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/Vincent/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/Vincent/AppData/Local/Microsoft/TypeScript/5.0 --enableTelemetry --typesMapLocation "c:/Users/Vincent/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation)
    0	    67	 34516	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\Vincent\AppData\Local\Temp\vscode-typescript\5a3b47b5af336b7c4547\tscancellation-d98519578445dcfb132c.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	   111	 36372	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\streetsidesoftware.code-spell-checker-2.20.4\packages\_server\dist\main.js --node-ipc --clientProcessId=12928)
    0	    26	 46116	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.74.0\dist\src\stepFunctions\asl\aslServer.js --node-ipc --clientProcessId=12928)
    0	    25	 50212	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=12928)
    0	   193	 22764	   gpu-process
    2	   384	 22844	extensionHost [4]
    0	   187	  5236	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\streetsidesoftware.code-spell-checker-2.20.4\packages\_server\dist\main.js --node-ipc --clientProcessId=22844)
    0	   327	 30396	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\Vincent\AppData\Local\Temp\vscode-typescript\61039dba202e023e1a90\tscancellation-1ca953e4106d223b6775.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    93	 19628	       electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/Vincent/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/Vincent/AppData/Local/Microsoft/TypeScript/5.0 --enableTelemetry --typesMapLocation "c:/Users/Vincent/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation)
    0	    90	 30560	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.74.0\dist\src\stepFunctions\asl\aslServer.js --node-ipc --clientProcessId=22844)
    0	    86	 31980	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=22844)
    0	    91	 39472	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.74.0\dist\src\ssmDocument\ssm\ssmServer.js --node-ipc --clientProcessId=22844)
    0	   150	 41284	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Vincent\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js --node-ipc --clientProcessId=22844)
    0	   126	 45948	     electron-nodejs ("C:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\Vincent\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\Vincent\AppData\Local\Temp\vscode-typescript\61039dba202e023e1a90\tscancellation-db1b58503c4426ae4f13.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	     6	 53856	     "C:\Program Files\Git\cmd\git.exe" check-ignore -v -z --stdin
    0	     7	 19516	       git.exe check-ignore -v -z --stdin
    0	    12	 50068	       console-window-host (Windows internal process)
    0	   302	 25800	window [4] (DefaultDash.jsx - CircleConnect - Visual Studio Code)
    0	   232	 35356	window [6] (getLoadIds.js - TproHourlyDataPull - Visual Studio Code)
    0	    22	 42836	   utility-network-service
    0	    97	 43684	window [8] (Issue Reporter)
    0	    58	 43688	shared-process
    0	    60	 22584	     ptyHost
    0	     5	 17696	       "C:\Program Files\Git\bin\bash.exe" --login -i
    0	    10	  7440	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login -i
    0	     8	 18472	       console-window-host (Windows internal process)
    0	     7	 23908	       console-window-host (Windows internal process)
    0	     6	 26612	       "C:\Program Files\Git\bin\bash.exe" --login -i
    0	    12	 24380	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login -i
    0	    28	 46444	fileWatcher [6]
    0	    90	 52400	fileWatcher [4]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (getLoadIds.js - TproHourlyDataPull - Visual Studio Code)
|  Window (DefaultDash.jsx - CircleConnect - Visual Studio Code)
|    Folder (TproHourlyDataPull): 488 files
|      File types: js(289) mjs(92) log(20) json(17) md(6) dockerignore(3)
|                  gitignore(3) env(2) EXAMPLE(2) env_20230124182824(1)
|      Conf files: package.json(3) dockerfile(2)
|    Folder (CircleConnect): 356 files
|      File types: js(74) jsx(70) pack(55) png(27) json(20) webp(12) svg(12)
|                  jpg(8) old(4) local(3)
|      Conf files: package.json(2) jsconfig.json(1);
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.74.0
vscode-apollo|apo|1.19.11
vscode-tailwindcss|bra|0.9.11
prettier-vscode|esb|9.13.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
copilot|Git|1.87.127
copilot-labs|Git|0.14.884
vscode-graphql-syntax|Gra|1.1.0
dotenv|mik|1.0.1
python|ms-|2023.8.0
prisma|Pri|4.15.0
vscode-yaml|red|1.13.0
code-spell-checker|str|2.20.4
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by chrmarti** [comment] 2023-06-02 15:37
Does this occur with all extensions disabled? (`F1` > `Developer: Reload With Extensions Disabled` or `code --disable-extensions`)

**Comment by cobalt88** [comment] 2023-06-02 18:39
no, after disabling and re-enabling everything one at a time again I think the culprit is Prettier. When Prettier was disabled it didnt do it at all, even replacing entire files, but as soon as I re-enabled it (including with no other extensions enabled) the problem came back. So this can probably be closed since it doesnt look like its an issue with VS Code.

**Comment by RyelBanfield** [comment] 2023-06-02 19:32
I have the same issue when using Prettier. Works fine for a while but after about 10mins, gets super slow to save and I click to close and reopen VSCode.

Found someone said to downgrade VSCode here - https://github.com/prettier/prettier-vscode/issues/1333#issuecomment-1573925970

**Comment by chrmarti** [comment] 2023-06-05 07:20
Could you open a new issue for Prettier? I guess, ideally you could provide steps to reproduce and a public repository with code where the issue reproduces. (https://github.com/prettier/prettier-vscode/issues/1333 is closed and was filed a long time ago.) See https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions for how to profile the extension yourself.

Closing as caused by extension. Thanks.

**Closed by chrmarti** 2023-06-05 07:20 UTC
Labels: info-needed
