### ISSUE TITLE
Editor overrides should operate on untyped editors only

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124351] opened 2021-05-21 10:41 UTC
Related to https://github.com/microsoft/vscode/issues/106012, the editor override service ideally:
* works on exclusively on `IResourceEditorInput | IUntitledTextResourceEditorInput | IResourceDiffEditorInput`

The would allow us to prevent this `createEditorInput` from running before the overrides are figured out:

https://github.com/microsoft/vscode/blob/f19843b0a3e508d613f5b1b43d0de50cd83a3ac8/src/vs/workbench/services/editor/browser/editorService.ts#L602-L602

(also in other places). This helps prevent leaks in editor inputs.

**Comment by lramos15** [comment] 2021-05-21 12:52
This is a duplicate of https://github.com/microsoft/vscode/issues/121101. But I'll close the other one as I think the explanation here is nicer.

**Comment by lramos15** [comment] 2021-05-21 19:37
The largest problem I'm currently running into with this is the diff editors. It seems that a lot of the consumers of the editor override service want names and descriptions from the typed diff editor input but by only allowing for `IResourceDiffEditorInput` we don't have that information.

**Comment by bpasero** [comment] 2021-05-22 06:16
We can easily enrich the untyped editors with all the info we need.

**Closed** 2021-06-11 18:59 UTC
Labels: debt, workbench-editor-override
