### ISSUE TITLE
Offer 'extract constant' first

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#79698] opened 2019-08-23 08:47 UTC
I much more often extract a constant than a function:
![image](https://user-images.githubusercontent.com/9205389/63579551-36194180-c593-11e9-9498-9e480bfa3461.png)

Can the 'extract constant' be moved to the top?

**Comment by mjbvz** [comment] 2019-08-24 03:37
Duplicate of https://github.com/microsoft/TypeScript/issues/29589

**Closed by mjbvz** 2019-08-24 03:37 UTC
