### ISSUE TITLE
language pack extension doesn't work after restart

### ISSUE THREAD

**Issue by cnjawi** [microsoft/vscode#189770] opened 2023-08-06 18:00 UTC
Type: <b>Bug</b>

I've been using the Chinese language pack before, but lately it's not working.
When I open a new window, the interface language remains the default English. After I reinstalled and restarted, the interface language changed to Chinese. But after restarting again, it changed back to the original and vscode prompts me to install the language pack again. Throughout the process, it never appeared in the installed extension list.
I tried other language packs that were not previously installed and this problem does not occur. The attempt in vscode insider version is also fine.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|6.94GB (2.07GB free)|
|Process Argv|--crash-reporter-id b3cb70f6-3f3a-48e6-9db0-d5bb41631a5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-clangd|llv|0.1.24
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.10
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
remote-wsl|ms-|0.81.0
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
hexeditor|ms-|1.9.12
material-icon-theme|PKi|4.29.0
sqlite-viewer|qwt|0.3.13
xmake-vscode|tbo|2.1.5
cmake|twx|0.0.17
cloudmusic|YXL|9.19.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by 377960738** [comment] 2023-08-07 11:28
My situation is: in the second window opened by Ctrl + shift + n shortcut keys, the 'chinese simple language' extension appears to be missing, and the extension will not take effect if it is installed again (the operating system is wsl), so far I have returned to Back version  1.80.2, because I need to open multiple entity windows to work.

**Comment by cedx** [comment] 2023-08-07 12:50
Same issue here with French language pack.

**Comment by FlorianLeChat** [comment] 2023-08-07 18:08
I can also confirm on my side following the latest update using the French language pack.

**Comment by iHuahua** [comment] 2023-08-07 18:17
一样的情况，提示切换英文->重启->变回英文->提示安装中文->安装中文->再重启->几分钟后再次提示切换英文，无限循环，我还以为是前两天弄那个什么profile file弄出啥问题了

**Comment by 377960738** [comment] 2023-08-08 00:55
> 一样的情况，提示切换英文->重启->变回英文->提示安装中文->安装中文->再重启->几分钟后再次提示切换英文，无限循环，我还以为是前两天弄那个什么profile file弄出啥问题了
我回退到上一个版本了，先顶几天，等待修复。git界面也是翻译不全反反复复的😂

**Comment by OpportunityLiu** [comment] 2023-08-08 07:20
It seems to be caused by some old config file from old versions.

I have a machine installed 1.80 at first and updated to 1.81 does not have this issue.
Another machine, which has this issue, is fixed by delete %AppData%/Code and %HOME%/.vscode and resync all settings and extensions.

**Comment by Juvwxyz** [comment] 2023-08-08 14:12
> 

Thank you, solved.

**Comment by TylerLeonhardt** [comment] 2023-08-08 17:36
@sandy081 assigning this to you since it seems to be related to language pack installation... let me know what you think.

**Comment by alexdima** [comment] 2023-08-08 20:56
I'm trying to reproduce with the following steps:
* I install a language extension pack (like the French Language Pack)
* I get prompted if I want to switch the language
* I choose Yes
* VS Code restarts in French
* I quit VS Code and start it again and it still comes up in French

Is there anything more to it? Do you have more special setups? Are you using VS Code Remote Extensions or profiles or something more special? @TylerLeonhardt Are you able to reproduce?

**Comment by zhangzhao219** [comment] 2023-08-09 00:34
> I'm trying to reproduce with the following steps, but I don't manage to get a repro:
> 
> * I install a language extension pack (like the French Language Pack)
> * I get prompted if I want to switch the language
> * I choose Yes
> * VS Code restarts in French
> * I quit VS Code and start it again and it still comes up in French
> 
> Is there anything more to it? Do you have more special setups? Are you using VS Code Remote Extensions or profiles or something more special? @TylerLeonhardt Are you able to reproduce?

Yes! I use VS Code Remote Extensions and then find this problem!
When VSCode starts the first time, I installed language extension pack (Chinese) and Remote Extensions, then I quit VS Code and start it again, it seems normal. 
But when I use Remote Extensions to connect remote server, especially Remote - SSH, VSCode mentioned that I do not install language extension pack (Chinese) **locally**, and then I can not find my language extension pack (Chinese) locally either. Although I chose to install it locally, it do not work and will mention the same problem the next time I start VSCode. 
Besides, my display language is Chinese or English randomly, whether I find the Chinese language extension pack or not.
I guess that this problem is with the VSCode newest version 1.81.0, cause when I uninstall it and install the old version, the problem disappeared.

**Comment by Aurorabili** [comment] 2023-08-09 09:03
I think this issue may only appear in language extension pack (Chinese). When I try to install Chinese language extension, the plugin disappears from the extension list after restarting vscode, but when I install Japanese language, it works.

```
Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

loc version: `v1.81.2023080209`

**Comment by midkir** [comment] 2023-08-09 10:52
I am using the Japanese language pack and I have the same problem.
I think it sometimes happens when I switch between local Windows vscode and WSL vscode on the same machine via remote extension.
I guess that extended profile sync functionality in v1.81 may cause this problem.

**Comment by alexdima** [comment] 2023-08-09 13:09
@midkir Could you please briefly explain the way you use profiles? Are you using perhaps "Apply this extension to all Profiles"?

**Comment by alexdima** [comment] 2023-08-09 13:12
I found some steps which reproduce the language pack getting uninstalled:
* (you can start with no profiles)
* install the French language extension
* switch the language to French and restart VS Code
* Import a builtin profile like the nodejs one
* the French language extension is uninstalled

**Comment by galaxy-s10** [comment] 2023-08-09 14:56
I also encountered it

**Comment by joyceerhl** [comment] 2023-08-09 19:27
The steps from https://github.com/microsoft/vscode/issues/189770#issuecomment-1671303587 no longer repro with https://github.com/microsoft/vscode/pull/190067

**Comment by joyceerhl** [comment] 2023-08-09 21:28
This should be fixed in the latest insiders build, can you please try it out there and let us know if it still repros for you or if you see other extension bugs?

**Closed by joyceerhl** 2023-08-09 21:28 UTC
Labels: bug, candidate, confirmed, regression

**Comment by midkir** [comment] 2023-08-09 23:18
I had two profiles (without(default)/with copilot) and was having this issue.
I tried it on the latest Insider build and couldn't reproduce it. thank you.

**Comment by silascript** [comment] 2023-08-10 18:16
> 一样的情况，提示切换英文->重启->变回英文->提示安装中文->安装中文->再重启->几分钟后再次提示切换英文，无限循环，我还以为是前两天弄那个什么profile file弄出啥问题了

应该跟Profile还是有点关联的。反正我是删除了.vscode和.config/Code后，以全新的VSCode状态下，重新导入之前版本下配的Profile，然后发现语言包就消失了。后来我试了下，在1.81版本下重新配过新的Profile，再导入，语言包就没事了。估计跟Profile的调整有关--反正Profile这块就是有各种小bug。
