### ISSUE TITLE
Interface overview is not following the side bar location

### ISSUE THREAD

**Issue by Pulgovisk** [Microsoft/vscode#37955] opened 2017-11-09 15:28 UTC
The interface overview is not following the side bar location. It´s assuming the side bar is on left side

![Interface overview](https://i.imgur.com/DZOWPbH.png)

- VSCode Version: 1.19.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode
2. Move the side bar to rigth
3. Open the interface overview

Reproduces without extensions: Yes

**Comment by sandy081** [comment] 2017-11-10 09:17
@Pulgovisk Not sure what do you mean by interface overview?

**Comment by Pulgovisk** [comment] 2017-11-10 09:59
@sandy081 The interface overview is a new feature, described in [v1.9 releases notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_9.md#welcome-experience)

```
If you are a new user, you will appreciate the Interface overview available from the Welcome page. It calls out the basic parts of the user interface with their keyboard shortcuts:
````

**Comment by sandy081** [comment] 2017-11-10 11:39
Oh yeah.. you are right. Forgot about it.

**Comment by chrmarti** [comment] 2017-11-10 15:36
Duplicate of #23602

**Closed by chrmarti** 2017-11-10 15:36 UTC
Labels: workbench
