### ISSUE TITLE
Have a collapse region button at the #endregion tag and not only at the top

### ISSUE THREAD

**Issue by scott-parkhill** [microsoft/vscode#125407] opened 2021-06-03 15:49 UTC
This feature is pretty straightforward. I would love it if you could collapse a region at the end of a region, please. It is VERY common that I am scrolling through code trying to find what I'm looking for and want to collapse regions as I scroll through. The problem is, when you've already scrolled through, that means you're at the bottom of a region, and then have to scroll all the way back to the top of the region to collapse it. I would like to be able to collapse the region once I'm at the bottom of it and have already reviewed everything. Thank you!

**Comment by aeschli** [comment] 2021-06-04 13:09
duplicate of https://github.com/microsoft/vscode/issues/60670

**Closed by aeschli** 2021-06-04 13:09 UTC

**Comment by scott-parkhill** [comment] 2021-06-04 14:24
Apologies, I didn't realise this was called "folding".
