### ISSUE TITLE
Added fonts will not display when the computer is restarted, and restarting the font cache fixes it.

### ISSUE THREAD

**Issue by darkenwarlock** [microsoft/vscode#226674] opened 2024-08-26 21:43 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Version: Windows 11 (Windows_NT x64 10.0.22631)

When the font is messed up:
![image](https://github.com/user-attachments/assets/13221bda-f6b9-49f9-8de9-c037be94fd25)
![image](https://github.com/user-attachments/assets/4f29c86b-cb77-480a-a795-a6ca234aa6c0)

After restarting the font cache and restarting VS Code:
![image](https://github.com/user-attachments/assets/72b62843-6372-444c-9466-d8a70b8a0b6b)

Steps to Reproduce:

1. Enable a new font within VS Code. Specifically, enable Fira Code with font ligatures.
2. Restart VS Code and code for a few minutes.
3. Exit VS Code.
4. Put the computer to sleep.
5. Wake the computer and open VS Code.
6. The font now changes to monospace or any default font set below "Fira Code."
7. Open Windows services.
8. Restart Windows font cache service.
9. Restart VS Code.
10. Font now appears as Fira Code.

**Comment by rzhao271** [comment] 2024-08-26 22:09
Duplicate of #173543 but thanks for the steps!

**Closed by rzhao271** 2024-08-26 22:09 UTC
