### ISSUE TITLE
UI doesn't indicate each thread listed in the call stack as having been "PAUSED ON EXCEPTION" on loading core dump

### ISSUE THREAD

**Issue by ayushsahay1837** [microsoft/vscode#165032] opened 2022-10-31 07:30 UTC
**Version of VS Code:** 1.67.2

**OS:** Ubuntu 18.04.6 LTS

**Reproducible steps that cause the issue:**

Have Visual Studio Code load a core dump in _lldb_ via _lldb-vscode_ (debug adapter for Visual Studio Code available as part of the LLDB project, which, to the best of my knowledge, is unpublished) by employing an attach configuration akin to the following –

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Post-mortem Debug",
            "type": "lldb-vscode",
            "request": "attach",
            "program": "${workspaceFolder}/a.out",
            "coreFile": "${workspaceFolder}/a.out.core"
        }
    ]
}
```

**What I expect to see, versus what I actually see:**

All threads in the process are stopped with reason _exception_ –

```
...

{"body":{"allThreadsStopped":true,"preserveFocusHint":false,"reason":"exception","threadCausedFocus":true,"threadId":848},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":843},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":844},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":845},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":846},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":847},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":849},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":850},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":851},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":852},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":853},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":854},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":855},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":856},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1881},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1882},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1883},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1884},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1886},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1887},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1888},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1889},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":true,"preserveFocusHint":true,"reason":"exception","threadId":1890},"event":"stopped","seq":0,"type":"event"}

...
```

So, I'd expect the UI to indicate each thread listed in the call stack as having been _PAUSED ON EXCEPTION_. However, I see that the UI indicates only _Thread # 23_ as having been _PAUSED ON EXCEPTION_, and others as having been _PAUSED_ –

![AllThreadsStoppedTrue](https://user-images.githubusercontent.com/12513869/198950367-f0095d68-c79a-4ca7-8627-8014186197b7.JPG)

What's curious, though, is that if _allThreadsStopped_ is reported as _false_ in each of the pertinent stopped events, then the UI indicates all threads in the call stack as having been _PAUSED ON EXCEPTION_ –

```
...

{"body":{"allThreadsStopped":false,"preserveFocusHint":false,"reason":"exception","threadCausedFocus":true,"threadId":848},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":843},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":844},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":845},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":846},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":847},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":849},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":850},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":851},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":852},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":853},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":854},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":855},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":856},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1881},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1882},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1883},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1884},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1886},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1887},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1888},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1889},"event":"stopped","seq":0,"type":"event"}

{"body":{"allThreadsStopped":false,"preserveFocusHint":true,"reason":"exception","threadId":1890},"event":"stopped","seq":0,"type":"event"}

...
```

![AllThreadsStoppedFalse](https://user-images.githubusercontent.com/12513869/198950594-48262c87-a9ec-494f-8509-cd7b25690e18.JPG)

Kindly let me know in case any additional information is required.

**Comment by roblourens** [comment] 2022-11-01 00:05
Initial investigation shows that this is from https://github.com/microsoft/vscode/blob/a803dc359aa1ed48c7acf074dd81d6af1525c8c8/src/vs/workbench/contrib/debug/browser/debugSession.ts#L892

I think it essentially clears the previous pause reason when processing the `allThreadsStopped`. I think this could keep the previous `stoppedDetails` on the thread. But, isn't it odd to send `allThreadsStopped` if you are going to send individual stopped events for every thread anyway?

**Comment by ayushsahay1837** [comment] 2022-11-01 13:00
@roblourens, I imagine that that's an implication of the design. Currently, LLDB supports only process-centric debugging. So, when any thread in a process stops, all the other threads are stopped too. I reckon that that's why _lldb-vscode_ reports _allThreadsStopped_ as _true_ for every stopped event. However, AFAICT, _lldb-vscode_ maintains neither a list nor the states of the processes and threads under debug, and relies on pertinent events broadcast by LLDB to report stopped events. Now, if I'm not wrong, then all the threads in a core dump are stopped. So, I'd expect LLDB to broadcast a pertinent event for each thread in a core dump, and _lldb-vscode_ to consequently report stopped events for all the threads.

**Comment by roblourens** [comment] 2022-11-01 15:56
Sure, that's fine. Seems correct for vscode to support this the way you're using it.

**Comment by ayushsahay1837** [comment] 2022-11-01 17:00
@roblourens, thanks! 😁

BTW, is it too early for any work on this to be planned for a specific release? I only ask so that I can offer our customers a ballpark estimate of when they can expect the fix for this to become available. 😬

**Comment by roblourens** [comment] 2022-11-01 18:02
How does next month sound? 😄

**Comment by roblourens** [comment] 2022-11-01 18:03
And once the PR above is merged, and we have resumed shipping new Insiders after this week's release (should be by the end of the week, or next Monday), I'd appreciate you verifying that the issue is actually fixed

**Comment by ayushsahay1837** [comment] 2022-11-01 19:30
@roblourens, sure, I'd be happy to! Thanks a lot for looking into this! 😁

**Closed** 2022-11-02 05:12 UTC
Labels: bug, debug

**Comment by ayushsahay1837** [comment] 2022-11-08 06:30
@roblourens, the UI indicates each thread listed in the call stack as having been _PAUSED ON EXCEPTION_ in the latest release of _Visual Studio Code Insiders_.

![AllThreadsStoppedTrueFixed](https://user-images.githubusercontent.com/12513869/200483019-a82740ba-1ec1-4cf6-9b87-e6840e9a56a6.JPG)
