### ISSUE TITLE
VS Code Blurry Text Ubuntu Bionic Beaver

### ISSUE THREAD

**Issue by ahmedbilal** [Microsoft/vscode#44086] opened 2018-02-21 05:33 UTC
- VSCode Version: 1.20.1
- OS Version: Ubuntu Bionic Beaver (Daily Build)

Steps to Reproduce:

1. Install Ubuntu Bionic Beaver (Daily Build)
2. Install VS Code
3. Open it and you would see blurry text.

Does this issue occur when all extensions are disabled?: Yes

![Screenshot](https://preview.ibb.co/ejw93H/Screenshot_from_2018_02_21_10_32_34.png)

**Comment by RMacfarlane** [comment] 2018-02-21 17:40
Duplicate of https://github.com/Microsoft/vscode/issues/35675

**Closed by RMacfarlane** 2018-02-21 17:40 UTC
