### ISSUE TITLE
Cannot access installation file for macOS Mojave 

### ISSUE THREAD

**Issue by FranjoIM** [Microsoft/vscode#62431] opened 2018-11-02 01:58 UTC
I'm trying to install the VSC through terminal for Anaconda. I keep getting following message: "Please make sure you are connected to the internet!" After I tried directly accessing the website, I get the following message:

<img width="614" alt="screen shot 2018-11-01 at 9 57 17 pm" src="https://user-images.githubusercontent.com/29928096/47889610-2d4b5980-de21-11e8-82d2-ad796eadcd90.png">

**Comment by Pyxelx** [comment] 2018-11-02 01:59
This is a duplicate of https://github.com/Microsoft/vscode/issues/62427

**Comment by Pyxelx** [comment] 2018-11-03 00:05
@FranjoIM please close this as the issue was solved a bit ago.

**Closed** 2018-11-04 17:49 UTC
Labels: *duplicate
