### ISSUE TITLE
TS Server fatal error:  Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by enoguchi-lmi** [microsoft/vscode#116388] opened 2021-02-10 23:27 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.parsePackageName (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:39472:30)
    at ConfiguredProject.Project.enablePlugin (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:151962:24)
    at ConfiguredProject.enablePluginsWithOptions (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152477:30)
    at ProjectService.loadConfiguredProject (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154206:25)
    at ProjectService.createAndLoadConfiguredProject (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154145:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154150:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
    at /Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:97
    at Object.flatMap (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
    at /Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
    at IOSession.Session.executeCommand (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
    at IOSession.Session.onMessage (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
    at Interface.<anonymous> (/Users/enoguchi/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:35:15.302Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|26, 11, 7|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id 85cdcebc-629d-480b-9f82-c2bffe1360bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.10.0
better-comments|aar|2.1.0
Bookmarks|ale|12.1.4
atlascode|atl|2.8.5
turbo-console-log|Cha|2.1.6
vscode-css-modules|cli|0.2.3
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.14
copy-name-of-current-branch|dka|0.0.1
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.64
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.1
restore-terminals|Eth|1.0.6
vscode-pull-request-github|Git|0.23.0
rest-client|hum|0.24.4
vscode-case-shifter|Jin|1.1.0
vscode-duplicate|mrm|1.2.1
debugger-for-chrome|msj|4.12.12
vscode-yaml-sort|Pas|3.1.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.5.0
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.15.0
markdown-preview-enhanced|shd|0.5.16
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
vscodeintellicode|Vis|1.2.11
quokka-vscode|Wal|1.0.342
HCL|who|0.0.5
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2
sort-js-object-keys|zen|1.0.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-02-11 00:01
/duplicate of #116219 and will be fixed in upcoming 1.53.2

**Closed** 2021-02-11 00:03 UTC
Labels: *duplicate, new release
