### ISSUE TITLE
It is desirable to be able to dynamically adjust the order of the prompts in the prompt list based on the user's choice

### ISSUE THREAD

**Issue by xiaotan0305** [Microsoft/vscode#34189] opened 2017-09-12 03:02 UTC
- VSCode Version: 1.17.0
- OS Version: 10.13 Beta

Steps to Reproduce:

1. Install plugin  `JavaScript Snippet Pack for Visual Studio Code`
2. Type `cl` to the pop-up prompt box

### I hope to be able to add according to the choice of dynamic adjustment prompt box list order, such as I often use `cl` to output `console.log`, but each time need to manually select the upper and lower keys, affecting efficiency.

![image](https://user-images.githubusercontent.com/12965330/30306079-e45d210e-973b-11e7-95f2-8be5ca2b4607.png)

### It is recommended to add dynamic adjustment options based on user input

![image](https://user-images.githubusercontent.com/12965330/30306540-60c705fa-973e-11e7-90e7-cb977d8cd27b.png)

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment] 2017-09-12 09:17
duplicate of #32886

**Closed by jrieken** 2017-09-12 09:17 UTC
