### ISSUE TITLE
Format code - disappear in 1.9.1

### ISSUE THREAD

**Issue by wizardnet972** [Microsoft/vscode#20728] opened 2017-02-16 14:09 UTC
Hi,

I searching for "format code"  through the search functionality provided in the editor with Ctrl +Shift+ P, not i cannot see that option.

Ctrl +Shift+ P -> not working.

I dont have any extenstions installed. 
This is new install.

Why?

**Comment by mrmlnc** [comment] 2017-02-16 14:13
Language? List of extensions?

**Comment by wizardnet972** [comment] 2017-02-16 14:15
just simple html snippet, I have no extensions

**Comment by mrmlnc** [comment] 2017-02-16 14:21
You use `>`?

![screencast 2017-02-16 17-19-34](https://cloud.githubusercontent.com/assets/7034281/23024639/311c6afe-f46c-11e6-9f0c-2408923a0a5b.gif)

**Comment by wizardnet972** [comment] 2017-02-16 14:23
Yes. but as you can see here I have no option like that.

![error2](https://cloud.githubusercontent.com/assets/4997825/23024769/3b1cb4b2-f464-11e6-87a7-872a1e6f322e.png)

**Comment by wizardnet972** [comment] 2017-02-16 14:23
also I got error like this:

![error](https://cloud.githubusercontent.com/assets/4997825/23024790/4eac3b92-f464-11e6-9999-481b14d4ec2b.png)

**Comment by pr-yemibedu** [comment] 2017-02-16 16:03
Hello,
 Can you provide details on your environment? Currently, a Mac and a Windows user were able to see the command is available. You should have a look at your keyboard shortcuts file. vscode will show you the default keybindings on the left and split pane your user or workspace overrides on the right.

```
{ "key": "shift+alt+f",           "command": "editor.action.formatDocument",
                                     "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly" },
{ "key": "ctrl+k ctrl+f",         "command": "editor.action.formatSelection",
                                     "when": "editorHasDocumentSelectionFormattingProvider && editorHasSelection && editorTextFocus && !editorReadonly" },
```

![image](https://cloud.githubusercontent.com/assets/22304841/23028964/e789b124-f436-11e6-8f89-9758985eee9e.png)

**Comment by wizardnet972** [comment] 2017-02-16 16:11
Yes. I have Windows 7 64bit. (admin). I try to change the keys, try to run the commands still not working :(

**Comment by joaomoreno** [comment] 2017-02-17 09:54
Duplicate of #20168

**Closed by joaomoreno** 2017-02-17 09:54 UTC
