### ISSUE TITLE
TypeScript Dies

### ISSUE THREAD

**Issue by ChadWWatson** [Microsoft/vscode#40725] opened 2017-12-22 16:00 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
react-native-react-redux-snippets-for-es6-es7-version-standard|EQu|1.0.3
vsc-material-theme|Equ|1.1.2
beautify|Hoo|1.1.1
csharpfixformat|Leo|0.0.52
vscode-docker|Pet|0.0.22
jsx|Twe|0.0.1
html-snippets|abu|0.1.0
airship-react-snippets|air|0.0.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
es7-react-js-snippets|dsz|1.3.0
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.22
prettier-vscode|esb|1.0.1
code-runner|for|0.8.6
csharpextensions|jch|1.3.0
vscode-csharp-snippets|jor|0.2.0
docomment|k--|0.0.17
Go|luk|0.6.70
vscode-language-babel|mgm|0.0.10
vscode-cosmosdb|ms-|0.3.0
azure-account|ms-|0.2.2
csharp|ms-|1.13.1
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|4.0.0
color-highlight|nau|2.3.0
Csharp-ASPNETCore|rah|1.0.5
prettier-now|rem|1.4.9
vscode-icons|rob|7.19.0
vscode-multiclip|sle|0.1.3
autoimport|ste|1.5.3
addDocComments|ste|0.0.8
ayu|tea|0.11.0
vscode-react-native|vsm|0.5.7
vscode-import-cost|wix|2.5.1

(9 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by idchlife** [comment] 2017-12-22 19:14
Guys, I beg to notice this issue since it's true. Typescript Language Server dies with these errors:

```javascript

index.js:5 Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
onError @ index.js:5
events.js:163 Uncaught Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4044 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4044
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2744 Extension host terminated unexpectedly.
```

I mean you could not work with TypeScript anymore. And VSCode is kinda main editor for you know... TypeScript stuff. Now TS not working at all. Just right after I updated

**Comment by mjbvz** [comment] 2018-01-02 22:37
A few questions:

- Does this happen if you disable all extensions?
- Does this happen for all projects you open, or just one specifically?
- Have you set a custom `typescript.tsdk` value in your workspace or user settings?

Can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by WoodyWoodsta** [comment] 2018-01-09 15:51
@mjbvz 

I've been having the same issue for a while. To answer your questions:
* Yes
* All projects
* No

I've done the steps you provided and I get the following in my output panel and `tsserver.log`: https://gist.github.com/WoodyWoodsta/284ed36b6b8330084a5ac30819db32c9

**Comment by ceyhunkerti** [comment] 2018-02-14 10:41
I have a similar issue with ubuntu 16.04 
![image](https://user-images.githubusercontent.com/6328046/36200004-6609953c-118c-11e8-8f94-4a030be4108d.png)

![image](https://user-images.githubusercontent.com/6328046/36200051-89e05c0c-118c-11e8-9b56-f213539a3c78.png)

**Comment by tcmal** [comment] 2018-03-12 20:34
> Allocation failed - JavaScript heap out of memory

Were you editing large file(s) at the time?

A workaround could be to increase node's max memory size from the default 1.7GB using the ` --max-old-space-size` argument.

**Comment by ceyhunkerti** [comment] 2018-03-12 21:08
i think this is a extension issue, pl/sql extension may be causing that.
so we can close this issue. Thanks for the help

**Comment by mjbvz** [comment] 2018-06-18 22:15
Closing this issue since we haven't heard back from original poster

If you are still seeing this issue in the latest vscode insiders build with all extensions disabled, please open a new issue with your server logs ([see these instructions for information on collecting the logs](https://github.com/Microsoft/vscode/issues/40725#issuecomment-354894070))

**Closed by mjbvz** 2018-06-18 22:15 UTC
Labels: javascript, needs more info
