### ISSUE TITLE
Let debug breakpoint pined to the original line during debug session

### ISSUE THREAD

**Issue by copdips** [Microsoft/vscode#57948] opened 2018-09-05 09:27 UTC
Hello,

Suppose we add a breakpoint to the line 2, and we insert 3 blank lines before, current version of vscode will keep the breakpoint still at the line 2 which is pointed to a blank line.

**original breakpoint:**
```bash

line1. code1
(breakpoint here) line2. code2
```

**add 3 blank lines before the line 2:**
```bash
line1. code1
(breakpoint still here) line2. 
line3.
line4.
line5. code2
```

**I expect to see**
```bash
line1. code1
line2. 
line3
line4
(breakpoint here) line5. code2
```

Could you please let the breakpoint to pined to the original line code, which means if the original line of code moves, the breakpoint should go with it.

Regards

**Comment by weinand** [comment] 2018-09-05 09:34
I'm not seeing the behaviour you are describing:
![2018-09-05_11-32-26](https://user-images.githubusercontent.com/1898161/45084862-92275380-b0ff-11e8-9ab5-341eb88b06a8.gif)

As you can see in the screencast, the breakpoint moves and the line number updates.

**Comment by copdips** [comment] 2018-09-05 12:46
@weinand 

thx for you rapid reponse, I cannot reproduce the issue neither.
I will raise a new issue next time I encounter it.

**Comment by weinand** [comment] 2018-09-05 13:27
"Live edit" while a debug session is running only works for debug extensions that support this.
The node-debugger of VS Code does not.
So node.js does not see the edited source which means it hits breakpoints in the original location (even though the breakpoint in the editor shows up in the new location). VS Code shows breakpoint with a grey ring if the breakpoint location does not match what node.js sees.

**Comment by weinand** [comment] 2018-09-05 13:29
duplicate of #6930

**Closed by weinand** 2018-09-05 13:29 UTC
Labels: debug, needs more info
