### ISSUE TITLE
PHP Brackets are red

### ISSUE THREAD

**Issue by EdgarAlexPoe** [microsoft/vscode#176310] opened 2023-03-06 22:45 UTC
Type: <b>Bug</b>

Hello,
I just updated to VSC 1.76.0 and now my opening and closing PHP brackets are red, just as if there are no closing brackets. My php is not broken, and my local environment functions fine. 
I usually rely on the colors of my characters, to tell me if there is an error, so this is a pretty big deal for me. Also, when I highlight an opening bracket, it does not highlight its relative closing bracket. something is broken with that update. Thank you.

A

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|24.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id ee40ecba-3463-4fa5-91b4-7657061c1ba0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
apacheconf-snippets|eim|1.3.0
auto-close-tag|for|0.5.14
vscode-pull-request-github|Git|0.60.0
pro-deployer|hem|1.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsccsb:30677849
pythonb192:30669360
funwalk2:30676043

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-06 23:04
Is this #175797? Are you able to repro in the latest Insiders?

**Comment by EdgarAlexPoe** [comment] 2023-03-07 15:05
Seems this is happening when you close your `<?php> `tags. When the tags are left open, the colorization is correct. This is a new bug from the update.

**Closed php tags**
![image](https://user-images.githubusercontent.com/61436524/223461479-9d8d833f-7f81-417c-97df-d92b0cc0fb7c.png)

**Open php tags**
![image](https://user-images.githubusercontent.com/61436524/223461781-60e43494-9d4b-43b6-a820-caef4e994b33.png)

**Comment by rzhao271** [comment] 2023-03-07 16:57
Duplicate of #175797

**Closed by rzhao271** 2023-03-07 16:57 UTC
Labels: info-needed
