### ISSUE TITLE
Use region and endregion can not be folded

### ISSUE THREAD

**Issue by CrazyNiutou** [Microsoft/vscode#34561] opened 2017-09-18 07:15 UTC
Use region and endregion can not be folded

**Comment by CrazyNiutou** [comment] 2017-09-18 07:17
Has this function already?

**Comment by yume-chan** [comment] 2017-09-18 07:46
Duplicate of #12146

**Comment by CrazyNiutou** [comment] 2017-09-18 07:48
Okay, thanks friends

**Comment by aeschli** [comment] 2017-09-21 11:48
duplicate of #12146

**Closed by aeschli** 2017-09-21 11:48 UTC
Labels: editor, editor-folding
