### ISSUE TITLE
Only one line of stdout is displayed when running a task

### ISSUE THREAD

**Issue by schperplata** [microsoft/vscode#82440] opened 2019-10-12 18:36 UTC
Issue Type: <b>Bug</b>

**Issue:** VS Code task that run `.bat` file shows only first line of script stdout in terminal.  

___
I have a `.bat` file with following content:
```
@echo off
echo Generating GUI objects
pyuic5 ui/gui.ui -o gui.py
pyuic5 ui/serial_setup_dialog.ui -o serial_setup_dialog.py

echo Generating resources
pyrcc5 images/icons.qrc -o icons_rc.py

echo Done.
```
Running this file produces folowing output:
```
Generating GUI objects
Generating resources
Done.
```
___
Then I have a VS Code task, that runs this `.bat` file:
```
"label": "ui -> py",
"type": "process",
"command": "generatePyFromUi.bat"
```

On task execution, this is what I get in terminal output (PowerShell or cmd.exe):
```
> Executing task in folder SerialTool: D:\Stromarija\GIT\SerialTool\src\gui\generatePyFromUi.bat  <

Generating GUI objects

<bunch of empty lines - no hidden text>


Terminal will be reused by tasks, press any key to close it.
```

Where are `Generating resources` and `Done.` lines?

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (2.64GB free)|
|Process Argv|D:\Stromarija\GIT\SerialTool\serialTool.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cortex-debug|mar|0.3.1
python|ms-|2019.10.41019
cpptools|ms-|0.25.1

</details>

**Comment by alexr00** [comment] 2019-10-16 09:40
winpty strikes again. Duplicate of https://github.com/microsoft/vscode/issues/57803

**Closed** 2019-10-16 09:40 UTC
Labels: *duplicate, new release
