### ISSUE TITLE
Alt+click selection does not work in terminal

### ISSUE THREAD

**Issue by probablykasper** [microsoft/vscode#95340] opened 2020-04-15 14:16 UTC
Some CLI tools respond to click events, which makes text unselectable. You'd hold alt to select text in these cases, but it does not work in VSCode.

- VSCode Version: 1.44.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Install [lazydocker](https://github.com/jesseduffield/lazydocker) (or another similar tool)
2. Run `lazydocker` in VSCode
3. Try to select any text in the terminal while holding alt

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2020-11-05 17:15
I cannot reproduce with the above steps so I'm closing it off to reduce our issue count. If you can still reproduce, please let me know, a [gif](https://gifcap.dev/) would be really handy too.

**Closed by meganrogge** 2020-11-05 17:15 UTC
Labels: *not-reproducible, bug, integrated-terminal, mac

**Comment by probablykasper** [comment] 2020-11-05 18:24
@meganrogge Sure. Here I'm trying to select text:
![screenrec](https://user-images.githubusercontent.com/11315492/98280822-3f29df00-1f9c-11eb-8d8c-9d8c7254262f.gif)

**Comment by Tyriar** [comment] 2020-11-05 18:29
@probablykasper try out this setting:

```
"terminal.integrated.macOptionClickForcesSelection": true
```

This was added for just this reason.

**Comment by probablykasper** [comment] 2020-11-05 18:52
@Tyriar Ah, that was the problem, my bad. Thanks!

**Comment by Tyriar** [comment] 2020-11-05 20:54
@probablykasper good to hear 👍
