### ISSUE TITLE
File isn't highlighted on right-click

### ISSUE THREAD

**Issue by Neorth** [microsoft/vscode#83643] opened 2019-10-30 09:31 UTC
When right-clicking a file in a file list I expect the file to be highlighted. Right now the file gets highlighted after the context menu is closed. It can be confusing when right-clicking a file next to a opened file that is highlighted. See these screenshots:
![image](https://user-images.githubusercontent.com/8577089/67844671-75698e80-fafe-11e9-83f5-ea882e2abfb5.png)
![image](https://user-images.githubusercontent.com/8577089/67845659-258bc700-fb00-11e9-91cb-8f0d3ab2a47c.png)

- VSCode Version: 1.39.2 and 1.40.0-insider
- OS Version: Win 10

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment] 2019-10-30 18:33
Possible duplicate of #70966

**Closed** 2019-10-31 08:08 UTC
Labels: *duplicate
