### ISSUE TITLE
VSCode still cannot detect Git :(

### ISSUE THREAD

**Issue by mrtianjin829** [microsoft/vscode#144976] opened 2022-03-13 10:28 UTC
Issue Type: <b>Bug</b>

VSCode cannot detect git. It says No source control providers registered. How to fix? I have reloaded my window and restarted my machine. Still not working.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.58GB free)|
|Process Argv|D:\\etc\\tjshell --crash-reporter-id b938978e-179e-48ee-b1d8-c6c5b59cdaba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
vscode-deno|den|3.10.1
javascript-ejs-support|Dig|1.3.1
vscode-npm-script|eg2|0.3.24
todo-tree|Gru|0.0.215
rest-client|hum|0.24.6
discord-vscode|icr|5.8.0
cpptools|ms-|1.8.4
live-server|ms-|0.2.12
powershell|ms-|2021.12.0
lua|sum|2.6.7
vscode-icons|vsc|11.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
vscgsvidc:30447482
pynewfile477:30450038

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-03-13 13:36
What version of Git have you installed on your Windows workstation? See https://code.visualstudio.com/Docs/editor/versioncontrol#_git-support

**Comment by lszomoru** [comment] 2022-03-14 07:20
@mrtianjin829, I have also noticed that you have the `vscode-icons` extension installed. Recently we have found that this extension exposes a bug, in the extension activation code. This bug has been fixed with the latest Insiders release. Could you please install that and see if that resolves the problem? Also, could you please try starting code with the `--disable-extensions` flag and see if that resolves the problem?

**Comment by mrtianjin829** [comment] 2022-03-15 11:09
Okay

**Comment by mrtianjin829** [comment] 2022-03-15 11:10
git version 2.35.1.windows.2

**Comment by lszomoru** [comment] 2022-03-15 11:22
> Recently we have found that this extension exposes a bug, in the extension activation code. This bug has been fixed with the latest Insiders release. Could you please install that and see if that resolves the problem? Also, could you please try starting code with the --disable-extensions flag and see if that resolves the problem?


Could you please try the following and let me know if that resolves the issue?

**Comment by mrtianjin829** [comment] 2022-03-15 11:32
You are talking about VSCode's insiders release?

**Comment by lszomoru** [comment] 2022-03-30 13:15
@mrtianjin829, that is correct. Sorry for not getting back to you on this until now.

**Comment by mrtianjin829** [comment] 2022-03-30 16:45
I used VSCode Insiders. The bug was fixed. Thanks.

**Comment by lszomoru** [comment] 2022-03-30 19:46
@mrtianjin829, thank is great news. Thanks for the update!

**Comment by lszomoru** [comment] 2022-03-30 19:47
Closing as duplicate of #144518.

**Closed by lszomoru** 2022-03-30 19:47 UTC
Labels: git
