### ISSUE TITLE
Debug console stops automatically scrolling sometimes when contents wrap

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#117674] opened 2021-02-25 12:08 UTC
Splitting from https://github.com/microsoft/vscode/issues/115945.

- Clone mock-debug
- Run the tests
- Resize the window so the debug console has lots of wrapping
- Run the tests again

After a few tests run, the Debug Console will stop scrolling down automatically and just remain part-way through.

<img width="838" alt="Screenshot 2021-02-25 at 12 08 28" src="https://user-images.githubusercontent.com/1078012/109151517-2ff4ba00-7762-11eb-98a0-cd45f2fda4ca.png">

**Comment by isidorn** [comment] 2021-03-04 10:45
@DanTup thanks for steps I can reproduce this.

@joaomoreno here I am hitting the limitation of what the tree gives me. Currently I use the following heurisitc to figure out if the last element is visible in the tree
```typescript
const lastElementVisible = (this.tree.scrollTop + this.tree.renderHeight) >= this.tree.scrollHeight;
```

However that does not give the correct result when elements are wrapped and take additional lines.
So I could either somehow update that check, or I could use the `tree.lastElementVisible`. I would just care if there are elements after the last visible element, but I could not figure out any tree api to get next neighbour of the last visible element. Might I be missing something? Let me know what you think, thanks.

**Comment by joaomoreno** [comment] 2021-03-08 15:21
> However that does not give the correct result when elements are wrapped and take additional lines.

@isidorn What values does it return in that case?

**Comment by isidorn** [comment] 2021-03-08 15:30
In this step we are good:
```
scroll top: 89
render height: 151
scroll height: 240
```
In this step we are no longer good:
```
scroll top: 121
render height: 151
scroll height: 280
```

**Comment by isidorn** [comment] 2021-03-11 12:29
@joaomoreno and me investigated into this and it seems to be related to how async code is handled on the list side.
Thus assigning this to on-deck and once @joaomoreno finds time he can look into a fix or recommend a workaround for me on the Debug Console side.

**Comment by awa5114** [comment] 2021-05-25 04:47
Any progress on this issue?  Would be great to not have to manually scroll down during the debug session.

**Comment by oliversalzburg** [comment] 2021-05-25 08:58
@awa5114 Not to my knowledge. I've been told a small trick though 😄 In the debug console, hit Shift+Tab to move focus from the input box to the output list. Now you can just hit End once to move to the end of the list.

**Comment by awa5114** [comment] 2021-06-11 06:50
@oliversalzburg thanks for the tip, but going through all that hassle every single time I type in a command in the debug console or try to inspect a variable by printing out its type is simply not worth it. 

@isidorn are there any viable workarounds to this? I believe it makes the debug console pretty much impossible to use for the average python developer.

**Comment by isidorn** [comment] 2021-06-11 12:47
Workaround is 
```
"debug.console.wordWrap": false
```

As for progress, we plan to fix this however not sure when. @joaomoreno did an initial investigation and it proved more complex than anticipated.

**Comment by awa5114** [comment] 2021-06-11 16:01
@isidorn Thanks for your valuable feedback. This works for me. I should probably add that `debug.console.wordWrap` should be added to the settings.json and not the launch.json.

Just out of curiosity, doesn't that basically solve the problem? What else is there to fix?

**Comment by rvanlaar** [comment] 2021-06-30 14:27
@awa5114 Setting wordWrap to false will not display all output.
![Screenshot from 2021-06-30 16-26-29](https://user-images.githubusercontent.com/710771/123978341-14bfe280-d9c0-11eb-93a0-9894043af625.png)

**Comment by binh-vu** [comment] 2021-11-03 20:14
Setting `wordWrap` to false also hide the last line (image). Please fix this! 

![image](https://user-images.githubusercontent.com/4346739/140185587-4784d252-70ba-4cdb-82b1-db26f0342ab3.png)

**Comment by andynvt** [comment] 2022-01-20 02:07
any update?

**Comment by deemru** [comment] 2022-02-14 21:56
That (https://github.com/microsoft/vscode/issues/131999) was a super annoying bug, but today i found this thread and turned off `debug.console.wordWrap` (turned on by default) and it scrolls down automatically!

**Comment by DaichiShirakawa** [comment] 2022-02-24 05:38
Please god if you exists, please re-create the universe except this terrible bug.
The bug makes us sad every minutes in Flutter-based development...

**Comment by easeccy** [comment] 2022-03-17 10:05
I want to have auto-scroll with word wrap functionality. This is very annoying bug.

**Comment by roblourens** [comment] 2022-03-18 18:57
Maybe this got worse recently, but I am seeing it happen with no wrapping involved, just the simplest single-line output. I think I have a fix. Basically

1. We add an item, call updateChildren
2. The list renders the item off screen. getHeight returns an estimate that is off by 1px
3. The dynamic height is not probed because it is offscreen
4. Code in repl.ts tries to scroll to the bottom, but using a scrollHeight measurement that is off by 1px
5. The item is rendered, dynamic height is probed, size is fixed, but that means the list is no longer scrolled all the way down, so repl.ts stops autoscrolling

I have an easy workaround to watch for content height change events from the list and update the scroll at this point. I think only Debug Console needs this feature - if it's ever needed anywhere else, we should implement it inside the List.

**Comment by easeccy** [comment] 2022-04-05 09:16
The issue still occurs. I have to manually scroll down to see the newest logs.

**Comment by hillarysanders** [comment] 2022-04-05 19:47
Yep, me too. I've turned off wordWrap and smartScrollin my setttings.json and I still have to scroll down in the interactive console whenever I run code :(.
```
    "debug.console.wordWrap": false,
    "output.smartScroll.enabled": false,
    ```

**Comment by roblourens** [comment] 2022-04-06 16:14
@easeccy can you share a code snippet that reproduces the issue? I don't see an issue.

@hillarysanders it sounds like you might be using the interactive window which is not what this issue is about. Please make sure you're updated to the latest version and open a new issue

**Comment by easeccy** [comment] 2022-04-07 20:01
I'm debugging Flutter apps with `--verbose` option which sometimes outputs a lot of lines of logs at once. I suspect that breaks it. When the log density is normal, it works.

**Comment by davidmartos96** [comment] 2022-04-07 20:57
How can the fix be tested? Do we need to build from source or is it in the Insiders version?

**Comment by roblourens** [comment] 2022-04-07 23:55
It went out in the latest stable update. If you're still seeing the issue I can reopen it and investigate a little more

**Comment by roblourens** [comment] 2022-04-13 16:23
I set up a flutter app and tried debugging it in verbose mode, but it doesn't do anything unusual and I don't see an issue. Also tried some other cases with different types of log messages printed very quickly.

@easeccy are you able to share the app? Or if not, a screen recording of the console, or screenshot of the point where it stops scrolling might help

**Comment by vanowm** [comment] 2022-04-17 00:45
So, basically wrapped lines considered as single line, therefore it miscalculating how many lines scroll by?

**Comment by roblourens** [comment] 2022-04-18 17:37
I'm not seeing an issue with wrapped lines anymore

**Comment by DanTup** [comment] 2022-04-20 10:47
I'm not sure this is particularly helpful information (besides maybe helping confirm there's still an issue), but I was just able to reproduce this with a Flutter project (on current stable), but have been unable to repro again while recording. It happened while Flutter was doing `pub` checks (it prints a lot of very verbose output with all the HTTP requests to the Pub API).

I've tried clearing my Pub cache and modifying my pubspec (with `"dart.runPubGetOnPubspecChanges": false` so Flutter would re-check Pub packages when the debug session starts), but have been unable to trigger it again (nor could I repro with the original steps using mock-debug above).

**Comment by DanTup** [comment] 2022-04-20 10:48
Oh, perhaps noteworthy, when it did happen (sorry I didn't take screenshot, I thought it would be easy to repro!), the last few lines printed were a _very_ long line (a large JSON payload) followed by 1 or 2 short (unwrapped) lines.

**Comment by easeccy** [comment] 2022-06-09 11:12
Issue is still happening. I can't find a good pattern to suspect and reproduce it. All I remember is I had disabled the content wrap setting to give it a shot on my wide screen. Reverting it later did not help. I was doing Flutter development on VSCode for 3 years, and from that day, I'm getting this very annoying bug.

**Comment by roblourens** [comment] 2022-09-10 21:11
I have a fix which I think only affects the case when wordwrap is disabled. From this thread, I'm not sure whether anyone was still seeing an issue with wordwrap enabled. It got a lot easier to repro after my fix for https://github.com/microsoft/vscode/pull/160622 fixed an issue with sizing.

**Comment by roblourens** [comment] 2022-09-10 21:11
Here's the code I was using to repro the issue:

```js
setInterval(() => {
    console.log(`abc
def
def
def
def
def
def
def
def
def
def
def
def
def
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
ghi
jkl
jkl
jkl
jkl
jkl
jkl
jkllksdj flksdj fsdklfj lsdkjf lsdkjf lsdkj flsdkj flsdkj flsdkj flksdj flskdjfjkllksdj flksdj fsdklfj lsdkjf lsdkjf lsdkj flsdkj flsdkj flsdkj flksdj flskdjfjkllksdj flksdj fsdklfj lsdkjf lsdkjf lsdkj flsdkj flsdkj flsdkj flksdj flskdjfjkllksdj flksdj fsdklfj lsdkjf lsdkjf lsdkj flsdkj flsdkj flsdkj flksdj flskdjfjkllksdj flksdj fsdklfj lsdkjf lsdkjf lsdkj flsdkj flsdkj flsdkj flksdj flskdjfjkllksdj flksdj fsdklfj lsdkjf lsdkjf lsdkj flsdkj flsdkj flsdkj flksdj flskdjf
jkl
jkl
jkl
jkl
jkl
jkl
jkl
${Math.random()}`)
}, 600);
```

and `"debug.console.wordWrap": false`

**Comment by DanTup** [comment] 2022-09-12 10:29
I can't repro now, but I saw this again a few days ago, but I do not have wordWrap set, it's on the default (`true`).

If I see it again, is there any useful info I can get from it (other than a shareable repro ofc, assuming I can't make one).

**Closed** 2022-09-12 12:15 UTC
Labels: bug, debug
