### ISSUE TITLE
VS Code Ignore (hide) Warnings in Problems Tab

### ISSUE THREAD

**Issue by Domvel** [Microsoft/vscode#59038] opened 2018-09-20 11:30 UTC
I wondering if there is already a feature to hide all warnings from problems tab.
If not here's the feature request. In my case I use unity with a few 3rd party assets.
There are "many" warnings about deprecated usage of Unity features. Whatever ...
It would be great if I could hide these warnings on the problems tab.
I want "Problems 0" but on the bottom of VS Code the indicator errors and warnings is ok.
There I can see the amount of warnings. Only the problems tab should be clean.
So we need filter options (buttons, menu, etc) to simple hide all warnings and / or errors.

![problems](https://user-images.githubusercontent.com/35452565/45815845-300f4680-bcda-11e8-9983-79f94f7a0276.jpg)

I don't want to touch the 3rd party source code. It's dangerous and a lot of work. So just hide all warnings.

Current version: 1.27.2

Sorry if this is a duplicate. I overlooked it. (#50449, #41114)

**Comment by sandy081** [comment] 2018-09-21 15:45
Duplicate of #47354

**Closed** 2018-09-21 15:45 UTC
Labels: *duplicate, error-list
