### ISSUE TITLE
Debug: sometimes breakpoints don't respond

### ISSUE THREAD

**Issue by Eli-Goldberg** [Microsoft/vscode#38218] opened 2017-11-13 11:45 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (0fbdfff167653b233231259ceb3109f0931887ef, 2017-11-09T06:19:28.857Z)
- OS Version: Linux x64 4.10.0-38-generic (Ubuntu 16)
- Node Version: Node 9.1.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-mocha|Com|0.1.1
Angular-BeastCode|Mik|5.0.15
yaml|ada|0.0.9
better-toml|bun|0.3.1
regex|chr|0.1.0
jsrefactor|cms|1.5.3
vscode-eslint|dba|1.4.3
gitlens|eam|6.0.0
node-version|fiv|0.0.1
flow-for-vscode|flo|0.7.2
vscode-flow-ide|gca|1.2.0
vscode-auto-open-markdown-preview|hnw|0.0.4
javascript-unit-test-snippet|iZD|1.0.0
Go|luk|0.6.67
vs-code-quick-require|mil|0.2.0
python|ms-|0.8.0
chai-snippets|nwh|0.1.0
vscode-versionlens|pfl|0.19.1
require-complete|sen|0.1.0
vscode-sql-beautify|sen|0.0.4
es6-mocha-snippets|spo|0.0.5

---

Steps to Reproduce:
Very hard to reproduce.. 
1. During debug add multiple breakpoints
2. Some of the red dots in the editor will no longer be synchronized with the actual breakpoint tracking in the side panel

![ezgif-3-8a5f20cd6f](https://user-images.githubusercontent.com/19211868/32724024-530c540e-c878-11e7-841c-693f1d81ea6f.gif)

Reproduces with or without extensions: No

**Comment by weinand** [comment] 2017-11-13 12:24
Duplicate of #37880. Please try Insiders.

**Closed by weinand** 2017-11-13 12:24 UTC
Labels: debug, insiders
