### ISSUE TITLE
Date/Time/DateTime support in snippets?

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#42207] opened 2018-01-26 16:01 UTC
Could be added date/time/datetime variable to  snippets?

I would like to create "comment" snippet with actual date/time/datime  and its very annoying to do  manually because date/time/datime variable is missing.

**Comment by usernamehw** [comment] 2018-01-26 16:25
Duplicate of https://github.com/Microsoft/vscode/issues/41631

**Closed** 2018-01-26 18:27 UTC
Labels: *duplicate
