### ISSUE TITLE
`vscode.extensions.all` doesn't include disabled inclusions

### ISSUE THREAD

**Issue by FancyBanana** [Microsoft/vscode#69992] opened 2019-03-07 21:48 UTC
This is an issue for [code-settings-sync][1] extension. It uses `vscode.extensions.all` to get list of all extensions and it is missing disabled extensions. It is referenced [in this issue][2].

[1]: https://github.com/shanalikhan/code-settings-sync
[2]: https://github.com/shanalikhan/code-settings-sync/issues/143

**Comment by sandy081** [comment] 2019-03-11 08:33
Duplicate of #14444

**Closed** 2019-03-11 08:33 UTC
Labels: *duplicate, extensions
