### ISSUE TITLE
ES6 modules broken in 0.10.8 with Salsa

### ISSUE THREAD

**Issue by prashaantt** [Microsoft/vscode#2848] opened 2016-02-09 15:34 UTC
I'm loving the JSX support in the latest Code update, courtesy Salsa — thanks a ton for that! The thing is, I'm not ready to go all out on TS yet. Is it possible to just get the JSX auto-complete/IntelliSense support without running into issues like these:

![image](https://cloud.githubusercontent.com/assets/390540/12920869/7e7322ba-cf70-11e5-9768-cb8768e1d13f.png)

![image](https://cloud.githubusercontent.com/assets/390540/12920907/a92d7276-cf70-11e5-85b9-c1e8328d37c2.png)

**Comment by prashaantt** [comment] 2016-02-09 16:01
I have been experimenting a bit and dropping a `jsconfig.json` in my project seems to do the trick and no longer shows these errors. Is that the way to achieve this?

**Comment by tmkbry** [comment] 2016-02-09 16:20
@prashaantt I had the same problem, the jsconfig.json fixed it for me, thanks.

To the second problem, I have no problem to reproduce it without the error, maybe it's because I have this in my jsconfig.json:
`{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules"
    ]
}`

**Comment by prashaantt** [comment] 2016-02-09 16:29
@tmkbry I have a similar config as yours, plus the `"module": "commonjs"` inside `compilerOptions`, but I can't get rid of the squigglies on the export.

**Comment by prashaantt** [comment] 2016-02-09 18:35
Ok, so this works:

```js
export default function () { }
```

but this doesn't:

```js
export default () => { }
```

Awesome!

**Comment by prashaantt** [comment] 2016-02-09 18:37
(Perhaps I should leave this issue open, just in case there's anything the Code team can do to make this alt syntax work too.)

**Comment by prashaantt** [comment] 2016-02-09 19:26
Another instance that I can't work around:

```js
import { connect } from 'react-redux';

const mapStateToProps = (state) => { ... };

class App extends React.Component { ... }

export default connect(mapStateToProps)(App); // here be the relentless squiggly
```

The `export` throws the same error as before: `'export=' can only be used in a .ts file`.

**Comment by egamma** [comment] 2016-02-10 16:49
Extracted a separate issue for 
>I think ideally the module should be  es6  but  jsconfig.json  reports an error for that, which otherwise is acceptable inside a  tsconfig.json .

Moving to Salsa

**Comment by egamma** [comment] 2016-02-10 16:50
This issue was moved to Microsoft/TypeScript#7006

**Closed by egamma** 2016-02-10 16:50 UTC

**Comment by prashaantt** [comment] 2016-02-10 18:07
@egamma Sorry you needed to do this spring cleaning, I'll try discerning between issues that belong to TypeScript. I hope this is all automated for you to copy over to the right repo :)

You and your team are doing an amazing job with Code :+1:

**Comment by egamma** [comment] 2016-02-10 21:22
@prashaantt no need to sorry. We need this feedback and the issue mover (https://github-issue-mover.appspot.com/) helps a lot. Also glad you like Code.
