### ISSUE TITLE
Remote SSH broken in latest Insider release

### ISSUE THREAD

**Issue by 343max** [microsoft/vscode#143089] opened 2022-02-15 09:31 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.65.0-insider (Universal)
Commit: 50089c3f92c17584a4aca179f51f220b56c22020
Date: 2022-02-14T05:17:15.582Z (1 day ago)
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Darwin arm64 21.4.0
```
- OS Version: macOS Monterey 12.3 Beta (21E5206e)

Steps to Reproduce:

- connect to linux via ssh (Ubuntu in my case) Linux 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- work fine on a stable release, so I'm pretty confident it's not a change in my setup

error:
```
[10:25:00.925] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430359)
	at u (/Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:424682)
	at Object.t.handleInstallOutput (/Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:429101)
	at Object.e [as tryInstallWithLocalServer] (/Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:469079)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:486771
	at async Object.t.withShowDetailsEvent (/Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:490561)
	at async /Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467603
	at async E (/Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (/Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467218)
	at async Object.t.resolve (/Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:488171)
	at async /Users/max/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:564197
[10:25:00.927] Local server exit: 15
[10:25:00.930] ------
```

**Comment by bogurd** [comment] 2022-02-15 12:46
I have the exact same issue. A clean install of the server does not help.

```
[13:46:00.094] Terminating local server
[13:46:00.103] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430359)
	at u (/home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:424682)
	at Object.t.handleInstallOutput (/home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:429101)
	at Object.e [as tryInstallWithLocalServer] (/home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:469079)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:486771
	at async Object.t.withShowDetailsEvent (/home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:490561)
	at async /home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467603
	at async E (/home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (/home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467218)
	at async Object.t.resolve (/home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:488171)
	at async /home/bogurd/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:564197
[13:46:00.118] Local server exit: 15
```

**Comment by dragz** [comment] 2022-02-15 14:18
Same here (i submitted issue 143105 before I saw this, sorry).

As described in my issue the remote server seems to ask for license agreement acceptance on stdin.

**Comment by gjsjohnmurray** [comment] 2022-02-15 15:47
Maybe a duplicate of https://github.com/microsoft/vscode/issues/142755

**Comment by bogurd** [comment] 2022-02-15 16:09
@gjsjohnmurray Thanks for this. Indeed, when switching to the pre-release of Remote SSH (as suggested by the issues you reference), the issue goes away.

**Comment by alexdima** [comment] 2022-02-15 16:26
:+1: Let's track in https://github.com/microsoft/vscode-remote-release/issues/6328

**Closed by alexdima** 2022-02-15 16:26 UTC
Labels: triage-needed

**Comment by 343max** [comment] 2022-02-17 10:45
Yes, switching to pre-release version of remote SSH fixed it for me as well. Closing.
