### ISSUE TITLE
Debugger stops at random paths, without being able to see the stack

### ISSUE THREAD

**Issue by Eli-Goldberg** [Microsoft/vscode#17301] opened 2016-12-15 13:03 UTC
- VSCode Version: 1.8.0
- OS Version: Ubuntu 16.04

See image -
when hovering at top of stack trace, tooltip shows debugger is stopped at weird path "1003/619".
I'm running in context of co with support of generator promises, might have to do with the problem.
Didn't happen before version 1.8.0

Steps to Reproduce:
1. Make sure debugger is node2
2. step into a generator function
3. debugger should stop at some weird path

![image](https://cloud.githubusercontent.com/assets/19211868/21224942/3488ada4-c2d7-11e6-82ff-f0f57154f463.png)

**Comment by roblourens** [comment] 2016-12-15 22:44
Can you give a code sample? And what shows in the editor when you're here. Are you using a promise library?

**Comment by isidorn** [comment] 2017-01-03 09:11
@roblourens you might want to close this as a duplicate of #16913

**Closed** 2017-01-03 11:09 UTC
