### ISSUE TITLE
Add option to separe defined members from default (javascript) ones in Intellisense popup

### ISSUE THREAD

**Issue by distante** [Microsoft/vscode#51468] opened 2018-06-08 16:38 UTC
Let me explain my feature request with images.

I have this very simple class:
![image](https://user-images.githubusercontent.com/5490201/41169667-f2d4ae18-6b49-11e8-86a9-99158fe78f46.png)

When I use it the Intellisense Popup is:
![image](https://user-images.githubusercontent.com/5490201/41169636-e29abd76-6b49-11e8-823d-39639f7cfde1.png)

Even thought the cursor place it self in the only declared member, it is not ease to difference at first glance _what is what_ and as it grows it will be even harder.

![image](https://user-images.githubusercontent.com/5490201/41169970-e23bd0a8-6b4a-11e8-8ea9-e1dc56593e4a.png)

Would be nice an option to list first the class members like:

```
-----own members------
a
b
c
------default---------
apply
caller
.
.
```

**Comment by mjbvz** [comment] 2018-07-16 19:48
Duplicate of https://github.com/Microsoft/vscode/issues/50755 /  https://github.com/Microsoft/vscode/issues/50291

**Closed by mjbvz** 2018-07-16 19:48 UTC
Labels: feature-request, javascript
