### ISSUE TITLE
Can't `F2` rename JSX html element after hotfix 1.78.2

### ISSUE THREAD

**Issue by goodideagiver** [microsoft/vscode#184161] opened 2023-06-02 13:13 UTC
Type: <b>Bug</b>

Press F2 on JSX tag that is normal HTML element (tested on .tsx file)

After recent hotfixes it's not possible to rename HTML tags in jsx using rename refactor command and F2 shortcut. The rename attempt results in an error: `you cannot rename elements that are defined in node_modules folder`.

Typescript version in the project is 5.1.3

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500T CPU @ 2.30GHz (12 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (1.09GB free)|
|Process Argv|--crash-reporter-id 28e4f0e9-e9b4-4839-b3b1-de85179cc58c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
project-manager|ale|12.7.0
vim-cheatsheet|And|0.0.1
astro-vscode|ast|1.0.8
openmatchingfiles|bca|0.5.4
beardedicons|Bea|1.12.0
vscode-autohotkey-neko-help|cat|0.0.42
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
bracket-select|chu|2.0.2
vscode-css-modules|cli|0.5.1
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
arrow-function-snippets|dei|3.5.0
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.6.0
prettier-vscode|esb|9.13.0
copilot|Git|1.88.132
vscode-pull-request-github|Git|0.64.0
raythis|Goo|1.1.1
vscode-fast-folder-structure|Huu|3.9.2
easy-snippet|inu|0.6.3
monkey-patch|ioc|0.1.23
vscode-env|Iro|0.1.0
ejs-beautify|j69|1.0.6
vscode-icon-theme|jtl|1.6.6
vscode-colorize|kam|0.11.1
vscode-autohotkey-plus-plus|mar|3.3.0
visual-update-ts|Mar|0.0.1
ts-error-translator|mat|0.8.0
vscode-github-actions|me-|3.0.1
template-string-converter|meg|0.6.1
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
playwright|ms-|1.0.11
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.0
test-adapter-converter|ms-|0.1.7
vscode-quick-open-create|noc|0.6.0
vscode-create-test-file|pau|0.0.1
paul-typescript-toolkit|pau|0.0.6
material-product-icons|PKi|1.5.0
vscode-react-refactor|pla|1.1.3
vscode-yaml|red|1.13.0
vscode-sort-json|ric|1.20.0
vscode-git-commit|rio|3.1.0
swdc-vscode|sof|2.7.0
code-spell-checker|str|2.20.4
code-spell-checker-polish|str|2.0.3
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.2.4
control-snippets|svi|1.9.1
icons|tal|3.6.3
branch-warnings|tel|1.0.10
vscode-mdx|uni|1.3.0
errorlens|use|3.11.0
highlight-matching-tag|vin|0.11.0
learn-vim|vin|0.0.28
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-css-variables|vun|2.6.3
vscode-autohotkey-debug|zer|1.11.0
vitest-explorer|Zix|0.2.41

(13 theme extensions excluded)

</details>

**Comment by mateuszmiko** [comment] 2023-06-02 13:21
Unfortunately, I have the same problem :(

**Comment by mjbvz** [comment] 2023-06-02 17:01
Works fine for me

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Also did you disable the `"javascript.preferences.renameMatchingJsxTags"` setting (it is on by default)

**Comment by goodideagiver** [comment] 2023-06-02 18:47
# First 1.78.2

@mjbvz Extensions enabled and settings disabled

![obraz](https://github.com/microsoft/vscode/assets/55458485/707cc98f-df32-48ba-ba88-ead769694693)

Extensions disabled

![obraz](https://github.com/microsoft/vscode/assets/55458485/078bea88-42f3-4ac5-9dbf-3f17c5ac2647)

Extensions disabled, settings enabled

![obraz](https://github.com/microsoft/vscode/assets/55458485/cea82687-0f52-4aa2-96de-a49c0484c989)

# Latest insiders build and no extensions 🎉

![obraz](https://github.com/microsoft/vscode/assets/55458485/86d87639-b183-4381-9f0d-a377347d4f34)

![obraz](https://github.com/microsoft/vscode/assets/55458485/cc2ff39f-ace3-4c20-870d-93e848326b7a)

**Comment by mjbvz** [comment] 2023-06-05 18:46
Thanks for checking. Closing since it sounds like it is working in insiders (which will become the stable version shortly). Either it was already fixed or there was a configuration issue with your current stable version

**Closed by mjbvz** 2023-06-05 18:46 UTC
Labels: info-needed
