### ISSUE TITLE
Cannot read property 'length' of undefined Error After update (v1_11)

### ISSUE THREAD

**Issue by jihin** [Microsoft/vscode#24174] opened 2017-04-07 05:56 UTC
I have installed your new version of VS Code. After installation, When I formatting the code I am getting the `error Cannot read property 'length' of undefined`

- VSCode v1_11:
- Ubuntu 16.04 LTS
![error](https://cloud.githubusercontent.com/assets/9817635/24787221/cb4d564e-1b84-11e7-8245-f65c4b8ee270.png)

**Comment by chrmarti** [comment] 2017-04-07 06:10
What language are you formatting? Which extensions to you have installed (`code --list-extensions`)?

**Comment by jihin** [comment] 2017-04-07 06:15
TypeScript (.ts)

**Comment by jrieken** [comment] 2017-04-10 09:26
@jihin I cannot reproduce. What exact version do you mean by `v1_11`? Is this insiders 1_11 or the released version 1.11.1?

**Comment by jihin** [comment] 2017-04-10 09:43
1_11

**Comment by jrieken** [comment] 2017-04-10 10:03
@jihin Is this insiders 1_11 or stable?

**Comment by jrieken** [comment] 2017-04-11 13:50
@jihin ping

**Comment by jrieken** [comment] 2017-04-13 13:38
Closing because this issue is without actionable information.

**Closed by jrieken** 2017-04-13 13:38 UTC
Labels: needs more info, not-reproducible
