### ISSUE TITLE
 Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#80619] opened 2019-09-10 05:52 UTC
Issue Id: <b>19923829-124a-352e-6644-a954fdecb4be</b><br /><br />*Versions* <br />- 1.38.0-insider (9/3/2019 11:14:03 PM)<br />-  dcc01858d3f75696568eb751238d01b30a1e7d33<br />-  e77b008fb04222192a608906ff603bd72943d779<br />*Stack* <br />TypeError: Cannot read property 'uri' of null<br />[/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#520:177 (_actionCallback)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#L520:177 (_actionCallback))<br />[/vs/base/common/actions.ts#179:15 (run)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/base/common/actions.ts#L179:15 (run))<br />[/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#397:17 (onWorkspaceFoldersChanged)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#L397:17 (onWorkspaceFoldersChanged))<br />[/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#313:76 (call)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#L313:76 (call))<br />[/vs/base/common/event.ts#572:15 (fire)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/base/common/event.ts#L572:15 (fire))<br />[/vs/workbench/services/configuration/browser/configurationService.ts#390:39](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/services/configuration/browser/configurationService.ts#L390:39)<br />

**Comment by roblourens** [comment] 2019-09-16 00:10
Dupe of https://github.com/microsoft/vscode/issues/79172

**Closed by roblourens** 2019-09-16 00:10 UTC
