### ISSUE TITLE
 Unknown injections for grammar <source.ts>

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#21311] opened 2017-02-23 19:16 UTC
Issue Id: <b>0b90598a-4d14-9199-cbb4-3ce7bc5e3d90</b><br /><br />*Versions* <br />- 1.9.1<br />*Stack* <br />Error: Unknown injections for grammar <source.ts><br />    at Registry._loadGrammar (/node_modules/vscode-textmate/release/main.js:2929:30) <no sourcemaps><br />    at Registry.loadGrammarWithEmbeddedLanguages (/node_modules/vscode-textmate/release/main.js:2878:14) <no sourcemaps><br />[/vs/editor/electron-browser/textMate/TMSyntax.ts#L244:25 (loadGrammarWithEmbeddedLanguages)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/electron-browser/textMate/TMSyntax.ts#L244:25 (loadGrammarWithEmbeddedLanguages))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1641:0 (init)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1641:0 (init))<br />[/vs/editor/electron-browser/textMate/TMSyntax.ts#L243:9](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/electron-browser/textMate/TMSyntax.ts#L243:9)<br />[/vs/editor/electron-browser/textMate/TMSyntax.ts#L258:7 (_createGrammar)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/electron-browser/textMate/TMSyntax.ts#L258:7 (_createGrammar))<br />[/vs/editor/electron-browser/textMate/TMSyntax.ts#L147:9 (registerDefinition)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/electron-browser/textMate/TMSyntax.ts#L147:9 (registerDefinition))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L118:26 (call)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/event.ts#L118:26 (call))<br />[/vs/editor/common/services/modeServiceImpl.ts#L239:25 (fire)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/services/modeServiceImpl.ts#L239:25 (fire))<br />

**Comment by aeschli** [comment] 2017-02-27 16:15
duplicate of #21310

**Closed by aeschli** 2017-02-27 16:15 UTC
