### ISSUE TITLE
File explorer is not updated after many file changes occur

### ISSUE THREAD

**Issue by Paviluf** [microsoft/vscode#28432] opened 2017-06-10 19:06 UTC
Hello,

I noticed that sometimes (often ?) the file explorer doesn't get updated (missing files/folder) after creating new files/folders with something like a git pull or using symfony console to generate files.

Refreshing the explorer using the little refresh icon make the files/folders appear.

This is a follow up of this issue https://github.com/Microsoft/vscode/issues/24309

- VSCode Version: 1.21
- OS Version: Ubuntu 17.10 / Fedora 27

Thanks !

**Comment by mattflix** [comment] 2017-06-23 00:55
VS Code used to auto-refresh file system changes.  Now, nothing is auto-refreshed. 

In the file explorer, I have to press the refresh icon to get externally changes folders and files to appear.

Please fix!

**Comment by mattflix** [comment] 2017-06-24 00:51
I ran Code --verbose and, whenever I change files somewhere within the folder (current open in Code), I see lines like this fly by in the verbose output:

```
[5624:0623/174920.757:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[5624:0623/174920.759:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[5624:0623/174920.878:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
```

So, it seems like the VS Code process is away of the file system changes, but nothing ever updates in the VS Code user-interface.

**Comment by dmlemos** [comment] 2017-07-12 13:11
VSCode doesn't handle refresh properly when working on a multi-folder root. I have to manually trigger `Files: Refresh Explorer`

The files were not in git.

**Comment by IllNate** [comment] 2017-07-17 19:53
I would also prefer the explorer to refresh automatically. I can't see any benefit of not.

I imagine that this is not done, because the explorer 'jumps' to the open file when refreshed. But I also don't like this behavior. I don't think the scroll should not change when refreshing. 

Thanks for your great work!

**Comment by Paviluf** [comment] 2017-08-10 05:41
It's an important bug that can lead to error. I hope it can be fixed as soon as possible.

**Comment by devvedNET** [comment] 2017-08-12 09:44
I agree with @Paviluf.  If I `git pull`, I expect my **explorer** within vscode to automatically be updated to reflect the latest changes of my repo. Instead, I don't see those updates reflected until I click the **refresh** icon in vscode.  The additional step of clicking **refresh** shouldn't be required. 🕷


_**This is a standard feature in every other ide.**_

**Comment by Mikeysax** [comment] 2017-10-18 19:29
I've also experienced this after switching branches and pulling latest code. The tree was not updated and it left me confused as to why I couldn't find specific files I knew existed.

VScode 1.17-2
Manjaro Linux, kernel 4.13

**Comment by kieferrm** [comment] 2017-11-01 07:02
@Tyriar shouldn't the new file watcher improve the experience?

**Comment by Tyriar** [comment] 2017-11-01 19:40
@kieferrm there are some issues with the new watcher ([here](https://github.com/Axosoft/nsfw/issues)) and some with the older watcher as well (eg. this issue). I think performance is generally better with the new one, supporting multiple roots was easy and it's now using the same watcher on all platforms (before we hand-wrote/owned the Windows one).

**Comment by boyangwang** [comment] 2018-01-02 03:39
Hi, is this fixed? I'm still seeing this under macOS, 1.19.1

**Comment by mattflix** [comment] 2018-01-02 08:27
@boyangwang, nope not yet fixed under MacOS or Windows.

**Comment by thoqbk** [comment] 2018-01-16 06:40
In MacOS, I press Cmd + b then Cmd + b again refresh.

**Comment by mattflix** [comment] 2018-01-16 07:02
@thoqbk, the issue is not that you cannot refresh the explorer manually, but rather that the explorer doesn't refresh automatically (which it did used to, but that behavior broke somewhere along the way).

**Comment by thoqbk** [comment] 2018-01-16 07:16
@mattflix, yes I know that. I tried to find some shortcut keys to refresh manually but it doesn't work.
Finally, I found Cmd + b, which is my favorite keys, could help.

**Comment by kevmon** [comment] 2018-01-24 06:28
@thoqbk I'm in MacOS and experiencing the same problem, but Cmd + b (twice) doesn't refresh the explorer for me.  Are you aware of a menu option for refreshing?

**Comment by ZiyiFeng-SJSU** [comment] 2018-01-25 07:14
Linux 17.10 x64 is having same problem that file explorer is not updated.

**Comment by SamyBencherif** [comment] 2018-01-28 00:10
High Sierra 10.13.1 (17B1003) having the same problem.

**Comment by bsendras** [comment] 2018-01-28 02:48
Still happening in vsCode v1.19.3 macOs with High Sierra 10.13.3, even having the scm activity panel selected. Please, take care of this issue. It is annoying to have to click on the refresh button and using git integration gets confusing.

**Comment by zackify** [comment] 2018-01-29 15:05
Yep, still happens all the time. CMD + P `> Reload Window` is a daily thing for me.

**Comment by Tyriar** [comment] 2018-01-29 18:53
@zackify a full window reload is overkill, hitting the refresh button on the file explorer should be enough

**Comment by liuliangsir** [comment] 2018-01-31 06:48
Not sure if this is the solution, but as an interim you could try the following config option
```
{
  "key": "ctrl+f5",
  "command": "workbench.action.reloadWindow",
  "when": "editorTextFocus"
}
```

**Comment by Tyriar** [comment] 2018-01-31 17:01
@liuliangsir I posted an answer to the same SO question, I recommend just refreshing the explorer:

```js
{
  "key": "ctrl+f5",
  "command": "workbench.files.action.refreshFilesExplorer"
}
```

**Comment by mattflix** [comment] 2018-01-31 18:51
Good grief, _please_ stop posting instructions about how to manually refresh the File Explorer.  This issue is about the fact that the File Explorer doesn't auto-refresh as it is supposed to (and once did reliably).  Manual refresh should not be necessary.

**Comment by Tyriar** [comment] 2018-01-31 19:06
@mattflix the proper fix for the issue is more involved and will not get attention for some time due to lack of resources. I'm pointing out that reloading the file explorer is a far better workaround that the entire window.

**Comment by barbossa** [comment] 2018-02-11 20:57
vs code 1.20.0 running on ubuntu. auto refresh issue still present.

**Comment by dardub** [comment] 2018-02-22 18:40
This is a base functionality for any IDE. Even though it doesn't "break" anything it deserves attention.

**Comment by arthurwhite** [comment] 2018-03-06 16:12
That also drove me crazy … until I figured out there was a directory with an accent in its name. 💥 

But the refresh only breaks when VS Code is launched from the inside of the directory (or one of its subdirectories).
If the full path from a parent, non-accentuated directory is provided, it works as intended:

```Bash
cd ~/dév
code .      # FAILS (VS Code will never refresh file explorer and opened files)
code ~/dév  # WORKS
```

Maybe it's not the same bug for everyone but here on macOS 10.13, this one is constant and reproducible.

**Comment by Dominik-K** [comment] 2018-03-07 17:45
Does it work if you use the setting `files.useExperimentalFileWatcher": true`? (Seen in the [issue with (maybe) the same root cause #22266](https://github.com/Microsoft/vscode/issues/22266)?
With this setting, it also does not auto-refresh, unfortunately (Version 1.21.0-insider a903bd38f, MacOS El Capitan (10.11.6) )

Interestingly, the Git "Source Control" always auto-refreshs, no matter if the experimental file watcher is used or not.

**Comment by arthurwhite** [comment] 2018-03-07 17:56
@Dominik-K, what about my previous observation?
Don't you have an accent in the directory path from where you open VS Code?

`"files.useExperimentalFileWatcher": true` doesn't affect this bug.

**Comment by Dominik-K** [comment] 2018-03-07 18:02
@arthurwhite You're lucky that auto-refresh is working on your side (with a workaround). Which VSCode version are you using? No, I don't use accents in folder or file names.
So, you better create a new issue with your specific bug. This one is about auto-refresh not working in general.

**Comment by Dominik-K** [comment] 2018-03-07 18:40
Just found out that this happens only if I'm using a workspace. `code-insiders --verbose abc.workspace` shows these lines:

    [99398:0307/192511.104861:INFO:CONSOLE(257)] "%c[IPC Library: Watcher] %cStart watching: [... many folders ...]
    Stop watching: []", source: file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (257)
    [99398:0307/192511.105465:INFO:CONSOLE(257)] "%c[IPC Library: Watcher] %c(node:99405) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit", source: file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (257)
Seems like I have too many folders added to the workspace.

**Comment by arthurwhite** [comment] 2018-03-07 19:14
I have the 1.21.0-insider version. But it has been confirmed also on the stable branch.

> So, you better create a new issue with your specific bug. This one is about auto-refresh not working in general.

I won't post another duplicate of this issue: the effect of this bug is the same.
Maybe the causes are different from one another. But now, we have at least one tangible path to explore.

**Comment by barbossa** [comment] 2018-03-08 16:07
Guys, it can be related to https://code.visualstudio.com/docs/setup/linux#_error-enospc
check this params on your pc

**Comment by Tyriar** [comment] 2018-03-09 15:06
> Guys, it can be related to https://code.visualstudio.com/docs/setup/linux#_error-enospc

In the latest version you should get a nice notification warning you about file handles pointing to those docs.

**Comment by bradennapier** [comment] 2018-03-15 05:16
Literally just spent like a hour trying to figure out why webpack wasnt building a dist folder.  Just moved from atom.  Wow I can not believe this is not working properly.  Love VSCode this is just a huge piece for me.  Only one I noticed was not updating files that were updated elsewhere.  Like if I am updating packages and they are updated by npm gotta close and reopen file to see that.

* switches back to atom for now *

**Comment by dardub** [comment] 2018-03-15 14:41
@Tyriar Can you explain to us how that article linked helps those of us on OSX with this issue. I'm not understanding how that fixes this issue.

**Comment by Tyriar** [comment] 2018-03-15 14:59
@dardub that's for Linux, I didn't imply otherwise did I?

**Comment by dardub** [comment] 2018-03-15 16:44
@Tyriar Ok. Obviously the link was for Linux, but many of us mentioned that this was occurring on other operating systems as well. So I'm just wondering if there is a solution for other operating systems if there is a solution for Linux users.

**Comment by barbossa** [comment] 2018-03-15 19:04
@dardub I`ve edited my comment. Now link is correct.

**Comment by Siraris** [comment] 2018-03-19 16:10
I'm seeing this randomly when switching branches in git.  I can manually refresh and all is OK, but would be nice to have it auto refresh without my intervention.  I tried restarting in verbose mode to see if I could see anything, but now it is fine if I switch back and forth between branches.

**Comment by bpasero** [comment] 2018-03-28 05:53
People seeing this issue, here is some steps to get more info:

VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.

**Comment by Paviluf** [comment] 2018-04-09 19:18
Well it **seem** that it doesn't happen anymore since I removed the symlinks I used to have the folders inside my /home (Desktop, Downloads, etc...) redirected to my other partition /media/Data.

**Comment by maximeplante** [comment] 2018-04-09 19:25
Me it didn't work when I had an accentuated letter in the path of my project folder. It works now that I removed it.

**Comment by bpasero** [comment] 2018-04-10 05:03
@maximeplante which OS are you on and what was the folder name?

**Comment by maximeplante** [comment] 2018-04-10 05:36
macOS 10.13.4

It won't work if the projet's folder has an accent or if the path to the project folder has an accent.

**Comment by snwflake** [comment] 2018-06-13 07:20
### First thing to check:
- [x] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
- [x] I verified that this issue is happening outside of a node_modules folder. Our file watcher ignores this folder!

### To find out more about this issue, please first answer this:
> What OS are you on
- MacOS Sierra 10.12.6

> Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
- I have no idea what the differences between those things are. simple project structure...?!
    `vue init webpack foo && cd foo && yarn install && yarn run build` -> dist folder doesn't exist.

> Do you have files.useExperimentalFileWatcher: true configured in settings?
- No

> What is your configured files.watcherExclude setting?
- Not existing

### Then please answer the following depending on your setup:
- [x] It reproduces with any folder or workspace you open
- [x] The files/folders you open are on your local disk and not on a network share nor a UNC drive
- [x] The files/folders you open are not behind a symbolic link
- [x] The folder(s) opened use the exact same casing as they are on disk
- [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)
- Can't tell...vscode won't allow me to open the same project twice in seperate windows ¯\\\_(ツ)\_/¯

### Then please attach the output of our development console

```
09:11:09.495 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/js/vendor.11a0744ddf4f449bef76.js.gz
09:11:09.495 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/mstile-310x310.png
09:11:09.495 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/android-chrome-512x512.png
09:11:09.496 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensanssemibold.483351b.ttf
09:11:09.496 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensansextrabolditalic.51d4b21.woff2
09:11:09.496 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensansextrabolditalic.cb00b81.woff
09:11:09.496 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensanssemibolditalic.1e78922.woff2
09:11:09.496 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensans.d2a705b.ttf
09:11:09.496 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensansbolditalic.47cf698.ttf
09:11:09.496 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensans.48aa7ad.woff2
09:11:09.498 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensansextrabold.0f5ecd4.woff2
09:11:09.498 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensanssemibold.86dd419.woff2
09:11:09.498 console.ts:136 [IPC Library: Watcher] [ADDED] /Users/snwflake/git-repos/nb-GMTool/client/dist/static/fonts/opensansbolditalic.90b8cd1.woff
09:11:09.501 log.ts:171   ERR [FileWatcher] terminated unexpectedly and is restarted again...
09:11:09.503 ipc.cp.ts:186 IPC "Watcher" crashed with exit code null
(anonymous) @ ipc.cp.ts:186
09:11:09.865 console.ts:136 [IPC Library: Watcher] Start watching: /Users/snwflake/git-repos/nb-GMTool]
```

I shortened the list a little, since there is a bunch more static stuff.

The explorer doesn't even update the files listed by the watcher. The only file inside `dist` is the `index.html`. E.g. not even the fonts listed above are added. Still need to manually refresh...

I feel like this issue should get a lot more attention...

**Comment by ajelcocks** [comment] 2018-06-16 13:11
What OS are you on
MAC OS 10.13.5

Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
Single folder workspace

Do you have files.useExperimentalFileWatcher: true configured in settings?
Tried with and without

What is your configured files.watcherExclude setting?
It isn't set

It reproduces with any folder or workspace you open
yes

The files/folders you open are on your local disk and not on a network share nor a UNC drive 
yes, on local disk

The files/folders you open are not behind a symbolic link
Correct, all local

The folder(s) opened use the exact same casing as they are on disk
yes

It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)
didnt try - I kept it simple

I have not tried insider edition - yet

In a simple project with two folders in the project where folder 1 is in master and both folders are is in a branch...

workspace folder
+ folder 1
+ folder 2
master has workspace+folder1
branch has workspace+folder1+folder2

If I checkout the branch and npm install in folder2, then checkout master the result is that folder 2 is not removed and contains node_modules. The files in folder2 are removed. 
Refreshing the view does no good, presumably because the folders exists on disk.

However, if I checkout master then checkout branch and then back to master without executing npm install then folder2 is removed

It would seem the presence of node_modules is a factor preventing the folder from being deleted.

**Comment by sfrooster** [comment] 2018-06-17 01:31
FWIW - I've been using vscode on OSX for 18 months or so now.  Just today (on the latest version, 1.24.1), I noticed that the file browser wasn't refreshing.  Looking for the issue led me here and in reading the comments I remembered something.  Recently I had experimented with using a workspace, and that workspace had two folders in it.  I didn't like it so I ditched it and went back to the way I normally work, with one exception.  It used to be I would always run "code ." from the directory I wanted to work in, but now I was using "spotlight" and starting vscode and it just happened to open with the files I wanted so....  Except the auto-refresh we're all talking about here wasn't working.  Closing vscode and going back to "code ." from the directory I wanted to work in "fixed" it.

I put "fixed" in quotes because I gather that's not sufficient for what others want, but maybe that little bit of info will help someone else sort it all out...

**Comment by snwflake** [comment] 2018-06-17 04:07
I open all my projects with `$ code ${pathToProject}`, so that doesn't change anything for me.
I also don't use workspaces.

**Comment by sfrooster** [comment] 2018-06-17 04:35
@snwflake And are you having the no-refresh issue, or not?  I'm not sure it's relevant, because I just went back and tested various scenarios involving this to see if I could reproduce the broken state I was in before, and I can't.  So my little anecdote above may very well have been this issue, just presenting in as-if it was related to the way code was opened.

**Comment by snwflake** [comment] 2018-06-17 04:52
@sfrooster I do.
https://github.com/Microsoft/vscode/issues/28432#issuecomment-396839485

**Comment by jannejava** [comment] 2018-07-05 10:06
First of all, most of the things VSCode is great! 

But this a little of a show stopper for me. I have the same problems on macOS, the file explorer does refresh but far from always, it's not reliable, which is a little annoying. If you are running npm in the built-in terminal, it does not refresh.

Also, if you have a lot of folders open and press refresh the whole view reload and selects the row from the top, but does not scroll to the right position so you lose focus.

https://www.dropbox.com/s/fnx6ie45cppij0a/vscode.mp4?dl=0

**Comment by vedmant** [comment] 2018-08-14 09:28
I have the same problem, it could at least reload files when you collapse and then expand a folder.

**Comment by EmpireJones** [comment] 2018-08-21 22:57
Possibly a duplicate: https://github.com/Microsoft/vscode/issues/46058

**Comment by PrinceMerluza** [comment] 2018-09-06 08:58
Still exists. Watching this issue.

**Comment by fuzihaofzh** [comment] 2018-09-20 08:27
Still exists in OSX. Can anyone help to solve?

**Comment by Banonevar** [comment] 2018-09-29 03:35
Same windows 10

**Comment by briemarie** [comment] 2018-10-01 22:32
Just adding another +1 to the issue occurring on OSX. I have to quit VS Code to get new generated files (protobufs, mocks, etc) to show up in the tree.

**Comment by DragonRydrz** [comment] 2018-11-22 00:50
Im on 1.29.1 and after committing files, the folder/file names dont change from green/yellow back to gray.  I have to reload for it to notice that they have been committed.

**Comment by mdo5004** [comment] 2018-12-19 13:55
If it helps anyone, I was in the middle of reporting this and I saw this in my settings:

<img width="925" alt="screen shot 2018-12-19 at 8 51 20 am" src="https://user-images.githubusercontent.com/12416969/50224381-ce5b8880-036b-11e9-87f4-40e1bfb81e97.png">


which obviously meant my file watcher was ignoring _everything_. Not sure how that got there, but clearly the culprit: I removed it and it's working as expected.

Lesson learned: Always double check your settings!

**Comment by NomanGul** [comment] 2018-12-31 17:40
:1st_place_medal:  I found a solution :boom: 

:+1: Settings > Check the "Use Experimental File Watcher" Option...

:man_technologist:  Happy Coding :)

**Comment by pauby** [comment] 2019-01-03 17:49
@NomanGul I've had that checked for some time. Makes absolutely no difference.

**Comment by NomanGul** [comment] 2019-01-03 20:02
@pauby What is your vscode current version? (mine is 1.30.1)

**Comment by pauby** [comment] 2019-01-03 20:30
@NomanGul 1.30.1

**Comment by NomanGul** [comment] 2019-01-03 20:32
In my vscode auto files and git refresh is not working but after check "Use Experimental File Watcher" It's working

**Comment by pauby** [comment] 2019-01-03 20:36
@NomanGul I got that from what you'd said. Earlier in this thread (or it may have been another thread) it was advised to check the 'Experimental' setting so mine has been checked for a while now (I'd say at least 6 weeks) with no effect.

**Comment by akuji1993** [comment] 2019-02-27 15:03
Still exists with and without experimental file watching on MacOS

**Comment by KyivJunta** [comment] 2019-02-27 15:46
Problem appeared again on Win 10 with the latest stable Code.

**Comment by snwflake** [comment] 2019-02-27 22:00
Problem never disappeared on macOS...

**Comment by jakeadelman** [comment] 2019-02-27 23:27
Strangely enough for me it has to do with the extension GitLens. I don't think it's an issue with vscode because the file explorer updates correctly on the dev build (macos). Once I disable GitLens on my personal install the file explorer updates correctly. Might be something other extensions trigger as well but for me it was GitLens

**Comment by ryanmortier** [comment] 2019-04-24 17:45
VS Code: v1.33.1
Windows: v10.0.18362 x64

External file changes are not refreshed as of today.

**Comment by marvila** [comment] 2019-05-24 13:52
I found the same issue a few weeks ago and only now I could investigate it further and found something that might be the culprit, at least on my system. 

It seems to have something to do with symbolic links.

VC Code: 1.34.0
Linux: Ubuntu 18.04

A few weeks ago, I moved my files from one disk to another and created a symbolic link (ln -s) with the same name as before, but pointing, obviously, to the new location.

It was around that time that I noticed the change in behavior. I thought it was due to an extension I installed, but removing it didn't solve the problem.

So today, I don't know why, I tried to open the file through the full path, not the symbolic link _et voilà_, everything worked as expected, that is, i could see the coloring on the side of the changed files and auto sync at the GIT SCM view after saving.

I also noticed that opening through the full path, not the symbolic link, made vscode open the folder as if it was opening a new folder since the previously opened files were all closed.

**So it looks like the issue is with vscode not being able to work through symbolic links.**

_As a workaround: always open folders through their full path / mount point, never through symbolic links._

But I'd really appreciate if it was possible to use symbolic links as it would make my folder path much shorther.

**Comment by tkvw** [comment] 2019-06-06 20:09
So I'm experiencing the same issue. In my use case I am using a `go` code generation tool (`goa`) which overrides generated files if they exists. If I start code in `verbose` mode I see only the `Deleted` events from the filewatcher. So I think this all happens to fast. If I modify my `makefile` and run a `rm -rf <generated folder>` before I run `goa` everything is fine. It just gives the file watcher some time to actually notice the file changes or not to miss fs events.  

Environment: 
```
Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:13:26.790Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-51-generic
```

**Comment by tapz** [comment] 2019-11-13 08:04
After installing MacOS Catalina, file changes are not reflected to the Explorer and add-ons do not get get that information either.

VSC: 1.40.0
MacOS: 10.15.1 (19B88)

**Comment by goldbergyoni** [comment] 2019-11-26 13:26
> After installing MacOS Catalina, file changes are not reflected to the Explorer and add-ons do not get get that information either.

Same here

**Comment by newmrdenis** [comment] 2019-12-02 17:12
Any changes on this issue? I am working via ssh using sshfs (remote filesystem) and after any manipulations performed on connected computer changes doesn't appear on mine( After manually refreshing list of files using corresponding button all appears. It makes me sometimes crazy

**Comment by tdotholla** [comment] 2019-12-06 20:37
i created a new file with "touch blahblah.js" and doesn't show up after changes/saving/etc....

**Comment by giulianisanches** [comment] 2019-12-11 01:26
I'm having this issue and the behaviour is exaclty what @marvila commented above. If i open a folder that is a simbolic link, my source control file explorer does not update.

```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.12.14-lp151.28.32-default
```

**Comment by Ciantic** [comment] 2020-01-09 13:39
I have renamed a src folder, and now when I do "Go to File..." there is a lot of dead files there. I tried "Refresh File Explorer" and restarting/reloading VSCode. Neither works, I have to try to navigate file and get the error "Unable to read file" then it will update that file (by removing it from index), but not all files.

Is there a way to force refresh all files? I think the watcher isn't working in Windows.

**Comment by mertyuksel** [comment] 2020-02-11 16:15
VS Code: 1.42.0
Ubuntu: 18.04

I was getting that notification "Visual Studio Code is unable to watch for file changes in this large workspace" when I opened a laravel project in VS code, and also my file explorer didn't refresh itself when I added a new file. Then I tried this quick solution [here](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc), and my file explorer problem was automatically solved. 

It might help someone else that has the same problem as me.

**Comment by BernardA** [comment] 2020-05-13 12:54
Files are not updated when pulling from `origin`, **even after manually triggering refresh of the explorer**. Only old version available, though I can diff the commits with `git diff HEAD^ HEAD`.

I am forced to clone origin once again.

**Comment by RichIsOnRails** [comment] 2020-08-10 04:38
Having a similar issue. My file list does not update for any terminal actions that create new commands:

Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

This is on remote WSL2. I can open the folder locally on the filesystem and it works fine. As a somewhat unrelated note, the Linux build also works fine so this issue appears to be related to the WSL remote functionality.

**Comment by iPankajrai** [comment] 2020-09-05 11:33
I'm also facing the similar issue with the VS Code. I'm using laravel framework. and whenever I create any file using make:controller anyfilename , in terminal, the file does not get updated in file system of vs code.

Hoping for this bug to be fixed as soon as possible.

**Comment by anhlqn** [comment] 2020-10-15 16:45
VS Code 1.50.0
Windows 10 with WSL 2 and Ubuntu 18.04.
Still having the issue after trying other changes previously suggested.

**Comment by boblitex** [comment] 2020-10-16 02:57
> Version: 1.50.0 (system setup)
> Commit: [93c2f0f](https://github.com/microsoft/vscode/commit/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3)
> Date: 2020-10-07T06:10:52.432Z
> Electron: 9.2.1
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.19041
> 
> Windows 10 with WSL 2 and Ubuntu 18.04.
> Still having the issue after trying other changes previously suggested.

probably a wsl 2 issue, I have the same problem with Ubuntu 20.04

I also don't have intellisense for npm modules

**Comment by dhunt84971** [comment] 2020-11-13 12:59
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-7634-generic

I am having a similar issue using Ubuntu 20.04, but it seems to occur only if the file is named .settings

To reproduce the issue:
1. Create a file named .settings in the root of the project folder from a terminal using touch.
2. The VSCode explorer will not show the recently added file.
3. Clicking the refresh button does not show the file either.

Extensions installed:
code --install-extension brenosolutions.sqlformatter
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eg2.vscode-npm-script
code --install-extension golang.go
code --install-extension HookyQR.beautify
code --install-extension Leopotam.csharpfixformat
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension redhat.java
code --install-extension sensourceinc.vscode-sql-beautify
code --install-extension uctakeoff.vscode-counter
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension Zignd.html-css-class-completion

**Comment by flcoder** [comment] 2020-11-29 21:35
I was having this problem because I was in `~/proj1` which was a symlink to `/mnt/d/p/proj1` and I typed `code .` to open vscode.  When I closed vscode and typed `cd /mnt/d/p/proj1 && code .` vscode behaved fine, so it's an issue with symlinks (for me).

**Comment by MehdizadeMilad** [comment] 2020-11-30 09:52
I had the same issue on Fedora 33, Code 1.51.1.
when I opened a workspace, VSCODE notified me with this message: 

> Unable to watch for file changes in this large workspace. 

this link helped me to fix it:
_[https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc)_

**Comment by erayerdin** [comment] 2021-01-03 05:50
Having the same issue in Kubuntu 20.04.1.

I recently migrated to Kubuntu. I was using Manjaro and it did not have this problem.

BTW, I see people do "Reload Window" thing. Don't do that, it's a waste of resource and time. Instead, do "Refresh Explorer" which only, well, refreshes file explorer.

**Comment by PaulPCIO** [comment] 2021-02-18 08:28
The same issue on windows 10 **wsl** using ubuntu remote.

1. An easy way to recreate the problem, use terminal to create a folder in the current directory:
```
$ mkdir test
```

2. The folder does not show up in vscode untill you hit the refresh icon:
![image](https://user-images.githubusercontent.com/39598117/108327224-6f079600-71cb-11eb-986c-59ee9fb65aa9.png)

**Comment by Ciantic** [comment] 2021-02-18 16:49
@PaulPCIO That is correct, if you want to follow that issue particluarily subscribe to this: https://github.com/microsoft/WSL/issues/4739

Problem is that plan9 doesn't transfer file change events through the barrier. Practically this means you have to live in WSL file system or Windows file system, trying to mix the two will cause problems with dev tools. Personally I hope Microsoft implements real ext4 or linux compatible driver for Windows so that it won't require that hacky Plan9, instead the WSL could appear as real lettered drive without network mapping.

**Comment by bpasero** [comment] 2021-06-21 12:23
I think this issue has grown sufficiently enough that imho it is no longer possible to figure out each individuals issue people have with the file watcher in VSCode. If there are no objections I would like to close this one and open individual issues that are then easier to track.

Since this issue is specifically around the explorer not showing changes when they happen, I opened https://github.com/microsoft/vscode/issues/126817 to investigate whether we could simply refresh the explorer automatically in certain situations to make the issue less likely to occur.

**Some things I want to make clear:**
* file watching over network shares or symbolic links is provided without guarantee - they may or may not work but will often most likely not work
* operating systems may have specific limits in how many file events they can report and may drop events on pressure - this is not really something VSCode can fix without implementing a custom file watcher on each OS that does not rely on native built ins from the filesystem
* VSCode is relying on the operating system to report file events (Windows: [`FileSystemWatcher`](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-5.0), macOS: [`fsevents`](https://github.com/fsevents/fsevents), Linux: [`inotify`](https://man7.org/linux/man-pages/man7/inotify.7.html))

If people have specific issues that are easy to reproduce, then please ping here and we can convert them into individual issues top level and further discuss. Please also be aware of other issues already reported: https://github.com/microsoft/vscode/labels/file-watcher

Thanks!

**Closed** 2021-06-29 05:58 UTC
Labels: file-watcher, needs more info, upstream

**Comment by pauby** [comment] 2021-06-29 08:15
@bpasero When raising the new issues can you link them to this issue, so we can keep track? As you can appreciate this issue was raised over 4 years ago with no movement.

**Comment by bpasero** [comment] 2021-06-29 08:49
I will do my best 👍
