### ISSUE TITLE
[Folding] buttons at linenumbers are not displayed (shortcuts aren't working neither)

### ISSUE THREAD

**Issue by BarbecueSilver** [microsoft/vscode#75632] opened 2019-06-17 13:28 UTC
Issue Type: <b>Bug</b>

**How to reproduce?**
Start VSCode and check for the line number column. Sections of code are not having the `+` and `-` buttons anymore.
The shortcuts described on https://code.visualstudio.com/docs/editor/codebasics#_folding are not working at all.
I tried to restart VSCode and use it without any extensions ... I am still not able to use folding anymore.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 4.18.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2437)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.39GB (0.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment] 2019-06-17 15:21
@BarbecueSilver what language are you coding in?

**Comment by aeschli** [comment] 2019-10-10 13:21
duplicate of #75726

**Closed by aeschli** 2019-10-10 13:21 UTC
Labels: editor-contrib
