### ISSUE TITLE
Menu actions don't work, can't open folder or file

### ISSUE THREAD

**Issue by GDreyV** [Microsoft/vscode#58069] opened 2018-09-06 12:45 UTC
Version 1.26.1
In Developers tool I see several errors:
TypeError: Cannot read property 'getValue' of undefined
    at t.getValue (configurationService.ts:255)
    at t.initServiceCollection (shell.ts:347)
    at t.renderContents (shell.ts:163)
    at t.open (shell.ts:459)
    at main.ts:104
    at Object.g [as _notify] (winjs.base.js:1191)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._oncancel._run (winjs.base.js:1089)
    at n.Class.derive._oncancel._completed (winjs.base.js:1057)
    at runCallback (timers.js:789)
    at tryOnImmediate (timers.js:751)
    at processImmediate [as _immediateCallback] (timers.js:722)

[uncaught exception]: Error: [createInstance] e depends on UNKNOWN service dialogService.
onError @ index.js:41
(anonymous) @ index.js:160
emitOne @ events.js:116
emit @ events.js:211
window.onerror @ C:\Users\avgre\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\renderer\init.js:142

Error: [createInstance] e depends on UNKNOWN service dialogService.
    at e._createInstance (instantiationService.ts:88)
    at e.createInstance (instantiationService.ts:73)
    at shell.ts:343
    at n.Class.derive._creator.done (winjs.base.js:1545)
    at Object.g [as _notify] (winjs.base.js:1201)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._creator._run (winjs.base.js:1089)
    at n.Class.derive._creator._completed (winjs.base.js:1057)
    at Object.g [as _notify] (winjs.base.js:1191)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._oncancel._run (winjs.base.js:1089)
    at n.Class.derive._oncancel._completed (winjs.base.js:1057)
    at Socket.<anonymous> (ipc.net.ts:281)
    at Object.onceWrapper (events.js:313)
    at emitNone (events.js:106)
    at Socket.emit (events.js:208)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1169)

**Comment by GDreyV** [comment] 2018-09-06 12:48
I removed all extensions, also I removed entire Code folder in %appdata%, reinstalled Vscode and rebooted system several times.

**Comment by sandy081** [comment] 2018-09-06 17:58
@GDreyV May I know you see this error when you start VS Code? 

@bpasero This can only open if the configuration service is not initialised. Do you know any code paths that code lead to uninitialised configuration service?

**Comment by bpasero** [comment] 2018-09-07 05:06
Maybe VSCode crashed somewhere on startup but the menu was still there (the native one is always there) and the user could interact with actions with a broken workbench?

**Comment by GDreyV** [comment] 2018-09-07 09:02
@sandy081 yep, when I start vscode the only thing I see is top menu - welcome page is not loaded as well. From system (top) menu I can toggle developer tools, open about popup... When I press check for updates Vscode just closes.

**Comment by GDreyV** [comment] 2018-09-10 09:30
Did you manage to reproduce the issue? Is there any workarounds for that?

**Comment by sandy081** [comment] 2018-09-11 13:20
@GDreyV No, I could not reproduce it.

Can you please let us know if there was a crash while opening VS Code?

@bpasero Assigning to you.

**Comment by GDreyV** [comment] 2018-09-13 08:01
@sandy081 to be 100% sure that we are on the same page I recorded small video to show how does it work on my side: https://youtu.be/XK-198iSt-k

**Comment by bpasero** [comment] 2018-09-13 08:11
Somehow there seems to be a NPE happening when accessing the configuration service here: 

https://github.com/Microsoft/vscode/blob/26d471d4795dc55d033fa91099593f772428f01b/src/vs/workbench/electron-browser/shell.ts#L357

@GDreyV does it reproduce if you start from the command line pointing to a different user data directory: `code --user-data-dir <other dir>`

**Comment by GDreyV** [comment] 2018-09-13 09:28
@bpasero yes, it works fine.

**Comment by bpasero** [comment] 2018-09-13 10:03
@GDreyV what happens if you start with "code -n"? I would still like to understand how you end up with that exception

**Comment by sandy081** [comment] 2018-09-13 10:39
@bpasero As said earlier, NPE in configuration service can happen only when configuration service is not initialised. There should be an error before this NPE while initialising.

**Comment by bpasero** [comment] 2018-09-13 10:47
@GDreyV that is too bad. If you can ever reproduce, can you run "code --verbose" from the command line and report back? Closing for now.

**Comment by bpasero** [comment] 2018-09-13 10:47
@GDreyV actually if you do not mind, maybe send us the logs that got produced. You can find them here: 

![image](https://user-images.githubusercontent.com/900690/45484074-38540880-b753-11e8-8281-1885ee975e2e.png)

**Closed by bpasero** 2018-09-13 10:47 UTC
Labels: freeze-slow-crash, needs more info

**Comment by GDreyV** [comment] 2018-09-14 08:10
Sure, here's the link to the log files I found in that folder https://1drv.ms/u/s!AqyaJ9a4KonbnZJPrP6eKj7wMXe7fQ ... hardly think if it will help somehow because they are mostly empty :(

**Comment by bpasero** [comment] 2018-09-14 08:50
Yeah, does not seem to contain any info :-/
