### ISSUE TITLE
How i can split terminal tabs in two, for using another sessions side by side 

### ISSUE THREAD

**Issue by klaveren** [Microsoft/vscode#33122] opened 2017-08-25 05:31 UTC
Well, i don'n know if exist this options, but if exist, how I can do?
Thanks

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment] 2017-08-30 17:47
Duplicate of https://github.com/Microsoft/vscode/issues/7504

**Closed by Tyriar** 2017-08-30 17:47 UTC
Labels: integrated-terminal
