### ISSUE TITLE
Renaming a file twice causes unwanted rename abortion

### ISSUE THREAD

**Issue by josiahsrc** [microsoft/vscode#115549] opened 2021-02-01 15:41 UTC
- VSCode Version: 1.52.1
- OS Version: Mac OS Big Sur 11.1

Steps to Reproduce:

1. Rename a file
2. Rename the file again shortly thereafter

Does this issue occur when all extensions are disabled?: Yes

Demo of the issue below. I renamed the file, then tried to rename again. While renaming the second time, the editor will exit renaming the file. My intention was to remove the "_renaming" suffix from the folder name, but it exited automatically before I could do so.

https://user-images.githubusercontent.com/37915005/106480990-32b50580-6469-11eb-80be-c377ec26f318.mov

**Comment by gjsjohnmurray** [comment] 2021-02-01 16:10
Looks like a duplicate of an issue fixed in the upcoming 1.53, expected this week Are you able to try and reproduce it with [Insiders](https://code.visualstudio.com/insiders/)?

**Closed** 2021-02-01 16:18 UTC
Labels: *duplicate

**Comment by josiahsrc** [comment] 2021-02-01 18:11
@gjsjohnmurray The insiders build fixes the issue. Thanks! Do you know when 1.53 will be released in the stable build?

**Comment by gjsjohnmurray** [comment] 2021-02-01 18:34
@josiahsrc based on the endgame plan https://github.com/microsoft/vscode/issues/114896 we should see it Wednesday or Thursday
