### ISSUE TITLE
Refactor when moving files

### ISSUE THREAD

**Issue by claudius25** [Microsoft/vscode#26314] opened 2017-05-09 14:15 UTC
The best feature you could have is to refactor when moving files in the explorer (out of the box) 
There is a extension (move ts) but it's buggy. 
It's a basic refactor thing, which to my surprise is not in visual code. 

So if i move a file from a folder to another, i want it's path reference to be updated automatically in the project. I tried this on a angular 2 project with .ts files and it did not work. I haven't tried with other files.

Thanks

**Comment by stringham** [comment] 2017-05-20 15:11
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/19439 which is waiting on TS language support tracked by https://github.com/Microsoft/TypeScript/issues/6487.

Because I needed this functionality for a large project, I created the [Move TS](https://marketplace.visualstudio.com/items?itemName=stringham.move-ts) extension to get by in the meantime. If you're having issues with the extension, I recommend opening an issue: https://github.com/stringham/move-ts/issues

**Comment by mjbvz** [comment] 2017-11-03 22:49
Duplicate of #19439

**Closed by mjbvz** 2017-11-03 22:49 UTC
Labels: duplicate, editor, feature-request
