### ISSUE TITLE
100 % memory usage everytime it tries to do code assist

### ISSUE THREAD

**Issue by ogiexela** [microsoft/vscode#89744] opened 2020-01-30 21:46 UTC
Issue Type: <b>Bug</b>

I'm using vs code for angular/typescript app development and it started using 100% of memory all of the sudden every time I try to invoke code assist ctrl+space. I've restarted my computer many times times.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.900.7
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.0
vscode-firefox-debug|fir|2.6.1
import-sorter|mik|3.3.1
vscode-typescript-tslint-plugin|ms-|1.2.3
sort-lines|Tyr|1.9.0

</details>

**Comment by mjbvz** [comment] 2020-01-31 19:36
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2020-01-31 19:37
Also, if you see this issue in VS Code insiders, please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status` when you see the high cpu usage

**Comment by mjbvz** [comment] 2020-02-07 23:55
Closing as not actionable without more info. Possible caused by an extension like the angular one

**Closed by mjbvz** 2020-02-07 23:55 UTC
Labels: needs more info
