### ISSUE TITLE
Don't expand the folded region automatically

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#64026] opened 2018-11-29 20:51 UTC
Issue Type: <b>Feature Request</b>

**VSC**

![vsc](https://user-images.githubusercontent.com/7588612/49250970-3cb9c480-f418-11e8-9dce-e48cccc3e21d.gif)

Visual Studio doesn't expand the folded region unless you click on the `+` icon

**VS**

![notexpand](https://user-images.githubusercontent.com/7588612/49250868-e64c8600-f417-11e8-8a0c-de2fd81868c9.gif)

VS Code version: Code - Insiders 1.30.0-insider (cd5b4d1bb3fc7e509fba077095b2b280b8ff7161, 2018-11-29T06:32:54.872Z)
OS version: Windows_NT x64 10.0.18290

**Comment by aeschli** [comment] 2019-01-04 14:23
duplicate of #53886

**Closed by aeschli** 2019-01-04 14:23 UTC
Labels: editor-folding, feature-request
