### ISSUE TITLE
Window always on top

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#73046] opened 2019-04-29 18:50 UTC
There are times when I would like the editor to **ALWAYS** be on top of other widows, such as when I am writing JavaScript code for the browser and I am limited on screen space, I would sometimes like to have vscode on top of my browser even when the browser has focus. 

I have a Windows 10 extension to do this when I right click on a Windows window, an option shows to keep the window on top (This is also built into Ubuntu):

![Always on top](https://user-images.githubusercontent.com/1571806/56918881-ca134a80-6a84-11e9-95e8-98de832728bb.png)

This works for most windows, but when using the `"window.titleBarStyle": "custom"` option in vscode that `Always on top` doesn't exist any more as seen here:

![Always on top gone](https://user-images.githubusercontent.com/1571806/56918889-ced7fe80-6a84-11e9-834c-56cb25cea624.png)

I see that Electron has an option for this, but it isn't utilized in vscode

https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L127

```js
new BrowserWindow({ alwaysOnTop: true })
```

It would be helpful (at least for me) if either:

A. Additional window options were added to the title bar.
B. There was a command that toggled forcing the window to stay on top.

**Comment by RMacfarlane** [comment] 2019-04-30 01:09
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/68482, let's track it there. Please go thumbs-up that issue and add any additional comments. Thanks!

**Closed by RMacfarlane** 2019-04-30 01:09 UTC
