### ISSUE TITLE
Cannot display all symbols of Default Settings (1.8)

### ISSUE THREAD

**Issue by pierredewilde** [Microsoft/vscode#17378] opened 2016-12-16 08:10 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none

With the new appareance of Default Settings, we loose the possibility to view all settings (symbols) using `cmd+shift+O`.

Moreover, the commands `Fold All` and `Unfold All` are not more applicable to Default Settings, only to User/Workspace Settings.

**Comment by pierredewilde** [comment] 2016-12-16 08:13
Is it a settings to disable new Default Settings view and restore old one ?

**Comment by kieferrm** [comment] 2016-12-17 13:58
Duplicate of #17376. Having an option for using the old behavior is tracked in #17371.

**Closed by kieferrm** 2016-12-17 13:58 UTC

**Comment by sandy081** [comment] 2016-12-19 11:45
@pierredewilde As said this is being tracked in #17371, your input over there is much welcome. Thanks.
