### ISSUE TITLE
wrong cursor position when using cmder in vscode

### ISSUE THREAD

**Issue by lonelykid** [Microsoft/vscode#69582] opened 2019-02-28 07:07 UTC
- VSCode Version:1.31.1
- OS Version: Win 10 1809

Steps to Reproduce:

As shown in the figure, there's a mismatch when moving the cursor to the left and back. The problem might be related to the clink injection part of the cmder script.
![image](https://user-images.githubusercontent.com/2936633/52658700-af8bf500-2ec9-11e9-98c8-e23ff1693524.gif)

The related settings are
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.env.windows": {"CMDER_ROOT": "C:\\Users\\xxx\\apps\\cmder"},
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "C:\\Users\\xxx\\apps\\cmder\\vendor\\test.bat /f"
    ]

I understand this might not be the best place to ask. But I wish to get some help about how to fix this since many vscode&cmder users would come across this rep.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by lonelykid** [comment] 2019-02-28 08:03
I managed to solve the problem by replacing the lambda λ prompt with dollar $. BTW, the same mismatch happens for bash/powershell/cmd as long as you use λ as the prompt symbol. It might not be a good idea for them to use λ. But it seem to be a issue for vscode. anyway, it doesn't matter as long as you can replace the symbol

**Comment by Tyriar** [comment] 2019-03-01 00:00
Looks like a duplicate of https://github.com/xtermjs/xterm.js/issues/1709

**Closed by Tyriar** 2019-03-01 00:00 UTC
Labels: integrated-terminal
