### ISSUE TITLE
VSCode Freezes on cancelled Open Workspace

### ISSUE THREAD

**Issue by astanciu** [Microsoft/vscode#45256] opened 2018-03-08 05:38 UTC
- VSCode Version: 1.21.0
- OS Version: 10.13.3

Steps to Reproduce:

1. Open VS Code
2. File > Open Workspace
3. Cancel out of the finder file picker
4. Stuck with spinning beach ball

( At this point you have to ForceQuit and to restart. You will run into #45160. You must `sudo rm ~/Library/Application\ Support/Code/1.21.0-main.sock` )

Does this issue occur when all extensions are disabled?: Yes!

**Comment by bpasero** [comment] 2018-03-08 05:44
@astanciu I cannot reproduce what you describe, can you share a video what you do? Also, does it happen with other dialogs that you cancel too?

**Comment by astanciu** [comment] 2018-03-08 13:49
I can make a video (or gif) if really needed, but it's quite literally:
- Open VSCode
- File -> Open Workspace -> Cancel
- Enjoy spinning beachball

I did just try another dialog (just File -> Open) and that also froze it.

**Comment by bpasero** [comment] 2018-03-08 14:09
@astanciu 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by astanciu** [comment] 2018-03-08 14:16
I restarted my computer and I can no longer reproduce this :/ If you want we can close this. I suspect it may have something to do with what's happening in  #45160. I'll update if I can repro this after a crash/forcekill/removal of .sock file

**Comment by bpasero** [comment] 2018-03-08 15:15
@astanciu ok closing, but ping me when it happens again

**Closed by bpasero** 2018-03-08 15:15 UTC
Labels: freeze-slow-crash, needs more info, new release
