### ISSUE TITLE
Use of bash bitwise shift left causes colour highlighting to break

### ISSUE THREAD

**Issue by theknowledge** [microsoft/vscode#227068] opened 2024-08-29 11:40 UTC
Type: <b>Bug</b>

Including bash bitwise shift left << inside a variable assignment causes all subsequent colour highlighting to break, all text except $variables appears orange
e.g.
b=$(( a << 4 ))

Other operators do not cause a problem.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.25GB free)|
|Process Argv|--crash-reporter-id bec0f67a-4990-41d2-bfd2-893d445a558a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.27.1
rainbow-csv|mec|3.12.0
debugpy|ms-|2024.8.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.19.49
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.10.26
remote-explorer|ms-|0.4.3
tcl|ras|0.1.0
shellcheck|tim|0.37.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by theknowledge** [comment] 2024-08-29 11:42
Problem persists in v1.92.2

**Comment by theknowledge** [comment] 2024-08-30 14:27
Hi Alex, sure thing:
![image](https://github.com/user-attachments/assets/2dfbe2f5-7a53-4029-a24f-8fd120364d37)

As opposed to:
![image](https://github.com/user-attachments/assets/211deb1b-5701-4fbe-8312-324da84ae86f)

Thanks

**Comment by johan-boule** [comment] 2024-08-31 18:22
I think VSCode's syntax parsing for Bash or just posix shell, is probably only 50% correct, no more.
I don't use VSCode for doing bash stuff, because the colors are wrong half the time and it's distracting.

**Comment by alexr00** [comment] 2024-09-02 18:06
Duplicate of the upstream issue https://github.com/jeff-hykin/better-shell-syntax/issues/93, but because of the license change we can't take the fix.

**Closed** 2024-09-02 18:07 UTC
Labels: grammar, upstream-issue-linked
