### ISSUE TITLE
"Terminal process "bash "" failed to launch (exit code: 127)" debugging C++ over WSL with last Insiders build.

### ISSUE THREAD

**Issue by slaierno** [microsoft/vscode#124116] opened 2021-05-18 14:55 UTC
Issue Type: <b>Bug</b>

This issue occurs when starting a debug session even with the simplest hello world C++ program on WSL (did not try other languages). I noticed that on an existing project, then tried a brand new hello world project, obtaining the same issue. 

It seems not to be related to the C/C++ extensions, since the extension was not recently updated and using a non-Insiders VSCode version works flawlessly.

Running any debug instance, will generate a "Terminal process "bash "" failed to launch (exit code: 127)", than the "debugging state" will hang until the stop button is pressed

To replicate the bug, just create a simple C++ project and try to debug the main file.

![bug_vscode](https://user-images.githubusercontent.com/7281159/118673810-9802eb80-b7f9-11eb-8b04-dac44c7b504f.gif)

VS Code version: Code - Insiders 1.57.0-insider (45aafeb326d0d3d56cbc9e2932f87e368dbf652d, 2021-05-18T05:14:15.253Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.54GB free)|
|Process Argv|--crash-reporter-id b1bdaaae-e0bb-4809-9b74-caea9dd5a156|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS8|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.88GB (20.44GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS8|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.88GB (20.44GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
gitlens|eam|11.4.1
vscode-reveal|evi|4.0.3
comment-anchors|Exo|1.9.3
cpptools|ms-|1.4.0-insiders2
asn1|wil|0.5.3

</details>

**Comment by Tyriar** [comment] 2021-05-18 18:41
Do you set `terminal.integrated.inheritEnv`?

**Comment by slaierno** [comment] 2021-05-18 19:20
Yes, I've tried `true`, `false` and unsetted (which should default to `true`, I suppose...?). Setting `terminal.integrated.inheritEnv` or not does not change the behaviour. Also, setting it or not does not alter the (correct) behaviour with the stable version of VSCode.

**Comment by csghone** [comment] 2021-05-19 05:03
These are reported elsewhere as well.

#124007 - This one was incorrectly closed
#123949 - This was closed as a duplicate of the previous one.

**Comment by altosaar** [comment] 2021-05-19 20:43
Also facing this issue

**Comment by gusar** [comment] 2021-05-20 08:58
Also experiencing the exact same problem.
Version 1.57.0-insider

**Comment by a-tom** [comment] 2021-05-20 09:14
Same issue here using zsh and a python program to debug.
Code Version 1.57.0-insider (from 2021-05-20T05:14:43.087Z)
WSL: Debian Buster
WinVer: 1909 Build 18363.1500

I very briefly see the following text in the terminal before it switches back to my previous terminal:
```
This shell is running on your local machine, NOT on the connected remote machine
/usr/bin/zsh: can't open input file:
```

After that I get the same error
```
The terminal process "zsh ''" failed to launch (exit code: 127).
```

**Comment by altosaar** [comment] 2021-05-20 13:55
Solved with setting  "console": "internalConsole" in the configuration (from #123949)

**Comment by gusar** [comment] 2021-05-20 13:58
"console" is not possible to set with a cppdbg launch configuration. Therefore it's not a solution.

**Comment by testforstephen** [comment] 2021-05-21 09:30
Also have this issue in Java debugger. Since the terminal is the only way to accept program input, hope this issue can be fixed before new VS Code release out.

**Comment by chimaoshu** [comment] 2021-05-21 12:51
I also faced this problem, I have tried WSL (Ubuntu 20.04), Remote SSH(CentOS) and Windows, this problem will appear everytime when I was launching a debug task. I use default setting on anything about terminal.integrated.

Version: 1.57.0-insider (user setup)
Commit: 4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5
Date: 2021-05-21T05:13:41.097Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by verma16Ayush** [comment] 2021-05-21 16:50
same issue. happens only in insiders version

**Comment by prittjam** [comment] 2021-05-21 21:13
same issue

**Comment by andrea-de** [comment] 2021-05-24 13:15
Also having this issue only with code-insiders. Code is configured with the same exact settings as Code Insiders, which works. 
I tried disabling extensions in case it might have an effect but the result was the same.

**Comment by andrea-de** [comment] 2021-05-24 13:16
Also having this issue only with code-insiders. Code, which works, is configured with the same exact settings as Code Insiders. I tried disabling extensions in case it might have an effect but the result was the same.

**Comment by griffiti** [comment] 2021-05-24 19:16
I'm also getting issue trying to run Java apps / macOS 11.3.1. Fails with Insiders only.

**Comment by Tyriar** [comment] 2021-05-25 12:16
Possible improvements I just made:

- Force inheritEnv/useShellEnvironment for ext debug terminals https://github.com/microsoft/vscode/issues/124041
- Add -l to macOS default profiles, was only in fallback profiles https://github.com/microsoft/vscode/issues/124409

Someone is pointing out the double single quote (`''`) here, but it hasn't changed recently: https://github.com/microsoft/vscode/issues/123949#issuecomment-841847897

**Comment by Tyriar** [comment] 2021-05-25 12:17
A cpp duplicate: https://github.com/microsoft/vscode-cpptools/issues/7551

**Comment by Tyriar** [comment] 2021-05-25 13:20
For anyone experiencing this issue can you [enable trace logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging) and paste is logged when creating the terminal? This will give information about how the terminal launches

**Comment by anatolyburakov** [comment] 2021-05-25 13:44
These logs contain a lot of personally identifying information, is there a particular log file you would like to look at, and how much of it? Is it "extension host"? "Window"? "Main"?

On another note, is it possible to downgrade to previous Insiders build, because this bug has thrown a giant wrench in my workflow?

**Comment by Tyriar** [comment] 2021-05-25 13:54
@anatolyburakov this one:

<img width="522" alt="Screen Shot 2021-05-25 at 6 53 25 AM" src="https://user-images.githubusercontent.com/2193314/119509916-e8aca400-bd25-11eb-97df-78753bffc0bd.png">

Plus this one (which will be in the remote server log):

<img width="622" alt="Screen Shot 2021-05-25 at 6 54 10 AM" src="https://user-images.githubusercontent.com/2193314/119510010-037f1880-bd26-11eb-87d1-b95634089b8d.png">

The `env` part is important but you may want to sanitize some of that.

**Comment by anatolyburakov** [comment] 2021-05-25 13:57
I'm not sure how to get to the screens you have shown (please don't assume everyone is a proficient web developer!), could you please provide more details as to how to get there?

Looking in remote logs, i found the following in "Remote Server" log:
```
[2021-05-25 13:50:23.868] [remoteagent] [debug] Terminal process launching on remote agent {"shellLaunchConfig":{"name":"Build docs","executable":"bash","args":["-c","make docs"],"cwd":"/root/xxxx","useShellEnvironment":true},"initialCwd":"/root/xxxx","cols":195,"rows":15,"env":{"no_proxy":"localhost,127.0.0.1","USER":"root","SSH_CLIENT":"xxxx","XDG_SESSION_TYPE":"tty","SHLVL":"0","MOTD_SHOWN":"pam","HOME":"/root","OLDPWD":"/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46","DBUS_SESSION_BUS_ADDRESS":"unix:path=/run/user/0/bus","https_proxy":"xxxx","LOGNAME":"root","http_proxy":"xxxx","_":"/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/node","XDG_SESSION_CLASS":"user","XDG_SESSION_ID":"5296","PATH":"/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/bin:/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin","ftp_proxy":"xxxx","XDG_RUNTIME_DIR":"/run/user/0","LANG":"en_US.UTF-8","SHELL":"/bin/bash","PWD":"/root","SSH_CONNECTION":"xxxx","HISTTIMEFORMAT":"%d/%m/%y %T ","LESSCLOSE":"/usr/bin/lesspipe %s %s","LESSOPEN":"| /usr/bin/lesspipe %s","LIBVIRT_DEFAULT_URI":"qemu:///system","XDG_DATA_DIRS":"/usr/local/share:/usr/share:/var/lib/snapd/desktop","BROWSER":"/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/bin/helpers/browser.sh","TERM_PROGRAM":"vscode","TERM_PROGRAM_VERSION":"1.57.0-insider","COLORTERM":"truecolor","VSCODE_GIT_IPC_HANDLE":"/run/user/0/vscode-git-ac21d75fa8.sock","GIT_ASKPASS":"/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/git/dist/askpass.sh","VSCODE_GIT_ASKPASS_NODE":"/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/node","VSCODE_GIT_ASKPASS_MAIN":"/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/git/dist/askpass-main.js"}}
```

This looks vaguely relevant to what we're trying to achieve here...

**Comment by Tyriar** [comment] 2021-05-25 14:29
@anatolyburakov and that's exiting with a code of 127? It looks fine based on the log 🤔 

Shell and args look fine:

> "executable":"bash","args":["-c","make docs"]

`useShellEnvironment` is set (forces inheritEnv = true):

> "useShellEnvironment":true

PATH looks fine:

> "PATH":"/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/bin:/root/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

**Comment by anatolyburakov** [comment] 2021-05-25 14:30
@Tyriar is there anything else i can check and help debug this issue?

**Closed** 2021-05-25 17:37 UTC
Labels: needs more info

**Comment by pythonmaxi** [comment] 2021-05-25 18:41
Same problem here on Linux debugging python code.

**Comment by meganrogge** [comment] 2021-05-25 19:02
Will be fixed in Insider's tomorrow.
