### ISSUE TITLE
Save Workspace Only When You Click 'Closed Workspace' and Not When Closing VSCode

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#30974] opened 2017-07-19 01:33 UTC
- VSCode Version: 1.15.0 Insiders ( 3cfa565 , Date 2017-07-17T05:15:33.728Z)
- OS Version: Windows 10

From [#30608](https://github.com/Microsoft/vscode/issues/30608#issuecomment-315092428)

@bpasero  said that the intent would be to ask to save Workspace when the VSCode closed. In my view, this request should only be made when I click on 'Closed Workspace.' (It will be very uncomfortable to be forced to save when closing)

It should work the way it is in the current version, and when I use a single folder. If I close the VSCode when I open it again it returns in the state that it was.

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-07-19 04:54
@Tekbr the consequence of that is that we need to show untitled workspaces throughout the UI (e..g File > Open Recent). Not sure how useful that is since these workspaces have no name.

**Comment by bpasero** [comment] 2017-11-17 08:23
Closing "as designed", no plans to change this currently.

**Comment by Tekbr** [comment] 2017-11-17 13:55
-- Sorry for the English, I used Google Translator --

@bpasero  There is a moment we need to close everything running, for several reasons and being forced to save is very bad. Yet, it must be considered. Please reopen.

**Comment by bpasero** [comment] 2017-11-17 14:37
@Tekbr sorry, this is our issue clean up and some rules apply. We do not want to keep issues open that a) do not have lots of upvotes and b) are unlikely to get looked at for the next 6-12 months.

I am not inventing this clean up, it comes from https://github.com/Microsoft/vscode/issues/38268 so please complain there.

**Comment by bpasero** [comment] 2017-11-17 14:52
Given multi-root is a relatively new feature, I am willing to be less strict and wait for more user feedback. But please understand that this issue will not get much attention from me unless it ends up highly requested also from others.

**Comment by Tekbr** [comment] 2017-11-17 15:10
-- Sorry for the English, I used Google Translator --

@bpasero Anyway thank you. I still ask you to watch this case with care.

**Closed** 2018-09-11 09:30 UTC
Labels: *out-of-scope, feature-request, multi-root

**Comment by Tekbr** [comment] 2018-09-19 23:33
-- Sorry for the English, I used Google Translator --

@bpasero , in case #42657 it looks like @DavidLudwig was wanting to send a PR, I do not know if he came to see .. or could that question only be resolved by the members?

**Comment by mpressen** [comment] 2019-05-29 09:10
really annoying and time-consuming to have to click on 'Don't Save' every time i decide to close a workspace.
I use them to have several instance of vs_code on different screens via 'Duplicate workspace in new window'.
Would love a checkbox to tick in order to not see it ever again
