### ISSUE TITLE
`getWordRangeAtPosition` result is neither a closed interval nor half-open

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#4694] opened 2016-03-26 19:04 UTC
- VSCode Version:
  0.10.12-insider
- OS Version:
  Ubuntu 14.04

From my comment in aioutecism/amVim-for-VSCode#52

Some problems with `getWordRangeAtPosition`:
- it tries to return a half-open range (start is inclusive, end is not), but it's more like a quasi-half-open range
- most of the time when the cursor is positioned inside non-words, it returns undefined

The one exception to the latter point is that it _won't_ return undefined if called from a position at the end of one of those half-open ranges.  For example, for the string

```
foo bar  baz   fum
```
- inside "foo" it returns character offsets [0, 3)
- inside "foo" it returns [4, 7)
- inside "foo" it returns [9, 12)
- inside "foo" it returns [15, 18)

But:
- for the space before "fum" it returns undefined
- for the space before "baz" it returns undefined
- for the space before "bar" it returns [0, 3)

Even if someone says, "the word's range end should point to an offset just past the end of the word", then I would say, "great, that's called a half-open interval, but the space after 'foo' and 'bar' and 'baz' should still be consistent with the subsequent spaces, and right now it isn't, which means sometimes it's treating the range as a half-open interval, and other times it's treating it as a closed interval".

**Comment by colbyrussell** [comment] 2016-03-26 19:07
I think ultimately the best thing would be it if this API just ditched the half-open intervals and use all closed intervals, all the time.  E.g., for `foo   bar`:

- For any position inside "foo", it returns [0, 2]
- For any position over one of the spaces, it returns [3, 5]
- For any position inside "bar", it returns [6, 8]

Alternatively:

- For the first space, it returns [3, 3]
- For the second space, it returns [4, 4]
- For the third space, it returns [5, 5]

Or:

- For any position over one of the spaces, it returns undefined, unless a second optional argument is passed to `getWordRangeAtPosition`, in which case it returns [3, 5]

**Comment by alexandrudima** [comment] 2017-03-01 15:56
This is by design. A position is a location **between** two characters or the location before the first character or the location after the last character on a line:

![image](https://cloud.githubusercontent.com/assets/5047891/23467571/b53c2d06-fe9e-11e6-90eb-4e8a53c19cd3.png)

e.g. (considering this to be the first line in the document)

### position (0,1):
![image](https://cloud.githubusercontent.com/assets/5047891/23467657/ed4c5b44-fe9e-11e6-979e-58bfdff9e5e3.png)

### position (0,7):
![image](https://cloud.githubusercontent.com/assets/5047891/23467765/303e75e0-fe9f-11e6-908a-226836786138.png)

### position (0,8):
![image](https://cloud.githubusercontent.com/assets/5047891/23467850/68b1a230-fe9f-11e6-9534-67e67ef93a35.png)

---

That is why `getWordRangeAtPosition` returns undefined for positions `(0,8), (0,13), (0,14)` in this case, because there are no words adjacent to/touching those positions. i.e.:

![image](https://cloud.githubusercontent.com/assets/5047891/23468007/de88c6be-fe9f-11e6-80cc-48ddc425f1ad.png)

**Closed by alexandrudima** 2017-03-01 15:56 UTC
Labels: api, editor
