### ISSUE TITLE
Terminal cant open

### ISSUE THREAD

**Issue by kshivam654** [microsoft/vscode#180268] opened 2023-04-18 23:12 UTC
Type: <b>Bug</b>

The terminal process failed to launch: A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\conpty-3392794.359076339-in').

shows this error wheneven i try to open terminal

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.56GB (6.69GB free)|
|Process Argv|--crash-reporter-id eb0cb7b0-c003-418f-99db-350ada74861a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
atlascode|atl|3.0.3
vscode-tailwindcss|bra|0.9.11
path-intellisense|chr|2.8.4
codeium|Cod|1.2.3
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.5.0
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.7.5
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
vscode-language-babel|mgm|0.0.38
vscode-docker|ms-|1.25.0
isort|ms-|2022.8.0
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.20
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.288.1
vsliveshare|ms-|1.0.5862
material-icon-theme|PKi|4.26.0
vscode-yaml|red|1.12.2
LiveServer|rit|5.7.9
console-ninja|Wal|0.0.106

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsccsb:30705552
vscodedisable:30660115
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30716742
pythonclientmvcf:30713944

```

</details>

**Comment by meganrogge** [comment] 2023-04-19 01:13
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-04-19 01:13 UTC
