### ISSUE TITLE
Problem installing extension

### ISSUE THREAD

**Issue by aphilpotts** [Microsoft/vscode#2162] opened 2016-01-21 21:51 UTC
If I try to install the extension, vscode asks to restart, then after restarting I see an "issue" at the bottom left of the vscode window.

[c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/csharp-o]: Cannot read file c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/csharp-o/package.json: ENOENT: no such file or directory, open 'c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\csharp-o\package.json'

This also breaks the install system, as the extension is half installed, I had to remove the extensions folder to fix that.

**Comment by joaomoreno** [comment] 2016-01-25 09:29
Duplicate of #1605

**Closed by joaomoreno** 2016-01-25 09:29 UTC
Labels: install-update
