### ISSUE TITLE
input " in terminal

### ISSUE THREAD

**Issue by tingtien** [Microsoft/vscode#15627] opened 2016-11-17 09:50 UTC
- VSCode Version:1.7.1 
- OS Version:10.11.6
- terminal : iTerm2(3.0.12)

Steps to Reproduce:

1. there are the messy code when I input " in terminal,but it is right in the iTerm2.

vs code:
![1118-1](https://cloud.githubusercontent.com/assets/5448557/20384306/47f272ac-acee-11e6-979e-8280a31cccc6.jpg)

iterm2:
![1118-2](https://cloud.githubusercontent.com/assets/5448557/20384860/4257fb30-acf0-11e6-8aa9-c12cdef9448b.jpg)

**Comment by Tyriar** [comment] 2016-11-18 04:13
Duplicate of https://github.com/Microsoft/vscode/issues/14586

**Closed by Tyriar** 2016-11-18 04:13 UTC
Labels: integrated-terminal
