### ISSUE TITLE
VS Code can freeze on startup sending messages to extension host

### ISSUE THREAD

**Issue by Platzer** [Microsoft/vscode#13667] opened 2016-10-13 11:02 UTC
- Version 1.7.0-insider
- Commit 5dd716eaedc5a239379013863568c7f7dea708a5
- Date 2016-10-13T08:02:00.080Z
- OS Version: Win 7 x64

Steps to Reproduce:
---
1. Open workspace with one open "medium" source code file (~ 2500 lines of code)
2. Cannot reproduce with VSCode 1.6

Console output of `code-insiders.cmd VCS_Dokumente --disable-extensions --verbose`:
---
```
[main 12:52:09] Starting VS Code in verbose mode
[main 12:52:09] from: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app
[main 12:52:09] args: { _: [ 'C:\\Users\\platzelu\\Documents\\VCS_Dokumente' ],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false }
[8996:1013/125209:ERROR:jump_list.cc(274)] Failed to append custom category 'Recent Folders' to Jump List due to system privacy settings.
[8996:1013/125210:INFO:CONSOLE(66)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (66)
[main 12:52:11] IPC#vscode-workbenchLoaded
ApplicationInsights:Sender [ { Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:80
      at errnoException (dns.js:28:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
    code: 'ENOTFOUND',
    errno: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com',
    host: 'dc.services.visualstudio.com',
    port: 80 } ]
ApplicationInsights:Sender [ { Error: getaddrinfo ENOTFOUND vortex.data.microsoft.com vortex.data.microsoft.com:443
      at errnoException (dns.js:28:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
    code: 'ENOTFOUND',
    errno: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'vortex.data.microsoft.com',
    host: 'vortex.data.microsoft.com',
    port: 443 } ]
[VS Code]: detected unresponsive
[main 12:52:49] Lifecycle#window-all-closed
[main 12:52:49] Lifecycle#before-quit
[main 12:52:49] App#will-quit: disposing resources
```
Developer Tools Consol output: 
---
![grafik](https://cloud.githubusercontent.com/assets/3358663/19346725/2dd290ba-9145-11e6-8a56-f685510a69da.png)

**Comment by bpasero** [comment] 2016-10-13 13:45
@Platzer are you offline or behind a slow network connection?

**Comment by Platzer** [comment] 2016-10-13 15:11
No slow connection +20Mbit sync. I also tried it outside the corporate network in case of firewall prolem, also not working.
Yes can reproduce it with each folder. If no open files are restored it is working, if at least 1 open file is restored the editor crash.
I also set following in my setting.json:
```
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
```

**Comment by bpasero** [comment] 2016-10-13 15:26
This could be what @dbaeumer found in his setup too.

**Comment by dlong500** [comment] 2016-10-13 19:49
I realized my problem only occurred when I had a new yarn.lock file open in the editor, and this file is quite large (~6000 lines).  For anyone who doesn't know what that file is, it is produced by Yarn (a new frontend for NPM that solves the problem NPM shrinkwrap tried to solve by producing a dependency resolution file that can be committed in a source repo).  See https://yarnpkg.com

Just as with @Platzer, I can't reproduce the problem in v1.6.

**Comment by ZCShou** [comment] 2016-10-14 01:19
+1   This issue starts to display since Code - Insiders 1.7.0-insider (cf203e09145586b96497eab230253d686c2b2a2d, 2016-10-11T06:11:07.928Z)  But for me, it not displays always. 

![4](https://cloud.githubusercontent.com/assets/8591065/19333030/4bb3656c-9124-11e6-942b-ce67b22805ed.gif)

**Comment by SK83RJOSH** [comment] 2016-10-14 03:55
Same issue here, appears to happen only when I have multiple "medium" sized source files open in a particular project (400~ lines each).

**Comment by bpasero** [comment] 2016-10-14 07:42
I can reproduce by having a sufficient large enough file open right on startup with latest insiders. It seems to be an issue with node.js (https://github.com/nodejs/node/issues/7657) blocking the process while waiting for IPC messages. 

https://github.com/Microsoft/vscode/commit/aa2fd63b49bea3b5c4b5668b1079dcb235822484 resulted in larger messages being sent to the extension host right on startup and seems to now cause this more easily. I believe this could happen before already though.

**Closed** 2016-10-17 05:57 UTC
Labels: freeze-slow-crash, important
