### ISSUE TITLE
Adjusting Terminal Size Messes Up Output

### ISSUE THREAD

**Issue by zxsmjy** [microsoft/vscode#223638] opened 2024-07-25 12:15 UTC
Adjusting terminal size (by dragging the horizontal bar) messes up output, example:
This is the output before adjusting the size
![image](https://github.com/user-attachments/assets/b1dbe862-066c-45ae-a72a-b777e73b1799)

However, after dragging the horizontal bar down and up a few times, it becomes a mess with duplicated lines

![image](https://github.com/user-attachments/assets/73ccecaf-4e03-423b-ab9d-d979e2684b57)

VSCode version 1.91.1

**Comment by zxsmjy** [comment] 2024-07-25 12:26
This is apparently a similar issue as https://github.com/microsoft/vscode/issues/79816.
But after 5 years and so many versions and is still happening.

**Comment by meganrogge** [comment] 2024-07-25 16:30
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-07-25 16:30 UTC
