### ISSUE TITLE
Typing doesn't trigger snippets in JSON string

### ISSUE THREAD

**Issue by Jklein64** [microsoft/vscode#110058] opened 2020-11-06 04:46 UTC
- VSCode Version: 1.50.1
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Create an empty folder and open in with `file` > `open`
2. Open the command palette and choose `Preferences: Configure User Snippets` >  `new snippets file for <dirname>...` > enter any name and press `enter`.
3. Open the snippets config file and replace the contents with this:
```json
{
  "snip": {
    "prefix": "snip",
    "body": "snipped!"
  }
}
```
4. Open command palette again, and choose `Preferences: Open Workspace Settings (JSON)`.  Replace the contents of the settings.json file with this:
```json
{
  "editor.quickSuggestions": {
    "other": true,
    "strings": true
  }
}
```
5. Create a new JSON file and try to use the snippets inside of it.  

Expected Behavior: Typing out "snip" inside of a string should suggest the `snip` snippet and replace it with "snipped!"

Actual Behavior: Typing out "snip" outside of a JSON string literal will trigger the suggestion, though typing "snip" inside of one will not.  However, pressing `ctrl` + `space` inside of the string will suggest the snippet, and insertion with the `Insert Snippet` command works.

does not work by typing inside of the string:
<img width="284" alt="Screen Shot 2020-11-05 at 11 33 52 PM" src="https://user-images.githubusercontent.com/43863752/98326631-a7d68300-1fbf-11eb-8219-33dc371ca974.png">

works outside of string:
<img width="542" alt="Screen Shot 2020-11-05 at 11 33 38 PM" src="https://user-images.githubusercontent.com/43863752/98326630-a73dec80-1fbf-11eb-9b81-6aed3728bc8c.png">

suggests the snippet after pressing `ctrl` + `space`:
<img width="631" alt="Screen Shot 2020-11-05 at 11 34 09 PM" src="https://user-images.githubusercontent.com/43863752/98326629-a73dec80-1fbf-11eb-9797-ec0fdd3d9cd5.png">

Snippet works properly when inside of JSON string if called from command palette:
![snip](https://user-images.githubusercontent.com/43863752/98326944-6eeade00-1fc0-11eb-8cb9-a3ecee47fcb1.gif)

Everything works totally fine in YAML with no extensions though...
![snip](https://user-images.githubusercontent.com/43863752/98327180-f2a4ca80-1fc0-11eb-8e02-e3d813e340c9.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Jklein64** [comment] 2020-11-06 16:05
Just to complicate things even more, inserting snippets in JSON strings works perfectly fine in the couple of seconds it takes to set up right after refreshing the window.
![snip](https://user-images.githubusercontent.com/43863752/98387703-bb193b00-201f-11eb-8adb-b75d2b4b2e65.gif)

**Comment by aeschli** [comment] 2020-11-19 15:49
duplicate of https://github.com/microsoft/vscode/issues/32480

**Closed by aeschli** 2020-11-19 15:49 UTC
