### ISSUE TITLE
Suggest documentation formatting issue

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#26294] opened 2017-05-09 10:38 UTC
The formatting/wrapping of the documention shown in the suggest widget looks less good than in the old implementation:

new:
![image](https://cloud.githubusercontent.com/assets/172399/25846935/386cffe8-34b4-11e7-9a47-9ccfaa5b522c.png)

old:
![image](https://cloud.githubusercontent.com/assets/172399/25846955/4c8ca6c2-34b4-11e7-93b9-6e84fe81a850.png)

Notice the unnatural word wraps.

**Comment by ramya-rao-a** [comment] 2017-05-09 14:04
Duplicate of #25892
Please follow the discussion in #25892

**Closed by ramya-rao-a** 2017-05-09 14:04 UTC
Labels: editor, editor-colors
