### ISSUE TITLE
Markdown preview when zoomed does not use full window

### ISSUE THREAD

**Issue by brockallen** [Microsoft/vscode#21893] opened 2017-03-03 13:53 UTC
VSCode Version: 1.10.1 (also in previous versions for ~3+ months from my recollection)
OS Version: Win10

Steps to Reproduce:

1. Use Ctrl+ to enlarger font size
2. Open a .md file
3. Open a preview of the .md to the side (via Ctrl-K, V)
4. Notice preview does not fill whole window (see image below -- notice the scroll bars)

I'd expect the preview window to use the full space (as it does without the zoom step above)

![untitled](https://cloud.githubusercontent.com/assets/649492/23553449/c175966a-ffee-11e6-8a85-d5ae7e8248d9.png)

**Comment by mjbvz** [comment] 2017-03-03 20:50
Duplicate of #5745

**Closed by mjbvz** 2017-03-03 20:50 UTC
Labels: duplicate, webview
