### ISSUE TITLE
Issue reporter window stays black

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#116111] opened 2021-02-08 14:14 UTC
Version: 1.54.0-insider
Commit: afd102cbd2e17305a510701d7fd963ec2528e4ea
Date: 2021-02-08T05:13:33.147Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-41-generic

- Open `Help: Report Issue`
- Issue report stays empty

Looks like have an extension that has no publisher. Not clear yet how I got this.

![image](https://user-images.githubusercontent.com/6461412/107231170-4095f800-6a20-11eb-9187-b381d85d05c8.png)

**Comment by RMacfarlane** [comment] 2021-05-06 20:29
Duplicate of https://github.com/microsoft/vscode/issues/118480

**Closed by RMacfarlane** 2021-05-06 20:29 UTC
