### ISSUE TITLE
FileSystemWatcher may miss event when many changes are happening in a short order

### ISSUE THREAD

**Issue by cdietrich** [microsoft/vscode#220039] opened 2024-07-05 08:35 UTC
- VS Code Version: 1.91.0
- OS Version: MacOS Sonoma 14.5

Register a file System watcher

```
const w = vscode.workspace.createFileSystemWatcher(new vscode.RelativePattern(vscode.workspace.workspaceFolders![0],"*.txt"));
w.onDidDelete((e) => {
	console.log(e);
	counter++;
});
```

do a deletion of a huge number of files (would also happen on creation)
then the watch may omit some changes

(when used together with a language server/vscode-language-client this will be bad a the state in the server might become out of sync)

here is an attempt to write a reproducing test

https://github.com/cdietrich/fs-watcher-bug/blob/main/src/test/extension.test.ts

originally reported as https://github.com/microsoft/vscode-languageserver-node/issues/1503

cc @dbaeumer

**Comment by ocallesp** [comment] 2024-07-25 20:17
This bug is also affecting the Test Explorer in C# DevKit (https://github.com/microsoft/vscode-dotnettools/issues/996) causing to miss some test methods.

@bpasero is there any milestone for this bug ?

**Comment by bpasero** [comment] 2024-08-05 10:45
Would be great to distill a reproducible case using https://github.com/parcel-bundler/watcher, which is the file watcher we leverage so that it can be reported upstream, if it turns out to be.

**Comment by cdietrich** [comment] 2024-08-08 18:33
@bpasero maybe https://github.com/cdietrich/parcel-watcher-bug helps

**Comment by bpasero** [comment] 2024-08-09 04:08
@cdietrich here is my output on macOS:

```
~/Desktop/parcel-watcher-bug> node index.js
1001
counter 1000
1
~/Desktop/parcel-watcher-bug> 
```

What do you get?

We use the standard backend for parcel watcher, so it would be `inotify` on Linux.

**Comment by cdietrich** [comment] 2024-08-09 05:57
if i run multiple times it will say

counter 567
or counter 998
or counter 867

**Comment by cdietrich** [comment] 2024-08-09 06:03
from my m2 pro

```
while ./node_modules/.bin/ts-node index.ts; do :; done
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 779
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 1000
1
1001
counter 593
1
1001
counter 1000
1
1001
```

on my private m1 air much more often.

**Comment by bpasero** [comment] 2024-08-09 06:15
@cdietrich got it, I would think you can report this with your repro at https://github.com/parcel-bundler/watcher

**Comment by cdietrich** [comment] 2024-08-09 07:33
done https://github.com/parcel-bundler/watcher/issues/183

**Comment by bpasero** [comment] 2024-08-09 07:41
Thanks a ton for the issue and repro, thats helpful, I am going ahead and close this as upstream. I am monitoring the parcel repository for fixes.

**Comment by ocallesp** [comment] 2024-08-12 02:00
Is the bug in FileSystemWatcher related to parcel-bundler/watcher?

Why was this GitHub issue closed? It seems that the bug might not have been transitioned appropriately. There’s a concern that the issue with FileSystemWatcher could be overlooked if it’s not being actively monitored.

**Comment by bpasero** [comment] 2024-08-12 17:33
Re-opening to reference a partner issue: https://github.com/microsoft/vscode-dotnettools/issues/996

**Closed** 2024-08-20 11:25 UTC
Labels: info-needed, upstream, file-watcher

**Comment by dbaeumer** [comment] 2024-12-12 13:51
From https://github.com/microsoft/vscode-languageserver-node/issues/1503

A test case with VS Code API that fails:

```ts
import * as assert from 'assert';

// You can import and use all API from the 'vscode' module
// as well as import your extension to test it
import * as vscode from 'vscode';

suite('Extension Test Suite', () => {
	vscode.window.showInformationMessage('Start all tests.');

	test('Sample test', async () => {
		const uri = vscode.workspace.workspaceFolders![0].uri;
		const wse = new vscode.WorkspaceEdit();
		for (let i = 0; i < 1000; i++) {
			wse.createFile(vscode.Uri.joinPath(uri, `test_${i}.txt`));
		}
		await vscode.workspace.applyEdit(wse);
		
		const relativePattern = new vscode.RelativePattern(uri, "*.txt");
		const files = await vscode.workspace.findFiles(relativePattern);
		assert.strictEqual(files.length, 1000);

		const watcher = vscode.workspace.createFileSystemWatcher(relativePattern);
		
		let counter = 0;
		watcher.onDidDelete((e) => {
			console.log(e);
			counter++;
		});
		
		const deleteWse = new vscode.WorkspaceEdit();
		for (let i = 0; i < 1000; i++) {
			deleteWse.deleteFile(vscode.Uri.joinPath(uri, `test_${i}.txt`));
		}	
		await vscode.workspace.applyEdit(deleteWse);
		
		const files2 = await vscode.workspace.findFiles("*.txt");
		assert.strictEqual(files2.length, 0);
		watcher.dispose();

		assert.strictEqual(1000, counter);
	});
});
```
