### ISSUE TITLE
 Cannot read property '_acceptIsDirty' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5484] opened 2016-04-19 08:11 UTC
Issue Id: <b>25627564-167f-0fb7-fa66-53028cfa6eb6</b><br /><br />*Versions* <br />- 1.0.0-insider<br />-  fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8<br />*Stack* <br />TypeError: Cannot read property '_acceptIsDirty' of undefined<br />    at e._acceptModelReverted (\out\vs\workbench\node\pluginHostProcess.js:18:26765) <no sourcemaps><br />    at t.e.handle (\out\vs\workbench\node\pluginHostProcess.js:15:12835) <no sourcemaps><br />    at c (\out\vs\workbench\node\pluginHostProcess.js:11:16222) <no sourcemaps><br />    at h (\out\vs\workbench\node\pluginHostProcess.js:11:16882) <no sourcemaps><br />    at doNTCallback0 (node.js:420:9)<br />    at process._tickCallback (node.js:349:13)<br />

**Comment by jrieken** [comment] 2016-04-19 09:33
duplicate of #5016

**Closed by jrieken** 2016-04-19 09:33 UTC
Labels: bug, error-telemetry
