### ISSUE TITLE
Editor/Tab does not close when tab bar hidden

### ISSUE THREAD

**Issue by ussfranck** [microsoft/vscode#213213] opened 2024-05-22 08:21 UTC
Type: <b>Bug</b>

# Problem closing tabs and home page with custom interface configuration

I've configured Visual Studio Code to be as simple as possible for me. Here are the changes I've made:

- I changed the position of the activity bar to "bottom".
- I've hidden the tab bar.
- I set the zoom level to "0.3".
- I've hidden the tab display.
- I've changed the position of the sidebar.

However, I have a persistent problem: every time I open VSCode and open tabs for coding, I can't close them without reloading the window. What's more, even without opening a project, to close the home page that appears by default on startup, I also have to reload the window. This behavior is really frustrating.

## Steps to Reproduce

1. **Configure VSCode**:
   - Change position of activity bar to "bottom".
   - Hide tab bar.
   - Set zoom level to "0.3".
   - Hide tab display.
   - Change sidebar position.
2. **Open VSCode**.
3. **Open tabs for coding**.
4. **Try to close tabs**.

## Expected Results
Tabs should close normally without requiring a window reload.

## Actual Results
Tabs won't close unless the window is reloaded. Similarly, the home page that appears by default at startup cannot be closed without reloading the window.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.64GB free)|
|Process Argv|--crash-reporter-id a096bc6a-60f4-4c68-a8b1-c74d75913966|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
codegeex|AMi|2.9.0
architecture-view-nestjs|arc|0.7.0
vscode-tailwindcss|bra|0.10.5
dart-code|Dar|3.88.1
flutter|Dar|3.88.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.0.4
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
headwind|hey|1.7.0
vscode-typescript-next|ms-|5.5.20240505
material-icon-theme|PKi|5.3.0
prisma|Pri|5.14.0
vscode-thunder-client|ran|2.23.8
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1958

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvptcf:31049071
a69g1124:31046351
dvdeprecationcf:31052040
pythonprc:31047982
dwnewjupytercf:31046870
fa862199:31048878

```

</details>

**Comment by TylerLeonhardt** [comment] 2024-05-29 16:47
I can't reproduce this. Can you please provide a minimum repro with a `settings.json` file?

**Comment by ussfranck** [comment] 2024-05-30 04:59
Hey James🖐️, Yeah no issues. there y go:
Ok, paste this minimal config into y vscode, quit & reopen vscode, load a project or try closing the "welcome" tab, and...the problem should go away.

Note: On my windows i've a custom display level (110%) that's not caused by this as i've also checked this side, James. Thank y!
________________________________

**Comment by TylerLeonhardt** [comment] 2024-05-30 13:58
Did you attach a file? I'm not seeing it here? Feel free to just paste the text of the minimum repro too.

**Comment by ussfranck** [comment] 2024-05-31 07:58
{
    "workbench.colorTheme": "Default Dark+",
    "workbench.activityBar.location": "top", 
    "window.zoomLevel": 0.2, // important change
    "[typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.tabSize": 2,
    "editor.cursorBlinking": "expand",
    "editor.scrollbar.horizontalScrollbarSize": 8,
    "editor.scrollbar.verticalScrollbarSize": 8,
    "workbench.editor.showTabs": "none" // important change
}

**Comment by TylerLeonhardt** [comment] 2024-05-31 15:42
https://github.com/microsoft/vscode/assets/2644648/caed9551-4bc1-45f8-bb5d-de556a8bcaf6

Still can't repro... here's what I'm doing:
1. pasting your settings file into settings.json
2. saving it
3. opening new editors
4. closing new editors (both with the keybinding and the `x`)

No reload. Are these steps correct for you?

Also, how are you closing the tabs? With the keybinding? If so, double check that the correct keybinding is being fired.

**Comment by ussfranck** [comment] 2024-06-02 19:06
Ok, the keybinding is correct, reloading  is only necessary when the problem actually occurs, the steps are correct. Watch this video

https://github.com/microsoft/vscode/assets/151151525/2eb4d91e-a092-4ec6-bb02-555b512ac766

**Comment by TylerLeonhardt** [comment] 2024-06-03 03:09
I can repro! Thanks! I think this goes to @bpasero 

Steps:
* Open workspace-less VS Code
* Set these settings:
```json
{
    "workbench.colorTheme": "Default Dark+",
    "workbench.activityBar.location": "top",
    "window.zoomLevel": 0.2, // important change
    "editor.tabSize": 2,
    "editor.cursorBlinking": "expand",
    "editor.scrollbar.horizontalScrollbarSize": 8,
    "editor.scrollbar.verticalScrollbarSize": 8,
    "workbench.editor.showTabs": "none" // important change
}
```
* Open a workspace
* 🐛 the `x` button in the top right doesn't close any windows. Similarly, the "Split Editor Right" doesn't work either

**Comment by benibenj** [comment] 2024-06-07 23:41
Thanks for the repro steps. I was able to fix the bug

**Comment by eleanorjboyd** [comment] 2024-06-25 18:21
set those settings on my mac and I no longer see the tab to close the editor window:
<img width="1546" alt="Screenshot 2024-06-25 at 11 20 36 AM" src="https://github.com/microsoft/vscode/assets/26030610/866db6cf-103d-4549-a54a-cdc169c4992c">


this is how it normally looks:
<img width="1470" alt="Screenshot 2024-06-25 at 11 21 27 AM" src="https://github.com/microsoft/vscode/assets/26030610/741eb39d-1d4f-45eb-92e5-736a54db6018">

**Comment by benibenj** [comment] 2024-06-26 07:30
@eleanorjboyd The UI looks correct. The tab bar needs to be hidden. When following Tyler's repro steps here: https://github.com/microsoft/vscode/issues/213213#issuecomment-2144196057 , You should then be able to close the current editor with the `x` action in the title bar on the right side

**Closed by benibenj** 2024-06-26 07:30 UTC
Labels: bug, workbench-tabs, workbench-editors, confirmed
