### ISSUE TITLE
HTML: comments inside a script tag no longer sensitive to script language

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12969] opened 2016-09-29 04:50 UTC
- VSCode Version: Insiders
- OS Version: Windows 10

Regarding test plan item #12100

Steps to Reproduce:

1. Select some JavaScript code inside of a `<script>` block in an HTML file*.
2. Use the keyboard shortcut to "Add a line comment" or run the command from the command palette.
3. Note that in the latest Insiders build, it no longer uses `//`` JavaScript-valid comments; instead, it now uses `` comments.

**Current Insiders**
<img width="430" alt="screen shot 2016-09-28 at 9 44 55 pm" src="https://cloud.githubusercontent.com/assets/11839736/18941370/70475cea-85c5-11e6-8860-325e5320d70e.png">

**Current Stable**
<img width="452" alt="screen shot 2016-09-28 at 9 44 18 pm" src="https://cloud.githubusercontent.com/assets/11839736/18941369/6ec87bc4-85c5-11e6-8e35-63388192d5a2.png">

 *I'm not sure, but this may apply to Handlebars and Razor also.

**Comment by egamma** [comment] 2016-09-30 08:43
HTML has been extracted into a separate language server and this functionality has been lost. Moving to October.

We should document this limitation in the release notes.

**Comment by felixfbecker** [comment] 2016-10-01 08:58
https://github.com/Microsoft/vscode/issues/1751?

**Comment by aeschli** [comment] 2016-10-11 13:21
duplicate of #11081

**Closed by aeschli** 2016-10-11 13:21 UTC
Labels: bug, debt, html
