### ISSUE TITLE
Can't copy file name text when rename image file

### ISSUE THREAD

**Issue by shadowdreamer** [microsoft/vscode#126458] opened 2021-06-16 09:14 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1.open a folder with image,
2.choose a image file press `f2` , press `ctrl + c`  to copy file name.

can't copy the file name,already disabled all extensions. 

i fall back to ver 1.56, it's ok to copy.

**Comment by TNTrocket** [comment] 2021-06-22 02:52
same problem

**Comment by isidorn** [comment] 2021-06-22 18:39
The issue here is that for image files it seems like the Cmd/Ctrl+C gets bind to another command. And thus the native copy is not working.
Assigning first to @loganrosen due to this custom editor work which is my first suspect for potentially breaking this previous milestone.

**Comment by lramos15** [comment] 2021-06-22 18:50
Poor @loganrosen always getting accidentally mentioned because of me :p.

What does F2 do? As I can copy the image file names without issue but clicking F2 doesn't seem to do anything for me.

**Comment by fireattack** [comment] 2021-06-22 20:14
> Poor @loganrosen always getting accidentally mentioned because of me :p.
> 
> What does F2 do? As I can copy the image file names without issue but clicking F2 doesn't seem to do anything for me.

F2 means "rename" on Windows.

**Comment by fireattack** [comment] 2021-06-22 20:24
To clarify a little bit. 

As isidorn said, it's not strictly "can't copy filename with image", but that "when you open a image file at the active tab, ctrl+C simply does not work anywhere".

In most of cases this will only happen if you're renaming/copying the image file itself, since most of people (including OP and me) do the following steps when wanting to copy a file:
1. click the file that I want to rename (which will inevitably put it into the active tab)
2. Hit F2 (Windows)
3. Press Ctrl+C to copy the name

Which triggers this bug reliably. 

But you can simply:
1. Open any image in active tab. 
2. Right click any file in the filelist and choose rename (this way, the active tab won't change).
3. Try to press Ctrl+C to copy the name

Expected: the filename is copied.
Observed: the filename is not copied.

**Comment by lramos15** [comment] 2021-06-22 20:25
@mjbvz I believe this might be a regression from you adding cut/copy/paste support into webviews.

**Comment by klueless-io** [comment] 2021-06-24 01:25
This issue happens on Mac as well, but instead of pressing F2 (windows only) I do the following

Click on image file with mouse
or
Command+Shift+E to focus on solution explorer
Navigate to image file


Then press enter, this puts file name into edit mode (similar to F2 on windows)
Press Command+C to copy file name

Go to another text window and press Command+V to paste
and the just selected + copied text is NOT pasted, only previous copy is pasted.

So I have the exact same issues of copy keybinding not working when looking at an image on the Mac

**Comment by isidorn** [comment] 2021-06-29 11:12
@lramos15 is @mjbvz on vacation?
I am getting more duplicates of this issue, is it possible to look into it this week? Should we assign to June?

**Comment by lramos15** [comment] 2021-06-29 13:35
> @lramos15 is @mjbvz on vacation?
> I am getting more duplicates of this issue, is it possible to look into it this week? Should we assign to June?

He was on vacation, but I believe he should be back now. I'm not super familiar with the webview code we can assign to June and mark as important as It seems to annoy a lot of users.

**Comment by bodydisplaynone** [comment] 2021-06-30 07:27
As part of the insider program, my machine updated to Win 11 insider edition in the evening and the problem seems gone.

I can't clearly tell when it started working again but it was definitely after receiving some updates and restarting a few times. I don't remember if I used it out of pure habit and not even noticing while still under Win 10.

![image](https://user-images.githubusercontent.com/22660372/123919117-e2dd5a80-d984-11eb-9877-e3f5a790d852.png)
![image](https://user-images.githubusercontent.com/22660372/123919172-f688c100-d984-11eb-8dfb-f9e10a20bcfe.png)

**Closed** 2021-07-08 00:29 UTC
Labels: bug, important, regression, webview
