### ISSUE TITLE
XML fromating broken

### ISSUE THREAD

**Issue by prochan2** [Microsoft/vscode#702] opened 2015-11-26 10:19 UTC
![image](https://cloud.githubusercontent.com/assets/5324719/11420609/7ed0a9ac-942f-11e5-8cff-255704a1138d.png)

(The string is all blue, just the quotes are brown.)

**Comment by aeschli** [comment] 2015-11-27 15:58
duplicate of #23

**Closed by aeschli** 2015-11-27 15:58 UTC
