### ISSUE TITLE
Syntax Highlighting has stopped working across all files and extensions

### ISSUE THREAD

**Issue by alexander-novo** [microsoft/vscode#133109] opened 2021-09-14 17:08 UTC
Issue Type: <b>Bug</b>

This happened after I switched the python linter to pylint using the Python extension, VS Code asked me to install it, and I clicked the button to install it (after which it still complained in the output window that pylint was not installed). I noticed that the syntax highlighting had stopped working on my .py files, and after opening other types of files in different workspaces, all of my syntax highlighting has stopped.

The Log (Windows) view has this to say:
```
[2021-09-14 09:46:40.154] [renderer1] [error] Invalid or unexpected token: C:\Users\bleac\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-textmate\release\main.js:2
����
^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at wrapSafe (internal/modules/cjs/loader.js:1021:15)
    at Module._compile (internal/modules/cjs/loader.js:1081:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.t._load (electron/js2c/renderer_init.js:69:307)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:101)
    at r.load (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:3:11082)
    at r.load (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:3:10249)
    at l (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:10308)
    at Object.errorback (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:10429)
    at r.triggerErrorback (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:3:10613)
    at vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:3:10319
    at r.load (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:3:11099)
    at r.load (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:3:10249)
    at l (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:10308)
    at r._loadModule (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:10438)
    at r._resolve (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:6142)
    at r._relativeRequire (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:6828)
    at n (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:9414)
    at vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1916:28461
    at new Promise (<anonymous>)
    at i._getOrCreateGrammarFactory (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1916:28441)
    at vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1916:29329
    at i._registerDefinitionIfAvailable (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1916:29749)
    at l._handler (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1916:27052)
    at l._handle (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1476:16692)
    at l.acceptUsers (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1476:16596)
    at Function._handleExtensionPoint (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2872:151628)
    at cl._doHandleExtensionPoints (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2872:150747)
    at cl._startLocalExtensionHost (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2878:9281)
    at async cl._scanAndHandleExtensions (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2878:8243)
    at async cl._initialize (vscode-file://vscode-app/c:/Users/bleac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2872:145188)
```

After opening up the main.js file in question, I find a bunch of broken characters at the bottom:
```
...
function n(r){if(t[r])return t[r].exports;var i=t[r]={exports:{}};return e[r].call(i.exports,i,i.exports,n),i.exports}(787)})()}));//# sourceMappin
����
�
�
��	�	�
��	�	�	�
�	����	�	�	�
�	�	�	�
�
�
�
�
�	�	�	�
```

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (35.64GB free)|
|Process Argv|C:\\Users\\bleac\\Documents\\School\\CS 422\\Project1 --crash-reporter-id 0439b5de-74b6-4f22-9fa6-ddb61441b3d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cudacpp|kri|0.1.1
gnuplot|mam|1.0.5
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
hexeditor|ms-|1.8.2
java|red|0.81.0
vscodeintellicode|Vis|1.2.14
vscode-maven|vsc|0.33.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by alexander-novo** [comment] 2021-09-14 17:15
I ended up running the installer to try and fix it. The installer detected multiple VS Code processes that were open, despite no windows being open on my desktop. After closing the processes through task manager and re-installing, the issue was fixed.

**Comment by alexdima** [comment] 2021-09-27 07:31
It looks like the `.asar` file became corrupted on disk.

**Comment by joaomoreno** [comment] 2021-09-27 15:46
Does this reproduce if you reinstall VS Code?

**Comment by alexdima** [comment] 2021-09-27 16:26
@joaomoreno I think it did:

> After closing the processes through task manager and re-installing, the issue was fixed.

**Comment by alexander-novo** [comment] 2021-09-27 16:56
To be clear, the issue did not reproduce after re-installing.

**Comment by joaomoreno** [comment] 2021-09-29 07:43
Interesting. Unsure why that `.asar` file got corrupted in your system, but it could literally be any piece of software on your system causing the issue. It could even be hardware failure. Closing this for now as you seem to be unblocked.

**Closed by joaomoreno** 2021-09-29 07:43 UTC
Labels: needs more info
