### ISSUE TITLE
ES6 String Templates syntax highlighting

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#1339] opened 2015-12-15 15:48 UTC
1) Create a new JS file in a project set to ES6
2) Add the following code
var mytext = \`some ES6 \'text\'\`;
// this comment is brown
console.log('the console log is brown but this string inside it is coloured!');

You will see that everything after the first \' is brown. I am aware that there is no need to use the backslash to escape the ' character, but as far as I am aware it is also not invalid javascript. And if it is invalid, I would expect some other kind of error to indicate that it is invalid.

**Comment by massimocode** [comment] 2015-12-15 15:55
Sorry for some additional information, it seems that the real issue as that the backtick ` is not being recognised as a string character (i.e. like single quote and double quote)

**Comment by massimocode** [comment] 2015-12-15 17:12
Sorry accidentally closed issue. I've updated the initial comment with a nicer description etc

**Comment by aeschli** [comment] 2015-12-16 08:52
duplicate of #133

**Closed by aeschli** 2015-12-16 08:52 UTC
Labels: bug, js
