### ISSUE TITLE
Cannot use multi window when 'prefer tabs' option (only in Mac) in turned on 

### ISSUE THREAD

**Issue by harryi3t** [Microsoft/vscode#44201] opened 2018-02-22 13:05 UTC
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra, 10.13.2

Steps to Reproduce:

1. Turn on "Prefer tabs when opening documents"
![screenshot_22_02_18__6_21_pm](https://user-images.githubusercontent.com/5207331/36539538-3751a1e0-17fd-11e8-818c-a78f2645507e.png)

2. Open a folder in VScode. (`code /path/to/folder1`)
![screenshot_22_02_18__6_23_pm](https://user-images.githubusercontent.com/5207331/36539653-8174f790-17fd-11e8-8d14-97492474d104.png)

3. Try opening another window. All of the following ways fails
 - from command-line (`code /path/to/another/folder`)
 - from menu -> File -> New Window (Or Shortcut)
 - Ctrl-R -> Choose a recent project
![screenshot_22_02_18__6_26_pm](https://user-images.githubusercontent.com/5207331/36539793-ff5abdd4-17fd-11e8-9cae-69b2268b9d07.png)

Note: When I quit the app, for a split second I see the old window (folder1) which disappeared before.
![vscode-bug](https://user-images.githubusercontent.com/5207331/36540052-ed9c549e-17fe-11e8-8f4b-ab4749549b77.gif)

__Does this issue occurs when all extensions are disabled?__: Yes

**Comment by bpasero** [comment] 2018-02-22 14:21
This seems to be a duplicate of https://github.com/Microsoft/vscode/issues/35361

On top of that, you can disable native tabs via: `"window.nativeTabs": false`

**Closed by bpasero** 2018-02-22 14:21 UTC
