### ISSUE TITLE
[Insiders] "Start Debugging" asks to choose environment when triggered from main menu

### ISSUE THREAD

**Issue by winzig** [Microsoft/vscode#64450] opened 2018-12-05 20:22 UTC
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.30.0-insider (85f805acf9436381b878cab5ab6c5146beec7893, 2018-12-05T12:13:44.894Z)
OS version: Darwin x64 18.2.0

Suddenly now when I try to start debugging on my .net core web app, it prompts me to choose my environment. Previously it would just start debugging based on my launch.json. I chose .NET Core from the list, but nothing further happened. 

If I instead click on the play button on the bottom status bar that says ".NET Core Launch (web)", debugging starts normally. I am not sure if this is an issue in vscode-insiders, or in the c# extension, since if I disable the extension, debugging obviously cannot happen.

**Comment by weinand** [comment] 2018-12-06 08:58
@isidorn please investigate because there were changes in that area.

**Comment by isidorn** [comment] 2018-12-06 09:00
@weinand sure, that is why I assigned it to november

**Comment by isidorn** [comment] 2018-12-06 13:39
@winzig I can not reproduce this. With the C# sample console repository (`dotnet new console`). I have attached a gif, let me know what you are doing differently than me. Also can you reproduce if you disable all other extensions except C#? If yes can you reproduce with the `dotnet new console` sample repository. If not can you please share your repository so we investigate more?

@gregg-miskelly did you change something in the C# extension which might cause this?

![c](https://user-images.githubusercontent.com/1926584/49587582-8fd5cf00-f964-11e8-8d1c-c8fde6c7b387.gif)

**Comment by gregg-miskelly** [comment] 2018-12-06 17:02
No, we haven't released any updates to the C# extension in a few weeks.

**Comment by jtsom** [comment] 2018-12-12 01:57
Per my report #64828 clicking the run button at the top of the debug pane is not an issue - tapping the run button in the Touch Bar shows this problem - the Choose Environment menu, then nothing.

**Comment by winzig** [comment] 2018-12-12 03:02
Sorry guys, I've been slammed at work since opening this issue. As @jtsom indicated, the way you're doing it in the gif works for me as well, but if I use the `Debug > Start Debugging` menu, I get prompted to Choose Environment. 

Incidentally, hitting F5 (which is mapped to the same menu command) works fine.

**Comment by isidorn** [comment] 2018-12-12 10:21
@winzig thanks for providing more details. This is a regression and we will push a fix for this.
@RMacfarlane this is introduced with our change of the debugStart actions for the ProcessExplorer. I should have caught this when I reviewed your PR. I have created a follow up item for something that I missed in the PR https://github.com/Microsoft/vscode/issues/64858

**Comment by roblourens** [comment] 2018-12-12 22:12
@isidorn I've reopened these issues because they are not yet fixed in the milestone to which they are assigned. I think they should only be closed when fixed and ready for verification, etc. Anyway feel free to merge the PRs now.

**Comment by isidorn** [comment] 2018-12-13 09:49
@roblourens thanks. I have assigned this to the November 2018 Recovery

**Closed by isidorn** 2018-12-13 09:49 UTC
Labels: bug, candidate, debug
