### ISSUE TITLE
PowerShell overrides any default terminal on the first run

### ISSUE THREAD

**Issue by ssstain** [microsoft/vscode#132402] opened 2021-09-05 19:30 UTC
Issue Type: <b>Bug</b>

When you start a Python project in a newly created virtual environment the VS Code may ask you to install missing linters and other dependencies. If you confirm the installation, the terminal window popups with the powershell, though you may have your default terminal set to cmd in Windows (or Clink - http://mridgers.github.io/clink, in my case).
Powershell has no perms to run scripts on my system, so there is a the problem with activating a virtual environment and all the installed stuff may go to a wrong one.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by ssstain** [comment] 2021-09-05 19:47
Should this on be closed as a duplicate of #132150

**Comment by gjsjohnmurray** [comment] 2021-09-05 20:04
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-05 20:04 UTC
Labels: *duplicate, new release
