### ISSUE TITLE
[css] /deep/ selector is still broken (scss)

### ISSUE THREAD

**Issue by tx8821** [Microsoft/vscode#26004] opened 2017-05-05 08:17 UTC
- VSCode Version: 1.12.1
- OS Version: Win 10

Steps to Reproduce:

Interestingly the issue at https://github.com/Microsoft/vscode/issues/7002 is considered fixed since 1.12, but apparently it has not been fixed, as I just updated to latest version 1.12.1, and /deep/ selector in scss is still not recognized by the IDE.

This screenshot shows it all:

![deepbroken](https://cloud.githubusercontent.com/assets/22138773/25738060/16833e22-318c-11e7-9b88-b6273f435354.png)
![deepbroken2](https://cloud.githubusercontent.com/assets/22138773/25738131/796ffffc-318c-11e7-9ada-bf0f1b898474.png)

Those are ordinary SCSS files. Angular-CLI generated project (latest version). Please fix this.

#7002

**Comment by aeschli** [comment] 2017-05-05 10:45
Please paste your code sample, thanks!

**Comment by aeschli** [comment] 2017-05-05 11:00
The problem is the lack of spec here. Can someone confirm that `>>>` or `/deep/` followed by `>` is a valid syntax?

**Comment by tx8821** [comment] 2017-05-05 11:31
@aeschli It seems that direct child selector (`>`) is causing the problem indeed. Without it, there is no error as far as I can test. As for whether the `/deep/` followed by `>` syntax is valid, I'd say that it's totally valid because valid css is generated by scss parser, and not only it is semantically correct, it is quite commonly used and pretty hard to emulate otherwise.

**Comment by leonadler** [comment] 2017-05-05 13:32
From a logical standpoint, `parentelement > childelement` makes sense,  
while `parentelement /deep/ > childelement` does not.
What should the direct child selector of the second example refer to? Direct child of what?
Compared to CSS without shadow DOM, this makes sense: `> element { }` is not valid CSS (again - direct child of what?), `* > element { }` is valid CSS.

Consider using either
1. `parentelement /deep/ * > childelement`, which carries the semantics "somewhere within parent, find a childelement which is a direct ancestor of any element" or
2. `parentelement::shadow > childelement` which means "inside the shadow dom of the parent element, find a direct ancestor which is a `childelement`.
3. `parentelement /deep/ childelement` which means "a childelement anywhere underneath parentelement"

**Comment by tx8821** [comment] 2017-05-05 19:31
@leonadler I don't want to sound rude, but... please don't talk and give advice on the subject that you don't understand. The particular use case I'm facing in my project for example, is an Angular application, that emulates the shadow DOM for its components and `:host /deep/ > child` is used to apply styling to the direct child component that is transcluded inside parent dynamically. Shortly, there is a valid, frequent, and hard-to-workaround use case, at least for Angular applications. I'm sure there are other uses, but I think the single example is enough. When the platform uses the particular functionality, compiles it perfectly, and at the same time IDE has a syntax highlighting problem - that is clearly an IDE issue, period.

**Comment by epicgirl1998** [comment] 2017-05-06 11:37
> The particular use case I'm facing in my project for example, is an Angular application, that emulates the shadow DOM for its components and `:host /deep/ > child` is used to apply styling to the direct child component that is transcluded inside parent dynamically.

according to all i know about css selectors, `:host /deep/ > child` is invalid in the same way as `:host > > child` is

are you sure the style is actually being applied? what does the selector look like in your browser's style inspector?

> Angular application, that emulates the shadow DOM for its components

if it's only emulating the shadow dom and not actually using it (for older browsers i assume), then it probably has to convert `:host` and `/deep/` into something that works without actual shadow dom, so maybe a transformation like that is erroneously turning the selector into a valid one?

disclaimer: i have not used angular or scss

**Comment by aeschli** [comment] 2017-05-08 07:08
Thanks a lot for the information, @leonadler! 
Closing the issue until we get a prove that `/deep/ >` is valid syntax.

**Closed by aeschli** 2017-05-08 07:08 UTC

**Comment by leonadler** [comment] 2017-05-08 17:28
> The particular use case I'm facing in my project for example, is an Angular application, that emulates the shadow DOM for its components and :host /deep/ > child is used to apply styling to the direct child component that is transcluded inside parent dynamically.

Yeah, I know, I am working with Angular2&4 for almost two years. If you would have bothered to read or try my answer instead of trying to belittle me, you would see that `:host::shadow-root > element` does _exactly_ what you are trying to do. `/deep/ > element` just makes no sense.

> I don't want to sound rude, but...

Then don't be rude?

---

### Answer for future readers

Assuming this HTML with shadow DOM (native or emulated, does not matter):

```html
<my-component>
    ::shadow-root
        <p>a</p>
        <div>
            <p>b</b>
        </div>
</my-component>
```

To select the paragraph containing "a", not the one containing "b":

```css
my-component::shadow-root > p {
    // style declarations
}
```

---

A scenario where `parent /deep/ child` (or `parent >>> child`) makes sense:

```html
<parent-component>
    ::shadow-root
        <div>a</div>
        <child-component>
            ::shadow-root
                <div>b</div>
        </child-component>
        <child-component>
            ::shadow-root
                <div>c</div>
        </child-component>
        <nested-component>
            ::shadow-root
                <div>d</div>
                <child-component>
                    ::shadow-root
                        <div>e</div>
                </child-component>
        </nested-component>
</parent-component>
```

With this HTML structure, `parent-component /deep/ div` (or `parent-component >>> div`) will select _all_ divs in the example.

**Comment by emilio-martinez** [comment] 2017-05-16 15:17
Agreed. `/deep/ >` doesn't make sense, even for transcluded content. I'm actually surprised that it works. I wonder if it's, more than anything, a side effect of how Angular parses the css for emulated view encapsulation.
