### ISSUE TITLE
TernarySearchTree: Cannot read property '1' of undefined #138284 (random)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#204109] opened 2024-02-02 10:29 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=254956&view=logs&j=b599f925-57da-5b26-3abb-63aa7efd9fc6&t=8cfaeab5-d16b-5ade-99ec-032efde9358d&l=12453

```
1) Ternary Search Tree
       TernarySearchTree: Cannot read property '1' of undefined #138284 (random):

      
      + expected - actual


  RangeError: Invalid array length
      at Array.push (<anonymous>)
      at $bi.e (file:///D:/a/_work/1/s/out-build/vs/base/common/ternarySearchTree.js:450:27)
      at $bi.delete (file:///D:/a/_work/1/s/out-build/vs/base/common/ternarySearchTree.js:431:25)
      at Context.<anonymous> (file:///D:/a/_work/1/s/out-build/vs/base/test/common/ternarySearchtree.test.js:433:31)
```

**Comment by jrieken** [comment] 2024-12-10 11:04
/duplicate of https://github.com/microsoft/vscode/issues/227147

**Closed by jrieken** 2024-12-10 11:04 UTC
Labels: unit-test-failure
