### ISSUE TITLE
Cannot read property 'scheme' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4488] opened 2016-03-21 07:02 UTC
Got this by running "out of source" with latest clicking through some TS files of the workbench (within the vs/workbench/api folder):

```
Cannot read property 'scheme' of undefined: TypeError: Cannot read property 'scheme' of undefined
    at TypeScriptServiceClient.asAbsolutePath (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/typescriptServiceClient.js:211:21)
    at BufferSyncSupport.onDidRemoveDocument (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/features/bufferSyncSupport.js:110:36)
    at CallbackList.invoke (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:57:43)
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:84:40)
    at ExtHostModelService._acceptModelRemoved (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostDocuments.js:157:51)
    at ExtHostThreadService.AbstractThreadService.handle (/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/thread/common/abstractThreadService.js:72:27)
    at invokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/extensions/common/ipcRemoteCom.js:127:53)
    at receiveOneMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/extensions/common/ipcRemoteCom.js:84:36)
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

**Comment by dbaeumer** [comment] 2016-03-21 08:12
@jrieken I received a document remove event with a document set to undefined. Moving to you since the remove document should IMO contain a valid document object. Marking as important since you changed something in that area on Friday and I suspect a regression here.

**Comment by dbaeumer** [comment] 2016-03-21 08:12
Setting to mark to see if this is a regression. @jrieken feel free to un-label.

**Comment by jrieken** [comment] 2016-03-21 08:32
@alexandrudima It seems we have a document without an uri...

**Comment by alexandrudima** [comment] 2016-03-21 10:51
@bpasero Any repro steps? Did you have extensions installed that provide documents?

**Comment by alexandrudima** [comment] 2016-03-21 10:56
@jrieken This is most weird.
* the `_uri` on `ExtHostDocumentData` is set only in the ctor.
* it is accessed in `_acceptModelAdd` so we know that this document was not created with an undefined uri:
```
let data = new ExtHostDocumentData(this._proxy, initData.url, initData.value.lines, initData.value.EOL, initData.modeId, initData.versionId, initData.isDirty);
		let key = data.document.uri.toString();
```

* the `_acceptModelRemoved` only works if there is an `ExtHostDocumentData`

**Comment by jrieken** [comment] 2016-03-21 11:03
yeah, that's why I am so puzzled

**Comment by alexandrudima** [comment] 2016-03-21 11:07
The only funny business in there is that the document is returned via `weak`.get. I am not sure... maybe something is broken inside `weak` ?

**Comment by alexandrudima** [comment] 2016-03-21 11:10
Maybe it is near death (whatever that means) and accessing any methods/members on the proxy returns undefined?

https://github.com/TooTallNate/node-weak/blob/master/src/weakref.cc#L280

```
	get isDocumentReferenced(): boolean {
		return this._documentRef && !weak.isDead(this._documentRef);
	}
```

**Comment by alexandrudima** [comment] 2016-03-21 11:12
Looks like if the proxy is dead, the return value for a getter is undefined:

https://github.com/TooTallNate/node-weak/blob/master/src/weakref.cc#L74

```
NAN_PROPERTY_GETTER(WeakNamedPropertyGetter) {
  UNWRAP
  info.GetReturnValue().Set(dead ? Local<Value>() : Nan::Get(obj, property).ToLocalChecked());
}
```

I think `Local<Value>()` is undefined.

**Comment by alexandrudima** [comment] 2016-03-21 11:16
Their example at https://github.com/TooTallNate/node-weak#example mentions that a GC`d proxy acts as an empty object: 
```
// `callback()` above is called, and `ref` now acts like an empty object.
typeof ref.foo === 'undefined'
```

which is sort of what we're seeing with `document.uri`

**Comment by alexandrudima** [comment] 2016-03-21 11:19
@jrieken 

I think there could be a theoretical "data race" with the GC in this code:

If a Garbage Collection runs between the if stmt and the return value, then `_documentRef` is dead and we don't create a new one.

```
	get document(): vscode.TextDocument {
		// dereferences or creates the actual document for this
		// document data. keeps a weak reference only such that
		// we later when a document isn't needed anymore

		if (!this.isDocumentReferenced) {
			const data = this;
			const doc = {
				get uri() { return data._uri; },
				get fileName() { return data._uri.fsPath; },
				get isUntitled() { return data._uri.scheme !== 'file'; },
				get languageId() { return data._languageId; },
				get version() { return data._versionId; },
				get isDirty() { return data._isDirty; },
				save() { return data._proxy._trySaveDocument(data._uri); },
				getText(range?) { return range ? data._getTextInRange(range) : data.getText(); },
				get lineCount() { return data._lines.length; },
				lineAt(lineOrPos) { return data.lineAt(lineOrPos); },
				offsetAt(pos) { return data.offsetAt(pos); },
				positionAt(offset) { return data.positionAt(offset); },
				validateRange(ran) { return data.validateRange(ran); },
				validatePosition(pos) { return data.validatePosition(pos); },
				getWordRangeAtPosition(pos) { return data.getWordRangeAtPosition(pos); }
			};
			this._documentRef = weak(doc);
		}

// ---> GC happens here

		return weak.get(this._documentRef);
	}

	get isDocumentReferenced(): boolean {
		return this._documentRef && !weak.isDead(this._documentRef);
	}
```

**Comment by jrieken** [comment] 2016-03-21 11:30
interesting. we should probably hold on to `this.isDocumentReferenced` with a local variable during the execution of that function. I'll will try if I can repo this manually with manual GC invocations

**Comment by bpasero** [comment] 2016-03-21 12:27
@alexandrudima I think these extensions run as part of "out of dev" for me:

![image](https://cloud.githubusercontent.com/assets/900690/13918573/a0f76de2-ef68-11e5-8214-9090c42504d0.png)

**Comment by jrieken** [comment] 2016-03-21 13:25
Hm, we call `weak.get` which should return `undefined` in case that GC data race happens, https://github.com/TooTallNate/node-weak#object-weakgetweakref-ref

**Comment by jrieken** [comment] 2016-03-21 17:51
I opt for not fixing this for March. We ship like that since Jan, see this for the first time, and don't really understand how this happens.

**Comment by bpasero** [comment] 2016-03-21 18:02
Makes sense.

**Comment by jrieken** [comment] 2016-04-08 09:35
We now also check for `isNearDeath` which mean only the weak reference is holding a reference. Lets see how it goes.

**Comment by jrieken** [comment] 2016-04-11 12:24
The fix didn't work so well...

**Comment by jrieken** [comment] 2016-04-11 13:08
related to #5162

**Comment by jrieken** [comment] 2016-04-13 08:48
_fixed_ by not using node-weak anymore, https://github.com/Microsoft/vscode/commit/7c4c828dcbf46e243a4c523b57873394e7deac6a

**Closed by jrieken** 2016-04-13 08:48 UTC
Labels: bug, important
