### ISSUE TITLE
Run and Debug in separate panel

### ISSUE THREAD

**Issue by Shanduur** [microsoft/vscode#118426] opened 2021-03-08 10:53 UTC
Hi!

I think that being able to have **Run and Debug** tab opened in another location - llike another tab with code?

Maybe photo will visualize it better:

![ex](https://user-images.githubusercontent.com/32583062/110311984-d06d9880-8004-11eb-8e83-fa75955e0a4b.png)

**Comment by isidorn** [comment] 2021-03-08 12:51
This is a duplicate of flexible workbench layout.
Thus closing as duplicate, we do not want to solve this specifically for debug

fyi @sbatten

**Closed** 2021-03-08 12:51 UTC
Labels: *duplicate, debug
