### ISSUE TITLE
"Reopen in WSL" option missing

### ISSUE THREAD

**Issue by JamesIV4** [microsoft/vscode#189551] opened 2023-08-03 13:24 UTC
Type: <b>Bug</b>

1) Click the >< arrows in the bottom left.
2) The option to "Reopen in WSL" is missing, but when running in WSL "Reopen in Windows" does appear. Only "Connect to WSL" is there, but that doesn't open the same workspace you're in already.

It's inconvenient to then have to then go and find and open the workspace once in WSL.

Screenshot:
![image](https://github.com/microsoft/vscode/assets/10490279/a85b3757-aac0-480a-8088-e294574e0a4d)

VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (8.13GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/jpound/Repos/messaging-admin-ui --crash-reporter-id ea5a17eb-61a7-444c-83ca-28627d66cb54|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (4 x 2495)|
|Memory (System)|5.79GB (3.85GB free)|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
color-info|bie|0.7.2
stylelint-disable-snippets|hed|1.0.3
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.80.2
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.3.0
material-icon-theme|PKi|4.29.0
code-settings-sync|Sha|3.4.3
errorlens|use|3.12.0
vscode-icons|vsc|12.4.0
increment-selection|alb|0.2.0
atlascode|atl|3.0.4
color-info|bie|0.7.2
htmltagwrap|bra|1.0.0
vscode-tailwindcss|bra|0.9.11
turbo-console-log|Cha|2.9.6
npm-intellisense|chr|1.4.4
angular-schematics|cyr|5.4.2
vscode-eslint|dba|2.4.2
gitlens|eam|14.1.1
add-contextmenu-toggle-comment|ebi|0.0.1
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.1.0
handlebars-preview|Gre|1.4.1
editorenhancements|gur|1.0.1
stylelint-disable-snippets|hed|1.0.3
beautify|Hoo|1.5.0
JSDocTagComplete|Hoo|0.0.2
githd|hui|2.3.3
jbockle-format-files|jbo|3.4.0
diff-tool|jin|0.0.1
minifyall|jos|2.10.0
vscode-format-context-menu|lac|1.0.4
expand-region|let|0.1.4
vs-live-share-mdns|lhe|0.0.11
git-graph|mhu|1.30.0
css-responsive|mre|1.1.2
vscode-scss|mrm|0.10.0
playwright|ms-|1.0.15
vsliveshare|ms-|1.0.5877
react-proptypes-intellisense|OfH|1.0.3
material-icon-theme|PKi|4.29.0
css-alphabetize|Pol|0.3.1
vscode-yaml|red|1.14.0
px-to-rem|sai|1.3.1
autoimport|ste|1.5.4
addDocComments|ste|0.0.8
code-spell-checker|str|2.20.5
vscode-stylelint|sty|1.2.4
vscode-pets|ton|1.24.0
alphabetical-sorter|ue|2.0.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.4.0
sort-js-object-keys|zen|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonnoceb:30805159
e537b577:30795824
ie5ij191:30792101
dsvsc013:30795093
dsvsc014:30804076
cmakesidepanelv2:30779593

```

</details>

**Comment by aeschli** [comment] 2023-08-17 13:54
Yes, we decided to slim down the remote menu. You can still find `Reopen Folder in WSL` in the command palette

**Comment by aeschli** [comment] 2023-08-17 13:54
duplicate of https://github.com/microsoft/vscode/issues/176073

**Closed by aeschli** 2023-08-17 13:54 UTC

**Comment by BDisp** [comment] 2023-09-27 22:15
> It's the only WSL option from all of those that's of any use to me. This is a really confusing decision.

To me too. This really does not make any sense because if we are on `WSL` remote and we click on it, it's show `Reopen Folder on Windows`. So, if we are on `Windows` why it not show `Reopen Folder on WSL`. 

> Yes, we decided to slim down the remote menu. You can still find `Reopen Folder in WSL` in the command palette

It's inconsistent then, If the intention was to sim down the remote menu, the `Reopen Folder on Windows` option should be removed too. But the `WSL: Reopen Folder in WSL` is an option I use a lot but I would prefer it in the remote menu, if possible of course. Thanks.
