### ISSUE TITLE
Dragging file or folder to empty explorer shows as Copy

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#53064] opened 2018-06-26 22:42 UTC
- VSCode Version: 1.25.0 Insiders
- OS Version: Windows 10

Found while testing https://github.com/Microsoft/vscode/issues/52292
Steps to Reproduce:

1. Drag a file or folder to an empty explorer
2. Hover image says "+ Copy" which is perhaps misleading since the file or folder will be opened not copied.

![image](https://user-images.githubusercontent.com/12818376/41943204-6b559ec2-7957-11e8-9bde-db3cc7255c6e.png)

**Comment by isidorn** [comment] 2018-06-27 09:50
We already behave like that in the explorer for a couple of years and nobody complained. Since the behavior is the same not matter if the explorer is empty or not.
@bpasero DId somebody complain 
Also I tried putting a 'move' instead of the 'copy' as the dropEffect but then the plus is not decorated, so it seems like we can not do better than this

**Comment by bpasero** [comment] 2018-06-27 10:10
I think copy is the right thing to show, it is intentional. You could argue that if we would show "move" feedback, people are confused because the file is also definitely not moved.

**Comment by isidorn** [comment] 2018-06-27 12:08
Thus closing as designed + none of the users complained.

**Closed by isidorn** 2018-06-27 12:08 UTC
Labels: under-discussion
