### ISSUE TITLE
workspaceContains doesn't activate

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#27761] opened 2017-05-31 17:27 UTC
On Windows in a workspace that matches the glob pattern `**/*.json`

![image](https://cloud.githubusercontent.com/assets/172399/26645008/f887afce-4636-11e7-8e9a-4f50301b8c23.png)

An extension with the the following workspaceContains event is not activated:
```json
    "activationEvents": [
        "workspaceContains:**/*.json"
    ],
```

**Comment by alexandrudima** [comment] 2017-05-31 18:12
What am I doing so different than you or @seanmcbreen (in #27665). The following totally works for me on Windows:

`package.json`:
```json
{
    "publisher": "alex",
    "name": "test",
    "version": "0.0.0",
    "engines":{
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "workspaceContains:**/*.json"
    ],
    "main": "./main.js"
}
```

```main.js
exports.activate = function() {
    console.log('Hello world, I am activated');
};
```

I get `[Extension Host] Hello world, I am activated` when opening e.g. the vscode repository.

@egamma Let's look into this together tomorrow

**Comment by alexandrudima** [comment] 2017-05-31 19:34
Is it possible you are debugging your extension and that is the root cause?

**Comment by alexandrudima** [comment] 2017-06-01 09:48
Duplicate of #27665

**Closed by alexandrudima** 2017-06-01 09:48 UTC
Labels: needs more info
