### ISSUE TITLE
Feature request: support multi select in TreeView API

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#65954] opened 2019-01-03 06:57 UTC
Support multi select in TreeView API, just like the multi select in file explorer
![image](https://user-images.githubusercontent.com/1050213/50626143-8772b300-0f67-11e9-9179-d556a4368852.png)
Use [Azure IoT Hub Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit) as example. In that case, we could let user to do operation on multi devices.
![image](https://user-images.githubusercontent.com/1050213/50626201-d7517a00-0f67-11e9-98c1-4bbd2ff1df1a.png)

**Comment by sandy081** [comment] 2019-01-03 15:21
Duplicate of #56344

**Closed** 2019-01-03 15:21 UTC
Labels: *duplicate, explorer-custom
