### ISSUE TITLE
Allow configuration/selection of Git commit behavior for untracked files

### ISSUE THREAD

**Issue by zerocrates** [Microsoft/vscode#19876] opened 2017-02-03 20:48 UTC
Near as I can tell, the default behavior of the checkmark in the Git panel is to commit all the shown changes: that is, both tracked and untracked files. #10448 allowed ignoring the untracked files in the badge counter, but the panel's behavior remains unchanged.

My expectation for a default action there is that it would be equivalent to either `git commit`, or `git commit -a`. If you stage something, you then get `git commit` behavior, but simple `git commit -a` doesn't seem to be available as far as I can tell.

A "Commit All Tracked" or similarly-named option in the panel's menu would be pretty useful by itself as an option, but the natural thing to me, given the existence of the setting controlling the badge counter, would be a parallel setting controlling what the default "nothing staged" commit button does: specifically wether it includes untracked files.

**Comment by joaomoreno** [comment] 2017-02-06 09:47
The checkmark commits:

- only the staged files, if there are any
- everything, else.

So, unlike you mentioned, when there are both staged and unstaged files, only the staged files will be committed. We found this to be a very helpful workflow. Can you give that a try and let us know if it still bothers you?

**Comment by zerocrates** [comment] 2017-02-07 20:37
Yes, the "stage then commit" flow works exactly how I'd expect it to, which is as you describe.

The default behavior does still bother me personally though. Mapping to how the command line behaves, I'd expect the checkmark with nothing staged to do one of the following: nothing (it's disabled and forces you to stage things if you want to commit, as if you ran `git commit` with nothing staged), or committing all the changed tracked files (the equivalent of `git commit -a`).

Committing an untracked file is a fairly major operation in my mind, and it makes me uncomfortable that it's the default here. There's already a practical equivalent in the interface to the `git add -A .` that's implicit in the default checkmark: the Stage All button. On the other hand there's not, at least in my understanding, a way to do either `commit -a` or to stage just the tracked files in a single click.

**Comment by joaomoreno** [comment] 2017-02-08 08:57
Got it, I wasn't getting the point about untracked vs. tracked files. Never really considered it.

What if we kept the current flow, but introduced a setting which would let you control whether untracked files are committed when commit runs and there are no staged changes? Ie `git.commit` could be `all` or `tracked`.

**Comment by zerocrates** [comment] 2017-02-08 16:09
That would be pretty much perfect. In fact it's what I suggested:

> the natural thing to me, given the existence of the setting controlling the badge counter, would be a parallel setting controlling what the default "nothing staged" commit button does: specifically wether it includes untracked files.

**Comment by joaomoreno** [comment] 2017-02-08 17:11
Ha, I see! We go full circle... thanks for the patience. 😆

**Comment by dbuchanan** [comment] 2017-02-11 20:37
Hi, would it be possible to extend that setting to include an option to commit only staged files (i.e. no commit if no files staged)? Or perhaps give a warning when no files are staged? Currently the default action of commiting all if nothing staged keeps catching me out, thanks.

**Comment by joaomoreno** [comment] 2017-02-13 07:31
Wouldn't that be a separate setting?

**Comment by dbuchanan** [comment] 2017-02-15 03:51
Possibly, although not sure how it would work as a setting since it would be very similar to what you proposed.

Your idea was to have a setting whereby `git.commit` could be `all` or `tracked`. I'd like to see a similar setting whereby `git.commit` could be `all` or `staged only`.

**Comment by zerocrates** [comment] 2017-02-17 21:36
It would/could be somewhat sensible to have all three of these options as one setting. As I understand it, each is a mutually exclusive way for the Commit action to work when nothing is staged (in all three cases it would keep its current behavior when anything has been staged):

- `all`: all changed/added files, as it works now, `git add -A . && git commit`
- `tracked`: all changed tracked files, `git commit -a`
- `staged`: do nothing/be disabled, `git commit`

What `staged` gets you is the ability to have the UI force you to explicitly select everything you want to commit, which lines up with how the CLI works with no flags given. I personally think of `tracked` as being the more important/useful setting to have, as there's not really any equivalent functionality now to commit or stage just all the changed tracked files, but `staged` would make sense as well.

**Comment by dbuchanan** [comment] 2017-02-18 04:19
That sounds like a good solution, thanks for describing it better than I could! ;)

**Comment by joaomoreno** [comment] 2017-04-25 14:55
Duplicate of #15613

**Closed by joaomoreno** 2017-04-25 14:55 UTC
Labels: feature-request, git
