### ISSUE TITLE
always noresponse  when i code for css

### ISSUE THREAD

**Issue by lseyesl** [Microsoft/vscode#11998] opened 2016-09-14 02:58 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

always noresponse  when i code for css

**Comment by bpasero** [comment] 2016-09-14 05:00
@lseyesl can you share more details of what happens?

**Comment by lseyesl** [comment] 2016-09-18 01:50
@bpasero  sorry, i think it appear with autoformat or (jshint || eslint) check , and i don't know how to get more info for it. because it not report some info

**Comment by lseyesl** [comment] 2016-09-18 02:10
![default](https://cloud.githubusercontent.com/assets/3131207/18612276/0d9dde60-7d88-11e6-826d-bdfbd346007f.png)
just this

**Comment by mjbvz** [comment] 2017-01-11 23:24
Closing as we need more information to investigate this.

@lseyesl Please try using VSCode 1.8. If you still see the problem, try launching code with `--disable-extensions` to see if an extension is the root cause.

Thanks

**Closed by mjbvz** 2017-01-11 23:24 UTC
Labels: needs more info
