### ISSUE TITLE
Javascript linter does not obey `javascript.implicitProjectConfig.experimentalDecorators` for decorators in script tags

### ISSUE THREAD

**Issue by kaleidawave** [microsoft/vscode#92846] opened 2020-03-17 13:31 UTC
- VSCode Version: 1.43.0
- OS Version: n/a

I have the  `javascript.implicitProjectConfig.experimentalDecorators` set to `true` in my settings:

Given a `script.js`
```js
@MyDecorator
class MyClass {
     ...
}
```

Does not produce any warnings as expected.

However in `index.html`:

```html
...
<script>
    @MyDecorator
    class MyClass {
        ...
    }
</script>
...
```

The linter says `Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.`

**Comment by mjbvz** [comment] 2020-03-17 19:08
This has the same root cause as #26338: `<script>` script are owned by the html extension instead of by the JavaScript extension. Fixing that is difficult

However we could have a small fix that just makes html understand the `javascript.implicitProjectConfig.experimentalDecorators` setting. Marking this as help-wanted

**Comment by liy-che** [comment] 2020-04-19 21:31
Hello @mjbvz, I'd like to try my hands on fixing this issue. Can you give some pointers as to which files are good places to start?

**Comment by mjbvz** [comment] 2020-04-20 22:40
This change will need to be made in the HTML extension

Here's where we configure TypeScript for the html extension: 

https://github.com/microsoft/vscode/blob/8f08c2ffa75e9ca53ac8ef67ff023feeb94fe5fc/extensions/html-language-features/server/src/modes/javascriptMode.ts#L32

You should:

- Pass the value for `experimentalDecorators` in with the initial configuration
- Make sure that the language service updates its value for `experimentalDecorators` when the VS Code setting changes

**Comment by liy-che** [comment] 2020-04-21 03:58
Is there another way to get the setting value other than vscode.workspace.getConfiguration()? The 'vscode' module cannot be found when I try to import it into javascriptMode. I think 'vscode' would have to be added as a dependency in package.json in order to import 'vscode'.

**Comment by liy-che** [comment] 2020-04-21 20:19
Right now I'm passing in a default 'false' for experimentalDecorators in the initial configuration and passing the settings into getJavascriptMode.doValidation to update compilerOptions and calling ts.createLanguageService(host) every time doValidation is invoked. It has the expected behavior, but is there a better way to update the compiler options without creating the service every time it runs validation?

**Comment by mjbvz** [comment] 2020-04-22 17:43
Is `getCompilationSettings` called when the file is changed? If it is, try updating the object that it returns

**Closed** 2020-04-24 18:34 UTC
Labels: help wanted, html, javascript

**Comment by agm1984** [comment] 2020-05-05 05:00
I am reproducing this error now with the following code:

``` blade
@php
$config = [
    'appName' => config('app.name'),
];
@endphp

<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <title>Arbitrary</title>
</head>

<body>
  <div id="app"></div>

  <script>
    window.config = @json($config);
  </script>
</body>
</html>
```

I realize this is known, but I will add the mention with respect to `@json`.

Here is the relevant docs page, if a person wanted to make a unit test using @json: https://laravel.com/docs/7.x/blade

If anyone finds this in the future, if `"javascript.implicitProjectConfig.experimentalDecorators": false,` is set in settings.json, it should suppress this error.

Additionally, both `tsconfig.json` and `jsconfig.json` files, in the root of the project, take precedence over that settings.json setting.
