### ISSUE TITLE
CSS Rename Symbol action on class leaves superfluous dot character

### ISSUE THREAD

**Issue by myfonj** [Microsoft/vscode#26829] opened 2017-05-17 17:41 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
---

Steps to Reproduce:

1. Create CSS file.
2. Write `.foo`.
3. Invoke "Rename Symbol" (By default bound to `F2`, or use the Command Palette).
4. Type `.bar`.
5. Press Enter.

Expected outcome
Selector (and its instances) changed to **`.bar`**.

Actual outcome
Selector (and its instances) changed to **`..bar`**.

![vscode-css class-rename-symbol-bug](https://cloud.githubusercontent.com/assets/1761395/26167443/10adb93c-3b37-11e7-9d75-0344c7052cd7.gif)

**Comment by aeschli** [comment] 2017-05-18 07:45
duplicate of #7340

**Closed** 2017-05-26 19:54 UTC
Labels: bug, css-less-sass
