### ISSUE TITLE
No intellisense for Javascript projects

### ISSUE THREAD

**Issue by DelvarWorld** [Microsoft/vscode#2056] opened 2016-01-16 01:15 UTC
For example without even having to analyze user Javascript classes, basic intellisense is missing:

![screen shot 2016-01-15 at 5 11 58 pm](https://cloud.githubusercontent.com/assets/79215/12369394/374adca8-bbab-11e5-8537-771681f7fca6.png)

I type `test.`, nothing happens so I type `Ctrl-Space` and after 1-2 seconds(!) an empty menu comes up.

Function arguments aren't suggested:

![screen shot 2016-01-15 at 5 13 46 pm](https://cloud.githubusercontent.com/assets/79215/12369402/60b84a76-bbab-11e5-8993-1363213ebd4c.png)

My `jsconfig.json`:

    {
        "compilerOptions": {
            "target": "ES6",
            "module": "commonjs"
        },
        "exclude": [
            "node_modules"
        ]
    }

**Comment by jrieken** [comment] 2016-01-18 10:41
duplicate of #2054

**Closed by jrieken** 2016-01-18 10:41 UTC
Labels: js
