### ISSUE TITLE
UI : Force user choice when multiple TS imports are available

### ISSUE THREAD

**Issue by cyrilletuzi** [Microsoft/vscode#41175] opened 2018-01-05 08:15 UTC
- VSCode Version: Insiders 1.20
- TS Version : 2.7

Now that Microsoft/TypeScript#19694 is fixed in TS 2.7, TS imports with multiple sources are proposed in VS Code Insiders.

I've made some students use it in an Angular course, and I have an important UI feedback. The multiple imports suggested for an identical name should not just be proposed : the choice should be forced before including the auto-import.

Otherwise, people very often doesn't notice there is multiple choices, and then just hit "Enter", selecting the default one proposed and resulting in broken code that won't compile (as the import won't be the good one). Even for more experienced users, it happens very often.

**Comment by mjbvz** [comment] 2018-01-05 19:02
Duplicate of #40414

**Closed by mjbvz** 2018-01-05 19:02 UTC
Labels: insiders, typescript
