### ISSUE TITLE
Error: Path must be a string. Received null due to some plugin

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#12229] opened 2016-09-18 18:24 UTC
- VSCode Version: 1.6.0-insider (58d7ff)
- OS Version: Windows 10

Steps to Reproduce:

1. Open a git project with eslint enabled and then open the change view for a file
2. The error `Error: Path must be a string. Received null` will be shown.

More discussion at https://github.com/Microsoft/vscode/issues/711

Restarting vscode with `--disable-extensions` fixes this issue. I think this might be caused
by the eslint server. The stack-trace for the error:

```js

e.doShow	@	workbench.main.js:94
e.show	@	workbench.main.js:94
(anonymous function)	@	workbench.main.js:105
i.Class.derive._oncancel	@	workbench.main.js:31
t.$showMessage	@	workbench.main.js:104
e.handle	@	workbench.main.js:104
s	@	workbench.main.js:50
f	@	workbench.main.js:50
_combinedTickCallback	@	internal/process/next_tick.js:67
_tickCallback	@	internal/process/next_tick.js:98
```

**Comment by bpasero** [comment] 2016-09-19 05:22
Maybe this is https://github.com/jshint/jshint/issues/2922 ?

**Comment by dbaeumer** [comment] 2016-09-19 08:25
@kumarharsh is there anything in the ESLint output pane?

**Comment by kumarharsh** [comment] 2016-09-20 06:50
@dbaeumer nothing, although the `Eslint` text in the bottom-right corner of the status bar turns `darkred` whenever this error happens.
![2016-09-20](https://cloud.githubusercontent.com/assets/760112/18660161/a230b17e-7f2c-11e6-849c-c1a73aec843b.png)

**Comment by kumarharsh** [comment] 2016-09-20 06:52
@bpasero no idea, but jshint is a different linter. I don't have jshint in my project, and I don't think eslint or any of its plugins depend on it...

**Comment by kumarharsh** [comment] 2016-09-20 09:30
Here is a small repo using which I'm able to reproduce this bug:

https://github.com/kumarharsh/vscode-eslint-bugs

* Do npm install
* soft reset the HEAD to one commit back, then open the repo in vscode, go to 

Relevant info:
VSCode version: 1.6.0-Insider (0a0bfe)
OS: Windows 10
Date: 16-09-20T06:11:03.267Z

**Comment by dbaeumer** [comment] 2016-09-21 09:50
@kumarharsh thanks for the test case. I am able to reproduce.

**Comment by dbaeumer** [comment] 2016-09-21 09:55
Will investigate for September.

**Comment by dbaeumer** [comment] 2016-09-27 13:34
@kumarharsh I was able to track this down. The exception is actually thrown by ESLint itself. Although stated differently the version 1.3.1 you use can't handle the fact that executeOnText (http://eslint.org/docs/developer-guide/nodejs-api#executeontext) is called with no file. 

Since 1.3.1 (the version you use) is a very old version would you be able to upgrade to a newer version. Fixing this is not easy since the CLIEngine doesn't carry any version attribute.

**Comment by kumarharsh** [comment] 2016-09-27 14:22
@dbaeumer wow, thanks. I'll try upgrading my eslint version and see if this issue goes away.

**Comment by dbaeumer** [comment] 2016-09-29 12:08
I will close the issue.

@kumarharsh please ping if you think I should still investigate into a work around.

**Closed by dbaeumer** 2016-09-29 12:08 UTC

**Comment by kumarharsh** [comment] 2016-09-29 13:19
@dbaeumer although I've done this in a smaller project, but not yet in the main one, it does seem to fix itself when I install a newer version of eslint.

**Comment by nathantschultz** [comment] 2016-10-17 16:30
I'm still seeing this with the latest eslint installed.
![screen shot 2016-10-17 at 10 28 42 am](https://cloud.githubusercontent.com/assets/6363133/19446145/a6593478-9454-11e6-8947-74f645083884.png)

**Comment by nathantschultz** [comment] 2016-10-17 16:31
@kumarharsh can you reopen this issue? Or do I need to create a new one?

**Comment by nathantschultz** [comment] 2016-10-17 16:44
Nevermind. I uninstalled eslint and installed it again and now I'm not seeing the error.
