### ISSUE TITLE
input not focus when files update in git

### ISSUE THREAD

**Issue by Gumplefik** [microsoft/vscode#119053] opened 2021-03-16 07:50 UTC
Issue Type: <b>Bug</b>

in workspace
1. open terminal
2. build your code in react or patch update files
3. in the meantime. if you are input commit text in first git project. then it will onblur and sometime the text will show in another input item.
hope files change not influence on input which i am working on. 

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 19.6.0

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-peek|dar|1.0.2
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
vue-snippets|hol|1.0.4
vue|jcb|0.1.5
formate|Mik|1.1.6
vscode-docker|ms-|1.11.0
vscode-language-pack-zh-hans|MS-|1.54.2
remote-containers|ms-|0.163.2
korofileheader|OBK|4.8.3
vetur|oct|0.33.1
markdown-preview-enhanced|shd|0.5.16
vue-helper|she|2.4.7
tabnine-vscode|Tab|3.2.8
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vspre833:30267464
vsfjg287:30275553

```

</details>

**Comment by madprops** [comment] 2021-03-24 03:37
Can confirm this is happening. I start typing on a project's commit input, then after the diff reloads the project on the bottom gets focused, interrupting what I was doing.

**Comment by eamodio** [comment] 2021-04-01 19:55
Duplicate of https://github.com/microsoft/vscode/issues/120162

**Closed by eamodio** 2021-04-01 19:55 UTC
Labels: *duplicate
