### ISSUE TITLE
Formatting not working after using inline style attribute in html

### ISSUE THREAD

**Issue by kishanmundha** [Microsoft/vscode#19585] opened 2017-01-30 16:30 UTC
Hello Team,

I'm using VSCode since last 6 months. Recently I started to work on angular 2 and when I try to format HTML it's format wrong.

I will show with a example.

When I try to format below HTML it's working absolutely fine.

```
<div>
  <div>
    Hello HTML
  </div>
</div>
```

But when I add inline style as below

```
<div style="width:100px">
  <div>
    Hello HTML
  </div>
</div>
```

It format as below

```
<div style="width:100px">
<div>
  Hello HTML
</div>
</div>
```

After next line of inline style formatting won't work or working wrong. Next line reset indent. I don't know about problem but I think this is issue, need to fix.

- VSCode Version: 1.8.1
- OS Version: Window 7 SP 1

**Comment by aeschli** [comment] 2017-01-31 08:43
duplicate of #17849

**Closed by aeschli** 2017-01-31 08:43 UTC
