### ISSUE TITLE
Feature Request: Open Code from stdout

### ISSUE THREAD

**Issue by cdhunt** [Microsoft/vscode#24913] opened 2017-04-17 20:31 UTC
I think there could be some interesting uses for being able to populate the contents of a new Untitled document from stdout via command-line. I frequently dump data from a process to a file and open it in Code, but that's usually not a file I want to save, I just want to view the contents in Code. This functionality would save me several steps.

For example:
```powershell
PS C:\> '{"key": "value"}' | code
```
Would start up Code like this.

![code_2017-04-17_16-27-18](https://cloud.githubusercontent.com/assets/114173/25103489/bf83351e-238a-11e7-932b-6791f6d61264.png)

**Comment by pr-yemibedu** [comment] 2017-04-17 21:01
Hello,
 This sounds interesting. it should pipe in with an option because by default this would at least on windows look for a file by name. Something like -nb for "new buffer" would be nice. If it is possible it could be able to have multiple times it is used or reuse the same code window. Thank you. Good day.

**Comment by benblank** [comment] 2017-08-15 18:07
I'd be quite interested in seeing this feature as well.  Being able to use VS Code as an alternative to `less` would fit well in my usual workflows.

**Comment by mjbvz** [comment] 2017-11-03 22:52
Duplicate of #6161

**Closed by mjbvz** 2017-11-03 22:52 UTC
Labels: duplicate, feature-request, workbench
