### ISSUE TITLE
Case-insensitive file name causes weird editor tab name.

### ISSUE THREAD

**Issue by ayqy** [microsoft/vscode#71699] opened 2019-04-04 04:11 UTC
- VSCode Version: Version 1.32.3 (1.32.3) a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
- OS Version: OSX 10.14.3 (18D42)

Steps to Reproduce:

Pay attention on this behavior since yesterday.

![image](https://user-images.githubusercontent.com/12402989/55529108-2f685b80-56d2-11e9-93e0-80feb4ebce83.png)
![image](https://user-images.githubusercontent.com/12402989/55529129-4a3ad000-56d2-11e9-997f-c5961cdac017.png)
![image](https://user-images.githubusercontent.com/12402989/55529138-60489080-56d2-11e9-9798-5687d8da34eb.png)

If Copy path, I got `QRcode.jsx` and `Qrcode.jsx`, but exactly is the same file:

![image](https://user-images.githubusercontent.com/12402989/55529212-b9182900-56d2-11e9-84e2-462bc91685b8.png)

Does this issue occur when all extensions are disabled?: Yes.

**Comment by ayqy** [comment] 2019-04-04 04:13
```bash
$ ls <path>
QRCode.css		QRCode.jsx		extractPreviewQr.js
```

**Comment by mjbvz** [comment] 2019-05-10 18:51
Thanks. This is a duplicate of #12448

**Closed by mjbvz** 2019-05-10 18:51 UTC
