### ISSUE TITLE
Can not collapse dom element manually in jsx file

### ISSUE THREAD

**Issue by Rhuaer** [Microsoft/vscode#47627] opened 2018-04-11 03:19 UTC
Issue Type: <b>Bug</b>

1.  create a jsx file
2.  write some dom element code in render method, like 
``` jsx
<div>
  <span>something here</span>
</div>
```
3.  can't collapse  `div` element when mouse hovers on the line where `div` is it
4. can reproduce after disabling all extension

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz (4 x 2808)|
|Memory (System)|15.96GB (8.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details>Extensions: none
![image](https://user-images.githubusercontent.com/13702561/38594707-32ec35a0-3d7a-11e8-8dd2-0d9002248a24.png)

**Comment by mjbvz** [comment] 2018-04-11 05:58
Duplicate of https://github.com/Microsoft/TypeScript/issues/23273

Set `"typescript.experimental.syntaxFolding": false` to disable syntax based folding

**Closed by mjbvz** 2018-04-11 05:58 UTC
Labels: new release
