### ISSUE TITLE
Git not detected on remote-ssh session

### ISSUE THREAD

**Issue by robfallows** [microsoft/vscode#75503] opened 2019-06-14 11:55 UTC
Issue Type: <b>Bug</b>

## vscode-insiders

1. Remote-ssh to a linux host.
1. Open terminal and create a new folder (`mkdir myfolder`).
1. Open `myfolder` in vscode.
1. Open vscode Source Control and Initialise Repository.
1. Open terminal and verify `.git/` folder is present (`ls .git`).
1. Check vscode Source Control - still reports "No source control providers registered".

Opening a folder already using `git` exhibits the same issue (i.e. this is not just a new SCM provider issue).

VS Code version: Code - Insiders 1.36.0-insider (d04b5d2eb16c156e24dbf44010c315d968694bd6, 2019-06-13T05:19:34.516Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-148-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (3.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Local-Ubuntu-VM|
|OS|Linux x64 4.4.0-148-generic|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (3 x 2591)|
|Memory (System)|1.95GB (0.18GB free)|
|VM|100%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
ansible|haa|0.2.8
AWK|lug|0.0.2
remote-containers|ms-|0.61.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.0
vscode-remote-extensionpack|ms-|0.15.0
vscode-docker|Pet|0.6.2
arm-snippets|sam|1.4.14
vscode-icons|vsc|8.7.0
markdown-toc|Ala|1.5.6
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
vscode-markdownlint|Dav|0.27.0
githistory|don|0.4.6
gitlens|eam|9.8.2
docker-explorer|for|0.1.6
docker-extension-pack|for|0.0.1
vscode-pull-request-github|Git|0.8.0
beautify|Hoo|1.5.0
markdown-extended|jeb|1.0.8
vscode-github|Kni|0.30.2
bash-ide-vscode|mad|1.3.3
rainbow-csv|mec|1.1.1
vscode-azurefunctions|ms-|0.17.1
vscode-cosmosdb|ms-|0.10.2
python|ms-|2019.5.18875
azure-account|ms-|0.8.4
azurecli|ms-|0.4.5
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.6.0
indent-rainbow|ode|7.4.0
bash-beautify|sha|0.1.1
ansible-autocomplete|tim|0.0.2
vscode-ansible|vsc|0.5.2

</details>

**Comment by gjsjohnmurray** [comment] 2019-06-14 12:10
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/671. Fix is due in the next Insiders.

**Closed** 2019-06-14 12:22 UTC
Labels: git
