### ISSUE TITLE
I want to show the second line of text after the code is collapsed

### ISSUE THREAD

**Issue by imseanpan** [Microsoft/vscode#44997] opened 2018-03-04 04:23 UTC
I want to show the second line of text after the code is collapsed~~~

![image](https://user-images.githubusercontent.com/12888042/36942112-2ab725c6-1fa6-11e8-8249-b101f675e358.png)

Did not show anything after folding.
![image](https://user-images.githubusercontent.com/12888042/36942114-468e13cc-1fa6-11e8-94b9-1b8bcf8f7f88.png)

I hope there is a setting to show the second line when the first line is empty.

like this

![image](https://user-images.githubusercontent.com/12888042/36942126-d3c62b4e-1fa6-11e8-9e48-fc65db98f37e.png)

thanks~

**Comment by atian25** [comment] 2018-03-05 03:24
+1

**Comment by aeschli** [comment] 2018-03-05 15:42
duplicate of #31966

**Closed by aeschli** 2018-03-05 15:42 UTC
Labels: editor, editor-core
