### ISSUE TITLE
VSCode will not run unless there is an internet connection

### ISSUE THREAD

**Issue by binaryWard** [Microsoft/vscode#64924] opened 2018-12-12 23:13 UTC
Issue Type: <b>Bug</b>

VSCode is not opening unless I have an internet connection.  The similar issues are all reported as closed.  Windows 1809 was recently installed and VSCode was at latest version and I have just upgraded before this submission and the same problem.  
It will not load unless there is an internet connection.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) x7-Z8700  CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.92GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by usernamehw** [comment] 2018-12-12 23:17
/duplicate of #7570. Fixed in Electron 3 #52629

**Closed** 2018-12-12 23:18 UTC
Labels: *duplicate, new release

**Comment by binaryWard** [comment] 2018-12-13 00:07
I have LogMeIn Hamachi installed.  What I have found out is if I have my WiFi not connected to a network and Hamachi "off"  VSCode will not open.

Now, if I am still not connected to Wi-Fi but turn on Hamachi.  Hamachi will detect there is no network connection but ask me if I would like for it to continue to check for a connection.  VSCode will open.  The computer does not have an internet connection but basically the network adapters show up as having a lan port but it does not have a network connection.

A workaround for now.
