### ISSUE TITLE
All files saving as plain text (.txt)

### ISSUE THREAD

**Issue by samtanderson** [microsoft/vscode#104939] opened 2020-08-18 15:19 UTC
Issue Type: <b>Bug</b>

As of most recent patch, when opening a new file via CTRL+N and then saving using any method, all files save with initial formatting of 'Plain Text (.txt)'. Prior to this update, files were saving under the 'All Types (* . *)' extension. I have my default language set to .SQL when creating new files, so my expected result would be the final file is saved as 'XXX.SQL'. When saving now it will show either 'XXX.SQL.TXT' or 'XXX.TXT'. From talking with my colleagues it seems this is a global issue that only started just recently. We all have SSMS installed, so the file extension should not be unrecognized either.

Edit: For additional testing, I also attempted to use another coding language by changing it on the task bar at the bottom of VsCode and I still get the same behavior. Seems unrelated to whichever language is chosen as all language used result in the same plain text saving behavior.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
tortoise-svn|fan|0.1.1
mssql|ms-|1.9.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-08-18 16:15
Looks like a duplicate of #103704 which is fixed in Insiders and also in the upcoming Recovery release.

**Closed** 2020-08-19 06:26 UTC
Labels: *duplicate
