### ISSUE TITLE
High CPU usage on Mac OS. Drains battery on laptop.

### ISSUE THREAD

**Issue by rchavez-nejmgroup** [Microsoft/vscode#39684] opened 2017-12-05 13:53 UTC
I'm unable to reopen the following ticket, and am still having problems:

https://github.com/Microsoft/vscode/issues/38913

I've added comments to the above ticket.

Thanks

**Comment by bpasero** [comment] 2017-12-05 14:20
@rchavez-nejmgroup can you follow https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by rchavez-nejmgroup** [comment] 2017-12-05 15:09
will do

**Comment by jeremyfa** [comment] 2017-12-05 21:37
FYI I am having the same issue on my macbook pro (high sierra 10.13.1), since vscode was updated (today) to `1.18.1`. The fan is screaming since then :(

**Comment by rchavez-nejmgroup** [comment] 2017-12-06 13:07
What is the size of your workspace/project (how many files)?
doesn't matter, the Code Helper fires up and consumes CPU as soon as VSCode starts

What languages are used in this project?
doesn't matter, see above.  Usually I'm just working in XML or JSON

Which Code process consumes the most resources?
Code Helper -- screen capture attached

![2017-12-06_07-54-34](https://user-images.githubusercontent.com/12071955/33662707-daee22b4-da5a-11e7-839e-4f1f50a39682.png)

The Code Helper process disappears when I exit VSCode

I've run **code --disable-extensions**  to see if there's an extension causing the problem, but Code Helper starts up and consumes CPU regardless

I've reset settings/emptied them - the problem persists

I ran code --verbose, but I'm not seeing any suspicious output

**Comment by bpasero** [comment] 2017-12-06 13:38
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by rchavez-nejmgroup** [comment] 2017-12-06 15:02
There appears to be only one process (69069).  Here's the dump:

rchavez          69069 214.3 13.3  7269408 2229080   ??  R     9:38AM   1:42.98 /Users/rchavez/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/rchavez/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
rchavez          69162   0.0  0.0  4278008   1056 s000  S+    9:39AM   0:00.00 grep 69069

**Comment by bpasero** [comment] 2017-12-06 15:08
Marking as duplicate of https://github.com/Microsoft/vscode/issues/3998 then. As a workaround you can set: `"files.useExperimentalFileWatcher": true`

**Closed by bpasero** 2017-12-06 15:08 UTC
Labels: file-watcher, freeze-slow-crash, needs more info

**Comment by rchavez-nejmgroup** [comment] 2017-12-06 15:09
When I run VSCode -- Insiders I don't have the same problem.  The Code Helper comes and goes in Activity Monitor, it doesn't stick around.  CPU usage is only 5.x% or so.
