### ISSUE TITLE
shell environment inconsistent for extension 

### ISSUE THREAD

**Issue by connectdotz** [microsoft/vscode#132886] opened 2021-09-10 19:40 UTC
Issue Type: <b>Bug</b>

on mac, open the vscode from desktop (UI) first time after the machine restarted, the shell env is not initalized (not sourcing profile nor rc files) upon extension startup; restarting code again from desktop, the shell env is initialized correctly upon starting up then extension.

If this is due to a race condition (first time launch vscode took longer to initialize the shell env?), is there a way for the extension to get notified when the shell env is fully initialized?

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 11, 6|
|Memory (System)|32.00GB (4.09GB free)|
|Process Argv|--crash-reporter-id 438d80c7-05fc-418f-b140-e69581260943|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-color-pick|ada|0.6.2
spellright|ban|3.0.60
emojisense|bie|0.9.0
vscode-eslint|dba|2.1.25
xml|Dot|2.5.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
vscode-commands|fab|1.4.3
flow-for-vscode|flo|1.9.2
shell-format|fox|7.1.0
vscode-pull-request-github|Git|0.30.0
go|gol|0.27.2
vscode-insertdatestring|jsy|2.3.0
vscode-colorize|kam|0.11.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.6.1
vscode-jest|Ort|4.2.0
material-icon-theme|PKi|4.10.0
java|red|0.81.0
markdown-preview-enhanced|shd|0.6.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vim|vsc|1.21.7
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2021-09-10 20:39
I think it's duplicate of either #132150 or #132766

Both should be resolved in Insiders already and in upcoming August Recovery release (1.60.1).

**Closed** 2021-09-11 02:44 UTC

**Comment by connectdotz** [comment] 2021-09-11 17:36
hi @meganrogge I tried the insider build (2021-09-10T17:03:53.070Z) this morning (2021/09/11), and the problem still exists. So not sure if this is a duplicate as you indicated.

Just to clarify that this is not related to integrated terminal nor powershell. Our extension spawned a child process when vscode starts. This child process's env is inherent from vscode's `process.env`. When I examine the vscode's process.env before spawning the process, it contains inconsistent content even when everything else is absolutely identical. It looks like during the first vscode launch (after OS restart), user's shell initialization files are not sourced, but the subsequent start-ups do source these files.
