### ISSUE TITLE
Inconsistent text formating after a tag in html

### ISSUE THREAD

**Issue by TarjeiB** [Microsoft/vscode#34022] opened 2017-09-08 11:57 UTC
- VSCode Version: 1.14-insider, 1.16
- OS Version: Win10

Steps to Reproduce:
Format text below in html document.
1:
```
Culpa fugiat ea sint odio, laboriosam totam ducimus sed distinctio sequi, expedita ab dicta. <a href="www.google.com">google.com</a>
Lorem ipsum dolor sit.
```
Format ->
```
Culpa fugiat ea sint odio, laboriosam totam ducimus sed distinctio sequi, expedita ab dicta. <a href="www.google.com">google.com</a>Lorem ipsum dolor sit.
```
Format again ->
```
Culpa fugiat ea sint odio, laboriosam totam ducimus sed distinctio sequi, expedita ab dicta. <a href="www.google.com">google.com</a>Lorem
ipsum dolor sit.
```
2:
With wrapping tags, adds two spaces after the closing a tag for each wrapping tag. 
```
<div>
  <div>
    <p>
      Culpa fugiat ea sint odio, laboriosam totam ducimus sed distinctio sequi, expedita ab dicta. <a href="www.google.com">google.com</a>      Lorem ipsum dolor sit.
    </p>
  </div>
</div>
```

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-09-11 08:57
@TarjeiB What's your current value for '"html.format.wrapLineLength"' ?

**Comment by aeschli** [comment] 2017-09-11 08:59
The second issue looks like a duplicate of https://github.com/beautify-web/js-beautify/issues/1223

**Comment by TarjeiB** [comment] 2017-09-11 09:15
@aeschli All defaults, "html.format.wrapLineLength": 120

**Comment by aeschli** [comment] 2017-09-11 09:27
I the built-in html formatter to the latest version of jsbeautify, and I can't reproduce your first issue.
You can give it a try with tomorrows insider build.

If you still see issues, try to reproduce it on http://jsbeautifier.org/ and file it at https://github.com/beautify-web/js-beautify/issues

**Closed** 2017-09-12 09:01 UTC
Labels: html, insiders
