### ISSUE TITLE
Ignore .directory files on Linux

### ISSUE THREAD

**Issue by guoyunhe** [Microsoft/vscode#48039] opened 2018-04-17 09:12 UTC
- VSCode Version: 1.22.2
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1. Use Dolphin file manager to open a folder on Linux with KDE desktop.
2. Click Preview button in file manager.
3. Open that folder in VS Code.
4. You will see a `.directory` file.

`.directory` files contains folder information for Dolphin file manager. It is usually useless for any other applications and editors. So it should be excluded in settings by default:
```json
{
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/.directory": true
  }
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2018-04-17 14:51
This is configurable so you can easily add it to your user configuration.
However this hshould not be the default, since Dolphin is not so widely used by our users to my knowledge.

Closing as designed

**Closed by isidorn** 2018-04-17 14:51 UTC
