### ISSUE TITLE
Built in extensions should have icons

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109832] opened 2020-11-02 07:57 UTC
I noticed that we include a couple of extensions that lack an icon:

![image](https://user-images.githubusercontent.com/900690/97843328-66a55100-1ce9-11eb-90ea-66745844b193.png)
![image](https://user-images.githubusercontent.com/900690/97843338-6c9b3200-1ce9-11eb-9f84-f8a571cef9bd.png)
![image](https://user-images.githubusercontent.com/900690/97843344-6f962280-1ce9-11eb-9517-36900cbe5ac4.png)
![image](https://user-images.githubusercontent.com/900690/97843355-72911300-1ce9-11eb-8798-24907dd6ff1c.png)
![image](https://user-images.githubusercontent.com/900690/97843365-76249a00-1ce9-11eb-81f3-3c9df69ff3ff.png)

**Comment by misolori** [comment] 2020-11-05 22:49
Duplicate of https://github.com/microsoft/vscode/issues/81760

**Closed by misolori** 2020-11-05 22:49 UTC
Labels: debt, extensions, icons-product, polish
