### ISSUE TITLE
Find in Files:  backreference in regex search and replace not working with newlines

### ISSUE THREAD

**Issue by eduardZA** [microsoft/vscode#80803] opened 2019-09-12 14:19 UTC
Issue Type: <b>Bug</b>

Create a text file and add the following:

```
this is the first line of the document.
this is the second one.
```

In the document, search for this:
```
(this is the first line)( of the document.)(\nthis is the second)( one.)
```

Replace the text with this:
```
$1$3
```

This gives the expected result.
![Screenshot 2019-09-12 at 16 01 55](https://user-images.githubusercontent.com/18609955/64791200-a48c6680-d577-11e9-82d4-0bb96b329ca5.png)
![Screenshot 2019-09-12 at 16 02 06](https://user-images.githubusercontent.com/18609955/64791213-ac4c0b00-d577-11e9-822d-ccaaffae2889.png)

Follow the exact same procedure with the Find in Files dialog.  This works in the absence of newline characters:
![Screenshot 2019-09-12 at 15 56 19](https://user-images.githubusercontent.com/18609955/64791306-d3a2d800-d577-11e9-92ec-7ba80fcdeb5c.png)

As soon as the search is extended to contain a multiline pattern, the backreferences are printed explicitly and not interpolated:
![Screenshot 2019-09-12 at 16 01 09](https://user-images.githubusercontent.com/18609955/64791338-dbfb1300-d577-11e9-828b-014076087b9c.png)

These types of replacements definitely worked in version 1.29 with much more complicated replace patterns, even using optional groups.

The results are the same regardless of whether `"search.usePCRE2": true` is set (originally released in [1.29](https://code.visualstudio.com/updates/v1_29#_backreferences-and-lookahead-in-search), but deprecated in [1.37](https://code.visualstudio.com/updates/v1_37)).

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|-psn_0_548998|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
shell-snippets|cds|0.1.2
bracket-pair-colorizer|Coe|1.0.61
scala|dal|0.0.5
gitlens|eam|9.9.3
terraform|mau|1.4.0
rainbow-csv|mec|1.3.1
ecdc|mit|1.3.0
vscode-docker|ms-|0.7.0
Go|ms-|0.11.4
chef|Pen|0.7.1
ruby|reb|0.25.3
vscode-yaml|red|0.5.2
HCL|who|0.0.5

</details>

**Comment by roblourens** [comment] 2019-09-15 19:45
Dupe of #80667

**Closed by roblourens** 2019-09-15 19:45 UTC
Labels: new release
