### ISSUE TITLE
spawn npm ENOENT on windows for npm tasks.

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#24115] opened 2017-04-06 17:56 UTC
- VSCode Version: 1.11.1 (March 2017)
- OS Version: Windows 10, 1607

<kbd>CTRL+SHIFT+B</kbd> for tasks.json with npm task results in:

```
running command> npm run watch-all
Failed to launch external program npm .
spawn npm ENOENT
```

I'm seeing lots of mentions of "spawn npm ENOENT" in google searches and in VSCode open issues, but i don't know that they're the same.

Steps to Reproduce:

I have a tasks.json file with the following configuration.  Various options seem to have no effect - `"cmd"` works as a "command" but nothing with npm.  `"cmd /C echo %PATH%"` and `"cmd /C npm --version"` and `"cmd /C node --version"` all work and give expected (latest) values.  Using cmd to call npm works, but it shouldn't be necessary, won't be cross-platform, and might not work with the background/Problem integration (haven't gotten that far)

![image](https://cloud.githubusercontent.com/assets/17498172/24768134/7e7bb8de-1acf-11e7-82ee-c1a563ab0afc.png)

```
Error: spawn npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

```
{
    "version": "0.1.0",
    "command": "npm",
    "suppressTaskName": true,
    "tasks": [
        {
            "isBuildCommand": true,
            "isShellCommand": true,
            "echoCommand": true,
            "isBackground": true,
            "taskName": "version",
            "args": ["--version"]
        }
    ]
}
```

**Comment by dbaeumer** [comment] 2017-04-07 09:32
Do you have node and npm installed and on the path. The problem is that npm can't be found. Looking at the tasks.json you need to do:

```json
{
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "isBuildCommand": true,
            "echoCommand": true,
            "taskName": "version",
            "args": ["--version"]
        }
    ]
}
```

**Comment by dbaeumer** [comment] 2017-04-07 09:33
Closing since this works for me in latest. Please ping if above tasks.json doesn't work for you.

**Closed by dbaeumer** 2017-04-07 09:32 UTC
Labels: needs more info

**Comment by JasonKleban** [comment] 2017-04-07 12:46
Perhaps this is environmental, but I am really having a difficult time diagnosing it.  Based on your comments, I think my other open issue could be related?  https://github.com/Microsoft/vscode/issues/23701

How would an environmental issue cause `npm --version` to fail where `cmd /C "npm --version"` succeeds?

**Comment by JasonKleban** [comment] 2017-04-07 14:26
{ "command": "which" ... { ... args: ["npm"] } }

```
running command> which npm
/c/Users/jkleban/AppData/Roaming/npm/npm
```

But this works!  `{ "command": "npm.cmd" ... { ... args: ["--version"] } }`

**Comment by dbaeumer** [comment] 2017-04-07 14:35
@JasonKleban what kind of default shell are you using. 

Here is what I see using VS Code:

![capture](https://cloud.githubusercontent.com/assets/1931590/24804861/24b7df26-1bb0-11e7-8cfa-78889ba557bb.png)

**Comment by dbaeumer** [comment] 2017-04-07 14:35
Could you create a small test project demoing what you see and share it on github.

**Comment by JasonKleban** [comment] 2017-04-07 14:37
Since `{ "command": "npm.cmd" ... { ... args: ["--version"] } }` works, is there anything in VSCode (different from any other shell, as I illustrated in #23701) that would not allow ".cmd" extensions to work?

**Comment by JasonKleban** [comment] 2017-04-07 14:51
Your example works:

```
{
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "isBuildCommand": true,
            "echoCommand": true,
            "taskName": "version",
            "args": ["--version"]
        }
    ]
}
```

but `"isShellCommand": false,` doesn't

```
{
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": false,   <<<<<<<<<<<<
    "suppressTaskName": true,
    "tasks": [
        {
            "isBuildCommand": true,
            "echoCommand": true,
            "taskName": "version",
            "args": ["--version"]
        }
    ]
}
```

Nor does putting it in the wrong spot, even though the schema suggests it:

```
{
    "version": "0.1.0",
    "command": "npm",
    "suppressTaskName": true,
    "tasks": [
        {
            "isBuildCommand": true,
            "isShellCommand": true, <<<<<
            "echoCommand": true,
            "taskName": "version",
            "args": ["--version"]
        }
    ]
}
```

Maybe some guidance on this is warranted?

**Comment by dbaeumer** [comment] 2017-04-10 08:15
`isShellCommand` can't work since npm is not an executable. It is a shell script and therefore needs to be executed in a shell. 

The `isShellCommand` in the task itself should as you point out either work or be flagged by the schema.

**Comment by dbaeumer** [comment] 2017-04-10 08:17
Opened https://github.com/Microsoft/vscode/issues/24410
