### ISSUE TITLE
[html] VSCode doesn't automatically close HTML tags

### ISSUE THREAD

**Issue by johnyradio** [Microsoft/vscode#2246] opened 2016-01-25 18:06 UTC
in html file-type
vscode version 0.10.6

My User Settings config says:
"editor.autoClosingBrackets": true,

but it still doesn't work.

For example, when you type in "<script" the IntelliSense suggestions pops up and you press enter on "script" it doesn't close the tag like this:

```
<script>
</script>
```

but it stays like this:

```
<script>
```

**Comment by cindoum** [comment] 2016-06-17 14:57
any update on it?

**Comment by aeschli** [comment] 2016-06-17 16:45
@cindoum Sorry, no, we currently have no plans adding this.
I recommend you using the emmet expansion
enter `script`, press tab. This expand to `<script></script>`

**Comment by mahomedh** [comment] 2016-07-14 14:18
You can use the "Auto Close Tag" extension to replace this behaviour. IMO this is better so that VSCode can stay light and people can "enable" features with the extension of choice.

https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag

**Comment by Peter-Juhasz** [comment] 2016-08-07 18:26
It is so essential that it should be part of the HTML language service.

**Comment by glen-84** [comment] 2016-09-10 18:18
Duplicate of #502 (?).

**Comment by aeschli** [comment] 2016-09-12 15:11
Yes, #502 is the same. I'll close #502 as dup.

**Comment by JMCA2** [comment] 2016-12-18 01:40
+1 This makes coding faster.

**Comment by neovive** [comment] 2017-03-21 16:14
Perhaps this is better as a separate feature request, but it would be useful to integrate auto tag renaming. It's currently available as a [popular extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag). Thanks.

**Comment by formulahendry** [comment] 2017-03-31 03:34
You may want to use [Auto Close Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) extension, and it supports for both Visual Studio mode and Sublime Text mode.

* Visual Studio mode:  `<script>` --> `<script></script>`
![Visual Studio](https://github.com/formulahendry/vscode-auto-close-tag/raw/master/images/usage.gif)
* Sublime Text mode:  `<script></` --> `<script></script>`
![Sublime Text](https://github.com/formulahendry/vscode-auto-close-tag/raw/master/images/st3.gif)

**Comment by DominikDitoIvosevic** [comment] 2017-05-01 14:41
Can't you use the https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages ?

autoClosingPairs - Defines the open and close symbols for the auto-close functionality. When an open symbol is entered, the editor will insert the close symbol automatically. Auto closing pairs optionally take a notIn parameter to deactivate a pair inside strings or comments.

**Comment by stofte** [comment] 2017-05-17 10:27
Feature makes it slightly annoying to add HTML to existing tags as it prefers to close the parent tag, instead of creating a new opening tag (I'll have to untrain hitting enter when writing HTML). Esp common occurence with div soup.

**Closed** 2017-08-25 10:08 UTC
Labels: feature-request, html

**Comment by aeschli** [comment] 2017-08-28 20:41
I added auto-close to the built-in HTML language support:

- typing the `>` of `<sometag>` will add the closing tag `</sometag>`.
- typing `/` of `</` will also close the tag.
- this behaviour is enabled by default and can be turned off with setting `html.autoClosingTags`

Thanks @formulahendry for leading the way with his extension. Note that the auto-close extension has more features, in particular, configurable support for more languages. 
Jun, if you can add a check for the new setting that would be great, the auto-close extension can co-exist with the new support.

**Comment by formulahendry** [comment] 2017-08-29 02:35
Thanks @aeschli , that's cool! I will take a look.

**Comment by rosieks** [comment] 2017-09-02 19:06
Does it work also with JSX/TSX?

**Comment by aeschli** [comment] 2017-09-04 09:23
@rosieks No, this is only for html, handlebars and razor files.

**Comment by johnyradio** [comment] 2017-09-05 00:32
Thx, @aeschli , you rock!

**Comment by johnyradio** [comment] 2017-09-05 00:34
@formulahendry , how is @aeschli 's solution different from the [Auto Close Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) extension?

**Comment by formulahendry** [comment] 2017-09-05 01:59
@johnyradio 

@aeschli 's solution is leveraging the VSCode built-in HTML extension. It could distinguish HTML and embedded languages well. So when you write embedded languages inside HTML, there will not be improper auto-close if you write generic like https://github.com/formulahendry/vscode-auto-close-tag/issues/17. While the limitation is that it only works on html, handlebars and razor files.

For Auto Close Tag extension, it is based on regular expression. So it works for any languages, while the limitation is that it could not distinguish HTML and embedded languages.
