### ISSUE TITLE
Blacklisting Extensions

### ISSUE THREAD

**Issue by destenson** [Microsoft/vscode#27359] opened 2017-05-27 04:18 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Install one of the many worthless or broken extensions with an appealing name or description.
2. Try it & find out it sucks and you never want to see it again.
3. Try to find some extension blacklist feature, but there is none.

This feature is still needed badly.

**Comment by roblourens** [comment] 2017-05-28 03:20
Workaround - leave it installed but disable it?

**Comment by destenson** [comment] 2017-05-28 03:37
I have done that before, and often I do, but then tend to forget the reason
it was disabled. I'm tempted to dive into the code myself and hack away at
a quick & dirty solution... At one point, there were some extensions that
kept re-installing themselves after I removed them & I ended up writing a
shell-script daemon to watch the directory & delete them before they
re-installed themselves. I haven't been in vscode's source very much at all
though. I'm sure that whatever I come up with will be a hack-job. I'm
hoping someone in the know will at least tell me where to put the few dozen
lines of code needed to implement this feature.

**Comment by yfdyh000** [comment] 2017-05-28 03:46
#26860

**Comment by destenson** [comment] 2017-08-03 03:55
#15747, yay it's been assigned to someone & it's on the backlog.

**Comment by mjbvz** [comment] 2017-11-03 22:42
Duplicate of #15747

**Closed by mjbvz** 2017-11-03 22:42 UTC
Labels: duplicate, extensions, feature-request
