### ISSUE TITLE
Editor window blanks out Randomly

### ISSUE THREAD

**Issue by cpheps** [microsoft/vscode#84706] opened 2019-11-13 15:56 UTC
Issue Type: <b>Bug</b>

Unsure what the trigger is but when occasionaly when I press the *CMD* key my editor window will go blank. This bug is not reliably reporducable and is fixed by closing the window and reloading it. 

I'm currently seeing it only when working in a remote SSH environment but unsure if it does this on a local project.

VS Code version: Code - Insiders 1.41.0-insider (c408a2c02d78982b1f83819c587c02bb59af9f93, 2019-11-13T06:24:06.004Z)
OS version: Darwin x64 19.0.0
Remote OS version: Linux x64 4.15.0-39-generic
Fetching remote diagnostics for 'ssh-remote+box1' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|-psn_0_245820|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: box1|
|OS|Linux x64 4.15.0-39-generic|
|CPUs|Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz (8 x 1599)|
|Memory (System)|47.15GB (21.05GB free)|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+box1' timed out.
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
touch-bar-display|bla|1.3.1
gotemplate|cas|0.3.0
bracket-pair-colorizer|Coe|1.0.61
mysql-syntax|jak|1.3.1
saltstack|kor|0.0.6
Kotlin|mat|1.7.0
remote-containers|ms-|0.84.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.2
vscode-remote-extensionpack|ms-|0.17.0
code-settings-sync|Sha|3.4.3
bunker|sld|1.1.6
vscode-icons|vsc|9.5.0
Bookmarks|ale|10.5.0
project-manager|ale|10.8.0
githistory|don|0.4.6
prettify-json|moh|0.0.3
Go|ms-|0.11.9
vsliveshare|ms-|1.0.1123
code-spell-checker|str|1.7.20
unique-window-colors|stu|1.0.51
gitblame|wad|3.0.1
change-case|wma|1.0.0
vscode-proto3|zxh|0.3.0

(3 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2019-11-13 22:26
@roblourens any idea?

**Comment by nailao** [comment] 2019-11-14 02:49
![2019-11-14](https://user-images.githubusercontent.com/19665552/68822531-1bef8b00-06cc-11ea-8752-d1f55323b143.gif)
When switching windows, sometimes it takes more than 1 second to wait. This is not the case before.

**Comment by rebornix** [comment] 2019-11-14 22:46
Starting with @deepak1556 as we saw similar issue on Window.s

**Comment by deepak1556** [comment] 2019-11-15 18:09
@nailao the issue you are describing is https://github.com/microsoft/vscode/issues/84343 which got fixed in insiders and will soon be available in stable.

This is a different one, I will let @roblourens eliminate any remote related issue first.

**Comment by roblourens** [comment] 2019-11-19 03:23
@cpheps can you explain more about exactly what you are seeing? 

> when I press the CMD key my editor window will go blank.

There is probably no remote specific issue here though @deepak1556

**Comment by cpheps** [comment] 2019-11-19 13:00
@roblourens Sure, not must to it though sadly. When in an editor pane occasionally when I push the CMD key all content will disappear from the current pane (code, line numbers, scroll bar, cursor). No other pane is affected if I have several open, a simple closing the pane and reopening fixes the issue.

**Comment by roblourens** [comment] 2019-11-20 01:38
How often does this happen? Any chance you can catch a video/screenshot? Also maybe try launching with `--disable-gpu`?

**Comment by cpheps** [comment] 2019-11-20 13:03
When I filed this bug it would happen maybe 4-5 times throughout a 8 hour work day. I haven't seen it in a while so maybe it got inherently fixed. If it happens again I'll take a screen shot I can't reliably reproduce it.

**Comment by cpheps** [comment] 2019-12-03 12:43
I haven't seen this issue in several weeks now. I don't know if it got fixed by something else but I would feel comfortable closing the issue if there is nothing driving it.

**Comment by nailao** [comment] 2019-12-04 02:18
> I haven't seen this issue in several weeks now. I don't know if it got fixed by something else but I would feel comfortable closing the issue if there is nothing driving it.

1.40.2 is resolved.

**Comment by deepak1556** [comment] 2019-12-07 06:09
Closing for now, please ping if you see the issue again. Thanks!

**Comment by cpheps** [comment] 2019-12-09 16:41
Just got it to happen again. Did a `cmd+Click` to follow a definition here is my logs. I replace my files with `XXX`.

``` 
ERR selectionRange must be contained in fullRange: Error: selectionRange must be contained in fullRange
	at Function.validate (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:390:458)
	at new w (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:390:326)
	at new w (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:378:821)
	at asDocumentSymbol (/home/cphelps/.vscode-server-insiders/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:396:22)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/home/cphelps/.vscode-server-insiders/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:393:23)
	at /home/cphelps/.vscode-server-insiders/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/client.js:1002:62
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1572   ERR Assertion failed (document 'file:///home/cphelps/XXX/XXX/XXX/XXX/XXX.go already exists!'): Error: Assertion failed (document 'file:///home/cphelps/XXX/XXX/XXX/XXX/XXX.go already exists!')
	at Object.t.ok (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:6:190)
	at f.$acceptDocumentsAndEditorsDelta (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:579:183)
	at p._doInvokeHandler (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:682:275)
	at p._invokeHandler (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:681:971)
	at p._receiveRequest (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:680:639)
	at p._receiveOneMessage (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:679:468)
	at /home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:677:691
	at l.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:46:893)
	at _.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:189:274)
	at /home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:839:285
	at l.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:46:893)
	at _.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:189:274)
	at t.PersistentProtocol._receiveMessage (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:193:629)
	at /home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:190:824
	at l.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:46:893)
	at p.acceptChunk (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:186:737)
	at /home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:186:89
	at Socket.t (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:195:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

Here's what my editor looks like:

![Screen Shot 2019-12-09 at 11 35 45 AM](https://user-images.githubusercontent.com/11877763/70454644-c31bd400-1a78-11ea-96e2-9f572e6cfb5c.png)


Current vscode version:

```
Version: 1.41.0-insider
Commit: 87c2e0be5d7359ce110c4c9ec9f6df71be996f8a
Date: 2019-12-06T21:34:49.305Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by bpasero** [comment] 2019-12-09 17:46
@cpheps would it be possible to get an exact step by step repro from you that we can play with? That includes a workspace to clone, the extensions you have installed and the instructions for how to get there.

**Comment by cpheps** [comment] 2019-12-09 18:02
Here are the steps I took:
1. Closed all previously opened panes (there were a lot in 2 split groups). None contained the new file
2. Closed explorer side bar and terminal 
3.`CMD + P` open file
4. Scrolled through file
5. `CMD + Click` on jump to definition
6. Editor pane blanked

I can't give the code base but I can supply my setup up.

Extensions:


Extension | Author (truncated) | Version
-- | -- | --
html-snippets | abu | 0.2.1
rtf | ale | 2.1.0
touch-bar-display | bla | 1.3.1
gotemplate | cas | 0.3.0
bracket-pair-colorizer | Coe | 1.0.61
mysql-syntax | jak | 1.3.1
saltstack | kor | 0.0.6
Kotlin | mat | 1.7.0
vscode-docker | ms- | 0.9.0
remote-containers | ms- | 0.91.0
remote-ssh | ms- | 0.47.2
remote-ssh-edit | ms- | 0.47.2
remote-wsl | ms- | 0.41.5
vscode-remote-extensionpack | ms- | 0.17.0
code-settings-sync | Sha | 3.4.3
bunker | sld | 1.1.6
vscode-icons | vsc | 9.6.0
vscode-ruby | win | 0.26.0
Bookmarks | ale | 10.6.0
project-manager | ale | 10.9.1
githistory | don | 0.4.11
prettify-json | moh | 0.0.3
Go | ms- | 0.11.9
vsliveshare | ms- | 1.0.1293
code-spell-checker | str | 1.7.20
unique-window-colors | stu | 1.0.51
gitblame | wad | 3.0.1
change-case | wma | 1.0.0
vscode-proto3 | zxh | 0.3.0

Here is a screenshot of the div containing the editor pane. Looks like my file is in there:
![Screen Shot 2019-12-09 at 12 54 46 PM](https://user-images.githubusercontent.com/11877763/70459956-46422780-1a83-11ea-92d7-69566ca05857.png)

Here is my workspace config:

```
{
	"folders": [
		{
			"path": "XXX",
                        "name": "XXX"
		},
		{
			"path": "XXX/YYY",
                        "name": "source"
		}
	],
	"settings": {
		"workbench.colorCustomizations": {
			"activityBar.foreground": "#ccff00",
			"activityBarBadge.foreground": "#ffb300",
			"activityBarBadge.background": "#b300ff",
			"contrastBorder": "#2f4f4f",
			"editorGroup.border": "#2f4f4f",
			"panel.border": "#2f4f4f",
			"activityBar.background": "#2E3004",
			"titleBar.activeBackground": "#404306",
			"titleBar.activeForeground": "#FBFCDD"
		},
		"files.watcherExclude": {
			"**/bin/**": true
		},
		"go.testFlags": [
			"-mod=vendor"
		],
		"gopls": {
			"buildFlags": [
			    "-mod=vendor"
			 ]		
		},
		"cSpell.words": [
			"golang",
			"oauth",
			"repo",
			"vsock"
		],
		"git.ignoreLimitWarning": true,
		
	}
}
```

My remote config:

```
{
    "go.lintOnSave": "off",
    "terminal.integrated.copyOnSelection": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
        "editor.snippetSuggestions": "none",
    },
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function
    
        // Experimental settings
        "completeUnimported": true, // autocomplete unimported packages
        "watchFileChanges": true,  // watch file changes outside of the editor
        "deepCompletion": true,     // enable deep completion
    },
    "files.eol": "\n",
    "go.toolsEnvVars": {
        "GO111MODULE": "auto"
    },
    "go.useLanguageServer": true,
    "files.autoSave": "onFocusChange",
    "terminal.integrated.shellArgs.linux": [ "-l" ]
}
```

User Config:

```
// Place your settings in this file to overwrite the default settings
{
    // Controls the rendering size of tabs in characters. Accepted values: "auto", 2, 4, 6, etc. If set to "auto", the value will be guessed when a file is opened.
    "editor.tabSize": 4,
    // Controls if the editor will insert spaces for tabs. Accepted values:  "auto", true, false. If set to "auto", the value will be guessed when a file is opened.
    "editor.insertSpaces": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    // Configurations for the extension.
    "TodoParser": {
        "include": [
            "rb",
            "go",
            "rake",
            "md",
            "erb"
        ],
        "markers": [
            "TODO:",
            "TODO",
            "<TODO",
            "<TODO:"
        ]
    },
    "ruby.lint": {
        "ruby-lint": false
    },
    "ruby.locate": {
        "include": "{**/*.rb,**/*.rake}",
        "exclude": "{**/@(test|spec|tmp|.*),**/@(test|spec|tmp|.*)/**,**/*_spec.rb}"
    },
    "java.home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home",
    "editor.fontLigatures": true,
    // "editor.fontFamily": "Fira Code",
    "editor.fontFamily": "'Cascadia Code', Consolas, 'Courier New', monospace",
    "editor.fontSize": 12,
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Chocolate Ice Cream",
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "files.associations": {
        "*.xmlp": "xml"
    },
    "cSpell.words": [
        "golang",
        "oauth",
        "repo"
    ],
    "cSpell.enabledLanguageIds": [
        "c",
        "cpp",
        "csharp",
        "go",
        "javascript",
        "javascriptreact",
        "json",
        "latex",
        "markdown",
        "php",
        "plaintext",
        "python",
        "text",
        "typescript",
        "typescriptreact",
        "yml"
    ],
    "extensions.ignoreRecommendations": false,
    "editor.tokenColorCustomizations": {
        "[1984 - Fancy]": {
            "comments": "#0ad0f3",
            "textMateRules": [
                {
                    "scope": "constant.other",
                    "settings": {
                        "foreground": "#06e514"
                    }
                }
            ],
        },
        "[Chocolate Ice Cream]": {
            "comments": "#d689b6f6",
            "textMateRules": [
                {
                    "scope": "constant.other",
                    "settings": {
                        "foreground": "#89d624"
                    }
                }
            ]
        }
    },
    "sync.lastUpload": "2018-08-20T16:58:42.294Z",
    "sync.autoDownload": false,
    "sync.autoUpload": true,
    "sync.lastDownload": "",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false,
    "explorer.confirmDelete": false,
    "python.disablePromptForFeatures": [
        "pylint"
    ],
    "git.path": "/usr/bin/git",
    "bracketPairColorizer.consecutivePairColors": [
        "()",
        "[]",
        "{}",
        [
            "Yellow",
            "Pink",
            "LightSkyBlue",
            "#fa87ce"
        ],
        "Red"
    ],
    "workbench.startupEditor": "newUntitledFile",
    "sync.removeExtensions": true,
    "sync.syncExtensions": true,
    "workbench.editor.enablePreview": false,
    "breadcrumbs.enabled": true,
    "mssql.connections": [],
    "editor.wordWrap": "off",
    "editor.renderWhitespace": "none",
    "go.coverOnSingleTest": true,
    "[typescript]": {
        "editor.tabSize": 2
    },
    "[javascript]": {
        "editor.tabSize": 2
    },
    "yaml.format.enable": true,
    "workbench.editor.showTabs": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "typescript.updateImportsOnFileMove.enabled": "always",
    "editor.minimap.enabled": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "files.autoSave": "onFocusChange",
    "zenMode.hideTabs": false,
    "zenMode.hideLineNumbers": false,
    "go.useLanguageServer": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function
        "completeUnimported": true,
    },
    "files.eol": "\n", // formatting only supports LF line endings
    "terminal.integrated.copyOnSelection": true,
    "sync.forceUpload": true
}
```

**Comment by cpheps** [comment] 2019-12-09 18:21
I also just noticed if I open the same file in a new editor pane, same group, it has my workspace path listed using `source` as the file root rather than `home/cphelps/XXX/XXX` which the blank editor shows.

**Comment by bpasero** [comment] 2019-12-10 06:20
@cpheps can you do this while the developer console is opened in dev tools to see what errors are printed when this happens? I wonder if there is anything in the logs that correlates to this issue.

**Comment by cpheps** [comment] 2019-12-10 12:36
@bpasero I can't reliably replicate it. I posted the logs I saw but I didn't open the console until after it happened (not sure if that matters). It usually happened when pressing the `CMD` key, I'm unsure what triggers it as it hasn't happened in a while.

Sorry that's not much information, let me know if you need more.

**Comment by bpasero** [comment] 2019-12-10 12:38
> It usually happened when pressing the CMD key

You mean, pressing CMD+key and clicking on a definition to navigate to it?

**Comment by cpheps** [comment] 2019-12-10 12:42
Usually on the down press of the CMD key before I can do an additional key stroke.

**Comment by bpasero** [comment] 2019-12-10 14:47
To clarify:
* you move mouse over a word
* you press CMD
* you release CMD
=> editor goes blank?

**Comment by cpheps** [comment] 2019-12-10 14:54
So it's

- mouse over a word
- press CMD
  => editor goes blank

**Comment by bpasero** [comment] 2019-12-10 15:28
@cpheps and then when this happens exactly is there any output in the developer console?

**Comment by cpheps** [comment] 2019-12-10 15:38
This is the output I captured I'm not sure if it's related or not:

```
ERR selectionRange must be contained in fullRange: Error: selectionRange must be contained in fullRange
	at Function.validate (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:390:458)
	at new w (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:390:326)
	at new w (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:378:821)
	at asDocumentSymbol (/home/cphelps/.vscode-server-insiders/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:396:22)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/home/cphelps/.vscode-server-insiders/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:393:23)
	at /home/cphelps/.vscode-server-insiders/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/client.js:1002:62
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1572   ERR Assertion failed (document 'file:///home/cphelps/XXX/XXX/XXX/XXX/XXX.go already exists!'): Error: Assertion failed (document 'file:///home/cphelps/XXX/XXX/XXX/XXX/XXX.go already exists!')
	at Object.t.ok (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:6:190)
	at f.$acceptDocumentsAndEditorsDelta (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:579:183)
	at p._doInvokeHandler (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:682:275)
	at p._invokeHandler (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:681:971)
	at p._receiveRequest (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:680:639)
	at p._receiveOneMessage (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:679:468)
	at /home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:677:691
	at l.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:46:893)
	at _.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:189:274)
	at /home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:839:285
	at l.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:46:893)
	at _.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:189:274)
	at t.PersistentProtocol._receiveMessage (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:193:629)
	at /home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:190:824
	at l.fire (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:46:893)
	at p.acceptChunk (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:186:737)
	at /home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:186:89
	at Socket.t (/home/cphelps/.vscode-server-insiders/bin/87c2e0be5d7359ce110c4c9ec9f6df71be996f8a/out/vs/server/remoteExtensionHostProcess.js:195:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by bpasero** [comment] 2019-12-10 15:57
@alexdima @jrieken @rebornix any idea why the editor might turn blank when we trigger preview hover? Not sure if the stack in https://github.com/microsoft/vscode/issues/84706#issuecomment-564091654 could be related.

**Comment by bpasero** [comment] 2019-12-10 15:57
@cpheps can you record a screencast possibly?

**Comment by cpheps** [comment] 2019-12-10 16:05
I can't reliably reproduce it, I do the preview hover/declaration jump multiple times a day and only once in a while does this issue happen. I'll try to trigger it.

**Comment by bpasero** [comment] 2019-12-10 16:14
> preview hover/declaration jump

You just said that this is not related to jumping but just hovering??

**Comment by cpheps** [comment] 2019-12-10 16:27
Sorry all I know is usually when I go to do a declaration jump on the CMD down press the editor goes blank. It happens so randomly it's hard to pin point what caused it.

**Comment by jrieken** [comment] 2019-12-10 17:36
Both errors [shown above happen](https://github.com/microsoft/vscode/issues/84706#issuecomment-564091654) on the extension host process, not the renderer. Therefore I doubt that they have something to do with this, the first error is about the go extension providing invalid outline data, the second is more interesting because it means documents & editors between the renderer and extension host are out of sync but I also doubt it causes the window to blank out.

**Comment by cpheps** [comment] 2019-12-12 13:19
Happened again this time it happened on a pane I wasn't on but once I moved back to it the pane was blank. Here are all the logs I captured and the html line of the pane.

```html
<div class="editor-instance showUnused" data-editor-id="workbench.editors.files.textFileEditor" data-keybinding-context="2" aria-label="runtimes_test.go. Text file editor., Group 1." style=""></div>
```


[vscode-logs.txt](https://github.com/microsoft/vscode/files/3955872/vscode-logs.txt)

**Comment by roblourens** [comment] 2019-12-13 01:29
The errors don't look related. cc @sbatten in case you have any ideas

**Comment by alexdima** [comment] 2019-12-13 11:22
> any idea why the editor might turn blank when we trigger preview hover? Not sure if the stack in #84706 (comment) could be related.

Sorry, I've never seen this. One speculation could be that a hover is painted and that leads to the GPU running out of memory or something? It is also not clear, @cpheps, does this reproduce at all when running with `--disable-gpu` ?

**Comment by cpheps** [comment] 2019-12-13 12:07
@alexdima I'll give it a shot running with `--disable-gpu`. Happens so randomly though it'll be hard to tell if it's because of that setting or just not hitting the issue.

**Comment by bpasero** [comment] 2019-12-17 15:36
@cpheps does it still happen with todays insider build?

**Comment by cpheps** [comment] 2019-12-17 15:46
I have not seen it but it hasn't happened since I last reported something 5 days ago.

**Comment by bpasero** [comment] 2019-12-17 15:50
Ok please report back if it happens again.

**Closed** 2019-12-24 16:16 UTC
Labels: mac, needs more info
