### ISSUE TITLE
[snippets] How can I excute some javascript in snippet

### ISSUE THREAD

**Issue by falltodis** [Microsoft/vscode#12990] opened 2016-09-29 10:45 UTC
- VSCode Version:  1.5.3 (1.5.3)
- OS Version: mac os

How can I excute  some javascript in snippet? I want to make a common coment with systemtime which looks like below

```
// config
"date: ${new Date().toISOString()}"

// I want
date: 2016-09-10 12-12-12

// actually 
date: new Date().toISOString()
```

**Comment by jrieken** [comment] 2016-11-03 15:21
closing as dupe of #10561

**Closed by jrieken** 2016-11-03 15:21 UTC
Labels: duplicate, feature-request, snippets
