### ISSUE TITLE
Wrong spacing of text in integrated terminal

### ISSUE THREAD

**Issue by Shanduur** [microsoft/vscode#121560] opened 2021-04-17 20:04 UTC
- VS Code Version: 1.55.2 3c4e3df9e89829dce27b7b5c24508306b151f30d x64
- OS Version: Windows 10 20H1 (build 19043.928)

Steps to Reproduce:

1. Open VSCode in Python . Powershell projects
2. Open Terminal - font is not set correctly.

As it is visible on the screenshots, I have set the following option, but even without it problem persists. Changing this setting (changing font family, removing it or whatever else) and saving *settings.json* sets the correct spacing in the terminal font.

```json
"terminal.integrated.fontFamily": "Consolas"
```

Does this issue occur when all extensions are disabled?: Yes

So that's what happening:

With extensions:
![Screenshot 2021-04-17 215620](https://user-images.githubusercontent.com/32583062/115125462-7c24e380-9fc8-11eb-9eb8-34ae7c83cc7a.png)

Without extensions:
![Screenshot 2021-04-17 215944](https://user-images.githubusercontent.com/32583062/115125470-8b0b9600-9fc8-11eb-9d59-28e5f37f79be.png)

**Comment by Valac01** [comment] 2021-04-20 11:47
I had this issue too, I just reinstalled it and it got fixed.

**Comment by meganrogge** [comment] 2021-04-22 20:22
Duplicate of #73879

**Closed** 2021-04-22 20:22 UTC
Labels: *duplicate, bug, integrated-terminal
