### ISSUE TITLE
Move an terminal in the editor area to the right

### ISSUE THREAD

**Issue by mathieug** [microsoft/vscode#140425] opened 2022-01-10 15:15 UTC
Issue Type: <b>Bug</b>

1. Run command "Terminal: Create New Terminal in Editor Area"
2. Wait for the shell to be loaded (prompt is shown), then move the tab to the right to split the view (empty editor on the left, terminal on the right)
3. The shell disappears, the terminal tab is now empty

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.55GB free)|
|Process Argv|--disable-extensions --crash-reporter-id ad80bda7-2002-4d63-9d45-38ce6ec37ce3|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30414010
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

Here is the bug in image in a VS Code with disabled extensions (ran with `code --disable-extensions`):

<img width="1792" alt="Capture d’écran 2022-01-10 à 16 15 43" src="https://user-images.githubusercontent.com/951183/148790041-09114cc3-4048-4b54-86bf-e8bd23b79607.png">
<img width="1792" alt="Capture d’écran 2022-01-10 à 16 15 52" src="https://user-images.githubusercontent.com/951183/148790077-01bd1b6f-db18-42ed-9440-5cc1935feeb6.png">
<img width="1789" alt="Capture d’écran 2022-01-10 à 16 16 07" src="https://user-images.githubusercontent.com/951183/148790101-8166eb3f-c35a-4fc3-a095-5f35cbb5a3e1.png">

**Comment by IllusionMH** [comment] 2022-01-10 22:00
@JacksonKearl does bot supposed to detect `/` `duplicate` in the middle of two words without start of the line or at least whitespace before?

**Comment by JacksonKearl** [comment] 2022-01-10 22:43
@IllusionMH good call, should be fixed now. I'll let @meganrogge decide if it's a duplicate.

**Comment by meganrogge** [comment] 2022-01-11 04:00
/duplicate of #139222 already fixed in insider's

**Closed by meganrogge** 2022-01-11 04:00 UTC
Labels: *duplicate
