### ISSUE TITLE
Collapse all folderers in Explorer does not close the folders.

### ISSUE THREAD

**Issue by JurePuh** [microsoft/vscode#88092] opened 2020-01-04 19:31 UTC
Issue Type: <b>Bug</b>

Hello, I added a folder to my project and init are many .py files. When I click (collapse all folder in explorer) function , vscode wont close the folders.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (11.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.11.50794
powershell|ms-|2019.12.0

(2 theme extensions excluded)

</details>

**Comment by egamma** [comment] 2020-01-06 09:03
/needsMoreInfo cannot reproduce given the steps you have provided and this works for me, see the animated gif below. Please include more details for how to reproduce this behaviour.

![screencast 2020-01-06 10-01-55](https://user-images.githubusercontent.com/172399/71807495-bab0bc00-306b-11ea-8e7c-3e947cdb1bea.gif)

**Comment by bpasero** [comment] 2020-01-06 16:11
Maybe this is https://github.com/microsoft/vscode/issues/88146 ?

**Comment by egamma** [comment] 2020-01-07 11:35
The description mentions 

> I added a folder to my project

Which hints that this is a multi-root setup. Closing as a duplicate.

**Closed by egamma** 2020-01-07 11:35 UTC
Labels: needs more info
