### ISSUE TITLE
toggleTerminal key binding not working with focus in terminal

### ISSUE THREAD

**Issue by phest** [Microsoft/vscode#10167] opened 2016-08-05 05:18 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 10 (10.0.10586)

Steps to Reproduce:

1. add new keybinding: `{ "key": "f1", "command": "workbench.action.terminal.toggleTerminal"},`
2. close integrated terminal if open
3. press F1, terminal expands on bottom, with keyboard cursor inside
4. press F1, terminal will stay, and `A` will be added to terminal

Expected behavior: 4. press F1, terminal collapses

**Comment by Tyriar** [comment] 2016-08-05 07:19
Duplicate of https://github.com/Microsoft/vscode/issues/7269

Currently for terminal keybindings you're restricted to those key combinations that are not consumed by the terminal itself.

**Closed by Tyriar** 2016-08-05 07:19 UTC
