### ISSUE TITLE
Native Notebooks - Changing kernel causes markdown to flicker, then disappear

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#126056] opened 2021-06-11 14:58 UTC
- VS Code Version: 1.57.0 & 1.57.0-insider

Steps to Reproduce:

1. Open notebook
2. Change kernel - markdown will flicker
3. Change kernel again - markdown disappears
4. This behavior continues every other kernel switch

![Markdown Disappearing](https://user-images.githubusercontent.com/19276747/121623812-3c590600-ca25-11eb-96ba-af9bc9a0dc08.gif)

**Comment by rebornix** [comment] 2021-06-11 16:21
The way I reproduced this issue is 

* create a code cell
* change it markdown
* double click to edit
* escape
* the markdown cell is blank

```
notebookWebviewPreloads.js:3 Uncaught (in promise) Error: Could not find renderer
    at Object.render (notebookWebviewPreloads.js:3)
    at K.updateContentAndRender (notebookWebviewPreloads.js:3)
    at new K (notebookWebviewPreloads.js:3)
    at Object.createMarkupCell (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
    at Array.map (<anonymous>)
    at Object.ensureMarkupCells (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
```

**Comment by rebornix** [comment] 2021-06-11 16:21
https://github.com/microsoft/vscode/issues/126056#issuecomment-859695620 this might be different from the original issue

**Comment by mjbvz** [comment] 2021-06-11 20:39
@connor4312 I suspect this may be from 7c226ae15584cbf1cc62d328c489ab40cc3d33c6 (or related followup changes) but am still debugging. Any ideas off the top of your head?

**Comment by connor4312** [comment] 2021-06-11 21:06
Definitely related to some state not being preserved well between reloads, but I don't know what specific problem it could be off the top of my head.

**Comment by mjbvz** [comment] 2021-06-11 22:09
Actually seem to making renderer async. Seems fixed with 3086bb5956b5161b0c22cd71c13427773be834be but I need to test a bit more and then back port to 1.57

**Comment by mjbvz** [comment] 2021-06-12 00:00
Let me know if you still see this in the next insiders build

**Comment by rzhao271** [comment] 2021-06-17 16:05
@rebornix while following https://github.com/microsoft/vscode/issues/126056#issuecomment-859695620, the markdown cell isn't blank, but when I change the code cell to a text cell in a github issues notebook, I see the message `No renderer found for "text/plain" a`.

**Comment by rzhao271** [comment] 2021-06-17 16:10
I can still repro the original issue with the same steps.
The markdown shows up again after step 4 if one scrolls down and back up.

![recording (37)](https://user-images.githubusercontent.com/7199958/122434069-a143bd00-cf4b-11eb-9fb7-dbeaf30b18b3.gif)

**Comment by mjbvz** [comment] 2021-07-14 23:25
I can't reproduce this with a simple Jupyter notebook

@rzhao271 Can you please test using the latest insiders. If you still see this, please share the notebook you are using

**Closed** 2021-07-15 23:57 UTC
Labels: bug, needs more info, notebook

**Comment by aparente-nurix** [comment] 2021-07-18 20:59
Also getting this same issue with July 2021 (version 1.59.0-insider), but its happening in a notebook I can't share for confidentiality purposes. I tried reproducing this in a blank notebook with the goal of being able to share it, but I wasn't able to reproduce the issue.

**Comment by rzhao271** [comment] 2021-07-28 18:55
Marking as verified, as I'm unable to repro the issue on my notebook, now. Feel free to reopen this issue or create a new one if there's a notebook you're seeing the issue with that you're able to share.
