### ISSUE TITLE
Voiceover when expanding selection could be better

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#144791] opened 2022-03-09 22:20 UTC
Couple issues:
1. when expanding the ***** selection, it only ever says 1star star star` selected even when more *'s are shown in the text. This seems to be a macos global bug
2. The formatting `foo unselected, foo bar selected` is not great, it hides the most important info. This seems to be a chromium thing, repros in edge, but notes handles it better IMO

![Recording 2022-03-09 at 14 14 46](https://user-images.githubusercontent.com/8586769/157545699-c905f645-7283-4a1e-8038-0bcbc705f98b.gif)

![Recording 2022-03-09 at 14 20 03](https://user-images.githubusercontent.com/8586769/157547278-7558fc63-5eb8-4b2f-a40e-1da9df45cbbf.gif)

**Comment by isidorn** [comment] 2022-03-10 12:42
@JacksonKearl can you reproduce with VoiceOver and `textArea` here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
If yes, can you please file a new issue for VoiceOver here https://bugs.webkit.org/
Then I can share the bug with the VoiceOver authors. Thanks!

**Comment by JacksonKearl** [comment] 2022-04-06 00:36
It works fine in WebKit, seems to be only Chromium/Electron that's effected.

**Comment by isidorn** [comment] 2022-04-06 08:45
@JacksonKearl if you can reproduce with Chromium then can you file a new issue in https://bugs.chromium.org/p/chromium/issues/list

Or are you saying you can only reproduce with Electron?

**Comment by JacksonKearl** [comment] 2022-04-06 17:41
Sure, reported here https://bugs.chromium.org/p/chromium/issues/detail?id=1313990 👍

**Comment by MarcoZehe** [comment] 2022-11-26 10:15
Is #162152 a duplicate of this bug?

**Comment by JacksonKearl** [comment] 2022-11-27 06:27
@MarcoZehe yes I believe so, good news is chromium fixed this 12 days ago! https://bugs.chromium.org/p/chromium/issues/detail?id=1172956#c7

Bad news is it may be a while before vscode gets that build.

**Comment by MarcoZehe** [comment] 2022-11-27 11:02
Thanks! Yes, I saw that it is fixed now, and I also discovered that I was the one who originally filed this bug report in February 2021. I couldn't figure out what version of Chromium this will be in, though, but I suppose it is currently in Canary and has to move through beta and release for the next couple of weeks, then to Electron, until it finally hits VSCode once it moves to that version of Electron that has the fix.

**Comment by isidorn** [comment] 2022-11-28 09:32
@MarcoZehe thanks for opening the original issue on the Chromium side.
@deepak1556 can we back port the chromium fix so it is included as part of our next Electron update?

@JacksonKearl hey there 👋

**Comment by deepak1556** [comment] 2022-12-08 08:20
Fixed upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1172956

I will backport the fix with Electron 22 update.

**Comment by deepak1556** [comment] 2023-03-22 22:56
Reopening because Electron 22 was reverted for the March milestone.

**Closed** 2023-04-21 15:36 UTC
Labels: bug, upstream, accessibility, upstream-issue-fixed, chromium, fixed-in-electron-22
