### ISSUE TITLE
Cannot click on publisher names with dashes

### ISSUE THREAD

**Issue by aym-v** [microsoft/vscode#122130] opened 2021-04-25 12:56 UTC
- VS Code Version: 1.55.2
- OS Version: darwin 20.3.0

Steps to Reproduce:

1. Go to an extension made by a publisher with a dash in its name (e.g: `scala-lang`)
2. Click on the publisher name
3. There is no result

**Capture:**

https://user-images.githubusercontent.com/18191750/115878801-43ae5b00-a449-11eb-966e-480d635175fa.mp4

### Proposed solution

Add a @publisher search field that would use the actual publisherName field rather than displayName or publisherId. This probably involves some changes to the search API.

Searches would then look like this:
"@publisher:intersystems-community"
"@publisher:scala-lang"
"@publisher:usernamehw"

Does this issue occur when all extensions are disabled?: Yes

**Comment by aym-v** [comment] 2021-04-25 13:12
related to #100495

**Comment by eamodio** [comment] 2021-04-25 15:58
Duplicate of #100495

**Closed** 2021-04-25 15:59 UTC
Labels: *duplicate
