### ISSUE TITLE
Emmet: wrap with abbreviation is broken for 'span'

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#31212] opened 2017-07-21 13:04 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (9912a545c9728ce5e6b3cdfcc9442ee47955aa42, 2017-07-21T05:16:15.475Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.2
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
atom-keybindings|ms-|2.9.1
stylelint|shi|0.28.0
---

Steps to Reproduce:

1. Open the following HTML file:
```
<html>
<body>
  <ul>
	  <li></li>
	  <li></li>
	  <li></li>
	  <li></li>
	  <li></li>
  </ul>
</body>
</html>
```
2. Select all lines between the `ul` tags.
3. Invoke "Emmet: Wrap with Abbreviation", and then type `span` in the command palette.
4. The end result is horrific:
```
<html>
<body>
  <span> 	<ul> 	 <li></li> 	 <li></li> 	 <li></li> 	 <li></li> 	 <li></li> 	</ul> </span>
</body>
</html>
```

**Comment by vvs** [comment] 2017-07-21 13:08
Interestingly enough, everything works fine for other tags, like `div`, `p` or `body`! 😳

**Comment by vvs** [comment] 2017-07-21 13:25
Another bad tag that exhibits the same problem is `em`.

Trying to wrap with `em` leads to all lines combined into a single one.

**Comment by ramya-rao-a** [comment] 2017-07-21 16:05
Duplicate of #29898

This happens for all elements that have `display: inline` by default.

Emmet thinks that "oh this is an inline element, so I should place everything in a single line"

Solution would be to fix it upstream by not doing this single line treatment if the text being wrapped is multi line to begin with.

**Closed by ramya-rao-a** 2017-07-21 16:05 UTC
Labels: insiders
