### ISSUE TITLE
Replace dialog opens with the wrong field focused

### ISSUE THREAD

**Issue by jcward** [Microsoft/vscode#4566] opened 2016-03-22 16:30 UTC
- VSCode Version: 0.10.11 (commit: f291f4) downloaded today
- OS Version: Ubuntu 14.04 x64

Steps to Reproduce:
1. In the editor, hit `CTRL-H` for Find & Replace pop-up

Screen grab of the issue:

![test](https://cloud.githubusercontent.com/assets/2192439/13959231/056f47e4-f019-11e5-8b8f-91bd982e0870.gif)

Issue: Notice the **Find** field should be focused first when the dialog is opened. Instead, the **Replace** field is focused. And `tab` moves the focus forward, to the little icons (one would have to know to `shift-tab` to get back to Find.)

**ETA:** Ah, I suppose this changed at some point, I was comparing 0.10.11 Linux to 0.10.3 Windows.

So it becomes a question of which implementation is "more better". :p :)

Alright, well, here's a list of editor software that focuses the Find input when pressing `Ctrl-H`:
- Microsoft Office
- Google Docs
- GitHub in-browser editor
- Sublime
- Visual Studio 2015 (community / windows)
- Atom 1.5.3

Vs. editors that focus Replace first:
- Atom 1.0.2

Feel free to bring others to my attention.

**Comment by Tyriar** [comment] 2016-03-22 16:43
This applies across OS's, I also think this is as designed. Might be worth a little discussion with the feature owner though.

Note that you can always use <kbd>ctrl</kbd>+<kbd>f</kbd> to focus find from anywhere.

**Comment by jcward** [comment] 2016-03-22 17:02
@Tyriar ah, thanks. I've added a list of editor software that focuses on Find first.

**Comment by Tyriar** [comment] 2016-03-22 17:23
Atom 1.5.3 focuses find first too.

**Comment by OlsonDev** [comment] 2016-07-05 16:40
I agree, this behavior is counter-intuitive. I realized I run into [my issue](https://github.com/Microsoft/vscode/issues/2812) (of the find widget not trapping focus) a lot because I'm accustomed to hitting `Ctrl+H` instead of `Ctrl+F` (because many apps have separate "Find" and "Find & Replace" dialogs). When I `Ctrl+H`, I notice the focus is on Replace, intuitively hit `Tab` to go back to `Find` but then I realize the buttons are tab-focusable (in many IDEs they aren't, just `Alt`-shortcut-able (Atom & Sublime Text to name a few)). Okay, that's fine. Now, to get back to Find, I have to `Shift+Tab` twice or `Tab` a few more times; `Shift+Tab` is uncomfortable to hit so I'll instead go for 4 more `Tab`s, just to realize focus has fallen off the find widget.

If this issue was fixed, I probably wouldn't run into [my issue](https://github.com/Microsoft/vscode/issues/2812) as often.

**Comment by OlsonDev** [comment] 2016-07-05 17:12
More examples:

Focuses Find input on `Ctrl+H`:
- Beyond Compare
- WinMerge
- Notepad++
- Wordpad
- Fiddler ScriptEditor
- SQL Server Management Studio 2016 (Replace widget in query editor)

Focuses Replace input on `Ctrl+H`:
- SQL Server Management Studio 2016 (Replace in Files dialog pops up with no query editor open)

**Comment by tbfleming** [comment] 2016-07-15 02:34
It took me time to get used to using ctrl+f to focus the find field and ctrl+h to focus the replace field. Now I prefer it; it beats tabbing.

**Comment by rebornix** [comment] 2017-05-23 00:30
this issue is talking about the same thing as https://github.com/Microsoft/vscode/issues/17562 . From tomorrow's insiders,  if current selection and the existing search string in Find Widget are empty, we'll focus the Find Input first.

Close it first and please let me know if you have any idea about that.

**Closed by rebornix** 2017-05-23 00:30 UTC
Labels: editor-find-widget, under-discussion
