### ISSUE TITLE
Markdown preview jumps like crazy

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#50934] opened 2018-06-01 10:14 UTC
Insders, os x

Open our vscode-docs repo
Work on the release notes, and have the markdown preview open side by side
Make some edits in the notable changes section for example, notice the screen jumping all the time making the experience very unpleasent

![jump](https://user-images.githubusercontent.com/1926584/40835927-3ac1d742-6595-11e8-9216-d2886c1106c8.gif)

**Comment by mjbvz** [comment] 2018-06-01 18:16
Duplicate of #49150

**Closed by mjbvz** 2018-06-01 18:16 UTC
Labels: bug, markdown
