### ISSUE TITLE
Sort extensions by extension update date

### ISSUE THREAD

**Issue by janderudder** [microsoft/vscode#53405] opened 2018-07-01 20:03 UTC
It's in the title : I could use the possibility to browse installed extensions sorted by ~~installation~~ update date.

I often install a batch of extensions at a time, for a given language, or about a given feature. Some times I find unrelated extensions during the search and install them too.
So I restart the editor with a whole bunch of new extensions, and its behavior may be quite different compared to last reload.

I don't necessarily remember the names of all the newly installed extensions, and after restarting the editor sometimes I wish to go back to the extension read-me to see the how-to again, or just get the extension's name to use its commands.

When you have a lot of extensions installed it may be hard to browse through to find the new ones.
It would be nice to have a way to discriminate the latest installed extensions.

Thank you for this great editor anyway :)

**Comment by robertopc** [comment] 2018-07-05 12:54
I want this feature too.

**Comment by cacheflow** [comment] 2018-07-06 05:19
I'll take this.

**Comment by ramya-rao-a** [comment] 2018-09-11 23:07
We do not store any data around install timestamps. All information we show around extensions are coming from the marketplace. We could use at the timestamps of the directory for the extension, but for every extension update, a new folder is created and the older one is deleted.

So there is no way at the moment to get the install date.

**Comment by KillyMXI** [comment] 2018-09-24 11:48
> We could use at the timestamps of the directory for the extension, but for every extension update, a new folder is created and the older one is deleted.

In my ticket I was asking about install OR UPDATE dates, so this way, although shakey, would've worked for me fine.

**Comment by ramya-rao-a** [comment] 2018-09-24 18:11
> In my ticket I was asking about install OR UPDATE dates

Thanks for clarifying. That was not clear to me initially.
This does simplify things.

**Comment by KillyMXI** [comment] 2018-09-24 18:18
Please note that my ticket is not this one (it was marked as duplicate of
this one despite being older).

**Comment by nealot** [comment] 2018-09-25 10:27
@KillyMXI I don't think janderudder was referring to the original date an extension was installed. Since every update requires an extension to be reinstalled, he was most likely asking for a way to organize the last date an extension was updated *or* installed. I mean, I don't think anyone would want to keep track of when they first installed an extension -- that's pretty useless.

Anyways, I really hope we get some sorting options for dates because figuring out the latest extension settings is a hassle.

**Comment by janderudder** [comment] 2018-09-25 17:53
> @KillyMXI I don't think janderudder was referring to the original date an extension was installed.
Actually I was. I am not familiar with how VS Code extensions work. Anyway, the purpose of this feature, as I see it, would be to have a view of newest installed extensions so we can easily find the cause of a change in the UI for instance, after installing a bunch of extensions and not paying much attention to the names and details.
I guess it would fall in this use case to sort extensions by update date.

**Comment by ramya-rao-a** [comment] 2018-09-25 19:00
Copying @MeikTranel's comment from #59315 as I think it provides yet another scenario where this feature is useful

> As a user, who enjoys reading patch notes it'd be cool if there was a way to sort an extension by the date of the update/install. That way i can still use autoupdate and in the event of an error that suddenly erupts i could help extension authors by providing context, when the issues first appeared and if its correlating with the installation or update of an extension.

**Comment by MeikTranel** [comment] 2018-09-25 20:11
Are we all agreeing that "updated date" is most interesting detail, thus should be the focus of this issue?

If so we should be updating the title? Installation date isn't really capturing it then. That would reduce the number of duplicate issues.

**Comment by johanngerell** [comment] 2019-06-19 08:41
Does anyone know if this issue is being looked into to get it forward? I really miss this feature, as it's impossible to discover new extensions in general and color themes in particular.

**Comment by MeikTranel** [comment] 2019-06-19 15:25
I do think they still have this on their mind. The last two sprints were really "secretive" when it came to microsoft internal development on vscode.. the UI team was working intensively on the iconography relaunch, which is in preview right now. I assume since the overarching extension UI issue #68527 is still on the iteration plan that means we'll see movement soon.

**Comment by misolori** [comment] 2019-06-24 16:01
@johanngerell yes, as @MeikTranel mentioned we have some explorations around updating our UI for extensions and are looking to enable sorting (see #68527). I'm hoping that after we update our iconography (#8017) that we'll be able to tackle this next.

**Comment by spartanatreyu** [comment] 2019-07-02 01:19
Just going to copy my [comment](https://github.com/microsoft/vscode/issues/68527#issuecomment-507477986) into this issue:

> Something I've found missing from the current functionality that would be handy to have would be a way to order extensions by install date.
> 
> I installed the Trailing Spaces extension to highlight any random trailing spaces that have slipped into the code and it worked great, but randomly a few hours later I encountered a problem with it where it was incorrectly highlighting lines that were had no whitespace issues.
> 
> I went to the extensions pane to remove the extension and couldn't remember what it was called. I clicked on the menu button (three dots) in the extension pane, first to show only the installed extensions (which hides the pre-installed and recommended extensions), then again to sort by installation date.
> 
> Currently we have:
> 
> - Sort By: Install Count
> - Sort By: Rating
> - Sort By: Name
> 
> but no "Sort By: Install Date".
> 
> It was only a minor nuisance to re-read all of my installed extensions (25 of them, mainly language syntax support extensions) to find the misbehaving one but this would be a nice quality of life fix to add for devs that are trying new extensions

**Comment by wctiger** [comment] 2021-06-30 16:00
Following up on this feature request. 
For me I have ~40 extensions installed and all of sudden some of them is making my intellisense slow (by comparing between all extension disabled and enabled).  So it will be really helpful if there is a way to just look at extensions that get updated most recently to help troubleshoot problems like this.

**Comment by evanrs** [comment] 2021-09-11 14:28
With so many extensions it can be hard to recall their names. The problem starts when installing new extensions — you want to try it, but you can't trust you'll be able to uninstall it. When you can't recall the name, that is.

Sorting by `installDate` would be quite useful for maintaining ones workspace — and, encouraging a more adventurous use of newer extensions.

**Comment by gmccullo** [comment] 2021-09-26 15:19
I need this too. It would make it a lot easier to figure what newly updated extension is  making VS Code run impossibly slow.

**Comment by dexterlakin** [comment] 2022-01-17 09:30
There's a bug with one of my recently installed extensions and this would be useful to figure out which one

**Comment by janderudder** [comment] 2022-01-18 06:43
After re-reading this whole thread and some of the related threads mentioning this one, I just want to mention that kind of two different features are being talked about. They are similar - indeed in some cases they serve the same purpose - but they are still different enough that it's worth clarifying, IMO.

So, in _sorting extensions by update date_, the "update date" part may be understood in two ways:

1. the date the extension source code was updated by its author on the marketplace
2. the date the extension package was installed locally on the user's machine

Case 2 includes the first installation and subsequent updates. Technically an update is made of deletion + new install of the extension (according to what I read).

Having a way to sort/filter recently updated extensions on the marketplace is cool for discoverability, but the second feature is more adapted to keeping track of one's own workspace state. 

- You want to read the docs of your last installed extensions but don't remember their names? Sort by local install date. 
- Your editor starts being slow all of a sudden? Check the last extensions updated on your machine.

Say you log in after a two months vacation: what's new updates to you is already old news on the marketplace.

To wrap this up, if you want this feature, it seems the way to go is to write an extension that tracks the creation date of each extension's subdirectory on the local machine.

**Comment by Dromantor** [comment] 2022-07-14 08:04
Since my FR was closed as a duplicate to this one, which it barely is but whatever, let me extend this feature request by what I requested:

It would be nice to have some notification which extensions were updated this session so that you don't have to actively scroll through the extensions panel and check if anything has indeed updated. Disable-able through a setting of course bc. it could annoy some users.

Use cases:
- You have some extension disabled bc. it's broken any you wait for an update to be able to use it again.
- You know some extensions require a reload after an update to work properly.
- You want to know when your favourite extension updated to check out the changelog.

This could also help to track down the source of performance problems like mentioned multiple times because the user already knows what updated last.

**Comment by heartacker** [comment] 2022-09-20 12:04
fantastic works
we can see the recently updated exts and also @outdated exts
thanks
![image](https://user-images.githubusercontent.com/1876302/191252407-d99dba49-43f6-48e4-b882-027334ca8ef3.png)

BTW: we could use one filter to see ext with two groups

and can we have this two
https://github.com/microsoft/vscode/issues/142007#issuecomment-1039798341

**Closed** 2022-09-27 06:42 UTC
Labels: feature-request, extensions

**Comment by RoestVrijStaal** [comment] 2022-09-27 07:11
Isn't it strange to close the ticket _before_ it has been verified as resolved?

**Comment by sandy081** [comment] 2022-09-27 07:49
We close the issue when it is fixed and get it tested. If there are any issues with the feature we will open new bugs.

@benibenj Is not this covered by a Test Plan Item?

**Comment by benibenj** [comment] 2022-09-27 09:35
This is indirectly covered by a test plan item (updates view test plan item)
