### ISSUE TITLE
Can't scroll Vscode terminal with ansicon

### ISSUE THREAD

**Issue by DanieleNardi** [microsoft/vscode#225389] opened 2024-08-12 09:01 UTC
Type: <b>Bug</b>

Hello,
I'm trying to use ansicon into Vscode terminal, in order to fix color issues with git bash.
So far so good, color issue has been solved, BUT now the terminal is not scrollable anymore.

How to replicate the issue:
in your Vscode workspace, add the following snippet:

"terminal.integrated.defaultProfile.windows": "Git Bash",
  "terminal.integrated.profiles.windows": {
    "Git Bash": {
      "source": "Git Bash",
      "path": "C:\\Program Files\\ANSICON\\x64\\ansicon.exe",
      "args": ["C:\\Program Files\\Git\\bin\\bash.exe","--login","-i"],
      "color": "terminal.ansiRed",
      "icon": "terminal-bash",
      "overrideName": true				
    }
  }

Then open a new terminal and launch a verbose command, like "ls -l" and you'll see that you can't scroll up and down to view the whole command output.

If I remove the "args" line, so referring just ansicon, the issue persists.
I tried to add "terminal.integrated.scrollback": 10000, but it doesn't solve the problem.
Also, the "reset" command doesn't solve the problem.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.80GB free)|
|Process Argv|--crash-reporter-id 6c095bde-a8aa-424d-8c44-379fcebd2e73|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
stack-overflow-view|4tr|0.1.1
better-comments|aar|3.0.2
path-intellisense|chr|2.9.0
doxdocgen|csc|1.4.0
arm|dan|1.7.4
vscode-markdownlint|Dav|0.55.0
ini-for-vscode|Dav|0.0.4
python-environment-manager|don|1.2.4
xml|Dot|2.5.1
dependi|fil|0.7.7
vscode-test-explorer|hbe|2.21.1
better-cpp-syntax|jef|1.27.1
svn-scm|joh|2.17.0
bash-ide-vscode|mad|1.42.0
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rainbow-csv|mec|3.12.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.14
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
test-adapter-converter|ms-|0.1.9
vscode-serial-monitor|ms-|0.12.0
material-icon-theme|PKi|5.9.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
bash-debug|rog|0.3.9
rust-analyzer|rus|0.3.2070
taskrunnercode|San|0.3.0
markdown-preview-enhanced|shd|0.8.13
even-better-toml|tam|0.19.2
shellcheck|tim|0.37.1
pdf|tom|1.2.2
gnu-mapfiles|tro|1.1.0
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.17.2
linkerscript|Zix|1.0.4

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by meganrogge** [comment] 2024-08-12 14:50
a gif would help

**Comment by DanieleNardi** [comment] 2024-08-13 05:39
> a gif would help
Here it is :)
![gitbashissue](https://github.com/user-attachments/assets/e91bcfc0-016b-4960-9785-31e84013fed6)

**Comment by meganrogge** [comment] 2024-08-13 17:48
does ansicon work with the windows terminal?

**Comment by DanieleNardi** [comment] 2024-08-21 10:54
same issue with windows terminal

**Comment by meganrogge** [comment] 2024-08-21 13:45
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-08-21 13:45 UTC
Labels: info-needed
