### ISSUE TITLE
Unnecessary errors on snippets not being under the extension folder

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#56510] opened 2018-08-15 23:18 UTC
- VSCode Version: 1.27 Insiders
- OS Version: Windows

Steps to Reproduce:

1. Install the `vscode-go` extension
2. Open the console in dev tools
3. See the below error

![image](https://user-images.githubusercontent.com/16890566/44178344-c8485900-a0a6-11e8-894f-055e56c367bf.png)

The snippet folder is already under the extension folder.
The difference is casing might be the reason for this error to show up.

**Comment by aeschli** [comment] 2018-08-16 10:29
duplicate of #56403

**Closed by aeschli** 2018-08-16 10:29 UTC
Labels: bug
