### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by rt442979559** [microsoft/vscode#137403] opened 2021-11-18 01:11 UTC
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.1-rc

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57005:22)
    at getPropertyOfType (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57665:24)
    at resolveESModuleSymbol (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49811:54)
    at getTargetOfNamespaceImport (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48996:28)
    at getTargetOfAliasDeclaration (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49230:28)
    at resolveAlias (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49275:30)
    at getSymbol (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47833:38)
    at resolveNameHelper (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48125:34)
    at resolveName (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48108:20)
    at resolveEntityName (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49447:42)
    at getTargetOfAliasLikeExpression (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49204:29)
    at getTargetOfExportAssignment (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49193:28)
    at getTargetOfAliasDeclaration (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49240:28)
    at resolveAlias (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49275:30)
    at resolveSymbol (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49265:67)
    at resolveExternalModuleSymbol (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49757:36)
    at getTargetOfNamespaceExportDeclaration (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49180:28)
    at getTargetOfAliasDeclaration (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49242:28)
    at resolveAlias (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49275:30)
    at tryResolveAlias (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49291:24)
    at getCandidateName (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72924:33)
    at Object.getSpellingSuggestion (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1873:33)
    at getSpellingSuggestionForName (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72914:23)
    at j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72855:24
    at resolveNameHelper (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48416:30)
    at getSuggestedSymbolForNonexistentSymbol (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72837:26)
    at resolveNameHelper (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48438:42)
    at resolveName (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48108:20)
    at getGlobalSymbol (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:58878:20)
    at getGlobalTypeSymbol (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:58860:20)
    at getGlobalType (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:58881:26)
    at initializeTypeChecker (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:85029:52)
    at Object.createTypeChecker (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47390:9)
    at Object.getTypeChecker (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114380:79)
    at synchronizeHostData (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159854:21)
    at Object.getProgram (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159975:13)
    at AutoImportProviderProject.Project.updateGraphWorker (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164989:53)
    at AutoImportProviderProject.Project.updateGraph (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164918:42)
    at AutoImportProviderProject.updateGraph (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165763:70)
    at Object.updateProjectIfDirty (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166400:45)
    at ConfiguredProject.Project.getPackageJsonAutoImportProvider (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165538:32)
    at ConfiguredProject.Project.updateGraph (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164956:26)
    at ConfiguredProject.updateGraph (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165911:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167635:25)
    at ProjectService.assignProjectToOpenedScriptInfo (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168718:44)
    at j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169058:97
    at Object.flatMap (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169058:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170216:46)
    at j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172149:88
    at IOSession.Session.executeWithRequestId (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172140:28)
    at IOSession.Session.executeCommand (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172149:33)
    at IOSession.Session.onMessage (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172175:35)
    at Interface.<anonymous> (j:\vsCode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174780:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by mjbvz** [comment] 2021-11-18 16:21
Duplicate of https://github.com/microsoft/TypeScript/issues/46587

**Closed by mjbvz** 2021-11-18 16:21 UTC

**Comment by mjbvz** [comment] 2021-11-18 17:15
To help us investigate and fix this issue, please share an example project and the steps you follow to trigger this issue. You can share this on https://github.com/microsoft/TypeScript/issues/46587
