### ISSUE TITLE
SCM Graph - Difficult to check incoming and outgoing commits

### ISSUE THREAD

**Issue by gmesta** [microsoft/vscode#228186] opened 2024-09-11 05:13 UTC
Hi 
Is there a way to get back the old incoming and outgoing history feature?
Its very difficult to check incoming commits in this new source control graph view
![image](https://github.com/user-attachments/assets/e5e0fc58-c041-4913-830a-8d6fbf3c3e50)

Thanks

**Comment by Littledogdudu** [comment] 2024-09-14 07:23
Very few people ask this question, but the actual use of the feature “Source Control Graph” is not as intuitive as it used to be.
1. The first question is already said above.
2. The second problem is that because it's another fixed pane, I need to adjust this pane when I'm modifying a lot of files so I can see the commit in its entirety, and it's not as easy as it seems because I have to adjust it almost every time
![图片](https://github.com/user-attachments/assets/59b50a7d-7d0c-4eca-a0b6-aec219e6e3ad)

I hope to be able to temporarily set it in the settings to keep the previous style.
Thanks

**Comment by alebrozzo** [comment] 2024-09-27 09:17
+1

The SC Graph gives me information that I don't need, but hides the good information we used to have, mainly the ability to see each incoming commit separately and also what the resulting code will look like once I pull everything. Same for outgoing. I loved this feature.
The graph is confusing, I don't understand all the color lines, I am not about to take NYC's subway. Why completely remove the old feature?

**Comment by alebrozzo** [comment] 2024-09-27 09:23
I guess all explanations are in this other ticket:

https://github.com/microsoft/vscode/issues/227727

**Comment by Littledogdudu** [comment] 2024-09-27 09:32
> I guess all explanations are in this other ticket:
> 
> #227727

Thanks, you are right

**Comment by lszomoru** [comment] 2024-12-10 12:42
Closing as duplicate of [#227727](https://github.com/microsoft/vscode/issues/227727)

**Closed by lszomoru** 2024-12-10 12:42 UTC
Labels: feature-request, scm
