### ISSUE TITLE
Code actions such as format on save are not triggered when closing the file and Auto Save enabled

### ISSUE THREAD

**Issue by ullumullu** [microsoft/vscode#177787] opened 2023-03-21 11:03 UTC
Type: <b>Bug</b>

1. Enable AutoSave via File > Auto Save
2. Define a code action on save (in your settings.json) such as:
    `"editor.formatOnSave": true`
     or
     ```
    "editor.codeActionsOnSave": [
      "source.organizeImports",
      "source.fixAll"
    ]
   ```
3. Modify a file and close it
4. Code actions are not triggered
5. Explicitly triggering a save via cmd+s triggers the code actions

For reference - the problem was discovered while working on a TypeScript project using the native language server organise imports functionality.

**Expected behaviour**

I'd expect that code actions on save would also get triggered when auto save is enabled (or at least when the file gets closed).

VS Code version: Code 1.75.0 (Universal) (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ullumullu** [comment] 2023-03-22 08:10
@mjbvz yes I can also reproduce this with the insiders build

```
Version: 1.77.0-insider (Universal)
Commit: b8e4c550bc87aa1db64e612706ac5238035e9cc2
Date: 2023-03-22T05:24:06.369Z (2 hrs ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes
```

The only "adjustment" needed is to configure code actions (configuring one of them would already be enough):

settings.json
```
{
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": [
            "source.organizeImports",
            "source.fixAll"
        ]
    },
    "files.autoSave": "afterDelay"
}
```

If I now add an unused import to a file while auto-save is enabled it is not getting removed without explicitly triggering. a save. Even closing the file is not triggering the code actions.

Another finding I had in the meantime while playing around with the auto-save settings as well. I can scope down the issue when `files.autoSave` is set to "afterDelay". The other two options "onFocusChange" and "onWindowChange" correctly trigger the code actions. 

Side note: adjusting `files.autoSaveDelay` seems to have no effect on the issue.

**Comment by mjbvz** [comment] 2023-03-29 21:18
Duplicate of #163920

Currently we only enable these actions on manual saves

**Closed by mjbvz** 2023-03-29 21:18 UTC
Labels: info-needed
