### ISSUE TITLE
terminal tooltip position blocks text selection

### ISSUE THREAD

**Issue by tgreen7** [microsoft/vscode#113310] opened 2020-12-22 18:23 UTC
- VSCode Version:1.52.1
- OS Version: macos 10.14.6 

Steps to Reproduce:

1. I am using the extension gitlens which is adding a tooltip to the branch name in the integrated terminal.
2. The tooltip on hover is blocked the text. This blocks a double click so I can't select the branch name.
<img width="1115" alt="Screen Shot 2020-12-21 at 12 33 25 PM" src="https://user-images.githubusercontent.com/10415101/102920342-7a467b80-443f-11eb-8760-ab2424b01ca0.png">

issue in gitlens: https://github.com/eamodio/vscode-gitlens/issues/1284

i also saw this closed issue https://github.com/microsoft/vscode/issues/99924 which said that a setting should have been added to disable these tooltips. Where is that setting?

Thanks.

**Comment by meganrogge** [comment] 2020-12-22 21:43
Duplicate of #15667

**Closed** 2020-12-22 21:44 UTC
Labels: *duplicate

**Comment by tgreen7** [comment] 2020-12-23 01:13
@meganrogge That issue is similar but mine is specific to the tooltips in the integrated terminal. I would like a setting to turn of the terminal tooltips but keep the editor ones or at least have a more fine grained control of which ones show up.

**Comment by meganrogge** [comment] 2020-12-30 05:15
@tgreen7 you should create a feature request for that

**Comment by eamodio** [comment] 2021-01-08 06:15
@tgreen7 I opened this here: https://github.com/microsoft/vscode/issues/114008
