### ISSUE TITLE
When typing Korean, Backspace unicode (red box) appears. (on Mac) 

### ISSUE THREAD

**Issue by doubled9** [microsoft/vscode#175308] opened 2023-02-24 07:55 UTC
Does this issue occur when all extensions are disabled?: Yes!

- VS Code Version: : 1.75.1
- Electron: 19.1.9
- Chromium: 102.0.5005.194
- Node.js: 16.14.2
- V8: 10.2.154.23-electron.0
OS: Darwin x64 21.6.0
- Sandbox: No
- OS Version: 12.6.3(21G419)
- Keyboard: Korean IME

Steps to Reproduce:

1. Select text,
2. Type Korean once.
3. And Stroke Backspace.
4. Typed Unicode Character “␈” (U+2408) https://www.compart.com/en/unicode/U+2408

https://user-images.githubusercontent.com/106290268/221121751-034f0292-0113-4972-96cf-09694dc6510d.mov

**Comment by alexdima** [comment] 2023-02-24 12:42
Duplicate of #148356

**Closed by alexdima** 2023-02-24 12:42 UTC

**Comment by bexoss** [comment] 2023-03-03 13:41
#171388
