### ISSUE TITLE
style in 'th' element breaks html autoformatting

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#18418] opened 2017-01-11 21:23 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10

```
<table>
    <thead style="">

</thead>
</table>
```
Auto formats to the same thing.

Expected formatting:

```
<table>
    <thead  style="">

</thead>
</table>
```

```
<table>
    <thead>
        <tr>
            <th style="width: 1%">#</th>
</tr>
</thead>
</table>
```

autoformats to the same thing

expected formatting:

```
<table>
    <thead>
        <tr>
            <th style="width: 1%">#</th>
        </tr>
    </thead>
</table>
```

removing the style properties produces the expected formatting

**Comment by aeschli** [comment] 2017-01-12 00:26
duplicate of #17849

**Closed by aeschli** 2017-01-12 00:26 UTC
Labels: format, html
