### ISSUE TITLE
Smoke Test: Don't get cross file intellisense in JS

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3509] opened 2016-02-26 16:48 UTC
* in the smoke test repo, add a new file bar.js:
```
exports.foo = 3;
```
* in app.js add the following:
```
var bar = require('./bar');
bar.
```

> No completions on bar

**Comment by alexandrudima** [comment] 2016-02-26 16:49
![image](https://cloud.githubusercontent.com/assets/5047891/13358791/528d443e-dcb1-11e5-92d8-e10f45871fcf.png)

**Comment by egamma** [comment] 2016-02-29 08:48
I cannot reproduce this with the following jsconfig.json

```json
{
    "compilerOptions": {
        "module": "commonjs"
    }
}
```

**Comment by joaomoreno** [comment] 2016-02-29 09:05
Documentation

**Comment by egamma** [comment] 2016-03-15 14:07
Upstream fix merged into our code.

**Closed by egamma** 2016-03-15 14:07 UTC
Labels: bug, upstream
