### ISSUE TITLE
Remembering opened files without having to close the app (e.g. after crashes or reboots)

### ISSUE THREAD

**Issue by RafaelQuirino** [microsoft/vscode#80317] opened 2019-09-04 13:50 UTC
Hello vscode team. I love the app, but one features displeases me. I usually don't close my editor (because i don't shutdown my OS). I rather do some reboots in terminal when needed. But in this case the app doesn't remember the opened (or closed) files. I notice it only remembers the files/folders configuration when i explicitly close the app, hitting the x button on top right corner and then reopen it. If i don't do this, the app reopens with the last configuration saved upon explicitly closing it. For instance, i open it, add a folder to workspace, open a file, close it, reopen it, it remembers this configuration. But then i open another file, and reboot the SO without closing the editor. Now when i open the editor it gives me the first configuration, i.e. it didn't remember the last file opened. 
I would like it to remember this configuration automatically, i.e. when i open a file or add a folder to the workspace the app automatically saves the new configuration. In the case of a crash or reboot, the app still reopens with the last configuration saved. Is it possible?
Best regards.

**Comment by usernamehw** [comment] 2019-09-04 18:35
Duplicate of #12058

**Closed** 2019-09-05 04:47 UTC
Labels: *duplicate
