### ISSUE TITLE
SQL syntax is not highlighted correctly

### ISSUE THREAD

**Issue by IvanAram1107** [microsoft/vscode#193899] opened 2023-09-24 03:51 UTC
Type: <b>Bug</b>

If I create an SQL script that has this:
```sql
INSERT INTO `customers` (`customerNumber`,`customerName`,`contactLastName`,`contactFirstName`,`phone`,`addressLine1`,`addressLine2`,`city`,`state`,`postalCode`,`country`,`salesRepEmployeeNumber`,`creditLimit`) 
VALUES
(276,'Anna\'s Decorations, Ltd','Hara','Anna','02 9936 8555','201 Miller Street','Level 15','North Sydney','NSW','2060','Australia',1611,'107800.00');
```
Visual Studio doesn't read the SQL syntax correctly, it shows the text white after Anna\\', and I think it is happening because it doesn't recognize the backslash or something similar

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.66GB free)|
|Process Argv|--crash-reporter-id df3e24fc-e2dc-4850-98fd-dd8d26566338|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
vscode-angular2-files|ale|1.6.4
ng-template|Ang|16.1.8
markdown-emoji|bie|0.3.0
path-intellisense|chr|2.8.4
angular-schematics|cyr|5.4.2
vscode-eslint|dba|2.4.2
python-environment-manager|don|1.2.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
angular2-switcher|inf|0.4.0
angular-file-changer|joh|0.0.4
Angular2|joh|16.0.1
angular-extension-pack|loi|1.1.0
vscode-language-babel|mgm|0.0.39
vscode-docker|ms-|1.26.0
flake8|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.20
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
arrr|obe|0.1.3
material-icon-theme|PKi|4.30.1
prisma|Pri|5.3.1
quicktype|qui|12.0.46
karma-problem-matcher|rct|1.0.1
java|red|1.22.1
angular-cli|seg|0.0.19
simontest|Sim|1.9.10
autoimport|ste|1.5.4
move-ts|str|1.12.0
shellcheck|tim|0.34.0
autocomplate-shell|tru|0.1.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-manifest-yaml|vmw|1.49.0
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-maven|vsc|0.42.0
vscode-spring-initializr|vsc|0.11.2
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by codespearhead** [comment] 2023-09-25 03:23
> Type: Bug
> 
> If I create an SQL script that has this:
> 
> ```sql
> INSERT INTO `customers` (`customerNumber`,`customerName`,`contactLastName`,`contactFirstName`,`phone`,`addressLine1`,`addressLine2`,`city`,`state`,`postalCode`,`country`,`salesRepEmployeeNumber`,`creditLimit`) 
> VALUES
> (276,'Anna\'s Decorations, Ltd','Hara','Anna','02 9936 8555','201 Miller Street','Level 15','North Sydney','NSW','2060','Australia',1611,'107800.00');
> ```
> 
> Visual Studio doesn't read the SQL syntax correctly, it shows the text white after Anna\', and I think it is happening because it doesn't recognize the backslash or something similar
> 
> VS Code version: Code 1.82.2 ([abd2f3d](https://github.com/microsoft/vscode/commit/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d), 2023-09-14T05:55:25.390Z) OS version: Windows_NT x64 10.0.22621 Modes:
> System Info
> Extensions (50)
> A/B Experiments

Are you running the latest version of VSCode? Because I can't reproduce the issue.

**Comment by IvanAram1107** [comment] 2023-09-25 06:29
If the latest version is 1.82.2 then yes I am

**Comment by alexr00** [comment] 2023-09-29 13:11
Duplicate of https://github.com/microsoft/vscode/issues/132944

**Closed by alexr00** 2023-09-29 13:11 UTC
