### ISSUE TITLE
SCROLLING IS CHOPPY AND ANNOYING

### ISSUE THREAD

**Issue by sreejithr** [Microsoft/vscode#47181] opened 2018-04-04 07:54 UTC
Issue Type: <b>Bug</b>

SCROLLING IS MESSED UP. Not that scrolling in general is great on Windows machines. But scroll performance in VS Code makes the rest of Windows look like a Mac.

I've 16GB of RAM on a Core i7 machine. It's choppy and there's >1sec lag with scroll gestures. It's 2018 for god sake.

How to reproduce?

Even with 1 file scrolling is choppy. But it gets worse after you use your screen touch screen to scroll.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|Memory (System)|15.84GB (6.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
vscode-emacs-friendly|lfs|0.8.2
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.3.0
gitblame|wad|2.4.1

</details>
Reproduces only with extensions

**Comment by bsvipas** [comment] 2018-04-04 07:57
Could you reproduce the same with **all** extensions disabled?

**Comment by bpasero** [comment] 2018-04-04 07:57
Duplicate of https://github.com/Microsoft/vscode/issues/13612

**Closed by bpasero** 2018-04-04 07:57 UTC
Labels: editor, editor-core
