### ISSUE TITLE
UI BUG in activity bar

### ISSUE THREAD

**Issue by whoizNiKHiL** [microsoft/vscode#193304] opened 2023-09-17 16:49 UTC
Type: <b>Bug</b>

When primary bar is set to right and we click on bottom options (account / settings), the popup/ modal closes itself by choosing one option. Overall the two options are hard to operate when on right side.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:51:20.981Z)
OS version: Linux x64 5.15.0-83-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|15.18GB (9.04GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0bc5accc-6ab2-40f9-a02c-999162a42d2e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
vscrpc:30673769
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by nikhilc6** [comment] 2023-09-17 17:10
It works fine on left as there is some margin. But on right there is no margin of popup / modal. So it just overlaps on your click.

**Comment by sbatten** [comment] 2023-09-19 15:45
@deepak1556 right now, native anchored menus (dropdowns or button-triggered menus) have this issue because electron will not compensate for mouse location. @bpasero's fix for context menus won't apply here because we pass an anchor over. should we consider if native menus are enabled for linux/windows that we ignore the anchor and use mouse  position instead.

alternatively, we could ditch native menus for the context menu service on non-macos desktop platforms regardless of titlebar style

**Comment by deepak1556** [comment] 2023-09-20 05:27
> native anchored menus (dropdowns or button-triggered menus) have this issue because electron will not compensate for mouse location

Is there an upstream issue for this I can look at ?

**Comment by sbatten** [comment] 2023-09-27 18:42
It's essentially this one https://github.com/microsoft/vscode/issues/113175

**Comment by deepak1556** [comment] 2023-09-28 01:46
Ah okay, I don't have way to move that issue forward since I lack repro on my setup. If I am not mistaken, @bpasero also made the change to native context menus to use mouse position https://github.com/microsoft/vscode/issues/113175#issuecomment-1655698829 and given the issue persists, I like the alternative to make custom context menus as default regardless of titlebar style.

**Comment by sbatten** [comment] 2023-09-28 21:33
I assume this means for Windows, Linux, and Web

**Comment by deepak1556** [comment] 2023-09-28 23:56
I was 👍 for Linux, is there a strong reason to make the change on Windows as well ?

**Comment by sbatten** [comment] 2023-09-29 01:32
I _think_ the same applies for those that use the native titlebar on WIndows

**Comment by rzhao271** [comment] 2024-12-13 23:14
Closing as duplicate of #167941

**Closed by rzhao271** 2024-12-13 23:14 UTC
Labels: under-discussion, workbench-auxsidebar
