### ISSUE TITLE
Integrated terminal ENV variables

### ISSUE THREAD

**Issue by thr67** [microsoft/vscode#123142] opened 2021-05-06 14:54 UTC
Hello,

It seems in the release 1.56, environment variables are not transmited anymore to the shell.

The following configuration works perfectly in 1.55.2 but doesn't work anymore in 1.56 :

"terminal.integrated.env.osx":
		{
			"LGIT_DIR":"git"
		}

1) Result of 'echo' command in an integrated terminal in 1.55.2
$ echo $LGIT_DIR 
git

2) Same thing in 1.56
echo $LGIT_DIR 

So, I downgraded from 1.56 to 1.55.2

Thank you.

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (21.79GB free)|
|Process Argv|--crash-reporter-id abb1a36d-b19c-416f-9108-62835239935f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
java|red|0.79.1
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by meganrogge** [comment] 2021-05-06 18:13
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by meganrogge** [comment] 2021-05-06 18:14
Duplicate of #122104

**Closed** 2021-05-06 18:21 UTC
Labels: *duplicate
