### ISSUE TITLE
vscode fills /tmp with sock files

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#20490] opened 2017-02-12 01:38 UTC
- VSCode Version: 1.9.1
- OS Version: Linux x64

Not sure if this is VSCode itself or one of the extensions, but I'm ending up with hundreds of these files in my `/tmp` directory:

![socks](https://cloud.githubusercontent.com/assets/13035517/22858908/9efee026-f0c3-11e6-8201-b032c3955d4f.png)

**Comment by joaomoreno** [comment] 2017-02-14 14:07
Duplicate of #7758

**Closed by joaomoreno** 2017-02-14 14:07 UTC
