### ISSUE TITLE
HTML Language Server throw a error,when click the annotation!

### ISSUE THREAD

**Issue by leeneo** [Microsoft/vscode#32971] opened 2017-08-22 17:39 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---

html-snippets|abu|0.1.0
live-html-previewer|hdg|0.2.0
beautify|Hoo|1.1.1
vs-color-picker|lih|0.6.0
easy-less|mrc|1.4.5
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.1.8
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:
1,Errors by HTML Language Server:
[Error - 上午1:27:30] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined
  Code: -32603 

2,Source code（The &lt;&gt; omitted ）:
!DOCTYPE html
html
head
	meta charset="UTF-8"
	meta name="viewport" content="width=640px, user-scalable=no" /
	<title>分屏动画</title>
	<style type="text/css">
		* {
			margin: 0;
			padding: 0;
			list-style: none;
		}
		html,body,.list {
			width: 100%;
			height: 100%;
		}
		.list {
			overflow: hidden;
			position: relative;
		}
		.list>li {
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
			display: none;
			position: absolute;
			background-size: cover!important;
		}
		.list>li:nth-child(1) {
			display: block;
			background: url(img/p1.jpg) center 0 no-repeat;
		}
		.list>li:nth-child(2) {
			background: url(img/p2.jpg) center 0 no-repeat;
		}

		.list>li:nth-child(3) {
			background: url(img/p3.jpg) center 0 no-repeat;
		}
		.list>li:nth-child(4) {
			background: url(img/p4.jpg) center 0 no-repeat;
		}
	</style>
/head
body
	ul class="list"
		li></li
		li></li
		li></li
		li></li
	/ul
/body
/html
<script src="js/jquery-2.1.3.min.js"></script>
<script type="text/javascript">

	//  此时我们先完成手指向上滑动屏里需要做的事情，根椐我们的分析，手指向上滑动时
	//  我们要让下一从屏幕的下方慢慢显示出来，而且滑动过程中手指滑运多少距离，屏幕
	//  就滑动多少距离。 
	//  所以在这里我们遇到了一个问题，我们需要根据当前屏来判断一下需要显示的下一屏
	//  是第几屏，此时我们能获取到的就是当前屏的编号。
	var aLi = $('.list > li');
	var iH = $(window).height();
	var strartY, moveY, endY, nowIndex, nextIndex;
	aLi.on('touchstart', function (ev) {
		nowIndex = $(this).index();
		strartY = ev.originalEvent.changedTouches[0].clientY;
		$(this).on('touchmove', function (ev) {
			endY = ev.originalEvent.changedTouches[0].clientY;
			if (strartY > endY) {
				nextIndex = nowIndex + 1;
				aLi.eq(nextIndex).show();
				moveY = strartY - endY;
				aLi.eq(nextIndex).css('top', iH - moveY);
				console.log(nextIndex);
			} else if (strartY < endY) {
				console.log('下');
			}
		});
		$(this).on('touchend', function () {
		});
	});
</script>

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment] 2017-08-23 06:43
duplicate of #30774

**Closed by aeschli** 2017-08-23 06:43 UTC
Labels: html, new release
