### ISSUE TITLE
JSONC has no icon

### ISSUE THREAD

**Issue by DusterTheFirst** [Microsoft/vscode#40534] opened 2017-12-19 21:35 UTC
- VSCode Version: 1.19.1
- OS Version: Windows 10 Build 16299.125

Steps to Reproduce:

1. Create JSON file
2. Set file association to `JSON with Comments`
3. See this ![image](https://user-images.githubusercontent.com/14093962/34179772-3980adcc-e4da-11e7-9c58-ba04780b2cb0.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-12-20 10:28
duplicate of #40244

**Closed by aeschli** 2017-12-20 10:28 UTC
