### ISSUE TITLE
Add some feedback help for writing snippet variables

### ISSUE THREAD

**Issue by bradzacher** [Microsoft/vscode#36716] opened 2017-10-23 00:46 UTC
When writing complex snippets with replacement, the onus is entirely on the user to figure out why a snippet failed to parse/replace.

Due to the syntax, it's pretty hard to track exactly why a snippet failed to parse.

It'd be great if you added some output with the error reason to make it easier to work with the system.

I.e. an error toast, or alternately a separate output log with detailed messages.

**Comment by jrieken** [comment] 2017-10-23 07:33
duplicate of #16702

**Closed by jrieken** 2017-10-23 07:33 UTC
Labels: api, editor
