### ISSUE TITLE
Javascript React Emmet is not working

### ISSUE THREAD

**Issue by kairxa** [Microsoft/vscode#15868] opened 2016-11-22 09:11 UTC
- VSCode Version: 1.7.1
- OS Version: macOS 10.12.1

Steps to Reproduce:

1. Open up a `.jsx` file
2. Pressing tab now no longer autocomplete `jsx` syntaxes.

Did I miss something on the changelog? I just updated it and suddenly it stops working. Running with `--disable-extension` still does not fix the problem. Apparently no issue about this has been raised in here so I'm quite confused right now whether it's an intended change or a local problem. Thanks.

#### Edit

`vscode@1.6.1` does not have this problem.

**Comment by kaiwood** [comment] 2016-11-22 12:34
Duplicate of  #14962 

@kairxa Looks like this will be fixed with the upcoming 1.7.2 release

**Comment by jrieken** [comment] 2016-11-22 12:41
closing as dup

**Closed by jrieken** 2016-11-22 12:41 UTC
