### ISSUE TITLE
markdown.copyFiles.destination don't work well

### ISSUE THREAD

**Issue by zhongqianli** [microsoft/vscode#211434] opened 2024-04-26 09:36 UTC
I read the guide in https://code.visualstudio.com/Docs/languages/markdown ,  try to change markdown.copyFiles.destination by add 
```
"markdown.copyFiles.destination": {
  "docs/**/*": "images/${documentBaseName}/"
}
```
It can work in "./docs", when I copy image to markdown file, it save to the directory "images/${documentBaseName}/".

![image](https://github.com/microsoft/vscode/assets/42531675/0b3d9ee8-3d62-45ea-a0bd-6e1a4baf5e84)

I need work in "./", so I change it to:
```
"markdown.copyFiles.destination": {
  "./**/*": "images/${documentBaseName}/"
}
```
but it failed, when I copy image to markdown file, it save to the directory "./" rather than "images/${documentBaseName}/".

![image](https://github.com/microsoft/vscode/assets/42531675/761d009e-be50-4076-87b3-d8457fbee292)

**Comment by mjbvz** [comment] 2024-04-29 17:05
Duplicate of [#211431](https://github.com/microsoft/vscode/issues/211431)

**Closed by mjbvz** 2024-04-29 17:05 UTC
