### ISSUE TITLE
All extensions missed

### ISSUE THREAD

**Issue by panathos** [microsoft/vscode#170056] opened 2022-12-26 19:29 UTC
Type: <b>Bug</b>

Started after update 1.74.2

2022-12-26 20:26:27.014 [error] [uncaught exception in sharedProcess]: A system error occurred (ENOENT: no such file or directory, scandir 'D:\Scoop\apps\vscode\1.74.2\data\user-data\clp\46568dd7c2f1ff3e98ade5c2dc152273.it'): Error: ENOENT: no such file or directory, scandir 'D:\Scoop\apps\vscode\1.74.2\data\user-data\clp\46568dd7c2f1ff3e98ade5c2dc152273.it'

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.07GB free)|
|Process Argv|d:/xampp/htdocs/bacdt/.vscode/yii1-xamp.code-workspace --crash-reporter-id b92a01d7-44bc-4d00-8663-cc1f36f3217f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (112)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
stylus|Ala|0.0.4
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
copy-relative-path|ale|0.0.2
html-end-tag-labels|ant|0.9.0
awarest-align|awa|1.1.0
emojisense|bie|0.9.1
markdown-checkbox|bie|0.4.0
vscode-intelephense-client|bme|1.8.2
language-hugo-vscode|bud|1.3.1
gotemplate|cas|0.4.0
path-intellisense|chr|2.8.4
regex|chr|0.4.0
codeswing|cod|0.0.21
gitignore|cod|0.9.0
macros|ctf|0.1.0
goto-documentation|cxf|0.0.1
autoit|Dam|1.0.10
reverse-search|Dan|2.0.2
vscode-eslint|dba|2.2.6
vscode-quick-select|dba|0.2.9
vscode-axe-linter|deq|4.5.0
vscode-new-file|dku|4.0.2
githistory|don|0.6.19
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
filter-lines|ear|1.0.0
vscode-html-css|ecm|1.13.1
vscode-hugo-themer|eli|1.2.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.10.3
auto-close-tag|for|0.5.14
gitkraken-authentication|git|1.0.3
todo-tree|Gru|0.0.220
editorenhancements|gur|1.0.1
svgeditor|hen|2.9.0
vscode-remark-hugo|Hit|0.2.13
vscode-dimmer|hoo|2.1.0
rest-client|hum|0.25.1
output-colorizer|IBM|0.1.2
vscode-dimmer-block|ima|2.2.0
easy-snippet|inu|0.6.3
customize-ui|ioc|0.1.65
monkey-patch|ioc|0.1.23
highlight-string-code|iuy|0.4.5
vscode-essentials|jab|1.6.0
search-editor-apply-changes|jak|0.1.1
vscode-placeholder-images|Jak|0.1.0
string-highlight|jen|0.0.8
vscode-text-pastry|jkj|1.3.1
svg|joc|1.4.26
vscode-peacock|joh|4.2.2
tasks-context|jsa|1.0.0
vscode-insertdatestring|jsy|2.3.1
vscode-smart-split-into-lines|Jul|0.0.1
vscode-format-context-menu|lac|1.0.4
vscode-regexp-preivew|le0|0.0.3
regexp-preview|Lou|0.1.5
gitless|maa|11.7.2
php-import-checker|mar|0.10.0
php-namespace-resolver|Meh|1.1.9
metago|met|4.3.1
MetaJump|met|1.4.0
MetaWord|met|1.3.0
git-graph|mhu|1.30.0
vscode-checkpoints|mic|1.3.3
dotenv|mik|1.0.1
vscode-deploy-reloaded|mkl|0.89.0
vscode-apache|mrm|1.2.0
vscode-language-pack-it|MS-|1.74.12140931
vscode-edge-devtools|ms-|2.1.1
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
sqltools|mtx|0.26.0
sqltools-driver-mysql|mtx|0.4.1
select-paragraph|nac|0.1.1
color-highlight|nau|2.5.0
php-docblocker|nei|2.7.0
gremlins|nho|0.26.0
incrementor|nms|1.0.3
indent-rainbow|ode|8.3.1
explorer-exclude|Pet|1.3.2
phpstorm-snippets|phi|1.1.2
material-icon-theme|PKi|4.23.1
vscode-template-literal-editor|pli|0.10.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
psi-header|psi|1.21.0
subtle-brackets|raf|3.0.0
calc|rai|2.3.1
explorer-exclude-vscode-extension|Red|1.2.2
LiveServer|rit|5.7.9
color-manager|roy|0.7.5
code-settings-sync|Sha|3.4.3
rewrap|stk|1.16.3
tabnine-vscode|Tab|3.6.31
tachyons-snippets|tho|0.0.3
vscode-mermaid-editor|tom|0.17.1
remove-empty-lines|use|0.0.12
highlight-matching-tag|vin|0.10.1
php-docblock-generator|vin|0.0.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
rainbow-tags|vol|0.4.1
gistfs|vsl|0.4.1
better-align|wwm|1.1.6
php-debug|xde|1.29.1
php-pack|xde|1.0.3
hugobot|zii|0.0.14
vscode-firstupper|zki|0.2.1

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by sandy081** [comment] 2022-12-27 10:39
What do you mean by all extensions are missed? Are they running? Are they not shown in extensions view?

**Comment by panathos** [comment] 2022-12-27 17:01
@sandy081 VSCode reported "0 extension installed", and no extension was functional. Close app & reopen, reload Window but no change. Turned off computer.

Today no problem with VSCode, started app and all extensions correctly loaded.

I don't have further information about extensions missed yesterday.

**Comment by sandy081** [comment] 2022-12-29 08:29
Ok, very strange. 

Closing it as the issue is resolved strangely. Please report back to us if you see it again with following logs

- F1 > Open View... > Shared
- F1 > Open View... > Window

**Closed** 2022-12-29 08:29 UTC
Labels: info-needed
