### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45558] opened 2018-03-12 06:54 UTC
From https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=0c0f5629-095c-7c4c-169c-927ca79e83ad

```
TypeError: Cannot read property 'type' of undefined
/vs/editor/common/viewLayout/viewLineRenderer.ts#516:34 (lineContent)
/vs/editor/common/viewLayout/viewLineRenderer.ts#320:34 (input)
/vs/editor/common/viewLayout/viewLineRenderer.ts#266:43 (renderViewLine)
/vs/editor/browser/viewParts/lines/viewLine.ts#220:17 (renderLine)
/vs/editor/browser/view/viewLayer.ts#592:30 (_finishRendering)
/vs/editor/browser/view/viewLayer.ts#449:7 (render)
/vs/editor/browser/view/viewLayer.ts#355:24 (renderLines)
/vs/editor/browser/viewParts/lines/viewLines.ts#513:21 (renderText)
/vs/editor/browser/view/viewImpl.ts#425:18 (_actualRender)
/vs/editor/browser/view/viewImpl.ts#383:29
```

**Comment by alexandrudima** [comment] 2018-04-04 09:35
Duplicate of #45735

**Closed by alexandrudima** 2018-04-04 09:35 UTC
Labels: error-telemetry
