### ISSUE TITLE
Opening a file changes its edit status, even if there is no change in file content

### ISSUE THREAD

**Issue by akankshagaur** [Microsoft/vscode#15276] opened 2016-11-10 04:55 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 7

**Steps to Reproduce:**

1. Double click a file from Explorer.

**Desired Behavior**

Edit status of file should not change

**Actual Behavior**

File status shown as edited. Requests save/dont save option on close

**Comment by bpasero** [comment] 2016-11-10 06:03
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by ramya-rao-a** [comment] 2016-11-16 19:16
@akankshagaur 
Does this happen with all file types? 
What extensions do have installed?
Like @bpasero suggested, please try with all extensions disabled and let us know if you still see the issue.

**Comment by ramya-rao-a** [comment] 2016-11-19 00:40
Closing this for now since we did not hear back for over a week.
@akankshagaur Please feel free to re-open this if you have any additional info

**Closed by ramya-rao-a** 2016-11-19 00:40 UTC
Labels: needs more info
