### ISSUE TITLE
Incorrect p10k display

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/vscode#122005] opened 2021-04-23 09:52 UTC
- VS Code Version: 1.55.2
- OS Version:  19043.962

Steps to Reproduce:

1. Install ZSH with p10k
2. Open terminal in VScode

Does this issue occur when all extensions are disabled?: Yes

Additionally:

If you change the font size, the problem is eliminated before reopening the terminal.
The problem came up recently, after one of the latest VScode or terminal updates or whatever.

New terminal:
![image](https://user-images.githubusercontent.com/35394377/115853847-46ea1c80-a432-11eb-8d58-48f67ba46e67.png)

Change font size:
![image](https://user-images.githubusercontent.com/35394377/115853973-6e40e980-a432-11eb-8b14-c89ab465b5ee.png)

WinTerminal:
![image](https://user-images.githubusercontent.com/35394377/115854085-92042f80-a432-11eb-919c-33289034153c.png)

**Comment by IllusionMH** [comment] 2021-04-23 18:11
/duplicate of #120129

Shuld be fixed Insiders build https://code.visualstudio.com/insiders/

**Closed** 2021-04-23 18:12 UTC
Labels: *duplicate
