### ISSUE TITLE
Grouping breakpoints

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vscode#95232] opened 2020-04-14 15:10 UTC
#64186

Sometimes I want to debug a specific feature of my project but I don' want to hit every breakpoint. So it would be nice if I don't need to disable every breakpoint which I don't need. Rather it would be helpful to enable or disable groups of breakpoints for a feature.
In my opinion, this feature is now easier to implement because of the development concerning breakpoints since December 2018.

**Comment by isidorn** [comment] 2020-04-15 08:09
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
Also Duplicate of https://github.com/microsoft/vscode/issues/64186

**Closed** 2020-06-29 13:59 UTC
Labels: *out-of-scope, debug, feature-request
