### ISSUE TITLE
Strange selection behavior in markdown editor

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#19318] opened 2017-01-25 00:51 UTC
Testing #19089 

In the example below, double clicking at this cursor position results in an odd selection behavior where the bracket on the previous line gets selected
![image](https://cloud.githubusercontent.com/assets/762848/22273360/2d195a6c-e255-11e6-8862-d46e190904b4.png)

![image](https://cloud.githubusercontent.com/assets/762848/22273355/1fc6efb4-e255-11e6-8b8d-9ea0d51fe776.png)

**Comment by mjbvz** [comment] 2017-01-25 02:35
Closing as a duplicate of #18494 since is behavior is another symptom of using the standard word range definition.

**Closed by mjbvz** 2017-01-25 02:35 UTC
Labels: bug, editor, markdown
