### ISSUE TITLE
TypeScript and JavaScript Language Features extension has crashed

### ISSUE THREAD

**Issue by goalg** [microsoft/vscode#103041] opened 2020-07-21 20:53 UTC
Issue Type: <b>Bug</b>

I am working through an ssh tunnel into a Ubuntu 16.04 VM on a cloud provider server, through two pcs separate and distinct pc's. The TypeScript and JavaScript Language Features extension has crashed on both. This really started happening (along with other extension crashes) after the June 2020 update was installed. 
I'm no expert, but I did work IT in another life, and I would guess that that update is buggy. 
I have also just installed The firebase SDK, and today the Firebase-admin SDK on the Ubuntu box. 
Good luck. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.14393
Remote OS version: Linux x64 4.4.0-185-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.45GB (4.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Ubuntu5|
|OS|Linux x64 4.4.0-185-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (1 x 2399)|
|Memory (System)|0.97GB (0.06GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.0
vscode-peacock|joh|3.7.2
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
debugger-for-chrome|msj|4.12.9
material-theme|zhu|3.8.5
vscode-eslint|dba|2.1.8

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-07-22 21:16
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by goalg** [comment] 2020-07-22 21:36
I see where you're going with that line of thought. I have not tried that yet, although I do have Code Insiders installed in my local boxes. I tried installing JSHint just today, and it returned the following error:

"Failed to load jshint library. Please install jshint in your workspace folder using 'npm install jshint' or globally using 'npm install -g jshint' and then press Retry."

Allow me to edify. my user on my ubuntu vm is named alex. Alex has sudo rights, but is not root. When I installed both the firebase client sdk and the firebase-admin sdk, I used the "sudo npm install" command with a -g flag. 

My root web directory on that vm is created and owned by the user alex. That directory is where I do the installations with the "sudo npm install" command sequence. 

I also log into the ssh tunnel with user alex. btw. 

If I had to start looking somewhere it would be user access. especially considering I'm using a -g flag with a sudo install in a directory that doesn't belong to root..   

These are permission rights for my root web directory on ubuntu: drwxrwxr-x

**Comment by goalg** [comment] 2020-07-22 21:58
Along that same thought pattern, I ran chmod 776 on my ubuntu vm root web directory. Installed jshint using the aforementioned recommended npm install "sudo npm install vshint" within ubuntu, and it installed and enabled the vshint extension. 
I believe this was caused due to root not having "write" privileges before I ran chmod 776. User alex is in the same group as root.

**Comment by mjbvz** [comment] 2020-07-22 23:07
/cc @roblourens for ssh permissions

Please test on insiders with extensions disable as well to make sure one of them is not causing this

**Comment by goalg** [comment] 2020-07-22 23:29
I did run Code Insiders with all extensions (except 'ssh remote') disabled. I installed firebase-admin sdk using 'sudo npm install -g firebase-admin --save'
No issues. 
Now the question is, because I did not listen, was it the extensions, or was it the chmod

**Comment by roblourens** [comment] 2020-07-23 04:44
I think it's best practice not to use `sudo npm install` especially since the remote server does not have the ability to escalate permissions, and you are probably not logging in as the superuser.

**Comment by mjbvz** [comment] 2020-07-23 18:04
Sounds like it could be a permissions issue.

If you have steps that we can follow to reproduce this, I can try to investigate further. Otherwise it sounds like you are unblocked?

**Comment by goalg** [comment] 2020-07-25 21:49
mjbvz That's what I thought too. alex is a sudo user in the ubuntu box. I ssh in as alex. The root page was created by the user alex. I had not chmod on that directory until 2 days ago. Before that here were the privileges on that base web page:
drwxr-xr-x
That means that the root user only had "read - execute" rights. Not write rights. I have been using the sudo command to install node.js, express.js, npm mysql, firebase-admin sdk, etc. I always flagged these installs -g (global). 
Two days ago, I ran a chmod 776 on that directory. The new privileges are:
drwxrwxr-x after the chmod. 
This has (so far) solved any issues with vs code extensions crashing.

**Comment by mjbvz** [comment] 2020-07-27 20:58
Ok, I'm closing this since it sounds expected given the permissions. The TypeScript server spawned by VS Code server does need read permissions for the workspace. If you are using a local TS version, VS Code also will need to be able to execute your local TypeScript version

**Closed by mjbvz** 2020-07-27 20:58 UTC
Labels: needs more info
