### ISSUE TITLE
Typesscript serviced died 5 times

### ISSUE THREAD

**Issue by sterlp** [microsoft/vscode#113454] opened 2020-12-26 20:06 UTC
Issue Type: <b>Bug</b>

Did some commits in the shell nad got this message "Typesscript serviced died 5 times ...".

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.57GB free)|
|Process Argv|. --crash-reporter-id 8f8f4765-3932-40ba-abd8-16e9f3d8a48c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.2
vscode-django|bat|1.0.1
npm-intellisense|chr|1.3.1
dart-code|Dar|3.18.0
flutter|Dar|3.18.0
python-extension-pack|don|1.6.0
gitlens|eam|11.1.0
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
Angular2|joh|11.0.0
MagicPython|mag|1.1.0
vscode-language-pack-de|MS-|1.52.2
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
vscode-typescript-tslint-plugin|ms-|1.3.2
awesome-flutter-snippets|Nas|2.0.4
quicktype|qui|12.0.46
vscodeintellicode|Vis|1.2.10
jinja|who|0.0.8
qf|Wsc|6.8.122

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspyt653:30237719
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt600:30239448

```

</details>

**Comment by mjbvz** [comment] 2021-01-04 20:45
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also please provide steps to reproduce 

/needsMoreInfo

**Comment by sterlp** [comment] 2021-01-05 17:37
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> Also please provide steps to reproduce
> 
> /needsMoreInfo

Currently I haven't any steps to reproduce the issue right now. Haven't tried sorry.

**Comment by mjbvz** [comment] 2021-01-16 01:27
Ok, closing since it isn't reproducible. If you see in insiders with extensions disabled, please let me know and I can investigate

**Closed by mjbvz** 2021-01-16 01:27 UTC
Labels: needs more info
