### ISSUE TITLE
css.completion.completePropertyWithSemicolon doesn't work after last update

### ISSUE THREAD

**Issue by calmeee** [microsoft/vscode#100684] opened 2020-06-21 09:11 UTC
`**<!--**` ⚠️⚠️ Do Not Delete This! bug_report_template ⚠️⚠️ -->

- VSCode Version: 1.46.1
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. Add `"css.completion.completePropertyWithSemicolon": false,` into settings.json
2. open `.css` file and start typing any property, e.g. `bg` for `background`, then press **Tab**

**Expected result:**
css property is completed with colon and without semicolon

**Actual result:**
css property is completed also with semicolon

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by calmeee** [comment] 2020-06-21 09:14
On disabling all extensions, semicolon is still added

**Comment by aeschli** [comment] 2020-06-26 12:26
It was caused by a bug in the language server. Fixed by an server update: https://github.com/microsoft/vscode/commit/ebbb51635e6545940eb9f3e47ab338035cd8a117

**Closed by aeschli** 2020-06-26 12:26 UTC
