### ISSUE TITLE
Typing exit in terminal results in "The terminal process "" resulted with exit code 1" which requires manual interaction to get rid of

### ISSUE THREAD

**Issue by elibroftw** [microsoft/vscode#137634] opened 2021-11-22 06:09 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Windows, cmd as default terminal
2. Focus  to terminal
2. Enter exit
3. Watch bottom right for notification that requires manual interaction to get rid of.
Is there a way to exit the terminal only using keyboard shortcuts?

**Comment by mamphis** [comment] 2021-11-22 08:39
Hi @elibroftw!

You can use this command and assign a Keyboard shortcut.
![image](https://user-images.githubusercontent.com/10652205/142829263-e9fa288c-5d56-4383-b3c7-5be527ccfcc5.png)


But for me (Version: 1.63.0-insider (system setup)) the terminal is closing properly when typing `exit` in the command prompt.

**Comment by elibroftw** [comment] 2021-11-22 15:30
The issue only happens sometimes. It doesn't happen all the time. The exit code is 9009.
![image](https://user-images.githubusercontent.com/21298211/142888919-6d0904d7-2fd7-4840-aaeb-cdb2cad7cc48.png)

**Comment by elibroftw** [comment] 2021-11-22 15:31
But thanks for the command name, I rebinded `Ctrl + Shift + W` to kill the terminal instance.

**Comment by meganrogge** [comment] 2021-11-30 21:19
I can't reproduce the issue. Please open a new one with repro steps if you can do repro it consistently

**Closed by meganrogge** 2021-11-30 21:19 UTC
