### ISSUE TITLE
SCM icon lost when unfocuse

### ISSUE THREAD

**Issue by qin-nz** [Microsoft/vscode#40562] opened 2017-12-20 09:15 UTC
- VSCode Version: 1.19
- OS Version: Ubuntu 16.04
![tim 20171220161432](https://user-images.githubusercontent.com/6998071/34199528-080886be-e5a9-11e7-99a1-ad7761876d5f.png)

In the morning, everything is OK, but now I open vscode and can't find SCM icon.
I try View>SCM, it appear.
But when I focus on other plane, it disappear again.

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-12-20 09:33
@isidorn again... something seems to be broken :-/

**Comment by isidorn** [comment] 2017-12-20 09:59
@qin-nz can you please try to answer my questions from https://github.com/Microsoft/vscode/issues/40531#issuecomment-353006558

Closing this issue as a duplicate of that one and let's continue the discussion there

**Closed by isidorn** 2017-12-20 09:59 UTC
Labels: workbench-layout
