### ISSUE TITLE
When pasting code from the clipboard, the HTML tag is closed incorrectly

### ISSUE THREAD

**Issue by mnosal** [microsoft/vscode#229474] opened 2024-09-24 05:41 UTC
Type: <b>Bug</b>

If I have a code in my clipboard, for example:

```
<div class="article-blocks__item">
       <h4>Lorem ipsum...</h4>
       <p>Lorem ipsum...</p>
</div>
```

and I paste it to the page, the program closes the first tag and it shouldn't do anything. I get the following code:

```
<div class="article-blocks__item"></div> <- here comes the closure
       <h4>Lorem ipsum...</h4>
       <p>Lorem ipsum...</p>
</div>
```

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.05GB free)|
|Process Argv|G:\\__projekty-w-toku\\2024-08__My-Family-Home\\_kodowanie --crash-reporter-id af75efa5-dc7d-4e35-912b-23fa2f18f2c6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
replacerules|bhu|0.4.2
vscode-eslint|dba|3.0.10
xml|Dot|2.5.1
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
html-slim-scss-css-class-completion|gen|1.7.8
live-sass|gle|6.1.2
minify|Hoo|0.4.3
ftp-sync|luk|0.3.9
rainbow-csv|mec|3.12.0
vscode-autoprefixer|mrm|3.0.1
vscode-scss|mrm|0.10.0
vscode-language-pack-pl|MS-|1.93.2024091109
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
live-server|ms-|0.4.15
LiveServer|rit|5.7.9
eplcode|som|0.0.1
material-theme|zhu|3.17.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564

```

</details>

**Comment by aeschli** [comment] 2024-09-24 07:45
duplicate of https://github.com/microsoft/vscode/issues/227859

**Closed by aeschli** 2024-09-24 07:45 UTC
