### ISSUE TITLE
extension view

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#73691] opened 2019-05-13 19:31 UTC
- atm the extension view refresh everytime you move to another tab.

    actually this is the default behavior for the whole editor, but in the case of extensions it has proven to be a bad decision, why ? 
    because lots of extensions have gifs and images in their readme & everytime the view gets reloaded, all of the images and data gets reloaded as well
    also the scrolling position, sometimes the description is very long and i need to go back and forth between the extension view and the editor settings/keybindings to have an idea of how the extension works, but with the constant reload of the view it gets very frustrating.

- another issue is once the extension tab is closed, you can't reopen it back like any other editor view, not sure why & if the editor got reloaded/closed all the extension tabs are closed & without the persistent option i have to go search for them again which is also hard because of the sort by algorithm that shows a big log of totally unrelated extensions.

- also in case you have the extension tab in a split view, because the view is read-only it means u cant activate it with a mouse click like any other tab,
which means if u tried to close it you will close a different tab "the previously focused one" and your only solution would clicking on the extension tab it self to make it active.

**Comment by gjsjohnmurray** [comment] 2019-05-13 20:58
First point looks like a duplicate of #27498

**Comment by mjbvz** [comment] 2019-05-13 22:32
Duplicate of  #27498

Please open separate issues for the other two points

**Closed by mjbvz** 2019-05-13 22:32 UTC
Labels: extensions

**Comment by ctf0** [comment] 2019-05-14 05:36
for ref https://github.com/microsoft/vscode/issues/73703 & https://github.com/microsoft/vscode/issues/73704
