### ISSUE TITLE
VScode is getting frozen on rhel 7.9

### ISSUE THREAD

**Issue by outjoker** [microsoft/vscode#121073] opened 2021-04-12 07:33 UTC
- VS Code Version: 1.55.1
- OS Version: linux (rhel 7.9)

Steps to Reproduce:

1. I tried to open an existing project/ new window in vscode.
2. the window opens up and thereafter i am not able to do anything, all the operations inside the window have been frozen
3. i tried to uninstall and re-install, but the problem still persists

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2021-04-12 08:43
/duplicate of #115784

New Electron versions don't support CentOS 7. See linked issue for details and probable workarounds

**Closed** 2021-04-12 08:43 UTC
Labels: *duplicate, new release
