### ISSUE TITLE
 Cannot read property 'value' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#38187] opened 2017-11-13 06:26 UTC
Issue Id: <b>c17cc017-0d12-b1e1-e3e3-5d5960fa383b</b><br /><br />*Versions* <br />- 1.18.0<br />*Stack* <br />TypeError: Cannot read property 'value' of null<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L246:16 (value)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L246:16 (value))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1031:0 (_run)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L1031:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L736:0 (_chainedError)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L736:0 (_chainedError))<br />[/vs/base/common/winjs.base.raw.js#L1209:0 (onError)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L1209:0 (onError))<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1041:0 (_run)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/winjs.base.raw.js#L1041:0 (_run))<br />

**Comment by alexandrudima** [comment] 2017-12-06 12:04
Duplicate of #37677

**Closed by alexandrudima** 2017-12-06 12:04 UTC
Labels: bug, error-telemetry
