### ISSUE TITLE
VS Code doesn't follow typescript@beta (2.0.0) update

### ISSUE THREAD

**Issue by psnider** [Microsoft/vscode#10766] opened 2016-08-22 00:00 UTC
- VSCode Version: 1.4.0
- OS Version: Mac 10.11.6

Steps to Reproduce:

1.  Create a workspace as detailed in http://stackoverflow.com/questions/38797506/typescript-typings-error-when-using-es6-shim-promise-all
2. Open a VS Code instance pointing to the workspace.
3. Notice that it shows an error on line #9:
```
    return p
```
The error is:
```
[ts] 
Type 'Promise<Promise<boolean>[]>' is not assignable to type 'Promise<boolean[]>'.
  Type 'Promise<boolean>[]' is not assignable to type 'boolean[]'.
    Type 'Promise<boolean>' is not assignable to type 'boolean'.
(local var) p: Promise<Promise<boolean>[]>
```

**Note** that if you compile this same code with version 2.0.0 of the typescript compiler, it no longer issues an error.

**Comment by psnider** [comment] 2016-08-22 00:24
BTW, I don't have typescript installed globally, but it is installed in my workspace via:
```
npm install typescript@beta --save-dev
```

**Comment by alexandrudima** [comment] 2016-08-22 07:40
fyi @dbaeumer

**Comment by michaeljota** [comment] 2016-09-14 19:22
Did this get solved in the 1.5 update? I mean, now you can select if want to use workspace typescript compiler instead.

**Comment by dbaeumer** [comment] 2016-09-14 20:23
You can also set the typescript.tsdk variable to make this persistent for a workspace

**Comment by waderyan** [comment] 2016-09-14 20:43
@psnider thank you for opening this issue. Sorry for the delay this fell through my query. 

Is this resolved for you now with 1.5 update (as @michaeljota asks above)?
Can you confirm you've followed the steps as described [here](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions)?

**Comment by psnider** [comment] 2016-09-16 20:53
Yes, it seems that both changes work:
- When I didn't have **typescript.tsdk** set, *Code* prompted me for using the locally installed typescript or the default.
- When I set **typescript.tsdk**, *Code* seemed to use the locally installed typescript as I expected.

Thanks

BTW, for me, on a Mac, the reference on the [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) page isn't **File > Preferences** but rather **Code > Preferences**.

**Comment by michaeljota** [comment] 2016-09-17 20:02
I think you should close this issue then. :).

**Comment by waderyan** [comment] 2016-09-20 17:10
Closing as the issue is resolved for OP.

**Closed by waderyan** 2016-09-20 17:10 UTC
Labels: typescript
