### ISSUE TITLE
Slow startup issue

### ISSUE THREAD

**Issue by avranju** [Microsoft/vscode#21813] opened 2017-03-02 18:28 UTC
[8f5f_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814715/8f5f_renderer.cpuprofile.txt)
[8f5f_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814716/8f5f_main.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15033</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3492)</code>
- Memory (System): <code>63.95GB (38.13GB free)</code>
- Memory (Process): <code>143.11MB working set (149.40MB peak, 104.52MB private, 35.40MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|30|
|main|app.isReady => window.loadUrl()|293|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|305|
|renderer|require(workbench.main.js)|1183|
|renderer|create extension host => extensions onReady()|1774|
|renderer|restore viewlet|285|
|renderer|restore editor view state|785|
|renderer|overall workbench load|2249|
|main + renderer|start => extensions ready|3753|
|main + renderer|start => workbench ready|4083|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\rajave\8f5f_main.cpuprofile.txt`
-`C:\Users\rajave\8f5f_renderer.cpuprofile.txt`

**Comment by jrieken** [comment] 2017-03-06 16:54
dupe of  #22086

**Closed by jrieken** 2017-03-06 16:54 UTC
Labels: perf-profile
