### ISSUE TITLE
Opening a Jupyter notebook disrupts existing SSH connection with the remote 

### ISSUE THREAD

**Issue by Avishka-Perera** [microsoft/vscode#196022] opened 2023-10-19 18:00 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.1
- OS Version: Local: Ubuntu 22.04, Remote: Ubuntu 20.04
- Jupyter extension version: v2023.9.1102792234
- Remote SSh extension version: v0.106.5
- Python extension version: v2023.18.0

I have two servers one with Ubuntu 20.04 and the other with 22.04. This bug occurs only in the 20.04 server. When I connect to the remote server with vscode, Remote SSH gives the following logs
```
[23:22:11.782] Log Level: 2
[23:22:11.796] VS Code version: 1.83.1
[23:22:11.796] Remote-SSH version: remote-ssh@0.106.5
[23:22:11.796] linux x64
[23:22:11.797] SSH Resolver called for "ssh-remote+192.248.10.120", attempt 1
[23:22:11.798] "remote.SSH.useLocalServer": true
[23:22:11.799] "remote.SSH.useExecServer": false
[23:22:11.799] "remote.SSH.path": undefined
[23:22:11.799] "remote.SSH.configFile": undefined
[23:22:11.799] "remote.SSH.useFlock": true
[23:22:11.799] "remote.SSH.lockfilesInTmp": false
[23:22:11.799] "remote.SSH.localServerDownload": auto
[23:22:11.800] "remote.SSH.remoteServerListenOnSocket": false
[23:22:11.800] "remote.SSH.showLoginTerminal": false
[23:22:11.800] "remote.SSH.defaultExtensions": []
[23:22:11.800] "remote.SSH.loglevel": 2
[23:22:11.801] "remote.SSH.enableDynamicForwarding": true
[23:22:11.801] "remote.SSH.enableRemoteCommand": false
[23:22:11.801] "remote.SSH.serverPickPortsFromRange": {}
[23:22:11.802] "remote.SSH.serverInstallPath": {}
[23:22:11.806] SSH Resolver called for host: 192.248.10.120
[23:22:11.806] Setting up SSH remote "192.248.10.120"
[23:22:11.809] Acquiring local install lock: /tmp/vscode-remote-ssh-c940f595-install.lock
[23:22:11.813] Looking for existing server data file at /home/avishka/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-c940f595-f1b07bd25dfad64b0167beb15359ae573aecd2cc-0.106.5-tr/data.json
[23:22:11.813] Using commit id "f1b07bd25dfad64b0167beb15359ae573aecd2cc" and quality "stable" for server
[23:22:11.818] Install and start server if needed
[23:22:11.821] PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
[23:22:11.821] Checking ssh with "ssh -V"
[23:22:11.830] > OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022

[23:22:11.833] askpass server listening on /run/user/1000/vscode-ssh-askpass-7020fefe66231ce577fa8e1205be4c537f8dbf9c.sock
[23:22:11.833] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-0454306672e9df386688d3aecf4bacb4fc8d290b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","33111","-o","ConnectTimeout=15","192.248.10.120"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/avishka/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-c940f595-f1b07bd25dfad64b0167beb15359ae573aecd2cc-0.106.5-tr/data.json"}
[23:22:11.833] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/avishka/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.5/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/snap/code/143/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/avishka/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.5/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-7020fefe66231ce577fa8e1205be4c537f8dbf9c.sock"}
[23:22:11.838] Spawned 34845
[23:22:11.941] > local-server-1> Running ssh connection command: "-v -T -D 33111 -o ConnectTimeout=15 192.248.10.120"
[23:22:11.946] > local-server-1> Spawned ssh, pid=34853
[23:22:11.949] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022
[23:22:12.137] stderr> debug1: Server host key: ssh-ed25519 SHA256:O2Q3Ot00kHRnuJux4A/9oLbeeXAGaIr8YCr9QFMlJYk
[23:22:12.416] stderr> Authenticated to 192.248.10.120 ([192.248.10.120]:22) using "publickey".
[23:22:13.079] > Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-164-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Thu 19 Oct 2023 11:22:12 PM +0530
> 
>   System load:                0.08
>   Usage of /home:             88.7% of 468.38GB
>   Memory usage:               1%
>   Swap usage:                 0%
>   Temperature:                40.0 C
>   Processes:                  541
>   Users logged in:            1
>   IPv4 address for enp0s31f6: 192.248.10.120
> 
>   => /home is using 88.7% of 468.38GB
> 
>  * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
>    just raised the bar for easy, resilient and secure K8s cluster deployment.
> 
>    https://ubuntu.com/engage/secure-kubernetes-at-the-edge
> 
> Expanded Security Maintenance for Applications is not enabled.
> 
> 9 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> 22 additional security updates can be applied with ESM Apps.
> Learn more about enabling ESM Apps service at https://ubuntu.com/esm
> 
> New release '22.04.3 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> 15 updates could not be installed automatically. For more details,
> see /var/log/unattended-upgrades/unattended-upgrades.log
[23:22:13.111] > ready: 8deba43114ee
[23:22:13.132] > Linux 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023
[23:22:13.133] Platform: linux
[23:22:13.157] > /bin/bash
[23:22:13.158] Shell: bash
[23:22:13.158] Creating bash subshell inside "bash"
[23:22:13.239] > bash version:  5.0.17(1)-release
[23:22:13.245] > bash version:  5.0.17(1)-release
[23:22:13.349] > 8deba43114ee: running
[23:22:13.390] > Acquiring lock on /home/avishka/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/vscode-remote-lock.avishka.f1b07bd25dfad64b0167beb15359ae573aecd2cc
[23:22:13.395] > Found existing installation at /home/avishka/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc...
[23:22:13.396] > Checking /home/avishka/.vscode-server/.f1b07bd25dfad64b0167beb15359ae573aecd2cc.log and /home/avishka/.vscode-server/.f1b07bd25dfad64b0167beb15359ae573aecd2cc.pid for a running server
[23:22:13.398] > Looking for server with pid: 26425
[23:22:13.435] > Found running server...
>  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
[23:22:13.436] > * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[23:22:13.449] > Checking server status on port 43299 with wget
[23:22:13.462] > 8deba43114ee: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==43299==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
[23:22:13.464] > tmpDir==/run/user/1012==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==aa111111-11a1-1a1a-111a-aa11a1a1a111==
> 8deba43114ee: end
[23:22:13.464] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==43299==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==tmpDir==/run/user/1012==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==aa111111-11a1-1a1a-111a-aa11a1a1a111==

[23:22:13.465] Remote server is listening on port 43299
[23:22:13.465] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":43299},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1012","platform":"linux","connectionToken":"aa111111-11a1-1a1a-111a-aa11a1a1a111"},"installUnpackCode":""}
[23:22:13.466] Persisting server connection details to /home/avishka/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-c940f595-f1b07bd25dfad64b0167beb15359ae573aecd2cc-0.106.5-tr/data.json
[23:22:13.470] Starting forwarding server. local port 46703 -> socksPort 33111 -> remotePort 43299
[23:22:13.470] Forwarding server listening on port 46703
[23:22:13.470] Waiting for ssh tunnel to be ready
[23:22:13.472] [Forwarding server port 46703] Got connection 0
[23:22:13.473] Tunneled port 43299 to local port 46703
[23:22:13.473] Resolved "ssh-remote+192.248.10.120" to "port 46703"
[23:22:13.484] ------




[23:22:13.499] [Forwarding server port 46703] Got connection 1
[23:22:13.601] [Forwarding server port 46703] Got connection 2
[23:22:14.408] [Forwarding server port 46703] Got connection 3
[23:22:14.409] [Forwarding server port 46703] Got connection 4
```

Whenever I open a Jupyter notebook, the connection is broken.
![image](https://github.com/microsoft/vscode/assets/74392492/e5a21c3f-ea37-4c29-86c6-a47f95be8551)

Remote SSH also makes more logs now. Which is not seen in my Ubuntu 22.04 server
```
[23:28:09.120] SSH Resolver called for "ssh-remote+192.248.10.120", attempt 2, (Reconnection)
[23:28:09.124] SSH Resolver called for host: 192.248.10.120
[23:28:09.124] Setting up SSH remote "192.248.10.120"
[23:28:09.127] Acquiring local install lock: /tmp/vscode-remote-ssh-c940f595-install.lock
[23:28:09.130] Looking for existing server data file at /home/avishka/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-c940f595-f1b07bd25dfad64b0167beb15359ae573aecd2cc-0.106.5-tr/data.json
[23:28:09.132] Found local server running: {"remoteListeningOn":{"port":43299},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1012","platform":"linux","connectionToken":"aa111111-11a1-1a1a-111a-aa11a1a1a111","pid":34845,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-0454306672e9df386688d3aecf4bacb4fc8d290b.sock","socksPort":33111,"startupTime":1697737931839}
[23:28:09.133] Running server is stale. Ignoring
[23:28:09.136] Using commit id "f1b07bd25dfad64b0167beb15359ae573aecd2cc" and quality "stable" for server
[23:28:09.142] Install and start server if needed
[23:28:09.147] askpass server listening on /run/user/1000/vscode-ssh-askpass-e7e1da0b36d018587054bf6eb824a666e53e8e2f.sock
[23:28:09.147] Spawning local server with {"serverId":2,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-a35f7eb982fca121d2d78f2b7d63d91d556869e9.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","33111","-o","ConnectTimeout=15","192.248.10.120"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/avishka/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-c940f595-f1b07bd25dfad64b0167beb15359ae573aecd2cc-0.106.5-tr/data.json"}
[23:28:09.147] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/avishka/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.5/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/snap/code/143/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/avishka/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.5/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-e7e1da0b36d018587054bf6eb824a666e53e8e2f.sock"}
[23:28:09.153] Spawned 35020
[23:28:09.154] Failed to set up socket for dynamic port forward to remote port 43299: Socket closed. Is the remote port correct?
[23:28:09.248] > local-server-2> Running ssh connection command: "-v -T -D 33111 -o ConnectTimeout=15 192.248.10.120"
[23:28:09.252] > local-server-2> Spawned ssh, pid=35028
[23:28:09.256] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022
[23:28:09.541] stderr> debug1: Server host key: ssh-ed25519 SHA256:O2Q3Ot00kHRnuJux4A/9oLbeeXAGaIr8YCr9QFMlJYk
[23:28:09.863] stderr> Authenticated to 192.248.10.120 ([192.248.10.120]:22) using "publickey".
[23:28:09.864] stderr> bind [::1]:33111: Address already in use
[23:28:09.864] stderr> bind [127.0.0.1]:33111: Address already in use
[23:28:09.864] stderr> channel_setup_fwd_listener_tcpip: cannot listen to port: 33111
[23:28:09.865] stderr> Could not request local forwarding.
[23:28:10.647] > Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-164-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Thu 19 Oct 2023 11:28:09 PM +0530
> 
>   System load:                0.16
>   Usage of /home:             88.7% of 468.38GB
>   Memory usage:               1%
>   Swap usage:                 0%
>   Temperature:                40.0 C
>   Processes:                  543
>   Users logged in:            1
>   IPv4 address for enp0s31f6: 192.248.10.120
> 
>   => /home is using 88.7% of 468.38GB
> 
>  * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
>    just raised the bar for easy, resilient and secure K8s cluster deployment.
> 
>    https://ubuntu.com/engage/secure-kubernetes-at-the-edge
> 
> 1 device has a firmware upgrade available.
> Run `fwupdmgr get-upgrades` for more information.
> 
> 
> Expanded Security Maintenance for Applications is not enabled.
> 
> 9 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> 22 additional security updates can be applied with ESM Apps.
> Learn more about enabling ESM Apps service at https://ubuntu.com/esm
> 
> New release '22.04.3 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> 15 updates could not be installed automatically. For more details,
> see /var/log/unattended-upgrades/unattended-upgrades.log
[23:28:10.693] > ready: 9f8ef0798838
[23:28:10.759] > Linux 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023
[23:28:10.759] Platform: linux
[23:28:10.805] > /bin/bash
[23:28:10.806] Shell: bash
[23:28:10.807] Creating bash subshell inside "bash"
[23:28:10.901] > bash version:  5.0.17(1)-release
[23:28:10.904] > bash version:  5.0.17(1)-release
[23:28:11.061] > 9f8ef0798838: running
[23:28:11.107] > Acquiring lock on /home/avishka/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/vscode-remote-lock.avishka.f1b07bd25dfad64b0167beb15359ae573aecd2cc
[23:28:11.119] > Found existing installation at /home/avishka/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc...
> Checking /home/avishka/.vscode-server/.f1b07bd25dfad64b0167beb15359ae573aecd2cc.log and /home/avishka/.vscode-server/.f1b07bd25dfad64b0167beb15359ae573aecd2cc.pid for a running server
> Looking for server with pid: 26425
[23:28:11.160] > Running ssh connection command... /home/avishka/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/avishka/.vscode-server/.f1b07bd25dfad64b0167beb15359ae573aecd2cc.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     CONDA_EXE=/opt/conda/bin/conda
>     _CE_M=
>     LC_ADDRESS=C.UTF-8
>     LC_NAME=C.UTF-8
>     LC_MONETARY=C.UTF-8
>     PWD=/home/avishka
>     LOGNAME=avishka
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/avishka
>     LANG=C.UTF-8
>     LC_PAPER=C.UTF-8
>     VSCODE_AGENT_FOLDER=/home/avishka/.vscode-server
>     SSH_CONNECTION=43.250.240.16 62981 192.248.10.120 22
>     XDG_SESSION_CLASS=user
>     LC_IDENTIFICATION=C.UTF-8
>     _CE_CONDA=
>     USER=avishka
>     CONDA_SHLVL=0
>     SHLVL=1
>     LC_TELEPHONE=C.UTF-8
>     LC_MEASUREMENT=C.UTF-8
>     XDG_SESSION_ID=94
>     CONDA_PYTHON_EXE=/opt/conda/bin/python
>     XDG_RUNTIME_DIR=/run/user/1012
>     SSH_CLIENT=43.250.240.16 62981 22
>     LC_TIME=C.UTF-8
>     XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
>     PATH=/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/texlive/2023/bin/x86_64-linux
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1012/bus
>     LC_NUMERIC=C.UTF-8
>     _=/usr/bin/printenv
[23:28:11.161] > Removing old logfile at /home/avishka/.vscode-server/.f1b07bd25dfad64b0167beb15359ae573aecd2cc.log
> Spawned remote server: 26997
[23:28:11.187] > Waiting for server log...
[23:28:11.202] > Waiting for server log...
[23:28:11.244] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[23:28:11.251] > 9f8ef0798838: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
[23:28:11.253] > listeningOn==38709==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1012==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==91==
> connectionToken==a11111a1-11a1-1aa1-a1aa-aa1a111a1111==
> 9f8ef0798838: end
[23:28:11.254] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====listeningOn==38709==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1012==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==91==
connectionToken==a11111a1-11a1-1aa1-a1aa-aa1a111a1111==

[23:28:11.255] Remote server is listening on port 38709
[23:28:11.255] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":38709},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1012","platform":"linux","connectionToken":"a11111a1-11a1-1aa1-a1aa-aa1a111a1111"},"serverStartTime":91,"installUnpackCode":""}
[23:28:11.259] Persisting server connection details to /home/avishka/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-c940f595-f1b07bd25dfad64b0167beb15359ae573aecd2cc-0.106.5-tr/data.json
[23:28:11.265] Starting forwarding server. local port 46081 -> socksPort 33111 -> remotePort 38709
[23:28:11.266] Forwarding server listening on port 46081
[23:28:11.267] Waiting for ssh tunnel to be ready
[23:28:11.268] [Forwarding server port 46081] Got connection 0
[23:28:11.270] Tunneled port 38709 to local port 46081
[23:28:11.271] Resolved "ssh-remote+192.248.10.120" to "port 46081"
[23:28:11.280] ------




[23:28:11.306] [Forwarding server port 46081] Got connection 1
[23:28:13.601] > local-server-1> Timed out
[23:28:13.608] Local server exit: 0
```

**Comment by edsealing** [comment] 2023-10-19 19:33
Looks like a duplicate to https://github.com/microsoft/vscode/issues/195617
Same bug is affecting WSL connections with remote.

**Comment by rebornix** [comment] 2023-10-20 19:11
It's a duplicate of https://github.com/microsoft/vscode/issues/195617#issuecomment-1773202568 , please follow steps in https://github.com/microsoft/vscode/issues/195617#issuecomment-1773202568 to upgrade Pylance to have this issue fixed, thanks!

**Closed by rebornix** 2023-10-20 19:11 UTC
