### ISSUE TITLE
Cannot create new file using remote cli

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#138089] opened 2021-11-29 20:17 UTC
- VS Code Version: insiders and from sources

Steps to Reproduce:

1. run vscode server
2. open terminal and type `code new_file` to open a new file
3. :bug: nothing happens

Seems a regression from this PR https://github.com/microsoft/vscode/pull/136359
cc @bpasero

**Comment by lszomoru** [comment] 2021-11-30 13:21
Duplicate of #137409. This should be fixed in today's Insider release.

**Closed by lszomoru** 2021-11-30 13:21 UTC
Labels: bug, remote
