### ISSUE TITLE
Missing title in window title bar

### ISSUE THREAD

**Issue by kanongil** [Microsoft/vscode#28798] opened 2017-06-15 09:12 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.9.1|
|vscode-eslint|dbaeumer|1.2.11|
|vsc-ember-cli|felixrieseberg|0.3.3|
|Theme-TomorrowKit|ms-vscode|0.1.4|
|cpptools|ms-vscode|0.11.4|
|debugger-for-chrome|msjsdiag|3.1.4|;

---

Steps to Reproduce:

1. Open any file.

**Comment by bpasero** [comment] 2017-06-15 15:59
@kanongil can you share a screenshot?

**Comment by kanongil** [comment] 2017-06-15 22:05
Empty titlebar (besides close/minimize/fullscreen dots):
<img width="443" alt="screen shot 2017-06-16 at 00 00 20" src="https://user-images.githubusercontent.com/753512/27203596-d94da34c-5226-11e7-9d24-278511670d99.png">

It used to be there, eg: http://mitchdenny.com/content/images/2015/05/Visual-Studio-Code-1.png

**Comment by bpasero** [comment] 2017-06-19 05:21
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by kanongil** [comment] 2017-06-19 09:12
@bpasero This is still an issue in the insider build I just downloaded.

**Comment by bpasero** [comment] 2017-06-19 09:47
@kanongil what is your "window.titleBarStyle" setting? does it help when you change it to "native"?

**Comment by kanongil** [comment] 2017-06-19 09:54
It's the default:
```
  "window.titleBarStyle": "custom",
```

Overriding it with `"native"` seems to fix this issue.

**Comment by bpasero** [comment] 2017-06-19 12:00
@kanongil it must be the theme you are using, which one is it?

**Comment by kanongil** [comment] 2017-06-19 12:15
I use the `"Quiet Light"` theme, but the issue persists if I delete all entries in the user `settings.json` (along with empty workspace settings).

You are not able to replicate? I just checked my colleague's editor, and it works as it should. I guess this must be an issue with the macOS 10.13 beta I'm running.

I don't know what your policy is regarding beta OS', but feel free to close it, if you would rather wait it out a bit.

**Comment by bpasero** [comment] 2017-06-19 13:59
@weinand do you see this missing title too when running on macOS 10.13?

@kanongil can you change your theme just to see if that fixes it?

**Comment by weinand** [comment] 2017-06-19 16:03
The latest Insiders crashes on startup on High Sierra:
```
Last login: Mon Jun 19 16:36:31 on console
macos-high-sierra:~ weinand$ /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron 
TypeError: Cannot read property 'reopenFolders' of undefined
    at e.getRestoreWindowsSetting (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:270796)
    at e.doGetWindowsFromLastSession (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:269767)
    at e.getWindowsToOpen (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:269099)
    at e.open (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:265701)
    at t.openFirstWindow (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:316903)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:314524
    at t.invokeFunction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:164273)
    at t.startup (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:314488)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:321107
    at Object.v [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:67486)
macos-high-sierra:~ weinand$ 
```

**Comment by bpasero** [comment] 2017-06-19 16:33
@weinand I pushed a fix for that earlier today but I guess our signed bits still have the bug. The fix is to define a user setting like this one:

`"window.zoomLevel": 1`

**Comment by sc0ttwad3** [comment] 2017-06-20 17:49
[**Update**: going to try the user setting definition suggested by @bpasero which I had not found when recording the error below]

+1 same issue on Windows 10 build 16199.  __VSCode nightly__ was working on 6/20/17 and all prior nightly builds, This morning, with no user environment or settings changes, it starts to __load__ and __immediately errors out__  with the following logged to the terminal

```
TypeError: Cannot read property 'reopenFolders' of undefined
    at e.getRestoreWindowsSetting (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:270796)
    at e.doGetWindowsFromLastSession (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:269767)
    at e.getWindowsToOpen (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:269099)
    at e.open (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:265701)
    at t.openFirstWindow (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:316903)
    at C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:314524
    at t.invokeFunction (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:164273)
    at t.startup (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:314488)
    at C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:321107
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:67486)
```

Already tried a complete uninstall/reinstall: **same error**.
Did another complete uninstall/reinstall and copied back in my user settings, etc.: **same error**.

Going to dive into C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:270796 directly for more insight.

**Comment by bpasero** [comment] 2017-11-14 17:44
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.

**Closed by bpasero** 2017-11-14 17:44 UTC
Labels: electron, needs more info, upstream
