### ISSUE TITLE
Expand DOC: View Panes can handle different UI in the items, apart from text (TreeView) like the Breakpoints View

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#101175] opened 2020-06-27 05:29 UTC
Looking at the Breakpoints View the ViewItems can handle more complex UI than text as described in the TreeView page.

Looking at the source code the `BreakPointsView` extends the `ViewPane` class and uses a different mechanism than the `TreeView`.

Please expand the API to allow extension developers to also use these additional features.

And also write a doc page describing the use of this (template based) mechanism.

**Comment by alexr00** [comment] 2020-06-30 07:52
Duplicate of https://github.com/microsoft/vscode/issues/97190

**Closed by alexr00** 2020-06-30 07:52 UTC
