### ISSUE TITLE
Wrong/annoying background selection color in Solarized Light

### ISSUE THREAD

**Issue by jensnicolay** [Microsoft/vscode#24750] opened 2017-04-14 07:40 UTC
The background selection and word highlight color is too dark in 'Solarized Light' theme. This also makes the selected/highlighted text difficult to read.

I think this problem (color change) was introduced in 1.11.

![screen shot 2017-04-14 at 09 38 09](https://cloud.githubusercontent.com/assets/3582540/25036813/2f504d7e-20f6-11e7-8eb8-9e547ec93c00.png)

- VSCode Version: 1.11.2
- OS Version: Mac OS 10.12

Steps to Reproduce:

1. Select 'Solarized Light' theme
2. Type and select some text

**Comment by aeschli** [comment] 2017-04-14 20:03
duplicate of #24040

**Closed by aeschli** 2017-04-14 20:03 UTC
