### ISSUE TITLE
Can vscode start to render the DOM when the white screen turned black? It is very uncomfortable to suddenly flash this at night, my browser refresh the DOM page is white action with black theme

### ISSUE THREAD

**Issue by Super1Windcloud** [microsoft/vscode#223785] opened 2024-07-25 19:23 UTC
Can vscode start to render the DOM when the white screen turned black? It is very uncomfortable to suddenly flash this at night, my browser refresh the DOM page is white action with black theme

**Comment by gjsjohnmurray** [comment] 2024-07-25 22:54
Maybe a duplicate of #206863

**Closed** 2024-07-26 20:57 UTC
