### ISSUE TITLE
Picker is slow when used with many thousand elements

### ISSUE THREAD

**Issue by Wosi** [microsoft/vscode#20136] opened 2017-02-07 17:02 UTC
- VSCode Version: 1.9.0
- OS Version: Windows 7, Windows 10

Steps to Reproduce:

1. Call showQuickPick() with the items from [here](https://gist.github.com/Wosi/34713260519924210d2007e26cdeab00)
2. Type "test" letter by letter. You'll see the slow responding quick picker. The code completion box responds much faster working on the same data.

Here a sample how it looks like:
![slowquickpick](https://cloud.githubusercontent.com/assets/3448684/22701957/7159e952-ed5f-11e6-9689-f4c2e7633b75.gif)

**Comment by bpasero** [comment] 2017-02-07 17:39
Two reasons: we use the list widget for IntelliSense which is super fast and does not have high update cost when updating the tree. Second, quick open actually limits the number of results to some value, at least for file search.

CPU trace attached: 
[CPU-20170207T183917.cpuprofile.zip](https://github.com/Microsoft/vscode/files/758512/CPU-20170207T183917.cpuprofile.zip)

**Comment by bpasero** [comment] 2017-09-29 07:56
The original slowness is no longer there (the one from the tree), when I now test it with 10000 elements the majority of time is spend in `QuickOpenModel.compare() `where we check if a element is a match for a given search string.

**Comment by bpasero** [comment] 2017-11-15 16:19
@isidorn this might be resolved if we switch to using a list for quick pick.

**Comment by isidorn** [comment] 2018-05-11 09:07
Closing as duplicate of using a list for quick pick. Till then this is just a consequence of us using a tree which we do not plan to change afaik
fyi @chrmarti

**Comment by chrmarti** [comment] 2018-05-11 11:08
Most time is spent comparing entries.

**Closed** 2019-10-31 14:09 UTC
Labels: *out-of-scope, bug, perf, quick-pick
