### ISSUE TITLE
Allow configuration of settings search paths

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#59374] opened 2018-09-25 20:07 UTC
I am creating this issue because @remcohaszing's issue #56148 was closed as a duplicate of my issue #40233 when it is not in fact a duplicate:

> I use git for version control. I regularly type git clean -xdf from muscle memory, so I can work in a pristine environment, for example when switching branches.
> 
> Often I totally forget about my .vscode directory, so I will need to restore them manually. Of course it is possible to use workspaces instead, but it’s so convenient to just use code . from the terminal. It would be a shame to give this up.
> 
> My idea is to offer a different location for these configurations, which will be loaded when a directory is loaded, like .vscode, but outside of the version control.
> 
> Some potential locations:
> 
>   * .git/vscode
>   * $XDG_CONFIG_HOME/Code/Projects/${dirname}

IMO a general solution to this request would look something like `"settings.location": { [key: string]: bool }`, specified in user settings.

### The default value

```json
{
    "settings.location": {
        "${workspaceFolder}/.vscode/settings.json": true
    }
}
```

### Embedding within VCS dot folders (#56148)
```json
{
    "settings.location": {
        "${workspaceFolder}/.git/vscode": true,
        "${workspaceFolder}/.svn/vscode": true
    }
}
```

**Comment by firelizzard18** [comment] 2018-09-25 20:10
**This is not a duplicate of #40233.**

#40233 could be implemented as a specific use case of this proposal, but it has a fundamentally different goal, and could be implemented more easily than this proposal.

**Comment by sandy081** [comment] 2018-09-26 08:35
Duplicate of #29918. Please reopen it if you don't think so.

**Closed** 2018-09-26 08:35 UTC
Labels: *duplicate, config

**Comment by firelizzard18** [comment] 2018-09-28 16:56
@sandy081 This is a more general approach than #29918.

**Comment by sandy081** [comment] 2018-10-01 07:34
@firelizzard18 At the end of the day they are talking about the same problem - Ability to configure workspace configuration outside workspace.
