### ISSUE TITLE
Error in integrated console

### ISSUE THREAD

**Issue by gorsuchtim** [Microsoft/vscode#15517] opened 2016-11-15 14:49 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|htmltagwrap|bradgashler|0.0.3|
|beautify|HookyQR|0.5.4|
|guides|spywhere|0.5.1|
|JavaScriptSnippets|xabikos|1.2.0|

---

Error:

[Error - 8:48:11 AM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Path must be a string. Received undefined
  Code: -32603 

Steps to Reproduce:

1.  Open any htm file
2.  Save file, view console

**Comment by ramya-rao-a** [comment] 2016-11-16 03:14
Can you retry with extensions disabled?

**Comment by aeschli** [comment] 2016-11-17 07:43
duplicate of #15018

**Closed by aeschli** 2016-11-17 07:43 UTC
Labels: duplicate
