### ISSUE TITLE
Open files with specific extension in split screen window

### ISSUE THREAD

**Issue by AlanBlanchet** [microsoft/vscode#137124] opened 2021-11-13 16:01 UTC
Hello VSCode community,

I was programming an app for the web with react. And I thought about what could be a good feature. Every time I create a .sass file I always drag the file to my split screen window on the right so I can have on one side the program I'm developing and on another I can have the .sass file to edit.

Whenever I save in the file the changes automatically make the browser refresh.

At that moment I really wanted an extension that could automatically open the sass file in the second split screen window instead of the first one where my react components are.

![image](https://user-images.githubusercontent.com/22567306/141650541-b8a7b144-7897-4419-a2f1-bd33f50383a7.png)

Leave your thoughts about this idea.
Thanks in advance for the replies.

**Comment by gjsjohnmurray** [comment] 2021-11-13 16:11
/duplicate of #136162 which needs upvotes in order to move from Backlog Candidates to Backlog.

**Closed** 2021-11-13 16:11 UTC
Labels: *duplicate
