### ISSUE TITLE
Multiline string autoselection

### ISSUE THREAD

**Issue by sandorvasas** [microsoft/vscode#121993] opened 2021-04-23 06:58 UTC
Just recently, multiline strings get auto-highlighted like they were selected. It annoys me. How can I disable this, what is the feature's name to search for in settings?
[Please see this image](https://ibb.co/5sH7HQd)

**Comment by IllusionMH** [comment] 2021-04-23 18:23
Duplicate of https://github.com/microsoft/TypeScript/issues/43292

> Looks like it can be disabled by "editor.occurrencesHighlight": false ATM.

/assign mjbvz

**Closed** 2021-04-23 23:07 UTC
Labels: *duplicate
