### ISSUE TITLE
Git viewlet stages incorrect file

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31112] opened 2017-07-20 08:48 UTC
pls see the attached video.

I stage main.ts using the '+' action, but package.json is staged.

![staging](https://user-images.githubusercontent.com/172399/28408788-e66eb552-6d38-11e7-8edb-889f3de353c5.gif)

**Comment by egamma** [comment] 2017-07-20 08:51
Updated to the latest
![image](https://user-images.githubusercontent.com/172399/28408935-53e442d2-6d39-11e7-992c-f2e82f31f902.png)

**Comment by joaomoreno** [comment] 2017-07-20 08:58
Duplicate of #31038

The stage command takes the active editor's resource and stages that in case it receives no resources in its arguments.

**Closed by joaomoreno** 2017-07-20 08:58 UTC
Labels: bug, git, important
