### ISSUE TITLE
Unable to sign in with GH account

### ISSUE THREAD

**Issue by motss** [microsoft/vscode#110171] opened 2020-11-08 07:21 UTC
Did a clean install (not upgrading from older version) of the latest v1.51.0 VSCode on Windows 10 and tried to sign in to GH account to sync all settings. Found out that only sign in to MS account works while sign in to GH account will keep prompting you to sign in after numerous successful (I think, no error and nothing signed me in to my account) attempts.

## System information
CPUs | Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.85GB (5.41GB free)
Process Argv | . --crash-reporter-id 46708fdb-c67f-4924-88c6-887643f94287
Screen Reader | no
VM | 0%

## Enabled extensions
Extension | Author (truncated) | Version
-- | -- | --
emojisense | bie | 0.8.0
jsdoc-markdown-highlighting | bie | 0.0.1
vscode-docker | ms- | 1.7.0
remote-wsl | ms- | 0.51.1
vscode-todo-highlight | way | 1.0.4
vscode-vlang | 0x9 | 0.1.2
vscode-lcov | ale | 0.2.0
emojisense | bie | 0.8.0
jsdoc-markdown-highlighting | bie | 0.0.1
lit-html | bie | 1.11.1
markdown-preview-github-styles | bie | 0.1.6
better-toml | bun | 0.3.2
vscode-svgviewer | css | 2.0.0
vscode-wasm | dts | 1.3.1
gitlens | eam | 10.2.3
EditorConfig | Edi | 0.15.1
vscode-diff | fab | 1.4.0
glitch | gli | 0.1.7
vscode-styled-components | jpo | 1.2.0
vscode-filesize | mkx | 2.1.4
vscode-docker | ms- | 1.7.0
vscode-typescript-tslint-plugin | ms- | 1.2.3
resourcemonitor | mut | 1.0.7
reload | nat | 0.0.6
indent-rainbow | ode | 7.4.0
vscode-yaml | red | 0.12.0
vscode-sort-json | ric | 1.18.1
rust | rus | 0.7.8
vscode-coverage-gutters | rya | 2.6.0
crates | ser | 0.5.3
rewrap | stk | 1.13.0
code-spell-checker | str | 1.9.2
vscode-todo-highlight | way | 1.0.4
markdown-all-in-one | yzh | 3.3.0
sort-js-object-keys | zen | 1.0.6

## VSCode information
![VSCode vesion](https://user-images.githubusercontent.com/10607759/98459464-f198b680-21d5-11eb-94b2-0db212ef163d.png)

**Comment by RMacfarlane** [comment] 2020-11-09 16:00
@motss Can you open the output panel and paste the log from "GitHub Authentication" here?

**Comment by motss** [comment] 2020-11-09 17:19
@RMacfarlane Please find the log + SS below.

### Github Authentication log

```
[Error  - 17:15:02.851] Getting token failed: Error: Decryption failed
[Info  - 17:15:11.90] Logging in...
[Info  - 17:15:24.309] Exchanging code for token...
[Info  - 17:15:25.726] Token exchange success!
[Info  - 17:15:25.727] Getting user info...
[Info  - 17:15:26.543] Got account info!
[Info  - 17:15:26.552] Login success!
[Error  - 17:15:26.561] Getting token failed: Error: Cannot get password
[Info  - 17:15:26.564] Removing session no longer found in keychain
```

### Screenshot

The login is always successful on the web but VSCode is always acting weird.

![failed to login with GH in VSCode](https://user-images.githubusercontent.com/10607759/98574084-72e56b80-22f2-11eb-827f-388001e90bc1.png)

**Comment by SConaway** [comment] 2020-11-17 05:25
Here's what I'm getting. It's slightly different, so maybe this is the mac version? I can create another issue if you'd like.

<details>
<summary>Log</summary>

````
$ cat logs/20201115T200008/exthost1/output_logging_20201115T200027/10-GitHub\ Authentication.log
[Error  - 04:00:34.396] Getting token failed: Error: UNIX[No such file or directory]
[Info  - 04:00:50.920] Logging in...
[Info  - 04:00:55.765] Exchanging code for token...
[Info  - 04:00:56.450] Token exchange success!
[Info  - 04:00:56.450] Getting user info...
[Info  - 04:00:57.420] Got account info!
[Error  - 04:00:57.542] Setting token failed: Error: UNIX[No such file or directory]
[Info  - 04:01:00.849] Login success!
````

</details>

**Comment by shacal** [comment] 2020-12-17 06:52
I started to have this same issue
`Getting token failed: Error: Decryption failed`
When using Microsoft account for sync

**Comment by dsbert** [comment] 2021-01-14 15:07
I'm having this same issue as well.

Windows 10
Firefox Developer Edition

**Comment by oae** [comment] 2021-01-16 13:21
I have the same problem. If I open `Code.exe` directly. It doesn't have this problem. But if I try to open vscode from commandline with `code.cmd` under `bin` directory then authentication fails.

* Github Authentication Log with `code.exe`

```
[Error  - 13:13:32.842] Getting token failed: Error: Decryption failed
[Info  - 13:13:45.399] Logging in...
[Info  - 13:13:53.85] Exchanging code for token...
[Info  - 13:13:53.910] Token exchange success!
[Info  - 13:13:53.910] Getting user info...
[Info  - 13:13:54.301] Got account info!
[Info  - 13:13:54.308] Login success!
```

* Github Authentication Log with `bin\code.cmd`

```
Error  - 13:19:18.393] Getting token failed: Error: Decryption failed
[Info  - 13:19:27.974] Logging in...
[Info  - 13:19:35.606] Exchanging code for token...
[Info  - 13:19:36.548] Token exchange success!
[Info  - 13:19:36.548] Getting user info...
[Info  - 13:19:36.941] Got account info!
[Info  - 13:19:36.950] Login success!
[Error  - 13:19:36.957] Getting token failed: Error: Cannot get password
[Info  - 13:19:36.966] Removing session no longer found in keychain
```

**Comment by sajalshres** [comment] 2021-03-15 13:07
I'm also facing this same issue

```
[Info  - 13:49:03.246] Logging in...
[Info  - 13:49:18.309] Exchanging code for token...
[Info  - 13:49:19.700] Exchanging code for token...
[Info  - 13:49:20.242] Token exchange success!
[Info  - 13:49:20.242] Getting user info...
[Info  - 13:49:21.582] Token exchange success!
[Info  - 13:49:21.691] Got account info!
[Info  - 13:49:21.702] Login success!
[Error  - 13:49:21.710] Getting token failed: Error: Cannot get password
[Info  - 13:49:21.715] Removing session no longer found in keychain
```

Windows 10 Enterprise 1909
Firefox Developer Edition

**Comment by RMacfarlane** [comment] 2021-05-13 17:14
Closing as a duplicate of https://github.com/microsoft/vscode/issues/111468

**Closed by RMacfarlane** 2021-05-13 17:14 UTC
Labels: needs more info
