### ISSUE TITLE
Valid code showing up as error

### ISSUE THREAD

**Issue by mochanekodev** [microsoft/vscode#120750] opened 2021-04-07 17:49 UTC
Issue Type: <b>Bug</b>

I guess this is a bug? I don't think it's a feature request.. Anyhow, I'm going through a course right now for Javascript, and the provided files often have embedded javascript that uses HTML comment lines. I've looked it up on w3schools and it is valid and common practice, so it confuses me why it would come up as an error in VS Code. What I'm referring to is the sample code under "Tips and Notes" here: https://www.w3schools.com/tags/tag_comment.asp (shown below as a screenshot).

![image](https://user-images.githubusercontent.com/30380114/113925149-4ace3b80-97b0-11eb-9505-13c6ce7dee43.png)

Before this last update it would show as an error but didn't really bother me as it only showed the red underline (as is still done and can also be seen in the screenshot below). However, now my file names also show up in bright red every time that bit of code is used and _that_ bothers me. But I like the feature of showing files with errors in red. The problem is that it simply shouldn't be registering as an error in code.

Here is how files show in VS Code when commenting out Javascript as shown in the sample code from w3schools above.
![image](https://user-images.githubusercontent.com/30380114/113924949-0e024480-97b0-11eb-8512-061eb96df57f.png)

These are files that are provided with that code in place, which is being used properly, so every single file from this Javascript course I am doing comes up as having an error with the name of the file in bright red.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by mjbvz** [comment] 2021-04-07 19:42
Please share steps to reproduce the problem and a screenshot of the issue 

/needsMoreInfo

**Comment by mochanekodev** [comment] 2021-04-07 19:53
Sorry, this is my first time using GitHub to report an error like this. I've updated my initial post with screenshots and a little more verbose information.

**Comment by mjbvz** [comment] 2021-04-07 19:56
@aeschli It looks like html comments inside of script blocks are not being processed properly

**Comment by IllusionMH** [comment] 2021-04-07 21:45
@mjbvz Are these HTML-like comments parsed by TS correctly?

Looks like issue is reproducible in JS files as well
![image](https://user-images.githubusercontent.com/1312662/113938499-60208580-9803-11eb-85ed-40030b627775.png)

If this script linked in HTML and opened - second log will be called and not other parse errors etc.

**Comment by aeschli** [comment] 2021-04-08 10:30
duplicate of #47448

**Closed** 2021-04-15 11:27 UTC
Labels: html, needs more info
