### ISSUE TITLE
Multi root feature does not display included work root directories 

### ISSUE THREAD

**Issue by jozseftoth** [Microsoft/vscode#38221] opened 2017-11-13 12:58 UTC
- VSCode Version: 1.18.0
- OS Version: win7 SP1

Steps to Reproduce:

1. open a folder as a new workspace
2. add one or more directory to the workspace which is outside from the workspace's root 
3. the added directories and the files does not appears in the project explorer, but the files are searchable for strings on the search tab even there are locations to the work directories in the saved workspace files.

Reproduces without extensions: Yes

**Comment by isidorn** [comment] 2017-11-14 11:15
@jozseftoth can you maybe attach a short gif / video that ilustrates this issue?
Can you also reproduce with latest vscode insiders since we have fixed some issue about root folders being hidden
https://code.visualstudio.com/insiders/

**Comment by jozseftoth** [comment] 2017-11-15 11:00
I have been checked with the vscode insiders, this functionality works well there. In addition, I checked that what happens if the insiders saved code-workspace file opened with the vscode: altough it is searchable, the workspace seems empty even if the vscode insiders works properly with that file.

![image](https://user-images.githubusercontent.com/10272597/32832312-59d5be0e-c9fb-11e7-9ec9-4ca9d283f03a.png)

**Comment by isidorn** [comment] 2017-11-15 11:22
As far as I understood your statement everything works fine in insiders -> closing
This should also be fixed in stable soon.

**Closed by isidorn** 2017-11-15 11:22 UTC
Labels: file-explorer, multi-root, needs more info, new release
