### ISSUE TITLE
Add `executeDocumentSemanticTokensProvider` API

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#104896] opened 2020-08-18 07:00 UTC
There should be a command to run the semantic provider, so one could test semantic highlighting end-to-end.

Need to update doc here as well: https://code.visualstudio.com/api/references/commands

**Comment by aeschli** [comment] 2020-08-18 07:44
Hi @octref ! Nice to see you active!

Marking as duplicate of https://github.com/microsoft/vscode/issues/91375

**Closed by aeschli** 2020-08-18 07:44 UTC
