### ISSUE TITLE
Mojave dark mode adds black border around app for light themes

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#62414] opened 2018-11-01 20:49 UTC
Issue Type: <b>Bug</b>

Related to #54838 

When dark mode is enabled, a black border is added around the app, which looks great in out dark theme:
![image](https://user-images.githubusercontent.com/35271042/47879037-e63b7500-dddc-11e8-82f5-8c1af786a0ab.png)

But in our light theme this looks bad:
![image](https://user-images.githubusercontent.com/35271042/47878988-cefc8780-dddc-11e8-8199-add5c267d2c5.png)

It would be great to disable this when on light themes.

VS Code version: Code - Insiders 1.29.0-insider (d7ac6e838f51a03f7d417b4758f5fb075878d615, 2018-11-01T06:11:43.390Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
vscode-pull-request-github|Git|0.2.2
vscode-colorize|kam|0.7.2
material-icon-theme|PKi|3.6.0

(3 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-11-18 11:49
@MarshallOfSound any ideas?

**Comment by MarshallOfSound** [comment] 2018-11-18 11:56
@bpasero My understanding of these issues so far is that this is "intended behavior" on Mojave.  macOS adds these color highlights to the window to match the theme under the assumption that the apps theme matches the OS theme.  (This assumption is based on the `NSRequiresAquaSystemAppearance` key)

If you're using a VS Code light theme with Mojave dark mode this is just going to happen unless Apple change there mind on enforcing this weird window border or someone finds a hidden window style for turning it off in native land.

**Comment by bpasero** [comment] 2018-11-18 12:10
@MarshallOfSound yeah that is what I am thinking as well. Closing as designed by Apple.

**Closed by bpasero** 2018-11-18 12:10 UTC
Labels: insiders, mac, mojave, upstream
