### ISSUE TITLE
Question: Minimum width for VS Code status bar icon

### ISSUE THREAD

**Issue by jamarw** [Microsoft/vscode#13168] opened 2016-10-03 18:39 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 10 Enterprise (10.0.14393 Build 14393)

Steps to Reproduce:

1. Create a typescript file in VS Code and a function to update the StatusBarItem
Example:
```typescript
function uiBold() {
        let statusBarItem: vscode.StatusBarItem;
        statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
        statusBarItem.text = "$(bold) Bold";
        statusBarItem.color = "black";
        statusBarItem.show()
        statusBarItem.command = "extension.formatBold";
}
```
2. Create a new status bar item using the bold or italic Octicon icons [`statusBarItem.text = "$(bold) Bold";`]
3. Open the file in debug mode/Extension Development Host] and run the command to launch the function
4. Text (Bold) will render but icon will not.

Expected results
Using the code above, change the bold icon to pencil or gear and run step 3.  Both the icon and text will show.

Question
Is there a minimum width required for VS Code status bar icons?  I've tried a few and the ones that do not work are 10px or smaller in width (<svg width="10px").  Icons that I have tested that are 14px or larger work just fine.

Thanks and please let me know if you need any additional details or if you'd like me to share the ts files for the extension I'm developing.

**Comment by jamarw** [comment] 2016-10-25 05:23
Hi @jrieken , just checking in to see if there's any updates on this.  Looping in the PM I'm working with on this project.  Thanks

CC: @meganbradley

**Comment by jrieken** [comment] 2016-10-25 07:09
Sorry, no update yet. I also don't know if a min width is the best way going forward. Since everyone is biased towards her/his extension everyone is likely assigning a large min width. 

Adding @stevencl and @bpasero that are in charge of the actual status bar implementation and design.

**Comment by bpasero** [comment] 2016-10-27 15:43
@jrieken I do not understand this issue. the problem is that the user tries to use an icon which does not exist in our version of octicon. We ship with 3.1.0 and bold seems only to be added in 3.2.0. I think we should eventually just update to latest to avoid this confusion.

**Comment by jrieken** [comment] 2016-10-27 15:58
Yeah - I didn't read further than *minimum width*. Closing this as dupe of https://github.com/Microsoft/vscode/issues/10455

**Closed by jrieken** 2016-10-27 15:58 UTC
Labels: feature-request, question, workbench

**Comment by jamarw** [comment] 2016-10-27 17:50
Thanks all for the help.  I'll check the other issue for status.
