### ISSUE TITLE
Context menu in wrong location after increasing font size

### ISSUE THREAD

**Issue by markdall** [Microsoft/vscode#4437] opened 2016-03-18 19:55 UTC
- VSCode Version: 
Version 0.10.11
Commit f291f4ad600767626b24a4b15816b04bee9a3049
Date 2016-03-11T17:10:35.304Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
- OS Version: Windows 7 Enterprise Version 6.1.7601

Steps to Reproduce:
1. Start VSCode.
2. Press Control + a few times because you're getting older and your monitor is very large. :)
3. Right click on some text. 

Expected result: The context menu opens at the mouse pointer. 

Actual result: The context menu opens at what would be the right location if you hadn't increased the font size. 

Notes: 
1. I could not for the life of me find a way to search these issues, apologies in advance if this is a dupe. 
2. This is a new bug for this update - this didn't used to happen.

**Comment by joaomoreno** [comment] 2016-03-22 12:12
Duplicate of #821

**Closed by joaomoreno** 2016-03-22 12:12 UTC
