### ISSUE TITLE
zip extract bug

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#8044] opened 2016-06-23 10:14 UTC
- VSCode Version: 1.3.0-insiders
- OS Version: windows 7

Steps to Reproduce:

1. download zip file: https://github.com/f111fei/test-files/raw/master/vscode-zip/test.zip

2. run test code.
```
import {extract} from 'vs/base/node/zip';
extract('test.zip', './dest', {})
	.then(() => {
		console.log('success');
	}, e => {
		console.log(e.message);
	});
```

`console.log` never will be called. `Promise` is pending forever.

**Comment by joaomoreno** [comment] 2016-06-24 06:21
Is this related to #7599 and it so, did you encounter this bug in an actual extension installation?

**Comment by f111fei** [comment] 2016-06-24 06:40
@joaomoreno 
No. we use our extension marketplace to install extension, but the `zip` file can't be extracted.

**Comment by f111fei** [comment] 2016-06-24 06:49
the issue is different from PR https://github.com/Microsoft/vscode/pull/7599. the issue `zip` extract success, but `Promise` is pending forever. PR 7599 `zip` file extract failed.

I suggest you write a test use these `zip` file for `vs/base/node/zip`

**Comment by joaomoreno** [comment] 2016-07-06 15:11
Is it possible that you ran into this on top of your own changes from #7599? After the changes of that PR plus my commit on top (as explained in the PR) I can not reproduce this issue.

Closing as can't reproduce. But let me know if you still can. 👍

**Closed by joaomoreno** 2016-07-06 15:11 UTC
Labels: bug
