### ISSUE TITLE
See current component in react

### ISSUE THREAD

**Issue by apperside** [Microsoft/vscode#29017] opened 2017-06-19 13:24 UTC
Is very common in react programming to have different components in the same file. It would be very helpfull if we can have immediate evidence of the component that is currently being edited (something like intellij's navigation bar)

**Comment by techird** [comment] 2017-06-19 15:13
Why not just use <kbd>Ctrl</kbd> + <kbd>P</kpd> and type `@` to search?

**Comment by apperside** [comment] 2017-06-19 15:40
Actually I am referring to something like this https://www.jetbrains.com/help/idea/navigation-bar.html , where you can see (for example in java) the class and the method you are into.
In react could be something like file name > component > method

**Comment by mjbvz** [comment] 2017-06-19 15:53
Does #9418 cover this?

**Comment by apperside** [comment] 2017-06-19 16:02
I already had a look at that, but doesn't help because it does not provide a real solution to this.
What I am asking is something that gives a quick response to the question "In which point of the code am I in?"

Since react is very verbose, it could be very useful

**Comment by mjbvz** [comment] 2017-11-09 00:25
Duplicate of #9418

**Closed by mjbvz** 2017-11-09 00:25 UTC
Labels: duplicate, feature-request
