### ISSUE TITLE
Selection menu: Not all actions work on read only editors

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16627] opened 2016-12-06 11:15 UTC
Testing #16558 

- In the git view, select a file that was removed.
- set focus to the editor and try the actions from the selection menu

  - set cursor above/below doesn't seem to have an effect
  - move/copy lines don't have an effect

- Unavailable actions should better be disabled. or maybe there should be some feed back.
- set cursor above/below should also work in a readonly editor

**Comment by alexandrudima** [comment] 2016-12-07 16:33
I have extracted the last bullet point to a new issue. For the rest of the bullet points, the top level menu should be updated based on the current focused editor.

e.g. 
1) Close all editors. Click on Selection Menu. It should contain only disabled items. 
2) Focus in the terminal. Click on anything in the Selection Menu, etc.

**Comment by bpasero** [comment] 2016-12-08 09:10
Related: https://github.com/Microsoft/vscode/issues/991

**Comment by chrmarti** [comment] 2017-11-30 23:50
Same with the Edit menu. This is by design at the moment.

**Comment by bpasero** [comment] 2018-07-13 05:52
Duplicate of https://github.com/Microsoft/vscode/issues/991

**Closed by bpasero** 2018-07-13 05:52 UTC
Labels: feature-request, workbench-menu
