### ISSUE TITLE
Regression of #7218: Backspace does not handle certain emoji correctly

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#47031] opened 2018-03-31 14:16 UTC
This is the same issue as #7218. It seemed to be fixed at that time, but it has appeared again.

I searched duplicated issues in https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+emoji+label%3Aeditor+

Thank you.

----

- VSCode Version: 1.21.1
- OS Version: Windows 7 Pro 64bit

Steps to Reproduce:

1. Input emoji.
2. Type backspace key.

![emoji-backspace](https://user-images.githubusercontent.com/1937871/38164020-bc7ea522-3538-11e8-9c4d-cf0e8edea280.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jasonpezzimenti** [comment] 2018-04-01 19:01
I can confirm this behavior. I'm already working on it.

**Comment by alexandrudima** [comment] 2018-04-19 20:57
@mysticatea I believe this depends from emoji to emoji. For example, I cannot reproduce using the "💩" or "👍" emojis. What specific emoji are you having trouble with ?

**Comment by mysticatea** [comment] 2018-04-20 03:14
At that time, I had used 👍 (U+1f44d). I will check again later.

**Comment by mysticatea** [comment] 2018-04-20 03:30
It doesn't reproduce in VSCode 1.23.0-insider (1fdf60b882f0edc6753fc964b253783eb46d56ef).

**Comment by usernamehw** [comment] 2018-04-20 05:13
I can't reproduce it anymore in **1.23**. Bug was still there about 3~8 days ago.

**Comment by alexandrudima** [comment] 2018-04-20 07:27
@mysticatea @usernamehw I cannot reproduce the problem using "👍". Did you perhaps install an extension that reimplements backspace? You can look for keybindings via `ctrl+k ctrl+s`

![image](https://user-images.githubusercontent.com/5047891/39036161-fe187456-447c-11e8-9446-f04aa64d7c22.png)

By default, our command is `deleteLeft`.

**Comment by mysticatea** [comment] 2018-04-20 08:08
> Did you perhaps install an extension that reimplements backspace?

No. It happens with `--disable-extensions` CLI option.

![image](https://user-images.githubusercontent.com/1937871/39038055-6ce5eaa4-44bd-11e8-9bea-1b8d33f44b92.png)

**Comment by alexandrudima** [comment] 2018-04-20 10:18
Ok, I was able to reproduce. It has to do with a method `validateRange` getting corrupt output after certain edit patterns. Duplicate of #47733. The insiders release contains the fix already.

**Closed by alexandrudima** 2018-04-20 10:18 UTC
Labels: needs more info
