### ISSUE TITLE
Format Html file cause css style with extra spacing

### ISSUE THREAD

**Issue by showenx** [Microsoft/vscode#22184] opened 2017-03-07 22:52 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.8.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|vscode-icons|robertohuertasm|7.2.0|
|sass-indented|robinbentley|1.3.0|;

---

Steps to Reproduce:

1. create a blank html page
2. add following styles with comments in header 
<style type="text/css">
    /* some comments  */
    .somestyle {
        display: none;
    }
</style>
3. Format the html page in vscode by using **Alt + Shift + F**
4. Extra space line is added by vscode every time formatting page

**Comment by mjbvz** [comment] 2017-03-07 23:05
This is a duplicate of #21717 

@aeschli has already checked in a fix which should be in the 1.10 recovery build

**Closed by mjbvz** 2017-03-07 23:05 UTC
Labels: duplicate
