### ISSUE TITLE
Settings problems are not cleared when closing settings.json

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#69456] opened 2019-02-26 13:48 UTC
With version 1.31.1 (Ubuntu)

1. Open Settings
2. Open JSON editor
3. Note 'problems' with old settings which are no longer valid
4. Close JSON editor
5. Note 'problems' are not cleared.

It's not consistent - I have two windows open at the moment. One exhibits the behaviour and one doesn't... reloading fixes it.

**Comment by roblourens** [comment] 2019-02-26 18:15
I can't repro this. It's probably caused by an extension. You can try starting with `--disable-extensions` to check or try to figure out which extension might be looking at json files and keeping a model open.

**Comment by Gruntfuggly** [comment] 2019-02-27 17:53
I *think* this happens when the user settings.json and the workspace settings.json have both been opened.

Unfortunately, I can't really run without extensions, or my workflow would be totally compromised.

**Comment by roblourens** [comment] 2019-02-28 03:49
I mean, you could just try starting once without extensions and reproduce the issue so we can verify that it is caused by an extension.

**Comment by Gruntfuggly** [comment] 2019-02-28 08:54
It doesn't happen all the time - this is the nub of the problem with the problems view. After a while you notice that there are problems that shouldn't be there anymore and there is no way to clear them without reloading the window.

When I run with `--disable-extensions` I get an error:

```
notificationsAlerts.ts:38 TypeError: Cannot read property 'scheme' of null
    at t.resolveContent (remoteFileService.ts:340)
    at t.createIfNotExists (preferencesService.ts:532)
    at t.createSettingsIfNotExists (preferencesService.ts:528)
    at t.getOrCreateEditableSettingsEditorInput (preferencesService.ts:451)
    at t.doOpenSplitJSON (preferencesService.ts:345)
    at t.doOpenSettings (preferencesService.ts:318)
    at t.openOrSwitchSettings (preferencesService.ts:308)
    at t.openFolderSettings (preferencesService.ts:234)
    at t.openSettingsFile (settingsEditor2.ts:451)
    at t.switchToSettingsFile (settingsEditor2.ts:439)
    at preferences.contribution.ts:692
    at t.e.invokeFunction (instantiationService.ts:54)
    at Proxy.t._tryExecuteCommand (commandService.ts:63)
    at commandService.ts:52
```

Is this a separate bug?

**Comment by Gruntfuggly** [comment] 2019-02-28 09:20
OK, that error only happened once.

I've just seen it again when running without any extensions.

**Comment by roblourens** [comment] 2019-02-28 16:36
That error could actually related. It looks like you have the split json editor enabled, that is useful info. I think this method would have returned `null` which it looks like isn't handled well in some cases. https://github.com/Microsoft/vscode/blob/0a4a3b98282175a82a819b70d2bbe46475e1ebd0/src/vs/workbench/services/preferences/browser/preferencesService.ts#L496-L510

When you saw the error were you opening workspace settings? Do you have a multi-root workspace open or just a single folder?

**Comment by Gruntfuggly** [comment] 2019-02-28 17:56
Just a single folder, and yes, the split editor is enabled, although I'm fairly sure it has happened with out it too.

**Comment by Gruntfuggly** [comment] 2019-06-12 08:25
Still seeing this all the time.

**Comment by roblourens** [comment] 2019-10-10 21:58
I think this should be fixed because unrecognized settings are no longer considered error/warnings. Let me know if not the case.

**Closed by roblourens** 2019-10-10 21:58 UTC
Labels: bug, settings-editor

**Comment by Gruntfuggly** [comment] 2019-10-10 23:01
Yes  - they just showing up as 'info's now. Thanks.
