### ISSUE TITLE
File not reloaded after Workbench reload

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#148184] opened 2022-04-26 17:24 UTC
Testing #148045

- open the modified file from a pull request. The file should have comments
-  reload the workbench

Observe:

- the file is not restored and the comments view is not revealed.

![cast](https://user-images.githubusercontent.com/1931590/165357609-d271ca3e-e5fc-4baf-9247-a8e2550f37a0.gif)

This is in WSL

**Comment by dbaeumer** [comment] 2022-04-26 17:29
Same behavior in pure Windows.

**Comment by lychung7** [comment] 2022-04-26 18:42
Same behavior on Mac

**Comment by alexr00** [comment] 2022-04-27 09:32
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2938 (also filed by @dbaeumer :))

**Closed by alexr00** 2022-04-27 09:32 UTC

**Comment by dbaeumer** [comment] 2022-04-28 12:59
That was 8 months ago. Got swapped out :-)
