### ISSUE TITLE
Keep undo stack between file close and reopen

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#7169] opened 2016-06-03 07:40 UTC
- Make a change in a file
- Close it <kbd>Ctrl W</kbd>
- Open it again <kbd>Ctrl Shift T</kbd>

Undo stack is lost 😢

**Comment by joaomoreno** [comment] 2016-06-03 07:59
Fixed recently.

**Comment by bpasero** [comment] 2016-06-03 07:59
Fixed in latest. Maybe you are still using this?

![image](https://cloud.githubusercontent.com/assets/900690/15772525/d9666f00-2971-11e6-8064-6ef5a2aab44e.png)

**Comment by joaomoreno** [comment] 2016-06-10 07:38
Updated original steps.

**Comment by bpasero** [comment] 2016-06-10 07:42
We dispose the editor when you close it and this means we get rid of the undo stack. This needs support from the editor to store the undo stack with the editor and resource (maybe similar to storing the view state)?

@alexandrudima moving to you.

**Comment by alexandrudima** [comment] 2016-06-29 19:17
We have the content hash now, but not a serializable undo/redo stack

**Comment by alexandrudima** [comment] 2016-06-29 19:18
IMHO this should go on the plan rather than me doing it under the radar. @joaomoreno you can lobby for it

**Comment by bpasero** [comment] 2016-08-26 10:49
See also https://github.com/Microsoft/vscode/issues/10932

**Comment by stevensacks** [comment] 2017-10-27 17:37
This bug is back again. I'm using Version 1.17.2 (1.17.2). This one bug makes VS Code almost unusable for me, since it's such a common part of my workflow.

**Comment by stevensacks** [comment] 2017-10-27 17:58
Also broken in Insiders: Version 1.18.0-insider.

**Comment by dedmazayukr** [comment] 2017-11-19 22:24
I confirm broken in version 1.18.1, also on version 1.19.0-insider

**Comment by skylarmb** [comment] 2018-10-18 22:13
This is still an issue... `cmd+w` by accident, `cmd+shift+t` a split second later and all my edit history is gone. Infuriating.

**Comment by kr094** [comment] 2019-05-23 18:22
There are bugs like this one that leave vs code feeling quite unfinished as an overall product.

**Comment by phil294** [comment] 2019-07-26 15:58
Was this ever possible at all? I am seeing conflicting statements here.

Is this a bug or a feature request?

Also see https://github.com/Microsoft/vscode/issues/47874.

**Comment by aloey** [comment] 2020-02-01 06:23
is there any update to this issue?

**Comment by charrondev** [comment] 2020-02-24 17:45
Confirmed this is still not working. I prefer VSCode to Webstorm in every aspect except for this. Webstorm will keep a long running local revision history, and VSCode can't even keep it for 5 seconds after closing a file.

**Comment by skylarmb** [comment] 2020-02-27 19:22
even `vim` supports this... you can close a buffer and re-open it and maintain your undo stack, or even quit vim entirely and re-open it in a different terminal and keep your undo history. 

```
set undodir=~/.vim/tmp/backup/
set undofile
```

**Comment by silllli** [comment] 2020-03-04 11:38
I am also missing this feature.

The undo history is also lost when renaming a file, even if it's open.

**Closed** 2020-03-23 10:41 UTC
Labels: editor-textbuffer, feature-request, undo-redo

**Comment by meboev** [comment] 2020-04-09 10:58
Oh God, please make this optional, default "on" if you want, but put an option that I can turn off. Some people like me, like to ditch the undo/redo history this way! You know, open the file clean, no undo history, etc. Existence of this feature is the main reason I hate Web Storm, and prefer VS Code, and now you are making this default here also! OMG

**Comment by sfilipov** [comment] 2020-04-09 11:16
Apologies for the off topic, and no disrespect to @meboev comment, but it reminded me of the following XKCD and it needs to be mentioned:

[Workflow](https://xkcd.com/1172/)

**Comment by meboev** [comment] 2020-04-09 19:59
About the XKCD analogy... The funny thing is that it's more like the other way around. Something like, you have just fixed a bug for people with a non-working "Control + w" on their keyboard, with a permanent, non opt-out binding of the "Spacebar" anywhere in the app, interpreting it's single press with a rapidly heating the CPU, making your OS freeze, thus closing the currently opened files with a hardware reboot.

**Comment by charrondev** [comment] 2020-04-09 20:18
> Oh God, please make this optional, default "on" if you want, but put an option that I can turn off. Some people like me, like to ditch the undo/redo history this way! You know, open the file clean, no undo history, etc. Existence of this feature is the main reason I hate Web Storm, and prefer VS Code, and now you are making this default here also! OMG

I view it as, I like to keep a clean list of open editors, rather than a clean undo history. The open editors (or tabs if you configure that way) are visual. The undo history is not.

I'll also note that unlike webstorm, VSCode is open source and accepts community contributions so if a configuration option isn't present you can implement one.

**Comment by phil294** [comment] 2020-04-09 22:51
> Oh God, please make this optional, default "on" if you want, but put an option that I can turn off. Some people like me, like to ditch the undo/redo history this way! You know, open the file clean, no undo history, etc. Existence of this feature is the main reason I hate Web Storm, and prefer VS Code, and now you are making this default here also! OMG

Not trying to invalidate your point, but could you please explain what you need to ditch the undo history for? Is it so that you can spam "undo" without worrying about going back further than desired?

It seems that now that this issue got closed, your best bet is probably to open up a new one. Either way you have a point, since making new features configurable is rarely a bad idea

**Comment by aj-vargas** [comment] 2020-04-10 03:21
Reading the comments of past years I see how useful this new feature is for some. I always saw the bug more like a feature [over WebStorm](https://youtrack.jetbrains.com/issue/IDEA-108209) though hehe.

> even `vim` supports this... you can close a buffer and re-open it and maintain your undo stack, or even quit vim entirely and re-open it in a different terminal and keep your undo history.
> 
> ```
> set undodir=~/.vim/tmp/backup/
> set undofile
> ```

And even `vim` [supports disabling](https://stackoverflow.com/questions/15660669/what-is-a-un-file-or-or-why-does-vim-in-the-terminal-make-the-un-file) persistent undo :)

> Not trying to invalidate your point, but could you please explain what you need to ditch the undo history for? Is it so that you can spam "undo" without worrying about going back further than desired?

It's my own specific case yes, to be able to spam "undo" without worries. When I close a tab in VSCode I mean to say "I'm closing this file" not "I'm hiding this file", hitting `⌘+Z` and seeing the file contents change *feels* like I just hid it from the view (like @charrondev mentioned). When I have multiple VSCode windows open (and several tabs on each), hitting `⌘+Z` on a file without seeing changes gives me the *feel* that the file (of all open files/tabs) hasn't been edited since open and it's *clean*.

Not a dealbreaker for me tbh, but I agree with @phil294, it would be nice that these kind of features were configurable.

Anyways, somebody opened the issue #94778 requesting the configurable persistent undo.

**Comment by Esteban26** [comment] 2020-04-24 20:08
I also think it should be optional. In my case, if I close a file is because I already finished modifying it, soI don't need the history anymore. So, the next time I open that file I expect an empty undo/redo list, and now If change something and then I press ctrl + z by twice I can delete something or add something I wrote or deleted previously, so I my case now I need to be very careful while pressing ctrl + z, I need to check that several times to check I didn't break anything. Also you need to think that for most of the cases people open and close their files several times while coding and this behavior could affect them as I explained, and only a very small percentage of cases would be the 'accidents' that they said. VSCode is a code editor, not a version tracker.

**Comment by dkolba** [comment] 2020-04-27 15:09
Coming from vim, I am astonished that no one is missing this feature?! Persistent undo stacks are great for rapid prototyping - kinda like a "git lite™️". Sad to see this issue closed. 😢😭

**Comment by anstosa** [comment] 2020-04-27 15:11
@dkolba It's closed because they added it in the March update

**Comment by dkolba** [comment] 2020-04-28 09:03
@anstosa only if you didn't close VSCode in between edits (which completely defeats the purpose tbh).

**Comment by anstosa** [comment] 2020-04-28 14:40
@dkolba agree that they should make it truly persistent, disagree that it defeats the purpose... I close files as part of my normal workflow and frequently want to go back to them. I never close VSCode as part of my normal workflow
