### ISSUE TITLE
Entering two forward slashes produces annoying </anonymous> tag in file with js extension

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [microsoft/vscode#91006] opened 2020-02-19 17:01 UTC
- VSCode Version:

Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

- OS Version:
macos mojave 

Steps to Reproduce:

1) Open file
2) Save it with .js extension
3) type //

And it produces this strange tag </anonymous>.  Why is it doing this?

**Comment by gjsjohnmurray** [comment] 2020-02-19 19:55
Does this reproduce if you run with all extensions disabled?

**Comment by mjbvz** [comment] 2020-03-03 22:26
Closing this as we need more info from the original poster. This sounds like it is likely caused by an extension

**Closed by mjbvz** 2020-03-03 22:26 UTC
Labels: needs more info
