### ISSUE TITLE
terminal dropdown showing garbled text

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#78539] opened 2019-08-06 06:52 UTC
- VSCode Version: 1.36.1
- OS Version: 10.14

See the 2 screenshots below:
<table><tr><td>
<img width="347" alt="image" src="https://user-images.githubusercontent.com/610161/62669857-cd8f6980-b9c3-11e9-8fc6-e39a63f91fc7.png">
</td><td>
<img width="322" alt="image" src="https://user-images.githubusercontent.com/610161/62669915-f57ecd00-b9c3-11e9-8ee9-27267381877e.png">
</td></tr></table>

Steps to Reproduce:

1. open integrated terminal, say running bash
2. run less by piping something to it, e.g. `date | less`
3. now the process name would start to show garbled text and keep changing. And the dropdown, when opened, would keep flickering

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2019-08-06 09:19
If you don't rename terminal you should see process name in terminal title.

Could you check if this happens in other terminal apps that display process name somewhere or may be in `ps`?

**Comment by ryenus** [comment] 2019-08-06 09:38
> Could you check if this happens in other terminal apps that display process name somewhere or may be in ps?

No, I tried `ps` and `top`, both have the process name displayed correctly, probably the problem is caused by the pipe?

**Comment by Tyriar** [comment] 2019-08-07 17:29
Can you show a screenshot? Does it only happen when you run less?

**Comment by ryenus** [comment] 2019-08-08 02:07
Here we go, see the 2 screenshots below:
<table><tr><td>
<img width="347" alt="image" src="https://user-images.githubusercontent.com/610161/62669857-cd8f6980-b9c3-11e9-8fc6-e39a63f91fc7.png">
</td><td>
<img width="322" alt="image" src="https://user-images.githubusercontent.com/610161/62669915-f57ecd00-b9c3-11e9-8ee9-27267381877e.png">
</td></tr></table>

1. the vscode session is started with `code --disable-extensions`
2. run `date | less` in the integrated terminal. The problem might not always happen right after vscode started, you might need to wait a few seconds meanwhile running some commands first, such as ls, top, date, etc.
3. once the problem occurs, the process name keeps changing, if the dropdown is clicked, it would keep flickering

**Comment by roblourens** [comment] 2019-10-08 23:49
I also see it, anytime I pipe multiple lines of text into less. For me if it's a single line of text, less just exits immediately.

Example: `xxd file.txt | less`

**Comment by ryenus** [comment] 2019-10-15 06:55
@roblourens you might have the option `--quit-if-one-screen`/`-F` set by default?
As a workaround, you can try `date | less -+F`

**Comment by bvschaik** [comment] 2020-04-13 18:15
Any update on this and/or can I help debugging this? I'm also encountering it and it's pretty annoying for me.

**Comment by Tyriar** [comment] 2020-04-14 13:32
The code is here:

https://github.com/microsoft/node-pty/blob/19449d2c319442bec3992cd280e9c88a185b6cb9/src/unix/pty.cc#L403-L429

I believe when @roblourens looked into the issue he found that it also occurs in tmux.

**Comment by bvschaik** [comment] 2020-04-15 06:40
I'm investigating. I think it's caused by the following: if you do `command | less`, at some point `command` is done and `less` takes over. At that point the code for getting the current command gets confused. You can verify this by doing `tail -f <large file> | less`: as long as `tail` is active, VSCode properly displays "tail". Hit Ctrl+C to kill `tail`, leaving only `less` active: garbled command.

Looking at tmux: it indeed also has this issue, but only on older versions of macOS. It has two bits of code for getting the process name: one for [macOS 10.7 and up](https://github.com/tmux/tmux/blob/master/osdep-darwin.c#L41-L52), and one for [older versions](https://github.com/tmux/tmux/blob/master/osdep-darwin.c#L54-L67). VSCode uses the one for older versions, which indeed gives garbled results. The code for 10.7+ jumps back from `command` to `bash` when `command` finishes execution, which seems a better solution to me than nonsense text which changes all the time.

Seeing that VSCode requires macOS 10.10 or higher, does it make sense to use the newer version?

**Comment by nicm** [comment] 2020-04-15 12:00
This does indeed happen in tmux although nobody has reported it. This seems to fix it. OS X doesn't seem great at returning the "right" process when there are multiple, but the whole idea is a best effort anyway.
~~~~
--- a/osdep-darwin.c
+++ b/osdep-darwin.c
@@ -61,7 +61,7 @@ osdep_get_name(int fd, __unused char *tty)
        size = sizeof kp;
        if (sysctl(mib, 4, &kp, &size, NULL, 0) == -1)
                return (NULL);
-       if (*kp.kp_proc.p_comm == '\0')
+       if (size != (sizeof kp) || *kp.kp_proc.p_comm == '\0')
                return (NULL);

        return (strdup(kp.kp_proc.p_comm));

**Comment by Tyriar** [comment] 2020-04-15 12:46
@nicm do you want to do a PR to node-pty and I can test it out?

**Comment by nicm** [comment] 2020-04-15 12:56
It looks like you just need to change this line https://github.com/microsoft/node-pty/blob/19449d2c319442bec3992cd280e9c88a185b6cb9/src/unix/pty.cc#L612

**Comment by Tyriar** [comment] 2020-04-15 13:04
@nicm figured you might want credit for the fix if it gets merged, I can try myself if you want though.

**Comment by nicm** [comment] 2020-04-15 13:15
No it's OK.

**Comment by bvschaik** [comment] 2020-04-15 13:50
> OS X doesn't seem great at returning the "right" process when there are multiple

It just always returns the first process in the chain it seems, and doesn't update the process group when the first one exits. Upon further investigation, sysctl returns 0 in the `size` argument when the process has exited, so the `kp` struct then basically contains random memory, which explains the garbled output. Nice find.

**Comment by Tyriar** [comment] 2020-04-15 13:51
Pulled in the change and verified it works, thanks all!

**Closed by bvschaik** 2020-04-15 13:50 UTC
Labels: bug, help wanted, integrated-terminal, upstream, upstream-issue-fixed, upstream-issue-linked

**Comment by ryenus** [comment] 2020-04-16 10:56
Adding a link to the patch: https://github.com/microsoft/node-pty/pull/401/
Kudos to @nicm, and thank you all for the great job!
