### ISSUE TITLE
Custom menus should be scrollable in case they don't fit in the window

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#55739] opened 2018-08-03 08:38 UTC
macOS style

**Comment by sbatten** [comment] 2018-08-03 16:56
#52533

**Comment by joaomoreno** [comment] 2018-08-06 07:55
@sbatten I've pushed an improved context view layout algorithm which makes sure the widget is always visible if it can fit the window. So, the GIF in the first post of #52533 will not happen any more. This issue is about the cases where the menus doesn't fit at all in the window.

**Comment by bpasero** [comment] 2018-11-28 09:38
Isn't this fixed with the new scrollbar in menus?

**Comment by sbatten** [comment] 2018-11-28 18:10
yes this should be resolved as duplicate of #52533

**Closed by sbatten** 2018-11-28 18:10 UTC
Labels: feature-request, workbench-menu
