### ISSUE TITLE
Syntax coloring randomly dimmed

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#63864] opened 2018-11-27 15:16 UTC
Issue Type: <b>Bug</b>

I noticed in the latest Insiders that some of the syntax coloring does not match, even though when inspected it's the same scope and hex color.  Reloading the window corrects the issue, but eventually it recurs.

### Before, showing the issue:
<img width="332" alt="before" src="https://user-images.githubusercontent.com/835148/49091310-85615a00-f22d-11e8-8bb2-46689a465551.png">

### After reload window:
<img width="399" alt="after" src="https://user-images.githubusercontent.com/835148/49091324-8eeac200-f22d-11e8-8124-80d285fba2a4.png">

Notice "sidebar" and "_wpapi"

VS Code version: Code - Insiders 1.30.0-insider (d3bb20c3fd1f23c369b80dca2ed25d54efd664e2, 2018-11-27T08:19:57.734Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|-psn_0_1402317063|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-svgo|ajh|0.1.0
Bookmarks|ale|9.3.0
project-manager|ale|9.1.0
ACF-Snippet|ant|1.9.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
prettier-vscode|esb|1.7.2
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.13.0
svg|joc|0.1.4
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
theme-monokai-pro-vscode|mon|1.1.9
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-html-scss|P-d|0.0.42
vscode-versionlens|pfl|0.22.0
polacode|pnp|0.2.2
quicktype|qui|12.0.46
LiveServer|rit|5.3.0
code-settings-sync|Sha|3.2.2
stylelint|shi|0.46.1
rewrap|stk|1.9.1
ayu|tea|0.17.0
sort-lines|Tyr|1.7.0
vscode-terminal-here|Tyr|0.1.1
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-11-27 19:57
If you hover over those variables, do you see a message about them being unused?

**Comment by smlombardi** [comment] 2018-11-27 21:14
This was when (somehow) VSCode was using Typescript 3.2rc2.  I also saw the ellipses under non-typed variables.

I then switched back to the version of Typescript in the project, 2.7.2 and the ellipses and the dimming are gone.  Is that a feature, and does it require a news version of Typescript?

**Comment by smlombardi** [comment] 2018-11-27 21:16
Also, I believe they _are_ used, see `this.sidebar = _globals.sidebar; ` in constructor; doesn't that mark it as used? 

The other one `_wpapi` is no longer used in this component.

**Comment by mjbvz** [comment] 2018-11-27 21:18
yes unused variable marking require TS 2.9+. If the variable is never read, it is be marked unused even if it is assigned to

Was that the cause of the dimming?

**Comment by smlombardi** [comment] 2018-11-27 21:38
Probably.  I can't seem to switch Code back to using a new Typescript to check for sure, because now I get this message 

<img width="667" alt="screen shot 2018-11-27 at 4 38 00 pm" src="https://user-images.githubusercontent.com/835148/49113186-dccded00-f262-11e8-800f-d69995a85b17.png">

**Comment by mjbvz** [comment] 2018-11-27 22:17
Did you have `typescript.tsdk` configured in your user settings? It is likely pointing to an invalid path

**Comment by smlombardi** [comment] 2018-11-28 13:51
My workspace settings file has
```
{
  "path-autocomplete.pathMappings": {
    "/": "${folder}/client/src"
  },
  "html.format.wrapAttributes": "force-aligned",
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

My User Settings file does not have this entry.

**Comment by mjbvz** [comment] 2018-11-29 02:36
I'm closing this dimming issue as by-design 

VS Code's version of typescript would only be under that path if `typescript.tsdk` is configured in user settings (either by you or through an extension). If you select the invalid version that is listed, it should fall back to the bundled version as well

**Closed by mjbvz** 2018-11-29 02:36 UTC
Labels: insiders, needs more info
