### ISSUE TITLE
scrollBeyondFirstLine

### ISSUE THREAD

**Issue by b5414** [microsoft/vscode#108548] opened 2020-10-12 21:29 UTC
### Feature Request

Hello, everything is fine, good product :) 

You already have a _checkbox_ in the settings, which is responsible for `editor.scrollBeyondLastLine`
I would also like to use an inverted _similar checkbox_, which (will be) named: `scrollBeyondFirstLine`
It is not very comfortable to look up, and I would like to keep the *first line* at the level of ~`10-20 lines`

**Comment by ArturoDent** [comment] 2020-10-13 04:32
Is this the same as https://github.com/microsoft/vscode/issues/49027

**Comment by b5414** [comment] 2020-10-13 09:05
Wow, `editor.paddingTop` - works good, thank you @ArturoDent 

But I'd like the `scrollBeyondFirstLine` feature, because of two reasons: 
1. `paddingTop` will move 1 line at center every `ctrl+N`, to pixels :(
2. `scrollBeyondFirstLine` is similar to `scrollBeyondLastLine`... > easy search + independent of the typed pixels (you can scroll more, and again about (1) - not put your 1 line to the bottom)

**Comment by b5414** [comment] 2020-10-14 05:13
LOL, the `Output (code)` also takes the value from `editor.padding.top`, and it's really bad, probably this is a bug
https://imgur.com/wxRRbRt (I just pressed compile = `Run code` in `formulahendry.code-runner` ext)

Also, about the `needs more info` tag, [#49027](https://github.com/microsoft/vscode/issues/49027) is the same

**Comment by chrmarti** [comment] 2020-10-14 08:37
@sandy081 for the `editor.padding.top` being applied to the Output panel in case that is a bug. Otherwise good to close as a duplicate of #49027. Thanks.

**Comment by sandy081** [comment] 2020-10-19 14:33
Fixed padding in output.

**Closed by sandy081** 2020-10-19 14:33 UTC
Labels: needs more info
