### ISSUE TITLE
Braket pair colorization get confused

### ISSUE THREAD

**Issue by yuvalrakavy** [microsoft/vscode#132163] opened 2021-09-02 20:33 UTC
Issue Type: <b>Bug</b>

Use Rust

Use expression such as:

fn x() -> i16 { }

 The > is treated as braket and is colored. This is incorrect.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|128.00GB (1.49GB free)|
|Process Argv|--crash-reporter-id 59bb568f-99d7-4d02-8384-cfbc0b1f4a76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|1.1.2
vscode-gcode-syntax|app|0.6.2
hsm-post-processor|Aut|3.5.5
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
githistory|don|0.6.18
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.30.0
go|gol|0.27.2
vscode-systemd-support|han|0.1.1
fusion-360-helper|Hic|1.0.4
Ionide-fsharp|Ion|5.7.1
rust-analyzer|mat|0.2.727
rainbow-csv|mec|1.9.1
csharp|ms-|1.23.15
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
powershell|ms-|2021.8.2
vscode-typescript-tslint-plugin|ms-|1.3.3
printcode|nob|3.0.0
vscode-xml-complete|rog|0.3.0
toggle-case|rya|1.0.2
vscode-fileutils|sle|3.4.5
tabnine-vscode|Tab|3.4.26
vscodeintellicode|Vis|1.2.14
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
vsdyn478:30356813
vscus224:30358039

```

</details>

**Comment by hediet** [comment] 2021-09-05 20:43
Duplicate of #132336.

Please ping the author of the language-extension to remove `<`...`>` from the bracket pairs to colorize. (see [my comment](https://github.com/microsoft/vscode/issues/132336#issuecomment-913204643))

**Closed by hediet** 2021-09-05 20:43 UTC
Labels: new release
