### ISSUE TITLE
Failed opening Getting Started in latest insider version.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#121510] opened 2021-04-16 21:10 UTC
- VS Code Version: 1.56.0 - Insider (Commit: ce791d27) 
- OS Version: Windows 10 20h2

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/17777237/115084095-a747fe00-9f08-11eb-9431-e86f882fce97.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2021-04-16 21:36
/duplicate of #121456 and fixed in the next Insiders

**Closed** 2021-04-16 21:37 UTC
Labels: *duplicate
