### ISSUE TITLE
Split editor - editing on the left side makes folded code on the right side to expand

### ISSUE THREAD

**Issue by ddenev** [microsoft/vscode#159646] opened 2022-08-31 07:44 UTC
Type: <b>Bug</b>

This was first reported to the Volar extension team:
https://github.com/johnsoncodehk/volar/issues/1702

How to reproduce:
- open a .vue file with the Volar extension installed
- open Volar split view (opens `<script>` and `<style>` on one side and `<template>` on the other side)
- collapse all sections on the right side
- start typing in any section on the left side, e.g. in `<template>` section

You will see that `<template>` on the right side is automatically expanded.

Volar team said this is a VSCode issue (see the issue above).

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.6.1
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.8.0
JavaScriptSnippetsStandard|jms|1.8.0
csharp|ms-|1.25.0
material-icon-theme|PKi|4.20.0
volar|Vue|0.40.5
vscode-todo-highlight|way|1.0.5
material-theme|zhu|3.15.2

</details>

**Comment by aeschli** [comment] 2022-09-30 07:53
Duplicate of https://github.com/microsoft/vscode/issues/161647

**Closed by aeschli** 2022-09-30 07:53 UTC
