### ISSUE TITLE
PHP should have word completion

### ISSUE THREAD

**Issue by dannyZhou** [Microsoft/vscode#10001] opened 2016-08-01 00:40 UTC
- VSCode Version:
  - Version 1.3.1
  - Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae
  - Date 2016-07-12T13:28:46.761Z
  - Shell 0.37.6
  - Renderer 49.0.2623.75
  - Node 5.10.0
- OS Version: `ubuntu 14.04`  `3.13.0-32-generic`  `x86_64` 
- File Type: *.php

Preferences:

``` json
{
    "files.trimTrailingWhitespace": true,
    "files.autoSave": "onFocusChange"
}
```

Steps to Reproduce:
1. Open code.
2. `Select Language Mode` to PHP. (Or open a `php` file)
3. In the first line, I input `Helloworld`.
4. In the second line I input `Hell`.
5. Check `word completion list` has word `Helloword`.

![screenshot - 2016 07 29 - 12 21 15](https://cloud.githubusercontent.com/assets/6329191/17237665/f8dbb692-5586-11e6-80b0-ceff96fe73cf.png)

In this version has save problem. 
- Version 1.4.0-insider
- Commit 4656fe3ff2952e9538d81e7a7571674352e5d62f
- Date 2016-07-29T05:12:17.453Z
- Shell 0.37.6
- Renderer 49.0.2623.75
- Node 5.10.0

**Comment by mjbvz** [comment] 2017-11-03 20:14
Duplicate of #21611

**Closed by mjbvz** 2017-11-03 20:14 UTC
Labels: feature-request
