### ISSUE TITLE
[Feature Request] Open Powershell as native console

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#4353] opened 2016-03-17 10:27 UTC
Could you add functionality to specify which console to open when using the `ctrl+shift+c` keyboard shortcut to run the command `workbench.action.terminal.openNativeConsole`
This would allow users to specify using Powershell over Cmd

**Comment by felixfbecker** [comment] 2016-03-17 14:53
duplicate of https://github.com/Microsoft/vscode/issues/1905

**Comment by stkb** [comment] 2016-03-17 18:43
@tht13 You can use the [Open in User-defined Console](https://marketplace.visualstudio.com/items?itemName=vilicvane.console) extension

**Comment by felixfbecker** [comment] 2016-03-17 19:02
@stkb that doesn't apply to right click > open command prompt here though

**Comment by stkb** [comment] 2016-03-17 19:11
@felixfbecker That's true, but I was only replying to tht13 about his original request regarding the `ctrl+shift+c` shortcut.

Though if they implement the choice for the right-click menu they should do it for `ctrl+shift+c` action too, of course.

**Comment by joaomoreno** [comment] 2016-03-17 22:22
Yeah, closing as duplicate of #1905.

**Closed by joaomoreno** 2016-03-17 22:22 UTC
