### ISSUE TITLE
Code silently failing on Mac OS Sierra

### ISSUE THREAD

**Issue by dragos** [Microsoft/vscode#19564] opened 2017-01-29 14:30 UTC
- VSCode Version: 1.8.1
- OS Version: 10.12.2

I simply can't start Code anymore. Yesterday it worked fine, and as far as I can tell, nothing has changed (no updates, neither OS nor Code) since then.

Steps to Reproduce:

```
$ code . --verbose
[main 15:28:23] Sending env to running instance...
[main 15:28:23] Sent env to running instance. Terminating...
$ 
```

Same behaviour when I try to open it from the Applications folder, or without any arguments on the command line.

There are no Code processes running.

```
$ ps -ax | grep code
20412 ??         0:00.04 /System/Library/Frameworks/VideoToolbox.framework/Versions/A/XPCServices/VTDecoderXPCService.xpc/Contents/MacOS/VTDecoderXPCService
23254 ttys005    0:00.00 grep code
```

Nothing of note in the system log either.

**Comment by dragos** [comment] 2017-01-29 14:32
`code --disable-extensions` doesn't work either.

**Comment by Nikki1993** [comment] 2017-01-29 15:51
Can't reproduce on macOS: 10.12.3, vscode 1.8.1 Have you tried running permission check through disk utility &/or reinstalling VS Code entirely? I'd suggest use https://freemacsoft.net/appcleaner/ for that as it removes **everything** related to the app unlike simple drag to the trash bin.

**Comment by dragos** [comment] 2017-01-29 16:21
It started working again after a restart, but I thought it's still worth investigating.

**Comment by mousetraps** [comment] 2017-01-30 02:22
cc @bpasero if he has any clues, but it's hard for us to investigate if we don't have a repro. Closing this issue, but happy to reopen if you run into it again, and can provide more details. Happy coding!

**Closed by mousetraps** 2017-01-30 02:22 UTC

**Comment by bpasero** [comment] 2017-01-30 06:55
Issues like this seem to happen when there is still a Code process hanging around even though no visible Window is open for Code. In that case a restart helps or finding that stray process and terminating it.

**Comment by dragos** [comment] 2017-01-30 07:52
How can I provide more details? `--verbose` shows nothing of value, and there was no code process (at least, no process with `code` in its name). I'm happy to provide more details when it happens again, but I need some handle on *how to get those details*.
