### ISSUE TITLE
Support other shell types for terminal shell integration history

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155530] opened 2022-07-18 18:33 UTC
Currently only pwsh, bash and zsh shell types are allowed to restore and fetch history for shell integration:

https://github.com/microsoft/vscode/blob/8846ac54887deb74afdb262cbdaecdd12b824f98/src/vs/workbench/contrib/terminal/common/history.ts#L82-L94

This needs to be more flexible to support other REPLs like fish, [julia](https://github.com/microsoft/vscode/issues/155315), python, etc.

**Comment by babakks** [comment] 2022-07-23 18:06
@Tyriar I've submitted a PR for `fish` shell. Could you please review it?

**Comment by pfitzseb** [comment] 2022-08-05 08:45
Should probably reopen this, considering that https://github.com/microsoft/vscode/pull/156058 only supports fish.

**Comment by Tyriar** [comment] 2023-12-13 13:42
Closing again, here's the current state:

- fish is automatically activated
- The Python extension is experimenting with shell integration in their REPL command
- Julia extension handles shell integration
- The Nushell extension handles shell integration

Generally new shells should be handled in extensions or manual scripts unless it hits some critical mass where it's justified to build in support for VS Code.

**Comment by pfitzseb** [comment] 2023-12-13 14:22
Julia commands are now properly inserted into the history (and persisted across terminal restarts), but it looks like recent commands are not looked up based on the current shell (which means my zsh and julia commands are mixed together). Is that working as intended?

**Comment by Tyriar** [comment] 2023-12-13 14:46
Doh, I read the issue wrong you're right 🤦

This does need to happen still and we'll run into this very soon with the upcoming Python integration. cc @anthonykim1

**Comment by anthonykim1** [comment] 2023-12-13 22:15
Yessss! I this would be awesome for run recent command https://github.com/microsoft/vscode-python/issues/22647 which should happen in January after I make changes for #199770 as advised. (red/blue decorations are everywhere with Windows pwsh users when trying to use shell integration for Python REPL)

**Comment by meganrogge** [comment] 2023-12-19 18:02
@jooyoungseo here is where we're tracking this issue that you're eagerly awaiting 😄 .

**Comment by Tyriar** [comment] 2024-03-22 17:49
@anthonykim1 planning on this for March?

**Comment by anthonykim1** [comment] 2024-03-23 05:58
@Tyriar I have a PR open, but did not have a room to finish this month. Will try to get this onto the plan next month!

**Comment by anthonykim1** [comment] 2024-08-19 01:20
Closing this as completed Julia, Nushell, Python is merged.

**Closed by anthonykim1** 2024-08-19 01:20 UTC
Labels: help wanted, feature-request, terminal-shell-integration

**Comment by anthonykim1** [comment] 2024-08-26 22:36
https://github.com/microsoft/vscode/issues/224326 and https://github.com/microsoft/vscode/issues/224325 have the appropriate verification steps. Removing this from the milestone.

**Comment by Tyriar** [comment] 2024-08-27 16:35
@anthonykim1 since the work happened in August just adding verified it a nicer way to track things without losing the milestone info.
