### ISSUE TITLE
Empty spaces - Exponential backoff?

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#221009] opened 2024-07-08 09:47 UTC
The converging space sequence might be coincidence:

![Image](https://github.com/user-attachments/assets/6b464830-60be-4cf3-ae43-a6e8b97525a0)

The sequence is:
```
24
9
5
4
2
2
2
1
```
... so maybe it is just random.

Other spooky things are going on as well:

![Image](https://github.com/user-attachments/assets/68d4555e-6068-4216-8363-74ba5fcb6e8f)

**Comment by hediet** [comment] 2024-07-08 17:15
unfortunately I don't remember what happened before...

**Comment by Tyriar** [comment] 2024-12-18 19:41
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-18 19:41 UTC
