### ISSUE TITLE
Consider using markdown preview font size for font size in notebooks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#130695] opened 2021-08-12 16:26 UTC
Markdown font sizes shouldn't necessarily correspond to the font size of output elsewhere in a notebook. It would be nice if the font of markdown could be modified independent of the output font.

See comments here:
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details

**Comment by mjbvz** [comment] 2021-08-12 18:49
Duplicate of #126294

**Closed by mjbvz** 2021-08-12 18:49 UTC
