### ISSUE TITLE
Rendering glitch integrated terminal when window maximised 

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#121066] opened 2021-04-12 04:29 UTC
## VS Code Version:
Version: 1.55.1 (user setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0

- OS Version:
_Windows_NT x64 10.0.19042

## Steps to Reproduce:

1. Open the integrated terminal pane by typing Ctrl+`
2. Observe that the pane looks like this
![image](https://user-images.githubusercontent.com/5498936/114339741-45e6fe80-9b99-11eb-86ba-3f2a6c66fef2.png)
5. Observe that this only occurs when the window is maximised.
6. Observe that anything that triggers a resize fixes it.
7. Observe that changing the integrated terminal letter spacing also fixes it.

Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

**Comment by PeterWone** [comment] 2021-04-12 05:41
And a reboot appears to have made it go away.

**Comment by meganrogge** [comment] 2021-04-14 15:53
Probably a duplicate of https://github.com/microsoft/vscode/issues/120004

**Closed by meganrogge** 2021-04-14 15:53 UTC
