### ISSUE TITLE
problems with the cursor when I press enter

### ISSUE THREAD

**Issue by linedotwww** [Microsoft/vscode#19414] opened 2017-01-26 05:52 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-caniuse|akamud|0.5.3|
|theme-onedark|azemoh|0.4.3|
|path-intellisense|christian-kohler|1.2.0|
|vscode-great-icons|emmanuelbeziat|1.1.40|
|auto-rename-tag|formulahendry|0.0.11|
|easy-less|mrcrowl|1.3.4|
|vscode-duplicate|mrmlnc|1.0.2|
|vscode-less|mrmlnc|0.6.0|
|sublime-keybindings|ms-vscode|1.8.2|
|html-css-class-completion|Zignd|1.0.3|

---
I show you how it works in atom.

![gif1](https://cloud.githubusercontent.com/assets/15665678/22321128/18f3d856-e3a3-11e6-8469-b4f3d79c117e.gif)

then I show you how it works in VSCODE

![gif2](https://cloud.githubusercontent.com/assets/15665678/22321175/862806d6-e3a3-11e6-953d-5a1b7b7a8122.gif)

Steps to Reproduce:

1. I have to press "Enter" twice to move to a new line because when I click first time it returns to its original position. Although logically there should be a transition but a new line.

**Comment by mousetraps** [comment] 2017-01-26 20:42
Hey @linedotwww - sorry to hear you're running into issues! This appears to be an issue with the html-snippets extension, rather than the built-in HTML support. Mind reporting it over there instead?

Closing this issue as it's caused by an extension, but lmk if you meant something different, and we'll be happy to reopen. Happy coding!

**Closed by mousetraps** 2017-01-26 20:42 UTC
Labels: caused-by-extension, html

**Comment by linedotwww** [comment] 2017-01-26 20:53
мне приходится два раза нажимать клавишу энтер чтоб добавить новую строку и это не проблема.
