### ISSUE TITLE
Brackets not closing automatically in python and javascript , in c++ its working correct 

### ISSUE THREAD

**Issue by satyam4484** [microsoft/vscode#128494] opened 2021-07-12 16:57 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Latest
- OS Version: ubuntu latest

Steps to Reproduce:

1.create a file with extension **.py** or **.js** .
2. write some piece of code and when you press these **(** .
3. Expected **( )** .
4. Getting **(**.

**Comment by hediet** [comment] 2021-07-13 07:34
Duplicate of #127739.

**Closed** 2021-07-13 07:35 UTC
Labels: *duplicate
