### ISSUE TITLE
Minified js breaking autoformatter

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#20069] opened 2017-02-06 18:32 UTC
- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

First script tag and contents causing Auto formatter (alt-shift-f) to break the javascript.

```
<!DOCTYPE html>
<html>

<body>
<div class="container">
	<div class="hero-unit">
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
		</script>
	</div>



	<script type="text/javascript">
		var disqus_shortname = 'bootstrapcalendar'; // required: replace example with your forum shortname
        var calendar = $("#calendar").calendar(
            {
                tmpl_path: "/tmpls/",
                events_source: function () { return [
					{
						"success": 1,
						"result": [
							{
								"id": 293,
								"title": "Event 1",
								"url": "http://example.com",
								"class": "event-important",
								"start": 12039485678000, // Milliseconds
								"end": 1234576967000 // Milliseconds
							},
						
						]
					}
				]; }
            }); 
	</script>
</div>
</body>
</html>

```

auto formats to

```
<!DOCTYPE html>
<html>

<body>
	<div class="container">
		<div class="hero-unit">
			<script>
				!f unc ti on( d ,s,id){ var   js,fjs=d.getElementsByTagName ( s )[0],p=/^http:/.test(d.lo c ation) ? 'http':' ht tps';if(!d.getElementBy I d( i d)){js=d.createElem ent(s ) ;js .id=id ; j s .src=p+'://platform.twitter.com/widge ts.js';fjs.parentNode.insertBef ore(j s , fjs);}}(document, 'script', 'twitter-w');
			</script>
		</div>



		<script type="text/javascript">
			var disqus_shortname = 'bootstrapcalendar'; // required: replace example with your forum s			
        var calendar = $("#calendar").c				   					          tmpl_path: "/					          events_source: fun
						tion () { 							n [									{
						"succ								1,
						"re									[
										
								"i										
								"title": "E										
								"url": "http://examp										
								"class": "event-imp										
								"start": 12039485678000, // Mill										
								"end": 1234576967000 // Mill									s
	},										
									]								
					}
				        });
		</script>
	</div>
</body>

</html>
```

**Comment by mjbvz** [comment] 2017-02-06 18:48
Closing as a duplicate of #19813. I believe @aeschli already has a fix checked in.

**Closed by mjbvz** 2017-02-06 18:48 UTC
Labels: duplicate, format
