### ISSUE TITLE
regression:   "editor.selectionClipboard": false no longer respected on ubuntu

### ISSUE THREAD

**Issue by GuyKedem1** [microsoft/vscode#49305] opened 2018-05-06 13:45 UTC
middle click paste now works, as opposed to previous versions. 

- VSCode Version: april release
- OS Version: ubuntu 17.10

**Comment by Tyriar** [comment] 2018-05-11 18:12
@alexandrudima box selection may have broken this, if both can't live in harmony then middle click to paste selection should win (until we get https://github.com/Microsoft/vscode/issues/3130)

**Comment by Nekotekina** [comment] 2018-06-05 14:41
Why there is no separate setting for middle-click paste? Or it's the only thing that is supposed to be affected by this setting?

**Comment by goosenphil** [comment] 2018-07-04 09:57
I am also experiencing this issue

**Comment by Argysh** [comment] 2018-09-11 06:57
+1 
I'm constantly screwing up my code when scrolling through it. (hypersensitive mouse wheel syndrome) 
I would really like to be able to disable it again

**Comment by yli3** [comment] 2018-10-16 00:09
Is there a resolution to this? VScode is in the only application in which this happens, the proposed setting of editor.selectionClipboard to false does not fix it, and my code is also constantly breaking everywhere because of unnoticed and accidental middle-clicks. I'd greatly appreciate some relief from this!

**Comment by faiwer** [comment] 2018-10-17 10:51
@yli3 there's an [answer](https://github.com/Microsoft/vscode/issues/59065) from @Tyriar:

> This is as designed, I'm not even sure we could disable it if we wanted to since it's an OS-level thing and we're build on the web platform.

It sounds like we're doomed to suffer :)

**Comment by Grinnz** [comment] 2018-10-17 15:51
It worked before the April release.

**Comment by zaverden** [comment] 2018-10-23 10:50
reproduced with following versions:

VS code:
```
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
Ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

**Comment by j-james** [comment] 2018-10-31 17:30
I too am experiencing this issue. This makes it hard to type when all my code gets pasted in every time I touch my trackpad wrong. 

Manjaro:
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.0
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"
```

Code - OSS: 
```
Version: 1.27.2
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-14T00:41:55.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by SunYongshuai** [comment] 2018-12-22 12:33
I meet the same problem.
I turn "middle paste" in the system setting and set "editor.selectionClipboard" false, but it doesn't work.
System Info:
Ubuntu 18.04 
Linux <name> 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

VS code info:
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64

Is there any ways to solve the problem?

**Comment by SunYongshuai** [comment] 2018-12-23 08:30
May be it is the problem of system.
And I turn off the middle button function to solve the problem. And it works for me.
Reference: [xorg - How can I turn off “middle mouse button paste” functionality in all programs?](https://unix.stackexchange.com/questions/24330/how-can-i-turn-off-middle-mouse-button-paste-functionality-in-all-programs)

**Comment by Grinnz** [comment] 2018-12-24 00:41
It is not a problem of the system. As I already noted, this is a regression.

**Comment by claudiocarcaci** [comment] 2019-01-15 09:53
Also for me.
+1

**Comment by AlibekJ** [comment] 2019-01-17 06:47
Middle-click paste is disabled in my system. Pastes nowhere except vscode.

   ` "editor.selectionClipboard": false` in settings 

 

Ubuntu 18.10
Linux 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.18.0-13-generic

**Comment by vincenzoml** [comment] 2019-01-24 09:18
To clarify for those who think this is an xorg setting; it's not. Applications implement the protocol. That's why disabling it in gnome via gnome-tweaks does not disable it in vscode; and in chrome, for the record.r r the record.r the record.the record. ;-)

**Comment by hsandt** [comment] 2019-01-31 23:55
I had to use Easystroke Gesture Recognition to remap Middle click to Ctrl+click, so I can navigate to the symbol under the cursor instead of pasting.

It works fine. I was already using this app for other gestures anyway (like Mouse wheel left -> Ctrl + PgUp to open previous tab).

That remains a workaround though. As for actually binding Middle click to something else, see https://github.com/Microsoft/vscode/issues/3130

**Comment by dtmland** [comment] 2019-02-27 21:06
+1 Please fix

Best workaround I have found so far:

> No need to disable your precious middle mouse button bindings, no clearing of visual selections nor performance losses because of emptying the primary X clipboard periodically. With the utilization of XInput and Xlibs this has no measurable impact on performance whatsoever. No elevated privileges required. Just run within your regular users' X session.

https://github.com/milaq/XMousePasteBlock

**Comment by vincenzoml** [comment] 2019-02-28 14:09
@dtmland  thanks a lot, immensely helpful.

**Comment by sudhirdhumal289** [comment] 2019-03-09 07:08
Can we not have setting for this feature in VS Code.
This is irritating, I wrote hundreds of line and after save I get an error in browser because of this stupid behaviour.

Setting to disable the three finger tap to paste is really necessary.

Behaviour is reproducible every time. Copy manually (right click and copy something, or ctrl+c) then tap with 3 fingers. (selectionClipboard setting in this case is not working)

**Comment by donaldcallen** [comment] 2019-04-01 03:28
This editor is unusable for me. I've had the clipboard spattered all over my code simply because I used the mouse wheel to scroll for the last time. It's absurd that there is no way to disable this.

**Comment by tommyvct** [comment] 2019-04-05 01:06
I bet this issue will never be solved until 2050

**Comment by ACheshirov** [comment] 2019-04-10 21:23
@donaldcallen same problem here. It's very annoying...

**Comment by NotKyros** [comment] 2019-04-14 04:21
This issue needs to get fixed. Several times I've wasted time having to debug my code when all that happened was an extra line got pasted in somewhere on accident.

**Comment by Vivalio** [comment] 2019-04-15 14:16
This may help. i havent tried as i dont have the time, but it was marked as the answer in S.O. https://app.assembla.com/spaces/slipstream/wiki/Disabling_GTK's_middle_mouse_button_functionality

**Comment by lss4** [comment] 2019-04-16 03:02
Originally I looked at #14610 and followed its instructions and the middle-click paste did stop for once, but after that this unwanted behavior reappeared. Then I found this... so the editor setting doesn't really work after all.

It's really necessary to disable this within the app as in some cases VS code would paste unwanted stuffs while scrolling as if the middle wheel was clicked (while in reality I did not).

**Comment by averypierce** [comment] 2019-04-16 19:41
> EDIT: XMousePasteBlock apparently works as intended... just that I don't know where and how I should put it in the startup script so it can cover everywhere (all programs, sudo/root or not).

Appending `xmousepasteblock &` to ~/.profile oughta do it.
- Open terminal
- enter `gedit ~/.profile`
- paste in `xmousepasteblock &` and save
- Important: Don't omit the `&` or your computer will hang on login.

**Comment by ivorhoulker** [comment] 2019-05-14 08:35
Finally found what was causing my code to constantly break when navigating with the mouse.  I'm having the same issue on my mac and it's making it very frustrating to work with - I will try the solutions proposed here but really hope it can be fixed properly.

**Comment by monaroau** [comment] 2019-06-15 11:49
Is there a fix for this yet?

**Comment by ACheshirov** [comment] 2019-06-15 19:07
XMousePasteBlock is the best. I made it to start with the system and I'm fine now. :)

**Comment by waynebloss** [comment] 2019-06-25 14:13
Same here on Arch / Manjaro with XFCE

**Comment by MrStofkat** [comment] 2019-07-10 16:36
Bumping for a solution to this problem. Especially with a sensitive middle mouse button this is very annoying. Just like @ivorhoulker it took me some time to figure out what was actually causing this.

**Comment by donaldcallen** [comment] 2019-07-10 17:11
I no longer use this editor because of this.

**Comment by waynebloss** [comment] 2019-07-10 19:02
@donaldcallen If you don't use middle-click to paste you can disable it system-wide with [XMousePasteBlock](https://aur.archlinux.org/packages/xmousepasteblock-git/).

**Comment by lss4** [comment] 2019-07-11 00:32
Additionally... it seems VSCode often mistreats mouse scrolls as middle clicks causing unwanted pastes.

While this is indeed a system-level feature, I recall that before using XMousePasteBlock, in other programs, if I really have to paste something that way I need to _explicitly_ do a middle click, and mouse scrolls hardly caused any unwanted pastes outside VSCode.

**Comment by waynebloss** [comment] 2019-07-11 18:35
The back/forward buttons on my mouse started working on my Linux workstation today, so we're definitely making progress. Thanks!

**Comment by leimao** [comment] 2019-07-13 17:58
I am having the exact same problem. Could you guys fix it soon? Thank you very much.

**Comment by yay** [comment] 2019-08-06 20:11
![Screenshot from 2019-08-06 21-10-22](https://user-images.githubusercontent.com/1799756/62573757-ae42f000-b88e-11e9-94d6-1c991bd8b183.png)
The `Middle Click Paste` option is respected by other apps, but not VS Code.

**Comment by plezan** [comment] 2019-09-17 09:56
Please at least disable it when it is maped for the multi-selection, That realy is a dealbreaker

**Comment by aaronps** [comment] 2019-09-29 08:27
Yes, this problem is breaking code constantly, year and half and still going, let's see how many years takes to fix.

**Comment by souldomination** [comment] 2019-10-02 09:00
Is disabling middle button click the only solution for this problem currently? So sad.

**Comment by ACheshirov** [comment] 2019-10-02 09:43
Look guys, if you doesn't use middle click paste feature, you could install XMousePasteBlock, which fix this issue. You could still use middle click at all, it just disable that paste feature. I'm using it and it works perfect.

**Comment by dorianfm** [comment] 2019-10-02 12:05
+1 for a fix

**Comment by j-james** [comment] 2019-10-02 20:46
@ACheshirov 
The issue for many people (or at least me and @souldomination ) is that we use middle-click paste outside of Visual Studio. But it's very easy to paste your buffer without realizing it scrolling, and not very easy to find and remove that code.

**Comment by lss4** [comment] 2019-10-02 23:28
> @ACheshirov
> The issue for many people (or at least me and @souldomination ) is that we use middle-click paste outside of Visual Studio. But it's very easy to paste your buffer without realizing it scrolling, and not very easy to find and remove that code.

Yeah, the problem with VSCode is that things get pasted _while scrolling_ with middle mouse wheel (without having to explicitly middle-click). This is hardly expected behavior and can be hard to notice at times.

Using XMousePasteBlock disables middle-click paste feature system-wise and also fixes the VSCode issue that things get pasted while scrolling, but it's indeed not a solution for those who do use the middle-click paste feature.

**Closed** 2019-10-10 14:46 UTC
Labels: bug, editor-contrib, linux
