### ISSUE TITLE
The Auth API for microsoft provider is  broken in insiders version

### ISSUE THREAD

**Issue by samrat-gavale** [microsoft/vscode#117276] opened 2021-02-22 19:30 UTC
Issue Type: <b>Bug</b>

1. Create an empty extensions named aad-auth-1 through the yo code generator. See this tutorial.
2. Register an AAD app to act as a resource. See this. You can skip 8th step here.
3. Add the VS Code AAD client (Id: aebc6443-996d-45c2-90f0-388ff96faa56) as trusted client for the user_impersonation scope in the above two AAD apps.
4. In  extension, package.json, change the hello world command title to Hello World 1 . Then update the command execution to
```
let disposable = vscode.commands.registerCommand('aad-auth-1.helloWorld1', async () => {
    // The code you place here will be executed every time your command is executed

    // Display a message box to the user
    vscode.window.showInformationMessage('Hello World from aad-auth-1!');
    try {
        await vscode.authentication.getSession('microsoft', [
            'cd96451f-9709-4a95-b1f5-79da05cf8502/user_impersonation',
            'offline_access',
            ], { clearSessionPreference: false, createIfNone: false })
            .then((session: vscode.AuthenticationSession) => {
                console.log(session);
            });
    } catch (error) {
        console.log(error.message);
    }
});
```
Note that the AAD resource ID needs to be updated above in the scopes argument to the `getSession` method.

5. Compile, package and install the extension on VS Code insiders.
6. Run the command Hello World 1. You should get a blue glyph on the user accounts menu at bottom left. Sign in into the extension using AAD identity. 
7. Run the command Hello World 1 again. You will see another blue glyph on user accounts menu asking you to sign in. Ideally the session should be available and logged into the console. Instead the console logs `undefined`. You can open the console through Help -->Toggle developer tools to verify. 

VS Code version: Code - Insiders 1.54.0-insider (11cd76005bc7516dcc726d7389d0bce1744e5c85, 2021-02-22T05:14:36.498Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.34GB free)|
|Process Argv|--folder-uri file:///d%3A/code/vscodeexts/aad-auth-1 --crash-reporter-id 89bbd2c8-eadf-40a4-831a-2bab71a0d01a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.3.3

</details>

**Comment by RMacfarlane** [comment] 2021-02-22 20:21
Duplicate of https://github.com/microsoft/vscode/issues/117266

**Closed by RMacfarlane** 2021-02-22 20:21 UTC
