### ISSUE TITLE
Under tasks/command the env.EnvironmentVariableName (eg. env.graphviz) does no expand.

### ISSUE THREAD

**Issue by RafaelSchreiner** [Microsoft/vscode#28533] opened 2017-06-12 14:22 UTC
- VSCode Version: 1.13.0
- OS Version: Win 7 Pro 64 Bit

Calling a task with "command": "${env.graphviz}/dot.exe" does not expand any more with vscode 1.13.0.
But calling with "command": "%graphviz%/dot.exe" does

Steps to Reproduce:

1. create an env "graphviz" like "c:\tools\graphviz\bin" under windows env dialog
2. create a task.json file with 
"version": "0.1.0",
"tasks": [
{
"isShellCommand": true,
"showOutput": "always",
"echoCommand": true,
"suppressTaskName": true,
"command": "${env.graphviz}/dot.exe",
"taskname": "graphviz svg",
"args": ["-Tsvg", "${file}", "-o", "${fileDirname}/${fileBaseNameNoExtension}.svg"]
}
...
]

I get the output:
 '${env.graphviz}' is not recognized as an internal or external command,...

**Comment by Triztian** [comment] 2017-06-12 19:39
I'm experiencing the same in macOS

**Comment by ramya-rao-a** [comment] 2017-06-12 21:16
Closing as duplicate of #28365

cc @dbaeumer

**Closed by ramya-rao-a** 2017-06-12 21:16 UTC
Labels: new release
