### ISSUE TITLE
Auto-format indentation not working right in JavaScript/jQuery

### ISSUE THREAD

**Issue by davelogear** [Microsoft/vscode#50354] opened 2018-05-23 13:35 UTC
After hitting the auto-format keyboard shortcut, the .done and .fail parts indent too far... it throws off the ending brace which is two indents in after the whole function call train rather than 1 where the train started (with .ajax).

![image](https://user-images.githubusercontent.com/32692076/40424227-3248c62e-5e52-11e8-9c50-ffe03a0ce8f8.png)

- VSCode Version: 1.23.1
- OS Version: Windows 7 64-bit latest

Steps to Reproduce:

1. Create a .html file that includes the latest jQuery.
2. Add a <script> with an $.ajax call, an attached .done call, then an attached .fail call.
3. Use the auto-format keyboard shortcut (mine is Ctrl+Shift+F), tied to editor.action.formatDocument.
4. Notice .done and .fail are indented one more indent than .ajax, and 

`jQuery.blah = function (){
    $.ajax({
        url: 'blah.url'
    })
    .done(function(data) {
        // blah
    })
    .fail(function(data) {
		// blah
    });
}`

To be more readable, it makes sense that the closing brace/paren are on the same indentation as the opening... VS Code thinks they need to be further indented for some reason, making it look like something is missing before tracing opening/closing characters.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2018-05-28 09:11
We're using the typescript formatter here. I verified that this behaves the same when in a standalone js file.

**Comment by mjbvz** [comment] 2018-06-20 21:41
Duplicate of https://github.com/Microsoft/TypeScript/issues/14586

**Closed by mjbvz** 2018-06-20 21:41 UTC
Labels: editor, editor-autoindent
