### ISSUE TITLE
Add support for subword navigation/editing

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#3526] opened 2016-02-27 17:25 UTC
I never encountered this feature outside vim. But then I used Sublime and then Atom, and found this awesome feature, and have been using it a lot recently. Can this be added to vscode?

Ref: https://github.com/atom/atom/pull/5806

**Comment by kumarharsh** [comment] 2016-04-06 21:23
Seems like #1085 does exactly this. Can we move ahead in polishing that PR so that it can be added to  code soon?

**Comment by Krzysztof-Cieslak** [comment] 2016-09-25 21:12
Feature provided by: https://marketplace.visualstudio.com/items?itemName=ow.vscode-subword-navigation

**Comment by kumarharsh** [comment] 2016-09-26 18:37
It's there, but there are a few things I think it can't do, such as within the filename while renaming/creating new files from the sidebar, or when writing the git commit message, etc.

**Comment by timmccall-wf** [comment] 2017-03-01 21:30
The plugin mentioned above also does not allow subword navigation with multiple cursors which drives me absolutely bonkers.

**Comment by mccalltd** [comment] 2017-03-01 22:04
The plugin mentioned above also does not allow subword navigation with multiple cursors. Oh the little things that would mean so much.... 

I looked at the PR mentioned above, the one without tests. @alexandrudima Is there any interest in getting that old PR up to snuff and into master? I'd be happy to help move it forward if so.

**Comment by astoilkov** [comment] 2017-07-02 07:09
The first time I encountered this feature was in Atom. I first thought "Hmm. Interesting but it seems like an overhead" but after I experimented with using it it became obvious that it is super useful feature. It would be awesome if it gets implemented.

**Comment by V-ed** [comment] 2018-07-03 17:43
This feature has been added by the PR #48023 and will be available in the `1.25` release of VSCode ([proof](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_25.md#sub-word-support)).

@alexandrudima, This is one of the few duplicates for this feature request that has no recent movement. Shouldn't it be closed as duplicate of the oldest duplicate I can find, a.k.a. #541?

**Comment by alexandrudima** [comment] 2018-07-04 09:22
Here is an example for how you can bind the new commands:

```
{ "key": "ctrl+right",       "command": "cursorWordPartRight",
                                "when": "textInputFocus" },
{ "key": "ctrl+shift+right", "command": "cursorWordPartRightSelect",
                                "when": "textInputFocus" },
{ "key": "ctrl+left",        "command": "cursorWordPartStartLeft",
                                "when": "textInputFocus" },
{ "key": "ctrl+shift+left",  "command": "cursorWordPartStartLeftSelect",
                                "when": "textInputFocus" },
{ "key": "ctrl+backspace",   "command": "deleteWordPartLeft",
                                "when": "textInputFocus && !editorReadonly" },
{ "key": "ctrl+delete",      "command": "deleteWordPartRight",
                                "when": "textInputFocus && !editorReadonly" },
```

**Closed by alexandrudima** 2018-07-04 09:22 UTC
Labels: editor-commands, feature-request

**Comment by temurih** [comment] 2018-07-12 19:53
@alexandrudima, where to add these settings? I tried adding it to `USER SETTINGS`, but didn't work for me. Wouldn't it be great if there is a button in the release notes that will add the settings where ever they need to go!?

**Comment by kumarharsh** [comment] 2018-07-12 20:49
The are already there - search for "Keyboard Shortcuts" in Ctrl+P (or press Ctrl+K Ctrl+S)

**Comment by temurih** [comment] 2018-07-12 20:53
@kumarharsh, not on mine!

**Comment by kumarharsh** [comment] 2018-07-13 13:31
![image](https://user-images.githubusercontent.com/760112/42694169-150f2968-86cf-11e8-93fd-85d5788810ac.png)

Make sure you've upgraded to 1.25.0
