### ISSUE TITLE
, should not be trigger character in JSON

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#144904] opened 2022-03-11 11:55 UTC
Currently `,` is a trigger character in JSON. The problem is that when I want to press `,` and `enter` to get a newline, the intelli-sense appears and the first suggestion gets accepted (because of my enter). Leading to a bad user experience. Text gets inserted instead of a newline.

fyi @jrieken

![Screenshot 2022-03-11 at 12 54 24](https://user-images.githubusercontent.com/1926584/157862313-8595882c-6ba7-4178-82aa-2dbab077175f.png)

**Comment by aeschli** [comment] 2022-03-11 13:16
The JSON language server does not set 'comma' as a trigger character. Also, I can't reproduce this in a JSON file.

**Comment by isidorn** [comment] 2022-03-11 13:27
You are right. This does not reproduce always. Here is how I can reproduce with a fresh user data dir

Open our `vscode-distro` repository. Open this file https://github.com/microsoft/vscode-distro/blob/isidorn/update-extension-tips/quality/stable/product.json#L59
Delete the comma at the end, insert the comma -> see bug

**Comment by aeschli** [comment] 2022-03-14 09:32
shouldAutoTrigger looks if after typing a character the cursor is at the end of a word. If it is, it triggers quick suggest. 

In the JSON example `getWordAtPosition` returns a word, but it it shouldn't. The JSON word rule says a word can start with a `"` can contain any character except `"` (includes comma). The word ends with a new line or a second '"`

getWordAtPosition has an optimization to only look 15 characters before the current cursors. It thinks the current word is `",`.
If it had further, it would have seen that it's not in a word.

**Comment by aeschli** [comment] 2022-03-14 09:33
Created https://github.com/microsoft/vscode/issues/145019. Marking as dup.

**Closed by aeschli** 2022-03-14 09:33 UTC
Labels: needs more info, json

**Comment by isidorn** [comment] 2022-03-14 10:11
@aeschli thanks for the investigation.
