### ISSUE TITLE
Emmet:Remove Tag followed by undo creates unwanted closing tag

### ISSUE THREAD

**Issue by dph76** [Microsoft/vscode#56597] opened 2018-08-16 19:11 UTC
Issue Type: <b>Bug</b>

1. Create a html file with the following 3 lines of content:
<p>

</p>

2. Put cursor on line 1
3. Run the "emmet:remove tag" command
4. Press CTRL+Z

The result is:
<p></p>

</p>

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3998)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (9.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vetur|oct|0.12.6

(1 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment] 2018-08-16 23:25
Duplicate of #39545 with root cause being #34484

**Closed by ramya-rao-a** 2018-08-16 23:25 UTC
Labels: new release
