### ISSUE TITLE
Relative path in adapterExecutableCommand

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19315] opened 2017-01-25 00:38 UTC
Testing https://github.com/Microsoft/vscode/issues/19043

In package.json, the 'program' field for a debug adapter can be a relative path, but when returned from adapterExecutableCommand, it must be an absolute path. The error message for this is not obvious (just `"read ECONNRESET"`) so I think either a relative path should be resolved, or there should be a better error message, or it should be documented that the path must be absolute.

It's a little inconvenient to resolve it to an absolute path using the __dirname of some source file in your extension.

**Comment by isidorn** [comment] 2017-01-25 08:58
@weinand I can also look into this if needed so feel free to assign back :)

**Comment by weinand** [comment] 2017-01-25 11:30
For January I will just document that it must be absolute (and mark the feature experimental).
I will revisit this in February.

**Comment by weinand** [comment] 2017-12-04 14:21
This inconsistency will be eliminated when moving this API over to the debugConfigProvider.
duplicate of #33801

**Closed by weinand** 2017-12-04 14:21 UTC
Labels: debt, debug
