### ISSUE TITLE
No feedback when uninstalling an extension

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#67456] opened 2019-01-29 18:57 UTC
When uninstalling an extension by clicking the gear icon in the extension viewlet, the only feedback I get that the extension was removed is the disappearance of the gear icon. If the extension comes from the marketplace, it turns into an install button, but if it comes from a VSIX, nothing else happens.

**Comment by sandy081** [comment] 2019-01-29 21:57
Duplicate of #66931

**Closed** 2019-01-29 21:57 UTC
Labels: *duplicate
