### ISSUE TITLE
Programmatically resolve Webview View

### ISSUE THREAD

**Issue by jmiles17** [microsoft/vscode#152382] opened 2022-06-16 19:56 UTC
I have a view in the Panel area and I wish to trigger WebviewViewProvider.resolveWebviewView() without showing the view / the user opening the view. I understand that you can use vscode.commands.executeCommand("myView.focus"), which would then open the view and trigger the above function. I also tried executing the command "workbench.view.extension.myview", and that seemed to have the same action. Instead, I want to activate the view such that the provider takes ownership of it (using resolveWebviewView), but the view remains hidden. Is this possible?

**Comment by mjbvz** [comment] 2022-09-21 23:42
Duplicate of #146330

**Closed by mjbvz** 2022-09-21 23:42 UTC
Labels: webview, api-proposal, webview-views
