### ISSUE TITLE
Typescript workspace problems not being detected

### ISSUE THREAD

**Issue by rbingham** [Microsoft/vscode#39454] opened 2017-12-02 05:31 UTC
VsCode will only report typescript problems when files with the problems are open even though there is a tsconfig.json file.

- VSCode Version: 1.18.1
- OS Version: Arch Linux 4.13.12-1 (Kernel version)

Steps to Reproduce:

1. Create typescript project with two typescript files: index.ts and test.ts
2. export class from test.ts
3. import class from test into index.ts and call non-existant method on the imported class. Error appears
4. close index.ts error disappears

tsconfig.json contents
```json
{
	"compilerOptions": {
			"target": "es6",
			"module": "commonjs",
			"sourceMap": true,
			"rootDir": "./"
	},
	"include": [
		"**/*.ts"
	]
}
``` 

test1.ts contents
```typescript
export class test {
    public static test123(): number {
        console.log('Hello World');
        return 0;
    }
}
```

index.ts contents
```typescript
import { test } from "./test";

test.main();
```

Reproduces without extensions: Yes

![typescript_error](https://user-images.githubusercontent.com/7032804/33512145-1380c2e8-d6e7-11e7-9c38-50df768a54c7.gif)
In the gif, the tsconfig.json has the 'files' option, but I can confirm that it is still happening when using the 'include' option

**Comment by mjbvz** [comment] 2017-12-04 19:50
duplicate of #13953

**Closed by mjbvz** 2017-12-04 19:50 UTC
Labels: typescript
