### ISSUE TITLE
Problems area freeze on update of diagnostics

### ISSUE THREAD

**Issue by mkloar** [microsoft/vscode#135941] opened 2021-10-27 10:03 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.60.0
- OS Version: Windows_NT x64 10.0.0.19041

We're developing a **custom** extension (not part of vscode marketplace), where we're reading workspace files and we're producing a diagnostic collection for some files (one file can have multiple diagnostics). We have a case where we're reporting a huge number of diagnostics (around 1200-1500). We also have a file watcher and on the 'update' event we're updating the diagnostic collection. The problem is that when we try to update diagnostic collection to 1200, then the 'Problems' area will **freeze** for like 2 or 3 seconds.

**Steps to Reproduce:**

1. Open vscode with our custom extension
2. Extension will produce a huge number of diagnostic collection (in problems area will be number between 1000 and 1500)
3. After the custom extension will update the collection with 1200 entries, then the 'Problems' area will freeze for 2-3 seconds.

**How we're updating diagnostic collection:**

```
// Get all diagnostics
const allDiagnostics: Map<vscode.Uri, vscode.Diagnostic[]> = ...;

// Update diagnostic on change event (filewatcher)
VsCodeManager.updateDiagnosticCollection(allDiagnostics);

....

// Some class that we have for vscode management
export class VsCodeManager {
    private static _context: vscode.ExtensionContext;
    private static _mainOutputChannel: vscode.OutputChannel;
    private static _diagnosticCollection: vscode.DiagnosticCollection;
    
    ...
     public static updateDiagnosticCollection(
        newDiagnosticCollection: Map<vscode.Uri, vscode.Diagnostic[]>
    ): void {
       this._diagnosticCollection.clear();

        // add newly created diagnostics
        for (const [newUri, newDiagnostics] of newDiagnosticCollection) {
            this._diagnosticCollection.set(newUri, newDiagnostics);
        }
   }
 ```

**Comment by sandy081** [comment] 2021-11-03 17:17
@mkloar Thanks for the profile. It looks like you are updating diagnostics of many resources at a time.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/10746682/140133961-fe720829-ae0a-4ed8-a20c-c2ed74092c64.png">

It would be great if you can provide a sample to reproduce it?

**Comment by sandy081** [comment] 2021-11-03 18:20
I can repro this with following sample

```ts
const diagnostics = vscode.languages.createDiagnosticCollection();
	vscode.commands.registerCommand('testExtension.helloWorld', async (arg) => {
		for (let i = 1; i <= 2000; i++) {
			diagnostics.set(vscode.Uri.file(`users/sandy081/work/vscode/${i}.json`), [
				new vscode.Diagnostic(new vscode.Range(new vscode.Position(1, 2), new vscode.Position(1, 2)), 'hello world 1'),
				new vscode.Diagnostic(new vscode.Range(new vscode.Position(2, 2), new vscode.Position(2, 2)), 'hello world 2'),
				new vscode.Diagnostic(new vscode.Range(new vscode.Position(3, 2), new vscode.Position(3, 2)), 'hello world 3'),
				new vscode.Diagnostic(new vscode.Range(new vscode.Position(4, 2), new vscode.Position(4, 2)), 'hello world 4'),
			])
		}
	});
```

**Comment by sandy081** [comment] 2021-11-03 18:54
Using `diffIdentityProvider` while updating the tree improves the performance, but only from the 3rd time calling the command. Editor still freezes when calling the command for the second time.

@joaomoreno can you please help me in understanding why updating the tree second time is not performant? To give more information:

- Running command for the first time, tree is reset completely:
https://github.com/microsoft/vscode/blob/fab12653546d5372447a941f70b9369e51ab29f8/src/vs/workbench/contrib/markers/browser/markersView.ts#L331-L333

- Running the command from thereafter, tree is updated:
https://github.com/microsoft/vscode/blob/fab12653546d5372447a941f70b9369e51ab29f8/src/vs/workbench/contrib/markers/browser/markersView.ts#L275-L277

**Comment by mkloar** [comment] 2021-11-04 08:22
> I can repro this with following sample
> 
> * Create an extension with following sample - creates large number of diagnostics when running hello world command
> 
> ```ts
> const diagnostics = vscode.languages.createDiagnosticCollection();
> 	vscode.commands.registerCommand('testExtension.helloWorld', async (arg) => {
> 		for (let i = 1; i <= 2000; i++) {
> 			diagnostics.set(vscode.Uri.file(`users/sandy081/work/vscode/${i}.json`), [
> 				new vscode.Diagnostic(new vscode.Range(new vscode.Position(1, 2), new vscode.Position(1, 2)), 'hello world 1'),
> 				new vscode.Diagnostic(new vscode.Range(new vscode.Position(2, 2), new vscode.Position(2, 2)), 'hello world 2'),
> 				new vscode.Diagnostic(new vscode.Range(new vscode.Position(3, 2), new vscode.Position(3, 2)), 'hello world 3'),
> 				new vscode.Diagnostic(new vscode.Range(new vscode.Position(4, 2), new vscode.Position(4, 2)), 'hello world 4'),
> 			])
> 		}
> 	});
> ```
> 
> * Open VS Code with above extension and open problems view
> * Run the command - Problems are updated. Good.
> * Run the command again - Editor freezes

Yeah, I wanted to paste a similar case as yours.

**Comment by joaomoreno** [comment] 2021-11-04 09:18
@connor4312 Can you take a look?

**Comment by connor4312** [comment] 2021-11-04 16:30
> it breaks updating the tree when the view is not visible

Are there repro steps for this? It seems to work for me with the identity provider always.

That may be your issue. We cache the last diff IDs for the children of any parent. This can only be done when a diffIdentityProvider is present. Thus only the second sequential call when a diffIdentityProvider is present will experience any optimization.

**Comment by sandy081** [comment] 2021-11-09 07:58
> Are there repro steps for this? 

yes, please follow these steps:

1. Add following identity provider at this line - https://github.com/microsoft/vscode/blob/b389529e97d7f5d6893dc15b73f4f42dd3a4a185/src/vs/workbench/contrib/markers/browser/markersView.ts#L330

```ts
diffIdentityProvider: {
									getId(element: MarkerElement): string { return element.id; }
								}
```
2. Run VS Code from sources
3. Open a CSS file and create an empty rule - make sure problems view show a warning
4. Close the problems view
5. Open settings editor and update `css.lint.emptyRules` setting value to `error`
6. Open problems view - warning does not change to error

However, this is not the main issue. Irrespective of passing `diffIdentityProvider` in the above code or not, tree is having perf issues when updating the children. Here are the steps to repro that:

- Create an extension with following sample - creates large number of diagnostics when running hello world command

```ts
const diagnostics = vscode.languages.createDiagnosticCollection();
	vscode.commands.registerCommand('testExtension.helloWorld', async (arg) => {
		for (let i = 1; i <= 2000; i++) {
			diagnostics.set(vscode.Uri.file(`users/sandy081/work/vscode/${i}.json`), [
				new vscode.Diagnostic(new vscode.Range(new vscode.Position(1, 2), new vscode.Position(1, 2)), 'hello world 1'),
				new vscode.Diagnostic(new vscode.Range(new vscode.Position(2, 2), new vscode.Position(2, 2)), 'hello world 2'),
				new vscode.Diagnostic(new vscode.Range(new vscode.Position(3, 2), new vscode.Position(3, 2)), 'hello world 3'),
				new vscode.Diagnostic(new vscode.Range(new vscode.Position(4, 2), new vscode.Position(4, 2)), 'hello world 4'),
			])
		}
	});
```

- Open VS Code with above extension and open problems view
- Run the command - Problems are updated. Good.
- Run the command again - Editor freezes

Note that, freeze does not happen if you run the above command again. It seems to happen only when second time.

**Comment by mkloar** [comment] 2021-11-30 10:16
Any update on this?

With the new version of the VScode (1.62.3), we're getting this error:

![image](https://user-images.githubusercontent.com/17946736/144028700-06bfd4e2-4918-4816-99cb-69730720107a.png)

**Comment by sandy081** [comment] 2021-11-30 11:48
@connor4312 Can you please try these steps - https://github.com/microsoft/vscode/issues/135941#issuecomment-963899082

**Comment by connor4312** [comment] 2021-12-17 19:07
> warning does not change to error

This is because the ID of the element doesn't change, so it will not be rerendered. Some ways you could deal with this:

- If settings change, rerender without using the diffIndentityProvider
- More optimal -- have the ID be generated to include all data that is used in the render, so if the problem level changes then the element gets a new ID. Note that with improvements made a month or two ago, it's fine to have the element instance change its ID (you used to have to replace the instance.)

> tree is having perf issues when updating the children

Not sure why I was having trouble repo'ing this earlier. Fixed in the linked comment.

**Closed** 2021-12-17 19:08 UTC
Labels: freeze-slow-crash-leak, error-list, perf
