### ISSUE TITLE
Custom Marketplace URL

### ISSUE THREAD

**Issue by jodyford** [microsoft/vscode#86164] opened 2019-12-03 20:28 UTC
I use VS Code on a disconnected corporate network.  We have an internal site with VS extensions.  But, being able to customize the URL for the Marketplace in VS Code would improve the usability of this IDE on my network and improve the search-ability of extensions on our network.

Thanks,

Jody

**Comment by AwesomeCookieButter** [comment] 2020-07-22 17:14
I have the same use case.  This might be a duplicate of https://github.com/microsoft/vscode/issues/21839 but at least this issue is assigned.

**Comment by Spriithy** [comment] 2020-10-28 08:42
Same issue here.

**Closed** 2020-11-05 08:20 UTC
Labels: extensions
