### ISSUE TITLE
When changing the name of a variable the summary presented by the orca is not consistent with the result of the operation.

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#130137] opened 2021-08-04 19:36 UTC
Issue Type: <b>Bug</b>

1. Launch orca and  open a java script file using vscode.
1. Inside the file opened declare one variable named p1.
1. After create the variable insert in the last line of the file the following:
var p2 = p1 + p1 + p1 +p1;
1. Rename the variable p1 to p1x.

The orca announces the amount of changes made as well as the amount of files changed.

The problem is that at least in my environment, the number of files and the number of changes announced by orca is the same, although I only have one file.
In my test I receive the following:
"Successfully renamed 'p1' to 'p1x'. Summary: Made 4 text edits in 4 files"

VS Code version: Code - Insiders 1.59.0-insider (cead2f699cd0afb2464d8d3ad975776051583b4f, 2021-08-03T15:33:41.082Z)
OS version: Linux x64 5.13.7-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2365)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.68GB (0.78GB free)|
|Process Argv|-n --crash-reporter-id bcecf5e0-97d1-4830-b28c-0943c4adab1c|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.13.0
shell-format|fox|7.1.0
rest-client|hum|0.24.5
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
vscode-aks-tools|ms-|0.0.9
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
azure-account|ms-|0.9.8
powershell|ms-|2021.6.2
vsliveshare|ms-|1.0.4650
vsliveshare-audio|ms-|0.1.91
oracledevtools|Ora|19.3.4
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.26.0
vscode-manifest-yaml|Piv|1.26.0
vscode-spring-boot|Piv|1.26.0
fabric8-analytics|red|0.3.3
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
vscode-yaml|red|0.22.0
sonarlint-vscode|Son|2.0.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.2
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.32.1
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
00j7a122:30294756
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt:30346833
dockerwalkthrucf:30346919

```

</details>

**Comment by jvesouza** [comment] 2021-08-04 19:47
ping @isidorn

**Comment by isidorn** [comment] 2021-08-05 07:46
@jvesouza thanks for creating this issue. I can reproduce it.
It seems like the ariaSummary computed here is wrong https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/bulkEdit/browser/bulkEditService.ts#L48

The problem is that `resourceEdits` are not de-duped based on resource. So if there are 5 resource edits in the same file it says "5 files" instead of "one file".
For now assigning to @jrieken and feel free to unassign yourself and I can also fix this. Though it would require some casting I think...

**Closed** 2021-09-27 13:39 UTC
Labels: bug, accessibility, workspace-edit, rename

**Comment by jvesouza** [comment] 2021-09-28 08:49
I did some tests here and the problem was really fixed, thank you very much.
