### ISSUE TITLE
Search Editor focus is lost after navigating with Ctrl+Tab

### ISSUE THREAD

**Issue by stepanhakobyan** [microsoft/vscode#92634] opened 2020-03-13 09:03 UTC
Issue Type: <b>Bug</b>

Hi, 
First. I love the new search editor.

Now to the point.
When I
1. search something in the search editor,
2. move to search results (Ctrl+Down Key),
3. move to some other file (F12 to go to definition or Ctrl+Tab)
4. then return back with Ctrl+Tab
it focuses in the search box and not on the results (that way I left in 3rd step)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by JacksonKearl** [comment] 2020-03-25 02:34
Hey I'm not able to reproduce this across macOS or Windows, for me the focus stays where it was. Do you similarly lose focus when you open the command pallet, switch between windows, or reload the window?

**Comment by stepanhakobyan** [comment] 2020-03-25 03:17
Hi @JacksonKearl ,
Here are the steps (with corrected 3-rd step)

1. search something in the search editor,
2. move to search results (Ctrl+Down Key),
3. move to some other open file with Ctrl+Tab,
4. then return back with Ctrl+Tab.

**Comment by JacksonKearl** [comment] 2020-03-25 04:03
Ah, now I can reproduce in Stable, but this is fixed in Insiders.

**Closed by JacksonKearl** 2020-03-25 04:03 UTC
Labels: bug, needs more info, search-editor
