### ISSUE TITLE
SCM: Support input box spell checking

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#35571] opened 2017-10-04 11:52 UTC
For longer commit messages it would be great to have a spell checker there. Ideally, VSCode would provide that out of the box but if the direction is to leave spell checking up to extensions (and there are already some great ones out there, like [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) by @bartosz-antosik), there could be an API for that.

Possibly related: Offline spell checker for VSCode #20266

**UPDATE**: since 2020, Electron supports spell checking natively, see [below](https://github.com/microsoft/vscode/issues/35571#issuecomment-584672653).

**Comment by joaomoreno** [comment] 2017-10-05 07:46
This could be interesting: https://github.com/electron-userland/electron-spellchecker

**Comment by rmnegatives** [comment] 2017-10-06 03:09
I would love to give this a go. The electron-spellchecker seems like a potential solution.

**Comment by einsiol** [comment] 2018-04-12 09:43
This would be a very valuable feature, there is nothing worse than creating a spelling mistake in a commit and discovering many commits later.

**Comment by skprabhanjan** [comment] 2018-09-17 12:02
@joaomoreno , Working on this and using https://github.com/electron-userland/electron-spellchecker as suggested.

**Comment by joaomoreno** [comment] 2018-09-24 09:18
Is that module special? Does it need to run in Electron itself? Note that extensions do not run in Electron, but in an extension host.

**Comment by skprabhanjan** [comment] 2018-09-24 12:04
@joaomoreno , I got the point that extensions run in extensions host, is there any way to install and use this module there ?
I also think that "electron-spellchecker" derives some information from electron (https://electron-userland.github.io/electron-spellchecker/docs/class/src/context-menu-builder.js~ContextMenuBuilder.html) as described here.
Also is there any external module used in any extension so that I can refer something from that ?
Thanks :)

**Comment by joaomoreno** [comment] 2018-09-25 09:01
> I also think that "electron-spellchecker" derives some information from electron (https://electron-userland.github.io/electron-spellchecker/docs/class/src/context-menu-builder.js~ContextMenuBuilder.html) as described here.

That's a very good indication that this will not work. I suggest to pick another issue to work on. :+1: 

I'll remove the `help wanted` label since this is not trivial and we're not sure how to proceed here.

**Comment by bartosz-antosik** [comment] 2018-09-25 09:08
@joaomoreno Could you maybe provide some "on changed" callback API call with the content of the edit box which e.g. a spell checking extension (like [Spell Right](https://github.com/bartosz-antosik/vscode-spellright) of mine) could service? And another "diagnostics" type to provide suggestions?

**Comment by borekb** [comment] 2018-09-25 09:09
That would be awesome, I use Spell Right all the time.

**Comment by skprabhanjan** [comment] 2018-09-25 09:45
@joaomoreno , There is already a validateInput function that validates the input in many ways( e.g commitMessageWhitespacesOnlyWarning in https://github.com/Microsoft/vscode/blob/master/extensions/git/src/repository.ts#L658 ) .
As @bartosz-antosik suggested, is it possible to use Spell Right in validateInput?
I can look at this approach if you suggest me to go ahead :)
Thanks.

**Comment by joaomoreno** [comment] 2018-09-25 09:46
@skprabhanjan I was about to suggest we try that. Git now exposes a rich API. We could open that API to let extensions register additional input validators.

**Comment by skprabhanjan** [comment] 2018-09-25 10:00
@joaomoreno , I will try with that but I have a small doubt,
Are you suggesting me to use any Git API's that are exposed(which still needs to be researched) or something like Spell Right?

**Comment by joaomoreno** [comment] 2018-09-25 10:02
We need to expose new Git extension API: one which lets other extensions register input validators.

**Comment by skprabhanjan** [comment] 2018-09-25 10:05
@joaomoreno , Okay I will look into how to achieve that.
I will contact you in case of any queries.
Also an example of how to expose a new API would help me go in the rite direction.
Thanks for the help:)

**Comment by bartosz-antosik** [comment] 2018-09-25 10:10
@joaomoreno But it seems half way though: There needs to be some way to correct spelling (underline, right click menu etc.)

**Comment by sreejith-ms** [comment] 2019-01-28 12:37
Any updates?

**Comment by ntrepid8** [comment] 2019-02-04 17:09
Is there any way to open a new editor tab the way Sublime Text does and use that for the commit message?

**Comment by timbrown5** [comment] 2019-02-06 11:53
As a workaround you can open a new file, paste/write the commit message in there and copy it back into the commit afterwords.

**Comment by dko-slapdash** [comment] 2019-06-09 07:00
Even underlining a spelling error with red would do the trick for 99% of cases. Like in the browser's <input> field - the browser underlines the errors natively; maybe it can be just enabled in VSCode's text field too?

I see in VSCode's developer tools that this commit message is currently represented as a textarea:
```
<textarea class="input" autocorrect="off" autocapitalize="off"
spellcheck="false" placeholder="Message (press ⌘Enter to commit)"
title="Message (press ⌘Enter to commit)"
style="background-color: rgb(60, 60, 60); color: rgb(204, 204, 204); height: 26px;"></textarea>
```

**Comment by ssbarnea** [comment] 2019-07-29 08:45
Any chances to make Git Commit Message editing to use the spellchecker?

**Comment by golavr** [comment] 2020-02-01 00:17
why very basic feature request spread across years?

**Comment by elcste** [comment] 2020-02-11 14:51
[Electron 8](https://github.com/electron/electron/releases/tag/v8.0.0) includes support for the [built-in Chromium spellchecker](https://github.com/electron/electron/pull/20897). Maybe now this feature would be easier?

**Comment by heaths** [comment] 2020-06-11 16:31
I would also like to see this in the github.vscode-pull-request-github extension as well. Microsoft [just improved](https://www.theverge.com/2020/5/28/21273934/microsoft-google-chrome-edge-chromium-spellcheck-improvements) the spell checker in Chrome recently as well.

**Comment by mrhut10** [comment] 2021-03-31 00:24
I too would love this feature, can't bare to think how many of my commit messages have terrible spelling in them., please keep me updated and if anyway I can help with this feature

**Comment by kaalam** [comment] 2021-04-01 09:20
Looking forward to it too.

**Comment by krutoo** [comment] 2021-04-03 07:38
Most expected feature for me

**Comment by sans238** [comment] 2021-05-26 13:54
When will this feature be available?

**Comment by JacquesBass** [comment] 2021-05-26 14:05
There's hope. The request is not closed yet (4 years open). Someone must read this.

**Comment by urenajose** [comment] 2021-06-15 20:37
Most expected feature for me 🤞

**Comment by Avivhdr** [comment] 2021-08-10 07:04
Looking forward to it too 🤞

**Comment by Shahaed** [comment] 2021-11-05 00:06
I would ask implementation of https://www.electronjs.org/docs/latest/tutorial/spellchecker be applied to all input boxes including the [vscode comment API](https://code.visualstudio.com/api/references/vscode-api#CommentController). 

This would be a great quality of life improvement for people that want to center their workflow on vscode, especially for users using the built-in source code tool and writing descriptive commit messages or the GitHub pull request extension (which uses the comment API) and reviews a lot of code. It would also resolve this [issue](https://github.com/microsoft/vscode-pull-request-github/issues/1487).

Hopefully, this change can be given priority!

**Comment by werame** [comment] 2022-01-09 00:15
> Is there any way to open a new editor tab the way Sublime Text does and use that for the commit message?

Actually there's at least one extension (["Commit Message Editor"](https://marketplace.visualstudio.com/items?itemName=adam-bender.commit-message-editor)) that does that, meaning opens the commit message in a separate, larger box, CME doesn't seem allow/support any spelling either. at least not wit [cSpell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). Or at least I haven't figured out how to configure cSpell for CME's buffers.

**Comment by mrrau** [comment] 2022-01-28 11:17
Looking forward to it 🚀

**Comment by alexkautz2** [comment] 2022-02-19 00:46
This feature would really help with accessibility.
I have a disability that makes spelling words hard, and adding spellchecking to the commit box would help accommodate me.

**Comment by Talia-K-Loos** [comment] 2022-03-18 18:41
+1

I came here to suggest this and found it already suggested.

Also would like to see this enabled for the "git commit" file language type, markdown type, and text type -- dictionary selectable.

**Comment by ssbarnea** [comment] 2022-03-19 07:42
I find the title bit misleading because the major problem is the design flaw that assumed that a commit message needs an input box instead of a full blown editor tab/window. Lack of spellchecking is a side effect, one of many.

That is why I so never do commits from vscode UI, i use command line finely tuned to open commit message in vscode.

**Comment by Talia-K-Loos** [comment] 2022-03-24 21:55
> I find the title bit misleading because the major problem is the design flaw that assumed that a commit message needs an input box instead of a full blown editor tab/window. Lack of spellchecking is a side effect, one of many.
> 
> That is why I so never do commits from vscode UI, i use command line finely tuned to open commit message in vscode.

Nah, the title is exactly what it is. It's gonna be a text field with a lot of text for some folks, and very little text for others. While I completely agree that best practice for commit messages makes that tiny little text box a very, _very_ strange choice, your process isn't my process isn't someone else's and we all deserve a spell checker to have our back.

Me, while I like the _idea_ of how you've set up your workflow, it also wouldn't work well for me in practice. I prefer to stick to a GUI when using a GUI app, and stick to a CLI when using a CLI-app. I already pay enough in mental context switching cost as it is, adding more frequent context switches for me would be a headache. Instead, I just tell VSC to pop open a blank file and tell it that the language is a commit message, copy and paste into that box, no command line. Probably the only thing I'm going to do differently in the long run is bind the first and last parts of this process to two key chords -- one for creating the buffer and designating it as a commit message buffer, and a second for copying it, pasting that in the oddly mail-slot-sized box that was allotted for a commit message, making the commit, and destroying the buffer window. In other words, make it work like we kinda feel it should work, even if it's a bit of a weird work-around of a way.

But for those folks who are going to either compose their commit message right there (a lot like those folks who use -m on the command line, either always or selectively) they deserve spell checking just as much as you or I do.

**Comment by vanowm** [comment] 2022-04-06 00:23
4.5 years later still waiting.

What' wrong with a regular `textarea`, why can't it be used instead?

**Comment by dapptain** [comment] 2022-06-15 15:06
Desperately needed.

**Comment by talregev** [comment] 2022-06-25 08:39
+1 do make it happen

**Comment by lszomoru** [comment] 2022-06-27 09:38
In the latest Insiders release (2022-06-27), if you click on the commit button without a commit message, a full editor will open that can be used as an input for the commit message. This has the side effect that any spellchecker extensions will work in the commit message editor as well. 

Next milestone, I will also look into the possibility of leveraging the built-in spellchecker or exposing the document behind the SCM Input so that spellchecker extensions can get access to the document, and provide markers for words that are mistyped.

**Comment by borekb** [comment] 2022-07-08 17:14
@lszomoru I've just tried in VSCode 1.69 and it's awesome!

<img width="1271" alt="Screen Shot 2022-07-08 at 19 07 59" src="https://user-images.githubusercontent.com/101152/178039258-4184c53e-4d71-4482-838e-f8fb03ab7b41.png">

(This is the new feature in combination with [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) by @bartosz-antosik.)

If you can get the spell checker working in the sidebar, that would be even better but this is already great news! Thanks for your work on this.

**Comment by mfulton26** [comment] 2022-07-08 18:45
I can confirm that spell checking works in the new commit message editor flow with [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) too

**Comment by lszomoru** [comment] 2022-07-08 19:11
Glad to hear that things are working as expected. Most of the credit goes to @JohnnyCrazy who contributed the new flow to use the full text editor as the commit message editor. In July I will take a look to see if there is a way to expose the document of the SCM input box to extensions to enable spell checking there as well. I will keep this issue updated with my progress.

**Comment by mfulton26** [comment] 2022-07-08 19:17
If anyone else here wants to see Markdown preview support for the new commit message using an editor feature then please upvote https://github.com/microsoft/vscode/issues/154392. Thanks!

**Comment by urenajose** [comment] 2022-07-09 00:21
> In the latest Insiders release (2022-06-27), if you click on the commit button without a commit message, a full editor will open that can be used as an input for the commit message. This has the side effect that any spellchecker extensions will work in the commit message editor as well.
> 
> Next milestone, I will also look into the possibility of leveraging the built-in spellchecker or exposing the document behind the SCM Input so that spellchecker extensions can get access to the document, and provide markers for words that are mistyped.

I tried to click commit button without a commit message but I get a Bad status code 500 error, is there a setting which I need to enable first?
![image](https://user-images.githubusercontent.com/65747456/178084246-33f6d146-9ca0-455c-974e-df25ae966c5d.png)

![image](https://user-images.githubusercontent.com/65747456/178084296-2891bc0f-1ab4-468f-9518-8a1aa9d80b17.png)

**Comment by lszomoru** [comment] 2022-07-09 07:35
@urenajose, you are hitting an issue that is currently being tracked as https://github.com/microsoft/vscode/issues/154449

**Comment by talregev** [comment] 2022-07-09 09:51
> @lszomoru, I tried to click commit button without a commit message but I get a Bad status code 500 error, is there a setting which I need to enable first?

Probably you didn't set user name and password for git. 
You can check on output of vscode (when you open terminal, check the output tab (different tab))
Then you will see the error msg.

**Comment by lszomoru** [comment] 2022-07-14 16:30
After talking to the team today, as it turns out, extensions already have access to the text document that is associated with the SCM input field which enables extension authors to implement spell check for the SCM input field. The text document is in the `workspace.textDocuments` array, and the `workspace.onDidChangeTextDocument` event fires when the text document changes. The text document has the `vscode` scheme and `scminput` languageId. 

Today I have submitted [a pull request](https://github.com/bartosz-antosik/vscode-spellright/pull/518) to the Spell Right extension, and next I will be looking at the Code Spell Checker extension and will probably reach out to the extension author either with a pull request or with the exact steps that they need to make to their extension.

As soon as diagnostic information is emitted to the text document that is associated with the SCM input field, there are some "papercuts" that I need to address in the "Problems View": 1) the file name associated with the problem should have the repository name, 2) clicking on a problem should focus the SCM input field.

**Comment by lszomoru** [comment] 2022-07-15 12:33
I have also submitted [a pull request](https://github.com/streetsidesoftware/vscode-spell-checker/pull/2081) to the Code Spell Checker extension. The changes to that extension as minimal since all it has to do is remove `vscode` from the list of blocked schemes. As soon as that happens, spell checking for the SCM input can be enabled by tweaking the settings of the extension.

**Comment by lszomoru** [comment] 2022-07-18 17:07
The author of the Code Spell Checker extension published an update (`v2.3.1`) that contains my proposed changes so you can enable spell checking in the commit input box by adding `vscode` to the allowed schemas, and `scminput` to the enabled file types:

```json
  "cSpell.allowedSchemas": ["file", "gist", "sftp", "untitled", "vscode-notebook-cell", "vscode-userdata", "vscode"],
  "cSpell.enableFiletypes": ["scminput"],
```

**Comment by Jason3S** [comment] 2022-07-18 19:23
@lszomoru,

It is better to use:
> ```json
>   "cSpell.allowedSchemas": ["file", "gist", "sftp", "untitled", "vscode-notebook-cell", "vscode-userdata", "vscode"],
>   "cSpell.enableFiletypes": ["scminput"],
> ```

![image](https://user-images.githubusercontent.com/3740137/179600218-7afae4f1-b973-49fb-a076-de0137d92b25.png)

Because of limitations in the way VS Code merges settings, lists are overwritten instead of merged. So, setting `enabledLanguageIds` will disable all other file types.

**Comment by lszomoru** [comment] 2022-07-26 09:09
Today's Insiders release (2022-070-26) contains a change so that we adopt a dedicated scheme, `vscode-scm` for the text document associated with the commit input. This enables extension authors to easily identify such documents. In case you are using the Code Spell Checker extension please update your user settings to:

```json
  "cSpell.allowedSchemas": ["file", "gist", "sftp", "untitled", "vscode-notebook-cell", "vscode-userdata", "vscode-scm"],
  "cSpell.enableFiletypes": ["scminput"],
```

@Jason3S, with this change, you can add the `vscode` scheme back to the blocked list and add the `vscode-scm` scheme to the default list of schemes that are being processed. I have also pushed a commit so that problem markers for documents using the `vscode-scm` scheme will not appear in the problems view.

**Closed** 2022-07-26 09:19 UTC
Labels: feature-request, scm

**Comment by Jason3S** [comment] 2022-07-26 15:58
@lszomoru, I'll update the extension.
