### ISSUE TITLE
`openNotebookDocument` should not hang when no content provider is registered

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#133339] opened 2021-09-17 17:12 UTC
I discovered this is `window.test.ts`

1. Execute `openNotebookDocument` using a `.vsctestnb` URI
2. Await the promise
3. 🐛 The promise will never resolve because the content provider is not registered.

Expected:
The promise shouldn't hang, but instead should reject.

**Comment by jrieken** [comment] 2021-09-21 09:23
@lramos15 Is this a problem specific to the test extension and its provider?

**Comment by lramos15** [comment] 2021-09-21 12:37
I don't think so. I think it's a problem when the `package.json` defines a notebook but there is no content provider available due to it not being registered in the code.

**Comment by jrieken** [comment] 2021-09-21 12:55
So, it is a problem specific to the extension, right? The problem is that we need to wait for the extension to register the content provider and it's hard to say what a good timeout would be

**Comment by lramos15** [comment] 2021-09-21 13:28
> So, it is a problem specific to the extension, right? The problem is that we need to wait for the extension to register the content provider and it's hard to say what a good timeout would be

Right the problem is we wait forever right now, or at least a very long time. This leads to what seems like a promise which never resolves or rejects.

**Comment by jrieken** [comment] 2021-09-24 12:54
Given this is an extension issue and given this is a testing extension (not productive) for a very narrow use-case I opt'ing for a won't fix here

**Closed by jrieken** 2021-09-24 12:54 UTC
