### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by MThomadakis** [microsoft/vscode#232185] opened 2024-10-24 18:54 UTC
Type: <b>Bug</b>

Images in html are broken.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13620H (16 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (7.12GB free)|
|Process Argv|--crash-reporter-id 8748a189-9f69-4977-9396-e69260a7a748|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
composer-php-vscode|DEV|1.52.16226
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.52.16226
profiler-php-vscode|DEV|1.52.16226
html-preview-vscode|geo|0.2.5
vscode-latex|mat|1.3.0
latex-previewer|mjp|0.9.9
debugpy|ms-|2024.12.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.10.1
LiveServer|rit|5.7.9
latex-viewer|Sap|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1cf:31157160
controlgs:31153265
5fd0e150:31155592

```

</details>

**Comment by IllusionMH** [comment] 2024-10-24 23:17
/needsMoreInfo

Please specify how it's related to VS Code editor itself with  steps to reproduce and code samples.

**Comment by jd-apprentice** [comment] 2024-10-28 23:44
https://www.w3schools.com/html/html_images.asp

**Comment by aeschli** [comment] 2024-12-09 20:20
Closing due to lack of reproducible steps.

**Closed by aeschli** 2024-12-09 20:20 UTC
Labels: info-needed
