### ISSUE TITLE
Disk name in ${workspaceRoot} is lowercase may result in a bug related to node6, webpack and babel

### ISSUE THREAD

**Issue by unhealthy** [Microsoft/vscode#6348] opened 2016-05-13 12:56 UTC
- VSCode Version: v1.1
- OS Version: windows 10
- nodejs Version: v6

Steps to Reproduce:
( a little bit complicate)
1. mkdir try-bugs && cd try-bugs 
2.npm install -g vue-cli
2.vue init webpack
3.npm install
4.set up a task in task.json, whose command is `npm`, args is `["run", "build"]`
5. press `contrl + shift + b` to build the project
6.then babel of webpack does not work in the right way
![image](https://cloud.githubusercontent.com/assets/3315274/15247779/e2c30e2a-1948-11e6-85ef-065a9c4bb524.png)

Further description and guess:
I have install a extension of vscode called [new-cmd ](https://marketplace.visualstudio.com/items?itemName=odonno.new-cmd), which can enable you to open a new terminal from current work space directory by typing command `cmd` after pressing `f1` in vscode.
If I open a terminal using this extension and then run `npm run build` in this terminal, it will show me the same bug as run the build task from vscode.
![image](https://cloud.githubusercontent.com/assets/3315274/15247757/cc4b29d4-1948-11e6-98da-07de74a8b956.png)

However, if I open a terminal manually by right click and run the same command, everything goes well.
![image](https://cloud.githubusercontent.com/assets/3315274/15247842/53734e96-1949-11e6-9f70-fee948c954c0.png)

I notice that there is one difference between the two terminal is that the disk name. The disk name in former terminal is `d:\` while the later one is `D:\`. 
In the project, from one hand, there are some code, the config of webpack specifically, related to `path.join(__dirname, ...)`, which will generate an absolute path to files begin with `D:\`. From the other hand, there are some other code use relative path to locate file, which will result in path to file begin with `d:\`.
I wonder whether this caused my problem or not.
By the way, if I repeat the process with node5, the bug disappear.

**Comment by weinand** [comment] 2016-05-22 10:25
@unhealthy in node v6 the case of drive letters has changed.
This is a duplicate of https://github.com/Microsoft/vscode/issues/6530

**Closed by weinand** 2016-05-22 10:25 UTC
