### ISSUE TITLE
extension activate triggering mechanism  if all views are collapsed

### ISSUE THREAD

**Issue by cjlapao** [microsoft/vscode#227948] opened 2024-09-09 09:15 UTC
We have an extension that contains a rather complex activation method, we provide several views and due to the licensing system on our product not all views are accessible to every one, the activating takes this into account and rather than going through everything at startup we want to initialize the extension when the user clicks in the icon in the activity bar. This used to work or at least we never had reports of users not seeing this issue.

The issue is apparent if the user collapses all the views like this
![image](https://github.com/user-attachments/assets/8edbbec9-0132-43ce-a71d-52f3828b553f)
In this case, the extension activation method is never triggered, and the extra panels are never shown; in this case, what this user should see is this.
![image](https://github.com/user-attachments/assets/05b39ad0-ade4-4628-a398-e07009ffbe06)

Other users might have fewer views depending on the license.

We tried different methods, like adding a command to the activity bar
```json
        "viewsContainers": {
            "activitybar": [
                {
                    "id": "parallels-desktop",
                    "title": "Parallels Desktop",
                    "icon": "img/logo/parallels_logo.svg",
                    "command": "parallels-desktop.openView"
                }
            ]
        },
```

I also tried these activation events

```json
    "activationEvents": [
        "onViewContainer:parallels-desktop",
        "onCommand:parallels-desktop.openView"
    ],
```

And none of that helps. With the command, we can see the command in the command pallet, and if we trigger it, the extension does get activated, so what we need is a way to connect that button to be executed when a user clicks on the extension icon in the activity bar or when the container is displayed.

I might have missed an API somewhere, but I couldn't find a way to make it work.

tagging @isidorn for visibility

**Comment by isidorn** [comment] 2024-09-09 09:46
@alexr00 could you help our friends from Parallels?

**Comment by alexr00** [comment] 2024-09-11 14:25
@cjlapao we don't have a `onViewContainer` activation event, and since all your views are collapsed, you won't get activated by an `onView` event either. Are there any other activation events that would suit your needs: https://github.com/Microsoft/vscode-docs/blob/main/api/references/activation-events.md ? Ideally not `onStartupFinished` or `*` as they are very eager.

**Comment by alexr00** [comment] 2024-09-11 15:48
No, we have no plan to add an `onViewContainer` event at this time. 

Am I understanding the reason you want to activate when the view container correctly? You have some views, which are hidden by default because of some context values that they check for in the `when` clauses in package.json. During activation, you set those context values as appropriate based on their license status. The user entry point of the extension is through these views.

**Comment by cjlapao** [comment] 2024-09-12 05:50
Yes,

That is correct. If any of the views that are accessible to every user are collapsed, then the user will never see the views that he has access to, rendering the process useless for them. Also, it is not very user-friendly to tell them they need to expand a view to trigger the initialization process.

Is this triggers part of the open source of VSCode? we (mainly me) woundn't mind contributing and creating these triggers if that is ok with the vscode team and if it is part of the open-source code.

**Comment by alexr00** [comment] 2024-09-12 11:33
@sandy081 in case you have additional context on this. Do you think it makes sense to have a `onViewContainer` activation event? My concern is that we could have extensions activating too eagerly because the active view will be restored when VS Code is opened/reloaded. I think this shouldn't be a big problem though since any view that is restored is one that the user was actually using.

**Comment by sandy081** [comment] 2024-09-13 08:13
Please note that user can move views to any view container and extension should activate on any view container opened. It is almost same as early activation.

**Comment by cjlapao** [comment] 2024-09-13 09:40
@sandy081 These views will not be visible even if the user moves them somewhere else. They are not registered until the activation is executed, so even if they move them to another view container, they will disappear the next time the VSCode starts.

The only way we can change this is to be eager during activation and activate it for every user that has the extension installed, and that is just not what we want to happen. We are open to other solutions as long as we can activate it when something else besides an expanded view is expanded.

let me know what options would work here

**Comment by alexr00** [comment] 2024-09-13 13:26
@cjlapao there's another options: show the collapsed views for all users, then when the extension activates and sets contexts you hide the ones that no longer apply to that user.

**Comment by cjlapao** [comment] 2024-09-13 13:31
@alexr00 I will have a go at that but how would we still fix this is again all views are collapsed. Then we will have users that shouldn't see some of them, seeing everything and then they would disappear.

This will potentially raise some concerns from our users about views disappearing.

**Comment by alexr00** [comment] 2024-09-13 13:38
@cjlapao I appreciate that you're trying to keep your extension a good citizen and not have it do a bunch of unneeded work on startup. it sounds like the ideal scenario for you would be this:
A. Have something that runs eagerly on startup, checks the licenses, and sets the contexts for the view.
B. Have something that runs when a view is opened to provide all your extension functionality.

The best way I can think for you to do this is to have 2 extensions that depend on each other. One that does A and activates on startup finished and one that does B and activates when a view is opened. Given what @sandy081 pointed out about views being moved to other view containers, this is even better than having on `onViewContainer` event.

**Comment by cjlapao** [comment] 2024-09-14 05:48
@alexr00 That will be the same as having the `*` or `onStartupFinished` as the heavy process is the activation one, and that is what we are trying to avoid here. While I understand @sandy081 concern about moving them around, I am not sure what the problem is with adding this activation trigger.

We are not making anything worse, as it is not mandatory, and it will not be worse than the very eager ones we already have. Also, if the user does indeed move the view out of the container, that view will be "hidden" until the right container is enabled, and for our use case, that is completely fine.

At the moment as it stands we will need to move our extension to the eager mode, this will make vscode take a longer time to boot than necessary if the user has our extension installed even if he does not plan to work on virtualization.

But thank you for having a look at this

**Comment by alexr00** [comment] 2024-09-16 13:55
> That will be the same as having the * or onStartupFinished as the heavy process is the activation one, and that is what we are trying to avoid here. 

My thinking is that the eager extension would *only* check licenses and set contexts, making it very light instead of heavy.

> While I understand @sandy081 concern about moving them around, I am not sure what the problem is with adding this activation trigger.

The issue is that users will move the view and you will be in the exact same position you are in right now. It will result in nondeterministic behavior for extension authors who assume that their view will be opened even though it is not, which is not good API for us to provide.

**Comment by cjlapao** [comment] 2024-09-18 08:01
Unfortunately, it is the other way around. Checking for a license is the heaver (long pool action), which we want to avoid, at least in an eager way.

Is it possible to make one of the views not collapsible? That would also work. we could lease the help always to be expanded and hence always starting the extension.

Sorry for asking so many questions. We do understand where you guys are coming from, but we are also trying to find a solution that is easy for users to understand.

**Comment by alexr00** [comment] 2024-09-18 20:36
> Unfortunately, it is the other way around. Checking for a license is the heaver (long pool action), which we want to avoid, at least in an eager way.

Ok, got it. 

There is no way to make one of the views not-collapsible. I think the most thorough and performant way you could do this is the following:
1. Cache the license info locally. Have a simple extension that just reads your local cache and sets contexts that will show/hide the views.
2. Instead of only showing the views if certain contexts are set, hide the views only if certain contexts are set. 
3. Keep the main extension activating off the views. When the extension is finally activated, update the cache in (1) and update the contexts.

If this sounds like a reasonable approach, then maybe we can help out with (1). This can't be the first time an extension has had the catch 22 of wanting contexts set for views but not wanting to activate. @sandy081, could we offer some kind of cross-session persistent context that could be set and that isn't a setting? That way, only one extension would be needed instead of 2.

**Comment by cjlapao** [comment] 2024-09-19 06:23
We are open to trying any solution that can help with this. Now, a second extension is something we are trying to avoid. Having two requires more maintenance, and we don't have a big team on this, so we would like to avoid any extra overhead.

We already have local caching in the form of our own config file, which we read at the beginning. The issue of using caching is people can start without a license, or with a different license and then buy or change it. So, on start we need to check if this changed or not, hence the long pooling process. We do not have a way of telling vscode that the file changed if someone bought a new license.

This is an example where the cache went wrong
https://github.com/Parallels/parallels-vscode-extension/issues/110

The user did have a valid license that we bought after he used the extension, actually, he bought it because of using the extension and then due to us only using the cache.

We tried to use a background check that keeps updating the cache file, but this only works if the vscode is on and the user changes the license at that point; otherwise, when we start, if everything is collapsed, we then end up in the same spot. Also, from what we can see, background processes are very costly to the vscode performance, so we try to avoid it as much as we can.

At the moment, we passed to our PMs the scenario where we have all the views always on and to the init when one of the views is expanded, and if you do not have a license, we just leave it there.

Any other way, besides having two extensions, I cannot think of a way to avoid the eager loading

**Comment by sandy081** [comment] 2024-09-23 10:38
>  could we offer some kind of cross-session persistent context that could be set and that isn't a setting? 

We do not have cross-session persistent context, but extensions can store data in global memento and set the context in the session listening and reading to global memento.

**Comment by alexr00** [comment] 2024-09-24 08:55
@sandy081 to do that the extension already needs to be activated. The issue here is that the extension needs the context set but hasn't yet been activated.

**Comment by sandy081** [comment] 2024-09-24 16:00
Looks like extension needs to be activated on start up for computing licenses and it can do it once and share this information across sessions using global state

**Comment by cjlapao** [comment] 2024-09-30 06:00
@sandy081 Yes, we had that before, but we changed it as the computing of the licensing process and initialization of some of the background processes are very heavy and unnecessary if the user does not intend to use us in every session. 

For example, at the start, when activating it on a Mac, it will check for the license and, in some cases, will start background processes that will run periodically to keep states refreshed. Those are only needed if you indeed want to use our extension; otherwise, they are a waste of resources as the user does not need to keep that updated; keeping it at the startup is just too eager and a bad user experience to add so much backend processes where they do not provide any benefits. Unless I am wrong, I cannot see an activate per view, an activate per startup, or an onCollapse action for the view. If we have any of those then we can work the license at the beginning, set some context variables and then on the view being activated having this.

**Comment by alexr00** [comment] 2024-09-30 08:55
Discussed with @sandy081 and here's our best recommendation:
- Activate on startup
- On first run of the extension fetch the license state. Cache it.
- On subsequent runs of the extension, only read the cache on activation.
- Listen for one of your views becoming visible: https://github.com/microsoft/vscode/blob/ae985885b9f9dc7b8bcc8bfd55908aa171b83409/src/vscode-dts/vscode.d.ts#L11754-L11757
- When the view becomes visible, start your background license state refresh.

If this doesn't work for you, then we could consider adding an "on view visible, even if it's just collapsed" activation event.

**Closed by alexr00** 2024-09-30 08:55 UTC
