### ISSUE TITLE
Integrated terminal hangs when trying to print an API response

### ISSUE THREAD

**Issue by storfiskur** [microsoft/vscode#214553] opened 2024-06-07 06:03 UTC
Does this issue occur when all extensions are disabled?: Yes

The built-in terminal hangs when trying to output a large API response.
Works flawlessly in external Powershell and on Linux on the same machine and vscode version. 
Older versions of vscode (I tried 1.86.2.) work fine.

- VS Code Version: 1.90.0
- OS Version:  Windows 11 Pro 23H2
Steps to Reproduce:
1.  Make a query to the API with a relatively large response (such as https://pokeapi.co/api/v2/pokemon/pikachu) in any language of choice. I've tried Python and Go
2. Print the response to the integrated terminal

**Comment by meganrogge** [comment] 2024-06-07 16:57
are you using git bash? if so, /duplicate of https://github.com/microsoft/vscode/issues/212090

**Closed by meganrogge** 2024-06-07 16:57 UTC
Labels: new release
