### ISSUE TITLE
HTML formatting with multi-line attribute values

### ISSUE THREAD

**Issue by edvinv** [Microsoft/vscode#21294] opened 2017-02-23 16:04 UTC
Following html is not correctly formatted. Both closing divs are at same position. It looks like that problem is with multi-line attribute value (data-columns in example). If I change data-columns value to single-line it is correctly formatted. But some attribute values can be very long and putting them into single line becomes totally unreadable.

```html
<div id="dialer-capmaign-console" class="fill-vertically" style="flex: 1 1 auto;">
	<div id="sessionsGrid" data-columns="[
		{ field: 'dialerSession.startTime', format:'{0:G}', title:'Start time', width:122 },
		{ field: 'dialerSession.endTime', format:'{0:G}', title:'End time', width:122, attributes: {class:'tooltip-column'}},
		{ field: 'conversationStartTime', template: cty.ui.gct.duration_dialerSession_conversationStartTime_endTime, title:'Duration', width:80},
		{ field: 'dialerSession.caller.lastName',template: cty.ui.gct.person_dialerSession_caller_link, title:'Caller', width:160 },
		{ field: 'noteType',template:cty.ui.gct.nameDescription_noteType, title:'Note type', width:150, attributes: {class:'tooltip-column'}},
		{ field: 'note', title:'Note'}
		]">
</div>
</div>
```

**Comment by aeschli** [comment] 2017-02-23 19:57
duplicate of #20844. It's fixed in the latest insiders build.

**Closed by aeschli** 2017-02-23 19:57 UTC
