### ISSUE TITLE
Markdown syntax highlighting in JSDoc comments has stopped working

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#84853] opened 2019-11-14 18:49 UTC
Until now, some markdown was highlighted in multiline JSDoc comments. For example, the inline code was higlighted here:
```js
  /**
   * SVG icon path to show. If not provided, no icon will appear. Icon paths can
   * be imported from `@mdi/js`, ie: `import {mdiAbTesting} from "@mdi/js";`.
   */
```

Now, the entire comment is gray except only JSDoc tags are highlighted:
![image](https://user-images.githubusercontent.com/2294248/68886599-83fe9b00-06e5-11ea-8565-b6b56b8827e9.png)

Version: 1.41.0-insider (user setup)
Commit: b6a486e34fe3715f6edec0cdb11138b1672d33bd
Date: 2019-11-14T05:35:51.486Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by Jaeiya** [comment] 2019-11-14 19:00
Just want to confirm that I have the same issue.

**Comment by mjbvz** [comment] 2019-11-14 19:06
Duplicate of #84626

**Closed by mjbvz** 2019-11-14 19:06 UTC
