### ISSUE TITLE
When I writing fast `console.log(` deletes `log` for some reason

### ISSUE THREAD

**Issue by aliev** [Microsoft/vscode#57072] opened 2018-08-23 09:16 UTC
- VSCode Version: Version 1.26.1 (1.26.1)
- OS Version: 10.13.6 (17G65)

Steps to Reproduce:

1. Open JavaScript file (with jsx)
2. Write console.log(

Does this issue occur when all extensions are disabled?: Yes

My settings.json: https://gist.github.com/aliev/6134f897587390dec4c3ffe40390d9ab
Video how it looks: https://drive.google.com/open?id=1UK2Ikl4rhprPX66Jnshhwyb7OIRFmybu

It seems this happens when the autocomplete is turned on. I disabled all plugins before testing and recording video.

**Comment by ojassvi** [comment] 2018-08-24 19:45
Yeah, I am also facing this issue.

**Comment by rdenman** [comment] 2018-08-27 13:49
I've been seeing this since last updating as well (VS Code 1.26.1, Windows 10.0.16299)

**Comment by Utopiad** [comment] 2018-09-02 08:42
@aliev I can't see your settings (leads me to Github's 404), but do you have this setting set to false ?
`editor.acceptSuggestionOnCommitCharacter`
Since I changed it three weeks ago, I no longer have this problem.

**Comment by aliev** [comment] 2018-09-02 09:13
@Utopiad ah sorry I updated gist link. seems to work!

**Comment by mjbvz** [comment] 2018-09-11 22:04
Please test this in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled. I was able to reproduce this in older builds but made a few tweaks to how suggestions work haven't been to in recent insiders builds

**Comment by mjbvz** [comment] 2018-09-17 22:56
Closing as either fixed in insiders or related to typescript plugins, see: https://github.com/styled-components/vscode-styled-components/issues/132

**Closed by mjbvz** 2018-09-17 22:56 UTC
Labels: bug, javascript, needs more info
