### ISSUE TITLE
TypeScript syntax highlighting issue with arrow functions

### ISSUE THREAD

**Issue by tristan957** [Microsoft/vscode#73157] opened 2019-05-02 06:48 UTC
- VSCode Version: 1.33.1
- OS Version: Solus 4

Steps to Reproduce:
1. Setup code like so:
```ts
public constructor(authService: AuthService) {
		super(GoogleStrategy.options, async (
			req: Request, // eslint-disable-line @typescript-eslint/no-unused-vars
			accessToken: string,
			refreshToken: string, // eslint-disable-line @typescript-eslint/no-unused-vars
			profile: Profile, // eslint-disable-line @typescript-eslint/no-unused-vars
			done: VerifyFunction // eslint-disable-line @typescript-eslint/no-unused-vars
		): Promise<User> => {
			const user = await authService.validateUser(accessToken);
			if (user === undefined) {
				throw new UnauthorizedException();
			}

			return user;
		});
	}
```
![image](https://user-images.githubusercontent.com/11936772/57059717-23919a00-6c7c-11e9-8cf9-f70e249717c1.png)

2. Then change it to this

```ts
public constructor(authService: AuthService) {
		super(
			GoogleStrategy.options,
			async (
				req: Request, // eslint-disable-line @typescript-eslint/no-unused-vars
				accessToken: string,
				refreshToken: string, // eslint-disable-line @typescript-eslint/no-unused-vars
				profile: Profile, // eslint-disable-line @typescript-eslint/no-unused-vars
				done: VerifyFunction // eslint-disable-line @typescript-eslint/no-unused-vars
			): Promise<User> => {
				const user = await authService.validateUser(accessToken);
				if (user === undefined) {
					throw new UnauthorizedException();
				}

				return user;
			}
		);
	}
```
![image](https://user-images.githubusercontent.com/11936772/57059780-65badb80-6c7c-11e9-80ac-fae008eaeba0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by tristan957** [comment] 2019-05-02 06:49
The syntax even breaks in GitHub highlighting haha

**Comment by mjbvz** [comment] 2019-05-02 16:32
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment] 2019-05-02 16:34
Also, what is the issue? The wrong color keywords in the arrow func?

**Comment by tristan957** [comment] 2019-05-02 18:08
Not sure why the second image did not get posted. The textmate grammar classifiers change significantly in the second example. `async` becomes a function name. The parameters are no longer classified as such. This reproduces in insiders on macOS.

**Comment by mjbvz** [comment] 2019-05-03 00:04
Thanks for the clarification.

This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/705 which has been marked as wont-fix due to the limitations of textmate grammars

Closing as a duplicate

**Closed by mjbvz** 2019-05-03 00:04 UTC
Labels: needs more info, typescript
