### ISSUE TITLE
Line-final cursor position incorrect with Unicode combining characters 0x300 - 0x363

### ISSUE THREAD

**Issue by anyong** [Microsoft/vscode#5511] opened 2016-04-19 17:41 UTC
- VSCode Version: 1.0.0-insider
- OS Version:Windows 10

Steps to Reproduce:

1. Write text with a Unicode combining character
2. Try to move the cursor to the end of the line, it jumps back to the beginning

![](http://i.imgur.com/UP3rHt1.gif)

**Comment by JamieSharpe** [comment] 2016-04-22 18:28
This also happens with:

- U+2712 (Black Nib) ✒️
- U+1F5D2 (Spiral Note Pad) 🗒

**Comment by alexandrudima** [comment] 2016-04-27 16:12
@anyong Love the bug report gif! This could be caused by a Chromium bug that would hit us also when writing Thai.

**Comment by alexandrudima** [comment] 2016-04-27 20:47
Thanks to the update to Electron 0.37.6 that brings in Chromium 49, we get the fix from Chromium. I have verified this is fixed on master.

**Closed by alexandrudima** 2016-04-27 20:47 UTC
Labels: editor

**Comment by anyong** [comment] 2016-04-27 21:47
Excellent, when will this be in insider build?

**Comment by alexandrudima** [comment] 2016-04-29 07:20
@anyong The latest insider build already contains the update to Electron v0.37.6
