### ISSUE TITLE
Problems: focus lost when clicked

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91139] opened 2020-02-21 10:44 UTC
Steps to Reproduce:

1. expand a node in problems
2. click an error

=> 🐛 focus moves into editor

![Kapture 2020-02-21 at 11 43 24](https://user-images.githubusercontent.com/900690/75027762-676dbe00-549f-11ea-8750-4b6278cdf738.gif)

**Comment by sandy081** [comment] 2020-02-23 14:18
I can't reproduce, do you have a special set up or extensions?

**Comment by bpasero** [comment] 2020-02-23 15:26
@sandy081 hm right, does not reproduce with TS errors. These are ESLint errors, maybe that is coming from the extension?

**Comment by sandy081** [comment] 2020-02-26 11:02
It could be that diagnostics are regenerated on opening the file?

**Comment by bpasero** [comment] 2020-02-26 11:10
@sandy081 yes that is exactly what is happening, good point. The editor does not gain focus, but the selected problem is lost.

**Comment by sandy081** [comment] 2020-02-26 11:12
@bpasero Is it possible to provide me set up this so that I can repro and see how  I can fix this?

**Comment by bpasero** [comment] 2020-02-26 11:13
@sandy081 yeah here you go:
* overwrite our eslintrc.json with the contents below
* run the task to run eslint
* click on a warning

```json
{
    "root": true,
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint",
        "jsdoc"
    ],
    "rules": {
        "constructor-super": "warn",
        "curly": "warn",
        "eqeqeq": "warn",
        "no-buffer-constructor": "warn",
        "no-caller": "warn",
        "no-debugger": "warn",
        "no-duplicate-case": "warn",
        "no-duplicate-imports": "warn",
        "no-eval": "warn",
        "no-extra-semi": "warn",
        "no-new-wrappers": "warn",
        "no-redeclare": "warn",
        "no-sparse-arrays": "warn",
        "no-throw-literal": "warn",
        "no-unsafe-finally": "warn",
        "no-unused-labels": "warn",
        "no-restricted-globals": [
            "warn",
            "name",
            "length",
            "event",
            "closed",
            "external",
            "status",
            "origin",
            "orientation"
        ], // non-complete list of globals that are easy to access unintentionally
        "no-var": "warn",
        "jsdoc/no-types": "warn",
        "semi": "warn",
        "@typescript-eslint/semi": "warn",
        "@typescript-eslint/class-name-casing": "warn",
        "code-no-unused-expressions": [
            "warn",
            {
                "allowTernary": true
            }
        ],
        "code-translation-remind": "warn",
        "code-no-nls-in-standalone-editor": "warn",
        "code-no-standalone-editor": "warn",
        "code-no-unexternalized-strings": "warn",
        "code-layering": [
            "warn",
            {
                "common": [],
                "node": [
                    "common"
                ],
                "browser": [
                    "common"
                ],
                "electron-main": [
                    "common",
                    "node"
                ],
                "electron-browser": [
                    "common",
                    "browser",
                    "node"
                ]
            }
        ],
        "code-import-patterns": [
            "warn",
            // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            // !!! Do not relax these rules !!!
            // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            {
                "target": "**/vs/base/common/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/common/**"
                ]
            },
            {
                "target": "**/vs/base/test/common/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/base/test/common/**"
                ]
            },
            {
                "target": "**/vs/base/browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/base/node/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/{common,node}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                // vs/base/test/browser contains tests for vs/base/browser
                "target": "**/vs/base/test/browser/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/base/test/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/base/parts/*/common/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/base/parts/*/common/**"
                ]
            },
            {
                "target": "**/vs/base/parts/*/browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/base/parts/*/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/base/parts/*/node/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/{common,node}/**",
                    "**/vs/base/parts/*/{common,node}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/base/parts/*/electron-browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser,node,electron-browser}/**",
                    "**/vs/base/parts/*/{common,browser,node,electron-browser}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/base/parts/*/electron-main/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/{common,node,electron-main}/**",
                    "**/vs/base/parts/*/{common,node,electron-main}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/platform/*/common/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/base/parts/*/common/**",
                    "**/vs/platform/*/common/**"
                ]
            },
            {
                "target": "**/vs/platform/*/test/common/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/base/parts/*/common/**",
                    "**/vs/platform/*/common/**",
                    "**/vs/platform/*/test/common/**"
                ]
            },
            {
                "target": "**/vs/platform/*/browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/base/parts/*/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/platform/*/node/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/{common,node}/**",
                    "**/vs/base/parts/*/{common,node}/**",
                    "**/vs/platform/*/{common,node}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/platform/*/electron-browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser,node}/**",
                    "**/vs/base/parts/*/{common,browser,node,electron-browser}/**",
                    "**/vs/platform/*/{common,browser,node,electron-browser}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/platform/*/electron-main/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/{common,node,electron-main}/**",
                    "**/vs/base/parts/*/{common,node,electron-main}/**",
                    "**/vs/platform/*/{common,node,electron-main}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/platform/*/test/browser/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**",
                    "**/vs/platform/*/test/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/editor/common/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/base/worker/**",
                    "**/vs/platform/*/common/**",
                    "**/vs/editor/common/**"
                ]
            },
            {
                "target": "**/vs/editor/test/common/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/platform/*/common/**",
                    "**/vs/platform/*/test/common/**",
                    "**/vs/editor/common/**",
                    "**/vs/editor/test/common/**"
                ]
            },
            {
                "target": "**/vs/editor/browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**",
                    "**/vs/editor/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/editor/test/browser/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**",
                    "**/vs/platform/*/test/{common,browser}/**",
                    "**/vs/editor/{common,browser}/**",
                    "**/vs/editor/test/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/editor/standalone/common/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/platform/*/common/**",
                    "**/vs/editor/common/**",
                    "**/vs/editor/standalone/common/**"
                ]
            },
            {
                "target": "**/vs/editor/standalone/test/common/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/platform/*/common/**",
                    "**/vs/platform/*/test/common/**",
                    "**/vs/editor/common/**",
                    "**/vs/editor/test/common/**"
                ]
            },
            {
                "target": "**/vs/editor/standalone/browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/base/parts/*/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**",
                    "**/vs/editor/{common,browser}/**",
                    "**/vs/editor/contrib/**",
                    "**/vs/editor/standalone/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/editor/standalone/test/browser/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**",
                    "**/vs/platform/*/test/{common,browser}/**",
                    "**/vs/editor/{common,browser}/**",
                    "**/vs/editor/standalone/{common,browser}/**",
                    "**/vs/editor/test/{common,browser}/**"
                ]
            },
            {
                "target": "**/vs/editor/contrib/*/test/**",
                "restrictions": [
                    "assert",
                    "sinon",
                    "vs/nls",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/base/test/{common,browser}/**",
                    "**/vs/base/parts/*/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**",
                    "**/vs/platform/*/test/{common,browser}/**",
                    "**/vs/editor/{common,browser}/**",
                    "**/vs/editor/test/{common,browser}/**",
                    "**/vs/editor/contrib/**"
                ]
            },
            {
                "target": "**/vs/editor/contrib/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/base/parts/*/{common,browser}/**",
                    "**/vs/platform/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**",
                    "**/vs/editor/{common,browser}/**",
                    "**/vs/editor/contrib/**"
                ]
            },
            {
                "target": "**/vs/workbench/common/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/base/parts/*/common/**",
                    "**/vs/platform/*/common/**",
                    "**/vs/editor/common/**",
                    "**/vs/editor/contrib/*/common/**",
                    "**/vs/workbench/common/**",
                    "**/vs/workbench/services/*/common/**",
                    "assert"
                ]
            },
            {
                "target": "**/vs/workbench/browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser}/**",
                    "**/vs/base/parts/*/{common,browser}/**",
                    "**/vs/platform/*/{common,browser}/**",
                    "**/vs/editor/{common,browser}/**",
                    "**/vs/editor/contrib/**", // editor/contrib is equivalent to /browser/ by convention
                    "**/vs/workbench/workbench.web.api",
                    "**/vs/workbench/{common,browser}/**",
                    "**/vs/workbench/services/*/{common,browser}/**",
                    "assert"
                ]
            },
            {
                "target": "**/vs/workbench/workbench.desktop.main.ts",
                "restrictions": [
                    "**"
                ]
            },
            {
                "target": "**/vs/workbench/api/common/**",
                "restrictions": [
                    "vscode",
                    "vs/nls",
                    "**/vs/base/common/**",
                    "**/vs/platform/*/common/**",
                    "**/vs/editor/common/**",
                    "**/vs/editor/contrib/*/common/**",
                    "**/vs/workbench/api/common/**",
                    "**/vs/workbench/common/**",
                    "**/vs/workbench/services/*/common/**",
                    "**/vs/workbench/contrib/*/common/**"
                ]
            },
            {
                "target": "**/vs/workbench/api/worker/**",
                "restrictions": [
                    "vscode",
                    "vs/nls",
                    "**/vs/**/{common,worker}/**"
                ]
            },
            {
                "target": "**/vs/workbench/electron-browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/{common,browser,node,electron-browser}/**",
                    "**/vs/base/parts/*/{common,browser,node,electron-browser}/**",
                    "**/vs/platform/*/{common,browser,node,electron-browser}/**",
                    "**/vs/editor/{common,browser,node,electron-browser}/**",
                    "**/vs/editor/contrib/**", // editor/contrib is equivalent to /browser/ by convention
                    "**/vs/workbench/{common,browser,node,electron-browser,api}/**",
                    "**/vs/workbench/services/*/{common,browser,node,electron-browser}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/workbench/services/**/test/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/**",
                    "**/vs/platform/**",
                    "**/vs/editor/**",
                    "**/vs/workbench/{common,browser,node,electron-browser}/**",
                    "vs/workbench/contrib/files/common/editors/fileEditorInput",
                    "**/vs/workbench/services/**",
                    "**/vs/workbench/test/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/workbench/services/**/common/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/**/common/**",
                    "**/vs/platform/**/common/**",
                    "**/vs/editor/common/**",
                    "**/vs/workbench/workbench.web.api",
                    "**/vs/workbench/common/**",
                    "**/vs/workbench/services/**/common/**",
                    "**/vs/workbench/api/**/common/**",
                    "vscode-textmate"
                ]
            },
            {
                "target": "**/vs/workbench/services/**/worker/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/**/common/**",
                    "**/vs/platform/**/common/**",
                    "**/vs/editor/common/**",
                    "**/vs/workbench/**/common/**",
                    "**/vs/workbench/**/worker/**",
                    "**/vs/workbench/services/**/common/**",
                    "vscode"
                ]
            },
            {
                "target": "**/vs/workbench/services/**/browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/**/{common,browser,worker}/**",
                    "**/vs/platform/**/{common,browser}/**",
                    "**/vs/editor/{common,browser}/**",
                    "**/vs/workbench/workbench.web.api",
                    "**/vs/workbench/{common,browser}/**",
                    "**/vs/workbench/api/{common,browser}/**",
                    "**/vs/workbench/services/**/{common,browser}/**",
                    "vscode-textmate",
                    "onigasm-umd"
                ]
            },
            {
                "target": "**/vs/workbench/services/**/node/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/**/{common,node}/**",
                    "**/vs/platform/**/{common,node}/**",
                    "**/vs/editor/{common,node}/**",
                    "**/vs/workbench/{common,node}/**",
                    "**/vs/workbench/api/{common,node}/**",
                    "**/vs/workbench/services/**/{common,node}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/workbench/services/**/electron-browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/**/{common,browser,worker,node,electron-browser}/**",
                    "**/vs/platform/**/{common,browser,node,electron-browser}/**",
                    "**/vs/editor/**",
                    "**/vs/workbench/{common,browser,node,electron-browser,api}/**",
                    "**/vs/workbench/services/**/{common,browser,node,electron-browser}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/workbench/contrib/terminal/browser/**",
                "restrictions": [
                    // xterm and its addons are strictly browser-only components
                    "xterm",
                    "xterm-addon-*",
                    "**/vs/**"
                ]
            },
            {
                "target": "**/vs/workbench/contrib/extensions/browser/**",
                "restrictions": [
                    "semver-umd",
                    "**/vs/**"
                ]
            },
            {
                "target": "**/vs/workbench/contrib/update/browser/update.ts",
                "restrictions": [
                    "semver-umd",
                    "**/vs/**"
                ]
            },
            {
                "target": "**/vs/code/node/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/**/{common,node}/**",
                    "**/vs/base/parts/**/{common,node}/**",
                    "**/vs/platform/**/{common,node}/**",
                    "**/vs/code/**/{common,node}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/code/electron-browser/**",
                "restrictions": [
                    "vs/nls",
                    "vs/css!./**/*",
                    "**/vs/base/**/{common,browser,node,electron-browser}/**",
                    "**/vs/base/parts/**/{common,browser,node,electron-browser}/**",
                    "**/vs/platform/**/{common,browser,node,electron-browser}/**",
                    "**/vs/code/**/{common,browser,node,electron-browser}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/code/electron-main/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/**/{common,node,electron-main}/**",
                    "**/vs/base/parts/**/{common,node,electron-main}/**",
                    "**/vs/platform/**/{common,node,electron-main}/**",
                    "**/vs/code/**/{common,node,electron-main}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/vs/server/**",
                "restrictions": [
                    "vs/nls",
                    "**/vs/base/**/{common,node}/**",
                    "**/vs/base/parts/**/{common,node}/**",
                    "**/vs/platform/**/{common,node}/**",
                    "**/vs/workbench/**/{common,node}/**",
                    "**/vs/server/**",
                    "**/vs/code/**/{common,node}/**",
                    "!path" // node modules (except path where we have our own impl)
                ]
            },
            {
                "target": "**/{node,electron-browser,electron-main}/**",
                "restrictions": "**/*"
            },
            {
                "target": "**/extensions/**",
                "restrictions": "**/*"
            },
            {
                "target": "**/test/smoke/**",
                "restrictions": [
                    "**/test/smoke/**",
                    "*"
                ]
            },
            {
                "target": "**/test/automation/**",
                "restrictions": [
                    "**/test/automation/**",
                    "*"
                ]
            },
            {
                "target": "**/test/integration/**",
                "restrictions": [
                    "**/test/integration/**",
                    "*"
                ]
            },
            {
                "target": "{**/api/**.test.ts,}",
                "restrictions": "{**/vs/**,assert,sinon,crypto,vscode}"
            },
            {
                "target": "{**/**.test.ts,**/test/**}",
                "restrictions": "{**/vs/**,assert,sinon,crypto,xterm*}"
            },
            {
                "target": "**/{common,browser,workbench}/**",
                "restrictions": "**/vs/**"
            }
        ]
    },
    "overrides": [
        {
            "files": [
                "*.js"
            ],
            "rules": {
                "jsdoc/no-types": "off"
            }
        },
        {
            "files": [
                "**/vscode.d.ts",
                "**/vscode.proposed.d.ts"
            ],
            "rules": {
                "vscode-dts-create-func": "warn",
                "vscode-dts-literal-or-types": "warn",
                "vscode-dts-interface-naming": "warn",
                "vscode-dts-event-naming": [
                    "warn",
                    {
                        "allowed": [
                            "onCancellationRequested",
                            "event"
                        ],
                        "verbs": [
                            "accept",
                            "change",
                            "close",
                            "collapse",
                            "create",
                            "delete",
                            "dispose",
                            "edit",
                            "end",
                            "expand",
                            "hide",
                            "open",
                            "override",
                            "receive",
                            "register",
                            "rename",
                            "save",
                            "send",
                            "start",
                            "terminate",
                            "trigger",
                            "unregister",
                            "write"
                        ]
                    }
                ]
            }
        }
    ]
}

```

**Comment by sandy081** [comment] 2020-06-11 15:50
Actually it seems the issue is with typescript generating different diagnostics. I tried following steps:

1. overwrite `eslintrc.json` with the contents above
2. run the task - `npm eslint`
3. Wait until problems are generated in problems views
4. click on the error/warning from problems view 

At step 3 ESLint is generating following diagnostic:

```
code: "@typescript-eslint/class-name-casing"
endColumn: 2
endLineNumber: 1
message: "Definition for rule '@typescript-eslint/class-name-casing' was not found."
owner: "eslint"
relatedInformation: undefined
resource: _URI {scheme: "file", authority: "", path: "/Users/sandy081/work/vscode/src/vs/base/browser/fastDomNode.ts", query: "", fragment: "", …}
severity: 8
source: "eslint"
startColumn: 1
startLineNumber: 1
tags: undefined
```

After step 4, file is opened and TS is generating following diagnostic.

```
code: "@typescript-eslint/class-name-casing"
endColumn: 1
endLineNumber: 1
message: "Definition for rule '@typescript-eslint/class-name-casing' was not found"
owner: "eslint"
relatedInformation: undefined
resource: _URI {scheme: "file", authority: "", path: "/Users/sandy081/work/vscode/src/vs/base/browser/fastDomNode.ts", query: "", fragment: "", …}
severity: 8
source: "eslint"
startColumn: 1
startLineNumber: 1
tags: undefined
```

Both diagnostics are almost same except that `endColumn` is different. Hence selection is lost on Problems view.

To be sure, I tried reproducing this with a sample extension that generates 
- diagnostics when activated 
- same diagnostics when file is opened

```
export function activate(context: vscode.ExtensionContext) {

	const collection = vscode.languages.createDiagnosticCollection('test');
	const uri = vscode.workspace.workspaceFolders![0].uri.with({ path: path.join(vscode.workspace.workspaceFolders![0].uri.path, 'package.json') })
	collection.set(uri, [createDiagnostic(uri)]);

	vscode.window.onDidChangeActiveTextEditor(e => {
		if (vscode.window.activeTextEditor) {
			collection.set(vscode.window.activeTextEditor.document.uri, [createDiagnostic(vscode.window.activeTextEditor.document.uri)]);
		}
	});
}

function createDiagnostic(uri: vscode.Uri): vscode.Diagnostic {
	return {
		code: '1234',
		message: 'this is a sample error',
		range: new vscode.Range(new vscode.Position(3, 4), new vscode.Position(3, 10)),
		severity: vscode.DiagnosticSeverity.Error,
		source: 'abcd'
	};
}
```

Problems view is not loosing selection here when the file is opened from problems view.

Hence assigning to @mjbvz to see why diagnostics have different `endColumn`

**Comment by mjbvz** [comment] 2020-06-11 17:50
Hey @dbaeumer, looks like these diagnostics are actually from eslint. I wonder if this is a mismatch between the  problems matcher and the diagnostics the extension generates when you open a file

**Comment by bpasero** [comment] 2020-06-12 06:11
@sandy081 can you elaborate how the fact that line numbers are part of the diagnostics causes the problems view to loose focus?

**Comment by dbaeumer** [comment] 2020-06-12 10:14
I tried to reproduce and all I get is:

<img width="650" alt="capture" src="https://user-images.githubusercontent.com/1931590/84492304-46c3b100-aca6-11ea-9e8b-ed28dd064cb1.png">

@bpasero any hint what I do wrong?

**Comment by sandy081** [comment] 2020-06-12 13:33
> can you elaborate how the fact that line numbers are part of the diagnostics causes the problems view to loose focus?

Different line numbers implies different diagnostics. So replacing diagnostics loses the focus as the old diagnostic does not exist. Instead of losing focus, I can focus on other diagnostic (say first, previous etc) but the issue here is that if there is no change in diagnostic there should not be any focus change.

**Comment by sandy081** [comment] 2020-06-12 13:34
@dbaeumer Now can you click on one of the error and see if the selection in the problems view is lost?

**Comment by bpasero** [comment] 2020-06-12 15:22
Oh yeah, indeed it seems it is not focusing editor but simply loosing focus. I will update the summary.

**Comment by dbaeumer** [comment] 2020-06-15 09:15
Actually there is little I can do. This is what I get from the eslint when running the extension:

<img width="348" alt="capture" src="https://user-images.githubusercontent.com/1931590/84639924-525ae600-aef9-11ea-8cb3-17eb52a29786.png">

And the task (eslint terminal output) reports:

<img width="700" alt="capture" src="https://user-images.githubusercontent.com/1931590/84640046-75859580-aef9-11ea-88d9-8ac1d3da20b4.png">

Assigning to @sandy081 to handle the case more gracefully. I am very reluctant to start changing reported line / column information.

**Comment by dbaeumer** [comment] 2020-06-15 09:17
@sandy081 please ping if you think there is something I should / could do.

**Comment by sandy081** [comment] 2020-06-15 16:18
Thanks @dbaeumer. It seems TS and ESLint are not getting along with each other and generating different line numbers for same error. 

I do not want to make any assumptions in the core to fix it. Hence leaving to @mjbvz to see if this difference can be removed or not.

**Comment by mjbvz** [comment] 2020-06-15 18:51
@sandy081 As far as I can tell these error do not come from TypeScript, they are both from eslint. Please follow up with @dbaeumer to see see if eslint needs to be fixed or if the problems view can be less strict when checking if two errors are equivalent

**Comment by dbaeumer** [comment] 2020-06-16 07:17
@sandy081 both problems do come from ESLint. The one is through a task run in the terminal using eslint on the command line. The other is from the vscode-eslint extension calling into the ESLint node API. I don't know why they generate different end character information but as you can see here they do: https://github.com/microsoft/vscode/issues/91139#issuecomment-644008864

I am not asking that you fold them. You can't. But why do we have to loose focus in the editor in this case?

**Comment by sandy081** [comment] 2020-06-16 13:13
> But why do we have to loose focus in the editor in this case?

We are not loosing focus in the editor instead we are loosing focus in Problems views. This is because the problems are getting replaced (the one from eslint command line with vscode-eslint extension) and since these problems are different focus is not retained.

**Comment by dbaeumer** [comment] 2020-06-17 10:01
OK, now I understand. But we could preserve focus in the problems view and simply deselect the item.

**Comment by sandy081** [comment] 2020-06-17 13:59
Added a fix to not to loose the focus and retain to the first diagnostic.

**Closed by sandy081** 2020-06-17 13:59 UTC
Labels: bug, error-list
