### ISSUE TITLE
Autocompletion not working inside template literals of TypeScript 

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#26190] opened 2017-05-08 08:41 UTC
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Write following code in typescript
 ```typescript
 let name = 'foo';
 let result = `${name}`;
 ```
2. No autocompletion poped for `name` variable.

**Comment by mjbvz** [comment] 2017-05-08 16:26
Try setting: 

```
	"editor.quickSuggestions": {
		"other": true,
		"comments": false,
		"strings": true
	}
```

Closing as duplicate of #23962

**Closed by mjbvz** 2017-05-08 16:26 UTC

**Comment by Huachao** [comment] 2017-05-09 00:02
@mjbvz I think for string interpolation case, like in ES6, C#, Typescript, they'd better not be categorized into "String", since we always need autocompletion for them
