### ISSUE TITLE
vscode appends git diff to commit message

### ISSUE THREAD

**Issue by BernhardFuchs** [microsoft/vscode#92581] opened 2020-03-12 14:17 UTC
- VSCode Version: 1.43.0
- OS Version: macOS Catalina 10.15.3

Steps to Reproduce:

1. Set vscode as default editor for git `git config --global core.editor "code --wait"`
2. Take following Angular component:
```lang-ts
import { Component, ViewChild, ElementRef, OnInit } from '@angular/core';
import { ThemeConstantService } from '../shared/services/theme-constant.service';

@Component({
  templateUrl: './dashboard.component.html',
  styles: [
    `
      @media only screen and (min-width: 992px) {
        .completion-chart {
          width: calc(100% - 330px);
        }
      }
    `
  ]
})
export class ProjectsDashboardComponent implements OnInit {
  constructor(private colorConfig: ThemeConstantService) {}
  themeColors = this.colorConfig.get().colors;
  blue = this.themeColors.blue;
  blueLight = this.themeColors.blueLight;
  cyan = this.themeColors.cyan;
  cyanLight = this.themeColors.cyanLight;
  gold = this.themeColors.gold;
  purple = this.themeColors.purple;
  purpleLight = this.themeColors.purpleLight;
  red = this.themeColors.red;
  transparent = this.themeColors.transparent;

  @ViewChild('completionChart', { static: true }) canvas: ElementRef;

  completionChartData: Array<any> = [
    {
      data: [30, 60, 40, 50, 40, 55, 85, 65, 75, 50, 70],
      label: 'Series A'
    }
  ];
  currentcompletionChartLabelsIdx = 1;
  completionChartLabels: Array<any> = [
    '16th',
    '17th',
    '18th',
    '19th',
    '20th',
    '21th',
    '22th',
    '23th',
    '24th',
    '25th',
    '26th'
  ];
  completionChartOptions: any = {
    maintainAspectRatio: false,
    responsive: true,
    hover: {
      mode: 'nearest',
      intersect: true
    },
    tooltips: {
      mode: 'index'
    },
    elements: {
      line: {
        tension: 0,
        borderWidth: 2
      }
    },
    scales: {
      xAxes: [
        {
          gridLines: [
            {
              display: false
            }
          ],
          ticks: {
            display: true,
            fontColor: this.themeColors.grayLight,
            fontSize: 13,
            padding: 10
          }
        }
      ],
      yAxes: [
        {
          gridLines: {
            drawBorder: false,
            drawTicks: false,
            borderDash: [3, 4],
            zeroLineWidth: 1,
            zeroLineBorderDash: [3, 4]
          },
          ticks: {
            display: true,
            max: 100,
            stepSize: 20,
            fontColor: this.themeColors.grayLight,
            fontSize: 13,
            padding: 10
          }
        }
      ]
    }
  };
  completionChartColors;
  completionChartType = 'line';

  projectList = [
    {
      project: 'Mind Cog App',
      avatar: 'assets/images/others/thumb-1.jpg',
      status: 'Ready',
      tasks: '31',
      progress: 100
    },
    {
      project: 'Mill Estate',
      avatar: 'assets/images/others/thumb-2.jpg',
      status: 'In Progress',
      tasks: '56',
      progress: 76
    },
    {
      project: 'Eastern Sack',
      avatar: 'assets/images/others/thumb-3.jpg',
      status: 'In Progress',
      tasks: '21',
      progress: 87
    },
    {
      project: 'Fortier Studio',
      avatar: 'assets/images/others/thumb-5.jpg',
      status: 'In Progress',
      tasks: '18',
      progress: 68
    },
    {
      project: 'Indi Web',
      avatar: 'assets/images/others/thumb-6.jpg',
      status: 'Behind',
      tasks: '165',
      progress: 28
    }
  ];

  memberList = [
    {
      name: 'Erin Gonzales',
      img: 'assets/images/avatars/thumb-1.jpg',
      mail: 'erin.gon@gmail.com'
    },
    {
      name: 'Darryl Day',
      img: 'assets/images/avatars/thumb-2.jpg',
      mail: 'darryl.d@gmail.com'
    },
    {
      name: 'Marshall Nichols',
      img: 'assets/images/avatars/thumb-3.jpg',
      mail: 'marshalln@gmail.com'
    },
    {
      name: 'Virgil Gonzales',
      img: 'assets/images/avatars/thumb-4.jpg',
      mail: 'virgil14@gmail.com'
    },
    {
      name: 'Nicole Wyne',
      img: 'assets/images/avatars/thumb-5.jpg',
      mail: 'nicolew@gmail.com'
    },
    {
      name: 'Riley Newman',
      img: 'assets/images/avatars/thumb-6.jpg',
      mail: 'rileyn93@gmail.com'
    },
    {
      name: 'Pamela Wanda',
      img: 'assets/images/avatars/thumb-7.jpg',
      mail: 'pamelaw@gmail.com'
    }
  ];

  activityList = [
    {
      name: 'Virgil Gonzales',
      date: '10:44 PM',
      action: 'Complete task',
      target: 'Prototype Design',
      actionType: 'completed'
    },
    {
      name: 'Marshall Nichols',
      date: '10:44 PM',
      action: 'Complete task',
      target: 'Documentation',
      actionType: 'completed'
    },
    {
      name: 'Virgil Gonzales',
      date: '8:34 PM',
      action: 'Commented',
      target: "'That's not our work",
      actionType: 'comment'
    },
    {
      name: 'Pamela Wanda',
      date: '8:34 PM',
      action: 'Removed',
      target: 'a file',
      actionType: 'removed'
    },
    {
      name: 'Lilian Stone',
      date: '8:34 PM',
      action: 'Attached file',
      target: 'Mockup Zip',
      actionType: 'upload'
    },
    {
      name: 'Marshall Nichols',
      date: '10:44 PM',
      action: 'Complete task',
      target: 'UI Revamp',
      actionType: 'completed'
    },
    {
      name: 'Riley Newman',
      date: '8:34 PM',
      action: 'Commented',
      target: "'Hi, please done this before tommorow'",
      actionType: 'comment'
    },
    {
      name: 'Erin Gonzales',
      date: '10:44 PM',
      action: 'Complete task',
      target: 'UI Revamp',
      actionType: 'completed'
    },
    {
      name: 'Pamela Wanda',
      date: '11:25 PM',
      action: 'Complete task',
      target: 'Clean Up Workspace',
      actionType: 'completed'
    },
    {
      name: 'Nicole Wyne',
      date: '8:25 PM',
      action: 'Complete task',
      target: 'Create Workspace',
      actionType: 'completed'
    }
  ];

  tasksList = [
    {
      name: 'Erin Gonzales',
      avatar: 'assets/images/avatars/thumb-1.jpg',
      due: '24 Mar, 2019',
      status: 'Medium',
      title: 'Define users and workflow',
      desc: 'A cheeseburger is more than sandwich'
    },
    {
      name: 'Virgil Gonzales',
      avatar: 'assets/images/avatars/thumb-4.jpg',
      due: '27 Mar, 2019',
      status: 'Medium',
      title: 'Change interface',
      desc: 'Efficiently unleash cross-media information'
    },
    {
      name: 'Nicole Wyne',
      avatar: 'assets/images/avatars/thumb-5.jpg',
      due: '29 Mar, 2019',
      status: 'Low',
      title: 'Create databases',
      desc: "Here's the story of a man named Brady"
    },
    {
      name: 'Darryl Day',
      avatar: 'assets/images/avatars/thumb-2.jpg',
      due: '2 Apr, 2019',
      status: 'High',
      title: 'Verify connectivity',
      desc: "Bugger bag egg's old boy willy jolly"
    },
    {
      name: 'Riley Newman',
      avatar: 'assets/images/avatars/thumb-6.jpg',
      due: '7 Apr, 2019',
      status: 'Medium',
      title: 'Prepare implementation',
      desc: 'Drop in axle roll-in rail slide'
    }
  ];

  ngOnInit(): void {}
}
```
3. Remove e.g. array so the code it looks like this
```lang-ts
import { Component, ViewChild, ElementRef, OnInit } from '@angular/core';
import { ThemeConstantService } from '../shared/services/theme-constant.service';

@Component({
  templateUrl: './dashboard.component.html',
  styles: [
    `
      @media only screen and (min-width: 992px) {
        .completion-chart {
          width: calc(100% - 330px);
        }
      }
    `
  ]
})
export class ProjectsDashboardComponent implements OnInit {
  constructor(private colorConfig: ThemeConstantService) {}
  themeColors = this.colorConfig.get().colors;
  blue = this.themeColors.blue;
  blueLight = this.themeColors.blueLight;
  cyan = this.themeColors.cyan;
  cyanLight = this.themeColors.cyanLight;
  gold = this.themeColors.gold;
  purple = this.themeColors.purple;
  purpleLight = this.themeColors.purpleLight;
  red = this.themeColors.red;
  transparent = this.themeColors.transparent;

  @ViewChild('completionChart', { static: true }) canvas: ElementRef;

  completionChartData: Array<any> = [
    {
      data: [30, 60, 40, 50, 40, 55, 85, 65, 75, 50, 70],
      label: 'Series A'
    }
  ];
  currentcompletionChartLabelsIdx = 1;
  completionChartOptions: any = {
    maintainAspectRatio: false,
    responsive: true,
    hover: {
      mode: 'nearest',
      intersect: true
    },
    tooltips: {
      mode: 'index'
    },
    elements: {
      line: {
        tension: 0,
        borderWidth: 2
      }
    },
    scales: {
      xAxes: [
        {
          gridLines: [
            {
              display: false
            }
          ],
          ticks: {
            display: true,
            fontColor: this.themeColors.grayLight,
            fontSize: 13,
            padding: 10
          }
        }
      ],
      yAxes: [
        {
          gridLines: {
            drawBorder: false,
            drawTicks: false,
            borderDash: [3, 4],
            zeroLineWidth: 1,
            zeroLineBorderDash: [3, 4]
          },
          ticks: {
            display: true,
            max: 100,
            stepSize: 20,
            fontColor: this.themeColors.grayLight,
            fontSize: 13,
            padding: 10
          }
        }
      ]
    }
  };
  completionChartColors;
  completionChartType = 'line';

  projectList = [
    {
      project: 'Mind Cog App',
      avatar: 'assets/images/others/thumb-1.jpg',
      status: 'Ready',
      tasks: '31',
      progress: 100
    },
    {
      project: 'Mill Estate',
      avatar: 'assets/images/others/thumb-2.jpg',
      status: 'In Progress',
      tasks: '56',
      progress: 76
    },
    {
      project: 'Eastern Sack',
      avatar: 'assets/images/others/thumb-3.jpg',
      status: 'In Progress',
      tasks: '21',
      progress: 87
    },
    {
      project: 'Fortier Studio',
      avatar: 'assets/images/others/thumb-5.jpg',
      status: 'In Progress',
      tasks: '18',
      progress: 68
    },
    {
      project: 'Indi Web',
      avatar: 'assets/images/others/thumb-6.jpg',
      status: 'Behind',
      tasks: '165',
      progress: 28
    }
  ];

  memberList = [
    {
      name: 'Erin Gonzales',
      img: 'assets/images/avatars/thumb-1.jpg',
      mail: 'erin.gon@gmail.com'
    },
    {
      name: 'Darryl Day',
      img: 'assets/images/avatars/thumb-2.jpg',
      mail: 'darryl.d@gmail.com'
    },
    {
      name: 'Marshall Nichols',
      img: 'assets/images/avatars/thumb-3.jpg',
      mail: 'marshalln@gmail.com'
    },
    {
      name: 'Virgil Gonzales',
      img: 'assets/images/avatars/thumb-4.jpg',
      mail: 'virgil14@gmail.com'
    },
    {
      name: 'Nicole Wyne',
      img: 'assets/images/avatars/thumb-5.jpg',
      mail: 'nicolew@gmail.com'
    },
    {
      name: 'Riley Newman',
      img: 'assets/images/avatars/thumb-6.jpg',
      mail: 'rileyn93@gmail.com'
    },
    {
      name: 'Pamela Wanda',
      img: 'assets/images/avatars/thumb-7.jpg',
      mail: 'pamelaw@gmail.com'
    }
  ];

  activityList = [
    {
      name: 'Virgil Gonzales',
      date: '10:44 PM',
      action: 'Complete task',
      target: 'Prototype Design',
      actionType: 'completed'
    },
    {
      name: 'Marshall Nichols',
      date: '10:44 PM',
      action: 'Complete task',
      target: 'Documentation',
      actionType: 'completed'
    },
    {
      name: 'Virgil Gonzales',
      date: '8:34 PM',
      action: 'Commented',
      target: "'That's not our work",
      actionType: 'comment'
    },
    {
      name: 'Pamela Wanda',
      date: '8:34 PM',
      action: 'Removed',
      target: 'a file',
      actionType: 'removed'
    },
    {
      name: 'Lilian Stone',
      date: '8:34 PM',
      action: 'Attached file',
      target: 'Mockup Zip',
      actionType: 'upload'
    },
    {
      name: 'Marshall Nichols',
      date: '10:44 PM',
      action: 'Complete task',
      target: 'UI Revamp',
      actionType: 'completed'
    },
    {
      name: 'Riley Newman',
      date: '8:34 PM',
      action: 'Commented',
      target: "'Hi, please done this before tommorow'",
      actionType: 'comment'
    },
    {
      name: 'Erin Gonzales',
      date: '10:44 PM',
      action: 'Complete task',
      target: 'UI Revamp',
      actionType: 'completed'
    },
    {
      name: 'Pamela Wanda',
      date: '11:25 PM',
      action: 'Complete task',
      target: 'Clean Up Workspace',
      actionType: 'completed'
    },
    {
      name: 'Nicole Wyne',
      date: '8:25 PM',
      action: 'Complete task',
      target: 'Create Workspace',
      actionType: 'completed'
    }
  ];

  tasksList = [
    {
      name: 'Erin Gonzales',
      avatar: 'assets/images/avatars/thumb-1.jpg',
      due: '24 Mar, 2019',
      status: 'Medium',
      title: 'Define users and workflow',
      desc: 'A cheeseburger is more than sandwich'
    },
    {
      name: 'Virgil Gonzales',
      avatar: 'assets/images/avatars/thumb-4.jpg',
      due: '27 Mar, 2019',
      status: 'Medium',
      title: 'Change interface',
      desc: 'Efficiently unleash cross-media information'
    },
    {
      name: 'Nicole Wyne',
      avatar: 'assets/images/avatars/thumb-5.jpg',
      due: '29 Mar, 2019',
      status: 'Low',
      title: 'Create databases',
      desc: "Here's the story of a man named Brady"
    },
    {
      name: 'Darryl Day',
      avatar: 'assets/images/avatars/thumb-2.jpg',
      due: '2 Apr, 2019',
      status: 'High',
      title: 'Verify connectivity',
      desc: "Bugger bag egg's old boy willy jolly"
    },
    {
      name: 'Riley Newman',
      avatar: 'assets/images/avatars/thumb-6.jpg',
      due: '7 Apr, 2019',
      status: 'Medium',
      title: 'Prepare implementation',
      desc: 'Drop in axle roll-in rail slide'
    }
  ];

  ngOnInit(): void {}
}
```

### Expected output for `git log`:  
`feat: remove array`

### Actual output for `git log`:
```
feat: remove array
    diff --git a/apps/sandbox/src/app/dashboard/dashboard.component.ts b/apps/sandbox/src/app/dashboard/dashboard.component.ts
    index deb66e2..b53de3d 100644
    --- a/apps/sandbox/src/app/dashboard/dashboard.component.ts
    +++ b/apps/sandbox/src/app/dashboard/dashboard.component.ts
    @@ -35,19 +35,6 @@ export class ProjectsDashboardComponent implements OnInit {
         }
       ];
       currentcompletionChartLabelsIdx = 1;
    -  completionChartLabels: Array<any> = [
    -    '16th',
    -    '17th',
    -    '18th',
    -    '19th',
    -    '20th',
    -    '21th',
    -    '22th',
    -    '23th',
    -    '24th',
    -    '25th',
    -    '26th'
    -  ];
       completionChartOptions: any = {
         maintainAspectRatio: false,
         responsive: true,
```

Does this issue occur when all extensions are disabled?: Yes

This is related to [this](https://github.com/microsoft/vscode/issues/51121) issue and with `VIM` the commit works. So its not the local git configuration.

The issue does not appear if only small parts (like properties) are deleted. I suspect that arrays are the problem.  
What looks suspicious is this colour for the bracket:
![vscode-git-bug](https://user-images.githubusercontent.com/1122134/76530506-1a648280-6474-11ea-8a4a-57e7f4f9c0b0.png)

**Comment by BernhardFuchs** [comment] 2020-03-14 02:04
I just saw `^M` at the end of the lines in a file of the same project and found [this stackexchange thead](https://unix.stackexchange.com/questions/17647/m-at-the-end-of-each-line-of-text-files-generated-under-windows).  
Some files of this project are part of a theme we bought on a marketplace and it seems they were edited on a windows machine.

**Comment by joaomoreno** [comment] 2020-04-01 09:19
Can you reproduce with `--disable-extensions`?

**Comment by BernhardFuchs** [comment] 2020-04-01 09:22
Yes, same with disabled extensions.

**Comment by bpasero** [comment] 2020-04-01 09:51
@BernhardFuchs I cannot reproduce, here is what I did based on your description:
* created an empty folder
* created a file with your contents
* committed that to git
* made the change as instructed by you
* ran `git log`

The output was:

![image](https://user-images.githubusercontent.com/900690/78123870-1e4e4980-740f-11ea-8619-5b52aac1ff3c.png)

So I see no issue with VSCode here and suggest you report this to git.

**Comment by BernhardFuchs** [comment] 2020-04-04 14:18
I don't have this issue when I use vim as editor so I assume it's something with VSCode but I also had a hard time reproducing it with a small sample.

For me the priority on this is not high, so feel free to close it.

**Closed** 2020-04-05 06:12 UTC
Labels: needs more info
