### ISSUE TITLE
drag and drop now copies instead of moving.

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#54500] opened 2018-07-17 18:29 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10

Steps to Reproduce:

1. select a block of text
2. drag the text to new location.
3. instead of moved, the text is now copied.

NOTE: even if you don't move the text, say you just wiggle the cursor, the text is still copied on same line!!!

Does this issue occur when all extensions are disabled?: Yes

**Comment by r3wt** [comment] 2018-07-19 21:10
@rebornix just wanted to report that the issue seems to have subsided since i upgraded to version `1.25.1`, if you want to go ahead and close this, you can and if it happens again i'll ping you here to ask to reopen the thread. Thank you for your hard work on this project, i appreciate you all.

**Comment by axefrog** [comment] 2018-07-24 19:13
I am using VS Code 1.25.1 and this issue still occurs for me. It's not that the issue has subsided, it's that it's intermittent, and doesn't appear to be triggered by any obvious pattern. Everybody loves a heisenbug...

**Comment by r3wt** [comment] 2018-07-24 19:56
@axefrog you are correct, i have noticed that the issue is occassionally still occuring. i only notice it when the app fails to compile because of the duplicate line.

**Comment by Kevin-He-DVHS** [comment] 2018-07-30 20:45
This is a duplicate of #35453. Please close this.

**Comment by rebornix** [comment] 2018-09-05 00:11
Let's track it in https://github.com/Microsoft/vscode/issues/35453 and I'll investigate with all the information provided here. Thank you everyone for your help.

**Closed** 2018-09-05 00:11 UTC
Labels: *duplicate, editor
