### ISSUE TITLE
IntelliSense suggestions are very easy to miss

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#122515] opened 2021-04-28 10:09 UTC
- VS Code Version: 1.55.2
- OS Version: macOS 11.2.3

Steps to Reproduce:

Open a VS Code instance with no extensions and default settings: `code --disable-extensions --user-data-dir temp .`

Create a new TypeScript file with this content:

```ts
declare const fn: (params: { myProp: string }) => void;

fn({   });
//   ^ cursor here
```

With the cursor in the specified position, press `ctrl+space`. As desired, `myProp` is the selected suggestion and appears at the top of the list.

![image](https://user-images.githubusercontent.com/921609/116384729-0a426a80-a810-11eb-97f2-f81fa586f876.png)

However, this behaviour changes as soon as we use a snippet. To demonstrate this: in the same file, create a new line and use a snippet. For example, type `async` and then trigger the suggestion for `async arrow function`.

![image](https://user-images.githubusercontent.com/921609/116384013-580aa300-a80f-11eb-8c2a-cd3f6251b09b.png)

Now place the cursor back inside of the `fn` function call as specified and press `ctrl+space`. 

https://user-images.githubusercontent.com/921609/116384233-90aa7c80-a80f-11eb-9e2b-f1e52442cf13.mov

The suggestion for `myProp` is nowhere to be seen. This is because the suggestion is at the top of the list and the list has been scrolled down to the recently used suggestion.

https://user-images.githubusercontent.com/921609/116385500-c13ee600-a810-11eb-9b53-203f46275b60.mov

However, this is really not obvious, especially considering the scroll bar is so discrete and disappears completely after a few seconds. The user might not even realise the list has been scrolled down.

To address this, I would like to suggest a few things. Ideally these suggestions would alter the default behaviour, since this is an accessibility issue, but at the very least they could be configured using new settings.

- Disable fading scroll bars inside of the suggestions list. Related: https://github.com/microsoft/vscode/issues/35454
- When the selected suggestion isn't at the top of the list but is close to the top, keep the list scrolled to the top when it's opened rather than scrolling down to the selected suggestion. Note this isn't the same thing as `"editor.suggestSelection": "first"` because that changes the suggested selection.
- When determining the suggestion to select by default, give IntelliSense suggestions higher priority than recently used. We already have a `editor.suggestSelection` setting but it doesn't have an option for this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2021-04-28 11:13
/duplicate of https://github.com/microsoft/vscode/issues/77453

**Closed** 2021-04-28 11:13 UTC
Labels: *duplicate, suggest
