### ISSUE TITLE
Automatically updating imports breaks call to require()

### ISSUE THREAD

**Issue by uhyo** [Microsoft/vscode#72555] opened 2019-04-18 13:42 UTC
- VSCode Version:
```
バージョン: 1.32.3
コミット: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
日付: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.10-040910-generic
```

```
Version: 1.34.0-insider
Commit: fe31e7bfb96b242094332bd324b88f4000b42b27
Date: 2019-04-18T06:50:15.144Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.10-040910-generic
```
- OS Version: Ubuntu 16.04 LTS

**Steps to Reproduce**:

1. Prepare the below structure of files:

```
+-- index.js
|
+-- foo/
    |
    +-- bar.js
    |
    +-- sub/
```
where `bar.js` is empty and `index.js` is:

```js
const bar = require('./foo/bar.js');
```

2. Move `foo/bar.js` to `foo/sub/bar.js`
3. VSCode asks you to whether automatically update imports
4. Select Yes

**Expected behavior**: the call to `require` in `index.js` becomes `require('./foo/sub/bar.js')`

**Actual behavior**: `require('./foo/sub/bar.js/index.js')` 

Notably, the problem disappears if the call is changed to `requrire('./foo/bar')`.

**Does this issue occur when all extensions are disabled?**: Yes

**Comment by mjbvz** [comment] 2019-04-18 17:31
Duplicate of https://github.com/Microsoft/TypeScript/issues/30550

**Closed by mjbvz** 2019-04-18 17:31 UTC
Labels: javascript
