### ISSUE TITLE
TS: quick outline is no longer showing a method implementation

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18030] opened 2017-01-03 09:37 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (d384271ffb5655cee1ddf8f93f51cd892ee2cc40, 2017-01-03T07:05:16.958Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|close-all|benjpas|1.0.2|
|vscode-eslint|dbaeumer|1.2.0|
|tslint|eg2|0.7.1|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|extension-manifest-editor|ms-devlabs|0.1.3|
|vscode-open-in-github|ziyasal|1.2.3|

---

Steps to Reproduce:

1. open windows.ts (`src/vs/code/electron-main/windows.ts`)
2. quick outline and try to find the `open` method

=> you only see one from the interface, not the one that actually implements it

**Comment by mjbvz** [comment] 2017-01-03 19:33
This looks like it is because we are still using TypeScript 2.0.3 to build vscode itself. I confirmed that this has been fixed in TS 2.1.4. 

@bpasero Please let me know if you are seeing this with a new TS version. Also, should I look into bumping the TS version we use inside VSCode itself?

**Comment by bpasero** [comment] 2017-01-04 06:26
@mjbvz my understanding is that we ship VS Code with 2.0.3 so as a user I cannot change the TS version easily. I do not feel qualified to answer your last question about TS. Reopening until a fix has landed.

**Comment by mjbvz** [comment] 2017-01-04 17:37
@bpasero The TS extension bundles TypeScript 2.1.4, but we allow users to easily point to any version of typescript they like using the `typescript.tsdk` property. For VSCode, we currently build using TS 2.0.3 and point the tsdk to this local install of TypeScript.

The correct fix here is to use a newer version of TypeScript. This is not something that we can fix on our side and the the TS team has already fixed it.  You can check if this is indeed fixed by installing TypeScript 2.1.4+ somewhere locally, and pointing the VSCode workspace `typescript.tsdk` setting to this path.

**Closed by mjbvz** 2017-01-04 17:37 UTC
Labels: bug, typescript

**Comment by mjbvz** [comment] 2017-01-04 17:47
Yes, I tried upgrading VSCode to use TypeScript 2.1.4, but there are a few compiler bugs that break the tests (and possibly the product too). I'll follow up with the TS team to make sure this gets fixed. I believe the bug has been fixed in the current TS 2.2 preview builds, but I'll see if they plan on taking it into the TS 2.1.5 as well
