### ISSUE TITLE
#if and #endif macros folding cannot be done when the code were not intended!

### ISSUE THREAD

**Issue by konosubakonoakua** [Microsoft/vscode#69935] opened 2019-03-07 08:02 UTC
Just like this
![cannot fold](https://user-images.githubusercontent.com/42881610/53941108-3a8b9400-40f2-11e9-82e7-2ec3f8b028e9.png)
after intended:
![can fold but with tab added](https://user-images.githubusercontent.com/42881610/53941144-4d9e6400-40f2-11e9-8e8f-e59858197dd5.png)
HOW CAN I FOLD THE MACRO WITHOUT INTENDING THE CODE?

**Comment by gjsjohnmurray** [comment] 2019-03-07 09:36
I think [this article](https://code.visualstudio.com/docs/editor/codebasics#_folding) may explain what you're seeing:

> Folding ranges are by default evaluated based on the indentation of lines. A folding range starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.
> 
> Since the 1.22 release, folding ranges can also be computed based on syntax tokens of the editor's configured language. The following languages already provide syntax aware folding:
> 
>     Markdown, HTML, CSS, LESS, SCSS and JSON
> 

What language is your file being handled as?

**Comment by konosubakonoakua** [comment] 2019-03-07 11:37
> I think [this article](https://code.visualstudio.com/docs/editor/codebasics#_folding) may explain what you're seeing:
> 
> > Folding ranges are by default evaluated based on the indentation of lines. A folding range starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.
> > Since the 1.22 release, folding ranges can also be computed based on syntax tokens of the editor's configured language. The following languages already provide syntax aware folding:
> > ```
> > Markdown, HTML, CSS, LESS, SCSS and JSON
> > ```
> 
> What language is your file being handled as?

thanks for your reply, i'm using pure c in my project.

**Comment by gjsjohnmurray** [comment] 2019-03-07 12:12
So your issue is probably a duplicate of #66404. That has been closed with a reference to https://github.com/Microsoft/vscode-cpptools/issues/407. Unless the Language Server VSCode is using for your C files gets enhanced to implement a [FoldingRangeProvider](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider) the best you can expect from VSCode is indent-based folding.

**Closed** 2019-03-08 05:08 UTC
Labels: editor-folding
