### ISSUE TITLE
Underscore not shown in filenames in the ls output in terminal

### ISSUE THREAD

**Issue by varunmuriyanat** [microsoft/vscode#130040] opened 2021-08-03 13:24 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Ubuntu 21.04

Steps to Reproduce:

1. Open terminal in vscode
2. Type ls -l
3. The output doesn't show underscores in the filenames listed. A space is shown instead. Underscores in the directory names are shown though.

VS Code version details copied from About window:
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.11.0-25-generic

![ls output from vscode terminal](https://user-images.githubusercontent.com/57871337/128022919-5469e88d-4488-4d20-b3f9-9ca271651010.png)

![Same output from normal terminal](https://user-images.githubusercontent.com/57871337/128022938-a864ff4f-3d9b-44b4-a5ea-01d65f721bbd.png)

**Comment by IllusionMH** [comment] 2021-08-03 13:33
/duplicate of #123077

Fix should be available in Insiders builds https://code.visualstudio.com/insiders/ and in upcoming stable release soon™

**Closed** 2021-08-03 13:34 UTC
Labels: *duplicate
