### ISSUE TITLE
Suggestion should align to bottom when it's above the cursor

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#26493] opened 2017-05-11 22:06 UTC
- VSCode Version: 1.13-Insiders
- OS Version: macOS

![suggestion](https://cloud.githubusercontent.com/assets/876920/25973993/598052d6-365b-11e7-827e-200da3a41b5d.gif)

**Comment by ramya-rao-a** [comment] 2017-05-15 01:42
Duplicate of #26416

**Closed by ramya-rao-a** 2017-05-15 01:42 UTC
