### ISSUE TITLE
No cross file undo (when file name changes?)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#91380] opened 2020-02-25 13:59 UTC
re #91248

* open java-8 dev container
* in `AppTest.java` add a reference to `App`
* open both files side by side, reload
* rename `App` to `App3`
* undo
* 🐛 only one editor is undone, no message, no x-file undo

**Comment by alexdima** [comment] 2020-02-26 15:53
@jrieken I am seeing a notification when undoing. This seems to be the same case as #91379 or is perhaps a duplicate of #77190 , since the rename is not limited to textual changes, it also includes a file rename:

![Kapture 2020-02-26 at 16 47 52](https://user-images.githubusercontent.com/5047891/75361591-d68c4d80-58b7-11ea-819e-9eb43615d4e1.gif)

I am sorry I should have probably specified better what is implemented. We now support cross-file undo of textual edits if the text buffers have not been disposed in the meantime. I did not implement undo for file edits, that still needs to be implemented.

I suggest to continue tracking in #77190

**Closed by alexdima** 2020-02-26 15:53 UTC
Labels: undo-redo
