### ISSUE TITLE
Markdown image doesn't show correctly

### ISSUE THREAD

**Issue by moyamoyarua** [Microsoft/vscode#46497] opened 2018-03-25 14:59 UTC
- VSCode Version: `1.21.1`
- OS Version: `Windows 10 1709`

Steps to Reproduce:

1. file tree
    ![](https://i.imgur.com/0MwXfM9.png)
2. img.md
    ![](https://i.imgur.com/6YICrtm.png)
3. Preview
    ![](https://i.imgur.com/eb6vh5S.png)

Does this issue occur when all extensions are disabled?: `Yes`

**Comment by mjbvz** [comment] 2018-03-26 19:05
Duplicate of #46448

**Closed by mjbvz** 2018-03-26 19:05 UTC
Labels: markdown
