### ISSUE TITLE
Trouble with auto import React component when using vscode 1.28

### ISSUE THREAD

**Issue by huynguyend191** [Microsoft/vscode#60631] opened 2018-10-11 12:36 UTC
I don't know why auto import suggestion doesn't work as it used to in VSC 1.26. For example, in 1.28 I want to auto import component, as I hit enter when the suggestion list appears, it only show this:

`<import('./components/CourseList').CourseList`

instead of `<CourseList />` and import line in 1.26

**Comment by mjbvz** [comment] 2018-10-11 16:58
Duplicate of https://github.com/Microsoft/TypeScript/issues/27317

**Closed by mjbvz** 2018-10-11 16:58 UTC
Labels: javascript
