### ISSUE TITLE
It's easy to use "Multiple cursor" ,but autocomplete not working correctly  & how to remove one of the cursor ?

### ISSUE THREAD

**Issue by manglobe** [Microsoft/vscode#25964] opened 2017-05-05 01:50 UTC
If I want to write same code in several place  , I will use alt+click to generate multiple cursor . But when I press 'tab' to use autocomplete , it can't works.

And if I generate a cursor in a wrong place，I don't know how to remove it , I can only come back again .

I read the Official documents [https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor](url) , but I just find how to make multiple cursor.

**Comment by alexandrudima** [comment] 2017-05-19 16:18
`ctrl+u` will undo the addition of a cursor. It is a much more general command than that, `ctrl+u` is cursor undo, meaning it will bring the cursors in the previous state they had. The cursor undo/redo stack is cleared when editing the buffer.

For the suggestion question, I refer you to @jrieken

**Comment by jrieken** [comment] 2017-05-22 07:43
> . But when I press 'tab' to use autocomplete , it can't works.
@manglobe Please clarify this

**Comment by manglobe** [comment] 2017-05-23 01:22
@jrieken For Example I want write several 'a' tag in html :
1. I used alt+click to generate multiple cursor ;
2. Then I pressed  ‘a’ , every cursor writed an 'a' in the document , and so far so good ;
3. I pressed 'tab' ,  I  wished  every cursor will write ‘<a href=""></a>’  , but only the first one do it .


![1](https://cloud.githubusercontent.com/assets/19583202/26334515/2f873490-3f98-11e7-8d82-41a4790f91f7.gif)

Another scene:
1. I used alt+click to generate multiple cursor ,then pressed 'a' ;
2. I removed all the multiple cursor ,and then generate them again ;
3 I pressed 'tab' , this time no one works .

![2](https://cloud.githubusercontent.com/assets/19583202/26334516/2fcb2506-3f98-11e7-86f8-b41670751988.gif)

Mybe my english was too awful . So I uploaded two gifs .  _(:3 」∠)_

**Comment by jrieken** [comment] 2017-05-23 07:10
This is emmet which doesn't support multiple cursors, yet

**Comment by ramya-rao-a** [comment] 2017-05-23 15:54
Closing as duplicate of #9571

@manglobe We will have multi cursor emmet expansions in the upcoming release.
Please follow #9571 for when it will be available in the Insiders build

**Closed by ramya-rao-a** 2017-05-23 15:54 UTC
Labels: emmet

**Comment by ramya-rao-a** [comment] 2017-06-01 05:17
@manglobe 

Set `emmet.useNewEmmet` to `true` (in the latest Insiders dated 6/1 or above and eventually in the stable release of 1.13 and higher) to get emmet abbreviation expansions in the suggestion list.
This will work in multi cursor too

For details on this setting read https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464
