### ISSUE TITLE
Find widget doesn't leave enough room when opened as find/replace

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28054] opened 2017-06-05 17:59 UTC
- Open find/replace widget with cmd+opt+f
- Scroll up
- Not enough room at the top

Works when the find widget is expanded

![jun-05-2017 10-57-48](https://cloud.githubusercontent.com/assets/323878/26796334/f3983b8c-49dd-11e7-9166-9cabc99f980c.gif)

**Comment by Simran-B** [comment] 2017-12-22 10:24
Can't reproduce in v1.19.1 on Windows 10. Seems to work correctly:

https://youtu.be/PupNU_vyZn4

**Comment by rebornix** [comment] 2018-09-18 19:01
Duplicate of https://github.com/Microsoft/vscode/issues/27520

**Closed** 2018-09-18 19:01 UTC
Labels: *duplicate, bug, editor-find
