### ISSUE TITLE
Text cursor and VSCode insertion bar out of synch

### ISSUE THREAD

**Issue by MAGOO56** [microsoft/vscode#111058] opened 2020-11-20 21:13 UTC
Issue Type: <b>Bug</b>

I'm unsure of the exact cause. I'm a low vision user and have various visual accesibility features enabled. In particular, I have configured the settings:

"Ease of Access" -> "Text Cursor" as follows:
* Turn on text cursor indicator - Enabled
* Change text cursor size - 3 (50%)
* Suggested text cursor colors - Turquoise
* Change text cursor thickness - 6 (26%)

"Ease of Access" -> "Magnifier"
* Turn on magnifier - Enabled
* Change zoom level - 500%
* Start magnifier after sign-in - Checked
* Start magnifier before sign-in for everyone - Checked
* Smooth edges of images and text - Checked
* Invert colors - Not checked
* Choose a view - Full screen
* Have magnifier follow:
    * Mouse pointer - Checked
    * Keyboard focus - Checked
    * Text cursor - Checked
    * Narrator cursor - Checked
* Keep the mouse pointer - Centered on the screen
* Keep the text cursor - Within the edges of the screen
* Choose a modifier key - Control + Alt

I use NVDA (Non Visual Desktop Access) as my screen reader instead of Narrator.
I have two 4K monitors in dual screen, both at 

I've noticed this in all versions of VSCode that I've used over the past year. When I first launch VSCode, the position of the two appear to be in synch. But as I user the keyboard to move thru the text the two cursors get out of synch.
* If I move to the end of the line, the VSCode text cursor is at the end of the line, but the system text cursor (with the indicator set) will be way to the right side (aout twice where it should be).
* If I move down in the file, again the VSCode text cursor is where it should be, but the system text cursor is way below this point (about twice as far).

Since I have following the system text cursor/keyboard focus set, the screen moves to follow the system text cursor which means the area of interest quickly moves out of view.

If I zoom out to 100%, the two cursors still stay out of synch. If I click where I want to be, the system cursor is still out of synch.

So far, this is the only program/App where I've experienced this behaviour.

Thanks for looking into this issue.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.06GB free)|
|Process Argv|C:\Users\rmcge\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json --crash-reporter-id 1635da57-a4e5-40dc-bc82-f0f9a99b97d2|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.51.4
powershell|ms-|2020.6.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment] 2020-11-23 08:37
@MAGOO56 thanks a lot for filling the issue, however this seems like a duplicate of https://github.com/microsoft/vscode/issues/105558

I plan to investigate more into that issue and hopefully find a solution or a workaounrd.
If that issue does not sound like yours let us know and I will reopen this one

Thanks!

**Closed by isidorn** 2020-11-23 08:37 UTC
