### ISSUE TITLE
"find all references" previously highlighted "find all references" word remains highlighted

### ISSUE THREAD

**Issue by gujiman** [Microsoft/vscode#17346] opened 2016-12-15 21:57 UTC
#- VSCode Version: 1.8.0
- OS Version: win 7

Steps to Reproduce:

1. Open any type of file where by a keyword may be used in multiple files. I.e we have 2 Files and both have keywords used in both files:

File 1:
----------------------------------------------------

function a(){
return 1;
}
b();

----------------------------------------------------
File 2:
----------------------------------------------------

function b(){
return 1;
}
a();

----------------------------------------------------

2. Now select a() from file 1 and right click and select "find all references" to open the "find all references" box.
3. You have to toggle both files in the "find all references" box (do it a couple of times).
4. Close the "Find in File" box.
5. Now select b() and repeat step 2 and 3. As you will see that the previously highlighted b() is still highlighted.

**Comment by rebornix** [comment] 2016-12-15 23:41
![search-highlight](https://cloud.githubusercontent.com/assets/876920/21246325/cdbbde24-c2dc-11e6-9da8-19507103a078.gif)


@gujiman can you help confirm above gif represents what you are describing? Are you saying that in step 5, `b()` is still highlighted in the sidebar?

cc @roblourens it looks like that the search sidebar is not cleaned even though that it's hidden before we run `Find in files`

**Comment by gujiman** [comment] 2016-12-18 04:06
hi,

Im really sorry about this but the problem was in "find all references" feature not "find in files" feature!

<img src="https://cloud.githubusercontent.com/assets/9681295/21291425/f0be1814-c4d6-11e6-985e-0476613246f2.gif">

**Comment by gujiman** [comment] 2016-12-19 16:12
@roblourens just wondering why the issue was closed. I have sent the following screenshot which shows the bug:

<img src="https://cloud.githubusercontent.com/assets/9681295/21291425/f0be1814-c4d6-11e6-985e-0476613246f2.gif">

**Comment by rebornix** [comment] 2016-12-19 17:41
@gujiman no worries. it' a valid issue about Find all reference.

**Comment by roblourens** [comment] 2016-12-20 02:54
Sorry for closing it, I misread

**Comment by gujiman** [comment] 2016-12-20 14:02
no probs. Brilliant software by the way

**Comment by rebornix** [comment] 2016-12-22 01:20
@gujiman excellent finding actually, it's a bug in the reference widget. I like your reproduce steps.

**Closed** 2016-12-28 11:45 UTC
Labels: bug, editor
