### ISSUE TITLE
Emmet problem in multi line edit and intellisense list

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#20486] opened 2017-02-11 22:21 UTC
1) in multi line edit emmet not working at all.

2) when i press tab it set first item of intellisense list , we can ignore intellisense list when tab pressed because in speed write it very bad.

![ks](https://cloud.githubusercontent.com/assets/17777237/22857930/ace9cc6a-f0b8-11e6-9751-0b6216aa64d1.gif)

**Comment by ramya-rao-a** [comment] 2017-02-11 23:22
Closing this as duplicate of #9571

**Closed by ramya-rao-a** 2017-02-11 23:22 UTC

**Comment by ramya-rao-a** [comment] 2017-06-01 05:18
@pixieaka 

Set `emmet.useNewEmmet` to `true` (in the latest Insiders dated 6/1 or above and eventually in the stable release of 1.13 and higher) to get emmet abbreviation expansions in the suggestion list.
This will work in multi cursor too

For details on this setting read https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464
