### ISSUE TITLE
US International keyboard select detect does not work - mac - Mojave

### ISSUE THREAD

**Issue by aeciolevy** [Microsoft/vscode#60646] opened 2018-10-11 15:08 UTC
Issue Type: <b>Bug</b>

When I select a word and press singlequotes or double quotes it erase the word
![vscode-bug](https://user-images.githubusercontent.com/16165803/46814068-cd372b00-cd2c-11e8-8bec-09756b3d923d.gif)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|-psn_0_45067|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-debug|Uni|1.3.0
Bookmarks|ale|9.1.0
project-manager|ale|9.0.1
code-gnu-global|aus|0.2.2
phpserver|bra|2.4.6
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
eppz-code|epp|1.2.41
vsc-material-theme|Equ|2.4.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
vscode-styled-components|jpo|0.0.22
unity-snippets-modified|lio|0.4.0
dotenv|mik|1.0.1
python|ms-|2018.9.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
elmmet|nec|1.0.1
polacode|pnp|0.2.2
subtle-brackets|raf|3.0.0
vscode-icons|rob|7.27.0
code-settings-sync|Sha|3.1.2
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.9.0

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment] 2018-10-16 12:06
Duplicate of #34407

**Closed by alexandrudima** 2018-10-16 12:06 UTC
