### ISSUE TITLE
[emmet] don't provide a proposal on 'dot' only

### ISSUE THREAD

**Issue by JasonWoof** [microsoft/vscode#103253] opened 2020-07-24 15:13 UTC
- VSCode Version: 1.47.2
- OS Version: debian unstable

Steps to Reproduce:

1. Define a global snippet with prefix "."
2. In an html file, press the period key, then tab

Expected behavior: get the snippet body you defined.

Actual result: ``<div class=""></div>``

I believe this is triggering emmet by accident. It appears that the intended use of this emmet snippet is for typing something like ".foo" and pressing tab. Without the "foo" part (the class name) the snippet is net useful.

Please fix this emmet snippet so it doesn't match a period by itself.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JasonWoof** [comment] 2020-07-24 15:20
".." and "..." and "...." etc also expand to ``<div class=""></div>``. Please remove these too.

**Comment by ArturoDent** [comment] 2020-07-26 01:31
This setting would put your snippet `.` first in the suggestions, so that `.+tab` would insert your user-defined snippet and not the emmet abbreviation.

**Comment by JasonWoof** [comment] 2020-07-26 01:38
@ArturoDent you have a way of prioritizing snippets above emmet abbreviations? What is it? You said "this setting" but then didn't mention a setting.

I fiddled with several settings in an attempt to get my snippet to be top priority and didn't manage it.

**Comment by ArturoDent** [comment] 2020-07-26 01:55
Sorry, fixed above.

**Comment by JasonWoof** [comment] 2020-07-26 01:57
Thanks!

**Comment by aeschli** [comment] 2020-08-11 15:47
Ok to close?

**Comment by JasonWoof** [comment] 2020-08-12 03:23
Only close the bug if it's been fixed.

**Comment by aeschli** [comment] 2020-08-12 18:29
What you see is the intended behavior. Emmet has a proposal for `.` and I would not say that its not useful.
As it matches the prefix the most, is ordered on top, and is used when you press tab.

![image](https://user-images.githubusercontent.com/6461412/90052737-deab3e80-dcd9-11ea-96a6-1c91ebe6e4fd.png)

`"editor.snippetSuggestions": "top"` lets you order snippets on top, above all other code completions.

What is your request? That emmet no longer provides a completion for `.` ?

**Comment by JasonWoof** [comment] 2020-08-13 00:21
There's no way that this is intended. Nobody decided that `.` and `..` and `...` and `....` and `....` followed by tab should produce a tag with `class=""`. The class attribute is not inherited, so `class=""` would only be used it the most contrived and ill-advised scenario.

The intention was obviously a single period followed by a valid class name.

Emmet should not bind to `.` or `..` or `...`, etc because it doesn't do anything useful when you press tab after those things (it produces code that nobody would ever want, and makes it more difficult for people to make a snippet with those names.)

When I type `...` then press tab I want the ellipsis unicode character.

My request is that the emmet feature fix it's matching pattern so it doesn't eat one or more periods without a class name following.

**Comment by rzhao271** [comment] 2020-10-05 21:17
I think single dot should stay due to #70469
Double and triple dots shouldn't be a thing parsed by Emmet, though.

> When I type ... then press tab I want the ellipsis unicode character.

@JasonWoof is there some editor that currently provides this support?

**Comment by JasonWoof** [comment] 2020-10-06 16:37
I'm ok with single dot being expanded into something useful, eg ``<div>|</div>`` or ``<div class="|"></div>``

I made this bug report because the emmet feature was making it difficult to make snippets like "." -> "·" and "..." -> "…" without providing any benefit.

If emmet is doing something useful with any of those, then it's fine to do that. Emmet should stop hogging prefixes that it doesn't build useful html from.

@rzhao271 I would think any decent snippets feature in any editor could expand "..." to "…". I've done this with ultisnips in vim and I can do it in vscode with the built in snippets feature now that I turned off emmet.

**Comment by rzhao271** [comment] 2020-11-06 18:16
Hm, doesn't seem like Emmet custom snippets support . or ...
Closing this as a wont-fix since I feel Emmet's parser (upstream) would have to change a bunch to accommodate this.

Workaround for now is to use VS Code snippets and set `"editor.snippetSuggestions": "top"`, as @ArturoDent mentioned above.

**Closed by rzhao271** 2020-11-06 18:16 UTC
Labels: emmet, feature-request
