### ISSUE TITLE
.ipynb files can't open, error loading webview, webview fatal error

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#158943] opened 2022-08-23 17:24 UTC
Type: <b>Bug</b>

When trying to open an ipynb file, none of the webview loads. UI elements such as breadcrumbs and the +code/markdown, >Run All will still render, however the notebook will not. 

<img width="786" alt="image" src="https://user-images.githubusercontent.com/12552271/186224599-39b1faab-f9e6-4beb-b20e-df99cfe8f5c8.png">

<img width="745" alt="image" src="https://user-images.githubusercontent.com/12552271/186224681-ddb940f2-7737-40fd-b137-f1540c685615.png">

VS Code version: Code - Insiders 1.71.0-insider (d5104dc1894e4a78b600662bf8958c7a2b9286a7, 2022-08-23T15:24:12.374Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.34GB free)|
|Process Argv|--crash-reporter-id 62122f1b-5534-43ca-aa21-fca29c482163|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.8.0
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.13.12341009
vscode-pylance|ms-|2022.8.31
jupyter|ms-|2022.8.1002371040
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52cf:30549188

```

</details>

**Comment by mjbvz** [comment] 2022-08-23 19:09
Duplicate of #122951

**Closed by mjbvz** 2022-08-23 19:09 UTC
