### ISSUE TITLE
Windows: file renamed case issues

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#49285] opened 2018-05-05 23:21 UTC
I'm on the latest code insiders on windows 10.
Didn't find the issue related.

I have an issue with one of my files. First it was called `transitBlock.ts`, then I renamed it in to `TransitBlock`, actually on windows NTFS they are the same files. Now during the work with vscode I can actually open both files (both files are shown in recently opened search), and sometimes it actually loads old an old version of the code and breaks everything in current code. I can not fixate more accurate details what is going on with the erros and how the code becames broken, but the situation when I see both files in search on Windows in not normal anyway.

![image](https://user-images.githubusercontent.com/736697/39668325-2e5a95e0-50e4-11e8-9ad1-5c0f60e39b69.png)

**Comment by bpasero** [comment] 2018-05-07 04:08
Duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2018-05-07 04:08 UTC
