### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#95533] opened 2020-04-17 14:24 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (tsserver.js:112241:13)
    at Object.releaseDocument (tsserver.js:112236:20)
    at tsserver.js:135319:45
    at Object.forEach (tsserver.js:167:30)
    at Proxy.dispose (tsserver.js:135318:20)
    at InferredProject.Project.close (tsserver.js:139542:38)
    at InferredProject.close (tsserver.js:140420:40)
    at ProjectService.removeProject (tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.45.0-insider (a3083e58e2a9e77f60e531acaa32e18527ae8439, 2020-04-17T08:08:39.508Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_2568819|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|1.4.2
Bookmarks|ale|11.1.0
project-manager|ale|10.11.0
ng-template|Ang|0.901.2
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.3
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.4.0
todo-tree|Gru|0.0.172
ecdc|mit|1.3.0
HTMLHint|mka|0.6.0
theme-monokai-pro-vscode|mon|1.1.15
vscode-scss|mrm|0.9.0
js-debug-companion|ms-|1.0.0
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
angular2-inline|nat|0.0.17
angular-console|nrw|11.1.3
angular-component-extension|oni|0.0.14
vscode-versionlens|pfl|0.25.0
quicktype|qui|12.0.46
format-html-in-php|rif|1.6.2
code-settings-sync|Sha|3.4.3
rewrap|stk|1.9.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.1.1
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.8.0

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-04-17 19:34
Duplicate of microsoft/TypeScript#37500 (through #93364)

**Closed by mjbvz** 2020-04-17 19:34 UTC
