### ISSUE TITLE
'Your local changes would be overwritten by checkout' but I don't have local changes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#161610] opened 2022-08-08 19:44 UTC
Here's what happened:

- I had some local changes
- I checked out out a PR through the extension
- It was a shallow clone (so I saw a single commit with no history), and I saw this error in the log which is probably from that:

```
[Debug 1659987519.693s] Unshallowing failed: Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "DirtyWorkTree",
  "gitCommand": "pull",
  "stdout": "",
  "stderr": "error: Cannot pull with rebase, you have unstaged changes.\nerror: please commit or stash them.\n"
}. Falling back to git pull
```

- Opened another PR and saw the same
- Stashed the changes, so now there are no local changes
- Trying to open another PR, but I get the warning

I see https://github.com/microsoft/vscode-pull-request-github/issues/2529 but looks like there was no resolution

Full log:
[7-GitHub Pull Request.log.zip](https://github.com/microsoft/vscode-pull-request-github/files/9284563/7-GitHub.Pull.Request.log.zip)

After reloading the window, I was able to checkout a PR with no problem.

**Comment by lszomoru** [comment] 2022-12-12 13:03
@alexr00, I remember we spoke about this in the past but I don't think we were able to track down the root cause? 
Do you still have a repro for this? If not, can we go ahead and close the issue until we have a repro to debug this?

**Comment by alexr00** [comment] 2022-12-14 13:22
I don't have a repro, but I did have the state updating issue just yesterday. I was making 1 commit very 1-2 minutes for 20-30 minutes. I just tried to reproduce it now and I can't though. It seems to be tied to their being lots of either git or file watching notifications in some short period of time. 

Since I can't repro feel free to close.

**Closed** 2022-12-14 15:02 UTC
Labels: bug, git
