### ISSUE TITLE
"Configure Default Build Task" (Typescript) does not work as expected

### ISSUE THREAD

**Issue by onlineservices283418** [Microsoft/vscode#31527] opened 2017-07-27 09:06 UTC
- VSCode Version: 1.14.2
- OS Version: Windows 10 Pro 1703 15063.483

Steps to Reproduce:

1. Install typescript:
`npm install typescript --save-dev`.

2. Create `tsconfig.json ` in the project's root directory:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "./bld",
        "rootDir": "./",
        "strict": true,
        "alwaysStrict": true,
        "moduleResolution": "node"
    }
}
```
3. Create `tasks.json` in `./.vscode`:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "presentation": {
                "echo": true,
                "reveal": "never",
                "focus": false,
                "panel": "shared"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
4. Create `test.ts` in the project's root directory:
`console.log("Hello, world!");`

5. Open `test.ts` in VS Code editor tab. Press `Ctrl+Shift+B`. Despite isDefault is set to true and 'tsconfig.json' is explicitly specified in `tasks.json`, VS Code still asks to choose default build task: `tsc: build tsconfig.json recently used tasks`. When I press `Ctrl+Shift+B` in the context of other editor tabs, e. g. `tsconfig.json`,  confirmation is not required.

npm tasks work as expected, i. e. I get no additional confirmations if `isDefault: true`.

Reproduces without extensions: Yes

**Comment by Patman64** [comment] 2017-07-30 02:59
Having the same issue here, also on 1.14.2.

**Comment by dbaeumer** [comment] 2017-08-03 13:57
This is caused by https://github.com/Microsoft/vscode/issues/31977. I am closing as a dup. The reason is that I get two identical task and then treat both as a build task. They get then de-dup in the picker.

**Closed by dbaeumer** 2017-08-03 13:57 UTC
Labels: bug, tasks
