### ISSUE TITLE
Search in csv through workspace using in-built search sidebar, highlightes incorrect result in csv

### ISSUE THREAD

**Issue by Litetook** [microsoft/vscode#126928] opened 2021-06-22 17:40 UTC
Steps to repro:
1) Create CSV file with comma separator. For reproducing, I used a file with 2 columns and more than 1000 rows. One of the value should be link, which starts with http. In my case, it is the second value.
2) Copy any value (not the link) between commas from this CSV (you can do it on any row).
3) Then save this file, close it and close vs code.
4) Open vs code, open your workspace, which contains this CSV file.
5) Open search on the left panel and try to find copied value in the workspace.
6) Results column under search box will show you the correct result of finding, but if you click on the result to open the needed file, highlighted field in CSV will be incorrect (it does not match your copied value and result in results sidebar).
This issue has been reproduced on two different PCs

**Comment by Litetook** [comment] 2021-06-22 18:28
![Code_rslk1eA8A2](https://user-images.githubusercontent.com/48100814/122979854-9217a180-d387-11eb-85c2-a26fd0aaeb75.png)

**Comment by roblourens** [comment] 2021-06-22 18:47
Is it possible that this file has some CR-only line endings (not LF, CRLF)? Can you share the file?

**Comment by Litetook** [comment] 2021-06-22 18:51
Sorry, I can not provide the file due to the security policies of my company. 
Can I share any other details? Maybe some attribute or any other information.

**Comment by Litetook** [comment] 2021-06-22 18:57
> Is it possible that this file has some CR-only line endings (not LF, CRLF)? Can you share the file?
I use LF to start a new line when exporting information from Python into csv.

**Comment by roblourens** [comment] 2021-06-22 19:01
You could replace all the sensitive info, see if the problem still occurs and send me that file.

Or, you can try to narrow down the problem some more. Does it happen if the search match is on the first line? Second line? At some point you might find the line in the file that messes up the result ranges.

**Comment by Litetook** [comment] 2021-06-22 20:54
I forgot to mention, if I see the incorrect result in my file, close it, and then re-open this file - the issue disappears and I see the true result of the search.

"You could replace all the sensitive info, see if the problem still occurs, and send me that file."
Looks like an issue connected with the link combinations from the file. If links are the same, the problem disappears.

I also found out that in every case value, for which I am looking for, contains  _ symbol, and I am using a part after this symbol, but before the comma. (see screenshot)
Also, I see that vs code highlights the correct order of symbols, but in one line above than needed. You can see this in the screenshot as well. 

Now I am looking for a way to provide you file, cause if I totally change or delete the links from the file issue is gone.

It does not happen on the first or second or on the fifth line. In my case, I reproduced it on line 1881, can not check all of them.

**Comment by Litetook** [comment] 2021-06-22 21:25
Try to find us8
![image](https://user-images.githubusercontent.com/48100814/123001388-31e12980-d3a0-11eb-9bd3-886e9bee1805.png)

file attached.
[test.zip](https://github.com/microsoft/vscode/files/6697487/test.zip)

**Comment by roblourens** [comment] 2021-06-23 17:54
There is a bare CR character in this file

![image](https://user-images.githubusercontent.com/323878/123145143-5de8c300-d411-11eb-9e32-82174f8554f1.png)

Duplicate of https://github.com/microsoft/vscode/issues/48063

**Closed by roblourens** 2021-06-23 17:54 UTC
Labels: needs more info
