### ISSUE TITLE
Editor - Japanese input - strange behavior on word wrapping

### ISSUE THREAD

**Issue by remio87** [microsoft/vscode#143167] opened 2022-02-16 02:55 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.0-insider
Commit: 50089c3f92c17584a4aca179f51f220b56c22020
Date: 2022-02-14T05:17:14.990Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT x64 10.0.19043
IME: Microsoft IME

Steps to Reproduce:
1. Install VS Code
2. Open a new file
3. Enable word-wrapping
4. Enter Japanese sentence so that it go over the wrap point
5. Get the strange behavior shown in the video below

Strange behavior - What I got on VS Code with the above steps

https://user-images.githubusercontent.com/82135212/154186413-dfc6a7d0-2e0d-4d22-a774-6fd4852f7863.mp4

Normal behavior - What I got on Mery (text editor)

https://user-images.githubusercontent.com/82135212/154187902-c15438d8-481e-475b-909d-d7b3d568eaac.mp4

I found issue #138704 and #139956. I also found those issues should be solved by PR #139394 in the insiders. So I tried the latest insiders as indicated above. However, I still got the same problem. The above video actually records the behavior of the insiders without any extensions.

[update] I could not record the window of Notepad properly, so I re-upload a video showing expected normal behavior on another text editor. Notepad shows the same (normal) behavior.

**Comment by alexdima** [comment] 2022-02-16 08:28
I confirm, we are currently not able to render the composed text on multiple lines (wrapped). Let's track in https://github.com/microsoft/vscode/issues/28291

**Comment by dhimetoro** [comment] 2022-03-21 07:28
This issue is not a duplicate of #28291.
Issue #28291 is about the text being typed being displayed outside of the window.

This issue (#143167) is about the text being typed being swept away as if it were being overwritten inside the window instead of being displayed outside the window.
This makes it difficult to use because the text being typed is swept away and becomes invisible.
This behavior has been occurring since version 1.64.0. It did not occur until version 1.63.2.


This issue behavior. Since version 1.64.0 (also version 1.66.0-insider).

https://user-images.githubusercontent.com/89648677/159217699-20e0b59c-b8d2-4f0c-953f-aa3b3f0dad3c.mp4


Expected behavior. All characters being typed are displayed, making it easy to type. Until version 1.63.2.

https://user-images.githubusercontent.com/89648677/159217800-9e7e8877-f52f-4057-84dc-d988da2e7e8e.mp4

**Closed** 2024-09-09 12:58 UTC
Labels: bug, editor-input-IME
