### ISSUE TITLE
Timeline (git log) shows nothing for nested git repositories

### ISSUE THREAD

**Issue by dprogm** [microsoft/vscode#164447] opened 2022-10-24 12:58 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: 18.04.6 LTS (Bionic Beaver)

Steps to Reproduce:

1. Provide a git repository that contains multiple nested git repositories
2. Set `"git.repositoryScanMaxDepth": -1` 
3. The timeline doesn't display the git commit log

The output of git shows the following:
```console
[2022-10-24T12:52:05.863Z] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n21 -- /absolute/path/to/file.hpp [110ms]
```
If I execute this command from within the nested repository it shows the git log correctly. My assumption is that this command is executed from some top level directory.

**Comment by lszomoru** [comment] 2022-10-24 13:29
@dprogm, to avoid any confusion do you mind sharing a screenshot of the "timeline" that should display the git commit log? Thanks!

**Comment by lszomoru** [comment] 2022-10-24 14:37
@dprogm, any additional information that you could provide to set up a repro would be highly appreciated. Thanks!

**Comment by lszomoru** [comment] 2022-11-24 11:00
@dprogm, sorry for not getting back to you on this until now. Could you also provide a screenshot of the "Source Control" viewlet? Does that should all three repositories? Also could you check the value of the `git.repositoryScanMaxDepth` setting?

**Comment by dprogm** [comment] 2022-11-25 04:42
The "Source Control" viewlet only shows the `top_repo` and `sub_repo_1`. For some reason `sub_repo_2` is not shown.
<img width="1904" alt="Source_Control_Viewlet" src="https://user-images.githubusercontent.com/32619672/203902668-434aa9db-eb5a-4d7e-a109-eeea378ba2b3.png">
My settings are as follows:
```json
{
  "git.repositoryScanMaxDepth": -1
}
```

**Comment by lszomoru** [comment] 2023-01-20 15:14
@dprogm, sorry for not getting back to you. I believe that indeed the problem is due to the fact that `sub_repo_2` is not being discovered by VS Code. Would you be able to start VS Code using `code --log trace`, open the folder/workspace and then send me the contents of [the git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window) so that I can review the logs of the repository discovery. Also, I guess the Timeline is working as expected if you select a file from the `sub_repo_1` repository.

**Comment by dprogm** [comment] 2023-01-25 15:51
```
2023-01-25 16:40:02.944 [info] Log level: Info
2023-01-25 16:40:02.963 [info] Validating found git in: "/opt/local/bin/git"
2023-01-25 16:40:02.964 [info] Using git "2.19.1" from "/opt/local/bin/git"
2023-01-25 16:40:02.964 [info] > git rev-parse --show-toplevel [6ms]
2023-01-25 16:40:02.964 [info] > git rev-parse --git-dir --git-common-dir [7ms]
2023-01-25 16:40:02.964 [info] Open repository: /Users/workstation/Dev/top_repo
2023-01-25 16:40:02.964 [info] > git rev-parse --show-toplevel [67ms]
2023-01-25 16:40:02.964 [warning] No remotes found in the git config file.
2023-01-25 16:40:02.964 [info] > git config --get commit.template [25ms]
2023-01-25 16:40:02.964 [info] > git rev-parse --git-dir --git-common-dir [7ms]
2023-01-25 16:40:02.964 [info] Open repository: /Users/workstation/Dev/sub_repo_2
2023-01-25 16:40:02.964 [info] > git remote --verbose [9ms]
2023-01-25 16:40:02.964 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [12ms]
2023-01-25 16:40:02.964 [info] > git config --get commit.template [9ms]
2023-01-25 16:40:02.964 [info] > git rev-parse --show-toplevel [16ms]
2023-01-25 16:40:02.964 [warning] No remotes found in the git config file.
2023-01-25 16:40:02.964 [info] > git status -z -uall [19ms]
2023-01-25 16:40:02.964 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [15ms]
2023-01-25 16:40:02.965 [info] > git rev-parse --show-toplevel [13ms]
2023-01-25 16:40:02.965 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n632 -- /Users/workstation/Dev/top_repo/sub_dir/sub_repo_2/file1.txt [18ms]
2023-01-25 16:40:02.965 [info] fatal: your current branch 'master' does not have any commits yet
2023-01-25 16:40:02.965 [info] > git remote --verbose [11ms]
2023-01-25 16:40:02.965 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [13ms]
2023-01-25 16:40:02.965 [info] > git config --get commit.template [30ms]
2023-01-25 16:40:02.971 [warning] No remotes found in the git config file.
2023-01-25 16:40:02.973 [info] > git status -z -uall [33ms]
2023-01-25 16:40:02.973 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [30ms]
2023-01-25 16:40:02.979 [info] > git remote --verbose [8ms]
2023-01-25 16:40:02.979 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [11ms]
2023-01-25 16:40:02.990 [warning] No remotes found in the git config file.
2023-01-25 16:40:02.990 [info] > git status -z -uall [8ms]
2023-01-25 16:40:02.990 [info] > git config --get commit.template [11ms]
2023-01-25 16:40:02.992 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [8ms]
2023-01-25 16:40:02.995 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [8ms]
2023-01-25 16:40:02.997 [info] > git remote --verbose [7ms]
2023-01-25 16:40:03.008 [info] > git status -z -uall [8ms]
2023-01-25 16:40:03.011 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [8ms]
2023-01-25 16:40:03.321 [info] > git show --textconv :sub_dir/sub_repo_2/file1.txt [8ms]
2023-01-25 16:40:03.329 [info] > git ls-files --stage -- /Users/workstation/Dev/top_repo/sub_dir/sub_repo_2/file1.txt [14ms]
2023-01-25 16:40:03.342 [info] > git check-ignore -v -z --stdin [14ms]
2023-01-25 16:40:29.885 [info] > git check-ignore -v -z --stdin [7ms]
```
As you can see in the log it only attempts to open `top_repo` and `sub_repo_2`. For some reason it doesn't see `sub_repo_1`. If I select `top_repo/sub_dir/sub_repo_2/file1.txt` for example then I get the following output:
```
2023-01-25 16:44:20.174 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n902 -- /Users/workstation/Dev/top_repo/sub_dir/sub_repo_2/file1.txt [10ms]
2023-01-25 16:44:20.174 [info] fatal: your current branch 'master' does not have any commits yet
```
But there are commits in `sub_repo_2`. I guess this is why the timeline isn't showing me anything except `File Saved`. If I can further support you let me know.

**Comment by lszomoru** [comment] 2023-01-27 15:00
@dprogm, thanks for getting back to me on this. Couple of things that stand out from the logs:
1. I just realised but I was wondering if you are able to reproduce with the latest Insiders release 1.75
2. In the screenshot with the directory structure I see that `sub_repo_1` and `sub_repo_2` folders are both under a `sub_dir` folder. Yet looking at the logs that you have shared I see that we first open the "/Users/workstation/Dev/top_repo" repository after which we are opening the "/Users/workstation/Dev/sub_repo_2". That does not match the folder structure from the screenshot. Am I missing something here?

**Comment by lszomoru** [comment] 2024-12-13 07:19
Closing the issue as I never gotten the necessary information to continue the investigation.

**Closed by lszomoru** 2024-12-13 07:19 UTC
Labels: bug, info-needed, git
