### ISSUE TITLE
touchpad scrolling problem

### ISSUE THREAD

**Issue by nshamsiddin** [Microsoft/vscode#45970] opened 2018-03-16 11:26 UTC
Issue Type: <b>Bug</b>

sometimes touchpad scrolling works teribly bad when I maximize VS Code.
I always have to minimize and remaximize to solve this issue

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|7.93GB (2.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
bootstrap-4-cdn-snippet|eve|1.0.7
intellij-idea-keybindings|k--|0.2.21
python|ms-|2018.2.1
bootstrap4-vscode|the|4.0.0
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces only with extensions

**Comment by bpasero** [comment] 2018-03-16 13:11
Duplicate of #13612

**Closed by bpasero** 2018-03-16 13:11 UTC
Labels: new release
