### ISSUE TITLE
test explorer

### ISSUE THREAD

**Issue by pana-cc** [Microsoft/vscode#29990] opened 2017-07-01 13:59 UTC
Hi,
I am the author of mocha-typescript and I would like to add a VSCode extension that would:
 - Run all tests on file change and print the results on the integrated terminal
 - Display an overlay over the code with test status and buttons to re-run the particular tests (similar to the merge conflict resolution buttons)
 - Display a tree view in the left hand panel with all tests and their statuses along options to enable/disable the watcher in point 1, as well butttons to rerun tests or just the failed tests
Are these possible using an official extensibility API?
Do you have plans to provide something similar (VisualStudio has test explorer)?
If these are possible could you give me some directions to the APIs I should use?

**Comment by alexriedl** [comment] 2017-07-11 18:24
Related: [9505](https://github.com/Microsoft/vscode/issues/9505)

**Comment by sandy081** [comment] 2017-08-25 14:25
@pana-cc Here is the reference to contribute custom views
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews

**Comment by Tyriar** [comment] 2017-08-27 15:40
Duplicate of #9505

**Closed by Tyriar** 2017-08-27 15:40 UTC
Labels: question, workbench
