### ISSUE TITLE
Highlighted indent guides unexpected behavior

### ISSUE THREAD

**Issue by buenon** [Microsoft/vscode#50529] opened 2018-05-27 10:59 UTC
Issue Type: <b>Bug</b>

When the cursor is outside of the current view (e.g. currently viewing lines 120-150 and the cursor is at line 100) the highlighted indent guides disappear.

Also, placing the cursor before a closing bracket and after the closing bracket should highlight the indent guildes differently.
Before the closing bracket should highlight the scope between the opening and closing brackets.
After the closing bracket should highlight the parent's scope.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.4
xml|Dot|2.0.0
beautify|Hoo|1.3.0

</details>

**Comment by alexandrudima** [comment] 2018-05-29 13:44
Duplicate of #49173

**Closed** 2018-05-29 13:44 UTC
Labels: *duplicate
