### ISSUE TITLE
search.maxResults setting not working in search editor

### ISSUE THREAD

**Issue by petwu** [microsoft/vscode#128641] opened 2021-07-14 11:08 UTC
Issue Type: <b>Bug</b>

The `search.maxResults` settings introduced in version #126762 only works inside the sidebar search, but not in the search editor. The search editor still has the old limit of 10,000 results despite `search.maxResults` being set to a higher 
(or lower) value.

![](https://user-images.githubusercontent.com/39537032/125611470-ef175423-c479-4841-b71d-a1a7c64a1552.png)

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2276G CPU @ 3.80GHz (12 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (22.86GB free)|
|Process Argv|--crash-reporter-id d0fc1044-621d-448f-a1da-51ebf398f9c7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by JacksonKearl** [comment] 2021-08-13 22:10
Fixed in main, duplicate of #129153

**Closed by JacksonKearl** 2021-08-13 22:10 UTC
