### ISSUE TITLE
Unable to sync preferences

### ISSUE THREAD

**Issue by ButchAnton** [microsoft/vscode#95914] opened 2020-04-22 19:25 UTC
Issue Type: <b>Bug</b>

When preference syncing was first introduced, it worked fine.  After an update, it stopped working, complaining about there being a duplicate key in the keystore.  Now, with the most recent updates, I see two new errors:

Writing login information to the keychain failed with error 'The specified item could not be found in the keychain.'.

Source: Microsoft Account (Extension)

and 

Error while starting Sync: No Auth Token Available

VS Code version: Code - Insiders 1.45.0-insider (bd262894bbaac5156d5bf832160b7056c91decea, 2020-04-22T18:26:38.140Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|-psn_0_4195328|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.1.0
project-manager|ale|10.11.0
arepl|alm|1.0.23
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
vscode-custom-css|be5|3.0.9
color-info|bie|0.5.1
regex|chr|0.2.0
open-html-in-browser|cod|0.1.21
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
vscode-faker|dee|1.4.1
git-extension-pack|don|0.1.3
githistory|don|0.6.3
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|4.5.0
code-runner|for|0.9.17
gc-excelviewer|Gra|2.1.34
todo-tree|Gru|0.0.172
vscode-guid|hea|1.4.19
vscode-emacs|hir|0.1.1
beautify|Hoo|1.5.0
replace-curly-quotes|jin|1.1.0
vscode-peacock|joh|3.7.0
chat|kar|0.33.0
vscode-gutter-preview|kis|0.26.1
git-indicators|lam|2.1.2
MagicPython|mag|1.1.0
rainbow-csv|mec|1.7.0
ui5-explorer|mic|0.4.0
xml-format|mik|1.0.2
vscode-ui5|mil|1.0.2
vscode-clang|mit|0.2.3
prettify-json|moh|0.0.3
vscode-docker|ms-|1.1.0
python|ms-|2020.4.74986
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.27.0
vsliveshare|ms-|1.0.2000
vsliveshare-audio|ms-|0.1.84
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
color-highlight|nau|2.3.0
vscode-print|pdc|0.7.14
platformio-ide|pla|1.10.0
polacode|pnp|0.3.4
vscode-css-peek|pra|3.0.2
view-in-browser|qin|0.0.5
java|red|0.60.0
vscode-xml|red|0.11.0
vscode-format|rya|0.0.6
nightwatch-js-snippets|san|0.2.0
todotasks|san|0.5.0
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.7.2
guides|spy|0.9.3
python|tht|0.2.3
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.1
gitblame|wad|3.2.0
quokka-vscode|Wal|1.0.288
vscode-todo-highlight|way|1.0.4
debug|web|0.24.0
change-case|wma|1.0.0
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment] 2020-04-24 14:57
`Error while starting Sync: No Auth Token Available` should be fixed in the next Insider's

'The specified item could not be found in the keychain.'. is a duplicate of https://github.com/microsoft/vscode/issues/95701

**Closed by RMacfarlane** 2020-04-24 14:57 UTC
Labels: authentication, settings-sync
