### ISSUE TITLE
[Request] [JSON] a jsonValidation extension contribution point for @context

### ISSUE THREAD

**Issue by benatkin** [microsoft/vscode#98442] opened 2020-05-23 19:59 UTC
Like the `$schema` key, the `@context` key is used to identify the file type in JSON files. It's used in w3 standards like Activity Streams. It's also used by https://schema.org/ which shows up in lots of web pages.

https://www.w3.org/TR/activitystreams-core/#example-1

Adding "contextMatch" here would make it so anyone could write an extension that would provide a JSON schema for a context that would show up regardless of the file extensions. Often json files are just `.json`, not `.jsonld` so the isn't sufficient.

This could be done with "contextMatch" which would be analagous to "fileMatch" here but match a URL.

https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation

Since the `$schema` is non-standard I think it could cause it to fail a strict JSON schema that didn't include it, so I think a contribution point for `@context` would be a better solution in a lot of cases. https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json

**Comment by benatkin** [comment] 2020-05-23 20:09
Oh, and this could also be used in the other places that use fileMatch. So not just an extension contribution point. https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json

**Comment by aeschli** [comment] 2020-10-14 20:39
duplicate of https://github.com/microsoft/vscode/issues/56334

**Closed by aeschli** 2020-10-14 20:39 UTC
