### ISSUE TITLE
Editor window blanks out when splitting on dual-wide monitor

### ISSUE THREAD

**Issue by recursionbane** [Microsoft/vscode#56390] opened 2018-08-14 18:18 UTC
Issue Type: <b>Bug</b>

**[Video of behavior on Streamable](https://streamable.com/y4c5v)**

1. Window resolution is: 6874x1410
2. Create blank new file, type any amount of text
3. Split window horizontally once (two-column layout): Everything's okay
4. Split window horizontally once more (three-column layout): All text within editors disappear

**This is reproducible both in Stable 1.26 (August 2018) and Insiders 1.27.0 (August 2018).**
Developer Console only says: INFO no standard startup: not a new window

I'd like to point out that this bug renders VS Code unusable on wide displays.
The problem did not exist in 1.25 when the grid layout was first introduced.
Changing color schemes and disabling all extensions had no impact.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (6.79GB free)|
|Process Argv|%AppData%\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment] 2018-08-15 05:02
Marking as duplicate of https://github.com/Microsoft/vscode/issues/51576

@recursionbane can you give a newer build a try that is using Electron 3.0.x: https://az764295.vo.msecnd.net/exploration/e6caa88a0261e72c41c76ab2ff454b8763a19f73/VSCode-win32-x64-1.27.0-exploration.zip

**Closed by bpasero** 2018-08-15 05:02 UTC
Labels: electron-2.0.x-update, new release
