### ISSUE TITLE
Outline trying to reveal activeEntry when entry is filtered out

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#208923] opened 2024-03-27 16:35 UTC
I saw this once a couple days ago, and again today

- Open notebook
- Close it
- The notebook outline is still there and overlayed with this message

<img width="371" alt="image" src="https://github.com/microsoft/vscode/assets/323878/10c22b87-816a-4b60-ae8a-8011ef0c8e6e">

```
2024-03-27 11:03:48.642 [error] TreeError [OutlinePane] Tree element not found: [object Object]: Error: TreeError [OutlinePane] Tree element not found: [object Object]
    at T.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:29689)
    at T.getListIndex (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:28692)
    at Y.getRelativeTop (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:626:2556)
    at V (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38288)
    at P.jc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38425)
2024-03-27 11:06:20.347 [error] [Extension Host] [extension] Error: Response stream has been closed
    at Object.markdown (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:855:1469)
    at p (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:895:7332)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at hE.processResponse (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:897:27)
    at oE.fetchConversationResponse (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:859:1735)
    at oE._provideResponseWithProgress (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:857:1618)
    at oE.provideResponseWithProgress (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:855:1830)
    at r.x (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:869:859)
2024-03-27 11:06:29.734 [error] [Extension Host] [extension] Error: Response stream has been closed
    at Object.markdown (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:855:1469)
    at p (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:895:7332)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at hE.processResponse (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:897:27)
    at oE.fetchConversationResponse (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:859:1735)
    at oE._provideResponseWithProgress (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:857:1618)
    at oE.provideResponseWithProgress (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:855:1830)
    at r.x (/Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.14.2024032701/dist/extension.js:869:859)
2024-03-27 11:11:15.667 [error] TreeError [OutlinePane] Tree element not found: [object Object]: Error: TreeError [OutlinePane] Tree element not found: [object Object]
    at T.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:29689)
    at T.getListIndex (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:28692)
    at Y.getRelativeTop (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:626:2556)
    at V (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38288)
    at P.jc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38425)
2024-03-27 11:18:53.876 [error] TreeError [OutlinePane] Tree element not found: [object Object]: Error: TreeError [OutlinePane] Tree element not found: [object Object]
    at T.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:29689)
    at T.getListIndex (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:28692)
    at Y.getRelativeTop (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:626:2556)
    at V (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38288)
    at P.jc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38425)
2024-03-27 11:33:54.451 [error] TreeError [OutlinePane] Tree element not found: [object Object]: Error: TreeError [OutlinePane] Tree element not found: [object Object]
    at T.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:29689)
    at T.getListIndex (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:28692)
    at Y.getRelativeTop (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:626:2556)
    at V (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38288)
    at P.jc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38425)
2024-03-27 11:33:59.429 [error] TreeError [OutlinePane] Tree element not found: [object Object]: Error: TreeError [OutlinePane] Tree element not found: [object Object]
    at T.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:29689)
    at T.getListIndex (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:28692)
    at Y.getRelativeTop (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:626:2556)
    at V (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38288)
    at P.jc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38425)
```

**Comment by Yoyokrazy** [comment] 2024-03-27 22:15
update after trying to repro: 
- repro is EXTREMELY inconsistent, only been able to get the bug once on insiders, and never in OSS. When bugged:
  - outline view entirely locks up, notebook entries overlay the placeholder as shown above in the screenshot. forces user to reload the window to fix 
  - error logs as shown above ^^ 
  - potential memory leak in the render template? creating the scoped context keys seem to be related here: https://github.com/microsoft/vscode/blob/9e0b3f311a68dce476b6209519d5b1506077bbcb/src/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.ts#L160
  - mem leak seems to be tied to the bug, absolutely no issues when the primary bug itself doesn't repro. multiple memory profiles reveal nothing out of the ordinary. need to profile when the bug presents again.

**Comment by Yoyokrazy** [comment] 2024-03-27 23:25
- tied to configuration change listeners maybe

**Comment by Yoyokrazy** [comment] 2024-03-27 23:38
cc @joaomoreno 

Wondering if there's a way that we can make sure that the treeview can recover from this? Bit painful forcing a full reload. The treeview fails on a `setSelection` call and from that point the DOM node is fully present regardless of editor switching.

**Comment by deepak1556** [comment] 2024-04-02 02:36
@joaomoreno is OOF till next week, if this requires attention from him I suggest we move the issue to next milestone or the recovery milestone. I don't see any candidate label, please let me know otherwise.

**Comment by shubhamv199** [comment] 2024-04-08 08:05
the issue is still happening. Sometimes the outline is stuck and its view remains the same even if I open a new notebook with different content.

**Comment by jorenham** [comment] 2024-04-08 14:12
Once I open a notebook, the outline stops updating, and requires a full vscode restart. On opening a notebook, I see the following `Window` output:

```
2024-04-08 16:11:01.120 [error] TreeError [OutlinePane] Tree element not found: [object Object]: Error: TreeError [OutlinePane] Tree element not found: [object Object]
    at T.o (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:192:29689)
    at T.getListIndex (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:192:28692)
    at Y.getRelativeTop (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:626:2556)
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38326)
    at P.jc (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2334:38463)
```

**Comment by jrieken** [comment] 2024-04-08 14:58
@Yoyokrazy should we track this as candidate? (assuming fix is in reason)

**Comment by Yoyokrazy** [comment] 2024-04-08 16:46
@jrieken Yep, I think that's pretty fair. Given the only way out of the broken state is a full reload, it seems breaking enough (and a regression) to warrant candidate status.

**Comment by Yoyokrazy** [comment] 2024-04-08 18:58
Easy repro: 
- ensure `notebook.outline.showCodeCells` is set to `false` (this is the default, but double check you haven't changed this)
- create a notebook with only code cells
- set outline mode to follow cursor
![image](https://github.com/microsoft/vscode/assets/12552271/06221e6a-2426-4b9a-bad9-e695c7db4916)
- click into a code cell, treeview will attempt to reveal/highlight the entry however it is not found

**Comment by Yoyokrazy** [comment] 2024-04-08 19:17
Description of issue (from PR)
When outline view was set to `follow cursor`, the treeview will try to highlight the active entry in the outline view. After the latest iteration, users are now able to exclude a variety of cell types from the view. This filtering logic was shifted to the treeview's `getChildren` call in order to preserve the outline model for other computations (namely nb sticky scroll).

Easiest example is if the user excludes code cells (the default behavior), and then clicks a code cell. The treeview will attempt to highlight the entry, but as the cell was filtered out, there would be an error as the entry cannot be found. This breaks the outline view entirely, and the treeview cannot recover. Ideally this wouldn't force a reload, but this PR ensures that a notebook entry exclusion error will not break the view state.

**Closed** 2024-04-08 19:27 UTC
Labels: bug, important, candidate, notebook-toc-outline
