### ISSUE TITLE
Diagnostics sticking around after being fixed

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#50410] opened 2018-05-24 18:40 UTC
Issue Type: <b>Bug</b>

* Type `const x: number = "";` in a `.ts` file and reload.
* You should see an error on `x`.
* Replace `""` with `0`.
* The error does not go away. Tsserver logs show us sending the new empty diagnostics.

VS Code version: Code - Insiders 1.24.0-insider (8bf066e3dca775522bdebde4f742e71498b09bca, 2018-05-24T05:11:02.116Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.63GB (2.09GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
typescript-javascript-grammar|ms-|0.0.41

</details>

**Comment by mjbvz** [comment] 2018-05-24 20:27
Duplicate of #50405

Fixed by the new insiders

**Closed by mjbvz** 2018-05-24 20:27 UTC
Labels: javascript, typescript
