### ISSUE TITLE
New "Untitled-1" tab being added by itself over and over

### ISSUE THREAD

**Issue by johngagefaulkner** [microsoft/vscode#202789] opened 2024-01-19 00:41 UTC
Type: <b>Bug</b>

Unfortunately, I have absolutely no idea how to _reliably_ reproduce the problem. Initially, I believed that one of the markdown preview extensions I installed was creating new "Untitled" documents whenever I would preview a Markdown file. But, now, as I've been typing this, two more were created. I've taken a screenshot and uploaded it [here](https://i.imgur.com/5X1fg6m.png). See below:

![bugScreenshot](https://i.imgur.com/5X1fg6m.png)

### Shortcuts/Keybindings
I thought that maybe there was a shortcut that I was accidentally hitting to create a new file... but the only keybinding set for creating a new file was <kbd>CTRL+SHIFT+N</kbd> (which I'm certainly not accidentally hitting while typing.) I left my PC running overnight last night and woke up to like 13 of these fake "new" tabs... so that eliminates any concern that it's something I'm doing/some interaction I'm performing.

### Checking Log Files (an attempt was made)
I thought I might be able to find a log file somewhere (whether through VSCode's log file itself or maybe there's a log file per extension) where I could find something defining that a new file had been created... but I wasn't able to find anything like that either.

### Additional Details
Also, for what it's worth, if I try to USE that blank document, I can't save anything. It will tell me "Untitled-1" doesn't exist and I can't save it to a file anywhere. So it's obviously an issue of some sort. 

### Ideas/Requests
If there's something I can enable to audit/monitor what's happening inside of VSCode so that I can then identify what is instructing VSCode to create a new blank document, that'd be great.

# Thank you!

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.23615
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (18.16GB free)|
|Process Argv|--crash-reporter-id 6b885fa0-9c35-4251-b793-d5c14ceba9e6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.1.0
copilot|Git|1.151.0
copilot-chat|Git|0.11.1
adaptivecardsstudiobeta|mad|1.2.1
csdevkit|ms-|1.2.7
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
powershell|ms-|2024.0.0
vscode-xml|red|0.26.2023120208
LiveServer|rit|5.7.9
markdown-preview-enhanced|shd|0.8.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30933248
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-01-19 05:04
I suggest you use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Another strategy is to create a new empty profile in case your settings are somehow causing it.

**Comment by mjbvz** [comment] 2024-02-08 00:19
Closing as likely caused by an extension / user configuration

**Closed by mjbvz** 2024-02-08 00:19 UTC
Labels: info-needed
