### ISSUE TITLE
[folding] Code gets unfolded during typing (Python)

### ISSUE THREAD

**Issue by EduardoNigro** [microsoft/vscode#140938] opened 2022-01-18 21:40 UTC
Issue Type: <b>Bug</b>

I usually have my code folded at the method level (when I'm creating a class) and I believe after the latest release, depending on what you're typing, VS Code will unfold all the methods after the line that was being modified.
It only unfolds when there's a syntax error that occurs as you're modifying the code. For example, a mismatched bracket in a list. Note that this type of syntax error is bound to happen as you're modifying the code. Next thing I know, before I can close that bracket, all the methods are unfolded :(

I appreciate your support.
Thanks,
Eduardo

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (17.42GB free)|
|Process Argv|--crash-reporter-id b9bc0b0a-2a6b-45f4-a7e6-cbcf9e10bfbc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.7.0
githistory|don|0.6.19
gitlens|eam|11.7.0
kite|kit|0.147.0
git-graph|mhu|1.30.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
live-server|ms-|0.2.12
vscode-qt-for-python|sea|1.1.7
simple-rst|tro|1.5.1
pyqt-integration|zho|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by PieterBranderhorst** [comment] 2022-01-19 07:19
I think this has the same underlying cause as #137890. There is a pending fix, #139779, which should fix this problem.

**Comment by EduardoNigro** [comment] 2022-01-19 19:46
Thanks for the response, Pieter!
Still on the code folding topic, if I may suggest, you guys should consider some sort of settings that can be saved (like the one from MATLAB below). I find it extremely useful for large code files. There's also a hot key combination to fold and unfold based on the saved settings, such as **"CTRL" + "SHIFT" + "+"** and **"CTRL" + "SHIFT" + "-"**.

Regards,
Eduardo

![image](https://user-images.githubusercontent.com/78741781/150202021-43b3525f-b302-4813-b285-d11917b4da8f.png)

**Comment by EduardoNigro** [comment] 2022-02-04 17:15
Guys! Please fix this issue! It's driving me insane. Every time I accidentally delete a matching bracket, parenthesis, or quotation mark, it unfolds the entire code after the line where it occurred. I'm being super careful when typing those. But every now and then... BOOM!! 😵‍💫

**Comment by EduardoNigro** [comment] 2022-03-01 22:43
Please fix this issue. Pretty please?

**Comment by ProceduralCode** [comment] 2022-06-13 22:55
One un-ideal possible workaround: Change Editor: Folding Strategy from auto to indentation.

**Comment by EduardoNigro** [comment] 2022-06-15 13:40
Thanks ProceduralCode! It seems to work well!

**Comment by aeschli** [comment] 2022-07-25 14:25
Marking as duplicate of https://github.com/microsoft/vscode/issues/137890

**Closed by aeschli** 2022-07-25 14:25 UTC
Labels: bug, editor-folding
