### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by rodrigodiasf1984** [microsoft/vscode#176645] opened 2023-03-09 14:58 UTC
Type: <b>Bug</b>

extensios is crashing

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 7, 6|
|Memory (System)|16.00GB (0.64GB free)|
|Process Argv|--crash-reporter-id d703b935-cdf8-4136-a905-27735b8840b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.17.7
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.9.7
turbo-console-log|Cha|2.7.1
dscodegpt|Dan|2.0.1
dart-code|Dar|3.60.1
flutter|Dar|3.60.0
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
vscode-jest-runner|fir|0.4.60
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
copilot|Git|1.77.9225
beautify|Hoo|1.5.0
svg|joc|1.5.0
vscode-gutter-preview|kis|0.30.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-docker|ms-|1.24.0
vscode-language-pack-pt-BR|MS-|1.76.2023030809
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vsliveshare|ms-|1.0.5834
color-highlight|nau|2.5.0
angular-console|nrw|17.32.0
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.24.0
prisma|Pri|4.11.0
vscode-sort-json|ric|1.20.0
rcomponent|rod|5.0.0
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.5
codelf|unb|11.7.0
vscode-apple-swift-format|vkn|1.4.2
vscode-gradle|vsc|3.12.6
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
chatgpt-vscode-plugin-zh|xia|1.0.2
tailwind-snippets|Zar|1.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
pythonms35:30680984

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:18
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:18 UTC
Labels: freeze-slow-crash-leak, extension-host
