### ISSUE TITLE
Tabs in Insiders getting stacked up on the same tab 

### ISSUE THREAD

**Issue by jeyanthimuthuram** [Microsoft/vscode#39627] opened 2017-12-05 09:36 UTC
- VSCode Version:
_Version 1.19.0-insider
Commit 6bc5a14bf34e44b3af5508350cc1221fcc999ceb
Date 2017-12-05T06:14:37.864Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64_

Issue:
Tabs are getting stacked on the same over and over and make the vscode un-usable ( randomly happening).

I Used this build of 15 minutes ,and ran into the issue twice , need to restart that whole editor to make the things normal

**Comment by bpasero** [comment] 2017-12-05 11:29
@jeyanthimuthuram can you share a video how this looks like for you?

@joaomoreno I think you saw this too?

**Comment by Jeyanthinath** [comment] 2017-12-06 14:43
@bpasero Sure I will update you once I face this issue, I moved to stable build for a while .

**Comment by bpasero** [comment] 2017-12-06 14:47
@Jeyanthinath it would be helpful if you could try to reproduce and attach a screenshot as we are in endgame week and closing for our next stable release.

Also to verify, you are NOT seeing this behaviour:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/33667306-c8b865fe-da9c-11e7-8645-db4d6e073470.gif)


...which is expected default behaviour until you set `"workbench.editor.enablePreview": false`

**Comment by Jeyanthinath** [comment] 2017-12-06 19:39
I set the flag to false now. After setting as of now I didn't faced any.
Will keep posted.

On Dec 6, 2017 8:18 PM, "Benjamin Pasero" <notifications@github.com> wrote:

@Jeyanthinath <https://github.com/jeyanthinath> it would be helpful if you
could try to reproduce and attach a screenshot as we are in endgame week
and closing for our next stable release.

Also to verify, you are NOT seeing this behaviour:

[image: flicker_chrome58]
<https://user-images.githubusercontent.com/900690/33667306-c8b865fe-da9c-11e7-8645-db4d6e073470.gif>

...which is expected default behaviour until you set
"workbench.editor.enablePreview":
false

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/39627#issuecomment-349661043>,
or mute the thread

**Comment by steve9164** [comment] 2017-12-08 05:30
I found that I had the setting:
```
"workbench.editor.showTabs": false
```
which caused something similar to what @jeyanthimuthuram is describing. I don't ever remember setting that. Making that `true` fixed the problem.

**Comment by bpasero** [comment] 2017-12-08 05:56
Ok thanks, let me know.

**Comment by Jeyanthinath** [comment] 2017-12-12 14:12
@bpasero Hurray , I found the issue 

![file_stackissue](https://user-images.githubusercontent.com/2253649/33888914-82b93b28-df74-11e7-9f33-a12ea9fc6a20.gif)

The files are changing and the file name is not changed

**Comment by bpasero** [comment] 2017-12-13 06:16
@jeyanthimuthuram ok this looks indeed like a bug, thanks for sharing! I assume this is not easily reproducible for you or is it?

When it happens again, can you:
* click Help > Toggle Developer Tools > Console and see if there is any output
* from that view click on the little arrow icon

![image](https://user-images.githubusercontent.com/900690/33924252-87574cea-dfd5-11e7-8b92-4acae0379b59.png)

and then on the tab list in the top center

![image](https://user-images.githubusercontent.com/900690/33924237-784e1cce-dfd5-11e7-9bdf-c176a6fe062c.png)

and then see if the tab elements are actually there?

![image](https://user-images.githubusercontent.com/900690/33924242-7fcc3936-dfd5-11e7-9d96-9808b633452a.png)

**Comment by Jeyanthinath** [comment] 2017-12-13 06:21
@bpasero It is not reproducible as far as I know , sure I will try to collect the information on the tabs as well as developer console logs :) 

I should have done this last time :thinking:

**Comment by bpasero** [comment] 2017-12-13 06:22
@Jeyanthinath no worries, thanks!

**Comment by bpasero** [comment] 2017-12-20 07:15
Any update?

**Comment by Jeyanthinath** [comment] 2017-12-20 08:29
@bpasero as of now nope.

**Comment by bpasero** [comment] 2018-01-28 07:15
Closing until there are steps to reproduce.

**Closed by bpasero** 2018-01-28 07:15 UTC
Labels: needs more info
