### ISSUE TITLE
Watcher: changes from git operations are reported as `add` and not `change`

### ISSUE THREAD

**Issue by moloko** [microsoft/vscode#136460] opened 2021-11-04 18:33 UTC
This is basically the same issue as #134851 but I can't re-open that so creating a new issue

There are full details of the problem here: https://github.com/teledemic/vscode-branch-warning/issues/15 (most of the specifics are in [this comment](https://github.com/teledemic/vscode-branch-warning/issues/15#issuecomment-954694915)) hope it's OK to link to that rather than reproduce here...

**Comment by bpasero** [comment] 2021-11-04 19:07
@moloko can you please configure `files.legacyWatcher: off`, use Code stable `1.62.0` (which we just released) or latest insider and let me know if it still reproduces. Also let me know platform you are on when seeing the issue.

**Comment by moloko** [comment] 2021-11-04 20:48
@bpasero Yes I still have the issue on VSC v1.62.0 with `files.legacyWatcher: off`

I am running macOS v11.6.1 on an M1 Macbook Pro - but also get the same issue on my old Intel Mac (same OS version)

I'll try the Insider build tomorrow if I can

Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:23:13.307Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

**Comment by bpasero** [comment] 2021-11-05 07:03
@moloko please do. I just gave it a test:
* run `code-insiders --verbose`
* open developer tools (from Help menu)
* in the console filter by typing `.git/HEAD`
* switch a branch in the project
* see how the event is triggered from the file watcher:

![image](https://user-images.githubusercontent.com/900690/140470947-37a6d2cb-23df-481e-8257-fc1c1a56315d.png)

**Comment by bpasero** [comment] 2021-11-05 07:05
Ok, I see a difference in events:
* `chokidar`: reports `CHANGED`
* `vscode-nsfw`: reports `ADDED`
* `parcel/watcher`: reports `ADDED`

We used `chokidar` previously when you open a folder. We always have been using `vscode-nsfw` when you open a multi-root workspace with more than 1 folder. We now use `parcel/watcher`.

I am not surprised that `vscode-nsfw` and `parcel/watcher` report the same kind of event because their implementation is very similar. It is possible that `chokidar` was doing some kind of normalization that would make it report a `change` instead of `add`.

One workaround for your extension would be to handle this case too, not just the changed case.

I would still have to figure out if the file is actually deleted and added on disk or changed.

**Comment by moloko** [comment] 2021-11-05 10:06
> One workaround for your extension would be to handle this case too, not just the changed case.

Cool, though I'm not actually the author of that extension, that'd be @teledemic

**Comment by bpasero** [comment] 2021-11-06 10:54
This is actually https://github.com/parcel-bundler/watcher/issues/72 which I had been reporting before. At the moment the only workaround is to react to any change kind for this file to detect a branch switch.

**Comment by bpasero** [comment] 2021-11-18 15:53
I am going ahead to close this, I am not sure if my PR will be accepted but the workaround is to update downstream consumers to also listen to add events.

**Comment by bpasero** [comment] 2021-11-23 07:24
Reopening for tracking.

**Closed** 2021-11-29 18:22 UTC
Labels: bug, upstream, macos, file-watcher, confirmed, upstream-issue-linked

**Comment by moloko** [comment] 2021-11-30 12:13
Doesn't look like it has helped I'm afraid, same issue as before.

I'm using:
Version: 1.63.0-insider (Universal)
Commit: b9cf83f70bb6b4697b544a97c7056dfd28fccc5f
Date: 2021-11-30T05:13:11.628Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

**Comment by moloko** [comment] 2021-11-30 12:28
@bpasero weirdly even enabling the 'legacy watcher' now no longer works for me, in both Insider build and v1.62.3 (I think it stopped working a few weeks back).

If I amend Teledemic's extension to have a handler for `onDidCreate` it works fine both with and without legacy watch enabled.

**Comment by bpasero** [comment] 2021-11-30 12:48
Yeah it is always best as an extension to react to both create and change events because there is no 100% guarantee.

**Comment by roblourens** [comment] 2021-12-03 19:26
Not sure there is anything to verify here, and I assume you don't want to reopen the issue?
