### ISSUE TITLE
UWP Application - Feature request

### ISSUE THREAD

**Issue by OrbintSoft** [Microsoft/vscode#11807] opened 2016-09-09 23:21 UTC
I think it should be great if we can have Windows Universal Application to use on mobile with continuum.

https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7762905-visual-studio-code-on-universal-app-platform

**Comment by ramya-rao-a** [comment] 2016-09-11 18:49
Closing as duplicate of #10759
@OrbintSoft @WangZishi Don't forget to up vote the original issue logged.

**Closed by ramya-rao-a** 2016-09-11 18:49 UTC
