### ISSUE TITLE
Autocomplete for non-typescript imports (eg webpack-file-loader)

### ISSUE THREAD

**Issue by Lexicality** [microsoft/vscode#88984] opened 2020-01-20 17:10 UTC
## Backstory
My frontend code imports various templates via
```typescript
import template from "templates/foo/bar/baz.jinja";
```
using Webpack to compile the templates.
To this end, I have this is my tsconfig.json:
```json
{
    "compilerOptions": {
        "baseUrl": "client",
        "paths": {
            "templates/*": [
                "../server/templates/*"
            ]
        }
    }
}
```
and this in global.d.ts
```typescript
declare module "*.jinja" {
    export default function(context?: { [arg: string]: any }): string;
}
```
With this setup I have type checking and when I start to import a template intellisense correctly gives me folders however it does *not* show me any of the `.jinja` files in those folders.
It also does not let me jump to those files by pressing F12 in the way that it does with typescript files.
## Request
* I want to be able to type `import template from "templates/foo/bar/`, press ctrl space and be shown `baz.jinja`
* I would like to be able to press F12 on `import template from "templates/foo/bar/baz.jinja";` and be taken to `/server/templates/foo/bar/baz.jinja` in the editor

**Comment by mjbvz** [comment] 2020-01-21 17:48
Duplicate of https://github.com/microsoft/TypeScript/issues/15146

**Closed by mjbvz** 2020-01-21 17:48 UTC
Labels: javascript
