### ISSUE TITLE
tsserver should be restarted upon crash

### ISSUE THREAD

**Issue by flaviut** [Microsoft/vscode#28644] opened 2017-06-13 17:34 UTC
- VSCode Version: 1.13.0
- OS Version: Debian Jessie

Sometimes the typescript server will run out of memory and die, which will break all the stuff that vscode uses it for. It would be nice if vscode automatically restarted the server when that happens.

**Comment by mjbvz** [comment] 2017-06-13 19:48
If the server is truly crashing, rather than just hanging, we should already restart it automatically. 

Can you take look at the TSServer trace to see what is going on:

1. Set `"typescript.tsserver.trace": "messages"`
2. Reproduce the issue
3. Open the output panel and look at the `TypeScript` section. This should log the communications with the TS Server, along with when the server is restarted

**Comment by flaviut** [comment] 2017-06-13 22:18
I don't know how to reproduce this at will (or I would have submitted a bug in ts), but I'll go ahead and do that and hopefully it happens again :smile:

**Comment by mjbvz** [comment] 2017-06-28 04:02
Closing since we need the logs to investigate this. Please post up the logs if you see this again. You may also want to give the insiders builds a try to see if the issue has been fixed: https://code.visualstudio.com/insiders

**Closed by mjbvz** 2017-06-28 04:02 UTC
Labels: needs more info, typescript
