### ISSUE TITLE
Crash once a while

### ISSUE THREAD

**Issue by Kingscity** [Microsoft/vscode#10903] opened 2016-08-24 17:51 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open software
2. Start editing, typing, copying and pasting
3. (not sure if type too "fast"), and it stop and crush

**Comment by sandy081** [comment] 2016-08-25 11:28
@Kingscity Very sorry to hear that VS Code is crashing. I do not think this could be due to fast typing but to know the root cause for it would you let us know

What kind of project are you are coding. How big is it?
Is it a Git repository
Do you have a special setup?
When this happens would you be able to run a CPU profile from the developer tools (help > toggle developer tools) to see where we spend so much time?

Also, did this not happen with the previous release?

And finally, since this might be related to an extension, does it reproduce when you run with extensions disabled (code --disable-extensions from the command line)?

**Comment by dbaeumer** [comment] 2016-09-05 08:54
@Kingscity I will close the issue since we haven't received a response. If you still can reproduce the issue please ping with steps that demonstrate the problematic behavior.

**Closed by dbaeumer** 2016-09-05 08:54 UTC
Labels: freeze-slow-crash, needs more info
