### ISSUE TITLE
Windows 10 1px black border at bottom

### ISSUE THREAD

**Issue by m4tsur** [Microsoft/vscode#61445] opened 2018-10-21 19:13 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open **Code**
2. Expand **Code** window to full-screen.
3. Look at 1px border at bottom of window, when it is hovered cursor become `s-resize`, but window is not resizing by dragging it.

This bug occurs only in full-screen-expanded window...

<details>
<summary>Screenshot 1(window is expanded):</summary>

![image](https://user-images.githubusercontent.com/5437930/47271047-023d4c00-d57d-11e8-9a18-55d2c5f88c2e.png)

</details>

<details>
<summary>Screenshot 2(window is attached to right):</summary>

![image](https://user-images.githubusercontent.com/5437930/47271149-69a7cb80-d57e-11e8-9f86-e74a3f0c7a00.png)

</details>

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 955 Processor (4 x 3215)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (1.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by l0calh05t** [comment] 2018-10-22 15:18
Step 2 should be maximize the window, not switch to full-screen.

**Comment by sbatten** [comment] 2018-10-22 17:16
duplicate of https://github.com/Microsoft/vscode/issues/58427

**Closed by sbatten** 2018-10-22 17:16 UTC
Labels: new release, workbench-title
