### ISSUE TITLE
[Feature request] Add keybinding directly on the Command Pallete...

### ISSUE THREAD

**Issue by RubenMateus** [Microsoft/vscode#45221] opened 2018-03-07 18:20 UTC
I would like to be possible that the custom key bind could be generated in the command Pallete...

here:
![sem titulo](https://user-images.githubusercontent.com/24896825/37110361-959b6aba-2234-11e8-8311-5060ad0a7f21.png)

**Comment by usernamehw** [comment] 2018-03-07 23:00
Duplicate of #27716

**Closed** 2018-03-08 05:12 UTC
Labels: *duplicate, feature-request, workbench
