### ISSUE TITLE
Lightbulb Gets in the Way of Breakpoint

### ISSUE THREAD

**Issue by robbpriestley** [Microsoft/vscode#25210] opened 2017-04-23 16:26 UTC
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Try to set a breakpoint by clicking in the margin area

Expected outcome: breakpoint can easily be set
Actual outcome: lightbulb icon sitting in the margin "blocks" the breakpoint from being set

Note: I'm pretty sure the lightbulb used to "float" out in the editor area when activated, and that was fine, but at some point, it was moved into the margin area. I find this is frustrating when in the midst of an intense debugging session.

<img width="1280" alt="screen shot 2017-04-23 at 9 17 56 am" src="https://cloud.githubusercontent.com/assets/16694050/25315237/e203e39c-2806-11e7-9e90-3860ba4ef59c.png">

**Comment by CherryDT** [comment] 2017-04-23 17:40
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/25174 ...

**Comment by robbpriestley** [comment] 2017-04-23 17:56
@CherryDT yes, I agree

**Comment by mjbvz** [comment] 2017-04-24 05:29
Closing as duplicate of #25174

**Closed by mjbvz** 2017-04-24 05:29 UTC
Labels: duplicate
