### ISSUE TITLE
Git source control, icons fail to load

### ISSUE THREAD

**Issue by mycroft16** [microsoft/vscode#78411] opened 2019-08-02 22:39 UTC
Issue Type: <b>Bug</b>
How to reproduce:
Switch to the git source control pane, hovering over any row should show icons for stage, discard, etc. They are not visible, but the button action areas are still there and have hover states.

Actual Result:
Looking at the console for Developer Tools shows "Failed to load resource: net::ERR_NOT_IMPLEMENTED refresh.svg:1 (for all of the icons)
![image](https://user-images.githubusercontent.com/10989109/62402187-d0153d80-b543-11e9-984c-aa9cb74a6d19.png)

![image](https://user-images.githubusercontent.com/10989109/62402214-e7ecc180-b543-11e9-9aa0-e49271379850.png)
(icons should show in the red circled area, on the "Changes" line always, and on each individual file line when hovered.)

Expected Result:
Icons should display.

VS Code version: Code - Insiders 1.37.0-insider (0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b, 2019-08-02T21:22:13.578Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2501)|
|Memory (System)|15.91GB (7.30GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.39.1
vscode-remote-extensionpack|ms-|0.15.0

</details>

**Comment by IllusionMH** [comment] 2019-08-03 22:15
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/908

**Closed** 2019-08-05 08:39 UTC
