### ISSUE TITLE
Unicode Support(Encoding) For Output

### ISSUE THREAD

**Issue by ArtBlnd** [Microsoft/vscode#25002] opened 2017-04-19 08:03 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.2|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|java|redhat|0.1.0|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|;

---
<img width="995" alt="code_2017-04-19_17-02-20" src="https://cloud.githubusercontent.com/assets/2209400/25169428/feda55a6-2521-11e7-834b-4eac9ffd5678.png">

Output console dosn't support unicode characters
also there is no settings for output encoding.

**Comment by mjbvz** [comment] 2017-04-19 21:16
I believe this is a duplicate of #3550

**Closed by mjbvz** 2017-04-19 21:16 UTC
