### ISSUE TITLE
Windows 7 (classic theme): Title flashes with custom menubar enabled

### ISSUE THREAD

**Issue by Thunraz** [microsoft/vscode#56630] opened 2018-08-17 05:55 UTC
When window.titleBarStyle is set to custom there is a brief flash of the native title bar when switching between files. This behavior also happens for me in the current Insiders build, but didn't occur in v1.25.1.

![titlebar-flash](https://user-images.githubusercontent.com/977116/44249637-15384680-a1f1-11e8-83a6-a8484225be50.gif)

- VSCode Version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
- OS Version: Windows 7 Professional SP1 (Windows_NT x64 6.1.7601)

Steps to Reproduce:

1. Switch between open files

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-08-17 06:03
@Thunraz are you using some custom window manager or theming program?

**Comment by Thunraz** [comment] 2018-08-17 06:06
@bpasero no, just "regular" Windows.

**Comment by bpasero** [comment] 2018-08-17 06:16
@Thunraz interesting, and in 1.25 you are also using the custom title bar style right?

In that case I suspect an issue with the Electron update. 

Can you just try with a very new version of VSCode (make sure to set title bar to custom again): https://az764295.vo.msecnd.net/exploration/57d01751b88c89046b33be3f1d55f860041fd27b/VSCode-win32-x64-1.27.0-exploration.zip

**Comment by Thunraz** [comment] 2018-08-17 06:28
@bpasero Yes, in 1.25 I was also using custom title bar style (I've updated my comment above with a GIF showing the expected behavior).

Unfortunately, the Exploration version of VSCode shows the same behavior:
![titlebar-exploration-flash](https://user-images.githubusercontent.com/977116/44250878-947c4900-a1f6-11e8-842a-f05d630c3c77.gif)

I've just done another test since I'm using the "classic" Windows theme (i.e. Windows 9x/2000 window styles). When using the "modern" theme, there's no native title bar flash:

![titlebar-modern-theme-no-flash](https://user-images.githubusercontent.com/977116/44251123-84b13480-a1f7-11e8-98be-c6fe25b4988f.gif)

**Comment by bpasero** [comment] 2018-08-17 06:34
@Thunraz yeah so it is indeed related to changing a theme in Windows 7 it seems.

**Comment by Thunraz** [comment] 2018-08-28 20:05
Is there any more information I could provide?

**Comment by bpasero** [comment] 2018-08-29 05:06
At this time no, I fear I have no workaround currently other than not using that windows theme.

**Comment by kanlukasz** [comment] 2019-02-21 20:09
I have the same problem.
Windows 7 Classic Theme (no areo)
Fresh install 1.31.1

**Comment by kanlukasz** [comment] 2019-03-05 19:02
### MY SOLUTION:
Change Title Bar Style to native

![obraz](https://user-images.githubusercontent.com/30685349/53829827-53c10300-3f81-11e9-82eb-251fedfe4bc5.png)

**Comment by anikolaev** [comment] 2019-07-29 12:03
@kanlukasz Thanks for workaround but in this mode 'Alt' keypress doesn't activate the menu bar. Light menu bar doesn't look good with dark themes. Vertical space is wasted.

I wish it could be fixed. That's is one of the reasons I don't use VS Code.

**Comment by mtsh1000** [comment] 2019-09-16 07:22
There is also another side effect of this glitch, that the window title bar stays on top developer tools menu bar.
![vscode_title](https://user-images.githubusercontent.com/32628738/64940162-8074a200-d863-11e9-8606-6334b93d52d2.png)

**Comment by bpasero** [comment] 2019-10-08 14:30
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by bpasero** [comment] 2019-10-15 15:10
@sbatten moving forward you need to come up with a standalone reproducible sample and file this to Electron if we want a fix. I think leaving this issue dormant without this action we can equally just close this as wontfix.

**Comment by sbatten** [comment] 2019-10-15 17:35
I'll try with Electron Fiddle in a Win7 VM

**Comment by mtsh1000** [comment] 2019-10-22 08:13
This seems to be related to that Win 7 basic theme uses GDI for drawing while aero theme and all later windows versions use DirectX.

**Comment by sbatten** [comment] 2019-10-23 00:41
After quite a bit of playing around, the culprit is outlined in the upstream bug linked above. The good news is, there is another workaround that one can use if you don't really care about so much state in the window title. 

**Workaround:**
Set the setting `window.title` to something static like `${appName}` or `${appName} - ${folderName}`. This will stop the title from being updated on editor changes and prevent the bug from surfacing.

**Comment by sbatten** [comment] 2020-10-16 18:10
Redirecting to @deepak1556 to retriage this since upstream has no traction

**Comment by RogueX957** [comment] 2021-04-02 15:29
Can still reproduce on my VsCode too, but the workaround fixed the issue.
I have a doubt: Can you tell me which Electron version is VsCode currently using?

**Comment by deepak1556** [comment] 2022-12-12 11:03
Windows 7 is no longer supported by VSCode, you can read more about it at https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-windows-7

**Closed by deepak1556** 2022-12-12 11:03 UTC
Labels: upstream, electron, titlebar, menus, upstream-issue-linked, windows 7
