### ISSUE TITLE
Refusing to stay signed in

### ISSUE THREAD

**Issue by abhishek-0619** [microsoft/vscode#136335] opened 2021-11-03 06:32 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Vs code is not able to persist my sign-in. After every restart, my vs code is prompting me to sign in again and again. Please solve

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.93GB free)|
|Process Argv|--crash-reporter-id fb4a9c58-14bb-4189-b786-9a430d461e59|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-exports-autocomplete|cap|0.5.4
path-intellisense|chr|2.4.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.2.1
es7-react-js-snippets|dsz|3.1.1
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.9
copilot|Git|1.6.3615
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.8.1236758218
material-icon-theme|PKi|4.10.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.4.33
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-03 06:43
Please update to the current release 1.61.2 and retest.

**Comment by abhishek-0619** [comment] 2021-11-04 04:17
> Please update to the current release 1.61.2 and retest.

Updated to the 1.61.2 and tested but the issue still exists. After every session, it will log out.

**Comment by TylerLeonhardt** [comment] 2021-11-04 20:54
Most likely a duplicate of https://github.com/microsoft/vscode/issues/133201#issuecomment-956430361 be sure to read my update there for next steps.

**Closed by TylerLeonhardt** 2021-11-04 20:54 UTC
