### ISSUE TITLE
"window.restoreWindows": "folders"  doesn't work under Linux

### ISSUE THREAD

**Issue by MrChriZ** [Microsoft/vscode#49050] opened 2018-05-02 13:02 UTC
- VSCode Version:Version 1.22.2
- OS Version:Linux Mint 18.3

Steps to Reproduce:
1. Set "window.restoreWindows": "folders" 
2. Close Code
3. Relaunch code
4. Only one Window reopens.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-05-03 04:04
@MrChriZ video proof please

**Comment by MrChriZ** [comment] 2018-05-03 08:31
OK Slightly different -- here's a video of it **not working** in **Windows** which is running under a VM on my Linux setup.  It was easier to demonstrate code being closed unexpectedly here by killing the VM:

https://www.youtube.com/watch?v=NDwZtpLgOA0&feature=youtu.be

**Comment by MrChriZ** [comment] 2018-05-03 08:45
Something more nuanced is going on under Linux
I setup the Red and Blue folder test as I did under Windows and code worked as expected.

I opened two Ember projects I'm working on and killed code and then reopened and it instead reopened my red / blue folders.

https://www.youtube.com/watch?v=Tc9AgbWlTSE&feature=youtu.be

**Comment by MrChriZ** [comment] 2018-05-03 09:34
It dawned on me that there may be some kind of timer involved which is causing the issues I'm seeing. 
I've tested leaving the Windows system for 30 minutes but code still opened a different folder set than the one I had opened for 30 minutes prior to unexpected system restart.

**Comment by MrChriZ** [comment] 2018-05-03 10:49
So I tried again opening two folders sets in Linux.  I interacted with both flicking through different files.
I then left them for around 5 minutes.  Prior to a restart which I video'd.
Now please excuse the shakey hand video - but I don't have a VM set up for Linux and I can't screen record a full system restart.

https://www.youtube.com/watch?v=jDS-DnSnP6A

Again Code does not open the correct folder set.  
At the start of the video 0:06 in the top window I have my RedPill folder open.
When I reopen code 0:54 in the top window code reopens my EmberJS folder.
The bottom window I believe opened the correct folder... but opens with a different file.

**Comment by bpasero** [comment] 2018-05-03 17:26
@MrChriZ wait a sec, you "power off" the machine while VS Code is running and expect it to restore all windows then? I think there is a high likelyhood that this kills VS Code without having a chance to persist any data.

Can you please reproduce this issue by opening 2 folders, then selecting File > Quit and then starting again?

**Comment by MrChriZ** [comment] 2018-05-03 17:37
"VS Code needs a normal shutdown for this feature to work."
Why?! Chrome manages to remember which tabs I had opened in a similar setup.
It can't be that hard to remember which folders it opened?!

**Comment by bpasero** [comment] 2018-05-04 04:33
Yeah agreed, so marking as duplicate of https://github.com/Microsoft/vscode/issues/12058

**Closed by bpasero** 2018-05-04 04:33 UTC
Labels: needs more info, workbench-state

**Comment by MrChriZ** [comment] 2018-05-04 08:39
Thanks did search but didn't see that one.
