### ISSUE TITLE
File model cache can end up with stale, disposed entries causing issues

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11684] opened 2016-09-08 11:03 UTC
Saw this today but could not consistently repro. I opened this folder, opened the Git view, opened the diff of nodeDebug.ts. Cleaned the changes in that file. Then I opened another file. Then clicked on nodeDebug.ts and saw the issue in the gif - when I click nodeDebug.ts, it doesn't change the editor content. Debugged with @jrieken and saw in doSetInput that we get a disposed model. But no other errors or anything logged.

![sep-08-2016 12-58-30](https://cloud.githubusercontent.com/assets/323878/18347117/1a2e3754-75c4-11e6-94d8-03ebb32248fc.gif)
![image](https://cloud.githubusercontent.com/assets/323878/18346893/f9a99312-75c2-11e6-81d0-fc7dcc5388c7.png)

**Comment by bpasero** [comment] 2016-09-08 11:52
@roblourens yeah I saw this once too, there is a disposed model lurking in my caches and you do not get an error. I am working in this area currently to make sure that my caches never contain a disposed model. I am optimistically closing this as fixed, but please reopen if you see it from our 1.6.0 nightlies (where I pushed some changes).

**Comment by bpasero** [comment] 2016-09-09 08:00
Still reproduces...

**Closed** 2016-09-12 08:43 UTC
Labels: bug, important, workbench

**Comment by bpasero** [comment] 2016-09-12 08:46
Happy to finally found steps how to reproduce. It is a race condition:
* open a file and make changes
* open the diff editor on this file
* from the git viewlet undo the changes
=> you end up jumping back to the file you started
=> sometimes the file turns out to be empty

What happens?
* when you undo from the git viewlet, the file on disk is reverted
* this emits a file change event
* we have a listener that disposes file models when they change on disk
* this listener disposes the model even though we are about to load it (undoing the change in the git viewlet closes the diff editor and reveals the file)
* you end up opening a disposed model

Fix: When we detect file changes and are about to dispose models, we have to check for pending loads on the model and not dispose the model in that case.
