### ISSUE TITLE
Version 1.13 is showing the logo of Github in front of .gitignore file

### ISSUE THREAD

**Issue by latenssi** [Microsoft/vscode#28300] opened 2017-06-09 06:35 UTC
- VSCode Version: 1.13
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Open Visual Studio Code
2. Add .gitignore file to the Explorer

![image](https://user-images.githubusercontent.com/1526792/26963763-ec0a42fe-4cf6-11e7-9a03-add0c40a7795.png)

**Comment by equinusocio** [comment] 2017-06-09 06:58
This is related to seti-icons... that is not a curated theme icons.

**Comment by michelkaporin** [comment] 2017-06-09 07:10
This is not a bug.

**Comment by equinusocio** [comment] 2017-06-09 07:15
@michelkaporin Github issues was not made only for bugs. Yes, this is not a bug, is just a discussion about a bad and misleading ux. Also why `.travis.yml` have a **!** as icon? Why docker icon use a pink color when the docker brand color is blue?

**Comment by michelkaporin** [comment] 2017-06-09 07:21
@equinusocio Now it makes sense what are you complaining about, next time please provide more information when filing an issue.

Assigning to @isidorn as it's UX-related.

**Comment by equinusocio** [comment] 2017-06-09 07:26
@michelkaporin is not my issue :) But thanks for reopening it 👍

**Comment by michelkaporin** [comment] 2017-06-09 07:28
@equinusocio sorry, I meant @latenssi.

**Comment by isidorn** [comment] 2017-06-09 09:02
Forwarding to @aeschli as he is the owner of seti on the vscode side

**Comment by King66** [comment] 2017-06-09 09:05
https://github.com/Microsoft/vscode/pull/27279

**Comment by aeschli** [comment] 2017-06-09 09:13
We take the Seti icon theme as-is from https://github.com/jesseweed/seti-ui and we have no plans to maintain our own variant. Please file improvement request directly against https://github.com/jesseweed/seti-ui.

Also, there are many other alternative themes available on the marketplace.

**Comment by equinusocio** [comment] 2017-06-09 09:14
I suggest icons from material theme..

**Closed by aeschli** 2017-06-09 09:13 UTC

**Comment by yfdyh000** [comment] 2017-06-14 15:01
https://github.com/jesseweed/seti-ui/issues/341.

**Comment by jens1o** [comment] 2017-06-18 14:52
> we have no plans to maintain our own variant

Well, seti-ui seems to be not that kind of maintained as if it is ready for this large user base, especially when you set it as default.

**Comment by aeschli** [comment] 2017-06-19 13:19
@jens1o  From my experience, `seti-ui` is well maintained. But updates come in bursts. So be patient.

**Comment by jens1o** [comment] 2017-06-19 13:30
By maintaining, I also mean reacting to issues and so on. https://github.com/jesseweed/seti-ui/issues As you can see, it looks really empty, unfortunately.
