### ISSUE TITLE
vs code cannot find module '@angular/core' or any other modules

### ISSUE THREAD

**Issue by GHR-Arash** [Microsoft/vscode#33209] opened 2017-08-27 10:00 UTC
![stackoverflow2](https://user-images.githubusercontent.com/5657535/29748863-53457d5a-8b34-11e7-871f-e2437a30d175.jpg)

- VSCode Version:1.15.1
- OS Version:windows 10 Enterprise , version 1703.

Steps to Reproduce:

1.
2.
my project was generated with [Angular CLI] version 1.2.6.

I can compile the project and it works fine, but I always get error in vs code telling me cannot find module '@angular/core' 
cannot find module '@angular/router'
cannot find module .....

`<img src="https://i.stack.imgur.com/SPelZ.jpg" />`

`<img src="https://i.stack.imgur.com/UhOkE.jpg"/
![stackoverflow](https://user-images.githubusercontent.com/5657535/29748862-4d1253fe-8b34-11e7-8841-255a09d93bf7.jpg)
>`

here is my enviroment specification :

```
@angular/cli: 1.2.6
node: 6.9.1
os: win32 x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4
os:Microsoft vs 10 enterprise


**project root folder**

.angular-cli.json
.editorconfig
.gitignore
.vscode
e2e
karma.conf.js
node_modules
package.json
protractor.conf.js
README.md
src
tsconfig.json
tslint.json

**node_module folder**

-@angular
--animations
--cli
--common
--compiler
--compiler-cli
--core
---@angular
---bundles
---core.d.ts
---core.metadata.json
---package.json
---public_api.d.ts
---README.md
---src
---testing
---testing.d.ts
---testing.metadata.json
--forms
--http
--language-service
--platform-browser
--platform-browser-dynamic
--router
--tsc-wrapped
@ng-bootstrap
@ngtools
-@types
--jasmine
--jasminewd2
--node
--q
--selenium-webdriver


**tsconfig.json :**

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```

Reproduces without extensions: Yes/No

**Comment by GHR-Arash** [comment] 2017-08-27 10:02
very frustrating experience with vs code

**Comment by mjbvz** [comment] 2017-08-28 18:37
If you get rid of `typeRoots` in your `tsconfig`, does it work?

**Comment by GHR-Arash** [comment] 2017-08-29 03:54
I removed typeRoots from tsconfig. but no. it didn't help

**Comment by GHR-Arash** [comment] 2017-08-29 04:13
I uninstalled all extension I had already installed, and it turns out JavaScript and TypeScript IntelliSense extension from below address caused the issue.
https://marketplace.visualstudio.com/items?itemName=sourcegraph.javascript-typescript

**Comment by mjbvz** [comment] 2017-08-29 22:08
Closing as caused by extension. Please try filing an issue with that extension

**Closed by mjbvz** 2017-08-29 22:08 UTC
Labels: caused-by-extension, javascript, new release

**Comment by victornoel** [comment] 2017-09-06 08:14
@mjbvz I'm seeing the same problem even if I remove all my extensions (I removed `~/.vscode`).

Actually, it only can't find imports with an `@` in it it seems…

I'm using vscode 1.15.1, ts 2.4.2 (from my workspace, it's an angular-cli project), and these are my configurations for tsc:
* `/tsconfig.json`:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "plugins": [
      {
          "name": "tslint-language-service",
          "disableNoUnusedVariableRule": false
      }
    ]
  }
}
```
and 
* `src/tsconfig.json`:
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "",
    "types": [
      "jasmine",
      "node"
    ]
  }
}
```

Should I open another issue? Thanks :)

**Comment by victornoel** [comment] 2017-09-07 12:45
it's ok, it's a problem caused by one of my typescript plugin.

**Comment by ayyash** [comment] 2017-09-20 15:32
I did nothing except upgrade vscode, and now it cannot find the @angular/core module 
I disabled all plugins, still getting an error

**Comment by victornoel** [comment] 2017-09-20 16:19
@ayyash what's your tsconfig and also is there some vscode plugins that maybe use a ts plugin (such as tslint vnext)?

**Comment by ayyash** [comment] 2017-09-21 05:28
Never mind the issue is reported here https://github.com/Microsoft/vscode/issues/34681 
(PS i disabled all plugins but the problem persisted)
