### ISSUE TITLE
auto-formatting seems to be broken with svg style attribute

### ISSUE THREAD

**Issue by simonmurdock** [Microsoft/vscode#18969] opened 2017-01-21 09:54 UTC
- VSCode Version:1.8.1
- OS Version: OSX Sierra 10.12.2

Steps to Reproduce:

Create a plain html file with this contents, I've stripped this down from a full HTML page to this

 - This HTML seems to produce incorrect indentation on the `<g>` tag, caused by the style attribute
```
<svg>
    <g>
        <rect style="width:200px;"></rect>
</g>
</svg>
```

- this HTML seems to indent fine (I've removed the style on the rect tag)

```
<svg>
    <g>
        <rect></rect>
    </g>
</svg>
```

**Comment by aeschli** [comment] 2017-01-23 11:55
duplicate of #17849

**Closed by aeschli** 2017-01-23 11:55 UTC
Labels: html
