### ISSUE TITLE
ADD TOOGLE PIN STATUS

### ISSUE THREAD

**Issue by phamminhtuan** [Microsoft/vscode#44395] opened 2018-02-26 08:33 UTC
### Issue Type
Feature Request

### Description

If can add the function to pin status like microsoft visual studio , that's great!

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment] 2018-02-26 09:37
Duplicate of https://www.github.com/Microsoft/vscode/issues/12622

**Closed by bpasero** 2018-02-26 09:37 UTC
Labels: *duplicate, workbench-diagnostics
