### ISSUE TITLE
JS modules intellisense isn't working

### ISSUE THREAD

**Issue by kraftwerk28** [Microsoft/vscode#40988] opened 2017-12-31 14:29 UTC
- VSCode Version: 1.19.1
- OS Version: Ubuntu 16.04 LTS

When importing npm modules through 'require()', intellisense stops working. All nessesary modules are installed.
![peek 2017-12-31 16-27](https://user-images.githubusercontent.com/31807671/34462245-309afc04-ee48-11e7-81d7-48b308feecd1.gif)

**Comment by tomy8910** [comment] 2017-12-31 19:54
This also happens to me. But even at first type, intellisense won't work. I tried disabling extensions but the problem persisted. 

- VSCode Version: Version 1.20.0-insider (1.20.0-insider)
- OS Version: macOS High Sierra

**Comment by kraftwerk28** [comment] 2018-01-02 16:23
When adding an expressjs requirement, all npm intellisense becomes working.

**Comment by mjbvz** [comment] 2018-01-03 21:41
I believe this has the same root cause as https://github.com/Microsoft/TypeScript/issues/20988

As a workaround, try running `npm install --save-dev @types/node` to manually install the node typings

Closing as upstream

**Closed by mjbvz** 2018-01-03 21:41 UTC
Labels: javascript
