### ISSUE TITLE
Quotemark for reference import

### ISSUE THREAD

**Issue by rafakwolf** [Microsoft/vscode#27440] opened 2017-05-29 12:22 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (8c1c1d14df3c2f819078484aeffee37c3f00a7a8, 2017-05-29T05:13:44.347Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.4.2|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.1.9|
|Angular1|johnpapa|0.1.16|
|csharp|ms-vscode|1.10.0|
|team|ms-vsts|1.118.2|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-icons|robertohuertasm|7.8.1|
|testcafe-test-runner|romanresh|1.0.2|
|code-settings-sync|Shan|2.8.1|
|omnipascal|Wosi|0.13.0|
|Material-theme|zhuangtongfa|2.8.0|;

---

Steps to Reproduce:

1. Import reference via "Ctrl + ." 
2. Quotemark should be single, the import is always double, may the import consider the tslint rules?

![image](https://cloud.githubusercontent.com/assets/2060578/26549632/534b97b0-4450-11e7-8f4f-349770cec532.png)

**Comment by mjbvz** [comment] 2017-05-30 15:50
Duplicate of https://github.com/Microsoft/TypeScript/issues/13270

**Closed by mjbvz** 2017-05-30 15:50 UTC
Labels: duplicate
