### ISSUE TITLE
Integrated terminal sometimes scrolls right after paste

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6944] opened 2016-05-26 22:21 UTC
- VSCode Version: 1.2.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open integrated terminal
2. Type git clone 
3. Right click just to the right of the typing cursor
4. Paste https://github.com/Microsoft/vscode-smoketest-express.git 

![image](https://cloud.githubusercontent.com/assets/12900364/15592020/61d125ba-2355-11e6-9dad-1b8cc1fe6744.png)

After scrolling back using the left arrow on the keypad, you cant get all the way back:

![image](https://cloud.githubusercontent.com/assets/12900364/15592051/8a311952-2355-11e6-8c9f-296dc17fb65c.png)

**Comment by Tyriar** [comment] 2016-05-27 03:47
Duplicate of https://github.com/Microsoft/vscode/issues/6738

**Closed by Tyriar** 2016-05-27 03:47 UTC
Labels: bug, integrated-terminal, v-test
