### ISSUE TITLE
Highlighting sections/files in the side menu

### ISSUE THREAD

**Issue by AModin** [microsoft/vscode#95687] opened 2020-04-20 11:27 UTC
Since you working in a few files/directories I think it will be great if the user will have the ability to mark these files with some different colors so it will be much easier to find it in the side menu (project explorer). The example is attached below.

![exam](https://user-images.githubusercontent.com/15379788/79746567-ddad6600-8312-11ea-8e73-81b1398a27f1.png)

**Comment by usernamehw** [comment] 2020-04-20 12:30
Possible duplicate of #62104.

**Closed** 2020-04-20 13:02 UTC
Labels: *duplicate
