### ISSUE TITLE
Everything on Explorer blurs out

### ISSUE THREAD

**Issue by rpai9** [microsoft/vscode#119131] opened 2021-03-16 21:25 UTC
- VS Code Version: 1.54.3
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Have a code that downloads a large amount of files (download then delete)
2. Everything will start blurring
![image](https://user-images.githubusercontent.com/68650968/111381491-28974100-867c-11eb-8631-4e5bcaa65476.png)

Does this issue occur when all extensions are disabled?: Yes/No Yes. I was able to reproduce this after disabling all the extenstions

**Comment by isidorn** [comment] 2021-03-17 10:44
I can not reproduce. Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by daminebenq** [comment] 2021-03-19 14:54
Isn't it a problem with the hardware of your machine @rpai9 ? maybe the GPU has a problem, because i had the same problem, and because of it i refunded a 1 year old laptop i used from ACER...

**Comment by rpai9** [comment] 2021-03-24 14:09
> I can not reproduce. Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

I don't seem to be able to replicate it on the insider edition

**Comment by rpai9** [comment] 2021-03-24 14:15
> Isn't it a problem with the hardware of your machine @rpai9 ? maybe the GPU has a problem, because i had the same problem, and because of it i refunded a 1 year old laptop i used from ACER...

I'm using a 2019 Macbook pro with Radeon Pro 555X 4 GB Intel UHD Graphics 630 1536 MB. I know it's not the best GPUs but it works fairly well for all the other things. But it's entirely possible that GPU might be having a hard time keeping up with the changes. I'm not sure if our IT is going to replace the laptop just because of this issue.

**Comment by isidorn** [comment] 2021-03-24 15:33
If you can not reproduce with insiders than it is probably fixed in latest, thus closing

**Closed by isidorn** 2021-03-24 15:33 UTC
Labels: file-explorer, needs more info
