### ISSUE TITLE
About the TreeItem2 class

### ISSUE THREAD

**Issue by systemaker** [Microsoft/vscode#71399] opened 2019-03-28 17:04 UTC
When will we get in vscode production version ( not in vscode.proposed.d.ts ) the TreeItem2 class from TestView example ?

**Comment by sandy081** [comment] 2019-04-01 07:50
Duplicate of https://github.com/Microsoft/vscode/issues/61579

@systemaker Please provide your usecase in above issue that why you need this API and how you would like to use it. It will help us to work on it to get into a better shape

**Closed** 2019-04-01 07:50 UTC
Labels: *duplicate, explorer-custom
