### ISSUE TITLE
Expose the selected file's uri from the file explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#131376] opened 2021-08-23 05:24 UTC
When I tried to adopt the contribution point `file/newFile` to customize the creating file action, I found that it's difficult for the extension to generate files at the correct place. If extension can get the selected file's uri from the file explorer, then it can behave just like the `New File` action in the file explorer title.

**Comment by JacksonKearl** [comment] 2021-08-23 19:07
`file/NewFile` contributions would ideally create new untitled files, similar to what `File => New File` does today. Would that work in your case? 

Otherwise this is duplicate of https://github.com/microsoft/vscode/issues/3553, and related to https://github.com/microsoft/vscode/issues/108271

**Closed by JacksonKearl** 2021-08-23 19:07 UTC

**Comment by jdneo** [comment] 2021-08-24 02:58
Thank you @JacksonKearl! Yes the request is the same as #3553.

I'm trying to implement `new Java class` feature via this contribution point, which the location is important because the file location can be used to infer the package statement for the new Java class.

For sure I can just create a new untitled file which only contains an empty class body in it. But I'm afraid that's not user expected due to:

- The user have to do a save action if he want to persist it.
- After saving to disk, errors will be reported because the lack of package statement at the file head.

Hope this feature request can be taken into consideration, thanks! :)
