### ISSUE TITLE
Context menu not fully visible when titleBarStyle is "custom"

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#54081] opened 2018-07-11 16:45 UTC
- VSCode Version: 1.25.0
- OS Version: Win10 x64 10.0.17134.165

Steps to Reproduce:

1. Set "window.titleBarStyle": "custom"
2. Restart so the setting is effective
3. Open a file that is long enough to fill the whole editor window
4. Right click in the editor near the bottom

Expected: The context menu appears and is fully visible
Actual: The context menu's top is at mouse pointer location, and is only partially visible due to the location.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment] 2018-07-12 17:33
duplicate of #52533

**Closed by sbatten** 2018-07-12 17:33 UTC
Labels: workbench-menu
