### ISSUE TITLE
Forwarded port details - truncate long arguments

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#115597] opened 2021-02-02 09:32 UTC
- Try the VS Code Remote Node sample
- npm install
- F5

Notice that the debugger runs some bootstrap processes that have very long arguments which can be overwhelming:
![image](https://user-images.githubusercontent.com/172399/106580046-bcd09d00-6541-11eb-801c-d2db157d9450.png)

Suggest to truncate the command line after some number of characters, e.g. 30 and show the full name only on hover.

**Comment by alexr00** [comment] 2021-02-02 14:18
Duplicate of https://github.com/microsoft/vscode/issues/115213

**Closed by alexr00** 2021-02-02 14:18 UTC
