### ISSUE TITLE
Linux version cannot autofill DOCTYPE

### ISSUE THREAD

**Issue by ViBE-HU** [Microsoft/vscode#11832] opened 2016-09-10 17:26 UTC
- VSCode Version: 1.5.1
- OS Version: Ubuntu 16.04, 64 bit

Steps to Reproduce:
1. Start Visual Studio Code.
2. Create an empty HTML file.
3. Input `<!DOC` for example.
4. Press TAB.
5. It should fill with the form below but nothing happens.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

</body>
</html>
```

**Comment by ramya-rao-a** [comment] 2016-09-11 16:24
@ViBE-HU Is this a regression? Was this working for you before and not in 1.5.1 anymore?

Pressing TAB after `<!DOC` gives me `<!DOC></!DOC>`
Pressing TAB after `!` gives me 
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
```

**Comment by ViBE-HU** [comment] 2016-09-12 12:41
@ramya-rao-a I just started to use on Linux, so I'm not sure, but the same Windows version can do it.

**Comment by rebornix** [comment] 2016-09-12 17:17
@ramya-rao-a I've tested both 1.4.0 and 1.5.1 and they work.

@ViBE-HU can you help check the right bottom of your Code window and there is a status bar indicating the language for current file, is it saying `HTML`? Besides, can you help provide us the list of extensions you installed as I don't see this issue with a clean install. Thanks in advance!

**Comment by mjbvz** [comment] 2017-01-11 23:22
Closing as we're unable to repo this

@ViBE-HU Please let me know if you still see this issue in VSCode 1.8. If you are, try running code with `--disable-extensions` to see if an extension is the root cause

Thanks

**Closed by mjbvz** 2017-01-11 23:22 UTC
Labels: needs more info
