### ISSUE TITLE
Detect git repo in subfolder

### ISSUE THREAD

**Issue by maxcherio** [microsoft/vscode#118234] opened 2021-03-05 17:15 UTC
Issue Type: <b>Feature Request</b>

Hello,
I would like that Visual Studio Code recognizes the repos that are inside subfolders of the main folder.

Thanks and regards,
Massimo Cherio
massimo.cherio@punchtorino.com
max.cherio@gmail.com

VS Code version: Code - Insiders 1.55.0-insider (04770364fdc1bebeca9d1a257df2cacce06b35d6, 2021-03-05T15:40:03.281Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by eamodio** [comment] 2021-03-08 20:36
Duplicate of #87888

**Closed** 2021-03-08 20:37 UTC
Labels: *duplicate
