### ISSUE TITLE
MACRO in C language

### ISSUE THREAD

**Issue by zhanggy** [Microsoft/vscode#12555] opened 2016-09-24 06:40 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. when I define macros like this,
```
#define FUNCTION_BEGIN()    \
    void MyFun()            \
    {

#define FUNCTION_END()      \
    }
```
all code below display in same color.

<img width="640" alt="snapshot" src="https://cloud.githubusercontent.com/assets/4606273/19226078/df261afe-8ed8-11e6-8316-906ea1bf264d.png">

**Comment by brotulix** [comment] 2016-10-18 15:06
Similar(same?) thing happens with
```
// this comment has the right colour
#define PRIMARY     BIT(0)
// this comment has the wrong colour
#define SECONDARY   BIT(1)
#define TERTIARY    BIT(2)
// This comment also has the wrong colour
#define QUATERNARY  BIT(3)
#
// this comment has the right colour
```

where a single "escaping" # seems to return the highlighter to the right mode.

![image](https://cloud.githubusercontent.com/assets/1337122/19483411/8867203c-9554-11e6-9d6b-f9e9d3e52479.png)

**Comment by zhanggy** [comment] 2016-10-19 03:01
can fix the bug with following trick temporarily
<img width="504" alt="code-snap" src="https://cloud.githubusercontent.com/assets/4606273/19504241/56756eac-95eb-11e6-85a8-880b5e075a66.png">

**Comment by dustpg** [comment] 2016-10-24 11:14
same case. MS not fix it yet :(  
![code_2016-10-24_19-07-31](https://cloud.githubusercontent.com/assets/6801311/19643667/099087b6-9a1e-11e6-8103-07dce530487a.png)

**Comment by aeschli** [comment] 2016-10-24 13:48
duplicate of https://github.com/atom/language-c/issues/173

**Closed by aeschli** 2016-10-24 13:48 UTC
Labels: bug, languages basic
