### ISSUE TITLE
Language server crashes continuously (C/C++) since this morning's update

### ISSUE THREAD

**Issue by tonyh326** [microsoft/vscode#120724] opened 2021-04-07 11:39 UTC
Issue Type: <b>Bug</b>

Start VSCode.  I'm using Remote SSH.

[2021-04-07 07:28:36.855] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50164:25)
	at Object.dispose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:51084:35)
	at LanguageClient.handleConnectionClosed (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:53166:42)
	at LanguageClient.handleConnectionClosed (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:54356:15)
	at closeHandler (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:53153:18)
	at CallbackList.invoke (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48882:39)
	at Emitter.fire (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48940:36)
	at closeHandler (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:49514:26)
	at CallbackList.invoke (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48882:39)
	at Emitter.fire (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48940:36)
	at StreamMessageReader.fireClose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50330:27)
	at Socket.<anonymous> (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50370:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
[2021-04-07 07:28:39.638] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50164:25)
	at Object.dispose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:51084:35)
	at LanguageClient.handleConnectionClosed (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:53166:42)
	at LanguageClient.handleConnectionClosed (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:54356:15)
	at closeHandler (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:53153:18)
	at CallbackList.invoke (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48882:39)
	at Emitter.fire (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48940:36)
	at closeHandler (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:49514:26)
	at CallbackList.invoke (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48882:39)
	at Emitter.fire (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48940:36)
	at StreamMessageReader.fireClose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50330:27)
	at Socket.<anonymous> (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50370:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
[2021-04-07 07:28:42.258] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50164:25)
	at Object.dispose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:51084:35)
	at LanguageClient.handleConnectionClosed (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:53166:42)
	at LanguageClient.handleConnectionClosed (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:54356:15)
	at closeHandler (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:53153:18)
	at CallbackList.invoke (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48882:39)
	at Emitter.fire (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48940:36)
	at closeHandler (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:49514:26)
	at CallbackList.invoke (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48882:39)
	at Emitter.fire (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:48940:36)
	at StreamMessageReader.fireClose (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50330:27)
	at Socket.<anonymous> (/homes/thart/.vscode-server/extensions/ms-vscode.cpptools-1.3.0-insiders4/dist/main.js:50370:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
[2021-04-07 07:33:27.427] [renderer1] [error] Could not find pty with id "41": Error: Could not find pty with id "41"
    at g._throwIfNoPty (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:12:41804)
    at g.shutdown (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:12:40226)
    at Object.call (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:11:8237)
    at u.onPromise (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:10:44099)
    at u.onRawMessage (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:10:43458)
    at /homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:10:42711
    at w.fire (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:8:1836)
    at process.E (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:6:30258)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[2021-04-07 07:34:40.840] [renderer1] [error] Could not find pty with id "42": Error: Could not find pty with id "42"
    at g._throwIfNoPty (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:12:41804)
    at g.shutdown (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:12:40226)
    at Object.call (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:11:8237)
    at u.onPromise (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:10:44099)
    at u.onRawMessage (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:10:43458)
    at /homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:10:42711
    at w.fire (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:8:1836)
    at process.E (/homes/thart/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/platform/terminal/node/ptyHostMain.js:6:30258)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 4.1.13-100.fc21.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|--crash-reporter-id 6658d6f5-579b-4f61-8f78-5c21f07d7b3d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: hercules.corero.com|
|OS|Linux x64 4.1.13-100.fc21.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (56 x 1886)|
|Memory (System)|251.79GB (165.66GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
bracket-pair-colorizer-2|Coe|0.2.0
systemd-unit-file|coo|1.0.6
CppSnippets|har|0.0.15
vscode-emacs|hir|0.1.1
better-cpp-syntax|jef|1.15.5
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
vscode-icons|vsc|11.4.0
material-theme|zhu|3.10.11
atlascode|atl|2.8.6
gitlens|eam|11.3.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.4
jupyter|ms-|2021.5.702919634
cpptools|ms-|1.3.0-insiders4
vscode-yaml|red|0.17.0
code-spell-checker|str|1.10.2
yang-vscode|typ|2.0.5

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by IllusionMH** [comment] 2021-04-07 12:08
/extCpp

Most likely duplicate of https://github.com/microsoft/vscode-cpptools/issues/7306

**Closed** 2021-04-07 12:09 UTC
Labels: *caused-by-extension
