### ISSUE TITLE
No CLI docs for --remote

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91459] opened 2020-02-25 19:44 UTC
Ref #91227

I wasn't sure what the syntax `--remote wsl+Ubuntu` was supposed to do, and `code-insiders --help` doesn't mention it.

**Comment by aeschli** [comment] 2020-02-26 08:55
duplicate of https://github.com/microsoft/vscode-remote-release/issues/1534

**Closed by aeschli** 2020-02-26 08:55 UTC
