### ISSUE TITLE
Cannot expand code blocks after collapsing and closing the file

### ISSUE THREAD

**Issue by loretoparisi** [microsoft/vscode#74530] opened 2019-05-29 10:25 UTC
- VSCode Version:
1.34.0
- OS Version:
macOS 10.14.5
Steps to Reproduce:

1. Open a large JavaScript file with code (classes or functions)
2. Collapses blocks
3. Close the file
4. Reopen the same file
5. Try to expand collapsed blocks.

The `+` will not be showed. A `Loading...` box will be presented when hovering on the line number area.
<img width="720" alt="Schermata 2019-05-29 alle 12 21 01" src="https://user-images.githubusercontent.com/163333/58549777-97d44480-820c-11e9-9d36-bf63d98ed14e.png">

the same `Loading...` popup box is presented when hovering a variable name.

<img width="646" alt="Schermata 2019-05-29 alle 12 20 36" src="https://user-images.githubusercontent.com/163333/58549829-b2a6b900-820c-11e9-85f2-10f2139f268a.png">

The `+` glyphicon will not be showed even closing and reopening that file multiple times.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2019-05-29 18:01
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by loretoparisi** [comment] 2019-05-30 09:15
I have also tested that restarting the IDE fix the issue. While re-opening the same file - without restarting the IDE - does not.

I have to test this issue with the insider build and report here.

**Comment by mjbvz** [comment] 2020-10-03 01:26
Closing this since it is out of date and I have not been able to reproduce the problem.

Let me know if there's a case where a code block cannot be expanded again after being folded

**Closed by mjbvz** 2020-10-03 01:26 UTC
Labels: editor-folding
