### ISSUE TITLE
Render Inline Images in code comments

### ISSUE THREAD

**Issue by robertlugg** [Microsoft/vscode#41775] opened 2018-01-17 22:19 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
language-julia|jul|0.9.1
python|ms-|0.9.1
unicode-latex|oij|1.1.1
vscode-code-outline|pat|0.0.12
progen-mtp|rob|0.0.1
tcl|ras|0.1.0
vscode-icons|rob|7.19.0
partial-diff|ryu|0.5.1
code-spell-checker|str|1.6.2

(1 theme extensions excluded)

---
Feature Request
------------------
Allow images to be displayed "inline" with source code.  Provide meta-data to indicate what to show (using markup, etc).

For several domains an image is worth a thousand words, as they say.  I write geometric routines and wish to describe, for instance, coordinate systems.

I would also like to be able to insert other simple illustrations.  This is better than ascii art.

I know this is a code editor and not a word processor, so have no problems greatly restricting how images are inserted.  Primarily, its just for commenting code better.

As a bonus, I would love the "drag and drop" like this github issue dialog where dropping a file into VSCode will embed whatever markup is needed including potentially copying the image to the same directory as the source code.

References
------------
This Visual Studio extension does exactly what I'm requesting:
https://github.com/lukesdm/image-comments
![image 1226](https://user-images.githubusercontent.com/6054540/35069993-cdd06fb6-fbd3-11e7-8e2a-3a17635ce856.png)

This Visual Studio example is also very similar:
https://editorsamples.codeplex.com/wikipage?title=Image%20Insertion&referringTitle=Home

This request is *not* the same as
https://github.com/Microsoft/vscode/issues/7689 or
https://marketplace.visualstudio.com/items?itemName=kisstkondoros.vscode-gutter-preview
, but is similar.  I don't want a quick "icon", i want a read-able "full-size" image that will help my comment.

**Comment by pyang-1981** [comment] 2018-01-18 04:16
Great request. That will be very helpful.

**Comment by Mlocik97-issues** [comment] 2018-01-18 15:59
I think it's can be also very dangerous (unsecure)...

**Comment by m-schuetz** [comment] 2018-03-27 13:55
I'd also love to have this feature! Developers in visual computing could greatly benefit from graphical representations of algorithms in comments. 

If this makes it into vscode, it would be good if the links could be specified relative to the workspace/project folder, since web content may not always be available or it may get removed at some point. 

![image](https://user-images.githubusercontent.com/6705073/37971832-32d1f716-31d7-11e8-9d56-a91cefafe0ad.png)

**Comment by danmarshall** [comment] 2018-03-29 22:46
👍 I've long wanted this feature in an editor. It could also support a data-uri.
Come to think about it, perhaps this could be implemented markdown inside of a multi-line comment.

**Comment by tecosaur** [comment] 2019-01-11 07:40
I'm here from [LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop) where the is significant demand for inline previews of both images and math (using MathJax).

Adding my two cents - I'd really like to see it, and I also know of a large community that is particularly interested in this capability.

**Comment by jrieken** [comment] 2019-01-18 16:54
/duplicate of https://github.com/Microsoft/vscode/issues/3220

**Closed** 2019-01-18 16:54 UTC
Labels: *duplicate, api, editor-rendering, feature-request

**Comment by robertlugg** [comment] 2019-01-18 17:56
Hi @jrieken, I reviews most of the #3220 thread.  There are several concepts related to my request.  But viewing that thread, I don't see a consistent alignment with the end goal or with my request.  Or, put another way, if issue #3220 were satisfied, would it _necessarily_ mean that my request would also be satisfied?

What concerns me most is the title of that request.  I don't want a "peek" or something like jupyter that performs an evaluation (although those features are nice too).

I don't see how my request is a duplicate of #3220.  That said, I'll respect your judgement if after reviewing this note you conclude that it is.  Thank you for your thoughts on this.

**Comment by jrieken** [comment] 2019-01-18 18:06
Yeah, with #3220 (and PR https://github.com/Microsoft/vscode/pull/66418) there will be API that allows you do render images inline with code and/or code comments. 

<img width="313" alt="screenshot 2019-01-18 at 10 06 00" src="https://user-images.githubusercontent.com/1794099/51404574-ab59fb00-1b08-11e9-8b02-05883a8d2bbc.png">
