### ISSUE TITLE
Test: Basic auth support for proxies

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#221327] opened 2024-07-10 07:40 UTC
Refs: https://github.com/microsoft/vscode/issues/220034

- [x] macOS @rzhao271
- [ ] linux @roblourens
- [x] windows @joyceerhl

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23221327%0A%0A&assignees=chrmarti)

---

- Clone https://github.com/microsoft/vscode-proxy-agent.
- `Dev Containers: Reopen in Container` > `Basic Auth Test`.
- Follow the README.md in the dev container (https://github.com/microsoft/vscode-proxy-agent/blob/main/.devcontainer/basic-auth-test/README.md).

**Comment by roblourens** [comment] 2024-07-23 21:09
I'm getting these errors when trying to install extensions

```
2024-07-23 21:07:46.396 [info] Started local extension host with pid 13223.
2024-07-23 21:07:48.997 [info] [perf] Render performance baseline is 12ms
2024-07-23 21:08:03.767 [error] Failed: net::ERR_TUNNEL_CONNECTION_FAILED
    at Y.D (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:170102)
    at async Y.B (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:166893)
    at async Y.getExtensions (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:163417)
    at async F (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:71516)
    at async z.M (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:71995)
    at async /home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:65447
    at async Promise.all (index 0)
    at async z.I (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:65234)
    at async z.installGalleryExtensions (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:62367)
    at async z.installFromGallery (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:61510)
2024-07-23 21:08:03.782 [error] net::ERR_TUNNEL_CONNECTION_FAILED: Failed: net::ERR_TUNNEL_CONNECTION_FAILED
    at Y.D (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:170102)
    at async Y.B (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:166893)
    at async Y.getExtensions (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:163417)
    at async F (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:71516)
    at async z.M (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:71995)
    at async /home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:65447
    at async Promise.all (index 0)
    at async z.I (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:65234)
    at async z.installGalleryExtensions (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:62367)
    at async z.installFromGallery (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:61510)
2024-07-23 21:08:20.291 [error] Error: net::ERR_TUNNEL_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114482)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
2024-07-23 21:08:20.310 [error] net::ERR_TUNNEL_CONNECTION_FAILED: Error: net::ERR_TUNNEL_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114482)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
2024-07-23 21:08:34.310 [error] Failed: net::ERR_TUNNEL_CONNECTION_FAILED
    at Y.D (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:170102)
    at async Y.B (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:166893)
    at async Y.getExtensions (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:163417)
    at async F (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:71516)
    at async z.M (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:71995)
    at async /home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:65447
    at async Promise.all (index 0)
    at async z.I (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:65234)
    at async z.installGalleryExtensions (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:62367)
    at async z.installFromGallery (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:61510)
2024-07-23 21:08:34.323 [error] net::ERR_TUNNEL_CONNECTION_FAILED: Failed: net::ERR_TUNNEL_CONNECTION_FAILED
    at Y.D (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:170102)
    at async Y.B (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:166893)
    at async Y.getExtensions (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:163417)
    at async F (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:71516)
    at async z.M (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:71995)
    at async /home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:65447
    at async Promise.all (index 0)
    at async z.I (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:65234)
    at async z.installGalleryExtensions (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:62367)
    at async z.installFromGallery (/home/roblou/Downloads/VSCode-linux-arm64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:61510)
```

**Comment by roblourens** [comment] 2024-07-23 21:12
Opened https://github.com/microsoft/vscode/issues/223393

**Comment by chrmarti** [comment] 2024-07-24 08:14
@roblourens Everything else seems to work from my testing. Could you confirm? Thanks.

**Comment by roblourens** [comment] 2024-07-24 19:46
Looks like the issue is on August, so closing https://github.com/microsoft/vscode/issues/223393

**Closed by roblourens** 2024-07-24 19:46 UTC
Labels: testplan-item, proxy
