### ISSUE TITLE
 Files panel to manage, transfer, and synchronize files and folders between local and remotes sites

### ISSUE THREAD

**Issue by bensonkb** [Microsoft/vscode#31243] opened 2017-07-22 07:24 UTC
Need a  Files panel to manage, transfer, and synchronize files and folders between local and remotes sites like Dreamwear. Sync local and Remote Files.
 Toggle between the FTP View and the Git View in Files panel, to manage the files using an FTP server or Git repositories

**Comment by isidorn** [comment] 2017-07-24 07:35
fyi @jrieken

**Comment by jrieken** [comment] 2017-07-24 07:55
duplicate of #29194

**Closed by jrieken** 2017-07-24 07:55 UTC
Labels: feature-request, workbench
