### ISSUE TITLE
ECONNREFUSED debugging browsers in remotes

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#120227] opened 2021-03-31 07:25 UTC
In our selfhosting setup, pressing F5 will yield this notification after about a minute of launching:

![image](https://user-images.githubusercontent.com/22350/113106240-66858080-91b7-11eb-9709-11407b9b9c98.png)

When inspecting the toolbar, I see the shared process is missing:

![image](https://user-images.githubusercontent.com/22350/113106344-8321b880-91b7-11eb-8620-b14c8a86a2dc.png)

@bpasero Could it be related to the introduction of the sandbox?

**Comment by bpasero** [comment] 2021-03-31 07:43
Sandbox is not enabled.

**Comment by connor4312** [comment] 2021-03-31 23:32
Hm, I don't hit this on Windows or OSX, but don't have a WSL with X forwarding setup on hand to test your scenario. For a sanity check, do you see anything in the debug console when this happens?

**Comment by joaomoreno** [comment] 2021-04-01 12:55
No, it's empty. 😢

**Comment by connor4312** [comment] 2021-04-01 15:35
This seems to affect all remotes (see linked issue), marking as candidate for recovery

**Comment by connor4312** [comment] 2021-04-01 16:01
For other users running into this: the fix will be available in the nightly release after this evening.

**Comment by nicojs** [comment] 2021-04-02 15:18
Thanks @connor4312! I can confirm that switching to nightly just now fixed it 🎉. You deserve a medal 🥇

**Comment by dpvball** [comment] 2021-04-02 17:07
it fixed it for me as well. Thanks @connor4312 

one thing to note, it was giving me a connection error still with my launch.json using legacy attach for chrome which was working before. I changed it to the following and everything works as expected again
`"type": "pwa-chrome",`

**Comment by connor4312** [comment] 2021-04-05 15:44
This will be in the upcoming [recovery build](https://github.com/microsoft/vscode/issues/120378)

**Closed by connor4312** 2021-04-05 15:44 UTC
Labels: bug, candidate, debug

**Comment by connor4312** [comment] 2021-04-05 23:06
@joaomoreno please verify if you can 🙂

**Comment by BartCorremans** [comment] 2021-04-06 11:36
This fix works for me about half of the time. I have to try a couple of times to get the debugger to attach to Chrome properly, it seems very random.

This is my launch.json:

`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        }
    ]
}`

I don't see anything special in the Extension Host console. Is there any other info I can provide?

**Comment by connor4312** [comment] 2021-04-06 15:44
Can you share a gif of what you see? https://gifcap.dev/ is helpful

**Comment by BartCorremans** [comment] 2021-04-06 16:04
Sure thing.

![recording](https://user-images.githubusercontent.com/10078799/113741841-5400cf00-9702-11eb-9996-4f164194b97a.gif)

When it does work, the url in Chrome switches from about:blank to http://localhost:4200 within a second or so. Otherwise, the above is what I get.

**Comment by connor4312** [comment] 2021-04-06 16:38
Hm, okay. I don't get that from here and it seems like the fix worked for others... Can you add `trace: true` to the launch.json and share the resulting log file? Its location will be printed in the debug console. That might have some additional information for me to see what's going on.

**Comment by BartCorremans** [comment] 2021-04-06 16:46
[vscode-debugadapter-dce5d35c.json.gz](https://github.com/microsoft/vscode/files/6266301/vscode-debugadapter-dce5d35c.json.gz)

**Comment by Olivloliv** [comment] 2021-04-08 18:44
I experience the same issue, but it just never works, I always have the error message. I can't unzip the resulting trace file, but if it might be useful...
[vscode-debugadapter-da47e36d.json.gz](https://github.com/microsoft/vscode/files/6280787/vscode-debugadapter-da47e36d.json.gz)

**Comment by cool-delete** [comment] 2021-04-08 19:01
I experience the same issue, but it just never works, I always have the error message.
my wsl port is set from 50000 to 60000
so  I keep seeing that it will definitely fail to start
![image](https://user-images.githubusercontent.com/13638610/114081867-ac40f800-98df-11eb-9cc4-97a252fdb097.png)
@connor4312

**Comment by connor4312** [comment] 2021-04-08 21:00
@Olivloliv you are not running the version of the debugger with the fix, please see here https://github.com/microsoft/vscode/issues/120227#issuecomment-812007561

@cool-delete please confirm that you're running the correct version of the debugger

**Comment by cool-delete** [comment] 2021-04-08 23:37
yes thanks this fix my problem

**Comment by Olivloliv** [comment] 2021-04-09 18:48
Oups my bad, it does fix it as well ! thanks

**Comment by Agamennon** [comment] 2021-04-09 20:25
Please re-open as the new update broke this again (insider 1.56.0)  javascript debugger (v2021.4.717)

**Comment by Agamennon** [comment] 2021-04-09 20:29
reverting to javascript debugger 1.56.0,  this version is working fine.

**Comment by connor4312** [comment] 2021-04-09 21:56
@Agamennon please capture a trace log by setting `"trace": true` in your launch.json

**Comment by MikeMcDonald83** [comment] 2021-04-21 19:33
Still having this problem. Using Insiders 1.56.0, js-debug nightly 2021.4.2017 and Ubuntu 20.04.2 on WSL2. Tried both launch and attach. Tried various ports. I can't unzip the verbose debug log because "Unexpected end of file" with gzip. I'll attach anyways. If there's a way to print a verbose log without compression I will do so.

launch.json for this attempt:
`"version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:8081",
      "webRoot": "${workspaceFolder}",
      "trace": true
    }
  ]`

[vscode-debugadapter-78f9297a.json.gz](https://github.com/microsoft/vscode/files/6353415/vscode-debugadapter-78f9297a.json.gz)

**Comment by connor4312** [comment] 2021-04-21 19:35
@MikeMcDonald83 are there any errors if you open console in the `Toggle Developer Tools` command?

**Comment by MikeMcDonald83** [comment] 2021-04-21 19:55
@connor4312 Yes. This was from 2 attempts using the same settings as before.

![image](https://user-images.githubusercontent.com/65324686/115612974-77ef1380-a2b1-11eb-88c9-d31baec1f13d.png)

**Comment by mellester** [comment] 2021-04-26 12:30
[vscode-debugadapter-db300a49.json.gz](https://github.com/microsoft/vscode/files/6376980/vscode-debugadapter-db300a49.json.gz)
I still have the same problem
![image](https://user-images.githubusercontent.com/609138/116082523-cb8ba380-a69b-11eb-8d89-d5f71816dcab.png)
![image](https://user-images.githubusercontent.com/609138/116082601-e3632780-a69b-11eb-985f-155bf99dafb0.png)

**Comment by Agamennon** [comment] 2021-04-29 16:12
Unfortunately Javascript debugger 1.56.1 broke this again, nightly is also broken, there is no working javascript debugger now working with WSL ,  last working version was 1.56.0,

**Comment by connor4312** [comment] 2021-04-29 16:13
@Agamennon please open an issue here with the instructions on the template https://github.com/microsoft/vscode-js-debug/issues

**Comment by connor4312** [comment] 2021-04-30 04:56
fyi (for others who commented on this issue) I believe I've found the issue, see https://github.com/microsoft/vscode-js-debug/issues/982#issuecomment-829819546
