### ISSUE TITLE
扩展宿主意外终止

### ISSUE THREAD

**Issue by zhiyongwu** [Microsoft/vscode#50427] opened 2018-05-25 01:48 UTC
Issue Type: <b>Bug</b>

在windows cmd中使用code .命令启动vsCode
vsCode右下角出现“扩展宿主意外终止”提示，重启无效

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.63GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.23.5
python|ms-|2018.4.0

</details>

**Comment by yume-chan** [comment] 2018-05-25 06:46
Looks like a duplicate of Microsoft/vscode-python#342

Can you check your `PATH` environment variable and post here?

**Comment by zhiyongwu** [comment] 2018-05-25 06:56
分别是用户环境变量和系统环境变量中的PATH
![image](https://user-images.githubusercontent.com/13998812/40530526-c0c7d9fa-602b-11e8-8db6-7d9e4deda9d8.png)
![image](https://user-images.githubusercontent.com/13998812/40530533-c5da5ad0-602b-11e8-9a51-83d3367c9465.png)

**Comment by yume-chan** [comment] 2018-05-25 07:01
The last one (which contains `%JAVA_HOME`) looks strange to me.

Can you make sure it's correct or try to remove it temporarily and try again?

**Comment by zhiyongwu** [comment] 2018-05-25 07:07
It works after removing the last one in my Path.Thank you. @yume-chan

**Closed** 2018-05-28 13:08 UTC
Labels: extension-host
