### ISSUE TITLE
Add a way to format diff instead of the whole document

### ISSUE THREAD

**Issue by kirillbobyrev** [microsoft/vscode#100958] opened 2020-06-24 14:06 UTC
Right now VSCode provides "Format Document" and "Format Selection" and surfaces those via LSP. Most of the time I want to format the Git (or whatever CVS I'm using) diff and not the whole document because otherwise I'm changing code from other people and the history (along with `git blame`) becomes less transparent. In many projects (such as LLVM) there are policies that prevent people from doing that: reviewers ask for the changes that were simply changing formatting in unrelated code to be reverted.

I would like VSCode to provide "Format Diff" in some form because (unlike LSP) it clearly has a notion of CVS. This is probably not very hard because this command would just get the diff and use "Format Selection" on its regions.

**Comment by jrieken** [comment] 2020-06-24 14:21
/duplicate of https://github.com/microsoft/vscode/issues/44075

**Closed** 2020-06-24 14:22 UTC
Labels: *duplicate, feature-request, formatting
