### ISSUE TITLE
Cannot prof startup

### ISSUE THREAD

**Issue by lijunle** [Microsoft/vscode#58929] opened 2018-09-19 05:23 UTC
I am using the newest VSCode insider. It is running very slow in my virtual machine. I tried to following the instructions in [this wiki](https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly). However, the parameter is failing as shown in the GIF. (The GIF is a little bit long.)

![cannotprofstartup](https://user-images.githubusercontent.com/1296500/45732458-fe7d7900-bc0e-11e8-925c-d192ed879ec3.gif)

**Comment by jrieken** [comment] 2018-09-21 07:41
Yeah, I have seen this too

**Comment by jrieken** [comment] 2018-09-21 10:00
This is working with stable but not with Insiders or from source. It seems that the `remote-debugging-port` flag that we need to start the debugger isn't working anymore.

@bpasero Is it possible that this is due to the electron update or due to your refactorings in the bootstrap scripts?

**Comment by bpasero** [comment] 2018-09-21 10:15
@jrieken I am quite sure that I tested `--prof-startup` when I did the `boostrap` changes and it worked. Now I see this output: `Failed to profile startup. Make sure to quit Code first.` when closing Code.

**Comment by jrieken** [comment] 2018-09-21 10:33
yeah, that's because the renderer doesn't seem to be debuggable anymore (`remote-debugging-port`). i will push a change to make things more graceful but the bug will remain.

**Comment by jrieken** [comment] 2018-09-21 10:36
@bpasero this is where everything comes together https://github.com/Microsoft/vscode/blob/e25d7ddbf039d18e7a783c85d528e23e29b809a2/src/vs/code/node/cli.ts#L266-L268. 

We tell the main process and the extension host to start stopped and the renderer to be debuggable (since that cannot be started stopped). Then we try to connect to all of them to profile for a bit

**Comment by jrieken** [comment] 2018-09-21 10:41
maybe related to https://github.com/electron/electron/issues/10445?

**Comment by bpasero** [comment] 2018-09-21 12:48
I know I was able to do `--prof-startup` this month at least and since it works with Code stable, I think it is at least not a Electron regression:

![image](https://user-images.githubusercontent.com/900690/45882122-71bcf180-bdad-11e8-94ae-312c5d3112e4.png)

**Comment by bpasero** [comment] 2018-09-21 12:54
Yeah, I cannot reproduce with 2.0.7. This could be https://github.com/electron/node/pull/53

**Closed** 2018-09-21 13:16 UTC
Labels: bug, perf-startup
