### ISSUE TITLE
[ts] Syntax Highlighting Issue: Template Strings and Semicolons

### ISSUE THREAD

**Issue by jvilk** [Microsoft/vscode#6634] opened 2016-05-22 17:50 UTC
- VSCode Version: 1.1.1
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Insert the following TypeScript code into the editor:

```{ts}
var a = true ? true : `;`;
var i;
```

2. Observe that `var i;` is colored as if it were part of the template string (in VSCode, and on GitHub!).

<img width="290" alt="tsbug" src="https://cloud.githubusercontent.com/assets/1141042/15455483/747275dc-2023-11e6-9f54-9558ebef7bbc.png">

Removing any part of the first line prevents the bug. It only appears to occur when combining variable assignment, the ternary operator, and a template string containing a semicolon (`;`).

Further Info:

A single occurrence of this bug can derail syntax highlighting for the rest of the file, since template strings are multi-line. Template strings with semicolons can be a common occurrence for projects that generate JavaScript as output, and ternaries are a common case when wanting to handle a slight variation in output.

**Comment by jvilk** [comment] 2016-05-22 18:09
Here's a workaround:

```{ts}
var a = (true ? true : `;`);
var i;
```

**Comment by aeschli** [comment] 2016-05-23 07:03
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81

**Closed by aeschli** 2016-05-23 07:03 UTC
