### ISSUE TITLE
folding function be added in the next version?

### ISSUE THREAD

**Issue by hulang** [Microsoft/vscode#2475] opened 2016-01-28 03:34 UTC
I am a Chinese cabbage, and when the time to release the next version.
Will the folding function be added in the next version?
There is also in the page. Write: 《script type= there is no hint like VS: text/javascript

**Comment by glen-84** [comment] 2016-01-28 07:15
#105

**Comment by hulang** [comment] 2016-01-28 08:15
thank you。。。。
This would have to wait for a while.

**Comment by aeschli** [comment] 2016-01-28 08:41
duplicate of #105

**Closed by aeschli** 2016-01-28 08:41 UTC
