### ISSUE TITLE
Window reloads when adding or removing folder from workspace.

### ISSUE THREAD

**Issue by alancnet** [microsoft/vscode#108575] opened 2020-04-29 21:31 UTC
- VSCode Version: 1.44.2
- Local OS Version: Windows 10, Version 1909 (OS Build 18363.778)
- Remote OS Version: Ubuntu 19.10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to SSH host, open terminal.
2. Make two directories: project1, project2
3. Type `code project1` - A new VSCode window will open in that folder.
4. Add Folder to Workspace... -> project2 - VSCode will reload.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

This is a larger problem than the reload itself. If you're working on multiple projects, and they're running in the terminal, adding a folder and reloading will disconnect the terminals from the running processes. I have resorted to `npx kill-code` to kill those background instances.

**Comment by chrmarti** [comment] 2020-10-13 09:04
@bpasero I think this is still expected. Can't find the original issue though.

**Comment by aeschli** [comment] 2020-10-13 15:28
duplicate of https://github.com/microsoft/vscode/issues/72529

**Closed by aeschli** 2020-10-13 15:28 UTC
Labels: remote
