### ISSUE TITLE
Reinstallation of Code Alpha left it in a bad state

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5840] opened 2016-04-26 13:50 UTC
Fixing #5463

I had Code Alpha installed in CentOS (red hat). Today, I downloaded the latest RPM, installed it and now I can't launch Code nor reinstall it.

It doesn't seem to be installed at all. It is also gone from the Applications menu, where it used to be before installing it today.

![image](https://cloud.githubusercontent.com/assets/22350/14820319/7067f6b8-0bc6-11e6-92cd-b2c4bae2a2c1.png)

Can't even reinstall it:

![image](https://cloud.githubusercontent.com/assets/22350/14820323/753c95a4-0bc6-11e6-985c-e22175fe926c.png)

**Comment by joaomoreno** [comment] 2016-04-26 13:53
I could fix it by running `sudo rpm -ev code-alpha` and reinstalling the `rpm` package.

**Comment by Tyriar** [comment] 2016-04-27 21:56
I think I've experienced this where the installer didn't work, it seemed like the installer's issue to me. It happened to me pretty consistently whenever I tried to install a second thing. Fresh restart and using it always seemed to work.

**Comment by astitcher** [comment] 2016-06-07 19:39
This issue exists with the 1.2 released rpm too.

The cause is a misunderstanding about the order of running the scriptlets:

If you are upgrading the postuninstall scriptlet runs *after the upgrade* to uninstall anything left over in the old installation. In this case it is removing the /usr/bin/code (or code-alpha) link to /usr/share/code/bin/code just after it was created.

The postuninstall scriptlet needs to check whether an upgrade is being run and in that case just not do the remove.

I think the section should look like:
```
%postun
f [ "$1" -ge 1 ]; then
  rm -f /usr/bin/code
fi
```

Also note that you shouldn't need sudo for any part of the rpm scripts as installing a package runs as root.

**Comment by Tyriar** [comment] 2016-06-08 07:30
Should be fixed via PR from @astitcher

**Closed by Tyriar** 2016-06-08 07:30 UTC
Labels: bug, install-update, linux
