### ISSUE TITLE
Multiple versions of TypeScript installed for VS Code codebase

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#116503] opened 2021-02-11 21:59 UTC
Looking over our repos main `yarn.lock`, it seems we currently installing 3 copy of TypeScript:

```
typescript@^2.6.2:
  version "2.6.2"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-2.6.2.tgz#3c5b6fd7f6de0914269027f03c0946758f7673a4"
  integrity sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q=

typescript@^3.0.1:
  version "3.9.7"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-3.9.7.tgz#98d600a5ebdc38f40cb277522f12dc800e9e25fa"
  integrity sha512-BLbiRkiBzAwsjut4x/dsibSTB6yWpwT5qWmC2OfuCg3GgVQCSgMs4vEctYPhsaGtd0AeuuHMkjZ2h2WG8MSzRw==

# this is our main version used for compiling. Exact version number may differ
typescript@^4.3.0-dev.20210211:
  version "4.3.0-dev.20210211"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-4.3.0-dev.20210211.tgz#4ad889da82e02dc74df155d9f31c28a3f7154403"
  integrity sha512-Xy5pmfBIAYjHItLhqGASnEy3TVzUQNr82QDFspuSnU05Dpei2oZz7mw9FSyNWN0zddZ2twctKKQpYpv2nuRfZA==
```

The typescript package is fairly large (60MB) so it would be nice if we could only install a single copy. Currently the three copies end up consuming `180 / 550 MB = 30%` of our `node_modules` on disk size

**Comment by mjbvz** [comment] 2021-02-11 22:12
The extra copies come from packages we controls:

- `vscode-nls-dev` -> `typescript@2.6`
- `vscode-telemetry-extractor` -> `ts-morph` -> `typescript@3.0`

**Comment by joaomoreno** [comment] 2021-02-12 14:06
I have assigned the issue to the respective module owners. And here is my suggestion for both: make typescript a [peerDependency](https://medium.com/angular-in-depth/npm-peer-dependencies-f843f3ac4e7f) instead of a regular dependency.

**Comment by dbaeumer** [comment] 2021-02-15 08:40
Making TS a peer dependency in `vscode-nls-dev` makes it harder to use for all extension developers :-). At least it will require a major version increase since it is a breaking change.

**Comment by joaomoreno** [comment] 2021-02-15 09:04
Maybe @mjbvz can suggest an alternative solution?

**Comment by mjbvz** [comment] 2021-02-16 20:54
It should  be a peer dependency in my option. That way `vscode-nls-dev` is understands the same version of typescript that the package consumer is compiling

**Comment by dbaeumer** [comment] 2021-02-17 10:50
@mjbvz the problem is that `vscode-nls-dev` is a rewriting tool for JS. I use TS simple to get a nice JS parser and API. It has nothing to do with compiling TS. So making this a peer dependency makes the tool fail for people that don't need a TS compiler in their project.

**Comment by lramos15** [comment] 2021-02-17 15:44
I've reached out to the ts-morph team and they plan to bundle typescript.js into the ts-morph package to hopefully reduce the overall package size.

**Comment by joaomoreno** [comment] 2021-02-17 16:32
> I've reached out to the ts-morph team and they plan to bundle typescript.js into the ts-morph package to hopefully reduce the overall package size.

Wouldn't that mean that they would just inline TypeScript? So we would effectively still have more than one copy?

**Comment by lramos15** [comment] 2021-02-17 16:37
@joaomoreno Yes and no, they would package a minified version which is ~5.5MB versus the normal 60MB typescript package. This would remove the NPM dependency of typescript from their package.json effectively preventing us from downloading two. Additionally, the telemetry extractor is just a CI tool and not shipped within VS Code, so any packages it downloads get promptly thrown out after it's run meaning that any reduction in download size = faster builds which is an improvement. TS morph won't work with a peer dependency of typescript as each version of typescript breaks the package, the other option would be to keep updating the telemetry extractor whenever we can to stay in sync with the new version, but VS Code is often running the beta versions which aren't supported by ts-morph. Here's the issue I filed against their repo where the maintainer provided their feedback https://github.com/dsherret/ts-morph/issues/932

**Comment by dbaeumer** [comment] 2021-02-18 10:48
@Iramos15 can you explain how they package a minified version of TS?

**Comment by dsherret** [comment] 2021-02-18 15:31
@dbaeumer There's a lot of stuff in the typescript package that isn't necessary when just using the compiler api. It only needs to pull in typescript.js and the node_modules/typescript/lib/*.d.ts files (lib files). The lib files are already bundled and minified within ts-morph for the in memory file system host, so in the next version it's going to use that for the "real" file system host as well. The .d.ts files are minified with https://github.com/dsherret/dts-minify

**Comment by lramos15** [comment] 2021-03-30 13:39
I have bumped ts-morph in all our repros thanks to @dsherret for the help there 👍

**Comment by dbaeumer** [comment] 2022-12-05 19:13
@TylerLeonhardt assigning to you as the owner of nls :-). I think with the work you do right now with tree sitter for parsing this will go away anyways.

**Comment by TylerLeonhardt** [comment] 2022-12-06 21:51
We are slowly moving off of `vscode-nls` and `vscode-nls-dev` entirely so let's just ignore that and track it with https://github.com/microsoft/vscode/issues/166305

**Closed** 2022-12-06 21:51 UTC
Labels: engineering
