### ISSUE TITLE
Underscore character is hidden in integrated terminal

### ISSUE THREAD

**Issue by nhdhung** [Microsoft/vscode#38761] opened 2017-11-20 09:14 UTC
- VSCode Version: 1.18.1
- OS Version: Ubuntu (Unity)

Steps to Reproduce:

1. Open integrated terminal
2. Type something with underscore

Reproduces without extensions: Yes

**Comment by maxibanki** [comment] 2017-11-20 09:58
Duplicate of #35901

`"terminal.integrated.fontSize": 13`

Use this as a workaround.

**Comment by HaithamSweilem** [comment] 2017-11-22 10:04
Try changing the fontFamily to workaround this without changing fontSize:
`"terminal.integrated.fontFamily": "courier new"`

**Closed** 2017-12-11 14:44 UTC
Labels: *duplicate, integrated-terminal
