### ISSUE TITLE
Snippet scope unsaved

### ISSUE THREAD

**Issue by WORMSS** [microsoft/vscode#78681] opened 2019-08-08 07:47 UTC
Snippets that have a scope to a language do not work in a file that has not been saved yet to the file extension.

I do not wish to target 'plaintext' scope, because, I don't want to muddy the water with real text .txt scopes. (This will be a shared project snippet).

### Currently Use Case:

1. New File (Ctrl, N) (opens in plaintext scope)
2. go to use snippet (nothing, ARRRG)
3. Save file as MyNewFile.ts (to change it to typescript scope, yes, I could change the scope of the file, but my co-workers wouldn't remember how, saving the file is easiest way to explain)
4. go to use snippet (ahh, it's there, and it works)

I would like to eliminate steps 2 and 3.

I know new files open with the plaintext context, (but this is prob configurable?),
So I want to put something like
```
"scope": "ts,default-new",
```
or something along those lines.

### New Use Case
1. New File (Ctrl+N) (opens in plaintext, or what ever someone has configured)
2. go to use snippet (ahh, it's there, and it works).

**Comment by gjsjohnmurray** [comment] 2019-08-08 08:01
> I know new files open with the plaintext context, (but this is prob configurable?)

`"files.defaultLanguage": "typescript"`

**Comment by WORMSS** [comment] 2019-08-08 08:16
> > I know new files open with the plaintext context, (but this is prob configurable?)
> 
> `"files.defaultLanguage": "typescript"`

Yep, I thought it would be, but everything other than that line is the feature request.. I wasn't going to ask all co-workers to change their setup to allow a single snippet to work cross-team

**Comment by jrieken** [comment] 2019-08-08 09:20
> I wasn't going to ask all co-workers to change their setup to allow a single snippet 

You can make it a project setting in case the teams on a shared project. 

Closing this as duplicate of https://github.com/microsoft/vscode/issues/75955. Once that is implemented (properly) you should be able to target snippets by uri, like our document selectors, e.g. you can say "scope is typescript and all files with the untitled-scheme"

**Closed** 2019-08-08 09:23 UTC
Labels: *duplicate, snippets
