### ISSUE TITLE
git reset -p : Reset line per line (and maybe per block too)

### ISSUE THREAD

**Issue by maxime1992** [Microsoft/vscode#19118] opened 2017-01-24 08:37 UTC
it would be super nice to have the equivalent of `git reset -p`.

We can add and remove selectively what we want to be in staging or not, but I haven't find an option to reset lines/blocks.

Thanks for VSC, it's awesome :heart: !

**Comment by mousetraps** [comment] 2017-01-24 23:22
Actually, looks like it does exist! https://github.com/Microsoft/vscode/issues/10782#issuecomment-241966057

Closing as a duplicate of #6516, but lmk if you meant something different, an we can reopen.

**Closed by mousetraps** 2017-01-24 23:22 UTC

**Comment by maxime1992** [comment] 2017-01-25 07:13
@mousetraps I read the links you gave me but the working part are about stage/unstage.

But you can't reset a line https://github.com/Microsoft/vscode/issues/10782#issuecomment-241966520 https://github.com/Microsoft/vscode/issues/10782#issuecomment-241966057 .

I think this needs to be reopened, let me know if you have this option in your VSC but I couldn't find anything else than unstage.
