### ISSUE TITLE
Extention not listed if starting with a dot

### ISSUE THREAD

**Issue by realemx** [microsoft/vscode#111647] opened 2020-12-01 17:10 UTC
- VSCode Version: 1.51.1
- OS Version: Manjaro Linux - Kernel 5.4.80-2

Steps to Reproduce:

1. Search for [this extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet-test-explorer). It does not show under Linux, but it shows under Windows. 

My guess is, it's because the extension name starts with a dot. I've manually installed the extension with the .vsix file and it functions properly, but it still does not show up on the list of installed extensions.

**Comment by sandy081** [comment] 2020-12-01 17:57
It is nothing to with extension name. Your linux distribution of VS Code is not using VS Code Marketplace instead it is configured with Open VSIX. Hence you are not seeing it in linux.

**Comment by sandy081** [comment] 2020-12-01 17:57
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Closed by sandy081** 2020-12-01 17:57 UTC
