### ISSUE TITLE
command-line arg "-n" (and --new-window) fails to open new window

### ISSUE THREAD

**Issue by mmacy** [Microsoft/vscode#41874] opened 2018-01-19 17:07 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.0.0
LinkCheckMD|bla|0.1.5
vscode-markdownlint|Dav|0.12.1
json-tools|eri|1.0.2
gauntlet|Mic|2.6.0
python|ms-|0.9.1
azure-account|ms-|0.2.2
azurecli|ms-|0.4.0
csharp|ms-|1.13.1
vscode-docker|Pet|0.0.23
java|red|0.17.0
python|tht|0.2.3
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

---

**Steps to Reproduce:**

1. Open existing directory in VS Code: `code .`
2. Open existing directory with `-n` arg to force new window: `code -n .`

**Result:**
The previously opened VS Code window is displayed.

**Expected:**
A new instance of VS Code should open to the specified directory.

**Reproduces without extensions:** Yes

**Comment by bpasero** [comment] 2018-01-19 18:03
@mmacy this does not work because currently we do not allow to open the same folder in multiple windows. If you just type "`code -n`" it will work. 

Closing as duplicate of https://github.com/Microsoft/vscode/issues/2686

**Closed by bpasero** 2018-01-19 18:03 UTC

**Comment by mmacy** [comment] 2018-01-19 18:13
@bpasero Bummer! But thanks for the response. Would be pretty hot if somehow this could be automated when executing `code -n .`:

*create another Window and use the "Add Folder to Workspace" action to open your project a second time*

(from comment on [19793](https://github.com/Microsoft/vscode/issues/19793#issuecomment-344985923))
