### ISSUE TITLE
Outline View does not show function variables as functions in JavaScript

### ISSUE THREAD

**Issue by AnthonySLWhite** [Microsoft/vscode#67421] opened 2019-01-29 15:15 UTC
Version: 1.30.2 (system setup)
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
Steps to Reproduce:

1. Create a variable that is assigned a function
```javascript
const test = function() {...};
const anotherTest = (e)=>e
```
2. Outline view show this as a variable instead of a function. 
It's really annoying because it looks like everything else

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-01-29 20:01
Duplicate of https://github.com/Microsoft/TypeScript/issues/29036

**Closed by mjbvz** 2019-01-29 20:01 UTC
Labels: javascript
