### ISSUE TITLE
Proxy window stopped working

### ISSUE THREAD

**Issue by cullio** [microsoft/vscode#104637] opened 2020-08-14 09:31 UTC
Issue Type: <b>Bug</b>

When using a proxy, OK or CANCEL buttons on the proxy window are not responding.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (20.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.15.1
vscode-great-icons|emm|2.1.47
stylelint-plus|hex|0.52.10
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by gjsjohnmurray** [comment] 2020-08-14 09:38
Possible duplicate of #104603 which offers a workaround.

**Comment by cullio** [comment] 2020-08-14 09:58
Indeed this is a duplicate of #104603, and the workaround provided there works.

**Closed** 2020-08-14 09:58 UTC
Labels: new release
