### ISSUE TITLE
Cursor is not shown on correct position when resized

### ISSUE THREAD

**Issue by noushad-pp** [Microsoft/vscode#28174] opened 2017-06-07 08:55 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-darktooth|Poorchop|0.0.2|
|vscode-snazzy-operator|aaronthomas|1.1.3|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|
|Theme-Green|gerane|0.0.2|
|ewamvscadaptor|mphasiswyde|0.3.4|
|cordova-tools|vsmobile|1.2.7|
|vscode-react-native|vsmobile|0.3.2|
|Material-theme|zhuangtongfa|2.8.4|;

---

Steps to Reproduce:

1.Go in gull screen mode
2. Reduce the screen ratio by ctrl and - keys
3. click on any arbitrary point in the code.
4. Cursor is not displayed on the actual position

**Comment by alexandrudima** [comment] 2017-06-07 09:36
Duplicate of #26151

**Closed by alexandrudima** 2017-06-07 09:36 UTC
