### ISSUE TITLE
Language server keeps restarting on save

### ISSUE THREAD

**Issue by Sytten** [microsoft/vscode#108288] opened 2020-10-07 15:01 UTC
Hi there!
I have a very weird bug on MacOS 10.14.6 with VScode 1.49.3 and Typescript 3.
When I open VSCode the language server starts no problem and runs fine, but after some time (around 1h) if I hit save the server does a full restart every single time. This doesn't seem related to one particular project as I tested with multiple big typescript projects. This is particularly annoying because I lose all the contextual typing information until the server restarts.
This problem started recently (<1 month).
Not so sure how I can help debug it and find the root cause of the full restart?
Thanks for all the work 👍

**Comment by mjbvz** [comment] 2020-10-09 06:40
How do you know it is restarting? 

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by Sytten** [comment] 2020-10-10 00:00
I will test it this weekend. 
Well it says that it is restarting in the bottom left and I don't have any type hinting until it is restarted.

**Comment by mjbvz** [comment] 2020-10-20 03:29
Did you get a chance to test this?

**Comment by Sytten** [comment] 2020-10-20 21:50
Sorry lots of things pulling me this past few days, I did make some more observations though.
It seems that if something changes in the `node_modules` it starts to have this behaviour.
I am using [prisma](https://github.com/prisma/prisma) and it seems to happen if I generate the new client (basically they push some code in the `node_module`). Or maybe it's because it loads too much stuff from the node_modules. I will try a clean install.

**Comment by mjbvz** [comment] 2020-10-29 22:28
Closing this as we can't investigate without more information and steps to reproduce the problem. If you are still seeing the crash with extensions disabled, you can try collecting a log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Closed by mjbvz** 2020-10-29 22:28 UTC
Labels: needs more info

**Comment by pie6k** [comment] 2020-10-31 12:21
![CleanShot 2020-10-31 at 13 20 30](https://user-images.githubusercontent.com/7311462/97779049-e6ada880-1b7b-11eb-9394-b6e5b430dcb1.gif)


I've got pretty similar issue.

Every time I save the file, server gots restarted.

With 

```
[Info  - 12:15:07.357] Killing TS Server
[Info  - 12:15:07.357] Starting TS Server 
```

I'm trying to find some logs 

Here is my scenario of logs collecting

1. I set `"typescript.tsserver.log": "verbose"`
2. I wait for server to initialize and then I open the logs - I note last line of the logs before I save the file
3. I save any file in any way
4. I paste 'new logs' here:

```
Info 338  [13:18:16.815] request:
    {"seq":9,"type":"request","command":"getApplicableRefactors","arguments":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","startLine":1,"startOffset":1,"endLine":1,"endOffset":1}}
Perf 339  [13:18:16.856] 9::getApplicableRefactors: elapsed time (in milliseconds) 40.4733
Info 340  [13:18:16.856] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":9,"success":true,"body":[{"name":"Convert export","description":"Convert default export to named export","actions":[{"name":"Convert default export to named export","description":"Convert default export to named export","notApplicableReason":"Could not find export statement"}]},{"name":"Convert export","description":"Convert named export to default export","actions":[{"name":"Convert named export to default export","description":"Convert named export to default export","notApplicableReason":"Could not find export statement"}]},{"name":"Convert import","description":"Convert namespace import to named imports","actions":[{"name":"Convert namespace import to named imports","description":"Convert namespace import to named imports","notApplicableReason":"Selection is not an import declaration."}]},{"name":"Convert import","description":"Convert named imports to namespace import","actions":[{"name":"Convert named imports to namespace import","description":"Convert named imports to namespace import","notApplicableReason":"Selection is not an import declaration."}]},{"name":"Extract Symbol","description":"Extract function","actions":[{"description":"Extract function","name":"function_extract_error","notApplicableReason":"Cannot extract empty range."}]},{"name":"Extract Symbol","description":"Extract constant","actions":[{"description":"Extract constant","name":"constant_extract_error","notApplicableReason":"Cannot extract empty range."}]},{"name":"Extract type","description":"Extract type","actions":[{"name":"Extract to typedef","description":"Extract to typedef","notApplicableReason":"Selection is not a valid type node"},{"name":"Extract to type alias","description":"Extract to type alias","notApplicableReason":"Selection is not a valid type node"},{"name":"Extract to interface","description":"Extract to interface","notApplicableReason":"Selection is not a valid type node"}]},{"name":"Add or remove braces in an arrow function","description":"Add or remove braces in an arrow function","actions":[{"name":"Add braces to arrow function","description":"Add braces to arrow function","notApplicableReason":"Could not find a containing arrow function"},{"name":"Remove braces from arrow function","description":"Remove braces from arrow function","notApplicableReason":"Could not find a containing arrow function"}]}]}
Info 341  [13:18:16.859] request:
    {"seq":10,"type":"request","command":"projectInfo","arguments":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","needFileNameList":false}}
Perf 342  [13:18:16.860] 10::projectInfo: elapsed time (in milliseconds) 0.2701
Info 343  [13:18:16.860] response:
    {"seq":0,"type":"response","command":"projectInfo","request_seq":10,"success":true,"body":{"configFileName":"<ROOT>/packages/ui/tsconfig.json","languageServiceDisabled":false}}
Info 344  [13:18:17.35] request:
    {"seq":11,"type":"request","command":"getApplicableRefactors","arguments":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","startLine":54,"startOffset":5,"endLine":54,"endOffset":5}}
Perf 345  [13:18:17.37] 11::getApplicableRefactors: elapsed time (in milliseconds) 1.8753
Info 346  [13:18:17.37] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":11,"success":true,"body":[{"name":"Convert export","description":"Convert default export to named export","actions":[{"name":"Convert default export to named export","description":"Convert default export to named export","notApplicableReason":"Could not find export statement"}]},{"name":"Convert export","description":"Convert named export to default export","actions":[{"name":"Convert named export to default export","description":"Convert named export to default export","notApplicableReason":"Could not find export statement"}]},{"name":"Convert import","description":"Convert namespace import to named imports","actions":[{"name":"Convert namespace import to named imports","description":"Convert namespace import to named imports","notApplicableReason":"Selection is not an import declaration."}]},{"name":"Convert import","description":"Convert named imports to namespace import","actions":[{"name":"Convert named imports to namespace import","description":"Convert named imports to namespace import","notApplicableReason":"Selection is not an import declaration."}]},{"name":"Extract Symbol","description":"Extract function","actions":[{"description":"Extract function","name":"function_extract_error","notApplicableReason":"Cannot extract empty range."}]},{"name":"Extract Symbol","description":"Extract constant","actions":[{"description":"Extract constant","name":"constant_extract_error","notApplicableReason":"Cannot extract empty range."}]},{"name":"Extract type","description":"Extract type","actions":[{"name":"Extract to typedef","description":"Extract to typedef","notApplicableReason":"Selection is not a valid type node"},{"name":"Extract to type alias","description":"Extract to type alias","notApplicableReason":"Selection is not a valid type node"},{"name":"Extract to interface","description":"Extract to interface","notApplicableReason":"Selection is not a valid type node"}]},{"name":"Generate 'get' and 'set' accessors","description":"Generate 'get' and 'set' accessors","actions":[{"name":"Generate 'get' and 'set' accessors","description":"Generate 'get' and 'set' accessors","notApplicableReason":"Could not find property for which to generate accessor"}]},{"name":"Add or remove braces in an arrow function","description":"Add or remove braces in an arrow function","actions":[{"name":"Add braces to arrow function","description":"Add braces to arrow function","notApplicableReason":"Containing function is not an arrow function"},{"name":"Remove braces from arrow function","description":"Remove braces from arrow function","notApplicableReason":"Containing function is not an arrow function"}]}]}
Info 347  [13:18:17.119] request:
    {"seq":12,"type":"request","command":"geterr","arguments":{"delay":0,"files":["<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx"]}}
Perf 348  [13:18:17.120] 12::geterr: async elapsed time (in milliseconds) 0.2861
Info 349  [13:18:17.121] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","diagnostics":[]}}
Info 350  [13:18:17.121] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","diagnostics":[]}}
Info 351  [13:18:17.122] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","diagnostics":[{"start":{"line":2,"offset":1},"end":{"line":2,"offset":63},"text":"'useMethod' is declared but its value is never read.","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":3,"offset":10},"end":{"line":3,"offset":25},"text":"'AnimatePresence' is declared but its value is never read.","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":4,"offset":1},"end":{"line":4,"offset":32},"text":"'useRef' is declared but its value is never read.","code":6133,"category":"suggestion","reportsUnnecessary":true}]}}
Info 352  [13:18:17.122] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":12}}
Info 353  [13:18:17.816] request:
    {"seq":13,"type":"request","command":"updateOpen","arguments":{"changedFiles":[{"fileName":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","textChanges":[{"newText":"\n  ","start":{"line":54,"offset":5},"end":{"line":54,"offset":5}}]}],"closedFiles":[],"openFiles":[]}}
Perf 354  [13:18:17.816] 13::updateOpen: elapsed time (in milliseconds) 0.4213
Info 355  [13:18:17.816] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":13,"success":true,"body":true}
Info 356  [13:18:18.10] request:
    {"seq":14,"type":"request","command":"updateOpen","arguments":{"changedFiles":[{"fileName":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","textChanges":[{"newText":"2","start":{"line":55,"offset":3},"end":{"line":55,"offset":3}}]}],"closedFiles":[],"openFiles":[]}}
Perf 357  [13:18:18.11] 14::updateOpen: elapsed time (in milliseconds) 1.1559
Info 358  [13:18:18.11] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":14,"success":true,"body":true}
Info 359  [13:18:18.60] request:
    {"seq":15,"type":"request","command":"getApplicableRefactors","arguments":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","startLine":55,"startOffset":4,"endLine":55,"endOffset":4}}
Info 360  [13:18:18.60] Starting updateGraphWorker: Project: <ROOT>/packages/ui/tsconfig.json
Info 361  [13:18:18.88] Finishing updateGraphWorker: Project: <ROOT>/packages/ui/tsconfig.json Version: 2 structureChanged: false Elapsed: 28ms
Info 362  [13:18:18.88] Different program with same set of files:: oldProgram.structureIsReused:: 2
Perf 363  [13:18:18.89] 15::getApplicableRefactors: elapsed time (in milliseconds) 28.5654
Info 364  [13:18:18.89] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":15,"success":true,"performanceData":{"updateGraphDurationMs":28},"body":[{"name":"Convert export","description":"Convert default export to named export","actions":[{"name":"Convert default export to named export","description":"Convert default export to named export","notApplicableReason":"Could not find export statement"}]},{"name":"Convert export","description":"Convert named export to default export","actions":[{"name":"Convert named export to default export","description":"Convert named export to default export","notApplicableReason":"Could not find export statement"}]},{"name":"Convert import","description":"Convert namespace import to named imports","actions":[{"name":"Convert namespace import to named imports","description":"Convert namespace import to named imports","notApplicableReason":"Selection is not an import declaration."}]},{"name":"Convert import","description":"Convert named imports to namespace import","actions":[{"name":"Convert named imports to namespace import","description":"Convert named imports to namespace import","notApplicableReason":"Selection is not an import declaration."}]},{"name":"Extract Symbol","description":"Extract function","actions":[{"description":"Extract function","name":"function_extract_error","notApplicableReason":"Cannot extract empty range."}]},{"name":"Extract Symbol","description":"Extract constant","actions":[{"description":"Extract constant","name":"constant_extract_error","notApplicableReason":"Cannot extract empty range."}]},{"name":"Extract type","description":"Extract type","actions":[{"name":"Extract to typedef","description":"Extract to typedef","notApplicableReason":"Selection is not a valid type node"},{"name":"Extract to type alias","description":"Extract to type alias","notApplicableReason":"Selection is not a valid type node"},{"name":"Extract to interface","description":"Extract to interface","notApplicableReason":"Selection is not a valid type node"}]},{"name":"Generate 'get' and 'set' accessors","description":"Generate 'get' and 'set' accessors","actions":[{"name":"Generate 'get' and 'set' accessors","description":"Generate 'get' and 'set' accessors","notApplicableReason":"Could not find property for which to generate accessor"}]},{"name":"Add or remove braces in an arrow function","description":"Add or remove braces in an arrow function","actions":[{"name":"Add braces to arrow function","description":"Add braces to arrow function","notApplicableReason":"Containing function is not an arrow function"},{"name":"Remove braces from arrow function","description":"Remove braces from arrow function","notApplicableReason":"Containing function is not an arrow function"}]}]}
Info 365  [13:18:18.120] request:
    {"seq":16,"type":"request","command":"geterr","arguments":{"delay":0,"files":["<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx"]}}
Perf 366  [13:18:18.120] 16::geterr: async elapsed time (in milliseconds) 0.1721
Info 367  [13:18:18.122] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","diagnostics":[]}}
Info 368  [13:18:18.392] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","diagnostics":[]}}
Info 369  [13:18:18.392] request:
    {"seq":17,"type":"request","command":"updateOpen","arguments":{"changedFiles":[{"fileName":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","textChanges":[{"newText":";","start":{"line":55,"offset":4},"end":{"line":55,"offset":4}}]}],"closedFiles":[],"openFiles":[]}}
Perf 370  [13:18:18.392] 17::updateOpen: elapsed time (in milliseconds) 0.1161
Info 371  [13:18:18.393] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":17,"success":true,"body":true}
Info 372  [13:18:18.393] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":16}}
Info 373  [13:18:18.393] request:
    {"seq":18,"type":"request","command":"getApplicableRefactors","arguments":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","startLine":55,"startOffset":5,"endLine":55,"endOffset":5}}
Info 374  [13:18:18.393] Starting updateGraphWorker: Project: <ROOT>/packages/ui/tsconfig.json
Info 375  [13:18:18.413] Finishing updateGraphWorker: Project: <ROOT>/packages/ui/tsconfig.json Version: 3 structureChanged: false Elapsed: 20ms
Info 376  [13:18:18.413] Different program with same set of files:: oldProgram.structureIsReused:: 2
Perf 377  [13:18:18.414] 18::getApplicableRefactors: elapsed time (in milliseconds) 21.2609
Info 378  [13:18:18.414] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":18,"success":true,"performanceData":{"updateGraphDurationMs":20},"body":[{"name":"Convert export","description":"Convert default export to named export","actions":[{"name":"Convert default export to named export","description":"Convert default export to named export","notApplicableReason":"Could not find export statement"}]},{"name":"Convert export","description":"Convert named export to default export","actions":[{"name":"Convert named export to default export","description":"Convert named export to default export","notApplicableReason":"Could not find export statement"}]},{"name":"Convert import","description":"Convert namespace import to named imports","actions":[{"name":"Convert namespace import to named imports","description":"Convert namespace import to named imports","notApplicableReason":"Selection is not an import declaration."}]},{"name":"Convert import","description":"Convert named imports to namespace import","actions":[{"name":"Convert named imports to namespace import","description":"Convert named imports to namespace import","notApplicableReason":"Selection is not an import declaration."}]},{"name":"Extract Symbol","description":"Extract function","actions":[{"description":"Extract function","name":"function_extract_error","notApplicableReason":"Cannot extract empty range."}]},{"name":"Extract Symbol","description":"Extract constant","actions":[{"description":"Extract constant","name":"constant_extract_error","notApplicableReason":"Cannot extract empty range."}]},{"name":"Extract type","description":"Extract type","actions":[{"name":"Extract to typedef","description":"Extract to typedef","notApplicableReason":"Selection is not a valid type node"},{"name":"Extract to type alias","description":"Extract to type alias","notApplicableReason":"Selection is not a valid type node"},{"name":"Extract to interface","description":"Extract to interface","notApplicableReason":"Selection is not a valid type node"}]},{"name":"Generate 'get' and 'set' accessors","description":"Generate 'get' and 'set' accessors","actions":[{"name":"Generate 'get' and 'set' accessors","description":"Generate 'get' and 'set' accessors","notApplicableReason":"Could not find property for which to generate accessor"}]},{"name":"Add or remove braces in an arrow function","description":"Add or remove braces in an arrow function","actions":[{"name":"Add braces to arrow function","description":"Add braces to arrow function","notApplicableReason":"Containing function is not an arrow function"},{"name":"Remove braces from arrow function","description":"Remove braces from arrow function","notApplicableReason":"Containing function is not an arrow function"}]}]}
Info 379  [13:18:18.581] request:
    {"seq":19,"type":"request","command":"geterr","arguments":{"delay":0,"files":["<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx"]}}
Perf 380  [13:18:18.581] 19::geterr: async elapsed time (in milliseconds) 0.1475
Info 381  [13:18:18.581] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"<ROOT>/packages/ui/dnd/ZoneDropIndicator.tsx","diagnostics":[]}}
```

Note I've masked my original files paths with <ROOT>

I don't see any meaningful information there

**Comment by mjbvz** [comment] 2020-10-31 18:53
@pi1024e When this happens, in VS Code run `Developer: Toggle developer tools` and look in the developer tools console. Are there are TS errors in there?

**Comment by pie6k** [comment] 2020-11-02 12:26
<img width="885" alt="CleanShot 2020-11-02 at 13 21 50@2x" src="https://user-images.githubusercontent.com/7311462/97867575-653a4f80-1d0e-11eb-9650-7c35f370a5a3.png">

I've got such logs.

I've also found another interesting thing.

I've tried to create vs-code workspaces for my monorepo (I've got multiple typescript packages).

When I've created new workspace folder for each package and open workspace instead of root folder - changes are not restarting the tsserver.

I've checked if I have proper 'exclude' 'include' in tsconfig files and they seems correct.

I'm having root tsconfig that other files are extending from.

So in general I'm able to have ts working at all again, which is great, and it also seems to be a bit faster in workspace setup, but still I have no idea what is causing it to restart on any change in previous setup.

It seems like some conflict between packages.

Note
My packages are never 'compiled'. IE I have `app` and `ui` packages.

`app` is using `ui`.

`ui/index.ts` is never compiled into something like `ui/index.js`. Instead - it is compiled by `app` that is using it when bundling.

**Comment by Sytten** [comment] 2020-11-02 15:59
I have a similar setup, but I also have multiple tsconfig per project for tests and main source file. From what I understood, vscode has a hard time dealing with multiple files.
I also have this log in the console:
```
[Extension Host] File /Users/Sytten/Projects/*****/ds2/node_modules/@****/api/prisma/schema.prisma has been changed. Restarting TS Server.
```
What is even weirder is that a prisma file is not even relevant to TS.

**Comment by pie6k** [comment] 2020-11-02 16:20
I can also confirm that disabling prisma extension solves the issue.

I have similar setup to @Sytten - monorepo with multiple packages written in typescript.

**Comment by Sytten** [comment] 2020-11-03 21:42
It should be fixed now @pie6k, thanks for sticking with us @mjbvz
