### ISSUE TITLE
'Initializing JS/TS Features' permanent message and no JS Intellisense

### ISSUE THREAD

**Issue by Zoggite** [microsoft/vscode#109299] opened 2020-10-24 15:01 UTC
Steps to reproduce:
1. Install latest VS Code version downloaded from web site
2. Go to 'Help > Interactive Playground'
Message '_Initializing JS/TS Features_' appears at bottom and never disappears. Hovering over JS code in the 'Interactive Playground' produces a tooltip window with '_(loading ...) any_' in it.

I've tried uninstalling and reinstalling and rebooting (no change).
Some reports I've found talk about the 'JavaScript/Typescript Language Features' builtin extension but that does not appear in my system (There are separate Javascript and Typescript 'Language Basics' Extensions - both enabled).
Some reports talk about typing 'Typescript: Restart TS Server' into the Command palette, but if I put 'Typescript' into the palette I get 'No Matching Commands'.

Just to reiterate, this is a brand new install on a machine that has never had VS Code on it. I have no extensions nor any code loaded.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (3.06GB free)|
|Process Argv|--crash-reporter-id 44c0f21e-017a-461b-afaf-31c27a7afabf|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment] 2020-10-26 23:07
Duplicate of #108454

**Closed by mjbvz** 2020-10-26 23:07 UTC
