### ISSUE TITLE
"Go to file" Opening a file doesn't show it's content

### ISSUE THREAD

**Issue by dolevillusive** [Microsoft/vscode#60528] opened 2018-10-10 16:03 UTC
Issue Type: <b>Bug</b>

Use the "Go To File" select an unopened file
If the file is already opened code will show it's content, but if doesn't the file content window will be empty

VS Code version: Code - Insiders 1.29.0-insider (cc5e2b41c3add18a31e87f84b5d6162566a38d6e, 2018-10-10T05:19:52.883Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (16.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.17.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
confluence-markup|den|0.1.4
githistory|don|0.4.3
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
gitlens|eam|8.5.6
gc-excelviewer|Gra|2.1.26
cypher-query-language|jak|1.0.2
vs-color-picker|lih|0.7.0
MagicPython|mag|1.1.0
prettify-json|moh|0.0.3
python|ms-|2018.9.0
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|0.3.735
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.27.0
code-spell-checker|str|1.6.10
vscodeintellicode|Vis|1.0.4
jinja|who|0.0.8
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-10-11 05:03
@dolevillusive can you clear the list of recently opened files and do testing again? We had a recent bug in this area that was fixed but for some reason it requires the history to be emptied. 

Marking as duplicate of https://github.com/Microsoft/vscode/issues/60163

**Closed by bpasero** 2018-10-11 05:03 UTC
