### ISSUE TITLE
On hover tooltip flashes if scrolling position lefts a part of the hoverable outside of the view.

### ISSUE THREAD

**Issue by anurbol** [microsoft/vscode#71493] opened 2019-03-30 22:58 UTC
- VSCode Version: 1.32.3
- OS Version: Lubuntu

Steps to Reproduce:

1. Scroll right so that some symbol partly is left out of the visible area.
2. Hover over that symbol.
3. Enjoy the flash (see in the gif)

![vsbug](https://user-images.githubusercontent.com/3603448/55282601-3eb57500-5371-11e9-9a96-8f357d0e9c8d.gif)

Does this issue occur when all extensions are disabled?: Yes/No
YES.

P.S. I am surprised that this bug lives to the day, I saw it so many times. But I also couldn't find an issue describing the same bug.

**Comment by chenruyi** [comment] 2019-04-01 10:34
I test this in windows 10, It reproduced. 
Code Version: 1.32.3
It seems that this is can be reproduced if the symbol left first letter hidden even if some pixel.
js:
![2019-04-01_18-33-39](https://user-images.githubusercontent.com/24762361/55321611-b89e4900-54ac-11e9-8aed-f587e8a1425e.gif)

**Comment by imjakey** [comment] 2019-04-04 09:39
I have the same issue, 
My Env :
OS :  WINDOW 10
VsCode Version: 1.32.3

![tooltip-flash](https://user-images.githubusercontent.com/2662273/55545339-994b2a00-56ff-11e9-8266-cae6633d3c3b.gif)

In my case, the tooltip need to show two message from PHP IntelliSense plugin and PHP Phan (Analyzer), if i disable any one, it works fine.

**Comment by anurbol** [comment] 2019-04-04 18:11
@imjakey seems like you have an issue that is non relevant to this one.

**Comment by georgejiang97** [comment] 2019-04-08 02:56
Hey! Could I try taking this one? I'm new to open source contributions, so any pointers would be very helpful. @anurbol @joaomoreno (Sorry, I don't know who to ping regarding this)

**Comment by tamuratak** [comment] 2019-04-09 00:44
Duplicate of #51794?

**Closed** 2019-07-22 08:33 UTC
Labels: bug, editor-hover, help wanted

**Comment by SSJ9899TDylan** [comment] 2019-07-22 08:36
Bruh
Sent by Dylan Taylor
