### ISSUE TITLE
VSCode thinks I have a task running

### ISSUE THREAD

**Issue by j-marcon** [microsoft/vscode#139149] opened 2021-12-15 01:00 UTC
Issue Type: <b>Bug</b>

I'm on today's VSCode Insiders version and the problem appeared for the first time either in yesterday's or today's version. After starting a new session of VSCode, the first time I run a task (from my tasks.json), it runs fine and terminates properly. The second time I try to start it, I get the following 2 errors messages:

`There are task errors. See the output for details.`

`There is already a task running. Terminate it first before executing another task.`

When I click on "Show output" (first message), the task output is empty. When I click on "Terminate Task" (second message), it tells me that "No task is currently running".

For information, this workflow worked well as of a couple of days ago. Any help appreciated.

VS Code version: Code - Insiders 1.64.0-insider (886fd126446cd4b8b03f2b32f09c173dec541e6d, 2021-12-14T13:26:59.630Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

**Comment by alexr00** [comment] 2021-12-15 07:38
Duplicate of https://github.com/microsoft/vscode/issues/139089

**Closed by alexr00** 2021-12-15 07:38 UTC
