### ISSUE TITLE
Opening a notebook sometimes shows the plaintext view

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99484] opened 2020-06-05 19:37 UTC
Found verifying #99233.

Have two notebook files, with one open. Reload.

While notebook is loading, open the other notebook from explorer. See plaintext notebook content.

**Comment by rebornix** [comment] 2020-06-29 21:35
/duplicate of https://github.com/microsoft/vscode/issues/96446

**Closed by rebornix** 2020-06-29 21:35 UTC
Labels: notebook
