### ISSUE TITLE
Extension build specifying VS Code 1.55-insider engine is treated as compatible with VS Code 1.55 stable

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#120274] opened 2021-03-31 22:22 UTC
The Jupyter extension uses the engine property in our package.json to release builds of our extension that get downloaded for VS Code insiders only, e.g.

```
    "engines": {
        "vscode": "1.55.0-insider"
    },
```

If an extension build published to the marketplace specifies 1.55.0-insider, it shows up as a viable alternative in stable VS Code 1.55. 

/cc @rebornix @rchiodo @DonJayamanne @IanMatthewHuff @DavidKutu

**Comment by DonJayamanne** [comment] 2021-04-02 15:32
@sandy081 
The problem here is we were under the impression that extensions targetting 1.55.0-insiders could not be installe in 1.55.0 stable. 
At least that was our assumption, however it does make sense if this is how it works.

Is there a way for us to ensure extensions :
* can only be installed & run in VS Code Insiders & not stable.
* When in extensions tab, only those extensions are displayed that target VS Code insiders & similarly when a user is in stable, they will not see extensions that target the insiders.

The reason is we'd like to ensure users don't see the insider builds of our extensions when in VS Code Stable.

@rebornix /cc

**Comment by sandy081** [comment] 2021-04-06 12:59
> If an extension build published to the marketplace specifies 1.55.0-insider, it shows up as a viable alternative in stable VS Code 1.55.

Even though this extension is shown for stable, we always try to install the compatible extension which means the extension with vscode engine set to `"1.55.0-insider"` is ignored in VS Code stable. Have you tried installing from the stable and checked?

**Comment by DonJayamanne** [comment] 2021-04-06 14:40
> with vscode engine set to "1.55.0-insider" is ignored in VS Code stable

I can confirm this doesnt work as expecred.

The following version is available for stable VS Code - `2021.5.697286501`.
This version targets `1.55.0-insiders` (package.json).
I.e. i was able to select this from the list of versions avaialble in VS Code stable.

**Comment by sandy081** [comment] 2021-04-16 12:35
Assigning to April for investigation

**Comment by DonJayamanne** [comment] 2021-04-28 20:30
@sandy081 do we know what's going to happen here, we'll have another release soon and we could run into this same issue once again.
Should this be escalated?

**Comment by sandy081** [comment] 2021-04-29 12:42
@DonJayamanne I just tried to install the Jupyter extension in stable and it works as expected. By this I mean

- It shows the latest version that is available in MP 

<img width="366" alt="Screenshot 2021-04-29 at 18 09 14" src="https://user-images.githubusercontent.com/10746682/116551958-1dd7f900-a916-11eb-92c8-9e8d45a1600f.png">

- When asked to install, VS Code installs the latest compatible version 

<img width="938" alt="Screenshot 2021-04-29 at 18 06 20" src="https://user-images.githubusercontent.com/10746682/116551736-d6ea0380-a915-11eb-8601-8bd12319e675.png">

May I know if you are seeing the same otherwise please provide me the steps you are following (also any screenshots would be helpful).

**Comment by rebornix** [comment] 2021-05-04 23:02
@sandy081 VS Code has no issue downloading the latest compatible version, whose engine is `^1.55.2` but you can still select an older version which was targeting `1.55-insiders`.

**Comment by rchiodo** [comment] 2021-05-04 23:04
With the 1.56 version that's about to go out you can see this happening:

Jupyter extension lists all of the 'insiders' only builds that we pushed to the marketplace. It should still be on the 2021.5 versions:

![image](https://user-images.githubusercontent.com/19672699/117080309-6d416f00-acf2-11eb-87de-aa04a0468245.png)

**Comment by DonJayamanne** [comment] 2021-05-19 14:34
@sandy081 any chance we can reopen this?
We've been running into this issue for a few months now

**Comment by sandy081** [comment] 2021-10-06 12:17
> If an extension build published to the marketplace specifies 1.55.0-insider, it shows up as a viable alternative in stable VS Code 1.55.

We follow semever and as per semver rules - https://semver.org/#spec-item-11, this is correct. 1.55.0-insider < 1.55.x and hence it is compatible.

This seems to be the very specific problem we are discussing here - https://github.com/microsoft/vscode/issues/15756#issuecomment-916728348

Please provide your feedback there.

**Closed by sandy081** 2021-10-06 12:17 UTC
