### ISSUE TITLE
Go menu is not working

### ISSUE THREAD

**Issue by ganeshguptaql2** [microsoft/vscode#97690] opened 2020-05-13 09:03 UTC
Hi There,

I have installed version : 1.45.0 (user setup) and I am working on typescript react and node js code.
**I am facing a problem with go menu and after right click on workspace, not showing go to options.** also I have installed ''Go extension '' https://code.visualstudio.com/docs/languages/go 

Please guide me how to fix this issues. 

Thanks and Regards,
Ganesh kumar gupta

**Comment by alexdima** [comment] 2020-05-13 09:35
@ganeshguptaql2 Do you mean you don't see the "Go to Definition" and other commands like that in the context menu? What file type do you have opened when you right click?

![image](https://user-images.githubusercontent.com/5047891/81796409-b14dc980-950d-11ea-9357-23f452accdde.png)

**Comment by ganeshguptaql2** [comment] 2020-05-13 09:46
![image](https://user-images.githubusercontent.com/59866023/81797373-4f508c80-952c-11ea-8020-797c8d13263e.png)
![image](https://user-images.githubusercontent.com/59866023/81797426-68593d80-952c-11ea-9f19-1c13ecf3ed3e.png)

Go to definition
Go to Type definition
Go to implementations
Go to References

These options not working in my vs code workspace.

**Comment by mjbvz** [comment] 2020-05-13 18:54
Have you disabled the builtin JavaScript and TypeScript extension. Search `@builtin javascript` in the extension views and make sure this extension is enabled:

![Screen Shot 2020-05-13 at 11 54 21 AM](https://user-images.githubusercontent.com/12821956/81852840-7dc06e80-9510-11ea-88dc-c27774fa09ce.png)

**Comment by ganeshguptaql2** [comment] 2020-05-14 03:55
![image](https://user-images.githubusercontent.com/59866023/81890819-79558d80-95c4-11ea-87c8-225ef25e7efd.png)

**TypeScript and JavaScript Language Features**  Yes this extension is not disable.

**Comment by ganeshguptaql2** [comment] 2020-05-14 10:09
Please help me... I am facing a lot of problems. I am not able to catch and reduce the error and cannot get into error files so please help me...Please as a request.
**Go to definition
Go to Type definition
Go to implementations
Go to References**

**Comment by mjbvz** [comment] 2020-05-14 19:08
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by ganeshguptaql2** [comment] 2020-05-15 15:56
It's almost working but ctrl+click is not working. If you have any ideas please share.

**Comment by mjbvz** [comment] 2020-05-15 17:48
Have you changed the `editor.multiCursorModifier` setting?

**Comment by ganeshguptaql2** [comment] 2020-05-16 13:56
Hi Every One,
It's very Important for all........ If you will facing same problem then Please follow this guide line........
**Step one(1) Disable all extensions in VS code.
Steps Two (2) Go to this path and delete all Extensions  C:\Users\ganesh_gupta\.vscode\extensions 
Then fix this issue** 👍  

Thanks Guys For the help 👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by mjbvz** [comment] 2020-05-18 20:37
Ok, closing since it sounds like the issue is fixed

**Closed by mjbvz** 2020-05-18 20:37 UTC
Labels: needs more info
