### ISSUE TITLE
Syntax error in scss/sass map

### ISSUE THREAD

**Issue by andrefarzat** [Microsoft/vscode#17706] opened 2016-12-21 23:04 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.7.1|
|theme-material-theme|jprestidge|1.0.1|
|vscode-scss|mrmlnc|0.6.0|
|vscode-icons|robertohuertasm|4.2.0|

---

Steps to Reproduce:

1. Create a new scss file
2. Create a [map](https://www.sitepoint.com/using-sass-maps/). ex:
```scss
$colors: (
    home: #083b7a,
    assignments: #28abdf,
    groups: #ee5935,
    clients: #1a77b9,
    office: #902c8e,
    staff: #bc2333,
    events: #28abdf,
    library: #9c2361,
);
```
3. The syntax parser complains about it (line 34 and 35 of the following print):
![screen shot 2016-12-21 at 6 01 51 pm](https://cloud.githubusercontent.com/assets/649219/21409344/c042b55e-c7a7-11e6-9822-43de7417957a.png)

**Comment by Aarilight** [comment] 2016-12-26 06:57
+1. When this is implemented it may be a good idea to add map support for `@each` as well:

```
$map: (
  prop1: val1,
  prop2: val2
);
@each $prop, $val in $map {
  do-something-with: $prop $val;
}
```

**Comment by mrmlnc** [comment] 2016-12-26 07:41
@egamma, it seems to me, this is duplicate of #1758 🐼

**Comment by egamma** [comment] 2016-12-29 19:29
Marking as a duplicate of #1758 as suggested.

Thanks @mrmlnc

**Closed by egamma** 2016-12-29 19:29 UTC
Labels: duplicate
