### ISSUE TITLE
End of HTML comments failing

### ISSUE THREAD

**Issue by Sethvg** [Microsoft/vscode#36504] opened 2017-10-18 16:43 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/5665290/31731055-afe9d448-b3e8-11e7-8238-f2f266621fda.png)

Html Comment styling continues past end of comments.

**Comment by mjbvz** [comment] 2017-10-19 00:10
Duplicate of #33944 which is now being tracked upstream by https://github.com/textmate/html.tmbundle/issues/75

**Closed by mjbvz** 2017-10-19 00:10 UTC
Labels: duplicate
