### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by rabinosona** [Microsoft/vscode#71805] opened 2019-04-05 15:37 UTC
Issue Type: <b>Bug</b>

Update the VSCode to the latest version.
Try to type in keywords or paths inside the TS code.
Nothing happens, the formatting does not work properly too.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3203)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.06GB free)|
|Process Argv|D:\SierraGold\NetQuery-UI-ReactJS|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-components|jpo|0.0.26
angelscript|ren|1.0.1
linter-xo|sam|2.3.2
quokka-vscode|Wal|1.0.205

</details>

**Comment by luisrudge** [comment] 2019-04-05 16:22
same issue

**Comment by shaun-sweet** [comment] 2019-04-05 18:29
also have been experiencing the same issue since the latest release has hit.

**Comment by mjbvz** [comment] 2019-04-05 19:09
Likely a duplicate of #71751 

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for possible workarounds

@rabinosona If that doesn't solve the issue for you, please let me know

**Comment by rabinosona** [comment] 2019-04-06 05:13
This guide didn't help me out.

My current TS version (the workspace one):

![image](https://user-images.githubusercontent.com/17945174/55665189-7c1f7400-5843-11e9-9abb-be5f1c9d6060.png)

My current package.json file:

>{
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1",
		"start": "parcel ./public/index.html",
		"dev": "NODE_ENV=development parcel ./public/index.html",
		"build": "NODE_ENV=production parcel build --experimental-scope-hoisting ./public/index.html",
		"pretty-quick": "pretty-quick",
		"precommit": "pretty-quick --staged"
	},
	"devDependencies": {
		"@babel/core": "^7.4.0",
		"@babel/plugin-proposal-class-properties": "^7.4.0",
		"@babel/plugin-transform-runtime": "^7.4.0",
		"@babel/preset-env": "^7.4.2",
		"@babel/preset-react": "^7.0.0",
		"@types/react": "^16.8.10",
		"@types/react-dom": "^16.8.3",
		"@types/react-redux": "^7.0.6",
		"@types/react-router-dom": "^4.3.1",
		"@types/styled-components": "^4.1.12",
		"@types/webpack-env": "^1.13.9",
		"@typescript-eslint/eslint-plugin": "^1.5.0",
		"@typescript-eslint/parser": "^1.5.0",
		"babel-eslint": "^10.0.1",
		"eslint": "^5.16.0",
		"eslint-config-prettier": "^4.1.0",
		"eslint-plugin-ava": "^6.0.0",
		"eslint-plugin-import": "^2.16.0",
		"eslint-plugin-no-use-extend-native": "^0.4.0",
		"eslint-plugin-prettier": "^3.0.1",
		"eslint-plugin-promise": "^4.1.1",
		"eslint-plugin-react": "^7.12.4",
		"eslint-plugin-react-hooks": "^1.6.0",
		"eslint-plugin-unicorn": "^8.0.1",
		"husky": "^1.3.1",
		"parcel-bundler": "^1.12.3",
		"parcel-plugin-bundle-visualiser": "^1.2.0",
		"parcel-plugin-imagemin": "^2.1.3",
		"postcss-modules": "^1.4.1",
		"postcss-nested": "^4.1.2",
		"prettier": "1.16.4",
		"pretty-quick": "^1.10.0",
		"react-dom": "^16.8.6",
		"react-hot-loader": "^4.8.2",
		"typescript": "^3.3.4000"
	},
	"dependencies": {
		"@babel/polyfill": "^7.4.0",
		"@babel/runtime": "^7.4.2",
		"@babel/runtime-corejs2": "^7.4.2",
		"@hot-loader/react-dom": "^16.8.6",
		"@syncfusion/ej2-react-buttons": "^17.1.38",
		"@syncfusion/ej2-react-grids": "^17.1.38",
		"@syncfusion/ej2-react-inputs": "^17.1.38",
		"@types/react-fontawesome": "^1.6.4",
		"@types/react-redux": "^7.0.6",
		"@types/react-router-dom": "^4.3.1",
		"@types/styled-components": "^4.1.5",
		"astroturf": "^0.9.2",
		"connected-react-router": "^6.3.2",
		"font-awesome": "^4.7.0",
		"greenlet": "^1.0.1",
		"history": "^4.9.0",
		"immutable": "^4.0.0-rc.12",
		"line-awesome": "^1.0.2",
		"modern-normalize": "^0.5.0",
		"parcel": "^1.12.3",
		"react": "^16.8.6",
		"react-animations": "^1.0.0",
		"react-fontawesome": "^1.6.1",
		"react-redux": "^6.0.1",
		"react-router": "^5.0.0",
		"react-router-dom": "^5.0.0",
		"redux": "^4.0.1",
		"redux-devtools-extension": "^2.13.8",
		"redux-saga": "^1.0.2",
		"reselect": "^4.0.0",
		"semantic-ui-css": "^2.4.1",
		"semantic-ui-react": "^0.86.0",
		"styled-components": "^4.2.0"
	},
	"name": "NetQuery-UI-ReactJS",
	"version": "1.0.0",
	"main": "imagemin.config.js",
	"repository": {
		"type": "git",
		"url": "git+https://github.com/saisierragold/NetQuery-UI-ReactJS.git"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"bugs": {
		"url": "https://github.com/saisierragold/NetQuery-UI-ReactJS/issues"
	},
	"homepage": "https://github.com/saisierragold/NetQuery-UI-ReactJS#readme",
	"description": ""
}

The caches are cleared too.

**Comment by mjbvz** [comment] 2019-04-15 22:51
@rabinosona  Can you share your project?

**Comment by osogrizz** [comment] 2019-04-16 18:09
I am having issues with auto completion as well. It first noticed it sometime last week.

Expected: Pressing tab either tabs 4 spaces or auto completes inputed text.

Results: Tab key does not function at all. No spaces added. No auto complete. Instead I receive error:  
`command 'emmet.expandAbbreviation' not found`

One note, if I set `emmet.expandAbbreviation: false`,  my tab key works again (adding spaces). I don't receive any errors but obviously there is no auto complete functionality in that case.

Also I am not seeing performance issues experienced in #71751.

These are my emmet settings:

{
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Atom One Dark",
    "files.associations": {
        "*.js": "javascript",
    },
    "emmet.showSuggestionsAsSnippets": true,
    "eslint.autoFixOnSave": true,
    "eslint.alwaysShowStatus": true,
    "eslint.run": "onSave",
    "diffEditor.ignoreTrimWhitespace": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.editor.enablePreview": false,
    "gitlens.hovers.enabled": false,
    "editor.minimap.enabled": false,
    "window.zoomLevel": 0,
    "emmet.triggerExpansionOnTab": true,
    "emmet.expandAbbreviation": true,
    "breadcrumbs.enabled": true,
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 100,
    "edge.format.enable": true,
}

**Comment by mjbvz** [comment] 2019-04-17 18:15
@osogrizz Opened new issue for you: #72507

**Comment by mjbvz** [comment] 2019-04-22 18:57
Closing as need more info to investigate

@rabinosona What specific version of `@types/styled-components` do you have installed? (the actual installed version, not just the version listed in the `package.json`) I suspect you are hitting this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391 and need to upgrade to the latest `@types/styled-components`

**Closed by mjbvz** 2019-04-22 18:57 UTC
Labels: needs more info
