### ISSUE TITLE
Markdown fenced blocks in jsdoc blocks prefixed with `* `

### ISSUE THREAD

**Issue by SMotaal** [Microsoft/vscode#72495] opened 2019-04-17 12:48 UTC
- VSCode Version: Version 1.33.1 (1.33.1)
- OS Version: MacOS 10.14.4 (18E226)

Fenced code blocks should not render with the leading jsdoc `* ` prefixes

Steps to Reproduce:

1. Past the actual code in a new JavaScript file.
2. Hover over `something` and observe the rendered fenced block

Does this issue occur when all extensions are disabled?: **Yes**

<table>
<tr><th>Actual Code
<tr><td>

```js
/**
 * **`<em>`**
 *
 * `<p>`
 *
 * ```ts
 *  declare const x = 1;
 * ```
 *
 * @param {*} listeners - `<p>` **`<em>`**
 */
const something = () => {};
```

<tr><th>Visually (ie hover)
<tr><td>

 **`<em>`**
 
 **`<p>`**
 
 &emsp;*  <samp>declare const x = 1;</samp>
 &emsp;*
 
 *@param* `listeners` — `<p>` **`<em>`**

<tr><th>DOM (ie `devtools`)

<tr><td>

```html
<div class="monaco-tokenized-source">
  <span class="mtk8">const</span>
  <span class="mtk9"> something: (listeners: </span>
  <span class="mtk5">any</span>
  <span class="mtk9">) </span>
  <span class="mtk8">=&gt;</span>
  <span class="mtk9"> </span>
  <span class="mtk8">Promise</span>
  <span class="mtk9">&lt;</span>
  <span class="mtk5">any</span>
  <span class="mtk9">&gt;</span>
</div>
```

</table>

**Comment by mjbvz** [comment] 2019-04-17 17:19
Duplicate of https://github.com/Microsoft/TypeScript/issues/23517

**Closed by mjbvz** 2019-04-17 17:19 UTC
Labels: javascript
