### ISSUE TITLE
Unable to open any quick pick from settings gear when release notes are open

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#75209] opened 2019-06-10 17:05 UTC
Issue Type: <b>Bug</b>

![gif](https://user-images.githubusercontent.com/35271042/59212334-f41d5980-8b66-11e9-99b2-d1aa810af2c8.gif)

When I have the release notes open I can't seem to open the any quick pick item (Command palette, color theme, file icons) as it is immediately closed. You can't see it in the GIF because it is sped up but it briefly flashes. This only repros on Windows and on release notes (doesn't happen on Welcome/Interactive playground pages).

Repro Steps:
1. Open Insiders
2. Open Release Notes (if not open)
3. Open any quick pick via the Settings gear (command palette, color/file icon theme)
4. :bug: Quick pick does not open

cc @chrmarti @mattbierner unsure if this is related specifically to webviews

VS Code version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T05:19:15.188Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (4 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.98GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by sbatten** [comment] 2019-06-10 22:09
@mjbvz didn't we have a PR around this issue recently?

**Comment by mjbvz** [comment] 2019-06-11 00:42
I think this is a duplicate of #68335

**Comment by sbatten** [comment] 2019-06-11 01:40
@mjbvz  I'm not so sure, I think that one is about menus appearing where this issue is about the quick pick disappearing immediately. I think there is some weird interaction with the context menu restoring focus and the web view restoring focus to itself

**Comment by COD3BREAK3R** [comment] 2019-07-11 13:33
Yesterday I updated VS Code to version 1.36.1 and this has not been solved, why is this problem closed?

When I am in the readme of an extension and click on your document and autoseguido of that I try to change the theme or the VS Code icon through the configuration menu on the left it automatically closes me the menu of choosing the themes or icons, this is needed solve.

**Comment by yzhang-gh** [comment] 2019-08-20 16:00
Same here (while any kind of webview is focused, e.g. Markdown preview, Python interactive window).

**Comment by chrmarti** [comment] 2019-08-21 07:40
Gave this a try, but it needs more investigation. I logged all focus and blur events (capture phase on window) and it ends with blur on the input element of the QuickInput. The document.activeElement at that point is the webview although there is no focus event logged for that.

One difference between having the Release Notes open and having the Welcome page open is that with the Release Notes there are focus and blur events for the `global` object which I don't see when the Welcome page is shown. Any idea what these could be? Is that the webview drawing focus?

**Comment by gjsjohnmurray** [comment] 2019-11-26 10:50
/confirm still occurs on 1.40.2 and 1.41.0-insider, both on Windows.

**Comment by sbatten** [comment] 2020-04-16 19:03
I still see the issue in the original gif on today's insiders

**Comment by misolori** [comment] 2020-04-16 21:46
@sbatten i'm seeing this fixed on today's insiders

Version: 1.45.0-insider
Commit: 6e9a34c0de4181a99f11e106733ee3e8c9db79f1
Date: 2020-04-16T05:41:45.257Z (16 hrs ago)
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by mjbvz** [comment] 2020-04-16 22:48
@sbatten Which os were you on?

**Comment by sbatten** [comment] 2020-04-16 23:03
Windows

**Closed** 2020-04-17 01:34 UTC
Labels: bug, confirmed, menus, verification-found, webview

**Comment by jkeech** [comment] 2020-04-29 17:24
I also see this on Windows, both desktop and web, stable and insiders when I have a custom webview open and the quick pick / theme pop up would overlap the webview pane.

**Comment by misolori** [comment] 2020-04-29 18:02
Verified that this is fixed on both mac and windows.
