### ISSUE TITLE
Mystery about recently opened menu and dock context menu

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11320] opened 2016-08-31 15:36 UTC
In VS Code we have `File > Open Recent > MRU List of files and folder` and there is also a content menu in the dock showing some previously used files and folder. Somehow they are never really in sync for me and I wonder what the relation between those two are?

This is actual recently opened list 
<img width="793" alt="screen shot 2016-08-31 at 17 34 19" src="https://cloud.githubusercontent.com/assets/1794099/18135212/694ba2b4-6fa1-11e6-825f-dcf5b6d0f2da.png">

This is just a list
<img width="221" alt="screen shot 2016-08-31 at 17 34 09" src="https://cloud.githubusercontent.com/assets/1794099/18135214/6a6eb6d6-6fa1-11e6-81df-fe98f5d19e95.png">

**Comment by bpasero** [comment] 2016-08-31 15:42
Both places are being filled from the same code but I noticed that the dock menu sometimes does not accept an entry added. Closing as duplicate of https://github.com/Microsoft/vscode/issues/6912

**Closed by bpasero** 2016-08-31 15:42 UTC
