### ISSUE TITLE
Synchronise between different OS's.

### ISSUE THREAD

**Issue by dannysmc95** [microsoft/vscode#113224] opened 2020-12-21 09:58 UTC
Can you make the sync feature "smarter" as currently if I set the SSH config in Windows, when I move to my Mac or a Linux machine, the sync will pull the config path and overwrite my path locally, and therefore I have to change it, and the same issue will happen constantly, as I switch between different machines a lot.

Can you make it so certain OS specific settings are synced but synced for a specific platform, so for example if I change the SSH config path in Windows, then that will be saved in a "Windows" scoped setting, and will not affect the same setting when synced to Linux or Mac for example.

**Comment by yume-chan** [comment] 2020-12-21 10:24
Duplicate of #5595

You can try the workaround in https://github.com/microsoft/vscode/issues/5595#issuecomment-673677625 while waiting it been implemented.

**Comment by dannysmc95** [comment] 2020-12-21 10:45
Thanks @yume-chan did not see that, my mistake, will check out the workaround!

**Closed** 2021-01-05 17:55 UTC
