### ISSUE TITLE
Ability to print code

### ISSUE THREAD

**Issue by rwildt** [Microsoft/vscode#63991] opened 2018-11-29 14:45 UTC
Issue Type: <b>Feature Request</b>

It's totally crazy that Visual Studio Code does not allow printing?  With longer code, it's really the only way to go through everything and deal with issues.

Please add, thank you.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.14393

**Comment by usernamehw** [comment] 2018-11-29 15:12
Do you mean the same thing as this issue #5953?

**Comment by mjbvz** [comment] 2018-11-29 16:02
Duplicate of #5953

**Closed by mjbvz** 2018-11-29 16:02 UTC
