### ISSUE TITLE
[mitigated] Selection by mouse affected by gitlens decoration

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#88873] opened 2020-01-17 18:13 UTC
Issue Type: <b>Bug</b>

Codelens affects the hit test of mouse position when selecting text by moving mouse.

![codelens-selection](https://user-images.githubusercontent.com/876920/72635566-f112f480-3911-11ea-8600-11e73a04aa95.gif)

As shown above, I have trouble selecting to the end of the line.

VS Code version: Code - Insiders 1.42.0-insider (fd13e449f5f2fe300f187129d6065ed1cfad74d3, 2020-01-17T16:30:38.851Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.78GB free)|
|Process Argv|-psn_0_17432735|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.0
vscode-pull-request-github-insiders|Git|2020.1.11042
remote-ssh-edit-nightly|ms-|2020.1.11041
remote-ssh-nightly|ms-|2020.1.11041
debugger-for-chrome|msj|4.12.5

(2 theme extensions excluded)

</details>

**Comment by alexdima** [comment] 2020-01-17 20:55
@rebornix I have tried with:
* `settings.json`:
```
    "typescript.referencesCodeLens.enabled": true
```
* `test.ts`:
```ts
class C {
    readonly isClosed: boolean;

    constructor() {
        this.isClosed = true;
    }
}

const c:C;
c.isClosed;
```
![Kapture 2020-01-17 at 21 53 05](https://user-images.githubusercontent.com/5047891/72645379-d8d3c180-3973-11ea-84da-741825ab3503.gif)

And I could not reproduce. 

Perhaps there are more steps to it? Did you try disabling all extensions, I see that there is a git lens decoration on that line.

**Comment by jmbockhorst** [comment] 2020-01-18 01:12
I am also seeing this, but it seems like an issue with gitlens, not codelens.

**Comment by alexdima** [comment] 2020-01-18 18:11
This appears to be a result of using `margin` in the `after` decoration. Here is an extension I can reproduce with:
* `package.json`
```json
{
    "publisher": "alex",
    "name": "40127",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```
* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
	const dectype2 = vscode.window.createTextEditorDecorationType({
		after: {
			contentText: "abcd",
			color: "#00ff00",
			margin: "0px 0px 0px 3em"
		}
	});
	vscode.window.activeTextEditor.setDecorations(dectype2, [
		new vscode.Range(0, 1000, 0, 1000),
		new vscode.Range(1, 1000, 1, 1000),
		new vscode.Range(2, 1000, 2, 1000),
		new vscode.Range(3, 1000, 3, 1000),
		new vscode.Range(4, 1000, 4, 1000),
		new vscode.Range(5, 1000, 5, 1000),
		new vscode.Range(6, 1000, 6, 1000),
		new vscode.Range(7, 1000, 7, 1000),
		new vscode.Range(8, 1000, 8, 1000),
		new vscode.Range(9, 1000, 9, 1000),
	]);
}

```

**Comment by alexdima** [comment] 2020-01-18 18:49
I could reproduce in Chromium and have created https://bugs.chromium.org/p/chromium/issues/detail?id=1043471 upstream.

FYI @eamodio The usage of `margin` in the `::after` element makes hit testing incorrect.

**Comment by eamodio** [comment] 2020-01-18 18:52
@alexdima Is this new with Electron 7?

**Comment by alexdima** [comment] 2020-01-18 20:02
I don't know.

**Comment by Yen** [comment] 2020-01-19 02:40
I think this was caused by a change to vscode, not gitlens. I have a second plugin [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) that is seeing the same issues. 
![wsHaZ6ByNu](https://user-images.githubusercontent.com/10085851/72673597-cbe2cb00-3a64-11ea-8c40-f823c2d69e38.gif)

**Comment by alexdima** [comment] 2020-01-19 09:07
Indeed, I cannot reproduce on Stable, and since this is a Chromium issue, this is caused by our Electron 7 upgrade on Insiders.

**Comment by alexdima** [comment] 2020-01-20 10:13
Adding important as more members of the dev team are hitting this -- @jrieken

**Comment by jrieken** [comment] 2020-01-20 11:34
This makes it very hard to click after a line so that the cursor is at its end. In 9 out of 10 cases selection jumps to the line start

**Comment by deepak1556** [comment] 2020-01-20 23:12
As a temporary workaround, can you see if the issue repros when launching code with `--disable-features="LayoutNG"`

**Comment by Frizi** [comment] 2020-01-22 16:25
It seems like the selection jumping is just a side effect of incorrect mouse coordinates offset. Here is a more complete bug demo for full context




![selection_2](https://user-images.githubusercontent.com/919491/72912588-25384c00-3d3c-11ea-8f1e-f5f6b399b09e.gif)

**Comment by dlong500** [comment] 2020-01-28 12:47
Has something changed in the latest insiders version (c4b6a6b537de49a734d0eedea06152ea37dfdb6a)?  It looks like the issue is resolved as far as I can tell, but it also looks like Electron is back to 6.x.

**Comment by alexdima** [comment] 2020-01-28 13:24
@dlong500 Yes, in preparation for our upcoming release, we have rolled back Insiders to Electron 6.0. Once we ship stable, we will upgrade Insiders again to Electron 7.0, which has this issue.

**Comment by jamesheazlewood** [comment] 2020-02-14 00:10
I noticed that if you have `"gitlens.currentLine.scrollable": false,` you can see this offset issue happen to the entire line instead of just the gap between the lens text and the code, even with deepak1556's workaround. Might be worth noting.

**Comment by bpasero** [comment] 2020-02-17 09:45
I pushed a change to always configure to disable `LayoutNG`.

**Comment by bpasero** [comment] 2020-02-21 07:09
@alexr00 can you also confirm this is fixed for you with latest?

**Comment by eamodio** [comment] 2020-02-21 07:44
It looks good to me

**Comment by ebraminio** [comment] 2020-04-17 15:32
Fixed by upstream fortunately https://crbug.com/1043471#c11

**Comment by deepak1556** [comment] 2020-06-17 21:38
Backporting the chromium fix to Electron 8 turned out non-trivial because of the changes between versions and also I am not familiar with LayoutNG code path. I have backported the fix to Electron 9 for now, will enable LayoutNG when we adopt this version. If anyone else is interested in backporting the fix to Electron 8, feel free to. I can help with development setup quesitons.

**Comment by deepak1556** [comment] 2020-08-28 21:05
Should be fixed in latest insiders.

**Closed by deepak1556** 2020-08-28 21:05 UTC
Labels: chromium, electron-7-update, fixed-in-electron-9, regression, upstream, upstream-issue-fixed
