### ISSUE TITLE
Multiple cursors leave viewable window when using up/down arrows to navigate.

### ISSUE THREAD

**Issue by yconway** [microsoft/vscode#88061] opened 2020-01-03 19:54 UTC
- VSCode Version: 1.41.1
- OS Version: Ubuntu 18.04 bionic (x86-64)

Steps to Reproduce:

1. add multiple cursors to your editor (alt + up arrow)
2. use your up/down arrows to navigate your cursors out of the current viewable window (for example, move your cursors down to some code that is out of view)
3. the cursors are now outside of the current viewable window.

note that the window scrolls along with your cursor when you only have one.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by yconway** [comment] 2020-01-03 19:55
bump

**Comment by egamma** [comment] 2020-01-04 16:15
/needsMoreInfo thanks for the issue, can you please illustrate the problem with screenshots.

**Comment by yconway** [comment] 2020-01-06 17:50
the terminal window was a red herring.  This bug happens whenever I have multiple cursors and move them with the up/down arrow keys

![scrolling with multicursor](https://user-images.githubusercontent.com/37809541/71836918-c8217280-307a-11ea-9ac4-85c3bcbc12a7.gif)

**Comment by alexdima** [comment] 2020-01-21 09:12
Duplicate of #6995

**Closed by alexdima** 2020-01-21 09:12 UTC
