### ISSUE TITLE
Broken stage button in SCM viewlet

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31022] opened 2017-07-19 11:04 UTC
Reported by smoke test - plus button is not clickable.

![4](https://user-images.githubusercontent.com/2239563/28363941-c82706dc-6c82-11e7-862f-bdcf787edf60.png)

**Comment by michelkaporin** [comment] 2017-07-19 13:04
@joaomoreno I've tested button clickability also manually and didn't see any UI feedback after a click. I did it on the smoke test produced executable on Windows.

**Comment by joaomoreno** [comment] 2017-07-19 13:16
@michelkaporin It doesn't appear broken in Insiders.

**Comment by michelkaporin** [comment] 2017-07-19 13:47
@joaomoreno maybe built over bad commit then. Although I didn't get update for Insiders today to test it there.

**Comment by chrmarti** [comment] 2017-07-19 14:09
Also works for me in:
- VSCode Version: Code - Insiders 1.15.0-insider (9a308d1128df9af90e84b2988bce4f57f885b1c3, 2017-07-19T06:31:43.209Z)
- OS Version: Darwin x64 16.6.0

Which commit was the smoke test build built from?

**Comment by michelkaporin** [comment] 2017-07-19 14:19
@chrmarti  9a308d1

You can rerun it and see if it's fixed 👍 or wait until tomorrow's smoke test

**Comment by michelkaporin** [comment] 2017-07-19 14:59
Just received todays Insiders update on Windows. Stage/undo buttons don't work in SCM viewlet for me.

**Comment by bpasero** [comment] 2017-07-20 07:09
Since a couple of days I cannot unstage or stage files at random. Increasing severity.

**Comment by joaomoreno** [comment] 2017-07-20 07:19
@bpasero Please provide more details.

![kapture 2017-07-20 at 9 18 38](https://user-images.githubusercontent.com/22350/28405152-6ef6e5e6-6d2c-11e7-9af2-e1de91169f59.gif)

**Comment by isidorn** [comment] 2017-07-20 07:37
This was also happening to me this week, but when I deleted the index.lock in my .git folder everything worked fine.
It is very strange that this happened to all of us at the same time though.

**Comment by weinand** [comment] 2017-07-20 08:31
Yesterday, I was seeing this too. In today''s insiders I don't see this anymore.

**Comment by joaomoreno** [comment] 2017-07-20 09:00
Duplicate of #31038

No URIs are getting to the git extension.

**Closed by joaomoreno** 2017-07-20 09:00 UTC
Labels: bug, important, scm
