### ISSUE TITLE
process.env layer breakers

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79210] opened 2019-08-15 12:48 UTC
`process` cannot be used in browser. We have a replacement in common if that helps.

- [x] https://github.com/microsoft/vscode/blob/f5ade17659504c1b305959b265fbe0712b757e1a/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L228

- [ ] https://github.com/microsoft/vscode/blob/f5ade17659504c1b305959b265fbe0712b757e1a/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1386

- [x] https://github.com/microsoft/vscode/blob/f5ade17659504c1b305959b265fbe0712b757e1a/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L597

**Comment by alexr00** [comment] 2019-08-15 12:53
The tasks part is a duplicate of https://github.com/microsoft/vscode/issues/76351
It is still a layer break, but that code in tasks will never run where there is no node.

**Comment by isidorn** [comment] 2019-08-15 13:24
@bpasero thanks for the ping. I have updated that we use process.env from common
fyi @weinand

**Comment by bpasero** [comment] 2019-08-15 14:25
@alexr00 if you look at the fix from Isi, there is a process.env in common you can simply use which is safe.

**Closed** 2019-08-22 16:06 UTC
Labels: debt, important, web
