### ISSUE TITLE
Missing intellisense for 'requestIdleCallback'

### ISSUE THREAD

**Issue by carljohnesan** [microsoft/vscode#89293] opened 2020-01-26 13:04 UTC
There are missing intellisense for `requestIdleCallback` method. It's weird considering there's intellisense even for `setImmediate` which is edge-only feature.
![requestidlecallbackmissing](https://user-images.githubusercontent.com/47556468/73135648-21af0880-404d-11ea-8c35-354285e61fc9.png)

**Comment by mjbvz** [comment] 2020-01-27 19:47
Duplicate of https://github.com/microsoft/TypeScript/issues/21309

**Closed by mjbvz** 2020-01-27 19:47 UTC
Labels: javascript
