### ISSUE TITLE
Pressing F5 to Debug Prompts to Save (Powershell)

### ISSUE THREAD

**Issue by SoulSeekkor** [microsoft/vscode#117607] opened 2021-02-24 17:17 UTC
- VS Code Version: 1.53.2 (user setup)
- OS Version: Windows 10 20H2 Build 19042.804

Steps to Reproduce:

1. Open VS Code.
2. Create a new tab with language set to powershell.
3. Type some mundane code (for example: get-date) and press F5.
4. It will first prompt to save the file, THEN run the code after you cancel the save file window.

Just a note that this has been happening for weeks, extremely frustrating when trying to do any kind of scripting work as every time I press F5 (or use the menu, doesn't matter which) it always prompts and most of the time I'm just testing little snippets and don't want to save a bunch of test snippets to my repo.  It does not happen on saved files.  I cannot seem to find a setting to get rid of this new behavior, if there is one please let me know.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2021-02-24 18:32
/duplicate of #114890

Option to configure this will arrive in 1.54, due out by the end of next week.

**Closed** 2021-02-24 18:34 UTC
Labels: *duplicate
