### ISSUE TITLE
Cannot read JSON in CentOS

### ISSUE THREAD

**Issue by bhkeys** [Microsoft/vscode#28243] opened 2017-06-08 16:33 UTC
- VSCode Version: 1.12
- OS Version: CentOS 7

Steps to Reproduce:

1. Install vscode on CentOS
2. You will get this ![error](http://pix.toile-libre.org/upload/original/1496939552.png)

[this issue](https://github.com/Microsoft/vscode/issues/8950) is probably related.

**Comment by wanghaiyang1930** [comment] 2017-06-11 02:40
I have the same problem.
    Version: 1.13.0
    OS: Debian 6

**Comment by vbuell** [comment] 2017-06-12 16:54
The same problem using latest Raspbian (debian jessie arm):

Version 1.14.0
Commit ebecfa501bf8d6e353cd971628b05cf5c223fa45
Date 2017-06-11T20:16:09.668Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

Installed DEB built and packaged by https://code.headmelted.com/

**Comment by aeschli** [comment] 2017-06-14 07:49
Can you open the developer tools (Help > Toggle Developer Tools) and see if there is more information?
Is this only with JSON or with any other file format?

**Comment by aeschli** [comment] 2017-08-31 13:46
duplicate of #32193

**Closed by aeschli** 2017-08-31 13:46 UTC
Labels: json
