### ISSUE TITLE
[Insiders]: Semantic highlight cannot be disabled

### ISSUE THREAD

**Issue by limbosounds** [microsoft/vscode#94278] opened 2020-04-02 11:10 UTC
Issue Type: <b>Bug</b>

I disabled semantic highlight like 2 weeks ago, because Monokai Dimmed theme has weird highlight for this feature. After yesturday update I came to this issue.
1. Open Insiders.
2. Despite of you disabled Semantic Highlight, it will be enabled (by fact, in settings it is still disabled).
3. If you re-disable it in settings, it will be disabled until you open any file to editor.

Same shit with manually set the `editor.tokenColorCustomizations -> semanticHighlighting`

Also, text-mate rules stopped working for me (in my case, it is `variable.object.property.ts`) despite of semantic highlight is disabled.

![Capture__](https://user-images.githubusercontent.com/26549754/78246610-187d6480-74f2-11ea-9239-7451ec773b22.PNG)
![Capture](https://user-images.githubusercontent.com/26549754/78243260-1e704700-74ec-11ea-85b2-53c9398cb0a8.PNG)

VS Code version: Code - Insiders 1.44.0-insider (2f984aad710215f4e4684a035bb02f55d1a9e2cc, 2020-04-01T05:37:21.008Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
todo-tree|Gru|0.0.171
vscode-docker|ms-|1.0.0
remote-wsl|ms-|0.44.2
sass-indented|syl|1.8.1

</details>

**Comment by limbosounds** [comment] 2020-04-02 15:14
UPDATE: Time by time semantic highlighting is being disabled for about a half of second during scroll

**Comment by andrew-linck** [comment] 2020-04-03 01:25
For now I would revert to using "Solarized Dark" because the syntax highlighting is not as obstructive.

**Comment by aeschli** [comment] 2020-04-03 10:37
duplicate of #93897

**Closed by aeschli** 2020-04-03 10:37 UTC
