### ISSUE TITLE
Crash when opening a large file in the editor

### ISSUE THREAD

**Issue by jesseliu612** [Microsoft/vscode#41472] opened 2018-01-11 15:02 UTC
- VSCode Version:1.19
- OS Version:Ubuntu 14.04 LTS

Steps to Reproduce:

1. generate a large file (larger than about 20MB, maybe)
2. use vscode to open it

It is possible to open files that large in gedit or emacs, but it's quite inconvenient and I hope this issue to be solved.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-01-11 15:12
@jesseliu612 and what happens if you open such a file in VS Code?

**Comment by jesseliu612** [comment] 2018-01-13 11:53
@bpasero 

抱歉没有及时看到您的回复。打开大文件时（尤其是在已打开的大文件发生更改，而vscode自动重新加载时），vscode通常会变为无响应状态，但工具栏仍可点选，只是无法执行任何操作。顺带一提，我在用coderunner扩展执行c++程序时，只要程序往一个已打开的文件中写入信息，就会触发无响应。

Sorry for not noticing your reply in time. When opening large files (especially when the original file changed and vscode try to reload it), it turns to "not responding", and after one minute maybe, it ask me to reload the frame. While this issue happening, the tool bar is still able to respond the mouse click operation, but cannot use it to close window or do anything else.
By the way, vscode always turn to "not responding" when I use extension "coderunner" to run my c++ code and the programe wrote a lot to an opening file.

**Comment by bpasero** [comment] 2018-01-13 13:25
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by jesseliu612** [comment] 2018-01-14 08:10
@bpasero still turn not responding when a large file changed and vscode attempt to reload it. After I use the command `killall code` to stop it, Ubuntu system told me "系统剩余空间不足" ( lack of remaining space in English, maybe).

**Comment by bpasero** [comment] 2018-01-14 08:19
@jesseliu612 is that file open source, could you attach it as zip here?

**Comment by jesseliu612** [comment] 2018-01-14 08:22
simply try this code to generate a huge file
```c++
#include <cstdio>
#include <cstdlib>
int main () {
    freopen("a.txt","w",stdout);
    for(int i=1;i<=10000000;i+=1) printf("%d\n",7-i);
    return 0;
}
```
1. run the code above, use vscode to open `a.txt`.
2. change `7-i` to `5-i`, and run it again.
3. vscode will turn not responding

**Comment by bpasero** [comment] 2018-01-14 09:48
Moving to @rebornix who is working on reducing the memory footprint of opening large files.

**Comment by rebornix** [comment] 2018-01-29 18:46
@jesseliu612 We changed the text buffer implementation in current Insider, and I generated the same test file by the snippet you provided above, opening the file in latest Insider doesn't crash, can you confirm that? 

You may still see perf issue when moving your cursor, that's because we tried to find matches for words under the cursor and since there are 10,000,000 lines, it takes a long time to finish the word matching (since the file is large, we don't have a copy in worker process so it's blocking). I'll fix this issue later.

**Comment by rebornix** [comment] 2018-01-29 19:02
@jesseliu612 we turned off new text buffer implementation in Insider for this week (our endgame), so you can verify this issue with next week's Insider.

**Closed** 2018-02-12 22:12 UTC
Labels: editor-textbuffer, freeze-slow-crash, needs more info

**Comment by jesseliu612** [comment] 2018-03-01 11:53
@rebornix sorry for not noticing your reply. It's too hard to access github here. I can confirm that opening such a large file is quite easy now, but if i first open an empty file, and then use that program to write numbers into it, vscode will crash immediately. I think it is because vscode is hard to reload the file when it changes rapidly.
