### ISSUE TITLE
wrong import suggestion for 'ionic-angular' in ionic app

### ISSUE THREAD

**Issue by g3t1t** [Microsoft/vscode#54252] opened 2018-07-13 11:09 UTC
- VSCode Version: 1.25.1
- OS Version: MacOS 10.13.5

Steps to Reproduce:

1. create blank ionic app (version 3.20.0) and open it in vscode
2. remove import of 'ionic-angular' in file 'app.component.ts'
3. get import suggestion from vscode for Class 'Platform':
Instead of 'ionic-angular' it suggests '../../node_modules/ionic-angular/umd'.
After starting app with 'ionic serve' this import results in Ionic Error "Cannot find Module '.'"

This wrong import results in more problems when moving or renaming Files. Cause of the automatic refactoring from vscode, all 'ionic-angular' imports going to be changed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by g3t1t** [comment] 2018-07-13 11:39
Issue is the same as https://github.com/Microsoft/TypeScript/issues/25204

**Comment by mjbvz** [comment] 2018-07-13 21:11
Closing as duplicate of Microsoft/TypeScript#25204

**Closed by mjbvz** 2018-07-13 21:11 UTC
Labels: new release, upstream
