### ISSUE TITLE
All suggestions being read at once with VoiceOver on Mac when editing code

### ISSUE THREAD

**Issue by keford** [microsoft/vscode#140221] opened 2022-01-06 15:00 UTC
Issue Type: <b>Bug</b>

1. Open a new file in VS Code.
2. Change the type to one that ensures suggestions are provided.  I used html.
3. Start typing some code.  In my case I entered <h.

Result:
All the suggestions were read at once after entering these two characters.  I would have expected just the highlighted item to be read.  It was properly as I used up and down arrow.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 93b64371-544c-441c-98de-23303e474b41|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
py55gd98cf:30419166
vscexrecpromp3t1:30407762

```

</details>

**Comment by isidorn** [comment] 2022-01-06 15:25
I can not reproduce this.
@sana-ajani @jrieken can you please try on your machine?
@keford can you also try with VS Code insiders (just so we are 100% sure you see this with latest) https://code.visualstudio.com/insiders/

**Comment by keford** [comment] 2022-01-06 17:14
This repros in the identical fashion for me with the Insider build.



From: Isidor Nikolic ***@***.***>
Date: Thursday, January 6, 2022 at 10:25 AM
To: microsoft/vscode ***@***.***>
Cc: Kelly Ford (CELA) ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/vscode] All suggestions being read at once with VoiceOver on Mac when editing code (Issue #140221)

I can not reproduce this.
@sana-ajani<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsana-ajani&data=04%7C01%7Ckeford%40microsoft.com%7C22f196d2fa6446ae933908d9d128c23d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770795252619382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QpTt4DnpcVlLZhAfbWQX5Vu5DtyPTRj5DlAp8ecFlE4%3D&reserved=0> @jrieken<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjrieken&data=04%7C01%7Ckeford%40microsoft.com%7C22f196d2fa6446ae933908d9d128c23d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770795252619382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7KBUjcl5OnY%2B7M0TtzBbg3axv5tmcJ%2FB0aT0WoDluS0%3D&reserved=0> can you please try on your machine?
@keford<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkeford&data=04%7C01%7Ckeford%40microsoft.com%7C22f196d2fa6446ae933908d9d128c23d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770795252619382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LJNag%2Bh%2BC%2FGN59XYYj2LCi6EeRPxV%2BvmYoNFBoGwyz8%3D&reserved=0> can you also try with VS Code insiders (just so we are 100% sure you see this with latest) https://code.visualstudio.com/insiders/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2Finsiders%2F&data=04%7C01%7Ckeford%40microsoft.com%7C22f196d2fa6446ae933908d9d128c23d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770795252619382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=811v49nPY11R4e%2FfI4lsX%2Bfe%2FKz3lipXidQNkJk04SM%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F140221%23issuecomment-1006677444&data=04%7C01%7Ckeford%40microsoft.com%7C22f196d2fa6446ae933908d9d128c23d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770795252619382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BVup6NluLMS4B9F4jgXWW%2Fu0L3yQQqd3Uj3uF%2BanhRU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT2VAIQXBJGRI3OMF4YWOVTUUWX6HANCNFSM5LMQPGIA&data=04%7C01%7Ckeford%40microsoft.com%7C22f196d2fa6446ae933908d9d128c23d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770795252669379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rPVy2BCiCsaG74Q1uDfAPP%2BnqL2H0AJac6p1ULsCMN8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckeford%40microsoft.com%7C22f196d2fa6446ae933908d9d128c23d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770795252669379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fb9IunFygkzPWO0yex5kATLMI0IvGB3mjGw%2FwI2MqVE%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckeford%40microsoft.com%7C22f196d2fa6446ae933908d9d128c23d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770795252669379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BHheDQ9xa4SdzDlxkoegwmI1wQR28CA32ZQsMi8zEqk%3D&reserved=0>.

**Comment by jrieken** [comment] 2022-01-07 07:48
Hm... I can also not reproduce (on an intel mac, using latest insider) @keford can you share the file and what exactly is being read out to you?

**Comment by Ashwinipola26** [comment] 2022-01-07 10:52
GitHubTags:#A11y_Visual Studio Code Client;#A11ySev2;#A11yTCS;#A11yMAS;#DesktopApp;#Visual Studio Code Client;#WCAG1.3.1;#Info and Relationships;#MAC;#AINotInScope;#VoiceOver;#BM-VisualStudioCodeClient-MAC-Aug2021;

**Comment by isidorn** [comment] 2022-01-07 16:15
I can reproduce. Here are steps:
1. New untitled file. Set language mode to `HTML`
2. Type `<h`
3. Voice over reads the whole suggest widget content 🐛 

At times like this I wish we had a contact in Apple because I have no clue why did VoiceOver in this case decide to read everything.

**Comment by isidorn** [comment] 2022-01-12 14:10
We have talked to Apple and they acknowledged this is a VoiceOver issue.
They have pushed a fix for the issue and it will be included in the next release.
So marking as upstream and closing since it got resolved. Thanks Apple!

**Closed by isidorn** 2022-01-12 14:10 UTC
Labels: bug, macos, accessibility, suggest
