### ISSUE TITLE
Cannot easily develop a extension with faulty save method

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115028] opened 2021-01-26 11:50 UTC
* develop a notebook (or custom editor) extenion
* have an error condition in its save logic, e.g throw an extension
* you are doomed because you cannot quite the debugee

<img width="1336" alt="Screenshot 2021-01-26 at 12 49 14" src="https://user-images.githubusercontent.com/1794099/105841495-fc910500-5fd4-11eb-912a-dcb1e5e1a77e.png">

**Comment by bpasero** [comment] 2021-01-26 13:55
Either provide your extension as sample or let me know what to change in our custom editor example (https://github.com/Microsoft/vscode-extension-samples/blob/master/custom-editor-sample) to get this to happen. I tried to throw an error from the `save` method in `pawDrawEditor` but only get this:

![image](https://user-images.githubusercontent.com/900690/105853805-6239bd00-5fe6-11eb-9ab0-c30c466e2102.png)

Which does prevent the shutdown from happening.

For the longest time we actually explicitly disabled handling of dirty files in the extension development window but changed that when custom editors appeared so that authors have a chance to debug these cases. 

I am not entirely sure what should happen here. To get out of this you need to click "Cancel" and then revert the editors.

**Comment by jrieken** [comment] 2021-01-26 13:58
Throw an error here: https://github.com/microsoft/vscode-github-issue-notebooks/blob/8578b61e431056a277d387950e3221498d4ef561/src/extension/notebookProvider.ts#L269

**Comment by bpasero** [comment] 2021-01-26 15:55
One idea would be to always allow to close a window when you are doing extension development but still trigger the normal shutdown handlers so that an extension developer can properly debug that code.

**Comment by Tyriar** [comment] 2021-01-29 13:45
I hit this as well yesterday, I needed to kill the window via task manager. My problem was the embedded page threw an error during a save.

Extensions could ship with an exception like this so there should be some intuitive way to shut the window down, can the wait for dirty editors notification have an override button that shows up after a few seconds?

**Comment by bpasero** [comment] 2021-01-29 14:06
@Tyriar did you read my instructions?

> To get out of this you need to click "Cancel" and then revert the editors.

**Comment by Tyriar** [comment] 2021-01-29 14:25
@bpasero this is an unreasonable expectation for the user to revert the editor via the command palette. For my case I had auto save on and the custom editor tab wasn't even visible anymore (0 tabs open).

**Comment by bpasero** [comment] 2021-01-29 14:46
@Tyriar I did not say to revert via command palette, the editor should be visible, show dirty and closing it will ask you to save or revert. Anything else is a bug that we should follow up independent from this issue that is only about extension development where this flow can be painful when you often start/stop/debug/refresh.

**Comment by bpasero** [comment] 2021-02-01 14:30
**Steps:**
* start https://github.com/microsoft/vscode-github-issue-notebooks
* throw in `save` method
* enable auto save on focus out
* make notebook dirty
* close the other window (the debugger)

=> 🐛 the remaining window refuses to quit and behaves weird

![image](https://user-images.githubusercontent.com/900690/106471838-57799f00-64a2-11eb-88a5-399f14f677a8.png)


I cannot reproduce it any other way anymore, but that is possibly due to the changes I pushed today.

**Comment by bpasero** [comment] 2021-02-01 14:30
Possible that this is a hanging promise somewhere in custom editor land. @mjbvz are notebooks using custom editor infrastructure?

**Comment by bpasero** [comment] 2021-02-01 16:51
@jrieken I see what is going on:
* you start debug that extension
* window opens and everything is fine, except you cannot save
* you either stop debugging or close that window that is the debugger
* this triggers an attempt to close the extension dev window and actually terminates the extension host process (you can see from the process explorer)
* this triggers the normal shutdown handlers that will eventually try to backup the notebook because it is dirty
* at this point, I can see that the promise in [here](https://github.com/microsoft/vscode/blob/b112052169c3611ecd086b9474facea77444402c/src/vs/workbench/api/browser/mainThreadNotebook.ts#L485-L485) never returns

Since the promise never returns, we simply wait on the backup to happen for as long as it takes and we prevent the window close from happening.

Can we at least get an error thrown if anyone attempts to communicate to an extension host that has been terminated?

**Comment by jrieken** [comment] 2021-02-01 16:56
> Can we at least get an error thrown if anyone attempts to communicate to an extension host that has been terminated?

question for @alexdima

**Comment by bpasero** [comment] 2021-02-02 07:58
I have extracted https://github.com/microsoft/vscode/issues/115588 for the particular issue that promises to the extension host don't throw when the extension host is gone.

As for this issue I have done my best to help devs get out of this: backups now also show progress and can be cancelled. Same as save operations if you cancel, the shutdown normally proceeds:

**Backups**
![backup-pending](https://user-images.githubusercontent.com/900690/106569391-bd166b80-6534-11eb-9fe8-d3a201d105f1.gif)


**Save**
![save-pending](https://user-images.githubusercontent.com/900690/106569397-c0a9f280-6534-11eb-9f66-488535693aa2.gif)

**Closed by bpasero** 2021-02-02 07:58 UTC
Labels: custom-editors, extensions-development
