### ISSUE TITLE
Trusted domains not working?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#84430] opened 2019-11-10 22:44 UTC
In Insiders, here is the list I see when I run "Manage Trusted Domains"

```
[
  "https://developer.mozilla.org",
  "https://github.com",
  "https://code.visualstudio.com",
  "https://go.microsoft.com",
  "https://marketplace.visualstudio.com",
  "https://vscode-auth.github.com"
]
```

But if I open an empty document with `https://github.com` and cmd+click, it still asks me whether to trust it.

If I say "Configure Trusted Domains" -> "Trust https://github.com", nothing happens and the list of trusted domains doesn't change.

**Comment by octref** [comment] 2019-11-11 16:07
Duplicate of #84301. Just pushed a fix.

**Closed by octref** 2019-11-11 16:07 UTC
