### ISSUE TITLE
te

### ISSUE THREAD

**Issue by xlebenny** [Microsoft/vscode#34420] opened 2017-09-15 03:58 UTC
It's sound look like can set environment variables by "terminal.integrated.env.windows" config

- VSCode Version: 1.16.1
- OS Version: Windows 10

Steps to Reproduce:

1. File > Preference > Setting, save with below text
{
    "terminal.integrated.env.windows": {
        "foo": "bar"
    }
}

2. View > Integrated Terminal

3. input echo $foo in Terminal

Output:
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\bar> echo $foo
PS C:\bar> 

Expected Output:
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\bar> echo $foo
bar       <---- because configed in terminal.integrated.env.windows
PS C:\bar> 

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-09-15 07:33
@xlebenny Can you please write steps for your problem ?

**Comment by xlebenny** [comment] 2017-09-15 07:51
Updated @alexandrudima , but why  stackovewflow copy by post to here?

**Comment by yume-chan** [comment] 2017-09-24 13:36
In PowerShell, `$foo` means a local variable named `foo`, and `$env:foo` means an environment variable named `foo`.

I have confirmed that `$env:foo` does work.

**Comment by xlebenny** [comment] 2017-09-25 04:43
@yume-chan i tried below is work for me

```
"terminal.integrated.env.windows": {
    "foo": "bar"
}
```

```
PS C:\bar> echo $env:foo
bar
```


but, how to `append` variable instead of replace?
```
"terminal.integrated.env.windows": {
    "path": "$Env:Path;C:\\new\\path"
}
```

```
PS C:\bar> echo $Env:Path
$Env:Path;C:\new\path
```

**Comment by yume-chan** [comment] 2017-09-25 04:51
See #34337. There is currently no way to do that.

`${env:Name}` is supported in `tasks.json`, can it be extended to `settings.json`? @Tyriar

**Comment by Tyriar** [comment] 2017-09-25 21:09
Closing as duplicate of https://github.com/Microsoft/vscode/issues/34337

@yume-chan I'll reopen the issue with syntax similar to tasks.

**Closed** 2017-09-26 01:58 UTC
Labels: needs more info
