### ISSUE TITLE
终端输入卡顿

### ISSUE THREAD

**Issue by Yangjiejiejie** [microsoft/vscode#110797] opened 2020-11-17 11:16 UTC
Issue Type: <b>Performance Issue</b>

终端输入卡顿

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id 6a472893-5ee4-484e-9777-f492fc4c8139|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    8	   115	  2223	code main
    1	    66	  2226	   gpu-process
    0	    33	  2228	   utility
    0	   311	  2229	   window (index.tsx — workSpace2)
    0	     0	  2235	     /bin/bash -l
    0	   197	  2238	     extensionHost
    0	    82	  2241	       electron_node tsserver.js 
    0	   311	  2242	       electron_node tsserver.js 
    0	    66	  2258	         electron_node typingsInstaller.js typesMap.js 
    0	    33	  2245	       electron_node serverMain.js 
    0	    82	  2284	       electron_node eslintServer.js 
    0	    33	  2299	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=2238
    0	    33	  2239	     watcherService
    0	    33	  2251	     searchService
   91	    98	  2240	   shared-process
    0	     0	  2486	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	    66	  2481	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.tsx — workSpace2)
|    Folder (workSpace2): 2194 files
|      File types: tsx(464) ts(278) png(254) less(216) js(121) scss(120)
|                  css(49) json(32) txt(17) svg(15)
|      Conf files: makefile(2) package.json(2) tsconfig.json(2)
|                  jsconfig.json(1);
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.13
javascript-ejs-support|Dig|1.3.1
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.7.2
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
code-runner|for|0.11.1
vue-snippets|hol|0.1.12
vscode-fileheader|mik|0.0.2
vscode-language-pack-zh-hans|MS-|1.51.2
vetur|oct|0.30.2
docthis|oou|0.8.2
LiveServer|rit|5.6.1
js-jsx-snippets|sky|10.1.0
autoimport|ste|1.5.3
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by leaves4j** [comment] 2020-11-18 02:35
https://github.com/microsoft/vscode/issues/105446

**Comment by AryanBeezadhur** [comment] 2020-11-18 09:45
> 终端输入卡顿
Means: Terminal input freezes.

Duplicate of #105446

**Comment by AryanBeezadhur** [comment] 2020-11-18 09:46
Duplicate of #105446

**Closed** 2020-11-23 02:24 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified

**Comment by Huuhung92** [comment] 2020-11-23 02:32
Hcu
