### ISSUE TITLE
Debugging C# - VSCode hangs when breakpoint hit

### ISSUE THREAD

**Issue by RandScullard** [microsoft/vscode#116865] opened 2021-02-17 17:34 UTC
Issue Type: <b>Bug</b>

- I am using VSCode to debug my C# ASP.NET Core project running on Kestrel on my Windows laptop.
- I set a breakpoint in my C# code and trigger the feature in my app (in the browser) that causes that breakpoint to be hit.
- I see VSCode's task bar button begin to flash, indicating that the breakpoint has been hit.
- I click the task bar button to bring VSCode to the foreground. 
- VSCode is hung - the entire UI is non-responsive. The line with the breakpoint is not highlighted.
- I click back on the browser window and VSCode immediately becomes responsive again and highlights the line with the breakpoint. I can then work with the debugger, which works fine until the next time a breakpoint is hit; then the whole process repeats.

This sequence of steps happens the same way every time. I have tried a sample ASP.NET Core project and got the same behavior, so it is nothing specific to my code. I have also tried disabling all extensions except the C# extension (required for debugging) and it still happens.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (18.94GB free)|
|Process Argv|--crash-reporter-id 28325b46-87fa-4884-ae6b-3bd5373edc01|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.11.1
awarest-align|awa|1.1.0
markdown-preview-github-styles|bie|0.1.6
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
rainbow-csv|mec|1.8.1
git-graph|mhu|1.28.0
csharp|ms-|1.23.9
powershell|ms-|2020.6.0
vscode-gitextensions|pmi|1.1.0
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627cf:30244335
pythonvspyt875:30251590

```

</details>

**Comment by avenmore** [comment] 2021-02-18 12:29
I'm also seeing this when a "debugger" statement is hit in my Vue script section. The behavior reminds me of my Win32 days when we would call [LockWindowUpdate()](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-lockwindowupdate) while doing some messy painting to reduce flicker, and it didn't get unlocked. I'm now in the habit of doing a quick double Alt-Tab or double tapping the Windows key (to bring up/hide the Start menu) which has the effect of unlocking it.

**Comment by isidorn** [comment] 2021-02-18 16:13
Sounds related to this https://github.com/microsoft/vscode/issues/114459
Since we use the `electron` focus window API. Also assigning to @deepak1556 since he would know if we should close this as duplicate

**Comment by avenmore** [comment] 2021-02-18 16:47
It certainly is the same issue as #116615 which was closed as a duplicate of  #114459, and starting with `code --disable-features=CalculateNativeWinOcclusion` solves the problem for me too, so I would say yes, this is a duplicate of that issue.

**Comment by isidorn** [comment] 2021-02-18 17:24
Thanks for letting us know. Then let's close as duplicate, and if @deepak1556 thinks I am mistaken we can reopen

**Closed by isidorn** 2021-02-18 17:24 UTC
Labels: under-discussion

**Comment by deepak1556** [comment] 2021-02-18 19:10
Nope all good, thanks for triaging the issue!

**Comment by RandScullard** [comment] 2021-02-18 21:33
Confirmed that `code --disable-features=CalculateNativeWinOcclusion` fixes the problem on my system. Thanks for your help!
