### ISSUE TITLE
JSON completion does not overwrite properly

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2501] opened 2016-01-28 15:55 UTC
* user settings
* type 'editor.' -> invoke intelli-sense and choose 'editor.lineNumber'
* notice the result, I would expect that the 'editor.' I typed gets overwritten

![screen shot 2016-01-28 at 16 52 46](https://cloud.githubusercontent.com/assets/1926584/12649603/97e71444-c5df-11e5-965c-2e6061ac40e9.png)

**Comment by aeschli** [comment] 2016-01-28 19:16
duplicate of #2342

**Closed by aeschli** 2016-01-28 19:16 UTC
Labels: bug, json
