### ISSUE TITLE
proposal: paste/drag image embeds into markdown

### ISSUE THREAD

**Issue by cutecycle** [microsoft/vscode#156676] opened 2022-07-29 15:41 UTC
I am aware of the Markdown Paste extension, but I think it would be ideal for this to be part of vscode's built-in markdown functionality. 

I think one of the top causes of OneNote/Docs/Slack/jirapages proliferating in engineering teams (and resulting in later cycles of trying to get it under control/portable/flexible or meet an organizational documentation standard by getting it into the repository in markdown) is the ergonomics of image pasting. 

It's "easy" to install the extension, find that it doesn't just override Ctrl-V, search the command palette, find out it's an entirely separate command to paste, use that, and then have it ask you what you want to name the file in a follow up modal dialog... but if you present that as a solution, especially in early stages/when there's time constraints, it'll always be "too complicated" relatively.
![image](https://user-images.githubusercontent.com/12169942/181793342-02f03764-2b31-4620-94bf-401d3f1c0e06.png)

GitHub and Azure Devops support pasting an image directly from the clipboard and having its location automatically translated to a working markdown image embed in a single step, in multiple editing contexts.
![image](https://user-images.githubusercontent.com/12169942/181793387-2bb1687a-32eb-4d65-8add-9105816d2315.png)

**Comment by mjbvz** [comment] 2022-08-01 20:41
Duplicate of #30066

See the `markdown.experimental.editor.pasteLinks.enabled` setting

**Closed by mjbvz** 2022-08-01 20:41 UTC
