### ISSUE TITLE
Word wrap should not break before a space

### ISSUE THREAD

**Issue by mhchem** [microsoft/vscode#47990] opened 2018-04-16 18:54 UTC
Line breaking does not work 100%

Copy the text below into a plain text document (with word-wrap enabled) and slowly resize the width of the editor.

abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc, abc

a) At some widths, some lines will start with a space.
b) At some widths, the last-but-one line will end in `abc,abc`, forgetting about the space that actually is there.

Visual Studio Code 1.21.1

**Comment by alexandrudima** [comment] 2018-04-17 08:53
@mhchem I cannot reproduce anything wrong:

![kapture 2018-04-17 at 10 52 14](https://user-images.githubusercontent.com/5047891/38859025-720dc0d4-422d-11e8-83ad-95dfccb35db3.gif)

**Comment by mhchem** [comment] 2018-04-18 06:06
Strange. I cannot reproduce (b) either.

But (a) can be seen on your image.
When breaking text lines, they should never start with a space.

![image](https://user-images.githubusercontent.com/16336692/38914346-4d948604-42df-11e8-91c0-2a853aa04a78.png)

**Comment by mhchem** [comment] 2018-04-18 06:07
@alexandrudima Strange. I cannot reproduce (b) either.

But (a) can be seen on your image.
When breaking text lines, they should never start with a space.

![image](https://user-images.githubusercontent.com/16336692/38914346-4d948604-42df-11e8-91c0-2a853aa04a78.png)

**Comment by EduardoSH18** [comment] 2018-07-13 16:49
On Visual studio code version 1.25.1 cannot reproduce (b).
on version 1.25.1 (a) it's still happening.

**Comment by martinauer** [comment] 2019-11-16 13:59
Problem (a) -- whitespace displayed at start on new line under word wrap, if comma ends preceding line -- still exists in v1.40.1 on macOS. While not fatal, it is extremely distracting; a fix would be greatly appreciated. Thanks!

**Comment by alexdima** [comment] 2020-01-10 09:54
Fixed with the fix for https://github.com/microsoft/vscode/issues/33366

**Closed by alexdima** 2020-01-10 09:54 UTC
Labels: editor-wrapping, feature-request

**Comment by alexdima** [comment] 2020-01-27 23:25
To verify, please check that you don't have wrapping points introduced right before a space. The following is not desirable:
![image](https://user-images.githubusercontent.com/16336692/38914346-4d948604-42df-11e8-91c0-2a853aa04a78.png)
