### ISSUE TITLE
Source Control: Command+Enter no longer syncs after committing

### ISSUE THREAD

**Issue by sschultze** [microsoft/vscode#157235] opened 2022-08-05 09:06 UTC
Type: <b>Bug</b>

In previous versions, Comment+Enter would do what the large button right under the message input box does - commit and sync.

In the current version, Command+Enter only commits and does not sync. I have to click the large button instead to commit and sync. This can be very annoying as this way, syncing is easily forgot.

Expected: Command+Enter again performs the same action as the large button under the message input box - commit and sync.

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:39:20.716Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv|--crash-reporter-id cdc0e6d9-8ca3-4968-a189-ac301fe5ea29|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
csharp|ms-|1.25.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728
hb751961:30541207
dsvsc012cf:30540253

```

</details>

**Comment by tisswb** [comment] 2022-08-09 02:32
same issue

**Comment by lszomoru** [comment] 2022-08-09 07:54
@sschultze, the default behaviour of the "Commit" action button can be controlled using the `git.postCommitCommand` setting. Could you please check the value of this setting? Does setting the value of the setting to `sync` resolve the issue? Thanks!

**Comment by sschultze** [comment] 2022-08-09 08:22
@lszomoru I had already checked if the update process changed this setting and checked again - `git.postCommitCommand` is still set to `sync`.

All `git.*` settings:

```json
"git.enableSmartCommit": true,
"git.autofetch": true,
"git.postCommitCommand": "sync",
"git.rebaseWhenSync": true,
"git.confirmSync": false,
```

**Comment by sschultze** [comment] 2022-08-09 08:23
And there are no project-specific settings other than `typescript.tsdk`.

**Comment by lszomoru** [comment] 2022-08-09 09:01
@sschultze, thank you! I am closing this as duplicate of https://github.com/microsoft/vscode/issues/157002. A fix for this should be released later today in Insiders and will do my best so that it makes it into the Stable recovery release that is planned for the second half of this week. Apologies for the inconvenience.

**Closed** 2022-08-09 09:01 UTC
Labels: git, *duplicate, new release

**Comment by sschultze** [comment] 2022-08-09 13:03
@lszomoru Great, thank you!
