### ISSUE TITLE
Add ability to remove control+click = goToDefinition

### ISSUE THREAD

**Issue by msftmeason** [Microsoft/vscode#59141] opened 2018-09-21 22:30 UTC
Issue Type: <b>Feature Request</b>

Related to:
https://stackoverflow.com/questions/37683703/how-to-disable-ctrl-click-in-vs-code

In Visual Studio, I can change the control+click behavior for when hovering over a variable or function name to quick select it for copy+paste/overwrite/etc.  In VSCode, this functionality is removed and users that attempt to control+click on an element will instead navigate away.  This is extremely frustrating for those of us who like to quickly select an element and are used to how Visual Studio works.

Please get this IDE up to par with the standard set by Visual Studio.  It's deeply ingrained enough in my muscle memory that I can't use VSCode at all until this is implemented.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

**Comment by rebornix** [comment] 2018-09-24 17:56
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2298 and let's track it in https://github.com/Microsoft/vscode/issues/3130

**Closed** 2018-09-24 17:56 UTC
Labels: *duplicate, editor, editor-folding
