### ISSUE TITLE
Cannot use provided Bug Report for Extension Go Critic - Description Required

### ISSUE THREAD

**Issue by wayneforrest** [microsoft/vscode#214665] opened 2024-06-08 06:13 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:48.028Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

Steps to Reproduce:

1. Open The Dialog as shown in the dialog, and click the button.,
![Screenshot 2024-06-08 at 6 11 07 PM](https://github.com/microsoft/vscode/assets/10992743/1ced1a18-a7cc-466f-800b-42247087c906)

**Comment by justschen** [comment] 2024-06-27 20:46
there is a PR out to fix the UI element of this, but there is an underlying issue. 

atm, Go Critic does not provide a valid `bugsURL`, but instead provides a `repositoryURL`, so reporting issues via the issue reporter here is not valid. After the fix is in, I will submit an issue on the Go Critic side 👍 

Thanks for catching this!

**Comment by gjsjohnmurray** [comment] 2024-10-06 05:54
Looks like a duplicate of #219574 which is now fixed. But maybe @justschen is keeping ti's open for follow-up action noted above.

**Closed** 2024-12-10 09:49 UTC
Labels: bug, issue-reporter
