### ISSUE TITLE
context menus not getting hooked up to commands in Insiders

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#23313] opened 2017-03-27 22:15 UTC
i found this because my extension https://github.com/chrisdias/vscode-opennewinstance stopped working when you right click on a folder.  Same problem happens with Erich's npm extension.

- VSCode Version: insiders 1.11.0 c995ecf
- OS Version: MacOS

Steps to Reproduce:

1. clone https://github.com/chrisdias/vscode-opennewinstance, run npm install, open code-insiders
2. but a breakpoint in extension.ts on the line 16 
3. press F5
4. in development instance, open some workspace that has folders in it
5. right click on a folder and choose "Open New Workbench Here"

Result: Nothing happens, breakpoint is not hit, the command is not executed.

6. Open command palette
7. execute command "Open New Workbench Here" 

Result: breakpoint is hit.

However, notice that `e` is `undefined`.  in stable, it comes in as `null`.

**Comment by kieferrm** [comment] 2017-03-28 00:09
Duplicate of #23162.

**Closed by kieferrm** 2017-03-28 00:09 UTC
Labels: duplicate
