### ISSUE TITLE
Better documentation for snippet transform grammar

### ISSUE THREAD

**Issue by dogoku** [Microsoft/vscode#36052] opened 2017-10-11 10:50 UTC
- VSCode Version: 1.17
- OS Version: N/A

The snippet transform feature is one I have been waiting for a long time, but there is no documentation on it, other than the one `/capitalize` [example in the release notes of v1.17](https://code.visualstudio.com/updates/v1_17#_snippet-transforms).

I tried using textmate/sublime transforms but they don't seem to be recognised

For example `${TM_FILENAME/^(\w)|(?:-(\w))|(\.js$)/(?1\u$1:)(?2\u$2:)/g}` is a transform that reads a filename in the format `my-file-name.js` and converts it to `MyFileName` (taken from a sublime snippet I wrote years ago)

I also tried being clever and using `${1:${TM_FILENAME/(.*)\\.js/${1:/hyphenate}/}}` hoping that `hyphenate` was already implemented, but again no cigar.

Are their plans of updating the docs or can you atleast point us to the transform syntax and available keywords for transforms? Is there a way to define our keywords? (e.g /hyphenate)

**Comment by jrieken** [comment] 2017-10-11 14:16
Good catch. This should have happened for the October release. The tracking item is this one https://github.com/Microsoft/vscode-docs/issues/1190

**Comment by jrieken** [comment] 2017-10-11 14:18
Closing this as a dupe of https://github.com/Microsoft/vscode-docs/issues/1190. Let me know if you want more docs on the subject

**Closed by jrieken** 2017-10-11 14:18 UTC
Labels: question, snippets

**Comment by dogoku** [comment] 2017-10-11 18:41
Thanks for the reply. I made a new issue for an actual bug that is related to this one: #36089
