### ISSUE TITLE
Project name and the four actions are not removed from explorer title

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#48179] opened 2018-04-19 07:04 UTC
Issue Type: <b>Bug</b>

1. Hide "Open Editors"
2. Show "Open Editors"
![explorer](https://user-images.githubusercontent.com/24318019/38976113-cfb10578-43e2-11e8-999c-656a8ac8a207.gif)
![explorer](https://user-images.githubusercontent.com/24318019/38976120-d68950b2-43e2-11e8-83bd-d5f11dbb45d1.png)

VS Code version: Code - Insiders 1.23.0-insider (88f500e805ecc4efd064f7886c1a5ce8a2a2c087, 2018-04-18T05:16:18.357Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
debugger-for-chrome|msj|4.3.0

</details>

**Comment by isidorn** [comment] 2018-04-19 13:32
After debugging the issue is that PanelViewlet thinks it is not in single view when the `OpenEditors` view is added back.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L550
visibleViewsCount is 2 there, and it should be 1. Assigning to @sandy081

**Comment by sandy081** [comment] 2018-04-19 16:13
This is caused by #45033. Two fixes are needed.

**Fix 1:** Headers are getting updated only if there is a change in `isSingleView` value. `ViewsViewlet` is computing `isSingleView` value from the registered view descriptors. Hence while panel is being added `isSingleView` values remains same before and after. So **Fix** is to let `ViewsViewlet` compute `isSingleView` value from panels length.

**Fix 2:** Above fix breaks #37084. Because panels are being added one by one and `PanelViewlet` updates headers after a panel is added. This is overriding the state of the panel, like, collapsed. **Fix** is to allow adding panels in bulk instead of one. `PanelViewlet` should support this API because it is the one that checks `isSingleView` and updates headers.

**Closed** 2018-04-19 16:14 UTC
Labels: bug, workbench-views

**Comment by isidorn** [comment] 2018-04-20 08:26
@sandy081 thanks for the analysis and the fix
