### ISSUE TITLE
Code Plugin CPU 100%

### ISSUE THREAD

**Issue by Alice-space** [microsoft/vscode#233076] opened 2024-11-05 11:42 UTC
Type: <b>Performance Issue</b>

Code Helper (Plugin) app takes 100% CPU

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 24.1.0
Modes:
Remote OS version: Linux x64 5.14.0-427.40.1.el9_4.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (3.98GB free)|
|Process Argv|--crash-reporter-id 676919ff-7b6e-4485-a5f1-954be54a035d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: optiplex6|
|OS|Linux x64 5.14.0-427.40.1.el9_4.x86_64|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700 (24 x 0)|
|Memory (System)|77.74GB (74.80GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	   229	 12949	code main
    0	    82	 12952	   gpu-process
    0	    33	 12953	   utility-network-service
   10	   115	 13011	shared-process
    0	     0	 13673	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   393	 13614	window [2] (WGAN.py — cepc-fastecalsim [SSH: optiplex6])
  100	   180	 13616	extensionHost [2]
    0	    49	 13619	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=13616
    0	    66	 13623	fileWatcher [2]
    0	   131	 13624	extensionHost [2]
    0	    49	 13634	     electron-nodejs (localServer.js data.js )
    0	     0	 13643	       ssh -v -T -D 60633 -o ConnectTimeout=15 optiplex6

Remote: SSH: optiplex6
CPU %	Mem MB	   PID	Process
    0	    16	 62233	remote agent
    0	     0	 62306	   ptyHost
    0	     0	 62651	     /usr/bin/bash --init-file /home/alice/.vscode-server/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/server/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
    0	     0	 62819	     /usr/bin/bash --init-file /home/alice/.vscode-server/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/server/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
    0	    33	 62453	   extension-host
    0	     0	 62539	     /home/alice/.vscode-server/extensions/ms-python.python-2024.18.0-linux-x64/python-env-tools/bin/pet server
    0	    66	 62768	     /home/alice/.vscode-server/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/server/node /home/alice/.vscode-server/extensions/ms-python.vscode-pylance-2024.11.1/dist/server.bundle.js --cancellationReceive=file:56de24614b2d53fda10fd54683d842022ce739ff88 --node-ipc --clientProcessId=62453
    0	    16	 62464	   fileWatcher
    0	     0	 62976	   /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: optiplex6|    Folder (cepc-fastecalsim): 7928 files|      File types: yaml(2632) 0(86) 1(43) 2(43) 3(43) 4(43) 5(43) 6(43) 7(43)
|                  8(43)
|      Conf files:;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
vscode-remote-extensionpack|ms-|0.26.0
remote-explorer|ms-|0.4.3
material-icon-theme|PKi|5.12.0
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by mjbvz** [comment] 2024-11-05 19:14
Duplicate of #232699 based on the symptoms

**Closed by mjbvz** 2024-11-05 19:14 UTC
