### ISSUE TITLE
【vscode.dev】 TS file or JS file the  IntelliSense is always loading.

### ISSUE THREAD

**Issue by darrenweb** [microsoft/vscode#222017] opened 2024-07-18 04:18 UTC
1,In the latest version of Chrome open https://vscode.dev/github/microsoft/vscode-vsce

2,Open any TS file or JS file

3,You will find that IntelliSense is always loading. 

It's been 1 hour and it's still loading See the screenshot.
![94}2X591YP4XW~4T`8X21YY](https://github.com/user-attachments/assets/ce7dfa99-1432-4556-a796-c32e3f934a7c)

**Comment by mjbvz** [comment] 2024-07-23 21:57
Duplicate of #221299

**Closed by mjbvz** 2024-07-23 21:57 UTC
