### ISSUE TITLE
Lagging due to TypeScript and JavaScript Language Features extension

### ISSUE THREAD

**Issue by JakubKoralewski** [microsoft/vscode#75077] opened 2019-06-07 14:08 UTC
Issue Type: <b>Performance Issue</b>

Takes a few seconds for VSCodeVim to input. Checked without VSCodeVim and the slowdown typing feeling happens as well. Happens often but not always. The slowdown can also be experienced by scrolling under some load period.

Project has only a few TypeScript files.
![](https://i.imgur.com/4dvWKKh.png)

Here's a performance profile gist: https://gist.github.com/JakubKoralewski/2a188bc8c17bd18e2062e59f24616c58

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-6800K APU with Radeon(tm) HD Graphics   (4 x 4091)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.24GB free)|
|Process Argv|--inspect-extensions=9993 .|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    96	 16204	code main
    0	    74	 13292	   shared-process
    0	   379	 14976	   window (Running Extensions - pro - Visual Studio Code)
    0	    16	 14364	     watcherService 
    0	     5	  7660	       console-window-host (Windows internal process)
    0	  1000	 14520	     extensionHost
    0	    21	  2264	       electron_node server.js 
    0	   206	  6064	       electron_node tsserver.js 
    0	    21	 15392	         electron_node typingsInstaller.js typesMap.js 
    0	    19	 14784	       electron_node eslintServer.js 
    0	    20	 15860	       "F:\PROGRAMY\VS Code\Microsoft VS Code\Code.exe" --nolazy --inspect=16104 "f:\PROGRAMY\VS Code\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=14520
    0	    45	 17104	       "F:\PROGRAMY\VS Code\Microsoft VS Code\Code.exe" --nolazy --inspect=6045 "f:\PROGRAMY\VS Code\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=14520
    0	    18	 18160	       "F:\PROGRAMY\VS Code\Microsoft VS Code\Code.exe" --nolazy --inspect=6044 "f:\PROGRAMY\VS Code\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=14520
    0	     9	 15936	     electron-crash-reporter
    3	   134	 16312	   gpu-process
    5	    57	 19140	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Running Extensions - pro - Visual Studio Code)
|    Folder (pro): 1170 files
|      File types: ts(843) svg(220) json(33) js(20) md(20) html(12) scss(9)
|                  tsx(7) css(2) png(2)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|                  webpack.config.js(1) settings.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
vscode-sqlite|ale|0.7.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-clock|Com|0.0.1
smali|cra|1.0.1
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.0
vscode-faker|dee|1.3.0
gitlens|eam|9.8.1
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
vscode-pull-request-github|Git|0.8.0
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.134
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
latex-workshop|Jam|7.0.2
svelte-vscode|Jam|0.9.1
svg|joc|0.1.4
php-cs-fixer|jun|0.1.119
MagicPython|mag|1.1.0
eclipse-new-java-project|mel|1.0.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.6.2
mssql|ms-|1.6.0
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
vscode-typescript-tslint-plugin|ms-|1.1.0
vsliveshare|ms-|1.0.337
debugger-for-chrome|msj|4.11.3
vetur|oct|0.21.0
unicode-latex|oij|1.1.2
material-icon-theme|PKi|3.8.0
format-html-in-php|rif|1.5.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vscode-paste-and-indent|Rub|0.0.8
rust|rus|0.6.1
code-settings-sync|Sha|3.2.9
vue-docs|tit|1.0.2
vim|vsc|1.8.1
vscode-todo-highlight|way|1.0.4
code-d|web|0.20.2
JavaScriptSnippets|xab|1.7.2
local-history|xyz|1.7.0
markdown-all-in-one|yzh|2.3.1
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

I have now noticed that according to the workspace info I have 843 ts files, but they must be in node_modules, because my actual project only has 3 or 4 TypeScript files.

**Comment by mjbvz** [comment] 2019-06-07 18:07
@JakubKoralewski Do you see this if you disable your other extension? Use the `Developer: reload with disabled extensions` command to test this.

@jrieken The profile shows two long running calls:

* One in the `$provideCodeActions._withAdapter` call
* One for `getFolder`

Neither of these make sense to me. Any idea what could be causing the reported perf issue?

**Comment by JakubKoralewski** [comment] 2019-06-07 20:41
@mjbvz The problem seems to be gone once I reload the window with the extensions disabled.

**Comment by mjbvz** [comment] 2019-06-11 17:31
Ok, closing as not-reproducable / caused by extension

**Closed by mjbvz** 2019-06-11 17:31 UTC
Labels: javascript, needs more info, perf
