### ISSUE TITLE
Where have the GIT related widgets gone?

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode#41226] opened 2018-01-06 17:30 UTC
- VSCode Version: 1.20 insiders
- OS Version: Ubuntu 17.10 + Linux 4.14.12
Steps to Reproduce:

1. Open a folder that's under GIT revision control
2. When needing to push a change, notice that the button we used to push to synchronize changes is gone. (have to use drop down in SCM viewlet instead)

![image](https://user-images.githubusercontent.com/7761010/34642223-c3eb0cee-f30f-11e7-98b6-2654c52fbc08.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment] 2018-01-06 18:22
Duplicate of https://github.com/Microsoft/vscode/issues/41203

**Comment by joaomoreno** [comment] 2018-01-08 10:51
https://github.com/Microsoft/vscode/issues/40851

**Closed by joaomoreno** 2018-01-08 10:51 UTC
Labels: git, insiders
