### ISSUE TITLE
Scroll issue in explorer

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#50762] opened 2018-05-30 06:41 UTC
Hello,

- VSCode Version: 1.23.1
- OS Version: Win10 x64

Steps to Reproduce:

1. Open any project
2. See below

![vscode](https://user-images.githubusercontent.com/9152330/40703322-05b9fc1a-63fa-11e8-9065-9fb169af0603.gif)

Does this issue occur when all extensions are disabled?: Yes

Thanks.

**Comment by pqvst** [comment] 2018-05-30 10:55
Today I also noticed that my file tree explorer has gone completely haywire. I've noticed:
- Items reordering randomly while scrolling
- Items reordering randomly while expanding subfolders
- The top of the tree appears out of order
- Middle sections of the tree appearing out of order

Seems to only happen when I have many files visible/expanded.

![wtf](https://user-images.githubusercontent.com/4990657/40716265-a6403f10-6408-11e8-974e-09083593d11c.png)

**Comment by dehghani-mehdi** [comment] 2018-05-30 13:11
Dear bot, mentioned issue is really useful :p

**Comment by octref** [comment] 2018-05-30 19:53
@dehghani-mehdi @pqvst Do you have any public project where you can reproduce this issue?

**Comment by dehghani-mehdi** [comment] 2018-05-31 12:18
@joaomoreno  How this issue is duplicate of mentioned issue?!
Maybe related but not duplicate.

**Comment by pqvst** [comment] 2018-05-31 13:19
@joaomoreno If it helps, I've been working in the same repo for many months without experiencing any issues like this, until yesterday. Yesterday was, however, the first day that my repo contained a `.vscode` folder. I have no idea if that is related.

**Comment by octref** [comment] 2018-05-31 15:30
@joaomoreno From what I see, #22269 seems to be specific about creating new files and cancelling the operation, whereas this one files (`webpack.config.js` and `postcss.config.js`) disappeared from the explorer by just scrolling.

**Comment by dehghani-mehdi** [comment] 2018-06-01 05:40
To be more specific, the content height is less than available height in explorer. that's the problem.

**Comment by joaomoreno** [comment] 2018-06-01 06:49
I see. @pqvst, from your screenshot, it seems you have the tree issue #22269. If your issue is the appearance of a `.vscode` folder, then read @octref's comment.

---

@dehghani-mehdi If you restart Code, does the issue reliably reproduce? Can you provide a full screen recording of that happening? Does it happen on other projects? Do it happen on other machines?

**Comment by joaomoreno** [comment] 2018-06-04 10:06
@dehghani-mehdi Excellent! Does the issue get fixed once you resize Code's window?

**Comment by dehghani-mehdi** [comment] 2018-06-07 04:17
@joaomoreno Nope

**Comment by joaomoreno** [comment] 2018-06-07 08:03
Can you show me what happens when you resize the window?

**Comment by dehghani-mehdi** [comment] 2018-06-09 05:58
Here you go

![vscode3](https://user-images.githubusercontent.com/9152330/41188230-c4523728-6bcf-11e8-8b9c-9c9f02fef376.gif)

**Comment by dehghani-mehdi** [comment] 2018-06-11 09:31
I have no idea about `[Unsupported]`, but yes, I use [Custom CSS and JS Loader](https://github.com/be5invis/vscode-custom-css), but i tested with `--disable-extensions` switch and same happens. (and `[Unsupported]` is still there)

![vscode](https://user-images.githubusercontent.com/9152330/41223739-e4caf42a-6d7f-11e8-93e2-f328f3d0a05a.gif)

I don't remember last time that I saw VSCode without `[Unsupported]`.

**Comment by joaomoreno** [comment] 2018-06-12 09:37
`[Unsupported]` started appearing with Custom CSS and JS Loader, for sure. This is an extension which intently changes core CSS and JS of VS Code. If you install it, we can provide no support to you, since we don't control what that extension manipulates.

I'm going to ask you once again: Can you reproduce it in a fresh build? vscode-update.azurewebsites.net/latest/win32-x64-archive/insider Download that, double click Code.exe and check whether the issue still exists.

**Comment by dehghani-mehdi** [comment] 2018-06-12 10:01
I just checked my co-worker's VSCode and there was `[Unsupported]`  too, I double check the installed extensions list and there was nothing special. I think the `[Unsupported]` added by default! I'm sure I saw  `[Unsupported]` even before installing Custom CSS and JS Loader.

Anyway I'll try the fresh build and let you know the result.

**Comment by dehghani-mehdi** [comment] 2018-06-12 10:15
With insider everything is as should be and there is no issue with the scroll.

**Comment by joaomoreno** [comment] 2018-06-13 07:21
Alright, closing it.

My suggestion is to remove that extension, uninstall VS Code and install it again. Try to stay away from extensions which hack into our core files. If you have `[Unsupported]` in the title bar, we can't provide any support.

**Closed by joaomoreno** 2018-06-13 07:21 UTC
Labels: needs more info

**Comment by dehghani-mehdi** [comment] 2018-06-13 09:17
Thanks,

Default style of VSCode is not good enough (_that's way extensions like Custom CSS and JS Loader created_) and I prefer to use/hack core css and fix this issue by myself than stay with default style.
