### ISSUE TITLE
Debug: pressing F5 may skip the following breakpoint(s) while using the debug controls does not.

### ISSUE THREAD

**Issue by nicoabie** [microsoft/vscode#124949] opened 2021-05-31 00:29 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
1.57.0-insider (Universal)
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T10:00:38.762Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.3.0
- OS Version: macOS Big Sur 11.2.3 (20D91)

Steps to Reproduce:

1. Have a project with consecutive breakpoints 
2. Using the debug controls clicking the "pause play" button will go to the next breakpoint but if pressing F5 it may jump over it.

Possible thing that is happening is that pressing F5 may send many signals to the debugger but clicking it just sends one.
I was able once to press F5 quick enough to not jump over it.

**Comment by weinand** [comment] 2021-05-31 07:26
What debugger are you using?

**Comment by nicoabie** [comment] 2021-05-31 11:52
Nodejs debugger and using the touchbar, sorry for not mentioning those.

**Comment by isidorn** [comment] 2021-05-31 12:40
I can not reproduce this. Both F5 and the debug toolbar go to the same command. 
@connor4312 also assigning to you since this might be on the js-debug side.

/jsDebugLogs

**Comment by nicoabie** [comment] 2021-05-31 12:49
@isidorn I'm not questioning that they both go to the same command because both go to the next breakpoint (but in the case of pressing F5 with the touch bar you have to press it very quick, if not it skips it)
I've tested it many times to make sure I'm not saying crazy things.

Is it posible that pressing F5 sends many signals and clicking on the debug control just sends one?

**Comment by isidorn** [comment] 2021-05-31 12:57
@nicoabie that is the reason why I asked you to provide logs. So can you please provide logs when you reproduce the issue and we will see if multiple requests are being sent out (they should not)

**Comment by nicoabie** [comment] 2021-05-31 13:04
Could you provide me the file path where the log location is, because it doesn't appear in the debug tab :(

**Comment by nicoabie** [comment] 2021-05-31 14:01
[vscode-debugadapter-ea8697ab.json.gz](https://github.com/microsoft/vscode/files/6570735/vscode-debugadapter-ea8697ab.json.gz)

**Comment by connor4312** [comment] 2021-06-01 21:14
I'm not seeing anything weird, there is one stopped event, and then one resume call. I'm not sure how the UI would affect that. It looks like you had a breakpoint in `mergeIncludes.test.ts`, however, which was never loaded by the program. Since you are attaching to jest rather than launching it directly, make sure to set `--runInBand` when you start.

**Comment by nicoabie** [comment] 2021-06-01 23:01
Thing that I'm experiencing now with the debugger is that it stops on even runs (or odd) but it works, it doesn't, it works, it doesn't. I swear to god I'm no crazy

**Comment by connor4312** [comment] 2021-06-01 23:14
that is something that I could expect in attach mode without --runInBand

**Closed** 2021-06-09 11:27 UTC
Labels: debug, needs more info
