### ISSUE TITLE
VS Code doesn't start anymore 

### ISSUE THREAD

**Issue by alfiobiondo** [microsoft/vscode#219901] opened 2024-07-03 22:36 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.0
- OS Version: MacOs Big Sur 11.7.10

Steps to Reproduce:

1.  [2890:0704/003248.433136:ERROR:node_bindings.cc(162)] Fatal error in V8: v8::Template::Set Invalid value, must be a primitive or a Template
2.  [1]    2890 segmentation fault  /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron

**Comment by mjbvz** [comment] 2024-07-03 23:41
Duplicate of #219893

**Comment by britniangela** [comment] 2024-07-03 23:42
How do we open VS now that the update has caused issue?

**Closed by mjbvz** 2024-07-03 23:41 UTC
Labels: new release

**Comment by britniangela** [comment] 2024-07-03 23:59
I downloaded the May version but now I have two VS Codes on my computer so
now what do I do? I'm not a professional coder or tech person. Just a
random person going through an online course.
-----------------------
*Britni Burdette*
Assistant TM | VIP Manager | Merch
(407) 454-1979
***@***.***
"A Jane of all trades."

**Comment by sunnydsouza** [comment] 2024-07-04 04:39
I suffer from this same issue and get the same error, as soon I updated to the latest version[2890:0704/003248.433136:ERROR:node_bindings.cc(162)] Fatal error in V8: v8::Template::Set Invalid value, must be a primitive or a Template

**Comment by mahmoud-bebars** [comment] 2024-07-04 07:37
I have Same Issue & even after reinstalling VSCode & losing all the data I can not open it 
starting for one sec & then crash 
the terminal throws this error 
```
/Applications/VSCode.app/Contents/MacOS/Electron ; exit;
[3695:0704/103432.755487:ERROR:node_bindings.cc(162)] Fatal error in V8: v8::Template::Set Invalid value, must be a primitive or a Template
zsh: segmentation fault  /Applications/VSCode.app/Contents/MacOS/Electron
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by buzzdev** [comment] 2024-07-04 13:41
Me too.
MacOS 11.7.10

```
[1018:0704/153754.151251:ERROR:node_bindings.cc(162)] Fatal error in V8: v8::Template::Set Invalid value, must be a primitive or a Template
Segmentation fault: 11
```

**Comment by AlexR2D2** [comment] 2024-07-05 06:09
the same, macOS 11.7.10

**Comment by axellentx2** [comment] 2024-07-05 07:32
Same here on macOS 11.7.10 (Big Sur)

**Comment by cnwarden** [comment] 2024-07-05 07:58
the same(macos 11.7.10), solved by installing 1.90

**Comment by jspeaks** [comment] 2024-07-05 18:50
same(macos 11.7.10), solved by installing 1.90

**Comment by Azhy-Slemany** [comment] 2024-07-05 19:08
Same here (macOS 11.7.9), and the problem is that I deleted all the caches of VS Code.

**Comment by aossey** [comment] 2024-07-06 01:54
Same issue (macos 11.7.10).

**Comment by lemon1964** [comment] 2024-07-06 13:48
The same. After reinstalling to the May and January versions, it still does not open.
V8 is associated with the JS engine, reinstalled node. Still won't open. On my Mac 11.7 VSCode seems to have died. How can you still revive him, three hours ago he was still so vigorous...?

**Comment by ivanistheone** [comment] 2024-07-06 14:47
Thx @alfiobiondo for the workaround using v1.90

**Comment by froestiago** [comment] 2024-07-06 17:36
This problem happened to me after a 'force quit' last night
The workaround of using v.1.9.0 solved the question here.
(Make sure to disable auto-update)
Thank you!
macOS version 10.15.7

**Comment by xavier-kirkpatrick** [comment] 2024-07-07 03:24
Same issue here with version 1.91. Uninstall 1.91 and reinstall 1.90. Make sure right after you reinstall you disconnect from the internet and disable auto updates then restart, as it will update to 1.91 very discretely and break again.

**Comment by warjiang** [comment] 2024-07-07 16:48
Also suffered from the same problem, more detailed info as following, may it helps for debug:
![image](https://github.com/microsoft/vscode/assets/6478745/9bcf03fd-19c0-4223-b62b-dddc46dddba6)


BTW, the vscode version info:
```
1.91.0
ea1445cc7016315d0f5728f8e8b12a45dc0a7286
x64
```

**Comment by deepak1556** [comment] 2024-07-08 00:31
Please check https://github.com/microsoft/vscode/issues/219893 for latest updates, the issue has been addressed in insiders https://code.visualstudio.com/insiders and will be addressed in stable this week as part of `1.91.1` release.

**Comment by davideperi** [comment] 2024-07-08 12:40
Same here with Mac 11.6.1

**Comment by RollingTL** [comment] 2024-07-09 10:20
Same here!

**Comment by TheTridentGuy** [comment] 2024-07-10 00:50
Same here on MacOS 10.15.
