### ISSUE TITLE
Primary Side Bar empties it self after reopenning the VS Code, if Activity Bar is toggled off

### ISSUE THREAD

**Issue by hbaklan943** [microsoft/vscode#191910] opened 2023-08-31 14:43 UTC
Type: <b>Bug</b>

Steps to reproduce:
- Open a folder ,which includes some files, in VS Code
- Press Folders icon in Activity Bar to see File Explorer in Primary Side Bar (You can see the files)
- Toggle the Activity Bar Visibility (View: Toggle Activity Bar Visibility)
- Close VS Code and open it again 
- Now you see an empty Primary Side Bar.

Actual Result: User sees a useless Primary Side Bar and more importantly  doesn't looks like how you left it before closing the VS Code.
![image](https://github.com/microsoft/vscode/assets/39270324/edb788bd-0ddd-4b0b-bd66-bd9a50093f3c)

Expected Result: When restarting VS Code Primary Side Bar shows the last view it was showing(Eg. Folders, Source Control, Search, Extensions...)
![image](https://github.com/microsoft/vscode/assets/39270324/42ac9630-23f9-470a-ae09-f5d09e1a99ae)

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 6.2.0-27-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics (12 x 3970)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|14.99GB (7.68GB free)|
|Process Argv|. --crash-reporter-id 6919f149-b701-4f66-bbd9-42e7ed645c8e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.19.0
vscode-chrome-extesion-manifest-json-schema|cez|1.0.2
js-codeformer|cms|2.6.1
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.50
dart-code|Dar|3.70.0
flutter|Dar|3.70.0
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.1.0
vscode-google-translate|fun|1.4.13
codespaces|Git|1.15.0
copilot|Git|1.106.367
gc-excelviewer|Gra|4.2.58
rest-client|hum|0.25.1
easy-snippet|inu|0.6.3
better-cpp-syntax|jef|1.17.2
vscode-docker|ms-|1.26.0
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.50
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
material-icon-theme|PKi|4.30.1
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1641
vue-vscode-snippets|sdr|3.1.1
js-jsx-snippets|sky|11.0.1
tauri-vscode|tau|0.2.6
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
volar|Vue|1.8.8
JavaScriptSnippets|xab|1.8.0
google-translate-turkish|yas|0.2.0
material-theme|zhu|3.16.0

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
962ge761:30823813
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by hbaklan943** [comment] 2023-08-31 15:29
Also when I have 2  or more VS Code windows opened and toggle the Activity Bar on one of them the other ones also toggles the Activity Bar. This might be related.

**Comment by lramos15** [comment] 2023-08-31 15:31
I can't reproduce this. Please try insiders
https://code.visualstudio.com/insiders/

**Comment by hbaklan943** [comment] 2023-08-31 21:04
You are right, I installed insiders and can't reproduce either but my second point still exists(Also when I have 2 or more VS Code windows opened and toggle the Activity Bar on one of them the other one also gets affected by this action and toggles the Activity Bar.).

**Comment by hbaklan943** [comment] 2023-08-31 21:07
Will we see the fix on the next stable release cause it is annoying to see an empty Primary Side Bar.

**Comment by lramos15** [comment] 2023-08-31 21:33
Insiders gets released as stable come end of next week. So this should be fixed soon.

**Closed by lramos15** 2023-08-31 21:33 UTC
Labels: info-needed
