### ISSUE TITLE
Extension host terminated unexpectedly...

### ISSUE THREAD

**Issue by Malaya2184** [microsoft/vscode#94948] opened 2020-04-10 20:52 UTC
We have written the needed d
Issue Type: <b>Bug</b>

after the latest update this error is occurring with my vs code for several times.. so that no extensions are working ........
getting rid of it....
so much irritating...

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
c-cpp-compile-run|dan|1.0.7
gitlens|eam|10.2.1
auto-rename-tag|for|0.1.1
git-graph|mhu|1.22.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.3.71659
indent-rainbow|ode|7.4.0
java|red|0.59.1
vscode-yaml|red|0.7.2
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.0
vscode-todo-highlight|way|1.0.4

</details>
ata into your clipboard because it was too large to send. Please paste.

**Comment by Malaya2184** [comment] 2020-04-10 20:59
after reinstalling the vs code works perfectly but after the restart same problem is arising so please do some permanent solution....

**Comment by gjsjohnmurray** [comment] 2020-04-10 21:32
Check if your antivirus is interfering with VSCode files.

**Comment by RMacfarlane** [comment] 2020-04-11 06:55
Duplicate of https://github.com/microsoft/vscode/issues/94807, please read the issue here for how to fix: https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765

**Closed by RMacfarlane** 2020-04-11 06:55 UTC
Labels: new release

**Comment by Malaya2184** [comment] 2020-04-11 18:37
i have found the solution for this...
go to the quick heal
->file folders
->exclude file folder from scanning
->add file i.e C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js
->save changes...
It is working perfectly....
