### ISSUE TITLE
`AltGr+` keybindings move focus to the menu filter box

### ISSUE THREAD

**Issue by Mr-Pepe** [microsoft/vscode#110472] opened 2020-11-12 11:35 UTC
I use an xkb keymap to map AltGr+K/I to ArrowDown/ArrowUp. This works fine for navigation everywhere in VS Code except for the problems view. 

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.74-1-MANJARO

Steps to Reproduce:

1. Focus problems view
2. Use the arrowkeys of the keyboard to navigate problems -> works fine
3. Use the key combinations that are mapped to ArrowDown and ArrowUp in xkb to navigate problems -> focus jumps to filter box
4. Use the key combinations that are mapped to ArrowDown and ArrowUp in xkb inside the filter box -> gets recognized as arrow keys and scrolls through past filter searches as expected

Does this issue occur when all extensions are disabled?: Yes

**Comment by Mr-Pepe** [comment] 2020-11-20 15:23
I am using "keyboard.dispatch": "keyCode".

I also have a mapping for AltGr+N and now VS code does not recognize the N key anymore when combined with Ctrl. Assigning Ctrl+N as a shortcut in KDE system settings is no problem, but setting it in VS code does not work, because the shortcut editor only recognizes the Ctrl press, but not N.

**Comment by sandy081** [comment] 2020-11-27 07:01
Assigning to @alexdima as it seems keyboard related.

**Comment by alexdima** [comment] 2020-11-27 07:37
@Mr-Pepe 
Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command Developer: Toggle Keyboard Shortcuts Troubleshooting
  * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* You can then press your desired keybinding and check what keyboard shortcut VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and we can help decipher it for you.

**Comment by Mr-Pepe** [comment] 2020-11-27 11:56
@alexdima  Here are the logs. Once with AltGr+K and once with the actual down arrow key. I seems to me that both get resolved to DownArrow, but in the latter case it also triggers the list.focusDown keybinding. In the former case it instead focuses on the filter box.

```
[2020-11-27 12:34:15.725] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: AltRight, keyCode: 223, key: ShiftLevel5
[2020-11-27 12:34:15.725] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: AltRight, keyCode: 91 ('OEM_8')
[2020-11-27 12:34:15.725] [renderer1] [info] [KeybindingService]: | Resolving OEM_8
[2020-11-27 12:34:15.726] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2020-11-27 12:34:15.966] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: KeyK, keyCode: 40, key: ArrowDown
[2020-11-27 12:34:15.966] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: KeyK, keyCode: 18 ('DownArrow')
[2020-11-27 12:34:15.966] [renderer1] [info] [KeybindingService]: | Resolving DownArrow
[2020-11-27 12:34:15.966] [renderer1] [info] [KeybindingService]: \ From 13 keybinding entries, no when clauses matched the context.
```


Here the log for when I use the actual down arrow key.

```
[2020-11-27 12:45:21.274] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: ArrowDown, keyCode: 40, key: ArrowDown
[2020-11-27 12:45:21.274] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: ArrowDown, keyCode: 18 ('DownArrow')
[2020-11-27 12:45:21.277] [renderer1] [info] [KeybindingService]: | Resolving DownArrow
[2020-11-27 12:45:21.277] [renderer1] [info] [KeybindingService]: \ From 13 keybinding entries, matched list.focusDown, when: listFocus && !inputFocus, source: built-in.
```

Let me know if you need more info.

**Comment by alexdima** [comment] 2020-11-30 11:13
Thank you for the extra information. It looks like the focus might be leaving the list when `AltGr+K` is pressed. AFAIK, `Alt` sometimes can move the focus to the menu, so I wonder if that is what is happening here. Does it make any difference when configuring `"window.titleBarStyle": "native"` ?

**Comment by Mr-Pepe** [comment] 2020-12-07 13:34
Please reopen.
I already have "window.titleBarStyle": "native" set. 
Indeed, it seems that combining AltGr with any other key takes me to the filter box. However, the problems panel is the only place where I can observe this behavior. Navigating other lists works just fine. 
Is there a way to deactivate the behavior?

**Comment by alexdima** [comment] 2020-12-09 12:59
@Mr-Pepe I am trying to reproduce on my side, but I could not. 

I am using Ubuntu 20.04 with KDE Plasma and in order to reduce potential problems caused by xkb keymap, I bind directly in vscode `ctrl+alt+i` to `"list.focusDown"`:
* `settings.json`:
```js
// empty settings => dispatching on scan code (the default)
{}
```
* `keybindings.json`:
```
[
	{ "key": "ctrl+alt+i", "command": "list.focusDown", "when": "listFocus && !inputFocus" }
]
```

When I press `ctrl+alt+i`, the selection moves down in the problems list. To clarify, can you reproduce this without using xkb keymap? So for example if you have `ctrl+alt+f` free, could you try with binding that directly in vscode?

![Kapture 2020-12-09 at 13 57 31](https://user-images.githubusercontent.com/5047891/101632672-876a7000-3a26-11eb-896c-7d4f37a84ade.gif)

When you say "combining AltGr with any other key takes me to the filter box", what filter box do you mean?

**Comment by Mr-Pepe** [comment] 2020-12-09 22:09
The filter box is visible in your recording next to Problems, Output, Debug Console, Terminal.

Yes, I can reproduce what you did. I don't have any xkb mapping and can bind Ctrl+Alt+I to list.focusDown and it goes down the list. Using the shortcut troubleshooting console without xkb, the AltGr key gets detected as AltRight and it switches focus to the filter box when pressed in the problems panel together with any other key.
```
[2020-12-09 22:50:14.717] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: AltRight, keyCode: 225, key: AltGraph
[2020-12-09 22:50:14.717] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: AltRight, keyCode: 0 ('unknown')
[2020-12-09 22:50:14.717] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched. 
```

So **without** xkb:
Code: AltRight    keyCode: 225    key: AltGraph
Converted to      keyCode: 0 ('unknown')

**With** xkb:
Code: AltRight    keyCode: 223    key: ShiftLevel5
Converted to      keyCode: 91 ('OEM_8')

Regardless of whether I use dispatching on code or key code, the focus always switches to the filter box if I press the AltGr key together with another key.

**Comment by Mr-Pepe** [comment] 2021-02-28 12:31
The problem still persists and I had a look at it again. Please have a look at the following outputs.

When I press the arrow down key in the problems panel everything works as expected:
```
[2021-02-28 13:21:53.382] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: ArrowDown, keyCode: 40, key: ArrowDown
[2021-02-28 13:21:53.382] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: ArrowDown, keyCode: 18 ('DownArrow')
[2021-02-28 13:21:53.383] [renderer3] [info] [KeybindingService]: | Resolving DownArrow
[2021-02-28 13:21:53.383] [renderer3] [info] [KeybindingService]: \ From 12 keybinding entries, matched list.focusDown, when: listFocus && !inputFocus, source: built-in.
```

However, this is the output with my keybinding. DownArrow is still resolved, but it apparently doesn't match `listFocus && !inputFocus` anymore. Afterwards the process is on the filter box.
```
[2021-02-28 13:21:46.912] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: AltRight, keyCode: 223, key: ShiftLevel5
[2021-02-28 13:21:46.912] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: AltRight, keyCode: 91 ('OEM_8')
[2021-02-28 13:21:46.913] [renderer3] [info] [KeybindingService]: | Resolving OEM_8
[2021-02-28 13:21:46.913] [renderer3] [info] [KeybindingService]: \ No keybinding entries.
[2021-02-28 13:21:47.039] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: KeyK, keyCode: 40, key: ArrowDown
[2021-02-28 13:21:47.039] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: KeyK, keyCode: 18 ('DownArrow')
[2021-02-28 13:21:47.039] [renderer3] [info] [KeybindingService]: | Resolving DownArrow
[2021-02-28 13:21:47.039] [renderer3] [info] [KeybindingService]: \ From 12 keybinding entries, no when clauses matched the context.
```

If I only press AltGr by itself, nothing happens and the focus stays on the list. It looks like OEM_8 + any other key switches the focus to the filter box.

**Comment by Mr-Pepe** [comment] 2021-05-30 11:42
The issue is not solved.

**Closed** 2021-08-28 11:24 UTC
Labels: needs more info, keybindings, linux
