### ISSUE TITLE
Alt+letter file menu shortcuts no longer work in Linux

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33479] opened 2017-08-30 04:39 UTC
- VSCode Version: Code - Insiders 1.16.0-insider (b9ac10234f86f145fdbcf066758934e0857d7592, 2017-08-25T05:16:07.411Z)
- OS Version: Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.3
vscode-terminal-here|Tyr|0.0.5
vscode-svgviewer|css|1.4.2
tslint|eg2|0.17.0
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
vscode-rust|kal|0.4.2
vscode-scss|mrm|0.6.2
cpptools|ms-|0.12.3
seti-icons|qin|0.1.3

(3 theme extensions excluded)

---

Probably due to the Electron update.

**Comment by bpasero** [comment] 2017-08-30 04:44
@Tyriar when I press Alt I am getting a search box where I can search for the menu entry:

![image](https://user-images.githubusercontent.com/900690/29855772-b9e0b54a-8d4e-11e7-9b1d-68f6e876ea55.png)

Same for stable for me.

**Comment by Tyriar** [comment] 2017-08-30 04:45
@bpasero that's pressing, holding alt and pressing a key should trigger the menu

**Comment by Tyriar** [comment] 2017-08-30 04:46
Holding alt+F works in Chrome and vscode@1.15 but not in Insiders.

**Comment by Tyriar** [comment] 2017-08-30 04:48
Also, holding alt is meant to reveal the menu and underline the shortcuts. It reveals fine but doesn't show any underlines, which indicates to me that Electron is no longer telling the OS where the & is (or whatever format is normal on Linux).

**Comment by bpasero** [comment] 2017-08-30 04:59
Oh wow, I can reproduce. That is a pretty serious regression, no? At least we gotta check if this is Electron or not...

**Comment by Tyriar** [comment] 2017-08-30 05:10
@bpasero it sucks but I wouldn't consider it a blocker, but we should definitely report asap if it's not something we did on our end. It also might be fixed in later Electron versions?

**Comment by Tyriar** [comment] 2017-08-30 05:13
I checked via https://github.com/electron/electron-quick-start, it's broken in v1.7.3 and v1.7.6

**Comment by Tyriar** [comment] 2017-08-30 05:30
They actually work fine, the demo doesn't seem to have the accelerator keys working. It works just fine in 1.7.3 and 1.7.6 when I add this to main.js:

```js
const Menu = electron.Menu
const MenuItem = electron.MenuItem
var m = new Menu();
m.append(new MenuItem({ label: '&test' }));
Menu.setApplicationMenu(m)
```

---

I think this is something we did:

https://github.com/Microsoft/vscode/blob/2c0a55294b47d61b04840fcf00ab7bec5ba8f204/src/vs/base/common/labels.ts#L306

**Comment by Tyriar** [comment] 2017-08-30 05:33
It appears to be added in this commit: https://github.com/Microsoft/vscode/commit/a65b52fab8516fb120e28f6bcd0d55f2c328b339#diff-edff6c3b3b470a1a02e4743257a948dcR131

**Comment by bpasero** [comment] 2017-08-30 07:50
I pushed a fix that also has a nice benefit: dialog buttons are now keyboard accessible by Alt-click too. It looks like on Linux setting "_" into a button label enables mnemonics for them.

**Closed** 2017-08-30 07:49 UTC
Labels: bug, important, insiders, linux, menu

**Comment by Tyriar** [comment] 2017-08-30 13:48
Awesome! Thanks ☺️

**Comment by aeschli** [comment] 2017-09-01 13:13
Works on Joaos machine. On my parallels instance with Elementarty OS, I see the underlines but they quickly disapear again. Pressing a key opens the menu.
