### ISSUE TITLE
 the terminal does not work if there is a Russian in the file path

### ISSUE THREAD

**Issue by druidich** [Microsoft/vscode#9620] opened 2016-07-22 11:18 UTC
- VSCode Version:
1.3.1
- OS Version:
Windows 10 1511
Steps to Reproduce:

1. open the folder with the name of Russian
2. press '`'+'ctrl'
3. finishhim

**Comment by Tyriar** [comment] 2016-07-22 21:37
Duplicate of #7727

**Closed by Tyriar** 2016-07-22 21:37 UTC
Labels: integrated-terminal
