### ISSUE TITLE
${file} resolves to output window file

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode#108619] opened 2020-10-13 20:07 UTC
Issue Type: <b>Bug</b>

`${file}` is resolving to `extension-output-#5` instead of actual selected file.

This is due to our `resolveDebugConfiguration` function calling `vscode.window.createOutputChannel(...).show()` then it calls the prelaunchtask which references `${file}`.

We have a workaround to write to the output channel and not show it. 

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (40.87GB free)|
|Process Argv|--crash-reporter-id 89ad4c69-aa25-4a98-9f44-ef26e847bfb1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|Memory (System)|63.85GB (40.87GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.6.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.0
cpptools|ms-|1.0.1

</details>

**Comment by isidorn** [comment] 2020-10-20 15:41
I also find this a bit strange since the variable resolver calls the `editorService.activeEditor` [here](https://github.com/microsoft/vscode/blob/49d9c8c79b6fd9aaeeb5e869e37d93cfd0e7b703/src/vs/workbench/services/configurationResolver/browser/configurationResolverService.ts#L54) when resolving the `${file}`

So it might be the defintiion of the editorService that we allow activeEditor to point to the output.
@bpasero might know exactly
Forwarding to @alexr00 since she owns configuration resolving.

**Comment by bpasero** [comment] 2020-10-21 05:57
@isidorn the output channel can never be `editorService.activeEditor`, there must be other code that ends up using it. If you can reproduce that `editorService.activeEditor` returns an output channel, please file an `important` bug to me.

**Comment by alexr00** [comment] 2020-10-21 11:43
Duplicate of https://github.com/microsoft/vscode/issues/95423

@bpasero 
`ExtHostDocumentsAndEditors` will return non-code editors as the `activeEditor`. 
https://github.com/microsoft/vscode/blob/958a942f5ddd56b62e62f75777096276a547f779/src/vs/workbench/api/common/extHostDebugService.ts#L994-L1000

**Closed** 2020-10-21 11:43 UTC

**Comment by bpasero** [comment] 2020-10-21 13:28
Ah ok sorry, I thought this is about `IEditorService` in the workbench. I have no ownership of the ext-host equivalent, but it is a bit misleading that we call them the same.
