### ISSUE TITLE
Multiple Language

### ISSUE THREAD

**Issue by tiwarinitin94** [Microsoft/vscode#59692] opened 2018-09-30 09:04 UTC
Issue Type: <b>Bug</b>

when I am editing a .php page its only giving me hints related with php language, I should be able to select multiple language functions, For example I have a php page that contains HTML and JS as well. So I want to get hints with each language, aur auto complete things. 

I have uploaded an image its the right corner of the software where we select the file type that we are editing. And If I select PHP I get hints of PHP functions when I type, so I am suggesting its not a issue, but It will be better if I can select multiple language whichever language I am using for my page.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (1.06GB free)|
|Process Argv|C:\Users\NST\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by tiwarinitin94** [comment] 2018-09-30 09:06
No its not a similar extension, my code doesn't has that problem

**Comment by usernamehw** [comment] 2018-09-30 15:51
Duplicate of #1751 ?

**Comment by aeschli** [comment] 2018-10-02 08:30
duplicate of #670

@tiwarinitin94 Please try one of the PHP extensions: Intelephense and PHP:
- [PHP IntelliSense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) 
- [PHP Intelephence](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).

**Closed by aeschli** 2018-10-02 08:30 UTC
