### ISSUE TITLE
stupidly large files

### ISSUE THREAD

**Issue by Redtile** [microsoft/vscode#78394] opened 2019-08-02 16:45 UTC
OK, don't ask why but I need to open a 16GB file to do some editing to and cant find a program that will let me so I thought I would try vscode, it obviously didn't work which is why I'm here so I was wondering if it would be possible (after at least 3 years of it being mentioned in other posts) to it being added in, my computer currently has 48GB of ram so plenty to open it even if it needed double the file size in ram but even when I do give the software the ram I still get an error saying "cant open file is too large(16GB)" if this is unable to be added in (ideally soon) does anyone know of a program that would allow me to open a file this large in a way that I can mess with the code?
the file is a .VNEM and .VMDK file, most other files I have needed to open have done so

**Comment by gjsjohnmurray** [comment] 2019-08-02 16:55
Did you try increasing the `files.maxMemoryForLargeFilesMB` setting?

**Comment by Redtile** [comment] 2019-08-02 17:38
Thanks for the response, I have increased it to 24GB

**Comment by gjsjohnmurray** [comment] 2019-08-02 17:56
@Redtile do you mean you had already done that and you still can't open the file?

**Comment by Redtile** [comment] 2019-08-02 19:25
Yes I have done that already but I still get an error msg, I can upload a screen shot when I am back at my desk

**Comment by rebornix** [comment] 2019-10-21 21:33
Our implementation of text buffer doesn't come with no cost, it tries to store minimal information, like line break offsets in the buffer and references between chunks of raw data. For a relatively large amount of lines of data, the metadata stored in the text buffer can be large, sometimes even larger than the file itself. Currently we don't have a sound solution for making the text buffer slim for all cases.

**Comment by Redtile** [comment] 2019-10-21 21:39
Ok so for a vmdk file at 16GB approx how much memory do I need to dedicate to it? I have a top of the line custom built rig so in theory there shouldnt be an issue

**Comment by jorgegarciamule** [comment] 2019-10-24 12:31
Is it possible that I was able to open a big file with an older version and when I do that it says something like "we can't highlight sintax but at least I open it." and now it just crush? If that is true, what about a fallback mechanism?

**Comment by rebornix** [comment] 2019-10-24 17:17
> Is it possible that I was able to open a big file with an older version and when I do that it says something like "we can't highlight sintax but at least I open it." and now it just crush? If that is true, what about a fallback mechanism?

@jordanmkasla2009 if that's what you see "works in 1.38 but fails in 1.39" then it's a regression which we should fix. Can you help confirm that? We didn't remove what you described.

**Comment by jorgegarciamule** [comment] 2019-10-24 19:39
> > Is it possible that I was able to open a big file with an older version and when I do that it says something like "we can't highlight sintax but at least I open it." and now it just crush? If that is true, what about a fallback mechanism?
> 
> @jordanmkasla2009 if that's what you see "works in 1.38 but fails in 1.39" then it's a regression which we should fix. Can you help confirm that? We didn't remove what you described.

It looked to be just a wrong perception on my side. I tried with some old version and I see the same behavior as described in this issue. Is that buffer ref code centralized somewhere? Looks like they will need to go to disk also.

**Comment by rebornix** [comment] 2020-11-03 17:19
/duplicate of https://github.com/microsoft/vscode/issues/46723

**Closed** 2020-11-03 17:20 UTC
Labels: *duplicate, editor-textbuffer, feature-request
