### ISSUE TITLE
Regex replace fails on group operation.

### ISSUE THREAD

**Issue by paperant** [microsoft/vscode#40213] opened 2017-12-14 13:42 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|1.8.0
code-runner|for|0.8.5
python|ms-|0.8.0
java|red|0.15.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Use `Command + Alt` to call the replace window, enter your regex with group selection like `'(\d+)'` to find all numbers in the form of string.
2. In the `Replace` input box type as `\1` to replace the selected matches with the 1st group. For example, here we type `\1` to convert the matched strings to numbers.
3. Finally we can get strings like `'1'` replaced as `1`, but it turns out `\1`. 

Reproduces without extensions: Yes

**Comment by LenzGr** [comment] 2017-12-14 16:43
I too stumbled into a similar issue - seems like using a `\1` backreference to replace a string is not supported yet?

**Comment by paperant** [comment] 2017-12-15 06:16
@LenzGr Yes. Seems regex is not supported perfectly in current version. 
By the way, Sublime Text works well in my case. Maybe that's why I have to keep both on my machine~

**Comment by LenzGr** [comment] 2017-12-15 08:12
@paperant I had to resort to using gvim for that bulk regex-based search and replace. Unfortunately there is little documentation about the regex capabilities of the search/replace tool.

**Comment by Simran-B** [comment] 2017-12-22 10:34
Isn't the placeholder for the first capture group `$1`?

This is JavaScript RegExp, it does not support `\1` to my best knowledge.

**Comment by paperant** [comment] 2017-12-22 10:56
@Simran-B `$` works! Thanks bro. 
By the way, does it mean that RegExp in VS Code works under the **JavaScript** style due to `Electron`?

**Comment by LenzGr** [comment] 2017-12-22 11:02
Good to know that VS Code expects JavaScript-Style Regular Expressions...

Ist that documented somewhere? If not, this would be a nice addition to the documentation...

**Comment by Simran-B** [comment] 2017-12-22 11:35
Honestly, I can't find any documentation for the Find widget... That's really odd.

The only thing I found is about advanced search:
https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

But yes, Electron is based on V8, which is a JavaScript engine and VS Code uses its regular expression implementation.

**Comment by nhoizey** [comment] 2018-11-08 13:45
`$1` doesn't work for me in VS Code 1.28.2 on macOS Mojave:

![image](https://user-images.githubusercontent.com/78213/48202336-df74ab00-e364-11e8-8e03-231866a5abdb.png)

I see this issue is 11 months old and still open.

Is there anything planned to make groups work in search/replace?

**Comment by Simran-B** [comment] 2018-11-08 18:00
@nhoizey Something is strange about your search phrase.

To make it work in the Find widget (Ctrl+F), I had to change it to `(tags:\s*\[[^]*)Paris Web`. 

My test text:

```
tags:    [Paris Web Something, RWD]
tags:    [Paris Web, company]
tags:    [qualité, em, Paris Web]
```

Replace all works fine using `$1parisweb`:

```
tags:    [parisweb Something, RWD]
tags:    [parisweb, company]
tags:    [qualité, em, parisweb]
```

If I try the same search and replace phrases in the search panel however, I get an "Error: unclosed character class". In your screenshot, I can see that you placed an unescaped closing square bracket after the character class to match all characters (`[^]`), which makes the error go away for me, but then it won't find matches for me (Windows 10, VS Code 1.28.2). The error shows if I escape the second closing bracket as well, which made me think that escaped opening square brackets might be broken.

However, I then replace the `[^]` by `[\s\S]` which is equivalent, and it works: `(tags:\s*\[[\s\S]*)Paris Web`

![image](https://user-images.githubusercontent.com/7819991/48217744-7c950b00-e388-11e8-8a36-2f5e5a432a7d.png)

Can you try this search expression? If it still does not work, then it appears to be related to your OS, which would be rather strange though.

**Comment by nhoizey** [comment] 2018-11-08 22:11
@Simran-B thanks for taking time to search for an answer!

Your suggestion `(tags:\s*\[[\s\S]*)Paris Web` seems to work indeed.

But after reading my search string once again, I saw that I should have escaped the first closing square bracket: `(tags:\s*\[[^\]]*)Paris Web`, because I want any character but the closing square bracket. This works.

But your version would also find `tags:  [twitter] Paris Web` (`Paris Web` is after the closing square bracket), which I don't want.

It looks however there is an issue: my first search regex without closing square bracket escaping found relevant strings, as the screenshot showed, but `$1` was not replaced with the group value it matched.

**Comment by Simran-B** [comment] 2018-11-12 12:30
@nhoizey Ah, now I understand your regular expression. `[^]` wasn't meant as match-all, but match everything but a literal `]`. It works here with your fixed phrase:

![image](https://user-images.githubusercontent.com/7819991/48347484-a7c87480-e67e-11e8-9e89-8708d960b72a.png)

If your initial phrase is the only one which leads to `$1` not being substituted with the first matched group, then it's a side-effect of an unsupported search expression perhaps? But yeah, still worth to report as separate bug, because if it's actually not supported (using `[^]` as short hand for `[\s\S]`) then I would expect to see an error. Something is definitely off with the search panel, whereas the find widget behaves as expected.

**Comment by Simran-B** [comment] 2018-11-16 12:01
@nhoizey I was able to reproduce a problem and reported it here: #63297. It tries to substitute `$1` literally although there is a capture group with value `array`, but it changes to the expected value as soon as you open the Replace Preview. Maybe you saw some similar behavior?

Another related issue, but said to be fixed: #58374

**Comment by nhoizey** [comment] 2019-04-24 09:00
Hi @Simran-B, sorry for the very late answer. It looks like I don't have issues anymore.

**Comment by rebornix** [comment] 2019-10-23 21:55
The Find Widget input box honors JavaScript regex engine, closing it as the issue here is no longer valid.

**Closed by rebornix** 2019-10-23 21:55 UTC
Labels: editor-find, feature-request

**Comment by Simran-B** [comment] 2019-10-24 09:43
@rebornix I disagree.
- The documentation does not mention the _Find Widget_ in [GET STARTED > User Interface](https://code.visualstudio.com/docs/getstarted/userinterface)
- Instead, it is mentioned under [USER GUIDE > Basic Editing # Find and Replace](https://code.visualstudio.com/docs/editor/codebasics#_find-and-replace), but it only lists _Regular Expression_ as option under _Advanced find and replace options_, not saying anything about JavaScript regex engine being used nor providing an example
- If you are lucky, you might find the well hidden [GET STARTED > Tips and Tricks # Search and Modify](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_search-and-modify) paragraph under the _IntelliSense_ headline, which briefly mentions that you can use parentheses and `$1` etc. to reuse the content matched. But it also fails to mention that the JS regex engine is used.

IMO, the _Search and Modify_ paragraph should be removed and the content added to _USER GUIDE > Basic Editing # Find and Replace_ instead, plus a sentence added about the regex engine being used.
