### ISSUE TITLE
Trying to open a folder from the GUI crashes vscode version 1.94.0.

### ISSUE THREAD

**Issue by jdavidagudelo** [microsoft/vscode#230477] opened 2024-10-04 11:02 UTC
Does this issue occur when all extensions are disabled?: YES

- VS Code Version: 1.94.0
d78a74bcdfad14d5d3b1b782f87255d802b57511
x64
- OS Version: Lubuntu.

Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

Steps to Reproduce:

1. Open vscode GUI. 
2. Go to File -> Open Folder ...
3. Select any folder making click on it and all vscode windows previously opened crash without any warning.

Another way to reproduce it:

1. Open vscode GUI
2. Go to File -> New Window
3. Go to File -> Open Folder in any of the windows and vscode crashes.

**Comment by gjsjohnmurray** [comment] 2024-10-04 12:10
Looks like a duplicate of #230454

**Comment by deepak1556** [comment] 2024-10-04 17:15
Merging to https://github.com/microsoft/vscode/issues/230454

Please follow-up in that issue.

**Closed by deepak1556** 2024-10-04 17:15 UTC
Labels: freeze-slow-crash-leak, new release
