### ISSUE TITLE
editor.smoothScrolling breaks find jump

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#173487] opened 2023-02-05 20:18 UTC
Type: <b>Bug</b>

With `editor.smoothScrolling` enabled if I use find widget inside editor it doesn't jump straight to the first match, it only scrolls a little bit, but if I press <kbd>Enter</kbd> again it jumps as expected to the second match and reveals text. Even though I see cursor moved it scrolled just a bit down. If I disable `editor.smoothScrolling` everything works fine as before. I feel like this is a regression and started to happen after 1.72 or 1.73.

As you can see from the gif it scrolls, but not enough, because `foo` is still invisible and if I hit <kbd>Enter</kbd> again it scrolled to the second match which revealed text I was looking for. And, if you take a look into scrollbar you will see that my cursor position was moved to the 1 match.

![Recording 2023-02-05 at 22 23 26](https://user-images.githubusercontent.com/10441177/216842934-13123fb9-9ed5-4aa5-b024-1f4fe993e10e.gif)

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:26:31.005Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 6, 6|
|Memory (System)|32.00GB (0.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
copilot|Git|1.71.8269
vscode-graphql|Gra|0.8.5
vscode-graphql-syntax|Gra|1.0.6
fluent-icons|mig|0.0.18
symbols|mig|0.0.9
vscode-react-native|msj|1.10.0
color-highlight|nau|2.5.0
vscode-thunder-client|ran|2.3.4
vscode-fileutils|sle|3.10.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.30
vim|vsc|1.24.3
quokka-vscode|Wal|1.0.524

(1 theme extensions excluded)

</details>

**Comment by hediet** [comment] 2023-02-07 09:55
I also noticed this. @alexdima is this related to the scrolling speed adjustment you worked on?

**Comment by drbr** [comment] 2023-02-17 21:23
I've been noticing this too — so far I've never experienced it with smooth scrolling disabled.

I usually use the Vim extension (it looks like the OP might be too), but I've seen the issue even with the Vim extension disabled.

**Comment by svipas** [comment] 2023-02-19 11:16
@alexdima I tracked it down, seems like it's because of Vim extension (`vscodevim.vim`).

**Comment by axefrog** [comment] 2023-02-20 00:03
This also occurs horizontally, to an even greater degree than it does vertically. If I hit HOME or END on my keyboard, I typically have to repeat this 4-5 times before it actually scrolls the view to where it should have scrolled in the first place.

**Comment by axefrog** [comment] 2023-02-20 19:07
@alexdima I'm not even using vim and it's happening for me. I think you closed this prematurely.

**Comment by alexdima** [comment] 2023-02-20 20:06
@axefrog Sorry about that, I didn't realize from your comment that you're not using vim. Could you please share steps to reproduce?

**Comment by bogdan-d** [comment] 2023-02-21 11:51
I also have this issue and I'm not using vim. The issue doesn't seem to reproduce with extensions disabled, but I haven't tracked the responsible extension(s) yet.

**Comment by FSDRE** [comment] 2023-02-23 15:54
@alexdima I can confirm this issue without having enabled ANY extensions or smoothScrolling enabled.

My reproduction would be:

1. Start VSCode with default settings, no extensions, no smoothScrolling
2. `npm install monaco-editor`
3. Open up `monaco.d.ts` (huge file)
4. Place cursor somewhere in the first 100 lines
5. `CTRL + F`
6. Type `storage` (should find one result)

=> Scrolls down a little bit but not where the word actually is

If you repeatedly hit `Enter` in the find field it scrolls down a little bit more every time until it finally reaches the word. This is some super odd behavior 😄

**Comment by FSDRE** [comment] 2023-02-23 18:02
@alexdima Huh... this is a weird issue. I am going to double-check tomorrow. But also #171026 is completely weird with having two instances of VSC running different scroll speeds with the same settings. This makes no sense at all.

**Comment by FSDRE** [comment] 2023-02-23 19:20
@alexdima I did this on two fresh 1.75.1 user installations. On one machine locally and on the other machine connected via the Microsoft Remote Desktop App from the Windows Store.

Here's are the steps:

1. Open freshly installed VSC
2. `Open Folder` -> Create new one -> Select it
3. `npm init` -> hit `Enter` until done
4. `npm install monaco-editor --save`
5. Open `monaco.d.ts`
6. `CTRL + F` -> type storage -> works fine!
7. Go to File -> Preferences -> Workspace -> show `settings.json`
8. Add `"editor.smoothScrolling": true`
9. Go back to `monaco.d.ts`
10. Scroll back up and place cursor somewhere
11. 6. `CTRL + F` -> type storage

=> On the local machine this works flawlessly, on the machine connected via remote desktop the scrolling is all over the place!

I cannot think about anything other that is different between the two machines. Unfortunately I cannot connect to my local machine via remote desktop in order to double check.

So maybe this is all trash because I missed something or it is actually a good hint towards the solution, I don't know.

What's about the rest here? Are you using remote desktop or are you working locally?

**Comment by FSDRE** [comment] 2023-02-23 19:28
And to be clear: In my first reproduction attempt I mistakenly copied the hidden folder .vscode with the workspace settings over and it had smooth scrolling enabled. Just that you know, why it also failed.

**Comment by alexdima** [comment] 2023-02-24 21:27
@FSDRE Thank you for the extra details. Unfortunately, I still cannot reproduce in a vanilla VS Code without any extensions and without any user settings except `editor.smoothScrolling: true`:


https://user-images.githubusercontent.com/5047891/221296328-1bea11b7-6953-461d-a451-2fba90d1b9e3.mp4

**Comment by FSDRE** [comment] 2023-02-27 10:28
@alexdima What I cannot see in your clip is if you are trying this in remote desktop. Again, locally it works perfectly. I only have the issue when working with VSC in a remote desktop environment.

**Comment by bogdan-d** [comment] 2023-02-27 11:29
Ok, I don't use remote desktop. I have this problem on my local vscode installation. I managed to reproduce the steps provided by @FSDRE in a Windows Sandbox with a fresh code install:

https://user-images.githubusercontent.com/4302588/221552287-10b55c23-7387-4f22-aecf-fe37593cb678.mp4

This is my code environment:

Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Closed** 2023-04-06 16:35 UTC
Labels: info-needed
