### ISSUE TITLE
Output window does not respect codepage

### ISSUE THREAD

**Issue by vsobotka** [Microsoft/vscode#21971] opened 2017-03-04 10:10 UTC
- VSCode Version: 1.10.1 (653f8733)
- OS Version: Windows 10 Pro (10.0.14393)
- User settings
```
{
    "files.encoding": "cp852",
    "editor.minimap.enabled": true,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"
}
```

Steps to Reproduce:

1. Have file `errors.log` written in `CP 852`
```
Dočasná tabulka (TEMP TABLE) ttSumaStavu nebyla nalezena. (5445)
** .\a_s\r_prefak.p Nemohu porozumět řádku 23. (196)
```
2. Configure task
```
{
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": ["/C"],

    "tasks": [
        {
            "taskName": "Check codepage",
            "suppressTaskName": true,
            "isBuildCommand": false,
            "args": ["chcp && type errors.log"]
        }
    ]
}
```
3. Run the task
![obrazek](https://cloud.githubusercontent.com/assets/4008662/23577857/3a2118b0-00ca-11e7-9378-2bfcf74f4992.png)
4. Run the command `chcp && type errors.log` manually in terminal window
![obrazek](https://cloud.githubusercontent.com/assets/4008662/23577882/755f4b22-00ca-11e7-8b89-ca51623e7c7e.png)

**Comment by isidorn** [comment] 2017-03-06 14:36
Duplicate of https://github.com/Microsoft/vscode/issues/3550

**Closed by isidorn** 2017-03-06 14:36 UTC
Labels: feature-request
