### ISSUE TITLE
Add filtering option on warnings and errors in Problems Output tab

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [Microsoft/vscode#29272] opened 2017-06-22 15:42 UTC
Similar to Unity engine console logger..

While we may be able to filter by problems we are not able to filter by errors or warnings instead I am presented with huge list and have to scroll through it! I would like to have option to quickly hide and unhide warnings instead seeing them all in list.. As well as having option to hide and unhide specific errors... Thank you!

**Comment by KillyMXI** [comment] 2017-07-15 10:22
Currently, it's possible to filter by "info", "warn", "error" strings - it works fine.
The problem is, it's not quite intuitive. I discovered it just now from the issue #8305
Providing input suggestions to input string would improve the discoverability of the feature.

VisualStudio-style toggles by type is what people most likely expect to see in Problems window.

**Comment by kmolerov** [comment] 2017-07-24 07:51
There should be an additional dropdown for filter based on type, next to the filter textbox. It would be more convenient.

**Comment by KillyMXI** [comment] 2017-07-26 12:00
Toggle buttons for every level (VisualStudio-style) seems more convenient to me, since it allows for "show everything except info" behaviour.
The only thing I'm not sure about is the possible UI clutter with more controls. But additional dropdown will take as much space.

One possible approach to avoid cluttering UI with controls and provide more flexibility at the same time:
Everything still has to be done in filter box, but dropdown with some helpers has to be added to it, that will help to construct queries - include and exclude stuff. Something that will allow to select levels, sources (plugins), strings (may be prefilled with frequent words from existing problems) and has two buttons - "include" and "exclude".
List of frequent queries would also be helpful.

**Comment by liamstask** [comment] 2017-11-23 22:15
also, typing `error` into the box to filter for errors doesn't work as expected - problems of type error remain, but problems of type info (the ones with the blue `i`) also remain, if their text contains the word 'error'.

**Comment by sandy081** [comment] 2017-11-27 13:45
Duplicate of #8305

**Closed** 2017-11-27 13:45 UTC
Labels: *duplicate, error-list, feature-request, ux
