### ISSUE TITLE
Markdown: Dragging multiple images does not work

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#164813] opened 2022-10-27 15:04 UTC
It justs concatenates the paths:

![Code_-_Insiders_OiUZhU9M3J](https://user-images.githubusercontent.com/2931520/198326472-dfbbc0e4-a744-4972-bb72-812c71dab7e0.gif)

**Comment by mjbvz** [comment] 2022-10-27 16:23
Duplicate of #156371

**Closed by mjbvz** 2022-10-27 16:23 UTC
