### ISSUE TITLE
use ctrl+click(mouse left click) jump to definition

### ISSUE THREAD

**Issue by Jamesmahaitao** [microsoft/vscode#136456] opened 2021-11-04 17:23 UTC
System: MacOS 11.4(Apple Silicon)
VSCode Version: 1.61.2

i want press ctrl+click(mouse left click) to jump to definition,how can i do?

i tried the following:

press start+click can jump to definition when i add "editor.multiCursorModifier":"ctrlCmd" to settings.json

press alt+click can jump to definition when i add "editor.multiCursorModifier": "alt" to settings.json

modify keybindings.json as flowing.

{
    "key": "f12",
    "command": "-editor.action.goToDeclaration",
    "when": "editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor"
},
{
    "key": "ctrl+enter",
    "command": "editor.action.goToDeclaration",
    "when": "editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor"
}

all above doesn't work.
what should i do?

**Comment by bl-ue** [comment] 2021-11-04 17:27
Literal duplicate of #136456

**Closed** 2021-11-04 17:38 UTC
