### ISSUE TITLE
Recent update of INSIDERS Edition made COG Wheel completely disappear

### ISSUE THREAD

**Issue by RobFosterNYC** [Microsoft/vscode#71585] opened 2019-04-02 07:32 UTC
Using the VS Code INSIDERS Edtion v1.33

For some reason the COG Wheel has now disappeared and I cant access it.
.
![Screenshot_28](https://user-images.githubusercontent.com/18384135/55383959-6df5ee80-54f7-11e9-93bc-4f6b3deacae9.png)

If there are more mods than the bar could hold, there used to be a ( ... )
that would allow the user to click on to see the rest of the list of the mods installed as well as the user was always able to see the COG wheel as it never used to go away.
Now its just gone in recent updates for some reason.

Like so,
.
![Screenshot_29](https://user-images.githubusercontent.com/18384135/55384087-c0370f80-54f7-11e9-8753-60052270de65.png)

.
Please fix  thanks  :D

**Comment by isidorn** [comment] 2019-04-03 08:48
This is a regression from stable. And I can reproduce.
Doing some bisection this commit has caused the issue https://github.com/Microsoft/vscode/commit/21afd814cd6bac6e7b3d21161df34d4bafd9f3c8
Thus forwarding this to @RMacfarlane and @sandy081 

However imho should not be a candidate (even though it can happen that a user has many extensions installed that clog up the activity bar and that the COG wheel does not get shown making the user miss the update)

**Comment by RobFosterNYC** [comment] 2019-04-05 11:17
@isidorn @sandy081 @bpasero @mjbvz 
.
You guys closed this issue.
And now with the recent update of VS Code that just happened.
My COG wheel is completely gone on the stable release of VS Code 
Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
.
You guys might want to reopen this case as its now affecting the stable release.
as shown in this picture.
.
![Screenshot_75](https://user-images.githubusercontent.com/18384135/55623991-93daf780-5772-11e9-9c71-8b3289571fe1.png)

**Comment by isidorn** [comment] 2019-04-05 12:28
It is fixed in insiders. And the fix will be available in the next stable release in may.
So you should use insiders if you need the fix badly or be patient. Cheers

**Comment by bpasero** [comment] 2019-04-05 13:31
@sandy081 @isidorn why not make this a candidate for recovery release?

**Comment by isidorn** [comment] 2019-04-05 13:39
@bpasero fine by me. however I do not think it is that major (I commented about this in the first comment)
I leave this up to @sandy081

**Comment by sandy081** [comment] 2019-04-08 08:17
Since this is a regression I will tag this as a candidate and bring it up for discussion.

**Comment by konradw86** [comment] 2019-04-08 09:00
wt., 2.04.2019, 09:33 użytkownik RobFosterNYC <notifications@github.com>
napisał:

**Closed** 2019-04-09 14:20 UTC
Labels: bug, candidate, workbench-layout

**Comment by isidorn** [comment] 2019-04-10 09:22
Works great, verified with stable build 2f7c3971e1
