### ISSUE TITLE
no extension found

### ISSUE THREAD

**Issue by SuryaSg** [Microsoft/vscode#57671] opened 2018-08-31 08:56 UTC
Issue Type: <b>Bug</b>

no extension found error while selecting Extensions (Ctrl + Shift + X)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.50GB free)|
|Process Argv|C:\Users\surv2e12620\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.7.1
atom-keybindings|ms-|3.0.4
vscode-yaml|red|0.0.14
python|tht|0.2.3

</details>

**Comment by SuryaSg** [comment] 2018-08-31 08:59
Its not helping, no extensions found in marketplace. Kindly assist

**Comment by SuryaSg** [comment] 2018-08-31 09:03
All the above extensions are installed by Copy/pasting from my previous workstation. But no extensions shown from marketplace.

**Comment by oneslash** [comment] 2018-08-31 10:34
same here with `@sort:installs category:languages`

<img width="319" alt="screen shot 2018-08-31 at 12 34 07" src="https://user-images.githubusercontent.com/15870134/44908009-413be780-ad1a-11e8-986b-f0121dd5d66b.png">

**Comment by sandy081** [comment] 2018-08-31 15:06
@oneslash I think you are seeing a different issue and is fixed - https://github.com/Microsoft/vscode/issues/57160

@SuryaSg I suppose you are seeing no extension when you query in market place? Can you provide a screenshot of extensions view like above?

**Comment by SuryaSg** [comment] 2018-09-03 10:42
PFB, SS of the same.
![vserror](https://user-images.githubusercontent.com/10097003/44982618-1fe63000-af94-11e8-9187-fc18a6ea38fd.PNG)

**Comment by SuryaSg** [comment] 2018-09-03 10:48
Please resolve as your reference to the fixed ID - #57160 is not my case.
Kindly do the needful.

**Comment by sandy081** [comment] 2018-09-03 14:04
@ramya-rao-a Forwarding to you

**Comment by lawrencegripper** [comment] 2018-09-04 10:16
Hi, I'm also seeing this behavior on Ubuntu 18. 
 
It looks like the marketplace site is down at the moment. If I go there in the browser I see 

```

Sorry! Our services aren't available right now.

We're working to restore all services as quickly as possible. Please check back soon.
Ref A: 3ABE8683FE934BE185D69871AC237669 Ref B: LON21EDGE0905 Ref C: 2018-09-04T10:13:13Z 
```

I'd classify the behavior as a bug in VSCode as it causes quite a bit of confusion, I've spent a while upgrading downgrading a tweaking before I realized it was a API outage.  

I would expect VSCode to also show a warning explaining the outage as current behavior is misleading.

**Comment by GiuseppeDiPalma** [comment] 2018-09-04 12:12
![cattura](https://user-images.githubusercontent.com/11930075/45030535-77e06d80-b04c-11e8-914c-9ce9ede0603a.PNG)

I think is same problem. 
I stay on windows 10 with vscode ultimate version.

But i think that this is problem for all user.

**Comment by shurikdima** [comment] 2018-09-04 12:33
same over here using macOS, high sierra 10.3.2

**Comment by minotaurrr** [comment] 2018-09-04 12:37
same issue on macOS high sierra 10.13.5

**Comment by pedroapfilho** [comment] 2018-09-04 13:05
same here macOS high sierra 10.13.6

**Comment by plrang** [comment] 2018-09-04 13:07
Same here, win 10. Extensions: 'check for updates' returns 503

**Comment by pedroapfilho** [comment] 2018-09-04 13:07
But the site is down too: https://marketplace.visualstudio.com/vscode

**Comment by GiuseppeDiPalma** [comment] 2018-09-04 13:26
Ok I think that stay in updating

**Comment by rahulkp220** [comment] 2018-09-04 13:51
Facing the same here!

**Comment by liyi193328** [comment] 2018-09-04 13:55
same questions

**Comment by terry90** [comment] 2018-09-04 14:17
Same here

**Comment by doKill** [comment] 2018-09-04 14:31
no wonder i met same problem，official out tell us reason

**Comment by kongchenglc** [comment] 2018-09-04 14:41
same here macOS high sierra 10.13.6

**Comment by rahulkp220** [comment] 2018-09-04 15:29
@pedroapfilho you are right! `vscode` tries to connect to Azure in the backend and there is problems there. Have a read here guys!

https://www.zdnet.com/article/microsoft-south-central-u-s-datacenter-outage-takes-down-a-number-of-cloud-services/

**Comment by umairqazi523** [comment] 2018-09-04 17:15
Same problem.

**Comment by Stjepan930820** [comment] 2018-09-04 18:27
same problem on Ubuntu 18.04

**Comment by rahulsoibam** [comment] 2018-09-04 18:32
I've been uninstalling and reinstalling for hours now. Tried compiling from source, downloading the prebuilt package and using brew cask. I thought I broke it by updating.

Would appreciate it if an official announcement is made is to when it will be up again.

**Comment by rahulkp220** [comment] 2018-09-04 18:41
@rahulsoibam VSTS is down, there is nothing vscode can do. the service that it needs to allow showing up extensions is out. Check this https://marketplace.visualstudio.com/vscode

**Comment by pedroapfilho** [comment] 2018-09-04 20:35
https://azure.microsoft.com/en-us/status/

**Comment by default081** [comment] 2018-09-04 20:57
Same problem on Debian 9

**Comment by mjbvz** [comment] 2018-09-04 23:26
Duplicate of #57851

**Closed by mjbvz** 2018-09-04 23:26 UTC
Labels: extensions, needs more info

**Comment by Emil-Valentin-Toma** [comment] 2018-09-05 03:48
Marketplace still down, no recommended extensions to show just yet.

![image](https://user-images.githubusercontent.com/25068526/45069888-a7cc5700-b0c6-11e8-9ab4-0cadaae4fb30.png)
