### ISSUE TITLE
API: view management API for non-TextEditors

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#14483] opened 2016-10-25 19:11 UTC
Request: API support for managing non-`TextEditor` views. The functionality should support:
- show()
- hide()/close()
- move tabs/groups
- on-closed event (#12114, #13623)
- on-focus-changed event (via `onDidChangeActiveTextEditor` or new `onDidChangeActiveView`)
- presence in `visibleTextEditors` or new `visibleViews` (#6941)

In particular, `previewHtml` should return an object that provides the above functionality,

_Example use case:_ I create a preview for each open document of a certain file type. (The preview is derived from the current state of processing the document; not its contents.) Typically, the documents are all on the left column and their previews are on the right. When interacting with the document, its associated preview should become visible (without receiving focus); moving to a different column than the document itself if necessary. Without this kind of functionality, it easy for the user of my extension to become lost and confused when interacting with multiple documents.

**Comment by bpasero** [comment] 2016-10-26 04:41
@jrieken fyi

**Comment by jrieken** [comment] 2016-10-26 07:49
We have a dup for that but I am not finding it right now

**Comment by siegebell** [comment] 2016-10-26 14:02
@jrieken I've seen a couple related issues, but none that request a comprehensive API for managing views.

I'll also amend this request to include views of any `TextDocumentContentProvider`. (Related: #10379)

**Comment by mjbvz** [comment] 2017-03-24 00:51
I have a few markdown extension feature requests / bugs that all depend on this functionality, namely #8581

**Comment by StephenWeatherford** [comment] 2017-11-16 01:55
We've got data associated with each opened HTML view, which could be very large.  So we'd like to know when the tab is closed (not just deactivated) so we can dispose of it.

**Comment by jrieken** [comment] 2017-11-16 08:57
closing as dupe of #15178

**Closed by jrieken** 2017-11-16 08:57 UTC
Labels: api, feature-request
