### ISSUE TITLE
Markdown preview pane has wrong size unless text-size is 100%. Wasted space or cut-off text.

### ISSUE THREAD

**Issue by flexiblefactory** [Microsoft/vscode#20067] opened 2017-02-06 18:07 UTC
- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Change text-size to above 100% (ctrl +). 

2. View a markdown file in preview mode or eg. an extension readme page. Scroll pane is too small. Wasted space. Bad layout. (see pic)

3.  Change text-size to below 100% (ctrl -). Scroll pane is too large. Text is cut off. Bad layout.

![image](https://cloud.githubusercontent.com/assets/1742880/22659662/5e5243dc-ec96-11e6-8034-169926389a38.png)

**Comment by mjbvz** [comment] 2017-02-06 18:28
Closing as duplicate of #5745

**Closed by mjbvz** 2017-02-06 18:28 UTC
Labels: duplicate, webview
