### ISSUE TITLE
No extensions come up

### ISSUE THREAD

**Issue by ptdave20** [Microsoft/vscode#57923] opened 2018-09-05 01:55 UTC
Issue Type: <b>Bug</b>

Fresh install, search for extensions. none show.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G (4 x 3692)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (9.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alonesuperman** [comment] 2018-09-05 02:02
same question
----
Version: 1.26.1
Submitted: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by programkode** [comment] 2018-09-05 02:11
The whole Marketplace seems to be down: https://marketplace.visualstudio.com/

**Comment by mjbvz** [comment] 2018-09-05 02:37
Duplicate of #57851

**Closed by mjbvz** 2018-09-05 02:37 UTC
