### ISSUE TITLE
New update code colors bug (seems)

### ISSUE THREAD

**Issue by tomasalles** [microsoft/vscode#92526] opened 2020-03-11 22:31 UTC
Hello, my VSCode updated today and apparently some of the code colors changed, is this the expected behaviour or bug? Sure seems like a bug.

the console in console.log in javascript used to be green and is now blue as in like a variable name.

As soon as I open a file it is green for an instant and after some miliseconds it turns blue, which leads me to believe it is a bug of sorts.
Seen odd behaviour with colors in other instances.

Check this print screen:  https://imgur.com/GLzvJuQ

Can someone help?

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.8-arch1-1

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-03-11 22:34
/duplicate of #90379

As a workaround you could disable semantic highlighting.

**Closed by gjsjohnmurray** 2020-03-11 22:34 UTC
Labels: *duplicate

**Comment by tomasalles** [comment] 2020-03-11 22:40
> /duplicate of #90379
> 
> As a workaround you could disable semantic highlighting.

@gjsjohnmurray TYVM sir
