### ISSUE TITLE
Terminal skips layout when restoring from tmux

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#71078] opened 2019-03-25 13:59 UTC
I've had this issue for a while, just never created a ticket for it...

Very often, yet not always, when I reload my workbench, the terminal fails to relayout my [tmux setup](https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41). I need to resize the terminal using the sash. Hiding and showing the terminal doesn't help. It's as if a layout call is missed somewhere.

![Peek 2019-03-25 14-58](https://user-images.githubusercontent.com/22350/54925406-87eb6c00-4f0e-11e9-86db-e1e252e43e52.gif)

**Comment by Daniel-McCarthy** [comment] 2019-04-19 03:49
I have peeked at this a bit and started by setting up tmux with two panels as mentioned in the original post. I was able to reproduce this issue as well, however my experience was that when this occurred I was able to consistently make this occur repeatedly by closing the terminal with the X, then going to `Terminal > New Terminal`, where as reloading allowed it to display properly.

Each time I reproduced this issue successfully I also got this error:
```
ERR ioctl(2) failed.: Error: ioctl(2) failed. 

at UnixTerminal.resize (/home/user/Documents/vscode/node_modules/node-pty/lib/unixTerminal.js:216:13)

at TerminalProcess.resize (file:///home/user/Documents/vscode/out/vs/workbench/contrib/terminal/node/terminalProcess.js:152:30) 

at TerminalProcessManager.setDimensions (file:///home/user/Documents/vscode/out/vs/workbench/contrib/terminal/browser/terminalProcessManager.js:186:31) 

at _processManager.ptyProcessReady.then (file:///home/user/Documents/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1076:86)
```

In case this helps in finding the issue, I have shared this here as I am not yet sure how to resolve it.

**Comment by Tyriar** [comment] 2019-05-01 21:28
Thanks @Daniel-McCarthy, that's helpful and makes sense. There's a full stack trace in https://github.com/Microsoft/vscode/issues/57976, I'm closing that one off in favor of this.

**Comment by Tyriar** [comment] 2019-05-01 21:31
Upstream issue: https://github.com/Microsoft/node-pty/issues/220

**Comment by Tyriar** [comment] 2019-05-10 23:03
The ioctl exception will give more detail on how it failed when https://github.com/microsoft/vscode/pull/73597 is merged.

**Comment by Tyriar** [comment] 2019-05-13 18:44
I looked into this and could repro without the ioctl errors. It really seems like an issue in tmux because the pty is initialized to the correct size, then another resize call is triggered with the same correct size, but tmux still renders wrong. Also strangely telling tmux to relayout fixes it (ctrl+b, r) which indicates to me the issue is in tmux.

**Closed by Tyriar** 2019-05-13 18:44 UTC
Labels: bug, help wanted, integrated-terminal, upstream
