### ISSUE TITLE
Very Buggy After Latest Release

### ISSUE THREAD

**Issue by Rakeda** [microsoft/vscode#84190] opened 2019-11-08 02:53 UTC
Issue Type: <b>Performance Issue</b>

Ever since i've updated to the latest version my visual studio code is buddy and cancels my extensions every 5 minutes.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    83	 10580	code main
    0	    14	  5480	   electron-crash-reporter
    0	   105	 16160	   gpu-process
    0	   252	 18344	   window (App.js - walk - Visual Studio Code)
    0	   111	  2604	     extensionHost
    0	   204	 24932	       electron_node tsserver.js 
    0	    45	 28272	         electron_node typingsInstaller.js typesMap.js 
    0	    27	 25336	       electron_node eslintServer.js 
    0	    56	 26308	       electron_node server.js 
    0	    52	 27820	       electron_node tsserver.js 
    0	    11	  5660	     watcherService 
    0	    11	  9772	       console-window-host (Windows internal process)
    0	    34	 23608	     searchService
    1	    68	 21848	   window (Issue Reporter)
    0	    71	 25252	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (App.js - walk - Visual Studio Code)
|    Folder (walk): 20 files
|      File types: json(6) js(2) png(2) DS_Store(1) gitignore(1) log(1)
|                  lock(1)
|      Conf files: package.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.31.2
vscode-eslint|dba|1.9.1
es7-react-js-snippets|dsz|2.4.4
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
ftp-simple|hum|0.7.5
search-node-modules|jas|1.3.0
sftp|lix|1.12.9
vscode-language-babel|mgm|0.0.25
remote-containers|ms-|0.83.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.2
vscode-remote-extensionpack|ms-|0.17.0
vscode-react-native|msj|0.13.0
color-highlight|nau|2.3.0
java|red|0.52.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.7.20
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
gitblame|wad|3.0.1
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0

</details>

**Comment by alexandrudima** [comment] 2019-11-08 08:19
@Rakeda I'm sorry, I don't understand, what do you mean? In what way is VS Code very buggy? Can you please write detailed steps with what you do and what happens?

**Comment by Avivhdr** [comment] 2019-11-08 21:06
Hi, I also experience it.
After loading vs code, and using the F2 option (rename), it worked and renamed the variable, but also  gave me the following error message:
![image](https://user-images.githubusercontent.com/23265867/68510282-c2c2ca00-027b-11ea-8c63-56bfcf73b327.png)

When I press F2 the second time i get the following message (I was pressing F2 when the cursor was on "_channel_index_") and the rename option was not available any more:
![image](https://user-images.githubusercontent.com/23265867/68510343-f30a6880-027b-11ea-8171-672ab35ec258.png).

Restarting vscode and disabling & enabling the extension didn't help,
Do you perhaps now why?

Thanks!

**Comment by mjbvz** [comment] 2019-11-08 23:00
@Avivhdr Please open a separate issue. @Rakeda's description is too vague to say this is the same problem

**Comment by Avivhdr** [comment] 2019-11-09 08:17
@mjbvz I opened one, Thanks.
[Issue-84356](https://github.com/microsoft/vscode/issues/84356)

**Comment by mjbvz** [comment] 2019-11-11 22:09
Closing as more information is needed to investigate original issue. Likely caused by one of the installed extensions

**Closed by mjbvz** 2019-11-11 22:09 UTC
Labels: needs more info
