### ISSUE TITLE
version 1.25.0 can not debug in WSL

### ISSUE THREAD

**Issue by LeoYoung** [Microsoft/vscode#53674] opened 2018-07-06 08:40 UTC
Issue Type: <b>Bug</b>

When I update VS code to version 1.25.0 
I found that the breakpoint not hit when debugging (I'm using WSL)
I have set "useWSL": true in launch.json and it works well in version 1.24.1

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (3.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
javascript-ejs-support|Dig|0.3.2
gitlens|eam|8.4.1
EditorConfig|Edi|0.12.4
php-debug|fel|1.12.3
beautify|Hoo|1.3.2
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.25.3
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.7.0
vetur|oct|0.12.5
material-icon-theme|PKi|3.5.1
ayu|tea|0.14.0
vscode-todo-highlight|way|0.5.12
markdown-all-in-one|yzh|1.5.1

</details>

**Comment by weinand** [comment] 2018-07-06 16:29
@LeoYoung what version of node.js are you using in WSL?
You can find out by running this in Windows:
```
wsl node --version
```

**Comment by fxlemire** [comment] 2018-07-06 19:46
I have the same problem, I have version 8.9.4 in WSL.

**Comment by LeoYoung** [comment] 2018-07-07 01:33
@weinand thank you for reply
my node version is `8.11.2` and npm version is `6.1.0`

**Comment by weinand** [comment] 2018-07-09 22:19
Most likely this issue is a duplicate of https://github.com/Microsoft/vscode/issues/53785.
There will be a fix for #53785 in tomorrow's Insider build.
It would be great if you could verify that this fixes the WSL issue as well.

**Comment by LeoYoung** [comment] 2018-07-10 09:29
@weinand 
I have tried the new Insider build (Version 1.26.0)
It seems that this bug has been fixed, THANKS👍

**Comment by weinand** [comment] 2018-07-10 10:36
@LeoYoung great, thanks a lot for verifying this.

**Comment by fxlemire** [comment] 2018-07-10 12:43
I confirm, also works on my end! 👍

**Comment by weinand** [comment] 2018-07-10 13:12
duplicate of #53785

**Closed** 2018-07-10 13:12 UTC
Labels: *duplicate, bug, debug, new release
