### ISSUE TITLE
File content lost when renaming an unsaved file.

### ISSUE THREAD

**Issue by lrvizentini** [Microsoft/vscode#18122] opened 2017-01-04 21:30 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.3.0|
|tslint|eg2|0.7.1|
|vscode-npm-script|eg2|0.1.6|
|Angular1|johnpapa|0.1.16|
|csharp|ms-vscode|1.6.2|
|vs-keybindings|ms-vscode|0.1.2|
|debugger-for-chrome|msjsdiag|2.4.1|
|cordova-tools|vsmobile|1.2.5|

---

Steps to Reproduce:

1. create a new empty file, of any extension
2. edit the file and put some content, DO NOT SAVE
3. rename the file in VsCode
4. you lost the content edited

**Comment by bpasero** [comment] 2017-01-05 07:11
There is a very verbose warning that tells what happens:

![image](https://cloud.githubusercontent.com/assets/900690/21671836/83f3ecf8-d31e-11e6-9a4c-50aeda25a192.png)

Otherwise, duplicate of https://github.com/Microsoft/vscode/issues/11997

**Closed by bpasero** 2017-01-05 07:11 UTC
