### ISSUE TITLE
there is no hint when writing javascript in html file

### ISSUE THREAD

**Issue by Dongep** [Microsoft/vscode#3995] opened 2016-03-11 07:50 UTC
but it is normal in a javascript file

**Comment by dbaeumer** [comment] 2016-03-14 20:19
@aeschli why me :-)

**Comment by dbaeumer** [comment] 2016-03-14 20:20
@Dongep are you talking about linting ?

**Comment by egamma** [comment] 2016-04-13 10:46
I suspect this is intellisense inside script tags which is a known limitations.

**Comment by butterandfly** [comment] 2016-06-12 04:39
This feature is so important to Polymer.

**Comment by mjbvz** [comment] 2016-11-18 22:30
Closing this as a duplicate of #3465, which tracks supporting intellisense and other language features for js inside of html script tags.

**Closed by mjbvz** 2016-11-18 22:30 UTC
Labels: duplicate, feature-request, js
