### ISSUE TITLE
Garbled text in default embedded terminal

### ISSUE THREAD

**Issue by SomervilleTom** [microsoft/vscode#140060] opened 2022-01-03 20:38 UTC
Issue Type: <b>Bug</b>

1. Open VSC on remote host 

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.49.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.49.1.el7.x86_64

When I open VSC on a remote host, I often see garbled text in the embedded terminal as shown in the screenshot that follows:

![garbled_text_in_terminal](https://user-images.githubusercontent.com/64976799/147977453-6a5c50ec-0150-442f-887c-e48f9c159267.png)

When I kill and restart the terminal, the issue disappears.

I'm running VSC on VirtualBox guest VM running Windows 10 Pro. The underlying host is a RockyLinux v8.5 system.

I'm using the "Remote SSH" extension, and the remote host is running a reasonably current version CentOS 7. Each remote host is an AWS EC2 instance. I've been noticing this behavior for the last month or so. It seems to happen on each remote host (though I'm not sure).

Here is the same VSC instance after killing the garbled terminal and starting a new one by invoking the "Terminal -> New Terminal" command:
![normal_text_in_terminal](https://user-images.githubusercontent.com/64976799/147978122-49436f22-edd1-4339-992a-7f96a9e7a2c9.png)

**Comment by meganrogge** [comment] 2022-01-03 22:21
please attach a gif of the issue

**Comment by SomervilleTom** [comment] 2022-01-03 22:40
Garbled text (showing issue):
![garbled_text_in_terminal](https://user-images.githubusercontent.com/64976799/147988016-7aa78f9a-ff9b-4f50-9ee2-dacdb8fb4a9f.gif)

Correct text (after killing and re-opening embedded terminal):

![normal_text_in_terminal](https://user-images.githubusercontent.com/64976799/147988056-d5784a0a-0ba4-4908-ab93-f8f09c4f0839.gif)

**Comment by IllusionMH** [comment] 2022-01-04 15:09
> VS Code version: Code 1.60.1

Also Is it reproducible in latest stable version 1.63.2?

**Comment by SomervilleTom** [comment] 2022-01-04 21:59
It just now failed again, this time running v1.63.2. I'm happy to harvest and forward files from `.vscode-server` on the remote host if that's helpful.

Here's a full screenshot of the failure I just had. Garbled text is circled in red.

![new_garbled_text_in_terminal](https://user-images.githubusercontent.com/64976799/148129446-1c7442dd-66d1-43e4-8903-458572831e48.gif)

**Comment by SomervilleTom** [comment] 2022-01-04 22:06
Here is the current client-side version info (from the "Help" command):

```
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by SomervilleTom** [comment] 2022-01-04 22:11
I've got a tar-gz file with the current contents of `.vscode-server`, but it's large (320MB). Let me know if you'd like me to forward it somehow.

**Comment by Tyriar** [comment] 2022-01-05 17:54
@alexdima any idea on this one around remote connection/compression? The text we're getting appears to be coming in the correct order but some characters are corrupted and pointing to other characters, for example notice how all `o` characters are replaced with `d`s below:

![image](https://user-images.githubusercontent.com/2193314/148265208-2a735ac3-3113-436a-b0d1-452562787ae6.png)

**Comment by SomervilleTom** [comment] 2022-01-07 19:48
FWIW, it seems to be getting slightly worse, in that just now I had to kill and restart the terminal several times (3-4) in order to get clean text.

I've also noticed only while I'm editing a React app. Perhaps there is some React involvement? While it's working properly, it always starts with the following:

```
Debugger listening on ws://127.0.0.1:53036/631bfe8f-4d31-491d-bf83-6cb0b24acc99
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
```
There is so much magic going on (VSC, `npm`, `React`, `nginx`, etc) that it wouldn't surprise me if something in all that is scrambling the terminal itself. Perhaps something is sending garbage special characters that the terminal emulator is treating as terminal control chars? Who knows ...

**Comment by SomervilleTom** [comment] 2022-01-10 23:47
I just saw the same behavior in a VSC instance open on a nodejs (rather than React) app. This is "node express" app, so it's fairly vanilla.

It tells me that the behavior is not specific to React, and may be part of npm.

**Comment by alexdima** [comment] 2022-01-13 20:17
I have seen something similar before when investigating https://github.com/microsoft/vscode/issues/134429 . But #134429 was about the extension host connection. Depending on timing, we would loose a websocket message (a heart-beat that we would send) while passing the socket from the server process to the extension host process. This could have meant that we would lose 4 (or so) bytes from the compressed stream. zlib uses a sliding window for compression and uses instructions like "use 3 bytes from 10 bytes ago". If the stream is somehow incomplete, it can definitely end up with such artifacts where characters are replaced incorrectly.

That being said, this issue is about a remote terminal, and AFAIK its data travels through the management connection which is a socket which never leaves the server process. I can review the code to check that at no time is the socket without a `data` listener. 

@Tyriar Do you have by any chance some logging that could be turned on server-side to compare if the terminal output looks good before being sent to the client?

@SomervilleTom is there something else very specific about the remote machine you are connecting to? like it is a slow machine, with low RAM, CPUs, etc? Also, if you reload the window, we will restore your existing terminal session. Are the characters consistently garbled in the same way during a session?

**Comment by SomervilleTom** [comment] 2022-01-13 21:50
@alexdima:
"... is there something else very specific about the remote machine you are connecting to? like it is a slow machine, with low RAM, CPUs, etc?":
Not as far as I know. It's an AWS EC2 "t2-large" instance with lots of RAM, disk, and CPU power.

"Are the characters consistently garbled in the same way during a session?":
To the contrary -- I've always been able recover from the situation by killing the embedded terminal and starting a new one. Very occasionally, I'll see a few garbled characters in the new embedded terminal instance. Killing and restarting a third time always fixes the issue.

"Did you notice any such garbled characters outside of the terminal? Like when opening files or looking at file names in the explorer?":
I see no evidence of any file corruption, this appears to be very specific to the embedded terminal.

I also do not see this issue using any other connections to the same remote instance. I frequently keep at least one SSH client connected to the same remote instance I've seen no such issues there.

"... is it normal for a terminal to begin with "Debugger listening on..."
I've wondered about the same thing. These sessions always involve either NodeJS or React projects -- each with various npm modules loaded.

I'm relatively new to this entire toolchain, so I have no insight or intuition about what is or is not unusual.

**Comment by mrtumnus** [comment] 2022-05-06 14:19
I'm seeing this in a Windows 10 VM running VS code (VirtualBox).  It appears on multiple terminal types, including Git Bash (default), Javascript Debug Terminal and PowerShell.

**Comment by mrtumnus** [comment] 2022-05-06 14:25
> @SomervilleTom 
> I'm running VSC on VirtualBox guest VM running Windows 10 Pro. The underlying host is a RockyLinux v8.5 system.
VirtualBox here as well - Windows 10 Pro on a Windows 10 Enterprise host.  I'm not doing any remoting though - just using the guest directly.

**Comment by Tyriar** [comment] 2022-05-06 15:06
> Do you have by any chance some logging that could be turned on server-side to compare if the terminal output looks good before being sent to the client?

Not currently

> is it normal for a terminal to begin with "Debugger listening on

This is because auto attach is on, it injects an environment variable that connects any node process to the debugger.

**Comment by Tyriar** [comment] 2022-05-06 15:09
Adding some logging here: https://github.com/microsoft/vscode/pull/148917, this will let us see whether the problem is due to node-pty/shell or somewhere in the pty host connection

**Comment by mrtumnus** [comment] 2022-05-06 15:11
I think this has to do with GPU acceleration for terminal.  Turning it off completely eliminated any corruption.  I can switch back and forth with a terminal window open and see the text garble ('auto' or 'on') or not ('off').  I've seen 'canvas' mode also show some corruption, but it seems a bit more stable than 'on' or 'auto'.

**Comment by Tyriar** [comment] 2022-05-06 15:21
It could be misplaced glyph's in the terminal's texture atlas, it's just strange that I've never encountered this if so.

**Comment by mrtumnus** [comment] 2022-05-06 15:40
![vscode_terminal_corruption](https://user-images.githubusercontent.com/1738198/167166377-e805ec63-ba7b-49cb-a256-7173c5fab4e6.gif)

**Comment by mrtumnus** [comment] 2022-05-06 15:48
Maybe "back and forth" was too pessimistic.  The corruption isn't consistent, as noted previously.  But switching Gpu Acceleration off always removes it.

Looks like the corruption involves reusing some text from later in the string being rendered:

```
user@Test => rojecTjot (from "Project")?
u => r
s => o
e => j
r => e
@ => c
T => T
e => j (consistent with first replacement above)
s => o (consistent)
t => t
```

**Comment by mrtumnus** [comment] 2022-05-06 15:51
> It could be misplaced glyph's in the terminal's texture atlas, it's just strange that I've never encountered this if so.

Do you run vscode in a VM much?  This has been the only way I've encountered this.  Running vscode on a host does not produce this behavior in my experience.

**Comment by DarrenLevine** [comment] 2022-05-06 18:27
My team and I are also seeing this issue in the integrated terminal on windows when sending command sequences to the terminal via several different independent methods. The issue seems to occur more frequently when larger amounts of text are sent to the terminal. And the issue can always be fixed temporarily be closing the offending terminal instance, at which time when sending a new command causes a new terminal to be created, the command will not error out on this first command, but every command sent to that terminal afterwards is susceptible to this bug, at seemingly random intervals.

I'm able to reproduce the issue using the following extensions to send text to the integrated terminal:

[formulahendry.code-runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) 

[malkomalko.send-to-terminal](https://marketplace.visualstudio.com/items?itemName=malkomalko.send-to-terminal) 

[discretegames.f5anything]
(https://marketplace.visualstudio.com/items?itemName=discretegames.f5anything)

I'm running a MSYS2 bash terminal on windows 10 Enterprise and Windows 11. In order to reproduce, I just send a large echo command  "echo 1233456..." with a few hundred characters, and after a few back to back runs, the corruptions start appearing.

Also, turning off gpu accelerating seems to reduce the frequency of the issue slightly, but does not fully fix/prevent it when large amounts of text are sent to the terminal.

**Comment by SomervilleTom** [comment] 2022-10-28 21:06
Still happening on 28-Oct-2022. I'm using the "Remote SSH" extension, so the embedded terminal in question is always running on a remote host. That remote host is now running a current Rocky Linux v8.6 on a robust AWS EC2 instance.

The garbled text is occasional and can usually be fixed by killing and reopening the embedded terminal.

**Comment by Tyriar** [comment] 2022-11-30 19:38
I believe this particular problem is fixed, please search existing issues or create a new one if you see other rendering problems.

**Closed by Tyriar** 2022-11-30 19:38 UTC
Labels: bug, confirmation-pending, terminal-process

**Comment by SomervilleTom** [comment] 2022-11-30 19:40
Fixed in which release? I'm running v1.73.1 of VSC and if anything it is happening more frequently.

**Comment by SomervilleTom** [comment] 2022-11-30 19:41
Is some part of my [28-Oct-2022 update](https://github.com/microsoft/vscode/issues/140060#issuecomment-1295466739) unclear?

**Comment by SomervilleTom** [comment] 2022-11-30 19:42
I'm happy to take and post screenshots if it's helpful.

**Comment by Tyriar** [comment] 2022-11-30 19:42
@SomervilleTom are you seeing glyphs being invisible or scrambled, or do some characters look like other characters in the original screenshot?

![image](https://user-images.githubusercontent.com/2193314/204893096-edd82445-f7b6-4c7c-927c-75a5af21e1cb.png)

**Comment by SomervilleTom** [comment] 2022-11-30 19:47
I see scrambled and improper characters. I haven't noticed any invisible chars. I'll post a screenshot the next time it happens -- it's been hitting me several times per day recently.

**Comment by Tyriar** [comment] 2022-11-30 19:52
Thanks, I can reopen if this is still an issue, this one is specifically tracking characters completely swapped for others. We recently made a change that fixes scrambled and invisible characters in https://github.com/xtermjs/xterm.js/pull/4271

**Comment by mrtumnus** [comment] 2022-11-30 19:52
I no longer see this issue, but I am running VSC on the Windows host using an SSH remote connection. Also, I am now using VMWare rather than VirtualBox.  If I run VSC within the VMWare guest, I don't get any scrambled characters, regardless of whether GPU Acceleration is enabled.

**Comment by mrtumnus** [comment] 2022-11-30 19:53
> I see scrambled and improper characters. I haven't noticed any invisible chars. I'll post a screenshot the next time it happens -- it's been hitting me several times per day recently.

Are you still running VSC in a VirtualBox guest?

**Comment by SomervilleTom** [comment] 2022-11-30 19:53
Here is what I expect:
![20221130_vsc_correct_prompt](https://user-images.githubusercontent.com/64976799/204895036-1b74ff13-0de8-4355-8a09-084643712e7c.png)

Here is what I got just now (in response to the "New Terminal" menu command):
![20221130_vsc_missing_chars](https://user-images.githubusercontent.com/64976799/204895051-5eafa145-500f-496b-9a86-f1b0cbb6e6c8.png)

**Comment by SomervilleTom** [comment] 2022-11-30 19:58
"Are you still running VSC in a VirtualBox guest?"

Yes. It's the same configuration as above. I'm running VSC locally on a VirtualBox guest VM running Windows 10 Pro. It's using "remote SSH" and connected to a remote instance on an AWS EC2 instance running Rocky Linux v8.7.

**Comment by Tyriar** [comment] 2022-11-30 19:58
@SomervilleTom that looks like https://github.com/xtermjs/xterm.js/pull/4271 which is coming in 1.74

**Comment by SomervilleTom** [comment] 2022-11-30 20:00
I'll post a screenshot the next time I see scrambled characters.

I appreciate your attention. I know issues like this are tedious and annoying to chase down -- I spent several decades on your side of the support exchange. :)

**Comment by SomervilleTom** [comment] 2022-11-30 20:24
Just now got a scrambled/garbled character -- "S":

![20221130_vsc_garbled_chars](https://user-images.githubusercontent.com/64976799/204900745-88810cef-a404-41f7-bfc2-5abe70dcd89d.png)

**Comment by SomervilleTom** [comment] 2022-11-30 20:41
> Have you tried messing around with VirtualBox's rendering modes? Graphics Controller, 3D Acceleration?

No. Everything else in the VM works fine, this issue seems to be specific to VSCode.

**Comment by Tyriar** [comment] 2022-11-30 22:47
@SomervilleTom yep that looks like also https://github.com/xtermjs/xterm.js/pull/4271, so hopefully things are all good when you get the update 🤞

**Comment by SomervilleTom** [comment] 2022-12-02 20:18
@Tyriar Do you have a timeline for this update?

This problem appears to interact with a different issue related to 'Remote SSH'. I observe that the `vscode-server` on the target instance opens many ports during a "yarn start", and apparently doesn't close them properly.

The result is that after a given resource is started and stopped multiple times, `SS -tna | grep TIME` shows dozens of ports in "TIME-WAIT" status on the target server. The server eventually hits some threshold (I don't know where it's set) such that nothing can connect to the server until the dead ports time out.

The only current workaround for this issue requires stopping and restarting the affected application -- sometimes multiple times.

The result is that I have to shut down all the VSC connections and wait.

I'm working on a project where I frequently have 4 different VSC windows running -- 2 backend services and 2 React front-end services. Each of those React front-ends has its own "development" server.

It's tedious to kill and restart all of these.

Hence my eagerness to get a fix for this garbled character issue -- one less aggravation. :)

**Comment by Tyriar** [comment] 2022-12-02 20:26
Our endgame plans show the expected release time: https://github.com/microsoft/vscode/issues/167267, likely the 7th or 8th of December.

**Comment by SomervilleTom** [comment] 2022-12-02 20:32
@Tyriar: Awesome! I appreciate your attention and immediate response.

**Comment by SomervilleTom** [comment] 2022-12-10 00:36
I'm running the new release and still have the same garbled characters:

![20221209_vsc_garbled_chars](https://user-images.githubusercontent.com/64976799/206818998-e3c22687-28b5-41bf-bc1a-6a95c0316e96.png)

Here is the text of the "About" pane for the failing VSC instance:

```
Version: 1.74.0 (system setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.18363
Sandboxed: No
```

I'm connected to a remote instance using the "remote SSH" extension. The above screenshot is of a Terminal instance on the remote system.
