### ISSUE TITLE
Keyboard shortcut for extracting a variable/function after selection

### ISSUE THREAD

**Issue by tomepejo** [Microsoft/vscode#41425] opened 2018-01-10 20:16 UTC
*Extract local refactoring for JavaScript and TypeScript* was [recently](https://code.visualstudio.com/updates/v1_18#_extract-local-refactoring-for-javascript-and-typescript) introduced to the VS Code.
It would be great if a **keybinding** is available for this feature as well.

**Comment by mjbvz** [comment] 2018-01-11 06:15
Duplicate of #33555

**Closed by mjbvz** 2018-01-11 06:15 UTC
Labels: feature-request, javascript
