### ISSUE TITLE
正在初始化 JS/TS 语言功能

### ISSUE THREAD

**Issue by HKmylove** [microsoft/vscode#108367] opened 2020-10-09 07:49 UTC
Issue Type: <b>Bug</b>

打开js文件就会出现

![image](https://user-images.githubusercontent.com/45782901/95557176-fd625300-0a46-11eb-934c-c28a965e8950.png)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.74GB (1.61GB free)|
|Process Argv|--crash-reporter-id d8a40286-c49c-430c-8268-0be071fa5a6f --crash-reporter-id d8a40286-c49c-430c-8268-0be071fa5a6f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
bracket-pair-colorizer-2|Coe|0.2.0
sftp|lix|1.12.9
vscode-language-pack-zh-hans|MS-|1.50.2
indent-rainbow|ode|7.4.0
laravel-blade|one|1.24.0
tabnine-vscode|Tab|3.0.3
vscode-icons|vsc|11.0.0

</details>

**Comment by alannt777** [comment] 2020-10-09 08:11
Title: Initializing JS/TS language functionality.*
Content: Open the js file and it will appear.*

I think he meant that It is showing `initializing JS/TS features` for a long time and It is not initializing. If that is the case, then this issue is a duplicate of #105381


*Using Microsoft Translator

**Comment by escape0707** [comment] 2020-10-10 08:27
@alannt777 You're right.
He means VSCode is showing initializing JS/TS features once he opened a `.js` file.
But he didn't provide any other info.

**Comment by mjbvz** [comment] 2020-10-20 22:47
Closing this as not actionable without more information and steps to reproduce the issue

**Closed by mjbvz** 2020-10-20 22:47 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
