### ISSUE TITLE
ctrl+n/p doesn't work which works in sublime line

### ISSUE THREAD

**Issue by g0ne150** [Microsoft/vscode#8783] opened 2016-07-06 04:36 UTC
- VSCode Version: all versions
- OS Version: OS X

Steps to Reproduce:

1. [shift+]cmd+p
2. ctrl+n/p doesn't work which works in sublime

**Comment by joaomoreno** [comment] 2016-07-06 10:58
Duplicate of #7876

**Closed by joaomoreno** 2016-07-06 10:58 UTC
