### ISSUE TITLE
Undo stack includes final newline being removed and inserted on every save in json files with files.insertFinalNewline = true && editor.formatOnSave = true

### ISSUE THREAD

**Issue by jplatte** [Microsoft/vscode#56019] opened 2018-08-08 17:29 UTC
- VSCode Version: 1.25.1 (also reproducible in 1.26.0-insider)
- OS Version: arch linux

When saving a json file while both `files.insertFinalNewline` and `editor.formatOnSave` are set to `true`, the editor will remove (if present), then re-add the final newline on every save. Trying to then undo changes made before saving the file first undoes the newline re-insertion on first try, the newline deletion on the second try, and only then the actual change before saving the file. This is especially inconvenient in large files, where the view scrolls to the end of the file when the newline changes are undone.

I would guess that this could be fixed by not removing the final newline when formatting json if `files.insertFinalNewline` is set to `true`.

Steps to Reproduce:

1. Set `files.insertFinalNewline` and `editor.formatOnSave` to `true`
2. Create or open a json file (just `{}` suffices)
3. Do some modifications
4. Save the json file
5. Try to undo the previous modifications with Ctrl+Z

Does this issue occur when all extensions are disabled?: Yes

**Comment by jplatte** [comment] 2018-08-08 17:33
Okay, this is indeed a duplicate, but the old issue doesn't explain why this is an issue and hasn't received any attention more than 1.5 years. Not sure how to proceed, so I'll leave this open for now.

**Comment by aeschli** [comment] 2018-08-08 19:00
duplicate of #17359

**Closed by aeschli** 2018-08-08 19:00 UTC
Labels: insiders
