### ISSUE TITLE
Failed to update plug-in

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#53378] opened 2018-06-30 11:57 UTC
Issue Type: <b>Bug</b>

Failed to update plug-in.Tried  many times the result is the same.But the extensions will update successed when reload windows or reopen the VSCode.

VS Code version: Code - Insiders 1.25.0-insider (6ca99aca80e80224f1c0bd4370c6ec4941c3bc54, 2018-06-29T09:03:04.490Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (0.90GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.14.0
flutter|Dar|2.14.0
code-runner|for|0.9.3
Kotlin|mat|1.6.0
vscode-cosmosdb|ms-|0.7.2
vscode-language-pack-zh-hans|MS-|1.25.1
windowsiot|ms-|0.0.20
python|ms-|2018.6.0
vscode-ai|ms-|0.1.9
azure-account|ms-|0.4.1
cpptools|ms-|0.17.5
csharp|ms-|1.15.2
Go|ms-|0.6.84
js-atom-grammar|ms-|0.1.14
jscs|ms-|0.1.9
mono-debug|ms-|0.15.8
typescript-javascript-grammar|ms-|0.0.42
vetur|oct|0.12.5
quantum-devkit-vscode|qua|0.2.18061503
java|red|0.27.0
vscode-yaml|red|0.0.13
rust|rus|0.4.5
vscode-arduino|vsc|0.2.17
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0
JavaScriptSnippets|xab|1.7.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2018-06-30 16:55
Can you describe exactly what the problem is when you try to update an extension?

**Comment by czfadmin** [comment] 2018-07-01 05:22
@roblourens 
When I update some plugins that are prompted to be updated, it should show Reload but it still shows that we are asking for updates. But the plugin is updated when we reload the window or restart the vscode.

**Comment by sandy081** [comment] 2018-07-02 09:30
Duplicate of #53426

**Closed** 2018-07-02 09:30 UTC
Labels: *duplicate
