### ISSUE TITLE
not colored "#" and ">" after "$" in markdown

### ISSUE THREAD

**Issue by cascadehammer** [microsoft/vscode#137562] opened 2021-11-20 02:34 UTC
Issue Type: <b>Bug</b>

When I create a markdown file in Visual Studio Code, the # and > are usually colored, but the # and > on the line after the $ are not colored.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by cascadehammer** [comment] 2021-11-20 02:49
In a new markdown file:
#      (colored)
>      (colored)
(This is OK)
But, the following contents are not colored:
$      (not colored)
#      (not colored)
>      (not colored)
(This is NG)

when there are even number of $, # and > seem to be colored.
$      (not colored)
$      (not colored)
#      (colored)
>      (colored)

I hope this is reproduced.

**Comment by cascadehammer** [comment] 2021-11-20 03:03
```
$$
#
>
```
Even if there are two $ in the same line, # and > are not colored.

```
$$$$
#
>
```
if there are four $ in the same line, # and > are colored.

Umm...

**Comment by gjsjohnmurray** [comment] 2021-11-20 06:07
/duplicate of #136535 which is fixed for the next release (1.63) due in December. 

If you are able to install Insiders you can verify this.

**Closed** 2021-11-20 06:08 UTC
Labels: *duplicate, new release
