### ISSUE TITLE
Interactive python could not convert to Notebook with result 

### ISSUE THREAD

**Issue by Herman-Wu** [microsoft/vscode#129349] opened 2021-07-25 14:58 UTC
Issue Type: <b>Bug</b>

Environment: Anaconda, Python 3.7, 3.8
After written some python in Interactive Python and tried to convert it to Jupiter Notebook in order to store the result, the result of the execution is not included in the generated notebook. 

This is a deal-breaker, I have to use the non-insider version until this is been fixed. 

Thanks 

VS Code version: Code - Insiders 1.59.0-insider (e8a59bc6f920e731b47f0bc72263e82aba8b796e, 2021-07-22T05:14:01.507Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-11955M CPU @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.20GB (32.94GB free)|
|Process Argv|--crash-reporter-id 10749f8e-d7a2-4845-9119-d7146a261d97|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-profile-switcher|aar|0.3.3
Bookmarks|ale|13.1.0
project-manager|ale|12.3.0
vscode-sequence-diagrams|Ale|0.4.7
vscode-browser-preview|auc|0.7.1
markdown-checkbox|bie|0.1.3
markdown-mermaid|bie|1.10.0
markdown-preview-github-styles|bie|0.2.0
mermaid-markdown-syntax-highlighting|bpr|1.2.2
bracket-pair-colorizer|Coe|1.0.61
excel-to-markdown-table|csh|1.2.2
markdown-table-prettify|dar|3.4.0
githistory|don|0.6.17
gitlens|eam|11.6.0
vscode-git-history|fab|2.0.5
md2reader|gdr|0.8.0
gc-excelviewer|Gra|3.0.42
todo-tree|Gru|0.0.213
beautify|Hoo|1.5.0
githd|hui|2.2.4
plantuml|jeb|2.15.1
vscode-insertdatestring|jsy|2.3.0
vscode-markdown-notes|kor|0.0.24
markdown-converter|man|3.1.2
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1055544705
remote-containers|ms-|0.189.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
git-file-history|pom|1.0.1
vscode-yaml|red|0.21.1
highlight-words|rsb|0.1.4
text-marker|ryu|1.11.0
markdown-preview-enhanced|shd|0.5.22
vscode-markdown-preview-include|sta|0.0.4
unique-window-colors|stu|1.0.51
markdown-memo|svs|0.3.9
spellchecker|swy|1.3.0
open-in-browser|tec|2.0.0
vscode-markdown-paste-image|tel|0.13.3
vscode-mermaid-preview|vst|1.6.2
vscode-todo-highlight|way|1.0.4
markdown-auto-toc|wib|0.3.0
dictionary-completion|yzh|1.1.0
markdown-all-in-one|yzh|3.4.0
grammarly|znc|0.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-07-26 03:57
/duplicate of https://github.com/microsoft/vscode-jupyter/issues/6779

**Closed** 2021-07-26 03:57 UTC
Labels: *duplicate
