### ISSUE TITLE
Open Markdown preview to the side shortcut not working

### ISSUE THREAD

**Issue by brgrz** [Microsoft/vscode#38498] opened 2017-11-16 10:34 UTC
The Ctrl+K V shortcut to open Markdown preview is not working for me for some reason.

**Comment by mjbvz** [comment] 2017-11-16 20:01
Can you still open the preview using the `open preview to side` command? Any custom keybindings? What if you disable all installed extensions?

**Comment by brgrz** [comment] 2017-11-16 21:16
Clicking on the button to open the preview does work. I removed all the extensions that were changing the shortcuts (the formatting ones). I guess I could remove all the extensions. Or is there a way to reset the shortcuts back to defaults?

**Comment by mjbvz** [comment] 2017-11-17 00:48
So does the keyboard shortcut work when when you disable all extensions? Try looking at your current [keybindings](https://code.visualstudio.com/docs/getstarted/keybindings) to make sure Ctrl+K V still points to `Open Preview to Side`

**Comment by mjbvz** [comment] 2017-11-27 19:27
Closing as possibly caused by extension or custom settings

**Closed by mjbvz** 2017-11-27 19:27 UTC
Labels: markdown, needs more info
