### ISSUE TITLE
JS semantic highlighting in some instances makes code actually harder to read

### ISSUE THREAD

**Issue by CherryDT** [microsoft/vscode#91068] opened 2020-02-20 10:44 UTC
Issue Type: <b>Bug</b>

For a few days now I'm seeing an issue with JS syntax highlighting. I'm using latest VSCode Insiders and I tried with extensions disabled, and it still happens.

Suppose I have a JS file with these contents:

```javascript
console.log('hi')

const test = {
  aaa: '1',
  bbb: String
}
```

When I start VSCode, initially it looks correct:

![image](https://user-images.githubusercontent.com/6010463/74926496-43927580-53d6-11ea-9dcf-cc1f13eb8ec1.png)

But after ~10 seconds, it changes to a slightly messed-up state:

![image](https://user-images.githubusercontent.com/6010463/74926515-4b521a00-53d6-11ea-85d1-8dae1fb07055.png)

Notice how the `console` became light-blue and `bbb` became yellow! (I noticed that what makes object keys yellow is when their value is a single word that happens to be highlighted in green.)

It stays this way from then on. This makes my JS files much harder to read.

VS Code version: Code - Insiders 1.43.0-insider (9c341b3d8f2f41277be6dd59e7f4e847e6b594ac, 2020-02-20T05:39:38.179Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (5.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote||
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.83GB (5.68GB free)|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment] 2020-02-20 10:50
This works as intended after implementation of [Semantic highlighting for TypeScript & JavaScrip](https://code.visualstudio.com/updates/v1_42#_semantic-highlighting-for-typescript-javascript)

It is enabled by default in Insider builds and can be turned off with `"editor.semanticHighlighting.enabled": false` to always use highlight based on TM grammars.

/cc @aeschli

**Comment by aeschli** [comment] 2020-02-20 11:44
Interesting example.
- `console` got classified as a variable, as that's what it is. (Semantic highlighting has no concept of library variables and functions)
- `bbb` got classified as member as `String` is callable. Although that's true (`String(1)"`) that's not what users typically do with Strings.

**Comment by CherryDT** [comment] 2020-02-20 11:47
Ah. It seems this feature is working against me. Thanks, I'll just disable it.

The problem is, it causes this sort of messed-up code for things like Mongoose model definitions:

![image](https://user-images.githubusercontent.com/6010463/74931058-30d06e80-53df-11ea-8b76-6e92a9918ab7.png)

**Comment by aeschli** [comment] 2020-02-20 14:39
I fixed the `String`, `Number` and 'Date' issue: https://github.com/aeschli/typescript-vscode-sh-plugin/commit/102a3a190ceece98b7c6e18251c44aed9a49e742

**Comment by aeschli** [comment] 2020-02-20 14:49
I created #91090 for supporting different rendering of the 'standard' types and variables (such as 'console'.

Closing this issue as dup of #91090

**Closed by aeschli** 2020-02-20 14:49 UTC
Labels: semantic-tokens, typescript

**Comment by IllusionMH** [comment] 2020-02-20 15:07
Would it change what colors are applied in case of React component?
![image](https://user-images.githubusercontent.com/1312662/74946954-c03b4900-5402-11ea-8c90-814fed73c2c9.png)

Will `a` instead will be colored as usual variable (same as `b`)? Or `getProperties` doesn't relate to `keyof`?
