### ISSUE TITLE
Completion providers with resolve methods leak memory

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#74446] opened 2019-05-28 09:10 UTC
Here's a fake completion provider that returns 20k items. Its resolve method does nothing (but exists, so that VS Code thinks it may be used - that seems to be important).

```ts
export class FakeCompletionItemProvider implements CompletionItemProvider {
	public async provideCompletionItems(
		document: TextDocument, position: Position, token: CancellationToken, context: CompletionContext,
	): Promise<CompletionList> {

		const items: CompletionItem[] = Array<CompletionItem>(20000);
		for (let i = 0; i < items.length; i++) {
			const item = new CompletionItem(`Item ${i}`);
			item.filterText = `${item.label}???`;
			item.kind = CompletionItemKind.Constant;
			item.detail = "(deprecated)";
			item.documentation = "docs";
			item.insertText = `${item.label} !!`;
			item.keepWhitespace = true;
			item.commitCharacters = ["["];

			item.command = {
				command: "editor.action.triggerSuggest",
				title: "Suggest",
			};
			items[i] = item;
		}
		return new CompletionList(items);
	}

	public async resolveCompletionItem(item: DelayedCompletionItem, token: CancellationToken): Promise<CompletionItem | undefined> {
		return undefined;
	}
}
```

If you register this provider, then repeatedly invoke completion (I found the easiest way to do this was inserting lots of newlines then hitting `Ctrl`+`Space` then `Backspace` repeatedly), the memory grows continiously and is never reclaimed.

![memory](https://user-images.githubusercontent.com/1078012/58465909-8ae22300-8130-11e9-8deb-ea2a9c6ff3c9.png)

I believe this may be what my users are seeing in https://github.com/Dart-Code/Dart-Code/issues/1721 and https://github.com/flutter/flutter/issues/33280 and I saw in https://github.com/microsoft/vscode/issues/74390. After many the extension host crashes being out of memory.

@jrieken FYI (relates a little to what I was trying to repro with https://github.com/microsoft/vscode/issues/74418, but did badly because I removed resolve).

**Comment by DanTup** [comment] 2019-05-28 09:21
Running the test I had for #74418 the result is much more obvious:

```
Total run took 59028 ms heap change was 270 MB // without resolve
Total run took 81234 ms heap change was 1597 MB // with (empty) resolve
```

**Comment by jrieken** [comment] 2019-05-28 09:21
I can confirm that the `executeCompletionItemProvider` leaks but very scary is that the completion model itself doesn't seems to be disposed (tho all the code for it should be in place)

**Comment by jrieken** [comment] 2019-05-28 09:23
wow - this is a good fix. thanks @DanTup

**Comment by DanTup** [comment] 2019-05-28 09:26
np! Hope it's an easy fix. I'd planned to disable our unimported-file completions in the next release, but assuming you can get this into the May release I think I'll just leave it for people to tolerate (or manually disable) until then 👍

**Comment by jrieken** [comment] 2019-05-28 09:31
wait, I do see the `$releaseCompletionItems` message being send. That happens whenever a suggest session end, e.g the widget closes or suggest is retriggered. Debugging this shows that the item cache is cleared. 

<img width="472" alt="Screenshot 2019-05-28 at 11 29 08" src="https://user-images.githubusercontent.com/1794099/58467393-dbab4900-813b-11e9-9440-4e14ad09f5fe.png">


There is the leak when using the command but I am not so sure about the leakage in normal use anymore. 

@DanTup Still thanks for this issue (nuked my previous comment with some false claims)

**Comment by DanTup** [comment] 2019-05-28 09:38
> There is the leak when using the command but I am not so sure about the leakage in normal use anymore.

My repro above is normal use (not calling the command from a test, but triggering from the editor):

> "I found the easiest way to do this was inserting lots of newlines then hitting `Ctrl`+`Space` then `Backspace` repeatedly"

Can you repro it doing that? (I don't know if it's important to cancel the completion prior to it being rendered with the list, but that's what I was doing).

**Comment by jrieken** [comment] 2019-05-28 09:50
@DanTup Can you start with `--logExtensionHostCommunication` and check for a `$releaseCompletionItems` message being send from the window to the extension host process? That message should be send to clear the result of a provide call (give the provider has a resolve-function)

<img width="543" alt="Screenshot 2019-05-28 at 11 49 25" src="https://user-images.githubusercontent.com/1794099/58468911-c1bf3580-813e-11e9-9a1a-d6201714438c.png">

**Comment by jrieken** [comment] 2019-05-28 09:54
To clarify further - below screen capture shows how thing relate, the reply to the request (145) contains the id of the result (4) which is then used in the release-call

<img width="799" alt="Screenshot 2019-05-28 at 11 52 35" src="https://user-images.githubusercontent.com/1794099/58469128-2f6b6180-813f-11e9-935d-09b798d4d9a2.png">

**Comment by DanTup** [comment] 2019-05-28 09:57
> Can you start with `--logExtensionHostCommunication` and check for a $releaseCompletionItems message being send from the window to the extension host process?

I switched to Insiders and updated to ensure there's nothing changed since stable, but I still see it. Doing what you see, as far as I can tell there is *not* a call to release.

Here, I hit `Ctrl+Space`, `Backspace`, `Ctrl+Space` so that there were two requests for completion, and the first was cancelled (but seems not released).

![prov](https://user-images.githubusercontent.com/1078012/58469418-62a9f280-8137-11e9-897c-e6d3b377f924.png)

**Comment by DanTup** [comment] 2019-05-28 09:59
Wait, further down I did get:

```
113 - request: ExtHostLanguageFeatures.$releaseCompletionItems( 2 3 )
```

**Comment by DanTup** [comment] 2019-05-28 10:02
But if I run it a lot of times, then the number of releases don't seem to match the number of requests?

![counts](https://user-images.githubusercontent.com/1078012/58469786-1e6b2200-8138-11e9-9ab4-f3612814cc6f.png)

**Comment by DanTup** [comment] 2019-05-28 10:04
Maybe it's a race? If the client doesn't get the results (due to cancelling), does it assume it doesn't need to release them - even though the extension host may have added them to some cache?

**Comment by DanTup** [comment] 2019-05-28 10:06
Is there any good way to filter this log, so I can easily see the completion requests and their replies, without other noise?

**Comment by jrieken** [comment] 2019-05-28 10:06
Yeah, that could be it. The request is being cancelled (which means the UI never gets a result) but if the provider still returns something then we keep it forever

**Comment by DanTup** [comment] 2019-05-28 10:09
If it helps, [here is a log](https://github.com/microsoft/vscode/files/3227015/completion.txt) from my running completion multiple times and seeing this. My guess is that there are missing releases, but it's hard to match all the requests up :-)

**Comment by jrieken** [comment] 2019-05-28 10:15
> but it's hard to match all the requests up.

I am simply counting find matches, e.g. there are 5 provider-calls and only 1 release-call, and 4 cancel. I guess dart returns a result despite the cancellation token being in cancel-state, then it's us also not honouring that token and caching the items forever. 

I has a fix ready which makes sure we never cache when cancellation happened...

**Comment by jrieken** [comment] 2019-05-28 10:19
Closing this with my fix (https://github.com/microsoft/vscode/commit/034165ac674c36131429301aea78fea7877acb72). @DanTup Thanks for the help!

**Closed by jrieken** 2019-05-28 10:19 UTC
Labels: bug, freeze-slow-crash, important, suggest

**Comment by DanTup** [comment] 2019-05-28 10:24
>  I guess dart returns a result despite the cancellation token being in cancel-state, then it's us also not honouring that token and caching the items forever.

Today it does, though vNext checks the tokens and bails out. The testing done just above was using the fake provider I listed right at the top of here though, which has no async work in (so I presume the cancellation token couldn't have been updated since it's single-threaded?).

I don't have all the stuff set up to build VS Code locally since reinstalling Windows (maybe you can make that work in a container ;-)) but I'll test itout tomorrow in Insiders with the stuff above and my real extension.

Thanks for the quick investigation and fix :-)

**Comment by DanTup** [comment] 2019-05-29 07:48
@jrieken I tested this in Insiders (same things as yesterday).. test no longer reports huge numbers and manually spamming the buttons doesn't result in memory climbing anymore:

![memory](https://user-images.githubusercontent.com/1078012/58539074-7c5a4100-81ee-11e9-9deb-d2da83f6a905.png)

So the fix certainly appears to resolve everything I was hitting. Thanks for addressing it so quickly! 😃
