### ISSUE TITLE
"Recently Used" Option For Sublevel Tasks

### ISSUE THREAD

**Issue by joelmagner** [microsoft/vscode#78422] opened 2019-08-03 09:16 UTC
# Feature request:

Allow sub-level tasks to have _Recently Used_ in the sublevel option. 

![Recently Used](https://i.imgur.com/hj95BXL.png)

This would be very handy when you have a lot of sub-options.
Usually you just want to rerun the same task, lets say I'm working on *Customer3*, or even.. customer 9.. You can see the hassle I have to go through every time by navigating down to Customer9 in the list with my arrow keys (or pick up the mouse and click (if it is visible in the list)). 
This proposed feature would allow me to do:
`CTRL+SHIFT+B -> ENTER -> ENTER`

Verifiable example:
```
"tasks": [
        {
            "label": "Build Customer",
            "type": "shell",
            "command": ".\\AutoBuild.bat",
            "options": {
                "shell": {
                    "executable": "powershell.exe"
                },
                "cwd": "${workspaceFolder}",
            },
            "isBackground": false,
            "args": [
                "${input:customerName}",
                "${input:buildWhat}"
            ],
            "group": "build",
            "problemMatcher": []
        }
    ],
    "inputs": [
        {
            "type": "pickString",
            "id": "customerName",
            "options": [
                "customer1",
                "customer2",
                "customer3"
            ],
            "description": "📦 Select Customer...",
            "default": "customer1"
        },
        {
            "type": "pickString",
            "id": "buildWhat",
            "description": "🗳 Select SW version",
            "options": [
                "v102",
                "v103"
            ],
            "default": ""
        },
    ]
```

Add a couple of more options and sub-options and you will see what I mean.

**Comment by alexr00** [comment] 2019-08-05 08:38
Duplicate of #72944

**Closed by alexr00** 2019-08-05 08:38 UTC
