### ISSUE TITLE
Intellisense for nodejs not working - vscode 1.23.1

### ISSUE THREAD

**Issue by FabriceTheMan** [Microsoft/vscode#51035] opened 2018-06-03 07:12 UTC
I have searched and there are many issues related (although most of them don't use the last version of VSCode), but none of them allow fixing the issue definitely.
I use the same version of VSCode on Windows 10 Version 1803 (OS Build 17134.1) and CentOS 7. On Windows 10 it works flawlessly, on CentOS 7 it's unfortunately very different.

- VSCode Version: 1.23.1
- OS Version: CentOS 7

Steps to Reproduce:
1. Install CentOS 7
2. Install VSCode with Nodejs extension as per following article: https://code.visualstudio.com/docs/setup/linux
3. Create a folder - Create a new nodejs project : npm init -y.
4. Create a js file and start using a built in module: fs=require('fs')
5. fs. => will not show intellisense...

I got it WORKING SUCCESSFULLY ONCE in one of my project. For that I just install the types module for (core) node: npm i @types/node. It then installed this @types folder in node_modules and it all start working. I still have this project working.

I then create another project in a separate folder and start it all again. It didn't work. I then try to install VSCode intellisense extension (this one: https://marketplace.visualstudio.com/items?itemName=leizongmin.node-module-intellisense) but it didn't solve the issue. Any other project I have created since don't have intellisense working successfully.

I compare the files in the working project and non working project 1 by 1, but no success.

Does this issue occur when all extensions are disabled?: Yes

Anyhelp more than welcome.

**Comment by jsprow** [comment] 2018-06-07 18:35
I've got the same issue over on macOS 10.13.4 (17E202) with VSCode version 1.24.0.

Autocomplete isn't working unless I manually add `@types/{some_module}`, including Node built-ins. I guess I'm cool doing this, but I feel like autocomplete used to be the default behavior.

Steps to reproduce:
1. Remove VSCode from Applications folder.
2. In terminal: `rm -rf ~/.vscode && rm -rf /Library/Application\ Support/Code`.
3. Download and install VSCode 1.24.0.
4. Create a `.js` file and run `npm init`.
5. In the file:
```js
const fs = require('fs');
fs.{ should autocomplete }
```
6. It doesn't autocomplete.
7. Run: `npm i -S @types/node`.
8. Autocomplete works great!

Let me know if there's any other information I can add that might help!

**Comment by mjbvz** [comment] 2018-06-07 23:27
Yes, lease try collecting the automatic typings acquisition logs:

1. Set `  "typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the issue
1. In a js file, run the `TypeScript: Open ts server log` command
1. This should open a folder with a `ti-xxx.log` file in it. That is the typings installer log

If you can share that file, someone on the TS team or I may be able to track down why node types are not being downloaded properly. If you don't want to share the full file, try looking for errors in that file, especially ones related to `@types/node`

**Comment by jsprow** [comment] 2018-06-08 00:21
Thanks @mjbvz,

Strange thing happened... I went to duplicate the error in a new folder (new `npm init`, too), and everything was fine. Since commenting, I ended up adding my usual extensions (it's a work day). When I was trying to reproduce the problem, I disabled all of them. Intellisense worked afterward, so I enabled the extensions again, restarted, and... it's still working.

Maybe an extension problem? That seems to be the case with many of the related issues I've looked at. Weird thing is, I had the same issue on a clean install. I looked through the log and couldn't spot any obvious errors, but attached it, all the same.

The only other thing I can think of (maybe a stretch), is that I downgraded Node from 10.4.0 to 8.11.2 to play nice with some dependencies I needed to use.

If there's anything else I can do, let me know. For some reason, bugs that 'fix themselves' concern me the most.

[ti-84827.log](https://github.com/Microsoft/vscode/files/2082467/ti-84827.log)

**Comment by jsprow** [comment] 2018-06-08 00:26
Also, I'll do a clean install again in the morning, following the steps in my earlier comment: [https://github.com/Microsoft/vscode/issues/51035#issuecomment-395521890](url)

**Comment by jsprow** [comment] 2018-06-11 14:52
I tried duplicating the problem: put Node back to 10.4.0 and went through a clean install. Everything's working great. Problem solved... for me, at least.

**Comment by xxDukeMCxx** [comment] 2018-06-11 22:24
Hi,

just upgrade to 1.24.0 and in all my projects i have now errors about unknow modules, and so unknow properties/functions, and so on and so forth...

So i create a new empty project, and try steps of @mjbvz, here the result :

![image](https://user-images.githubusercontent.com/38319680/41259969-d1788fd0-6dd5-11e8-82f2-270e55657bc7.png)

[ti-22792.log](https://github.com/Microsoft/vscode/files/2091928/ti-22792.log)

I see thoses lines but don't know if it's a sign of error or not :

![image](https://user-images.githubusercontent.com/38319680/41260260-03b59e10-6dd7-11e8-89b9-6b784f2531f2.png)

I can private send you tsserver.log if needed.

Thanks !

**Comment by mjbvz** [comment] 2018-06-12 02:00
@xxDukeMCxx yes if you can please sent me the logs: matb AT microsoft.com

This issue likely resolves itself because automatic types accession (which is how we get the typings files that provide intellisense for node) failed on its first attempt but then succeeded on the next attempt. Once it succeeds, it will use the cached types so you should not see this failure again

**Comment by xxDukeMCxx** [comment] 2018-06-12 21:36
@mjbvz have sent you this morning logs, hope this can help.
After multiple reboot, etc. the problem is always present.
So i looked log in detail, and make somes tests with a new simple project node & express only.

==> it's like LOG are lying.

- 1st I cleared the typescript directory :
![image](https://user-images.githubusercontent.com/38319680/41318144-ae8d2900-6e97-11e8-9a3c-75c5ad06217c.png)

- 2nd i open my project with VSCODE
The directory is populated with 
![image](https://user-images.githubusercontent.com/38319680/41318212-d6b8edf6-6e97-11e8-8bed-8c19a8bbc39b.png)
and
![image](https://user-images.githubusercontent.com/38319680/41318226-df8f9844-6e97-11e8-995f-0928ff862752.png)

go to the TS log :
first, log say this
![image](https://user-images.githubusercontent.com/38319680/41318273-0647727c-6e98-11e8-8c17-ff2cfbe47a76.png)
that's true, "types-registry" is well installed.

more later, log say :
![image](https://user-images.githubusercontent.com/38319680/41318316-3d776888-6e98-11e8-975b-d8ed8e70a15b.png)
that's true, my project use Node and Express, so need this.
In the package.json  they have been well added :
![image](https://user-images.githubusercontent.com/38319680/41318349-605c70d2-6e98-11e8-88b5-7edabc54d1cc.png)
![image](https://user-images.githubusercontent.com/38319680/41318365-6a7e84c4-6e98-11e8-833f-bf6dcfb26205.png)

back to the log, the log say :
![image](https://user-images.githubusercontent.com/38319680/41318431-96a9b424-6e98-11e8-8f20-9dea46f546d8.png)
But that's like a lie : nothing was installed, look at the directory :
![image](https://user-images.githubusercontent.com/38319680/41318467-ae363bc6-6e98-11e8-9220-4410db7ee4f0.png)

and so the problem is present.

- third, now if i just manually launch npm install in the type definition directory :
![image](https://user-images.githubusercontent.com/38319680/41318508-d0f070be-6e98-11e8-9bcb-39eda8cf9502.png)

check the directory :
![image](https://user-images.githubusercontent.com/38319680/41318517-dbcfb328-6e98-11e8-92ea-43ad55307585.png)
yep, all is here.

check by restarting VSCODE : VSCODE now work.

So it seem that something go wrong when VSCODE / TS try to install the type.
Don't know how to go further in investigation.

Thanks !

**Comment by xxDukeMCxx** [comment] 2018-06-12 22:47
Seem's to be NPM related, so i added a few log in my npm.cmd
the strange thing is npm said that he audit the packages, but never said he installed them :
![image](https://user-images.githubusercontent.com/38319680/41320639-dd4adcd4-6ea0-11e8-9fe8-4c23b5483b5e.png)

**Comment by xxDukeMCxx** [comment] 2018-06-12 23:08
sorry for that multiples answers... but now i found that when VSCODE launch npm for installing Types Definitions, the NODE_ENV variable is set to "production". So npm doesn't install the DEVDependencies. Or all the type dependencies are set as DevDepencies :
![image](https://user-images.githubusercontent.com/38319680/41321788-c619d4ca-6ea5-11e8-9b4b-6ef58016e388.png)

Do you know why VSCODE launch NPM with NODE_ENV environnement set to "production" ?
On my system i haven't this environemment variable set :
![image](https://user-images.githubusercontent.com/38319680/41321830-052b626e-6ea6-11e8-849e-ec589eab2809.png)

**Comment by mjbvz** [comment] 2018-06-20 20:55
@FabriceTheMan Are you still seeing this issue, or was it a transient failure?

@xxDukeMCxx The npm command we run should only be for automatic typings acquisition. This installs typings into a global cache and is separate from your local type dependencies. Did you run `npm install` in your workspace to install the types dev dependencies?

**Comment by xxDukeMCxx** [comment] 2018-06-22 10:53
@mjbvz hi, made more test today and saw that an extension was the problem (Import Cost). By disabling it the problem is resolved for me. But i think TS global cache packaqe downloading script should have some protection, like locally set NODE_ENV to "dev" before launching the 'npm install' command, and after downloading finsihed, unset the localy NODE_ENV global environnement variable.

**Comment by mjbvz** [comment] 2018-06-25 20:47
Closing this issue as transient. @FabriceTheMan let me know if you still see it in insiders with all extensions disiabled

**Closed by mjbvz** 2018-06-25 20:47 UTC
Labels: javascript, needs more info
