### ISSUE TITLE
macOS - cmd + h does not work (to hide the app) when in Markdown Preview

### ISSUE THREAD

**Issue by anadin** [microsoft/vscode#110836] opened 2020-11-18 02:31 UTC
Issue Type: <b>Bug</b>

Start a new markdown file
Enter any text
cmd+shift+p and choose Markdown: Open Preview

If the Markdown preview editor is in focus, cmd+h has no affect on VSCode

If the original file editor is in focus then cmd+h works

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 9|
|Memory (System)|32.00GB (2.63GB free)|
|Process Argv|--crash-reporter-id a3940467-7df9-4f9f-a518-aa568eb4e1b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.4.0
shaderlabvscodefree|aml|1.2.0
vscode-subtitles|ast|0.3.3
code-gnu-global|aus|0.2.2
spellright|ban|3.0.52
regex|chr|0.2.0
native-ascii-converter|cwa|1.0.8
transformer|dak|1.9.0
githistory|don|0.6.14
xml|Dot|2.5.1
gitlens|eam|11.0.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
json-pretty-printer|eus|1.1.0
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.1
vdf|GEE|0.0.6
todo-tree|Gru|0.0.188
haxe-hl|Hax|1.1.1
blender-development|Jac|0.0.12
svn-scm|joh|2.13.3
roslynator|jos|3.0.1
swift|Kas|0.2.0
electron-debug|kod|18.11.1
kha|kod|20.4.0
kha-extension-pack|kod|20.2.2
krafix|kod|18.7.1
krom|kod|20.1.0
krom-debug|kod|20.6.0
vscode-simple-icons|Lau|1.13.5
vscode-regexp-preivew|le0|0.0.3
restructuredtext|lex|129.0.0
vs-color-picker|lih|1.0.0
rainbow-csv|mec|1.7.1
render-crlf|med|1.5.16
vscode-clang|mit|0.2.3
csharp|ms-|1.23.6
python|ms-|2020.11.358366026
vscode-pylance|ms-|2020.11.1
jupyter|ms-|2020.11.358541065
vscode-ai|ms-|0.6.16
azure-account|ms-|0.9.4
cpptools|ms-|1.1.1
mono-debug|ms-|0.16.2
vscode-react-native|msj|1.1.1
easyzoom|Nab|0.1.0
vshaxe|nad|2.21.4
color-highlight|nau|2.3.0
subtitles-editor|pep|1.0.4
seti-icons|qin|0.1.3
vscode-sort-json|ric|1.18.1
code-settings-sync|Sha|3.4.3
json-schema-validator|tbe|0.1.0
best-light-themes-pack|the|1.0.2
cmake|twx|0.0.17
sort-lines|Tyr|1.9.0
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
haxe-checkstyle|vsh|1.6.1
haxe-debug|vsh|1.2.3
haxe-extension-pack|vsh|1.3.0
hxcpp-debugger|vsh|1.2.4
vscode-todo-highlight|way|1.0.4
codedox|wig|1.3.1
markdown-pdf|yza|1.4.4
propertylist|zho|0.0.2

(18 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2020-11-18 04:06
What do your keybindings show for Cmd+h?

Does the problem also happen if you run the command to reload with all extensions disabled?

**Comment by anadin** [comment] 2020-11-18 05:30
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/2351943/99487700-ac813b00-29b2-11eb-998e-c3f83ea9d1d7.png">

Sorry I should have mentioned I had already checked the keybindings.

Disabling all extensions does not change the behaviour.

**Comment by mjbvz** [comment] 2020-11-19 20:23
Duplicate of #71800

**Closed by mjbvz** 2020-11-19 20:23 UTC
