### ISSUE TITLE
Inconsistent suggest default across languages/extensions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74054] opened 2019-05-21 10:42 UTC
How IntelliSense works out of the box differs between languages (feature are owners?) and I think that's confusing. The following concepts/styles exist

* `accept on commit character` - A completion is inserted when a character is being pressed, e.g. `;` accept a completion *and* inserts that character. Extensions define what characters accept a completion and the setting `acceptSuggestionOnCommitCharacter` (default `true`) enables/disables this
* `snippet mode on accept` - When a suggestion is accepted, snippet mode is entered. This can be simple, e.g only placing the cursor, or complex by defining multiple tab stops
* `re-trigger on accept` - When a suggestion is accepted, suggest is invoked again. This doesn't exist as a concept in VS Code itself but extension achieve this via the accept-command API. If this becomes/is(?) popular we should consider making this also a concept in VS Code itself. 

|   | accept on commit character  | snippet mode on accept  |  re-tigger on accept |
|---|---|---|---|
| JS/TS  | yes  | disabled (1)  | no support  |
| JSON  | no support | yes  | ?  |
| CSS et al | no support | yes  | yes (value sets)  |
| HTML  | no support | yes (2)  | yes (value sets)  |
|  C# |  yes | no  | ?  |
| Python  | ?  | ?  | ?  |

1. JS/TS has the setting `completionFunctionCalls` that enters snippet mode
2. HTML has simple snippet completions like `<div>$0</div>` (position cursor only) but also complex one like `id="$1"$0`

**Comment by mjbvz** [comment] 2019-05-21 18:18
I think allowing languages/extensions to have different completions behavior makes sense because each language comes with different expectations. CSS and json for example involve typing out a lot of names that do not have suggestions (such as referencing a class defined in your html or js)

One idea would be to standardize some settings for snippets and re-trigger, the way we already do for `editor.acceptSuggestionOnCommitCharacter`

**Comment by jrieken** [comment] 2019-05-22 07:24
> Commit characters would not make sense in those cases

Disagree - I think `:` and `,` would be great commit characters, e.g I type `depe` and `:` to have `"dependencies": "|"`

**Comment by aeschli** [comment] 2019-10-10 10:12
@jrieken Using commit character definitely makes sense. I can add `:` for JSON and CSS when completing properties, `;`  in CSS for statement completion,`=` for attribute competion. But I'm not sure it serves the purpose that users are less confused to know what the possible competition characters are for a specific proposal. To fix that we probably need some UI affordance.

As for retrigger, I think it's goodness and I agree we should make it 'official' by having a 'retrigger' flag on the completion proposal.

Created https://github.com/microsoft/vscode-css-languageservice/issues/182
https://github.com/microsoft/vscode-json-languageservice/issues/44
https://github.com/microsoft/vscode-html-languageservice/issues/73

**Comment by Gama11** [comment] 2019-10-10 12:59
We also use `CompletionItem.command` in some cases in the Haxe extension. However, not just for retriggering completion, but also for triggering _signature help_ (`"editor.action.triggerParameterHints"`). Should that be included in an API as well, or continue to be handled with commands?

**Comment by jrieken** [comment] 2019-10-10 13:15
I like that @Gama11. Triggering signature is indeed very similar and something that we should have on our radar.

**Comment by mjbvz** [comment] 2019-10-21 21:09
@jrieken Duplicate of #10266?

**Comment by jrieken** [comment] 2019-10-22 07:04
Not really, this is about writing down all the different behaviours and the attempt to align them or at least align the defaults, like JSON defaults to inserting snippets, TS doesn't etc etc

**Closed** 2020-11-10 11:07 UTC
Labels: *out-of-scope, polish, suggest, under-discussion
