### ISSUE TITLE
Strange new border on the activity bar

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#96082] opened 2020-04-24 18:06 UTC
I believe this appeared in today's insiders
![image](https://user-images.githubusercontent.com/641685/80243165-aef5ff00-8634-11ea-963a-6744a66908b5.png)

**Comment by rebornix** [comment] 2020-04-24 20:29
duplicate of https://github.com/microsoft/vscode/issues/95858 ?

**Closed** 2020-04-24 20:34 UTC
Labels: *duplicate
