### ISSUE TITLE
Store split pane view state globaly, not per workspace

### ISSUE THREAD

**Issue by thiagolunardi** [Microsoft/vscode#36199] opened 2017-10-13 07:33 UTC
Very often I need to resize the tools views width and height. I like to have then thin, and keep some views collapsed - like Open Editors - and the File Explorer fully expanded as possible.  Also, I like to keep Terminal with around 20 lines high.

So, every time I start a new VSCode Windows I need to resize everything again. Will be really nice if there is a way to Save my defined windows/views positions and sizing design, and VSCode remember that when it is opened again.

**Comment by isidorn** [comment] 2017-10-13 08:30
We always try to keep all the view state persisted. However there might be some corner case where this is not the case.
So please provide exact reproducable steps how to get into this state where view state is not preserved.

**Comment by thiagolunardi** [comment] 2017-10-13 09:21
New info: the design changes if I open a different folder. If it's the same, it remember the last design, working as expected. But if it opens another Folder, it's like a fresh opening.

- Fresh start:

![image](https://user-images.githubusercontent.com/5428523/31539143-008ae1ba-b008-11e7-984c-754544a47318.png)

- Design changes:

![image](https://user-images.githubusercontent.com/5428523/31539167-19071916-b008-11e7-8f48-2a016951932b.png)

- Close VSCode
- Open a different folder

![image](https://user-images.githubusercontent.com/5428523/31539292-7776ed1e-b008-11e7-8558-aaaa18798822.png)

- The file explorer is shrink-ed again.

**Comment by isidorn** [comment] 2017-10-13 09:36
This is designed behavior since we store the state per workspace.
We choose this because we believe that people setup their view state per a workspace, and each workspace might require a different setup.

@joaomoreno  correct me if I am wrong here. I can see myself leaning towards the user proposal to store this state globaly

**Comment by joaomoreno** [comment] 2017-10-16 12:39
@isidorn Please ping @sandy081

**Comment by sandy081** [comment] 2017-10-16 16:47
@isidorn Yes, View state is stored for workspace. I see this as a different requirement. Users would like to disable a view contribution globally. Here is the issue tracking this #35462.

Marking this as a duplicate of #35462

**Closed by sandy081** 2017-10-16 16:47 UTC
Labels: workbench
