### ISSUE TITLE
No indicator whether cell is running in Interactive window

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#129269] opened 2021-07-23 19:52 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Create a Pythno file with the following code:
```
# %%
import time
time.sleep(10000)
```

2. Run the above cell
I can see the interacgive window started & ther'es a collapsed cell with the line `import time`
That's it.
I thought it was stuck , but after expanding the cell I found the code is still running.
Note: I"m not running `time.sleep`, but have some other complex code (for me it stuck on the imports for some larger packages like scikitlearn, pandas, etc)
& then when running some otehr cells noticed the same thing.

I'm assuming users too would run into the same issue, issue of not knowing what's going on as there's no UI to indicate that cells are running.

@rebornix @joyceerhl /cc

**Comment by joyceerhl** [comment] 2021-07-23 20:01
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/6473

**Closed** 2021-07-23 20:21 UTC
Labels: *duplicate
