### ISSUE TITLE
Multiline console messages are not shown in Debug Console.

### ISSUE THREAD

**Issue by MicahZoltu** [Microsoft/vscode#51008] opened 2018-06-02 11:53 UTC
- VSCode Version: 1.23.1
- OS Version: Windows 10

Steps to Reproduce:

`file.js`
```javascript
console.error(new Error('A\nB'))
```
`launch.json`
```json
{
    "type": "node",
    "request": "launch",
    "name": "File",
    "args": [ "${workspaceFolder}/file.js", ],
}
```
Start debugging via F5 or command pallet or debug panel.

### Expected Output:
```
Error: A
B
    at Object.<anonymous> (C:\Users\micah\Source\test\file.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

### Actual Output:
```
> Error: A
```

This would be fine if the little expansion arrow resulted in showing the rest of the error.  However, the expansion arrow doesn't appear to do anything.

The bug appears to be with any object expansion as `console.log({ a: 'hello', b: 'goodbye'})` also has an expansion arrow that doesn't do anything.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2018-06-21 08:21
Works fine for me in latest vscode insiders.
Can you reproduce with vscode insiders? https://code.visualstudio.com/insiders/

![screen shot 2018-06-21 at 10 20 53](https://user-images.githubusercontent.com/1926584/41706747-d89f3c46-753c-11e8-8acf-377d71287afa.png)

**Comment by MicahZoltu** [comment] 2018-06-21 10:11
Unknown.  Installing Insider is beyond my level of willingness to troubleshoot/report bugs.  😬 

I can confirm that it is still a bug as of v1.24.1.  Are you able to reproduce the bug in that version but not Insider (following the instructions)?

**Comment by MicahZoltu** [comment] 2018-06-21 10:12
Note: I just realized the instructions didn't specifically say to debug using VSCode.  The problem does _not_ reproduce when you just do `node file.js` from a powershell terminal.  Will update original report.

**Comment by isidorn** [comment] 2018-06-21 11:59
Yeah I can reproduce in stable, so since I can not repro in insiders it seems to be fixed in latest. Closing

**Closed by isidorn** 2018-06-21 11:59 UTC
Labels: debug-console, javascript, needs more info
