### ISSUE TITLE
"initialize repository" button is shadowed by files from other repository

### ISSUE THREAD

**Issue by swiperthefox** [microsoft/vscode#127694] opened 2021-06-30 18:49 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- Version: 1.57.1
- OS: Linux x64 5.10.0-6-amd64

Steps to Reproduce:

1. Make an new folder: `mkdir testing`
2. Open it in VS Code: `code testing`
  There is an "Initialize repository" button in git view, since there no repository is created yet.
3. Open a file from other repository
4. In the git view, you can only manage the above repository, and the "Initialize repository" button disappeared, changes of current working directory does not show in git view (which is correct, since the working directory does not belong to that repository).

Expected behavior:

The git view should show "multiple" repository. In this case, one of them is an non-existing one with "Initialize repository" button in it.

**Comment by tim-elmer** [comment] 2022-06-17 21:12
+1 on
```
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043
```

Closing and reopening the affected instance jettisons the phantom repository.

**Comment by lszomoru** [comment] 2022-12-13 13:25
Couple of things to call out:
1) At the moment VS Code views are implemented so that they are either showing a list/treeview or welcome content (in this case it is the "Initialise Repository") button. As soon as a repository is being discovered, the welcome content is hidden as the view will show the discovered repository. This behaviour is by design and I do not believe there are plans to change it.
2) One can control repository discovery using the `git.autoRepositoryDetection` setting. In case you do not want VS Code to discover repositories "outside" the current folder/workspace you can change the value of this setting to `subFolders`.

I will go ahead and close this issue but please feel free to reopen it in case you have further questions or concerns. Thanks!

**Closed by lszomoru** 2022-12-13 13:25 UTC
Labels: bug, git
