### ISSUE TITLE
Tabbing through elements on extension pages in the VS Code marketplace lands on non-interactive elements

### ISSUE THREAD

**Issue by andyleejordan** [microsoft/vscode#206568] opened 2024-02-29 21:19 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.87.0 (user setup)
- OS Version: Windows_NT arm64 10.0.22631

Steps to Reproduce:

1. Open _any_ extension in the VS Code marketplace (that is, the "Extensions" view within VS Code itself)
2. Using the keyboard to navigate, press "tab" to cycle through the elements of the previewed extension
3. The accessibility issue is that the focus will land on non-interactive elements (i.e. things you wouldn't click with the mouse and don't have a description read out) such as the extension's logo image and download count

This is not my area of expertise. I am relaying an internal accessibility bug filed against me as the PowerShell extension maintainer. I have made it very clear to the team filing said bug that this is a _generic issue_ with _all_ extensions in the marketplace, not just the PowerShell extension, as the problem exists within the Extensions view of VS Code. I'm attaching their latest screen capture, but manually verified it reproduces as they described with the version of VS Code and Windows I posted above. I _think_ the best fix would be that "tab" navigation never lands on the logo (as there is no way to provide a screen-reader a description to read out, since every extension would need to describe their associated image, and there's no process for publishing that information with the extension such as in is the manifest), and if it is to continue to land on on the non-clickable download count, it should read it out loud (it might be, I didn't test, again not my bug or area of expertise). But I'm not sure, please work with the team that actually filed this and is using me as a messenger, e.g. @Latha2564.

Here is the internal bug: https://msazure.visualstudio.com/One/_workitems/edit/9128065 that has been open since June 2021. Why the filers won't assign it to the VS Code team internally, I don't know. Here is the previously filed issue: https://github.com/microsoft/vscode/issues/135448 that was accidentally closed by @isidorn because the filer did not make it clear enough that this is a VS Code issue in general, so it was closed and redirected back to me as an extension maintainer. I can't fix this though, it's in VS Code.

Here's their latest screen capture:

https://github.com/microsoft/vscode/assets/2226434/cf002576-8685-406d-ac9e-b2d63356f971

**Comment by meganrogge** [comment] 2024-02-29 22:09
When it lands on things and a screen reader is enabled, those get read out. This is working as designed. I'd suggest closing that work item.

https://github.com/microsoft/vscode/assets/29464607/c3d0dce7-813c-47ee-b648-fe460b883f39

**Closed by meganrogge** 2024-02-29 22:09 UTC
Labels: new release

**Comment by andyleejordan** [comment] 2024-02-29 22:13
@meganrogge what is read out for the extension logo?

**Comment by meganrogge** [comment] 2024-02-29 22:14
focus does not move to the extension logo for me

**Comment by meganrogge** [comment] 2024-02-29 22:15
it moves to the editor, which is as expected/by design

**Comment by meganrogge** [comment] 2024-02-29 22:17
when you enable a screen reader, what do you hear when that happens?

**Comment by andyleejordan** [comment] 2024-02-29 22:20
https://github.com/microsoft/vscode/assets/2226434/9af2c716-eb7e-4b18-b00f-3c59cf84aca3

Uhh let me try to find a screen reader. Also:
> I'd suggest closing that work item.
I've told the filers as clearly as possible that a) they're testing VS Code, not my extension and so b) need to work with your team, because c) I _have_ closed it and they just keep adding videos of "still broken" because I don't think they understand what they're even testing.

**Comment by andyleejordan** [comment] 2024-02-29 22:21
Ahh, that "somewhere" I couldn't see (and I think is why they keep opening this bug) with a screen-reader enabled is an invisible box (highlighted when the screen reader is on) that just says "document."

**Comment by meganrogge** [comment] 2024-02-29 22:26
Yep, that indicates that the editor is focused to a screen reader user. like I said, I believe this is working as designed.

**Comment by meganrogge** [comment] 2024-02-29 22:27
Yes, sometimes they don't know what is a real vs fake bug 😄

**Comment by meganrogge** [comment] 2024-02-29 22:28
Commented and moved that issue to `resolved`
