### ISSUE TITLE
Provides completions at inappropriate locations

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#49651] opened 2018-05-10 21:58 UTC
Issue Type: <b>Feature Request</b>

* Paste:
```ts
const x = { newLine: 0 };
x.new
```
* Put cursor after `new` and request completions.
* First completion is:
```ts
const x = { newline: 0 };
x.const name = new type(arguments);
```
(This will sometimes happen when typing `new` and hitting enter to complete, but sometimes that results in `newline` as expected.)

This isn't an appropriate location for that completion since we're not at a new statement position. The ts completions API provides a `CompletionInfo` interface that would provide an `isGlobalCompletion` flag to tell an editor that it's OK to provide that kind of completion.
Currently `CompletionsResponse` in `protocol.ts` only includes a `CompletionEntry[]`, but it might be possible to add a new property to that interface.

VS Code version: Code - Insiders 1.24.0-insider (25aab64fccf650e2be3d19d613e51b26100300a8, 2018-05-10T05:11:35.028Z)
OS version: Linux x64 4.13.0-37-generic

**Comment by mjbvz** [comment] 2018-05-23 18:44
Duplicate of #1304. Caused by snippets.

The typescript extension currently can't control when these snippets are or are not contributed

**Closed by mjbvz** 2018-05-23 18:44 UTC
