### ISSUE TITLE
Launch.json Configurations Not Appearing In Dev Container

### ISSUE THREAD

**Issue by connor981332** [microsoft/vscode#179058] opened 2023-04-03 21:06 UTC
Type: <b>Bug</b>

When you open a dev container and click the "Run and Debug" button, the various configurations (i.e. scripts) from the launch.json file do not appear.

I have tested and found this bug in version 1.77 and 1.78 (insider).

Reverting to version 1.73 fixes the issue.

We are experiencing this issue in all our Node Express apps. We have not tested other dev containers with other types of apps.

VS Code version: Code - Insiders 1.78.0-insider (Universal) (2da5a0024fe2ca407f741f19340f1a10f4d692af, 2023-04-03T05:23:48.301Z)
(I have also encountered this bug on the NON insider 1.77 build)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes
Remote OS version: Linux arm64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 9, 8|
|Memory (System)|32.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Accounts API @ desktop-linux|
|OS|Linux arm64 5.15.49-linuxkit|
|CPUs|unknown (5 x 0)|
|Memory (System)|11.68GB (9.74GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.289.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.4.0
prettier-vscode|esb|9.10.4
rest-client|hum|0.25.1
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
live-server|ms-|0.4.7
code-spell-checker|str|2.20.4
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes627cf:30244335
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30659908
pythonb192:30661256
defaultazurewalk:30687958
pythonms35:30671666
0bg3d529:30680467
ecj1e332:30687743
pythonclientmv:30700173

```

</details>

**Comment by connor981332** [comment] 2023-04-03 21:16
Reverting to version 1.76.2 also fixed the issue. There seems to be evidence that dev container extensions in general are impacted by this bug, which seems to be introduced in version 1.77

**Comment by raysuelzer** [comment] 2023-04-03 21:55
Do you see any errors in the window output?

Likely related to: https://github.com/microsoft/vscode/issues/178748

**Comment by connor981332** [comment] 2023-04-03 22:05
Nope, I don't see any errors.

On the insider version (1.78) I don't even see any buttons in the "run and debug" section.

In the production version (1.77) I see two buttons, "JavaScript Debug Terminal" and "Debug URL", but neither of them do anything.
![Screenshot 2023-04-03 at 4 02 21 PM](https://user-images.githubusercontent.com/43152960/229637569-0f359a9f-6eb8-45dc-8fad-2f02a67fd753.png)


When you click them, it says at the bottom  something about extensions and then there are spinning arrows (as if it were loading something) and then the message goes away and no errors pop up.

**Comment by connor981332** [comment] 2023-04-03 22:07
This is what the "Run and Debug" section looks like after reverting to version 1.76.2

![Screenshot 2023-04-03 at 4 06 19 PM](https://user-images.githubusercontent.com/43152960/229637754-63210682-be82-4275-8251-15d1277fc205.png)

This is what it's supposed to look like.

**Comment by connor981332** [comment] 2023-04-03 22:12
Although I am on an M1 Mac, my coworker on an intel mac experienced this same issue on the same VS code versions.

**Comment by roblourens** [comment] 2023-04-04 03:17
Yes, please check for errors, follow https://github.com/microsoft/vscode/issues/178748, or share your dev container configuration for me to try

**Comment by connor981332** [comment] 2023-04-04 16:41
`2023-04-04 10:36:30.190 [info] Electron sandbox mode is enabled!
2023-04-04 10:36:30.197 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-04-04 10:36:30.197 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-04-04 10:36:32.972 [info] [perf] Render performance baseline is 18ms
2023-04-04 10:36:47.180 [info] Electron sandbox mode is enabled!
2023-04-04 10:36:47.192 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-04-04 10:36:47.192 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-04-04 10:36:47.732 [info] Invoking resolveAuthority(dev-container)...
2023-04-04 10:36:47.732 [info] [LocalProcess0][resolveAuthority(dev-container,1)][0ms] obtaining proxy...
2023-04-04 10:36:47.732 [info] [LocalProcess0][resolveAuthority(dev-container,1)][0ms] invoking...
2023-04-04 10:36:48.735 [info] [LocalProcess0][resolveAuthority(dev-container,1)][1003ms] waiting...
2023-04-04 10:36:49.733 [info] [LocalProcess0][resolveAuthority(dev-container,1)][2000ms] waiting...
2023-04-04 10:36:50.270 [info] [LocalProcess0][resolveAuthority(dev-container,1)][2538ms] returned 127.0.0.1:33795
2023-04-04 10:36:50.271 [info] resolveAuthority(dev-container) returned '127.0.0.1:33795' after 2538 ms
2023-04-04 10:36:50.271 [info] Creating a socket (renderer-Management-f59af3fb-3bc9-4df7-b16d-8d556b7d9b8d)...
2023-04-04 10:36:50.272 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771)...
2023-04-04 10:36:50.278 [error] [File Watcher (node.js)] Refusing to watch /Volumes/Code/work/accounts-api/.devcontainer/devcontainer.json for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
2023-04-04 10:36:50.431 [info] Creating a socket (renderer-Management-f59af3fb-3bc9-4df7-b16d-8d556b7d9b8d) was successful after 160 ms.
2023-04-04 10:36:50.669 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771) was successful after 398 ms.
2023-04-04 10:36:51.375 [info] [perf] Render performance baseline is 18ms
2023-04-04 10:36:51.462 [error] [Extension Host] Error: Error relocating /vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/node_modules/spdlog/build/Release/spdlog.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.m._load (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:14199)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/node_modules/spdlog/index.js:3:35)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.m._load (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:14199)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at i (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:5:98)
    at n.load (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:4:1651)
    at _.load (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:3:9105)
    at u (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:5:9325)
    at Object.errorback (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:5:9444)
    at _.triggerErrorback (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:3:9399)
    at /vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:3:9150
    at n.load (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:4:1668)
    at _.load (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:3:9105)
    at u (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:5:9325)
    at h._loadModule (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:5:9453)
    at h._resolve (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:6:452)
    at h.defineModule (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:5:5548)
    at h._relativeRequire (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:5:6172)
    at e (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/loader.js:5:8503)
    at R.C (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:8815)
    at new Promise (<anonymous>)
    at R (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:8795)
    at D.n (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:9925)
    at new D (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:9795)
    at P.m (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:106:954)
    at P.createLogger (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:5469)
    at new P (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:91:13841)
    at S.j (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:1296)
    at /vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:3032
    at z.a (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:66:48073)
    at z.get value [as value] (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:66:48227)
    at Object.get (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:3438)
    at new u (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:115:1150)
    at c (/vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:18641)
2023-04-04 10:37:01.219 [error] Error while registering log channel vscode-remote://dev-container%2B7b22686f737450617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d617069222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/node/.vscode-server-insiders/data/logs/20230403T150145/remoteagent.log Timed out while waiting for file to be created
2023-04-04 10:37:01.219 [error] Error while registering log channel vscode-remote://dev-container%2B7b22686f737450617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d617069222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/node/.vscode-server-insiders/data/logs/20230403T150145/remoteptyhost.log Timed out while waiting for file to be created
2023-04-04 10:37:01.764 [error] Error while registering log channel vscode-remote://dev-container%2B7b22686f737450617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d617069222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f566f6c756d65732f436f64652f776f726b2f6163636f756e74732d6170692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/node/.vscode-server-insiders/data/logs/20230403T150145/exthost4/remoteexthost.log Timed out while waiting for file to be created
2023-04-04 10:37:11.789 [info] [remote-connection][ExtensionHost][2898e…][reconnect] received socket timeout event (unacknowledgedMsgCount: 58, timeSinceOldestUnacknowledgedMsg: 20331, timeSinceLastReceivedSomeData: 20300).
2023-04-04 10:37:11.790 [info] [remote-connection][ExtensionHost][2898e…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-04-04 10:37:11.794 [info] [remote-connection][ExtensionHost][2898e…][reconnect] resolving connection...
2023-04-04 10:37:11.794 [info] [remote-connection][ExtensionHost][2898e…][reconnect] connecting to 127.0.0.1:33795...
2023-04-04 10:37:11.794 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771)...
2023-04-04 10:37:11.988 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771) was successful after 198 ms.
2023-04-04 10:37:12.008 [info] [remote-connection][ExtensionHost][2898e…][reconnect] reconnected!
2023-04-04 10:37:32.015 [info] [remote-connection][ExtensionHost][2898e…][reconnect] received socket timeout event (unacknowledgedMsgCount: 58, timeSinceOldestUnacknowledgedMsg: 20005, timeSinceLastReceivedSomeData: 20005).
2023-04-04 10:37:32.044 [info] [remote-connection][ExtensionHost][2898e…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-04-04 10:37:32.044 [info] [remote-connection][ExtensionHost][2898e…][reconnect] resolving connection...
2023-04-04 10:37:32.044 [info] [remote-connection][ExtensionHost][2898e…][reconnect] connecting to 127.0.0.1:33795...
2023-04-04 10:37:32.044 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771)...
2023-04-04 10:37:32.183 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771) was successful after 138 ms.
2023-04-04 10:37:32.195 [info] [remote-connection][ExtensionHost][2898e…][reconnect] reconnected!
2023-04-04 10:37:52.198 [info] [remote-connection][ExtensionHost][2898e…][reconnect] received socket timeout event (unacknowledgedMsgCount: 65, timeSinceOldestUnacknowledgedMsg: 20003, timeSinceLastReceivedSomeData: 20003).
2023-04-04 10:37:52.199 [info] [remote-connection][ExtensionHost][2898e…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-04-04 10:37:52.199 [info] [remote-connection][ExtensionHost][2898e…][reconnect] resolving connection...
2023-04-04 10:37:52.199 [info] [remote-connection][ExtensionHost][2898e…][reconnect] connecting to 127.0.0.1:33795...
2023-04-04 10:37:52.199 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771)...
2023-04-04 10:37:52.381 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771) was successful after 183 ms.
2023-04-04 10:37:52.396 [info] [remote-connection][ExtensionHost][2898e…][reconnect] reconnected!
2023-04-04 10:38:12.398 [info] [remote-connection][ExtensionHost][2898e…][reconnect] received socket timeout event (unacknowledgedMsgCount: 70, timeSinceOldestUnacknowledgedMsg: 20002, timeSinceLastReceivedSomeData: 20002).
2023-04-04 10:38:12.399 [info] [remote-connection][ExtensionHost][2898e…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-04-04 10:38:12.400 [info] [remote-connection][ExtensionHost][2898e…][reconnect] resolving connection...
2023-04-04 10:38:12.400 [info] [remote-connection][ExtensionHost][2898e…][reconnect] connecting to 127.0.0.1:33795...
2023-04-04 10:38:12.401 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771)...
2023-04-04 10:38:12.597 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771) was successful after 197 ms.
2023-04-04 10:38:12.615 [info] [remote-connection][ExtensionHost][2898e…][reconnect] reconnected!
2023-04-04 10:38:32.620 [info] [remote-connection][ExtensionHost][2898e…][reconnect] received socket timeout event (unacknowledgedMsgCount: 102, timeSinceOldestUnacknowledgedMsg: 20004, timeSinceLastReceivedSomeData: 20004).
2023-04-04 10:38:32.641 [info] [remote-connection][ExtensionHost][2898e…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-04-04 10:38:32.641 [info] [remote-connection][ExtensionHost][2898e…][reconnect] resolving connection...
2023-04-04 10:38:32.641 [info] [remote-connection][ExtensionHost][2898e…][reconnect] connecting to 127.0.0.1:33795...
2023-04-04 10:38:32.641 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771)...
2023-04-04 10:38:32.793 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771) was successful after 151 ms.
2023-04-04 10:38:32.804 [info] [remote-connection][ExtensionHost][2898e…][reconnect] reconnected!
2023-04-04 10:38:52.805 [info] [remote-connection][ExtensionHost][2898e…][reconnect] received socket timeout event (unacknowledgedMsgCount: 126, timeSinceOldestUnacknowledgedMsg: 20001, timeSinceLastReceivedSomeData: 20001).
2023-04-04 10:38:52.823 [info] [remote-connection][ExtensionHost][2898e…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-04-04 10:38:52.823 [info] [remote-connection][ExtensionHost][2898e…][reconnect] resolving connection...
2023-04-04 10:38:52.823 [info] [remote-connection][ExtensionHost][2898e…][reconnect] connecting to 127.0.0.1:33795...
2023-04-04 10:38:52.823 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771)...
2023-04-04 10:38:52.997 [info] Creating a socket (renderer-ExtensionHost-2898e631-347b-4ca2-a43e-3b5e9c716771) was successful after 174 ms.
2023-04-04 10:38:53.009 [info] [remote-connection][ExtensionHost][2898e…][reconnect] reconnected!`

**Comment by connor981332** [comment] 2023-04-04 16:44
It looks like I'm getting a similar error as #178748

Namely, `[error] [Extension Host] Error: Error relocating /vscode/vscode-server-insiders/bin/alpine-arm64/2da5a0024fe2ca407f741f19340f1a10f4d692af-insider/node_modules/spdlog/build/Release/spdlog.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found`

**Comment by roblourens** [comment] 2023-04-04 17:40
Thanks, I will close it as a dupe of that issue, and hopefully also figure out why it's breaking the debug view

**Closed by roblourens** 2023-04-04 17:40 UTC
Labels: info-needed

**Comment by raysuelzer** [comment] 2023-04-04 18:48
> Thanks, I will close it as a dupe of that issue, and hopefully also figure out why it's breaking the debug view

I had the same issue actually, which is how I first noticed it. But, i wasn't sure it an issue with the debug view directly from my experience it seemed to be more of an IO issue where it could not create the file in a timely manner. I was able to get it running by manually creating the launch.json file on my host container.

**Comment by connor981332** [comment] 2023-04-10 17:33
@roblourens Thanks!
