### ISSUE TITLE
Sloppy Ctrl+Tab 

### ISSUE THREAD

**Issue by ja-94** [microsoft/vscode#90380] opened 2020-02-10 16:35 UTC
I have my keyboard shortcuts setup so that Ctrl+Tab switches between editors (Ctrl + Tab for workbench.action.nextEditor, Ctrl+Shift+Tab for workbench.action.previousEditor). 

Since the last update to VSCode, this seems to have stopped working properly.

Having one editor and one python interactive window, it succesfully switches from the editor to the python interactive window but then it gets stuck. I have to maintain Ctrl+Tab pressed for a while and at some point (randomly, it seems), it will switch back to the editor.

If it's of any help I'm running Ubuntu 18.04 on a T490s Thinkpad.

**Comment by JacksonKearl** [comment] 2020-02-10 17:03
@mjbvz related to issue where some keybindings don't always work in webview?

**Comment by ja-94** [comment] 2020-02-13 11:10
This is very annoying, any ideas of how to solve it?

**Comment by ja-94** [comment] 2020-02-13 11:13
I opened keyboard shortcuts to check again that my shortcuts make sense. If I have the keyboard shortcuts tab opened, the shortcut actually works. I can use Ctrl + Tab successfully to move between the other two tabs I have open.

**Comment by mjbvz** [comment] 2020-04-28 00:16
Duplicate of #86864

**Closed by mjbvz** 2020-04-28 00:16 UTC
Labels: webview
