### ISSUE TITLE
Double error decorations

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#69358] opened 2019-02-25 11:38 UTC
Not sure how I got two almost equal diagnostics but I think showing the actions two times isn't ideal

<img width="468" alt="screenshot 2019-02-25 at 11 58 57" src="https://user-images.githubusercontent.com/1794099/53334822-2d082a00-38fa-11e9-9ab7-1de66692a2fa.png">

**Comment by sandy081** [comment] 2019-02-25 11:50
Duplicate of https://github.com/Microsoft/vscode/issues/69327

**Closed** 2019-02-25 11:50 UTC
Labels: *duplicate
