### ISSUE TITLE
Perf issue when resizing panel next to editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83014] opened 2019-10-21 22:03 UTC
Issue Type: <b>Feature Request</b>

**Repo**
1. In the VS Code codebase, open an editor
1. Then resize the search resutls panel

**Bug**
This is super slow

![Screen Shot 2019-10-21 at 3 03 32 PM](https://user-images.githubusercontent.com/12821956/67246674-f4cad400-f413-11e9-867c-83fcf6de75f1.png)

[Profile-20191021T150302.json.txt](https://github.com/microsoft/vscode/files/3753054/Profile-20191021T150302.json.txt)

VS Code version: Code - Insiders 1.40.0-insider (82ca6ba87f450245f665ab7a5f3a686e2cd00045, 2019-10-21T05:39:31.415Z)
OS version: Darwin x64 18.7.0

**Comment by mjbvz** [comment] 2019-10-21 22:05
Oh wait, this is not specific to search results. Assigning better owner

**Comment by mjbvz** [comment] 2019-10-21 22:18
Tested with extensions disabled and still seeing choppy performance. Seems related to setting `"editor.wordWrap": "on"`

**Comment by alexandrudima** [comment] 2019-10-24 08:48
Duplicate of #21196

**Closed by alexandrudima** 2019-10-24 08:48 UTC
Labels: perf
