### ISSUE TITLE
OutputChannel  show didn' t working some time

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/vscode#113912] opened 2021-01-06 14:42 UTC
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

here my code :

```
let testOutputChannel: OutputChannel = window.createOutputChannel('Run  Test');

	context.subscriptions.push(commands.registerCommand('test.start', (uri : Uri) => {
		if (!uri && window.activeTextEditor) {
			uri = window.activeTextEditor.document.uri;
		}

		
		testOutputChannel.show();

                 ...
                 create a subprocess and do some append text
                 ..
	}));

```

Usually it is normal, but some time the  testoutputChannel didn't show automatically.
But when open the outputChannel manually， all appended output was there. it seams `show` didn't bring the channel to front and focus.

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment] 2021-01-06 15:38
This works for me. Can you reproduce with latest vscode insiders?
https://code.visualstudio.com/insiders/

**Comment by zhfnjust** [comment] 2021-01-07 04:56
> This works for me. Can you reproduce with latest vscode insiders?
> https://code.visualstudio.com/insiders/

yes, it works  most time

**Comment by isidorn** [comment] 2021-01-07 11:09
If you have reproducable steps that work all the time let me know and we can reopen this.
For now closing this
fyi @sandy081

**Closed by isidorn** 2021-01-07 11:09 UTC
Labels: needs more info, output
