### ISSUE TITLE
Add cursor at any position without needing spaces

### ISSUE THREAD

**Issue by YLiLarry** [microsoft/vscode#84277] opened 2019-11-08 15:41 UTC
I would like to request an addition "Add cursor at any position by inserting spaces" feature.

The current "Add cursor at any position feature" requires the place you insert the cursor to at least have space characters. I wonder if there is a way to truly add a cursor to any position. When there are no space characters between the end of that line and the cursor position, I'd like VSC to automatically insert spaces up to that cursor position?

A very frequent use case would be when you want to add a cursor directly above/below the current cursor, and by default, if the intended line is empty or does not have spaces to the cursor position, VSC would add the new cursor to the end of that line. This is not very convenient when you want to modify text/code formatted by columns, for example, a table-like text with some empty lines between rows. This causes the current adding a cursor to the line above/below feature only work blocks of rows where there is no empty line between them. With the requested feature, you can freely extend your cursor above/below across the empty lines. The requested feature would also work when the "trim trailing whitespaces on save" feature is enabled since VSC would insert the spaces for cursor extension purpose, and remove them on save.

**Comment by YLiLarry** [comment] 2019-11-08 15:44
This is different from #62679 in the way that, instead of **not selecting the line** that does not have enough spaces, I want to select the position directly under the cursor on that empty line, and spaces automatically inserted til that cursor position.

**Comment by alexandrudima** [comment] 2019-11-08 16:51
Duplicate of #13960

**Closed by alexandrudima** 2019-11-08 16:51 UTC
