### ISSUE TITLE
Hot exit: preserve files explorer state

### ISSUE THREAD

**Issue by Tarik02** [microsoft/vscode#128040] opened 2021-07-06 09:04 UTC
VSCode preserves list of open files, but it does not preserve files explorer state (collapsed folders).

**Comment by isidorn** [comment] 2021-07-27 09:26
It preserves it for me. 
I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Tarik02** [comment] 2021-07-27 16:11
@isidorn will try later. Could you try to reproduce it while using Remote Container (docker)?

**Comment by isidorn** [comment] 2021-07-27 16:26
Try later with insiders and let me know how it goes.

**Comment by Tarik02** [comment] 2021-07-28 06:52
> Try later with insiders and let me know how it goes.

Wow, it saves the state in Insiders version. Waiting for this to be merged to main branch.

**Comment by isidorn** [comment] 2021-07-28 07:51
There might be some extension which is breaking your flow. However since this works in insiders I am closing this issue

**Closed by isidorn** 2021-07-28 07:51 UTC
Labels: file-explorer, needs more info
