### ISSUE TITLE
autocomplete of npm package is jacked up

### ISSUE THREAD

**Issue by swilliams-a3digital** [Microsoft/vscode#54190] opened 2018-07-12 16:11 UTC
Issue Type: <b>Bug</b>

autocomplete is now doing this:
import { DateProvider } from '../../node_modules/@a3-digital/date-utils';

It should be doing this:
import { DateProvider } from '@a3-digital/date-utils';

The ../../node_modules stuff is jacked up and doesn't work.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 5|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_7972762|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
xml|Dot|2.3.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
json-tools|eri|1.0.2
terraform|mau|1.2.3
csharp|ms-|1.15.2
vscode-icons|rob|7.24.0
yo|sam|0.9.3
gitblame|wad|2.4.2
vscode-proto3|zxh|0.2.1

</details>

**Comment by mjbvz** [comment] 2018-07-12 19:46
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-12 19:46 UTC
Labels: typescript
