### ISSUE TITLE
Change multi line text search shortcut from ctrl+enter to shift+enter

### ISSUE THREAD

**Issue by csrapr** [microsoft/vscode#81426] opened 2019-09-25 10:24 UTC
In the latest update  (2019/09/25), the new multi line search feature was introduced, but the shortcut isn't the same as in every other app **where pressing the enter key sends the message**

For example in slack to create a new line you hold shift and press enter
Same thing in facebook messenger, whatsapp, steam, real time support chats (e.g. amazon), etc

I think VScode should follow the "standard" and change the key combination from ctrl+enter to shift+enter, to be in line with every other app

**Comment by rebornix** [comment] 2019-10-22 23:17
/duplicate of https://github.com/microsoft/vscode/issues/81337

**Closed** 2019-10-22 23:17 UTC
Labels: *duplicate, editor-find, feature-request
