### ISSUE TITLE
The `notebook.codeActionsOnSave` setting should work with code actions, not commands

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#180839] opened 2023-04-25 15:50 UTC
Testing #180765

I noticed that there's a difference in functionality between `notebook.codeActionsOnSave` and `editor.codeActionsOnSave`. While the former works with commands, the latter works with code actions. This is a conceptual mismatch that we should reconsider, as it makes notebook code actions incompatible with editor code actions. Currently, notebooks already support "normal" code actions for their cell editors (examples can be found in GHINB), and it would be best to maintain consistency with that. 

Real code actions provide structured data such as workspace edits that can be previewed, selectively applied, and configured. While there is a deprecated way for a code action provider to return just commands, it's still better than only returning command IDs, as the former can be associated with an extension and computed dynamically. 

Commands, on the other hand, are more general and don't have the same benefits as code actions. There's no guarantee that a command running while saving won't change the notebook at the same time, and a command can't truly participate in save by adding pre-save edits. 

Ideally, we should revisit this issue, but at a minimum, we should not use the name "codeActions" for this feature and clearly mark the setting as experimental (via its name). Additionally, we should stop recommending `notebook.format` as a possible on-save command, as there's a proper way to handle this (`notebook.formatOnSave.enabled`).

**Comment by roblourens** [comment] 2023-04-25 16:53
The editor setting also gives intellisense for code action IDs, the notebook version should do this too

<img width="343" alt="image" src="https://user-images.githubusercontent.com/323878/234348068-8a51ef66-430c-4d01-862e-a1150a32f5fc.png">

**Comment by mjbvz** [comment] 2023-04-25 18:17
I believe the longer term goal was to migrate to code actions. Until that happens though, can we either:

- Not ship or document this setting. This is my recommendation as that way users don't start depending the command based behavior
 
- As Joh suggested, give this setting a different name that clearly marks it as experimental

**Comment by Yoyokrazy** [comment] 2023-04-25 18:19
> I noticed that there's a difference in functionality between `notebook.codeActionsOnSave` and `editor.codeActionsOnSave`

I agree there's a discrepancy between `editor.codeActionsonSave` and `notebook.codeActionsOnSave` given the current behaviors. Right now the issue is that the api that the editor uses can't be used for notebook level CodeActions which is the current goal. The plan is to propose a new API supporting notebook level CodeActions during the next iteration which will properly utilize Workspace Edits and allow for more notebook specific CodeActions, following much of the structure laid out within the vscode.d.ts CodeAction API. This would also likely add the intellisense that @roblourens mentioned above.

> Additionally, we should stop recommending `notebook.format` as a possible on-save command

Yep, I'll go ahead and change this to a more generic example in the settings, and I'll go ahead and mark the setting more obviously experimental as well.

**Comment by rebornix** [comment] 2023-05-31 21:34
@Yoyokrazy I think this is done, right?

**Comment by Yoyokrazy** [comment] 2023-05-31 21:36
Correct, closing since the behavior has been overhauled to work properly with CodeActions.

**Closed by Yoyokrazy** 2023-05-31 21:36 UTC
Labels: important
