### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: /node_modules/@types/component-emitter/index.d.ts linked to nonexistent file //node_modules/@types/component-emitter/index.d.ts

### ISSUE THREAD

**Issue by lznval** [microsoft/vscode#183756] opened 2023-05-30 06:41 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.4

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: z:/novostroy/node_modules/@types/component-emitter/index.d.ts linked to nonexistent file //172.16.1.25/www/novostroy/node_modules/@types/component-emitter/index.d.ts
    at realPath (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42011:9)
    at getOriginalAndResolvedFileName (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40972:28)
    at resolveTypeReferenceDirective (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41053:45)
    at Object.resolve (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117475:42)
    at resolveNamesWithLocalCache (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122896:29)
    at Object.resolveTypeReferenceDirectiveReferences (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122961:12)
    at InferredProject2.resolveTypeReferenceDirectiveReferences (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171601:33)
    at resolveTypeReferenceDirectiveNamesWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118162:20)
    at resolveTypeReferenceDirectiveNamesReusingOldState (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118332:14)
    at createProgram (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117949:27)
    at synchronizeHostData (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135422:15)
    at Object.getProgram (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135494:5)
    at InferredProject2.updateGraphWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172176:41)
    at InferredProject2.updateGraph (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172113:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174423:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176043:12)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:64
    at flatMap (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:24)
    at updateOpen (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177418:29)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:69
    at IpcIOSession.executeWithRequestId (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179977:14)
    at IpcIOSession.executeCommand (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:29)
    at IpcIOSession.onMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180027:51)
    at process.<anonymous> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181594:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

Extension|Author (truncated)|Version
---|---|---
ecsstractor-port|diz|0.0.3
auto-rename-tag|for|0.1.10
vscode-language-pack-ru|MS-|1.78.2023051009

**Comment by mjbvz** [comment] 2023-05-30 20:23
Duplicate of #182196

**Closed by mjbvz** 2023-05-30 20:23 UTC
