### ISSUE TITLE
Zen mode code centre

### ISSUE THREAD

**Issue by Zyst** [Microsoft/vscode#17203] opened 2016-12-14 22:31 UTC
- VSCode Version: 1.8
- OS Version: OS X 10.12.1

Zen mode is in! I love you guys, thanks for that, been looking forward to it! However, everything tends to hang to the left super heavily, which is not so fun in large monitors. Although I bet it works great on a vertical setup:

![VS Code Zen](https://cloud.githubusercontent.com/assets/3832380/21203753/9c834220-c219-11e6-892a-a3c193df2538.png)

I would love it if there were a way to add some left padding of sorts. For now I just turned off the Fullscreen option, changed the background color of my Desktop to match VS Code, and that works to some degree:

<img width="2560" alt="Zen workaround" src="https://cloud.githubusercontent.com/assets/3832380/21203927/7d67c52c-c21a-11e6-9965-827a79b7aa01.png">

How other people are doing it:

Distraction free mode in IntelliJ tries to centre the code a bit: 

![IntelliJ family distraction free mode](https://stanfy.com/wp-content/uploads/2016/06/Distraction-Free-Mode-Android-Studio.png)

The Atom Zen mode plugin does something similar:

![Atom Zen](https://i.github-camo.com/6dbae0fe77e4492d6aa9a2c93f39ca4db79c6271/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f322f323239303435352f63653939653937652d613031642d313165332d383830382d6562656334306539353962342e706e67)

If there is a way to do this already and my google-fu failed me I do apologize for that.

**Comment by atombender** [comment] 2016-12-14 22:43
I think the most intuitive solution would be to let the user specify a desired width, in characters. So if I set 100 (that's how long my codes lines are before I wrap them) as my Zen width, it will adjust the padding so that a 100-character line effectively becomes centered at all times.

**Comment by mjbvz** [comment] 2016-12-14 23:05
Closing as a duplicate of #15684, which was opened with zen more in mind

**Closed by mjbvz** 2016-12-14 23:05 UTC
Labels: duplicate
