### ISSUE TITLE
I Can't run my tasks in Bash Ubuntu for Windows

### ISSUE THREAD

**Issue by RenanZX** [microsoft/vscode#132459] opened 2021-09-06 12:58 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.60.0
- OS Version: Windows 10 64 Bits Build 19.043 Version: 10.0.19043

When i run a task in task.json, it run only in powershell for some reason, but i want to run in ubuntu terminal for windows. I put ```type:'bash'```, but it still doesn't works.

![Captura de tela 2021-09-06 100603](https://user-images.githubusercontent.com/20937501/132222053-b208fd03-f4ad-44a6-8595-651bd9a9819d.jpg)

My settings.json:

```
{
    "editor.suggestSelection": "first",
    //"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe"
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.tabSize": 2,
    "python.languageServer": "Microsoft",
    "python.pythonPath": "C:\\Users\\RenanPC\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "editor.fontSize": 16,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "terminal.integrated.tabs.enabled": true,
    "json.schemas": [
    ],
    "launch": {

        "configurations": [],
        "compounds": []
    },
    "redhat.telemetry.enabled": true,
    "python.defaultInterpreterPath": "C:\\Users\\RenanPC\\AppData\\Local\\Microsoft\\WindowsApps\\python3.9.exe",
    "terminal.integrated.defaultProfile.windows": "Ubuntu (WSL)",
    "terminal.integrated.profiles.windows": {
      "Ubuntu (WSL)": {
        "path": "C:\\WINDOWS\\System32\\wsl.exe",
        },
        "Command Prompt": {
          "path": [
            "${env:windir}\\Sysnative\\cmd.exe",
            "${env:windir}\\System32\\cmd.exe"
          ],
          "args": [],
          "icon": "terminal-cmd"
        },
        "PowerShell": {
          "source": "PowerShell",
          "icon": "terminal-powershell"
        }
    },
    "terminal.integrated.profiles.linux": {
      "Ubuntu (WSL)": {
        "path": "C:\\WINDOWS\\System32\\wsl.exe",
      }
    }
}
````

**Comment by gjsjohnmurray** [comment] 2021-09-06 14:17
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-06 14:18 UTC
Labels: *duplicate
