### ISSUE TITLE
color picker closes immediately when changlog webview editor is open 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#68219] opened 2019-02-08 09:51 UTC
Version: 1.32.0-insider
Commit: 45c7f29565821668f4d010b25e3289953bd9ac71
Date: 2019-02-07T10:22:16.187Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

- open the extension viewlet and select the GitLens extension
- clock on the `Details` tab then to the `Changelog` tab
- in the lower left corner, select the `Color Theme` action from the context menu of the gear action
- Color quick picker opens and closes immediately

- does not happen when command is run by keyboard shortcut not when opening from the menu

**Comment by aeschli** [comment] 2019-02-08 09:51
@sandy081 FYI

**Comment by mjbvz** [comment] 2019-02-22 00:30
Duplicate of #68019

**Closed by mjbvz** 2019-02-22 00:30 UTC
Labels: webview
