### ISSUE TITLE
Drop boxes in Settings don't open on touch

### ISSUE THREAD

**Issue by breyed** [microsoft/vscode#73887] opened 2019-05-17 12:49 UTC
Issue Type: <b>Bug</b>

The drop boxes that look like Windows ComboBoxes (but aren't really) should act like ComboBoxes, but don't. Preferably, they'd just be native ComboBoxes. An important feature that the VS Code drop boxes lack is dropping down when you touch them on a touch screen.

Repro:
1. Navigate to the Workbench Color Theme setting.
2. Touch the drop box on a touch screen.
3. Notice that nothing happens. The drop box should open.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.26.0
githistory|don|0.4.6
gitlens|eam|9.7.4
git-project-manager|fel|1.7.1
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.1

</details>

**Comment by roblourens** [comment] 2019-05-20 18:52
We add some features to the dropdown so we don't use native comboboxes. I think it should work with touch though.

**Comment by roblourens** [comment] 2019-10-10 19:01
duplicate of https://github.com/microsoft/vscode/issues/73283

**Closed** 2019-10-10 19:01 UTC
Labels: *duplicate, bug, settings-editor
