### ISSUE TITLE
Command `revealFileInOS` breaks with Explorer view NOT opened

### ISSUE THREAD

**Issue by ewerybody** [microsoft/vscode#110869] opened 2020-11-18 15:37 UTC
Issue Type: <b>Bug</b>

### Found:
Performing the command `revealFileInOS` fails when the Explorer view <kbd>Ctrl+Shift+E</kbd> is NOT visible.

### Repro:
• have 2 files in 2 tabs from **different** directories open
• run `revealFileInOS` on tab 1
• see the File Browser with the selected file
• close Explorer, the whole Sidebar or switch to Extensions, Debug view ...
• run `revealFileInOS` on tab 2
• see the File Browser opened with the file from tab 1 selected!

### Expected:
`revealFileInOS` always shows the according file in the File Browser

Interestingly `copyFilePath` always gives you the correct path of the file in the active tab regardless of the Explorer view state.

VS Code version: Code - Insiders 1.52.0-insider (78908e7eb4ff12fc2ed0dd1f17200fea48c56ab2, 2020-11-18T12:38:39.842Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (9.83GB free)|
|Process Argv|--crash-reporter-id 0c2cfa5b-5dc2-4a3f-8161-96a200a402ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vbscript|Dar|1.0.4
vsc-python-indent|Kev|1.12.0
python|ms-|2020.11.367453362
vscode-pylance|ms-|2020.11.1
jupyter|ms-|2020.11.358541065
vsliveshare|ms-|1.0.3206
vscode-qt-for-python|sea|0.5.3

(1 theme extensions excluded)

</details>

**Comment by ewerybody** [comment] 2020-11-19 12:52
Oh I found an even more severe one on that:
* Make a completely new window <kbd>Ctrl+Shift+N</kbd>
* save the file <kbd>Ctrl+S</kbd> anywhere
* call `revealFileInOS` (via command pallette or right-click on the tab: "Reveal in File Explorer")
* get this Info popup: **Open a file first to reveal**
![image](https://user-images.githubusercontent.com/218956/99668533-288c8900-2a6e-11eb-8484-f9ee20a93bf7.png)

The command `copyFilePath` still works correctly in this situation.

**Comment by isidorn** [comment] 2020-11-19 18:55
Yeah we are aware of that. 
@bpasero tackled a duplicate of this issue. Currently we have no plans to tackle this further. Thus assigning to backlog

**Comment by ewerybody** [comment] 2020-11-20 10:07
OK. I might look into it. Where do I start? 😄

**Comment by isidorn** [comment] 2020-11-20 10:09
https://github.com/microsoft/vscode/blob/936048e0288f7bb8db8f8bc1d5a8816c4d85647c/src/vs/workbench/contrib/files/electron-sandbox/fileActions.contribution.ts#L39

Though I am not sure if there is a nice solution...

**Closed** 2021-03-02 16:07 UTC
Labels: *out-of-scope, file-explorer, under-discussion
