### ISSUE TITLE
can't format code and intellisense  in VS Code 1.7.1(Mac)

### ISSUE THREAD

**Issue by charliethinker** [Microsoft/vscode#15682] opened 2016-11-18 01:21 UTC
- VSCode Version: v1.7.1-02611b40b24c9df2726ad8b33f5ef5f67ac30b44-2016-11-03T13:44:00.572Z
- OS Version: macOS Sierra v10.12.1

I use Shift + Alt + F to format code, It’s not working!  I also try to run VS Code without extensions, execute:`code --disable-extensions` but It still can’t working. when I pressing `shift`+`option` + `f` key in my Mac will typing special character `Ï`.

like this:
<img width="666"  src="https://cloud.githubusercontent.com/assets/5362201/20414932/1c89c0b6-ad70-11e6-9464-cd652295e162.png">

**Comment by danielo515** [comment] 2016-11-18 13:13
Facing similar issue. I'm unable to run the command format code

**Comment by ferhatayhan** [comment] 2016-11-19 02:19
i had same issue on mac. 

VSCode: 1.7.1
 macOSX El Capitan 10.11.6

**Comment by jrieken** [comment] 2016-11-21 08:38
@charliethinker This is not enough information for me to reproduce

**Comment by danielo515** [comment] 2016-11-21 14:01
What information would you need?
My versions are:
VSCode: 1.7.1 (1.7.1)
macOS Sierra: 10.12.1

**Comment by jrieken** [comment] 2016-11-21 15:21
I need to know in what language this happens and what plugins you are using. Also, I need to know if this only happens when you try this with the shortcut or if this also happens when selecting format from the context menu

**Comment by ferhatayhan** [comment] 2016-11-22 01:45
In my case when i editing some c# files using older versions vscode it was working perfectly  (i don't know which one is).
After the update right click menu, intellisense, document format and shortcuts not worked. But i solved my problem.

With the lastest update all csharp files HAVE to under at least one solution (.sln) or project.json structure, otherwise it's not gonna work correctly.
So, im happy :)

**Comment by charliethinker** [comment] 2016-11-22 01:54
@jrieken I'm in China, In Mac can only use `Shift + Alt + F` shortcut  to format code,  There is no way to use the context menu in Mac, I also try to run VS Code without extensions, execute: ·`code --disable-extensions`. but It still can’t working. 

I use extensions list here:
<img width="380" src="https://cloud.githubusercontent.com/assets/5362201/20507830/5dbb9804-b098-11e6-87d6-1c84b982161e.png">
<img width="381"  src="https://cloud.githubusercontent.com/assets/5362201/20507831/5de5d632-b098-11e6-8235-c18366ae73fc.png">
<img width="384"  src="https://cloud.githubusercontent.com/assets/5362201/20507832/5e114538-b098-11e6-9d62-ba369a94b4f8.png">
<img width="379"  src="https://cloud.githubusercontent.com/assets/5362201/20507833/5e1b78b4-b098-11e6-9db7-702dfd544d1e.png">
<img width="384" src="https://cloud.githubusercontent.com/assets/5362201/20507834/5e41d3c4-b098-11e6-9e96-446502d690fc.png">

I have to reinstall VS Code, It can work well. Today I found after I written markdown file in vs(I installed *vscode-instant-markdown* extension), format code and intellisense doesn't work again.

**Comment by charliethinker** [comment] 2016-11-22 01:58
@ferhatayhan 
> In my case when i editing some c# files using older versions vscode it was working perfectly

I'm the same as you.

**Comment by ferhatayhan** [comment] 2016-11-22 02:15
@charliethinker if you want to working with c#  read that topic. https://code.visualstudio.com/docs/languages/csharp#_roslyn-and-omnisharp

**Comment by charliethinker** [comment] 2016-11-22 04:11
@jrieken when I use cover install VS Code, format and intellisense can't working. but I use ccleaner to uninstall VS Code and install it again ,format and intellisense was working well. Then I opened two window of VS Code(`Shift+Cmd+N`), one side used to write C#, while used to write the markdown file, after a period of time, format and intellisense doesn't work again.

**Comment by danielo515** [comment] 2016-11-22 13:21
In my case it is happening for Javascript.
I never use the keyboard shortcut, I allways open the command palette and select format code. The option does not exist anymore. Here are my extensions:

![captura de pantalla 2016-11-22 14 19 15](https://cloud.githubusercontent.com/assets/2270425/20525228/c5c20f48-b0be-11e6-9cf0-c875b513c1c2.png)
![captura de pantalla 2016-11-22 14 19 37](https://cloud.githubusercontent.com/assets/2270425/20525237/ccdec168-b0be-11e6-8c13-07e6ef0d73fd.png)

This is what happens when I try to format it:
![captura de pantalla 2016-11-22 14 21 01](https://cloud.githubusercontent.com/assets/2270425/20525282/f2127f24-b0be-11e6-99b3-a69c52871869.png)

**Comment by jrieken** [comment] 2016-11-22 14:51
re https://github.com/Microsoft/vscode/issues/15682#issuecomment-262238663 we renamed that for format code, it does the same but has a different label. When you want to format a selection only, you must have a selection first. @danielo515 this issue is about a C# setup problem as it seems, please don't mixin JavaScript as these are different worlds

**Comment by jrieken** [comment] 2016-11-22 14:51
@charliethinker re https://github.com/Microsoft/vscode/issues/15682#issuecomment-262142905 Do I understand correctly that this happens with C# files?

**Comment by charliethinker** [comment] 2016-11-23 02:17
@jrieken re [#15682 (comment)](https://github.com/Microsoft/vscode/issues/15682#issuecomment-262260676) Yes.

This issue happened again today, after I open new window to writing my blog with markdown.

Then my context menu has changed:
before:
<img width="216" src="https://cloud.githubusercontent.com/assets/5362201/20549237/7f2cfdd4-b165-11e6-9098-5b3df23c4532.png">
after:
<img width="652" src="https://cloud.githubusercontent.com/assets/5362201/20549303/f32522ac-b165-11e6-9189-4e4b0e2cd8ac.png">

**Comment by ttimmons** [comment] 2016-12-15 20:17
I am having this same issue on Mac.

VSCode Version 1.8.0 (1.8.0)
MacOSX Version 10.11.6 (El Capitan)

When I try to format code via the shift+alt+F shortcut this character prints out instead of formatting the code: `Ï`. Also when I open the context menu there is no option for "Format Document". Furthermore if I open the command palette there is no option for "Format Document" as well. I am trying to do this on Python files, JavaScript files, SCSS files, and HTML files (all of which do not work).

Plugins Installed:
![screen shot 2016-12-15 at 12 10 15 pm](https://cloud.githubusercontent.com/assets/6750503/21240298/9310351c-c2bf-11e6-834a-97bd7bacb8d8.png)

The "Format Document" option missing from the command palette:
![screen shot 2016-12-15 at 12 16 30 pm](https://cloud.githubusercontent.com/assets/6750503/21240476/5b98cb48-c2c0-11e6-8319-a7f22980abd0.png)

The "Format Document" option missing from the context menu:
![screen shot 2016-12-15 at 12 09 47 pm](https://cloud.githubusercontent.com/assets/6750503/21240333/bd2880e8-c2bf-11e6-925d-ea1f992a1567.png)

**Comment by danielo515** [comment] 2016-12-15 20:55
>@danielo515 this issue is about a C# setup problem as it seems, please don't mixin JavaScript as these are different worlds

I can't see any evidence of that on the title neither on the description if the issue, so please forgive my confusion.

**Comment by yuanoook** [comment] 2017-02-13 03:01
It seems like this kind of situation happened after some extensions updated, I disable all my extensions, and format (shift + alt + f) works again.

**Comment by jrieken** [comment] 2017-02-15 07:50
ok. closing this as being caused by an extension that.

**Closed by jrieken** 2017-02-15 07:50 UTC
Labels: format, needs more info

**Comment by devna13** [comment] 2017-07-20 17:16
I had same issue when I was opening a single javascript file in vs code On Mac, But when I tried "Open Folder" in explorer for the same file "Format Document" start working.

**Comment by xavores** [comment] 2017-07-26 17:00
Hello i have same problem when (shift + alt + f) i have '.' and no formatting. 

Nobody have solution 

Thanks

**Comment by LucitheR** [comment] 2017-09-20 09:30
Hi there,  got a problem too, maybe it's releated:

on Mac OS and since VSCode 1.16 i cannot use ALT + L (@) inside any File "no keyboard combination"

**Comment by tdbear** [comment] 2017-10-13 00:04
1.17 clean, no plugins installed. shift+alt+f produces Ï. Format command is not available at all (it does not appear under shift+cmd+p ">format" )

**Comment by jasofalcon** [comment] 2017-11-06 15:13
Any updates on this? I don't want to get back to Atom because of these kinds of issues...

**Comment by jrieken** [comment] 2017-11-07 08:44
> 1.17 clean, no plugins installed. shift+alt+f produces Ï. Format command is not available at all (it does not appear under shift+cmd+p ">format" )

Out of the box, without extensions, VS Code supports formatting only for a small set of languages, like JavaScript and TypeScript. That is only because we ship those extensions with VS Code. The rule of thumb is that a formatter-extension must be installed. 

If a formatter exists, for lets say JavaScript, the editor context menu will include a "Format Document" command, also the <kbd>Alt/Option+Shift+F</kbd> sequence will be bound. If for a language, lets say Rust, no formatter is installed that doesn't happen, so no entry in the context menu, not binding the aforementioned sequence. 

We do acknowledge the <kbd>Alt/Option+Shift+F</kbd>-confusion because on macOS it inserts by default `Ï`. We have recently pushed a [commit](https://github.com//Microsoft/vscode/commit/9a9c8c7afb7753fdf71bee9193718448ea8c8179) that binds that sequence even when not having a formatter such that it can show a message asking you to install one. 

We encourage everyone to browse the existing [formatter extensions on our market-place](https://marketplace.visualstudio.com/search?target=VSCode&category=Formatters&sortBy=Downloads) because we cannot ship with formatters for every language.

**Comment by jrieken** [comment] 2017-11-07 08:47
I have renamed and locked this issue because we now show a message when no formatter is installed or available and because we want separate issues for separate things. Don't be afraid to file duplicate.
