### ISSUE TITLE
Multi select option for the file explorer

### ISSUE THREAD

**Issue by Umamaheswaran1990** [Microsoft/vscode#13088] opened 2016-09-30 16:37 UTC
I think multi select option in the file explorer similar to visual studio would be helpful and save lot of time for the developers in file management.

**Comment by bpasero** [comment] 2016-10-04 05:30
@Umamaheswaran1990 please take the time to search for duplicates first.

**Comment by Umamaheswaran1990** [comment] 2016-10-04 05:41
@bpasero I did tried to find the open issues with similar feature request before creating this but i couldnt find any, If there is already a ticket for this issue, please feel free to close this ticket. Also it would be helpful if you could share the other tickets id.

**Comment by bpasero** [comment] 2016-10-04 05:49
@Umamaheswaran1990  ![editors](https://cloud.githubusercontent.com/assets/900690/19063923/19d50c04-8a07-11e6-8de5-a258f10fb15a.gif)

**Comment by chrisbroome** [comment] 2016-12-08 19:46
@bpasero That's a helpful animation to see how you searched, but you didn't link the actual duplicate. I came here to post the exact same thing as @Umamaheswaran1990 and also had problems finding duplicate items. The filter labels definitely helped, but it still wasn't easy. That's probably because as of right now there are over 1000 issues open, lol.

For the record, this is a duplicate of #1023.

**Comment by Tyriar** [comment] 2016-12-09 04:15
Closing as duplicate of https://github.com/Microsoft/vscode/issues/1023

**Closed by Tyriar** 2016-12-09 04:15 UTC
Labels: explorer-files, feature-request
