### ISSUE TITLE
Drag into VS Code to install VSIX extension

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56933] opened 2018-08-21 18:22 UTC
I want to be able to drag a VSIX file into VS Code to install it.

**Comment by fabiospampinato** [comment] 2018-08-27 14:04
IMHO `.vsix` files should just be opened via VSC, so that one could install them with a double click.

If you're requesting this because installing `.vsix` files is a bit of a pain you might find my [`Install .VSIX`](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-install-vsix) extension useful.

**Comment by sandy081** [comment] 2018-09-24 17:10
Duplicate of #31079

**Closed** 2018-09-24 17:10 UTC
Labels: *duplicate, extensions, feature-request
