### ISSUE TITLE
Mac bar button

### ISSUE THREAD

**Issue by cscott2021** [microsoft/vscode#92512] opened 2020-03-11 18:37 UTC
Issue Type: <b>Bug</b>

On the bottom bar for mac, the icon is not normal size and can't be selected.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 7, 9|
|Memory (System)|16.00GB (4.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-html-css|ecm|0.2.3
python|ms-|2020.2.64397
vsliveshare|ms-|1.0.1742
commandlist|yam|1.0.2

</details>

**Comment by krupenja** [comment] 2020-03-12 00:23
Could be a duplicate of https://github.com/microsoft/vscode/issues/63068

**Closed** 2020-03-12 02:48 UTC
Labels: *duplicate, new release
