### ISSUE TITLE
Slow to get a functional TS editor

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#31344] opened 2017-07-24 21:56 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (9b6cc9f774f424b4e8a91d4a2d3d4ad8efb9cfb9, 2017-07-24T05:07:43.734Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
quokka-vscode|Wal|1.0.41
crazy|kie|0.0.1
githistory|don|0.2.2
python|don|0.6.9
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vsc-travis-ci-status|fel|1.1.0
svgpreview|kis|0.2.0
Go|luk|0.6.62
mssql|ms-|1.1.0
github-issues-prs|ms-|0.3.1
debugger-for-chrome|msj|3.1.6
vscode-versionlens|pfl|0.19.1
Ruby|reb|0.12.1
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.2.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1. open a VS Code workspace on `master`, no open editors
2. search for `from 'electron'` in all `*.ts` files
3. click on the first search result and wait until TS is properly initialized
4. click on the second search result and select `ipcMain` in the editor
-> caret stops blinking, it takes several seconds until the underlying word is highlighted and occurrences are shown in the scrollbar (only happens after the reference code lenses are shown)

Reproduces without extensions: **Yes**

This is the [TS server log](https://github.com/Microsoft/vscode/files/1171339/tsserver-log.txt)

**Comment by mjbvz** [comment] 2017-07-25 00:48
Thanks @kieferrm. I've opened https://github.com/Microsoft/TypeScript/issues/17385 to track this upstream.

I was able to reproduce this after closing all editor windows which leads me to suspect that the slowdown may be caused by us reloading some or part of the vscode project when switching between the search results

**Closed** 2017-07-25 00:59 UTC
Labels: insiders, perf, typescript, upstream
