### ISSUE TITLE
Include announcement section for extension authors

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#27993] opened 2017-06-04 06:12 UTC
Sometimes extension authors like me at `settings-sync` need to announce something, which may large chunk of users wont care but some users though. Hence allow authors to interact with users by showing announcements.

Currently there is not way other then that I am showing the message upon the code start and users takes it as spam or whatever.
When they click on the message, link should be opened, or the message can have multiple buttons.

If there is announcement section in the extension with a notification badge in the extensions will allow users to view them anytime, unlike they are doing right now to close the information message box every time.

// cc @Tyriar (https://github.com/shanalikhan/code-settings-sync/issues/335#issuecomment-305996633)

**Comment by jens1o** [comment] 2017-06-04 07:35
We at `vscode-icons` do have the same problem: https://github.com/vscode-icons/vscode-icons/blob/455c6f0443d313714c2cb886a9108af5ba5381d0/src/init/welcome.ts#L10-L62 (And there are more messages we display.)

// cc @robertohuertasm @JimiC

**Comment by Tyriar** [comment] 2017-06-06 19:00
Related: https://github.com/Microsoft/vscode/issues/22388

If we have a light weight notification system, we may just want to add notifications there for all extension updates? Especially automatic ones.

**Comment by shanalikhan** [comment] 2017-07-02 11:29
Here is another scenario

My Extension sometimes having problems in Mac OS and i dont have that environment. I test on Windows and Linux. I want to inform users with Mac OS if they are willing to fix minor issue and send me pull request.

I will have to send a message box to inform users when they open code

If there is announcement section, it would be great, to cover many scenarios to cover the interaction with users and authors.

**Comment by stevencl** [comment] 2017-08-10 16:52
We should consider the above as part of our work on improving notification UX (which has slowed down since we've been working on multi root). One thing that comes to mind from reading the above is that with notifications coming from many different channels, we may need to offer ways for users to control, based on the channel, how they are notified and when.

**Comment by isidorn** [comment] 2017-11-20 14:18
Closing as duplicate of https://github.com/Microsoft/vscode/issues/1135

**Closed by isidorn** 2017-11-20 14:18 UTC
Labels: api, ux
