### ISSUE TITLE
Autoimport is broken

### ISSUE THREAD

**Issue by bibblebabl** [Microsoft/vscode#60786] opened 2018-10-12 13:39 UTC
<img width="1440" alt="2018-10-12 16 37 17" src="https://user-images.githubusercontent.com/9008978/46872576-2ee6ba80-ce3d-11e8-8b8a-82ffcb0db934.png">
<img width="1440" alt="2018-10-12 16 37 21" src="https://user-images.githubusercontent.com/9008978/46872581-327a4180-ce3d-11e8-9794-62c73c58ca6a.png">

Issue Type: <b>Bug</b>

Auto import is broken.  When i start writing name of a component in JSX it shows me an option to choose, than i click on it and following code appears: 
` <import('./components/Form').Form`
See screenshots below

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
githistory|don|0.4.3
es7-react-js-snippets|dsz|1.8.6
gitlens|eam|8.5.6
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.4.2
path-autocomplete|ion|1.12.0
vscode-styled-components|jpo|0.0.22
vscode-styled-components-snippets|lXS|1.0.2
vscode-language-babel|mgm|0.0.20
prettify-json|moh|0.0.3
vscode-duplicate|mrm|1.2.1
sass-indented|rob|1.4.9

</details>

**Comment by n-sviridenko** [comment] 2018-10-12 16:04
Have same issue now 😭

**Comment by mjbvz** [comment] 2018-10-12 18:35
Duplicate of #60216

**Closed by mjbvz** 2018-10-12 18:35 UTC
Labels: new release

**Comment by jdk339** [comment] 2018-10-16 15:14
This is indeed an issue with VSCode, and not Typescript. Here's my current solution for the time being:

> I decided to revert back to a previous version of VS Code and it's working fine now. The only caveat is that I had to rename the directory at `$HOME/Library/Application Support/Code` to `$HOME/Library/Application Support/Code Backup` or else when I started a previous version of VS Code it would just give me a black screen.
> 
> From the "Code Backup" folder, copy your user settings from `User/settings.json` and you should be good to go until VS Code gets fixed.

**Comment by mdhornet90** [comment] 2018-10-19 21:02
This is still broken for me even with the latest update (1.28.2)

**Comment by k-knyazev** [comment] 2018-11-05 21:38
Broken TypeScript autoimports for me too, just suddenly stopped working, was at the 1.28.2 update, Linux Solus & Windows 10 Pro (latest).

**Comment by wynfred** [comment] 2018-11-14 17:59
Please reopen the issue
