### ISSUE TITLE
empty file appear after exit

### ISSUE THREAD

**Issue by lasypig** [Microsoft/vscode#10569] opened 2016-08-16 03:32 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:37:17.621Z)
- OS Version: Linux ia32 3.13.0-93-generic

Steps to Reproduce:

1. open vscode
2. close
3. a file named ??Q@h?}@8 appeared, size 0

**Comment by bpasero** [comment] 2016-08-16 08:34
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by lasypig** [comment] 2016-08-17 01:28
Yes, it is an issue with the extension "C/C++ for Visual Studio Code" @bpasero

**Comment by bpasero** [comment] 2016-08-17 04:26
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2016-08-17 04:26 UTC
Labels: needs more info
