### ISSUE TITLE
Failed to update some extensions

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#48373] opened 2018-04-23 07:50 UTC
Issue Type: <b>Bug</b>

Currently, I have the two extensions showing that they have updates (gitlens and bookmarks) . When I click update for those extensions, both show the error dialog: Failed to update 'eamodio.gitlens' and Failed to update "alefragnani.bookmarks".

The download manually button allows to download the vsix files, but they are not helping and are not updating the extenions either.

Looking at the devtools log, I see the following:

```
extensionsActions.ts:338 Error: Incomplete. Extracted 33 of 34 entries
(anonymous) @ extensionsActions.ts:338
```

and 

```
notificationsAlerts.ts:39 Failed to update 'eamodio.gitlens'.
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
```

VS Code version: Code - Insiders 1.23.0-insider (c1cd4378c5e5dc434ed959e13556d05240a8ca18, 2018-04-20T05:17:25.189Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (19.43GB free)|
|Process Argv|W:\Soft\VS Code\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.2
project-manager|ale|0.25.0
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.3
EditorConfig|Edi|0.12.1
prettier-vscode|esb|1.3.1
beautify|Hoo|1.3.0
vscode-stylefmt|mrm|2.5.0
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.3.0
stylelint|shi|0.36.0
vvs-theme-seti|Vla|1.0.0
vscode-todo-highlight|way|0.5.12
vscode-jumpy|wma|0.3.1

(2 theme extensions excluded)

</details>

**Comment by vvs** [comment] 2018-04-23 08:11
Also, tried to install some new extensions from the recommended list, e.g., TSLint (eg2/tslint), and it fails as well, with the same error: Failed to install 'eg2.tslint'. And the similar errors in the log:

Error: Incomplete. Extracted 2001 of 2002 entries.

So, basically, no extensions can be installed or updated at this moment for me :(

**Comment by sandy081** [comment] 2018-04-24 09:45
@vvs Thanks for reporting. We introduced this check to detect incomplete installs. Looks like while unzipping the vsix, always one entry is missing for you. 

Can you try installing some themes extensions?

Will add some logs today and you can try tomorrow so that we can see what is missing. 

Thanks.

**Comment by tlgreg** [comment] 2018-04-24 10:09
Same error for me, incomplete with one entry.

Currently two extensions have pending updates for me: `patbenatar.advanced-new-file` and `alefragnani.project-manager`.
I was able to update `CoenraadS.disableligatures` though from vsix file, which I couldn't update yesterday, but I didn't check the error back then.

Tried installing a theme, but same issue.
`Failed to install extension: tinkertrain.theme-panda Incomplete. Extracted 25 of 26 entries`

**Comment by sandy081** [comment] 2018-04-24 11:00
Thanks for updating. Will add logs and let you know.

**Comment by tlgreg** [comment] 2018-04-24 21:32
It's possible that some kind of a race condition is in play as it's seems to be randomly working.
`advanced-new-file` updated without any issues tonight so I tried spamming update for `project-manager` and around 8th try it also updated successfully.

**Comment by sandy081** [comment] 2018-04-25 09:53
@tlgreg I do not think there is any such race condition to happen. 

Can you please update to today's insiders and set VS Code log level to `debug` using `Set Log Level` command and try installing. Please check the logs for what files are being extracted and what is missing.

Thanks

**Comment by tlgreg** [comment] 2018-04-26 02:41
@vvs You should be able to find the log in output > Log (shared)

The current extension that failed to update is a bit bigger (`robertohuertasm.vscode-icons`), but same issue, I don't see the `extension.vsixmanifest` file in the debug log.

**Comment by sandy081** [comment] 2018-04-26 08:32
@tlgreg Thanks for the information. Is it possible to share the log?

Since you were able to reproduce it with theme extensions (which are smaller), can you please try to reproduce with it and check the logs?

**Comment by vvs** [comment] 2018-04-26 08:32
Ah, indeed, thanks @tlgreg, now I can see the output, which is just a huge list of files. I also don't see extension.vsixmanifest in the log.

The weird thing is that the installation problems are indeed not deterministic. Yesterday I tried to install tslint and jshint extensions, one was OK to install, another one was not OK. Today I tried, and I see the opposite results, the one that was not working yesterday can now be happily installed, and vise versa... Weird.

**Comment by vvs** [comment] 2018-04-26 08:36
Here's my debug output when trying to install a very small `disableligatures` extensions, @sandy081 :
```
[2018-04-26 10:35:37.425] [sharedprocess] [info] Installing extension: disableligatures
[2018-04-26 10:35:38.037] [sharedprocess] [info] Downloaded extension: disableligatures
[2018-04-26 10:35:38.044] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting [Content_Types].xml
[2018-04-26 10:35:38.044] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/CHANGELOG.md
[2018-04-26 10:35:38.045] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/img/cursor.png
[2018-04-26 10:35:38.045] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/img/icon.png
[2018-04-26 10:35:38.046] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/img/line.png
[2018-04-26 10:35:38.046] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/LICENSE.md
[2018-04-26 10:35:38.046] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/out/src/extension.js
[2018-04-26 10:35:38.047] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/package-lock.json
[2018-04-26 10:35:38.047] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/package.json
[2018-04-26 10:35:38.047] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/README.md
[2018-04-26 10:35:38.048] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Extracting extension/tslint.json
[2018-04-26 10:35:38.067] [sharedprocess] [info] Scanned user extensions: 16
[2018-04-26 10:35:38.067] [sharedprocess] [error] Failed to install extension: CoenraadS.disableligatures Incomplete. Extracted 11 of 12 entries
[2018-04-26 10:35:38.206] [sharedprocess] [info] Scanned user extensions: 16
[2018-04-26 10:35:38.221] [sharedprocess] [info] Scanned system extensions: 69
```

**Comment by vvs** [comment] 2018-04-26 08:38
Some more info, since I really like that disable ligatures extensions and really wanted to install it, I clicked install 10-15 times quickly, and eventually it installed :)

**Comment by tlgreg** [comment] 2018-04-26 08:58
The log:
```
[2018-04-26 10:53:32.480] [sharedprocess] [info] Installing extension: vscode-theme-darcula
[2018-04-26 10:53:32.758] [sharedprocess] [info] Downloaded extension: vscode-theme-darcula
[2018-04-26 10:53:32.767] [sharedprocess] [debug] C:\Users\{user}\.vscode-insiders\extensions\.rokoroku.vscode-theme-darcula-1.1.0 Extracting [Content_Types].xml
[2018-04-26 10:53:32.767] [sharedprocess] [debug] C:\Users\{user}\.vscode-insiders\extensions\.rokoroku.vscode-theme-darcula-1.1.0 Extracting extension/CHANGELOG.md
[2018-04-26 10:53:32.768] [sharedprocess] [debug] C:\Users\{user}\.vscode-insiders\extensions\.rokoroku.vscode-theme-darcula-1.1.0 Extracting extension/icon.png
[2018-04-26 10:53:32.769] [sharedprocess] [debug] C:\Users\{user}\.vscode-insiders\extensions\.rokoroku.vscode-theme-darcula-1.1.0 Extracting extension/icon.svg
[2018-04-26 10:53:32.770] [sharedprocess] [debug] C:\Users\{user}\.vscode-insiders\extensions\.rokoroku.vscode-theme-darcula-1.1.0 Extracting extension/package.json
[2018-04-26 10:53:32.771] [sharedprocess] [debug] C:\Users\{user}\.vscode-insiders\extensions\.rokoroku.vscode-theme-darcula-1.1.0 Extracting extension/README.md
[2018-04-26 10:53:32.774] [sharedprocess] [debug] C:\Users\{user}\.vscode-insiders\extensions\.rokoroku.vscode-theme-darcula-1.1.0 Extracting extension/themes/darcula.json
[2018-04-26 10:53:32.870] [sharedprocess] [info] Scanned user extensions: 81
[2018-04-26 10:53:32.871] [sharedprocess] [error] Failed to install extension: rokoroku.vscode-theme-darcula Incomplete. Extracted 7 of 8 entries
[2018-04-26 10:53:33.130] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-26 10:53:33.146] [sharedprocess] [info] Scanned user extensions: 81
```
Yeah, lots of extensions. :) The missing file is consistently `extension.vsixmanifest`.

**Comment by sandy081** [comment] 2018-04-26 12:04
@vvs @tlgreg Changed logs a little to see where the file is being missed in the following build. Can you please try and share the logs?

https://az764295.vo.msecnd.net/insider/520d075e1325fdb505b15b03cb4a201f46f5c2c9/VSCodeSetup-x64-1.23.0-insider.exe

I assume both of you on Windows

**Comment by sandy081** [comment] 2018-04-26 14:16
**NOTE:** Disable auto update of insiders (before installing above build. Set 
`"update.channel": "none"` in User settings.

**Comment by vvs** [comment] 2018-04-26 14:30
Here's the new log:
```

**Comment by vvs** [comment] 2018-04-26 14:34
And here's the log of TWO consecutive attempts to install the same extension. The first attempt fails, the second succeeds:

```
[2018-04-26 16:32:57.777] [sharedprocess] [info] Installing extension: disableligatures
[2018-04-26 16:32:57.920] [sharedprocess] [info] Downloaded extension: disableligatures
[2018-04-26 16:32:57.923] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found [Content_Types].xml
[2018-04-26 16:32:57.924] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/CHANGELOG.md
[2018-04-26 16:32:57.925] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/img/cursor.png
[2018-04-26 16:32:57.925] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/img/icon.png
[2018-04-26 16:32:57.926] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/img/line.png
[2018-04-26 16:32:57.927] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/LICENSE.md
[2018-04-26 16:32:57.928] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/out/src/extension.js
[2018-04-26 16:32:57.928] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/package-lock.json
[2018-04-26 16:32:57.929] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/package.json
[2018-04-26 16:32:57.929] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/README.md
[2018-04-26 16:32:57.930] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/tslint.json
[2018-04-26 16:32:57.951] [sharedprocess] [info] Scanned user extensions: 16
[2018-04-26 16:32:57.951] [sharedprocess] [error] Failed to install extension: CoenraadS.disableligatures Incomplete. Found 11 of 12 entries
[2018-04-26 16:32:58.074] [sharedprocess] [info] Scanned user extensions: 16
[2018-04-26 16:32:58.088] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-26 16:32:58.471] [sharedprocess] [info] Installing extension: disableligatures
[2018-04-26 16:32:58.641] [sharedprocess] [info] Downloaded extension: disableligatures
[2018-04-26 16:32:58.644] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension.vsixmanifest
[2018-04-26 16:32:58.644] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found [Content_Types].xml
[2018-04-26 16:32:58.644] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/CHANGELOG.md
[2018-04-26 16:32:58.645] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/img/cursor.png
[2018-04-26 16:32:58.645] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/img/icon.png
[2018-04-26 16:32:58.646] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/img/line.png
[2018-04-26 16:32:58.647] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/LICENSE.md
[2018-04-26 16:32:58.647] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/out/src/extension.js
[2018-04-26 16:32:58.647] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/package-lock.json
[2018-04-26 16:32:58.648] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/package.json
[2018-04-26 16:32:58.648] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/README.md
[2018-04-26 16:32:58.649] [sharedprocess] [debug] C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8 Found extension/tslint.json
[2018-04-26 16:32:58.656] [sharedprocess] [info] Extracted extension to C:\Users\vvs\.vscode-insiders\extensions\.CoenraadS.disableligatures-0.0.8: CoenraadS.disableligatures-0.0.8
[2018-04-26 16:32:58.658] [sharedprocess] [info] Renamed to C:\Users\vvs\.vscode-insiders\extensions\CoenraadS.disableligatures-0.0.8
[2018-04-26 16:32:58.658] [sharedprocess] [info] Installation completed. CoenraadS.disableligatures-0.0.8
[2018-04-26 16:32:58.664] [sharedprocess] [info] Extensions installed successfully: CoenraadS.disableligatures
[2018-04-26 16:32:58.792] [sharedprocess] [info] Scanned user extensions: 17
[2018-04-26 16:32:58.802] [sharedprocess] [info] Scanned system extensions: 69
```

**Comment by sandy081** [comment] 2018-04-26 15:46
@vvs Thanks a lot for sharing them. I can confirm that the we are missing the first event the unzip library is firing while extracting the entries.

I am preparing another build by changing the way we open the zip. I will let you know once the build is available.

**Comment by sandy081** [comment] 2018-04-26 16:59
@vvs Here is the new build, please try out and let me know if you can install successfully. 

https://az764295.vo.msecnd.net/insider/a86aa041810bb3c23185d2db4dc5b7785655472a/VSCodeSetup-x64-1.23.0-insider.exe

Thanks in advance.

**Comment by cwadrupldijjit** [comment] 2018-04-26 20:36
@sandy081, it looks like it worked for me.  I'd been experiencing the exact same issue, too.

Thanks for the build!

**Comment by tlgreg** [comment] 2018-04-26 20:51
@sandy081 This build works like a charm. Thanks for your work on the issue!

**Comment by sandy081** [comment] 2018-04-26 21:27
Thanks for confirming. Very much appreciated with the support.

Pushed the fix and will be available in tomorrow's insiders.

Please update to insiders tomorrow and confirm.

Thanks.

**Closed** 2018-04-27 07:51 UTC
Labels: bug, extensions

**Comment by sandy081** [comment] 2018-04-27 08:26
@tlgreg @cwadrupldijjit @vvs Please verify that you do not have this issue with new insiders.

General verification: 

- Install extensions randomly (top 10-20 extension) and make sure they are installed without errors. Also check Shared process logs for no unexpected errors.

**Comment by tlgreg** [comment] 2018-04-27 09:31
Installed a few extensions and works well, no issues, no errors in the log.

**Comment by vvs** [comment] 2018-04-27 11:25
@sandy081 Thank you very much for your efforts and quick resolution of this annoying bug. I  can confirm that the latest insiders build works fine for me.

Thanks!!
