### ISSUE TITLE
VS Code Integrated terminal crashes with exit code: 259.

### ISSUE THREAD

**Issue by FrancescoNegri** [microsoft/vscode#36994] opened 2017-10-26 16:26 UTC
- VSCode Version: 1.17.2
- OS Version: Windows 10 build 17025

Steps to Reproduce:

1. Open integrated terminal.
2. Write a command between "bash", "node .", "react-native run-android", ecc.. (with some commands like "cls" it keeps working).
3. Press Enter.

Reproduces without extensions: Yes
![screenshot 1](https://user-images.githubusercontent.com/11014462/32064927-988dfaba-ba7b-11e7-9c5b-4e945f2c6deb.png)
![screenshot 2](https://user-images.githubusercontent.com/11014462/32064928-98ae9680-ba7b-11e7-9a0b-dbf45b717f80.png)

**Comment by Tyriar** [comment] 2017-10-28 00:23
Hmm.. What the error message means is that cmd.exe crashed, can you run bash without any problems in a regular cmd.exe window?

Could you also check the devtools console for any errors? (Help > Toggle Developer Tools)

**Comment by FrancescoNegri** [comment] 2017-10-31 07:26
Yes, I can run it in a regular cmd.exe. The devtools console catch the exact same error (messageService.ts:125 Il processo del terminale è stato terminato. Codice di uscita: 259).

**Comment by FrancescoNegri** [comment] 2017-10-31 07:31
I have to say that probably the issue came out when I updated my SO to Redstone 4 (builds 17xxx).

**Comment by Tyriar** [comment] 2017-11-02 18:35
@FrancescoNegri do you mean an Insiders build of Windows? If so I can ping the console team as they might have changed something.

**Comment by FrancescoNegri** [comment] 2017-11-02 20:50
Yes, it's an Insider build, the last one relased in the "fast ring".

**Comment by Tyriar** [comment] 2017-11-07 22:44
@bitcrazed any insight into what would cause a 259 exit code in bash.exe? This may just be a problem with winpty doing something it isn't supposed to.

**Comment by bitcrazed** [comment] 2017-11-07 23:55
No idea - not seen that! @zadjii - you see something like this?

**Comment by zadjii-msft** [comment] 2017-11-08 00:28
Perhaps this is related to Microsoft/console#36? I haven't investigated it at all yet. I *really* doubt there's anything new in the 17017 build from us that would cause that, but hey who knows. 

My bet would be something with the input stack, because that was the area with the most code delta over the weeks leading to 17017/17025.

Has anyone from winpty (@rprichard) or ConEmu(@maximus5) investigated or seen this?

**Comment by rprichard** [comment] 2017-11-08 06:09
No, I hadn't seen this problem before.

**Comment by Maximus5** [comment] 2017-11-08 13:51
In the description I don't see where the error 259 appears.
But the code 259 usually means `STILL_ACTIVE` and this is rather strange.
You may try to use ProcessMonitor to determine which processes are started during your call and perhaps that gives you a clue.

**Comment by Tyriar** [comment] 2017-11-08 20:59
I've haven't seen any reports of this before, but there have been 2 (this and https://github.com/Microsoft/vscode/issues/37764) over the last couple of weeks.

**Comment by FrancescoNegri** [comment] 2017-11-13 09:21
I updated my SO to build 17035 and the issue is still there

**Comment by skyne98** [comment] 2017-11-16 14:03
Yep, the same problem here.

**Comment by Ofer-Gal** [comment] 2017-11-16 15:34
Me too only on windows 10. Don't have "bash" do I need to install it?

**Comment by bitcrazed** [comment] 2017-11-16 18:49
@Ofer-Gal since @FrancescoNegri original reported this happening with Cmd as his default terminal shell, I doubt this is related to WSL.

Still trying to repro this issue, but have not been able to yet. 

**If anyone else has a reliable repro, please share detailed repro steps here, along with build number, VSCode version number, etc.**

Also, please ensure you do NOT have Legacy Console enabled in your Console properties.

![image](https://user-images.githubusercontent.com/961950/32909580-c4f78cf6-cabb-11e7-87ed-44e82dbe1778.png)

**Comment by Ofer-Gal** [comment] 2017-11-17 01:50
Thanks but somehow it does not crash anymore (maybe a windows update)
even though I have `,
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"` in the settings.json, the terminal starts PowerShell.
I can live with that.

**Comment by FrancescoNegri** [comment] 2017-11-17 10:55
I have just updated VS Code to 1.18.1, no changes about the issue.
Anyway I noticed that even the integrated terminal closes itself with error 259, the command is launched and keeps running. For example I ran <bash> on the integrated terminal in VS, it exited with 259, then I tried to run <bash> in a common cmd prompt and it said that I couldn't because it was already running in a different instance. Hope this can help.

**Comment by anhdle14** [comment] 2018-02-19 02:33
Updating on the problem, currently running on:
VS Code version: Code - Insiders 1.21.0-insider (d28f096, 2018-02-09T05:14:50.066Z)
OS version: Windows_NT x64 10.0.17101

There are things that constantly bugging me:
* The extensions does not work well with WSL.exe/ Bash.exe. 
>For example Go Exts constantly bugging, and wait for 15' least to even do a simple debugging test. Python linter doesn't work automatically, have to re choose what linter to start working, and only work once.

* Everytime reloading Vscode. System starting to create, many duplicate init, bash, zsh, etc...
![Duplicating ZSH](https://i.stack.imgur.com/nyNTt.png)

* Exit code 259. Have to stop using it with vscode. The log doesn't show much of the help, trying to change to wsl.exe, assign to shortcut with custom commands at start did not help either. Tried using only bash, turning off everything, same result. The only thing left is to reinstall wsl. By the way, using it with Hyper.js or any other terminals work fine for me. 

_May be open the issue until this got fix?_

**Comment by willauld** [comment] 2018-07-29 23:06
I've just started seeing a similar crash of the integrated terminal with exit code 259. 

I'm running Win 10 insiders Build 17723.rs5_release.180720-1452. 
VS code is Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

I've disabled plug-ins, closed everything, rebooted, reopened vs code and gave the Newly troublesome command: go test

The terminal crashes and give the error code.
![capture](https://user-images.githubusercontent.com/9990713/43371546-0509d3de-9349-11e8-956c-9b7afc125591.PNG)

Not sure what to do next to root cause this.

Thanks,
Will

**Comment by willauld** [comment] 2018-07-29 23:46
Did a little more and found that I can, without issue, open a powershell and run the "go test." Also, the problem goes away if I reverted a specific file back to the last commit.

**Comment by willauld** [comment] 2018-07-30 22:33
I seem to have lost the ability to make this happen. Not sure what I changed, so, for now I can't reproduce it or fix it.

**Comment by eamodio** [comment] 2018-08-03 16:58
@Tyriar I am seemingly hitting this issue constantly now. It seems that almost any webpack output that contains errors over a certain length (and its not that long maybe a 100 lines?) the terminals crash with this error.

**Comment by Tyriar** [comment] 2018-08-03 19:23
@eamodio It's probably related to winpty https://github.com/Microsoft/vscode/issues/45693, which I'm looking into for 1.27. Maybe webpack changed something recently that triggers this in winpty?

**Comment by eamodio** [comment] 2018-08-04 03:32
Yeah, I guess -- its kind of nuts that I never saw this issue prior to a week or so ago and now it happens at least 10-20 times a day (constantly have to keep restarting watcher tasks).

Also I have just noticed this happening quite a few times over the last day or so too https://github.com/Microsoft/vscode/issues/26807. But probably related to me setting `"terminal.integrated.experimentalRestore": true`

**Comment by ShayBox** [comment] 2018-08-20 22:02
Been happening to me a lot recently too, and very reliably, I provided more details on my issue I closed above, don't want to spam the same stuff.
If that helps at all.

**Comment by Tyriar** [comment] 2019-10-08 15:26
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Closed by Tyriar** 2019-10-08 15:26 UTC
Labels: integrated-terminal, needs more info
