### ISSUE TITLE
Incorrect auto formatting (Shift+Alt+F) if the button tag has onclick function

### ISSUE THREAD

**Issue by AndrewBelle** [Microsoft/vscode#17469] opened 2016-12-17 18:34 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

Incorrect auto formatting (Shift+Alt+F) if the button tag has onclick function

Steps to Reproduce:

1. Paste the following code to a new .html file:
```
<body class="platform-android">
  <button onclick="startAnimation()">Start Graphic Performance Test</button>
  <div id="Result"> Time Interval</div>
  <div class="clearFix"></div>
</body>
```
2. Press Shift+Alt+F. The code will be formatted as follows:
```
<body class="platform-android">
  <button onclick="startAnimation()">Start Graphic Performance Test</button>
<div id="Result"> Time Interval</div>
<div class="clearFix"></div>
</body>
```

If we delete onclick="startAnimation()" from the button tag, the code will be formatted correctly (with indents as in the step number 1)

**Comment by itamark** [comment] 2016-12-17 22:18
"following code" is missing.

**Comment by AndrewBelle** [comment] 2016-12-18 11:37
Indeed, sorry. I updated the first post

**Comment by aeschli** [comment] 2016-12-31 02:58
duplicate of #17849

**Closed by aeschli** 2016-12-31 02:58 UTC
Labels: needs more info
