### ISSUE TITLE
Extension host terminated unexpectedly. Code:  3221225477  Signal:  null 

### ISSUE THREAD

**Issue by gonefuture** [Microsoft/vscode#34692] opened 2017-09-20 11:42 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-eslint|dba|1.3.2
javadebugger|don|0.1.3
python|don|0.7.0
vscode-javac|geo|0.0.46
vue-snippets|hol|0.1.5
cpptools|ms-|0.12.4
vscode-docker|Pet|0.0.18
open-in-browser|tec|1.1.0
python|tht|0.2.3
vscode-react-native|vsm|0.4.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by gonefuture** [comment] 2017-09-20 11:46
Extension host terminated unexpectedly. Code:  3221225477  Signal:  null   

I can't resolve this bug .It is useless that restarting it or reinstall.

**Comment by alexandrudima** [comment] 2017-09-21 10:35
@gonefuture Can you please try launching `Code.exe --disable-extensions` from a command prompt ?

**Comment by onofremartins** [comment] 2017-09-21 16:52
Hi, same problem here. i observe a massive use of RAM and CPU while try restart the Extension host process.
![image](https://user-images.githubusercontent.com/3029668/30708092-fe3d1800-9ed3-11e7-8dfb-8d72195736d6.png)

**Comment by alexandrudima** [comment] 2017-09-25 16:29
@onofremartins This all depends on what extensions you have installed. Does the massive usage of RAM reproduce when disabling all extensions ?

**Comment by gonefuture** [comment] 2017-10-08 02:32
![image](https://user-images.githubusercontent.com/19575771/31313295-55b1d3e2-ac11-11e7-934d-c5dc0956b649.png)

![image](https://user-images.githubusercontent.com/19575771/31313305-9e1b6f8a-ac11-11e7-9eed-b1ca39719590.png)

# The The problem still exists。I try to remove all extensions and reinstall ,but it is useless.

## **I find that  I can't use git in the vscode。**     It reminds me that "your system does not seem to have Git. installed." However ,I has install git,and set the git environment variable 。

![image](https://user-images.githubusercontent.com/19575771/31313341-150e2afa-ac13-11e7-8c75-8ca35c084a2c.png)

# **It say that "Source code management provider that has no activity."** and "Extension host terminated unexpectedly."

**Comment by gonefuture** [comment] 2017-10-11 04:25
![image](https://user-images.githubusercontent.com/19575771/31422246-0343b1aa-ae7f-11e7-8761-9c12dee2d306.png)
# in vscode Developer Tools

**Comment by joaomoreno** [comment] 2017-10-11 08:01
@gonefuture @onofremartins What language is your Windows installation?

**Comment by gonefuture** [comment] 2017-10-11 08:35
simple chinese

**Comment by onofremartins** [comment] 2017-10-16 15:38
My OS has English default. Windows 7. 

In my case I found the problem. This was my git repository, many files being processed by the git extension. I removed the git repository because I did not need on this project anymore and the problem did not happen again. but I do not know which of the extensions below was.


![image](https://user-images.githubusercontent.com/3029668/31620767-e20aadf8-b276-11e7-9319-a54161ba14ef.png)

**Comment by gonefuture** [comment] 2017-10-19 07:44
I has delete all extension and remove the git repository, however,wen use vscode to open file, the problem still exist. 


##What's more, I use anything about git in vscode . I can clone git proplem, it reminded me I has no git ,but I have and use git normally in other program.

**Comment by joaomoreno** [comment] 2017-10-19 08:27
@gonefuture What is the value of the following 3 environment variables, in your system:

- `ProgramW6432`
- `ProgramFiles(x86)`
- `ProgramFiles`

**Comment by gonefuture** [comment] 2017-10-26 11:40
@joaomoreno
How to see those  environment variables ?

**Comment by risa401** [comment] 2017-10-26 15:38
I'm really new to all of this, I just installed VSCode and got this error straight up from the box.

**Comment by ojhariddhish** [comment] 2017-11-26 05:56
Hi, 
Has there been a fix for this issue. I'm also facing this issue. 

My Configuration:
**Windows 10 Home:**  Update 1709
**VS Code:**  1.18.1 x64
**Node:** 9.2.0
**NPM:** 5.5.1
**Extensions Installed:** Babel ES6/ES7, Beautify, C/C++, C#, Code Runner, Dart Code, ESLint, Flutter Snippets, Go, Kotlin Language, MagicPython, markdownlint, Node Debug 2, One Dark Pro, Powershell, Project Manager, Python, React Native Tools, TSLint, Visual Studio Team Services & vscode-react-templates.

![vscodeissue](https://user-images.githubusercontent.com/4638776/33237520-5f24dde2-d29b-11e7-9fb1-395995a03190.png)

Tried re-installing VSCode, removed all extensions & re-installed them. Nothing works.

**Comment by gonefuture** [comment] 2017-11-27 03:07
@ojhariddhish 



The problem still exists, no matter how I upgrade the system or uninstall the software reinstall, I even tried the zip version of vscode.I think, which should be related to git, because my source code management function there is different from others

**Comment by gonefuture** [comment] 2017-11-27 03:10
@ojhariddhish 
![default](https://user-images.githubusercontent.com/19575771/33249101-87aae9be-d363-11e7-9767-678f3332de01.PNG)

**Comment by ojhariddhish** [comment] 2017-11-27 05:04
@gonefuture yes, the problem exists and its the same error we've been getting. I guess, now only #VScode team only can help us.

**Comment by joaomoreno** [comment] 2017-11-27 08:11
Does it reproduce with out latest insider release? https://go.microsoft.com/fwlink/?Linkid=850640

**Comment by gonefuture** [comment] 2017-11-27 14:53
@joaomoreno 
Oh, yes! The insider version is not wrong. When will the release version out?

**Comment by ojhariddhish** [comment] 2017-11-27 15:22
@joaomoreno thanks for the latest insider release. This release helped me find out which extension was causing this issue for me. It was React Native Tools. I've uninstalled this extension from stable as well as insider release and now the issue is gone. 

@gonefuture do you have React Native Tools extension installed? If yes, can you please confirm whether this is the extension causing the issue or its just on my system.

**Comment by joaomoreno** [comment] 2017-11-27 15:40
Great news, closing then!

**Closed** 2017-11-27 15:40 UTC
Labels: freeze-slow-crash, git, needs more info

**Comment by gonefuture** [comment] 2017-11-28 11:40
@joaomoreno 
Thanks.

**Comment by gonefuture** [comment] 2017-11-28 11:50
@ojhariddhish 
![default](https://user-images.githubusercontent.com/19575771/33318279-1d725452-d475-11e7-8ff4-013962aef81a.PNG)
Yes,I can use React-Native tool.

**Comment by ojhariddhish** [comment] 2017-11-29 03:44
Thanks @gonefuture. So, basically this extension was not the causing the issue for you but for me it was. 

Its good that @joaomoreno has provided us with Insider release.

**Comment by anonymouswalkalone** [comment] 2017-12-06 16:18
@joaomoreno
Thanks.

**Comment by lolyaltyCN** [comment] 2018-01-05 07:40
![image](https://user-images.githubusercontent.com/23227505/34599704-b59c42de-f22e-11e7-87c9-5acec7c16655.png)


我下载了最新版本的vsc但是他仍然是不好使的,node debug 失效,并且他卡住了
I downloaded the latest version of VSC, but he was still not good, node debug failed, and he stuck it
