### ISSUE TITLE
Move to file doesn't work

### ISSUE THREAD

**Issue by rifatdinc** [microsoft/vscode#228626] opened 2024-09-14 09:46 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. The move to file feature does not work when clicked.

https://github.com/user-attachments/assets/71fd83d5-1bf9-497a-9705-714f4e1aef3f

2. <semantic> TypeScript Server Error (5.7.0-dev.20240913) Debug Failure. Error: Debug Failure. at Object.addImportFromExportedSymbol (/Users/rifatdinc/.vscode/extensions/ms-vscode.vscode-typescript-next-5.7.20240913/node_modules/typescript/lib/typescript.js:155817:32) at /Users/rifatdinc/.vscode/extensions/ms-vscode.vscode-typescript-next-5.7.20240913/node_modules/typescript/lib/typescript.js:145615:19 at Map.forEach (<anonymous>) at addTargetFileImports (/Users/rifatdinc/.vscode/extensions/ms-vscode.vscode-typescript-next-5.7.20240913/node_modules/typescript/lib/typescript.js:145609:17) at getNewStatementsAndRemoveFromOldFile (/Users/rifatdinc/.vscode/extensions/ms-vscode.vscode-typescript-next-5.7.20240913/node_modules/typescript/lib/typescript.js:144829:3) at doChange3 (/Users/rifatdinc/.vscode/extensions/ms-vscode.vscode-typescript-next-5.7.20240913/node_modules/typescript/lib/typescript.js:144813:3) at /Users/rifatdinc/.vscode/extensions/ms-vscode.vscode-...

**Comment by mjbvz** [comment] 2024-09-23 18:16
Duplicate of https://github.com/microsoft/typescript/issues/59747 I believe

If you can, please try putting together a minimal repo and post it to TypeScript so we can verify the fix

**Closed by mjbvz** 2024-09-23 18:16 UTC
