### ISSUE TITLE
Error "Cannot read property 'line' of null" when resolveSkipFiles is set

### ISSUE THREAD

**Issue by ruslan-bikkinin** [microsoft/vscode#79092] opened 2019-07-29 14:17 UTC
# Description

Adding `resolveSkipFiles` to debug configuration leads to an error:
```
Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null
at Object. (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:792:62)
```

I couldn't reproduce it on dummy js script, it only reproducible while debugging React Native app via [extension](https://github.com/microsoft/vscode-react-native).

Related issue: https://github.com/microsoft/vscode-react-native/issues/1063

# Expected behavior

No error is shown, debugging works as expected

# Actual behavior

Error is shown, debugging is stopped

**Comment by roblourens** [comment] 2019-08-14 04:57
Closing as dupe of https://github.com/microsoft/vscode/issues/72412

**Closed by roblourens** 2019-08-14 04:57 UTC
Labels: bug, debug
