### ISSUE TITLE
Add extension context state as source for "when" clause contexts

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#23880] opened 2017-04-04 07:26 UTC
Feature request:

Currently when clauses can be evaluated based on a number of things as [outlined here](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts)
, but for an extension developer this requires adding a configuration option for something that might belong in the state.

For example, a gitter user has stated that they'd like to enable a context menu entry only if an IIS Server is running. Whether the server is running or not is a perfect example of extension state that could be stored in the extensionContext.globalState or extensionContext.workspaceState properties, but isn't accessible to the when clause context.

A workaround would be to abuse the user configuration and tell the user not to modify it manually, but that would only cause more confusion.

**Comment by pr-yemibedu** [comment] 2017-04-04 14:37
Hello,
 What is the mechanism that supports marking when a state is valid?
 So if the IIS is starting but can not handle requests, what state is it in?
 Also, if it is shutting down, would the state remain true?
 What is the exposure of state in face of errors? 

## Possibly
 So one scenario is to have generic when items that can and should be evaluated at delayed points. For example:

- when file - returns true if a file can be found at a given path.
- when time - return true if the current time matches given time stamp.
- when process - return true if a process can be found that matches a given name.
- when result - return true if the result of some typescript function matches a given value.

This or more would allow lots of context of when and how things can be triggered. They can not be cached and would need points of scope to determine *valid* state transitions. Thank you. Good day.

**Comment by jrieken** [comment] 2017-04-05 05:51
Today we have an API command that allows to set the context, without having to (ab)use the extension context. Closing this as dupe of #10471

**Closed by jrieken** 2017-04-05 05:51 UTC
Labels: feature-request
