### ISSUE TITLE
Allow regular expression for CompletionItemProvider triggerCharacters

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33697] opened 2017-09-01 18:39 UTC
**Problem**
For issues like #23962, we want to trigger suggestions when the user types the `'` in:

```js
import _ from '
```

Registering the TS completion provider with `'` as a trigger character currently results in the completion provider being shown too often and in unexpected placed

**Proposal**
Allow triggerCharacters to use regular expressions. This regular expression would be run against the proceeding text on the line. In the above case, the completion item provider would use a regular expression like `/from\s+['"]$/` and be run against: `import _ from '`

**Comment by rcjsuen** [comment] 2017-09-01 21:45
Should this feature be added to the language server protocol?

**Comment by jrieken** [comment] 2017-09-04 07:23
> trigger character currently results in the completion provider being shown too often and in unexpected placed

Why? The extension should just check if it is at the right location in the syntax tree. I don't think that running one (or many) arbitrary complex regular expressions while you type is a good idea. We have an API request to let provider know why they were just triggered and with that information a provider could just do the check itself

**Comment by ramya-rao-a** [comment] 2017-09-04 16:14
Here is another scenario.

`div.col-lg-12` is a valid emmet abbreviation. In fact, bootstrap users use such abbreviations all the time.
In html, the word definition includes the `-` and so above is considered a word and emmet completion provider is triggered.
But so many other languages do not have `-` in the word definition and so emmet completion provider will not be triggered for the above.
One solution is to add the numbers from 0 to 9 as trigger characters. Use of regex would help keep things clean in this case.

On the other hand I also understand running regex especially for the complete text before the cursor while you type may not efficient

I would have suggested regex matching just with text before cursor and after the last whitespace which can solve my issue, but won't help @mjbvz

**Comment by mjbvz** [comment] 2017-09-04 19:08
Another simple example I ran into with the emojisense extension:

For suggestions for strings like `:smile:`, I wanted to auto trigger suggestions when you type the `:` in lines such as:

```
:
a :
a : a
```

but not automatically trigger when there is no preceding space:

```
a:
a:a
```

However there are also cases where you really do want to see the emoji suggestions in the above (spaceless) case—such as typing a string of emoji—but only when you explicitly request them.

If I filtered the suggestions based on whether there is preceding space or not, then the manual suggestion scenario did not work. If I triggered on `:` without the check, then the suggestions were triggered unnecessarily. I had to add several workarounds for this including an [option to trigger on `:`](https://github.com/mattbierner/vscode-emojisense/blob/master/src/extension.ts#L13)

**Comment by ramya-rao-a** [comment] 2017-09-05 01:44
Would it help if the completion provider knew if the suggestions were manually triggered vs auto-triggered?

**Comment by jrieken** [comment] 2017-09-05 07:35
We have an API request to let provider know why they were just triggered and with that information a provider could just do the check itself

**Comment by mjbvz** [comment] 2017-09-05 20:57
Going back to the original problem, perhaps better example of a need for something beyond a trigger character is #32954. This issue is for auto showing suggestions when you type `${` in a template string.

If you register `{` as a trigger character, suggestions are incorrectly shown when typing `{` for blocks and object literals. However after `{` in a block is a perfectly valid context and should allow for manual suggestion triggering

**Comment by jrieken** [comment] 2017-09-06 08:22
Why @mjbvz? If you know why suggestion was triggered (24x7, trigger-character, manual, etc) you can  do that, you just need to look around. Triggered by character, character is `{`, position is inside template string -> Good, return something. Otherwise, don't. Using (and relying) on regular expressions is always error prone, what if I type `${` inside a comment? Will you propose things without verifying the position?

**Comment by mjbvz** [comment] 2017-09-08 01:08
Ok, why don't we try #752 and see if there are any problems with that or cases that it does not handle. Should I look into it for this iteration? Any more thoughts on the API change for this?

**Comment by jrieken** [comment] 2017-09-08 07:46
Yeah, let's schedule it for September and see how it does. I am closing this as a dupe of #752 then

**Closed by jrieken** 2017-09-08 07:46 UTC
Labels: api, duplicate, suggest, under-discussion
