### ISSUE TITLE
HTML attributes not properly highlighted

### ISSUE THREAD

**Issue by andrewmartin** [Microsoft/vscode#19405] opened 2017-01-26 00:42 UTC
Apologies if this isn't the right place, but I'm convinced it's a bug.

I'm seeing really boring HTML formatting in my editor. I just spent like 3 hours trying to figure out what was going on, and I can't find any solution or fix. Hoping someone knows why my HTML formatting looks uninteresting, or any ideas to change it, and I think it might be a bug. 

![image](https://cloud.githubusercontent.com/assets/273842/22315647/eb467322-e31c-11e6-9a51-9c04ea08f0e7.png)

Also, in JSX, block definitions look uninteresting as well. I wouldn't be surprised if this was related.

![image](https://cloud.githubusercontent.com/assets/273842/22315676/161a3b06-e31d-11e6-9420-8dec09d9fc5f.png)

- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: `macOS 10.12.2`
Steps to Reproduce:

1. Open HTML file.
2. See boring formatting.

**Comment by aeschli** [comment] 2017-01-26 20:27
What color theme do you use?

**Comment by mousetraps** [comment] 2017-01-26 20:39
@aeschli - fwiw I managed to reproduce a similar behavior with the "Red" color theme

**Comment by aeschli** [comment] 2017-01-27 07:14
@mousetraps What version of VSCode? What language mode? I'd love to see the example code so I can reproduce.

**Comment by mousetraps** [comment] 2017-01-27 07:56
@aeschli - I reproduced on insiders w html provided in @andrewmartin's setup before I assigned to you. It wasn't *exactly* the same as the screenshot because we had the bug where the background theme color wouldn't kick in, but strings in html were not being highlighted any differently than other elements. This wasn't the case in other themes iirc. I can double check tomorrow. If you can't repro with just a basic html element with a string (eg just try Img Src="my string"), then just forget my comment for the time being - maybe I'm remembering it wrong, or was momentarily color blind, or any number of possibilities. It's been a long day ;-)

**Comment by aeschli** [comment] 2017-01-27 08:45
That's how it currently looks with the Red theme:
![image](https://cloud.githubusercontent.com/assets/6461412/22364974/5b83cc8a-e475-11e6-9251-d363e69981a6.png)

**Comment by aeschli** [comment] 2017-01-30 13:41
Closing as things seems to work fine for me. @andrewmartin If you have additional information on how to reproduce the issue, please let me know and I'm happy to reopen.

**Closed by aeschli** 2017-01-30 13:41 UTC
Labels: bug, html, themes
