### ISSUE TITLE
Hide File Name According to rule

### ISSUE THREAD

**Issue by izacsc** [microsoft/vscode#83463] opened 2019-10-28 19:38 UTC
I'm developing an angular project and this is the file explorer view.

![image](https://user-images.githubusercontent.com/423449/67711103-0a09aa80-f9a0-11e9-94d8-c96047fec1e3.png)

I would like to specify some rule to hide some parts of the file name, like extensions or based on the parent folder like the example below:

![image](https://user-images.githubusercontent.com/423449/67711310-7d132100-f9a0-11e9-80cb-3143a9064102.png)

It would only affect the file explorer. It could be like the file exclusion pattern.

**Comment by isidorn** [comment] 2019-11-12 09:16
This is a duplicate of file nesting feature request. Please search for that one and you can upvote it. Thanks!

**Comment by izacsc** [comment] 2019-11-12 13:42
@isidorn Actually it is not a duplicate, but could be complementary to the file nesting issue. Please reconsider it.

This feature only changes the display name of the files in the explorer but doesn't change the "folder" structure, making the UI cleaner.

Since the file nesting issue doesnt look like is going to be solved anywhere soon ( it has more than 400 reactions since 2016 )  I thought maybe something different could be implemented.

Thanks

**Comment by isidorn** [comment] 2019-11-12 14:45
Sure, let's reopen this. Thanks for clarifying

**Closed** 2020-03-16 00:51 UTC
Labels: feature-request, file-explorer
