### ISSUE TITLE
Icons jump in search results

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#214165] opened 2024-06-03 18:04 UTC
Hovering over the X icon seems to push the readonly icon away:

![Recording 2024-06-03 at 20 03 35](https://github.com/microsoft/vscode/assets/900690/ac410bf1-9e3b-401d-8abd-a7e50c766dee)

**Comment by andreamah** [comment] 2024-06-03 19:19
That's strange- I don't remember making a change to add lock icons to the search (which would be a part of https://github.com/microsoft/vscode/issues/181000). Does this just appear with read-only files?

**Comment by bpasero** [comment] 2024-06-04 03:47
No, looks like here as well:

![Recording 2024-06-04 at 05 47 33](https://github.com/microsoft/vscode/assets/900690/9ec5ec44-2654-4197-85ae-d429c16a2563)

**Comment by andreamah** [comment] 2024-06-04 15:15
This should be a duplicate of https://github.com/microsoft/vscode/issues/156300

**Closed by andreamah** 2024-06-04 15:15 UTC
