### ISSUE TITLE
登录账户

### ISSUE THREAD

**Issue by XAINI** [microsoft/vscode#101255] opened 2020-06-29 01:46 UTC
Issue Type: <b>Bug</b>

I don't know how to sign in my account in vscode 
version: 1.46.1

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.46.3
vetur|oct|0.24.0

</details>

**Comment by kekekezi** [comment] 2020-06-29 02:31
同问

**Comment by mochaaP** [comment] 2020-08-14 17:00
请使用正确的 Issue 模版提交问题。

同时，此问题并不应该提交到 Issue 中，而更适合在帮助论坛或或即时聊天室中询问。

---

1. 确保您的 Visual Studio Code 为最新版本。
  ![Check for updates](https://user-images.githubusercontent.com/21154023/90274080-88353000-de92-11ea-9f5c-8eb1358ef4b0.png)

2. 选择登入菜单。
  ![Login menu on sidebar](https://user-images.githubusercontent.com/21154023/90273913-4906df00-de92-11ea-8c45-1f8fabf14a33.png)

希望这有帮助！

**Comment by dbaeumer** [comment] 2020-08-17 09:43
@mochaaP can you please provide the description in English as requested here: https://github.com/microsoft/vscode/issues/101255#issuecomment-650859821

**Comment by mochaaP** [comment] 2020-08-17 11:02
@dbaeumer As it's actually not a bug report, I think we can close this issue.

---

Translated:

> Please use the correct template to submit a issue.
>
> It's better to ask questions in support forums or user groups.
>
> ---
>
> 1. Make sure you're on the latest version of Visual Studio Code:
>   ![Check for updates](https://user-images.githubusercontent.com/21154023/90274080-88353000-de92-11ea-9f5c-8eb1358ef4b0.png)
>
> 2. Open the login menu on sidebar:
>  ![Login menu on sidebar](https://user-images.githubusercontent.com/21154023/90273913-4906df00-de92-11ea-8c45-1f8fabf14a33.png)
>
> Hope this helps!

**Comment by dbaeumer** [comment] 2020-08-18 12:25
Thanks for getting back. Closing the issue.

**Closed by dbaeumer** 2020-08-18 12:25 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
