### ISSUE TITLE
[BUG]: When rename css class, the dot is duplicated on all references.

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#30100] opened 2017-07-04 18:06 UTC
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. See figure.. (Open the box rename on keypress F2)

![bug_classe_css](https://user-images.githubusercontent.com/5774595/27839777-6246c8ca-60ca-11e7-9c8c-b06f8665fb26.gif)

**Comment by aeschli** [comment] 2017-07-11 09:46
duplicate of #7340

**Closed by aeschli** 2017-07-11 09:46 UTC
