### ISSUE TITLE
Resizeable suggestions should retain default size from previous releases

### ISSUE THREAD

**Issue by alexkreidler** [microsoft/vscode#110868] opened 2020-11-18 15:32 UTC
Issue Type: <b>Feature Request</b>

Resizable suggestions (https://github.com/microsoft/vscode/pull/109094) recently landed in version 1.51.

Unfortunately, I was perplexed upon trying to use autocomplete on a JSON file, as it seemed that the suggestion view had mysteriously compacted into a single line, rendering it almost unusable. I had to look through the release notes to figure out it was a new feature and could be fixed simply by resizing the box.

I propose that the suggestion view retains the same size as it had by default in previous versions. This would make it easier for users who are upgrading.

Alternatively, the resizable suggestions feature could have a setting such as "minimum size" that specifies minimum dimensions. Users would not be able to accidentally or otherwise resize below that size, unless they wanted to go into settings and change it.

Thanks!

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.3.0-64-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor (16 x 3882)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.65GB (0.39GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 768665f1-6e13-493d-8a60-3c142a8193ab|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by jrieken** [comment] 2020-11-18 16:10
> as it seemed that the suggestion view had mysteriously compacted into a single line, rendering it almost unusable

That should really not happen. The default is to show 12 items (assume there are 12 or more suggestions). I would really like to understand how you have gotten into that bogus state. Do you have by any change `editor.suggestLineHeight` configured?

**Comment by jrieken** [comment] 2020-11-18 16:11
fyi - you can also select "F1 > Reset Suggest Widget Size" and the size is back to normal. Tho, I really want to know how the "useless" size happens

**Comment by alexkreidler** [comment] 2020-11-18 16:21
Here's my search for line-height in settings. All are the same in workspace settings as well.

![image](https://user-images.githubusercontent.com/11166947/99556771-f3aa0480-298f-11eb-93a2-bdf6051cdf32.png)

I'm curious too about the bogus state but I just resized so I'm not sure if I'll ever run across it again. I'd be happy to send you my full settings.json file though as well.

Going AFK for a while so may not be able to respond/provide more info until tmrw.

Thanks for digging into this!

**Comment by jrieken** [comment] 2020-11-18 16:55
Interesting... There was potential for bugs with "unexpected" suggest line heights but your looks all good. You aren't the first to have encountered this and I am puzzled. I will fold this issue into https://github.com/microsoft/vscode/issues/110554 but please let me know if you encounter this again

**Comment by jrieken** [comment] 2020-11-18 16:55
/duplicate of https://github.com/microsoft/vscode/issues/110554

**Closed** 2020-11-18 16:56 UTC
Labels: *duplicate, needs more info, suggest
