### ISSUE TITLE
Autoimport always imports relative paths

### ISSUE THREAD

**Issue by sharpcoder28** [Microsoft/vscode#54187] opened 2018-07-12 15:53 UTC
With the June 1.25 version, imports now are full relative paths.

```
import { Observable } from '../../../../node_modules/rxjs';
```

I tried adding

`"typescript.preferences.importModuleSpecifier": "non-relative"`

which did not work.

**Comment by mjbvz** [comment] 2018-07-12 19:47
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-12 19:47 UTC
Labels: javascript
