### ISSUE TITLE
vscode does not open large files

### ISSUE THREAD

**Issue by d180cf** [Microsoft/vscode#9832] opened 2016-07-27 06:03 UTC
Basically, I tried to open a 250 MB log file and got a message that vscode doesn't support this. vs2015 opened the file in a second.

I like that it didn't hang or crash, like many other editors, but I don't see why opening large log files is a hard problem. Log files generally have a simple structure: a sequence of reasonably long text lines; vscode could detect if the file looks like a good log file and render a part of it that is visible. Obviously, then I'll want all the cool features like regexp search and highlighting, but I believe that this can be nicely abstracted at the fs level.

**Comment by egamma** [comment] 2016-07-27 07:14
@alexandrudima @gregvanl I suggest that we document our approach to large file handling in the FAQ.

**Comment by alexandrudima** [comment] 2016-08-02 13:24
@d180cf VSCode is optimized for editing. There are a great deal of assumptions one can make when creating a log viewer:

* the user is not allowed to edit the file
* since no changes can be made by the user to the file through the editor, the editor does not need to guarantee that no changes are lost
* this means that the file does not need to be kept in memory for the one in a million chance that it gets written/deleted by accident on disk and valuable changes made by the user get lost
* log files usually do not contain programming languages, so in all likelihood each log line can be colored independently of the rest of the file. This is not the case for programming languages, where a `/*` at line 1 might impact the coloring of line 2 million.

These assumptions (read-only, context-independent line coloring) are not assumptions we can make in VSCode since our primary scope is to be an editor for programming languages and not a log viewer.

This does not mean we could not be also a good log viewer, it is just not a top priority. Other than that, the only thing stopping us from opening that file is basically getting OOM.

**Comment by regs01** [comment] 2016-08-24 20:20
There could be some large files that needs to be edited, like SQL files or resource files. NotePad++ and AkelPad handles them well.

**Comment by cmosespl** [comment] 2016-09-19 13:10
Hello. I'm working a lot with books and dictionaries in text format (html, xml, sql, others). I do parsing, conversion and editing. VS Code works stable and smooth with files around 10MB, great job MS! How ever from time to time I have to work also with dictionaries with size of 100+MB and cannot do my job in VS Code. It would be awesome to have possibility to do work using one app instead of switching between different apps while working on the same project.

Notice: Notepad++ tend to corrupt files with size above few MB !!!

**Comment by gouletr** [comment] 2016-10-21 20:49
I agree it would be very useful for VSCode to be able to open large files.

Example: I wrote an app in C++ and compile it with Emscripten, which can produce pretty big .js files, depending on code size. Using the VSCode Chrome Debugger extension, we can debug Emscripten applications if they were built with proper build flags (source maps not absolutely necessary).

However, if the .js file is several MB, past a certain point VSCode will refuse to open them, so we can't put breakpoints anymore and use VSCode to debug. Interestingly, if you are a tiny bit below the VSCode max file size, it works like a charm.

Since there's no good options right now to debug Emscripten apps, it would be great if that limit was a user setting (or just removed) so that we can use VSCode in that scenario.

**Comment by BillDenton** [comment] 2016-10-24 14:51
I regularly need to inspect large log files. Whilst looking at them I often refer to the source files (C) to help in understanding them. So large file support is important.

**Comment by danechitoaie** [comment] 2016-10-24 19:34
I'm very happy that VSC doesn't crash when opening a large file like the other editors but I would be even happier if it would be possible to still allow the file to be opened in a "stream mode". Basically you can disable the syntax highlight (and maybe other features that would be resource intensive to implement on large files) but open and read the file in chunks of data (what's needed to be displayed on screen) and load more as you scroll (up or down).

**Comment by josemigallas** [comment] 2017-02-02 14:46
Any updates on this? IMO it's very annoying to have to change the editor or use the terminal whenever I need to check some log.

**Comment by jankap** [comment] 2017-02-14 11:41
A stream mode or a tail/less like experience would be awesome. Any news on that?

**Comment by danechitoaie** [comment] 2017-02-14 12:23
Yes, no need to load all file in memory. And also having syntax highlight disabled is ok. Just being able to open it and "stream trough it" would be perfect.

**Comment by alexandrudima** [comment] 2017-07-07 09:39
Some improvements have been made in #30180 , but our memory usage remains roughly: 

> file size on disk + 40-60 bytes (2 objects) per line

We will look into removing or raising the limit on 64 bit platforms

**Comment by baslr** [comment] 2017-07-14 23:38
I cant open a file with 60.2 MB and 1.1m lines.
Is there a hidden setting to overwrite the limitation?

**Comment by evandrocoan** [comment] 2017-07-23 17:36
Possible duplicate of: 

1. https://github.com/Microsoft/vscode/issues/6474 VS Code fails to open big files (60MB)

**Comment by alexandrudima** [comment] 2017-08-10 07:53
With the upcoming 1.15, the file size limit has been lifted on the 64bit releases of VSCode. On the 32bit variants, the file size limit has been raised to 300MB.

Files over 20MB or with more than 300k lines will be treated especially, and some of the features will be turned off for them (e.g. tokenization, word wrapping, etc.) in order to save memory.

**Closed by alexandrudima** 2017-08-10 07:53 UTC
Labels: feature-request

**Comment by micah-at-talos** [comment] 2017-10-18 15:03
On a related topic, I am unable to diff two files when one of them is very large.  Currently using a 64bit version of VS Code on MacOS.  

My command line is along the lines of:
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --diff <file a> <file b>

The files open in a side-by-side locked scrolling method, but I receive a warning notification "Cannot compare files because one file is too large."

No diff is performed.  In my case, one file is 8.4M and the other is 30M.
