### ISSUE TITLE
VS Code welcome page has 2 errors and 128 warnings

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#38957] opened 2017-11-22 14:07 UTC
VS Code 1.18.1
OS Windows

- open Code to show the Welcome screen
- toggle developer tools ('Help > Toggle Developer Tools')
- there are 2 errors and 128 warnings called out

![image](https://user-images.githubusercontent.com/33490168/33129162-fd2b9842-cf5c-11e7-9b4f-63dec2a45c34.png)

Here're the two errors;

![image](https://user-images.githubusercontent.com/33490168/33129242-461910ca-cf5d-11e7-9b85-ecfa9ce7d96c.png)

Here's a chunk of the 128 warnings

![image](https://user-images.githubusercontent.com/33490168/33129332-8aaeacd6-cf5d-11e7-9065-e0c819b50135.png)

and with more detail

![image](https://user-images.githubusercontent.com/33490168/33129529-29d09e00-cf5e-11e7-88e2-23cb4498e6c0.png)

It appears that someone is attempting to phone home.

![image](https://user-images.githubusercontent.com/33490168/33131411-745f2abc-cf64-11e7-8162-a08f53c39a0d.png)

**Comment by chrmarti** [comment] 2017-11-30 23:26
The only place I see `getLineMaxColumn` in `onEditorMouseDown` is in `folding.ts`.

**Comment by aeschli** [comment] 2017-12-01 09:57
`getLineMaxColumn` in `onEditorMouseDown` is duplicate of #38290

**Closed by aeschli** 2017-12-01 09:57 UTC
