### ISSUE TITLE
TypeScript Syntax Highlighting breaks when using ++ inside an if statement

### ISSUE THREAD

**Issue by fxlemire** [Microsoft/vscode#36436] opened 2017-10-17 17:16 UTC
- VSCode Version: 1.17.0
- OS Version: Windows 10

Using the ++ shorthand in an if statement on a TypeScript file breaks the syntax highlighting (fine when preceding the variable).

How it should look:

![image](https://user-images.githubusercontent.com/4381789/31678674-d7ab218c-b33c-11e7-9dc8-71914fc1caec.png)

How it looks:

![image](https://user-images.githubusercontent.com/4381789/31678695-ec339008-b33c-11e7-95b2-68ea87c7ac26.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-10-17 17:18
Duplicate of #35768

Should be fixed in VS Code 1.18 insiders builds already. Please try these out and let me know if you still see the issue

**Closed by mjbvz** 2017-10-17 17:18 UTC
Labels: duplicate, grammar, typescript
