### ISSUE TITLE
Proxie issue when viewing Extensions in gallery

### ISSUE THREAD

**Issue by FloMaetschke** [Microsoft/vscode#14853] opened 2016-11-02 14:16 UTC
- VSCode Version: 1.7.0-insider
- OS Version: MS Windows Server 2008 R2

Steps to Reproduce:

1. Use Visual Studio Code with Corporate Proxy

settings.json contains:
```
	// The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
	"http.proxy": "http://user:pw@123.123.123.123:8080",
	"http.proxyStrictSSL": false,
```

2. Select any extension to view on the right side (gallery) (extensions already installed are shown correctly).

Result:
![vscode network](https://cloud.githubusercontent.com/assets/7500948/19932170/4df9396e-a10f-11e6-9e01-204b08c9bea5.PNG)

I get 4 errors in developer console when opening the gallery view of an extension.
The text is displayed but images are missing.

> 
> dantup.gallery.vsassets.io/_apis/public/gallery/publisher/DanTup/extension/…/assetbyname/Microsoft.VisualStudio.Services.Icons.Default?redirect=true:1 GET https://dantup.gallery.vsassets.io/_apis/public/gallery/publisher/DanTup/ex….0/assetbyname/Microsoft.VisualStudio.Services.Icons.Default?redirect=true net::ERR_TUNNEL_CONNECTION_FAILED
> kevinplatel.gallery.vsassets.io/_apis/public/gallery/publisher/kevinplatel/…/assetbyname/Microsoft.VisualStudio.Services.Icons.Default?redirect=true:1 GET https://kevinplatel.gallery.vsassets.io/_apis/public/gallery/publisher/kevi….0/assetbyname/Microsoft.VisualStudio.Services.Icons.Default?redirect=true net::ERR_TUNNEL_CONNECTION_FAILED
> Microsoft.VisualStudio.Services.Icons.Default:1 GET https://dantup.gallery.vsassets.io/_apis/public/gallery/publisher/DanTup/ex…dart-code/0.13.0/assetbyname/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TUNNEL_CONNECTION_FAILED
> Microsoft.VisualStudio.Services.Icons.Default:1 GET https://kevinplatel.gallery.vsassets.io/_apis/public/gallery/publisher/kevi…nsion/dart/0.1.0/assetbyname/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TUNNEL_CONNECTION_FAILED

**Comment by joaomoreno** [comment] 2016-11-03 08:42
So... you can actually query for extensions right?

Can you take a look at this? http://troubleshooter.xyz/fix-err_tunnel_connection_failed-error-google-chrome/

**Comment by FloMaetschke** [comment] 2016-11-03 09:30
Yes! I can query and download extensions. But the images are not shown in the gallery.

**Comment by joaomoreno** [comment] 2016-11-03 09:45
Did you follow the guide I mentioned?

**Comment by FloMaetschke** [comment] 2016-11-03 13:04
Yes but it did not work.

**Comment by joaomoreno** [comment] 2017-04-26 08:59
Closing as dupe of proxy issues.

**Closed by joaomoreno** 2017-04-26 08:59 UTC
Labels: needs more info
