### ISSUE TITLE
Terminal not splitting

### ISSUE THREAD

**Issue by dan-nom** [Microsoft/vscode#63170] opened 2018-11-14 21:27 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Open the terminal
1. Click the 'Split Terminal' icon
1. Nothing happens

Expected results:
1. Open the terminal
1. Click the 'Split Terminal' icon
1. Terminal splits

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.14.67-07156-gc116f2c8c400

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 0|
|Memory (System)|4.84GB (3.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
tslint|eg2|1.0.40
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.5.1
prettier-vscode|esb|1.7.2
vscode-pull-request-github|Git|0.2.3
rest-client|hum|0.20.3
python|ms-|2018.10.1
debugger-for-chrome|msj|4.11.0
neuron-IPE|neu|1.0.3
bigquery-syntax-highlight|pen|0.0.2
sass-indented|rob|1.4.9
vscode-workspace-switcher|sad|1.9.0
code-settings-sync|Sha|3.2.0
vscodeintellicode|Vis|1.0.6

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment] 2018-11-15 09:20
Do you have `terminal.integrated.splitCwd` set in your settings file?

**Comment by polderudo** [comment] 2018-11-15 09:56
"terminal.integrated.splitCwd": "inherited" does not work.
workspaceRoot and initial works

**Comment by alexr00** [comment] 2018-12-05 14:05
duplicate of #62991

**Closed by alexr00** 2018-12-05 14:05 UTC
Labels: integrated-terminal, needs more info
