### ISSUE TITLE
macOS Look-Up word not work on VSCode

### ISSUE THREAD

**Issue by epsilonxe** [Microsoft/vscode#45290] opened 2018-03-08 12:44 UTC
- VSCode Version: 1.21.0
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Open any source file in VSCode, then select a word in the editor pane.
2. Launch look up word feature by using three-finger or force touch depending on the user setting.
3. Look up word  does not work anymore.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-03-08 13:17
> Look up word does not work anymore.

Are you saying this used to work?

**Comment by epsilonxe** [comment] 2018-03-08 14:13
@bpasero  Actually I just have tried VSCode for a week. 
I am quite sure that it worked in the previous version.
Unfortunately I have no earlier versions to test and confirm the problem, but it should work like other text editors.
Moreover I found another similar issue reported at https://github.com/Microsoft/vscode/issues/31047.

**Comment by bpasero** [comment] 2018-03-08 15:14
OK lets treat as duplicate of https://github.com/Microsoft/vscode/issues/31047

**Closed by bpasero** 2018-03-08 15:14 UTC
Labels: needs more info, new release
