### ISSUE TITLE
markdown.preview.scrollPreviewWithEditor broken

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#136174] opened 2021-10-30 19:50 UTC
Issue Type: <b>Bug</b>

Sometime in the last few releases the subject setting's behavior changed. It used to work by scrolling the preview so that it's first visible line matched the first visible line of the Markdown file being edited.

Now, instead, as text goes into the Markdown file, it continuously scrolls down, a line every couple of words, so that after half line of typing, the preview of the line you're typing is no longer visible. Scrolling the Markdown file brings it back into view, but typing starts the process all over again.

If I also turn on markdown.preview.scrollEditorWithPreview, the behavior of the preview window is the same, and the editor window scrolls also, meaning that my cursor is scrolled off the screen while I'm typing!

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (18.01GB free)|
|Process Argv|--crash-reporter-id 06338080-eec2-498d-98e0-cf3111dc1cde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (114)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
vscode-caniuse|aga|0.5.0
Bookmarks|ale|13.2.2
rtf|ale|2.3.0
vscode-sqlite|ale|0.13.0
swagger-viewer|Arj|3.1.2
armview|ben|0.4.5
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.12.1
markdown-yaml-preamble|bie|0.1.0
vscode-tldr|bmu|1.0.0
mermaid-markdown-syntax-highlighting|bpr|1.2.2
npm-intellisense|chr|1.4.0
gitignore|cod|0.7.0
disableligatures|Coe|0.0.10
vscode-markdownlint|Dav|0.44.4
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
dendron-snippet-maker|den|0.1.6
rushcore|Dev|1.0.2
rushnav|Dev|1.0.2
githistory|don|0.6.18
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
vscode-macros|EXC|1.2.0
git-project-manager|fel|1.7.1
scriptcsRunner|fil|0.1.0
vscode-firefox-debug|fir|2.9.4
vscode-npm|fkn|3.3.0
shell-format|fox|7.1.1
macros|ged|1.2.1
matlab|Gim|2.2.0
vscode-pull-request-github|Git|0.31.1
mdmath|goe|2.7.4
gc-excelviewer|Gra|3.0.44
beautify|Hoo|1.5.0
rest-client|hum|0.24.5
path-autocomplete|ion|1.17.1
mediawiki|jak|2.1.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
vscode-peacock|joh|3.10.1
gpg|jva|0.1.2
docomment|k--|0.1.20
vscode-liquid-snippets|kil|2.0.3
gnuplot|mam|1.0.5
markdown-shortcuts|mdi|0.12.0
openapi-lint|mer|1.2.0
HTMLHint|mka|0.10.0
azure-pipelines|ms-|1.191.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.5.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.1
vscode-bicep|ms-|0.4.1008
vscode-cosmosdb|ms-|0.18.1
csharp|ms-|1.23.16
vscode-dotnet-runtime|ms-|1.3.0
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.10.1
sql-database-projects-vscode|ms-|0.13.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.2
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscode-ai-remote|ms-|0.4.0
remote-containers|ms-|0.202.5
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.9
azurecli|ms-|0.5.0
live-server|ms-|0.2.9
mono-debug|ms-|0.16.2
powershell|ms-|2021.10.1
vscode-node-azure-pack|ms-|0.2.1
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.15.4
debugger-for-edge|msj|1.0.15
language-liquid|nei|0.1.1
azdo-wiki-md|ni|0.0.3
vscode-commons|red|0.0.6
vscode-yaml|red|1.0.0
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
toggle-case|rya|1.0.2
vscode-hexdump|sle|1.8.1
vscode-zipexplorer|sle|0.3.1
timestamp-converter|Sta|0.0.1
addDocComments|ste|0.0.8
code-spell-checker|str|2.0.10
code-spell-checker-greek|str|0.1.9
code-spell-checker-hebrew|str|0.1.8
code-spell-checker-medical-terms|str|1.0.12
code-spell-checker-spanish|str|2.0.2
msbuild-project-tools|tin|0.3.15
shell-launcher|Tyr|0.4.1
vscodeintellicode|Vis|1.2.14
nanoid-generator|vk-|0.1.2
vscode-icons|vsc|11.6.0
highlight-bad-chars|wen|0.0.5
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
t4-support|zbe|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246:30386377
vscrecpromptt3:30387013

```

</details>

**Comment by mjbvz** [comment] 2021-11-05 20:59
Duplicate of #89930

Please test in the latest insiders builds. If it isn't working as expected, share some example markdown and steps to reproduce the issue

**Closed by mjbvz** 2021-11-05 21:00 UTC

**Comment by af4jm** [comment] 2021-11-14 19:23
not only do I see this working correctly in Insiders, but 1.62.2 as well... thanks! (and sorry for being a bit late on this confirmation)
