### ISSUE TITLE
Menu items interleaving

### ISSUE THREAD

**Issue by dodalovicgran** [microsoft/vscode#188672] opened 2023-07-24 12:39 UTC
Type: <b>Bug</b>

```
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:25.257Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.6-76060206-generic
```

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:25.257Z)
OS version: Linux x64 6.2.6-76060206-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 4142)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.07GB (12.63GB free)|
|Process Argv|--unity-launch --crash-reporter-id 8b0f4ec5-17bd-4442-98fc-0a69ae52b2e5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
gitdiffer|aag|0.0.3
better-comments|aar|3.0.2
codesnap|adp|1.3.4
gitignore|cod|0.9.0
githistory|don|0.6.20
rust-syntax|dus|0.6.1
gitlens|eam|14.1.1
simple-new-file|fay|1.1.2
file-icons|fil|1.1.0
copilot|Git|1.98.275
vscode-test-explorer|hbe|2.21.1
rust-test-lens|hde|1.0.0
vscode-git-tags|how|1.4.4
rust-doc-viewer|JSc|3.0.4
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
vscode-docker|ms-|1.26.0
vscode-aks-tools|ms-|1.3.13
vscode-kubernetes-tools|ms-|1.3.13
remote-containers|ms-|0.299.0
azure-account|ms-|0.11.5
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5877
leaper|Onl|0.10.5
cargo|pan|0.2.3
subtle-brackets|raf|3.0.0
hippie-completion|rah|0.0.6
vscode-yaml|red|1.14.0
rust-analyzer|rus|0.3.1599
crates|ser|0.6.0
git-merger|sha|0.4.1
git-autoconfig|shy|0.0.2
vscode-rust-test-adapter|Swe|0.11.0
even-better-toml|tam|0.19.2
git-essentials|Tec|0.3.0
branch-warnings|tel|1.0.10
errorlens|use|3.12.0
vscode-lldb|vad|1.9.2
vscode-icons|vsc|12.4.0
gitblame|wad|10.4.0
vscode-todo-highlight|way|1.0.5
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|3.5.1
rust-extension-pack|Zer|1.1.0
vscode-open-in-github|ziy|1.3.6

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30795824
dsvsc013:30795093
dsvsc014:30791935

```

</details>

**Comment by dodalovicgran** [comment] 2023-07-24 12:39
Look at the left-hand side menu, the items are interleaved.
![image](https://github.com/microsoft/vscode/assets/116893230/3a40c111-9124-4b49-80dc-2ff3ef436da7)

**Comment by dodalovicgran** [comment] 2023-07-24 12:40
Look at the left-hand side menu, items are interleaved.

![image](https://github.com/microsoft/vscode/assets/116893230/3a40c111-9124-4b49-80dc-2ff3ef436da7)

**Comment by rzhao271** [comment] 2024-12-10 23:58
Closing as not reproducible. I wouldn't be surprised if there were some listview fixes since this issue was created.

**Closed by rzhao271** 2024-12-10 23:58 UTC
Labels: bug, settings-editor
