### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by qtbit** [Microsoft/vscode#44618] opened 2018-02-27 17:39 UTC
- VSCode Version: 1.21.0-insider
- OS Version: Win10

**Steps to Reproduce:**

1. run [Altap Salamander](https://www.altap.cz/salamander/downloads/) as administrator
2. run `code-insiders .` from its bottom command line (try more instances, one might work ok)
3. try to find something (ctrl+shift+F)

**Expected:** the search is working
**Actual:** spawn EACCES

![image](https://user-images.githubusercontent.com/25822015/36744554-6e153162-1bed-11e8-9e33-11dd4f9a74bc.png)

**Comment by tsalinger** [comment] 2018-02-28 08:37
I cannot reproduce it on Win10. @aeschli might be related to #43128

**Comment by chrmarti** [comment] 2018-02-28 10:43
How did you install VS Code? This looks like the current login does not have permissions to access rg.exe. /cc @joaomoreno

**Comment by qtbit** [comment] 2018-02-28 10:51
It seems it is related to Altap Salamander command line. It's a filemanager in classic old style with command line at the bottom. Running vscode from its command line causes the issue. I've update the steps.

**Comment by chrmarti** [comment] 2018-02-28 11:05
Is that file manager running under a different login than yours?

**Comment by qtbit** [comment] 2018-02-28 11:13
I believe not. How I can check that to be sure?

**Comment by chrmarti** [comment] 2018-02-28 13:36
Does unchecking that and then restarting the file manager fix the issue? I'm surprised the admin account cannot access that file, but maybe that is expected in this setup.

**Comment by qtbit** [comment] 2018-02-28 13:54
Yes, it works by unchecking that. It also works if I run the filemanager as admin by right clicking the filemanager icon and choosing "Run as administrator".

![image](https://user-images.githubusercontent.com/25822015/36790997-e3a12928-1c96-11e8-811c-e40b17c44781.png)

However, I get EACCESS error when I check "Run this program as an administrator" checkbox in Compatibility tab.

![image](https://user-images.githubusercontent.com/25822015/36791022-f9c11ef2-1c96-11e8-9ce6-fff2f910c221.png)

**Comment by qtbit** [comment] 2018-02-28 14:34
I tried to check the "Run this program as an administrator" checkbox in Compatibility tab for code-insiders and then run it - it crashed.

![image](https://user-images.githubusercontent.com/25822015/36793063-a24121da-1c9c-11e8-96a2-27a584ccc93f.png)

**Comment by chrmarti** [comment] 2018-02-28 16:05
Thanks for investigating. I'm closing this as it is a problem with how you launch VS Code, not VS Code itself.

**Closed by chrmarti** 2018-02-28 16:05 UTC
Labels: insiders

**Comment by qtbit** [comment] 2018-02-28 16:36
What? VS Code crashes, can't search and it's not its problem???

**Comment by chrmarti** [comment] 2018-03-01 06:40
@joaomoreno Can you advice on how we handle these cases? Are these known issues?

**Comment by joaomoreno** [comment] 2018-03-01 08:12
cc @bpasero
