### ISSUE TITLE
Preferences sync notification

### ISSUE THREAD

**Issue by Kinrany** [microsoft/vscode#94902] opened 2020-04-10 12:34 UTC
Issue Type: <b>Bug</b>

Notification "Preferences Sync: Sign in to sync (1)" won't go away

VS Code version: Code - Insiders 1.45.0-insider (c12bd56a8886f31e353a45f5846f0a35a52f908e, 2020-04-10T05:39:20.415Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.07GB free)|
|Process Argv|-psn_0_2286126|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.2
gitlens|eam|10.2.1
file-icons|fil|1.0.23
vscode-mocha-test-adapter|hbe|2.3.0
vscode-test-explorer|hbe|2.17.0
vscode-edit-csv|jan|0.2.6
vscode-js-annotations|lan|0.11.0
vscode-typescript-to-json-schema|mar|0.0.13
rust-analyzer|mat|0.2.117
vscode-http-client|mkl|0.34.0
vscode-docker|ms-|1.0.0
sqltools|mtx|0.21.6
vscodeintellicode|Vis|1.2.6

</details>

**Comment by RMacfarlane** [comment] 2020-04-10 17:44
Duplicate of https://github.com/microsoft/vscode/issues/94822

**Closed by RMacfarlane** 2020-04-10 17:44 UTC
