### ISSUE TITLE
Integrated terminal some texts are blank

### ISSUE THREAD

**Issue by NiloDrumond** [microsoft/vscode#95142] opened 2020-04-13 18:44 UTC
- VSCode Version: 1.44.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open integrated terminal
2. Use any command that keeps returning text for some period of time (like yarn add, yarn start or git push)

Does this issue occur when all extensions are disabled?: Yes

The integrated terminal shows some of the text (like in this case yarn run. yarn help also works fine), but all "in progress" text are blank:
![image](https://user-images.githubusercontent.com/48765760/79148925-b0096f80-7d9c-11ea-9647-5c39f84cd807.png)

The same doesn't happen if i use git bash or hyper with bash
![image](https://user-images.githubusercontent.com/48765760/79149090-f8c12880-7d9c-11ea-8cb2-f5b9ad32a174.png)

**Comment by IllusionMH** [comment] 2020-04-13 19:27
/duplicate of #57803

Looks like you've encountered bug in W10 1809 and only workaround is update to W10 1903 

See https://github.com/microsoft/vscode/issues/57803#issuecomment-449495423 for details

**Closed** 2020-04-13 19:28 UTC
Labels: *duplicate
