### ISSUE TITLE
Debugging no longer working since Sept 14th update

### ISSUE THREAD

**Issue by mredbishop** [Microsoft/vscode#12078] opened 2016-09-15 13:56 UTC
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/1096293/18552448/6096090c-7b54-11e6-8308-7b4cb69ee677.png)

- OS Version: Windows 10

Steps to Reproduce:

Debugging our typescript application using the app.ts file in the route was working right up to yesterday. It now does not start the app. 

It appears to be related to the source maps setting = true in the launch.json as setting this to false and running against the app.js works.

This is critical to ours and I imagine many other peoples debug process.

**Comment by bpasero** [comment] 2016-09-15 15:20
@weinand might be fixed by now?

**Comment by mredbishop** [comment] 2016-09-15 15:21
Nope :)

**Comment by weinand** [comment] 2016-09-16 13:17
@mredbishop please try the latest Insider build.

**Comment by mredbishop** [comment] 2016-09-16 15:25
Hey @weinand, I've just tried it and it still won't launch the debugger for ts files with the sourceMaps on.

**Comment by weinand** [comment] 2016-09-16 15:43
@mredbishop what is the value of your 'outDir' attribute?

**Comment by mredbishop** [comment] 2016-09-17 10:33
"configurations": [
        {
            // Name of configuration; appears in the launch configuration drop down menu.
            "name": "Debug Server",
            // Type of configuration. Possible values: "node", "mono".
            "type": "node",
            // Workspace relative or absolute path to the program.
            "program": "${workspaceRoot}/app.ts",
            // Automatically stop program after launch.
            "stopOnEntry": false,
            // Command line arguments passed to the program.
            "args": [
                "--color"
            ],
            // Workspace relative or absolute path to the working directory of the program being debugged. Default is the current workspace.
            "cwd": "${workspaceRoot}",
            // Workspace relative or absolute path to the runtime executable to be used. Default is the runtime executable on the PATH.
            "runtimeExecutable": null,
            // Optional arguments passed to the runtime executable.
            "runtimeArgs": [],
            // Environment variables passed to the program.
            "env": {},
            // Use JavaScript source maps (if they exist).
            "sourceMaps": true,
            // If JavaScript source maps are enabled, the generated code is expected in this directory.
            "outDir": "${workspaceRoot}",
            "request": "launch",
            "smartStep": true
        },

**Comment by mredbishop** [comment] 2016-09-19 09:40
@weinand This is now fixed by the looks. Just ran the latest insiders update and tested it.

Thanks :)

Ed

**Comment by weinand** [comment] 2016-09-19 10:35
@mredbishop the problem was probably the value of ${outDir}. Recently we changed the handling of outDir to search for all source maps eagerly and not only on demand. Due to this [bug](https://github.com/Microsoft/vscode/issues/12138) in our code we would stumble over the first broken or missing sourcemap while searching in ${outDir}. As long as you confine ${outDir} to only the folder where the generated code lives, the problem with broken or missing sourcemaps typically does not occur. 
But since you are specifying ${workspaceRoot}, VS Code will search the node_modules folder as well. And there it is very likely that a broken source map exists.
The problem has been fixed in the latest, but I recommend that you still try to set ${outDir} to a subfolder of your project folder because this will speed up source map handling.
(In the September release VSCode will support globbing for the outDir attribute.)

**Comment by weinand** [comment] 2016-09-19 10:35
duplicate of #12138

**Closed by weinand** 2016-09-19 10:35 UTC
Labels: bug, debug

**Comment by mredbishop** [comment] 2016-09-19 10:42
@weinand Unfortunately it would be a big change to our structure to move to a sub folder as our code is split between 3 main modules that are in directories off the root. We wouldn't do this if we were making a new app but this structure is legacy.

The globbing would ultimately solve the issue for us and really speed up our start time when debugging. When is that likely to make it to Insiders?

Thanks for all the updates by the way, we can't tell you how much time and effort is saved by having VS Code in our tool chain, It's awesome!

**Comment by weinand** [comment] 2016-09-19 10:53
@mredbishop you can already use the globbing in Insiders. Just use the new `outDirs` attribute and specify an array, e.g. if your generated code lives in "out", "bin", and "dist" use this:
```json
   "outDirs": [
      "${workspaceRoot}/out/**/*.js",
      "${workspaceRoot}/bin/**/*.js",
      "${workspaceRoot}/dist/**/*.js",
   ]
```

**Comment by weinand** [comment] 2016-09-19 16:05
@mredbishop attribute name change ahead!:
in the next Insider build the name of the attribute "outDirs" will become "outFiles" to better reflect what those glob patterns specify. This name will be the final name appearing in the September release.

**Comment by mredbishop** [comment] 2016-09-19 18:21
@weinand Thanks very much that's really great! We'll switch over once the name changes.

**Comment by weinand** [comment] 2016-09-19 20:46
@mredbishop btw, you can express the three folders case more simple:
```json
   "outDirs": [
      "${workspaceRoot}/{out,bin,dist}/**/*.js"
   ]
```

**Comment by weinand** [comment] 2016-09-20 08:43
@mredbishop the current Insiders now supports the `outFiles` attribute.

**Comment by ramya-rao-a** [comment] 2016-09-29 21:15
Marking as verified as @mredbishop does not have the issue with the latest insiders
