### ISSUE TITLE
Allow to theme UI components of the workbench

### ISSUE THREAD

**Issue by oliverhr** [Microsoft/vscode#1231] opened 2015-12-13 19:45 UTC
Is there a way to write a theme who also change color for UI components - Ej. affect sidebar and view bar.

Or this should be written separatelly like atom ui themes and syntax theme ?

**Comment by egamma** [comment] 2015-12-14 08:21
@aeschli fyi

**Comment by aeschli** [comment] 2015-12-14 10:20
No, there's currently now way to theme UI components other than the editor.

**Comment by oliverhr** [comment] 2015-12-14 16:39
Thank you @egamma / @aeschli

**Comment by SrTobi** [comment] 2015-12-21 15:32
Is this planed? I think its not that hard to load additional css styles overwriting the defaults.

**Comment by egamma** [comment] 2015-12-21 20:14
Agreed it is not hard and it is on the backlog, but many things are on the backlog that are not hard but still take time, as are things that are hard and take a lot of time :smile:

**Comment by Tyriar** [comment] 2016-05-26 18:12
Duplicate of https://github.com/Microsoft/vscode/issues/76

**Closed by Tyriar** 2016-05-26 18:12 UTC
Labels: api, feature-request, workbench

**Comment by equinusocio** [comment] 2017-01-24 16:12
Refer https://github.com/Microsoft/vscode/issues/17608
