### ISSUE TITLE
Multiline editing for 0-length rows

### ISSUE THREAD

**Issue by Roman-Tarasiuk** [microsoft/vscode#67784] opened 2019-02-02 09:27 UTC
When you select multiple lines for editing (e.g. Alt+Shift+Mouse Click) and some of them contain line with no text (\r\n only), cursor in that lines goes to the line begin.
It would be better behavior like in the Visual Studio text editor (or as in Notepad++): multiple cursors go in one column (spaces before cursor in 0-length line are filled automatically), this is much more better e.g. for commenting all lines simultaneously and comments go in the same indent from the line begin.

**Comment by alexandrudima** [comment] 2019-10-17 20:14
Duplicate of #5402

**Closed by alexandrudima** 2019-10-17 20:14 UTC
Labels: editor-columnselect, feature-request
