### ISSUE TITLE
Disable peek editor and just open the file directly when there are multiple definitions

### ISSUE THREAD

**Issue by fabriciorissetto** [Microsoft/vscode#34755] opened 2017-09-21 13:50 UTC
I'ld like to know if there is a way to:

When I press `F12` (Go to Definition) just open the file **without** the "peek editor" opened.

I mean, the current behavior is that when you press F12: 
* **First**: the related file is opened
* **Second**: you're faced with the "Peed editor"  

![screen shot](https://user-images.githubusercontent.com/376842/28370365-05244f72-6c92-11e7-8ed6-f9247f153911.png)
* **Third**: I usually press `ESC' to close it and stay in the file

I don't want to need to press that `ESC`. There is a way to configure it?

Related [question](https://stackoverflow.com/questions/41460845/disable-peek-in-visual-studio-code) on SO with 11 upvotes and no answer.

**Comment by ramya-rao-a** [comment] 2017-09-21 15:49
If a random file is chosen among the multiple definitions, how would you suggest we notify the user that there are multiple definitions?

**Comment by jrieken** [comment] 2017-09-21 16:11
F12 does that, it goes to the definition of a symbol but when there are multiple we cannot throw dice, so it is unclear how to make a decision. That's why we show all definition when there are than 1. @fabriciorissetto what do you suggest, what definitions should we ignore? We can add another command like "go to any definition" and folks can bind that to F12

**Comment by fabriciorissetto** [comment] 2017-09-21 19:46
Sorry folks, I had not seen this behavior, so it happens just in case of multiple definitions. The behavior makes sense. I think you can close the issue.

**Comment by Gruntfuggly** [comment] 2017-09-21 19:48
I don't understand why it opens the first editor in the list though - if there are multiple definitions, surely it should leave the original file open and show the peek view. If you press Escape it should return you to the originating file - not the first file it opened?

**Comment by jrieken** [comment] 2017-09-22 06:45
> I don't understand why it opens the first editor in the list though

That is the different between 'Peek Definition' and 'Go to Definition'. With the latter we try to bring you the definition and in case of many do that while also showing the other definitions. The former is what you describe. 


Hope that clarifies things. Closing based on https://github.com/fabriciorissetto

**Closed by jrieken** 2017-09-22 06:45 UTC
Labels: editor-workspace-symbols, needs more info

**Comment by jgale** [comment] 2017-11-17 15:27
I too had this question and was hoping to disable Peeks completely. I hadn't realized that it was only when you have multiple definitions. I think there may be something buggy with that logic. Here is an example where I cmd-clicked on a QuotesContainer component in JSX and it jumped to the definition - both of the definitions are from the exact same line, they are the same component. Clicking the different definitions does not change the content of the Peek at all.

![screenshot 2017-11-17 08 24 07](https://user-images.githubusercontent.com/942250/32954637-ebea9f32-cb70-11e7-8b77-0c16afbc13d5.png)

Is there any way for me to workaround it showing both of these definitions, which are actually the same?

Thanks!

**Comment by ramya-rao-a** [comment] 2017-11-17 17:32
@jgale If both the definitions are the same, then the issue is with the language service that is providing the definitions. From the perspective of the Peek control, there are more than 1 definition, and it reacts accordingly.
