### ISSUE TITLE
Feature request: As a user, I should be able to configure extensions contributed settings in language based settings

### ISSUE THREAD

**Issue by xahon** [Microsoft/vscode#37464] opened 2017-11-02 03:31 UTC
- VSCode Version: 1.17.2
b813d12980308015bcd2b3a2f6efa5c810c33ba5

- OS Version: Ubuntu 16.04

Now it's impossible to set plugin settings (i.e. emmet settings) based on current filetype

I wanna disable emmet and beautifiers, prettifiers when i'm in `["makefile"]` buffer, but for now only editor settings are available to customize.

May be i missed something or the same question already asked but i didn't found

**Comment by xahon** [comment] 2017-11-02 03:32
I'm sorry for emmet auto-assigned label

**Comment by ramya-rao-a** [comment] 2017-11-02 05:35
So basically you are asking for the feature to have settings coming from extensions to be set at file type level?

**Comment by xahon** [comment] 2017-11-02 06:19
@ramya-rao-a yes. Now i'm not able to disable prettier when i'm in `makefile` file type

**Comment by ramya-rao-a** [comment] 2017-11-02 15:21
@sandy081 Am sure there is already a feature request for this, but I couldn't find the issue.

**Comment by sandy081** [comment] 2017-11-02 15:27
I am sure there is one. But not able to find :(. Added to my bookmarks when I found the old one will make this duplicate.

**Comment by sandy081** [comment] 2017-11-17 14:49
Duplicate of #19642

**Closed by sandy081** 2017-11-17 14:49 UTC
Labels: config, feature-request
