### ISSUE TITLE
Unable to start Fish shell integrated terminal

### ISSUE THREAD

**Issue by wardy3** [microsoft/vscode#178910] opened 2023-04-01 23:33 UTC
Type: <b>Bug</b>

after upgrading to the latest Insiders, i can no longer use the intetrated terminal, which was fish. I have fish set via `chsh`

I get these messages:
```
warning: No TTY for interactive shell (tcgetpgrp failed)
setpgid: Inappropriate ioctl for device
```

Also, if i `chsh` to use zsh, it starts ok. But ...
```
(bank-py3.11) wardy@Wardys-MB-16 bank % fish -l
warning: No TTY for interactive shell (tcgetpgrp failed)
setpgid: Inappropriate ioctl for device
```

fish, version 3.6.1

![image](https://user-images.githubusercontent.com/15006782/229322746-9df3a46c-a79b-466c-8d24-1cd52ef20198.png)

VS Code version: Code - Insiders 1.78.0-insider (Universal) (f31dffc7f9b93a1cdef21243ec30dea7d489a615, 2023-03-31T01:49:03.052Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 9, 19|
|Memory (System)|32.00GB (1.08GB free)|
|Process Argv|--crash-reporter-id e45c21e3-3270-4be4-bf1b-d02853448a5e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.49.0
gitlens|eam|13.4.0
json-tools|eri|1.0.2
gitlab-workflow|Git|3.60.0
jq-syntax-highlighting|jq-|0.0.2
mypy|mat|0.2.3
rainbow-csv|mec|3.6.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.24.0
black-formatter|ms-|2023.1.10901017
flake8|ms-|2023.5.10901011
isort|ms-|2023.9.10861010
python|ms-|2023.7.10901017
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.101.2023032915
live-server|ms-|0.4.7
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
fix-json|oli|0.1.2
vscode-yaml-sort|Pas|6.5.0
vscode-yaml|red|1.12.2
vscode-sort-json|ric|1.20.0
perl|ric|2.5.0
vscode-coverage-gutters|rya|2.10.4
jinjahtml|sam|0.20.0
markdown-preview-enhanced|shd|0.6.8
sourcery|sou|1.1.0
tabnine-vscode|Tab|3.6.43
markdowntable|Tak|0.10.4
even-better-toml|tam|0.19.0
pdf|tom|1.2.2
errorlens|use|3.8.0
vscode-icons-mac|way|7.25.3
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
pythonb192cf:30661257
azdwalk:30687957
pythonms35:30671666
19089226:30680468
7ij38806:30687742
pythonclientmv:30700173

```

</details>

**Comment by Ovyerus** [comment] 2023-04-02 03:29
Happening to me as well

**Comment by tamuratak** [comment] 2023-04-02 05:09
Might be duplicate of #178810

**Comment by pebabion** [comment] 2023-04-03 13:43
Same for me.

**Closed** 2023-04-03 18:31 UTC

**Comment by EugeneTM** [comment] 2023-04-23 18:25
Same for me, but only on a certain box. This does not work
Version: 1.78.0-insider
Commit: b19017cea80b6157aa8214c984a70022e77526f2
Date: 2023-04-21T05:24:11.937Z
Electron: 22.4.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 17.7.0
Sandboxed: Yes
