### ISSUE TITLE
Better merge notification popped up after upgrade to latest insiders

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#38926] opened 2017-11-22 06:59 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (55866fc4c69056a20e8464a283ca3d874d1f8dcb, 2017-11-22T05:13:55.378Z)
- OS Version: Windows_NT x64 10.0.17040
---

When vscode re-opened after the latest insiders upgrade, I was presented with this message:
![image](https://user-images.githubusercontent.com/641685/33113949-942124fe-cf28-11e7-8f68-1c646dc1d5d4.png)

Better merge has been gone for a long time, and I verified I don't have any remnants of it in my `.vscode-insiders/extensions` folder

The only change I see in that area was: https://github.com/Microsoft/vscode/commit/2fd817b55752e571e9a434e8658c5f2511d2f70b

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-11-22 09:09
duplicate of #38930

**Closed by egamma** 2017-11-22 09:09 UTC
Labels: insiders
