### ISSUE TITLE
Terminal bugs

### ISSUE THREAD

**Issue by HolyOne** [microsoft/vscode#117837] opened 2021-02-27 22:05 UTC
Issue Type: <b>Bug</b>

Firstly, when I open a new powershell terminal I do not see any prompt until I press enter or any key.

Second, "clear" command clears the screen but after I run a command, I see previous buffers so terminal is not really cleared.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
laravel-extra-intellisense|ami|0.5.1
vscode-intelephense-client|bme|1.6.3
vscode-tailwindcss|bra|0.5.9
laravel-goto-view|cod|1.3.4
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.66
php-debug|fel|1.14.9
vscode-nuget-package-manager|jmr|1.1.6
dotenv|mik|1.0.1
laravel-intellisense|moh|0.2.0
csharp|ms-|1.23.9
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.603412351
remote-wsl|ms-|0.53.4
cpptools|ms-|1.2.2
vsliveshare|ms-|1.0.3784
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.11.0
laravel-artisan|rya|0.0.27
laravel-goto-controller|ste|0.0.12
vscode-arduino|vsc|0.3.5
html-css-class-completion|Zig|1.20.0

</details>

**Comment by meganrogge** [comment] 2021-03-01 16:51
Duplicate of #116610

**Closed** 2021-03-01 16:51 UTC
Labels: *duplicate, bug, integrated-terminal
