### ISSUE TITLE
[Windows+MSYS2] `doesn't have a git repository` except it is a git repository.

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode#180440] opened 2023-04-20 20:00 UTC
Does this issue occur when all extensions are disabled?: Yes/No

```
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

Steps to Reproduce:

1. Install MSYS2
2. Install git under MSYS2
3. Run `code . --log trace` in the git folder

```log
2023-04-20 15:57:32.592 [info] Log level: Trace
2023-04-20 15:57:32.592 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2023-04-20 15:57:32.592 [info] Validating found git in: "C:\Program Files (x86)\Git\cmd\git.exe"
2023-04-20 15:57:32.592 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2023-04-20 15:57:32.592 [info] Validating found git in: "C:\Users\xiaoh\AppData\Local\Programs\Git\cmd\git.exe"
2023-04-20 15:57:32.592 [info] Validating found git in: "C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe"
2023-04-20 15:57:32.682 [info] Using git "2.40.0" from "C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe"
2023-04-20 15:57:32.683 [trace] [swf] Scan workspace folders: [d:\dev\icewhale\zima-client-backup]
2023-04-20 15:57:32.694 [trace] [svte] Scan visible text editors. autoRepositoryDetection=true
2023-04-20 15:57:32.694 [trace] [svte] Open repository for editor resource d:\dev\icewhale\zima-client-backup\fsnotify_service.go
2023-04-20 15:57:32.694 [trace] [swsf] Scan workspace sub folders. autoRepositoryDetection=true
2023-04-20 15:57:32.694 [trace] [swsf] Workspace folder: d:\dev\icewhale\zima-client-backup
2023-04-20 15:57:32.695 [trace] Opening repository: d:\dev\icewhale\zima-client-backup
2023-04-20 15:57:32.697 [trace] [swsf] Workspace scan settings: repositoryScanMaxDepth=1; repositoryScanIgnoredFolders=[node_modules]; scanRepositories=[]
2023-04-20 15:57:32.697 [trace] [swsf] Workspace scan sub folders: [d:\dev\icewhale\zima-client-backup\.vscode, d:\dev\icewhale\zima-client-backup\api, d:\dev\icewhale\zima-client-backup\codegen, d:\dev\icewhale\zima-client-backup\internal]
2023-04-20 15:57:32.839 [info] > git rev-parse --show-toplevel [142ms]
2023-04-20 15:57:32.841 [trace] Repository root for path d:\dev\icewhale\zima-client-backup is: \d\dev\icewhale\zima-client-backup
2023-04-20 15:57:32.841 [trace] Opening repository for path='d:\dev\icewhale\zima-client-backup' failed; ex=spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-04-20 15:57:32.847 [trace] Opening repository: d:\dev\icewhale\zima-client-backup
2023-04-20 15:57:32.986 [info] > git rev-parse --show-toplevel [138ms]
2023-04-20 15:57:32.987 [trace] Repository root for path d:\dev\icewhale\zima-client-backup is: \d\dev\icewhale\zima-client-backup
2023-04-20 15:57:32.988 [trace] Opening repository for path='d:\dev\icewhale\zima-client-backup' failed; ex=spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-04-20 15:57:33.030 [trace] Opening repository: d:\dev\icewhale\zima-client-backup\.vscode
2023-04-20 15:57:33.218 [info] > git rev-parse --show-toplevel [189ms]
2023-04-20 15:57:33.220 [trace] Repository root for path d:\dev\icewhale\zima-client-backup\.vscode is: \d\dev\icewhale\zima-client-backup
2023-04-20 15:57:33.220 [trace] Opening repository for path='d:\dev\icewhale\zima-client-backup\.vscode' failed; ex=spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-04-20 15:57:33.237 [trace] Opening repository: d:\dev\icewhale\zima-client-backup\api
2023-04-20 15:57:33.328 [info] > git rev-parse --show-toplevel [91ms]
2023-04-20 15:57:33.330 [trace] Repository root for path d:\dev\icewhale\zima-client-backup\api is: \d\dev\icewhale\zima-client-backup
2023-04-20 15:57:33.330 [trace] Opening repository for path='d:\dev\icewhale\zima-client-backup\api' failed; ex=spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-04-20 15:57:33.337 [trace] Opening repository: d:\dev\icewhale\zima-client-backup\codegen
2023-04-20 15:57:33.511 [info] > git rev-parse --show-toplevel [175ms]
2023-04-20 15:57:33.513 [trace] Repository root for path d:\dev\icewhale\zima-client-backup\codegen is: \d\dev\icewhale\zima-client-backup
2023-04-20 15:57:33.513 [trace] Opening repository for path='d:\dev\icewhale\zima-client-backup\codegen' failed; ex=spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-04-20 15:57:33.526 [trace] Opening repository: d:\dev\icewhale\zima-client-backup\internal
2023-04-20 15:57:33.652 [info] > git rev-parse --show-toplevel [126ms]
2023-04-20 15:57:33.654 [trace] Repository root for path d:\dev\icewhale\zima-client-backup\internal is: \d\dev\icewhale\zima-client-backup
2023-04-20 15:57:33.655 [trace] Opening repository for path='d:\dev\icewhale\zima-client-backup\internal' failed; ex=spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Users\xiaoh\AppData\Local\msys2\usr\bin\git.exe ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Not exactly the same issue as https://github.com/microsoft/vscode/issues/173226

**Comment by gjsjohnmurray** [comment] 2023-04-20 20:34
Probably a duplicate of #143165

**Closed** 2023-04-25 13:54 UTC
