### ISSUE TITLE
Problem with typescript.tsdk in vscode workspace

### ISSUE THREAD

**Issue by asfernandes** [microsoft/vscode#106563] opened 2020-09-13 01:54 UTC
- VSCode Version: 1.49.0
- OS Version: Ubuntu 20.04

I'm trying to configure yarn v2 pnpfy vscode + typescript sdk in a vscode workspace and yarn workspace with multiple projects.

I put `typescript.tsdk` setting in a relative path of the workspace (`".yarn/sdks/typescript/lib"` or `"./.yarn/sdks/typescript/lib"`).

When opening vscode workspace and setting the typescript prompt, vscode updates the workspace setting and put the absolute path there. Of course this is not desired.

**Comment by asfernandes** [comment] 2020-09-13 02:01
The automatic change in settings is also happening with yarn v1 too.

I'm sure it didn't happened in old versions as my workspace was using the same setup.

**Comment by asfernandes** [comment] 2020-09-13 02:07
Also, the `typescript.tsdk` setting as I used was prefixed with `root/` and it's the same. VSCode automatically updates the workspace setting to the absolute path after select the version using the typescript prompt selector.

**Comment by mjbvz** [comment] 2020-09-13 08:26
Duplicate of #105202. Should already be fixed in the current insiders builds

**Closed by mjbvz** 2020-09-13 08:26 UTC
Labels: new release

**Comment by karol1990** [comment] 2020-10-06 23:10
@mjbvz unfortunately this problem doesn't seem to be solved. I'm using yarn 2.3.1 (which strongly relies on workspace ts settings) in following environment: 

Version: 1.49.3 (system setup)
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:57:01.595Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041 

Initial value of mine typescript.tsdk is: "typescript.tsdk": ".yarn/sdks/typescript/lib" and after "select ts to workspace version" it changes to absolute path. It's very not desired behavior, especially because workspace file is under version control. 

Worth to mention that, if you update the ts version to workspace one by "typescript.enablePromptUseWorkspaceTsdk": true popup then the path doesn't get updated.
