### ISSUE TITLE
Editor hover is easily lost in editor content

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7917] opened 2016-06-21 09:25 UTC
I am not a big fan of our hover when it has lots of contents because the content blends too easy into the other contents of the editor making it hard to read.

![image](https://cloud.githubusercontent.com/assets/900690/16224554/c9e51f4c-37a2-11e6-8c17-06b18d24fc45.png)

At the minimum the hover should have a different background color. Also in this example the JS doc comments look very similar to the actual method signature. I would love if both could be made more distinct so that its clear the one is documentation and the other is signature.

/cc @joaomoreno @bgashler1 @stevencl @alexandrudima

**Comment by joaomoreno** [comment] 2016-06-22 06:00
cc @jrieken

**Comment by joaomoreno** [comment] 2016-06-22 06:00
Duplicate of #2330

**Closed by joaomoreno** 2016-06-22 06:00 UTC
Labels: bug, color, ux
