### ISSUE TITLE
Invalid comparison: Error: Invalid comparison

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#126874] opened 2021-06-22 03:35 UTC
Does this issue occur when all extensions are disabled?: Yes/No

Yes

Version:

```
Version: 1.57.1 (Universal)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

Steps to Reproduce:

1. open my git repository which is a workspace
2. toggle source control panel, however it is empty
3. open devTools

![image](https://user-images.githubusercontent.com/41773861/122858922-b6568c80-d34d-11eb-8363-9291917d8997.png)

**Comment by lszomoru** [comment] 2022-01-05 15:13
This looks like a duplicate of #138734. Closing the issue for now.
Please reopen the issue if you are able to reproduce the problem with the latest Insiders release.

**Closed by lszomoru** 2022-01-05 15:13 UTC
Labels: bug, git
