### ISSUE TITLE
`files.insertFinalNewline` conflicts with `source.organizeImports` on save

### ISSUE THREAD

**Issue by dotdoom** [Microsoft/vscode#65733] opened 2018-12-27 14:34 UTC
Issue Type: <b>Bug</b>

1. Set `insertFinalNewline` to "true" in Settings.

1. Create a file (ex.: `nodemailer.d.ts`) with the following content

   ```
   declare module 'nodemailer.d.ts';
   ```

1. Save the file. Observe that a newline is not added.

1. Remove everything after `declare module`. Save. Observe that a newline is added.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 2635)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.56GB (0.92GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
polymer-ide|pol|0.6.0
vscode-bolt-language|smk|0.0.4

</details>

**Comment by bpasero** [comment] 2018-12-28 08:00
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dotdoom** [comment] 2018-12-28 08:08
Thanks, this is fair. Here's what I just did:

1. exit VSCode

1. start VSCode from a terminal in an empty directory

   ```shell
   $ code --disable-extensions nodemailer.d.ts
   ```

   noted that a pop up appears telling me that extensions are disabled.

1. type `declare module 'nodemailer.d.ts';`, hit `^S` (save). Observe that a newline is still **not** added.

**Comment by bpasero** [comment] 2018-12-28 08:20
@dotdoom can you share your settings?

**Comment by bpasero** [comment] 2018-12-28 09:01
I still cannot reproduce, here is what I see: 
![before](https://user-images.githubusercontent.com/900690/50509805-81706400-0a87-11e9-8202-463960b0c890.gif)

**Comment by bpasero** [comment] 2018-12-28 09:50
Thanks, so this seems to be triggered by a code action. Moving to @mjbvz (also @jrieken fyi)

**Comment by mjbvz** [comment] 2019-01-02 21:55
Caused by https://github.com/Microsoft/TypeScript/issues/29236 upstream

I'll look into making the VS Code side of this more reliable so that other save participates are still run if the code actions fail

**Closed** 2019-01-02 22:37 UTC
Labels: bug, javascript
