### ISSUE TITLE
Notifications - Clicking the gear pauses the notification animation

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#44683] opened 2018-02-28 00:01 UTC
Testing https://github.com/Microsoft/vscode/issues/44319

Clicking in the little gear in the activity bar pauses the animation of the toast, leaving it in a weird state.

<img width="501" alt="notification" src="https://user-images.githubusercontent.com/5607882/36762030-84b5635e-1bd6-11e8-9784-c4e69fcfb1ce.png">

Steps to Reproduce:

1. Click the Gear
2. Click `Check for updates`
3. Wait a bit and click the Gear again

Checked on stable and it has the same issue (in the old version of the notifications).

**Comment by bpasero** [comment] 2018-02-28 05:46
Duplicate of https://github.com/Microsoft/vscode/issues/23085

**Closed by bpasero** 2018-02-28 05:46 UTC
