### ISSUE TITLE
Import @angular in *.ts file - red underline in path.

### ISSUE THREAD

**Issue by alan-mroczek** [Microsoft/vscode#35301] opened 2017-09-28 07:38 UTC
- VSCode Version: 2.5.3-insiders.20170919
- OS Version: Win 7, 64-bit

Steps to Reproduce:

1. Install angular via npm
2. Import it in ts module (eg. `import { NgModule } from '@angular/core';`)
3. You can see that VS Code underlines path (may it be issue with at sign in @angular?)

Reproduces without extensions: Yes

Error does not occur if I import for example rxjs/Rx.

If I do instead `import { NgModule } from '@angular/core/core';` from example above,  it works, however it is not valid path, and app does not build.

It worked properly in previous build.

**Warning**: VS Code underlines import path after few seconds

**Comment by mjbvz** [comment] 2017-09-29 17:50
Duplicate of #34681

As Andy suggests, try installing `npm install -g typescript@2.5.3`, then [set up](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) vscode to use it

**Closed by mjbvz** 2017-09-29 17:50 UTC
Labels: javascript
