### ISSUE TITLE
Symbol loses its 'function' semantic token type when extra properties are added to its type

### ISSUE THREAD

**Issue by fgallardograzio** [microsoft/vscode#91168] opened 2020-02-21 18:30 UTC
Issue Type: <b>Bug</b>

Given:

```typescript
interface MyFunc {
    (): void;
}

let myFunc: MyFunc;
```

Here, `myFunc` is correctly assigned the `'function'` semantic token type.

Then, add an additional property to the `MyFunc` type, such as:

```typescript
interface MyFunc {
    (): void;
    attr: string;
}

let myFunc: MyFunc;
```

Now `myFunc` gets assigned a simple `'variable'` semantic token type instead.

Note that this also happens when types are inferred for a `const` declaration:

```typescript
const myInferredConstFunc = () => {}; 
```

When the myFunc symbol is declared and assigned a function (can be either a regular ES5 function or an arrow function), it's properly assigned a `'function'` semantic token.
But when you add an additional property to it:

```typescript
myInferredConstFunc.attr = 'str';
```

Now the `'function'` semantic token is lost.

But, function declarations are fine, though:

```typescript
function myFuncDec() {}
myFuncDec.attr = 'str';
```

There, `myFuncDec` still keeps its `'function'` semantic token.

----

I believe this used to work fine until yesterday.

**Related issues**: https://github.com/microsoft/vscode/issues/89337

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:40:52.685Z)
OS version: Linux x64 5.0.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2937)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.43GB (2.94GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by fgallardograzio** [comment] 2020-02-21 22:35
Looking at the code, I found commit [102a3a1 from aeschli/typescript-vscode-sh-plugin](https://github.com/aeschli/typescript-vscode-sh-plugin/commit/102a3a190ceece98b7c6e18251c44aed9a49e742) which may seem to indicate that this is the intended behavior?

In which case,if this is intended, then now it should be this one that's no longer be tagged with the 'function' semantic token, right?

```typescript
function myFuncDec() {}
myFuncDec.attr = 'str';
```

If I may, I'd argue it's very inconsistent, since (please correct me if I'm wrong) in JS all functions are just `Function` objects. So, they're just like any other object, plus also callable. And they do have native 'additional' properties and members, like `name`, `length`, `call` and `bind`.
So adding more custom properties and members to a function does not make it any less of a function.

In practice, this doesn't look right for React components as well. A function component would no longer be semantically typed as a function.

If, for other reasons, there needs to be a distinction, then perhaps we could have a new `callable` modifier or type?
That would be an interesting way to handle 'callable' parameters as well: https://github.com/microsoft/vscode/issues/91038

Thanks!

**Comment by aeschli** [comment] 2020-02-25 14:03
Yes, that's the intended behavior. As soon as there are properties as well, it's hard to know what the main propose of the object is. 
The main motivation was to fix `Object.create(null)` where `Object` got colored like a function.

But maybe there's a better approach. I need to dig deeper in the typescript type system.

**Comment by fgallardograzio** [comment] 2020-02-25 19:26
Thanks @aeschli 

>As soon as there are properties as well, it's hard to know what the main propose of the object is.

I'd have to say I disagree... if it's born a function it'll always be a function. Its 'main purpose' should be to be called, otherwise a regular object should've been used. Being able to be called is the only differentiating characteristic. Adding custom extra properties (besides the native properties and members all functions have anyways) won't change that.

Anyways, I see where you're going with `Object`, though. But I don't think it's worth it to make 'fragile' rules in an attempt to generalize a special treatment for javascript's weird natives.
Maybe add a separate semantic type for natives and that's it?

Right now `Object` gets a different semantic token whether it's used with `new` (token type: `interface`) or not (token type: `variable`), and that's confusing.

This is off topic, but since you mentioned it, shouldn't `Object.create` be colored like a class, though?
According to [MDN: Global_Objects/Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) it's a `class`, although typescript's lib ambient declarations appear to declare it as an `interface`, and in reality it behaves as a ... function?  so that calling `Object()` is effectively the same as invoking its constructor via `new Object()`.

**Comment by aeschli** [comment] 2020-05-10 08:38
Closing, no changes planed for now. We have https://github.com/aeschli/typescript-vscode-sh-plugin/issues/14 to track that and when the TypeScript team takes over our code they can reconsider.

**Closed by aeschli** 2020-05-10 08:38 UTC
