### ISSUE TITLE
Allow contribute trees to better control collapse-on-click behaviour

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45184] opened 2018-03-07 08:58 UTC
This isn't really a bug and it happens in the standard explorer tree, but it's undesirable when a tree node serves at two purposes (something that can can be selected for editing purposes and also expanded).

In this tree, I have items that can expand/collapse but also represent code in the main editor (for example `AlertDialog` is related to some code):

![collapses](https://user-images.githubusercontent.com/1078012/37082708-2391baae-21e5-11e8-9189-988070866384.png)

If I click on `AlertTree` to select it (which jumps the editor to its location) it also collapses the node. This is undesirable - the user wants to navigate to it - it doesn't make sense to hide its children.

I think there should be some ability on a TreeItem to control this behaviour (for example, I would prefer for it never to collapse on click, unless it was already selected).

I think it works ok in the File explorer tree because clicking on a folder is less useful (it doesn't navigate the editor) and therefore it doesn't happen as often as it would in an outline tree.

**Comment by sandy081** [comment] 2018-03-07 17:18
Duplicate of #34130

**Closed** 2018-03-07 17:18 UTC
Labels: *duplicate, explorer-custom
