### ISSUE TITLE
No intellisense for languages for custom files.associations

### ISSUE THREAD

**Issue by factormystic** [Microsoft/vscode#10348] opened 2016-08-09 15:14 UTC
- VSCode Version: Version: 1.4.0
- OS Version: Windows 10 v1511 b10586.494

Steps to Reproduce:

1. Go to https://code.visualstudio.com/docs/languages/overview & observe that intellisense should be possible for custom `files.associations` language options
2. Go to File -> Preferences -> User Settings
3. Add a `files.associations` setting like in the docs (correct quoting & spelling, etc)
4. Attempt to use <kbd>ctrl + space</kbd> to get language options for that part of the setting

The intellisense drop down shows up with the "no suggestions" message. However, I expect it to show language options. This is what the documentation says will happen, as well.

**Comment by aeschli** [comment] 2016-08-10 15:50
duplicate of #10184

**Closed by aeschli** 2016-08-10 15:50 UTC

**Comment by factormystic** [comment] 2016-08-10 17:23
👍
