### ISSUE TITLE
git no longer working when upgrading to V1.21.1

### ISSUE THREAD

**Issue by mars000** [Microsoft/vscode#46018] opened 2018-03-17 10:12 UTC
- VSCode Version: 1.21.1 x64
- OS Version: Windows 10

Steps to Reproduce:

1. I had V1.19 running. With git working nicely and linked in with GitHub remote accounts
2. VSC then updated to 1.21.1 and then Git dissapeared from gui and could not get git commands to function in Alt-Shit-P menu. However git still working in VSC terminal.
When I type in git --version in VSC integrated terminal I get: `git version 2.16.2.windows.1`

Not sure what is wrong here. Any help would be appreciated.

**Comment by mars000** [comment] 2018-03-18 07:55
Update:
- I've tried uninstalling git and re-installing, still no success. As per above git commands working in VSC terminal but not anywhere else. I notice that "git" does not appear anywhere in the Preference->Settings file but it does in the Insiders edition which I just installed (more on that below)
- **I've also just installed VSC Insiders and it WORKS perfectly with Inside**r  but **still not working with non-Insider version**. Detail of insider version are below:
![image](https://user-images.githubusercontent.com/19469711/37563850-b8b18fd2-2add-11e8-8923-578613a813d7.png)

**Comment by joaomoreno** [comment] 2018-03-19 15:02
Does it reproduce if you run with `code --disable-extensions`?

Does it reproduce if you reinstall VS Code?

**Comment by mars000** [comment] 2018-03-19 21:16
Does it reproduce if you run with code --disable-extensions?

Yes 

Does it reproduce if you reinstall VS Code?

Yes

**Comment by joaomoreno** [comment] 2018-03-20 08:20
Can you show me your user settings?

**Comment by mars000** [comment] 2018-03-20 08:25
{

    "git.path" : "C:\\Program Files\\Git\\bin\\git.exe", 

    "workbench.panel.location": "right",

    "window.zoomLevel": 0,

    "git.autofetch": true,

    "editor.smoothScrolling": true,

    "workbench.sideBar.location": "left",

    "window.menuBarVisibility": "default"   

}

 

I can confirm this is the location of git.exe

**Comment by joaomoreno** [comment] 2018-03-20 08:31
How about we try launching it with brand new user data dir?

```
code --user-data-dir SOME_TEMPORARY_FOLDER
```

**Comment by mars000** [comment] 2018-03-20 09:19
Yep that fixed it – git works perfectly now.

 

Question is what do I do with existing version so works when I click on icon ?

**Comment by joaomoreno** [comment] 2018-03-21 07:23
Well, that got me thinking. What about if you simply run

```
code
```

(Make sure Code is shut down first). Does that work?

**Comment by mars000** [comment] 2018-03-21 09:32
Unfortunately just running “code” does not work.

**Comment by joaomoreno** [comment] 2018-03-22 08:25
@alexandrudima @bpasero What could be inside user-data-dir which blocks the git extension from loading? Note that if he sets a different user-data-dir, the git extension opens up. His settings look simple enough:

```json
{
    "git.path" : "C:\\Program Files\\Git\\bin\\git.exe", 
    "workbench.panel.location": "right",
    "window.zoomLevel": 0,
    "git.autofetch": true,
    "editor.smoothScrolling": true,
    "workbench.sideBar.location": "left",
    "window.menuBarVisibility": "default"   
}
```

**Comment by bpasero** [comment] 2018-03-22 09:11
@joaomoreno any error message?

**Comment by mars000** [comment] 2018-03-22 11:19
No error messages are displayed.

**Comment by joaomoreno** [comment] 2018-03-26 13:37
@sandy081 Any ideas?

**Comment by sandy081** [comment] 2018-03-26 15:21
@mars000 Can you please check what is there in the built in extensions and what extensions are disabled and what extensions are running

`Extensions: Show Built-in Extensions`
`Extensions: Show Disabled Extensions`
`Developer: Show Running Extensions`

**Comment by mars000** [comment] 2018-03-27 02:47
Hi – as you can see below Git was disabled. The update from one version to another automatically disabled Git – any reason why this would occur ?

 

I enabled Git and now it works.

 

Thank you all for your help.

**Comment by joaomoreno** [comment] 2018-03-27 07:07
Thanks for confirming @mars000 

Dupe of #45398

**Closed by joaomoreno** 2018-03-27 07:07 UTC
Labels: needs more info
