### ISSUE TITLE
Usability problem - Typescript popup placement for unused function

### ISSUE THREAD

**Issue by EECOLOR** [microsoft/vscode#113456] opened 2020-12-26 22:13 UTC
When hovering over an unused function or argument the popup places the 'Quick fix' under my mouse preventing me from interacting with the function name. I often double click a name before I copy it. In this case I want to copy the name to start using the function. This is a big usability problem. 

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-123-generic

Steps to Reproduce:

1. Hover over the name of an unused function
2. Note that the popup falls over the name of the function

Does this issue occur when all extensions are disabled?: Yes

A screenshot of the problem.
![Screenshot_20201226_230918](https://user-images.githubusercontent.com/1486362/103159915-68623100-47cf-11eb-933f-8e4d4fc939ce.png)

**Comment by EECOLOR** [comment] 2020-12-26 22:15
Might be related to the changes that caused #112373 as they showed up at the same time.

**Comment by mjbvz** [comment] 2020-12-29 20:32
Duplicate of #112391

**Closed by mjbvz** 2020-12-29 20:32 UTC
