### ISSUE TITLE
Markdown: make a pass over languages that depend on markdown

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83633] opened 2019-10-30 08:01 UTC
Extracted from https://github.com/microsoft/vscode/issues/77990 there are other languages that - when opened - will drag in all of our languages via the markdown dependency.

**Comment by mjbvz** [comment] 2019-10-30 23:53
Known built-in grammars that include `text.html.markdown`:

- [ ] [F#](https://github.com/microsoft/vscode/blob/a0bc43dd73645fa8fba19b7b9a6b929c9eee5d18/extensions/fsharp/syntaxes/fsharp.tmLanguage.json#L578)
- [ ] [shellscript](https://github.com/microsoft/vscode/blob/8fdf170a0850c1cc027382f31650aaf300d3ae2a/extensions/shellscript/syntaxes/shell-unix-bash.tmLanguage.json#L502)

**Comment by bpasero** [comment] 2019-10-31 06:08
I think also:
* [ ] PHP
* [ ] Perl

Show more loading activity than other languages.

**Comment by bpasero** [comment] 2019-10-31 09:26
//cc @alexr00

**Comment by mjbvz** [comment] 2019-11-02 22:29
@bpasero Do the php and perl grammars pull in the markdown grammar too? I see that the references a few other languages but not markdown

**Comment by bpasero** [comment] 2019-11-03 07:18
@mjbvz I basically just printed which grammars are being loaded here: 

https://github.com/microsoft/vscode/blob/593c968f12833348e96eddbef9b81e2c5233bd68/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L194

**Comment by mjbvz** [comment] 2019-11-07 04:49
Root cause of all of this is https://github.com/microsoft/vscode-textmate/issues/106

We should investigate just how painful fixing the root cause of this issue would be. A few reasons why:

- Markdown files will still have this issue. MD files are found in a large number of repos.
- Many grammars are effected by the same issue. Markdown is just an extreme case of the problem

**Comment by alexr00** [comment] 2019-12-02 10:11
@mjbvz what needs to be done for this?

**Comment by mjbvz** [comment] 2019-12-05 07:05
Moving to December. Let's first test to see if these languages trigger the slow loading in the first place. If a language is effected, we can investigate how complicated a fix would be and if it would introduce significant regressions in the grammar

**Comment by mjbvz** [comment] 2020-10-15 00:54
Closing this snowplow issue as I'm not sure what action to take. If we see performance issues again, I suggest we look into microsoft/vscode-textmate#106 to address this

**Closed by mjbvz** 2020-10-15 00:54 UTC
Labels: debt, perf
