### ISSUE TITLE
Consider removing `${separator}` variable

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21223] opened 2017-02-22 22:36 UTC
Testing #20433

Currently, the default setting is rather difficult to read/parse. Is there any reason to include the separator string as a variable? (is it likely to change and is that something we want to optimize for?) If not, I think it would be much cleaner and readable to represent it as part of the string literal.
![screenshot from 2017-02-22 17-29-29](https://cloud.githubusercontent.com/assets/762848/23235703/83175a46-f924-11e6-8470-b90729dc0546.png)

**Comment by bpasero** [comment] 2017-02-23 05:47
@mousetraps I am open for ideas how to improve this but the reason this is a variable is that it is added only on the condition that the surrounding variables are present.

For example if you have no active editor opened, `${dirty}` and `${activeEditorName}` are both empty strings but you do not want the ${separator} to show under that condition, otherwise you end up with dangling "-" in the window title. Does it make sense?

**Comment by bpasero** [comment] 2017-04-05 04:48
Closing as designed.

**Closed by bpasero** 2017-04-05 04:48 UTC
Labels: needs more info
