### ISSUE TITLE
Add option to update vscode on startup or on both startup/close

### ISSUE THREAD

**Issue by soredake** [microsoft/vscode#181762] opened 2023-05-07 17:25 UTC
I am that type of person who never closes vscode with exception of shutdown (obviously).
Right now vscode cannot update itself on windows shutdown requiring me to restart vscode manually to update it: https://github.com/microsoft/vscode/issues/180814, having option to update it on both startup/close will somewhat fix the issue for me.
And, right now, vscode can be completely uninstalled when it will try to update itself on startup: https://github.com/microsoft/vscode/issues/52855, adding option to update vscode on startup will fix the issue for affected people.

**Comment by joaomoreno** [comment] 2023-05-11 15:04
This is just a duplicate of https://github.com/microsoft/vscode/issues/52855. Fixing that will involve making Windows wait for the update to complete.

**Closed by joaomoreno** 2023-05-11 15:04 UTC

**Comment by soredake** [comment] 2023-05-11 15:37
@joaomoreno that's not duplicate, if vscode can update itself on start of vscode there will be no problem as update is not done on shutdown.
