### ISSUE TITLE
fail to layout README in Extensions

### ISSUE THREAD

**Issue by tomocy** [microsoft/vscode#73256] opened 2019-05-03 21:34 UTC
This problem can be seen also in insider app.

- VSCode Version: 1.33.1
- OS Version: MacOS Majave 10.14.3 (18D109)

Steps to Reproduce:

1. See [the README](https://marketplace.visualstudio.com/items?itemName=tomocy.dominator) in browsers.
1. Search "Dominator" from Extensions in VSCode

In Extensions in VSCode, the README is not laid out nicely even though nicely in browsers.

<img width="1440" alt="Screen Shot 2019-05-04 at 6 18 20" src="https://user-images.githubusercontent.com/36136133/57166388-005e1a80-6e35-11e9-9630-4664c2bfc111.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by msftrncs** [comment] 2019-05-04 05:56
I think the PowerShell Preview extension README is suffering from this as well.

**Comment by msftrncs** [comment] 2019-05-04 06:09
Maybe this isn't related, but here is what it looks like for me in Insiders:

![image](https://user-images.githubusercontent.com/26179051/57174757-19e96d00-6e09-11e9-8e4b-1d64bb8fe455.png)

**Comment by mjbvz** [comment] 2019-05-09 18:42
@msftrncs That is a different issue

**Comment by mjbvz** [comment] 2019-05-09 19:55
The root cause seems to be an issue with the marked library we use to render extension markdown: https://github.com/markedjs/marked/issues/1487

**Comment by mjbvz** [comment] 2019-10-08 00:29
Closing this as upstream. Once the upstream issue is fixed, we'll pick it up for VS Code with the next marked release

If you want to help out, please look into helping marked fix this bug

**Closed by mjbvz** 2019-10-08 00:29 UTC
Labels: extensions, markdown, upstream
