### ISSUE TITLE
Softer output update for Notebooks

### ISSUE THREAD

**Issue by arribass** [microsoft/vscode#153261] opened 2022-06-26 21:53 UTC
When you do something like this  `display.clear_output(wait=True)` and then plot again the screen flashes. In other apps such as jupyter the screen prints the next 'frame' in a softer way and easier for the eye to see. I'm switching to Jupyter when i do tasks like this because its so unconfortable to look at. (Not trying to be offensive) Its just that it flashes my eyes.

**Comment by rebornix** [comment] 2022-06-29 00:31
@arribass thanks for the feedback, can you please share code snippet which I can use to reproduce this locally? Asking as I want to make sure I can reproduce locally what you were seeing, thanks in advance!

**Comment by arribass** [comment] 2022-06-30 11:38
Sure here you have it! 

Put this piece of code into a file called plotter.py

``` import matplotlib
import matplotlib.pyplot as plt

is_notebook = 'inline' in matplotlib.get_backend()

if is_notebook:
    from IPython import display

def plot_for_loop(x_label, y_label, title):
    for i in range(1000):
        plt.plot(i, i)
        plt.xlabel(x_label)
        plt.bar(i, i)
        plt.ylabel(y_label)
        plt.title('Visual Studio Code')
        plt.show()
        if is_notebook:
            display.clear_output(wait=True)
        else:
            plt.show()
 ```

Then run it on a VSCode notebook like this
```
import plotter as p
p.plot_for_loop('x', 'y', 'Visual Studio Code')```

The graph doesnt plot anything important but as you can see once it draws the new frame it flashes.

**Comment by rebornix** [comment] 2022-12-16 21:15
/duplicate of https://github.com/microsoft/vscode/issues/132143

**Closed by rebornix** 2022-12-16 21:15 UTC
Labels: polish, notebook-layout, notebook-output
