### ISSUE TITLE
Search in the markdown preview panel and then open a mark down file in same panel, the Visual Studio Code will crashed.

### ISSUE THREAD

**Issue by neville-studio** [microsoft/vscode#213147] opened 2024-05-21 11:55 UTC
Type: <b>Bug</b>

(I have set Markdown Preview as the default option to open the Markdown file)
1. Use Ctrl + F Accelerate key to open find box in a opened mark down file.

2. Find something in the markdown file which opened.

![image](https://github.com/microsoft/vscode/assets/90772701/8223bacf-d88d-47e2-b6e9-8f5f3f5560e9)

3. Drag or open another markdown file in explorer.

Visual Studio Code will crashed after take these steps.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (21.26GB free)|
|Process Argv|--crash-reporter-id 312cae00-019f-4238-8674-62dbb2a1eab3|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
arm-debugger|Arm|1.1.2
cmsis-csolution|Arm|1.34.9
device-manager|Arm|1.12.1
embedded-debug|Arm|1.1.2
environment-manager|Arm|1.1.16
keil-studio-pack|Arm|1.18.2
virtual-hardware|Arm|0.6.2
arm|dan|1.7.4
memory-inspector|ecl|1.1.0
peripheral-inspector|ecl|1.5.1
copilot|Git|1.194.0
copilot-chat|Git|0.15.2
keil-vscode-assistant|jac|1.9.1
better-cpp-syntax|jef|1.17.2
keil-vscode|jiy|0.0.2
vscode-language-pack-zh-hans|MS-|1.89.2024050109
csdevkit|ms-|1.5.20
csharp|ms-|2.28.11
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
remote-wsl|ms-|0.88.2
cpptools|ms-|1.20.5
vscode-yaml|red|1.14.0
volar|Vue|2.0.10
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31049070
a69g1124:31046351
dvdeprecationcf:31052040
pythonprt:31047983
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by neville-studio** [comment] 2024-05-21 12:17
This video is to help for understanding the issue.

https://github.com/microsoft/vscode/assets/90772701/4906a4ed-3552-431f-b2b7-7869ee29aeda

**Comment by andreamah** [comment] 2024-05-21 16:00
Does this happen with all extensions disabled?

**Comment by neville-studio** [comment] 2024-05-21 16:06
Yes, the video which I given, has disabled all of the extensions.

I have set the Markdown Preview as the default option to open the markdown file

**Comment by neville-studio** [comment] 2024-06-06 13:22
I have updated the vscode to the latest version, v1.90.0, but it have not fixed the information. when will the issue fixed?

**Comment by neville-studio** [comment] 2024-07-08 03:47
I have updated the vs code to the latest version (v1.90.2), the issue still not fixed. When will the issue fixed?

PS, when the error occured, the logs are below


[20240708T114052.zip](https://github.com/user-attachments/files/16122445/20240708T114052.zip)

**Comment by manav014** [comment] 2024-07-13 20:33
I was able to reproduce it in the latest stable release for mac. 

When I tried to reproduce it in `main` branch using `./scripts/code.sh` I found that, find is not working for markdown preview. 
I think this is a different issue but someone should look into this as this seems to be a valid issue in main branch. 

Tested with extensions disabled.

https://github.com/user-attachments/assets/0bb47435-cbc0-4e56-a821-61d59c2db412


cc: @mjbvz

**Comment by neville-studio** [comment] 2024-07-14 00:14
> I was able to reproduce it in the latest stable release for mac.
> 
> When I tried to reproduce it in `main` branch using `./scripts/code.sh` I found that, find is not working for markdown preview. I think this is a different issue but someone should look into this as this seems to be a valid issue in main branch.
> 
> Tested with extensions disabled.
> 
>  vscode_find_issue.mp4 
> cc: @mjbvz

1. You should set the Markdown Preview as the default option to open .md file
2. After searching, there must have some results.
3. After view the results, you should open an another markdown  file so that the issue will reproduce it.

PS. I'm using latest version of VS code in Windows, the issue still exists, with the Video File and the log file attached below.
video:
https://github.com/user-attachments/assets/d3274760-b201-42f5-adec-16183386874d

log:
[20240714T081212.zip](https://github.com/user-attachments/files/16207163/20240714T081212.zip)

**Comment by Parasaran-Python** [comment] 2024-07-15 14:35
Checked out to 1.91.1 version on source control. Built the code, still the find doesn't work for mark down files in preview mode, but works fine on the official vs code build of the same version,

The findInFrame function is not defined probably that's why find logic doesn't get executed on debug build. 

Not sure what's the gap, @mjbvz any hint would be highly appreciated in this aspect 🙂

**Comment by dangerman** [comment] 2024-07-15 21:01
I'm able to reproduce what I think looks like the same issue in VS Code 1.91.1 on Windows and MacOS (and 1.92.0 insider build), without specifically changing any settings for opening Markdown files.

It appears that:
 * you don't necessarily need to open a _new_ file
 * it might not be specific to the Markdown Preview
I think it could be a more general issue involving **Webviews** with the **find** widget, perhaps.

Also, `frame.findInFrame` is undefined for me too in `webviewMainService` and I can't reproduce when debugging locally or in the dev container 🤷‍♀️

### Example 1 - Changing tabs in editor group

 * Open a Markdown Preview
 * Search
 * Drag another editor into the **same EditorGroup** as the Markdown Preview with the search
 * Click on the Markdown Preview tab

The other editor appears in the EditorGroup, and the app remains responsive; however, when you click the Markdown Preview tab again it crashes.

![md-search-1](https://github.com/user-attachments/assets/b69572b5-fd45-4151-a53b-9a76f21cb74e)

###  Example 2 - Extension webview

 * From the **Extensions** view, open the page for an extension
 * Search
 * Open another extension page
 
 This one seems a bit flakier because _sometimes_ it works without crashing.

![extension-search-2](https://github.com/user-attachments/assets/a7261f50-15a1-4a44-ada2-1343b2bb14e2)

**Comment by tisilent** [comment] 2024-07-16 09:28
```
ExceptionAddress: 00007ff7f54b4d57 (Code___Insiders!v8::MemorySpan<v8::internal::Handle<v8::internal::Object> >::MemorySpan<v8::internal::Handle<v8::internal::Object> >+0x0000000000000047)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: ffffffffffffffff
Attempt to read from address ffffffffffffffff
```
.dmp info

**Comment by manav014** [comment] 2024-07-19 21:47
Created a separate issue for the markdown find not working in local build. (https://github.com/microsoft/vscode/issues/222244)

**Comment by dangerman** [comment] 2024-07-20 00:13
Looks like this might be a duplicate of:
 * https://github.com/microsoft/vscode/issues/201478
 * https://github.com/microsoft/vscode/issues/212544

They have similar reproduction steps and the same access violation exception.

**Comment by mjbvz** [comment] 2024-08-02 21:27
Duplicate of #177046

**Closed by mjbvz** 2024-08-02 21:27 UTC
Labels: bug, help wanted, info-needed, markdown
