### ISSUE TITLE
color

### ISSUE THREAD

**Issue by focusdroid** [Microsoft/vscode#36149] opened 2017-10-12 16:43 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.颜色像狗屎，，赶紧回复以前的颜色
2.The color is like shit, and quickly reply to the color

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-12 21:20
Duplicate of #35783

**Closed by mjbvz** 2017-10-12 21:20 UTC
Labels: extensions, new release
