### ISSUE TITLE
Right click shows inconsistent "New File" selections

### ISSUE THREAD

**Issue by CodySchrank** [Microsoft/vscode#48469] opened 2018-04-24 05:24 UTC
- VSCode Version:  1.22.2 (1.22.2)
- OS Version:   macOS 10.13.4

Steps to Reproduce:  Right clicking on a file should allow creation of a file/folder in that same dir.  This is standard behavior on other text editors.  It is very useful when there are hundreds of open files/folders to just right click on a file in a folder and click "new file" so that a new file gets added to the same folder of the original file.   However when right clicking on a file the option "new file" and "new folder" goes away.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by bpasero** [comment] 2018-04-24 07:46
Possibly a duplicate of #47972

**Comment by isidorn** [comment] 2018-04-24 07:56
@CodySchrank this works for me 
Can you provide a video of what is wrong. Can you also reproduce with vscode insiders https://code.visualstudio.com/insiders/

![screen shot 2018-04-24 at 09 55 39](https://user-images.githubusercontent.com/1926584/39173662-adf2ba50-47a5-11e8-9ff1-31598fd4eece.png)

**Comment by CodySchrank** [comment] 2018-04-24 14:52
Yes right clicking on folders works but right clicking on files does not.  Compare to sublime text.

vs-code-insiders:
![vscode](https://user-images.githubusercontent.com/10748482/39194878-7784c60a-4793-11e8-84ae-d9b682d0ec2f.gif)

sublime-text:
![sublime](https://user-images.githubusercontent.com/10748482/39194886-7ac8f3cc-4793-11e8-87ba-34bc58c5015d.gif)


Maybe it's just a habit I've developed over the years using different IDE's but I always right click on a file to make a new one, instead of the folder.  I don't see why the options to create a file/folder should be different between right clicking on a file and right clicking on a folder.

**Closed** 2018-04-25 07:56 UTC
Labels: *extension-candidate, file-explorer, needs more info

**Comment by CodySchrank** [comment] 2018-04-26 01:54
Fair enough.

If anyone wants this I added it https://marketplace.visualstudio.com/items?itemName=codyschrank.rightclickfix
