### ISSUE TITLE
JavaScript no highlight for single 'var' statement for multiple lines

### ISSUE THREAD

**Issue by ProvidenceXz** [Microsoft/vscode#7549] opened 2016-06-10 22:37 UTC
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5

```javascript 
var foo = 1, bar = 2, baz = 3;
```

In this case, foo, bar, and baz are properly highlighted. 
However, if you put bar and baz to separate lines, like:
```javascript
var foo = 1,
    bar = 2,
    baz = 3;
```
which is legit syntax, but bar and baz are not highlighted.

**Comment by aeschli** [comment] 2016-06-13 07:45
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/121

**Closed by aeschli** 2016-06-13 07:45 UTC
