### ISSUE TITLE
jsDoc intellisense support for @augments/@extends tags,overloaded function documentations,@typedef tags in other files.

### ISSUE THREAD

**Issue by aliemre1990** [Microsoft/vscode#72273] opened 2019-04-14 02:23 UTC
Issue Type: <b>Feature Request</b>

1-Please make intellisense support `@augments`/`@extends` tags. Intellisense is not showing base class properties both prototype and own.

2-An overloaded function documented like below doesn't display in intellisense either. It would be nice to see variations of the functions.
```
/**
 * Returns imported styles in 'dir/dir/style.scss' format.
 * @returns {string[]} Imported style's paths.
 *//**
* Returns imported styles in 'dir/dir/style.scss' format.
* @param {string} content File content to be used in operation.
* @returns {string[]} Imported style's paths.
*/
StyleFile.prototype.getImportedStylePaths = function (content) {
    if (!content)
        content = this.content;
....
}
```
![issue](https://user-images.githubusercontent.com/12927303/56087500-3ed76980-5e75-11e9-9be9-59fd0c1292ee.jpg)
Currently jsDoc comment is displayed like this.

3- Lastly Intellisense uses @typedef tags in other files but only if the file is opened in current window. Please allow any typedef tag to be used inside current working directory even if file containing typedef is not opened.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment] 2019-04-15 15:41
Please open separate issues for each of these three issues. 

For 1, can you please share some example code where it does not work as expected

**Comment by mjbvz** [comment] 2019-04-17 18:06
Duplicate of https://github.com/Microsoft/TypeScript/issues/30943

**Closed by mjbvz** 2019-04-17 18:06 UTC
Labels: javascript, needs more info
