### ISSUE TITLE
Custom Editor open with built-in doesn't work when already open with custom

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#99288] opened 2020-06-03 15:28 UTC
Testing https://github.com/microsoft/vscode/issues/99003

I have the .cscratch file open in the custom editor, then I also want to open the built in editor from the explorer view:
![recording (4)](https://user-images.githubusercontent.com/38270282/83656190-87913b00-a5bf-11ea-818f-8b2379445f0d.gif)

**Comment by mjbvz** [comment] 2020-06-04 23:42
Duplicate of #99252. Should be fixed in the next insiders build

**Closed by mjbvz** 2020-06-04 23:42 UTC
