### ISSUE TITLE
Source Control: View: Can't switch back to side by side after switching to inline

### ISSUE THREAD

**Issue by devinrhode2** [Microsoft/vscode#65117] opened 2018-12-15 00:09 UTC
At first glance, this seems to be fixed in insiders bulid version 1.31.0-insider. Will re-open in case I find out this is not true.

Source Control: View: Can't switch back to side by side after switching to inline
- VSCode Version: 1.30.0 (1.30.0)
- OS Version: High Sierra 10.13.6

Steps to Reproduce:
1. Enter Source Control from activity bar
2. Click file
3. Top right, click ••• menu
4. Click "Toggle Side by Side View"
5. (probably not necessary) Go about your life for a day?
6. Try to toggle back

Does this issue occur when all extensions are disabled? Yes

**Comment by devinrhode2** [comment] 2018-12-15 00:09
Not a duplicate of the bot's suggestion

**Comment by usernamehw** [comment] 2018-12-15 01:06
Possible duplicate of #65016

**Closed** 2018-12-17 08:33 UTC
Labels: *duplicate
