### ISSUE TITLE
Minimap - Scroll immediately when mouse button held down

### ISSUE THREAD

**Issue by flipswitchingmonkey** [Microsoft/vscode#22540] opened 2017-03-13 14:47 UTC
- VSCode Version: 1.10.2
- OS Version: Windows

Currently the minimap-position will jump to where the mouse is clicked on the minimap bar. However, to scrub from there, you need to release the mouse button and click again, then drag. It'd be better if when clicked and held, one could immediately scrub through the minimap.

**Comment by alexandrudima** [comment] 2017-03-28 13:27
Duplicate of #21708
Please see explanation in https://github.com/Microsoft/vscode/issues/21708#issuecomment-283600344

**Closed by alexandrudima** 2017-03-28 13:27 UTC
