### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by CesarGarcia-dot** [microsoft/vscode#119966] opened 2021-03-26 15:57 UTC
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.

Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.0-dev.20210324

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:113195:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:113230:29)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:112967:50)
    at InferredProject.Project.updateGraphWorker (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:156524:38)
    at InferredProject.Project.updateGraph (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:156455:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:158627:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:160184:26)
    at c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:160458:97
    at Object.flatMap (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:160458:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:161513:46)
    at c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:163412:88
    at IOSession.Session.executeWithRequestId (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:163403:28)
    at IOSession.Session.executeCommand (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:163412:33)
    at IOSession.Session.onMessage (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:163438:35)
    at Interface.<anonymous> (c:\Users\Cesar\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210324\node_modules\typescript\lib\tsserver.js:166040:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.72GB free)|
|Process Argv|--crash-reporter-id 41624b5b-0bed-4b68-a728-b67da4cfe243|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
better-comments|aar|2.1.0
nestjs-files|Abh|0.4.0
vscode-javascript-snippet-pack|aka|0.1.6
react-pure-to-class-vscode|ang|1.1.8
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
c-cpp-compile-run|dan|1.0.13
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
vscode-markdownlint|Dav|0.39.0
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.1
alstructurecreator|Edy|0.2.0
vscode-npm-script|eg2|0.3.18
react-native-react-redux|EQu|2.0.6
vue-inline-template|fai|1.0.1
php-debug|fel|1.14.11
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
go|gol|0.23.3
beautify|Hoo|1.5.0
wordpress|hri|1.0.1
search-node-modules|jas|1.3.0
csharpextensions|jch|1.3.1
Angular2|joh|11.0.0
vscode-csharp-snippets|jor|1.1.0
react-native-snippet|jun|0.5.6
docomment|k--|0.1.20
prettier-php|kar|0.0.3
vue-beautify2|ker|0.0.3
vscode-phpfmt|kok|1.0.30
csharpfixformat|Leo|0.0.84
php-namespace-resolver|Meh|1.1.8
Angular-BeastCode|Mik|10.0.3
mongodb-vscode|mon|0.5.0
graphql|mqu|0.1.2
vscode-docker|ms-|1.11.0
vscode-language-pack-es|MS-|1.54.2
csharp|ms-|1.23.9
mssql|ms-|1.10.1
remote-wsl|ms-|0.54.6
cpptools|ms-|1.2.2
js-debug-nightly|ms-|2021.3.2417
vscode-typescript-next|ms-|4.3.20210325
vsliveshare|ms-|1.0.4018
vscode-react-native|msj|1.4.1
awesome-flutter-snippets|Nas|2.0.4
color-highlight|nau|2.3.0
php-docblocker|nei|2.1.0
rpg|Nie|0.2.1
vetur|oct|0.33.1
gnucobol-debug|Ole|2.31.33
phpstorm-snippets|phi|1.1.1
vscode-php-getters-setters|php|1.2.3
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.6.0
vscode-yaml|red|0.17.0
prettier-now|rem|1.4.9
vscode-xml-complete|rog|0.3.0
react-native-snippet|san|0.6.0
vscode-sass-format|sas|1.1.7
vscode-javascript-booster|sbu|14.0.1
vue-vscode-snippets|sdr|2.2.0
php-files|sev|0.0.5
php-ci|sma|0.4.2
code-spell-checker|str|1.10.2
code-spell-checker-spanish|str|1.0.7
sass-indented|syl|1.8.16
php-refactor|tin|0.0.7
vscode-phpsab|val|0.0.11
gitblame|wad|6.0.2
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
wordpress-toolbox|wor|1.3.9
JavaScriptSnippets|xab|1.8.0
searchwpdocs|yog|2.0.1

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vspre833cf:30267465
vshan820cf:30276953

```

</details>

**Comment by mjbvz** [comment] 2021-03-26 20:09
Duplicate of https://github.com/microsoft/TypeScript/issues/43340

**Closed by mjbvz** 2021-03-26 20:09 UTC
