### ISSUE TITLE
Sash on the right prevents scrolling

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#170534] opened 2023-01-04 05:30 UTC
I am using VS Code always in fullscreen mode. Today I notice that I cannot grab the editor scrollbar when moving the mouse all the way to the right, here:

![Screenshot 2023-01-04 at 06 29 01](https://user-images.githubusercontent.com/900690/210490237-5fa47a02-1b43-4e4a-8d02-7a3e8b2d1e41.png)

It looks like my mouse is over a sash element, maybe from the auxiliary bar? I am not using this bar and would prefer if scrolling would work here. And besides, I cannot make the bar visible by moving the mouse left either.

**Comment by joaomoreno** [comment] 2023-01-06 08:23
This is because we now have a secondary side bar on that position, with a snapping sash. I suggest to close this as designed.

**Comment by extremeheat** [comment] 2023-06-06 23:20
This is incredibly annoying when scrolling, because I now I have to consciously move the cursor out of the edge of the screen (or carefully make sure I don't move the cursor too much) to adjust the scrollbar. On literally any other scroll bar (like on Chrome), I don't have to worry about missing the scrollbar BB except on VS Code. This is pretty bad UX, what is the significance of this panel over the scroll bar's ease of use? Why can't this be left to a menu option?

The fix I'm using for this is to open the Dev Tools (command palleted -> "Open Dev Tools") and running `$('.auxiliarybar').remove()` in the console to remove the element, as I don't see any setting to remove this.

**Comment by sbatten** [comment] 2023-08-04 17:04
As a compromise behavior. If you don't have any view containers in the secondary side bar, we will present a sash

**Closed** 2023-08-04 17:21 UTC
Labels: layout, papercut :drop_of_blood:
