### ISSUE TITLE
Version 1.8  can not install Extensions in proxy env.

### ISSUE THREAD

**Issue by yinay** [Microsoft/vscode#17360] opened 2016-12-16 00:50 UTC
- VSCode Version:1.8
- OS Version:win 7 

Steps to Reproduce:

1.  settting the proxy .  
{ "http.proxy": "",
  "http.proxyStrictSSL": false
}
2. try to seach the extensions. can not work .

**Comment by joaomoreno** [comment] 2016-12-16 09:23
Did you correctly set your proxy? Empty value seems wrong. Did you restart Code after changing those settings?

**Comment by yinay** [comment] 2016-12-20 00:59
Oh , the http.proxy is not empty 。I just keep it empty in this.
the same settings can be work ,on version 1.7.
did some one know the http agent changed on v 1.8?

**Comment by joaomoreno** [comment] 2017-01-03 09:39
@yinay Just to confirm: can you search for extensions?

**Comment by joewood** [comment] 2017-01-06 19:22
I'm seeing this too on Ubuntu. Looks like a regression as it was working before 1.8. In verbose mode I see:

```
[10483:0106/190618:ERROR:cert_verify_proc_nss.cc(942)] CERT_PKIXVerifyCert for marketplace.visualstudio.com failed err=-8172
[main 7:06:18 PM] IPC#vscode-workbenchLoaded
[10483:0106/190619:INFO:CONSOLE(94)] "An unknown error occurred. Please consult the log for more details.", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (94)
```

Which seems to be related to a chromium bug [30891](https://bugs.chromium.org/p/chromium/issues/detail?id=30891). This relates to a cert with an AIA extension - which I think is essentially a missing cert in the chain loaded dynamically.

**Comment by joewood** [comment] 2017-01-06 19:47
I found a workaround: -

After a bit of hacking around I found that Chromium uses its own (local) store for self-signed certs (not sure if this is a new thing).  If I load the set of root CA certs using the tool described [here](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_cert_management.md) everything starts working. 

Basically, for each `.crt` I do a:

```bash
certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n <FILENAME> -i <FILENAME>
```

**Comment by xapienz** [comment] 2017-03-08 10:31
I have the problem https://github.com/Microsoft/vscode/issues/18920, which shows the same log as in this bug. After today's update of vscode-insiders (when https://github.com/Microsoft/vscode/issues/21879 was merged) not only extensions, but also check of updates stopped working.
joewood's workaround worked well, thank you joewood!
I think this problem and #18920 may be the same.

**Comment by joaomoreno** [comment] 2017-03-08 14:10
Please check out #22214 

Closing this a duplicate

**Closed by joaomoreno** 2017-03-08 14:10 UTC
Labels: needs more info
