### ISSUE TITLE
QuickEdit a settings icon does not switch to newline

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#18269] opened 2017-01-08 09:12 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open 3-4 Editors(one of them is the default settings editor) next to each other to have not that much space left.
2. Try edit a option:
![image](https://cloud.githubusercontent.com/assets/11234139/21748677/ca3e9bfe-d58a-11e6-8ebc-53e6f4f02fb2.png)

Since my screenshot program doesn't want to recognize my pointer, I've drawn it. If you want to edit this option, the scrollbar is in its way. And when I am over the scrollbar, the edit icon is invisible.
I would like to have it being switched to the next line, so I can edit this option, even when there is not much space.

**Comment by sandy081** [comment] 2017-01-09 08:44
Duplicate of #16714

**Closed by sandy081** 2017-01-09 08:44 UTC
