### ISSUE TITLE
It has been moved to #15431

### ISSUE THREAD

**Issue by xDarkMan1** [Microsoft/vscode#15355] opened 2016-11-11 13:41 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 7 Professional

live view for html~php pages like brackets Code editor

**Comment by aeschli** [comment] 2016-11-11 20:18
Can you add more description what exactly that does? Maybe add a screenshot as well.

**Comment by xDarkMan1** [comment] 2016-11-12 00:03
Okay,tomorrow :+1:

**Comment by xDarkMan1** [comment] 2016-11-13 18:09
I want to delete the issue, then i'll create new issue with explain what does i mean

xDarkMan
Regards.

**Comment by aeschli** [comment] 2016-11-14 08:16
duplicate of #15431

**Closed** 2018-03-06 23:01 UTC
Labels: *duplicate, feature-request, php
