### ISSUE TITLE
Column/vertical select work like Visual Studio

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#29914] opened 2017-06-30 07:45 UTC
- VSCode Version: 1.13.1
- OS Version: Arch Linux

Steps to Reproduce:

1. Perform a column select near the end of a line, or across empty lines
2. Notice that the column is broken wherever there is empty space.
3. Also notice that when interacting with a column made from individual cursors, cursor movement across line-endings cause the cursors to become all messed up.

Basically, I just want column select to work like Visual Studio. The current implementation via many-cursors is a mess.

**Comment by rjmunro** [comment] 2018-03-05 09:07
This is mostly a duplicate of #5402. Please ensure you give that one a thumbs up.

**Closed** 2018-03-05 13:22 UTC
Labels: *duplicate, editor, editor-columnselect, feature-request
