### ISSUE TITLE
Keyboard shortcut for undo mixes with closeActiveEditor

### ISSUE THREAD

**Issue by Jessev6** [Microsoft/vscode#59330] opened 2018-09-25 12:05 UTC
Issue Type: <b>Bug</b>

1. Set machine language to nl_BE.
2. Login in a user session.
3. Set session language to us.
4. Use shortcut Ctrl+Z to undo previous action.
5. Shortcut for closeActiveEditor gets triggered.

This behaviour is probably because of the mixup with user session and machine language. This however is very annoying. I have this issue because I use an external keyboard with QWERTY layout but my laptop has AZERTY so I'd rather boot with my laptop's keyboard layout.

VS Code version: Code - OSS 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-14T00:41:55.375Z)
OS version: Linux x64 4.18.9-arch1-1-ARCH

**Comment by bpasero** [comment] 2018-09-25 12:09
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Jessev6** [comment] 2018-09-25 12:18
Just tested this and discovered that this bug is a bit different.

The bug occurs when I change my keyboard layout with ```setxkbmap -layout us``` while an instance of vscode is already running. I can type in the new layout, but the shortcuts have not adjusted, this however is easily worked around by reloading the editor. This may look like an issue with xserver instead of vscode, but this behaviour does not occur in other applications.

**Comment by alexandrudima** [comment] 2018-10-08 13:11
Have you seen https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

![image](https://user-images.githubusercontent.com/5047891/46610931-77843800-cb0c-11e8-8c60-9df8c11ffe4f.png)

Duplicate of #23690

**Closed by alexandrudima** 2018-10-08 13:11 UTC
Labels: keybindings, keyboard-layout, linux
