### ISSUE TITLE
Git cannot be clicked to add to stash

### ISSUE THREAD

**Issue by yexk** [microsoft/vscode#181870] opened 2023-05-09 08:27 UTC
Type: <b>Bug</b>

the button cannot clicked

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (10.89GB free)|
|Process Argv|--crash-reporter-id d167836f-5a43-47e6-8715-cb541f44e960|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
golangwithdidi|ald|0.0.1
toml|be5|0.6.0
vscode-intelephense-client|bme|1.9.5
better-toml|bun|0.3.2
doxdocgen|csc|1.4.0
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
composer-php-vscode|DEV|1.34.13083
phptools-vscode|DEV|1.34.13083
profiler-php-vscode|DEV|1.34.13083
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|13.5.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
code-runner|for|0.12.0
shell-format|fox|7.2.5
leek-fund|gis|3.3.0
go|gol|0.38.0
vscode-drawio|hed|1.6.6
better-cpp-syntax|jef|1.17.2
php-cs-fixer|jun|0.3.9
vscode-docker|ms-|1.25.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.78.4
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
php-docblocker|nei|2.7.0
gremlins|nho|0.26.0
vetur|oct|0.37.3
gotestexplorer|pre|0.1.13
quicktype|qui|12.0.46
fabric8-analytics|red|0.3.6
vscode-commons|red|0.0.6
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
LiveServer|rit|5.7.9
phpcs|she|1.0.8
cmake|twx|0.0.17
vscode-gradle|vsc|3.12.7
volar|Vue|1.6.4
php-debug|xde|1.32.1
php-pack|xde|1.0.3
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.5.1
vue|znc|0.12.0
php-intellisense|zob|1.1.2
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052

```

</details>

**Comment by yexk** [comment] 2023-05-09 08:31
![image](https://user-images.githubusercontent.com/19749521/237039729-5753dce4-098d-48bb-9099-69188b37cf2e.png)
 like this

**Comment by lszomoru** [comment] 2023-05-09 18:15
@yexk, are you able to reproduce this issue every time? When the issue occurs are the actions disabled for *all* items in the "Changes" list of only some of them? Thank you very much!

**Comment by yexk** [comment] 2023-05-10 07:03
I was able to reproduce it all the time yesterday. But I haven't seen it again after using it for a whole day today.

> @yexk, are you able to reproduce this issue every time? When the issue occurs are the actions disabled for _all_ items in the "Changes" list of only some of them? Thank you very much!

**Comment by frederikhors** [comment] 2023-05-10 11:53
Same here, very annoying!

**Comment by frederikhors** [comment] 2023-05-10 11:55
I think it happens after a commit, I'll try to better understand.

**Comment by lszomoru** [comment] 2023-05-10 15:33
Closing as duplicate of https://github.com/microsoft/vscode/issues/181154.

**Closed by lszomoru** 2023-05-10 15:33 UTC
Labels: bug, git
