### ISSUE TITLE
Global search slow

### ISSUE THREAD

**Issue by showenx** [microsoft/vscode#76681] opened 2019-07-05 09:10 UTC
Issue Type: <b>Bug</b>

In vscode 1.36

Use global search ('command+shift+F' ) is really slow compare with previous version.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
cucumberautocomplete|ale|2.14.0
swagger-viewer|Arj|2.2.2
vscode-raml|blz|3.0.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.2.0
flutter|Dar|3.2.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.8.2
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|1.9.0
vscode-reveal|evi|3.4.0
vscode-yarn|gam|1.6.0
vscode-pull-request-github|Git|0.8.0
cloudcode|goo|0.0.9
imagesprites|gur|1.0.0
beautify|Hoo|1.5.0
rest-client|hum|0.21.3
docthis|joe|0.7.1
vscode-github|Kni|0.30.2
node-module-intellisense|lei|1.5.0
Angular-BeastCode|Mik|8.0.10
vscode-docker|ms-|0.6.4
vscode-kubernetes-tools|ms-|1.0.1
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.1
vsliveshare|ms-|1.0.488
debugger-for-chrome|msj|4.11.6
material-icon-theme|PKi|3.8.0
vscode-css-peek|pra|3.0.2
vscode-yaml|red|0.4.1
sass-indented|rob|1.5.1
yo|sam|0.9.3
code-settings-sync|Sha|3.3.1
gherkin-autocomplete|sil|1.3.3
autoimport|ste|1.5.3
vscode-icons|vsc|8.8.0
quokka-vscode|Wal|1.0.233
vscode-import-cost|wix|2.12.0
html-css-class-completion|Zig|1.19.0

(5 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2019-07-06 18:42
Please check this wiki and let me know whether these tips help: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by nicolasbadia** [comment] 2019-07-13 14:31
Looks like a duplicate of https://github.com/microsoft/vscode/issues/76610

**Comment by roblourens** [comment] 2019-07-13 18:57
Not all "slow search" issues are the same issue.

**Closed by roblourens** 2019-07-13 18:57 UTC
Labels: needs more info
