### ISSUE TITLE
Intergrated terminal prompt is black on black

### ISSUE THREAD

**Issue by mikaoelitiana** [microsoft/vscode#110672] opened 2020-11-15 11:47 UTC
- VSCode Version: Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

- OS Version: Darwin x64 20.1.0

Steps to Reproduce:

1. Open VSCode Integrated Terminal (I am using ZSH with Oh My Zsh and p10k)

VsCode windows looks like this: 

<img width="1225" alt="Capture d’écran 2020-11-15 à 12 39 47" src="https://user-images.githubusercontent.com/674667/99184034-91a79000-2740-11eb-9891-099cbd3bc2dc.png">

in iTerm, everything is working fine 

<img width="1026" alt="Capture d’écran 2020-11-15 à 12 47 12" src="https://user-images.githubusercontent.com/674667/99184056-b00d8b80-2740-11eb-929f-8c0b49ca1c9d.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by hDmtP** [comment] 2020-11-15 14:57
Does it occur with all other OSs?(i.e. Windows, Ubuntu)

**Comment by mikaoelitiana** [comment] 2020-11-15 15:00
I have only been able to test on osx. It may be linked to recent upgrade on big sur (I have not noticed it before)

**Comment by meganrogge** [comment] 2020-11-20 17:45
does changing `terminal.integrated.rendererType` help?

**Comment by zacharyliu** [comment] 2020-11-20 20:35
I'm seeing this issue too after the Mac Big Sur upgrade. It looks like all text is getting rendered in black, regardless of the theme, and regardless of shell. Here's a screenshot of `htop` open with different themes:

Solarized Dark
![image](https://user-images.githubusercontent.com/376616/99847245-c606bc00-2b45-11eb-8e55-4ab641c9ea85.png)

Default Light+
![image](https://user-images.githubusercontent.com/376616/99847299-e0d93080-2b45-11eb-97f8-141b022c3eef.png)

Tomorrow Night Blue
![image](https://user-images.githubusercontent.com/376616/99847340-ecc4f280-2b45-11eb-9c08-9d78f02f3bb3.png)

For comparison here's an iTerm screenshot:

![image](https://user-images.githubusercontent.com/376616/99847436-0d8d4800-2b46-11eb-9cdf-83ef478e3ceb.png)


> does changing terminal.integrated.rendererType help?

No, the colors stayed the same after changing the renderer type, even after closing and opening the terminal.

**Comment by zacharyliu** [comment] 2020-11-20 22:50
Probably a dupe of #100840. Solution is to reinstall fonts: https://github.com/microsoft/vscode/issues/100840#issuecomment-726769115

**Comment by meganrogge** [comment] 2020-11-20 23:33
> Probably a dupe of #100840. Solution is to reinstall fonts: [#100840 (comment)](https://github.com/microsoft/vscode/issues/100840#issuecomment-726769115)

Duplicate of #100840

**Closed by meganrogge** 2020-11-20 23:33 UTC
Labels: bug, integrated-terminal, macos-big-sur
