### ISSUE TITLE
vscode终端输入npm i -g @vue/cli报错，显示无法识别@

### ISSUE THREAD

**Issue by boilingEternalPoetry** [microsoft/vscode#123233] opened 2021-05-07 03:53 UTC
![image](https://user-images.githubusercontent.com/50012321/117395807-4457ee80-af2b-11eb-8727-d5c57a7b6d38.png)

**Comment by infinnie** [comment] 2021-05-08 06:27
Translation:

Command `npm i -g @vue/cli` causes an error in VS Code’s integrated terminal.

**Comment by infinnie** [comment] 2021-05-08 06:30
Due to VS Code using PowerShell instead of Command Prompt, use `npm i -g "@vue/cli"` instead. Note that the character `@` is quoted.

**Comment by aravindvnair99** [comment] 2021-05-09 16:04
@infinnie Set your default terminal as CMD.

Possible duplicate of / related to https://github.com/microsoft/vscode/issues/123323

**Comment by boilingEternalPoetry** [comment] 2021-05-13 01:32
> 由于VS Code使用PowerShell而不是Command Prompt，因此请`npm i -g "@vue/cli"`改为使用。请注意该字符`@`被引号。

谢谢，按照你的这种写法，我能够正确执行这个命令了

**Closed** 2021-08-02 17:40 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
