### ISSUE TITLE
Expand select bugs with literals in a function call

### ISSUE THREAD

**Issue by BTooLs** [Microsoft/vscode#34102] opened 2017-09-10 17:41 UTC
- VSCode Version: 1.15.1
- OS Version: win10
I don't know if these 2 scenarios are 2 effects of the same bug, or 2 different bugs.

1. Javascript file, try to expand select on Math: ```funcCall(Math.PI, 3,4)``` The 2nd step will Not select "Math.Pi", but all the parameters. See the gif
![gif](https://i.imgur.com/QuSpi5V.gif)

2. Go files: ```func(var1, var2, 3, "s")```. Cursor on var1 or var2, expand will select "var1, var2" instead of just the var. See the gif
![gif](https://i.imgur.com/yezBuuW.gif)

Reproduces without extensions: Yes

**Comment by jrieken** [comment] 2017-09-12 09:15
duplicate of #4795

**Closed by jrieken** 2017-09-12 09:15 UTC
