### ISSUE TITLE
Cannot open links to local protocol handlers (outlook) in Markdown

### ISSUE THREAD

**Issue by balaji-dutt** [microsoft/vscode#169086] opened 2022-12-14 05:30 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Windows 10

Hi,

I'm trying to create a Markdown file that contains links to a specific email in Outlook. I'm using Office 365 and for this purpose, I've enabled the `outlook:` protocol handler using the registry workaround documented [in this article](https://www.slipstick.com/problems/outlook-missing-outlook-protocol/). I then find a link to the email in Outlook using the Outlook `EntryID` [Info on EntryID](https://learn.microsoft.com/en-us/office/vba/api/outlook.mailitem.entryid).

Unfortunately, I cannot open any links in Markdown files opened in VSCode via this technique whether in Editor view (Ctrl-Left Click) or via Preview.

Steps to Reproduce:

1. Enable `outlook:` protocol in Windows using the article linked above.
2. Create a minimal `test.md` as follows:

```
#### Test outlook protocol
[Subject](outlook:EntryID-of-email]
```

3. Try to open the email using `Ctrl-Click` in VSCode.

What Happens:
- I get an error saying Unable to resolve resource.

What I have tried:
- I have tried using direct HTML links `<a href="outlook:Entry ID">Subject</a>` as well but this not recognised as a link in Editor view.

What should happen:
- In Windows Explorer or Run, entering `outlook:Entry-ID` and pressing `Enter` will open the email. I would like to duplicate the same behaviour in VSCode.

**Comment by balaji-dutt** [comment] 2022-12-14 05:32
Hi,

The VSCode version I'm managing is centrally managed and hence I cannot upgrade to VS 1.74.0.

**Comment by mjbvz** [comment] 2022-12-14 22:37
Duplicate of #133278

**Closed by mjbvz** 2022-12-14 22:37 UTC
