### ISSUE TITLE
Feature request: Floobits extension

### ISSUE THREAD

**Issue by kube** [Microsoft/vscode#15357] opened 2016-11-11 13:55 UTC
Reopen a question already asked in #2411.

It would be a great thing to permit **real-time collaboration on code** between users.

I used Floobits in Sublime, and they also created a great extension for Atom. https://github.com/Floobits/floobits-atom

I know that VSCode team is working on some third party extensions, so would it be conceivable for you to work on a Floobits extension, or at least check that VSCode API has all necessary features for it?

(Not necessarily video chat, just enable code sync)

**Comment by NikosEfthias** [comment] 2016-12-10 01:58
wow this would be amazing

**Comment by NikosEfthias** [comment] 2016-12-10 01:58
is there any plan about this @aeschli ?

**Comment by aeschli** [comment] 2016-12-12 08:57
Sorry, I'm not aware of any plans to add real-time collaboration functionality. Looks like a great opportunity for an extension...

**Comment by damienstanton** [comment] 2017-06-11 19:51
FYI this extension looks like it accomplishes the pair programming goal: https://github.com/sockscode/sockscode-vscode

**Comment by mjbvz** [comment] 2017-11-09 00:46
Duplicate of #15916

**Closed by mjbvz** 2017-11-09 00:46 UTC
Labels: duplicate, extension-candidate, feature-request
