### ISSUE TITLE
The search does not work if the folder contains the letter й or Й in folder name

### ISSUE THREAD

**Issue by AGENTxXx** [microsoft/vscode#81293] opened 2019-09-22 20:01 UTC
- VSCode Version: 1.38.1
- OS Version: Darwin x64 18.0.0 (Mac Os Mojave 10.14)

Steps to Reproduce:

1. Create folder with letter й or Й and add file
2. Open find in left panel
3. Enter the text that is in the file inside the created folder

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2019-09-24 15:19
I can't reproduce this. Is that letter the only difference between folders that get results and folders that don't? Check if any tips in here help: https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by AGENTxXx** [comment] 2019-09-25 08:28
I recorded video for you - [VC Code search error](https://youtu.be/MkhuGomNFCo)

**Comment by roblourens** [comment] 2019-09-26 02:08
Thanks for the video. Could you try one thing for me? Try closing all editors and repeating the search, and check that it still works. This is because search comes from the editor for open files, and it looks like you have that file open in the editor. I think the editor didn't pick up the rename, so the editor might have powered the first search but not the second.

If the same thing happens, then please do this

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by AGENTxXx** [comment] 2019-09-26 18:30
My log:

[2019-09-26 23:28:48.358] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"workbench.output.action.clearOutput","from":"panel"}
[2019-09-26 23:28:57.922] [renderer1] [trace] telemetry/activityBarAction {"viewletId":"workbench.view.explorer","action":"show"}
[2019-09-26 23:29:12.051] [renderer1] [trace] telemetry/resolveProxy {"count":1,"duration":52,"errorCount":0,"cacheCount":1,"cacheSize":1,"cacheRolls":0,"envCount":0,"settingsCount":0,"localhostCount":0,"envNoProxyCount":0,"results":[{"proxy":"DIRECT","connection":"HTTPS","code":"HTTP_404","count":2}],"pluginHostTelemetry":true}
[2019-09-26 23:29:18.708] [renderer1] [trace] CommandService#executeCommand filesExplorer.findInFolder
[2019-09-26 23:29:18.708] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"filesExplorer.findInFolder","from":"contextMenu"}
[2019-09-26 23:29:22.058] [renderer1] [trace] SearchService#search {"_reason":"searchView","folderQueries":[{"folder":{"$mid":1,"fsPath":"/private/var/www/you-quest.com","external":"file:///private/var/www/you-quest.com","path":"/private/var/www/you-quest.com","scheme":"file"},"fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false,"includePattern":{"Весь код Й/resources/js":true,"Весь код Й/resources/js/**":true}}],"usingSearchPaths":true,"maxResults":10000,"type":2,"contentPattern":{"pattern":"btn","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"previewOptions":{"matchLines":1,"charsPerLine":250},"usePCRE2":false,"userDisabledExcludesAndIgnoreFiles":true}
[2019-09-26 23:29:22.069] [renderer1] [debug] SearchService#search provideTextSearchResults btn, {"folder":"file:///private/var/www/you-quest.com","excludes":[],"includes":["Весь код Й/resources/js","Весь код Й/resources/js/**"],"useIgnoreFiles":false,"useGlobalIgnoreFiles":false,"followSymlinks":true,"encoding":"utf8","maxFileSize":17179869184,"maxResults":10000,"previewOptions":{"matchLines":1,"charsPerLine":250},"usePCRE2":false}
[2019-09-26 23:29:22.070] [renderer1] [trace] telemetry/searchResultsFirstRender {"duration":12}
[2019-09-26 23:29:22.087] [renderer1] [debug] SearchService#search rg --hidden --ignore-case -g '!*' -g '/Весь код Й' -g '/Весь код Й/resources' -g '/Весь код Й/resources/js' -g '/Весь код Й/resources/js/**' --max-filesize '17179869184' --no-ignore --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'btn' '.'
 - cwd: /private/var/www/you-quest.com
[2019-09-26 23:29:22.095] [renderer1] [debug] SearchService#search Got data from stdout
[2019-09-26 23:29:22.096] [renderer1] [debug] SearchService#search No result from parser
[2019-09-26 23:29:22.096] [renderer1] [debug] SearchService#search 
[2019-09-26 23:29:22.097] [renderer1] [trace] SearchService#search: 39ms
[2019-09-26 23:29:22.097] [renderer1] [trace] telemetry/textSearchComplete {"reason":"searchView","workspaceFolderCount":1,"endToEndTime":39,"scheme":"file","usePCRE2":false}
[2019-09-26 23:29:22.104] [renderer1] [trace] telemetry/searchResultsShown {"count":0,"fileCount":0,"options":{"isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"duration":40,"scheme":"file"}
[2019-09-26 23:29:22.105] [renderer1] [trace] telemetry/searchResultsFinished {"duration":47}

**Comment by roblourens** [comment] 2019-09-27 15:22
Thanks. I still don't now. Could you try running the ripgrep command directly? Like this:

- cd to your project dir
- Run `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --hidden --ignore-case -g '!*' -g '/Весь код Й' -g '/Весь код Й/resources' -g '/Весь код Й/resources/js' -g '/Весь код Й/resources/js/**' --max-filesize '17179869184' --no-ignore --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'btn' '.'` (fix the path to rg if needed for your system)
- Show me the output
- Please try it with and without the `Й`

**Comment by AGENTxXx** [comment] 2019-10-03 18:14
With Й
`/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --hidden --ignore-case -g '!*' -g '/Весь код Й' -g '/Весь код/resources' -g '/Весь код Й/resources/js' -g '/Весь код Й/resources/js/**' --max-filesize '17179869184' --no-ignore --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'btn' '.'
{"data":{"elapsed_total":{"human":"0.018916s","nanos":18916256,"secs":0},"stats":{"bytes_printed":0,"bytes_searched":0,"elapsed":{"human":"0.000000s","nanos":0,"secs":0},"matched_lines":0,"matches":0,"searches":0,"searches_with_match":0}},"type":"summary"}`
Without Й - working. Very long logs (i checked it, the right matches have been found).
I try rename folder to "Весь код ц" and the right matches have been found too.

If I change Весь код Й to Весь код * in query:
`/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --hidden --ignore-case -g '!*' -g '/Весь код *' -g '/Весь код */resources' -g '/Весь код */resources/js' -g '/Весь код */resources/js/**' --max-filesize '17179869184' --no-ignore --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'btn' '.'` 
It's working!

**Comment by ornic** [comment] 2019-10-10 13:53
@AGENTxXx check your filesystem, may be it stores Й/й as pair of И/и + accent. I don't remember which accent, you can try to search for `И?` and check if that is a cause.

**Comment by AGENTxXx** [comment] 2019-10-15 06:08
I renamed folder to "И Весь коди", and search works correctly.

**Comment by roblourens** [comment] 2019-10-16 22:55
Thanks for doing this testing but I still can't reproduce it. If we can reduce it some more, I can file an issue upstream.

- Which filesystem do you have? You can check this by running Disk Utility on your mac. For example I have APFS
- Can you add `--trace` to the rg command that doesn't work, and give me the output?

**Closed** 2019-10-23 23:30 UTC
Labels: needs more info
