### ISSUE TITLE
Firefox crashes when I click on a link in VSCode. 

### ISSUE THREAD

**Issue by rumble19** [microsoft/vscode#85344] opened 2019-11-21 23:23 UTC
Issue Type: <b>Bug</b>

1. Brand new Ubuntu 19.10 install.  Comes with firefox installed and set as default browser. 
2. Install VSCode from "ubuntu software".
3. Click any link inside of VSCode, for example Help> Tips and Tricks. 
4. Firefox crashes. 

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.3.0-23-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3456)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 1|
|Memory (System)|15.38GB (5.81GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by francogu** [comment] 2019-11-27 10:59
https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1838129

**Comment by AsianJohnBoi** [comment] 2020-01-16 03:20
I followed ctaggart's workaround (https://github.com/microsoft/vscode/issues/75579) and was able to resolve this issue.

1. Remove and purge the current installation `sudo apt remove code --purge`
2. Download and install the deb package from https://code.visualstudio.com/download
`sudo apt install ./<vscodefile>.deb`

**Comment by arnas** [comment] 2020-02-08 08:15
Had same issue with code installed with a `snap`. Installed it as deb package fixed issue too.

**Comment by joaomoreno** [comment] 2020-02-17 09:21
This is the same underlying cause as https://github.com/microsoft/vscode/issues/90806.

@sergiusens has pointed out the root cause:

> If I were a betting person, I would put my stakes on gdk-pixbuf (https://github.com/snapcrafters/vscode/blob/master/files/bin/wrapper#L36)

Crash is gone after unsetting the following env:

> ```
> sergiusens@umbar:/snap/code/25$ unset GDK_PIXBUF_MODULE_FILE
> sergiusens@umbar:/snap/code/25$ unset GDK_PIXBUF_MODULEDIR
> ```

**Comment by sergiusens** [comment] 2020-02-21 20:41
@joaomoreno I have a LD_PRELOAD related solution I can share (which wouldn't touch code's code), but if on launch those can be unset if code or code-insiders is in process.env "SNAP_NAME", that should solve the problem too.

**Comment by ygbr** [comment] 2020-02-28 02:52
On Ubuntu 19.10 uninstalling the "Firefox Web Browser" pre-installed deb package and installing the package named as just "Firefox" (packaged as a snap by Mozilla itself) on the Ubuntu Software store did the trick.

**Comment by Tyriar** [comment] 2020-04-01 18:07
Advice from snapcraft team: this should be fixed by removing the following environment variables after start up:

```
GDK_PIXBUF_MODULE_FILE
GDK_PIXBUF_MODULEDIR
```

**Closed** 2020-04-06 07:25 UTC
Labels: bug, confirmed, linux, snap
