### ISSUE TITLE
Scrolling issue when VScode start

### ISSUE THREAD

**Issue by Nicolore93** [Microsoft/vscode#44069] opened 2018-02-20 23:02 UTC
### Issue Type
Bug

### Description

The scroll lag at program start, when i resize the windows the scroll starts to work properly

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|7.93GB (3.02GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.4.2
code-runner|for|0.8.7
python|ms-|2018.1.0
cpptools|ms-|0.15.0
platformio-ide|pla|0.12.1
debug|web|0.21.2

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by RMacfarlane** [comment] 2018-02-21 23:27
Is this happening when you open with no files, or when VS Code opens with your previous workspace? Do you need to resize the window to get scroll to work, or will it start working after some time?

**Comment by Nicolore93** [comment] 2018-02-21 23:38
It happens both with new file and also with previous workspace, if I start the python script (I use vscode for python programming) it start to work properly. It also start to work correctly if I resize the windows, but If I maximize the window scrolling lag again

**Comment by Nicolore93** [comment] 2018-02-21 23:39
It happens both with new file and also with previous workspace, if I start the python script (I use vscode for python programming) it start to work properly. It also start to work correctly if I resize the windows, but If I maximize the window scrolling lag again

**Comment by RMacfarlane** [comment] 2018-02-22 01:29
So is the lag only happening when the window is maximized?

**Comment by Nicolore93** [comment] 2018-02-22 01:31
Yes, every time I maximize the windows it start to lag.

**Comment by RMacfarlane** [comment] 2018-02-22 23:35
Are you scrolling using a mouse, or with a touchpad? This may be related to https://github.com/Microsoft/vscode/issues/13612

**Comment by pellea** [comment] 2018-02-24 12:24
I have a really hard time trying to scroll correctly with the touchpad too (Win10, SurfaceBook 2).

The problem occurs only in maximized mode. If I minimized and maximized vscode again, it seems to works better. If I have multiple instance of vscode running, I have to minimize/maximize each instance.

**Comment by RMacfarlane** [comment] 2018-02-24 21:31
Closing as a duplicate of #13612

A possible workaround is to try launching code from the terminal with the `--disable-gpu` flag. The issue is upstream in chromium, the next version of electron should have the fix for it. We're working on upgrading to electron 2.0 currently

**Closed by RMacfarlane** 2018-02-24 21:31 UTC
Labels: needs more info

**Comment by 199621** [comment] 2018-02-25 08:55
for peps working on my file i dont know if any of this helps but here goes<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<cp:coreProperties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties">

<dc:title/>

<dc:subject/>

<dc:creator>Andrew Marshall</dc:creator>

<cp:keywords/>

<dc:description/>

<cp:lastModifiedBy>Andrew Marshall</cp:lastModifiedBy>

<cp:revision>8</cp:revision>

<cp:lastPrinted>2016-02-22T23:38:00Z</cp:lastPrinted>

<dcterms:created xsi:type="dcterms:W3CDTF">2017-11-27T18:08:00Z</dcterms:created>

<dcterms:modified xsi:type="dcterms:W3CDTF">2017-11-27T18:12:00Z</dcterms:modified>

</cp:coreProperties>

**Comment by 199621** [comment] 2018-02-25 08:55
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<Properties xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes" xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties">


-<property name="ContentTypeId" pid="2" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>0x0101001BD230CD563FC9418C09184899154D75</vt:lpwstr>

</property>


-<property name="MSIP_Label_f42aa342-8706-4288-bd11-ebb85995028c_Enabled" pid="3" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>True</vt:lpwstr>

</property>


-<property name="MSIP_Label_f42aa342-8706-4288-bd11-ebb85995028c_SiteId" pid="4" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>72f988bf-86f1-41af-91ab-2d7cd011db47</vt:lpwstr>

</property>


-<property name="MSIP_Label_f42aa342-8706-4288-bd11-ebb85995028c_Owner" pid="5" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>amarshal@microsoft.com</vt:lpwstr>

</property>


-<property name="MSIP_Label_f42aa342-8706-4288-bd11-ebb85995028c_SetDate" pid="6" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>2017-11-27T18:08:29.0085757Z</vt:lpwstr>

</property>


-<property name="MSIP_Label_f42aa342-8706-4288-bd11-ebb85995028c_Name" pid="7" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>General</vt:lpwstr>

</property>


-<property name="MSIP_Label_f42aa342-8706-4288-bd11-ebb85995028c_Application" pid="8" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>Microsoft Azure Information Protection</vt:lpwstr>

</property>


-<property name="MSIP_Label_f42aa342-8706-4288-bd11-ebb85995028c_Extended_MSFT_Method" pid="9" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>Automatic</vt:lpwstr>

</property>


-<property name="Sensitivity" pid="10" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr>General</vt:lpwstr>

</property>


-<property name="LikesCount" pid="11" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr/>

</property>


-<property name="Ratings" pid="12" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr/>

</property>


-<property name="LikedBy" pid="13" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr/>

</property>


-<property name="RatedBy" pid="14" fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}">

<vt:lpwstr/>

</property>

</Properties>

**Comment by 199621** [comment] 2018-02-25 08:56
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<Properties xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes" xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">

<Template>Normal_Wordconv.dotm</Template>

<TotalTime>4</TotalTime>

<Pages>0</Pages>

<Words>0</Words>

<Characters>0</Characters>

<Application>Microsoft Office Outlook</Application>

<DocSecurity>0</DocSecurity>

<Lines>0</Lines>

<Paragraphs>0</Paragraphs>

<ScaleCrop>false</ScaleCrop>

<Company/>

<LinksUpToDate>false</LinksUpToDate>

<CharactersWithSpaces>0</CharactersWithSpaces>

<SharedDoc>false</SharedDoc>

<HyperlinksChanged>false</HyperlinksChanged>

<AppVersion>12.0000</AppVersion>

</Properties>

**Comment by 199621** [comment] 2018-02-25 09:03
Documents
