### ISSUE TITLE
Linux: VS Code blink and close itself after a few minutes

### ISSUE THREAD

**Issue by tkreque** [microsoft/vscode#126046] opened 2021-06-11 13:18 UTC
Since the upgrade the VS Code started to blink and close itself after a few minutes (usually 1 or 2 minutes).
Looking at the other topics I saw that using `--no-sandbox` makes VS Code stable again.

I'm currently using Ubuntu 20.04.
I didn't found any crash report to attach.

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-55-generic snap
```

**Comment by IllusionMH** [comment] 2021-06-11 13:31
I think it should be closed as duplicate of #126007

Are you using snap installation?

**Closed** 2021-06-11 14:56 UTC
Labels: needs more info
