### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by TradeIdeasPhilip** [microsoft/vscode#108462] opened 2020-10-10 18:01 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20201008

**Steps to reproduce crash**
1.  No idea.  I've been running my program repeatedly.  Sometimes I kill it and sometimes it runs to completion.  Suddenly I got a message saying that something typescript related kept dying and when I hit the button it took me here.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at Object.releaseDocumentWithKey (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:120220:35)
    at Object.onReleaseOldSourceFile (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:145974:34)
    at Object.createProgram (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:104729:26)
    at synchronizeHostData (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:145942:26)
    at Proxy.getProgram (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:146034:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:150896:53)
    at InferredProject.Project.updateGraph (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:150829:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:152920:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:154440:26)
    at c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:154697:97
    at Object.flatMap (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:154697:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:155716:46)
    at c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:157589:88
    at IOSession.Session.executeWithRequestId (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:157580:28)
    at IOSession.Session.executeCommand (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:157589:33)
    at IOSession.Session.onMessage (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:157613:35)
    at Interface.<anonymous> (c:\Users\Philip Smolen\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20201008\node_modules\typescript\lib\tsserver.js:159829:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (4.57GB free)|
|Process Argv|--crash-reporter-id 78c1bbb8-f139-4bd7-9513-56056e1f2860|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.5.4
vscode-eslint|dba|2.1.10
vscode-deno|den|2.3.1
xml|Dot|2.5.1
prettier-vscode|esb|5.7.1
php-intellisense|fel|2.3.14
csharp|ms-|1.23.2
remote-ssh-edit|ms-|0.55.0
cpptools|ms-|1.0.1
vscode-typescript-next|ms-|4.1.20201009

</details>

**Comment by mjbvz** [comment] 2020-10-12 23:20
Do you see this with all extensions disabled? Specifically the deno extension, which has been known to cause issues with TS Server?

**Comment by TradeIdeasPhilip** [comment] 2020-10-13 03:25
I only use Visual Studio Code for work on Deno.  I wouldn't know what to do with it if I disabled Deno.

**Comment by mjbvz** [comment] 2020-10-13 19:16
Well if the deno extension is causing this, then this needs to be filed against them so they can fix it.

Do you only see this in deno projects? Have you seen it in simple js projects or with the deno extension disabled?

**Comment by TradeIdeasPhilip** [comment] 2020-10-13 19:49
I didn't choose to post this here.  VS code popped up a dialog box and I clicked "yes" a few times.  If there's a better place to report the problem, please give me a link.

**Comment by mjbvz** [comment] 2020-11-02 21:17
Closing this as possible caused by deno without additional information. If you see this with deno disabled in your workspace, please let us know

**Closed by mjbvz** 2020-11-02 21:17 UTC
Labels: needs more info
