### ISSUE TITLE
Global SCSS or CSS file for allowing users to customize vscode

### ISSUE THREAD

**Issue by alixsep** [microsoft/vscode#129886] opened 2021-07-31 07:44 UTC
Hi!
I love vscode, along side with many others. onething that we want is ability to customize it. We already have themes and icons in the extention store. but what if someone wants **rounded corners** or a custom animation for the dropdowns? or may be even changing the layout based on their taste?

I saw this concept from reddit, ([Source](https://www.reddit.com/r/Windows11/comments/orbgzl/visual_studio_vs_code_and_github_desktop_with/?utm_source=share&utm_medium=web2x&context=3)) and this is legitmately an absolute beautiful redesign of vscode:

![fo8a5hwq0dd71](https://user-images.githubusercontent.com/59757582/127732718-07359cda-97cd-4d06-8720-65523a02fea5.jpg)
![fuh3rhwq0dd71](https://user-images.githubusercontent.com/59757582/127732728-741e8738-98c4-4db2-939b-00acc67e89b4.jpg)

**Comment by aeschli** [comment] 2021-08-17 19:17
Duplicate of https://github.com/microsoft/vscode/issues/459

See https://github.com/microsoft/vscode/pull/40764#issuecomment-355011312 why we do not want to go that way.

**Closed by aeschli** 2021-08-17 19:17 UTC

**Comment by alixsep** [comment] 2021-08-19 14:30
@aeschli and you got 27 dislikes and 2 likes for your comment.
