### ISSUE TITLE
Option to disable Undo/Redo for File Operations

### ISSUE THREAD

**Issue by TSiege** [microsoft/vscode#117621] opened 2021-02-24 20:36 UTC
Multiple times since the "Undo File Operations" feature has been released, I've experienced accidentally undoing file renames/deletions. This has caused me a lot more trouble than it's worth. I've lost time undoing unknowingly altering my file system _and_ even automatic name changes in other files related to auto renaming. A prompt isn't enough for me. I simply find the feature harmful to my workflows and would like to have the ability to turn it off. I know [others](https://stackoverflow.com/questions/65966902/disable-the-undo-command-for-file-operations-in-explorer-feature-in-vs-code) have also found it difficult as well

**Comment by isidorn** [comment] 2021-02-25 08:27
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by TSiege** [comment] 2021-03-01 17:43
Thanks @isidorn!

**Comment by elis** [comment] 2021-03-06 11:12
When navigating between files, and often selecting a file that you just recently did some change to (in the code), and at the same time having some changes made to the files themselves (e.g. copying, renaming, moving files via the file navigator), I often click Undo/Redo EXPECTING my code to update, but sometimes it will have catastrophic consequences, such as deleting an entire codebase with no ability to "Redo/Undo" to retrieve any of the lost code.

Didn't commit? well, have fun trying to reconstruct your last three hours of your coding session - because it's gone and you have no way to get it back!

Please - allow some way to disable this demonic "feature".

When I click on a file in the file navigator, I expect the code editor to be the active element that any and all actions will be performed on. Having the focus stay on the file manager is utterly unintuitive and requires high attention to details to not mess up a work in progress.

**Comment by avshyz** [comment] 2021-03-06 11:39
This is highly frustrating.
@isidorn Jet brains products has the same feature, but in there case there's a prompt, warning about the operation that's about to happen ("are you sure you want to undo file deletion / move of x files?")

**Comment by elis** [comment] 2021-03-06 11:43
From the Stackoverflow thread mentioned by the OP, here's a quick fix that you can use by modifying the keybindings json to the following:

```

    {
        "key": "cmd+z",
        "command": "undo",
        "when": "editorFocus"
    },
    {
        "key": "cmd+z",
        "command": "-undo"
    },
    {
        "key": "shift+cmd+z",
        "command": "redo",
        "when": "editorFocus"
    },
    {
        "key": "shift+cmd+z",
        "command": "-redo"
    }
 ```

**Comment by lirongfei123** [comment] 2021-04-09 11:43
this feature is a very bad feature, pleate sopport to disable it, thanks

**Comment by slikk66** [comment] 2021-05-14 16:59
I would like to disable all keyboard operations for the file explorer, period.  I just had to reconstruct missing files/folders that were appearing/disappearing, I have no idea how these things even were happening.  I'd prefer no files get deleted, undeleted/redeleted etc unless I use the mouse and menu actions to perform file operations.

**Comment by watsonian** [comment] 2021-06-15 20:43
I would like to reiterate that this needs to be addressed. I'm not sure why this feature was implemented, but it's caused me much grief. The behavior is unexpected and I find that I end up accidentally undoing file explorer operations when I had no intention of doing so several times per day. I've not once ever wanted to undo anything done in the explorer. So, this feature has introduced daily frustration to solve something that was never a problem. Behavior like this should be toggle-able and defaulted to disabled.

**Comment by gravity-addiction** [comment] 2021-07-04 00:48
Why is this still an issue??? The issue wouldn't be so bad if the REDO command actually worked. The feature is broken and should never have made it to production. It's been an issue for 6 month, I spent a month on sublime due to this issue. been pretty good and just had a folder complete get erased, not in the garbage can, not anywhere. just f'in gone, and redo gave me an empty folder..

**Comment by hga77** [comment] 2021-07-11 15:36
This is an absolute joke!! The guy who thought of this "feature" needs to be put into prison for life!!! What are you thinking vscode team??? You have shown a lack of user commitment.

GET RID OF THIS FEATURE NOW!!!!

**Comment by fedalvez** [comment] 2021-07-14 19:56
I think is a cool feature, however it needs to be confirmed by the user before doing it.

**Comment by figloalds** [comment] 2021-08-09 20:58
I would like to point out that I too fell victim to this diabolic "feature".
I had coded an entire new mechanism and while trying to undo multiple actions on a file elsewhere unrelated, the editor COMPLETELY UNDONE all my new work and it was not committed.
Luckily I was able to find my work on the windows trashbin, it could have been irreversible, this "feature" needs to be removed

**Comment by raygig** [comment] 2021-08-24 17:20
This is the most dangerous feature ever developed. PLEASE REMOVE IT!

**Comment by JacksonKearl** [comment] 2021-08-24 17:50
Hello all, I recently acquired this ticket. It seems there may be separate issues going on here and I want to make sure I understand the problem fully. The issue title requests a way to disable undo/redo for file operations, but in the comments I see folks saying that they've experienced dataloss due to these operations. To me these seem like different issues: undo/redo causing dataloss sounds like a bug, and disabling the operations sounds like a request. 

It would be helpful to me if someone could give a step by step description of how the dataloss is occurring (a screen recording on gifcap.dev would be helpful), and I will look to see how to fix that dataloss (the solution may indeed be to provide an option to disable file operations, but I don't know until I see what exactly is going on here). 

I have tested with undoing/redoing renaming folders, nested folders, and files and did not experience dataloss. 

I am aware of an outstanding ticket requesting redo of a folder deletion to work ( https://github.com/microsoft/vscode/issues/111022) however I'm not sure this is what's happening here, as in that case the files are still available in the trash and the user explicitly requested they be deleted.

**Comment by camnicklaus** [comment] 2021-09-13 15:45
I'm here to add my voice. I find this feature super frustrating.
I've just "lost" a file and had to recover it from the trash.
I'm grateful for this thread, as I didn't realize I could find my work in the trash... I've lost work previously :( 
For me It's difficult to recreate because when the it happens I'm not looking at the files directory window I'm looking at the code window and by the time you realize you're acting on a different window it's hard to know how many steps you've gone.

**Comment by dorkk-online** [comment] 2021-09-19 15:24
I literally just crashed my project because the undo removed all of my node modules. Although reinstalling node modules is an easy task I have lost multiple files and hours of work since the release of this feature.

**Comment by mark-hubers** [comment] 2021-09-30 14:51
To me, this is just about permanently deleted!  Yes, they end up in the trash, but on a macOS, my trash is enormous and you lose all the path info and spend hours at times trying to know what the hell it just deleted and where you need to restore it to.   So let say you have not to edit some files (made a new one, move a folder, rename a file) in many days, and your editing your code and then say OK that idea did not work and I would do a undo about 2 to 5 times thinking I am removing my last 2 to 5 edits in that file but did not know my pointer still inside the explorer and BAM! I just mess up my file system with the last 2 to 5 things I did in there over the last few weeks.  I do commit my changes but not every day or every hour so that is no help.  This has happened over 3 to 5 times so far and HATE this as this is not a feature as this is a job killer as it cost time and money.
I am going to try the keyboard mapping in the hope this fixes it for now but this should not be our fix as you are forcing all the other poor souls that will get burned by this as well before they learn to patch it up with a keymap override.
Sorry is really upset as last time this cost me  many hours and still not able to sleep thinking I miss something and will show up later on some prod system.

**Comment by zakariamofaddel** [comment] 2021-10-20 18:22
Same @tawani :( it was a very bad experience! Luckily I found my lost files in the trash and with some more work I was able to glue all the pieces back together.
This thought me to commit more often, but still a very dangerous feature that should be activated by user and disabled by default!

**Comment by m-zavgorodniy** [comment] 2021-11-02 16:44
This feature is hell *tired*, can we just remove it please guys

**Comment by TSiege** [comment] 2021-11-15 14:04
I'll chime in again, but I actually see the utility of this feature. It's nice to be able to copy and paste directories, as well as undo. But I think there should be an option to warn on file system undo as well as completely disabling it. It can be a highly destructive action and warrants confirmation from the user. Maybe it could be an option with `undo` values being `always`, `warn`, `disabled`?

**Comment by raygig** [comment] 2021-11-23 11:36
REMOVE THIS #$^&%@#!$ FEATURE!!!

**Comment by cjhopman** [comment] 2021-11-25 06:38
This is a terrible experience. I just lost about a day of work to this behavior. I don't know if it's related to working on a filesystem where vscode can't put things in trash, or if the undo buffer is too small or who knows, or if i accidentally did a real operation somewhere making vscode throw away the redo stack. Regardless of how it happened, I don't think it's a good idea to hijack such a common hotkey for destructive behaviors like deleting files and folders.

**Comment by peranadj** [comment] 2021-11-29 11:12
Wow had my first run in with this, what a silly feature..

**Comment by monim67** [comment] 2021-11-30 10:25
If this feature exists it should exist disabled by default.

**Comment by wandeber** [comment] 2021-12-28 19:04
Lost entire directory... It's not the first time I think I am undoing inside the text editor but I'm undoing in the directories. I can not hate this thing more ^^'

**Closed** 2022-01-05 04:59 UTC
Labels: feature-request, file-explorer, undo-redo

**Comment by JacksonKearl** [comment] 2022-01-05 06:59
In today's insiders is a new setting `explorer.enableUndo` which defaults to `warn`, providing a warning in the case of undoing create-via-paste/etc. events, and also supports options of `allow` (maintaining the old behavior), or `never` (explorer does not participate in undo at all). 

Please do let me know if you encounter any deletion events that are not properly warned about under the new `warn` setting.

**Comment by borislav-risika** [comment] 2022-01-20 14:20
Holy shit, who in their right mind thought this was a good feature?

**Comment by Reyescult** [comment] 2022-01-21 18:59
I gotta say, this and the undo after close/open are the kind of 'features' that make me HATE a program that I used to love. Making seemingly arbitrary changes to a default workflow that has existed for YEARS is a recipe for disaster, and this one is particularly nasty. I mean, what developer in their right mind would want such a destructive change to the default workflow of a program they have been using for any extended period of time? I had inadvertently been on an older version of VSCode for a while, and only discovered this madness recently. It has completely blown my workflow and caused me a LOT of problems.

**Comment by JacksonKearl** [comment] 2022-01-27 00:47
With tomorrow's Insiders (next week's Stable) this is now split this into two settings, `explorer.enableUndo` is a boolean controlling whether the explorer participates in Undo at all, and `explorer.confirmUndo` is an enum configuring how frequently to prompt before undoing.

**Comment by TSiege** [comment] 2022-01-31 19:24
Thanks so much @JacksonKearl. Really appreciate the response on this
