### ISSUE TITLE
Webview crashes with ECONNRESET on workspace folder changes

### ISSUE THREAD

**Issue by bfitzpat** [microsoft/vscode#83681] opened 2019-10-30 18:20 UTC
- VSCode Version: 1.39.2
- OS Version: Linux x64 5.0.0-25-generic

Steps to Reproduce:

1. Starting with the webview sample (https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample)
2. Add this after line 33 in extension.ts

```
	if (vscode.workspace.onDidChangeWorkspaceFolders){
		vscode.workspace.onDidChangeWorkspaceFolders( (e) => {
			console.log(e);
			vscode.window.showErrorMessage(`Workspace changed: ${e}`);
		});
	}
```
1. Start in a new workspace (with no workspace folders). Open the Cat Coding window
2. Add and remove folders to the workspace. Eventually you should see the webview developer tools pop up to the right with an ECONNRESET error. 

![image](https://user-images.githubusercontent.com/530878/67886550-3e4fa900-fb0f-11e9-8a5d-c83eb48f2fa6.png)

I have tried several different ways to catch that ECONNRESET issue, but nothing has worked. As soon as it occurs, all communication to/from the WebView and the extension code (any messages posted back and forth) cease to be passed. 

This seems like the issue https://github.com/microsoft/vscode/issues/42613, but there was no indication of what the "fix" was that corrected the problem on the user's side. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2019-11-13 06:10
Root cause is https://github.com/microsoft/vscode/issues/69335

Closing as a duplicate. Once #69335 is resolved, the extension host will no longer need to be restarted when the workspace's folders change

**Closed by mjbvz** 2019-11-13 06:10 UTC
