### ISSUE TITLE
Duplicate lines at end of file on save

### ISSUE THREAD

**Issue by rchipman** [Microsoft/vscode#25144] opened 2017-04-21 14:33 UTC
*Software Versions*
- VSCode Version: 11.1.2
- OS Version: Windows 10 Pro Version 1703

*Extensions* 
- Angular v4 Typescript Snippets - 2.2.3
- Auto Rename Tag - 0.0.11
- C# - 1.8.1
- Contextual Duplicate - 0.2.0
- Intellisense for CSS Class Names - 1.1.0
- JS-CSS-HTML Formatter - 0.2.3
- Material Theme Icons - 2.0.4
- TSLint - 0.12.0
- TypescriptHero - 0.12.0

Steps to Reproduce:

1. Save a file that you are working on.
2. Sometimes it randomly adds duplicate lines to the end of the file with the same line number.  Appears to only be a visual bug, you cannot select the lines that are added or do anything with them.

![duplicate-lines-bug](https://cloud.githubusercontent.com/assets/3871032/25282246/ea21621e-267d-11e7-970c-aeef1ea86134.png)

**Comment by mjbvz** [comment] 2017-04-21 18:42
This may be caused by one of your extensions. Can you please try running code using  `code --disable-extensions` in the command line to see if this is the case

**Comment by mjbvz** [comment] 2017-05-01 19:51
Closing as there is not enough info to investigate this. I suspect an extension is the root cause here

**Closed by mjbvz** 2017-05-01 19:51 UTC
Labels: needs more info
