### ISSUE TITLE
refacetor name in 'LF' mode

### ISSUE THREAD

**Issue by Stuben** [Microsoft/vscode#18019] opened 2017-01-03 03:53 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|

---

Steps to Reproduce:

1.refacetor name in 'LF' mode
2.the target name is not refacetor but change others

**Comment by sandy081** [comment] 2017-01-03 09:43
@Stuben Description is not helpful to understand where and what the problem is. Can you please provide detailed steps to reproduce and some code snippets.

Thanks

**Comment by mjbvz** [comment] 2017-01-09 18:58
Closing as we need more information to investigate.

@Stuben Please describe the issue, along with the expected behavior and the current behavior so that we can investigate. 

Thanks.

**Closed by mjbvz** 2017-01-09 18:58 UTC
Labels: needs more info
