### ISSUE TITLE
Allow to fix tabs (like pinning in Chrome)

### ISSUE THREAD

**Issue by lucas-viewup** [Microsoft/vscode#33509] opened 2017-08-30 11:44 UTC
A interesting thing I see in browsers, specially Google Chrome, is the feature to fix tabs. It would be possible to implement it in Visual Studio Code? Sometimes I close by mistake the open tabs of editor. Thanks!

**Comment by ramya-rao-a** [comment] 2017-09-18 21:53
@bpasero How is this different from #12622?

**Comment by mjbvz** [comment] 2017-11-03 22:23
Closing as duplicate of #12622

**Closed by mjbvz** 2017-11-03 22:23 UTC
Labels: duplicate, feature-request, workbench, workbench-tabs
