### ISSUE TITLE
Unsaved file state not shown when Autosave delay <= 1000 ms

### ISSUE THREAD

**Issue by L-Sypniewski** [Microsoft/vscode#60894] opened 2018-10-14 14:33 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Set Auto Save setting to "afterDelay"
2. Set Auto Save Delay setting to 1000 miliseconds or less
3. Modify any opened file

For 1001 ms it works perfectly fine - I can see white circle on the file tab indicating the file hasn't been saved yet, after a moment it disappears as the file has been saved.

For values <= 1000 indicator is not shown, suggesting the file is being saved immediately.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (2.84GB free)|
|Process Argv|code --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by bpasero** [comment] 2018-10-15 05:10
Yes, closing as designed. We do not show the dirty indicator for values of 1ms and below. There is a bit of history to it: originally VSCode never had a dirty indicator (auto save was the only thing). We then added a way to disable auto save but no-one in the team liked the fact that you would see a dirty indicator (because that is a hint for auto-save not being enabled). Thus I decided to only show the dirty indicator for delays >1s.

**Closed by bpasero** 2018-10-15 05:10 UTC
Labels: new release
