### ISSUE TITLE
Typo modifiedStart < modifiedStart

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#32283] opened 2017-08-11 06:06 UTC
https://github.com/Microsoft/vscode/blob/90b6859f375e2b4d6707181cbe8bcf78b6289919/src/vs/base/common/diff/diff.ts#L863

**Comment by chrisdias** [comment] 2017-08-11 06:24
dupe of https://github.com/Microsoft/vscode/issues/32233

**Closed by chrisdias** 2017-08-11 06:24 UTC
