### ISSUE TITLE
File path case-insensitivity on Windows

### ISSUE THREAD

**Issue by martincohen** [Microsoft/vscode#18718] opened 2017-01-18 10:25 UTC
[As requested](https://github.com/Microsoft/vscode/issues/12922#issuecomment-273415314) by @isidorn, I'm filing this issue separately.

The issue of case-insensitivity on Windows is basically breaking everything with my experience in C/C++ development, especially when using MSVC toolchain. I have duplicate files opened most of the time (that are not with same path according to `vscode`, therefore they function as two distinct files):
![image](https://cloud.githubusercontent.com/assets/421916/22060213/31962096-dd70-11e6-81a7-cc0825862618.png)

The problem often (like every 5 minutes) results in this:
![image](https://cloud.githubusercontent.com/assets/421916/22060215/3884c7d6-dd70-11e6-9b7f-a86d905fc602.png)

Which in turn results in a lot of changes being lost, or serious time waste in trying to merge the two files.

In my humble opinion, this is a major issue in the `vscode` core for anyone trying to use Windows-only command-line tools. And so it is a problem for extension creators on Windows, as they are required to be extra careful with case-sensitivity required currently by `vscode`, which does not follow platform guidelines for handling paths.

Also it is very easy to get to this state (using MSVC `cppvsdbg`), which is the biggest problem:
1. Open a file from *Explorer*.
2. One of the following:
  a. Put breakpoint to a C/C++ file. Run debug and get a new file instance each time you step (so even if you close it, the next step will reopen the same file).
  c. Open an issue from *Problems* view and get a new file instance.
  d. Open a file from external application with different case in the path (cmd, Total Commander, etc.) and get a new file instance.

In fact you can have dozens of instances of the same file.
![image](https://cloud.githubusercontent.com/assets/421916/22060284/7215020e-dd70-11e6-8c80-10e093ba1cd5.png)

**Comment by bpasero** [comment] 2017-01-18 11:51
Duplicate of https://github.com/Microsoft/vscode/issues/12448

**Comment by bpasero** [comment] 2017-01-18 11:52
![image](https://cloud.githubusercontent.com/assets/900690/22063017/e9d9a540-dd7c-11e6-8af5-89376660d2a1.png)

**Closed** 2017-01-18 11:51 UTC
