### ISSUE TITLE
Dvorak keyboard on Ubuntu uses qwerty keys for some commands

### ISSUE THREAD

**Issue by peredwardsson** [microsoft/vscode#109909] opened 2020-11-03 11:53 UTC
Issue Type: <b>Bug</b>

To reproduce:
- Switch keyboard layout to any Dvorak (or assumably any non-qwerty) layout 
- Select some text
- Copy using ctrl C
- Paste using ctrl V

No text will be pasted. Instead, copying, pasting and a handful of other commands (notably find (ctrl F), but not find in files (ctrl shift F)) use the QWERTY layout buttons rather than my preferred layout.

I suspect this can come from some keys being registered by the button rather than the letters they represent. This is not a behaviour I expect from VS code, and indeed, this is not a problem when trying to reproduce this on a Windows machine. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.4.0-52-generic snap
Remote OS version: Linux x64 4.15.0-120-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.49GB (5.14GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 8ffb9f82-9740-4c3d-8bff-8f166eeceb46|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 172.27.176.11|
|OS|Linux x64 4.15.0-120-generic|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2423)|
|Memory (System)|15.54GB (11.61GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.7.0
remote-containers|ms-|0.145.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
vscode-icons|vsc|11.0.0
python|ms-|2020.10.332292344
cpptools|ms-|1.0.1

</details>

**Comment by alexdima** [comment] 2020-11-06 10:12
Please see https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

Most likely duplicate of #23690 or #24166

**Closed by alexdima** 2020-11-06 10:12 UTC
Labels: linux
