### ISSUE TITLE
Reverse search not working for ZSH in integrated terminal

### ISSUE THREAD

**Issue by tairosonloa** [microsoft/vscode#138079] opened 2021-11-29 18:13 UTC
Reverse search doesn’t work for ZSH in integrated terminal (WSL 2 Ubuntu). However, it works for bash from integrated terminal (also WSL2 Ubuntu). Reverse search works for ZSH if I use another terminal emulator, like Windows Terminal or `wsl.exe`  command inside `Powershell.exe`, so it doesn't look like a ZSH configuration error itself.

Things I have already tried (without success):
```jsonc
// On my settings.json
{
  "terminal.integrated.allowChords": false
}
```

```jsonc
// On my keybindings.json
[
  {
    "key": "ctrl+r",
    "command": "workbench.action.terminal.sendSequence",
    "args": { "text": "\u0012" },
    "when": "terminalFocus"
  },
]
```

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Windows 10 x64 10.0.19042 and WSL 2

Steps to Reproduce:

1. Open an integrated terminal inside vscode
2. Focus integrated terminal
3. Press Ctrl+R
4. Nothing happends

My `settings.json`:
```jsonc
{
  // Core VSCode features
  "files.autoSave": "onWindowChange",
  "telemetry.telemetryLevel": "off",
  "explorer.confirmDelete": false,
  "explorer.confirmDragAndDrop": false,
  "explorer.autoReveal": false,
  "terminal.integrated.tabs.enabled": true,
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "terminal.integrated.allowChords": false,

  // Theme and visuals
  "workbench.colorTheme": "Monokai Pro",
  "workbench.iconTheme": "material-icon-theme",
  "material-icon-theme.activeIconPack": "react",
  "material-icon-theme.showUpdateMessage": false,
  "material-icon-theme.showReloadMessage": false,
  "breadcrumbs.enabled": true,

  // Editor and code format
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.fontSize": 12.5,
  "editor.tabSize": 2,
  "editor.renderWhitespace": "boundary",
  "editor.suggestSelection": "first",
  "editor.emptySelectionClipboard": false,
  "editor.guides.bracketPairs": true,

  // File explorer
  "files.exclude": {
    ".cache": true,
    ".dist": true,
    ".history": true,
    ".idea": true,
    "**/.classpath": true,
    "**/.factorypath": true,
    "**/.project": true,
    "**/.settings": true,
    "code/dist": true,
    "dist": true
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "eslint.alwaysShowStatus": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll": true,
    "source.organizeImports": true
  },
  "editor.formatOnSave": true,
  "editor.formatOnSaveMode": "modifications",
  "editor.formatOnPaste": false,

  // Language custom settings
  "[python]": {
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.defaultFormatter": null,
    "editor.formatOnSaveMode": "file"
  },
  "[xml]": {
    "editor.defaultFormatter": "redhat.vscode-xml"
  },
  "[javascript, javascriptreact, typescript, typescriptreact]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
    "editor.formatOnSave": false
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  // "javascript.inlayHints.parameterNames.enabled": "all",
  "typescript.updateImportsOnFileMove.enabled": "always",
  "typescript.preferences.importModuleSpecifier": "relative",
  // "typescript.inlayHints.parameterNames.enabled": "all",
  "python.languageServer": "Pylance",
  "python.formatting.provider": "black",
  "python.formatting.blackArgs": ["--line-length", "120"],
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter.notebook.ipynb"
  },

  // Git
  "git.enableCommitSigning": true,
  "git.confirmSync": false,
  "git.autofetch": true,
  "diffEditor.ignoreTrimWhitespace": false,
  // GitHub
  "githubPullRequests.telemetry.enabled": false,
  "githubPullRequests.terminalLinksHandler": "github",
  // Git lens
  "gitlens.mode.active": "review",

  // Atlassian
  "yaml.schemas": {
    "file:///home/aalonso/.vscode-server/extensions/atlassian.atlascode-2.9.0/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml"
  },
  "atlascode.jira.explorer.nestSubtasks": true,
  "atlascode.bitbucket.pipelines.explorerEnabled": false,
  "atlascode.helpExplorerEnabled": false,
  "atlascode.bitbucket.issues.explorerEnabled": false,

  // Other extensions
  "todo-tree.tree.showScanModeButton": false,
  "todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)",
  "todo-tree.general.tags": [
    "BUG",
    "HACK",
    "FIXME",
    "TODO",
    "XXX",
    "[ ]",
    "[x]"
  ],
  "redhat.telemetry.enabled": false
}
```

My `keybindings.json` is empty (but I tried passing `\u0012` to the terminal as I explained above).

I have not additional settings files

**Comment by Tyriar** [comment] 2021-11-29 19:40
Can you try [enabling escape sequence logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging) and pasting in the output? This will tell us what the shell process is telling the terminal to do which will identify whether it's an issue with rendering or the process telling us the wrong thing.

/label "needs more info"

**Comment by tairosonloa** [comment] 2021-11-29 20:01
> Can you try [enabling escape sequence logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging) and pasting in the output? This will tell us what the shell process is telling the terminal to do which will identify whether it's an issue with rendering or the process telling us the wrong thing.

This is the output I got:
```
xterm.js: sending data "" 
[18]
0: 18
length: 1
__proto__: Array(0)
concat: ƒ concat()
constructor: ƒ Array()
copyWithin: ƒ copyWithin()
entries: ƒ entries()
every: ƒ every()
fill: ƒ fill()
filter: ƒ filter()
find: ƒ find()
findIndex: ƒ findIndex()
flat: ƒ flat()
flatMap: ƒ flatMap()
forEach: ƒ forEach()
includes: ƒ includes()
indexOf: ƒ indexOf()
join: ƒ join()
keys: ƒ keys()
lastIndexOf: ƒ lastIndexOf()
length: 0
map: ƒ map()
pop: ƒ pop()
push: ƒ push()
reduce: ƒ reduce()
reduceRight: ƒ reduceRight()
reverse: ƒ reverse()
shift: ƒ shift()
slice: ƒ slice()
some: ƒ some()
sort: ƒ sort()
splice: ƒ splice()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
unshift: ƒ unshift()
values: ƒ values()
Symbol(Symbol.iterator): ƒ values()
Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}
__proto__: Object
LogService.ts:62 xterm.js: parsing data 

[A[0m[27m[24m[J[33maalonso [35m~ 
[34m❯[00m [K[186C[33m(29-11 20:49)[00m[199D
```

Also, I did a bit more of testing, and it only occurs when in a remote-WSL folder. Native Windows folders haven't this problem. In both production and insiders version of vscode. Also, if I select profile `Ubuntu (WSL)` but without using the `connecto to remote WSL folder` thing, I'm able to use reverse search, even when the shell is in a WSL path (I tested the same path in all situations).

Strange that I didn't detected it with the initial `code --disable-extensions`, btw.

**Comment by Tyriar** [comment] 2021-11-29 20:09
This says we're doing the right thing, once we pass that sequence onto the pty it's out of our hands.

```
xterm.js: sending data "�" 
[18]
0: 18
```

I tried to reproduce and couldn't unfortunately. I suspect this is somehow related to your setup, maybe try diffing the terminal's environment (`env`) in zsh to see if something there could be causing the issue. Closing it out as I don't believe there's anything I can do to action.

> Strange that I didn't detect it with the initial code --disable-extensions, btw.

You mentioned it only happens when using a remote wsl window so `code --disable-extensions` should prevent that from opening?

**Closed by Tyriar** 2021-11-29 20:09 UTC
Labels: needs more info

**Comment by tairosonloa** [comment] 2021-11-29 21:04
After a big deep debugging sessions, it looks like having `export EDITOR=vim` in my `.zshrc` file makes reverse reach stop working. But this issue **ONLY** happens in the vscode integrated terminal. I have tried it like 10 times already, because I cannot believe.

Also, this only occurs if the `export EDITOR=vim` is inside `.zshrc`. Letting ZSH load and manually type in the cli `export EDITOR=vim` doesn't make reverse search to stop working.  It has to be something related to zsh initialization (although I have a really minimalist and straight-forward setup).

What I cannot understand is why this behavior **ONLY OCCURS** in the vscode integrated terminal.

**Comment by tairosonloa** [comment] 2021-11-29 21:09
Is there any problem with setting `EDITOR` env variable regarding vscode integrated terminal @Tyriar ?

**Comment by Tyriar** [comment] 2021-12-08 14:03
No idea, haven't heard of that before and I can't reproduce it either when I set EDITOR.
