### ISSUE TITLE
Notebooks: Cannot "Save As..." notebook

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96565] opened 2020-04-29 11:43 UTC
Steps:
* open a notebook
* select File > Save As...

=> 🐛 nothing happens, I am not being asked for a path.

**Comment by bpasero** [comment] 2020-04-30 11:35
Looks like `notebookEditorInput` is missing to implement the `saveAs` method.

**Comment by rebornix** [comment] 2020-05-01 00:32
/duplicate of https://github.com/microsoft/vscode/issues/96482 . Thanks for reporting, it might require some API change, we will look into this in next Iteration.

**Closed by rebornix** 2020-05-01 00:32 UTC
Labels: notebook
