### ISSUE TITLE
Hover status bar accessible view could have more info

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#218213] opened 2024-06-25 21:15 UTC
Testing #217237

When hovering a status bar with actions (like the "view problem"/"quick fix" actions), the accessible view/help only says "This is a hover status bar". Any reason it doesn't list the actions? Seems like that might be helpful

**Comment by aiday-mar** [comment] 2024-06-26 09:38
duplicate of https://github.com/microsoft/vscode/issues/217975

**Closed by aiday-mar** 2024-06-26 09:38 UTC
Labels: polish, editor-autoindent
