### ISSUE TITLE
'File: Save All' for 300+ files hangs VS Code

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#92917] opened 2020-03-18 11:12 UTC
- VSCode Version: 1.4.30
- OS Version: Ubuntu 16.04.05

Steps to Reproduce:

1. Change +300 files.
2. Press `ctrl+k s`

I am running VS Code on Windows 10, but using VS Code remote to connect to a remote ssh host. Both have 16gb of ram, and does not use it all even when saving.

I noticed this behavior when doing a search&replace, that automatically saves the files. I also tried to manually save the all changed files via ´ctrl+k s´ and the same things happens.

Does this issue occur when all extensions are disabled?: Yes

**Comment by thernstig** [comment] 2020-03-18 11:21
I also noticed it loses the ssh connections and pops up the window with "Attempting to re-connect", which never happens (it keeps repeating). ssh'ing to the VM and checking `top` shows nothing strange. It is Python files being changed.

**Comment by roblourens** [comment] 2020-03-18 16:49
So you don't see any process using high cpu when this happens? What remote extensions do you have installed? Had a similar report that sounds like some extension is slowing things down during a large search/replace but haven't been able to reproduce this yet.

**Comment by thernstig** [comment] 2020-03-18 19:07
@roblourens I now realize I forgot to disable extensions, and in this case since it was Python files, it was the Python extension that froze. I verified this by disabling all extensions but `Remote  - SSH` and did the rename and all worked fine. Then I enabled the `Python` extension and did the same, it totally froze up. I double-checked `top` and found this to be the culprit when this happened:

```sh
PID        USER      PR  NI    VIRT     RES       SHR   S  %CPU  %MEM    TIME+   COMMAND
129267  yesbox   30  10    73696  45324   3632  R  96.0     0.3           2:50.74  tessellimage
```

After I closed VS Code from the Task Manager in Windows, I noticed that after about 5-10 seconds `tesselimage` dropped from the `top` list.

Should this maybe be moved to https://github.com/microsoft/vscode-python? Not sure you can do that though.

**Comment by roblourens** [comment] 2020-03-23 02:13
This doesn't sound like something the Python extension would use, that's strange. http://manpages.ubuntu.com/manpages/xenial/man6/tessellimage.6x.html. Thanks for your testing though.

Closing this as a dupe of https://github.com/microsoft/vscode/issues/89300 and will keep investigating it there.

**Closed by roblourens** 2020-03-23 02:13 UTC
Labels: needs more info, remote

**Comment by thernstig** [comment] 2020-03-23 13:06
@roblourens I agree completely that it is quite strange that process would show up, but I tested this twice and it was the same process name both times that started consuming all that cpu.
