### ISSUE TITLE
Cannot read property 'status' of null

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#7593] opened 2016-06-13 05:59 UTC
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open https://github.com/rubyide/vscode-ruby in Insider
2. F5 to debug
3. A new vscode instance pops up, wait for a few seconds. There is an error message pops up saying `Cannot read property 'status' of null`

Expected:
It should tell me local extension is overriden by the developing one.

StackTrace
```
Cannot read property 'status' of null: TypeError: Cannot read property 'status' of null,    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:7:12524,    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:7980),    at Object.W.enter (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:12065),    at n.Class.define._run (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:13386),    at n.Class.define._chainedError (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:12745),    at n (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:10568),    at n.Class.define.then (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:14195),    at Object.N.enter (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:10637),    at n.Class.define._run (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:13386),    at n.Class.define._setCompleteValue (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\node\gitApp.js:5:13080)e.doShow @ messageService.ts:119
keybindingResolver.ts:188 Conflict detected, command `scrollPageDown` cannot be triggered by ctrl+pagedown due to workbench.action.nextEditor
```

The error is thrown from  https://github.com/Microsoft/vscode/blob/c843d58563919cad115448fb93cd8774f722a5e5/src/vs/workbench/services/message/browser/messageService.ts#L119

**Comment by joaomoreno** [comment] 2016-06-13 09:24
Duplicate of #7597

**Closed by joaomoreno** 2016-06-13 09:24 UTC
