### ISSUE TITLE
Selection in GIT View does not change the editor view

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#24222] opened 2017-04-07 13:12 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-71-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.4.0|
|githistory|donjayamanne|0.2.0|
|phpunit|emallin|1.0.0|
|php-intellisense|felixfbecker|1.1.4|
|text-transform|florianloch|0.1.0|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|theme-dark-starry-night|jerry|1.0.2|
|vscode-simple-icons|LaurentTreguier|1.0.1|
|Go|lukehoban|0.6.59|
|vscode-todo|MattiasPernhult|0.8.0|
|vs-keybindings|ms-vscode|0.1.3|
|vscode-docker|PeterJausovec|0.0.13|
|material-icon-theme|PKief|2.0.3|
|better-merge|pprice|0.5.1|
|swaggitor|qnsolutions|0.1.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|2.3.9|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1. Have several files with changes ( I had one with conflict to be staged)
2. I solved the conflict, hit ctrl+s and then I wanted to see an other file, so I clicked

Nothing happens in the editor view.
After closing vscode there was still a process running.

**Comment by chrmarti** [comment] 2017-04-07 15:15
@DasJott Could you check what that processes command line arguments are?

**Comment by joaomoreno** [comment] 2017-04-07 15:20
> Nothing happens in the editor view.

Do you mean that a diff editor comes up without any contents?

**Comment by wushanchao** [comment] 2017-04-10 02:47
Mac OSX Yosemit 10.10.4
VSCode 1.11.1
hava the same problme.

**Comment by DasJott** [comment] 2017-04-10 07:22
> Do you mean that a diff editor comes up without any contents?

The editor is frozen. Contents stay the same. 
I will check the process as soon as possible.

**Comment by joaomoreno** [comment] 2017-04-10 08:52
@DasJott Can you show me a screenshot?

**Comment by DasJott** [comment] 2017-04-10 09:32
As it does not always happen and I use it with clear source code, chances are good, that I can not provide any screenshots. 
Anyway it would only show one file opened in editor and another one selected the left.

**Comment by joaomoreno** [comment] 2017-04-10 12:16
OK, pretty sure this is a duplicate of #23977

**Closed by joaomoreno** 2017-04-10 12:16 UTC
Labels: needs more info

**Comment by DasJott** [comment] 2017-04-10 12:18
Yep, looks like a duplicate.
