### ISSUE TITLE
Change logic of "Ctrl+Shift+[E F G D X]" to toggle between hide/show rather than only show

### ISSUE THREAD

**Issue by t-hofmann** [Microsoft/vscode#48545] opened 2018-04-24 12:54 UTC
This feature would allow the user to show and hide with the same shortcut. Additionally it would not force to learn "Ctrl+B" for hiding.

**Comment by yume-chan** [comment] 2018-04-28 09:39
Another duplicate to #41186, relates to #19400

It's quite popular for this feature request.

**Comment by bpasero** [comment] 2018-09-14 13:56
Closing as duplicate of https://github.com/Microsoft/vscode/issues/41186

We cannot change these commands to hide the sidebar because they are showing up in the main menu and it seems wrong to hide the sidebar when you pick them from the menu in case already visible.

**Closed by bpasero** 2018-09-14 13:56 UTC
Labels: feature-request, workbench-layout
