### ISSUE TITLE
"Failed to create terminal for task" after closing terminal from dependsOn task

### ISSUE THREAD

**Issue by dominikschreiber** [Microsoft/vscode#68431] opened 2019-02-11 14:24 UTC
Issue Type: <b>Bug</b>

Consider the following tasks.json:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "hello world",
            "command": "",
            "type": "shell",
            "dependsOn": [
                "hello",
                "world"
            ],
            "problemMatcher": []
        },
        {
            "label": "hello",
            "type": "shell",
            "command": "echo",
            "args": [
                "hello"
            ],
            "problemMatcher": []
        },
        {
            "label": "world",
            "type": "shell",
            "command": "echo",
            "args": [
                "world"
            ],
            "problemMatcher": []
        }
    ]
}
```

1. run task "hello world"
2. close both spawned terminals by pressing a key
3. then run any other task (e.g. "hello").

*Expectation:* the task should run.

*Observation:* the task is not run. Instead, a warning "There are task errors. See task output for details." and an error "Failed to create terminal for task hello" are shown. VSCode has to be reopened to run tasks again. This is reproducible with MacOS and Windows stable builds (don't have a Linux build at hand, but I assume it happens there as well). It worked before the January 2019 update.

The intention behind the "hello world" task is to have a common "wrapper" for multiple independent tasks, where the wrapper actually does nothing. It is quite possible that I misinterpret the [Integrate with External Tools via Tasks](https://code.visualstudio.com/docs/editor/tasks) article, and that the desired result should be achieved differently. On the other hand, it worked before the January update...

Thank you  for looking into this. You're really doing an awesome job and make my life as a developer better every day!

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (15.68GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.0.26
vscode-eslint|dba|1.8.0
vsc-material-theme|Equ|2.6.3
nasc-touchbar|fel|1.11.0
beautify|Hoo|1.4.8
java-properties|ith|0.0.2
vscode-jsp|pth|0.0.2
rust|rus|0.5.3
perforce|sle|3.1.0

</details>

**Comment by dharrington** [comment] 2019-02-11 18:57
I'm seeing this same error in 1.31.0 as well, but I'm not using "dependsOn". I'm using the ' panel: "shared" ' presentation option. I seem to be able to avoid the problem by switching to panel: "dedicated".

**Comment by alexr00** [comment] 2019-02-12 10:35
Duplicate of https://github.com/Microsoft/vscode/issues/68077. The fix is already available in Insiders, and will go out to stable in the recovery build.

**Closed by alexr00** 2019-02-12 10:35 UTC
Labels: tasks
