### ISSUE TITLE
Mouse pointer not displayed 

### ISSUE THREAD

**Issue by johncatley** [Microsoft/vscode#47646] opened 2018-04-11 08:45 UTC
Issue Type: <b>Bug</b>

Over the part that displays the code, the mouse pointer is not visible.
VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
sass-indented|rob|1.4.8

</details>

**Comment by bpasero** [comment] 2018-04-12 04:54
Duplicate of https://github.com/Microsoft/vscode/issues/47076

**Closed by bpasero** 2018-04-12 04:54 UTC
