### ISSUE TITLE
 the editor does not support Chinese

### ISSUE THREAD

**Issue by wjtGitHub** [Microsoft/vscode#28298] opened 2017-06-09 06:31 UTC
- VSCode Version:1.13.0
- OS Version:window7

Steps to Reproduce:

After the update is complete, the editor does not support Chinese

**Comment by chy9002** [comment] 2017-06-09 06:49
same issue with mac version. UI been changed to English after update.

**Comment by michelkaporin** [comment] 2017-06-09 07:03
Duplicate of #28268

**Closed by michelkaporin** 2017-06-09 07:03 UTC
Labels: new release
