### ISSUE TITLE
Feature regression [v1.31]: Fold Markdown by heading level

### ISSUE THREAD

**Issue by noraj** [Microsoft/vscode#68360] opened 2019-02-10 14:14 UTC
In v1.22 VSCode introduced a feature [Fold Markdown by heading level](https://code.visualstudio.com/updates/v1_22#_fold-markdown-by-heading-level).

It was working until v1.30 but it seems the feature disappeared in v1.31.

Versions:

```
Version: 1.31.0
Commit: bb1e228e30ce43ebb361c84fdf2f0d4fb7fda6ce
Date: 2019-02-09T14:23:42.615Z
Electron: 2.0.16
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.20.7-arch1-1-ARCH
```

Vscode is installed from ArchLinux (see this [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/code)).

Steps to Reproduce:

1. Open a markdown file
2. No folding possible

Does this issue occur when all extensions are disabled?: Yes

**Comment by noraj** [comment] 2019-02-10 14:15
As the (clever) bot said, it seems to be related to #68354.

**Comment by mjbvz** [comment] 2019-02-11 16:27
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment] 2019-02-12 19:37
Also, please check the developer logs as described in #68354

**Comment by mjbvz** [comment] 2019-02-13 19:10
Closing as likely duplicate of #68354

**Closed by mjbvz** 2019-02-13 19:10 UTC
Labels: markdown, needs more info

**Comment by noraj** [comment] 2019-02-13 21:22
@mjbvz It doesn't happen in vscode insider.

```
Version: 1.31.0
Commit: bb1e228e30ce43ebb361c84fdf2f0d4fb7fda6ce
Date: 2019-02-09T14:23:42.615Z
Electron: 2.0.16
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.20.7-arch1-1-ARCH
```
