### ISSUE TITLE
VS Code closed unexpectly

### ISSUE THREAD

**Issue by Coder-Bryan** [microsoft/vscode#190003] opened 2023-08-09 03:07 UTC
Type: <b>Bug</b>

1. uncomment codes with "ctrl + / "
2. VS Code closed directly

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.15.0-162-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.73GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2B7b22686f73744e616d65223a22446f7261646f2d646576227d/home/bryan.wang/develop/tops_v1/tops/library/computing --crash-reporter-id 0b12c1bf-dcff-4899-8349-dfb1dcd56abc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Dorado-dev|
|OS|Linux x64 4.15.0-162-generic|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 2179)|
|Memory (System)|62.83GB (54.44GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
gitlens|eam|14.2.0
debugger|enf|1.0.0
cpplint|min|0.1.3
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.10
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
clang-format|xav|1.9.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by bibartaks** [comment] 2023-08-09 04:34
It seems like you're encountering a bug related to using the "ctrl + /" shortcut to uncomment code in VS Code, which then leads to VS Code closing abruptly. This can be quite frustrating, but there are a few steps you can take to try and resolve this issue:

Check for Extension Conflicts:
Start by disabling all extensions and then try to reproduce the issue. If the problem goes away, re-enable your extensions one by one until you identify the one causing the conflict. This will help you narrow down the culprit.

Update Extensions:
Ensure that all your extensions are up to date. Sometimes outdated extensions can cause compatibility issues with newer versions of VS Code.

Update VS Code:
Make sure you're using the latest version of Visual Studio Code. Bugs and compatibility issues are often resolved in newer releases. You mentioned using version 1.81.0, but newer versions might have addressed this problem.

Reset Keyboard Shortcuts:
If the issue persists, reset your keyboard shortcuts to their default settings. This can help if there's a conflict with a custom shortcut you've set up. To do this, open the Command Palette (Ctrl+Shift+P), search for "Preferences: Open Keyboard Shortcuts (JSON)," and then reset the JSON file to its default contents.

Check for Operating System Updates:
Ensure that your Windows operating system and any relevant drivers are up to date. Sometimes conflicts between software can cause unexpected behavior.

Submit a Bug Report:
If none of the above steps resolve the issue, consider submitting a bug report to both VS Code and the relevant extension's GitHub repositories. Include detailed information about your environment, the steps to reproduce the issue, and any error messages you encounter.

Temporary Workaround:
In the meantime, you might consider using an alternative method to uncomment code, such as selecting the code and pressing the "Delete" key or using the "Edit" menu. This can help you avoid triggering the issue until it's resolved.

Remember that software bugs can be complex and might require the attention of the developers to fix. If the issue is widespread and causing significant inconvenience, it's likely that the VS Code team is already aware of it and working on a solution.

**Comment by dbaeumer** [comment] 2023-08-10 06:47
Anything special you did with keybindings?

**Closed** 2023-08-17 11:24 UTC
Labels: info-needed
