### ISSUE TITLE
When I minimize VS-Code while using windows-key + arrow keys, VS-Code becomes unresponsive untill I maximize it to fullscreen. 

### ISSUE THREAD

**Issue by Nieksa** [Microsoft/vscode#4494] opened 2016-03-21 10:33 UTC
- VSCode Version: 0.10.11
- OS Version: Windows  10

Steps to Reproduce:

1. Open Chrome set it to the left side of the screen with Windows key + Left arrow key
2. Op VS-Code and set it to the right side of the screen with Windows + Right arrow key.

in some cases VS-Code becomes unresponsive to mouse inputs until it is resized to max.

**Comment by bpasero** [comment] 2016-03-24 06:30
I tried to reproduce but cannot. Something in your system is maybe configured in a way that causes this?

**Comment by beebes** [comment] 2016-04-12 02:07
This reproduces for me as well on Windows 10. Pretty much the same repo steps, except I don't think it matters what program you dock to the other side.

1. Open VS Code.
2. Press Windows + Left Arrow
3. Pick another window to dock to the right by hitting enter, in my case Microsoft Edge.
4. Click back into the VS Code document editing window to give it focus.
5. Type some text; nothing shows up.
6. Maximize the window, everything you entered suddenly appears.

I originally looked into this because someone else complained to me about it, so I think that's at least 3 repros. :)

**Comment by bpasero** [comment] 2016-04-12 05:10
Can you guys check if insiders release fixed this somehow? 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by beebes** [comment] 2016-04-12 16:13
It still repros for me with the latest Code insiders build. However, I just tried it on a machine running an insiders Windows 10 build, and I can't seem to repro it there at all. So it may be something they've changed/fixed in more recent Windows 10 builds.

**Comment by bpasero** [comment] 2016-04-12 17:14
Interesting :+1:

**Closed** 2016-04-25 07:20 UTC
Labels: needs more info, upstream
