### ISSUE TITLE
VS Code dull and with grey blocks on 2nd screen

### ISSUE THREAD

**Issue by nickpma** [microsoft/vscode#98176] opened 2020-05-19 14:25 UTC
- VSCode Version: 1.45.1
- OS Version: Windows 10 v2004
- Laptop: Surface Book 2
- 2nd Screen: Dell 

**Issue:**
Got VS code installed on my Surface Book 2, but on my external screen it is unusable.
As per screenshot, it looks very dull and random grey blocks appear.
All other software looks perfectly fine on my 2nd screen. Also, this applies to all themes, not just the dark theme.

**Steps to Reproduce:**

1. Perform a fresh install of VS Code
2. Open VS code on 1st screen
3. Everything looks fine
4. Open VS Code on 2nd screen
5. VS code looks very dull and is showing grey blocks

Does this issue occur when all extensions are disabled?: Yes

**Steps Taken to Resolve:**

1. Fresh install of VS Code
2. Checked display settings and change primary monitor
3. Changed VS code colour scheme
4. Enabled/disable minimap

![vscodeissue](https://user-images.githubusercontent.com/15964477/82338326-1b93cc00-9a30-11ea-99cb-2bc552c01c2e.png)

**Comment by nickpma** [comment] 2020-05-19 14:43
After some more research it seems this issue has been raised in the past:
[https://github.com/Microsoft/vscode/issues/68069](url)

However it might have come back, now with the weird grey blocks.
Disabling HDR works, but that's not what I would like on my expensive 2nd screen.

**Comment by IllusionMH** [comment] 2020-05-19 17:48
/duplicate of  #88491

Linked issue contains current workaround with enforcing color profile

**Closed** 2020-05-19 17:49 UTC
Labels: *duplicate
