### ISSUE TITLE
My text font color is bugged

### ISSUE THREAD

**Issue by Franh01** [microsoft/vscode#166525] opened 2022-11-17 01:31 UTC
Type: <b>Bug</b>

I'm not really sure what happened, just reloaded window from the console (CTRL+SHIFT+P) and then tried everything to solve it, even reinstalled vs code.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.93GB (16.42GB free)|
|Process Argv|--crash-reporter-id efcf05bb-2972-4767-9143-373f8b5bc1dc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.0.4
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
json|Mee|0.1.2
vscode-typescript-next|ms-|5.0.20221116
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
icons|tal|3.6.0
bootstrap4-vscode|the|6.1.0
errorlens|use|3.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
3d0df643:30608728
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by Moyise** [comment] 2022-11-17 01:48
I have the same issue.

**Comment by joshuaconnorsmith** [comment] 2022-11-17 01:48
Seeing this issue as well. Text color seems to be almost entirely white for me

**Comment by AmelloAster** [comment] 2022-11-17 01:50
me too

**Comment by 3lang3** [comment] 2022-11-17 02:19
same issue

**Comment by MARIOMARUI** [comment] 2022-11-17 02:20
what reason is this

**Comment by dehyang** [comment] 2022-11-17 02:31
![image](https://user-images.githubusercontent.com/83799221/202340164-8906d77b-13d4-49ea-bf41-d5c11d83d021.png)
It's like this when I go to work in the morning

**Comment by strawji02** [comment] 2022-11-17 02:35
![image](https://user-images.githubusercontent.com/26446288/202340627-268540d2-acca-4936-bb95-0c77b223a582.png)
This is terrible :(

**Comment by CorgiOnNeptune** [comment] 2022-11-17 02:37
Having strange, maybe connected issue. 

My comment lines in Javascript files are not darkening, regardless of themes/extensions.
But my comment lines are formatting just fine in any other file type. (html, json, css).

Started happening ever since I tried to do a VSCode LiveShare with a classmate.

![](https://i.imgur.com/7IWN1Cr.png)

**Comment by hydronatron** [comment] 2022-11-17 02:45
Able to reproduce this as well - I've deduced the issue to something only going on in the `vscode-typescript-next` extension for highlighting; disabling it seems to fix the issue.

### **Nightly enabled**
![image](https://user-images.githubusercontent.com/28845225/202341893-d0ccedd3-ab35-4a13-bd2c-ff3a72e07f56.png)

### **Nightlydisabled**
![image](https://user-images.githubusercontent.com/28845225/202341873-286dfe18-131c-43c0-ba74-71f459ddfe97.png)

**Comment by Franh01** [comment] 2022-11-17 02:46
> Able to reproduce this as well - I've deduced the issue to something only going on in the `vscode-typescript-next` extension for highlighting; disabling it seems to fix the issue.
> 
> ### **Nightly enabled**
> ![image](https://user-images.githubusercontent.com/28845225/202341893-d0ccedd3-ab35-4a13-bd2c-ff3a72e07f56.png)
> 
> ### **Nightly disabled**
> ![image](https://user-images.githubusercontent.com/28845225/202341873-286dfe18-131c-43c0-ba74-71f459ddfe97.png)

True, just tried the same and also solve the problem, thanks a lot!

**Comment by Nicolerobinn** [comment] 2022-11-17 02:48
me too

**Comment by bagaskarala** [comment] 2022-11-17 02:55
extension `JavaScript and TypeScript Nightly` v5.0.20221116 have bug in syntax highlighting, solution: 
- downgrade extension to v5.0.20221115
- or, you can disable/uninstall `JavaScript and TypeScript Nightly` and let vscode use built in TS version

**Comment by vtdkhoa** [comment] 2022-11-17 04:54
Same.
OS: Ubuntu 20.04 (Linux x64)
Version: 1.72.2
I did downgrade from 1.73.1 to 1.72.2 and it's still the s
![image](https://user-images.githubusercontent.com/28914274/202359399-7916c247-a7ab-4d13-ae3b-12a626762d85.png)

**Comment by Manybin** [comment] 2022-11-17 06:39
me too

**Comment by aeschli** [comment] 2022-11-17 08:50
Duplicate of https://github.com/microsoft/vscode-typescript-next/issues/43
@mjbvz FYI

**Closed by aeschli** 2022-11-17 08:50 UTC
Labels: font-rendering, triage-needed

**Comment by lutinmaviou** [comment] 2022-11-17 18:03
I had the same issue, thank you very much for the help ;)
I have updated the **JavaScript and Typescript Nightly** extension, problem fixed!
