### ISSUE TITLE
Editor stuck

### ISSUE THREAD

**Issue by lizhijian520** [Microsoft/vscode#63123] opened 2018-11-14 11:43 UTC
Issue Type: <b>Bug</b>

When you've written code or switched other TAB pages or two or three vscode, you're stuck

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.95GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.1.0
mpvue-snippets|ban|1.2.1
path-intellisense|chr|1.4.2
vscode-filesize|mkx|2.1.1
vscode-language-pack-zh-hans|MS-|1.29.2
vetur|oct|0.13.0
seti-icons|qin|0.1.3
view-in-browser|qin|0.0.5
minapp-vscode|qiu|1.9.2
vscode-icons|rob|7.28.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment] 2018-11-14 14:03
/duplicate of https://github.com/Microsoft/vscode/issues/62970

**Closed** 2018-11-14 14:03 UTC
Labels: *duplicate, new release
