### ISSUE TITLE
File  Deleted when i copy and paste file from vs code explorer

### ISSUE THREAD

**Issue by deepakgd** [microsoft/vscode#84652] opened 2019-11-13 05:39 UTC
- VSCode Version: 1.40.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open project folder by `code .` in terminal
2. In VS code file Explorer left side, right click on file and copy
3. Open another project in vs code by `code . `in termial
4. In VS code file explorer on left side, right click and paste 
5. Now actual source file got deleted

**Comment by NizamLZ** [comment] 2019-11-13 11:26
Duplicate of #83335 which cannot be reproduced.

**Closed** 2019-11-14 17:02 UTC
Labels: *duplicate

**Comment by deepakgd** [comment] 2019-12-19 09:39
I like to reopen this issue because today i faced same issue again. Unable to upload webm format here so please find bug recreate video from google drive as below

[Video link](https://drive.google.com/file/d/1eqSZ8QpYszuRsq-vDSUyFWfTUa3sd7k8/view?usp=sharing
)
