### ISSUE TITLE
Mac OS X :: "Open Folder With" VS Code

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/vscode#1223] opened 2015-12-12 22:22 UTC
Hello,

Since Finder is obviously developed by Apple, I'm not sure if this would be possible or not. Is there any way to right-click a folder in Finder, and "open with VS Code?" You can do this with individual files, but it would be a nice, small workflow enhancement to be able to open a _folder_ with VS Code, directly from Finder, as well. If not, no big deal. This would be a fault with Finder, rather than VS Code.

Here's a screenshot of right-clicking a folder ... there's no "Open With" option. Maybe the **Share** option could work somehow?

<img width="367" alt="screen shot 2015-12-12 at 3 20 03 pm" src="https://cloud.githubusercontent.com/assets/466713/11764203/1e1419d4-a0e4-11e5-814e-c2a201c90ef6.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by takumif** [comment] 2015-12-13 03:14
![screen shot 2015-12-12 at 10 10 05 pm](https://cloud.githubusercontent.com/assets/5505433/11765250/352e78f6-a11d-11e5-92fb-6a78cc55487b.png)

You can open a folder by drag-and-dropping it on the VSCode icon on the dock. I personally don't like apps that clutter the right click menu.

**Comment by egamma** [comment] 2015-12-14 08:39
@joaomoreno fyi.

**Comment by joaomoreno** [comment] 2015-12-14 09:27
I love @takumif's suggestion, this is also our recommendation.

**Comment by bansalvks** [comment] 2016-05-20 07:14
I am from windows environment and VS Code provides the same option there. I do not know why the hell it is doing discrimination with osx and not providing the same here.

it is not impossible and we need it

**Comment by joaomoreno** [comment] 2016-05-24 06:51
Simply because this is not common behaviour in OS X.

[You are free to create a global Service which does this for you](http://www.hongkiat.com/blog/customize-mac-right-click-menu/).

**Comment by rocketspacer** [comment] 2017-03-12 19:39
SourceTree did it, can't really define it as uncommon behavior  
![image](https://cloud.githubusercontent.com/assets/17026876/23835225/2ca9ea72-0796-11e7-8b06-3c21f985970a.png)

**Comment by dfblackburn** [comment] 2017-03-23 14:10
I work in both Windows and OSX (often on the same project), and I would also like to have this behavior. 
Just like some people don't like apps cluttering up the right click menu, I don't like apps cluttering up my dock (which does not include VS Code right now).
It is pretty easy to disable the shortcut in the Keyboard preferences, so I do not see a lot of negative impact to having it.

**Comment by rocketspacer** [comment] 2017-03-23 17:00
Sure, we could totally create a global Service... but why don't we have it built-in? Quite a reasonable request, Atlassian Source Tree did it :D You can't really describe it as uncommon behavior

**Comment by joaomoreno** [comment] 2017-03-23 17:27
@rocketspacer Care to contribute a PR which adds a Service?

**Comment by rocketspacer** [comment] 2017-03-23 18:08
I know it's not nice to just ask you to do stuffs but I'm not really doing desktop development or electron. :D I've done some research and found some leads on how to do it in Objective-C, doesn't sure how it works in electron though
http://stackoverflow.com/questions/3732142/writing-a-snow-leopard-service-for-finder-app

**Comment by rocketspacer** [comment] 2017-03-23 18:11
I've confirmed that Atlassian wrote Source Tree natively for each OS (C# for Windows, Objective-C for OSX)

**Comment by JReinhold** [comment] 2017-04-15 17:31
I made the service myself in 2 minutes. It seems like all we need is to, is add a prebuilt .workflow folder with files to the `~/Library/Services/` folder, and we should be good to go.

However, I'm not sure how to achieve this automatically when installing VS Code. Maybe we can create a command, that the users can choose to run at any time if they like? Or we can run it on firstRun of VS Code.

any thoughts @joaomoreno ?

**Comment by joaomoreno** [comment] 2017-04-18 07:23
Having a command in the Command Palette which installs this for the user would be nice.

**Comment by JReinhold** [comment] 2017-04-20 08:38
Okay, I'll try to start work on it soon.

**Comment by dansiegel** [comment] 2017-04-20 19:37
> Or we can run it on firstRun of VS Code.

If it only does this on the first run, users who already have VS Code installed would have to know both, that the option exists, and how to get the command onto the command palette. To be honest most of us deal with so many updates, we probably aren't paying very close attention to the release notes. So I might suggest that if we have to manually do something to enable this, that there is some thought into making sure we know the feature is there and what to do.

**Comment by JReinhold** [comment] 2017-04-23 08:24
> So I might suggest that if we have to manually do something to enable this, that there is some thought into making sure we know the feature is there and what to do.

We could create a dialog with something like "would you like to enable the 'Open in VSCode' context menu?", and save wether or not the user has been presented with this dialog before. Then, on new installs, the dialog would appear on firstRun, because the user has never seen it. And users that update would see it once when they have updated, because they have never seen it before either.

I would need some guidance though, on how and where to save this `macOSContextHasPrompted` state. I can only think of doing it like a userSetting, but that would be a really bad idea for multiple reasons. There must be some way to internally save stuff like this.

**Comment by mix3d** [comment] 2017-05-04 20:58
+1 for the feature :)

**Comment by JReinhold** [comment] 2017-05-13 20:22
I can't seem to find the time to implement this, so if anyone wants to give it a try, please do. All that have to be done is to copy the content of 
[this zip file](https://github.com/Microsoft/vscode/files/998921/Open.in.VS.Code.workflow.zip) into the folder: `~/Library/Services` (the zip-file contains a folder called `Open in VS Code.workflow`

(this doesn't mean I've given up, just that I don't know when I will have time to get around to it.)

**Comment by csujedihy** [comment] 2017-05-29 02:12
@JReinhold It works.

**Comment by thewinger** [comment] 2017-10-16 08:54
I have found this app that really helps with this issue

https://github.com/sozercan/OpenInCode

**Comment by sebfindling** [comment] 2018-08-06 14:58
@thewinger freaking awesome <3 this is exactly what we needed, if only Microsoft gave more crap about MacOS users instead of having @joaomoreno 's attitude to us, it would be a better place.

**Comment by RoadToDream** [comment] 2018-08-25 11:12
<img width="204" alt="screen shot 2018-08-25 at 19 11 38" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
Just made one and will pull a request some day... after my exams

**Comment by RoadToDream** [comment] 2018-08-26 09:31
@csujedihy @thewinger @jd-carroll @sebolio Just build one tested on 10.13, maybe have a try will eliminate several bugs after exams. 
[SzContext.app.zip](https://github.com/Microsoft/vscode/files/2321398/SzContext.app.zip)

**Comment by jd-carroll** [comment] 2018-08-26 20:07
@RoadToDream - Can you send a link to the source for this / future PR?  I would be interested in seeing how this all works

(Good luck on your exams)

**Comment by RoadToDream** [comment] 2018-08-27 00:42
Will open a repo but after made it a more versatile and complete project.

**Comment by lukekhamilton** [comment] 2018-10-01 03:33
Any updates on this one?

**Comment by rdytogokev** [comment] 2019-01-23 21:21
I found this github repo:
https://github.com/Sankra/OpenFolderInVSCode

**Comment by GeeLaw** [comment] 2019-02-27 09:38
The Quick Actions context menu workflow is just "Run Shell Script" receiving "files or folders" in "Finder":

```bash
for f in "$@"
do
	/usr/local/bin/code "$f"
done
```

I'm no expert in creating installation program for VS Code that installs this. Help yourself.

**Note** A caveat is that the option doesn't appear when you open the context menu on the background of (**blank space inside**) a folder. It seems to me that **OneDrive is able to add items to that context menu**, consult them to find out how to add "Open with Code" there -- I don't think you can drag & drop the background of a folder (nor the folder's tab) to the Code icon.

**Comment by sebolio** [comment] 2019-04-01 22:32
> I have found this app that really helps with this issue
> 
> https://github.com/sozercan/OpenInCode

you're the real MVP

**Comment by xgqfrms** [comment] 2019-05-26 13:15
# solutions

1. https://github.com/Sankra/OpenFolderInVSCode

2. https://www.jimbobbennett.io/open-anything-in-vs-code-using-a-macos-quick-action/

**Comment by cv-minhtranhoang** [comment] 2019-07-09 08:27
> I can't seem to find the time to implement this, so if anyone wants to give it a try, please do. All that have to be done is to copy the content of
> [this zip file](https://github.com/Microsoft/vscode/files/998921/Open.in.VS.Code.workflow.zip) into the folder: `~/Library/Services` (the zip-file contains a folder called `Open in VS Code.workflow`

Thanks a lot, it's worked for me

**Comment by benbendemo** [comment] 2020-02-28 00:07
> I can't seem to find the time to implement this, so if anyone wants to give it a try, please do. All that have to be done is to copy the content of
> [this zip file](https://github.com/Microsoft/vscode/files/998921/Open.in.VS.Code.workflow.zip) into the folder: `~/Library/Services` (the zip-file contains a folder called `Open in VS Code.workflow`

Thanks a lot, it works on my macOS

**Comment by furkankesgin** [comment] 2020-07-26 16:51
> <img alt="screen shot 2018-08-25 at 19 11 38" width="204" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
> 
> Just made one and will pull a request some day... after my exams

@RoadToDream That's what I want it, really I love it, there has been a long time if you're here, is it possible to share the link? 
I always show making as services, but I want to do like your style.

**Comment by skarchmit** [comment] 2020-08-02 02:25
> > <img alt="screen shot 2018-08-25 at 19 11 38" width="204" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
> > Just made one and will pull a request some day... after my exams
> 
> @RoadToDream That's what I want it, really I love it, there has been a long time if you're here, is it possible to share the link?
> I always show making as services, but I want to do like your style.

How did you delete all the other things from your right click?

**Comment by RoadToDream** [comment] 2020-12-06 04:37
> > <img alt="screen shot 2018-08-25 at 19 11 38" width="204" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
> > Just made one and will pull a request some day... after my exams
> 
> @RoadToDream That's what I want it, really I love it, there has been a long time if you're here, is it possible to share the link?
> I always show making as services, but I want to do like your style.

Hi furkankesgin, I believe that the way VS code compile does not fit an easy fix. If you still prefer my way, you may use the one built by my self. After move the app to Application folder and open it, the System Preference will pops up, please check the finder extension for SzContext. 
[SzContext.zip](https://github.com/microsoft/vscode/files/5648298/SzContext.zip)

**Comment by KerimG** [comment] 2020-12-11 11:52
> <img alt="screen shot 2018-08-25 at 19 11 38" width="204" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
> 
> Just made one and will pull a request some day... after my exams

This is an infinitely better solution than the Service one. @RoadToDream  why do you think this cannot be added to VSC? If you need help with it, I could take a look.

**Comment by RoadToDream** [comment] 2020-12-12 23:26
> > <img alt="screen shot 2018-08-25 at 19 11 38" width="204" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
> > Just made one and will pull a request some day... after my exams
> 
> This is an infinitely better solution than the Service one. @RoadToDream why do you think this cannot be added to VSC? If you need help with it, I could take a look.

I would love to push that into the repo if you would like to help! As I am not very familiar with the building process of VSCode. From my perspective, the build process should be something like:
1. download compiled version of electron
2. compile typescript and move it into the compiled electron
Is my understanding correct? 
To have the dropdown menu enabled as a Finder extension, we need to have a service running in the background. So there should be two items: service and extension, included in the package. After checking the documentation of electron and yarn, I didn't found anything very useful. It would be a great help if you can help to integrate it into VSCode. 
For now, I would like to provide a very simple implementation. 
https://github.com/RoadToDream/SzContext

**Comment by RoadToDream** [comment] 2020-12-12 23:34
> > <img alt="screen shot 2018-08-25 at 19 11 38" width="204" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
> 
> > 
> 
> > Just made one and will pull a request some day... after my exams
> 
> 
> 
> @RoadToDream That's what I want it, really I love it, there has been a long time if you're here, is it possible to share the link? 
> 
> I always show making as services, but I want to do like your style.

I know it's been a long time. But if you are still interested, go check the link 

https://github.com/RoadToDream/SzContext

**Comment by RoadToDream** [comment] 2020-12-12 23:34
> @RoadToDream - Can you send a link to the source for this / future PR?  I would be interested in seeing how this all works
> 
> 
> 
> (Good luck on your exams)

I know it's been a long time, but if you are still interested, go check the link. 

https://github.com/RoadToDream/SzContext

**Comment by furkankesgin** [comment] 2020-12-12 23:57
> > > <img alt="screen shot 2018-08-25 at 19 11 38" width="204" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
> > > Just made one and will pull a request some day... after my exams
> > 
> > 
> > @RoadToDream That's what I want it, really I love it, there has been a long time if you're here, is it possible to share the link?
> > I always show making as services, but I want to do like your style.
> 
> Hi furkankesgin, I believe that the way VS code compile does not fit an easy fix. If you still prefer my way, you may use the one built by my self. After move the app to Application folder and open it, the System Preference will pops up, please check the finder extension for SzContext.
> [SzContext.zip](https://github.com/microsoft/vscode/files/5648298/SzContext.zip)

Thank you so much for your help. I installed your app and I will share this with my friends. Because I know many people need this who came from windows machines.

**Comment by RoadToDream** [comment] 2020-12-13 00:53
> > > > <img alt="screen shot 2018-08-25 at 19 11 38" width="204" src="https://user-images.githubusercontent.com/8088354/44617725-ba5eb900-a89a-11e8-9093-170bcaff1e49.png">
> 
> > > > Just made one and will pull a request some day... after my exams
> 
> > > 
> 
> > > 
> 
> > > @RoadToDream That's what I want it, really I love it, there has been a long time if you're here, is it possible to share the link?
> 
> > > I always show making as services, but I want to do like your style.
> 
> > 
> 
> > Hi furkankesgin, I believe that the way VS code compile does not fit an easy fix. If you still prefer my way, you may use the one built by my self. After move the app to Application folder and open it, the System Preference will pops up, please check the finder extension for SzContext.
> 
> > [SzContext.zip](https://github.com/microsoft/vscode/files/5648298/SzContext.zip)
> 
> 
> 
> Thank you so much for your help. I installed your app and I will share this with my friends. Because I know many people need this who came from windows machines.

Really happy to see it helps. Enjoy.

**Comment by RoadToDream** [comment] 2020-12-13 20:30
> I love @takumif's suggestion, this is also our recommendation.
> 

￼I would like to provide a commit to add finder context menu, but I think it will not pass pre-submission check as it will include Xcode project. May I ask if there is a way to add such contents?

**Comment by reslear** [comment] 2020-12-27 15:42
@RoadToDream SzContext in bigsur have lags when open context menu

**Comment by RoadToDream** [comment] 2020-12-28 00:03
> @RoadToDream SzContext in bigsur have lags when open context menu

Hi reslear, issue has been fixed, thanks for reporting. Check it at [v0.4](https://github.com/RoadToDream/SzContext/releases/download/0.4/SzContext.dmg). (May need to relaunch Finder to let it work properly)
Also I would suggest to report issue in SzContext repo, I am afraid it is not proper to discussing issues of other projects in this thread.

**Comment by RoadToDream** [comment] 2021-01-13 02:30
We all love VS Code, it provides us a tremendous experience of development. For me, and I believe for many others, the only missing function on macOS is "Open with VS Code". 

I could say we now have a perfect solution to that issue if you don't mind installing a tiny app. Please go check 

https://apps.apple.com/us/app/szcontext/id1547864620?mt=12

App is on AppStore so it's totally sandboxed, no worries about it may ruin your files. Also more importantly, app will totally be free. @

![image](https://user-images.githubusercontent.com/8088354/104394387-613f6080-54fb-11eb-9ab5-d216e71eac01.png)

**Comment by commonpike** [comment] 2021-04-15 08:12
> The Quick Actions context menu workflow is just "Run Shell Script" receiving "files or folders" in "Finder":
> 
> ```shell
> exec /bin/bash --login -c 'for f in "$@"; do /usr/local/bin/code "$f"; done' dummy.sh "$@"
> ```
> 

This article 
https://www.jimbobbennett.io/open-anything-in-vs-code-using-a-macos-quick-action/
uses 

```
open -n -b "com.microsoft.VSCode" --args "$*" 
```

and works really nice - no bash needed

**Comment by taronling** [comment] 2021-12-25 01:19
> 

This is exactly what I was looking for + more. Thanks!

**Comment by 00rain00** [comment] 2022-05-31 03:09
Problem solved, thanks all.

**Comment by joaomoreno** [comment] 2022-12-09 10:26
Closing due to an existing solution.

**Closed by joaomoreno** 2022-12-09 10:26 UTC
Labels: feature-request, install-update, macos, workbench-os-integration
