### ISSUE TITLE
emmet not working

### ISSUE THREAD

**Issue by codehobbyist06** [microsoft/vscode#137350] opened 2021-11-17 08:57 UTC
Issue Type: <b>Bug</b>

1. Open VSCode
2. Create a react project using 'npx create-react-app app_name'.
3. While working on a react functional component, I am not able to use emmet abbreviations for jsx.
4. I have added this line to settings.json
  "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    }

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-6310 APU with AMD Radeon R4 Graphics     (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.46GB (0.73GB free)|
|Process Argv|--crash-reporter-id 02b7f44b-389c-41eb-960c-c4c8cdd0a5e4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.0.0
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378
vscexrecpromptt2:30400062

```

</details>

**Comment by rzhao271** [comment] 2021-11-17 16:15
Duplicate of https://github.com/microsoft/vscode/issues/137012

**Closed** 2021-11-17 16:16 UTC
Labels: *duplicate
