### ISSUE TITLE
Prompt to reopen and save file in admin mode on save of protected file

### ISSUE THREAD

**Issue by lanierhall** [Microsoft/vscode#31621] opened 2017-07-28 05:56 UTC
When attempting to save a file in Windows while not in administrator mode where the file is [protected|read-only|system] pops up a message that the save failed with options like save-as, retry, cancel.  
Add an option to restart visual studio code in admin mode and save.

Try this in notepad++ for an example.

**Comment by jontro** [comment] 2017-08-24 20:59
See #1614

**Comment by Tyriar** [comment] 2017-08-30 17:51
Thanks @jontro 

Duplicate of #1614

**Closed** 2017-08-30 17:51 UTC
Labels: duplicate, explorer-files, feature-request, windows
