### ISSUE TITLE
GitHub authentication not prompting sign in

### ISSUE THREAD

**Issue by beauxq** [microsoft/vscode#137282] opened 2021-11-16 06:03 UTC
Issue Type: <b>Bug</b>

This page
https://code.visualstudio.com/docs/editor/github
says this:
> When you do something that requires GitHub authentication, you'll see a prompt to sign in

I am doing something that requires GitHub authentication, and I am not seeing any prompt to sign in.
I'm just seeing:

> fatal: Authentication failed for 'https://github.com/username/reponame.git/'

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.4.0-90-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.60GB (0.83GB free)|
|Process Argv|--unity-launch --crash-reporter-id e5a759f8-56e2-4ef2-8056-76b15f14ce2e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
language-gas-x86|bas|0.0.2
vscode-eslint|dba|2.2.2
vscode-wasm|dts|1.3.1
go|gol|0.29.0
rest-client|hum|0.24.5
sublime-babel-vscode|jos|0.2.10
mypy|mat|0.2.1
asm-code-lens|maz|1.8.3
git-graph|mhu|1.30.0
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vetur|oct|0.35.0
ruby|reb|0.28.1
LiveServer|rit|5.6.1
code-spell-checker|str|2.0.12
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-16 06:12
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Closed** 2021-11-16 06:12 UTC
Labels: *duplicate, new release
