### ISSUE TITLE
Allow pin/star folders and pages on welcome screen

### ISSUE THREAD

**Issue by ishashankkawle** [microsoft/vscode#221805] opened 2024-07-16 13:03 UTC
- As part of this feature I would like to have ability to star a folder on my welcome screen of VSCode.
- Also It would be better if I can see list of my starred folders and pages.
- Also I would like to have ability to remove pin/star from any page or folder from welcome screen of VSCode.

**Comment by bhavyaus** [comment] 2024-07-25 18:43
dupe of https://github.com/microsoft/vscode/issues/63057

**Closed by bhavyaus** 2024-07-25 18:43 UTC
