### ISSUE TITLE
Explorer: Provide a setting so that only double click opens a file in the editor or expands a folder

### ISSUE THREAD

**Issue by ivalexa** [Microsoft/vscode#9388] opened 2016-07-16 14:48 UTC
- VSCode Version:1.3.1
- OS Version:  Win 10

Feature , double click to open a file.
Is it possible to add feature in order to force vscode to open file only by double clicking on it,  single click should only select a file in explorer ?
This can be very useful when there is a lot of files and you looking the exact one in explorer.

**Comment by brunnopleffken** [comment] 2016-07-16 16:20
I'm using VS Code 1.4.0 Insider, but I think v1.3.1 behaves the same way: single-click just to select and preview the file; double-click already open it.

**Comment by qwert789** [comment] 2016-07-16 16:44
@brunnopleffken thnx, but i want to disable preview , otherwise there is no reason for double click

**Comment by bgse** [comment] 2016-07-16 22:02
@qwert789 The 'preview' function does not keep the file open when you preview or open another file in the same editor stack (unless you edit the previewed file, which makes the file opened).

Not sure what you are going for here, why would you actually (left-)click the file if you do not intend to do anything with it?

**Comment by payonel** [comment] 2016-07-21 04:55
I also am trying to figure out how to do this

Why? because I want the explorer panel to have focus, I might then use the arrow keys to scroll up and down in the list of files for me. I realize the pane takes focus on mouse-enter, which honestly, is a bit weird to me.

Why else? I was hoping I could type the name of a file and it's scroll to the next file it found starting with that letter. Unfortunately, even with KB focus in the explorer window it doesn't do this.

Why else? I don't like it adding files to the "OPEN EDITORS" group while I'm still selecting/scrolling for the file I want. I want [enter] or [double click] to open the file. With preview disabled, it should still require double click to open the file (imo) -- this is how it worked in vs 2012-2013

**Comment by iamsunny** [comment] 2016-08-23 04:17
I'm also having this trouble. Most of the time I want to drag and drop files into the editor from the explorer bar. As soon I select a file to drag, it opens it in preview mode and I lose the focus of the current editing file in editor.

**Comment by azizsaboor** [comment] 2016-10-31 04:31
Yes. I really dislike this "feature" of VS Code. I want to disable automatic previewing of any file just because I have single-clicked it. I would much rather double-click to open only. How do we achieve this?

**Comment by waynebloss** [comment] 2016-11-09 17:37
I hate the "Preview Tab" feature of the full Visual Studio and I hate it in VSCode too.

Has anyone found a way to turn this off yet?

**Comment by waynebloss** [comment] 2016-11-11 18:21
I found a really klunky workaround - if you right-click the Explorer pane and then hit `Esc` to hide the menu, the Explorer pane retains focus and then you can use the keyboard to navigate your folder.

**Comment by bgse** [comment] 2016-11-11 23:14
@waynebloss You can also use the shortcut (Ctrl+Shift+E) to switch focus to explorer, or if you really want to use the mouse, you can middle-click and prevent the right-click menu that way.

**Comment by waynebloss** [comment] 2016-11-11 23:38
@bgse when I tried that earlier today it opened the file that received focus in the explorer tree immediately.

**Comment by finalclass** [comment] 2016-11-25 08:30
This preview feature indeed is super annoying. Please provide a way to disable it or some guidance on how to change it manually in the code.

**Comment by sp4ceman** [comment] 2016-12-02 08:11
nthing the calls for this. i single click to get into the explorer tree to use my mouse wheel to scroll up or down. i dont want it to do anything, i dont want to flash another window i just want to scroll up or down without losing where i am in my file. normally do this a lot when triple checking paths etc.

**Comment by bgse** [comment] 2016-12-02 10:33
@sp4ceman No offense meant, guess coming from different platforms makes for different habits and expectations.

As for clicking the explorer tree for scroll wheel usage, you don't actually have to do that, it is sufficient to just hover the cursor over the explorer tree, and then you can start using the wheel without clicking first.

Maybe there is some hacky-whacky way to get rid of preview mode via extension for now, might look into it a bit over the weekend.

**Comment by payonel** [comment] 2016-12-02 22:08
@bgse but for me the issue is that I like to pgup/pgdown in a file tree to quickly look in other folders. My projects have many files and many folders maintained by many other devs, so it is not infrequent that I don't know yet what I'm looking for. Or to use the left arrow key to close the collapse the current folder, and down/up arrow to adjacent folders and right arrow to open one and look again. Scrolling with the mouse can be somewhat slow when I'm trying to view a large range.

**Comment by giangcoi48k** [comment] 2016-12-20 04:30
I've just updated to the latest version 1.8.1 this morning, and it seems that micorosoft are not determined this additional option. I am really disappointed, I really hate the preview feature horribly. I have to consider switching to another ide

**Comment by bpasero** [comment] 2017-01-04 10:09
Updated the summary: such a setting should also control that a folder only expands on double click.

**Comment by hpcsc** [comment] 2017-01-05 08:38
@qwert789 and other interested people: i'm working on a pull request to implement this feature. Do you expect this behaviour (single click to highlight, double click to open/toggle) everywhere else like search results, git changes, extensions, etc? Or you just want it for the explorer?

**Comment by finalclass** [comment] 2017-01-05 08:42
Wow, that's a great news. IMO it should be only implemented in the explorer.

**Comment by hpcsc** [comment] 2017-01-05 14:04
@finalclass to be clear, in explorer section, there are "Open Editors" pane and "Explorer" pane. I assume you are only referring to "Explorer" pane?

I'll wait 1-2 days to see any other opinion

**Comment by finalclass** [comment] 2017-01-05 15:25
I don't use "Open Editors" at all, I keep it closed all the time so I can't say how it should work there.

**Comment by payonel** [comment] 2017-01-05 15:51
I think the behavior should be the same in all panes of the explorer section, "open editors" and "explorer". to me this is a change in behavior of clicking on the filenames, and it should differ just because i clicked on a filename a few nodes higher in the same "viewport". Either way, this change is a welcome update and I appreciate your work on this for us. Thank you!

**Comment by benedictleejh** [comment] 2017-01-05 18:17
IMO I would expect this behaviour everywhere else as well, not just the explorer, so that it behaves consistently.

**Comment by qwert789** [comment] 2017-01-05 18:27
Awesome news, I believe that explorer pane is the most important place, but it would be really nice to add this behavior in all places for consistency.
Thanks man :)

**Comment by payonel** [comment] 2017-01-05 18:42
@benedictleejh i hate typos the reverse meaning, but it appears you understood my intent perfectly, I typoed "should differ" where it should have said "shoudn't differ", basically, let's make it consistent. I think that's what you read from my comment, thankfully.

**Comment by hpcsc** [comment] 2017-01-06 02:49
seem like most people agree on making it consistent and applying this behaviour to all other places

if so, here are the places that I can think of to modify, let me know if I miss out any place:

1. Explorer tab - **Open Editors** pane
2. Explorer tab - **Explorer** pane
<img width="534" alt="vscode - explorer" src="https://cloud.githubusercontent.com/assets/5293047/21705684/6717a398-d3fc-11e6-8f1e-aa5ddd7c50af.png">

3. Search tab - **Search result** pane
<img width="680" alt="vscode - search result" src="https://cloud.githubusercontent.com/assets/5293047/21705732/a1dbf79a-d3fc-11e6-8c95-a8f2a8db14e4.png">

4. Git tab - **Changes** pane
<img width="606" alt="vscode - git" src="https://cloud.githubusercontent.com/assets/5293047/21705755/c5f9a76c-d3fc-11e6-9715-dc3fea1ae8ba.png">

5. Debugger tab - **Variables** pane
6. Debugger tab - **Watch** pane
7. Debugger tab - **Callstack** pane
8. Debugger tab - **Breakpoint** pane
<img width="778" alt="vscode - debugger" src="https://cloud.githubusercontent.com/assets/5293047/21705765/da78fc56-d3fc-11e6-8f19-18ca7987a72c.png">

9. Extensions tab
<img width="786" alt="vscode - extensions" src="https://cloud.githubusercontent.com/assets/5293047/21705791/109d76fe-d3fd-11e6-9393-f19ae8267c88.png">

**Comment by bpasero** [comment] 2017-01-06 06:20
@hpcsc there is also the "Problems" view where this applies. 

+1 for changing this everywhere. Please also keep in mind that I think collapse/expand should only work on double click.

The easiest to find all places where a tree is used might be to just check for references to the `Tree` widget everywhere.

**Comment by hpcsc** [comment] 2017-01-06 06:28
@bpasero 
I updated with 2 more places:
10. **Find All References** result
11. **Problems** view

Do you mean collapse/expand should apply in all cases, doesn't matter the `openOnSelect` setting is on or off?

I have found most of places, however still have some doubts. Will post the question in the pull request. Thanks for your help

**Comment by bpasero** [comment] 2017-01-06 06:38
My feeling is that this setting should be named in a way that it makes more clear what it does: when enabled, a single click on a tree node is doing only selection, but neither open nor expand/collapse. Only a double click invokes the default action on a tree node (which is toggle expand/collapse for a node with children and opening otherwise).

**Comment by bpasero** [comment] 2017-01-06 06:39
Btw interesting to see and learn how e.g. Eclipse does it:

![image](https://cloud.githubusercontent.com/assets/900690/21709680/4bf45c28-d3e3-11e6-9463-d577e9e0131c.png)

**Comment by R3V07T** [comment] 2017-01-06 06:43
N30

**Comment by hpcsc** [comment] 2017-01-06 06:43
Good idea, I can rename it to `workbench.openMode` with 2 values: `singleClick` or `doubleClick`
I put it under `workbench` since now it's applicable to everywhere, not just the sidebar

**Comment by bpasero** [comment] 2017-01-06 07:00
Sounds good.

**Comment by pantonis** [comment] 2017-04-06 14:33
Any news on this irritating single click preview mode?

**Comment by bpasero** [comment] 2017-04-06 16:35
Sorry, didn't have much time to look into this again. As it stands right now we need to clean up some debt first in the area of tree usage throughout our code before we can ask for a PR again.

**Comment by aight8** [comment] 2017-04-25 21:10
There are many reasons for this - I don't mentioned it so much because I accepted it - but good this issue exists.
If I just want to "select" a folder to execute an action on it (currently it toggle the folder also this is annoying)
If you just want to "select" a file to execute an action it it (currently it opens a preview, this is irritates)

Als alternative, a little bit hidden solution, I just want to mention that it could differ where you click the filesystem entry. For example if clicking the icon or the space before it could be just a select, if click the file name or the space after it it stays with the current behaviour. Of course this would be the best of both worlds but I understand if you are not ready for experiments like this.

**Comment by ShayBox** [comment] 2017-08-10 13:07
Any news on this? I would like it

**Comment by R3V07T** [comment] 2017-08-16 18:24
???

**Comment by dinhtuan1991vt** [comment] 2017-08-17 07:06
waiting for this.

**Comment by finalclass** [comment] 2017-08-17 07:36
yeah, me too. The way clicking works on explorer now is just too annoying and overshadows the goodies that are included in vscode.

**Comment by isaaceliape** [comment] 2017-08-17 19:08
To solve this problem I make this change on default settings:
`"workbench.editor.enablePreview": false,`

**Comment by ShayBox** [comment] 2017-08-17 19:10
That doesn't fix this, that makes it so when you single click on a file it doesn't open as a temporary file, but as a permanent file, it does not change the single click to open to a double click.

**Comment by chriscarpenter12** [comment] 2017-08-22 15:22
@ShayBox I agree. This was unexpected behavior when I first opened the editor. I was surprised that I couldn't find a setting to disable the single click. 😞

**Comment by superTechnologist** [comment] 2017-08-28 03:34
there is no way to disable single click preview. it is very annoying.

**Comment by leonardocfwd** [comment] 2017-08-29 07:42
Oh man... this thing is really annoying!!!! Please just include some new property where a developer can disable/enable it

**Comment by qn0361** [comment] 2017-08-29 11:12
Annoying as hell indeed.

**Comment by gibbok** [comment] 2017-09-26 07:40
Annoying indeed, let's add an option in preferences.

**Comment by englandschorsch** [comment] 2017-09-29 09:36
The single-click folder expand/collapse is the most annoying thing about VS Code, which is otherwise a brilliant editor. Please add an option in the preferences for this.

**Comment by ocboogie** [comment] 2017-10-05 03:51
At least give us the option... plz

**Comment by 2289034325** [comment] 2017-10-11 08:23
"workbench.editor.enablePreview": false,
"workbench.editor.enablePreviewFromQuickOpen": false
这两个设置并不能解决问题，浪费了老子好长时间

                  __
                //_/| 
               /—-/ 
              /—-/ 
             /—-/ 
            /—-/ 
           /—-/ 
        /´¯/'--'/´¯`·_ 
      /'/--/—-/—--/¨\ 
     ('(———- ¯~/'--') 
      \————-'—--/ 
      '\'————_-·´
        \———--  /
         \———--

**Comment by ShayBox** [comment] 2017-10-11 08:26
@2289034325 That's not what we're talking about.

**Comment by ShayBox** [comment] 2017-10-14 09:42
In Case you mis understood the above comment like I did, it is actually giving a middle finger to the fact that the above options doesn't fix the problem.
"These two settings do not solve the problem, wasting my mother for a long time" - Google translate

**Comment by Talv** [comment] 2017-10-15 01:06
It doesn't change the fact that his comment is worthless, like most of others who just bump the thread for no reason - by repeating something that have already been said.
Please, use *Reactions* - add +1 on the main post, and move on if you don't have anything relevant to say.

**Comment by shengsheng** [comment] 2017-10-20 09:38
Any news? 
Please provider a "double click" model.

**Comment by Montago** [comment] 2017-10-23 14:16
i want to doubleclick to open ... please make it so !

**Comment by technoiswatchingyou** [comment] 2017-10-26 01:18
Doubleclick for file opening +1

**Comment by mybios** [comment] 2017-10-27 08:26
Doubleclick for file opening +1
 👎 1

**Comment by giangcoi48k** [comment] 2017-11-18 07:29
Any news?
Please provider a "double click to open file" model. I expected the annual year that this feature is not yet appearing

**Comment by psicofrenia** [comment] 2017-12-05 09:35
Doubleclick for file opening +1

The single-click preview makes bad the best editor around

**Comment by eliziersr** [comment] 2017-12-06 18:04
Doubleclick for file opening and folder expand !

**Comment by dianne21** [comment] 2017-12-08 18:24
I find this very annoying myself too! I'm wanted to use VS for my new projects, but this 'feature' makes me hate it instead..

**Comment by jucrouzet** [comment] 2017-12-15 20:18
Same here, pretty annoying lack of feature ...

**Comment by simeyla** [comment] 2018-01-01 22:06
UGH. Happy New Year and another year of single clicking.

I use a Wacom pen with one button set to double click and I'm so used to doing this in Visual Studio that now I'm working with VSCode I end up opening and closing a folder instead of opening it. Super annoying when switching between IDEs. With single click it just feels much more 'fragile' somehow - like I'm going to break it. I know that doesn't make total sense but it's how it feels.

**Comment by ryancdotnet** [comment] 2018-01-11 04:21
Please create a setting for this. How can so much be configurable in VSCode, yet this simple setting does not exist? There is no reason for it. If a developer prefers to single-click or double-click, so be it. Neither option should be forced across the board, especially for as configurable as VSCode is.
Disclaimer: VSCode is still amazing. :)

**Comment by KangZiRu** [comment] 2018-01-15 13:11
Is there any extension to fix this problem? I'm unable to find anything as this far.

**Comment by ponylin1985** [comment] 2018-01-22 04:54
I hate VS Code PreView....
I don't want this fucking PreView!!!! I want to double-click to open a new tab..............
DO NOT copy the style from Sublime, Atom or any else..................

**Comment by fractalf** [comment] 2018-01-23 08:34
Why would you click on a file if you don't want to do an action? I'm looking for a way to open a file for real (not in preview mode) with just a one click (like default behaviour in earlier Atom verisons). So if anyone fix this, please also allow open file with one click ;)

**Comment by fractalf** [comment] 2018-01-23 08:39
I can't understand why you would want to click on a file if you don't want to actually do something with it?

Now, for those that really has this slight behavior disability (which seems like quite alot of people reading this thread) I do agree that there could be an option for this.

**Comment by finalclass** [comment] 2018-01-23 08:55
@ponylin1985 @fractalf 
Why? Mainly to focus the file. When in windows explorer or mac's finder you click on a file it does not automatically open but it just focuses it. In VSCode it automatically opens in a weird `preview` state. Then when it's opened in this `preview` state and you will not notice that and click on another file to open another file then your first file will automatically close because it has been in this `preview` state. I'm using VSCode for more then a year now and this single issue is still driving me crazy. It's the most annoying thing of VSCode and I can't get use to it no matter how I try. Judging on the number of comments in this topic I see that I'm not alone. 
I understand why someone would like it to work as it is right now thus I think this should be an option. Even better solution would be to provide the ability to write custom plugins that would replace Explorer completely.

VSCode team please give an update on this feature. Will you ever plan to solve it? It has been reported 1.5 years ago and there is still no update on this one;(

**Comment by sp4ceman** [comment] 2018-01-23 09:17
@fractalf i cant scroll the explorer up and down without activating the window. i cant activate the window without clicking on something. normally the something in a file explorer is a file so thats what normally gets clicked on. this is normal windows behaviour. 

previewing what i just clicked on is not normal windows behaviour. nothing in windows behaves this way its non standard and in a year of daily usage of vscode it still feels weird.

**Comment by KangZiRu** [comment] 2018-01-24 08:17
Well, I discovered that the event listener for the explorer is located in TreeView.ts, which is located on the cloud, not local.

The question is:
Is it possible to override the event by writing an extension?

**Comment by luispabon** [comment] 2018-01-26 13:29
It's a bloody annoying feature for sure. `workbench.editor.enablePreview --> false` at least gets rid of the preview feature.

It still opens the file (not as a preview) on its own tab, which is better, but I'd definitely like the option to double click instead so that it matches all my other editors.

**Comment by StanleyGoldman** [comment] 2018-01-29 05:12
I'm finding the default of, "Click a file to preview" and "Click a folder to collapse/expand" really tiring for the very simple operation of copying and pasting files. I click the file I want to copy, it opens in preview, I click the folder I want to paste it in and the over eager expand collapse functionality makes me second guess where I am pasting the file.

Sidebar:
I would actually like to cut and paste files to move them, something that seems supported in most IDEs. But I can't "cut" a file.

**Comment by montapro** [comment] 2018-01-29 11:02
@StanleyGoldman You can move files and folders with drag&drop.

**Comment by finalclass** [comment] 2018-01-29 11:11
@montapro copy paste is more user friendly since sometimes you have a lot of files and directories expanded and you have to scroll a lot to drop the dragged file.

**Comment by montapro** [comment] 2018-01-29 11:15
@finalclass It also my opinion. But it's a way.

**Comment by StanleyGoldman** [comment] 2018-01-29 12:09
Yes, @montapro I think we all realize drag and drop is supported 😅, but it seems every other IDE I use (ahem... like Visual Studio) has gotten me used to such functionality.

**Comment by bpasero** [comment] 2018-01-29 14:03
Added `workbench.list.openMode: singleClick | doubleClick`.

**Closed** 2018-01-29 14:03 UTC
Labels: debt, feature-request, file-explorer, tree

**Comment by Montago** [comment] 2018-01-29 14:25
@bpasero Commit, Release, Ship it !

**Comment by luispabon** [comment] 2018-01-29 14:26
💪

**Comment by leonardosrk** [comment] 2018-01-29 14:35
That's music to my ears!!! Oops, I mean, a collyrium to my eyes!!! xD Looking forward to it! Big thanks @bpasero

**Comment by StanleyGoldman** [comment] 2018-01-29 14:36
Thanks

**Comment by pohybel** [comment] 2018-01-29 18:49
Finally! Thank you! When it will be released?

**Comment by citycide** [comment] 2018-01-29 18:54
@pohybel 

> bpasero (Benjamin Pasero) added this to the January 2018 milestone 5 hours ago

**Comment by sp4ceman** [comment] 2018-01-30 08:30
thank you!

**Comment by bpasero** [comment] 2018-01-30 09:16
This will be in todays insider build to try out. You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tvvignesh** [comment] 2018-01-31 11:39
@bpasero Just tried it out in the insiders build. While it works great, there is an issue. 
The tree in the explorer must be expandable in single click and the file should be opened by double click. Right now, we need to double click even for opening tree in the explorer which is not user friendly. I am using my keyboards arrow key for opening up trees now due to this.
Love the great work you guys are doing for vscode. Keep it up.

![code](https://user-images.githubusercontent.com/1165845/35621114-45df5aaa-06a9-11e8-93c4-49c67ff5911d.png)

**Comment by luispabon** [comment] 2018-01-31 12:18
@tvvignesh that would be inconsistent with vscode itself as well as all other apps with a tree view that work the same way. The little triangle is there for single click operations.

**Comment by bpasero** [comment] 2018-01-31 13:04
I agree on the desire to expand a tree node with single-click if clicking onto the twistie, for that I opened: https://github.com/Microsoft/vscode/issues/42621

I am not sure about adding 2 options for expanding/collapsing a node with children and opening an item, for me logically it is the same "open" operation.

**Comment by d-bauer** [comment] 2018-01-31 14:35
I agree with @luispabon. 
Even in Visual Studio you have to double-click a folder to expand/collapse in the tree view. But you can click on the little triangle icon to expand/collapse with a single click. Maybe thats an option, @bpasero?

**Comment by tvvignesh** [comment] 2018-01-31 15:43
I tried clicking on triangle. Did not work. Had to double click to get it to expand. Also, the triangle is too small. Please check atom. Looking for the same functionality..

Single click to select or expand, double click to open. I tried opening the same project in both vscode and atom, tried expanding and I could clearly see the change in usability. Just my feedback here. Not sure how vscode internals are.

**Comment by tvvignesh** [comment] 2018-01-31 15:47
@bpasero: looks like you are already working on it. Thanks.
