### ISSUE TITLE
Continue On > Reopen on the Desktop flow when GitHub Repositories is not installed on desktop

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161971] opened 2022-09-27 13:24 UTC
Testing #161875

When I tried to reopen https://insiders.vscode.dev/github/bpasero/vscode-bisect on desktop I was asked to install the extension but then nothing opened. If it matters, I am running from a "testing" profile (i.e. not my default profile).

![image](https://user-images.githubusercontent.com/900690/192538412-eea038f1-58d5-480d-b733-51e5a441e3b9.png)

**Comment by joyceerhl** [comment] 2022-09-27 13:53
Do you have [GitHub Repositories](https://marketplace.visualstudio.com/items?itemname=github.remotehub) installed locally?

**Comment by bpasero** [comment] 2022-09-27 14:09
No I do not think so:

![image](https://user-images.githubusercontent.com/900690/192549603-209d705b-cfa9-46e5-8f00-245a47f8dcdc.png)

**Comment by joyceerhl** [comment] 2022-09-27 15:57
If you install the pre-release of GitHub Repositories and try again, does that work? If so, this looks like a bug that Remote Repositories is the url handler for the extension operation but doesn't notify if you need additional extensions.

**Comment by joyceerhl** [comment] 2022-09-27 17:38
> the first one failed

Do you mean signing into GitHub failed? Was it a modal dialog or a quickpick?

**Comment by amunger** [comment] 2022-09-27 18:16
modal dialog that stayed up until it timed out, and a page that failed to load in my browser (Edge)

**Comment by joyceerhl** [comment] 2022-09-27 19:18
> modal dialog that stayed up until it timed out, and a page that failed to load in my browser (Edge)

cc @TylerLeonhardt for GitHub auth

**Comment by TylerLeonhardt** [comment] 2022-09-27 19:23
> modal dialog that stayed up until it timed out, and a page that failed to load in my browser (Edge)

Got a screenshot or gif?

**Comment by amunger** [comment] 2022-09-27 19:26
![image](https://user-images.githubusercontent.com/2019016/192617628-b1a9ce9d-0a9f-4391-90d7-6afb4f5bf5b4.png)

**Comment by TylerLeonhardt** [comment] 2022-09-27 19:36
What's your browser look like?

**Comment by amunger** [comment] 2022-09-27 19:39
after closing and re-opening I'm suddenly signed in. But the browser just had a blank `about:blank` page, wasn't trying to load anything. I'm not sure how to sign out to see if it repros again

**Comment by TylerLeonhardt** [comment] 2022-09-27 19:57
GitHub's auth page does this redirect to a blank page that it closes... it's possible that you somehow got stranded on that page... if you see it again, feel free to reach out!

**Comment by bpasero** [comment] 2022-09-28 04:43
So when I install the pre-release version of GitHub repositories, this flow works now fine for me! This issue can be closed if you agree.

**Comment by joyceerhl** [comment] 2022-09-28 15:56
Thanks for the testing everyone, I converted this issue to track the fact that Reopen on the Desktop when you don't have GitHub Repositories installed on desktop does not work.

**Comment by joyceerhl** [comment] 2022-11-17 19:07
I pushed a workaround for this that makes Remote Repositories an extension pack, so that when it is installed, GitHub Repositories  and Azure Repos are also installed. Ideally however Remote Repositories would have a way to specify that
1. GitHub Repositories and Azure Repos should be installed when Remote Repositories is directly installed
2. No additional extensions should be installed when Remote Repositories is installed as a dependency of either GitHub Repositories or Azure Repos

**Comment by joyceerhl** [comment] 2022-12-01 19:44
If you don't have either Remote Repositories or GitHub Repositories installed, this should now work as expected because of the extension pack, but if you have Remote Repositories and not GitHub Repositories, this won't work. Reopening to fix the latter.

**Closed** 2023-04-07 22:13 UTC
Labels: bug, ux, polish

**Comment by meganrogge** [comment] 2023-04-27 18:59
@joyceerhl is this working as designed?

From the repro steps above, this command has been renamed to `Continue Workign in Remote Repository on VS Code Desktop`

![Screenshot 2023-04-27 at 11 56 13 AM](https://user-images.githubusercontent.com/29464607/234964252-399fbc18-e6d1-4579-bc47-c43326af30f0.png)

I also see these prompts simultaneously, which is confusing to me.
![Screenshot 2023-04-27 at 11 56 55 AM](https://user-images.githubusercontent.com/29464607/234964393-09efb6fe-640b-47ee-8678-21f6394cba9e.png)

I then see a third prompt
![Screenshot 2023-04-27 at 11 57 25 AM](https://user-images.githubusercontent.com/29464607/234964499-601f2f82-41c3-4d95-830d-6bded990b119.png)

And finally, I see a notification about needing to install an extension.
![Screenshot 2023-04-27 at 11 57 44 AM](https://user-images.githubusercontent.com/29464607/234964576-a17e3ba8-c8d7-4bba-ad53-eb5214c512b3.png)

I expected clicking `Show Extensions` to take me to the extension(s) I need to install, but instead, it just focuses the extensions view.

**Comment by joyceerhl** [comment] 2023-04-27 19:57
> I expected clicking Show Extensions to take me to the extension(s) I need to install, but instead, it just focuses the extensions view.

Hm, this should have prepopulated the extension IDs in the extensions view. Let me see if I can repro. 

The double prompt is unfortunate but we cannot control the one on the top (which comes from the browser), and the modal from us is necessary to give users a way out if they didn't install VS Code locally (in which case reopen on desktop will no-op)

**Comment by meganrogge** [comment] 2023-04-27 20:18
Not sure if this matters, but my extensions view was already showing at that time and also had input.

**Comment by joyceerhl** [comment] 2023-04-27 20:20
> also had input

That's probably why then
