### ISSUE TITLE
Terminal scrolling

### ISSUE THREAD

**Issue by fender** [Microsoft/vscode#45415] opened 2018-03-09 15:41 UTC
Issue Type: <b>Bug</b>

When hiding then re-opening my terminal window, its scrolled to the top of the log.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.57GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.0.7
vscode-eslint|dba|1.4.7
vscode-babel-coloring|dza|0.0.4
dotenv|mik|1.0.1
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.1.0
gitblame|wad|2.2.0

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment] 2018-03-09 17:05
Can you pls provide more information? I can't reproduce the problem. What shell are you using? Do you split your terminals? If you have a screen cast pls attach it. Thanks a ton.

**Comment by fender** [comment] 2018-03-11 11:08
@kieferrm 

[scroll.zip](https://github.com/Microsoft/vscode/files/1800236/scroll.zip)

I am on Mac OS X and this happens when I close then re-open the terminal and start to scroll up or down even though I should already be at the bottom.

**Comment by kieferrm** [comment] 2018-03-11 21:17
Thanks @fender for the screencast.

**Comment by raygervais** [comment] 2018-03-19 16:47
I'd like to take a crack at this, any tips / thoughts  prior to me setting up and starting? Thanks!

**Comment by Tyriar** [comment] 2018-03-19 18:16
This is fixed in Insiders already https://github.com/Microsoft/vscode/issues/45134

**Closed by Tyriar** 2018-03-19 18:16 UTC
Labels: integrated-terminal
