### ISSUE TITLE
Cursor position after deselection and line wrap

### ISSUE THREAD

**Issue by hookxs** [microsoft/vscode#92336] opened 2020-03-10 09:54 UTC
Normally, when a text a selected and either left or right arrow is pressed, the text is deselected and the cursor is placed before the first or after the last character of the selection, respectively, regardless of its previous position. This is very useful behavior. However, when the selected text is wrapped due to "word wrap"=on (not because multiple lines are selected) and left arrow is pressed, the cursor ends up one character before the previously selected text, which is inconsistent with the normal behavior. Right arrow works fine. This is more serious than it may seem because when multiple words are selected (ie all find matches) and some are line-wrapped while some aren't, one cannot consistently work with the multiple cursors (and for example change only part of the searched phrase) because some of the cursors will be offset by one character. Let me know if further clarification or video is needed.

**Comment by alexdima** [comment] 2020-03-11 08:08
Duplicate of #65815 . Today's insiders should already contain a fix.

**Closed by alexdima** 2020-03-11 08:08 UTC
