### ISSUE TITLE
Middle mouse click to scrolling.

### ISSUE THREAD

**Issue by brain-5** [microsoft/vscode#166076] opened 2022-11-11 03:38 UTC
Type: <b>Feature Request</b>

I will want to see middle mouse button click to scrolling in text editor, please! Please, add this option to settings.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by alexdima** [comment] 2022-11-25 20:02
Duplicate of https://github.com/microsoft/vscode/issues/6302

**Closed by alexdima** 2022-11-25 20:02 UTC
