### ISSUE TITLE
Cannot exit `git show` with `q` inside vs code

### ISSUE THREAD

**Issue by haimingz** [microsoft/vscode#203623] opened 2024-01-28 03:23 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: Windows 11 22H2

Steps to Reproduce:

1. create a git bash terminal in VS Code
2. enter the command `git show`
3. enter `q` to quit.
4. the terminal will not quit git show and freeze

Results from my test:
git bash outside VS Code -- ok
git bash inside VS Code -- not ok
PowerShell inside/outside VS Code -- not ok

**Comment by meganrogge** [comment] 2024-01-29 15:35
works for me in insider's on pwsh for macOS, @tyriar, how about windows?

**Comment by DhruvSankhe** [comment] 2024-07-16 10:30
vim test1.txt

**Comment by meganrogge** [comment] 2024-07-16 17:08
I cannot reproduce, thus closing

**Closed by meganrogge** 2024-07-16 17:08 UTC
