### ISSUE TITLE
Incorrect highlight for javascript ?

### ISSUE THREAD

**Issue by leozzyzheng** [Microsoft/vscode#3765] opened 2016-03-07 10:27 UTC
![image](https://cloud.githubusercontent.com/assets/6134295/13566431/8c8fb676-e490-11e5-8546-4d5a68ae34db.png)
![image](https://cloud.githubusercontent.com/assets/6134295/13566470/ba8e910a-e490-11e5-90b2-9cca9c76e372.png)

I have only added a space before the `<` on line 5.
Is it incorrect highlight ? I have remove all extensions and reinstall VSCode and set `javascript.validate.enable` to false, it didn't work.

Besides, I had used `npm ` install `jshint` and `eslint` in global but the highlight didn't change after I removed all of them.

VSCode version :
![image](https://cloud.githubusercontent.com/assets/6134295/13567557/e52abeec-e496-11e5-885e-eabb2feddd33.png)

**Comment by aeschli** [comment] 2016-03-07 11:18
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-03-07 11:18 UTC
Labels: js
