### ISSUE TITLE
command "code-insider ." do not work properly

### ISSUE THREAD

**Issue by vystepanenko** [microsoft/vscode#137711] opened 2021-11-23 10:58 UTC
Issue Type: <b>Bug</b>

command `code-insider .` do not work properly. This command must to open project in current folder but instead it open empty project

Steps to reproduce:
- In wsl go to project folder 
`cd /project/folder`
then type
`code-insiders .`

### Expected result
Open project in this folder

### Actual result
VSCode opened empty project or last opened project from other dir

Also reproduced with disabled extensions

VS Code version: Code - Insiders 1.63.0-insider (ed3018f4310e906daa0a9119d997e75b8a38b879, 2021-11-23T05:33:39.595Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.48GB free)|
|Process Argv|--remote=wsl+Ubuntu-20.04 --crash-reporter-id cac02e12-1b29-4401-90b4-691c0715a32a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3700)|
|Memory (System)|7.72GB (4.30GB free)|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-edge-devtools|ms-|1.4.1
remote-containers|ms-|0.206.0
remote-wsl|ms-|0.63.2
laravel5-snippets|one|1.13.0
material-icon-theme|PKi|4.10.0
code-settings-sync|Sha|3.4.3
errorlens|use|3.4.1
vscode-openapi|42C|4.6.4
vscode-sqlite|ale|0.14.0
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.7.2
better-phpunit|cal|1.5.3
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
php-debug|fel|1.22.0
php-cs-fixer|jun|0.2.8
twig-language|mbl|0.9.2
vscode-deploy-reloaded|mkl|0.89.0
vscode-docker|ms-|1.18.0
snippet-creator|nik|0.0.5
vetur|oct|0.35.0
laravel-blade|one|1.28.0
advanced-new-file|pat|1.2.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.0
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.28
code-spell-checker|str|2.0.13
code-spell-checker-russian|str|2.0.1
code-spell-checker-ukrainian|str|0.1.10
tabnine-vscode|Tab|3.5.1
errorlens|use|3.4.1
vscode-import-cost|wix|2.15.0
ascii-unicode-escape|yar|0.1.0

(5 theme extensions excluded)

</details>

**Comment by lauritk** [comment] 2021-11-23 15:13
I have some what same issue when trying to open files from wsl2 or using code-insiders as a core git editor. A new vs code window is opened with a empty new file.

**Comment by cdxn** [comment] 2021-11-23 15:35
same/similar - current build (and build as of Nov 22) - does not take . or path from code-insiders command line.

With no instances running, first instance opens the first project/location in recent. Subsequent instances open empty.

WSL2 follows this pattern.

Context-menu/right-click in windows context passes correctly to code-insiders (folder or individual file). WSL2 cli does not.

This is true from WSL2 launching with --disable-extensions

**Comment by youfang11523868** [comment] 2021-11-24 05:42
I have the same question as you. Why I can use code command to create a new file on Windows but not on Linux?

**Comment by lauritk** [comment] 2021-11-24 07:50
Perhaps duplicate of #137409 ?

**Comment by youfang11523868** [comment] 2021-11-24 07:53
I check it, thank you.

**Comment by egamma** [comment] 2021-11-24 08:19
/duplicate 
Since this happens on WSL this looks like a duplicate of #137409

**Closed by egamma** 2021-11-24 08:19 UTC
