### ISSUE TITLE
Experimental File Watcher - high CPU on "circular" symlinks

### ISSUE THREAD

**Issue by p-romanski** [Microsoft/vscode#36307] opened 2017-10-15 18:46 UTC
- VSCode Version: 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7)
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Set "files.useExperimentalFileWatcher": true and close VS Code
2. Create a symlink to root directory (must be an absolute link, not relative!):
```
$ mkdir loop
$ ln -s / loop/root
```

3. Open directory containing that symlink in VS Code:
```
$ code --disable-extensions loop
```

4. Watch processes - one of vs code processes takes high CPU 

Reproduces without extensions: Yes

See also: #3998

**Comment by xeor** [comment] 2017-10-15 19:07
Just noticed the same thing on osx...

**Comment by p-romanski** [comment] 2017-10-16 17:38
Updating issue with:
- vs code version 1.17.0
- confirmation that issue exists without extensions

**Comment by dobrysmak** [comment] 2017-10-18 14:16
Same issue here
vs code version 1.17.2
Even after closing the VsCode the Code Helpers is still running with 100% CPU usage.

**Comment by Tyriar** [comment] 2017-10-21 16:39
Reported upstream https://github.com/Axosoft/nsfw/issues/40

**Comment by Tyriar** [comment] 2017-10-27 23:00
Upstream PR https://github.com/Axosoft/nsfw/pull/41

**Comment by Tyriar** [comment] 2017-12-13 15:47
The original PR was closed so I opened one which was merged https://github.com/Axosoft/nsfw/pull/47, just need a release to pull this in.

**Comment by hebo-hebo** [comment] 2018-01-20 04:15
I have vscode 1.19.2 on Ubuntu. The various node_modules directories have symbolic links point to each other that form the circular links. Have "**/node_modules/**": true in "files.watcherExclude". After vscode is started, it uses 100% CPU and memory usage increased dramatically and soon reached the max memory and hang the system. This problem happens whatever useExperimentalFileWatcher is set true or false. The ps shows the problem code process has parameter '--type=watcherService". Attached gdb to the process, it shows the watcher follows through the circular symbolic links. Set "search.followSymlinks": false has no effect,.

Thread 3 (Thread 0x7f1f937a9700 (LWP 2302)):
#0  0x00007f1f99f94be5 in __GI___xstat (vers=<optimized out>,
    name=0x8388432e818 "/home/bo/workspace_git/BMI/bmi-cleanup/node_modules/msp-driver-ccp/node_modules/msp-driver-channels/node_modules/msp-driver-ccp/node_modules/msp-driver-channels/node_modules/msp-driver-ccp/node_module"..., buf=0x7f1f937a40c0) at ../sysdeps/unix/sysv/linux/wordsize-64/xstat.c:35

**Comment by jwulf** [comment] 2018-03-06 22:02
@Tyriar is it possible/easy to patch VS Code to stop this behaviour while waiting for it to hit a release? I have a workspace that causes a 20GB VM to exhaust its memory in about 15 mins because of circular symlinks (it uses lerna).

**Comment by Tyriar** [comment] 2018-03-07 17:56
@jwulf yeah I'll fork the module to get this in, was hoping I wouldn't need to.

**Closed** 2018-03-07 19:41 UTC
Labels: bug, file-watcher, linux, perf, upstream

**Comment by RMacfarlane** [comment] 2018-03-30 21:50
@Tyriar what's the expected behavior after the change? I'm still seeing high CPU on today's insiders version

on Ubuntu
![loop_cpu](https://user-images.githubusercontent.com/3672607/38154927-9bebc0c0-3429-11e8-8a92-f9542fe7c021.png)

on Mac
```
~$ code-insiders --status

Version:          Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:10:29.002Z)
OS Version:       Darwin x64 17.4.0
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)
Memory (System):  16.00GB (0.04GB free)
Load (avg):       3, 3, 2
VM:               29%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --disable-extensions loop

CPU %	Mem MB	   PID	Process
    1	   115	 77391	code-insiders main
    0	   246	 77394	   window (Welcome — loop)
    0	    66	 77396	     extensionHost
  146	   672	 77398	     watcherService
    0	    98	 77395	   shared-process
```

**Comment by Tyriar** [comment] 2018-03-31 01:51
@RMacfarlane the fix is specific to Linux only when you have experimental file watcher set to true in settings (or you have a multi-root workspace open).

**Comment by jwulf** [comment] 2018-04-02 01:03
If you have this issue, it's not just high CPU usage - your memory will be exhausted within minutes. With a workspace with circular symlinks in it (it uses lerna and has circular dependencies), I was seeing 20GB of RAM get sucked up in about 15 minutes.

Insiders has had the fix for a while now.

**Comment by Tyriar** [comment] 2018-04-02 14:32
@jwulf thanks, I'll mark as verified since you saw it before :+1:
