### ISSUE TITLE
Empty content area within new editor window on the macOS insider

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode#38157] opened 2017-11-12 18:10 UTC
- VSCode Version:
Version 1.19.0-insider (1.19.0-insider)
d6fbdcf19716910b26ea81efc95724f2fabe5aa6
2017-11-10T06:06:08.063Z
- OS Version:
macOS, Sierra, 10.12.6 (16G1036)

Steps to Reproduce:
1. fresh install of VSCode Insider, no extensions
2. open VSCode
3. no content, empty workspace, nothing, no welcome screen

![image](https://user-images.githubusercontent.com/14539/32701848-11b1f388-c7dd-11e7-94fb-8b54646218bf.png)

The output from dev tools:
```txt
shell.ts:175 Cannot assign to read only property 'when' of object '#<Object>': TypeError: Cannot assign to read only property 'when' of object '#<Object>'
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:22749
    at Array.forEach (native)
    at s (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:22664)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:22730
    at Array.forEach (native)
    at Object.s [as mixin] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:22664)
    at Object.t.getExcludes (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1268237)
    at t.getExcludes (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10:340445)
    at e.globFn (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10:340135)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:2028495
```
Full output:
https://gist.github.com/peterblazejewicz/111f7e27abe99d27b8068c65eef06147

Trying built-in any command menu results in warning:
```
[createInstance] r depends on UNKNOWN service quickOpenService.
```

Thanks!

**Comment by sandy081** [comment] 2017-11-13 11:14
I could reproduce the crash with following steps.

- Have following settings in the settings file under `.vscode` folder
```json
"search.exclude": {
        "build/**/*.js": {
			"when": "$(basename).ts"
		}
    },
    "files.exclude": {
        "build/**/*.js": {
			"when": "$(basename).ts"
		}
    }
```

Open the folder in VS Code and  💥

**Comment by sandy081** [comment] 2017-11-13 11:16
There are two errors in the log

1. `shell.ts:175 Cannot assign to read only property 'when' of object '#<Object>': TypeError: Cannot assign to read only property 'when' of object '#<Object>'` 

2. `shell.ts:463 Cannot add property sessionID, object is not extensible: TypeError: Cannot add property sessionID, object is not extensible`

First one is caused while merging files.exclude and search.exclude settings. Second one is caused while logging workbench editor settings using telemetry. Both are because, the configuration object which is frozen is being modified.

**Closed** 2017-11-13 11:20 UTC
Labels: bug, freeze-slow-crash, important, workbench

**Comment by peterblazejewicz** [comment] 2017-11-13 17:02
Thanks!
