### ISSUE TITLE
Can't emoji

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62506] opened 2018-11-02 21:44 UTC
😢😭😡😢😭😡😢😭😡😢😭😡😢😭😡😢😭😡

![image](https://user-images.githubusercontent.com/4033249/47941992-9f698000-dead-11e8-9c1f-b0fd5463b4c0.png)

**Comment by mjbvz** [comment] 2018-11-02 21:45
Duplicate of #62426

**Closed** 2018-11-02 21:46 UTC
