### ISSUE TITLE
Javascript regex syntax coloring bug

### ISSUE THREAD

**Issue by tdenisenko** [Microsoft/vscode#15692] opened 2016-11-18 04:20 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:
![51f96435343e0f939fa35c64b63f6134](https://cloud.githubusercontent.com/assets/5215665/20418414/d4ef1390-ad7f-11e6-849c-e3d8953ee42a.png)

1. Divider symbol "/" and regex string symbol "/" is somehow conflicting with each other and causes wrong coloring and syntax highlighting errors. But the code is working perfectly, and this issue only happens on Visual Code.
2. The code is attached below:
`$scope.formatPrice = function(num) {
        if (num >= 1000000) {
            return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
        }
        if (num >= 1000) {
            return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K';
        }
        return num;
    }
  };`

**Comment by ramya-rao-a** [comment] 2016-11-18 05:26
Closing as duplicate of #15334. 
@aeschli Looks like the upstream https://github.com/Microsoft/TypeScript-TmLanguage/issues/356 is fixed. Any idea, when can we pull in the grammar?

**Closed by ramya-rao-a** 2016-11-18 05:26 UTC

**Comment by aeschli** [comment] 2016-11-18 16:27
@ramya-rao-a I updated the grammar with https://github.com/Microsoft/vscode/commit/b8f51b535129d2c640ce4615049f1990fc83367c

**Comment by ramya-rao-a** [comment] 2016-11-21 17:55
@aeschli Will the grammar be part of 1.7.2 ?

**Comment by ramya-rao-a** [comment] 2016-11-21 21:59
@aeschli FYI, this has been cherry-picked by @kieferrm for 1.72

**Comment by aeschli** [comment] 2016-11-22 10:44
@ramya-rao-a, @kieferrm Let's hope that goes well. I think we should always selfhost on a updated grammar for a week or so.
