### ISSUE TITLE
Why my vscode can't use Toggle Word Wrap

### ISSUE THREAD

**Issue by yuantongkang** [Microsoft/vscode#23202] opened 2017-03-25 09:29 UTC
- VSCode Version: 1.10.2
- Microsoft Windows [ver 10.0.15063]

Steps to Reproduce:

1. hit alt + z ````no work````
2. click  View -> Toggle Word Wrap ````no work````
[this is my html file](http://onb5ufwvw.bkt.clouddn.com/index.html)
when I edit a html file ,I used a base64 format picture into a style tag，all the string was put in a line,but display in some lines.So I wanna to hit alt+z to  solve it，I have also tried the following settings:
````"editor.wordWrap": "on" ````and```` "editor.wordWrap": "off"````， but nothing happend。**Content still wraps!!!**  ![avatar](http://onb5ufwvw.bkt.clouddn.com/GIF.gif)

**Comment by amelamlivic** [comment] 2017-03-25 11:13
let me fuck fuck

**Comment by yuantongkang** [comment] 2017-03-25 12:24
@amelamlivic you're welcome

**Comment by alexandrudima** [comment] 2017-03-27 07:30
Duplicate of #21801. There is a solution in the Insiders build

**Closed by alexandrudima** 2017-03-27 07:30 UTC
