### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by digitaloptometry** [Microsoft/vscode#1524] opened 2015-12-21 10:31 UTC
Having votes on a signle request does not appear to be effective, so maybe if in stead of voting on an exisisting one we create hundreds of code folding requests will they add it?

been wanting to use VS Code for months now, and it's frustrating to have complicated features like extenstions added, but something simple like code folding is left.

Gonna give up on VS Code in a month :(

**Comment by bpasero** [comment] 2015-12-21 12:56
Closing as duplicate of #105. It is high on our backlog.

**Closed by bpasero** 2015-12-21 12:56 UTC
