### ISSUE TITLE
Enable Peek menu in Peek window

### ISSUE THREAD

**Issue by jeffbi** [microsoft/vscode#145272] opened 2022-03-16 22:40 UTC
When in the Peek window the context menu (right-click) does not include Peek options. It would be very helpful to right-click on a symbol in the Peek window and be able to, for example, select Peek Definition and have the definition of that symbol replace the current content of the peek window (or better, create a tab within the Peek window). Currently the only way to look at the definition of a symbol selected in the Peek window is to select `Go to Definition` which replaces the currently active window.

**Comment by gjsjohnmurray** [comment] 2022-03-16 23:45
Looks like a duplicate of #6857

**Comment by jeffbi** [comment] 2022-03-17 01:13
So it does. I did a search but I didn't see that come up. Sorry about that.

**Closed** 2022-03-17 07:48 UTC
Labels: *duplicate
