### ISSUE TITLE
Size of release notes pane is shrunk incorrectly

### ISSUE THREAD

**Issue by jakeouellette** [Microsoft/vscode#20670] opened 2017-02-15 18:17 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Let release notes pop up
2. Hit Command + to grow text size
3. Text gets cut off because there is a Pane

Normal:
![image](https://cloud.githubusercontent.com/assets/4029481/22988674/f350f46a-f380-11e6-95c5-befa11400333.png)

After command +
![image](https://cloud.githubusercontent.com/assets/4029481/22988688/fc2e7bc0-f380-11e6-8c7e-b637e04acd0f.png)

**Comment by mjbvz** [comment] 2017-02-15 21:27
Duplicate of #5745

**Closed by mjbvz** 2017-02-15 21:27 UTC
Labels: duplicate, webview
