### ISSUE TITLE
Cannot input Chinese in the terminal

### ISSUE THREAD

**Issue by Reilkay** [microsoft/vscode#112978] opened 2020-12-19 07:00 UTC
- VSCode Version: 1.52.1-1
- OS Version: Arch Linux x86_64

Steps to Reproduce:

1. When using IME to type in the terminal:
     ![Screenshot_20201219_144324.png](https://i.loli.net/2020/12/19/FvrVKOi4DdPjp3x.png)
2. The actual input is different from the input.(Each input is like a queue, and the queue is never pop.)
3. When I type “啊”，“宝宝”，”踩踩踩踩“，”顶顶顶顶顶顶顶顶“，I get this:
     ![Screenshot_20201219_144612.png](https://i.loli.net/2020/12/19/2lW1rEzTeQhnYBa.png)
4. Only exit and restart the vscode can help.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2020-12-22 21:25
do you have a custom font set for the terminal?

**Comment by ddzy** [comment] 2020-12-26 01:04
Same issue

**Comment by ccloli** [comment] 2021-01-26 06:23
I'm experiencing the same problem on terminal, when inputing with CJK IME, the selected word will not be filled, or it will ignore some characters. I also tried the latest inside build but can still get this problem. 

![vscode-terminal](https://user-images.githubusercontent.com/8115912/105803068-98237500-5fd7-11eb-8949-7dafe9e79600.gif)

This bug happens at around 1.52.0 (maybe, I don't update VSCode in time), and it occurs when you're inputing CJK letters with some CJK IME (for my example, this bug happens with [QQ Pinyin](http://qq.pinyin.cn/), but with Microsoft Pinyin it works fine).

> This comment was posted at https://github.com/microsoft/vscode/issues/112621#issuecomment-767302336 , but it may not related to the original topic (happens on Source Control panel) and I didn't notice this issue at that time.

**Comment by BlackGlory** [comment] 2021-02-17 03:19
It can still be reproduced on 1.53.2.

**Comment by meganrogge** [comment] 2021-02-26 19:29
Duplicate of #115814

**Closed** 2021-02-26 19:30 UTC
Labels: *duplicate, bug, integrated-terminal
