### ISSUE TITLE
problems HTML with the cursor when I press enter

### ISSUE THREAD

**Issue by linedotwww** [Microsoft/vscode#19478] opened 2017-01-27 07:21 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.4.2|

---

I show you how it works in atom.

![gif1](https://cloud.githubusercontent.com/assets/15665678/22363221/cd122208-e479-11e6-8895-4bfb44658f7e.gif)

then I show you how it works in VSCODE

![gif2](https://cloud.githubusercontent.com/assets/15665678/22363225/d96a5886-e479-11e6-801d-175290a83b60.gif)

![gif3](https://cloud.githubusercontent.com/assets/15665678/22363404/32bf9562-e47b-11e6-8838-3385d4943059.gif)
why when I press the "ENTER" the cursor moves to the alt attribute. Logically it should add a new line

![html json](https://cloud.githubusercontent.com/assets/15665678/22500773/00846366-e877-11e6-841f-4ac111cba421.jpg)

![gif4](https://cloud.githubusercontent.com/assets/15665678/22500917/86f5c3c2-e877-11e6-89f0-573240eac0e3.gif)

I moved the cursor with the mouse, then I pressed enter

![gif5](https://cloud.githubusercontent.com/assets/15665678/22501114/5f952d76-e878-11e6-8646-2d21b95b8e11.gif)

I moved the mouse cursor to end of line, again, I have twice hit the Enter key to move to a new line. Sorry for my English. But if I moved the mouse pointer immediately to a new line the problem disappears

![gif6](https://cloud.githubusercontent.com/assets/15665678/22501209/d88f948c-e878-11e6-9ebe-af4823354312.gif)

and then I press the tab key, and why is he fixated?

Steps to Reproduce:

1. I have to press "Enter" twice to move to a new line because when I click first time it returns to its original position. Although logically there should be a transition but a new line. 

Specifically I deleted all the plug-ins to show what the problem is VS CODE

**Comment by mousetraps** [comment] 2017-01-27 20:21
Ahh, thanks for refiling - I see, this is to do with emmet, not snippet support. Sorry, it was hard for me to tell from the gif earlier. @ramya-rao-a - thoughts on the suggested behavior?

**Comment by linedotwww** [comment] 2017-01-28 06:14
Thanks)

**Comment by ramya-rao-a** [comment] 2017-02-01 01:54
`img` is a snippet provided by emmet. Rest of what we are seeing here is the snippet expansion behavior in VS Code.

@linedotwww When I press ENTER the second time, the new line breaks from inside the alt attribute. How are you getting the cursor to the end of the line before the second ENTER?

@jrieken thoughts?

**Comment by linedotwww** [comment] 2017-02-01 07:59
By the way this happens and when I enter my snippet. I have to press twice enter to add new line

**Comment by linedotwww** [comment] 2017-02-01 09:11
![html json](https://cloud.githubusercontent.com/assets/15665678/22500773/00846366-e877-11e6-841f-4ac111cba421.jpg)

![gif4](https://cloud.githubusercontent.com/assets/15665678/22500917/86f5c3c2-e877-11e6-89f0-573240eac0e3.gif)

**Comment by jrieken** [comment] 2017-02-01 09:29
@linedotwww Sorry, the gif are way to confusing, please update this issue with steps

**Comment by ramya-rao-a** [comment] 2017-02-06 07:15
@linedotwww asking again, When I press ENTER the second time, the new line breaks from inside the alt attribute. How are you getting the cursor to the end of the line before the second ENTER?

**Comment by linedotwww** [comment] 2017-02-06 07:55
with the mouse

**Comment by ramya-rao-a** [comment] 2017-02-07 06:57
Ok I think I got it.
@linedotwww Can you confirm the below steps?

1. type `img` hit tab, cursor is in `src` attribute
2. use mouse to place cursor at end of the line, hit enter 
    - user expects to go to the next line, but cursor ends up in the `alt` attribute
3. repeat i.e. use mouse to place cursor at end of the line, hit enter 
    - now cursor goes to the next line

What is happening is that after step 2, you are still in "snippet mode". While in "snippet mode" hitting ENTER or ESC takes out of the "snippet mode". So in step 2, when you hit ENTER, you get out of snippet mode instead of that ENTER taking you to the next line.

By the time you are in step 3, you are out of "snippet mode" and so the ENTER you press takes you to the next line.

Note: You can tell if you are in snippet mode if the expanded snippet has a slightly different background color than the rest of the editor, as you can see in your gifs.

Related to #5427

@jrieken This is about ENTER not taking cursor to next line and instead getting used as an escape out of snippet more

**Comment by jrieken** [comment] 2017-02-07 08:47
closing this of a dupe of #5427

**Closed by jrieken** 2017-02-07 08:47 UTC
Labels: bug, snippets
