### ISSUE TITLE
Keeps Recommending install c# microsoft extension and not found on marketplace.

### ISSUE THREAD

**Issue by NULL0B** [microsoft/vscode#92175] opened 2020-03-06 18:13 UTC
Hello:
c# extension breaking changes:
```
What's new in 1.21.13
Change Marketplace publisher for the C# extension from ms-vscode to ms-dotnettools
```
This let vscode asking to install recommends for .cs files as it doesnt detect the extension

**Comment by IllusionMH** [comment] 2020-03-06 18:44
/duplicate of #92153

You can install previous version for now. See https://github.com/OmniSharp/omnisharp-vscode/issues/3623#issuecomment-595561225 for current workaround

**Closed** 2020-03-06 18:45 UTC
Labels: *duplicate
