### ISSUE TITLE
Lost coloring

### ISSUE THREAD

**Issue by MaHa-Work** [microsoft/vscode#166612] opened 2022-11-17 17:18 UTC
Type: <b>Bug</b>

Import/const/this keywords are no longer shown as colored keywords. Strings/String literals/comments are now all white. Changing to a different color theme does not fix the issue.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.63GB free)|
|Process Argv|--crash-reporter-id 9bb5e8fa-a3e6-4204-803e-3e9c98874c4a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|15.0.1
vscode-html-css|ecm|1.13.1
rest-client|hum|0.25.1
vscode-language-babel|mgm|0.0.36
vscode-docker|ms-|1.22.2
remote-containers|ms-|0.262.3
vscode-typescript-next|ms-|5.0.20221117
LiveServer|rit|5.7.9
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by helendurranttw** [comment] 2022-11-17 17:22
I'm seeing this too.

Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (1 wk ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

**Comment by mjbvz** [comment] 2022-11-17 17:33
Duplicate of https://github.com/microsoft/vscode-typescript-next/issues/43

**Closed by mjbvz** 2022-11-17 17:33 UTC
