### ISSUE TITLE
VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code. 

### ISSUE THREAD

**Issue by ggprod** [microsoft/vscode#72721] opened 2019-04-22 17:32 UTC
Several extensions are causing the error on vscode startup:
VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code. 

This is being caused by the latest vscode-docker extension, the redhat.java (Language support for Java by RedHat), redhat.vscode-yaml (YAML support by RedHat), esbenp.prettier-vscode (Prettier - Code Formatter) and others

- VSCode Version: v1.33.1
- OS Version: MacOS Mojave 10.14.4

Steps to Reproduce:

1. Install certain extension
2. Startup vscode

Does this issue occur when all extensions are disabled?: No

**Comment by up2pixy** [comment] 2019-04-22 20:36
I have same issue today.

**Comment by mjbvz** [comment] 2019-04-23 18:42
@ggprod Can you check if the tsserver file has actually been deleted. For macos, it would be under the vs code executable itself:

- For 1.33 stable: `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js`
- For insiders: `/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js`

In the terminal can just run, `ls "/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/"` and see which files are present in that directory

**Comment by wcjohnson11** [comment] 2019-04-23 21:20
I had this same error. I tried to reinstall with no success.

I checked in the dir that @mjbvz mentioned above and `tsserver.js` was present.
I was able to get rid of the error message and get the rest of my extensions working by clicking on the cog in the error message which took me to the extension settings, VSCode's bundled typescript/javascript language features, and clicking enable.

Doing this and restarting VSCode fixed the issue for me.

- VSCode v1.33.1
- OS version: Mac Mojave v10.14.4

**Comment by ggprod** [comment] 2019-04-23 22:06
@mjbvz Yes, I see the file present and was able to fix the problem via the method @wcjohnson11 indicates.  Thanks!

**Comment by booc0mtaco** [comment] 2019-05-02 22:32
It appears that if you disable this built-in extension (say, you want to use flow instead of typescript), you get this error on every application launch. This seems like a regression...

**Comment by valscion** [comment] 2019-05-08 06:55
This started happening to me, too — I have disabled the `vscode.typescript-language-features` extension for the current workspace and get this error on every launch of VS Code.

I do have the `tsserver.js` present. Running macOS Mojave version 10.14.4 (18E226) and VS Code version 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8)

![vesa_Vesas-MBP____code_v_venuu__zsh__and_VS_Code_s_tsserver_was_deleted_by_another_application_such_as_a_misbehaving_virus_detection_tool__Please_reinstall_VS_Code__·_Issue__72721_·_microsoft_vscode_and_Extension__TypeScript_and_JavaScript_](https://user-images.githubusercontent.com/482561/57355648-2eb26180-7177-11e9-86ed-1a901365e73c.png)

**Comment by mjbvz** [comment] 2019-05-08 18:31
Does this also happen in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

---

Adding @sandy081 since it sounds like the builtin js/ts extension could still be activated even when disabled? Or that installing other extensions is corrupting our extension?

**Comment by valscion** [comment] 2019-05-09 06:46
For some reason the error has gone away for me ¯\\\_(ツ)_/¯ I don't think I've updated anything between my message and now.

**Comment by sandy081** [comment] 2019-05-09 07:36
@mjbvz There was a bug recently (last stable) that disabled extensions are getting activated - https://github.com/microsoft/vscode/issues/71752. This got fixed in insiders.

**Comment by cweekly** [comment] 2019-05-16 14:34
I'm on VSC v1.33.1, macOs 10.13.6, and saw this error today (after 1st system reboot in weeks). The Typescript built-in extension remained in "disabled" state. Restarted VSC a couple times and the error went away.

**Comment by mjbvz** [comment] 2019-05-16 17:35
I'm closing this a a duplicate of #71752. If you see this when using VS Code 1.34+, please let me know

**Closed by mjbvz** 2019-05-16 17:35 UTC
Labels: extensions, needs more info
