### ISSUE TITLE
Auto Import does wrong imports

### ISSUE THREAD

**Issue by ahmad2smile** [Microsoft/vscode#40702] opened 2017-12-22 08:05 UTC
When trying to import something with Auto Import if the lib is already in the file then It works fine.

Like if I import Component from `react` when file already includes `import react from 'react'` it works fine and adds

`import react, { Component } from 'react'`
but If I import something from a lib thats not already in the file then it goes crazy like,
trying to auto import something from `react-navigation` results in:

`import { addNavigationHelpers } from "../../../../Library/Caches/typescript/2.6/node_modules/@types/react-navigation";
`

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions:

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.1.2
beautify|Hoo|1.1.1
code-settings-sync|Sha|2.8.7
vscode-color|ans|0.4.5
vscode-eslint|dba|1.4.3
prettier-vscode|esb|1.0.1
vscode-redux-devtools|jin|0.0.11
atom-keybindings|ms-|3.0.4
node-debug2|ms-|1.19.3
debugger-for-chrome|msj|4.0.0
vscode-react-native|vsm|0.5.7

---

Steps to Reproduce:

1. Just try to auto import `addNavigationHelpers` from `react-navigation`

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-12-22 19:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/19878

To check this, please try using typescript@next in your workspace by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Closed by mjbvz** 2017-12-22 19:17 UTC
Labels: javascript
