### ISSUE TITLE
Debugger won't hit break points with Jest test

### ISSUE THREAD

**Issue by abogartz** [Microsoft/vscode#54485] opened 2018-07-17 16:10 UTC
Issue Type: <b>Bug</b>

Run debug with the following debugger setup:

```
{
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "port": 9229,
      "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/.bin/jest",
        "--watch",
        "--bail",
        "--runInBand"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "runtimeExecutable": "${env:HOME}/.nvm/versions/node/v8.11.1/bin/node",
      "skipFiles": [
        "lodash.js",
        "zone.js",
        "tslib.js",
        "angular",
        "browser-sync*",
        "pdf-make*"
      ]
    },
```
Getting this error in the CALL STACK pane and no breakpoints are hit.

`[node-debug2] Error processing "stackTrace", Cannot read prop "replace" of null.`

VS Code version: Code - Insiders 1.26.0-insider (d1272ff8edbaa54c81382f82fa2091f63ed3daea, 2018-07-17T08:29:57.116Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.37GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1179936|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
string-converter|ada|0.1.1
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
auto-rename-tag|for|0.0.15
githd|hui|1.2.0
typelens|kis|1.5.0
vsliveshare|ms-|0.3.395
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.0
typescript-hero|rbb|2.3.2
vscode-icons|rob|7.24.0
sass-indented|rob|1.4.9
shader|sle|1.1.3
move-ts|str|1.11.3
sort-lines|Tyr|1.7.0

</details>

**Comment by abogartz** [comment] 2018-07-17 16:16
I just opened the DEBUG CONSOLE and I see a slew if VSCode errors.

`******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'replace' of null
    at Object.applySourceMapPathOverrides (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapUtils.js:68:46)`

**Comment by abogartz** [comment] 2018-07-18 15:49
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2206432/debugadapter.txt)

**Comment by roblourens** [comment] 2018-07-18 18:34
The log does not show a pause or stacktrace request or any errors. Did you run the same scenario and see the errors when producing the log?

**Comment by abogartz** [comment] 2018-07-18 19:49
Yes, I was able to see the same errors. Visually, the breakpoint remains gray and does not turn red. In the debug console, I see those errors.

**Comment by roblourens** [comment] 2018-07-18 20:38
Any chance you can share your project?

Or can you try producing a log again to see if it ends up with the relevant log messages this time?

**Comment by abogartz** [comment] 2018-07-19 17:21
I can share the project, but I can try and get a better log result. Stay tuned...

**Comment by abogartz** [comment] 2018-07-19 18:10
I've seen this before, but now it's working. The problem seems to be intermittent. Maybe it's related to which file I'm trying to add the breakpoints to. I'll keep working and see if I can isolate the steps.

**Comment by ctsstc** [comment] 2018-09-10 23:50
I feel like I'm experiencing the same issue and that it came about when I added these for my skipfiles:
After they are added it breakpoints in places I never set and it moves breakpoints around oddly.
It makes me wonder if it's avoiding the skipfiles to help it determine where the breakpoints are, maybe related to mapping?

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Jest Debug - Launch via NPM",
      "runtimeExecutable": "node",
      "runtimeArgs": [
        "--debug-brk",
        "--inspect",
        "${workspaceRoot}/node_modules/jest/bin/jest.js",
        "-i"
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "port": 9229,
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ]
    }
  ]
}
```

**Comment by roblourens** [comment] 2018-09-10 23:58
skipFiles should not break that. Does it work correctly if you get rid of those lines?

**Comment by ctsstc** [comment] 2018-09-10 23:59
Sorry edited the above comment and seems you've already responded before I updated, so I brought it to this comment instead. I removed the skipFiles and it still happens.

I do notice it seems odd that when I start the debug session my breakpoint (line 39) becomes gray and says "Unverifiable breakpoint" then it breaks a few lines above (line 33) in another function. If I add it back (line 39) after it hits the breakpoint that it added above (line 33), it will now hit the breakpoint (line 39) upon resuming. Both breakpoints at this point show up in the breakpoint panel (line 33, line 39) with their own line numbers. Upon resuming and the debugging session ends, now it has two breakpoints in the breakpoint panel that show the same line number (line 39, line 39).

**Comment by ctsstc** [comment] 2018-09-11 00:03
Here's a video of what I'm seeing https://screencast.com/t/mxvlvpHrYps

Sometimes it breaks on a VM file that doesn't exist in the project, sometimes it doesn't even land in the same file.

**Comment by roblourens** [comment] 2018-09-11 01:29
Can you share your project?

**Comment by ctsstc** [comment] 2018-09-11 01:53
@roblourens unfortunately no, but tomorrow I will try to see if I can reproduce it in an example that I can share.

**Comment by rswerve** [comment] 2018-09-19 17:28
Would I be better off opening a new issue with the debug details?  Not sure this one is being checked anymore.

**Comment by roblourens** [comment] 2018-09-19 18:28
This one was specifically for the error `Cannot read prop "replace" of null.` which sounds like it went away, so I'm going to close it, but you can open a new one @rswerve. Looking at your log, I see you set breakpoints in a file but I don't see that file being loaded.

**Closed by roblourens** 2018-09-19 18:28 UTC
Labels: debug, needs more info

**Comment by arizonatribe** [comment] 2018-09-28 02:00
Actually this issue was specifically opened for the problem:
```
Debugger won't hit break points with Jest test #54485
```
:)

**Comment by jacksaunders** [comment] 2018-10-05 16:37
I am getting exactly the same issue, it seems to be isolated just my test files. I can set app breakpoints no problem and it hits them even from the test. Any Chance we can reopen this and i will see if i can set up a similar repo to help

**Comment by jacksaunders** [comment] 2018-10-05 16:55
So i have created a repo which is close to what i am working on, its an ejected create react app and can be seen here. 

https://github.com/jacksaunders/vscode-jest-test

I ran  vscode with all plugins disabled, and just ran the basic App test that comes with create react app. 

here is a quick gif of what is happened

![jest-test](https://user-images.githubusercontent.com/1415692/46548699-b4abb880-c8c7-11e8-9564-0f99cb23e4e9.gif)

## vscode version info

![image](https://user-images.githubusercontent.com/1415692/46548737-d016c380-c8c7-11e8-8813-71ab9d711575.png)

**Comment by roblourens** [comment] 2018-10-05 17:52
Please open a new issue
