### ISSUE TITLE
Can we have Terminal as a separate window?

### ISSUE THREAD

**Issue by pmkary** [microsoft/vscode#105591] opened 2020-08-28 14:50 UTC
VS Code's terminal has grown from a nice-to-have thing to one of the greatest terminals ever. It is by far better than the original system terminals and the alternatives iTerm / Hyper / Upterm / Alacritty ... 

But it is limited to the panels of the VS Code. What if you could open them as separate windows and then be able to split the windows. I wish I could open a VS Code window in full screen just for my terminals or maybe an editor that represented the Terminal. 

There is one undeniable truth that for each electron software you are running one chrome. By making the custom editors you now have made it possible to reduce the cost of many electrons to one and have the VS Code do what an operating system does by providing a safe foundation of APIs. So having that powerful terminal do much more than just a panel make the vsocde move one more step towards that OS where you can all your developer tools in one software cross-platform talking to each other.

**Comment by IllusionMH** [comment] 2020-08-29 00:12
Looks like duplicate of #10121

**Comment by Tyriar** [comment] 2020-08-29 00:44
Actually this one: https://github.com/microsoft/vscode/issues/34442, be sure to give it a :+1:

/duplicate

**Closed by Tyriar** 2020-08-29 00:44 UTC
