### ISSUE TITLE
`add configuration` don't open launch.json when click again

### ISSUE THREAD

**Issue by kpge** [microsoft/vscode#80244] opened 2019-09-03 03:28 UTC
can not open `launch.json` when click  `Add configuration` again after the file is closed

- VSCode Version: Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
- OS Version:win10

Steps to Reproduce:
![vscode](https://user-images.githubusercontent.com/35068357/64142268-e7469400-ce3d-11e9-8e56-f1ce001a14d8.gif)

1.click `Add configuration` in debug widget
2.close launch.json
3. click  `Add configuration` in debug widget again.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment] 2019-09-03 04:10
/confirm I can repro on 1.37.1 and on 1.38.0-insider. Also when all extensions are disabled.

**Comment by isidorn** [comment] 2019-09-03 12:33
I can reproduce this on Windows where we use the custom select box.
The issue here is that the custom SelectBox fires a `onDidSelect` event, when listening to that event debug decides to change the selection [here](https://github.com/Microsoft/vscode/blob/99bc09cea27a29e4ea702845f0eb843669c254bd/src/vs/workbench/contrib/debug/browser/debugActionViewItems.ts#L111) (such that the "Add Configuration" does not remain selected). It seems like the custom select box can not handle this case of changing what is selected as soon as the onDidSelect event fires. If we do this with a timeout it works nicely, but is a hack thus I would prefer a proper solution.

Code pointer for the custom select box https://github.com/Microsoft/vscode/blob/99bc09cea27a29e4ea702845f0eb843669c254bd/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L83
PR welcome that fixes this issue.

fyi @cleidigh

**Comment by cleidigh** [comment] 2019-09-03 21:14
@isidorn 
You can assign this to me .  We had something similar in the past to my recollection.  But I agree I don't like the timeout approach.  I am just wondering if it is of particular edge type case that forces us to have something like a "post-change-event" paradigm.  The interaction between the debug selection and the editor window has always had a few quirks.

**Comment by isidorn** [comment] 2019-09-04 07:53
@cleidigh makese sense, assigning to you. As for building master if you still see the error you can post it here.

**Comment by cleidigh** [comment] 2019-09-05 19:45
@isidorn 
Unfortunately master build still fails.  I double check to the current requirements I am all up-to-date according to the docs.  The failures the download of rigrep. output below:  Thanks for the help.
[4/4] Building fresh packages...
[10/15] ⠄ oniguruma
[7/15] ⠄ spdlog
[9/15] ⠄ vscode-sqlite3
[8/15] ⡀ vscode-ripgrep
error C:\Dev\VSC Dev\vc-fork-cdl\vscode\node_modules\vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: C:\Dev\VSC Dev\vc-fork-cdl\vscode\node_modules\vscode-ripgrep
Output:
Finding release for v11.0.1-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2
Downloading from https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/assets/13800815
Downloading to C:\Users\CHRIST~1\AppData\Local\Temp\vscode-ripgrep-cache-1.5.6\ripgrep-v11.0.1-2-x86_64-pc-windows-msvc.zip
Downloading with Invoke-WebRequest
Unzipping to C:\Dev\VSC Dev\vc-fork-cdl\vscode\node_modules\vscode-ripgrep\bin
Deleting invalid download
Downloading ripgrep failed: Error: Command failed: powershell -ExecutionPolicy Bypass -Command Expand-Archive -Path C:\Users\CHRIST~1\AppData\Local\Temp\vscode-ripgrep-cache-1.5.6\ripgrep-v11.0.1-2-x86_64-pc-windows-msvc.zip -DestinationPath C:\Dev\VSC Dev\vc-fork-cdl\vscode\node_modules\vscode-ripgrep\bin -Force
Expand-Archive : A positional parameter cannot be found that accepts argument
'Dev\vc-fork-cdl\vscode\node_modules\vscode-ripgrep\bin'.
At line:1 char:1
+ Expand-Archive -Path C:\Users\CHRIST~1\AppData\Local\Temp\vscode-ripg ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Expand-Archive
    at ChildProcess.exithandler (child_process.js:294:12)

**Comment by isidorn** [comment] 2019-09-06 08:05
@roblourens can you help please for the build error @cleidigh is hitting. This seems like a similar issue I was hitting

**Comment by roblourens** [comment] 2019-09-10 14:38
This is https://github.com/microsoft/vscode-ripgrep/issues/2 @cleidigh, sorry will fix soon

**Comment by cleidigh** [comment] 2019-09-10 20:31
@roblourens 
Excellent, it has been  a while hope all is good with you.
I will look for the fix..

**Comment by plainerman** [comment] 2021-01-27 08:42
@cleidigh 
I could not reproduce this issue anymore. I believe that it can be closed.

**Comment by isidorn** [comment] 2021-01-27 08:45
Oh yeah this seems to work. @plainerman thanks for pointing out!

**Closed by isidorn** 2021-01-27 08:45 UTC
Labels: bug, confirmed, debug, help wanted
