### ISSUE TITLE
WebGL/GLSL rendering issue

### ISSUE THREAD

**Issue by leroyron** [Microsoft/vscode#22485] opened 2017-03-12 20:27 UTC
- VSCode Version: 1.10.2
- OS Version: Windows 8.1

Has the Webview Preview Chrome version changed, The WebGL renderer use to work before.
Before:
[https://github.com/leroyron/timeline-vscode/raw/master/images/preview.gif](https://github.com/leroyron/timeline-vscode/raw/master/images/preview.gif
)
After:
[http://imgur.com/a/D4gqK](http://imgur.com/a/D4gqK)

As you see it's now only showing basic GLSL rendering for the 2D reticle and cursors.

Has the chrome been downgraded? because i'm able to view it in a standalone chrome browser-

UPDATE: It's an ASYNC issue...

**Comment by weinand** [comment] 2017-03-13 09:15
@leroyron does it make a difference if you switch back to VS Code 1.9.x?
What do you mean by "It's an ASYNC issue..."?

**Comment by leroyron** [comment] 2017-03-14 00:17
@weinand Yes, the update is the issue, **January 2017 (version 1.9)** - Visual Studio Code - is the last working version for WebGL, textures are having problem loading in... The debugger shows nothing, VSCode 1.9 has **Chrome version 53** as well **February 2017 (version 1.10)**

**Comment by jrieken** [comment] 2017-03-14 09:13
@mjbvz made changes in the webview area

**Comment by mjbvz** [comment] 2017-03-14 17:24
@leroyron Please double check that the developer console does not have any error messages. Make sure you are in the devtools for the webview itself by running `document.getElementsByTagName('webview')[0].openDevTools()` in the primary devtools console. Also, try debugging with all exceptions enabled to see if any caught exceptions are causing trouble.

If you still do not find the root cause, please confirm your code works in Chrome proper and provide some example code so that we can investigate

**Comment by leroyron** [comment] 2017-03-14 23:00
I only get this warning: -- [Extension Host] typescript (vscode.typescript) uses PROPOSED API which is subject to change and removal without notice [Extension Host] extensionHost.ts:282 --
In WebView Chrome and VSCode Output...

No errors coming from the Extension Host Debugger.

Comparing WebGL and Browser Info:
**Google Chrome Browser v56** with **VSCode 1.10.2 Chrome Browser v53**
[http://imgur.com/a/Hje1q](http://imgur.com/a/Hje1q)

**Google Chrome Browser v56** with **VSCode 1.9.1 Chrome Browser v53**
[http://imgur.com/a/Abeh4](http://imgur.com/a/Abeh4)

I notice **security in MarkDowns for VSCode 1.10.2**, is security getting in the way by any chance?
[http://imgur.com/a/HUSuF](http://imgur.com/a/HUSuF)

**Comment by mjbvz** [comment] 2017-03-16 00:24
@leroyron Yes we restricted what the markdown preview can display by default but this should not impact an extension, unless you are somehow invoking the markdown extension's preview with custom content

**Comment by mjbvz** [comment] 2017-03-21 23:00
Closing as with the information provided, the issue does not seem to be caused by VSCode itself. @leroyron, if you still believe that the VSCode webview is the root cause here, please share a small sample extension that demonstrates the problem and I can take another look

**Closed by mjbvz** 2017-03-21 23:00 UTC
Labels: needs more info, webview

**Comment by leroyron** [comment] 2017-04-12 23:54
I used an IFrame now WebGL works for my project.
