### ISSUE TITLE
Unable to correctly change the "Choose what to configure in your Profile" options when creating a Profile

### ISSUE THREAD

**Issue by ClxUne09** [microsoft/vscode#226020] opened 2024-08-19 23:27 UTC
Type: <b>Bug</b>

# Unable to correctly change the "Choose what to configure in your Profile" options when creating a Profile

Hi, I have a problem when trying to change my configured ("Choose what to configure in your Profile" Section) options while creating a new profile. If I change any option in this section, I am unable to modify anything else, and all options become disabled. This also includes issues with the "copy from:" option.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.9.0
fluent-icons|mig|0.0.18
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
powershell|ms-|2024.2.2
vs-sequential-number|nep|1.1.0
material-icon-theme|PKi|5.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-c:31118571

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-08-20 00:06
/duplicate of #224788 which also offers a workaround

**Closed** 2024-08-20 00:07 UTC
Labels: *duplicate, triage-needed
