### ISSUE TITLE
Chords broken

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16610] opened 2016-12-06 10:33 UTC
* open keybindings editor
* press Cmd+K, Cmd+K
* 🐛 nothing happens

**Comment by jrieken** [comment] 2016-12-06 10:34
![screen shot 2016-12-06 at 11 34 26](https://cloud.githubusercontent.com/assets/1794099/20922300/f315f196-bba7-11e6-9335-5d9b6d786b5a.png)

I see that message when I press `cmd` for the second time.

**Comment by Tyriar** [comment] 2016-12-06 19:16
@jrieken cannot repro on Mac or Linux with latest Insiders (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94)?

**Comment by jrieken** [comment] 2016-12-07 07:20
Reproduces with insiders (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18) on Mac for me. @Microsoft/vscode Can someone else try?

**Comment by bpasero** [comment] 2016-12-07 07:27
It does for me. I see the message as soon as `Cmd-key` is pressed, so I think the chord is not even able to detect the full `Cmd+K` key press.

**Comment by alexandrudima** [comment] 2016-12-07 08:49
I can reproduce if I open the keybindings and then press:
* `Ctrl+K`
* press only `Ctrl` (see invalid chord message)
* I can no longer press `Ctrl+K`, `Ctrl+K`, there appears to be some state that is miss-managed.

**Comment by Tyriar** [comment] 2016-12-07 18:33
Still can't repro on 0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, @alexandrudima could this be a duplicate of https://github.com/Microsoft/vscode/issues/16833?

**Comment by alexandrudima** [comment] 2016-12-08 15:36
Indeed, duplicate of #16833

**Comment by alexandrudima** [comment] 2016-12-08 15:36
To the verifier: Please verify with these steps too.

**Closed by alexandrudima** 2016-12-08 15:36 UTC
Labels: bug, important
