### ISSUE TITLE
Cannot paste using (cmd + v) in VSCode Desktop integrated terminal

### ISSUE THREAD

**Issue by VincentDondain** [microsoft/vscode#116143] opened 2021-02-08 20:57 UTC
On macOS I cannot paste using the keyboard shortcut (cmd + v) in the integrated terminal. If I right click and select paste that works.

## Environment

CPUs | Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 64.00GB (27.35GB free)
Process Argv | --crash-reporter-id a89ac4a4-a92a-483e-9532-9b18b01d1b98
Screen Reader | no
VM | 0%

## Extensions

Does this issue occur when all extensions are disabled?: **Yes**

Extension | Author (truncated) | Version
-- | -- | --
Bookmarks | ale | 12.1.4
markdown-preview-github-styles | bie | 0.1.6
path-intellisense | chr | 2.3.0
bracket-pair-colorizer | Coe | 1.0.61
es7-react-js-snippets | dsz | 3.1.0
gitlens | eam | 11.2.1
EditorConfig | Edi | 0.16.4
vscode-yarn | gam | 1.7.1
codespaces | Git | 0.7.1
vscode-pull-request-github | Git | 0.23.0
terraform | has | 2.5.0
rails-snippets | Hri | 1.0.8
better-line-select | kai | 1.1.1
vscode-azureterraform | ms- | 0.3.2
vscode-docker | ms- | 1.9.1
csharp | ms- | 1.23.9
vscode-kubernetes-tools | ms- | 1.2.3
remote-containers | ms- | 0.158.0
azure-account | ms- | 0.9.5
azurecli | ms- | 0.5.0
material-icon-theme | PKi | 4.5.0
ruby | reb | 0.28.1
vscode-xml | red | 0.15.0
vscode-yaml | red | 0.14.0
code-spell-checker | str | 1.10.2
vscodeintellicode | Vis | 1.2.11
vscode-icons | vsc | 11.1.0
vscode-ruby | win | 0.28.0
JavaScriptSnippets | xab | 1.8.0

## A/B experiment info

vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanelcf:30233468
coreuntitledfile:30249963

**Comment by meganrogge** [comment] 2021-02-08 21:07
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

Duplicate of #116098

**Closed** 2021-02-08 21:08 UTC
Labels: *duplicate

**Comment by VincentDondain** [comment] 2021-02-09 14:20
@meganrogge yes I can confirm this is fixed in the latest Insiders build, thank you very much (:
