### ISSUE TITLE
Git Branch Picker Race Condition

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#214626] opened 2024-06-07 16:10 UTC
If I paste the branch too quickly and then press enter, it does not switch to it, but creates a new branch.
This breaks muscle memory, as it works when you do it slowly.

![Code_-_Insiders_peF36XR6nS](https://github.com/microsoft/vscode/assets/2931520/d5d901c1-ad87-4c36-afe5-2a3a4d267800)

Once loading completes, it should select the branch again.

**Comment by lszomoru** [comment] 2024-07-05 13:29
Duplicate of https://github.com/microsoft/vscode/issues/218628

**Closed by lszomoru** 2024-07-05 13:29 UTC
Labels: bug, git
