### ISSUE TITLE
Breakpoint section doesn't show breakpoints initially

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#35179] opened 2017-09-26 21:46 UTC
- VSCode Version: Insiders 1.17 a5210bcbda97166904ce4c08ee296cb98fccfcd9
- OS Version: macOS

Steps to Reproduce:

- install mock-debug extension
- create a breakpoint in a foo.md file

Observe: 
Breakpoint shows up in gutter and BREAKPOINTS view

- restart or reload VS Code

Observe: 
Breakpoint section is expanded but doesn't show breakpoints.

- add another breakpoint

Observe: 
both breakpoints show up

**Comment by isidorn** [comment] 2017-09-27 14:38
I can not reproduce this with my latest fixes linked in the other issue thus closing.
Please let me know if you can still reproduce this, thank you.

**Comment by weinand** [comment] 2017-09-28 14:16
I can still reproduce this.

**Comment by isidorn** [comment] 2017-09-28 14:21
For some reason I do not see this on my machine. Due to that I believe it is a timing issue. Might the split view ask me too early about the size
@joaomoreno did we change something with our split view refactoring that could affect this?

**Comment by joaomoreno** [comment] 2017-09-28 14:33
Possible... but probably not. Check the code that sets the view size and make sure it sets it right.

**Comment by isidorn** [comment] 2017-10-03 15:28
I believe https://github.com/Microsoft/vscode/commit/1804467caaff744834b477b0ca4c3897b0b35939 has introduced this issue. Looking at the code I am suspect the setting of 0 as the size in the constructor. I believe I have addresed this issue with the commit, however since I could not originaly reporduce this issue will wait for @weinand to check.

**Closed** 2017-10-03 15:27 UTC
Labels: bug, debug
