### ISSUE TITLE
[[[[[please add]]]]] spelling check in build inside vs code

### ISSUE THREAD

**Issue by abhijitkumarbiswas** [Microsoft/vscode#41264] opened 2018-01-08 04:46 UTC
Please add spelling check feature inside the vs code

**Comment by usernamehw** [comment] 2018-01-08 05:09
https://marketplace.visualstudio.com/search?term=spell&target=VSCode&category=All%20categories&sortBy=Relevance

Or duplicate of https://github.com/Microsoft/vscode/issues/20266

**Closed** 2018-01-08 05:32 UTC
Labels: *duplicate
