### ISSUE TITLE
Can't open launch.json

### ISSUE THREAD

**Issue by daydaystar** [Microsoft/vscode#70609] opened 2019-03-16 09:31 UTC
Issue Type: <b>Bug</b>

1.Click on the gear
2.Ctrl + Shift + p
3.Click the options
None of the above is valid

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.32.4

</details>

**Comment by roblourens** [comment] 2019-03-16 18:43
Please give more details. I don't understand what the problem is.

**Comment by daydaystar** [comment] 2019-03-17 05:47
I click the gear button and the profile should pop up but nothing happened,my debug profile doesn't open.I reinstalled vscode, but the problem still exists.

**Comment by isidorn** [comment] 2019-03-18 09:53
I have no clue what you are saying.
1. Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
2. If yes please attach a .gif video showing the problem
3. Write nice reproducable steps

**Comment by daydaystar** [comment] 2019-03-19 06:35
1.Vscode insiders is ok!

2.That's it,
![1552977154674](https://user-images.githubusercontent.com/23712342/54585094-22056d00-4a54-11e9-9749-7833f0e80608.gif)
![1552975900863 (3)](https://user-images.githubusercontent.com/23712342/54584647-e7e79b80-4a52-11e9-9199-cf33bea9c804.gif)

3.I don't know the steps

**Comment by isidorn** [comment] 2019-03-19 08:36
If vscode insiders is ok than that means this is fixed. So closing

**Closed by isidorn** 2019-03-19 08:36 UTC
Labels: debug, needs more info
