### ISSUE TITLE
Expand settings pane to all editor groups

### ISSUE THREAD

**Issue by dmlemos** [Microsoft/vscode#28540] opened 2017-06-12 15:28 UTC
- VSCode Version: 1.13.0
- OS Version: macOS 10.12.5

Usually I have 2 editor groups opened, so when I open settings it only uses one of the groups, making it difficult to edit. The settings pane has already two sections so you can imagine the trouble to make changes to it.

<img width="1626" alt="screen shot 2017-06-12 at 16 25 41" src="https://user-images.githubusercontent.com/1868454/27041429-dba53044-4f8b-11e7-875a-eb6ce05db696.png">

Having used SublimeText, I think they got this right. The default behaviour should be to open settings as if there is only one editor group, or at least open in a new window:

<img width="1623" alt="screen shot 2017-06-12 at 16 27 11" src="https://user-images.githubusercontent.com/1868454/27041483-08498e88-4f8c-11e7-922f-5101bf89c9cc.png">

**Comment by ramya-rao-a** [comment] 2017-06-12 19:49
cc @bpasero for editor group , @sandy081 for settings

**Comment by sandy081** [comment] 2017-08-25 15:22
@bpasero Not sure if we can provide an option to hide other groups when settings editor is open?

**Comment by bpasero** [comment] 2017-08-25 15:32
I think we should only consider that if we make the settings editor a true separate thing which is on top of all other things. For example in Sublime, it is true that settings covers everything, but that is only because settings opens in its own Window. Nothing is changed in the editor layout of where you came from.

**Comment by dmlemos** [comment] 2017-08-26 15:23
I'd like the option to open in a new window.

**Comment by sandy081** [comment] 2017-11-17 15:05
Duplicate of #16732

**Closed** 2017-11-17 15:05 UTC
Labels: *duplicate, feature-request, settings-editor
