### ISSUE TITLE
Don't enter a newline when pressing return on an auto-completion keyword which has been completed

### ISSUE THREAD

**Issue by Jarrio** [Microsoft/vscode#26503] opened 2017-05-12 03:15 UTC
- VSCode Version: `1.12`
- OS Version: Windows 10

Steps to Reproduce:

1. Type in a complete `keyword` which brings up an auto-completion prompt
2. Press `Enter`

In my experience, IDE's tend to just close out the auto-completion box in this scenario. It seems quite unusual to have it input a newline in this situation.

Gif of the issue:

![gif](https://cloud.githubusercontent.com/assets/748557/25980883/96f0b674-36c9-11e7-9e84-77d3a47a6b77.gif)

**Comment by jrieken** [comment] 2017-05-12 07:15
This is a dupe of https://github.com/Microsoft/vscode/issues/24420. This isn't an easy topic as it seems, please join the discussion.

In short, to re-store the old enter behaviour add this to your `keybindings.json`

```json
{
  "key": "enter",
  "command": "acceptSelectedSuggestion",
  "when": "editorTextFocus && suggestWidgetVisible"
}
```

**Closed by jrieken** 2017-05-12 07:15 UTC
Labels: suggest
