### ISSUE TITLE
Can't copy and paste the file list of a directory anymore

### ISSUE THREAD

**Issue by vpoguru** [microsoft/vscode#147863] opened 2022-04-21 16:16 UTC
Issue Type: <b>Bug</b>

I used to be able to select the contents of a directory in a macOS Finder window and paste the file list into VSCode. This no longer works. I have to copy and paste the file list into BBEdit and from there into VSCode.

I have disabled all extensions. An extension does not seem to be the culprit.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

**Comment by JacksonKearl** [comment] 2022-04-21 17:20
Likely duplicate of #146770.

**Closed by JacksonKearl** 2022-04-21 17:20 UTC
