### ISSUE TITLE
Include test gutter icons in sticky scroll

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#186166] opened 2023-06-26 14:41 UTC
Moved from https://github.com/Dart-Code/Dart-Code/issues/4610.

It'd be really nice for CodeLens and test icons to show up in sticky scroll:

![stick_code_lens_tests](https://github.com/microsoft/vscode/assets/1078012/e807b9a3-ed32-4a91-9dc4-1b3d541d721e)

I see there's an existing issue about CodeLens at https://github.com/microsoft/vscode/issues/182949, so this request is for the test icons to appear there too (red arrow).

**Comment by aiday-mar** [comment] 2023-06-27 04:51
Hi thanks for filing the issue. There are indeed many issues concerning the addition of decorators into sticky scroll : decorators in the form of indentation lines, gutter icons, code lens text, background colors.  In other words making the sticky scroll lines resemble the editor lines. The idea is on the roadmap, but I am not sure when we will be addressing it.

**Comment by alefragnani** [comment] 2023-06-28 11:25
Hi @aiday-mar ,

 I just noticed the same issue with my Bookmarks extension, which adds gutter and line/background decorators. Good to know it is on the roadmap.

Thank you for your feedback!

**Comment by aiday-mar** [comment] 2023-12-05 08:30
/duplicate of https://github.com/microsoft/vscode/issues/186166

**Closed by aiday-mar** 2023-12-05 08:30 UTC
Labels: editor-sticky-scroll, editor-sticky-scroll-decorations
