### ISSUE TITLE
Syntax coloring bug on certain C++ preprocessor constructs

### ISSUE THREAD

**Issue by wjk** [Microsoft/vscode#20962] opened 2017-02-20 23:03 UTC
- VSCode Version: 1.9.1
- C/C++ extension version 0.10.1 (_installed, but disabled_)
- OS Version: macOS Sierra 10.12.3

### Steps to Reproduce:

See the below screenshot.

![cpptools screenshot](https://cloud.githubusercontent.com/assets/1915951/23144587/88f6f780-f796-11e6-8a46-d083f2c886e8.png)

In the above screenshot, the blue coloring of the preprocessor-macro value "leaks" into the rest of the document. There are two things I can do to avoid this:

1. Change line 13 to say `#define LLD_VERSION_STRING() LLD_MAKE_VERSION_STRING(...)`. The extra parentheses after the macro name cause the blue coloring to terminate at the end of the line.
1. Add a second preprocessor command (`#define`, `#if`, etc) after the line that causes the bug. This also causes the syntax coloring to reset.

I am not sure whether to file this issue here or at [vscode-cpptools](https://github.com/Microsoft/vscode-cpptools). While my issue is C++-related, it still occurs if the C/C++ extension is disabled. (I had to disable it because it was eating up way too much RAM for my project, and straining my MacBook. The RAM consumption is easily explainable, though; I am working on a very large, complex project, and VSCode must keep all of the symbols in memory, all at once.) If I should have filed it there instead, please notify me or just migrate the issue. Thanks!

**Comment by aeschli** [comment] 2017-02-21 11:09
duplicate of https://github.com/atom/language-c/issues/173

**Closed by aeschli** 2017-02-21 11:09 UTC
