### ISSUE TITLE
Visual studio code crashes every 2 mins

### ISSUE THREAD

**Issue by tonymk** [Microsoft/vscode#6877] opened 2016-05-25 14:01 UTC
- VSCode Version: 1.1.1
- OS Version: win 10 pro, version 1511, os build 10586.318

Steps to Reproduce:

1. Start visual studio
2. open folder
3. wait

Get an error msg, window has crashed We are sorry.....  You can reopen...

**Comment by DickvdBrink** [comment] 2016-05-25 14:08
What kind of workspace is it? How many files, which languages (eg php, typescript, c#)

**Comment by bpasero** [comment] 2016-05-26 07:42
@tonymk can you answer?

**Comment by tonymk** [comment] 2016-05-26 08:29
It crashes in both .net core and angular2 environments. Testing with single files now. Seems ok so far. Did try to run it in administrator mode, still crashed.

**Comment by tonymk** [comment] 2016-05-26 08:39
Deleted node_modules to test with fewer files, still crashes. with this stucture.

C:.
│   .gitignore
│   index.html
│   package.json
│   systemjs.config.js
│   tsconfig.json
│   typings.json
│
├───app
│   │   app.component.js
│   │   app.component.js.map
│   │   app.component.ts
│   │   main.js
│   │   main.js.map
│   │   main.ts
│   │
│   ├───components
│   │       clientcustomers.service.js
│   │       clientcustomers.service.js.map
│   │       clientcustomers.service.ts
│   │
│   ├───models
│   └───services
└───typings
    │   index.d.ts
    │
    └───globals
        ├───core-js
        │       index.d.ts
        │       typings.json
        │
        ├───jasmine
        │       index.d.ts
        │       typings.json
        │
        └───node
                index.d.ts
                typings.json

**Comment by bpasero** [comment] 2016-05-26 08:52
@tonymk are you able to share the workspace with us that crashes and list the exact installed extensions that you have?

**Comment by tonymk** [comment] 2016-05-26 09:01
I just found out how to avoid it from crashing, i noticed a 99+ on the side bar at the git symbol. And it shortly crashed after. So i disabled git. and it is not crashing anymore. Not sure how that works, since the folder i opened does not have a git repository. 

As for extensions: C#, Angular2 snippets by balram, gitignore by codeZombie.

**Comment by weinand** [comment] 2016-05-26 09:54
@joaomoreno any idea if/how git could be involved here?

**Comment by tonymk** [comment] 2016-05-26 10:35
Found the problem, there turned out to be a .git file in c:\. (Sigh) So when there was not any .git file in the folder that was opened. It got overloaded with too many files and crashed.

**Comment by joaomoreno** [comment] 2016-05-26 13:05
Glad you found the hidden `.git` folder. Closing as a duplicate of #4805.

**Closed by joaomoreno** 2016-05-26 13:05 UTC
Labels: duplicate, freeze-slow-crash
