### ISSUE TITLE
Schemed filepaths support regression

### ISSUE THREAD

**Issue by merceyz** [microsoft/vscode#105014] opened 2020-08-19 17:30 UTC
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode/pull/94986 added support for creating VsCodeResource for schemed filepaths while https://github.com/microsoft/vscode/commit/3841f78377fc02ab5ef514cbd0fa760ed4ac6f0d regresses it.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment] 2020-08-20 18:03
This is what I was afraid of with #94986. We don't test this code path and don't have any insights into when it breaks. 

The change in 3841f78 enabled JS/TS single file intellisense for all schemes which has been a requested feature. If someone puts together a fix that doesn't regress 3841f78 and isn't super complex we would take it but I'm not going to investigate fixing this from the VS Code side

**Comment by arcanis** [comment] 2020-09-03 09:06
@mjbvz Can you share some context on 3841f78377fc02ab5ef514cbd0fa760ed4ac6f0d? I have a few questions:

- You mention that this commit intends to add intellisense support for all schemes - shouldn't that mean that `zip:` should be supported too, since it's a scheme like any other? Could this bug be more general than just zip?

- How is this particular commit expected to fix intellisense? In particular, it looks to me it'll turn all `scheme:/foo/bar` paths into `Uri.file` instances, meaning that they would [loose their schemes in favor of `file:`](https://github.com/microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L168), regardless of the scheme. If this is the expected behavior, what makes TS aware of the files (for instance, in our case TS throws errors saying that the file can't be loaded; is it different for the other schemes)? Just trying to make sure I don't regress your work either 😄

- I think we'd be happy to write tests, but I'm not sure how they are written in this codebase. Do you have some pointers? Would unit tests suffice?

**Comment by mjbvz** [comment] 2020-09-03 20:57
1. We treat all non `file:` schemed files as being in-memory. This prevents TS from trying to look up imported file (since it cannot read them from disk). After the change, the path we send to TS will look something like: `^scheme:/path/to/file.js`

1. 3841f78 was only part of the larger change. It specifically is part that strips off the `^`. 

Try updating your code to see if you can use the new logic. For example, you may be able to look for `^zip:/path/to/file` style paths in the TS server.

**Comment by merceyz** [comment] 2020-09-03 21:46
@mjbvz Thanks for the details, made it really obvious what the fix was, this can be fixed on our side without any changes in VSCode https://github.com/yarnpkg/berry/pull/1799 :+1:

**Comment by mjbvz** [comment] 2020-09-04 01:50
Glad you were able to fix this on your side! Closing this issue then

Please make sure to use VS Code insiders to test out the latest JS/TS changes and so you can detect if they cause any earlier on

**Closed by mjbvz** 2020-09-04 01:50 UTC
Labels: help wanted, javascript, typescript
