### ISSUE TITLE
[html] syntax highlighting broken if there is a syntax error in the style tag

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#13112] opened 2016-10-01 03:56 UTC
- VSCode Version: 1.6.0-insider 602155b
- OS Version: Windows 10

Steps to Reproduce:
1. When I use the `style` tag, it does not seem to respect the limit `<style> </ style>`.

![gif](https://cloud.githubusercontent.com/assets/19866231/19011582/5d903f6a-8771-11e6-8111-b94922662081.gif)
1. The same does not happen in the stable version 1.5.3 

![capturar2222](https://cloud.githubusercontent.com/assets/19866231/19011583/66f65c92-8771-11e6-826b-fff663027820.JPG)

No installed extensions.

**Comment by aeschli** [comment] 2016-10-10 10:00
duplicate of #8928

**Comment by Tekbr** [comment] 2016-10-11 11:43
@aeschli This case is different. I see the gif that when I leave only .body the tag style it is interfering in any html code.
About this case referenced I know it's an old problem VSCode.

The problem remains in the stable version 1.6.0 and version 1.7.0 insidider. This problem did not happen in version 1.5.3.

**Comment by Tekbr** [comment] 2016-10-21 14:48
@aeschli So you can see the difference?

**Comment by aeschli** [comment] 2016-10-21 15:40
Oh, sorry, now see. It seems to be an issue of the grammar embedding.

**Comment by aeschli** [comment] 2017-02-01 15:54
Atom has the same problem, so it's a problem of the grammar.

**Comment by aeschli** [comment] 2017-09-13 08:54
duplicate of #20488

**Closed** 2017-10-04 14:22 UTC
Labels: bug, languages basic

**Comment by Tekbr** [comment] 2017-10-09 17:47
-- Sorry for the English, I used Google Translator --

@aeschli Although you have identified the problem the longest, issue #20488 is rather a duplicate of this. :stuck_out_tongue: 😆
