### ISSUE TITLE
Extension count in not working properly

### ISSUE THREAD

**Issue by indahud** [microsoft/vscode#109725] opened 2020-10-30 09:14 UTC
- VSCode Version: 1.49.1
- OS Version: Linux x64 5.8.16-2-MANJARO

Steps to Reproduce:

1. Go to any extension of your choice
2. Install count is less than marketplace count.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tamuratak** [comment] 2020-10-30 10:02
Duplicate of #109365 and #107997. See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Closed** 2020-10-30 14:22 UTC
