### ISSUE TITLE
June release breaks auto-resizing grouped editors

### ISSUE THREAD

**Issue by skullk1d** [Microsoft/vscode#54361] opened 2018-07-16 02:20 UTC
Issue Type: <b>Bug</b>

Open two columns of editors in the workbench.
Resize one column to minimum width.
Click on the smaller column.

I expect the smaller column to auto-expand as usual, but since June release it doesn't. I have to manually resize each column every time. Please fix or point me to a setting for this.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
JSDocTagComplete|Hoo|0.0.2
vscode-docker|Pet|0.0.27
snapshot-tools|asv|0.0.7
scratchpad|awe|0.1.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
xml|Dot|2.3.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
vsc-material-theme|Equ|2.3.0
flow-for-vscode|flo|0.8.2
code-runner|for|0.9.3
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
python|ms-|2018.6.0
Go|ms-|0.6.84
sublime-keybindings|ms-|4.0.0
ide-purescript|nwo|0.19.0
language-purescript|nwo|0.1.2
material-icon-theme|PKi|3.5.1
sass-indented|rob|1.4.9
elm|sbr|0.18.0
python|tht|0.2.3
vscode-todo-highlight|way|0.5.12

(3 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2018-07-16 05:38
Duplicate of #51614

It's already done in the insiders builds, and will ship with next release.

**Closed** 2018-07-16 14:39 UTC
Labels: *duplicate, new release
