### ISSUE TITLE
Long Delay When Breakpoint Hit After VS Code Update

### ISSUE THREAD

**Issue by as185386** [microsoft/vscode#123315] opened 2021-05-07 17:36 UTC
Issue Type: <b>Performance Issue</b>

VS Code just updated to the latest version.  Now, when debugging a React app, there is a much longer delay when a breakpoint is hit before I can view or do anything in VS Code than there was before the update.  It is taking a minute or two before the UI becomes responsive which is very disruptive when debugging.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.91GB free)|
|Process Argv|--crash-reporter-id 9dc68548-dd88-491e-8477-4e0dd201a134|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    84	 13096	code main
    0	    27	  7904	   utility
    1	    49	  9160	   window (Issue Reporter)
    0	    69	 14580	   shared-process
    0	    35	 12560	     "C:\Users\as185386\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\as185386\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.pwa-msedge "{\"common.vscodemachineid\":\"889aa20947a25e654c07ca305cd44d48de113be13fde6f497dcf2269fd319e9d\",\"common.vscodesessionid\":\"546bcf09-ffcf-4804-89a9-add33b3e3fd61620408336507\"}" AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	    31	 22220	     ptyHost
    0	     6	 20488	       console-window-host (Windows internal process)
    0	    75	 20536	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    13	 23468	         C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" run start"
    0	    29	 14604	           "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" run start
    0	    13	 18192	             C:\WINDOWS\system32\cmd.exe /d /s /c react-scripts start
    0	    22	 14864	               electron_node react-scripts.js 
    0	   334	  5036	                 "C:\Program Files\nodejs\node.exe" C:\Development\NPS-Configuration-Manager\src\node_modules\react-scripts\scripts\start.js
    5	   343	 11916	                   "C:\Program Files\nodejs\node.exe" --max-old-space-size=2048 C:\Development\NPS-Configuration-Manager\src\node_modules\fork-ts-checker-webpack-plugin\lib\service.js
    1	   252	 21144	   gpu-process
    0	   251	 23456	   window (EditLane.tsx - src - Visual Studio Code)
    0	    32	 20556	     searchService
    0	   217	 23396	     extensionHost
    0	    39	 21320	       electron_node server.js 
    0	    92	 24640	       electron_node eslintServer.js 
    0	   120	 24900	       electron_node ms-vscode.js 
    0	    25	 16660	         window (undefined)
    0	     7	 17420	         crashpad-handler
    0	    19	 19372	         utility
    0	   153	 23656	         gpu-process
    1	   718	 24176	         window (undefined)
    0	    33	 26132	         utility
    0	   244	 25448	       electron_node tsserver.js 
    0	    44	  2348	         electron_node typingsInstaller.js typesMap.js 
    0	    30	 25512	       "C:\Users\as185386\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\as185386\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=23396
    0	    70	 25888	       electron_node tsserver.js 
    0	    14	 26496	     watcherService 
    0	    12	  9344	       console-window-host (Windows internal process)
    0	    13	 24996	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (EditLane.tsx - src - Visual Studio Code)
|    Folder (src): 245 files
|      File types: ts(63) tsx(62) png(17) json(12) jpg(9) map(5) js(4) txt(3)
|                  jpeg(3) ico(2)
|      Conf files: launch.json(1) tasks.json(1) package.json(1)
|                  tsconfig.json(1)
|      Launch Configs: pwa-msedge docker;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.20
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
color-the-tag-name|jzm|0.19.8
git-graph|mhu|1.30.0
import-sorter|mik|3.3.1
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
remote-containers|ms-|0.177.0
env-cmd-file-syntax|Nix|0.2.2
material-icon-theme|PKi|4.6.0
vscode-javascript-booster|sbu|14.0.1
sass-indented|syl|1.8.16

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes516:30244333
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by as185386** [comment] 2021-05-07 19:16
Just to provide more info, I reverted back to version 1.55.2 and, when I hit a breakpoint, the UI is almost instantly responsive.  Thanks!

**Comment by isidorn** [comment] 2021-05-07 20:44
I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by avenmore** [comment] 2021-05-09 18:34
I'd guess this is a duplicate of #123257, a possible regression of issue mentioned in #116865, #116615, #117162, (and more) which were closed as duplicates of #114459. It is back with this build for me too.

**Comment by isidorn** [comment] 2021-05-10 07:16
@avenmore thanks, let close as duplicate and we will probably soon reopen the root cause issue

**Comment by isidorn** [comment] 2021-05-10 07:32
@as185386 can you reproduce if you start vscode with
`code --disable-features=CalculateNativeWinOcclusion <path to workspace/folder> `

**Comment by isidorn** [comment] 2021-05-10 08:23
Let's close as duplicate of https://github.com/microsoft/vscode/issues/123257
Please follow that issue for more details

@as185386 also if you can try running VS Code with the flag would be great. Thanks

**Closed by isidorn** 2021-05-10 08:23 UTC
Labels: debug, needs more info
