### ISSUE TITLE
Relative links to local files in comments don't work

### ISSUE THREAD

**Issue by zombie** [microsoft/vscode#201408] opened 2023-12-22 14:58 UTC
Type: <b>Bug</b>

Steps to Reproduce:

1. Add a relative link to a file from the same project in a plain comment or a JSDoc @link tag: `// file://./package.json`
2. Ctrl-click the link.
3. Error: Unable to open 'package.json'.  [...] file was not found.

Apparently support for this was added (or fixed) in #90848 three years ago, but it looks like it regressed.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.59GB (2.75GB free)|
|Process Argv|--crash-reporter-id 49d984e9-51d6-49d3-a0ff-9efc64b54dd8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.143.0
copilot-chat|Git|0.11.1
hg|mrc|1.9.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
idl|myt|0.3.1
autotrim|Nat|1.0.6
lit-plugin|run|1.4.1
cody-ai|sou|1.0.4
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by mjbvz** [comment] 2024-02-08 00:46
Duplicate of https://github.com/microsoft/TypeScript/issues/47718

[#90848](https://github.com/microsoft/vscode/issues/90848) is the clickable links rendered in the document itself. I don't  think we've ever supported this syntax for rendering `@link` in hovers and suggestions so it's likely not a regression

**Closed by mjbvz** 2024-02-08 00:46 UTC

**Comment by zombie** [comment] 2024-02-08 22:02
@mjbvz I'm not sure if I'm missing something, but the STR from #90848 doesn't work for me (as I mentioned "in a plain comment").

```
/**
 * Pretty things file://./package.json
 * Pretty things file:///./package.json
 */
```

Both of these render as a link for me: 
![vscode-relative-links](https://github.com/microsoft/vscode/assets/207002/11c717b0-e4da-4e69-becb-afabe5e772dc)

but if I ctrl-click them, I get the `Unable to open "package.json"` error:
![vscode-relative-error](https://github.com/microsoft/vscode/assets/207002/bf8f23a7-e4e5-4507-b9d0-b5a8021bbe2b)

Not sure what's happening, am I missing some configuration to enable this to work as intended?
