### ISSUE TITLE
run a file create duplicate cmd messages.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#129386] opened 2021-07-26 10:23 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.58.2
- OS Version: win10 20h2

Steps to Reproduce:

1. set `terminal.integrated.defaultLocation` to `editor`
2. try run a file.

https://user-images.githubusercontent.com/26390254/126973897-54a95e89-5bf8-46c4-9fa4-b638a19da1b2.mp4

**Comment by meganrogge** [comment] 2021-07-26 17:30
Can you please explain in words what you're expecting and what the actual behavior is?

**Comment by byehack** [comment] 2021-07-26 18:28
https://user-images.githubusercontent.com/26390254/126973897-54a95e89-5bf8-46c4-9fa4-b638a19da1b2.mp4

look at 0:50 of video.
there is a extra printed:
```
Microsoft Windows [Version 10.0.19042.1083]
(c) Microsoft Corporation. All rights reserved.

E:\projects\iChests>
```
at first of terminal.
it shouldn't happen.

**Comment by Tyriar** [comment] 2021-07-27 16:46
This is fixed in insiders, was caused by the `show` ext api always showing the panel

/duplicate

**Closed by Tyriar** 2021-07-27 16:46 UTC
Labels: needs more info
