### ISSUE TITLE
Distinguish mirror cursors in HTML files

### ISSUE THREAD

**Issue by abhnvkmr** [microsoft/vscode#86947] opened 2019-12-13 16:51 UTC
Visual Studio Code 1.41 November update introduced mirror cursors in HTML files. I really love this feature which allows us to rename a tag without any command or third-party extensions. But when the cursor is at a tag, there is no distinction between the two cursors.

It's not an issue if I'm in an editing flow but coming back from a break or distraction, it's hard to know where the cursor will be when it gets out of the tag.

**Comment by octref** [comment] 2019-12-13 17:41
Duplicate of #85630.

**Closed by octref** 2019-12-13 17:41 UTC
