### ISSUE TITLE
Code helper issue cpu issue...

### ISSUE THREAD

**Issue by leozhao0709** [Microsoft/vscode#25759] opened 2017-05-02 06:01 UTC
- VSCode Version: 1.11.2
- OS Version: macOS Sierra

I am doing some angular project, and when I have this, it result in code helper run really high cpu percentage. The code is looks like 
`<app-project *ngFor="let prj of projects; let i = index" [project]="prj" [ngClass]="{marked: markedPrjIndex === i, inactive: prj.status === 'inactive'}" (statusUpdated)="onStatusUpdated($event, i)"
      (projectDeleted)="onProjectDeleted(i)" (click)="markedPrjIndex = i"></app-project>`

when I edit the [ngclass] part, it result in this issue.

I tried ps -eo pcpu,user,pid,command | grep Code, it gives this:

```
0.0 root               347 /System/Library/Frameworks/Security.framework/Versions/A/XPCServices/com.apple.CodeSigningHelper.xpc/Contents/MacOS/com.apple.CodeSigningHelper
  0.1 lzhao            15739 /Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_2572916
  0.0 lzhao            15743 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=gpu-process --channel=15739.0.1442984189 --mojo-application-channel-token=EB6675B90D207ED4CD3779721CF33309 --no-sandbox --supports-dual-gpus=true --gpu-driver-bug-workarounds=18,20,40,51,52,56,58,66,67,71,73,75 --gpu-vendor-id=0x1002 --gpu-device-id=0x6821 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x0d26 --gpu-active-vendor-id=0x1002 --gpu-active-device-id=0x6821
  0.0 lzhao            15747 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=39AFD331A4AE17E8CA23489651AABB93 --lang=en-US --node-integration=true --hidden-page --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=109715975133DFA50A59FA22741995DC --mojo-application-channel-token=39AFD331A4AE17E8CA23489651AABB93 --channel=15739.2.220945468
  0.0 lzhao            16136 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --database=/var/folders/28/xvf4mwws7dv8fq8s7875qs1493qdrk/T/VSCode Crashes --url=https://ticinocrashreporter.azurewebsites.net/crash --handshake-fd=65
  0.0 lzhao            90687 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=688EB2EECF9B88B991C19C09BCA167C2 --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=C26CFE056C954D890AA6FEEE2649C439 --mojo-application-channel-token=688EB2EECF9B88B991C19C09BCA167C2 --channel=15739.64.1158856004
100.0 lzhao            90697 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
  0.0 lzhao            90698 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
  0.0 lzhao            90701 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/28/xvf4mwws7dv8fq8s7875qs1493qdrk/T/vscode-tscancellation-14b3dc9b8c86f64730c6.sock*
  0.0 lzhao            90702 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
  0.0 lzhao            90722 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/lzhao/Library/Caches/typescript --enableTelemetry
  0.0 lzhao            90827 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html/node_modules/vscode-languageclient/lib/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html/server/out/htmlServerMain.js --node-ipc
  0.0 lzhao            90828 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/lzhao/.vscode/extensions/Angular.ng-template-0.1.3/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/lzhao/.vscode/extensions/Angular.ng-template-0.1.3/server/server.js --node-ipc
  0.0 lzhao            90829 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/lzhao/.vscode/extensions/mkaufman.HTMLHint-0.3.3/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/lzhao/.vscode/extensions/mkaufman.HTMLHint-0.3.3/server/server.js
  0.0 lzhao            91236 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn Code
```

Looks this result in the issue:
100.0 lzhao            90697 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost

any help?

**Comment by mjbvz** [comment] 2017-05-02 16:47
Does this only occur when working with angular projects?  The angular extension is tracking a few bugs that sound similar:

https://github.com/angular/vscode-ng-language-service/issues/32
https://github.com/angular/vscode-ng-language-service/issues/69
https://github.com/angular/vscode-ng-language-service/issues/73

Some of these may be fixed by 0.1.3

**Comment by leozhao0709** [comment] 2017-05-02 17:39
Thanks for your responding. 

But seems it's not the ng-language-service issue. I disabled all my angular related extension, but it still have this problem. 

I think it's only occur in angular [ngClass] directive, when you have several classes in this directive, it will have this problem.

**Comment by mjbvz** [comment] 2017-05-02 17:47
@leozhao0709 Does this still happen if you disable all extensions by running code with the `--disable-extensions` command line flag?

**Comment by leozhao0709** [comment] 2017-05-02 18:00
@mjbvz it's not happen again if I use the disable-extensions flag to disable all the extension.

Then I test all my current extension, seems it's a bug for the **auto rename tag** extension. It not happen again If I just disable this extension.

Thanks so much!

**Comment by mjbvz** [comment] 2017-05-02 18:49
Glad you found the root cause. 

Closing this since it seems to be caused by an extension

**Closed by mjbvz** 2017-05-02 18:49 UTC
Labels: caused-by-extension, freeze-slow-crash, javascript, needs more info
