### ISSUE TITLE
Large yaml file cannot be opened in new release 1.62.0

### ISSUE THREAD

**Issue by aihua5** [microsoft/vscode#136639] opened 2021-11-08 00:55 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by aihua5** [comment] 2021-11-08 00:58
Does this issue occur when all extensions are disabled?: Yes

版本: 1.62.0 (system setup)
提交: b3318bc0524af3d74034b8bb8a64df0ccf35549a
日期: 2021-11-03T15:23:01.379Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:
1. In 1.61, the large yaml file(>12m) can be opened,
2. in 1.62, the same file cannot be opened.

**Comment by IllusionMH** [comment] 2021-11-08 13:56
/needsMoreInfo

Do you see any error or what is VS Code behavior when you try to open large files?

**Comment by SeanChao** [comment] 2021-11-09 08:13
I run into the same issue in the same version.

It seems that when opening a large file, the UI is blocked. I cannot click anything. After a while, it prompts that the window is not responding.

Rolling back to version 1.61, the issue does not exist.

**Comment by pgalbavy-itrs** [comment] 2021-11-09 10:34
I have a 26MB log file (generic log file, not YAML as per topic title) and see the same symptoms as above. I disabled all extensions, just in case, but no change. Increasing memory for large files to 16MB made no change, neither did the optimisations tick box. Used to work fine - going to rollback to 1.61 to test.

**Comment by Morilli** [comment] 2021-11-10 04:10
Can confirm having the same issue as above, but with a .txt file. vscode seems to freeze after a file exceeds a size of exactly 5 million bytes
Here is an example file that is exactly 5 million bytes long: [test.txt](https://github.com/microsoft/vscode/files/7509769/test.txt)
Trying to add any character to it in vscode or any other program will make vscode freeze and unable to edit or open the file.

As this completely destroys my workflow, I am forced to go back to 1.61.2 for the time being.

**Comment by xcap2000** [comment] 2021-11-10 16:36
> Can confirm having the same issue as above, but with a .txt file. vscode seems to freeze after a file exceeds a size of exactly 5 million bytes. Here is an example file that is exactly 5 million bytes long: [test.txt](https://github.com/microsoft/vscode/files/7509769/test.txt) Trying to add any character to it in vscode or any other program will make vscode freeze and unable to edit or open the file.
> 
> As this completely destroys my workflow, I am forced to go back to 1.61.2 for the time being.

The exact same thing is happening here.

**Comment by AlCalzone** [comment] 2021-11-11 07:32
Can confirm, the same is happening here. I frequently have to open log files which can easily go into the megabytes.
1.62.1 just freezes endlessly with the occasional question if the window should be restarted
1.61.2 opens the file instantly.

**Comment by winfij** [comment] 2021-11-11 19:09
Same here, when opening a large text file in 1.62.1 (with all extensions disabled) one cpu core jumps to 100% and the UI locks up until the app is closed.
Downgrading to 1.61.2 works fine.
If I load the big file in 1.61.2 and then upgrade to 1.62.1 it hangs on startup after auto-loading the big file.

**Comment by SeanChao** [comment] 2021-11-12 03:54
This is a duplicate of #136470 
Version 1.62.2 has fixed this issue

**Closed** 2021-11-12 09:37 UTC
Labels: needs more info
