### ISSUE TITLE
Right click will break VirtualBox with Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by meolic** [microsoft/vscode#84470] opened 2019-11-11 10:02 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

I have Win10 and VirtualBox with XUbuntu 18.04 LTS. I have Code on this Ubuntu. After the last update, right click anywhere in the editor break the whole virtual computer (illegal instruction).

**Comment by deepak1556** [comment] 2019-11-18 23:49
@meolic does this still repro if you do the following on latest stable `1.40.1` ?

```
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
```

**Comment by meolic** [comment] 2019-11-19 06:52
On Mon, 18 Nov 2019 15:52:11 -0800
Robo <notifications@github.com> wrote:

> @meolic does this still repro if you do the following on latest
> stable `1.40.1` ?
> 
> ```
> * Command Palette search for "Configure Runtime Arguments"
> * Set `disable-hardware-acceleration: true`
> * Restart
> ```
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/microsoft/vscode/issues/84470#issuecomment-555264527

Well, I looks better. I was able to produce PDF from Markdown using an extension
which was impossible without this fix.

Please note, that Code crashes even after I updated the proposed argument
and tried to close, but after the restart everything seem to be OK.

Best regards, Robert

**Comment by deepak1556** [comment] 2020-03-11 04:52
Thanks for confirming, closing this as duplicate of https://github.com/microsoft/vscode/issues/84745

Virtualbox bugs are linked at https://github.com/microsoft/vscode/issues/84745#issuecomment-561645280

**Closed by deepak1556** 2020-03-11 04:52 UTC
Labels: needs more info
