### ISSUE TITLE
peer config file for extenstion

### ISSUE THREAD

**Issue by woodgear** [microsoft/vscode#124804] opened 2021-05-28 05:13 UTC
you may add a lot of config in settings.json, for example to config [vscode vim](https://github.com/VSCodeVim/Vim),here is a example of my vscode config [my vscode setting](https://github.com/woodgear/s-config/blob/master/vscode/settings.json) which is 800 line now, and more extension i install, the more lines i will to add in settings.json, there is a duplicate issue https://github.com/microsoft/vscode/issues/74434 ,but have been closed, so i though i have to create a new feature request.
i do not know why but @sandy081  seems does not answer the question about how to deal the more and more long settings.json file, https://github.com/microsoft/vscode/issues/68386 have nothing relate to this question.
i also seen some people ask question in reddit [can_i_split_the_settingsjson_into_smaller_files](https://www.reddit.com/r/vscode/comments/gv6mpk/can_i_split_the_settingsjson_into_smaller_files/), and the short word "no" is strong enough to break our heart.

**Comment by sandy081** [comment] 2021-06-04 14:23
/duplicate

It is duplicate of #74434 and I see it was closed because of not providing info - which is not correct. I just closed that as out of scope and in favour of rich settings editor we have.

**Closed** 2021-06-04 14:24 UTC
Labels: *duplicate
