### ISSUE TITLE
Git diff decorations not showing in editor or Explorer

### ISSUE THREAD

**Issue by vncnth** [microsoft/vscode#213857] opened 2024-05-29 21:48 UTC
Type: <b>Bug</b>

Hi, I recently noticed that my editor and Explorer no longer show any Git decorations (i.e. the blue and green lines in the editor, "U" and "M" in the Explorer), even though Source Control detects changes and will show the diff.

I've tried uninstalling and reinstalling, as well as reinstalling a previous version of VS Code, to no avail.

Interestingly, I've noticed that the colors don't show when I open my file through my workspace in VS Code...

![not working](https://github.com/microsoft/vscode/assets/45691709/1d9ecbc3-711f-4374-a9d2-00c29f19c53a)

...but they do when I open the same file directly from Windows Explorer by dragging and dropping it into the VS Code editor section:

![working](https://github.com/microsoft/vscode/assets/45691709/ce33e784-0eb3-48c1-8603-681edfa482bc)

Can someone help me please?

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (2.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
gitlens|eam|15.0.4
rainbow-csv|mec|3.12.0
vscode-dotnet-runtime|ms-|2.0.5
mssql|ms-|1.22.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
oracledevtools|Ora|21.9.0
sas-lsp|SAS|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by lszomoru** [comment] 2024-05-30 12:42
@vncnth, are you able to reproduce the issue with the latest VS Code Insiders release (`v1.90`)? Thanks!

**Comment by vncnth** [comment] 2024-05-30 14:34
Hi @lszomoru, thanks for responding so quickly. Yes, I get the same issue with the latest VS Code Insiders release.

I hadn't included a screenshot of the Source Control / Explorer issue in my initial post so here it is - Source Control shows the files that have diffs, but the green/yellow highlights in the Explorer don't appear:

![image](https://github.com/microsoft/vscode/assets/45691709/c4d0c1ac-e199-47c7-8fe2-eeb1081dfa20)

Thinking back, I noticed that this issue first started after my VS Code auto-updated a few releases back and I received this prompt for the first time:

![image](https://github.com/microsoft/vscode/assets/45691709/a1591da4-d8c9-43a6-af8c-8b1c27628951)

I had clicked either "Yes" or "Always" and that's when this issue started happening.

Interestingly, when I look this setting up, it's set to "prompt," but I don't receive a prompt each time I open my workspace. Maybe something is wrong with how this setting functions?

![image](https://github.com/microsoft/vscode/assets/45691709/5525b313-4640-4c01-9647-546360898606)

**Comment by vncnth** [comment] 2024-06-07 15:10
Hi @lszomoru, I unintentionally closed this, but reopened it as it's still an issue. Do you have any updates?

**Comment by lszomoru** [comment] 2024-08-20 08:33
@vncnth, sorry for not getting back to you on this. Assuming that you are still able to reproduce this issue with the latest VS Code release could you please implement the following steps: 
1. Close all the tabs that you have opened in VS Code
2. Invoke the "Git: Show Git Output" command from the command palette. 
3. Click on the "Clear Output" action in the toolbar of the output window
4. Open the file that has changes from the Source Control window. 
5. Drag the file from Windows explorer
6. Share the contents of the git output window

**Comment by vncnth** [comment] 2024-08-27 20:10
Hi @lszomoru, thanks for following up. Oddly, I'm not able to open the file from my workspace and then separately by dragging and dropping from Windows Explorer anymore. When the file is already open in my Editor, dragging and dropping from Windows Explorer just takes me to the file that's already open in the Editor. But here's the log file anyway when I follow your steps. I replaced parts of my folder paths with "...":
[Log.txt](https://github.com/user-attachments/files/16768386/Log.txt)

Instead, what I'm noticing is that I don't see the highlights when I'm in my office and on my work network, while I do see the highlights when I'm working remotely and logged into my work's VPN.

**Comment by vncnth** [comment] 2024-09-12 14:43
Thanks @Augustindou, but installing 1.91.1, 1.92.0 and 1.92.1 didn't work for me. @lszomoru?

**Comment by lszomoru** [comment] 2024-09-19 15:18
Given that you have identified the two scenarios in which things work as expected and not work as expected I would like to dig in:
1. Can you check the following settings in both cases:
    * scm.diffDecorationsGutterVisibility
    * scm.diffDecorations
    * scm.diffDecorationsGutterWidth 
2. I would also like to ask you to come up with the minimal steps to reproduce the issue (ex: open a file), and collect the git log output for the two scenarios. It would be very important not to alter the path of files as I am suspecting that this is related to the workspace/file path.

**Comment by vncnth** [comment] 2024-09-24 14:08
Hi @lszomoru, here are my settings for those three items:

![image](https://github.com/user-attachments/assets/73a43534-e6e1-420e-8b42-852ef92e1c36)

As for the git log, is there a way I can share it with you privately? I don't want to share my company's filepaths publicly.

**Comment by lszomoru** [comment] 2024-10-04 08:29
@vncnth, could you please download and try the latest VS Code Insiders 1.95?
I have made some changes to the repository discovery for folders/workspaces that use a UNC path. Thanks!

**Comment by Augustindou** [comment] 2024-10-04 10:10
Hello @lszomoru, 

Sorry for the delay in my response, I've been quite busy during the past 2 weeks, here are some informations on my side

* Seems like the problem is not fully fixed in `1.92.1`, as I sometimes have to restart VSCode to make them appear, and I sometimes just give up :/
* Just spent some time changing versions, and it seems like 
  * `1.94.0` works
  * tried `1.92.2` again and it seems to work (this time, didn't work before)
  * `1.93.0` doesn't work
    * Cause doesn't seem to be the project side, as I created a minimal example with 1 file (line 1 is committed, lines 2 & 3 are not)
           ![image](https://github.com/user-attachments/assets/08d428eb-9193-4fb8-8518-c05b74f4d09b)
    * Here is what I believe is the git log after opening vscode (Bottom panel > Output > Git) for the dummy project I created
        ``` 
        2024-10-04 11:39:15.163 [info] [main] Log level: Info
        2024-10-04 11:39:15.163 [info] [main] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
        2024-10-04 11:39:15.255 [info] [main] Using git "2.39.0.windows.1" from "C:\Program Files\Git\cmd\git.exe"
        2024-10-04 11:39:15.255 [info] [Model][doInitialScan] Initial repository scan started
        2024-10-04 11:39:15.983 [info] > git rev-parse --show-toplevel [183ms]
        2024-10-04 11:39:16.097 [info] > git rev-parse --git-dir --git-common-dir [97ms]
        2024-10-04 11:39:16.102 [info] [Model][openRepository] Opened repository: c:\Users\Augustind'Oultremont\Documents\git-projects\git-diff-not-showing
        2024-10-04 11:39:16.105 [info] [Model][doInitialScan] Initial repository scan completed - repositories (1), closed repositories (0), parent repositories (0), unsafe repositories (0)
        2024-10-04 11:39:16.125 [info] [Git][getRemotes] No remotes found in the git config file
        2024-10-04 11:39:16.198 [info] > git config --get commit.template [82ms]
        2024-10-04 11:39:16.212 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/master refs/remotes/master [88ms]
        2024-10-04 11:39:16.366 [info] > git status -z -uall [148ms]
        2024-10-04 11:39:16.487 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/master refs/remotes/master [107ms]
        2024-10-04 11:39:16.592 [info] > git config --local branch.master.vscode-merge-base [98ms]
        2024-10-04 11:39:16.592 [warning] [Git][config] git config failed: Failed to execute git
        2024-10-04 11:39:16.690 [info] > git reflog master --grep-reflog=branch: Created from *. [91ms]
        2024-10-04 11:39:16.748 [info] > git check-ignore -v -z --stdin [104ms]
        2024-10-04 11:39:16.813 [info] > git symbolic-ref --short refs/remotes/origin/HEAD [115ms]
        2024-10-04 11:39:16.813 [info] fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
        2024-10-04 11:39:16.840 [info] > git ls-files --stage -- C:\Users\Augustind'Oultremont\Documents\git-projects\git-diff-not-showing\modified-file.txt [120ms]
        2024-10-04 11:39:16.848 [info] > git show --textconv :modified-file.txt [136ms]
        2024-10-04 11:39:16.930 [info] > git cat-file -s 70c379b63ffa0795fdbfbc128e5a2818397b7ef8 [83ms] 
        ```
    * The problem seems to come from this line (I guess ?), I get the same one every time I edit my file
        ```
        2024-10-04 11:45:46.756 [warning] [Git][config] git config failed: Failed to execute git
        ```
* For the settings, I didn't edit the default ones, here's a screenshot from my settings page
      ![image](https://github.com/user-attachments/assets/c8607409-6beb-45e2-aa12-5b5f20d0dc99)



Hope this helps & thanks for your work !

**Comment by lszomoru** [comment] 2024-10-04 10:23
@Augustindou, thanks for the information. Could you also check VS Code Insiders 1.95? Thank you!

**Comment by Augustindou** [comment] 2024-10-04 10:31
@lszomoru I updated my previous comment to add the git log for `1.94.0` (not sure you saw that).

Here's the log for `1.95.0` (insiders) installed with `winget install --id=Microsoft.VisualStudioCode.Insiders  -e`
```
2024-10-04 12:18:44.925 [info] [main] Log level: Info
2024-10-04 12:18:44.925 [info] [main] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2024-10-04 12:18:44.994 [info] [main] Using git "2.39.0.windows.1" from "C:\Program Files\Git\cmd\git.exe"
2024-10-04 12:18:44.994 [info] [Model][doInitialScan] Initial repository scan started
2024-10-04 12:18:45.897 [info] > git rev-parse --show-toplevel [869ms]
2024-10-04 12:18:46.263 [info] > git rev-parse --git-dir --git-common-dir [114ms]
2024-10-04 12:18:46.281 [info] [Model][openRepository] Opened repository: c:\Users\Augustind'Oultremont\Documents\git-projects\git-diff-not-showing
2024-10-04 12:18:46.288 [info] [Model][doInitialScan] Initial repository scan completed - repositories (1), closed repositories (0), parent repositories (0), unsafe repositories (0)
2024-10-04 12:18:46.312 [info] [Git][getRemotes] No remotes found in the git config file
2024-10-04 12:18:46.402 [info] > git config --get commit.template [101ms]
2024-10-04 12:18:46.417 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/master refs/remotes/master [106ms]
2024-10-04 12:18:46.520 [info] > git status -z -uall [94ms]
2024-10-04 12:18:46.529 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [96ms]
2024-10-04 12:18:46.627 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/master refs/remotes/master [84ms]
2024-10-04 12:18:46.717 [info] > git config --local branch.master.vscode-merge-base [82ms]
2024-10-04 12:18:46.718 [warning] [Git][config] git config failed: Failed to execute git
2024-10-04 12:18:46.799 [info] > git reflog master --grep-reflog=branch: Created from *. [75ms]
2024-10-04 12:18:46.885 [info] > git symbolic-ref --short refs/remotes/origin/HEAD [80ms]
2024-10-04 12:18:46.886 [info] fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
2024-10-04 12:18:46.886 [warning] [Repository][getDefaultBranch] Failed to get default branch details: Failed to execute git.
2024-10-04 12:18:46.932 [info] > git check-ignore -v -z --stdin [100ms]
2024-10-04 12:18:46.982 [info] > git ls-files --stage -- C:\Users\Augustind'Oultremont\Documents\git-projects\git-diff-not-showing\modified-file.txt [122ms]
2024-10-04 12:18:46.992 [info] > git show --textconv :modified-file.txt [140ms]
2024-10-04 12:18:47.090 [info] > git cat-file -s 70c379b63ffa0795fdbfbc128e5a2818397b7ef8 [100ms]
```

**Comment by lszomoru** [comment] 2024-10-24 12:37
> Any idea when this will get incorporated into the next VS Code update?

The next VS Code stable release is scheduled for next week.

**Closed by lszomoru** 2024-10-24 12:37 UTC
Labels: info-needed, git

**Comment by vncnth** [comment] 2024-10-24 14:17
Great, thank you so much!
