### ISSUE TITLE
Random reveal while searching

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#127453] opened 2021-06-29 12:56 UTC
Testing #127173

* preview README.md from our repo
* type `The ` and backspace a couple of times
* 🐛 when backspacing some random portion of the page is being revealed

https://user-images.githubusercontent.com/1794099/123800921-10c19100-d8ea-11eb-803d-60663fc7e76d.mov

**Comment by lramos15** [comment] 2021-06-29 14:21
I also see this just when searching in that it will hop to random places on the page even if they don't have results

**Comment by bamurtaugh** [comment] 2021-06-29 16:41
I believe I also experience this when hitting "Enter" several times. It travels through the first through results, but then seems to jump down unexpectedly:

![recording (23)](https://user-images.githubusercontent.com/25310137/123835712-bb6f8a80-d8bd-11eb-8c2d-ac2b6040f51c.gif)

**Comment by rzhao271** [comment] 2021-06-29 17:04
Oh this might have to do with the markdown document scrolling, causing the find widget to parse it as a content update and stopping the search.

**Comment by rzhao271** [comment] 2021-07-06 19:32
Duplicate of #127507.

**Closed by rzhao271** 2021-07-06 19:32 UTC
Labels: bug
