### ISSUE TITLE
Detect TypeScript version from `package.json` in multi-root workspace

### ISSUE THREAD

**Issue by rubengmurray** [microsoft/vscode#163079] opened 2022-10-08 21:42 UTC
I spend my time coding in multi-root workspaces. I find this makes things a lot easier for me navigating through related services.

However, in multi-root workspaces the version of TypeScript is not detected based on the relevant `package.json` of the file in view. This leads to mis-matches on what VS Code thinks will be a TS issue, rather than the TS version used in that project. 

For workspaces consisting of one project, VS Code automatically detects the version from `node_modules`, according to the docs:

https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions

Could this be extended to multi-root workspaces, looking for the closest `package.json` for the file in view, and switching the TypeScript version dynamically?

The current means of switching TypeScript version does not easily allow for the version of the file in view to be selected.

I tried making an extension to do this but I couldn't find an API that would allow me to get the version correctly based on the file change.

------

I searched for `typescript version package.json multi-root` for related issues.

I think these are related, but I'm not sure they're discussing exactly the same thing (one seems broader, and mentions `settings.json`, other mentions npm workspaces, but I'm not using `npm 7`)

https://github.com/microsoft/vscode/issues/134748
https://github.com/microsoft/vscode/issues/32693

**Comment by mjbvz** [comment] 2022-10-10 17:26
Duplicate of #147660

**Closed by mjbvz** 2022-10-10 17:26 UTC
