### ISSUE TITLE
How to show color in js file?

### ISSUE THREAD

**Issue by Jancat** [Microsoft/vscode#36965] opened 2017-10-26 09:16 UTC
I wrote color value in js file using with JSX syntax, and How can I see the color in the editor like in css file?

**Colors.js**

    const colors = {
      background: '#1F0808',
    }

**Comment by maxibanki** [comment] 2017-10-26 09:23
Looks similar to #36485

**Comment by mjbvz** [comment] 2017-10-26 18:51
Thanks, yes this is a duplicate of #36485

**Closed by mjbvz** 2017-10-26 18:51 UTC
Labels: duplicate, javascript
