### ISSUE TITLE
For-loop in JavaScript is colored turquoise/blue

### ISSUE THREAD

**Issue by JustGoscha** [Microsoft/vscode#4050] opened 2016-03-11 23:04 UTC
Here's an example:

![capture](https://cloud.githubusercontent.com/assets/791485/13717982/e8178412-e7e5-11e5-8b49-86b6774fb5c2.PNG)

Here's the code:
http://pastebin.com/gwSzquA0

The cause lies in the for loop declaration. It happens for `i<` , but not for `i <`, so the parser does something wrong there. Note the extra space.

**Comment by Tyriar** [comment] 2016-03-12 00:16
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by Tyriar** 2016-03-12 00:16 UTC
