### ISSUE TITLE
Mac OS download zip contains logs of signing?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6631] opened 2016-05-22 16:21 UTC
When I unzip Code for Mac I would expect just the application bundle and nothing else. What I see today is a folder containing a file `VSCode-darwin-stable-unsigned_log` with these contents:

```
Codesign Allocate:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
Using signature "%s" for applications, "%s" for installers.Developer ID Application: Microsoft CorporationDeveloper ID Installer: Microsoft Corporation
Job Mode:full
Unzipping "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned.zip"
All files that got unziped:2
Visual Studio Code.app
VSCode-darwin-stable-unsigned_log.txt
Apps Found:1
/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app
Pkg Found:0
Misc Found:0
Signing app at "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app".
Scanning path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app" for executables.
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib".
Codesign Succeeded. Verifying...
Codesign Verified./Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib".
Codesign Succeeded. Verifying...
Codesign Verified./Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crashpad_handler".
Codesign Succeeded. Verifying...
Codesign Verified./Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crashpad_handler
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt".
Codesign Succeeded. Verifying...
Codesign Verified./Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/Current".
Codesign Succeeded. Verifying...
Codesign Verified./Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/Current
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/Current".
Codesign Succeeded. Verifying...
Codesign Verified./Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/Current
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current".
Codesign Succeeded. Verifying...
Codesign Verified./Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/Current".
Codesign Succeeded. Verifying...
Codesign Verified./Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/Current
Signing path "/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app/Contents/F/Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app: accepted
source=Developer ID
origin=Developer ID Application: Microsoft Corporation (UBF8T346G9)
productbuild: Adding component at /Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.app
productbuild: Using timestamp authority for signature
productbuild: Signing product with identity "Developer ID Installer: Microsoft Corporation (UBF8T346G9)" from keychain ThalesCSS
productbuild: Adding certificate "Developer ID Certification Authority"
productbuild: Adding certificate "Apple Root CA"
productbuild: Wrote product to /Users/Shared/ManualSigning/PRA33113580/VSCode-darwin-stable-unsigned/Visual Studio Code.pkg
productbuild: Supported OS versions: [10.9.0, )
```

Imho that looks quite amateurish to me and we should just unzip to the application bundle without any files or folders inside.

/cc @joaomoreno

**Comment by chrisdias** [comment] 2016-05-23 03:54
dupe of https://github.com/Microsoft/vscode-distro/issues/43

**Closed by chrisdias** 2016-05-23 03:54 UTC
Labels: bug, important

**Comment by joaomoreno** [comment] 2016-05-24 06:48
Fixed.
