### ISSUE TITLE
Emmet Expansion of `php` has unexpected behavior in `.php` files

### ISSUE THREAD

**Issue by zackcote** [Microsoft/vscode#15592] opened 2016-11-16 21:30 UTC
- VSCode Version: Version 1.7.1 (1.7.1)
- OS Version: El Capitan 10.11.6 (15G1108)

Steps to Reproduce:

1. Open file with syntax set to php.
2. Type `php`, and press `Tab` to expand with Emmet

Expanding the string `php` with Emmet produces `<php></php>` instead of the far more helpful `<?php ?>`. I believe Sublime, Atom, etc. all address this and the `<?php ?>` expansion occurs.

**Comment by ramya-rao-a** [comment] 2016-11-16 22:18
@zackcote Are you trying this in a php file? Can you share your settings if any?

**Comment by ramya-rao-a** [comment] 2016-11-16 22:29
Closing as duplicate of #7913

**Comment by ramya-rao-a** [comment] 2016-11-16 23:00
If you want to disable the html like expansions in a php file inside the `<?php ?>` block, then add `"emmet.excludeLanguages": ["php"]` in your settings.
You can disable emmet expansions altogether by setting `"emmet.triggerExpansionOnTab":false`

If you are looking for php like expansions, then I believe that is not supported at the moment.

@mrmlnc Can you confirm?

**Comment by mrmlnc** [comment] 2016-11-16 23:06
@ramya-rao-a, yeap 👍

It seems to me that in Atom `<?php ?>` is just a snippet.

**Comment by ramya-rao-a** [comment] 2016-11-16 23:07
Thanks @mrmlnc

**Closed by ramya-rao-a** 2016-11-16 23:07 UTC
Labels: emmet

**Comment by ramya-rao-a** [comment] 2017-08-10 17:49
With the new Emmet improvements in VS Code 1.15, this is no longer a problem

Tab will no longer trigger Emmet, instead Emmet abbreviations will show up in suggestion/auto-completion list.

In this particular case, emmet will not provide any suggestions either

Please read more on what else is new at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

**Comment by yamenarahman** [comment] 2017-09-12 10:47
@ramya-rao-a What if I want only php abbreviations to be listed on suggestion/auto-completition list ?

**Comment by ramya-rao-a** [comment] 2017-09-12 14:32
@yamenarahman What do you mean by "only php abbreviations"?

**Comment by yamenarahman** [comment] 2017-09-12 15:29
@ramya-rao-a Sorry it's my bad, I figured out what was missed in my conf.

**Comment by ramya-rao-a** [comment] 2017-09-12 15:56
@yamenarahman No problem, Happy Coding!
