### ISSUE TITLE
When start vscode in cmd, there is remain a dos window

### ISSUE THREAD

**Issue by longtsing** [microsoft/vscode#210876] opened 2024-04-22 06:28 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: windows 10 22H2

Steps to reproduce:

1. Win+R opens the run window and runs the code command.
![image](https://github.com/microsoft/vscode/assets/1655769/56c5a249-676c-4964-829b-1c86a3cfd331)

3. vscode is opened, but a DOS window will remain in the foreground, and the DOS window needs to be closed manually.
![image](https://github.com/microsoft/vscode/assets/1655769/d8f0acf6-1637-4778-8ae6-d50537c01ebe)

5. Manually close vscode, and the dos window will also exit automatically.

It is same with https://github.com/microsoft/vscode/issues/70139

```[tasklist]
### Tasks
```

**Comment by longtsing** [comment] 2024-04-22 06:46
@yunxu1019 
@DonJayamanne

The issue is stayed long time. There is fix code that need to be merged. 
https://github.com/microsoft/vscode/pull/209315

**Comment by longtsing** [comment] 2024-04-29 01:27
@roblourens For developers using vscode, running code.cmd to start vscode is the more popular way. Therefore, this redundant DOS window is a problem that greatly affects the user experience. Please check this issue as soon as possible.
Thanks a lot.

**Comment by longtsing** [comment] 2024-05-04 14:01
@roblourens hello？May？

**Comment by longtsing** [comment] 2024-05-07 07:11
Keep leaving messages to keep the issue from being closed.

**Comment by longtsing** [comment] 2024-05-13 00:38
@roblourens  I need your hellp. May I have the honor to contributor for vscode?

**Comment by roblourens** [comment] 2024-05-13 21:27
Sorry for the delay but I think this is actually a dupe of https://github.com/microsoft/vscode/issues/66750

**Closed by roblourens** 2024-05-13 21:27 UTC
