### ISSUE TITLE
Problem with updating Extension

### ISSUE THREAD

**Issue by gep13** [Microsoft/vscode#418] opened 2015-11-21 17:49 UTC
I have just tried to update an installed extension, but the process seemed to hang.

I eventually decided to restart VS Code, and when I did, the extension in question was no longer installed.  I attempted to install it again, but the process never seemed to complete.  I did this a few times, each time opening/closing VS Code, and eventually, on I think the fourth attempt, the extension correctly installed.

Is this a known issue?  Are there any logs that I can provide to help identify the problem?

**Comment by mackenza** [comment] 2015-11-21 17:58
Which extension, what platform you are running on would probably help address your issue

**Comment by gep13** [comment] 2015-11-21 18:02
Ah, good point :+1: 

Running on Windows 8.1, and was trying to update this extension:

https://marketplace.visualstudio.com/items/odonno.pomodoro-code

**Comment by akamud** [comment] 2015-11-21 18:20
I had the same problem on Windows 8.1.

I checked the extensions folder after the first crash and I noticed the folder for the extension only had the icon file. I was trying to update this extension: https://marketplace.visualstudio.com/items/akamud.vscode-caniuse

**Comment by lukehoban** [comment] 2015-11-22 00:08
I've also seen failures to download all of the files for the extension during updates on Windows 10 several times.  I have not seen these failures on OS X.

**Comment by joaomoreno** [comment] 2015-11-24 08:51
Duplicate of #537

**Closed by joaomoreno** 2015-11-24 08:51 UTC
