### ISSUE TITLE
Native IW - (Minor issue for now) Menu's appear under the input box.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#129423] opened 2021-07-26 15:46 UTC
Not a huge deal, especially in this case since this would likely only be a problem if the cell is collapsed AND we continue to show the "choose mimetype" option (Bug #129420). But could be problematic in the future or in scenarios I'm not considering at the moment. 
![image](https://user-images.githubusercontent.com/11685408/127018471-c4721854-5ec2-4bfd-9249-e9ce8181f740.png)

**Comment by joyceerhl** [comment] 2021-07-26 16:10
Duplicate of https://github.com/microsoft/vscode/issues/127576

**Comment by rebornix** [comment] 2021-08-05 23:23
it's a duplicated

**Closed by rebornix** 2021-08-05 23:23 UTC
Labels: bug, *duplicate, interactive-window
