### ISSUE TITLE
Support proposed ES Next class-field and private method

### ISSUE THREAD

**Issue by wh1tecat-nya** [Microsoft/vscode#64674] opened 2018-12-09 03:06 UTC
pipe line operator is discussion now here https://github.com/Microsoft/TypeScript/issues/17718
but looks like not open discussion class-field and private method.

**Comment by mjbvz** [comment] 2018-12-12 00:20
Duplicate of https://github.com/Microsoft/TypeScript/issues/9950

**Closed by mjbvz** 2018-12-12 00:20 UTC
