### ISSUE TITLE
Extension viewlet is broken on Ubuntu

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8877] opened 2016-07-08 02:19 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

Related #8859

This is what I see when mousing over the extension viewlet

![image](https://cloud.githubusercontent.com/assets/2193314/16675600/5322ffd2-4477-11e6-830b-5b5355bad0d6.png)

<details>
<summary>There are a lot of errors in the console (click to toggle)</summary>
<pre>
Conflict detected, command `workbench.action.output.toggleOutput` cannot be triggered by ctrl+shift+h due to workbench.action.replaceInFiles
shell.ts:416Cannot read property 'version' of undefined: TypeError: Cannot read property 'version' of undefined
    at t.Object.defineProperty.get [as latestVersion] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:81:21735)
    at t.Object.defineProperty.get [as outdated] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:81:23158)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:105:4512
    at Array.reduce (native)
    at e.onServiceChange (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:105:4480)
    at e.invoke (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:37:16332)
    at e.fire (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:37:18116)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:81:24683
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:7416)
    at Object.W.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:10994)e.onUnexpectedError @ shell.ts:416
shell.ts:416Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23456),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ shell.ts:416
winjs.base.js:45WARNING: Promise with no error callback:4
winjs.base.js:46Object
winjs.base.js:45WARNING: Promise with no error callback:6
winjs.base.js:46Object
winjs.base.js:45WARNING: Promise with no error callback:8
winjs.base.js:46Object
mainThreadExtensionService.ts:96[/home/daniel/.vscode/extensions/ms-vscode.omnisharp-0.3.2]: Command `o.restart` appears multiple times in the `commands` section.
mainThreadExtensionService.ts:96[/home/daniel/.vscode/extensions/ms-vscode.omnisharp-0.3.2]: Command `o.pickProjectAndStart` appears multiple times in the `commands` section.
mainThreadExtensionService.ts:90[/home/daniel/.vscode/extensions/vscode-project-manager]: Cannot read file /home/daniel/.vscode/extensions/vscode-project-manager/package.json: ENOENT: no such file or directory, open '/home/daniel/.vscode/extensions/vscode-project-manager/package.json'.t.$localShowMessage @ mainThreadExtensionService.ts:90
threadService.ts:214[Extension Host] [/home/daniel/.vscode/extensions/ms-vscode.omnisharp-0.3.2]: Command `o.restart` appears multiple times in the `commands` section.
threadService.ts:214[Extension Host] [/home/daniel/.vscode/extensions/ms-vscode.omnisharp-0.3.2]: Command `o.pickProjectAndStart` appears multiple times in the `commands` section.
threadService.ts:214[Extension Host] [/home/daniel/.vscode/extensions/vscode-project-manager]: Cannot read file /home/daniel/.vscode/extensions/vscode-project-manager/package.json: ENOENT: no such file or directory, open '/home/daniel/.vscode/extensions/vscode-project-manager/package.json'.(anonymous function) @ threadService.ts:214
winjs.base.js:45WARNING: Promise with no error callback:9
winjs.base.js:46Object
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:28 [uncaught exception]: TypeError: Cannot read property 'publisher' of undefinedonError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:28
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:31 TypeError: Cannot read property 'publisher' of undefined
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27943
    at Array.every (native)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27908
    at Array.filter (native)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27880
    at i.Class.define.done (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:14123)
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:7558)
    at Object.W.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:10994)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12822)
    at i.Class.define._completed (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12263)onError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:31
winjs.base.raw.js:2036Uncaught TypeError: Cannot read property 'publisher' of undefined
winjs.base.js:45WARNING: Promise with no error callback:10
winjs.base.js:46Object
winjs.base.js:45WARNING: Promise with no error callback:11
winjs.base.js:46Object
keybindingResolver.ts:188Conflict detected, command `workbench.action.output.toggleOutput` cannot be triggered by ctrl+shift+h due to workbench.action.replaceInFiles
keybindingResolver.ts:188Conflict detected, command `editor.debug.action.toggleBreakpoint` cannot be triggered by f9 due to sortLines.sortLines
winjs.base.js:45WARNING: Promise with no error callback:12
winjs.base.js:46Object
winjs.base.js:45WARNING: Promise with no error callback:13
winjs.base.js:46Object
shell.ts:416Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ shell.ts:416
winjs.base.js:45 WARNING: Promise with no error callback:14
winjs.base.js:46 Object
shell.ts:416 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23456),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ shell.ts:416
winjs.base.js:45 WARNING: Promise with no error callback:15
winjs.base.js:46 Object
shell.ts:416 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ shell.ts:416
winjs.base.js:45 WARNING: Promise with no error callback:16
winjs.base.js:46 Object
winjs.base.js:45 WARNING: Promise with no error callback:17
winjs.base.js:46 Object
shell.ts:416 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23456),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ shell.ts:416
winjs.base.js:45 WARNING: Promise with no error callback:18
winjs.base.js:46 Object
winjs.base.js:45 WARNING: Promise with no error callback:19
winjs.base.js:46 Object
winjs.base.js:45WARNING: Promise with no error callback:20
winjs.base.js:46Object
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:28 [uncaught exception]: TypeError: Cannot read property 'publisher' of undefinedonError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:28
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:31 TypeError: Cannot read property 'publisher' of undefined
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27943
    at Array.every (native)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27908
    at Array.filter (native)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27880
    at i.Class.define.done (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:14123)
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:7558)
    at Object.W.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:10994)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12822)
    at i.Class.define._completed (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12263)onError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:31
winjs.base.raw.js:2036Uncaught TypeError: Cannot read property 'publisher' of undefined
shell.ts:416Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)
</pre>
</details>

It keeps repeating after this.

**Comment by joaomoreno** [comment] 2016-07-08 09:25
@Tyriar Can you reproduce out of sources?

**Comment by joaomoreno** [comment] 2016-07-08 10:15
Can you set a breakpoint in `extensionsWorkbenchService.ts:163` and trigger the bug? You can achieve this in the Developer tools, clicking `Ctrl-O` and typing `extensionsWorkbenchService` to find the file. I'm interested in the the contents of the `t` array, specifically if there are any extensions in there with an `undefined` `manifest` property:

![image](https://cloud.githubusercontent.com/assets/22350/16684470/850fc2da-4505-11e6-82ba-9dec9634600c.png)

**Comment by joaomoreno** [comment] 2016-07-08 13:19
- Shutdown Code
- Run `ps ax | grep code` in a terminal, do you see any Code process still running?

**Comment by joaomoreno** [comment] 2016-07-08 13:39
Duplicate of #8859

**Closed by joaomoreno** 2016-07-08 13:39 UTC
Labels: bug, candidate, extensions, important
