### ISSUE TITLE
No extensions showing

### ISSUE THREAD

**Issue by raph90** [Microsoft/vscode#57863] opened 2018-09-04 12:44 UTC
Issue Type: <b>Bug</b>

I can't browse and install extensions - search shows no results and there are no recommended results...

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.19GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_376924|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.17.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.5.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
es7-react-js-snippets|dsz|1.8.6
beautify|Hoo|1.4.2
vscode-colorize|kam|0.7.1
MagicPython|mag|1.0.12
python|ms-|2018.7.1
material-icon-theme|PKi|3.5.3
LiveServer|rit|5.1.1
hyper-javascript-snippets|t7y|2.0.0
vscodeintellicode|Vis|1.0.3
full-react-snippets|wal|1.1.2
jinja|who|0.0.8
html-css-class-completion|Zig|1.17.1

(3 theme extensions excluded)

</details>

**Comment by Gruntfuggly** [comment] 2018-09-04 12:46
The whole Marketplace is down - I don't think it's a bug in the software....

**Comment by Korbl** [comment] 2018-09-04 12:50
as @Gruntfuggly mentioned, the whole of https://marketplace.visualstudio.com/ is down.

**Comment by jinzongmin** [comment] 2018-09-04 12:50
![image](https://user-images.githubusercontent.com/11606489/45032338-2d7ae300-b084-11e8-837f-b18509602642.png)

**Comment by raph90** [comment] 2018-09-04 12:56
Got it, thanks guys. Hopefully it'll be back online soon...

**Comment by MLefebvreICO** [comment] 2018-09-04 13:28
Maybe adding an error message saying the server is down in the interface while searching could be a great.

FYI: Marketplace is down probably due to [VSTS' servers performance degrations](https://blogs.msdn.microsoft.com/vsoservice/?p=17405)

**Comment by enyo** [comment] 2018-09-04 13:51
Duplicate of #57851

**Closed** 2018-09-04 17:49 UTC
Labels: *duplicate, extensions
