### ISSUE TITLE
Decorators rendered incorrectly in docs codeblock preview

### ISSUE THREAD

**Issue by jdt3969** [microsoft/vscode#119218] opened 2021-03-18 00:45 UTC
- VS Code Version:
- OS Version:

Decorators aren't rendered correctly in preview. I would expect codeblock to not be modified

Steps to Reproduce:

<img width="500" alt="CleanShot 2021-03-17 at 17 27 28@2x" src="https://user-images.githubusercontent.com/8384749/111556076-f3a3f080-8746-11eb-8ea7-d3e8cc46e65a.png">
<img width="399" alt="CleanShot 2021-03-17 at 17 27 40@2x" src="https://user-images.githubusercontent.com/8384749/111556088-f999d180-8746-11eb-994c-1182dfd34adf.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2021-03-18 02:00
Duplicate of https://github.com/microsoft/TypeScript/issues/38922

**Closed by mjbvz** 2021-03-18 02:00 UTC
