### ISSUE TITLE
settings sync stopped working Version: 1.55.0-insider

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#118194] opened 2021-03-05 10:56 UTC
Issue Type: <b>Bug</b>

Version: 1.55.0-insider
Commit: 567b82a0f9c31bd463af64997997730c5d0173cc
Date: 2021-03-05T05:22:04.953Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

VS Code version: Code - Insiders 1.55.0-insider (567b82a0f9c31bd463af64997997730c5d0173cc, 2021-03-05T05:22:04.953Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|work/CM work/DI2Infrastructure work/DS9 work/SRE work/TF-Modules work/azuredevops work/datagenic work/gitlab work/terraform-provider|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
markdown-toc|Ala|1.5.6
inline-hasher|ale|1.1.0
spellright|ban|3.0.56
git-temporal-vscode|bee|1.0.0
better-toml|bun|0.3.2
hadolint|exi|1.0.1
terraform|has|2.7.0
markdown-shortcuts|mdi|0.12.0
azure-pipelines|ms-|1.183.0
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.10.0
azure-account|ms-|0.9.6
azurecli|ms-|0.5.0
vscode-yaml-sort|Pas|3.3.0
errorlens|Phi|1.1.3
git-file-history|pom|1.0.1
vscode-yaml|red|0.16.0
vscode-gitweblinks|red|2.3.0
vscode-nginx|sha|0.6.0
shellcheck|tim|0.13.2
azure-devops-yaml-pipeline-validator|Tom|1.7.0
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.1.0
jinja|who|0.0.8
json|Zai|2.0.2

</details>

**Comment by IllusionMH** [comment] 2021-03-05 11:32
/needsMoreInfo

Are you using MS account to sync? Looks like duplicate of #118171

**Comment by FernandoMiguel** [comment] 2021-03-05 11:39
> /needsMoreInfo
> 
> Are you using MS account to sync? Looks like duplicate of #118171

@IllusionMH it has been github account, i believe, since day one.
I do have a vague idea it initially was a very convoluted step.
but this morning on restart for insider updates it simply stop showing in sync, and kept showing a "loading.." below.
i just checked and now I see this
![image](https://user-images.githubusercontent.com/168366/110110910-6d32fa80-7da7-11eb-982e-e9fadce220af.png)
but it is still showing the blue alert

**Comment by MJECloud** [comment] 2021-03-05 11:47
I've got the same behaviour on windows after updating to 1.55.0-insider

![image](https://user-images.githubusercontent.com/22131101/110111617-ee42bf80-7db0-11eb-9e0f-da2ac3aa2570.png)

Version: 1.55.0-insider (user setup)
Commit: 567b82a0f9c31bd463af64997997730c5d0173cc
Date: 2021-03-05T05:22:52.277Z (6 hrs ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by sandy081** [comment] 2021-03-05 13:34
Fixed by bc62648b05c87ba814aa22f6f416f1cec96c1bf8

Sorry about this issue - Fixed it and triggered new insiders which will be available soon - will update.

**Closed by sandy081** 2021-03-05 13:34 UTC
Labels: bug, confirmed, important, settings-sync

**Comment by sandy081** [comment] 2021-03-05 17:11
Insiders with the fix is released.
