### ISSUE TITLE
VSCode theme development request help!

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#182961] opened 2023-05-19 12:48 UTC
VSCode theme development request help!
Excuse me, teachers! How to modify the border color and background color of the check box in the vscode popup window?
VSCode 1.78
Windows 10
I've taken screenshots of the checkbox images of the two popups as case illustrations:
![2023-05-19_111111111111](https://github.com/microsoft/vscode/assets/54253524/166dbe28-3bbe-4fed-b8f6-56ca0bb74cf3)
![2023-05-19_2222222222222](https://github.com/microsoft/vscode/assets/54253524/49413d7d-1f12-433b-aba8-36ea733c4b19)
Hope to get help from all the teachers! Thank you so much!

**Comment by aeschli** [comment] 2023-08-21 09:48
duplicate of https://github.com/microsoft/vscode/issues/190663

**Closed by aeschli** 2023-08-21 09:48 UTC
