### ISSUE TITLE
Markdown JSDoc links don't work in remote windows

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#165080] opened 2022-10-31 18:48 UTC
1. Open https://github.com/microsoft/vscode-extension-samples/blob/fdd3bb95ce8e38ffe58fc9158797239fdf5017f1/tree-view-sample/src/extension.ts#L18 in a remote window (WSL, SSH, Codespaces)
2. Hover over `registerTreeViewDataProvider`
3. Click on `TreeView` in JSDoc
4. :bug: get a file not found error
![image](https://user-images.githubusercontent.com/30305945/199085877-7578b411-7c76-411d-849b-b0ea13749646.png)

@jkeech tracked the feature impl down to https://insiders.vscode.dev/github/microsoft/vscode/blob/3dc149ae651205b35544c040b3f9fd8ad11352d2/extensions/typescript-language-features/src/utils/previewer.ts#L148-L155. From the URI in the hover above which has a `file` scheme instead of a `vscode-remote` scheme, and from the code above, I suspect these URIs can't be assumed to exist on disk and the URI scheme needs to be preserved

**Comment by mjbvz** [comment] 2022-11-02 08:02
Duplicate of #162507

**Closed by mjbvz** 2022-11-02 08:02 UTC
