### ISSUE TITLE
sqlite3 CLI in Terminal

### ISSUE THREAD

**Issue by 5wattbulb** [microsoft/vscode#116174] opened 2021-02-09 09:42 UTC
Issue Type: <b>Bug</b>

Start sqlite3 in ubuntu 20.04 terminal. Press enter until on bottom line of terminal window. Press any key until cursor is at bottom right position in terminal window. Keep pressing the key and you'll find the cursor wraps to the beginning of the same line rather than scroll to a new line. Use .exit to exit sqlite3 and the problem persists in the terminal window even though you're back in the bash shell. Additionally, while running sqlite3 the arrow keys don't work properly. They print out characters rather than allow you to move through the command you've just entered or move through bash history.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.91GB free)|
|Process Argv|--crash-reporter-id b4321af5-cee0-4e9f-8096-a5398bc82ffe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2207)|
|Memory (System)|12.43GB (0.20GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.53.2
cpptools|ms-|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry244:30250195
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by meganrogge** [comment] 2021-02-09 15:42
Can you try changing your renderer type?

**Comment by 5wattbulb** [comment] 2021-02-09 16:44
I'm new to VCS and I'm unsure what that means Megan. If I click 'view | command palette' and type in 'render' all I get is 'toggle render whitespace'.

**Comment by meganrogge** [comment] 2021-02-09 20:49
Can you pls provide a [gif](http://gifcap.dev/) of this happening so I can understand the problem?

**Comment by 5wattbulb** [comment] 2021-02-10 10:52
![recording](https://user-images.githubusercontent.com/76473295/107499885-6987cb80-6b8d-11eb-8461-d7591152bbe8.gif)

The recording shows the wrapping problem Megan. After I execute the command at the bottom I clicked the arrow up/left/right and down keys followed by a series of 'x' keys until it wraps again. I try deleting them with the backspace key but get stopped at beginning of line. Finally I click ctrl+z to exit sqlite3.

**Comment by meganrogge** [comment] 2021-02-10 18:27
Are you pressing alt when you use the arrow keys? Try setting `terminal.integrated.altClickMovesCursor` to false.

**Comment by 5wattbulb** [comment] 2021-02-10 19:25
I'm not pressing Alt with the arrow keys Megan but if I do I get no response at all. I can't find the setting you mention. I brought up command palette and did various partial searches but could find nothing like that. Do I have to create the setting and, if so, where do I put it?

**Comment by meganrogge** [comment] 2021-02-11 04:22
Click the settings gear in the bottom left corner of the window then in the search bar, paste:

`terminal.integrated.altClickMovesCursor` and uncheck the box

**Comment by 5wattbulb** [comment] 2021-02-12 07:14
I'll hopefully get back to you in a day or so Megan. I've been hit with a blue wall of death and I'm going to have to reinstall everything.

**Comment by 5wattbulb** [comment] 2021-02-15 10:38
Hi Megan, I had to do a full reinstall of windows, vsc etc. so vsc settings were at default values. I installed sqlite3 using 'sudo apt install sqlite3'. When I run sqlite3 in vsc terminal the arrow keys now work properly but the word wrap to same line at bottom line problem persists. Does it do the same on your system?

PS Checked or not 'terminal.integrated.altClickMovesCursor' makes no difference.

**Comment by 5wattbulb** [comment] 2021-02-19 09:40
I've sorted the arrow key problems by installing libreadline-dev following advice from the sqlite forum. The bottom line wrapping problem does seem to be a wsl / vscode / windows terminal problem though.

**Comment by meganrogge** [comment] 2021-02-26 19:19
Thanks for the info and glad to hear you resolved the arrow key issue. 
So does this not fix the wrapping issue then?
> Edit: I just noticed that clicking on that 'toggle render whitespace' has solved the word wrapping issue at the bottom of the screen. it now scrolls to a new line rather than wrapping round to the beginning of the same line. Thank you for that Megan.

**Comment by 5wattbulb** [comment] 2021-02-27 08:15
The 'toggle render whitespace' is no longer there. It's been replaced by 'Render Whitespace' which is an enum (none, boundary, selection, trailing, all). I've currently got it set to 'selection default' but none of the other settings make any difference to the wrapping problem.

**Comment by AndreaPi** [comment] 2021-03-02 13:06
Looks like these other issues may be possible duplicates of this one:

https://github.com/microsoft/vscode/issues/116029

https://github.com/microsoft/vscode/pull/115446

Note that the first user experiences the issue only when connecting to a remote server using the Remote-WSL extension (same as me) and only when using bash or zsh but not when using the Powershell terminal (I can't confirm this since I'm not on Windows).

**Comment by Waghabond** [comment] 2021-03-02 13:11
Hey yes, i have the same problem with line wrapping. i dont use sqllite but the problem looks very similar to that gif. It only a correction to what Andrea said it manifests when the current vscode window connected to WSL and it only happens in the cmd and bash terminals. When the vscode window is not connected to WSL the issue is not observed in any terminal.

**Comment by samherrmann** [comment] 2021-03-02 19:40
I am experiencing the same issue when connected to WSL. I tried the following settings suggested by Megan, but none of them made a difference:
* `"terminal.integrated.altClickMovesCursor": false`
* `"terminal.integrated.rendererType": "canvas"`
* `"terminal.integrated.rendererType": "dom"`
* `"terminal.integrated.rendererType": "experimentalWebgl"`

**Comment by 5wattbulb** [comment] 2021-03-03 11:30
I'm relieved to see I'm not alone.

**Comment by AndreaPi** [comment] 2021-04-11 14:07
So, are there any plans to tackle this?

**Comment by PaulPCIO** [comment] 2021-04-17 10:51
Also having the same issue when connected wsl

**Comment by AndreaPi** [comment] 2021-04-17 16:30
@PaulPCIO  great! Where/how do I change this setting? What command should I look for using the command palette?

**Comment by Waghabond** [comment] 2021-04-17 16:33
> @PaulPCIO great! Where/how do I change this setting? What command should I look for using the command palette?

you would just put that line into your settings.json

**Comment by AndreaPi** [comment] 2021-04-17 18:39
@Waghabond if I open "settings" from the menu I don't see the whole file, but just some settings I can edit. I guess I'll have to find the file location & open it directly rather than through the Settings (Preferences?) menu.

**Comment by Waghabond** [comment] 2021-04-17 18:44
@AndreaPi you can access it by doing ctrl+shift+p to open the command palette and typing "settings json". An option to open the json will come up.

**Comment by dariobig** [comment] 2021-04-19 19:40
Same problem for me connecting to docker. Setting `"terminal.integrated.rendererType": "canvas"` fixed it as well. 
I'm on latest visual studio (1.55.2) and docker desktop (3.2.2) on mac:

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (6 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

**Comment by xdhmoore** [comment] 2021-04-21 16:28
I see this behavior (using the Remote-Docker extension) but I seem to be able to fix it by unmaximizing my VS Code window and remaximizing it.  I've also noticed that when I first start VS Code, sometimes the window is pretty small and I usually maximize the window before the Terminal loads (which can be a long time when using the Remote-Docker extension). The width that the terminal bug wraps at seems to be the same width as the original terminal would have been when I first opened VS Code and before I maximized it. 

Theory:
When I maximize the window shortly after opening VS Code, the Terminal width isn't being updated to match cause it is still loading. Maybe the long load times of Remote-Docker / Remove-WSL workspaces contribute.

I've reproduced it a couple times, but it doesn't happen *every* time, so maybe it's a race condition (depending on the loading state of Terminal when the window is first maximized?)

**Comment by cdwort** [comment] 2021-04-29 15:49
Just adding my experience -- I opened the Codespace in the current window size and still encountered this issue. I can reload the Codespace to get the same behavior. Screenshot of trying to run `bundle` in a Ruby app:

<img width="1502" alt="Screen Shot 2021-04-29 at 10 39 59 AM" src="https://user-images.githubusercontent.com/1014482/116580034-9a4be700-a8d8-11eb-8b1c-7c7d892584d6.png">

**Comment by Waghabond** [comment] 2021-04-29 15:53
@cdwort did you set terminal renderer to canvas?

**Comment by exophoric** [comment] 2021-07-02 18:25
For me this issue occurs rarely but still a few times a month in a regular bash shell session. (No need for full-screen / cursor moving terminal apps like sqlite.) 

I don't know what triggers this, but when I have it, I noticed that splitting the terminal / resizing the splits or simply resizing the browser can resolve it temporarily. If I grow the width of the affected terminal back to its original size or wider than it was, then the wrapping issue occurs again.

My current setup is:
v1.57.0, running on linux fedora 33,  kde spin. 
terminal.integrated.altClickMovesCursor = true
terminal.integrated.gpuAcceleration = auto

terminal.integrated.rendererType is not a valid option in my vscode version or OS or I don't know what I'm doing.

**Comment by 5wattbulb** [comment] 2021-09-23 11:22
I've been using GNU m4 CLI and finding similar issues. You can't press the up arrow to repeat the last command, you can't move around the current line using the left and right arrow keys meaning backspace is the only way of editing.

**Comment by meganrogge** [comment] 2021-10-12 18:00
I can't reproduce the issue, so am closing this as it's likely been fixed. Please create a new issue, citing this one, with detailed steps to repro if you see this again. 
/duplicate #120810

**Comment by Tyriar** [comment] 2022-12-01 20:05
This issue is a bit stale now, a lot of changes have happened to the renderers since. My guess is also that this is related to conpty if connecting via WSL/docker on Windows. Please create a new issue if you still see this on 1.74

**Closed by Tyriar** 2022-12-01 20:05 UTC
Labels: bug, terminal
