### ISSUE TITLE
Right Click Trouble 

### ISSUE THREAD

**Issue by edipgencler** [microsoft/vscode#137879] opened 2021-11-25 12:34 UTC
Issue Type: <b>Bug</b>

Right click stays on

VS Code version: Code - Insiders 1.63.0-insider (c1f2f40bcd81380bf2e286af64becddada57db88, 2021-11-24T05:33:22.438Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 3600 6-Core Processor           (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.76GB free)|
|Process Argv|--crash-reporter-id 66cdc87c-2979-4d54-88d5-6407104c3d4a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.7.1
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
vscode-html-css|ecm|1.10.2
php-debug|fel|1.22.0
composer|ika|0.7.1
vue|jcb|0.1.5
vsc-python-indent|Kev|1.14.2
materialdesignicons-intellisense|luk|4.0.0
MagicPython|mag|1.1.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
autodocstring|njp|0.5.4
vetur|oct|0.35.0
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt2:30397559
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by IllusionMH** [comment] 2021-11-25 13:32
/duplicate of #137785

Fix already available in latest Insiders build

**Closed** 2021-11-25 13:33 UTC
Labels: *duplicate
