### ISSUE TITLE
Diff view showing an older version of notebook file

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#105956] opened 2020-09-02 17:00 UTC
Testing #105770

Did a git pull and made sure my notebooks file is up-to-date, make a change in a cell and the left side of the diff view has an older version of my file and not the one I made the most recent change in.

![recording (7)](https://user-images.githubusercontent.com/9721254/92013489-dd3ec600-ed1b-11ea-90c4-c7802edf00d8.gif)

**Comment by rebornix** [comment] 2020-09-02 21:49
> Did a git pull and made sure my notebooks file is up-to-date, make a change in a cell and the left side of the diff view has an older version of my file and not the one I made the most recent change in.

Did you happen to have the diff editor opened once before you do `git pull`? if so, I think it's a duplicate of https://github.com/microsoft/vscode/issues/105917

**Closed** 2020-09-10 11:23 UTC
Labels: needs more info, notebook
