### ISSUE TITLE
[javascript] TextMate themes don't seem to apply to all keywords

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#257] opened 2015-11-19 16:09 UTC
Since last update the default VS Code dark theme has changed (I like the old one because I just don't want bright red colors on the dark background). So I tried (first time I have to admit) create (or modify) a theme via http://tmtheme-editor.herokuapp.com/

Resulting theme is a modification of Visual Studio Dark (uploaded as .txt since .tmTheme is not allowed)
[Visual Studio Dark Modified.txt](https://github.com/Microsoft/vscode/files/39136/Visual.Studio.Dark.Modified.txt)

tmtheme-editor online interprets theme as follows:
![image](https://cloud.githubusercontent.com/assets/8778539/11275555/74bee006-8ede-11e5-956a-831aac59ef4e.png)

VS Code however does not interpret theme identically:
![image](https://cloud.githubusercontent.com/assets/8778539/11275539/65af5708-8ede-11e5-941a-b7a2c89f4ae3.png)

Please note that this is my first contact with this stuff - I'm not sure if this is an issue related to VS Code of tmtheme-editor

**Comment by tSte** [comment] 2015-11-19 16:44
Okay I found out that class, super and extends are interpreted as 'invalid.illegal' - why are those interpreted that way? My jsconfig.json contains compiler options for ES6...

"compilerOptions": {
	"target": "ES6",
}

**Comment by aeschli** [comment] 2015-11-24 10:56
The problem is that our JavaScript tokenizer isn't supporting ES6 yet.

**Comment by tSte** [comment] 2015-11-24 11:46
I am not sure if ES6 is the problem here... for example the "let" or "const" keywords are classified correctly. But the "new" keyword is not. Object keys are considered (if I am not wrong) to be constants. Document and Array objects poses also different colors.

**Comment by aeschli** [comment] 2015-11-24 16:35
Looking at your code example we need to get ES6 back to work.
duplicate of #133

**Closed by aeschli** 2015-11-24 16:35 UTC
