### ISSUE TITLE
Swap icons for stable and insider

### ISSUE THREAD

**Issue by lzantal** [Microsoft/vscode#36835] opened 2017-10-24 16:25 UTC
Just a suggestion that using the green icon for the stable release and the orange icon for the insiders. Green is more associated with everything is good, free to go like a stop light etc... 

Laszlo

**Comment by chrisdias** [comment] 2017-10-24 18:59
dupe of https://github.com/Microsoft/vscode/issues/35674

**Closed by chrisdias** 2017-10-24 18:59 UTC
