### ISSUE TITLE
Rename (F2) adds extra . (.header-toolbar => ..header)

### ISSUE THREAD

**Issue by misiam** [Microsoft/vscode#34200] opened 2017-09-12 07:40 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
code-gnu-global|aus|0.2.2
vscode-icontheme-nomo-dark|be5|1.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.0
python|don|0.7.0
xml|Dot|1.9.2
vscode-npm-script|eg2|0.2.1
vscode-great-icons|emm|2.1.15
code-runner|for|0.7.1
gc-excelviewer|Gra|1.1.15
beautify|Hoo|1.1.1
rest-client|hum|0.15.2
search-node-modules|jas|1.2.0
csharpextensions|jch|1.3.0
node-module-intellisense|lei|1.4.0
vs-color-picker|lih|0.6.0
OpenVim|mat|0.0.8
mssql|ms-|1.1.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.2
material-icon-theme|PKi|2.2.1
java|red|0.9.0
vscode-icons|rob|7.12.0
preview-vscode|sea|1.2.0
code-settings-sync|Sha|2.8.3
nodejs-extension-pack|wad|0.1.9
iis-express|war|1.0.0
vscode-cil-complete|wk-|0.0.5
JavaScriptSnippets|xab|1.4.1

(10 theme extensions excluded)

---

Steps to Reproduce:

1.  In .css file try to press F2 (rename) on .header-toolbar style
2. Rename from ".header-toolbar" to ".header"
3) Bug => it appeared to be "..header"
Reproduces without extensions: **Yes**

**Comment by aeschli** [comment] 2017-09-12 08:14
duplicate of https://github.com/Microsoft/vscode/issues/30100

**Closed by aeschli** 2017-09-12 08:14 UTC
Labels: new release
