### ISSUE TITLE
When using multiple cursors, the window doesn't follow them when using keyboard

### ISSUE THREAD

**Issue by antonioplacerda** [Microsoft/vscode#41802] opened 2018-01-18 10:04 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
compulim-vscode-closetag|Com|1.1.0
xml|Dot|1.9.2
vs-code-xml-format|fab|0.1.5
code-runner|for|0.8.7
vscode-abap|lar|0.1.0
mssql|ms-|1.3.0
vscode-icons|rob|7.19.0
partial-diff|ryu|0.5.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Create multiple cursor
2. Go out of scope with the cursors using the keyboard
3. Stop seeing them!

Reproduces without extensions: Yes

**Comment by jrieken** [comment] 2018-01-18 10:07
> Go out of scope with the cursors using

What is going out of scope?

**Comment by antonioplacerda** [comment] 2018-01-18 10:21
any of the cursor

**Comment by jrieken** [comment] 2018-01-18 10:41
That answer didn't seem like it was for my question. What is 'going out of scope', scrolling, TextMate scopes, going over words. Please clarify.

**Comment by antonioplacerda** [comment] 2018-01-18 10:59
I'm sorry, I can't explain myself any better.
The issue I'm having is the one presented on the gif I uploaded. When I move the cursor using the keyboard keys, the window doesn't follow. Perhaps going out of scope is not the best way to describe this...

The normal behavior when using a single cursor is that the window follows the cursor. I expected the same to happen when using multiple cursors

**Comment by jrieken** [comment] 2018-01-18 11:03
Thanks, the gif helped. What you call scope is usually referred to as viewport.

**Comment by antonioplacerda** [comment] 2018-01-18 11:23
Ok, thank you! Sorry for the confusion

**Comment by alexandrudima** [comment] 2018-01-18 14:35
Duplicate of #6995

**Closed by alexandrudima** 2018-01-18 14:35 UTC
Labels: editor, editor-core
