### ISSUE TITLE
Notifications UX

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1135] opened 2015-12-09 11:30 UTC
We need to explore improving the way that we display warnings, errors and notifications to users. Currently we have a variety of mechanisms (info in status bar, details in quick open, error/warning dialog).

We need a consistent way that prompts the user when there are notifications/errors/warnings for them to pay attention to and a consistent affordance for the user to get a holistic view of all of the notitications/errors/warnings.

**Comment by Alphapage** [comment] 2016-03-31 08:20
I'm agree with you.
It would be great to have a notifications center.

For extensions, status bar messages is the only way to display info for a short time without disturbing the user too much, but it is difficult to attract the attention.
The only way is to show a warning|info|error message, but the user must interact with it which is not necessary in most cases. So, a notification center would be a great enhancement to track non blocking messages (displayed for 5 seconds only by default for example).

**Comment by schittli** [comment] 2018-02-01 17:06
We really cannot believe you introduced this kind of annoying feature, especially because every other IDE has solved this kind of message-handling years ago in a perfect way: the usual solution does not annoy users and nobody reclaims that they are missing notification.

Therefore, it's really strange that you need more than 2 years to roll it back and reapply the old and great working concept.

**Comment by bpasero** [comment] 2018-02-10 13:46
Duplicate of https://github.com/Microsoft/vscode/issues/22388

**Closed by bpasero** 2018-02-10 13:46 UTC
Labels: ux, workbench-notifications
