### ISSUE TITLE
Changes can get lost when application crashes with dirty files open

### ISSUE THREAD

**Issue by rpanjwani** [Microsoft/vscode#1106] opened 2015-12-08 16:33 UTC
VS Code froze and I lost all my changes.

**Comment by egamma** [comment] 2015-12-09 07:52
Did you have auto save (File>Autosave) turned on?

**Comment by bpasero** [comment] 2015-12-21 13:50
@rpanjwani can you clarify what happened to your changes? was the file empty when you reopened it after restart?

**Comment by rpanjwani** [comment] 2015-12-24 05:46
There was no file. I had just been coding into a file for a while without saving it. I turned on auto-save feature afterwards, but I think it should be on by default.

**Comment by rpanjwani** [comment] 2015-12-24 05:47
@bpasero I had just been coding on a file for a while without saving it. I think auto-save should be on by default.

**Comment by bpasero** [comment] 2015-12-24 08:20
Makes sense. The only solution I can see is to frequently perform backups of the file so that a state can be restored later.

**Comment by bpasero** [comment] 2015-12-24 08:21
https://github.com/Microsoft/vscode/issues/1161 is related and having a backup solution would fix both things.

**Comment by bpasero** [comment] 2015-12-24 15:14
Closing as duplicate of #1161

**Closed by bpasero** 2015-12-24 15:14 UTC
Labels: bug, files
