### ISSUE TITLE
The list of files in WSL is not updated

### ISSUE THREAD

**Issue by okineadev** [microsoft/vscode#198743] opened 2023-11-21 08:01 UTC
Type: <b>Bug</b>

When I create the test.py file it doesn't appear in the file list until I close and reopen the editor

https://github.com/microsoft/vscode/assets/81070564/d8a0b6cf-ed8a-4195-ab51-b52ee40c71e8

VS Code version: Code - Insiders 1.85.0-insider (05cd2640ec8a106a4ee99cb38e6ee34fbec04f11, 2023-11-21T05:35:09.651Z)
OS version: Windows_NT x64 10.0.23590
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (5.14GB free)|
|Process Argv|--crash-reporter-id 75c1e97a-4c7a-4737-b36e-a3d6abf26d86|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz (16 x 2495)|
|Memory (System)|2.84GB (1.16GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
vscode-firefox-debug|fir|2.9.10
auto-rename-tag|for|0.1.10
remote-containers|ms-|0.324.0
remote-ssh|ms-|0.108.2023110315
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.5.2023110609
remote-server|ms-|1.6.2023110809
material-icon-theme|PKi|4.32.0
sweetalert2-snippet|roh|1.1.2
chrome-extension-developer-tools|aar|2.0.4
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-markdownlint|Dav|0.52.0
gitlens|eam|2023.11.2004
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
cloudcode|goo|2.1.1
vscode-language-pack-ru|MS-|1.84.2023111509
live-server|ms-|0.5.2023112001
vscode-css-peek|pra|4.4.1
trailing-spaces|sha|0.4.1
vscode-pets|ton|1.25.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
volar|Vue|1.8.23
vscode-typescript-vue-plugin|Vue|1.8.22
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30859870
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by aeschli** [comment] 2023-11-22 08:13
duplicate of https://github.com/microsoft/vscode-remote-release/issues/5000

**Closed by aeschli** 2023-11-22 08:13 UTC

**Comment by okineadev** [comment] 2023-11-22 09:59
So you won't fix it?

**Comment by aeschli** [comment] 2023-11-22 10:19
Unfortunately, this needs to be fixed in WSL.
