### ISSUE TITLE
Error when searching for text in files: A system error occurred (spawn ENAMETOOLONG)

### ISSUE THREAD

**Issue by kaiyoma** [microsoft/vscode#221496] opened 2024-07-11 18:23 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.1
- OS Version: Windows 11

Steps to Reproduce:

1. Search for text in all open files

![image](https://github.com/microsoft/vscode/assets/10719780/fcaef664-0cba-43fd-a4b8-6ec68d10ef3e)

**Comment by andreamah** [comment] 2024-07-12 16:22
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/98514. Try looking at your `files.exclude` setting.

**Closed** 2024-07-12 16:22 UTC
Labels: new release
