### ISSUE TITLE
Prompt user when dirty file gets deleted

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#6864] opened 2016-05-25 09:59 UTC
- VSCode Version: 1.1.1
- OS Version: current OSX

Steps to Reproduce:
Vscode with github

1. create a file
2. add content in the file, but don't save it. Stay on it in the editor.
3. delete file (move to trash) from tree file browser

File still shows in working files as unsaved file, and on screen. This is confusing, as 'save all' might recreate the deleted file. A deleted file, even if unsaved, should be removed from:

- File browser, both tree and working files
- editor

**Comment by bpasero** [comment] 2016-05-25 13:25
@Brakkar we cannot really close the file with user changes because that would mean data loss. We could however maybe ask the user what to do if we detect this case.

**Comment by Brakkar** [comment] 2016-05-25 13:28
Yes, would be good and if user agrees, the file should be truly removed from editor as well as all browser tree areas. Tks.

**Comment by bpasero** [comment] 2016-08-08 08:06
Duplicate of https://github.com/Microsoft/vscode/issues/9313

**Closed by bpasero** 2016-08-08 08:06 UTC
Labels: feature-request, files
