### ISSUE TITLE
Release Notes scroll up when switching back to tab

### ISSUE THREAD

**Issue by rje6459** [Microsoft/vscode#47832] opened 2018-04-13 12:48 UTC
Issue Type: <b>Bug</b>

I was switching between the release notes tab and a test document to try out the new Emmet: Wrap with abbreviation feature when I discovered that the Release Notes page would scroll up to the Find and Replace improvements for large files section, making it so that the Emmet: Wrap with abbreviation section was not visible. I thought it may have been because I was scrolled in between sections, so the page was automatically scrolling up to the header for the active section, but this issue occured both when I maually scrolled to the Emmet section and when I used the hyperlink.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.65GB (3.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
<!-- genera

**Comment by mjbvz** [comment] 2018-04-13 21:35
Duplicate of #45571

**Closed by mjbvz** 2018-04-13 21:35 UTC
Labels: emmet
