### ISSUE TITLE
Fail to focus on textarea in webview visually within 5 seconds

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#65410] opened 2018-12-19 18:51 UTC
Issue Type: <b>Bug</b>

Re https://github.com/Microsoft/vscode/issues/63180

* Install GitHub Pull Request 0.3.2
* Open VSCode and open a description view of any pull request
* Click into the textarea at the end of the document
* On Stable
  * The textarea is focused, it shows a blinking cursor and you can type
* On Insiders 1.31
  * The textarea is not focused visually, no blinking cursor. It looks like the UI is forzen but actually you can still type.

VS Code version: Code - Insiders 1.31.0-insider (d315b31c6b5cdca082b0a6e193306e4001586509, 2018-12-19T08:03:47.112Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|-psn_0_11594510|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
solargraph|cas|0.18.0
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
gitlens|eam|9.2.2
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.7.3
vscode-pull-request-github|Git|0.3.2
ocaml|hac|0.6.43
beautify|Hoo|1.4.7
references-plusplus|jri|0.0.5
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.9
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
azure-account|ms-|0.7.0
Go|ms-|0.8.0
PowerShell|ms-|1.10.1
vscode-typescript-tslint-plugin|ms-|0.2.1
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.1071
debugger-for-chrome|msj|4.11.1
debugger-for-ios-web|msj|0.1.2
color-highlight|nau|2.3.0
vetur|oct|0.14.3
subtitles-editor|pep|1.0.1
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.1
seti-icons|qin|0.1.3
project-snippets|reb|0.5.0
ruby|reb|0.21.0
smartpaste|reb|0.0.3
toggle|reb|0.0.1
sass-indented|rob|1.4.9
rust|rus|0.5.3
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.1.2

(10 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-12-19 19:42
Also effects the tab focus outline

**Comment by bpasero** [comment] 2018-12-20 06:04
Caused by changes to the `<webview>` with Electron 3. A good first issue from https://github.com/Microsoft/vscode/issues/63180

**Comment by zabel-xyz** [comment] 2018-12-22 08:32
Same problem with my extension [plsql-language](https://github.com/zabel-xyz/plsql-language)
With command "Activate connection", I display an html formular to input some data.
=> Issue with focus and tab in input controls

Version: 1.31.0-insider (system setup)
Commit: e02e44464c02d617b98d0a3265bf5efef7794436
Date: 2018-12-21T06:20:35.852Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment] 2019-01-05 02:11
Addressed by #66070

**Closed by mjbvz** 2019-01-05 02:11 UTC
Labels: bug, electron, electron-3.0.x-update, upstream, webview
