### ISSUE TITLE
Centered the restore button icon

### ISSUE THREAD

**Issue by Demonese** [microsoft/vscode#159874] opened 2022-09-02 09:42 UTC
Version: 1.71.0 (system setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

As you can see it doesn't seem to be centered:
<img width="194" alt="image" src="https://user-images.githubusercontent.com/57629614/188111877-ce682ba0-e382-4de7-85a9-f61fd67715e3.png">

**Comment by rzhao271** [comment] 2022-09-06 15:04
Duplicate of https://github.com/microsoft/vscode/issues/157086

**Closed by rzhao271** 2022-09-06 15:04 UTC
