### ISSUE TITLE
Path intellisense is brutally slow and then stops working

### ISSUE THREAD

**Issue by jankalfus** [Microsoft/vscode#36825] opened 2017-10-24 14:03 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---
1. Try to use path intellisense for relative path
VS Code is brutally slow at first, it gets worse with every level, until it stops suggesting completely at 4th level (`import Something from '../../../../<here, nothing happens>'`). Then it never starts working again, even after writing a completely new import statement. The only way to get it "working" is by restarting the editor. But then, all the issues start again.

I'm thinking maybe this has something to do with the Fall Creators Update?

Reproduces without extensions: Yes

**Comment by cadebward** [comment] 2017-10-24 15:53
I have the same issue on OSX.

VSCode Version: 1.17.2
OS Version: OSX 10.11.6 (15G1611)

It only happens on projects with lots of files and directories. 

```bash
$ find . -type f | wc -l
69620
```

**Comment by mjbvz** [comment] 2017-10-24 22:06
I believe this is https://github.com/Microsoft/TypeScript/issues/16329 . It should be fixed in TypeScript 2.6 which is included in the current VS Code insiders builds. Please try this out and let me know if you still see the performance problems

**Comment by jankalfus** [comment] 2017-10-25 06:11
@mjbvz Unfortunately, the problem doesn't seem to be related to that issue. I've tried the latest insider build (Insiders 1.18.0-insider (c1e079b6ccfad9ead105c44a84e862ffc5250222, 2017-10-25T04:18:36.616Z)) and the issue is the same.

BTW I also noticed that both the AutoFileName and Relative Path extensions stopped working as well.

Like I said in the original post, I suspect this has something to do with the Fall Creators Update. I didn't have any issues (I'm not sure about VS Code itself, but I'm 100 % sure the extensions were working) before the update.

**Comment by mjbvz** [comment] 2017-10-28 00:05
Can you please try collecting the TypeScript server logs to see if that has any leads:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Run the `Typescript: Open TS Server log` command in vs code and look in the `tsserver.log` file in the opened directory

Look for errors, stack traces, or other suspicious info near the end of the logs, specifically around the `'completions'` requests. Also see if any of these requests are taking a long time to complete.

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by jankalfus** [comment] 2017-10-30 12:01
Here you go: 

```
Info 218  [12:49:31.876] request: {"seq":72,"type":"request","command":"completions","arguments":{"file":"/*censored*/","line":12,"offset":27}}
Info 219  [12:49:32.586] Scheduling throttled operation: {"projectName":"/dev/null/inferredProject1*","fileNames":[/*censored list of 489 files*/],"compilerOptions":{"module":1,"target":2,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"allowJs":true,"jsx":1,"checkJs":false,"noEmitForJsFiles":true,"maxNodeModuleJsDepth":2},"typeAcquisition":{"enable":true,"include":[],"exclude":[]},"unresolvedImports":["child_process","core-js","crypto","events","fs","http","https","net","node-notifier","path","readline","stream","tls","url","util","vm","zlib"],"projectRootPath":"","kind":"discover"}
Info 220  [12:49:32.587] Scheduling request for: /dev/null/inferredProject1*
Perf 221  [12:49:32.591] 72::completions: elapsed time (in milliseconds) 713.8218
Info 222  [12:49:32.591] response: {"seq":0,"type":"response","command":"completions","request_seq":72,"success":true,"body":[{"name":"index","kind":"script","kindModifiers":"","sortText":"index","replacementSpan":{"start":{"line":12,"offset":26},"end":{"line":12,"offset":27}}},{"name":"js","kind":"directory","kindModifiers":"","sortText":"js","replacementSpan":{"start":{"line":12,"offset":26},"end":{"line":12,"offset":27}}},{"name":"scss","kind":"directory","kindModifiers":"","sortText":"scss","replacementSpan":{"start":{"line":12,"offset":26},"end":{"line":12,"offset":27}}}]}
```

Sorry, but I had to censor the file paths. BTW I couldn't find any errors or stack traces.

**Comment by umstek** [comment] 2017-11-03 15:07
This happens not only in TypeScript, but also in JavaScript (create-react-app). 
![image](https://user-images.githubusercontent.com/7861481/32380555-56ab7d96-c0d6-11e7-978d-e02369032c5a.png)
Keeps showing the loading indicator forever. (Extensions are disabled.) 
When this happens, all other intellisense stop working. 
![image](https://user-images.githubusercontent.com/7861481/32380707-c30578de-c0d6-11e7-88e9-c8361f3f7404.png)

**Comment by jankalfus** [comment] 2017-11-03 16:19
@umstek That's the exact same behavior I'm observing. I just realized I might have not been clear in my original post, but this too happens in Javascript for me.

However, I don't think it really matters, as all the intellisense is powered by the TypeScript server, right?

**Comment by umstek** [comment] 2017-11-03 17:39
@jankalfus ah, yes I think so.

**Comment by yklykl530** [comment] 2017-11-05 10:00
see this issue, update Typescript version is working, https://github.com/Microsoft/vscode/issues/35603

**Comment by yklykl530** [comment] 2017-11-05 10:03
I find this question for a week, hope this issue fixed official version vscode as soon as possible,thanks @mjbvz

**Comment by DrakeXiang** [comment] 2017-11-09 09:46
@yklykl530  I set typescript.tsdk to version 2.6.1, didn't help with the situation

**Comment by nicksnyder** [comment] 2017-11-14 18:51
I am experiencing this issue in insiders 73830a36872aa1c168c085dad8cc6e2e1a05ff45

https://cl.ly/0o0F1H170j0S

Attached is the log from this session.
[tsserver.log](https://github.com/Microsoft/vscode/files/1472131/tsserver.log)

**Comment by nicksnyder** [comment] 2017-11-14 21:15
Just wanted to add two more pieces of information:
- This isn't just a windows issue (I am on Mac).
- This appears to have regressed for me sometime in the last week. Sorry I don't have a more precise time.

My current dev experience is painfully slow now as a result of this issue. Please let me know if there is any other information that I could provide to help debug since this reliably reproduces for me.

**Comment by mjbvz** [comment] 2017-11-15 19:36
Thank you all for the additional information.

I have opened https://github.com/Microsoft/TypeScript/issues/20047 to track this upstream and moved over a few comments to help the TS team with investigation. Please follow up on the TypeScript issue instead of this one.

Closing as upstream

**Closed by mjbvz** 2017-11-15 19:36 UTC
Labels: typescript, upstream, windows
