### ISSUE TITLE
Unexpected [ts] errors in JavaScript files (experimentalDecorators) despite settings or disabling builtins

### ISSUE THREAD

**Issue by AndrewHuffman** [Microsoft/vscode#62167] opened 2018-10-30 15:52 UTC
Issue Type: <b>Bug</b>

Similar to #54261 that appears to have been closed without a resolution.  I've seen this issue off an on for months depending on what I'm working on:

![screen shot 2018-10-30 at 11 37 39 am](https://user-images.githubusercontent.com/502073/47731340-4645e600-dc3a-11e8-9640-52814debd72f.png)

What's really bizarre, and leads me to believe this may be a bug, is I've tried the following without resolution:

- Set `experimentalDecorators` to `false`
- Disabling the builtin "TypeScript and JavaScript Language Features" extension

It will appear to work at first, but once I open another javascript file with decorators I'll see this ts error again.

Additionally, given the amount of attention on other bug, I think the community would appreciate some attention to this issue.  I don't believe it makes sense for [ts] errors to appear in javascript files at all, unless configured to do so. Can someone elaborate why this happens at all?

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz (16 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (0.06GB free)|
|Process Argv|app-main.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
JSDocTagComplete|Hoo|0.0.2
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|9.1.0
project-manager|ale|9.0.1
rtf|ale|1.3.0
copy-relative-path|ale|0.0.2
jest-snippets|and|1.6.1
lit-html|bie|1.7.0
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.60
compulim-vscode-closetag|Com|1.2.0
vsforce|cov|0.2.0
vscode-eslint|dba|1.6.1
git-extension-pack|don|0.1.3
githistory|don|0.4.3
jquerysnippets|don|0.0.1
xml|Dot|2.3.2
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.5
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.5.1
prettier-vscode|esb|1.6.1
vscode-jest-runner|fir|0.2.3
code-runner|for|0.9.5
todo-tree|Gru|0.0.97
vscode-import-formatter|hen|0.1.8
docthis|joe|0.7.1
apex|Joh|0.0.2
sublime-babel-vscode|jos|0.2.10
vscode-language-babel|mgm|0.0.21
vscode-todo-parser|min|1.9.1
theme-monokai-pro-vscode|mon|1.1.8
python|ms-|2018.9.2
vetur|oct|0.13.0
material-icon-theme|PKi|3.6.0
node-tdd|pra|0.2.4
java|red|0.33.0
vscode-icons|rob|7.27.0
salesforcedx-vscode|sal|44.4.0
salesforcedx-vscode-apex|sal|44.4.0
salesforcedx-vscode-apex-debugger|sal|44.4.0
salesforcedx-vscode-apex-replay-debugger|sal|44.4.0
salesforcedx-vscode-core|sal|44.4.0
salesforcedx-vscode-lightning|sal|44.4.0
salesforcedx-vscode-lwc|sal|44.4.0
salesforcedx-vscode-visualforce|sal|44.4.0
todotasks|san|0.5.0
vue-vscode-extensionpack|sdr|0.1.3
vue-vscode-snippets|sdr|1.3.0
vscode-table-formatter|shu|1.2.1
html5-boilerplate|sid|1.0.3
vscode-fileutils|sle|2.11.0
javascript-typescript|sou|0.0.7
addDocComments|ste|0.0.8
code-spell-checker|str|1.6.10
source-depot|sup|0.0.2
ayu|tea|0.16.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-todo-highlight|way|1.0.4
html-snippets|wge|0.1.5
vscode-jumpy|wma|0.3.1
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.1
FilterText|yhi|0.0.11
markdown-all-in-one|yzh|1.7.0
vscode-open-in-github|ziy|1.3.6

(11 theme extensions excluded)

</details>

**Comment by AndrewHuffman** [comment] 2018-10-30 16:04
Actually, this may be an issue with the [Sourcegraph](https://marketplace.visualstudio.com/items?itemName=sourcegraph.javascript-typescript) extension. Disabling that, and re-enabling the builtin plugin has not reproduced the same errors. I'll report back if I see this issue resurface with that extension disabled.

**Comment by mjbvz** [comment] 2018-10-31 18:31
Closing as caused by extension for now

**Closed by mjbvz** 2018-10-31 18:31 UTC

**Comment by AndrewHuffman** [comment] 2018-10-31 19:35
Thanks, I've not seen it come back so must be related to the Sourcegraph extension.
