### ISSUE TITLE
Support of changing the background color of the code block in color schemes

### ISSUE THREAD

**Issue by Katarn** [Microsoft/vscode#55471] opened 2018-07-31 13:38 UTC
As, for example, it works in SublimeText.

![image](https://user-images.githubusercontent.com/6339978/43462988-26f61ae6-94e0-11e8-858a-f6f45498153d.png)

**Comment by aeschli** [comment] 2018-07-31 21:25
duplicate of #3429

**Closed by aeschli** 2018-07-31 21:25 UTC
Labels: editor, editor-contrib
