### ISSUE TITLE
Ubuntu 21.10: The whole vscode application looks blur under 200% DPI scaling

### ISSUE THREAD

**Issue by Demonese** [microsoft/vscode#135492] opened 2021-10-20 17:13 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-20-generic
- OS Version:
Ubuntu 21.10 amd64
GNOME 40.4.0
Wayland

Steps to Reproduce:

1. Setup 200% DPI scaling (4k monitor)
![1](https://user-images.githubusercontent.com/57629614/138139720-ca1785f6-c8c2-467e-8882-de8ff0e818a5.png)
2. Open vscode
![2](https://user-images.githubusercontent.com/57629614/138139603-c3cfb640-cad2-4d38-b24c-7b8ca51eaac3.png)

Update:

Disable "Fractional Scaling" and then the problem solved. But if other users are using 125%, 150% or 175% scaling, this problem might not avoid?

**Comment by mpstv** [comment] 2021-11-03 15:23
Hi everyone.

I have the same issue when scaling the interface to 125% on Ubuntu 21.10 vscode looks blur.

**Comment by modzilla99** [comment] 2021-11-05 09:56
This is because it's running in on X11 and not wayland, launching it with:
code -enable-features=UseOzonePlatform -ozone-platform=wayland

fixes that problem, but then (at least for me) the header bar goes poof! At least shortcuts like Super + Arrowkeys work.

**Comment by modzilla99** [comment] 2021-11-05 10:07
You can fix it as described in this comment: https://github.com/microsoft/vscode/issues/109176#issuecomment-846656606

**Comment by mpstv** [comment] 2021-11-08 09:12
@modzilla99 
`code --enable-features=UseOzonePlatform --ozone-platform=wayland` - worked for me. Thanks!

**Comment by dieseltravis** [comment] 2022-04-09 01:09
Are there newer flags that can be used?
```
❯ code --enable-features=UseOzonePlatform --ozone-platform=wayland
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.

❯ code --version
1.66.1
8dfae7a5cd50421d10cd99cb873990460525a898
x64
```

**Comment by rorysteward** [comment] 2022-04-12 20:57
Same issue here on Ubuntu 22.04 with 125% fractional scaling enabled, anyway it is related to Chrome as I have the same problems with it. I don't think this issue was present on Ubuntu 20.04

**Comment by Zhou-Yicheng** [comment] 2022-04-13 12:10
@dieseltravis, @rorysteward  try vscode insiders (Version: 1.67.0), its newer Electron fixes the issue

**Comment by yangcheng** [comment] 2022-07-08 03:24
> 

I am on  1.68.1 with same issue, it did not start the app
`
>code --enable-features=UseOzonePlatform --ozone-platform=wayland                                                                                      [11:02:29]
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
>code --version                                                                                                                                        [11:22:31]
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
`

**Comment by porjo** [comment] 2022-08-09 23:32
> code --enable-features=UseOzonePlatform --ozone-platform=wayland
             
This worked for me using code 1.70.0 package on Fedora 36 running Wayland with 150% scaling. Window decorations are missing however including minimise, maximise etc (easy to overcome with keyboard shortcuts).

**Comment by miromarszal** [comment] 2022-08-15 12:51
Does not work on 1.70.1 on Ubuntu 22.04. The app does not start at all with 
```
code --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by cbrnr** [comment] 2022-08-16 08:20
You can enable window decorations with another flag:

```
code --ozone-platform=wayland --enable-features=WaylandWindowDecorations
```

This has an effect only when "Window: Title Bar Style" is set to "native". If set to "custom", custom window decorations are shown with some nice space-saving features, but unfortunately the window drop shadow is missing then.

**Comment by zjalicf** [comment] 2022-08-16 12:30
To anyone still having problems, there is a good chance the following fix will work for your setup.
I have a 1920x1080 monitor and carbon x1 thinkpad with 2K screen. I run latest 22.04 ubuntu and wayland is enabled by default. I think you shouldnt disable it because for example, it breaks screen sharing, fonts get blurry, insane lag when window swtiching etc. Also, fractional scaling still sucks for electron apps so that should be disabled also.

The solution is to install gnome-tweaks: 
`sudo apt install gnome-tweak-tool`

After that, launch it, go to Fonts. There you can adjust Interface Text, Document Text etc and you can set the Scaling Factor which seems to not affect VSC in any way. For me, I just set it to 1.50 there, fonts all 13 and its working great!

**Comment by porjo** [comment] 2022-08-16 22:34
> Does not work on 1.70.1 on Ubuntu 22.04. The app does not start at all with

@miromarszal  I've since switched to [VSCodium](https://github.com/VSCodium/vscodium) and had the same problem with it - adding `--log debug` worked for me e.g

```
code  --enable-features=UseOzonePlatform --ozone-platform=wayland --log debug
```

@cbrnr thanks for the tip about window decorations :+1:

**Comment by patoi** [comment] 2022-09-01 13:57
This works to me: https://stackoverflow.com/questions/51456526/how-to-change-font-size-in-vs-code-sidebar

**Comment by miromarszal** [comment] 2022-09-22 13:26
> I've since switched to [VSCodium](https://github.com/VSCodium/vscodium) and had the same problem with it - adding `--log debug` worked for me
@porjo thanks for the tip. Unfortunately, this doesn't help. I've seen this method somewhere, including multiple `--log debug` entries, but it doesn't start the app, no matter how many I include.

**Comment by tabish-javed** [comment] 2022-09-27 18:34
Try disabling Wayland on Ubuntu, just un-comment "WaylandEnable=flase" in /etc/gdm3/custom.conf and reboot/re-login.

```
$ cat /etc/gdm3/custom.conf |head -7
# GDM configuration storage
#
# See /usr/share/gdm/gdm.schemas for a list of available options.

[daemon]
# Uncomment the line below to force the login screen to use Xorg
WaylandEnable=false # <<< UN-COMMENT THIS LINE
$
```

**Comment by hacefresko** [comment] 2022-12-04 19:48
Same problem here. Fixed it by adding `--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland` to my `code.desktop` file, but now whenever I run the app from the task bar I have two instances of vs code, which bothers me a little. Anyway, I hope this will we fixed soon, and not only in VS code since it affects every Electron app in Ubuntu when using the fractional scaling

**Comment by deepak1556** [comment] 2022-12-07 12:33
Closing since issue is resolved when running with wayland.

**Closed by deepak1556** 2022-12-07 12:33 UTC

**Comment by nguyendkin** [comment] 2022-12-13 04:14
1.
/usr/share/applications/code.desktop 
Edit xec=/usr/share/code/code --unity-launch %F to Exec=/usr/share/code/code --enable-features=UseOzonePlatform %U --ozone-platform=wayland --unity-launch %F. (For vscode in the dock)

2.
/usr/bin/code
Edit ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@" to ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --enable-features=UseOzonePlatform --ozone-platform=wayland --ms-enable-electron-run-as-node "$@". (For "code .")

3. If your vscode was hide title bar
 "window.titleBarStyle": "custom"

**Comment by Melebius** [comment] 2023-01-03 10:26
Is there any fix for the app not being launched with `--ozone-platform=wayland` (Ubuntu 22.04 with Wayland)? I am sorry but I haven’t found any solution for users who reported this problem on this page.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
$ code  --enable-features=UseOzonePlatform --ozone-platform=wayland --log debug
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
$ code --version
1.74.2
e8a3071ea4344d9d48ef8a4df2c097372b0c5161
x64
```
Only [switching to X11](https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop) seems to work around the issue for me.

**Comment by cbrnr** [comment] 2023-01-03 10:39
Just to make sure, we all see the warnings, but you can ignore them because they are passed to Electron correctly. So this means your UI is still blurry?

**Comment by Melebius** [comment] 2023-01-03 11:42
@cbrnr
- My VS Code UI is blurry if `code` is launched without the parameters.
- It does not start at all if the parameter `--ozone-platform=wayland` is specified.
- It works correctly on X11.

**Comment by dustojnikhummer** [comment] 2023-01-22 11:36
> @cbrnr
> 
> * My VS Code UI is blurry if `code` is launched without parameters, I am using Wayland and having Fractional scaling on.
> * It does not start at all if the parameter `--ozone-platform=wayland` is specified. Even with `--log debug`, I am getting no additional messages apart from the warnings.
> * VS Code appears correctly without fractional scaling or when using X11.
> 
> I am using the Snap release of VS Code.
> 
> ```
> $ type code
> code is /snap/bin/code
> ```

I can confirm same blurry UI under Wayland with fractional scaling (KDE), but I'm using the Flatpak version.
I don't think this should get closed until you don't need any flags to run it in Wayland mode

**Comment by deepak1556** [comment] 2023-01-26 12:26
@Melebius VSCode snap at the moment cannot run with native wayland support, please follow https://github.com/microsoft/vscode/issues/146890 for updates. You can either use debian package or launch with `--ozone-platform=x11` as workaround.
