### ISSUE TITLE
Allow folder creating from Simple File Dialog

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137368] opened 2021-11-17 15:06 UTC
Issue Type: <b>Feature Request</b>

After opening a file provided by my extension's FileSystemProvider, then using File\Save As... from the menu, the Simple File Dialog appears. This is expected. However, if I edit the full path to include one or more folders that don't currently exist on the target filesystem I am not permitted to OK the dialog. The error message is 'Please enter a path that exists.'

Please allow a non-existent path and leave it up to the FileSystemProvider to decide whether to reject the save or to create the new folder(s) and proceed with the save.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by alexr00** [comment] 2021-11-19 09:45
Duplicate of https://github.com/microsoft/vscode/issues/71425

**Closed by alexr00** 2021-11-19 09:45 UTC
