### ISSUE TITLE
All cells are collapsed when viewing a notebook diff

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#226818] opened 2024-08-27 17:11 UTC
Testing #226664

1. Open a notebook with several cells
2. make a change in a cell and open the diff view

:bug: all cells are hidden

![Recording 2024-08-27 at 10 11 26](https://github.com/user-attachments/assets/84454e92-c3df-4fdb-bba8-b1c80816b098)

**Comment by DonJayamanne** [comment] 2024-08-27 20:16
@amunger Please can you try this again,
This time
* Reload VS Code
* Open the diff viewer first
* There's a known issue where making changes to the notebook after you've loaded the diff viewer once before will not reflect the changes made subsequently.
* To replicate the issue, after you've opened the diff viewer once, then make a change to a cell and come back into the diff viewer & open again & see if it works

**Comment by amunger** [comment] 2024-08-27 20:31
If I reload vs code, the diff view shows the cells

**Comment by DonJayamanne** [comment] 2024-08-27 22:08
Duplicate of https://github.com/microsoft/vscode/issues/226766

**Closed by DonJayamanne** 2024-08-27 22:08 UTC
Labels: bug, info-needed, notebook, notebook-diff
