### ISSUE TITLE
[FR] Option to keep the suggestion icons' original colors

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#126765] opened 2021-06-20 03:37 UTC
The white icon is _**very weird**_ and _**very distracting**_:

![image](https://user-images.githubusercontent.com/28700378/122661344-e2420880-d1bb-11eb-97d9-807ab3501670.png)

The original behavior before `v1.57.0` was so much better:

![image](https://user-images.githubusercontent.com/28700378/122661394-5c728d00-d1bc-11eb-9054-e0f980862761.png)

Hope there's a way to revert to the old behavior.

**Comment by usernamehw** [comment] 2021-06-20 08:11
/duplicate of #125998. It should be fixed in **1.58.0**

**Closed** 2021-06-20 08:12 UTC
Labels: *duplicate
