### ISSUE TITLE
Turn vscode.dev into an installable PWA

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#136616] opened 2021-11-07 12:25 UTC
I think turning vscode.dev into an installable PWA like Codesandbox or Stackblitz would be awesome.

Codesandbox:
![image](https://user-images.githubusercontent.com/29214635/140644682-7b37afd4-baf9-4ac2-a0f9-fd18635065ab.png)

Stackblitz:
![image](https://user-images.githubusercontent.com/29214635/140644731-d37113e4-5905-4d1c-82cd-d92a084ecb79.png)

**Comment by yume-chan** [comment] 2021-11-08 01:59
Duplicate of #135781

**Closed** 2021-11-08 06:16 UTC
Labels: *duplicate
