### ISSUE TITLE
Wrong Indent Level in JSX

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#30825] opened 2017-07-17 02:26 UTC
- VSCode Version:1.14.1
- OS Version:Windows 7

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/15119639/28253825-1106bbc2-6ada-11e7-9e49-dba70c042f67.png)

2.When press Tab in the newline between div tag, the indent level is wrong. Press enter after the div, the indent level is right. Only appears in JSX, I have test in the HTML file and it works well.

Reproduces without extensions: Yes

**Comment by duro** [comment] 2017-11-18 06:02
I definitely experience this as well. Also problems with copy and pasting JSX. The indent levels are always out of wack when I copy and past from one jest level to another.

**Comment by duro** [comment] 2017-11-18 06:03
Just for context case, I am running the latest version of VSCode

**Comment by savovs** [comment] 2018-01-02 18:38
I have a similar issue here's a GIF: http://www.giphy.com/gifs/3ohc0Y4D2kzfD2IVNu

**Comment by JKRy** [comment] 2018-02-10 19:15
I am also seeing this - however I am not getting correct indentation for either of @savovs examples above, on Code version 1.20.0. Seeing the same as above on Insiders version 1.21.0 though.

**Comment by silvenon** [comment] 2018-07-24 18:20
Does someone know where indentation rules for JavaScript/JSX are defined?

**Comment by mattfysh** [comment] 2018-09-21 11:08
I've just noticed this too, it will only correctly auto-indent if the element has no attributes assigned.

e.g. pressing enter after `<span>` will indent correctly, but if you have `<span className="foo">` it will not

Interestingly, it will work if pressing enter after `<span >`
(space between tagname and closing angle bracket)

**Comment by pettyron** [comment] 2018-11-02 18:37
Other issues about this have been reported as well.

[Issue: 6194](https://github.com/Microsoft/vscode/issues/61954)
[Issue: 60860](https://github.com/Microsoft/vscode/issues/60860)

It seems like everyone issue points out the problem and the response is always needs more information.
It would be nice to have this resolved as the issue seems to have been unaddressed for over a year.

**Comment by mjbvz** [comment] 2019-04-09 21:33
I cannot reproduce the original issue anymore

The other issues people  posted about indent after `enter` are duplicates of #65955. Should be fixed in the latest VS Code insiders build

**Closed by mjbvz** 2019-04-09 21:33 UTC
Labels: bug, editor-autoindent, languages-basic
