### ISSUE TITLE
Debug: Clicking a callstack row calls `openEditor` twice

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#136829] opened 2021-11-10 06:59 UTC
Add a `console.log(new Error().stack)` into https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/contrib/debug/common/debugSource.ts#L75

Follow steps from https://github.com/microsoft/vscode/issues/136684#issuecomment-964356897. Notice how `openEditor` is called 2 times:

```
debugSource.js:53 Error
    at Source.openInEditor (debugSource.js:53)
    at StackFrame.openInEditor (debugModel.js:322)
    at DebugService.focusStackFrame (debugService.js:691)
    at focusStackFrame (callStackView.js:214)
    at callStackView.js:222
    at Emitter.fire (event.js:435)
    at TreeResourceNavigator._open (listService.js:494)
    at TreeResourceNavigator.onPointer (listService.js:472)
    at listService.js:438
    at Emitter.fire (event.js:435)
    at event.js:43
    at Emitter.fire (event.js:435)
    at event.js:43
    at Emitter.fire (event.js:435)
    at TreeNodeListMouseController.onViewPointer (listWidget.js:535)
    at TreeNodeListMouseController.onViewPointer (abstractTree.js:852)
    at event.js:65
    at Emitter.fire (event.js:435)
    at event.js:43
    at Emitter.fire (event.js:435)
    at HTMLDivElement.fn (event.js:11)
debugSource.js:53 Error
    at Source.openInEditor (debugSource.js:53)
    at StackFrame.openInEditor (debugModel.js:322)
    at callStackView.js:223
    at Emitter.fire (event.js:435)
    at TreeResourceNavigator._open (listService.js:494)
    at TreeResourceNavigator.onPointer (listService.js:472)
    at listService.js:438
    at Emitter.fire (event.js:435)
    at event.js:43
    at Emitter.fire (event.js:435)
    at event.js:43
    at Emitter.fire (event.js:435)
    at TreeNodeListMouseController.onViewPointer (listWidget.js:535)
    at TreeNodeListMouseController.onViewPointer (abstractTree.js:852)
    at event.js:65
    at Emitter.fire (event.js:435)
    at event.js:43
    at Emitter.fire (event.js:435)
    at HTMLDivElement.fn (event.js:11)
```

**Comment by joaomoreno** [comment] 2022-01-26 13:01
Sorry for the delay here. The problem isn't in the list widget but in the call stack view, which does two things simultaneously to open the file:

https://github.com/microsoft/vscode/blob/c6e58d126f6b5676242e32b34180b2a595f29b51/src/vs/workbench/contrib/debug/browser/callStackView.ts#L311-L312

@roblourens Am I right in assigning this to you now?

**Closed** 2022-04-13 22:49 UTC
Labels: bug, debug
