### ISSUE TITLE
Can not navigate from error list to file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3506] opened 2016-02-26 15:55 UTC
* vscode express smoke test repo
* ctrl + shift + B, ctrl + shit + M
* click on one of the errors to navigate to
* get an error, event though routes/index.js exists

Though this seems to work in the vscode repo nicely

![screen shot 2016-02-26 at 16 54 34](https://cloud.githubusercontent.com/assets/1926584/13357243/b0a36c04-dca9-11e5-9e20-26eaf3f36fab.png)

**Comment by joaomoreno** [comment] 2016-02-27 19:59
Duplicate of #3512

**Closed by joaomoreno** 2016-02-27 19:59 UTC
Labels: bug
