### ISSUE TITLE
Option for closing Debug Panel after Debug Session ends/keep Focus on Editor during Debug

### ISSUE THREAD

**Issue by lrwagner** [microsoft/vscode#114494] opened 2021-01-17 15:48 UTC
1. an option to auto-close the debug panel after debug session stops. There is already a setting to open the explorer panel after debug stops (debug.openExplorerOnEnd).
2. an option to keep focus on the editor tab when starting a debug session. Using VscodeVim with bindings for debug session control it feels annoying to switch back to the editor window for stepping though code etc.

**Comment by isidorn** [comment] 2021-01-18 10:50
1. Duplicate of https://github.com/microsoft/vscode/issues/110349
2. When I press F5 and I start debugging the focus is still in the Editor for me. What are you doing differetnyl and where does focus end up for you?

**Comment by lrwagner** [comment] 2021-01-18 14:55
Interesting: I'm using vimvscode to access debugging (mapped <leader>df to "workbench.action.debug.start", my leader being space)
If I'm using the default F5 keybind to enter debug mode focus stays in the editor for me, too. 

This it what my remap looks like in settings.json:
`    "vim.normalModeKeyBindingsNonRecursive": [
 {
      "before": [
        "<leader>",
        "d",
        "f"
      ],
      "commands": [
        "workbench.action.debug.start"
      ]
    }
]`

**Comment by isidorn** [comment] 2021-01-18 15:36
@lrwagner This sounds like some extensino passes focus to the integrated terminal.
I suggest you use extension bisect and figure it out.
I see you are using Python, so this sounds like an issue for the python extension - they are probably passing focus to the terminal

If it works for Insiders then there is nothing we can do in vscode core. Thus closing this and also I can not repro

**Closed by isidorn** 2021-01-18 15:36 UTC
Labels: debug, needs more info
