### ISSUE TITLE
ms-vscode-remote.remote-wsl activation error

### ISSUE THREAD

**Issue by vkoprivica** [microsoft/vscode#110299] opened 2020-07-16 20:59 UTC
```
[2020-07-16 15:00:25.859] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onResolveRemoteAuthority:wsl"}
[2020-07-16 15:00:25.860] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/aavkoprivi/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4/dist/extension
[2020-07-16 15:00:25.865] [exthost] [error] Activating extension ms-vscode-remote.remote-wsl failed due to an error:
[2020-07-16 15:00:25.865] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:375:7)
	at Function.Module._nodeModulePaths (internal/modules/cjs/loader.js:590:37)
	at Module.load (internal/modules/cjs/loader.js:777:23)
	at Module._load (internal/modules/cjs/loader.js:693:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:348)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:839)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:940:198)
	at Module.require (internal/modules/cjs/loader.js:820:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:33:205)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:945:34)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:599)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:834:692)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:832:453)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:405)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:83
	at Array.map (<anonymous>)
	at h._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:71)
	at h.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:546)
	at h._activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:833:300)
	at h.$resolveAuthority (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:842:313)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-07-16 15:00:25.974] [exthost] [info] eager extensions activated
[2020-07-16 15:54:16.538] [exthost] [info] extension host started
[2020-07-16 15:54:16.547] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onResolveRemoteAuthority:wsl"}
[2020-07-16 15:54:16.547] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/aavkoprivi/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4/dist/extension
[2020-07-16 15:54:16.554] [exthost] [error] Activating extension ms-vscode-remote.remote-wsl failed due to an error:
[2020-07-16 15:54:16.554] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:375:7)
	at Function.Module._nodeModulePaths (internal/modules/cjs/loader.js:590:37)
	at Module.load (internal/modules/cjs/loader.js:777:23)
	at Module._load (internal/modules/cjs/loader.js:693:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:348)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:839)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:940:198)
	at Module.require (internal/modules/cjs/loader.js:820:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:33:205)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:945:34)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:599)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:834:692)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:832:453)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:405)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:83
	at Array.map (<anonymous>)
	at h._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:71)
	at h.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:546)
	at h._activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:833:300)
	at h.$resolveAuthority (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:842:313)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-07-16 15:54:16.873] [exthost] [info] eager extensions activated
```

**Comment by alexdima** [comment] 2020-11-11 19:50
Yeah. No idea without steps.

Duplicate of https://github.com/microsoft/vscode/issues/80971 

@aeschli The stack trace is in the require call to load the wsl remote extension. At that time (when the resolver is loaded), the wsl remote extension is the only extension loaded in the extension host, so no other extension could be causing this. 

My best guess is that @vkoprivica has some environmental variables set which completely mess up the code loading of nodejs. @vkoprivica Did you ever customize your environmental variables?

**Closed** 2020-11-24 11:24 UTC
Labels: needs more info
