### ISSUE TITLE
Cannot debug TypeScript file if source map is in a different directory

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#4705] opened 2016-03-28 05:38 UTC
It's currently not possible to debug a TypeScript file when the source map is stored in a different directory.

However, I feel it should be possible to debug TypeScript files even when the corresponding source maps are stored in a different directory.
- VSCode Version: 0.10.11
- OS Version: Windows 10/64

Steps to Reproduce:

https://github.com/SetTrend/VSC-Debugger

**Comment by isidorn** [comment] 2016-03-29 10:06
@SetTrend Very cool repro septs. however I do not see the `launch.json` as part of that repository? Have you tried setting the 'outDir' in your `launch.json` to point to your `output` folder

**Comment by weinand** [comment] 2016-03-29 10:11
@SetTrend yes, please set 'outDir' to 'output' and let me know if that works. If not I will reopen this issue.

**Comment by SetTrend** [comment] 2016-03-29 20:42
@isidorn : Oops... I accidentally excluded the .vscode folder. Added it now to the repository.

@weinand : Nope, the suggested solution didn't help:

![debugerror](https://cloud.githubusercontent.com/assets/9283914/14123150/746dbd92-f5ff-11e5-8445-c43c7addf5b9.png)

**Comment by weinand** [comment] 2016-03-29 22:15
@SetTrend thanks for making the project available.

There a two problems with your setup:

1. `outDir` expects the folder where the generated code lives. For your project this is `${workspaceRoot}\\output\\js`.

2. the source map spec says: 'If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap (like resolving script src in a html document)'.
In your source map the concatenated path is `../.././src/typescript/X/Test.ts` which is identical to `../../src/typescript/X/Test.ts`. Resolving this relative to the source map location `VSC-Debugger/output/maps/js/X/`results in `VSC-Debugger/output/maps/js/X/../../src/typescript/X/Test.ts` which can be simplified to `VSC-Debugger/output/maps/src/typescript/X/Test.ts`. This location does not exist.

The correct `sourceRoot` for your project is `../../../../src/typescript/`. With this setting breakpoints work fine.

There is still a bug in the source-map npm module that VS Code uses which prevents that paths with single dot segments '/./' are not handled correctly. 

BTW, you can use forward slashes in your launch.json. They are portable and do not need escaping...

**Comment by SetTrend** [comment] 2016-04-03 10:18
Thanks, @weinand , for your very informative answer!

With your information I was now able to update the source map paths assignment. I uploaded an update to GitHub to reflect the changes I made.

However, the TypeScript source is still not used by the debugger:

![typescript](https://cloud.githubusercontent.com/assets/9283914/14231895/c1f31f1a-f994-11e5-8496-eec9f564063b.png)

Is that the bug you have spotted? Or is it due to #2544 ? Shouldn't we re-open #2544 anyway? It contains action items to solve an issue which haven't been implemented yet. The feature request therein is still valid.

**Comment by weinand** [comment] 2016-04-03 20:09
@SetTrend I've pulled your changes and did a 'gulp tsc' on Windows 10 but the `sourceRoot` in the map file still lacks another '..'. After adding it, VS Code opens the TypeScript for me:

![2016-04-03 22-03-33](https://cloud.githubusercontent.com/assets/1898161/14234646/16f401ca-f9e8-11e5-9153-a336fff2157a.png)

BTW, the trace output in your screenshot looks different then my Windows 10 screenshot:

![2016-04-03 22-06-49](https://cloud.githubusercontent.com/assets/1898161/14234662/76d3f758-f9e8-11e5-8846-0602aaa36f87.png)

Your 'src' paths on the right hand side start with 'file://' whereas mine do not. This might be another issue...

**Comment by SetTrend** [comment] 2016-04-03 20:55
Strange... Perhaps it's because I have some [spaces in the path (see this issue)](https://github.com/nodejs/node/issues/5060)?

Actually I found the three `".."` in the path alright. Have you seen my code in the `tsc` task:

```js
.pipe(pi.sourcemaps.write(path.relative(dest, mapsRoot)   // relative to gulp.dest() folder
                         , { includeContent: false
                           , sourceRoot: path.relative(mapsRoot, tsRoot)  // TypeScript source root, relative to maps root
                           }))
```

The path is getting calculated. The trace log gives the correct path to the TypeScript file. It just isn't used.

**Comment by weinand** [comment] 2016-04-03 21:14
@SetTrend yes, the space in the path could be the reason why the 'src' pathes start with 'file://'. I will try to reproduce.

I'll try again to explain why 'sourceRoot' is wrong (no, I will not debug the code in the gulp script because VS Code only uses the resulting source map ;-)

Here is the concatenation based on the source map v3 spec:

```
src = <location of source map> + <sourceRoot> + <sources entry>
src = 'output/maps/js/X' + '../../../src/typescript' + 'X/Test.ts'
src = 'output/src/typescript/X/Test.ts'
```

The resulting path still has an 'output' segment.

**Comment by weinand** [comment] 2016-04-03 21:30
@SetTrend no, spaces in paths do not result in pathes starting with 'file://':

![2016-04-03 23-27-42](https://cloud.githubusercontent.com/assets/1898161/14235069/001d9af4-f9f4-11e5-8b73-ab3523e0217d.png)

**Comment by SetTrend** [comment] 2016-04-13 04:38
There's one thing I don't understand: Why does the trace give two different paths to the `.ts` source file:

![selection](https://cloud.githubusercontent.com/assets/9283914/14482928/48cd8d72-0142-11e6-99d2-30c0f140deba.png)

**Comment by weinand** [comment] 2016-04-13 15:30
@SetTrend the first lookup is using a more lenient lookup that I wrote which only works for files (not locations within a file). The second is using the standard source map npm module which I cannot configure to become 'lemient'.

**Comment by bluntcoder** [comment] 2017-02-06 04:12
@weinand Trying to use your debugging tips but https://github.com/Microsoft/vscode-react-native/issues/391 (apologies I put it in the wrong project)

**Comment by SetTrend** [comment] 2017-02-06 10:13
Just to drop a note here: I'm currently working in a full-time project working with legacy ASP.NET, so unfortunately I cannot follow my GitHub threads at this time.

If you can wait: The project I'm participating in is planned to be completed in April. I'll return to VC Code R&D then.

And I will then finally have time to solve a long-term [issue in gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps/issues/191). When that issue is solved it might help solving this issue here. But I'm not sure though at this time.

**Comment by a8775** [comment] 2017-03-31 08:37
+1

**Comment by weinand** [comment] 2017-08-17 13:34
This should work now. Please reopen if you see it again.

**Closed** 2017-08-17 13:34 UTC
Labels: bug, debug
