### ISSUE TITLE
parameters are not aligned in function with many parameters

### ISSUE THREAD

**Issue by lucap86** [Microsoft/vscode#23101] opened 2017-03-23 14:55 UTC
As said by @torryt in #4039 for functions with many parameters when they are splitted over multiple lines, Auto-Indent breaks the parameter alignment.
this also cause tslint "parameters are not aligned (align)" warn

![align](https://cloud.githubusercontent.com/assets/15343100/24253624/18a12de4-0fe1-11e7-8f48-e8f4a76ba391.gif)

**Comment by mjbvz** [comment] 2017-03-23 22:48
@lucap86 Thanks for the report. As a workaround, use `format selection` or `format document` which correctly handles this case in my testing

**Comment by lucap86** [comment] 2017-03-24 07:55
hi @mjbvz 

```format selection``` or ```format document``` cause the same issue for me

**Comment by mjbvz** [comment] 2017-03-24 19:41
@lucap86 Do you have any extensions installed? Try running code with `--disable-extensions` to ensure you are using the builtin formatter

**Comment by lucap86** [comment] 2017-03-25 09:09
nope...
with --disable-extensions:

![fdoc](https://cloud.githubusercontent.com/assets/15343100/24321039/f3202b3e-1142-11e7-80fc-3f33d354a6dd.gif)
![fsel](https://cloud.githubusercontent.com/assets/15343100/24321040/f324f0e2-1142-11e7-94bd-94ea3a77e9b7.gif)

**Comment by lucap86** [comment] 2017-06-09 08:10
Could someone kindly pick this up?

I think that is it a blocker for VScode to autoformat TS appropriately.
My code become warned everyday more because of that issue :(

Thanks greatly!

**Comment by fengcen** [comment] 2017-06-17 04:25
@mjbvz I need this feature too. Thanks.

**Comment by lucap86** [comment] 2017-07-28 12:14
![a](https://user-images.githubusercontent.com/15343100/28716729-0d3c47c8-739f-11e7-98b0-5fcc0882e3c2.gif)

**Comment by york-xtrem** [comment] 2017-08-11 07:23
+1

**Comment by hoegge** [comment] 2017-08-15 20:33
+1 @mjbvz 
Would be very nice to get fixed - also in VS 2017

**Comment by xealot** [comment] 2017-10-03 16:44
I know this seems like a low rent issue, but it's frustrating to format your file and then have your linter explode on you.

If anyone wants to hand-wave in the direction this could be corrected maybe someone could fix it.

**Comment by Dashue** [comment] 2017-10-03 17:06
It's not ideal, but I've adopted this pattern for the time being. Readable enough for me

constructor(
    fb: FormBuilder,
    public service: Servce1,
    private service2: Service2
  ) {
    /* Put logic here */
  }

**Comment by hoegge** [comment] 2017-10-04 05:31
Why not just fix the formatter to do it right?

**Comment by Ebraheem-Alrabee3** [comment] 2017-10-25 13:58
@lucap86 
You can download TSlint extension for VS code 
then got to file/preference/setting 
and change the property "tslint.autoFixOnSave" to true 

by this even if you scattered the code and ruined the format 
at save it will be fixed in TSlint formatter rules not VS code .

**Comment by Dashue** [comment] 2017-10-25 14:02
Would you mind including the name of the tslint formatter rule to automatically align?

**Comment by Ebraheem-Alrabee3** [comment] 2017-10-25 14:20
@Dashue
Sorry Johan, I have tried to find out the rule for the same purpose with no success for now.

**Comment by pvjonesop** [comment] 2017-11-09 18:06
This is not fixed for me, even with tslint.autoFixOnSave set to true.

**Comment by pvjones** [comment] 2017-11-09 18:31
A workable fix for me involves setting: 
```  "editor.formatOnSave": false,
  "javascript.format.enable": false,
  "typescript.format.enable": false,
  "tslint.autoFixOnSave": true,```

**Comment by ramtech123** [comment] 2017-11-14 05:34
@Dashue thanks, that helped me to overcome this problem. I couldn't initially understand what was the difference.

Putting it in words if somebody needs it in future - _function name/constructor in its dedicated line and all the parameters are in subsequent lines_, thus taking care of alignment as well as indentation.

![image](https://user-images.githubusercontent.com/22439295/32764424-6b52b388-c92b-11e7-941e-40c00f0754d1.png)

**Comment by Dashue** [comment] 2017-11-14 11:47
Cheers for making the explanation more clear!

**Comment by ericsnap** [comment] 2017-12-14 23:15
Just curious why @mjbvz marked this as _as-designed_ and _feature-request_
This is clearly a bug and because its not labeled as such, is not being worked on.

**Comment by mjbvz** [comment] 2017-12-14 23:46
This is not a bug. Our formatter is doing what it was designed to do here

Looks like https://github.com/Microsoft/TypeScript/issues/11629 already tracks this upstream. Let's continue tracking this feature over there since this would need to be fixed on the TS side

**Closed by mjbvz** 2017-12-14 23:47 UTC
Labels: as-designed, feature-request, formatting, javascript, typescript, upstream

**Comment by ericsnap** [comment] 2017-12-15 00:41
@mjbvz thanks for clarifying. And it looks like I already added my $0.02 on that TypeScript issue...
