### ISSUE TITLE
VS code suddenly very slow

### ISSUE THREAD

**Issue by Pibe97** [microsoft/vscode#216593] opened 2024-06-19 08:55 UTC
Type: <b>Performance Issue</b>

From one day to another, vs code has become super slow and I am not sure why. The same issue persists when I disable all extensions.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 5.15.0-87-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 3|
|Memory (System)|31.07GB (26.21GB free)|
|Process Argv|--force-user-env --no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id 2b7ee110-b35a-49cb-9a83-10f4026951c2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   159	  9940	code main
    0	    32	  9942	   zygote
    0	    32	  9943	   zygote
    0	   255	 10021	window [1] (jax_helper_fns.py - LLM_KSE - Visual Studio Code)
    0	    95	 21316	window [4] (Issue Reporter)
    0	    64	  9977	   utility-network-service
    0	    95	 10051	shared-process
    0	     0	 21327	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 21328	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   191	 10052	fileWatcher [1]
    0	   223	 10097	extensionHost [1]
    0	    32	 10140	     /home/pbeck/miniconda3/envs/tf/bin/python /home/pbeck/.vscode/extensions/ms-python.isort-2023.10.1/bundled/tool/lsp_server.py
    0	   255	 10174	     electron-nodejs (bundle.js )
    0	    64	 10115	ptyHost
    0	     0	 10135	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 10149	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 10495	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.204.0
copilot-chat|Git|0.16.1
rainbow-csv|mec|3.12.0
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by MarcusSp** [comment] 2024-06-19 09:24
I have the same problem:

Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:43.666Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-35-generic snap

**Comment by Pibe97** [comment] 2024-06-19 09:28
I downgraded to 1.89 and that seems to fix the issues. Apparently it is the 1.90.1 update that makes everything super sluggish. Lesson learnt: disable auto-update.

**Comment by alexr00** [comment] 2024-06-19 09:33
Can you please share a performance profile as per https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-sluggish ?

**Comment by MarcusSp** [comment] 2024-06-19 09:41
> Can you please share a performance profile as per https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-sluggish ?

Would love to, but in my case VS code crahses when I try to use the developer tools.

**Comment by Pibe97** [comment] 2024-06-19 09:45
> > Can you please share a performance profile as per https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-sluggish ?
> 
> Would love to, but in my case VS code crahses when I try to use the developer tools.

Same here!

**Comment by MarcusSp** [comment] 2024-06-19 09:48
> I downgraded to 1.89 and that seems to fix the issues. Apparently it is the 1.90.1 update that makes everything super sluggish. Lesson learnt: disable auto-update.

Can confirm that downgrading to 1.89 solves the issue. Maybe auto updating is really a bad choice...

**Comment by alexr00** [comment] 2024-06-19 10:14
Looks like you're using the snap. Duplicate of https://github.com/microsoft/vscode/issues/212494.

**Closed by alexr00** 2024-06-19 10:14 UTC
