### ISSUE TITLE
Alt menu shortcuts do not work when focus is in terminal

### ISSUE THREAD

**Issue by papadi** [Microsoft/vscode#33517] opened 2017-08-30 13:24 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-mocha|Com|0.1.1
vscode-mocha-test-runner|cst|0.2.2
githistory|don|0.2.3
python|don|0.7.0
tslint|eg2|0.17.0
phpunit|ema|1.1.0
vscode-great-icons|emm|2.1.15
php-debug|fel|1.11.1
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
phpcs|ika|0.7.0
vsclassic-icon-theme|jez|1.0.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.2.0
Chef|Pen|0.6.3
material-icon-theme|PKi|2.2.0

---

Steps to Reproduce:

1. Open integrated terminal
2. Press Ctrl+F
Expected: File menu should drop down
Actual: Shortcut letters are underlined in menu but menu doesn't drop down

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment] 2017-08-30 15:09
Duplicate of https://github.com/Microsoft/vscode/issues/33479

**Closed by Tyriar** 2017-08-30 15:09 UTC
Labels: integrated-terminal, new release
