### ISSUE TITLE
with the latest version of the code-insiders version, 

### ISSUE THREAD

**Issue by dcu-sharepoint** [Microsoft/vscode#48076] opened 2018-04-17 21:05 UTC
then new file/folder buttons no longer work inside a project 

- VSCode Version:

latest code-insiders version/update

- OS Version:
10.0.16299 N/A Build 16299

Steps to Reproduce:

1. click the new file button or the new folder button inside a project
2.

Does this issue occur when all extensions are disabled?: Yes/No
don't know

**Comment by mjbvz** [comment] 2018-04-17 23:15
Duplicate of #47937. Should be fixed in the newly released insiders build

**Closed by mjbvz** 2018-04-17 23:15 UTC
