### ISSUE TITLE
Unsupported compression in packaging

### ISSUE THREAD

**Issue by h2x0r** [microsoft/vscode#230933] opened 2024-10-09 14:33 UTC
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.94.1-1728111316
- OS Version: 11.11 (Debian)

Steps to Reproduce:
```
apt-get upgrade
...
dpkg-deb: error: archive '/var/cache/apt/archives/code_1.94.1-1728111316_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/code_1.94.1-1728111316_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
...
```

**Comment by gjsjohnmurray** [comment] 2024-10-09 15:39
/duplicate of https://github.com/microsoft/vscode/issues/230418 and fixed in upcoming 1.94.2

**Closed** 2024-10-09 15:39 UTC
Labels: *duplicate, triage-needed, new release
