### ISSUE TITLE
code-snippets

### ISSUE THREAD

**Issue by crj-mc** [microsoft/vscode#114698] opened 2021-01-21 12:34 UTC
Issue Type: <b>Bug</b>

Add it to your `name.code-snippets` file and you will find something unexpected.
```
"snip":{
		"prefix": "snip",
		"description": "It may be a bug",
		"body": "\\\\"
	}
```
If you use this snippet in your code, it can only show one \ instead of two.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (6.35GB free)|
|Process Argv|--crash-reporter-id 12c1efa4-8fe6-4429-b496-ef700fe1acc9|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.15.0
vscode-language-pack-zh-hans|MS-|1.52.2
jupyter|ms-|2020.12.414227025
latex-utilities|tec|0.3.7
latex-support|tor|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600cf:30247032

```

</details>

**Comment by crj-mc** [comment] 2021-01-21 13:23
I have **only one** `.code-snippets` file in my project. In addition, it work expectedly when I create a new empty folder and do it as 
[Typing doesn't trigger snippets in JSON string (#110058)](https://www.github.com/microsoft/vscode/issues/110058)

I create a new foler named `test`. The structure of this test project is shown below.
+ test
    + `.vscode`
        + `test.code-snippets`
        + `test.code-workspace`
    + `test.txt`

In `test.code-snippets`
```
{
	"snip": {
		"prefix": "snip",
		"body": "snipped!"
	}
}
```

In `test.code-workspace`
```
{
	"folders": [
		{
			"path": ".."
		}
	],
	"settings": {
		"editor.quickSuggestions": {
			"other": true,
			"strings": true
		}
	}
}
```
I don't know whether I understand [Typing doesn't trigger snippets in JSON string (#110058)](https://www.github.com/microsoft/vscode/issues/110058) clearly,
but when I type `snip` in `test.txt`, as expected, it turned into `snipped!`.

**Comment by jrieken** [comment] 2021-01-21 15:03
I don't see how comment 1 and 2 are related

**Comment by crj-mc** [comment] 2021-01-21 16:18
Comment 2 want to check if it is already covered by an existing snippets setting, but I have only a `.code-snippets` file in my project. I don't know how to check it...... You can ignore comment 2.
But you can easily test comment 1 in your computer. Maybe it is only the problem in my computer.

**Comment by jrieken** [comment] 2021-01-22 11:45
/duplicate of https://github.com/microsoft/vscode/issues/33933#issuecomment-328793257

**Closed** 2021-01-22 11:46 UTC
Labels: *duplicate, needs more info
