### ISSUE TITLE
Scroll Synchronization

### ISSUE THREAD

**Issue by jbramwell** [Microsoft/vscode#6992] opened 2016-05-28 18:13 UTC
This is more of a feature request...

When viewing a markdown file in split panes with one side being the raw markdown and the other being the HTML preview, I'd like to be able to have the two panes stay in sync as I scroll one or the other. For example, if I scroll down in the raw pane, I'd like the preview pane to scroll down as well so the markdown and preview stay in sync with each other. This is a feature found in MarkdownPad, my current/previous markdown editor, that I'd like to see in VS Code as well.

Thanks!

**Comment by rebornix** [comment] 2016-06-01 06:16
The key point of synchronized scrolling is mapping the preview html sections to markdown source. A dirty but quick solution is injecting hidden splitters to html preview then map them to line numbers of markdown source. Since we've moved the markdown rendering code to a separate extension, this kind of hack should go with the extension either.

The missing feature in VS Code is how to scroll the preview panel. We are previewing the content by triggering `htmlPreview` command with content bytes, it's likely we should bind some `scrollHandler` to the `htmlPreview` action.

**Comment by Emeryao** [comment] 2016-06-14 09:13
+1
really needs this feature

**Comment by Mucaccino** [comment] 2016-06-25 18:25
+1

**Comment by jingniao** [comment] 2016-07-20 23:47
+1

**Comment by forehalo** [comment] 2016-07-21 02:31
+1

**Comment by joshsleeper** [comment] 2016-08-02 21:52
I'd very much like this as well.
I'm sure it could be implemented as an extension, but it seems small enough that it would probably make sense to be a core feature.

**Comment by akzaidi** [comment] 2016-09-09 13:36
I'd love this feature as well, would make VS Code my default Markdown editor.
The [Markdown Editor](https://github.com/madskristensen/MarkdownEditor) for Visual Studio 2015 has this feature already. But using the full-fleshed VS IDE for markdown seems like overkill... It also has the ability to follow links, as asked for in the [issue](https://github.com/Microsoft/vscode/issues/3771)

**Comment by jordanroskelley** [comment] 2016-09-17 04:58
+1 I use VS Code md for my project docs, and having them out of sync is painful. Also, when leaving and returning to the md preview pane, it resets to the top. This makes it difficult to follow links in the md.

**Comment by b1as** [comment] 2016-09-20 14:41
+1

**Comment by mjbvz** [comment] 2016-09-20 23:22
Closing as duplicate of #5047, which also requested this feature.

**Closed by mjbvz** 2016-09-20 23:22 UTC
Labels: duplicate, feature-request

**Comment by a1018875550** [comment] 2016-09-30 03:50
+1 this feature very usefull

**Comment by neilyoung** [comment] 2016-11-22 19:58
+1 would be great

**Comment by a1018875550** [comment] 2016-11-28 04:44
when the vscode have the feature?

**Comment by iebox** [comment] 2016-12-17 08:18
+1

**Comment by nonoroazoro** [comment] 2016-12-21 03:26
+1

**Comment by amazingandyyy** [comment] 2017-02-02 19:56
amazing! Awesome! Thanks!!

**Comment by jihunx** [comment] 2017-02-03 02:37
How can I enable this function? I updated to version 1.9.0, but Synchronized Markdown Preview doesn't work. Only click event works well, other feature is not working.

**Comment by mjbvz** [comment] 2017-02-03 02:48
@jihunx Please open a new issue with some repo steps and I'll take a look

**Comment by RobDaPraia** [comment] 2017-02-03 07:54
Thanks a lot but how does this work?

Do yo need to install an extension to make the Markdown preview work?

In the documentation I read: 

```
VS Code supports Markdown files out of the box. You just start writing Markdown text, save the file with the .md extension and then you can toggle the visualization of the editor between the code and the preview of the Markdown file
```
But when I click the preview button, nothing happens, or do you have to enable a setting?

**Comment by Zicore** [comment] 2017-02-03 08:22
I also don't see it working.

**Comment by RobDaPraia** [comment] 2017-02-03 08:47
Removed all extensions beside the 'Auto-Open MarkdownPreview' uninstalled, reinstalled VSC and rebooted computer.

I see two issues:

__Issue 1:__

The preview now works out of the box for a file like:

```
# How to create documentation

__Todo:__ create content, blabla....

Explain documents are created with Markdown, commit, Git, VSTS location, automatic build and automatic deploy to web site/SharePoint

![](img/CreateDocumentationProcess.jpg)  

## Using Visual Studio Code with Markdown

[https://code.visualstudio.com/docs/languages/markdown](https://code.visualstudio.com/docs/languages/markdown)  

```

But is does not work for the same file with some meta data added to the top. Instead the preview keeps blinking and cpu usage spikes, but preview stays empty, I have to kill the Visual Studio Code task through the Task Manager. It happens with this file:

```
---  
Header: Coding Guidelines
Type:   
Title: How to create documentation  
Description:   
Version: v1.0
Date: 20170108
TopicId: 30
...  

# How to create documentation

__Todo:__ create content, blabla....

Explain documents are created with Markdown, commit, Git, VSTS location, automatic build and automatic deploy to web site/SharePoint

![](img/CreateDocumentationProcess.jpg)  


## Using Visual Studio Code with Markdown

[https://code.visualstudio.com/docs/languages/markdown](https://code.visualstudio.com/docs/languages/markdown)  

```

__Issue 2:__

I can open a long document (without the meta lines) and show the preview. But when I scroll through the document, the preview is not scrolled in sync, VSC version is 1.9.0

**Comment by RobDaPraia** [comment] 2017-02-03 08:52
Update Issue 1:

When I identify the meta block at the beginning with dashes only, then the preview works and no spkie in cpu usage. I think I will use this as a work around for the moment and change my Markdown files like this:

> Synced Scrolling with preview is still not working

```
---  
Header: Coding Guidelines
Type:   
Title: How to create documentation  
Description:   
Version: v1.0
Date: 20170108
TopicId: 30
---  

# How to create documentation

__Todo:__ create content, blabla....

Explain documents are created with Markdown, commit, Git, VSTS location, automatic build and automatic deploy to web site/SharePoint

![](img/CreateDocumentationProcess.jpg)  


## Using Visual Studio Code with Markdown

[https://code.visualstudio.com/docs/languages/markdown](https://code.visualstudio.com/docs/languages/markdown)  
```

**Comment by mjbvz** [comment] 2017-02-04 01:46
PR with fix for the cpu usage: #19894 

@RobDaPraia We currently don't support using `...` to terminate a frontmatter block. Using it will break syntax highlighting and cause the entire rest of the document to be treated as yaml instead of markdown.

In the future, please open new issues so that we can track individual issues and feature requests better

**Comment by RobDaPraia** [comment] 2017-02-08 14:25
@mjbvz Thanks for the explanation

create new issue: yes will do so next time, makes sense ;)

**Comment by RobDaPraia** [comment] 2017-02-11 09:59
Thanks for the Update: 1.9.1 

Still a question about the scrolling now with update 1.9.1:

1   When I scroll the preview window, the source window is also scrolling
2   When I scroll the source window, the preview window is not scrolling
3   When I double click in the preview window the cursor in the source window is placed on the object
4   When I click in the source window the preview window scrolls to the same location

I'm very pleased that 1,3 and 4 work, but should 2 also work out of the box or is this the intended behavior?

**Comment by mjbvz** [comment] 2017-02-13 22:13
@RobDaPraia Yes, that is the expected behavior with VSCode 1.9. Source to preview scroll sync is tracked by #19459
