### ISSUE TITLE
Terminal Integrated Split Cwd not supported chinese root

### ISSUE THREAD

**Issue by Lucasgong** [microsoft/vscode#107523] opened 2020-09-27 03:25 UTC
## Issue Description
Terminal Integrated Split Cwd not supported chinese root
I work in a folder named as "机器学习".
It works fine when I use "control`" to open a  new terminal window. 
But when I use "command \\", I suppose it will open a split terminal, but it goes wrong. 
Error message is  "terminal start wrong: start directory(cwd)“../\xe9\x87\x8f\xe5\x8c\x96\xe4\xba\xa4\xe6\x98\x93”not exists" 

## Steps to Reproduce
Remove chinese character from the folder name and it works fine.

## Environment information:
Vscode: 1.49.2
macOS catalina 10.15.7

**Comment by meganrogge** [comment] 2020-11-04 22:49
When I try this, using the command palette and using the keyboard shortcut, it splits the terminal, but goes to the upper level directory instead of the one named 机器学习
![recording (25)](https://user-images.githubusercontent.com/29464607/98176165-e0396c80-1eac-11eb-9092-22e963d249ef.gif)

**Comment by rzhao271** [comment] 2020-11-05 00:30
Duplicate of #83496

**Closed** 2020-11-05 00:31 UTC
Labels: *duplicate, bug, integrated-terminal, mac
