### ISSUE TITLE
The title of custom view moved to the Panel does not use the view's name

### ISSUE THREAD

**Issue by HampusAdolfsson** [microsoft/vscode#230383] opened 2024-10-03 11:03 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1
- OS Version: Windows 11 / 10.0.22631 Build 22631

Steps to Reproduce:
1. Pick any custom view provided by an extension (tree- or webview doesn't matter) in the side panel.
2. Move the view so that it gets its own tab in the bottom panel.
3. Observe that the name of the view's tab in the bottom panel is just its 'contextualTitle', not its name.

For example, using the "Line history" view from Gitlens:

In its original place:

![image](https://github.com/user-attachments/assets/d1504b2e-ce58-4e95-b58a-d70b41dbc128)

When placed in the bottom panel:

![image](https://github.com/user-attachments/assets/a847181e-dcf1-4d64-9c3b-3fbf8b964573)

Since Gitlens (like most extensions) uses the same contextualTitle for all views, this tab title is not enough to be able to tell what view it actually is.

A better title would be to use both the contextualTitle and the name, like it does when placing the view in a different container in the side panel:

![image](https://github.com/user-attachments/assets/41dc9e1f-2fcc-45e3-ba2b-0d21c18699e3)

**Comment by HampusAdolfsson** [comment] 2024-10-03 11:04
Possibly related to #121501 and #206362

**Comment by benibenj** [comment] 2024-10-03 15:04
Closing as a duplicate of #206362

**Closed by benibenj** 2024-10-03 15:04 UTC
