### ISSUE TITLE
Commit message is lost if you up-arrow once too many times

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [microsoft/vscode#222005] opened 2024-07-17 23:37 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  
```
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```
- OS Version:  Windows 10 with VScode accessing SSH Remote Linux server

Steps to Reproduce:

1. Open a workspace with a git repository
2. Open the "Source Control" sidebar
3. Change a file so you can enter a "Commit" message
4. Type a few lines, then up-arrow to the top of the commit message, then up-arrow one more time
5. The commit message is lost.
6. A down-arrow does not restore the previously typed commit message.

This is a data loss scenario, so I treat it as a critical bug.

**Comment by LiveFreeAndRoam** [comment] 2024-07-17 23:52
I don't know if this is relevant, but the steps I took to get here...

1. Committed some code changes, accompanied by a message
2. Undid the last commit via the VSCode menu item
3. In the "Commit Message" input field, I edited the commit message
4. This is when I up-arrowed one too many times and lost the updated message.

* Does VSCode store it's commit message anywhere that I can access?

**Comment by lszomoru** [comment] 2024-07-31 09:04
@LiveFreeAndRoam, sorry about that. By arrowing up one too many times I suspect that you mean that you have pressed the up arrow twice: 1) the cursor moves to the beginning of the commit input field, 2) the input gets cleared. 

Here is what I tried in order to get the original contents of the input back:
1) Press `Ctrl+Z` (undo) as that will restore the original contents of the input
2) Press up arrow, press down arrow twice as this will also restore the original contents of the input 

Could you give this a try and let me know if these work for you? Thanks!

**Comment by lszomoru** [comment] 2024-12-20 15:35
Closing as duplicate of [#229970](https://github.com/microsoft/vscode/issues/229970)

**Closed by lszomoru** 2024-12-20 15:35 UTC
Labels: bug, scm
