### ISSUE TITLE
CTRL + C not higlighting anything will copy a blank line instead of keeping item in clipboard

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#13540] opened 2016-10-11 20:14 UTC
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: alefragnani.Bookmarks-0.9.2, alefragnani.numbered-bookmarks-0.5.0, azemoh.one-monokai-0.1.14, be5invis.vscode-icontheme-nomo-dark-1.1.4, hirofumii.rubyblue-theme-1.0.2, PasqNet.theme-earlytorise-0.0.4, qinjia.seti-icons-0.1.1

Steps to Reproduce:

1.CTRL + C, not higlighting anything, will copy a blank line instead of keeping current text in clipboard

**Comment by Bill-Stewart** [comment] 2016-10-11 20:20
Can't reproduce. Do you have the cursor on a blank line? If so, this behavior is expected.

**Comment by soljohnston777** [comment] 2016-10-11 20:36
Yes.  the cursor is on a blank line.  Is there a way to turn that off then?  Otherwise, can you make an option to turn that off?

**Comment by Bill-Stewart** [comment] 2016-10-11 20:49
This has already been requested. See https://github.com/Microsoft/vscode/issues/11112 - the request is to add an option to disable <kbd>ctrl</kbd>+<kbd>c</kbd> behavior of "copy current line to clipboard if there is no selection".

**Comment by isidorn** [comment] 2016-10-11 20:56
Closing as dupcliate

**Closed by isidorn** 2016-10-11 20:56 UTC
