### ISSUE TITLE
File nesting patterns are case-incorrect

### ISSUE THREAD

**Issue by uecasm** [microsoft/vscode#144812] opened 2022-03-10 06:28 UTC
Issue Type: <b>Bug</b>

With the experimental file nesting enabled, the following pattern:

`"*.resx": "$(capture).*.resx, $(capture).designer.cs"`

Will successfully nest a file `Resources.Designer.cs` inside `Resources.resx` as expected.

However, writing the pattern with `Designer` instead of `designer` causes it to match nothing, even though the actual filename does include a capital.

It should either be doing proper case-insensitive matching or proper case-sensitive matching, but it seems to instead be doing a force-lowercase on filenames and then case-sensitive matching on patterns, which is the worst of both worlds.

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by JacksonKearl** [comment] 2022-03-18 02:38
Duplicate of #142390

**Closed** 2022-03-18 02:38 UTC
Labels: bug, file-explorer
