### ISSUE TITLE
substring of prefix can't trigger snippet

### ISSUE THREAD

**Issue by yangshuairocks** [Microsoft/vscode#60737] opened 2018-10-12 06:19 UTC
- VSCode Version:
Version: 1.29.0-insider
Commit: cc5e2b41c3add18a31e87f84b5d6162566a38d6e
Date: 2018-10-10T05:19:52.883Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version:
Windows 10 Version 1803 (OS Build 17134.228)

Steps to Reproduce:

1. Create a snippet with the following content

```
{
    "My templates for Rsharper": {
        "scope": "csharp",
        "prefix": "mytemplate",
        "body": [
            "test"
        ],
        "description": "My templates for Rsharper"
    }
}

```
2. Open a new tab and set it as csharp mode. 
3. In the new tab, type `template`, the snippet created above will not be triggered. 

In previous version, substring (`template` here) of the prefix (`mytemplate`) can also trigger a snippet. I suspect this is a configuration issue, however I searched around the configuration and couldn't find one. Please confirm if this is a bug or not. Thanks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2018-10-15 09:04
Actually not sure that this is a bug. The `template` prefix is just weak match for `mytemplate` and we have never shown those. Tho, it would be different if it was `myTemplate` (upper-case `T`) and this or something slightly different might have been caused by the fix for #60247

**Comment by jrieken** [comment] 2018-10-15 13:03
> Will the nightly build include this fix?

Yeah, we will be in next (tomorrows) insiders build

>  I'm pretty sure for a prefix "mytemplate", you can use template, empla, plate, etc. to trigger it in the past version.

Pretty sure not

**Comment by yangshuairocks** [comment] 2018-10-18 04:32
I tried on an old version and it behaves just as you described. I may have remembered it wrong.

**Closed** 2018-10-18 04:33 UTC
Labels: needs more info, snippets

**Comment by yangshuairocks** [comment] 2018-11-20 18:35
Hi @jrieken, I suddenly found any substring of prefix can trigger the snippet today. Is there any settings to control this behavior? See below image. 
![image](https://user-images.githubusercontent.com/39968/48794690-aad5fb80-ed35-11e8-989f-e0934683a414.png)

BTW, below is my VSCode version info:

> Version: 1.30.0-insider
> Commit: 24b0f75b1e33b88f30f2ed9d5b17ca60062c270b
> Date: 2018-11-16T06:20:02.054Z
> Electron: 2.0.12
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64
