### ISSUE TITLE
custom titlebar when clicking on menus it needs a scrollbar

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#55763] opened 2018-08-03 14:36 UTC
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Steps to Reproduce:

1. enable     "window.titleBarStyle": "custom" and restart
2. resize the editor to be smaller than the full size of the menu.
3. click on for example view menu button.

expected behavior: me being able to scroll to access all menu options

actual behavior: the menu is clipped.

This happens on all platforms. I like the custom menu more the editor feels lighter and I have just a bit more vertical coding space.

**Comment by sbatten** [comment] 2018-08-08 02:07
duplicate of #55739

**Closed by sbatten** 2018-08-08 02:07 UTC
