### ISSUE TITLE
high CPU spike due to rg.exe after installing latest vscode update

### ISSUE THREAD

**Issue by HumaRamawat** [microsoft/vscode#88314] opened 2020-01-08 23:08 UTC
![image](https://user-images.githubusercontent.com/710291/72023798-9817d200-3228-11ea-9b3c-a5e5fdf63292.png)

![image](https://user-images.githubusercontent.com/710291/72023817-a8c84800-3228-11ea-9596-541e6077c929.png)

**Comment by connor4312** [comment] 2020-01-08 23:27
Can you provide reproduction steps or information about what you were doing at the time?

/needsMoreInfo

**Comment by HumaRamawat** [comment] 2020-01-09 12:02
I was using VS code for coding and searching. But even without doing
anything CPU stays at 100 Percent.

**Comment by JacksonKearl** [comment] 2020-01-09 16:29
@HumaRamawat does this happen every time you search or only intermittently?

@roblourens Possibly related the the other RG freeze/slow/crash's popping up?

**Comment by roblourens** [comment] 2020-01-13 05:22
Not necessarily @JacksonKearl. 

@HumaRamawat please check out the tips here to see whether anything is relevant https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by reyemtm** [comment] 2020-03-02 13:55
also experiencing this issue, with rg.exe continuing to run even after quitting vs code, pegging the CPU at 100%. Yes one of my workspaces is large...what else version 1.42.1. The issue has been present for several months.

**Comment by Twist-Fate** [comment] 2020-03-04 16:49
Found this thread.... and high CPU issue happens each time I open my VS code... and what I can do is to kill it manually...

![image](https://user-images.githubusercontent.com/11195198/75902558-0b872b80-5df5-11ea-9725-59a768e43469.png)

**Comment by roblourens** [comment] 2020-03-04 18:04
Closing this due to now response from the OP. Others, please open your own issue. If this happens at startup, it is due to an extension triggering a search. Please run "Set Log Level", pick "Trace", see the "Log (Window)" output channel for info which should help us figure out why the search is being started, and include that info in a new issue.

**Closed by roblourens** 2020-03-04 18:04 UTC
Labels: search
