### ISSUE TITLE
Toggle Menu Bar on macOS does not work

### ISSUE THREAD

**Issue by nemanjacosovic** [Microsoft/vscode#64152] opened 2018-12-02 16:26 UTC
- VSCode Version: 1.29.1 (1.29.1)
- OS Version: macOS 10.14.1 (18B75)

Steps to Reproduce:

1. Open VSCode
2. Click on **View**
3. Hover over **Apperance**
4. Click on **Toggle Menu Bar**

Error pops up.

Does this issue occur when all extensions are disabled?: Yes

<img width="542" alt="screen shot 2018-12-02 at 5 24 57 pm" src="https://user-images.githubusercontent.com/23336275/49342131-5432c080-f657-11e8-9618-356830c27de3.png">
<img width="396" alt="screen shot 2018-12-02 at 5 23 28 pm" src="https://user-images.githubusercontent.com/23336275/49342132-54cb5700-f657-11e8-879b-9955220726e7.png">
<img width="655" alt="screen shot 2018-12-02 at 5 23 09 pm" src="https://user-images.githubusercontent.com/23336275/49342133-54cb5700-f657-11e8-90ba-7b385429085f.png">

**Comment by sbatten** [comment] 2018-12-03 18:17
This is a duplicate of a separate issue that is resolved in insiders.  Will be fixed in next release.

**Closed** 2018-12-03 18:17 UTC
