### ISSUE TITLE
PS syntax highlighting broken on regex string

### ISSUE THREAD

**Issue by jiria** [Microsoft/vscode#10323] opened 2016-08-09 03:02 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. [ValidatePattern('^([\da-f]{2}-){5}[\da-f]{2}$')]
2. The rest of the file has improper highlighting

![image](https://cloud.githubusercontent.com/assets/18746096/17503218/e1343dc4-5da2-11e6-888d-c32bbcc8a9ad.png)

**Comment by daviwil** [comment] 2016-08-09 17:54
Hey @jiria, what happens if you use double-quotes there instead?

**Comment by jiria** [comment] 2016-08-09 18:28
Only slightly better, Foo and Bar get blue, but the rest stays brown.

**Comment by MattAllison** [comment] 2017-05-15 22:30
Any update on this?  I've started just throwing away ValidatePattern blocks in my code (which is the WRONG thing to do).  Parenthesis seems to be a key problem but not the only problem.

Patterns that don't work include:

[validatePattern("^((?!^.{24})([a-z]{2}a[0-9]+s[0-9]+[a-z]{4}sa[0-9]+))$")]
[ValidatePattern("^[a-zA-Z0-9 .,`"`'!;#$\(\)+-=@\[\]^_\{\}|~]{0,127}[\[\]^_\{\}|~=@a-zA-Z0-9,`"`'!;#$\(\)+-]$")]

**Comment by daviwil** [comment] 2017-05-15 22:34
Sorry for the delay on this. @gravejester, any chance you could take a look at the old syntax definition to see why the ValidatePattern regex causes highlighting to break for the whole file?  You can find the old one here:

https://github.com/Microsoft/vscode/blob/master/extensions/powershell/syntaxes/PowershellSyntax.tmLanguage

**Comment by gravejester** [comment] 2017-05-16 03:18
Sure.. will look into it.

**Comment by gravejester** [comment] 2017-05-16 03:56
After just a quick glance, I'm pretty sure this is a bug that is fixed in the new syntax rules in development.

Complex expressions like Regular Expressions should ideally be expressed as a single-quoted string, since this scope only includes escaping rules and nothing else. The problem in this instance is that when used [something('**here**')] it's not being scoped as a single-quoted string. On top of that the first ')' exits the current scope that began with the first '(' which takes us all the way out to the *source.powershell* scope. That's why the last single quote is being interpreted as the start quote and the rest of the document (until it finds another single quote) is being scoped as belonging to a single-quoted string.

@daviwil Do you want me to see if I can fix this particular bug in the old syntax rules so we can get a fix for this out?

**Comment by daviwil** [comment] 2017-05-16 13:22
If it's easy, then maybe give it a shot!  Otherwise it might be worthwhile to see if we can fix the remaining big issues with the new grammar so we can ship it again in the next VS Code release.

**Comment by MattAllison** [comment] 2017-05-16 17:49
I can provide some additional test patterns if that would help.  My developer skills are ancient but I'm willing to do what I can to assist.

        [ValidatePattern("(^[a-zA-Z0-9-]{1,15}$)")]                        
        [ValidatePattern("(^[a-zA-Z][a-zA-Z0-9(-?)]{1,61}[a-zA-Z0-9]$)")]

**Comment by aeschli** [comment] 2018-02-09 10:16
duplicate of https://github.com/Microsoft/vscode/issues/36991.

**Closed by aeschli** 2018-02-09 10:16 UTC
