### ISSUE TITLE
scss linter does not support mixin keyword arguments

### ISSUE THREAD

**Issue by acdha** [Microsoft/vscode#17554] opened 2016-12-19 20:13 UTC
- VSCode Version: 1.8.0
- OS Version: macOS 10.12.2

The built-in SCSS linter will report an error (“) expected”) for SCSS files which use mixins with a keyword argument map:

```scss
.title-row {
    @include flexbox((display: flex, justify-content: space-between, align-items: center));
}
```

Tools like stylelint, Compass, etc. accept this syntax which appears to be legal as described in http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_arguments

**Comment by egamma** [comment] 2016-12-20 10:27
@acdha as a workaround you can disable the built-in validation with the setting `scss.validate`.

**Comment by acdha** [comment] 2016-12-20 14:53
@egamma thanks – I'd done that earlier but some of the other messages are useful.

**Comment by aeschli** [comment] 2016-12-31 02:29
duplicate of #1758

**Closed by aeschli** 2016-12-31 02:29 UTC
Labels: css-less-sass
