### ISSUE TITLE
Make connection token in the server optional

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode#136615] opened 2021-11-07 11:47 UTC
First of all, I would love to say that the new server component in VS Code is awesome, I believe it has enormous potential, I'm excited to see what's coming. 

The connection tokens in the server provide a simple authentication option, but some users want to have some sort of their own auth, better integrated in their existing infrastructure. Hence, I suggest making it possible to disable this option entirely, I don't think it should be disabled by default, making it secure out of the box is great, but some kind of flag to turn this functionality off would be helpful.

**Comment by kifayat26** [comment] 2021-12-13 18:07
Hello everyone. Can anyone please tell me, when the feature will be released? It is very important for my project.

**Comment by ndgayan** [comment] 2021-12-15 23:15
Correct. I'm also waiting for this functionality.

**Comment by routerino** [comment] 2021-12-19 09:50
I'll also chime in. I protect my Vscode environment behind https, an oauth proxy and single sign on server. Having the token authentication on top of that is unnecessary and causes headaches when it comes to automating dev environment provisioning.

**Comment by Pmoshbr** [comment] 2021-12-29 12:07
Waiting for this functionality be optional. No reason to use this in my implementation.

**Comment by aeschli** [comment] 2022-01-11 12:17
`--without-connection-token` added by  https://github.com/microsoft/vscode/commit/2387375634512422255f1c5c2cbde2a886713188
Leaving it to @alexdima to fully implement it

**Comment by ndgayan** [comment] 2022-01-18 16:22
Still, we need to supply "without-connection-token" as a "tkn" query argument in the url. 
E.g., http://<VSCodeIP>:<Port>/**?tkn=without-connection-token**

This can be misleading. Could you completely remove the "tkn" query argument? Then we can directly log into the server by typing "http://<VSCodeIP>:<Port>"

**Comment by aeschli** [comment] 2022-01-19 21:42
@ndgayan As mentioned, the issue is not yet fully fixed. When it is, `?tkn=without-connection-token` will be gone

**Closed** 2022-01-21 15:35 UTC
Labels: feature-request, server

**Comment by alexdima** [comment] 2022-01-25 14:21
To verify, you can launch the server from source using `./scripts/code-server.sh --without-connection-token` and you can try opening a browser at `http://localhost:9888` and seeing that it works.
