### ISSUE TITLE
Tensor flow message in developer tools

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129539] opened 2021-07-27 13:32 UTC
Refs: https://github.com/microsoft/vscode/issues/129436

Open developer tools, notice the message

```
============================
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================ 
```

Maybe we listen to their advice and do this strategy for VS Code app (not web).
Anyways we should try to disable this message so it does not spam every user that opens the developer tools.

Especially since this seems to happen even to users that do not set `experimentalLanguageDetection` to true.

**Comment by TylerLeonhardt** [comment] 2021-07-27 14:16
I was using the CPU backend because it was recommended here to be the fastest:
https://github.com/tensorflow/tfjs/issues/4838#issuecomment-850730654

> Especially since this seems to happen even to users that do not set experimentalLanguageDetection to true.

It might have happened when you clicked the language picker. The model gets loaded lazily and the only things that load the model are:
* detecting a change in an untitled file
* when you click the language picker while it says Auto

The first bullet is controlled by the setting, the second bullet I felt like wasn't disruptive so it's not controlled by the setting.

> Open developer tools, notice the message

This is a dupe of https://github.com/microsoft/vscode/issues/129005#issuecomment-885714321

**Closed by TylerLeonhardt** 2021-07-27 14:16 UTC

**Comment by isidorn** [comment] 2021-07-27 16:39
Hmm I did not really change language modes, I was testing something completelly unrelated.

Repro steps:
1. Latest vscode insiders, have no files open, reload
2. Open `debugService.ts` via quick pick
3. Notice warning in the developer tools

So it seems like you are loading the tensor flow library too aggressively. Can you double check please?

**Comment by TylerLeonhardt** [comment] 2021-07-27 17:09
Talked offline with @isidorn. He had my old extension still installed which caused that issue ^ I will unlist the extension so no one gets confused.
