### ISSUE TITLE
unable to launch to integratedTerminal

### ISSUE THREAD

**Issue by jdthoen** [microsoft/vscode#73880] opened 2019-05-17 10:50 UTC
Issue Type: <b>Bug</b>

After the latest update when we run a debug session that launches to the integrated terminal we get an error saying "Cannot launch debug target in terminal (Cannot read property 'trim' of null).

The launch does work with internalConsole and externalTerminal.

Here is out launch setting:
{
            "type": "node",
            "request": "launch",
            "name": "Mocha Current File",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "--timeout",
                "999999",
                "--colors",
                "${file}"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }

VS Code version: Code - Insiders 1.35.0-insider (a69d0f8b218498e22b7c3a0f76926cc6322e6106, 2019-05-17T05:18:13.839Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
copy-relative-path|ale|0.0.2
vscode-tidyhtml|anw|1.10.0
vscode-django|bat|0.19.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.0
gitlens|eam|9.7.4
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
macros|ged|1.2.1
vue-snippets|hol|0.1.11
require-js|lic|0.1.26
vscode-mocha-sidebar|mat|0.20.24
vscode-attrs-sorter|mrm|2.1.0
mssql|ms-|1.6.0
python|ms-|2019.4.12954
debugger-for-chrome|msj|4.11.3
vuejs-extension-pack|mub|1.1.3
node-modules-resolve|nau|1.0.2
vetur|oct|0.21.0
vscode-docker|Pet|0.6.2
sass-indented|rob|1.5.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.6.0
jenkinsfile-support|sec|0.1.0
vuejspack|she|1.3.2
sonarlint-vscode|Son|1.6.0
language-stylus|sys|1.11.0
vscode-status-bar-format-toggle|tom|1.5.0
vscodeintellicode|Vis|1.1.6
vscode-icons|vsc|8.6.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
vscode-import-cost|wix|2.12.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2
plsql-language|xyz|1.8.2
batch-format|zha|0.3.3

(2 theme extensions excluded)

</details>

**Comment by weinand** [comment] 2019-05-21 13:55
/duplicate of #73867

fixed in latest Insiders

**Closed** 2019-05-21 13:55 UTC
Labels: debug
