### ISSUE TITLE
html5 previewer plugin should not be able to take down renderer

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97788] opened 2020-05-14 07:49 UTC
Extracted from https://github.com/microsoft/vscode/issues/97768

There seems to be a way to crash the renderer from a bad behaving extension. I think we should investigate this and find ways to avoid that if possible. 

My understanding is that this is coming from a `webview`. 

//cc @alexdima @deepak1556

**Comment by mjbvz** [comment] 2020-05-14 19:18
I suspect the problem is that we catch exceptions that are thrown in the webview and pass them back to the main VS Code renderer so that we can log them. We pass the exception back over ipc. If an exception is happening in a tight loop, electron's ipc may get bogged down. 

The fix would likely be to cap the rate at which we allow exceptions to be logged (and log a message to say that not all exceptions will show in the console at this point)

**Comment by zacwalker93** [comment] 2020-11-10 01:55
I am interested in working on this issue if it is still available, Thanks!

**Comment by mjbvz** [comment] 2020-11-14 05:20
Yes it is. The relevant code on the VS Code side this this handler: https://github.com/microsoft/vscode/blob/ffb8c08dd9e6cf41cc64e0f24b535857c55f13a5/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L89

Although this could also be an electron problem that we may not be able to work around

**Comment by zacwalker93** [comment] 2020-12-11 23:04
Upon further inspection, I was able to reproduce the bug with a console.log() within a tight loop - without throwing any exceptions. Using an async function to make 1 second delays  between each console.log() call within the loop still crashes the program after around 260 console.log() calls as well. I was wondering if there is any other guidance you could give based off this?
Thank you!

**Comment by mjbvz** [comment] 2020-12-13 21:06
Does this happen in a basic electron webview  too? Try using electron fiddle to test this out: https://www.electronjs.org/fiddle

**Comment by zacwalker93** [comment] 2020-12-13 22:23
No, this program does not seem to crash by throwing new exceptions or logging too many times.

**Comment by mjbvz** [comment] 2020-12-14 23:44
Can you share the fiddle you used to test this?

**Comment by zacwalker93** [comment] 2020-12-16 03:40
[Bad_Loop_Fiddle.zip](https://github.com/microsoft/vscode/files/5700149/Bad_Loop_Fiddle.zip)
Sure, here it is.

**Comment by mjbvz** [comment] 2020-12-16 06:30
Thanks. Try seeing what is different between your example and VS Code. This should help you track down where the problem may lie.

For example, in VS Code we use the `console-message` handler: https://github.com/microsoft/vscode/blob/ffb8c08dd9e6cf41cc64e0f24b535857c55f13a5/src%2Fvs%2Fworkbench%2Fcontrib%2Fwebview%2Felectron-browser%2FwebviewElement.ts#L89

Try seeing if that causes problem in a normal electron webview too

**Comment by mjbvz** [comment] 2021-10-04 23:19
Closing this since it no longer applies now that VS Code's webview use iframes. If errors or console.logs are still causing issues, then it would be a problem for the Chrome dev tools instead now

**Closed by mjbvz** 2021-10-04 23:19 UTC
Labels: bug, help wanted, freeze-slow-crash-leak, good first issue, webview
