### ISSUE TITLE
Give option in settings to disable output window automatically popup

### ISSUE THREAD

**Issue by thesunfei** [Microsoft/vscode#45960] opened 2018-03-16 09:02 UTC
- VSCode Version: 1.21.1
- OS Version: window 10

Steps to Reproduce:

1.Type "}" in html JS block.
2.Output window with errors will automatically popup.

 Video link:
https://www.youtube.com/watch?v=BkW49oxEUFY

Suggestion:
FIx this bug and give option in settings to disable output window  automatically popup.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tsalinger** [comment] 2018-03-16 16:05
This is a duplicate of #45863.
Please see @aeschli's answer here: https://github.com/Microsoft/vscode/issues/45863#issuecomment-373650148

**Closed by tsalinger** 2018-03-16 16:05 UTC
Labels: new release
