### ISSUE TITLE
explorer decorations: improve colors

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#36413] opened 2017-10-17 12:05 UTC
The explorer decoration badges are too bright and barely readable:

Default dark:
![image](https://user-images.githubusercontent.com/6461412/31664033-2b949f4c-b344-11e7-95a1-b9fe735a75a9.png)

Monokai:
![image](https://user-images.githubusercontent.com/6461412/31664160-af0ff2cc-b344-11e7-90e6-c93ed52d0519.png)

**Comment by jrieken** [comment] 2017-10-17 13:14
dupe of #36246

**Closed by jrieken** 2017-10-17 13:14 UTC
Labels: workbench
