### ISSUE TITLE
Variable Font Size for Headings/Syntax

### ISSUE THREAD

**Issue by kellpossible** [Microsoft/vscode#72380] opened 2019-04-16 01:09 UTC
Emacs has the ability to specify different sized font for certain sections of the syntax. This is evident with their markdown-mode which uses this feature to emphasise different heading levels, it also makes the plain text version of markdown a lot more readable, and presentable.

This is how I have it set up in Emacs:

![image](https://user-images.githubusercontent.com/4527338/56174820-bfde5e80-6037-11e9-91fb-311a28191d51.png)

This is my attempt in VSCode (font sizes cannot be specified yet):

![image](https://user-images.githubusercontent.com/4527338/56174828-cd93e400-6037-11e9-9371-00ff90aceb8e.png)

VSCode settings for heading colours matching Emacs Org Mode:

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "markup.heading.markdown punctuation.definition.heading.markdown",
            "settings": {
                "foreground": "#8a8888",
            }
        },
        {
            "scope": "heading.1.markdown entity.name.section",
            "settings": {
                "foreground": "#ff7f24",
            }
        },
        {
            "scope": "heading.2.markdown entity.name.section",
            "settings": {
                "foreground": "#a6e22e",
            }
        },
        {
            "scope": "heading.3.markdown entity.name.section",
            "settings": {
                "foreground": "#66d9ef",
            }
        },
        {
            "scope": "heading.4.markdown entity.name.section",
            "settings": {
                "foreground": "#e6db74",
            }
        },
        {
            "scope": "heading.5.markdown entity.name.section",
            "settings": {
                "foreground": "#a1efe4",
            }
        },
        {
            "scope": "heading.6.markdown entity.name.section",
            "settings": {
                "foreground": "#fccf3e",
            }
        },
    ]
},
```

It would be great to be able to specify the font size in there too.

Existing issue for this feature was closed, but the font size part was probably forgotten and not implemented: https://github.com/Microsoft/vscode/issues/47113

**Comment by mjbvz** [comment] 2019-04-17 18:06
Duplicate of #69884

**Closed by mjbvz** 2019-04-17 18:06 UTC
Labels: markdown
