### ISSUE TITLE
Unable to rename file

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#69527] opened 2019-02-27 11:59 UTC
Issue Type: <b>Bug</b>

I have disabled all extensions, but I can't rename the files. The same happens as in the GIF below.

![error](https://user-images.githubusercontent.com/13393959/53488680-faad2700-3ac9-11e9-93e5-671bf023d94c.gif)

At the same time, when I reload the window, sometimes I can rename the file, and sometimes I can't complete the corresponding operation.

VS Code version: Code - Insiders 1.32.0-insider (ce073b0076ac2f69faf2c609af72f9b81506c791, 2019-02-27T06:17:47.743Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by usernamehw** [comment] 2019-02-28 00:45
duplicate of #69468 ?

**Comment by czfadmin** [comment] 2019-02-28 05:28
@usernamehw 
Yes, but this problem has not appeared again in the latest version.

**Comment by Tyriar** [comment] 2019-03-01 00:02
Duplicate https://github.com/Microsoft/vscode/issues/69468

**Closed by Tyriar** 2019-03-01 00:02 UTC
Labels: integrated-terminal
