### ISSUE TITLE
Repository selector in status bar - Versioncontrol

### ISSUE THREAD

**Issue by PauloGDPeixoto** [microsoft/vscode#91742] opened 2020-02-28 09:54 UTC
I work with a multi-root workspace and recently installed the GitHub Pull Requests extension, which can be cumbersome in this environment.
In order to open a pull request, I have to go to the Source Control pane, make sure that the correct repository is selected, and then go back to the GitHub Pull Requests pane to start opening the pull request.
This would be much easier and intuitive if, along with the branch selector in the status bar, there was a repository selector.

**Comment by IllusionMH** [comment] 2020-02-28 11:38
Actually it looks like duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1090

As for status panel - it shows branch for current active file (and basically file < folder < repo combination).
It's still possible to switch to another branch for current file/repo combination, you can't change repo for current file.
So it's not clear (intuitive) what repo change should do there, on the other hand - improvement to extension PR process (linked above) will solve your actual problem.

**Comment by PauloGDPeixoto** [comment] 2020-02-28 12:10
I understand and I can see how troublesome the selector could be.
But in that case, a visual indication of the repository in the status bar, next to the branch name, would be a nice indicator to keep track of where you're working.
Perhaps this is a bit of an edge case, but I have 5 organizations totalling 30+ repositories in my workspace, it can get a bit confusing at times.

**Comment by gjsjohnmurray** [comment] 2020-02-28 13:48
@PauloGDPeixoto does the hover tip on that indicator tell you what you need to know?

**Comment by PauloGDPeixoto** [comment] 2020-02-28 14:30
It does, but it would be nice to have the option to place it permanently in the status bar.

**Comment by gjsjohnmurray** [comment] 2020-02-28 14:32
cc @joaomoreno

**Comment by joaomoreno** [comment] 2020-04-03 12:02
Maybe a `git.showRepositoryInStatusBar` setting, `false` by default.

**Comment by xinyeah** [comment] 2020-10-01 17:18
I'm going to take a shot at this for Grace Hopper's Open Source Day!

**Comment by luucamay** [comment] 2020-10-01 21:32
Hello @joaomoreno, I want to try solving this problem. I am from Grace Hopper OSD

**Comment by luucamay** [comment] 2020-10-01 21:44
Hi @joaomoreno, the solution proposed by @ChrisPapp is not valid or why that one is not considered?

**Closed** 2020-11-06 09:57 UTC
Labels: *out-of-scope, feature-request, git, good first issue, help wanted
