### ISSUE TITLE
Feature: Filter by completion kind in intellisense

### ISSUE THREAD

**Issue by uxsoft** [Microsoft/vscode#23903] opened 2017-04-04 21:12 UTC
Visual Studio 2017 has a panel down at the bottom of the completion popup where user can select of which type only to show items. This helps when we know we're looking for a property.

These tabs are also controllable by keyboard shortcuts.

![completion kind filter](https://cloud.githubusercontent.com/assets/1889343/24678685/d8dea204-198b-11e7-9127-373a987425a6.PNG)

It would be nice to have this in vs code as well :-)

**Comment by jrieken** [comment] 2017-04-11 08:08
dupe of https://github.com/Microsoft/vscode/issues/18639

**Closed by jrieken** 2017-04-11 08:08 UTC
Labels: feature-request, suggest
