### ISSUE TITLE
Proxy dialog is getting closed before I could enter credentials

### ISSUE THREAD

**Issue by govindakatkamwar** [microsoft/vscode#106843] opened 2020-09-16 09:00 UTC
Issue Type: <b>Bug</b>

The proxy dialog is getting closed before I could enter credentials

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.85GB free)|
|Process Argv|--crash-reporter-id f8b60d1b-b3ef-42e1-8419-11e99c9d3ca5|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|11.3.1
ng-template|Ang|0.1001.0
githistory|don|0.6.9
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.6.0
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
rest-client|hum|0.24.2
csharpextensions|jch|1.3.1
docomment|k--|0.1.18
dotnet-core-essentials|Kis|0.0.8
csharpfixformat|Leo|0.0.84
azure-pipelines|ms-|1.174.2
vscode-azureappservice|ms-|0.18.0
vscode-azurefunctions|ms-|0.24.0
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.2.0
vscode-cosmosdb|ms-|0.14.0
vscode-docker|ms-|1.5.0
csharp|ms-|1.23.2
vscode-dotnet-runtime|ms-|0.1.2
mssql|ms-|1.9.0
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
notepadplusplus-keybindings|ms-|1.0.5
vscode-node-azure-pack|ms-|0.0.11
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.12.0
debugger-for-chrome|msj|4.12.10
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|1.17.0
wallaby-vscode|Wal|1.0.237

</details>

**Comment by gjsjohnmurray** [comment] 2020-09-16 14:03
/duplicate of #106434 and will be fixed in upcoming recovery release.

**Closed** 2020-09-16 14:04 UTC
Labels: *duplicate
