### ISSUE TITLE
Unable to load Tensorboard in Notebook 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#107992] opened 2020-10-02 19:31 UTC
- Version: 1.50.0-insider
- OS: Darwin x64 19.6.0

**Steps to Reproduce:**

1. Run a Python notebook (using the new VS Code Notebook API) with the following cells:
    * Cell 1
`%load_ext tensorboard`
    * Cell 2
```python
import tensorflow as tf
import datetime

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(x=x_train, 
          y=y_train, 
          epochs=1, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback])
```

    * Cell 3
`%tensorboard --logdir logs/fit`

2. At this point the last cell should have some empty output
This is because the output attempts to display an iframe relative to the current home page.
url = `/:6060`, this doesn't work due to the custom resource schemes.

3. Verify the page `http://localhost:6006` is accessible in a browser.

3. Add another cell with the following code:
```
from IPython.display import IFrame
IFrame('http://localhost:6006', width=700, height=350)
```
At this point it should display this iframe.
But it doesn't.

Here's the output from VS Code when attempting to load the above page in the iframe:

`
webviewElement.ts:150 [Embedded Page] Refused to frame 'http://localhost:6006/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors *".
`

**Note: Another way to easily test this**
* Run the python code outside VS Code (you don't need Python extension)
* Create & open a simple notebook in VS Code, with HTML output in a cell:
```
<iframe
            width="700"
            height="350"
            src="http://localhost:6006"
            frameborder="0"
            allowfullscreen
        ></iframe>
```

Does this issue occur when all extensions are disabled?: N/A

**Comment by rebornix** [comment] 2020-10-07 22:18
@mjbvz is this intentional that we disallow localhost in iframe?

**Comment by mjbvz** [comment] 2020-10-16 20:54
@DonJayamanne This is using the VS Code notebook APIs, correct? Does the python extension set any sort of content security polity in its content that could be blocking this?

**Comment by DonJayamanne** [comment] 2020-10-20 01:45
> This is using the VS Code notebook APIs and not custom editors or webview directly, correct

Yes (used in output using VSCode notebooks API)

> oes the python extension set any sort of content security polity in its content that could be blocking this?

This isn't a web server started by Python extension.
When running `%load_ext tensorboard`, tensor flow starts the local web server.

**Comment by mjbvz** [comment] 2020-10-27 01:07
@DonJayamanne After the cell `%tensorboard --logdir logs/fit`, I just see `Launching TensorBoard...` forever. Any suggestions or more minimal steps to reproduce?

Also, how do I confirm that I'm using the new notebook api for python vs the old one that's based on webviews?

**Comment by joyceerhl** [comment] 2020-10-27 01:43
@mjbvz the new notebook API is only available in Insiders and looks like this: 
![image](https://user-images.githubusercontent.com/30305945/97246582-ecda0880-17ba-11eb-8dc1-1adef3a6afb2.png) You can enable it by following these instructions: https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/#how-to-try-out-native-notebooks

**Comment by DonJayamanne** [comment] 2020-10-27 03:19
> forever. Any suggestions or more minimal steps to reproduce?

At this point it is failing because the output from the execution contains some javascript to create the IFrame. & the JS injects the src using `window.location` instaed of hardcoding it to `localhost`. This is to ensure they use the same host name where Jupyter UI is hosted.

We will need to put some hacky code in our extension to handle this situation.
For now you won't get the desired output.

Once you have got to this stage the tensorboard (web app) server is running.
You can view the output (view js/html rendered) & 99% of the time the port is the same.

You can now go into a separate cell & type the following code:
```python
from IPython.display import IFrame
IFrame('http://localhost:6006', width=700, height=350)
```

This will create the iframe with the right port.
FYi - You can confirm this address is accessible from your local browser.

> Also, how do I confirm that I'm using the new notebook api for python vs the old one that's based on webviews?

Once you have the extension activated (you will need to wait for extenion to get activated).
Right click on a notebook file & click on the `Open in Preview Notebook Editor` command

**Comment by rebornix** [comment] 2020-10-27 20:21
Interestingly I start a simple server locally at `127.0.0.1:6060` and then run 

```
from IPython.display import IFrame
IFrame('http://localhost:6060', width=700, height=350)
```

and the iframe is rendered properly

<img width="1848" alt="image" src="https://user-images.githubusercontent.com/876920/97357597-44c64d00-1857-11eb-84df-5c5ebbfddd5c.png">

**Comment by mjbvz** [comment] 2020-10-28 23:42
Thanks. I was able to run it and see that the iframe is using a `vscode-webview` uri:

![Screen Shot 2020-10-28 at 4 35 37 PM](https://user-images.githubusercontent.com/12821956/97508063-e757fc00-193b-11eb-8cff-067cbc668c49.png)

The `vscode-webview` protocol is only for VS Code's internal usage  this would definitely explain the problem. When I create an iframe using `IFrame('http://localhost:6060', width=700, height=350)`, it uses the expected `http` uri instead.

@DonJayamanne Could the python extension be either: hardcoding `vscode-webview` somewhere, or could either python or Tensorboard be picking this uri up from inside the webview (such as from `window.location`)? I quickly searched the public python repo but nothing stood out

**Comment by DonJayamanne** [comment] 2020-10-29 02:51
>  somewhere, or could either python or Tensorboard be picking this uri up from inside the webview (such as from window.location)?

Yes, I think I did mention this earlier. The js output from tensor board is using `window.location`. however changing that still  doesn't work. I thought it was some csp in VSCode webview that was preventing it from getting displayed.

Note, once you get that cell output, try the following in another cell.
```python
from IPython.display import IFrame
IFrame('http://localhost:6060', width=700, height=350)
```

and thanks

**Comment by mjbvz** [comment] 2020-10-29 21:41
I can't get tensorboard to launch the way you are describing. After following all those steps, nothing is running on localhost:6060. There are no errors that I see

I'm spending too much time just trying to setup the environment properly to reproduce this. @DonJayamanne Can you please first see if someone on the python team can investigate this more since they will know more about how tensor board is supposed to work. If they can't figure anything out, please put together a more minimal repo that demonstrates the problem or let's setup a brief call where we can debug this

**Comment by DonJayamanne** [comment] 2020-10-29 22:00
Thanks for your help, & i agree with your comments.

**Comment by joyceerhl** [comment] 2020-11-01 19:14
@mjbvz, tensorboard is launched by default on localhost:6006, not 6060—could that be the issue?

**Comment by mjbvz** [comment] 2020-11-02 21:34
Ah yes that was the issue!

I can repo this now but this looks like a tensorboard issue to me (or potentially a chromium bug).

Here's the warning I see:

```
Refused to frame 'http://localhost:6006/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors *".
```

The `frame-ancestors *` CSP rule does not come from VS Code or python but from the tensorboard website:

<img width="723" alt="Screen Shot 2020-11-02 at 1 26 10 PM" src="https://user-images.githubusercontent.com/12821956/97921245-82bbe900-1d0f-11eb-97be-2d308c080adc.png">

My (very basic) understanding is that `frame-ancestors *` should allow the page to be framed by anyone but maybe this does not apply for our webviews which use a custom`vscode-webview` scheme (and then another iframe inside of that)

Instead, if tensorboard omitted `frame-ancestors` entirely, I think it would allow the page to be embedded anywhere:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors 

I'm going to close this issue since I don't think it's something we can handle on the VS Code side.

@DonJayamanne Maybe the python team could follow up with Tensorboard about why `frame-ancestors *` is used? Someone could also review the CSP spec better to understand if there is a chromium bug here

**Closed by mjbvz** 2020-11-02 21:34 UTC
Labels: notebook, under-discussion, webview

**Comment by joyceerhl** [comment] 2020-11-03 04:05
The PR that introduces `frame-ancestors` is https://github.com/tensorflow/tensorboard/pull/2797. In the PR, `frame-ancestors *` is used precisely in order to 
> explicitly allow all hosts to iframe TensorBoard inside since we have a usecase like Jupyter notebooks


FWIW when I follow Don's steps above, I get a different error:
![image](https://user-images.githubusercontent.com/30305945/97948670-1c9e8880-1d46-11eb-836b-fba99b6abd18.png)

The `vscode-webview-resource` reference in that CSP is definitely not from tensorboard based on a search through their source code. Is this expected behavior?

**Comment by joyceerhl** [comment] 2020-11-06 21:30
@mjbvz TLDR while there might be a CSP bug here and while changing tensorboard would unblock us, I would appreciate your help with proving that the bug is in Chromium to help our case when requesting a change in tensorboard.

First, removing the `frame-ancestors *` line from my install of the tensorboard module allows me to frame tensorboard in webviews, native notebooks, and webview-based notebooks:

![image](https://user-images.githubusercontent.com/30305945/98414616-8feb1780-2030-11eb-8d40-6b41c9800563.png)

![image](https://user-images.githubusercontent.com/30305945/98414635-97122580-2030-11eb-8acf-a269ea3be063.png)

Second, the relevant part of the CSP spec is https://w3c.github.io/webappsec-csp/2/#directive-frame-ancestors. `frame-ancestors *` should be equivalent to not specifying the `frame-ancestors` directive at all:
> The term allowed frame ancestors refers to the result of parsing the frame-ancestors directive’s value as a source list. If a frame-ancestors directive is not explicitly included in the policy, then allowed frame ancestors is "*".

In addition, if I'm reading https://w3c.github.io/webappsec-csp/2/#match-source-expression correctly, the custom protocol that VSCode uses for its webviews should be immaterial, as the spec says that `*` should match URLs with custom schemes:

> If the source expression consists of a single U+002A ASTERISK character (*), and url’s scheme is not one of blob, data, filesystem, then return does match.

The fact that removing `frame-ancestors *` is all I needed to unblock this scenario suggests that there is a bug somewhere here. tensorboard added that directive to 
> explicitly allow all hosts to iframe TensorBoard inside since we have a usecase like Jupyter notebooks 

Although removing that directive should result in no behavior change for tensorboard, it would help our case to be able to point to a Chromium bug when upstreaming a change to tensorboard. 

Third, I can frame tensorboard without needing to modify the source in a simple Electron app using a single `<webview>` and a single `<iframe>`.

Iframe:
![image](https://user-images.githubusercontent.com/30305945/98415849-e0fc0b00-2032-11eb-8510-f310032d2bae.png)

Webview:
![image](https://user-images.githubusercontent.com/30305945/98415839-dc375700-2032-11eb-92d0-d1461886032f.png)

However, I was not able to frame tensorboard when following the nested iframe-within-webview structure that you provided in your [blog post on webviews](https://blog.mattbierner.com/vscode-webview-web-learnings/). The structure I tried based on your blog post, which doesn't work for framing unmodified tensorboard even in the absence of any CSPs being set, is:
```
 <webview>
    <html>
      <body>
        <iframe
             width="700"
             height="350"
             src="http://localhost:6006"
             frameborder="0"
             allowfullscreen
        ></iframe>
     </body>
   </html>
  </webview>
```

At this point I'm not sure if this indicates a bug in Chromium/Electron, or if the structure I'm trying above is off base WRT what VSCode's webview API implementation does, and haven't worked much with Electron's webviews, so would love your thoughts on what might be going on here. Thanks 😊

**Comment by joyceerhl** [comment] 2020-11-06 22:08
@mjbvz I can repro the `Refused to frame 'http://localhost:6006/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors *".` warning in a simple Electron app with a single `iframe`:

![image](https://user-images.githubusercontent.com/30305945/98418998-f8d68d80-2038-11eb-80b8-287b950fc2b9.png)

According to https://w3c.github.io/webappsec-csp/2/#match-source-expression, `frame-ancestors *` should match just about any URL:
> If the source expression consists of a single U+002A ASTERISK character (*), and url’s scheme is not one of blob, data, filesystem, then return does match.

Would you say this looks like a bug in Electron or Chromium?

**Comment by mjbvz** [comment] 2020-11-09 22:22
Thanks for the investigation!

Try testing in browsers too, such regular Chrome and Firefox. If it only happens in Chromium browsers, then [please file an issue against chromium](https://bugs.chromium.org/p/chromium/issues/list)

Unfortunately since this also happens in electron, this issue will likely take while to be fixed in VS Code itself. Since you can show that the problem happens outside of VS Code , maybe Tensorboard could look into a workaround on their side?

**Comment by joyceerhl** [comment] 2020-11-09 22:26
Sorry for not updating here: I filed an issue on Electron because I can repro the problem in a simple Electron app but not in Chromium-based browsers. https://github.com/electron/electron/issues/26369. Will also file an issue with TensorBoard to remove the CSP as a workaround. Thanks a million for all your help on this issue @mjbvz and @rebornix :)
