### ISSUE TITLE
Syntax highlight issue with comments

### ISSUE THREAD

**Issue by ashegoulding** [microsoft/vscode#110174] opened 2020-11-08 10:48 UTC
Issue Type: <b>Bug</b>

Comments in `/usr/include/linux/if_ether.h` are highlighted wrong. Obviously, the code compiles just fine, but Code thinks that they're malformatted.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.8.16-200.fc32.x86_64

**Comment by thunder-coding** [comment] 2020-11-09 05:06
Can you please share screenshot of the file

**Comment by ashegoulding** [comment] 2020-11-09 10:12
@thunder-coding You don't speak for the project, mate

**Comment by thunder-coding** [comment] 2020-11-09 10:15
I just wanted to help you :)

**Comment by ashegoulding** [comment] 2020-11-09 10:24
![Screenshot from 2020-11-09 20-52-22](https://user-images.githubusercontent.com/10917528/98529548-aa8dec80-22cd-11eb-8f05-8889d96d8bb6.png)

**Comment by thunder-coding** [comment] 2020-11-09 11:11
A real bug in VS Code.

Confirmed issues with C and C++ files.

This issue happens with only the `#define` preprocessor
![image](https://user-images.githubusercontent.com/68849076/98534127-05155180-22aa-11eb-891b-a650693f3a0f.png)


Does this happen when all the extensions are disabled: YES

**Comment by stevenhiner** [comment] 2020-11-18 15:42
I wonder if this is related to the behavior I see in groovy files. It seems similar in that it goes red related to `/` characters.

![image](https://user-images.githubusercontent.com/23109998/99549928-63f85c00-2977-11eb-94ff-9149bf048b3e.png)

In my case it doesn't happen in `c`, `cpp`, or `cs` files. 

Does this happen when all the extensions are disabled: YES

**Comment by stevenhiner** [comment] 2020-11-18 17:27
Also note that the incorrect line will highlight correctly if the comment is removed from the end of it. There appears to be an interaction between the / in code and the // after the closing brace.

**Comment by alexr00** [comment] 2020-12-30 15:44
@stevenhiner a different grammar is used for groovy, so I wouldn't expect the issue to be related.

**Comment by alexr00** [comment] 2020-12-30 15:51
Thanks for the small repro @thunder-coding! Looks like this is an issue in the grammar we use for C++. I created an issue in the upstream repository: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/527

**Closed by alexr00** 2020-12-30 15:51 UTC
