### ISSUE TITLE
Should I be able to "Hide Folders"?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173836] opened 2023-02-08 16:46 UTC
This action hides the icon, but not the contents:

![image](https://user-images.githubusercontent.com/900690/217595863-b5fc186e-bed9-4d18-91c6-67a56b4f3871.png)

**Comment by lramos15** [comment] 2023-02-08 21:29
@sbatten  / @sandy081 Any pointers here would be helpful. It appears that activity bar visibility is controlled by https://github.com/microsoft/vscode/blob/a987fee52eded44d24c2dc4784f7864d5852d06a/src/vs/workbench/services/views/browser/viewDescriptorService.ts#L789-L791 which respects the `canToggleVisibility` setting which a view sets on registration, but when in the secondary sidebar it just executes the composite bar action which doesn't have access to this property on the view. Is there a simple way to access the backing view descriptor of the composite item? What's the best approach to solving this as this effects any view which would say "hey I can't be hidden" and is moved to the secondary bar.

**Comment by sandy081** [comment] 2023-02-09 14:03
Thing is that we do not have capability to disable hiding view containers. It means, one can toggle explorer view container in the activity bar, but one cannot hide folders view because we have capability to disable hiding views. Hence, once you move just folders view to secondary side bar, we create a view container and place folders view in that. It is very similar to having only folders view in the explorer view container in the side bar. So one can always toggle the visibility of folders view container in the secondary side bar. 

> This action hides the icon, but not the contents:

I think it is because, this is the last visible view container and since there is no other view container to show after hiding this, this is shown. This is same behaviour also in other locations (sidebar) I suppose

**Comment by lramos15** [comment] 2023-02-09 14:24
Oh, I see. I think my confusion arose from the fact that the new view container has the same name as the view inside of it. I notice on the secondary sidebar with a view container with more than one view in it you still are unable to hide the views, but I guess that's more of a feature request since the context menu isn't even available there. Will close this as designed.

**Closed** 2023-02-09 14:24 UTC
Labels: *as-designed
