### ISSUE TITLE
Recently opened files includes deleted files

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#27104] opened 2017-05-22 23:40 UTC
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. In any project, open a file that exists (let's call it `foo.txt`).
2. Close VS Code.
3. Delete `foo.txt` from your file system.
4. Open VS Code.
5. Use quick open to search for the name of a file. A result will appear but if you try to open it, an error will happen `Unable to open 'foo.txt': File not found (/Users/.../foo.txt).`
6. Repeating step 5 multiple times the same thing happens.

I actually can't reproduce step (6) any more but I got into this state somehow. When I try to reproduce it seems to correctly eliminate the file after the first error.

Either way, it would be nice if VS Code removes files from the recently opened list that were deleted.

**Comment by chrmarti** [comment] 2017-05-26 16:43
Duplicate of #24318

**Closed** 2017-05-26 16:43 UTC
Labels: duplicate
