### ISSUE TITLE
Not able to change title of custom editor's webview panel(webViewPanel.title = 'NewName.extension')

### ISSUE THREAD

**Issue by sathya-1994** [microsoft/vscode#160543] opened 2022-09-09 17:49 UTC
I have contributed new custom editor and I am opening multiple custom editors of same type for a single document(single file)(based on cursor position).

I want to differentiate these custom editor as all editor/WebView panels will have same name as file name(example.cscratch).

I tried to update WebView panel's title variable at resolveCustomTextEditor method of CustomTextEditorProvider, but WebView panel name was not renamed in vscode UI.

I can see that tittle variable of WebView panel object updated but WebView panel's UI still contains file name as title.

If we create Webview panel using vscode.window.createWebviewPanel() API, then we can rename WebView panel just by updating title variable but same thing is not working for custom editor's WebView Panel.

Working for normal WebView panel:
this._panel.title = 'NewName.extension';
https://github.com/microsoft/vscode-extension-samples/blob/133fa26af64ba8760559c5a06299953673d60763/webview-sample/src/extension.ts#L165

Not working for custom editor's Webview panel:
Steps to reproduce:

Build https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample extension.
Also add below code in the resolveCustomTextEditor method of CatScratchEditorProvider.
code: webviewPanel.title ='exampleNew.cscratch'
https://github.com/microsoft/vscode-extension-samples/blob/133fa26af64ba8760559c5a06299953673d60763/custom-editor-sample/src/catScratchEditor.ts#L43
3.Run the extension
4.Open exampleFiles folder(https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample/exampleFiles)
5.Select example.cscratch file

**Expected output:** Custom editor of example.cscratch should contain title as 'exampleNew.cscratch' as we have update title of WebView panel in the resolveCustomTextEditor method.

**Actual output:** Custom editor of example.cscratch contain title as 'exampleNew.cscratch' even though we have update the title.

Any other way to update custom editor's WebView panel title?

**Comment by mjbvz** [comment] 2022-09-09 18:28
Duplicate of #105299

**Closed by mjbvz** 2022-09-09 18:28 UTC
