### ISSUE TITLE
Expose the state of the system on core crashes

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#2094] opened 2016-01-18 19:28 UTC
This is independent of the other issues, and is a UI feature request.

It seems like a lot of user confusion comes up because you aren't following good design practices, namely exposing the state of the system. If a process crashes and you still expose all features in the UI that link into that process, you're intentionally harming the user experience and the perceived credibility of the product. If I click on something and nothing happens, it's really bad. If I _can't_ click on it because it's grayed out with the error **The JavaScript engine has crashed**, it's still bad, but now I know what's going on, and I have more confidence in the software. Right now my mental model of vscode is...well...not great, because about half of the UI doesn't work and I don't know why. At least if I know it's from a process crash I can say "oh, it's not that 50% of this editor doesn't work, it's that one core process doesn't" which gives me more faith in the system as a whole.

**Comment by weinand** [comment] 2016-01-18 21:27
@DelvarWorld could you please be more specific as to what is not working for you. I'm asking for real examples and reproducible steps here. Thanks.

**Comment by DelvarWorld** [comment] 2016-01-18 22:08
Can't you just induce a crash manually? Either way take your pick: https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=author%3ADelvarWorld

**Comment by egamma** [comment] 2016-01-18 22:12
@weinand the current issue we are tracking down is #2054.

**Comment by egamma** [comment] 2016-01-18 22:15
@DelvarWorld we are moving from running language services in web workers into separate processes. I've checked and there we indicate the state when the server crashes to the user (also support to restart).

Given the move of the JS webworker into a server, we will no longer invest a lot into the webworker based language services.

**Comment by weinand** [comment] 2016-01-18 22:20
@egamma since you seem to oversee the individual issues behind this feature request, I'll assign it to you.

**Comment by egamma** [comment] 2017-10-21 15:28
More can be done on this issue, but I close this issue for now.

**Closed by egamma** 2017-10-21 15:28 UTC
Labels: feature-request
