### ISSUE TITLE
IDE crashing on response redirects

### ISSUE THREAD

**Issue by srealm** [Microsoft/vscode#26478] opened 2017-05-11 18:07 UTC
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Edit controller function
2. Type return redirect()->back();
3. As I am editing an existing controller and adding a response it crashes while typing the response redirect.

**Comment by egamma** [comment] 2017-05-12 06:50
In what language are you programming when this happens and what extension are you using?

**Comment by srealm** [comment] 2017-05-12 13:30
I am programming in PHP within the Laravel framework.

 

Extensions

Beautify

C#

Docker

Go

HTML Snippets

Mssql

Npm

Npm Intellisense

PHP Debug

PHP DocBlocker

PHP IntelliSense

PHP Intellisense-Crane

Vue

Vue 2 Snippets

 

Matthew Andrews, LEED AP | CEO | Web Developer | Photographer

Design Studio by Spherical Realm, LLC

O 312-402-1219 | C 312-493-9676

 <mailto:mra@srdesignstudio.com> mra@srdesignstudio.com |  <http://www.srdesignstudio.com/> www.srdesignstudio.com |  <http://www.twitter.com/!#/SRDesignStudio> @SRDesignStudio

Web Development | Graphic Design | Print/Media | Photography

**Comment by egamma** [comment] 2017-05-12 15:16
@srealm thanks for the additional information, but I cannot reproduce this issue given the above steps. We need detailed steps to reproduce the same setup as you have. Can you add an animated GIF that illustrates the crash?

**Comment by egamma** [comment] 2017-05-13 08:09
@srealm ping?

**Comment by egamma** [comment] 2017-05-14 06:42
@srealm closing for now, please reopen with more information.

**Closed by egamma** 2017-05-14 06:42 UTC
Labels: needs more info
