### ISSUE TITLE
Right-Click Context Menu No Longer Opens Files in Current Code.exe Window

### ISSUE THREAD

**Issue by rabel001** [Microsoft/vscode#7873] opened 2016-06-19 19:39 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Checked, deleted and recreated [HKEY_CLASSES_ROOT\*\shell\Open with VS Code\command]
@="\"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe\" \"%1\""
2. Reinstalled and checked all the options with regards to this issue.
3. Ran code.exe followed by a filename, and the file spawned a new Code.exe window.
![image](https://cloud.githubusercontent.com/assets/3143119/16179427/2b329898-362b-11e6-9846-d302541dcece.png)
![image](https://cloud.githubusercontent.com/assets/3143119/16179437/841596ae-362b-11e6-9ff9-25c73167fc0d.png)

**Comment by dbaeumer** [comment] 2016-06-20 18:53
@joaomoreno marking as important since this might be a regression.

**Comment by joaomoreno** [comment] 2016-07-06 10:31
@rabel001 

What is open in the original window?

There's also `window.openFilesInNewWindow` setting which you can use to control this. Does that solve it for you?

**Comment by rabel001** [comment] 2016-07-20 15:36
Thanks @joaomoreno and @dbaeumer.

It was set to true. I set it to false in my settings.json file, and now it opens in the current
Code.exe process exactly how I wanted it to.

I really appreciate the help.

**Comment by joaomoreno** [comment] 2016-07-21 06:31
No problem, thanks for the feedback!

**Closed by joaomoreno** 2016-07-21 06:31 UTC
Labels: needs more info
