### ISSUE TITLE
[new release] Git Graph Not Working After update to 1.52

### ISSUE THREAD

**Issue by artze** [microsoft/vscode#112430] opened 2020-12-14 05:50 UTC
The following was working as expected until the update to 1.52. 

System Info:
- VSCode Version: 1.52.0
- OS Version: Windows 10 Pro
- Running on WSL2. Project is in Linux environment and accessed using Remote extension.

Steps to Reproduce:
Opening Git Graph shows displays the following instead of the git graph:
![image](https://user-images.githubusercontent.com/13703523/102044429-c2e3b080-3e11-11eb-8ca9-05cc0b21b4a6.png)

For your info, the following is the output log for Git Graph, and did not seem to indicate any issues.
![image](https://user-images.githubusercontent.com/13703523/102044628-32f23680-3e12-11eb-9a56-583e4af3df89.png)

Note that I have created an issue on vscode project (rather than the extension project) because it was working fine before the update.

**Comment by artze** [comment] 2020-12-15 14:11
Still does not work on my end.

**Comment by rikarudoaranha** [comment] 2020-12-15 14:21
@artze I have reinstalled the plugin and after a while it started to work again. Maybe you should try.

**Comment by tao-cumplido** [comment] 2020-12-15 14:37
I had rendering issues with a few extensions after the update. They were all resolved after I closed VS Code completely and reopened.

**Comment by artze** [comment] 2020-12-16 09:27
Reinstalling extension didn't work for me.

**Comment by barroudjo** [comment] 2021-02-18 20:45
A combination of removing the extension (and also the windows version), reinstalling it, restarting vscode and restarting wsl (`wsl --shutdown`) did the trick for me.

**Comment by mjbvz** [comment] 2021-02-19 03:29
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/105536

Please let me know if you see this the latest VS Code insiders builds

**Closed by mjbvz** 2021-02-19 03:29 UTC
