### ISSUE TITLE
May 6th 2022: Latest Visual Studio Code Update fails

### ISSUE THREAD

**Issue by dipakboyed** [microsoft/vscode#148953] opened 2022-05-06 19:35 UTC
---------------------------
Visual Studio Code
---------------------------
There was an error while Opening file handle: "...\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\bootstrap-amd.js":
Failed to create file handle: Access is denied.
Please verify there are no Visual Studio Code processes still executing.
---------------------------
Retry   Cancel   
---------------------------
Latest Vs Code updater fails for me on Windows11. I can't see any handle open for this file elsewhere.

**Comment by jsuddsjr** [comment] 2022-05-06 20:00
Failed on Windows 10, too. I also tried installing Visual Studio Insiders, with the same result.

**Comment by lovettchris** [comment] 2022-05-06 21:16
I get the same thing also, I notice the file does not have user write permissions, only admin write permissions:
![image](https://user-images.githubusercontent.com/18707114/167217530-2092fb94-08ed-4856-afd8-83ec3baf9518.png)

**Comment by yonghenghuanmie** [comment] 2022-05-07 10:58
Same problem on windows11.
"May 07 18:46:37.177 INFO Get file handle: "C:\\Users\\huanmie\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code" (attempt 16)"
In fact this file is not in use, I can even delete it. 
This problem continues even after restart.

**Comment by lansalot** [comment] 2022-05-09 09:32
+1 I'm afraid - Fixed by removing the entire "C:\Users\$USER\AppData\Local\Programs\Microsoft VS Code" folder and re-installing. Same file permissions were missing too.

**Comment by ShadowXVII** [comment] 2022-05-10 03:01
I've had this issue too. Affecting my fleet of VS Code users.

Added some discussion here: https://stackoverflow.com/a/72180048/168457. Had to grant users permissions to their AppData directory.

**Comment by amcasey** [comment] 2022-05-10 17:55
@joaomoreno Let me know if you need an internal repro

**Comment by TheJCAB** [comment] 2022-05-10 23:57
May be a clue. I just tried running the installer as admin, and it says this:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/22421744/167742766-8f2ab269-80ff-4b9f-909b-94cbc0f6714b.png">

That installer has a date of today, so it's the one that was being used. But... when I click ok, I then get this:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/22421744/167742888-27a305cc-05a9-4bf4-b446-47620a671ada.png">

Indicating that VSCode is "system-installed". Note that the user installer is being offered by VSCode itself, just after launching it. So it might be some indication that it doesn't know how to system-update itself? Not sure.

I don't remember installing it any differently, but my neurons might be misfiring there :-).

**Comment by ShadowXVII** [comment] 2022-05-11 23:01
Our users sometimes have to run VS Code as admin on occasion for system-focused development. Perhaps it ran a self-update during that time which caused permissions to be lost and instead assigned to Admin group only?

**Comment by michael-hawker** [comment] 2022-05-13 21:34
I've also started hitting this the other day. Just rebooted and still hit it.

**Comment by lovettchris** [comment] 2022-05-13 21:37
I hit it too and had to wipe the folder and do full reinstall.  Definitely something wrong here.
________________________________

**Comment by michael-hawker** [comment] 2022-05-13 21:45
I was able to run the uninstaller and it seemed to wipe that directory clean as well. Installing from the latest download on the website for 1.67.1 worked after that. Will see when it tries to update next what happens.

**Comment by ShadowXVII** [comment] 2022-05-17 10:06
> > Our users sometimes have to run VS Code as admin on occasion for system-focused development. Perhaps it ran a self-update during that time which caused permissions to be lost and instead assigned to Admin group only?
> 
> @ShadowXVII , I have never used VSCode with admin permissions before, but I'm hitting exactly the same error. 

Ah, there goes that theory then. Haven't found any other possible pattern between.

**Comment by devlie** [comment] 2022-05-17 17:55
Those files that vscode installer was complaining about have ACL set to read-only for non admin users. Perhaps the installer is not running elevated when trying to replace them (they are in localappdata, so theoretically it doesn't need to be). I ended up just running the MSI installer directly; that allows me to install the latest VSCode, but the app is now living under Program Files instead of %localappdata%.

**Comment by ant0nsc** [comment] 2022-05-18 08:20
> Those files that vscode installer was complaining about have ACL set to read-only for non admin users. Perhaps the installer is not running elevated when trying to replace them (they are in localappdata, so theoretically it doesn't need to be). I ended up just running the MSI installer directly; that allows me to install the latest VSCode, but the app is now living under Program Files instead of %localappdata%.

I also tried downloading the MSI. When starting, my installer though again tried to write into AppData, and again failed with a permissions problem, screenshot below.

I ended up deleting the whole VSCode folder from AppData, and doing a new install :-(

![image](https://user-images.githubusercontent.com/4396121/168992190-11ce7975-68be-4a5a-9d56-4b0bb57f6ad0.png)

**Comment by jacleggmsr** [comment] 2022-05-18 20:09
Same issue for me.  My VSCode version:

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

I'm running windows 11.

**Comment by rainersigwald** [comment] 2022-05-18 21:09
#147408 is related (or maybe this is a duplicate). `icacls "%LOCALAPPDATA%\Programs\Microsoft VS Code" /grant "%USERDOMAIN%\%USERNAME%":F /T` worked around for me.

**Comment by jamesadevine** [comment] 2022-05-19 09:30
Thanks @rainersigwald, that command worked for me when run from cmd.exe with admin permissions. Once complete, I then hit retry in the updater, and the updater completed successfully.

**Comment by sandersaares** [comment] 2022-05-19 12:39
Also having this with the below version. Started happening today (though I do not use VS code all too often). Never used VS Code as admin, as far as I can recall.

Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by sba923** [comment] 2022-05-19 17:56
It seems that once you have performed an "update on close" while VScode was running elevated / as admin, you can no longer perform updates when non-elevated.

**Comment by joaomoreno** [comment] 2022-05-20 13:28
Duplicate of https://github.com/microsoft/vscode/issues/147408

**Closed by joaomoreno** 2022-05-20 13:28 UTC

**Comment by joshjm** [comment] 2022-06-07 03:20
i got the update to work by;

- closing vs code or restarting
- right click cs code and run as admin
- ctrl shift p, and check for updates/restart to update

and it worked for me
