### ISSUE TITLE
Merge Editor is extremely slow

### ISSUE THREAD

**Issue by MaxWeisen** [microsoft/vscode#157166] opened 2022-08-04 22:27 UTC
Type: <b>Bug</b>

- perform a large rebase with more than 5 commits
- as you reach the end, when you click on files to address conflicts, the new rebase tool pops up
- it takes over 2 minuets per file to open

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 18|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id ec9e84d1-79b9-4581-bc8f-cc562c1170d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|2.3.2
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
prettier-vscode|esb|9.5.0
vscode-pull-request-github|Git|0.48.0
fluent-icons|mig|0.0.18
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
material-product-icons|PKi|1.3.0
vue-vscode-snippets|sdr|3.1.1
code-spell-checker|str|2.3.4
open-in-browser|tec|2.0.0
errorlens|use|3.6.0
learn-vim|vin|0.0.28
vscode-icons|vsc|11.14.0
volar|Vue|0.39.4
material-theme|zhu|3.15.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by hediet** [comment] 2022-08-05 06:40
Can you share your input files? (There is a `Merge Editor Dev` command to copy the state as JSON)
In my experiments with historical merge conflicts in the typescript repository I didn't notice any slowness.

**Comment by isidorn** [comment] 2022-08-11 14:20
Duplicate of https://github.com/microsoft/vscode/issues/157283

**Closed by isidorn** 2022-08-11 14:20 UTC
Labels: info-needed, freeze-slow-crash-leak, merge-editor
