### ISSUE TITLE
VS Code should open images of moderate size

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#57908] opened 2018-09-04 22:05 UTC
VS Code cannot open an image preview of a 5MB PNG file. I think the size constraint was for source code, but not for images.

**Comment by bpasero** [comment] 2018-09-05 04:42
Here is what happens when opening and interacting with a 20 MB image:

![before](https://user-images.githubusercontent.com/900690/45071477-c5a1b800-b0d6-11e8-94e6-9e22504faf1d.gif)

I have a feeling the memory goes down again afterwards but the memory bump is quite crazy. This was on macOS.

Closing as duplicate of #25122

**Closed by bpasero** 2018-09-05 04:42 UTC
