### ISSUE TITLE
Find all references doesn't work in default exports

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#8091] opened 2016-06-24 07:36 UTC
@jrieken I suggest we stop using default exports them until Find All References work in them.

![image](https://cloud.githubusercontent.com/assets/22350/16331215/07bb65bc-39ef-11e6-8d08-afd475e28258.png)

![image](https://cloud.githubusercontent.com/assets/22350/16331199/db611d0e-39ee-11e6-8539-804fcf0d213a.png)

**Comment by jrieken** [comment] 2016-06-24 07:50
Fair point - this goes as works as designed for TS cos the default import is un-named and `import WebView ` is symbol declaration

**Comment by dbaeumer** [comment] 2016-06-24 10:10
Dups https://github.com/Microsoft/TypeScript/issues/9081. 

Closing since this needs to be addressed in TS land.

**Closed by dbaeumer** 2016-06-24 10:10 UTC
Labels: bug, typescript, upstream
