### ISSUE TITLE
Debug breakpoints cannot be remove

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#38150] opened 2017-11-12 11:51 UTC
- VSCode Version: 1.18.0
- OS Version: windows 7, 64-bit

After debugging my extension, the breakpoints just cannot be remove, new breakpoints can be add and remove, shows bellow:
![issue](https://user-images.githubusercontent.com/19996314/32698536-7fed46fe-c7e2-11e7-9be2-cc7c926526af.gif)

**Comment by weinand** [comment] 2017-11-12 13:45
duplicate of #37880. Already fixed in Insiders.

**Closed by weinand** 2017-11-12 13:45 UTC
Labels: debug, new release
