### ISSUE TITLE
Pasting a 1 line string into multiple cursors only applies to the first one

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#181563] opened 2023-05-04 17:51 UTC
![Recording 2023-05-04 at 10 50 41](https://user-images.githubusercontent.com/2193314/236287539-d2b4d25e-5c71-4d75-b267-90c44bc31ca3.gif)

Version: 1.79.0-insider (user setup)
Commit: f5d658848a7d39546e48b9393690b5ff18473a7b
Date: 2023-05-04T05:21:45.650Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by mjbvz** [comment] 2023-05-04 17:53
Duplicate of #181558

**Closed by mjbvz** 2023-05-04 17:53 UTC
Labels: important
