### ISSUE TITLE
Console instance is no longer editable without any command running

### ISSUE THREAD

**Issue by theashggl** [microsoft/vscode#190870] opened 2023-08-21 11:03 UTC
I have a console instance which is not getting edited anymore although I have other consoles which are working fine. I pressed the up button to get the previous command but instead the same command grew and became this big.

`ng new angular_frontendng vcd angular_spring_frontendng vng servecd angular_spring_frontendng servecd angular_spring_frontendng vng vng new angular_frontendrm -fr .gitng new angular_frontendng vcd angular_spring_frontendng vng serve`

At this point I was trying to delete the command by pressing backspace but it did nothing. As a result I had to open other instance instead to resume work.

**Comment by theashggl** [comment] 2023-08-22 14:41
FYI, this is a random event. I don't know how to reproduce it and will not be able to provide more information on it probably. I still have the terminal open, if needed I can only provide the screenshots or anything related to it until the window is open. Once closed it will be gone.

**Comment by Tyriar** [comment] 2023-08-22 14:43
Since it's random that makes me think more that it's an issue in conpty. See my standard response below:

This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/label terminal terminal-conpty windows

**Closed by Tyriar** 2023-08-22 14:43 UTC
Labels: windows, confirmation-pending, terminal-input
