### ISSUE TITLE
Wrong syntax highlighting for CSS keyframes

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14726] opened 2016-10-31 01:02 UTC
- VSCode Version: 1.7 Insider

`from` is not tokenized correctly it seems.

![image](https://cloud.githubusercontent.com/assets/4033249/19841539/bd0a37b4-9eca-11e6-8d4a-5a317e719ca4.png)

![image](https://cloud.githubusercontent.com/assets/4033249/19841551/d6913cf0-9eca-11e6-907e-6852f49a6ae5.png)

**Comment by aeschli** [comment] 2016-11-01 10:13
duplicate of #3481

**Closed by aeschli** 2016-11-01 10:13 UTC
Labels: css-less-sass
