### ISSUE TITLE
Tsx file intellisense on 0.10.5

### ISSUE THREAD

**Issue by goaty92** [Microsoft/vscode#1503] opened 2015-12-20 09:04 UTC
The intellisense when writing tsx file is lost. Those were working on 0.10.3

![button](https://cloud.githubusercontent.com/assets/11325809/11917270/27105a5c-a733-11e5-9b59-7b5b72f9458b.png)
![import](https://cloud.githubusercontent.com/assets/11325809/11917269/270c4b92-a733-11e5-92e9-4ba30953548e.png)

Besides, the syntax highlighting seems broken. Interfaces are no longer highlighted

**Comment by egamma** [comment] 2015-12-20 16:21
Problem confirmed, hover, goto definition still works but Intellisense is broken.

**Comment by egamma** [comment] 2016-02-03 11:04
Cannot reproduce in 0.10.7-insiders. Closing.

**Closed by egamma** 2016-02-03 11:04 UTC
Labels: bug, important, typescript
