### ISSUE TITLE
GIF file staged in Git repo, crashes window

### ISSUE THREAD

**Issue by drewda** [Microsoft/vscode#70917] opened 2019-03-21 19:59 UTC
Issue Type: <b>Bug</b>

In the process of staging and committing a small animated GIF file into a Git repo, my VS Code hangs.

--

Steps to reproduce:

1. Stage a `.gif` file using git (It's small: ~350Kb)
2. Switch to Source Control panel
3. Single click on the gif file listed under "STAGED CHANGES"

After a minute or two of delay: `The window is no longer responding. You can reopen or close the window or keep waiting.` Nothing ever appears in the main body window of the editor.

Note that when I am in the Editor panel, it's possible to view the GIF file. It's just a problem when in the Source Control panel.

--

Perhaps related to #66495. However, this is a pretty small GIF (well under 1Mb) and the problem occurs during in the context of Git.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
vscode-direnv|Rub|0.0.2
project-manager|ale|10.4.0
vscode-sqlite|ale|0.6.0
Handlebars|and|0.4.1
markdown-mermaid|bie|1.1.2
better-toml|bun|0.3.2
solargraph|cas|0.19.3
vscode-postgres|cko|1.1.9
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
vscode-pull-request-github|Git|0.5.1
beautify|Hoo|1.4.11
nbpreviewer|jit|1.2.2
rainbow-csv|mec|1.0.0
handlebars-formatter|mfe|0.0.3
dotenv|mik|1.0.1
vscode-open-in-sourcetree|mor|0.6.0
vscode-kubernetes-tools|ms-|0.1.18
python|ms-|2019.2.5558
cpptools|ms-|0.22.0
Go|ms-|0.9.2
vscode-typescript-tslint-plugin|ms-|1.0.0
vetur|oct|0.17.0
vscode-docker|Pet|0.6.1
vscode-graphql|Pri|0.1.7
ruby|reb|0.22.3
java|red|0.41.0
vscode-yaml|red|0.3.0
vscode-nginx|sha|0.6.0
vscode-checkstyle|she|1.0.2
gitconfig|sid|2.0.0
vscode-fileutils|sle|2.13.5
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2
change-case|wma|1.0.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by joaomoreno** [comment] 2019-03-22 10:04
Can you send us the gif?

**Comment by drewda** [comment] 2019-03-22 16:46
https://www.interline.io/images/here-cli-supports-geojsonl/streaming-geojsonl.gif

**Comment by joaomoreno** [comment] 2019-03-25 10:45
I can't reproduce over here.

Can you reproduce in the latest [insider release](https://code.visualstudio.com/insiders)?

**Comment by drewda** [comment] 2019-03-25 16:26
I have just tested again in both 1.32.3 and 1.33.0-insider. I still get the problem in 1.32.3. It works in 1.33.0-insider.

(Note that I have a good amount of custom config and extensions added to 1.32.3 that I have not copied over to 1.33.0-insider.)

**Comment by joaomoreno** [comment] 2019-03-26 08:06
Thanks! Duplicate of https://github.com/Microsoft/vscode/issues/69334

**Closed by joaomoreno** 2019-03-26 08:06 UTC
Labels: git, needs more info
