### ISSUE TITLE
Hidden comment thread requires double click to reveal the first time

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#164471] opened 2022-10-24 15:52 UTC
* Open a pull request that has comments made already
* Open the changed file with the comment
* When the comment thread is hidden by default, first click on the comment icon doesn't reveal it. The second does.

**Comment by alexr00** [comment] 2022-10-24 17:02
@rebornix I'm not able to reproduce this. Do you know why the comment was hidden by default?

**Comment by rebornix** [comment] 2022-10-27 23:26
@alexr00 I don't know, it seems they are often hidden for me. I thought we had heuristics (a feature but not bug). But now I think it's probably a state out of sync. The widget is not visible, but the state says it is, so the first click hide it again.

**Comment by KrabsWong** [comment] 2022-11-02 14:56
> @alexr00 I don't know, it seems they are often hidden for me. I thought we had heuristics (a feature but not bug). But now I think it's probably a state out of sync. The widget is not visible, but the state says it is, so the first click hide it again.

I met the same issue with my own extension.
It seems that if I set the default collapseState to Expanded, then I have to click the comment thread twice to expand it.

Set to Collapse with code or don't set anything, the behavior is correct -> Show up comments thread collapsed by default and expand it by click it once.

**Comment by KrabsWong** [comment] 2022-11-02 15:02
> @rebornix I'm not able to reproduce this. Do you know why the comment was hidden by default?

From my side, if I set `vscode.CommentThreadCollapsibleState.Expanded` to `thread.collapsibleState`, this case happens.

It works well if I set `vscode.CommentThreadCollapsibleState.Collapsed` or set nothing to thread.

**Comment by KrabsWong** [comment] 2022-11-11 03:02
Any progress on this issue?

**Comment by alexr00** [comment] 2022-11-11 08:55
I can reproduce the issue in web but not in desktop.

**Comment by KrabsWong** [comment] 2022-11-11 09:16
> I can reproduce the issue in web but not in desktop.

yes, happened in web.

**Comment by KrabsWong** [comment] 2022-11-23 03:14
Any progress?

**Comment by alexr00** [comment] 2022-11-24 14:36
Now I'm not able to reproduce this at all. @KrabsWong are you able to reproduce this in insiders.vscode.dev?

**Comment by KrabsWong** [comment] 2022-11-27 16:42
> Now I'm not able to reproduce this at all. @KrabsWong are you able to reproduce this in insiders.vscode.dev, and if so, can you share the pull request you saw the issue with?

Test from my side with github.dev (vscode version 1.73.1), expanded by default works well.

Test repo: https://github.com/KrabsWong/comments-expanded-verification
Test extension: https://marketplace.visualstudio.com/items?itemName=t-codespaces.comments-expand-verification

Step
1. Open any file
2. Execute command "Insert demo comments"

Then there are two comments added to line 2 and 4 with expanded by default

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/12368943/204148494-4e286b89-e398-47bb-8a86-44d24a27bb43.png">

**Comment by alexr00** [comment] 2022-11-28 08:51
@KrabsWong thanks for confirming that it works as expected for you now. Closing as this appears to have been fixed in the time since the issue was filed.

**Closed by alexr00** 2022-11-28 08:52 UTC
Labels: bug, info-needed, comments

**Comment by sergei-dyshel** [comment] 2023-01-06 20:28
@alexr00 
In what version was this issue fixed? I'm 1:1 reproducing it on 1.74 version (desktop). For example with `GitHub Pull Requests and Issues` plugin:

1. Configure `"githubPullRequests.commentExpandState": "expandUnresolved"` in settings json.
2. Open PR and file  with unresolved comments.
3. Unresolved comments appear as collapsed and 2 clicks are required to expand the thread

**Comment by alexr00** [comment] 2023-01-09 15:04
@sergei-dyshel those of us who saw this work actually just got lucky. It is actually fixed only in insiders (1.75) right now.

**Comment by alexr00** [comment] 2023-01-09 17:17
Should be this one: https://github.com/microsoft/vscode/commit/65462a0974c14bde44b88d7a772160dd680e80f2
