### ISSUE TITLE
lib.dom.d.ts leaks to @ts-check?

### ISSUE THREAD

**Issue by hemanth** [microsoft/vscode#102561] opened 2020-07-15 04:46 UTC
```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (1 mo ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. One any JS file, define `name` variable.
2. We see the redeclaration error.

![image](https://user-images.githubusercontent.com/18315/87504210-eca66a80-c61a-11ea-935f-e0a07bd40691.png)

Does this issue occur when all extensions are disabled?: Yes

Should `declare const name: never;` be a `declare var name: never;`?

**Comment by mjbvz** [comment] 2020-07-15 22:26
Duplicate of https://github.com/microsoft/TypeScript/issues/39534

**Closed by mjbvz** 2020-07-15 22:26 UTC
