### ISSUE TITLE
VS Code still shows errors for a typescript code file with // @ts-nocheck

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/vscode#74151] opened 2019-05-22 18:16 UTC
Issue Type: <b>Bug</b>

I have a .api.ts file (output from @microsoft/api-extractor) that's under ./temp folder which is not included in tsconfig.json. VS Code shows errors for this file even I had "// @ts-nocheck" at the top.

![image](https://user-images.githubusercontent.com/7583839/58198406-06e8f080-7c83-11e9-8b89-0775a24fba4b.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.76GB (18.69GB free)|
|Process Argv|--folder-uri file:///c%3A/github/jeremymeng/azure-sdk-for-js/sdk/storage/storage-blob|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-generate-getter-setter|DSK|0.5.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
vscode-pull-request-github|Git|0.6.0
ilspy-vscode|ics|0.7.5
docthis|joe|0.7.1
vscode-typescript-ast-explorer|kri|1.0.0
azurecli|ms-|0.4.5
Go|ms-|0.10.2
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2
trailing-spaces|sha|0.3.1

</details>

**Comment by mjbvz** [comment] 2019-05-22 18:23
Duplicate of https://github.com/microsoft/TypeScript/issues/26887

**Closed by mjbvz** 2019-05-22 18:23 UTC
