### ISSUE TITLE
Git command incorrect shows in terminal.

### ISSUE THREAD

**Issue by Lucien-Lu** [Microsoft/vscode#24743] opened 2017-04-14 06:16 UTC
- VSCode Version:1.11.2
- OS Version:macOS Sierria 10.12.4

Steps to Reproduce:

1.When I type in 'git s' ,the path which include Chinese always shows path twice.
2.Just look at 'time.json',the path repeat twice!
<img width="630" alt="2017-04-14 14 13 43" src="https://cloud.githubusercontent.com/assets/15938765/25034908/a68e672e-211c-11e7-8772-bb71a7e549ea.png">

**Comment by Tyriar** [comment] 2017-04-17 18:11
@Lucien-Lu hmm, I haven't seen this before, could you provide the following to help diagnose?

- `echo $LANG` output
- Does this happen in Terminal.app?
- Can you provide the text so I can try repro with the exact string?

**Comment by rmunn** [comment] 2017-04-18 03:55
I wonder if this might be somehow related to (although not a duplicate of) #24737, where Chinese characters' width was being incorrectly calculated in the integrated terminal. The bug here is probably different, but I notice that the repeated part of the text is laid out differently (wider spacing between characters) than the first occurrence of the repeated string, which is what made me think of #24737. If there's some terminal layout bug that's triggered by Chinese text (and, presumably, other languages with double-width characters, such as Japanese), then it may be affecting (though probably not causing) this behavior as well.

If the layout bug is indeed related, then #19665 may somehow be related as well.

**Comment by Tyriar** [comment] 2017-04-18 18:36
@rmunn https://github.com/Microsoft/vscode/issues/19665 is the root cause for all the Windows Creator's Update issues. This looks like a different thing as the Windows problem causes weird wrapping, not duplicated characters.

**Comment by Lucien-Lu** [comment] 2017-04-19 14:43
@Tyriar This doesn't happened in Terminal.app and I type the cmd you provide in integrated terminal.
<img width="327" alt="2017-04-19 22 40 23" src="https://cloud.githubusercontent.com/assets/15938765/25186032/85c9a632-2551-11e7-8c08-6de78af9cdea.png">

**Comment by Tyriar** [comment] 2017-04-20 00:58
@Lucien-Lu do you have anything in your settings.json?

**Comment by Lucien-Lu** [comment] 2017-04-20 10:18
@Tyriar Here is my settings.json.
```
// 将设置放入此文件中以覆盖默认设置
{
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "TwoStones",
    "workbench.experimental.colorCustomizations":{
            "editorCursor":"#f2c643",
            "editorLineNumbers": "#ff0000",
            "activeTabBackground": "#9900ee"
        },
    "window.zoomLevel": 0,
    "editor.fontSize": 14,
    "editor.renderLineHighlight": "none",
    "files.autoSave": "afterDelay",
    "window.title": "${activeEditorLong}${separator}${rootName}",
    "todohighlight.isEnable": true,
    "todohighlight.isCaseSensitive": false,
    "todohighlight.highlightWholeLine": true,
    "todohighlight.include": "{**/*.js,**/*.html,**/*.php,**/*.css}",
    "todohighlight.keywords": [
         {  
            "text": "TODO:", // custom text to be highlighted
            "color": "orange", // the text color, any css color identifier is valid
            "backgroundColor": "#27a", // the text background color
            "overviewRulerColor": "grey" //the color of the ruler mark on the scroll bar. use rgba() and define transparent colors to play well with other decorations.
        }
    ],
    "workbench.statusBar.visible": false
}
```

**Comment by Tyriar** [comment] 2017-04-20 17:59
@rebornix have you experienced this? I can't reproduce.

**Comment by rebornix** [comment] 2017-04-20 18:10
I can reproduce when there is Chinese character in a file path

![screen shot 2017-04-20 at 11 09 34 am](https://cloud.githubusercontent.com/assets/876920/25245642/f6c04df6-25b9-11e7-8a2a-3bb2ea27d806.png)

**Comment by nuintun** [comment] 2017-05-05 01:43
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|Bookmarks|alefragnani|0.14.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-svgviewer|cssho|1.4.0|
|vscode-npm-source|dkundel|1.0.0|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.1.2|
|EditorConfig|EditorConfig|0.9.3|
|tortoise-svn|fantasytyx|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|docthis|joelday|0.4.4|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|
|material-icon-theme|PKief|2.0.5|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.6.0|
|aspnet-helper|schneiderpat|0.6.3|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.1.0|;

This bug still exists in the new version.

![xterm](https://cloud.githubusercontent.com/assets/1730277/25731257/391723a0-3177-11e7-84a9-7d4f3d561e4c.gif)
![xterm2](https://cloud.githubusercontent.com/assets/1730277/25731258/3ac5e312-3177-11e7-9c3b-5f2b661a5d41.gif)

**Comment by Tyriar** [comment] 2017-05-09 17:59
Duplicate https://github.com/Microsoft/vscode/issues/26038

**Closed by Tyriar** 2017-05-09 17:59 UTC
Labels: bug, integrated-terminal
