### ISSUE TITLE
Check for updates does nothing when client is left running for a while

### ISSUE THREAD

**Issue by yoav-lavi** [Microsoft/vscode#38483] opened 2017-11-16 08:17 UTC
- VSCode Version: 1.19.0 (Insiders)
- OS Version: Microsoft Windows 10 Enterprise Build 15063

Steps to Reproduce:

1. Leave client open overnight (Not sure if this is correlated with a client that wasn't closed since the last time it was updated, but likely that it isn't)
2. Check for updates
3. The "Checking for updates..." label should be gray for a while and do nothing
4. After restarting the client, it works correctly

**Comment by mattacosta** [comment] 2017-11-16 22:56
Duplicate of #25632.

**Closed** 2017-11-17 08:50 UTC
Labels: insiders, install-update
