### ISSUE TITLE
Please add a feature: toggle the '\n' which is in the end of final line render effect

### ISSUE THREAD

**Issue by Imputes** [Microsoft/vscode#69143] opened 2019-02-21 13:45 UTC
## I know the POSIX defined a line that must end with '\n' character, but I can use the:
```json
"files.insertFinalNewline": true
```
## I know the `Microsoft` is best! And I believe you can complete this!

**Comment by alexandrudima** [comment] 2019-02-21 16:26
THIS HAS JUST BEEN IMPLEMENTED !

If you will download the [insiders version](https://code.visualstudio.com/insiders/), you can configure `"editor.renderFinalNewline": false`, which will actually be the default on Linux!

(duplicate of #1027)

**Closed by alexandrudima** 2019-02-21 16:26 UTC
