### ISSUE TITLE
Diff editor shows the spaces diff after when all diffs are removed 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19205] opened 2017-01-24 14:01 UTC
Testing #19049

![jan-24-2017 15-00-04](https://cloud.githubusercontent.com/assets/10746682/22250099/f8dddae8-e245-11e6-9a22-c35648ffec45.gif)

**Comment by alexandrudima** [comment] 2017-01-25 08:55
Duplicate of #18353

**Closed by alexandrudima** 2017-01-25 08:55 UTC
