### ISSUE TITLE
Hover not working in vscode LSP

### ISSUE THREAD

**Issue by SukiTUK** [microsoft/vscode#139370] opened 2021-12-17 12:04 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.62.3 (Universal)
- OS Version: Mac OS Big Sur 11.6

I am trying to implement hover feature for LSP using vscode
Steps to Reproduce:

1. I have added the following code in extensions.ts - but it doesnt work (client side implementation is not working)
2. When I enable hoverProvider capabilities in server.ts - the hover content is fetched from the server (server side implementation is working)

Can you tell me what is wrong with my code?

`export function activate(context: ExtensionContext) {
..........
	// Start the client. This will also launch the server
	client.start();
	**const disposable = languages.registerHoverProvider('scraperflow', {
		provideHover(document, position, token) {
			return new Hover({ language: "scraperflow", value: 'Message to show on Hover'});
		}
	});
	context.subscriptions.push(disposable);**

}`

**Comment by jrieken** [comment] 2021-12-20 09:19
I do see hovers working. Must be something specific to your extension. The snippet looks fine but isn't complete. Can you share a more complete sample that show hovers not working?

**Comment by SukiTUK** [comment] 2021-12-20 10:57
@jrieken I am able to see the hover but only from the server side ( which I have achieved with the following code in server.ts

`connection.onHover(({ textDocument, position }): Hover => {
    const document = documents.get(textDocument.uri);
    const start = {
		line: position.line,
		character: 0,
	};
	const end = {
		line: position.line + 1,
		character: 0,
	};
	return {
		contents: "what the heck from server side"
	};
});`)

video of Hover: https://drive.google.com/file/d/1VNF-_AT8ZPGTTU2OwYPmNU1heJlmnCJB/view?usp=sharing

The code written in extension.ts is not called and I donot get the message from the client side

`const disposable = languages.registerHoverProvider('scraperflow', {
		provideHover(document, position, token) {
			return new Hover({ language: "yales2", value: 'Hover from client side'});		}
	});
	context.subscriptions.push(disposable);

}`

**Comment by jrieken** [comment] 2021-12-20 11:02
Sorry, but a video doesn't allow me to reproduce this. Please share a complete sample that reproduces this, a good starting point is to generate a simple extension with `yo code`

**Comment by SukiTUK** [comment] 2021-12-20 11:22
I generated yo code and upload to https://github.com/SukiTUK/extensionLSP
I have given you the access @jrieken  . Please check and let me know if this is ok.

**Comment by SukiTUK** [comment] 2021-12-20 11:36
> Can you zip this up and attach the project here. Thanks

Sorry, I have no options to attach zip here. only option for me is to include links :( 
@jrieken

**Comment by SukiTUK** [comment] 2021-12-20 11:45
Suddenly the hover on client and from server side- both are working.... - not sure how? why? 

Thanks for the quick support, @jrieken 

One query: when would one implement server side or client side hover?

Whats the specific business use case and how would I choose from the two?

**Comment by jrieken** [comment] 2021-12-20 16:25
LSP means that your "server" can be reused by multiple editors, like VS Code or Sublime Text etc. If you don't need that implement a "normal" extension. 

I am closing this issue without action since the issue went aways and wasn't reproduciable for me

**Closed by jrieken** 2021-12-20 16:25 UTC
Labels: needs more info
