### ISSUE TITLE
Unclosed Single/Double Quotes in Template Strings Break Syntax Highlighting

### ISSUE THREAD

**Issue by davezuko** [Microsoft/vscode#129] opened 2015-11-19 00:28 UTC
If you use one single or double quote without closing it, syntax highlighting breaks (even with ES6 enabled as the target). Heres' an example:

![screen shot 2015-11-18 at 7 29 37 pm](https://cloud.githubusercontent.com/assets/6439050/11258829/bc70aaf6-8e2a-11e5-9a85-14a30811eb61.png)

My `jsconfig.json`:

```
{
  "compilerOptions": {
    "target": "ES6"
  }
}
```

**Edit**: In retrospect this may simply be that template strings _aren't_ highlighted, which causes this weird behavior.

**Comment by davezuko** [comment] 2015-11-19 13:31
This might be tied to https://github.com/Microsoft/vscode/issues/133.

**Comment by dn7q3b** [comment] 2015-11-19 19:44
Syntax highlighting in template strings is not working at all. The template string functionality itself works so far.

Issue seems to be that its not that template strings are not highlighting but that syntax highlighter has no concept of tilda quoted strings(template strings).

Expecting everything except ${expression} to be comment colored.

![tildaquotes](https://cloud.githubusercontent.com/assets/15118702/11282151/ce0eab68-8ecb-11e5-9d69-2cee67042129.png)

**Comment by StrahilKazlachev** [comment] 2015-11-20 13:06
Also if you have unclosed "comment" in template literal ``var path = `${root}/**/*.ts`; ``

**Comment by aeschli** [comment] 2015-11-24 16:52
duplicate of #133

**Closed by aeschli** 2015-11-24 16:52 UTC
