### ISSUE TITLE
terminal not work, exit code: {0}

### ISSUE THREAD

**Issue by digobarreto** [microsoft/vscode#86148] opened 2019-12-03 19:24 UTC
Open and terminal display message: the terminal process terminated with exit code: {0}

**Comment by gjsjohnmurray** [comment] 2019-12-03 23:37
/duplicate of #73790

See https://github.com/microsoft/terminal/issues/1838 for screenshot showing checkbox to clear.

**Closed** 2019-12-03 23:38 UTC
Labels: *duplicate, integrated-terminal
