### ISSUE TITLE
Extract method breaks formatting

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33496] opened 2017-08-30 09:27 UTC
```ts
function foo(b1: boolean, b2: boolean) {
	let x = 0;
	let y = 0;

	if (b1) {
		x = 1;
	}
	if (b2) {
		y = y + x;
	}
	return y;
}
```

Select
```ts
	if (b1) {
		x = 1;
	}
	if (b2) {
		y = y + x;
	}
```

- extract
- you get
```ts
function newFunction(b1: boolean, x: number, b2: boolean, y: number) {
    if(b1) {
    x = 1;
}
    if(b2) {
    y = y + x;
}
    return { x, y };
}
```

Observe the broken indentation

**Comment by mjbvz** [comment] 2017-08-30 20:44
Duplicate of #33443, also tracked upstream by Microsoft/TypeScript#18091

Will investigate a workaround

**Closed by mjbvz** 2017-08-30 20:44 UTC
Labels: typescript
