### ISSUE TITLE
TypeScript and JavaScript Language Features

### ISSUE THREAD

**Issue by Silverium** [microsoft/vscode#147281] opened 2022-04-12 08:30 UTC
Issue Type: <b>Bug</b>

I do nothing, but the TypeScript and JavaScript Language Features extension keeps crashing and restarting

VS Code version: Code 1.66.1 (Universal) (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:49:47.400Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 12, 11|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 6b1b35f2-03e5-45e4-be8e-73b9cf8d8e34|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.2
vscode-intelephense-client|bme|1.8.2
vscode-eslint|dba|2.2.2
vscode-quick-select|dba|0.2.9
docs-yaml|doc|0.2.8
xml|Dot|2.5.1
gitlens|eam|12.0.5
prettier-vscode|esb|9.5.0
shell-format|fox|7.2.2
copilot|Git|1.12.5517
go|gol|0.32.0
vscode-react-typescript|inf|1.3.1
vscode-env|Iro|0.1.0
svg|joc|1.4.17
vscode-styled-components|jpo|1.7.0
vscode-codemetrics|kis|1.24.0
sftp|lix|1.12.10
vscode-typescript-tslint-plugin|ms-|1.3.4
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
vscode-jest|Ort|4.2.1
vscode-thunder-client|ran|1.16.0
vscode-yaml|red|1.6.0
LiveServer|rit|5.7.5
vs-code-prettier-eslint|rve|3.1.0
vscode-javascript-booster|sbu|14.0.1
es6-mocha-snippets|spo|0.2.2
git-prefix|srm|1.3.0
code-spell-checker|str|2.1.11
jest-snapshot-language-support|tle|1.1.1
vscode-counter|uct|3.0.3
sync-rsync|vsc|0.36.0
full-react-snippets|wal|1.4.2
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by IllusionMH** [comment] 2022-04-12 08:46
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by Silverium** [comment] 2022-04-13 11:37
I got what happens. I create `tsconfig.json` dynamically every time I run the project with certain parameters, or when I run the tests. So in fact it restarts TS features with a good reason. I think that it's working as expected.

Thank you for your attention. 

Nevertheless, it would be cool that we can discard this notification to report.

The notifications states: "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."

**Comment by mjbvz** [comment] 2022-04-13 18:17
I don't think this is expected as it means the server is crashing

Can you share steps to reproduce the issue so we can investigate it?

**Comment by Silverium** [comment] 2022-04-14 06:10
OK, yes, we found an issue. It's crashing. When I disable all extensions, it works fine again. I am going now to see if I can find the extension causing the crashes.

**Comment by Silverium** [comment] 2022-04-14 06:14
I think I had a hunch or I was lucky, because the first extension I disabled was enough. Disabling Jest's extension made my VS Code to work normal again.

Name: Jest
Id: Orta.vscode-jest
Description: Use Facebook's Jest With Pleasure.
Version: 4.2.1
Publisher: Orta
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest

**Comment by Silverium** [comment] 2022-04-14 08:26
I was wrong, it was not that Jest Plugin, after a while it kept crashing again. The culprit was for TS-Lint plugin

Name: TSLint
Id: ms-vscode.vscode-typescript-tslint-plugin
Description: TSLint support for Visual Studio Code
Version: 1.3.4
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin

**Comment by mjbvz** [comment] 2022-05-23 23:23
Closing as caused by extension based on the feedback

**Closed by mjbvz** 2022-05-23 23:23 UTC
Labels: needs more info
