### ISSUE TITLE
Bottom left "action" (gear icon) menu not scrolling (MacOS)

### ISSUE THREAD

**Issue by atrn** [microsoft/vscode#40262] opened 2017-12-15 06:20 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
project-manager|ale|0.23.1
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
togglehs|bbe|0.1.2
gitignore|cod|0.5.0
githistory|don|0.2.3
git-project-manager|fel|1.4.0
auto-close-tag|for|0.5.5
Go|luk|0.6.69
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.4
debugger-for-chrome|msj|4.0.0
vscode-emacs-improved|rkw|0.1.1
cmake|twx|0.0.17
vscode-lldb|vad|0.7.1
cmake-tools|vec|0.10.3
gitblame|wad|2.2.0
clang-format|xav|1.6.1

(7 theme extensions excluded)

---

Steps to Reproduce:

1. Resize VS Code window so it occupies most but not all, of the display.
2. Click on bottom left "action" (gear icon) menu because it has
   an indicator on it (I'd just updated and it was the restart button).
3. Menu draws as a drop down but is clipped due to lack of space. See arrow at bottom of menu indicating it can scroll.
4. Attempt to scroll menu clicking on arrow and usual MacOS pointer motion. Menu doesn't scroll.
5. Resize window to give more room below (effectively moving the gear icon up a little). Click gear icon and see full menu.

The menu display changes location at different window sizes, which really means available space for the menu's height.  With a slightly larger window size the menu renders itself above and to the right of the gear icon.  Reducing the window height a little has it render as a drop-down (below) but with  insufficient height to display the full menu and adds the non-functioning scroll arrow.

Reproduces without extensions:  Yes

**Comment by ricobbe** [comment] 2017-12-25 18:08
After the most recent VSCode update, the gear-icon menu mentioned in the original submission appears to be fixed; it now displays on-screen in a position that allows the entire menu to display without scrolling.

However, I can still reproduce the original problem by right-clicking on an identifier in a line of an editor window that's close to the bottom of the screen.  See attached screenshot for an example; the bottom of the screenshot is the bottom of the screen.  As in the original report, neither clicking on nor hovering over the downward arrow in the popup menu has any effect.

![image](https://user-images.githubusercontent.com/30275542/34342105-1bde51f4-e95b-11e7-98c9-752fc7fceac6.png)

**Comment by bpasero** [comment] 2019-05-26 07:45
This bugs me a lot too, @deepak1556 any clues?

**Comment by bpasero** [comment] 2019-10-08 14:21
This is annoying. @deepak1556 we should address this somehow.

**Comment by bpasero** [comment] 2019-12-17 15:06
This is reported as https://github.com/electron/electron/issues/14261

**Comment by akaroml** [comment] 2020-03-04 03:31
Here's a related case in the bottom left corner. When there is enough space (full screen available) to show the full menu, vscode only uses a smaller portion and shows part of the menu items. I need to scroll to see all the items all the time. Check out this screen recording:

![vscode scroll to show full menu](https://user-images.githubusercontent.com/16755094/75842489-61ff6480-5e0b-11ea-927f-32ef8e82a24f.gif)

**Comment by bpasero** [comment] 2020-10-30 09:49
@deepak1556 @sbatten latest insiders from today seems to have fixed the issue for me! did we also move the location of the menu in native? I know we changed it for the custom menu.

![recording](https://user-images.githubusercontent.com/900690/97690705-a37d0800-1a9d-11eb-9c09-26b7c936611d.gif)

**Comment by sbatten** [comment] 2020-10-30 18:13
well i did change the native one to use the mouse location instead, but I'm not understanding the position in your screen shot.

**Comment by sbatten** [comment] 2020-10-30 18:15
oh I know, what's happening (I used native for titlebar setting but forgot macos titlebar custom => native menus) so its using the custom menu logic. I mean I can keep it that way if it looks good?

**Comment by bpasero** [comment] 2020-10-31 06:13
@sbatten since it is not a right-click menu I think the position now is actually better than before and if it fixes the scrolling issue on macOS, even better.

**Comment by sbatten** [comment] 2020-11-02 18:52
since this was caused by a bug in the logic, i updated the logic to make it intentional. will close this now

**Comment by sbatten** [comment] 2020-11-12 17:32
I updated how context view lays making alignment a lot better for custom menus. Unfortunately we don't have that level of control for native menus. The "bug" that fixed this has been removed since it is not a reliable fix and it resulted in some strange cases as well.

**Comment by deepak1556** [comment] 2021-03-12 03:51
Is this still an issue ? I am unable to repro with latest insiders.

**Comment by atrn** [comment] 2021-03-12 09:55
Seems to have been fixed for a while.  Works fine for me these days.

**Comment by bpasero** [comment] 2022-07-30 05:58
This is happening for a long time still:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/900690/181876979-739301bd-101b-4517-aeed-8bdbc8e02913.png">

**Comment by bpasero** [comment] 2022-08-03 05:22
Looks like a fix is in the works: https://github.com/electron/electron/pull/35194

**Closed** 2022-08-04 13:32 UTC
Labels: bug, upstream, electron, menus, upstream-issue-linked, papercut :drop_of_blood:

**Comment by bpasero** [comment] 2022-08-04 13:46
Nice 🎸
