### ISSUE TITLE
vscode in WSL cant update: Unable to download server on client side

### ISSUE THREAD

**Issue by dragonH** [microsoft/vscode#118744] opened 2021-03-11 16:42 UTC
- VS Code Version: 1.54.1
- OS Version: Windows build 19042 WSL2 (Ubuntu 18.04)

Steps to Reproduce:

1. Type `code` in WSL

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/18332044/110822233-d47f0c00-82cb-11eb-9795-96a63677d1e7.png)

it looks like the server is not reachable

**Comment by maple3142** [comment] 2021-03-11 17:55
![image](https://user-images.githubusercontent.com/9370547/110832207-0006f400-82d6-11eb-9aca-8b15338173c3.png)

Same problem here

VSCode + WSL not working after update

**Comment by aeschli** [comment] 2021-03-12 08:15
duplicate of https://github.com/microsoft/vscode-remote-release/issues/4648

**Closed by aeschli** 2021-03-12 08:15 UTC
