### ISSUE TITLE
Very slow debugger launching, with errors

### ISSUE THREAD

**Issue by DmitryAndreyeff** [Microsoft/vscode#36821] opened 2017-10-24 12:52 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Freshly installed node.js 8.7
2. VS code launched without extensions (--disable-extensions)
3. Opened a single line (console.log("test");) javascript file, placed a breakpoint on that line
4. Menu Debug->Start debugging

Result:
In most cases after ~1 minute thinking VSCode throws error "Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:13979)."
In some other rare cases after ~1 minute the debugger is launched and stops on the breakpoint.

launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "protocol": "inspector",
            "program": "${workspaceFolder}\\index.js"
        }
    ]
}

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-10-24 16:56
> In some other rare cases after ~1 minute the debugger is launched and stops on the breakpoint.

Weird, what is it doing for 1 minute? If you launch in debug mode manually, with `node --inspect-brk index.js`, is there any delay before it prints the messages that it's ready for the debugger to attach?

**Comment by DmitryAndreyeff** [comment] 2017-10-24 19:46
When I launch node manually I get message "Debugger listening..." very quickly.

Looked at the task manager during that minute. Noticed commands "where node" and then "node --version". Both take a lot of CPU and time. When I run these from CMD shell I get result within 1-2 seconds. Weird...

**Comment by roblourens** [comment] 2017-10-24 21:15
That is weird. Can you set the `"runtimeExecutable"` property to the location of node, and see whether it's much faster?

**Comment by DmitryAndreyeff** [comment] 2017-10-25 09:16
runtimeExecutable makes things a little faster, but still the whole IDE is very laggy. I've tried to reinstall it but it did not help. It feels like all processes spawned by VSCode are very slow.
I execute the same command "node --version" from VSCode terminal window and almost at the same time in the CMD shell. The shell gives result way faster. Task manager shows that both processes start without delays.

**Comment by roblourens** [comment] 2017-10-25 17:41
Can you tell me more about your system? Is this a VM? Does it have more than one CPU core? How much RAM, how many CPU cores, etc?

**Comment by DmitryAndreyeff** [comment] 2017-10-25 17:56
Lenovo T450 laptop, Intel i5, 4 cores, 8Gb RAM, 64 bit, Windows 7 Enterprise SP 1. Works pretty well.

I don't see MsMpEng.exe process at all.

**Comment by roblourens** [comment] 2017-10-25 18:46
Ok, you said

>  but still the whole IDE is very laggy. I've tried to reinstall it but it did not help. It feels like all processes spawned by VSCode are very slow.

Everything is slow? Launching, opening files, etc?

**Comment by DmitryAndreyeff** [comment] 2017-10-25 18:55
Launching is rather slow and CPU goes crazy for some time after launching, however the UI is responsive, files open quickly even during high CPU.

**Comment by roblourens** [comment] 2017-10-25 21:47
Ok, can you check which processes are using lots of CPU after launching? Is that still going on when you try to start debugging?

**Comment by DmitryAndreyeff** [comment] 2017-10-26 05:31
I start debugging after I waited long enough (~3min) for the CPU to calm down after launch. The same is for the test I did with "node --version".

About the processes taking up a lot of CPU and time during startup.
3-4 instances of Code.exe process in parallel. These are the switches I noticed in each different process
--disable-extensions
--reporter-url=…
--type=renderer…
--type=searchService
--type=extensionHost

Two Reg.exe processes with some key and switches "/v UserId" and "/v MachineId"

Then git.exe with switch "-- version" and then with "Rev-parse --show-toplevel"

**Comment by DmitryAndreyeff** [comment] 2017-11-06 09:58
Hi, the thread is still labeled "need more info". Is there anything specific I need to provide?

**Comment by roblourens** [comment] 2017-11-06 19:25
So it sounds like this isn't specific to debugging, and everything that Code does is running slowly on your machine for some reason.

It sounds like you tried launching with the `--disable-extensions` flag, which would be my next ask.

Could you download the Insiders build and see if it's any better there?

And if not, can you check out our Performance Issues wiki page to help us nail it down? https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by DmitryAndreyeff** [comment] 2017-11-06 20:19
Insiders build is not better unfortunately. I launched it with --prof-startup flag, attaching created files.

[d789_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1447655/d789_renderer.cpuprofile.txt)
[d789_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1447656/d789_main.cpuprofile.txt)

**Comment by roblourens** [comment] 2017-11-06 20:51
The slow part of the renderer process is clearly the spawn calls, which each take many seconds. The same problem would explain the debug adapter slowness.

This is described in https://github.com/Microsoft/vscode/issues/24884. Do you have any antivirus software running?

**Comment by DmitryAndreyeff** [comment] 2017-11-07 13:26
Yes I have Symantec Endpoint Protection. I cannot shut it down but I can add exceptions. Tried to add code.exe to exceptions but it did not help.

**Comment by roblourens** [comment] 2017-11-07 23:04
You could try adding an exception for the folder that you're opening. I've also worked around this in the past by adding an exception for the entire C:/ drive :)

**Comment by DmitryAndreyeff** [comment] 2017-11-08 19:12
Tried exceptions, no luck. Very frustrating. Even on a virtual machine VSCode is lightning fast compared to my work laptop. Other IDEs work well.
Thank you Rob for your assistance so far!

**Comment by roblourens** [comment] 2017-11-08 21:23
Sorry, I don't have any other suggestions. If you can't disable AV, maybe there are other options in Symantec. Or maybe you can report the issue to them somehow. I'll close this as a dupe of #24884, let's continue there.

**Closed by roblourens** 2017-11-08 21:23 UTC
Labels: debug, needs more info
