### ISSUE TITLE
ActionBar icons are not accessible when zoomed in

### ISSUE THREAD

**Issue by burkeholland** [Microsoft/vscode#71804] opened 2019-04-05 15:22 UTC
Issue Type: <b>Bug</b>

It seems that the behaviour of the ActionBar changed in the March 2019 release. It used to show an elipsis when you are zoomed in too far and it can't show all of the icons in the ActionBar. Now those icons are there, but you can't get to them unless you zoom out.

![image](https://user-images.githubusercontent.com/686963/55638405-b417b000-578c-11e9-8576-4113126823c3.png)

This makes it tough for doing screencasts because you need to the whole UI to be zoomed, not just the font. 

Am I missing something? Perhaps this behaviour by design and I just don't understand how to use it since the change.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_1827262|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.6.0
react-pure-to-class-vscode|ang|1.1.8
ng-template|Ang|0.1.11
vscode-browser-preview|auc|0.4.0
simple-react-snippets|bur|1.2.2
simple-timer|bur|1.0.1
vscode-exports-autocomplete|cap|0.5.4
toggle-format-on-save|cbr|0.2.0
path-intellisense|chr|1.4.2
codestream|Cod|0.51.0
vscode-svgviewer|css|2.0.0
snippetier|daf|0.1.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
prettier-vscode|esb|1.8.1
vscode-reveal|evi|3.3.2
code-runner|for|0.9.7
vscode-pull-request-github|Git|0.6.0
css2react|got|0.0.6
svgeditor|hen|2.9.0
vscode-power-mode|hoo|2.2.0
copy-markdown-as-html|jer|1.1.0
asciidoctor-vscode|joa|2.4.0
svg|joc|0.1.4
angular-essentials|joh|0.6.0
Angular2|joh|7.0.1
vscode-colorize|joh|0.0.1
vscode-peacock|joh|2.0.1
vspizza|jor|0.0.1
vscode-gist|ken|3.0.3
vscode-gutter-preview|kis|0.18.0
dotenv|mik|1.0.1
ecdc|mit|1.0.5
selected-character-count|mou|0.0.1
vscode-azureappservice|ms-|0.13.0
vscode-azureeventgrid|ms-|0.1.1
vscode-azurefunctions|ms-|0.16.0
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.1
mssql|ms-|1.5.0
azure-account|ms-|0.8.1
azurecli|ms-|0.4.4
csharp|ms-|1.18.0
vscode-typescript-tslint-plugin|ms-|1.0.0
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.18
vsliveshare-audio|ms-|0.1.48
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
svg-font-previewer|nko|1.1.4
vetur|oct|0.18.1
vscode-docker|Pet|0.6.1
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.7.0
polacode|pnp|0.2.2
vscode-yaml|red|0.4.0
sass-indented|rob|1.5.1
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.8
rewrap|stk|1.9.1
quokka-vscode|Wal|1.0.205
JavaScriptSnippets|xab|1.7.2
propertylist|zho|0.0.2

(10 theme extensions excluded)

</details>

**Comment by chrisdias** [comment] 2019-04-06 01:25
Doesn't seem to happen in Insiders.

**Comment by sandy081** [comment] 2019-04-08 08:31
Duplicate of #71585

**Closed by sandy081** 2019-04-08 08:31 UTC
Labels: new release
