### ISSUE TITLE
Test allowed extensions policy

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#235002] opened 2024-12-02 16:39 UTC
Refs: https://github.com/microsoft/vscode/issues/84756

- [x] Win @lszomoru
- [x] Win @chrisdias

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23235002%0A%0A&assignees=sandy081)

---

[Feature Documentation](https://github.com/microsoft/vscode-docs/blob/c78318cd6f3c6953eab911fdb59dc98252e6b8d2/docs/setup/enterprise.md#L21)

Test that Allowed Extensions (`extensions.allowed`) setting can be added as a [group policy on Windows](https://code.visualstudio.com/docs/setup/enterprise#_group-policy-on-windows). 

## Set up policies
- Download the Windows ZIP from the [builds page](https://builds.code.visualstudio.com/builds/insider) to get policies
- Inside you'll find a `policies` folder.  
  - Copy the `policies\VSCodeInsiders.admx` file to `C:\Windows\PolicyDefinitions\`
  - Copy the `policies\en-us\VSCodeInsiders.adml` file to `C:\Windows\PolicyDefinitions\en-us`
- Press `Win R`, type `gpedit.msc` hit Enter
- You'll find the **Allowed Extensions** policy for both levels in `{User,Computer} Configuration/Administrative Templates/Visual Studio Code - Insiders/Extensions`. To set it:
  - Double click it
  - Switch to Enabled
  - In the value text box enter the JSON string value of allowed extensions object. Example text: `{"microsoft": true}`

## Testing
- Open VS Code please make sure the configured extensions are allowed and others are not allowed
- Open Settings Editor and look for `extensions.allowed` setting in the settings editor and make sure 
  - the value is shown as configured above
  - there is no link to edit this setting
  - Modifying the setting in the json file should not have any impact

**Comment by Gijsreyn** [comment] 2024-12-02 17:01
I don't know if this is too soon feedback, but I just tried this in:

![Image](https://github.com/user-attachments/assets/4f38899a-d0ca-4625-8a54-a5a3412703b2)

Unfortunately, it did not work. Might I need the nightly build?

**Comment by sandy081** [comment] 2024-12-02 18:23
Also please note that there is a bug in today's insiders that reading policies from the registry is not working. End-end should be working from tomorrow's build.

**Comment by ntrogh** [comment] 2024-12-02 19:05
Instructions are included in our vnext docs, to be released with 1.96 : https://github.com/microsoft/vscode-docs/blob/5f8d57339f7334ab2e63ad162d538815419c3a9d/docs/setup/enterprise.md?plain=1#L79

> You can control the `extensions.allowed` setting by using device management. Use the `AllowedExtensions` VS Code policy, which overrides the `extensions.allowed` setting. The value of this policy is a JSON string that contains the allowed extensions.

**Closed** 2024-12-04 00:14 UTC
Labels: testplan-item

**Comment by Gijsreyn** [comment] 2024-12-04 03:36
Hi @sandy081 and @isidorn. I know this item is closed, but hopefully I can still leave some feedback here. If you want me to raise another issue, I can.

Perhaps it is good to document the current limitations e.g.:

- The setting does not allow to pin a specific version in the allowed list
- Wildcards cannot be used. For example, when I tried doing something like `*ms-*` or `ms-*` to allow all Microsoft extensions, it did not reflect

A script might also be useful to set the relevant registry key.

```powershell
# Change HKLM: to HKCU: if you want to do it for the user
$registryPath = 'HKLM:\SOFTWARE\Policies\Microsoft\VSCodeInsiders'
$propertyName = 'AllowedExtensions'
$propertyValue = @{'ms-vscode.powershell' = $true }

# Check if the registry key exists
if (-not (Test-Path $registryPath)) {
    # Create the registry key
    New-Item -Path $registryPath -Force
}

# Check if the property exists
if (-not (Get-ItemProperty -Path $registryPath -Name $propertyName -ErrorAction SilentlyContinue)) {
    # Create the property
    New-ItemProperty -Path $registryPath -Name $propertyName -Value ($propertyValue | ConvertTo-Json -Compress) -PropertyType String -Force
} else {
    Write-Output "The property '$propertyName' already exists."
}
```

**Comment by ntrogh** [comment] 2024-12-04 08:03
@Gijsreyn What exactly do you mean by not being able to pin a specific version? You can specify an extension and version to allow only that one (`"dbaeumer.vscode-eslint": ["3.0.0"]`). Or am I misinterpreting your comment?

I'll add a note about not supporting wildcards. BTW, you can use `microsoft` as the publisher ID to allow all Microsoft extensions.

**Comment by Gijsreyn** [comment] 2024-12-04 08:15
@ntrogh You are not misinterpreting it. I should have been testing with an _actual_ version that exist, which I didn't. Apologize, and thanks for providing the example.

Will wait for the awesome documentation to come. Cheers!

**Comment by ntrogh** [comment] 2024-12-04 08:17
Thanks for challenging us. Makes the docs better!

**Comment by rtpub88** [comment] 2024-12-17 10:07
Hi, just want to share that I tried this policy and found that although the extensions set in the group policy are being locked down (i.e. you cannot override the settings set by your administrator), any additional extensions you set in your settings.json will be allowed to install.

**Comment by isidorn** [comment] 2024-12-17 10:20
@rtpub88 thank you. Can you please file a new issue for this with repro steps and ping me @isidorn on the issue 🙏

**Comment by rtpub88** [comment] 2024-12-18 02:06
@isidorn I'll try to describe it since I cannot upload any images here.  :(

**Environment: Windows 10 PCs joined AD**

**Step 1 - Set up a group policy with AllowedExtensions enabled**
Computer Configuration > Administrative Templates > Visual Stuudio Code > Extensions
AllowedExtensions = '{ "ms-vscode.powershell": "stable", "ms-vscode.hexeditor": "stable" }'

**Step 2 - Apply policy to the PC**
Run "gpupdate /force" on the PC and confirmed that the enabled extensions are applied in VS Code

**Step 3 - Edit settings.json**
In the user's settings.json file, add the following section:
_"extensions.allowed": {
    "ms-vscode.PowerShell": true,
    "ms-vscode.hexeditor": [ "1.11.1", "1.11.0" ],
    "redhat": "stable:",
}_

**Step 4 - Search extensions and check status**
Search for "redhat" in VS Code extension UI and in this example setup, all extensions by Red Hat can be installed
