### ISSUE TITLE
WSL is crashing

### ISSUE THREAD

**Issue by okineadev** [microsoft/vscode#198061] opened 2023-11-12 21:00 UTC
Type: <b>Bug</b>

VS Code version: Code - Insiders 1.85.0-insider (2095b6f5a316c998fbfa17586d24f7974e3c8f13, 2023-11-10T14:46:43.072Z)
OS version: Windows_NT x64 10.0.23585
Modes:
Connection to 'WSL: Ubuntu' could not be established  WebSocket close with status code 1006

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (6.19GB free)|
|Process Argv|--crash-reporter-id 75c1e97a-4c7a-4737-b36e-a3d6abf26d86|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu' could not be established  WebSocket close with status code 1006
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30859870
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

vscode when used together with wsl crashes about every 10 minutes with this error:

![Знімок екрана 2023-11-12 224455](https://github.com/microsoft/vscode/assets/81070564/509fcad5-c1a0-4947-96cf-0c8598b1ca4d)

I propose to solve this problem by automatically restarting WSL:

```
wsl --shutdown
wsl
```

**Comment by aeschli** [comment] 2023-11-13 14:52
Can you find out what the cause can be? Maybe WSL is running out of memory?

**Comment by okineadev** [comment] 2023-11-13 17:06
I'll try tweaking my .wslconfig to use less RAM if anything happens - I'll let you know if it works - I'll post how I did it so people who run into a similar problem can fix it

**Comment by aeschli** [comment] 2023-12-06 12:14
Closing the issue for now.

**Closed by aeschli** 2023-12-06 12:14 UTC
