### ISSUE TITLE
Touchpad scroll behaves as arrow keys

### ISSUE THREAD

**Issue by BladeMF** [Microsoft/vscode#38085] opened 2017-11-10 18:22 UTC
- VSCode Version: 1.18.0
- OS Version: Win 10 Enterprise 1709 (16299.19)
- Extensions:
bajdzis.vscode-twig-pack@1.0.0
JuanBlanco.solidity@0.0.31
ms-python.python@0.8.0
PKief.material-icon-theme@2.2.4

Steps to Reproduce:

1. Scroll with two-finger scrolling on the touchpad

Effect: you can see the selected line moving. If scrolling up, the window scrolls when the line reaches the top. It does the same for scrolling down - the active/selected line moves down, reaches the bottom edge end *then* the window scrolls.

Touchpad: ELAN Smart-Pad, Driver Version: 11.4.92.1_X64_WHQL

Reproduces without extensions: Yes

**Comment by BladeMF** [comment] 2017-11-11 15:56
I can confirm that my normal mouse (Logitech) scrolls normally.

**Comment by BladeMF** [comment] 2017-11-11 16:54
Further, if I scroll over Explorer, it still scrolls the code window, not the Explorer. This also differs from the regular mouse.

**Comment by alexandrudima** [comment] 2017-11-13 11:18
Duplicate of #17476

**Closed by alexandrudima** 2017-11-13 11:18 UTC
Labels: editor, editor-core, new release, trackpad/scroll

**Comment by BladeMF** [comment] 2017-11-13 12:31
Reported here:
https://bugs.chromium.org/p/chromium/issues/detail?id=784329&can=2&q=touchpad%20scroll&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

Guys, just to point out that visiting https://microsoft.github.io/monaco-editor/ in Chrome doesn't exhibit the same behavior.
