### ISSUE TITLE
CompletionItemProvider not working when trying to complete on a whitespace when registering multiple in one extension

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#2552] opened 2016-01-29 16:14 UTC
The behavior is very random and not expected but can be reproduced. For example here is my extension.ts:

```typescript
import * as vscode from 'vscode'; 

import { FoobarCompletion } from "./foobar"

export function activate(context: vscode.ExtensionContext) {
	vscode.languages.registerCompletionItemProvider("barfoo", new FoobarCompletion());
	vscode.languages.registerCompletionItemProvider("foobar", new FoobarCompletion());
}
```

FoobarCompletion is just resolving some words (a-z) using a `Thenable<vscode.CompletionItem[]>`

When now trying to auto complete a file which is named `test.foobar` it wont work on whitespaces but `test.barfoo` would work. When switching the completion item providers around then the reverse will happen. Note that this bug only occurs when there is some content in the file already.

foobar.ts for reproducing: https://gist.github.com/WebFreak001/79e5d150cb78c833875d
package.json for reproducing: https://gist.github.com/WebFreak001/073847d7e96dde6567b6

When now using that code and assuming in file test.barfoo and in test.foobar is the following text:

```
banana {
    |
}
```

(`|` = cursor)

When trying to complete now it will only work for the .barfoo file but not for the .foobar file.

**Comment by jrieken** [comment] 2016-01-29 18:05
![jan 29 2016 19 03](https://cloud.githubusercontent.com/assets/1794099/12683720/199c126a-c6bb-11e5-9404-ec21856cc414.gif)

@WebFreak001 Can you give me some additional hints how this happens? I can't reproduce. Can you use the debugger to see if your provider gets hit in one or the other case?

**Comment by WebFreak001** [comment] 2016-01-29 18:47
Its very strange as it only happens when I first try to complete a whitespace. Somehow calling the other auto complete service fixed the first one as seen here: ![](http://i.webfreak.org/F9645C.gif)

I am not sure what causes the issue or if it is already fixed on master but its definetly weird behaviour that only occurs when restarting. Does vscode cache the auto complete results? If so it might cache some earlier result but it bugs because I register multiple in one extension.

**Comment by WebFreak001** [comment] 2016-01-29 19:45
This is actually really blocking when trying to include 2 different language completion providers. However I found out that the triggerCharacters properly call the completion. So why not just let ctrl-space use the same code as triggerCharacters does?

**Comment by jrieken** [comment] 2016-02-01 08:58
>  Does vscode cache the auto complete results? If so it might cache some earlier result but it bugs because I register multiple in one extension.

no caching. trigger character and the keybinding are more or less the same code.

**Comment by jrieken** [comment] 2016-02-03 11:35
closing since this works in the latest version of vs code

**Closed by jrieken** 2016-02-03 11:35 UTC
Labels: needs more info
