### ISSUE TITLE
 Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#53830] opened 2018-07-09 04:20 UTC
Issue Id: <b>facdca22-e2e1-78a3-fb88-4dc2de6dacf0</b><br /><br />*Versions* <br />- 1.25.0<br />*Stack* <br />TypeError: Cannot read property 'then' of undefined<br />[/vs/editor/contrib/codeAction/codeActionWidget.ts#33:24 (show)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionWidget.ts#L33:24 (show))<br />[/vs/editor/contrib/codeAction/codeActionCommands.ts#104:31 (_onCodeActionsEvent)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionCommands.ts#L104:31 (_onCodeActionsEvent))<br />[/vs/editor/contrib/codeAction/codeActionCommands.ts#70:42 (call)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionCommands.ts#L70:42 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/editor/contrib/codeAction/codeActionModel.ts#192:112 (_signalChange)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionModel.ts#L192:112 (_signalChange))<br />[/vs/editor/contrib/codeAction/codeActionModel.ts#105:8 (_createEventAndSignalChange)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionModel.ts#L105:8 (_createEventAndSignalChange))<br />[/vs/editor/contrib/codeAction/codeActionModel.ts#46:14 (trigger)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionModel.ts#L46:14 (trigger))<br />[/vs/editor/contrib/codeAction/codeActionModel.ts#201:33 (trigger)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionModel.ts#L201:33 (trigger))<br />[/vs/editor/contrib/codeAction/codeActionCommands.ts#128:21 (triggerFromEditorSelection)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionCommands.ts#L128:21 (triggerFromEditorSelection))<br />[/vs/editor/contrib/codeAction/codeActionCommands.ts#173:12 (showCodeActionsForEditorSelection)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionCommands.ts#L173:12 (showCodeActionsForEditorSelection))<br />[/vs/editor/contrib/codeAction/codeActionCommands.ts#198:9 (run)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/contrib/codeAction/codeActionCommands.ts#L198:9 (run))<br />[/vs/editor/browser/editorExtensions.ts#186:14 (runEditorCommand)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/browser/editorExtensions.ts#L186:14 (runEditorCommand))<br />[/vs/editor/browser/editorExtensions.ts#134:15 (apply)](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/editor/browser/editorExtensions.ts#L134:15 (apply))<br />[/vs/platform/instantiation/common/instantiationService.ts#57:20](https://github.com/microsoft/vscode/blob/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/platform/instantiation/common/instantiationService.ts#L57:20)<br />    at t.invokeWithinContext (out/vs/workbench/workbench.main<br />

**Comment by mjbvz** [comment] 2018-07-12 23:45
Duplicate of #53831

**Closed by mjbvz** 2018-07-12 23:45 UTC
Labels: editor, editor-contrib, error-telemetry
