### ISSUE TITLE
TS cannot move to an existing file

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#183871] opened 2023-05-30 21:23 UTC
Testing #183683

1. Have a type in a file
2. Have another empty .ts file
3. Move to File > Select existing file
4. Observe the error notification:

```
2023-05-30 14:21:09.233 [trace] <semantic> Response received: getEditsForRefactor (123). Request took 2 ms. Success: false . Message: Error processing request. Debug Failure. Expected isNewFile for (only) new files. {"isNewFile":true,"hasScriptInfo":true}
Error: Debug Failure. Expected isNewFile for (only) new files. {"isNewFile":true,"hasScriptInfo":true}
    at IpcIOSession.mapTextChangeToCodeEdit (/var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182095:13)
    at /var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182087:46
    at Array.map (<anonymous>)
    at IpcIOSession.mapTextChangesToCodeEdits (/var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182087:25)
    at IpcIOSession.getEditsForRefactor (/var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:181967:21)
    at getEditsForRefactor (/var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:180201:43)
    at /var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182326:69
    at IpcIOSession.executeWithRequestId (/var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182318:14)
    at IpcIOSession.executeCommand (/var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182326:29)
    at IpcIOSession.onMessage (/var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182368:51)
    at process.<anonymous> (/var/lib/snapd/snap/code-insiders/1309/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:183948:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by mjbvz** [comment] 2023-05-30 23:10
Seems like a duplicate of https://github.com/microsoft/TypeScript/issues/54285

@connor4312 Can you make sure you test this using the latest typescript nightly build (it should be 5.2.x now)

**Comment by connor4312** [comment] 2023-05-30 23:18
Still fails, but with a different error:

![image](https://github.com/microsoft/vscode/assets/2230985/6f76bdc0-c0a4-4913-8f76-1267758b8fa3)

**Comment by mjbvz** [comment] 2023-05-30 23:27
Opened https://github.com/microsoft/TypeScript/issues/54463 for that. Removing from our milestone until this gets fixed upstream

**Closed by mjbvz** 2023-05-30 23:27 UTC
Labels: bug
