### ISSUE TITLE
VSCode is crashing

### ISSUE THREAD

**Issue by arthurfurtunato** [microsoft/vscode#214491] opened 2024-06-06 17:58 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573)
- OS Version: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Open the terminal
2. Run 
```shell
code .
``` 
3. VSCode Open and close afterward.

**Comment by meganrogge** [comment] 2024-06-06 18:21
I can't repro

**Comment by arthurfurtunato** [comment] 2024-06-06 18:22
It's working now

**Comment by tolgacangoz** [comment] 2024-06-06 18:23
How :D I have the same issue in Ubuntu 24.04.

**Comment by arthurfurtunato** [comment] 2024-06-06 18:23
Really? Now, it's working. I don't know why

**Comment by erickduran-stx** [comment] 2024-06-06 18:29
Same issue, still broken.

**Comment by ikskoder** [comment] 2024-06-06 19:39
> GPU process isn't usable. Goodbye

Same problem on Ubuntu 20.04.6 LTS. AMD GPU

> If I add `--in-process-gpu` flag, it seems to work

For me it does not work as a fix

**Comment by GuySartorelli** [comment] 2024-06-06 22:56
Duplicate of https://github.com/microsoft/vscode/issues/214432

**Comment by deepak1556** [comment] 2024-06-07 02:22
Merging to https://github.com/microsoft/vscode/issues/212494

You can start the application with `--use-angle=swiftshader` as workaround until fix is released.

**Closed by deepak1556** 2024-06-07 02:22 UTC
Labels: new release
