### ISSUE TITLE
How to write a problemMatcher with "background" and no problems?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82624] opened 2019-10-15 17:35 UTC
Trying to solve https://github.com/microsoft/vscode/issues/82621 by adding a problemMatcher with "background" property. But I don't actually want it to match any problems.

If I don't set the "pattern" property I just get

```
Error: the description can't be converted into a problem matcher:
{
    "background": {
        "activeOnStart": false,
        "beginsPattern": "Web UI available at",
        "endsPattern": "sdf"
    }
}
```

which is not a helpful error message. But it seems like I have to add an empty problemMatcher pattern like this

```
"pattern": {
	"regexp": ""
},
```

**Comment by roblourens** [comment] 2019-10-15 17:39
Also, I have to full in a dummy endsPattern, when there is no end output from the task, how can I get rid of that?

**Comment by alexr00** [comment] 2019-10-16 09:23
Error messages are unhelpful is a duplicate of https://github.com/microsoft/vscode/issues/29951

Having a better solution than a problem matcher for tracking background tasks is a duplicate of https://github.com/microsoft/vscode/issues/6209

**Closed by alexr00** 2019-10-16 09:23 UTC
