### ISSUE TITLE
[Feature] Auto-enable extensions per session

### ISSUE THREAD

**Issue by lonix1** [Microsoft/vscode#72255] opened 2019-04-13 11:09 UTC
We develop apps in node, asp.net, and python. We have extensions for each platform, so my vscode has almost 50 extensions, and some conflict with each other.

Switching between projects is challenging, as I need to disable/enable various extensions.

It would be nice to have something similar to [`.vscode/extensions.json`](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions), but it enables specific extensions for that workspace. Let's call it `.vscode/session.json` for example.

So by default all the extensions would be installed, but not enabled. When I'd open a workspace with a `.vscode/session.json`, the extensions in that file would be automatically enabled, *for that session only*.

Maybe we could reuse `.vscode/extensions.json` like this:

````json
"recommendations": [
  "ms-vscode.vscode-typescript-tslint-plugin",
  "dbaeumer.vscode-eslint",
  "msjsdiag.debugger-for-chrome"
],
"enableForSession": [
  "foo",
  "bar",
  "baz"
]
````

**Comment by ArulDhandapani** [comment] 2019-04-15 08:22
I also recommend feature request, but ".code-workspace" workspace configurations in vscode would be best place for this.

**Comment by ArulDhandapani** [comment] 2019-04-15 08:27
Also, I saw few other configurations conflict issues when multiple developers working in a project(_By setup their own preference causing project quality_). If we able to list out required plugins in a workspace configuration(.code-workspace) for auto-installation would be grateful. If it's implemented then each project controlled by it's own .code-workspace configurations file to install required plugins and it's configurations apply to it's project.

**Comment by lonix1** [comment] 2019-04-15 09:18
@ArulDhapani If you like the feature request, please upvote it. I think that's how the vscode team prioritizes new features.

**Comment by whut** [comment] 2019-04-18 07:48
Is it dupe of #61723?

**Comment by lonix1** [comment] 2019-04-18 08:43
@whut This issue is simpler and to the point. That other issue is too complicated, and that's a guarantee it'll never be implemented. It needs to be automatic, without extra commands.

**Comment by sandy081** [comment] 2019-04-25 09:13
Duplicate of https://github.com/Microsoft/vscode/issues/40239

**Closed by sandy081** 2019-04-25 09:13 UTC
Labels: extensions
