### ISSUE TITLE
Active icon indicator in the side bar doesn't show well on all monitors

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#100309] opened 2020-06-16 17:02 UTC
Issue Type: <b>Bug</b>

The active icon indicator, a very thin vertical line on the outer side of the main window, doesn't show well on some monitors where the few edge pixels appear dimmed (or color shifted). For example, on my Dell U3415W the indicator pretty much vanishes when viewed from a the center of the monitor (normal usage)

![image](https://user-images.githubusercontent.com/13824553/84804905-45e99280-afb8-11ea-815b-a52b25a86729.png)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by misolori** [comment] 2020-06-16 17:51
I think this might be a monitor issue in general and I don't believe there is much we can do here. In your screenshot it looks like your monitor is cutting off a pixel around the edge. Below is what it looks like on my monitor:

![image](https://user-images.githubusercontent.com/35271042/84809275-af6c9f80-afbe-11ea-9bee-e2810dea588e.png)

>  the indicator pretty much vanishes **when viewed from a the center of the monitor** (normal usage)

Can you clarify this point? What do you mean by "when viewed from a the center of the monitor"?

**Comment by tlemo** [comment] 2020-06-16 18:18
> Below is what it looks like on my monitor:

Correct, that's how it looks when the window is not maximized. Can you try maximizing the VS Code window? I forgot to mention that this appears to be a regression (I don't remember this being a noticeable problem in older versions) 

> Can you clarify this point? What do you mean by "when viewed from a the center of the monitor"?

Sorry - what I meant is sitting centered to the monitor. For extra wide monitors, this means that the view angle for the vertical monitor edges is fairly sharp.

**Comment by IllusionMH** [comment] 2020-06-16 18:28
Might be side effect of #85310 which noticeable for maximized windows.

Do you see same width if you restore window (from maximized to small window) and move it's side near to the edge of the screen?

**Comment by tlemo** [comment] 2020-06-16 18:31
@IllusionMH : it could very well be related to #85310. The monitor issue I described just compounds to the window decoration issue and makes it more obvious.

One additional data point in case it helps: I checked and the indicator "trimming" when the window is maximized happens on both Windows and Linux.

**Comment by misolori** [comment] 2020-06-16 18:33
@tlemo my screenshot is for when it is maximized, but there is no difference for me.

**Comment by misolori** [comment] 2020-06-16 18:35
It appears then that this is indeed a duplicate of #85310, thanks @IllusionMH. Will close this issue, thanks for the update.

**Comment by IllusionMH** [comment] 2020-06-16 18:37
Checked one more thing: event if there is no 1px visible on next monitor border still might look cropped as with #85310.
However it has proper visual width if I set `"window.titleBarStyle": "native"`

`"window.titleBarStyle": "custom"`
![image](https://user-images.githubusercontent.com/1312662/84813936-6269e700-b019-11ea-8914-76f8746bf441.png)
`"window.titleBarStyle": "native"`
![image](https://user-images.githubusercontent.com/1312662/84813964-6dbd1280-b019-11ea-92da-0e89cc481d88.png)

@misolori do you have 2 monitors?

**Comment by tlemo** [comment] 2020-06-16 18:37
@misolori : the issue only happens if the "Title bar style" setting is set to "custom". 

While similar, this may be a different issue than #85310:
1. This issue seems to be a more recent regression
2. It reproduces consistently if the title bar style is set to "custom"

**Comment by misolori** [comment] 2020-06-16 18:41
I have a single monitor and couldn't reproduce, and on Windows the custom titlebar is enabled by default (for me it's enabled), so this doesn't appear to happen in 2 & 3.

@tlemo do you have two monitors?

**Comment by tlemo** [comment] 2020-06-16 18:52
> @tlemo do you have two monitors?
No, single monitor.

One small correction: I can only reproduce this on Windows (with custom title bar style). It doesn't reproduce on Ubuntu 20.04.

**Comment by IllusionMH** [comment] 2020-06-16 18:58
I was able to also reproduce this problem in single screen (Surface Pro 3)

Maybe this observation is somehow related https://github.com/microsoft/vscode/issues/90466#issuecomment-584927230 
My (wild) guess is that this issue and #85310 still has same underlying reason - incorrect calculations of chromeless window dimensions.

Maybe @deepak1556 has more info to weight in if they are related.

**Comment by tlemo** [comment] 2020-06-16 19:03
Thanks @IllusionMH & @misolori for looking into this!

**Comment by deepak1556** [comment] 2020-06-25 06:04
Thanks @IllusionMH 

yes the root issue is same, but I will keep this issue open because of the behavior difference.

**Comment by deepak1556** [comment] 2020-11-05 10:12
Should be fixed with latest insiders and upcoming stable release.

**Closed by deepak1556** 2020-11-05 10:12 UTC
Labels: electron, titlebar, windows
