### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by zhoocoo** [microsoft/vscode#106624] opened 2020-09-14 06:15 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200913

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:13450:55)
    at getTextOfNode (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:13475:16)
    at Object.declarationNameToString (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:13787:66)
    at getDisplayName (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:39842:53)
    at declareSymbol (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:39956:111)
    at bindExportsPropertyAssignment (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:42066:17)
    at bindWorker (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41762:29)
    at bind (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41651:13)
    at bindExpressionStatement (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40716:13)
    at bindChildren (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40201:21)
    at bind (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40142:94
    at Object.forEach (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40149:16)
    at bindEachFunctionsFirst (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40142:13)
    at bindChildren (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40241:21)
    at bindContainer (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40099:17)
    at bind (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41665:21)
    at bindSourceFile (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:39708:17)
    at Object.bindSourceFile (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:39647:9)
    at initializeTypeChecker (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:77643:20)
    at Object.createTypeChecker (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:43696:9)
    at Object.getTypeChecker (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:104892:79)
    at synchronizeHostData (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:145287:21)
    at Proxy.getProgram (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:145369:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:150226:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:150159:42)
    at ConfiguredProject.updateGraph (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:151093:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:152797:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:153695:44)
    at c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:154018:97
    at Object.flatMap (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:154018:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:155037:46)
    at c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:156910:88
    at IOSession.Session.executeWithRequestId (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:156901:28)
    at IOSession.Session.executeCommand (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:156910:33)
    at IOSession.Session.onMessage (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:156934:35)
    at Interface.<anonymous> (c:\Users\zhaocongcong\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:159150:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.37GB free)|
|Process Argv|--crash-reporter-id eacbd511-c2b7-44e7-9f89-0adcbe2f2c1e|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
typescript|Ais|0.0.1
bat-snippets|bat|0.2.0
shell|bbe|0.3.0
link-with-leetcode|bla|0.7.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
emoji-badges-vscode|cly|1.0.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
javascript-ejs-support|Dig|1.3.1
vscode-generate-getter-setter|DSK|0.5.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.6.0
code-runner|for|0.11.0
shell-format|fox|7.0.1
vue-snippets|hol|0.1.12
path-autocomplete|ion|1.15.0
vue|jcb|0.1.5
ejs-eval|kev|1.0.1
graphql-for-vscode|kum|1.15.3
vscode-leetcode|Lee|0.17.0
restructuredtext|lex|129.0.0
jsdoc|lll|1.0.3
marp-vscode|mar|0.15.0
git-graph|mhu|1.26.0
dotenv|mik|1.0.1
HTMLHint|mka|0.8.0
vscode-filesize|mkx|2.1.4
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.5.0
vscode-language-pack-zh-hans|MS-|1.49.1
python|ms-|2020.8.108011
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|4.1.20200913
vscode-typescript-tslint-plugin|ms-|1.2.3
node-modules-resolve|nau|1.0.2
elmmet|nec|1.0.1
vetur|oct|0.27.3
vue-beautify|pea|2.0.4
material-icon-theme|PKi|4.3.0
tsimporter|pmn|2.0.1
vscode-graphql|Pri|0.3.2
tslint-vue|pro|1.5.6
ejs-language-support|Qas|0.0.1
typescript-hero|rbb|3.0.0
project-snippets|reb|0.5.0
shellman|Rem|4.7.0
partial-diff|ryu|1.4.1
preview-vscode|sea|2.1.0
file-tree-generator|Shi|1.1.1
vs-picgo|Spa|2.1.0
addDocComments|ste|0.0.8
move-ts|str|1.12.0
sass-indented|syl|1.8.11
language-stylus|sys|1.11.0
ejs-snippets|Tao|0.1.0
open-in-browser|tec|2.0.0
shellcheck|tim|0.10.1
hosts|tom|1.1.1
shell-launcher|Tyr|0.4.1
gitflow|vec|1.2.1
highlight-matching-tag|vin|0.9.9
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.3.0
project-tree|zhu|0.3.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-09-14 18:19
Duplicate of https://github.com/microsoft/TypeScript/issues/40513

**Closed by mjbvz** 2020-09-14 18:19 UTC
Labels: new release
