### ISSUE TITLE
Different results when search for  .*

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9908] opened 2016-07-28 15:11 UTC
search for `.*` in _both_ the editor and the search viewlet. The search viewlet produces different (and weird) results

![screen shot 2016-07-28 at 17 10 01](https://cloud.githubusercontent.com/assets/1794099/17217913/4ff16d42-54e6-11e6-8403-1c5ae1eb8b25.png)

**Comment by jrieken** [comment] 2016-07-28 15:11
related https://github.com/Microsoft/vscode/issues/6053

**Comment by sandy081** [comment] 2016-08-03 13:44
@jrieken I get a validation error for `.*` expression in Search viewlet. May I know if you followed specific steps to reproduce it?

![screen shot 2016-08-03 at 3 44 38 pm](https://cloud.githubusercontent.com/assets/10746682/17367669/34a34e98-5991-11e6-9615-d24047b8ac03.png)

**Comment by jrieken** [comment] 2016-08-03 14:17
Yeah - that's what I would have expected in the first place and I was surprised that I got further... I stumbled over this cos I see the editor now support searches like that I and believe the workbench should catch up

**Comment by sandy081** [comment] 2016-09-07 16:04
I do not think supporting such a greedy expression in Search is a good idea. I also think it does not makes sense in Editor but leaving it as is since it is not harming.

 I am not able to reproduce this in Search and hence closing this. Please reopen this if there is a way to reproduce the weird state in search.

**Closed by sandy081** 2016-09-07 16:04 UTC
Labels: bug, search
