### ISSUE TITLE
Crash with error code 132 - JS out of memory

### ISSUE THREAD

**Issue by br0kenpixel** [microsoft/vscode#227373] opened 2024-09-02 12:07 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.92.2`, `fee1edb8d6d72a0ddff41e5f71a671c23ed924b9`, `x64`
- OS Version: `Fedora 40 (KDE) using 6.9.12-200.fc40.x86_64 kernel`

Steps to Reproduce:

1. Open VSCode
2. Observe crash

```
$ code --disable-extensions --verbose
[96237:0902/134853.638897:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
<--- Last few GCs --->

[96237:0x36bc00100000]      334 ms: Mark-Compact (reduce) 6.4 (16.0) -> 6.4 (8.2) MB, pooled: 0 MB, 67.02 / 0.00 ms  (average mu = 0.003, current mu = 0.001) last resort; GC in old space requested
[96237:0x36bc00100000]      338 ms: Mark-Compact (reduce) 6.4 (8.2) -> 6.4 (8.2) MB, pooled: 0 MB, 3.86 / 0.00 ms  (average mu = 0.003, current mu = 0.003) last resort; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
----- Native stack trace -----
[0902/134853.813563:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0902/134853.813641:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0902/134853.820566:ERROR:directory_reader_posix.cc(43)] opendir /home/br0kenpixel/.config/Code/Crashpad/attachments/1af0ef5c-fe03-4afe-beff-b033d6b4b175: No such file or directory (2)
```

Repeating the same command gives me something more verbose:
```
[96657:0902/135332.675408:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[main 2024-09-02T11:53:33.006Z] [File Watcher (node.js)] Request to start watching: /home/br0kenpixel/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/br0kenpixel/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-09-02T11:53:33.021Z] Starting VS Code
[main 2024-09-02T11:53:33.021Z] from: /usr/share/code/resources/app
[main 2024-09-02T11:53:33.022Z] args: {
  _: [],
  diff: false,
  merge: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  'update-extensions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-lcd-text': false,
  'disable-gpu': false,
  'disable-chromium-sandbox': false,
  sandbox: false,
  telemetry: false,
  debugRenderer: false,
  'enable-smoke-test-driver': false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'use-inmemory-secretstorage': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'f23bc059-693b-420c-bcf6-09933fe13298',
  'skip-add-to-recently-opened': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'preserve-env': false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  'disable-gpu-sandbox': false,
  '__enable-file-policy': false,
  'enable-coi': false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  'profile-temp': false,
  logsPath: '/home/br0kenpixel/.config/Code/logs/20240902T135332'
}
[main 2024-09-02T11:53:33.023Z] Resolving machine identifier...
[main 2024-09-02T11:53:33.023Z] Resolved machine identifier: 5c2bcf2b107a455d2246ef01840978865d86b37f2ea0ee9c40581a4c15001262
[main 2024-09-02T11:53:33.023Z] Main->SharedProcess#connect
[main 2024-09-02T11:53:33.028Z] [File Watcher (node.js)] Started watching: '/home/br0kenpixel/.config/Code/User'
[main 2024-09-02T11:53:33.029Z] StorageMainService: creating application storage
[main 2024-09-02T11:53:33.039Z] ElectronURLListener: waiting for window to be ready to handle URLs...
[main 2024-09-02T11:53:33.039Z] lifecycle (main): phase changed (value: 2)
[main 2024-09-02T11:53:33.039Z] windowsManager#open
[main 2024-09-02T11:53:33.040Z] windowsManager#open pathsToOpen [
  {
    backupPath: '/home/br0kenpixel/.config/Code/Backups/1725277079613',
    remoteAuthority: undefined
  }
]
[main 2024-09-02T11:53:33.044Z] windowsManager#doOpenEmpty {
  restore: true,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: true
}
[main 2024-09-02T11:53:33.045Z] IPC Object URL: Registered new channel vscode:db0eab28-146c-40f3-a8d4-0008f3df79d3.
[main 2024-09-02T11:53:33.045Z] window#validateWindowState: validating window state on 1 display(s) { mode: 0, x: 0, y: 28, width: 1708, height: 996 }
[main 2024-09-02T11:53:33.045Z] window#validateWindowState: single monitor working area { x: 0, y: 0, width: 1707, height: 1024 }
[main 2024-09-02T11:53:33.046Z] window#ctor: using window state { mode: 0, x: 0, y: 28, width: 1707, height: 996 }
[main 2024-09-02T11:53:33.119Z] window#load: attempt to load window (id: 1)
[96718:0902/135333.124833:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[main 2024-09-02T11:53:33.129Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2024-09-02T11:53:33.129Z] lifecycle (main): phase changed (value: 3)
[main 2024-09-02T11:53:33.129Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2024-09-02T11:53:33.129Z] update#setState idle
[main 2024-09-02T11:53:33.146Z] [File Watcher (node.js)] Started watching: '/home/br0kenpixel/.config/Code/User/settings.json'
[96692:0902/135334.590971:WARNING:sandbox_linux.cc(420)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2024-09-02T11:53:34.624Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
<--- Last few GCs --->

[1:0x312000578000]     1712 ms: Mark-Compact (reduce) 1.8 (6.4) -> 1.8 (3.4) MB, pooled: 0 MB, 1.04 / 0.00 ms  (average mu = 0.028, current mu = 0.023) last resort; GC in old space requested
[1:0x312000578000]     1713 ms: Mark-Compact (reduce) 1.8 (3.4) -> 1.8 (3.4) MB, pooled: 0 MB, 0.91 / 0.00 ms  (average mu = 0.021, current mu = 0.013) last resort; GC in old space requested


<--- JS stacktrace --->
[96718:0902/135334.840351:ERROR:v8_initializer.cc(811)] V8 javascript OOM (CALL_AND_RETRY_LAST).
[0902/135334.848224:ERROR:directory_reader_posix.cc(43)] opendir /home/br0kenpixel/.config/Code/Crashpad/attachments/9046ad83-0c8f-4b39-85b8-cb8b4544791d: No such file or directory (2)
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[main 2024-09-02T11:53:35.227Z] CodeWindow: renderer process gone (reason: crashed, code: 132)
[main 2024-09-02T11:53:35.632Z] lifecycle (main): phase changed (value: 4)
[96657:0902/135337.677380:ERROR:browser_main_loop.cc(280)] GLib-GObject: ../gobject/gsignal.c:2685: instance '0x13b400e4c3c0' has no handler with id '3746'
[main 2024-09-02T11:53:37.681Z] IPC Object URL: Removed channel vscode:db0eab28-146c-40f3-a8d4-0008f3df79d3.
[main 2024-09-02T11:53:37.682Z] Lifecycle#window.on('closed') - window ID 1
[main 2024-09-02T11:53:37.682Z] Lifecycle#onWillShutdown.fire()
[main 2024-09-02T11:53:37.738Z] Lifecycle#onWillShutdown - begin 'instanceLockfile'
[main 2024-09-02T11:53:37.739Z] storageMainService#onWillShutdown()
[main 2024-09-02T11:53:37.739Z] Lifecycle#onWillShutdown - begin 'applicationStorage'
[main 2024-09-02T11:53:37.739Z] Lifecycle#onWillShutdown - begin 'extHostStarter'
[main 2024-09-02T11:53:37.739Z] Lifecycle#app.on(window-all-closed)
[main 2024-09-02T11:53:37.739Z] Lifecycle#app.on(before-quit)
[main 2024-09-02T11:53:37.739Z] Lifecycle#onBeforeShutdown.fire()
[main 2024-09-02T11:53:37.740Z] [WindowsStateHandler] onBeforeShutdown {
  lastActiveWindow: undefined,
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}
[main 2024-09-02T11:53:37.740Z] Lifecycle#app.on(will-quit) - begin
[main 2024-09-02T11:53:37.740Z] Lifecycle#onWillShutdown - end 'extHostStarter'
[main 2024-09-02T11:53:37.740Z] Lifecycle#onWillShutdown - end 'instanceLockfile'
[main 2024-09-02T11:53:37.742Z] [File Watcher (node.js)] Request to stop watching: /home/br0kenpixel/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/br0kenpixel/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-09-02T11:53:37.742Z] [File Watcher (node.js)] stopping file watcher (/home/br0kenpixel/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>))
[main 2024-09-02T11:53:37.745Z] [File Watcher (node.js)] stopping file watcher (/home/br0kenpixel/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>))
[main 2024-09-02T11:53:37.746Z] StorageMainService: closed application storage
[main 2024-09-02T11:53:37.746Z] Lifecycle#onWillShutdown - end 'applicationStorage'
[main 2024-09-02T11:53:37.765Z] Lifecycle#app.on(will-quit) - after fireOnWillShutdown
[main 2024-09-02T11:53:37.765Z] Lifecycle#app.on(will-quit) - calling app.quit()
```

Running the same command for the 3rd time, makes VSCode run just fine.

## Related to
This issue may be related to or duplicate of:
-  #190560

## Possible causes
AMD iGPU drivers could be the cause. I noticed that these crashes are more likely to happen after my laptop was woken up from sleep.

**Comment by tamuratak** [comment] 2024-09-02 13:22
It might be duplicate of #221886 or #224673. See https://github.com/microsoft/vscode/issues/224673#issuecomment-2302332588

**Comment by br0kenpixel** [comment] 2024-09-02 13:44
I don't think it's related to SELinux, as I couldn't find any denial logs in `dmesg`, nor `journalctl`. As for the `6.10.6-200.fc40` kernel, I already have it installed, but unfortunately I can't use it reliably. It causes my system to occasionally crash due to some issue with the AMD iGPU driver.

**Comment by deepak1556** [comment] 2024-12-12 09:43
If the issue still persists with latest stable, can you follow the steps before to capture a heap profile,

* From a fresh instance, run `Developer: Toggle Developer Tools`
* Switch to the `Memory` tab and select the option as shown in the screenshot below
 ![Image](https://github.com/user-attachments/assets/a0a32e6c-c350-4890-81e3-2c29a8513f75)
* Start the recording, repeat the steps that repro the crash
* Save the profile and attach it to this issue

**Closed** 2024-12-19 11:27 UTC
Labels: info-needed
