### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by mwblock9** [microsoft/vscode#122660] opened 2021-04-29 13:33 UTC
Issue Type: <b>Bug</b>

Start VS Code Insiders and wait. Currently when I launch the latest version VS Code with no extensions enabled, VS Code Insiders constantly tries to initialize JS/TS language features. Eventually, VS Code Insiders will report that the initialization failed 5 times. That has lead to this report. This started happening within the past week.

VS Code version: Code - Insiders 1.56.0-insider (0123d26aaa393bccf99f31f1eac07df6c9e218ce, 2021-04-29T05:14:58.987Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.32GB free)|
|Process Argv|--crash-reporter-id 59a55d33-1727-4148-8270-00c2d59d183f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|6.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry914:30244316
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255cf:30295351
vscgsv2:30286872

```

</details>

**Comment by mwblock9** [comment] 2021-04-29 15:05
I believe I was able to resolve this issue myself via performing `lerna clean` followed by `npm ci`.

**Comment by mjbvz** [comment] 2021-04-29 18:56
If you are still seeing this, please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment] 2021-05-06 22:58
Closing since we need more info to investigate this

**Closed by mjbvz** 2021-05-06 22:58 UTC
Labels: needs more info
