### ISSUE TITLE
Add progress indicator for the "configure or fix launch.json" gear button

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44874] opened 2018-03-01 22:23 UTC
Issue Type: <b>Bug</b>

**Steps to Reproduce:**

1. In a project with no `launch.json`
1. In debug panel
2. Click on the debug gear for `configure or fix launch.json`

**Bug**
Notice a several second delay before `select environment` is shown. There is no indication that work is being done in the background during this delay

Only happens first time

VS Code version: Code - Insiders 1.21.0-insider (9a04587cc6b42c332609a08bfd7e2dbeac592c21, 2018-03-01T06:39:57.509Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details>
Reproduces only with extensions

**Comment by weinand** [comment] 2018-03-01 22:27
What (debugger) extensions do you have installed?
If any, does it help if you disable the debuggers?

**Comment by mjbvz** [comment] 2018-03-01 23:19
@weinand Possibly caused by the docker extension. I went through one-by-one disabling extensions. After disabling docker, the gear button again has an immediate effect

**Comment by weinand** [comment] 2018-03-01 23:21
Great, that helps us a lot!

**Comment by isidorn** [comment] 2018-06-07 15:27
Duplicate of https://github.com/Microsoft/vscode/issues/37929

**Closed by isidorn** 2018-06-07 15:27 UTC
Labels: bug, debug
