### ISSUE TITLE
Allow variables to be displayed in a different base during debugging

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#17668] opened 2016-12-21 12:37 UTC
Integer variables are always displayed in decimal format in Locals, Watches and on hover.

It would be nice to have a context menu option to allow the values to be displayed in binary, octal or hexadecimal format, perhaps with a "debug.displayBase" option for a default configuration value.

**Comment by egamma** [comment] 2016-12-21 14:36
fyi @weinand

**Comment by weinand** [comment] 2017-11-10 10:32
duplicate of #28025

**Closed by weinand** 2017-11-10 10:32 UTC
Labels: debug, feature-request
