### ISSUE TITLE
lagging when using windows precision touchpad!

### ISSUE THREAD

**Issue by Khalilsqu** [Microsoft/vscode#49303] opened 2018-05-06 11:15 UTC
I know this has been mentioned many times around and all related issues were closed and locked for developers limited discussion. I would like to know how far the discussion has gone in resolving the issue since I am right now as of 6th of May 2018 using the latest update of VSC yet the lagging is dragging me crazy. It is annoying to the point that you almost cannot use VSC in windows laptop machine yet VSC is a Microsoft product.

I am aware that this issue is duplicate. I searched almost all of them but none giving a solution to the issue. I just would like you to give me please a time-frame when it could be resolved. Meanwhile I might use another alternative.

**Comment by bpasero** [comment] 2018-05-07 04:12
Duplicate of https://github.com/Microsoft/vscode/issues/13612

**Closed by bpasero** 2018-05-07 04:12 UTC
