### ISSUE TITLE
Compatibility with Wacom Input Device

### ISSUE THREAD

**Issue by JSungMin** [Microsoft/vscode#65856] opened 2018-12-31 11:11 UTC
Issue Type: <b>Bug</b>

visual studio code editing function get broken when i work with my wacom device (CTL-490)...

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.31GB free)|
|Process Argv|C:\Users\SungMin\Documents\sodom -r -g C:\Users\SungMin\Documents\sodom\Assets\Scripts\GameObjects\Actors\Enemy\Boss\Hund\Hund.cs:1|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
unity-tools|Tob|1.0.5
unity-debug|Uni|2.6.6
unity-snippets|Ycl|0.1.2

</details>

**Comment by egamma** [comment] 2018-12-31 15:16
Given the minimal information this looks like a duplicate of https://github.com/Microsoft/vscode/issues/39801

**Closed** 2018-12-31 15:16 UTC
Labels: *duplicate
