### ISSUE TITLE
New blue icon not visible pinned to taskbar with default win7 background

### ISSUE THREAD

**Issue by martinwilkerson-scisys** [Microsoft/vscode#38079] opened 2017-11-10 16:56 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
VS-code-vagrantfile|mar|0.0.7
azure-account|ms-|0.2.0
vscode-docker|Pet|0.0.21
plsql-language|xyz|1.1.1

Steps to Reproduce:

1. Install the October release of VS Code on Windows 7
2. Pin VS Code to the taskbar
3. Set the default blue + logo desktop background
4. Enable Win 7 visual styles (i.e. transparent taskbar)

Expected behaviour:

Able to see the icon

Actual behaviour:

Icon is nearly the same colour as the taskbar so is not visible. See attached screenshot.
![vs-code-icon-not-visible](https://user-images.githubusercontent.com/22169186/32669292-ee0e7fba-c637-11e7-8991-50b9dd21b42b.png)

Reproduces without extensions: Yes

**Comment by DanAtkinson** [comment] 2017-11-10 21:31
I think this might be a dupe of #37958.

**Closed** 2017-11-11 08:22 UTC
Labels: icon, new release, windows

**Comment by martinwilkerson-scisys** [comment] 2017-11-13 09:29
Agreed, sorry I didn't see that one when searching for existing issues. I'll add my screenshot to that issue.
