### ISSUE TITLE
An option to copy the error message

### ISSUE THREAD

**Issue by Prottoy2938** [microsoft/vscode#105386] opened 2020-08-26 06:10 UTC
VS Code often shows an error  by creating a curly border on the bottom of the error code and when we hover on that line it shows us the error message.

 And most of the time if the error is new to me, I just copy the error message on search it on Google. If this happens to everyone, then it would be a useful feature to have a copy option to copy the error message. Like this:

![Tux, the Linux mascot](https://i.ibb.co/CPhBtpc/copy-button-description.jpg)

**Comment by RMacfarlane** [comment] 2020-08-26 16:30
Closing as a duplicate of https://github.com/Microsoft/vscode/issues/63296

**Closed by RMacfarlane** 2020-08-26 16:30 UTC
