### ISSUE TITLE
Repeated characters inserted in editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#53483] opened 2018-07-03 10:05 UTC
Create the following `file.py`:

```py
name = f"joao {dsaname}"
ddd
modifieddsadsadsa a long long long modifieddsadsadsa a long long long modifieddsadsadsa a long long long 
dsanamedass
dsasdaadss

dsaa
```

Close the file, open the file again, move the cursor to the end of line 2 and type `d`.

![issue](https://user-images.githubusercontent.com/22350/42213559-690bccce-7eb9-11e8-99b9-09c766bf6d19.gif)

**Comment by alexandrudima** [comment] 2018-07-03 10:07
Duplicate of #49480

**Closed by alexandrudima** 2018-07-03 10:07 UTC
Labels: bug, editor
