### ISSUE TITLE
QuickFix list support cycle select

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#139464] opened 2021-12-19 10:37 UTC
For example, in following scene, I just need to press <kbd>↑</kbd> to select the last item.

![image](https://user-images.githubusercontent.com/41773861/146671847-cb672ea0-cc12-4045-a198-a77f9253d55f.png)

**Comment by mjbvz** [comment] 2022-01-03 23:16
Duplicate of #55111 

That is the standard MacOS context menu. VS Code can't change it's behavior

**Closed by mjbvz** 2022-01-03 23:16 UTC
