### ISSUE TITLE
Select all cmd-shift-G does not select all

### ISSUE THREAD

**Issue by dearfrankg** [Microsoft/vscode#36003] opened 2017-10-10 20:51 UTC
- VSCode Version: Version 1.17.1 (1.17.1)
- OS Version: macos sierra 10.12.6 (16G29)

Steps to Reproduce:

1. Create a file with 10k sql insert statements --> 

INSERT INTO tabel (one, two, three) 
   VALUES 
   (1, 'value2', 3, 4),
   (1, 'value2', 3, 4),
    ... // 10k lines
   (1, 'value2', 3, 4);

2. Highlight the open paren and select all with cmd-shift-G

Scroll down and notice that only 2k are selected and 8k are not.

Reproduces without extensions: Yes/No

Don't know

**Comment by alexandrudima** [comment] 2017-10-21 09:08
Duplicate of #5887

**Closed by alexandrudima** 2017-10-21 09:08 UTC
Labels: editor
