### ISSUE TITLE
 Illegal value for lineNumber

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#97461] opened 2020-05-11 06:08 UTC
Issue Id: <b>2060dfc7-0c8e-d13e-5ec8-dfa1d09a5db0</b><br /><br />*Versions* <br />- 1.45.0<br />*Stack* <br />Error: Illegal value for lineNumber<br />[/vs/editor/common/model/textModel.ts#820:9 (getLineMaxColumn)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/model/textModel.ts#L820:9 (getLineMaxColumn))<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#1067:15 (getViewLineMaxColumn)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/viewModel/splitLinesCollection.ts#L1067:15 (getViewLineMaxColumn))<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#779:31 (getViewLineMaxColumn)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/viewModel/splitLinesCollection.ts#L779:31 (getViewLineMaxColumn))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#572:20 (getLineMaxColumn)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/viewModel/viewModelImpl.ts#L572:20 (getLineMaxColumn))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#475:27 (getCompletelyVisibleViewRange)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/viewModel/viewModelImpl.ts#L475:27 (getCompletelyVisibleViewRange))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#420:32 (getVisibleRanges)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/viewModel/viewModelImpl.ts#L420:32 (getVisibleRanges))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#460:35 (getVisibleRanges)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/browser/widget/codeEditorWidget.ts#L460:35 (getVisibleRanges))<br />[/vs/workbench/api/browser/mainThreadEditor.ts#86:21 (_readVisibleRangesFromCodeEditor)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/api/browser/mainThreadEditor.ts#L86:21 (_readVisibleRangesFromCodeEditor))<br />[/vs/workbench/api/browser/mainThreadEditor.ts#31:55 (readFromEditor)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/api/browser/mainThreadEditor.ts#L31:55 (readFromEditor))<br />[/vs/workbench/api/browser/mainThreadEditor.ts#203:34 (_updatePropertiesNow)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/api/browser/mainThreadEditor.ts#L203:34 (_updatePropertiesNow))<br />[/vs/workbench/api/browser/mainThreadEditor.ts#260:9](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/api/browser/mainThreadEditor.ts#L260:9)<br />    at e.fire (out/vs/workbench/<br />

**Comment by alexdima** [comment] 2020-05-25 10:15
Duplicate of #97447

**Closed by alexdima** 2020-05-25 10:15 UTC
Labels: error-telemetry
