### ISSUE TITLE
Menubar menus and other lists flash white on Linux before rendering

### ISSUE THREAD

**Issue by louhy** [microsoft/vscode#102878] opened 2020-07-18 20:15 UTC
Issue Type: <b>Bug</b>

On Linux Mint 19.3 XFCE (NVidia 1080 GPU), whenever a menubar item is shown (File, Edit, Selection, View, etc.) the menu "popup" first renders with a bright white background for a split second before rendering the menu. 

This may not sound like a big problem, but this blinding bright white flash makes VS Code unusable for me. It seems like combobox/dropdown selection field popups also have a similar issue, although those don't hurt the eyes as much. 

If the slow rendering glitch can't be fixed easily, making the initial background color darker to match the dark VS Code background would at least make the app usable despite the ugly visual glitch.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.33GB (22.87GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by gjsjohnmurray** [comment] 2020-07-19 03:20
/duplicate of #80798 which gives a workaround as well as a link to the upstream issue.

**Closed** 2020-07-19 03:20 UTC
Labels: *duplicate, new release
