### ISSUE TITLE
Bracket matching erroneously highlights irrelevant brackets in JSX

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/vscode#84537] opened 2019-11-11 23:08 UTC
Issue Type: <b>Bug</b>

The following code causes brackets to be highlighted when they should not be:

```jsx
// Cursor here
const header = (
    <div className="test-group-header">
    </div>
)
```

![image](https://user-images.githubusercontent.com/829827/68628293-00e70600-0495-11ea-947d-a4129a4ab038.png)

I would expect that the brackets were only highlighted when my cursor was within them.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|-psn_0_61455|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
auto-rename-tag|for|0.1.1
change-case|wma|1.0.0

</details>

**Comment by NickHeiner** [comment] 2019-11-11 23:08
I do not believe that any of those are genuine duplicates.

**Comment by 0sdavison** [comment] 2019-11-26 15:04
Possible duplicate of #84281

**Closed** 2019-12-02 20:07 UTC
Labels: bug, editor-bracket-matching
