### ISSUE TITLE
Iussue with editorIndentGuide.activeBackground

### ISSUE THREAD

**Issue by satowine1** [Microsoft/vscode#49622] opened 2018-05-10 14:32 UTC
The editor marks well the indent line guide but, after a certain number of scrolls, when cursor is hidden on the screen, the color of line disappear.
This feature is useful only if i can see the indent guide marked on the bottom of code, away from cursor... Because of this iussue is not very useful, unfortunately...
This is my setting of property:
```
 "workbench.colorCustomizations": {
        "editorIndentGuide.activeBackground": "#90EE90"
    },
```

Screens:
-When cursor is visible on the screen (it is on the top left corner)-
![1](https://user-images.githubusercontent.com/16965844/39874946-8addd28a-546f-11e8-853e-f26a760312b7.PNG)
-When cursor is hidden-
![2](https://user-images.githubusercontent.com/16965844/39874966-9b1723c2-546f-11e8-82e3-ebedc1f8f636.PNG)

- VSCode Version: 1.2.3
- OS Version: Win 10

Steps to Reproduce:

1. Adding editorIndentGuide.activeBackground property to User setting 
2. Adding a color to property

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-05-11 07:41
Duplicate of #49173

**Closed by alexandrudima** 2018-05-11 07:41 UTC
Labels: editor, editor-core
