### ISSUE TITLE
Update notification icon persists after update in latest version of Insiders (1.45.0 4c5185373d5f209cd6c0b5d29a216fb801da34e)

### ISSUE THREAD

**Issue by bergmeister** [microsoft/vscode#95125] opened 2020-04-13 15:10 UTC
```
Version: 1.45.0-insider (user setup)
Commit: 44c5185373d5f209cd6c0b5d29a216fb801da34e
Date: 2020-04-10T18:12:33.780Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. Update to latest version of Code Insiders
2. Observe that after the update the `1` from the Update notification icon does not go away. Clicking 'Check Updates' again confirms that there is no new update.
![image](https://user-images.githubusercontent.com/9250262/79131767-0d9fbb00-7da1-11ea-8c04-72ca4f2f9c0f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-04-13 16:32
/duplicate of #94822

This one is not from update, but from sync feature.

**Closed** 2020-04-13 16:32 UTC
Labels: *duplicate
