### ISSUE TITLE
Highlighting of Select texts either greys out or dissappears upon right-click

### ISSUE THREAD

**Issue by mchassy** [microsoft/vscode#133511] opened 2021-09-21 09:59 UTC
Issue Type: <b>Bug</b>

In some extensions, for example Thunder Client, and in most pages which document extensions, right-click copy paste is not working. Double clicking a word will high-light that word; sometimes with a transparent bright blue, sometimes with a transparent light grey. But when right-clicking on that selection, the high-light either dissappears of become an inverse dark grey background with the letters in black. In either case, nothing can be copieds at this point.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (1.71GB free)|
|Process Argv|--crash-reporter-id ac3b8f2c-f520-4b63-a05b-86e51069b12c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
xml|Dot|2.5.1
prettier-vscode|esb|9.0.0
gc-excelviewer|Gra|3.0.44
vscode-thunder-client|ran|1.9.1
vim|vsc|1.21.7
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
dockerwalkthrucf:30369616
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by alexdima** [comment] 2021-09-24 14:11
@mchassy I cannot reproduce:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/134688808-c6a5ab15-3d90-42ef-aac6-2407464a22b4.gif)

**Comment by mchassy** [comment] 2021-09-24 15:52
The behaviour is variable. Sometimes does not work at all. Sometime only works works with Ctrl-C. Here a few screen recordings. You can clearly see that sometimes you select something which appears to be highlighed in blue. Then when you right-click it becomes grey.


1. Trying to copy from the documentation of Thunder REST Client (using both right click and ctrl-c)

https://user-images.githubusercontent.com/15926092/134704160-6b91052e-0bff-45f6-9e55-e9314dab1dd9.mp4

2. Trying to copy from the environment variable section of Thunder REST Client  (using both right click and ctrl-c)

https://user-images.githubusercontent.com/15926092/134704471-b078568e-0a7c-40bb-8057-92f694582c3b.mp4

3. Trying to copy from a CSV file  (using both right click and ctrl-c)

https://user-images.githubusercontent.com/15926092/134704555-ff40eac3-e650-4f64-a71a-a590d4287dc4.mp4

**Comment by sandy081** [comment] 2021-09-28 12:40
@mchassy Videos are not clear. Can you please upload them with good resolution?

It seems user is copying from web views, hence assigning to @mjbvz

**Comment by mchassy** [comment] 2021-09-28 13:12
Sorry, trying to find the right profile so they are clear enough, but can still be uploaded. These should work better.

https://user-images.githubusercontent.com/15926092/135093581-56d5bedd-50d6-42d0-b926-fa02ae42791d.mp4


https://user-images.githubusercontent.com/15926092/135093544-cf132a56-ffe2-4e31-853e-87616a037d14.mp4


https://user-images.githubusercontent.com/15926092/135093556-0de5335b-1ab3-4c9f-b030-b7fe10850778.mp4

**Closed** 2021-10-19 11:25 UTC
Labels: needs more info
