### ISSUE TITLE
Remote window / integration tests is broken

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#105562] opened 2020-08-28 07:14 UTC
```
illegalState - creating UNKNOWN service instance ExtensionGalleryService: Error: illegalState - creating UNKNOWN service instance ExtensionGalleryService
    at InstantiationService._createServiceInstanceWithOwner (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:171:23)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:156:43)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:113:29)
```

Caused by 8743d95c76e76b5b665c5b1b1ba2ef9ebdbbad49

**Comment by sandy081** [comment] 2020-08-28 07:18
This is caused, because of using `instantiationService` to create `DesktopRemoteExtensionManagementService`.

https://github.com/microsoft/vscode/blob/1cc26ce/src/vs/workbench/services/extensionManagement/electron-browser/extensionManagementServerService.ts#L40

Error does not happen when I changed this to create the instance directly

```ts
const extensionManagementService = new DesktopRemoteExtensionManagementService(remoteAgentConnection.getChannel<IChannel>('extensions'), this.localExtensionManagementServer, logService, galleryService, configurationService, productService);
```

Pushing above fix for now to unblock builds.

@jrieken Any insights why the former did not work?

**Comment by sandy081** [comment] 2020-08-28 07:40
It seems using `IInstantiationService` to create `DesktopRemoteExtensionManagementService` is causing this error:

https://github.com/microsoft/vscode/blob/1cc26ce/src/vs/workbench/services/extensionManagement/electron-browser/extensionManagementServerService.ts#L40

No error is seen, when I changed this to instantiate `DesktopRemoteExtensionManagementService` directly

```ts
const extensionManagementService = new DesktopRemoteExtensionManagementService(remoteAgentConnection.getChannel<IChannel>('extensions'), this.localExtensionManagementServer, logService, galleryService, configurationService, productService);
```

Pushing this to unblock builds.

@jrieken any insights about the difference here?

**Comment by jrieken** [comment] 2020-08-31 16:09
@sandy081 Did you find anything out here? One other possible case could be a service depending on this service and since it's still creating it cannot be depended on

**Comment by sandy081** [comment] 2020-08-31 16:12
@jrieken Oh no, I did not find any.

I closed it as I was cleaning up issues for current milestone. I forgot about this.

Will reopen and investigate it during endgame (or debt week)

**Comment by sandy081** [comment] 2020-09-22 20:07
@jrieken Did some investigation but could not find out the root cause (also tried enabling trace in InstantiationService). Probably you might be faster in understanding it. I made it simpler to reproduce from sources

- Comment out following line 
https://github.com/microsoft/vscode/blob/6ddaba3a52b59b1679b07d1423ebc641ba72cf5b/src/vs/workbench/services/extensionManagement/electron-browser/extensionManagementServerService.ts#L33
- Open remote window - you will see following error

```
ERR illegalState - creating UNKNOWN service instance ExtensionGalleryService: Error: illegalState - creating UNKNOWN service instance ExtensionGalleryService
    at InstantiationService._createServiceInstanceWithOwner (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:171:23)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:156:43)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:113:29)
    at Object.get (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:36:45)
    at Workbench.initLayout (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/layout.js:141:42)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:67:26
    at InstantiationService.invokeFunction (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at Workbench.startup (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:61:38)
    at DesktopMain.open (file:///Users/sandy081/work/vscode/out/vs/workbench/electron-browser/desktop.main.js:61:52)
```

**Comment by jrieken** [comment] 2020-09-23 08:08
This is interesting... It does seems to be an issue with the instantiation service but I don't know yet what exactly. Whenever something is instantiated it's dependency graph (of services) is built and then root-by-root dependencies are created first. It seems that the `extensionGalleryService` appears as root two times, e.g after it has already been instantiated and that's something we don't expect.

<img width="865" alt="Screenshot 2020-09-23 at 10 06 41" src="https://user-images.githubusercontent.com/1794099/93984745-7d6c9580-fd84-11ea-8373-ccaceee298de.png">

**Comment by jrieken** [comment] 2020-09-23 08:23
Ok, this isn't a problem with the dependency graph but somewhat concurrent modifications of the internal instantiation service stats. This is the cause: https://github.com/microsoft/vscode/blob/6ddaba3a52b59b1679b07d1423ebc641ba72cf5b/src/vs/workbench/services/extensionManagement/electron-browser/extensionManagementServerService.ts#L41. 

So, there is a dependency graph. We start with those nodes that have no dependencies and instantiate them, then remove those node, and restart with the new set of nodes. What's happening here is that resolving roots has side-effect on subsequent dependencies because it again uses the instantiation service. That leads to unexpected results because the dependency graph is now out-of-sync with the real world

**Closed** 2020-09-23 08:59 UTC
Labels: bug
