### ISSUE TITLE
IntelliSense is disabled by default in new release.

### ISSUE THREAD

**Issue by xinkule** [Microsoft/vscode#71778] opened 2019-04-05 09:07 UTC
- VSCode Version: 1.33.0
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:

1. install new version vscode and restart

Today when I installed the new version of vscode and restarted, I found out that the quick suggestion doesn't work anymore. So I tried restarting vscode and my computer, neither of these attempts worked.

I don't know if others run into the same problem, but I guess this behavior is disabled by default in the new release ? If so, I think it's really upset when you open your code, and find out what used to work doesn't work anymore.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kanitsharma** [comment] 2019-04-05 09:19
I am facing similar issues after the update, for me even go to definition isn't working. I tried updating my settings as you suggested, still not working. :(

**Comment by xinkule** [comment] 2019-04-05 09:26
> I am facing similar issues after the update, for me even go to definition isn't working. I tried updating my settings as you suggested, still not working. :(

The setting doesn't work for me anymore, so I edited it... The same goes for 'go to definition', when I hover on the variable, I can the `loading`, so I guess there is something going wrong with whatever connection it is.

**Comment by kanitsharma** [comment] 2019-04-05 09:31
CPU spiking to 100%
https://github.com/Microsoft/vscode/issues/71760#issuecomment-480208796
I think issue with ts-server

**Comment by AndreevskiAleksandar** [comment] 2019-04-05 10:48
I can see the ```loading``` text also, but no autocompletion or ```go to definition``` also. The CPU does not have spikes. It is just endlessly stuck on loading... I am on MacOS Mojave 10.14.2

**Comment by clapertosa** [comment] 2019-04-05 10:53
Same CPU heavy load and IntelliSense not working on Manjaro (Linux).

**Comment by AndreevskiAleksandar** [comment] 2019-04-05 10:58
The CPU spikes go up when the files validate the syntax. Example: I ll not close a bracket, and the line is underlined in red as it should, but when I close it, it takes up to 30-60 seconds to remove the syntax error and the CPU load goes up.

**Comment by george-maged** [comment] 2019-04-05 11:55
I am having the same Issue on windows 10 after I updated VS code. I get loading text when I hit control + space and the suggestions come after a minute or so.

**Comment by pedromarquesm** [comment] 2019-04-05 12:13
same problem here. disabled update.mode to manual, and downgraded to 1.32.3.
Downgrade solved my problem

**Comment by cpwinn** [comment] 2019-04-05 15:03
> same problem here. changed
> 
> `update.mode`
> 
> to manual, and downgraded to 1.32.3.
> Downgrade solved my problem

Same for me. Here is the 1.32.3 installer: https://code.visualstudio.com/updates/v1_32

**Comment by pedromarquesm** [comment] 2019-04-05 15:54
I actually found what was causing all this issues.
This new version set the Typescript version to be used, as the default of VS Code, instead of the version inside the project/workspace.
So, all of a sudden, vs code forced typescript version 3.4.1
![image](https://user-images.githubusercontent.com/41088477/55640404-6b2f1e00-57c3-11e9-849f-cd5ad8133e64.png)
access that selection. by clicking on (that is enabled when .ts files are open):
![image](https://user-images.githubusercontent.com/41088477/55640443-7f731b00-57c3-11e9-8bda-a3f04f60dadd.png)

**Comment by mjbvz** [comment] 2019-04-05 19:11
Duplicate of #71751 

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for possible workarounds

If that doesn't solve the issue for you, please open a new issue

**Closed by mjbvz** 2019-04-05 19:11 UTC
Labels: new release
