### ISSUE TITLE
Multiple Build Commands are not executed

### ISSUE THREAD

**Issue by FloMaetschke** [Microsoft/vscode#16345] opened 2016-12-01 21:20 UTC
- VSCode Version: 1.8.8.0-insider  (4721762...)
- OS Version: Windows 10

Steps to Reproduce:

1.  set tasks.json like this:
```

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "echo",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "isBuildCommand": true,
            "taskName": "build-task1",
            "args": [
                "1"
            ]
        },
        {
            "isBuildCommand": true,
            "taskName": "build-task2",
            "args": [
                "2"
            ]
        }
    ]
}

```
2. Press ctrl+shift+b. Output should be 1 2 but it is only 1.

**Comment by chrmarti** [comment] 2016-12-02 22:22
Duplicate of #16373

**Closed by chrmarti** 2016-12-02 22:22 UTC
Labels: tasks
