### ISSUE TITLE
Emmet syntax appears to be broken

### ISSUE THREAD

**Issue by benjaminmillhouse** [Microsoft/vscode#13508] opened 2016-10-11 13:35 UTC
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: abusaidm.html-snippets-0.0.16, andischerer.theme-atom-one-dark-0.0.1, dbaeumer.vscode-eslint-1.0.7, donjayamanne.githistory-0.1.0, HookyQR.JSDocTagComplete-0.0.2, joelday.docthis-0.3.4, johnpapa.Angular1-0.1.16, ms-vscode.csharp-1.4.1, ms-vscode.js-atom-grammar-0.1.9, robertohuertasm.vscode-icons-3.0.3, wcwhitehead.bootstrap-3-snippets-0.0.7, Zignd.html-css-class-completion-1.0.3

Steps to Reproduce:

1. Type an emmet with a class (ex: div.form-group)
When pressing tab to expand the emmet, the only thing expanded is the 'p', so it expands to:
`div.form-grou<p></p>`

**Comment by egamma** [comment] 2016-10-11 13:43
@benjaminmillhouse I cannot reproduce given the steps above. Please add more detailed steps. Ideally with a snippet to reproduce the problem.

![emmet](https://cloud.githubusercontent.com/assets/172399/19272577/5ecd2d24-8fc9-11e6-85ec-e75abd75dc54.gif)

**Comment by benjaminmillhouse** [comment] 2016-10-11 13:50
The steps are type div.form-group, press tab to expand the emmet

Here is what it looks like in my VS Code.  I just updated to the latest release this morning. I did not have any issues prior to this release.  Normal emmets still work (div, span, etc.) but it doesn’t like the class syntax on my machine now.

**Comment by mrmlnc** [comment] 2016-10-11 13:54
IMHO, related to `abusaidm.html-snippets-0.0.16` extension. You use `"editor.tabCompletion": true`, right? Try running VS Code without extensions by `code . --disable-extensions`.

**Comment by benjaminmillhouse** [comment] 2016-10-11 13:56
Right
Let me go ahead and remove that extension altogether and see if that clears it out.

**Comment by benjaminmillhouse** [comment] 2016-10-11 13:56
That fixed it.  Thank you for the quick response.
Sorry for the false alarm.

**Comment by mrmlnc** [comment] 2016-10-11 14:04
Ping @jrieken 😺

**Comment by jrieken** [comment] 2016-10-11 14:06
Yes - by default `tabCompletion` takes precedence over emmet

**Comment by benjaminmillhouse** [comment] 2016-10-11 14:18
Thank you all for the feedback.
I’ve noticed one other difference I wanted to ask about.
Previously I had been writing my JavaScript classes in this format:

var Class = (function () {
	function Class() { }
	return Class;
}());

and before IntelliSense picked up on the class structure whenever I created a new instance.
ex: var a = new Class();
However, now it shows ‘a’ as type ‘any’ in the example able.
To correct this, I have to remove the IIF from around function Class() and it works.
Just curious if this was intentional?  Is there some documentation you could refer me to for what Code will auto-detect in terms of class syntax?

Unfortunately my project cannot be written in TypeScript yet, so it was very helpful to at least have full autocompletion if I structured my class definitions the way code expected.

Thanks!

Ben

**Comment by jrieken** [comment] 2016-10-11 16:19
@benjaminmillhouse re https://github.com/Microsoft/vscode/issues/13508#issuecomment-252930121 separate problems/questions/bugs/etc deserve separate github issues. Please, create a new issue for that.

**Comment by egamma** [comment] 2016-10-12 09:41
closing this issue.

**Closed by egamma** 2016-10-12 09:41 UTC
Labels: upstream
