### ISSUE TITLE
TSC hangs on while building

### ISSUE THREAD

**Issue by hasankoroglu** [Microsoft/vscode#38052] opened 2017-11-10 11:18 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.11.1
spfx-debug|eli|0.0.3
spfx-essentials|eli|0.0.2
auto-close-tag|for|0.5.3
beautify|Hoo|1.1.1
json-to-ts|Mar|1.5.3
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.17.0
autoimport|ste|1.5.3
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. ctrl + shift + b
2. building icon spinning always, can not finish building.  but creates the js files.
[TypeScript.zip](https://github.com/Microsoft/vscode/files/1461102/TypeScript.zip)

For video record: https://1drv.ms/u/s!Aj-2PjPharvQg-56fDmSDytfMggQGw

Reproduces without extensions: Yes - no luck

**Comment by mjbvz** [comment] 2017-11-10 19:27
What version of `tsc` are you using? You can find this by running `tsc --version` in the integrated terminal

**Comment by OlekNg** [comment] 2017-11-10 22:06
I have the same problem. Only tslint extension. Typescript 2.6.1

**Comment by dbaeumer** [comment] 2017-11-13 09:49
Very likely a dup of #37934 which will be fixed with the next recovery build.

**Comment by hasankoroglu** [comment] 2017-11-13 09:58
@mjbvz sorry for the lately answer. My tsc Version 2.6.1.

**Comment by mjbvz** [comment] 2017-11-13 21:25
Thanks @dbaeumer!

Yes this does sounds like a duplicate of #37934  

@hasankoroglu Please try the current VS Code insiders build and let me know if you still see this problem

**Closed by mjbvz** 2017-11-13 21:25 UTC
Labels: duplicate, new release

**Comment by OlekNg** [comment] 2017-11-13 21:38
Just tried the newest insiders build and in my case the problem has been solved.
Thanks!

**Comment by hasankoroglu** [comment] 2017-11-13 22:14
Thanks guys, you are awesome. Problem solved.
