### ISSUE TITLE
Message after installing an extension should have a Close or Later button

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4243] opened 2016-03-15 11:55 UTC
fyi @egamma 

![image](https://cloud.githubusercontent.com/assets/5047891/13776919/1237e006-eaad-11e5-954d-323f8eb699ef.png)

**Comment by joaomoreno** [comment] 2016-03-15 13:54
Duplicate of #4157

**Closed by joaomoreno** 2016-03-15 13:54 UTC
Labels: polish
