### ISSUE TITLE
Javascript colorization for "let" & "var" parameters inside a function

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#3933] opened 2016-03-09 20:38 UTC
Let and var parameters of Javascript are not being colorized properly when used as part of a longer word/parameter inside a function.

![parametercolor](https://cloud.githubusercontent.com/assets/12900364/13649641/7e700b2c-e5f3-11e5-9427-eacbcde85757.JPG)

`fcamelCase = function( all, letter, lettuce, constest ) {
		var variance = letter.toUpperCase();
		return variance;
	};`

This is effecting the latest Alpha build (0.10.12-alpha)

**Comment by aeschli** [comment] 2016-03-10 09:43
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by aeschli** 2016-03-10 09:43 UTC
