### ISSUE TITLE
Inconsistent behavior when I modify a test

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#115067] opened 2021-01-26 15:47 UTC
Testing #114932

When I modify this failing test, to make it pass, it seems to re-run the test,  but when I modify it to make it fail in a different way than before, then it displays the run icon. 

![recording (7)](https://user-images.githubusercontent.com/29464607/105867834-5f20db80-5faa-11eb-95cc-acb9907bcd98.gif)

**Comment by connor4312** [comment] 2021-01-26 16:54
That's because the sample extension is using the test name as a cache for the state. THere's an existing 2 + 2 = 4 test so it's marked as passed, but no 2 + 2 = 5 test so it's the 'unset' state.

This is an artifact of how the sample works, and I will be changing how states are dealt with next month, so closing this 'as designed' for now

**Closed** 2021-01-26 16:55 UTC
Labels: *as-designed

**Comment by connor4312** [comment] 2021-01-26 17:25
https://github.com/microsoft/vscode/issues/115101
