### ISSUE TITLE
Integrated Terminal Not Launching

### ISSUE THREAD

**Issue by kk-sdsu** [Microsoft/vscode#30738] opened 2017-07-14 22:45 UTC
- VSCode Version: 1.14.1
- OS Version: Windows 10

Opening Integrated Terminal stopped working after the recent update to VSCode. Still working fine on my Mac and Windows VMs with same, updated version.

I did change from the default C:\WINDOWS\Sysnative\cmd.exe, but neither that nor powershell nor git bash will work. It just won't open. No Error message or warning. Clicking the + to add another instance does nothing.

Steps to Reproduce:

1. Open VS Code
2. Attempt to open Integrated Terminal (ctrl + `)

Reproduces without extensions: No idea

![image](https://user-images.githubusercontent.com/25672852/28233289-9e9dbe0e-68aa-11e7-9b25-80f9f8e2ffa5.png)

**Comment by Tyriar** [comment] 2017-07-15 00:01
If you're on the 64-bit version of VS Code this is a duplicate of https://github.com/Microsoft/vscode/issues/27915

**Closed by Tyriar** 2017-07-15 00:01 UTC
Labels: integrated-terminal, new release
