### ISSUE TITLE
High CPU usage in ubuntu16.04

### ISSUE THREAD

**Issue by 995270418L** [Microsoft/vscode#26702] opened 2017-05-16 00:56 UTC
- VSCode Version: 1.12
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. run the vscode and use the top command in shell to check the cpu usage
2. find more than 137.9% usage of CPU without run projects.

**Comment by Tyriar** [comment] 2017-05-16 19:55
@995270418L can you try closing all windows and running `code --disable-extensions` to see if it reproduces?

**Comment by peperunas** [comment] 2017-05-23 14:17
+1 on Arch linux

`VSCode version: 1.12.2`
`OS`: Arch Linux

I have run it with and without `--disable-extensions`

**Comment by Tyriar** [comment] 2017-05-23 16:52
Could people reproducing this run `ps aux | grep code` and find the command/args that have the high CPU (third col)?

**Comment by peperunas** [comment] 2017-05-23 18:31
```

**Comment by Tyriar** [comment] 2017-05-24 00:31
@bpasero `watcherService` seems to be taking 113% CPU?

**Comment by bpasero** [comment] 2017-05-24 04:44
https://github.com/Microsoft/vscode/issues/3998

**Closed by bpasero** 2017-05-24 04:44 UTC
Labels: linux, needs more info, perf

**Comment by 995270418L** [comment] 2017-05-24 09:52
Cause this problem in my computer( ubuntu16.04 vscode 1.12) is the vueJS plugin. when i uninstall it. the software become normal when it running.

**Comment by 995270418L** [comment] 2017-05-24 09:54
And the all plugins of vuejs cause this problem.

**Comment by YUFENGWANG** [comment] 2017-09-07 05:57
same problem here, still digging it out.
