### ISSUE TITLE
Auto close single and double quotes aren't working

### ISSUE THREAD

**Issue by vvinhas** [Microsoft/vscode#26820] opened 2017-05-17 14:07 UTC
For some odd reason, single and double quotes are not self closing.
Brackets and parentheses are working fine though.

![Screencast](https://media.giphy.com/media/xUPGcGTK3Q4dMhtvpe/giphy.gif)

**VSCode Version:** April 2017 (1.12)
**OS Version:** macOS Sierra (10.12.4)

**Comment by rebornix** [comment] 2017-05-26 00:34
@vvinhas can you try to run Code without any extension by `code --disable-extensions`? Besides, can you open Help --> Developer Tools and see if there is any error there?

**Comment by vvinhas** [comment] 2017-05-26 01:18
NP @rebornix 

Unfortunately, the same thing happens and no errors are shown in the console.
![VSCode Extensions Disabled](https://media.giphy.com/media/3og0ILithD6XggVJdK/giphy.gif)

**Comment by rebornix** [comment] 2017-05-26 16:48
@vvinhas can you share the extensions list with me ? Or even better together with your settings file.

**Comment by vvinhas** [comment] 2017-05-27 02:33
Yup!

**Extensions**
```
FallenMax.mithril-emmet-0.6.1
HookyQR.beautify-1.0.2
KTamas.laravel-blade-0.0.1
Kasik96.format-indent-1.3.0
Shan.code-settings-sync-2.7.0
Shan.code-settings-sync-2.8.0
TwentyChung.jsx-0.0.1
WallabyJs.quokka-vscode-1.0.33
WallabyJs.quokka-vscode-1.0.34
abusaidm.html-snippets-0.1.0
christian-kohler.path-intellisense-1.4.2
dbaeumer.vscode-eslint-1.2.11
dkundel.vscode-new-file-3.0.2
donjayamanne.githistory-0.2.0
felixfbecker.php-debug-1.10.0
felixfbecker.php-intellisense-1.2.1
felixfbecker.php-intellisense-1.2.2
ikappas.phpcs-0.7.0
neilbrayfield.php-docblocker-1.1.0
onecentlin.laravel-blade-1.8.1
robertohuertasm.vscode-icons-7.7.0
robinbentley.sass-indented-1.4.1
xabikos.javascriptsnippets-1.4.0
xabikos.reactsnippets-1.3.0
zhuangtongfa.material-theme-2.7.8
zhuangtongfa.material-theme-2.8.0
```

**Settings**
```json
{
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.fontSize": 14,
    "editor.fontWeight": "300",
    "editor.lineHeight": 22,
    "editor.tabSize": 4,
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "editor.formatOnType": true,
    "files.exclude": {
        "**/*.cs.meta": true
    },
    "workbench.colorTheme": "One Dark Pro",
    "workbench.iconTheme": "vscode-icons",
    "workbench.editor.tabCloseButton": "right",
    "window.zoomLevel": 1,
    "emmet.syntaxProfiles": {
        "javascript": "jsx"
    },
    "newFile.defaultBaseFileName": "script",
    "newFile.defaultFileExtension": ".js",
    "[javascript]": {
        "editor.tabSize": 2
    },
    "[javascriptreact]": {
        "editor.tabSize": 2
    },
    "sync.gist": "", //hidden
    "sync.lastUpload": "", //hidden
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "eslint.autoFixOnSave": false
}
```

**Comment by jochim-van-dijck** [comment] 2017-06-04 03:20
I have the exact same bug! All brackets are auto-closing but the `'` and `"`, I cannot figure out for the life of me what causes this behaviour. I am on a completely fresh install of VS Code v1.12.2 and macOS Sierra v10.12.5.

**Comment by vvinhas** [comment] 2017-08-02 13:48
Using version `1.14.2` and the bug persist.

**Comment by melquic** [comment] 2017-08-19 17:56
Same bug here. Version 1.15.1 and MacOS 10.12.5

**Comment by tormink** [comment] 2017-08-20 23:47
Same bug here. Version 1.15.1 and macOS 10.12.6.

**Comment by vtr83** [comment] 2017-08-30 11:12
I wrote a keybinding to solve this
```
{
    "key": "shift+'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {"snippet": "$1\""}
},
{
    "key": "'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {"snippet": "$1'"}
}
```
So you can hit single or double quotes and then space

**Comment by andremacola** [comment] 2017-08-31 22:50
Sabe problem here with the latest stable version

**Comment by andremacola** [comment] 2017-09-05 04:54
@vtr83 the problem with this approach is that in languages like portuguese, we accentuation in words for exemple á é í ó ú and we do that with the same single quote key

**Comment by tormink** [comment] 2017-09-06 01:40
I also use a Brazilian keyboard (**Brazilian Pro** is the name of the keyboard configuration in macOS). I just added the standard U.S. keyboard, and it no longer bugs with quotes, however, I can no longer use accented characters such as á, é, í, ó, ú that way, because the keyboard now treats the quotes simply as quotes, not helper keys for accents. I do not wish to need to keep switching around all the time while coding, when I need to write a string in Portuguese. So the problem is VS Code can't handle that keyboard configuration for some reason. Other editors I've tested have that behavior for quotes if you press once and then space, which is the expected behavior in that case.

**Comment by vtr83** [comment] 2017-09-08 11:16
@andremacola I know, i'm from Brazil, the Atom editor has the best behavior in this situation, if you type a single (or double) quote and then you type a vowel or 'c' it will be used as accent, but if you press 'space' or other letter it will be wrapped in quotes, I wrote the keybinding as a provisional solution, the best would be vscode to have the same behavior as Atom does.

**Comment by CodeSigils** [comment] 2017-09-22 08:21
Same Here with VS Code version 1.16.1 in OSX Sierra 10.12.6

**Comment by CodeSigils** [comment] 2017-09-22 08:39
Ok, I have found the solution:
Try setting the language to "U.S." instead of "U.S. International - PC" in the language menu of the menu bar (keyboard -> Input Sources). It seems The "international" option adds special characters and interacts with quotation symbols. Solved for me.

**Comment by andremacola** [comment] 2017-09-22 15:48
@CodeSigils yes this is a Vscode problem, all the other editors works just fine. Your solution is not for non-english languages.

**Comment by hugw** [comment] 2017-10-02 18:46
I can confirm the issue. Right now I'm using keyboard layout set to "U.S International". ST and Atom work as expected.

**Comment by nighto** [comment] 2017-10-10 18:39
Seems to be macOS specific problem, doesn't have this on VSCode 1.14.0 on Windows 7.

**Comment by blairdow** [comment] 2017-10-10 22:10
Similar issue here... brackets, parentheses, etc autoclose properly. I have found that double and single quotes autoclose properly UNLESS they are typed inside an html tag, ie. to add a class name.

**Comment by vitor-hugo** [comment] 2017-10-11 13:04
@nighto True! I've tried on Windows 10, and even with English keyboard it works!

P.S. Atom on MacOS also works properly.

**Comment by vtr83** [comment] 2017-10-11 13:09
@nighto True! I've tried on Windows 10, and even with English keyboard it works!

P.S. Atom on MacOS also works properly.

**Comment by darqueos** [comment] 2017-10-13 14:21
Same issue. Running macOS 10.13 and VSCode 1.17.1. I also use _U.S. International - PC_ as the default keyboard configuration. All other editors don't have this issue though.

**Comment by tocvieira** [comment] 2017-10-23 13:36
Same issue here.

**Comment by Heckthor** [comment] 2017-10-23 23:09
I hate "same here" posts but same here. Autocompletion doesn't work inside HTML tags. I tried quotes, double quotes, parenthesis, brackets, curly braces. 

It does work inside HTML files but outside tags.

**Comment by dandeveloper** [comment] 2017-10-29 00:34
Same issue here, when type single or double quotes the Auto close isn't working.
Macbook Air
OS: MacOS 10.13
VSCode Version: 1.17.2
Keyboard Layout: US International - PC

**Comment by LeReverandNox** [comment] 2017-10-30 12:51
Exactly same issue here =/

**Comment by rubencherbit** [comment] 2017-10-30 13:20
Same here :(

Macbook Pro 15" 2017 Touchbar
MacOS 10.13
VSCode 1.17.2
Keyboard Layout : US International PC

**Comment by betorobson** [comment] 2017-11-07 16:54
same here!
Mac OS High Sierra 10.13.1

I'm very disappointed, moving back to ST until VS Code get this fixed :-(

**Comment by vpcsilva** [comment] 2017-11-13 19:25
Same issue here.
Macbook running Mac OS Sierra 10.12.6
VS Code 1.16.1
Keyboard settings: U.S. International - PC
😞

**Comment by bloqhead** [comment] 2017-11-17 16:52
I am on version 1.18.1 and am encountering the same bug. Completely disabled all extensions and the bug persists. I also tried clearing out my custom settings and restarted but to no avail.

It seems to only be happening in Twig for me, even when I had all extensions disabled. Tested in other file types and it works just dandy.

**Comment by stephenpc** [comment] 2017-11-20 14:03
Reporting the same bug... happens regardless of file type.

- Macbook Pro 15" 2017 w/Touch Bar
- macOS High Sierra 10.13.2
- Visual Studio Code 1.81.1 (with extensions enabled or disabled)
- Keyboard Layout: U.S. (standard)

**Comment by vvinhas** [comment] 2017-11-21 02:44
With so many reports, this should be considered a severe bug. It's ruining the experience for Mac users.

**Comment by Rumyra** [comment] 2017-11-23 14:13
The keybinding @vtr83 made above doesn't work as I would expect to fix this...

I modified it - this is how I would want my quotes to work (I add one and one appears after and the cursor stays in the middle)

`{
    "key": "shift+'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
      "snippet": "\"$1\""
    }
  },
  {
    "key": "'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
      "snippet": "'$1'"
    }
  }`

**Comment by Robitis** [comment] 2017-12-01 21:24
I am experiencing this bug on a Windows 7 laptop, v1.18.1, all extensions disabled

**Comment by robertotcestari** [comment] 2017-12-02 02:05
Same here!!!

**Comment by artem-p** [comment] 2017-12-04 08:46
Same thing. 1.18.0, Windows 10.

**Comment by artem-p** [comment] 2017-12-04 08:48
Sorry, in my case it was due to React JSX extension. Without it works fine.

**Comment by abreuallan** [comment] 2017-12-30 14:16
Same here on High Sierra.

**Comment by pedrotorchio** [comment] 2018-01-05 15:09
Same on High Sierra, US International keyboard

**Comment by morcegon** [comment] 2018-01-10 17:57
Same here on High Sierra, Brazilian Keys.

**Comment by sadstack** [comment] 2018-01-13 20:00
this bug is ruining my vscode experience..

macOS High Sierra, German layout

**Comment by Maffelz** [comment] 2018-01-13 20:01
FUCK THIS IDE, ALLWAYS PROBLEM BUT THE WANT THERE FUCKING MONEY !!!!!

**Comment by leelandmiller** [comment] 2018-01-31 05:25
This is the second time I've tried switching from Atom to Code in the past year. It starts out somewhat satisfying (for a couple hours) and then is ruined by something so small like this. Things that I never even thought twice about not having when using Atom. Apparently Code is just not ready for actual use yet.

**Comment by proimage** [comment] 2018-02-02 14:34
It's not being inside or outside of HTML that causes this behavior. Quotes autocomplete (or not) according to the char before and after them. From my testing:

- They autocomplete when before and after is whitespace
- They autocomplete when before is one of a number of different punctuation marks and after is whitespace or a closing HTML `>` tag.

**Comment by dandeveloper** [comment] 2018-02-27 14:36
Almost one year and no one has fixed this bug, because of that I'm still using Atom.

**Comment by golinmarq** [comment] 2018-03-03 00:10
@dandeveloper just change your keyboard settings or make a PR to solve this

**Comment by andersonsantos** [comment] 2018-03-09 02:29
Same here on High Sierra, Brazilian Keys.

**Comment by Toisen** [comment] 2018-03-13 19:56
Same in Win10 with Ru/En layout. The editor can't auto close quotes in 2018... Not even funny.
One of my collegues suggested me to try this editor instead of WebStorm. You know what? I'm almost done with it! Intellisense and autocompletion breaks if closing tag in front of it so i need to put space for some strange reason, there is no syntax highliting for Angular 5 properties in html templates even with Angular Language Service extension, refactorings not exist and I don't even want to tell you how big is my config file became in that two days of pain. Looks like the only thing that done right with this product is marketing strategy.

**Comment by lavandongen** [comment] 2018-04-13 08:41
Still an issue as of today :/ not cool. Code runs a lot better on my low-end hardware, but this and many other autocomplete bugs/features just totally ruin my coding experience. Switching back to Atom for now where this behaviour is perfect.

Will see in a year or so if this has changed.

**Comment by dsudduth** [comment] 2018-04-19 15:59
@rebornix Any chance you can offer some feedback here? Seems like something that could be escalated and fixed.

**Comment by BraisC** [comment] 2018-04-26 19:01
Yep, the problem appears when there is a char after the quotes, example:
<div class=**"**> //Not autocomplete
<div class=**"** > //Autocomplete correctly notice the space before the closing >

**Comment by caiodv** [comment] 2018-05-16 20:51
I had the same issue, just changed the language from "US International" to "US"  and  everything works fine now.

**Comment by leelandmiller** [comment] 2018-05-16 21:29
Really? Because I've always been on "US" and it's never worked.

**Comment by andremacola** [comment] 2018-05-16 22:30
@caiodv but with US layout you cant write words like á é í ó ú ñ ü ö ï... etc. You need US International

**Comment by caiodv** [comment] 2018-05-17 12:49
@andremacola on mac you can, you just need to use the alternative method of applying accents, press  option+e and you get é, option+i and you get î, and so on...on a windows machine I have no idea.

**Comment by vitor-hugo** [comment] 2018-05-17 17:18
I've created a keymap to solve this, you can use with selected texts as well.
```
{
  "key": "ctrl+shift+'",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "args": {
    "snippet": "\"${TM_SELECTED_TEXT}$1\""
  }
},
{
  "key": "ctrl+'",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "args": {
    "snippet": "'${TM_SELECTED_TEXT}$1'"
  }
},
{
  "key": "ctrl+;",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "args": {
    "snippet": "`${TM_SELECTED_TEXT}$1`"
  }
}
```

**Comment by vvo** [comment] 2018-05-23 13:59
How do you use it afterwards @dandeveloper?

**Comment by rodrigoyoshida** [comment] 2018-05-29 20:46
Same thing here, looks like it will never be fixed. Atom is a much better editor, I just keep using vscode because of its performance. I will switch back to Atom when they solve it.

**Comment by hdupin** [comment] 2018-06-02 15:43
Same thing here..

**Comment by aeciolevy** [comment] 2018-06-02 21:47
Same problem here.

**Closed** 2018-06-08 00:01 UTC
Labels: bug, editor-autoclosing, keyboard-layout

**Comment by rebornix** [comment] 2018-06-08 00:09
Learnt Portuguese a little bit (my first language doesn't have accents) and pushed a fix for this issue. The auto closing will be triggered when you press an acute accent like `'` and press space. Please note that the auto closing logic is the same as when you use US keyboard layout.

Techinically auto close doens't kick in before the fix is because inserting `'` in US international or Portuguese will switch the IME to composition mode, a following space quits the composition mode but we didn't try to see if we should do an auto closing.

--- 
To verifiers (VSCode team member):

* Please verify on different keyboard layouts which support acute accents
* Please verify auto close language configuration works properly

**Comment by aeciolevy** [comment] 2018-06-08 01:33
I am using a mac from the US, I guess the problem is the atom shortcut that I got, but it was a really good insight @rebornix .

**Comment by rebornix** [comment] 2018-06-08 04:48
@aeciolevy feel free to ping if the fix doesn't work for you, there are probably other issues that leads to unexpected behavior.

**Comment by dandeveloper** [comment] 2018-06-27 00:50
@rebornix I've made some tests and when I try to wrap the text with single or double quotes the text is replaced by the quotes. Another strange behavior that I noticed happens when you are in a single line comment in a javaScript file for example, the single and double quotes doesn't work properly.

**Comment by zelljhos** [comment] 2018-07-06 03:41
Hello, i solved this issue with this extension:
https://marketplace.visualstudio.com/items?itemName=konstantin.wrapSelection

i hope this feature could be by default in coming versions.

Thanks.

**Comment by lucheol** [comment] 2018-07-11 17:11
@rebornix, now its working in this last update! Thank you! I'm from Brazil, using Mac and ABNT keyboard (PT_BR).

**Comment by gfpacheco** [comment] 2018-07-11 17:42
Still not working on Mac using US International keyboard layout

**Comment by dandeveloper** [comment] 2018-07-11 19:38
@lucheol the open and close the quotes bug was solved but there is another bug when you try to wrap a word with quotes.
@rebornix Did you read my comment about the bug when you select a word and try to wrap it with quotes?

**Comment by lucheol** [comment] 2018-07-11 19:43
@dandeveloper really, only the open and close quotes are solved. Wrap quotes still not working here too.

**Comment by jeffersonRibeiro** [comment] 2018-07-16 01:04
@CentaurWarchief Fiz uma alteração no keybiding da @Rumyra para funcionar com a configuração de teclado "Brazilian Pro" do Mac.

`
  {
    "key": "shift+'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
      "snippet": "$1\""
    }
  },
  {
    "key": "'",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
      "snippet": "$1'"
    }
  }
`
