### ISSUE TITLE
Folding happens at one level above than it should

### ISSUE THREAD

**Issue by vincentvictoria** [microsoft/vscode#130453] opened 2021-08-10 01:21 UTC
Does this issue occur when all extensions are disabled?: YES

- VS Code Version: 1.59.0
- OS Version: macOS 11.3.1

Steps to Reproduce:

1. Create and open following test.js
```
let t = new UnitTest();

t.suite( "admin", s => {
    s
    .suite( 'admin.bogunso', async ( s ) => {
        s
        .beforeTest( setup )
        .afterTest( teardown )
        .test( 'admin.bogunso.add', async () => {
            console.log( 'try to fold this function' );
        })
        .test( 'admin.bogunso.user', async () => {
            console.log();
        })
    })
    .test( "admin.login", async () => {
        console.log();
    } )
    .test( "admin.service.tts", async () => {
        console.log();
    } ).skip()
    .test( "admin.mem.hall.list", async () => {
        console.log();
    } )
    .test( "admin.mem.hall.update", async () => {
    } )
    .test( "admin.asset.add, info", async () => {
        console.log();
    } )
    .test( "admin.asset.add2, info", async () => {
        console.log();
    } )
    .test( "admin.asset.list", async () => {
        console.log();
    } )
    .test( "admin.player.list", async () => {
        console.log();
    } )
    .test( "admin.player.info", async () => {
        console.log();
    } )
    .test( "admin.center", async () => {
        console.log();
    } )
    .test( "admin.center.photo.upload", async () => {
        console.log();
    } )
    .test( "admin.center.manager.add", async () => {
        console.log();
    } )
    .test( "admin.center.manager.add.dupe fails", async () => {
        console.log();
    } )
    .test( "admin.center.employee.list", async () => {
        console.log();
    } )
    .test( "admin.category", async () => {
        console.log();
    } )
    .test( "admin.category.sort", async () => {
        console.log();
    } )
    .test( "admin.category.sort.update", async () => {
        console.log();
    } )
    .test( "admin.category.sort.add", async () => {
        console.log();
    } )
    .test( "admin.category.update", async () => {
        console.log();
    } )
    .test( "admin.category.update.background", async () => {
        console.log();
    } )
    .test( "admin.category.delete", async () => {
        console.log();
    } )
    .test( "admin.video", async () => {
        console.log();
    } )
    .test( "admin.video.update - type", async () => {
        console.log();
    } )
    .test( "admin.video.update - forms", async () => {
        console.log();
    } )
    .test( "admin.video.2", async () => {
        console.log();
    } )
    .test( "admin.video.list", async () => {
        console.log();
    } )
    .test( "admin.video.list.", async () => {
        console.log();
    } )
    .test( "admin.video.list..", async () => {
        console.log();
    } )
    .test( "admin.video.list...", async () => {
        console.log();
    } )

    .beforeTest( setup )
    .afterTest( teardown )
} )
.run();
```
2. Try to fold from the line `console.log( 'try to fold this function' );`, it's expected to fold these lines:
```
        .test( 'admin.bogunso.add', async () => {
            console.log( 'try to fold this function' );
        })
```
But instead, it folds one more level than it should:
```
    .suite( 'admin.bogunso', async ( s ) => {
        s
        .beforeTest( setup )
        .afterTest( teardown )
        .test( 'admin.bogunso.add', async () => {
            console.log( 'try to fold this function' );
        })
        .test( 'admin.bogunso.user', async () => {
            console.log();
        })
    })
```
3. Any other foldings from other `console.log();` lines works as it should but not the line.

**Comment by aeschli** [comment] 2021-08-18 11:44
Looks like the TypeScript server does not create a folding regions for
```
        .test( 'admin.bogunso.add', async () => {
            console.log( 'try to fold this function' );
        })
        .test( 'admin.bogunso.user', async () => {
            console.log();
        })```
When removing two other ranges
```
    .test( "admin.video.list..", async () => {
        console.log();
    } )
    .test( "admin.video.list...", async () => {
        console.log();
    } )
 ```

Then the ones above get a range.
Is there some kind of limit? Looks like there's no more than 30 ranges created.

**Comment by mjbvz** [comment] 2021-08-18 17:45
Duplicate of https://github.com/microsoft/TypeScript/issues/25782

**Closed by mjbvz** 2021-08-18 17:45 UTC
