### ISSUE TITLE
Allow extensions to define the editor layout

### ISSUE THREAD

**Issue by stephen-hardy** [Microsoft/vscode#20239] opened 2017-02-09 00:28 UTC
Hello,

When I'm using the MSSQL extension and execute a query, it spits the window into two side by side panels to show the results. I can change that to over and under by toggling the editor layout, but I can't seem to find a setting that allows me to change the default. It would be nice for it to always open over and under.

If I haven't missed an existing global setting, I'd be happy just with that being added. However, what would really be nice is to have setting specific to certain actions. For example, I like seeing diff's side by side. I'd prefer to keep that, and still get SQL results over and under. Do extension developers have the ability to specify how the editor will split when they call for it? That would be ideal, then I'd ask that extension to make a setting too.

Thanks,
Stephen

**Comment by bpasero** [comment] 2017-02-09 08:24
I think what we should provide for extensions is a command to define the editor layout. I agree that it does not make sense to always go into one mode or the other, it depends on the action.

**Comment by bpasero** [comment] 2018-06-02 08:56
Marking as duplicate of https://github.com/Microsoft/vscode/issues/33102

**Closed by bpasero** 2018-06-02 08:56 UTC
Labels: api, feature-request
