### ISSUE TITLE
Image preview editor drag-and-drop behavior broken

### ISSUE THREAD

**Issue by seraku24** [microsoft/vscode#82533] opened 2019-10-14 21:37 UTC
Issue Type: <b>Bug</b>

![vscode-image-preview](https://user-images.githubusercontent.com/20533271/66784579-c0916980-ee8f-11e9-9445-a1d687127135.gif)

1. Open an image from the project to obtain an image preview editor.
2. Drag any file from the project onto the opened image preview editor.

Expected:
The new file can be dropped and opened either as a new tab in the existing pane or as a new pane split from the existing one.

Actual:
No drop behavior occurs unless dropping specifically within the tab area.

Side Note:
Rendering performance is significantly worse with the new image preview editor.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (11.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.47
vscode-semistandard|fle|1.1.2
cpptools|ms-|0.25.1
vscode-typescript-tslint-plugin|ms-|1.2.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-10-14 21:59
Thanks for the report. This is a duplicate of #25854

Both image previews and markdown previews now use webview editors. Will look into this month if there's time

**Closed by mjbvz** 2019-10-14 21:59 UTC
Labels: new release
