### ISSUE TITLE
VSCode cannot open a bash terminal on Windows WSL 2 / Ubuntu

### ISSUE THREAD

**Issue by ablankenship10** [microsoft/vscode#102628] opened 2020-07-15 19:23 UTC
When attempting to open a bash terminal from Windows to WSL 2 linux distro, it seems to be failing passing some arguments in whatever is actually starting a terminal instance, possibly a `login` command as that is what the error displays as missing some quotes. This only started happening after installing the latest insider builds of Windows, Linux Kernel, Nvidia driver, etc to gain access to CUDA within WSL. This bug also occurs in the latest VS code insider build with only the WSL extension enabled as necessary for the bug to occur.

- VSCode Version: 1.47.1
- VSCode Insiders Version: 1.48.0-insider
- OS Version: Windows 10.0.20161 (Fast dev ring) , Ubuntu 18.04

Steps to Reproduce:

1. Install the latest windows insider version
2. Enable WSL 2 and install latest linux kernel
3. Open project folder from console using `code .`
4. Attempt to open a terminal with ctrl-`
5. Terminal flashes for a second and disappears with following message:

```
xargs: unmatched double quote; By default quotes are special to xargs unless you use the -0 option

Usage: login [-p] name
       login [-p] [-h host] [-f name]
       login [-p] [-r host]
```

Other terminals for windows (powershell) and /bin/sh work. Only /bin/bash fails.

Remote Extension Host Log trace

```
[2020-07-15 13:46:59.312] [exthost] [debug] Terminal process launching on ext host {"executable":"/bin/bash","args":[],"cwd":"/home/aaron/dev/[Redacted]/[Redacted]"} /home/aaron/dev/[Redacted]/[Redacted] 305 18 {"USER":"aaron","SHLVL":"1","HOME":"/home/aaron","WSL_DISTRO_NAME":"Ubuntu-18.04","LOGNAME":"aaron","WSL_INTEROP":"/run/WSL/11397_interop","NAME":"TheGibson","_":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/node","TERM":"xterm-256color","PATH":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin","LANG":"C.UTF-8","SHELL":"/bin/bash","PWD":"/","HOSTTYPE":"x86_64","WSLENV":"VSCODE_WSL_EXT_LOCATION/up","SUDO_GID":"0","USERNAME":"aaron","PRE_NAMESPACE_PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/GtkSharp/2.12/bin:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn/:/mnt/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/120/DTS/Binn/:/mnt/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/nodejs/:/mnt/c/Users/Aaron/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Aaron/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/Aaron/AppData/Local/GitHubDesktop/bin:/mnt/c/Program Files (x86)/FAHClient:/mnt/c/Users/Aaron/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Aaron/AppData/Roaming/npm","SUDO_COMMAND":"/bin/bash -c set -a; [ -f \"$HOME/.systemd-env\" ] && source \"$HOME/.systemd-env\"; set +a; exec bash -c \\'/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/node\\'\\ -p\\ \\'\\\"9afcd7ffc9ae\\\"\\ +\\ JSON.stringify\\(process.env\\)\\ +\\ \\\"9afcd7ffc9ae\\\"\\'","SUDO_USER":"root","SUDO_UID":"0","MAIL":"/var/mail/aaron","PRE_NAMESPACE_PWD":"/mnt/c/Users/Aaron/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4","AMD_ENTRYPOINT":"vs/server/remoteExtensionHostProcess","PIPE_LOGGING":"true","VERBOSE_LOGGING":"true","VSCODE_IPC_HOOK_CLI":"/tmp/vscode-ipc-1489afc5-a78f-4092-962f-62a4d6888ff8.sock","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","TERM_PROGRAM":"vscode","TERM_PROGRAM_VERSION":"1.47.1","COLORTERM":"truecolor","VSCODE_GIT_IPC_HANDLE":"/tmp/vscode-git-756037f1c3.sock","GIT_ASKPASS":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/extensions/git/dist/askpass.sh","VSCODE_GIT_ASKPASS_NODE":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/node","VSCODE_GIT_ASKPASS_MAIN":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/extensions/git/dist/askpass-main.js"}

[2020-07-15 13:46:59.312] [exthost] [trace] IPty#spawn /bin/bash [] {"name":"xterm-256color","cwd":"/home/aaron/dev/[Redacted]/[Redacted]","env":{"USER":"aaron","SHLVL":"1","HOME":"/home/aaron","WSL_DISTRO_NAME":"Ubuntu-18.04","LOGNAME":"aaron","WSL_INTEROP":"/run/WSL/11397_interop","NAME":"TheGibson","_":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/node","TERM":"xterm-256color","PATH":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin","LANG":"C.UTF-8","SHELL":"/bin/bash","PWD":"/","HOSTTYPE":"x86_64","WSLENV":"VSCODE_WSL_EXT_LOCATION/up","SUDO_GID":"0","USERNAME":"aaron","PRE_NAMESPACE_PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/GtkSharp/2.12/bin:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn/:/mnt/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/120/DTS/Binn/:/mnt/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/nodejs/:/mnt/c/Users/Aaron/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Aaron/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/Aaron/AppData/Local/GitHubDesktop/bin:/mnt/c/Program Files (x86)/FAHClient:/mnt/c/Users/Aaron/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Aaron/AppData/Roaming/npm","SUDO_COMMAND":"/bin/bash -c set -a; [ -f \"$HOME/.systemd-env\" ] && source \"$HOME/.systemd-env\"; set +a; exec bash -c \\'/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/node\\'\\ -p\\ \\'\\\"9afcd7ffc9ae\\\"\\ +\\ JSON.stringify\\(process.env\\)\\ +\\ \\\"9afcd7ffc9ae\\\"\\'","SUDO_USER":"root","SUDO_UID":"0","MAIL":"/var/mail/aaron","PRE_NAMESPACE_PWD":"/mnt/c/Users/Aaron/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4","AMD_ENTRYPOINT":"vs/server/remoteExtensionHostProcess","PIPE_LOGGING":"true","VERBOSE_LOGGING":"true","VSCODE_IPC_HOOK_CLI":"/tmp/vscode-ipc-1489afc5-a78f-4092-962f-62a4d6888ff8.sock","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","TERM_PROGRAM":"vscode","TERM_PROGRAM_VERSION":"1.47.1","COLORTERM":"truecolor","VSCODE_GIT_IPC_HANDLE":"/tmp/vscode-git-756037f1c3.sock","GIT_ASKPASS":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/extensions/git/dist/askpass.sh","VSCODE_GIT_ASKPASS_NODE":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/node","VSCODE_GIT_ASKPASS_MAIN":"/home/aaron/.vscode-server/bin/485c41f9460bdb830c4da12c102daff275415b53/extensions/git/dist/askpass-main.js"},"cols":305,"rows":18,"useConpty":false,"conptyInheritCursor":false}
```

Does this issue occur when all extensions are disabled?: It occurs only with WSL 2 extension.

**Comment by cuzox** [comment] 2020-07-15 20:32
I was having a similar issue, probably not related.
VSCode would not be able to start in `Remote - WSL` mode, as it would give me the error popup `vscode disconnected from wsl+ubuntu`, and something about not being able to install the `Remote - WSL` extension.
I just did `wsl --shutdown` and it was fine

**Comment by ablankenship10** [comment] 2020-07-15 20:50
Yea that seems more like an issue with networking between the host and wsl distro. I am connected fine it just can't open a /bin/bash terminal, but I can use a /bin/sh terminal. Running `wsl` from powershell opens up bash fine. I'm guessing its something to do with this login call being done behind the scenes not escaping a string properly.

**Comment by mschnee** [comment] 2020-07-22 18:49
It's worth noting that I am experiencing this same issue in WSL2 after running the steps here to enable systemd and snap installation: https://github.com/DamionGans/ubuntu-wsl2-systemd-script

This essentially ensures systemd is running, and the process take a little time: if VSCode is attempting some kind of shell attachment before the systemd scripts have settled, when this may simply be the result of an error case bubbling up.

I can use a separate shell outside of the integrated terminal for now; I assume that long-term WSL2 plans may better support, or natively support, having systemd running (for the purpose of supporting graphical applications, see [here](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/#wsl-gui))

**Comment by benjamincburns** [comment] 2020-07-28 23:51
I'm also experiencing this issue, also running the latest Windows Insider build as of today (20175.1000). I also enabled `systemd` and `snap` via [DamionGans/ubuntu-wsl2-systemd-script](https://github.com/DamionGans/ubuntu-wsl2-systemd-script). At a guess, it'd appear that the problem is something to do with quoting of the args passed to `xargs` in [`enter-systemd-namespace`](https://github.com/DamionGans/ubuntu-wsl2-systemd-script/blob/4d221c4f9bf89187eee7cd7ee298e5344190b191/enter-systemd-namespace#L47). This script is sourced from `/etc/bash.bashrc`, so it's run on every normal login.

I'll see if I can't add some additional debugging output to that script and get some more info about what's going wrong.

**Comment by benjamincburns** [comment] 2020-07-29 00:00
I think this is because the WSL Remote extension is creating/modifying the file `~/.systemd-env`. The following line seems to be the issue - if I delete it and try executing the `xargs` command from the script I mentioned in my previous comment, it no longer complains.

```
SUDO_COMMAND="/bin/bash -c set -a; [ -f \"\$HOME/.systemd-env\" ] && source \"\$HOME/.systemd-env\"; set +a; exec bash -c \\'/home/myuser/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node\\'\\ -p\\ \\'\\\"f3cfc37ff7a5\\\"\\ +\\ JSON.stringify\\(process.env\\)\\ +\\ \\\"f3cfc37ff7a5\\\"\\'"
```

**Comment by benjamincburns** [comment] 2020-07-29 01:30
As a temporary workaround until this bug is fixed, I've edited my `enter-systemd-namespace` script to change the final `if` block to the following. It seems to get my VSCode terminal working, and so far it hasn't appeared to break anything else...


```bash
if [ -n "$SYSTEMD_PID" ] && [ "$SYSTEMD_PID" != "1" ]; then
    if [ -n "$1" ] && [ "$1" != "bash --login" ] && [ "$1" != "/bin/bash --login" ]; then
        exec /usr/bin/nsenter -t "$SYSTEMD_PID" -a \
            /usr/bin/sudo -H -u "$SUDO_USER" \
            /bin/bash -c 'set -a; [ -f "$HOME/.systemd-env" ] && source "$HOME/.systemd-env"; set +a; exec bash -c '"$(printf "%q" "$@")"
    else
        exec /usr/bin/nsenter -t "$SYSTEMD_PID" -a \
            bash -c '/bin/login -p -f "$SUDO_USER" $([ -f "$USER_HOME/.systemd-env" ] && /bin/cat "$USER_HOME/.systemd-env" | xargs -d '\''\n'\'')'
    fi
    echo "Existential crisis"
    exit 1
fi
```

**Comment by diddledan** [comment] 2020-07-29 01:38
Thanks, @benjamincburns for forwarding this to us at damiongans/ubuntu-wsl2-systemd-script. I'll file a PR with the fix now, but until it's merged you can get the fixed file from https://github.com/diddledan/ubuntu-wsl2-systemd-script/blob/vscode-remote-support/enter-systemd-namespace

**Comment by aeschli** [comment] 2020-08-11 21:39
I'm not aware that VSCode nor the VScode Remote extension creates `.systemd-env`. Are you sure?

**Comment by ablankenship10** [comment] 2020-08-21 07:33
Thanks @benjamincburns for hunting that down and @diddledan with the fork! Thats finally resolved it after not having a terminal all month :)

**Comment by aeschli** [comment] 2020-10-14 20:52
I'm afraid I don't really understand the details here. Let me know if there's anything that the Remote WSL extension needs to do  differently.

**Closed by aeschli** 2020-10-14 20:52 UTC
