### ISSUE TITLE
[Feature] New extension ideas (curated by users)

### ISSUE THREAD

**Issue by madarsbiss** [microsoft/vscode#72336] opened 2019-04-15 11:29 UTC
VS Code should implement a built-in feature where we could request ideas for new extensions... that way, while you code and come up with some concept that would make coding more productive (best ideas always arise while doing), you can post it to the public wish-list, which is available for curating for other VS Code users... Top voted extension ideas each week or so gets on top and might be an awesome source of inspiration for aspiring developers looking to contribute...

**Comment by usernamehw** [comment] 2019-04-15 14:52
Duplicate of #63298

**Closed** 2019-10-28 16:00 UTC
Labels: *duplicate, extensions
