### ISSUE TITLE
Support linkification of JsDoc import() on hover

### ISSUE THREAD

**Issue by icetbr** [microsoft/vscode#156429] opened 2022-07-27 12:40 UTC
I want to improve navigation between related code, using JsDoc comments as a mean. So when I hover my code I want to click the link and go to the specified symbol.

This is the specific case
`{@link import('./jsdocLinkTarget.js') t} `

And this is just some other tests that would be very nice if they worked as well
```js
/**
    | ____________ | ______________________ | ______________________                      |
    | ------------ | ---------------------- | ------------------------------------------- |
    | FAILS        | no special syntax      | ./jsdocLinkTarget.js                        |
    | WORKS        | proper markdown        | [jsdocLinkTarget](./jsdocLinkTarget.js)     |
    | FAILS        | symbol as target       | [jsdocLinkTarget](./jsdocLinkTarget.js#a1)  |
    | FAILS        | line as target         | [jsdocLinkTarget](./jsdocLinkTarget.js#L3)  |
    | FAILS        | self link              | [./jsdocLinkTarget.js]()                    |
    | FAILS        | reference              | [jsdocLinkTarget][1]                        |
    | FAILS        | jsdoc link             | {@link ./jsdocLinkTarget.js}                |
    | WORKS        | known symbol           | {@link jsdocLinkTarget}                     |
    | FAILS        | jsdoc import           | {@link import('./jsdocLinkTarget.js') t}    |
    | FAILS        | file protocol          | file://./jsdocLinkTarget.js                 |
    | WORKS        | http protocol          | https://www.google.com                      |
 */
const a = () => {};
```

**Comment by mjbvz** [comment] 2022-07-27 18:45
Duplicate of https://github.com/microsoft/TypeScript/issues/47718

See https://github.com/microsoft/TypeScript/issues/47718#issuecomment-1029220408

**Closed by mjbvz** 2022-07-27 18:45 UTC
