### ISSUE TITLE
Integrated terminal does not launch when project folder contains special/unicode characters

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#7727] opened 2016-06-15 16:23 UTC
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10 Home

![Gif](https://gyazo.com/d5e7694b12d7b1dc46346e98effea98f.gif)

Steps to Reproduce:

1. Open a folder with special characters;
2. Try to open the integrated Terminal;

**Comment by Tyriar** [comment] 2016-06-15 18:14
@VitorLuizC can you paste in some of the problem characters? Also do you have any terminal-specific settings set in your settings.json?

**Comment by VitorLuizC** [comment] 2016-06-15 19:32
My folder's name is "Paçoca", so the "ç" is the only special character, and no I didn't have any terminal-specific settings in my settings.json.

![settings.json screenshot](https://i.gyazo.com/218b7ae9af10fdee37f4f168957e6244.png)

I've tried to open integrated terminal in another folder without special characters("Pacoca") and it worked.

**Comment by Tyriar** [comment] 2016-06-15 19:55
Seems fine on stable and insiders on Linux:

![image](https://cloud.githubusercontent.com/assets/2193314/16095193/6bb0ab7a-32f8-11e6-994e-5d87314fbbbd.png)

Perhaps it's only happening on Windows?

**Comment by VitorLuizC** [comment] 2016-06-15 20:22
I don't know if it metters but that folder is inside my OneDrive folder.

![Folder's path](https://i.gyazo.com/7e9e5e10cdcb4dcf6ece2fe1822bb880.png)

**Comment by ZCShou** [comment] 2016-06-16 00:37
Chinese folder or  Japanese folder so does on Windows 10！！

**Comment by Tyriar** [comment] 2016-06-16 02:20
Must be a windows thing, I'll try have a look at this for v1.3

**Comment by hakanostrom** [comment] 2016-06-17 13:36
Can confirm it effects on a new installation of v1.2.1 and on windows.
Folders causing this for me is when opened as "root" and containing swedish letters (åäö)

**Comment by Tyriar** [comment] 2016-06-17 17:50
I had a look at this and it appears to be an upstream issue, moving to backlog.

**Comment by joseph-iussa** [comment] 2016-06-22 06:04
Can confirm this is happening for me as well (just updated to 1.2.1 and currently on Windows 10). Behaviour is exactly as shown in VitorLuizC's image, except that I have no special characters in my path, and in fact the problem still occurs with no folders or files open and just the initial untitled document displayed.

I recently upgraded to Windows 10 from Windows 7 and the problem was not present while on Windows 7.

**Comment by svekl** [comment] 2016-07-07 23:08
For me it happens for russian characters, I have "Сергей" in path on Win 10

**Comment by xmichaelx** [comment] 2016-07-19 09:00
Confirm for polish letters in path on Windows 10.

**Comment by hs3180** [comment] 2016-07-24 17:07
:+1: for Chinese

**Comment by Igmat** [comment] 2016-07-26 13:30
+1 for Russian on Windows 10. It doesn't matter are there any special characters in path for opened by VSCode folder. Having them in Windows username will be enough to get integrated-terminal crashing.

**Comment by ZCShou** [comment] 2016-07-26 13:51
@Tyriar  Chinese folder's error
![2016-07-26_214730](https://cloud.githubusercontent.com/assets/8591065/17140353/c36ca4c0-537a-11e6-8cb8-400ad4b6ec5a.png)
![2016-07-26_214755](https://cloud.githubusercontent.com/assets/8591065/17140354/c39c2812-537a-11e6-931f-d45b7da4dbd7.png)

**Comment by JohnyDeath** [comment] 2016-09-01 11:19
Any news?

**Comment by ugros** [comment] 2016-09-08 23:06
I've already opened an issue to this exact same problem 3 months ago. It was closed, because for Tyriar everything seemed to work fine. I've tried VScode on 3 different computers, with both powerShell and cmdprompt, with default settings, and it never worked. In fact, I've never seen a Windows computer that had integrated terminal working.

**Comment by Tyriar** [comment] 2016-09-08 23:14
@ugros many people are experiencing this issue as you can see from the linked issues. This issue is actually on the integrated terminal backlog (#9959) and is one of the major bugs I'll be looking at in September.

I can't see your original issue though? https://github.com/Microsoft/vscode/issues/created_by/ugros

**Comment by ugros** [comment] 2016-09-08 23:25
@Tyriar I've been using different github account. 
https://github.com/Microsoft/vscode/issues/7440

By the way, is there any workaround or any fix I can do with my computer, that would fix this issue in the meanwhile? My workflow suffers a lot by this issue.

Thanks a lot

**Comment by Tyriar** [comment] 2016-09-08 23:30
Ah, I think the EPIPE thing was something else that stopped occurring in 1.2 or 1.3.

The only workarounds I can think of are to rename/relocate the open folder. I'll hopefully be checking this out sometime next week so it may come through in the Insiders build then.

**Comment by ugros** [comment] 2016-09-08 23:35
> The only workarounds I can think of are to rename/relocate the open folder.
What do you mean by this? Could you please evaluate? Thanks

**Comment by Tyriar** [comment] 2016-09-09 17:05
I mean if you're working out of `C:\Users\<special chars>\dev` you can move your `dev` dir to `C:\dev` to get around this.

**Comment by joseph-iussa** [comment] 2016-09-11 07:51
I was able to fix this for myself by changing the setting `terminal.integrated.shell.windows` from
`"C:\\WINDOWS\\system32\\cmd.exe"` (the default I assume, at least I hadn't changed it myself)
to
`"C:\\Windows\\sysnative\\cmd.exe"` (which the comment above the setting says is the 64bit version)

Hope that's helpful with fixing this issue. I'll also point out again that I experienced this issue without a project folder opened at all, i.e. with only an empty unsaved document opened, so the presence of special chars didn't seem to be the cause of the issue on my system.

**Comment by Tyriar** [comment] 2016-09-12 02:52
@joseph-iussa double checked and setting to the 64-bit cmd doesn't fix this issue. Not sure what the problem was with opening the terminal with no open folder, doesn't reproduce on my machine.

**Comment by osnoser1** [comment] 2016-09-14 12:42
Not only special chars, i think that are all unicode characters.
My user folder is 'Alfonso Andrés'.
Windows 10.

**Comment by Dzienny** [comment] 2016-09-18 21:25
I encountered this problem today. I think I found the culprit. The vscode uses pty.js to open the terminal. https://github.com/Microsoft/vscode/blob/a6c845baf7fed4a186e3b744c5c14c0be53494fe/src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js (line: 30)

And on the pty.js project I found the following open issue: https://github.com/chjj/pty.js/issues/173

**Comment by Tyriar** [comment] 2016-09-18 21:42
@Dzienny yes it could be either pty.js or the dated winpty version it uses.

**Comment by the-ress** [comment] 2016-10-12 13:05
I've created a pull request with the fix here: chjj/pty.js#176

**Closed** 2016-10-12 19:26 UTC
Labels: bug, help wanted, integrated-terminal, upstream, windows

**Comment by Tyriar** [comment] 2016-10-12 19:28
Fixed thanks to @the-ress's pull request! You can try this out in the [Insiders build](https://code.visualstudio.com/insiders) tomorrow or in stable v1.7.

**Comment by srcnalt** [comment] 2016-11-22 13:46
I am facing this error on Linux Solus. No special character on file dir. When I try to compile code (alt+enter) F# Interactive console appears for a moment then I get this error message.

**Comment by Tyriar** [comment] 2016-11-22 19:03
@srcnalt make sure you're on the latest version, if you still experience the issue please file a new one via Help > Report Issues :smiley:

**Comment by uetoyo** [comment] 2017-03-11 16:03
O have the same issue:

**Comment by dfilaretti** [comment] 2017-04-27 21:14
Exact same problem here with Ionide on windows 10. Have tried on windows 7 and it works.
Do not have any accents or special chars.

**Comment by devmattrick** [comment] 2017-11-01 03:19
Sorry to bump, but I'm not sure if this is related.

When I run `rollup -w` I get the "The terminal process terminated with exit code" error, but the error code is 259, strangely. Running it in git bash outside of VSCode works fine, but the integrated terminal crashes without fail.
