### ISSUE TITLE
terminal doesn't focus when I press ctrl-` to open it

### ISSUE THREAD

**Issue by JasonWoof** [microsoft/vscode#128351] opened 2021-07-09 20:25 UTC
Issue Type: <b>Bug</b>

as of this latest version, the first time I open a terminal at the bottom by pressing ctrl-` (control + backtick) the keyboard focus does not go into the terminal, so when I type it's still editing my document. Pressing ctrl-` more times does nothing (it neither focuses the terminal nor hides it.) If I click into the terminal pane, then the key combo starts to work again: I can then ctrl-` to close the terminal, and then hit it again to re-open-and-focus the terminal. If I exit the terminal with ctrl-d then it goes back to the buggy behavior again as described above.

This bug is new as of the latest version update.

Further details: I looked in the keybinding settings UI, and the only keybind it had for ctrl-` was to close the terminal (it had a when expression of "terminal.active"). I tried adding a keybinding for ctrl-` to trigger "Terminal: Focus on Terminal View" when "!terminal.active" but that didn't change the behavior of anything I could see (I tried all the reproduce steps described above.)

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:53:55.113Z)
OS version: Linux x64 5.10.0-8-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 955)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|7.43GB (0.15GB free)|
|Process Argv|dev/allinadayswork --crash-reporter-id f6b33f70-d5ce-4dff-b30a-dafea807859e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.16.1
vscode-docker|ms-|1.14.0
remote-containers|ms-|0.187.0
cpptools|ms-|1.5.1
svelte-vscode|sve|105.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehovct:30309550
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by IllusionMH** [comment] 2021-07-09 21:50
Probably duplicate of #128255

**Comment by iamCristYe** [comment] 2021-07-12 02:27
dup of https://github.com/microsoft/vscode/issues/128255

**Closed** 2021-07-12 21:17 UTC
Labels: new release
