### ISSUE TITLE
Auto-save workspace to restore active files in editor (after improper application exit)

### ISSUE THREAD

**Issue by zhuhang-jasper** [microsoft/vscode#80760] opened 2019-09-12 02:40 UTC
Right now, VSCode workspace will not auto save, and only will be saved upon user exit the application properly.

* workspace refers to active files/views in the editor

In the case of PC restart or VSCode force close, the workspace will not be saved. Therefore, after starting VSCode again, the active files in editor are not the ones last opened, they are the ones that were last opened on previous proper exit.

**Comment by usernamehw** [comment] 2019-09-12 05:27
Duplicate of #12058

**Closed** 2019-09-12 07:36 UTC

**Comment by zhuhang-jasper** [comment] 2019-09-17 05:21
> Duplicate of #80032

Ermm, still don't think so.
#80032 is about using the workspace file across different platforms when being moved to another machine.

What I am saying is auto-saving this workbench file.
I have no idea why you kept thinking its duplicate?? Is my English too difficult to understand?

**Comment by bpasero** [comment] 2019-09-17 05:33
@zhuhang-jasper I find it is a duplicate.

You say:

> In the case of PC restart or VSCode force close, the workspace will not be saved. workspace refers to active files/views in the editor

https://github.com/microsoft/vscode/issues/80032 says:

> Can a workspace save open files (maybe including the view). So it would be possible to open a workspace and continue working with the open files from last session.

**Comment by zhuhang-jasper** [comment] 2019-09-17 06:01
> #80032 says:
> 
> > Can a workspace save open files (maybe including the view). So it would be possible to open a workspace and continue working with the open files from last session.

This behaviour is already implemented in the current VSCode. RIGHT NOW, u indeed can already open a workspace and continue working with open files from last session.
And you yourself @bpasero replied at that point of time:
> > @N7K4 every opened file is associated with a workspace, can you provide steps where this does not work?

And then author explained his true intentions on cross-platform portability:
>> On the local machine you are right. But when I use a workspace file under source control or I want to share it with a team member (on a different machine) all files are not listed.

I'm frustrated to repeat myself again for the 4th time:
My intention is to add "auto-save" feature for workspace file.
Benefit: In case of VSCode accidental termination, not all changes to workspace are lost.

Let me update my original issue to include what I mentioned in, and hopefully its more clear.
https://github.com/microsoft/vscode/issues/80760#issuecomment-532063365

**Comment by bpasero** [comment] 2019-09-17 06:22
@zhuhang-jasper I think this ends up to be a combination of https://github.com/microsoft/vscode/issues/12058 and https://github.com/microsoft/vscode/issues/80032 right? Basically everytime UI state changes (this includes the list of opened files), this state is being persisted into the code workspace file.

Today, state is not persisted periodically (only on shutdown) and it is also not persisted into the workspace file.

**Comment by zhuhang-jasper** [comment] 2019-09-17 06:26
> Today, state is not persisted periodically (only on shutdown) and it is also not persisted into the workspace file.

Really? I thought the opened files are already persisted in the workspace file.
Because right now when you open a workspace, the opened files will be restored correctly.

**Comment by bpasero** [comment] 2019-09-17 06:35
@zhuhang-jasper they are persisted but not within the `.code-workspace` file. Just open it and check the contents. My understanding from your issue was that you want to save it within that file.

We store this state in some %APPDATA% folder together with all the other state.

**Comment by zhuhang-jasper** [comment] 2019-09-17 06:39
> @zhuhang-jasper they are persisted but not within the `.code-workspace` file. Just open it and check the contents. My understanding from your issue was that you want to save it within that file.
> 
> We store this state in some `%APPDATA%` folder together with all the other state.

You are right. 
If its not currently persisted in the workspace file, then auto-saving doesn't help.
The other 2 issues are sufficient. Thanks for clarification.
