### ISSUE TITLE
VS Code does not open default profile shell on startup

### ISSUE THREAD

**Issue by aileak** [microsoft/vscode#132239] opened 2021-09-03 10:04 UTC
Issue Type: <b>Bug</b>

1. Select Git Bash as default profile
2. Open 1 Git Bash terminal
3. Close VS Code
4. Open VS Code
5. It opens PowerShell on startup, instead of Git Bash or any other shell

VS Code version: 1.60.0
OS version: Windows 10

**Comment by IllusionMH** [comment] 2021-09-03 10:33
/duplicate of #128763 (reproducible not only for remote)

**Closed** 2021-09-03 10:33 UTC
Labels: *duplicate, new release
