### ISSUE TITLE
No preview of markdown within block comments in JS/TS code

### ISSUE THREAD

**Issue by narkowicz** [microsoft/vscode#85571] opened 2019-11-26 02:33 UTC
Issue Type: <b>Bug</b>

Inline preview rendering of markdown content within block comments in JavaScript and TypeScript files is missing.

This appears to be a regression introduced in VS Code 1.40.x (still present in Insiders) that I couldn't find referenced in the change log? Feature made for happier reading and writing formatted TSDoc / JSDoc comments.

Steps to reproduce:

1. Create a new document, set language mode to TypeScript or JavaScript.

2. Paste the following code:
```
/**
 * This block comment used to render markdown formatting inline, such as:
 * **bold**, _italic_, `inline code` and...
 * 
 * ```ts
 * // Syntax highlighted code blocks
 * const example = print('hello');
 * ```
 */
```

3. Expect the markdown within the code block to be formatted, but it is not

Repeating steps in Visual Studio Code 1.39.2 correctly renders preview of markdown within the block comment.

Screenshot shows Insiders top, Code 1.39.2 below:
![Screen Shot 2019-11-26 at 1 32 13 pm](https://user-images.githubusercontent.com/390358/69594685-396c0f80-1051-11ea-93da-db0b56af76f6.jpg)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.41.0-insider (abbf52b1378e2976803f81b1317fe3a5e6e39c23, 2019-11-25T10:09:34.712Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment] 2019-11-26 03:32
Duplicate of #85187

This extension now provides JSDoc markdown highlighting: https://marketplace.visualstudio.com/items?itemName=bierner.jsdoc-markdown-highlighting

**Closed by mjbvz** 2019-11-26 03:32 UTC
