### ISSUE TITLE
Editor: Arrow key doesn't work

### ISSUE THREAD

**Issue by s-masashi** [Microsoft/vscode#24645] opened 2017-04-13 00:10 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.51-40.58.amzn1.x86_64
- Extensions: none
---

Quite simple but serious problem.
Around version 1.11, editor window doesn't accept any arrow key at all!
I tried clean reinstall, however, it doesn't solve this symptom.

Steps to Reproduce:

1. Install Visual Studio Code
2. Open a file, type some characters, and press arrow keys to move around.

I'm using LXDE desktop on Ubuntu 16.
Special things are this environment is on TigerVNC virtual desktop prepared with Docker container version of Ubuntu.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by alexandrudima** [comment] 2017-04-13 07:41
Duplicate of #24107 -- the latest insiders build already contains a fix

**Closed by alexandrudima** 2017-04-13 07:41 UTC
