### ISSUE TITLE
[Markdown] Formulas are not highlighted when put beside a non-whitespace character

### ISSUE THREAD

**Issue by YVVT** [microsoft/vscode#170943] opened 2023-01-10 09:04 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 11 22h2

Steps to Reproduce:

1. Create a `.md` file
2. Copy & paste the following content into the file

```md
这是一个公式$sin^2(x)+cos^2(x)=1$
$sin^2(x)+cos^2(x)=1$
```

Expected behavior:

Both formulas should be highlighted.

Actual behavior:

Only the formula in line 2 is highlighted, while the one in line 1 is not.

![image](https://user-images.githubusercontent.com/62426149/211507768-d5d24207-def0-4c35-be0b-50e8a0f0ebb2.png)

**Comment by danilhendrasr** [comment] 2023-01-12 14:00
Hi, I would like to try resolving this issue.
Any pointer where in the codebase should I be taking a look at?

**Comment by Raj1998** [comment] 2023-01-23 16:59
From my initial debugging, it seems the problem is coming from https://github.com/microsoft/vscode-textmate library. @mjbvz can you confirm this?

**Comment by mjbvz** [comment] 2023-01-23 17:56
That library runs the grammars to do the highlighting. The actual grammar is in:

https://github.com/microsoft/vscode/blob/8aee3a2c503fe730d3112f7b66a7a9c569df5f06/extensions/markdown-math/syntaxes/md-math-inline.tmLanguage.json

With tests in:

https://github.com/microsoft/vscode/blob/559e9beea981b47ffd76d90158ccccafef663324/extensions/vscode-colorize-tests/test/colorize-fixtures/md-math.md

**Comment by danilhendrasr** [comment] 2023-01-28 01:47
Thank you for the pointer, I'll look into it.

**Comment by danilhendrasr** [comment] 2023-01-28 08:11
Does the formula also has to be highlighted when it's followed by word characters (e.g. `这是一个公式$sin^2(x)+cos^2(x)=1$asdf`) @mjbvz ? Because it seems doing so breaks some of the tests.

**Closed** 2023-02-01 00:00 UTC
Labels: bug, markdown, editor-highlight, notebook-math
