### ISSUE TITLE
Auto-import adds backslash to `}`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#152333] opened 2022-06-16 13:58 UTC
https://user-images.githubusercontent.com/5047891/174086606-3fccfc5e-0d2b-4868-a7b3-c6e6410607cd.mp4

**Comment by Dovernh** [comment] 2022-06-16 14:56
it also occurs when you select "Declare Method" from the "light bulb"

**Comment by mjbvz** [comment] 2022-06-16 15:12
Duplicate of #152272 

/cc @jrieken

**Closed by mjbvz** 2022-06-16 15:12 UTC

**Comment by duncan-faulkner** [comment] 2022-06-16 15:19
also adds slash on save
