### ISSUE TITLE
Debugging on MacOS - When will we get it?

### ISSUE THREAD

**Issue by johnvpetersen** [Microsoft/vscode#3757] opened 2016-03-06 23:50 UTC
I posted this issue on the ASP.NET Project:

https://github.com/aspnet/Mvc/issues/4236#issue-138848669

When can we expect to be able to debug server side code on the Mac?

JP

**Comment by egamma** [comment] 2016-03-07 09:01
Duplicate of # 275, see also this comment https://github.com/Microsoft/vscode/issues/275#issuecomment-192967125

**Closed by egamma** 2016-03-07 09:01 UTC
