### ISSUE TITLE
Block select + wrapped text + insert alters wrapped lines, not "real" lines

### ISSUE THREAD

**Issue by jonpryor** [microsoft/vscode#94228] opened 2020-04-01 23:41 UTC
Issue Type: <b>Bug</b>

1. Create a new Plain Text document.
2. Within (1), create a very long line, *longer than the window width*.
3. Copy (2) at least three times.

    For example:

    ```
    This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. 
    This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. 
    This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. This is a very long line. 
    ```

4. Enable word wrap: ⌥ Z.  Each line should wrap, as each line is longer than the window width.
5. Hold down ⌥ + ⇧, click row 1 column 1, and drag down to row 3 column 1.
6. Type `x x x `.

**Expected results**: `x x x ` should appear *three times*, once per line.

**Actual results**: `x x x ` appears on every "word wrapped line".  If word wrap is disabled via ⌥ Z after step (6), `x x x ` is visible multiple times *within* lines 1 & 2, instead of just at the beginning of each line.

This is particularly annoying when editing Markdown documents, as word wrap appears to be enabled by default.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:41.240Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz (24 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|96.00GB (1.66GB free)|
|Process Argv|-n . src/Utilities/ToolLocationHelper.cs|
|Screen Reader|no|
|VM|7%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
shell-format|fox|7.0.1
vscode-test-explorer|hbe|2.17.0
csharp|ms-|1.21.16
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.0
mono-debug|ms-|0.15.8
wordcount|ms-|0.1.0
java|red|0.59.0
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2
vscode-nxunit-test-adapter|wgh|0.1.3
markdown-pdf|yza|1.4.4
t4-support|zbe|0.4.3

</details>

**Comment by alexdima** [comment] 2020-04-02 09:32
Duplicate of #26393

**Closed by alexdima** 2020-04-02 09:32 UTC
