### ISSUE TITLE
"Select for Merge" almost like Compare

### ISSUE THREAD

**Issue by Montago** [Microsoft/vscode#62016] opened 2018-10-29 07:35 UTC
I'm working with a local copy of the template files used in production.... 

in this organization, we have people who edit directly in the production files ... crazy i know, right ? 

anyways - i'm developing using my local templates and sometimes need to sync with production. 

Therefore it would be awesome if i could use the Merge tool to make both files equal . 

eg: "Select for Merge A + B " .. then go through the merge procedure..  afterwords the output of the merge is then overwriting both files. 

this would make life so much easier for me, and everyone else who occasionally need to sync files

**Comment by Montago** [comment] 2018-10-29 07:39
Seems to be a duplicate / alternate version of https://github.com/Microsoft/vscode/issues/25887

**Comment by weinand** [comment] 2018-10-29 07:44
duplicate of #25887

**Closed** 2018-10-29 07:44 UTC
Labels: *duplicate
