### ISSUE TITLE
Suggest widget takes wrong suggestion

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#116764] opened 2021-02-16 11:13 UTC
1. Open `listWidget.ts`
2. Delete line 7: `import { IDisposable, dispose, DisposableStore } from 'vs/base/common/lifecycle';`
3. Go to line 108, put cursor at the end of `IDisposable`, trigger Suggest, pick the one coming from `.../lifecycle`

🐛 Notice line 29 now says `import { IDisposable } from 'vs/workbench/workbench.web.api';`

![recording (13)](https://user-images.githubusercontent.com/22350/108055521-f22abf80-7004-11eb-91f2-d1af5f6e3dab.gif)

**Comment by joaomoreno** [comment] 2021-02-16 15:01
Just hit this again, it's very annoying.

**Comment by mjbvz** [comment] 2021-02-16 20:25
Duplicate of https://github.com/microsoft/TypeScript/issues/42752

**Comment by joaomoreno** [comment] 2021-05-11 09:05
I keep hitting this @mjbvz and now I see this is closed upstream....

**Closed** 2021-05-12 01:20 UTC
Labels: bug, typescript
