### ISSUE TITLE
CSS intellisense add extra colon (again)

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#18340] opened 2017-01-09 20:24 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (12af9ea6effefeaeecde2107c960ae5222703864, 2017-01-09T07:05:32.550Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.2.0|
|code-settings-sync|Shan|2.4.2|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.1|
|project-manager|alefragnani|0.12.2|
|vscode-angular-files|alexiv|1.3.7|
|one-monokai|azemoh|0.2.4|
|vscode-icontheme-nomo-dark|be5invis|1.2.4|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|tslint|eg2|0.7.1|
|vscode-great-icons|emmanuelbeziat|1.1.36|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|10.2.0|
|ftp-sync|lukasz-wronski|0.3.2|
|HTMLHint|mkaufman|0.3.3|
|vscode-csscomb|mrmlnc|4.0.0|
|vscode-postcss-sorting|mrmlnc|2.1.0|
|vscode-stylefmt|mrmlnc|2.2.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.17|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|6.0.0|
|stylelint|shinnn|0.21.2|
|darcula-extended|smlombardi|1.1.2|
|theme-tesla|smlombardi|5.3.10|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

This issue: https://github.com/Microsoft/vscode/issues/15586

Has regressed in one of the latest Insiders builds, after being fixed for a while.

**Comment by aeschli** [comment] 2017-01-10 03:39
@smlombardi I can't reproduce this with the steps for #15586:
- type a css selector, e.g. .pb-font
- type a colon, invoke code assist
- type bef to scroll to ::before
- choose it

Tested in css and scss and I get `.pb-font::before` which is the expected result.

Please add your steps to reproduce. Also try this with all extensions disabled.

**Comment by aeschli** [comment] 2017-01-19 09:35
Closing. Please reopen with steps...

**Closed by aeschli** 2017-01-19 09:35 UTC
Labels: css-less-sass

**Comment by smlombardi** [comment] 2017-02-01 13:28
@aeschli See attached:

![feb-01-2017 08-27-06](https://cloud.githubusercontent.com/assets/835148/22508511/547f739e-e858-11e6-999d-3a5303fc0cf4.gif)

**Comment by aeschli** [comment] 2017-02-01 14:58
Thanks, that's a dup of #17726 (I assume that's SCSS)

**Comment by smlombardi** [comment] 2017-02-01 15:36
Yes.
