### ISSUE TITLE
textDocument/codeAction request has end character set as 1.7976931348623157E+308

### ISSUE THREAD

**Issue by rjmholt** [microsoft/vscode#80288] opened 2019-09-03 21:35 UTC
From https://github.com/powershell/vscode-powershell/issues/2135.

- VSCode Version: 1.37.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

See ![GIF](https://user-images.githubusercontent.com/18121861/63850627-305d9a80-c99d-11e9-96c3-cbc6ff50153c.gif).

Does this issue occur when all extensions are disabled?: No -- need an extension for a CodeLens

We've been looking into this on the PowerShell extension side, but see this message in the logs:

```json
    {
      "jsonrpc": "2.0",
      "id": 8,
      "method": "textDocument/codeAction",
      "params": {
        "textDocument": {
          "uri": "file:///c%3A/Users/Keith/.vscode/extensions/ms-vscode.powershell-2019.5.0/examples/2135_Repro.Tests.ps1"
        },
        "range": {
          "start": {
            "line": 2,
            "character": 8
          },
          "end": {
            "line": 2,
            "character": 1.7976931348623157E+308
          }
        },
        "context": {
          "diagnostics": []
        }
      }
    }
```

This value for `range.end.character` causes the extension to crash, but there's not much sane we can do with it. It's equal to `Number.MAX_VALUE` in JS.

**Comment by mjbvz** [comment] 2019-09-09 16:51
Can you please write out the steps to reproduce this (instead of a gif)

**Comment by rjmholt** [comment] 2019-09-10 22:33
- Install the powershell-preview extension to provide [this problem matcher](https://github.com/PowerShell/vscode-powershell/blob/c15f9dc6716f36f194cb84663177963c638b52e5/package.json#L290-L308)
- Ensure PowerShell is installed
- Install Pester (`Install-Module Pester` in PowerShell)
- Create `foo.ps1`:

```powershell
Describe "Repro" {
    It "Test" -Test {
        3 % 2 | Should -BeExactly 0
    }
}
```

- Add the following to the `tasks.json`:

```json
{
    "label": "Test",
    "type": "shell",
    "command": "Invoke-Pester -PesterOption @{IncludeVSCodeMarker=$true}",
    "group": {
        "kind": "test",
        "isDefault": true
    },
    "problemMatcher": [
        "$pester"
    ]
},
```

- In the Command Palette, run `Tasks: Run Test Task`
- When a red squiggle appears under the test, click on `QuickFix` (some users hit this with only a hover over the red squiggle)

Pester writes an output to stdout and VSCode parses this. This output provides a line, but not a column. VSCode highlights this line, but then sends `Number.MAX_VALUE` as the column end character to our language server, which is too big to be deserialised as a fixed-width integer (e.g. a `long`). A value like `Number.MAX_SAFE_INTEGER` would work just as well here (that many characters represents ~8000 TiB) but wouldn't require arbitrary precision integers (which require allocation or special handling at the deserialisation layer) in languages where numbers are not all floating point.

I appreciate that the LSP spec specifies this value as a number not an integer, but I feel that a  floating point number of characters (which `Number.MAX_VALUE` is, since `Number.MAX_VALUE === Number.MAX_VALUE + 1`) isn't meaningful or useful to send to servers.

**Comment by mjbvz** [comment] 2019-10-25 23:46
Just got around to looking into this but I can't reproduce the diagnostic showing up:

![Screen Shot 2019-10-25 at 4 44 26 PM](https://user-images.githubusercontent.com/12821956/67610325-bea88f80-f746-11e9-8031-454806f039c1.png)

@rjmholt Are there any extra steps required here? I'm not a heavy powershell/windows user so its possible my machine is not configured properly

**Comment by mjbvz** [comment] 2019-10-31 00:10
@rjmholt Any details on reproducing this?

**Comment by mamidenn** [comment] 2019-10-31 08:04
@mjbvz Please try renaming `foo.ps1` to `foo.Tests.ps1` and reproduce as described above.

![80288](https://user-images.githubusercontent.com/4650305/67929288-40704100-fbbd-11e9-9064-e71b9c2d3f92.gif)

**Comment by rjmholt** [comment] 2019-10-31 17:35
> Any details on reproducing this?

Sorry, lost the original notification!

> Please try renaming foo.ps1 to foo.Tests.ps1 and reproduce as described above.

Ah, yes, please give that a try.

The issue itself lies in how the problem matcher handles not being given a column, so if that doesn't work I might be able to craft a more minimal scenario (that will just take time).

**Comment by mjbvz** [comment] 2019-11-14 06:49
Now I can run the test but I don't see any problem squiggles in `foo.Test.ps1`:

<img width="1414" alt="Screen Shot 2019-11-13 at 10 48 09 PM" src="https://user-images.githubusercontent.com/12821956/68833173-b2d62c00-0667-11ea-8184-10f7f8d95da4.png">


Instead, it is highlighting the error in `Should.ps1`:

<img width="554" alt="Screen Shot 2019-11-13 at 10 48 41 PM" src="https://user-images.githubusercontent.com/12821956/68833223-ce413700-0667-11ea-8d88-3a31f6daee89.png">

**Comment by mamidenn** [comment] 2019-11-18 08:30
It appears you are running an old version of Pester (3.4.0 - latest is 4.9.0), which does not yet have `-BeExactly`. You could try updating Pester using `Update-Module Pester`.

Or you could try adapting `foo.Tests.ps1` to be
```powershell
Describe "Repro" {
    It "Test" -Test {
        3 % 2 | Should -Be 0
    }
}
```
I was able to reproduce the issue using Pester 3.4.0 and the above script.

Thanks for keeping it up 😃!

**Comment by mjbvz** [comment] 2019-11-20 00:31
Thanks. I can finally repo this.

The root cause seems to be that the marker itself (the problem) has an invalid range. The code action itself just surfaces this range. I confirmed that the marker service is storing a marker that has an endColumn value of `1.7976931348623157e+308`

This comes from the `problemMatcher`: https://github.com/microsoft/vscode/blob/d5386d323342076c82a0e2331df5c603d980f059/src/vs/workbench/contrib/tasks/common/problemMatcher.ts#L383

So if the problem matcher returned the end column, this wouldn't happen. I think I can also fix the code action provider to clip the range before  passing it on however

**Comment by mjbvz** [comment] 2019-11-20 01:20
Made a fix but the Powershell extension still seems to crash when requesting the code actions. I  confirmed that we are passing a more sane range now however

**Comment by rjmholt** [comment] 2019-11-20 04:05
Not surprised we still crash; we're quite sensitive to line offsets.

But if the crash is happening after deserialisation, we're in business.

**Comment by aeschli** [comment] 2019-12-05 16:03
@rjmholt If you can verify the fix works for you that would be great. Set the verified label if it does, or reopen.

**Comment by jrieken** [comment] 2019-12-06 10:46
@mjbvz Are there verification steps?

**Comment by JacksonKearl** [comment] 2019-12-06 17:45
Still experiencing Powershell crashing with the above repro steps.

**Comment by mjbvz** [comment] 2019-12-06 17:48
As I noted, Powershell seems to still have a bug even after our fix. You verify this, either debug the code action code to confirm the right offset is used or see if the powershell extension has logging and confirm the right offsets are passed to it

**Comment by JacksonKearl** [comment] 2019-12-06 19:00
the correct offsets are not passed to the extension:
```ts
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value 1.79769313486232E+308 to type 'System.Int64'. Path 'params.range.end.character', line 1, position 233. ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Double.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)   
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, 
Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, 
Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty 
property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty 
property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerPropert
```

**Comment by TylerLeonhardt** [comment] 2019-12-06 19:09
@JacksonKearl can you set your log level to `Diagnostic` and [attach the logs here](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)?

**Comment by JacksonKearl** [comment] 2019-12-06 19:14
[EditorServices.log](https://github.com/microsoft/vscode/files/3933637/EditorServices.log)
[Start-EditorServices-EditorServices.log](https://github.com/microsoft/vscode/files/3933638/Start-EditorServices-EditorServices.log)
[vscode-powershell.log](https://github.com/microsoft/vscode/files/3933639/vscode-powershell.log)

**Comment by mjbvz** [comment] 2019-12-06 19:16
Here's the range i see on the VS Code side for the request:

![Screen Shot 2019-12-06 at 11 15 50 AM](https://user-images.githubusercontent.com/12821956/70349560-c8c7ae80-1819-11ea-8360-ff0b696b3ca2.png)

This is in the extensioHost in `extHostLanguageFeatures`

**Comment by mjbvz** [comment] 2019-12-06 19:25
@TylerLeonhardt In VS Code insiders can you see where the range it crashes on comes from. Is it getting passed in by the code action provider or is it from the diagnostic?

**Comment by TylerLeonhardt** [comment] 2019-12-08 04:34
@JacksonKearl sorry those are the wrong logs - the logs I'm looking for are here:

https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs

**Comment by TylerLeonhardt** [comment] 2019-12-08 04:44
@mjbvz 

[session.log](https://github.com/microsoft/vscode/files/3935866/session.log)

here's my log that vscode generates for the LSP communication. Drop this into [the inspector](https://microsoft.github.io/language-server-protocol/inspector/), scroll to the bottom, then click on the codeAction.

You'll see that vscode sends the language server:

```json
{
  "textDocument": {
    "uri": "file:///Users/tyleonha/Code/PowerShell/Misc/foo.Tests.ps1"
  },
  "range": {
    "start": {
      "line": 2,
      "character": 8
    },
    "end": {
      "line": 2,
      "character": 1.7976931348623157e+308
    }
  },
  "context": {
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 2,
            "character": 8
          },
          "end": {
            "line": 2,
            "character": 1.7976931348623157e+308
          }
        },
        "message": "Test",
        "severity": 1
      }
    ]
  }
}

```

**Comment by TylerLeonhardt** [comment] 2020-01-27 19:34
@mjbvz let me know if there's any other information you need but this seems to still be a bug in vscode. Unfortunately I don't think we can workaround this at this time.

**Comment by mjbvz** [comment] 2020-06-27 00:24
After snowplowing for like six iterations iterations, it's time to admit I'm not going to get around to this issue anytime soon. 

Marking as help wanted. @TylerLeonhardt It'd probably be best if someone from the Powershell extension could  investigate this. It may be a bug on the VS Code side but so far I've only seen reports of it effecting Powershell

**Comment by TylerLeonhardt** [comment] 2020-06-27 00:30
I mean this affects any language extension that uses:

https://github.com/OmniSharp/csharp-language-server-protocol

Which includes the ARM extension, the Razor, extension, and more.

Because that library tries to serialize the column into the int, but vscode defaults to some massive number outside of that range when it can't find a column.

If vscode defaulted to something within the range of int, this would resolve the issue.

**Comment by mjbvz** [comment] 2020-06-27 00:36
It would be helpful to have someone from any of effected extensions investigate this.

I don't deal with any of those languages/extensions regularly, so just setting up a repo for this bug is a big time sink. Someone with more knowledge of how these extensions are implemented should be able to pinpoint what is going wrong much more quickly

**Comment by TylerLeonhardt** [comment] 2020-06-27 00:41
Without knowing any of the code, I wonder if it has something to do at the serialization layer, when column is set to undefined

**Comment by TylerLeonhardt** [comment] 2020-06-27 21:56
@mjbvz the problem is this line:

https://github.com/microsoft/vscode/blob/04c36be045a94fee58e5f8992d3e3fd980294a84/src/vs/workbench/contrib/tasks/common/problemMatcher.ts#L383

It uses `Number.MAX_VALUE` which is `1.7976931348623157e+308` which isn't really safe to use since it just represents the largest value that javascript can "handle". `Number.MAX_SAFE_INTEGER` might be a better option because it represents `2^53 - 1` which is a 64bit integer... but that could cause problems with language servers that only use 32bit integers.

The best value for the default for this would be: 2^31-1, or 2,147,483,647 which is the largest 32bit integer.

I verified that setting that line to `2147483647` no longer throws an exception in the PowerShell language server. If you wanna verify it yourself, @rjmholt's steps are all you need to do: https://github.com/microsoft/vscode/issues/80288#issuecomment-530146364

@mjbvz how would you like to proceed here?

**Comment by mjbvz** [comment] 2020-06-29 22:07
Thanks for the investigation!

Adding @alexr00 for the problem matcher. Using a large number like `2^31-1` sounds reasonable

**Comment by TylerLeonhardt** [comment] 2020-06-30 02:21
It might be worth spot checking some of the other usages of `Number.MAX_INT` (I saw a few in the code) in favor of an max 32bit int constant used everywhere.

**Comment by alexr00** [comment] 2020-06-30 09:00
`2147483647` seems fine for the end character position. I'll make the change for the July iteration.

**Closed** 2020-07-08 11:38 UTC
Labels: bug, editor-code-actions, help wanted
