### ISSUE TITLE
Miscoloration caused by '?' at end of comment

### ISSUE THREAD

**Issue by mikeduffy** [Microsoft/vscode#56402] opened 2018-08-14 20:36 UTC
Issue Type: <b>Bug</b>

With extensions disabled, place the following three lines in a .ts file:
<pre>
  const a = 2 // tunable?
  console.log(`${a}`)
  const b = 3
</pre>
The third line will be miscolored by VS Code.  Adding a blank line after the first will correct the issue, as will removing the ${...} from the template string.

Here's an image of the problem: https://imgur.com/a/6wLJJv9

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_8259552|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
vscode-proto3|zxh|0.2.1

</details>

**Comment by mjbvz** [comment] 2018-08-20 10:39
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/646

**Closed by mjbvz** 2018-08-20 10:39 UTC
Labels: new release
