### ISSUE TITLE
VS code hangs when hovering over big string variable 

### ISSUE THREAD

**Issue by joelharkes** [Microsoft/vscode#39042] opened 2017-11-23 15:40 UTC
- VSCode Version: lastest
- OS Version: win-10-64bit

Steps to Reproduce:

Debug following code and hover over variable: `content` after it has been set.
```
const maxBytes = 1024 * 4096;
const content = Array(maxBytes + 2).join("a") ;
```

After 1-2 minutes you see te result: 
![image](https://user-images.githubusercontent.com/2960938/33180307-8bc33370-d06c-11e7-988a-d4075d5cb290.png)

Ok i know its not a good idea to have such big strings but, I think it might be nicer experience to only show the first n (say 100) characters and end with .... or some other visual way to say there is more content in variable.

Reproduces without extensions: Untested, pretty sure it does.

**Comment by weinand** [comment] 2017-11-23 15:42
which version of node.js are you using?

**Comment by joelharkes** [comment] 2017-11-23 19:29
9.0.0

**Comment by roblourens** [comment] 2018-02-09 06:39
I should trim values after some length like you suggest. Does node-debug have a limit like this?

@isidorn any thoughts on what the limit should be, or should I see how far I can push it?

**Comment by isidorn** [comment] 2018-02-09 10:13
@roblourens we do not have a limit in the hover on the vscode side since we show a scroll bar.
We do have a limit for a value length in the viewlet, and that is 1024 characters. Which seems unrelated to this problem.

Because we do not have a limit on the vscode hover side I would suggest to try out how far you can push it.

**Comment by joelharkes** [comment] 2018-02-09 20:49
It's just a minor issue, probably not many people get. I just registered it since I saw it.

Maybe check if the hang/delay is UI related or debugger-data related, if the latter maybe ignore trying to fix this.

**Comment by roblourens** [comment] 2018-02-10 03:26
Testing with 1 MB instead of 4, the whole time is spent on browser layout:

![image](https://user-images.githubusercontent.com/323878/36058096-c3500e28-0dcd-11e8-8af0-685651c1577e.png)

Given that, any limit should probably be added on the frontend. 256 kb takes a couple seconds to show up on my relatively fast macbook. Something around there might be a good limit, I can't imagine anyone wanting to scroll through that much text in a hover.

**Comment by isidorn** [comment] 2018-02-14 09:44
On my 4 year old mac book pro it takes 30 seconds to show the results in hover and then the user can nicely inspect them.
I do not want to put a limit until some users hits hits without trying to hit it by creating a max string.
Also the worse behavior is not that bad imho

Closing as designed

**Closed by isidorn** 2018-02-14 09:44 UTC
Labels: debug, under-discussion
