### ISSUE TITLE
Download Extensions

### ISSUE THREAD

**Issue by Sariln** [Microsoft/vscode#63934] opened 2018-11-28 16:42 UTC
Issue Type: <b>Feature Request</b>

It should have download progress bar or download complete percent when downloading extension, Thank you.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment] 2018-11-29 10:06
Duplicate of #30143

**Closed by sandy081** 2018-11-29 10:06 UTC
Labels: extensions
