### ISSUE TITLE
Electron 2.0.x: characters render duplicated when opacity is used in editor

### ISSUE THREAD

**Issue by ggovan** [Microsoft/vscode#52196] opened 2018-06-18 12:58 UTC
Issue Type: <b>Bug</b>

In a JS or TS file create an unused import `import * as unused from 'somewhere'`

The editor then reads

```
import **asaunused from 'somewhere';
```

The text when copy and pasted is correct. The DOM looks correct. removing the opacity of the `&nbsp` elements fixes the issue.

![image](https://user-images.githubusercontent.com/18617844/41537191-9e3451fc-72ff-11e8-9c2e-f7586b83dac0.png)

VS Code version: Code - Insiders 1.25.0-insider (c51cf862a9604dffe2e3e8792a4b0a45213869a3, 2018-06-18T08:50:30.859Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (5.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by mjbvz** [comment] 2018-06-18 20:57
So if you paste `import * as unused from 'somewhere'` in to an editor, the text looks corrupted?

Can you please share you user configuration. Have you configured a font for example?

**Comment by ggovan** [comment] 2018-06-19 09:14
Here is my user config. I get the same issue if I remove the `zoomLevel`.

```
{
    "window.zoomLevel": -1,
    "todohighlight.isCaseSensitive": false,
    "todohighlight.include": "{**/*.cs,**/*.jsx,**/*.ts,**/*.html,**/*.php,**/*.css,**/*.scss}",
    "vsicons.dontShowNewVersionMessage": true,
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "Solarized Light",
    "java.home": "C:\\Program Files\\Java\\jdk1.8.0_131",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "java.errors.incompleteClasspath.severity": "ignore",
    "diffEditor.ignoreTrimWhitespace": false,
}

**Comment by mjbvz** [comment] 2018-06-19 16:36
@alexandrudima @rebornix Any thoughts on this issue? I haven't been able to repo it

**Comment by ggovan** [comment] 2018-06-20 08:15
Sorry wrong, button.

I meant to say that I have tried this on another machine with the same setup and was unable to reproduce it. But on my main machine it is consistent across multiple projects and restarts.

**Comment by alexandrudima** [comment] 2018-06-20 08:27
I am also not able to reproduce.

**Comment by joaomoreno** [comment] 2018-06-21 07:56
Just reproduced it! 🎆 

Paste these contents in a .ts file:

```ts
function foo() {
    const a = `hdshhdasha;
    return `hello`;
}
```

And have this tsconfig.json:

```json
{
    "compilerOptions": {
        "noUnusedLocals": true
    }
}
```

A mysterious `a` creeps out from under the shadows!!! 😨 

![image](https://user-images.githubusercontent.com/22350/41705488-63e2d910-7539-11e8-90c4-190e22126a18.png)

**Comment by joaomoreno** [comment] 2018-06-21 08:05
OK, what.

It doesn't repro with `--disable-gpu`. My graphics card specs are:

```
Intel Iris Pro:

  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0d26
  Revision ID:	0x0008
  Metal:	Supported, feature set macOS GPUFamily1 v3
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
```

@ggovan What's your graphics card?

**Comment by ggovan** [comment] 2018-06-21 08:17
Good to see it's not just me.

```
Name	- Intel(R) HD Graphics 4600
PNP Device ID	- PCI\VEN_8086&DEV_0412&SUBSYS_05A41028&REV_06\3&11583659&0&10
Adapter Type	- Intel(R) HD Graphics Family, Intel Corporation compatible
Adapter Description	- Intel(R) HD Graphics 4600
Adapter RAM	 - 1.00 GB (1,073,741,824 bytes)
Installed Drivers	- igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll
Driver Version -	20.19.15.4531
INF File	- oem76.inf (iHSWD_w10 section)
Colour Planes- Not Available
Colour Table Entries -	4294967296
Resolution	- 1680 x 1050 x 59 hertz
Bits/Pixel -	32
Memory Address	- 0xF7800000-0xF7BFFFFF
Memory Address	- 0xE0000000-0xEFFFFFFF
I/O Port	- 0x0000F000-0x0000F03F
IRQ Channel - IRQ 4294967290
I/O Port	- 0x000003B0-0x000003BB
I/O Port	- 0x000003C0-0x000003DF
Memory Address	- 0xA0000-0xBFFFF
Driver	- c:\windows\system32\drivers\igdkmd64.sys (20.19.15.4531, 7.61 MB (7,974,904 bytes), 22/02/2017 00:31)
```

**Comment by joaomoreno** [comment] 2018-06-21 09:42
@ggovan Can you reproduce with `--disable-gpu`?

**Comment by ggovan** [comment] 2018-06-21 09:49
Everything works fine when I `--disable-gpu`.

**Comment by alexandrudima** [comment] 2018-06-21 10:35
@chrmarti does this work fine for you when running with `--disable-gpu` ?

**Comment by chrmarti** [comment] 2018-06-21 14:43
To reproduce in Electrom:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
<style>
  .squiggly-inline-unnecessary {
  opacity: 0.6;
}
.view-line {
  font-family: "Monaco";
    font-weight: normal;
    font-size: 14px;
    line-height: 21px;
    letter-spacing: 0px;
}
  </style>
<div style="top:21px;height:21px;" class="view-line"><span><span class="mtk1">&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="mtk5 squiggly-inline-unnecessary">const</span><span class="mtk1 squiggly-inline-unnecessary">&nbsp;</span><span class="mtk13 squiggly-inline-unnecessary">a</span><span class="mtk1 squiggly-inline-unnecessary">&nbsp;</span><span class="mtk17 squiggly-inline-unnecessary">=</span><span class="mtk1 squiggly-inline-unnecessary">&nbsp;</span><span class="mtk9 squiggly-inline-unnecessary">`hdshhdasha;</span></span></div>

    <h1>Hello World!</h1>
    <!-- All of the Node.js APIs are available in this renderer process. -->
    We are using Node.js <script>document.write(process.versions.node)</script>,
    Chromium <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.

    <script>
      // You can also require other files to run in this process
      require('./renderer.js')
    </script>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/9205389/41726379-4994972c-7572-11e8-9063-cda99f13d350.png)

**Comment by alexandrudima** [comment] 2018-06-21 15:05
I've created https://github.com/electron/electron/issues/13367 against Electron

**Comment by ggovan** [comment] 2018-07-11 13:00
I no longer have this issue on 1.26.0-insider (Commit: bbafa06a3d3db60bbd06d4d4cd582586f7126d93 Date: 2018-07-09T05:49:15.364Z).

I'm happy for this tobe closed.

**Comment by bpasero** [comment] 2018-07-12 13:53
@alexandrudima @rebornix since I cannot find a correlating issue at Chrome so far, I am thinking of a workaround we could apply in VSCode. Looks like adding `will-change: transform;` to the `.squiggly-inline-unnecessary` class fixes it, but the implications are not entirely clear to me (other than knowing that Chrome will put the elements matching this class on a separate layer for painting). 

Also, I wonder if there could be another case where this hits us in the editor that we did not discover yet, e.g. is there another case where we combine `&nbsp;` with `opacity` and monospace fonts.

**Comment by Tyriar** [comment] 2018-07-18 21:19
Moving to Chromium v63's version of skia appears to have fixed the issue (@deepak1556 put a build together for me to test).

Before:

<img width="274" alt="screen shot 2018-07-18 at 2 07 53 pm" src="https://user-images.githubusercontent.com/2193314/42908352-8f2679da-8a95-11e8-9d27-4593d7c74e47.png">

After:

<img width="399" alt="screen shot 2018-07-18 at 2 10 02 pm" src="https://user-images.githubusercontent.com/2193314/42908354-91596c4e-8a95-11e8-9c0e-58720fdc9949.png">

Tested on mid 2014 mac with Intel Iris Pro 1536 MB.

**Comment by bpasero** [comment] 2018-08-06 08:46
We pushed a workaround using `will-change:opacity` for these.

**Closed by bpasero** 2018-08-06 08:46 UTC
Labels: bug, electron, electron-2.0.x-update, electron-blocker
