### ISSUE TITLE
timeout after 1000 ms

### ISSUE THREAD

**Issue by ati0ns** [microsoft/vscode#103105] opened 2020-07-22 15:30 UTC
- VSCode Version: I do not know.
- OS Version: What is this ?

Steps to Reproduce:

1. Start the debugger.
2. Stop it.

Does this issue occur when all extensions are disabled?: Yes/No
Probably.

![image](https://user-images.githubusercontent.com/35779030/88196034-05c5a180-cc41-11ea-9b35-f8e9df37cb6f.png)

**Comment by weinand** [comment] 2020-07-22 16:23
/needsMoreInfo

If you use the "Report Issue" command from VS Code's Help menu, it will automatically fill in the version number and OS information into the issue.

What debugger are you talking about?

**Comment by gjsjohnmurray** [comment] 2020-07-22 22:22
Mentioned by @joaomoreno in https://github.com/microsoft/vscode/issues/100368#issuecomment-662316618

**Comment by ati0ns** [comment] 2020-07-23 08:30
![image](https://user-images.githubusercontent.com/35779030/88266395-73b8aa00-cccf-11ea-93d8-83d38fe5e1fa.png)
![image](https://user-images.githubusercontent.com/35779030/88266438-8337f300-cccf-11ea-8592-5e800802d3ef.png)
![image](https://user-images.githubusercontent.com/35779030/88266454-8b902e00-cccf-11ea-9b53-88000852000f.png)

**Comment by weinand** [comment] 2020-07-23 09:08
You said:
> Start the debugger.

Since you have C++, C#, Python, PHP, Java, and JS debuggers installed, I do not know what "debugger" you mean.

Please provide more details.

**Comment by joaomoreno** [comment] 2020-07-23 15:22
@weinand, @gjsjohnmurray is 100% correct.

You can easily reproduce this by following my steps in https://github.com/microsoft/vscode/issues/100368#issuecomment-662316618 on our selfhost setup.

**Comment by yannickowow** [comment] 2020-07-29 09:22
Hi
I have the same behavior with my own Debug Adapter or with CppTools with custom GDB
With my adapter and my GDB, close can take a time (more than 1000 ms), because it uses subcomponents. From my side, this error happens when Code does not wait for disconnectRequest response.

Where  this timeout came from ?

Thanks in advance.

**Comment by connor4312** [comment] 2020-07-31 16:04
This may duplicate https://github.com/microsoft/vscode/issues/102037

**Comment by zhangzheming629** [comment] 2020-08-10 01:07
![ND6Q0LH S0 V@}1BT8JMD(I](https://user-images.githubusercontent.com/38377736/89745785-a42e7f80-dae8-11ea-8f46-873d7080d7c1.png)
我也遇到了

**Comment by connor4312** [comment] 2020-08-10 04:56
I see the assignment to Isi but I think this should be closed as an extension issue, unless the UX question is at play. At least when this is hit in js-debug, it's a result of the extension not responding to the disconnect request soon enough, which is an extension issue.

**Comment by weinand** [comment] 2020-08-10 06:54
If extensions have difficulties to respond to the `disconnect` request is time, then we should relax that requirement on the VS Code side.

**Comment by isidorn** [comment] 2020-08-11 15:27
I do not see big value in showing the timeout error to the user. Thus I have pushed the following change:
1) Increased timeout from 1s to 2s
2) Not showing the error in the case that the debug adapter is going down
3) Changed the timeout message to be localized (will not affect this case since we do not show the error now)

**Closed** 2020-08-11 15:26 UTC
Labels: debug

**Comment by 39r762193i** [comment] 2020-08-11 15:31
> 
> 
> 
> 
> 
> 
> - VSCode Version: I do not know.
> - OS Version: What is this ?
> 
> Steps to Reproduce:
> 
> 1. Start the debugger.
> 2. Stop it.
> 
> 
> Does this issue occur when all extensions are disabled?: Yes/No
> Probably.
> 
> ![image](https://user-images.githubusercontent.com/35779030/88196034-05c5a180-cc41-11ea-9b35-f8e9df37cb6f.png)
>

**Comment by connor4312** [comment] 2020-08-11 16:04
> I do not see big value in showing the timeout error to the use

Imo it's the same as the typescript server has crashed errors -- not necessarily useful to the user, but a nag for extension authors. If it's just a console log most developers will probably ignore it.

**Comment by isidorn** [comment] 2020-08-11 16:20
I see. However still prefer to optimise for the users.

**Comment by Zuckjet** [comment] 2020-08-16 08:32
**timeout after 1000 ms error** occurred frquently.

- VSCode Version:  
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

- OS Version: 
Edition: Windows 10 Home
Version: 1909

My vscode launch.json file:
```
"name": "Launch via NPM",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm.cmd",
            "stopOnEntry": true,
            "runtimeArgs": [
                "run-script", "debug"
            ],
            "port": 5858,
```
I also tried to add timeout option to fix the error, but not working.

My vscode only installed one debugger extension, which is "Debugger for chrome".

Everytime this error occurred , my vscode cannot debug anymore, and I have to restart vscode, but after a time , it occurred again.

**Comment by connor4312** [comment] 2020-08-16 15:32
This fix is so far only on VS Code Insiders: https://code.visualstudio.com/insiders/

**Comment by Zuckjet** [comment] 2020-08-16 15:43
> This fix is so far only on VS Code Insiders: https://code.visualstudio.com/insiders/

Thanks, I wil try this version.
