### ISSUE TITLE
Find box position resets after changing tabs

### ISSUE THREAD

**Issue by Argo483** [Microsoft/vscode#39753] opened 2017-12-06 03:31 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|6.3.0
prettier-vscode|esb|0.26.0
vs-keybindings|ms-|0.1.7

---

Steps to Reproduce:

1. Open file in VSCode which has a a string repeated in at least two posisions
2. Ctrl + F to open find box
3. Search for a string which exists in at least 2 places
4. Press enter so you are in a position which is greater than 1 (e.g. find box says 5 of 8)
5. Change to another tab in VsCode
6. Go back to the initial tab which has the find box open

Expected: find box should be at the same position as before you change tab (e.g if it was at 5 of 10 before changing tabs, it should still be at 5 of 10 when you go back to that tab)
Actual: find box always resets to position 1 of X after changing tabs

I find this issue to be a huge drain on productivity when switching between tabs as I am constantly loosing my scroll position in files. I believe this issue was not there in previous versions which leads me to believe it is a bug.

![image](https://user-images.githubusercontent.com/5241853/33643305-5332a948-da92-11e7-8c1a-a851d859987d.png)

Reproduces without extensions: Yes

**Comment by Simran-B** [comment] 2017-12-22 09:42
Can't reproduce it here in v1.19.1 on Windows 10. I can not observe any notable change of the widget position.

Can you share a screen recording? Maybe the window position, size etc. also play a role here.

**Comment by rebornix** [comment] 2018-09-18 19:38
As we don't have more information for troubleshooting, close it for now but we can reopen whenever we have more infos.

**Closed by rebornix** 2018-09-18 19:38 UTC
Labels: editor, editor-find, needs more info
