### ISSUE TITLE
The web vscode editor won't authenticate and it doesn't allow to click anything else on screen

### ISSUE THREAD

**Issue by Pubathed0g** [microsoft/vscode#142142] opened 2022-02-04 02:10 UTC
Does this issue occur when all extensions are disabled?: Yes/No - I can still access the page when the github repository extension is disabled, but even then random error still pop up at the bottom right. 

- VS Code Version:
- OS Version:

![image](https://user-images.githubusercontent.com/98989931/152460677-09f110ff-8794-459c-bac2-fb1b0ee07cfd.png)
When trying to use the web vscode editor, this happens and it won't allow me to authenticate or to click anything on the screen.

**Comment by Pubathed0g** [comment] 2022-02-04 02:12
"Allow" is the only thing that I can click on the page, which opens another tab asking me to confirm the authorization. I click ok on that tab, but it just redirects to text to exit the page. Then I'm back to the same screen.

**Comment by joyceerhl** [comment] 2022-02-04 05:15
@Pubathed0g If you reload the github.dev page after authenticating in the tab that appears, do you still get the same notification in the bottom right?

**Comment by Pubathed0g** [comment] 2022-02-04 05:27
Now when I try to recreate it, it's not stuck at the "Allow" popup, but when I click on the accounts at the bottom left, it says "github is currently unavailable"

**Comment by Pubathed0g** [comment] 2022-02-04 05:29
Ok, I then refreshed the github.dev page and the popup came back. I authorized it, and refreshed, which left me with:
![image](https://user-images.githubusercontent.com/98989931/152477174-da684da4-1f07-4c4d-b82a-14e24fbc3d46.png)

**Comment by joyceerhl** [comment] 2022-02-04 05:30
Do you see the same behavior if you try vscode.dev/github/Pubathed0g/token-list?

**Comment by joyceerhl** [comment] 2022-02-04 05:36
Also, on github.dev, if you hit 'Cancel' on the modal dialog and open the terminal area panel, can you possibly navigate to the Output tab and grab the logs for the GitHub Authentication extension?

![image](https://user-images.githubusercontent.com/30305945/152477762-6dace967-c098-4ba4-954c-b125775969aa.png)

**Comment by Pubathed0g** [comment] 2022-02-04 05:46
It doesn't allow me to hit the "cancel" or the "x" button.

**Comment by Pubathed0g** [comment] 2022-02-04 05:47
Also, this happens when I try to authenticate it now.
![image](https://user-images.githubusercontent.com/98989931/152478974-d6d7ece2-9777-46df-a48e-0901a80a5c96.png)

**Comment by joyceerhl** [comment] 2022-02-04 05:53
> Also, this happens when I try to authenticate it now. ![image](https://user-images.githubusercontent.com/98989931/152478974-d6d7ece2-9777-46df-a48e-0901a80a5c96.png)

Now if you click on Allow, or dismiss the modal dialog and click on Reauthenticate in the bottom right, are you still unable to sign in? And do you face similar issues in https://vscode.dev/github/Pubathed0g/token-list?

**Comment by Pubathed0g** [comment] 2022-02-04 05:57
I'm not even able to click "Reauthenticate" or "Cancel". The only option is "Allow" and when I click it, it just brings me to the authentication confirmation page. And the same issue on the token-list repository.

**Comment by Pubathed0g** [comment] 2022-02-04 06:03
It's pretty weird in my opinion. I made a new github account. Uninstalled VSCode, reinstalled, and uninstalled again. I thought that everything would be fresh and set as default, but I'm not sure went wrong.

**Comment by joyceerhl** [comment] 2022-02-04 06:06
I can't reproduce this at all. Tho, possibly same issue experienced by https://twitter.com/erbanku/status/1489462003257143297

Did you use github.dev before today, and was today the first time you have seen this behavior?

**Comment by Pubathed0g** [comment] 2022-02-04 06:08
It's my first time using github, at least in depth. That's the screen I see after clicking "allow", in the tweet.

**Comment by Pubathed0g** [comment] 2022-02-04 09:07
I found the issue. I guess one of my chrome extensions was causing problems. Changing browsers or going in incognito mode fixed it. Thanks for your patience though. :)

**Comment by TylerLeonhardt** [comment] 2022-02-04 16:59
@Pubathed0g but you said you also tried this in another browser, right? Did you have this extension installed in both Chrome and Edge? and if so, could you let me know what the extension is called?

**Comment by joyceerhl** [comment] 2022-02-04 17:56
Another report of auth issues: https://twitter.com/IgorBrigadir/status/1489613452226273288

**Comment by joyceerhl** [comment] 2022-02-11 05:13
Duplicate of https://github.com/microsoft/vscode/issues/142485, fixed in 1.64.2 and deployed in github.dev. Thank you @joaomoreno!

**Closed by joyceerhl** 2022-02-11 05:13 UTC
Labels: bug
