### ISSUE TITLE
Sync Changes button options

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#154857] opened 2022-07-11 21:22 UTC
<img width="294" alt="CleanShot 2022-07-11 at 14 21 19@2x" src="https://user-images.githubusercontent.com/35271042/178360595-e6f99365-7f85-4191-a1b9-985350dedd66.png">

<img width="165" alt="CleanShot 2022-07-11 at 14 22 05@2x" src="https://user-images.githubusercontent.com/35271042/178360608-7aee97ad-da9d-4e86-9f53-7b46399857d0.png">

I would love for an option when there are no pending changes to hide the "Sync Changes" button in the SCM view as it can be a little noisy when not needed.

**Comment by gjsjohnmurray** [comment] 2022-07-11 21:56
See https://github.com/microsoft/vscode/issues/154478#issuecomment-1179180462

**Comment by lszomoru** [comment] 2022-07-12 14:16
Closing this as duplicate of #154478

**Closed by lszomoru** 2022-07-12 14:16 UTC
