### ISSUE TITLE
Vs Code get blocked after a special regex search

### ISSUE THREAD

**Issue by Ali-Meddioui** [microsoft/vscode#147298] opened 2022-04-12 12:31 UTC
### Version
_Version: 1.66.1 (user setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042_

### Steps to Reproduce:

1. Search in **a large file** (500 lines) in REGEX mode this pattern : **((.|\n)*)\<FooBar\>** 

=>  Vs code blocks and after a while crashes

**Comment by IllusionMH** [comment] 2022-04-12 12:45
Looks like some content for RegExp was "eaten" by Markdown. If you have another `*` in RegExp then it's duplicate of #30874

**Comment by Ali-Meddioui** [comment] 2022-04-12 13:09
@IllusionMH  Thank you for your reply. the pattern is : ((.|\n)*)<FooBar>

**Comment by roblourens** [comment] 2022-04-12 19:03
It looks like this regex will just be slow to run. I don't know whether to call it the same as the catastrophic backtracking in #30874, but we run the regex in the same thread as the UI and just have to wait for javascript to respond again. Making it more specific might help.

**Closed by roblourens** 2022-04-12 19:03 UTC
