### ISSUE TITLE
Split view visibility not preserved across workspaces

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#43594] opened 2018-02-13 15:59 UTC
### Issue Type: Bug

Not sure if was always like this. 
When you open workspace for the first time `open editors` is visible:
![2018-02-13_01-35-57](https://user-images.githubusercontent.com/9638156/36159021-c8d15f0e-10ee-11e8-9305-ebea35056841.gif)

After reloading the editor `open editors` pane is hidden (as was expected for it to behave from the start).

VS Code version: Code - Insiders 1.21.0-insider (4d122017332a1ed12e083d79f85a054ac3f32fcf, 2018-02-13T05:16:56.295Z)
OS version: Windows_NT x64 10.0.17093
Reproduces without extensions

**Comment by usernamehw** [comment] 2018-02-13 16:37
I'll close as a duplicate of #43597

**Comment by isidorn** [comment] 2018-02-14 09:03
Right click on open editors to hide it

**Comment by usernamehw** [comment] 2018-02-14 14:55
@isidorn, I'm reopening this because I have hidden through context menu `opened editors` (that should hide them in all workspaces) and they are visible on the new workspaces on the first startup, which is seemingly a bug.

**Comment by isidorn** [comment] 2018-02-14 15:00
@usernamehw thanks, that sounds like a bug
@sandy081 split views visibility should be stored per user not per workspace. 
Isn't this tackled via https://github.com/Microsoft/vscode/issues/35462

**Comment by usernamehw** [comment] 2018-02-14 15:04
It is preserved per user correctly; only first startup on new workspace is affected.

**Comment by sandy081** [comment] 2018-02-14 15:07
It is preserved globally and the default is to show initially.

**Comment by isidorn** [comment] 2018-02-14 15:09
Ok, but the first startup on the new workspace should respect the previous value if there is some. So if hidden it should be hidden on a new workspace.

**Comment by sandy081** [comment] 2018-02-14 15:42
Yes, I confirm that on first and fresh start up (no previous value) open editors is shown (default). Once it is hidden it is respected always for all workspaces.

**Comment by sandy081** [comment] 2018-02-14 16:00
Sorry, I could reproduce it when I do not close the existing window. Here are the steps:

- Open a workspace
- Hide the open editors view
- Open a new workspace
- Open editors view is still visible

It works if you close the window from where you hide the open editors view.

**Comment by sandy081** [comment] 2018-02-14 16:06
Strange, I cannot reproduce in out of dev with above steps. I see that I am storing the value in global storage when the view is hidden. 

@isidorn are you able to reproduce it consistently in dev?

**Comment by isidorn** [comment] 2018-02-14 16:15
@sandy081 yeah, I can repro easily out of source

**Comment by sandy081** [comment] 2018-02-19 10:32
Checked with @isidorn and he also not cannot reproduce this. Hence closing this.

**Closed by sandy081** 2018-02-19 10:32 UTC
Labels: bug, workbench-layout
