### ISSUE TITLE
Adding SemanticTokenColorCustomizations-rules in settings.json file disable the color-picke

### ISSUE THREAD

**Issue by DirkDeclercq** [microsoft/vscode#137166] opened 2021-11-14 15:06 UTC
Issue Type: <b>Bug</b>

When I add rules to the editor.semanticTokenColorCustomizations-element in the settings.json file the color-picker for other colored-elements in same settings.json file does not work anymore.

Color-picker available when rules are disabled :
![image](https://user-images.githubusercontent.com/25179893/141686707-f8b458cb-4741-49d3-b387-f41cff9aec21.png)

Color-picker not available when rules are enabled:
![image](https://user-images.githubusercontent.com/25179893/141686724-0e0c88f0-612d-4893-b406-6bacf36d0faf.png)

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (18.13GB free)|
|Process Argv|--folder-uri file:///c%3A/Dev%20Learning/Udemy/JavaScript%20-%20The%20Complete%20Guide%202021%20%28Beginner%20%2B%20Advanced%29/basics-01-starting-project --crash-reporter-id 7d10d3bc-bb4a-452c-9722-1f26a164d34d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
ddcextensionpack|DDC|0.0.1
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
vscode-commands|fab|1.4.3
todo-tree|Gru|0.0.214
vscode-drawio|hed|1.6.2
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.5.0
shortcut-menu-bar|jer|3.0.3
HTMLHint|mka|0.10.0
csharp|ms-|1.23.16
powershell|ms-|2021.10.2
material-icon-theme|PKi|4.10.0
vscode-css-peek|pra|4.2.0
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.4
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by aeschli** [comment] 2021-11-15 11:54
Can you set `"json.trace.server": "verbose"` and check if there's an error in the `JSON Language Server` output?

If you find `Invalid regular expression` it's a duplicate of https://github.com/microsoft/vscode/issues/137054

**Comment by aeschli** [comment] 2021-11-15 12:03
I reproduced the issue with
```
	"workbench.colorCustomizations": {
		"editorOverviewRuler.warningForeground": "#f0f"
	},
	"editor.semanticTokenColorCustomizations": {
		"[Default Dark+]": {
			"enabled": true,
			"rules": {

			}
		}
	},
```

It is in deed caused by #137054. Making as dup.

**Closed by aeschli** 2021-11-15 12:03 UTC
Labels: new release

**Comment by DirkDeclercq** [comment] 2021-11-15 12:16
Thx for the fast response !
