### ISSUE TITLE
Unable to Customise New Profile Configuration

### ISSUE THREAD

**Issue by AbelBlossom** [microsoft/vscode#226533] opened 2024-08-24 17:56 UTC
Type: <b>Bug</b>

1.  Click on Settings Icon -> Profile -> New Profile
2. All the configurations are selected by default, disabling one disables all and clicking on one refuse to toggle it

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 9, 11|
|Memory (System)|16.00GB (3.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AbelBlossom** [comment] 2024-08-24 17:57
![Screenshot](https://github.com/user-attachments/assets/f899cc5a-0d8e-4d16-ba60-e9889edb0df1)

**Comment by crack-dawn** [comment] 2024-08-25 01:43
I meet the same problem above.
I hope VSCode can fix this issue in time.

**Comment by gjsjohnmurray** [comment] 2024-08-26 16:40
/duplicate of #224788 which offers a workaround. Will be fixed by changes in upcoming 1.93

**Closed** 2024-08-26 16:42 UTC
Labels: *duplicate, triage-needed
