### ISSUE TITLE
Remote-SSH: Recursive file watching not working

### ISSUE THREAD

**Issue by drok** [microsoft/vscode#201767] opened 2024-01-04 08:28 UTC
This is a continuation of #196466 which was closed without a solution.

I have the same issue as @sbatten in #196466, namely, I need to receive `onDidChange` events for files in the workspace.

The response @bpasero gave evades answering the question:

              @sbatten you seem to be watching inside the workspace though because you create a watcher with `vscode.workspace.workspaceFolders?.[0]?.uri`. Did you test this in an empty window to get the `vscode.Uri.file('/home/username/Source/testing-1/')` fallback?

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/196466#issuecomment-1778505083_

The issue at hand is that some files need to be monitored by an extension. I understand this "competes" with vscode's own file watcher, and vscode is expected to use its own filewatcher to service such filewatchers, but it does not.

Please provide a solution to @sbatten's issue, which is "how to watch workspace changes". That answer will also answer my issue.

**Comment by bpasero** [comment] 2024-01-04 10:02
@drok after you have studied the JSDoc of `createFileSystemWatcher`, can you let me know what is missing so that we can update the docs:

https://github.com/microsoft/vscode/blob/c18ce2ce9521cef51e98325bb3fbddf24abb8ecd/src/vscode-dts/vscode.d.ts#L13268

**Comment by drok** [comment] 2024-01-04 19:00
I have studied the docs in detail. The behaviour of the software does not reflect the documented behaviour.

In the code snippet provided by @sbatten in #196466 the intent is clearly to subscribe to change events to *.test.ts files anywhere/recursively in the first folder of the workspace, including subdirectories (ie, `new vscode.RelativePattern(folder, '**/*.test.ts')`, where `folder` is the first folder in the workspace.

The title of #196466 is unfortunate because it refers to files **outside** the workspace, while the intent of the code supplied is to monitor files **inside** the workspace.

Unfortunate title aside, vscode does not behave as advertised in the documentation. In practice, with the #196466 code, a change to a file `${workspace}/blah.test.ts` (ie, a file at the root of the workspace folder) would indeed cause the `onDidChange` handler to be called.

**However**, a change to a file `${workspace}/subfolder/blah.test.ts` (ie, a file in a subdirectory of the workspace folder) would **not** cause the `onDidChange` handler to be called.

In your response above you again seek to avoid the issue by suggesting the problem to be fixed is with the documentation rather than the functionality.

To be certain, the documentation is also defective, as it is ambiguous and unclear. Also, **to be certain**, this issue, and #196466 are not focused on the documentation, but on the actual behaviour. I will not point out the ambiguities in the documentation here so as to not distract from the actual issue, because over the course of many https://github.com/microsoft/vscode/labels/file-watcher issues, the intended meaning can be understood. A developer is required to research these issues in order to resolve the ambiguities. Since it is possible for a person to resolve the ambiguities, given enough effort, I choose not to focus on improving the documentation. I focus on implementing what the documentation intends to document.

**Comment by drok** [comment] 2024-01-04 19:28
Issue #146182 is closer to the scenario I am testing (extension is running remotely via SSH), and the comment https://github.com/microsoft/vscode/issues/146182#issuecomment-1083018281 is precisely reproduced.

I don't normally test without SSH, but out of curiosity, I tested on windows without SSH. To my surprise, changes in subdirectories are detected in that case, but not remotely via SSH. #146182 should be reopened. It appears `inotify_add_watch()` is only called on the top directory, not on the subdirectories. Note that `inotify_add_watch()` does not watch recursively, by design. Further, if I add a file watcher on a non-recursive path inside the workspace, the correct `inotify_add_watch()` is made, and `epoll_wait()` correctly returns the file change events, but vscode does not call the extension's event handler.

## Here is a repro without any extensions, showing the issue occurs inside vscode:

Use vscode on Windows, connecting to a linux host with Remote SSH. Use putty to open an SSH connection separate from vscode's ssh connection, so you can create files on the linux host without using vscode.

1. Create the folder `/tmp/vscode-issue-201767/subfolder` on the remote host. 
```
$ mkdir -p /tmp/vscode-issue-201767/subfolder
```
2. Connect with vscode to the remote host, open the parent folder `/tmp/vscode-issue-201767`
3. From palette, "Extensions: Disable all installed extensions on this workspace"
4. quit vscode
5. restart vscode, select the /tmp/vscode-issue-201767 workspace (will prompt "Extension 'Remote - SSH' is required to open the remote window. OK to enable?")
6. click "Enable and Reload"
7. Expand the `subfolder` directory in the file explorer pane.
8. In the putty terminal to the linux host, create a file in the root directory (vscode's file explorer automatically updates)
```
$ touch /tmp/vscode-issue-201767/file-in-root-dir
```
9. In the putty terminal, create a file in the subfolder. (**vscode file explorer fails to update**)
```
$ touch /tmp/vscode-issue-201767/subfolder/file-in-subfolder
```
10. click on the vscode window to bring it into focus. (the `subfolder/file-in-subfolder` appears on focusing vscode)

### The problem is that at step 9, a file created in a subfolder of the workspace is not noticed by vscode.

Step 10 demonstrates that vscode's developers are aware of the issue, and have hidden it by doing a directory refresh/scan upon window gaining focus.

Using strace to monitor the interaction between node and kernel on the linux host shows that `inotify_add_watch()` is only called on the root workpace folder, but not on any subfolders. This function does not monitor the filesystem recursively, by design. Each subfolder needs to be watched individually.

## The hack/workaround has concealed another bug:

If an extension creates a non-recursive file watcher on the subfolder of a workspace folder, the correct `inotify_add_watch()` for the subfolder is executed, and the kernel does deliver change notifications correctly, but that notification is not delivered to the extension's onDidChange/Create/Delete event handlers. It appears the event is thrown away by vscode.

**Comment by bpasero** [comment] 2024-01-04 19:32
So I was not able to figure out what https://github.com/microsoft/vscode/issues/146182 could be causing and unless some new information can be provided that would help figure out the root cause, I do not see how to proceed here.

**Comment by drok** [comment] 2024-01-04 22:25
> So I was not able to figure out what #146182 could be causing and unless some new information can be provided that would help figure out the root cause, I do not see how to proceed here.

The new information is above: https://github.com/microsoft/vscode/issues/201767#issuecomment-1877646477

It demonstrates that recursive watching as implemented in vscode (the "one VSCode creates for workspace watching" as you call it) does not work. Whether vscode configures the parcel bundler watcher incorrectly or whether the parcel bundler watcher itself is incapable of recursive watching is the determination you need to make, before being able to see how to proceed.

You cannot point the finger at "parcel bundler watcher" and claim this watcher issue in vscode must be "someone else's fault".

Please read the new information above: https://github.com/microsoft/vscode/issues/201767#issuecomment-1877646477

The #146182 issue includes all the information needed to help you reproduce the problem, but in that issue it looks like you never attempted to reproduce it.

The comment https://github.com/microsoft/vscode/issues/201767#issuecomment-1877646477, once again, gives you a new, even simpler way to reproduce the problem, which involves no extensions at all.

As @arnaudsylvestre concluded, I have to use fs.watch if I want reliable watches. vscode's implementation is broken.

**Comment by bpasero** [comment] 2024-01-10 11:19
I am not able to reproduce what you report. My setup is a Windows 11 connected to a Ubuntu 20 via SSH remote operating on the folders you suggested:

![Recording 2024-01-10 at 12 17 41](https://github.com/microsoft/vscode/assets/900690/dd880e1c-177b-4de9-bba5-3e5bdd2b9421)

If you have any more information for me to reproduce, please update this issue.

**Comment by drok** [comment] 2024-01-10 17:26
> If you have any more information for me to reproduce, please update this issue.

Interesting. I see from your screencap that you use a newer vscode.

I use Ubuntu 16.04.1 LTS (I don't think this matters because `inotify` doesn't work recursively by design), and the following vscode:
```
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.17763
Sandboxed: No
```

Although it is an older vscode, it is still very new (April 2023), and as I implement my extension I must assume that some of my users will use this version, or even older.

If the problem really is fixed in your version (I will try the newest and update this), then the documentation for the watcher API should be updated to note the old bug. Extension users cannot be expected to run the "latest" vscode, although some extension devs may force their users to upgrade with the `vscode.engines` setting in `package.json`

Are you able to reproduce the issue on vscode 1.77.3 ?

**Comment by bpasero** [comment] 2024-01-10 18:00
Is there anything that prevents you from trying to reproduce with latest version of VS Code? I would even suggest to try with VS Code insiders, which can be side by side installed to stable:

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by drok** [comment] 2024-01-10 18:31
I definitely will try it with a newer vscode, or even the insiders, and will update this issue with my findings.

However, whatever I find with newer vscode, does not change that my extension must work correctly on old versions. The extension refered to in https://github.com/microsoft/vscode/issues/146182 from Mar 2022 must also work on old versions, and thus it needs to rely on `fs.watch`, even if newer vscode versions eventually fixed the bug.

Also, if the bug did at some point exist, and was fixed in vscode, the broken versions must still be mentioned in the watcher API docs.

So while I plan on testing with a newer vscode, that outcome does not change the fact that my extension must support users who are on older vscode releases.

At first glance, vscode insiders does not install on my Ubuntu 16 remote (I have not attempted to run previous insider versions on this host, but at least version 1.77.3 and previous versions have been working fine for me):
```
[13:21:40.029] > 11ee8d1b1f37: start
> SSH_AUTH_SOCK==/tmp/ssh-vDzRxObPDj/agent.22874==
> DISPLAY==localhost:10.0==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==14783==
> execServerToken==0bc0e140359c==
> 11ee8d1b1f37: end
> 
[13:21:40.030] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-vDzRxObPDj/agent.22874==
DISPLAY==localhost:10.0==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==14783==
execServerToken==0bc0e140359c==

[13:21:40.030] Failed to parse remote port from server output
[13:21:40.032] Resolver error: Error: 
	at g.Create (d:\Profiles\Radu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:642703)
	at t.handleInstallOutput (d:\Profiles\Radu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:640069)
	at t.tryInstall (d:\Profiles\Radu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:761983)
	at async d:\Profiles\Radu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:722522
	at async t.withShowDetailsEvent (d:\Profiles\Radu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:725828)
	at async I (d:\Profiles\Radu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:719493)
	at async t.resolve (d:\Profiles\Radu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:723199)
	at async d:\Profiles\Radu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:907003
[13:21:40.037] ------
```

Given this error, I'm not keen to update my vscode from 1.77.3; I need to get work done, not to chase vscode bugs.

I have little doubt that the latest vscode on the latest linux remote works great, but the fact remains, I need the extension I am working on to work correctly on older vscodes, since I have no control over the versions my customers use.

**Comment by drok** [comment] 2024-01-10 18:52
Update; I found the following vscode insiders install message in the file `/home/radu/.vscode-server-insiders/.cli.c973ec767338f7846710cc2ee46e38b4504a044c.log`:

```
[2024-01-10 13:21:25] error This machine not meet Visual Studio Code Server's prerequisites, expected either...:   - find GLIBC >= 2.17 (but found v2.23.0 instead) for GNU environments
  - find /lib/ld-musl-x86_64.so.1, which is required to run the Visual Studio Code Server in musl environments
   ```

I must 🤣 at this error, because `v2.23.0` is definitely greater than `GLIBC >= 2.17` in my eyes, though it looks like an apples to oranges comparison. It's not ready to :shipit:

I won't be able to test a newer vscode as it appears incompatible with "This machine" that I am interested in.

**Comment by bpasero** [comment] 2024-01-10 19:06
Yeah it is likely that we dropped support for Ubuntu 16 meanwhile.

I am sorry, but we do not give support for older versions of VS Code, nor do I think does it make sense that we should update any of our docs given that people that run into this on Ubuntu 16 are using a now unsupported old installation of VS Code.

**Comment by drok** [comment] 2024-01-10 19:16
Update: https://code.visualstudio.com/updates/v1_82 mentions that vscode dropped support for CentOS 7 (which is not EOL for another 6 months, and in use/ELS till 2028+) and Ubuntu 18 which will be in ESM till 2028, by "upgrading" to node 18.

Once again. My extension audience will be using CentOS/RHEL 7, Ubuntu 16 and 18, and therefore will be forced to use vscode < 1.82 at least until 2028. I have to support these OS's until at least 2028, and probably well after that. My customers need to develop and maintain software for existing (read "old") systems, not only produce new software for state-of-the art systems.

**Comment by drok** [comment] 2024-01-10 19:27
> now unsupported old installation of VS Code

You are referring to vscode versions before 1.82, ie, versions before July 2023 (it is now Jan 2024).

You would have said the same in August 2023, when 1.81 was "old", and you offered no support in Mar 2022 in https://github.com/microsoft/vscode/issues/146182 when this bug was current in the (latest, at the time) release.

I think it's more accurate to say that you give "no meaningful support at all".

**Comment by bpasero** [comment] 2024-01-10 19:42
I think I tried to give support as much as I can and I feel this discussion is not leading to a good outcome, so I am going ahead and will close it.

**Closed by bpasero** 2024-01-10 19:42 UTC
Labels: info-needed, file-watcher, confirmation-pending
