### ISSUE TITLE
Issue reporter does nothing when "Create on GitHub" is pressed

### ISSUE THREAD

**Issue by 0xabu** [microsoft/vscode#134530] opened 2021-10-06 21:24 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
1.60.2
- OS Version:
Windows 11 x64 22000

Steps to Reproduce:
1. Help -> Report Issue
2. Fill out the report as shown:
![image](https://user-images.githubusercontent.com/13037682/136285258-ae9218fd-e5a6-4d7b-84b3-6e0423686477.png)
3. Click "Create on GitHub"
   (nothing happens)

**Comment by altano** [comment] 2023-09-02 22:18
Signing out and signing back in does not fix the already-open issue reporter, and the already-open issue reporter has captured information about my extension bisect that I lose when I close it (the bisect is how I ended up in the Issue Reporter). Also when I close and re-open the Issue Reporter, the extension is disabled (automatically, as a result of it being the culprit that the extension bisect discovered). So, this workaround isn't ideal and it might be the case that bug reports are just not getting filed by the extension bisect tool (which is fantastic, btw).

**Comment by justschen** [comment] 2023-12-07 00:54
@0xabu was unable to reproduce on 1.84.2

**Closed** 2023-12-07 00:54 UTC
Labels: bug, issue-reporter
