### ISSUE TITLE
VSCode freeses when something process is running and Japanese IME is opening.

### ISSUE THREAD

**Issue by fujitatakesh** [microsoft/vscode#115736] opened 2021-02-04 08:30 UTC
Issue Type: <b>Bug</b>

1:Open Source Control View.
2:Stage a file.
3:Input commit message stop on the way by Japanese IME.
4:Maybe background process, progress action appeared, running something(scan files?).
  ->Seemed it needs a same timing 3: and 4:.
5:Freeze the view.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.09GB free)|
|Process Argv|--crash-reporter-id a399381a-0c4e-4845-8ba0-bbf38b7d9811|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.19.1
flutter|Dar|3.19.0
githistory|don|0.6.14
xml|Dot|2.5.1
vscode-optimize-images|fab|1.1.0
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
vscode-nuget-package-manager|jmr|1.1.6
classic-asp-html|jtj|0.1.2
sftp|lix|1.12.9
rainbow-csv|mec|1.8.1
vscode-language-pack-ja|MS-|1.52.2
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
easy-compile|ref|1.2.1
vscode-xml-complete|rog|0.2.15
html2jade|wma|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by tomothy83** [comment] 2021-02-05 03:53
@fujitatakesh , Is this duplicate of #112621?

**Comment by fujitatakesh** [comment] 2021-02-05 04:03
> @fujitatakesh , Is this duplicate of #112621?

Exactly. I hope it'll be fine, thank you.

**Closed** 2021-03-02 16:30 UTC
Labels: *english-please, *not-reproducible, needs more info, translation-required-japanese
