### ISSUE TITLE
[Feature Request] Different way to complete with tab (YCM style)

### ISSUE THREAD

**Issue by andreyorst** [Microsoft/vscode#34694] opened 2017-09-20 12:52 UTC
## Before I start
Hello.

VS Code is great software, and i really like how it grows over time, so I want to improve the experience of using it.

Previously I used Vim a lot, because at work it is my only option, but at home for hobbies I use VS Code, and when I program in C, at my work I use YouCompleteMe (YCM) plugin for `tab` completions, and I really like the way it works. 

## Touch typing

The main thing is that I use all my 10 fingers to write code, and rarelly move hands from home row, because vim, _you know_, has `hjkl` and other ways to navigate in code. So first thing was to install vim-extension to VS Code, to stop using arrow keys, and it works well. But tab completion still forces me to use arrows.

How it works in Vim: I select from the list using the `tab` button and I confirm the completion by simply continuing typing. Therefore, my hands never leave the home row.

The way it works in VS Code: `tab` button completes the completion and closes popup, And arrow keys are just navigate within the list and not confirm anything. So I need to navigate in list with arrow keys (and leave home row) then press `tab` for completion. In fact it is way faster just to type most things by hand just looking at the popup for reference. And it is frustrating after long way of programming in vim.

## So what do _you_ want?
All I want is an option in settings to change `tab` key behavior to something like (or close to) YCM style. 
The behavior itself can be described like so:
  1. Start typing (`std::` for example)
  2. Completion popup is displayed (or invoked by `tab`)
  3. Press the `tab` and completion is done, but popup isn't closed
  4. Press tab again, and next item in popup list replaces previous completion
  5. Press tab until you will be satisfied with your completed text
  6. Continue typing, popup is closed (unless you folow the completion hint from popup)

That's how (mostly) it works in such plugins like YouCompleteMe, Supertab in Vim. You can try this plugins for better understanding of what i mean. And it is comfortable because you don't need arrow keys at all.

## P.S:
Previously (before Vim) I used Visual Studio for C++ programming, and when I swithced to YCM's completion system I noticed a great boost of writing speed. YCM has it's own plugin in the marketplace, but it uses standard `tab` behavior, which makes it little less useful an makes me little less productive.

Thanks.

**Comment by ramya-rao-a** [comment] 2017-09-21 01:35
cc @jrieken and @alexandrudima

**Comment by jrieken** [comment] 2017-09-21 08:34
Duplicate of https://github.com/Microsoft/vscode/issues/28215

**Closed by jrieken** 2017-09-21 08:34 UTC
Labels: suggest
