### ISSUE TITLE
[Git Message] Pinyin ghosting when inputting Chinese 

### ISSUE THREAD

**Issue by shenghui0779** [microsoft/vscode#166181] opened 2022-11-12 11:28 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.1
- OS Version: MacOS Ventura 13.0.1

Steps to Reproduce:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/67535398/201471751-8c0b6b3e-5ccc-4cc1-9bd4-8326f7a99b5e.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/67535398/201471728-b9588e8c-d00e-4cb3-9cd9-e16e5239420f.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/67535398/201471644-16dd8754-348d-400a-85ea-eded0eb4af63.png">

**Comment by lszomoru** [comment] 2022-11-15 17:14
duplicate of #165682

**Closed by lszomoru** 2022-11-15 17:14 UTC
