### ISSUE TITLE
Feature request: Lazy QuickPickList

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode#23338] opened 2017-03-28 05:53 UTC
- VSCode Version: 1.10.2
- OS Version: Linux

I would like to have an autocomplete QuickPickList. Is this possible right now? As far as I know the items need to be available in advance right now, right?
I would like to have it for this feature: KnisterPeter/vscode-github#84

I could think it would be a useful addition to other plugins as well.

**Comment by jrieken** [comment] 2017-03-29 07:14
closing as dupe of #21372

**Closed by jrieken** 2017-03-29 07:14 UTC
Labels: api, feature-request, quick-pick, workbench
