### ISSUE TITLE
When "ctrl+enter" or "shift+enter" it run the wrong cell

### ISSUE THREAD

**Issue by Tirbo06** [microsoft/vscode#133038] opened 2021-09-09 10:09 UTC
## Environment data

VS Code version: 1.60
Jupyter Extension version (available under the Extensions sidebar): v2021.8.1054968649
Python Extension version (available under the Extensions sidebar): v2021.7.1060902895
OS (Windows | Mac | Linux distro) and version: Windows 10: 21H1
Python and/or Anaconda version: 3.8.10/3.9.6
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
Jupyter server running: Local | Remote | N/A: Local and remote
## Expected behaviour

Run the selected cell when "ctrl+enter" or "shift+enter".

## Actual behaviour
Sometimes, when "ctrl+enter" or "shift+enter" to run a cell, it run the wrong cell.
It seems to me that it is running the last cell ran.

## Steps to reproduce:
Hard to reproduce as it is happening randomly. I would suspect it to happen after a high memory consumption (reaching to max) that will make it bug until we restart the apk/computer.

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```

```

</p>
</details>

**Comment by greazer** [comment] 2021-09-13 22:07
VSCode core handles the ctrl+enter and shift+enter shortcuts so transfering there.

**Comment by munro** [comment] 2021-09-14 17:17
Having the same issue, I've tried playing with the shortcuts, but I can't seem to fix it.  It really makes VSCode Notebooks unusable 😞 

It seems like there's some discrepancy with where the editor cursor is, and where the notebook thinks the cursor is when executing.

**Comment by wenkangmq** [comment] 2021-09-16 03:59
Same issue, default keybinding ctrl+Enter runs the above(previously edited) cell instead of the current one. Resetting shortcut keybinding make the problem go away for a while but then happens again radomly.

**Comment by roblourens** [comment] 2021-09-17 19:23
I can't reproduce this. A gif would really help. @yuanchongtt had a screenshot of a notebook with the editor focus and cell focus out of sync. 

![image](https://user-images.githubusercontent.com/39210932/133044550-541bdd1f-e3da-46d7-abe7-3d11ae0d9bb0.png)

Is that what people are seeing? Would really like to see a gif of how people get into that state

**Comment by theonlypoi** [comment] 2021-09-18 05:41
I have noticed similar behaviour. I don't know if it's actually the problem. But this happens when I create one cell using code button that appears on hovering over the cell and then create another cell using the code button at the top.

Steps to reproduce:
1. Create a new notebook.
2. Delete the first cell that appears.
3. Use `+code` button on the screen to create a cell (execute it with Ctrl + Enter).
4. Then use `+code` button (that appears on the top bar) to create another cell. 

Now the cursor appears to stop on the first cell.
This is for a completely new notebook. But unable to reproduce this behaviour when the notebook already have some cells.

I don't know how to create a gif but I hope the steps I mentioned will be helpful.

**Comment by wenkangmq** [comment] 2021-09-19 14:08
I think the problem is that vscode is not focusing on the current cell, the result of that is ctrl+enter runs the other cell
[made a gif](https://imgur.com/a/042jNDp)

**Comment by DonJayamanne** [comment] 2021-09-21 16:23
@roblourens I'm running into this pretty consistently, will ping when today when I run into this.

**Comment by jazzlw** [comment] 2021-09-23 18:06
This issue has been killing me. makes the vscode notebooks almost unusable. I generally resort to manually clicking the play button on a given cell to get it to run. This generally does not fix the behavior or change focus, but sometimes it does. Seems very stochastic overall.

**Comment by jazzlw** [comment] 2021-09-23 20:31
Added detail: Often this seems to be caused by a clear separation of focus, where the blue vertical bar focus indicator is not on the cell currently being edited, as in the gif above.

However, at other times, the blue cell focus indicator is correct and a different cell is still run, with no visual indication of which one it will be.

**Comment by roblourens** [comment] 2021-09-24 00:03
I am still not able to repro this. People who see this, cold you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by DonJayamanne** [comment] 2021-09-24 18:14
@roblourens i think https://github.com/microsoft/vscode/issues/133026 is a dup of this. Possible the contexts weren't working correctly. E.g. i run into issues where selecting a cell and hitting the `DD` to delete a cell wouldn't work, until and unless i closed and re-opened the notebook.
FYI - I haven't been able to replicate this, since monday.

**Comment by jazzlw** [comment] 2021-09-27 18:31
I've switched to insiders and haven't had the problem again yet! I'll message back again if it happens again in the insiders version.

**Comment by roblourens** [comment] 2021-09-30 21:22
Moving to October - seems like this has still been observed once or twice in Insiders, but there's nothing that I can do here right now. Please continue to report it if you see it and let me know what actions you took.

**Comment by wenkangmq** [comment] 2021-10-01 07:41
I have been using a fresh install of the 1.61.0-insider build on Fedora for a week. Only extensions are Dracula theme, phtyon extension, and tabnine, also no settings sync. I haven't encountered this bug yet.

**Comment by CiralaDevelopment** [comment] 2021-10-01 13:36
I've been plagued by this issue for some time now, on the Insiders build as well. I've managed to reproduce it consistently by and below are some screenshots of how I reproduce it.

1. Create a new cell and run it

![1](https://user-images.githubusercontent.com/13252907/135628324-26ed94de-c652-4473-9fbb-097c44cddc6c.png)

2. Click the first cell to select it and then create a new cell below

![2](https://user-images.githubusercontent.com/13252907/135628326-31ac7249-7d19-4b08-b0fc-7920cfd5de86.png)

3. Clicking the new cell places the cursor in it and allows for editing while the first cell remains selected

![3](https://user-images.githubusercontent.com/13252907/135628329-78fd702e-f1e5-4116-8bbe-320eeed8c6a9.png)

4. Shift+enter in the new cell incorrectly runs the first cell 

![4](https://user-images.githubusercontent.com/13252907/135628306-1bed2e08-60de-43fd-ba6d-42b7b8a6ee46.png)

5. Cell selection/run-context is now messy and shift-enter behavior unpredictable.

![5](https://user-images.githubusercontent.com/13252907/135628318-8dfd41c5-a4fb-4742-b708-913b6a783c34.png)



Hope this helps.

**Comment by roblourens** [comment] 2021-10-02 00:10
Thanks for the screenshots! I see you have an update pending in that Insiders build, can you check the date on it? (Help > About)

I've found two ways to get the editor and list focus out of sync. But neither is what we are seeing here.

- Focus the cell 1 editor
- Mouse down on the cell 1 statusbar and drag off it
- Click on the cell 2 editor
- Now both cell editors have the focus outline and cell 1 will never lose it until the editor is focused and blurred again

---

- Focus the cell 1 editor
- Click to add a breakpoint in cell 2
- Now cell 2 has list focus but cell 1 still has editor focus

I don't think either of these are worth taking for this release. I still don't see how it's possible to insert a cell and end up with that cell not focused

**Comment by CiralaDevelopment** [comment] 2021-10-04 10:22
> Thanks for the screenshots! I see you have an update pending in that Insiders build, can you check the date on it? (Help > About)

Version: 1.61.0-insider
Date: 2021-09-16T08:31:28.161Z

> I still don't see how it's possible to insert a cell and end up with that cell not focused

Are you referring to my situation? If so, is there anything else I can do or test to ease your debugging?

**Comment by jazzlw** [comment] 2021-10-08 18:15
Have been using insiders for a while and not been having the problem but just had it again today... I'm surprised to see my info date says 9-26 since I thought I'd just updated.  I'll update again and report back if the problem continues


Version: 1.61.0-insider (Universal)
Commit: 214ac689ca9874a8a4be386f73d5cb60e15af25e
Date: 2021-09-28T05:14:06.244Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 17.7.0

**Comment by harripj** [comment] 2021-11-23 13:24
I am still having this problem running on 1.62.3, Windows. It has been plaguing me for a while. The problem is intermittent and hard to reproduce in my case too. I have noticed that when it happens the thick blue 'active cell' line indicator (on left of cell) remains fixed on a certain cell, despite the creation or clicking on new cells. This is the cell that also executes, so I imagine the two are related. The cell toolbar also remains fixed on this cell despite focussing/clicking on a new cell in my case.

I have attached a screenshot here to better explain my descriptions. 
![image](https://user-images.githubusercontent.com/16853829/143032001-2f4bf037-ecdc-4db1-bd6b-5d0f5f638875.png)

**Comment by melihozaydin** [comment] 2021-11-24 12:41
Having the same issue as well. It's not a big issue as I can close and reopen the notebook to temporarily fix it, but it is annoying as hell.

**Comment by munro** [comment] 2021-11-24 15:21
Same, this issue was fixed a bit—but then started happening again recently. 😢

**Comment by harripj** [comment] 2021-11-25 10:07
It just happened to me again. I tried to execute a cell above or below a certain cell, but this cell kept executing instead. In fact I noticed that by clicking in the gutter I could move the blue active line and cell toolbar (that I mentioned above https://github.com/microsoft/vscode/issues/133038#issuecomment-976529373) but even though this UI was changed, the wrong cell kept executing. So my last comment maybe somewhat of a red herring!

Another thing I noticed is that I had clicked away to a different program and when I returned to VS Code the problem had sorted itself out and the correct cell would execute.

**Comment by hamiddashti** [comment] 2021-12-03 19:39
Same here. Is there any solution found for this issue, rather than closing and reopening the notebook?

**Comment by david-waterworth** [comment] 2021-12-09 09:37
@hamiddashti if this is the same problem I reported (https://github.com/microsoft/vscode/issues/136310) then a potential solution is to change focus from vscode to another application and then switch back. I noticed this as each time I encountered the issue I tried to switch to a screen recorder to record and the problem went away. It could well be a different issue though, or behave differently on different platforms (I'm using Linux)

**Comment by roblourens** [comment] 2022-02-24 16:04
No reports of this in awhile - closing

**Closed by roblourens** 2022-02-24 16:04 UTC
Labels: bug, regression, notebook-keybinding, notebook-regression
