### ISSUE TITLE
集成终端显示异常

### ISSUE THREAD

**Issue by CHL2** [Microsoft/vscode#26256] opened 2017-05-09 02:47 UTC
- VSCode Version: 1.12.1
- OS Version: Windows 10 Creator Updata

Steps to Reproduce:

1. Type `Ctrl` + `

![image](https://cloud.githubusercontent.com/assets/18417342/25833556/c0bbe70c-34a4-11e7-846a-a88263dd80a7.png)

**Comment by kevin0137** [comment] 2017-05-09 02:59
+1

**Comment by irexer** [comment] 2017-05-09 03:56
+1

**Comment by egamma** [comment] 2017-05-09 07:00
duplicate of #26263

**Closed by egamma** 2017-05-09 07:00 UTC
