### ISSUE TITLE
Add variable substitution to refer to a specific root folder of a multi-root workspace

### ISSUE THREAD

**Issue by winglerw28** [Microsoft/vscode#38977] opened 2017-11-22 19:07 UTC
Currently, the settings provide the substitution `${workspaceFolder}` for finding the root of the currently active folder. For some projects, you may wish to refer to a different root folder of a multi-root workspace; an example of this: `~/projects/myApp` depends on `~/projects/myNpmPackage`.

With the above scenario, the `myApp.code-workspace` will look as follows:

```json
{
    "folders": [
        {
            "name": "my-npm-package",
            "path": "~/projects/myNpmPackage"
        },
        {
            "name": "app-that-deps-on-package",
            "path": "~/projects/myApp"
        }
    ]
}
```

It would be nice to have the ability to reference another workspace root for things such as source mapping with the `msjsdiag.debugger-for-chrome` extension. A syntax for this could be along the lines of `${workspaceFolder:<folder-name>}`.

Using the aforementioned syntax in `~/projects/myApp/.vscode/launch.json` could look like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug My App in Chrome (Launch)",
            "type": "chrome",
            "request": "launch",
            "preLaunchTask": "build-npm-package",
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}",
            "pathMapping": {
                "/myApp/node_modules/myNpmPackage": "${workspaceFolder:my-npm-package}",
                "/myApp": "${workspaceFolder}/public"
            }
        }
    ]
}
```

This yields the following advantages:

- I no longer have to worry about the relative location of the `myNpmPackage` folder when writing tasks, and can instead simply update `myApp.code-workspace`
- In `tasks.json`, I can now create the `build-npm-package` task to build `myNpmPackage` and copy any changes into the `node_modules` folder of `myApp`, avoiding having to manually copy anything 
- I no longer have to open two copies of source files from `myNpmPackage` while debugging, and am less likely to accidentally edit the `node_modules` version since it won't open when stepping through
- I can use workspace settings that can refer to multiple root folders in `myApp.code-workspace`
- These substitutions would make consolidating `task.json` or `launch.json` files into a single config easier if desired (or if a multi-root workspace supports a workspace-wide `tasks.json` or `launch.json` in the future)

**Comment by weinand** [comment] 2017-11-22 19:33
Yes, support for root-folder based variables is planned under this umbrella item: #38134

**Comment by winglerw28** [comment] 2017-11-23 01:59
My search skills failed me when trying to find if that was already submitted. Thanks!

**Comment by isidorn** [comment] 2017-11-23 08:36
Closing as duplicate of the umbrela.
@winglerw28 we will keep your feedback in mind when we look into closing the umbreal item. Thank you

**Closed by isidorn** 2017-11-23 08:36 UTC
Labels: debug, feature-request
