### ISSUE TITLE
Format on paste trims trailing character when pasting class name in html

### ISSUE THREAD

**Issue by swervo** [Microsoft/vscode#26744] opened 2017-05-16 12:14 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mavensmate|DavidHelmer|0.7.0|
|html-snippets|abusaidm|0.1.0|
|angular1-code-snippets|alexandersage|0.0.3|
|htmltagwrap|bradgashler|0.0.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|tslint|eg2|0.14.0|
|Angular2|johnpapa|2.2.3|
|debugger-for-chrome|msjsdiag|3.1.1|;

---

The issue I'm seeing is when I add a class name to an html element when I place the cursor at the end of the last class name and add a space when I paste the new class name the space is removed thus running the class names together and making them invalid.

I've tested this with:

`'editor.formatOnPaste': false`

and it doesn't occur. I've only noticed it today so I suspect it is related to a recent update. I've also tested it with all my extensions turned off and it still occurs.

Steps to Reproduce:

1. Enable 'format on paste'
2. Put a string in the clipboard (eg., 'large')
3. Place the cursor at the end of a class string eg., place it after 'brand' below

`<div class="button brand"></div>`

4. Insert a space:

`<div class="button brand "></div>`

5. Paste string
6. Result (note missing space):

`<div class="button brandlarge"></div>`

7. Expected result:

`<div class="button brand large"></div>`

**Comment by aeschli** [comment] 2017-05-26 19:20
duplicate of #26297

**Closed by aeschli** 2017-05-26 19:20 UTC
