### ISSUE TITLE
Allow `files.encoding` to be set per programming language.

### ISSUE THREAD

**Issue by Lisoph** [Microsoft/vscode#29575] opened 2017-06-27 10:52 UTC
The default file encoding cannot be set per programming language. This is a problem, because certain old languages force you to use old encodings.

Instead of manually having to reload the file in the correct encoding every time, I propose to allow the `files.encoding` setting to appear inside language specific settings.

```json
"[baan]": {
    "files.encoding": "iso88591"
}
```

When opening files of the types registered for the `baan` language, this would automatically set the file encoding to the specified value.

---

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.2.0|
|baan|danielhauser|0.0.1|
|vscode-rust|kalitaalexey|0.4.2|
|cpptools|ms-vscode|0.11.4|;

**Comment by Sleaker** [comment] 2017-06-28 18:53
This is a duplicate of a feature I requested back in febuary: #19890

**Closed** 2017-06-30 04:14 UTC
Labels: config, feature-request, workbench
