### ISSUE TITLE
Fresh install of Visual Studio Code does not launch

### ISSUE THREAD

**Issue by ryanbrandenburg** [Microsoft/vscode#16948] opened 2016-12-08 22:01 UTC
- VSCode Version: 1.7.2-1479766213
- OS Version: CentOS7 (64)

Steps to Reproduce:

1. Install VS Code via .rpm
2. Open a terminal and run "code ."
3. See that it returns `/usr/share/code/bin/../code: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`.

**Comment by kazaroff** [comment] 2016-12-09 16:59
Have the same problem on CentOS7. If you use yum to install the 1.7.2 code rpm, it will resolve the dependencies, but then it does not start complaining
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

**Comment by Tyriar** [comment] 2016-12-09 17:24
Duplicate of https://github.com/Microsoft/vscode/issues/15325.

This is fixed in the upcoming version, in the meantime you can install the dep manually with `sudo yum install libXScrnSaver.x86_64`

**Closed by Tyriar** 2016-12-09 17:24 UTC

**Comment by kwmiebach** [comment] 2017-03-15 13:30
On debian 8 (and probably ubuntu), to install the dependency manually:

`sudo apt install libxss1`

**Comment by miparnisari** [comment] 2017-05-30 03:18
@kwmiebach it's actually `sudo apt-get install libxss1`, but thanks :)
