### ISSUE TITLE
Lost indent spaces when copy code to OneNote

### ISSUE THREAD

**Issue by MattYangGH** [Microsoft/vscode#39289] opened 2017-11-29 02:14 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.12.0
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
format-php|Kas|1.1.2
swift|Kas|0.0.3
vscode-html-scss|P-d|0.0.42
php-formatter|Sop|0.2.4
code-gnu-global|aus|0.2.2
vscode-database|baj|1.2.0
vscode-file-templates|bam|1.1.0
code-sql|cod|0.0.3
vscode-html-css|ecm|0.1.8
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
code-runner|for|0.8.4
mdmath|goe|2.0.7
CppSnippets|har|0.0.13
vscode-ebnf|igo|1.0.3
copy-markdown-as-html|jer|1.0.0
php-symbols|lin|2.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
markdown-shortcuts|mdi|0.8.1
vscode-clang|mit|0.2.2
vscode-apache|mrm|1.1.1
mssql|ms-|1.2.1
python|ms-|0.8.0
cpptools|ms-|0.14.3
php-docblocker|nei|1.3.2
vscode-icons|rob|7.18.1
vscode-sql-beautify|sen|0.0.4
php-ci|sma|0.2.8
python|tht|0.2.3

---

Steps to Reproduce:

1. Select and copy the code from vscode (Python code)
2. Paste to OneNote

Result:
The indent spaces have been lost! 

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-11-29 08:55
Duplicate of #35954

**Closed** 2017-11-29 20:06 UTC
Labels: *duplicate
