### ISSUE TITLE
How to correctly response StackTraceRequest?

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#46099] opened 2018-03-19 11:37 UTC
_From @actboy168 on March 17, 2018 6:48_

My debugger sometimes has a bug. There are two identical stack frames in the vscode UI.

I found that vscode will send StackTraceRequest three times and my response is as follows

```
Step 1.

StackTraceRequest:
startFrame = 0
levels = 1

StackTraceResponse:
stackFrames
* frame id = 2
totalFrames = 1

Step 2.

StackTraceRequest:
startFrame = 0
levels = 20

StackTraceResponse:
stackFrames
* frame id = 2
* frame id = 3
* frame id = 4
totalFrames = 3

Step 3.

StackTraceRequest:
startFrame = 1
levels = 19

StackTraceResponse:
stackFrames
* frame id = 2
* frame id = 3
* frame id = 4
totalFrames = 3
```

Then the UI will display 4 stack frames
* frame id = 2
* frame id = 2
* frame id = 3
* frame id = 4

![1](https://user-images.githubusercontent.com/1836844/37552465-2c9d232c-29f1-11e8-8192-06d30749480f.png)

My frame id starts at 2 and I don't know what effect.

_Copied from original issue: Microsoft/vscode-debugadapter-node#169_

**Comment by weinand** [comment] 2018-03-19 11:46
In Step 1 you are supposed to return the "total number of frames" as `totalFrames`. In your case this is probably 3 and not 1.

Here is how it should work:

- Assume that your current stack has 3 frames.
- VS Code sends a first StackTraceRequest(startFrame = 0, levels = 1) to get the first frame and find the total number of frames.
- you return the first frame and totalFrames: 3
- now VS Code knows how many frames there are in total and VS Code sends a second StackTraceRequest(startFrame = 1, levels = 2) to get the next batch of frames.

**Comment by actboy168** [comment] 2018-03-19 12:06
Thank you very much, I already know where I was wrong.

**Comment by actboy168** [comment] 2018-03-19 12:15
This means that for every time StackTraceRequest, I need to iterate over all the stack frames to get totalFrames. What is the purpose of the step-by-step request stack frame?

**Comment by weinand** [comment] 2018-03-19 14:38
There are two cases:
- if you return the value `true` for the `supportsDelayedStackTraceLoading` capability, VS Code will do the sequence I've explained above: first get the first frame and the total number of frames and then after a delay the rest. If the user is stepping through his program quickly, VS Code will only ask for the first frame and not for the rest. This makes the stepping faster.
- if you return the value `false` for the `supportsDelayedStackTraceLoading` capability (or the capability is missing), VS Code will always ask for the first 20 frames. If there are more frames, VS Code asks for the next 20 frames only if the user presses a "more frames" button.

If you experience that VS Code does not work like this, please let us know.

My recommendation is the following:
- if your debug adapter can determine the total number of frames cheaply (e.g. without requesting all frames), then use the first approach (supportsDelayedStackTraceLoading = true). 
- if you can only find the total number of frames after retrieving them all, then use the second approach (supportsDelayedStackTraceLoading = false). In this case just return the requested stackframes and don't return a `totalFrames` value.

**Comment by actboy168** [comment] 2018-03-20 04:30
Hi, I found that the vscode works fine when I don't return totalFrames. (I have been return the value true for the supportsDelayedStackTraceLoading capability) I don't know if I have any bugs like this.

I still don't understand the significance of totalFrames for vsocde.If the number of stack frames returned by the debugger is less than `levels`, then no more stack frames are available. So it doesn't seem necessary to know totalFrames in advance.

In fact, if you ignore the second StackTraceRequest, vscode looks like this works. So the second StackTraceRequest looks like a bug, because it's redundant and it doesn't match what you said.

**Comment by weinand** [comment] 2018-03-20 09:51
I cannot confirm that VS Code sends bogus StackTrace requests. I've added some tracing to mock-debug and I'm seeing the following sequences:

for `supportsDelayedStackTraceLoading = false`:
```
stackTraceRequest(startFrame:0 maxLevels:20) -> totalFrames:11
```

for `supportsDelayedStackTraceLoading = true`:
```
stackTraceRequest(startFrame:0 maxLevels:1) -> totalFrames:11
stackTraceRequest(startFrame:1 maxLevels:19) -> totalFrames:11
```

This output corresponds to my description from above.

**Comment by actboy168** [comment] 2018-03-23 05:25
I dumped all the protocol.

It has twice `ThreadsRequest`. Am I missing anything?

```
{"command":"initialize","arguments":{"clientID":"vscode","adapterID":"lua","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"zh-cn"},"type":"request","seq":1}
{"type":"response","seq":1,"command":"initialize","request_seq":1,"success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsDelayedStackTraceLoading":true,"supportsExceptionInfoRequest":true,"exceptionBreakpointFilters":[{"default":true,"filter":"error","label":"Uncaught Error"}]}}
{"command":"launch","arguments":{"name":"launch","type":"lua","request":"launch","stopOnEntry":true,"program":"E:\\GitHub\\lml\\test/test.lua","cwd":"E:\\GitHub\\lml\\test","path":"E:\\GitHub\\lml\\test/?.lua","arg":[],"console":"utf8","__sessionId":"12dfaf96-51d7-482b-a397-a05a60134b71"},"type":"request","seq":2}
{"type":"event","seq":2,"event":"initialized"}
{"command":"setExceptionBreakpoints","arguments":{"filters":["error"]},"type":"request","seq":3}
{"type":"response","seq":3,"command":"launch","request_seq":2,"success":true}
{"type":"response","seq":4,"command":"setExceptionBreakpoints","request_seq":3,"success":true}
{"command":"configurationDone","type":"request","seq":4}
{"command":"threads","type":"request","seq":5}
{"type":"response","seq":5,"command":"configurationDone","request_seq":4,"success":true}
{"type":"event","seq":6,"event":"thread","body":{"reason":"started","threadId":1}}
{"type":"event","seq":7,"event":"stopped","body":{"reason":"entry","threadId":1}}
{"command":"threads","type":"request","seq":6}
{"type":"event","seq":8,"event":"stopped","body":{"reason":"step","threadId":1}}
{"type":"response","seq":9,"command":"threads","request_seq":5,"success":true,"body":{"threads":[{"name":"LuaThread","id":1}]}}
{"type":"response","seq":10,"command":"threads","request_seq":6,"success":true,"body":{"threads":[{"name":"LuaThread","id":1}]}}
{"command":"threads","type":"request","seq":7}
{"command":"threads","type":"request","seq":8}
{"type":"response","seq":11,"command":"threads","request_seq":7,"success":true,"body":{"threads":[{"name":"LuaThread","id":1}]}}
{"type":"response","seq":12,"command":"threads","request_seq":8,"success":true,"body":{"threads":[{"name":"LuaThread","id":1}]}}
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":9}
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":10}
{"type":"response","seq":13,"command":"stackTrace","request_seq":9,"success":true,"body":{"stackFrames":[{"source":{"name":"test.lua","path":"E:\\GitHub\\lml\\test\\test.lua"},"id":0,"name":"[main chunk]","line":3,"column":1}],"totalFrames":1}}
{"type":"response","seq":14,"command":"stackTrace","request_seq":10,"success":true,"body":{"stackFrames":[{"source":{"name":"test.lua","path":"E:\\GitHub\\lml\\test\\test.lua"},"id":0,"name":"[main chunk]","line":3,"column":1}],"totalFrames":1}}
{"command":"scopes","arguments":{"frameId":0},"type":"request","seq":11}
{"type":"response","seq":15,"command":"scopes","request_seq":11,"success":true,"body":{"scopes":[{"name":"Upvalues","variablesReference":1,"expensive":false},{"name":"Globals","variablesReference":2,"expensive":true},{"name":"Standard","variablesReference":3,"expensive":true}]}}
{"command":"variables","arguments":{"variablesReference":1},"type":"request","seq":12}
{"type":"response","seq":16,"command":"variables","request_seq":12,"success":true,"body":{"variables":[{"variablesReference":4,"name":"_ENV","value":"table: E4A4CC8","type":"table"},"variables"]}}
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":1,"levels":19},"type":"request","seq":13}
{"type":"response","seq":17,"command":"stackTrace","request_seq":13,"success":true,"body":{"stackFrames":[],"totalFrames":1}}

{"command":"next","arguments":{"threadId":1},"type":"request","seq":14}
{"type":"response","seq":18,"command":"next","request_seq":14,"success":true}
{"type":"event","seq":19,"event":"stopped","body":{"reason":"step","threadId":1}}
{"command":"threads","type":"request","seq":15}
{"type":"response","seq":20,"command":"threads","request_seq":15,"success":true,"body":{"threads":[{"name":"LuaThread","id":1}]}}
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":16}
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":17}
{"type":"response","seq":21,"command":"stackTrace","request_seq":16,"success":true,"body":{"stackFrames":[{"source":{"name":"test.lua","path":"E:\\GitHub\\lml\\test\\test.lua"},"id":0,"name":"[main chunk]","line":1,"column":1}],"totalFrames":1}}
{"type":"response","seq":22,"command":"stackTrace","request_seq":17,"success":true,"body":{"stackFrames":[{"source":{"name":"test.lua","path":"E:\\GitHub\\lml\\test\\test.lua"},"id":0,"name":"[main chunk]","line":1,"column":1}],"totalFrames":1}}
{"command":"scopes","arguments":{"frameId":0},"type":"request","seq":18}
{"type":"response","seq":23,"command":"scopes","request_seq":18,"success":true,"body":{"scopes":[{"name":"Upvalues","variablesReference":1,"expensive":false},{"name":"Globals","variablesReference":2,"expensive":true},{"name":"Standard","variablesReference":3,"expensive":true}]}}
{"command":"variables","arguments":{"variablesReference":1},"type":"request","seq":19}
{"type":"response","seq":24,"command":"variables","request_seq":19,"success":true,"body":{"variables":[{"variablesReference":4,"name":"_ENV","value":"table: E4A4CC8","type":"table"},"variables"]}}
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":1,"levels":19},"type":"request","seq":20}
{"type":"response","seq":25,"command":"stackTrace","request_seq":20,"success":true,"body":{"stackFrames":[],"totalFrames":1}}

```

**Comment by paulo-fernando-silva** [comment] 2018-05-05 10:14
I'm also curious why stackTraceRequest gets called twice every time. Is there a reason with the same parameters? I only have one thread.

**Comment by weinand** [comment] 2018-05-05 22:01
@isidorn please investigate

**Comment by isidorn** [comment] 2018-05-08 15:39
@paulo-fernando-silva @actboy168 please provide me some reproducable steps so I can investigate this more since I can not reproduce this with debugging node. 
`stackTraceRequest` should be called twice first with 0,1 than everything else.

**Comment by isidorn** [comment] 2018-05-09 07:57
@actboy168 thanks, closing this as designed then

**Closed by isidorn** 2018-05-09 07:57 UTC
Labels: debug, needs more info, question
