### ISSUE TITLE
UX about inline traffic light

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#17532] opened 2016-12-19 13:11 UTC
I'm thinking about picking up #12628, but would like to get some input from the UX team, so we can get the design right.

## Current State

![](https://cloud.githubusercontent.com/assets/49038/20053382/88475732-a4d8-11e6-97aa-80eb257c5264.png)

However, this design doesn't work when activitybar is hidden or in the right.

## Electron's limitation

Electron allows one of the four following styles, but they can't be changed at runtime. Would need a restart of VSCode to use another style.

![image](https://cloud.githubusercontent.com/assets/4033249/21313907/4580a386-c62f-11e6-9984-a08284442a28.png)

### To make the inline traffic lights work, there are three options:

1. When inlining traffic lights into activitybar, lock activitybar so user can't hide it or move it to the right.

2. Tweak the sidebar and tabbar, so they could contain the traffic lights. Chrome-style tabbar is achievable:

    ![](https://cloud.githubusercontent.com/assets/900690/19407942/0deedfac-92b1-11e6-9a5c-ae38a3a3b28b.png)

    **but I can't find a good way to let sidebar contain traffic lights**. Haven't seen other OS X app putting traffic light in sidebar either.

3. Instead of inlining traffic lights into activitybar, we inline the traffic lights into a **custom titlebar**. This is how many macOS apps are designed, like Mail, iTunes and Safari:

    ![image](https://cloud.githubusercontent.com/assets/4033249/21311564/c7c6dc32-c622-11e6-83f5-8f4188b85805.png)

1 is easy to implement. 3 feels right design-wise. 2 probably isn't worth pursuing, as it involves a lot effort for a not-so-good design.

### Do we also add such a feature for Windows?

- If so, I think inlining traffic lights into custom titlebar is better, as the "traffic lights" are to the right in Windows. Borrowing @be5invis's mockups...

    This looks natural:

    ![image](https://cloud.githubusercontent.com/assets/4033249/21310986/f094e698-c61f-11e6-978c-7457d924e882.png)

    Whereas this one looks odd, and doesn't account for the case when both activitybar and sidebar are hidden. It also leaves no space for menu items.

    ![image](https://cloud.githubusercontent.com/assets/4033249/21311076/4dc9b8d4-c620-11e6-920d-a48a96eb90b2.png)

## My thoughts

Overall, I feel 3 is better than 1 in terms of usability and cross-platform design consistency.

It seems @bpasero already made a custom titlebar for macOS. If we choose design 3, I can try to make `titleBarStyle: custom` for Windows. If we choose to push the original idea forward, I want to get some input from the UX team for the usability concerns.

/cc @bpasero @stevencl @bgashler1

**Comment by be5invis** [comment] 2016-12-19 13:46
The second image is just a joke...

The first one is actually a plausible plan. The “Title Bar” is built with:

- Grand button, for menu and action input.
- Tabs / Panel titles.
- Space for dragging the entire window (ref: Edge).
- Minimize-Maximize-Close buttons.

**Comment by octref** [comment] 2016-12-19 13:56
@be5invis I feel it would be better to have a dedicated tabbar separate from titlebar. But that's a discussion for later.

**Comment by be5invis** [comment] 2016-12-19 14:01
This is Edge:

![image](https://cloud.githubusercontent.com/assets/240091/21315353/b938cfae-c636-11e6-82f9-da57d03bb16b.png)

**Comment by bpasero** [comment] 2016-12-19 14:13
I still think a design on macOS where the buttons move to the left of the tab-well would be nice to explore similar to how Chrome shows it. It gets more interesting in our case because:
* the activity bar can be on or off or to the right hand side
* the side bar can be visible or not

I also think that we should support this on Windows. There however we have no good access to the native window controls, so we need to keep in mind that we can never get the native look and feel right on that OS.

Moving to @stevencl and @bgashler1 as potential design topic for the future.

**Comment by be5invis** [comment] 2016-12-19 14:16
@bpasero Simulate using SVG? Typora on Windows has a similar “borderless” mode, but it is not open-source.

**Comment by be5invis** [comment] 2016-12-19 14:16
cc. @abnerlee

**Comment by octref** [comment] 2016-12-19 14:27
@bpasero 

> I still think a design on macOS where the buttons move to the left of the tab-well would be nice to explore similar to how Chrome shows it.

Then we also need a design for handling traffic lights with hidden activitybar + open sidebar.

As for adding things to activitybar, I think it makes more sense to explore enhancing the custom titlebar. Electron has [`hidden-inset`](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#hidden-inset) so we can make the titlebar wider, and our use case is pretty similar to XCode:

![test](https://cloud.githubusercontent.com/assets/4033249/21316093/31f3c248-c63a-11e6-8506-979a57829dc7.gif)

**Comment by net** [comment] 2017-06-03 04:47
Not sure if I should bring this up here or in #12377.

Hopefully we get a way to hide the both titlebar *and* the traffic lights. The traffic lights are useless if you use keyboard shortcuts.

Regarding dragging issues, on macOS you can move windows around without a titlebar by moving the cursor over the edge of the window so the resize arrow appears, then dragging perpendicular to the direction of the resize arrow. (For example, when hovering over the left or right edge, drag vertically instead of horizontally.)

**Comment by dzannotti** [comment] 2017-06-22 22:33
I would love to see this PR moving forward, are there any blocker tasks i could help with?
@bpasero

**Comment by patrys** [comment] 2017-09-07 13:59
I have to say that for a rather opinionated UI (extensions can't customize it) the options to hide or move the activity bar are rather surprising to me.

**Comment by dzannotti** [comment] 2017-09-08 22:03
pinging again @stevencl @bpasero

**Comment by bpasero** [comment] 2017-09-10 07:33
@dzannotti feel free to jump in (the PR that started the work is here: https://github.com/Microsoft/vscode/pull/12628 and there is more discussion here: https://github.com/Microsoft/vscode/issues/12377). 

Here is an overview of the challenges that would need to be addressed to move this in:
* where to put the window controls depending on the activity bar visibility (users can hide it) and location (users can put it to the right). one possible solution is to prevent hiding and changing the location if this style is enabled and always have the controls within the activity bar on the left hand side. alternatively if we allow to hide/move the activity bar, the solution needs to find a way to put the controls in the side bar, or editor area when the sidebar is hidden
* making sure that the activity bar cannot be zoomed (or only the icons within) when the window controls are within so that the alignment of the window controls is still OK in different zoom levels
* adjusting the activity bar properly when the user enters fullscreen (in that case the window controls disappear and so we would not want extra padding in the activity bar since the controls are no longer there)
* allowing to drag the window in certain areas: if we remove the title bar, you need other means of moving the window. possible solution is to enable this for the activity bar and maybe status bar

I think its all doable, but a bit challenging 👍

**Comment by bpasero** [comment] 2017-11-17 08:32
/duplicate of https://github.com/Microsoft/vscode/issues/12377

**Closed by bpasero** 2017-11-17 08:32 UTC
Labels: *duplicate, ux, workbench-title
