### ISSUE TITLE
Setting tokenColorCustomizations has refresh issues

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31632] opened 2017-07-28 07:46 UTC
Testing #31360 on Ubuntu

Notice in the recording how:

- The tokens don't refresh when I change the `fontStyle`. Only when I change `foreground`.
- The tokens don't appear customised after a reload

![kapture 2017-07-28 at 9 44 41](https://user-images.githubusercontent.com/22350/28707648-7a95c3ce-7379-11e7-90d5-b937e6da6cfc.gif)

**Comment by aeschli** [comment] 2017-08-04 13:55
duplicate of #29421

**Closed by aeschli** 2017-08-04 13:55 UTC
