### ISSUE TITLE
Switch group command not working as expected

### ISSUE THREAD

**Issue by antonioriverov** [microsoft/vscode#97992] opened 2020-05-16 17:29 UTC
Issue Type: <b>Bug</b>

When having Python interactive window open and try to switch to that group (normally with Cmd + 2), the cursor will disappear instead of going to the "command line" (the space to write commands). Then when trying to go back to editor with Cmd + 1, this won't work again so I need to use the mouse to click where I want to go. This is happening since the last update. It's important to mention that this problem is exclusive for Python Interactive. When using editors, it works fine. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (1.19GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.78807
vim|vsc|1.14.3

</details>

**Comment by bpasero** [comment] 2020-05-18 11:11
Sounds like a `webview` issue to me. Maybe caused by extension, not sure.

**Comment by antonioriverov** [comment] 2020-05-24 02:35
I'm not sure. I disabled the extensions but this kept happening. I had to go back to version 1.44.2 for it to work again.

**Comment by joyceerhl** [comment] 2020-06-02 18:36
Hi @mjbvz 👋 I work on the Python extension data science team. We've had multiple users report this issue on our repo: [#11808](https://github.com/microsoft/vscode-python/issues/11808) and [#12088](https://github.com/microsoft/vscode-python/issues/12088).

This bug does not manifest with 1.44.2. In ^1.45, it appears that our webview within the panel doesn't receive focus when the user switches to a group containing it using the Ctrl+1/2 keyboard shortcut. Specifically, `focus` fires when the user directly clicks on the webview, but not with the keyboard shortcuts.

Would you happen to have an idea of when / how this can be fixed, and any workarounds we can use in the interim to ensure our webview receives focus with keyboard shortcuts?

**Comment by mjbvz** [comment] 2020-06-02 21:47
@joyceerhl Are any other keyboard shortcut not working?

**Comment by joyceerhl** [comment] 2020-06-02 21:50
I've only been testing switching groups, so just Ctrl+1/2/3 etc. Sorry if my original comment was ambiguous!

**Comment by mjbvz** [comment] 2020-06-02 22:11
This is a lower priority issue since those keyboard short cuts are not super heavily used.

It sounds like the core of https://github.com/microsoft/vscode-python/issues/11808 is that focus is not restored once the interactive window is refocused. I can repo this just by clicking away from the python interactive window and then clicking on the interactive window tab. I believe that needs to be fixed in the interactive window's implementation

**Comment by joyceerhl** [comment] 2020-06-02 22:27
Just to be sure I understand—you're recommending that when the webview panel is focused, we should also explicitly focus the webview? Could you point me to docs for managing focus changes for webview panels?

**Comment by mjbvz** [comment] 2020-06-02 22:51
This is up to your extension. When a webview tab is focused, VS Code focused the webview element but it does not restore focus to any previously focused element within that webview

In your webview, you can just use:

```
window.addEventListener('focus', () => { });
window.addEventListener('blur', () => { });
```

to detect when focus is gained or lost

**Comment by joyceerhl** [comment] 2020-06-02 22:58
Will give that a try. Thank you!

**Comment by joyceerhl** [comment] 2020-06-04 19:59
Hi @mjbvz, I added listeners for `focus` and `blur` events on the window itself, and forced a focus on the input box when `window` receives focus. This did not resolve the issue.

Based on logging in the window focus / blur callbacks, it appears that if I select, unselect, then reselect the interactive window using keyboard shortcuts, on reselect, the webview window gets `focus` immediately followed by `blur`, which is what results in the interactive window becoming unresponsive. This still manifests after stripping out all the places in our codebase where we manually focus elements. We do not get the extra `blur` event if we click directly on the panel tab.

For this reason I think this bug is a result of a change in keyboard shortcut handling and listening for `focus` / `blur` on the window is insufficient, since we're getting an extra `blur` external to our code. Would you be able to suggest any workarounds we can implement while the keyboard shortcut issue is being resolved?

**Comment by mjbvz** [comment] 2020-06-04 20:08
@joyceerhl I see that a focus event is always fired last: 

![Jun-04-2020 13-06-47](https://user-images.githubusercontent.com/12821956/83805202-49018c00-a664-11ea-99c5-f242687f3db0.gif)

It looks like there is an extra `blur` in between but the focus remains the last callback

**Comment by joyceerhl** [comment] 2020-06-04 23:32
> focus is not restored once the interactive window is refocused. I can repo this just by clicking away from the python interactive window and then clicking on the interactive window tab.

I can repro this behavior with the standard Cat Coding demo extension, so I don't think this is our bug. Clicking on the tab for the webview results in a `blur` being the last callback, so focus gets trapped in the webview, after which I'm unable to navigate away using keyboard shortcuts.

![webview](https://user-images.githubusercontent.com/30305945/83819865-e1f1d080-a67f-11ea-80f9-1e5cb62d3304.gif)

**Comment by greazer** [comment] 2020-06-05 18:39
This behavior affects accessibility. Is there a different keyboard-only combination that can enable the user to switch groups and set focus as the original user desires? If not, then I think the priority of this bug warrants a closer look.

**Comment by antonioriverov** [comment] 2020-06-16 16:46
Hi, just following up. Is there any fix to this yet? Thank you for looking into this.

**Comment by joyceerhl** [comment] 2020-06-25 17:28
Hey @mjbvz, we're getting more users reporting issues with our interactive window and Jupyter notebook viewer. I see that there's a 'help wanted' label on this--I'd be happy to work with you to submit a fix!

**Comment by mjbvz** [comment] 2020-06-25 23:54
Here's the place where we try rebroadcasting keypresses from webviews: https://github.com/microsoft/vscode/blob/49f35453c456dd7189578895d81868e66ee3aab9/src/vs/workbench/contrib/webview/browser/baseWebviewElement.ts#L155

Try looking into why these keypresses are either not rebroadcast or why they are not handled properly as VS Code commands

**Comment by corneliusroemer** [comment] 2020-10-26 10:21
Hi there, are there any updates, it's been silent here for 4 months? It totally breaks the Python extension workflow for me (and many others). Python is one of the main extensions and MS supported so it'd be fab if you could reconsider priority of this bug.

**Comment by nayefahmad** [comment] 2020-10-29 04:57
Just wanted to add that I also find this issue to be a major barrier to effectively using the Python interactive extension. It would be great if this could be prioritized higher.

**Comment by rchiodo** [comment] 2020-12-01 20:55
I've done some debugging on this problem. I believe the root cause of the problem is the fix created by these two commits:
https://github.com/microsoft/vscode/commit/870700e95c18eff7f0827595b521a9d10a243274
https://github.com/microsoft/vscode/commit/88929c7a45ec3d1b0c570113cf222ff92a860f60

What I see happening is that the blur (from the second commit) is also async if the webview has focus already. Meaning it can happen at random times after the delayed focus trigger. 

I'm going to submit a PR that I think fixes it and maintains the current behavior as well. This zip has a test extension (minus the gif for the cat) that I used to verify CTRL+1/2 works as expected.
[cat-coding-0.0.1.zip](https://github.com/microsoft/vscode/files/5625391/cat-coding-0.0.1.zip)

**Comment by connor4312** [comment] 2021-01-28 22:56
I can still reproduce this on Windows: https://memes.peet.io/img/21-01-8f0f0372-8296-45f8-b503-1d2098378704.mp4

I don't see any PRs on the jupyter side referenced, is there an update I need to take from there?

**Comment by rchiodo** [comment] 2021-01-28 23:00
Latest bits from jupyter extension should be good enough.

**Comment by rchiodo** [comment] 2021-01-28 23:01
You might want to try the cat coding example I added to see if that repros for you.

**Comment by connor4312** [comment] 2021-01-28 23:06
I'm on the latest published version of the Jupyter extension, 2020.12.414227025.

The focus works sometimes in the cat coding example, though it's inconsistent. Video: https://memes.peet.io/img/21-01-9e4f1c74-9140-4625-86e0-d722add628e9.mp4

**Comment by rchiodo** [comment] 2021-01-28 23:57
Yeah we have the same inconsistency in the jupyter extension. I can't repro the problem anymore myself.

**Comment by dynamicwebpaige** [comment] 2021-03-15 09:43
It sounds like this bug makes working in Python interactive mode on remote infrastructure, using only a keyboard, impossible. Is that correct?

**Comment by rchiodo** [comment] 2021-03-15 16:06
@dynamicwebpaige impossible might be too strong a word, but it's certainly harder. When it doesn't work, you'll sometimes end up with focus elsewhere. You can then tab or hit CTRL+1 again to try a second time.

**Comment by mjbvz** [comment] 2021-10-20 00:01
The interactive window now is built into VS Code instead of being a webview, so this issue should not longer happen for it

However I also tested this on Mac and Windows using a simple textarea inside a webview. On Mac, both cmd+# and ctrl+# work for me. On windows: ctrl+# and alt+# are also working for me

If you are still seeing this issue in any webview, please let me know specifically what type of webview you have opened and where you are focused when trying to trigger the shortcuts

**Closed by mjbvz** 2021-10-20 00:01 UTC
Labels: bug, help wanted, verification-found, webview
