### ISSUE TITLE
C# Snippets do not work after update to 1.12.0

### ISSUE THREAD

**Issue by a-heryani** [Microsoft/vscode#25943] opened 2017-05-04 22:53 UTC
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:18:34.633Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|fresh-material|2ndshift|1.5.0|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|bower|donjayamanne|0.0.3|
|jquerysnippets|donjayamanne|0.0.1|
|bowerwatcher|ealsur|0.0.1|
|vscode-html-css|ecmel|0.1.2|
|tslint|eg2|0.12.0|
|vscode-npm-script|eg2|0.1.9|
|auto-close-tag|formulahendry|0.3.12|
|vscode-material-theme|fredrikaverpil|0.0.5|
|beautify|HookyQR|1.0.2|
|csharpextensions|jchannon|1.3.0|
|nuget-reverse-package-search|jesschadwick|0.1.68|
|vscode-nuget-package-manager|jmrog|1.1.2|
|Angular2|johnpapa|2.2.3|
|theme-material-theme|jprestidge|1.0.1|
|docomment|k--kato|0.0.14|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.9.0|
|vscode-versionlens|pflannery|0.14.1|
|material-icon-theme|PKief|2.0.5|
|ClassyNaming|reflectiondm|1.0.0|
|prettier-eslint-vscode|RobinMalfait|0.7.1|
|aspnet-helper|schneiderpat|0.6.3|
|code-settings-sync|Shan|2.7.0|
|bootstrap4-vscode|thekalinga|2.3.3|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|vscode-material-syntax-dark|woodywoodsta|0.1.1|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1. Try any VSCode built-in C# snippet (ctor, prop etc)
2. Intellisense does not show the snippet in the list of available actions

**Comment by kieferrm** [comment] 2017-05-04 23:23
Duplicate of #25938.

**Comment by seanmcbreen** [comment] 2017-05-05 00:06
I have seen a few people report snippets not working - by the thing seams to be more that the ordering of completions differs.  Several people have resolve this by adding in the setting:

`"editor.snippetSuggestions": "top"`

Worth giving this a try to see if the it returns you closer to your expected behavior.

**Comment by a-heryani** [comment] 2017-05-05 00:14
That was the first thing I tried before opening this issue. Made no difference.

![image](https://cloud.githubusercontent.com/assets/26278881/25729858/8de7ea78-317b-11e7-94ab-7f6274bdfa2d.png)

**Comment by jrieken** [comment] 2017-05-05 06:56
closing as dupe

**Closed by jrieken** 2017-05-05 06:56 UTC
Labels: duplicate
