### ISSUE TITLE
Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by gaz647** [microsoft/vscode#232194] opened 2024-10-24 19:43 UTC
Type: <b>Bug</b>

When trying to add a folder to the workspace, VSCode quits unexpectedly

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|13, 6, 2|
|Memory (System)|15.53GB (9.72GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 655b40e9-7926-4607-ae35-dfa0c72bbb22|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.10.0
vscode-tailwindcss|bra|0.12.11
turbo-console-log|Cha|2.10.5
mobileview|cir|0.0.7
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
fast-arrow-hai-nui-che|hai|2.0.3
vscode-colorize|kam|0.11.1
idx-monospace-theme|kek|1.3.3
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.12.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
ayu|tea|1.0.5
pdf|tom|1.2.2
errorlens|use|3.20.0
volar|Vue|2.1.6
vscode-wakatime|Wak|24.6.2
glean|wix|5.2.2
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|Yoa|0.6.0
html-css-class-completion|Zig|1.20.0
classnametocss|zit|0.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-10-24 20:57
/duplicate of https://github.com/microsoft/vscode/issues/230454

**Closed** 2024-10-24 20:57 UTC
Labels: *duplicate
