### ISSUE TITLE
Global search buffer should not focus input fields 

### ISSUE THREAD

**Issue by wprater** [microsoft/vscode#39904] opened 2017-12-08 01:44 UTC
When the global buffer is changed, the input fields should not be changed, only populated.

Currently when I select some text and hit `cmd+e` the find viewlet is opened and focus is set on the input field.  

I would not expect focus, since I dont plan to modify the input, but usually find next or move the cursor around.

**Comment by wprater** [comment] 2017-12-13 22:53
the more I think about this, I really dont feel the Find widget should open all all when the global buffer is changed.  find inputs should populate with the global buffer whenever it changes. it should be a known fact that I can alter the buffer in another app, come to VS Code and cmd+g to search.  

or if I were to place text into buffer with cmd+e, Id expect it to just be there and already filled in all search inputs for when/if I need to alter or act upon them.

does this make sense?  I feel its correct in the sense of how other apps have been implemented this in macOS for years.

**Comment by rebornix** [comment] 2019-10-23 22:11
/duplicate of https://github.com/microsoft/vscode/issues/44093

**Closed** 2019-10-23 22:11 UTC
Labels: *duplicate, editor-find, under-discussion
