### ISSUE TITLE
Breakpoints do not seem to be forwarded to gdb

### ISSUE THREAD

**Issue by nlurkin** [microsoft/vscode#150518] opened 2022-05-27 08:26 UTC
Does this issue occur when all extensions are disabled?: Cannot check without the extension enabled.

- VS Code Version:1.67.2
- OS Version:Ubuntu 20.04.2

Hello,
I am opening this bug report here as suggested on the original report (https://github.com/microsoft/vscode-cpptools/issues/9361)

I am trying to run debugging with the cpptools extension, but no breakpoints are hit. In the original report, I submitted the plugin log and it seems that their plugin is not even receiving the list of requested breakpoints that are set in vscode.

Steps to Reproduce:

1. Set some breakpoints in the code
2.Launch debugging, breakpoints are not received in the debugger.

**Comment by nlurkin** [comment] 2022-05-27 09:03
Hello,
Let me add as well that I just tried reverting to 1.66.2 and with that version, everything is working as expected.

**Comment by roblourens** [comment] 2022-05-27 21:58
Hm, I can't reproduce and I can't think of any relevant changes on our end.

If you download the last version of vscode from the links at the top of the page here: https://code.visualstudio.com/updates/v1_66 does it work in that version? (Or you can go older if you think it was a longer time ago.)

And while taking that log, you tried setting and unsetting breakpoints? 

Do the breakpoints show as gray circles? 

Any errors in vscode devtools (Help > Toggle developer tools)?

**Comment by nlurkin** [comment] 2022-05-30 08:18
Hello,
I have tried indeed to set and unset breakpoints while taking the log (and saw no movement in the log at all), and the breakpoints where showing full red dots.

While checking, I have been going back and forth between the latest version and earlier ones, also downgrading and upgrading some of the plugins (the latest version of some of them do not seem to be compatible with older versions of vscode). Eventually the issue disappeared and I am not able anymore to reproduce it anymore. I am rather sure that my current situation in terms of versions of vscode and each individual plugins is the same as before (everything at the latest), so I don't know what changed in the process of downgrading and upgrading...

**Comment by roblourens** [comment] 2022-06-01 00:40
That's strange, I'm not sure what happened. Thanks for doing that experimentation. I'm going to close this for now but we can reopen it if you see this issue again.

**Closed by roblourens** 2022-06-01 00:40 UTC
Labels: needs more info
