### ISSUE TITLE
Cannot use any keybindings inside webview

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#61762] opened 2018-10-24 23:04 UTC
1. Open release notes
2. Use some keybinding (ctrl+,, ctrl+k, etc.), nothing seems to work

**Comment by Tyriar** [comment] 2018-10-26 14:54
This was on Windows 10

**Comment by bpasero** [comment] 2018-10-26 15:50
Ok, I was testing only macOS.

**Comment by bpasero** [comment] 2018-10-27 12:14
@Tyriar I cannot reproduce, in this video I can open settings (Ctrl+,) and quick open (Ctrl+P):

![before](https://user-images.githubusercontent.com/900690/47603891-7ef37e80-d9f2-11e8-8894-3cfb920ee567.gif)

**Comment by Tyriar** [comment] 2018-12-03 14:06
I can still reproduce, I notice you're using the OSS build over the exploration, maybe that's it? Build details:

VS Code version: Code - Exploration 1.30.0-exploration (57d85c2667e8e66140e0f7edfb8b6e636c6a4876, 2018-12-01T13:59:00.436Z)
OS version: Windows_NT x64 10.0.18290

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (54.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.3.0
cpptools|ms-|0.20.1
material-icon-theme|PKi|3.6.1
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-12-03 17:48
When I print the keybinding we emit:

https://github.com/Microsoft/vscode/blob/57d85c2667e8e66140e0f7edfb8b6e636c6a4876/src/vs/workbench/parts/webview/electron-browser/webviewElement.ts#L163

At least I am getting the exact same result on Linux (where the keybinding works) as on Windows, weird.

**Comment by bpasero** [comment] 2018-12-04 13:41
I think a better solution (that I just verified works on Windows) is to listen on the actual keyboard event in the `webview `and serialize that one over to the `renderer `to dispatch to the keybinding service. It looks like one property is missing from Electron's `before-input-event` that causes us to ignore the keyboard event. The property is `keyCode`.

**Comment by bpasero** [comment] 2018-12-05 10:46
Fixed via https://github.com/Microsoft/vscode/pull/64417/commits/42cde7e5aa79232d9a8adcf3d6527d97cfcc32cb

**Closed by bpasero** 2018-12-05 10:46 UTC
Labels: bug, electron, electron-3.0.x-update, electron-blocker

**Comment by Tyriar** [comment] 2019-01-31 20:43
Verified on windows, linux and mac
