### ISSUE TITLE
Auto indent: incorrect indentation when pressing enter after the end of an arrow function

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#116843] opened 2021-02-17 10:46 UTC
- VS Code Version: 1.53.2
- OS Version: macOS 11.2.1

Steps to Reproduce:

```ts
const add1 = (n) =>
    n + 1;
```

(Arrow functions are frequently formatted in this way by Prettier.)

1. After the last character on the last line, press enter

Expected: a new line is created without indentation
Actual: a new line is created with indentation

![image](https://user-images.githubusercontent.com/921609/108193526-72d4e300-710d-11eb-922c-70cd7e0d50fe.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by NotWearingPants** [comment] 2021-02-18 20:23
This has nothing to do with arrow functions. The editor just repeats the previous indentation level, and only cares about brackets I believe. The problem is that there is nothing about indentation in the LSP protocol.

The closest thing would be to look at the folding and have VSCode use the indentation of where the folding region starts, but this doesn't apply everywhere.

What indentation would you expect here?:
```js
const x = array
    .map(n => n+1)
```
You might say that there is no semicolon so the user obviously intends to chain another array method, so we need indentation.
Then what about users who don't use semicolons? This is ambiguous.

Maybe the solution is to first guess the semicolon preference from the current file. Or maybe we assume it needs indentation, but if the user doesn't type a dot then we dedent the line? The point is, I think this should be a discussion in https://github.com/microsoft/language-server-protocol

**Comment by OliverJAsh** [comment] 2021-02-18 20:25
Very good points. I don't have any answers unfortunately.

**Comment by NotWearingPants** [comment] 2021-02-18 20:34
Although I found the place to fix this specific problem, but I'm not sure what to change 😅

https://github.com/microsoft/vscode/blob/bcc49ca4b67723b90e40998a159e18fc4c45dbf9/extensions/typescript-language-features/src/languageFeatures/languageConfiguration.ts#L16-L53

**Comment by FilipePintoReis** [comment] 2021-03-07 18:04
I have noticed that languages that enforce the use of semicolon in the end of a statement also display this issue (I've tried with with Java and C) so it might be worth looking into it.

**Comment by FilipePintoReis** [comment] 2021-03-16 00:17
I've been changing this but nothing is happening for some reason.
I've changed `increaseIndentPattern` to `increaseIndentPattern: / /,` and expected that when typing 
```
if(true){
}
```
If I hit enter right after opening curly braces, no indent increase would happen.

I've been running by opening debug on VS, choosing `Launch VS Code` from the dropdown, and hitting run.
For some reason, this freezes the VS code window, so I just ctrl + shift + F5 to restart and I manage to open VS code.

Does anyone know what I'm doing wrong in order to test this?

**Comment by Jemt** [comment] 2024-05-05 21:11
Probably related: https://github.com/microsoft/vscode/issues/209802

**Comment by FlowIT-JIT** [comment] 2024-05-06 06:18
Related: https://github.com/microsoft/vscode/issues/209822

**Comment by aiday-mar** [comment] 2024-05-13 08:45
Hi @OliverJAsh thank you for posting the issue. This should be fixed with the changes made in this PR https://github.com/microsoft/vscode/pull/208222

**Closed by aiday-mar** 2024-05-13 08:45 UTC
Labels: bug, help wanted, typescript, javascript, editor-autoindent
