### ISSUE TITLE
 Uncaught TypeError: Cannot set property '1' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#27250] opened 2017-05-25 10:10 UTC
Issue Id: <b>a3a96766-beb6-7775-4316-c003528859e2</b><br /><br />*Versions* <br />- 1.12.2<br />*Stack* <br />TypeError: Cannot set property '1' of undefined<br />[/vs/base/common/filters.ts#L511:19 (score)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/base/common/filters.ts#L511:19 (score))<br />[/vs/editor/contrib/suggest/browser/completionModel.ts#L127:15 (fuzzyScore)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/contrib/suggest/browser/completionModel.ts#L127:15 (fuzzyScore))<br />[/vs/editor/contrib/suggest/browser/completionModel.ts#L98:8 (_createCachedState)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/contrib/suggest/browser/completionModel.ts#L98:8 (_createCachedState))<br />[/vs/editor/contrib/suggest/browser/completionModel.ts#L67:7 (_ensureCachedState)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/contrib/suggest/browser/completionModel.ts#L67:7 (_ensureCachedState))<br />[/vs/editor/contrib/suggest/browser/suggestModel.ts#L414:28 (items)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L414:28 (items))<br />[/vs/editor/contrib/suggest/browser/suggestModel.ts#L315:9 (onNewContext)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L315:9 (onNewContext))<br />[/vs/base/common/async.ts#L533:3 (runner)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/base/common/async.ts#L533:3 (runner))<br />

**Comment by jrieken** [comment] 2017-05-26 08:18
dupe of #26511

**Closed by jrieken** 2017-05-26 08:18 UTC
Labels: error-telemetry
