### ISSUE TITLE
Too many exclude settings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29629] opened 2017-06-27 14:57 UTC
Refs: #29478

Currently I feel like we have too many exclude settings in the settings.json, what is worse I am not sure what is their relation and which one applies where.

Do we really have user sceanrios that people want to fine grain this and that one exclude is not enough to bind them all?

files.exclude
files.watcherExclude
search.exclude

**Comment by bpasero** [comment] 2017-06-27 15:51
I consider files.watcherExclude a hack/workaround and not a typical use case. The others are valid imho, though the one (files.exclude) also applies to search.exclude. Maybe those two could be folded into one.

**Comment by roblourens** [comment] 2017-06-27 16:21
I like the separate files/search.exclude because I want to see some files in the explorer, like node_modules and build output, but not search them. Also it's always been that way.

**Comment by bpasero** [comment] 2017-11-15 17:49
Closing, "as designed".

**Closed by bpasero** 2017-11-15 17:49 UTC
Labels: settings, under-discussion
