### ISSUE TITLE
Provide option to code format only changed lines on save

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode#44610] opened 2018-02-27 15:45 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10

This is a feature request to have an option to code format only changed lines on a save.

I know about code format on type, but it's not always sufficient (because extensions may format only under certain situations -- for instance, when a new line is entered -- and it's possible that such a situation is not triggered for the format to happen).

**Comment by ppaul** [comment] 2018-04-27 19:03
sorry for not being present on the thread; this has nothing to do with #44804 
It doesn't make sens to talk about saving non-dirty files, of course. I'm sure it doesn't autoformat thousands of untouched files in a project

**Comment by chrisdias** [comment] 2019-08-02 17:52
this looks like a dupe of #44075

**Closed** 2019-08-02 17:52 UTC
Labels: *duplicate, feature-request
