### ISSUE TITLE
HTML snippets no longer work inside quotes

### ISSUE THREAD

**Issue by NiekPas** [Microsoft/vscode#13685] opened 2016-10-13 15:15 UTC
- VSCode Version: 1.6.0
- OS Version: Windows 10 (build 14393.222)

Steps to Reproduce:

1.  Open or create a .html file.
2. Type a double (") or single (') quote.
3. Start typing a snippet prefix (any predefined snippet, such as 'a' for a link, will do).

Expected behavior: the snippet will be highlighted and pressing tab will expand the snippet.
Observed behavior: nothing happens.

This is problematic for me because (for reasons I won't go into here) I often use snippets inside the the 'style' attribute of a html element. For instance, I have a snippet with the prefix 'stct' to enter 'text-align:center;'. This no longer works since version 1.6.0.

![vscode-snippets-issue](https://cloud.githubusercontent.com/assets/11707054/19354875/9396e14e-9168-11e6-9a53-ef7cd485be2e.gif)

**Comment by aeschli** [comment] 2016-10-14 06:09
duplicate of #13675

**Closed by aeschli** 2016-10-14 06:09 UTC
