### ISSUE TITLE
Bug with formatting conditional renders in JSX

### ISSUE THREAD

**Issue by 0xdeafcafe** [microsoft/vscode#57424] opened 2018-08-28 14:06 UTC
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
ue4-snippets|CAP|1.0.0
vscode-ipaddress|Com|1.0.0
minify|Hoo|0.3.0
emoji|Per|0.0.3
lorem-ipsum|Tyr|1.2.0
map-replace-js|Yuk|0.1.0
calculate|aca|2.1.0
vscode-mjml|att|1.4.0
vscode-custom-css|be5|2.7.1
random-string-password-generator|bib|1.0.1
unique-lines|bib|1.0.0
better-toml|bun|0.3.2
vscode-eslint|dba|1.5.0
vscode-hasher|dee|1.0.1
bower|don|0.0.3
githistory|don|0.4.2
xml|Dot|2.3.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.3.0
json-tools|eri|1.0.2
vscode-solution-explorer|fer|0.2.32
dotnet-test-explorer|for|0.5.2
vscode-guid|hea|1.3.1
beautify|Hoo|1.4.2
vscode-map-preview|jum|0.4.2
docomment|k--|0.1.2
insertdatetime|lar|0.0.1
vue|liu|0.1.5
rainbow-csv|mec|0.4.2
code-beautifier|mic|2.1.0
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
mssql|ms-|1.4.0
python|ms-|2018.7.1
azure-account|ms-|0.4.3
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
Go|ms-|0.6.88
mono-debug|ms-|0.15.8
PowerShell|ms-|1.8.3
vsliveshare|ms-|0.3.577
debugger-for-chrome|msj|4.8.2
peep|nwa|0.0.5
vscode-docker|Pet|0.1.0
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.5.3
polacode|pnp|0.2.2
vscode-yaml|red|0.0.15
classynaming|ref|1.2.0
vscode-sort-json|ric|1.13.0
LiveServer|rit|5.1.1
vscode-coverage-gutters|rya|2.1.1
final-newline|sam|0.3.2
code-settings-sync|Sha|3.1.0
slack|soz|0.0.14
code-spell-checker|str|1.6.10
ayu|tea|0.15.0
html-preview-vscode|tht|0.1.1
vscode-lldb|vad|0.8.9
full-react-snippets|wal|1.1.2
change-case|wma|1.0.0

(6 theme extensions excluded)
</details>

Steps to Reproduce:

1. Write a conditional rendering snippet in React that speads on to more than 1 line.
2. When it does, new lines (and the line you were last on) will go 1 indent too far to the left.

![](https://thumbs.gfycat.com/NarrowGleefulHerald-size_restricted.gif)

This has happened for awhile, although I only just got around to reporting it here.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-09-04 18:57
Please provide a code example (as text) that demonstrates the problem

**Comment by 0xdeafcafe** [comment] 2018-09-05 08:46
Anything inside the `customInputAllowed` conditional render will have weird formatting issues when editing.

```js
<table>
	<thead>
		<tr>
			<th>{'Field'}</th>
			<th>{'Current amount'}</th>
			<th>{'Refund amount'}</th>
			<th>{'Final amount'}</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{'Example field'}</td>
			<td>{'£23.34'}</td>
			<td>
				{!customInputAllowed && '£1.00'}
				{customInputAllowed &&
					<InputGroup>
						<InputGroupAddon addonType={'prepend'}>{'£'}</InputGroupAddon>
						<Input
							name={k}
							onChange={event => this.handleChange(k, event)}
							type={'text'}
							value={customRefund[k]}
						/>
					</InputGroup>
				}
			</td>
			<td>{'£22.34'}</td>
		</tr>
	</tbody>
</table>
```

**Comment by 0xdeafcafe** [comment] 2018-09-06 12:05
Yeah, it happens when you press enter. Can confirm it still happens in VSCode 1.27

**Comment by mjbvz** [comment] 2021-10-04 23:28
Closing due to lack of additional feedback since this was opened and the complexity of fixing the on enter rules without causing regressions

**Closed by mjbvz** 2021-10-04 23:28 UTC
Labels: bug, editor-contrib, editor-autoindent
