### ISSUE TITLE
emmet is wrong

### ISSUE THREAD

**Issue by Zzhiren** [Microsoft/vscode#26369] opened 2017-05-10 08:42 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.3.2|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.14.0|
|Theme-Dark-Dracula|gerane|0.0.2|
|Theme-Dracula|gerane|0.0.2|
|theme-material-theme|jprestidge|1.0.1|
|vetur|octref|0.6.8|
|material-icon-theme|PKief|2.0.5|
|code-settings-sync|Shan|2.7.0|
|vue-color|staychan|0.0.3|
|open-in-browser|techer|1.0.0|
|tmlanguage|Togusa09|0.7.1|
|theme-bluloco-dark|uloco|1.2.0|
|theme-dracula-soft|yomed|1.0.2|;

---

Steps to Reproduce:

1.when i open an new folder, in html i press tab can`t emmet
2.

**Comment by egamma** [comment] 2017-05-10 08:52
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by egamma** [comment] 2017-05-11 06:50
Cannot act on this issue without additional information. Closing the issue, please reopen when you add more information.

**Closed by egamma** 2017-05-11 06:50 UTC
Labels: needs more info
