### ISSUE TITLE
Extension contributed walkthroughs don't restore on reload

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128948] opened 2021-07-18 12:30 UTC
Repro:

1. Install Luna Paint
2. Open the walkthrough page for the extension
3. Reload the window, the welcome home will load

It appears to happen because the editor is restored before extensions activate. In console:

```
workbench.js:32 Could not restore to category Tyriar.luna-paint#exampleProject as it was not found
```

**Comment by JacksonKearl** [comment] 2021-08-13 22:12
Duplicate of #123525

**Closed by JacksonKearl** 2021-08-13 22:12 UTC
