### ISSUE TITLE
今天vetur更新后，主机还是会意外停止

### ISSUE THREAD

**Issue by 18267372741** [Microsoft/vscode#25498] opened 2017-04-27 00:42 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|stylus|Alan|0.0.4|
|project-manager|alefragnani|0.15.0|
|vue-snippets|hollowtree|0.1.1|
|vscode-lebab|jeremyrajan|1.0.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vetur|octref|0.6.3|
|vscode-docker|PeterJausovec|0.0.13|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment] 2017-04-27 04:45
Please open Vetur issues against that extension' repository: https://github.com/octref/vetur/issues

This may be a duplicate of https://github.com/octref/vetur/issues/155

**Closed by mjbvz** 2017-04-27 04:45 UTC
Labels: caused-by-extension
