### ISSUE TITLE
VSCode's replace function does not work on large files

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [Microsoft/vscode#58702] opened 2018-09-14 15:34 UTC
I have a 350MB text file with lots of white spaces. I'm trying to do a search and replace with regex:
`Search: /((\r\n|\n|\r)$)|(^(\r\n|\n|\r))|^\s*$/gm`
`Replace:`
VSCode does replace single lines, but does not respond when I press "replace all"
![image](https://user-images.githubusercontent.com/5278928/45560018-fe960700-b811-11e8-9178-cca505ef5281.png)

**Comment by rebornix** [comment] 2018-09-14 18:07
Duplicate of https://github.com/Microsoft/vscode/issues/40580, thanks for your feedback!

**Closed** 2018-09-14 18:07 UTC
Labels: *duplicate, editor-find
