### ISSUE TITLE
Keyboard shortcuts using default OS Keyboard layout and not follow switching

### ISSUE THREAD

**Issue by lpikora** [Microsoft/vscode#29012] opened 2017-06-19 09:32 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.10.0-22-generic (Ubuntu 17.04 Gnome 3)
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|EditorConfig|EditorConfig|0.9.3|
|code-settings-sync|Shan|2.8.1|
|string-converter|adamwalzer|0.0.9|
|Bookmarks|alefragnani|0.15.2|
|better-toml|bungcip|0.2.0|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|php-intellisense|felixfbecker|1.4.1|
|Angular2|johnpapa|2.3.3|
|vscode-scss|mrmlnc|0.6.2|
|tsimporter|pmneo|1.2.14|
|java|redhat|0.6.0|
|final-newline|samverschueren|0.3.2|
|blueprint|teamchilla|1.3.0|
|cordova-tools|vsmobile|1.2.7|
|gitblame|waderyan|1.11.3|
|twig|whatwedo|1.0.2|;

---

VS code using for Keyboard shortcuts default keyboard layout. When keyboard layout is switched to something else VS code Keyboard shortcuts still using default keyboard layout. Using Ubuntu 17.04 Gnome 3.

Steps to Reproduce:

1. Add new keyboard layout in systems keyboard layout settings (eg. `cs`)
2. Switch to `cs` keyboard layout
3. Pres `ctrl` + `key with /`, it should zoom out (`cs` layout has `-` on `/` key), but it toggle comment.

**Comment by alexandrudima** [comment] 2017-06-20 08:16
@lpikora On Linux, we have a couple of known issues.

* We don't detect a keyboard layout change while VS Code is running. - #23690

* We reflect what the X11 APIs tell us (the equivalent of `xkbmap -query`) but this does not work with some window managers, as changing a keyboard layout in these window managers does not result in any change to the X11 APIs - #23505 , #24166

This page also explains these known issues and some more -- https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings

I'm thinking this issue is a duplicate of one of the known issues.

**Comment by nemenos** [comment] 2017-06-29 06:37
Hello,
 the same happens on windows,
pressing ALT+Shift changes Windows current keyboard layout, but vscode still applies my italian default keyboard.

**Comment by alexandrudima** [comment] 2017-06-29 07:01
@nemenos 

Please create a separate issue, and please include the Windows version and VS Code version.

Your problem cannot be the same problem as the OP's, since there are completely separate code paths for keyboard handling on Windows and on Linux. In the new issue I will ask you for additional information.

**Closed** 2017-07-06 08:00 UTC
Labels: needs more info
