### ISSUE TITLE
lost my code edits

### ISSUE THREAD

**Issue by venky7799** [microsoft/vscode#104516] opened 2020-08-12 20:20 UTC
Issue Type: <b>Bug</b>

VS Code window crashed and I lost my code edits.there is debug.log file automatically generated. 

[0813/012027.557:ERROR:file_io.cc(89)] ReadExactly: expected 40, observed 0

how to get my code edit back

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:31:37.228Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.41GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.1.3
debugger-for-chrome|msj|4.12.9
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|4.0.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by venky7799** [comment] 2020-08-12 20:35
Anyone please help me. Hour's of work gone in 5sec.

**Comment by bpasero** [comment] 2020-08-13 07:33
Sorry to hear that, can you share the exact steps and what happened?

**Comment by venky7799** [comment] 2020-08-13 10:05
Yes sure, while coding my css file(with live server) , vs code editor suddenly got stuck and total system begun slowing down, nothing is working, then I just closed all tabs including vs editor and everything. Done some refreshing and opened vs code again. There is no code in my css file. A notification has appeared on right bottom saying vs code crashed and something(i haven't read totally). There is file generated automatically named dubug. Then again I restarted whole system. But no use.

**Comment by venky7799** [comment] 2020-08-13 10:07
[0813/012027.557:ERROR:file_io.cc(89)] ReadExactly: expected 40, observed 0


This is file generated debug.log

**Comment by bpasero** [comment] 2020-08-13 11:45
Is this with a local file system or a remote one or even a network share?

**Comment by venky7799** [comment] 2020-08-13 12:12
On local file..

**Comment by bpasero** [comment] 2020-08-13 12:19
I fear there is a little chance that this can happen if VSCode crashes while writing to the target file. Writing to a file always truncates it first and then writes the contents. However, we do keep a backup of non-saved contents unless `files.hotExit` is disabled, but I assume you did not touch this setting?

**Comment by venky7799** [comment] 2020-08-13 12:22
![IMG_20200813_175134.jpg](https://user-images.githubusercontent.com/63292604/90133767-ad8c4600-dd8d-11ea-8bfc-873ebf58823a.jpg)

**Comment by venky7799** [comment] 2020-08-13 12:24
Nope not at all haven't touched any thing. Even haven't written any code at all. Just closed that folder and vs code.

**Comment by venky7799** [comment] 2020-08-13 12:32
Please save me.

**Comment by bpasero** [comment] 2020-08-13 12:55
So to clarify, you were editing `style.css` and then `debug.log` appeared?

**Comment by venky7799** [comment] 2020-08-13 13:07
Yes..i think After vs code hanged , and I closed everything

**Comment by bpasero** [comment] 2020-08-14 07:37
I am sorry I cannot be of more help here without fully understanding what happened. 

My last idea is to check if `%APPDATA%\Code\Backups` has anything inside to restore from. This is the location where backups are made for any dirty file. However, if there was a backup, it should open when you open Code, so I guess it is not there?

**Comment by bpasero** [comment] 2020-08-14 09:13
Duplicate of https://github.com/microsoft/vscode/issues/98063

**Closed by bpasero** 2020-08-14 09:13 UTC
Labels: needs more info
