### ISSUE TITLE
On PC 'Delete' key not working on insiders for approx last week

### ISSUE THREAD

**Issue by acotty** [microsoft/vscode#123040] opened 2021-05-06 01:29 UTC
On Windows 10 with insiders for the last 5 to 7 days the delete key has been doing "funny" things like and the issues have changed, but still does not work correctly.
1) When editing files pressing the delete key has deleted in the terminal window.
2) With the latest pressing the delete key a pop up with the test "Cannot read property 'dispose' of undefined" occcurs.
3) I cannot find any area where the delete key works like it did before a week ago.

The delete key works fine in all other windows apps, so the physical keyboad is okay.

If you need logs or anything else please let me know and I will try to supply the data/info ASAP.

Version: 1.57.0-insider (user setup)
Commit: b95b73b7b074f5dddccd57e5e290617f1a767ec1
Date: 2021-05-05T17:20:18.311Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Extension | Author (truncated) | Version
-- | -- | --
vscode-openapi | 42C | 4.5.0
Handlebars | and | 0.4.1
ng-template | Ang | 11.2.14
swagger-viewer | Arj | 3.0.1
npm-intellisense | chr | 1.3.1
path-intellisense | chr | 2.3.0
vscode-markdownlint | Dav | 0.40.4
vscode-eslint | dba | 2.1.20
githistory | don | 0.6.16
xml | Dot | 2.5.1
gitlens | eam | 11.4.1
EditorConfig | Edi | 0.16.4
tslint | eg2 | 1.0.46
vscode-npm-script | eg2 | 0.3.21
git-project-manager | fel | 1.7.1
vscode-firefox-debug | fir | 2.9.4
code-runner | for | 0.11.3
docker-explorer | for | 0.1.7
vscode-pull-request-github | Git | 0.25.1
docker-linter | hen | 0.5.0
rest-client | hum | 0.24.5
angular-essentials | joh | 11.0.0
Angular2 | joh | 11.0.0
openapi-lint | mer | 1.2.0
Angular-BeastCode | Mik | 10.0.3
file-downloader | min | 1.0.10
mindaro | min | 1.0.120210423
vscode-docker | ms- | 1.12.1
vscode-kubernetes-tools | ms- | 1.3.2
mssql | ms- | 1.10.1
python | ms- | 2021.4.765268190
jupyter | ms- | 2021.6.812916528
remote-containers | ms- | 0.177.0
remote-wsl | ms- | 0.56.1
cpptools | ms- | 1.3.1
vscode-typescript-tslint-plugin | ms- | 1.3.3
debugger-for-chrome | msj | 4.12.12
debugger-for-edge | msj | 1.0.15
vscode-run-git-difftool | nar | 0.0.5
angular2-inline | nat | 0.0.17
material-icon-theme | PKi | 4.6.0
swaggitor | qns | 0.1.1
diff | raf | 0.0.1
vscode-yaml | red | 0.18.0
partial-diff | ryu | 1.4.3
markdown-preview-enhanced | shd | 0.5.18
prettier-vscode | Sim | 2.0.7
vscode-taskexplorer | spm | 2.0.7
vscode-icons | vsc | 11.4.0
gitblame | wad | 6.0.2
debug | web | 0.25.0
JavaScriptSnippets | xab | 1.8.0
json | Zai | 2.0.2

**Comment by gjsjohnmurray** [comment] 2021-05-06 02:27
Does the problem also happen when all your extensions are disabled? Maybe use the "Start Extension Bisect" command in order to investigate.

**Comment by acotty** [comment] 2021-05-06 02:31
Is there any easy way to disable all extensions at once? If not I will read up on the bisect blog posting I seen previously.

**Comment by acotty** [comment] 2021-05-06 02:34
I have disabled all of the extensions and the delete key is still poping up the "Cannot read property 'dispose' of undefined" in the edit window and does not remove breakpoints.

Its it working for you on Windows?

**Comment by JacksonKearl** [comment] 2021-05-06 05:40
Can you run "Developer: Toggle Keyboard Shortcuts Troubleshooting" and include the logs it generates concerning how the delete key is being handled?

**Comment by feeva** [comment] 2021-05-06 05:45
Here's mine when I press the delete key:

[2021-05-06 14:44:43.466] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Delete, keyCode: 46, key: Delete
[2021-05-06 14:44:43.466] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Delete, keyCode: 20 ('Delete')
[2021-05-06 14:44:43.467] [renderer1] [info] [KeybindingService]: | Resolving Delete
[2021-05-06 14:44:43.467] [renderer1] [info] [KeybindingService]: \ From 12 keybinding entries, matched workbench.action.terminal.killInstance, when: terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus, source: built-in.
[2021-05-06 14:44:43.538] [renderer1] [info] [KeybindingService]: | Resolving Delete
[2021-05-06 14:44:43.539] [renderer1] [info] [KeybindingService]: \ From 12 keybinding entries, matched workbench.action.terminal.killInstance, when: terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus, source: built-in.


> Can you run "Developer: Toggle Keyboard Shortcuts Troubleshooting" and include the logs it generates concerning how the delete key is being handled?

**Comment by JacksonKearl** [comment] 2021-05-06 05:49
@feeva I presume you did not have the terminal tabs tree focused at that time? 

cc @meganrogge are the context keys maybe being incorrectly set?

**Comment by feeva** [comment] 2021-05-06 05:50
@JacksonKearl I removed the key binding. So now I don't know that for sure. Do you still need to know?

**Comment by JacksonKearl** [comment] 2021-05-06 05:59
It would be helpful for debugging to know if your focus was in on the terminal tabs view, in which case running `workbench.action.terminal.killInstance` would make sense, or elsewhere, in which case we shouldn't have dispatched to that command and it might be the case that some of the context keys we use to determine how to route keybindings my be incorrectly set. 

This problem is appearing now because terminal tabs are a new feature with this iteration.

**Comment by feeva** [comment] 2021-05-06 06:13
Ah, yeah, the new terminal tabs. I like it anyway. 👍

My focus was in the editor. I was just doing just normal edit activities. But I'm not sure the terminal was open or not.

**Comment by acotty** [comment] 2021-05-06 06:30
Plot thickens, when I first run the "Developer: Toggle Keyboard Shortcuts Troubleshooting" command I get the following error as I have deleted the initial powershell terminal as I use the "javascript Debug Terminal" as my default.

[2021-05-06 12:32:18.733] [renderer1] [error] Terminal with ID 1 does not exist (has it already been disposed?): Error: Terminal with ID 1 does not exist (has it already been disposed?)
    at W._getIndexFromId (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2714:29334)
    at W.setActiveInstance (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2714:24738)
    at file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2120:32850
    at l.fire (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58655
    at file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:3623
    at l.fire (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at r._set (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:124:31818)
    at r.set (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:124:31633)
    at p.setSelection (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:142:9062)
    at file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2120:31876
    at l.fire (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2714:15732
    at l.fire (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at W.setActiveTabByIndex (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2714:24996)
    at W._removeTab (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2714:23753)
    at file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2714:15623
    at l.fire (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at l.fire (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1856)
    at f._onInstanceDisposed (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1802:26559)
    at file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1802:25962
    at l.fire (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at ii.dispose (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2627:111308)
    at file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2124:1403
    at b._runForSelectionOrInstance (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2124:1708)
    at R.M [as _actionCallback] (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2124:1369)
    at R.run (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:30505)
    at _.runAction (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:30953)
    at _.run (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:30855)
    at f.onClick (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:33980)
    at Immediate._onImmediate (file:///C:/Users/andrew/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:33512)
    at processImmediate (internal/timers.js:461:21)

**Comment by acotty** [comment] 2021-05-06 06:30
The log when I press the delete key is:

[2021-05-06 16:30:11.937] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Delete, keyCode: 46, key: Delete
[2021-05-06 16:30:11.938] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Delete, keyCode: 20 ('Delete')
[2021-05-06 16:30:11.938] [renderer1] [info] [KeybindingService]: | Resolving Delete
[2021-05-06 16:30:11.938] [renderer1] [info] [KeybindingService]: \ From 11 keybinding entries, matched workbench.action.terminal.killInstance, when: terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus, source: built-in.
[2021-05-06 16:30:12.080] [renderer1] [info] [KeybindingService]: | Resolving Delete
[2021-05-06 16:30:12.080] [renderer1] [info] [KeybindingService]: \ From 11 keybinding entries, matched workbench.action.terminal.killInstance, when: terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus, source: built-in.

**Comment by acotty** [comment] 2021-05-06 06:35
The log when I press the delete key with the focus in the breakpoint window and press the delete key after selecting a breakpoint via the mouse:
[2021-05-06 16:34:37.107] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Delete, keyCode: 46, key: Delete
[2021-05-06 16:34:37.108] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Delete, keyCode: 20 ('Delete')
[2021-05-06 16:34:37.109] [renderer1] [info] [KeybindingService]: | Resolving Delete
[2021-05-06 16:34:37.109] [renderer1] [info] [KeybindingService]: \ From 11 keybinding entries, matched workbench.action.terminal.killInstance, when: terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus, source: built-in.

**Comment by acotty** [comment] 2021-05-06 06:45
More details:
1) The delete key works until you delete the initial powershell terminal.

I did the following:
1) Start VSC  - default terminal is powershell
     - can delete
2) Add a new Powershell terminal via the new tab feature 
     - can delete
3) Add a  Javascript Debug terminal via the new tab feature 
     - can delete
4) Delete the second powershell terminal 
     - can delete
3) Delete the initial powershell
    ***** DELETE STOPS WORKING ****

I also did the following
1) Start VSC  - default terminal is powershell
     - can delete
2) Add a  Javascript Debug terminal via the new tab feature 
     - can delete
3) Delete the initial powershell
    ***** DELETE STOPS WORKING ****

**Comment by acotty** [comment] 2021-05-06 06:46
Let me know if I can do anything more.

**Comment by GreenBlackSky** [comment] 2021-05-06 08:35
I've encountered the same issue with the delete key. It started working after I removed following binding:
`{ "key": "delete",                "command": "workbench.action.terminal.killInstance",
                                     "when": "terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus" },`
Though, now I can't delete open terminals in terminal side panel with the delete key.

**Comment by acotty** [comment] 2021-05-06 09:21
Yes more info:
If I delete the terminal by the old terminal dropdown the del key wored fine, so the issue is further refined to the new tab delete functionality not working the same as the old functionality.

**Comment by dan1994** [comment] 2021-05-06 11:25
Just updated to 1.56.0 and the delete key stopped working.
When a terminal is open, the delete key focuses on the terminal, and after disposing of the terminal it just doesn't do anything.

This is the log from pressing delete:
```
[2021-05-06 14:21:21.586] [renderer2] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Delete, keyCode: 46, key: Delete
[2021-05-06 14:21:21.586] [renderer2] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Delete, keyCode: 20 ('Delete')
[2021-05-06 14:21:21.587] [renderer2] [info] [KeybindingService]: | Resolving Delete
[2021-05-06 14:21:21.587] [renderer2] [info] [KeybindingService]: \ From 11 keybinding entries, matched workbench.action.terminal.killInstance, when: terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus, source: built-in.
```
Removing the `workbench.action.terminal.killInstance` works as a workaround.

About info:
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by eMuonTau** [comment] 2021-05-06 15:20
All shortcuts using `terminalTabsFocus` not working. `Delete` and `F2` in my case. 

Version: 1.56.0
OS: Linux x64 5.4.0-72-generic (Linux Mint 20.1)

**Comment by Tyriar** [comment] 2021-05-06 15:25
Are people experiencing this all using the new terminal tabs, or is it happening with tabs disabled?

**Comment by abitofmaya** [comment] 2021-05-07 07:37
@Tyriar, It also happens when Terminal Tabs are disabled. When the editor is in focus, if you hit DELETE, it switches focus to the Terminal.

**Comment by hosseini44444** [comment] 2021-05-07 09:29
I have kinda the same issue and it happens until I disable tabs and restart VScode.
In Windows 10 after enabling terminal tabs and deleting a terminal, When I press delete in editor it deletes the selected terminal tab instead of deleting a character.

**Comment by 4thex** [comment] 2021-05-07 10:09
I can confirm that I deleted the PowerShell terminal, and that is when the delete key stopped working. Adding a PowerShell terminal back made it work again.

**Comment by wolf99** [comment] 2021-05-07 15:56
Have this on the update I received today.
All kinds of hinky stuff going on when terminal tabs are enabled (good job it's preview ay! 😊).

After updating but before restarting, default terminals started disappearing from the terminal picker until I had only two "Ubuntu (WSL)" there, why there were two of those I don't know either.

I update, restart vs code
I set Ubuntu (WSL) as the default profile, with terminal tabs enabled.
I opened and then closed a terminal using Ctrl+' followed by Ctrl +d
Then when I try to use the del key in the settings.json file a toast alert says "Cannot use 'in' operator to search for instanceId in 4"

Resolution requires disabling terminal tabs and restarting vs code

**Comment by Tyriar** [comment] 2021-05-07 17:41
@wolf99 

> After updating but before restarting, default terminals started disappearing from the terminal picker until I had only two "Ubuntu (WSL)" there, why there were two of those I don't know either.

Not totally clear what you mean here, could you create a gif in a new issue?

> Additionally terminal titles seem to not be dynamic regardless of the setting of overrideName or even when "terminal.integrated.profiles.{platform}" is removed completely.

Tracked in https://github.com/microsoft/vscode/issues/123104

**Comment by acotty** [comment] 2021-05-08 00:30
I have tested it on the following version and my reported del key problem is now fixed.

Version: 1.57.0-insider (user setup)
Commit: a19565da7dfc739fa26e36aae96113e19fe3806f
Date: 2021-05-07T17:19:03.737Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by meganrogge** [comment] 2021-05-08 00:59
Hey thanks so much, we intend to close this issue w the PR headed for the release branch of stable on Tuesday, so will keep it open until then @acotty

**Comment by acotty** [comment] 2021-05-08 04:10
I did not think about the 1.56.x release branch... I know if there is a next time for a bug I raise.

**Comment by Lycolia** [comment] 2021-05-12 10:41
I'm having this issue with the latest release, is there anything I can do to resolve this issue?
Or wait for the 1.57.0 release?

Version: 1.56.1 (user setup)
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:05.141Z (6 日前)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Tyriar** [comment] 2021-05-12 11:38
@Lycolia 1.56.2 is coming soon which will have this fixed

**Closed** 2021-05-12 11:37 UTC
Labels: bug, candidate, important, integrated-terminal, integrated-terminal-tabs
