### ISSUE TITLE
[Debug]Error pop-up should go away once user fix all the errors and started debugging.

### ISSUE THREAD

**Issue by v-pavanp** [microsoft/vscode#4597] opened 2016-03-23 05:19 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open a folder for "Blank Node.js TypeScript" project.
2. Click on debug icon from the view bar and set node debugger.
3. It will generate a launch.json file with some default settings.
4. Try to debug and verify error messages.
   5 try to generate few more errors by updating invalid entries in launch.json.
5. Now fix all the error by updating launch.json and start debugging.
6. Verify command prompt and make sure it should not generate any error message.

Actual: 
Error message pop-up remains forever and user needs to click on close button to get rid from error popup. 

Debugger started and command prompt displaying message like below with error pop-up.
node --debug-brk=29322 --nolazy BlankNodeJSTypeScriptApp\server.js 
Debugger listening on port 29322

![image](https://cloud.githubusercontent.com/assets/17735796/13976372/8580fa5a-f07c-11e5-8639-4836677e1352.png)
![image](https://cloud.githubusercontent.com/assets/17735796/13976224/175dbc9e-f07b-11e5-9f05-c8a559e3e6f6.png)

 Debug control action hidden behind the error pop-up.
![image](https://cloud.githubusercontent.com/assets/17735796/13976214/d9e005fc-f07a-11e5-9e09-37c8ef56ed00.png)

Expected: Once user fixed the errors and start debugging then error pop-up should not be displayed.

**Comment by isidorn** [comment] 2016-03-23 08:16
Currently our error reporting infrastructure is just designed in that way, the error is in the users face and he has to explicitly do something about it. Error messages do not get automatically hidden anywhere else in vscode - and doing what you are suggesting - hidding all error messages once a user start debugging might hide some errors which are not related to debugging.

Closing this as designed and forwarding to @bpasero to verify and maybe check if he has some smart ideas.

**Comment by bpasero** [comment] 2016-04-29 08:21
@isidorn I actually started to clean up error messages from failing saves to files once the file gets saved successfull, so I would not think this is a pattern (not cleaning up errors). If we can automatically remove errors, I would do it!

**Comment by isidorn** [comment] 2016-04-29 13:46
@bpasero I can always remove all message service messages on debug start which does not seem smart. I do not see any other api in message service except hideAll, but I can look into it more

**Comment by bpasero** [comment] 2016-04-29 15:33
Every call to show() returns a function to hide().

**Comment by isidorn** [comment] 2016-05-02 21:57
@bpasero I can nicely clean up all the msgs which I create in the debug world, however most of the errors I just bubble up to the central error handling place. In that case I have no handle on how to hide the error message. Not sure if I can do something in this case?

**Comment by isidorn** [comment] 2016-05-04 10:06
ping @bpasero there is no smart way to dispose these error messages that get handled in the central error handling location?

**Comment by bpasero** [comment] 2016-05-04 10:08
No, we would have to introduce more smartness around errors (e.g. have a category "debug" for them) to be able to do this. Or actually allow to generate a UUID with an error that you could then use in the message service to close a message.

**Comment by isidorn** [comment] 2016-05-04 10:13
I could introduce this UUID smartness in the message service. Are there more use cases for this?
If this is the only use case, I would push it to the backlog until more people want to use it.

**Comment by bpasero** [comment] 2016-05-04 10:27
I dont think we have another use case atm.

**Comment by gpuido** [comment] 2017-09-19 08:12
Is there any new setting to get around this problem today ?
I would much prefer to be able to disable those error popups.
Why not log these errors somewhere like the 'Problems' tabs of the console ?

**Comment by connor4312** [comment] 2019-10-08 22:59
It looks like this particular error is gone, but errors in the debug contribution in general have been moved over to the `IDialogService`, whose `show()` method and `IShowResult` do not allow for dismissal. Should this issue be closed as designed again @isidorn?

**Closed** 2019-10-09 09:02 UTC
Labels: *out-of-scope, debug, feature-request
