### ISSUE TITLE
Profiles don't sync views (secondary sidebar)

### ISSUE THREAD

**Issue by Zerotask** [microsoft/vscode#180163] opened 2023-04-17 20:45 UTC
Does this issue occur when all extensions are disabled?: not tested

- VS Code Version: 1.77.3
- OS Version: Windows 10

Steps to Reproduce:

1. drag something to the secondary sidebar
2. switch profile
3. close secondary sidebar
4. switch back to the previous profile
5. secondary sidebar isn't visible

I'd assume that my view is saved to the profile. If I switch to another profile, I don't want to see the secondary sidebar.
If I switch then back to the profile, I want to see the secondary sidebar.

**Comment by Zerotask** [comment] 2023-04-19 21:32
After step 5 I opened the secondary sidebar and I see the view/content. Just to be sure, my issue is that I must open the secondary sidebar manually. I'd assume, after I switch back to this profile, the secondary sidebar is automatically opened.
Generally spoken, I'd like to have my appearance to be saved in my profile.

**Comment by sandy081** [comment] 2023-05-10 06:39
This is because the expansion state of a view / sidebar is not scoped to profile. It is scoped to workspace/folder you have opened. Hence closing this as designed

CC @sbatten

**Closed by sandy081** 2023-05-10 06:39 UTC
Labels: info-needed, user-profiles
