### ISSUE TITLE
[UX] Searching in search widget. The results were collapsed, but the button was also "Collapse All"

### ISSUE THREAD

**Issue by zero00072** [microsoft/vscode#203422] opened 2024-01-25 09:03 UTC
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.86.0-insider
Commit: 1091f68d834974d78cd4f9769034b4ae4581ff2a
Date: 2024-01-24T05:35:58.929Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.86.0-insider Chrome/118.0.5993.159 Electron/27.2.3 Safari/537.36
- OS Version: Debian GNU/Linux trixie/sid

Steps to Reproduce:

1. Open a folder of code.
2. Search something in search widget.

Expect:

Collapse all results. But keep Expand/Collapse button at top right **Expand All**, shows `[+]`.

Real result:

Collapse all results. The Expand/Collapse button at top right is **Collapse All**, shows `[-]`. I can not either click it.

![search_collapse](https://github.com/microsoft/vscode/assets/2072036/3d5d8914-9ac2-4ec3-9957-2139f512b293)

Maybe it is associate with #203378.

**Comment by zero00072** [comment] 2024-01-25 09:12
Addition, my `settings.json` is:

```json
{
  "search.collapseResults": "alwaysCollapse"
}
```

**Comment by zero00072** [comment] 2024-02-16 03:24
@andreamah I have found this issue almost been resolved. I can not reproduce it in recently version.

![search_expand](https://github.com/microsoft/vscode/assets/2072036/80d76805-9bac-446c-a156-289de79f09dc)

**Comment by andreamah** [comment] 2024-02-16 17:56
I think this was fixed by https://github.com/microsoft/vscode/pull/205235. I actually think this was a duplicate of https://github.com/microsoft/vscode/issues/204316. Thanks for pointing this out!

/duplicate https://github.com/microsoft/vscode/issues/204316

**Closed** 2024-02-16 17:56 UTC
Labels: bug, search, *duplicate, confirmed
