### ISSUE TITLE
Editor progress slider is moving without end

### ISSUE THREAD

**Issue by wclr** [microsoft/vscode#113903] opened 2021-01-06 11:15 UTC
- VSCode Version: 
1.52.0-insider
050a123750e4ef4009930d0da1ff7a1a6441d4f3
x64
- OS Version: Windows 10

Not sure how to name it correctly, talking about this thing, which is constantly moving:

![image](https://user-images.githubusercontent.com/736697/103762142-9cdcb500-5039-11eb-8261-48c3bdf4deb2.png)

So it starts constantly moving after some operation and never stops. The question is: how to debug to what process does it refer to and how to stop it without full window reload?

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by bpasero** [comment] 2021-01-06 13:25
> So it starts constantly moving after some operation and never stops.

A good start would be to tell us the operation you start.

**Comment by wclr** [comment] 2021-01-14 19:43
@bpasero I think get what action case it:

I press Ctrl+Alt+F to get file formatted, but there is not formatter configure so I get the notice:
> There are multiple formatters for 'PureScript' files. Select a default formatter to continue. 
With `Configure...` button.

I press cancel. An progress slider starts to run. To and it I just press Ctrl+Alt+F again and cancel it. After that it doesn't start to progress "run", even if I try to format agan.

**Comment by jrieken** [comment] 2021-01-15 08:11
https://user-images.githubusercontent.com/1794099/104698402-9c1ae180-5711-11eb-9fb1-3e50678f5868.mov

Does not reproduce for me. Please provide repro steps and make sure to use latest insiders

**Comment by wclr** [comment] 2021-01-15 11:42
Try to press ESC instead of clicking the cross in the floating popup. Clicking cross form stops it too for me, pressing ESC doesn't.

![purs-vscode-format](https://user-images.githubusercontent.com/736697/104723093-8bd62700-5750-11eb-927b-d87cac54762a.gif)

**Comment by jrieken** [comment] 2021-01-15 12:46
Thanks for clarifying. The problem is that ESC doesn't dismiss the message but it hides it. Notice the little dot on the bell icon. Adding @bpasero for what to do here

<img width="55" alt="Screenshot 2021-01-15 at 13 45 11" src="https://user-images.githubusercontent.com/1794099/104728918-e9aa4500-5737-11eb-9387-6f2a072ffd68.png">

**Comment by bpasero** [comment] 2021-01-15 12:49
Well that is expected because we bind `Escape` to hiding toasts:

![image](https://user-images.githubusercontent.com/900690/104729230-6b01d780-5738-11eb-81fe-817777c4e89e.png)

If you don't like that, you can rebind `Escape` to `notifications.clearAll`

**Comment by bpasero** [comment] 2021-01-15 12:51
Hm, I think I take that back, looks like "Clear All" keeps the ones with progress around because we want a user to be aware that something is running in the background.

Maybe I have not fully understood the issue then: it seems there is a operation running that is not cancelled, so it would make sense to keep showing the progress bar for as long as that is true, no?

**Comment by wclr** [comment] 2021-01-15 17:40
> Maybe I have not fully understood the issue then: it seems there is a operation running that is not cancelled, so it would make sense to keep showing the progress bar for as long as that is true, no?

From UX perspective pressing ESC should cancel the operation. It hides the popup. And if Ctrl+Alf+F called the second time, pressing ESC cancels operation (no progress running anymore).

**Comment by bpasero** [comment] 2021-01-16 07:11
@wclr I am not sure I would agree. It is very easy to press escape in the editor for whatever reason and you might not be aware that this cancels a background operation. I would only think that escape should cancel if this is very obvious (e.g. the progress thing being a modal dialog and presented prominently to the user).

**Comment by wclr** [comment] 2021-01-16 13:28
> I am not sure I would agree. It is very easy to press escape in the editor for whatever reason and you might not be aware that this cancels a background operation. 

So it not random key pressing here. And pressing ESC in this case removes popup related to formatting operation, and thus creates the impression that this question was closed. But the progress bar continues to run and it is not clear what to do next.

**Comment by bpasero** [comment] 2021-01-16 14:43
@wclr are you seeing the progress operation in the status bar at least? I think we configured notifications that show progress to indicate this also in the status bar when they get hidden to make sure users can get back to it easily.

**Comment by wclr** [comment] 2021-01-16 18:57
I've posted the full-screen gif I see. So I know what to do with this issue now. But if you say that it works as intended, ok, but I see that behaviour is inconsistent from the UX perspective.

**Comment by jrieken** [comment] 2021-01-19 14:32
I have pushed a change that makes us show a model dialog when a default formatter is required. Cancelling that will cancel the underlying operation.

@bpasero I leave it up to you if we want to make tweaks to the notifications or not

**Comment by bpasero** [comment] 2021-01-19 14:39
I am still thinking that people have built a lot of muscle memory to hit `Escape` key whenever a notification appears and think that blindly cancelling any running operation as a result of that would cause a lot more frustration than being helpful. The idea of `Escape` is to quickly dismiss a notification toast so that it can continue in the background. The idea was never to cancel the operation. Keyboard focus is inside the editor when the toast appears and it is already a bit on the edge that pressing `Escape` while the editor has focus hides the toasts, but we did that for a fast way to get out of notification spam. I would not add the ability to cancel running operations via `Escape` by default.

One thing that is missing is a command the user can bind to cancel a notification that has progress, so I am fine to have a new issue for that and leave this one for verification.

**Comment by jrieken** [comment] 2021-01-19 15:48
Makes sense. Closing this as being specific for format

**Comment by jrieken** [comment] 2021-01-19 15:48
To verify:

* install multiple formatter for a language
* select format document from the menu (context menu or command palette)
* verify that a modal dialog shows that makes you select a default formatter
*

**Closed by jrieken** 2021-01-19 15:48 UTC
Labels: bug, formatting, workbench-notifications
