### ISSUE TITLE
How to use my MS account to sync settings in VS Code?

### ISSUE THREAD

**Issue by haimat** [microsoft/vscode#110086] opened 2020-11-06 14:44 UTC
- VSCode Version: 1.51.0
- OS Version: Windows 10

Steps to Reproduce:
I am trying to sync my VS Code settings via my MS account. So in VS Code I click on to the "Accounts" button in the lower-right corner, then I selecte the "Turn on settings sync ..." option, then I leave all options selected in the popup and click on to the "Sign in & Turn on" button, then I select "Sign in with Microsoft", which opens a new browser window/tab at location

    localhost:65508/signin?nonce=51WxyZA16ATjV7nsMVFlrg==

However, that keeps on loading forever, nothing happens.  
Is this an issue on my end, how can I select my MS account for VS Code sync?

Does this issue occur when all extensions are disabled?: Yes

**Comment by epicodertime** [comment] 2020-11-06 15:02
here is a doc https://code.visualstudio.com/docs/editor/settings-sync#:~:text=You%20can%20turn%20on%20Settings,and%20UI%20State%20are%20supported. to help please not this is for bugs and feature request so I will close this bug

**Comment by haimat** [comment] 2020-11-06 15:07
> here is a doc https://code.visualstudio.com/docs/editor/settings-sync#:~:text=You%20can%20turn%20on%20Settings,and%20UI%20State%20are%20supported. to help please not this is for bugs and feature requests

Well, I have seeen and followed this help page.
However, the issue here is that the MS account selection step in the browser does not work.

**Comment by epicodertime** [comment] 2020-11-06 15:10
try reinstalling your browser and also try using the system file checker on Windows 10 to see if an update bricked some functionally  https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

**Comment by haimat** [comment] 2020-11-06 15:13
> try reinstalling your browser and also try using the system file checker on Windows 10 to see if an update bricked some functionally https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

I have also tried the default Edge browser of Windows 10, but experience the very same issue here too.
It seems the problem is not the browser, but something else.
But how can I debug this issue?

**Comment by epicodertime** [comment] 2020-11-06 15:20
i don't think there is a way for me to debug it can you reinstall vs code or check if there is any updates

**Comment by epicodertime** [comment] 2020-11-06 15:23
i also noticed that there is issues with server errors when trying to sync https://github.com/microsoft/vscode/issues/92705

**Comment by mkvlrn** [comment] 2020-11-07 13:33
@haimat I had the same issue, having the MS signin page be something in localhost as well when using the Remote WSL extension, opening a folder within my WSL(2).

When opening a "local" windows folder - and not using Remote WSL - I could sign in using my MS account. But once I go back to WSL Remote it remains signed off.

It's definitely an issue with this new version, and it has nothing to do with your browser.

**Comment by haimat** [comment] 2020-11-08 11:44
> It's definitely an issue with this new version, and it has nothing to do with your browser.

Thanks for the feedback - I can confirm that I also develop on WSL.

**Comment by RMacfarlane** [comment] 2020-11-09 15:58
Closing as a duplicate of https://github.com/microsoft/vscode/issues/104674

**Closed by RMacfarlane** 2020-11-09 15:58 UTC
Labels: new release
