### ISSUE TITLE
Empty Run and Debug section

### ISSUE THREAD

**Issue by dpkirchner** [microsoft/vscode#137094] opened 2021-11-13 00:17 UTC
Issue Type: <b>Bug</b>

At some point the "Run and Debug" section in VSCode became blank, and I'm not sure why. It had been working fine about an hour ago. I don't believe I made any changes that should have caused this, although I was working on a local copy of an extension when the section became blank. I have tried a couple of things: `git clean -fdx` in my workspace and removed the directory from my VSCode recents list to try to start from scratch, switched projects, modified launch.json hoping to trigger a reload, reloaded VSCode manually several times.

I've tried with and without the `--disable-extensions` flag but that had no effect. The extension I am working on is disabled globally.

The section is populated as expected when using the insiders build, so maybe there's some configuration lingering somewhere. I haven't found any in `~/.vscode`. Is there another directory to check? Unfortunately, it's difficult to find it myself as I was working on the vscode-js-debug extension specifically and there are obviously a lot of matches for that in `~/Library/Application Support/Code` as you'd expect.

This is a duplicate of issue: https://github.com/microsoft/vscode/issues/128135

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.84GB free)|
|Process Argv|--crash-reporter-id 0d505d6d-ccae-4312-bfae-ab12f60f20a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.3
ndjson-colorizer|bus|1.0.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.0.0
nasc-touchbar|fel|1.12.0
vscode-pull-request-github|Git|0.32.0
terraform|has|2.16.0
saltstack|kor|0.0.9
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.0
rewrap|stk|1.15.2
code-spell-checker|str|2.0.12
vscodeintellicode|Vis|1.2.14
JavaScriptSnippets|xab|1.8.0

(6 theme extensions excluded)

</details>

**Comment by dpkirchner** [comment] 2021-11-13 00:32
Re-enabling the built-in Javascript Debug extension seems to fix this, but that's obviously not a solution as that's the very extension I'm working on. Maybe that part isn't solvable here. But...

Would it be possible to update the "Run and Debug" section so it shows a useful message when the extension is disabled? (I'm not sure what it should be. Is there a way to detect that there's no enabled extensions capable of supplying "Run and Debug" options?)

**Comment by weinand** [comment] 2021-11-15 09:16
This is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/5794.

The issue with the empty "Run and Debug" has been addressed by https://github.com/microsoft/vscode/issues/136450.

**Closed by weinand** 2021-11-15 09:16 UTC
Labels: new release
