### ISSUE TITLE
Command "toggle editor group sizes" leads to undefined visual state

### ISSUE THREAD

**Issue by david-scepanovic-nutanix** [microsoft/vscode#136651] opened 2021-11-08 09:23 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62
- OS Version: Windows 10 (ssh -> CentOs7)

Steps to Reproduce:

1.  Split files over multiple editor groups (e.g. 2)
2. Toggle activity bar (to ON)
3. Focus on **any** editor group
4. Toggle Editor group size (focused editor group becomes maximized)
5. Toggle activity bar (to OFF)

**Comment by sbatten** [comment] 2021-11-08 18:21
I think this is a dupe of this issue https://github.com/microsoft/vscode/issues/70083, please let me know if I am mistaken

**Closed by sbatten** 2021-11-08 18:21 UTC
