### ISSUE TITLE
when clause contexts not support '||' operator and '()'

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#46389] opened 2018-03-23 05:00 UTC
- VSCode Version: 1.21.1
- OS Version: Mac OS 10.13.3

It seems only support ``&&`` operator

### Not Support '||'

```json
"when": "a || b"
```

### Not Support '(  )'

```json
"when": "a && b (c==1 || d==2)"
```

Here is I how to implement it. ugly but works

```json
{
    "menus": [
               {
                    "command": "gpm.openInCurrentWindow",
                    "group": "context",
                    "when": "viewItem == a"
                },
                {
                    "command": "gpm.openInCurrentWindow",
                    "group": "context",
                    "when": "viewItem == b"
                },
  ]
}
```

Got any better idea? or implement this feature.

**Comment by alexandrudima** [comment] 2018-03-28 13:37
Duplicate of #33547

**Closed by alexandrudima** 2018-03-28 13:37 UTC
Labels: keybindings
