### ISSUE TITLE
The sparkling button that allowed me to use AI to write my git messages is gone ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [microsoft/vscode#200491] opened 2023-12-10 19:23 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.0
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. open `source control` -> no sparkling button (paid copilot is required)

**Comment by lszomoru** [comment] 2023-12-12 08:13
@MohamedAliRashad, did you previous use this functionality through the GitLens extension? We are looking at making it easier to contribute an action to the source control input that resulted in a temporary breaking change.

**Comment by lszomoru** [comment] 2023-12-12 12:32
@MohamedAliRashad, do you have the Copilot and Copilot Chat extensions installed? If so, could you please share the exact versions of the two extensions? Also does your workspace contains multiple git repositories?

**Comment by MohamedAliRashad** [comment] 2023-12-12 20:20
GitHub Copilot: v1.142.0
GitHub Copilot Chat: v0.11.0


_Also does your workspace contains multiple git repositories?_
**Yes**

**Comment by lszomoru** [comment] 2023-12-13 13:29
Thanks! Closing as duplicate of https://github.com/microsoft/vscode/issues/200375.
The fix is already in VS Code Insiders and will be released to Stable later this week.

**Closed by lszomoru** 2023-12-13 13:29 UTC
Labels: info-needed
