### ISSUE TITLE
日本語入力の未確定状態で文字列が正しく表示されない

### ISSUE THREAD

**Issue by qtamaki** [microsoft/vscode#141852] opened 2022-01-30 23:42 UTC
Issue Type: <b>Bug</b>

日本語で入力している最中に、変換候補が出た状態で文字列の一部が欠けるという減少が起きている。MacでGoogle日本語入力を使用している

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id ad187c4f-c252-4cd9-b9a9-291d595905a6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-insertdatestring|jsy|2.3.0
vscode-language-pack-ja|MS-|1.63.3
scala|sca|0.5.5
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by lramos15** [comment] 2022-01-31 14:42
Based on using online translation looks like it relates to entering Japanese characters into the editor

**Comment by tamuratak** [comment] 2022-02-01 05:53
It might be duplicate of #138704

**Comment by lramos15** [comment] 2022-02-01 15:03
@tamuratak This seems likely since they aren't on insiders.

@qtamaki Feel free to try [insiders](https://code.visualstudio.com/insiders/) and if that doesn't work reopen. You can also wait a week for the new release of VS Code which will contain this fix.

**Closed by lramos15** 2022-02-01 15:03 UTC
Labels: needs more info, *english-please, translation-required-japanese
