### ISSUE TITLE
Split screen for windows 11 is missing from scode

### ISSUE THREAD

**Issue by m0usaa** [microsoft/vscode#144387] opened 2022-03-04 11:59 UTC
I'd like vscode developers to enable the new windows 11 split screen feature in the program in next update
thank you best wishes ❤️

**Comment by IllusionMH** [comment] 2022-03-04 12:39
/duplicate of #127449

If you meant something else please create new issue with more details.

**Closed** 2022-03-04 12:40 UTC
Labels: *duplicate
