### ISSUE TITLE
Document format is very slow | CPU | Any extention

### ISSUE THREAD

**Issue by justnonamenoname** [Microsoft/vscode#15416] opened 2016-11-13 02:47 UTC
- VSCode Version: 1.5-1.7.1 (didn't tested <1.5)
- OS Version: Windows 7

Redirect from:
https://github.com/Microsoft/vscode/issues/15221#issuecomment-260099727
&
https://github.com/Microsoft/vscode-cpptools/issues/345

I can't reopen original issue

Steps to Reproduce:

1. Check Format Document on this file - 40k lines
www.gta-samp.com/size.cpp

clang-format.exe works 1 second
but Code.exe stuck at CPU 100% for a minute

Visual Studio 2013 format this file in second

If you delete ms-vscode.cpptools and install 
marketplace.visualstudio.com/items?itemName=ryannaddy.vscode-format
or change filename to .css Code.exe will stuck at CPU 100% too

Also run
extention dir\ms-vscode.cpptools-0.9.2\LLVM\bin
clang-format.exe size.cpp
it will format in 3 seconds too

It's not problem of extension

**Comment by aeschli** [comment] 2016-11-14 09:06
duplicate of #15221

**Closed by aeschli** 2016-11-14 09:06 UTC
