### ISSUE TITLE
Debug toolbar contributed commands missing when toolbar is docked

### ISSUE THREAD

**Issue by readyiman** [microsoft/vscode#115945] opened 2021-02-05 23:14 UTC
Issue Type: <b>Bug</b>

I works with Flutter and just updated VSCode to version 1.53 yesterday and this thing is happen:

1. Debug Console auto scroll stop scrolling to the end of line, it somehow always stop prematurely at start (just scroll a bit and then stop).
2. Flutter hot reload button was missing  from  Run buttons. The function ctrl+F5 still works though.

I think this is VSCode bug, and not Flutter/Dart bug. Because it happens after 1.53 update.

The Auto Scroll part is really annoying for me.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (4 x 3691)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.08GB free)|
|Process Argv|--crash-reporter-id a704c221-6da9-4cb2-9758-c753a081462d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.19.1
flutter|Dar|3.19.0
githistory|don|0.6.14
todo-tree|Gru|0.0.196

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by readyiman** [comment] 2021-02-06 14:57
I found the problem.
1. Auto scroll on Debug Console not working because of Word Wrap. `debug.console.wordWrap` .Turning it off make it works.
2. Flutter hot reload button disappear if `debug.toolBarLocation` is docked. It's appear fine on floating.

The Flutter button on left panel already feels normal after latest extension update. Or it is already normal at first (Please ignore this last issue, maybe I'm just tired).

**Comment by isidorn** [comment] 2021-02-08 09:24
I can not reproduce this, can you share an exact reproducable steps for this?
@dantup do you also see this? Did I break this again?

**Comment by DanTup** [comment] 2021-02-08 09:56
@isidorn honestly, I haven't seen scrolling work right for quite a while. Each time I saw it I assumed the previous fix hadn't made stable yet (although in hindsight it does seem like a while now).

I just tried running Dart-Code's tests (TypeScript) though, and I'm not seeing *any* output in the Debug Console at all, which definitely doesn't seem right. The window on the left here is the extension code and the Debug Console should be filling up with Mocha output as the tests are running.

<img width="1742" alt="Screenshot 2021-02-08 at 09 53 34" src="https://user-images.githubusercontent.com/1078012/107203691-a4ee9280-69f3-11eb-8686-98239de9f1a9.png">

I'll let the run finish and see if anything shows up and post back. If nothing, I'll see if I can repro it and provide instructions for you to run the same thing.

**Comment by DanTup** [comment] 2021-02-08 10:18
The screenshot above turned out to be because I was running in `noDebug` mode. I thought I used to get the test output even in that mode, but that doesn't seem to be the case today. Running without `noDebug` *does* show the output. It's probably unrelated to the scrolling issue being discussed here.

I did test with a Flutter app though, and was unable to reproduce either issue noted above (scrolling issues, or the hot reload button missing from the debug toolbar).

**Comment by isidorn** [comment] 2021-02-08 13:41
@dantup thanks for trying it out. Let's keep this open and see if more users face this
@readyiman can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by readyiman** [comment] 2021-02-08 21:22
Its actually easy to reproduce for me.
First run a Flutter project.

To see that Debug Console not auto scrolling right you need:
1. Long and multiple text to show on it, like when your project has Google Map widget. 
2. Make sure word wrap setting is on `debug.console.wordWrap`
3. Make sure your Debug Console window width is narrow.

To see Flutter hot reload missing:
1. Just change `debug.toolBarLocation` setting to docked.

**Comment by isidorn** [comment] 2021-02-09 17:01
@dantup can you repro that the hot reload is missing when `debug.toolBarLocation` is docked?

I can not reproduce this with mock debug. As I nicely see contributed actions in the debug toolbar

![Screenshot 2021-02-09 at 18 01 17](https://user-images.githubusercontent.com/1926584/107399299-d608b900-6b00-11eb-9f8c-62bfe97bb0dc.png)

**Comment by DanTup** [comment] 2021-02-09 17:41
@isidorn actually, I can repro that:

![Feb-09-2021 17-38-25](https://user-images.githubusercontent.com/1078012/107403991-ae642180-6afd-11eb-84b2-d8262c700222.gif)

I'm not really sure why. The definition is here:

https://github.com/Dart-Code/Dart-Code/blob/1fc34a7651dd3560cea71207e29669ca530792ef/package.json#L994-L999

There is a context on it that changes after the debug session starts (we wait to see whether the hot reload service is available in the debugger before enabling it). This was enabled by https://github.com/microsoft/vscode/issues/69398 - is it possible that's not applying correctly when docked?

**Comment by DanTup** [comment] 2021-02-09 17:42
The Inspector button is also disappeared - that also has a context on it (also toggled after the session starts, in a `handleDebugSessionStart` handler).

**Comment by DanTup** [comment] 2021-02-09 17:45
Also - I was able to reproduce the scrolling issue in my TypeScript project (the Dart-Code extension). I made the window really narrow and ran the mocha tests, and after a few tests, I saw the scroll bar flashing and getting smaller, but the window was no longer scrolling:

<img width="401" alt="Screenshot 2021-02-09 at 17 44 16" src="https://user-images.githubusercontent.com/1078012/107404762-81fcd500-6afe-11eb-8bf3-fbb36d787413.png">

This is running the "Dart Tests + DA" debug config from the Dart-Code repo (although they might not run well without a Dart SDK on PATH, so it may be easier to repro with just a basic set of TS tests/console output and a narrow window).

**Comment by Kooni-Boop** [comment] 2021-02-14 20:16
i had this issue with my old mac, and i fixed it by disabling debug console's word wrap.

**Comment by isidorn** [comment] 2021-02-19 15:19
I can reproduce the issue of the flutter commands not showing up in debug viewlet toolbar when it is docked. I know what is the problem and I will look into the fix.

For the auto scroll, please create a new issue if you can reproduce this consistently

**Comment by DanTup** [comment] 2021-02-25 12:08
@isidorn I repro'd with mock-debug and just resizing the window, so I've opened https://github.com/microsoft/vscode/issues/117674 with details. Thanks!

**Comment by isidorn** [comment] 2021-02-25 12:38
Great, thanks!

**Comment by isidorn** [comment] 2021-03-04 14:35
Unfortunately it is currently not possible for me fix the contributed actions in the debug toolbar to show up in the view menu. With the current api available to me I can not just listen to menu registration and re-register the commands to a different menu.
For a clean solution I would need to be able to specify a custom menu id fo the title area of my viewlet so that menu is also taken into account.
However not that many users use debug toolbar as docked so I think we are good for now,

**Comment by DNACore** [comment] 2021-07-06 06:29
> @isidorn actually, I can repro that:
> 
> ![Feb-09-2021 17-38-25](https://user-images.githubusercontent.com/1078012/107403991-ae642180-6afd-11eb-84b2-d8262c700222.gif)
> 
> I'm not really sure why. The definition is here:
> 
> https://github.com/Dart-Code/Dart-Code/blob/1fc34a7651dd3560cea71207e29669ca530792ef/package.json#L994-L999
> 
> There is a context on it that changes after the debug session starts (we wait to see whether the hot reload service is available in the debugger before enabling it). This was enabled by #69398 - is it possible that's not applying correctly when docked?

I found the same issue...Any it isn't fixed till now.

**Comment by testforstephen** [comment] 2021-07-23 03:00
In Java debugger, we contribute a hotCodeReplace button to the debug toolbar. This button disappears as well when the debug toolbar is docked. See issue https://github.com/microsoft/vscode-java-debug/issues/1024

**Comment by isidorn** [comment] 2021-08-10 14:47
I pushed a fix for this. It would be great if you can try it out and let me know how it works.
I double checked and for me this now works as expected

**Closed** 2021-08-10 14:46 UTC
Labels: bug, debug

**Comment by DanTup** [comment] 2021-08-12 15:19
Fix looks good, thanks!

<img width="367" alt="Screenshot 2021-08-12 at 16 18 41" src="https://user-images.githubusercontent.com/1078012/129222893-925470ea-989b-4a73-a83c-60382237e50a.png">

**Comment by isidorn** [comment] 2021-08-13 07:58
@DanTup thanks a lot Dan for verifying, adding verified label.
