### ISSUE TITLE
Provide a way to show the editor hover while debugging

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#84561] opened 2019-11-12 07:57 UTC
Currently when your program stops at a breakpoint, hover on symbols will trigger evaluate DAP request automatically. And LSP doesn't receive hover request, so no way to show the javadoc during debugging. 

Really like having a way to trigger the javadoc during debugging. It could be a shortcut to trigger javadoc manually. Or VS Code client intelligently determines sending the hover request to the correct server (DAP or LSP) based on the hover context. If the hover context is a variable, send to DAP, otherwise, to LSP.

**Comment by isidorn** [comment] 2019-11-14 14:57
The issue here is that debug hides all other hovers to show the debug custom hover.
Due to that the javadoc hover is not shown.

This is a design limitation of the debug.
However I will leave this open as a feature request to debug so we support this scenario in the future.
As you suggest, the user could explicitly trigger the regular hover.

**Comment by testforstephen** [comment] 2019-11-15 02:40
> As you suggest, the user could explicitly trigger the regular hover.

The problem is it's not possible to trigger it manually, because the javadoc request is not exposed to user.

**Comment by Trass3r** [comment] 2020-08-26 13:05
Duplicate of #99856?

**Comment by isidorn** [comment] 2020-08-26 13:42
Actually this is an older issue, so closing that one.

**Comment by isidorn** [comment] 2020-08-26 13:43
Idea from @dantup and @weinand use the `alt` key to switch between hovers

**Comment by Trass3r** [comment] 2020-08-26 13:46
I think Ctrl would be more natural for the fingers.

**Comment by isidorn** [comment] 2020-08-26 13:50
We use `alt` in other places in VS Code as a way to show "ALTernative" content

**Comment by DanTup** [comment] 2020-08-26 14:22
I don't know what it is on Windows, but on Mac if you hold down Cmd when hovering over symbols, it shows a preview of the definition. If this is Ctrl or Alt on Windows, it might be wise to avoid using the same one (otherwise the hover might be larger than expected because it'll have a code snippet in it too).

**Comment by isidorn** [comment] 2020-09-17 09:13
I have pushed the following change:
While debugging while a user is holding down the `alt` key we do not show the debug hover, but the regular editor hover. 
I tried this out and seems to work quite nicely. But I would be interested a lot in feedback. So try it out with VS Code insiders from Friday and let me know how it goes. I will also present this in our daily team meeting to get more feedback, so still not closing this issue.

Some open questions:
* How to make this `alt` behavior more discoverable
* Is it frustrating to hold down alt key while reading a long JSDoc

Alternative approach would be to just have a global command that toggles the hover behavior. However this felt more "heavy" to me and I personally prefer the `alt` approach.

@dantup Thanks for feedback. I have verified and on Windows this is `Ctrl`. So it seems like the `alt` key is free for this.

fyi @weinand @connor4312

**Comment by Trass3r** [comment] 2020-09-17 11:07
>     * How to make this `alt` behavior more discoverable

That would be my main concern too. Maybe there needs to be a 'status bar' in the popup reading "hold Alt for ...". I vaguely remember something like that from VS.

> Alternative approach would be to just have a global command that toggles the hover behavior. However this felt more "heavy" to me and I personally prefer the `alt` approach.

You probably need to switch fast and often so that would be way too clumsy.

**Comment by DanTup** [comment] 2020-09-17 11:10
If something like that is done, it should be probably include the others (for example the Cmd/Ctrl behaviour I mentioned above). There are lots of little things like that that aren't very discoverable right now (I only found that one by accident because it was rendering badly due to some other issues).

**Comment by isidorn** [comment] 2020-09-17 12:56
Feedback from standup was positive. With the overall impression that the ideal solution would be to just show both the regular hover and the debug hover at the same time. However since this is currently not possible due to the way how editor layout hovers this alt approach is a good workaround.

Feedback once you try it out is very welcome.
Status in the debug hover just to always show "hold Alt..." message sounds like a bit too much, especialy since it does not bring value once user figures it out.

**Closed** 2020-09-17 12:57 UTC
Labels: debug, feature-request

**Comment by heartacker** [comment] 2020-09-17 14:45
if we can add an new pendant(little button?) to the debug popup, while debugging, show the debug popup when hovered, user will see the pendant.
 than user can move The cursor to the pendant, then show the comments or infos from lsp. if there is no info, hide the pendant

**Comment by testforstephen** [comment] 2020-09-18 08:51
I tried `⌥ + hover` in macOS, the javadoc for a symbol can pop up when debugging a Java program. But i see two issues for the fix:
- Cannot pin the javadoc triggered by `⌥ + hover`. 
If i release the key `⌥ `, the doc will disappear immediately. As comparison, in a normal `hover` ux, if the mouse focus is still on the widget and it will keep there. This is useful when reading a long doc.
- `⌥ + hover` will cause the normal `hover` action not working.
  Below are the reproduce steps:
  - Starting a debug session, and stop at a breakpoint.
  - Stop debugging session.
  - `⌥ + hover` at a symbol.
  - `hover` at a symbol, no javadoc anymore.

A new global command to trigger javadoc at the selected symbol would be a good option. With this, you didn't need deal with the debugging state.

**Comment by isidorn** [comment] 2020-09-18 09:00
I have pushed a smoother transitoin between the debug hover and the editor hover.

@testforstephen thanks a lot for trying out out.
1) Good feedback. I will try to improve this right now
2) I just pushed a fix for this

As for the global command I would only add this if this `alt` approach proves bad. Before that I would first think about making it more discoverable.

**Comment by isidorn** [comment] 2020-09-18 16:15
I have also pushed a commit to tackle 1)

Please try it out with VS Code insiders from monday and let me know how it behaves now. Thanks a lot!

**Comment by testforstephen** [comment] 2020-09-21 08:52
@isidorn tried again, the latest insider works well.

**Comment by isidorn** [comment] 2020-09-21 12:01
Great! I will also create a small test plan item for this so we cover it in Endgame week.
