### ISSUE TITLE
Automatic multiple cursor on HTML tags

### ISSUE THREAD

**Issue by DezembroYD** [microsoft/vscode#87271] opened 2019-12-18 17:51 UTC
- VSCode Version: 1.41.0 
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create HTML file
2. Write `<div></div>`
3. Put the cursor after the last html tag word (ex: v, from div)
4. 
![image](https://user-images.githubusercontent.com/41813537/71109639-628d4500-21a4-11ea-9632-9b0257845bcf.png)
5. VSC automatic create a new cursor in the closing tag

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2019-12-18 19:01
It's functions as designed, see [HTML mirror cursor](https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor)

Do you experiencing any bugs with this behavior? Post also contains info how to configure this behavior if needed.

**Comment by DezembroYD** [comment] 2019-12-18 19:26
Resolved!

But that wasn't active before the latest update.

Maybe the latest update automatically turned on?

**Comment by IllusionMH** [comment] 2019-12-18 22:57
@DezembroYD this is new feature from latest version 1.41 (which was released last week) and it is enabled by default. However you can turn it off if you prefer.

Do you see any bug or problems with this feature? If not could you close this issue?

**Comment by octref** [comment] 2019-12-19 20:46
As @IllusionMH mentioned, it's a new feature, if you don't like it you can turn it off.

**Closed** 2019-12-19 20:46 UTC
Labels: *as-designed, html

**Comment by suryasarafe** [comment] 2020-01-02 10:22
thank you @IllusionMH, i searching name of the feature, and it's named 

> Mirror Cursor On Matching Tag

in settings, i don't want this feature active, make many of my code have wrong position.

this have issue when your cursor on div or other html tag and move below or above the selected line code, and somewhere in your code just move without permission

**Comment by JohnnyTMD** [comment] 2020-01-21 08:04
> It's functions as designed, see [HTML mirror cursor](https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor)


Finally found how to disable that.
I can't make any use of that, only makes me more troubles.

**Comment by garg10may** [comment] 2020-01-28 15:55
such a bogus feature. remove it or disable by default. More importantly, I was thinking there's some extension doing it.

**Comment by Seairth** [comment] 2020-01-31 03:17
In my case, every time I started typing an attribute, the mirror cursor was also adding it to the closing tag! Maybe this is because I am working with Angular templates, but it doesn't really matter. This should be an opt-in feature.

**Comment by bradleypeabody** [comment] 2020-02-02 04:21
This is also particularly dangerous when the closing tag is too far down and not visible.  You are then automatically editing something you can't even see.

If you accidentally mis-match your tags it is even worse, as it will modify the wrong closing tag.

This seems like something that should be activated with a keystroke, not automatic.

**Comment by octref** [comment] 2020-02-03 14:09
This is made an opt-in feature: https://github.com/microsoft/vscode/issues/87737#issuecomment-577095726

**Comment by rjsteinert** [comment] 2020-02-08 17:06
This has been driving me nuts! Thank you!
