### ISSUE TITLE
There are file path and folder path in the log output by the terminal. Use CTRL + Click to always open a new window  ?

### ISSUE THREAD

**Issue by love596310898** [microsoft/vscode#137419] opened 2021-11-14 05:00 UTC
🚨 The issue tracker is not for questions 🚨
There are file path and folder path in the log output by the terminal. Use CTRL + Click to always open a new window, but my expected file path open on current window and folder path open on a new window?
[this a error screenshot](https://love596310898.github.io/img/vscode.error.png) 
Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Tyriar** [comment] 2021-11-19 13:58
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal

**Comment by love596310898** [comment] 2021-11-20 03:51
> Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
> 
> /label "needs more info" terminal

[this a error screenshot](https://love596310898.github.io/img/vscode.error.png)

**Comment by love596310898** [comment] 2021-11-22 02:40
![vscode error](https://user-images.githubusercontent.com/27677166/142793142-2a02f159-f528-4817-be0a-a5c744350225.png)

**Comment by Tyriar** [comment] 2021-11-22 15:08
I can't reproduce this but I've seen reports in the past. Will probably be easy to fix once we have a solid repro case.

**Comment by love596310898** [comment] 2021-11-23 01:15
thanks, I am just feedbacked some info and hope vscode becomes better. Actualy this problem is not  imptcted my work!

**Comment by Tyriar** [comment] 2022-12-07 22:42
We can't action this without a repro case unfortunately, closing off to keep the issue count manageable.

**Closed by Tyriar** 2022-12-07 22:42 UTC
Labels: bug, confirmation-pending, terminal-links
