### ISSUE TITLE
source.addMissingImports does not work without CheckJS

### ISSUE THREAD

**Issue by MrOxMasTer** [microsoft/vscode#180503] opened 2023-04-21 12:27 UTC
Type: <b>Bug</b>

I use js/jsx . I want to use the function "source.addMissingImports": true, but This function does not work without checkJS: true. I don't need type checking in js/jsx files, but without it, the automatic addition of missing imports doesn't work. Is it possible to somehow differentiate or correct this? It seems to me that these are generally different functions that should work separately from each other, but without check JS does not work.

VS Code version: Code - Insiders 1.78.0-insider (3ad5774eb8123d4224eb55629df9e5f82fe13b99, 2023-04-14T05:25:56.476Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.60GB free)|
|Process Argv|--crash-reporter-id 8d5950e0-2632-4265-9569-e267bad308c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-color-picker|Ant|0.0.4
htmltagwrap|bra|0.0.9
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
vscode-faker|dee|2.0.0
gitlens|eam|13.5.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.12.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
backticks|fra|1.7.0
todo-tree|Gru|0.0.226
google-translate|han|1.2.8
stylelint-plus|hex|0.56.6
vscode-htmlhint|HTM|1.0.4
discord-vscode|icr|5.8.0
hungry-delete|jas|1.7.0
styled-components-snippets|jon|0.10.0
google-fonts|lio|0.0.1
vscode-scss|mrm|0.10.0
css-responsive-jsx-tsx|MrO|1.1.3
vscode-language-pack-ru|MS-|1.78.2023041909
color-highlight|nau|2.5.0
px-to-rem|sai|1.3.1
svg-preview|Sim|2.8.3
guides|spy|0.9.3
autoimport|ste|1.5.4
code-spell-checker|str|2.20.4
code-spell-checker-russian|str|2.0.9
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.2.4
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.3.0
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
material-theme|zhu|3.15.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
6233i204:30659907
functionswalk:30687959
pythonms35:30671666
pythonfmttext:30716741
pythonclientmv:30700173
showcppwkth:30715168

```

</details>

**Comment by MrOxMasTer** [comment] 2023-04-21 12:28
source.add Missing Imports refer to codeAction, and checkJS refer to another.

**Comment by mjbvz** [comment] 2023-04-21 16:44
Duplicate of #180001

Please don't open duplicate issues just because you're unhappy with the answer you got

**Closed by mjbvz** 2023-04-21 16:44 UTC

**Comment by MrOxMasTer** [comment] 2023-04-21 20:50
> Duplicate of #180001
> 
> Please don't open duplicate issues just because you're unhappy with the answer you got

Because you don't solve the problem, you just give up on it. Your function doesn't work at all, and you're sitting there and rubbing some kind of game into me.

**Comment by MrOxMasTer** [comment] 2023-04-22 13:20
> Duplicate of #180001
> 
> Please don't open duplicate issues just because you're unhappy with the answer you got

and where to file a complaint about useless moderators and deleting comments?

**Comment by MrOxMasTer** [comment] 2023-04-22 13:21
> Duplicate of #180001
> 
> Please don't open duplicate issues just because you're unhappy with the answer you got

and where to file a complaint about useless moderators and deleting comments?
