### ISSUE TITLE
"problems" output on dart seems buggy

### ISSUE THREAD

**Issue by mbagusrd** [Microsoft/vscode#56556] opened 2018-08-16 11:49 UTC
Issue Type: <b>Bug</b>

"PROBLEMS" view in dart programming seems buggy .. 
It shows many error but the counter says 3 
and when I click on it sometimes doesnt navigate to the editor

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:25:59.521Z)
OS version: Linux x64 4.15.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2103)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.59GB (0.40GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|0.0.2
dart-code|Dar|2.17.1
flutter|Dar|2.17.1

</details>

**Comment by sandy081** [comment] 2018-08-16 12:02
Duplicate of #56371

**Closed** 2018-08-16 12:02 UTC
Labels: *duplicate, new release
