### ISSUE TITLE
[createInstance] extensionManagementService depends on downloadService which is NOT registered.

### ISSUE THREAD

**Issue by mrkanister** [Microsoft/vscode#58097] opened 2018-09-06 17:04 UTC
Issue Type: <b>Bug</b>

After upgrading to Visual Studio Code v1.27.1, managing extension via the command line started to show unexpected output on STDERR:

```
$ code --list-extensions
[createInstance] extensionManagementService depends on downloadService which is NOT registered.
DavidAnson.vscode-markdownlint
ms-vscode.Go
stkb.rewrap
timonwong.shellcheck
```

Apart from the output, everything else seems to work fine as far as I can see.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 1960)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|7.41GB (1.73GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.20.0
Go|ms-|0.6.89
rewrap|stk|1.9.1
shellcheck|tim|0.5.1

</details>

**Comment by Evan-Yang** [comment] 2018-09-07 07:28
The same issue when i use Power Shell `code --install-extension C:\Tools\***.vsix` on Windows Server 2012 R2

**Comment by bdjurkan** [comment] 2018-09-07 10:02
Same issue.

**Comment by brendonjwong** [comment] 2018-09-07 18:16
I am experiencing the same issue on macOS High Sierra 10.13.4. My VS Code version matches the reporter's version.

**Comment by ke4ukz** [comment] 2018-09-08 18:03
I had this issue (1.27.1 x64 on Windows 10 Pro). It turns out I had a rule blocking outbound connections to various IP addresses in Windows Firewall. I disabled the rule and no longer received this message.

**Comment by shizonic** [comment] 2018-09-09 05:36
Same here on v. 1.27.1. On version 1.26.1 it didn't happen.

**Comment by bmarshalsea** [comment] 2018-09-09 12:04
Fresh install of 1.2.7.1 (x64) on new machine (SBook2) and it's doing this.
So general issue, not only an upgrade.

**Comment by shizonic** [comment] 2018-09-09 12:43
@bmarshalsea I think you mean 1.27.1

**Comment by sandy081** [comment] 2018-09-11 11:57
@jrieken `DownloadService` is marked as optional and why is the service dependency message shown still?

https://github.com/Microsoft/vscode/blob/6023a8a4b8f439c87bd8770ddca6495777523d08/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L144

**Comment by jrieken** [comment] 2018-09-11 12:45
@sandy081 This might be caused by a dependency of your dependencies

**Comment by sandy081** [comment] 2018-09-11 14:19
@jrieken There is no other service except `ExtensionManagementService` depends on `IDownloadService`. And, it marks the service as optional. When `ExtensionManagementService` is getting instantiated, `IDownloadService` is not available.

**Comment by jrieken** [comment] 2018-09-11 14:35
Hm, yeah. There is something with this. It might well be a false positive

**Closed** 2018-09-11 14:50 UTC
Labels: bug, cli

**Comment by egorse** [comment] 2018-09-14 12:19
1.27.2 - same

```
$ uname -a
Linux PC15326 4.4.0-134-generic #160~14.04.1-Ubuntu SMP Fri Aug 17 11:07:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ code --version
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
$ code --install-extension ms-python.python-2018.7.1.vsix
[createInstance] extensionManagementService depends on downloadService which is NOT registered.
Corrupt ZIP: end of central directory record signature not found
```

**Comment by sandy081** [comment] 2018-09-14 13:48
@egorse Fix is not available in 1.27.2. It is currently in our insiders and will be available in next stable (1.28) release.

**Comment by egorse** [comment] 2018-09-14 16:32
@sandy081 sorry - misunderstood reference just above my comment

**Comment by mrkanister** [comment] 2018-09-15 19:57
Just wanted to confirm that this issue is fixed in the insiders build.
Thank you, @sandy081 :)
