### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by JacksMaster** [microsoft/vscode#136507] opened 2021-11-05 11:00 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.0-dev.20211029

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:56969:22)
    at getPropertyOfType (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57629:24)
    at resolveESModuleSymbol (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49775:54)
    at getTargetOfNamespaceImport (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48977:28)
    at getTargetOfAliasDeclaration (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49211:28)
    at resolveAlias (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49256:30)
    at getSymbol (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47814:38)
    at resolveNameHelper (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48106:34)
    at resolveName (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48089:20)
    at resolveEntityName (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49428:42)
    at getTargetOfExportSpecifier (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49168:17)
    at getTargetOfAliasDeclaration (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49218:28)
    at resolveAlias (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49256:30)
    at resolveSymbol (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49246:67)
    at mergeSymbol (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47600:42)
    at d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47715:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47713:20)
    at mergeSymbol (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47624:21)
    at d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47715:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47713:20)
    at initializeTypeChecker (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:84949:21)
    at Object.createTypeChecker (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47371:9)
    at Object.getTypeChecker (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114340:79)
    at synchronizeHostData (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159795:21)
    at Proxy.getProgram (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159916:13)
    at ConfiguredProject.Project.updateGraphWorker (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164926:53)
    at ConfiguredProject.Project.updateGraph (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164855:42)
    at ConfiguredProject.updateGraph (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165848:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167572:25)
    at ProjectService.assignProjectToOpenedScriptInfo (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168655:44)
    at d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168995:97
    at Object.flatMap (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168995:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170153:46)
    at d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172086:88
    at IOSession.Session.executeWithRequestId (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172077:28)
    at IOSession.Session.executeCommand (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172086:33)
    at IOSession.Session.onMessage (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172112:35)
    at Interface.<anonymous> (d:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174717:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.63.0-insider (552af97a0170b43c9323bec62211feb184da9749, 2021-11-05T05:16:20.583Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.14GB free)|
|Process Argv|--crash-reporter-id aee561ce-1043-4278-8e1e-c80280f4d85e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
iconify|ant|0.2.2
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
headwind|hey|1.7.0
volar|joh|0.28.10
vscode-typescript-vue-plugin|joh|0.28.10
i18n-ally|lok|2.8.1
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-language-pack-zh-hans|MS-|1.62.2
vetur|oct|0.35.0
material-icon-theme|PKi|4.10.0
vscode-stylelint|sty|1.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593cf:30376535

```

</details>

**Comment by IllusionMH** [comment] 2021-11-05 11:42
/duplidate of https://github.com/microsoft/TypeScript/issues/46587

**Comment by IllusionMH** [comment] 2021-11-05 11:48
/duplicate of https://github.com/microsoft/TypeScript/issues/46587

Sorry for second notification - typo in command requires another comment to work

**Closed** 2021-11-05 11:48 UTC
Labels: *duplicate

**Comment by mjbvz** [comment] 2021-11-18 17:16
To help us investigate and fix this issue, please share an example project and the steps you follow to trigger this error. You can share this on https://github.com/microsoft/TypeScript/issues/46587
