### ISSUE TITLE
Unable to open vscode application

### ISSUE THREAD

**Issue by nielsonic** [microsoft/vscode#87786] opened 2019-12-27 22:08 UTC
<img width="425" alt="Screen Shot 2019-12-27 at 3 03 09 PM" src="https://user-images.githubusercontent.com/43583109/71534229-99590e80-28ba-11ea-8df4-015a85846189.png">
 
Running macOS Catalina Version 10.15.2

**Comment by IllusionMH** [comment] 2019-12-27 23:13
/duplicate of #74782

Please see steps in #74782 (comment) for current workaround.

**Closed** 2019-12-27 23:13 UTC
Labels: *duplicate
