### ISSUE TITLE
File names changed only by casing cause very bizarre behavior.

### ISSUE THREAD

**Issue by taicho** [Microsoft/vscode#40654] opened 2017-12-21 14:20 UTC
Upon refactoring a project and renaming some files (.ts) to have consistent casing I am noticing some extremely bizarre behavior. It's worth noting that I have Git with case-sensitivity enabled. That being said, I disabled Git via git.enabled in the workspace and restarted and still observe the same behaviors.

Example 1:
When editing one the files and saving the IDE opens up another instance of the file but with the old casing e.g. someFileName.ts -> SomeFileName.ts. At that point it seems to throw off the TS compiler built into VS Code and start reporting errors all of the files some of which are duplicate identifiers because it appears that at least in memory the IDE thinks it has two files with the same content that are separate...

Example 2:
Even if the file has not been saved and the other "ghost" file mentioned in example 1 has not appeared yet simple refactors such as identifier rename do not work yet when saving the new "ghost" file appears with the changes present but once again the IDE thinks it has two files with the same content which results in TS showing errors inline in files and "Problems".

What I've tried:
- Disabling Git for the workspace and restarting vscode.
- Restarting vscode multiple times. Other projects work fine.

Notes:
Even though the IDE shows the editor for the "ghost" file with the old casing it does not actually produce one in the file system.

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.2.0
html-snippets|abu|0.1.0
copy-syntax|ati|0.5.1
jshint|dba|0.10.15
tslint|eg2|1.0.24
docthis|joe|0.6.0
docomment|k--|0.0.17
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|4.0.0
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Create git repo.
2. Set git to be case-sensitive i.e. consider file name changes in case only to be considered changes.
3. Commit a file name like "SomeFile.ts" or "SomeFile.js"
4. Make changes to file and and rename to "someFile.js" or "someFile.ts".
5. Commit changes.
6. Open or restart Vs Code.
7. Perform edits on file and save.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment] 2017-12-22 09:22
> When editing one the files and saving the IDE opens up another instance of the file but with the old casing e.g. someFileName.ts -> SomeFileName.ts.

Can you record a screencast of this?

Also, can you really reproduce with `code --disable-extensions`?

**Comment by taicho** [comment] 2018-01-30 14:26
@joaomoreno Thanks for the follow-up on this!

Unfortunately I did try ```code --disable-extensions``` and did a whole day's worth of coding and still see the same behavior exhibited. The best I can figure is that because the commit history from a Git perspective contains the file with it's old casing somehow vs code is getting confused. It's getting really frustrating I can tell you that - it breaks all code evaluation, formatting functionality etc... and starts doing some really weird corruptions in the file.

I also tried completely deleting the repo and re-cloning which produces the same effects in vs code so that's why I've come to the conclusion that it has to do with the commit history and how vscode may use that in it's file resolution process. Oddly enough I disabled all source control in vscode and still saw the same behavior so I am uncertain. Also, worth noting these effects only occur on projects where casing of a file has been changed and committed (use git ignore case false).

I'm suprised nobody else seems to have run into this...

You can replicate by following these steps:
1. Create a projects (folder, npm, etc...)
2. Add a tsconfig.json (just so everything is the same as mine)
3. Create some .ts files e.g. Foo.ts.
4. Commit.
5. Set git ignore case false globally.
6. Rename file e.g. foo.ts
7. Commit.
8. Reload vscode.
9. Try formatting the .ts and working with the file a bit...eventually you will see the same file added to your "open editors" list and opened but with the old casing, when that happens everything will start getting really wonky if you try working with the current (lower-cased) file.

**Comment by joaomoreno** [comment] 2018-01-30 14:37
Can you record a screencast of this?

**Comment by taicho** [comment] 2018-02-09 18:37
@joaomoreno I've been a little lazy with the screencast so apologies for that. That being said, I **believe** this is in fact an issue with TypeScript itself. In my index.ts I had imports that referenced the files in their previously TitleCased format which I changed and suddenly VSCode is now behaving normally. Since the parsing and validation of TypeScript occurs in TypeScript and is passed to VSCode I'm guessing because the errors might have been reported with the "bad" filename casing and yet on disk there is only the camelCased file it was throwing everything off and causing VSCode to open a new window with the same file contents but with a different casing in the name as if the files were different causing all sorts of artifacts.

I'm tempted to create an issue in Microsoft/TypeScript.

**Comment by joaomoreno** [comment] 2018-02-12 09:30
Yes, this seems to have nothing to do with Git, especially if it reproduces even when Git is disabled.

**Comment by mjbvz** [comment] 2018-02-12 20:03
Duplicate of #12448

The root cause is how we handle changes to path case on case-insensitive file system. Still trying to understand if we can work around this somehow on the TS side

**Closed by mjbvz** 2018-02-12 20:03 UTC
