### ISSUE TITLE
Errors and warnings not highlighted in the code (JS, ESLint)

### ISSUE THREAD

**Issue by fila90** [microsoft/vscode#116305] opened 2021-02-10 10:30 UTC
- VS Code Version: 1.53.1
- OS Version: macOS Big Sur 11.2.1

Steps to Reproduce:

1. Open VSCode (stable or insiders)
2. Write something wrong

Does this issue occur when all extensions are disabled?: Yes

Since the last update errors and warnings are no longer being highlighted in the code (they used to be underlined, unused vars were greyed out etc.).
I tried removing/reinstalling the extensions, nothing works, only downgrading to version 1.52 fixes it.

They are still nicely shown in `PROBLEMS` panel.

**Comment by vrg-success** [comment] 2021-02-10 11:06
Some problem...

**Comment by dbaeumer** [comment] 2021-02-12 09:24
Since they are still nicely shown in the problems panel it is not a problem generating the issues (e.g. from TS or ESLint).

@alexdima assigning to you to see if there is something in the editor that makes the errors not being underlined there. 

@vrg-success which OS are you on.

**Comment by alexdima** [comment] 2021-02-12 10:15
@fila90 Does this problem reproduce when closing all instances of vscode and launching with a fresh user data dir (fresh settings) `code --user-data-dir=/Users/myuser/new/folder` ?

**Comment by soetji** [comment] 2021-02-12 16:15
It works for me when launching with a fresh user data dir. Otherwise it doesn't.

**Comment by alexdima** [comment] 2021-02-15 08:50
@soetji Thanks for the extra information. The way errors are rendered can be influenced via settings. Can you try commenting out your settings?

**Comment by fila90** [comment] 2021-02-15 10:50
@alexdima 
these are mine settings
```JSON
{
  "breadcrumbs.filePath": "off",
  "breadcrumbs.symbolPath": "off",
  "editor.acceptSuggestionOnEnter": "smart",
  "editor.colorDecorators": false,
  "editor.cursorBlinking": "smooth",
  "editor.cursorStyle": "line-thin",
  "editor.detectIndentation": false,
  "editor.fontSize": 12,
  "editor.hover.enabled": false,
  "editor.minimap.renderCharacters": false,
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.scrollBeyondLastLine": false,
  "editor.snippetSuggestions": "top",
  "editor.tabSize": 2,
  "editor.wordWrap": "on",
  "explorer.confirmDelete": false,
  "explorer.confirmDragAndDrop": false,
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/node_modules": true,
  },
  "files.insertFinalNewline": true,
  "files.trimFinalNewlines": true,
  "files.trimTrailingWhitespace": true,
  "html.format.wrapAttributes": "force-expand-multiline",
  "window.closeWhenEmpty": true,
  "window.restoreFullscreen": true,
  "window.titleBarStyle": "custom",
  "workbench.commandPalette.history": 0,
  "workbench.editor.tabSizing": "shrink",
  "workbench.settings.editor": "json",
  "workbench.settings.useSplitJSON": true,
  "workbench.startupEditor": "newUntitledFile",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  "breadcrumbs.enabled": false,
  "editor.renderControlCharacters": false,
  "editor.renderWhitespace": "none",
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "diffEditor.renderSideBySide": true,
  "javascript.validate.enable": false,
  "search.searchOnTypeDebouncePeriod": 500,
  "git.openDiffOnClick": false,
  "workbench.colorTheme": "GitHub Dark",
  "svg.preview.mode": "svg",
  "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
  }
}
```
I haven't touched them since the last update and highlighting stopped working.
`--user-data-dir` with this highlighting works. soo, should I delete my settings and start over?

**Comment by fila90** [comment] 2021-02-15 11:03
wild side note

- if I delete those settings and save, highlighting works
- if I paste them back in, highlighting works
- if I close editor and reopen, highlighting doesn't work

**Comment by fila90** [comment] 2021-02-15 11:15
so, I narrowed it down to `"breadcrumbs.enabled": false,`
If i remove it, error highlighting works

**Comment by soetji** [comment] 2021-02-15 17:37
Yes, the same for me. Error highlighting worked after I removed `"breadcrumbs.enabled": false` and restarted the app.

**Comment by alexdima** [comment] 2021-02-15 19:14
cc @jrieken

**Comment by jrieken** [comment] 2021-02-16 08:18
That is somewhat surprising. Breadcrumbs have nothing in common with errors, except for using the same extension to provide this data. Can we get some details here? Please answer the following questions

* do you use outline? (f1 > focus on outline view)
* do you see error on the dev tools console (f1 > toggle developer tools > console)
* you are not seeing the squiggle my screen shot shows when using the snippet below?

```js

function foo() {
    console log();
}
``

<img width="1159" alt="Screenshot 2021-02-16 at 09 16 06" src="https://user-images.githubusercontent.com/1794099/108035759-9cbbd600-7037-11eb-9e90-d45d6f1a4dde.png">

**Comment by fila90** [comment] 2021-02-16 10:12
I've cleared up my settings and this is what I'm left with

```JSON
{
    "breadcrumbs.enabled": false,
    "editor.colorDecorators": false,
    "editor.cursorBlinking": "smooth",
    "editor.cursorStyle": "line-thin",
    "editor.minimap.renderCharacters": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.renderWhitespace": "none",
    "editor.scrollBeyondLastLine": false,
    "editor.tabSize": 2,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "git.openDiffOnClick": false,
    "html.format.wrapAttributes": "force-expand-multiline",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "javascript.validate.enable": false,
    "search.searchOnTypeDebouncePeriod": 500,
    "window.restoreFullscreen": true,
    "workbench.colorTheme": "GitHub Dark",
    "workbench.editor.tabSizing": "shrink",
    "workbench.settings.editor": "json",
    "workbench.startupEditor": "none",
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[html]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascriptreact]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
      "editor.defaultFormatter": "vscode.typescript-language-features"
    },
  }
```

wild thing, highlighting works now even tho I have `"breadcrumbs.enabled": false,`, so my guess is some combination of settings that breaks it?

**Comment by jrieken** [comment] 2021-02-16 10:15
Oh, hello: `"javascript.validate.enable": false`.

**Comment by fila90** [comment] 2021-02-16 10:16
> Oh, hello: `"javascript.validate.enable": false`. That setting (from your settings) disables errors and warnings for JavaScript

as I'm telling you, now it works with `javascript.validate.enable": false` so it's not that :D

**Comment by jrieken** [comment] 2021-02-16 10:19
> ESLint and Flow in the project

Then file this issue against the respective extensions. It's their responsibility to deliver errors/warnings to vscode

**Comment by fila90** [comment] 2021-02-16 10:30
> > ESLint and Flow in the project
> 
> Then file this issue against the respective extensions. It's their responsibility to deliver errors/warnings to vscode

The errors and warnings are nicely shown in VSCode `PROBLEMS` panel, so those extensions are generating them and they work as expected.
The problem is in VSCode because with my first set of settings posted above warnings and errors are not highlighted.
If I downgrade to version 1.52, highlighting works, I don't downgrade extensions or change settings I just downgrade VSCode and it works!

Now with my second set of settings it work with the latest version of VSCode, so my guess is that is some combination of those settings that's making the problem. In both sets of settings I have `javascript.validate.enable": false` and `breadcrumbs.enabled": false`.

If you want to reproduce it, you probably just need to copy mine first set of settings and it will break on your end as well.
All of this is already written down in the problem and comments, just read.

**Comment by jrieken** [comment] 2021-02-16 12:30
> If you want to reproduce it, you probably just need to copy mine first set of settings, restart the app and it will break on your end as well.

Nope - it doesn't

**Comment by soetji** [comment] 2021-02-16 20:30
I see the problem when I have the following in my `settings.json`

```
{
    "breadcrumbs.enabled": false,
    "editor.hover.enabled": false,
}
```
My vscode version is:
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

<img width="864" alt="Screen Shot 2021-02-16 at 3 23 52 PM" src="https://user-images.githubusercontent.com/220015/108117527-02758580-706b-11eb-89f3-d29cf4817a46.png">

**Comment by alexdima** [comment] 2021-02-25 15:41
@jrieken Believe it or not, this has to do with lazy instantiation of services. The ctor of `MarkerDecorationsService` is not invoked when configuring `"breadcrumbs.enabled": false`.

**Closed** 2021-02-25 18:20 UTC
Labels: bug
