### ISSUE TITLE
Terminal prompt shows PWD twice after update

### ISSUE THREAD

**Issue by pixelstew** [Microsoft/vscode#28328] opened 2017-06-09 10:06 UTC
VSCode Version: 1.13.0
OS Version: macOS Sierra 10.12
Steps to Reproduce:

Open terminal
CD to any dir
The prompt shows the PWD twice. When you type one of the iterations of pwd disappears then reappears when typing has ceased. Makes it hard to track what commands you are typing?

<img width="923" alt="screen shot 2017-06-09 at 10 57 27" src="https://user-images.githubusercontent.com/8128855/26971037-8fef2356-4d03-11e7-89f7-c048d4ba7a52.png">

Issue also experienced by @tomitrescak

**Comment by migstopheles** [comment] 2017-06-09 10:21
Also having a similar issue with zsh using the agnoster theme. My issue is that the the branch name is displayed twice, seems to be based on whether the branch name contains a slash (`/`) character or not.

![screen shot 2017-06-09 at 11 20 22](https://user-images.githubusercontent.com/2482374/26971606-bed9ca16-4d05-11e7-96e7-c38f33e9e4b2.png)

**Comment by vikrantnegi** [comment] 2017-06-09 10:31
Yes. I'm facing this issue as well. It flickers whenever I try typing.

**Comment by alexdevico** [comment] 2017-06-09 10:50
Also it's jumping on typing from one to two PWD showed. So it's not usable for now, you don't see what you type.

**Comment by AgrimAsthana-CS** [comment] 2017-06-09 14:46
Same issue being noticed here.

**Comment by Apidcloud** [comment] 2017-06-09 15:04
Same issue with the branch here

**Comment by Kirtaner** [comment] 2017-06-09 15:28
Same issue

**Comment by chanceaclark** [comment] 2017-06-09 17:43
Same issue with both flickering and PWD showing up twice.

![duplicate_pdw](https://user-images.githubusercontent.com/10539418/26987469-47647b14-4d11-11e7-8b74-6d45f1597e07.gif)

**Comment by ishitatsuyuki** [comment] 2017-06-10 09:38
Sounds like the new version is handling Powerline symbols improperly, as all your screenshots show.

**Comment by AaronSum** [comment] 2017-06-10 10:06
Same issue

**Comment by ishitatsuyuki** [comment] 2017-06-11 02:00
Dupe #28304

**Comment by ramya-rao-a** [comment] 2017-06-12 17:24
Thanks @ishitatsuyuki 
Closing as duplicate of #28304

cc @Tyriar

**Closed by ramya-rao-a** 2017-06-12 17:24 UTC
Labels: integrated-terminal, new release
