### ISSUE TITLE
Explorer should sort foo.go before foo_test.go, not after

### ISSUE THREAD

**Issue by peterbourgon** [microsoft/vscode#92662] opened 2020-03-13 18:06 UTC
**Version of VS Code**

- Version: 1.43.0
- Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
- Date: 2020-03-09T19:34:44.548Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.3.0

**Your operating system**

macOS Catalina 10.15.3

**List of extensions that you have installed**

- skyapps.fish-vscode
- ms-vscode.go
- adamcaviness.theme-monokai-dark-soda
- stkb.rewrap
- rust-lang.rust

**Reproducible steps (1... 2... 3...) that cause the issue**

When VS Code is opened on a directory, the Explorer pane shows a tree of files rooted in that directory. But the sort order of files that share a prefix is incorrect.

Given a directory with foo.go and foo_test.go, I expect to see

```
pkg
├── foo
│   ├── foo.go
│   └── foo_test.go
```

Instead, I see

```
pkg
├── foo
│   ├── foo_test.go
│   └── foo.go
```

which is backwards.

**What you expected to see, versus what you actually saw**

See above.

**Images, animations, or a link to a video showing the issue occurring**

n/a

**A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally**

n/a

**Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)**

n/a

**Comment by peterbourgon** [comment] 2020-03-13 18:12
I've added the missing information.

**Comment by gjsjohnmurray** [comment] 2020-03-13 20:20
Is this a duplicate of #27759?

**Comment by peterbourgon** [comment] 2020-03-13 20:31
They are similar, but this issue takes a stricter stance: sort order _in this case_ is well-defined and should not vary by platform.

**Comment by isidorn** [comment] 2020-03-16 09:46
Dup of that one and more explorer sorting issues https://github.com/microsoft/vscode/issues/27286

**Closed by isidorn** 2020-03-16 09:46 UTC
Labels: needs more info
