### ISSUE TITLE
Add a user-defined .vscode-directory

### ISSUE THREAD

**Issue by manuth** [microsoft/vscode#85523] opened 2019-11-25 08:30 UTC
The `.vscode`-directory contains workspace-settings which are shared to the other developers through `git`.

In some cases users might not only have settings they want to share, but also workspace-settings which are user-defined and which are not meant to be shared to the other developers like, for example, the path to executables (such as the path to the `python`-venv created for the workspace).

I suggest to add a directory like, for example `.vscode-custom`, `.vscode/custom` or `.vscode-user` which contains user-defined settings and can be excluded from scm.

This would, for example, solve this issue: https://github.com/microsoft/vscode-python/issues/2125

Such a pattern would also be useful for user-defined settings for the `devcontainer` in order to specify user-defined extensions to install etc.

**Comment by egamma** [comment] 2019-11-25 10:08
duplicate of https://github.com/microsoft/vscode/issues/40233

**Closed by egamma** 2019-11-25 10:08 UTC
