### ISSUE TITLE
F10 and F11 do not start debugging

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#62170] opened 2018-10-30 16:18 UTC
I might be doing something wrong here, but F10 doesn't appear to do anything. F11 makes VS Code go full screen. I can run the new command in the command pallet(Start Debuging and Stop on Entry) but when I use it to debug an extension it never breaks.

I checked and didn't see one, but is there a setting I need to enable?
Found while testing #49855

**Comment by isidorn** [comment] 2018-10-30 18:04
No, there is no setting that needs to be enabled for this.
The `stopOnEntry` flag is ignored for EH debugging, not sure if we can do something about this. @roblourens @weinand 
F10 and F11 keyboard shortcuts are only enabled when `debugConfigurationType="node"`, so they will not work for EH debugging because their type is not node. This seems to be a lucky coincidence because it seems that stopOnEntry might not make sense in this scenario 
@alexr00 can you please try for a node program if it works nicely for you

![screenshot 2018-10-30 at 19 02 21](https://user-images.githubusercontent.com/1926584/47739748-5bd90100-dc76-11e8-9530-808c4042d987.png)

**Comment by roblourens** [comment] 2018-10-30 18:21
I don't think we'd want stopOnEntry for EH debugging, because it will stop in some EH internal code that the user doesn't care about. Stopping in the first line of their extension would be nice but isn't easy, the user should just set a breakpoint for that.

**Comment by isidorn** [comment] 2018-10-30 19:07
Than I think we are good here.
Closing as designed
@alexr00 please reopen if the shortcuts do not work for you when debugging a `node` program

**Closed by isidorn** 2018-10-30 19:07 UTC
Labels: debug, under-discussion

**Comment by alexr00** [comment] 2018-10-31 11:15
I see it working now. Thanks for the info. However, it seems a little odd that F11 means full screen sometimes and start debugging an break on entry other times without any user input.

**Comment by isidorn** [comment] 2018-10-31 11:22
@alexr00 I do agree that it is a bit weird both on linux and on windows.
Weird enough that I would suggest that we have no default keybinding for step_into while not debugging on windows and linux, but only on mac.
Otherwise users that are accustumed to use F11 to go into full screen will no longer be able to do that if they have a node configuration. Of course, this is all customisable so it makes the experience a bit better.

@roblourens @weinand thoughts?

**Comment by roblourens** [comment] 2018-10-31 16:15
Is f11 the default keybinding for full screen on windows? Yeah that seems weird. But isn't it also weird that it means either full screen or step into?

**Comment by isidorn** [comment] 2018-10-31 16:24
You can not full screen while debugging via shortcuts. This was like that for a couple of years and nobody complained (maybe one person)

**Comment by isidorn** [comment] 2018-11-02 08:12
FYI I have decided to not steal F11 on windows and linux, it will be there only on mac
via https://github.com/Microsoft/vscode-node-debug/commit/660175936b0d83277a1b8b2a8a0f2f868ccd032b

**Comment by isidorn** [comment] 2018-11-02 08:13
To verify:
Use windows or linux
1. Have a launch configuration with type node
