### ISSUE TITLE
The Bad display of the terminal

### ISSUE THREAD

**Issue by sigmarising** [Microsoft/vscode#26976] opened 2017-05-20 03:31 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|code-gnu-global|austin|0.2.2|
|vscode-markdownlint|DavidAnson|0.7.2|
|python|donjayamanne|0.6.4|
|matlab|Gimly81|0.5.0|
|MagicPython|magicstack|1.0.10|
|vscode-autoprefixer|mrmlnc|2.0.0|
|cpptools|ms-vscode|0.11.1|
|vscode-icons|robertohuertasm|7.7.0|
|python|tht13|0.2.3|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1. I use the keyboard shortcut Ctrl + ` to open the terminal
2. The terminal show me the bad display

the screenshot:

![bug](https://cloud.githubusercontent.com/assets/25470568/26272620/be3d07b4-3d4f-11e7-9525-45187046783b.png)

**Comment by Nitro-N** [comment] 2017-05-20 10:45
I have the same problem

**Comment by Kroc** [comment] 2017-05-20 11:48
Related/dupe of #1727?

**Comment by sigmarising** [comment] 2017-05-21 00:32
It seems that this problem just happen in the latest version of VSCode. 

I remember when I use the VSCode two months ago, the terminal displays very well, and I handled all my git operations in VSCode.

There is one more assumption, the VSCode gets the bad display only in the Windows10 15063(1703). Two months ago, my computer operation system was Windows10 14393(1607), and the terminal doesn't have any problems. But after I upgrade the windows10, the terminal got the confusion output.

**Comment by Tyriar** [comment] 2017-05-21 21:42
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Closed by Tyriar** 2017-05-21 21:42 UTC
