### ISSUE TITLE
When the Chinese input box shift

### ISSUE THREAD

**Issue by phm622848** [Microsoft/vscode#33238] opened 2017-08-28 06:30 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.1.0
tslint|eg2|0.17.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
path-autocomplete|ion|1.6.1
debugger-for-chrome|msj|3.1.8
ayu|tea|0.6.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.
![image](https://user-images.githubusercontent.com/18509054/29761718-41c9e1fa-8bfd-11e7-900a-e9c865e13e89.png)

Reproduces without extensions: Yes/No

**Comment by wangweixuan** [comment] 2017-08-28 09:11
Duplicate of #356.
This should be fixed in the next release. Or you can try out the Insiders version.

**Comment by rebornix** [comment] 2017-11-16 22:52
Close as fixed.

**Closed by rebornix** 2017-11-16 22:52 UTC
Labels: editor-ime, mac
