### ISSUE TITLE
Error: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by michikuehne** [Microsoft/vscode#13474] opened 2016-10-11 06:54 UTC
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 15.6.0
- Extensions: chenxsan.vscode-standard-format-0.0.12, naumovs.color-highlight-1.2.1, shardulm94.trailing-spaces-0.2.11, shinnn.standard-0.1.5, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:

1. Update to newestes VSCode Version
2. Just code in a simple js-file. With every character I type the error message "Error Path must be a string. Received undefined" is displayed again.

**Comment by isidorn** [comment] 2016-10-11 09:21
@michaelchiche  I can not reproduce this. Do you also see this if you run with --disable-extensions?

**Comment by michaelchiche** [comment] 2016-10-11 09:23
@isidorn wrong mention i think ;)

**Comment by isidorn** [comment] 2016-10-11 09:28
Oops
@michikuehne I meant :)

**Comment by michikuehne** [comment] 2016-10-11 09:28
@isidorn You supposed the right. If I run vsc without --disable-extensions the error message doesn't occur.
So one of the extension I use must be responsible for this error. Thanks for the hint

**Comment by isidorn** [comment] 2016-10-11 09:31
@michikuehne what I suggest is to uninstall extensions one by one and try to figure out which one it is. Once you got that just file this issue to the github repository of that extension.
Closing this as there is nothing to be done on the vscode side

**Closed by isidorn** 2016-10-11 09:31 UTC
Labels: needs more info

**Comment by rasmuslundberg** [comment] 2016-10-12 07:16
Hi! I had the same problem, i have tried each one of my extensions and found out that in my case its vscode-standard 0.1.5 thats causing the problems. It actually says on their extensions page that their dev dependencies are out of date. i think https://github.com/shinnn is the authour.

**Comment by michikuehne** [comment] 2016-10-12 07:21
@rasmuslundberg You're right! The same plugin caused the error message on my vscode.

**Comment by rasmuslundberg** [comment] 2016-10-12 07:25
What the easiest way to contact shinnn? is there a formal way to ask for a update on  a vscode extension or should we just post an issue on the repos? Sorry for my newb questions.

**Comment by michikuehne** [comment] 2016-10-12 07:31
@rasmuslundberg Right, just open I github issue on his repo.

**Comment by rasmuslundberg** [comment] 2016-10-12 07:31
@michikuehne its already there https://github.com/shinnn/vscode-standard/issues/7

**Comment by jhaddow** [comment] 2017-02-10 16:56
FWIW, The ESLint extension causes this error for me.

**Comment by mehas** [comment] 2017-07-28 18:20
FYI I received this error because my global install of `eslint` was out of date
