### ISSUE TITLE
throw '存储空间不足，无法处理此命令。' when I open the terminal(ctrl + `)

### ISSUE THREAD

**Issue by cainiaoDJ** [Microsoft/vscode#9470] opened 2016-07-19 06:50 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. all of triminal configs are defualt; and I installed a plugin --"Terminal", contributed by Jun Han
2. use ```Ctrl ` ``` open the terminal,and then it tell me `存储空间不足，无法处理此命令。`  I didn't run any command, just open it.

**Comment by lextm** [comment] 2016-07-19 07:24
According to its download page,

https://marketplace.visualstudio.com/items?itemName=formulahendry.terminal

you should report any issues of that extension to 

https://github.com/formulahendry/vscode-terminal/issues

As that's an individual extension, not Visual Studio Code itself, I think this issue here should be closed.

Mind you now VSCode has a built-in terminal, so you don't really need that extension.

**Comment by cainiaoDJ** [comment] 2016-07-19 07:36
I had unistalled the plugin,  and It tell me those message again. this issue is different from `https://github.com/formulahendry/vscode-terminal/issues/3`. The characters issue was solved in V1.3.  My issue is "存储空间不足，无法处理此命令", it means "not enough stroge to process this command".

**Comment by Tyriar** [comment] 2016-07-21 18:53
So yes to be clear, ctrl+backtick opens the integrated terminal which offers what vscode-terminal does and much more so I recommend using the integrated terminal.

Since you say the issue is fixed I'll close this off. Please comment if you have any more issues.

**Closed by Tyriar** 2016-07-21 18:53 UTC
Labels: integrated-terminal

**Comment by cainiaoDJ** [comment] 2016-07-22 02:27
```JSON
    //-------- Integrated terminal configuration --------
    // The path of the shell that the terminal uses on Windows.
    //"terminal.integrated.shell.windows": "C:\\cygwin64\\bin\\mintty.exe",

    // The font family used by the terminal (CSS font-family format).
    //"terminal.integrated.fontFamily": "'微软雅黑'",
    //-------- 外部终端配置 --------

    // Customizes which terminal to run on Windows.
    //"terminal.external.windowsExec": "C:\\cygwin64\\bin\\mintty.exe",

    // 控制在多少个字符后编辑器会自动换到下一行。将其设置为 0 则将打开视区宽度换行(自动换行)。将其设置为 -1 则将强制编辑器始终不换行。
```

all configs of terminal in `settings.json` is here. I commented it out. it throw  error again. I just use `cmd.exe` as my terminal, it is the default config. See the following png.
[termianl](https://github.com/cainiaoDJ/images/blob/master/vscode/terminal/vscode_terminal_screenshoot.png)

**Comment by lextm** [comment] 2016-07-22 08:03
So the actual problem on this machine is that when VSCode launches Command Prompt (cmd.exe), an error message saying "Not enough storage is available to process this command."

This message is really ambiguous. Posts like [this](http://serverfault.com/questions/147526/not-enough-storage-is-available-to-process-this-command) seem to indicate the cause is at OS level, not VSCode.

**Comment by Tyriar** [comment] 2016-07-22 21:58
Duplicate of #9470

**Comment by lextm** [comment] 2016-09-23 13:13
Today I happened to come across this exact error message on an Azure VM Windows Server 2012 R2 via RDP. Not sure of the cause still, but it does not prevent commands from being executed.

Thus, I assume it is a harmless message that we can safely ignore.
