### ISSUE TITLE
File watcher fails with chinese characters in path

### ISSUE THREAD

**Issue by leixu2txtek** [Microsoft/vscode#481] opened 2015-11-23 10:02 UTC
**First of all , Thanks to all contributor**

When i use the lastest version to build my node app, i want to debug my app..

when i add the launch.json , but not appear in the  launch configuration dropdown menu.

So , i  guess need restart the VSCode ,    Yes...  did it...

Maybe it's a  tiny bug...

thx.

OS : Windows 10 pro 10586

**Comment by isidorn** [comment] 2015-11-23 15:04
Ok, so:
* You manually create a launch.json file
* You open the debug viewlet but you do not see the configurations in the launch dropdown

Did I understand your steps properly? Because I can not reproduce this beahvior.
Providing more precise steps would be useful, especially how you add the launch.json

**Comment by isidorn** [comment] 2015-11-23 19:36
Might it be a duplicate of #458

**Comment by leixu2txtek** [comment] 2015-11-24 02:41
ok . .

1.
![click the debug button](https://cloud.githubusercontent.com/assets/5109966/11356296/816e0a86-9297-11e5-8578-fc230a2a443c.png)

2.
![selected the node js](https://cloud.githubusercontent.com/assets/5109966/11356297/891b7f0c-9297-11e5-9100-37ee03f6909e.png)

3.
![need restart](https://cloud.githubusercontent.com/assets/5109966/11356301/9141ae40-9297-11e5-8fab-a7603afe0a24.png)

**Comment by isidorn** [comment] 2015-11-24 08:47
@bpasero seems like file events are missing here. Any idea why that might be?

**Comment by bpasero** [comment] 2015-11-24 08:49
Easy to find out running with --verbose

**Comment by isidorn** [comment] 2015-11-24 08:53
@leixu2txtek we believe you might be missing file events, though you would see this in other places as well (git viewlet not being updated with a badge once you make changes). Can you run code with --verbose flag and via palette open developer: toggle developer tools and post the screenshot frmo the output if there are file events comming

**Comment by leixu2txtek** [comment] 2015-11-24 13:25
ok...

![dev](https://cloud.githubusercontent.com/assets/5109966/11367904/b7bd5e20-92f1-11e5-88ef-8207bf128bf5.png)

**Comment by bpasero** [comment] 2015-11-24 14:54
Hm, maybe the path uses characters we fail to decode. If you delete a file in the windows explorer, does the explorer in VSCode update?

**Comment by leixu2txtek** [comment] 2015-11-25 01:26
Maybe...  you know, I am Chinese people...

i'll test it with full english path

thx

**Comment by leixu2txtek** [comment] 2015-11-25 01:30
@bpasero @isidorn 

Yes.. Really it is because of Chinese characters...

thx..

**Comment by leixu2txtek** [comment] 2015-11-25 01:33
@bpasero VSCode does not automatically update, I need to manually refresh.

**Comment by bpasero** [comment] 2015-11-25 05:52
@leixu2txtek can you give me an example path so that I can try to reproduce.

**Comment by leixu2txtek** [comment] 2015-11-25 06:24
@bpasero :)  

D:\新建文件夹\中文项目目录

**Comment by bpasero** [comment] 2015-11-25 20:09
Wow this is a great bug, turns out we need to set UTF-8 when writing from C# to the console. I think I have a fix for it.

**Comment by leixu2txtek** [comment] 2015-11-26 01:26
@bpasero Nice...    :+1:

**Comment by bpasero** [comment] 2015-11-26 06:50
@leixu2txtek I pushed a fix and you can patch your vscode to pick it up:
- close vscode
- download the CodeHelper.exe from https://github.com/Microsoft/vscode/blob/2a74a926822dc2617c129f896b010e39b40c1051/src/vs/workbench/services/files/node/watcher/win32/CodeHelper.exe
- overwrite the existing CodeHelper.exe in C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\files\node\watcher\win32

**Closed by bpasero** 2015-11-26 06:50 UTC
Labels: bug

**Comment by leixu2txtek** [comment] 2015-11-26 09:51
@bpasero  worked .. thx

**Comment by bpasero** [comment] 2015-11-26 11:07
Great :+1:
