### ISSUE TITLE
Notifications tab

### ISSUE THREAD

**Issue by CTimmerman** [Microsoft/vscode#32136] opened 2017-08-08 11:16 UTC
- VSCode Version: 1.14.2
- OS Version: 10.12.5 (16F73)

Steps to Reproduce:

1. Close annoying notification to see your open file tabs.
2. Wonder what that notification was about.
3. Notice a lot of unused space next to the Terminal tab.

Reproduces without extensions: Yes

**Comment by weinand** [comment] 2017-08-08 12:40
A screenshot would help to understand what you mean.

**Comment by CTimmerman** [comment] 2017-08-08 22:39
Imagine working on several files, when suddenly some extension or whatever causes an unmovable popup to appear right over your open file tabs. I don't know how to reproduce that (hence point #2), so used a more tolerable popup at appears at the same location:

![Don't cover my work; use a notification center!](https://user-images.githubusercontent.com/9662163/29097553-ca1b18ca-7c9a-11e7-85a4-4e4ed11ad87d.png)

**Comment by weinand** [comment] 2017-08-08 22:43
Thanks a lot for the clarification.

**Comment by CTimmerman** [comment] 2017-08-09 08:04
A new (or existing) tab for error messages would also solve #32175

**Comment by bpasero** [comment] 2017-08-11 08:48
Lets mark this as duplicate of https://github.com/Microsoft/vscode/issues/22388

**Closed by bpasero** 2017-08-11 08:48 UTC
