### ISSUE TITLE
restart the vscode,showed wrong style

### ISSUE THREAD

**Issue by AllenHee** [microsoft/vscode#119426] opened 2021-03-22 01:42 UTC
- VS Code Version:1.54.3
- OS Version:Darwin x64 20.1.0

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/16890350/111930017-eb570700-8af2-11eb-8229-becb60701712.png)

1.
2.

Does this issue occur when all extensions are disabled?: No

**Comment by sbatten** [comment] 2021-03-22 18:06
@AllenHee is it possible to open the dev tools? `Cmd+Shift+P` > `Open Dev Tools` and report any errors?

**Comment by AllenHee** [comment] 2021-03-24 00:43
I can open the dev tools,but don`t report any errorss
![image](https://user-images.githubusercontent.com/16890350/112237158-0c4b6380-8c7d-11eb-9991-ad35eec1769e.png)

**Comment by deepak1556** [comment] 2021-03-24 01:06
Does the issue happen when you start with `code --disable-gpu` ?

**Comment by AllenHee** [comment] 2021-03-24 06:17
> Does the issue happen when you start with `code --disable-gpu` ?

no

**Comment by AllenHee** [comment] 2021-03-24 06:22
> > Does the issue happen when you start with `code --disable-gpu` ?
> 
> no

I just updated the vscode about a week ago, and in the day before yesterday,because I edited some setting of pluging,restarted the vscode, the issue happened

**Comment by deepak1556** [comment] 2021-03-24 07:06
Do you see the issue when you run with `code --disable-extensions` ?

**Comment by AllenHee** [comment] 2021-03-24 07:26
> Do you see the issue when you run with `code --disable-extensions` ?

I disabled the extensions that I edited, but it didnt work

**Comment by deepak1556** [comment] 2021-03-24 07:42
In that case this is purely a gpu support issue, please follow the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration to disable the support. We can verify if it gets fixed with newer versions.

**Comment by AllenHee** [comment] 2021-03-24 08:20
> In that case this is purely a gpu support issue, please follow the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration to disable the support. We can verify if it gets fixed with newer versions.

but when I run the Preferences: Configure Runtime Arguments command.I cant do anything
![image](https://user-images.githubusercontent.com/16890350/112277510-cca46c00-8cbc-11eb-84a5-6e05be8e32c4.png)

**Comment by AllenHee** [comment] 2021-03-24 08:21
> In that case this is purely a gpu support issue, please follow the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration to disable the support. We can verify if it gets fixed with newer versions.

It doesnt show anything and I cant do anything

**Comment by deepak1556** [comment] 2021-03-24 08:26
Start the app like `code --disable-gpu` and then perform the above steps, so that from next start you don't have to specify the command line.

**Comment by AllenHee** [comment] 2021-03-24 08:31
> Start the app like `code --disable-gpu` and then perform the above steps, so that from next start you don't have to specify the command line flag.

I use the Mac,I dont know how to start the app like code --disable-gpu

**Comment by deepak1556** [comment] 2021-03-24 08:51
I thought you had already tried it https://github.com/microsoft/vscode/issues/119426#issuecomment-805533569 and reported the issue is fixed with that flag.

* Open terminal on your mac
* Run `code --disable-gpu`

If the above command outputs something like `code not recognized` then try the following as alternative

* Run `open -a /Applications/Visual\ Studio\ Code.app --args --disable-gpu`

**Comment by AllenHee** [comment] 2021-03-24 08:53
> I thought you had already tried it [#119426 (comment)](https://github.com/microsoft/vscode/issues/119426#issuecomment-805533569) and reported the issue is fixed with that flag.
> 
> * Open terminal on your mac
> * Run `code --disable-gpu`
> 
> If the above command outputs something like `code not recognized` then try the following as alternative
> 
> * Run `open -a /Applications/Visual\ Studio\ Code.app --args --disable-gpu`

It also doesnt work
![image](https://user-images.githubusercontent.com/16890350/112281859-7dad0580-8cc1-11eb-9038-f1289465f912.png)

**Comment by deepak1556** [comment] 2021-03-24 20:51
Can you provide the output of `code --verbose`, run this in a terminal.

**Comment by AllenHee** [comment] 2021-03-25 01:42
> Can you provide the output of `code --verbose`, run this in a terminal.

I have tried,but it didnt work
![image](https://user-images.githubusercontent.com/16890350/112406065-6d8f3780-8d4e-11eb-9732-f202a43d47ca.png)

**Comment by deepak1556** [comment] 2021-03-25 01:58
The command will not fix the issue, it print some data in the terminal. Please attach the printed output.

**Comment by AllenHee** [comment] 2021-03-25 02:03
> The command will not fix the issue, it print some data in the terminal. Please attach the printed output.
It showed command not found: code

**Comment by AllenHee** [comment] 2021-03-25 02:14
> The command will not fix the issue, it print some data in the terminal. Please attach the printed output.

It showed
![image](https://user-images.githubusercontent.com/16890350/112408510-e1cbda00-8d52-11eb-8ad5-d1bb1e1855cb.png)

**Comment by deepak1556** [comment] 2021-03-25 02:36
Thanks, that log means there was already a running instance of vscode application. Please exit the application and also ensure all vscode processes are quit in the system activity monitor. After that, try the command again.

**Comment by AllenHee** [comment] 2021-03-25 02:48
> Thanks, that log means there was already a running instance of vscode application. Please exit the application and also ensure all vscode processes are quit in the system activity monitor. After that, try the command again.

there is the message,if you need word for copy,please tell me
![image](https://user-images.githubusercontent.com/16890350/112411050-34a79080-8d57-11eb-8c0d-7a7da3e7c6c0.png)

![image](https://user-images.githubusercontent.com/16890350/112411083-42f5ac80-8d57-11eb-87ac-aebedd932046.png)

![image](https://user-images.githubusercontent.com/16890350/112411125-57d24000-8d57-11eb-8682-029d5e3667ec.png)


![image](https://user-images.githubusercontent.com/16890350/112411193-789a9580-8d57-11eb-9afb-3a5c29c26163.png)


![image](https://user-images.githubusercontent.com/16890350/112411231-88b27500-8d57-11eb-959c-731e5d0ea928.png)

**Comment by deepak1556** [comment] 2021-03-25 04:30
Thanks for the log, can you exit the application and run `code --user-data-dir /tmp/vscode-startup`.

**Comment by AllenHee** [comment] 2021-03-25 05:58
> Thanks for the log, can you exit the application and run `code --user-data-dir /tmp/vscode-startup`.

![image](https://user-images.githubusercontent.com/16890350/112425982-0c795b00-8d72-11eb-9081-73b1862ec59f.png)

![image](https://user-images.githubusercontent.com/16890350/112426005-17cc8680-8d72-11eb-9d59-968ce30a0caa.png)


![image](https://user-images.githubusercontent.com/16890350/112426023-261aa280-8d72-11eb-863c-58af6c11b406.png)

**Comment by deepak1556** [comment] 2021-03-25 07:35
Can you install the insiders https://code.visualstudio.com/insiders and see if it works fine ?

**Comment by AllenHee** [comment] 2021-03-25 07:52
> Can you install the insiders https://code.visualstudio.com/insiders and see if it works fine ?

it works fine
![image](https://user-images.githubusercontent.com/16890350/112437581-12773800-8d82-11eb-8bbc-5f9fbc8160e8.png)

**Comment by AllenHee** [comment] 2021-03-25 08:02
> Can you install the insiders https://code.visualstudio.com/insiders and see if it works fine ?

and I use the Version:1.53.2,it also works fine

**Comment by deepak1556** [comment] 2021-03-29 16:51
Thanks for testing, lets check back if the issue happens with `1.55` stable that will be released this week.

**Comment by AllenHee** [comment] 2021-03-30 02:43
> Thanks for testing, lets check back if the issue happens with `1.55` stable that will be released this week.

ok, I expect the 1.55

**Closed** 2021-04-12 07:44 UTC
Labels: mac, needs more info
