### ISSUE TITLE
Typescript autocomplete string inside backticks

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#36161] opened 2017-10-12 19:14 UTC
```typescript
let count: 'one' | 'two';
```
When using single quote or double quote autocomplete works:
```typescript
count = '|';
count = "|";
```
But not for backticks:
```typescript
count = `|`;
```

Also, wouldn't it be better when having a definite set of strings (here 'one' & 'two') trigger autocomplete on typing opening quote?

**Comment by usernamehw** [comment] 2017-10-12 19:24
As I now see it's currently not possible to auto trigger by typing quote 25 034 issue.

**Comment by mjbvz** [comment] 2017-10-12 19:57
Yes this is a duplicate of #25034

**Closed by mjbvz** 2017-10-12 19:57 UTC
Labels: duplicate, typescript

**Comment by usernamehw** [comment] 2017-10-12 20:33
... and what about autocomplete inside template literal?

**Comment by usernamehw** [comment] 2017-10-13 16:09
@mjbvz The crux of the matter was that there is no autocomplete inside backticks:

```typescript
let count: 'one' | 'two';
// // put the cursor inside quotes
count = ``;// trigger autocomplete
```

**Comment by mjbvz** [comment] 2017-10-13 17:18
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/19162 to track this upstream
