### ISSUE TITLE
`dependencies` in extension `package.json` does not work as documentation at all

### ISSUE THREAD

**Issue by JounQin** [microsoft/vscode#200433] opened 2023-12-09 08:34 UTC
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.85.0
提交: af28b32d7e553898b2a91af498b1fb666fdebe0c
日期: 2023-12-06T18:17:50.719Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

![image](https://github.com/microsoft/vscode/assets/8336744/801dbf92-25ff-48bd-85af-a76b1f354ac1)

It says `dependencies` will just work as node `dependencies`, but it actually doesn't and never work.

![image](https://github.com/microsoft/vscode/assets/8336744/de536a97-ccfe-40a3-b39d-a528aead67ec)

For now, we have to bundle all dependencies manually.

**Comment by gjsjohnmurray** [comment] 2023-12-09 10:42
How are you bundling your extension? I use Webpack for mine and usually don't have to do anything special to get the dependencies included in the VSIX.

https://code.visualstudio.com/api/working-with-extensions/bundling-extension#using-webpack

**Comment by JounQin** [comment] 2023-12-09 10:48
Per https://github.com/idahogurl/vs-code-prettier-eslint, `esbuild` is used for bundling.

**Comment by gjsjohnmurray** [comment] 2023-12-09 14:31
Have you reviewed the info at https://code.visualstudio.com/api/working-with-extensions/bundling-extension#using-esbuild?

**Comment by JounQin** [comment] 2023-12-09 14:34
@gjsjohnmurray So the document about `dependencies` field in `package.json` is absolutely wrong, and `vsce`'s `dependencies` option which is `true` by default is absolutely meaningless.

**Comment by joaomoreno** [comment] 2023-12-15 20:09
Duplicate of https://github.com/microsoft/vscode-vsce/issues/914

**Closed by joaomoreno** 2023-12-15 20:09 UTC
