### ISSUE TITLE
Allow creating new files with slashes in their names and construct the tree automatically

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#43096] opened 2018-02-07 12:59 UTC
There is no existing issue for this according to my search `is:issue new file slash in name`

I'd like to request a feature where the explorer pane's new file name's input accepts relative paths such as `a/b/c.txt` and instead of warning about an invalid file name figures out that `c.txt` is the portion of the path that represents the name to be validated. VS Code should, in case of a valid name being provided, either construct the directory tree based on the relative path and place the final name here. The existing portion of the directory tree (if any) should not cause a conflict, but should just be reused.

**Comment by usernamehw** [comment] 2018-02-07 13:49
Duplicate of https://github.com/Microsoft/vscode/issues/12893

**Closed** 2018-02-07 13:51 UTC
