### ISSUE TITLE
Expand icon is lost when deleting a line using git and collapse the code.

### ISSUE THREAD

**Issue by avmalexisl** [Microsoft/vscode#9214] opened 2016-07-13 14:35 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10240

Steps to Reproduce:

1.Create a function with some lines inside. Git will tell you you've added these lines.
2.Sumbit the source to repository.
2.1.Collapse the created function and you'll see the expand icon.
3.Now remove any inside line from created function. Git will tell you you've removed a line.
4.Collapse the function. Notice how instead of the expand icon it is shown the git red triangle from removed line.
![issue_expand_icon](https://cloud.githubusercontent.com/assets/9555365/16807147/5f436bcc-48e5-11e6-96b3-675b2df3fd7e.png)

**Comment by aeschli** [comment] 2016-07-14 09:27
duplicate of #9222

**Closed by aeschli** 2016-07-14 09:27 UTC
