### ISSUE TITLE
VSC tsserver.js hogging my CPU even if I never used TS!

### ISSUE THREAD

**Issue by unlucio** [Microsoft/vscode#71286] opened 2019-03-27 12:28 UTC
VSC is causing my machine to freeze up or incredibly slow down with apparent no reason: killing VSC brings back the computer to life.
A quick check to `htop` shows all my cores in the red and VSC firmly on top holding on my CPU with claws and teeth.
As `code --status` shows the culprit seems been `tsserver.js`, which I find very odd none of our projects uses TS in any way, so why is it even running?
Searching throughout the issues seems like someone was able to mitigate the problem fixing the ts config in their project but all our projects are either vanilla JS, golang or python.
It is a bit frustrating been stopped or slow by a text editor doing things in background I didn't ask for 😅

```
Version:          Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS Version:       Darwin x64 18.2.0
CPUs:             Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)
Memory (System):  16.00GB (0.03GB free)
Load (avg):       8, 8, 8
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    2	    82	 22873	code main
    0	    66	 22874	   gpu-process
    0	   262	 22875	   window (package.json — music-magic)
    0	   295	 23052	     extensionHost
    0	    49	 23056	       electron_node server.js
    0	    49	 23059	       electron_node server.js
    0	    33	 23062	       electron_node server.js
    0	    49	 23063	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=23052
    0	    33	 23075	       electron_node server.js
   80	   262	 23775	       electron_node tsserver.js
    0	    66	 23776	         electron_node typingsInstaller.js typesMap.js
    0	    33	 23778	       electron_node eslintServer.js
    0	   115	 23053	     watcherService
    0	    98	 23054	   shared-process
    0	   262	 27786	   window (mmIndex.jsx — client.eject)
    0	    49	 27787	     watcherService
    0	   328	 27788	     extensionHost
    0	    66	 27803	       electron_node server.js
    0	    82	 27805	       electron_node eslintServer.js
    0	   279	 27807	       electron_node tsserver.js
    0	    82	 27824	         electron_node typingsInstaller.js typesMap.js
    0	    49	 27810	       electron_node server.js
    0	    49	 27922	       node /private/tmp/client.eject/node_modules/.bin/jest --json --useStderr --outputFile /var/folders/4c/t9fcrq912jd7l74l0h24q4cc0000gn/T/jest_runner.json --watchAll --no-color
    0	    33	 27791	     searchService
```

**Comment by mjbvz** [comment] 2019-03-28 02:58
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by Risto-Mcintosh** [comment] 2019-03-28 20:17
Im having the same problem.  I followed the Performance issue guide, I still can't figure it out. I also open up the project in the Insiders build (which as no extensions)  and the 'electron_node tsserver.js' is still using a lot of memory

**Comment by kevbost** [comment] 2019-03-31 02:28
I'm going to chime in here since this is the most active thread. I'm having the same issue where `electron_node tsserver.js` is hogging all cpu resources and is seemingly unresolvable.

**Comment by mjbvz** [comment] 2019-03-31 18:52
@Risto-Mcintosh @kevbost  Please open separate issues. It makes investigations easier

**Comment by kevbost** [comment] 2019-04-01 04:27
My issue is identical to everyone else's. A Google search on this leads to unresolved thread after unresolved thread. Adding a new issue just adds to the clutter.

**Comment by mjbvz** [comment] 2019-04-05 23:31
@kevbost Open a new issue. High cpu usage is a symptom with many possible root causes so, as I said, it's far easier to track these per case

**Comment by mjbvz** [comment] 2019-04-29 18:40
Closing as more information is needed from OP to investigate

My best guess is that this is a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391 since that package was causing perf issues around the time this issue was filed. Upgrading VS Code versions and making sure you do not have a broken version of `@types/styled-components` should fix that if it were the cause

**Closed by mjbvz** 2019-04-29 18:40 UTC
Labels: javascript, needs more info

**Comment by ou2s** [comment] 2019-06-07 06:53
The issue is still occurring on 1.35.0. 
And I never used Typescript too.
