### ISSUE TITLE
Unable to save GO file

### ISSUE THREAD

**Issue by alexandrevk** [microsoft/vscode#104730] opened 2020-08-15 21:30 UTC
Issue Type: <b>Bug</b>

open folder -> create new one -> create new main.go file -> add some code (e.g. package main

import (
	"fmt"

)

func main() {
	var emails []string
	fmt.Printf("Emails: %#v \n", emails)
}    -> click ctrl +S 

Expected : file successfully saved
Result: flickering screen, unable to continue

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9920X CPU @ 3.50GHz (24 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (23.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
go-group-imports|ale|1.1.3
duplicate|gee|1.0.1
GoPro|gir|0.1.2
go|gol|0.16.1
gradle-language|nac|0.2.3
java|red|0.65.0
vscode-gradle|ric|3.4.2
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.11.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.24.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-08-15 22:10
/needsMoreInfo does the problem also happen if you run the command to reload with all extensions disabled?

**Comment by bpasero** [comment] 2020-08-17 06:50
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by vikram-rawat** [comment] 2020-08-18 08:34
I have exactly the same issue since a month. 

https://github.com/golang/vscode-go/issues/236

VScode-Go extensions told me that it 's bug with the VScode itself. It's very very very annoying to not able to save file and have to close the entire app because it flickers a lot.

**Comment by vikram-rawat** [comment] 2020-08-18 08:38
code --disable-extensions

this doesn't help. I tried it and it still flickers while saving a go file. with all extensions disabled.

Please fix it ASAP. it's very hard to work on go code on vscode anymore with this issue.

**Comment by bpasero** [comment] 2020-08-18 09:00
![recording](https://user-images.githubusercontent.com/900690/90492946-0c610f00-e142-11ea-9916-d8b20e7b4b5b.gif)

As you can see this works fine for me, can you record a screen cast?

**Comment by vikram-rawat** [comment] 2020-08-18 14:57
Thanks for replying 

I am sorry! somehow It worked this time but didn't work earlier. Now How would I know which extension is causing this problem So that I can disable it permanently.

**Comment by bpasero** [comment] 2020-08-18 15:05
Ok waiting for @alexandrevk reply before closing this.

**Closed** 2020-08-26 11:22 UTC
Labels: needs more info
