### ISSUE TITLE
switch git related icons from the github icon to git icon

### ISSUE THREAD

**Issue by rgl** [Microsoft/vscode#28953] opened 2017-06-18 07:47 UTC
- VSCode Version: 13.13.1
- OS Version: Ubuntu 17.04

I've noticed that the .gitignore icon (maybe for other files too) is for github:

![image](https://user-images.githubusercontent.com/43356/27259065-9136781c-5402-11e7-9bf8-e867ea9d4a88.png)

shouldn't it be the git icon from https://git-scm.com/?

**Comment by jens1o** [comment] 2017-06-18 14:47
Duplicate #28435

**Comment by rgl** [comment] 2017-06-18 15:04
For reference, this seems to be an [issue with the default seti-ui theme](https://github.com/jesseweed/seti-ui/issues/341).

**Comment by ramya-rao-a** [comment] 2017-06-19 01:30
Thanks for the links @jens1o!

Closing this issue as duplicate of #28300 

There is an upstream issue for this https://github.com/jesseweed/seti-ui/issues/341. Please up vote and add your thoughts there.

**Closed by ramya-rao-a** 2017-06-19 01:30 UTC
