### ISSUE TITLE
Solution Explorer Searching Doesn't Show What You're Searching For

### ISSUE THREAD

**Issue by DanJ210** [microsoft/vscode#83444] opened 2019-10-28 15:21 UTC
Issue Type: <b>Bug</b>

Start searching for a file in a large project. You'll get the results in the screenshot. Nothing is highlighted as if nothing is found or highlighted but when you dig down into the folder tree that they are in, you'll see them highlighted.

![Searching - No Highlighting](https://user-images.githubusercontent.com/16159685/67691432-f6951a00-f974-11e9-88ed-a0f181003cac.png)
![Searching - Found Files No Highlighting](https://user-images.githubusercontent.com/16159685/67691436-f85edd80-f974-11e9-817b-a7842dc8c05f.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (7 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.94GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
gitlens|eam|10.1.1
vscode-npm-script|eg2|0.3.9
vscode-great-icons|emm|2.1.47
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
dotnet-test-explorer|for|0.7.1
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
rest-client|hum|0.22.2
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
docomment|k--|0.1.8
dotnet-core-essentials|Kis|0.0.8
vscode-attrs-sorter|mrm|2.1.0
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.1
vscode-azurefunctions|ms-|0.19.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
vscode-edge-devtools|ms-|1.0.4
mssql|ms-|1.7.0
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
vscode-node-azure-pack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.1056
vsliveshare-audio|ms-|0.1.66
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.7.0
debugger-for-chrome|msj|4.12.1
debugger-for-edge|msj|1.0.12
vuejs-extension-pack|mub|1.1.5
vetur|oct|0.22.6
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.9.1
tslint-vue|pro|1.5.6
LiveServer|rit|5.6.1
vscode-essentials-snippets|rob|2.0.0
yo|sam|0.9.3
code-settings-sync|Sha|3.4.3
git-autoconfig|shy|0.0.1
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.0
azure-iot-toolkit|vsc|2.12.0
vscode-icons|vsc|9.5.0
WebTemplateStudio-dev-nightly|WAS|0.0.1929801
wilderminds-aspnetcore-snippets|wil|0.2.1
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-10-28 16:35
/duplicate of #66971

@DanJ210 this is functioned as designed ATM - highlights only has info about visible nodes, therefore you have to open folders with those files first.

There is #66971 which tracks full tree resolution before applying highlights/filtering.

In the meantime you are still able to use <kbd>Ctrl+P</kbd> and type name of file to use global file search.

**Closed** 2019-10-28 16:35 UTC
Labels: *duplicate
