### ISSUE TITLE
welcome page, “Recent” items

### ISSUE THREAD

**Issue by tryingfly** [microsoft/vscode#180624] opened 2023-04-23 02:55 UTC
Type: <b>Bug</b>

In welcome page, “Recent” items used to be the right part of the page, and it showed more items. But now the “Recent” items is on the left-bottom corner, and only five items are listed. I think the old version is better.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment] 2023-04-23 06:00
@chrmarti this is a duplicate of #178831 which needs to be reopened please.

**Comment by bhavyaus** [comment] 2023-05-01 18:46
See proposal: https://github.com/microsoft/vscode/issues/178831#issuecomment-1530064071

**Closed** 2023-05-04 21:00 UTC
Labels: bug, getting-started
