### ISSUE TITLE
Typescript: Import path not changed after moving file to a subfolder.

### ISSUE THREAD

**Issue by ardivali** [Microsoft/vscode#51374] opened 2018-06-07 17:46 UTC
Issue Type: <b>Bug</b>

If I move file: a.ts into a folder (like /b) all files which are importing a.ts will update the path: 'a' to 'b/a'. That's OK.
But if I had some imports inside a.ts itself, they would remain unchanged. While I would expect them to be changed. For example 'some-resource' to '../some-resource'

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.14393

**Comment by mjbvz** [comment] 2018-06-07 22:30
Duplicate of https://github.com/Microsoft/TypeScript/issues/24345

Will be fixed in vscode insiders once we pick up a new TS version this week or next

**Closed by mjbvz** 2018-06-07 22:30 UTC
Labels: new release

**Comment by ardivali** [comment] 2018-06-08 04:39
Thanks!
