### ISSUE TITLE
Integrated terminal mouse reporting not working on Windows

### ISSUE THREAD

**Issue by BDisp** [microsoft/vscode#136749] opened 2021-11-09 12:50 UTC
Does this issue occur when all extensions are disabled?: Yes (Only C# enabled)

- VS Code Version: 1.62.0
- OS Version: 21H1 (19043.1320)

Steps to Reproduce:

1. Using `Console Virtual Terminal Sequences` (https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) is now possible to run cross platform code (`Windows`, `Linux` and `macOS`).
2. Using a console with mouse reporting, like `Terminal.Gui` (https://github.com/migueldeicaza/gui.cs) with the -usc argument, the mouse reporting only work on `Linux` and `macOS` integrated terminal and not work on `Windows` integrated terminal, but it will work running on a external terminal (`cmd`, `PowerShell` and `Windows Terminal`) from `Windows OS`.

Do I need to to do some configuration or is as is?

**Comment by Tyriar** [comment] 2021-12-21 18:56
We support it, you probably need to update Windows:

---

This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2021-12-21 18:56 UTC
Labels: windows, confirmation-pending, terminal-input

**Comment by willmcgugan** [comment] 2022-01-28 10:34
I'm experiencing the same issue on a fully up-to-date version of Windows 10. Windows Terminal works fine.

Is the only solution to update to Windows 11 ?

**Comment by BDisp** [comment] 2022-01-28 11:02
> Is the only solution to update to Windows 11 ?

Yes, unfortunately.
