### ISSUE TITLE
Need visible, clickable `Close All` or `Close Group` action

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9888] opened 2016-07-28 09:40 UTC
Not sure if we already had an issue for this, but I'm going crazy without this action. Right click on the title simply doesn't work for me.

**Comment by bpasero** [comment] 2016-08-05 15:11
@joaomoreno what about we leverage the new support to change an action when you press the Alt key and if you hover over the X for closing you get the close all?

**Comment by bgashler1** [comment] 2016-08-05 21:01
@joaomoreno do you have tabs on or disabled?  Also, have you tried using <kbd>Ctrl</kbd> + <kbd>K</kbd> + <kbd>W</kbd> or using the overflow menu to click "Close All?"

I'm worried that if we add a visible Close All command that it could be accidentally clicked and wipe out all the open files users have open.  That's why it's tucked in the overflow menu currently.

**Comment by joaomoreno** [comment] 2016-08-08 09:38
@bgashler1 Yes to all. I currently rebind <kbd>Cmd W</kbd> to close all editors in a group (model concept) because that seems to be the only way I can close a *pane* (view concept). In my mind there are editor panes and I can open files in them, the collection of which is kept nice and tidy by Quick Open. In our current model there are editor groups, each editor is a file. A `Close` X-button action makes sense in that model, where you see tabs and clicking it will close each tab. In my workflow the `X` is completely useless, there's not a single time I click it since I'm not managing open editors, I'm managing editor panes. So... I would like the equivalent of a `Close Pane` action.

@bpasero <kbd>Alt</kbd> is a good idea; but if I'm reaching for the keyboard, I'll just do <kbd>Cmd W</kbd> as I'm doing today.

**Comment by bpasero** [comment] 2016-08-08 11:23
I think this will be handled as soon as it is possible to configure the toolbar buttons of the editor (something Joh is working on). 

I feel not good to just replace the X with the close all because that will piss off people that expect this to close one editor. 

I feel also bad to just add another action because that space is limited.

After all, I feel like adding a setting for this would make most sense.

Thoughts?

**Comment by joaomoreno** [comment] 2016-08-08 12:21
👍 on a setting

**Comment by stevencl** [comment] 2016-08-08 13:17
Just to confirm, when tabs are disabled, the setting would determine whether or not clicking X would close the top most editor in the group or the complete group? If the default is that it continues to close the top most editor, this sounds like a reasonable approach.

**Comment by bpasero** [comment] 2016-08-08 13:38
I worry that introducing this setting is confusing for when tabs are enabled because then imho it does not make any much sense...

**Comment by bpasero** [comment] 2016-08-08 13:46
After talking to @joaomoreno he thinks that https://github.com/Microsoft/vscode/issues/9904 would help him a lot. So I suggest we close this as duplicate of https://github.com/Microsoft/vscode/issues/7046 and wait for more user feedback.

**Closed by bpasero** 2016-08-08 13:46 UTC
Labels: feature-request, ux, workbench

**Comment by stevencl** [comment] 2016-08-08 13:50
OK. I was going to suggest something like: 

    //This setting controls how the close button works when tabs are disabled
    "workbench.editor.groupCloseButton" : "closeAllWhenTabsDisabled"

**Comment by bpasero** [comment] 2016-08-08 13:52
@stevencl that is great, I will add this to the other issue as suggestion!
