### ISSUE TITLE
Notebook serializers need viewOptions

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#122734] opened 2021-04-30 15:39 UTC
In order to complete the migration to serializers and stop using content providers, we need to be able to specify a `viewOption` with a `fileNamePattern` for the serializer so it can recognize files. I am working on Live Share notebooks support, and I need to register a serializer on the guest side that can recognize files with a specific file name. The only place to associate the serializer with a name pattern to pass in `NotebookDocumentContentOptions` to the serializer constructor: 

![image](https://user-images.githubusercontent.com/22576531/116718599-fcffba00-a98e-11eb-85b0-9362931be4a3.png)

But it says it is not ready for dev use yet and doesn't appear to work. 

cc @jrieken @rebornix

**Comment by jrieken** [comment] 2021-04-30 15:58
/duplicate of https://github.com/microsoft/vscode/issues/122733

**Closed** 2021-04-30 15:59 UTC
Labels: *duplicate
