### ISSUE TITLE
Bug of typing brackets

### ISSUE THREAD

**Issue by papple23g** [microsoft/vscode#147810] opened 2022-04-21 02:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows_NT x64 10.0.19044

When you select the text and press "(", it is expected that a pair of brackets will appear "()" to wrap up the text, which is no problem in the English input method, but switch to Chinese input method, the brackets will show the wrong pair (as the picture shows).
![220421_103107](https://user-images.githubusercontent.com/97163289/164360440-029c5657-e73e-4147-a0cc-4d7f72f4c7c5.gif)

**Comment by alexdima** [comment] 2022-04-21 10:21
@papple23g I could not reproduce. Here is what I have tried:
* configured the input language like this:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/5047891/164434059-f7270064-bb91-4deb-986b-96a58d632f84.png">
* in a txt file, I select some text and press <kbd>Shift</kbd> + <kbd>9</kbd>:

https://user-images.githubusercontent.com/5047891/164434835-944e7def-f685-4b6b-9738-f95043c50180.mp4

**Comment by papple23g** [comment] 2022-04-21 16:35
@alexdima Thank you for your reply, I apologize that I forgot to explain the details of the input method.
Actually, my input method is not "Chinese (Simplified, China)", but "Chinese - (Traditional, Taiwan)", and the problem occurs in Chinese input mode (you can switch between Chinese and English in that input method by simply pressing Shift)

● Does this reproduce when disabling all extensions? (Yes)
● Does this work as expected when changing the input mode to English? (Yes)

**Comment by alexdima** [comment] 2022-10-24 19:13
Fixed via https://github.com/microsoft/vscode/pull/147187

**Closed by alexdima** 2022-10-24 19:13 UTC
Labels: bug, windows, editor-input-IME, editor-autoclosing
