### ISSUE TITLE
TypeScript provides two identical tasks

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#31977] opened 2017-08-03 13:55 UTC
Steps to reproduce:

- create a fresh workspace
- create a tsconfig.json
```ts
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "./bld",
        "rootDir": "./",
        "strict": true,
        "alwaysStrict": true,
        "moduleResolution": "node"
    }
}
```
- create a test.ts file
```ts
console.log("Hello World");
```
- F1 > Run Task

Observe: you have two tsc build tasks listed.

<img width="551" alt="capture" src="https://user-images.githubusercontent.com/1931590/28925097-269dcfd8-7864-11e7-820b-8454a15ffb7e.png">

**Comment by mjbvz** [comment] 2017-08-03 21:31
Possible duplicate of #29929 

This should already have been fixed in current insiders builds. Are you still seeing the issue?

**Comment by dbaeumer** [comment] 2017-08-04 07:59
I saw this yesterday when running out of sources. The key is to have focus in the test.ts file after you created it.

**Comment by mjbvz** [comment] 2017-08-04 19:30
I'm still unable to reproduce this. What OS are you on?

**Comment by onlineservices283418** [comment] 2017-08-06 14:19
Complete STR is here #31527

**Comment by dbaeumer** [comment] 2017-08-07 08:41
I am using Windows 10. I tried it again this morning and the steps from above still reproduce this. I do have auto save on so both tsconfig.json and the test.ts are save to disk.

**Comment by dbaeumer** [comment] 2017-08-14 09:04
Reopening...

**Comment by dbaeumer** [comment] 2017-08-18 08:19
@mjbvz anything I can help with tracking this down?

**Comment by mjbvz** [comment] 2017-08-18 20:46
@dbaeumer Thanks, I think I've tracked it down. It came down to a path using `/` instead of `\` on windows. Testing now and will submit a fix shortly

**Closed** 2017-08-18 21:02 UTC
Labels: bug, needs more info, typescript
