### ISSUE TITLE
Trouble with selecting RTL texts in codes in new update

### ISSUE THREAD

**Issue by hrahimi270** [microsoft/vscode#92372] opened 2020-03-10 15:31 UTC
Issue Type: <b>Bug</b>

In the latest update, there is a trouble with selecting RTL texts in VSCode.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|-psn_0_5084377|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
smarty|imp|0.3.0
svelte-vscode|Jam|0.9.3
sftp|lix|1.12.9
vscode-nunjucks-formatter|oki|0.1.3
laravel-blade|one|1.20.0
material-icon-theme|PKi|4.0.1
nunjucks|ron|0.2.3
twig|wha|1.0.2
material-theme|zhu|3.2.3

</details>

**Comment by rebornix** [comment] 2020-03-10 17:15
@hrahimi270 could you please provide a recording of the screen to help demonstrate the problem you run into?

**Comment by rebornix** [comment] 2020-03-10 17:19
/duplicate of https://github.com/microsoft/vscode/issues/92373

**Closed** 2020-03-10 17:19 UTC
Labels: *duplicate, needs more info, new release
