### ISSUE TITLE
Cursor stuck on pointer

### ISSUE THREAD

**Issue by jafinn3** [microsoft/vscode#68851] opened 2019-02-16 19:24 UTC
Issue Type: <b>Bug</b>

Open the latest VSCode in Ubuntu. Hover mouse past line 23 or past character column 80. The cursor will stay as the default pointer, even when hovering over text. Occurs on top of embedded terminal as well, meaning the resize window cursor doesn't appear for that either. 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2052)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.42GB (7.41GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-sshfs|Kel|1.12.3
python|ms-|2019.1.0
cpptools|ms-|0.21.0
veriloghdl|msh|1.0.1
tmlanguage|Tog|0.9.0
vscode-arduino|vsc|0.2.25

</details>

**Comment by alexandrudima** [comment] 2019-10-25 12:05
Duplicate of #65294

**Closed by alexandrudima** 2019-10-25 12:05 UTC
Labels: bug, editor-rendering, linux
