### ISSUE TITLE
Broke extension with your update

### ISSUE THREAD

**Issue by pledbetter-cvet** [microsoft/vscode#123292] opened 2021-05-07 14:04 UTC
Your version 1.56 broke the Salesforce Query Editor extension.

**Comment by JacksonKearl** [comment] 2021-05-07 18:00
Could you provide more information on what exactly has broken?

**Comment by nrayburn-tech** [comment] 2021-05-07 19:20
Duplicate of #123281.

**Closed** 2021-05-07 19:57 UTC
Labels: needs more info

**Comment by AllanOricil** [comment] 2021-05-07 22:22
@JacksonKearl  Vscode downloads the app.js from the cdn, it runs, but the app is not mounting on the iframe. And there are no error messages anywhere, which makes it impossible to debug. I shared the source code with @mjbvz and if you want to help, I can also share with you.

**Comment by JacksonKearl** [comment] 2021-05-07 22:24
@mjbvz can handle this best
