### ISSUE TITLE
Unable to use variables in problemMatcher regexp

### ISSUE THREAD

**Issue by pakLebah** [Microsoft/vscode#69743] opened 2019-03-03 17:17 UTC
I have searched the issues repo and I believe this one hasn't been reported.

System:
- VSCode Version: 1.31.1
- OS Version: Mac OS Mojave

Steps to Reproduce:
1.  Put task's variable(s) into the `problemMatcher` object, for example `$cwd`, like this:
```
"problemMatcher": {
  "pattern": {
    "kind"    : "location",
    "regexp"  : "^\\${cwd}\\/(.*):(\\d.*):(\\d.*): (error|warning|info): (.*)$",
    "file"    : 1,
    "line"    : 2,
    "column"  : 3,
    "severity": 4,
    "message" : 5,
    "loop"    : true,
  }
}
```
2. Run the task, I use it to parse a compiler output, and it failed. If I manually put the content of `$cwd` variable (with necessary escaping), it works.

So, I think vs code doesn't replace any variable(s) being used within the `regexp` of `problemMatcher`. It should be a bug, right?

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2019-03-04 08:52
Duplicate of #69622. The way for more complex problem matchers should be new API.

**Closed** 2019-03-04 08:52 UTC
Labels: *duplicate, tasks

**Comment by pakLebah** [comment] 2019-03-04 12:06
I don't think it's quite similar. The problem of #69622 is with `package.json` which I didn't know about. This problem I'm reporting happens with `tasks.json` which everybody uses. And if the problem had been reported since long time ago, why didn't it get fix after all this time? I believe putting vscode variables into `regexp` (with automatic escaping) shouldn't be that hard.

**Comment by alexr00** [comment] 2019-03-04 14:09
A more complete solution for allowing more than just regex in problem matchers is to allow a new type of problem matcher which lets you write code for your problem matching instead of using a regex. With this solution, adding variable to the problem matcher is redundant. It does not make sense to have both. #11663 tracks adding new API for code problem matchers.
