### ISSUE TITLE
Permitir trabajar con multiples lenguajes

### ISSUE THREAD

**Issue by AndyUPC** [Microsoft/vscode#22863] opened 2017-03-19 22:41 UTC
- VSCode Version: 1.10.2
- OS Version: Win 10

Actualmente cuando trabajas con diferentes lenguajes, por ejemplo html y php , ya no resalta las etiquetas de cierre para html.

**Comment by weinand** [comment] 2017-03-20 08:51
translated:
"Currently when working with different languages, for example html and php, it no longer highlights the closing tags for html."

**Comment by aeschli** [comment] 2017-03-27 14:00
duplicate of #2915

**Closed by aeschli** 2017-03-27 14:00 UTC

**Comment by AndyUPC** [comment] 2017-03-27 16:51
I have reviewed other post with the same problem and do not give a concrete solution, because Microsoft does not correct this problem, since other editors like Atom and Sublime Text do very well without needing to configure or modify anything additional.
