### ISSUE TITLE
new and delete keywords no longer highlighted in C++ file

### ISSUE THREAD

**Issue by BrandonShockley** [Microsoft/vscode#71821] opened 2019-04-05 19:48 UTC
Issue Type: <b>Bug</b>

1. Update to VSCode 1.33 from 1.32.3
2. new and delete keywords no longer highlighted in C++ file

Doesn't change when disabling extensions.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-test-explorer|hbe|2.9.2
hex-fmt|ker|1.0.0
vscode-catch2-test-adapter|mat|2.4.3
rainbow-csv|mec|1.0.0
python|ms-|2019.3.6352
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
veriloghdl|msh|1.0.2
java|red|0.42.1
shader|sle|1.1.4
cmake|twx|0.0.17
unity-debug|Uni|2.7.2
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.16.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by Andrew088** [comment] 2019-04-06 00:13
Hi! I'm new to this project and would like to be assigned to this bug as well.

**Comment by valentinorecaldini** [comment] 2019-04-06 10:46
This is true for other keywords: operator, and, or. I haven't checked all the other ones, so I cannot say there aren't more.

**Comment by mflan48** [comment] 2019-04-07 22:48
Hi @alexr00, I would like to be assigned to this bug as well if possible.

**Comment by alexr00** [comment] 2019-04-08 08:27
@jeff-hykin, it looks like `new` used to be keyword.control.cpp. Now it is keyword.operator.memory.new.cpp. Is this intentional? If it's intentional, we can add the it into the themes, but ideally there wouldn't be too many changes like this since it requires constant updating of the themes.

**Comment by weinand** [comment] 2019-04-10 08:26
@alexr00 this can be closed, right?

**Closed** 2019-04-10 08:50 UTC
Labels: bug, candidate, grammar, themes

**Comment by alexr00** [comment] 2019-04-10 10:11
Yes, it is merged into the release branch.

**Comment by aeschli** [comment] 2019-04-10 19:05
Verified that fix is in stable d1875a089ed838af5a6c69f629482933321fa4c9

@alexr00 Insider still shows the problem

**Comment by alexr00** [comment] 2019-04-11 09:08
I just pushed the first part of a fix to master, so it should be in the next insiders. There are still more theme updates to make, but this will fix at least new, delete, using, and typedef in insiders.

**Comment by tristan957** [comment] 2019-04-14 06:56
This should be a blocking issue for the grammar update as well https://github.com/jeff-hykin/cpp-textmate-grammar/issues/95

**Comment by alexr00** [comment] 2019-04-15 08:09
@tristan957 thanks for the heads up. I'll update the grammar again for insiders.

**Comment by alexr00** [comment] 2019-04-16 15:53
Updated grammar again.

**Comment by tristan957** [comment] 2019-04-16 20:04
@alexr00, is the plan to move forward with https://github.com/jeff-hykin/cpp-textmate-grammar in future releases of VSCode?

This is more of an organizational question, but if Microsoft now owns GitHub, and by extension Atom, can't you guys just merge the original PRs? What is holding that back?

**Comment by alexr00** [comment] 2019-04-17 08:03
The plan is to move forward with https://github.com/jeff-hykin/cpp-textmate-grammar. There are folks working in that repository to make a better and well maintained C++ grammar. 🎉

The old Atom TextMate grammar does not have anyone who wants to improve and maintain it. That includes merging PRs.

**Comment by jeff-hykin** [comment] 2019-04-17 23:39
Thanks @alexr00 😁. We might break and misinterpret things some times, but I do want to be clear that we'll do whatever the community needs first.

Over the last few days I have been surprised with the number of important bugs though. I expected Beta testing would be effectively done by the people using the extension, and to some degree thats certainly true. I think most of them don't use the default theme though so I will start testing the default theme myself.

I've been looking into https://github.com/Microsoft/vscode-textmate to see if there is a way we can use it for integration testing which would help reduce regressions considerably. We added unit tests to the library awhile back and they've been helpful.

**Comment by jeff-hykin** [comment] 2019-04-17 23:42
@tristan957 You can expect that bugs as blatant as the one you reported won't happen often in the future. The cause of that one was from initial port from json to ruby for the C syntax, which was a recent and involved several changes. I try to get high priority bugs fixed within 12 hours of them being posted, and try to implement easy fixes within 24 hours.
