### ISSUE TITLE
flickering when fullscreen on Ubuntu Zesty + nvidia drivers

### ISSUE THREAD

**Issue by shoenig** [Microsoft/vscode#31796] opened 2017-08-01 02:32 UTC
- VSCode Version:
```
$ code --version
1.14.2
cb82febafda0c8c199b9201ad274e25d9a76874e
```
- OS Version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

- nVidia driver version:
```
$ cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.66  Mon May  1 15:29:16 PDT 2017
GCC version:  gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)
```

Steps to Reproduce:

0. Use nVidia graphics 
1. Launch code
2. Enter fullscreen (press f11)
3. Notice lots of flickering, especially when alt-tabbing between other programs with vscode running visibly in the background

Fortunately there is a perfect workaround, which is to launch with `--force-gpu-rasterization`

gnome users can edit the icon launcher
Edit `/usr/share/applications/code.desktop` and modify the two `Exec` lines to include the new flag:
```
[Desktop Entry]
Exec=/usr/share/code/code --force-gpu-rasterization --unity-launch %U
```
and
```
[Desktop Action new-window]
Exec=/usr/share/code/code --force-gpu-rasterization --new-window %U
```

Reproduces without extensions: Yes

**Comment by jhasse** [comment] 2017-08-03 09:20
I'm having the same problem, but with an Intel GPU on Ubuntu MATE 16.04 using Compiz. The `--force-gpu-rasterization` workaround also works :)

**Comment by bpasero** [comment] 2017-08-11 08:20
Maybe this is a duplicate of https://github.com/Microsoft/vscode/issues/25934 ?

**Comment by Tyriar** [comment] 2017-08-18 00:17
Yeah let's track it in that one.

**Comment by Tyriar** [comment] 2017-08-18 00:18
Duplicate of #25934

**Closed by Tyriar** 2017-08-18 00:17 UTC
Labels: linux, upstream
