### ISSUE TITLE
Links remain when text removed in editor

### ISSUE THREAD

**Issue by Dylan-Osborne** [microsoft/vscode#77571] opened 2019-07-18 11:41 UTC
- VSCode Version: 1.36.1 (system setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Add a link somewhere in your document.
2. Remove a line anywhere above your link, the bottom most link's 'underline' will remain where it was before the text was removed.
3. Sometimes the underline will blink continuously. It appears that if you save the document twice the underline is removed (only sometimes as well), otherwise the underline will be removed after a while.

Here's a GIF of the issue.
![LinkBlinkVisualStudioCode](https://user-images.githubusercontent.com/46000533/61454548-803e5000-a961-11e9-9e92-6f1f6d74a0e9.gif)

I have tested the issue in the latest insiders (1.37.0-insider (system setup)) and the error appears to still be there.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment] 2019-07-18 21:04
Possible duplicate of #48321

**Closed** 2019-07-22 09:11 UTC
Labels: *duplicate, editor-contrib
