### ISSUE TITLE
Perl syntax highlight is broken

### ISSUE THREAD

**Issue by Sco768** [microsoft/vscode#78708] opened 2019-08-08 15:27 UTC
Issue Type: <b>Bug</b>

Perl syntax highlight breaks with a simple line involving two pairs of square brackets:

        use strict;
        my %FORM = (logins => "Aaaa, Bbbb Cccc");
        my $good_highlight = "a string";
        # everything after this line is highlighted the wrong way
        my $logins_from_form = [split /[,\s]+/, $FORM{logins}];
        my $bad_highlight = "a string";

1. Create a new .pl file or choose Perl language manually, edit the file
2. Put the code above
3. Notice that the colors in the last line are different from the third one. In a real life situation that would make a few screens of mostly brown (or whatever "my" is in the last line) lines until a similar line would fix the highlight back.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.50GB (3.67GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
perl-html-template|bia|1.1.7
vscode-perl|cfg|1.18.0
copy-path|Eti|0.0.1
copy-filename|jac|2.1.4
mysql-syntax|jak|1.3.1
vscode-edit-csv|jan|0.1.2
python|ms-|2019.8.29288
copy-file-name|nem|1.2.0
java|red|0.47.0
trailing-spaces|sha|0.3.1
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2

</details>

**Comment by alexr00** [comment] 2019-08-13 10:25
Duplicate of https://github.com/textmate/perl.tmbundle/issues/27

**Closed by alexr00** 2019-08-13 10:25 UTC
