### ISSUE TITLE
Allow detachable multiple windows on the same workspace

### ISSUE THREAD

**Issue by pavlos256** [Microsoft/vscode#367] opened 2015-11-20 17:36 UTC
Allow opening additional windows (BrowserWIndow) to be able to work on multi-monitor setups.

See also:
- [Detachable split-view](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8279298-detachable-split-view)
- [Ability to have a "folder" open over multiple windows (like Visual studio)](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7764594-ability-to-have-a-folder-open-over-multiple-wind)
- [Multiple windows, same folder](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8162727-multiple-windows-same-folder)

**Comment by stereokai** [comment] 2016-02-02 11:00
+1.

It is quite limiting, and very annoying, that when opening the same workspace (folder, or file) in a new window, VSCode instead jumps to the existing window.

**Comment by bpasero** [comment] 2016-03-14 18:36
https://github.com/Microsoft/vscode/issues/2686

**Comment by pavlos256** [comment] 2016-06-24 09:56
@bpasero I consider this different from #2686. This is about having multiple OS windows with one VSCode instance. One sidebar, one command bar and being able to drag editors out from one OS window into another OS window.

Do you think the work done for #2686 will also allow this?

**Comment by etoah** [comment] 2016-12-24 03:51
+1

**Comment by wupaz** [comment] 2017-01-24 14:25
+1

**Comment by bit2pixel** [comment] 2017-05-08 23:01
+1. Even only a detachable `PROBLEMS` `OUTPUT` `DEBUG CONSOLE` `TERMINAL` section would make a huge difference. Test results on a different screen would greatly increase productivity.

**Comment by dacrouch** [comment] 2017-05-24 16:56
This is the single issue standing in the way of finally migrating away from Eclipse for me.

**Comment by jeremyd** [comment] 2017-06-30 21:02
The progress on this is underwhelming since 2015.

**Comment by d4hines** [comment] 2017-07-06 18:43
Opening a new window on a work space that is already open seems to be impossible, no matter how I go about it. This goes very much against my intuition and the "principle of least surprise" - why should the application go out its way to prevent a new window from opening if another one already exists?

**Comment by BentOnCoding** [comment] 2017-08-17 19:49
VS Code Devs : we need this so bad.

Please !

**Comment by stereokai** [comment] 2017-08-17 23:05
Here is a work around:

Wrap your project's folder in another, empty folder, like this:
```
├─ New empty folder
└─── Project root
```

Now you can open the same project in separate instances of VSCode - just open each folder in VSCode!

**Comment by Robinfr** [comment] 2017-09-15 22:32
This, for me, is also the last reason not to switch to VSCode completely yet.

**Comment by RoyTinker** [comment] 2017-10-05 16:57
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/10121. Could y'all go vote there if you get a chance?

**Comment by RoyTinker** [comment] 2017-10-05 16:58
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/10121 (and that one has a few more more votes)... could y'all go vote there? :-)

**Comment by bpasero** [comment] 2017-11-21 16:28
@RoyTinker yeah agree, please cast your vote at https://github.com/Microsoft/vscode/issues/10121

**Closed by bpasero** 2017-11-21 16:28 UTC
Labels: feature-request, workbench-electron, workbench-layout
