### ISSUE TITLE
[Bug] Tab completion issue with Copilot

### ISSUE THREAD

**Issue by melMass** [microsoft/vscode#130674] opened 2021-08-12 12:34 UTC
### Report summary
**Does this issue occur when all extensions are disabled?:**

I'm not sure how to use `--disable-extensions` while still enabling Copilot?

Running the Extension Bisect (two times) always return that the issue is copilot, or at least the combination of extensions never solves the tab issue

- VS Code Version: 1.60.0-insider | 7c25c174726ab969db3f99058cdf24bcfae1cfbe
- OS Version: Darwin x64 19.6.0 (Catalina)
---

### Report

Hi,

As discussed in #127797 I have the same issue, but it is not related to Emmet. 
And running bisect I could not found if another extension was causing this.
@hediet You told me to tag you so here we are, I think @bala0406 have the same issue, do not hesitate to post details here.

Thanks

**Comment by hediet** [comment] 2021-08-12 13:43
> Running the Extension Bisect (two times) always return that the issue is copilot, or at least the combination of extensions never solves the tab issue

Please disable all extensions and only enable the Copilot extension.

A gif would also be very helpful, so I can try to reproduce!

**Comment by melMass** [comment] 2021-08-13 01:35
> Please disable all extensions and only enable the Copilot extension.

Is there an easy way to enable all but one? Cf:

> I'm not sure how to use --disable-extensions while still enabling Copilot?

![copibug](https://user-images.githubusercontent.com/7041726/129292340-2b7ea2ba-46e4-4f7f-a567-6be50eee7ea9.gif)

**Comment by bala0406** [comment] 2021-08-13 04:54
The issue still persists with all the extensions disabled except co-pilot.

**Comment by e-desouza** [comment] 2021-08-13 05:09
I have the same issue. It's showing me the recommendation but there's no shortcut I can enter to actually accept that change. I tried adding/changing the shortcuts that show up under "copilot" in keyboard shortcuts but other than "Open Copilot" (which opens up a side bar, with the recommendations) none of the others work.

**Comment by hediet** [comment] 2021-08-13 07:27
> Is there an easy way to enable all but one? Cf:

You can disable all extensions:

![image](https://user-images.githubusercontent.com/2931520/129320288-4e6351a9-37a2-40ac-baca-f937a1c054b7.png)

And then just enable Copilot.

> ![copibug](https://user-images.githubusercontent.com/7041726/129292340-2b7ea2ba-46e4-4f7f-a567-6be50eee7ea9.gif)

This looks like there is another extension active that shows "Expected indented block", I guess Error Lens.

**Comment by bala0406** [comment] 2021-08-13 10:12
Also, one more associated isuue, when github co-pilot is active, brackets are not auto-closing. Tried setting "editor.autoClosingBrackets": "always", but still brackets don't close automatically.

**Comment by melMass** [comment] 2021-08-13 14:25
> This looks like there is another extension active that shows "Expected indented block", I guess Error Lens.

Yes!! Enabling only **Python** and **Copilot**, works. 

And I actually thought: *How can someone know what keybindings an addon sets?*... I then looked at my keybindings.... There is an `extension` column (BTW having a way to sort would be nice) and the culprit is...... 🥁 

### TabOut ([marketlink](https://marketplace.visualstudio.com/items?itemName=albert.TabOut))

I feel so dumb. In my defense, I had no idea about this extension 😅 

I'm leaving it open for @bala0406 I think you can track it down as I did.

**Comment by melMass** [comment] 2021-08-13 14:44
Closing he also found his issue ([Windows Default Keybindings](https://marketplace.visualstudio.com/items?itemName=smcpeak.default-keys-windows))

**Closed** 2021-08-13 14:44 UTC

**Comment by melMass** [comment] 2021-08-14 11:16
> Also, one more associated isuue, when github co-pilot is active, brackets are not auto-closing. Tried setting "editor.autoClosingBrackets": "always", but still brackets don't close automatically.

This should be a similar issue, an extension that overrides the behavior somehow, you should open a new issue!

**Comment by hediet** [comment] 2021-08-15 11:09
> This should be a similar issue, an extension that overrides the behavior somehow, you should open a new issue!

This is copilot and a known issue that is already being tracked.

**Comment by melMass** [comment] 2021-08-15 11:10
> > This should be a similar issue, an extension that overrides the behavior somehow, you should open a new issue!
> 
> 
> 
> This is copilot and a known issue that is already being tracked.

Privately or do you have an issue #?

**Comment by hediet** [comment] 2021-08-15 11:16
I think it is privately tracked in the Copilot org, as it is not an issue related to VS Code.
VS Code has everything that is needed to fix that issue on Copilot's side.

**Comment by CodeNameNinja** [comment] 2021-09-07 17:20
For me it was editing `editor.action.inlineSuggest.commit` in the key bindings

![image](https://user-images.githubusercontent.com/35192626/132385585-13dacbe1-50a7-4bfd-8017-c6d66d5814b3.png)
