### ISSUE TITLE
Issues about "clear" command in powershell prompt

### ISSUE THREAD

**Issue by zhong-yiyu** [microsoft/vscode#108410] opened 2020-10-09 15:57 UTC
- VSCode Version: Stable Build
- OS Version: Windows 10 

The `clear` command in powershell doesn't work as in native powershell windows. In VS Code sometimes it just rolls the current information up and show you a new page with all the former information up in the window, causing problems in searching.
Steps to Reproduce:

1. Open some files and use the powershell to generate some output
2. Move to powershell's window and type in 'clear'
3. The powershell's window didn't acutually "clear" everything, sometimes they just roll the current information up and show you a new page.

Does this issue occur when all extensions are disabled?: Yes\

**Comment by alannt777** [comment] 2020-10-10 09:37
could be a duplicate of #72708

**Closed** 2020-10-10 10:27 UTC

**Comment by zhong-yiyu** [comment] 2020-10-10 16:07
Thanks! That totally explained my questions.
________________________________
发件人: Alan Ninan Thomas <notifications@github.com>
发送时间: 2020年10月10日 上午 10:38
收件人: microsoft/vscode <vscode@noreply.github.com>
抄送: zhong-yiyu <zhong_yi_yu@outlook.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/vscode] Issues about "clear" command in powershell prompt (#108410)


could be a duplicate of #72708<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F72708&data=02%7C01%7C%7Ce33b50eebb554a7765da08d86d002f91%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637379194845417947&sdata=NWz3G%2Fk18TfiwITPGgCpvhf0TMZAnjURuOlAwVlSBKE%3D&reserved=0>

―
