### ISSUE TITLE
Native Tab commands missing from Command Palette in March 2020 (version 1.44) update

### ISSUE THREAD

**Issue by bsdahl** [microsoft/vscode#94814] opened 2020-04-09 17:12 UTC
- VSCode Version: March 2020 (version 1.44)
- OS Version: MacOs Catalina 10.15.4

Steps to Reproduce:

1. Open Command Palette
2. Search for any Native Tabs commands:

- "New Window Tab"
- "Show Previous Window Tab"
- "Show Next Tab"
- "Move Tab to New Window"
- "Merge All Windows"

The commands are no longer available in the Command Palette. Reverting to the February 2020 version brings them back for me.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2020-04-09 18:05
Duplicate of https://github.com/microsoft/vscode/issues/94734

**Closed** 2020-04-09 18:06 UTC
Labels: *duplicate
