### ISSUE TITLE
Terminal Rendering Issue; Insiders 1.25 on Windows 10

### ISSUE THREAD

**Issue by christopherwolf1** [Microsoft/vscode#51798] opened 2018-06-13 20:52 UTC
- VSCode Version:
Version: 1.25.0-insider
Commit: 583f1e4934c5fd3b62c2ca5bf177c728b31b9605
Date: 2018-06-13T05:18:10.709Z
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:
Windows 10 Enterprise Version 1803
Build 17134.112

- Steps to Reproduce:
1. Launch Visual Studio Code Insiders
2. Wait for Integrated Terminal to load; unless a carriage return and line feed is executed, the portion beneath the active command line in the terminal is pure black. After a CRLF event, the new line restores the background to the normal color, but the black portion beneath still remains. See attached GIF. 

Does this issue occur when all extensions are disabled?: Yes

![vscode-insiders_integratedterminalbug](https://user-images.githubusercontent.com/15132959/41377100-e79021e4-6f0f-11e8-8898-10c7505d7118.gif)

**Comment by jordanmaslyn** [comment] 2018-06-14 01:03
Duplicate of #51774

**Comment by yume-chan** [comment] 2018-06-14 06:55
Duplicate of #51749

It's already been fixed in today's insiders version.

**Closed** 2018-06-14 07:10 UTC
Labels: *duplicate, integrated-terminal

**Comment by christopherwolf1** [comment] 2018-06-14 09:43
Confirmed for me with the latest insider's version, as stated above; pretty fast fix. 😃 👍
