### ISSUE TITLE
Custom controls don't work on touchscreen

### ISSUE THREAD

**Issue by Helediron** [microsoft/vscode#79273] opened 2019-08-16 05:55 UTC
Issue Type: <b>Bug</b>

Use touchscreen laptop. Go to settings, find any checkbox.
Tap the checkbox with finger and nothing happens.
Click the same checkbox with mouse and it turns on/off normally.
I can use checkboxes in other programs through touch screen.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.10.6
beautify|Hoo|1.5.0
powershell|ms-|2019.5.0
debugger-for-chrome|msj|4.11.7

</details>

**Comment by roblourens** [comment] 2019-10-19 02:05
All the custom controls need to use our touch.ts

**Comment by rzhao271** [comment] 2020-11-06 21:49
Cannot reproduce on latest Insiders. @Helediron feel free to reply if this issue still occurs for you after updating to the latest version of VS Code.

**Comment by roblourens** [comment] 2020-11-07 00:52
Are you sure? Which touchscreen device did you try on?

**Comment by roblourens** [comment] 2020-11-09 17:25
Checkboxes work now but dropdowns still don't

**Comment by 747** [comment] 2021-05-27 06:49
Still persisting as of 1.56.2. Doesn't work either with finger or touch pen.

**Comment by roblourens** [comment] 2021-11-05 16:42
Dupe of https://github.com/microsoft/vscode/issues/73283

**Closed by roblourens** 2021-11-05 16:42 UTC
Labels: bug, settings-editor
