### ISSUE TITLE
[var] keyword is also highlighted in any word starting with 'var...'

### ISSUE THREAD

**Issue by ujc** [Microsoft/vscode#4555] opened 2016-03-22 12:34 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 7

Steps to Reproduce:

1. Set the "Language Mode" to "Javascript"
2. Write "variable", you'll see that the prefix "var" is highlighted

This doesn't happen when the word starting with "var" is part of a function argument, or inside strings
*Tried with multiple themes, issues seems to be theme-agnostic (happens on all of them)

![variables](https://cloud.githubusercontent.com/assets/5549335/13951630/ed72bd52-f03a-11e5-9131-cd55a0938c7f.png)

**Comment by aeschli** [comment] 2016-03-22 13:48
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by aeschli** 2016-03-22 13:48 UTC
