### ISSUE TITLE
Terminal Window does not scroll

### ISSUE THREAD

**Issue by jboothe** [Microsoft/vscode#10221] opened 2016-08-05 20:20 UTC
Terminal window does not allow scrolling up to previous output. Previous to 1.4, this was an intermittent problem, now its a permanent problem. 

![screen shot 2016-08-05 at 4 17 01 pm](https://cloud.githubusercontent.com/assets/3723481/17449428/57e1ce64-5b28-11e6-8005-011eaa3589a1.png)

- VSCode Version: 1.4
- OS Version: OS X v10.11.6
- zsh

Steps to Reproduce:
 1. Open prompt window
 1. Enter a few commands to create more output than the window size
 1. Attempt to scroll up or down

**Comment by Tyriar** [comment] 2016-08-05 20:52
Duplicate of https://github.com/Microsoft/vscode/issues/7817, the upstream issue is https://github.com/sourcelair/xterm.js/issues/151

**Closed by Tyriar** 2016-08-05 20:52 UTC
