### ISSUE TITLE
Changing username causes Setup error

### ISSUE THREAD

**Issue by icecream17** [microsoft/vscode#120289] opened 2021-04-01 02:22 UTC
Issue Type: <b>Bug</b>

These steps seem strange... but I did this to remove a space from my user path since it was causing issues

1. Be on a windows admin account
2. Create another admin account
3. Go to the other admin account, and rename the folder `C:\Users\<username1>` to a different username, say `C:\Users\<username2>`
    - In this case, username1 had a space.
    - see https://superuser.com/questions/890812/how-to-rename-the-user-folder-in-windows-10
    - I changed the registry and updated all user and system environment variables, including path, as stated in the above link, but I don't think that's important here.
4. Restart computer
5. Log in to the first original admin account
6. Open vscode, which was installed before you changed your username
7. Wait 5-30 seconds before you get the Setup errors

Screenshots:
![image](https://user-images.githubusercontent.com/58114641/113231624-43afa680-9261-11eb-829c-f64c49bacdba.png)
![image](https://user-images.githubusercontent.com/58114641/113231657-575b0d00-9261-11eb-9f23-7a2b93d07b7c.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

Also happens on `code --disable-extensions`

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.22GB free)|
|Process Argv|--crash-reporter-id 2f428590-17e5-4109-be1b-9a06114d5666|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
clock|ang|1.0.1
markdown-preview-github-styles|bie|0.1.6
vscode-styled-jsx|bla|2.0.0
npm-intellisense|chr|1.3.1
doxdocgen|csc|1.1.0
c-cpp-compile-run|dan|1.0.13
vscode-markdownlint|Dav|0.40.1
vscode-eslint|dba|2.1.19
deepcode|dee|3.0.11
python-preview|don|0.0.4
githistory|don|0.6.16
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.18
vscode-highlight|fab|1.4.1
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.3
auto-close-tag|for|0.5.10
vscode-pull-request-github|Git|0.24.0
todo-tree|Gru|0.0.209
better-cpp-syntax|jef|1.15.5
vscode-gutter-preview|kis|0.27.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
atom-keybindings|ms-|3.0.9
cpptools|ms-|1.2.2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4070
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
vscode-react-native|msj|1.4.1
java|red|0.76.0
rust|rus|0.7.8
html5-boilerplate|sid|1.1.1
js-jsx-snippets|sky|10.1.0
tabnine-vscode|Tab|3.2.16
even-better-toml|tam|0.11.1
open-in-browser|tec|2.0.0
gnu-mapfiles|tro|1.1.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30265425
openwslfolder:30282073
vscoresta800:30279781
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by yume-chan** [comment] 2021-04-01 06:03
Duplicate of #97141

See https://github.com/microsoft/vscode/issues/97141#issuecomment-628464509

(I remember there was another one with normal English but I can't find it)

**Comment by joaomoreno** [comment] 2021-04-01 13:05
Thanks @yume-chan. As referred in the other issue:

> We do not support changing the installation path, only uninstalling and reinstalling in a different location. Sorry about that!

I suggest uninstalling VS Code, renaming the user and reinstalling VS Code for next time.

**Closed by joaomoreno** 2021-04-01 13:05 UTC
