### ISSUE TITLE
Improve "Extensions" pane

### ISSUE THREAD

**Issue by AntonDemchenko** [Microsoft/vscode#71358] opened 2019-03-28 09:25 UTC
I'm tired resizing "Enabled", "Recommended", "Disabled" parts in "Extensions" pane. I think it would be better to make them as separated tabs.

**Comment by shiftgeist** [comment] 2019-03-28 09:32
IMO it is fine how it is because I focus on the "Enabled" tab while the others are closed. If i need to disable some i open the tab.

**Comment by sandy081** [comment] 2019-03-28 13:18
Duplicate of #68527

**Closed** 2019-03-28 13:18 UTC
Labels: *duplicate, extensions
