### ISSUE TITLE
I've already logged in to my account, but I'm still repeatedly told to log in.

### ISSUE THREAD

**Issue by imwangpan** [microsoft/vscode#105698] opened 2020-08-31 02:25 UTC
Issue Type: <b>Bug</b>

I have logged into my account, but every day or two it shows that I am not logged into any account. I can log in again, but every day or two it shows that I haven't logged in to any account. Please fix this problem as soon as possible.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19042

**Comment by RMacfarlane** [comment] 2020-09-01 15:51
Closing as a duplicate of https://github.com/microsoft/vscode/issues/105503

**Closed by RMacfarlane** 2020-09-01 15:51 UTC
