### ISSUE TITLE
Explorer sort order doesn't follow standard practice

### ISSUE THREAD

**Issue by iliazlobin** [microsoft/vscode#79940] opened 2019-08-27 19:32 UTC
I've noticed that the sort order in the Explorer view doesn't comply with the one in Windows Explorer and in output of the `ll` linux command. This makes me feel confused sometimes especially if there are a lot of files in a folder.

References:
* https://github.com/microsoft/vscode/issues/9437
* https://github.com/microsoft/vscode/issues/5066

Version: 1.38-insider (user setup)

![image](https://user-images.githubusercontent.com/3456942/63801791-c9e36880-c919-11e9-8939-fb550451aac9.png)

**Comment by gjsjohnmurray** [comment] 2019-08-27 19:54
@iliazlobin did you see #27759 ? If yours is a duplicate of it please close this one.

**Closed** 2019-08-28 08:16 UTC
Labels: *duplicate
