### ISSUE TITLE
Can not lunch the example extension "hello world~" , it show some error.

### ISSUE THREAD

**Issue by Aaronphy** [microsoft/vscode#117109] opened 2021-02-20 03:10 UTC
- VS Code Version: 1.53.0 
- OS Version:  macOS Big Sur

Steps to Reproduce:

1.yo and generate the example extension
  ```bash
	yo code 
	choose ts extension
	whether bundle or not 
  ```
2. Press F5 to debug the example extension "hello world"
3. The error shows up:
   ![image](https://user-images.githubusercontent.com/16236806/107142797-4500d900-696c-11eb-8dd9-cad512966f5c.png)

It cannot debug normally as the doc says, please help to see and fix it.
This is my vscode ```setting.json``` config about the terminal :

```json
	"terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.inheritEnv": false
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment] 2021-02-22 11:42
@Aaronphy I cannot reproduce the problem you are seeing.
Does it make a difference if you change the `"terminal.integrated.inheritEnv"` to true?

**Comment by weinand** [comment] 2021-02-22 11:51
Since extension debugging doesn't use the integrated terminal directly and since the error message refers to the "npm run watch" task, I suspect that the `"terminal.integrated.inheritEnv": false` affects the watch task in a negative way.

@alexr00 does this ring a bell?

**Comment by alexr00** [comment] 2021-02-22 12:39
Yes, most users need to have ` "terminal.integrated.inheritEnv": true` to use npm tasks. Otherwise, the location of npm cannot be found. I would close this issue since this is the intended behavior.

**Comment by weinand** [comment] 2021-02-22 13:11
@Aaronphy so, `"terminal.integrated.inheritEnv": false` prevents npm from working (which breaks building typical npm-based extensions).

**Closed by weinand** 2021-02-22 13:11 UTC
Labels: needs more info
