### ISSUE TITLE
Ubuntu install vscode turn white in my mac Parallels Desktop

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [microsoft/vscode#93128] opened 2020-03-21 05:11 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by wangwenqiangGitHub** [comment] 2020-03-21 05:12
1. 1.43.1
2.16.04

**Comment by wangwenqiangGitHub** [comment] 2020-03-21 05:13
VSCode Version: 1.43.1
OS: Ubuntu 16.04

**Comment by wangwenqiangGitHub** [comment] 2020-03-21 05:36
have already been solved

**Comment by aeschli** [comment] 2020-03-21 10:04
I understand that the issue is solved now. Closing.

**Closed** 2020-03-21 10:03 UTC
