### ISSUE TITLE
Cannot read property 'openTaskFile" of undefined

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#83988] opened 2019-11-05 14:33 UTC
Issue Type: <b>Bug</b>
It seems that if no .vscode/tasks.json it currently cannot be generated. Also if you create it manually, it cannot be opened neither.

  ERR Cannot read property 'openTaskFile' of undefined: TypeError: Cannot read property 'openTaskFile' of undefined
    at s (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4542:309)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4543:695

VS Code version: Code - Insiders 1.40.0-insider (d39e6b396c3ea364584126316a0fcf30f9cb378e, 2019-11-05T01:58:38.382Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.62GB free)|
|Process Argv|-psn_0_5703024|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment] 2019-11-06 08:57
Duplicate of https://github.com/microsoft/vscode/issues/83836. If you install the latest insiders version (515f496d9a7617caf07f38298f610920f60834d6) then you'll have the fix

**Closed** 2019-11-06 08:58 UTC
Labels: *duplicate
