### ISSUE TITLE
When pressing Delete Key is Acting Weird

### ISSUE THREAD

**Issue by felipebraga** [microsoft/vscode#76632] opened 2019-07-04 19:22 UTC
Issue Type: <b>Bug</b>

In the file **Explorer** when I press the key "Delete", it's showing a filter option, like if I was searching a file by name.

Follow an image:

![image](https://user-images.githubusercontent.com/2760663/60685119-c383c380-9e77-11e9-9eff-94069d92b1bd.png)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.19.56-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3487)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (4.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
debugger-for-chrome|msj|4.11.6
vetur|oct|0.21.1

</details>

**Comment by gjsjohnmurray** [comment] 2019-07-04 19:55
Duplicate of #76514 and will be fixed in upcoming recovery release.

**Comment by dbaeumer** [comment] 2019-07-05 07:16
Yes, dups #76514

**Closed by dbaeumer** 2019-07-05 07:16 UTC
Labels: new release
