### ISSUE TITLE
Show line numbers with references results

### ISSUE THREAD

**Issue by mmakrzem** [Microsoft/vscode#63785] opened 2018-11-26 15:26 UTC
Issue Type: <b>Feature Request</b>

I have set search.showLineNumber = true.

When I use the search feature I see the line numbers as expected.  When I right click on a variable and choose Find All References, I get a panel of "Search Results" however each result does not display the line number.

Either a new setting option should be added (ie references.showLineNumber) or just piggy back off the search.showLinNumber setting to indicate whether line numbers should be displayed in the same way as in the search results panel.

VS Code version: Code - Insiders 1.30.0-insider (04cbc78e23eeddc368d634ed52402dbc6f28ebc9, 2018-11-23T10:06:54.093Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment] 2018-11-26 16:20
/duplicate of https://github.com/Microsoft/vscode-references-view/issues/14

**Closed** 2018-11-26 16:20 UTC
Labels: *duplicate, insiders
