### ISSUE TITLE
Ctrl+P when Release Notes is open, opens a recently open file

### ISSUE THREAD

**Issue by MrSparc** [microsoft/vscode#90579] opened 2020-02-13 10:08 UTC
Issue Type: <b>Bug</b>

1. After an update the "Release Notes: 1.42.0" is opened
2. While active, press Ctrl + P  "Go to File" keeping the Ctrl pressed for a few seconds, showing the list of recently open files
3. When release the Ctrl key, automatically opens the recently open file that was selected by default instead of allow us to type any command

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 4.12.14-lp151.28.36-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.53GB (2.23GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
latex-preview|ajs|0.5.1
alignment|ann|0.3.0
blamer-vs|bea|0.5.2
vscode-eslint|dba|2.0.15
xml|Dot|2.5.0
vscode-svn|eli|0.1.0
vscode-postman|eri|1.0.2
vscode-peacock|joh|3.3.1
svn-scm|joh|2.7.0
chat|kar|0.31.0
perl-debug|mor|0.6.3
hg|mrc|1.3.0
vscode-docker|ms-|0.10.0
mssql|ms-|1.8.0
python|ms-|2020.2.63072
cpptools|ms-|0.26.3
Go|ms-|0.13.0
vsliveshare|ms-|1.0.1587
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
java|red|0.55.1
rust|rus|0.7.0
omnipascal|Wos|0.17.3
clang-format|xav|1.9.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-02-13 10:24
Probably a duplicate of #82670

**Comment by JacksonKearl** [comment] 2020-02-13 19:41
I can't reproduce. Are you opening the command pallet or the file picker? It's not clear to me what you mean by "open the Command Palette keeping the Ctrl pressed for a few seconds, showing the list of recently open files".

**Comment by MrSparc** [comment] 2020-02-14 11:13
Because a picture is worth a thousand words:
With Release Notes open and do Ctrl+P:
![VSC_Ctrl+P_withReleaseNotes](https://user-images.githubusercontent.com/2487742/74526156-ad180d00-4f1a-11ea-94a3-cfcddac07356.gif)

Without Release Notes open and do Ctrl+P:
![VSC_Ctrl+P_withoutReleaseNotes](https://user-images.githubusercontent.com/2487742/74526335-11d36780-4f1b-11ea-85f8-3702c5d749ae.gif)

**Comment by JacksonKearl** [comment] 2020-02-14 14:39
@MrSparc thanks, I can reproduce now. Seems to only happen on Linux.

**Comment by bpasero** [comment] 2020-02-14 15:01
If it only reproduces in release notes, I suspect a webview issue with keybindings which https://github.com/microsoft/vscode/issues/82670 is similar.

**Comment by IanMatthewHuff** [comment] 2020-02-27 22:36
Just as a +1 on this. For the Python extension we use a number of webviews. If any of our webviews are opened Ctrl+* commands get doubled. Had a few reports on this already:
https://github.com/microsoft/vscode-python/issues/10147
https://github.com/microsoft/vscode-python/issues/10267

I was investigating our code when I realized that I could repro it not just with our stuff, but with the coding cat webview sample.

**Comment by gjsjohnmurray** [comment] 2020-02-28 09:06
@IanMatthewHuff are you on Linux too?

@all I assume it's intentionally convenient that if I hold Ctrl down, then press and release P to open the list, each subsequent press-and-release of P moves the list selector down one position. Similarly, Shift+P moves up one position. And when I finally release the Ctrl key it opens whatever item is currently selected.

**Comment by IanMatthewHuff** [comment] 2020-02-28 16:24
@gjsjohnmurray not normally, but when our customers reported this I checked it out on Linux. I only see this happen there, not on Mac or Windows.

**Comment by mjbvz** [comment] 2020-04-17 22:48
Duplicate of #88284 I believe. I just checked in a fix but let me know if still see this in the next insiders build

**Closed by mjbvz** 2020-04-17 22:48 UTC
Labels: webview

**Comment by MrSparc** [comment] 2020-04-27 09:10
I'm sorry, but this issue still happens in the release March 2020 (v1.44.2):
![VSCMarch2020_Ctrl+P_withReleaseNotes](https://user-images.githubusercontent.com/2487742/80354912-48105a00-886f-11ea-8cb9-58d1f97ef803.gif)
