### ISSUE TITLE
Webview view navigation command buttons have unexpected visibility behaviour

### ISSUE THREAD

**Issue by matthewjamesadam** [microsoft/vscode#171456] opened 2023-01-17 02:27 UTC
Does this issue occur when all extensions are disabled?: No, as this is an extension API issue

- VS Code Version: 1.74.3
- OS Version: MacOS 12.5.1

When a webview view displays a title command (using the `group: navigation` option), the resulting button can become invisible when focus is removed from the webview view.  This is reproducible using the calico colors example (https://github.com/Microsoft/vscode-extension-samples/tree/main/webview-view-sample).

Steps to Reproduce:

1. Run the Calico Colors sample app
2. Open up the 'Calico Colors' view
3. Click on a text editor to remove focus from the Calico Colors view
4. Move the mouse over the Calico Colors view

I would expect that the 'Clear Colors' command button would be visible when the mouse hovers over the webview, but it is not.  It is only displayed when the mouse hovers over the webview title, or when the webview has focus.  This is not how the built-in VSCode views work, for instance the Outline view always displays these buttons when the mouse is within the view area.

Here is a recording showing this behaviour.  Note that the Outline and Timeline views behave differently then the Calico Colors view:

https://user-images.githubusercontent.com/2133518/212796093-6c86b3ad-c97a-4f69-81c2-2c5e1e6cada9.mp4

**Comment by mjbvz** [comment] 2023-01-17 18:26
Duplicate of #109030

**Closed by mjbvz** 2023-01-17 18:26 UTC
