### ISSUE TITLE
Don't differentiate between file and web link?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141417] opened 2022-01-25 13:20 UTC
Testing #141342

I find that the differentiation between "Open Most Recent File Link" and "Open Most Recent Web Link" adds too much mental overload. Both labels are very similar and easy to confuse. I would merge this into "Open Most Recent Link" (or just "Open Link"), esp. since there is the "Open detected link" power command which all links and groups them by kind

**Comment by Tyriar** [comment] 2022-01-25 15:13
The idea with them was so you could hook up a keybinding to open the link without a quick pick. Eg. run a server and press ctrl+blah to open the server in the browser. We could do this via args but I don't think it's reasonable right now to expect users to use args in keybindings since the UI doesn't support them.

**Comment by jrieken** [comment] 2022-01-25 15:26
Maybe have one command for "Open Last Link" and than the two special commands for file and web links?

**Comment by Tyriar** [comment] 2022-01-25 15:28
"Open Last Link" implies to me that "Word" links would also be included, which would make such a command pretty much useless since the last word link is probably something silly like part of your prompt or the command.

**Comment by meganrogge** [comment] 2022-01-25 18:02
It's more accessible to be descriptive and specific with what these commands do.

This is also why we have the more generic `Open Detected Link` command - to educate about the types of links and to catch the case you're talking about @jrieken.

**Comment by Tyriar** [comment] 2022-01-26 16:17
After a chat with @meganrogge we're going to close this as designed because:

- Web and File are important to keep the commands as a single action with no further actions (as opposed to Open Detected Link...)
- Ideally we would have a single `Open Last Link`, but the keybindings editor does not yet support setting arguments, or creating multiple keybindings with different arguments for the same command

We could revisit this if those improvements to the keybindings editor ever happens.

**Closed by Tyriar** 2022-01-26 16:17 UTC
Labels: under-discussion
