### ISSUE TITLE
Markdown: Linking to an internal page heading is failed

### ISSUE THREAD

**Issue by mdj982** [microsoft/vscode#157260] opened 2022-08-05 12:18 UTC
Does this issue occur when all extensions are disabled?:
- For WSL targets / SSH targets (Linux), when only Remote WSL / Remote SSH extension enabled -> Yes
- When open those files (located on Windows) by VS Code for Windows (not WSL) -> No

- VS Code Version: 1.70.0
- OS Version: Windows 10

Steps to Reproduce:

1. Consider the following markdown file.

```md
# Title
## Table of contents
- [First Section](#first-section)
## First Section
```

2. What expected when "Ctrl + Click" to the (#first-section) link is to jump to the page heading of "First Section". However, I got the following error.
- The path separator seems to be back slash instead of slash.
- This error occurs when Markdown files are regarded as a component of WSL or SSH targets (Linux).
- Behavior by opening those files on Windows with VS Code for Windows is correct.
![image](https://user-images.githubusercontent.com/16437623/183074871-b1785905-a5b2-4a3d-b0fb-164e0ed60c61.png)

**Comment by mjbvz** [comment] 2022-08-05 16:51
Just to confirm, this only happens when you are connected to a remote workspace from windows? It doesn't happen on if you open the workspace directly on windows?

**Comment by mdj982** [comment] 2022-08-06 05:32
Exactly. That is what I mean.

I also found that an unnamed new file (Ctrl + N , input the above sample, without saving) works well.
After saving that file with any name, this issue occurs.

Additional information:
- Versions
  - Remote WSL v0.66.3 (latest)
  - Remote SSH v0.84.0 (latest)

**Comment by a4lg** [comment] 2022-08-07 08:51
*This is not just headings.*

Does this issue occur when all extensions are disabled?: When only "Remote - SSH" is enabled

Repository: https://github.com/a4lg/binutils-gdb.wiki.git (work tree `/src/private/github/binutils-wiki`)
Remote: SSH (Linux)
Host: Windows

Let me see... when I open `Patch-Queue.md` and Ctrl+Click `(./Patches-Processed)` on the line 1 to open `Patches-Processed.md`, it says the file is not found just like @mdj982 reported.  Changing the link part to `(./Patches-Processed.md)` didn't make much difference.

When I right click and copy the absolute path, the result was `\src\private\github\binutils-wiki\Patches-Processed.md` (yes, backslash instead of slash). Copying the relative path did the same.

Worst of all, if I "Create File" from the error screen and save it, the file is saved to the local machine's `C:\src\private\github\binutils-wiki\Patches-Processed.md`, not to the remote repository. Yes, the Markdown editor clearly handles the links as local links.

**Comment by 767829413** [comment] 2022-08-15 05:51
![image](https://user-images.githubusercontent.com/34152277/184583142-925cbf43-4c5a-4476-ba45-8e755a257684.png)
I am also using wsl2 + vscode development, we recommend using this version, very stable!

**Comment by a4lg** [comment] 2022-08-21 09:15
I turned on the developer tools and did see an error on 1.70.2 (not on 1.69.2):

```
  ERR Error: ファイルが見つかりません。(Japanese→English translation: a file is not found.)
    at g.handleSetInputError (workbench.desktop.main.js:2723:95761)
    at async g.setInput (workbench.desktop.main.js:2723:95001)
    at async o.doSetInput (workbench.desktop.main.js:2721:6429)
    at async o.doOpenEditor (workbench.desktop.main.js:2721:4791)
    at async openEditor (workbench.desktop.main.js:2721:3783)
    at async workbench.desktop.main.js:2928:16842
    at async C.doOpenCodeEditor (workbench.desktop.main.js:1358:58246)
    at async C.openCodeEditor (workbench.desktop.main.js:661:60078)
    at async S.open (workbench.desktop.main.js:602:47629)
    at async l.open (workbench.desktop.main.js:602:49092)
    at async workbench.desktop.main.js:2723:26091
```

I decided to add a breakpoint to `g.setInput` (`TextFileEditor.setInput`) and observe various `FileEditorInput` argument internals. I'm not an expert of VSCode internals so I could not dig down further but I can see there's something wrong.

# 1.69.2

## Open from VSCode's file explorer

```
bl {_store: d, _onDidChangeDirty: o, _onDidChangeLabel: o, _onDidChangeCapabilities: o, _onWillDispose: o, …}
cachedTextFileModelReference: undefined
disposed: false
editorService: O {_store: d, editorGroupService: Fi, instantiationService: m, fileService: h, configurationService: x, …}
fileService: h {_store: d, logService: A, BUFFER_SIZE: 262144, _onDidChangeFileSystemProviderRegistrations: o, onDidChangeFileSystemProviderRegistrations: ƒ, …}
filesConfigurationService: Oa {_store: d, configurationService: x, contextService: x, _onAutoSaveConfigurationChange: o, onAutoSaveConfigurationChange: ƒ, …}
forceOpenAs: 0
instantiationService: m {_activeInstantiations: Set(0), _services: t, _strict: true, _parent: undefined}
labelService: Proxy {onDidChangeFormatters: ƒ, registerFormatter: ƒ, getHostLabel: ƒ, getUriBasenameLabel: ƒ, getUriLabel: ƒ, …}
model: undefined
modelListeners: d {_toDispose: Set(0), _isDisposed: false}
onDidChangeCapabilities: (T,I,y)=> {…}
onDidChangeDirty: (T,I,y)=> {…}
onDidChangeLabel: (T,I,y)=> {…}
onWillDispose: (T,I,y)=> {…}
pathService: Proxy {userHome: ƒ}
resource: b
	authority: "ssh-remote+REMOTEMACHINE"
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "vscode-remote"
	_formatted: "vscode-remote://ssh-remote%2BREMOTEMACHINE/src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
textFileService: p {_store: d, fileService: h, untitledTextEditorService: Proxy, lifecycleService: Ts, instantiationService: m, …}
textModelResolverService: Proxy {registerTextModelContentProvider: ƒ, createModelReference: ƒ}
_longDescription: undefined
_longTitle: undefined
_mediumDescription: undefined
_mediumTitle: undefined
_name: "Patches-Processed.md"
_onDidChangeCapabilities: o {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeDirty: o {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeLabel: o {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onWillDispose: o {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_preferredResource: b
	authority: "ssh-remote+REMOTEMACHINE"
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "vscode-remote"
	_formatted: "vscode-remote://ssh-remote%2BREMOTEMACHINE/src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
_shortDescription: undefined
_shortTitle: undefined
_store: d {_toDispose: Set(9), _isDisposed: false}
capabilities: (...)
editorId: (...)
longDescription: (...)
longTitle: (...)
mediumDescription: (...)
mediumTitle: (...)
preferredResource: (...)
shortDescription: (...)
shortTitle: (...)
typeId: (...)
[[Prototype]]: u
```

## Clicked a Markdown link (reproduced as [above](https://github.com/microsoft/vscode/issues/157260#issuecomment-1207360774))

```
bl {_store: d, _onDidChangeDirty: o, _onDidChangeLabel: o, _onDidChangeCapabilities: o, _onWillDispose: o, …}
cachedTextFileModelReference: undefined
disposed: false
editorService: O {_store: d, editorGroupService: Fi, instantiationService: m, fileService: h, configurationService: x, …}
fileService: h {_store: d, logService: A, BUFFER_SIZE: 262144, _onDidChangeFileSystemProviderRegistrations: o, onDidChangeFileSystemProviderRegistrations: ƒ, …}
filesConfigurationService: Oa {_store: d, configurationService: x, contextService: x, _onAutoSaveConfigurationChange: o, onAutoSaveConfigurationChange: ƒ, …}
forceOpenAs: 0
instantiationService: m {_activeInstantiations: Set(0), _services: t, _strict: true, _parent: undefined}
labelService: Proxy {onDidChangeFormatters: ƒ, registerFormatter: ƒ, getHostLabel: ƒ, getUriBasenameLabel: ƒ, getUriLabel: ƒ, …}
model: undefined
modelListeners: d {_toDispose: Set(0), _isDisposed: false}
onDidChangeCapabilities: (T,I,y)=> {…}
onDidChangeDirty: (T,I,y)=> {…}
onDidChangeLabel: (T,I,y)=> {…}
onWillDispose: (T,I,y)=> {…}
pathService: Proxy {userHome: ƒ}
resource: b
authority: "ssh-remote+REMOTEMACHINE"
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "vscode-remote"
	_formatted: "vscode-remote://ssh-remote%2BREMOTEMACHINE/src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
textFileService: p {_store: d, fileService: h, untitledTextEditorService: Proxy, lifecycleService: Ts, instantiationService: m, …}
textModelResolverService: Proxy {registerTextModelContentProvider: ƒ, createModelReference: ƒ}
_longDescription: undefined
_longTitle: undefined
_mediumDescription: undefined
_mediumTitle: undefined
_name: "Patches-Processed.md"
_onDidChangeCapabilities: o {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeDirty: o {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeLabel: o {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onWillDispose: o {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_preferredResource: b
	authority: "ssh-remote+REMOTEMACHINE"
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "vscode-remote"
	_formatted: "vscode-remote://ssh-remote%2BREMOTEMACHINE/src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: null
	fsPath: (...)
	[[Prototype]]: u
_shortDescription: undefined
_shortTitle: undefined
_store: d {_toDispose: Set(9), _isDisposed: false}
capabilities: (...)
editorId: (...)
longDescription: (...)
longTitle: (...)
mediumDescription: (...)
mediumTitle: (...)
preferredResource: (...)
shortDescription: (...)
shortTitle: (...)
typeId: (...)
[[Prototype]]: u
```

# 1.70.2

## Open from VSCode's file explorer

```
kl {_store: d, _onDidChangeDirty: l, _onDidChangeLabel: l, _onDidChangeCapabilities: l, _onWillDispose: l, …}
cachedTextFileModelReference: undefined
disposed: false
editorService: O {_store: d, editorGroupService: Bi, instantiationService: p, fileService: h, configurationService: L, …}
fileService: h {_store: d, logService: R, BUFFER_SIZE: 262144, _onDidChangeFileSystemProviderRegistrations: l, onDidChangeFileSystemProviderRegistrations: ƒ, …}
filesConfigurationService: Ha {_store: d, configurationService: L, contextService: L, _onAutoSaveConfigurationChange: l, onAutoSaveConfigurationChange: ƒ, …}
forceOpenAs: 0
instantiationService: p {_activeInstantiations: Set(0), _services: t, _strict: true, _parent: undefined}
labelService: Proxy {onDidChangeFormatters: ƒ, registerFormatter: ƒ, getHostLabel: ƒ, getUriBasenameLabel: ƒ, getUriLabel: ƒ, …}
model: undefined
modelListeners: d {_toDispose: Set(0), _isDisposed: false}
onDidChangeCapabilities: (T,E,D)=> {…}
onDidChangeDirty: (T,E,D)=> {…}
onDidChangeLabel: (T,E,D)=> {…}
onWillDispose: (T,E,D)=> {…}
pathService: Proxy {userHome: ƒ, hasValidBasename: ƒ}
resource: S
	authority: "ssh-remote+REMOTEMACHINE"
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "vscode-remote"
	_formatted: "vscode-remote://ssh-remote%2BREMOTEMACHINE/src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
textFileService: v {_store: d, fileService: h, untitledTextEditorService: Proxy, lifecycleService: Ps, instantiationService: p, …}
textModelResolverService: Proxy {registerTextModelContentProvider: ƒ, createModelReference: ƒ}
_longDescription: undefined
_longTitle: undefined
_mediumDescription: undefined
_mediumTitle: undefined
_name: "Patches-Processed.md"
_onDidChangeCapabilities: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeDirty: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeLabel: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onWillDispose: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_preferredResource: S
	authority: "ssh-remote+REMOTEMACHINE"
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "vscode-remote"
	_formatted: "vscode-remote://ssh-remote%2BREMOTEMACHINE/src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
_shortDescription: undefined
_shortTitle: undefined
_store: d {_toDispose: Set(9), _isDisposed: false}
capabilities: (...)
editorId: (...)
longDescription: (...)
longTitle: (...)
mediumDescription: (...)
mediumTitle: (...)
preferredResource: (...)
shortDescription: (...)
shortTitle: (...)
typeId: (...)
[[Prototype]]: u
```

## Clicked a Markdown link (reproduced as [above](https://github.com/microsoft/vscode/issues/157260#issuecomment-1207360774))

```
kl {_store: d, _onDidChangeDirty: l, _onDidChangeLabel: l, _onDidChangeCapabilities: l, _onWillDispose: l, …}
cachedTextFileModelReference: undefined
disposed: false
editorService: O {_store: d, editorGroupService: Bi, instantiationService: p, fileService: h, configurationService: L, …}
fileService: h {_store: d, logService: R, BUFFER_SIZE: 262144, _onDidChangeFileSystemProviderRegistrations: l, onDidChangeFileSystemProviderRegistrations: ƒ, …}
filesConfigurationService: Ha {_store: d, configurationService: L, contextService: L, _onAutoSaveConfigurationChange: l, onAutoSaveConfigurationChange: ƒ, …}
forceOpenAs: 0
instantiationService: p {_activeInstantiations: Set(0), _services: t, _strict: true, _parent: undefined}
labelService: Proxy {onDidChangeFormatters: ƒ, registerFormatter: ƒ, getHostLabel: ƒ, getUriBasenameLabel: ƒ, getUriLabel: ƒ, …}
model: undefined
modelListeners: d {_toDispose: Set(0), _isDisposed: false}
onDidChangeCapabilities: (T,E,D)=> {…}
onDidChangeDirty: (T,E,D)=> {…}
onDidChangeLabel: (T,E,D)=> {…}
onWillDispose: (T,E,D)=> {…}
pathService: Proxy {userHome: ƒ, hasValidBasename: ƒ}
resource: S
	authority: ""
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "file"
	_formatted: "file:///src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
textFileService: v {_store: d, fileService: h, untitledTextEditorService: Proxy, lifecycleService: Ps, instantiationService: p, …}
textModelResolverService: Proxy {registerTextModelContentProvider: ƒ, createModelReference: ƒ}
_longDescription: undefined
_longTitle: undefined
_mediumDescription: undefined
_mediumTitle: undefined
_name: "Patches-Processed.md"
_onDidChangeCapabilities: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeDirty: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeLabel: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onWillDispose: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_preferredResource: S
	authority: ""
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "file"
	_formatted: "file:///src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
_shortDescription: undefined
_shortTitle: undefined
_store: d {_toDispose: Set(9), _isDisposed: false}
capabilities: (...)
editorId: (...)
longDescription: (...)
longTitle: (...)
mediumDescription: (...)
mediumTitle: (...)
preferredResource: (...)
shortDescription: (...)
shortTitle: (...)
typeId: (...)
[[Prototype]]: u
```

## Created a file from the error screen (reproduced as [above](https://github.com/microsoft/vscode/issues/157260#issuecomment-1207360774))

```
kl {_store: d, _onDidChangeDirty: l, _onDidChangeLabel: l, _onDidChangeCapabilities: l, _onWillDispose: l, …}
cachedTextFileModelReference: undefined
disposed: false
editorService: O {_store: d, editorGroupService: Bi, instantiationService: p, fileService: h, configurationService: L, …}
fileService: h {_store: d, logService: R, BUFFER_SIZE: 262144, _onDidChangeFileSystemProviderRegistrations: l, onDidChangeFileSystemProviderRegistrations: ƒ, …}
filesConfigurationService: Ha {_store: d, configurationService: L, contextService: L, _onAutoSaveConfigurationChange: l, onAutoSaveConfigurationChange: ƒ, …}
forceOpenAs: 0
instantiationService: p {_activeInstantiations: Set(0), _services: t, _strict: true, _parent: undefined}
labelService: Proxy {onDidChangeFormatters: ƒ, registerFormatter: ƒ, getHostLabel: ƒ, getUriBasenameLabel: ƒ, getUriLabel: ƒ, …}
model: undefined
modelListeners: d {_toDispose: Set(0), _isDisposed: false}
onDidChangeCapabilities: (T,E,D)=> {…}
onDidChangeDirty: (T,E,D)=> {…}
onDidChangeLabel: (T,E,D)=> {…}
onWillDispose: (T,E,D)=> {…}
pathService: Proxy {userHome: ƒ, hasValidBasename: ƒ}
preferredContents: undefined
resource: S
	authority: ""
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "file"
	_formatted: "file:///src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
textFileService: v {_store: d, fileService: h, untitledTextEditorService: Proxy, lifecycleService: Ps, instantiationService: p, …}
textModelResolverService: Proxy {registerTextModelContentProvider: ƒ, createModelReference: ƒ}
_longDescription: undefined
_longTitle: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
_mediumDescription: "\\src\\private\\github\\binutils-wiki"
_mediumTitle: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
_name: "Patches-Processed.md"
_onDidChangeCapabilities: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeDirty: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onDidChangeLabel: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_onWillDispose: l {_disposed: false, _options: undefined, _leakageMon: u, _perfMon: undefined, _deliveryQueue: undefined, …}
_preferredResource: S
	authority: ""
	fragment: ""
	path: "/src/private/github/binutils-wiki/Patches-Processed.md"
	query: ""
	scheme: "file"
	_formatted: "file:///src/private/github/binutils-wiki/Patches-Processed.md"
	_fsPath: "\\src\\private\\github\\binutils-wiki\\Patches-Processed.md"
	fsPath: (...)
	[[Prototype]]: u
_shortDescription: undefined
_shortTitle: "Patches-Processed.md"
_store: d {_toDispose: Set(9), _isDisposed: false}
capabilities: (...)
editorId: (...)
longDescription: (...)
longTitle: (...)
mediumDescription: (...)
mediumTitle: (...)
preferredResource: (...)
shortDescription: (...)
shortTitle: (...)
typeId: (...)
[[Prototype]]: u
```

# Analysis

I haven't tracked down further but clearly a `file` scheme URL is given when a `vscode-remote` scheme URL should be given. Someone's giving this wrong URL.

**Comment by a4lg** [comment] 2022-08-21 09:35
Related:
-   #157124
-   #157448

**Comment by normal-cock** [comment] 2022-08-29 00:59
I also encountered same kind of issue on my macbook.
* VS Code Version: 1.70.2
* OS Version: Macbook 11.6.8

**Comment by normal-cock** [comment] 2022-09-01 12:36
Do we have any idea when this bug would be fixed?

**Comment by mdj982** [comment] 2022-09-05 07:57
One month has passed. I hope this issue will be fixed in 1.70.x. Thanks for lots of reports.

**Comment by 767829413** [comment] 2022-09-08 09:59
The latest version has not solved this problem, very uncomfortable!
August 2022 (version 1.71)

**Comment by Hocnonsense** [comment] 2022-09-10 02:51
It seems related to
- https://github.com/microsoft/vscode/issues/159083

**Comment by normal-cock** [comment] 2022-09-17 12:32
The latest version 1.71.2 still have this problem

**Comment by a4lg** [comment] 2022-09-17 16:19
On the other hand, this issue seems to be fixed in the latest Visual Studio Code - Insiders (version 1.72.0).

**Comment by mjbvz** [comment] 2022-09-19 19:55
Possibly fixed by https://github.com/microsoft/vscode-markdown-languageservice/pull/42

If you are still seeing using VS Code using the insiders build (1.72), please share your OS and steps to reproduce the problem

**Closed by mjbvz** 2022-09-19 19:55 UTC
Labels: bug, help wanted, markdown

**Comment by jiangying000** [comment] 2022-09-23 08:41
> Possibly fixed by [microsoft/vscode-markdown-languageservice#42](https://github.com/microsoft/vscode-markdown-languageservice/pull/42)
> 
> If you are still seeing using VS Code using the insiders build (1.72), please share your OS and steps to reproduce the problem

when will 1.72 be released?
