### ISSUE TITLE
Set file extension of JSON configuration files to `.jsonc`

### ISSUE THREAD

**Issue by lindhe** [microsoft/vscode#189385] opened 2023-08-01 06:46 UTC
The configuration files under `.vscode` have the file extension `.json` although they are really `.jsonc`. This causes many editors and file viewers to use incorrect syntax highlighting for them. See this example:

https://github.com/home-assistant/core/blob/f0640fc057ff8f200eb35dd6c57388432e2c33ed/.vscode/settings.default.json

![Screenshot from 2023-08-01 08-43-40](https://github.com/microsoft/vscode/assets/7773090/c8cd7c6d-eeb3-42cc-b84b-1d309691ec0d)

I suggest that the default files provided are renamed to have the `.jsonc` file name extension.

If vscode already supports reading config from `.jsonc` files, this ought to be a smooth change. If not, that's obviously critical to get in place first.

**Comment by ArturoDent** [comment] 2023-08-03 21:41
How was `settings.default.json` created?

**Comment by lindhe** [comment] 2023-08-04 05:27
In the specific example I linked to, I don't know. But I do know that I have a `.vscode/` directory in my home directory  with similar files in it. And those files were automatically created by vscode at some point.

**Comment by rzhao271** [comment] 2023-08-11 17:36
I discussed this issue with the team and I'm marking it as out of scope due to the risk of potential regressions.
At this time, users interested in getting the rendering to work can try manually renaming the file in their own repo.

**Closed by rzhao271** 2023-08-11 17:36 UTC
