### ISSUE TITLE
[Question] package --pre-release vs versions.

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode#174945] opened 2023-02-01 18:00 UTC
I read the docs here [Prerelease Extensions](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions). I noted the recommendation of odd and even versions for pre-release and release extensions...
This is not an ideal versioning scenario in my case.
What if I publish pre-release 1.45 and then publish release 1.45? What happens in this case with respect to users working with pre-release 1.45 once 1.45 release comes out? Will they be automatically upgraded to 1.45 release? If someone choses to install pre-release of an extension does it mean that the user would always prefer pre-release to a release until version of the release is higher than the pre-release?

**Comment by isidorn** [comment] 2023-02-21 16:04
Duplicate of https://github.com/microsoft/vscode-discussions/discussions/2
Odd / even recommendation will be removed once semver is supported https://github.com/microsoft/vsmarketplace/issues/50

Closing as duplicate of those

**Closed by isidorn** 2023-02-21 16:04 UTC
