### ISSUE TITLE
Git tab doesn't handle multiple workspaces with the same git submodules

### ISSUE THREAD

**Issue by rcsmith00** [microsoft/vscode#75443] opened 2019-06-13 18:23 UTC
Issue Type: <b>Bug</b>

Have 2 instances of vs code running
workspace A has git structure     A root repo, with x, y, and z submodules.  Workspace B has git structure that has B root repo and x,y, and z submodules that are named the same as workspace A.  Under source Control providers, It lists A, x, y, z, B, x, y, z.            Except it is not clear which x, y, and z repo's belong to which root repo.  There is no path information to determine which one to close.    Seems it would be better if a vs code instance only opened the git repos in it's project tree.  Is there a configuration setting that I am missing?

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

**Comment by rcsmith00** [comment] 2019-06-13 19:20
similar but it doesn't cover running multiple instances of vs code

**Comment by joaomoreno** [comment] 2019-06-19 09:36
> Under source Control providers, It lists A, x, y, z, B, x, y, z.

Which window shows that? Both?

**Comment by rcsmith00** [comment] 2019-06-19 15:59
Yes,   To work around the issue, I closed both workspaces, and then had to reopen one of them.

**Comment by joaomoreno** [comment] 2019-06-20 08:11
Can you show me screenshots of both windows?

**Comment by Awbmilne** [comment] 2020-07-17 14:06
This is a duplicate of issue #101859: PLEASE UPVOTE IT THERE!

**Comment by joaomoreno** [comment] 2020-09-30 12:43
Actually closing this as designed. The workspace/folder name should appear in the windows title, that should help. Apart from that, hovering over the repository names should show you their full path.

**Closed by joaomoreno** 2020-09-30 12:43 UTC
