### ISSUE TITLE
Disabling or removing the "new file editor" choice menu, e.g. removing the "Jupyter Notebook (preview)" option

### ISSUE THREAD

**Issue by bbugh** [microsoft/vscode#103574] opened 2020-07-29 17:38 UTC
Hi! 👋

It looks like VSCode is adding some Jupyter features, which is probably great for people who care, but I don't think the current New File behavior should be the default for everyone who uses VSCode. 

Every time I select "New File" from the menu now, I get a popup menu asking me if I want a Jupyter Notebook new file or a regular text file. I don't and won't ever need to create a new file for a Jupyter Notebook in VSCode, and I want to disable this choice so I can keep the previous behavior of just making a new file and letting me write stuff. This new behavior seems to be core to VSCode for some reason and I cannot find a way to remove or disable it. None of the menu options I tried remove this behavior. 

Preferable behavior would be that this is not enabled by default, or there's some way to tell VSCode "disable everything that has to Jupyter", or there's a way to restore the original New File behavior so it just creates a new editor without a useless (to me) choice.

Thank you for considering this feature request!

**Comment by bbugh** [comment] 2020-07-29 20:04
I discovered that this is part of the Python extension package, which I removed. However, the "Text Editor - Built In" still appears even though there is only one option. 

I think it would be better if this did not appear when there is only one option.

**Comment by gjsjohnmurray** [comment] 2020-07-29 23:29
> However, the "Text Editor - Built In" still appears even though there is only one option. I think it would be better if this did not appear when there is only one option.

This is a duplicate of #102289 and is fixed in Insiders. AFAIK it only happens when you use the "New File" link from the Welcome page. Workaround is to use the option from the File menu.

**Comment by bbugh** [comment] 2020-07-30 09:26
Thank you for the information! I'm not sure what the Welcome page is though, the issue I am reporting happens from the File menu -> New File, or the shortcut key.

**Closed** 2020-07-30 09:27 UTC
