### ISSUE TITLE
Updated to latest, installed extensions are gone and cannot reinstall

### ISSUE THREAD

**Issue by mwenning** [Microsoft/vscode#8960] opened 2016-07-08 15:54 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.2.0-41-generic

Steps to Reproduce:
Using under Ubuntu Linux 15.10, 

1. Quit Visual Studio Code 1.2  
2. run .deb file to update from 1.2 to 1.3 
3. Click More -> Show Installed Extensions , no extensions show up
4. Hit ctl-P, type 'ext install python' (for example)
5. Python shows up in Extensions sidebar.  Click on Install.
6.  Nothing happens, nothing is installed.

**Comment by thiagolucio** [comment] 2016-07-08 16:43
Same with me...
Ubuntu Gnome 16

**Comment by mwenning** [comment] 2016-07-08 16:55
Looks like they've renamed the dpkg also, to roll back, do 
sudo apt-get remove code 

the old 1.2.1 package is named "visual-studio-code", 
imho they should stick with "visual-studio-code"

**Comment by fpahl** [comment] 2016-07-08 17:03
I have the same issue with Ubuntu 16.04. Removing the old package and reinstall did not resolve the issue.

**Comment by fpahl** [comment] 2016-07-08 17:07
It worked after a reboot of the OS.

**Comment by mwenning** [comment] 2016-07-08 18:19
fpahl, you're right it does.  Thanks. 
so upgrade procedure is:
1. Remove the old one with 'sudo apt-get remove visual-studio-code'
2. Install new one (1.3.0)
3. Reboot.
4. Remember that the 1.3.0 version is called 'code' instead of 'visual-studio-code'

**Comment by Tyriar** [comment] 2016-07-08 19:10
This is a duplicate of https://github.com/Microsoft/vscode/issues/8859#issuecomment-231410408, see there for root cause and steps to fix.

**Closed by Tyriar** 2016-07-08 19:10 UTC
