### ISSUE TITLE
JS Syntax

### ISSUE THREAD

**Issue by jtibrewal09** [Microsoft/vscode#56971] opened 2018-08-22 06:55 UTC
Issue Type: <b>Bug</b>

In new update the synta highlighting of JavaScript shows red color for some partial codes which is very confusing.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.14
python|ms-|2018.7.1
gitblame|wad|2.4.4

</details>

**Comment by mjbvz** [comment] 2018-08-22 08:15
Please share the text of the code that produces this error

**Comment by mjbvz** [comment] 2018-08-24 08:12
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/648

Fixed in insiders

**Closed by mjbvz** 2018-08-24 08:12 UTC
Labels: grammar, needs more info
