### ISSUE TITLE
Scroll is changed when user is switching pages

### ISSUE THREAD

**Issue by Cliwo** [Microsoft/vscode#28486] opened 2017-06-12 05:02 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|unity-debug|Unity|1.2.0|
|unity-snippets|YclepticStudios|0.1.2|
|csharp|ms-vscode|1.10.0|;

---

Steps to Reproduce:

1. Make two pages (open two codes like A.cs , B.cs)
2. Switch each pages (A.cs to B.cs / B.cs to A.cs)
3. The Scroll is not in the former position.

this problem makes me dizzy.

**Comment by bpasero** [comment] 2017-06-13 09:42
@Cliwo can you share a screencast of what you are doing and what you are seeing?

**Comment by Cliwo** [comment] 2017-06-15 03:12
Here is a video
https://drive.google.com/file/d/0BxKikrXbjhfsckNzZFozUWsxWkE/view?usp=sharing

if you cannot see the video, please let me know
and please ignore code and watch scroll position

**Comment by Cliwo** [comment] 2017-06-15 03:21
I think Search Bar amplifys the effect. (making scroll bar go down)

**Comment by bpasero** [comment] 2017-06-15 04:04
This seems to be CodeLens related.

**Comment by alexandrudima** [comment] 2017-06-15 06:13
Today, our strategy is to preserve the centered line in the viewport when code lens are added. Perhaps we can change the strategy to preserve the top line in the viewport.

**Comment by ypapouin** [comment] 2017-07-12 12:19
> This seems to be CodeLens related.

Indeed, same issue here with C# code and Code 1.14, after I set editor.codeLens to false the issue disappear.

>I think Search Bar (cmd + f) amplifys the effect. (making scroll bar go down)

Indeed to with Code 1.14, it massively change the scroll bar position

**Comment by Cliwo** [comment] 2017-08-08 09:36
This problem still occurs
Jesus

**Comment by yakirn** [comment] 2017-08-10 09:13
I can confirm this also happens in typescript.

**Comment by alexandrudima** [comment] 2018-04-17 21:42
Fixed via #41968

**Closed by alexandrudima** 2018-04-17 21:42 UTC
Labels: bug
