### ISSUE TITLE
Getting started - empty list

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#119617] opened 2021-03-23 14:44 UTC
Testing #119543

If there are not items in the "Getting Started" section we should either provide a "congratulations" message, or remove the section altogether as it currently looks weird when it is empty (see screenshot). 

![image](https://user-images.githubusercontent.com/3372902/112164980-a1534b80-8bee-11eb-9cc4-d0641b599c23.png)

**Comment by JacksonKearl** [comment] 2021-03-23 19:35
Thanks, duplicate of #119496

**Closed by JacksonKearl** 2021-03-23 19:35 UTC
