### ISSUE TITLE
Maximized VS Code is larger than my monitor

### ISSUE THREAD

**Issue by manospasj** [microsoft/vscode#85595] opened 2019-11-26 11:42 UTC
Issue Type: <b>Bug</b>

My PC has a two monitor setup, where each monitor has different resolution and scale settings. VS Code works fine in the primary monitor although when I move it to the second monitor and maximize it, it expands beyond the monitor dimensions. Please see screenshot.

This only happens with window.titleBarStyle set to default. If I set it to native, the issue is gone.
Also, this was working fine before the last update.

![image](https://user-images.githubusercontent.com/5380042/69626932-8942da80-1041-11ea-8556-d453e6faf5aa.png)

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (9.57GB free)|
|Process Argv|C:\Users\manos.pasgiannis\Desktop\AWS Organizations.md|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.24
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
prettier-vscode|esb|3.9.0
dotenv|mik|1.0.1
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
vscode-yaml|red|0.6.1

</details>

**Comment by IllusionMH** [comment] 2019-11-26 11:57
/duplicate of #85595 (event if that one says Full screen, both cases window looks maximized)

Could you please add more details about your setup (resolutions, zoom levels etc.) to that issue.

**Closed** 2019-11-26 11:57 UTC
Labels: *duplicate, new release

**Comment by manospasj** [comment] 2019-11-26 12:44
@IllusionMH How can an issue be duplicate of itself?
My primary monitor has a resolution of 3200x1800px and a zoom level of 250%. VS Code works fine in this one. The issue is visible only in my second monitor where the resolution is 1920x1080px with a zoom level of 100%.

**Comment by IllusionMH** [comment] 2019-11-26 12:45
@manospasj sorry, wrong copy-paste of issue number.

Issue that I wanted to reference is #85592
