### ISSUE TITLE
"Reveal In Side Bar" does not work if the file is opened from external apps

### ISSUE THREAD

**Issue by saschanaz** [microsoft/vscode#110188] opened 2020-11-08 20:44 UTC
- VSCode Version: 1.51.0
- OS Version: Windows 10 19042

Steps to Reproduce:

1. Open a folder
2. Open a file inside the folder, via File Explorer or via GitHub Desktop
3. See the "Open editors" list shows a full path instead of a relative path
4. Try "Reveal In Side Bar"

![image](https://user-images.githubusercontent.com/3396686/98483741-312dc580-220b-11eb-822a-ed0c7b693521.png)

Does this issue occur when all extensions are disabled?: Yes

I think this is a regression in 1.51.

**Comment by isidorn** [comment] 2020-11-09 10:39
I can reproduce this only on Windows. On macOS things seems to work just fine.
The issue seems to be that this check [here](https://github.com/microsoft/vscode/blob/59a1893d6d66171437f3608d2e938efa616f421e/src/vs/workbench/contrib/files/browser/fileCommands.ts#L336) fails.
So the `contextService.isInsideWorkspace` wrongly returns `false` here.

I believe the issue is with the uri when it comes into VS Code via the Open With command, it has the following structure. Notice the leading upper case `C`. And I believe all URI internally have the lower case driver letter.

So the gist is: "Open With" command should normalize drive letters when feeding uri's into VS Code.

Also assigning to @bpasero and @sandy081 for ideas

![Screenshot 2020-11-09 at 11 36 05](https://user-images.githubusercontent.com/1926584/98530863-c8346500-227f-11eb-8c9a-7710e975cd81.png)

**Comment by bpasero** [comment] 2020-11-09 10:45
Could this be https://github.com/microsoft/vscode/commit/b228267d50d474de56cb56c19d151bd8f61b59f0 too, see https://github.com/microsoft/vscode/issues/108535 @jrieken

**Comment by jrieken** [comment] 2020-11-09 11:03
Yeah - likely because the uri search tree is not doing implicit normalisations anymore. I'd say the workspace service or workspace-object should make sure to use a canonical uri before looking something up. Not sure this is a candidate tho.

**Comment by jrieken** [comment] 2020-11-09 11:07
The smallest fix is to create the search tree with the `ignorePathCasing` option here: https://github.com/microsoft/vscode/blob/960205b8a06e3fdc283b9a476952620041cba84a/src/vs/platform/workspace/common/workspace.ts#L147

**Comment by isidorn** [comment] 2020-11-09 11:56
I am perfectly fine with not doing this is a candidate. Just added label for awarness.

**Comment by isidorn** [comment] 2020-11-10 08:52
For users coming to this issue to find more details: we will ship a fix for this issue in vscode stable this or next week.
If you are interested in how we fixed it you can checkout this PR https://github.com/microsoft/vscode/pull/110247

**Comment by jrieken** [comment] 2020-11-10 09:48
merged my PR and cherry-picked the change to master. Also, driving the adoption of the better way of doing this: https://github.com/microsoft/vscode/issues/110241

**Closed by jrieken** 2020-11-10 09:48 UTC
Labels: bug, candidate, new release, regression, uri
