### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by TGod-Ajayi** [microsoft/vscode#106602] opened 2020-09-13 21:03 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200911

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13424:55)
    at getTextOfNode (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13449:16)
    at Object.declarationNameToString (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13761:66)
    at getDisplayName (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39745:53)
    at declareSymbol (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39859:111)
    at bindExportsPropertyAssignment (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41969:17)
    at bindWorker (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41665:29)
    at bind (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41554:13)
    at bindExpressionStatement (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40619:13)
    at bindChildren (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40104:21)
    at bind (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41565:21)
    at /Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40045:94
    at Object.forEach (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40052:16)
    at bindEachFunctionsFirst (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40045:13)
    at bindChildren (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40144:21)
    at bindContainer (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40002:17)
    at bind (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41568:21)
    at bindSourceFile (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39611:17)
    at Object.bindSourceFile (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39550:9)
    at initializeTypeChecker (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:77500:20)
    at Object.createTypeChecker (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:43597:9)
    at Object.getTypeChecker (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:104583:79)
    at synchronizeHostData (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:144689:21)
    at Object.getProgram (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:144771:13)
    at AutoImportProviderProject.Project.updateGraphWorker (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149616:53)
    at AutoImportProviderProject.Project.updateGraph (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149549:42)
    at AutoImportProviderProject.updateGraph (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:150361:53)
    at Object.updateProjectIfDirty (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:150972:45)
    at InferredProject.Project.getPackageJsonAutoImportProvider (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:150162:32)
    at InferredProject.Project.updateGraph (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149586:26)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:151631:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153151:26)
    at /Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153408:97
    at Object.flatMap (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153408:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:154427:46)
    at /Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156300:88
    at IOSession.Session.executeWithRequestId (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156291:28)
    at IOSession.Session.executeCommand (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156300:33)
    at IOSession.Session.onMessage (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156324:35)
    at Interface.<anonymous> (/Users/dev/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:158540:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|141, 64, 29|
|Memory (System)|8.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id 03dafd07-5f86-4162-b65c-2266745e2cdb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
vscode-sequence-diagrams|Ale|0.4.0
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1001.0
vscode-apollo|apo|1.16.8
vscode-custom-css|be5|3.0.10
simple-react-snippets|bur|1.2.3
vscode-standardjs-snippets|cap|0.8.15
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.3.0
angular2-snippets|dan|1.0.21
vscode-simpler-icons|dav|1.6.5
angular-extension-pack|dog|9.0.0
githistory|don|0.6.9
es7-react-js-snippets|dsz|3.0.0
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
eppz-code|epp|1.2.52
react-native-react-redux|EQu|2.0.4
mithril-emmet|Fal|0.7.6
auto-rename-tag|for|0.1.4
beautify|Hoo|1.5.0
rest-client|hum|0.24.2
angular2-switcher|inf|0.3.3
csharpextensions|jch|1.3.1
docthis|joe|0.7.1
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.8.0
vscode-csharp-snippets|jor|0.3.1
react-native-snippet|jun|0.5.6
refactorix|kri|0.3.6
csharpfixformat|Leo|0.0.84
react-apollo-snippets|lev|0.0.3
csharp-colors|log|0.1.8
sequelize-vscode-association-snippet|lou|0.0.2
json-to-ts|Mar|1.7.5
vscode-language-babel|mgm|0.0.29
code-beautifier|mic|2.3.3
Angular-BeastCode|Mik|10.0.3
csharp|ms-|1.23.2
mssql|ms-|1.9.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|4.1.20200911
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.10
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|0.17.0
sqltools|mtx|0.23.0
gremlins|nho|0.23.1
angular-console|nrw|13.0.0
material-icon-theme|PKi|4.3.0
vscode-css-peek|pra|4.0.0
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
js-jsx-snippets|sky|10.1.0
autoimport|ste|1.5.3
move-ts|str|1.12.0
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.7
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-09-13 23:46
Please fill in the template to the best of your ability

Also does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2020-09-14 18:18
Duplicate of https://github.com/microsoft/TypeScript/issues/40513

**Closed by mjbvz** 2020-09-14 18:18 UTC
Labels: needs more info, new release
