### ISSUE TITLE
snippets json not using "JSON with comments" language mode

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39628] opened 2017-12-05 09:41 UTC
testing #39588

`F1`
Open user snippets
Pick `JavaScript`
`javascript.json` opens

result: language mode is `JSON`, 
expected: language mode is `JSON with Comments`

![image](https://user-images.githubusercontent.com/1487073/33600124-a2e454b8-d9a8-11e7-974e-504798381bb1.png)

Same happens for any/all of the other language snippet files (e.g. `css.json`, `csharp.json`, etc.)

**Comment by aeschli** [comment] 2017-12-05 12:16
duplicate of #39642

**Closed by aeschli** 2017-12-05 12:16 UTC
Labels: json
