### ISSUE TITLE
Suggest to enable auto-stash, if disabled, when pulling when the working tree is dirty

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#215438] opened 2024-06-13 13:03 UTC
Currently we only show an error to the user, we should use the opportunity to say "would you like to enable auto stash?" with options "No", "Enable auto stash and continue", "Cancel".

**Comment by lszomoru** [comment] 2024-12-10 15:13
Closing as duplicate of [#186431](https://github.com/microsoft/vscode/issues/186431)

**Closed by lszomoru** 2024-12-10 15:13 UTC
Labels: feature-request, git
