### ISSUE TITLE
[Feature Request]: Expose IQuickOpenService as public api

### ISSUE THREAD

**Issue by balajikris** [Microsoft/vscode#22334] opened 2017-03-09 22:52 UTC
- VSCode Version: 1.10.0
- OS Version: win10

Steps to Reproduce:

I'm trying to build an extension that presents a list of npm-packages in the command palette. As the user scrolls down the list, I would like to show a preview-html of the package's README in a virtual document (see screenshot). The existing `InputOptions` do not help me in accomplishing this. For now, I'm using `showQuickPick` but I don't think it exposes a callback for the event of user moving down the list.

This experience would be similar to how vscode accomplishes previewing a color theme when the user is browsing through the different available themes from the command palette. [This code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/themes/electron-browser/themes.contribution.ts#L80) is what I think I need, but it is not part of the public api.

// Thanks to @hoovercj for helping me navigate through the source.

screenshot:
![image](https://cloud.githubusercontent.com/assets/4213867/23774373/373c2704-04d8-11e7-9b69-0c1003cbc2f0.png)

**Comment by hoovercj** [comment] 2017-03-09 23:06
I would also like to take advantage of this api.

I have an extension for a language called `octo` and I bundle documentation and sample code with it. As the OP does, I use quick picks to expose those and it would be hugely beneficial if I could simultaneously show the content of docs or sample code in an editor as the user cycles through the options.

**Comment by jrieken** [comment] 2017-03-10 08:00
closing this as dupe of https://github.com/Microsoft/vscode/issues?q=is%3Aopen+label%3Aapi+label%3Aquick-pick+label%3Afeature-request

**Closed by jrieken** 2017-03-10 08:00 UTC
Labels: api

**Comment by hoovercj** [comment] 2017-03-11 17:49
@balajikris you and I both missed something obvious. oops!

[QuickPickOptions](https://code.visualstudio.com/docs/extensionAPI/vscode-api#QuickPickOptions) takes an `onDidSelectItem` callback that does what we both need.

I connected it with a `TextDocumentContentProvider` in a sample extension [here](https://github.com/hoovercj/vscode-api-playground/tree/master/QuickPickDocumentPreview) which I'll be folding into my real extensions after [this fix](https://github.com/Microsoft/vscode/issues/21413) comes out with the next release.

I hope that helps!

**Comment by balajikris** [comment] 2017-03-13 07:02
ah! I see. I noticed that event but got confused as to what selection meant - cycling through with arrow keys or commiting one by hitting Enter. Thanks for looking into this -- your api-playground idea is awesome, I'll take a peek. Thanks much!
