### ISSUE TITLE
git autorefresh is not working.

### ISSUE THREAD

**Issue by simon-r** [Microsoft/vscode#42821] opened 2018-02-02 13:17 UTC
- VSCode Version: 1.19.3
- OS Version: Linux (ARCH)

I've enabled 
```
  "git.autorefresh": true,
```
But the auto-refresh don't work, and I've to push the refresh button to see the edited files. 

I've also observed that if I edit a file with an external editor or I change the branch in the git project the files in the editor are not updated.
And, also, in the git toolbar if I discard an edit in the editor the file is not updated.

Steps to Reproduce (in my installation):

1. Open a project or folder: edit and save a file.
2. In the git toolbar the updated files are not notified until I click the refresh button.

.... After the manual refresh I can commit and stage normally.

> 
> Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment] 2018-02-02 15:41
Do file events work otherwise? If you open a file and modify it on the outside, does VS Code react to it? If you add new files to your folder, does VS Code show them in the explorer?

**Comment by simon-r** [comment] 2018-02-04 19:27
No.
If I modify or add a file outside vscode it does not work.

And also with the explorer I've a similar problem.

**Comment by jensrossbach** [comment] 2018-02-05 16:40
I observed similar behaviour since version 1.19.3. For me it's rarely working correctly, but most of the time, the auto refresh is not working.

**Comment by simon-r** [comment] 2018-02-08 15:35
I confirm the problem also with VSCODE 1.20

It has worked 1 time, and now it don't works.

**Comment by barbossa** [comment] 2018-02-11 21:00
vs code 1.20.0 running on ubuntu. auto refresh issue still present.

**Comment by craigktreasure** [comment] 2018-02-14 16:29
I thought it was just me. I'm seeing the same since around VSCode 1.19. I'm on Windows 10 1709.

**Comment by simon-r** [comment] 2018-02-19 08:29
I confirm the problem with 
vscode 1.20.1

**Comment by MrChriZ** [comment] 2018-02-19 12:42
With vscode 1.20.1/Linux Mint 18.3 after generating new files externally using Ember I'm not seeing new files appear in the tree until I press the refresh button.

**Comment by kramvan1** [comment] 2018-03-02 16:14
1.20.1 on mac, Directory window is not auto refreshing, need to hit the refresh button after each git branch or file change.

**Comment by kramvan1** [comment] 2018-03-02 16:15
Why is this tagged as NEED MORE INFO, it's a very basic use case as stated above.  What else do you need?

**Comment by Ziflin** [comment] 2018-03-02 16:19
I'd definitely like to hear any suggestions for fixing the Git auto-refresh issue. I've uninstalled VS Code completely and reinstalled it and am still having this issue which is annoying enough to make me switch to a new editor.

**Comment by simon-r** [comment] 2018-03-06 09:29
I've observed that sometime, randomly, the problem disappear.
But at the moment the bug is there (and very annoying).

**Comment by Ziflin** [comment] 2018-03-08 13:46
I was finally able to fix whatever the issue was preventing Git AutoRefresh from working by renaming my `C:\Users\XXX\AppData\Roaming\Code` folder and restarting VS Code. This seemed to fix it, so I copied my `keybindings.json` and `settings.json` files over and it still worked, so I'm still not sure how that fixed it, but it appears to be working correctly again.

**Comment by barbossa** [comment] 2018-03-08 16:05
Guys, it can be related to https://code.visualstudio.com/docs/setup/linux#_error-enospc
check this params on your pc

**Comment by simon-r** [comment] 2018-03-13 09:52
@barbossa 
It seems that your hack has fixed the problem (at least for me).

**Comment by AshokBaruaAkas** [comment] 2018-03-22 06:08
Need Help: I have the problem with the latest version of vs code. 
Its count the total push req.
but Pull request not count..

**Comment by c7hm4r** [comment] 2018-04-28 21:14
I tried to disable all extensions, increased `fs.inotify.max_user_watches` to 524288 and removed `~/.config/Code/{*Cache*,Cookies*,Local Storage,User/workspaceStorage}` with no success.

It does not work on one repository where:

- the authentication to the default remote (git upstream) is via an SSH key file and
- the SSH key is (differently from other keys on my machine) not managed by an key manager (in my case, because the key file does not reside in ~/.ssh/ and is instead configured via ~/.ssh/config) so that the file needs to be unlocked on every git remote command like `fetch` and
- in the VS Code configuration: `"git.autofetch": true`.

When I set a different git remote whose key file is managed by gnome-keyring (Fedora) and reload VS Code, it works. Could it be possible that VS Code disables file watching when `git fetch` fails?

**Comment by cancerberoSgx** [comment] 2018-06-22 04:51
[solved] same here. arch linux. Big repository and stop working no matter how I increment the limit.  fs.inotify.max_user_watches . Opened Developer tools and see some errors related to node_modules files. So I remove them a recursively . vscode went crazy, couldn't kill the process and had to wait 3 minutes until the SO ended rebooting (I suspect vscode) after rebooting all went fine. Just in case, recursively removing all those files can be done like this: 

```find . -name "node_modules" -exec rm -rf '{}' +; find . -name "package-lock.json" -exec rm -rf '{}' +; ```

**Comment by tobihagemann** [comment] 2018-06-23 12:44
I don't know if the issue describe by OP is the same as the one by @SLMaxwell but I can absolutely confirm what he described.

It's easily reproducible:

1. Use any project that is using `git` for version control (and has a `.git` folder inside).
2. Open any **subdirectory** of this project in VS Code.
3. Make some changes in the project.
4. Commit and push these changes externally.

I would expect VS Code to automatically refresh its git status and know that the changes have been committed/pushed. Instead, VS Code doesn't automatically refresh its git status and you have to do it manually.

Step 2 is crucial. If you open the root directory of the project instead, it works as expected.

**Comment by danielrob** [comment] 2018-06-26 09:45
I'm on OSX 10.11.6. I've had this for a few weeks. I switched to insiders. On first boot it worked. After getting setup it stopped working. I disabled all extensions, it still doesn't work. 

```
 1. $ cd  /project
 2. $ code-insiders .
 3. $ git rev-parse --show-toplevel //  /project
 4. make an edit to a file
```
Expected: git status is refreshed in the git sidebar. 
Actual: nothin'.

**Comment by romellem** [comment] 2018-07-26 18:49
@tobihagemann great find. I was running into the same issue, and I was able to reproduce the issue easily by making sure to open VS Code from within a sub directory within my git repo.

**Comment by danielrob** [comment] 2018-07-26 20:58
FYI, this seems to have improved for me.

**Comment by tobihagemann** [comment] 2018-07-26 22:22
Unchanged here using latest version of VS Code. Just committed something 15 mins ago and VS Code never auto-refreshed its git status.

**Comment by mellena1** [comment] 2018-08-01 23:33
I am seeing this with the most recent version of VSCode as well (on macOS High Sierra).

**Comment by bpasero** [comment] 2018-09-22 06:39
Anyone seeing this issue, do you still see it? If so, can you run `code --verbose` and make a change to a file and report back if you see file events showing up?

**Comment by tobihagemann** [comment] 2018-09-22 08:55
Yes, still seeing the issue. I've described how to reproduce it here: https://github.com/Microsoft/vscode/issues/42821#issuecomment-399675310

When opening the project from a subdirectory, I don't see _any_ file watcher events. The log stays empty while performing the git commands outside of VS Code.

When opening the project from the root directory (where the `.git` folder is located), I see file watcher events and everything is fine. It looks like this:

```
[3624:0922/104628.406461:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[ADDED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104628.459934:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104628.507096:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104628.507341:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[DELETED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104628.560409:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104628.560470:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104632.737985:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104632.790019:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.080803:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.080931:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.081193:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.081356:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.081924:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.131730:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.131797:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.131835:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.131867:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.131899:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.365940:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.418318:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.514300:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
[3624:0922/104639.569767:INFO:CONSOLE(276)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (276)
```

**Comment by bpasero** [comment] 2018-09-22 12:00
@tobihagemann ok that is explainable, we do not support git unless the root folder of the .git is opened. Please open the root folder and it will work.

**Comment by bpasero** [comment] 2018-09-22 14:01
@tobihagemann that is fine as separate feature request, but the statement "git autorefresh is not working" can be explained by how you are not opening the root folder. I am still trying to understand if there is an actual bug here or just behaviour we did not implement.

**Comment by keipher** [comment] 2018-09-25 21:20
Bug or "not implemented" both lead to the fact that I must always open the root folder to get auto-refresh capability for git. There is little reason for the root folder requirement in my opinion and this requirement can actually promote errors since VSCode can specify an incorrect branch; it would be better to show no branch at all!! Atom, for example, will refresh the GIT branch from the root or a subfolder and I find that to be the most beneficial behavior.

**Comment by tim0991** [comment] 2018-10-17 03:37
Still in `osx 10.11.2 `  `vscode 1.28`

1.27 works fine

**Comment by fcastilloec** [comment] 2018-10-26 20:38
@bpasero I can report that this bug is still happening with `v1.28.2`. When running `code --verbose` and changing something on the git repository, I can see the File Watcher detecting the changes, but the GUI is not refreshing at all. I have to manually do it.
I always open my project from the root directory, so I don't have any problems with subfolders. As you can see in the output below, I just run a simple `npm update` on the root in order to have an updated `package.json` and `package-lock.json`. vscode seems to see all the changes, but again, the GUI is never refreshed. This means there's no badge under the source countrol icon, and when on the sidebar, there's no files shown with any changes, even though the were changes!

```
[2411:1026/132946.296309:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c[ADDED] /home/felipe/workspace/headset/package.json.2095173220", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.330236:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED] /home/felipe/workspace/headset/package.json", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.379751:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized  [ADDED] /home/felipe/workspace/headset/package.json.2095173220", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.379775:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized  [CHANGED] /home/felipe/workspace/headset/package.json", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.428911:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c[DELETED] /home/felipe/workspace/headset/package.json.2095173220", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.479770:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized  [DELETED] /home/felipe/workspace/headset/package.json.2095173220", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.484297:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c[ADDED] /home/felipe/workspace/headset/package-lock.json.3451669346", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.487101:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED] /home/felipe/workspace/headset/package-lock.json.3451669346", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.487163:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c[CHANGED] /home/felipe/workspace/headset/package-lock.json", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.537149:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized  [ADDED] /home/felipe/workspace/headset/package-lock.json.3451669346", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.537172:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized  [CHANGED] /home/felipe/workspace/headset/package-lock.json", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.590090:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c[DELETED] /home/felipe/workspace/headset/package-lock.json.3451669346", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
[2411:1026/132946.644022:INFO:CONSOLE(282)] "%c[IPC Library: File Watcher (chokidar)] %c >> normalized  [DELETED] /home/felipe/workspace/headset/package-lock.json.3451669346", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (282)
```

**Comment by bpasero** [comment] 2018-10-27 06:08
@fcastilloec and when you reload the window, the changes show up in the git view?

**Comment by fcastilloec** [comment] 2018-10-27 20:58
@bpasero yes, after manually reloading the window, the changes show up and everything is fine.

**Closed** 2018-11-04 07:12 UTC
Labels: file-watcher, needs more info, upstream

**Comment by thisismydesign** [comment] 2018-11-07 13:47
Could someone clarify what this issue incorporates and what information is missing? Maybe create new separate issues if needed?

I have the same problem with a workspace in git project root directory. It's a fresh project with a handful of files so this issue doesn't make sense to me. I did see the [above mentioned](https://github.com/Microsoft/vscode/issues/42821#issuecomment-371533377) warning pop up a few times ("unable to watch for file changes in this large workspace") but not all the time.

My suspicion is that it's the size of the files that's problematic, e.g. big development.log or tmp files. So I went ahead and ignored those:
```
"files.watcherExclude": {
  "**/.git/objects/**": true,
  "**/.git/subtree-cache/**": true,
  "**/node_modules/*/**": true,
  "**/tmp/**": true,
  "**/log/**": true,
  "**/coverage/**": true
}
```

This seemed to help but a restart also seems to solve the issue temporarily so I can't really tell.

What do you think about a feature to exclude watching gitignored files? I think that would make sense and would simplify the config as well in many cases.

Another thing worth mentioning is the `files.useExperimentalFileWatcher` option. I couldn't find how it is different but maybe it's helpful if the problem persists.

**Comment by wernovox** [comment] 2018-11-29 22:00
I am also having this trouble and I wasn't able to fix yet.
Ubuntu LTS.

**Comment by yy7054wyq5** [comment] 2018-12-02 04:06
macOS: 10.14.1
vscode: 1.29.1
If i put git project in my system partition(Macintosh HD). Git autorefresh work fine. 
I have another partition named 'free', If put git project in it. Git autorefresh did't work.
In these case, Git work fine.

**Comment by fcastilloec** [comment] 2018-12-11 05:03
I can confirm that the issue with this bug is related to different partitions. As @yy7054wyq5 mentioned, if I have a project in the same partition/disk as vscode is installed, then everything works perfectly, otherwise, it doesn't.

@bpasero is there anything I (we) can do to help fix this issue? It's extremely annoying
