### ISSUE TITLE
Format javascript misindent

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#36372] opened 2017-10-16 18:12 UTC
Calling a function with multiple object arguments:
```javascript
func({
    frst: 1
}, {
    scnd: 2
})
```
`Format Document`:
```javascript
func({
    frst: 1
}, {
        scnd: 2
    })
```

**Comment by mjbvz** [comment] 2017-10-16 18:23
Duplicate of https://github.com/Microsoft/TypeScript/issues/14589

**Closed by mjbvz** 2017-10-16 18:23 UTC
Labels: format, javascript, upstream
