### ISSUE TITLE
Unable to disable middle click paste on OSX

### ISSUE THREAD

**Issue by nick-invision** [microsoft/vscode#80804] opened 2019-09-12 14:26 UTC
Middle click causes clipboard contents to paste.  This used to be a feature that could be disabled via "editor.selectionClipboard": "false", but that doesn't appear to be recognized nor work anymore.  This is problematic because my middle click button is mapped to other keystrokes so the results are unexpected.

- VSCode Version: 1.38.1
- OS Version: MacOS Mojave 10.14.6
- Mouse: Logitech MX Master 2s and Marathon M705

Steps to Reproduce:
Prereq: I have middle click mapped to CMD+W to close a tab, but reproduced with multiple other mappings
1. Copy text from anywhere
2. Open a new tab
3. Press middle click
4. Note that the copied text is now pasted

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArsalanWahid** [comment] 2019-09-17 17:38
I second @nick-invision with the addition that mapping any keystroke to any configurable mouse button is causing the clipboard paste problem.

**Current Setup:**
VSCode Version: 1.38.1
OS Version: MacOS Mojave 10.14.6
Mouse: Logitech MX Master 2s

**Comment by alexandrudima** [comment] 2019-10-10 10:33
@nick-invision @ArsalanWahid I cannot reproduce, I have tried with a Microsoft mouse and pressing the middle button has no effect. I have searched for "Logitech MX Master 2s" and have found this article https://9to5mac.com/2017/06/01/hands-on-logitechs-new-mx-master-2s-mouse-w-flow/ 

![image](https://user-images.githubusercontent.com/5047891/66561550-fa920100-eb59-11e9-8602-ab4743f98272.png)

I think the mouse is trying to do something very smart, like act like a keyboard or something and that is backfiring... In any case, I cannot reproduce, does this reproduce for you with other mice?

**Comment by pookdeveloper** [comment] 2019-10-10 11:05
I have the same problem any solutions ¿

**Comment by pookdeveloper** [comment] 2019-10-10 15:40
I have the version September 2019 (version 1.39), and works fine :)

**Comment by ish2028** [comment] 2019-10-16 17:50
I am having similar issues with copy and paste.  I have my side buttons to act as shortcuts for CMD+C and CMD+V but doesn't work properly.  When select text and copy then paste, it will paste it twice.  If I do a copy without selection then paste, it will copy the entire line and the next line below and paste that content.  The next time I do a copy it will act as if I pressed paste.  I am using Logitech MX Anywhere 2S

**Comment by adabru** [comment] 2019-10-17 11:19
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.6-arch1-1-ARCH
no extensions running
![s](https://user-images.githubusercontent.com/6108978/67003852-3c352580-f0df-11e9-8b98-3fed0755844c.png)
I am having this issue on Linux running vscode under XWayland. The option is set to false but middle click both with mouse and with trackpad still pastes primary clipboard. In my case that leads to https://github.com/microsoft/vscode/issues/64856 .
I think solving https://github.com/microsoft/vscode/issues/3130 would also solve this issue.

**Comment by adabru** [comment] 2019-10-17 17:05
For me on Linux the issue was solved in the insiders version (1.40.0-insider), see https://github.com/microsoft/vscode/issues/64856#issuecomment-543200367 .

**Comment by alexandrudima** [comment] 2019-10-18 12:55
I believe this is an issue with the hardware or the driver for it, I don't think this is an issue within VS Code, so I will close this issue...

**Closed by alexandrudima** 2019-10-18 12:55 UTC
Labels: mac, needs more info

**Comment by ArsalanWahid** [comment] 2019-11-02 08:15
The bug no longer exists using 

VSCODE 1.39.2 
macOS Catalina 10.15
