### ISSUE TITLE
[folding] Add code folding for markdown based on heading level

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3347] opened 2016-02-23 16:37 UTC
``` markdown
# Some heading

Collapsing `#` should collapse all lower level headings; `##`, `###`, etc.

## Another heading

Collapsing `##` should collapse all lower level headings; `###`, `####`, etc.

### Another heading

And so on...
```

**Comment by bpasero** [comment] 2016-02-29 13:11
:+1:

**Comment by windsource** [comment] 2016-08-10 15:04
+1

**Comment by darkf** [comment] 2016-12-05 03:58
Why is this essential feature still not a thing?

**Comment by Tyriar** [comment] 2016-12-05 20:36
@darkf because it relies on #3422 which is non-trivial and it needs to be prioritized against other work.

**Comment by sixeyes** [comment] 2017-04-06 15:04
+1

**Comment by gravidor** [comment] 2017-07-21 01:35
+1

**Comment by yusiwen** [comment] 2017-08-08 01:37
+1
or adding a heading list view(TOC view) on the right side, it's really convenient for editing a large markdown file.

**Comment by iswade** [comment] 2017-10-12 01:45
Please refer to the org-mode tab feature to implement, it's powerful.

**Comment by sejnub** [comment] 2017-11-08 11:28
+1

**Comment by aeschli** [comment] 2017-11-22 10:15
duplicate of #3422

**Closed** 2018-03-02 21:33 UTC
Labels: editor-folding, feature-request, markdown

**Comment by neilsustc** [comment] 2018-03-16 13:08
I noticed that this is already implemented in the latest insider build, thanks a lot.
One more request, would you please preserve the last blank line of a folded region?
I mean

```
- # Heading 1

  Some text

- # Heading 1

  Another text
```

becomes

```
+ # Heading 1

+ # Heading 1
```

instead of

```
+ # Heading 1
+ # Heading 1
```

One reason is that currently

```
- # Heading 1           - # Heading 1

  ...                     ...

- ## Subheading 1  -->  + ## Subheading 1
                        - # Heading 2
  ...

- # Heading 2
```

**Comment by hikinthru** [comment] 2018-04-01 14:11
Can anyone update the status on this?

**Comment by Tyriar** [comment] 2018-04-02 13:29
@hikinthru it's coming to the next stable release.
