### ISSUE TITLE
auto jsdoc comments not completing @returns 

### ISSUE THREAD

**Issue by wayou** [Microsoft/vscode#23786] opened 2017-04-01 07:29 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|code-settings-sync|Shan|2.6.1|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-dash|deerawan|1.4.0|
|python|donjayamanne|0.6.0|
|flow-for-vscode|flowtype|0.5.0|
|Theme-MaterialKit|ms-vscode|0.1.1|
|sublime-keybindings|ms-vscode|2.0.1|
|vscode-icons|robertohuertasm|7.4.0|
|vscode-todo-highlight|wayou|0.4.13|;

---

The built in [Auto JSDoc comments](https://code.visualstudio.com/updates/v1_10#_auto-jsdoc-comments) is really nice. However, `@returns` not working.

Steps to Reproduce:

1. create a es6 class:
```js
class Foo {
    bar() {
        return "allo!";
    }
}
```

2. type `/**` above method `bar` and enter not completing the documentation, `@returns` is expected.

**Comment by mjbvz** [comment] 2017-04-03 16:53
Thanks. This is a duplicate of #21832. `@return` completion specifically is tracked upstream by https://github.com/Microsoft/TypeScript/issues/14248

**Closed by mjbvz** 2017-04-03 16:53 UTC
