### ISSUE TITLE
errors.reduce is not a function

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35539] opened 2017-10-03 18:31 UTC
Seen when testing locally. I think TPromise.join() will always reject with the same value as the first promise that was rejected, that is not an array in general: https://github.com/Microsoft/vscode/blame/master/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L271

/Users/chrmarti/Development/repos/vscode/out/vs/workbench/services/message/browser/messageService.js:85 errors.reduce is not a function: TypeError: errors.reduce is not a function,    at ExtensionManagementService.joinErrors (file:///Users/chrmarti/Development/repos/vscode/out/vs/platform/extensionManagement/node/extensionManagementService.js:264:27),    at file:///Users/chrmarti/Development/repos/vscode/out/vs/platform/extensionManagement/node/extensionManagementService.js:255:141,    at Object.notifyError [as _notify] (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1209:50),    at Object.enter (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:901:30),    at Promise_ctor._run (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1068:29),    at Promise_ctor._error (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1041:18),    at error (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:743:33),    at ErrorPromise_ctor.ErrorPromise_then [as then] (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1436:50),    at Object.enter (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:747:28),    at Promise_ctor._run (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)

**Comment by sandy081** [comment] 2017-10-10 09:09
Making this as a duplicate of the #35903 as the later has steps to reproduce.

Duplicate of #35903

**Closed by sandy081** 2017-10-10 09:09 UTC
Labels: bug, extensions
