### ISSUE TITLE
Column mode selection behavior is inconsistent with user expectations

### ISSUE THREAD

**Issue by nholthaus** [Microsoft/vscode#11830] opened 2016-09-10 14:29 UTC
- VSCode Version: 1.5.1
- OS Version: Ubuntu 14.04, Windows 7/10, probably all others

Most programs with column mode (visual studio/notepad++/kdevelop/etc) have the following user experience:

1. hold the keyboard shortcut/toggle column mode.
2. click somewhere. This is the selection 'start' anchor.
3. drag somewhere. This is the selection 'end' anchor.

However, in visual studio code, the process is:

1. click somewhere. This is the selection 'start' anchor.
2. hold the keyboard shortcut/toggle column mode
3. drag somewhere. This is the selection 'end' anchor.

IMHO this is unintuitive for two reasons:
1. It goes against all the training we have from other dev tools we've been using much longer.
2. Usually, I don't think about where I _left_ my cursor when I decide to do an operation. I'm thinking about what I _want_ to do. I find that whenever I use code's column mode, I'm always unpleasantly surprised to find that the cursor is not where I expect it and isn't updated to my click.

Additionally, while it's technically the same number of steps, method 1 is much more fluid as the holding/clicking/dragging can be done in a smooth motion, rather than having to position the cursor as a distinct and thoughtful first step.

Could you please change the cursor selection to method 2?

**Comment by glen-84** [comment] 2016-09-10 17:43
Duplicate of #5402.

**Comment by ramya-rao-a** [comment] 2016-09-11 16:28
@nholthaus Don't forget to up vote the original issue
@glen-84 Thanks for finding the original issue

**Closed by ramya-rao-a** 2016-09-11 16:28 UTC
Labels: duplicate
