### ISSUE TITLE
Renaming files not working on some files

### ISSUE THREAD

**Issue by ertay** [microsoft/vscode#95647] opened 2020-04-19 16:51 UTC
Issue Type: <b>Bug</b>

Tagging @IsidorN as requested.
I'm trying to rename some Markdown files that I have in a folder and about 1/3 of  the files can be renamed, while for the rest, when I try to rename them, nothing happens. It works fine in the stable version, but not on the insiders version. Here is a link to the repository where my blog is hosted: https://github.com/ertay/ertay.github.io

Steps to Reproduce:

1. Download the repository linked above.
2. Open the folder in VS Code
3. Expand the _posts folder in the Files Explorer.
4. Try to rename the files in the bottom (so the latest files).

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.45.0-insider (a3083e58e2a9e77f60e531acaa32e18527ae8439, 2020-04-17T08:09:47.238Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.35GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment] 2020-04-20 10:51
@ertay thanks for precise steps however this works for me.
I followed your exact steps and I could rename from the explorer both by using the keyboard and the context menu.

Here's a gif showing what I am doing. If you are doing something different to what I described or what I have shown in the gif let me know.
Also if you F1 > developer tools > do you see some errors in the console
Can you rename those files using the native file explorer

![rename](https://user-images.githubusercontent.com/1926584/79743839-98cf0280-8305-11ea-83c7-9fe74985c255.gif)

**Comment by ertay** [comment] 2020-04-20 11:41
@Isidorn I'm sorry I'm not able to see the GIF as I am blind. For me both the F2 shortcut, and the Rename function from the context menu don't work. If I start from the top of the file list in the _posts folder, it works until I reach the file named "2019-4-4-episode-9-sighted-assistance-for-blind-board-gamers-with-dale-and-laura-rowe". After that file, I cannot rename any of the files inside that folder, others work fine.

Also, I toggled the Developer Tools, which seemed to open a DOM browser, going through that with my screen reader I didn't see any errors. 

Renaming the files outside of VS Code-Insiders works fine, even with VS Code Insiders open, iif I use Windows Explorer to rename an opened file, it updates in VS Code just fine. It is very weird because I don't have this problem in the stable build of VS Code, all files can be renamed there. I tried closing the folder, opening it again, but same issue.

**Comment by isidorn** [comment] 2020-04-20 13:19
@ertay no need to be sorry, I was stupid about the gif, I have removed it from my initial comment. Sorry about that.

1) Do you use some screen reader when attached to VS Code?
2) When you press `F2` do you not get the inputbox, or you get it but typing anyhting has no effect
3) You see the same behavior even if you reload vscode?
4) Does deleting those files for example work? Only rename is the problem?

I just tried reproducing also on my Windows machine and I could not reproduce. And due to I have to ask you all these questions..

**Comment by isidorn** [comment] 2020-04-21 08:34
Let's close as duplicate of https://github.com/microsoft/vscode/issues/95315
Since that is the oldest issue. It seems like I broke something in vscode insiders.

**Closed by isidorn** 2020-04-21 08:34 UTC
Labels: file-explorer, needs more info
