### ISSUE TITLE
Find in Files doesn't produce results from editors you haven't focused yet

### ISSUE THREAD

**Issue by sonatypeJimB** [microsoft/vscode#80648] opened 2019-09-10 14:37 UTC
- VSCode Version: 1.38.0
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Open multiple files via terminal, e.g.:
rg -F -l 'origin_found_in_model(' django-cors-* | xargs code -n
(This opens 11 files, all of which have the same filename (in different subdirs)
2. Use "Find in Files" to search for a text string that you know is in all opened files
3. Observe that the results only come from the currently focused file, and not all opened files
4. Click to focus each of the other open files' tabs and refresh the search results
5. Observe that each time you focus another file, the Find begins including results from that file

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by skprabhanjan** [comment] 2019-09-18 05:12
@roblourens , This somehow works correctly for me and I cannot reproduce this issue.
Any thoughts here ?

**Comment by roblourens** [comment] 2019-09-18 16:56
This will not be an easy one to fix @skprabhanjan

**Comment by roblourens** [comment] 2019-10-10 00:51
duplicate of https://github.com/microsoft/vscode/issues/62488

**Closed by roblourens** 2019-10-10 00:51 UTC
Labels: bug, search
