### ISSUE TITLE
Invalid string length + Unknown actor MainThreadTerminal Service

### ISSUE THREAD

**Issue by easherma-truth** [microsoft/vscode#151147] opened 2022-06-02 19:44 UTC
Issue Type: <b>Bug</b>

I keep getting these errors, seems to only be with one workspace and extentions enabled. 

I see these errors in logs: 

```
[2022-06-02 14:41:37.170] [renderer5] [error] RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at r (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:7126)
    at Function.serializeRequestArguments (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:17746)
    at v._remoteCall (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:13422)
    at Proxy.L.<computed>.M.charCodeAt.L.<computed> (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:9649)
    at new o (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1712:64318)
    at S._createInstance (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:591:1332)
    at S.createInstance (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:591:773)
    at Br._createExtensionHostCustomers (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1968:7761)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1968:5199
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
2022-06-02 14:41:37.242] [renderer5] [error] Unknown actor MainThreadTerminalService: Error: Unknown actor MainThreadTerminalService
    at v._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:12971)
    at v._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:12851)
    at v._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:11513)
    at v._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:10191)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1719:8300
    at m.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at u._deliverMessages (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19435)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19180
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.17.5-76051705-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 3119)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.08GB (11.10GB free)|
|Process Argv|. --crash-reporter-id 1ab019cd-013c-4781-90d0-5dd4d6953623|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.7
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
pythonsnippets|frh|1.0.2
unibeautify-vscode|Gla|0.8.2
pytest-snippets|jai|1.0.0
vscode-graphviz|joa|0.0.6
pretty-formatter|mbl|0.2.2
theme-monokai-pro-vscode|mon|1.1.20
vscode-docker|ms-|1.22.0
python|ms-|2022.6.3
vscode-pylance|ms-|2022.6.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.234.0
test-adapter-converter|ms-|0.1.6
autodocstring|njp|0.6.1
jinjahtml|sam|0.17.0
django-intellisense|sha|0.0.2
code-settings-sync|Sha|3.4.3
code-spell-checker|str|2.2.0
graphviz-interactive-preview|tin|0.3.0
errorlens|use|3.5.1
intellicode-api-usage-examples|Vis|0.1.1
vscodeintellicode|Vis|1.2.21
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550

```

</details>

**Comment by Tyriar** [comment] 2022-06-02 20:48
Looking at those locations in the bundled product, here are where the exceptions are throw.

```
[2022-06-02 14:41:37.170] [renderer5] [error] RangeError: Invalid string length
```


JSON.stringify: r (stringify) https://github.com/Microsoft/vscode/blob/bd50a9b0751d4708e0a7b9c78b2a13c34ec6e681/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L82
serializeRequestArguments https://github.com/Microsoft/vscode/blob/bd50a9b0751d4708e0a7b9c78b2a13c34ec6e681/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L755

2022-06-02 14:41:37.242] [renderer5] [error] Unknown actor MainThreadTerminalService: Error: Unknown actor MainThreadTerminalService

https://github.com/Microsoft/vscode/blob/bd50a9b0751d4708e0a7b9c78b2a13c34ec6e681/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L467

@jrieken any idea what could be causing this/hints where to look? AFAIK we're registering MainThreadTerminalService in every extension host type.

**Comment by alexdima** [comment] 2022-06-10 13:46
Deminified using https://github.com/alexdima/vscode-stack-beautifier

RangeError:&nbsp;Invalid&nbsp;string&nbsp;length<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/services/extensions/common/rpcProtocol.ts:82:13`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./workbench/services/extensions/common/rpcProtocol.ts#L82)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/services/extensions/common/rpcProtocol.ts:755:9`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./workbench/services/extensions/common/rpcProtocol.ts#L755)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/services/extensions/common/rpcProtocol.ts:490:47`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./workbench/services/extensions/common/rpcProtocol.ts#L490)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/services/extensions/common/rpcProtocol.ts:253:18`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./workbench/services/extensions/common/rpcProtocol.ts#L253)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/api/browser/mainThreadTesting.ts:45:14`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./workbench/api/browser/mainThreadTesting.ts#L45)<br/>&nbsp;&nbsp;at&nbsp;[`./platform/instantiation/common/instantiationService.ts:110:12`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./platform/instantiation/common/instantiationService.ts#L110)<br/>&nbsp;&nbsp;at&nbsp;[`./platform/instantiation/common/instantiationService.ts:76:17`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./platform/instantiation/common/instantiationService.ts#L76)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/services/extensions/common/extensionHostManager.ts:295:47`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./workbench/services/extensions/common/extensionHostManager.ts#L295)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/services/extensions/common/extensionHostManager.ts:145:16`](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/./workbench/services/extensions/common/extensionHostManager.ts#L145)<br/>

---

The root cause is that [`MainThreadTesting `](https://github.com/Microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/workbench/api/browser/mainThreadTesting.ts#L45) tries to send a message to the extension host which is so large that it cannot be represented as a JavaScript string. According to [this StackOverflow post](https://stackoverflow.com/a/47781288), JavaScript strings can be up to 1GB in length, so `MainThreadTesting` must be trying to send more than 1GB of data in its ctor.

The ctor for `MainThreadTesting` throws, so that terminates abruptly [this loop where extension host named customers are instantiated](https://github.com/microsoft/vscode/blob/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/src/vs/workbench/services/extensions/common/extensionHostManager.ts#L295). I think this then causes the error `Unknown actor MainThreadTerminalService`.

I will look into wrapping all instantiations with a try/catch such that other named customers are not affected by one failing, but this is a critical error, the extension host can't be in a good state even if one named customer is missing.

**Comment by connor4312** [comment] 2022-06-10 14:19
1GB feels like an above-average string length.

@easherma-truth what kind of tests do you have in your workspace? I see you have the `test-adapter-converter` extension, but don't recognize anything that would plug into that.

**Comment by easherma-truth** [comment] 2022-07-11 18:29
@connor4312 most of the time I'm on a python/django stack, so mostly pytest. I have `test-adapter-converter` currently disabled, I think at some point I was playing around with using https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer but that is also disabled at the moment.

**Comment by Mike-Klepper-Hathway** [comment] 2022-07-12 16:15
Am experiencing the same problem on 
Mac OS Monterey 12.3.1
VS Code: 1.69.1; also on 1.68.0
Also tried different versions of Node

Bisect shows "This might be a problem with Code"

When VS Code is started, this is printed in the Output terminal:
```
[2022-07-12 12:10:36.274] [renderer1] [critical] Cannot instantiate named customer: 'MainThreadTesting'
[2022-07-12 12:10:36.274] [renderer1] [critical] {}
[2022-07-12 12:10:36.275] [renderer1] [error] Invalid string length: RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:7166)
    at Function.serializeRequestArguments (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:17633)
    at v._remoteCall (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:13331)
    at Proxy.x.<computed>.M.charCodeAt.x.<computed> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:9691)
    at new o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1698:64098)
    at m._createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:599:1346)
    at m.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:599:779)
    at Is._createExtensionHostCustomers (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1956:7767)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1956:5199
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-07-12 12:10:36.310] [renderer1] [error] Error: Missing proxy instance MainThreadTesting
    at v.assertRegistered (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:9901)
    at Is._createExtensionHostCustomers (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1956:8265)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1956:5199
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-07-12 12:10:36.310] [renderer1] [warning] Settings Sync: Accounts are not initialized
[2022-07-12 12:10:36.315] [renderer1] [error] Missing proxy instance MainThreadTesting: Error: Missing proxy instance MainThreadTesting
    at v.assertRegistered (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:9901)
    at Is._createExtensionHostCustomers (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1956:8265)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1956:5199
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by easherma-truth** [comment] 2022-07-13 15:21
FWIW, when I open from a workspace I don't get this error, even when working on the same repo. Very odd.

**Comment by bpasero** [comment] 2022-07-30 04:06
I think this was mitigated, so moving to August.

**Closed** 2022-08-02 15:27 UTC
Labels: bug, important

**Comment by mjbvz** [comment] 2022-08-25 23:43
@connor4312 Any steps to verify this?

**Comment by connor4312** [comment] 2022-08-26 15:57
No steps really, but in the code the lines that caused this error no longer exist: https://github.com/microsoft/vscode/pull/156834/files#diff-86e89d2d87ac27d3efa349c72b84b0130a5e01592563e6555d68a368beffec0d

**Comment by TylerLeonhardt** [comment] 2022-08-26 16:56
marking as verified from code review.
