### ISSUE TITLE
Git: Bad status code: 500

### ISSUE THREAD

**Issue by ALLG-Solutions** [microsoft/vscode#154511] opened 2022-07-08 14:09 UTC
Issue Type: <b>Bug</b>

Bom dia, após fazer a atualização do VS Code ontem, não consigo mais sincronizar alterações com o github.

Sempre que tento sincronizar, sobe um pop-up com o erro: "Git: Bad status code: 500".

Já removi o repositório da minha máquina e fiz o clone via github desktop e mesmo assim o VS Code não permite a sincronização.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (2.93GB free)|
|Process Argv|--crash-reporter-id fd276314-46f0-4e78-8d2e-1872dda1e178|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xd|ado|1.2.3
vscode-tailwindcss|bra|0.8.6
vscode-html-css|ecm|1.13.0
prettier-vscode|esb|9.5.0
vscode-language-pack-pt-BR|MS-|1.69.7060944
LiveServer|rit|5.7.5
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by lszomoru** [comment] 2022-07-08 15:35
Closing as duplicate of #154449.

**Closed** 2022-07-08 15:35 UTC
Labels: bug, git, *duplicate, new release
