### ISSUE TITLE
Multiple Alt-F S commands in the File Menu.

### ISSUE THREAD

**Issue by observaInc** [Microsoft/vscode#38429] opened 2017-11-15 16:40 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Type Alt-F S.  It doesn't save.  It did in the past.

I'm a chronic Alt-F S pusher, to save my work as I go.  With the latest release, there are now two Alt-F S choices.  Maybe have a different hot letter for "Save WorkSpace As".  Maybe Alt-F k?

**Comment by jkristia** [comment] 2017-11-15 21:32
+1 for this issue. I have used 'Alt F S' for the last many years and cannot get used to Ctrl-S instead. Please bring this back

**Comment by isidorn** [comment] 2017-11-16 09:50
Duplicate of https://github.com/Microsoft/vscode/issues/38006

**Closed by isidorn** 2017-11-16 09:50 UTC
Labels: new release
