### ISSUE TITLE
Windows: window on secondary monitor does not restore at exact position

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#36122] opened 2017-10-12 09:46 UTC
This can happen when VS Code on a secondary monitor is not full screen. I filed https://github.com/electron/electron/issues/10768 and https://github.com/electron/electron/issues/10771

**Comment by bpasero** [comment] 2017-10-17 04:52
Maybe causes https://github.com/Microsoft/vscode/issues/35148

**Comment by robinsh** [comment] 2017-10-18 16:50
@bpasero Just FYI: I opened VS Code, put it on the second monitor, maximized it, then closed it. When I reopened it, it opened it (maximized) on the Surface tablet. That's at least better than it showing up off-screen. When do you think my original problem (appearing off-screen) might be fixed?

**Comment by bpasero** [comment] 2017-10-19 09:44
@robinsh we require a fix in our upstream component Electron. I hope to get something for this milestone but it might slip.

**Comment by davidnjohnson** [comment] 2017-10-19 16:59
In case it helps anyone who stumbles on this issue; the problem is the most severe when the zoom level of the primary monitor doesn't match the secondary monitor.  I suspect the saved coordinates are being erroneously multiplied by the zoom level of the primary monitor, rather than the ones on the secondary monitor.  (I finally ended up setting my 4K primary monitor to 1920x1080 with 100% zoom, which fixed the positioning issue on VSCode open)

**Comment by robinsh** [comment] 2017-10-19 23:06
Thanks @davidnjohnson . I don't know if I can bear changing the resolution on my Surface just for this one problem, but if I get desperate, I'll try it out!

**Comment by robinsh** [comment] 2017-10-19 23:07
@bpasero Thanks very much. It's quite maddening. Will I get any kind of notification when it's been fixed?

**Closed** 2017-11-01 10:47 UTC
Labels: bug, electron, upstream, workbench

**Comment by bpasero** [comment] 2017-11-01 10:49
I pushed a workaround in VS Code that seems to fix this by calling `window.setPosition` in case the retrieved position is different from what we passed in. 

**To verify:**
* connect an external monitor to have 2 monitors
* move VS Code to the external monitor (do not maximize the window)
* close VS Code and restart
* the position should be the same as before

Maybe use VS Code stable to verify the issue reproduces with your setup.
