### ISSUE TITLE
Command `workbench.action.compareEditor.previousChange` (or next change) lags

### ISSUE THREAD

**Issue by timocov** [microsoft/vscode#178680] opened 2023-03-30 11:37 UTC
Type: <b>Performance Issue</b>

Every time I execute a command `workbench.action.compareEditor.previousChange` or next change either via command palette or shortcut (I have `ctrl+shift+up` assigned) it takes about half a second to do it (see attached gif below). I tried to disable all extensions but no luck.

![vscode-issue](https://user-images.githubusercontent.com/3112183/228823925-10f4525a-7f49-4bf3-93d0-dd06252b9b3f.gif)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045

Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600K (20 x 3494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (19.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   119	  1188	code main
    0	   272	  7328	   window (D:\projects\dts-bundle-generator\src\bundle-generator.ts - dts-bundle-generator)
    0	    98	  8612	   issue-reporter
    0	    89	 11084	   utility-process
    0	   126	 11316	   utility-process
    0	   153	  6940	     electron-nodejs ("C:\Users\timocov\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\timocov\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\timocov\AppData\Local\Temp\vscode-typescript\a966e4908f350cbb39f0\tscancellation-cec96480eb3d10899abe.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	   108	 20832	       electron-nodejs ("C:\Users\timocov\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/timocov/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/timocov/AppData/Local/Microsoft/TypeScript/4.9 --enableTelemetry --typesMapLocation "c:/Users/timocov/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation)
    0	   135	 12444	     electron-nodejs ("C:\Users\timocov\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\timocov\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\timocov\AppData\Local\Temp\vscode-typescript\a966e4908f350cbb39f0\tscancellation-e1e28ea54b5dd2856370.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    40	 13728	   utility-network-service
    0	   632	 14304	   gpu-process
    0	   110	 19500	   shared-process
    0	    94	  3280	     fileWatcher
    0	    74	 19920	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (D:\projects\dts-bundle-generator\src\bundle-generator.ts - dts-bundle-generator)
|    Folder (dts-bundle-generator): 682 files
|      File types: ts(370) js(94) json(20) gitignore(8) md(5) yml(3)
|                  tsbuildinfo(3) eslintignore(1) gitattributes(1) svg(1)
|      Conf files: tsconfig.json(17) github-actions(2) settings.json(1)
|                  package.json(1);
```

</details>
Extensions: none

**Comment by dwelle** [comment] 2023-04-17 12:15
duplicate of https://github.com/microsoft/vscode/issues/173256?

**Comment by hediet** [comment] 2023-04-18 07:12
Closing as duplicate.

**Closed by hediet** 2023-04-18 07:12 UTC
