### ISSUE TITLE
Changing ExperimentalDecorators requires restart to take effect

### ISSUE THREAD

**Issue by benjaminRomano** [Microsoft/vscode#539] opened 2015-11-24 09:24 UTC
![image](https://cloud.githubusercontent.com/assets/9221137/11362592/578d84e0-925a-11e5-9a3d-17d8222f3752.png)

Even after setting experimentalDecorators to true in the tsconfig.json, the error message persists. The error message goes away once you restart vs code.

**Comment by egamma** [comment] 2015-11-30 09:31
@dbaeumer is this issue addressed in TS 1.7?

**Comment by dbaeumer** [comment] 2015-11-30 11:01
@egamma I was able to reproduce this and it is actually a timing issue (race condition). The problem is that the tsserver (even 1.6.x version) listen to changes of the tsconfig.json file. VSCode re-requests all diagnostics when the tsconfig.json file changes. If the tsserver hasn't processed the file event of the tsconfig.json change event yet the old diagnostic values are computed. 

The real fix would be that the tsserver informs the editor about a change to the tsconfig.json file and then the editor can request diagnostics. As a workaround we can add a timeout in VSCode. However that might not always work.

**Comment by dbaeumer** [comment] 2015-11-30 11:09
I opend https://github.com/Microsoft/TypeScript/issues/5829 for a real fix in tsserver land. I will put in a work around on our end to make the race condition less likely.

**Closed** 2015-11-30 11:15 UTC
Labels: bug, typescript
