### ISSUE TITLE
黑色背景(monokai),选中状态下看不见选中的字了(背景色和字体颜色重合)

### ISSUE THREAD

**Issue by hanjituan** [microsoft/vscode#123059] opened 2021-05-06 02:39 UTC
Issue Type: <b>Bug</b>

随便选择代码,然后搜索
在搜索栏中展示的白色背景和白色的字完全看不了选中的是什么字

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.88GB free)|
|Process Argv|--crash-reporter-id 3b8cdeec-14f6-4fed-85d1-c6d558b52425|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-angular2-files|ale|1.6.4
ng-template|Ang|11.2.14
ng-zorro-vscode|cip|11.2.2
codestream|Cod|11.0.5
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
tslint|eg2|1.0.46
auto-close-tag|for|0.5.10
vue|jcb|0.1.5
Angular2|joh|11.0.0
code-beautifier|mic|2.3.3
Angular-BeastCode|Mik|10.0.3
vscode-language-pack-zh-hans|MS-|1.56.1
vetur|oct|0.33.1
material-icon-theme|PKi|4.6.0
angular-follow-selector|san|1.2.0
element-ui-snippets|SS|0.7.2
autoimport|ste|1.5.4
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by lengthmin** [comment] 2021-05-06 03:22
描述的详细一点，我简单试了一下并没有复现，是全局搜索还是当前文件搜索？

---
please describe in detail, unable to reproduce

**Comment by lengthmin** [comment] 2021-05-06 03:23
![image](https://user-images.githubusercontent.com/13938334/117237360-64b97780-ae5d-11eb-8f10-cca5444e3580.png)

can reproduce

**Comment by lengthmin** [comment] 2021-05-06 03:24
related https://github.com/microsoft/vscode/issues/123044

**Comment by crisbeto** [comment] 2021-05-06 05:36
I'm seeing this too: 
![bug](https://user-images.githubusercontent.com/4450522/117246986-cd90f780-ae3d-11eb-9c3b-b1154328e78d.png)

**Comment by infinnie** [comment] 2021-05-06 06:43
Translation:
# In a dark theme (_e.g._ Monokai), text becomes invisible when selected (due to its color being the same as the selection background)

Select text and search.

In the search box, the selection background and text are in the same light color, so that one cannot see which text is selected.

**Comment by nrayburn-tech** [comment] 2021-05-08 23:28
Duplicate of #123044.

**Comment by CodeCrazy-ywt** [comment] 2021-07-02 14:33
> 感谢您创建此问题！
> 
> 然而，由于您没有使用英语，我们很难进行处理。如果可能，请您将此问题描述修改为英文。请您直接编辑此问题，不要提交回复或新问题。
> 
> 请注意，机器翻译服务通常无法处理用于讨论软件问题所需的技术性语言，所以我们推荐您寻找一位熟悉相关技术的人来协助翻译。
> 
> 如果您无法做到，没有关系。此问题已经被标记为需要翻译，等待社区成员志愿进行翻译。
> 
> Thanks for creating this issue!
> 
> Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.
> 
> In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.
> 
> Otherwise, we have marked this as needing translation and a community member may be able to help out.

Here's my translation:
Title: In the dark background(monokai), words selected cannot be seen(The background color is the same as the word color)
Content:Select a text, then search(I suppose he means ctrl+f). In the search box, the background and the words are both white, and words are invisible.

**Closed** 2021-07-06 17:48 UTC
Labels: *duplicate, *english-please, needs more info, translation-required-chinese-simplified
