### ISSUE TITLE
[feat] Set file's language mode via comment

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#230094] opened 2024-09-30 04:30 UTC
I often open files which are not associated with the correct language, as they lack extensions. So I must use the 2-part "Change Language Mode" command from the command palette.

That is slow and a nuisance, and must be done each time.

It would be nice if we could manually associate a file with a language. For example, with a comment at the top or bottom of the file:
```
# lang:foo
```
or
```
// lang:foo
```

But it should allow whitespace and other comments too, so we can use a regular file header and other instructions, if needed:
```
// this file does foo bar baz                                    // spell:disable // lang:foo
// copyright by company
...
```

**Comment by isidorn** [comment] 2024-10-04 13:36
This should work already. Since we have automatic language detection as you start typing.
What is exactly missing here?

**Comment by isidorn** [comment] 2024-10-04 16:51
I suggest to just file new issues with reproducible steps when it detects the wrong langauge. That would be the most helpful. Thus closing this one

**Closed by isidorn** 2024-10-04 16:51 UTC
Labels: info-needed
