### ISSUE TITLE
Breakpoints pane should update when debugger has switched

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#126608] opened 2021-06-17 11:03 UTC
When using both the JS Debugger and [XDebug](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug) at the same time I lose control of the JS Debugger (even after switching back) in the breakpoints pane (on the left hand side).

All other panes update: "variables", "watch", "call stack", "loaded scripts" but "breakpoints" remains on the Xdebug options when switching back to the JS Debugger. This means its impossible for me to switch off the "Caught Errors" breakpoint without switching off the JS Debugger altogether.

**Comment by jasonwilliams** [comment] 2021-06-21 16:58
In this video i start the JS Debugger with chrome running. I check for "Uncaught Breakpoints".

i then start XDebug and the "breakpoints" pane changes (bottom left). However, switching back to Chrome doesn't bring it back, so I'm now stuck on this pane and unable to turn off "Uncaught Breakpoints".

Even after turning off XDebug completely the "breakpoints" pane remains the same
 
https://user-images.githubusercontent.com/936006/122799716-f704c600-d2b9-11eb-9f1d-e133a4b2db78.mov

**Comment by isidorn** [comment] 2021-06-22 14:06
@jasonwilliams I acknowledge this issue.
We simply did not write code to support this. Our current approach with mutli session debugging and exception breakpoints is that they will be similar across different sessions.
If they are not then issues like the one you presented appear.

The fix would be that on focus change the exception breakpoints change.
And thinking about it more, exception breakpoints should probably live on the `DebugSession` layer and not in the debug model since they are tied to the session, not the overall model.

This should be fixed in vscode core thus unassigning @connor4312 
However not sure when I will find to tackle this.

**Comment by weinand** [comment] 2021-08-18 10:07
Yes, exception configurations depend on active session and we need to reflect this in the UI.
The problem is that breakpoints **do not** depend on the active session but that they share the BREAKPOINTS view with the exceptions.

**Comment by johnrom** [comment] 2022-04-08 15:34
Probably related, but the topic isn't covered in the OP: https://github.com/microsoft/vscode/issues/147096

If exceptions lived in DebugSession layer as above, that would likely fix my issue as well.

**Comment by nisargjhaveri** [comment] 2022-08-17 10:02
I've attempted a fix in PR #158355.

It does not completely move exception breakpoints to the DebugSession plane, but allows multiple debuggers with different exception breakpoints capabilities to co-exists by showing all exception breakpoints at once.

As an added benefit, it also helps with workspaces where multiple debuggers are used frequently as it does not remove the exception breakpoints for other debuggers automatically and keeps the preferences intact.

This does not fix the issue #147096, where we need different enablement for different sessions.

**Closed** 2022-11-17 20:39 UTC
Labels: bug, debug

**Comment by roblourens** [comment] 2022-11-29 04:00
Verification steps

- Start a debug session
- Start a second debug session with a different debug type. For example, you can use node/python for this
- Ensure that when you focus the first debug session in the callstack, the breakpoints view shows the exception filters from that debug type, and when you focus the second, it switches to exception filters from the second.
- Try starting, stopping, switching the focused debug session, make sure nothing weird happens
- And test with multiple sessions of the same type- the checked exception filters should still apply to all sessions of the same type

**Comment by meganrogge** [comment] 2022-11-30 22:01
@roblourens when I try to debug a python file, it doesn't stay in the view for long enough to actually focus the item

https://user-images.githubusercontent.com/29464607/204917424-ac9ab6fa-4dcf-41ba-a801-280eb2c06a54.mov

**Comment by roblourens** [comment] 2022-12-01 00:52
Sure- it ran and completed. You could try hitting a breakpoint 😄

**Comment by meganrogge** [comment] 2022-12-01 04:16
I added a breakpoint but it didn't stop there

**Comment by johnrom** [comment] 2022-12-01 15:14
@meganrogge if you stop all of your other processes and run only that python script, does it hit the breakpoint? I notice in your screen capture it is set to debug, so theoretically it should.

![image](https://user-images.githubusercontent.com/1881482/205089128-40a4aa4f-b476-44b8-afc4-f854025f2352.png)

I noticed that on the live build (I haven't tested this prerelease), if I have another session running in JS or something, it displays an inactive breakpoint for the python script -- but it still hits the breakpoint when I debug using Python 3.11.0.

- If the python script doesn't hit the breakpoint when all other processes are stopped, either 
  - there is a configuration issue with your VS Code (maybe using an unsupported python version, or some setting specific to your vscode prerelease build) or 
  - there is an issue with Python breakpoints in general at this commit.
- If the python script does hit the breakpoint, it's possible this latest commit (or another prerelease change contained in this commit) actually broke something related to multiple sessions and python

**Comment by roblourens** [comment] 2022-12-01 19:30
Python 2.7 may not be supported for debugging @meganrogge, in any case, I recommend moving to the latest 3.x

@johnrom you seem to think you're commenting on a PR, but this is not a PR

**Comment by johnrom** [comment] 2022-12-01 19:38
@roblourens the PR tracked by this issue is #158355 and is what I am referring to by "the PR"

**Comment by roblourens** [comment] 2022-12-01 20:48
It seems like you're trying to be helpful, so thank you, but all this stuff you're saying doesn't really seem relevant to the problem at hand.

**Comment by meganrogge** [comment] 2022-12-01 21:09
I'm pretty confused by this python experience - my version is `3.9.5`, this `pyenv shell 2.7.18` thing is printed to the terminal 🤔 . Someone else should try to verify this.

![Screenshot 2022-12-01 at 3 08 10 PM](https://user-images.githubusercontent.com/29464607/205159548-066e1ef2-f81b-4dc6-ae8b-a16d58fc5ceb.png)

**Comment by paulacamargo25** [comment] 2022-12-01 21:57
Everything works for me as expected. Nice Job!

<img width="1792" alt="Screenshot 2022-12-01 at 1 55 09 PM" src="https://user-images.githubusercontent.com/17892325/205167247-3dd33183-2fdb-4dd0-9a2e-058b0448b7de.png">

<img width="347" alt="Screenshot 2022-12-01 at 1 54 17 PM" src="https://user-images.githubusercontent.com/17892325/205167231-895d8699-94b9-4435-b66f-f46716b7cee5.png">
<img width="342" alt="Screenshot 2022-12-01 at 1 54 58 PM" src="https://user-images.githubusercontent.com/17892325/205167245-c7e9e036-ad54-4f9e-99ae-87545b4d18e1.png">

**Comment by johnrom** [comment] 2022-12-02 14:52
I was under the impression that someone was trying to verify an issue that I'm following, and that individual was not able to because of a likely misconfiguration either in vscode or python itself. I gave steps for ruling out vscode (or at worst, identifying a regression). I'm not sure what is off topic about that, but either way it looks like the situation has resolved itself. I'll avoid commenting on issues that you manage in the future unless I am directly participating in them.
