### ISSUE TITLE
Markdown preview rendering width does not consider window.zoomLevel correctly

### ISSUE THREAD

**Issue by ccprog** [Microsoft/vscode#17467] opened 2016-12-17 18:01 UTC
- VSCode Version: 1.8.0
- OS Version: Linux Mint LMDE2 Cinnamon 64-bit, Cinnamon 3.2

Depending on the value of window.zoomLevel or  on the fly with Ctrl-'+' or Ctrl-'-', the Markdown preview width might not fit within its display area:
- for `"window.zoomLevel": 1`, the lines are visibly shorter than the editor area, and the scroll bar sits left of the right border.
![zoomlevel-up](https://cloud.githubusercontent.com/assets/5325416/21288703/4075c584-c48a-11e6-8a5e-acbe06a327fe.png)
- for `"window.zoomLevel": 0`, the lines just fill the editor area.
- for `"window.zoomLevel": -1`, the lines are overflowing the editor area, no scroll bar is visible, no horizontal scroll bar is displayed.![zoomlevel-down](https://cloud.githubusercontent.com/assets/5325416/21288709/585b0060-c48a-11e6-9ffd-b6cb33b3bebc.png)

If `window.zoomLevel` is changed in settings.json during runtime, the scrollbar disapears.

Changing fonts or font sizes does change the effective line breaks, but they still try to fit into the same faulty width.

**Comment by kieferrm** [comment] 2016-12-17 18:42
Duplicate of #5745.

**Closed by kieferrm** 2016-12-17 18:42 UTC
