### ISSUE TITLE
Enter button doesn't work

### ISSUE THREAD

**Issue by NabeelMansour** [microsoft/vscode#178879] opened 2023-04-01 11:48 UTC
Type: <b>Performance Issue</b>

Enter button doesn't work

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.62GB free)|
|Process Argv|--crash-reporter-id e211abc1-8ed1-48e3-b87d-15a08ac1485c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   135	 24016	code main
    0	   215	  2324	extensionHost [1]
    0	   114	  3532	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\mikae\.vscode\extensions\pranaygp.vscode-css-peek-4.2.0\server\out\server.js --node-ipc --clientProcessId=2324)
    0	   107	  3664	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\mikae\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=2324)
    0	   112	 23864	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "d:\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=2324)
    0	   234	  4884	window [1] (style.css - 6_month_coding _blueprint - Visual Studio Code)
    0	   114	  5116	fileWatcher [1]
    0	    70	  5676	   utility-network-service
    0	   126	  6320	shared-process
    0	   101	 14368	     ptyHost
    0	    91	 16596	window [2] (Issue Reporter)
    0	    52	 16684	   crashpad-handler
    0	   181	 25472	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (style.css - 6_month_coding _blueprint - Visual Studio Code)
|    Folder (6_month_coding _blueprint): 20 files
|      File types: jpg(13) css(2) html(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
bracket-pair-colorizer-2|Coe|0.2.4
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.4.0
vscode-styled-components|die|0.1.33
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.7.4
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
live-sass|gle|6.0.4
rest-client|hum|0.25.1
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
vscode-language-babel|mgm|0.0.38
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
powershell|ms-|2023.3.3
vsliveshare|ms-|1.0.5834
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.25.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
bootstrap4-vscode|the|6.1.0
highlight-matching-tag|vin|0.11.0
quokka-vscode|Wal|1.0.529
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
php-debug|xde|1.32.1
php-pack|xde|1.0.3
vscode-preview-server|yui|1.3.0
material-theme|zhu|3.15.8

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
pythonb192cf:30669361
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by Humayun-glitch** [comment] 2023-04-01 12:40
There are a few potential fixes that you can try:

- One workaround is using “Ctrl + Enter” instead of pressing Enter.

- Another solution is to add "editor.acceptSuggestionOnEnter": "on" or "editor.acceptSuggestionOnEnter": "smart" in your settings.json file. This controls whether suggestions should be accepted on Enter, in addition to Tab, and helps to avoid ambiguity between inserting new lines or accepting suggestions. 

- You can also check if any other software or operating system keyboard shortcut overrides the VS Code shortcut.

**Comment by anastaciom** [comment] 2023-04-02 01:31
I have the same problem the **Enter button does not work** in version `1.77.0`, I had to go back to version `1.76.2`  :disappointed:

> Windows 11 Pro - 22H2 version
>Processor: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz 2.50GHz
>RAM: 32.0 GB (usable: 31.9 GB)

**Comment by Humayun-glitch** [comment] 2023-04-02 02:08
> I have the same problem the **Enter button does not work** in version `1.77.0`, I had to go back to version `1.76.2`  :disappointed:
> 
> > Windows 11 Pro - 22H2 version
> >Processor: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz 2.50GHz
> >RAM: 32.0 GB (usable: 31.9 GB)

I have tried fixing the issue and have made a pull request, lets see what happens.

**Comment by tamuratak** [comment] 2023-04-02 07:12
Duplicate of #178782

Disable the extension, [diegolincoln.vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components)

See https://github.com/microsoft/vscode/issues/178782#issuecomment-1492651359

**Comment by anastaciom** [comment] 2023-04-02 17:59
> Duplicate of #178782
> 
> Disable the extension, [diegolincoln.vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components)
> 
> See [#178782 (comment)](https://github.com/microsoft/vscode/issues/178782#issuecomment-1492651359)

Thank you very much, it worked here

**Closed** 2023-04-03 17:35 UTC
Labels: triage-needed

**Comment by NabeelMansour** [comment] 2023-04-04 20:16
> I have the same problem the **Enter button does not work** in version `1.77.0`, I had to go back to version `1.76.2` 😞
> 
> > Windows 11 Pro - 22H2 version
> > Processor: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz 2.50GHz
> > RAM: 32.0 GB (usable: 31.9 GB)

aha ok, thanks for the tips. I've tried a lot but without luck, so downgrade it is
