### ISSUE TITLE
Create a difference between Open Editors and Tabs

### ISSUE THREAD

**Issue by heliocarbex** [microsoft/vscode#98380] opened 2020-05-22 13:53 UTC
Today the same files appears in the tabs and the Open Editors. I think that should be a difference in these two resources. In the tabs, we want the extreme focus on the job right now. On the Open editors, the relevant files in the work session.

**Comment by isidorn** [comment] 2020-05-26 10:51
What you want is a working sets view, duplicate of already opened issues which you can find if you search for issue tagged with file-exporer and feature-request.

**Closed** 2020-05-26 10:51 UTC
Labels: *duplicate
