### ISSUE TITLE
Intellisense is not context-sensitive!

### ISSUE THREAD

**Issue by hamzaabdullah90** [Microsoft/vscode#43883] opened 2018-02-17 10:14 UTC
- VSCode Version: 1.19.2
- OS Version: Windows 10 1709

Steps to Reproduce:

1. Open any files with a mixed code of two or more different programming languages!
2. Try to hit in Windows `Ctrl + Space` to bring up Intellisense for another programming language other than the specified in the file extension.

Does this issue occur when all extensions are disabled?: N/A (I have to use extensions in order to enable Intellisense).

**Comment by jens1o** [comment] 2018-02-18 07:39
related to https://github.com/Microsoft/vscode/issues/670

**Comment by egamma** [comment] 2018-02-18 13:42
@hamzaabdullah90 please be more specific and provide a snippet that illustrates the problem.

**Comment by hamzaabdullah90** [comment] 2018-02-21 11:02
When I am trying to edit a PHP file and there is an HTML snippet inside I can not get the HTML intellisense I only get the PHP intellisense.

**Comment by egamma** [comment] 2018-02-21 11:11
@hamzaabdullah90 thanks for getting back, this is a duplicate of #670 as pointed out by @jens1o  (thanks).

**Closed by egamma** 2018-02-21 11:11 UTC
Labels: extensions, needs more info
