### ISSUE TITLE
VS Code Server for WSL closed unexpectedly

### ISSUE THREAD

**Issue by markfaine** [microsoft/vscode#77103] opened 2019-07-10 13:41 UTC
Version: 1.37.0-insider (user setup)
Commit: 360e4e4dfa989135f28edc0d6f7e42df33cddf87
Date: 2019-07-10T05:26:12.322Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

## Expected
Open code insiders and it opens the last opened project and initiates the WSL remote connection. 

## Actual
See image:
![vscode-error](https://user-images.githubusercontent.com/949949/60972640-47143900-a2ec-11e9-8186-78cb5c3c2256.png)

## Reproducible steps
1. CTRL-SHIFT-p
1. Type: Remote-WSL-New Window and ENTER

Or any action that would result in a WSL Remote session started.

The issue seems to be that I don't have the command wslpath in my path.  This error happened today for the first time.  This has worked properly up until today and I'm not aware of any changes to my computer.  I don't think that I have ever had the wslpath command, or at least I don't think so.

Extensions are attached:
[extensions.txt](https://github.com/microsoft/vscode/files/3377705/extensions.txt)

**Comment by markfaine** [comment] 2019-07-10 14:03
Reverting the Remote WSL extension to 0.38.7 seems to have fixed the issue, for now. I suppose something changed in 0.38.8 that has broken it for me.  I suspect they are developing the extension with the assumption that we're all running a very recent windows build number.  I would absolutely upgrade my Windows if that were an option, however, it isn't since my company, like many, tends to take their time with Windows updates.  I'll leave this open for now since I'd like to have it moved or tagged however is necessary so that the team that is working on that extension can see it.

**Comment by aeschli** [comment] 2019-07-11 08:42
duplicate of #77055.
I've released an update yesterday (0.38.9) with a fix for it. Please let me know in #77055 if this works for you or if there's still an issue.

**Closed by aeschli** 2019-07-11 08:42 UTC
