### ISSUE TITLE
code formatting

### ISSUE THREAD

**Issue by mg1075** [Microsoft/vscode#17310] opened 2016-12-15 14:59 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|nativescript|Telerik|0.5.1|

---

Steps to Reproduce:
I just updated to the latest version of vscode (1.8) today.

When I formatted (Alt + Shift + F) code for a .html page,
the results were **unexpected**, not properly aligned, and 
**not** the behavior of code formatting prior to 1.8.

The .html page is a part of an ionic 2 project and so has 
ionic 2 components along with typical html elements such as `<div>`.

**Comment by mg1075** [comment] 2016-12-15 15:02
Looks like this may be a duplicate issue,
because yes, some of the html I'm using also has inline styles.

vscode does fine with this:
```
<div>
    <div>
        <div>
            <div></div>
        </div>
    </div>
</div>
```

...but it bombs on this:
```
<div>
    <div>
        <div style="width: 40px;">
            <div></div>
        </div>
    </div>
</div>
```

...by turning it into this:
```
<div>
    <div>
        <div style="width: 40px;">
<div></div>
</div>
</div>
</div>
```

**Comment by marpereira** [comment] 2016-12-15 15:25
Duplicated:
#17267
#17309

**Comment by kieferrm** [comment] 2016-12-15 19:23
Duplicate of #17267.

**Closed by kieferrm** 2016-12-15 19:23 UTC
