### ISSUE TITLE
Unable to debug [Codespaces extension]

### ISSUE THREAD

**Issue by fara-nak** [microsoft/vscode#127562] opened 2021-06-29 20:26 UTC
**repro steps:**
1- in latest  vscode-insider version install github-codespaces extension
2-  create a codespaces out of Cascade repo:  https://devdiv.visualstudio.com/DevDiv/_git/Cascade
3- navigate to cascade/vscode/codespaces
4- try debugging this code

**expected:**
-you should be able to debug with no error

**actual:**
-cannot load codespaces extension due to following error:
![image](https://user-images.githubusercontent.com/48534922/123879995-9ea37900-d8f6-11eb-96cb-ba6a2ab4d8a4.png)

workaround for this one based on Liveshare [doc](https://github.com/microsoft/vssaas-planning/blob/main/docs/Collaboration/GettingStarted/liveshare-in-codespaces.md#manually-enable-proposed-apis):

in windows, set the `enableProposedApi `to 1 in **remoteExtensionHostProcess.js** file

5- try debugging again after the workaround, another vscode insider would pop up, go to remote explorer
6- try creating another codespaces here(in the debugging session) OR try deleting one of the existing codespaces if you have any

**expected:**
-you should be able to run all the codespaces commands (add, delete and etc)

**actual:**
- there is a warning and all commands fail with error: cannot read property 'X' of undifiend.
* X can be different based on which command you've tried to run.
![image](https://user-images.githubusercontent.com/48534922/123880379-5fc1f300-d8f7-11eb-93e2-17af5ad08f28.png)

![image](https://user-images.githubusercontent.com/48534922/123880397-6f413c00-d8f7-11eb-814b-7c42d2644292.png)

**Comment by aishwaryabh** [comment] 2021-06-29 20:37
I'm having a similar issue with debugging on vs code codespaces extension. I also can't connect to a codespace that I created on the web and get this error when trying to connect via the extension development host:
![image](https://user-images.githubusercontent.com/37918412/123864019-19f93080-d8df-11eb-96ff-5e52492b8f4d.png)

**Comment by weinand** [comment] 2021-06-29 23:14
I don't understand how and what you are debugging. None of the errors your are seeing is related to debugging. Please explain with reproducible steps.

**Comment by aishwaryabh** [comment] 2021-06-29 23:29
So when we are trying to debug on vscode for developing the codespaces extension the following appears on the screen and we are not able to access the extension itself.
![image](https://user-images.githubusercontent.com/37918412/123879332-9e56ae00-d8f5-11eb-93b0-50698fd2a096.png)

To fix this, we did the following: Open `extensionHostProcess.js` from C:\Users\USERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node. Search for nullextensiondescription and change enableProposedAPI to 1.

After doing this change we are now able to access the codespaces extension from codespaces. However, running any other command on a codespace causes another issue where we can't run any other commands on a codespace (such as create, delete, connect) like Fara mentioned.

**Comment by fara-nak** [comment] 2021-06-29 23:33
@weinand updated the description

**Comment by fara-nak** [comment] 2021-07-01 05:37
@weinand please let us know if you need more details. maybe we can jump in a call to look at this? this is blocking us for debugging entirely so we would appreciate some attentions here

**Comment by weinand** [comment] 2021-07-01 09:58
@fara-nak how do I create a codespaces out of Cascade repo?

I think an error message with a name `nullExtensionDescription` and patching the `extensionHostProcess.js` seems a bit fishy. So I think there is already a problem with extension loading and activation. 

@alexdima do you have an idea what's going on?

**Comment by alexdima** [comment] 2021-07-01 11:25
[This error message](https://github.com/microsoft/vscode/issues/127562#issuecomment-870984449) indicates to me that the extension host is unable to correlate the invocation of `require('vscode')` that your extension does with your extension identifier. Internally, this works by throwing an error and looking at the call stack for `require('vscode')`. It looks at the top file on the call stack and tries to find which extension folder contains that file. When that fails, [it logs a warning in the extension host log](https://github.com/microsoft/vscode/blob/8378fa3af20c4433b22b70c6e8d3b6c0b613f797/src/vs/workbench/api/common/extHostRequireInterceptor.ts#L116-L122).

@fara-nak @aishwaryabh Could you please share your extension host log so we can see if there is such a mis-matched require call? (`F1 > Developer: Show Logs... > Extension Host`).

cc @jrieken for ideas

**Comment by jrieken** [comment] 2021-07-01 12:16
>  Internally, this works by throwing an error and looking at the call stack for require('vscode'). It looks at the top file on the call stack and tries to find which extension folder contains that file. When that fails, it logs a warning in the extension host log.

No error-throwing, but using the [path of the file](https://github.com/microsoft/vscode/blob/edf387a2e8ffcec690d050c57dbc1f97c1b7169b/src/vs/workbench/api/node/extHostExtensionService.ts#L27) that's calling `require`. @fara-nak @aishwaryabh Do you use a node_modules that calls `require('vscode')` which is outside of your extension's install location? Like a sym-link?

**Comment by weinand** [comment] 2021-07-01 12:30
@jrieken I'm not sure whether the following links in the package.json qualify as sym-links:

<img width="560" alt="2021-07-01_14-25-53" src="https://user-images.githubusercontent.com/1898161/124124127-5d3ad700-da78-11eb-8a2e-14057bb95b57.png">

**Comment by jrieken** [comment] 2021-07-01 12:39
It's the first time that I see `link` as protocol/scheme. Couldn't find docs but I assume that's like `npm link` which has this exact issue...

**Comment by fara-nak** [comment] 2021-07-01 16:14
@alexdima here is the log for extensionHost: 
```
[2021-07-01 09:09:28.256] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-07-01 09:09:28.257] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-07-01 09:09:28.402] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-07-01 09:09:28.402] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-07-01 09:09:28.439] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl-recommender","_lower":"ms-vscode-remote.remote-wsl-recommender"},"activationEvent":"onStartupFinished"}
[2021-07-01 09:09:28.439] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode-remote.remote-wsl-recommender/dist/extension.js
[2021-07-01 09:09:28.586] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-07-01 09:09:28.587] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-07-01 09:09:28.595] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-07-01 09:09:28.596] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/.vscode-insiders/extensions/esbenp.prettier-vscode-8.0.1/dist/extension
[2021-07-01 09:09:31.950] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onStartupFinished"}
[2021-07-01 09:09:31.950] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.58.2/dist/extension
[2021-07-01 09:09:33.053] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"GitHub.codespaces","_lower":"github.codespaces"},"activationEvent":"api"}
[2021-07-01 09:09:33.053] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github-authentication/dist/extension.js
[2021-07-01 09:09:34.154] [exthost] [info] ExtensionService#_doActivateExtension waderyan.gitblame {"startup":false,"extensionId":{"value":"waderyan.gitblame","_lower":"waderyan.gitblame"},"activationEvent":"onStartupFinished"}
[2021-07-01 09:09:34.155] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/.vscode-insiders/extensions/waderyan.gitblame-7.0.6/dist/index
[2021-07-01 09:09:34.300] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-07-01 09:09:34.300] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-07-01 09:09:35.609] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":false,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-07-01 09:09:35.609] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/fanasiri/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github/dist/extension.js
[2021-07-01 09:09:39.903] [exthost] [error] Activating extension GitHub.codespaces failed due to an error:
[2021-07-01 09:09:39.903] [exthost] [error] Error: [nullExtensionDescription]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api nullExtensionDescription
    at m (c:\Users\fanasiri\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:90195)
    at Object.d [as checkProposedApiEnabled] (c:\Users\fanasiri\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:90142)
    at Object.registerRemoteAuthorityResolver (c:\Users\fanasiri\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:36025)
    at Object.registerResolver (c:\Cascade\vscode\codespaces\out\src\abstractions\node\src\abstractions\node\resolver.ts:66:26)
    at activate (c:\Cascade\vscode\codespaces\debug\src\src\extension.ts:123:29)
[2021-07-01 09:09:42.269] [exthost] [info] eager extensions activated
```

**Comment by fara-nak** [comment] 2021-07-01 16:17
from anotjer conversation related to proposedApi issue:
 
`LiveShare regularly runs into this - it happens if the extension project is referencing some other library and the library happens to use a proposed API - VSCode walks up the tree and finds the package.json for that project and tries to the extension ID from there which is null and it complains that the nullExtension doesn't have proposed APIs enabled. `

cc  @alyssajotice

**Comment by alyssajotice** [comment] 2021-07-01 16:22
Here is some additional information: https://github.com/microsoft/vscode/issues/106968. Live Share works around this by setting the `enableProposedAPI` flag in extensionHostProcess.js.

**Comment by jrieken** [comment] 2021-07-01 16:25
> Live Share works around this by setting the enableProposedAPI flag in extensionHostProcess.js.

Which is only half a fix because the instance of the vscode-module that your extension is working with is still wrong. So, all instance specific stuff, like extension storage etc, will be wrong

**Comment by fara-nak** [comment] 2021-07-01 19:36
@jrieken are you referring to using webpack? this would be really hard to to do that to test any new tests. we used to be able to debug using proposedAPI, what has changed that broke debugging? 

also I still don't understand why the work around (although it is fishy) breaks the extension? I think @alyssajotice is doing same workaround for Liveshare and she is able to debug Liveshare so this is breaking codespaces only.

**Comment by weinand** [comment] 2021-07-01 21:14
I'm not aware of any changes in debugging that would cause this breakage. 

Are you able to hit a breakpoint in the "activate" function of your codespaces extension?

**Comment by connor4312** [comment] 2021-07-01 21:19
I don't think this is influenced by js-debug. Launching and activation is handled by core.

**Comment by jrieken** [comment] 2021-07-02 06:41
>  we used to be able to debug using proposedAPI, what has changed that broke debugging?

Sorry, but nothing has changed. This is an old and inherent limitation of requiring the vscode module. All callers of `require('vscode')` must be in files that are inside the extensions directory. If that's not the case many things are broken, namely: proposed API, extension storage, extension context and others. It just happens to be that lack of proposed API is the most obvious. 

Closing this as a dupe of https://github.com/microsoft/vscode/issues/124820

**Closed by jrieken** 2021-07-02 06:41 UTC
Labels: debug, needs more info
