### ISSUE TITLE
emmet abreviation

### ISSUE THREAD

**Issue by thiagohc20** [microsoft/vscode#154425] opened 2022-07-08 00:49 UTC
after update 1.6.9 emmet multiplication doesnt work

li*4 doesnt work

**Comment by pralima87** [comment] 2022-07-08 04:13
yeah it also stopped working for me. Not only with multipliers but other symbols too.
When typing ul> the ">" hides the abreviation window

Man I just lost 3 hours trying to fix this. Was driving me insane.

using TAB emmet.triggerExpansionOnTab will trigger the abreviation regardless

**Comment by thiagohc20** [comment] 2022-07-08 04:32
lol

I was thinking my vscode had broken
but i did downgrade for 1.6.7 and fixed.
De: pralima87 ***@***.***>
Enviado: sexta-feira, 8 de julho de 2022 02:13
Para: microsoft/vscode ***@***.***>
Cc: thiagohc20 ***@***.***>; Author ***@***.***>
Assunto: Re: [microsoft/vscode] emmet abreviation (Issue #154425)


yeah it also stopped working for me. Not only with multipliers but other symbols too.
When typing ul> the ">" hides the abreviation window

Man I just lost 3 hours trying to fix this. Was driving me insane.

using TAB emmet.triggerExpansionOnTab will trigger the abreviation regardless

**Comment by davidbdeath** [comment] 2022-07-08 04:50
I am experiencing the same issue.

**Comment by gjsjohnmurray** [comment] 2022-07-08 06:35
Related to #154375

**Comment by niaskywalk** [comment] 2022-07-08 06:58
Also broken for me. Rolling back to 1.38.1 fixed the issue.

While I was on 1.69.0, `li*3`, `.class-name*3` and `!` would only work when triggering manually with `ctrl-space`. However, oddly, the multiplier (*), plus(+) and greater-than(>) symbols worked when I kept typing through to the next element command, but not by itself.

**Comment by rzhao271** [comment] 2022-07-12 16:24
Duplicate of https://github.com/microsoft/vscode/issues/154375

**Closed by rzhao271** 2022-07-12 16:24 UTC
