### ISSUE TITLE
TypeScript keeps removing/adding my project

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33776] opened 2017-09-04 08:03 UTC
I have noticed this since we have switched to 2.5.1/2. When ever I switch files it takes very long to get quick outline again. Having the (`terse`) log, I see that TypeScript keeps removing and opening the project. 

[Archive.zip](https://github.com/Microsoft/vscode/files/1274005/Archive.zip)

<img width="780" alt="screen shot 2017-09-04 at 10 02 13" src="https://user-images.githubusercontent.com/1794099/30017133-3896de0c-9158-11e7-91ea-c159d0c087bc.png">

**Comment by jrieken** [comment] 2017-09-04 08:17
This happens in a multi root and single root setup

**Comment by mjbvz** [comment] 2017-09-04 19:31
This seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/17385 that Kai reported (see Andy's comment)

We've brought this up to the TS team a few times but there was not enough understanding of the problem to get a fix in for 2.5. I'll make sure this is still being investigated

**Comment by jrieken** [comment] 2017-10-02 14:33
Sorry, re-opening this as it's pretty obvious we are being ignored by the TypeScript folks and because this is major PITA. @mjbvz How about you just not sending close-event immediately but with a Nsec-delay?

Just to be clear. This happens not just after closing the last file but also while switching between two files. And this is the sequence of death and doom:

* don't use tab
* open a single file from our huge repo
* use Cmd+P to go to another file from history
* the `close`-event is being send *before* the `open`-event is being send

```
lias","kindModifiers":"","spans":[{"start":{"line":8,"offset":8},"end":{"line":8,"offset":11}}]}]}}
Info 43   [16:26:49.963] request: {"seq":11,"type":"request","command":"close","arguments":{"file":"/Users/jrieken/Code/vscode/src/vs/workbench/parts/files/common/explorerModel.ts"}}
Info 44   [16:26:49.967] remove project: /Users/jrieken/Code/vscode/src
```

**Comment by mjbvz** [comment] 2017-10-03 02:58
@jrieken This should be addressed by the work the TS team has been doing to improve file watching with TypeScript 2.6. They were not comfortable taking the fix in for TS 2.5.3. I'll remind them of this specific issue at our next sync up and let you know once we have a build of TS with the fix

**Comment by jrieken** [comment] 2017-10-03 06:33
> @jrieken This should be addressed by the work the TS team has been doing to improve file watching with TypeScript 2.6.

I know that but it hasn't happened in four weeks and there is easy workaround on our side. So why aren't we pragmatic?

**Comment by mjbvz** [comment] 2017-10-12 00:10
@jrieken and @kieferrm Can you please try installing `typescript@next` into your vscode workspace and seeing if you still run into this problem?

I just tested it by disabling tabs and switching between a number of files. With typescript@next, I no longer see the same performance issues when opening new files

**Comment by mjbvz** [comment] 2017-10-20 20:42
Closing out since I have not heard anything about this occurring with TS 2.6

**Closed by mjbvz** 2017-10-20 20:42 UTC
Labels: bug, important, needs more info, typescript, upstream
