### ISSUE TITLE
Git Lens extension stopped working on latest insiders

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#31048] opened 2017-07-19 14:50 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (9a308d1128df9af90e84b2988bce4f57f885b1c3, 2017-07-19T06:40:44.535Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.1
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
atom-keybindings|ms-|2.9.1
stylelint|shi|0.27.0

---

Quite popular (350K) and 5-starred extension Git Lens doesn't work with the latest insiders build anymore.

Steps to Reproduce:

1. Launch VS Code  with the installed Gitlens extension https://github.com/eamodio/vscode-gitlens/
2. Notice that the extension doesn't work anymore: it doesn't show in the status bar the author of the current line, doesn't show blame output, doesn't provide many of its features in via the command palette.

I bisected the recent VS Code changes and here's the commit that breaks the extension: 531b6b1c219fb4b18df6a429d19ed2649c2c61ac

**Comment by jrieken** [comment] 2017-07-20 07:50
dupe of #31038

**Comment by vvs** [comment] 2017-07-20 10:02
I've built VS Code from the latest master sources and unfortunately, that fix for #31038 didn't fix this issue.

Most of the Git Lens functionality continues to be disabled and not available.

**Comment by jrieken** [comment] 2017-07-20 10:25
Yeah, I see that two. Might not be a duplicate then

**Comment by eamodio** [comment] 2017-07-20 10:30
My guess is it might havee something to do with the Uri changes to use readonly fields. Because my `GitUri` class extends `Uri` and tries setting those private props -- [see here])https://github.com/eamodio/vscode-gitlens/blob/master/src/git/gitUri.ts#L21)

**Comment by jrieken** [comment] 2017-07-20 10:37
> Because my GitUri class extends Uri and tries setting those private props

😲 Hm, sorry for breaking you, tho please use private properties. The refactoring was about slimming down the `URI` class. You might be able to easily fix this, since the (not public) ctor now allows to set those fields. Tho you are on thin ice with this.

**Comment by jrieken** [comment] 2017-07-20 12:13
@eamodio Not pretty, but replacing the explicit assignments with this makes this work (test it with insiders and stable)

```
        const base = this as any;
        for (const key in uri) {
            if (uri.hasOwnProperty(key)) {
                base[key] = (uri as any)[key];
            }
        }
```

[patch.txt](https://github.com/Microsoft/vscode/files/1162212/patch.txt)

**Comment by eamodio** [comment] 2017-07-20 12:19
@jrieken thanks! I'm not in front of a computer atm so I can't really check it out. Do you think that method is better than calling the other ctor? Or maybe until 1.15 becomes stable. If you wouldn't mind creating a PR that would be great. I'll try to get that in tonight.

**Comment by jrieken** [comment] 2017-07-20 12:22
> Do you think that method is better than calling the other ctor?

No, calling the ctor is better but until insiders and stable aren't equal you must have some graceful code that handles both (`_scheme` and `scheme`-getter as well as `scheme` etc).

**Comment by eamodio** [comment] 2017-07-20 12:27
Yeah. That makes sense. Thanks again!

**Comment by jrieken** [comment] 2017-07-20 12:35
There you go: https://github.com/eamodio/vscode-gitlens/pull/121. Should be OK, please give it a try tho. Especially considering that I have created this PR entirely in the web 😱

**Comment by vvs** [comment] 2017-07-20 12:57
The proposed PR works for me on the insiders build. Thanks1

**Comment by fjsuarez** [comment] 2017-07-20 17:42
Sorry for the newb question, can you please give instructions or a link on how to compile and install your patched branch?

**Comment by eamodio** [comment] 2017-07-20 17:54
@fjsuarez I will release a new GitLens tonight with the patch

**Comment by eamodio** [comment] 2017-07-20 20:49
v4.3.2 is out with the patch -- thanks again @jrieken 

I think this can be closed now.

**Comment by jrieken** [comment] 2017-07-21 07:32
Thanks everyone! Happy Coding!

**Closed by jrieken** 2017-07-21 07:32 UTC
Labels: caused-by-extension, extensions, insiders

**Comment by takato1314** [comment] 2017-10-19 06:49
Hi all, i am getting this same issue where all the features of Git Lens are not working at all after i upgraded my VSCode just recently. Below are the VSCode version that i am using:

<img width="183" alt="2017-10-19_14-40-09" src="https://user-images.githubusercontent.com/10910968/31757667-7cd7575c-b4dc-11e7-836d-1b22cd6cba13.png">

Before the update it is working as usual. Also, I am using Git Lens version 5.6.5.

**Comment by eamodio** [comment] 2017-10-19 07:07
@takato1314 its probably best to open this issue on the GitLens repo: https://github.com/eamodio/vscode-gitlens/issues
Although I'm am unable to reproduce any issues with the latest vscode (stable or insiders). You might want to try uninstalling GitLens completely and then re-installing it to see if that helps.

**Comment by vvs** [comment] 2017-10-19 07:12
@takato1314 FWIW, the latest insiders build of VS Code works with no issue with the latest GitLens (5.6.5) for me.

**Comment by takato1314** [comment] 2017-10-19 13:15
@eamodio and @vvs, thanks for the advice. Strangely enough completely uninstall and reinstall the extension does get everything working again. 

@eamodio I didnt thought of opening an issue in the vscode-gitlens repo because initially it was working fine before the VsCode upgrade, but after reinstalling as you suggested helps.
