### ISSUE TITLE
Test contributing timeline providers from extensions

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89385] opened 2020-01-27 22:24 UTC
Refs: #84297

- [ ] anyOS @Tyriar
- [x] anyOS @sbatten

Complexity: 4

---

## Testing

Extensions can now contribute timeline providers to show time-series information in a new _Timeline_ view in the Explorer sidebar.

Develop an extension that can contribute a `TimelineProvider` to provide time-series information given a `Uri`. Here is an [example provider](https://github.com/microsoft/vscode/blob/4f42834c994f9d98cecad705ea585c19fa7b1b0f/extensions/git/src/timelineProvider.ts).

Here is the current API declarations:
https://github.com/microsoft/vscode/blob/4f42834c994f9d98cecad705ea585c19fa7b1b0f/src/vs/vscode.proposed.d.ts#L1473-L1565)

- Make sure there is a command contributed to each timeline item for the on click action.
- Try making a provider take a while and make sure the view shows an indication of progress/loading
- Try updating provider data after initial load (using `onDidChange`) and ensure the view is updated
- For extra points, try setting `replaceable` to `true` and then register a replacement provider using the same `source` -- it should replace the existing one. Also try the same thing without setting `replaceable` (or set to `false`) and the second registration should error out.

# Notes

- The `DocumentSelector` as part of the `registerTimelineProvider` call isn't yet honored
- You cannot (yet) attach context menus to timeline items

**Comment by Tyriar** [comment] 2020-01-28 16:54
I can't get the API to work. With the following ext code:

```ts
import * as vscode from 'vscode';

const backups: { [uri: string]: string[] } = {};

export function activate(context: vscode.ExtensionContext) {
	console.log('activate');
	context.subscriptions.push(vscode.workspace.onDidSaveTextDocument(d => {
		const uri = d.uri.toString();
		if (backups[uri] === undefined) {
			backups[uri] = [];
		}
		backups[uri].push(d.getText());
		console.log('backed up');
	}));
	const changeEmitter = new vscode.EventEmitter<vscode.Uri | undefined>();
	context.subscriptions.push(vscode.workspace.registerTimelineProvider('*', {
		source: 'my-magical-timeline-provider',
		sourceDescription: 'My magical timeline provider',
		provideTimeline: (uri: vscode.Uri, token: vscode.CancellationToken) => {
			console.log('provide');
			const result: vscode.TimelineItem[] = [
				new (vscode.TimelineItem as any)('rawr', Date.now())
			];
			return result;
		},
		onDidChange: changeEmitter.event
	}));
}
```

backed up gets logged but not provide:

![image](https://user-images.githubusercontent.com/2193314/73285987-b6c81380-41ab-11ea-9f93-f86c5d19d129.png)

**Comment by Tyriar** [comment] 2020-01-29 13:40
Tried again and still having problems, closing off as I'm blocked. Hopefully the root cause of the problem will surface before the API is stabilized.

**Closed by Tyriar** 2020-01-29 13:40 UTC
Labels: testplan-item
