### ISSUE TITLE
Errors shown in the message box are always also printed to the console

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#32138] opened 2017-08-08 12:20 UTC
in the hello extension add this code:
```
vscode.workspace.openTextDocument('/foobar/info.txt').then(doc => vscode.window.showTextDocument(doc), err => vscode.window.showInformationMessage(err.message));
```
Make sure that '/foobar/info.txt' **does not** exist.
Run the extension and trigger the 'hello' action.

Observe annoying exception in dev tools:
![2017-08-08_14-18-38](https://user-images.githubusercontent.com/1898161/29071583-8adbbd78-7c44-11e7-8029-c132a5227025.png)

Since the error is handled in a perfectly fine way, It is confusing for a developer that the dev tools open and show an exception stack trace.

**Comment by jrieken** [comment] 2017-08-14 09:53
Unsure who prints that...

**Comment by jrieken** [comment] 2017-08-14 10:54
The error is handle [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadDocuments.ts#L213) and forwarded to the extension host (visible by it being able to show the message bar). There must be another error that isn't handled

**Comment by bpasero** [comment] 2017-08-15 10:59
At one point (a long time ago) we decided to always print an error that is shown in the message box also in the console to see the full stack of the error. The printing happens here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/message/browser/messageService.ts#L125

I actually do not know if there is a benefit from having this. Since the console is for developers and not for our users I think this is never something that a user cares about. We have to decide for us if we want to keep this behaviour or not. I do not mind either way.

**Comment by bpasero** [comment] 2017-11-15 17:56
Closing "as designed".

**Closed by bpasero** 2017-11-15 17:56 UTC
Labels: under-discussion, workbench
