### ISSUE TITLE
Can't create a blade file

### ISSUE THREAD

**Issue by Alyousfi** [Microsoft/vscode#57340] opened 2018-08-28 08:36 UTC
Issue Type: <b>Bug</b>

It treats the 'blade' in .blade.php as a part of the name as opposed to a file format!

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|4.00GB (0.03GB free)|
|Process Argv|/Users/ibrahimA/Downloads/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_3961799|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by dbaeumer** [comment] 2018-08-28 08:47
So `.blade.php` should be treated as a single extension. 

@bpasero not sure if this is workbench or editor. Starting with workbench.

**Comment by bpasero** [comment] 2018-08-28 08:57
@Alyousfi can you state the exact steps you are doing?

**Comment by isidorn** [comment] 2018-08-29 13:43
Let's treat it as a duplicate of https://github.com/Microsoft/vscode/issues/56812
And rename that one

**Closed by isidorn** 2018-08-29 13:43 UTC
Labels: file-explorer
