### ISSUE TITLE
'Replace' function work not good in editor

### ISSUE THREAD

**Issue by wdianfengshan** [microsoft/vscode#193898] opened 2023-09-24 03:29 UTC
Type: <b>Feature Request</b>

Platform: MacOS 12.6.8
I use 'cmd+F' to search and replace the words in editor (e.g. jupyter). But when I click the botton 'Replcace' to replace a word by another, the search match (in a rectangle box) will jump to the first match (looks like it search again). But I want it to jump to the next word matched. 
I wonder it is my mistakes or bug?

VS Code version: Code 1.82.2 (Universal) (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin arm64 21.6.0
Modes:

**Comment by amunger** [comment] 2023-12-14 17:26
duplicate of https://github.com/microsoft/vscode/issues/190575

**Closed by amunger** 2023-12-14 17:26 UTC
Labels: editor-find, under-discussion
