### ISSUE TITLE
Middle click in the Replace section of Find/Replace dialog pastes into the main document

### ISSUE THREAD

**Issue by decuman** [microsoft/vscode#53635] opened 2018-07-06 02:45 UTC
When middle clicking in the **replace** section of the  _find and replace_ dialog pastes into the main window at a current cursor position instead. Middle click pasting into the **find** section of the dialog works fine. Ctrl+C/Ctrl-V paste works fine in both input fields.

- VSCode Version: 1.25.0
- OS Version: Linux 64-bit Kubuntu 16.04

Steps to Reproduce:

1. Create an empty tab
2. Copy any text with a mouse selection
3. Open Find/Replace dialog
4. Middle click to paste into **Replace** section

Does this issue occur when all extensions are disabled?: Yes

**Comment by glcraft** [comment] 2018-07-06 11:54
It does the same thing if I try to close tab by middle click it.

**Comment by alexandrudima** [comment] 2018-07-27 10:37
I cannot reproduce this:

![kapture 2018-07-27 at 12 36 44](https://user-images.githubusercontent.com/5047891/43316471-c3a10224-9199-11e8-8aa0-bdd2b75694b2.gif)

**Comment by decuman** [comment] 2018-07-27 12:31
Middle click to paste into Replace section. You’re pasting into Find section

**Comment by alexandrudima** [comment] 2018-07-30 11:01
Thanks @decuman I can reproduce when middle clicking in the replace field.

**Comment by cician** [comment] 2018-09-16 10:17
I'm also on Kubuntu 16.04 and it doesn't happen with the replace field in VSCode 1.27.2, but I have the same problem when middle clicking on the scroll minimap and more importantly when closing a tab with middle click. I constantly have to undo accidental changes due to unwanted pastes. Combined with issue #49305 it gets really annoying.

**Comment by suzetmk** [comment] 2019-02-27 01:52
@cician 
OK, I've found one bug here. The middle-click on tree view should stop propagation as same as find box.
Patch would be something like this.

```diff
diff --git a/src/vs/base/parts/tree/browser/treeDefaults.ts b/src/vs/base/parts/tree/browser/treeDefaults.ts
index 8d30a79..f2e24e1 100644
--- a/src/vs/base/parts/tree/browser/treeDefaults.ts
+++ b/src/vs/base/parts/tree/browser/treeDefaults.ts
@@ -142,6 +142,11 @@ export class DefaultController implements _.IController {
 				}
 			}
 
+			// on linux, middle key does pasting.
+			if (event.middleButton) {
+				event.stopPropagation();
+			}
+
 			// Propagate to onLeftClick now
 			return this.onLeftClick(tree, element, event, origin);
 		}

```

**Comment by leongor** [comment] 2019-05-08 08:36
It's very annoying issue for me as I use selection clipboard intensively.
Is there a solution for it?

**Comment by escaner** [comment] 2019-08-16 12:00
It would be nice if these bugs get fixed in Linux. This is the main way of copy & paste in X11: select and middle click with mouse. No need to press slow copy and paste key combos as in Windows.

**Comment by alexandrudima** [comment] 2019-10-11 08:10
I cannot reproduce this anymore, middle clicking in the replace field does not trigger a selection paste in the editor:

![Kapture 2019-10-11 at 10 09 39](https://user-images.githubusercontent.com/5047891/66635338-48b50c00-ec0f-11e9-81b9-21188210f90b.gif)

**Closed by alexandrudima** 2019-10-11 08:10 UTC
Labels: bug, linux

**Comment by decuman** [comment] 2019-10-11 21:51
Unfortunately, still have this issue present in the latest vscode 1.39.1 version
Despite switching to a newer OS Version: Linux 64-bit Kubuntu 18.04

**Comment by escaner** [comment] 2019-10-11 22:11
For me it is the same as this one https://github.com/microsoft/vscode/issues/67671:
Still present in 1.39.1, but fixed in the 1.40.0-insider version from https://code.visualstudio.com/insiders/

**Comment by alexandrudima** [comment] 2019-10-11 22:49
@decuman Could you please also try with the latest insiders?

**Comment by decuman** [comment] 2019-10-11 23:07
Yes. Confirm that the middle click paste works fine with the latest insiders version.
