### ISSUE TITLE
DOES NOT START...

### ISSUE THREAD

**Issue by wibeebee** [Microsoft/vscode#58020] opened 2018-09-06 00:47 UTC
- VSCode Version: 1.27.0
- OS Version: Win10 v1803 (17134.228)

Steps to Reproduce:

HELP ME....

1. 
[180906_error_log.txt](https://github.com/Microsoft/vscode/files/2355041/180906_error_log.txt)

2.
![image](https://user-images.githubusercontent.com/43019892/45128601-d4ad6680-b1b9-11e8-978c-97c5053d66b6.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by nuintun** [comment] 2018-09-06 02:38
Same issue, this issue caused by user folder contains non ASCII characters.

**Comment by bpasero** [comment] 2018-09-06 05:10
Marking as duplicate of https://github.com/Microsoft/vscode/issues/57982

@nuintun thanks for saying that, it seems to be the issue.

**Closed by bpasero** 2018-09-06 05:10 UTC
Labels: new release
