### ISSUE TITLE
VSCode terminal doesn't allow/request permissions to access media devices

### ISSUE THREAD

**Issue by jvanheugten** [microsoft/vscode#95062] opened 2020-04-12 18:54 UTC
- VSCode Version: 1.44.0
- OS Version: Max OSX Catalina 10.15.2

Steps to Reproduce:

1. Run this python script in the VSCode terminal which needs access to the camera:
```
import cv2

cam = cv2.VideoCapture(0)
print(cam.isOpened())
cam.release()
```

The result will be `Abort trap: 6`. This also occurs if you try to run the debugger.
The script does work in the Mac Terminal and iTerm.

This is likely because vscode does not have permissions to access the camera. There is no way to force vscode to appear in the Mac permissions (Security & Privacy -> Privacy -> Camera), such that it cannot be enabled by the user.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jvanheugten** [comment] 2020-04-12 18:58
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [camera authority in macOS 10.15 (#93130)](https://www.github.com/microsoft/vscode/issues/93130)

Probably both issues have similar origin, namely camera permissions are not set for vscode.

**Comment by deepak1556** [comment] 2020-04-13 22:09
@jvanheugten your assumption is correct. But if your macOS terminal app got the permissions to access camera, then any process spawned from it should get that. I am unable to reproduce the crash with the terminal from inside code after I grant the terminal access to camera.

Can you share a video demo ?

**Comment by jvanheugten** [comment] 2020-04-14 10:23
![image](https://user-images.githubusercontent.com/12444498/79214016-68412180-7e4a-11ea-9154-f6f533eac312.png)
Here is a simple demonstration. Mac OS Terminal shows the correct result, but terminal in VSCode does not.

Does VSCode spawn a emulated terminal? If MacOS thinks it is VSCode that spawns it, I would expect a permission request to access the camera, but that never happens. My privacy settings do show that Terminal has access to the camera, but there is no way to add VSCode to that list.

**Comment by deepak1556** [comment] 2020-04-14 20:13
Have your restarted code after giving your macOS terminal access to camera ? Otherwise code wouldn't pick up the privilege for the terminals it opens.

> Does VSCode spawn a emulated terminal? 

@Tyriar how do we spawn terminals on macOS ?

I tried the following steps and it seems to work , https://streamable.com/zsa8ro

 > My privacy settings do show that Terminal has access to the camera, but there is no way to add VSCode to that list.

Yes you can't do that at the moment, because code doesn't carry the entitlement that requests access to camera. I am looking to avoid adding this unless necessary, but for the current use case through the terminal things should work the way it is.

**Comment by jvanheugten** [comment] 2020-04-14 20:24
Yes, I've restarted vscode a couple of times. I'll try uninstalling and reinstalling it from scratch tomorrow.

**Comment by Tyriar** [comment] 2020-04-15 13:36
@deepak1556 

https://github.com/microsoft/node-pty/blob/cd72d3303cb484e402381741e7e6a613886eda7b/src/unix/pty.cc#L441

**Comment by jvanheugten** [comment] 2020-04-15 14:48
I just completely uninstalled VSCode and re-installed it and restarted my computer. The problem is still there.

I even deleted everything according to similar paths here: https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac

**Comment by jvanheugten** [comment] 2020-04-15 14:54
Just ran VSCode as administrator:
`sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`
Then my terminal in VSCode will run as root and the program executes as normal.

**Comment by deepak1556** [comment] 2020-04-15 19:50
Thanks for the context, based on https://github.com/microsoft/vscode/issues/95062#issuecomment-614044993 since we `execvp`, macOS tcc utility will consider the permissions of the parent process instead of the forked process.

But I am still confused why it wasn't an issue with my setup, moving this next milestone for further investigation.

**Comment by jelling** [comment] 2020-04-27 15:34
Similar issue exists with access to the microphone via Pythoh. In both cases it seems that the VSCode terminal is not requesting permissions from MacOS. I say this because if you run the same CLI command via the built-in MacOS Terminal app then permissions are requested and everything works as it should.

Proposed solution: update VSCode terminal to request permissions from MacOS.

**Comment by deepak1556** [comment] 2020-04-27 18:18
@jelling thanks for the report. the root cause is same. I have updated the bug title.

**Comment by MHDFahz** [comment] 2020-05-06 00:13
I tried all those step but doesn't working

**Comment by becting** [comment] 2020-05-07 22:55
I am having the same issue. Code runs without issue from terminal which is able to request the appropriate permissions. VSCode however does not request permissions as expected.

The output is 
`OpenCV: not authorized to capture video (status 0), requesting...`

**Comment by becting** [comment] 2020-05-07 23:04
> https://streamable.com/zsa8ro

However, when I start VS Code from terminal, it works.

**Comment by deepak1556** [comment] 2020-05-07 23:49
> However, when I start VS Code from terminal, it works.

Thanks for confirming @becting , thats the only workaround available for now.

As I have outlined earlier

```
The underlying issue is the way macOS TCC responsibility chain works, for ex: if you launch some application from macOS Terminal.app directly, TCC will determine Terminal.app to be the responsible process for the purpose of permission prompts, rather than the launched app itself. Unless the app is started through the LaunchServices (Finder/Open) the permission prompts will be attributed to the parent process that started it.

In VSCode, the builtin terminal is launched in a process forked from the main app, so any application launched without the use of launchservices from the terminal will have their permissions attributed to VSCode app which currently doesn't obtain the media device permission, and hence you are seeing the issue mentioned.
```

So to workaround, 

* kill all your running instances of VSCode including any helper process, verify with Activity Monitor
* make sure macOS Terminal.app has media permissions
* start VSCode from Terminal.app `code` or `code-insiders`
* Scripts run from the VSCode terminal that required media access should now work

@jelling @MHDFahz can you verify the above workaround ?

**Comment by jvanheugten** [comment] 2020-05-08 10:13
Yes, it works when executing with `code` from Terminal.

**Comment by DamonQin** [comment] 2020-05-27 10:25
@jvanheugten

**Comment by DamonQin** [comment] 2020-05-27 10:38
@jvanheugten 

Here is my steps.
- os: Catalina 10.15.5

1, There's a sqlite3 db file(TCC.db) in this path:
~/Library/Application Support/com.apple.TCC/
2, Insert a row to table access, like this:
INSERT INTO access VALUES('kTCCServiceMicrophone','com.microsoft.VSCode',0,1,1,NULL,NULL,NULL,'UNUSED',NULL,0,1590575788);
3, Check the permission(Security & Privacy -> Privacy -> Microphone)
4, Restart vscode

Cheers！ 🍺🍺🍺

**Comment by MHDFahz** [comment] 2020-05-27 16:15
Not working

**Comment by Caldeira777** [comment] 2020-07-29 15:24
> Yes, it works when executing with `code` from Terminal.

Are you running VSCode as root? 
I did that and VSCode stopped updating. I don't think that we've got a solution for that yet.

**Comment by Untitleddotpy** [comment] 2020-08-07 17:05
Did anyone find a solution for this?

**Comment by HaoHoo** [comment] 2020-08-10 05:37
I just install sox via brew command line and then prompt me to add Terminal to microphone access Privacy setting.

**Comment by guilhermeandraschko-vakt** [comment] 2020-09-10 22:36
Try to update the folder permissions recursively with: `chmod -R 777 folder`

**Comment by AlCash07** [comment] 2020-09-11 17:01
I have the same issue and it's circumvented by running `code` from Terminal, but still not fixed when I open VScode normally.

**Comment by fandy** [comment] 2020-10-28 10:23
+1 it would be great for VScode to simply request permissions on Mac, so that we don't have to do this workaround.

**Comment by wrogner** [comment] 2020-12-23 18:26
@DamonQin 
> Here is my steps.
> 
> * os: Catalina 10.15.5
> 
> 1, There's a sqlite3 db file(TCC.db) in this path:
> ~/Library/Application Support/com.apple.TCC/
> 2, Insert a row to table access, like this:
> INSERT INTO access VALUES('kTCCServiceMicrophone','com.microsoft.VSCode',0,1,1,NULL,NULL,NULL,'UNUSED',NULL,0,1590575788);
> 3, Check the permission(Security & Privacy -> Privacy -> Microphone)
> 4, Restart vscode
> 

Can you comment on what these parameters do? Specifically the last one is interesting.

**Comment by wrogner** [comment] 2020-12-23 19:21
> 【Abort trap: 6】crashed on macOS , cv2.VideoCapture(0) #96167

Tried to insert above statements (the last parameter is the time stamp).

Did not work:

a. The number of columns has been changed from 12 to 13 (which can be mitigated by adding a NULL value)
b. the TCC.db is read only and cannot be changed to be written.

So, sorry, NO.

The issue still exists

**Comment by wrogner** [comment] 2020-12-25 12:16
Summarizing:
VSCode cannot access the camera or microphone.
In the Security panel of MacOS, under Camera or Mic there is no entry for VSCode to be selectable
There is no way to add VSCode using the standard interface.

None of the suggestions above work (for obvious reasons as most people try around and give up prematurely)

Here is the solution that works and an explanation why:

--- SOLUTION
cd ~/Library/Application Support/com.apple.TCC
cp TCC.db TCC.db_backup
sqlite3 TCC.db
```
> INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
> INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,2,0,1);
> .exit
```

Logout / Login
Check under System Preferences -> Security & Privacy (there should be a VSCode access for both camera and mic)

Test functionality in VSCode
Create a Jupyter NB:

```
import cv2

cam = cv2.VideoCapture(0)
print(cam.isOpened())
cam.release()
```

Run and enjoy
--- EXPLANATION
MacOS requires applications to register for access of sensitive (privacy related) components of the computer.
Therefore it provides a secure part of the OS that can partially be altered in recovery mode (available via cmd-R during boot).

This is not required to fix missing access grants on a per user basis:

Apple maintains a security database that stores the information observable in the System Preferences -> Security & Privacy dialog. This database is stored under ~/Library/Application Support/com.apple.TCC/TCC.db.
It is a simple SQLite3 database.

In TCC.db there are several tables, one of which - access - is relevante (the others are empty).

The access table provides 13 fields of which only the first 6 need be entered. The rest has default values.

A comprehesive list of services can be found here: 

[https://apple.stackexchange.com/questions/339363/how-can-i-remove-applications-from-security-privacy](https://apple.stackexchange.com/questions/339363/how-can-i-remove-applications-from-security-privacy) 

If you need to figure out the internally used client name, use this command:

osascript -e 'id of app “Application name.app”'

Application name.app being the name found in the /Application folder.

**Comment by el-mimoso** [comment] 2021-01-05 20:17
> +1 it would be great for VScode to simply request permissions on Mac, so that we don't have to do this workaround.

Yep just like pyCharm does it but i hate its GUI and need to learn their shortcuts 😢

**Comment by mattialibera** [comment] 2021-01-21 15:59
> Summarizing:
> VSCode cannot access the camera or microphone.
> In the Security panel of MacOS, under Camera or Mic there is no entry for VSCode to be selectable
> There is no way to add VSCode using the standard interface.
> 
> None of the suggestions above work (for obvious reasons as most people try around and give up prematurely)
> 
> Here is the solution that works and an explanation why:
> 
> --- SOLUTION
> cd ~/Library/Application Support/com.apple.TCC
> cp TCC.db TCC.db_backup
> sqlite3 TCC.db
> 
> ```
> > INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
> > INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,2,0,1);
> > .exit
> ```
> 
> Logout / Login
> Check under System Preferences -> Security & Privacy (there should be a VSCode access for both camera and mic)
> 
> Test functionality in VSCode
> Create a Jupyter NB:
> 
> ```
> import cv2
> 
> cam = cv2.VideoCapture(0)
> print(cam.isOpened())
> cam.release()
> ```
> 
> Run and enjoy
> --- EXPLANATION
> MacOS requires applications to register for access of sensitive (privacy related) components of the computer.
> Therefore it provides a secure part of the OS that can partially be altered in recovery mode (available via cmd-R during boot).
> 
> This is not required to fix missing access grants on a per user basis:
> 
> Apple maintains a security database that stores the information observable in the System Preferences -> Security & Privacy dialog. This database is stored under ~/Library/Application Support/com.apple.TCC/TCC.db.
> It is a simple SQLite3 database.
> 
> In TCC.db there are several tables, one of which - access - is relevante (the others are empty).
> 
> The access table provides 13 fields of which only the first 6 need be entered. The rest has default values.
> 
> A comprehesive list of services can be found here:
> 
> https://apple.stackexchange.com/questions/339363/how-can-i-remove-applications-from-security-privacy
> 
> If you need to figure out the internally used client name, use this command:
> 
> osascript -e 'id of app “Application name.app”'
> 
> Application name.app being the name found in the /Application folder.

That works on Big Sur; for Catalina it's enough to use the following lines in sqlite3:
```
> INSERT into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier, flags) VALUES ("kTCCServiceCamera","com.microsoft.VSCoda",0,1,1,"UNUSED",0);
> INSERT into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier, flags) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,1,1,"UNUSED",0);
> .exit
```

PS: it's important you give full access permissions to Terminal in security settings

**Comment by 2xAA** [comment] 2021-02-07 20:29
There's a slight error in the above for Catalina, this will work:

```
> INSERT into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier, flags) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0,1,1,"UNUSED",0);
> INSERT into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier, flags) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,1,1,"UNUSED",0);
> .exit
```

**Comment by csarami** [comment] 2021-02-17 16:37
> > Summarizing:
> > VSCode cannot access the camera or microphone.
> > In the Security panel of MacOS, under Camera or Mic there is no entry for VSCode to be selectable
> > There is no way to add VSCode using the standard interface.
> > None of the suggestions above work (for obvious reasons as most people try around and give up prematurely)
> > Here is the solution that works and an explanation why:
> > --- SOLUTION
> > cd ~/Library/Application Support/com.apple.TCC
> > cp TCC.db TCC.db_backup
> > sqlite3 TCC.db
> > ```
> > > INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
> > > INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,2,0,1);
> > > .exit
> > ```
> > 
> > 
> > Logout / Login
> > Check under System Preferences -> Security & Privacy (there should be a VSCode access for both camera and mic)
> > Test functionality in VSCode
> > Create a Jupyter NB:
> > ```
> > import cv2
> > 
> > cam = cv2.VideoCapture(0)
> > print(cam.isOpened())
> > cam.release()
> > ```
> > 
> > 
> > Run and enjoy
> > --- EXPLANATION
> > MacOS requires applications to register for access of sensitive (privacy related) components of the computer.
> > Therefore it provides a secure part of the OS that can partially be altered in recovery mode (available via cmd-R during boot).
> > This is not required to fix missing access grants on a per user basis:
> > Apple maintains a security database that stores the information observable in the System Preferences -> Security & Privacy dialog. This database is stored under ~/Library/Application Support/com.apple.TCC/TCC.db.
> > It is a simple SQLite3 database.
> > In TCC.db there are several tables, one of which - access - is relevante (the others are empty).
> > The access table provides 13 fields of which only the first 6 need be entered. The rest has default values.
> > A comprehesive list of services can be found here:
> > https://apple.stackexchange.com/questions/339363/how-can-i-remove-applications-from-security-privacy
> > If you need to figure out the internally used client name, use this command:
> > osascript -e 'id of app “Application name.app”'
> > Application name.app being the name found in the /Application folder.
> 
> That works on Big Sur; for Catalina it's enough to use the following lines in sqlite3:
> 
> ```
> > INSERT into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier, flags) VALUES ("kTCCServiceCamera","com.microsoft.VSCoda",0,1,1,"UNUSED",0);
> > INSERT into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier, flags) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,1,1,"UNUSED",0);
> > .exit
> ```
> 
> PS: it's important you give full access permissions to Terminal in security settings

Is there a similar solution for MacOS Mojave?

When I run your code:

sqlite> INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
Error: table access has no column named auth_value

Any one knows a revision of a solution for Mojave, please?

![image](https://user-images.githubusercontent.com/11630582/108235999-6c963500-7114-11eb-9107-5c34f36f3d8a.png)

**Comment by mattialibera** [comment] 2021-02-18 16:53
> > > Summarizing:
> > > VSCode cannot access the camera or microphone.
> > > In the Security panel of MacOS, under Camera or Mic there is no entry for VSCode to be selectable
> > > There is no way to add VSCode using the standard interface.
> > > None of the suggestions above work (for obvious reasons as most people try around and give up prematurely)
> > > Here is the solution that works and an explanation why:
> > > --- SOLUTION
> > > cd ~/Library/Application Support/com.apple.TCC
> > > cp TCC.db TCC.db_backup
> > > sqlite3 TCC.db
> > > ```
> > > > INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
> > > > INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,2,0,1);
> > > > .exit
> > > ```
> 
> Is there a similar solution for MacOS Mojave?
> 
> When I run your code:
> 
> ```
> sqlite> INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES 
> ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
> Error: table access has no column named auth_value
> ```
> 
> Anyone knows a revision of a solution for Mojave, please?
> 
> ![image](https://user-images.githubusercontent.com/11630582/108235999-6c963500-7114-11eb-9107-5c34f36f3d8a.png)

@csarami see solution I posted above: https://github.com/microsoft/vscode/issues/95062#issuecomment-764745144; it should work for Mojave too.

**Comment by csarami** [comment] 2021-02-18 17:23
> > > > Summarizing:
> > > > VSCode cannot access the camera or microphone.
> > > > In the Security panel of MacOS, under Camera or Mic there is no entry for VSCode to be selectable
> > > > There is no way to add VSCode using the standard interface.
> > > > None of the suggestions above work (for obvious reasons as most people try around and give up prematurely)
> > > > Here is the solution that works and an explanation why:
> > > > --- SOLUTION
> > > > cd ~/Library/Application Support/com.apple.TCC
> > > > cp TCC.db TCC.db_backup
> > > > sqlite3 TCC.db
> > > > ```
> > > > > INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
> > > > > INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,2,0,1);
> > > > > .exit
> > > > ```
> > 
> > 
> > Is there a similar solution for MacOS Mojave?
> > When I run your code:
> > ```
> > sqlite> INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES 
> > ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
> > Error: table access has no column named auth_value
> > ```
> > 
> > 
> > Anyone knows a revision of a solution for Mojave, please?
> > ![image](https://user-images.githubusercontent.com/11630582/108235999-6c963500-7114-11eb-9107-5c34f36f3d8a.png)
> 
> @csarami see solution I posted above: [#95062 (comment)](https://github.com/microsoft/vscode/issues/95062#issuecomment-764745144); it should work for Mojave too.

But there are no such attributes as " auth_value, auth_reason, auth_version" in the table in  Mojave.

**Comment by mattialibera** [comment] 2021-02-18 17:31
> > @csarami see solution I posted above: [#95062 (comment)](https://github.com/microsoft/vscode/issues/95062#issuecomment-764745144); it should work for Mojave too.
> 
> @mattialibera But there are no such attributes as " auth_value, auth_reason, auth_version" in the table in Mojave.

@csarami my solution doesn't mention those attributes; below the screenshot:
![image](https://user-images.githubusercontent.com/62540874/108396752-7c4a7200-7217-11eb-852d-67f663329ce3.png)

**Comment by wrogner** [comment] 2021-02-18 17:32
The table structure in Mojave is different to BigSur.

With your qualifications you should be able to figure out the attributes.

**Comment by Naohiro2g** [comment] 2021-02-20 04:45
First of all, there is no need to be in the recovery mode to edit the database but terminal app needs full disk access.

Mojave version is here, at your own risk. Be careful. 

```
cd ~/Library/Application\ Support/com.apple.TCC/
cp TCC.db TCC.db.bak
sqlite3 TCC.db    # sqlite> prompt appears.


# for Camera

INSERT into access VALUES('kTCCServiceCamera',"com.microsoft.VSCode",0,1,1,NULL,NULL,NULL,'UNUSED',NULL,0,1541440109);

#  for Microphone

INSERT into access VALUES('kTCCServiceMicrophone','com.microsoft.VSCode',0,1,1,NULL,NULL,NULL,'UNUSED',NULL,0,1541440109);
```

**Comment by ph1p** [comment] 2021-02-20 14:33
Thanks @Naohiro2g ! Worked for me on **Big Sur 11.3 Beta** after adding another value and restarting VSCode.

For the Insider version, just use "**com.microsoft.VSCodeInsiders**".

```sql
VALUES('kTCCServiceCamera',"com.microsoft.VSCode",0,1,1,1,NULL,NULL,NULL,'UNUSED',NULL,0,1541440109);
```

**Comment by Naohiro2g** [comment] 2021-02-21 03:28
ph1q, thanks for the info regarding BigSur and insiders.

## We'd better to wait for the bug fix release but you can try the solution at your own risk. BE CAREFUL, IT'S DANGEROUS ENOUGH TO EDIT THE DATABASE BY HAND.

You Have Been Warned.
===================================================================

```sh
cd ~/Library/Application\ Support/com.apple.TCC/
cp TCC.db TCC.db.bak
sqlite3 TCC.db    # sqlite> prompt appears.
```

```sql
for Mojave, Catalina
INSERT into access VALUES('kTCCServiceCamera',"com.microsoft.VSCode",0,1,1,NULL,NULL,NULL,'UNUSED',NULL,0,1541440109);

for BigSur
INSERT into access VALUES('kTCCServiceCamera',"com.microsoft.VSCode",0,1,1,1,NULL,NULL,NULL,'UNUSED',NULL,0,1541440109);

for Microphone, replace the keyword with
'kTCCServiceMicrophone'

for VS Code Insiders, go with
'com.microsoft.VSCodeInsiders'
```

**Comment by sst2010** [comment] 2021-02-21 09:40
> **Comment: https://github.com/microsoft/vscode/issues/95062#issuecomment-751241372**
> ```
> cd ~/Library/Application Support/com.apple.TCC
> cp TCC.db TCC.db_backup
> sqlite3 TCC.db
> INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0,2,0,1);
> INSERT into access (service, client, client_type, auth_value, auth_reason, auth_version) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0,2,0,1);
> .exit
> ```

- The above code snippet works perfectly on Big Sur. Refer to the comment below this for Catalina.
- Also, before running the above comments, you need to grant `Full Disk Access` to Terminal.
  - You can do so at: System Preferences -> Security & Privacy -> Privacy tab -> Full Disk Access row in left sidebar
  - SRC: https://apple.stackexchange.com/a/339627/377639
- Simply restart VSCode after doing all of the above and it works like a charm.

**Comment by Naohiro2g** [comment] 2021-02-21 12:26
Just try this to know it's not "perfect". `cd ~/Library/Application Support/com.apple.TCC`

**Comment by GusnaIkhsan** [comment] 2021-03-02 02:50
I code with vscode but run the code with iTerm. Its work for me

**Comment by Naohiro2g** [comment] 2021-03-02 04:04
@GusnaIkhsan You launch VS Code via `code .` command on the terminal, right?  We knew it can be done as the first and the safer workaround. But we are too lazy and would like to have every options in hand. :)

If you have VS Code open all the time, and are used to using the terminal in VS Code, you may find it a bit cumbersome to restart VS Code using the terminal outside.  And you need to grant full disk access permission to the terminal app beforehand, like in another workaround.

**Comment by adgbu** [comment] 2021-03-11 20:55
Using the webcam (and virtual webcams) with Python+OpenCV from Terminal works fine. I can not get it to work within VSCode no matter what I do.

I have tried to grant permission to VSCode through the TCC but it still won't work. Don't know if I did it right. 

I used this tool [tccutil by jacobsalmela](https://github.com/jacobsalmela/tccutil). I also had to reboot into Recovery mode and disable SIP before I could try this. I got the util to work, but still no camera access inside VSCode.

I was thinking whether it would be possible to write a VSCode extension that just opens the camera and the microphone and does so by the book according to Apple's API recommendation. Would that bring up the dialog to grant permission to these resources for VSCode?

**Comment by mattialibera** [comment] 2021-03-12 07:52
> Using the webcam (and virtual webcams) with Python+OpenCV from Terminal works fine. I can not get it to work within VSCode no matter what I do.
> 
> I have tried to grant permission to VSCode through the TCC but it still won't work. Don't know if I did it right.
> 
> I used this tool [tccutil by jacobsalmela](https://github.com/jacobsalmela/tccutil). I also had to reboot into Recovery mode and disable SIP before I could try this. I got the util to work, but still no camera access inside VSCode.
> 
> I was thinking whether it would be possible to write a VSCode extension that just opens the camera and the microphone and does so by the book according to Apple's API recommendation. Would that bring up the dialog to grant permission to these resources for VSCode?

On MacOS sometimes OpenCV has some communication problems with some webcams; I'm almost sure that the problem is about that and not related with vscode in this case.

**Comment by adgbu** [comment] 2021-03-12 08:44
@mattialibera 
Then why does it work perfectly from Terminal but not from within VSCode?
It's even the same Python virtual environment. The only difference is inside or outside VSCode.

**Comment by mattialibera** [comment] 2021-03-12 11:11
@adgbu did you use exactly commands in my/others posts above? Which OS version do you have?

**Comment by adgbu** [comment] 2021-03-12 12:39
@mattialibera No, I used the tccutil tool.
I got it working now, by using the SQL INSERT commands directly. 
A couple of things that may help someone else:
1. There is a typo in your SQL command for Catalina where is says "com.microsoft.VSCoda".
2. My biggest problem was that I could not read the TCC.db file or even list that directory until after I booted into Recovery mode and turned off SIP. What I really **should** have done was to turn on _Full disk access_ for Terminal, but I didn't know that.

Thanks for taking the time to answer.

**Comment by HoBu23** [comment] 2021-03-13 11:40
macOS Big Sur, Version 11.2.3.

macOS Big Sur, version 11.2.3.

I have written a script in Python3 for speech recognition. When I run this script in VSCode internal terminal, I can't pick up any signal from the microphone. Then I tried to run my script natively in MAC terminal, it works after accepting the permission for microphone.
I tried again in VSCode internal terminal and same problem as before. No signal from the microphone.
I miss the permission for microphone in the VSCode terminal.

<img width="750" alt="permissions" src="https://user-images.githubusercontent.com/23123915/111028767-08a41b00-83f9-11eb-9f97-b9f1c7442e99.png">

Many thanks in advance for any help.

**Comment by wrogner** [comment] 2021-03-13 12:11
@HoBu23 : Please read the suggested solutions (and verify them) before submitting an addition.
Solutions for > 10.15.x by @wrogner
Solutions for < 10.15.x by @mattialibera

**Comment by HoBu23** [comment] 2021-03-13 18:47
> @HoBu23 : Please read the suggested solutions (and verify them) before submitting an addition.
> Solutions for > 10.15.x by @wrogner
> Solutions for < 10.15.x by @mattialibera

okay, thanks for your info, but I have no success with @wrogner way. Problem with open .db in sqlite3.
Now I tried it in IntelliJ IDEA.

This is the result:
<img width="397" alt="IntelliJ IDEA" src="https://user-images.githubusercontent.com/23123915/111040659-4d00dc80-8434-11eb-9c7b-e848db5694e0.png">

I think Microsoft should still think about this

**Closed** 2021-03-31 05:58 UTC
Labels: bug, confirmed, integrated-terminal, macos-catalina
