### ISSUE TITLE
Unsaved modifications to output files being inserted into other tabs

### ISSUE THREAD

**Issue by kirkholloway** [Microsoft/vscode#22922] opened 2017-03-21 00:38 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|vscode-markdownlint|DavidAnson|0.7.0|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|react-utils|lukazakrajsek|0.1.0|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.10.1|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|debugger-for-chrome|msjsdiag|2.6.0|
|Spell|seanmcbreen|0.9.1|
|python|tht13|0.2.3|
|Material-theme|zhuangtongfa|2.3.0|;

---

Steps to Reproduce:

1. Create script (mine was a node script) which generates an output file
2. Run the script
3. Make modification to the output file in another tab of the same window (I was using Prettify JSON)
4. With any other tab open Code, re-run the script

At step 4, whichever tab is currently open will receive the full unsaved contents of the output file

**Comment by rebornix** [comment] 2017-03-21 16:44
@kirkholloway can you still reproduce if you disable all extensions by running `code --disable-extensions`?

**Comment by kirkholloway** [comment] 2017-03-21 21:05
Bug doesn't seem to happen without extensions disabled. When running the script with extensions, I was using the `Ctrl + R, R` npm extension command to re-run the node script

**Comment by aeschli** [comment] 2017-03-31 07:19
Closing as the bug seems to be in an extension.

**Closed by aeschli** 2017-03-31 07:19 UTC
Labels: needs more info
