### ISSUE TITLE
An update is ready to install. Visual Studio Code is trying to add a new helper tool

### ISSUE THREAD

**Issue by balupton** [Microsoft/vscode#22363] opened 2017-03-10 08:48 UTC
- VSCode Version: Version 1.10.1 (1.10.1)
- OS Version: macOS 10.12.4 Beta (16E183b)

Steps to Reproduce:

1. Open Visual Studio Code, get prompted to enter my admin password without explanation of why.
2. Click cancel, as no reasoning was provided to trust it
3. See the error bar say `The operation couldn’t be completed. (OSStatus error -60006.)`

---

I have Visual Studio Code installed at `~/Applications`. What helper tool is it trying to install? Why does it need admin permissions?

**Comment by danrosenthal** [comment] 2017-03-10 18:29
I'm also experiencing this same issue.

**Comment by joaomoreno** [comment] 2017-03-13 09:27
[Please read this](https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150).

Duplicate of #7426

**Closed by joaomoreno** 2017-03-13 09:27 UTC
