### ISSUE TITLE
`TypeScript and JavaScript Language Features`'s High Usage, crashes and other bugs

### ISSUE THREAD

**Issue by FrameMuse** [microsoft/vscode#197165] opened 2023-11-01 18:59 UTC
Does this issue occur when all extensions are disabled?: No, bugs happen only with "TypeScript and JavaScript Language Features"

- OS Version: **Windows 11**
- VS Code About:
```
Version: 1.84.0-insider
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T10:16:52.814Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.84.0-insider Chrome/114.0.5735.289 Electron/25.9.2 Safari/537.36
```

Steps to Reproduce:

1. Activate "TypeScript and JavaScript Language Features"
2. Open a TypeScript project with lots of functions, types and function-type references
3. See degraded performance, at first glance seem to work fine but slowly getting less performant with continuous usage

I found some other probably related issues:
- #197143
- #197141
- #197125
- #197112
- #197101
- #197091
- #197064
- #197055
- #197049

**Comment by FrameMuse** [comment] 2023-11-02 06:57
Also, my custom Keyboard bindings stop working when the bugs happen. They work, when TypeScript intellisense is loading properly. TypeScript intellisense is loading properly only when I open small projects.

**Comment by FrameMuse** [comment] 2023-11-02 08:39
After some time of VSCode usage while performance is still degraded, this popped up
![image](https://github.com/microsoft/vscode/assets/53980482/f365b5eb-24bb-485a-87cc-590842901171)

And 2 minutes lates another popup appeared
![image](https://github.com/microsoft/vscode/assets/53980482/4785126b-9816-4e74-abae-bc4512ce29ca)

**Comment by FrameMuse** [comment] 2023-11-02 11:49
With new version `1.85.0-insider` - "TypeScript and JavaScript Language Features" seems to have less degraded performance, but when open more files, endless "intellisense loading" returns back and nothing works.

**Comment by FrameMuse** [comment] 2023-11-03 19:05
I've recently updated to the latest build and this seems to fix all bugs.

The commit that has it working properly:
`1ef160d5bc6aab85b74e34c98d7861c7727a37ec`

**Comment by FrameMuse** [comment] 2023-11-06 09:28
From my observations, it is clear that bugs aren't fixed but memory leak is less serious than before, it takes some time and all the bugs appear again.

Commit: `9aacac648821b5c9c1a7192ac9d44c50af6fe241`

**Comment by FrameMuse** [comment] 2023-11-08 07:22
Currently, it's more like going back and forth - I update the VSCode bugs disappear or become less serious and then they come back again, I'm not sure what's going on.

I always try to test the codebase with disabled extensions, so this is **apparently** not related to any extensions.

**Comment by FrameMuse** [comment] 2023-11-09 13:07
Commit: `7771124ebd6b7f6e60da14d744961b717b73282f`, the typescript intellisense become even more performant than it was before.

**Comment by FrameMuse** [comment] 2023-11-09 13:08
Commit: `f346494c77e1245505e53a2ddcab3bfb4ee52e08`, the typescript intellisense become **even** more performant than it was before.

**At least for the regular usage.**

**Comment by mjbvz** [comment] 2023-11-15 21:05
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

That warning mentions you have a number of TypeScript plugins enabled which could cause this issue

**Comment by FrameMuse** [comment] 2023-11-16 10:50
@mjbvz It doesn't reproduce in **the latest** VS Code Insiders build even with all the extensions **enabled**.

Actually, now everything is working MUCH faster (at least for my projects).

**Comment by mjbvz** [comment] 2023-11-16 22:34
Thanks for testing. Closing since its sounds like the issue may have already been fixed

**Closed by mjbvz** 2023-11-16 22:34 UTC
Labels: info-needed
