### ISSUE TITLE
Whole line copying/pasting doesn't work across different files.

### ISSUE THREAD

**Issue by anton89** [Microsoft/vscode#28031] opened 2017-06-05 10:29 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open 2 file let say a.js and b.js
2. In a.js copy whole line(wihout selection)
3. Try paste in a.js, behavior is correct where line is duplicated
4. Try paste in b.js behavior is different instead of paste-ing copied line into new line and it append copied line into same line

**Comment by nsf** [comment] 2017-07-02 16:59
Same on 1.13.1 on Linux. Very annoying. Got used to copy/pasting lines like that in sublime, trying to use vscode due to better tools integration (typescript in particular), but this kind of little differences really makes me sad. Please fix it.

**Comment by shurcooL** [comment] 2017-07-02 23:11
I can confirm this happens on VSCode Version 1.13.1 on macOS.

It seems the paste behavior change as soon as you navigate away from your current tab where you copied or cut the line, even if you immediately return back to it.

I can also confirm this weird/inconsistent behavior is not present in latest Sublime Text 3 (dev channel, build 3140).

**Comment by alexandrudima** [comment] 2017-12-14 09:57
Duplicate of #5639

**Closed by alexandrudima** 2017-12-14 09:57 UTC
Labels: bug, editor-clipboard
