### ISSUE TITLE
Default Terminal cannot be set to Git Bash

### ISSUE THREAD

**Issue by stefanofavero** [microsoft/vscode#132440] opened 2021-09-06 09:33 UTC
Issue Type: <b>Bug</b>

Default Terminal is poweshell and cannot be changed even setting profiles and default profile = Git Bash

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.14.0
ng-template|Ang|12.2.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|3.9.1
vscode-language-pack-it|MS-|1.60.2
remote-wsl|ms-|0.58.2
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
angular2-inline|nat|0.0.17
material-icon-theme|PKi|4.10.0
autoimport|ste|1.5.4
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.14
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-06 09:36
/duplicate of #132150 and expected to be fixed in upcoming recovery release

**Closed** 2021-09-06 09:37 UTC
Labels: *duplicate, new release
