### ISSUE TITLE
Delete is no longer irreverisible

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111636] opened 2020-12-01 15:11 UTC
Testing #111015

- select two files, press `shift + delete`
- dialog shows:
![image](https://user-images.githubusercontent.com/6461412/100758193-86ff2300-33ef-11eb-8293-b70abfd41886.png)\
- press ok
- invoke Undo, files are back

The impossible has happened! :-)

**Comment by aeschli** [comment] 2020-12-01 15:11
(it's probably ok to leave things as they are  ;-))

**Comment by isidorn** [comment] 2020-12-01 15:14
Haha it's magic!
The problem is that we still do not fully restore deleted folders, so I think it is fine to keep this warning dialog.
Assigning to Debt week though to polish the dialog wording (we could remove "This action is irreversible" part).

**Comment by isidorn** [comment] 2020-12-10 15:49
Currently we do not support Undoing folder delete - the folder is just brough back empty.
So if you are deleting at least a folder I am leaving the old message, when you are just deleting files I now show this

![Screenshot 2020-12-10 at 16 47 28](https://user-images.githubusercontent.com/1926584/101794936-ab51b280-3b07-11eb-9ea2-4a32915904aa.png)

**Closed** 2020-12-10 15:53 UTC
Labels: bug, file-explorer, polish
