### ISSUE TITLE
'UI State' history entries in setting sync view always show complete delete of file contents

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#104126] opened 2020-08-05 22:45 UTC
Issue Type: <b>Bug</b>

Testing #103604

**Repro**
1. Enable setting sync for all features
1. Open the setting sync data view
1. View a `UI State` entry and click on `globalState.json`

**Bug**
These entries always show the entire file contents as being deleted for me:

<img width="2047" alt="Screen Shot 2020-08-05 at 3 42 24 PM" src="https://user-images.githubusercontent.com/12821956/89471253-8224ae00-d732-11ea-803b-2f47e9a7e3ea.png">

This is true for every `UI State` entry I tried viewing on any of my synced machines

VS Code version: Code - Insiders 1.48.0-insider (d13d2fc56da7a2f8bcad4256212db0661fcbba45, 2020-08-05T05:26:44.946Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.31GB free)|
|Process Argv|--user-data-dir=./c/data --extensions-dir=./c/extension|
|Screen Reader|no|
|VM|14%|
</details>

**Comment by 9at8** [comment] 2020-08-05 23:58
@mjbvz possible duplicate of #103995 ?

**Closed** 2020-08-06 00:41 UTC
Labels: *duplicate
