### ISSUE TITLE
Extension host failing

### ISSUE THREAD

**Issue by blaineventurine** [microsoft/vscode#84931] opened 2019-11-15 16:40 UTC
Issue Type: <b>Bug</b>

Running an angular project, periodically debugging with Chrome. Intellisense disappears, F12 will not find references, TypeScript tells me there are errors when there aren't (things like a variable not being defined, even though it is), but then doesn't catch things that should cause a compile error. Eventually, extensionHost.ts crashes:

FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory

 1: 00007FF7B033C9E2 node::EmitAsyncDestroy+11839202
 2: 00007FF7AF7C9A96 node::Abort+22
 3: 00007FF7AF7CA073 node::Abort+1523
 4: 00007FF7AD33CCC8 v8::V8::GetVersion+792
 5: 00007FF7AD33CC6A v8::V8::GetVersion+698
 6: 00007FF7AD385F83 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+61731
 7: 00007FF7AD384746 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+55526
 8: 00007FF7AD38226A std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+46090
 9: 00007FF7AD38CAD9 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+89209
10: 00007FF7AD38D03E std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+90590
11: 00007FF7AD563F57 v8::Unlocker::~Unlocker+52839
12: 00007FF7AD797961 v8::TickSample::GetStackSample+449681
13: 00007FF7ADD090FD v8_inspector::V8ContextInfo::executionContextId+3107101
14: 000003242FDBBDE7 

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.91GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
gitlens|eam|10.1.2
vscode-diff|fab|1.4.0
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
output-colorizer|IBM|0.1.2
latex-workshop|Jam|8.3.1
regex-railroad-diagrams|kog|0.2.4
json-to-ts|Mar|1.5.5
rainbow-csv|mec|1.3.1
Angular-BeastCode|Mik|8.0.10
dotenv|mik|1.0.1
ruby-rubocop|mis|0.8.1
prettify-json|moh|0.0.3
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.1
vscode-azurefunctions|ms-|0.20.0
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.2
mssql|ms-|1.7.0
python|ms-|2019.10.44104
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.2
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
cpptools|ms-|0.26.1
csharp|ms-|1.21.7
powershell|ms-|2019.11.0
vscode-node-azure-pack|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.2
debugger-for-chrome|msj|4.12.1
material-icon-theme|PKi|3.9.1
java|red|0.53.1
vscode-yaml|red|0.6.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
code-spell-checker|str|1.7.20
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.2.0
application-insights|Vis|0.4.2
azure-iot-toolkit|vsc|2.13.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.5.0

</details>

**Comment by kimih12** [comment] 2019-11-15 21:15
I have a development environment running Angular and NodeJS. I'm experiencing a similar issue with no references, suggestions, etc. I am at same VS Code version and OS version as the author.

Visual Studio Code alone consumes more than 4GB of memory when this happens... Maybe a possible memory leak? I haven't installed any new extensions past few weeks, the only recent update was VS Code.

![image](https://user-images.githubusercontent.com/48962675/68975929-685cc880-07a9-11ea-97d0-51a3ea10306e.png)

![image](https://user-images.githubusercontent.com/48962675/68975816-17e56b00-07a9-11ea-93d7-fa2d7eb2c016.png)

**Comment by alexandrudima** [comment] 2019-11-18 14:42
@blaineventurine From the information you have attached, you are experiencing an OOM crash. Unfortunately, any one of the extensions that are running can end up allocating a lot of memory and suffer from a memory leak which might lead to an OOM situation. We currently don't have any tools available to us that would help us clearly spot which extension allocates the most amount of memory because the extensions are executing in a single v8 context in a single process. Could you perhaps try to disable some of the extensions you use? You can find a list of executing extensions using `F1 > Developer: Show running extensions`

@kimih12 I am not 100% sure if you are suffering from the same issue as the OP, but it appears for you the `tsserver` process is consuming 4GB of RAM. I wonder, do you have `vscode-typescript-tslint-plugin` installed? I have noticed the OP has the same extension installed and there is another thread where that extension appears.

**Comment by kimih12** [comment] 2019-11-18 18:50
@alexandrudima Yes, I do have the `ms-vscode.vscode-typescript-tslint-plugin` installed.

**Comment by mjbvz** [comment] 2019-11-19 19:30
Duplicate of #84940 I believe

**Closed by mjbvz** 2019-11-19 19:30 UTC
Labels: needs more info
