### ISSUE TITLE
restart button on debugging toolbar should restart the file that originally started it, not the active window from the editor

### ISSUE THREAD

**Issue by amesmr** [Microsoft/vscode#23036] opened 2017-03-22 18:03 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|Handlebars|andrejunges|0.2.0|
|handlebars-preview|chaliy|1.1.0|
|bracket-pair-colorizer|CoenraadS|0.8.8|
|beautify|HookyQR|1.0.2|
|node-module-intellisense|leizongmin|1.3.0|
|debugger-for-chrome|msjsdiag|2.7.0|
|node-modules-resolve|naumovs|1.0.2|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1. Running Node server app in debugger - server.js
2. Change to edit .html file that the server is serving.
3. Hit restart on the debugging toolbar (green circular arrow).
4. ERROR - Cannot launch program 'folder\folder\\**home.html**'; setting the 'outFiles' attribute might help.

**Comment by isidorn** [comment] 2017-03-23 09:09
@weinand this is the issue if we should reload the configuration on restart or if we should not.
It seems to be tricky to find the right balance, atm we relaod the configuration but keep the process.type since the debug extension might ovewrite it.
I agree that this behavior is strange and it might make sense to also ovewrite the program, but that feels like a hack. What fields do we overwrite and which do we keep.
In the end it just might be better that we do not relaod the configuration but just use the one on the active process.

**Comment by weinand** [comment] 2017-03-23 09:40
@isidorn but in this case the problem is probably that the launch config uses the '${file}' variable and this is reevaluated on restart. So it picks up the html file instead of the original server.js.

**Comment by isidorn** [comment] 2017-03-23 09:42
@weinand yes that is the underlying problem. I can also close this as designed even though it feels to me as unexpected behavior

**Comment by weinand** [comment] 2017-03-23 09:57
We should consider to reload (and reevaluate variables) only if the underlying launch.json has changed. If it hasn't we will continue to use the launch config in memory.

Open issue: do we loop this launch config again through the extension's startSession command?

**Comment by isidorn** [comment] 2017-10-27 14:21
This should be fixed in latest vscode insiders
@amesmr let me know if that is not the case and I will reopen, thanks

**Closed by isidorn** 2017-10-27 14:21 UTC
Labels: bug, debug
