### ISSUE TITLE
MAC OS Services submenu ant text services - dont work

### ISSUE THREAD

**Issue by ambrosso** [Microsoft/vscode#47704] opened 2018-04-12 00:21 UTC
VS Code Services menu don't open MacOS Services.
If text in VS Code editor is selected, there is no Text service in Services submenu.
So any Text Service cant be applied to selected text.
Text Services keyboard shortcuts don't work too.

<a href="http://imgbox.com/qBT42g3f" target="_blank"><img src="https://images2.imgbox.com/1d/c5/qBT42g3f_o.png" alt="image host"/></a>

- VSCode Version: 1.22.1 and 1.23 Insiders
- OS Version: OSX 10.13.4

Steps to Reproduce:

1. Select any text in VS Code editor
2. Open: Code -> Services
3. No Text Services there
4. And Text Services shortcuts don't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-04-12 08:59
If someone wants to help out, feel free 👍

**Comment by bpasero** [comment] 2018-04-12 09:00
Duplicate of https://github.com/Microsoft/vscode/issues/27799

**Closed by bpasero** 2018-04-12 09:00 UTC
Labels: electron, help wanted, os-integration
