### ISSUE TITLE
Couldn't save code（vue）

### ISSUE THREAD

**Issue by 13714273163** [microsoft/vscode#91057] opened 2020-02-20 08:55 UTC
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601

question:Every time I save, it appears as shown in the figure, which prevents me from saving the code：Running Save Participants for 'xxxx': Quick Fixes
![question](https://user-images.githubusercontent.com/27482143/74916915-a3eadc80-5401-11ea-8fd4-ad747c9bfa4b.png)

**Comment by gjsjohnmurray** [comment] 2020-02-20 09:10
Possible duplicate of #90889

**Comment by XuZhaoTong** [comment] 2020-02-21 06:14
I also encountered this problem. After opening vscode for a period of time, this problem will appear. I don't know what to do at all. Does anyone have any way??

**Comment by gjsjohnmurray** [comment] 2020-02-21 10:32
Did you follow the advice in #90889? What were your results?

**Comment by katz12** [comment] 2020-02-25 22:16
@13714273163 do you use the ESLint plugin by chance?

**Closed** 2020-02-25 22:19 UTC
Labels: *caused-by-extension

**Comment by octref** [comment] 2020-02-25 22:21
I assume this is ESLint's Auto Fix On Save feature: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
The dup issue is in microsoft/vscode-eslint, so please follow that one.

**Comment by dbaeumer** [comment] 2020-02-26 11:12
@13714273163 if you use ESLint can you please comment here: https://github.com/microsoft/vscode-eslint/issues/904 

It would be great if you can provide a GitHub repository to clone which demos this.

**Comment by 13714273163** [comment] 2020-02-27 01:47
i just reload Window From time to time
