### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by dingjianz** [microsoft/vscode#175067] opened 2023-02-22 03:17 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230220

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-styled-plugin`
- `typescript-vue-plugin-forward`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33949:11)
    at parseSimpleUnaryExpression (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33582:16)
    at parseUnaryExpressionOrHigher (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33550:35)
    at parseBinaryExpressionOrHigher (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33468:25)
    at parseAssignmentExpressionOrHigher (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33141:18)
    at parseExpression (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33107:16)
    at doOutsideOfContext (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30804:12)
    at allowInAnd (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30825:12)
    at parseExpressionOrLabeledStatement (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:34619:24)
    at parseStatement (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:34851:12)
    at parseListElement (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:31575:12)
    at parseList (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:31560:19)
    at parseSourceFileWorker (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30620:24)
    at Object.parseSourceFile (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30453:20)
    at createSourceFile (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30314:21)
    at createLanguageServiceSourceFile (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135115:22)
    at acquireOrUpdateDocument (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:132037:26)
    at Object.acquireDocumentWithKey (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:131962:12)
    at getOrCreateSourceFileByPath (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135440:31)
    at Object.getOrCreateSourceFile (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135420:14)
    at c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135352:42
    at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117119:24)
    at findSourceFileWorker (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119451:23)
    at findSourceFile (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119371:20)
    at c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119320:22
    at getSourceFileFromReferenceWorker (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119289:26)
    at processSourceFile (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119318:5)
    at processRootFile (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119114:5)
    at c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117899:41
    at forEach (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:2309:22)
    at createProgram (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117899:5)
    at synchronizeHostData (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135376:15)
    at Proxy.getProgram (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135448:5)
    at ConfiguredProject2.updateGraphWorker (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:172060:41)
    at ConfiguredProject2.updateGraph (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:171997:32)
    at ConfiguredProject2.updateGraph (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:173179:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:174786:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:175877:26)
    at c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:176157:64
    at flatMap (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:2557:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:176157:24)
    at updateOpen (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:177302:29)
    at c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179869:69
    at IpcIOSession.executeWithRequestId (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179861:14)
    at IpcIOSession.executeCommand (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179869:29)
    at IpcIOSession.onMessage (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179911:51)
    at process.<anonymous> (c:\Users\jianding9\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:181479:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.18363
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.41GB free)|
|Process Argv|--crash-reporter-id 10ba5059-d6ec-4f4d-85ff-fa1c195b1e4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
react-hooks-snippets|AlD|1.2.0
project-manager|ale|12.7.0
bundle-size|amb|1.5.0
simple-react-snippets|bur|1.2.7
path-intellisense|chr|2.8.4
vscode-wxml|cod|0.1.9
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
shell-format|fox|7.2.2
todo-tree|Gru|0.0.224
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
vscode-react-typescript|inf|1.3.1
styled-components-snippets|jon|0.10.0
vscode-gutter-preview|kis|0.30.0
vscode-leetcode|Lee|0.18.1
vscode-language-babel|mgm|0.0.36
vscode-docker|ms-|1.23.3
vscode-language-pack-zh-hans|MS-|1.75.2023021509
remote-containers|ms-|0.275.1
vscode-typescript-next|ms-|5.0.202302200
indent-rainbow|ode|8.3.1
vuehelper|oys|0.1.0
material-icon-theme|PKi|4.24.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
vscode-plugin-json2interface|sjh|0.0.2
guides|spy|0.9.3
vscode-styled-components|sty|1.7.5
open-in-browser|tec|2.0.0
rainbow-tags|vol|0.4.1
volar|Vue|1.1.5
vscode-typescript-vue-plugin|Vue|1.1.5
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30662992
89544117:30613380
pythonsymbol12:30657548
vsccsb:30662443
pythonb192cf:30669361

```

</details>

**Comment by mjbvz** [comment] 2023-02-22 04:26
Duplicate of https://github.com/vuejs/language-tools/issues/2434

As the issue reporter noted, this is likely caused by one of the Vue extensions you have installed. Please following up with the correct extension so that they can investigate and fix this

**Closed by mjbvz** 2023-02-22 04:26 UTC
