### ISSUE TITLE
Restart program ignores changes in .vscode/launch.json parameters

### ISSUE THREAD

**Issue by RomanDavlyatshin** [microsoft/vscode#102602] opened 2020-07-15 15:01 UTC
- VSCode Version: 1.47.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Add launch configuration (tested only "type":"node")
2. Add some env variable to launch configuration
3. Start program and log env value
4. Edit launch.json - set previously created env variable to any other value
5. Restart program with restart button or shortcut
6. See old env variable value being logged

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment] 2020-07-21 11:02
@isidorn I can reproduce this

**Comment by isidorn** [comment] 2020-07-30 09:25
The issue is the following:

js-debug sets the `supportsRestartRequest` capability. Because we detect that capability we simply send the `restart` request to the session and it is up to the session to restart like it wants. Thus ignoring any changes in the `launch.json`.

I see two potential solutions:
1. We define `supportsRestartRequest` to only be respected if the user did not make changes to the `launch.json`. However there is an additional problem here, since the js-debug created a child session, and the user is actually restarting a child session we do not have an exact correlation between a child session and a changed launch configuration. We would have to introduce a heuristic: if the launch configuration is changed of a child session or any of it's parent sessions do not respect `supportsRestartRequest`. This would have as a consequence that if there are two child sessions, user changes the launch.json of the parent and restarts one of the child sessions, we would stop the parent and start everything again
2. js-debug handles this in the restart request by re-reading the launch configuration

@weinand @connor4312 let me know what you think

**Comment by connor4312** [comment] 2020-07-30 20:55
I see the issue with (1)

I think (2) is reasonable, but I'm not sure the best way to do it. I would have to figure out where the launch config exists on disk and resolve variables myself, which gets rather complex when dealing with workspace configurations.

I could stop terminate the session and invoke `vscode.startDebugging` again, but there's still the problem that I need to determine where the launch config exists in order to figure out whether a restart is needed!

Maybe the best solution is to provide some hint in DAP restart request that the launch config changed so that the debugger can react appropriately.

**Comment by isidorn** [comment] 2020-07-31 07:28
@connor4312 I believe you could use the [`getConfiguration('launch')`](https://github.com/microsoft/vscode/blob/a3dd5c3b75b2a8c3523ae0dc9828c2391bdc723e/src/vs/vscode.d.ts#L9825) api to get the launch.json and then you could see if the launch config with the right name exists. But I agree it is not very nice.

Introducing a hint in the DAP restart request sounds like a good idea to me.
When you see that I sent you that flag you could terminate the session and invoke `vscode.startDebugging` as you suggested.
However I would still have the problem when detecting if there was a change due to the parent child sessions. So I would have to say I send that flag if the child configuraiton changed or if the parent configuration changed. Maybe we should specify that as part of the comment of the flag.

**Comment by connor4312** [comment] 2020-07-31 14:58
I didn't know I could get the launch config using that method. I'll try that out (during debt week next month) and see if I can get something working without requiring dap/vscode changes.

**Comment by isidorn** [comment] 2020-08-11 14:59
Also assigning to you @connor4312

**Comment by connor4312** [comment] 2020-09-08 21:19
This is not very practical for me to do in js-debug. I have a version 'working' in the linked commit, but the big missing part I cannot do is resolution of variables used in the configuration. `${workspaceFolder}`, I can take care of, but things like inputs are not practical to re-implement. That is, to resolve those I actually need to start a fresh debugging session.

Also, even with that solved, there's currently state that is stored for the session tree which I would need to build wiring to rework.

Changing the launch config is not something that happens super often (and if it is, then they might want to use something else like `${input:` variables). I think having to stop and start the debug session in these cases is okay, and perhaps even intuitive.

**Closed** 2020-09-08 21:19 UTC
Labels: bug, debug
