### ISSUE TITLE
Latest insider build breaks the ionide extension's terminal integration.

### ISSUE THREAD

**Issue by nhirschey** [microsoft/vscode#121665] opened 2021-04-19 17:35 UTC
See the bug report here about the broken terminal integration.: https://github.com/ionide/ionide-vscode-fsharp/issues/1525

using alt+enter to send code to the terminal does not work, and I cannot copy and paste code into the terminal either.

I suspect that it it is the same issue as this https://github.com/microsoft/vscode/issues/121654

I confirmed on 2 pcs. If I used the insider build from 3 days ago, everything is fine. After updating to this morning's insider build, terminal integration with the ionide f# extension no longer works in the insider build. VS Code stable is fine.

Is this a bug on vscode's side? Or is this an architecture change that downstream extensions need to handle? Please let me know if you need further debug information.

Log (Extension host):
```
[2021-04-21 16:28:14.358] [exthost] [error] [Ionide.Ionide-fsharp] provider FAILED
[2021-04-21 16:28:14.360] [exthost] [error] Error: Illegal argument: line must be non-negative
	at C (c:\Users\nicho\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
	at new u (c:\Users\nicho\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:76:13900)
	at new u (c:\Users\nicho\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:76:13295)
	at w (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:231857)
	at y (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:231930)
	at J (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:237977)
	at Object.asCodeAction (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:242018)
	at c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:1:105482
```

Log (Window):
```
[2021-04-21 16:28:14.361] [renderer1] [error] Illegal argument: line must be non-negative: Error: Illegal argument: line must be non-negative
	at C (c:\Users\nicho\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
	at new u (c:\Users\nicho\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:76:13900)
	at new u (c:\Users\nicho\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:76:13295)
	at w (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:231857)
	at y (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:231930)
	at J (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:237977)
	at Object.asCodeAction (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:242018)
	at c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:1:105482
```

Version: 1.56.0-insider (user setup)
Commit: 8aff878db2542eea2dfb571c8bb485118bbb3113
Date: 2021-04-19T05:15:35.845Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

I'm using ionide 5.5.2.

**Comment by nhirschey** [comment] 2021-04-21 07:15
@meganrogge please do not merge the terminal changes made between April 16 and April 19 into vs code stable until this issue is resolved. 

Everything was fine in insiders edition until April 16. Changes to the terminal in the April 19 insiders release broke ionide integration. 

If I can provide any more debug info, please let me know.

**Comment by Tyriar** [comment] 2021-04-22 18:07
@nhirschey do you have `terminal.integrated.windowsEnableConpty` in your settings.json and are you running in a local window?

**Comment by nhirschey** [comment] 2021-04-22 18:40
I am running local. 

But bingo: I also have windowsEnableConpyty=false in my settings because of this https://github.com/microsoft/vscode/issues/71966#issuecomment-805782707. 

I just tried it both ways; if I set windowsEnableConpyty=true then ionide works. If I set it to false then ionide is broken. Though I set it to false because the hangs whenever I closed the terminal were pretty painful (I close terminal to cancel a calculation or refresh my interactive session during data analysis).

```
{
    "terminal.integrated.rendererType": "experimentalWebgl",
    "latex-workshop.view.pdf.viewer": "tab",
    "window.zoomLevel": 2,
    "git.autofetch": true,
    "terminal.integrated.windowsEnableConpty": false,
    "notebook.kernelProviderAssociations": [
        {
            "viewType": "jupyter-notebook",
            "kernelProvider": "ms-toolsai.jupyter"
        }
    ],
    "jupyter.experiments.optOutFrom": [
    
    ],
    "FSharp.verboseLogging": true,
    "workbench.activityBar.visible": false,
    "debug.openDebug": "neverOpen",
    "editor.tabCompletion": "on",
    "powershell.integratedConsole.focusConsoleOnExecute": false,
    "files.defaultLanguage": "powershell",
    "workbench.colorTheme": "PowerShell ISE",
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
    "powershell.buttons.showPanelMovementButtons": true,
}
```

**Comment by meganrogge** [comment] 2021-04-22 20:11
Thanks for that info. This is a duplicate of #121685

**Closed** 2021-04-22 20:12 UTC
Labels: *duplicate, electron, integrated-terminal
