### ISSUE TITLE
[emmet] Inconsistency on cursor placement when applying emmet proposals

### ISSUE THREAD

**Issue by Dean-NC** [microsoft/vscode#104586] opened 2020-08-13 20:19 UTC
- VSCode Version: 1.47.3
- OS Version: Windows x64 10.0.18363

[vscode.zip](https://github.com/microsoft/vscode/files/5071203/vscode.zip)

![T1](https://user-images.githubusercontent.com/12361341/90182910-a874ca00-dd80-11ea-899e-e5291f1592f2.gif)

Steps to Reproduce:

1. In attached html file, put cursor inside body {} style rule, and type: **dis**, and then intellisense will show  _display: none_ as the first choice (Emmet abbreviation). Press tab key, and cursor will be after the semi-colon.
2. Press enter key to go to next line. Type **ov** or **over**, and intellisense will show _overflow: hidden;_ as the first choice (Emmet abbreviation). Press tab key, and _hidden_ will be hilighted/selected, rather than cursor being after the semi-colon.

I can see the advantages of both cursor placements, but why the inconsistency?

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment] 2020-10-12 21:55
I believe this is by design.
In the cheat sheet [https://docs.emmet.io/cheat-sheet/](https://docs.emmet.io/cheat-sheet/), `di` (or `d:i`) and `ov` have different expansion patterns. The green highlight around `hidden` refers to the fact that that selection will be focused after the expansion.

**Comment by Dean-NC** [comment] 2020-10-12 23:43
@rzhao271 As I understand it, the green hilight simply tells what the default property value is if you don't give any starting characters. For example, _display_ will have the value 'block', and _overflow_ will have 'hidden'.
But that doesn't explain why **when pressing the tab key**, _overflow_ **incorrectly puts the cursor before the semicolon**, whereas  _display_ correctly puts the cursor **after the semicolon**.

Please re-open this.

**Comment by rzhao271** [comment] 2020-10-13 16:57
Will reopen, but I noticed this inconsistency between `di` and `ov` is also in Sublime Text and the Emmet website itself [here](https://docs.emmet.io/actions/expand-abbreviation/).

Something else to note is that `db` expands to `display: block;|`, whereas just `d` expands to `display: block|;`. My guess is that if you already gave Emmet the suggested value, it'll put the cursor after the semicolon, but if you didn't, it'll put it before the semicolon, giving you a chance to change the value. In your demo, you typed `dis`, which the VS Code Emmet interpreted as `di`, which expanded to `display: inline;|`.

@sergeche can you confirm this is intended behaviour?

**Comment by Dean-NC** [comment] 2020-10-13 17:44
@rzhao271 Thanks for re-opening and investigating. I believe most people expect the cursor to end up after the semicolon, because in our minds, this is "Microsoft-style intellisense/auto-complete". I do know that for me, when pressing tab and sometimes the cursor is placed oddly like this, it disrupts the typing flow, because I now can't press _enter_, but have to either press _end_ then _enter_, or _down-arrow_.

**Comment by rzhao271** [comment] 2020-11-04 18:39
Closing this again. Considering that this is how Emmet works on other editors too, I'm not sure it's worth changing this behaviour just for VS Code.

Also, as I mentioned earlier, depending on the abbreviation, Emmet will suggest a value to fill in and then the cursor will end up after the semicolon. Type `oh` or `ovh` instead of `ov` for overflow hidden, for example.

**Closed by rzhao271** 2020-11-04 18:39 UTC
Labels: bug, emmet, needs more info
