### ISSUE TITLE
EditorLayout window not expanding automatically on focus

### ISSUE THREAD

**Issue by sanket-bhalerao** [Microsoft/vscode#53090] opened 2018-06-27 07:06 UTC
Issue Type: <b>Bug</b>

open visual studio code
open two files in vertical layout
resize one tab to smallest possible width
focus (click) on the smaller editor file
behaviour before 1.25 version: the smaller editor will automatically expand and larger window will shrink.
![image](https://user-images.githubusercontent.com/9264813/41958132-bcc5e5aa-7a06-11e8-9bec-34ba49716dd1.png)

VS Code version: Code - Insiders 1.25.0-insider (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:18:12.763Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (2.44GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
gitlens|eam|8.4.1
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
PowerShell|ms-|1.7.0
typescript-javascript-grammar|ms-|0.0.42
vsliveshare|ms-|0.3.335
debugger-for-chrome|msj|4.7.0

</details>

**Comment by bpasero** [comment] 2018-06-28 05:01
Duplicate of https://github.com/Microsoft/vscode/issues/51614

**Closed by bpasero** 2018-06-28 05:01 UTC
Labels: workbench-grid
