### ISSUE TITLE
MacOS VSCode and keypress to get accent print double character

### ISSUE THREAD

**Issue by blackholegalaxy** [Microsoft/vscode#33888] opened 2017-09-06 11:53 UTC
- VSCode Version: Version 1.15.1 (1.15.1)
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Use VSCode (latest version) on macOS with non accent keyboard layout. eg: US
2. Press key "e" and maintain to get OSx accentuated characters suggestion. Press the desired number to get accentuated letter.
3. The letter without accent is printed followed by the accentuated one instead of replacing the first one with accentuated.

**Please note** this behavior is not encountered in other editors or in browser for example. Nor encountered in slack app desktop. Just in VS Code.

**It's note encounted in the search input (CMD + F).**

**Please also note** this behavior is not new and was encountered before june.

Here is a gif:

![sep-06-2017 07-46-46](https://user-images.githubusercontent.com/11064123/30110461-2b513f22-92d8-11e7-9b7a-a53d6e636894.gif)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-09-27 22:22
Duplicate of #32985 Should be fixed for VSCode 1.17

**Closed by mjbvz** 2017-09-27 22:22 UTC
Labels: duplicate, editor, editor-input
