### ISSUE TITLE
Keyboard navigation in trees can't find children of never-expanded folders

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#95980] opened 2020-04-23 16:13 UTC
- VSCode Version: 1.44.x or insiders
- OS Version: win10

Steps to Reproduce:

1. focus on explorer
2. start typing, for instance "foo"
3. if "foo" is nested under a folder that has never been expanded since window load, "foo" will not be found. 
4. If I have expanded foo's immediate parent at least once, "foo" will be found, no matter if it's collapsed or not.

(having a `jsconfig.json` doesn't help)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ZYinMD** [comment] 2020-04-23 16:16
Not sure if it's intended behavior. If yes, then what's the correct way to search for a folder? As far as I know, you can't find a folder by using the `Search` tool, nor by using `Quick open`.

**Comment by IllusionMH** [comment] 2020-04-23 16:44
Duplicate of #66971 (will keep open if someone knows better way to find folder)

As for folders search not sure if it's available. I usually type folder name in Quick open and pick file from that folder - will be expanded with `"explorer.autoReveal": true`

**Comment by isidorn** [comment] 2020-04-24 07:22
And yes we do not have a good "find folder" functionliaty. Though this can easily be added by an extension. VS Code is an editor, so we are all about fiels.

**Closed** 2020-04-24 07:22 UTC
Labels: *duplicate

**Comment by ZYinMD** [comment] 2020-04-24 13:56
Thanks @isidorn ! Is there an existing feature request about folder searching? I found some issues mentioning it, but seems there's no "master" issue about folder searching.
