### ISSUE TITLE
New Feature Bug: Experimental Edit Context 

### ISSUE THREAD

**Issue by theferaltaint** [microsoft/vscode#230605] opened 2024-10-05 19:35 UTC
Type: <b>Bug</b>

Description:
When using the new experimental "Edit Context" feature in VSCode, keyboard input becomes non-functional (except for the carriage-return/enter key) after detaching a file tab. This issue persists across all system shortcuts (e.g., Ctrl + C), and standard key inputs, effectively rendering the detached tab unusable for typing or command input. However, mouse input does register. You can click and select text, and right-click to open menus. 

Steps to Reproduce:
1. Enable the "Edit Context" feature in VSCode.
2. Open multiple file tabs.
3. Pop-out/detach one of the open tabs into a separate window.
4. Attempt to type or use system shortcuts in the detached tab.

Troubleshooting Steps Taken:
- Used Extension Bisect to cycle through each extension to check the impact of each. Then disabled all extensions to ensure no interference from third-party tools. Issue persists, confirming it is unrelated to installed extensions.
- Changed from input device with cherry red switches to one with cherry brown switches. Then switched to non-mechanical switches. Also checked all input drivers. Issue persists, confirming it is unrelated to hardware nor is it driver related.
- Disabled all Logitech software. Issue persists, confirming it is unrelated to third-party input device software.
- Toggled read-only mode on and off for the active tab. Issue persists. Only change is that of course enter key input no longer registers as expected.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.5.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
regex|chr|0.5.0
vscode-markdownlint|Dav|0.56.0
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
code-runner|for|0.12.2
copilot|Git|1.235.1137
copilot-chat|Git|0.22.2024100401
go|gol|0.43.2
node-module-intellisense|lei|1.5.0
regionfolder|map|1.0.22
json|Mee|0.1.2
vscode-language-babel|mgm|0.0.40
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.3.2
vscode-dotnet-runtime|ms-|2.1.7
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
pylint|ms-|2023.10.1
python|ms-|2024.17.2024100401
vscode-pylance|ms-|2024.9.2
remote-wsl|ms-|0.88.4
extension-test-runner|ms-|0.0.12
makefile-tools|ms-|0.11.13
powershell|ms-|2024.3.2
sublime-keybindings|ms-|4.1.10
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
code-spell-checker|str|3.0.1
run-in-powershell|tob|1.2.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscodeintellicode-completions|Vis|2.0.0
vscodeintellicode-insiders|Vis|1.1.10
vscode-icons|vsc|12.9.0
json-color-token|yec|1.3.3
material-theme|zhu|3.17.5

(1 theme extensions excluded)

</details>

**Comment by theferaltaint** [comment] 2024-10-05 19:41
Update:

I have also confirmed that one of the issues reported by other users below where the Copilot chat disappears after the response is tied to this feature being active.

**Comment by bpasero** [comment] 2024-10-06 13:12
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by IllusionMH** [comment] 2024-10-07 05:16
Looks like duplicate of #229825

**Comment by theferaltaint** [comment] 2024-10-07 15:32
@IllusionMH sorry I didn't see that one in the list.

**Comment by aiday-mar** [comment] 2024-10-08 07:02
Thank you @IllusionMH. I will close this issue.

**Closed by aiday-mar** 2024-10-08 07:02 UTC
Labels: *duplicate, editor-edit-context
