### ISSUE TITLE
Preview features on Double Click

### ISSUE THREAD

**Issue by saileshkush95** [Microsoft/vscode#52375] opened 2018-06-20 02:53 UTC
I want to open the file in the preview mode after double click until I edit the file.
Same as single click preview features but I didn't want to preview any file with just the single single

Preview features is automatically disabled when i enable open file with double click
even preview features is enable in the setting
Thank you

**Comment by mjbvz** [comment] 2018-06-20 17:17
Duplicate of #47978

**Closed by mjbvz** 2018-06-20 17:17 UTC
