### ISSUE TITLE
[sql] Incorrect interpertation of a backward slash in single quotes ( '\' vs '\\' ) in sql files.

### ISSUE THREAD

**Issue by Angel-G** [Microsoft/vscode#8862] opened 2016-07-07 23:08 UTC
When viewing sql code (*.sql) if you have a backward slash in single quotes (sql1) the app will consider anything else after it (till the end of the code) to be comments. If you add a second backward slash within the single quotes (sql2) it will interpret it an an esc char and defined it as \ but the sql program will output two backward slash \\

![sql1](https://cloud.githubusercontent.com/assets/20346405/16672383/a9c4f826-445a-11e6-89ff-54bd2469e550.jpg)
![sql2](https://cloud.githubusercontent.com/assets/20346405/16672384/a9cabe64-445a-11e6-96f2-b6559f6f805a.jpg)

- VSCode Version: 1.3.0
- OS Version:          win 7 ent SP1

1. 
2.

**Comment by aeschli** [comment] 2016-07-14 20:47
duplicate of #5223

**Closed by aeschli** 2016-07-14 20:47 UTC
Labels: languages basic
