### ISSUE TITLE
TS Support For Web

### ISSUE THREAD

**Issue by cemalgnlts** [microsoft/vscode#205286] opened 2024-02-15 12:33 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.86.1

Steps to Reproduce:

1. Open the [sample repo](https://github.com/cemalgnlts/vscode-ts-support) with vscode.dev (https://vscode.dev/github/cemalgnlts/vscode-ts-support).
2. you will see that the type of the `logger` variable is incorrect.

Open Developer Tools and you will see the following error logs in the console:
```
Error: Could not read file outside of project root /vscode-vfs/github/cemalgnlts/node_modules
Error: Could not read file outside of project root /vscode-vfs/github/cemalgnlts
Error: Could not read file outside of project root /vscode-vfs/github/cemalgnlts/node_modules/@types
```

If you then delete the codes and rewrite them, you can also see these errors:
```
[Extension Host] no package at path /cemalgnlts/vscode-ts-support/node_modules/logger/index.d.ts /cemalgnlts/vscode-ts-support/node_modules/logger

---

Error: Invalid path: /vscode-vfs
Error: Invalid path: /
```

**Comment by mjbvz** [comment] 2024-02-21 21:37
Duplicate of #182791

**Closed by mjbvz** 2024-02-21 21:37 UTC
