### ISSUE TITLE
Source control shows current branch as 'master'

### ISSUE THREAD

**Issue by brainz80** [microsoft/vscode#165320] opened 2022-11-03 08:13 UTC
Type: <b>Bug</b>

Source control shows current branch as 'master' in Git worktree eventhough active branch isn't 'master'.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.35GB (16.19GB free)|
|Process Argv|--crash-reporter-id f331158c-b76c-4212-9fc0-84faccb73710|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
smarty-template-support|asw|2.0.0
unique-lines|bib|1.0.0
vscode-intelephense-client|bme|1.8.2
turbo-console-log|Cha|2.5.6
gitignore|cod|0.9.0
compulim-vscode-closetag|Com|1.2.0
vscode-springboot-snippets|dev|1.2.0
xml|Dot|2.5.1
gitlens|eam|13.0.3
EditorConfig|Edi|0.16.4
vscode-open-multiple-files|fab|1.4.0
vscode-search-open-all-results|fab|1.0.3
vscode-todo-plus|fab|4.18.4
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
remotehub|Git|0.46.0
terraform|has|2.24.3
vscode-guid|hea|1.5.0
npm-dependency-links|her|1.2.0
rest-client|hum|0.25.1
align-columns|jca|0.0.4
jsdelivr|jsD|1.0.2
latte|Kas|0.18.0
vscode-regexp-preivew|Lul|1.0.0
regionfolder|map|1.0.18
rainbow-csv|mec|3.2.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.22.2
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
hexeditor|ms-|1.9.9
powershell|ms-|2022.10.0
remote-repositories|ms-|0.24.0
sublime-keybindings|ms-|4.0.10
php-docblocker|nei|2.7.0
vetur|oct|0.36.1
advanced-new-file|pat|1.2.2
vscode-versionlens|pfl|1.0.10
csv-to-table|php|1.4.0
material-icon-theme|PKi|4.21.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
text-marker|ryu|1.11.0
vscode-nginx|sha|0.6.0
fish-vscode|sky|0.2.1
vscode-fileutils|sle|3.5.0
alrunner|tfe|3.3.3
errorlens|use|3.6.0
vscode-conventional-commits|viv|1.24.3
change-case|wma|1.0.0
php-debug|xde|1.29.0
sort-js-object-keys|zen|1.0.6
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
iaj6b796:30602301

```

</details>

**Comment by brainz80** [comment] 2022-11-03 08:14
Attached screenshot

![image](https://user-images.githubusercontent.com/1257591/199673424-4c02e37b-82d2-42c5-a707-19322a4a8b42.png)

**Comment by nopresnik** [comment] 2022-11-03 23:31
I am also having this problem after VS Code updated itself this morning.  Following.

**Comment by lszomoru** [comment] 2022-11-04 08:28
Closing as duplicate of https://github.com/microsoft/vscode/issues/164363

**Closed by lszomoru** 2022-11-04 08:28 UTC
Labels: new release
