### ISSUE TITLE
Consider making Settings Sync available for OSS builds

### ISSUE THREAD

**Issue by coxackie** [microsoft/vscode#110668] opened 2020-11-15 09:51 UTC
A lot of Linux distributions use the OSS build of vscode. The Settings Sync functionality is missing there; see https://github.com/microsoft/vscode/issues/105310

Could you please consider bringing it? I know that there is an extension that does this, but since there is already a built-in feature, it could be preferable.

Many thanks for your amazing work!

**Comment by sandy081** [comment] 2020-11-16 09:26
Sorry that we do not have plans for this. Hence closing this.

**Closed by sandy081** 2020-11-16 09:26 UTC
Labels: wont-fix

**Comment by coxackie** [comment] 2020-11-16 09:44
Many thanks for your response. Could you please kindly add a couple of words on explaining why the specific functionality is not included in OSS builds, for posterity?

**Comment by sandy081** [comment] 2020-11-16 11:24
CCing @chrisdias @kieferrm to answer above question.

**Comment by coxackie** [comment] 2020-11-16 19:56
Thanks, @sandy081, I am quite looking forward to see what @chrisdias and @kieferrm have to say.

**Comment by thefoxie** [comment] 2020-11-20 14:43
@coxackie long story short it's just MS being MS. Technically, there is no reason to not include such functionality. We could use MS binary but it doesn't use system electron but its own bundled version.

https://github.com/microsoft/vscode/issues/56686

**Comment by coxackie** [comment] 2020-11-21 09:38
@thefoxie Well, ok, one may trash all they want, but they do give this wonderful code base that we can use, and it is a terrific editor. I am sure the exclusion of the extension has anything to do with the bundling of system electron, unless you mentioned it to point out that they are not receptive to accommodate open source requests (which, again, may be just because they are also working under certain legal requirements).

 Anyway, let see if we do hear from @chrisdias and @kieferrm at some point.

**Comment by thefoxie** [comment] 2020-11-23 10:17
@coxackie my guess it would be either legal requirement or just management decision. Why would it has to do anything with electron being bundled or not? Haven't studied the code but I doubt that. Do they add that feature in during build on their servers? Same goes for extensions. We can turn them on  (I mean the official repos) via product.json. Why we cannot use the official repos is beyond my understanding as it doesn't make any sense. It's not a technical issue but decision making issue. These guys have little to no say in the matter as I believe we wouldn't be having this conversation if they had. In fact they are victims to the corporate BS as well.

**Comment by coxackie** [comment] 2020-11-25 22:35
well, ok. Even though I understand the constraints these guys are working under, it would have been nice if there was a response, so at least there could be a hint of how to circumvent the fact that nothing can be done (from the corporate side) in order to get this feature. But, oh, well. We will continue relying on the Settings Sync extension of Shan Khan (which is anyway awesome).

**Comment by darkbasic** [comment] 2021-06-24 08:00
Still no official answer on this? I guess it's MS being MS after all...

**Comment by thefoxie** [comment] 2021-06-24 08:25
@darkbasic it's possible to sync, but not officially, thus it might be against the license. I've almost managed to run the remote ssh. The problem is it loads different version on remote (which throws error) and I have no idea why. But sure, MS just being MS :smile:

**Comment by VijoPlays** [comment] 2022-09-06 17:29
True chads.
