### ISSUE TITLE
Sass/Scss - Issue with the Sass map and @each rule

### ISSUE THREAD

**Issue by andrewhathaway** [Microsoft/vscode#1924] opened 2016-01-11 13:25 UTC
Wasn't sure how to phrase this one so forgive me for the bad name, however I will explain!

I have two issues with VSC currently complaining about the following lines (arrow indicates red squiggly line).

```scss
$pushes: (
  alpha : 40px,
//      ^
  beta : 30px,
//     ^
  gamma : 25px
);
```

The first arrows message is: ") expected" and the second "} expected".

```scss
@each $spacingName, $spacingValue in $pushes {
//                ^
  @include pushes($spacingName);
}
```
The arrows message is "in expected".

Hope this makes sense. Thanks.

**Comment by aeschli** [comment] 2016-01-12 08:24
The map syntax is not yet supported. Duplicate of #1758

**Closed by aeschli** 2016-01-12 08:24 UTC
Labels: css-less-sass

**Comment by andrewhathaway** [comment] 2016-01-12 09:16
Any estimation on when this will be supported? Thanks.
