### ISSUE TITLE
editor widget selected entry's icon color recently forced to white

### ISSUE THREAD

**Issue by romain20100** [microsoft/vscode#126909] opened 2021-06-22 13:51 UTC
Does this issue occur when all extensions are disabled?: **Yes**

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (5 days ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. trigger any autocomplete such that an editor suggest widget opens with fields, methods or anything that has a coloured icon
2. The currently selected entry has an icon that is now always white even though each "kind" of suggestion has its color.

This is bugging me because I associate the white icon to snippets and unknown types.

Is it intentional that the icon is coloured white?

If it is, I would appreciate if it was possible to keep the normal icon color with an `editorSuggestWidget` setting.

This issue is recent, I think it appeared with the last update.

**Comment by gjsjohnmurray** [comment] 2021-06-22 14:25
see #126557

**Comment by usernamehw** [comment] 2021-06-22 14:25
/duplicate of #125998. It should be fixed in 1.58.0

**Closed** 2021-06-22 14:25 UTC
Labels: *duplicate
