### ISSUE TITLE
Syncup theme color in Markdown Preview

### ISSUE THREAD

**Issue by 1chooo** [microsoft/vscode#232826] opened 2024-11-01 14:05 UTC
### Description

The current Markdown preview is not synchronized with the theme, and the syntax colors do not match the selected theme. Even when switching to a different theme, the Markdown preview does not update accordingly.

### Screenshots

![Image](https://github.com/user-attachments/assets/b7702cdc-b0b0-4b69-a664-de0516059f52)

**Comment by mjbvz** [comment] 2024-11-01 16:13
Duplicate of #91279

**Closed by mjbvz** 2024-11-01 16:13 UTC
