### ISSUE TITLE
Git "fatal: Authentication failed for" error with new v1.62.2 

### ISSUE THREAD

**Issue by adriandelgg** [microsoft/vscode#137266] opened 2021-11-16 01:37 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Linux openSUSE Tumbleweed

Steps to Reproduce:

1. Upgrade to 1.62.2
2. Try to interact with Git like push

A lot of us are currently having the issue where we aren't able to push changes to GitHub anymore and getting a
fatal: Authentication failed for error.

This is because the newest version of VS Code (1.62.2) introduced this bug.

The way I solved it was by downgrading it to 1.62.1 & now it works perfectly again.

I'm on Linux, so this may not apply or work for you, but it should if all VS Code versions are the same across all OSs.

If you use openSUSE Tumbleweed like me, you can run the following command to downgrade:
`$ sudo zypper in --oldpackage code-1.62.1`

**Comment by bobert600** [comment] 2021-11-16 02:18
I'm also having this problem on Windows. I will downgrade to 1.62.1 soon if need be as I can't upload my completed code.

**Comment by Laethaka** [comment] 2021-11-16 04:26
`sudo apt install code=1.62.1-1636111026` also downgrades

**Comment by gjsjohnmurray** [comment] 2021-11-16 05:55
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Closed** 2021-11-16 05:56 UTC
Labels: *duplicate, new release
