### ISSUE TITLE
Disabled debuggers should not enable breakpoints for their `languages`

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#134143] opened 2021-09-29 16:49 UTC
Testing https://github.com/microsoft/vscode/issues/133146

1. Disable a debugger for a language via its `when` clause
2. You can still set breakpoints in the UI in files associated with that debugger

Should this be disallowed/removed?

**Comment by isidorn** [comment] 2021-09-29 16:57
Good point but duplicate of https://github.com/microsoft/vscode/issues/133585

**Closed by isidorn** 2021-09-29 16:57 UTC
