### ISSUE TITLE
Javascript highlighting

### ISSUE THREAD

**Issue by jabaz** [Microsoft/vscode#6948] opened 2016-05-26 23:47 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10 x64

Steps to Reproduce:
![unnamed](https://cloud.githubusercontent.com/assets/13858505/15593349/0753f4b4-23b4-11e6-92bd-aa73baaef5eb.png)

1. When i write this kind of code, part of it is highlighted as green
2. Example if i write `var testing = test ? console.log('true') : console.log('false')` it highlights text after **:**
![image](https://cloud.githubusercontent.com/assets/13858505/15593467/23efad1a-23b5-11e6-90f2-a9d03b9210a8.png)

3. So i think it happens when i use "var" and ":" in same line! and green color ends at "="

**Comment by aeschli** [comment] 2016-05-27 13:35
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81

**Closed by aeschli** 2016-05-27 13:35 UTC
