### ISSUE TITLE
typescript.npm doesn't work on Linux

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27762] opened 2017-05-31 17:27 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (3a6eda74ead5b5b041da0bbc18b70218e8c95bba, 2017-05-31T05:11:41.588Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.2|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

https://github.com/Microsoft/vscode/issues/27695

Steps to Reproduce:

Note that I installed nodejs via a package manager originally.

1.

  ```
  sudo mv /usr/bin/npm /usr/bin/npm2
  rm -rf ~/.cache/typescript
  ```

2. Verify that I get the error when attempting to fetch jquery types.
3. Close vscode.
4. Download nodejs and place in `/home/daniel/tools/node-v6.10.3-linux-x64`.
5. Launch VS Code
6. Set `"typescript.npm": "/home/daniel/tools/node-v6.10.3-linux-x64/bin/npm"`
7. Try get jquery ATA working, no error occurs but no types appear

  ![image](https://cloud.githubusercontent.com/assets/2193314/26645029/926ef472-45eb-11e7-9073-4ecba96b4324.png)

8. Check cache

```
$ ls ~/.cache/typescript/
package.json
$ cat ~/.cache/typescript/package.json
{}
```

**Comment by mjbvz** [comment] 2017-05-31 21:14
I can't reproduce this on ubuntu. Can you check the typings installer log / tsserver log?

**Comment by mjbvz** [comment] 2017-05-31 22:49
@Tyriar Also, can you confirm that you were in a workspace that was using TS 2.3.4 by running the `Select TypeScript Version` command

**Comment by Tyriar** [comment] 2017-05-31 23:03
Yes the TS version was the issue, maybe the message could be more clear that it's not supported then?

**Comment by mjbvz** [comment] 2017-06-01 00:23
Closing as this is expected then

The version required is mentioned in the setting description and the docs https://github.com/Microsoft/vscode-docs/blob/vnext/docs/languages/javascript.md#fixing-npm-not-installed-warning-for-automatic-type-acquisition 

The warning message itself is getting pretty long already so I'll look into seeing if we can improve this in any way for the May release

**Closed by mjbvz** 2017-06-01 00:23 UTC
Labels: bug, important, linux, needs more info, typescript
