### ISSUE TITLE
[json] npm package tooltip not working for @ namespaced packages

### ISSUE THREAD

**Issue by SkaterDad** [Microsoft/vscode#2109] opened 2016-01-19 14:25 UTC
When in `package.json`, the tooltips that show you more information about npm packages on mouse hover are not working if the package name is namespaced.

For example: `@cycle/core` does not show any information, but `express` shows the description and latest version number.

I'm on version 0.10.6.

**Comment by aeschli** [comment] 2016-08-30 08:18
duplicate of #10541

**Closed by aeschli** 2016-08-30 08:18 UTC
Labels: bug, json
