### ISSUE TITLE
hi vscode, fixed vietnamse code language please

### ISSUE THREAD

**Issue by lyquocnam** [Microsoft/vscode#2196] opened 2016-01-23 05:57 UTC
i report many times about this, but not fixed yet... so sad.
i recored my screen 
https://youtu.be/Hb4tLqiyuNs
i use unikey ( simple and popular vietnamese language tool ) + vscode.
but it not work.
i try to many other language tool but still not working...
and other editor: sublimetext, atom it good work.. (sorry about this compare )

**Comment by Tyriar** [comment] 2016-01-23 15:45
Duplicate of https://github.com/Microsoft/vscode/issues/1168

**Comment by alexandrudima** [comment] 2016-01-25 10:46
@lyquocnam Thank you, the video is helpful in helping me understand how to use UniKey. Let's track this in #1168

**Closed** 2016-01-25 10:47 UTC
Labels: editor
