### ISSUE TITLE
Reveal in Finder with multi-selection in same folder does not work

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#42685] opened 2018-01-31 23:13 UTC
Testing #41473.

On macOS.

1. Open a workspace that contains several folders
2. Select file F1 in folder A.
3. Select files F2 and F3 in folder B.
4. `Reveal in Finder` from context menu.
-> two finder windows open, one for A and one for B
-> F1 is selected in the first window
-> F3 is selected in the second window

This shows that a multi-selection works in general for Reveal in Finder. However, it does not work as expected if all files in the selection are in the same folder.

**Comment by isidorn** [comment] 2018-02-01 14:08
Duplicate of https://github.com/Microsoft/vscode/issues/42576

**Closed by isidorn** 2018-02-01 14:08 UTC
