### ISSUE TITLE
Watching too many files on WSL #153731

### ISSUE THREAD

**Issue by richtera** [microsoft/vscode#153734] opened 2022-06-29 18:09 UTC
Issue Type: <b>Bug</b>

I am seeing the same thing on non-insider build:
```sh
$ ./list-watchers 

   INOTIFY   INSTANCES
   WATCHES      PER   
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
  470103         1     10271 andy        /home/andy/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/node /home/andy/.vscode-server/bin/30d9c6cd9483b2cc586687151bcb
    1364         1      3639 andy        /home/andy/.vscode-server-insiders/bin/53130238b422606ffcd616126fb8c6c81c6e4436/node /home/andy/Development/nx-workspace/node_modules/
       9         1     10214 andy        /home/andy/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/node /home/andy/.vscode-server/bin/30d9c6cd9483b2cc586687151bcb

  471476  WATCHES TOTAL COUNT

INotify instances per user (e.g. limits specified by fs.inotify.max_user_instances): 

INSTANCES    USER
-----------  ------------------
3            andy
```
I was unable to update watch exclude in either build to limit the number of files. But I am kind of dead in the water.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (33.06GB free)|
|Process Argv|--crash-reporter-id db2c49a0-c178-4fe7-b9ea-930397e91764|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|31.35GB (17.31GB free)|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
quokkasyntax|aid|1.2.4
project-manager|ale|12.6.0
language-hugo-vscode|bud|1.3.1
dotenv|mik|1.0.1
vscode-edge-devtools|ms-|2.1.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
fish-vscode|sky|0.2.1
vscode-nvm|abu|0.0.1
project-manager|ale|12.6.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.14.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
go|gol|0.34.0
go-nightly|gol|2022.6.2820
gc-excelviewer|Gra|4.2.55
kite|kit|0.147.0
vscode-docker|ms-|1.22.0
python|ms-|2022.8.1
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
cpptools|ms-|1.10.7
angular-console|nrw|17.18.6
prettier-vscode|pre|3.14.1
markdown-preview-enhanced|shd|0.6.3
stately-vscode|sta|1.8.3
vsfire|tob|1.4.1
pdf|tom|1.2.0
har-viewer|unc|0.0.1
docker|vsc|1.0.0
yaml|vsc|1.0.0
clang-format|xav|1.9.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment] 2022-06-29 18:30
Duplicate of #153731

**Closed by mjbvz** 2022-06-29 18:30 UTC
