### ISSUE TITLE
Allow per-language settings for addons.

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode#19642] opened 2017-01-31 22:08 UTC
- VSCode Version: Version 1.9.0-insider (fcac9b686abe4292e69a774f61c8c4ce17768bf5)
- OS Version: Arch Linux

Right now per-language settings work for editor settings only, it would be really nice to be able to control addons too.

For example I use tslint for both JS and TS, however I'd like to enable `"tslint.autoFixOnSave": true` for typescript files only.

**Comment by sandy081** [comment] 2017-02-02 14:44
This is a good use case. Since language based settings feature is new we would like to gather more feedback and new requirements before committing. Hence keeping this in backlog.

**Comment by sandy081** [comment] 2017-02-02 14:45
Just to note that this feature need contribution from the extension side to support

**Comment by sandy081** [comment] 2017-11-20 09:01
Duplicate of #26707

**Closed** 2017-11-20 09:02 UTC
Labels: *duplicate, config, feature-request
