### ISSUE TITLE
Enhancement - search project dir by filename

### ISSUE THREAD

**Issue by perfecto25** [Microsoft/vscode#25781] opened 2017-05-02 15:03 UTC
currently if I open a dir with large # of files, I dont see a way to search for a file, I can only search inside open files, 

lets say I want to find file named file68, i have to scroll all the way down, In this example its easy because of numerical naming, but in real examples I spend lot of time scrolling through hundreds of files to find the right file to edit, should be an easier way. 

![vc2](https://cloud.githubusercontent.com/assets/10224886/25624318/fa9d0c90-2f26-11e7-84c4-88273ea8fd5c.png)

**Comment by eliashdezr** [comment] 2017-05-02 15:18
If you type F1 and then remove the angle bracket, you can search by filenames in the project.

**Comment by guyellis** [comment] 2017-05-02 15:19
@perfecto25 Did you know that `Ctrl/Cmd + p` allows you to find file patterns by typing parts of their names?

**Comment by perfecto25** [comment] 2017-05-02 17:04
awesome thankx for the tip.

**Comment by kieferrm** [comment] 2017-05-02 18:09
See tips above. Otherwise, this is a duplicate of #10026.

**Closed by kieferrm** 2017-05-02 18:09 UTC
