### ISSUE TITLE
JavaScript computed method names break syntax highlighting

### ISSUE THREAD

**Issue by ilogico** [Microsoft/vscode#10297] opened 2016-08-08 11:17 UTC
- VSCode Version: 1.4
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. create a class with computed method names like:

const _privateMethod = Symbol();

class MyClass {
  [_privateMethod]() {
    return 42;
  }
}

2. You should see the syntax highlighting is broken for the rest of the class declaration.

**Comment by wallverb** [comment] 2016-08-08 12:11
The same issue with TypeScript. 

Interesting that github's coloring gets also broken for `ts`

```ts
class MyClass {
 [_privateMethod]() {
  return 42;
 }
 test() {
 }
}
```

but is ok for js:
```js
class MyClass {
 [_privateMethod]() {
  return 42;
 }
 test() {
 }
}
```

**Comment by glen-84** [comment] 2016-08-08 12:54
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/236 (?).

**Comment by aeschli** [comment] 2016-08-08 13:02
Yes, that looks like a dup of Microsoft/TypeScript-TmLanguage#236 . Thanks @glen-84

**Closed by aeschli** 2016-08-08 13:02 UTC
