### ISSUE TITLE
can css editor expend/un-expend code?

### ISSUE THREAD

**Issue by wwfifi** [Microsoft/vscode#1631] opened 2015-12-24 07:09 UTC
if css have mutiple @media marks and so many style items, coding jump is hard.
if css code can expend/un-expend, may make it easy.

**Comment by glen-84** [comment] 2015-12-24 08:36
Duplicate of #105?

**Comment by bpasero** [comment] 2015-12-24 08:58
Yup.

**Closed by bpasero** 2015-12-24 08:58 UTC
