### ISSUE TITLE
Integrated terminal does not receive break command when using Node debugger

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#41655] opened 2018-01-16 07:15 UTC
See video:

[http://streaka.testing.videos.s3.amazonaws.com/screencast_2018-01-16_14-07-36.mp4](http://streaka.testing.videos.s3.amazonaws.com/screencast_2018-01-16_14-07-36.mp4)

This is a major pain in the butt. Any ideas?

Using latest VSCode 1.19.2, macOS Sierra.

Using Node 8.8.1

**Comment by jpike88** [comment] 2018-01-16 07:16
Found the issue!

"port":0

^ that configuration caused it.

I don't think it should any effect on killing the process.

**Comment by jpike88** [comment] 2018-01-16 07:22
This also prevents the terminal from killing the process on the 'stop' command.

**Comment by jpike88** [comment] 2018-01-16 07:29
This issue appears to originate in the node debugger.

https://github.com/Microsoft/vscode-node-debug/issues/168

**Comment by isidorn** [comment] 2018-01-16 08:45
@jpike88 thanks for the investigation, closing as a duplicate of that issue

**Closed by isidorn** 2018-01-16 08:45 UTC
