### ISSUE TITLE
Menus do not work on Windows 10 build 15025.rs_prerelease

### ISSUE THREAD

**Issue by djensen47** [Microsoft/vscode#19698] opened 2017-02-01 23:05 UTC
- VSCode Version: I don't know because I can't open the menus
- OS Version: Windows 10 build 15025.rs_prerelease

Steps to Reproduce:

1. Install WIndows 10 15025.rs_prerelease
2. Click on File, Edit, Selection, View, Go, Help (or try keyboard shortcuts)

Expected result: menu opens
Actual result; the menu doesn't open or the menu is not visible

**Comment by bpasero** [comment] 2017-02-02 06:20
@djensen47 that is weird! 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by be5invis** [comment] 2017-02-02 08:31
Another image, from https://www.zhihu.com/question/55328189?group_id=810523368477581312
![](https://pic1.zhimg.com/v2-c170ddc40bf0a06eebfbf6bca20e2a10_b.jpg)

**Comment by dragonJACson** [comment] 2017-02-02 08:43
When I click the invisible menu, it actually worked,but I can only see the program but not the menu. AKA, menu exists there, but the program is like ghost.

**Comment by bpasero** [comment] 2017-02-02 08:54
This sounds like a Windows bug to me with a pre-release version of Windows 10

**Comment by be5invis** [comment] 2017-02-02 09:22
https://insider.windows.com/FeedbackHub/fb?contextid=52&feedbackid=04a842d2-6eed-4452-b96a-5c64e7c2b3eb&form=1

**Comment by djensen47** [comment] 2017-02-02 18:52
Yeah, it turns out this happens with several apps built on Electron. gVim,
however, seems to be unaffected.

Sorry, I can't try the latest nightly because I rolled back the Windows 10
update. Everything works on the previous Windows build.

**Comment by be5invis** [comment] 2017-02-02 18:54
@gongminmin ← WDG DWM guy

**Comment by Rhywden** [comment] 2017-02-03 10:34
@bpasero Can confirm that the issue still exists with the insider build I just downloaded.

**Comment by Rhywden** [comment] 2017-02-03 13:13
@bpasero However, here's the weird thing I just discovered: My desktop does _not_ have this issue, only my Surface Book.

Even though both are on the same Windows Insider build.

**Comment by Rhywden** [comment] 2017-02-03 20:46
Okay, I found the source of the issue - it's the DPI scaling. If it's set to 200% or above (which is the default for a Surface Book with its 3000 by 2000 resolution) then I don't see the menus. If I set the scaling to anything below 200% (i.e. 175% to 100%) then it works normally again.

**Comment by gongminmin** [comment] 2017-02-04 00:00
Found something more interesting.
1. Only repro when DPI is 200%, not 175% nor 225%.
2. Not only VSCode's menu get occluded, but also other menus, such as the menu popup when right-click on desktop.
3. In screen print, it looks right.

**Comment by zhengbli** [comment] 2017-02-04 00:01
Have issues with %250 as well. Sometimes the right-click menu does not show up on this build.
Happens for Chrome as well.

**Comment by EternalPhane** [comment] 2017-02-04 11:09
mine's %125, but the menu still hides behind the window (= =)
seems to be related with both dpi and resolution

**Comment by danieldjordan** [comment] 2017-02-06 17:46
Same Issue.
Resolution: 3200x1800
DPI Scaling: 175%
Windows Version: 15025.rs_prerelease
VS.Code Version: 1.10.0-insider

Taking a screenshot brings the menu in front of the app.

**Comment by djensen47** [comment] 2017-02-08 22:45
There's a new Windows Insider Fast Ring build. Has anybody tried 15031 yet? Is the issue still there?

**Comment by gongminmin** [comment] 2017-02-09 01:59
Tried on 15032, no repro anymore.

**Comment by madcampos** [comment] 2017-02-09 02:17
Same here.
Surface book, with windows build 15025 and scaling of 200%.
It's known that there is problems with this build and scaling.
Tested on version 1.9 of vscode, the prior version (1.8.1) worked as expected in the same windows build.
Insiders build don't work either.

**Comment by djensen47** [comment] 2017-02-09 10:28
> @gongminmin 
> Tried on 15032, no repro anymore.

Do you mean to say that the issue is resolved in 15032?

**Comment by zhengbli** [comment] 2017-02-09 17:23
Nope, on 15033 even, still see this.

**Comment by zhengbli** [comment] 2017-02-11 06:31
Seems fixed in an internal build 15035. So the fix should be available for next insider build I think

**Comment by bpasero** [comment] 2017-02-20 13:28
Ok thanks.

**Closed by bpasero** 2017-02-20 13:28 UTC
Labels: needs more info, upstream
