### ISSUE TITLE
Navigation in JS doesn't work

### ISSUE THREAD

**Issue by pom421** [Microsoft/vscode#28495] opened 2017-06-12 08:14 UTC
- VSCode Version: 1.13
- OS Version: Mac OS 10.12

I wonder how to navigate in Javascript code in VS code. 
To figure out the behavior, I made this little project : 

- js
- js/index.js
- js/foo.js

index.js

    var person = {}
    
    person.name = "azeaze"
    
    person.sayHello = function() {
      console.log("Hi! My name is ", this.name)
    }

foo.js

    console.log('In foo module')
    
    person.sayHello()

jsconfig.json

    {
        "compilerOptions": {
            "target": "ES5"
        },
        "exclude": [
            "node_modules"
        ],
        "include": [
            "js/*"
        ]
    }

What I need is to navigate, from the foo.js file when I click on person.sayHello. I tried Cmd-click or F12 but VS Code replies "No definition found for sayHello". Why VS code can't?

May be the use of module is required? If so, is there a way to handle legacy code (pure ES5 code) who don't provide it? And what the purpose of "include" in jsconfig.json, if the IDE only need to follow the require? 

Edit : 
I tried to follow this answer https://stackoverflow.com/questions/28559881/debugging-navigating-js-code-in-visual-studio, that is to say add to foo.js : 

    /// <reference path="../Path/To/The/Referenced/index.js" />

But F12 navigation still doesn't work.

**Comment by mjbvz** [comment] 2017-06-12 16:50
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/10868 . The TypeScript service that powers our JS and TS language currently cannot recognize properties added to an object after it is created.

The best workaround is to define all the properties in the object literal:

```js
var person = {
   name: "azeaze",
   sayHello: function() {
     console.log("Hi! My name is ", this.name)
  }
}
```

or to add an explicit type using jsdocs:

```js
/**
 * @type {{ name: string, sayHello: () => void}}
 */
// @ts-ignore
var person = {}

person.name = "azeaze"

person.sayHello = function() {
  console.log("Hi! My name is ", this.name)
}
```

**Closed by mjbvz** 2017-06-12 16:50 UTC
Labels: new release
