### ISSUE TITLE
whether i can get all completionitem list include vscode itself provided in plugin api  "registerCompletionItemProvider"?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#956] opened 2015-12-03 09:39 UTC
whether vscode can change the mechanism that make me can get all all completionitem list include vscode itself provided in the following method provideCompletionItems in my vscode plugin? where I can know how vscode deal with this in vscode source?

	vscode.languages.registerCompletionItemProvider("javascript",
	{
		resolveCompletionItem(item:vscode.CompletionItem, token: vscode.CancellationToken): vscode.CompletionItem 
		{
		var completionItem1:vscode.CompletionItem = new vscode.CompletionItem("id");
		completionItem1.detail = "aaa";
		completionItem1.filterText = "aa";
		completionItem1.insertText = "aa";
		return completionItem1;
		}
		,
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): Promise<vscode.CompletionItem[]> 
		{
			return new Promise((resolve, reject) => { 
			var completionItems:vscode.CompletionItem[] = [];
	
			return resolve(completionItems) ;
						});
		}
	})

**Comment by jrieken** [comment] 2015-12-03 11:12
@BleyChen Is this a bug or a feature request? Please provide more detail ala actual behaviour vs. expected behaviour

**Comment by BleyChen** [comment] 2015-12-03 12:58
yes, recently i was reading the vscode source and i want to know whether i can change the vscode source that make me can get all the completionitem list in method "provideCompletionItems".

**Comment by BleyChen** [comment] 2015-12-07 02:27
I have add the comment that what i want as following:
![testaaa](https://cloud.githubusercontent.com/assets/15098626/11617653/e7d586f2-9ccc-11e5-8f8c-b1cbd5dba27b.png)

**Comment by jrieken** [comment] 2015-12-07 09:16
Yes but with care only. With the Dec15 update you can invoke this command `https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostLanguageFeatureCommands.ts#L55` to retrieve the same list of completions the UI would show. Note, that it will recurse into your `provideCompletionItems` call so that you must guard yourself to not recurse endless.

**Comment by jrieken** [comment] 2015-12-07 09:17
Duplicate of #913

**Closed by jrieken** 2015-12-07 09:16 UTC
Labels: needs more info
