### ISSUE TITLE
Tree view corruption

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#48274] opened 2018-04-20 12:49 UTC
My extension implements a tree view.

I've tried to provide a filter function which hides entries which don't match and calls reveal on all the entries which do. This sort of works, providing I do the reveals after a short timeout.

Sometimes however, something goes wrong and the view gets mixed up:

![image](https://user-images.githubusercontent.com/376658/39051566-001feab2-44a1-11e8-9b38-1692f7e1cd26.png)

Note that the top elements in the view are not children of anything (the view is scrolled to the top), and should actually be under "March".

Unfortunately, I can't reproduce it reliably at the moment.

**Comment by Gruntfuggly** [comment] 2018-04-20 14:08
Another related problem - sometimes the entries are repeated:

![image](https://user-images.githubusercontent.com/376658/39055539-6d2518c0-44ac-11e8-8e7f-ca219f0fd81b.png)

Clicking on one of them hights more than one.

In this state, scrolling only affects the bottom half of the list?

**Comment by Gruntfuggly** [comment] 2018-04-20 14:09
This is on Ubuntu, version 1.22.2.

**Comment by Gruntfuggly** [comment] 2018-04-22 21:30
I've done some more investigation and if I comment out the calls to reveal it's fine. Seems like there may be a threading issue or something when calling reveal?

**Comment by sandy081** [comment] 2018-04-23 08:13
@Gruntfuggly Can you please provide a simple sample to reproduce it. It will be helpful to reproduce and fix the issue.

**Comment by Gruntfuggly** [comment] 2018-04-23 10:40
Hmm - might be tricky as you'd need some data for the extension to process. I'll see if I can produce a minimal example.

**Comment by sandy081** [comment] 2018-04-23 14:29
That would be great.

**Comment by sandy081** [comment] 2018-05-23 16:29
@Gruntfuggly I am marking this as a duplicate of #50336 and you can verify if the fix also fixes this.

**Closed** 2018-05-23 16:30 UTC
Labels: *duplicate, explorer-custom, needs more info
