### ISSUE TITLE
Extension installation fails to verify signature on REMOTE release

### ISSUE THREAD

**Issue by jlynchMicron** [microsoft/vscode#173327] opened 2023-02-03 16:34 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.75.0
- OS Version: CentOS Version 7

Steps to Reproduce:

1. Open up new VScode remote session.
2. Try to update any extension.

Tagging maintainer per request: @dtivel 

Important note: Using identical corporate proxy settings for both environments, which worked before latest VScode update 1.75.

Windows 11 Host (extensions install fine):
![image](https://user-images.githubusercontent.com/58755604/216655668-52ec388e-997d-4acb-b7ba-842347603edc.png)

Linux Remote SSH Session (extensions not installing, note the python extension):
![image](https://user-images.githubusercontent.com/58755604/216656042-f67fca22-c43d-479d-8c41-02a41126a872.png)

**Comment by cuzox** [comment] 2023-02-03 19:59
Facing same issue

**Comment by eleanorjboyd** [comment] 2023-02-03 20:46
Hello! We are seeing a few people facing this issue. The error message is `Signature Untrusted`. We will keep this issue as the main issue to track the progress here. 

Currently, the workaround seems to be to downgrading vscode. As seen from user @inh3 `Same issue. Downgraded VSCode to 1.74.3 to restore functionality.` in https://github.com/microsoft/vscode/issues/173215.

The issue is also reported on the remote-release extension here: https://github.com/microsoft/vscode/issues/173215

**Comment by dtivel** [comment] 2023-02-03 21:19
Does the file at `/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem` contain certificates?

**Comment by jlynchMicron** [comment] 2023-02-03 21:21
> Does the file at `/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem` contain certificates?

Yes:
![image](https://user-images.githubusercontent.com/58755604/216713035-43a279a0-a6f5-4752-a1e8-a693ca02271b.png)

**Comment by jlynchMicron** [comment] 2023-02-03 21:23
> Does the file at `/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem` contain certificates?

Yes, it appears to have my organizations certificate in it based on the comment.

**Comment by dtivel** [comment] 2023-02-03 21:26
It probably does not have [this root certificate](https://crt.sh/?q=552f7bdcf1a7af9e6ce672017f4f12abf77240c78e761ac203d1d9d20ac89988).  Can you confirm?

```
-----BEGIN CERTIFICATE-----
MIIFkDCCA3igAwIBAgIQBZsbV56OITLiOQe9p3d1XDANBgkqhkiG9w0BAQwFADBi
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkIFJvb3Qg
RzQwHhcNMTMwODAxMTIwMDAwWhcNMzgwMTE1MTIwMDAwWjBiMQswCQYDVQQGEwJV
UzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQu
Y29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkIFJvb3QgRzQwggIiMA0GCSqG
SIb3DQEBAQUAA4ICDwAwggIKAoICAQC/5pBzaN675F1KPDAiMGkz7MKnJS7JIT3y
ithZwuEppz1Yq3aaza57G4QNxDAf8xukOBbrVsaXbR2rsnnyyhHS5F/WBTxSD1If
xp4VpX6+n6lXFllVcq9ok3DCsrp1mWpzMpTREEQQLt+C8weE5nQ7bXHiLQwb7iDV
ySAdYyktzuxeTsiT+CFhmzTrBcZe7FsavOvJz82sNEBfsXpm7nfISKhmV1efVFiO
DCu3T6cw2Vbuyntd463JT17lNecxy9qTXtyOj4DatpGYQJB5w3jHtrHEtWoYOAMQ
jdjUN6QuBX2I9YI+EJFwq1WCQTLX2wRzKm6RAXwhTNS8rhsDdV14Ztk6MUSaM0C/
CNdaSaTC5qmgZ92kJ7yhTzm1EVgX9yRcRo9k98FpiHaYdj1ZXUJ2h4mXaXpI8OCi
EhtmmnTK3kse5w5jrubU75KSOp493ADkRSWJtppEGSt+wJS00mFt6zPZxd9LBADM
fRyVw4/3IbKyEbe7f/LVjHAsQWCqsWMYRJUadmJ+9oCw++hkpjPRiQfhvbfmQ6QY
uKZ3AeEPlAwhHbJUKSWJbOUOUlFHdL4mrLZBdd56rF+NP8m800ERElvlEFDrMcXK
chYiCd98THU/Y+whX8QgUWtvsauGi0/C1kVfnSD8oR7FwI+isX4KJpn15GkvmB0t
9dmpsh3lGwIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIB
hjAdBgNVHQ4EFgQU7NfjgtJxXWRM3y5nP+e6mK4cD08wDQYJKoZIhvcNAQEMBQAD
ggIBALth2X2pbL4XxJEbw6GiAI3jZGgPVs93rnD5/ZpKmbnJeFwMDF/k5hQpVgs2
SV1EY+CtnJYYZhsjDT156W1r1lT40jzBQ0CuHVD1UvyQO7uYmWlrx8GnqGikJ9yd
+SeuMIW59mdNOj6PWTkiU0TryF0Dyu1Qen1iIQqAyHNm0aAFYF/opbSnr6j3bTWc
fFqK1qI4mfN4i/RN0iAL3gTujJtHgXINwBQy7zBZLq7gcfJW5GqXb5JQbZaNaHqa
sjYUegbyJLkJEVDXCLG4iXqEI2FCKeWjzaIgQdfRnGTZ6iahixTXTBmyUEFxPT9N
cCOGDErcgdLMMpSEDQgJlxxPwO5rIHQw0uA5NBCFIRUBCOhVMt5xSdkoF1BN5r5N
0XWs0Mr7QbhDparTwwVETyw2m+L64kW4I1NsBm9nVX9GtUw/bihaeSbSpKhil9Ie
4u1Ki7wb/UdKDd9nZn6yW0HQO+T0O/QEY+nvwlQAUaCKKsnOeMzV6ocEGLPOr0mI
r/OSmbaz5mEP0oUA51Aa5BuVnRmhuZyxm7EAHu/QD09CbMkKvO5D+jpxpchNJqU1
/YldvIViHTLSoCtU7ZpXwdv6EM8Zt4tKG48BtieVU+i2iW1bvGjUI+iLUaJW+fCm
gKDWHrO8Dw9TdSmq6hN35N6MgSGtBxBHEa2HPQfRdbzP82Z+
-----END CERTIFICATE-----
```

**Comment by jlynchMicron** [comment] 2023-02-03 21:29
It looks like it does not have that one:
![image](https://user-images.githubusercontent.com/58755604/216714278-d48a0f23-6591-4b85-9408-11a60c59868d.png)

**Comment by dtivel** [comment] 2023-02-03 22:08
The code signing certificate that VS Marketplace uses to repository sign extensions chains to this root, so trusting this root will resolve the `Untrusted` error you're seeing.

To verify extensions signed with this certificate, VS Code requires a certificate trust store that is valid for code signing.

Linux doesn't reliably have this, so VS Code defaults to using its own built-in trust store.  This built-in trust store is effectively a snapshot of the Windows trust store that is valid for code signing and contains this root certificate.

For the Linux distributions (like Red Hat and CentOS) that do have this established system (root-owned) code signing trust store, we want to respect it.  The intent here is to reuse a system-managed trust store if we can.

`/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem`

I see a few options:

* Add the root certificate to your PEM file.  This is a system-wide change, so you should be comfortable with the change.
* Set the `extensions.verifySignature` option to `false` in the right setting file (remote, in your case).  This should be considered a short-term workaround, and the option may disappear in the future.
* Downgrade to 1.74.3.

For now, I'd choose the 2nd option.

CC @isidorn

**Comment by jlynchMicron** [comment] 2023-02-03 22:25
@dtivel, thank you for looking into this!  Yeah I don't think my organization would let us tamper with the system root certificate.

I can go with option 2 for now, but if that option disappears in the future, I'm not sure what options we will have down the road.

**Comment by jlynchMicron** [comment] 2023-02-03 22:35
> * Set the `extensions.verifySignature` option to `false` in the right setting file (remote, in your case).  This should be considered a short-term workaround, and the option may disappear in the future.

Do I have to do anything to enable it?  It does not look like VScode is recognizing it as a "real" setting:
![image](https://user-images.githubusercontent.com/58755604/216723985-79a4dcb9-7904-4ec9-b16c-a8ec1a1b635d.png)

**Comment by dtivel** [comment] 2023-02-04 00:35
It looks correct.  Make sure you put it in your remote settings if you're having problems on the remote side.  You can leave local settings as-is (enabled).

**Comment by sandy081** [comment] 2023-02-04 17:22
@dtivel 

Thanks for jumping on to this and inspecting the issue. 

### Immediate Workaround

Disable signing verification manually

- Open Settings UI
- Go to Remote Settings Tab
- Open the Settings file by clicking on the button available on the top right corner
- Add this setting `"extensions.verifySignature": false`

<img width="747" alt="Screenshot 2023-02-04 at 18 06 45" src="https://user-images.githubusercontent.com/10746682/216780209-974e4422-3965-4540-9ecd-fe9d044f4caa.png">

### Recovery

- Disable signing automatically for the platforms where this can happen

### Long term

- Come up with a solution where we can verify signing successfully in these cases

**Comment by ismail** [comment] 2023-02-04 19:34
This doesn't seem to work here:

```
❯ cat .vscode-server/data/Machine/settings.json
{
    "extensions.verifySignature": false
}
```

Also, a better option would be to be able to force VS Code to use its internal certificate store.

**Comment by zulrang** [comment] 2023-02-05 23:39
@sandy081 
1. That's not a valid setting
2. It doesn't work

**Comment by ByronHsu** [comment] 2023-02-06 03:10
Downloading [vscode](https://code.visualstudio.com/updates/v1_74) `1.74.3` can suppress this issue.

**Comment by bluebandit21** [comment] 2023-02-06 03:35
Potentially helpful workaround for anyone experiencing the same problem --
Downloading the VSIX of the extension you want to install (say, from their repository), copying over to the remote, and then using the 
`Extensions: Install from VSIX...` command from the command palette to install it seems to work :)

Definitely not a fix to the actual problem, but seems like a reasonably easy way to get extensions onto a remote without having to downgrade.

**Comment by maciejmatczak** [comment] 2023-02-06 07:12
@zulrang , worked for me after killing a server process on a target machine.

Reload Windows, close/open VS Code did not help. Only after a "power cycling" a VS Code process server worked.

**Comment by sandy081** [comment] 2023-02-06 07:44
@zulrang Setting should work even without restart / reload. Where are you applying this setting ? I mean in which file?

**Comment by tomba4** [comment] 2023-02-06 08:27
@sandy081 there's simply no such setting as "extensions.verifySignature".

BTW, I reverted to 1.74.3 but then it turned out ALL MY REMOTE EXTENSIONS WERE GONE. What the... is happening?

**Comment by sandy081** [comment] 2023-02-06 08:34
@tomba4 Yes, it is not a registered setting. You have to open the file and add this. May I know if you have done what is mentioned in this [comment](https://github.com/microsoft/vscode/issues/173327?notification_referrer_id=NT_kwDOAKP7OrM1NTA2NzUyMzcwOjEwNzQ2Njgy&notifications_query=is%3Aunread#issuecomment-1416805325)

**Comment by tomba4** [comment] 2023-02-06 08:43
@sandy081 the screenshot in that comment was explicitly showing the GUI version of the settings, and there the option is not available. I haven't tried it then.

**Comment by sandy081** [comment] 2023-02-06 08:54
@tomba4  Ok, I will update the comment and screenshot - mentioning to add the setting in the file. Can you please set this setting and let me know if it works.

**Comment by tomba4** [comment] 2023-02-06 09:00
@sandy081 I managed to restore my environment from backups on 1.74.3, so it's working again for me. But 1.75 itself is completely broken as it seems...

**Comment by sandy081** [comment] 2023-02-06 09:10
@tomba4 Is it ok, if you can please upgrade to 1.75 using following steps:

- Update the remote settings to use `extensions.verifySignature` and set it to `false`
- Upgrade to 1.75
- Try to install extensions and make sure it works

**Comment by ismail** [comment] 2023-02-06 09:17
> @zulrang Setting should work even without restart / reload. Where are you applying this setting ? I mean in which file?

It doesn't seem to work like that, looks a process on the server side is not picking it up. It worked for me after half an hour or so. I didn't manually kill/restart anything on the server side.

**Comment by shaoqx** [comment] 2023-02-06 21:07
Facing the same problem here on the remote server. I found it first with my home laptop and again with my working PC once I updated VSCode on the PC to 1.75.0. 
Tried the 2nd fix with `extensions.verifySignature`. It only works after I killed the current Code server with `Remote-SSH: Kill Current VS Code Server`

**Comment by LsYueh** [comment] 2023-02-07 00:20
> Facing the same problem here on the remote server. I found it first with my home laptop and again with my working PC once I updated VSCode on the PC to 1.75.0. Tried the 2nd fix with `extensions.verifySignature`. It only works after I killed the current Code server with `Remote-SSH: Kill Current VS Code Server`

Proofed, and works will. thanks for the information.

### If Already Upgrade to 1.75 
1. Update the remote settings to use `extensions.verifySignature` and set it to `false`
2. Killed the current Code server with `Remote-SSH: Kill Current VS Code Server`
3. (Disconnected from Remote)
4. Restart host VS Code
5. Try to install extensions and make sure it works
6. Done

**Comment by xiaoshude** [comment] 2023-02-07 02:45
> > @shaoqx Facing the same problem here on the remote server. I found it first with my home laptop and again with my working PC once I updated VSCode on the PC to 1.75.0. Tried the 2nd fix with `extensions.verifySignature`. It only works after I killed the current Code server with `Remote-SSH: Kill Current VS Code Server`
> 
> Proofed, and works well. thanks for the information.
> 
> ### If Already Upgrade to 1.75
> 1. Update the remote settings to use `extensions.verifySignature` and set it to `false`
> 2. Killed the current Code server with `Remote-SSH: Kill Current VS Code Server`
> 3. (Disconnected from Remote)
> 4. Restart host VS Code
> 5. Try to install extensions and make sure it works
> 6. Done
work for me!

**Comment by isidorn** [comment] 2023-02-07 12:33
@dtivel @sandy081 and me discussed this and we decided on the following: for Linux distributions (like Red Hat and CentOS) that do have this established system (root-owned) code signing trust store, we will still give priority to the trust store that is shipped with VS Code. This way we can be 100% sure that the trust store we use is valid for code signing.

This fix will be included in the next Stable release that we plan to do on Wednesday or Thursday.

In our February milestone we plan to introduce a setting, for example `"extensions.signatureTrustStore" "product" | "system" `(default is "product") that will allow users to control what trust store should VS Code use. In the future when VS Code introduces more settings to be admin controlled, this can be the mechanism for system admins to control what trust store is to be used.

After you get this stable update I would kindly ask all of you to remove the `extensions.verifySignature: false` from your settings, because we want signature verification to not be disabled and to hear if there are any other issues that we might have not fixed. Thank you very much!

**Comment by isidorn** [comment] 2023-02-07 14:14
Closing this issue as I have verified that our fix indeed fixes the problem on CentOS.

However it would be great if someone from the community also tries out and confirms to us that the issue is indeed fixed (make sure to remove `extensions.verifySignature: false` from your settings).

Here's the link to the Linux x64 build https://az764295.vo.msecnd.net/stable/dd1dbfeecbd06802a4a357767fedeb5a6268cf71/code-stable-x64-1675778107.tar.gz

Thank you

**Closed by isidorn** 2023-02-07 14:14 UTC
Labels: bug, extensions, candidate

**Comment by ByronHsu** [comment] 2023-02-07 20:42
@isidorn I am using vscode on macOS and connecting to remote centOS, and I also suffered from this issue. Will there be a new macOS vscode release to fix the issue?

**Comment by sandy081** [comment] 2023-02-08 08:29
@ByronHsu  Yes, it fixes your scenario too.

**Comment by grandmasteri** [comment] 2023-02-08 23:45
I am connecting from MacOS to Linux host but none of the above fixes worked for me. I tried everything in [xiaoshude](https://github.com/xiaoshude)'s [comment](https://github.com/microsoft/vscode/issues/173327#issuecomment-1420116931) which summarizes all the fixes in this thread so far but I still get an "Untrusted" error (I used the Docker extension as the example in the blow screenshot)
![image](https://user-images.githubusercontent.com/31323121/217677310-50ea8e4f-0e79-4d88-a8c3-41c1ec442a08.png)

**Comment by sandy081** [comment] 2023-02-09 08:27
@grandmasteri Can you please share following logs while the issue happens?

- F1 > Open View... > Remote Server
- F1 > Open View... > Window

**Comment by xcmz** [comment] 2023-02-09 08:28
@grandmasteri 

for mac2centos, in additional to the workaround, following may help.
1. restart remote server.
2. directly connect to remote server, instead of the project,

**Comment by Rhahkeem** [comment] 2023-02-22 18:14
FWIW this also happens in the Dev-Containers extension workflow. I can't install any extensions in the container and if I update the settings file, since it doesnt get picked up I have to rebuild the container, which ultimately wipes out the settings.json all over again

**Comment by gusarov** [comment] 2023-03-16 21:21
I now see the same on Windows... disabled verify signature, updated everything, including VSCode (apparently had tons of not installed updates for extensions). But as soon as I enable it back, extension installation are no longer works with exact same error

**Comment by darionesi** [comment] 2023-03-17 15:14
@Rhahkeem @gusarov does the issue have similar symptoms to https://github.com/microsoft/vscode-remote-release/issues/8169 ?
