### ISSUE TITLE
URLs on Diagnostic codes no longer function (they just jump to the location of the error)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#110744] opened 2020-11-16 17:56 UTC
Given the following code in an extension:

```ts
export function activate(context: vs.ExtensionContext) {
	const diag = vs.languages.createDiagnosticCollection("test");
	vs.workspace.onDidOpenTextDocument((e) => {
		diag.set(e.uri, [
			{
				message: 'A message',
				code: {
					value: 'foo',
					target: vs.Uri.parse('https://www.bing.com/'),
				},
				range: new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)),
				severity: vs.DiagnosticSeverity.Error,
			}
		]);
	});
}
```

Clicking the diagnostic code no longer opens the URL (it appears to just open the file where the error is, not the URL it should open in the browser):

![Nov-16-2020 17-55-16](https://user-images.githubusercontent.com/1078012/99289483-eaf0eb80-2834-11eb-9756-03b02b5921d4.gif)

**Comment by sandy081** [comment] 2020-11-19 18:45
Did you do ctrl+click / cmd+click ?

**Comment by DanTup** [comment] 2020-11-23 12:33
Hmm, Cmd+Click works. Has it always been that way? I was sure I could just click previously.

If this is intended, I think there should be a tooltip or something, as this doesn't seem very disoverable.

**Comment by sandy081** [comment] 2020-11-24 10:34
Yes, its always cmd+click.

Duplicate of https://github.com/microsoft/vscode/issues/89643

**Closed** 2020-11-24 10:34 UTC
Labels: *duplicate, error-list, needs more info
