### ISSUE TITLE
OrganizeImports Action Removes Import

### ISSUE THREAD

**Issue by simonua** [Microsoft/vscode#49718] opened 2018-05-11 19:04 UTC
Issue Type: <b>Bug</b>

The new organizeImports code in 1.23 appears a bit too assertive. For example, when saving this snippet, the action removes the import. 

```
import { ElementFinder } from 'protractor';

export { ElementFinder };
```

My setting:

```
"[typescript]": {
   "editor.codeActionsOnSave": {
      "source.organizeImports": true
   }
}
```

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment] 2018-05-11 19:10
Duplicate of #49193 

Fixed in insiders

**Closed by mjbvz** 2018-05-11 19:10 UTC
Labels: new release
