### ISSUE TITLE
Trust: should a drag operation from a trusted window ask for trust again?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125084] opened 2021-06-01 13:00 UTC
Here I drag a file from a trusted window to a new window and I get asked again. I would probably not expect that to happen given I already trusted the file in the source:

![recording (1)](https://user-images.githubusercontent.com/900690/120327410-0364b700-c2ea-11eb-907c-8fe509e29c36.gif)

**Comment by sbatten** [comment] 2021-06-07 16:03
So the scenario is:
2 empty windows.
Both are trusted and one has untrusted content opened.
Dragging the "untrusted" content into the second trusted window asks if it is okay because we treat it like any open file operation.

I think the best UX is indeed that we do not ask again. We need a way to detect this from the `openEditors` I believe.

**Comment by lszomoru** [comment] 2021-07-21 08:57
Trust state is stored only at the folder level (workspace file is an exception), so when an untrusted file is being opened in a trusted window/workspace, it's not that the file becomes trusted, but the window/workspace is marked as accepting files that are not trusted. I do not believe that this is something that we can detect, unless we decide to add the capability to store trust state at the file level. Closing this issue "by design" for now.

**Closed by lszomoru** 2021-07-21 08:57 UTC
Labels: under-discussion, workspace-trust
