### ISSUE TITLE
Background color not right for themes whose bgcolor is neither black or white

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19391] opened 2017-01-25 19:54 UTC
- VSCode Version: Insiders dated 2017-01-25
- OS Version: Windows

Steps to Reproduce:

1. Change theme to anything which doesnt have a black or white background. Like
- Tomorrow night blue
- Red
- Solarized Dark
- Solarized Light

The foreground colors match between stable and insiders.
But the background color in insiders is only either black or white.

Its black.. or white... feel like breaking into MJ's song here...

**Comment by alexandrudima** [comment] 2017-01-25 20:10
Duplicate of #19344

**Closed by alexandrudima** 2017-01-25 20:10 UTC
Labels: important, themes
