### ISSUE TITLE
Research multiple cursor after find/replace in selection

### ISSUE THREAD

**Issue by ldexterldesign** [Microsoft/vscode#43942] opened 2018-02-18 18:26 UTC
NB https://stackoverflow.com/questions/tagged/vscode - would have posted here but 😬...

<img width="789" alt="screen shot 2018-02-18 at 19 18 49" src="https://user-images.githubusercontent.com/1715809/36355255-ddbc6436-14e0-11e8-9404-810a9f91ed8d.png">

Hi all,

Hope you're well

I make use of this feature regularly, using search find/replace:

⇧⌘L Select all occurrences of current selection

![untitled mov](https://user-images.githubusercontent.com/1715809/36355263-f3f75cf6-14e0-11e8-9595-6b0d604acac2.gif)

I would like to perform the same action combined with "Find in selection" (i.e. I want to select all occurrences in *a specific* selection) but for the life of me I'm unable to achieve this

Can anyone else perform this action, if yes I'd love to hear how?

Hope this is clear and to hear back

Thanks (in advance)

Related:

https://github.com/Microsoft/vscode/issues/9444
https://github.com/Microsoft/vscode/issues/9584
https://github.com/Microsoft/vscode/issues/21792
https://github.com/Microsoft/vscode/issues/26417
https://github.com/Microsoft/vscode/issues/27083

**Comment by egamma** [comment] 2018-02-19 08:02
This is currently not supported but there is a feature request for this feature.

Closing as a duplicate of #21792

**Closed by egamma** 2018-02-19 08:02 UTC
