### ISSUE TITLE
"Change All Occurrences" regression: Match Whole Word / Match Case state is broken

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#24965] opened 2017-04-18 17:51 UTC
- VSCode Version: 1.11.2
- OS Version: Ubuntu

Steps to Reproduce:

1. Use "Change All Occurrences" on any word / symbol
2. Try to set "Match Whole World" and/or "Match Case". Issues:
  a. "Match Whole World",  "Match Case" buttons toggle each other (appear to be exclusive, no way to set both as in previous version of vs code)
  b. Subsequent "Change All Occurrences" do not use the last state - it resets to both "Match Whole World",  "Match Case" unchecked.

**Comment by alexandrudima** [comment] 2017-04-21 07:39
The toggles were not painted correctly.

**Comment by aeschli** [comment] 2017-04-21 09:16
duplicate of #23540

**Closed by aeschli** 2017-04-21 09:16 UTC
