### ISSUE TITLE
Windows Terminal command not working

### ISSUE THREAD

**Issue by herissonnobre** [microsoft/vscode#126759] opened 2021-06-19 21:27 UTC
Issue Type: <b>Bug</b>

When I type "code-insiders.cmd ." on Windows Terminal, VS Code opens VS Code AppData folder instead the terminal current folder.

VS Code version: Code - Insiders 1.58.0-insider (7dea6d7402b55671410a129661cad24b55aed9f4, 2021-06-18T13:58:43.903Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (6.42GB free)|
|Process Argv|. --crash-reporter-id 8d06bf74-32e5-4162-bda2-0066a1675b1a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
split-line|che|1.0.2
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|6.4.0
auto-close-tag|for|0.5.10
code-runner|for|0.11.4
material-icon-theme|PKi|4.7.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

**Comment by yume-chan** [comment] 2021-06-20 12:23
Duplicate of #122060

**Closed** 2021-06-28 14:43 UTC
