### ISSUE TITLE
In the 'Extensions' View, only the two first entries of the 'INSTALLED' category are visible by default, and the separator's position is not remembered

### ISSUE THREAD

**Issue by darkred** [Microsoft/vscode#37443] opened 2017-11-01 20:27 UTC
- VSCode Version: 1.17.2 x64
- OS Version: win10 x64

Steps to Reproduce:

1. When clicking to expand the 'Extensions' View (Ctrl+Shift+X)
then, no matter how many extensions you have, it only show the first 2 of them. *(and immediately below them, are the "RECOMMENDED" category entries)* 
In my case I have 5, as seen in the counter:
![2017-11-01_220526](https://user-images.githubusercontent.com/723651/32295809-05333e42-bf53-11e7-82bf-785e87cc234a.jpg)

2. Even if you drag the the "RECOMMENDED" category separator lower, in order to make all extension entries visible,
then, if you close the View and re-open it, it will have 2 extension entries visible only, again.

My suggestion:

- either either make sure that in the 'INSTALLED' category entries appear as many as possible, i.e. have the separator's position maybe to the 3/4 of the display's height by default
- or just store the position of the separator, when the user moves it.

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment] 2017-11-02 23:44
@sandy081 Do you want to close this as duplicate of #36887?

**Comment by sandy081** [comment] 2017-11-03 07:56
Yah it is.

**Closed by sandy081** 2017-11-03 07:56 UTC
Labels: extensions
