### ISSUE TITLE
Git Bash Terminal input is blocked after edit

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode#193809] opened 2023-09-22 14:01 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Win10 22H2

Steps to Reproduce:

I'm using a Git Bash Terminal (https://gitforwindows.org/ 2.42.0.2 with default install options) inside VSCode and the git setting `git config core.editor 'code --wait'`.
When I run `git add -p` and then enter `e` it correctly opens the patch in the same VSCode window for editing and after closing progresses in the terminal to the next hunk.
Scrolling etc is still possible but it doesn't accept any input anymore.
Ctrl+C etc has no effect. The only way to exit this deadlock is to kill the terminal, but that also leaves the git index untouched.

**Comment by Trass3r** [comment] 2023-09-22 14:05
Just cross-checked, it doesn't happen with the default Command Prompt. It's some issue related to the Git mintty.

**Comment by joyceerhl** [comment] 2023-12-13 21:52
I cannot repro this with Git Bash, does this still occur reliably for you?

**Comment by Trass3r** [comment] 2023-12-14 13:18
Yes it does. The profile config looks default too. It auto-detected the git bash and I can directly open it inside VSCode.

**Comment by ars-con** [comment] 2024-08-21 18:10
I'm also having this exact issue.

VS Code 1.92.1, Git 2.46.0

**Comment by Tyriar** [comment] 2024-12-19 11:40
I also can't reproduce so unfortunately this isn't actionable and closing. Something that could improve this you could try is to move to the new backend on Windows by setting `"terminal.integrated.experimental.windowsUseConptyDll": true` and restarting the terminal. Other than that I'm not sure, this sort of problem is largely out of our hands as we as the terminal just do as we're told by the process running on the other side.

**Closed by Tyriar** 2024-12-19 11:40 UTC
Labels: bug, windows, confirmation-pending

**Comment by Trass3r** [comment] 2024-12-19 14:23
Unfortunately `windowsUseConptyDll` doesn't fix it.
I also upgraded to the newest Git with mintty 3.7.6 but it persists.
I'm still curious what could be different about your setup.

**Comment by Tyriar** [comment] 2024-12-19 14:29
@Trass3r not sure, if it works in Windows Terminal but not VS Code then hopefully it'll get fixed when we get access to conpty v2 (https://github.com/microsoft/vscode/issues/224488).

**Comment by Trass3r** [comment] 2024-12-19 20:45
Ah, it works in a separate Git Bash, but not when opening the git bash in Windows Terminal.
