### ISSUE TITLE
HTML `class` attribute doesn't receive known CSS classes in code completion

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode#79623] opened 2019-08-22 07:46 UTC
- VSCode Version: 1.37.1
- OS Version: Fedora 30

This is initially reported to Eclipse Wild Web Developer as https://github.com/eclipse/wildwebdeveloper/issues/8 . Wild Web Developer uses the language server from VSCode. The same issue happens in VSCode.

Steps to Reproduce:
1. Create a HTML file
```html
<html>
<style>
.myclass { background: green;}
</style></head>
<body>
<p class="">test</p></body>
</html>
```
2. Try getting code completion inside the `class` attribute value, between the quotes
EXPECTED: `.myclass`
GOT: a list of the "words" in the file (background, p, body...), without much smartness.

**Comment by IllusionMH** [comment] 2019-08-22 09:19
Looks like duplicate of #27635 (please up vote that issue if it is)
In the meantime you can try suggestions from https://github.com/microsoft/vscode/issues/27635#issuecomment-429612617

**Closed** 2019-08-22 14:32 UTC
Labels: *duplicate
