### ISSUE TITLE
Workspace filename extension suffix not set automatically

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#82705] opened 2019-10-16 15:44 UTC
Currently, the workspace file extension suffix is not set automatically when creating a vscode workspace.

![workspace_problem](https://user-images.githubusercontent.com/17570430/66935546-739ec600-f03c-11e9-97a2-3ac0b255c9f1.gif)

#### System information
- **VSCode Version:** 1.40.0-1571220350
- **OS Version:** ubuntu 18.04

**Does this issue occur when all extensions are disabled?:** Yes

#### Steps to Reproduce:

1. Open vscode-insiders using `code-insiders --disable-extensions.
2. Create a workspace not manually setting the suffix.
3. Try to open the workspace.

**Comment by bpasero** [comment] 2019-10-17 05:17
I cannot reproduce on Ubuntu 18:

![image](https://user-images.githubusercontent.com/900690/66979528-33782b80-f0ae-11e9-8d94-87432abb32c2.png)

This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Closed by bpasero** 2019-10-17 05:17 UTC

**Comment by rickstaa** [comment] 2019-10-17 06:22
@bpasero Thanks for investigating.
