### ISSUE TITLE
F8 - go to next error - removes the cursor from the editor

### ISSUE THREAD

**Issue by ryanmcnamara** [Microsoft/vscode#23171] opened 2017-03-24 17:33 UTC
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: OSX 10.11.6

This is an FR on the go to next error command. 
Currently the cursor is removed from the code editor when using the go to next error feature.
![mar-24-2017 10-28-52](https://cloud.githubusercontent.com/assets/3452559/24306211/0b1e38b4-107d-11e7-8816-45c9954bf628.gif)

Users are required to click after jumping to the next error before actually being able to fix it. It would be nice if the cursor remained active in the editor when using the shortcut.

**Comment by mjbvz** [comment] 2017-04-03 21:06
@rebornix Can you please take a look at this or loop in the correct person? It's not specific to TypeScript/JavaScript as far as I can tell in my testing

**Comment by jrieken** [comment] 2017-04-04 14:59
dupe of #18366

**Closed by jrieken** 2017-04-04 14:59 UTC
