### ISSUE TITLE
Underscore is 'Space' in terminal

### ISSUE THREAD

**Issue by DannyMexen** [Microsoft/vscode#37888] opened 2017-11-09 06:36 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.13.0-16-lowlatency
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
sublime-keybindings|ms-|3.0.3

---

Steps to Reproduce:

1. Open terminal
2. Key in an underscore character

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-11-09 07:08
Duplicate of #35901

**Comment by DannyMexen** [comment] 2017-11-09 08:30
`"terminal.integrated.fontSize": 13`

This setting fixed it for me.

**Closed** 2017-11-09 08:51 UTC
Labels: integrated-terminal
