### ISSUE TITLE
[scss] syntax support web component special selector (/deep/) in .scss files

### ISSUE THREAD

**Issue by vpithart** [Microsoft/vscode#16411] opened 2016-12-02 22:16 UTC
- VSCode Version: 1.7.2
- OS Version: macOS 10.12.1

The special `/deep/` selector is widely used as a way to style elements inside Angular2 Components. I don't consider this as a dup of #15695 or #7002 as this is a feature request.

This affect productivity and usability of VS code.  The `"scss.validate": false` is not a way. The commit-only-if-no-syntax-errors rule becomes ineffective; The `problems` pane keeps flooded with red lines, which are actually not errors. 

No syntax workaround for `/deep/` is known so far.

Steps to Reproduce: 
1. Create any .scss file
2. Type in a block with the `/deep/` selector
3. Wait a second until syntax check is done
4. The opening slash `/` is red-underlined saying error `} expected`

Example:
```
/deep/ .tooltip-component {
  top: 14.7rem;
}
```

VS Code will mark this as an syntax error, although it is actually not:
![image](https://cloud.githubusercontent.com/assets/20604326/20852692/f571efd0-b89b-11e6-82aa-d6e4c0ca4ec1.png)

**Comment by aeschli** [comment] 2016-12-03 07:22
It is a duplicate of #7002, which is a feature request as well

**Closed by aeschli** 2016-12-03 07:22 UTC
Labels: languages basic
