### ISSUE TITLE
file`s content changed occasionally

### ISSUE THREAD

**Issue by xunonxyz** [Microsoft/vscode#22707] opened 2017-03-16 01:15 UTC
- VSCode Version:1.10.2
- OS Version: win10

Steps to Reproduce:

1.when i save file, another file`s content changed occasionally

**Comment by MikeVelazcoMtz** [comment] 2017-03-16 01:20
do you use git or how did you get this error?

I think that this is not clear enough.

**Comment by weinand** [comment] 2017-03-16 10:40
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by weinand** [comment] 2017-03-19 18:08
no reply -> closing

**Closed by weinand** 2017-03-19 18:08 UTC
Labels: needs more info
