### ISSUE TITLE
Editor tabs of freshly created files labeled as untracked after commit

### ISSUE THREAD

**Issue by moniuch** [microsoft/vscode#142243] opened 2022-02-05 00:01 UTC
Does this issue occur when all extensions are disabled?: IDK 

- VS Code Version: 1.64.0
- OS Version: macOS Monterey

Steps to Reproduce:

1. Add a new file (add some code to it).
2. Without closing it, stage the change and make a git commit that includes that file
3. After commit has been made, the tab continues to display "untracked" - giving a bit of a horrific impression that the file was skipped during the commit. The 'untracked' word of course disappears when you reopen the file.

![image 2022-02-05 00-54-37](https://user-images.githubusercontent.com/681956/152618703-5bc5705b-a5ad-46b5-b1e8-f88ddb43f674.png)

**Comment by lszomoru** [comment] 2023-12-08 14:02
@moniuch, apologies for not getting back to you on this until now. I am unable to reproduce this issue with the latest VS Code release. I will go ahead and optimistically close this issue but in case you are still able to reproduce please don't hesitate to reopen the issue. Thanks!

**Closed by lszomoru** 2023-12-08 14:02 UTC
Labels: bug, git
