### ISSUE TITLE
Explorer: reset filter on enter

### ISSUE THREAD

**Issue by ndan** [microsoft/vscode#74942] opened 2019-06-06 07:30 UTC
There is no way to reset filter by pressing enter because it's hardcoded to escape.

I'm using a filter/search in explorer for quick navigation, so I don't need to keep filter after I opened the file. I always have to press escape every time I come back to explorer.

It is also useful when you want to quickly navigate to a file in a certain folder, so you can type folder name, press enter to expand, then press down or make a new search. 

Similar issue https://github.com/microsoft/vscode/issues/68880

ps. RubyMine, Neotree for emacs and Nerdtree for vim work in that way out of the box

**Comment by isidorn** [comment] 2019-06-06 08:00
Well your pain would be fixed by #68880 as it seems to me. Since when you open a file, you lose focus and the filter widget would close.
Making the clear filter keybinding contributable would not solve your issue, since I think if we change it to be ENTER, then ENTER would not open the file, it would clear the filter, and only the second ENTER would open the file which would be bad.

So I suggest to close as duplicate of #68880 but leaving to @joaomoreno to decide

**Closed** 2019-06-06 11:41 UTC

**Comment by ndan** [comment] 2019-06-06 12:13
> Making the clear filter keybinding contributable would not solve your issue, since I think if we change it to be ENTER, then ENTER would not open the file, it would clear the filter, and only the second ENTER would open the file which would be bad.

At least I will be able to use [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)

It would be cool to fix https://github.com/microsoft/vscode/issues/68880, but it won't help with this
> It is also useful when you want to quickly navigate to a file in a certain folder, so you can type folder name, press enter to expand, then press down or make a new search.

Tnx for the response
