### ISSUE TITLE
VSCode auto completion not working as before

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#24949] opened 2017-04-18 12:26 UTC
- VSCode Version: 1.11.2
- OS Version: macos

Steps to Reproduce:

1. My REST Client extension previously will have auto completion for header value, but in latest version when I checked this, it doesn't work as expected, that means no auto completion at all
![image](https://cloud.githubusercontent.com/assets/2796177/25130477/da01f084-2474-11e7-8697-1e525265a762.png)

2. However, when I remove the space after the colon, I can get the auto completion.
![image](https://cloud.githubusercontent.com/assets/2796177/25130596/4f9a8f86-2475-11e7-8936-97c268affb0f.png)

**Comment by mjbvz** [comment] 2017-04-18 17:30
Can you please provide a small example extension that demonstrates this so that we can investigate

**Comment by Huachao** [comment] 2017-04-19 08:55
@mjbvz I found one interesting thing is that, since I have a line match in my language syntax file, the regex of the line is `^([\w\-]+)\s*\:\s*(.*?)\s*$` which is used to match the http request header line. If I don't match the whole line, like remove the `^` or `$` in regex expression, the auto completion will become available in the first screenshot.

**Comment by mjbvz** [comment] 2017-05-10 05:26
Closing since there's not enough info to say that VS Code is the root cause of this issue. @Huachao Please put together a small example extension that demonstrates this issue and we can take a look

**Closed by mjbvz** 2017-05-10 05:26 UTC
Labels: extensions, needs more info
