### ISSUE TITLE
Error when starting C++ program

### ISSUE THREAD

**Issue by Sublihim** [Microsoft/vscode#65047] opened 2018-12-14 03:50 UTC
Issue Type: <b>Bug</b>

I write a simple "Hello World" program in C ++.
Run for debugging.
In the debug console, the message: "Stopping due to fatal error: NullReferenceException: Object reference not set."
The program is not debugged, but VSCode shows that it is running.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.19.6-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.68GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.0.0
vscode-eslint|dba|1.7.2
tslint|eg2|1.0.41
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-language-pack-ru|MS-|1.30.2
cpptools|ms-|0.20.1
vscodeintellicode|Vis|1.1.1

</details>

**Comment by huanhexiao** [comment] 2018-12-14 08:38
Hey bro, do u solve this problem?

**Comment by Sublihim** [comment] 2018-12-14 09:21
> Hey bro, do u solve this problem?
Hey. No, I can not solve this problem for the second day. On the previous version it worked. After updating to 1.30 does not work

**Comment by huanhexiao** [comment] 2018-12-14 10:46
damn it...
I also encounter this, without any idea about it...

**Comment by Sublihim** [comment] 2018-12-14 11:42
> damn it...
> I also encounter this, without any idea about it...

Do you also use VSCode on linux? It appeared after the update?

**Comment by weinand** [comment] 2018-12-14 13:54
duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2922

**Closed by weinand** 2018-12-14 13:54 UTC
Labels: new release

**Comment by huanhexiao** [comment] 2018-12-15 07:54
a solution!
 use "externalConsole": false in launch.json

**Comment by 0xDEAD** [comment] 2018-12-17 08:31
Can confirm, externalConsole=false solves the problem for me
