### ISSUE TITLE
Inconsistent property syntax coloring in JS

### ISSUE THREAD

**Issue by Lucky-Loek** [Microsoft/vscode#57260] opened 2018-08-27 11:49 UTC
Issue Type: <b>Bug</b>

When using the `printf`-like features of `console.log`, the syntax coloring of properties is off. See below example. It happens in the built-in color schemes that color properties, like: Kimbie, Red, Solarized, Monokai Dimmed.

Also had this with Insider's and without extensions. See below screenshots for examples. Weird coloring happens on line 19 (or 20 and 21, depending on how it should be).

![afbeelding](https://user-images.githubusercontent.com/9716643/44658130-e778ac00-a9ff-11e8-9ae0-ae6dbceda3f7.png)

![afbeelding](https://user-images.githubusercontent.com/9716643/44658151-fe1f0300-a9ff-11e8-9ccf-310394ee0804.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|7.87GB (2.08GB free)|
|Process Argv|C:\Users\lind0096\AppData\Local\Programs\Microsoft VS Code\Code.exe --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by Lucky-Loek** [comment] 2018-08-28 09:16
Also happens in classes, I just found out, see line number 9, 10, 11. 

![afbeelding](https://user-images.githubusercontent.com/9716643/44713509-90341380-aab3-11e8-8a7d-8e4f4a49c9a0.png)

**Comment by SzHeJason** [comment] 2018-08-28 11:09
+1
![image](https://user-images.githubusercontent.com/20609396/44719093-d8275a80-aaf4-11e8-8e4e-28641d7dca1c.png)
![image](https://user-images.githubusercontent.com/20609396/44719102-de1d3b80-aaf4-11e8-9500-bdbc7ade0af7.png)

**Comment by mjbvz** [comment] 2018-09-04 21:00
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/657

This behavior has been marked as wontfix upstream because it matches what other js/ts grammars do

**Closed by mjbvz** 2018-09-04 21:00 UTC

**Comment by Lucky-Loek** [comment] 2018-09-05 06:52
Aah, that explains. I'll just use better naming and deal with it then. Thanks!
