### ISSUE TITLE
Error launching vscode when a # exists in the path

### ISSUE THREAD

**Issue by artbycrunk** [Microsoft/vscode#56691] opened 2018-08-17 14:46 UTC
- VSCode Version: 1.26.1
- OS Version: Ubuntu 16.04 / Centos 7.3

Steps to Reproduce:

1. Change the VScode folder to contain a # like VSCode-linux-x64#1.26
2. Run code from VSCode-linux-x64#1.26/bin/code

```
osboxes@osboxes:~/editors/VSCode-linux-x64#1.26/bin$ ./code --disable-extensions
The factory method of "vs/platform/node/package" has thrown an exception
{ Error: Cannot find module '/home/osboxes/editors/package.json'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:770)
    at Object.<anonymous> (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/code/node/cli.js:111:643)
    at Function.t._safeInvokeFunction (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:248)
    at Function.t._invokeFactory (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:495)
    at t.complete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:732)
    at s._onModuleComplete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:25)
    at s._onModuleComplete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:269)
    at s._resolve (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:29:599)
    at s.defineModule (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:23:862)
    at s._onLoad (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:25:611)
    at Object.callback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:890)
    at e.triggerCallback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:810)
    at /home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:616
    at t.load (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:16:146)
    at e.load (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:587)
    at i (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:808)
    at Object.errorback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:929)
    at e.triggerErrorback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:952)
    at /home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:657
    at ReadFileContext.callback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:16:267)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module '/home/osboxes/editors/package.json'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:770)
    at Object.<anonymous> (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/code/node/cli.js:111:643)
    at Function.t._safeInvokeFunction (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:248)
    at Function.t._invokeFactory (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:495)
    at t.complete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:732)
    at s._onModuleComplete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:25)
    at s._onModuleComplete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:269)
    at s._resolve (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:29:599)
    at s.defineModule (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:23:862)
    at s._onLoad (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:25:611)
    at Object.callback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:890)
    at e.triggerCallback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:810)
    at /home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:616
    at t.load (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:16:146)
    at e.load (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:587)
    at i (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:808)
    at Object.errorback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:929)
    at e.triggerErrorback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:952)
    at /home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:657
    at ReadFileContext.callback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:16:267)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
The factory method of "vs/platform/node/product" has thrown an exception
{ Error: Cannot find module '/home/osboxes/editors/product.json'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:770)
    at Object.<anonymous> (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/code/node/cli.js:111:855)
    at Function.t._safeInvokeFunction (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:248)
    at Function.t._invokeFactory (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:495)
    at t.complete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:732)
    at s._onModuleComplete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:25)
    at s._onModuleComplete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:269)
    at s._resolve (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:29:599)
    at s.defineModule (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:23:862)
    at s._onLoad (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:25:611)
    at Object.callback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:890)
    at e.triggerCallback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:810)
    at /home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:616
    at t.load (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:16:146)
    at e.load (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:587)
    at i (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:808)
    at Object.errorback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:929)
    at e.triggerErrorback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:952)
    at /home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:657
    at ReadFileContext.callback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:16:267)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module '/home/osboxes/editors/product.json'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:770)
    at Object.<anonymous> (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/code/node/cli.js:111:855)
    at Function.t._safeInvokeFunction (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:248)
    at Function.t._invokeFactory (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:495)
    at t.complete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:19:732)
    at s._onModuleComplete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:25)
    at s._onModuleComplete (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:30:269)
    at s._resolve (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:29:599)
    at s.defineModule (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:23:862)
    at s._onLoad (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:25:611)
    at Object.callback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:890)
    at e.triggerCallback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:810)
    at /home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:616
    at t.load (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:16:146)
    at e.load (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:587)
    at i (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:808)
    at Object.errorback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:27:929)
    at e.triggerErrorback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:952)
    at /home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:13:657
    at ReadFileContext.callback (/home/osboxes/editors/VSCode-linux-x64#1.26/resources/app/out/vs/loader.js:16:267)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```
Any ideas what could be causing this, and where in the source one could start looking for answers?

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by artbycrunk** [comment] 2018-08-18 15:55
@jrieken 
its seems like its because the packageJsonPath lookup is using URI.parse which is stripping off the fragment in the path.. should this lookup be using URI.file instead?

**Comment by jrieken** [comment] 2018-08-20 07:15
This might actually be an issue with `require.toUrl` or an issue with how we setup the loader/baseurl.

**Comment by octref** [comment] 2018-08-30 21:30
@jrieken The new one still don't work for me:

- Download Insiders / Stable into a folder like `foo#bar`
- Observer that there is no way to open them

![image](https://user-images.githubusercontent.com/4033249/44880427-44bf6800-ac61-11e8-8042-444207d98b76.png)

**Comment by jrieken** [comment] 2018-08-31 06:58
Works for me with those steps. @octref Are you sure that you are testing this with the right version and that you don't have VS Code Insiders already running?

![aug-31-2018 08-57-24](https://user-images.githubusercontent.com/1794099/44897430-ef846480-acfb-11e8-9dba-67ff72d53661.gif)

**Comment by bpasero** [comment] 2018-08-31 08:34
@jrieken @octref I cannot reproduce with todays insider release so I am moving this to September.

**Comment by artbycrunk** [comment] 2018-08-31 09:06
Just tested the latest insider release, works for me.

**Comment by jrieken** [comment] 2018-08-31 09:10
Ok - enough evidence (and trust in my changes). Closing.

**Closed by jrieken** 2018-08-31 09:10 UTC
Labels: bug, uri

**Comment by octref** [comment] 2018-08-31 16:16
Working for me now. I probably had Insider already running yesterday.
