### ISSUE TITLE
Copy/paste lines of code from vs without getting copied format

### ISSUE THREAD

**Issue by amitagrawal11** [Microsoft/vscode#41955] opened 2018-01-22 09:55 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.4
gitlens|eam|7.5.5
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
json-tools|eri|1.0.2
vscode-console-wrapper|fab|0.4.0
tortoise-svn|fan|0.1.1
Angular1|joh|0.2.0
Angular2|joh|2.11.2
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.0.0
vscode-docker|Pet|0.0.23
vscode-template-literal-editor|pli|0.8.4
vscode-icons|rob|7.19.0
autoimport|ste|1.5.3
quokka-vscode|Wal|1.0.93
wallaby-vscode|Wal|1.0.75
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Open any file (.txt, .js, .ts, .css) in vscode
2. Copy a piece of code 
3. paste it on Mailbox like as outlook, mac os mail, or any editor or paste it on any messengers like as skype, lync, skype for business
4. you will find that copied lines of code will also copies format.

![image](https://user-images.githubusercontent.com/5697986/35214883-a86d4858-ff88-11e7-941a-86d85028a9d6.png)

Reproduces without extensions: Yes/No

**Comment by usernamehw** [comment] 2018-01-22 11:33
Duplicate of https://github.com/Microsoft/vscode/issues/36960

**Closed** 2018-01-22 11:39 UTC
Labels: *duplicate, editor, editor-clipboard
