### ISSUE TITLE
 Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#3227] opened 2016-02-22 08:54 UTC
Issue Id: <b>76000c98-ba3d-f84d-60f4-a18061d87e94</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  df352367df2efcfa9d602d471e4e2f42140a0f05<br />-  45d69357c9eb068dd8e624f5b0fe461cd2078d88<br />-  783ecf841a2b21edca6d86853670cae89b4c244f<br />-  7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />*Stack* <br />RangeError: Maximum call stack size exceeded<br />    at y.scan (out/vs/languages/sass/common/sassWorker.js:4:902) <no sourcemaps><br />    at y.scan (out/vs/languages/sass/common/sassWorker.js:4:1041) <no sourcemaps><br />    at y.e.scan (out/vs/languages/css/common/cssWorker.js:4:27925) <no sourcemaps><br />    at y.scan (out/vs/languages/sass/common/sassWorker.js:4:1839) <no sourcemaps><br />    at y.scan (out/vs/languages/sass/common/sassWorker.js:4:1041) <no sourcemaps><br />    at y.e.scan (out/vs/languages/css/common/cssWorker.js:4:27925) <no sourcemaps><br />    at y.scan (out/vs/languages/sass/common/sassWorker.js:4:1839) <no sourcemaps><br />    at y.scan (out/vs/languages/sass/common/sassWorker.js:4:1041) <no sourcemaps><br />    at y.e.scan (out/vs/languages/css/common/cssWorker.js:4:27925) <no sourcemaps><br />    at y.scan (out/vs/languages/sass/common/sassWorker.js:4:1839) <no sourcemaps><br />

**Comment by aeschli** [comment] 2016-02-22 15:41
duplicate of #3048

**Closed by aeschli** 2016-02-22 15:41 UTC
Labels: error-telemetry
