### ISSUE TITLE
Jupyter notebook markdown inline and block code is now red in Dark+ V2 (Experimental) theme

### ISSUE THREAD

**Issue by ddbrierton** [microsoft/vscode#175808] opened 2023-03-01 21:56 UTC
Does this issue occur when all extensions are disabled?: No — an extension is required to see the bug

- VS Code Version: 1.76.0
- OS Version: macOS 13.2.1

Steps to Reproduce:

1. Open new Jupyter notebook.
2. Write some markdown including code in between backticks.

Code is displayed in a sort of deep red colour that looks like a fatal error message. This does not happen in an ordinary markdown file. This started happening immediately after the update to 1.76.0 today, so my first thought is that it must be a new version of the theme (also it doesn’t happen in V1 of Dark+), however it is possible that this is something to do with one of the Python extensions. Please advise if I have misfiled it.

Screenshots:

<img width="861" alt="Screenshot 2023-03-01 at 22 52 04" src="https://user-images.githubusercontent.com/7255543/222274779-17d945f4-3cb0-47b6-985e-3344bc4ba774.png">

<img width="865" alt="Screenshot 2023-03-01 at 22 52 25" src="https://user-images.githubusercontent.com/7255543/222274818-2354261a-5360-4270-8411-a0e31944597d.png">

**Comment by mjbvz** [comment] 2023-03-01 22:40
@daviddossett This is coming from the `textPreformat-foreground` theme color

**Comment by ddbrierton** [comment] 2023-03-08 23:53
Probably related to, or duplicate of, #175596

**Comment by joyceerhl** [comment] 2023-03-09 19:34
Duplicate of https://github.com/microsoft/vscode/issues/175596

**Closed by joyceerhl** 2023-03-09 19:34 UTC
