### ISSUE TITLE
JavaScript Language Service Bug on async shorthand with for-of loop in lambda object

### ISSUE THREAD

**Issue by falco467** [Microsoft/vscode#36153] opened 2017-10-12 17:24 UTC
- VSCode Version: 1.17.1 (Does not happen in 1.16.1 - regression?)
- OS Version: Windows 10

Steps to Reproduce:
Put the following valid code in a JavaScript document:
```
let validLambda = () => ({
    async bla() {
        for ( let i of [] ) {
            console.log(i)
        }
    }
})
```

The JS Language Service shows 10 Errors, spread over the whole code snippet. The same code didn't show any errors in VS-Code 1.16.1 - and is valid ES6 syntax.

The errors disappear if one removes just **one** of the following:
1. The surrounding Lambda Expression (Just write `let a = {...}` )
2. The async modifier on the function shorthand
3. The for loop (Just replace it with a regular `for( i in [] )` or `for( let i=0;;)` )

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-10-12 17:42
Thanks! I confirmed that this seems to be an issue and have opened https://github.com/Microsoft/TypeScript/issues/19134 to track this upstream

Closing as upstream

**Closed by mjbvz** 2017-10-12 17:42 UTC
Labels: javascript, new release, upstream
