### ISSUE TITLE
Can't make word pattern works with double ticks (for renaming)

### ISSUE THREAD

**Issue by MangelMaxime** [Microsoft/vscode#32762] opened 2017-08-18 08:00 UTC
In F#, we are allowed to name a variable like ` ``test`` ` (the double ticks are not an error)

In order to match this kind of variable and allowing renaming them, I created this regex:

```
(``((\w*\s?)\s?)*``)|((\w*')(\w'?)*)|(-?\d*\.\d\w*)|([^\`\~\!\@\$\^\&\*\(\)\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\s]+)
```

As you can see [here](https://regex101.com/r/laVr9h/1) it's matching the variables names as expected. However, when trying to rename it by pressing F2 in VSCode it's only capture `test`

-----------

- VSCode Version: 1.5.1
- OS Version: Windows Pro x64, Linux Mint 18.2

-----------

Steps to Reproduce:

1. Set the regex into wordPattern for a plugin.
2. Write this line: `let ``test`` = "" `
3. Try to rename ` ``test`` ` into `newName`

Same test for: ` ``test multiple words`` `

Here is a gif to demonstrate the issue:

![vscode_double_tick](https://user-images.githubusercontent.com/4760796/29449681-f745cf58-83fb-11e7-935a-fd93b3a95379.gif)

**Comment by alexandrudima** [comment] 2017-10-26 08:08
I believe rename (F2) uses the word definition provided by the language. I'm not sure if this is a problem with our rename code or with the word definition provided by the language.

**Comment by jrieken** [comment] 2017-10-26 08:15
duplicate of #7340

**Closed by jrieken** 2017-10-26 08:15 UTC
Labels: editor

**Comment by MangelMaxime** [comment] 2017-10-26 08:40
@alexandrudima You have the word pattern definition provided in my issue. And when I test it using a regex tool it's have the right behavior.

**Comment by MangelMaxime** [comment] 2017-10-26 08:43
@jrieken Sorry for the duplicate issue but not sure to see how it's related to the #7340 issues.

I suppose this is VSCode, who determine the string part being selected for rename. And the renameProvider part occured after this.
