### ISSUE TITLE
Support some way of launching without debugging like Visual Studio

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#3209] opened 2016-02-21 11:19 UTC
In Visual Studio, you can press Ctrl+F5 to launch the application without a debugger attached, which i befinicial for performance reasons. For VS Code this would be very helpful, because you don't always want to actually debug a file or actually cannot because there is no debug adapter extension out there yet. Currently, you have to define a "launch" task, which cannot get a keyboard shortcut. Having "Launch without debugging" would be much more semantically correct.

 - Introduce a new action in command palette "Launch without debuggin" with keyboard shortcut Ctrl+F5
 - If the currently selected configuration has `type` set, send the debug adapter a `launchRequest` with the additional argument `debug: false`
 - Make the debug setting `type` optional. If a configuration does not have a `type`, it can only be launched without debugging:
   - If `runtimeExecutable` is set, spawn the runtime executable (java, bash, ...) with the `runtimeArguments`, `program` and `args`.  
     Otherwise spawn `program` with `args` directly (like a .exe or .bat)
   - `program` should be allowed to drop the file extension (java needs this for example)
   - Put stdout on the debug console and send input on the debug console to stdin
   - If `externalConsole` is true, run the script in an external console
   - Support `preLaunchTask`

Examples:
```json
{
  "name": "Run currently open script",
  "runtimeExecutable": "bash",
  "program": "${file}"
}
```
```json
{
  "name": "Launch",
  "runtimeExecutable": "java",
  "program": "${workspaceRoot}/MyClass",
  "preLaunchTask": "compile"
}
```

**Comment by weinand** [comment] 2016-02-22 17:18
duplicate of #2780

**Closed** 2016-02-22 17:18 UTC
Labels: debug, feature-request
