### ISSUE TITLE
NPM Scripts not displayed in Explorer

### ISSUE THREAD

**Issue by davegardner** [microsoft/vscode#120764] opened 2021-04-07 21:45 UTC
Issue Type: <b>Bug</b>

Prerequisites:
- Windows 10, 
- Node 12.18.3, 
- VS Code Insiders 12.54 

To reproduce:
1. Create a new folder: ```mkdir NoScript```
2. Set the current folder: ```cd NoScript```
2. Create a new nodejs project ```npm init -y```
3. Open VS Code ```code ./```

### Expected
Window at bottom left of Explorer to show NPM Scripts with one entry for test.

### Result
No NPM Scripts window is displayed.

VS Code version: Code - Insiders 1.56.0-insider (550035808407c15252e581e8abe1b820b9d311ee, 2021-04-02T05:15:44.248Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 4415U @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.69GB free)|
|Process Argv|--crash-reporter-id 7613ea6d-8e47-4d61-8658-42121cadf87a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Pentium(R) CPU 4415U @ 2.30GHz (4 x 2300)|
|Memory (System)|7.87GB (1.69GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.54.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwsldoc:30278403
vsget980:30283264
vsc_aacf:30263846
vspre833:30267464
pythonptprofiler:30281269
vsdfh931:30280409
vscnewfilebuttoncf:30280635
vshan820:30276952
pythondataviewer:30285072

```

</details>

**Comment by IllusionMH** [comment] 2021-04-07 22:16
I believe this is duplicate of #120279

**Closed** 2021-04-07 22:36 UTC
Labels: *duplicate
