### ISSUE TITLE
Insiders regression: "(" and ")" in Uri's are not escaped (leading to extension failures)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#83490] opened 2019-10-29 01:34 UTC
- VSCode Version: 1.40.0-insiders
- OS Version: Windows (probably others)

Steps to Reproduce:

1. Use some LSP extension like the C/C++ one to open a document.

Bug: The Uri our extension receives doesn't have the "(" and ")" escaped with the %hex encoding, which causes error squiggles in our extension to fail to appear (https://github.com/microsoft/vscode-cpptools/issues/4505 ) because file comparisons fail because our internal "URI from path" code is encoding the "(" and ")". Let us know if we're expected to ship a fix to account for this change in Uri encoding.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment] 2019-10-29 07:46
> because file comparisons fail because our internal "URI from path" code is encoding the "(" and ")". Let us know if we're expected to ship a fix to account for this change in Uri encoding.

I would like to know more. What is your internal "URI from path" thing? Isn't that `vscode.Uri.file` and isn't that the `vscode-uri`-npm module? We did make changes to our uri-implementation to be more aligned with the whatwg-URL about what characters to encode and what not. I am aware that's a risky change and therefore I need more information to make a judgement, esp wrt the URI implementation you are using

**Comment by sean-mcmanus** [comment] 2019-10-29 19:12
The "URI from path" code is written in C++ in our LSP process. We get the URI via LSP in many cases, so we can't call the same vscode.Uri.file APIs. We have some ideas on how we could fix the issue on our end, such as storing/comparing "paths" instead of URIs or dynamically doing different URI encoding based on what VS Code does.

**Comment by jrieken** [comment] 2019-10-30 07:47
> The "URI from path" code is written in C++ in our LSP process.

So, is that a custom implementation or a library implementation? I am asking because all those changes were made to align with library implementations and to be compatible with them - often we over encoded things that are decoded in other implementation and therefore are loosing data along the way

**Comment by jrieken** [comment] 2019-10-30 09:34
/duplicate of https://github.com/microsoft/vscode/issues/83610

**Comment by jrieken** [comment] 2019-10-30 09:34
closing this as dupe, we will revert our uri changes as extension programmed against our behaviour.

**Closed** 2019-10-30 09:34 UTC
Labels: *duplicate, needs more info, uri

**Comment by jrieken** [comment] 2019-10-30 09:58
fixed via 58479e80ab899402283b522da173c34867d7c78f

**Comment by sean-mcmanus** [comment] 2019-11-01 19:11
Thanks.
