### ISSUE TITLE
Running Code should open a new instance, not activate a currently opened one

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#48] opened 2015-11-18 16:10 UTC
Ubuntu 12.04, vscode 0.10.1

Currently when you run `Code` if there is an instances already running (or shift clicking the app icon in Windows/Ubuntu) it will activate the currently opened window. This should open a new instance, the same goes for opening a new instance of `Code` with a folder as an argument when an instance is already open.

It's a very common use case for many developers to have multiple editors with the same folder open.

**Repro:**
1. `Code` (open instance of vscode)
2. `Code`

**Expected:**
A new instance of vscode is opened

**Actual:**
The current instance of vscode is activated

**Comment by montogeek** [comment] 2015-11-18 16:10
+1

**Comment by ntotten** [comment] 2015-11-20 14:40
Agreed, this is one of the main annoyances of code. I don't know any other editor that behaves the way code does. The default should be new window with an optional flag to reuse if you really want that behavior.

**Comment by bpasero** [comment] 2015-11-20 20:03
You can use the command line option `-n` to force open a new instance.

**Comment by ygorlazaro** [comment] 2015-11-20 21:17
This is good. But there's no way to make it a default option?

**Comment by bpasero** [comment] 2015-11-20 21:18
Fair, I can see about an option.

**Comment by dmccaffery** [comment] 2015-11-22 05:05
``` bash
# linux (assuming you symlinked already)
code () { /usr/local/bin/code -n $* }

# osx
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* }
```

**Comment by bpasero** [comment] 2015-11-23 08:43
Does someone have an idea how to name this setting? The intent is to control if launching "code" without path arguments will focus the last active instance or open a new, empty instance.

**Comment by montogeek** [comment] 2015-11-23 13:18
`new_instance`?

**Comment by bpasero** [comment] 2015-11-23 13:59
Our settings typically follow this pattern `window.reopenFolders` for example.

**Comment by Tyriar** [comment] 2015-11-23 15:33
`window.launchNewInstance`, `window.alwaysLaunchNewInstance`?

**Comment by bpasero** [comment] 2015-11-23 15:39
Well thats good but does not really capture the case that we only do so if you are passing in no arguments. I thought about `window.noArgsLaunchNewInstance` but its ugly.

**Comment by Tyriar** [comment] 2015-11-23 15:49
Do/can the settings have descriptions to go along with them? Adding `noArgs` to the start kind of feels like adding `byDefault`, which is implied.

**Comment by bpasero** [comment] 2015-11-23 15:51
Oh yeah:

![image](https://cloud.githubusercontent.com/assets/900690/11341364/7ab7dde2-9202-11e5-83b4-d2247a6dce0b.png)

**Comment by ericwj** [comment] 2016-01-04 16:32
When I select *File* | *Preferences* | *User Settings*, type `"window.openFilesInNewWindow": true` and press `Ctrl+Space` it'll show a tooltip "`true`: Default value".

However, on Windows 10.0.10586.36 in Code 0.10.6, typing `code .` in a folder or right-clicking in *File Explorer* on a file or folder and selecting *Open with Code* will do nothing whatsoever. It won't even reactivate (focus) the current instance. I'm not sure when this behavior was introduced. Previously code would happily open multiple instances without any configuration.

The setting `"window.openInNewWindow"` also doesn't seem to exist, but would be a better name for the setting. I don't want to only open files in a new window. `code .` should open the current folder regardless of how many instances of code are already open or whether they have folders or individual files open.

**Comment by bpasero** [comment] 2016-01-04 17:12
@ericwj  The setting to force reopen files in new windows or not is called `window.openFilesInNewWindow` and was renamed because it only impacts files and not folders.

From the command line you can use `-r` to force reuse the last instance or `-n` to force opening a new instance for whatever files or folders you pass in.

Could it be that in your case a window is already opened on a specific folder you try to open and it just is not focussed? There is another issue on Windows 10 where Code is not able to order a window from the background to the foreground, which might be related.

To make sure things work properly:
 * close all code instances
 * cd into your home directory and run `code .`
 * cd into a folder inside the home directory and run `code .`

You should find 2 instances of code running.

**Comment by ericwj** [comment] 2016-01-04 17:23
Assume I'm in `C:\Program Files (x86)\Microsoft VS Code` so `.` is that folder for this comment.

Sure I tried with a folder that wasn't open already. I updated my comment while investigating, please reread. I'm convinced there is an issue with the opening of code through the command prompt. It points to .\bin\code.cmd which starts .\code.exe with .\bin\code.js as the first argument, which starts .\code.exe. That's too many steps to just do .\code.exe %* which is what the registry sais should happen. If I edit code.cmd to do just that, all is fine.

So I suspect perhaps code.cmd and/or code.js were left from a previous install as is the path with points to .\bin not . and their contents break all command line switches, at least --help and -n don't do anything whatsoever as I confirmed.

**Comment by ericwj** [comment] 2016-01-04 17:27
Although running code.exe --help doesn't do anything still apart from showing a new prompt with a newline after it.

code.exe --n . works and correctly focuses the same window and brings it to the front when done twice.

**Comment by bpasero** [comment] 2016-01-04 17:56
@ericwj not sure why you refer to "--help", we do not support such an argument!

If you suspect a bad install, maybe try reinstalling from scratch after uninstall. I do not think we changed the code.cmd/code.js recently though.

**Comment by bpasero** [comment] 2016-01-04 17:58
Btw be careful with "code.exe" within the directory of installation, that one might be the code.exe from the installation which is not the same code.cmd we put on the path. hence my comment about PLEASE try it from the home dir.

**Comment by ericwj** [comment] 2016-01-08 15:25
I was using code from the command line in a directory that is a git repository somewhere deep in my user profile, if that's good enough. I started searching for the configuration option mentioned above after experiencing problems launching VS Code.

Is the content of code.cmd and code.js that I reported correct for the latest (few) version(s) of VS Code?

Note that the registry key I mentioned refers to code.exe within the directory of installation, Code.cmd uses `%~dp0..\\code.exe` and code.js uses `resolve(__dirname, '..', 'Code.exe')`. If that code.exe isn't the correct one, that's a problem in VS Code. 

I might reinstall, but most people don't. They install the new version through the prompts provided by code.exe when you release a new version. That's what I did this time, too. So if that produces this problem and clean install fixes it, it's a problem in VS Code.

**Comment by Spown** [comment] 2016-05-17 13:07
Middle clicking on the icon in the taskbar in Windows10 should normally open a new window also, which is not the case for VSC - it focuses the current running instance. I won't open a new issue, since i'm pretty sure midlle click on the icon is a shortcut for the above described behavior anyway.

**Comment by Tyriar** [comment] 2016-05-17 15:25
@Spown nice find, an alternative to that is <kbd>shift</kbd>+<kbd>click</kbd>.

**Comment by Tyriar** [comment] 2016-05-17 17:55
Running `code -n .` twice definitely doesn't open two instances for me, I remember having issues with this in the past as well (did it ever work or am I misunderstanding its purpose?). If `-n` consistently opened a new window it would solve my issue as I could use alias to force it:

```bash
alias code='code -n'
```

The middle click thing on Windows would be nice to have though.

**Comment by hashhar** [comment] 2016-05-30 15:47
I was looking into the Backlog issues and this came up. The way I see it, Code only fails to open a new instance if the currently running instance and the new instance both have same target folder.

- It works for opening two copies of a single file.
- Doesn't work for two empty instances.
- Doesn't work for two directories.

The above behaviour is independent of the flags. No flags make any difference in this behaviour.

**Comment by Tyriar** [comment] 2016-05-30 19:57
@hashhar yeah, I would only expect `-n` to do something different when opening a folder that is already open.

**Comment by hashhar** [comment] 2016-06-01 16:41
@Tyriar I meant that, even using `-n` doesn't work.

Try this:

```
code .
code -n .
```

Expected results are a new instance opening. But it simply transfers focus to the running instance.

**Comment by Tyriar** [comment] 2016-06-01 18:05
@hashhar I was agreeing with you :smiley: I think that is the only thing `-n` is supposed to do but it doesn't seem to work.

**Comment by hashhar** [comment] 2016-06-01 19:10
This seems a little trivial to fix. Could you point me to the file that handles the command line arguments?

**Comment by Tyriar** [comment] 2016-06-01 19:32
@hashhar it may be harder than you think due to the process management/sharing involved. Here are some relevant files:

- CLI: https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/cli.ts
- Electron main: https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/main.ts

**Comment by chuckries** [comment] 2016-06-04 00:39
+1 for middle click in windows should open new instance.

**Comment by Tyriar** [comment] 2016-07-22 09:05
Another case that changing this would fix: <kbd>win</kbd>+<kbd>shift</kbd>+(launcher number) on Ubuntu and Windows.

**Comment by bpasero** [comment] 2016-08-15 07:47
For people that expect "`code -n`" to open the same folder in 2 windows, we DO NOT support opening the same folder in multiple windows this yet.

**Comment by Tyriar** [comment] 2016-08-15 16:43
@bpasero since code attempts to open the previously opened folder when launching this way it never works. Things that would resolve this issue:

- Lifting constraint that the same folder cannot be opened in multiple windows of vscode 
- If vscode is currently running with a folder open, launching without a path specified (`code`/`code -n`) should open a new window with no folder opened (the same as ctrl+shift+n).
  - Note: This is different to what `window.reopenFolders` controls, I still want the previously opened folder to open when no instances of vscode are running.
  - Note: Currently multiple windows with *no folder open* will not open when using this method when `"window.reopenFolders": false`, but ctrl+shift+n works fine.

The second option is perfectly fine imo and would allow people to use the OS-level shortcuts that work with everything else (win+shift+num, shift+left click). It can also be a stop gap solution until multiple folders can be opened if that's the desired UX.

**Comment by bpasero** [comment] 2016-08-15 18:36
code -n should always open an empty window, does it not?

**Comment by calrsom** [comment] 2016-10-05 14:59
+1 For taskbar interactions (middle-click, and shift-click) to open a new window.

**Comment by Tyriar** [comment] 2016-12-21 19:26
@bpasero yes forcing the call to use `code -n` fixes this issue, for Linux specifically you can workaround this by changing the `Exec` line in `/usr/share/applications/code.desktop` to:

```ini
Exec=/usr/share/code/code -n %U
```

Personally I think this is how the CLI should work by default, unless `-r` was used or it was the same folder (#2686). If not, we could make the Windows shortcut use `-n` too like the workaround above.

**Comment by Tyriar** [comment] 2016-12-21 23:11
@joaomoreno is it possible to change the Windows shortcut to use `-n` so that shift+click and middle click work on the taskbar?

**Comment by bpasero** [comment] 2016-12-22 07:15
@Tyriar no, requires an Electron update and is already being taken care of in this PR: https://github.com/Microsoft/vscode/pull/15407

**Comment by Tyriar** [comment] 2017-01-03 18:20
@bpasero since making that comment I've found just adding `-n` is not enough as it forces a new window on a fresh launch even if hot exit backups are being restored. Always open a new window (unless there are backups) needs to be the default to fix this globally imo.

**Comment by bpasero** [comment] 2017-01-04 06:29
I see already different behaviour between Sublime (activates last active window) and Atom (opens a new empty window) so it looks like this is another area where we need a setting.

As for shift-click support on the launcher, that makes sense to open a new window.

**Comment by Tyriar** [comment] 2017-01-04 06:59
I think I found what we need for it to work for Linux without changing default behavior: using `[NewWindow Shortcut Group]` as the shortcut group. I'll check this out soon.

**Comment by bpasero** [comment] 2017-01-04 08:04
@Tyriar i think that makes sense, we could then actually also use it on Windows without having to update electron.

Also, people that want this behaviour from the command line could create an alias that always spawns code with this argument 👍

**Comment by Tyriar** [comment] 2017-01-04 08:18
I'll see if there's time to fit this in for Jan.

**Comment by Tyriar** [comment] 2017-01-05 18:11
I pushed the new CLI arg `--new-window-if-not-first` to master and integrated it into the .desktop file so this is fixed on the Linux side.

**Comment by bpasero** [comment] 2017-01-05 18:58
@Tyriar actually on Windows this might be more tricky and cannot be done easily even with that argument, now I just realise. Because by pinning Code to the taskbar, obviously you are pinning the normal Code.exe without arguments. There is no way for us to detect this case unfortunately, so we still need the Electron update as well as https://github.com/Microsoft/vscode/issues/15407 to land to get it.

**Comment by Tyriar** [comment] 2017-01-05 19:02
Makes sense :+1:

**Comment by bartcubbins** [comment] 2017-03-15 02:40
can confirm this

**Comment by mosajjal** [comment] 2017-03-15 06:00
I don't know if this is related to the current issue, but when you run Code in a different folder from the command line, it still uses the first instance's environment. For example if I had two different virtualenvs, If I run Code in the first one, and then open up a new terminal, go to the second venv and run code from there, it still uses the binaries and the environment of the first venv.

**Comment by Tyriar** [comment] 2017-03-17 17:37
@mosajjal that's by design, there is only 1 Electron main process and all VS Code windows inherit it.

**Comment by mosajjal** [comment] 2017-03-17 18:01
@Tyriar isn't there a way to change that? My work as a Python developer is highly dependent on having multiple virtualenvs and running pep8 in them based on their specific PATH. Sublime3 does it pretty well but I like vscode's git integration and debugging tools.

**Comment by mikelward** [comment] 2017-03-31 16:42
+1

    code -n .
    code -n .

Should launch two instances.

In practice, I actually need to be able to run vscode in a remote desktop/VNC session and a local desktop session on the same machine, both editing the same folder/project.  At the moment, I have to pkill one so I can start the other.

**Comment by mosajjal** [comment] 2017-03-31 17:03
it works ! Thanks :-)

**Comment by fadeevab** [comment] 2017-05-23 10:08
Should this issue be closed? :)

**Comment by Spown** [comment] 2017-05-23 10:12
I still would love to have a new, empty VSC instance when I middle-click on the icon in the task panel (win10 and VSC already opened).

**Comment by mosajjal** [comment] 2017-05-23 12:09
no it should remain open. I'd REALLY like a solution for this. @mikelward's solution actually doesn't work.. 
Is there a general Linux or Windows sandboxing app so we can contain vscode inside it? By sandboxing I mean a wrapper script which doesn't show the parent process to the running one in each window or sth like that

**Comment by mikelward** [comment] 2017-05-23 12:26
@mosajjal I'm not saying that's the solution, I'm saying that's the steps to reproduce/desired behavior!

**Comment by mosajjal** [comment] 2017-05-23 12:28
@mikelward  I know. I edited my comment to point out that's not the solution. Looked a bit confusing

**Comment by necrifede** [comment] 2017-11-01 19:07
To meet my requirement I executed using sudo option on ubuntu. 
```
$ sudo code . --user-data-dir=../alternative_folder
```
for now i enough for me.

**Comment by northeastsquare** [comment] 2017-12-13 06:03
Hack worked vscode works via xrdp in Ubuntu MATE 16.04:

make a backup first
sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/lib/x86_64-linux-gnu/libxcb.so.1
https://github.com/Microsoft/vscode/issues/3451

**Comment by mikemol** [comment] 2018-01-04 18:13
Would having a separate instance permit me to edit a file in one window and have the preview of the file update in the other window? My use case has me modifying documents in Markdown or whiteboarding in Graphviz, and sharing up the live previews in meetings. That works better if I can share up only the preview, and not the source code.

**Comment by spiralsam** [comment] 2018-02-18 07:57
Speaking only for myself, opening using Code is a great experience. Opening Code is a bad experience (using Windows). No workaround makes it better for various reasons.

The "-n" command line is not scalable:

1. The Code installer places what looked like dozens+ of Windows registry entries pointing to "Code.exe" for filetypes and explorer context menu actions. In order to add this as a default option manually, I'd have to edit each one of these to add "-n" as an argument (out of frustration to Code's startup behavior, I began to try to but stopped after realizing there were so many). I also am encouraged edit registry as well as edit the system-wide Code start menu shortcut as Administrator.

2. Even if (1) were feasible, this doesn't change the behavior of the Windows taskbar, which executes Code.exe (or maybe an equivalent application execution call (?)) without the "-n" argument. Middle-clicking Code's icon in the Windows taskbar, or using Win+Shift+[n] (where [n] is the place of Code in the taskbar). always activates an active Code window rather than opening a new window. As far as I can tell there is no way to change this.

The window.openFilesInNewWindow=on option solves half the problem of opening files from Explorer, but adds the problem of forcing all File->Open commands to open files in new windows (not my own desire), in addition to not solving the "other problem above.

Seeing as how this issue is from Nov 2015, I just want to update the issue for this year, 2018, that Windows Notepad still currently has a more sensible application activation experience: **opening the shortcut opens a new window, middle-click taskbar opens new window, and opening files from Explorer opens new windows, and File->Open does not open new windows. Not possible with Code.

Opening Code is a primary user interface experience, and the configuration solutions presently don' t address this. I like all the configuration options but here, many new configurations need not be necessary, I would just like to request a single window.openJustActLikeWindows7NotepadCirca2009=true. All these other window.open* features are handy conveniences that are fun to have, but they miss the broader picture. Again, only speaking for myself.

**Comment by cparker4486** [comment] 2018-03-07 16:48
@bpasero Any chance you could provide the reasoning from the Code team as to why this hasn't been implemented yet? It seems like a highly desired feature and is a behavior that's relatively unique to Code.

**Comment by bpasero** [comment] 2018-03-08 17:16
I am thinking about 2 changes to make this easier:

1) introduce a new setting `window.openWithoutArgumentsInNewWindow`
This setting would control what happens when you run Code without arguments when another instance is already running. I think on Linux and Windows we should change to opening a separate window and on macOS I would preserve the current behaviour of focussing the last active instance. If someone has pointers to OS UX guidelines in this area, I would appreciate it, but I have the feeling that macOS favours to focus the the running instance over opening a new one.

2) allow `window.openFilesInNewWindow: default` on Linux and Windows
The `default` option was never really supported for `window.openFilesInNewWindow` on Linux and Windows, but now it will favour to open a new window for opening files unless the file was opened from within the application (via file menu or file dialog). I will not change this setting though, by default we leave it to `off` because we prefer opening files in the last active instance over opening new windows.

Feedback welcome. The settings name is not ideal but was chosen to be similar to the other 2 settings we already have for files and folders.

**Comment by mikelward** [comment] 2018-03-08 18:56
My use case is `code .`.  Sounds like the second option would help there?

Would `-n` become equivalent to setting the first option?  (If it defaults to off on Mac, keeping the flag might make sense.)

**Comment by bpasero** [comment] 2018-03-09 05:59
@mikelward as for opening the same folder in multiple windows, that one is not handled with my proposed change. We have https://github.com/Microsoft/vscode/issues/2686 specifically for that case.

**Comment by bpasero** [comment] 2018-03-09 06:35
Closing as per https://github.com/Microsoft/vscode/issues/48#issuecomment-371556991

**Closed** 2018-03-09 06:34 UTC
Labels: feature-request, os-integration
