### ISSUE TITLE
Bug: Issues with Typing Devanagari Script in VS Code

### ISSUE THREAD

**Issue by Rana718** [microsoft/vscode#222328] opened 2024-07-21 05:11 UTC
Steps to Reproduce:

Open Visual Studio Code.
Set the input method to Devanagari script (e.g., using a specific keyboard layout or input method editor).
Attempt to type Devanagari characters in a text file.
Expected Behavior:
Devanagari characters should be typed correctly and rendered properly.

Actual Behavior:
Typing Devanagari characters results in incorrect or garbled text, or the input method does not work as expected.

**Comment by IllusionMH** [comment] 2024-07-21 16:07
Looks like duplicate of #222327
If it is - please close this one, upwote that, and add additional detsils there

**Closed** 2024-07-21 16:11 UTC
Labels: triage-needed
