### ISSUE TITLE
Feature Request: workspace keybindings

### ISSUE THREAD

**Issue by DerHerrGammler** [Microsoft/vscode#44112] opened 2018-02-21 11:15 UTC
I think it would be nice if there is a possible way to configure the KeyBinding also like every other Setting for specific wokrspaces. With this way I can configure my shortcuts for specific workspacec better and I can travel with my hole configuration to every Computer without reconfigure the system.

**Comment by RMacfarlane** [comment] 2018-02-21 17:53
Duplicate of https://github.com/Microsoft/vscode/issues/35675

**Closed** 2018-02-21 17:52 UTC
Labels: *duplicate, feature-request, keybindings

**Comment by RMacfarlane** [comment] 2018-02-21 21:30
Sorry, I pasted the wrong link. Here's the correct one: https://github.com/Microsoft/vscode/issues/18379

@alexandrudima do we plan to work on this? I see there is another open issue on this in the backlog https://github.com/Microsoft/vscode/issues/40703
