### ISSUE TITLE
VSCode's intellisense gets super slow in a Yarn Workspaces project

### ISSUE THREAD

**Issue by lffg** [microsoft/vscode#74588] opened 2019-05-29 23:43 UTC
Issue Type: <b>Bug</b>

My VSCode intellisense gets super slow while I'm coding in a project that is using a Yarn Workspaces and @types/styled-components. I've already updated all the @types dependecies but it still slow.

I've recorded a video to show how slow it is:

https://www.youtube.com/watch?v=ibHDE5jHw4M

Node that it has to reload when I've deleted the "theme" prop.

<details>
<summary>Some notes</summary>

I have this `sc-theme.d.ts` file (maybe this file is causing the issues...?):

```typescript
import theme from '../src/providers/Theme/theme'

type ThemeInterface = typeof theme

declare module 'styled-components' {
  // eslint-disable-next-line import/prefer-default-export
  export interface DefaultTheme extends ThemeInterface {}
}
```
</details>

If you want more info, please help me know.

Thanks in advance. :)

---

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.18GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.5.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.26
edge|luo|0.3.2
dotenv|mik|1.0.1
vscode-docker|Pet|0.6.2
material-icon-theme|PKi|3.8.0
code-settings-sync|Sha|3.2.9
highlight-matching-tag|vin|0.9.2
vscode-wakatime|Wak|2.1.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-05-30 01:05
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by lffg** [comment] 2019-05-30 20:09
No. The insiders build with no extensions (and with them) works absolutely fine. Nice new icon, by the way. :)

**Comment by mjbvz** [comment] 2019-05-30 20:21
Thanks for verifying

Closing this as a duplicate of https://github.com/microsoft/TypeScript/issues/30819

**Closed by mjbvz** 2019-05-30 20:21 UTC

**Comment by lffg** [comment] 2019-05-30 20:26
Just another question: do you know when this issue will be fixed inside a new VSCode update (not the insiders one).
