### ISSUE TITLE
hotkey 'ctrl+c' invalid in outer terminal 

### ISSUE THREAD

**Issue by ankyo** [Microsoft/vscode#7857] opened 2016-06-18 23:15 UTC
- VSCode Version: 1.21
- OS Version: win10

hotkey 'ctrl+c' invalid in outer terminal when open from vscode

**Comment by Tyriar** [comment] 2016-06-19 00:12
Duplicate of https://github.com/Microsoft/vscode/issues/6451

**Closed by Tyriar** 2016-06-19 00:12 UTC
