### ISSUE TITLE
Breakpoint on line with inline breakpoints breaks on first point instead of line itself

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#81879] opened 2019-10-02 23:38 UTC
Issue Type: <b>Bug</b>

1. Start debugging VSCode
2. Add a breakpoint to a line that has potential inline breakpoints, for example https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/preferences/browser/keybindingsEditor.ts#L508
3. Trigger the breakpoint being hit
4. Press F5 to continue

Instead of continuing, the breakpoint gets hit again. In the case of a breakpoint on the beginning of a loop, it gets hit for every item in the loop

![inlineBreakpoint](https://user-images.githubusercontent.com/3672607/66089137-e2efc280-e532-11e9-8821-89e79884c7f7.gif)

VS Code version: Code - Insiders 1.39.0-insider (695ee74864ef93d10f5de0861cb66af190e76211, 2019-10-02T08:57:07.116Z)
OS version: Darwin x64 18.7.0

**Comment by isidorn** [comment] 2019-10-03 12:13
I believe this is up to the debug adapter. Since vscode send the breakpoint without the `column` in this case and the debug adapter can interpreet it however it wants.
Here it seems that the `node2` adapter sets the breakpoint on first column. Thus also assigning to @roblourens so he can investigate from the `node2` side.

**Comment by roblourens** [comment] 2019-10-03 15:43
Hey @isidorn I'm confused by what I'm seeing. The DA is reporting two breakpoint locations, which you see in gray, at columns 14 and 39. And it sets a breakpoint on that line and says that it's on line 14. So I think the first decoration on this line is supposed to be red.

```
From client: setBreakpoints({"source":{"name":"keybindingsEditor.ts","path":"/datadrive/vscode-oss/src/vs/workbench/contrib/preferences/browser/keybindingsEditor.ts"},"lines":[508],"breakpoints":[{"line":508}],"sourceModified":false})
[...]
To client: {"seq":0,"type":"response","request_seq":69,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":1002,"verified":true,"line":508,"column":14}]}}
[...]
From client: breakpointLocations({"source":{"name":"keybindingsEditor.ts","path":"/datadrive/vscode-oss/src/vs/workbench/contrib/preferences/browser/keybindingsEditor.ts"},"line":508})
[...]
To client: {"seq":0,"type":"response","request_seq":71,"command":"breakpointLocations","success":true,"body":{"breakpoints":[{"line":508,"column":14},{"line":508,"column":39}]}}
```

For the actual stepping behavior, it does return to that statement on each iteration of the loop and there is no valid breakpoint on that line outside of the loop. This is really annoying for the reason you point out, unfortunately I can't improve it.

**Comment by isidorn** [comment] 2019-10-04 09:30
The issue is this code [here](https://github.com/Microsoft/vscode/blob/c8252b63f547674d2faf361d4181bb76b0b5f81a/src/vs/workbench/contrib/debug/common/debugModel.ts#L620)
Basically we only respect the column if the user explicitly set it. Reason being that if the user was not interested in column breakpoints we would not show them.
I think this heuristic no longer has ground with our rendering of breakpoint locations. So I plan to remove it first thing next week so we get feedback if this upsets people (I think it should not).

**Comment by roblourens** [comment] 2019-10-04 18:11
Oh I see - yeah I think it makes sense to remove that

**Closed** 2019-10-07 12:35 UTC
Labels: bug, debug
