### ISSUE TITLE
[js] Quotes not parsed properly in ES6 string templates

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#1174] opened 2015-12-10 19:29 UTC
When using single or double quotes within back-tick quotes, they are not considered quoted:

![screenshot 2015-12-10 14 26 50](https://cloud.githubusercontent.com/assets/573056/11725918/1e339a48-9f4a-11e5-90ac-d02f433dcdca.png)

So if they happen to be closed within the back ticks, it's not the end of the world, but if not, all subsequent formatting is lost.

**Comment by jeromu** [comment] 2015-12-11 04:14
+1, I ran into the same issue, even if my jsconfig.json is set to ES6:
{
	"compilerOptions": {
		"target": "ES6",
		"module": "commonjs"
	}
}

**Comment by aeschli** [comment] 2015-12-11 09:03
duplicate of #133.

**Closed by aeschli** 2015-12-11 09:03 UTC
Labels: bug, js
