### ISSUE TITLE
Regex find and replace - unwanted group replacing during search

### ISSUE THREAD

**Issue by szepeu** [Microsoft/vscode#58701] opened 2018-09-14 15:33 UTC
- VSCode Version: 1.27.1
- OS Version: Windows 7 64bit

Steps to Reproduce:
1. Create a file with any "regexable" content, simple c program as example:

```c
#include <stdio.h>

int main (void)
{
    int a = 10;
    
    if (a == 8)
        printf ("is 8");
    else
        printf ("is not 8");

    return 0;
}
```

Now, let's assume I find function-space-bracket convention ugly, so I'd like to change all its occurences to function-bracket with no space in between.

2. Press `ctrl+f`, use regex and search for `(\w+) \(`
This will find all occurences I'm interested in.

3. Press `ctrl+h` to expand "search" dialog to "search and replace"

*Expected:* Cursor will move to "replace" line, keeping all found items; using `$1(` as a replacement, I can replace everything found in the search scope as I want it.

*Actual:* As cursor moves to "replace" line, first regex group in "find" line gets replaced by first group match (in this example, `(\w+) \(` changes into `main \(`). 

For this not to happen, I have to use `ctrl+h` initially, use mouse cursor (or `shift+tab`) to move to "search" line, write regex, `tab` to "replace" line, write replacement. It makes search and replace using regex a bit annoying when used often. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment] 2018-09-17 17:54
Duplicate of #41027 and there is a PR to fix this issue https://github.com/Microsoft/vscode/pull/44984, I'll play with the PR and have it fixed.

**Comment by roblourens** [comment] 2018-09-17 21:47
I will come up with a similar fix for Search. Sort of relevant to https://github.com/Microsoft/vscode/issues/52320 as well.

**Closed** 2018-09-22 17:50 UTC
Labels: bug, search
