### ISSUE TITLE
The logo

### ISSUE THREAD

**Issue by gonoiu** [Microsoft/vscode#36639] opened 2017-10-20 14:32 UTC
- VSCode Version: latest
- OS Version: win10

Steps to Reproduce:

1. The logo is really ugly
2. The logo is really ugly
 
The new logo is so ugly can't even click on it to open the editor. I'm going to use somethig else.

**Comment by chrisdias** [comment] 2017-10-20 15:34
Don't give up on us yet, we're working on it!

Dupe of https://github.com/Microsoft/vscode/issues/35783

**Closed by chrisdias** 2017-10-20 15:34 UTC
Labels: workbench

**Comment by richarddavenport** [comment] 2017-10-20 15:38
@gonoiu hahahahahahaha
