### ISSUE TITLE
NodeJS "no debug adapter" when printing objects.

### ISSUE THREAD

**Issue by Guicbdiniz** [microsoft/vscode#93139] opened 2020-03-21 16:06 UTC
When I try to expand the content of a object while using the NodeJS console, a "no debug adapter" is show.

- VSCode Version: 1.43
- OS Version: Windows 10 Home - 1909
- Node version: 12.16.1

Steps to Reproduce:

1. Create a simple file with single object and log it to console.

```javascript
const myObject = {
    'hey': 'ho'
}

console.log(myObject)
```

2. Try to expand it in the console

![image](https://user-images.githubusercontent.com/43941670/77230603-21764980-6b74-11ea-8f83-48889b5b68f0.png)

Does this issue occur when all extensions are disabled?: Yes

Edit: I forgot to mention that I'm debugging the code, not simply running it. When I try to run it, the object is printed fine.

![image](https://user-images.githubusercontent.com/43941670/77230753-2982b900-6b75-11ea-87a0-aa39b745307a.png)

**Comment by bjesuiter** [comment] 2020-03-22 07:49
Interesting, I have the same problem. 
My system: 

- VSCode Version: 1.43.1
- OS Version: 10.14.6 (18G3020)
- Node Version: v12.16.1

**Comment by isidorn** [comment] 2020-03-23 10:16
In the newest vscode insiders you will get a more precise error message.
This is expected behavior, since you stopped debugging and the objects can no longer be evaluated.
Closing as designed. And for inspecting objects please put a breakpoint

**Closed by isidorn** 2020-03-23 10:16 UTC
