### ISSUE TITLE
Terminal opens with powershell while git bash is my default

### ISSUE THREAD

**Issue by Sven-27** [microsoft/vscode#132535] opened 2021-09-07 10:43 UTC
Issue Type: <b>Bug</b>

My terminal keeps opening powershell. Even though git bash is my default terminal. I have tried several options like reinstall vscode and git. and i found solutions for settings.json. what i have tried. But when opening vscode or switching to another project it opens powershell. 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.34GB free)|
|Process Argv|--crash-reporter-id 6d40e99d-034e-4857-bba8-9edd9af472bb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
emojisense|bie|0.8.0
vscode-tailwindcss|bra|0.6.14
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.1.0
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.8
vscode-pull-request-github|Git|0.30.0
stylelint-plus|hex|0.56.6
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
vscode-peacock|joh|3.9.1
styled-components-snippets|jon|0.10.0
vscode-styled-components|jpo|1.6.6
start-git-bash|McC|1.2.1
git-graph|mhu|1.30.0
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.16.1
vsliveshare|ms-|1.0.4761
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1
vscode-stylelint|sty|0.86.0
vscode-icons|vsc|11.6.0
quokka-vscode|Wal|1.0.398
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn478:30356813
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-07 10:50
/duplicate of #132150 and will be fixed in upcoming 1.60.1 recovery release

**Closed** 2021-09-07 10:51 UTC
Labels: *duplicate
