### ISSUE TITLE
Javascript regex syntax highlighting fails for !/regex/.test

### ISSUE THREAD

**Issue by qsniyg** [microsoft/vscode#91906] opened 2020-03-02 17:54 UTC
Issue Type: <b>Bug</b>

If parenthesis aren't added around /regex/.test(...), syntax highlighting for the regex fails (and occasionally it will break the syntax highlighting for code below it as well)

```
// regex syntax highlighting fails
if (!/[test]test/.test(test)) {
    console.log("test");
}

// regex syntax highlighting succeeds
if (!(/[test]test/.test(test))) {
    console.log("test");
}
```

VS Code version: Code - OSS 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-17T09:32:31.598Z)
OS version: Linux x64 5.5.5-zen1-1-zen

**Comment by mjbvz** [comment] 2020-03-02 19:14
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed by mjbvz** 2020-03-02 19:14 UTC
