### ISSUE TITLE
Consider gitignore or folders list for updateImportsOnFileMove.enabled config

### ISSUE THREAD

**Issue by SamvelRaja** [Microsoft/vscode#52258] opened 2018-06-19 06:09 UTC
- VSCode Version: Code-insider-1.25.0
- OS Version: Window 10 pro

Steps to Reproduce:

1. javascript.updateImportsOnFileMove.enabled = 'always'
2. rename any file.

This will freeze the whole vscode, as it tries to change `import` on all node_modules I have.

Expected behavior? if so, kindly make it configurable.

Does this issue occur when all extensions are disabled?: Doesn't matter

**Comment by mjbvz** [comment] 2018-06-19 17:11
Duplicate of https://github.com/Microsoft/TypeScript/issues/24914

Please try upgrading your workspace to typescript@next by following [these instructions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2018-06-19 17:11 UTC
Labels: javascript
