### ISSUE TITLE
Diagnostics break for the entire file when an empty `message` is posted

### ISSUE THREAD

**Issue by lnicola** [microsoft/vscode#155531] opened 2022-07-18 18:37 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.69.1
- OS Version: Linux

Spotted in https://github.com/rust-lang/rust-analyzer/issues/11404. I suspect the `undefined` in https://github.com/microsoft/vscode/blob/5acd9508c913b1d0ce3243f056c3cb039bac6938/src/vs/platform/markers/common/markerService.ts#L201-L203 breaks the caller.

CC https://github.com/microsoft/vscode/issues/5952

![image](https://user-images.githubusercontent.com/308347/179580240-25691eaf-86ca-4d4b-a5b0-b05f14870ba5.png)

Repro (with rust-analyzer):

```rust
fn main() {
    $;
    compile_error!("");
    $;
}
```

![image](https://user-images.githubusercontent.com/308347/179580365-e30c81fd-ac0d-41f4-9be5-cbe7af8f917c.png)

![image](https://user-images.githubusercontent.com/308347/179580394-96773f22-1927-4fe1-9af0-ffcafacf3c04.png)

![image](https://user-images.githubusercontent.com/308347/179580411-67139b1b-f4ed-4a6a-a0c5-bbf30b9ae714.png)

**Comment by jrieken** [comment] 2022-08-16 07:24
This is thrown in the extension host ([here](https://github.com/microsoft/vscode/blob/f07a9c82259009af17e617f7daaa797901abda87/src/vs/workbench/api/common/extHostTypes.ts#L1061)) and indicates bad extension behaviour. Depending on how the extension is written this likely prevent further errors but not errors from other extension. 

Closing as extension-caused since they must provide valid diagnostic objects

**Closed by jrieken** 2022-08-16 07:24 UTC

**Comment by lnicola** [comment] 2022-08-16 07:28
I don't think this is a bug in the extension. Rust code can legitimately emit compilation errors without a message. And the compiler does that too (for the related diagnostics), if I recall correctly.

**Comment by Veykril** [comment] 2022-08-16 09:49
Curious but is it documented somewhere that the diagnostic message is not allowed to be empty? If not that should be at least written down somewhere.

Fwiw the language server protocol also does not say that a message has to be non-empty, so either that should be added to that there as well or in my eyes VSCode is missing something to handle that case  there.

**Comment by lnicola** [comment] 2022-08-28 14:22
@jrieken would you mind reconsidering this, given the two comments above?

**Comment by jrieken** [comment] 2022-08-29 07:34
Yes, this is very much intentional. The one change I should probably do is to also throw with whitespace-only strings. Diagnostics are user-facing elements, they represent an issue with source code and doing that without a message feels illogical. 

Maybe I am not understanding your use-case but when would like to see an error squiggle (or entry in the problems views) without stating what the problem is? What's the use-case and how is that desirable?

**Comment by lnicola** [comment] 2022-08-29 08:00
> The one change I should probably do is to also throw with whitespace-only strings.

You're not throwing away anything, you're completely breaking the diagnostics for the whole extension when you encounter an empty one.

> What's the use-case and how is that desirable?

1. Rust code, including libraries, can emit compiler errors with an empty message. That might not be a great experience for the users, but it's fully allowed and used. [Sample](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8c357d031ae94f8e0c9d76a9f7bcadfb). Some popular libraries do or [did this](https://github.com/rust-lang/rust-analyzer/issues/10051#issuecomment-1027166434) at one point.
2. Rust compiler errors include multiple spans. Notice how the one on `&'a i32` has no message:

![image](https://user-images.githubusercontent.com/308347/187151087-48c2e4a0-8f30-4398-9730-93e95f0f0f72.png)

We expand them to multiple diagnostics, in order to show them nicely:

![image](https://user-images.githubusercontent.com/308347/187151567-aed921d0-5e1c-42c2-bd1f-cccf030e7a38.png)

If you delete the first span, you throw away information from the compiler:

![image](https://user-images.githubusercontent.com/308347/187152154-cccd6af6-2aae-4d07-9b7d-3db37891755b.png)

And of course, by throwing that exception, you're [**completely breaking**](https://github.com/rust-lang/rust-analyzer/issues/10051) diagnostics in the whole file (or even project/workspace, I don't remember), even those that **do** have an associated message.

We could duplicate the message from `&'b i32` in this case, but I'm not sure that works every time, and it would crowd out the diagnostic list. I think we did something like this at one point.

**Comment by jrieken** [comment] 2022-08-29 08:42
Why aren't you using [`DiagnosticRelatedInformation`](https://github.com/microsoft/vscode/blob/f00fde0f2401b6cab737136b3622ff4aa7e6db2f/src/vscode-dts/vscode.d.ts#L5999) for such cases?

**Comment by lnicola** [comment] 2022-08-29 08:50
[We are](https://github.com/rust-lang/rust-analyzer/blob/e8e598f6415461e7fe957eec1bee6afb55927d59/crates/rust-analyzer/src/diagnostics/to_proto.rs#L308-L313). As far as I know, this was/is also an issue for those.

And that doesn't fix the `compiler_error!` case.
