### ISSUE TITLE
Autocompletion makes it impossible to type spread/rest operator in javascript

### ISSUE THREAD

**Issue by bmarkovic** [microsoft/vscode#130770] opened 2021-08-13 14:04 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  Version: 1.59.0-insider
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open any Javascript file
2. Start typing elipsis by pressing full stop key three times
3. Your text buffer fills with up to three copies of first suggestion from intellisense/autocomplete, depending on typing speed sometimes one of them is an actual full stop character.

This started happening after the update to the current version of insiders

**Comment by Dramaturco** [comment] 2021-08-13 14:19
I've got the same issue on 1.59.0

**Comment by IllusionMH** [comment] 2021-08-13 14:33
/duplicate of #130096 which is candidate for July 2021 Recovery release

**Closed** 2021-08-13 14:34 UTC
Labels: *duplicate
