### ISSUE TITLE
Files importing renamed file are not saved after refactor

### ISSUE THREAD

**Issue by Letiste** [microsoft/vscode#149003] opened 2022-05-07 17:48 UTC
With the new update of April 2022, there is now [the option to automatically save a file after refactoring](https://code.visualstudio.com/updates/v1_67#_save-files-after-refactoring). 
It works well when for instance I rename a variable used in other files, it saves them too.
But, when renaming a file, it doesn't automatically save the files importing the renamed file. I think it should also work in that case (feel free to close this issue if you think otherwise).

Does this issue occur when all extensions are disabled?: Yes

Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:
1. Create two files `file_imported.js` and `file_importing.js`
2. In `file_importing.js`, import `file_imported.js` (`import "./file_imported"`)
3. Rename `file_imported.js` via the UI (right-click -> Rename) and confirm to update imports
4. `file_importing.js` is not saved

**Comment by mjbvz** [comment] 2022-05-07 22:01
Duplicate of #148901

**Closed by mjbvz** 2022-05-07 22:01 UTC
