### ISSUE TITLE
can not open a file with [ctrl + p] some times

### ISSUE THREAD

**Issue by match5** [Microsoft/vscode#60920] opened 2018-10-15 02:12 UTC
Issue Type: <b>Bug</b>

press [ctrl + p] 
search a file and enter
some times it dose not work

VS Code version: Code - Insiders 1.29.0-insider (931c22033db3cc8d5dff265889307ed4076ac2d3, 2018-10-12T05:17:15.739Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (8.00GB free)|
|Process Argv|D:\workspace\GameHall\gamehall.code-workspace|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Lua|key|0.0.9
prettify-json|moh|0.0.3
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
js-atom-grammar|ms-|0.1.14
vscode-icons|rob|7.27.0
markdown-preview-enhanced|shd|0.3.8
pdf|tom|0.3.0
propertylist|zho|0.0.2

</details>

**Comment by match5** [comment] 2018-10-16 04:08
yes, @genosonic 's description is more clear
@bpasero this Download didn't fix it

**Comment by bpasero** [comment] 2018-10-16 05:05
If someone is willing to do what I outline in https://github.com/Microsoft/vscode/issues/60163#issuecomment-430099279 I can try to reproduce. Thanks in advance.

Marking as duplicate of https://github.com/Microsoft/vscode/issues/60163

**Closed by bpasero** 2018-10-16 05:05 UTC
Labels: insiders, needs more info
