### ISSUE TITLE
occupation of CPU is too high when open the specify project

### ISSUE THREAD

**Issue by icesman** [Microsoft/vscode#26726] opened 2017-05-16 08:05 UTC
- VSCode Version: 1.12.2
- OS Version: osX 10.12.5

Steps to Reproduce:

1. open the [demo](https://github.com/icesman/vue-multiple-page-cnode) 

2.open the web pack.config.js on the root

And then cpu was occupied with process of the Code Helper, make the laptop so hot.
<img width="803" alt="2017-05-16 3 37 08" src="https://cloud.githubusercontent.com/assets/12438996/26095678/fff1ef1e-3a50-11e7-8532-6757e236d7aa.png">
<img width="803" alt="2017-05-16 3 37 08" src="https://cloud.githubusercontent.com/assets/12438996/26095700/1945acf8-3a51-11e7-82ac-5e023602d7b2.png">

Firstly I think it is caused by the plugin and uninstall the plugin, but it still is the same.
It works fine with other projects but somehow  goes wrong with the demo.

**Comment by bpasero** [comment] 2017-05-16 09:54
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by dmlemos** [comment] 2017-05-16 10:34
Same here. First time I started VS Code after updating to 10.12.5 my CPU went burst on all cores. I closed the process immediately. The second time I started this is what happened:

First lines are % CPU usage
```
100.0  0.0  2497332   4240   ??  R    11:22am   0:53.62 find -L . -not ( ( -name node_modules -o -name .git -o -name .svn -o -name .hg -o -name CVS -o -name .DS_Store ) -prune ) -type f
98.4  0.0  2498356   4248   ??  R    11:10am   0:56.48 find -L . -not ( ( -name node_modules -o -name .git -o -name .svn -o -name .hg -o -name CVS -o -name .DS_Store ) -prune ) -type f
```

After closing, these were still around:
```
120.3  7.1  4865388 1191620   ??  R    11:10am  22:46.70 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
103.6  7.9  4781088 1326112   ??  R    11:22am   8:56.52 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
```

Had to kill them by hand

After restarting it for the third time seems to be stable!

**Comment by icesman** [comment] 2017-05-17 00:49
It seems it is caused by TypeScript

<img width="1235" alt="2017-05-17 8 45 18" src="https://cloud.githubusercontent.com/assets/12438996/26133967/bfa4e802-3add-11e7-89fc-3a2fb12d35ae.png">

**Comment by bpasero** [comment] 2017-05-17 05:15
Looks like TypeScript typings aquisition.

**Comment by icesman** [comment] 2017-05-17 06:08
Can I fix it ?
Actually it happens in some earlier versions of VS Code.

**Comment by hezedu** [comment] 2017-05-20 01:38
`.eslintrc` causes CPU to always be high.

**Comment by dmlemos** [comment] 2017-05-23 16:02
More issues related to this #27133 #27131.
This seems to be getting quite common.

Is there any more information you need?

**Comment by mjbvz** [comment] 2017-05-31 03:27
The typings installer high CPU issue was tracked by https://github.com/Microsoft/TypeScript/issues/15301 but we didn't have enough data to investigate this.

@icesman TypeScript powers both our javascript and TypeScript language features. Using the latest insiders build for VSCode 1.13, can you please try collecting the typings installer logs: 

* Set `"typescript.tsserver.log": "verbose",`
* Restart VSCode and reproduce the issue
* Run the `TypeScript: Open TS Server log` command
* This should open a folder. Share the `ti-xxx.log` file in this folder.

 > **⚠️Warning:** The TypingsInstaller log may include information from your workspace, including module names and file paths. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by icesman** [comment] 2017-05-31 07:08
@mjbvz I try the VSCode 1.13 but can't reproduce the issue. 
It works well of the VSCode 1.13

**Comment by icesman** [comment] 2017-05-31 08:21
@mjbvz  It appears again after working about half hour...
```
Global cache location '/Users/iceman/Library/Caches/typescript', safe file path '/applications/visual studio code - insiders.app/contents/resources/app/extensions/node_modules/typescript/lib/typingsafelist.json'
Processing cache location '/Users/iceman/Library/Caches/typescript'
Trying to find '/Users/iceman/Library/Caches/typescript/package.json'...
Loaded content of '/Users/iceman/Library/Caches/typescript/package.json': {"devDependencies":{"@types/async":"^2.0.40","@types/babel-core":"^6.7.14","@types/compression-webpack-plugin":"^0.3.1","@types/copy-webpack-plugin":"^4.0.0","@types/extract-text-webpack-plugin":"^2.0.1","@types/firebase":"^2.4.31","@types/glob":"^5.0.30","@types/html-webpack-plugin":"^2.28.0","@types/js-base64":"^2.1.5","@types/node":"^7.0.18","@types/optimize-css-assets-webpack-plugin":"^1.3.1","@types/sprintf":"0.0.28","@types/stylus":"^0.48.27","@types/webpack":"^2.2.15","@types/webpack-dev-server":"^1.12.6","@types/webpack-hot-middleware":"^2.15.0","@types/webpack-merge":"0.0.4"}}
Adding entry into typings cache: 'async' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/async/index.d.ts'
Adding entry into typings cache: 'babel-core' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/babel-core/index.d.ts'
Adding entry into typings cache: 'compression-webpack-plugin' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/compression-webpack-plugin/index.d.ts'
Adding entry into typings cache: 'copy-webpack-plugin' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/copy-webpack-plugin/index.d.ts'
Adding entry into typings cache: 'extract-text-webpack-plugin' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/extract-text-webpack-plugin/index.d.ts'
Adding entry into typings cache: 'firebase' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/firebase/index.d.ts'
Adding entry into typings cache: 'glob' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/glob/index.d.ts'
Adding entry into typings cache: 'html-webpack-plugin' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/html-webpack-plugin/index.d.ts'
Adding entry into typings cache: 'js-base64' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/js-base64/index.d.ts'
Adding entry into typings cache: 'node' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/node/index.d.ts'
Adding entry into typings cache: 'optimize-css-assets-webpack-plugin' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/optimize-css-assets-webpack-plugin/index.d.ts'
Adding entry into typings cache: 'sprintf' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/sprintf/index.d.ts'
Adding entry into typings cache: 'stylus' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/stylus/index.d.ts'
Adding entry into typings cache: 'webpack' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/webpack/index.d.ts'
Adding entry into typings cache: 'webpack-dev-server' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/webpack-dev-server/index.d.ts'
Adding entry into typings cache: 'webpack-hot-middleware' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/webpack-hot-middleware/index.d.ts'
Adding entry into typings cache: 'webpack-merge' => '/Users/iceman/Library/Caches/typescript/node_modules/@types/webpack-merge/index.d.ts'
Finished processing cache location '/Users/iceman/Library/Caches/typescript'
Process id: 15479
NPM location: npm (explicit '--npmLocation' not  provided)
Npm config file: /Users/iceman/Library/Caches/typescript/package.json
Updating types-registry npm package...
Got install request {"projectName":"/dev/null/inferredProject1*","fileNames":["/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es6.d.ts","/Users/iceman/vue-multiple-page-cnode/webpack.config.js"],"compilerOptions":{"module":1,"target":2,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"allowJs":true,"jsx":1,"checkJs":false,"noEmitForJsFiles":true,"maxNodeModuleJsDepth":2},"typeAcquisition":{"enable":true,"include":[],"exclude":[]},"unresolvedImports":["caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","caniuse-db","child_process","crypto","events","events","fs","http","net","path","readline","stream","tls"],"projectRootPath":"","kind":"discover"}


```

Here is the log, I hope it is helpful for u

**Comment by mjbvz** [comment] 2017-06-01 01:40
Hey @andy-ms, the `"projectRootPath":"","kind":"discover"` bit looks suspicious. It seems like the `discoverTypings` function never completes in this cases?

Can you please take a look at the logs and see if anything stands out

**Comment by dmlemos** [comment] 2017-06-01 12:36
@mjbvz Unfortunately I cannot get the log. I set the setting, but when I try `TypeScript: Open TS Server log` gives me this error:
> Could not open TS Server log file

**Comment by icesman** [comment] 2017-06-01 13:49
@dmlemos  I also can't open the log file and I use the `ps aux | grep <pid>` to get the information. It also print the path of log file after you enable the log.

**Comment by mjbvz** [comment] 2017-06-01 21:12
Yes there was a bug in VSCode 1.12 where if the logfile grows very large we would fail to open it.

`ps aux` should work, and in VSCode 1.13 the `Open TS Server Log`command will now open the log file directory instead of trying to open the log file itself. VSCode 1.13 also prints to log file path to the TypeScript section of the output window (scroll to the very to of the output to see this):

![screen shot 2017-06-01 at 2 09 54 pm](https://cloud.githubusercontent.com/assets/12821956/26700930/0d731cf0-46d4-11e7-8a38-6a9aaaa0f0b7.png)

You can try this out in the current insiders builds: https://code.visualstudio.com/insiders

**Comment by mjbvz** [comment] 2017-06-01 21:27
Talked with the TypeScript team this morning about this issue. As a first step to investigate what may be causing the high cpu usage with the typings installer, I believe that we need to add some additional logging around the `discover` part of the typings installer. I've opened https://github.com/Microsoft/TypeScript/issues/16203 to track this work on the TypeScript side. We'll continue the investigation into this problem over there

Thanks

**Closed by mjbvz** 2017-06-01 21:27 UTC
Labels: freeze-slow-crash, javascript, typescript, upstream

**Comment by dmlemos** [comment] 2017-06-02 11:39
Can't get the log path with `ps` either. Running this command:
`ps aux | grep -i code | grep -i log`

**Comment by jens1o** [comment] 2017-06-02 11:46
You can download it here: https://code.visualstudio.com/insiders

(It will update each day.)

**Comment by dmlemos** [comment] 2017-06-12 15:14
Issue remains with 1.13.0

**Comment by mecp** [comment] 2017-06-14 14:06
Same here with 1.13.0

**Comment by icesman** [comment] 2017-06-15 03:09
@mecp @dmlemos  the issue now is moved to  [Microsoft/TypeScript#16203](https://github.com/Microsoft/TypeScript/issues/16203) . It's not fixed right now.
