### ISSUE TITLE
Multiple extensions not showing up or have wrong download counts

### ISSUE THREAD

**Issue by ItsDrike** [microsoft/vscode#109365] opened 2020-10-26 10:44 UTC
- VSCode Version: 1.50.1
- OS Version: Linux x64 5.9.1-arch1-1

Steps to Reproduce:

1. Go to extensions menu
2. Search for a specific extension called `Todo+`
3. No such extension found
4. Go to online [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus&ssr=false#version-history) where the extension shows up and it's quite popular
5. Copy the installation command
6. Use it in my local vscode and watch as nothing happens

Problem 2 (seems related, but I can open new issue if necessary):

1. Go to extensions menu
2. Search for the official Python extension
3. Look at the download count
![image](https://user-images.githubusercontent.com/20902250/97163025-51c43d00-1780-11eb-8b0a-aad9ad45d624.png)
4. Go to online [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ms-python.python) and check the real download count 
![image](https://user-images.githubusercontent.com/20902250/97163154-7ae4cd80-1780-11eb-9ce2-9e5b03f882c2.png)
5. Compare the numbers (78,701 - local, 26,553,865 - online marketplace)
6. Make sure it's the correct extension by checking the id `ms-python.python`

Does this issue occur when all extensions are disabled?: Yes

Description

I'm not sure why but I have just reinstalled my operating system (Arch Linux) and I've installed `code` repository 
![image](https://user-images.githubusercontent.com/20902250/97162363-66ec9c00-177f-11eb-91ef-4b2221c352ad.png)

Since the moment I've opened it and tried to install my common extensions I was using before the reinstallation, I knew there was something wrong since I couldn't found a lot of my extensions, initially I simply assumed that they were removed but that seemed unlikely when it was more than 4 extensions, so I went to online marketplace and found them still active there, I tried using the installation command but nothing happened. A while later I looked up the Python extension and found that the download amount was nowhere near the actual amount, I figured out that there's something very wrong with the extensions in my vscode but I've no idea what and considering this is a fresh installation, I don't think it has to do with my OS

**Comment by tamuratak** [comment] 2020-10-26 11:08
Duplicate of #107997. See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

The count you see is the one of https://open-vsx.org/extension/ms-python/python.

**Comment by ItsDrike** [comment] 2020-10-26 11:32
I've checked the comment you referenced and I understand now, but I still wonder if there's any way to switch it back without having to use outdated version

**Comment by sandy081** [comment] 2020-10-26 14:28
https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178 says following

> I was having this issue too, so I did a bit of digging. The change causing this was introduced in 1.49.1-1, in which the Arch packagers switched the marketplace to Open VSX. https://git.archlinux.org/svntogit/community.git/commit/trunk?id=b62a02ec645f16528c0269faf12e362a55efda75
A temporary workaround for this is to use the prior version: `sudo pacman -U https://archive.archlinux.org/packages/c/code/code-1.49.0-2-x86_64.pkg.tar.zst`
The proper solution for this is to reach out to the extension's maintainers and ask them to publish to Open VSX. See https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php (Ctrl + F for `missing`).

Closing this as not sure if there is any fix that can be done in VS Code.

@joaomoreno FYI - not sure if you have any ideas here.

**Closed by sandy081** 2020-10-26 14:28 UTC

**Comment by ItsDrike** [comment] 2020-10-26 14:38
A possible way for vscode to fix this directly may be to add a direct option to choose which marketplace should be used as a command
