### ISSUE TITLE
Inline-suggestion appearing at previous cursor location

### ISSUE THREAD

**Issue by johanrosenkilde** [microsoft/vscode#132516] opened 2021-09-07 07:06 UTC
Does this issue occur when all extensions are disabled?: No (Needs InlineSuggestions from some extension)

- VS Code Version: 1.60.0
- OS Version: MacOS Catalina 10.15.7

Steps to Reproduce:

1. Use GitHub Copilot. The exact version shouldn't be important, but this was verified using 1.4.2586.
2. Open a blank Python document and enter the following text:

```
thisVariable = 
thatVariable = 
``` 

There are a single space after each `=` sign. Put the cursor on the end of the first line and trigger Copilot inline-suggestion by pressing Backspace then Space. Don't accept it, but press Down-arrow, Backspace, Space. After pressing Down-arrow the suggestion on the first line disappears (as it should), but after the Backspace+space, you may see the suggestion briefly appear again, before the new inline-suggestion appearing on the second line.

This is a bit flaky, and it may not appear every time the cursor is moved. It may also depend on latency to the Copilot server, and so be less pronounced in e.g. North America than in Europe or Asia.

*Edit by @hediet*: This is the buggy behavior:
![Kapture 2021-09-06 at 16 52 18](https://user-images.githubusercontent.com/3774274/132235064-50fbc790-27df-4bf5-9dd3-ccc257036036.gif)

**Comment by hediet** [comment] 2021-09-07 10:46
Please let me know soon if we should release this with our Recovery Release tomorrow!

**Comment by johanrosenkilde** [comment] 2021-09-07 14:12
Thanks for your lightning fast fix, @hediet! 🍾 🥳  Releasing this quickly would be awesome - it's a quite distracting glitch!

**Comment by hediet** [comment] 2021-09-08 08:08
@johanrosenkilde can you verify that the issue is fixed in todays insider build?

**Comment by hsenag** [comment] 2021-09-08 08:27
> @johanrosenkilde can you verify that the issue is fixed in todays insider build?

As he's out today, I've had a play with today's insiders build and can't reproduce it, whereas I can with the insiders build from 6th September. So looks good to me!

**Closed** 2021-09-08 08:49 UTC
Labels: bug, candidate, regression, z-author-verified, inline-completions
