### ISSUE TITLE
Window not visible when using remote desktop connection and multiple monitors

### ISSUE THREAD

**Issue by pbricout** [microsoft/vscode#40708] opened 2017-12-22 08:56 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
code-spell-checker|str|1.6.2
spellchecker|swy|1.2.13

---

Steps to Reproduce:

1. One computer A with 2 screens the main screen being the right screen
2. Another computer B with 2 screens the main screen being the left screen
3. On computer A launch VSC and place it on the left screen
4. Remote desktop (dual screen) from computer B to computer A
5. The position of the VSC window is not updated to be visible on the screens, it is left on the left position of the main screen of the computer B hence invisible and not accessible

Tips:
The make the window visible, bring the focus to the VSC windows, type ctrl-space, M, one arrow key, then move the mouse.

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-12-22 09:07
There is a duplicate of this around better supporting Code when using remote desktop connections and multiple users but I cannot find it. @joaomoreno remember?

**Comment by bpasero** [comment] 2017-12-22 09:08
Ah wait, this is actually different, nevermind.

**Comment by bpasero** [comment] 2017-12-22 09:08
Setting electron label as this might require API that we do not have today to find out about monitor locations when using remote desktop.

**Comment by pbricout** [comment] 2018-05-18 13:26
Any update on this? Is the Electon API available or not?

**Comment by bpasero** [comment] 2019-10-08 14:21
I am sorry but currently not having enough resources to resolve this, nor fully understand it.

**Closed by bpasero** 2019-10-08 14:21 UTC
Labels: electron, upstream, workbench-os-integration
