### ISSUE TITLE
MAC OS x el capitan vscode upgrade to 0.10.5 cannot be used

### ISSUE THREAD

**Issue by ryj438591419** [Microsoft/vscode#1521] opened 2015-12-21 08:30 UTC
MAC OS x el capitan vscode upgrade to 0.10.5 cannot be used

**Comment by Onlytanya** [comment] 2015-12-21 08:35
you can start up code  with a English-US keyboard layout.

**Comment by jrieken** [comment] 2015-12-21 08:41
closing as duplicate of #1463

**Comment by ryj438591419** [comment] 2015-12-21 08:41
@Onlytanya  oh ! thank

**Comment by jrieken** [comment] 2015-12-21 08:43
sorry, for the hassle. we hope to get an update out soon

**Closed** 2015-12-21 10:00 UTC
