### ISSUE TITLE
Actions when using multiple cursors are only executed on the main one

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#10884] opened 2016-08-24 10:52 UTC
If I try to use Emmet's or VScode's selection expansion, emmet's wrap function or any other extension the action is only executed on the first cursor.

A use case I often use in ST3: `cmd+d` to select class names, then `ctrl+d` to expand to the container in question and finally `ctrl+w` to wrap all the containers in another container.

In VScode, any action apart from text editing (typing or deleting) will remove all secondary cursors.

**Comment by sandy081** [comment] 2016-08-25 12:56
@jrieken Assigning to you since I think it is related to the current work you are doing (not sure). Otherwise please re-assign it.

Thanks.

**Comment by jrieken** [comment] 2016-08-25 13:02
dupe of https://github.com/Microsoft/vscode/issues/9764

**Closed by jrieken** 2016-08-25 13:02 UTC
Labels: duplicate
