### ISSUE TITLE
During changes comparing I cannot select removed lines

### ISSUE THREAD

**Issue by ivanMalchenko** [microsoft/vscode#75198] opened 2019-06-10 12:41 UTC
Issue Type: <b>Bug</b>

In Source control I click a changed file, then in the new window I can look at changes, like what was removed or added, but I cannot select removed lines, but only in "side by side view" I can do so.
I want to select removed lined also. 

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

**Comment by egamma** [comment] 2019-06-11 07:01
Duplicate of https://github.com/microsoft/vscode/issues/8226

**Closed by egamma** 2019-06-11 07:01 UTC
