### ISSUE TITLE
Terminal find match count is incorrect

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#148109] opened 2022-04-26 04:58 UTC
Testing #148060

1. Create a new terminal
2. Run a script which logs the same text 2000 times
3. Run a query, ✅ find widget says there are 2000 matches
4. Resize the terminal (e.g. collapse and expand the side bar)
5. :bug: the number of matches is now less even though the same amount of scrollback is visible, moreover deleting and reentering the query doesn't reset the match count

![image](https://user-images.githubusercontent.com/30305945/165224114-9b32a38e-fe61-43e2-aacc-24ba66c65e51.png)

**Comment by rchiodo** [comment] 2022-04-27 20:31
Maybe this isn't released yet, but I'm still getting the same problem in today's insiders.

**Comment by joyceerhl** [comment] 2022-04-27 21:54
Still repros for me :(

**Comment by meganrogge** [comment] 2022-04-27 22:26
Can one of you pls provide a gif? it's working for me with the above example as expected and with others

**Comment by meganrogge** [comment] 2022-04-27 22:28
https://user-images.githubusercontent.com/29464607/165641806-c0c4f14a-6890-4feb-89ff-7ab7e5776b06.mov

**Comment by meganrogge** [comment] 2022-04-27 23:03
You are both on Windows - I wonder if that has to do with this. Could someone on mac pls verify this?

**Comment by joyceerhl** [comment] 2022-04-27 23:58
![Recording 2022-04-27 at 16 57 53](https://user-images.githubusercontent.com/30305945/165649947-2b4fd81b-fc94-427f-b2be-ffe476153948.gif)

**Comment by meganrogge** [comment] 2022-04-28 00:41
![playwright-screenshot-3-Error (1)](https://user-images.githubusercontent.com/29464607/165653708-5e89fe94-8f76-4c1b-bfa8-b522c91db1dd.png)

**Comment by Tyriar** [comment] 2022-05-25 15:30
Something weird going on here:

![image](https://user-images.githubusercontent.com/2193314/170300023-481c49b0-9515-4abc-9815-cc4edb8da205.png)

This is after pasting in " Hi Hi" many times, once the command wraps to the end the terminal freaks out (conpty reprinting), but at some point it breaks and find only finds one result. Finding the next works, but it still says 1 of 1.

**Comment by Tyriar** [comment] 2022-05-26 20:19
More weird behavior
![Recording 2022-05-26 at 13 18 56](https://user-images.githubusercontent.com/2193314/170573223-99eeb311-651a-4a0b-9b10-7e8f3f52a91a.gif)

**Comment by Tyriar** [comment] 2022-05-26 20:37
All results aren't getting included when search results get highlighted 
![image](https://user-images.githubusercontent.com/2193314/170576011-85247b12-1770-45e5-b3a1-644f93bd6a6b.png)

**Comment by Tyriar** [comment] 2022-05-26 21:40
Problem here seems to be the search addon gets confused because translateToString considers the second character whitespace:

https://github.com/Tyriar/xterm.js/blob/fd5f5e3204843263c13bda850502d1d77be2b3e5/src/common/buffer/BufferLine.ts#L436

But in the search algorirthm it's treated as a null character, `''` of length 0, as opposed to `' '`.

**Comment by joyceerhl** [comment] 2022-06-02 22:54
Still reproing this. Initially:

![image](https://user-images.githubusercontent.com/30305945/171751138-a6b33297-145f-428a-a912-529bf25c8de2.png)

After making the terminal panel taller:

![image](https://user-images.githubusercontent.com/30305945/171751240-bfc920bf-ccef-4a21-af01-2aa733446d22.png)

**Comment by Tyriar** [comment] 2022-06-02 23:26
@joyceerhl this is on Windows? That's actually by design because of the way conpty works, it ends up losing lines just above the bottom of the buffer.

**Comment by Tyriar** [comment] 2022-06-03 11:41
Pretty sure you were seeing https://github.com/microsoft/vscode/issues/150886 so closing this again for verification

**Closed by Tyriar** 2022-06-03 11:41 UTC
Labels: bug, upstream, verification-found, windows, upstream-issue-linked, terminal-find
