### ISSUE TITLE
Line Height in the "Folder" section of the sidebar.

### ISSUE THREAD

**Issue by muchologo** [microsoft/vscode#59873] opened 2018-10-03 04:34 UTC
It would be nice to be able customizing the line height or separation between the folders and file names of the sidebar. There are plenty and awesome themes out there, but the "folders view" is still to tight in comparition with the editor which we can tweak using the line height.
![feature-vsc](https://user-images.githubusercontent.com/28572911/46390065-877ac280-c69b-11e8-95a3-7000fe79ada6.jpg)

**Comment by isidorn** [comment] 2018-10-03 16:13
Somewhat a duplicate of https://github.com/Microsoft/vscode/issues/519
But let's keep this open for now since it is about line height

**Comment by MoOx** [comment] 2018-11-29 21:00
Time to make some noize on this PR https://github.com/Microsoft/vscode/pull/63602

**Comment by kanlukasz** [comment] 2019-08-08 12:06
#63602 is already closed due to merge conflicts.
I am also waiting for this line height option

**Closed** 2020-07-30 15:32 UTC
Labels: *out-of-scope, feature-request, file-explorer

**Comment by IAmTahazzot** [comment] 2023-03-22 03:59
There are _**Millions**_ of developers out there who want to personalize their VSCode experience to meet their unique needs. This is precisely what makes open-source software so powerful - the ability to shape and mold a tool to fit your individual workflow.

However, I understand that it can be disheartening to feel like our voice is not being heard in the VSCode community. Our opinion as a user is incredibly worthless to this community. This community are constantly striving to improve and evolve VSCode based on the feedback you receive from users like us.

>  So ignoring our opinion without saying any reason is not the best choice.

**Comment by prsy** [comment] 2023-07-18 08:32
Strange workflow:
1. "This feature request received a sufficient number of community upvotes and we moved it to our backlog"
2. @[isidorn](https://github.com/isidorn) isidorn added the [*out-of-scope]

**Comment by suxscribe** [comment] 2024-11-04 10:26
This feature is still pretty much needed. Please consider adding this 🙏

**Comment by Julian24Design** [comment] 2025-02-09 04:20
Is this feature still not implemented?

**Comment by rublev** [comment] 2025-02-09 21:04
I hate vscode. The simplest stuff is just not possible. Unbelievable.

**Comment by IAmTahazzot** [comment] 2025-02-12 08:34
> I hate vscode. The simplest stuff is just not possible. Unbelievable.

If you’re not satisfied with the community, it’s worth asking—what brings you here?

- Have an issue? Feel free to report it.
- Have suggestions or want to contribute a new feature? We’d love to see your pull request.
- If you genuinely dislike the community, remember—participation is completely voluntary.

Let’s keep the space constructive and focused on growth. Your contributions, feedback, and positive engagement are always welcome.
