### ISSUE TITLE
Can not change plugin version when plugin changelog page opened.

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode#95665] opened 2020-04-20 05:59 UTC
- VSCode Version: 1.44.2
- OS Version: Win10

### Steps to Reproduce:

1. Install the latest version of intelliCode or other java pack plugin
2. Install another version on the plugin changelog page

### Result:
Install another version button doesn't work.

![image](https://user-images.githubusercontent.com/44559777/79718543-dbe1a380-830e-11ea-887b-fc52942911b4.png)

**Comment by gjsjohnmurray** [comment] 2020-04-20 10:51
I can repro in 1.44.2 but not in 1.45.0-insider

Probably fixed by https://github.com/microsoft/vscode/issues/88284#issuecomment-615496315

**Comment by chrmarti** [comment] 2020-04-20 12:16
@EricZhangzf Could you check if this is fixed in 1.45? Download: https://code.visualstudio.com/insiders/

**Comment by EricZhangzf** [comment] 2020-04-21 02:33
@chrmarti  can not repro in 1.45, Fixed

**Comment by chrmarti** [comment] 2020-04-21 06:39
Thanks, closing as duplicate of https://github.com/microsoft/vscode/issues/88284.

**Closed by chrmarti** 2020-04-21 06:39 UTC
Labels: needs more info, new release
