### ISSUE TITLE
When using multicursor, Home and End keys do not scroll.

### ISSUE THREAD

**Issue by sant123** [Microsoft/vscode#13252] opened 2016-10-05 15:21 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 8.1

Steps to Reproduce:
1. Make some long texts until appears the horizontal scroll on the editor.
2. Use multicursor in some or all of these lines.
3. Press Home or End key to see what happens.

![bug multicursor](https://cloud.githubusercontent.com/assets/7959437/19119399/3b9d6e42-8ae5-11e6-90c8-7a5096667712.gif)

**Comment by alexandrudima** [comment] 2016-10-06 12:53
In this case (where the multiple cursors are close, we could scroll), but in the general case (where you could have multiple cursors on hundreds of distinct lines that do not fit within the viewport) this is impossible to do.

**Comment by sant123** [comment] 2016-10-06 13:21
@alexandrudima a good example you could take is the ```Sublime Text``` editor, it has multiple cursors support and this issue is not present here 😄.

**Comment by alexandrudima** [comment] 2016-10-06 13:34
@sant123 Thanks. Have you tried adding 1000 cursors on 1000 different rows?

**Comment by sant123** [comment] 2016-10-06 14:13
I haven't had the need to add 1000 cursors @alexandrudima 😃. However, take this as an example:

I have 75 lines in a file, but I only see 48 because of my monitor. Now I add the multicursor on the 75 lines of my file, then I press home and end keys. What should it do? Move the cursors to the beginning or the end of each row. I don't have to see the others because I know the others are in the beginning or in the end.

Is this what you are trying to tell me?

**Comment by alexandrudima** [comment] 2017-11-24 15:17
Duplicate of #6995

**Closed by alexandrudima** 2017-11-24 15:17 UTC
Labels: editor-multicursor, feature-request
