### ISSUE TITLE
Cannot toggleWrapping on terminal in the Editor Area at startup

### ISSUE THREAD

**Issue by BrokenClient** [microsoft/vscode#230619] opened 2024-10-06 04:06 UTC
Type: <b>Bug</b>

When starting up vscode with a terminal in the editor area, I cannot use `Alt+Z` to toggle word wrap for the terminal. However, the `Ctrl+ArrowUp/Down` (to scroll to the previous/next command) is available.

![image](https://github.com/user-attachments/assets/bd8b3dcc-096c-4b1a-9679-56978fd1272a)
(it may look like this, when i open the workspace, it return to the way it was closed, but the `Alt+Z` is not responsive)

When I start the terminal in the panel location using `` Ctrl+` ``, then the editor area terminal returns to normal.

![image](https://github.com/user-attachments/assets/4a5cfe75-4c1d-4451-b67c-afab879d8f9a)
(open terminal in the panel, everything becomes ok)

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.25GB free)|
|Process Argv|--crash-reporter-id 16da6464-ee3f-4f0d-a13e-72e0ae8b2074|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 0)|
|Memory (System)|7.68GB (6.65GB free)|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.8.0
arm|dan|1.7.4
es7-react-js-snippets|dsz|4.4.3
codespaces|Git|1.17.3
CppSnippets|har|0.0.15
output-colorizer|IBM|0.1.2
better-cpp-syntax|jef|1.27.1
vsc-python-indent|Kev|1.18.0
debug-tracker-vscode|mcu|0.0.15
peripheral-viewer|mcu|1.4.6
vscode-edge-devtools|ms-|2.1.6
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.88.4
vscode-serial-monitor|ms-|0.13.240924001
material-icon-theme|PKi|5.11.1
scala|sca|0.5.8
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.5
linkerscript|Zix|1.0.4
codegeex|AMi|2.17.0
eide|cl|3.20.0
doxdocgen|csc|1.4.0
xml|Dot|2.5.1
prettier-vscode|esb|11.0.0
hex-fmt|ker|1.0.0
labeled-bookmarks|koa|1.1.11
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
vscode-serial-monitor|ms-|0.13.240924001
korofileheader|OBK|4.9.3
vscode-yaml|red|1.15.0
xmake-vscode|tbo|2.3.7
gnu-mapfiles|tro|1.1.0
cmake|twx|0.0.17
srecord|xia|0.0.5
vscode-dosbox|xsr|0.1.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by meganrogge** [comment] 2024-12-16 22:25
closing as I cannot reproduce

**Closed by meganrogge** 2024-12-16 22:25 UTC
Labels: bug, terminal-editors
