### ISSUE TITLE
Running Task commands, will delete comments from tasks.json file

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#105885] opened 2020-09-01 21:30 UTC
- VSCode Version: 1.48.2 and 1.49.0-insider
- OS Version: Win64

Steps to Reproduce:

1. configure a few tasks in tasks.json file.
2. add some comments to the tasks.json file.
3. Run "`Tasks: Configure default build task`"
4. Change the default task
5. Now you will see that the comments are removed from tasks.json file.

The same issue will happen when running any Tasks command that needs to modify the tasks.json file (e.g. "`Task: configure task`", ...)

**Comment by sean-mcmanus** [comment] 2020-09-01 22:11
Looks like a duplicate of https://github.com/microsoft/vscode/issues/29453

**Comment by elahehrashedi** [comment] 2020-09-01 22:35
@sean-mcmanus Should I close this?

We solved this issue in C/C++ extension by using the `comment-json` library.

**Comment by sean-mcmanus** [comment] 2020-09-01 23:26
Yeah, you could close it. I think the VS Code team would close it as a duplicate.

**Comment by alexr00** [comment] 2020-09-02 07:53
@sean-mcmanus thanks for pointing out the duplicate. It is indeed a duplicate of #29453.

**Closed by alexr00** 2020-09-02 07:53 UTC
