### ISSUE TITLE
Unable to open a separate file

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#15599] opened 2016-11-17 00:31 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (fea4db1666427b95b649614fb7c40f25e3f5cf8d, 2016-11-16T22:05:31.640Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.0|
|tortoise-svn|fantasytyx|0.1.1|
|cpptools|ms-vscode|0.9.2|
|vscode-icons|robertohuertasm|4.0.1|

---

Steps to Reproduce:

1. Open any file by  Double-click  or right click
2. VSCode as follow
![2016-11-17_083047](https://cloud.githubusercontent.com/assets/8591065/20371490/2c44d1ce-aca0-11e6-95eb-ab384f8f1a70.png)

**Comment by ramya-rao-a** [comment] 2016-11-17 01:06
@chrmarti Duplicate of #15594 ?

**Comment by ramya-rao-a** [comment] 2016-11-17 01:21
The new insiders build has the fix. Please update.

**Closed by ramya-rao-a** 2016-11-17 01:21 UTC
