### ISSUE TITLE
Can't have dropdown action in composite title toolbar

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#98580] opened 2020-05-26 12:09 UTC
@lszomoru Uncovered a regression in the composite title toolbar, wrt actions and action items.

This commit attempts to put a `joao` action in the `RepositoryPane` title toolbar: https://github.com/microsoft/vscode/commit/e3b154ff372ea6e3c070da52a7f7e41dc039580a

Upon reload, you'll hit this line 3 times:

https://github.com/microsoft/vscode/blob/77b5058284a50445674ee3b237ad64793b38965e/src/vs/base/browser/ui/actionbar/actionbar.ts#L644-L644

The first two times, the correct `actionViewItemProvider` from `RepositoryPane` gets calls. The third time, the active composite seems to be the `SCMViewlet`, so the wrong provider gets called and my action gets rendered incorrectly.

---

This is blocking @lszomoru, who's implementing a feature which requires a dropdown action.

**Comment by sbatten** [comment] 2020-05-26 17:58
I don't understand the issue. I've patched with that commit and see that the action is in the titlebar.

![image](https://user-images.githubusercontent.com/6561887/82934026-b5331000-9f3f-11ea-8a84-a723ab28acc1.png)

What is the issue?

**Comment by sbatten** [comment] 2020-05-26 17:59
Oh, is it that this will not show up in the merged view container?

**Comment by lszomoru** [comment] 2020-05-26 18:52
@sbatten, the issue is that if you look at the DOM you will see that `MyAction` is rendered as a button instead of being rendered as a Dropdown. The expectation is that the the DOM of the two toolbar buttons is the same. Please ping me on Slack if you have any questions or concerns. Thanks!

**Comment by joaomoreno** [comment] 2020-05-27 07:30
Oh, you're right, totally forgot the punchline! That was a very underwhelming conclusion. I've pushed another commit to help illustrate the issue.

Notice that despite this line running twice, the action item still doesn't get rendered as a `joao` text dom node:

https://github.com/microsoft/vscode/blob/77163b71211a9c6ed4dbb5f5b4fe07c92ccdd1c5/src/vs/workbench/contrib/scm/browser/repositoryPane.ts#L688-L688

**Comment by sbatten** [comment] 2020-08-13 00:55
closing as this seems to be working fine now. JOAO is being rendered properly and I have testing adding a separate dropdown menu item in the primary actions of the title toolbar

**Closed by sbatten** 2020-08-13 00:55 UTC
Labels: bug, regression

**Comment by roblourens** [comment] 2020-09-02 23:23
I don't know how to merge those sample commits in with all the changes in the meantime. I'll mark it as verified because Steven said it worked recently
