### ISSUE TITLE
Enhancements => Custom CSS/JS  &  Extension icons in activity bar

### ISSUE THREAD

**Issue by Bram-Zijp** [Microsoft/vscode#20513] opened 2017-02-12 19:40 UTC
I would like to recommend the following enhancements:

1. Files to add custom CSS/JS to modify the editor.
2. Add functionality for Extensions to optional include icons in the activity bar.

**Comment by Tyriar** [comment] 2017-02-13 02:09
Duplicate of https://github.com/Microsoft/vscode/issues/459

The activity bar currently has a proposed API out that lets explorers be contributed.

**Closed by Tyriar** 2017-02-13 02:09 UTC
