### ISSUE TITLE
[Linux] Keyboard shortcuts do not update when keyboard mappings change for system

### ISSUE THREAD

**Issue by yingw787** [Microsoft/vscode#55381] opened 2018-07-30 17:46 UTC
- VSCode Version: 1.25.1 / 1dfc5e557209371715f655691b1235b6b26a06be / x64
- OS Version: Ubuntu 16.04.5 LTS

Steps to Reproduce:

1. Install Dvorak on your system.
2. Install VSCode.
3. Add some keyboard shortcuts (Ctrl + S to save).
4. Open VSCode with keyboard mapping Dvorak.
5. Create a text file.
6. Change keyboard mapping back to QWERTY.
7. Save using Ctrl + S with S being QWERTY S.
8. If fails, try using Ctrl + S with S being Dvorak S (';')

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by yingw787** [comment] 2018-07-30 17:50
This should not a duplicate of #48336, as that issue refers to keyboard mappings upon startup, while this one is changing keyboard mappings while the process is running.

**Comment by alexandrudima** [comment] 2018-07-30 20:38
Duplicate of #23690

**Closed by alexandrudima** 2018-07-30 20:38 UTC
Labels: keyboard-layout
