### ISSUE TITLE
Toggling fixed width only works one way

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#133971] opened 2021-09-28 09:19 UTC
Testing #133550

* have fixed with on
* in a narrow terminal type `ls -la`
* select `alt+z`, existing text is re-rendered correctly
* select `alt+z` again, :bug: no effect

https://user-images.githubusercontent.com/1794099/135059941-07d76af4-b5cf-4e9c-ad16-059bcd3025ae.mov

**Comment by meganrogge** [comment] 2021-09-28 21:11
I'm having trouble reproducing this

**Comment by meganrogge** [comment] 2021-09-29 14:37
could be related to the (now fixed) problem of losing terminal focus, since that's a precondition for the action to run https://github.com/microsoft/vscode/blob/246c663214aee34f0da6032d461b013381ba22c1/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1871-L1884

**Comment by meganrogge** [comment] 2021-09-29 18:59
this happens after reloading the window

**Closed** 2021-10-04 22:48 UTC
Labels: bug, terminal
