### ISSUE TITLE
Text-editor context menu is too crowded

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#106483] opened 2020-09-11 11:57 UTC
- VSCode Version: 1.49.0
- OS Version: Win10

Steps to Reproduce:
I have been using VS Code for ~3 years now, and I have yet to reach a point where I can intuitively use the right-click context menu of the text editor. I have given up hope in a way.

1. Install a few common extensions  (basically, Python, Gitlens)
2. Right-click in a `.py` file
3. That's too long:

![image](https://user-images.githubusercontent.com/12128514/92922689-854c4180-f436-11ea-98ee-0346abd30ab0.png)

Does this issue occur when all extensions are disabled?: No

**Comment by sbatten** [comment] 2020-09-12 00:07
@joaomoreno for comments on submenu api

**Comment by joaomoreno** [comment] 2020-09-14 09:39
Yeah, definitely needs cleanup. Not sure I'm the right person for this though.

**Comment by alexdima** [comment] 2020-09-14 14:19
I agree, but that is what happens when we open up a contribution point. Every extension believes that its actions are very important and must render in the context menu. IMHO this can be tackled by making the context menu editable by end users, e.g. similar to how keybindings can be edited by end users, to remove, to add, or to regroup actions in the context menu.

**Comment by jrieken** [comment] 2020-09-14 14:24
/duplicate of https://github.com/microsoft/vscode/issues/9285

**Closed** 2020-09-14 14:25 UTC
Labels: *duplicate, feature-request, menus, new release
