### ISSUE TITLE
Is it possible to have different text sizes in different windows when i change it one window it changes in all , 

### ISSUE THREAD

**Issue by hariprasath95** [Microsoft/vscode#36722] opened 2017-10-23 04:34 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-97-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-astyle|chi|0.7.1
githistory|don|0.2.3
local-history|gay|0.0.3
easy-icons|jam|0.3.1
cpptools|ms-|0.14.0
sublime-keybindings|ms-|2.9.1
java|red|0.12.0
trailing-spaces|sha|0.2.11
highlight-trailing-white-spaces|yba|0.0.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-10-23 05:07
Duplicate of #35913

**Closed** 2017-10-23 09:19 UTC
