### ISSUE TITLE
Allow custom editors to integrate with VS Code's context menu

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115096] opened 2021-01-26 17:15 UTC
I don't think this is possible currently and since the web platform does not have a means to control a native context menu it means that extensions would need to implement their own context menus. Integrating with VS Code's context menu would give the added benefit of allowing it to flow naturally out of the webview.

**Comment by mjbvz** [comment] 2021-01-29 21:11
Duplicate of #54285

**Closed by mjbvz** 2021-01-29 21:11 UTC
Labels: custom-editors
