### ISSUE TITLE
Source control: On opening panel, the commit message input doesn't get focus

### ISSUE THREAD

**Issue by levu42** [microsoft/vscode#145315] opened 2022-03-17 13:55 UTC
Issue Type: <b>Bug</b>

Step to reproduce:
- Press Ctrl+Shift+G (or whatever shortcut is assigned to switching to the "Source control" sidebar

Expected behavior:
- Sidebar opens and commit message input gets focus

Actual result:
- Sidebar opens but commit message input doesn't get focus

I consider this to be a bug since Ctrl+Shift+F for the search sidebar puts the focus into the search input

VS Code version: Code - OSS 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T18:39:38.183Z)
OS version: Linux x64 5.16.14-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.38GB (0.71GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.2
vscode-intelephense-client|bme|1.8.2
laravel-goto-view|cod|1.3.7
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
vscode-html-css|ecm|1.11.0
prettier-vscode|esb|9.3.0
php-intellisense|fel|2.3.14
todo-tree|Gru|0.0.215
test-adapter-converter|hbe|0.1.4
vscode-test-explorer|hbe|2.21.1
vscode-php-create-class|jag|1.5.0
volar|joh|0.33.2
php-cs-fixer|jun|0.2.10
vscode-php-refactoring|mar|1.3.1
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vetur|oct|0.35.0
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
vscode-thunder-client|ran|1.12.5
vscode-phpunit|rec|2.0.76
vscode-blade-formatter|shu|0.13.9
laravel-goto-controller|ste|0.0.15

</details>

**Comment by lszomoru** [comment] 2022-12-12 15:49
Closing this as duplicate of #131006.

**Closed by lszomoru** 2022-12-12 15:49 UTC
Labels: bug, git
