### ISSUE TITLE
Allow Windows cmd / Powershell to run as administrator

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#8051] opened 2016-06-23 13:05 UTC
- VSCode Version: Code - Insiders 1.3.0-insider (5eaf9f05038b0a9818ebff510e1aafe07ac1ae68, 2016-06-23T05:07:59.360Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open a Terminal window (either CMD.exe or Powershell)
2. Option to specify that command prompt is running with elevated permissions (Administrator)

This will help / allow some processes that run better as administrator. (eg. ember-cli, angular-cli) : 

```
c:\code\ng2test> ng serve

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.
```

(yes, this is actually angular-cli, but it's based off ember-cli, therefore the 'Ember CLI' in the message...)

**Comment by dbaeumer** [comment] 2016-06-23 20:52
Is this the integrated terminal ?

**Comment by jtsom** [comment] 2016-06-23 21:32
Sorry, yes the integrated terminal

**Comment by Tyriar** [comment] 2016-07-05 19:55
Duplicate of #7407. Not planning on supporting this, note that you can call `runas.exe` to run a command as an admin like so:

```
runas.exe /savecred /user:administrator "%sysdrive%\testScripts\testscript1.ps1" 
```

I find it a bit concerning that ember would ask for admin privileges at all though.

**Closed by Tyriar** 2016-07-05 19:55 UTC
Labels: feature-request, integrated-terminal

**Comment by jtsom** [comment] 2016-07-05 19:59
I believe it has to do with the way ember-cli / angular-cli do their builds- creating lots of symlinks on Windows not as an admin user is horribly slow.
