### ISSUE TITLE
minimap mouseDown + drag should behave like scrollbar

### ISSUE THREAD

**Issue by matthaeus** [Microsoft/vscode#54620] opened 2018-07-19 00:06 UTC
Like shown in this video: [https://twitter.com/matthaeus/status/1019730562154618880](https://twitter.com/matthaeus/status/1019730562154618880)

**Comment by alexandrudima** [comment] 2018-07-19 07:40
Duplicate of #21708. Read https://github.com/Microsoft/vscode/issues/21708#issuecomment-283600344

**Closed by alexandrudima** 2018-07-19 07:40 UTC
Labels: editor, editor-minimap
