### ISSUE TITLE
Debug Console: wrong order of incoming input

### ISSUE THREAD

**Issue by roojay520** [Microsoft/vscode#33822] opened 2017-09-05 03:32 UTC
## Runtime environment
* Visual Studio Code v1.15.1 own compiler
* Node.js v8.2.1
* OS: Windows_NT ia32 10.0.15063

## Description

I want to add "After sort:" between source arry and sort arry, look like this:
![CONSOLE Screenshot 1][1]

But console occasionally shows:
![CONSOLE Screenshot 2][2]

Why for-of-loop  has not finished running, jump out to run console.log ? Source code:
```javascript
    // Random to generate double digits.
    function getRandom() {
      return Math.round(Math.random() * 100);
    }
    // Writing data to the array.
    var score = [
      ["a", getRandom()],
      ["b", getRandom()],
      ["c", getRandom()],
      ["d", getRandom()],
      ["e", getRandom()]
    ];
    console.log("Before sort:");

    // Print source arry
    for (let m of score) {
      console.log(m);
    }

    // Call sort()
    score.sort((a, b) => {
      return b[1] - a[1];
    });
    console.log("After sort:");

    // Print sort arry.
    for (let n of score) {
      console.log(n);
    }
```
If i change my code like this:
```javascript
// Writing data to the array.
var score = [["a", 55], ["b", 33], ["c", 44], ["d", 88], ["e", 22]];
// Print source arry
for (let m of score) {
  console.log(m);
}
console.log("After sort：");
```
This bug will still appear: 
![CONSOLE Screenshot 3][3]

  [1]: https://i.stack.imgur.com/cAxmB.png
  [2]: https://i.stack.imgur.com/3faEk.png
  [3]: https://i.imgur.com/0fUXBNo.png

**Comment by isidorn** [comment] 2017-09-05 07:38
This is just the order the order in which node is emitting events. Not sure if we can do anything here, though assigning to @roblourens since I see you are using the inspector protocol.

**Comment by roblourens** [comment] 2017-09-05 22:24
The output events come back from the adapter in the right order, but they seem to get reordered by the console when it resolves the variables.

If the log statement is `console.log(1)` instead of logging an object, then this doesn't repro.

**Comment by isidorn** [comment] 2017-09-06 09:05
I acknowledge the bug, the issue is that vscode gets an object as output from `node2`. VSCode has to get the children of that object by sending some request to `node2`. In the meantime more output comes which gets recieved before the children get resolved thus being appended to the output before.

[Code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L338)

The fix would be to remember the events in which they came and append them to the repl in that order. This has the downside that if some object takes a long time to resolve all subsequent output will be stuck.
Not a big fan of the fix -> backlog

**Comment by roojay520** [comment] 2017-09-06 10:08
Thanks for your answer.

**Comment by roblourens** [comment] 2017-09-06 17:41
Can't the object be inserted in the right position, once it's resolved, while still appending other output?

This seems like a really bad bug - having logs in the wrong order could make someone waste a lot of time debugging.

**Comment by isidorn** [comment] 2017-09-07 08:07
Yes, we could insert it in the right position by changing the [`appendToRepl`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L957) API we have in the `debugModel`.
I would only look into this if more users complain since the model is quite fragile due to various heuristics on spliting incoming output.

**Comment by good-bits** [comment] 2017-10-29 06:21
@isidorn Possibly related to this defect and hopefully helpful: I bumped an issue where console.log() and console.error() messages appear out of order in the JavaScript DEBUG CONSOLE. The isolated code below demonstrates the observation. Doesn't happen outside of the DEBUG CONSOLE. Thanks!

![image](https://user-images.githubusercontent.com/25337926/32141144-d5b71d20-bc35-11e7-80bf-461738c76092.png)

The DEBUG CONSOLE: 

![image](https://user-images.githubusercontent.com/25337926/32141157-129d0fa6-bc36-11e7-9196-5df9a3d4c0cf.png)

**Comment by isidorn** [comment] 2017-10-30 08:05
@good-bits yeah, this seem to be the same issue. Assigning to November to investigate into a fix.

**Comment by good-bits** [comment] 2017-10-30 11:33
@isidorn Thanks!

**Comment by weinand** [comment] 2017-11-07 11:04
I agree with Rob that this is really a bad bug that we should fix: logs are for troubleshooting bugs not for making the troubleshooting more difficult...

**Comment by isidorn** [comment] 2017-11-07 11:27
@good-bits I have investigated into your issue and it is actually not the same as the one from above. To be more precise the issue is in the debug adapter - it is sending the events in the wrong order. To track this issue I have created https://github.com/Microsoft/vscode/issues/37770

Keeping this open as this is a different issue explained in my comment above and I will investigate in a fix.

**Closed** 2017-11-08 11:02 UTC
Labels: bug, debug

**Comment by good-bits** [comment] 2017-11-08 20:01
@isidorn @roblourens @weinand Thank you so much!
