### ISSUE TITLE
[scss,css] Document synchronization stop after 3-4 hours.

### ISSUE THREAD

**Issue by sqnkov** [Microsoft/vscode#18323] opened 2017-01-09 16:44 UTC
- VSCode Version: 1.8.1 (Stable)
- OS Version: Win 10 Home

Steps to Reproduce:

1. Write SCSS for numerous hours
2. Stare at the error log while shifting your eyebrows up.

This tends to happen after 3 to 4 hours of work, whole editor slows down too. Restarting the editor fixes the problem for about an hour.

![strng](https://cloud.githubusercontent.com/assets/9406520/21774605/acb067d6-d69b-11e6-9a19-51791ecffcb2.PNG)

**Comment by aeschli** [comment] 2017-02-21 09:42
duplicate of #19840

**Closed by aeschli** 2017-02-21 09:42 UTC
Labels: css-less-sass, freeze-slow-crash
