### ISSUE TITLE
Visual Studio Code crashes after rapidly clicking the Menu bar options (File, Edit, View, etc)

### ISSUE THREAD

**Issue by aradiuk** [microsoft/vscode#90059] opened 2020-02-05 09:46 UTC
After rapidly clicking different Menu bar options (File, Edit, View, etc) I get a completely white option box and after a few second VSC crashes.

Tell me if you need any logs collected and how to do it, thank you.

Easily reproduced on my system.
System is Kubuntu version 19.10, running on VirtualBox:
VirtualBox Graphical User Interface
Version 6.1.2 r135662 (Qt5.6.2)
Copyright © 2020 Oracle Corporation and/or its affiliates. All rights reserved

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-29-generic

![image](https://user-images.githubusercontent.com/26429847/73830185-e2cb4080-480c-11ea-8bb1-6f0ed3433760.png)

**Comment by deepak1556** [comment] 2020-03-11 04:53
@aradiuk can you try disabling gpu with https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

closing this as a duplicate of https://github.com/microsoft/vscode/issues/84745

**Closed by deepak1556** 2020-03-11 04:53 UTC
