### ISSUE TITLE
The vscode internal terminal cannot load information registered in ${env:PATH}.

### ISSUE THREAD

**Issue by ChangWan-Kim** [microsoft/vscode#210158] opened 2024-04-11 11:59 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.0
- OS Version: Windows11 Home 22H2, 22621.3447

The vscode internal terminal cannot load information registered in ${env:PATH}.

for example,
When you run the “where.exe where” command in Windows Terminal,
"C:\Windows\System32\where.exe" is displayed.

However, if you enter the same command in the Powershell terminal within vscode, an "Object Not Found" error is displayed.

Commands that run well in Windows Terminal Powershell, such as "py", "ipconfig", and "cmd", do not work in vscode.

I installed cmake and tried to use it in vscode but ran into this problem.

How do I solve this?

**Comment by meganrogge** [comment] 2024-04-11 13:41
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-04-11 13:41 UTC
