### ISSUE TITLE
Terminal process terminated with exit code 4294901760

### ISSUE THREAD

**Issue by qaqz111** [microsoft/vscode#174658] opened 2023-02-17 08:33 UTC
I searched issues list and found several similar issues reported but nothing has been settled.

Here's my steps to reproduce this problem:

0. prepare a fresh installed VM with Win10x64, newest VC redistributable libs installed. (maybe not necessary)
1. download and unzip `VSCode-win32-x64-1.75.1.zip` to `C:\VSCode`
2. make dir `C:\VSCode\data`
3. download and install python using `python-3.11.2-amd64.exe` from `python.org`
4. run VSCode, install extension `Python by microsoft` and **`Python Environment Manager by Don Jayamanne`**
5. open `Python` pane by `Python Environment Manager`, click `Refresh Environments` button which was on top-right of the pane, the python installed should be found and put under `Global` node in the pane
6. hover the mouse cursor on node `Global -> Python (3.11.2) C:\XXXX....`, the `Open in Terminal` and `Set as active workspace interpreter` buttons should appear on the right most of the node
7. click `Open in Terminal` button, a terminal pane should appear at bottom of VSCode, giving an output message which saying `Internal Windows PowerShell error.  Loading managed Windows PowerShell failed with error 8009001d.`, then the terminal process terminated and terminal pane was closed, a notification banner popped up at right-bottom of VSCode saying `The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 4294901760.`

I monitored the powershell.exe process's start commandline using ProcessMonitor (from sysinternals) and found the commandline is:
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"C:\VSCode\VSCode-v1.75.1\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
```
This commandline works well in a cmd console but can not run in a powershell console and the pwsh shell report an error:
```
String missing terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```
This is because powershell can not escape `\"` to `"` but should be [ `" ] in the commandline.
I don't know if this is the cause of the error, and also I don't know if this error is caused by the Python Environment Manager extension.

**Comment by qaqz111** [comment] 2023-02-17 08:49
Additional message maybe of help I found:
1. Error code `0x8009001D` / `NTE_PROVIDER_DLL_FAIL`, description: `Provider DLL failed to initialize correctly.`
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/705fb797-2175-4a90-b5a3-3918024b10b8

2. Look like this problem indeed was caused by path resolve:
https://github.com/PowerShell/PowerShell/issues/3545

**Comment by meganrogge** [comment] 2023-02-17 22:12
Is there a reason you are using windows powershell?

Can you try to reproduce with an updated powershell version?

**Comment by qaqz111** [comment] 2023-02-18 02:51
The powershell I used is come with win10 installed, basically I do not use it at all in daily work, so there's no reason for me to install an updated version of powershell.

For this issue, I installed `powershell-v7.3.2-x64.msi` from this page: https://github.com/PowerShell/PowerShell/releases/tag/v7.3.2 in the VM, put the pwsh7 dir before the old one which comes with win10 in `PATH` env var. Good news is no `8009001d` came out any more and terminal pane got works, but appears another small little issue that I do not know whether it is caused by pwsh7 or the `Python Environment Manager` extension.

In the `Python` pane of `Python Environment Manager` extension, `Open in Terminal` button works well for venvs, but the global non venv's `Open in Terminal` button will launch the terminal with the environment of current interpeter which was selected through `F1`->`Python: Select Interpreter` and displayed at right side of VSCode status bar.

See the screenshots:
![x1](https://user-images.githubusercontent.com/3367034/219827895-f16a3e3f-da5d-488e-9317-482355d6dee1.png)
![x2](https://user-images.githubusercontent.com/3367034/219827912-1f7947e5-12da-4f8f-bdc6-5f372ef672d4.png)
![xg](https://user-images.githubusercontent.com/3367034/219827917-1558ccb0-e3f0-44be-997d-db6048db2b17.png)
![x11](https://user-images.githubusercontent.com/3367034/219827924-50f2ce38-3dd0-4550-9aa7-e5e9041903a6.png)
![x22](https://user-images.githubusercontent.com/3367034/219827930-eb2744ef-b9be-482d-b0da-e3fe4f49ae8b.png)

**Comment by qaqz111** [comment] 2023-02-18 12:46
Unfortunately by correcting the commandline string VSCode generated did not fix the problem according to my tests.
I modified the local js file of VSCode installation on VM to generate correct commandline string, which was confirmed through ProcessMonitor, but with Windows PowerShell v5.1 the error `8009001d` is still there.

So, is there any way to make VSCode terminal work fine with Windows PowerShell v5.1? Will there be a bugfix?

I'm really not sure whether installing pwsh7 will break the current development environment on some of our machines.

**Comment by karthiknadig** [comment] 2023-02-23 00:34
This looks like the https://marketplace.visualstudio.com/items?itemName=donjayamanne.python-environment-manager extension. 
/cc @DonJayamanne

**Comment by DonJayamanne** [comment] 2023-05-09 20:40
Closing this issue in favour of the extension bug https://github.com/DonJayamanne/vscode-python-manager/issues/54

**Closed by DonJayamanne** 2023-05-09 20:40 UTC
Labels: extensions
