### ISSUE TITLE
Windows: changes to node_modules folder are ignored due to watcherExclude setting

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#23954] opened 2017-04-05 19:46 UTC
`node_modules` directory persists in Explorer side bar after being deleted by `Remove-Item` PowerShell cmdlet in integrated terminal.

- VSCode Version: 1.10.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Clone any node project with external node_modules dependencies
2. Execute `npm install`
3. Execute `Remove-Item node_modules`
4. Confirm prompt about recursive deletion

Expected:
`node_modules` is not shown in Explorer side bar.

Actual:
`node_modules` is shown in Explorer side bar.

**Comment by bpasero** [comment] 2017-04-06 05:18
This is due to the files.watcherExclude setting ignoring changes to the node_modules folder simply because it can contain so many file changes that we decided to ignore changes there for performance reasons. Closing as designed for now until we found a better way of dealing with the amount of file events from large folders.

**Comment by bpasero** [comment] 2017-04-06 05:45
Actually there is a difference between Windows and macOS/Linux: we ignore `**/node_modules/**` but that should actually not ignore changes to the `node_modules` folder itself. The real issue here is that our glob library is matching `node_modules` for a pattern of `**/node_modules/**` when it should not.

**Closed** 2017-05-05 11:48 UTC
Labels: bug, explorer-files

**Comment by bpasero** [comment] 2017-05-06 07:33
**Verification:**
* on windows open a folder with a `package.json`
* run `npm install` and verify the `node_modules` folder shows up in the explorer
