### ISSUE TITLE
Extension telemetry doesn't get reported from the CLI

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#47180] opened 2018-04-04 07:33 UTC
The `extensionGallery:install` and related events don't seem to be reported when installing extensions from the CLI.

After a quick code review, they seem to be emitted from the ExtensionsWorkbenchService. Should we move them to the ExtensionManagementService instead?

cc @seanmcbreen

**Comment by sandy081** [comment] 2018-04-04 09:41
Yes, we report extension install/update/uninstall telemetry from workbench. I think it makes sense to move to shared process.

**Comment by sandy081** [comment] 2018-04-05 08:55
I see telemetry events for installation/uninstallation on the workbench side is overloaded with too much of irrelevant data like extension recommendations. So, It is not straight to move the telemetry reporting from workbench to shared process without introducing new events. 

@ramya-rao-a 
I would suggest to introduce a new event called `extension.install.fromRecommendations` or something like that for recommendations data. Not sure if you want to report for update/uninstall.

What do you think?

**Comment by sandy081** [comment] 2018-04-13 15:57
@ramya-rao-a Assigning you too to handle recommendations telemetry. We should remove install telemetry from workbench and do only recommendation telemetry.

> I would suggest to introduce a new event called `extension.install.fromRecommendations` or something like that for recommendations data. Not sure if you want to report for update/uninstall.
I think you can also include the gallery query related telemetry data in this event.

**Comment by sandy081** [comment] 2018-04-17 09:38
Let me know if it is ok to remove the recommendations telemetry from extension workbench service. **Note:** Currently we have two times installation events.

**Comment by sandy081** [comment] 2018-04-20 09:41
@ramya-rao-a I removed telemetry reporting for install/update/uninstall in extension workbench service and retained telemetry for recommendations using new event `extensionGallery:install:recommendations`. Feel free to remove it if you no longer need it. Thanks

**Comment by ramya-rao-a** [comment] 2018-04-20 20:38
Thanks @sandy081 
That works for me

**Comment by ramya-rao-a** [comment] 2018-04-27 18:52
@sandy081 I dont see the event reaching the telemetry when installing extension via the cli. I am using `code-insiders --install-extension` . Tried both vsix and by providing the extension name

**Comment by chrmarti** [comment] 2018-04-30 15:04
@sandy081 Since you are out I'm moving this to the May milestone after consulting with @ramya-rao-a.

**Comment by sandy081** [comment] 2018-05-02 09:48
@ramya-rao-a Curious to know how you checked if the event has reached telemetry or not?

**Comment by sandy081** [comment] 2018-05-24 11:58
@ramya-rao-a I can confirm that ExtensionsManagementService is reporting telemetry when an extension is installed from command line

![image](https://user-images.githubusercontent.com/10746682/40483971-3b9f18b4-5f5a-11e8-8828-0aa3a34788f7.png)

Can you please let me know how to check if it reached kustos or not... I see that the kustos explorer link is not working me. Please let me know if it has changed.

**Comment by ramya-rao-a** [comment] 2018-05-30 22:22
@sandy081 I ran `Developer: Toggle Shared Process` and added a breakpoint in the [app insights appender](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/telemetry/node/appInsightsAppender.ts#L135).

Then ran `code --install-extension ms-vscode.Go` in an external terminal. The breakpoint was not hit.

**Comment by sandy081** [comment] 2018-05-31 06:26
CLI runs in a separate node process... but it reuses the same extension management code which runs in shared process. Check https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/cliProcessMain.ts#L93

You can debug the Cli process by attaching the debugger. Since it gets finished quickly may be you need to place timeout.

**Comment by sandy081** [comment] 2018-06-05 08:16
@ramya-rao-a Moving it to June as it is not important to fix now.

**Closed** 2018-06-11 15:15 UTC
Labels: bug, extensions, verification-found

**Comment by joaomoreno** [comment] 2018-06-28 13:32
@ramya-rao-a Any easy way to verify this?
