### ISSUE TITLE
Default termminal in Debian not working

### ISSUE THREAD

**Issue by arpit-absyadav** [microsoft/vscode#132713] opened 2021-09-09 03:36 UTC
Issue Type: <b>Bug</b>

I have followed the all the instruction to change the default terminal to bash in debian buster. Same configuration working in code-insider. 

` "terminal.integrated.defaultProfile.linux": "bash",
  "terminal.integrated.profiles.linux": {
    "bash": {
      "path": "/usr/bin/bash",
      "args": []
    }
  }` 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 4.19.0-17-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 3433)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.52GB (0.36GB free)|
|Process Argv|--unity-launch --crash-reporter-id db1ac497-be83-4213-a93d-d0832cef1c79|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (87)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.3
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
sonarqube-status|adi|0.2.0
Bookmarks|ale|13.2.1
expressjs|ama|2.0.0
All-Autocomplete|Ati|0.0.23
markdown-emoji|bie|0.2.1
markdown-mermaid|bie|1.12.1
vscode-tailwindcss|bra|0.6.14
sqlformatter|bre|0.0.7
node-snippets|chr|1.3.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
es6-javascript-snippets|Cja|0.6.1
aws-cloudformation-yaml|Dan|0.2.2
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
vscode-markdownlint|Dav|0.43.2
py-pack|dav|1.2.0
vscode-eslint|dba|2.1.23
python-preview|don|0.0.4
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
brackethighlighter|Dur|2.2.4
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
docker-explorer|for|0.1.7
json2ts|Gre|0.0.6
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
format-python-docstrings|ian|1.2.1
python-coding-conventions|igr|0.0.4
vscode-react-typescript|inf|1.3.1
mysql-syntax|jak|1.3.1
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.5.0
js--snippet-good|jim|1.6.0
JavaScriptSnippetsStandard|jms|1.8.0
node-module-intellisense|lei|1.5.0
vscode-python-test-adapter|lit|0.7.0
ts-barrelr|mik|1.6.0
dotenv|mik|1.0.1
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.10.0
prettify-json|moh|0.0.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
remote-containers|ms-|0.194.0
cpptools|ms-|1.6.0
test-adapter-converter|ms-|0.1.2
vscode-typescript-next|ms-|4.5.20210908
ng-fortytwo-vscode-extension|NG-|0.0.9
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.10.0
vscode-css-peek|pra|4.2.0
py-snippets|py-|0.0.1
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
vs-code-prettier-eslint|rve|3.0.4
esdoc-mdn|sam|0.11.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
sonarlint-vscode|Son|2.1.2
flowmaker|spe|1.2.0
es6-mocha-snippets|spo|0.2.2
autoimport|ste|1.5.4
code-spell-checker|str|2.0.4
sass-indented|syl|1.8.18
tabnine-vscode|Tab|3.4.26
snippet-creator|vin|1.1.0
vscodeintellicode|Vis|1.2.14
save-and-run|wk-|0.0.22
bracket-lens|wra|1.5.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224:30358039
vssid140:30363603

```

</details>

**Comment by ILunie** [comment] 2021-09-09 04:35
I got the same issue in windows. I reinstalled the application, delete AppData/Roaming and still the issue persists.

```json
    "terminal.integrated.profiles.windows": {
      "GitBash": {
        "path": [
          "C:\\Program Files\\Git\\bin\\bash.exe"
        ],
        "args": []
      },
    },
    "terminal.integrated.defaultProfile.windows": "GitBash",
```

**Comment by albertosantini** [comment] 2021-09-09 06:23
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery release.

**Comment by A-song-of-Ice-and-Fire** [comment] 2021-09-09 09:05
我在window10系统的vscode的1.60版本中遇到了同样的问题：打开vscode时，默认的终端无法打开，里面没有任何内容，但使用”新建终端“选项却可以创建一个正常的powershell终端，我的配置文件如下：
```
  "terminal.integrated.profiles.windows": {
      "PowerShell": {
          "source": "PowerShell",
          "icon": "terminal-powershell"
      },
      "Command Prompt": {
          "path": [
              "${env:windir}\\Sysnative\\cmd.exe",
              "${env:windir}\\System32\\cmd.exe"
          ],
          "args": [],
          "icon": "terminal-cmd"
      },
      "Git Bash": {
          "source": "Git Bash"
      },
      "Windows PowerShell": {
          "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
          "args": []
      }
  },
  "terminal.integrated.defaultProfile.windows": "Windows PowerShell"
```

**Comment by A-song-of-Ice-and-Fire** [comment] 2021-09-09 09:08
I encountered the same problem in vscode version 1.60 of windows 10 system: when opening vscode, the default terminal cannot be opened and there is nothing in it, but using the "new terminal" option can create a normal PowerShell terminal. My configuration file is as follows:
```
  "terminal.integrated.profiles.windows": {
      "PowerShell": {
          "source": "PowerShell",
          "icon": "terminal-powershell"
      },
      "Command Prompt": {
          "path": [
              "${env:windir}\\Sysnative\\cmd.exe",
              "${env:windir}\\System32\\cmd.exe"
          ],
          "args": [],
          "icon": "terminal-cmd"
      },
      "Git Bash": {
          "source": "Git Bash"
      },
      "Windows PowerShell": {
          "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
          "args": []
      }
  },
  "terminal.integrated.defaultProfile.windows": "Windows PowerShell"
```

**Comment by IllusionMH** [comment] 2021-09-09 09:21
VS Code 1.60 doesn't have fix yet, Insiders build has https://code.visualstudio.com/insiders/

**Closed** 2021-09-09 17:20 UTC
