### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。always

### ISSUE THREAD

**Issue by yalishanyi** [Microsoft/vscode#32294] opened 2017-08-11 08:27 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.扩展主机意外终止。请重新加载窗口以恢复。always
2.

**Comment by weinand** [comment] 2017-08-11 08:50
duplicate of https://github.com/Microsoft/vscode/issues/32248

**Comment by weinand** [comment] 2017-08-11 08:52
What did you do when this happened?

**Comment by yalishanyi** [comment] 2017-08-11 09:09
下载安装之后，安装c#扩展之后弹出这个警告，然后点"重新加载窗口也没用"，删除软件再重装也没用，每次都会弹出来，sorry,my english is poor

警告是：
扩展主机意外终止。请重新加载窗口以恢复。

**Comment by weinand** [comment] 2017-08-11 09:27
@yalishanyi even if your English is poor, it would be great if you could help us by using a translation tool. Since my Chinese is poor as well, I'll have to use the translation tool:
 
Translation:
Download and install, after the installation of c # expansion pop-up after the warning, and then "reload the window is useless", remove the software and then reload is useless, each time will pop up
The warning is:
The extended host terminated unexpectedly. Please reload the window to restore.

**Comment by weinand** [comment] 2017-08-11 09:28
Since this seems to be related to C# I'm moving this issue.

**Comment by weinand** [comment] 2017-08-11 09:28
This issue was moved to OmniSharp/omnisharp-vscode#1702

**Closed by weinand** 2017-08-11 09:28 UTC
Labels: freeze-slow-crash, needs more info, new release

**Comment by yalishanyi** [comment] 2017-08-11 09:34
@weinand It is no use unloading c #. What are the methods I can try   solving this problem
