### ISSUE TITLE
The global search capture the Delete key

### ISSUE THREAD

**Issue by alexalannunes** [microsoft/vscode#77788] opened 2019-07-22 23:19 UTC
Issue Type: <b>Bug</b>

When I select a file or folder on panel left and press the DEL key,
the word 'delete' appears in the global search

Follow the screenshot!

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3048)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.17GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.0
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-typescript-tslint-plugin|ms-|1.2.2
inline-html|pus|0.2.5
RocketseatReactJS|roc|2.2.0
RocketseatReactNative|roc|2.2.0
markdown-preview-enhanced|shd|0.4.3
vscode-spotify|shy|3.1.0
vscode-icons|vsc|8.8.0
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

</details>

![screen](https://user-images.githubusercontent.com/16847836/61671431-00481b00-acbe-11e9-8de4-3e868bc782a3.png)

**Comment by usernamehw** [comment] 2019-07-23 07:34
/duplicate of #76514

You need to update to the latest version **1.36.1**

**Closed** 2019-07-23 07:35 UTC
Labels: *duplicate, integrated-terminal
