### ISSUE TITLE
No IntelliSense for TS/JS files

### ISSUE THREAD

**Issue by otbe** [Microsoft/vscode#5161] opened 2016-04-11 10:53 UTC
Hi *,

I try to replace webstorm with vscode as my main development editor/IDE, but as of now its not possible for me. Im not sure if this is a bug or misconfiguration of my system but IntelliSense, "Go to definition" and other useful stuff don't work for JavaScript or TypeScript files. On the other hand "context-aware" JSONs like `tsconfig.json`, `package.json` do work like expected.

This is my test repo: https://github.com/otbe/vscode-intellisense-test

And this happens on my (and only on my) machine:
![no-intellisense](https://cloud.githubusercontent.com/assets/3391052/14424337/d419dbc8-ffe0-11e5-9539-b8cd4f0b3828.gif)

I have made no changes to the default settings of vscode.

Grateful for every hint :/
Thanks.

Versions:
- VSCode Version: 0.10.14-insider | 0.10.11
- OS Version: OS X 10.11.3

**Comment by sgal** [comment] 2016-04-11 11:54
Try to add **files** section in your tsconfig.json, like this example
`
// tsconfig.json
{
  compilerOptions: {...},
  files: ['./src/index.ts']
}
`

Not sure that will help, but that's the first thing that I would do.

**Comment by otbe** [comment] 2016-04-11 12:05
Tried already to add ```files``` or ```exclude``` to my ```tsconfig.json```, but this did not work for me. The test repo works as expected on my colleagues mac.

**Comment by dijiadu** [comment] 2016-04-12 12:25
I'm having a similar problem, but I do get a warning message: 

> The Typescript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report.

**Comment by egamma** [comment] 2016-04-12 13:59
I get Intellisense
![image](https://cloud.githubusercontent.com/assets/172399/14462342/e331461e-00c6-11e6-9c84-8eab89984840.png)

And Peek Definition works as well
![image](https://cloud.githubusercontent.com/assets/172399/14462384/14255710-00c7-11e6-8617-d1f72f4c8bef.png)

In your code you write `let s = Person()`, this should be flagged as an error
![image](https://cloud.githubusercontent.com/assets/172399/14462414/3f9b2eb0-00c7-11e6-9c45-e4fec6ece0f7.png)

What version are you using (bit this has already worked in ancient versions). What I see in the screen shot is that the tsconfig.json isn't saved. Can you try to save and to execute the command `Reload TypeScript` project.

**Comment by otbe** [comment] 2016-04-12 14:31
Hi @egamma 

your screenshots shows how it works on my colleagues mac. Im using the latest stable version and insiders (0.10.15-insider | 0.10.11). ```tsconfig.json``` was not saved only during screen recording :). A fresh clone of this repo did not work either.

Is it possible to activate verbose logging in vscode/tsc? Maybe vscode isn't communicating with the TS compiler API properly!?

**Comment by egamma** [comment] 2016-04-13 10:30
The fact that you do not get squiggles indicates that the tsserver has crashed and isn't running, assigning to @dbaeumer.

**Comment by otbe** [comment] 2016-04-13 13:13
But this misbahvior does not apply only to typescript.

![bildschirmfoto 2016-04-13 um 15 10 40](https://cloud.githubusercontent.com/assets/3391052/14494223/00979e6a-018a-11e6-8fef-69dc320e893c.png)

Same example works fine in my windows vm or on other Macs

**Comment by dbaeumer** [comment] 2016-04-13 19:43
@otbe when the tsserver crashes we show a Message Box in the UI that informs you about this. Did you saw such a message box.

The error shown in the last comment is indeed related to editing JS files. 
@jrieken: can you please look at this and may be create a separate issue.

**Comment by dbaeumer** [comment] 2016-04-13 19:51
I tried to reproduce this on the insider 0.10.15 without any luck. And the project is more than trivial. So I doubt that this is a tsserver issue at all. @otbe can you think of any difference between the Macs with the different behaviour. Are you using nvm ?

**Comment by otbe** [comment] 2016-04-13 20:11
@dbaeumer 
Saw no such message box ever, but typescript has never worked for me in vscode. :)

But how I said, this problem is not related only to typescript. Simple JS files (see screenshot) did not work either.

Both macs using nvm (node 4 & 5). 

Whats unique to my mac:
- brew is installed
- docker & docker related tools are installed

What I tried so far:
- installed typescript globally
- different node versions
- different vscode versions (insiders and stable)
- different user accounts (also newly created ones)

Did I miss something @donaldpipowitch?

**Comment by donaldpipowitch** [comment] 2016-04-14 05:36
I also use brew and nvm (but no docker tools). @otbe and I share a lot of projects and tools. We can't spot the difference in our setup. vscode works great for me.

**Comment by jrieken** [comment] 2016-04-14 06:30
@dbaeumer The error message is triggered by the status info call but it hint towards us not yet have done a single `openFile` request. That's the reason why the call fails. Now I wonder why that it...

@otbe At the bottom of the editor it says JavaScript, TypeScript respectively?

**Comment by otbe** [comment] 2016-04-14 06:57
@jrieken 
Yes it recognizes JS/TS properly.

**Comment by jrieken** [comment] 2016-04-14 07:00
Anything special about the file paths? Like ümlauts, network-share, sym links etc?

**Comment by dbaeumer** [comment] 2016-04-14 08:21
@otbe Just for clarification: the tsserver powers both TS and JS. That is why both don't work in your setup.

**Comment by dbaeumer** [comment] 2016-04-14 08:31
@otbe can you please try the following: 

- set the global environment variable TSS_TRACE to 1 (in a shell)
- start VSCode from that shell
- in VSCode open the Developer Tools by pressing F1 and typing developer tools. Select Developer: Toggle Developer Tools
- open a TS file

You should see something like this in the console:

![capture](https://cloud.githubusercontent.com/assets/1931590/14521901/185837d8-022c-11e6-91cf-a239a3f70b68.png)

**Comment by dbaeumer** [comment] 2016-04-14 08:32
@jrieken can you help with the env and starting from a shell on the Mac please.

**Comment by jrieken** [comment] 2016-04-14 08:46
On the mac that would be `export TSS_TRACE=1 && code`

**Comment by otbe** [comment] 2016-04-14 09:36
My output looks different (yeeah)

![bildschirmfoto 2016-04-14 um 11 34 51](https://cloud.githubusercontent.com/assets/3391052/14523636/05907396-0235-11e6-82b1-e5d7f3dbf2a6.png)

**Comment by jrieken** [comment] 2016-04-14 14:00
Can you check your `tsconfig.json`-file for errors or warning and comments? Maybe tsserver fails to process that and therefore responds with _No Project_ errors

**Comment by donaldpipowitch** [comment] 2016-04-14 14:03
@otbe and I use the same repositories without any changes. It can't be really a project-specific reason. It must be his global setup somehow :(

**Comment by otbe** [comment] 2016-04-14 14:13
@jrieken 
@donaldpipowitch and @egamma used the same ```tsconfig.json``` without problems.

Is it possible to "debug" tsserver.js? Tried to place some ```console.log```s inside ```getProjectForFile()``` but it crashes with ```unexpected end of input``` ...

**Comment by otbe** [comment] 2016-04-15 12:10
Maybe this is related to my problem, but I use a case-sensitive filesystem on my mac!?

**Comment by jrieken** [comment] 2016-04-15 13:28
yeah, that might be something... How do you start vscode? just clicking the icon or via the `code`-command shell from terminal and iff so do you pass on the file to open? In that case we might infer the wrong casing, meaning file path.

Another case would be special characters in path names, we know that on mac characters sometime differ in how they are encoded. Anything non-ascii in your paths?

**Comment by otbe** [comment] 2016-04-15 14:27
I just click the icon and open my project folder via ```File -> Open```.
Project path is: ```/Users/boo/vscode-intellisense-test```, tried also ```/tmp/vscode-intellisense-test```

**Comment by dbaeumer** [comment] 2016-04-15 14:41
@otbe: from the error message however it is clear that the file we are opening in the tsserver doesn't match the file name when asking for code complete. That is why the server response with no project info.

You can debug the tsserver by setting the env variable TSS_DEBUG to a port number. For example TSS_DEBUG=5859. Then you can attached a debugger like node inspector to the running server. I will think about what could cause this on Mac. I also will test you workspace on Linux which is case sensitive as well.

**Comment by otbe** [comment] 2016-04-15 14:51
```fileName``` and ```path```differs and ```defaultProject``` is undefined...

<img width="1213" alt="bildschirmfoto 2016-04-15 um 16 50 37" src="https://cloud.githubusercontent.com/assets/3391052/14565201/3b8febe8-032a-11e6-88e1-33ca40bdc059.png">

**Comment by jrieken** [comment] 2016-04-16 10:53
They should really not do that

**Comment by otbe** [comment] 2016-04-16 10:56
If I change ```useCaseSensitiveFileNames``` to true, IntelliSense starts working for me *happy*

**Comment by jrieken** [comment] 2016-04-16 10:58
Glad that works. We'll have to follow up with the TypeScript team. The filenames they cache shouldn't be normalised. Or they should apply the same rules then to the file paths we send them

**Comment by otbe** [comment] 2016-04-16 10:59
Indeed 👍

**Comment by dbaeumer** [comment] 2016-04-18 08:58
@otbe thanks a lot to track this down. Testing it on Linux would not have helped :-). I opened https://github.com/Microsoft/TypeScript/issues/8139 to get that fixed.

**Comment by jakepearson** [comment] 2016-04-20 17:11
@otbe While I wait for a proper release, how do I set `useCaseSensitiveFileNames`? Thanks!

**Comment by otbe** [comment] 2016-04-20 17:57
@jakepearson 
Instead of hacking the source of vscode/typescript you can use a nightly build of typescript (e.g. ```1.9.0-dev.20160420```) and set ```typescript.tsdk``` in your user settings of vscode.

I utilize my project version of typescript for that:
```
"typescript.tsdk": "./node_modules/typescript/lib"
```

**Comment by jakepearson** [comment] 2016-04-20 19:31
@otbe That worked. Thanks a bunch.

**Comment by arve0** [comment] 2016-05-04 19:59
Or globally:

```sh
npm i -g typescript@next
```

```json
"typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"
```

**Comment by dbaeumer** [comment] 2016-11-15 19:51
This got fixed by the TS team a long time ago.

**Closed by dbaeumer** 2016-11-15 19:51 UTC
Labels: bug, typescript, upstream
