### ISSUE TITLE
Extension contributed commands (non-codicons) seem to be missing

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#116168] opened 2021-02-09 07:07 UTC
In this screenshot there are 2 missing icons -- 1 from the GHPR extension and 1 from GitLens

![image](https://user-images.githubusercontent.com/641685/107327508-3b19cb80-6a7b-11eb-8c88-337fd2cf687f.png)

@joaomoreno I don't know if this has to do with your menu changes to SCM or not.

Maybe related (since it showed up at the same time), non-codicons in custom views are misaligned.

![image](https://user-images.githubusercontent.com/641685/107327666-7a481c80-6a7b-11eb-8c49-e05434af026f.png)

**Comment by gjsjohnmurray** [comment] 2021-02-09 11:26
@eamodio is this 1.54 Insiders or 1.53 Stable?

**Comment by jrieken** [comment] 2021-02-09 11:44
@sandy081 is this a dupe of the issue you had mentioned today?

**Comment by eamodio** [comment] 2021-02-09 14:27
1.54-insiders (1.53 works fine)

**Comment by sandy081** [comment] 2021-02-09 14:45
@jrieken I guess not because it seems it is icon missing not the complete action. Anyway the new insiders have the fix (I mentioned in standup today), @eamodio Please check if it is fixed in latest?

**Comment by eamodio** [comment] 2021-02-09 16:47
@sandy081 still broken in today's insiders.

**Comment by sandy081** [comment] 2021-02-09 17:52
Is the icon or action missing - I mean are you able to click and the action executes?

**Comment by eamodio** [comment] 2021-02-09 18:31
In the SCM view, the action is there and works, just the icons are missing. While in the custom trees, the actions/icon is there, but the icons are misaligned

**Comment by eamodio** [comment] 2021-02-09 19:43
@joaomoreno I did a git bisect and 02fddad16d9f147bbc3aaf97dbb6a0291fc68144 caused this. Still looking more into it.

**Closed** 2021-02-09 22:15 UTC
Labels: bug, scm
