### ISSUE TITLE
incorrect command line help shown for uninstall-extension

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#6292] opened 2016-05-11 18:37 UTC
- VSCode Version:1.1.0-alpha
- OS Version:Windows 10

Steps to Reproduce:

1. Run code-alpha --help

Shown as "list-extensions", should be "uninstall-extension"

```
 --list-extensions     List the installed extensions.
  --install-extension <extension>
                        Installs an extension.
  --list-extensions <extension>
                        Uninstalls an extension.
```

See https://github.com/Microsoft/vscode/commit/b455db9f356a9e395aefa44d9b3f5597c67b7aa0#diff-e255a28340d4f20061d11494e99bd60b

**Comment by isidorn** [comment] 2016-05-11 21:00
Duplicate of #6266

**Closed** 2016-05-11 21:01 UTC
