### ISSUE TITLE
Newlines break SQL detection in PHP syntax highlighting

### ISSUE THREAD

**Issue by Virakal** [microsoft/vscode#234892] opened 2024-11-29 10:48 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Windows 10

Steps to Reproduce:

Create PHP file with the following contents:

```php

<?php

$q1 = "   SELECT * FROM table";

$q2 = "
    SELECT *
    FROM table
";
```

Note that $q1 gets correctly syntax-highlighted as SQL despite leading whitespace, but $q2 (much cleaner layout for larger queries imo) is treated as a regular string.

**Comment by RedCMD** [comment] 2024-11-29 19:37
maybe `|#\\s*(?i)SQL` could get added to `sql-string-double-quoted` and `sql-string-single-quoted`

![Image](https://github.com/user-attachments/assets/94f8285b-f33f-4055-84d4-e2a256a829b0)

![Image](https://github.com/user-attachments/assets/0b0922b0-ebee-422e-a7ab-b6f661da59a9)

https://github.com/KapitanOczywisty/language-php

**Comment by alexr00** [comment] 2024-12-19 14:23
Duplicate of upstream issue: https://github.com/KapitanOczywisty/language-php/issues/18

**Closed by alexr00** 2024-12-19 14:23 UTC
Labels: feature-request, grammar
