### ISSUE TITLE
High CPU usage, and intellisense not working

### ISSUE THREAD

**Issue by Ncsabak** [Microsoft/vscode#72251] opened 2019-04-13 08:03 UTC
Hello, I updated my visual code to 1.33.1, and now I have high cpu usage ~30% (8th generation i5) and intellisense is not working after some minutes, when I start the program.

**Comment by Ncsabak** [comment] 2019-04-13 08:07
As I see extension host is responsible for high cpu usage. Is it an extension problem, or visual code?

**Comment by Nahov91** [comment] 2019-04-13 13:24
I had the same issue. In most cases it is caused by some extension. First try to launch it without extensions (extensions menu > ... > disable all installed extensions.
If the problem is gone try reenabling extensions one by one to see which one causes the high cpu usage.
If the high cpu usage still exists then it can be an issue with typescript package cacheing. In that case you have to delete the typescript folder on your computer. For me that was what solved the issue.

**Comment by alexieyizhe** [comment] 2019-04-14 01:35
Same issue with all extensions disabled - fix from #72002 didn't help. Downgraded to 1.23 and not having problems anymore.

**Comment by berkaey** [comment] 2019-04-15 07:01
Same here after 1.32 vscode got very very slow and has high cpu usage.

**Comment by mjbvz** [comment] 2019-04-15 18:07
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

**Comment by mjbvz** [comment] 2019-05-04 03:25
Closing as more information is needed from original poster

**Closed by mjbvz** 2019-05-04 03:25 UTC
Labels: javascript
