### ISSUE TITLE
VSCode uses high CPU usage without reason/at idle

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#147188] opened 2022-04-10 22:52 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.1
- OS Version: macOS 12.3.1 (21E258)

Steps to Reproduce:

1. Load 4-5 projects into VSCode with JS contents (React & Node.js) or better TypeScript project
2. Start work as usually
3. Look at Monitor activity

Maybe related issues:
- https://github.com/microsoft/vscode/issues/147151

Issue with more info:
- https://github.com/microsoft/vscode/issues/147211

I am started notice after seeing high temperatures on my Macbook Pro M1 (which max is 30C) but seen up-to 42C at idle.
About memory i am agree (2GB per project + 2GB GPU Process) but high CPU is exceeds over-using resource use of my machine (battery too)

<img width="1011" alt="Screenshot 2022-04-11 at 03 47 42" src="https://user-images.githubusercontent.com/3511344/162643281-19fcc23f-4a9d-4571-9965-99c75a99ea75.png">

<img width="1011" alt="Screenshot 2022-04-11 at 03 47 07" src="https://user-images.githubusercontent.com/3511344/162643284-86c090a9-6c34-4cd3-8396-c028db6f6947.png">

**Comment by lorand-horvath** [comment] 2022-04-11 06:55
Yes, Electron has been updated from version 13 to 17.2 in VSCode 1.66 and since then the software has become very slow, sluggish, laggy https://github.com/microsoft/vscode/issues/146737#issuecomment-1092500999

**Comment by dalisoft** [comment] 2022-04-11 08:46
Seems v1.65, v1.64 exists same issue just did not noticed, currently look to Onivim v2 until VSCode could fix this

**Comment by mjbvz** [comment] 2022-04-11 18:32
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by dalisoft** [comment] 2022-04-12 10:36
@mjbvz Hooray, Code Insiders build a lot of better and works muuuch smoother stable. Thank you.

About `code-insiders --status` [here](https://github.com/microsoft/vscode/issues/147211#issue-1199715298) information for stable as i cannot expose datas related to work projects but try more steps as possible as i can

**Comment by lorand-horvath** [comment] 2022-04-12 13:03
@dalisoft Can you tell us what Electron version you have in Code Insiders?

**Comment by dalisoft** [comment] 2022-04-12 13:07
@lorand-horvath Here report

```
Version: 1.67.0-insider
Commit: fcaeb69ec8e96057423f7dadd52e116e29b80cae
Date: 2022-04-12T05:33:21.986Z (7 hrs ago)
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0
```

Anyway a lot of **Electron** processes exists but not eating a lot of CPU like before, 5-8x lesser CPU usage and 2 times more battery life than stable

**Comment by lorand-horvath** [comment] 2022-04-12 13:14
Thanks, Electron 17.2 in VSCode 1.66 was pretty bad...

**Comment by bpasero** [comment] 2022-04-12 15:40
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by bpasero** [comment] 2022-04-12 15:41
Oh, its fixed in insiders, perfect 👍

**Closed by bpasero** 2022-04-12 15:41 UTC

**Comment by dalisoft** [comment] 2022-04-13 06:52
Could be better if you can release new update on stable as hot fix for Electron update

**Comment by lorand-horvath** [comment] 2022-04-13 07:03
Won't happen, we'll have to wait until April 1.67 is released. Until then I'm staying on 1.65.2 (Electron 13), it's good enough for me.

**Comment by bpasero** [comment] 2022-04-13 10:32
You can safely use VSCode insiders. The VSCode team uses insiders for working on VSCode since day 1.
