### ISSUE TITLE
Got `Handler already set!` error when trying to undo in the editor

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#126339] opened 2021-06-15 06:23 UTC
I just got the follow error when trying to undo -- and it keeps happening every time I try to undo. Had to restart vscode to fix it.

![image](https://user-images.githubusercontent.com/641685/122002811-38f4b000-cd80-11eb-8787-d7610a58dc06.png)

This is what I see in the console:
![image](https://user-images.githubusercontent.com/641685/122002772-2c705780-cd80-11eb-8c66-3c5be7d6a6b9.png)

```
ERR Handler already set!: Error: Handler already set!
    at o.setHandler (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1674:15623)
    at d.registerListeners (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:39804)
    at new d (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:39602)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at new Y (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314:27281)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3551
    at P._executor (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18543)
    at P.get value [as value] (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18736)
    at Object.get (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3652)
    at Tn.get isMultiSessionView [as isMultiSessionView] (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2322:3179)
    at new Tn (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314:66465)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at P.createView (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2558:35572)
    at P.onDidAddViewDescriptors (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2558:36996)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2558:32913
    at o.fire (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at h.triggerOnDidAddVisibleViewDescriptors (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2325:9908)
    at h.onDidChangeContext (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2325:14055)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2325:6764
    at o.fire (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:59092
    at v.fire (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at v.fire (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:2784)
    at r.setContext (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:634:120752)
    at n.set (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:634:119041)
    at new d (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:39757)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at new Y (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314:27281)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3551
    at P._executor (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18543)
    at P.get value [as value] (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18736)
    at Object.get (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3652)
    at D.registerListeners (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314:50275)
    at new D (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314:50190)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at b.safeCreateInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1715:6069)
    at b.doInstantiateByPhase (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1715:5856)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1715:5698
contributions.ts:123
Unable to instantiate workbench contribution D. Error: Handler already set!
    at o.setHandler (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1674)
    at d.registerListeners (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1676)
    at new d (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1676)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at p.createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at new Y (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625
    at P._executor (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68)
    at P.get value [as value] (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68)
    at Object.get (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at Tn.get isMultiSessionView [as isMultiSessionView] (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2322)
    at new Tn (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at p.createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at P.createView (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2558)
    at P.onDidAddViewDescriptors (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2558)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2558
    at o.fire (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60)
    at h.triggerOnDidAddVisibleViewDescriptors (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2325)
    at h.onDidChangeContext (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2325)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2325
    at o.fire (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58
    at v.fire (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60)
    at v.fire (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60)
    at r.setContext (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:634)
    at n.set (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:634)
    at new d (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1676)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at p.createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at new Y (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625
    at P._executor (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68)
    at P.get value [as value] (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68)
    at Object.get (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at D.registerListeners (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314)
    at new D (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2314)
    at p._createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at p.createInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625)
    at b.safeCreateInstance (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1715)
    at b.doInstantiateByPhase (vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1715)
    at vscode-file://vscode-app/c:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1715
safeCreateInstance @ contributions.ts:123
```

**Comment by AngusWG** [comment] 2021-06-15 08:13
restart vscode  for me as emergency plan.

**Comment by alexdima** [comment] 2021-06-15 22:09
I have seen this before in https://github.com/microsoft/vscode/issues/120132#issuecomment-818720698 . But we never managed to figure it out.

@isidorn The exception comes from [`debugAdapterManager.ts`](https://github.com/microsoft/vscode/blob/2267488a387a7cb24ecc181e1e631b1a6ce708ad/src/vs/workbench/contrib/debug/browser/debugAdapterManager.ts#L67) and it happens if someone calls `extensionPoint.setHandler` twice.

I have speculated before that it might be a weird instantiation order where the ctor would somehow be invoked twice (cc @jrieken ) or that it might be a weird code cache issue (cc @bpasero ). But @isidorn I will give this to you, maybe you can add some assertions on your side that this method is not called twice and capture the call stacks if it is called twice, I don't know.

**Comment by bpasero** [comment] 2021-06-16 06:46
Any steps to reproduce? Looking at the code it is not obvious to me how the `debugAdapterManager` could ever be instantiated twice.

**Comment by avenmore** [comment] 2021-06-16 19:53
I started getting this message with v1.57.0 when trying to run a Vue project. Long story short: I usually have my DEBUG CONSOLE window docked inside to the right of my TERMINAL (powershell), and upon opening VSCode it wouldn't be visible and I'd get this message after building successfully and trying to launch. The work-around is to close VSCode, navigate to folder `%USERPROFILE%\AppData\Roaming\Code\User\workspaceStorage` and delete the contents (notably state.vscdb) and then restart VSCode. The DEBUG CONSOLE then shows itself again and all is fine unless I dock it again and close VSCode and there is a good chance of it happening again next time VSCode is opened. I have stopped docking the window inside the terminal and it hasn't happened since.

**Comment by bpasero** [comment] 2021-06-17 06:22
If this happens in 1.57.0 then it is definitely not a code caching issue because that was only enabled in 1.58.x.

**Comment by aeschli** [comment] 2021-06-18 05:42
https://github.com/microsoft/vscode/blob/0cbec1ee916fcb99235f2acd874033010c56dd4b/src/vs/workbench/contrib/debug/common/debugViewModel.ts#L36

all `bindTo`'s are in the contextKeyService.bufferChangeEvents event handler, that looks like a bug.

**Comment by aeschli** [comment] 2021-06-18 09:22
I can reproduce with the steps from https://github.com/microsoft/vscode/issues/126339#issuecomment-862669116
I think the problem is that DebugService constructor triggers a second instanciation of a debug service:
```
DebugService (debugService.ts:109)
_createInstance (instantiationService.ts:110)
(anonymous) (instantiationService.ts:236)
IdleValue._executor (async.ts:856)
get value (async.ts:873)
get (instantiationService.ts:242)
get isMultiSessionView (repl.ts:496)
Repl (repl.ts:138)
_createInstance (instantiationService.ts:110)
createInstance (instantiationService.ts:76)
createView (viewPaneContainer.ts:677)
onDidAddViewDescriptors (viewPaneContainer.ts:764)
(anonymous) (viewPaneContainer.ts:531)
fire (event.ts:634)
triggerOnDidAddVisibleViewDescriptors (viewContainerModel.ts:447)
onDidChangeContext (viewContainerModel.ts:634)
(anonymous) (viewContainerModel.ts:329)
fire (event.ts:634)
(anonymous) (event.ts:75)
fire (event.ts:634)
fire (event.ts:697)
setContext (contextKeyService.ts:326)
set (contextKeyService.ts:200)
AdapterManager (debugAdapterManager.ts:63)
_createInstance (instantiationService.ts:110)
createInstance (instantiationService.ts:76)
DebugService (debugService.ts:109)
_createInstance (instantiationService.ts:110)
```

**Comment by alexdima** [comment] 2021-06-18 12:14
> DebugService constructor triggers a second instanciation of a debug service

cc @jrieken

**Comment by manishbhalshankar** [comment] 2021-06-18 13:54
> I started getting this message with v1.57.0 when trying to run a Vue project. Long story short: I usually have my DEBUG CONSOLE window docked inside to the right of my TERMINAL (powershell), and upon opening VSCode it wouldn't be visible and I'd get this message after building successfully and trying to launch. The work-around is to close VSCode, navigate to folder `%USERPROFILE%\AppData\Roaming\Code\User\workspaceStorage` and delete the contents (notably state.vscdb) and then restart VSCode. The DEBUG CONSOLE then shows itself again and all is fine unless I dock it again and close VSCode and there is a good chance of it happening again next time VSCode is opened. I have stopped docking the window inside the terminal and it hasn't happened since.

Yes, this is the case with me as well. I had arranged Problems, Output, Terminal, and Debug Console and build output all in one tab in split view. After setting this, if the workspace is reloaded, the issue occurs. After resetting the view, the issue gets resolved.

**Comment by frankorama** [comment] 2021-06-20 11:36
I just uninstalled the "prettier" extension and the problem has gone away for me

**Comment by filighbuster** [comment] 2021-06-20 18:55
Closing and reopening vscode, worked for me

**Comment by tjx666** [comment] 2021-06-23 06:13
Same here, https://github.com/microsoft/vscode/issues/126796#issuecomment-864908952

**Comment by dhp252** [comment] 2021-06-23 13:04
I just disabled an extension named Data Preview (id `randomfractalsinc.vscode-data-preview`) and got this error (again). After re-enable or uninstall the extension, the problem disappear.
I tried with some others extensions and everything are still fine, no issue.
I guess there are some conflicts between new vscode version and some extensions.

My vscode version info
```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-55-generic
```

**Comment by isidorn** [comment] 2021-06-24 12:32
@aeschli thanks for the stack trace, was super helpful 👏

**Closed** 2021-06-24 12:32 UTC
Labels: bug, debug

**Comment by dyspop** [comment] 2021-06-29 09:08
I had this happen by moving/renaming a folder on the host

i fixed it by doing this on Mac OS 10.15.5:
https://stackoverflow.com/a/53839847/5969222

1. Close VS Code
2. `rm -rf $HOME/Library/Application\ Support/Code`
3. rm -rf $HOME/.vscode
4. Remove VSCode from application
5. Reinstall VS Code
6. Reinstall Microsoft Remote Development extension package (0.21.0 at time of writing)

**Comment by kabkee** [comment] 2021-07-01 01:53
> restart vscode for me as emergency plan.

Saved my life.

**Comment by h4b00** [comment] 2021-07-01 06:15
@isidorn when can we expect that fix in vscode (not the insider version) ?

**Comment by isidorn** [comment] 2021-07-01 06:26
Next release. Next week.

**Comment by connor4312** [comment] 2021-07-01 18:58
Marking verified since I managed to start hitting this in OSS and no longer do so

**Comment by levent-kantaroglu** [comment] 2021-07-08 05:12
I temporarily turn it false to able to init debug.
`"security.workspace.trust.enabled": false`

**Comment by ceelsoin** [comment] 2021-07-08 13:56
on mac: i uninstalled my vscode from applications folder, re-download and install it. worked for me!

note: didn't get deleted my vscode prefs
