### ISSUE TITLE
Video not working in PR webview

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#201167] opened 2023-12-18 22:17 UTC
Does this issue occur when all extensions are disabled?: Yes/No

<img width="2032" alt="image" src="https://github.com/microsoft/vscode/assets/876920/629dc6ec-5b8f-4e31-ba69-95c979a6f8fd">

**Comment by alexr00** [comment] 2023-12-19 08:36
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4761

**Closed by alexr00** 2023-12-19 08:36 UTC
