### ISSUE TITLE
CamelCase navigation bug

### ISSUE THREAD

**Issue by strayiker** [Microsoft/vscode#54177] opened 2018-07-12 13:59 UTC
Issue Type: <b>Bug</b>

Navigation through an UPPER_CASE constants does not works correctly.
Expected behaviour: navigating by words separated by underscore.
Current behaviour: navigating by symbol at once.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 6.1.7601

**Comment by andrewarchi** [comment] 2018-07-12 22:21
Looks like a dupe of #53645.

**Closed** 2018-07-27 15:09 UTC
Labels: *duplicate, editor, editor-subword
