### ISSUE TITLE
Graphical glitches at the menu and side bars.

### ISSUE THREAD

**Issue by Damian434** [microsoft/vscode#106337] opened 2020-09-09 10:25 UTC
- VSCode Version: 1.48.2
- OS Version: Windows 10 Pro x64

First of all I've checked if these are not artifacts, I made a stress test for my GPU - there was nothing wrong with it. Is there anything else I can try?
![VSC err](https://user-images.githubusercontent.com/26167497/92586733-f523c600-f296-11ea-92ea-357fe5fafe69.png)

**Comment by IllusionMH** [comment] 2020-09-09 10:36
/duplicate of #93356

At this point workaround is either pass `--disable-gpu` on application start e.g. `code --disable-gpu`  or use steps in https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Closed** 2020-09-09 10:37 UTC
Labels: *duplicate
