### ISSUE TITLE
VSCode shouldn't resolve symlinks for ${workspaceRoot}

### ISSUE THREAD

**Issue by farcaller** [Microsoft/vscode#30682] opened 2017-07-14 08:37 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0

VSCode traverse symlinks when it opens the workspace which root directory is symlinked. That breaks tools that see files outside of the expected directory hierarchy; most easily reproduced with VSCode-go, that requires for source to live within $GOPATH for external tools to work.

Steps to Reproduce:

1. `mkdir fakeRoot realRoot`
2. `touch realRoot/main.go`
3. `ln -s $PWD/realRoot fakeRoot/myproject`
4. `code fakeRoot/myproject`

Expected results:

${workspaceRoot} points to `$PWD/fakeRoot/myproject`

Actual results:

${workspaceRoot} traverses the symlink and points to `$PWD/realRoot`

Workaround:

`code $PWD/fakeRoot` will see the `myproject` within as a directory, not a symlink, and then everything works as expected, but not the VSCode workspace is one level above where it should have been.

Reproduces without extensions: Yes

**Comment by farcaller** [comment] 2018-02-09 13:11
I've found a new workaround for this. If you convert your project to a workspace and will manually modify the workspace to point to your symlink instead of `.` **and** will add a trailing slash to the symlink, then the files will be opened from an expected (symlinked) location.

**Comment by bpasero** [comment] 2018-09-05 08:49
Duplicate of https://github.com/Microsoft/vscode/issues/18837

**Closed by bpasero** 2018-09-05 08:49 UTC
Labels: config, feature-request
