### ISSUE TITLE
Alt+Click on a toolbar button causes the Menu Bar to toggle on KeyUp

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#44396] opened 2018-02-26 08:39 UTC
Issue Type: Bug

1. Set the Menu Bar to be hidden
1. Alt+Click on one of the editor/title toolbar buttons (for example in GitLens if you Alt+Click on the Blame button it will show the recent changes rather than the blame)
1. :bug: Observe that when you let go of the `alt` key the menu bar will toggle back on

FYI, I have a PR ready to submit for this

VS Code version: Code - Insiders 1.21.0-insider (903169966590cd236c5016cdc774875215d31765, 2018-02-26T05:18:08.801Z)
OS version: Windows_NT x64 10.0.17107

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|31.93GB (17.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\Eric\code\microsoft\vscode|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by isidorn** [comment] 2018-02-26 12:02
@eamodio thanks for your PR, however let's first get the bug straigthend out.

1. Open explorer.
2. Hold alt key, trigger context menu -> notice there is "Delete Permanently"
3. Let go of the all key -> notice there is "Delete Permanently" still there. I just verified on windows.

Is this unexpected for you? Becuase it behaves just fine for me.
Or is the issue only visible for extensions?
Is step 1. really needed to repro? If yes how do you hide the Menu Bar

fyi @jrieken

**Comment by eamodio** [comment] 2018-02-26 17:10
@isidorn 
I can repro my issue on Windows/Linux - but the Menu Bar must be hidden (View -> Toggle Menu Bar).

Hold down `Alt` and click on any of these icons (granted only the GitLens one actually has an alternate command)
![image](https://user-images.githubusercontent.com/641685/36684210-a502cf96-1aed-11e8-809e-a53600749481.png)

When you let go of the `Alt` key it will cause the Menu Bar to be shown.

As for your issue, I can't even get a context menu to show up while holding down `Alt` -- well it shows for a second and disappears. And that doesn't matter if the menu bar is hidden or not.

**Comment by isidorn** [comment] 2018-02-27 16:10
This seems to be an issue with the alt key on windows and this feels like a duplicate of https://github.com/Microsoft/vscode/issues/44136

**Comment by eamodio** [comment] 2018-02-27 16:42
@isidorn the issue you mentioned, yes -- that is a duplicate of https://github.com/Microsoft/vscode/issues/44136, but the issue I mentioned is not. There is no issue with the `alt` key not working. It it just that *if* you hide the menu bar (on Windows/Linux) you can use the `alt` key alone to toggle it on and off. Which is perfectly fine and as-designed. But if you attempt to `alt+click` on an item in a "toolbar" (see the image in my previous post), the `alt` leaks through that click (the command works fine, mind you) so that not only does the command run, but the menu bar toggles (and it drives me NUTS 😄).

There was similar work done to stop this from happening when `alt`+clicking in the editor here:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/codeEditor/electron-browser/menuPreventer.ts

**Comment by isidorn** [comment] 2018-02-28 13:35
Ok thanks for more info. @jrieken fyi

**Closed** 2018-05-09 10:43 UTC
