### ISSUE TITLE
Markdown preview link lost when new file is saved

### ISSUE THREAD

**Issue by dwbruhn** [Microsoft/vscode#33424] opened 2017-08-29 16:32 UTC
- VSCode Version: 1.15.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Create a new, unsaved editor pane
2. Type some Markdown
3. Change language mode to Markdown
4. Click preview button to open the preview pane
5. Click back to the edit pane and save it as a file
6. Observe that the Markdown preview pane continues to show "Preview 'Untitled-1'" and will not reflect further edits to the file.

May be related to #12033

Screenshot:
![image](https://user-images.githubusercontent.com/8230981/29832384-e732df30-8c9c-11e7-9e69-bb031dc7fe57.png)

Reproduces without extensions: **Yes**

**Comment by mjbvz** [comment] 2017-08-29 17:19
Thanks. This looks like a duplicate of #12033

**Closed by mjbvz** 2017-08-29 17:19 UTC
Labels: duplicate, markdown, new release
