### ISSUE TITLE
VSCode & Task Output freezing, printing and sleeping

### ISSUE THREAD

**Issue by MrVallentin** [Microsoft/vscode#4449] opened 2016-03-19 06:11 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10

I encountered some odd behaviors in VSCode, when using tasks and the output window.
I'm currently doing some Python and has setup a task, for ease of execution using
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>.

---

The main issue is that VSCode opens the output window when the task starts (given that `"showOutput": "always"` is true), but output is first appearing when the task has ended.

The following text first appears in the output window 10 seconds after the task is started (i.e. when the task is done).

    from time import sleep
    
    for i in range(10):
        print(i)
        sleep(1) # seconds

---

What makes this further confusing it that the following never prints anything (as expected, due to the above).

    from time import sleep
    
    while True:
        print("Freeze")
        sleep(1) # seconds

But change the delay to 10 milliseconds and suddenly the output window is filled with "Freeze" every 4-10 seconds.

    from time import sleep
    
    while True:
        print("Freeze")
        sleep(0.01) # seconds

I changed the delay to 100 milliseconds instead of 10 milliseconds, and "Freeze" first appeared after 2-3 minutes in the output window.

---

Also removing the sleep command entirely, ends up in VSCode freezing completely.

Something interesting in this case, is that "Freeze" appears once. Then after 10-20 seconds, the output window is then again filled with "Freeze", while VSCode is still totally frozen. While the only solution being to kill VSCode with the task manager.

    while True:
        print("Freeze")

---

Also something that is worth mentioning. As (obviously) it's an output window, and not an input window. When the running task tries to read from the standard input (`raw_input()`/`input()` in Python) the task just stops.

As a feature request it would be nice to have an input/output window, instead of just an output window. If not, then just at least some prompt for closing the running task, instead of just having it frozen and hidden away in the background, not knowing what is happening.

**Comment by dbaeumer** [comment] 2016-03-21 08:43
@isidorn changed quite some code here for March milestone. Need to check if this behavior got better.

**Comment by egamma** [comment] 2016-03-21 09:20
@dbaeumer to verify that the improvements for March improve this.

**Comment by dbaeumer** [comment] 2016-03-21 10:47
I still see the freeze on latest. @isidorn, @bpasero  I though the output window throttles.

**Comment by dbaeumer** [comment] 2016-03-21 11:02
I profiled it and the time is still spent mostly in the Output Window (see attached screen shot, self time)

![capture](https://cloud.githubusercontent.com/assets/1931590/13916747/b2f9e562-ef5c-11e5-8000-6cf674d1d004.png)

**Comment by dbaeumer** [comment] 2016-03-21 11:15
In the sleep 1 seconds case the child process managed by node never receives any output data. I have no idea right now why this is the case.

**Comment by dbaeumer** [comment] 2016-03-21 11:21
There seems to be some buffering involved. In data comes in 8KB chunks. If only written every second then it takes a while until 8K are full.

**Comment by dbaeumer** [comment] 2016-03-21 11:26
If I do the same in node the text appears immediately. So it looks like the buffering happens somehow on the python side. The node code is:

```javascript
setInterval(function() {
    console.log('Freeze');
}, 1000);
```

**Comment by dbaeumer** [comment] 2016-03-21 11:26
Given the complexity of this I will investigate more for April.

**Comment by bpasero** [comment] 2016-03-21 12:28
@dbaeumer can you attach the CPU snapshot so that we can drill into the output editor input?

**Comment by dbaeumer** [comment] 2016-04-21 09:24
Reading through the Python docs it looks like that python buffers stdout & stderr when running as a child process. Calling python with the -u switch works as expected. 

![bug](https://cloud.githubusercontent.com/assets/1931590/14704147/99e966fa-07b3-11e6-86e8-4a0e99c2892c.gif)

**Comment by dbaeumer** [comment] 2016-04-21 09:26
Wasn't able to reproduce the freeze on latest alpha. Closing.

**Closed by dbaeumer** 2016-04-21 09:26 UTC
Labels: freeze-slow-crash, tasks
