### ISSUE TITLE
Different syntax highlighting for levels

### ISSUE THREAD

**Issue by stalkerg** [Microsoft/vscode#45934] opened 2018-03-16 02:12 UTC
Sorry but I am duplicate #31483 because you just closed that issue but for me this case very important.
Different colors on different levels very useful for JavaScript objects and JSON, that behavior supports by Sublime and Atom.
Also, in my opinion, it's not possible to implement an extension, for this behavior you should extend your color theme format to accept more than one color per semantic. 

Thank you. 

![json_colors_sublime](https://user-images.githubusercontent.com/1853716/37500538-5944cdec-290d-11e8-95e5-101eca538a92.png)
![json_colors_vscode](https://user-images.githubusercontent.com/1853716/37500541-5d1a2750-290d-11e8-8c15-ad7bc57e41f6.png)

**Comment by stalkerg** [comment] 2018-03-16 02:35
I think we should have a list of colors for each token and we can rotate these colors depend on a level like tokenColors[level % tokenColors.length]

**Comment by aeschli** [comment] 2018-03-16 07:56
It's not trivia, but this can be implemented as extension. You need to contribute a new JSON grammar that replaces the existing one.
Please add votes to #31483 if you want this to get some traction.

Closed as duplicate of #31483

**Closed by aeschli** 2018-03-16 07:56 UTC
Labels: javascript

**Comment by stalkerg** [comment] 2018-03-16 08:53
> It's not trivia, but this can be implemented as extension.

How? We can provide only one color per token now.

> You need to contribute a new JSON grammar that replaces the existing one.

For me more important JavaSript and TypeScript not JSON. 

> Please add votes to #31483 if you want this to get some traction.

In this case please rename those issue to more common task, JSON is not my main goal.

**Comment by stalkerg** [comment] 2018-03-16 08:54
Also! #31483  full banned issue, I cant vote or write messages.

**Comment by stalkerg** [comment] 2018-03-16 09:00
@aeschli in my opinion, it's two different cases and maybe only for JSON you can write some kind of extension but if you want to use this approach globally you should do something in core. 
It's very helpful for JS/TypeScript/Python.

**Comment by aeschli** [comment] 2018-03-16 09:10
I opened #31483 for comments (and votes) again.
Such a new grammar would have to generate different scopes per nesting level, so that themes can assign separate colors to it.

Maybe this doesn't even need a grammar change but could be done in the theme, using [Descendant Selectors](https://manual.macromates.com/en/scope_selectors)
