### ISSUE TITLE
Stop loop to next change at last change of file

### ISSUE THREAD

**Issue by jmetertea** [microsoft/vscode#120709] opened 2021-04-07 07:59 UTC
Don't loop to first change occurrence after reach last occurrence 
### Steps to reproduce
Go to Source Control (Ctrl+Shift+G)
Open changes of a file 
Click Next Change (Alt+F5)
### Results
When you reach the last occurrence, the Next Change command keep searching by jumping to the first occurrence at the top of the file. You're in a loop.

### Expectations
When last search occurrence is reached, most of text/code editor will prompt the user if he wants to keep searching the file from the first line. This is a feature I need and should be a toggle one.
Similar to editor stop loop
https://github.com/microsoft/vscode/issues/28666

My suggestion is to add property diffEditor.find.loop similar to editor.find.loop

**Comment by chennakeshava1998** [comment] 2021-04-13 08:01
Hello, I'm a new to the VSCode repository. I would like to help in implementing this feature. 
I'm assuming that we take the user's preference (as a boolean value) in `diffEditor.find.loop`. Is this the correct way to proceed? @eamodio  It would be very helpful if you could give me some pointers, I don't have much software engineering experience.
I made the following change at `src/vs/editor/browser/widget/diffReview.ts`. 
<img width="913" alt="image" src="https://user-images.githubusercontent.com/21219765/114516105-b43fc580-9c5a-11eb-861d-f760f86ff06f.png">

**Comment by coderpen-me** [comment] 2021-04-17 08:25
1. Go to settings, search for editor.find.loop.
2. Uncheck loop

Current behavior: If you have reached to the end of search, move next button will be disabled. 

Expected behavior: 

> If you have reached to the end, and you hit next button, a pop-up box must be shown that you have reached to end of search, do you want to start over. 

> If user clicks yes, loop flow will continue. If user clicks no, next button will be disabled. 

@joaomoreno @eamodio, If I got this right, can I work on this feature ?

**Comment by nicolasalarconrapela** [comment] 2021-05-07 09:40
_I am new to the project but I want to start this exciting project._

Can I jump into the challenge of solving the issue if there was no one assigned?  Thanks 😃

**Comment by bottercode** [comment] 2021-08-28 09:51
Hey! I would like to work on this one. Is it still open?

**Comment by ipotseluev** [comment] 2022-07-04 15:10
Seems like the issue is not fixed yet (VS Code v.1.68.1)
@ismailarilik as far as I see you implemented the solution and PR is closed, but the issue is still open. Maybe you know what's wrong? The solution not merged into main branch?

**Comment by lszomoru** [comment] 2023-01-09 11:12
Closing this as duplicate of https://github.com/microsoft/vscode/issues/163331.

**Closed by lszomoru** 2023-01-09 11:12 UTC
Labels: help wanted, feature-request, good first issue, scm
