### ISSUE TITLE
Changing language mode keeps previous linter and shows non-errors

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5205] opened 2016-04-12 23:02 UTC
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open an HTML file
2. Change language mode to Javascript
3. Change back to HTML

Actual:
Showing many errors as it still thinks it is in Javascript language mode.
![languagemodeswap](https://cloud.githubusercontent.com/assets/12900364/14478166/f4df4824-00c7-11e6-9767-cac15b71d644.JPG)

**Comment by egamma** [comment] 2016-04-13 10:51
Duplicate of #5193

**Closed by egamma** 2016-04-13 10:51 UTC
Labels: v-test
