### ISSUE TITLE
VS Code keeps getting unresponsive on Windows 10 vers. 2004

### ISSUE THREAD

**Issue by Tazaf** [microsoft/vscode#104689] opened 2020-08-14 21:22 UTC
Issue Type: <b>Performance Issue</b>

I upgraded today my Windows 10 **to vers. 2004 from vers. 1909** and since then, I'm experiencing issues with VS Code, which quite randomly **stops responding, yielding the OS popup "VS Code is not responding"**. I hit the "Wait for the program to respond", wait a few seconds, and VS Code responds again... or so I think since it goes back to being unresponsive a few seconds after. Rinse and repeat a random number of time and, finally, VS Code respond... Until the next unresponsive loop.

Here's some things I tried:

- It so happens that I also updated to the latest 1.48 version of VS Code at almost the same time, so I though at first that it was related to that update. But I uninstalled it and reinstalled the 1.47.3 (which was my previous working version), and, alas, the issue kept occuring.

- I work primarly on WSL using the WSL Remote Extension. I though that maybe it was related to that. But again, launching VS Code on Windows had the same effect.

- The issue arises on a more regular basis when I'm working on Java projects (with the Java Extension Pack enabled), especially when launching a debug session and stopping on breakpoints. Thus, I tried on a barebone VS Code by starting it with all extensions disabled (and opening an Angular project instead). It eventually became unresponsive, but I had to wait longer and do more random stuffs (open file, launch app, navigate in the menu, etc) for it to do so.

> The only thing I didn't try is reverting back to Windows 10 vers. 1909 using the native recovery utility, because quite frankly, I'm a little scared that it could fail and I'd have to reinstall from sratch.

I really can't provide a step-by-step reproduction procedure, since I'm not being able to trigger the issue with 100% certainty. Really sorry about that.

I also don't know if it's the right place to raise this issue, as it seems to be related to my updating of Windows, but the only program affected so far is VS Code. So, there's that.

Anyway... I'll happily provide you with any additionnal information you might request, as it's quite painful to develop with a regularly freezing VS Code, and I would like this issue sorted out as soom as possible.

(I can try and record my screen, if that would be helpful).

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.57GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   127	  4744	code main
    0	   102	  1588	   shared-process
    0	    69	  6536	   utility
    0	   284	 10884	   window (media f - Hubble - frontend - Visual Studio Code)
    0	     5	  3896	     "C:\Program Files\Git\bin\bash.exe"
    0	    10	 18500	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	   123	  5392	     extensionHost
    0	   214	 11640	       electron_node tsserver.js 
    0	    86	  9888	         electron_node typingsInstaller.js typesMap.js 
    0	    92	 20976	       electron_node tsserver.js 
    0	   108	 22456	       "C:\Users\obers\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\obers\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=5392
    0	     5	 14444	     "C:\Program Files\Git\bin\bash.exe" -c "npm run start"
    0	     8	 24548	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe" -c "npm run start"
    0	     8	  8892	         "C:\Program Files\Git\usr\bin\sh.exe"
    0	     6	   756	           "C:\Program Files\Git\usr\bin\sh.exe"
    0	    36	 23884	             "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs/node_modules/npm/bin/npm-cli.js" run start
    0	     5	  9248	               C:\WINDOWS\system32\cmd.exe /d /s /c ng serve --port 8015
    0	   732	 24112	                 "C:\Program Files\nodejs\\node.exe"   "C:\Program Files\nodejs\\node_modules\@angular\cli\bin\ng" serve --port 8015
    0	    63	 24308	                   "C:\Program Files\nodejs\node.exe" C:\square\media-f\dev\apps\hubble\frontend\node_modules\@ngtools\webpack\src\type_checker_worker.js 9d93e901-158a-4cf9-ba1b-2f0582ffcfeb
    0	     6	 19448	     console-window-host (Windows internal process)
    0	     6	 20308	     console-window-host (Windows internal process)
    0	    15	 24120	     watcherService 
    0	    11	  1852	       console-window-host (Windows internal process)
    0	    64	 19004	   electron-crash-reporter
    0	   343	 23560	   gpu-process
    0	    92	 24032	   window (Issue Reporter)
```

</details>
Extensions disabled

**Comment by bpasero** [comment] 2020-08-17 06:37
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Tazaf** [comment] 2020-08-17 09:00
Hi @bpasero 

Maybe that wasn't clear enough in my initial message, but I already tried launching VS Code without any extension (since I also wondered if it was caused by any one of them):

> - The issue arises on a more regular basis when I'm working on Java projects (with the Java Extension Pack enabled) [...]. **Thus, I tried on a barebone VS Code by starting it with all extensions disabled** [...]. It eventually became unresponsive, but I had to wait longer and do more random stuffs [...] for it to do so.

For the sake of thoroughness, I retried just now starting VS Code without extensions. I opened a Node project and moved through the code by Shift-clicking symbols. VS Code became unresponsive after some time, but only for like a second, after which it stayed stable until the end of my test.

I retried opening the same project normally (with all extensions), and witnessed the same behavior.

I have to admit, though, that the problem seems to be much more frequent and severe when working on Java projects with the Java Extension Pack.

So... the issue doesn't seem to be related to any extension, but is somewhat worse when they are activated.

**Comment by Tazaf** [comment] 2020-08-17 09:17
(Maybe my issue is related to #104358?)

**Comment by bpasero** [comment] 2020-08-17 10:13
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by cativo** [comment] 2020-08-18 09:21
@Tazaf I experienced the same after upgrading Windows 10 to 2004 version. I believe my issue #104358 is related to yours.

**Comment by Tazaf** [comment] 2020-08-19 09:02
> Can you follow this wiki and post the results back here [...]

I can, but I'm not entirely sure which results your's like me to report back.

> All the following results have been obtained launching VS Code on Windows with all extensions **disabled** and an Angular project opened

Anyway, I tried displaying the Process Explorer to see if any process was causing a spike in CPU usage. The problem is that the Process Explorer window itself become unresponsive when the issue arises. Not very helpful. I've also witnessed occurences when the Process Explorer window displays nothing at all:

![image](https://user-images.githubusercontent.com/7702322/90613756-19e1cc00-e20a-11ea-9c40-04d4fe9d29f9.png)

On the other hand, when displaying Windows Task Manager, there's a CPU usage spike on the Code.exe instance that does not respond:

![image](https://user-images.githubusercontent.com/7702322/90614135-8eb50600-e20a-11ea-8538-80516353fc56.png)

I also tried running `code --status` during a unresponsivness event. But this command hangs and does not produce any input until VS Code becomes responsive again. Since the result are printed when VS Code runs again normally, I'm not sure of their usefulness, but here they are anyway:

<details>
<summary><code>code --status</code> results</summary>

```
Version:          Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS Version:       Windows_NT x64 10.0.19041
CPUs:             Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)
Memory (System):  15.92GB (7.56GB free)
VM:               0%
Screen Reader:    yes
Process Argv:     --disable-extensions .
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        enabled
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0      132    5588  code main
    0      283   10172     window (media f - Mediashop - frontend - Visual Studio Code)
    0       73    9844       searchService
    0      120   10320       extensionHost
    0      500    6896         electron_node tsserver.js
    0       94   10824           electron_node typingsInstaller.js typesMap.js
    0       72   12932         "C:\Users\obers\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\obers\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=10320
    0       92   15332         electron_node tsserver.js
    0       83   18180         "C:\Users\obers\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\obers\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=10320
    0       94   18360         "C:\Users\obers\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\obers\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=10320
    0       15   15948       watcherService
    0       10   15940         console-window-host (Windows internal process)
    0       54   10632     electron-crash-reporter
    0       86   13052     window (Process Explorer)
    0       90   16200     shared-process
    0      172   16704     gpu-process
    0       38   16832     utility

Workspace Stats:
|  Window (media f - Mediashop - frontend - Visual Studio Code)
|    Folder (frontend): 638 files
|      File types: ts(191) scss(159) js(39) html(36) json(30) png(28) ttf(19)
|                  svg(13) eot(5) woff(5)
|      Conf files: tsconfig.json(2) launch.json(1) settings.json(1)
|                  tasks.json(1) package.json(1) tslint.json(1)
|      Launch Configs: chrome
```

</details>

Hope all of this is somewhat helpful 🤞

**Comment by bpasero** [comment] 2020-08-19 09:25
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Tazaf** [comment] 2020-08-19 10:25
> Can you try to reproduce with our nightly insider builds? [...]

@bpasero Yup, will do.

On a sidenote, I have to tell you that in my case, the unresponsivness _seems_ to happen more frequently when closing a file.

**Comment by bpasero** [comment] 2020-08-19 11:43
Thanks for trying.

**Comment by Tazaf** [comment] 2020-08-19 17:01
> Can you try to reproduce with our nightly insider builds?

Well... so far, so good!

I tried:
- Opening an Angular project, launching it, navigating through the code
- Installing extensions to work with Java
- Opened a heavy workspace with three Java projects and navigated through their respective code
- Launched the three projects at the same time
- Debugged with breakpoints

All of this without VS Code not responding. I experienced some slowliness at times, but that's probably due to the Java Server setting up or the app being compiled.

_(In parallel, I kept working with VS Code stable, which kept freezing regularly)_

I'll give it another day or two of tests, but apparently, Insiders doesn't yield the problem.

So @bpasero ... I suppose I should wait until 1.49 is released? Do you now what was changed in Insiders that fixed the problem?

**Comment by bpasero** [comment] 2020-08-20 05:45
OK closing thereby, you can use insiders for the time being, we keep it as stable as possible.

**Closed by bpasero** 2020-08-20 05:45 UTC
Labels: needs more info

**Comment by dannyjacosta** [comment] 2020-09-09 12:57
> code --disable-extensions

I tried this. Didn't make a difference

**Comment by Tazaf** [comment] 2020-09-09 21:19
@dannyjacosta Did you try with VS Code Insiders as mentionned previously?

Disabling the extensions did not fix the issue for me, but installing and working with VS Code Insiders (while waiting for 1.49 release) did it.
