### ISSUE TITLE
Visual studio code keep crashing on windows 10 after latest update to 1.16.0

### ISSUE THREAD

**Issue by HassanYousufi** [Microsoft/vscode#34139] opened 2017-09-11 11:23 UTC
- VSCode Version: 1.16.0
- OS Version: windows 10

Steps to Reproduce:

1. i am runing node apllication with mongese and angular 4, my vs code automatically crash after some time while i am running mongose and node with webpack in it. 
2. here is screen shoot of error.
![image](https://user-images.githubusercontent.com/23094645/30272291-444ee39c-970d-11e7-9ac2-e4a761f79589.png)

below is version detail of vs code 
![image](https://user-images.githubusercontent.com/23094645/30272324-78493cb0-970d-11e7-9c01-6fdad942f460.png)

Reproduces without extensions: Yes
I have disabled all extensions but still getting the same crashing issue.

**Comment by HassanYousufi** [comment] 2017-09-11 12:26
i have also installed vs code 1.17 having no extension, it is also crashing

**Comment by alexandrudima** [comment] 2017-09-12 07:51
@HassanYousufi Do you have a specific set of steps that you do before the crash occurs? I am presuming this is not caused by extensions (as you state above). What sort of things do you do before the crash occurs? Do you edit certain types of files, do you do certain operations that lead up to the crash? What sort of project are you working on ?

**Comment by HassanYousufi** [comment] 2017-09-12 08:41
As already said, I am building the app in MEAN Stack application, while I start code (node with web pack and Mongoose db) to run in the terminal of vs code,  it automatically crashes after a minute.  Now I have downgrade vs code to version 1.15.1. It working fine for me. I am nothing editing in code right now.

**Comment by alexandrudima** [comment] 2017-09-12 08:53
@HassanYousufi Do you:
* launch any processes in the integrated terminal ?
* launch any tasks in VS Code ?
* launch debugging ?
* type/edit

or do you simply open a folder and after 1 minute VS Code immediately crashes?

**Comment by tobeeze** [comment] 2017-09-12 15:57
I am also having the same issues with VS Code. Never experienced that till today, the problem started today when I uninstalled the 32bits version I was using previously without issues and installed the 64bit version. The crash started with the 64bit version. I uninstalled it and reinstalled the 32bit version I was using previously and its crashing also.

**Comment by alexandrudima** [comment] 2017-09-13 10:24
Adding @bpasero , maybe you have some ideas...

**Comment by bpasero** [comment] 2017-09-13 10:26
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by HassanYousufi** [comment] 2017-09-13 11:48
@alexandrudima I am running mongd and angular webpack in the integrated terminal of vs code.

**Comment by michal9909** [comment] 2017-09-13 14:44
I am having the same issue since the latest update. It would crash at random time, for example, it crashed for me when I generate a new component with Angular CLI.

**Comment by danielriosb** [comment] 2017-09-13 22:00
It is also crashing here everytime I run "nodemon" or "grunt". I am working with a MEAN Stack app.

**Comment by pozzito** [comment] 2017-09-14 12:48
Also happening on Windows 7 Enterprize x64 after latest update of Code to 1.16 (32bit) for the first time. For me the steps to reproduce (same crash windows) are while initiating build script in Integrated Terminal. My stack is npm (6.11.x) + grunt + angular 4 app.
The problems seams to occur while working in integrated cmd window and dont have anything with extensions.

**Comment by bpasero** [comment] 2017-09-14 12:56
@HassanYousufi @michal9909 @danielriosb @pozzito please fill out the [questionaire](https://github.com/Microsoft/vscode/issues/34139#issuecomment-329126150).

**Comment by crazyceelo** [comment] 2017-09-14 19:33
OMG its not just me. I am also having this issue. I am doing a MERN stack. Below are the steps.

Environment:
- surface book pro
- windows 10
- VS code 32. I also tried VS code 64 bit and same result.

1. Launch VS code and open my Master repository that is connected to GitHub.
2. Terminal 1, I run mongo with "Mongod"
3. Terminal 2, I run actual mongo with "Mongo"
4. Terminal 3, I run an express server with the command "Nodemon server.js"
5. Terminal 4, I run webpack with "webpack -w"
6. ---> VS code will crash and I will have to restart the entire process. Sometimes the crash occurs immediately after webpack is done building or it will crash anytime you change a file, save, and webpack auto-rebuilds. I have run without mongo in the background, and it crashes less, but it is still very inconvenient.

**Comment by bpasero** [comment] 2017-09-15 04:52
@crazyceelo does it reproduce if you are using an external terminal and not the integrated one? Does it reproduce if you configure `"files.useExperimentalFileWatcher": false` ?

**Comment by Tyriar** [comment] 2017-09-16 00:35
Might be a duplicate of https://github.com/Microsoft/vscode/issues/34301

**Comment by crazyceelo** [comment] 2017-09-16 07:15
@bpasero If I use an external terminal, the crash no longer occurs. I actually now prefer the external terminal window. Thanks a ton. I am now able to code without interruption. Once again, thanks a ton.

**Comment by pozzito** [comment] 2017-09-18 09:16
Happening again after update to Code x32 **1.16.1**, terminal is crashing the code again, on Win 7 SP1 Enterprize x64, while running any longer script but mostly on grunt build or grunt run. Our stack is npm (6.11.x) + grunt + angular 4 app.

**Comment by nishadmenezes** [comment] 2017-09-20 05:37
Facing the same issue after update. Angular 4 based MEAN stack application. Running mongod,  ng build and nodemon in 3 separate integrated terminals. Crashes quite often...

**Comment by looeee** [comment] 2017-09-21 07:25
I am also experiencing this, and updating to 1.16.1 has not fixed the issue. Also occurs when running terminals.

**Comment by aldo-sanchez** [comment] 2017-09-22 14:56
Same here.  Sometimes when I run Mongo in the integrated terminal VS Code will crash.  I updated VS Code at the beginning of September to the September update, then VS Code asked to update again, which it actually downgraded to the August 1.16 version. This is when I started noticing the crashes.  I'm running Windows 10.

**Comment by noce2** [comment] 2017-09-23 14:11
I have been experiencing the same issue while running ngRok along side a node server in the integrated terminal. I'm now using a separate powershell window to run ngRok and don't seem to be experiencing the issues anymore.

**Comment by tmzblue** [comment] 2017-09-25 13:33
I started seeing this error since VSCode 1.16.0.

**What OS/version are you using?**

- Windows 10
- VSCode 1.16.1

![image](https://user-images.githubusercontent.com/17063774/30809834-83b739cc-a1d9-11e7-98fe-dff2d3baeeb6.png)

**What were you doing when it happened?**

I'm developing an ASP.NET Core/angular 2 app. It usually occurs when I have **one or more** open terminals (powershell) with commands running - such as git/npm/dotnet

It's not consistent: I can work for hours without crashing, but It happens frequently during my work time (8hs aprox.).

**Comment by Tyriar** [comment] 2017-09-26 13:03
Duplicate #34301

**Closed by Tyriar** 2017-09-26 13:03 UTC
Labels: freeze-slow-crash, needs more info, new release

**Comment by delsumit** [comment] 2017-09-29 08:00
I am also getting same issue. Is this a version issue or OS compatibility issue for upgraded version

**Comment by Tyriar** [comment] 2017-09-29 09:22
@delsumit this should be fixed in Insiders, coming in v1.17

**Comment by pozzito** [comment] 2017-10-12 09:08
Its Working Now :+1:  !! 

Thank you @Tyriar and complete VS Code Team, this is now fixed in 1.17 and VS Code is working excellent on Win platform :)

We want just to help you so you can close all other bugs related to this, terminal is not crashing anymore, and is much faster.

Keep up the good work and thank you on this software (VS Studio meets Sublime)
