### ISSUE TITLE
Crash when attempting to open file/folder

### ISSUE THREAD

**Issue by Behrpack** [microsoft/vscode#109823] opened 2020-11-02 03:58 UTC
Issue Type: <b>Bug</b>

Select "File> Open Folder" or, "File> Open File"

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.8.15-301.fc33.x86_64 snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (4.36GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id f3db6986-a3a1-48d2-85da-30e15d48e210|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.0.0
python|ms-|2020.10.332292344
remote-containers|ms-|0.145.1
vim|vsc|1.17.1

</details>

**Comment by gjsjohnmurray** [comment] 2020-11-02 06:29
/needsMoreInfo does the problem also happen if you launch with all extensions disabled? What does the "crash" look like?

**Comment by Behrpack** [comment] 2020-11-02 20:59
The issue occurs with all regardless of extension state. I've attached a screen capture that will hopefully help.
[VScode_crash.zip](https://github.com/microsoft/vscode/files/5477991/VScode_crash.zip)

**Comment by isidorn** [comment] 2021-01-22 12:05
Closing as no other users complained and I could not reproduce

**Closed** 2021-01-22 12:05 UTC
Labels: needs more info
