### ISSUE TITLE
VSCode fails to search files (and cmd+p) inside folders stored in Google File Stream 

### ISSUE THREAD

**Issue by danielporto** [microsoft/vscode#74117] opened 2019-05-22 09:40 UTC
- VSCode Version: 1.34.0
- OS Version: highSierra and Mojave

Steps to Reproduce:

1. Store any project inside a Google File Stream volume
2. open that folder with vscode 
3. try to search for a file inside that folder using cmd+P (for the first time, i.e. without opening/close the file previously)

Does this issue occur when all extensions are disabled?: Yes

I also tried a few things but it didn't work:
- to make the folder available offline in Google File Stream
- open code --verbose to check for error messages but nothing different compared to a regular local folder shows up

Side notes (to rule out problems in Google File Steam):
I tried to open the directory with IntelliJ Idea and search works fine.
Surprisingly when I try to do the same test with Atom, the result is the same as that in vscode,
the search returns no result, despite the fact the there is a match. 
Could that be a problem of a library shared with Atom or Electron?

**Comment by roblourens** [comment] 2019-05-23 18:59
Atom and vscode both use ripgrep so it's possible that ripgrep won't search that drive for some reason. Do you know what Google File Stream does to actually mount that drive and what might be unusual about it?

It seems like Google File Stream is only available through work/school enterprise accounts? So I'm not sure if it's possible for me to test this?

**Comment by danielporto** [comment] 2019-05-24 09:38
Google file stream uses fuse.
here is the mount point description:
`drivefs on /Volumes/GoogleDrive (dfsfuse_DFS, local, nodev, nosuid, synchronous, mounted by dan)`
Internally I believe it caches a lot of stuff as needed, such that for the point of view of other regular applications they don't 'feel' like accessing a network drive.

I wonder if a flag on fuse leaks it out and it's somehow is detected by ripgrep or other culprit. 

And yes, only Academic or business account can use google file stream unfortunately. 
What tests can I do for you?

**Comment by roblourens** [comment] 2019-05-29 02:55
Other people have reported that fuse works but is extremely slow. Does text search return anything?

**Comment by jfloff** [comment] 2019-05-29 09:46
I've also experience some issues with Google File Stream so I can contribute to the discussion.

Text search does return some results, but only from files that you've previously opened, i.e., if you just opened a project without opening any files, your search will return nothing.

**Comment by roblourens** [comment] 2019-10-09 22:51
/duplicate of https://github.com/microsoft/vscode/issues/69333

**Closed by roblourens** 2019-10-09 22:51 UTC
Labels: needs more info, search
