### ISSUE TITLE
Error: Failed to move '*' to the recycle bin.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [microsoft/vscode#111111] opened 2020-11-22 03:00 UTC
- VSCode Version:
Version: 1.52.0-insider (user setup)
Commit: caf01baa45b9816e2e1d8a2de22b40cf89459c03
Date: 2020-11-20T07:41:44.570Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
- OS Version:
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎02-‎Jun-‎20
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0

Steps to Reproduce:

1. Create a file.
2. Try to delete the file/folder from the Explorer view.

Does this issue occur when all extensions are disabled?: Yes
![Screenshot (335)](https://user-images.githubusercontent.com/25576658/99892641-eeed9500-2c9c-11eb-8d4a-84759f70ddd1.png)

**Comment by gjsjohnmurray** [comment] 2020-11-22 04:59
As soon as you have dismissed that error message, I suggest you try to delete the same folder+file using Windows Explorer. What happens? Do they go to Recycle Bin? Or does Windows give you a failure message?

**Comment by ShubhamVerma1811** [comment] 2020-11-22 05:06
It gets deleted using Windows Explorer and I have turned off the option for deleted files to go to the bin but yeah it works.
Even the bash command (rm/rm -rf) works using vscode's built-in terminal.

**Comment by gjsjohnmurray** [comment] 2020-11-22 07:33
Thanks for the responses. I see that you are using Insiders. If you also have Stable installed (they coexist happily) please also test from there.

This information may be useful to the team member who picks up the issue. That might not happen until Monday.

**Comment by ShubhamVerma1811** [comment] 2020-11-22 07:38
Alright, I'll install the stable version and try on that and post the outcome here.

**Comment by isidorn** [comment] 2020-11-23 09:09
I tried this with VS Code insiders on Win and macOS and could not reproduce this.
Let's leave this open if more users hit this and you can let us know if you also see this in stable

fyi @bpasero for potential duplicates which I am unware of

**Comment by bpasero** [comment] 2020-11-23 09:54
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by ShubhamVerma1811** [comment] 2020-11-23 10:06
> 
> 
> Please see if you can find any logged output that could help us find the source of the issue:
> 
>     * run `code --verbose` from the command line and attach the output
> 
>     * in Code select **Help | Toggle Developer Tools** and select the **Console**
> 
>     * attach any output you see in the **Console** you can find
> 
> 
> Thanks!

I am not sure how to save logs but here is what I could get.

## Logs: [-1606125897070.log](https://github.com/microsoft/vscode/files/5582130/-1606125897070.log)

![Screenshot (341)](https://user-images.githubusercontent.com/25576658/99949765-90f6a580-2da1-11eb-87f2-b0bb13915bad.png)

**Comment by bpasero** [comment] 2020-11-23 10:09
Yeah unfortunately the error is very generic:

```
ERR Unknown (FileSystemError): Error: Failed to move 'demo.txt' to the recycle bin
    at Object.h [as createFileSystemProviderError] (file:///C:/Users/Shubham/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1741:87)
```

**Comment by ShubhamVerma1811** [comment] 2020-11-23 10:13
I think I found the issue right now.
So I have disabled the recycle bin for D: drive.
Which means deleted files are deleted forever. When bin is disabled this error comes on deleting files/folder.
When bin is enabled for D: drive everything works.

So should I modify the "Steps to reproduce" ?

**Comment by isidorn** [comment] 2020-11-23 10:22
I think this is expected behavior and thus we will close this issue as designed.

**Closed by isidorn** 2020-11-23 10:22 UTC
Labels: file-explorer, needs more info

**Comment by manuelcanepa** [comment] 2020-11-24 16:22
I have the same issue. I cant enable recycler bind because the drive where i work is not a windows drive. I have a drive connected through sshfs, i can delete files from windows explorer, but cant do on vscode (Insiders). I think is not "as-designed" because there is no way to delete files from files explorer on vscode.

## Visual Studio Code Insiders

### Normal delete

- Pressing delete over a file:
  ![image](https://user-images.githubusercontent.com/10290593/100120716-0b353180-2e57-11eb-852b-cadf530b4366.png)

- Press "Delete permanently": 
  ![image](https://user-images.githubusercontent.com/10290593/100120884-3ae43980-2e57-11eb-9549-cf7869421e02.png)

### Holding shift

- Hold shift + delete:
  ![image](https://user-images.githubusercontent.com/10290593/100120943-50596380-2e57-11eb-9291-b7f1093c019e.png)

- Press "Delete":
  ![image](https://user-images.githubusercontent.com/10290593/100120981-5a7b6200-2e57-11eb-8d2f-c45be4e3ecae.png)

## Visual Studio Code (Stable)

- Pressing delete over a file:
  ![image](https://user-images.githubusercontent.com/10290593/100121210-a0d0c100-2e57-11eb-8acb-12dc6bc5d8e3.png)

- Press "Move to recycler bin":
  ![image](https://user-images.githubusercontent.com/10290593/100121370-b5ad5480-2e57-11eb-9b72-6e5b3e3037fd.png)

- Press "Delete permanently" 
  Actually delete the file permanently
