### ISSUE TITLE
when editing c#, typing /* causes */ to be injected

### ISSUE THREAD

**Issue by negspect** [microsoft/vscode#43989] opened 2018-02-19 21:04 UTC
### Issue Type
Bug

### Description

in settings :

      "editor.autoClosingBrackets": false,

as this seems to be the only option related to turning auto complete dingleberries off.

however, when entering /* to comment out a block of code, an unwanted */ is injected which the user has to go back and delete.  it is far less effort to just type */ by oneself, but thanks for the thought.

for example:

        a = goodValue;
        /* */
        a += valueToCommentOut;
        */
        
gaaaah why did you do that?!

how can this obnoxious behaviour be disabled?

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1512)|
|Memory (System)|7.90GB (4.51GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.14.0
mono-debug|ms-|0.15.8
unity-debug|Uni|1.2.1

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment] 2019-04-29 14:22
Caused by https://github.com/Microsoft/vscode/blame/029a4e870a737336419a609421b757cf9534855c/extensions/csharp/language-configuration.json#L17

Since C# and JSON are the only ones auto-closing `/*` with `*/` (which is IMHO unexpected), let's forward to @aeschli to check why was this done.

**Closed** 2019-10-08 15:39 UTC
