### ISSUE TITLE
TextDocumentContentProvider sample extension broken

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#5709] opened 2016-04-24 04:07 UTC
In the latest alpha channel the TextDocumentProvider example extension is broken.
- extension: https://marketplace.visualstudio.com/items?itemName=eg2.vscode-css-properties
- source: https://github.com/Microsoft/vscode-extension-samples/tree/master/textdocumentprovider-sample

The method `provideTextDocumentContent` isn't called anymore.

The method is called when manually opening a document:
```ts
        vscode.workspace.openTextDocument(uri).then(doc => {
            let contents = doc.getText();
        }, reason => {
            console.log(reason);
        });
```

**Comment by egamma** [comment] 2016-04-24 04:19
Labeling as important since several extensions were derived from this sample and appear to be broken as well, e.g., https://marketplace.visualstudio.com/items?itemName=buzzfrog.imagepreview

**Comment by jrieken** [comment] 2016-04-25 07:43
I believe this is a dupe of #5736

**Closed** 2016-04-25 08:11 UTC
Labels: api, important
