### ISSUE TITLE
Active indent highlight is one indent behind

### ISSUE THREAD

**Issue by msaguindang** [Microsoft/vscode#54012] opened 2018-07-11 04:22 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10

Steps to Reproduce:

1. Click on an opening or closing bracket
2. View the indent guide

Does this issue occur when all extensions are disabled?: Yes

Screenshot:
![screenshot 17](https://user-images.githubusercontent.com/17432540/42550543-fa665706-8504-11e8-9664-170b19fc19fa.png)

**Comment by alexandrudima** [comment] 2018-07-27 07:09
Duplicate of #49342

**Closed by alexandrudima** 2018-07-27 07:09 UTC
Labels: editor
