### ISSUE TITLE
codeAction diagnostic is null when select a a problem form the problem views

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode#43878] opened 2018-02-17 08:04 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Install VSCode java extension from  https://marketplace.visualstudio.com/items?itemName=redhat.java
2. Unzip the simple projects below and open the App.java file
[simple-maven.zip](https://github.com/Microsoft/vscode/files/1733505/simple-maven.zip)

3. There are two problems in the problem view. 
4. Open the java trace in the user setting "    "java.trace.server": "verbose",
5. Click the first one, the code action of diagnostics fields is empty while the second one have the correct diagnostic values. 

Does this issue occur when all extensions are disabled?: Yes/No Not sure. I can repro this for java. But not sure any other extension provide this kind of code actions with diagnostics.

**Comment by yaohaizh** [comment] 2018-02-17 08:05
The first one: 
```json
[Trace - 4:05:01 PM] Sending request 'textDocument/codeAction - (15)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/Examples/simple-maven/src/main/java/com/simple/maven/App.java"
    },
    "range": {
        "start": {
            "line": 12,
            "character": 22
        },
        "end": {
            "line": 12,
            "character": 23
        }
    },
    "context": {
        "diagnostics": []
    }
}
```

**Comment by yaohaizh** [comment] 2018-02-17 08:06
The second one: 
```json
[Trace - 4:06:05 PM] Sending request 'textDocument/codeAction - (17)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/Examples/simple-maven/src/main/java/com/simple/maven/App.java"
    },
    "range": {
        "start": {
            "line": 18,
            "character": 8
        },
        "end": {
            "line": 18,
            "character": 15
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 18,
                        "character": 8
                    },
                    "end": {
                        "line": 18,
                        "character": 15
                    }
                },
                "message": "Unreachable code",
                "code": "536871073",
                "source": "Java"
            }
        ]
    }
}

```

**Comment by egamma** [comment] 2018-02-18 13:51
@aeschli can you please investigate whether this is an issue with the vscode language server integration support.

**Comment by aeschli** [comment] 2018-02-19 10:26
The problem is that the Java server reports the problem with non-matching coordinates:
```java
        while (false) {
```
```
"diagnostics": [
        {
            "range": {
                "start": {
                    "line": 12,
                    "character": 22
                },
                "end": {
                    "line": 12,
                    "character": 71
                }
            },
            "severity": 1,
            "code": "536871073",
            "source": "Java",
            "message": "Unreachable code"
        },
```
End should be `"character": 13`

The range is likely adjusted internally in VSCode when creating the marker. 
When evaluating the diagnostics, the matching fails as the code wants the marker range to [contain the diagnostic range](https://github.com/Microsoft/vscode/blob/9fda9a1bfd8959333ba2c6e38b090e3dbf48da66/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L286)

Assigning to @jrieken if we should also do something on our side.

@yaohaizh Can you fix the range on the Java side?

**Comment by jrieken** [comment] 2018-02-26 12:01
Yeah, we adjust the representation (the squiggle) but not the business object (marker/diagnostics)... I am not a fan of doing this because in most cases we don't have a document to perform adjustments with. Closing as designed

**Closed by jrieken** 2018-02-26 12:01 UTC
