### ISSUE TITLE
Extension host terminated unexpectedly 3 times within the last 5 minutes.

### ISSUE THREAD

**Issue by ljshwyykl** [microsoft/vscode#177061] opened 2023-03-14 09:38 UTC
Type: <b>Bug</b>

Extension host terminated unexpectedly 3 times within the last 5 minutes.

VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin arm64 21.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|. --crash-reporter-id 2fe9aade-87c9-4008-b034-f424f34425da|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
tailwindcss-extension-pack|and|1.1.4
tailwind-docs|aus|2.0.0
toml|be5|0.6.0
search-crates-io|bel|1.2.1
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.8
better-toml|bun|0.3.2
move-syntax|dam|0.4.8
vsc-gsql-extension|Dav|0.0.2
githistory|don|0.6.20
vscode-wasm|dts|1.4.0
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
shell-format|fox|7.2.5
copilot|Git|1.77.9225
go|gol|0.38.0
vscode-graphql|Gra|0.8.6
vscode-graphql-execution|Gra|0.1.8
vscode-graphql-syntax|Gra|1.1.0
terraform|has|2.25.4
vscode-test-explorer|hbe|2.21.1
headwind|hey|1.7.0
rest-client|hum|0.25.1
vue|jcb|0.1.5
plantuml|jeb|2.17.5
solidity|Jua|0.0.149
tailwind-sass-syntax|mac|1.3.0
vscode-dbml|mat|0.3.5
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
move-analyzer|mov|0.0.10
vscode-docker|ms-|1.24.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
cpptools|ms-|1.14.4
test-adapter-converter|ms-|0.1.6
sqltools|mtx|0.27.1
vscode-gn|npc|1.1.0
vetur|oct|0.37.3
prisma|Pri|4.11.0
vscode-xml|red|0.24.0
rust-analyzer|rus|0.3.1435
scala|sca|0.5.6
metals|sca|1.22.0
crates|ser|0.5.10
starcoin-ide|sta|0.7.9
code-spell-checker|str|2.19.0
tabnine-vscode|Tab|3.6.42
graphviz-interactive-preview|tin|0.3.5
solidity-visual-auditor|tin|0.1.5
vscode-ethover|tin|0.0.7
vscode-inline-bookmarks|tin|0.1.0
vscode-solidity-flattener|tin|0.0.11
vscode-solidity-language|tin|0.0.7
tldraw-vscode|tld|1.28.2
vscode-lldb|vad|1.9.0
snippet|vsc|0.9.2
chatgpt-china|Whe|5.0.6
vscode-js-console-utils|wht|0.7.0
fig|wit|0.0.7
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.5.0
project-tree|zhu|0.3.0
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30677850
funwalk2cf:30682975
pythonms35cf:30680985

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:11
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:11 UTC
Labels: freeze-slow-crash-leak, extension-host
