### ISSUE TITLE
Synchronize changes not showing animations while pulling changes

### ISSUE THREAD

**Issue by tonny008** [Microsoft/vscode#24167] opened 2017-04-07 03:34 UTC
- VSCode Version: 1.11.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. click Synchronize changes icon
2. the icon not showing  animations like old versions while pulling changes.

**Comment by jsynowiec** [comment] 2017-04-07 05:55
Duplicate of #23975

**Closed** 2017-04-07 06:01 UTC
