### ISSUE TITLE
Terminal: cannot launch code.sh from integrated terminal

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7451] opened 2016-06-09 05:48 UTC
<img width="715" alt="screen shot 2016-06-09 at 07 48 24" src="https://cloud.githubusercontent.com/assets/900690/15919964/8ec93690-2e16-11e6-9047-5236ec0fdd11.png">

Maybe an issue with the cwd?

**Comment by bpasero** [comment] 2016-06-09 05:48
code-cli.sh works btw 👍

**Comment by Tyriar** [comment] 2016-06-09 05:59
I have noticed something strange with cwd before, I has some repository open and did `code .` and it opened another folder, unrelated to both the active instance of `code` and `.`. Doing `cd .` also did nothing.

**Comment by Tyriar** [comment] 2016-07-05 18:50
This should work now, closing as duplicate of https://github.com/Microsoft/vscode/issues/8141

**Closed by Tyriar** 2016-07-05 18:50 UTC
Labels: bug, integrated-terminal
