### ISSUE TITLE
Feature request: Search results appear on tabs

### ISSUE THREAD

**Issue by brunofin** [Microsoft/vscode#63349] opened 2018-11-17 08:21 UTC
Simple idea, whenever we search for anything using the search panel (Shift+Ctrl+F), the search results appear in a new tab **within that panel**.

This would allow us to keep search results and search of another term. This would allow for example to after a later search, come back to the results of a previous one without needing to remember the search term and wait for the search to be performed and lose the current results as well.

I am attaching a simple mockup to better illustrate the idea:

![vscode-search-on-new-tab](https://user-images.githubusercontent.com/8077237/48658910-c85f4880-ea49-11e8-903b-029408d9255c.png)

**Comment by usernamehw** [comment] 2018-11-17 09:39
Duplicate of #16488 ?

**Comment by roblourens** [comment] 2018-11-17 19:59
Dupe of #16488, but thanks for the mockup!

**Closed** 2018-11-17 19:59 UTC
Labels: *duplicate, search

**Comment by brunofin** [comment] 2018-11-19 09:37
No problem. I added the mockup in the comments of #16488 as well
