### ISSUE TITLE
Cannot go back parent folder after clicking the "turn back" button

### ISSUE THREAD

**Issue by sugky7302** [microsoft/vscode#211597] opened 2024-04-29 02:53 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: Windows WSL / Mac

Steps to Reproduce:

1. Click "Open Folder"
![image](https://github.com/microsoft/vscode/assets/37475968/b5148b09-4daf-482e-9a7f-f4ecc310e40a)
![image](https://github.com/microsoft/vscode/assets/37475968/94233a3d-a4e3-49df-99e2-5d79ca1ae4f6)

2. Click ".." first. It's ok.
![image](https://github.com/microsoft/vscode/assets/37475968/076dd1fd-91fc-4dca-8b83-d300f99511f4)

3. Click ".." again. It's no response.

https://github.com/microsoft/vscode/assets/37475968/3778a479-d20a-4ed9-b269-a92d99548c19

**Comment by alexr00** [comment] 2024-04-29 16:22
Duplicate of https://github.com/microsoft/vscode/issues/209848

**Closed by alexr00** 2024-04-29 16:22 UTC
Labels: bug, simple-file-dialog
