### ISSUE TITLE
Cannot select multiple files in explorer pane

### ISSUE THREAD

**Issue by o-lim** [Microsoft/vscode#26494] opened 2017-05-11 22:27 UTC
- VSCode Version: 1.12.x
- OS Version: Linux

It would be nice if we could select multiple files at a time in the explorer pane.  This comes in handy when you want to delete several files or if you want to copy/move several files.

**Comment by cateyes99** [comment] 2017-05-11 22:59
duplicate of #1023

**Closed** 2017-05-12 00:33 UTC
Labels: duplicate
