### ISSUE TITLE
How do you get rid of line breakpoint dots?

### ISSUE THREAD

**Issue by lopugit** [microsoft/vscode#83627] opened 2019-10-30 05:14 UTC
Whenever I add a breakpoint by clicking left of the line number, a breakpoint circle is also added at a seemingly random spot within the line?? like in the middle of a word or something??

Such as seen here: https://github.com/Microsoft/vscode/issues/21164

How do you make the breakpoint only show next to the line number and not anywhere in the file??

**Comment by gjsjohnmurray** [comment] 2019-10-30 11:11
/duplicate of #83018 which asks for an option to turn these off

**Closed** 2019-10-30 11:11 UTC
Labels: *duplicate
