### ISSUE TITLE
Terminal: Dragging a directory into the terminal no longer copies 

### ISSUE THREAD

**Issue by RobertCharron** [microsoft/vscode#128675] opened 2021-07-14 16:25 UTC
Issue Type: **Bug**

Steps to recreate: 
- Create a new Project
- Add multiple folders to the project
- Open a terminal
- Drag the folder into the terminal

Expected output: The directory will populate in the terminal
Actual output: None

OS: Windows_NT x64 (Windows 10) Build 19041.1083 Feature Experience Pack 120.2212.3530.0

VS Code Version: 
- 1.58.1 (user setup)
- Commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
- Date: 2021-07-13T06:58:28.115Z
- Electron: 12.0.13
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0

OS: Windows_NT x64 10.0.19041
Run as admin: Yes
Restricted Mode: No

<details><summary>Extensions Active:</summary>
<p>
766b.go-outliner
aaron-bond.better-comments
bmewburn.vscode-intelephense-client
christian-kohler.npm-intellisense  
claudiosanches.woocommerce
CoenraadS.bracket-pair-colorizer   
dracula-theme.theme-dracula        
eamodio.gitlens
Equinusocio.vsc-community-material-theme
esbenp.prettier-vscode
felixfbecker.php-debug
felixfbecker.php-intellisense
formulahendry.code-runner
golang.go
hbenl.vscode-test-explorer
hridoy.wordpress
ikappas.phpcs
jeremyljackson.vs-docblock
johnbillion.vscode-wordpress-hooks
mblode.twig-language
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-wsl
ms-vscode.test-adapter-converter
ms-vsliveshare.vsliveshare
mtxr.sqltools
neilbrayfield.php-docblocker
octref.vetur
phproberto.vscode-php-getters-setters
premparihar.gotestexplorer
recca0120.vscode-phpunit
tht13.python
VisualStudioExptTeam.vscodeintellicode
windmilleng.vscode-go-autotest
wordpresstoolbox.wordpress-toolbox
wwm.better-align
zhuangtongfa.material-theme
</p>
</details>

**Comment by RobertCharron** [comment] 2021-07-14 16:29
For the record as well, we have tested this on multiple systems of the same OS/VS Version. This worked before the 1.58.1.

**Comment by jeanp413** [comment] 2021-07-14 21:55
This is a duplicate of #128283 and also created a PR #128419 fixing it

**Closed** 2021-07-15 15:48 UTC
