### ISSUE TITLE
Typescript schemas missing?

### ISSUE THREAD

**Issue by kedruff** [Microsoft/vscode#44832] opened 2018-03-01 14:10 UTC
Issue Type: <b>Bug</b>

Unable to load schema from '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/schemas/tsconfig.schema.json'

Actual: A listing of the typescript directory shows no schemas folder.
Expected: A listing of the typescript directory would show a schemas folder with a tsconfig.schema.json

VS Code version: Code - Insiders 1.21.0-insider (3fec61014742dec894b3a31cdf8556bf533cb0e1, 2018-02-28T06:08:46.169Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|Load (avg)|2, 9, 13|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by mjbvz** [comment] 2018-03-01 23:35
Duplicate of #44718

**Closed by mjbvz** 2018-03-01 23:35 UTC
Labels: insiders
