### ISSUE TITLE
Source Control section running forever

### ISSUE THREAD

**Issue by nguyennb9** [Microsoft/vscode#24170] opened 2017-04-07 04:22 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|project-manager|alefragnani|0.13.5|
|theme-desertex|casualjim|0.0.6|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|json-tools|eriklynd|1.0.2|
|prettier-vscode|esbenp|0.12.0|
|flow-for-vscode|flowtype|0.5.0|
|vscode-icon-theme|jtlowe|1.5.0|
|Go|lukehoban|0.6.59|
|addDocComments|stevencl|0.0.8|
|react-beautify|taichi|0.3.0|;

---

Steps to Reproduce:
![image](https://cloud.githubusercontent.com/assets/12994001/24785481/67a82e98-1b84-11e7-9188-df7095399707.png)

1. Make some change in your code when git working directory is empty
2. Open Source Control section
You will see the status bar running forever

**Comment by joaomoreno** [comment] 2017-04-07 08:20
Duplicate of #23977

**Comment by joaomoreno** [comment] 2017-04-07 13:16
Not a duplicate, actually.

**Closed** 2017-04-07 13:16 UTC
Labels: bug, git

**Comment by nguyennb9** [comment] 2017-04-07 14:40
Oh, so fast, thank you man. Keep up the good work 👍

**Comment by isidorn** [comment] 2017-04-12 09:15
Adding verified based on code review.
Now we are never showing progress for fetch operations
