### ISSUE TITLE
WSL extension broken after changing profiles and can't delete/reinstall

### ISSUE THREAD

**Issue by caforbes** [microsoft/vscode#181681] opened 2023-05-06 03:54 UTC
Type: <b>Bug</b>

I started on a working project in WSL2. Have been using it for months no problems.

1. I tried to create a new profile from the template "Python"
2. It prompted me to install WSL in that profile, I said yes
3. I changed back to my original profile
4. Now the original profile prompted me to install WSL, even though it had already been installed. In every profile I try I get this error:
```
2023-05-05 20:49:38.063 [error] Unable to delete the existing folder 'c:\Users\forcf\.vscode\extensions\ms-vscode-remote.remote-wsl-0.78.4' while installing the extension 'ms-vscode-remote.remote-wsl'. Please delete the folder manually and try again: Delete: Unable to delete the existing folder 'c:\Users\forcf\.vscode\extensions\ms-vscode-remote.remote-wsl-0.78.4' while installing the extension 'ms-vscode-remote.remote-wsl'. Please delete the folder manually and try again
    at e.ExtensionsScanner.extractUserExtension (c:\Users\forcf\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:12555)
    at async x.v (c:\Users\forcf\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:19429)
    at async x.y (c:\Users\forcf\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:21039)
    at async x.h (c:\Users\forcf\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:19004)
```
5. I can't delete the extension folder to manually reinstall because there is a file `wslServer.sh` which I do not have permissions to touch, even though I am an administrator.

Now everything on my computer is messed up because I've tried uninstalling everything, but even a fresh installation cannot install the WSL extension because of this file. please help.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.17GB free)|
|Process Argv|--crash-reporter-id c1118667-74ba-40f9-bac7-6ab9b5e651cb|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30731978

```

</details>

**Comment by Dufko** [comment] 2023-05-07 19:21
Currently experiencing the same issue. It won't even let me look at the owner.


But I found a **workaround**:

- Download the WSL extension from web version of the extension store: [https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) (if you deleted the rest of the extension like me)
- Rename the extension to .zip
- Copy the contents of the extension folder in the zip to `C:\Users\user\.vscode\extensions\ms-vscode-remote.remote-wsl-0.78.4` or your location of the extension
- This will make vscode think that the extension is properly installed
- On next launch there will be an error that it cannot connect to wsl
- Ignore it
- Go to extension store and install older version

**Comment by caforbes** [comment] 2023-05-07 23:44
My own workaround: restarting my computer and VSCode will delete the ownerless file and allow me to continue. However, creating new profiles from a project in WSL continues to raise the same problem with installation of the WSL extension.

**Comment by aeschli** [comment] 2023-05-09 21:23
The extension folder can't be deleted as WSL is still referencing `wslServer.sh`.
The workaround is to run `wsl --shutdown`

I'm not sure why switching the profile requires deleting the wsl extension.

**Comment by boneskull** [comment] 2023-05-18 18:38
Can confirm the workaround offered by @aeschli above works.

**Comment by ellisgeek** [comment] 2023-05-26 18:40
I have this issue as well and it's really annoying.

My workaround is to `killall node` (the vscode-server) in WSL and then cleanup the extension (delete `C:\Users\{{ username }}\.vscode\extensions\ms-vscode-remote.remote-wsl-x.xx.x`), reload, and re-install it.

**Comment by sandy081** [comment] 2023-06-01 10:20
Could be a duplicate of https://github.com/microsoft/vscode/issues/180482

**Comment by sandy081** [comment] 2023-06-08 12:48
> It prompted me to install WSL in that profile, I said yes

@caforbes Can you please provide me the screenshot of VS Code at this step? If possible, please share a gif/video of the steps you mentioned in the description.

**Comment by learning310** [comment] 2023-08-12 03:24
I have this issue as welln my computer.

**Comment by sandy081** [comment] 2023-08-24 12:35
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Closed by sandy081** 2023-08-24 12:35 UTC
Labels: bug, user-profiles
