### ISSUE TITLE
Intellisense completion covers code making it hard to type

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#133622] opened 2021-09-22 18:40 UTC
> You mean it comes up on top of it visually?

Yes. I think the current design didn't take consideration of the fact that the code entering field is fixed in the lower right corner. It seems like this is a general issue in vscode if you type code in the lower right position. 
![TBiSMCWVMm](https://user-images.githubusercontent.com/33796896/134402255-be364422-899f-4898-a6eb-b0337f5436dd.gif)
![FAlQQVZS61](https://user-images.githubusercontent.com/33796896/134402257-602844e8-4fcd-4e28-a791-57fe90677193.gif)

_Originally posted by @StevenLi-DS in https://github.com/microsoft/vscode-jupyter/issues/7406#issuecomment-925191006_

**Comment by rebornix** [comment] 2021-11-02 20:11
@jrieken any suggestion how we can position the suggest widget properly (like always above the cursor, since the editor is at the bottom of the workbench)?

**Comment by jrieken** [comment] 2021-11-03 08:21
The suggest widget does support these cases but always prefers to show below but we can add some options to tweak that preference for some editors. I am not familiar with the details of the interactive window and how its editor is created but this should be possible

**Comment by jrieken** [comment] 2021-11-05 08:25
I was able to reproduce with "normal" IntelliSense. The suggest details have a preference of being aligned to the top of the suggestions list. Now, when details are taller than the list and when the list is rendered above details render atop the text. 

I have pushed a fix to adjust the preference of details, when the suggestions list renders below it has a preference for being top aligned and the suggestions list renders above it has a preference of being bottom aligned. This fix will the general case but there can still by "special" size cases where this isn't ideal.

https://user-images.githubusercontent.com/1794099/140480160-15c92ec1-c0e3-4a44-ba86-59e566fcea2e.mov

**Closed** 2021-11-05 08:25 UTC
Labels: bug, ux, polish, suggest

**Comment by jrieken** [comment] 2021-11-05 08:27
To verify:

* have the snippet below
* make sure the last line is at the bottom of the VS Code window
* trigger parameter help and suggest
* make sure the details are bottom aligned
* scroll contents to the middle of the view port
* trigger parameter and suggest
* make sure the details are top aligned


```ts
/**
 * The quick brown fox and much more bla bla.
 * @example
 * TSDoc-like example tag
 * ```js
 * void foo();
 * ```
 */
function test(a: number, b: typeof document) {
	//
	return {
		really: true,
	}
}


test(true, d/*TRIGGER_HERE*/)
```

**Comment by rchiodo** [comment] 2021-12-01 19:10
/verified

![image](https://user-images.githubusercontent.com/19672699/144298122-26b114c4-a91f-4be4-9bad-bad71c1de83d.png)
