### ISSUE TITLE
Codelens shows "No" occacionally

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#68290] opened 2019-02-09 01:17 UTC
Issue Type: <b>Bug</b>

Very often after swtiching between files I started to see "No" being displayed in Codelens

<img width="562" alt="image" src="https://user-images.githubusercontent.com/876920/52514316-684ded80-2bc5-11e9-963a-158b00dd26b9.png">

VS Code version: Code - Insiders 1.32.0-insider (709bf352b12de8284683bef94cb5984129bfc776, 2019-02-08T14:51:00.181Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.63GB free)|
|Process Argv|-psn_0_8779871|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
solargraph|cas|0.19.3
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.8.1
vscode-pull-request-github-insiders|Git|1.39.0
ocaml|hac|0.6.43
beautify|Hoo|1.4.8
references-plusplus|jri|0.0.5
graphql-for-vscode|kum|1.13.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.9
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.1.0
azure-account|ms-|0.8.0
Go|ms-|0.9.1
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|0.4.1
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.1151
debugger-for-chrome|msj|4.11.1
debugger-for-ios-web|msj|0.1.2
color-highlight|nau|2.3.0
vetur|oct|0.15.0
subtitles-editor|pep|1.0.2
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.3
seti-icons|qin|0.1.3
project-snippets|reb|0.5.0
ruby|reb|0.21.0
smartpaste|reb|0.0.3
toggle|reb|0.0.1
sass-indented|rob|1.5.1
rust|rus|0.5.3
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.2.1

(10 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-02-11 16:58
Duplicate of #68393 I believe

**Comment by mjbvz** [comment] 2019-02-11 17:00
Nevermind, that's windows only I think. @rebornix are you using the language pack that you have installed?

**Comment by rebornix** [comment] 2019-02-11 17:08
@mjbvz I didn't use any language pack (I have them installed though).

**Comment by mjbvz** [comment] 2019-02-11 22:41
@jrieken I believe this issue may be from 0693cb7afc921b7ee3cbdeab1d63e85839cef90d. The full text here is `no command`. We show that placeholder text when `resolveCodeLens` in extHostLanguageFeatures returns undefined, but I'm having trouble determining why this is happening

**Comment by mjbvz** [comment] 2019-02-11 23:03
**Repo steps**
1. Enable the typescript reference code lens
1. Open a long file from the VS Code codebase
1. Wait for lenses to resolve.
1. Wait 30 seconds or so
1. Scroll down and then back up to where the previously resolve code lenses were showing
1. 🐛 Code lenses now labeled as `no commands`

Looks like the lenses are being garbage collected. I'm trying to figure out why this happens and also why we try to re-resolve already resolved code lenses

**Comment by jrieken** [comment] 2019-02-12 09:42
Yes, https://github.com/Microsoft/vscode/commit/0693cb7afc921b7ee3cbdeab1d63e85839cef90d actually removed a check that prevents double tracking of the same ext-host-side-objects

**Closed** 2019-02-12 10:00 UTC
Labels: bug
