### ISSUE TITLE
Support relative paths in output and repl

### ISSUE THREAD

**Issue by joebehymer** [Microsoft/vscode#6217] opened 2016-05-09 19:34 UTC
- VSCode Version: 1.0
- OS Version: OSX Yosemite

Steps to Reproduce:
1. Setup project with task runner that outputs tsc output to Output window with TSC 1.6.  Notice it uses full path names and you can click on a path to go to the file.
2. Upgrade project to TSC 1.8.  It now uses relative file paths and you can't click on them anymore.

with TypeScript 1.6 (working):http://imgur.com/sIQLu8I
with TypeScript 1.8 (broken): http://imgur.com/qePitPw

I have a pretty vanilla tasks.json that calls grunt (which uses grunt-ts). The output seems to match [line 80](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputWorker.ts#L80) here, yet I can't click the lines to navigate.  I believe this is because of a recent tsc version update to 1.8, and I downgraded back to 1.6 to verify.

**Comment by isidorn** [comment] 2016-05-09 19:40
I think this is just how our path detection works, and the new paths are not detected. @bpasero ?

**Comment by bpasero** [comment] 2016-05-10 05:00
Yes, for output and repl we only detect absolute paths as links:

https://github.com/Microsoft/vscode/blob/ben/stacks/src/vs/workbench/parts/output/common/outputWorker.ts#L73
https://github.com/Microsoft/vscode/blob/ben/stacks/src/vs/workbench/parts/debug/browser/replViewer.ts#L97

Maybe we should revisit this though. The reason we pick absolute paths is to have less false positives but maybe when we include the full error pattern (line:column) we will not get false positives even if we support relative paths.

The downside is that we always need to root relative paths to the workspace path and that might be a wrong assumption.

**Comment by jhasse** [comment] 2016-05-10 14:15
Wouldn't it be possible to use the `problemMatcher` also for the clickable links?

**Comment by bpasero** [comment] 2016-05-10 14:41
Yes, I think bringing in support for using problem matcher patterns is a good idea.

**Comment by joebehymer** [comment] 2016-05-10 14:55
I appreciate the general fix to this is to support relative paths, and additional support for problem matchers would be awesome (I did try it!).  

I hope that the fact that this is not a general language problem but a TypeScript problem should influence it's priority.  Heck, you guys are using TS 1.8 in vscode itself, do you not miss these?  Or maybe you never have any errors :)

**Comment by joebehymer** [comment] 2016-10-10 21:18
With the release of VSC 1.6, that ships with TS 2.0, a lot of people are going to run into this more often now, trying to hook up things to work with `strictNullChecks`.  I know I am.  

How I wish I could click on these...
```
test/spec/core/util/testUtils.ts(95,50): error TS2345: Argument of type 'null' is not assignable to parameter of type 'NotificationInteropProvider'.
test/spec/core/util/testUtils.ts(96,51): error TS2345: Argument of type 'null' is not assignable to parameter of type 'FeatureToggleInteropProvider'.
>> 309 non-emit-preventing type warnings  
```

**Comment by ramya-rao-a** [comment] 2017-03-28 21:51
@joebehymer You can now configure your tasks to send output to the integrated terminal which supports links on relative paths. 

https://code.visualstudio.com/updates/v1_9#_task-execution-in-terminal

**Comment by jhasse** [comment] 2017-03-29 08:08
The problem is, that this ignores the the directory specified in the `problemMatcher`:

```
"fileLocation": ["relative", "${workspaceRoot}/build/"],
```

So all of my links which are starting with `../` don't work.

**Comment by ramya-rao-a** [comment] 2017-03-29 17:00
cc @Tyriar our terminal expert

**Comment by dbaeumer** [comment] 2017-03-30 07:31
We are working on supporting problem matchers in the terminal which then will take the `fileLocation` into consideration.

**Comment by dbaeumer** [comment] 2017-11-10 14:33
Marking as dup of #21928 since there is no link matching planned in the old output runner.

**Closed by dbaeumer** 2017-11-10 14:33 UTC
Labels: feature-request, tasks
