### ISSUE TITLE
ms-python.python Webview is not loading on some systems. 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#98335] opened 2020-05-21 16:12 UTC
- VSCode Version: 1.46.insiders
- OS Version: Mac

Steps to Reproduce:

1. Install python extension
1. Run command 'Create New Blank Jupyter Notebook'
1. Blank window appears 50% of the time (it should show a toolbar and a single cell).

See the discussion here (we can't reproduce in house):
https://github.com/microsoft/vscode-python/issues/11865#issuecomment-631911989

Does this issue occur when all extensions are disabled?: N/A

It looks like the webview is created but the extension HTML is never loaded. We thought this might have been issue: #89038 but it's not showing the same symptoms (resource load errors).

Do you have any guidance on how we might debug this?

**Comment by mjbvz** [comment] 2020-05-26 20:18
Are users seeing this on the most recent VS Code insiders?

**Comment by rchiodo** [comment] 2020-05-26 20:20
According to the user's comments, yes. See the linked issue: (https://github.com/microsoft/vscode-python/issues/11865)

We cannot repro in house though.

**Comment by rchiodo** [comment] 2020-05-26 20:22
Specifically this comment where the user responded after I asked them to install the latest insiders:
https://github.com/microsoft/vscode-python/issues/11865#issuecomment-631672764

**Comment by mjbvz** [comment] 2020-06-02 02:44
Seems like the same issue as #98746

Can you please have the user test the next insiders build. The build includes a potential fix for this issue, but since I can't repo this I can't confirm

**Comment by rchiodo** [comment] 2020-06-02 15:53
Will do, thanks.

**Comment by rchiodo** [comment] 2020-06-02 18:06
I can confirm that this seems to fix the problem for those customers that were hitting the issue. Thanks.

**Comment by mjbvz** [comment] 2020-06-02 23:13
Thanks for confirming. Closing as a duplicate of #98746 then

**Closed by mjbvz** 2020-06-02 23:13 UTC
Labels: needs more info, webview
