### ISSUE TITLE
Simplified file picker will move the cursor to the beginning when pressing up to navigate the list

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69540] opened 2019-02-27 14:43 UTC
Quick open doesn't do this

Repro:

1. Open file picker
2. Press up, notice that the textbox cursor moved in addition to the selected list item

**Comment by alexr00** [comment] 2019-03-04 14:49
Duplicate of #69378

**Closed** 2019-03-04 14:49 UTC
Labels: *duplicate, bug
