### ISSUE TITLE
Help user to spot their desired VS code instance quickly!

### ISSUE THREAD

**Issue by jiec-msft** [microsoft/vscode#193873] opened 2023-09-23 10:00 UTC
You know, VS code is really powerful. And people are doing everything with it, one for editing repo for personal blog, one for code develop work like nodejs, python, java and etc, and another one to just open a temporary file.

The problem to the users is, from the OS Taskbar (Such as win11 taskbar), they all look same. And need an additional check to find the one that needed.

So, this feature request is to make it easier for user to find the target VS code instance.

One option I can think of is offering customizable icon, and if taskbar don't stack same app together, user can spot their desired VS code instance quickly!

**Comment by IllusionMH** [comment] 2023-09-23 19:48
Duplicate of #164157

You can use [Peacock extension] (https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) to easily color UI which will allow you to find them by preview.

**Closed** 2023-09-24 01:27 UTC
Labels: triage-needed
