### ISSUE TITLE
Column selection does not allow left highlighting

### ISSUE THREAD

**Issue by MiYanni** [Microsoft/vscode#21647] opened 2017-03-01 19:41 UTC
- VSCode Version: 1.9.1
- OS Version: Windows 10.0.14393.693

Steps to Reproduce:

1. Hold Shift+Alt.
2. Click and drag the mouse cursor left.
3. Observe that column selection does not begin highlight properly. Instead, the cursor position moves left instead of selecting to the left.

This functionality works appropriately when moving the cursor right. However, moving it left, it doesn't function at all. Standard click+drag actions allow highlighting to the left. Column selection should also allow left highlighting.

![2017-03-01_11-33-45](https://cloud.githubusercontent.com/assets/17788297/23477782/f3aca99c-fe73-11e6-9f94-76ff507016f7.gif)

**Comment by alexandrudima** [comment] 2017-03-02 09:54
Duplicate of #20087, fixed in latest stable release.

**Closed by alexandrudima** 2017-03-02 09:54 UTC
