### ISSUE TITLE
 request 'listbreakpoints' was cancelled because node is unresponsive

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#653] opened 2015-11-25 19:13 UTC
Id: <b>4f3e6055-db00-b505-57ef-2fbd3cb89778</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/workbench/parts/debug/node/rawDebugSession.ts#L68:28 (RawDebugSession.send)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/rawDebugSession.ts#L68:28 (RawDebugSession.send))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1470:0 (onError)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1470:0 (onError))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1176:0 (_notify)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1176:0 (_notify))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1316:0 (_run)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1316:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L61:5 (V8Protocol.send)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/v8Protocol.ts#L61:5 (V8Protocol.send))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L127:4 (V8Protocol.dispatch)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/v8Protocol.ts#L127:4 (V8Protocol.dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L96:11 (V8Protocol.handleData)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/v8Protocol.ts#L96:11 (V8Protocol.handleData))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L51:8 (V8Protocol.connect)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/v8Protocol.ts#L51:8 (V8Protocol.connect))<br />    at Socket.<anonymous> (out/vs/workbench/workbench.main.js:1593:24200)<br />    at emitOne (events.js:77:13)<br />

**Comment by isidorn** [comment] 2015-11-26 11:22
@weinand this is as designed, right? Do you think there is something better we could do here?

**Comment by isidorn** [comment] 2015-12-01 09:11
Assigning to Andre to read the comment 😇

**Comment by weinand** [comment] 2015-12-01 09:41
All timeouts are a result of debugging large data structures on versions of node.js that do not support code injection.
Resolved as a duplicate of Microsoft/vscode-node-debug#11

**Closed by weinand** 2015-12-01 09:41 UTC
Labels: debug, error
