### ISSUE TITLE
Calculated Snippets

### ISSUE THREAD

**Issue by mpearon** [Microsoft/vscode#19874] opened 2017-02-03 20:13 UTC
The ability to insert a "calculated" snippet would be great.  For instance, the snippet would process Get-Date, and actually insert the output as the snippet text.  It would be handy for creating Comment Blocks that contain creation dates, last updated, current machine, etc,...

- VSCode Version: 1.90
- OS Version: Win 10

**Comment by jrieken** [comment] 2017-02-06 08:46
dupe of #6920. Also you can use the extension API, implement a CompletionItemProvider and return completions of kind Snippet to achieve dynamic snippets

**Closed by jrieken** 2017-02-06 08:46 UTC
Labels: duplicate
