### ISSUE TITLE
Settings does not use default for some configuration values

### ISSUE THREAD

**Issue by Phrogz** [microsoft/vscode#177490] opened 2023-03-17 15:27 UTC
Does this issue occur when all extensions are disabled?: No (requires this extension)

- VS Code Version: 1.76.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Install the extension "NeatJSON" (`Phrogz.neatJSON`)
2. Open the Settings and search for "neatjson"

**EXPECTED**: Every configuration value uses the default.
**ACTUAL**: Some values are empty or show errors. (For me it's "Wrap Lines: Wrap Width" and "Format Decimals: Precision".)

![image](https://user-images.githubusercontent.com/14778/225947814-d17d9729-d0c3-41bc-9999-6e0dbcfbc54b.png)

Note that the configuration values have defaults, and settings.json does not have any overrides. Note also that "Indent: Amount" uses the same `type` and has a `default`, yet doesn't show the same problem.

First time I opened Settings for me `Wrap Lines?` also showed errors, first saying that it was the wrong type and I needed to edit it in the JSON. After editing the JSON to set a boolean value for it, _and then deleting that from `settings.json`_, the Settings panel fixed that value and no longer shows an error. But Wrap Width and Precision continue to show errors in Settings UI unless I set values in `settings.json`.

```
Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:57:21.103Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.4.0-1095-gke
Sandboxed: Yes
```

**Comment by rzhao271** [comment] 2023-03-21 22:59
Duplicate of #176373

**Closed by rzhao271** 2023-03-21 22:59 UTC
