### ISSUE TITLE
Allow custom file icon

### ISSUE THREAD

**Issue by mlntr** [microsoft/vscode#183176] opened 2023-05-23 02:11 UTC
I am happy with my file icon theme. but to help productivity, I would like to add a custom icon (it'd only appear in certain named files that I specify). It seems VS Code doesn't let users directly do this. VS Code should support this.

**Comment by aeschli** [comment] 2023-05-23 08:46
Duplicate of https://github.com/microsoft/vscode/issues/44026

**Closed by aeschli** 2023-05-23 08:46 UTC
