### ISSUE TITLE
Mixing open files into each other on Save

### ISSUE THREAD

**Issue by GroFinJarryd** [Microsoft/vscode#12224] opened 2016-09-18 16:07 UTC
- VSCode Version:1.5.2
- OS Version:Windows 10 x64 1607

Steps to Reproduce:

1. Opened up Mapped SharePoint drive linking to masterpage assets (HTML Display templates and HTML page layouts.
2. Have HTML page layout open and HTML Display template file open.
3. When saving HTML page layout, contents from the second file (HTML Display Template) get inserted into the HTML Page layout file

**Comment by bpasero** [comment] 2016-09-19 05:16
@GroFinJarryd I have no clue what the issue is, please add more details and possibly screenshots/video

**Comment by bpasero** [comment] 2016-09-24 06:05
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-09-24 06:05 UTC
Labels: needs more info
