### ISSUE TITLE
scrolling issue with touchpad 

### ISSUE THREAD

**Issue by chan4u** [Microsoft/vscode#30954] opened 2017-07-18 18:33 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. scrolling on pages stops frequently but when I resize the  VSC window scrolling on editor ,filetree works

2.

**Comment by rebornix** [comment] 2017-07-18 18:41
@chan4u are you saying that scrolling in the editor stops frequently and resizing the window can mitigate this problem? Besides, you don't see this issue in the file explorer, right?

**Comment by chan4u** [comment] 2017-07-18 18:43
yes exactly

**Comment by dlabaj** [comment] 2017-07-18 23:28
I'm having the same issue with the same build.

VSCode Version: 1.14.1
OS Version: Windows 10
Extensions: none

**Comment by Raul6469** [comment] 2017-07-25 21:33
The same for me,

OS Version: Windows 10 
VSCode version: 1.14.2

**Comment by morganwdavis** [comment] 2017-09-13 07:45
Confirming this janky touchpad scrolling as well, most notably for me in the file explorer.  I found that by popping into and out of zen view fixes it (basically causing a whole editor refresh).

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.16281
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.3
vscode-eslint|dba|1.3.1
vscode-html-css|ecm|0.1.8
php-intellisense|fel|1.5.1
php-docblocker|nei|1.2.0
rewrap|stk|1.5.0

**Comment by justinwzig** [comment] 2017-12-17 19:35
I'm having the same problem.
- Machine: Lenovo Thinkpad X1 Carbon
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
spellright|ban|2.0.16
vscode-markdownlint|Dav|0.12.0
git-project-manager|fel|1.4.0
ginfuru-vscode-jekyll-syntax|gin|0.0.5
vscode-jekyll-snippets|gin|0.8.7
sublime-babel-vscode|jos|0.2.9
graphql-for-vscode|kum|1.7.0
vscode-attrs-sorter|mrm|2.1.0
vscode-jade-snippets|mrm|1.0.1
sublime-keybindings|ms-|3.0.3
language-liquid|nei|0.0.3
sass-indented|rob|1.4.5
ayu|tea|0.10.0
html2jade|wma|0.2.0

(2 theme extensions excluded)


---

Steps to Reproduce:

1. Scroll
2. See the jankyness


Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-12-18 12:00
Duplicate of #13612

**Closed by alexandrudima** 2017-12-18 12:00 UTC
Labels: bug, editor, editor-core, trackpad/scroll
