### ISSUE TITLE
Darker/lighter areas in the source editor background

### ISSUE THREAD

**Issue by chuckleplant** [Microsoft/vscode#21422] opened 2017-02-25 18:46 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.2.3|
|python|donjayamanne|0.5.8|
|Theme-TwoStones|gerane|0.0.2|
|Theme-wild-cherry|gerane|0.0.3|
|theme-onedark-sublime|joshpeng|0.3.6|
|cpptools|ms-vscode|0.10.1|

---

Steps to Reproduce:

1. Open any file
2. Notice that some areas of the editor are darker/lighter depending on where the cursor is

Is this by design?  What is the purpose?

![vsc-darker](https://cloud.githubusercontent.com/assets/3345499/23333822/2147c6a4-fb93-11e6-9e65-4790319904b2.png)

**Comment by mrmlnc** [comment] 2017-02-25 19:19
Duplicate of #12473.

Sorry, but, please, use search before create a new issue.

See official release notes: http://code.visualstudio.com/updates/v1_6#_macos-sierra-support

**Closed** 2017-02-25 19:25 UTC
