### ISSUE TITLE
vs code won't suggest

### ISSUE THREAD

**Issue by mamoon100** [microsoft/vscode#130498] opened 2021-08-10 16:44 UTC
Issue Type: <b>Bug</b>

i dont know what happen but vs code won't suggest any word in any type of language 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.11.0-25-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 2480)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.42GB (4.79GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9c89dcb5-54ea-42d5-a8ec-9996ce421931|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
highlight-whitespaces|And|0.0.2
vscode-tailwindcss|bra|0.6.13
simple-react-snippets|bur|1.2.3
toggle-format-on-save|cbr|0.2.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
quick-html-previewer|dai|1.0.1
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
emoji-snippets|dev|1.5.3
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.8
copilot|Git|1.3.2283
vscode-pull-request-github|Git|0.29.0
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
kite|kit|0.147.0
node-module-intellisense|lei|1.5.0
code-beautifier|mic|2.3.3
vscode-exec-node|mir|0.5.4
HTMLHint|mka|0.10.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
live-server|ms-|0.2.7
vscode-typescript-next|ms-|4.5.20210809
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.6.0
material-icon-theme|PKi|4.9.0
ponicode|Pon|0.48.1
vscode-thunder-client|ran|1.8.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.22
vscode-scss-formatter|sib|2.2.3
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
sass-indented|syl|1.8.17
html-preview-vscode|tht|0.2.5
indent-one-space|use|0.2.6
vscodeintellicode|Vis|1.2.14
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.390
JavaScriptSnippets|xab|1.8.0
dom-code-snippets|yon|1.0.2
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-08-10 18:58
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by mamoon100** [comment] 2021-08-10 20:09
It's working now thanks 
I did not know there was a command can do this thank you sir 
Ps: it was "kite" extension

**Comment by gjsjohnmurray** [comment] 2021-08-10 22:26
Please close this issue.

**Closed** 2021-08-11 04:46 UTC
