### ISSUE TITLE
Manage Unsafe Repository fails with git error

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#169354] opened 2022-12-16 01:30 UTC
Windows 11 with `git 2.39.0.windows.1`, this is the error when trying to add the current workspace via the "Manage Unsafe Repository" quick prompt:

```
2022-12-15 17:25:45.511 [info] warning: encountered old-style '//Mac/Home/Documents/Personal/vscode' that should be '%(prefix)///Mac/Home/Documents/Personal/vscode'
warning: encountered old-style '//Mac/Home/Documents/Personal/vscode' that should be '%(prefix)///Mac/Home/Documents/Personal/vscode'
warning: encountered old-style '//Mac/Home/Documents/Personal/vscode' that should be '%(prefix)///Mac/Home/Documents/Personal/vscode'
```

Nothing happens afterwards, reload shows the same unsafe error notification.

**Comment by lszomoru** [comment] 2022-12-16 08:59
Duplicate of https://github.com/microsoft/vscode/issues/168344. Can you please see if this is fixed in Insiders? Thanks!

**Comment by lszomoru** [comment] 2023-01-10 08:09
Closing this as duplicate of #168344.

**Closed by lszomoru** 2023-01-10 08:09 UTC
Labels: bug, git
