### ISSUE TITLE
Alt+` key-combination on US-layout keyboard is sometimes intercepted by menu bar

### ISSUE THREAD

**Issue by espresso3389** [microsoft/vscode#115420] opened 2021-01-29 16:06 UTC
- VSCode Version: Version: 1.53.0-insider 5a52bc29d5e9bc419077552d336ea26d904299fa
- OS Version: Windows_NT x64 10.0.21301

Steps to Reproduce:

1.  `Alt`+`` ` `` to toggle Japanese IME on US-layout keyboard
2. Sometimes menu bar intercepts the key-combination and it results in key-focus got the menu bar.

Expected behavior:

- IME is toggled and the text pane keeps the keyboard focus.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment] 2021-01-29 18:41
@espresso3389  I assume you use the custom menubar?

**Comment by sbatten** [comment] 2021-01-29 19:15
@espresso3389 please confirm which menu bar you are using by checking `window.titleBarStyle` in your settings.

**Comment by espresso3389** [comment] 2021-01-30 09:20
`window.titleBarStyle` is `custom`.

**Comment by sbatten** [comment] 2021-02-05 19:00
marking as dupe of #115810, I now understand what is going on here... see dupe for info

**Closed by sbatten** 2021-02-05 19:00 UTC
Labels: needs more info
