### ISSUE TITLE
Time changes are not handled gracefully

### ISSUE THREAD

**Issue by monokrome** [Microsoft/vscode#49800] opened 2018-05-14 02:33 UTC
- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project in Visual Studio Code
2. Open Task Manager, because it's going to be hard to do later
3. Change your time in Windows 10 Date/Time settings

Visual Studio Code should now be using excessive CPU. Windows may freeze up. I think that this may depend on which files are open, or how long VSCode has been running - but these are just guesses.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment] 2018-05-15 09:25
Duplicate of #42752

**Closed** 2018-05-15 09:25 UTC
Labels: *duplicate, log
