### ISSUE TITLE
Dimming of inactive group and tab makes text unreadable

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#26117] opened 2017-05-06 13:19 UTC
vscode: 1.12

I'm trying to work with the new theming colors; however, it seems that the dimming of the inactive tab in an inactive group is greater than before?

I can't seem to find a combination that is readable unless I make the inactive tab color `#FFFFFF` which then makes it way too bright when the group is active.

**Comment by bpasero** [comment] 2017-05-07 07:24
Yeah something is odd, will check. Note that we currently do not expose a way to control the colors for "inactive tab, inactive group" or "active tab, inactive group" but maybe we should bring this back. One reason to remove it was to simplify colors, but I can see how this can make it hard for theme authors to tweak the colors.

@dakaraphi if you manually change the color of the inactive tab inside inactive group to use an opacity of 0.3 instead of the current 0.12 does it work for you? I am trying to understand if we need to bring back a way to theme the colors or if this is OK when we restore the opacity to how it was.

Here is how to tweak the color:
* open dev tools (from the help menu)
* click on Elements tab and the little arrow button top left
* click on the inactive tab
* find the rgba color and tweak it:

![image](https://cloud.githubusercontent.com/assets/900690/25778718/f51e1a50-3306-11e7-9459-b180cb76cf16.png)

**Comment by dakaraphi** [comment] 2017-05-07 13:46
@bpasero confirmed that `0.3` is enough to make it readable again.
Restoring the original value would be enough for me.

**Comment by bpasero** [comment] 2017-05-07 15:04
@dakaraphi awesome

**Comment by bpasero** [comment] 2017-05-07 15:04
Closing this as duplicate of https://github.com/Microsoft/vscode/issues/26132 thereby.

**Closed by bpasero** 2017-05-07 15:04 UTC
Labels: needs more info, themes
