### ISSUE TITLE
Global search losses track of current match after editing a file

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#26458] opened 2017-05-11 13:54 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.9|
|rainbow-brackets|2gua|0.0.6|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|vscode-astyle|chiehyu|0.6.2|
|python|donjayamanne|0.6.4|
|EditorConfig|EditorConfig|0.9.3|
|matlab|Gimly81|0.5.0|
|triggertaskonsave|Gruntfuggly|0.1.2|
|status-bar-tasks|GuardRex|0.2.0|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.4.4|
|center-editor-window|kaiwood|2.0.2|
|select-part-of-word|mlewand|1.0.1|
|cpptools|ms-vscode|0.11.0|
|indent-rainbow|oderwat|0.6.1|
|vscode-clearcase|OpenNingia|1.9.2|
|vscode-icons|robertohuertasm|7.7.0|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.4.2|
|vscode-hexdump|slevesque|1.3.0|
|code-spell-checker|streetsidesoftware|1.1.0|
|comment-snippets|Tobiah|0.2.0|
|selectline-statusbar|tomoki1207|0.0.2|
|dark-plus-material|vangware|1.0.1|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|;

---

Steps to Reproduce:

1. Global search for something that has multiple matches across multiple files.
2. Use F4 to set through matches.
3. Edit the code in one of the files found by the match.
4. Press F4 again to go to next match. It returns to beginning of the list rather than continuing from last match. Note: The last match may have been deleted in the editing. Expect that it should continue from previous match to next available one.

**Comment by kompot** [comment] 2017-08-15 20:54
I guess, in case found entry was completely deleted, focus should move to the next one.

E. g. you want to find and manually delete some entries after reviewing. This would work perfectly if focus moves to the next entry found.

**Comment by roblourens** [comment] 2017-12-04 19:11
/duplicate of https://github.com/Microsoft/vscode/issues/20467

**Closed by roblourens** 2017-12-04 19:11 UTC
Labels: *duplicate, bug, search
