### ISSUE TITLE
View not focus when go to end of long line

### ISSUE THREAD

**Issue by tdchien** [Microsoft/vscode#61976] opened 2018-10-28 09:03 UTC
Issue Type: <b>Bug</b>

When I make a jump to the last character of a long line (Using End key on window keyboard), the view can not display the cursor position. Please review and check this issue
![image](https://lh3.googleusercontent.com/-cRsT0gNVwDs/W9V3BIG82LI/AAAAAAAABJ8/1cnjOUvB9SwxUENYiHcMYdBHvsq8YLoZQCHMYCw/s0/2018-10-28_15-44-39.gif)

It's should be like I tried with Sublime Text
![image](https://lh3.googleusercontent.com/-DjZENiQvIHE/W9V7tZCjhZI/AAAAAAAABKU/EBKexaTdoiQDYVWdMO-yvKc6TqdgEyfXwCHMYCw/s0/2018-10-28_16-04-44.gif)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by weinand** [comment] 2018-10-28 14:44
Please explain the problem in words. Interpreting screen casts in not an efficient use of our time.

**Comment by tdchien** [comment] 2018-10-29 08:35
@weinand Sorry. I just add description of the problem. That's meaning when I make a jump to the last character of a long line, the view can not display the cursor position

**Comment by alexandrudima** [comment] 2018-10-29 12:57
Duplicate of #50304

**Closed by alexandrudima** 2018-10-29 12:57 UTC
