### ISSUE TITLE
IntelliSense offers too much help for basic literals

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#35806] opened 2017-10-07 21:44 UTC
- VSCode Version: 1.17.0
- OS Version: macOS 10.12.6

Reproduces without extensions: Yes

IntelliSense is getting in the way too much, for very simple things like JS objects. It's not only annoying and blocks my view of my code, but often times I'll want to use the arrow keys to navigate, and I get an IntelliSense popup which then blocks the up/down arrows which are used to navigate through hints. I'd rather not disable IntelliSense, though.

![screencap](https://user-images.githubusercontent.com/12532733/31312021-c63ba16c-ab7e-11e7-8d05-2124250c38a9.gif)

**Comment by andrewnaeve** [comment] 2017-12-01 03:04
+1 on this.

**Comment by mjbvz** [comment] 2018-03-26 22:51
Thanks. I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/22106 which is itself a duplicate of https://github.com/Microsoft/TypeScript/issues/1150 . If this is getting super annoying, you can disable the feature entirely by setting: `"editor.parameterHints": false`

Closing as upstream

**Closed by mjbvz** 2018-03-26 22:51 UTC
Labels: bug, javascript
