### ISSUE TITLE
"Open recent" lists of files and folders are not those most recently opened

### ISSUE THREAD

**Issue by fatherjack** [Microsoft/vscode#51124] opened 2018-06-05 07:26 UTC
Issue Type: <b>Bug</b>

The list of files and folders displayed in the Open recent dialogue is not a true representation of the files and folders that I have been editing and working with.

I can create new files or edit existing files and they seemingly get ignored as candidates for these lists.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|63.88GB (39.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.55
vscode-markdownlint|Dav|0.18.0
docs-authoring-pack|doc|0.0.3
docs-markdown|doc|0.0.3
xml|Dot|2.2.0
tslint|eg2|1.0.30
json-tools|eri|1.0.2
DocFX|ms-|0.1.3
mssql|ms-|1.3.1
PowerShell|ms-|1.7.0
vsliveshare|ms-|0.3.262
team|ms-|1.136.0
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.0
code-settings-sync|Sha|2.9.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-06-06 06:00
Duplicate of https://www.github.com/Microsoft/vscode/issues/49629

**Closed by bpasero** 2018-06-06 06:00 UTC

**Comment by fatherjack** [comment] 2018-06-06 14:44
Hi,

Can you explain the reason for this unexpected behaviour  please? It is different from every other Microsoft product's 'Recent files' functionality.

Many thanks
