### ISSUE TITLE
For file types where IntelliSense is not available, offer completion suggestions from opened editors

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode#52693] opened 2018-06-22 14:14 UTC
I like Visual Studio Code very much and I use it daily.

However, there's a small feature that bugs me, which is rarely present in programming editors or IDE, especially the bigger and more complex ones.

They either have very rich IntelliSense, where you get auto completion for class names, method names, properties, etc., or they're dumb as a brick for any kind of file they don't recognize.

Visual Studio Code does a bit better by offering completion suggestions from the current file, which is quite good.

However, there's an intermediary step which is actually quite good, sometimes it can even make you forget you're not using IntelliSense: offer completion suggestions from all the opened files or even all the files in the workspace if you want to be more extreme.

Vim, for example, does this. It's surprisingly effective, since the open files usually cover the same context as the file you're editing.

I should note that this would be a basic editing feature, not something tied to a specific language. It would be a catch-all for all the cases where VS Code doesn't have auto-completion support.

**Comment by mjbvz** [comment] 2018-06-25 18:31
Duplicate of #20886

**Closed by mjbvz** 2018-06-25 18:31 UTC
