### ISSUE TITLE
Commit messages are too light, hard to read

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#23429] opened 2017-03-28 13:50 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (a35c7da7b8f324c1e8cc7830173418e392542f6d, 2017-03-28T12:40:24.966Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.6.1|
|sort-lines|Tyriar|1.2.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.12.0|
|project-manager|alefragnani|0.13.5|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.8.1|
|Angular2|johnpapa|2.1.2|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-csscomb|mrmlnc|4.0.1|
|vscode-stylefmt|mrmlnc|2.2.4|
|stylelint|shinnn|0.23.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.4.1|
|theme-tesla|smlombardi|6.0.0|
|theme-toothpaste|aalaap|0.0.1|
|vscode-todo-highlight|wayou|0.4.12|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. commit some files, type a message
2. text is light gray on white

![screen shot 2017-03-28 at 9 36 39 am](https://cloud.githubusercontent.com/assets/835148/24408534/0934b77c-139c-11e7-82e5-632f0fbc8f6f.png)

**Comment by joaomoreno** [comment] 2017-03-28 15:02
Duplicate of #22131

**Closed by joaomoreno** 2017-03-28 15:02 UTC
