### ISSUE TITLE
Debugger not working properly, breakpoints won't trigger

### ISSUE THREAD

**Issue by TomL94** [Microsoft/vscode#5422] opened 2016-04-17 20:30 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 10

I'm working on a node.js project, using express.
I created the following POST route:
![capture](https://cloud.githubusercontent.com/assets/7473870/14589797/8d04b8bc-04f3-11e6-89cc-4311c527ad54.JPG)

Putted a breakpoint in the cb function of the route. When it arrives there, the program stops, but the breakpoint won't "trigger", VSCode looks like the server just runs as usual.
When the breakpoint isn't there - the program runs as it supposed to.

I opened the developer console, and when it supposedly reaches that breakpoint (again, not showing that the program stopped or anything) it prints to the console:
![capture2](https://cloud.githubusercontent.com/assets/7473870/14589822/24bf3420-04f4-11e6-88f0-37459605c512.JPG)

The same problem occurs on every post route so I can't debug them at all, but not on get routes (tried only get and post).

**Comment by weinand** [comment] 2016-04-18 12:17
@TomL94 are you launching the server through VS Code or are you attaching to a running server?

**Comment by molant** [comment] 2016-04-22 17:18
@weinand I'm having the same issue. My breakpoints in nodejs get reached, the execution stops but I don't see anything in the debugger window (but if I press F5 the execution continues). Strangely, when the code throws an exception and the debugger is set to capture all uncaught exceptions I can see the variables, call stack. etc.
If I set the debugger to break on entry it works as expected until I continue the execution to stop on a breakpoint.

This has also happened to other teammates in different times and versions but we've never found out how to reproduce it consistently (although once it happens doesn't seem to get fixed).

I'm currently running node 5.11.0 (was also happening with 5.10.1), Windows 10 14316 and the latest stable and insider versions of vs code (happens in both).

My alias is antonmo in case you want more information over Skype or follow up internally to get more info.

Thanks!

**Comment by rhurkes** [comment] 2016-05-01 00:23
VSCode version: 1.0.0
OS: OSX El Capitan
Node versions tried: 0.10.42, 4.4.3, 5.0.0, 5.9.1, 6.0.0
Express: 4.13.4

There are some weird conditions for this behavior that I've come across. I can recreate in every version of Node when trying to launch or attach my big app that uses Express's router:
http://expressjs.com/en/4x/api.html#express.router

I then tried the Express 'Hello World' sample located here:
http://expressjs.com/en/starter/hello-world.html
and set a breakpoint on 'res.send('Hello World!');'

Everything worked fine when debugging via launch or attach *except* for when I tried using Node 6.0.0 - then I observed the issue again. It's like it's hitting the breakpoint, but there is no visual indication in VSCode that it has done so, and watches/evaluations/stack don't have access to any of the expected objects.

**Comment by psulek** [comment] 2016-05-01 09:14
@rhurkes i have same issue with vscode (1.0) and node v6.

**Comment by psulek** [comment] 2016-05-01 09:17
@rhurkes So i unstalled node v6 and installed node-v5.11.0 and it works again. So issue is related to vscode 1.0 and node v6.

**Comment by schemburkar** [comment] 2016-05-05 02:56
Same issue as @rhurkes for me in express app. It now works with node v4.4.3 but not in v6
VSCode seems to stop at the breakpoint without any debug info with current line highlight, watch etc. I can then blindly step through using F8, without the current line being highlighted.

Debugger works on stopOnEntry but not in node/express handlers.

**Comment by molant** [comment] 2016-05-05 23:43
@psulek I'm runing node 5.11 and I'm having the same issue with the insider and the stable (and I had randomly for quite a few versions of vscode and node now).

**Comment by infeng** [comment] 2016-05-07 03:53
i have same problem
node: 6.0.0
os: windows10 14332
vscode: 1.0

**Comment by weinand** [comment] 2016-05-07 07:27
VSCode 1.0 does not yet support node v6.

**Comment by jasonmit** [comment] 2016-05-10 19:47
I'm experiencing this in node 4.4.3, I'll report back with more details shortly.

**Comment by rhurkes** [comment] 2016-05-10 20:01
For anyone seeing issues in places besides node 6.0, verify that nvm (or similar) isn't confusing things. I had to use launch.json's runtimeExecutable setting to get node 4.4.3 working with nvm while node 6 was installed as an OS package.

**Comment by jasonmit** [comment] 2016-05-10 20:07
@rhurkes I am attaching to the process in this case, so I don't specify a `runtimeExecutable`.  Also, some breakpoints hit and can be inspected whiled others hit and cannot be inspected.  Unfortunately, nothing in the developer console to provides any insight into what may be happening.

**Comment by cyan-haru-25** [comment] 2016-06-12 09:17
i had same problem. but I had resolved this problem.
I tried following environments. and its OK.
- OS : windows8.1
- vsCode : v1.2.0
- node : v6.2.1 and v5.10.1 and v4.4.3
- using port : 80

`my launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/bin/www",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}"
        },
    ]
}
```

this point is

 `"program": "${workspaceRoot}/bin/www",`
 
 <br>

 Step
-  you must stop `npm start`
- start debug with `Launch`

that's all

**Comment by chawk** [comment] 2016-08-13 18:19
I had this issue, but this was due to some breakpoints being applied within the Node.JS source code, when I removed those breakpoints everything worked fine.

**Comment by davidcoleman007** [comment] 2016-11-26 22:57
using windows 10 and latest electron, with node 6.9.1.  This happens for me as well.

I am building from the base electron-quick-start application.  I have stripped this down to a simple demo below.

my `index.html`
```html index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <link rel="stylesheet" href="./css/main.css"/>
    <script>
    	window.$ = window.jQuery = require('./libs/jquery-3.1.1.js');
   	</script>
	<script type="text/javascript" src="./views/main.view.js"></script>
  </head>
  <body>
  </body>

  <script>
    // You can also require other files to run in this process
    require('./renderer.js')
  </script>
</html>
```
main.view.js:
```javascript
$(document).ready(
	function() {
		debugger;
		console.log("i should have stopped now");
	}
);```

It does not stop.

**Comment by BoogalooJB** [comment] 2017-01-06 11:32
I had this issue, but I was using node 7.4.0. When I switched back to node 6.9, everything worked as expected (I had to set `runTimeExecutable` because I'm using `nvm` and the version set with `nvm` seems to have no effect in VS Code).

**Comment by weinand** [comment] 2017-01-06 11:43
@BoogalooJB VS Code uses the 'node' executable found via the PATH environment variable. If you manage node versions with nvm, you have to restart VS Code because otherwise it does not see updated environment variables. (But your approach will work too).

**Comment by GordonSmith** [comment] 2017-01-26 10:12
FWIW I was seeing this same issue in a node app written in TS and called from an external Test module (also coded in TS) - no express used.
What fixed it for me was correcting my "outDir" to point at the folder where the generated JS was: ```"outDir": ""${workspaceRoot}/dist-dev"```

Previously I had it set to ```"outDir": ""${workspaceRoot}/dist-dev/Test"``` which allowed me to set the breakpoints on the Test modukle, but not the app module.

Question:  "outDir" is saying its deprecated, what should it be replace with?

**Comment by isidorn** [comment] 2017-01-26 10:21
@GordonSmith please use "outFiles", more details https://code.visualstudio.com/updates/v1_6#_glob-pattern-support-for-source-map-setup

**Comment by jrwiegand** [comment] 2017-02-22 12:49
I am having this problem now. I am not sure if this started with the release of v1.9.0 or v1.9.1. I was definitely debugging with breakpoints in v1.8.x. Not sure how to solve this issue. I am using gulp, I don't know if that makes a difference for debugging as I am using the given configuration from vscode's debug configuration.

    OS : macOS Sierra 10.12.3
    vsCode : v1.9.1
    node : v7.5.0 and v6.9.5
    using port : 8080

`launch.json`

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Gulp default",
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}/node_modules/gulp/bin/gulp.js",
            "args": [
                "default"
            ]
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858
        }
    ]
}
```

**Comment by wgv-sethlivingston** [comment] 2017-03-06 23:43
{ "restart": true } was the secret sauce for me, too.

**Comment by jrwiegand** [comment] 2017-03-09 18:18
The debugger stopped working again and I did a little bit more digging. I found that the protocol using inspector to fix the situation (`"protocol": "inspector"`). So the current version I have is the following: 
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/server.js",
            "cwd": "${workspaceRoot}",
            "restart": true,
            "protocol": "inspector"
        }
    ]
}
```

However, even with this change the gulp tasks are not working.

**Comment by lidderupk** [comment] 2017-03-24 19:09
Hi, 

The debugger stopped working for me all of a sudden. I have uninstalled recent extensions hoping that will fix it. Here is launch.js

```
"configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/app.js",
            "cwd": "${workspaceRoot}",
            "restart": true,
            "protocol": "inspector"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "address": "localhost",
            "port": 5858
        }
    ]
```
I am trying to debug app.js. Thank you.

**Comment by weinand** [comment] 2017-04-06 12:33
Since there are so many "me too" reports piggy-backed on this issue, I can no longer follow them in details and I'm closing the issue.

If you still experience your problem in VS Code 1.11.0, please create a new issue with detailed steps.

**Closed by weinand** 2017-04-06 12:33 UTC
Labels: debug

**Comment by timhuff** [comment] 2017-08-12 03:31
I just ran into this issue. Another solution to try, future reader: For me, it ended up being that I hadn't properly capitalized a letter in my require statement. Breakpoints in the test worked fine but not in the required file. It ran the code, even with the messed up caps, but didn't stop at the breakpoint.

**Comment by GerryFudd** [comment] 2017-11-14 22:42
"Since there are so many "me too" reports piggy-backed on this issue, I can no longer follow them in details and I'm closing the issue."

That's an option?  Doesn't the number of me too comments indicate that this is a serious problem that is very much not resolved?

**Comment by weinand** [comment] 2017-11-14 22:49
No, most of the "me too"s are unrelated to the original issue and should have been filed as separate issues.

If you have another "me too" please file a new issue and we will investigate.

I'm locking this issue now.
