### ISSUE TITLE
Weird characters on vscode editor

### ISSUE THREAD

**Issue by siarsu** [Microsoft/vscode#38302] opened 2017-11-14 08:09 UTC
Since a few days, there are weird characters and small dots visible among the text in visual studio code 1.18 running on debian 9. I have tried to show a few weird characters and dot by using arrows in the attachment. I already have disabled extensions and restarted the vscode, but that didn't change anything.

 
![screenshot from 2017-11-14 08-48-01](https://user-images.githubusercontent.com/16521349/32769140-f7e986ac-c91a-11e7-8683-d766a8f67077.png)

**Comment by mboret** [comment] 2017-11-14 09:35
Same issue since the upgrade from the version 1.14.2 to 1.18.

**Comment by alexandrudima** [comment] 2017-11-15 09:47
Duplicate of #35675

**Closed by alexandrudima** 2017-11-15 09:47 UTC
Labels: editor, editor-core
