### ISSUE TITLE
Markdown Preview not launching

### ISSUE THREAD

**Issue by j-james** [Microsoft/vscode#68573] opened 2019-02-12 22:33 UTC
- VSCode Version: 1.31.0
- OS Version: Manjaro 18.0.2 Illyria

Steps to Reproduce:

1. Install VS Code
2. Open a Markdown file
3. Click either the "Open Preview to the Side button" or right-click on the file and select "Open Preview". 

Clicking the button gives me a `command 'markdown.showPreviewToSide' not found` error.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment] 2019-02-12 22:39
Duplicate of #68354

**Closed by mjbvz** 2019-02-12 22:39 UTC
Labels: markdown
