### ISSUE TITLE
macOS: ActivityBar color customization slightly broken.

### ISSUE THREAD

**Issue by JulianSchoenbaechler** [Microsoft/vscode#57694] opened 2018-08-31 14:28 UTC
On macOS, if the icons of the activity bar are color customized (`activityBar.foreground`) through a theme or manually in the settings, they'll disappear completely. I could reproduce this issue only on mac.

- VSCode Version: 1.26.1
- OS Version: macOS 10.13.6 (High Sierra)
---

Steps to Reproduce:

1. Add the following to the users/workspace settings:
```
"workbench.colorCustomizations": {
    "activityBar.foreground": "#ff00ff",
},
```
2. The icons of the activity bar are now gone:
![screen shot 2018-08-31 at 16 05 39](https://user-images.githubusercontent.com/10711264/44917143-d7323b00-ad37-11e8-9ac7-fc6460ac14e6.png)
3. When Visual Studio Code gets restarted, the icons will appear in the specified color for a fraction of a second only to disappear again.
4. On inspecting the CSS, the color has been applied, but there seems something other going on there too. If I remove the CSS property `will-change: transform;` of the `<a>` tag inside the list element of the activity bar manually, the icons show up again:
![screen shot 2018-08-31 at 16 25 01](https://user-images.githubusercontent.com/10711264/44918160-97b91e00-ad3a-11e8-8fd4-b7ebe3a45547.png) ![screen shot 2018-08-31 at 16 25 24](https://user-images.githubusercontent.com/10711264/44918167-9ab40e80-ad3a-11e8-9460-032577eec903.png)
---

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-09-01 05:58
@JulianSchoenbaechler is that with the standard dark+ theme? I cannot reproduce. The code you mention was only added to fix issues with the Electron 2.0.x release. We will take it out once we go to 3.0.x. We have builds ready for you to try that:

Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by JulianSchoenbaechler** [comment] 2018-09-01 12:14
Yes, this is with the standard dark+ theme. 
I took some deeper investigation and found out that it has to do with the hardware acceleration of the system. I'm on an old MacBook Pro that dynamically switches between the internal Intel HD Graphics and an old Nvidia gt300m. Rendering VSCode on the integrated GPU will produce this issue, while switching to the graphics card will display everything correctly.

However, the attached builds using the new Electron version seem to fix this issue, thank you for that!

**Comment by bpasero** [comment] 2019-01-25 16:24
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-01-25 16:24 UTC
Labels: electron, electron-2.0.x-update, fixed-in-electron-3.0.x, upstream
