### ISSUE TITLE
Very laggy/slow scrolling with larger files

### ISSUE THREAD

**Issue by daver99** [microsoft/vscode#109193] opened 2020-10-22 20:54 UTC
Issue Type: <b>Bug</b>

Load a text file that is 15000+ lines long.  Use the scrollbar or cursor to scan up and down.  It is very slow compared to other editors to update.  Use the keyboard to pageup/down there is a noticable lag from button release to screen update (I'd guess 150ms-200ms)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.77GB free)|
|Process Argv|--crash-reporter-id 1d21116e-b9f1-47ae-88d3-35155b64febe|
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by alexdima** [comment] 2020-10-26 13:26
I think this might be a duplicate of #107016

Does the slowness reproduce when closing all instances and launching with `code.exe --disable-renderer-accessibility` ?

**Comment by daver99** [comment] 2020-10-26 22:53
Yes -- thank you - that command line parameter does vastly improve the
situation.
Regards,
dR

**Closed** 2020-10-27 07:50 UTC
Labels: needs more info
