### ISSUE TITLE
Forced Strikethrough on word 'name' in simple console.log statement

### ISSUE THREAD

**Issue by SUBHADIPLAYEK** [microsoft/vscode#144054] opened 2022-02-28 08:40 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.const nam = prompt("Enter your name to join");
socket.emit('new-user-joined',name);
2.When I type that code into my vs code, vs code forces the word 'name' in the console.log statement to have a strike through. It only happens with the word 'name'. I can type any other word and no strikethrough.
the problem is like this: 
const name: void
@deprecated

'name' is deprecated.ts(6385)
[lib.dom.d.ts(17177, 5): ]()The declaration was marked as deprecated here.

**Comment by gjsjohnmurray** [comment] 2022-02-28 10:18
Maybe set `"editor.showDeprecated": false`

**Comment by IllusionMH** [comment] 2022-02-28 11:37
/duplcate of #117401

See comments there and linked issues/comments for details.

**Comment by IllusionMH** [comment] 2022-02-28 11:37
/duplicate of https://github.com/microsoft/vscode/issues/117401

See comments there and linked issues/comments for details.

P.S. Sorry for second notification

**Closed** 2022-02-28 11:38 UTC
Labels: *duplicate
