### ISSUE TITLE
Adding jsdoc type breaks hover positions

### ISSUE THREAD

**Issue by DannyMeister** [Microsoft/vscode#61199] opened 2018-10-18 04:52 UTC
When I add a jsdoc type annotation it is breaking the position for hover for all identifiers after it in the .js file.  The number of remaining characters within the comment following `/** @type` seems to the amount that the character position is off by.  The problem persists until vscode is closed and reopened.

![jsdoc_hover_pos](https://user-images.githubusercontent.com/7937829/47131947-1aecef80-d267-11e8-8b3a-e891785947b9.gif)

Issue confirmed present with all extensions disabled.

Version 1.28.2

**Comment by mjbvz** [comment] 2018-10-18 15:57
Duplicate of https://github.com/Microsoft/TypeScript/issues/27471 I believe

Try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) to see if https://github.com/Microsoft/TypeScript/pull/27343 fixed the problem

**Closed by mjbvz** 2018-10-18 15:57 UTC
Labels: javascript
