### ISSUE TITLE
How to append more folder into the workspace?

### ISSUE THREAD

**Issue by Ltre** [Microsoft/vscode#17522] opened 2016-12-19 09:04 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eclipse-keybindings|alphabotsec|0.8.0|
|tortoise-svn|fantasytyx|0.1.1|
|php-intellisense|felixfbecker|0.0.12|
|composer|ikappas|0.5.0|
|material-icon-theme|PKief|1.1.5|

---

Steps to Reproduce:

1. How to append more folder into the workspace?  I dont't like open multiple window to edit project

**Comment by Ltre** [comment] 2016-12-19 09:08
。。。 such as multiple folder from Sublime Text Editor

**Comment by kumarharsh** [comment] 2016-12-19 09:22
I don't think you can.

**Comment by Ltre** [comment] 2016-12-19 09:32
HOW TO SUPPORT IT?

**Comment by f111fei** [comment] 2016-12-19 10:11
it's in roadmap.

https://github.com/Microsoft/vscode/wiki/Roadmap

Multiple folders inside a single workspace

**Comment by egamma** [comment] 2016-12-19 10:31
Yes it is on the roadmap and it is a duplicate of #396

**Closed by egamma** 2016-12-19 10:31 UTC
Labels: duplicate
