### ISSUE TITLE
VSCODE WSL can't handle small/capital letters, in the same folder.

### ISSUE THREAD

**Issue by itsAnuga** [microsoft/vscode#195655] opened 2023-10-15 11:56 UTC
Type: <b>Bug</b>

Using WSL to simulate Ubuntu environment.

Having these two folders:
/srv/Ghost
/srv/ghost

Doing : "code /srv/Ghost", works.
Doing : "code /srv/ghots", afterwards and it "reopens" "/srv/Ghost".

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (6.23GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/srv/ghost --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics (16 x 3293)|
|Memory (System)|7.46GB (6.29GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-handlebars-ext|Its|1.0.1
remote-wsl|ms-|0.81.8
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
vsc-handlebars-ext|Its|1.0.1
sass-indented|syl|1.8.28

</details>

**Comment by aeschli** [comment] 2023-10-16 12:29
It's a known issue that we have with all types remote windows. n open, we don't know yet what OS the remote window has and treat the filesystem as case insensitive.
Duplicate of https://github.com/microsoft/vscode/issues/123421

**Closed by aeschli** 2023-10-16 12:29 UTC
