### ISSUE TITLE
Increase the number of recents from 100

### ISSUE THREAD

**Issue by github-account1111** [microsoft/vscode#128965] opened 2021-07-19 03:06 UTC
I used to think there was a bug in VSCode where it would "forget" recent files randomly. I've just realized that this happens by design.

There's a list of what looks like about 100 items, and once it overflows, the bottom item is discarded. Any reason for this behavior? Other than trying to conserve space - which is obviously a non-issue given it's just a text entry, so won't make a dent on any semi-modern computer's drive even if it were multiplied a thousand-fold. On the other hand, I've always found it frustrating to have to dig through the system with File Explorer to search for a file, when I could've easily opened it with Ctrl-r (given I've opened it in the past).

**Comment by github-account1111** [comment] 2021-08-05 10:27
If it doesn't get 20 upvotes can I resubmit?

**Comment by github-account1111** [comment] 2021-08-21 02:22
Following up.

It doesn't look like 20 upvotes are happening. Can I resubmit if it doesn't get there?

**Comment by vanenshi** [comment] 2021-09-05 14:58
duplicate of #131708

**Comment by github-account1111** [comment] 2021-09-06 00:18
How is this a duplicate? I opened this almost 2 months ago, while the one you linked is 11 days old. Maybe the other way around?

**Comment by TylerLeonhardt** [comment] 2021-09-28 16:05
@github-account1111 you're right it's technically the other way around but the other issue has more context so let's dupe this one to that and keep that one open.

**Closed by TylerLeonhardt** 2021-09-28 16:05 UTC
Labels: feature-request, workbench-history
