### ISSUE TITLE
tmux pane_current_path is duplicated

### ISSUE THREAD

**Issue by Mellbourn** [Microsoft/vscode#28564] opened 2017-06-12 20:59 UTC
- VSCode Version: 1.13.0 (1.13.0)
- OS Version: MacOS 10.12.5
- extensions: occurs even when I run code with `--disable-extensions`

Steps to Reproduce:

1. put this in `.tmux.conf`:
```
set -g pane-border-format "#{pane_index} #{pane_current_path} "
setw -g pane-border-status bottom

```
2. start a terminal in VSCode
3. in the terminal start tmux
```
tmux new-session -s test
```

Now, in the pane status line I expect to see the current path, e.g. `-0 /Users/klas.mellbourn ---`. 

Instead it looks like this `-/Users/klas.mellburn-0 /User/klas.mellbourn ---`. 
It seems that the current path and a dash is prepended to the expected pane title.

This occurs for both `bash` and `zsh`.

This occurs _only_ for the first pane. If I split the tmux session into to panes beside each other, the second pane gets the expected title `-1 /User/klas.mellbourn --`. However, the title for the second pane is positioned incorrectly horizontally. It is offset to the right by the size of the string `/Users/klas.mellbourn` as if tmux did not expect it to be shown.

This occurs _only_ within Visual Studio code. The pane title behaves just as expected in terminals (such as `iTerm` or the built in `terminal`) outside Visual Studio Code.

**Comment by ramya-rao-a** [comment] 2017-06-12 21:13
Duplicate of #26038

cc @Tyriar

**Closed by ramya-rao-a** 2017-06-12 21:13 UTC
Labels: new release
