### ISSUE TITLE
Terminal full black

### ISSUE THREAD

**Issue by vikpascual** [microsoft/vscode#187198] opened 2023-07-06 21:17 UTC
Type: <b>Bug</b>

I dont know how to reproduce this bug. I just restart VSCode after last update. This happens with powershell, git bash and python debug terminal. I disabled GPU acceleration but nothing changed.
![image](https://github.com/microsoft/vscode/assets/44240169/4b84efd7-08c8-49a8-a463-8dcb6760aa08)

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.24GB free)|
|Process Argv|--crash-reporter-id e61d592b-9712-4e12-b33c-5612294180e7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
node-js-snippet|abd|1.1.3
javascript-ejs-support|Dig|1.3.3
jquerysnippets|don|0.0.1
code-runner|for|0.12.0
prettify-json|moh|0.0.3
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.7.10
jupyter|ms-|2023.6.1001861915
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.16.3
bootstrap4-vscode|the|6.1.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
cmakesidepanelv2:30779593

```

</details>

**Comment by Kidsunbo** [comment] 2023-07-07 09:45
I have met this bug as well after upgrading to 1.80.0. 
The way I reproduce this is to 
1. start a docker container of ubuntu
2. connect to the container with dev-container
3. start a new C++ project with CMake extension
4. just compile and run.
5. closing all the terminal
6. start a new terminal
From now on, the terminal is full black. But I could still start the terminal with '+' icon. It can be fixed by restart vscode. I hope this imformation could be helpful.

**Comment by vikpascual** [comment] 2023-07-07 11:18
The first thing I did was to close all terminals and create new ones with the '+' symbol. The new terminals were experiencing the same issue. Then, I restarted VSCode and created new terminals again, but they still had the same problem.

**Comment by tjx666** [comment] 2023-07-07 19:37
After updated latest, I also occur this issue sometime.

```
Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:40:17.963Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by wulling1024** [comment] 2023-07-08 00:09
I'm also having this issue, can it be fixed recently @meganrogge

**Comment by tjx666** [comment] 2023-07-08 05:22
seems this always happen after my mac sleep long time

**Comment by vikpascual** [comment] 2023-07-08 07:49
After uninstalling and installing VSCode the problem persists.  Terminal works but I can see nothing.
![image](https://github.com/microsoft/vscode/assets/44240169/e43724b5-944d-4cb1-b6f1-185358b5b495)

**Comment by jerch** [comment] 2023-07-09 19:26
Plz also check if the issue goes away after disabling terminal image support:
```json
"terminal.integrated.enableImages": false
```

@Tyriar I remember a similar issue happened  when tabby integrated image support for the first time, but I had no chance to verify, as the reporter never answered in the issue thread. Could that be some electron/chrome gpu driver issue not being able to do transparent composition, and thus falling back to just a black canvas? Note that I never experienced that myself, so I am not even sure, if it is related to the image addon at all.

**Comment by JoonChicken** [comment] 2023-07-09 20:22
@jerch That fixed the problem for me.

**Comment by vikpascual** [comment] 2023-07-10 07:20
That fixed the problem for me too. Can I close this thread?

**Comment by jerch** [comment] 2023-07-10 07:26
Thx for the confirmations. I cannot really help to further debug this with electron/vscode, as I dont know how things like --disable-gpu or chrome://gpu play into this for electron. I also cannot repro it with any device I have access to. 

It pretty much smells like a driver issue with degraded transparent canvas composition, as the image canvas is meant to be a transparent layer above the terminal text layer drawing image tiles on top. This normally works for all text layer renderer types (DOM, canvas or webgl2).

> Can I close this thread?

Imho it is better to keep it open for now, as the circumstances, when the canvas gets wrongly painted black instead of transparent, might need further investigation.

**Comment by vikpascual** [comment] 2023-07-10 07:38
Anyway, I always have GPU acceleration disabled because this other problem happens. I don't know if it will help you. 
![image](https://github.com/microsoft/vscode/assets/44240169/1d6b6898-9f3a-426e-8f5d-9eccbf35ed95)

**Comment by Tyriar** [comment] 2023-07-11 14:40
Bit late to join here but I'm thinking we should only allow images when the canvas or webgl renderers are being used, in other words, depending on `terminal.integrated.gpuAcceleration`.

@jerch do we need `{ alpha: true }` on any of these `getContext` calls?

https://github.com/search?q=repo%3Ajerch%2Fxterm-addon-image%20getcontext&type=code

The regular renderers are all opaque in VS Code so this canvas is a little special compared to them.

**Comment by jerch** [comment] 2023-07-11 14:52
Well this one here is def. needed, otherwise the transparent overlaying does not work: https://github.com/jerch/xterm-addon-image/blob/5f5bae8c5fc4fe5269e3025a4f96ace38fc300e1/src/ImageRenderer.ts#L311

All others are set to `alpha: false`, which should be the default setting anyway.

I am not sure, if the `desynchronized: true` creates further driver issues here, if so we can that remove it (runs abit slower in chromium without, but not much).

**Comment by Tyriar** [comment] 2023-07-11 14:54
I doubt `desynchronized` would cause problems, let's go with checking if the DOM renderer is being used and disable it in that case

**Comment by Tyriar** [comment] 2023-07-11 14:57
To clarify, this will be a VS Code-side change, so I'll unload the addon when DOM is used

**Comment by jerch** [comment] 2023-07-11 14:58
> To clarify, this will be a VS Code-side change, so I'll unload the addon when DOM is used

Yepp, sounds good.

**Comment by jerch** [comment] 2023-07-11 15:00
I also want to point out, that the issue #184894 is still open. The patch release 0.4.2 hopefully resolves that one.

**Closed** 2023-07-11 20:38 UTC
Labels: bug, regression, terminal-persistence

**Comment by jerch** [comment] 2023-07-13 09:21
@Tyriar Is this issue worth to be further investigated or even reported to chromium devs at some point? Not being able to use transparent canvas layering on some machines these days looks to me like a rather bold issue for the browser engine with the biggest marketshare.

Ofc this only makes only sense if you can track down the issue further, e.g. which platform + gpu settings are affected. I would suspect that their is a common pattern to be found in chrome://gpu for those machines, sadly chrome's gpu/canvas stack is quite convoluted with all sorts of software shims to fix this or that, so it might be hard to spot this pattern. Well idk if it is worth the extra rounds, maybe only if a bigger percentage of ppl are affected by it.

**Comment by Tyriar** [comment] 2023-07-13 14:54
@jerch if we could get a minimal repro we could, I wouldn't want to potentially waste their time without one though. We've always had a class of users where GPU acceleration just doesn't work, some need to move on to terminal's dom renderer, and some need to launch Electron with `--disable-gpu`.

**Comment by tjx666** [comment] 2023-07-14 20:02
I can still occur this issue in latest recovery1:

```
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:58.115Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by Kidsunbo** [comment] 2023-07-15 04:01
> @Tyriar
> 
> I can still occur this issue in latest recovery1:
> 
> ```
> Version: 1.80.1
> Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
> Date: 2023-07-12T17:20:58.115Z
> Electron: 22.3.14
> ElectronBuildId: 21893604
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Darwin arm64 22.5.0
> ```
> 
>  2023-07-15.04.04.27.mov

this might be another bug.

**Comment by 42n8dzydoo** [comment] 2023-07-21 15:25
I figured my dark terminal was caused by my old Nvidia driver. Yesterday, they released a new update and the terminal was perfectly okay after.

Thanks y'all
