### ISSUE TITLE
I can't open powershell in vscode

### ISSUE THREAD

**Issue by reaCodes** [Microsoft/vscode#66248] opened 2019-01-09 01:28 UTC
- VSCode Version:1.30.2
- OS Version:windows 10 1809

Steps to Reproduce: Using <ctrl+~> to open the terminal

Phenomenon:
![image](https://user-images.githubusercontent.com/13817254/50869809-91c20080-13f0-11e9-8e53-9845462581e8.png)
powershell can't be opened, I can't enter something

This problem does not only occur in this version, this problem has existed in several previous versions.

Does this issue occur when all extensions are disabled?: Yes

**Comment by MicahZoltu** [comment] 2019-01-09 08:13
I have the same problem.  If you click inside the terminal and press enter then you can see the prompt.  It is there, just not displaying.

**Comment by reaCodes** [comment] 2019-01-09 12:05
@MicahZoltu 
Yes. When I press enter, I can input the command.
I also found a phenomenon, when I opened vscode for the first time after restarting my computer, use 'ctrl+~' can open powershell in terminal smoothly

**Comment by RMacfarlane** [comment] 2019-01-09 18:02
Duplicate of https://github.com/Microsoft/vscode/issues/57803

**Closed by RMacfarlane** 2019-01-09 18:02 UTC
Labels: *duplicate, new release
