### ISSUE TITLE
Scrolling jumps on minimap in bigger files

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode#22008] opened 2017-03-05 12:49 UTC
- VSCode Version: 1.10.1
- OS Version: Windows 10

In bigger files in terms of line count the minimap jumps on dragging. See attached GIF.
![2017-03-05_13-47-57](https://cloud.githubusercontent.com/assets/9491603/23587359/8a945394-01aa-11e7-81aa-9fe42c19cf1f.gif)

**Comment by blazej-p** [comment] 2017-03-09 08:33
Same behaviour occurs in:

-VSCode 1.10.2
-macOS Sierra 10.12

**Comment by deltaskelta** [comment] 2017-03-09 11:55
Upvoted original answer, this is extremely annoying and jarring, because it snaps my brain away from the lines of code I am reading and then I have to take a few seconds to find my place again.

macOS Sierra 10.12.3
VSCode 1.10.1

**Comment by Nderim1** [comment] 2017-03-27 13:19
![vscode_minimap](https://cloud.githubusercontent.com/assets/15191094/24358197/a6ab7870-1300-11e7-8212-889aba5adbb4.gif)

Same problem here. It's almost unusable.

**Comment by alexandrudima** [comment] 2017-06-07 14:23
Duplicate of #21346

**Closed by alexandrudima** 2017-06-07 14:23 UTC
Labels: bug, editor-minimap
