### ISSUE TITLE
Watcher ignores frequent changes to the same file

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [microsoft/vscode#139866] opened 2021-12-29 02:56 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 (user setup)
- OS Version: Win10.0.19042.1110

basically, this issue re-occured: #22266

Steps to Reproduce:

What I did in the gif below
1. open a folder
2. spawn a `ping -t` command and redirect its output to a file, `ping -t` will never stop and output one line to stdout every second
3. open the file
4. the editor should refresh, at least once per second, with one new line each time, to display the latest file content, but its not

![bug](https://user-images.githubusercontent.com/12868093/147622935-24da3863-03d5-411b-9c9a-d82324ef638f.gif)

And no, the latest insider version also have this problem.

And its not because of output buffering, when you manually switch to another editor tab and back, the file is refreshed.

This issue also occured in VSCode remote-ssh session.

**Comment by bpasero** [comment] 2021-12-29 08:35
This is likely caused by what was reported by https://github.com/parcel-bundler/watcher/issues/70 already. Though I cannot reproduce this issue when changing the sample in that issue to write every second, so not sure what `ping` does any different. But I can also reproduce on macOS.

**Comment by bpasero** [comment] 2021-12-31 07:53
I did some testing on both macOS and Windows and I cannot explain what the `ping` command does exactly, but I see no file events generated from:
* `FSEventStreamCreate` (macOS)
* `ReadDirectoryChangesW` (Windows)

When piping the output of `ping` command into a file. Given the underlying OS libraries do not report a file change event, our file watcher cannot do anything about it.

Even a 3rd party tool such as http://www.nirsoft.net/utils/folder_changes_view.html only reports a single file change event.

Closing as wontfix.

**Closed by bpasero** 2021-12-31 07:53 UTC
Labels: bug, upstream, file-watcher, upstream-issue-linked

**Comment by MichaelSuen-thePointer** [comment] 2021-12-31 09:32
@bpasero  wait! this is not a problem that only occurs 'magically' on ping, every program that uses stdout redirect have the same problem, for example a simple shell script `bash -c "while true; do echo 1; sleep 1; done" > out.txt` or even ` yes > out.txt` have the same problem!

**Comment by bpasero** [comment] 2021-12-31 09:53
@MichaelSuen-thePointer sure, I suspect this is all the same underlying issue with redirecting std-out, I wasn't thinking that the `ping` command is doing anything special because it doesn't even attempt to write to the file.

Again, if the OS does not report change events, then we cannot do anything about it. I am sure you will find the same issues with other watchers unless they actually do stat polling over a interval.

**Comment by MichaelSuen-thePointer** [comment] 2022-01-03 04:11
@bpasero Can I just switch back to the old polling based file watcher? It works well just before VSCode switch to the new OS API based file watcher.

**Comment by bpasero** [comment] 2022-01-03 08:17
We have never used a polling based file watcher unless you are connected to WSL via Windows where we still use a polling based watcher only.
