### ISSUE TITLE
vscode node debugger parses inline sourcemap incorrectly

### ISSUE THREAD

**Issue by t83714** [Microsoft/vscode#35978] opened 2017-10-10 09:44 UTC
- VSCode Version: 1.17.0 
- OS Version: macOS 10.13

Steps to Reproduce:

1. Create an empty folder
2. Add `package.json` with the following content:
```
{
  "name": "vscode-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@std/esm": "^0.11.3"
  },
  "@std/esm": {
    "esm": "all",
    "cjs": true
  }
}
```
3. Create file `index.js` with the following content:
```
import path from "path";

console.log(path.resolve(__dirname, ".."));
```
4. Configure launch.json as:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/index.js",
            "runtimeArgs": [
                "-r","@std/esm"
            ]
        }
    ]
}
```
5.  `npm install`
6. Press F5 to start vscode debugger
7. You will see the following error:
```
Debugging with inspector protocol because Node.js v8.6.0 was detected.
node --inspect-brk=36570 -r @std/esm index.js 
Debugger listening on ws://127.0.0.1:36570/a572c7ff-3251-4ae3-b74c-5abe01c3b73c
Debugger attached.
SourceMaps.getMapForGeneratedPath: exception while processing path: /Users/user/Development/vscode-issue/index.js, sourcemap: data:application/json;charset=utf-8,%7B%22version%22:3,%22sources%22:%5B%22/Users/user/Development/vscode-issue/index.js%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAAA;AACA;AACA%22%7D
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:20:25)
    at sourceMapContentsP.then.contents (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapFactory.js:53:28)
    at <anonymous>
```

Reproduces without extensions: Yes

It seems vscode debugger always assumes the inline sourcemap data URI is in base64 encoding (even if the `;base64` extension is not included in the data URI scheme).

This will lead to data decoding error.

**Comment by jdalton** [comment] 2017-10-10 14:21
Related to this line:
https://github.com/Microsoft/vscode/blob/407ce43a5e0bb079b3d0db802a2f7367c2f97c99/build/lib/util.js#L146

**Comment by roblourens** [comment] 2017-10-11 15:02
I didn't know that was valid. `convert-source-map` isn't involved at all, as far as I know. I just need to update https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/sourceMaps/sourceMap.ts#L81

**Comment by jdalton** [comment] 2017-10-11 16:51
Oh, rad! Yep, it's allowed. See for more info:
https://github.com/thlorenz/convert-source-map/issues/59#issuecomment-335552857

**Comment by ramya-rao-a** [comment] 2018-03-01 21:16
@roblourens Moving to March since you are not here ...

**Comment by roblourens** [comment] 2018-07-17 16:22
Is this format commonly used?

I think the right fix will be to take a dependency on that `convert-source-map` package.

**Comment by jpike88** [comment] 2018-07-17 17:31
Some more side information here:

The issue is the inlined source maps aren't being encoded properly. Here is the issue present in getMapForGeneratedPath, and what I see is that the mapPath has HTML entities used which throws everything off.

![screen shot 2018-07-18 at 12 16 19 am](https://user-images.githubusercontent.com/9585787/42833956-d248e6b0-8a1f-11e8-89d1-9c6834d66223.png)

Going up the stack trace... It's present in onScriptParsed in chromeDebugAdapter.js...

![screen shot 2018-07-18 at 12 29 17 am](https://user-images.githubusercontent.com/9585787/42834741-af4d0220-8a21-11e8-90f3-f54765bd9d66.png)

**Comment by jpike88** [comment] 2018-07-17 17:33
Still not sure why this issue popped up... I updated a fair amount of dependencies and this happened. Does this have to do with a recent typescript update? Does anyone know of workarounds to this?

**Comment by jpike88** [comment] 2018-07-17 17:35
Ohhh it might have been updating @std/esm! If anyone is having this issue downgrading that will probably help things.

**Comment by jpike88** [comment] 2018-07-17 17:39
confirming that downgrading to esm@3.0.18 reversed this issue.

**Comment by jpike88** [comment] 2018-07-17 17:41
@jdalton would you happen to know the latest non-breaking version of esm that won't re-trigger this issue?

**Comment by roblourens** [comment] 2018-07-17 17:59
The encoding is valid, I just haven't gotten to supporting it since it doesn't seem to be very common.

**Comment by jpike88** [comment] 2018-07-18 02:58
The error is really obscure though, it might be worth putting in a note regarding this in the error output.

**Comment by jdalton** [comment] 2018-07-18 16:48
I'll prep a PR to patch [getInlineSourceMapContents()](https://github.com/Microsoft/vscode-chrome-debug-core/blob/9d2d033134fcf46426c27dce5759cc0fba940c9d/src/sourceMaps/sourceMapFactory.ts#L65-L81) with support for utf-8 encoded source mapping urls.

**Comment by roblourens** [comment] 2018-07-18 17:48
That would be fantastic, thanks.

**Comment by roblourens** [comment] 2018-07-19 16:20
@Pokute beat you to it but I'll get this into tomorrow's Insiders build.

**Closed by roblourens** 2018-07-19 16:20 UTC
Labels: debug, feature-request

**Comment by remcohaszing** [comment] 2018-08-09 11:10
I just ran into this issue using VSCode 1.25.1. Just checking… should this fix have been released yet?

**Comment by jpike88** [comment] 2018-08-09 14:41
@remcohaszing its in insiders build, not released to the public yet
