### ISSUE TITLE
VS Code should restore windows to their original spaces when possible

### ISSUE THREAD

**Issue by nchammas** [microsoft/vscode#979] opened 2015-12-03 17:49 UTC
I have `"window.reopenFolders": "all"` set, and when I restart VS Code it correctly restores all the folders I had open. However, it restores them to the same OS X [space](https://support.apple.com/kb/PH18757?locale=en_US), as opposed to the spaces they were originally in.

When VS Code is restarted it should try to restore the windows that were open to the spaces they were originally in.

**Comment by bpasero** [comment] 2015-12-04 09:19
Have to check if there is API in Electron to find out about spaces.

**Comment by bpasero** [comment] 2016-12-12 11:05
From: https://github.com/Microsoft/vscode/issues/16991

### Steps to Reproduce:

1. [Create multiple Spaces](https://support.apple.com/kb/PH21872) for the current User.
2. Open Visual Studio Code on macOS (any version 10.7+).
3. Open a Folder (or new window) multiple times: once, at least, in each Space you created in Step 1.
    - Ensure you have the `window.reopenFolders` [setting](https://code.visualstudio.com/docs/editor/codebasics#_window-management) set to `all`.
4. Perform one of the following [_Sudden Termination_](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW22) actions:
    1. **Logout** of the current User. Log back into the same user.
    2. **Shut Down** the computer. Turn the computer back on.
    3. **Restart** the computer.

### Expected Results:

Visual Studio Code's windows restore to the Spaces they were in when the action in Step 4 took place.

### Actual Results:

Visual Studio Code restores all windows to the current Space (typically "Desktop 1") when the user is properly logged back in. They must be manually reassigned to the previous spaces.

### Errata:

- Compare Visual Studio Code's results with that of Apple's built-in applications: all windows of Apple-built apps correctly restore to the Space they existed in prior to the `Sudden Termination` event.
- Apple _does_ offer the ability to [**Assign apps to Spaces**](https://support.apple.com/kb/PH21872). However, this only adjusts what Space the Windows start in. If a user intentionally moves the windows to different Spaces then all Windows would recollect to _that_ space upon restart instead of the previously assigned Space (as expected). In short, this is not a solution to the problem.
- **Use Case:** A developer creates three Spaces and opens a folder in a unique Visual Studio Code window on each Space. These Spaces serve different development contexts for the developer. When restarting (say from OS update), the developer expects the windows to restore to the previously used Space.
- According to _Apple Developer Relations_, apps that wish to support this feature must "use NSWindow’s [encodeRestorableStateWithCoder:](https://developer.apple.com/reference/appkit/nsresponder/1526236-encoderestorablestatewithcoder) and [restoreStateWithCoder:](https://developer.apple.com/reference/appkit/nsresponder/1526253-restorestatewithcoder)" (those APIs are part of [NSResponder](https://developer.apple.com/reference/appkit/nsresponder)). This is also somewhat outlined [here](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26).

**Comment by nchammas** [comment] 2016-12-12 13:35
@ericdrobinson - I find that this problem exists even if I restart VS Code normally (i.e. not a sudden termination event). For example, when VS Code restarts to upgrade itself, I have to manually reassign all the windows I had open to their correct Space.

**Comment by ericdrobinson** [comment] 2016-12-12 14:27
@nchammas: 
> when VS Code restarts to upgrade itself, I have to manually reassign all the windows I had open to their correct Space.

This, unfortunately, is not something that is supported by macOS - it is a failing on Apple's side, not Visual Studio Code. It turns out that macOS _only_ supports Spaces restoration on a reboot. You can test this yourself with Apple's built-in applications (e.g. Safari, Text Edit, Terminal, Quicktime, etc.). In simple application-restart scenarios, Apple's application windows _do_ restore the previous visual state (as much as possible), but they **_do not_** properly restore previously used Spaces.

With respect to your initial comment:
> Chrome, for example, does this correctly ~most~ some of the time.

This is 100% false. Current versions of Chrome will _always_ restore to the default Space (typically Desktop 1) unless you've specifically assigned it to a Space through the Dock interface. [This](https://bugs.chromium.org/p/chromium/issues/detail?id=74812) is a link to the Chromium Bug report that describes this issue for that application. [This comment](https://bugs.chromium.org/p/chromium/issues/detail?id=74812#c56) outlines the difference between simple "App Restart" and "System Reboot" in terms of what's supported.

The thread linked above has a lot of good information about this issue with respect to OS-integration and expectations. If you wish macOS would support Space reassignment on basic Application Restart, I'd suggest filing a [bug report with Apple](http://bugreport.apple.com/). The more of us that do so, the more likely they will be to enable it.

**Comment by nchammas** [comment] 2016-12-12 15:00
> This is 100% false. Current versions of Chrome will always restore to the default Space (typically Desktop 1) unless you've specifically assigned it to a Space through the Dock interface.

I believe you are correct. I will remove that comment from my original post.

> If you wish macOS would support Space reassignment on basic Application Restart, I'd suggest filing a bug report with Apple. The more of us that do so, the more likely they will be to enable it.

Is there no existing bug report we can just watch or add a +1 to? Otherwise, yes, I'll file a report assuming that's the appropriate thing to do.

**Comment by ericdrobinson** [comment] 2016-12-12 15:46
>Is there no existing bug report we can just watch or add a +1 to?

I've looked but have not found an open bug tracker for Apple. There are bug report numbers mentioned in the Chromium Tracker comment I linked above, but I do not think you can reference those unless you have internal access to Apple's bug report system.

If anyone knows of a better way to affect change with Apple's development team, I'd love to hear it...

**Comment by nchammas** [comment] 2017-07-21 19:35
@ericdrobinson - There is a [recent comment](https://bugs.chromium.org/p/chromium/issues/detail?id=74812#c77) on that Chromium bug report stating that Apple offers a way to support space restoration via a [_restoration class_](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26). I don't know if this is a new feature or if I just misunderstood its relevance to this issue here.

@bpasero - Should I file an issue about this on the Electron tracker?

**Comment by ericdrobinson** [comment] 2017-07-21 20:02
Just did a quick bit of sleuthing and found [this issue](https://github.com/electron/electron/issues/5362) that seems _somewhat_ related. I'd argue that if a version of this issue makes sense on the Electron tracker, then it should be a new one. Fixing this issue wouldn't imply the addition of a "Workspace API", but would require handling of an OS-specific feature (implementing a portion of the macOS [User Interface Preservation](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26)).

**Comment by nchammas** [comment] 2017-07-26 19:46
Filed an issue on the Electron tracker here: https://github.com/electron/electron/issues/10124

**Comment by bpasero** [comment] 2019-10-10 15:51
The upstream issue has been closed as wontfix. That means, same here, sorry.

**Closed** 2019-10-10 15:51 UTC
Labels: *out-of-scope, electron, feature-request, upstream, workbench-window

**Comment by ericdrobinson** [comment] 2019-10-11 16:25
@bpasero Hilariously, the über-upstream issue (in Chromium) was actually fixed on September 30th. I've [posted](https://github.com/electron/electron/issues/10124#issuecomment-541131517) in the _upstream_ issue with clarification on whether that fix will affect Electron or not. Fingers are crossed, but this may become feasible once Electron updates to a Chromium version that contains the fix...

**Comment by anentropic** [comment] 2022-03-11 11:08
despite whatever issues there maybe with the facilities provided by macos, iTerm and Sublime Text seem to manage to do this, as well as Chrome

**Comment by gavofyork** [comment] 2023-03-03 13:16
Then surely this should now be reopened.

**Comment by ericdrobinson** [comment] 2023-03-03 19:45
@gavofyork What are you referring to?

@bpasero Can you please consider reopening this issue? It seems awkward to allow #152869 to remain open while this one is closed.

What's more, while the "upstream" issue (electron/electron#10124) was closed, another Electron maintainer (@MarshallOfSound) [has suggested](https://github.com/electron/electron/issues/15211#issuecomment-430528749) that this feature is something that apps (e.g. VS Code) can directly implement themselves:

> This is something apps can implement (by saving window location on quit and restoring on start)

As such, the "upstream" issue wouldn't necessarily even be a blocker in the first place.

Can you please consider reopening this issue?

**Comment by bpasero** [comment] 2023-03-04 05:48
We track this still at https://github.com/microsoft/vscode/issues/123517

**Comment by ericdrobinson** [comment] 2023-03-04 06:56
> What's more, while the "upstream" issue (https://github.com/electron/electron/issues/10124) was closed, another Electron maintainer (@MarshallOfSound) https://github.com/electron/electron/issues/15211#issuecomment-430528749 that this feature is something that apps (e.g. VS Code) can directly implement themselves:
>
> This is something apps can implement (by saving window location on quit and restoring on start)
>
> As such, the "upstream" issue wouldn't necessarily even be a blocker in the first place.

I dug into this a bit and I now suspect that there is indeed no way for apps to implement this feature without upstream work. As such I have issued a [formal feature request in the Electron repository](https://github.com/electron/electron/issues/37494) for support for this.

I will also move future comments to #123517. Thanks for the heads up!
