### ISSUE TITLE
Terminal - Cannot read property 'className' of undefined

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11969] opened 2016-09-13 17:25 UTC
I've seen this a couple times now, and when it shows up, I can't open the terminal until I restart Code. I can't get devtools to load sourcemaps, though. It looks like the undefined element is `this.wrapperElement` in `setVisible`. 

```
Cannot read property 'className' of undefined: TypeError: Cannot read property 'className' of undefined
    at g (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:40:23049)
    at Object.b [as toggleClass] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:40:23693)
    at t.setVisible (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:124:1799)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:124:7359
    at Array.forEach (native)
    at e.setActiveInstanceByIndex (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:124:7335)
    at e.createInstance (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:124:6205)
    at t.run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:89:7797)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:95:3877
    at n.Class.define.then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:11045)
```

**Comment by roblourens** [comment] 2016-09-13 17:29
Actually, I see it every time I open code-insiders now

**Comment by Tyriar** [comment] 2016-09-13 20:42
@roblourens thanks for the quick report. This was caused by the refactor yesterday (#11839). Fix will be in tomorrow's insiders.

**Closed** 2016-09-13 22:05 UTC
Labels: bug, integrated-terminal
