### ISSUE TITLE
VS Code refuses to save a files with extensions it doesn't like

### ISSUE THREAD

**Issue by toh-ableton** [microsoft/vscode#102713] opened 2020-07-16 16:14 UTC
Issue Type: <b>Bug</b>

1. Open a C++ header file.
2. Press Cmd-Shift-S (File -> Save as).
3. Enter "File.ipp" as the filename.

Expected results:
VS Code saves the file as File.ipp

Actual results:
VS Code admonishes me 
```
You cannot save this document with extension ".ipp" at the end of the name. The required extension is ".hxx"
```

<img width="562" alt="Screenshot 2020-07-16 at 18 06 51" src="https://user-images.githubusercontent.com/5611555/87695653-0a491080-c790-11ea-82c6-d13e8b40150d.png">

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2191B CPU @ 2.30GHz (36 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2427

</details>

**Comment by bpasero** [comment] 2020-07-17 06:15
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by daiyam** [comment] 2020-07-21 13:52
Hi @bpasero,

I have the same issue. I've investigated and this issue appears since v1.46.0. and it's a regression introduced by https://github.com/microsoft/vscode/commit/61416238eafceb219c8ba2cc31d02ddecbb9e3a6

Before, the filters were `[allFilesFilter, matchingFilter, ...]`. Since `allFilesFilter` was first, no extension wasn't enforced.
Since this commit, the filters are `[matchingFilter, allFilesFilter, ...]`. Since `matchingFilter` is first, the existing extension is enforced.

**Comment by bpasero** [comment] 2020-07-21 14:21
@daiyam thanks a lot for finding out about this, I was not aware. Another thing to learn when dealing with the quirks of native file dialogs.....

**Closed** 2020-07-21 14:22 UTC
Labels: bug, dialogs

**Comment by Spectrik** [comment] 2020-08-03 12:09
Does VScode really try to dictate us what extension we must use? Where is our freedom??? JK ;) :D
