### ISSUE TITLE
Bump quickOpen suggestions from current workspace to the top

### ISSUE THREAD

**Issue by Telokis** [Microsoft/vscode#38128] opened 2017-11-11 20:03 UTC
- VSCode Version: 1.18.0
- OS Version: Windows 10 64

Steps to Reproduce:

1. Open multiple workspaces containing the same file name
2. Open a random file from a workspace
3. Hit Ctrl+P to trigger quickOpen inputbox
4. Start typing the name of the file you want
5. You will get lots of suggestions.
6. The currently open file should help VSCode determine which workspace to "prioritize" when there are multiple matches.

**Comment by roblourens** [comment] 2018-09-22 01:09
I think this can be technically a duplicate of https://github.com/Microsoft/vscode/issues/38128 - across workspace folders vs within a folder.

**Closed by roblourens** 2018-09-22 01:09 UTC
Labels: feature-request, quick-pick, search

**Comment by Telokis** [comment] 2018-09-22 09:42
@roblourens You linked to this issue!

**Comment by roblourens** [comment] 2018-09-22 17:00
Heh oops, I meant https://github.com/Microsoft/vscode/issues/5806
