### ISSUE TITLE
Incorrect selection change event kind when clicking on selection

### ISSUE THREAD

**Issue by jpotterm** [Microsoft/vscode#43282] opened 2018-02-09 03:58 UTC
### Environment
- VSCode Version: 1.20.0
- OS Version: macOS 10.13.3
- Does this issue occur when all extensions are disabled?: Yes

### Steps to Reproduce

Create an extension to log selection change events:

```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext): void {
    context.subscriptions.push(
        vscode.window.onDidChangeTextEditorSelection(function(e) {
            console.log('Selection changed:', e.kind);
        })
    );
}
```

Create a selection with the mouse, and then click somewhere within the selection. The selection change event that gets logged is of kind `3` (Command), but I would expect it to be of kind `2` (Mouse). Though it's not really documented exactly what the kinds mean, it seems like the Command kind is reserved for selection changes that come from `executeCommand` or `editor.edit`. See screencast:

![bug_screencast](https://user-images.githubusercontent.com/134310/36010851-a4bbe9a2-0d21-11e8-8069-f22b83000ea6.gif)

**Comment by jrieken** [comment] 2018-02-26 15:51
The API more or less forwards what the editor announces...

**Comment by alexandrudima** [comment] 2018-02-27 13:09
I believe in this case, the dnd functionality (which is in `/contrib/`) kicks in, so the selection changes indirectly via an editor mouse down listener. The dnd code calls back into the editor, and the editor marks the reason as `api`...

**Comment by alexandrudima** [comment] 2018-04-25 21:37
Duplicate of #30230

**Closed by alexandrudima** 2018-04-25 21:37 UTC
Labels: api, editor
