### ISSUE TITLE
Pressing "ctrl+shift+e" records it as "ctrl+shift+unknown"

### ISSUE THREAD

**Issue by ayush987goyal** [microsoft/vscode#72947] opened 2019-04-27 04:07 UTC
Issue Type: <b>Bug</b>

I have a keyboard shortcut of opening the Explorer set to `ctrl+shift+e`. This is currently not working and hence I tried to check the keyboard shortcut settings for the same. I tried to record the keys that I press and typed `ctrl+shift+e` and it resulted in `ctrl+shift+unknown` in the input tag.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.0-13-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 1685)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.63GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
vscode-browser-preview|auc|0.5.3
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.26.0
flutter|Dar|2.26.0
vscode-eslint|dba|1.8.2
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
Angular2|joh|7.1.4
Angular-BeastCode|Mik|8.0.4
dotenv|mik|1.0.1
python|ms-|2019.4.11987
cpptools|ms-|0.22.1
Go|ms-|0.10.1
debugger-for-chrome|msj|4.11.3
vetur|oct|0.19.2
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.9
vscode-icons|vsc|8.6.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by krepflap** [comment] 2019-04-28 13:45
Same here, also on Linux (Ubuntu 18.04). Running with `--disable-extensions` doesn't work.

Some keyboard shortcuts just seem broken currently, it's the same for `ctrl+shift+u`.

```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic
```

**Comment by krepflap** [comment] 2019-04-29 07:11
Additional info: Can't reproduce this in Windows so must be platform specific, Linux only?

**Comment by warrenpoon** [comment] 2019-04-29 13:29
I also have this issue on Ubuntu 19.04. At first I thought disabling the built-in emoji keyboard shortcut for `Ctrl-Shift-E` via ibus-setup would do the trick, but there still seems to be some sort of conflcit.

**Comment by laur1s** [comment] 2019-04-30 17:27
@warrenpoon  are you using snap package or deb?

**Comment by warrenpoon** [comment] 2019-04-30 19:16
> @warrenpoon are you using snap package or deb?
Hello @laur1s , snap via the Software GUI

**Comment by kjs3** [comment] 2019-05-03 00:20
Same issue. Ubuntu 19.04 snap pkg installed via store.

**Comment by giulianisanches** [comment] 2019-05-06 01:54
I have the same issue and just found the followin post:

https://stackoverflow.com/questions/52032340/ctrlshifte-inerts-special-characters-into-file-instead-of-showing-explore-pane

As i'm using openSUSE Leap 15 with GTK3 3.22. The only option for me is to remap keys.

**Comment by alexandrudima** [comment] 2019-05-06 12:59
Related: #70277

**Comment by hardikdangar** [comment] 2019-05-10 09:42
To anyone who is experiencing this in Linux,

This is because ctrl + shift + E is assigned to emoji input.

TO disable that go to terminal & type 

$ ibus-setup

window will open third tab will be emojis tab. change the shortcut key ctrl + shift + e to anything you like. then explorer shortcut key will perfectly.

**Comment by Qussayyon** [comment] 2019-06-28 08:38
> To anyone who is experiencing this in Linux,
> 
> This is because ctrl + shift + E is assigned to emoji input.
> 
> TO disable that go to terminal & type
> 
> $ ibus-setup
> 
> window will open third tab will be emojis tab. change the shortcut key ctrl + shift + e to anything you like. then explorer shortcut key will perfectly.

Thanks, but when I run `ibus-setup` it says:
`Command 'ibus-setup' not found, but can be installed with:`

I'm using KDE neon (Ubuntu 18.04 LTS).

**Comment by hardikdangar** [comment] 2019-06-28 09:03
> > To anyone who is experiencing this in Linux,
> > This is because ctrl + shift + E is assigned to emoji input.
> > TO disable that go to terminal & type
> > $ ibus-setup
> > window will open third tab will be emojis tab. change the shortcut key ctrl + shift + e to anything you like. then explorer shortcut key will perfectly.
> 
> Thanks, but when I run `ibus-setup` it says:
> `Command 'ibus-setup' not found, but can be installed with:`
> 
> I'm using KDE neon (Ubuntu 18.04 LTS).

It seems you do not have ibus installed. you can install ibus with
`sudo apt install ibus`
and then try to run
`ibus-setup`

**Comment by Qussayyon** [comment] 2019-06-28 09:32
![Peek 2019-06-28 12-29](https://user-images.githubusercontent.com/13088819/60332946-819edd00-99a0-11e9-94d1-42a21a0cd3ef.gif)
I'm using KDE neon and KDE doesn't use `ibus` and as U see in gif, code is being run while disabling all extensions.

**Comment by DevGim** [comment] 2019-07-22 06:20
Thanks in advance.
I am using Ubuntu 19.04.

I cannot disable ibus-emoji.
Change shortcut with other meaniningless shortcut via ibus-setup is helpful for other application but not helpful for vscode.

What shoud I do?

**Comment by irthomasthomas** [comment] 2019-08-16 15:17
I still have this problem also with 1.37.1. It's amazing that MS with all of it's talent can't fix such a small but vital problem. Really what is so hard? I thought MS loved Linux? Where is the love?! ; (

**Comment by CVirus** [comment] 2019-09-19 19:57
Running ibus-setup and deleting the emoji shortcut seems to do the trick on Ubuntu 18.10

**Comment by irthomasthomas** [comment] 2019-09-22 13:51
I don't have that emoji stuff on my ubuntu 18.04

**Comment by alexandrudima** [comment] 2019-10-08 12:49
I am really sorry, but unfortunately this is not something we can fix in VS Code. There is no possible code change to do on our side if there are keybindings which do not reach our window/application from the OS.

**Closed by alexandrudima** 2019-10-08 12:49 UTC
Labels: keybindings, linux

**Comment by irthomasthomas** [comment] 2019-10-08 13:12
I don't know what you mean? How is this not a VS code bug if it only
happens in vs code? I don't have any of the aforementioned emoji stuff
installed. Just to be clear about what's happening, when I press
Ctrl+Shift+e the first time it works, but after that pressing ctrl+shift+e
causes some symbols to be inserted to the open document instead. No other
software on my machine behaves likes that, but if you know of something in
my linux which is causes this then I can try and fix it. Thanks

**Comment by alexandrudima** [comment] 2019-10-08 14:22
@irthomasthomas You might have a different issue than the OP. The OP affirms that ctrl+shift+e is not reaching VS Code (VS Code detects the keybinding as ctrl+shift+unknown).

So, in your case, I will assume that ctrl+shift+e is consistently detected as ctrl+shift+e by VS Code. Can you please confirm using these steps:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

If ctrl+shift+e consistently arrives from the OS as ctrl+shift+e, and sometimes it shows the explorer and sometimes it inserts symbols in the editor, then it is possible that you might have a keybinding customization for ctrl+shift+e. Can you please try to reproduce by disabling all extensions and removing your customizations from `keybindings.json`?

**Comment by Notevill** [comment] 2019-10-25 06:26
I am have issue like this. `Ctrl+Shift+u` give me `Ctrl+Shift+unknow`. And that not working only for VSCode. I tried set this shortcuts to i3wm for test and it works. 

VSCode about:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-16T10:22:16.623Z
Electron: 4.2.11
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.79-1-MANJARO
```

**Comment by Notevill** [comment] 2019-10-25 07:08
I found that this keybinding by default is for [unicode input](https://bbs.archlinux.org/viewtopic.php?id=171531). And while editor is in focus it try to print unicode symbols. Just use another keybindings.

**Comment by lcswillems** [comment] 2019-11-11 09:36
I have the same issue. Ctrl+shift+e is captured by i3wm.

**Comment by David-Else** [comment] 2019-11-11 10:29
This might work, depending on your setup: https://github.com/microsoft/vscode/issues/48480#issuecomment-414464079
