### ISSUE TITLE
folding end marker does not work on empty lines

### ISSUE THREAD

**Issue by almaceleste** [microsoft/vscode#111311] opened 2020-11-25 16:40 UTC
- VSCode Version: 1.51.1
- OS Version: Linux x64 5.8.0-26-lowlatency

Steps to Reproduce:

1. Generate Language Support extension with `yo code` wizard
2. Add language-specific settings to the project
3. Add following properties to the `language-configuration.json`:
```json
    "folding": {
        "markers": {
            "start": "^\\[.+\\]\\s*",
            "end": "^\\s*$"
        }
    }
```
4. Run debug
5. Ensure that folding does not work

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by aeschli** [comment] 2020-11-26 08:26
Duplicate of https://github.com/microsoft/vscode/issues/96821

**Comment by almaceleste** [comment] 2020-11-26 09:11
> Duplicate of #96821

this duplicate was closed due to the fact that *"not received the 20 community upvotes"*, which the community (of which I am a part) did not even know.  
I think this is an incorrect answer to my bug report (cause this is a bug, since the TextMate functionality declared in the application does not fully work). and this is not a reason to simply dismiss the problem and close the issue.

**Comment by almaceleste** [comment] 2020-11-27 04:15
it is not a `feature request` to vote on.  
this is a `bug report`. 
since when do you need to collect votes to correct a bug?!

**Comment by aeschli** [comment] 2020-11-27 08:15
Empty lines as stop (or start makers) were never intended to work, that's why it's a feature request.
The current algorithm that computes folding ranges based on indentation and markers already give empty lines special treatment so this will require some thought.

Can you give examples of languages where an empty end folding marker is useful?

**Comment by almaceleste** [comment] 2020-11-27 08:50
the [Language Configuration Guide](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding) says: 

> Language configuration folding: When VS Code finds both the `start` and `end` ***regex*** defined in `folding.markers`, it creates a folding marker enclosing the content inside the pair.   

the empty line regexes, such as `^\s*$` or `^$` or `^\n`, are valid and work for search and match purposes. 
and the Guide says nothing about they are not supported, nothing about restrictions.  

then this is a bug, not a feature request!

**Comment by almaceleste** [comment] 2020-11-27 09:04
> Can you give examples of languages where an empty end folding marker is useful?

R
Markdown
Desktop Entries (.desktop)
Plain Text
Yaml
INI files
REG files

do I have to continue?

**Comment by aeschli** [comment] 2020-11-27 09:17
The feature is called folding markers and is about explicit marker strings (e.g. '#region` and `#endregion`.) that users can enter to define custom folding ranges on top of folding based in indentation.
I don't think of an empty line as a marker string, but I guess this can be debated.

I can clarify the doc if that's helpful.

**Comment by almaceleste** [comment] 2020-11-27 16:31
the Language Configuration Guide says about ***regex*** - not about the strings with `#region` and `#endregion` or something else like that. 

> I can clarify the doc if that's helpful.  

And yes, I understand that it is possible to adjust the existing guide to the unfinished reality, but it looks like... uh... cheating? 
and I don't understand how it can help in solving the bug. how it can help in the development of language extensions.

**Comment by aeschli** [comment] 2020-11-30 09:28
I updated the doc to clarify what a marker is and what's currently supported.

If you want to full control over folding ranges, have a look at folding providers. In there you can use regexes, or even better use a language parser

**Comment by almaceleste** [comment] 2020-11-30 19:54
ahaha, you did it anyway! 
due to such an unfinished implementation, for many language extensions it is necessary to solve this problem with the folding providers. this creates tones of unnecessary code, increases the load and threatens with additional bugs. instead of solving the problem in one place, you decided to legitimize the unfinished state. not the most efficient solution in my opinion, but yes, the simplest one.

**Closed** 2021-01-27 02:51 UTC
Labels: editor-folding, feature-request
