### ISSUE TITLE
Multiple terminals created when open a project

### ISSUE THREAD

**Issue by liziwl** [microsoft/vscode#110294] opened 2020-11-10 09:08 UTC
Issue Type: <b>Bug</b>

## reproduce the bug
1. opening a project, and draw from the bottom to open the terminal panel.
2. shows that two terminals are created and the second is error.

* not installed WSL
* default terminal is Powershell

```
[2020-11-10 08:54:58.909] Error: spawn C:\WINDOWS\System32\wslconfig.exe ENOENT
```
![image](https://user-images.githubusercontent.com/23000702/98652310-699de280-2376-11eb-8e8f-549587c798f7.png)

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (11.09GB free)|
|Process Argv|--crash-reporter-id 0f84e014-d1be-4ce0-ae62-fbf71e22850d|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.3
latex-workshop|Jam|8.13.2
rainbow-csv|mec|1.7.1
python|ms-|2020.10.332292344
vscode-pylance|ms-|2020.11.0
remote-containers|ms-|0.148.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.51.2
vscode-remote-extensionpack|ms-|0.20.0
partial-diff|ryu|1.4.1
latex-utilities|tec|0.3.7
vscode-icons|vsc|11.0.0
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by chucknelson** [comment] 2020-11-10 15:27
+1 - Same exact thing happening after upgrading to 1.51.0 on a Windows 7 machine.

**Comment by ayazthemre** [comment] 2020-11-10 17:45
Same here. Not sure about updating.

**Comment by haohello** [comment] 2020-11-10 17:55
Same here.  I kept trying to search for the solution to this error online without any success.

**Comment by meganrogge** [comment] 2020-11-10 18:09
@liziwl sorry you're having this issue. can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? 

I'm not seeing this issue there. ![recording (32)](https://user-images.githubusercontent.com/29464607/98713606-acdb5f80-233c-11eb-93f2-7f1938c0e4ab.gif)

**Comment by areuthere** [comment] 2020-11-10 18:17
Seeing the same issue on 
![image](https://user-images.githubusercontent.com/22025324/98714579-11370700-23af-11eb-89df-4f385325dada.png)

**Comment by mrail** [comment] 2020-11-10 18:43
I have the same issue.  My default terminal is bash.

Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Tyriar** [comment] 2020-11-10 19:38
I suspect this is caused by the Remote WSL as it created a terminal for logs named "WSL" (name in the dropdown), it was also released yesterday.

**Comment by Tyriar** [comment] 2020-11-10 19:39
Tentatively marking November as it seems like a lot of people are hitting this.

**Comment by JJJAMM** [comment] 2020-11-11 01:49
![图片](https://user-images.githubusercontent.com/38007570/98755258-2dfd2a00-2403-11eb-83a1-d772fd677a13.png)

**Comment by Yudezhi** [comment] 2020-11-11 02:10
same issue， mark follow for solutions

**Comment by liziwl** [comment] 2020-11-11 02:57
> @liziwl sorry you're having this issue. I'm not able to reproduce it in Version 1.51 or Insider's. I noticed that you have remote-wsl listed in your extensions. Were you aware of that? I have that extension installed with the same version as you do so don't think that's causing the issue.

It seems caused by `remote-wsl` when I disable the extensions, the problem disappears. I reproduce the bug on a local project.

<img src="https://user-images.githubusercontent.com/23000702/98759489-22623100-240c-11eb-818e-e142152218df.png"  height = "300" />

**Comment by liziwl** [comment] 2020-11-11 03:16
Also can reproduce in the latest insider version.
<img src="https://user-images.githubusercontent.com/23000702/98760840-20e63800-240f-11eb-9e7e-5533fbccc607.png"  height = "300" />

![Irb1cuKDtB](https://user-images.githubusercontent.com/23000702/98760850-25125580-240f-11eb-9e2a-d063ad66a085.gif)

**Comment by kwangh** [comment] 2020-11-11 03:24
I solved by disabling **Remote - WSL** extensions.
![캡처](https://user-images.githubusercontent.com/8899396/98761367-9a365880-2418-11eb-867c-8b7e734f8aa9.PNG)
After the change, I reopened the vscode and the problem solved.

**Comment by psnehas** [comment] 2020-11-11 06:51
> As a temporary solution, I solved by disabling **Remote - WSL** extensions.
> ![캡처](https://user-images.githubusercontent.com/8899396/98761367-9a365880-2418-11eb-867c-8b7e734f8aa9.PNG)
> After the change, I reopened the vscode and the problem solved.

This solution worked for me! 
Thanks!

**Comment by amitsharma-007** [comment] 2020-11-11 07:37
I am getting the following error! Please Help Somebody!


[13:01:30.549] Log Level: 2
[13:01:30.554] remote-ssh@0.56.0
[13:01:30.554] win32 x64
[13:01:30.557] SSH Resolver called for "ssh-remote+formup-ec2", attempt 1
[13:01:30.557] SSH Resolver called for host: formup-ec2
[13:01:30.557] Setting up SSH remote "formup-ec2"
[13:01:30.587] Using commit id "fcac248b077b55bae4ba5bab613fd6e9156c2f0c" and quality "stable" for server
[13:01:30.589] Install and start server if needed
[13:01:30.594] Checking ssh with "ssh -V"
[13:01:30.683] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:01:30.692] Running script with connection command: ssh -T -D 59191 formup-ec2 bash
[13:01:30.696] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:01:32.314] > bec8b9973c71: running
> ]0;C:\WINDOWS\System32\cmd.exe
[13:01:32.314] Got some output, clearing connection timeout
[13:01:32.401] > Acquiring lock on /home/ubuntu/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6
> e9156c2f0c/vscode-remote-lock.ubuntu.fcac248b077b55bae4ba5bab613fd6e9156c2f0c   
[13:01:32.468] > Installing to /home/ubuntu/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e915
> 6c2f0c...
[13:01:32.478] > bec8b9973c71%%1%%    
> Downloading with wget
[13:05:00.874] > bec8b9973c71: running
> Acquiring lock on /home/ubuntu/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c/vscode-remote-lock.ubuntu.fcac
> 248b077b55bae4ba5bab613fd6e9156c2f0c
> Installing to /home/ubuntu/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c...
> bec8b9973c71%%1%%
> Downloading with wget
> 
> 
[13:06:47.268] > Connection reset by 3.7.88.12 port 22
[13:06:47.953] "install" terminal command done
[13:06:47.955] Install terminal quit with output: Connection reset by 3.7.88.12 port 22
[13:06:47.955] Received install output: Connection reset by 3.7.88.12 port 22
[13:06:47.963] Stopped parsing output early. Remaining text: Connection reset by 3.7.88.12 port 22
[13:06:47.964] Failed to parse remote port from server output
[13:06:47.979] Resolver error: Error: 
	at Function.Create (c:\Users\eds16\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:1:94424)
	at Object.t.handleInstallOutput (c:\Users\eds16\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:1:91173)
	at I (c:\Users\eds16\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:106975)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\eds16\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:104974
	at async Object.t.withShowDetailsEvent (c:\Users\eds16\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:110096)
	at async Object.t.resolve (c:\Users\eds16\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:108158)
	at async c:\Users\eds16\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:143767
[13:06:47.990] ------

**Comment by tanzil786** [comment] 2020-11-11 09:12
1) Go on extension
2) In search bar write "remote WSL"
3) click on "remote WSL"
4) and disable it for temporary solution
5) An now begin.

Happy and enjoy😀😀😎😎

**Comment by aeschli** [comment] 2020-11-11 10:31
I pushed a fix with Remote-WSL 0.51.3

**Comment by Pengyang233** [comment] 2020-11-11 11:50
same issue

**Comment by phoebusg** [comment] 2020-11-11 13:06
Same issue, last I remember I had opened a new terminal, worked fine. Started the editor a day later, In terminal I see this

**Comment by aeschli** [comment] 2020-11-11 14:46
duplicate of https://github.com/microsoft/vscode-remote-release/issues/3999

**Closed by aeschli** 2020-11-11 14:46 UTC
Labels: WSL, bug, integrated-terminal

**Comment by bramovic44** [comment] 2020-11-12 08:29
Hello, Personally, I don't desactivate 'remote WSL', I just opened a new terminal : CTRL + MAJ + ù
