### ISSUE TITLE
Default terminal problems

### ISSUE THREAD

**Issue by bugada** [microsoft/vscode#132444] opened 2021-09-06 10:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows 10 build1909

Steps to Reproduce:

1. Configure new default terminal in config:
```
    "terminal.integrated.profiles.windows": {
        "GitBash": {
            "path": "C:\\Users\\myuser\\bin\\bash.exe",
            "icon": "terminal-bash"
        }
    },
```
2. When VSCode starts the terminal is open on the Powershell profile even if the GUI says that GitBash is the default.
3. A Powershell terminal is used also for debug and process terminals
4. Using Open in integrated terminal on a file opens  Powershell terminal

A mitigation step is configuring this

`"terminal.integrated.automationShell.windows": "C:\\Users\\myuser\\bin\\bash.exe",`

and solves point number 3. But the documentation says: "By default, the task/debug features will use the default profile", in my case GitBash.

GitBash is installed as portable.
I can't use powershell since admins are limiting it.

Thank you
Andrea

**Comment by albertosantini** [comment] 2021-09-06 10:14
This is a duplicate of #132150 and will be fixed in upcoming recovery release

**Comment by burzomir** [comment] 2021-09-06 10:15
@albertosantini When is the recovery release coming?

**Comment by albertosantini** [comment] 2021-09-06 10:17
I suppose in a few days. See https://github.com/microsoft/vscode/issues/132426

**Closed** 2021-09-06 10:55 UTC
Labels: *duplicate, new release
