### ISSUE TITLE
Open wrong shell

### ISSUE THREAD

**Issue by matthias-p-nowak** [microsoft/vscode#132747] opened 2021-09-09 12:13 UTC
Issue Type: <b>Bug</b>

When I click in the Explorer on a folder and choose "open in integrated terminal", it opens it in powershell, which I do not want. My default is Git-Bash.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (16.14GB free)|
|Process Argv|--crash-reporter-id 04da1a09-1319-4e5b-b275-f2f15c1d57c6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml-key-viewer|cyb|0.2.2
go|gol|0.27.2
vscode-graphviz|joa|0.0.6
vscode-insertdatestring|jsy|2.3.0
saltstack|kor|0.0.8
vscode-docker|ms-|1.16.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
jinjahtml|sam|0.16.0
vscode-maven|vsc|0.33.0

</details>

**Comment by albertosantini** [comment] 2021-09-09 12:33
Maybe it is a duplicate of #132150 (bug which is already fixed in Insiders build and supposed to be in upcoming Recovery release).

**Comment by anzuj** [comment] 2021-09-09 13:09
Yes I have the same problem. Since the last update my default terminal has always been Shell which annoys me to no end. Hope the release comes soon!

**Closed** 2021-09-09 14:50 UTC
Labels: *duplicate
