### ISSUE TITLE
Extenstion Information Page content display problem

### ISSUE THREAD

**Issue by sphingu** [Microsoft/vscode#9793] opened 2016-07-26 15:44 UTC
- VSCode Version 1.3.1
- Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae
- Date 2016-07-12T13:42:20.692Z
- Shell 0.37.6
- Renderer 49.0.2623.75
- Node 5.10.0
- OS Version: Ubuntu 16

Steps to Reproduce:

1. Start VS Code 
2. Increase Zoom by Ctrl + +(Plus).
3. Open Extension Tab.
4. Click on any extension.
5. On Extension Information page, scroll display in properly.
![screenshot from 2016-07-26 21-08-19](https://cloud.githubusercontent.com/assets/4688134/17144757/8422d56e-5375-11e6-8cce-7fe88186d1f6.png)

**Comment by joaomoreno** [comment] 2016-07-27 07:47
Duplicate of #5745

**Closed by joaomoreno** 2016-07-27 07:47 UTC
Labels: extensions
