### ISSUE TITLE
workbench.list.openMode to control single click vs double click to open

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#43245] opened 2018-02-08 19:44 UTC
- VSCode Version: 1.20.0
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

When using "`workbench.list.openMode`" to control single click vs. double click to open ", I thought it would not affect "`workbench.editor.enablePreview`".

1- That is, when "`workbench.list.openMode: doubleClick`" and "`workbench.editor.enablePreview: true`" would affect only the folders, and when
"`workbench.list.openMode: doubleClick`" and "`workbench.editor.enablePreview: false`" would affect everything for double click.

2- An alternative would be to configure extensions of file types supported by VSCode that would **NOT** enter the preview. By default, all files would enter the preview.

For me the first option would solve. Does this setting make sense? 🤔 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-02-09 06:03
@Tekbr there is no relation between the 2 settings and I have no idea what you refer to with regards to "would affect only the folders". 

The setting is very simple:
* `singleClick`: folders expand on single click, items expand on single click
* `doubleClick`: folders expand with double click, items open with double click

Since we also "pin" items on double click ("pin" is the opposite of "preview"), it means that opening items with double click will "pin" them. 

Are you referring to being able to open an item in "preview" with a double click?

**Comment by Tekbr** [comment] 2018-02-09 12:46
@bpasero Let's try again!! If you still have questions, please ask me. And if it now makes any sense to you the explanation.

**Version - 1.19.3**
Settings: `workbench.editor.enablePreview: true`

1- Folders and Files opened in a single click
2- Files being opened in Preview.

**Version - 1.19.3**
Settings: `workbench.editor.enablePreview: false`

1- Folders and Files opened in a single click
2- Since files opened directly for editing.


**Version - 1.20.0**
Settings: `workbench.list.openMode: singleClick`
`workbench.editor.enablePreview: true`

1- Folders and Files open in a single click
2- Being what files open in Preview.

**Version - 1.20.0**
Settings: `workbench.list.openMode: singleClick`
`workbench.editor.enablePreview: false`

1- Folders and Files open in a single click
2- Since files open directly to edit.


**Version - 1.20.0 - Expected**
Settings: `workbench.list.openMode: doubleClick`
`workbench.editor.enablePreview: true`

1- Folders opened in double click
2- There is no possibility to see file in the preview.

**NOTE:** Expectation would be to preview the files only with `singleClick`. With a double click it would open directly to edit

**Version - 1.20.0**
Settings: `workbench.list.openMode: doubleClick`
`workbench.editor.enablePreview: false`

1- Folders and Files opened in double click
2- Since files opened directly for editing.


That is, in my opinion, `workbench.editor.enablePreview: true` becomes useless when `workbench.list.openMode` is set up with `doubleClick`. Or I'm doing something wrong.

**Comment by bpasero** [comment] 2018-02-09 17:38
> Version - 1.20.0 - Expected
> Settings: workbench.list.openMode: doubleClick
> workbench.editor.enablePreview: true
> 
> 1- Folders opened in double click
> 2- There is no possibility to see file in the preview.
> 
> NOTE: Expectation would be to preview the files only with singleClick. With a double click it would open directly to edit

I do not think that is what people want. People want to only open a file on double click, neither preview nor in edit mode. If we would change that, these people would basically have to make changes to 2 settings to get the desired behaviour. It is true that these people probably also do not want the preview editor in the first place but they might not be aware of the setting. 

The preview feature can still be used, e.g. if you open an entry from quick open. There are other ways how editors can also be opened programmatically in preview mode. 

I am closing this as designed until more people complain about it.

**Closed by bpasero** 2018-02-09 17:38 UTC
Labels: needs more info

**Comment by Tekbr** [comment] 2018-02-09 19:32
-- Sorry for the English, I used Google Translator --

> I do not think that is what people want. People want to only open a file on double click, neither preview nor in edit mode.

@bpasero But before having this function, they already put `workbench.editor.enablePreview: false`, not to have the preview. It soon makes sense if the preview is true to show and `doubleClick` active.

With` workbench.editor.enablePreview: false`, it works the way it is. As I mentioned in the previous review.

> If we would change that, these people would basically have to make changes to 2 settings to get the desired behaviour.

And as a single function you are removing an existing function.

> It is true that these people probably also do not want the preview editor in the first place but they might not be aware of the setting.

The same way I had to go back to the previous version to check the reason. I was not aware that by enabling doubleClick with preview, the preview would not work.

> The preview feature can still be used, e.g. if you open an entry from quick open. There are other ways how editors can also be opened programmatically in preview mode.

Yes, but it only works for some recent files and not for everyone.
