### ISSUE TITLE
Incorrect syntax highliting for C/C++

### ISSUE THREAD

**Issue by Rn86** [Microsoft/vscode#18179] opened 2017-01-05 16:51 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.0.9|
|tortoise-svn|fantasytyx|0.1.1|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.3.0|

Color theme: Dark(Visual Studio)

---

Visual Studio Code does not generate .browse.VS.db in .vscode

Steps to Reproduce:

1. Open directory with Visual Studio Code
2. Open C or C++ file
3. Everything is in blue.

**Comment by pieandcakes** [comment] 2017-01-05 22:54
@Rn86 This issue should be filed on the Microsoft C/C++ extensions github page at https://github.com/Microsoft/vscode-cpptools .

**Comment by Rn86** [comment] 2017-01-06 14:31
They responded with a message that vscode-cpptool does not impact colorization.

I tested maybe a dozen color themes and in all cases colorization was terrible. Ether everything is in same color or colors make no sense at all for example same function calls right after each other were in different colors.

https://github.com/Microsoft/vscode-cpptools/issues/434#issuecomment-270899566

**Comment by aeschli** [comment] 2017-01-10 03:09
Please add the code snippet (as small as possible) that shows the problem. Additionally a screenshot...

**Comment by Rn86** [comment] 2017-01-18 14:54
I can not include any code, because its confidential. But it seems i tracked down where all that colorization failures are coming from.
If there is macro defined at the top like this:

#define MY_MACRO_1()
#define MY_MACRO_2()
#define MY_MACRO_3(foo) \
	((foo) ? \
		MY_MACRO_1() :\
		MY_MACRO_2())

everything bellow is in blue color.

**Comment by Rn86** [comment] 2017-01-18 14:56
```
#define MY_MACRO_1()
#define MY_MACRO_2()
#define MY_MACRO_3(foo) \
	((foo) ? \
		MY_MACRO_1() :\
		MY_MACRO_2())
```

**Comment by Rn86** [comment] 2017-01-18 15:00
Changing these kind of macro blocks to:

```
#define MY_MACRO_1()
#define MY_MACRO_2()
#define MY_MACRO_3(foo) ((foo) ? MY_MACRO_1() : MY_MACRO_2())
```

fixes the problem.

**Comment by aeschli** [comment] 2017-01-19 15:54
duplicate of https://github.com/atom/language-c/issues/160

**Closed by aeschli** 2017-01-19 15:54 UTC
