### ISSUE TITLE
Remote debug throws "[node-debug2] Error processing "attach": 'Schema.getDomains' wasn't found"

### ISSUE THREAD

**Issue by Pho3nixHun** [Microsoft/vscode#25989] opened 2017-05-05 06:42 UTC
- VSCode Version: 1.12.1
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce:

1. Debug with "Attach to Remote Program"

It was working yesterday, right after the update to 1.12.1 it throws this:
`[node-debug2] Error processing "attach": 'Schema.getDomains' wasn't found`

Remote app is running on node 6.5 if that matters.

**Comment by cccstbccc** [comment] 2017-05-05 08:01
similar error when trying to launch, configuration is:

{
	"type": "node",
	"request": "launch",
	"name": "Launch",
	"program": "${workspaceRoot}/mypath/myscript.js",
	"cwd": "${workspaceRoot}/mypath",
	"protocol": "inspector"
}

note: i changed this because editor complained that "node2" is no longer supported, and i should add a protocol directive set to "inspector"

results in:

"Error processing "launch": 'Schema.getDomains' wasn't found"

and the program is not launched

**Comment by weinand** [comment] 2017-05-05 08:11
Duplicate of https://github.com/Microsoft/vscode/issues/25556
Either upgrade node.js to at least 6.6 or set `protocol` to `legacy`.

**Closed** 2017-05-05 08:11 UTC
Labels: duplicate

**Comment by Pho3nixHun** [comment] 2017-05-05 08:23
With `protocol` set to `legacy` it throws `Cannot connect to runtime process (reason: This socket has been ended by the other party).`

With  `protocol` set to `inspector` it is connecting, but after a few lines (in debug console), it throws the error mentioned above.

**Comment by weinand** [comment] 2017-05-05 08:48
@Pho3nixHun If you use the "legacy" protocol make sure that the node.js your are attaching to is configured for the "legacy" protocol, e.g. use "--debug" instead of "--inspect".

If you use the "inspector" protocol you have to upgrade node to at least 6.6 (the current LTS version is 6.10.3).

**Comment by Jeyanthinath** [comment] 2017-08-05 16:49
with node 8.2.1 

```
{
    "type": "node",
    "request": "attach",
    "protocol": "legacy",
    "name": "Attach",
    "port": 3000
}
```
still getting erro while attaching 

`Cannot connect to runtime; make sure that runtime is in 'legacy' debug mode.`

**Comment by roblourens** [comment] 2017-08-07 01:32
'legacy' won't work with 8.2.1, since the legacy debug protocol has been removed in that version. This is an unrelated issue.
