### ISSUE TITLE
"The specified task cannot be tracked" while waiting for user input variable in a "preLaunchTask"

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode#108443] opened 2020-10-10 10:20 UTC
- VSCode Version: 1.50.0
- OS Version: Windows 10

It seems that when starting a launch configuration that has a `preLaunchTask` that itself uses an input variable, we get "The specified task cannot be tracked" after 10 seconds of waiting for user input. When the same task is run manually via `Run Task` everything works fine. I believe this behaviour is not correct and that VSCode should never mark a task as unresponsive when in fact it has not been started yet. It should block and wait for user input without a warning. I'm not sure if there are any workarounds to this problem.

Steps to Reproduce:

1. Create an input variable and a task that references it in `tasks.json`
2. Create a launch configuration in `launch.json` that uses that task as its `preLaunchTask`
3. Launch the configuration and wait for 10 seconds

**Comment by alexr00** [comment] 2020-11-30 13:08
@isidorn, before I try to change this: how would you expect debug to behave in this scenario?

**Comment by isidorn** [comment] 2020-11-30 13:30
@alexr00 ideally debug would simply not complain in this case and wait indefenitely.
The issue is this timeout [here](https://github.com/microsoft/vscode/blob/f5fb75d82916e54ef0ec6488627eb4dc1d56fabf/src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts#L178) that does not take into account that a user is about to enter input.

**Comment by alexr00** [comment] 2020-12-28 16:33
Pushed a fix. Note that if you cancel the input then the launch config will still execute. This is consistent with the existing behavior.

**Closed** 2020-12-28 16:32 UTC
Labels: bug, tasks
