### ISSUE TITLE
Built-in support for zsh, powerlevel10k, nerd fonts or powerline.

### ISSUE THREAD

**Issue by PriyanshuMay** [microsoft/vscode#102332] opened 2020-07-13 04:19 UTC
* VSCode Version: 1.47.0
* OS Version: Ubuntu 20.04 LTS

When I use **zsh**,**powerlevel10k** and **hackfont or powerline** ,the *integrated terminal* starts behaving abnormally and it is really unpleasent to the eye.

![before](https://user-images.githubusercontent.com/54521023/87269922-43615680-c4ec-11ea-8816-90054f9c5fd9.png)

Then I have to tweak some setting in ``setting.json`` to make everything works.

![after](https://user-images.githubusercontent.com/54521023/87269980-65f36f80-c4ec-11ea-84d7-587e43225e15.png)

Shouldn't ``setting.json`` automatically update when user changes system's font or shell.

**Comment by yedhink** [comment] 2020-07-13 05:14
@PriyanshuMay I believe the integrated terminal render type is "canvas" by default. However, Electron/Chromium are slower at rendering to canvas on some environments so VS Code also provides a fallback DOM-renderer experience. Usually a notification will be shown for you to change the render type. You can try setting the render type to "auto" and vscode will auto-set it for you. 
`"terminal.integrated.rendererType": "auto",`

**Comment by Tyriar** [comment] 2020-07-13 12:52
> Then I have to tweak some setting in setting.json to make everything works.

What did you tweak? It should update when you change the font, can you create a [gif](https://gifcap.dev/) showing the problem of it not updating?

**Comment by PriyanshuMay** [comment] 2020-07-14 09:57
![code](https://user-images.githubusercontent.com/54521023/87412092-345ecf00-c5e6-11ea-953e-328ff77d46e2.gif)
* Hope this helps

**Comment by Tyriar** [comment] 2020-08-04 00:26
"monospace" is handed off to Chromium and is handled the same was as if it were a regular webpage. I'll close this as designed as if you want powerlines the current way you do it by design is by modifying your settings.json file.

**Closed** 2020-08-04 00:27 UTC
Labels: *as-designed, needs more info

**Comment by PriyanshuMay** [comment] 2020-08-04 19:44
Thanks for your time
