### ISSUE TITLE
vscode output window show messy code when debug a dotnet core console application.

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#35235] opened 2017-09-27 16:31 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Install dotnet core sdk and open vscode, create a console application with "dotnet new console"
2.Press F5, then vscode output window has messy code,like below:
![test](https://user-images.githubusercontent.com/8075421/30925418-5e21c90e-a3e4-11e7-9405-cbf1ce59ef9b.gif)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment] 2017-09-28 07:51
@DFVSQY can you please provide a simple console.log statement which does not get outputed nicely.
I think just some chinesse characters would do the trick

**Comment by DFVSQY** [comment] 2017-09-28 14:33
@isidorn Where can i input console.log statement ? How i can do it ? 
Is it like below:
![qq 20170928223009](https://user-images.githubusercontent.com/8075421/30972320-c685424c-a49c-11e7-8d63-da4c7e38fc3e.png)
It seems like it doesn't support chinese.

**Comment by isidorn** [comment] 2017-09-28 14:35
Jiust do it in your program using `Console.WriteLine('some chineese')`

**Comment by DFVSQY** [comment] 2017-09-28 14:41
It really doesn't support chinese when i type some chinese words. 
like below:
![qq 20170928223009](https://user-images.githubusercontent.com/8075421/30972746-108b516e-a49e-11e7-8ab3-32719b3fbaaf.png)

**Comment by isidorn** [comment] 2017-09-28 14:42
I understand. Can you please just copy paste line 20 here.

**Comment by DFVSQY** [comment] 2017-09-28 14:44
Console.WriteLine("哈哈");

**Comment by isidorn** [comment] 2017-10-04 09:44
@DFVSQY @rocketRobin  I cannot reproduce this issue using the following program:
I have tried both on Win and on OS X. Can you please post a very simple C# program for which you can always reproduce this issue? Thank you

```C#
using System;

namespace dotnet
{

    class Program
    {
        static void Main()
        {
            Console.WriteLine("哈哈");
        }
    }
}
```

**Comment by DFVSQY** [comment] 2017-10-04 11:39
@isidorn  I think you need chinese edition if you need reproduce this issue. chinese win10 system and chinese visual studio code.

**Comment by DFVSQY** [comment] 2017-10-04 11:49
when i use javascript, there is no problem, like below:
![test](https://user-images.githubusercontent.com/8075421/31174143-f66f0822-a93c-11e7-9df5-c58ab0e517f9.gif)

**Comment by isidorn** [comment] 2017-10-04 11:59
@DFVSQY I do not think that is this being chinnese eddition makes a difference. What is the minimalistic C# example for which you can reproduce the issue? Could you make an example in javascript that shows the problem?

**Comment by DFVSQY** [comment] 2017-10-04 13:12
This is C# problem:
```
using System;

namespace files
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("文件 编辑 选择 查看 转到 调试 任务 帮助");
            Console.WriteLine("哈哈");
        }
    }
}
```
![test](https://user-images.githubusercontent.com/8075421/31177450-a84ab022-a948-11e7-99c7-6be320405fa6.gif)

**Comment by DFVSQY** [comment] 2017-10-04 13:24
This is javascript program:
![test](https://user-images.githubusercontent.com/8075421/31178025-5bd4d2c0-a94a-11e7-9594-34c84eb1782c.gif)

**Comment by isidorn** [comment] 2017-10-04 13:50
@DFVSQY ok, thank you for more details. What exact language are you using for vscode? Simplified or traditional chinese?

I could not reproduce this on win10, since this is only happening for C# debug adapter I have created an issue here https://github.com/OmniSharp/omnisharp-vscode/issues/1775
Closing this one as this should be fixed by the extension

**Closed by isidorn** 2017-10-04 13:50 UTC
Labels: debug, needs more info

**Comment by DFVSQY** [comment] 2017-10-04 13:56
@isidorn vscode and win10 are both simplified chinese language.
