### ISSUE TITLE
Take up a lot of CPU   rp.exe

### ISSUE THREAD

**Issue by zoeDylan** [Microsoft/vscode#35854] opened 2017-10-09 02:08 UTC
- VSCode Version: **1.17**
- OS Version:    **windows 15063.608**

CPU: **i5-4460 3.20GHz**
RAM: **8G**

Steps to Reproduce:

1. 打开项目

2. 打开一个`.js`文件 

3. 打开任务管理器：rg.exe  占用大量CPU
 
![rg](https://user-images.githubusercontent.com/7030260/31323370-8451f9e8-acd9-11e7-848b-0d4b2729f573.png)
![sn o779rt ts7 ajt n9sm](https://user-images.githubusercontent.com/7030260/31323372-8cb44c26-acd9-11e7-9e3b-512fc8eca67a.png)

Reproduces without extensions: Yes/No

**Comment by zoeDylan** [comment] 2017-10-09 02:14
You can open the project

https://github.com/zoeDylan/zoeDylan.github.io

**Comment by zhoudailincser** [comment] 2017-10-09 06:48
是的，把三个进程杀掉然后把最高占cpu的那个vscode也杀了就回到正常了。准备回退版本，等更新。

**Comment by linxiangjun** [comment] 2017-10-09 06:51
我更新成最新的版本后也出现了这个问题，杀进程没有用，每次打开一个新窗口照样弹出这些进程。已经向官方提出来了，希望早点解决吧。

**Comment by newbienewbie** [comment] 2017-10-09 07:18
hi @zoeDylan  do you get the [ms-vscode.csharp](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) extension installed?

Maybe Duplicate of #35659

**Comment by zoeDylan** [comment] 2017-10-09 08:40
@newbienewbie   yes, But it's already uninstalled. Still not solve the problem

![0etg r0hrl3o7x ch f5 fb](https://user-images.githubusercontent.com/7030260/31330304-6796944e-ad10-11e7-9124-ace760390e6a.png)

**Comment by newbienewbie** [comment] 2017-10-09 09:07
@zoeDylan I don't know the reason.

I can't even reproduce the bug on the desktop computer in my office (win7 x64 ; CPU i7-4790 3.60GHz ; RAM 8.00GB) .  With CSharp extension installed , the `rg.exe` only takes up about 20% CPU usage.

On my personal Surface Pro3 , however , openning a npm package containing a `node_modules` subfolder  will cause the usage of CPU growing quickly up to 100% and last for about one or two minutes . If I disable the csharp extension , the `rg.exe` will only live about 8 seconds and then exit . At last the CPU usage will fall back to a normal level.

**Comment by zoeDylan** [comment] 2017-10-09 09:46
My friend also appeared the same problem，I temporarily use 'sublime  text', waiting for repair。

**Comment by chrmarti** [comment] 2017-10-09 19:56
Thanks. Could you run the following command in Powershell from your workspace folder and let me know what the output is?
```
(Measure-Command { & 'C:\Program Files\Microsoft VS Code\resources\app\node_modules\vscode-ripgrep\bin\rg.exe' --files --no-ignore --follow --hidden -- . | Measure-Object –Line | O
ut-Default }).TotalSeconds
```

**Comment by chrmarti** [comment] 2017-10-09 21:27
Also, what is the output of the following when run in Powershell while the `rg.exe` are running?
```
(Get-WmiObject Win32_Process -Filter "name = 'rg.exe'").CommandLine
```

**Comment by zoeDylan** [comment] 2017-10-10 01:39
@chrmarti   I can find the reason,

I run this command

![run](https://user-images.githubusercontent.com/7030260/31365292-ccd95602-ad9c-11e7-8380-7b26ffa0b026.png)

But I have a lot of 'node_modules'.  so,

![print](https://user-images.githubusercontent.com/7030260/31365352-290c66b2-ad9d-11e7-81ad-45b1416ab298.png)

` rg. exe ` spent a lot of time to cycle


at  vsCode

![vsc](https://user-images.githubusercontent.com/7030260/31365522-2fdad996-ad9e-11e7-947d-c630d5bb206c.png)

When ` rg.exe` himself ended, everything is all right

@newbienewbie  Thanks,I think I found the problem.

English is not good, forgive me。

@linxiangjun @zhoudailincser  目前测试出来的是，npm包过多,导致`rg.exe`一直在循环查找npm包,所以很卡，`rg.exe`跑结束后就正常了。

**Comment by newbienewbie** [comment] 2017-10-10 03:40
@zoeDylan  Maybe the real reason is symlink , dependencies or sth else insead of too much npm subpackages，because the `rg.exe` complains that `File system loop found`.

**Comment by zoeDylan** [comment] 2017-10-10 09:18
@newbienewbie   YES，I am thinking how to solve, now only let it run over to start work。

**Comment by chrmarti** [comment] 2017-10-10 14:08
@zoeDylan Could you rerun the command without `--follow`? That will tell us how long it takes when it does not follow symlinks.

**Comment by chrmarti** [comment] 2017-10-10 15:00
@zoeDylan Also: Which version of `npm` were you using to install the node modules? I'm trying to reproduce the problem.

**Comment by chrmarti** [comment] 2017-10-10 16:17
Marking as duplicate of #35659. Both show loops around `es5-ext`. Let's continue the discussion there.

**Closed** 2017-10-10 16:17 UTC
Labels: duplicate, search
