### ISSUE TITLE
Save As - Doesn't work for custom editors

### ISSUE THREAD

**Issue by AlessandroPerina** [microsoft/vscode#108572] opened 2020-10-13 08:21 UTC
Issue Type: <b>Bug</b>

Open a file (ipynb)
Press Save As basically to create a copy
File explorer doesn't show up

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (19.47GB free)|
|Process Argv|--crash-reporter-id 8f7b0688-8ff4-4389-a4d0-47fc2265e74f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
beautify|Hoo|1.5.0
mssql|ms-|1.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.9.112786
geo-data-viewer|Ran|2.3.0
vscode-yaml|red|0.11.1
language-c3|rsa|0.2.0
c3-vscode|sha|0.2.4
vscode-icons|vsc|11.0.0

</details>

**Comment by AlessandroPerina** [comment] 2020-10-13 08:22
I have just upgraded and the problem persists. 

![image](https://user-images.githubusercontent.com/7589671/95834998-f9337f80-0d3d-11eb-86d1-13adeddd598f.png)

**Comment by isidorn** [comment] 2020-10-19 19:26
And can you reproduce with VS Code insiders?

**Comment by pleabargain** [comment] 2020-10-21 08:40
I'm experiencing same bug 

I can save .txt files = no problem. 
Saving ipynb files = no joy!



Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic snap

![save as in jupyter notebook not working Peek 2020-10-21 11-34](https://user-images.githubusercontent.com/640846/96695270-21e8f400-1392-11eb-85aa-b5a733bff49c.gif)

**Comment by isidorn** [comment] 2020-10-21 17:59
This is saving custom editors, forwarding to @bpasero

**Comment by bpasero** [comment] 2020-10-22 06:21
Since I see Linux Snap here, note https://github.com/microsoft/vscode/issues/100940

**Comment by mjbvz** [comment] 2020-10-23 18:22
Have you started by filing this issue against the Python team?

**Comment by mjbvz** [comment] 2020-11-02 21:15
Closing as I believe this should be filed agains the python extension first. If they find that our custom editor's save as functionality doesn't work, they can follow up with steps to reproduce

**Closed by mjbvz** 2020-11-02 21:15 UTC
Labels: custom-editors

**Comment by pleabargain** [comment] 2020-11-28 10:08
I don't know where else to post this as it is the same error. 
Here is the video
https://www.youtube.com/watch?v=uYlQaP00bVk&feature=youtu.be

create a new file
save it
alt+f DOES NOT respond
plus plenty of other 
file >save as 
weirdness

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-54-generic snap

**Comment by Inspired1601** [comment] 2020-12-09 16:33
Same issue.
"Save as" doesn't work at all (for .ipynb files).

**Comment by rchiodo** [comment] 2020-12-10 17:25
File Save as is not supported for ipynb files unless you:

- Use the insiders build. If you use the insiders build the jupyter extension will actually use the new native notebook support that VS code is working on.

or

- Enroll in our 'Custom Editor' experiment. VS code has support for 'custom' editors but we haven't fully rolled it out yet. You can enroll in this experiment with the following setting in your user settings.json:

```json
    "jupyter.experiments.optInto": [
        "CustomEditor"
    ],
```

The reason File Save As (and any command from the File menu) doesn't work is that the ipynb editor is not an editor as far as VS code is concerned. It's simply a tool window.  When VS code added support for 'custom' editors, that made it possible for File Save as to work for ipynb files, but there were some problems in the implementation and we're only slowly rolling it out.

**Comment by AlessandroPerina** [comment] 2020-12-10 19:57
Thanks a lot, now it's clear!
Then maybe you should consider shading the "Save As" option, because it
looks I can click it :)

Cheers!
A
