### ISSUE TITLE
Colors washed out after 1.31 upgrade

### ISSUE THREAD

**Issue by dan-hughes** [microsoft/vscode#69135] opened 2019-02-21 12:00 UTC
Since the 1.31 release all the colors have a yellow hue to them. When I downgrade to 1.30 this issue goes away.  I have updated GPU drivers and run with the --disable-gpu flag without any success.

I installed the insiders 1.32 build and the issue is still occurring, but the 1.31 exploration build #68893 does not have this issue.

Image comparison below.

1.31.1
![image](https://user-images.githubusercontent.com/2237515/53167207-34b09180-35cf-11e9-98a6-80d4016c4f73.png)

1.30.2
![image](https://user-images.githubusercontent.com/2237515/53167443-dcc65a80-35cf-11e9-9ad2-e3fb9044b618.png)

**Comment by Tyriar** [comment] 2019-02-21 14:37
@bpasero dupe of https://github.com/Microsoft/vscode/issues/68893?

**Comment by bpasero** [comment] 2019-02-21 14:51
Yeah could be.

We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by dan-hughes** [comment] 2019-02-21 15:42
Doesn't occur on the exploration build (I had already checked and mentioned above).

This does not happen on my other PC, so this could be something around my hardware.


CPUs | Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)
---|---
GPU | Nvidia P2000 / Intel UHD630
GPU Status | 2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled webgl: enabled<br>webgl2: enabled
Memory (System) | 31.78GB (24.29GB free)
Process Argv |  
Screen Reader | no
VM | 0%

![image](https://user-images.githubusercontent.com/2237515/53180088-dabec480-35ec-11e9-8748-17048664c1b8.png)

**Comment by bryanhunwardsen** [comment] 2019-06-11 07:33
I have same issue updating to 1.36, not sure what ver I was coming from though.
Version: 1.36.0-insider (user setup)
Commit: c089daa858f34631f5f827ff8a0313bf1e2ded6d
Date: 2019-06-07T05:19:15.188Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/3408302/59252243-81e95b00-8be0-11e9-962d-b53f70f4f035.png)

**Comment by el** [comment] 2019-06-12 14:19
Same issue on ubuntu

![Screenshot from 2019-06-12 17-18-43](https://user-images.githubusercontent.com/1488164/59358971-32b53e80-8d36-11e9-866f-b996d83f4171.png)

**Comment by bpasero** [comment] 2019-07-01 06:24
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-07-01 06:24 UTC
Labels: electron, electron-3.0.x-update, fixed-in-electron-4.0.x, upstream

**Comment by felrib** [comment] 2019-07-04 14:17
Not sure if it's the same problem, but after 1.36 colors are a bit off. I'm using Ubuntu 19.04.

**Comment by michaelcacciatore** [comment] 2019-07-11 13:19
Turning off HDR on my primary monitor fixed the washed out colors (even though I was using VSCode on a secondary monitor).  I'm on VSCode 1.36.1

**Comment by ta32** [comment] 2019-08-04 09:31
@bpasero this issue is still occuring in version 1.36.1 it looks like when you enable HDR vscode becomes washed out, can we reopen this issue?

**Comment by bpasero** [comment] 2019-08-05 09:46
Got it. See https://github.com/microsoft/vscode/issues/65816 for the related issue to allow to force the color profile as a setting (not having to pass it as command line argument).
