### ISSUE TITLE
Inconsistent offset with compact folders in explorer

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#96918] opened 2020-05-04 14:04 UTC
VS Code version: Code - Insiders 1.45.0-insider (a250df703de955a38aed427a917bce8278ab3331, 2020-04-24T10:02:48.114Z)
OS version: Windows_NT x64 10.0.18363

![grafik](https://user-images.githubusercontent.com/530988/80974223-571b7d00-8e18-11ea-8e22-e2a1884c03b9.png)

**Comment by joaomoreno** [comment] 2020-05-11 09:19
![gif](https://media.giphy.com/media/voOhKPgzYsyPu/giphy.gif)

**Comment by joaomoreno** [comment] 2020-11-09 14:21
Dupe of https://github.com/microsoft/vscode/issues/109849, fixed in `master`.

**Closed by joaomoreno** 2020-11-09 14:21 UTC
Labels: bug, help wanted, ux
