### ISSUE TITLE
Executing Search/Replace on tens of thousands of files bricks VSCode and requires manually deleting workspace settings

### ISSUE THREAD

**Issue by jstine35** [microsoft/vscode#139381] opened 2021-12-17 15:03 UTC
Does this issue occur when all extensions are disabled?: YES

- VS Code Version:
```
$ code --version
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```
- OS Version:
```
$ uname -a
MINGW64_NT-10.0-19044 JStineWFH 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys
```

## Steps to Reproduce:

1. Open a workspace that contains 30,000+ text files (small files are fine, mine are 500 bytes each)
2. Attempt to perform a search/replace across all files, eg. where all 30,000 files are affected (replace foo ->bar)
3. Observe that VSCode shows only 20,000 results
4. Observe that VS.Code provides limited feedback that it's working (will it replace everything? will it replace only 20,000?? Is it doing anything at all?)
4. Attempt to repeat the search/replace because VS Code seems like it did something but there's still lots of unreplaced files
5. Repeat again. Because nothing seems to be happening.
5. Wait a while for things to explode - VSCode will eventually open 10k editor tabs and run out of file handles.
6. Close VSCode and try to reopen.
7. VSCode tries to open 10k tabs because it's trying to restore workspace, and crashes.

## There's several avenues to improving the UX here:

 - provide somewhat improved feedback when performing large search-replace.
 - Disallow parallel search-replace tasks (this is, I **think** parallel search-replace is part of this issue, but I'm not 100% sure it was , due to the lack of visual feedback)
 - Make it easier to wipe a workspace, eg add a command line option that either wipes the workspace, or prints out the fullpath to where workspace settings are kept (since these are stored in AppData on windows, for example)
 - Abstract/Virtualize your concept of editor tabs. It doesn't even make sense to have more file handles open than what's physically visible in the editor. Certianly it could be capped at 256 or 512 active handles. The rest of them can just be tracked virtually and recalled when they come into view (or when the IDE needs to query them for external changes). Tying each logical "editor tab" to a physical "file handle" is a bit rudimentary.

Any one of the above would be great ways to keep Code from feeling like it just perma-bricked itself into an unusable sate forever.

**Comment by roblourens** [comment] 2021-12-17 18:24
Duplicate of https://github.com/microsoft/vscode/issues/64485

You should not be seeing tabs open though. I can't repro that - it's likely that you have a misbehaving extension. For me, replacing 20k results is very fast but extensions can make this slower.

You can also change the default result size with `search.maxResults`. Only results that show in the list will be replaced.

**Closed by roblourens** 2021-12-17 18:24 UTC
