### ISSUE TITLE
Snap not opening on Manjaro 20.0.03 XFCE

### ISSUE THREAD

**Issue by spirulin** [microsoft/vscode#101728] opened 2020-07-04 22:44 UTC
- VSCode Version: Not really sure but the latest "Last updated
18 June 2020"
- OS Version: Manjaro 20.0.03

Steps to Reproduce:

1. Install
2. Launch

Does this issue occur when all extensions are disabled?: Yes

**Comment by 9at8** [comment] 2020-07-05 06:14
@spirulin can you show us what running `code --verbose` (or `code-insiders --verbose` if you are running insiders) from a terminal looks like?

**Comment by spirulin** [comment] 2020-07-05 18:24
code --verbose

> @spirulin can you show us what running `code --verbose` (or `code-insiders --verbose` if you are running insiders) from a terminal looks like?

Here it is:

```
Gtk-Message: 21:23:42.414: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:23:42.420: Failed to load module "canberra-gtk-module"
/usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/var/lib/snapd/snap/code/35/usr/share/code/../../lib/x86_64-linux-gnu/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
```

**Comment by ktw** [comment] 2020-07-06 06:02
Similar problems on Solus: (Both code and code-insiders)

```
/snap/code/35/usr/share/code/../../lib/x86_64-linux-gnu/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_hidden_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
Gtk-Message: 08:00:15.766: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:00:15.768: Failed to load module "canberra-gtk-module"

```

**Comment by 9at8** [comment] 2020-07-06 14:36
Looks similar to #77061

Maybe try this? https://github.com/microsoft/vscode/issues/77061#issuecomment-650144298

**Comment by joaomoreno** [comment] 2020-07-07 08:02
Dupe of https://github.com/microsoft/vscode/issues/77061

**Closed by joaomoreno** 2020-07-07 08:02 UTC
Labels: bug, linux, snap
