### ISSUE TITLE
debug - output doesn't show cos it's too large

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5802] opened 2016-04-26 09:28 UTC
#4952
- have code like this

```
        let longString = new Array(100001).join('oooooo ');
        longString += '<END>';    
        console.log(longString);
```
- ⚡ the console only shows a message about large output which is a big regression in comparison to the truncated message

![screen shot 2016-04-26 at 11 27 22](https://cloud.githubusercontent.com/assets/1794099/14813448/066f6652-0ba2-11e6-834e-e51b73fe9684.png)

**Comment by bpasero** [comment] 2016-04-26 11:08
@jrieken assigning back to you to retest this scenario with a newer Alpha build that includes our node-debug fix to actually enable debug injection for Electron.

**Comment by jrieken** [comment] 2016-04-26 12:27
disagree. we should not even have code that shows such a message, but it should truncate

**Comment by isidorn** [comment] 2016-04-26 12:42
Can not repro with latest alpha. We were always behaving like this, not a regression, removing important tag
Truncation is coming from [here](https://github.com/Microsoft/vscode/blob/master/src/bootstrap.js#L65)
@bpasero not sure if I can do something smarter there

**Comment by isidorn** [comment] 2016-10-06 15:00
Works for me now.

**Comment by jrieken** [comment] 2016-10-26 14:21
Nope, not for me

![screen shot 2016-10-26 at 16 20 55](https://cloud.githubusercontent.com/assets/1794099/19729711/37da8402-9b98-11e6-8caa-b19a8b6ac895.png)

**Comment by weinand** [comment] 2017-08-17 13:30
This works fine for "inspector" protocol (which is now supported for EH debugging).

**Comment by jrieken** [comment] 2017-08-29 15:23
Nope, using node 8.4.0 and inspect still shows this. The hover can show it, the console cannot. 

<img width="977" alt="screen shot 2017-08-29 at 17 23 07" src="https://user-images.githubusercontent.com/1794099/29829074-c8523f38-8cde-11e7-9438-2f8918182317.png">

**Comment by isidorn** [comment] 2017-11-13 18:03
This is happening due to the fact how we are computing height for strings here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L113

The computation is not 100% precise which shows in this huge string case. However since no user complained and this seems only visible for extremly long strings -> closing as will not fux until there is a real scenario where this bug hits us

**Comment by jrieken** [comment] 2017-11-14 07:47
Sorry, not sorry. After letting me verify and reopen this issue multiples (which costs time btw) I appreciate the acknowledgement this being an issue. But really, you are unable to count the newlines in a string?

**Comment by weinand** [comment] 2017-11-14 09:56
Let's fix this in November!

**Comment by jrieken** [comment] 2017-11-16 18:24
How about measuring the hover? That apparently can figure that it out

**Comment by isidorn** [comment] 2017-11-16 18:45
Hover in this case is not a tree, there we just but all the text and we set wrapping to true and the browser does everything nicely for us, so we do not have to compute.
Since the repl is the tree, the tree is implemented in such a way that each element needs to tell in advance what is the height (thus the computation).

**Comment by isidorn** [comment] 2019-02-20 11:31
Works now with the latest dynamic height in the tree. Yey.

**Closed by isidorn** 2019-02-20 11:31 UTC
Labels: bug, debug, verification-found
