### ISSUE TITLE
When the user creates a copy of a file, the copy is selected but no tab opens

### ISSUE THREAD

**Issue by hanak** [microsoft/vscode#122089] opened 2021-04-24 08:42 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Open VSCode.
2. Open a directory.
3. Create a file "file.txt" in the directory if there is none.
4. Close all tabs.
5. Click on the file "file.txt". This will open a tab. The explorer shows the file "file.txt" as selected.
![image](https://user-images.githubusercontent.com/178428/115953039-93dcfa00-a4e9-11eb-91de-c377c2556be0.png)

6. Press Ctrl+C followed with Ctrl+V. This will create a copy of the file "file copy.txt". The explorer shows the file "file copy.txt" as selected. However, no new tab opens.
![image](https://user-images.githubusercontent.com/178428/115952985-54aea900-a4e9-11eb-9bcf-367686004beb.png)

Actual:
No tab containing "file copy.txt" opens even though the explorer looks as if the user clicked on the copy. This leaves the tab "file.txt" the only open tab. Unless the user pays attention to the top of the VS Code window, the user will edit the original file instead of the copy.

Expected:
Option 1: VSCode opens the copy in a tab.
Option 2: VSCode does mark the copy as select in the explorer.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.1
swagger-viewer|Arj|3.0.1
vscode-svgviewer|css|2.0.0
gitlens|eam|11.4.1
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
vscode-test-explorer|hbe|2.19.6
twig-language-2|mbl|0.9.2
git-graph|mhu|1.30.0
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
vscode-phpunit|rec|2.0.76
vscode-yaml|red|0.18.0
jinjahtml|sam|0.16.0

</details>

**Comment by hanak** [comment] 2021-04-24 08:45
Suggested duplicate (#119187) shows a problem with the source control section while this issue shows a problem with the explorer section. Thus, it is unlikely, this is a duplicate of #119187.

**Comment by IllusionMH** [comment] 2021-04-24 20:27
/duplicate of #120882

Please upvote that issue

**Closed** 2021-04-24 20:28 UTC
Labels: *duplicate
