### ISSUE TITLE
Cutting/Deleting folded code affects only one line

### ISSUE THREAD

**Issue by PrzemyslawKlys** [Microsoft/vscode#60176] opened 2018-10-08 18:39 UTC
- VSCode Version: 1.28
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Have something like  this defined in powershell

![image](https://user-images.githubusercontent.com/15063294/46627151-d8763500-cb39-11e8-8578-d940ec12e1ad.png)

```powershell
    $Configuration = [ordered] @{
        Prettify       = @{
            CompanyName        = 'Evotec'
            UseBuiltinTemplate = $true
            CustomTemplatePath = ''
            Language           = 'en-US'
        }
        Options        = @{
            OpenDocument = $true
            OpenExcel    = $true
        }
        DisplayConsole = @{
            ShowTime   = $false
            LogFile    = "$ENV:TEMP\PSWinDocumentationADTesting.log"
            TimeFormat = 'yyyy-MM-dd HH:mm:ss'
        }
        Debug          = @{
            Verbose = $false
        }
    }
```

2. Fold it
3. Select it just like this (one full line)

![image](https://user-images.githubusercontent.com/15063294/46627186-f8a5f400-cb39-11e8-8cef-429d784f702b.png)

4. Moving/Deleting only affects one line not whole folded code block

Workaround is to select it with 2 lines like below

![image](https://user-images.githubusercontent.com/15063294/46627235-183d1c80-cb3a-11e8-885b-a6c98f590fcc.png)

Does this issue occur when all extensions are disabled?: Yes/No

Reference: https://github.com/PowerShell/vscode-powershell/issues/1563

**Comment by aeschli** [comment] 2018-10-12 08:48
duplicate of https://github.com/Microsoft/vscode/issues/59657

**Closed by aeschli** 2018-10-12 08:48 UTC
Labels: editor-folding
