### ISSUE TITLE
Search and replace does not find multiline strings

### ISSUE THREAD

**Issue by u458625** [Microsoft/vscode#39261] opened 2017-11-28 13:58 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.23.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
xml|Dot|1.9.2
php-intellisense|fel|2.0.1
file-icons|fil|1.0.7
auto-close-tag|for|0.5.3
code-runner|for|0.8.4
output-colorizer|IBM|0.1.2
csharpextensions|jch|1.3.0
mssql|ms-|1.2.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.1.0
vscode-icons|rob|7.18.1
code-spell-checker|str|1.5.1
vim|vsc|0.10.5
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

Description:
When searching for multi line strings it appears that the default behavior of the search is to strip newlines from the paste. This prevents the search function from matching the string and therefore prevents multi line search and replaces.

Steps to reproduce:
1. Copy code in "Code used" and paste into a new empty file in vs code several times. 
2. Ctrl F and paste the code in Search.
3. 0 matches found since newlines are stripped.

Text to be searched.
![image](https://user-images.githubusercontent.com/5900814/33323128-1c62f13e-d411-11e7-96ef-2afa5afe7b60.png)

Search and Replace Box:
![image](https://user-images.githubusercontent.com/5900814/33323209-57b3c16e-d411-11e7-8e10-923c029ece56.png)

Code used:
`# tmp = ""
# for r in relationships:
#     if r == relationships[-1]:
#         tmp = tmp + "\n\tnew ListItem() { Value = \"" + r + "\", Text = \"" + r + "\" }\n"
#     else:
#         tmp = tmp + "\n\tnew ListItem() { Value = \"" + r + "\", Text = \"" + r + "\" },"

# out = "return new ListItem[] { " + tmp + " };\n"

# print(out)`

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment] 2017-11-28 17:38
/duplicate of https://github.com/Microsoft/vscode/issues/13155

**Closed** 2017-11-28 17:38 UTC
Labels: *duplicate, search
