### ISSUE TITLE
Search In File does not return full result set

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#36477] opened 2017-10-18 10:40 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.2.22
code-runner|for|0.7.3
vscode-autohotkey|sle|0.2.1

![image](https://user-images.githubusercontent.com/6321426/31714582-d88101a2-b3ce-11e7-9c4b-90fe2414024a.png)

Well I want the entire set, I'm looking for every occurrence to apply a change throughout my project... 
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-19 00:26
I believe this is a duplicate of #30017

**Comment by icuurd12b42** [comment] 2017-10-19 02:36
Possible, but he did not mention a message and I initially thought he got more than I did but on second thought, I found out I had a backup folder under the folder structure in my project with about 100 versions of the project... making that 10000 value highly possible.... I think 10000 is a reasonable cutoff considering...

**Comment by roblourens** [comment] 2017-10-19 03:29
Yeah, the limit is there for perf reasons, and I don't plan to change it soon.

**Closed by roblourens** 2017-10-19 03:29 UTC
Labels: extensions
