### ISSUE TITLE
NPM scripts dont runs via buil-in tasks support.

### ISSUE THREAD

**Issue by NickolasGame** [Microsoft/vscode#28595] opened 2017-06-13 07:58 UTC
- VSCode Version: 1.13.0
- OS Version: Windows 10 64bit

In release notes is written what you can automatically run task from gulp, grunt, and npm scripts.
In example whats result from it is used new 2.0.0 version of tasks api.

If user want to run npm script via buil-in task system he (she) would probably see this:
![package json- -bootstrap- -visual-studio-code-13 06 2017-9_50_42](https://user-images.githubusercontent.com/21085814/27071994-a1e1b2aa-5027-11e7-8b4b-9dc9d0e16619.gif)

**Comment by dbaeumer** [comment] 2017-06-14 08:46
@egamma looks like the npm extension needs to check whether npm is installed.

**Comment by NickolasGame** [comment] 2017-06-14 11:38
And what is solution of this problem?

**Comment by dbaeumer** [comment] 2017-06-15 08:06
To not provide the task if npm is not install on the system or to prompt the user to install npm.

**Comment by NickolasGame** [comment] 2017-06-16 19:05
I dont think so, because it runs very good via cli.

**Comment by Livven** [comment] 2017-07-12 00:32
The built-in task support does not work for me either, though it seems because of a different reason since instead of an error message I get the `Usage: npm <command>` help screen similar to when you run `npm` by itself.

**Comment by stkb** [comment] 2017-07-12 14:19
@Livven Having the same problem; I opened #30488 for it.

**Comment by egamma** [comment] 2017-07-24 07:18
Closing as a duplicate of #30417. See this comment for a "work around".

**Closed by egamma** 2017-07-24 07:18 UTC
Labels: tasks
