### ISSUE TITLE
Apply search.exclude patterns to workspace symbol search as well

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#20579] opened 2017-02-14 04:12 UTC
There is a feature request to exclude certain folders from workspace symbol search in the Go extension.

Creating this issue here to discuss if it makes sense to use the `search.exclude` setting (or a new setting similar to it) and apply the same to workspace symbol search feature in the core product, so that individual extensions do not need to implement it.

Or one can argue that performance wise, it would be better if individual extensions do this exclusion rather than the core product filtering out given pattern.

cc @Microsoft/vscode

**Comment by chrmarti** [comment] 2017-02-14 15:03
Makes sense. What I sometimes miss in QuickOpen or global search is a quick way to turn the filters from settings off so I can search the entire folder. Might be similar here, but can be addressed later/separately.

Not sure if passing these filters around is something we would want the language server protocol to support or it maybe already supports. @mjbvz ?

**Comment by ramya-rao-a** [comment] 2017-02-14 21:30
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_symbol

The workspace symbol request could take additional param "exclude" for folder patterns to exclude.

cc @dbaeumer

**Comment by dbaeumer** [comment] 2017-02-15 06:56
If we change this we need to adopt the extension API and the language server protocol. Also I like letting the language server doing the filtering this might not be available in all servers and needs to be a dynamic capability. If the language server doesn't do the filtering could the workbench filter them out in a post processing step.

**Comment by jrieken** [comment] 2017-02-15 07:48
We have he same request for things like reference search, goto def. You might want to close this as dupe of #5749

**Comment by ramya-rao-a** [comment] 2017-03-29 00:36
Closing as dupe of #5749

**Closed** 2017-03-29 06:36 UTC
