### ISSUE TITLE
scss syntax highlighting: support @layer

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#199645] opened 2023-11-30 10:10 UTC
Issue of the SCSS grammar 
(We're still on the archived https://github.com/atom/language-sass)

`@layer` in 
```scss
@layer bootstrap;
@import url('bootstrap/scss/bootstrap.scss') layer(bootstrap);
```
not being highlighted is SCSS

**Comment by alexr00** [comment] 2023-12-01 08:01
Marking as a duplicate of the issue tracking finding a new scss grammar: https://github.com/microsoft/vscode/issues/81038

**Closed by alexr00** 2023-12-01 08:01 UTC
