### ISSUE TITLE
Don't show config issues in "Problems" window

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#36982] opened 2017-10-26 12:51 UTC
I have several configuration settings in my VS Code config (settings.json) that are unknown, either because I leave them in there for Linux so the setting isn't supported on Windows, or because they are "unsupported" config options that work nevertheless.  I don't think these "unknown configuration setting" warnings should be cluttering up the Problems tab, which should be reserved for issues with the project itself.

**Comment by sandy081** [comment] 2018-09-20 08:35
Duplicate of #33931

**Closed** 2018-09-20 08:36 UTC
Labels: *duplicate, error-list, feature-request
