### ISSUE TITLE
Nodejs Require autocomplete not working anymore

### ISSUE THREAD

**Issue by sonyarouje** [Microsoft/vscode#3135] opened 2016-02-18 19:19 UTC
Hi,
   I used VS Code since it launched, one of the feature i loved so much is the intellisense while adding a file using require when coding for node js.

After the latest update (Version: 0.10.8, Shell: 0.35.6) require intellisense is not working at all, it always says 'No suggestions'

Can someone help me to get the intellisense for 'require' command.

**Comment by laverite** [comment] 2016-02-18 21:42
+1

**Comment by codyrigney92** [comment] 2016-02-19 14:22
I'm guessing this is the same issue: https://github.com/Microsoft/vscode/issues/2923

**Comment by egamma** [comment] 2016-02-20 15:36
Closing as a duplicate of #2923

**Closed by egamma** 2016-02-20 15:36 UTC
