### ISSUE TITLE
500 internal server error installing vscode.d.ts

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#72446] opened 2019-04-16 22:39 UTC
Running npm install with `package.json` for our extension I see the following error:

Detected VS Code engine version: ^1.19.1
Error installing vscode.d.ts: Error: Request returned status code: 500
Details: Internal Server Error

**Comment by busticated** [comment] 2019-04-16 22:48
yep, i just got the same:

```
Detected VS Code engine version: ^1.27.0
Error installing vscode.d.ts: Error: Request returned status code: 500
Details: Internal Server Error
```

**Comment by nathan-alden-hp** [comment] 2019-04-16 22:52
Looks to me like their servers have issues. All the VS Code download links appear to be broken, too. I just get `Not Found`.

**Comment by mpiroc** [comment] 2019-04-16 23:10
I'm seeing the same for `^1.31.1`.

**Comment by theider** [comment] 2019-04-16 23:13
Getting not found on download from product web site:

https://update.code.visualstudio.com/latest/darwin/stable

**Comment by miaojiang** [comment] 2019-04-16 23:14
+1, seeing the same for 1.27.0

**Comment by IlyaBiryukov** [comment] 2019-04-16 23:17
Seems to be back online. Worked for me just now.

**Comment by octref** [comment] 2019-04-17 00:09
Duplicate of #72438.

Also just FYI, although this is not publicly released yet, if you are just using `vscode` module to get API for IntelliSense / diagnostics and not the testing script, you might be interested in `@types/vscode`. Read more in https://github.com/Microsoft/vscode/issues/70175.

**Closed by octref** 2019-04-17 00:09 UTC
