### ISSUE TITLE
xhr failed

### ISSUE THREAD

**Issue by Sakuara** [Microsoft/vscode#39319] opened 2017-11-29 14:35 UTC
- VSCode Version: Code 1.18.1 **[Unsupported]** (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
html-snippets|abu|0.1.0
ivue|dai|0.1.0
angular2-snippets|dan|1.0.16
vscode-html-css|ecm|0.1.8
vue-snippets|hol|0.1.5
vscode-angular2-emmet|jak|2.0.3
Angular1|joh|0.2.0
Angular2|joh|2.11.2
ionic1-snippets|jus|1.0.1
Angular-BeastCode|Mik|5.1.2
debugger-for-chrome|msj|3.5.0
generator-vue-components|Nic|0.1.5
vetur|oct|0.11.3
vuehelper|oys|0.1.0
vscode-html-scss|P-d|0.0.42
vue-beautify|pea|2.0.4
tsimporter|pmn|1.2.14
vue-vscode-snippets|sdr|1.2.0
background|sha|1.1.17
vue-ls|van|0.1.1
vue-ls-snippets|van|0.0.5

(1 theme extensions excluded)

---

Steps to Reproduce:

1. when select install plugins , it will show error : XHR failed.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-11-29 15:07
Duplicate of #34385

**Closed** 2017-11-29 23:00 UTC
Labels: *duplicate
