### ISSUE TITLE
Need VIM Mode

### ISSUE THREAD

**Issue by dukai** [Microsoft/vscode#847] opened 2015-12-01 08:16 UTC
Need VIM Mode,Thanks

**Comment by egamma** [comment] 2015-12-01 08:20
Duplicate of #300

**Comment by wmaurer** [comment] 2015-12-01 08:21
There are already two plugins with limited functionality
https://marketplace.visualstudio.com/items/vscodevim.vim
https://marketplace.visualstudio.com/items/74th.vimStyle

**Closed** 2015-12-01 08:20 UTC
Labels: feature request
