### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by hzjgithub** [microsoft/vscode#106666] opened 2020-09-14 15:38 UTC
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200913

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:13450:55)
    at getTextOfNode (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:13475:16)
    at Object.declarationNameToString (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:13787:66)
    at getDisplayName (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:39842:53)
    at declareSymbol (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:39956:111)
    at bindExportsPropertyAssignment (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:42066:17)
    at bindWorker (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41762:29)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41651:13)
    at bindExpressionStatement (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40716:13)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40201:21)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40142:94
    at Object.forEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40149:16)
    at bindEachFunctionsFirst (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40142:13)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40247:21)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at visitNode (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:27435:24)
    at Object.forEachChild (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:27565:21)
    at bindEachChild (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40152:16)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40250:21)
    at bindContainer (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40099:17)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41665:21)
    at Object.forEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40149:16)
    at visitNodes (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:27440:24)
    at Object.forEachChild (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:27618:24)
    at bindEachChild (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40152:16)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40250:21)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at Object.forEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40149:16)
    at bindCallExpressionFlow (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41077:21)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40229:21)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at bindReturnOrThrow (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40551:13)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40182:21)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40142:94
    at Object.forEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40149:16)
    at bindEachFunctionsFirst (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40142:13)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40247:21)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at visitNode (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:27435:24)
    at Object.forEachChild (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:27565:21)
    at bindEachChild (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40152:16)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40250:21)
    at bindContainer (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40099:17)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41665:21)
    at Object.forEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40149:16)
    at bindCallExpressionFlow (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41077:21)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40229:21)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at bindExpressionStatement (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40716:13)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40201:21)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41662:21)
    at c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40142:94
    at Object.forEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40149:16)
    at bindEachFunctionsFirst (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40142:13)
    at bindChildren (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40241:21)
    at bindContainer (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:40099:17)
    at bind (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:41665:21)
    at bindSourceFile (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:39708:17)
    at Object.bindSourceFile (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:39647:9)
    at initializeTypeChecker (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:77643:20)
    at Object.createTypeChecker (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:43696:9)
    at Object.getTypeChecker (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:104892:79)
    at synchronizeHostData (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:145287:21)
    at Proxy.getProgram (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:145369:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:150226:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:150159:42)
    at ConfiguredProject.updateGraph (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:151093:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:152797:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:153695:44)
    at c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:154018:97
    at Object.flatMap (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:154018:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:155037:46)
    at c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:156910:88
    at IOSession.Session.executeWithRequestId (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:156901:28)
    at IOSession.Session.executeCommand (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:156910:33)
    at IOSession.Session.onMessage (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:156934:35)
    at Interface.<anonymous> (c:\Users\hwsoft\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200913\node_modules\typescript\lib\tsserver.js:159150:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by mjbvz** [comment] 2020-09-14 18:19
Duplicate of https://github.com/microsoft/TypeScript/issues/40513

**Closed by mjbvz** 2020-09-14 18:19 UTC
