### ISSUE TITLE
Git: progress spins without stopping

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#36754] opened 2017-10-23 14:26 UTC
In todays insider build (`c1be82537d9fda852a258851f48ea78b7fc8a7a3`) I see the git viewlet progress spin without stopping (already saw this last week). am I the only one? this is in a multi root workspace. maybe related to decorations?

**Comment by maxibanki** [comment] 2017-10-23 14:47
I had this morning the same issue. I just tried to reproduce it, but I couldn't.

- VSCode Version: Code - Insiders 1.18.0-insider (c1be82537d9fda852a258851f48ea78b7fc8a7a3, 2017-10-23T04:18:13.902Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
xml|Dot|1.9.2
Go|luk|0.6.66
code-beautifier|mic|1.7.2
vscode-icons|rob|7.16.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

**Comment by joaomoreno** [comment] 2017-10-23 17:36
@jrieken In case you know something, since I haven't touched git in a while.

**Comment by jrieken** [comment] 2017-10-24 07:22
> but you might want to prevent that check-ignore operation from reporting progress?

How?

**Comment by jrieken** [comment] 2017-10-27 09:15
Closing as check for ignore files won't report progress anymore

**Closed** 2017-10-27 09:16 UTC

**Comment by Squiggle** [comment] 2017-10-27 09:18
Wow that was fast! I was just typing my response (I'll still post it here...)

I'm experiencing this issue (or similar?) in the latest production release (1.17.2) 64-bit, Windows 10.

It also renders the bottom left git buttons inoperable (synchronize changes, switching branch etc).

It works fine immediately after booting (for the first ~5 seconds), but then fails / freezes once my various console/debug/output console tabs etc. have finished loading.

**Comment by jrieken** [comment] 2017-10-27 13:34
> I'm experiencing this issue (or similar?) in the latest production release (1.17.2) 64-bit, Windows 10

I'd say similar because this is about 1.18.0-insiders
