### ISSUE TITLE
Duplicate files listed in search

### ISSUE THREAD

**Issue by sakthig** [Microsoft/vscode#56298] opened 2018-08-14 05:08 UTC
VSCode Version : 1.25.1
OS Version: 10.14 Beta

<img width="605" alt="screenshot 2018-08-14 at 10 18 43 am" src="https://user-images.githubusercontent.com/101381/44072701-12baf80c-9fae-11e8-8e1c-393e080da9f4.png">
<img width="288" alt="screenshot 2018-08-14 at 10 18 51 am" src="https://user-images.githubusercontent.com/101381/44072702-12f8bd18-9fae-11e8-91c1-911fdfad7f5a.png">

When i search for header file. Two files are listed with different Cases, both seem to be pointing to same file. But only one file exists in that folder.

**Comment by roblourens** [comment] 2018-08-14 16:14
Duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by roblourens** 2018-08-14 16:14 UTC
Labels: search
