### ISSUE TITLE
'Go to Symbol in Workspace' doesn't work unless an editor of the language is open

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#23584] opened 2017-03-29 16:08 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:05:18.022Z)
- OS Version: Darwin x64 16.5.0

`Go to Symbol in Workspace` only seems to work if there is at least one editor of a particular language open. For example, in order to get workspace symbols in Typescript, I need to have at least 1 Typescript file open, same with C#. If I have no editors open then there no symbols are shown.

---

Steps to Reproduce:

1. Open a folder (Typescript, C#, a mix, etc)
2. With no editors open, do a symbol search for a known symbol
3. No results will be displayed

1. Open a folder with more than 1 language (Typescript & C# for instance)
2. Open a Typescript file
3. Do a symbol search for a known Typescript symbol
4. Results will be displayed
5. Do a symbol search for a known C# symbol
6. No results will be displayed
7. Open a C# file
8. Do a symbol search for a known C# symbol
9. Results will be displayed

**Comment by chrmarti** [comment] 2017-03-31 18:47
Also in 1.10.2.

**Comment by mjbvz** [comment] 2017-04-03 22:16
Thanks. This looks like a duplicate of #17022

**Closed by mjbvz** 2017-04-03 22:16 UTC
Labels: duplicate, javascript, typescript

**Comment by mjbvz** [comment] 2017-04-03 22:18
Try following up with the C# extension to see if this is something they can look into as well
