### ISSUE TITLE
Possible to set a fixed width of integrated terminal (when terminal is located at left or right side)

### ISSUE THREAD

**Issue by danielbenjaminsson** [microsoft/vscode#112549] opened 2020-12-15 11:06 UTC
Possible to set a fixed width of integrated terminal (when located at left or right side).
Currently, it change width automatic when you toggling sidebar on/off.

**Comment by meganrogge** [comment] 2020-12-15 18:42
Duplicate of #74501

**Closed by meganrogge** 2020-12-15 18:42 UTC
