### ISSUE TITLE
Bug in using Ctrl+D to select same words or characters

### ISSUE THREAD

**Issue by papalugo** [Microsoft/vscode#26501] opened 2017-05-12 01:14 UTC
- VSCode Version: 1.12.1
- OS Version: Linux Ubuntu 16.04

Steps to Reproduce:

Hello, sorry my Engles.... But I believe I have found one Bug in VS Code, looking two frases bellow. Making a test. Select <br> and after press Crtl+D for many times, in first frase all <br> were Selected. Repeat same test with second frase, the selection will stop when there are two <br> together.

Thanks.

**Comment by egamma** [comment] 2017-05-12 06:35
@papalugo thanks for the issue report, can you please add an animated gif that illustrates the problem. Cannot reproduce the issue given steps above.

**Comment by papalugo** [comment] 2017-05-12 10:53
Hello, attached there are cases, case-1 is ok, case-2 there is a problem,
see a tag <br> is together in this case when press Ctrl+D last tag <br>
isn't seleced. It is a problem.

In case-3 the tag was separeted of <br><br> to <br> <br> and funcionality
returned stay ok.

Thanks.

Claudinei Comin

Em sex, 12 de mai de 2017 às 03:36, Erich Gamma <notifications@github.com>
escreveu:

**Comment by egamma** [comment] 2017-05-14 06:51
@papalugo thanks for following up but in this case a picture is so much better than words. Can you please add an animated GIF that illustrates the problem.

**Comment by papalugo** [comment] 2017-05-14 11:26
See case-2, last <br>.

Att.
Comin

Em dom, 14 de mai de 2017 às 03:52, Erich Gamma <notifications@github.com>
escreveu:

**Comment by alexandrudima** [comment] 2017-05-19 19:11
Duplicate of #6661

**Closed by alexandrudima** 2017-05-19 19:11 UTC
