### ISSUE TITLE
format document to html

### ISSUE THREAD

**Issue by feiyingcheung** [Microsoft/vscode#22122] opened 2017-03-07 03:50 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|GBKtoUTF8|bukas|0.0.2|
|cpptools|ms-vscode|0.10.2|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.0.11|
|vscode-icons|robertohuertasm|7.3.0|;

---
When auto format a html file, the CSS code would insert a space-line between styles.

Steps to Reproduce:

1.Just use "Format Document" format the html file which had multi-CSS styles.

**Comment by anchenbaba** [comment] 2017-03-07 06:18
yes,   i have the same problem.
vscode vesion is   1.10.1

**Comment by anchenbaba** [comment] 2017-03-07 06:21
so  i disable the style
"html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, select, small, span, strong, sub, sup, textarea, tt, var, style"

**Comment by aeschli** [comment] 2017-03-08 16:20
duplicate of #21717

**Closed by aeschli** 2017-03-08 16:20 UTC
Labels: html
