### ISSUE TITLE
Finish editing of CLI specified file should end --wait

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31547] opened 2017-07-27 10:00 UTC
testing #30717:

I would expect that the "--wait" ends when the file specified as a CLI argument is closed in the editor. The current model of when "--wait" ends appears to me less intuitive.

In the following cases "--wait" did not end (but I was expecting that it would end):
- launch "code --wait foo.txt" and open a second file "abc.txt" in the same window. Close the editor with "foo.txt". Now I would expect the "--wait" to end but VS Code to stay open.
- launch "code --wait foo.txt" and load a folder in the same window. Now foo.txt is definitively not open any more but  "--wait" does not return.

**Comment by bpasero** [comment] 2017-09-11 06:20
Marking as duplicate of https://github.com/Microsoft/vscode/issues/24327 and https://github.com/Microsoft/vscode/issues/34116 (which is a good catch!).

**Closed by bpasero** 2017-09-11 06:20 UTC
Labels: feature-request, workbench
