### ISSUE TITLE
The terminal path isn't matching with the working directory if '[' in the directory name

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#117681] opened 2021-02-25 13:49 UTC
Issue Type: <b>Bug</b>

If the directory name has **[** in it, the terminal path isn't matching.
I've tried some other symbols like **]{ }**, They all works well. 

_The bug can reproduce like in the pictures below._

![image](https://user-images.githubusercontent.com/24863266/109161393-f2b81880-77b1-11eb-82cf-26b3f8231bc6.png)
![image](https://user-images.githubusercontent.com/24863266/109161589-34e15a00-77b2-11eb-9db6-9c2da0b9c91c.png)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.23GB free)|
|Process Argv|C:\\Users\\bao00\\Desktop\\a[bc --crash-reporter-id 6fb4bb53-74d0-46d2-9639-3b0e028195bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.4
jupyter|ms-|2021.2.576440691

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30262999

```

</details>

**Comment by meganrogge** [comment] 2021-02-25 18:45
Duplicate of #116583

**Closed** 2021-02-25 18:46 UTC
Labels: *duplicate
