### ISSUE TITLE
[feature request] close IntelliSense popup on file save

### ISSUE THREAD

**Issue by samuela** [Microsoft/vscode#38478] opened 2017-11-16 05:46 UTC
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6

IntelliSense is great, albeit pretty eager at times. It would be great if it automatically hid once the user saves the file. Presumably a file save corresponds to the user having just written whatever they wanted to anyways so there's really no need to keep the IntelliSense popup hanging around. I find myself doing this cmd-s, esc key combination constantly in VSCode.

I've noticed that Atom implements this feature and while I didn't even think about it being there at the time, now I sorely miss it.

**Comment by usernamehw** [comment] 2017-11-18 12:11
If this is not gonna be implemented you can use [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros)

`settings.json`
```json
"macros": {
    "saveAndHideSuggest": [
        "workbench.action.files.save",
        "hideSuggestWidget"
    ]
}
```
`keybindings.json`
```json
{
    "key": "ctrl+s",
    "command": "-workbench.action.files.save"
},
{
    "key": "ctrl+s",
    "command": "macros.saveAndHideSuggest"
}
```

**Comment by jrieken** [comment] 2017-12-11 11:54
dupe of #26488

**Closed by jrieken** 2017-12-11 11:54 UTC
Labels: suggest, under-discussion
