### ISSUE TITLE
API: No way to find out that an editor has closed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#643] opened 2015-11-25 18:37 UTC
For the VS Code API tests I have a clean up function that signals that it is done when all editors are closed. Currently the solution is hacky, it needs to install a setInterval to periodically check on the `vscode.window.visibleTextEditors` property to eventually become 0 (see https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/utils.ts#L52).

The issue is that the `window.onDidChangeActiveTextEditor` event is not good enough for testing on the visible text editors as shown by the following test:

```
test('visibleTextEditors', () => {
	return workspace.openTextDocument(join(workspace.rootPath, './far.js')).then(doc => {
		return window.showTextDocument(doc).then((editor) => {
			return new Promise((c, e) => {
				const listener = window.onDidChangeActiveTextEditor(d => {
					console.log('editor is null?: ' + !d);
					if (window.visibleTextEditors.length > 0) {
						console.log('visibleTextEditors count is: ' + window.visibleTextEditors.length);
						return;
					}

					listener.dispose();
					c();
				});

				commands.executeCommand('workbench.action.closeAllEditors').then(null, e);
			});
		});
	});
});
```

The value passed in from the event is null as expected because I am running the close all editors action. However, `window.visibleTextEditors.length` is still 1 at that point.

**Comment by jrieken** [comment] 2015-11-26 09:15
@bpasero I don't see `setInterval` in your code.

@alexandrudima I think this is a duplicate of the editor change event firing to often

**Comment by bpasero** [comment] 2015-11-26 09:37
@jrieken https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/utils.ts#L52

**Comment by alexandrudima** [comment] 2016-07-04 15:58
@jrieken Maybe a new `onDidChangeVisibleTextEditors` ?

**Comment by jrieken** [comment] 2016-10-13 08:41
fyi @joaomoreno - please give it a try

**Closed** 2016-10-13 08:40 UTC
Labels: api, feature-request

**Comment by joaomoreno** [comment] 2016-10-13 14:34
Seems to work like a charm. 🎆
