### ISSUE TITLE
Quick Fix menu isn't scrollable

### ISSUE THREAD

**Issue by ConduciveMammal** [microsoft/vscode#173041] opened 2023-02-01 15:36 UTC
Type: <b>Bug</b>

Granted, code should **never** be this bad, however, when the quick fix menu has too many problems, the menu isn't scrollable so the bottom can't be reached.

https://share.cleanshot.com/VZQTTbXM

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id 4a9c861e-8151-46a8-904b-dc014f93ec08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
polaris-snippets|And|0.1.2
markdown-checkbox|bie|0.4.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
coddx-alpha|cod|0.3.1
vscode-code-review|d-k|1.33.1
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.2.6
vscode-dash|dee|2.4.0
vscode-axe-linter|deq|4.5.0
githistory|don|0.6.19
jquerysnippets|don|0.0.1
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
vscode-graphql|Gra|0.8.5
vscode-graphql-syntax|Gra|1.0.6
vscode-drawio|hed|1.6.6
vscode-env|Iro|0.1.0
web-accessibility|Max|0.2.83
fluent-icons|mig|0.0.18
vscode-autoprefixer|mrm|3.0.1
vscode-remark|mrm|1.2.1
vscode-scss|mrm|0.10.0
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.3
vsliveshare|ms-|1.0.5823
vsliveshare-pack|ms-|0.4.0
language-liquid|nei|0.1.1
vsnotes|pat|0.7.1
material-icon-theme|PKi|4.23.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.11.0
LiveServer|rit|5.7.9
vscode-javascript-booster|sbu|14.0.1
bash-beautify|sha|0.1.1
polaris-for-vscode|Sho|0.2.0
theme-check-vscode|Sho|1.9.5
vscode-stylelint|sty|1.2.3
shellcheck|tim|0.29.3
vscode-mdx|uni|1.2.1
vscode-sort-package-json|uni|1.3.0
intellicode-api-usage-examples|Vis|0.2.7
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2
zeplin|Zep|2.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
89544117:30613380
pythonsymbol12cf:30652349
a9j8j154:30646983

```

</details>

**Comment by mjbvz** [comment] 2023-02-01 18:46
Duplicate of #168955

**Closed by mjbvz** 2023-02-01 18:46 UTC
