### ISSUE TITLE
VS Code terminates if when clicking Debug -> Start without Debugging for extension tests

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#81090] opened 2019-09-18 09:16 UTC
- Run `yo code` to generate the sample TypeScript extension
- Open in VS Code
- Click `Debug` -> `Start Without Debugging`
- VS Code completely vanishes

It used to output a message about not being able to run tests from the command line while an instance of VS Code is open (a slightly misleading message, and a frustrating limitation, but at least it was clear what happened). Now, VS Code just disappears as if it crashed. This seems like rather undesirable behaviour.

I often run things without the debugger when I know I won't be debugging (for various reasons) so out of habit I often hit Ctrl+F5. Having to restart VS Code seems like a high penalty for that mistake :-)

**Comment by isidorn** [comment] 2019-10-16 10:12
@DanTup nice catch, thanks for filling this. I can reproduce.
I can also reproduce it with the current stable version and the previous stable version. So it seems like we always had this, just people did not hit it. Thus this is not a candidate. 
Investigating

**Comment by DanTup** [comment] 2019-10-16 10:18
> I can also reproduce it with the current stable version and the previous stable version.

It hasn't always been this way - it used to print a message in the console like "running tests from the command line is only possible when no instance of VS Code is open" (I always found the message amusing, since I wasn't running from the console - I guess it was triggered by not having the debugger attached - though honestly I don't understand why that limitation exists).

I agree it's not a priority though, the impact is low (though it is a little frustrating for those of us when we do hit it :-))

**Comment by isidorn** [comment] 2019-10-22 15:22
I can repro this all the time. However I am pretty clueless who is closing the window.
What I found is that it is not the debug service closing the window [here](https://github.com/Microsoft/vscode/blob/590a0595053f34bcdea30fd4758ee81e5c1629b0/src/vs/workbench/contrib/debug/browser/debugService.ts#L536)

Trying to find out who calls [electronService.closeWindow](https://github.com/Microsoft/vscode/blob/590a0595053f34bcdea30fd4758ee81e5c1629b0/src/vs/platform/electron/node/electron.ts#L78). Also produced no effect.

@weinand @bpasero might you have ideas who might close the first window when debugging EH tests with NoDebug flag?

**Comment by bpasero** [comment] 2019-10-22 15:34
I cannot reproduce, a new window opens with the extension being debugged. I tried insiders and out of sources, 😩

**Comment by bpasero** [comment] 2019-10-22 15:35
Oh this is running tests, yeah I see it...

**Comment by bpasero** [comment] 2019-10-22 15:38
@isidorn seems to be this code:

https://github.com/microsoft/vscode/blob/ff026e06014fdcb2a837c18d6b526bcfa9ff920c/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L555

If you run code with `--verbose` you see more output:

```
...
CommandService#executeCommand setContext
  1 passing (10ms)
[main 2019-10-22T15:37:12.011Z] IPC#vscode:exit null
[main 2019-10-22T15:37:12.012Z] Lifecycle#kill()
[main 2019-10-22T15:37:12.013Z] Lifecycle#window.on('closed') - window ID 1
[main 2019-10-22T15:37:12.017Z] Lifecycle#window.on('closed') - window ID 3
```

**Comment by weinand** [comment] 2019-10-23 09:34
The problem is the definition of the environment flag `isExtensionDevTestFromCli`:

https://github.com/microsoft/vscode/blob/7ee0e02883828d1137cb8fa8ad8a137540d93d9b/src/vs/workbench/services/extensions/common/extensionDevOptions.ts#L32

This flag should not become true when launching an extension (or its tests) from the debugger (even if "Start without Debugging" is used).

But the condition `environmentService.debugExtensionHost.break` is not correct because when "Start without Debugging" is used, the value of "break" is false, but the extension is still launched from the debugger.

The correct condition is `environmentService.debugExtensionHost.debugId`

**Closed** 2019-10-23 09:37 UTC
Labels: bug, debug

**Comment by bpasero** [comment] 2019-10-23 09:41
Thanks!
