### ISSUE TITLE
Open file is searched despite being excluded in `search.exclude`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#120295] opened 2021-04-01 03:16 UTC
- VS Code Version: 1.55.0
- OS Version: Windows 10

Steps to Reproduce:

1. exclude a  file in `search.exclude`
2. keep this file open
3. perform a global search for text this file contains
4. this file shows up in the search result despite being excluded in `search.exclude`

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2021-04-01 06:09
Duplicate of #31819

**Comment by roblourens** [comment] 2021-04-05 15:15
Yes, thanks @yume-chan

**Closed by roblourens** 2021-04-05 15:15 UTC
