### ISSUE TITLE
Better Syntax Error Highlighting

### ISSUE THREAD

**Issue by raptor235** [Microsoft/vscode#49930] opened 2018-05-15 19:35 UTC
Is there any plans on improving syntax highlighting... it would be great to be able to highlight the entire line of code that's breaking vs just the small squlighly line under the letter which is very hard to spot...

ie

![image](https://user-images.githubusercontent.com/313825/40079346-96dcafb8-5855-11e8-80ee-d1a628bba09a.png)

**Comment by usernamehw** [comment] 2018-05-15 20:29
Duplicate of #16222 or #9209

**Closed** 2018-05-21 06:29 UTC
Labels: editor, editor-core, needs more info
