### ISSUE TITLE
File explorer rendering issues

### ISSUE THREAD

**Issue by huttarichard** [Microsoft/vscode#48938] opened 2018-04-30 09:02 UTC
**First of all, love vscode ❤️** 
amazing job

- VSCode Version: Version 1.22.1 (1.22.1)
- OS Version: 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd

Steps to Reproduce:
Not able to reproduce this, since it takes time to trigger this issue.

It gets really annoying when you work on project and from some reason files start disappearing or you see folders which should not be there or you are looking for file which exists in system but not visible in explorer.

![screen shot 2018-04-30 at 10 31 55](https://user-images.githubusercontent.com/1809268/39420253-fdf37770-4c63-11e8-887a-88c92273fd6f.png)

Note:
 - scrollbar position
 - files in relation to scrollbar
 - top level folder `electrious` which should not be there
 - folder database on bottom continues on top until electrious folder, but definitively few files missing

I originally opened project with `code .` and `.` is referring to folder called electrious. Normally when you open folder like that you will not see the folder itself rather content in it. In my case electrious folder should not be there. And when I open project or click refresh button it disappears.

If you take a look on screenshot, you can see that scrollbar is on very top, and files above `electrious` folder are actually files which can be found in project, but rendered incorrectly.

Its happening after few hours of work. Therefore hard for me to test this with `--disable-extensions` since I need golang extensions very badly.

Im using these maybe we can blame one of them?

```
HookyQR.beautify
PeterJausovec.vscode-docker
eg2.tslint
henriiik.docker-linter
jock.svg
lukehoban.Go
mikestead.dotenv
mitaki28.vscode-clang
ms-python.python
ms-vscode.cpptools
peterj.proto
streetsidesoftware.code-spell-checker
tomoki1207.pdf
vncz.vscode-apielements
```

Does this issue occur when all extensions are disabled?: 
Tried that not happened so far, but as I said takes time to trigger this problem.

**Comment by isidorn** [comment] 2018-05-02 08:14
Duplicate of some already open issue like https://github.com/Microsoft/vscode/issues/48966#event-1602301996
fyi @joaomoreno this seems to be becomming more common

**Closed by isidorn** 2018-05-02 08:14 UTC
