### ISSUE TITLE
Env vars from one configuration bleed into another

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#83187] opened 2019-10-23 22:08 UTC
Issue Type: <b>Bug</b>

I've seen this multiple times but when I tried to come up with a repro it wasn't consistent.  I've got an environment variable DISABLE_SLOW tests defined as "1" in one configuration but not in a second. After using the first configuration for a while, then switching to the second, I'm finding that DISABLE_SLOW is stilled set to the value "1" from the first configuration even though it's not set at all in the second.

EXPECTED: Env vars set in one configuration shouldn't hang around and affect another.

Here are my configurations from launch.json:
```
        {
            "name": "Launch Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/out/test"
            ],
            "stopOnEntry": false,
            "sourceMaps": true,
            // outFiles is used for locating generated JavaScript files, see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm: compile",
            "env": {
                "MOCHA_grep": "", // RegExp of tests to run (empty for all)
                "MOCHA_invert": "0", // Invert the RegExp
                "AZCODE_ARM_IGNORE_BUNDLE": "1",
                "MOCHA_enableTimeouts": "0", // Disable time-outs
                "DEBUGTELEMETRY": "1", // 1=quiet; verbose=see telemetry in console; 0=send telemetry
                "NODE_DEBUG": "",
                "DISABLE_LANGUAGE_SERVER_TESTS": "0",
                "DISABLE_SLOW_TESTS": "1"
            }
        },
        {
            "name": "Launch Tests (webpack)",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/dist/test"
            ],
            "stopOnEntry": false,
            "sourceMaps": true,
            // outFiles is used for locating generated JavaScript files, see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ],
            "preLaunchTask": "npm: pretest-dev",
            "env": {
                "MOCHA_grep": "", // RegExp of tests to run (empty for all)
                "MOCHA_invert": "0", // Invert the RegExp
                "MOCHA_enableTimeouts": "0", // Disable time-outs
                "DEBUGTELEMETRY": "1", // 1=quiet; verbose=see telemetry in console; 0=send telemetry
                "NODE_DEBUG": "",
                "AZCODE_ARM_IGNORE_BUNDLE": "0"
            }
        }
```

VS Code version: Code - Insiders 1.40.0-insider (c58aaab8a1cc22a7139b761166a0d4f37d41e998, 2019-10-22T05:27:32.053Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.2.2
azurerm-vscode-tools|msa|0.7.0

</details>

**Comment by isidorn** [comment] 2019-10-24 08:53
This is related to how we start the EH window since the env vars seems to be preserved.
Thus also assigning to @weinand

**Comment by weinand** [comment] 2019-10-24 09:36
Env vars set in one ("extensionHost" debugging) configuration shouldn't hang around and affect another.
If they do, this is a bug.

**Comment by hyangah** [comment] 2020-11-13 04:30
I was bitten by this bug this week - made our released extension behave in test mode in my vscode. 
If it can be fixed soon, is there any easy walkaround to unset/recover polluted env vars automatically after using the configuration?

**Comment by weinand** [comment] 2020-11-25 09:33
As a workaround you can unset env variables with the value `null`, e.g. 
```
            "env": {
                "NODE_DEBUG": null
            }
```

**Comment by weinand** [comment] 2020-11-25 11:38
This problem only occurs on Windows.

**Closed** 2020-11-25 18:24 UTC
Labels: bug, debug

**Comment by hyangah** [comment] 2020-11-25 18:39
Thanks for the fix! 
This problem occurred on Mac OS and Linux too.

**Comment by weinand** [comment] 2020-11-25 22:00
@hyangah I was not able to reproduce the problem on macOS or linux, but I have no explanation why.
My fix is in no way platform specific.
