### ISSUE TITLE
Markdown Hover images broken

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode#80352] opened 2019-09-05 01:35 UTC
- VSCode Version: 1.38.0
- OS Version: Windows 10

I have hovers as `MarkdownString` containing the following:

`[![alt text](${imageUri})](${linkUri})`

The `imageUri` is a `file` URI to a local PNG image. Instead of the image, it now shows 
![image](https://user-images.githubusercontent.com/22951521/64304836-667dba00-cf5b-11e9-9959-f1ddbbc01e19.png) with the alt text.

This issue _started_ with v1.38.0, so is a regression.

**Comment by KamasamaK** [comment] 2019-09-05 18:01
I've done some searching and found a similar issue microsoft/vscode-remote-release#465. Note that this is _not_ using any remote dev. The recommendation in https://github.com/microsoft/vscode-remote-release/issues/465#issuecomment-506724863 from @jrieken  is what I was following, which is to use `vscode.Uri.file(extensionContext.asAbsolutePath(...)).toString()`.

I've used the integrated element inspector and found that the `<img>` tags _only_ have an `alt`.

**Comment by sbatten** [comment] 2019-09-05 18:07
assigned to @jrieken since you might know more

**Comment by jrieken** [comment] 2019-09-06 08:01
@KamasamaK Do you have a pointer to your extension - sources or extension itself?

**Comment by jrieken** [comment] 2019-09-06 08:45
I could reproduce with `kisstkondoros.vscode-gutter-preview` 

```css
h3 {
    color: red;
    background-image: url("./symbol-sprite.svg")
}
```

* have above CSS snippet, make sure that the SVG exists
* hover over `url`
* 🐛 no images is shown, the `insane` library seems to remove the `src` attribute 😱 

<img width="606" alt="Screenshot 2019-09-06 at 10 43 24" src="https://user-images.githubusercontent.com/1794099/64414163-2a4d7500-d093-11e9-88c7-f72bb9bd9df2.png">

**Comment by jrieken** [comment] 2019-09-06 08:57
@mjbvz The seems to be that we don't allow the `file` scheme. I am not sure if that's on purpose or an oversight. Then the `vscode-remote` scheme is missing as well.

**Comment by jrieken** [comment] 2019-09-06 09:03
The issue might actually be bigger, e.g I can contribute a file system for the `foo`-scheme and it should be valid/possible to generate links like so `[path.foo](foo:///some/path.foo)`. I think we should remove the scheme restriction all together. Risky links should still be taken care of with this: https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/base/browser/markdownRenderer.ts#L102

**Comment by jrieken** [comment] 2019-09-06 09:22
Ok, it looks like `insane` cannot be configured to allow all schemes... Unless I am missing something with `insane` we might need to extend `MarkdownRenderOptions` with a set of schemes that we populate at the places that have service access (requires to add `IFileService#schemes`)

**Comment by mjbvz** [comment] 2019-09-09 16:35
I suspect that `file` will cover the vast majority of use cases (and is the safer fix for a recovery)

**Closed** 2019-09-09 16:41 UTC
Labels: bug, candidate, markdown, regression
