### ISSUE TITLE
Do not close file if it disappears from disk.

### ISSUE THREAD

**Issue by LBensman** [Microsoft/vscode#49835] opened 2018-05-14 14:45 UTC
Issue Type: <b>Feature Request</b>

I'm on macOS and am using vscode to open files that are on a remote machine via sshfs mount point.  The sshfs mount point is linked to a machine that is only accessible via VPN tunnel.  If tunnel disappears or remote site is down (or unfortunately due to sshfs own stability issues), vscode often closes the tab with file with ENXIO error message saying something to the effect that file no longer there.  While technically-speaking the file isn't immediately there, in reality it is, or rather will be restored once the link has been restored.  I haven't quite figured out when, but vscode tends to remove the file from MRU list as well (though not always - might be only when I try to open recent when link is down, and then it removes it from there).

I experimented with    `"workbench.editor.closeOnFileDelete": false`   setting, but that one sometimes shows "file.cpp [Deleted from disk]" and at other times just nukes the tab.

Feature request is to have a similar setting that would simply prevent closing tabs or removing files from MRU when the file is not detected on system, especially for those cases when vscode can potentially detect that a directory in the path is a mount to a remote/detachable file system.

P.S. on the fence as to the classification between Feature Request and Bug-Report.  File being closed (even if not dirty) without intent has a bit of a buggy feel, but opted for feature request classification on the premise of special case where file is via a path mounted to remote system.  Feel free to change classification if it makes more sense for it to be classified as a bug.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 16.7.0

**Comment by bpasero** [comment] 2018-05-15 04:25
@LBensman the setting `"workbench.editor.closeOnFileDelete": false` is meant for this scenario, can you give me steps to reproduce how to still see tabs disappear even when this setting is on?

**Comment by LBensman** [comment] 2018-05-15 17:36
@bpasero , then it probably, indeed, more of a bug report than feature request ;)

I don't have solid and definitive steps to reproduce the issue at will - at least I haven't found them so far.  I'll be happy to aid in collecting and crystallizing the exact steps, and will update the thread as I find more.  However, here is some additional info and context:

As mentioned before, the path to the files that vscode nukes from open files are all over sshfs mount directory located on the remote machine.  I tried killing sshfs connection while having those files open (via `diskutil unmount force <mountpoint>`), but that did make vscode show "[deleted from disk]" marker rather than close.  It usually happens when I open my mac in the morning and it comes back from sleep: vpn is gone, and if sshfs fubars and doesn't handle it right, then when I command+tab to vscode, the issue occurs.  Note that it doesn't occur every time and after every hybernation.  Only sometimes.  But when it does, vscode displays ENXIO message at the bottom right corner.  I'll post screenshot when it happens again (usually once a week to every other week).

If you want me to turn on additional logging that I can pass to you when it does happen again, let me know what and where.

**Comment by bpasero** [comment] 2018-05-15 18:10
@LBensman I think there is still a case where tabs can close even if this setting is turned on:
* open some tabs behind an active one (just open some and only one is active)
* close VS Code
* start VS Code
* delete files from tabs that are inactive

=> the tab closes

In other words, we only preserve tabs that have been opened in the current session.

Is that what you see?

**Comment by LBensman** [comment] 2018-05-18 20:55
It's hard to say b/c I tend to keep vscode open for weeks, and wouldn't remember if a particular file was auto-reloaded on start or opened during the session.

What is the rationale for the distinction if it was opened during this session or not?  It seems it shouldn't really matter if the file was re-loaded from previous session - if mount point disappears unexpectedly, whether I opened those files just recently or vscode had been restarted, I still don't want them to be nuked from the editor.

**Comment by bpasero** [comment] 2018-05-19 04:46
@LBensman the reason is simple: if the file was not opened during the current session it means we do not have its contents loaded into memory. So when you click this tab now, what content should we show? Best we could do is showing an empty file (possibly dirty), but is that helpful?

**Comment by LBensman** [comment] 2018-05-22 23:27
@bpasero hmmm. Well, technically you don't have to show an empty file.  Thinking about Notepad++, I know that it is able to persist contents of buffers even if those were never saved to disk (i.e. not associated with any file; they were just newed, typed it, npp shut down, then restarted, and voila, content still there).  I believe it also is able to do the same with files that were loaded from disk, modified but not saved, and still show contents if the file is gone when npp is loaded again, though that stands to be verified (I don't believe it does that if file buffer wasn't dirty).  VS Code could keep internal persistence of all open files (regardless of dirtiness) to restore content of on startup, and then treat lack of associated file on disk as if file on disk was deleted while it was opened during current session.  I understand there are implications for very large files, etc., but perhaps npp behavior is an approximate guide.  And possibly a config setting to control current vs this modified behavior?

As for helpfulness.  My specific case, although I'd imagine it's not all too unique to me, is that I often have 10+ files opened from remote system that tend to be deep in repository (as in scattered throughout repository) (in the left panel, and a bunch of local files in my right panel).  Having all these files disappear from the editor, and then chasing them throughout the repository to reopen them (once sshfs mount is reestablished), and then re-arranging them in left and right panels*** is time-consuming at minimum.  Loosing position with files can mean starting chasing the call-graph again over some unfamiliar code that can take a good chunk of time.

So, yes, not having my workspace mutate due to temporary loss of connectivity to remote share would be very useful (to me, at least 😄 ). 

*** Many files are the same remote and local, and the reason I keep both copies open is because remote machine is an expensive shared development server with specialized hardware and requires editing code and building it there.  However, to commit files, I have to copy them locally so commits go under my name rather than name under which files on remote server were checked out.  Another case is there are several log files in various folders that I tend to keep open as well.  Having those close also wastes time chasing them, as well as loosing position in them.

**Comment by bpasero** [comment] 2018-05-23 03:46
Duplicate of https://github.com/Microsoft/vscode/issues/46431

**Closed by bpasero** 2018-05-23 03:46 UTC
Labels: needs more info

**Comment by LBensman** [comment] 2018-05-25 22:55
By the way, I just noticed that it closes files that I was editing an hour ago (closed lid, moved places, connected to a different wifi, reestablished vpn, but forgot to check on sshfs mounts).  Closed files that it definitely had contents in its buffers.

**Comment by bpasero** [comment] 2018-05-26 04:55
@LBensman I cannot explain that behaviour, that should definitely not happen. The full list of conditions to close an editor upon file delete is (any of the ones below):
* close the file if the setting is configured close files on delete (default unless changed by user)
* close the file if the file is not resolved (e.g. not yet opened)
* close the file if the file deletion was triggered by the user (e.g. the user deleted from the file explorer)

It will never close a dirty file of course, no matter the conditions.
