### ISSUE TITLE
Copilot suggestions shouldn't show up in unfocused notebook cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#133353] opened 2021-09-17 23:40 UTC
- Type some python code
- Quickly press esc to move focus out of the editor
- An inline suggestion shows up in the editor
- If I am working across multiple cells, I often leave these suggestions behind. They should be disabled in unfocused cells

![image](https://user-images.githubusercontent.com/323878/133863899-e280384a-6d8b-44f4-8ee0-421cbb9f674c.png)

Is there any way to accomplish this @hediet

**Comment by hediet** [comment] 2021-09-18 14:51
Does it generally make sense to hide ghost text if the editor does not have focus anymore?
Or should this just be done for notebook cells?

**Comment by roblourens** [comment] 2021-09-20 20:22
Not sure - does copilot still have a mode where they open extra suggestions in a side editor? I thought that switching normal editors while using copilot might be a real use case.

**Comment by rebornix** [comment] 2021-09-20 21:15
+1 for hiding ghost text for blurred text editor.

**Comment by hediet** [comment] 2021-09-21 10:22
> +1 for hiding ghost text for blurred text editor.

Implemented.

**Comment by hediet** [comment] 2021-09-21 10:49
Unfortunately, the hover used to cycle through inline suggestions also takes the focus from the editor.

Thus, we cannot hide the ghost text when the editor loses focus.

I don't know how to not hide the ghost text when the hover gets focus. Even worse, when the hover gets the focus and then loses it to something else (e.g. the sidebar), the ghost text should also hide, but this is even harder to detect.

**Comment by hediet** [comment] 2021-09-22 15:44
There is, but it does not work:

![recording](https://user-images.githubusercontent.com/2931520/134376312-590cc138-d9e0-4707-a38b-6fc98978d93c.gif)

https://github.com/microsoft/vscode/pull/133518 seems to fixes this, but I have no idea why.
This seems to be a different incarnation of https://github.com/microsoft/vscode/issues/133517.

It is also a time grave. I've already spent quite some time figuring out what is going on.
@alexdima had the insight that the other issue is caused by electron interpreting the two clicks as single double-click, but I have no idea why this causes focus problems.

**Comment by hediet** [comment] 2021-09-22 15:49
I moved this to october, as the PR that fixes the fix for this will also be merged not before next milestone (due to vacation).

**Closed** 2021-10-06 14:18 UTC
Labels: bug, notebook, notebook-editor
