### ISSUE TITLE
File recently case-renamed twice opened in same instance after saves

### ISSUE THREAD

**Issue by maoueh** [Microsoft/vscode#51772] opened 2018-06-13 14:36 UTC
- VSCode Version: 1.24.0
- OS Version: OS X 10.13.3

Steps to Reproduce:

1. Start a TypeScript project.
2. Create a file named `Block.ts`
3. Do some edits.
4. Save the file and quit editor.
5. Renamed the file to `block.ts`
6. Open back file and make a change, then Save.
7. `block.ts` is saved but a new tab appears with  name `Block.ts` with the bullet saying it's dirty.

Really similar to #24003 and #24038

Does this issue occur when all extensions are disabled?: ?

```
$ code --disable-extensions
open: unrecognized option `--disable-extensions'
```

Tried with `--fresh`, did nothing, still occurring.

**Comment by maoueh** [comment] 2018-06-13 14:45
I've made a small video, not sure how to upload it here.

**Comment by RMacfarlane** [comment] 2018-06-13 22:20
Thanks for reporting this! This looks like a duplicate of https://github.com/Microsoft/vscode/issues/40682 (see the comment section there, the title only mentions refactoring), so I'll close this one.

**Closed by RMacfarlane** 2018-06-13 22:20 UTC
Labels: typescript
