### ISSUE TITLE
after find or replace there comes some white sapce

### ISSUE THREAD

**Issue by lsw2013** [Microsoft/vscode#29418] opened 2017-06-26 03:07 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.2.0|;

---

Steps to Reproduce:

1. ctrl + H
2. scroll down by mouse wheel
3. you will find some white spaces on the top of current file

![default](https://user-images.githubusercontent.com/4578680/27523428-abba5b0a-5a5f-11e7-9edc-00ab4ac571c3.jpg)

**Comment by rebornix** [comment] 2018-09-21 19:11
Duplicate of https://github.com/Microsoft/vscode/issues/28390

**Closed** 2018-09-21 19:11 UTC
Labels: *duplicate, bug
