### ISSUE TITLE
Show underlying type documentation in interfaces and types that implement that type.

### ISSUE THREAD

**Issue by mesqueeb** [microsoft/vscode#94854] opened 2020-04-10 02:02 UTC
I often have function signatures saved as a separate type when I use them in a lot of places.

The problem is, whenever I use such a type in an interface or a compound type, it doesn't automatically show me the documentation for the underlying type when hovering over the property...

This makes it veeeery un-user-friendly for devs who consume my libraries. So to mitigate that I have to **manually duplicate the documentation block of the type inside every interface and compound type that uses it!**
```ts
/**
 * Documentation for function that is used in multiple places
 */
export type MyFunction = () => void

export interface SomeInferface {
  /**
   * I HAVE to duplicate the documentation manually here, if not, it won't show up on hovering over the `myFunction` prop in `SomeInterface`...
   */
  myFunction: MyFunction
}

export type SomeType = {
  /**
   * I HAVE to duplicate the documentation manually here, if not, it won't show up when hovering over the `myFunction` prop in `SomeType`...
   */
  myFunction: MyFunction
}
```

But this in turn is very error-prone if I change it and forget to update it somewhere...

VSCode should automatically show the documentation of the underlying type, if no other documentation was provided inside the interface or the compound type.

**Comment by mjbvz** [comment] 2020-04-10 02:07
Duplicate of https://github.com/microsoft/TypeScript/issues/37876

**Closed by mjbvz** 2020-04-10 02:07 UTC
