### ISSUE TITLE
Localization test failed in smoketest

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#122629] opened 2021-04-29 07:42 UTC
Please see https://dev.azure.com/monacotools/Monaco/_build/results?buildId=116212&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=2912d057-d0f3-5270-1d09-777eeaba2eea&s=0b07720d-539f-5e8e-7a21-42d3d721992e

(Attempt 1 on macOS)

```
  22 passing (2m)
  3 pending
  1 failing

  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:173:19)
      at async Code.waitForTextContent (/Users/runner/work/1/s/test/automation/out/code.js:234:16)
      at async Search.waitForTitle (/Users/runner/work/1/s/test/automation/out/viewlet.js:12:9)
      at async Context.<anonymous> (out/areas/workbench/localization.test.js:26:13)

```

**Comment by dbaeumer** [comment] 2021-04-29 09:28
Might be caused by some re-layouting of the workbench. Let me investigate.

**Comment by alexdima** [comment] 2021-04-29 09:30
@dbaeumer Some flakiness has been reported about the smoke tests around the welcome page, not sure if that one can impact multiple tests or just the data migration one -- see https://github.com/microsoft/vscode/issues/122317#issuecomment-827609291

**Comment by dbaeumer** [comment] 2021-04-29 09:49
I ran the test locally under Linux and the Localization test passed for me. Looking at the Insider build the Localization smoke test passed in later attempts (see https://dev.azure.com/monacotools/Monaco/_build/results?buildId=116212&view=logs&j=36c106ee-c497-5c4b-1441-e4117ec0825b&t=c76fe90b-63fd-5d48-a2d7-a0c27f2c2ae9)

So I don't thing that this is a general issue with the Localization smoke test.

**Comment by alexdima** [comment] 2021-04-29 12:53
cc @joaomoreno What should we do in case of smoke test flakiness ?

**Comment by joaomoreno** [comment] 2021-04-29 13:30
Disable the test and enable it once the flakiness is fixed.

Also consider removing these tests from the smoke test suite and into integration tests.

**Comment by dbaeumer** [comment] 2021-04-30 08:20
I will close the issue. The test passed in tonights insiders and they passed locally for me as well.

**Closed by dbaeumer** 2021-04-30 08:20 UTC
Labels: smoke-test-failure
