### ISSUE TITLE
Intergrated Terminal LetterSpace Of Chinese Words

### ISSUE THREAD

**Issue by zjruan** [Microsoft/vscode#7281] opened 2016-06-07 02:37 UTC
- VSCode Version:1.2
- OS Version: Windows10 Chinese Language

Steps to Reproduce:

1.  `` Ctrl + ` `` to open Intergrated Terminal
2.  ` ipconfig ` show ipaddress  
![TestImg](http://zjruan.com/sources/TestImg.png)

**Comment by Tyriar** [comment] 2016-06-07 07:33
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-07 07:33 UTC
