### ISSUE TITLE
preLaunchTask does not fire on restart for "node" adapter

### ISSUE THREAD

**Issue by osolo** [microsoft/vscode#104246] opened 2020-08-07 13:48 UTC
- VSCode Version: 1.47.3
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Create an project that uses the node adapter.  In my case I'm targeting Electron with Typescript.
2. Add a `preLaunchTask`
3. Run the application 
4. Edit one of the `.ts` files, introduce a syntax error
5. Hit the Restart button on the toolbar or `Ctrl+Shift+F5`

Expected: Should complain about the syntax error.
Actual: Does not - reruns the app without executing the `preLaunchTask`.

I'm attaching a small sample project that demonstrates this problem: [ts-test.zip](https://github.com/microsoft/vscode/files/5041745/ts-test.zip)

See also: #28979 which is an old, similar bug report.  I don't know if this is a regression.

Does this issue occur when all extensions are disabled?: Yes.  This happens on a fresh install.

**Comment by isidorn** [comment] 2020-08-10 09:00
Works for me with latest VS Code insiders

![Screenshot 2020-08-10 at 10 59 35](https://user-images.githubusercontent.com/1926584/89766537-9a147d00-daf8-11ea-806f-fd44930b9dfd.png)

@osolo can you repro using latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by OzSolomon-MSFT** [comment] 2020-08-10 13:41
@isidorn yes, I can repro this with the insiders build.  What can I do to provide more information?

**Comment by isidorn** [comment] 2020-08-10 13:44
It would be great to have a minimal possible repository which reproduces this. So we can just clone it from GitHub and see it repro on our machines.

**Comment by OzSolomon-MSFT** [comment] 2020-08-10 13:46
@isidorn did you use the zipped sample project I attached to the but report?  It's very basic.  All you need to do is unzip it and run `npm install`.

**Comment by isidorn** [comment] 2020-08-10 13:54
I tried with that sample and I can not reproduce the issue. Let me know what you are doing differently:

![recording (2)](https://user-images.githubusercontent.com/1926584/89790023-a4973c80-db21-11ea-96b1-2deadcd1ccbf.gif)

**Comment by OzSolomon-MSFT** [comment] 2020-08-10 14:07
@isidorn I'm doing the exact same as you:

![2020-08-10_10-06-44](https://user-images.githubusercontent.com/67602429/89791425-4f433700-daf1-11ea-8eaa-6c3993ac07e3.gif)

**Comment by isidorn** [comment] 2020-08-10 14:12
Do you have the following setting set?
```
"debug.onTaskErrors": "debugAnyway" 
```

**Comment by OzSolomon-MSFT** [comment] 2020-08-10 14:30
This is a fresh install.  My user settings file is empty.  

The default settings file has `"debug.onTaskErrors": "prompt"`, so I'm assuming that's in effect.

**Comment by isidorn** [comment] 2020-08-10 14:33
Then I suggest you F1 > developer tools > sources > put a breakpoint around [here](https://github.com/microsoft/vscode/blob/b6d267bb672f341ec7006b2194abbdd81ae8fda4/src/vs/workbench/contrib/debug/browser/debugService.ts#L616) and try to investigate 
Idealy the `runTasks` should get called.

Also you can try to reproduce with a very plain typescript sample, for exaple vscode starter extension.

**Comment by OzSolomon-MSFT** [comment] 2020-08-10 15:12
It looks like inside `restartSession` the debugging session configuration is missing the `preLaunchTask`:

![image](https://user-images.githubusercontent.com/67602429/89797831-6a19a980-daf9-11ea-9c98-ff19f4b392e8.png)

![image](https://user-images.githubusercontent.com/67602429/89797842-6e45c700-daf9-11ea-8190-05ad41bff2c4.png)

The session seems different than the one that is created in `doCreateSession`:

![image](https://user-images.githubusercontent.com/67602429/89798486-3c813000-dafa-11ea-94de-e93f871f58be.png)

Does this help?

**Comment by isidorn** [comment] 2020-08-10 15:13
Yeah, this helps. THanks a lot

@connor4312 can you change that you pass the `preLaunchTask` to child sessions? So when user restarts a child session this case is covered?
I am not sure why I can not repro this on the macOS.

**Comment by connor4312** [comment] 2020-08-10 15:16
Indeed, this is the same as https://github.com/microsoft/vscode/issues/102296. 

Thanks for reporting the issue, it should be fixed in 1.48.0 later this week (and is already fixed on VS Code Insiders)

/duplicate

**Comment by isidorn** [comment] 2020-08-10 15:20
@connor4312 hmm but the user says that he can reproduce with insiders - that is what got me confuse, since I knew you fixed something in this area that is why I first asked for repro in insiders.

**Comment by connor4312** [comment] 2020-08-10 15:23
Ah, okay, I missed that. @OzSolomon-MSFT can you set `trace: true` in your launch.json and share the resulting log (its location will be written in your debug console). That will help us see what's happening.

**Comment by OzSolomon-MSFT** [comment] 2020-08-10 15:34
@connor4312  please find attached.
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5051785/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment] 2020-08-10 15:46
Ah, got it, thanks 🙂 We weren't passing the tasks down to deeply nested children.

**Closed** 2020-08-10 15:47 UTC
Labels: bug, debug

**Comment by isidorn** [comment] 2020-08-10 15:49
Great, thanks for fixing. 
@OzSolomon-MSFT  thanks for provoding all teh details.
