### ISSUE TITLE
Snap package crashes while discarding changes

### ISSUE THREAD

**Issue by jardon** [microsoft/vscode#103965] opened 2020-08-04 16:58 UTC
I have run into an issue where VSCode editors will have changes in them and crash when trying to discard the changes.  I initially tried uninstalling and clearing the snap cache, but the open editors persisted.  I then ran the application with the verbose flag received the following output when trying to discard changes:
```
(code:93979): GdkPixbuf-WARNING **: 12:00:54.352: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(code:93979): Gtk-WARNING **: 12:00:54.352: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(code:93979): GdkPixbuf-WARNING **: 12:00:54.352: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:/build/gtk+3.0-24RAPQ/gtk+3.0-3.22.24/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
```

So I tried the recommended suggestion, but the folders only existed to `/usr/lib/` so the command failed.  I then created folders up to `/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/` and was able to run the above command.  This fixed the issue for me and I was able to discard the changes in the editors.  

Now I'm not all that familiar with GTK libraries, but aren't snap packages supposed to come with all of the dependencies OOTB?  I don't see why it would need a file on my host machine.  This only started happening 3-4 weeks ago.  

- VSCode Version: 1.47.3 (snap)
- OS Version: Manjaro 20.0.3

Steps to Reproduce:
I am a little unsure of how to reproduce it honestly.  I think it happens when the files that are open and have changes in the buffer are no longer mounted.  This happens when an sshfs session detaches because of hibernation or something else.

Does this issue occur when all extensions are disabled?: Yes

Lmk if you need any more info.  Thanks

**Comment by IllusionMH** [comment] 2020-08-04 17:29
/duplicate of #100940

Also check comment https://github.com/microsoft/vscode/issues/100940#issuecomment-651225395 if workaround described here helps.

**Closed** 2020-08-04 17:30 UTC
Labels: *duplicate
