### ISSUE TITLE
LaTeX syntax highlighting in Markdown files is wrong

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [microsoft/vscode#150350] opened 2022-05-25 08:21 UTC
This problem still occurs even if you disable all extensions and occurs in both stable and insider.

LaTeX syntax highlighting in Markdown files is wrong. It should be equivalent to syntax highlighting in LaTeX files.

There are two situations where LaTeX syntax is used within Markdown.

- Fenced code blocks
- Math block

## Demonstration

`workbench.colorTheme` is `Default Dark+`.

### Fenced code blocks

```latex
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{equation}
    R(x)
        =
        \begin{pmatrix}
            \cos x & -\sin x \\
            \sin x & \cos x
        \end{pmatrix}
\end{equation}
\end{document}
```

|       in LaTeX file       |               in Markdown file               |
| :-----------------------: | :------------------------------------------: |
| ![in LaTeX file][in-file] | ![in Fenced code block][in-fenced-codeBlock] |

[in-file]: https://user-images.githubusercontent.com/75878492/170209248-8d5c4419-cae3-473a-888c-033d1efeb0ae.png

[in-fenced-codeBlock]: https://user-images.githubusercontent.com/75878492/170209257-71006600-5708-41eb-8595-fce9b4c42813.png

The following points are not correct.

- `pmatrix` environment
- Commented out line within `equation` environment

### Math block

```latex
$$
    R(x)
        =
        \begin{pmatrix}
            \cos x & -\sin x \\
            \sin x & \cos x
        \end{pmatrix}
$$
```

|          in LaTeX file          |             in Markdown file              |
| :-----------------------------: | :---------------------------------------: |
| ![in LaTeX file][math-in-latex] | ![in Fenced code block][math-in-markdown] |

[math-in-latex]: https://user-images.githubusercontent.com/75878492/170212934-d92ed0ce-8968-4364-92b4-fcfdd8c2fa21.png

[math-in-markdown]: https://user-images.githubusercontent.com/75878492/170212933-588af121-345b-4e66-90a8-a60fddb6f048.png

## Version

```
 Version: 1.67.2 (user setup)
  Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
    Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
 Node.js: 16.13.0
      V8: 9.8.177.13-electron.0
      OS: Windows_NT x64 10.0.19043
```

```
 Version: 1.68.0-insider (user setup)
  Commit: c0769274fa136b45799edeccc0d0a2f645b75caf
    Date: 2022-05-23T05:17:12.256Z
Electron: 17.4.4
Chromium: 98.0.4758.141
 Node.js: 16.13.0
      V8: 9.8.177.13-electron.0
      OS: Windows_NT x64 10.0.19043
```

**Comment by mjbvz** [comment] 2022-08-04 00:01
Closing as same root root cause as https://github.com/microsoft/vscode/issues/118300#issuecomment-804471697

**Closed by mjbvz** 2022-08-04 00:01 UTC

**Comment by Yarakashi-Kikohshi** [comment] 2022-08-04 10:21
I assumed the problem was caused by LaTeX in Markdown. Thank you for investigating the duplication issue.

When I look for posted issue comments and their associated issues, all of them are closed, and the issues that remain open do not seem to exist at the moment.

As this problem has not been resolved, one of the issues should remain open. Is this issue being tracked publicly?
