### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by mubashirngi** [microsoft/vscode#106622] opened 2020-09-14 05:30 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

**TS Server Log**
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13450:55)
    at getTextOfNode (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13475:16)
    at Object.declarationNameToString (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13787:66)
    at getDisplayName (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39842:53)
    at declareSymbol (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39956:111)
    at bindExportsPropertyAssignment (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:42066:17)
    at bindWorker (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41762:29)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41651:13)
    at bindExpressionStatement (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40716:13)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40201:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40247:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27565:21)
    at bindEachChild (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bindContainer (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at visitNode (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27644:24)
    at bindEachChild (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at Object.forEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at visitNodes (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27440:24)
    at Object.forEachChild (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27618:24)
    at bindEachChild (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at Object.forEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindCallExpressionFlow (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41077:21)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40229:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at bindReturnOrThrow (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40551:13)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40182:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40247:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27565:21)
    at bindEachChild (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bindContainer (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at Object.forEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindCallExpressionFlow (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41077:21)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40229:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at bindExpressionStatement (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40716:13)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40201:21)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40241:21)
    at bindContainer (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at bindSourceFile (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39708:17)
    at Object.bindSourceFile (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39647:9)
    at initializeTypeChecker (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:77643:20)
    at Object.createTypeChecker (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:43696:9)
    at Object.getTypeChecker (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:104892:79)
    at synchronizeHostData (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:145287:21)
    at Proxy.getProgram (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:145369:13)
    at InferredProject.Project.updateGraphWorker (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:150226:53)
    at InferredProject.Project.updateGraph (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:150159:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:152241:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:153761:26)
    at /Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:154018:97
    at Object.flatMap (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:154018:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:155037:46)
    at /Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:156910:88
    at IOSession.Session.executeWithRequestId (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:156901:28)
    at IOSession.Session.executeCommand (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:156910:33)
    at IOSession.Session.onMessage (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:156934:35)
    at Interface.<anonymous> (/Users/mubashir/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:159150:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|16.00GB (2.62GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.14.1
flutter|Dar|3.14.1
prettier-vscode|esb|5.6.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.5.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
vscode-typescript-next|ms-|4.1.20200913
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-react-native|msj|0.17.0
vetur|oct|0.27.3
trailing-spaces|sha|0.3.1
vscode-snippets|the|0.1.3
gitblame|wad|5.0.0


</details>
<!-- generated by issue reporter -->

**Comment by mjbvz** [comment] 2020-09-14 18:18
Duplicate of https://github.com/microsoft/TypeScript/issues/40513

**Closed by mjbvz** 2020-09-14 18:18 UTC
Labels: new release
