### ISSUE TITLE
jsonFormatter:applyEdit() could format values nicely

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12323] opened 2016-09-20 13:58 UTC
See comment from @isidorn in https://github.com/Microsoft/vscode/issues/1396#issuecomment-248294777 where we see that filling in a complex object to a settings file does not format it but puts it on a single line.

I have seen this before already when storing a more complex object to settings (e.g. file associations).

**Comment by aeschli** [comment] 2016-12-12 15:57
duplicate of #13436

**Closed by aeschli** 2016-12-12 15:57 UTC
Labels: feature-request

**Comment by bpasero** [comment] 2016-12-12 15:59
@aeschli thanks for fixing this !
