### ISSUE TITLE
Tasks break because of wrong quoting

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#142505] opened 2022-02-08 10:52 UTC
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.64.0 (user setup)
- OS: Windows_NT x64 10.0.19043

My task setup has worked until 1.63, so something must have changed.

Steps to Reproduce:

1. Set up a custom Task with  `"type": "shell"` and a command to an abslute path: `"command": "C:\\Program Files\\Some\\Random Path\\whatever.exe"`, and some args.
2. Try to execute.
3. It will fail because the path to the "command" will be wrapped in single quotes `'` instead of standard double quotes `"`, which CMD does not like. The Task will thus fail.

BTW: It will also wrap the args into the wrong quotes, which will fail the task as well.

**Comment by gjsjohnmurray** [comment] 2022-02-08 12:10
/duplicate of #142196 and will be fixed in upcoming recovery release.

**Closed** 2022-02-08 12:11 UTC
Labels: *duplicate
