### ISSUE TITLE
my IDE stopped working after update 

### ISSUE THREAD

**Issue by harrylog** [Microsoft/vscode#15161] opened 2016-11-08 11:16 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment] 2016-11-08 11:25
Community need more information to try to help you. Please, provide more detailed description and steps to reproduce your problem.

**Comment by harrylog** [comment] 2016-11-08 11:45
i now have version 1.7.1
and nothing works.  not the CTRL+left click
no error detection
no auto complete.

2016-11-08 13:26 GMT+02:00 Denis Malinochkin <notifications@github.com>:

**Comment by aeschli** [comment] 2016-11-08 13:49
@harrylog For what language is that? Can you add a code sample that demonstrates the issue?

**Comment by aeschli** [comment] 2016-11-14 09:55
Closing due to lack of information. @harrylog Please reopen with more information if you still see this.

**Closed by aeschli** 2016-11-14 09:55 UTC
Labels: needs more info
