### ISSUE TITLE
Wrong vscode.d.ts? 

### ISSUE THREAD

**Issue by tempit** [Microsoft/vscode#39036] opened 2017-11-23 13:40 UTC
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
After cleaning all my modules, yarn.lock, etc., when trying to build my extension I get many errors from vscode-languageclient not finding things in vscode:

node_modules/vscode-languageclient/lib/client.d.ts(1,139): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'ProviderResult'.
node_modules/vscode-languageclient/lib/client.d.ts(1,272): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'CompletionList'.
node_modules/vscode-languageclient/lib/client.d.ts(1,648): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/client.d.ts(1,679): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'TextDocumentWillSaveEvent'.
node_modules/vscode-languageclient/lib/client.d.ts(1,706): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'WorkspaceFolder'.
node_modules/vscode-languageclient/lib/codeConverter.d.ts(11,46): error TS2694: Namespace 'vscode' has no exported member 'TextDocumentWillSaveEvent'.
node_modules/vscode-languageclient/lib/codeConverter.d.ts(36,31): error TS2694: Namespace 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(18,57): error TS2694: Namespace 'vscode' has no exported member 'CompletionList'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(21,122): error TS2694: Namespace 'vscode' has no exported member 'CompletionList'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(66,49): error TS2694: Namespace 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(67,53): error TS2694: Namespace 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(69,72): error TS2694: Namespace 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/workspaceFolders.proposed.d.ts(1,10): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'WorkspaceFoldersChangeEvent'.

When I follow the link to the d.ts it installs (below) I get a .d.ts that indeed doesn't have all these items. 
[I'm also missing languages.registerColorProvider, see #38959]

$ node ./node_modules/vscode/bin/install 
Detected VS Code engine version: ^0.10.0
Found minimal version that qualifies engine range: 0.10.2
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

Can it be that the vscode.d.ts is wrong, or am I missing something?
(My repo: https://github.com/wix/stylable-intelligence/)

Reproduces without extensions: Yes/No

**Comment by CoenraadS** [comment] 2017-11-23 19:48
Add this to your package .json:

```
"engines": {
        "vscode": "^1.18.0"
},
```

Then run `npm postinstall`

**Comment by aeschli** [comment] 2017-11-24 08:29
duplicate of #38959

**Closed by aeschli** 2017-11-24 08:29 UTC
Labels: typescript
