### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by Fatherfish** [Microsoft/vscode#68036] opened 2019-02-07 04:14 UTC
Issue Type: <b>Bug</b>

when rename file ,cant click on file name is still move file

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
es7-react-js-snippets|dsz|2.0.0
Angular2|joh|7.0.1
Angular-BeastCode|Mik|7.2.2
mssql|ms-|1.4.0
vscode-react-native|vsm|0.8.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by NiciusB** [comment] 2019-02-07 05:11
I'm not sure I understood the bug description, but I also have an issue when renaming files.


After entering the "renaming" state, I would usually double click to select a whole word. But with the new update, I cannot double click because it will exit the "renaming" state. Single clicks work as expected.

**Comment by KamasamaK** [comment] 2019-02-07 09:47
Looks like the same issue as #68028

**Comment by joaomoreno** [comment] 2019-02-07 09:49
Yup, dupe of #68028, thanks!

**Closed by joaomoreno** 2019-02-07 09:49 UTC
Labels: new release
