### ISSUE TITLE
Problem view focus border partially hidden

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69389] opened 2019-02-25 18:06 UTC
#69204

Version: 1.32.0-insider (user setup)
Commit: [393b48d](https://github.com/Microsoft/vscode/commit/393b48d4a5de85b6fa1d2ad0a59588d6715e12ea)
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

![image](https://user-images.githubusercontent.com/2193314/53358340-df34f700-38e4-11e9-8cf6-63d81c9eb32d.png)

HC:

![image](https://user-images.githubusercontent.com/2193314/53358353-e9ef8c00-38e4-11e9-8d77-d473b6df64d8.png)

**Comment by sandy081** [comment] 2019-02-25 22:34
Duplicate of #69382

**Closed by sandy081** 2019-02-25 22:34 UTC
Labels: bug, editor-error-widget

**Comment by Tyriar** [comment] 2019-02-26 01:14
Removing duplicate as this is its own bug and want to make sure it gets verified as well.
