### ISSUE TITLE
Snippets Not Handling Mirrored Tabstops Correctly  

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25058] opened 2017-04-20 04:53 UTC
From: http://stackoverflow.com/questions/43507897/is-it-possible-to-default-a-placeholder-or-tabstop-with-the-value-of-a-previous?stw=2

Steps to Reproduce:

1. Create a user snippet such as `import * as ${2:$1} from '${1:module}';`
2. Trigger the snippet and tab through the items of the snippet

**Expected Behavior**
TextMate:

![textmate](https://cloud.githubusercontent.com/assets/12821956/25214091/31670e6a-254a-11e7-8482-eb7bf0b2cf64.gif)

**Actual Behavior**
VScode goes to `$2` first and then seems to skip `$1`:

![apr-19-2017 21-52-17](https://cloud.githubusercontent.com/assets/12821956/25214144/88d3c648-254a-11e7-978c-06d7b33ab64e.gif)

**Comment by jrieken** [comment] 2017-04-21 10:47
dupe of https://github.com/Microsoft/vscode/issues/23728

**Closed by jrieken** 2017-04-21 10:47 UTC
Labels: bug, snippets
