### ISSUE TITLE
Emmet Tab Key Not Expanding In Certain Scenario

### ISSUE THREAD

**Issue by codeTrainingMine** [Microsoft/vscode#19947] opened 2017-02-04 23:06 UTC
After doing a particular sequence of actions, the Tab key for Emmet is not expanding the html shortcut. It instead jumps to the title element.

If I then close the file and re-open it, the Tab key does work.

after creating a new file, using the "!" shortcut to create an html skeleton, and then trying to expand an html shortcut.

- VSCode Version: Version 1.9.0
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

1. Create a new file
2. Type ! followed by Tab for the html skeleton shortcut
3. Type an html shortcut in the body, for example div#one{RELATIVE}
4. Press Tab
5. The cursor goes to the Title element instead of expanding the shortcut

**Comment by ramya-rao-a** [comment] 2017-02-05 19:06
Duplicate of #5427

@codeTrainingMine `!` expands to snippet with placeholder for the `title` element. When you are in a snippet mode, tab always cycles among the placeholders. That is why when you TAB, you end up in the `title` element.

#5427 is tracking to make this a better user experience.

Until then, press ESC to escape the snippet mode. 

One way to know that you are in snippet mode, is that the whole snippet would have a highlight of sorts. The placeholder will also be highlighted.

Snippet mode:
<img width="466" alt="screen shot 2017-02-05 at 11 04 33 am" src="https://cloud.githubusercontent.com/assets/16890566/22628997/00452376-eb93-11e6-8b35-ad6bd2d2774f.png">

After ESC from snippet mode:
<img width="538" alt="screen shot 2017-02-05 at 11 04 46 am" src="https://cloud.githubusercontent.com/assets/16890566/22629002/09eb2f92-eb93-11e6-8c5a-9f6465ad1c4b.png">

**Closed by ramya-rao-a** 2017-02-05 19:06 UTC
