### ISSUE TITLE
SCM view focus command titles are very long

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#229768] opened 2024-09-25 21:47 UTC
Example command ID: workbench.scm.history.focus
Example command title: workbench.views.service.sidebar.49db1b94-f905-4b4e-9fb4-4df2c1703b09: Focus on Source Control Graph View

![Command Palette showing long commands for SCM view](https://github.com/user-attachments/assets/95ee5789-b574-4c83-9514-c353c39d78fa)

**Comment by gjsjohnmurray** [comment] 2024-09-26 00:54
I think this is #201085

**Comment by lszomoru** [comment] 2024-09-26 07:34
Closing as duplicate of https://github.com/microsoft/vscode/issues/201085

**Closed by lszomoru** 2024-09-26 07:34 UTC
