### ISSUE TITLE
Size of the image is not shown in the status bar

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#81739] opened 2019-10-01 11:08 UTC
Testing #81674 
Linux

Size is not shown. It is shown in stable

![image](https://user-images.githubusercontent.com/10746682/65957158-70a4b280-e44c-11e9-8e70-72323945bfdf.png)

**Comment by mjbvz** [comment] 2019-10-01 21:11
Likely a duplicate of #81738. Will follow up on that issue

**Closed by mjbvz** 2019-10-01 21:11 UTC
