### ISSUE TITLE
All projects from "Open Recent" list are opened after a new version has been installed

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14153] opened 2016-10-21 11:12 UTC
When updating VS Code to a new version, VS Code will open all projects from the "Open Recent" list on restart.

**Comment by bpasero** [comment] 2016-10-21 13:21
I suspect hot-exit since I did not work in this area otherwise.

**Comment by Tyriar** [comment] 2016-11-01 16:47
I think this was to do with not handling the case where hot exit is disabled correctly.

**Comment by Tyriar** [comment] 2016-11-01 23:38
This may be different to the original issue but closing multiple windows at once now doesn't seem to clean up the workspaces correctly, the root cause is likely multiple renderer processes trying to save the same file https://github.com/Microsoft/vscode/issues/14056

**Comment by Tyriar** [comment] 2016-11-02 00:11
Closing as the code has change quite a bit since then and the rest I believe is a duplicate of #14056. We'll be doing a little internal test at Redmond before I push which should verify this is fixed.

**Closed by Tyriar** 2016-11-02 00:11 UTC
Labels: bug, hot-exit, important
