### ISSUE TITLE
Typescript error : shell.ts:475 Cannot read property 'on' of null

### ISSUE THREAD

**Issue by Moncef12** [Microsoft/vscode#25668] opened 2017-04-29 12:20 UTC
- VSCode Version: 1.11.2
- OS Version: ubuntu 14.04

Just when vs code starts, I get this error on the console log. (Now, all typescript's intellisense is not working).

```
[Extension Host] Looking for parseable documents...
shell.ts:475 Cannot read property 'on' of null: TypeError: Cannot read property 'on' of null
    at electron.fork (/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:428:37)
    at reject (/usr/share/code/resources/app/extensions/typescript/out/utils/electron.js:58:9)
    at ChildProcess.childProcess.once (/usr/share/code/resources/app/extensions/typescript/out/utils/electron.js:107:9)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)e.onUnexpectedError @ shell.ts:475(anonymous function) @ shell.ts:435e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] Uncaught Exception:  TypeError: Cannot read property 'on' of nulld.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] TypeError: Cannot read property 'on' of null
    at electron.fork (/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:428:37)
    at reject (/usr/share/code/resources/app/extensions/typescript/out/utils/electron.js:58:9)
    at ChildProcess.childProcess.once (/usr/share/code/resources/app/extensions/typescript/out/utils/electron.js:107:9)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

 

```

**Comment by mjbvz** [comment] 2017-05-02 23:34
Here's a similar report: https://github.com/Microsoft/vscode/issues/23018 I have not been able to reproduce this problem but it sounds like @MaZZly was able to work around it by removing everything under `/usr/share/code` and reinstalling. Perhaps worth trying at least

**Comment by MaZZly** [comment] 2017-05-03 11:37
Yes apparently `sudo apt-get purge code` didn't remove everything and some ghost files were leftover, causing the problem. 

Try this:
1. Uninstall vscode,
2. Do a `sudo rm -r /usr/share/code` 
3. Reinstall vscode

**Comment by Moncef12** [comment] 2017-05-04 10:54
Great !! thank you guys !  removing the shared folder resolved this issue.

**Comment by mjbvz** [comment] 2017-05-04 16:03
@Tyriar People only seem to be hitting this on Linux. Any thoughts on why some files might not being removed properly? Would a running codehelper process cause them to be kept around?

**Comment by Tyriar** [comment] 2017-05-04 18:24
I never tested purge explicitly, just relying on apt/dpkg to do its thing for this. Do you know why it needed to be purged in the first place?

**Comment by mjbvz** [comment] 2017-05-05 06:23
I'm unable to repo this after running `purge` and reinstalling code a few times. Closing since there's not enough information to investigate further

If anyone else hits this, before trying the workaround, please check the contents of `/usr/share/code` and let us know what the folder contains 

Thanks

**Closed by mjbvz** 2017-05-05 06:23 UTC
Labels: freeze-slow-crash, linux, needs more info, typescript
