### ISSUE TITLE
Focused Markdown cell has selection background, but code cells don't

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119719] opened 2021-03-23 22:17 UTC
Testing #119118

With the new renderer, the markdown cells have a selection background 

![image](https://user-images.githubusercontent.com/641685/112225848-ca320b80-8c03-11eb-86c1-82448b666c73.png)

but code cells don't

![image](https://user-images.githubusercontent.com/641685/112225865-d0c08300-8c03-11eb-8e58-af4773d21bc2.png)

**Comment by rebornix** [comment] 2021-03-24 01:13
I remember @mjbvz had a fix for this.

**Comment by mjbvz** [comment] 2021-03-24 04:05
Duplicate of #119704

**Closed by mjbvz** 2021-03-24 04:05 UTC
Labels: notebook-markdown
