### ISSUE TITLE
Select Default Profile do not actually open gitbash. After relaunch, on startup, it just keeps open PowerShell

### ISSUE THREAD

**Issue by nicewaytodoit** [microsoft/vscode#132538] opened 2021-09-07 11:24 UTC
Issue is the same as the closed https://github.com/microsoft/vscode/issues/123684

Only difference is that I started experiencing it after update to:

 Version: 1.60.0 (system setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by albertosantini** [comment] 2021-09-07 11:31
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Comment by gjsjohnmurray** [comment] 2021-09-07 12:01
/duplicate - thanks @albertosantini (FYI the special /-commands only trigger for team members and [Community Issue Trackers](https://github.com/microsoft/vscode/wiki/Community-Issue-Tracking))

**Closed** 2021-09-07 12:01 UTC
Labels: *duplicate

**Comment by albertosantini** [comment] 2021-09-07 13:59
@gjsjohnmurray I supposed it, but I like to use the same pratice or policy, just not to add more noise.
