### ISSUE TITLE
Beautify 1.5.0 format on save not working with vscode 1.50.1

### ISSUE THREAD

**Issue by ledmirage** [microsoft/vscode#108878] opened 2020-10-18 03:37 UTC
- VSCode Version: 1.50.1
- OS Version: Ubuntu 20.04.1

Steps to Reproduce:

1. Install vscode 1.49.3 with beautify extension
2. verify format on save is working
3. upgrade vscode to 1.50.1 (no changes on extension or settings)
4. format on save now doesn't work
5. downgrade vscode to 1.49.3, Beautify works again for format on save.

However, while using vscode 1.50.1, using command palette to select command "Beautify File" works.

Does this issue occur when all extensions are disabled?: N/A

The issue is extension related, so I can't disable it.

**Comment by gjsjohnmurray** [comment] 2020-10-18 05:48
Have you reported this to the extension author?

**Comment by marcmo** [comment] 2020-10-18 17:31
I had a similar issue with 1.50.1 and `rustfmt`.
turns out vs code was just finding multiple matching formatters and I had to do a `>Format Document` and select one formatter once. After that it worked.

**Comment by jrieken** [comment] 2020-10-19 08:07
/duplicate of https://github.com/microsoft/vscode/issues/108447

**Closed** 2020-10-19 08:08 UTC
Labels: *duplicate, formatting
