### ISSUE TITLE
Add option to disable bracket matching

### ISSUE THREAD

**Issue by thuyettiensinh** [Microsoft/vscode#18745] opened 2017-01-18 17:50 UTC
- VSCode Version: 1.8.1
![untitled](https://cloud.githubusercontent.com/assets/21211244/22076046/0e3c685a-dde1-11e6-9b8b-7bbfb3f93491.png)

HTML tag highlight when i active !
How to disable them ???
plz help me !

**Comment by Gama11** [comment] 2017-01-23 20:36
Duplicate? #16424

**Comment by mjbvz** [comment] 2017-02-04 00:46
Thanks @Gama11! Closing as a duplicate of #16424

**Closed by mjbvz** 2017-02-04 00:46 UTC
Labels: beginner, duplicate, editor-contrib, feature-request

**Comment by thuyettiensinh** [comment] 2017-02-04 03:11
tks all !
