### ISSUE TITLE
Code outline/file structure

### ISSUE THREAD

**Issue by vegarringdal** [Microsoft/vscode#15311] opened 2016-11-10 18:37 UTC
- VSCode Version:1.7.1
- OS Version:Win10

Is there plans for any code outline for visual studio code?
This could be very useful in big classes to get a overview of the file structure.

Maybe there is a expansion for this that I have not found ?

**Comment by aeschli** [comment] 2016-11-11 21:05
You can use `Ctrl + Shift + O` to see all symbols in a file.

**Comment by aeschli** [comment] 2016-11-11 21:06
duplicate of #5605

**Closed by aeschli** 2016-11-11 21:06 UTC
Labels: feature-request

**Comment by vegarringdal** [comment] 2016-11-11 21:11
@aeschli thank you :-)

Sorry for the duplicate, really tried to search, didnt know to search for symbol...
+1 the other one, would like something more powerful, like a panel under explorer, that showed types on variables,parms etc
