### ISSUE TITLE
Error while running html code

### ISSUE THREAD

**Issue by LeoKrool** [Microsoft/vscode#19547] opened 2017-01-28 15:42 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|view-in-browser|qinjia|0.0.5|

---

Error specification -
Running the contributed command:'extension.viewInBrowser' failed.

**Comment by mousetraps** [comment] 2017-01-28 23:27
@LeoKrool - it looks like this issue is being caused by the `view-in-browser` extension rather than VS Code itself, so I'm going to go ahead and close this issue, but I suggest chiming in on this related thread: https://github.com/hellopao/view-in-browser/issues/1

Lmk if you think otherwise, and we'll be happy to reopen. Happy coding!

**Closed by mousetraps** 2017-01-28 23:27 UTC
