### ISSUE TITLE
'r' not recognised as a valid CSS property

### ISSUE THREAD

**Issue by MartijnZwa** [microsoft/vscode#101007] opened 2020-06-25 06:58 UTC
Issue Type: <b>Bug</b>

The 'rx', 'ry' and 'r' CSS Properties are not recognised as valid properties, and hence cause an 'Unknown property' error. These properties are part of a [wider range of SVG geometry properties](https://css-tricks.com/svg-properties-and-css/) that might be added to browsers in SVG 2, which is currently still in the Candidate Recommendation stage. However, the 'rx', 'ry' and 'r' properties have already been implemented by Chrome, Firefox and Safari. They don't (yet) work in IE or Edge, but who uses that anyway.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (0.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cython|tcw|0.1.0

</details>

**Comment by aeschli** [comment] 2020-06-25 09:05
duplicate of https://github.com/microsoft/vscode/issues/85828

**Closed by aeschli** 2020-06-25 09:05 UTC
