### ISSUE TITLE
Emmet Wrap Individual lines with abreviation doesn't work properly

### ISSUE THREAD

**Issue by StaarX** [microsoft/vscode#92803] opened 2020-03-16 19:30 UTC
I have this text:
          Home
          Alice in Wonderland
          All Chapters
          Chapter 7: A Mad Tea-Party
>I use Shift+Ctrl+P 
>Then use command Emmet Wrap Indicidual lines with Abreviation
>Then li>a
I expect:
<li><a>Home</a></li>
<li><a>Alice in Wonderland</a></li>
<li><a>All Chapters</a></li>
<li><a>Chapter 7: A Mad Tea-Party</a></li>
and i got:
<li><a>Home
          Alice in Wonderland
          All Chapters
          Chapter 7: A Mad Tea-Party</a></li>

**Comment by octref** [comment] 2020-03-20 17:55
Duplicate of #78015.

**Closed by octref** 2020-03-20 17:55 UTC
