### ISSUE TITLE
some characters can not shown in console window

### ISSUE THREAD

**Issue by Simon-Wong** [microsoft/vscode#165317] opened 2022-11-03 06:51 UTC
Type: <b>Bug</b>

If I create a console window by shortcut key "~ + shif + ctrl"，it will create a console  window and works well.

Now,some charaters can not show in this console window,such as "q".
But if I create one by touch  the icon "+" in the panel,it works well.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (19.18GB free)|
|Process Argv|--crash-reporter-id ef857ad9-a798-42ed-92c1-64e131d70eda|
|Screen Reader|no|
|VM|80%|

|Item|Value|
|---|---|
|Remote|SSH: pg14和15|
|OS|Linux x64 3.10.0-1160.el7.x86_64|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (2 x 2803)|
|Memory (System)|3.68GB (2.30GB free)|
|VM|100%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.16.3
vscode-language-pack-zh-hans|MS-|1.73.11020948
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
doxdocgen|csc|1.4.0
vscode-office|cwe|2.8.1
better-cpp-syntax|jef|1.16.3
cmake-language-support-vscode|jos|0.0.7
vscode-language-pack-zh-hans|MS-|1.73.11020948
vscode-dotnet-runtime|ms-|1.6.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.9
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
iaj6b796:30602301

```

</details>

**Comment by xuestrange** [comment] 2022-11-03 07:28
This is a R terminal(radian). Some characters can not shown after vscode update. 
PS: the color scheme is [Github Dark Default](https://github.com/primer/github-vscode-theme)
![R terminal](https://raw.githubusercontent.com/xuestrange/picGoUploader/main/img/202211031523069.png)

**Comment by meganrogge** [comment] 2022-11-03 18:42
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by LiveFreeAndRoam** [comment] 2022-11-04 01:00
> does changing terminal.integrated.gpuAcceleration help?

It did for me. It was set to `auto`.  When I set it to `off`, the missing characters instantly reappeared.

Note that when set to `auto`, only occassionally some characters were not displayed.  So it's not 100% reproducible.

Any thoughts on a fix for this? Naturally, the sound of not using GPU acceleration is a little unsettling.

**Comment by xuestrange** [comment] 2022-11-04 01:54
> does changing `terminal.integrated.gpuAcceleration` help?

Setting it to `off` works for me

**Comment by Simon-Wong** [comment] 2022-11-04 05:27
That Set terminal.integrated.gpuAcceleration to off works for me.
But I don't know what happened.

**Comment by meganrogge** [comment] 2022-11-04 14:53
yes - some browser versions don't support gpu acceleration

we're tracking that here

/duplicate #165416

**Closed by meganrogge** 2022-11-04 14:53 UTC
Labels: info-needed, new release
