### ISSUE TITLE
Language File Association doesn't work

### ISSUE THREAD

**Issue by kernhanda** [Microsoft/vscode#62242] opened 2018-10-31 05:01 UTC
- VSCode Version:
Version: 1.29.0-insider
Commit: 4b2fac2b6da220f62ff58b2766e4ecc1f561be94
Date: 2018-10-30T16:48:18.436Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:
Ubuntu 18.04

Steps to Reproduce:

1. Open/create .tcc file
2. ctrl+shift+p
3. change language mode
4. Configure File Association for '.tcc'
5. Select C/C++

Notice that C/C++ syntax highlighting does not go into effect. Even closing the file and reopening doesn't set the language properly. 

This is a regression, I believe.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-10-31 13:59
Duplicate of #62030

**Closed by alexandrudima** 2018-10-31 13:59 UTC
