### ISSUE TITLE
[UI] Toolbar move to titlebar

### ISSUE THREAD

**Issue by leaxoy** [microsoft/vscode#149894] opened 2022-05-19 03:50 UTC
I updated to recently insiders release, and find search bar & jump button move to titlebar. As below:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/8556349/169200209-57052538-2da5-4924-8032-8c33b7c9f77a.png">
The toolbar still in tabbar, and it extrusion the tabbar, meanwhile titlbar has more space to place toolbar, so I suggest move toolbar to titlebar also.

**Comment by sbatten** [comment] 2022-05-19 14:41
I would consider this a duplicate of https://github.com/microsoft/vscode/issues/41309

**Closed by sbatten** 2022-05-19 14:41 UTC
