### ISSUE TITLE
Language selector action and Cell toolbar are overlapping

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96554] opened 2020-04-29 10:54 UTC
#96279

I have notebook with following setup:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/10746682/80588342-754c3c00-8a18-11ea-92ae-27a5d4e2bc4e.png">

- When I try to hover on language selector for first cell, the toolbar of second cell is getting overlapped.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/10746682/80588415-99a81880-8a18-11ea-84c1-61df59117331.png">

**Comment by rebornix** [comment] 2020-04-29 21:56
@roblourens any idea about this one, is it possible that the status bar size is not included in the layout?

Also I'm seeing "GitHub-issues" language picker in a markdown cell 
<img width="1683" alt="image" src="https://user-images.githubusercontent.com/876920/80650788-7d60a780-8a29-11ea-8222-6a17e16b0110.png">

**Comment by roblourens** [comment] 2020-04-29 22:12
Probably somehow related to https://github.com/microsoft/vscode/issues/96642

@rebornix we have https://github.com/microsoft/vscode/issues/96642

**Comment by rebornix** [comment] 2020-04-30 00:23
@sandy081 do you have stable reproduce steps for this issue?

**Comment by roblourens** [comment] 2020-04-30 03:42
I think I saw this once after some dragging/dropping and folding/unfolding and editing but can't repro consistently. 

What does it imply if the prefix sum computer returns a remainder?

![image](https://user-images.githubusercontent.com/323878/80669566-58405900-8a6a-11ea-84e9-6682e5cf0758.png)


![image](https://user-images.githubusercontent.com/323878/80669541-4959a680-8a6a-11ea-969f-56eefbc4750f.png)

**Comment by sandy081** [comment] 2020-04-30 07:41
Yeah I can't repro it but you can see that I got into this state.

It seems like this can happen when the two markdown cells are in edit mode which I am unable to get now.

**Comment by rebornix** [comment] 2020-05-07 00:33
I think this is probably because of a wrong layout (height calculation) of markdown cells, which has some new fixes in master today. Closing it for now and reopen if we see similar issues again.

**Closed by rebornix** 2020-05-07 00:33 UTC
Labels: bug, needs more info, notebook

**Comment by roblourens** [comment] 2020-05-07 01:47
Yeah I haven't seen it again.
