### ISSUE TITLE
[macOS] Shift+F5 results in typing `5;2~` in terminal instead of stop debugging

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#32888] opened 2017-08-21 14:56 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0

Steps to Reproduce:

0. `git clone https://github.com/Deilan/vscode-issue-31469.git`.
1. `yarn install` or `npm install`.
2. Launch debug configuration `Launch via nodemon`.
3. Press <kbd>Shift+F5</kbd>

Pressing <kbd>Shift+F5</kbd> results in typing `5;2~` in terminal instead of stop debugging.

Reproduces without extensions: Yes

**Comment by Deilan** [comment] 2017-08-22 09:50
I suppose shortcuts <kbd>Shift+F1</kbd>, <kbd>Shift+F2</kbd>, ..., <kbd>Shift+F12</kbd> should also be investigated.

**Comment by weinand** [comment] 2017-08-22 10:53
I cannot reproduce this.
As a long as a debug session is active (VS Code shows orange statusbar), <kbd>Shift+F5</kbd> always terminates the session fro me. But when no session is active, the  5;2~ appears in the Terminal.
This appears to be the correct behaviour since the "Stop" action (<kbd>Shift+F5</kbd>) has a "when" clause for "debugSession", so the action is only active if a debug session is active.

**Comment by Tyriar** [comment] 2017-08-22 18:12
This is expected from the terminal side.

Normally `5;2~` is sent to the shell when pressing shift+F5. The settings `terminal.integrated.commandsToSkipShell` contains a list of commands that will bypass the terminal entirely and go to be resolved by VS Code's keybindings system. The following debug commands are in this list:

```
    "workbench.action.debug.pause",
    "workbench.action.debug.restart",
    "workbench.action.debug.run",
    "workbench.action.debug.start",
    "workbench.action.debug.stop"
```

`workbench.action.debug.stop` is assigned to shift+F5. but only when `inDebugMode` is active:

![image](https://user-images.githubusercontent.com/2193314/29580354-9d78d790-872a-11e7-97ff-997b6e1cc506.png)

shift+f5 stops debugging for me just fine, when `inDebugMode` is active. `inDebugMode` does appear to be delayed by 1-2 seconds after debugging however so this could be improved in that perspective. I would expect `inDebugMode` to be true the moment the debug toolbar appears.

**Comment by weinand** [comment] 2017-08-22 20:50
@isidorn could we enter the "inDebugMode" mode earlier?

**Comment by isidorn** [comment] 2017-08-28 14:23
@weinand yes we could enter `inDebugMode` a bit earlier -> as soon as the user starts debugging and not when the adapter returns the `initialzed` request - as we currently do this.
However I do not think this is critical -> will do in debt week

**Comment by Deilan** [comment] 2017-08-31 07:58
Maybe you understand this already, but for the sake of completeness: the issue is being reproduced when debugging has been started or not yet finished, but the debugger hasn't connected yet or just disconnected already.

**Closed** 2017-09-08 14:03 UTC
Labels: bug, debug

**Comment by Deilan** [comment] 2017-10-23 11:05
I also confirm this now works as expected.
