### ISSUE TITLE
Debug: repl shows up everytime when I press F5

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5738] opened 2016-04-25 07:31 UTC
I thought we would be smarter here and only bring up the repl on the first debug launch but not subsequent launches when the user has closed the repl. I thought we would use the viewlet icon decoration to indicate that there is new output.

@isidorn maybe a regression?

**Comment by isidorn** [comment] 2016-04-25 07:34
@bpasero no, not a regression, we never added that smartness. Though I agree it is a bad experience so I will improve it today.
Do you think we should open the repl on the frist debug launch in the workspace. Or first debug launch since vscode started. Hmm? I would go for the second.

**Comment by bpasero** [comment] 2016-04-25 07:49
@isidorn ah so the change you did was to not pop up the repl when output is appended and the user closed it, right?

From your two options I am not sure what the difference is between the two?

Btw since this seems new behaviour I am not sure if it is desired for all users, maybe also check with @weinand. My use case is that I want to try out my extension often but there is absolutely nothing in the repl that I am using for my extension. So I constantly have to close the repl to win back the space for the editor area.

I like the idea of keeping the repl closed once it popped up after a  debug session and the user closing it. The alternative (I am sure you guys discussed this before) would be to close the repl when the debug session is  over?

**Comment by isidorn** [comment] 2016-04-25 14:51
I did a simple approach which I personalyl like, we only show the repl and debug viewlet on first debug start,
Please try it out and let me know how it feels.

Automatic closing we tried but it brings too many pains

**Closed** 2016-04-25 14:50 UTC
Labels: bug

**Comment by bpasero** [comment] 2016-04-25 15:24
Cool
