### ISSUE TITLE
PowerShell task running with lower privileges than user

### ISSUE THREAD

**Issue by szul** [microsoft/vscode#49712] opened 2018-05-11 17:55 UTC
I have a PowerShell one-liner that works perfectly fine in a PowerShell window, as well as the PowerShell terminal in Visual Studio Code, but when I set it up to run as a task in Visual Studio Code, it gives me a permission denied error when it attempts to access the directories/files. You can find the task in [this gist](https://gist.github.com/szul/f2de65d32fec9c0a94a9d55c1c389f2c).

**Comment by dbaeumer** [comment] 2018-05-14 06:57
@Tyriar any idea what could cause this. Is the terminal tweak the execution policy for PowerShell ?

**Comment by Tyriar** [comment] 2018-05-14 13:12
@szul are you using the PowerShell extension?

**Comment by szul** [comment] 2018-05-14 17:27
@Tyriar Yes. If I run the command in the PowerShell terminal there, it works just fine. It's only when I attempt to execute it as a task that I get the permission issue.

**Comment by Tyriar** [comment] 2018-05-14 18:41
If that's the case I'm not sure what's happening. @dbaeumer you must be spawning the terminal differently in some way to cause this?

**Comment by dbaeumer** [comment] 2018-05-15 07:46
Here is how I spawn the terminal in a simple dir example:

<img width="1123" alt="capture" src="https://user-images.githubusercontent.com/1931590/40043364-8cae1c10-5824-11e8-9398-8c47c45c19a9.png">

The `shellLaunchConfig` is the one I pass to `terminalService.createTerminal`. 

So at the end I simply take the shell setting for the integrated terminal and the add `-Command ...` to it. So there is nothing I can think of that makes this special.

@szul does this happen as well when you disable / uninstall the PowerShell extension?

**Comment by szul** [comment] 2018-05-15 14:11
@dbaeumer I get the same results with the extension installed or uninstalled, and with and without the Set-ExecutionPolicy in the shell command. The command is running [Chatdown](https://github.com/Microsoft/botbuilder-tools/tree/master/Chatdown) from the new Bot Framework tools, but it only reads from one file, transforming the data, and then outputs to a second file. If I have just a single chatdown command `chatdown test.chat > test.transform` in the "command" property, it works fine. It's only when I attempt to do a single line PowerShell command that recurses and reads/writes that this happen.

**Comment by dbaeumer** [comment] 2018-05-16 08:35
@szul thanks. Will it work when you put the command into a `ps` file and execute that. 

I see that parts for the command are quoted so might be something goes wrong with the quotes when executed as a single command.

**Comment by szul** [comment] 2018-05-16 11:26
@dbaeumer We have a winner. So it works from a `*.ps1` file executed in the command property in `tasks.json`, but not if the command is explicitly written in the `task.json` file.

On thing to note: When the task ran previously, the escapes occurred appropriately, and the command output to the terminal window showed the correct command.

I'm guessing the problem is maybe with the way that command gets translated and pushed to the shell?

**Comment by dbaeumer** [comment] 2018-05-16 14:10
@szul I think that is the problem. I will investigate further.

**Comment by JhonnyTerminus** [comment] 2018-08-27 15:52
+1 
Running VS-Code as admin does not solve the problem.
When powershell running as Admin it does not start with an admin token.

![image](https://user-images.githubusercontent.com/17069425/44670060-f1aba200-aa21-11e8-941c-6ecd8f168187.png)

![image](https://user-images.githubusercontent.com/17069425/44670015-e2c4ef80-aa21-11e8-907d-df3cd0a2b03a.png)

**Comment by dbaeumer** [comment] 2018-08-28 08:55
@JhonnyTerminus can you please open a new issue since your case is different to the one discussed so far in this issue.

**Comment by szul** [comment] 2019-01-04 16:30
@alexr00 I will dig this back up, and see if the error persists.

**Comment by uday31in** [comment] 2019-01-04 19:43
Having an issue with 1.30.1 version - issue started since last update.

PS C:\temp> Get-ExecutionPolicy
RemoteSigned

PS C:\temp> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process    RemoteSigned
  CurrentUser       Undefined
 **LocalMachine    Unrestricted**

**Comment by alexr00** [comment] 2019-01-07 09:40
In your user settings, what are `terminal.integrated.shellArgs.windows` and `terminal.integrated.shell.windows`?

Do you have the PowerShell extension enabled in VS Code? Does this reproduce if you disable the extension?

**Comment by szul** [comment] 2019-01-14 12:54
@alexr00 Finally had the opportunity to dig this back up. [Same issue](https://onedrive.live.com/?cid=0A1B1D3D918BDBC5&id=A1B1D3D918BDBC5%21842102&parId=A1B1D3D918BDBC5%21231&o=OneUp). If I take the same exact PowerShell code and put it in an external PowerShell file, and then run the file from the task, it works fine.

**Comment by alexr00** [comment] 2019-01-15 16:43
Thank you for trying it again. In your settings, what is `terminal.integrated.shellArgs.windows`?

**Comment by szul** [comment] 2019-01-15 16:53
@alexr00 An empty array. The `terminal.integrated.shell.windows` meanwhile is `"C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"`.

**Comment by szul** [comment] 2019-01-15 20:09
@alexr00 How do you want me to add this? The following throws a cmdlet not found error:

```
 "tasks": [
        {
            "label": "chatdown",
            "type": "shell",
            "command": "Get-ChildItem **/*.chat | ForEach-Object { chatdown \"$(Split-Path $_.FullName)/$($_.Name )\" >  \"$(Split-Path $_.FullName)/$($_.BaseName).transcript\" }",
            "args": ["-Command"],
            "problemMatcher": []
        }
    ]
```

**Comment by alexr00** [comment] 2019-04-29 09:41
I took your command and stepped through the code to see what it gets translated too:
`
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command Get-ChildItem **/*.chat | ForEach-Object { chatdown "$(Split-Path $_.FullName)/$($_.Name )" >  "$(Split-Path $_.FullName)/$($_.BaseName).transcript" }`

It looks like the escaped quotes are becoming just quotes. Are you expecting that the escapted quotes stay escaped? If you run that in the integrated terminal does it work?

**Comment by szul** [comment] 2019-05-20 15:23
@alexr00 No, the escaped quotes were just to escape them in the task file. When I move the PowerShell to an external file and then reference the external file in the task file, it is not escaped, and the command works as expected.

Here's the external file:
https://github.com/szul/chatbot-edui2018/blob/master/cd.ps1

...and here's the task file:
https://github.com/szul/chatbot-edui2018/blob/master/.vscode/tasks.json

**Comment by alexr00** [comment] 2019-05-21 09:42
The issue is that there is some additional escaping that needs to be done. Since we run your task as `powershell.exe -Command <your task here>` the regular escaping that you do for running the command from PowerShell isn't correct. When passing the cmdlet in with the `-Command` parameter (this is unavoidable, we must use the `-Command` parameter), different escaping is needed in your tasks.json file.

**Comment by alexr00** [comment] 2019-05-21 10:06
Based on the documentation here, I think I figured it out how your task should be escaped in tasks.json.
Mini example:
I have a folder `Folder With Space` in my workspace. From powershell, I would run:
`Get-ChildItem "Folder With Space"`
To get the same results when running with `powershell.exe -Command` I have to run:
`powershell.exe -Command "& {Get-ChildItem \"Folder With Space\"}"`
Therefore, in my tasks.json, this is how that task must be escaped:
```
{
	"type": "shell",
	"command": "& {Get-ChildItem \\\"Folder With Space\\\"}",
	"problemMatcher": [],
	"label": "Test Task"
		}
```
I'm going to leave this issue open and close it after I have added documentation to the tasks page about how to handle tasks with powershell cmdlets. @szul, thanks for your patience and help! Based on your task, I think it should probably look like this:
```
{
	"label": "chatdown",
	"type": "shell",
	"command": "& {Get-ChildItem **/*.chat | ForEach-Object { chatdown \\\"$(Split-Path $_.FullName)/$($_.Name )\\\" >  \\\"$(Split-Path $_.FullName)/$($_.BaseName).transcript\\\" }}",
	"args": ["-Command"],
	"problemMatcher": [],
}
```

**Comment by msftrncs** [comment] 2019-05-24 00:42
FYI, the `&` (invoke operator, redundant in this case) and braces around the entire command should be unnecessary, as is the '-command' arg, while using the 'shell' type.

```
	"command": "Get-ChildItem **/*.chat | ForEach-Object { chatdown \\\"$(Split-Path $_.FullName)/$($_.Name )\\\" >  \\\"$(Split-Path $_.FullName)/$($_.BaseName).transcript\\\" }",
```

Ideally, VS Code should automatically escape the quotes contained in the command, and in the args, and in any expanded variables, and should wrap the entire command in quotes before passing to PowerShell.   I pushed such a PR to GitHub Desktop back in December for a similar issue because it prevented Desktop from starting VS Code if the repository path contained spaces.  Every arg passed to a shell should be quoted if itself contains spaces.  Probably too late to change this behavior now though, as it would break existing task configurations.

**Comment by alexr00** [comment] 2019-05-31 08:53
Adding to documentation here: https://github.com/microsoft/vscode-docs/pull/2723

**Closed by alexr00** 2019-05-31 08:53 UTC
Labels: tasks
