### ISSUE TITLE
Make JavaScript comment blocks collapsible

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#84732] opened 2019-11-13 19:57 UTC
Issue Type: <b>Feature Request</b>

JavaScript comment blocks aren't able to be collapsed and they should be.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment] 2019-11-13 21:45
Duplicate of https://github.com/microsoft/TypeScript/issues/22732

**Closed by mjbvz** 2019-11-13 21:45 UTC
