### ISSUE TITLE
Folding - match in folded region is skipped

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2967] opened 2016-02-12 14:17 UTC
- Create some text with a folding region that includes `foobar`
- Fold this region
- Start a find for `foobar` 

-> the find box shows the correct number of matches, but when you want to step through them the match in the folded region isn't shown.

The expected behaviour is that the folding region expands to show the match.

**Comment by aeschli** [comment] 2016-02-24 14:46
duplicate of https://github.com/Microsoft/vscode/issues/2967

**Closed by aeschli** 2016-02-24 14:46 UTC
Labels: bug
