### ISSUE TITLE
Menu: clicking menu with touch does not work every second time

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52945] opened 2018-06-26 12:21 UTC
Refs: #52854

Steps:
* use a windows machine with touch display
* touch once to open a menu (e.g. File)
* touch another menu

=> 🐛 the menu does not open

**Comment by sbatten** [comment] 2018-08-21 17:37
duplicate of #56903

**Closed by sbatten** 2018-08-21 17:37 UTC
Labels: bug, workbench-menu
