### ISSUE TITLE
Interactive Playground: Rename Refactoring doesn't work

### ISSUE THREAD

**Issue by VAggrippino** [Microsoft/vscode#44156] opened 2018-02-21 19:58 UTC
### Issue Type
Bug

### Description

1. Choose Help / Interactive Playground
2. In the resulting window, scroll down to the "Rename Refactoring" section and place the cursor on the first occurrence of "Book" in the example.
3. Press F2
4. Type `Document` and press ENTER.

Expected:
All occurrences of `Book` should change to `Document`.

Observed:
Nothing changes. Sometimes I get the message "No Result". Sometimes I get the message "You cannot rename elements that are defined in the standard TypeScript Library". Most times nothing at all happens.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|7.89GB (2.40GB free)|
|Process Argv|D:\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by l8nite** [comment] 2018-02-23 12:54
Same here, brand new install.

**Comment by mjbvz** [comment] 2018-03-01 03:09
Duplicate of #44172

**Closed by mjbvz** 2018-03-01 03:09 UTC
Labels: editor, editor-contrib
