### ISSUE TITLE
Code preview on right covers a few characters

### ISSUE THREAD

**Issue by pwschaedler** [Microsoft/vscode#49494] opened 2018-05-08 22:57 UTC
Issue Type: <b>Bug</b>

Specifically working on an HTML file, the code preview on the right covers a few characters, so the cursor becomes invisible. Seems to be the same as #31312, which was closed

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.78GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
latex-workshop|Jam|5.3.3
format-php|Kas|1.1.2
language-haskell|jus|2.4.0
python|ms-|2018.4.0
cpptools|ms-|0.17.0
prolog|reb|0.0.4
java|red|0.24.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.7.0
markdown-pdf|yza|1.2.0

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment] 2018-05-15 07:38
@pwschaedler I can no longer reproduce #31312. Can you please share your settings and perhaps a screenshot of the problem.

**Comment by pwschaedler** [comment] 2018-05-15 08:12
Here are my user settings:
```
{
    "editor.fontFamily": "Inconsolata, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontSize": 14,
    "files.hotExit": "off",
    "editor.wordWrap": true,
    "workbench.iconTheme": "vs-seti",
    "[python]": {
        "editor.insertSpaces": true
    },
    "workbench.colorTheme": "Smyck",
    "python.pythonPath": "/usr/local/bin/python3",
    "python.linting.pylintArgs": [
        "--extension-pkg-whitelist=numpy"
    ],
    "workbench.startupEditor": "newUntitledFile",

    "editor.quickSuggestions": false,
    "editor.suggestOnTriggerCharacters": false,
    "editor.wordBasedSuggestions": false,
    "editor.quickSuggestionsDelay": 1000000,
    "editor.parameterHints": false,
    "latex-workshop.view.pdf.viewer": "tab"
}
```

And a screenshot of the issue:
<img width="1072" alt="screen shot 2018-05-15 at 1 09 33 am" src="https://user-images.githubusercontent.com/8781353/40044668-f200623c-57dc-11e8-841f-a32a06e54b5a.png">

**Comment by alexandrudima** [comment] 2018-05-15 08:27
Thanks for the screenshot, this clarifies things!

The root cause are the CSS color boxes, which are not taken into account when wrapping is computed. Duplicate of #32856.

**Closed by alexandrudima** 2018-05-15 08:28 UTC
Labels: needs more info
