### ISSUE TITLE
terminal opens to root of multiroot project of file initially opened

### ISSUE THREAD

**Issue by vrachels** [Microsoft/vscode#39826] opened 2017-12-06 20:34 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.1
tslint|eg2|1.0.24
debugger-for-chrome|msj|3.5.0
peep|nwa|0.0.5
vscode-docker|Pet|0.0.22
perforce|sle|3.0.0
autoimport|ste|1.5.3

Seemingly random start location when first encountered this.   Figured out that the cwd is the root of the  the current file that was opened when the terminal was first opened - but it remembers that cwd even when closing the terminal (hide or X) and opening while editing a different file in a different root)
To make it even more confusing, Vscode also remembers between executions - if the file that it is re-opened to is not actually in the workspace (ie, the user settings editor), it will use the previous run's cwd.

setting "" in settings terminal.integrated.cwd results in the same behavior
setting the name of the root desired to be the cwd actually causes opening the terminal to hang (ie "terminal.integrated.cwd": "files" for a root called files)

workaround is to specify full path to desired cwd in settings.  That isn't a good solution, since it cannot be set in the workspace file, since local project location might not be in same path for all developers

preferred feature could be something along the lines of:
new setting: "terminal.integrated.preferredRoot": "<name of root>"
new setting: "terminal.integrated.newRoot": "ask" | "usePreferred" | "useFile" - for pressing the '+' to ask vs using the above setting, vs using the current file's root.

could also just make the first root the 'preferredRoot'

---

Steps to Reproduce:

1. open multi root workspace
2. open terminal
3. open file in a root other than the terminal's current root / cwd
4. close vscode.  open vscode
5. note terminal's cwd is path to root of 3's file
6. open file in a root other than the terminal's current root / cwd
7. close / open vscode
8. note cwd is path to root of 6's file
9. open user settings
10. close / open vscode
11. note cwd is path to root of 6's file
---
1. set user setting: "terminal.integrated.cwd" to one of the names of the root paths
2. close/open vscode, open terminal if it wasn't already
3. note broken terminal window

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-12-11 18:33
I think you're opening the terminal using ctrl+` which actually *toggles* the panel and focuses the terminal, creating a terminal in the "default" root in the process. The default root here is defined as the first root in the explorer list.

I suggest you use ctrl+shift+` instead which will allow you to select the root:

![image](https://user-images.githubusercontent.com/2193314/33847237-be5e526a-de5e-11e7-955c-759e6759953b.png)

**Comment by vrachels** [comment] 2017-12-19 19:24
I think you may have missed the finer details of the bug report.   It would be fine / expected for it to always create the initial terminal in the default / first root.

Actual behavior is some remembered root, or a frozen console, in certain situations.
Specifically, the "... root of the the current file that was opened when the terminal was first opened"

**Comment by Tyriar** [comment] 2017-12-31 16:24
One of the things we didn't want to emphasize was the concept of a "default root", preferring the "last active root" instead. We wanted to move in this direction because there is no UI affordance that indicates the active/default root and it's not clear that it would be the first. For the terminal we only opt for the first root when no files have been opened in the workspace yet, this is the case because we want the terminal panel to open instantly when toggled.

As for the frozen/broken terminal window, I couldn't seem to reproduce this. Does is happen every time you do these steps?

1. set user setting: "terminal.integrated.cwd" to one of the names of the root paths
2. close/open vscode, open terminal if it wasn't already
3. note broken terminal window

**Comment by vrachels** [comment] 2018-01-02 19:02
after further investigation:
looks like it's using a relative t.i.c. value as a relative path to the _calculated_ root, rather than from the code-workspace path.  
  If that path doesn't exist, it freezes the default/toggled console.
  If I set a non-relative path to something that doesn't exist on disk, I get the same frozen behavior. (ie E:\\foo)


Other unexpected behavior is that the t.i.c. setting has no effect on a 'new' (rather than toggle) terminal.  At the very least, I would expect an additional entry in the selector for a tic that doesn't match any of the listed roots.   It would be preferred to have the option to specify skipping the dialog at all - either another keybinding, shift-click +, or a user-setting to apply.

**Comment by vrachels** [comment] 2018-01-27 02:44
Is further information needed?

**Comment by Tyriar** [comment] 2018-01-30 00:05
I'm not sure what t.i.c. is. For the freeze I think you're saying it's related to opening invalid folders? If so this is captured in https://github.com/Microsoft/vscode/issues/17450 and https://github.com/Microsoft/vscode/issues/31301

**Comment by Tyriar** [comment] 2018-01-30 01:00
Ah ok, I think the freezing is captured in the above 2 images then.

**Comment by vrachels** [comment] 2018-01-30 01:22
Indeed.  Still definitely a bug that trying to set a relative path as the t.i.c. results in unexpected behavior:  it should use a relative path from workspace root, not the calculated root.   Another thought I had for a workaround that didn't work as expected was to set t.i.c to ${workspaceFolder}.   This similarly froze.

with regards to the title issue: I would also argue that the implemented behavior is less clear (and has even less affordance) than having a default root (though of course the bugs don't help matters).  At least a default is consistent, and one can expect to go through settings to change specific behavior.

**Comment by Tyriar** [comment] 2018-01-30 18:55
@bpasero is it true that we still don't have and should keep away from a "default root" concept?

**Comment by bpasero** [comment] 2018-01-31 05:48
@Tyriar the only thing we have is deriving the root from the currently opened editor or if no editor is opened the root from the last opened editor that was part of the workspace.

**Comment by Tyriar** [comment] 2018-01-31 17:03
That's still my thinking as well. I'll close this off as designed, the bad paths breaking the terminal bug is tracked in https://github.com/Microsoft/vscode/issues/17450 and https://github.com/Microsoft/vscode/issues/31301

**Closed by Tyriar** 2018-01-31 17:03 UTC
Labels: integrated-terminal, needs more info

**Comment by vrachels** [comment] 2018-01-31 18:37
sorry, I still think there's a bug here if a relative path is specified in terminal.integrated.cwd
if will still calculate the derived root, then it applied the t.i.c value.
expected behavior is to either don't allow a relative path (and if so, please allow ${woorkspaceFolder}), or to apply the relative path from the .code-workspace file.

**Comment by Tyriar** [comment] 2018-01-31 19:04
@vrachels so you want `terminal.integrated.cwd` to work in folder settings? Let's move this into a new focused issue as this issue has discussed many different areas. I created https://github.com/Microsoft/vscode/issues/42661
