### ISSUE TITLE
Extension host goes off time to time 

### ISSUE THREAD

**Issue by Dellysn** [microsoft/vscode#176839] opened 2023-03-11 07:22 UTC
Type: <b>Bug</b>

There are no particular steps to reproduce... it just happens randomly

VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin x64 21.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 9, 9|
|Memory (System)|8.00GB (1.52GB free)|
|Process Argv|--crash-reporter-id 80a0e882-8b9c-49f9-a78e-e7945cc98cc8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
commit-message-editor|ada|0.23.0
codesnap|adp|1.3.4
emoji-log-vscode|ahm|1.3.0
project-manager|ale|12.7.0
stackoverflow-search|Ale|1.2.0
vscode-tailwindcss|bra|0.9.7
better-toml|bun|0.3.2
multi-cursor-case-preserve|Car|1.0.5
turbo-console-log|Cha|2.7.1
path-intellisense|chr|2.8.4
cssrem|cip|3.1.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
copilot|Git|1.77.9225
todo-tree|Gru|0.0.224
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.2.0
playwright|ms-|1.0.9
js-debug-nightly|ms-|2023.3.817
vsliveshare|ms-|1.0.5834
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.24.0
prisma|Pri|4.11.0
vscode-thunder-client|ran|2.5.1
vscode-yaml|red|1.12.1
LiveServer|rit|5.7.9
smartsemicolon|seu|1.0.3
errorlens|use|3.7.0
highlight-matching-tag|vin|0.11.0
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0
vscode-postcss|vun|2.0.2
vscode-wakatime|Wak|24.0.7
console-ninja|Wal|0.0.84
quokka-vscode|Wal|1.0.527
glean|wix|5.2.2
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.5.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vscodedisable:30660115
funwalk2:30682974
pythonms35cf:30680985

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:23
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:23 UTC
Labels: freeze-slow-crash-leak, extension-host
