### ISSUE TITLE
[css] Support @container css rule

### ISSUE THREAD

**Issue by OOPS-Studio** [microsoft/vscode#179314] opened 2023-04-05 20:50 UTC
Visual Studio Code does not recognize the `@container` at-rule in CSS.

`Unknown at rule @container`

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries

**Comment by aeschli** [comment] 2023-04-06 13:49
Duplicate of https://github.com/microsoft/vscode/issues/170589

**Closed** 2023-04-26 20:42 UTC
