### ISSUE TITLE
language auto detect choose Groovy instead of Python

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#129719] opened 2021-07-28 21:24 UTC
```
Version: 1.59.0-insider (user setup)
Commit: e437d424c5e6de97632f5513229c7ebc2cf27a32
Date: 2021-07-28T05:13:47.114Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19041
```

Did a quick search for Python samples, found this

https://skillcrush.com/blog/python-programming-examples/#:~:text=25%2B%20Python%20Programming%20Examples%201%20Remove%20Duplicates%20Function.,KM%2FH%20to%20MPH%20converter.%20...%20More%20items...%20

Set the setting `"workbench.editor.untitled.experimentalLanguageDetection":true,`
Copy/Pasted the following Magic 8 Ball code into a new untitled file:

``` python
import sys
import random

ans = True

while ans:
    question = raw_input("Ask the magic 8 ball a question: (press enter to quit) ")
    
    answers = random.randint(1,8)
    
    if question == "":
        sys.exit()
    
    elif answers == 1:
        print "It is certain"
    
    elif answers == 2:
        print "Outlook good"
    
    elif answers == 3:
        print "You may rely on it"
    
    elif answers == 4:
        print "Ask again later"
    
    elif answers == 5:
        print "Concentrate and ask again"
    
    elif answers == 6:
        print "Reply hazy, try again"
    
    elif answers == 7:
        print "My reply is no"
    
    elif answers == 8:
        print "My sources say no"
```

Auto Detect picked Groovy, not Python

![image](https://user-images.githubusercontent.com/1487073/127397940-3b02d247-11cd-4f1b-ab07-2f8027b310d9.png)

**Comment by JacksonKearl** [comment] 2021-08-17 20:11
seems to choose python now, not sure if this is one of those CLRF issues

**Comment by TylerLeonhardt** [comment] 2021-08-17 20:17
Yep I bet it was the CLRF issue... duplicate of #129730

**Closed by TylerLeonhardt** 2021-08-17 20:17 UTC
