### ISSUE TITLE
TreeError [CustomView] Data tree node not found 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#82629] opened 2019-10-15 18:30 UTC
- VSCode Version: 1.39.1
- OS Version: Windows 10

**This issue does not occur with 1.38.1** 
I am from the python extension team. I have investigated the issue from the extension side. This looks like a issue in the Tree View we use for test explorer.

### Steps to Reproduce:
1. Install python extension. 
2. Have following files and contents in the work-space folder:

**some_test.py**
```py
from math import factorial
import pytest
import unittest

class Test1(unittest.TestCase):
    def test_dosomething(self):
        self.assertEquals(1, 1)

@pytest.mark.parametrize("n, e", [(0, 1), (1, 1), (5, 120)])
def test_valid(n, e):
    assert factorial(n) == e
```
**.vscode/settings.json**
```js
{
    "python.testing.pytestArgs": [
        "."
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true,
}
```
3. Run "Discover Tests" from the command pallet.
4. Open Test explorer and run a test.
5. The tree view fails to update.

![issue7898](https://user-images.githubusercontent.com/3840081/66857815-e58fe600-ef3c-11e9-87ac-31e08d369bbc.gif)

Does this issue occur when all extensions are disabled?: N/A

Console:
```
Error: TreeError [CustomView] Data tree node not found: [object Object]
    at Y.getDataNode (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1045:675)
    at Y.rerender (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1043:295)
    at t.visible.e.map.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4974:446)
    at Array.map (<anonymous>)
    at U.doRefresh (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4974:437)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This looks related: #82290
Python extension side issue: https://github.com/microsoft/vscode-python/issues/7898

**Comment by askvortsov1** [comment] 2019-10-15 19:16
https://github.com/microsoft/vscode-python/issues/7975 Has a similar error message in the console, might be related as well.

**Comment by luabud** [comment] 2019-10-15 20:12
Python extension side issue link is here: https://github.com/microsoft/vscode-python/issues/7898 
The number in the original thread is correct but it's linked to one in the vscode repo :)

**Comment by jamesharris-garmin** [comment] 2019-10-16 21:26
Confirmed with 1.39.2

**Comment by pbotsman** [comment] 2019-10-24 06:50
Hello!

Is there any chance that this issue could be fixed in the current release?

Because of this issue, I had to downgrade to a previous version of the VS Code.
Looks like many developers who faced the same issue did the same.

Thank you!

**Comment by astrowonk** [comment] 2019-11-05 14:15
I'm with @pbotsman - I had to downgrade vscode so I could run unit tests without the animation spinning forever. Any update?

**Comment by consal** [comment] 2019-11-06 14:36
Any news on that? Still experiencing this issue

**Comment by gadol21** [comment] 2019-11-07 18:01
I managed to narrow down the issue to this commit:
https://github.com/microsoft/vscode/commit/f27b246e7869f49b475a0c35b19f216ed91726cb
from this PR - https://github.com/disksing/vscode/pull/1274/files

It is a revert of another commit, and i guess it was done for a good reason.
@joaomoreno why did you revert this change?

**Comment by jamesharris-garmin** [comment] 2019-11-07 19:31
Looks like it was attempting to find a better fix for #78388 unfortunately this workaround was a load bearing workaround for python developers.  I wonder why we seem to be failing in this context, or if the fix needs to move back to [microsoft/vscode-python](https://github.com/microsoft/vscode-python).

**Comment by karthiknadig** [comment] 2019-11-07 21:28
If this is not going to be changed in VS Code, please provide guidance on how to resolve this on the extension side. Since, we didn't really change anything in how we work with trees and we are now broken.

**Comment by astrowonk** [comment] 2019-11-08 00:33
I have to repeat that this is an extremely debilitating bug that requires any python developer to use 1.38. The silence on this is frustrating. It been open 23 days.

**Comment by xmatthias** [comment] 2019-11-08 08:26
The same problem also occurs in the current release (1.40).

Would be great if this could get some priority...
@luabud, @DonJayamanne (sorry for disturbing) - since it's affecting python tests - any chance to push this from within Microsoft?

**Comment by tdamsma** [comment] 2019-11-08 09:30
After updating to 1.40 checking if this was fixed was the first thing I did, was also a bit disappointed that fixing this issue didn't make it as I have come to rely upon it quite a bit.

**Comment by joaomoreno** [comment] 2019-11-08 09:52
Unfortunately this got lost since @sandy081 was out. Moving to @alexr00. cc @roblourens

**Comment by Meltz014** [comment] 2019-11-11 21:07
Any update on this issue?

**Comment by alexr00** [comment] 2019-11-12 08:39
Thanks for the easy repro steps! I can reproduce the issue. Now to find the cause...

**Closed** 2019-11-12 09:39 UTC
Labels: bug, candidate

**Comment by valerierose** [comment] 2019-11-12 21:11
I am also experiencing this issue. I've (mistakenly) filed bug reports with 3 separate extensions related to tests in python, the latest with much detail is here: https://github.com/microsoft/vscode-python/issues/8502.

I'm about to downgrade vscode because it is very disruptive.

**Comment by eedwards-sk** [comment] 2019-11-12 21:17
Did this really just get solved by swallowing all exceptions? o.O

**Comment by astrowonk** [comment] 2019-11-13 00:09
yeah @joaomoreno, is your commit the permanent fix? Wrapping it in try/catch?

**Comment by joaomoreno** [comment] 2019-11-13 08:49
@astrowonk No it's not. Proper fix will come with https://github.com/microsoft/vscode/issues/84569
