### ISSUE TITLE
Absolute path with root slash imports breaks intellisense

### ISSUE THREAD

**Issue by sikloidz** [Microsoft/vscode#31408] opened 2017-07-25 18:58 UTC
Hi.
I been  struggling with absolute path imports because intellisense breaks (and go to definition too), this import statement breaks intellisense:
```
import Something form '/imports/collections/something.js';
```
But this one doesn't:
```
import Something from 'imports/collections/something.js';
```
The problem is that I'm using meteor, which works with the first import statment but not with the second one.

Is there a way to configure vs code for working with absolute imports that includes a root slash? WebStorm support this but I really like more vs code.

ps. sorry for my bad english

**Comment by mjbvz** [comment] 2017-07-26 19:12
Try configuring the `paths` option in your `tsconfig` or `jsconfig` file. Here's the documentation on this: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

You'd probably want something like:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "/*": [
        "*"
      ]
    }
  }
}
```

**Comment by sikloidz** [comment] 2017-07-26 20:40
Hi.
Thanks for the answer, but the configuration that you suggest I already tried it and does not solve the problem.
Now, the documentation in the link that you provide me, says that an import starting with slash is treated as a relative import, since this documentation is for typescript, is the same for javascript? And if so, is there a way to make that vs code does not treat an import starting with a slash as a relative import?

**Comment by stolinski** [comment] 2017-08-02 20:53
I'm having this same issue. The above config does not work for `import Something form '/imports/collections/something.js';`

**Comment by juho** [comment] 2017-10-12 16:16
Also not working here

**Comment by sikloidz** [comment] 2017-10-12 16:24
It's seems that they won't fix it, and now I really don't think they should (it's more like meteor's problem). Also if you use typescript with meteor, you can configure paths aliases, but obviously use typescript is not an option for everyone.

**Comment by juho** [comment] 2017-10-12 16:32
Hmm. To me it's an odd idea that an IDE would or should not support a certain way of importing code. I'd vote for this to be supported so the tool at hand can be used to its fullest extent. Relative paths are not an option in a larger application, so this really hampers the experience with VSC.

**Comment by sikloidz** [comment] 2017-10-12 17:11
I agree that relative imports it's not the way to go, but maybe meteor should not be tied to root slash imports, but let us define namespaces for our modules, so instead of importing like this:

`import Something from '/modules/partners/collections/something.js`

We could configure a namespace an do something like this:

`import Something from 'partners/collections.js'`

And finally, if they someday fix this issue, I'll don't be mad, it's just that doesn't seems that they are willing to do it, at least not right now.
I know that this made vscode less attractive, but sadly for me, webstorm is justo to slow (webstorm doesn't have this problem)

**Comment by klaasman** [comment] 2017-11-08 09:28
I wonder *why* root slash imports aren't supported, as @juho says: an IDE should not decide how you import your modules.

I'm working with a Webpack configuration that is using the leading slash as project root, this won't go very well together with vscode. Defining module-namespaces is not really an option, since this could potentially clash with modules inside the `node_modules`.

**Comment by klaasman** [comment] 2017-11-08 09:45
@mjbvz It looks like your example should the right way to go, but it looks like it isn't working. Any other ideas?

**Comment by juho** [comment] 2017-11-08 13:11
@klaasman there was some discussion on it recently on the forums where people reported success with `eslint-plugin-import` and `eslint-import-resolver-meteor`:  https://forums.meteor.com/t/vscode-absolute-imports/40278/10

**Comment by juho** [comment] 2017-11-08 13:22
I feel like @mjbvz could weigh in also seeing how his solution doesn't work and workarounds are needed

**Comment by klaasman** [comment] 2017-11-08 13:44
Thanks for pointing me to that package, but I don't feel like importing meteor-specific linting-configuration in a project with 0 meteor-related code :-)

**Comment by stolinski** [comment] 2017-11-08 14:19
The solution from that thread wasn't to use an eslint package, I'm not sure why that was suggested as a solution. I used  https://github.com/tleunen/babel-plugin-module-resolver to fix this.

**Comment by klaasman** [comment] 2017-11-08 15:08
Ah I see. I'm afraid it won't work in my situation: I'm working with a single dependency webpack-setup, all babel configuration is managed by this dependency which means the config is living inside some folder in the node_modules.

**Comment by mjbvz** [comment] 2017-11-08 19:23
@mhegazy Any idea on how to setup a `jsconfig.json` for this case? I thought configuring a `paths` for `/*` used to work

**Comment by mhegazy** [comment] 2017-11-09 00:15
`/` is seen by the system as an absolute path.. it refers to the root directory.. we have a request to allow mapping that using path mapping in https://github.com/Microsoft/TypeScript/issues/13730

**Comment by juho** [comment] 2017-11-09 10:30
It would be great to have this solved as it's most likely causing hundreds of lost man hours across the board trying to find a fix and applying different plugins, just judging from the amount of forum, stackoverflow etc. posts I've seen on it.

**Comment by mjbvz** [comment] 2017-11-09 18:22
Thanks @mhegazy! Closing this as a duplicate of Microsoft/TypeScript#13730

We'll keep tracking this upstream

**Closed by mjbvz** 2017-11-09 18:22 UTC
Labels: javascript, question
