### ISSUE TITLE
Breadcrumb dropdown uses confusing indentation

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#61808] opened 2018-10-25 15:47 UTC
- VSCode Version: 1.28.2
- OS Version: Windows 10

When an entry in the breadcrumb dropdown is expandable its icon is preceded by the indicator with which to expand it. But non-expandable entries at the same level don't have equivalent whitespace, so the alignment of siblings is confusing. Below is a screenshot from a file in the vscode-mock-debug sample.

![image](https://user-images.githubusercontent.com/6726799/47512887-061ae800-d875-11e8-8820-cc80fb50bed5.png)

**Comment by aeschli** [comment] 2018-10-28 20:07
If a theme specifies that it has no folder icons, the file explorer aligns the arrow and the file icons on the same level.
But it looks like the breadcrumb still adds icons to container (non-leaf) elements, so that doesn't work anymore.
Maybe you need to do a hybrid way of indenting: for the file/ folder level, do it as the explorer, for member level, use the regular way.
Or, don't hide container icons if the file icon theme doesn't have folders.

**Comment by gjsjohnmurray** [comment] 2018-10-29 09:08
#28974 discussed an apparently similar issue in Explorer. At one stage there was an experiment with a blank placeholder icon to correct alignments in a generic way, but that was unpopular and got reverted.

Maybe the blank placeholder strategy would be okay in the breadcrumb dropdown.

Or how about putting the twistie **after** the icon in the drobdown entries that need both?

**Comment by jrieken** [comment] 2018-10-29 11:40
<img width="432" alt="screenshot 2018-10-29 at 12 39 26" src="https://user-images.githubusercontent.com/1794099/47647587-b7709500-db77-11e8-9c4b-5bc7a1e3291b.png">

I am actually not able to reproduce this. @gjsjohnmurray Please try with latest insiders and see if the problem still exists: http://code.visualstudio.com/insiders/

**Comment by gjsjohnmurray** [comment] 2018-10-29 12:24
I'm still seeing it with Insiders and the Seti file icon theme:
![image](https://user-images.githubusercontent.com/6726799/47648963-98700400-db73-11e8-9adf-81a642dd608d.png)

But switching the file icon theme to Minimal improves matters:

![image](https://user-images.githubusercontent.com/6726799/47649158-4085cd00-db74-11e8-945f-6fcf5811545b.png)

My help\About info:
Version: 1.29.0-insider (user setup)
Commit: 4626bc0e1b679d555dd6f034ece35ffc394b3bb7
Date: 2018-10-29T06:18:55.850Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by gjsjohnmurray** [comment] 2018-10-29 12:37
So is this similar to #57115 ?

**Comment by jrieken** [comment] 2018-10-29 13:16
Thanks - using Seti makes me reproduce this...

**Comment by jrieken** [comment] 2018-10-29 13:17
stretch for october

**Comment by jrieken** [comment] 2018-10-29 14:11
Today is the last dev day for the October release. Since this isn't a regression and since this requires larger effort I am moving it out to Nov

**Comment by jrieken** [comment] 2019-02-07 09:30
@joaomoreno What determines the indentation? Also with the new tree this looks like 💩. The resource labels show a better indent then the symbol label (IconLabel) but in neither a special config is used. 

<img width="362" alt="screenshot 2019-02-07 at 10 27 49" src="https://user-images.githubusercontent.com/1794099/52401895-1de44800-2ac3-11e9-8c86-70c62b983830.png">

⬆️ really hard to see that `_value` is a child of `FooModel`

⬇️ `app.js` looks like a child of `app`

<img width="309" alt="screenshot 2019-02-07 at 10 28 02" src="https://user-images.githubusercontent.com/1794099/52401897-1e7cde80-2ac3-11e9-9ae5-3cb78625ff53.png">

**Comment by jrieken** [comment] 2019-02-07 09:32
wow - this actually looks good when using *no* icon theme. Is @aeschli changing some global tree config?


:down: pretty, no icons!
<img width="251" alt="screenshot 2019-02-07 at 10 31 25" src="https://user-images.githubusercontent.com/1794099/52402051-921eeb80-2ac3-11e9-8746-c08e78af0c84.png">

**Comment by joaomoreno** [comment] 2019-02-07 09:49
The old tree's styling for this was a [complete nightmare](https://github.com/Microsoft/vscode/blob/45c7f29565821668f4d010b25e3289953bd9ac71/src/vs/workbench/browser/parts/views/media/views.css#L7-L51). The [new one](https://github.com/Microsoft/vscode/blob/45c7f29565821668f4d010b25e3289953bd9ac71/src/vs/workbench/browser/parts/views/media/views.css#L55-L61) isn't perfect, but it's much easier to understand.

Assuming we're already talking about new tree here,  I see you are already doing the _right_ thing [here](https://github.com/Microsoft/vscode/blob/45c7f29565821668f4d010b25e3289953bd9ac71/src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts#L132-L138). :thinking:

**Comment by jrieken** [comment] 2019-02-07 10:53
Ah, it might be enough to only do that for the file picker, not symbol picker!

**Comment by jrieken** [comment] 2019-02-07 11:03
That was it - those lines, that I have copy-paste'ed, are toxic for the symbol tree. When being used for the file pickers things are good 🎉

**Closed** 2019-02-07 12:58 UTC
Labels: breadcrumbs, bug
