### ISSUE TITLE
 Cannot read property 'closeMessage' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#72146] opened 2019-04-11 16:32 UTC
Issue Id: <b>fef948db-43c9-f28d-6c98-b6b3b9259643</b><br /><br />*Versions* <br />- 0ac111466ec925fd5ca180ab9893f51531e419b2<br />-  0dd516dd412d42323fc3464531b1c715d51c4c1a<br />-  4039ea871879ef8f654f27df5c32d209104b3a44<br />-  4d1cb56a5b88248b1e0f38b9980f4a1bc8a6fb1a<br />-  b5f5db349f211f5045e7dad6fd1672010d2d00de<br />-  f5044f0910e4aa7e7e06cb509781f3d56e729959<br />*Stack* <br />TypeError: Cannot read property 'closeMessage' of undefined<br />[/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#145:44 (emit)](https://github.com/microsoft/vscode/blob/0ac111466ec925fd5ca180ab9893f51531e419b2/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L145:44 (emit))<br />    at MouseZone.leaveCallback (\node_modules.asar\vscode-xterm\lib\Linkifier.js:194:25)<br />    at MouseZoneManager.clearAll (\node_modules.asar\vscode-xterm\lib\ui\MouseZoneManager.js:59:39)<br />    at Terminal.<anonymous> (\node_modules.asar\vscode-xterm\lib\Terminal.js:428:105)<br />    at Terminal.EventEmitter.emit (\node_modules.asar\vscode-xterm\lib\common\EventEmitter.js:70:20)<br />    at Terminal.emit (\node_modules.asar\vscode-xterm\lib\public\Terminal.js:47:20)<br />[/vs/workbench/contrib/terminal/browser/terminalInstance.ts#836:15 (setVisible)](https://github.com/microsoft/vscode/blob/0ac111466ec925fd5ca180ab9893f51531e419b2/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L836:15 (setVisible))<br />[/vs/workbench/contrib/terminal/browser/terminalTab.ts#366:40](https://github.com/microsoft/vscode/blob/0ac111466ec925fd5ca180ab9893f51531e419b2/src/vs/workbench/contrib/terminal/browser/terminalTab.ts#L366:40)<br />    at Array.forEach (<anonymous>)<br />[/vs/workbench/contrib/terminal/browser/terminalTab.ts#366:25 (setVisible)](https://github.com/microsoft/vscode/blob/0ac111466ec925fd5ca180ab9893f51531e419b2/src/vs/workbench/contrib/terminal/browser/terminalTab.ts#L366:25 (setVisible))<br />[/vs/workbench/contrib/terminal/common/terminalService.ts#266:41](https://github.com/microsoft/vscode/blob/0ac111466ec925fd5ca180ab9893f51531e419b2/src/vs/workbench/contrib/terminal/common/terminalService.ts#L266:41)<br />    at Array.forEach (<anonymous>)<br />    at Proxy.setActiveInstanceByIndex (out/vs/<br />

**Comment by Tyriar** [comment] 2019-05-20 19:18
From https://github.com/microsoft/vscode/issues/73974

> Had a window open for awhile, then randomly I can't open the panel anymore. Any keyboard shortcut that would show the panel just causes a notification to appear with Cannot read property 'closeMessage' of undefined. The terminal was probably active when I used it last. This was a remote ssh window.

**Comment by usernamehw** [comment] 2019-05-20 19:32
@Tyriar, that's great. Is it possible to make it a `candidate`?

**Comment by Tyriar** [comment] 2019-05-20 19:47
@usernamehw I wasn't able to reproduce the problem, did you hit it in a remote window?

**Comment by usernamehw** [comment] 2019-05-20 19:59
No, not remote. I have no steps. When I tried to reproduce it - it always worked. But that error popped up almost every day.

**Comment by Tyriar** [comment] 2019-05-20 22:27
I'll mark it as a candidate as it's a pretty safe change, not sure if we're doing a recovery build yet for this release.

**Comment by simeonwillbanks** [comment] 2019-05-21 12:46
Please forgive me, if this isn't helpful, I am new to vscode.  

I'm seeing this error, and I thought it was an issue with a plugin since I'd see the error while running the plugin.  Here are all the details.

https://github.com/Pallinder/rails-test-runner/issues/7

**Comment by Tyriar** [comment] 2019-05-21 23:37
@simeonwillbanks it should be fixed in today's Insiders build

**Comment by Tyriar** [comment] 2019-05-22 21:24
Fixed properly in a695b11e19580ab4c2b0b45b09f6594cf6663109 😅

**Closed** 2019-05-22 21:24 UTC
Labels: candidate, error-telemetry, integrated-terminal

**Comment by simeonwillbanks** [comment] 2019-06-11 13:24
@Tyriar thank you!

I'm trying out "May 2019 (version 1.35)", and I'll report back.

**Comment by simeonwillbanks** [comment] 2019-06-20 13:02
@Tyriar The issue is gone. Thank you for the help. ❤️
