### ISSUE TITLE
VsCode open one file in duplicated tabs when trying to use auto-import

### ISSUE THREAD

**Issue by luannguyend86** [microsoft/vscode#100816] opened 2020-06-23 04:25 UTC
Issue Type: <b>Bug</b>

```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (5 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

After upgrading my VsCode on Mac, I experienced an issue whenever I try to auto-import/using namespace with my C# code.

Step to reproduce: (I'm using C#)
1. Define a new type (what ever: enum, class,...) in one file code.
2. Navigate to new class file or existing one, try to declare new property by new type at step #1
3. The intelligent helper will indicate the new type and ask for resolving by import/using new type (by red underline)
4. Move the cursor to the error indicator, press Ctrl + . (Cmd + . on Mac) to allow Vscode to do it automatically
 Expecting issue: 
- on the left panel, there are two file (with the same name) of current file code is shown
- on the right, there are two tab which contains the same file codes, and one get latest update by intelligent helper, the rest is not

Hope this help!

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
format-indent|Kas|1.3.0
namespace|adr|1.1.2
aws-toolkit-vscode|ama|1.10.0
mermaid-markdown-syntax-highlighting|bpr|1.0.2
vscode-ipaddress|Com|1.0.0
dart-code|Dar|3.11.0
flutter|Dar|3.11.0
vscode-shell-snippets|Dee|0.3.1
gitlens|eam|10.2.2
php-debug|fel|1.13.0
dotnet-test-explorer|for|0.7.3
gc-excelviewer|Gra|3.0.36
rest-client|hum|0.24.1
ilspy-vscode|ics|0.7.11
vscode-tfs|iva|0.7.2
git-graph|mhu|1.24.0
prettify-json|moh|0.0.3
vscode-language-pack-zh-hans|MS-|1.46.3
csharp|ms-|1.22.1
mssql|ms-|1.9.0
azure-account|ms-|0.8.11
node-debug2|ms-|1.42.4
powershell|ms-|2020.6.0
quicktype|qui|12.0.46
java|red|0.63.0
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-mermaid-preview|vst|1.5.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by tuoitrexuquang** [comment] 2020-06-23 04:28
got the same issue

**Comment by nhn12** [comment] 2020-06-23 04:29
I also got the same issues.

**Comment by dbaeumer** [comment] 2020-06-23 07:40
@bpasero assigning to you because of the `on the left panel, there are two file (with the same name) of current file code is shown`. Could this be a regression because of the URI work ?

**Comment by bpasero** [comment] 2020-06-23 07:43
Needs more info, e.g. screenshots or screenshare how this looks like.

**Comment by luannguyend86** [comment] 2020-06-24 11:33
@bpasero Please see below, 
the first picture is the right tabs, after using Cmd + . to choose to implement the interface
<img width="860" alt="Screen Shot 2020-06-24 at 6 21 13 PM" src="https://user-images.githubusercontent.com/51289831/85548008-b2176680-b648-11ea-932e-3819ffa5d772.png">

and the second is the left panel information:
<img width="494" alt="Screen Shot 2020-06-24 at 6 21 24 PM" src="https://user-images.githubusercontent.com/51289831/85548177-e1c66e80-b648-11ea-9788-0163341cdffc.png">

As you can see, the editor is automatically open the same file.
This could caused some unknown errors once you only make editing to one of duplicated tab.

Hope this help!

**Comment by bpasero** [comment] 2020-06-24 15:27
@luannguyend86 can you right-click "Copy Path" on both and post the results here.

**Comment by luannguyend86** [comment] 2020-06-29 14:35
Hi @bpasero , sorry for very late response.
I'm sorry can not paste the path here because of some confidential information is included, sorry for that.
Just I had tried so, the path for both files (on the left panel) or tabs on the right was the same.

Hope this help.

**Comment by bpasero** [comment] 2020-06-29 14:47
Maybe anyone from the other folks here that can reproduce could paste the path of the 2 same files from "open editors" view to compare here.

**Closed** 2020-07-07 11:23 UTC
Labels: needs more info
