### ISSUE TITLE
Double paste when copying to Python Interactive window (this did not happen before the recent upgrade)

### ISSUE THREAD

**Issue by asalcedo29** [microsoft/vscode#102536] opened 2020-07-14 22:00 UTC
Issue Type: <b>Bug</b>

Copying command from .py file into Python Interactive results in double paste. 

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.91350
highlight-words|rsb|0.1.4
tabnine-vscode|Tab|2.8.9
vscodeintellicode|Vis|1.2.9

</details>

**Comment by mjbvz** [comment] 2020-07-14 22:04
Duplicate of #101946

**Closed by mjbvz** 2020-07-14 22:04 UTC
Labels: new release
