### ISSUE TITLE
100% CPU Usage with very small project open on Ubuntu

### ISSUE THREAD

**Issue by ishanjain28** [Microsoft/vscode#18449] opened 2017-01-12 13:27 UTC
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.04 x64

Steps to Reproduce:

1. I am working on a project that can be found here: [Anekant-Pharma](https://github.com/ishanjain28/anekant-pharma)
2. Closed Every single thing on my PC like Plank, Spotify and Background Processes like Redis Server, Mongo Server etc. 
3. Vscode starts using 100% of 1-2 cores, Now one of these cores stays at 100% for about 30-35 seconds and other core stays at 100% for about 10-15 seconds and then both of these core go back to normal and then vscode starts using another 2 cores and this just goes on. 

Computer Information: 

i7 4710HQ 2.5Ghz, 8 Cores
8GB DDR3 RAM
1TB 5400 RPM drive

Vscode Information: 

Plugins Installed: 67
Plugins Enabled: 49

Notes: 

I am not using any of those battery saving tools like laptop-mode-tools which throttle CPU or GPU. 

My Laptop FAN starts rotating at fairly high speeds(Don't have the exact numbers, But it's faster than usual). 

I don't know how to check this, but I am certain that Vscode is probably using a lot of GPU power too. 

Normally, My Laptop gives 3 hours Backup, But I was using vscode+rhythmbox and it showed only 1 hour backup.

**Comment by bpasero** [comment] 2017-01-12 13:28
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by ishanjain28** [comment] 2017-01-12 13:33
No, I started it with all extensions disabled and still the same problem. [CPU-Usage-Image](https://i.imgur.com/sSYRDbG.png)

**Comment by ishanjain28** [comment] 2017-01-12 13:36
Although I would like to say, That it has been running for about 5 minutes now, And now only 1 core is stuck at 100% usage, All other cores are b/w 1-20% usage.

**Comment by bpasero** [comment] 2017-01-12 13:37
@ishanjain28 can you find out the full command line args of that process? that helps understanding which process is doing the work.

**Comment by ishanjain28** [comment] 2017-01-12 13:42
I am using Htop to get information about Proceses. [Image that shows processes with max CPU Usage](https://i.imgur.com/nEW0zTb.png)

**Comment by ishanjain28** [comment] 2017-01-12 13:44
I just restarted code with --disable-extensions flag but it shows that the culprit process has been running for 1h36m. Should I kill all code processes and then restart it with --disable-extensions flag?

**Comment by SamVerschueren** [comment] 2017-01-12 14:11
@ishanjain28 Yes! I had it as well a couple of times, ended up being an extension not running correctly. So make sure you killed all those processes first (CodeHelper) and start Code again. Work with it for a while and check if it's not coming back.

Take a look at [this thread](https://github.com/Microsoft/vscode/issues/17740). Maybe @roblourens could chime in to detect the issue?

**Comment by ishanjain28** [comment] 2017-01-12 14:21
Yes!! That fixed the problem, It's now working very smoothly like it used to.. Thank you so much @SamVerschueren

**Comment by dbaeumer** [comment] 2017-01-16 10:50
The process that causes the CPU usage was the extension host. @jrieken FYI

@ishanjain28 without being able to check the extension host it is impossible to track this down. I will close the issue since the problem disappeared for you. Please ping if you see it again and we will try to understand why the extension host is causes such a CPU spike.

**Closed by dbaeumer** 2017-01-16 10:50 UTC
Labels: needs more info, perf
