### ISSUE TITLE
Error in Restore Panel Size button when change focus in fullscreen

### ISSUE THREAD

**Issue by ktowen** [Microsoft/vscode#62987] opened 2018-11-13 03:11 UTC
Issue Type: <b>Bug</b>

In fullscreen mode with the panel at the bottom open and maximized, when the focus changes (Alt+tab) the button changes to Maximize again but the panel it's already maximized

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment] 2018-11-13 10:29
I can not reproduce this. Can you reproduce with latest vscode insiders
https://code.visualstudio.com/insiders/

If yes can you attach a short video showing this?

**Comment by ktowen** [comment] 2018-11-14 06:45
Fresh installation
Version: 1.30.0-insider (user setup)
Commit: c72cb129f2a0b8117c9b01f3767026041d7d1d31
Date: 2018-11-13T06:19:28.504Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
 
![video_2018-11-14_013607](https://user-images.githubusercontent.com/17689932/48464804-c9c11480-e7ae-11e8-8efc-085ce731879c.gif)

**Comment by isidorn** [comment] 2018-11-14 09:32
That is fine, the issue here is that alt shows the custom menu
Showing the custom menu the whole workbench layouts and that changes the panel size which makes the panel not maximized anymore,
Closing as duplicate of some older issues / will get fixed when we get this https://github.com/Microsoft/vscode/issues/50853

**Closed by isidorn** 2018-11-14 09:32 UTC
Labels: needs more info, new release
