### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dicotomy** [microsoft/vscode#103321] opened 2020-07-25 17:42 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.RangeError: Maximum call stack size exceeded
    at toFileNameLowerCase (c:\Users\Poston\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200724\node_modules\typescript\lib\tsserver.js:1555:40)
    at Object.toPath (c:\Users\Poston\.vscode\extensions\ms-vscode.vscode-typescript-next-

**Comment by mjbvz** [comment] 2020-07-27 19:36
Duplicate of https://github.com/microsoft/TypeScript/issues/39321

If you have repo step or an example project that causes this, please share them

**Closed by mjbvz** 2020-07-27 19:36 UTC
