### ISSUE TITLE
Automatically Close When Open New Folder

### ISSUE THREAD

**Issue by rahuldmk** [microsoft/vscode#231553] opened 2024-10-17 03:34 UTC
Type: <b>Bug</b>

Open VS Code 
then Click File Menu -> Click Open Folder -> Select My Home Folder then
VS code Automatically close 

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 3999)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (10.81GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 992858bd-7725-4fcf-a7b9-bfe7551f1295|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.0
prettier-vscode|esb|11.0.0
rest-client|hum|0.25.1
material-icon-theme|PKi|5.11.1
fabric8-analytics|red|0.9.5
java|red|1.35.1
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.57.0
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.14.0
vscode-spring-initializr|vsc|0.11.2
nyan-cat|zhe|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilotcf:31160514
icondisabled:31158250

```

</details>

**Comment by alexandrmiee** [comment] 2024-10-17 04:39
Also, the bug is reproducing when opening the file.

Click File Menu -> Click Open File -> Open Some Folder

**Comment by gjsjohnmurray** [comment] 2024-10-17 08:05
/duplicate of https://github.com/microsoft/vscode/issues/230454

**Closed** 2024-10-17 08:06 UTC
Labels: *duplicate
