### ISSUE TITLE
[Feature Request] Horizontal Search Pane

### ISSUE THREAD

**Issue by x3r10n** [Microsoft/vscode#39263] opened 2017-11-28 14:33 UTC
- VSCode Version: 1.18.1
- OS Version: MacOS

Would love to be able to place the search pane Horizontally like in actual Visual Studio.

**Comment by roblourens** [comment] 2017-11-28 17:40
/duplicate of https://github.com/Microsoft/vscode/issues/9435

**Closed** 2017-11-28 17:41 UTC
Labels: *duplicate, search
