### ISSUE TITLE
why u keep open the shittty powershell

### ISSUE THREAD

**Issue by RUSshy** [microsoft/vscode#132662] opened 2021-09-08 15:57 UTC
Issue Type: <b>Bug</b>

nobody likes this stupid shell, STOP SPAWNING IT FFS

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.06GB free)|
|Process Argv|--crash-reporter-id 8057078f-d5a4-4a7d-8fb9-5631832a2b17|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
zls-vscode|Aug|1.0.4
vscode-jetbrains-keybindings|isu|0.1.9
cpptools|ms-|1.6.0
file-and-folder-icons|nex|1.0.4
code-d|web|0.22.0

</details>

**Comment by RUSshy** [comment] 2021-09-08 15:58
```
    "terminal.integrated.profiles.windows": {
        "cmder": {
            "path": "C:\\WINDOWS\\System32\\cmd.exe",
            "args": [
                "/K",
                "C:\\app\\cmder\\vendor\\bin\\vscode_init.cmd",
            ]
        }
    },
    "terminal.integrated.defaultProfile.windows": "Git Bash",
```

fix your shitty stuff

**Comment by MetabaronCZ** [comment] 2021-09-08 16:06
I can confirm this error. After today's update the terminal sets powershell by default. If I set Git Shell as default (as I had in previous versions) it is ignored and powershell is used all the time. I also tried to delete all settings related to terminal and it didnt help.

**Comment by IllusionMH** [comment] 2021-09-08 16:08
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Closed** 2021-09-08 16:09 UTC
Labels: *duplicate
