### ISSUE TITLE
Remember previously expanded folders

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#62706] opened 2018-11-07 09:55 UTC
Issue Type: <b>Bug</b>

After restarting, the insiders build no longer remembers which sub-folders were previously expanded in the explorer view. Only the root folder is expanded. The stable build still works as expected.

Expected:
```
my_project\
  + .vscode\
  - src\
    file1.ts
    file2.ts
  + test\
```
Actual:
```
my_project\
  + .vscode\
  + src\
  + test\
```

VS Code version: Code - Insiders 1.29.0-insider (5438af145cf480ce0162bda0799435684b293ec5, 2018-11-07T01:01:54.305Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none

**Comment by isidorn** [comment] 2018-11-07 17:11
This is a regression which happened due to us changin how the memento object for views work and should only affect the explorer.
Assigning to November for now, might go into the recovery build

**Comment by isidorn** [comment] 2018-11-08 11:43
This was probably caused by this commit 7e9546a39e4a67ad27a4777c1ffde1e1fdf932d2
This is not explorer specific, we are loosing all our memento state on reload, assigning to october.
Example: Turn on centered editor layout, change the layout size -> reload, centered layout has the default size 🐛

**Comment by isidorn** [comment] 2018-11-08 12:08
After further investigation this is only happening to the explorer because the workspace mement ostate was not properly passed in. Crated a PR which address this https://github.com/Microsoft/vscode/pull/62779

I still want to:
- [ ] Verify what exact change in that large commit caused this
- [ ] Verify no other viewlets got broken as part of the memento refactoring we did

**Comment by isidorn** [comment] 2018-11-08 16:06
This should be assigned to the October recovery milestone.

**Comment by isidorn** [comment] 2018-11-09 14:02
To verify:
1. Have some folders expanded in your explorer
2. Do not have any file open in your editr
3. Reload -> make sore those folders are still expanded

**Closed** 2018-11-09 14:02 UTC
Labels: bug, candidate, file-explorer
