### ISSUE TITLE
Intellisense codicons are greyscale (Big Issue For Productivity!)

### ISSUE THREAD

**Issue by matthew-plusprogramming** [microsoft/vscode#107276] opened 2020-09-23 05:14 UTC
- VSCode Version: Insiders latest update as of 09/22/2020
- OS Version: Tested on Windows 10 Pro Insider Preview, Windows 10 Pro, Windows 10 Home, Mac OSX Catalina

Steps to Reproduce:

1. Download/update to latest version of VSCode Insiders
2. Open a JS file
3. Create a function and move your cursor inside
4. Examine either the breadcrum trail under the file name, or look at intellisense suggestions

^^^ As said in title, these codicons which are normally purple or blue to denote functions, variables, etc are now grey

Does this issue occur when all extensions are disabled?: Yes

Example of this happening:
![image](https://user-images.githubusercontent.com/28150424/93969564-00f49b00-fd21-11ea-969b-87fb7369364c.png)

**Update:**

If it helps, I did some digging in the source code and it seems that this css file is the offender. Please note I have tested this on a fresh copy of VSCode Insiders with nothing installed.

The purple style as shown in the image below should be the applied style, but due to a recent change, this is no longer the case. 

![image](https://user-images.githubusercontent.com/28150424/93970354-cf7ccf00-fd22-11ea-801d-22404bb70fa2.png)
![image](https://user-images.githubusercontent.com/28150424/93970381-dacffa80-fd22-11ea-9546-46056e0ae031.png)

**Comment by matthew-plusprogramming** [comment] 2020-09-23 05:29
If it helps, I did some digging in the source code and it seems that this css file is the offender. Please note I have tested this on a fresh copy of VSCode Insiders with nothing installed.

The purple style as shown in the image below should be the applied style, but due to a recent change, this is no longer the case. 

![image](https://user-images.githubusercontent.com/28150424/93970354-cf7ccf00-fd22-11ea-801d-22404bb70fa2.png)
![image](https://user-images.githubusercontent.com/28150424/93970381-dacffa80-fd22-11ea-9546-46056e0ae031.png)

**Comment by misolori** [comment] 2020-09-23 06:29
Thanks for the details, this is a duplicate of #107264 and should be fixed in the next insiders.

**Closed** 2020-09-23 06:30 UTC
Labels: *duplicate
