### ISSUE TITLE
KaTeX parse error: Multiple \tag

### ISSUE THREAD

**Issue by feiyang21282** [microsoft/vscode#168121] opened 2022-10-19 08:45 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

\begin{align}
a&=b+c \tag{2} \\\\
d+e&=f \tag{3}
\end{align}

the above markdown codes can be rendered by the new katex version in https://katex.org/ , please update the katex version embedded in vscode-jupyter.

### VS Code Version

1.70.2

### Jupyter Extension Version

v2022.8.1002431052

### Jupyter logs

```shell
KaTeX parse error: Multiple \tag
```

**Comment by mjbvz** [comment] 2022-12-06 01:53
Duplicate of #162379. Should already be fixed

**Comment by feiyang21282** [comment] 2022-12-06 01:53
你好，你的信件我已收到。

**Closed by mjbvz** 2022-12-06 01:53 UTC
