### ISSUE TITLE
 Cannot read property 'length' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43476] opened 2018-02-12 07:06 UTC
Issue Id: <b>aaeb9ebc-ea17-745b-7a5f-ca05e7e9ca94</b><br /><br />*Versions* <br />- 1.20.0<br />*Stack* <br />TypeError: Cannot read property 'length' of null<br />[/vs/editor/common/model/textModel.ts#L1321:23 (length)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/model/textModel.ts#L1321:23 (length))<br />[/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L849:40 (deltaDecorations)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L849:40 (deltaDecorations))<br />[/vs/editor/common/model/textModel.ts#L1331:12 (callback)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/model/textModel.ts#L1331:12 (callback))<br />[/vs/editor/common/model/textModel.ts#L1296:15 (_changeDecorations)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/model/textModel.ts#L1296:15 (_changeDecorations))<br />[/vs/editor/common/commonCodeEditor.ts#L824:20 (changeDecorations)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/commonCodeEditor.ts#L824:20 (changeDecorations))<br />[/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L848:15 (changeDecorations)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L848:15 (changeDecorations))<br />[/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L162:32 (render)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L162:32 (render))<br />[/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L601:23 (filterPreferences)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L601:23 (filterPreferences))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />

**Comment by alexandrudima** [comment] 2018-02-13 14:09
The root cause is in the `preferencesRenderer.ts` file, where we pass in `null` as an argument to `deltaDecorations`.

**Comment by sandy081** [comment] 2018-02-13 20:05
@alexandrudima It's very strange that I am never setting `deltaDecorations` to null. This gets assigned by [IModelDecorationsChangeAccessor](https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/model.ts#L190). This returns a string array. By any chance this can return null?

I am fixing from my side by assigning to an empty array always.

**Closed** 2018-02-13 20:05 UTC
Labels: error-telemetry, settings-editor

**Comment by alexandrudima** [comment] 2018-02-15 09:49
@sandy081 `deltaDecorations` always returns an array
