### ISSUE TITLE
Autocomplete after paste HTML code

### ISSUE THREAD

**Issue by vellkan** [microsoft/vscode#229613] opened 2024-09-24 19:48 UTC
Type: <b>Bug</b>

I found new and very bad feature in last update.
When I paste code like this:
```
<ul>
 <li>lorem</li>
</ul>
```
I've got:
```
<ul></ul>
 <li>lorem</li>
</ul>
```

With extra closing tag after open tag.
Auto closing copy/pasted code - but it shouldn't work like that.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (11.19GB free)|
|Process Argv|--crash-reporter-id 8f8813f8-406d-4b6d-9046-a6b8658281fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
cloudflare-devtools|Ale|1.0.4
vscode-intelephense-client|bme|1.12.6
bracket-select|chu|2.0.2
codeium|Cod|1.16.18
svg-gallery|dev|2.1.0
auto-rename-tag|for|0.1.10
randomeverything|hel|0.0.3
minifyall|jos|2.10.0
rainbow-csv|mec|3.12.0
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.10.0
sftp|Nat|1.16.3
color-highlight|nau|2.8.0
material-icon-theme|PKi|5.11.1
vscode-css-peek|pra|4.4.1
format-html-in-php|rif|1.7.0
sass-indented|syl|1.8.31
errorlens|use|3.20.0
vscode-css-variables|vun|2.7.1
wordpress-toolbox|wor|1.3.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-c:31125598
cf971741:31144450
fje88620:31121564
iacca1:31144502
notype1:31143045

```

</details>

**Comment by aeschli** [comment] 2024-09-26 08:51
duplicate of https://github.com/microsoft/vscode/issues/227859

**Closed by aeschli** 2024-09-26 08:51 UTC
