### ISSUE TITLE
Consistency with the use of "workspace" 

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#77718] opened 2019-07-21 15:55 UTC
### Problem

Developers [don't know](https://stackoverflow.com/questions/44629890/what-is-a-workspace-in-vs-code) what a [workspace is](https://www.reddit.com/r/vscode/comments/9z1b34/totally_confused_by_workspaces_and_folders_in/). Here's [my recent attempt to clear up the confusion](https://stackoverflow.com/a/57134632/4500152).

### Confusion

- The [recent list widget](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_opening-workspace-files) groups folder workspaces along with `.code-workspace` workspaces under a "workspace" heading, indicating that everything in that list is a workspace. Then it gives `.code-workspace` workspaces a "Workspace" suffix, contradicting the header, and indicating that only those workspaces that are associated with a `.code-workspace` file are true workspaces. 

- The first interaction with the term "workspace" for most developers is going to be the workspace settings. This is setting up users for confusion right off the bat. Because a folder's `.vscode` settings is initially referred to as "Workspace" settings. But when a `.code-workspace` file is created, `.vscode` settings becomes "Folder" settings, while the `.code-workspace` settings becomes the new "Workspace" settings.

- "Open Workspace" is referring to a `.code-workspace` workspace (with the dialog only allowing a `.code-workspace` file to be selected). Same goes for "Add Folder to Workspace..." and "Save Workspace As...".

- An extension's "Disable (Workspace)" option is referring to workspace as defined by my definition in the SO post.

### Suggestion
_**NOTE**: Suggestions will be updated as discussion in this thread evolves._

- In the recent list widget, create two separate headings: "Workspace" and "Folder". Remove suffixes.
- In settings editor, always refer to specific settings with the same reference. "Workspace" tab for `.code-workspace` settings. "Folder" tab for `.vscode` settings.
- "Open Workspace", "Add Folder to Workspace...", and "Save Workspace As..." remain unchanged.
- An extension's context menu will show "Disable (Workspace)" or "Disable (Folder)" depending on which is currently active.
- Optionally, come up with another term when wanting to reference both definitions. Whether it's "Project" or something else. Then it would be acceptable to use "Disable (Project)" in the extension's context menu, for example.

**Comment by bpasero** [comment] 2019-08-05 10:22
I think we have to be careful to call this "multi root workspace" because you can easily have just one (or actually no) folder in a workspace file. The use case is still that it allows you to store workspace settings for this folder without polluting the folder with a `.vscode` folder.

**Comment by jabacchetta** [comment] 2019-08-05 17:46
Yeah, naming this will be tough. Although I do think that consistency across the UI is more important than the naming itself.

What about referring to everything as "Projects", and then in the recent list widget, for example, changing the heading to "Projects", and giving those projects a suffix "Workspace" for `.code-workspace` files and "Folders" for single folder projects?

Same goes for the settings... "Workspace" and "Folder" settings, with "Folder" always being used to refer to settings that exist inside a `.vscode` folder and "Workspace" always being used to refer to settings that exist in a `.code-workspace` file (as opposed to changing the naming and creating confusion when a `.code-workspace` file is created).

And then when enabling/disabling extensions, "enable for this project".

**Comment by bpasero** [comment] 2019-08-05 18:22
But why would we introduce something new ("Project") that was never used in VSCode so far at all? I do not want to bring in the notion of projects because the next question will be, what kind of project systems we support etc.

**Comment by jabacchetta** [comment] 2019-08-05 18:44
Another option:

In the recent list widget, separate them out into two different headings: "Workspace" and "Folder", and remove suffixes all together.

Again, "Workspace" and "Folder tabs in the settings, with "Folder" always being used for settings coming from the `.vscode` folder.

For enabling/disabling extensions, I suppose it would need to be dynamic. "Enable for this workspace" when a workspace is opened, and "Enable for this folder" otherwise.

At this point, I'm starting to confuse myself, lol.

**Comment by bpasero** [comment] 2019-08-06 08:06
We decided to call both single folders and workspace file the "workspace" you are in. You could name the one "single-folder workspace" and the other "multi-root workspace", but then again, a multi-root workspace can have 0-1 roots too.

**Comment by jabacchetta** [comment] 2019-08-06 13:31
What about the UI inconsistencies mentioned above?

Will suffixes be removed in the recent list widget?

When opening a `code-workspace` file, what will settings tabs look like? Will what was once referred to as "workspace" settings become "folder" settings still?

What will "Open WorkSpace" menu item become? In other words, it wouldn't make sense to refer to both a single folder project with a `vscode` folder and a project that's associated with a `code-workspace` file as a WorkSpace, but then have an option for opening a workspace that only allows you to choose a `code-workspace` file.

**Comment by bpasero** [comment] 2019-08-06 14:23
"Open Workspace" and "Open Folder" are still there so that we can filter the dialog. With our custom dialog it would probably be possibly to be smarter here. 

I refer to @sandy081 for settings.

**Comment by jabacchetta** [comment] 2019-08-06 14:33
Yeah, I definitely understand the need to filter the dialog, but again, this is a UI inconsistency that is going to confuse users. At times, both are being referred to as a workspace. At other times, the UI is using the term workspace to refer only to projects associated with a `.code-workspace` file.

I think, looking through the forum posts that I linked to, it's clear that this has become a confusing issue. Even the answers to those questions are all over the map. And the UI inconsistencies are the biggest cause of this confusion.

**Comment by jabacchetta** [comment] 2019-08-10 15:46
Expanding on earlier suggestion:

- In the recent list widget, create two separate headings: "Workspace" and "Folder". Remove suffixes.
- In settings editor, always refer to specific settings with the same reference. "Workspace" tab for .code-workspace settings. "Folder" tab for .vscode settings.
- "Open Workspace", "Add Folder to Workspace...", and "Save Workspace As..." remain unchanged.
- An extension's context menu will show "Disable (Workspace)" or "Disable (Folder)" depending on which is currently active.

**Comment by sandy081** [comment] 2019-08-14 10:55
I agree it makes sense to call settings from a folder always Folder settings which makes it consistent across single folder and multi root folder workspace.

**Comment by andrecasal** [comment] 2019-10-08 19:20
I think it would make a lot of intuitive sense to explain that VS Code assumes that any opened folders are an **implicit workspace** and that we have the ability to create an **explicit workspace** as a `.code-workspace` file.

Something like this:
VS Code assumes any opened folders as an **implicit workspace** and settings for each root folder go inside each root's /.vscode folder. We can also create an **explicit workspace** as a `.code-workspace` file which can contain none or more root folders. An explicit workspace `.code-workspace` file without any root folders can be used to save custom settings, useful for remote development for example, or with multiple root folders where you might have a repository with your product's source code along with the product's documentation which you'd like to keep current. There is no advantage to an explicit workspace `.code-workspace` file with only one root folder over an implicit workspace that automatically reads settings from the  /.vscode folder, however.

I suggest we use **implicit workspace** and **explicit workspace** to differentiate between the two use-cases.

**Comment by nemchik** [comment] 2019-10-08 19:28
I wouldn't mind to see `Project Folders` added to `Workspaces` (where a workspace is the vscode workspace and a project folder gets added to your tree).

**Comment by edburns** [comment] 2019-10-12 17:45
I just submitted a PR to address the documentation side of this issue: https://github.com/microsoft/vscode-docs/pull/3154 . Please consider it.

**Comment by Spenhouet** [comment] 2020-04-07 13:25
_While reading the following, keep in mind that I write this to point out my confusion about VS codes "workspace" concept and the term they are using for it._

I just came across this since I opened our project (single folder project) as workspace and my extensions stopped working:

> This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.

That makes absolutely no sense to me.

Why is a single folder project not a workspace?

Why are extensions not working in a workspace?

If this "workspace" concept is so useless, then why is VS code trying to force users to save a workspace file for projects?

Every other IDE I worked with before had such a "workspace" file. But it was always referring to a single folder project. I intuitively expected that this is the same with the VS code workspace, but it is not. It only starts to make sense with [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

Could someone explain to me how such a multi-root workspace is meant to work? Given multiple different Git projects that should all use the same VS code settings, extensions and launch configs.. how to combine this. Does the multi-root workspace with settings get an independent Git repository? Don't forget that extensions stop working as soon as we start using a workspace...

What a confusing mess.
After googling the above warning message and figuring out what VS code refers to as "workspace", I was sitting here like "what are they doing".

**Comment by codeputer** [comment] 2020-04-07 20:38
Within DAPR,  I have a launch settings to be:
    "program": "${workspaceFolder}/bin/Debug/netcoreapp3.1/RoutingSample.dll",
but it cant' find the file....

So I'm in the weeds now trying to understand how {workspaceFolder} is derived - or at least allow me to view what it becomes... this statement actually fails, and I'm wondering how to change the work space directory as this statement isn't working, and it's part of a well established library.

**Comment by mburszley** [comment] 2020-05-26 15:05
@codeputer `${workspaceFolder}` resolves to the current open folder, unintuitively.  See #98424

**Comment by joe733** [comment] 2020-07-18 13:43
At UI level I've a suggestion:

![discord](https://www.maketecheasier.com/assets/uploads/2017/04/discord-running.jpg)

If folders could be switched like the servers in Discord (top tabs is also an alternative) I think it will be cool! A default workspace manages the root `.code-workspace` files.

**Comment by MarcosCalvi** [comment] 2020-09-06 08:09
Well, obviously there is a lot of confussion around the concept of Workspace

The only thing that would make sense to me is a workspace have its own launch configurations, git configurations and the opened files you are working on that workspace so you could have different independent projects in the same window. Switching the workspace in that window would switch the files you are viewing and the configurations you have available. It seems obvious, I don't understand all the confussion.

What do you think of that?

**Comment by tamuratak** [comment] 2020-09-08 01:12
Related to microsoft/vscode-docs/issues/3547

**Comment by AlbertoFabbri93** [comment] 2020-11-14 01:12
I agree that something should be done in order to clarify the difference between workspace settings and folder settings.

**Comment by bpasero** [comment] 2020-12-17 11:00
As a first step I pushed the following changes:
* Windows taskbar will refer to "folders" or "folders & workspaces"
* Recently opened picker will refer to "folders" or "folders & workspaces"

If you never had a workspace open, you will just see this as a result:

![image](https://user-images.githubusercontent.com/900690/102479428-2d3d6080-405f-11eb-984a-47b5ce48f273.png)

![image](https://user-images.githubusercontent.com/900690/102479470-3c241300-405f-11eb-9f07-65ddd9c601df.png)

There is still the question wether we should refer to "Folder" for setting related things or keep using "Workspace" even when a folder is opened. I think this needs a bit more discussion. While I find it easy to argue that the settings editor should talk about "Folder" and not "Workspace" when a folder is opened, I wonder if an action such as `Enable All Extensions for this Workspace` should really be renamed to `Enable All Extensions for this Folder` when you are in a folder.

**Comment by bpasero** [comment] 2020-12-18 08:25
After discussing this more in the team, we feel that simply changing "Workspace" to "Folder" everywhere in our UI depending on wether you have  folder or a workspace open is more confusing than helpful. For many users that don't care about multi-root workspaces or are simply new to VSCode and only feel comfortable opening folders, a folder really is their workspace. 

Also, we cannot control how extensions refer to the workspace depending on context: many extensions already use the term "workspace" for when the user has a folder opened and we would introduce more inconsistency if we changed it in the core of VSCode.

In retrospect, I think we should have probably called "multi root workspaces" in VSCode something different that is not "workspace". We discussed calling it "Project" but then were afraid people would expect VSCode to have a full blown project system (which it does not have). 

If there is still a very obvious issue with the use of "workspace" vs "folder", I am happy to fix that (e.g. as I outlined in https://github.com/microsoft/vscode/issues/77718#issuecomment-747369118). 

Next plan of action:
* review https://stackoverflow.com/questions/44629890/what-is-a-workspace-in-visual-studio-code
* review suggested doc update https://github.com/microsoft/vscode-docs/pull/3154
* add a topic to our docs trying to answer our concept of workspace

@jabacchetta as author of this issue, does that make sense?

**Comment by andrecasal** [comment] 2020-12-18 10:55
> In retrospect, I think we should have probably called "multi root workspaces" in VSCode something different that is not "workspace". We discussed calling it "Project" but then were afraid people would expect VSCode to have a full blown project system (which it does not have).

Making the best possible decisions based on past bad decisions is the path towards the descent to a bloated and poorly explained VS Code. I urge you to think from first principles and don't treat the symptom, but the cause. If, in retrospect, a "multi root workspace" should have been called something else, please call it something else - even if, for a few moments, users will be confused. This will be better for the future of VS Code.

**Comment by gjsjohnmurray** [comment] 2020-12-18 11:08
I too would like VS Code core and its documentation to use the term "workspace" **only** for the thing that gets loaded from a .code-workspace file. The File menu (on Windows at least) already distinguishes well between Folder and Workspace.

If a user (even a new one) opens a folder, then that's what they're working in - a folder. I don't see any benefit in encouraging them to think of a simple folder as something called a workspace. Reserve that term for what were originally called multi-root workspaces.

Yes, there'll be a bit of confusion / pain for some as the terminology evolves, and some extensions might fail to keep up with the change, but I think the end result will be a lot easier to understand for future generations.

**Comment by Spenhouet** [comment] 2020-12-18 11:11
> I think we should have probably called "multi root workspaces" in VSCode something different that is not "workspace".

@bpasero How about "multi root workspace"?

**Comment by bpasero** [comment] 2020-12-18 11:15
@andrecasal @gjsjohnmurray how do you suggest we fix all the extensions that are out there to call their user facing things "workspace" or "folder" depending on wether the user has opened a folder or a workspace? I think that will not be easily possible. If we change something in VSCode (either call it "Folder" or call workspaces "Projects"), we need extensions to update too, no?

@Spenhouet 

> @bpasero How about "multi root workspace"?

You can have a workspace file opened that has no folder in it, so in theory it is a 0-root workspace, as such "multi root" might be misleading.

**Comment by andrecasal** [comment] 2020-12-18 11:22
> @andrecasal @gjsjohnmurray how do you suggest we fix all the extensions that are out there to call their user facing things "workspace" or "folder" depending on wether the user has opened a folder or a workspace? I think that will not be easily possible. If we change something in VSCode (either call it "Folder" or call workspaces "Projects"), we need extensions to update too, no?

As developers of VS Code you should do your best to help extension developers, but it's not your responsibility to fix them. It's the other way around.

**Comment by bpasero** [comment] 2020-12-18 12:17
Our data shows that the majority of people use VSCode with folders and not with `.code-workspace`. So we can either make a change that impacts the majority of users (including new users that have not yet learned about `.code-workspace`) or make a change for the few "power" users that want to leverage `.code-workspace`.

What if we pushed for a change that only impacts the minority with the goal to make things clear. I.e. refer to `.code-workspace` workspaces with a different word (that can be a separate discussion) but preserve "Workspace" as the "thing" you open in VSCode. To give an example: imagine the file menu has "Open Folder" and "Open Xyz" and no matter what option you pick, both result in an experience where you have a "workspace" opened with "Workspace Settings" and "Workspace State". In the "folder" case all this state is associated with the ".vscode" folder inside and in the "Xyz" case the state is associated with the "Xyz configuration file". 

I feel that route would still resolve the confusion and has minimal impact to the majority of users and/or new users. I also feel that the term "Workspace" is an accepted term for something you work on in VSCode. Imho the confusion only started to emerge when we gave `.code-workspace` the name "Workspace" too.

**Comment by gjsjohnmurray** [comment] 2020-12-18 12:32
@bpasero in other words Folder and Xyz would both be types of Workspace. Yes, this makes sense to me. I think Project works. It's a sufficiently generic term to mean we can still push back if people start saying "but a VS Code Project should do A, B and C as well", with the response "that's not in scope for what we're calling a Project - it's a candidate for an extension".

**Comment by bersbersbers** [comment] 2020-12-18 12:37
@bpasero
> Imho the confusion only started to emerge when we gave `.code-workspace` the name "Workspace" too.

Personally, I can confirm this.

I also understand your objection to the "Multi-root workspace", and I can't stop think about calling the `.code-workspace` a "Workspace collection".

**Comment by bpasero** [comment] 2020-12-18 12:38
One thing to keep in mind is that the file extension `code-workspace` is something we can probably not change. So if we go with a word such as "Project" it would still be `xyz.code-workspace` files you open from the file system.

**Comment by pelumiojebode** [comment] 2020-12-18 12:45
Integrated workspace
I guess 📈

**Comment by andrecasal** [comment] 2020-12-18 21:53
I believe this problem has been dragging for so long because there isn't a clear definition of what the problem actually is. Allow me to try and shed some light.

[The current state of affairs is quite complicated](https://www.youtube.com/watch?v=5SX0756hvyQ). Most of the confusion around what a "Workspace" is has to do with the *type* and *scope* of settings.

Let's make a clear distinction between folder and instance. Folder is self-explanatory. Instance is *the running VS Code instance where a single folder is opened*.

The global settings.json file can contain all three user, instance and folder type settings.
A .code-workspace file can contain instance and folder type settings.
A /.vscode/settings.json file can contain instance and folder type settings.

For example, "workbench.colorCustomizations": {} make sense as an instance setting because I might want to change the title bar color to easily distinguish the running instance of VS Code where the client folder is opened from the running instance of VS Code where the server folder is opened.

So far so good.

The confusion begins when you transform a Single Folder Workspace into an Implicit Workspace ([see the video above](https://www.youtube.com/watch?v=5SX0756hvyQ)), which is essentially the same thing but where the instance type settings no longer apply. And you have to be incredibly careful to not transform a Single Folder Workspace into an Implicit Workspace. Remove the folder from the explorer and add it again? Boom, instance settings no longer apply. Add a second folder and remove it later? Boom, instance settings no longer apply. You still have a single folder in your workspace, but it's not a Single Folder Workspace anymore, it's an Implicit Workspace where instance type settings don't apply.

**Comment by bpasero** [comment] 2020-12-21 07:12
I think you don't have to explicitly distinguish `Implicit Workspace mode` and `Explicit Workspace mode`, for VSCode they are really the same. We call the former "Untitled Workspaces" (https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file) and they work like any other workspace you open from a `.code.workspace` file. The only difference is that we keep the `.code-workspace` file in the user data directory automatically created for you. When you change workspace settings you will edit them into that `.code-workspace` file. When you "Save Workspace As..." the contents of this file can be written to a location anywhere on disk, but you are really just copying that untitled workspace to a different place. When you close the window without saving the untitled workspace, we delete it.

I am not sure the term `Instance type settings` is accurate, because you can have an empty VSCode window with files opened where settings apply and these settings can only come from the global `settings.json` file. I think the name "Workspace Setting" is very accurate because these settings are active whenever you open a workspace. If that workspace is a "Folder", the settings are defined in `.vscode/settings.json` and when you open a `.code-workspace` these settings are defined in that file. 

Settings are more complicated than that actually, because individual settings can be `folder` or `language` overridable:
* `folder`: actual settings value is determined by the root folder (this only applies when a `.code-workspace` file is opened), for example `files.exclude`
* `language`: actual settings value is determined by the language mode of the file that is opened (e.g. all editor settings fall into this category)

**Comment by aisbergde** [comment] 2020-12-21 07:43
@bpasero it is very useful to read what you write here. And I never would know this if not subscribing to this topic. I can't find this in the VSC documentation, but I think it would be great to find it also there. Could you consider in the team to explain this also in the documentation? Maybe not all details, but users could get a better understanding about settings, folders, implicit and explicit workspace.

**Comment by bpasero** [comment] 2020-12-21 07:58
Yes I was planning to update our docs to make this clear.

**Comment by bpasero** [comment] 2021-02-01 06:18
We now have a document explaining the concept of workspaces in VS Code: https://code.visualstudio.com/docs/editor/workspaces

If there are no objections, I will go ahead and close this issue. We will link to that document throughout our documentation so that people can easily find it. If you have feedback on the topic, feel free to open a PR for this site at https://github.com/microsoft/vscode-docs/blob/master/docs/editor/workspaces.md

Thanks!

**Comment by edburns** [comment] 2021-02-01 18:01
Hello @bpasero thank you so much for this, and in particular for this text:

> Note: It is also possible to open VS Code without a workspace. For example, when you open a new VS Code window by selecting a file from your platform's File menu, you will not be inside a workspace. In this mode, some of VS Code's capabilities are reduced but you can still open text files and edit them.

This text will clear up so much confusion and improve the day one experience of old school Java developers used to IDEs. I am also working on a PR to help those old school folks even more.  I'll link it here.

**Comment by edburns** [comment] 2021-02-01 21:46
@bpasero Here is the promised [PR #4288](https://github.com/microsoft/vscode-docs/pull/4288).

**Closed** 2021-02-09 08:31 UTC
Labels: under-discussion, workbench-multiroot
