### ISSUE TITLE
API: Allow to use the file watcher for aribitrary folders

### ISSUE THREAD

**Issue by innerlee** [microsoft/vscode#3025] opened 2016-02-15 16:13 UTC
vscode 0.10.8, windows 10.

![animation](https://cloud.githubusercontent.com/assets/9464825/13053819/770be720-d441-11e5-92ea-7d9c3f2232da.gif)

like in the video, branch status updated only when clicking git panel.
if auto tracking is not possible, how about update status when clicking the sync button in the status bar?

**Comment by MystK** [comment] 2016-02-15 18:39
Hello. This is not a bug. It is not updating for you because you did not enter your Git credentials. After entering your git credentials, the branch automatically changes.

**Comment by innerlee** [comment] 2016-02-15 23:26
Hi @MystK, all operations are local. The credential error in the video is not my point, just a side effect of showing that, after pressing the sync button,  the local git status is still not updated. Before that, I pressed the "master" button, this interaction also did not update the status. Until at last, I opened the git panel, new branch finally shows.
So, I expect that, clicking the "master" button or the sync button will refresh status first and show the new created/deleted branch.

**Comment by MystK** [comment] 2016-02-15 23:37
Thanks for the clarification. My apologies. I've tried to reproduce your issue but cannot. I've clones your environment and steps but my branch still switches to the testing branch without having to click the Git panel.

**Comment by innerlee** [comment] 2016-02-15 23:50
@MystK, I just find that this happens only when using vscode open a subfolder of a git repository. working on the repository root folder works normal.

**Comment by joaomoreno** [comment] 2016-02-16 07:53
This is

**Comment by felixfbecker** [comment] 2016-02-21 10:34
It works for me, it just takes a while...

**Comment by rhires** [comment] 2016-02-21 13:13
Actually...it used to track, but it doesn't anymore. That's what I'm seeing on Windows7 anyway with the latest update.

**Comment by bpasero** [comment] 2016-02-29 13:40
@joaomoreno thats a tough one, would you want explicit API to listen to a .git folder in the parent chain? I think if git does not find a .git folder to listen on, it should fallback to some polling mechanism instead.

**Comment by joaomoreno** [comment] 2016-03-22 12:23
Well ideally any contribution in Code should be able to tell the filesystem events contribution *hey, I wanna listen to all file change events at this given `root`*. The watcher should then accommodate that request.

Moving this to feature request and renaming title.

**Comment by joaomoreno** [comment] 2018-03-19 09:33
@jrieken @bpasero The duplicate number has reached my annoyance level. I will propose an arbitrary FS watching API.

**Comment by bpasero** [comment] 2018-03-19 09:46
@joaomoreno I think the API is not a problem, but the implementation. I would only do that once we switch to a common watcher for all platforms and all states (single-root vs multi-root). Doing this on top of our current watchers is throw-away code.

**Comment by joaomoreno** [comment] 2018-03-19 15:06
@bpasero Then you're forcing me to bring yet another watcher library within my git extension, or moving back to the Node API.

**Comment by bpasero** [comment] 2018-03-19 16:18
@joaomoreno yup that sounds about right

**Comment by eamodio** [comment] 2018-05-30 06:03
Just got bitten by this hard (failed to notice the note in the docs that say this only works within a workspace folder). I would also love to have an api that can watch an arbitrary path.

**Comment by joaomoreno** [comment] 2018-07-06 06:42
@bpasero I keep getting bitten by this too... any chance we can get this?

**Comment by bpasero** [comment] 2018-07-06 12:38
@joaomoreno man... I got desktop to setup!

**Comment by joaomoreno** [comment] 2018-08-21 07:52
@bpasero I get 3 issues per week related to this.

**Comment by joaomoreno** [comment] 2018-09-18 15:52
Here's the git issue: #41085

**Comment by eamodio** [comment] 2018-12-22 17:34
Any movement on this? I'm getting GitLens issues filed against this as well.

**Comment by joaomoreno** [comment] 2019-03-06 10:10
@bpasero 

![image](https://user-images.githubusercontent.com/900690/49581792-61032d00-f953-11e8-80ee-0fba2d35df2e.png)

**Comment by bpasero** [comment] 2019-03-07 15:21
Best I can do is move it to "On Deck" for now, meaning that it is definitely on my radar (or the teams radar). I see three possible solutions:

**Do nothing**
An extension can use the node.js API to install watchers on directories, so there is nothing that prevents them from installing file watchers on their own for directories that are outside the workspace. The related method is [`fs.watch`](https://nodejs.org/docs/v10.2.0/api/fs.html#fs_fs_watch_filename_options_listener). One could argue that we should not provide API for functionality already provided by node.js itself.

**Do the minimal thing**
Today we have 3 different watcher strategies:
* Multi Root Workspace: nsfw
* Single Folder Windows: C# solution
* Single Folder Mac/Linux: Chokidar

The C# solution does not allow to watch additional folders, while I believe Chokidar does. We could simply enable the Chokidar watcher option only for extensions that want to watch additional folders. We could even only let these events travel to extensions and not the VSCode core. Still, we should probably spawn a separate process to not put too much pressure on the extension host.

**Do the right thing**
This involves ditching all the current file watching strategies and come up with a single new one that is suitable for all cases, especially suitable to watch any number of paths in a smart way (e.g. by not watching the same folder when it is already being watched). Of course this option comes with most risks and work but also most benefits, considering all the other file watching issues we have.

**Comment by Tiedye** [comment] 2019-06-22 23:50
Is this on the radar still?  It been quite a while waiting for this to get addressed.  It feels like a big gap in an otherwise super polished application.

**Comment by linonetwo** [comment] 2020-01-27 06:37
This PR can fix https://github.com/microsoft/vscode/issues/41085 and https://github.com/microsoft/vscode/issues/41085

**Comment by karrtikr** [comment] 2020-10-20 22:29
Is https://github.com/microsoft/vscode/issues/100870 a dup of this?

**Comment by Andy-AO** [comment] 2021-04-01 10:22
It is inconceivable that this problem, which was identified in 2016, is still unresolved.

If the underlying assumptions were wrong in the first place, changes in the software design may not be so easy.

I've gotten used to hitting the refresh button by now.

**Comment by Andy-AO** [comment] 2021-04-01 10:29
Maybe a weaker solution can be provided for the time being: that is, for Explorer to be updated when a file is opened in Explorer but found not to exist.

Anyway, I often encounter this situation, the external file has been updated, but as a result, there is no update in Explorer, and when I open it, it will show open failure, and then I go to refresh it manually.

**Comment by jakebailey** [comment] 2021-04-28 00:07
I'm currently pulling my hair out trying to get a decent file watcher to work to detect Python package installs. VS Code has largely figured out all of the different edge cases and rationale for when to use various file watchers; it'd be extremely helpful if I could just piggy back on this (over LSP, I hope) similarly to the rest of the watch calls, rather than attempt to reimplement all of it in Node (which poses its own challenges thanks to compiled components and the lack of platform specific extensions).

**Comment by bpasero** [comment] 2022-01-05 16:44
PR is up at https://github.com/microsoft/vscode/pull/139881

@joaomoreno just to clarify, the need from the Git extension is to be able to watch some files inside the `.git` folder for changes? Is that a recursive watcher need or just flat?

**Comment by eamodio** [comment] 2022-01-05 19:24
For GitLens (and I'm pretty sure the Git extensions needs) it would need to be recursive, so that we can watch for specific changes within the `.git` folder.

Here are the watcher patterns GitLens uses today:
https://github.com/gitkraken/vscode-gitlens/blob/76e9abdceb70632bc4472aacb347bc4e994e742f/src/git/models/repository.ts#L243-L258

**Comment by Jolg42** [comment] 2022-01-05 20:16
For Prisma's extension we are currently using chokidar and it's recursive
https://github.com/prisma/language-tools/blob/main/packages/vscode/src/plugins/prisma-language-server/index.ts#L65-L82

**Comment by bpasero** [comment] 2022-01-06 07:13
I just looked at the Git extension and it does not require recursive watching:

https://github.com/microsoft/vscode/blob/a6177d979a45c63764275b4d1028de8a451d0025/extensions/git/src/watch.ts#L16

The patterns from GitLens seem fine to me and would work with what I am building in the PR.

@Jolg42 you seem to be listening to changes just to a single file but you need to scan any `node_modules` folder within the workspace, not just top level, is that right?

**Comment by Jolg42** [comment] 2022-01-06 07:29
@bpasero The most common use case would be indeed watching 1 file that could be in any `node_modules` folder. It might also be that we watch 2 files in 2 different `node_modules` folders.

**Comment by karrtikr** [comment] 2022-01-06 12:12
For Python extension, we currently use chokidar to watch for python binaries in environment folders outside workspace upto depth 2: https://github.com/microsoft/vscode-python/blob/456ac068e95ba600079ddcdc0cc7551d1659a699/src/client/common/platform/fileSystemWatcher.ts#L57-L81

Common patterns we watch for: [link](https://github.com/microsoft/vscode-python/blob/456ac068e95ba600079ddcdc0cc7551d1659a699/src/client/pythonEnvironments/common/pythonBinariesWatcher.ts#L61-L66)

**Comment by karrtikr** [comment] 2022-01-06 12:13
Just FYI for Python extension, we currently use chokidar to watch for python binaries in environment folders outside workspace upto depth 2: https://github.com/microsoft/vscode-python/blob/456ac068e95ba600079ddcdc0cc7551d1659a699/src/client/common/platform/fileSystemWatcher.ts#L57-L81

Common patterns we watch for: [link](https://github.com/microsoft/vscode-python/blob/456ac068e95ba600079ddcdc0cc7551d1659a699/src/client/pythonEnvironments/common/pythonBinariesWatcher.ts#L61-L66)

**Comment by bpasero** [comment] 2022-01-07 09:00
Thanks for providing examples, just to clarify what https://github.com/microsoft/vscode/pull/139881 will allow you to do: `vscode.workspace.createFileSystemWatcher` always allowed you to pass in a `Uri` via `RelativePattern`, i.e.:

```ts
createFileSystemWatcher(new vscode.RelativePattern(vscode.Uri.file('<some folder path>'), '*.js'))
```

Previously we would silently ignore a provided path that is outside the workspace. After my change, paths will be watched, even when they are outside the workspace with 2 different strategies depending on the pattern used:
* recursive when you provide a complex glob pattern (e.g. `**/*.js`) via [`parcel-bundler/watcher`](https://github.com/parcel-bundler/watcher)
* flat when you provide a simple pattern (e.g. `*.js`) via [`fs.watch`](https://nodejs.org/docs/v14.16.0/api/fs.html#fs_fs_watch_filename_options_listener)

However, when it comes to how to handle excludes, I am still not sure what to do so that extensions can efficiently use this new behaviour for file watching. To clarify: a user setting `files.watcherExclude` allows a user to configure glob patterns that will filter file events. The original idea behind this was to give the user a way to reduce CPU load when a workspace contains large folders that are known to change a lot but should be ignored for watching (such as node modules folder or any build output folder). By default we configure this setting to be:

```json
	"files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/.git/subtree-cache/**": true,
		"**/node_modules/*/**": true,
		"**/.hg/store/**": true
	}
```

Besides performance considerations, this setting is also required on Linux to reduce the number of opened file handles the watcher consumes. Unfortunately on Linux, recursive watching requires 1 file handle per folder in the hierarchy and only with these exclude rules are we able to reduce this overhead.

To be consistent, this setting needs to apply for extension watched paths as well, otherwise a user would not be in control anymore how file watching works. Given we have 2 different watch strategies, I am thinking:
* for recursively watched folders, apply excludes
* for non-recursive folders, do not apply excludes

The downside of this approach is that currently an extension cannot indicate the excludes to use, nor overwrite the default excludes we apply. This probably needs a new overload of the `createFileSystemWatcher` method to provide them (similar to `findFiles` method that has a `exclude?: GlobPattern | null` parameter).

However, even if we were to provide extensions with a way to override excludes, you would still not be able to watch the `node_modules` folder within a workspace. The reason for that is that we setup recursive watchers for all workspace folders right on startup and we don't allow extensions to add additional watchers for the workspace, because that would result in multiple watchers on the same paths competing against each other.

Open for thoughts and ideas how to proceed. My feeling is that my PR makes git extensions happy because watchers can be installed on git repositories outside the opened workspace. However those extensions that need to watch in a location that is excluded by default (i.e. `node_modules`) will have a harder time to use this for their needs I believe...

**Comment by eamodio** [comment] 2022-01-12 20:55
@bpasero will this be landing in the January release and available for extensions or will it have to be proposed first? I'm hoping and assuming the former as I didn't see any proposed `d.ts` changes in the PR. I'm hoping to get my hands on this ASAP as the Git Worktrees feature shipping soon in GitLens kind of requires this (which I've recently come to realize) for many setups. 

Say if you have a repo in:
`/code/project/repo`

By default, I will put worktrees in: (though this is still TBD)
`/code/project/repo/.git/.worktrees/<branch-name>`
And if you then open that folder, the real `.git` folder will be a parent of the workspace folder. 

Alternatively, a user can pick a different folder (often I've seen people create worktree folders as peer's to the main):
`/code/project/repo.<branch-name>` or something like that

Which again would suffer the same problem since again the real `.git` folder will be outside the workspace folder.

Thanks!

**Comment by bpasero** [comment] 2022-01-13 05:44
This is planned to be available in our upcoming January release without the need of proposed API. As I had indicated before, an extension can watch any path that is not within the opened workspace folder hierarchy. For non-recursive watchers, no excludes will apply, but for recursive watchers, the same excludes apply that apply for workspace folder watching.

**Closed** 2022-01-13 12:32 UTC
Labels: feature-request, api, file-watcher, api-proposal

**Comment by bpasero** [comment] 2022-03-30 08:39
Small update for a change I pushed for https://github.com/microsoft/vscode/issues/146066: with this change you can now create a file system watcher that is watching inside the workspace and the `files.watcherExclude` setting will not apply to you if the watcher is non-recursive. 

In other words: this enables you to watch a folder or file and be 100% sure that file events get delivered to you even if the user has configured exclude rules (or when our default exclude rules would impact the results).

This does not apply for recursive watching though because the exclude rules are there for a reason, to reduce overhead for recursive watching.

**Comment by bpasero** [comment] 2023-10-12 04:22
Another update: with https://github.com/microsoft/vscode/pull/194776 there is now proposed new API for `createFileSystemWatcher` that enables an extension to fully control file watching both recursive and flat bypassing any of the VS Code configured exclude rules.

With that change, file events are exclusively routed back to the extension making the request, thus reducing the performance overhead. No component in VS Code core and no other extension will receive these file events.

The only requirement for this to work is that you have to provide a set of glob patterns to `exclude` yourself. If no exclude rules are provided, we resort back to the old behaviour where in-workspace recursive watching is blocked.

https://github.com/microsoft/vscode/blob/895a9ff13055ddb528d0a4d34f36b6f6e3059b31/src/vscode-dts/vscode.proposed.createFileSystemWatcher.d.ts#L10-L37
