### ISSUE TITLE
[1.12.1] editor.acceptSuggestionOnCommitCharacter not being respected

### ISSUE THREAD

**Issue by scriptorum** [Microsoft/vscode#26569] opened 2017-05-12 19:20 UTC
I'm working in C#. I like suggestions, but I never want Code to accept them without my explicit say so, such as the tab key.  So I turned off `acceptSuggestionOnCommitCharacter` in my settings.json file:

![image](https://cloud.githubusercontent.com/assets/3144427/26013076/cdc6a77a-3724-11e7-9131-ab0cea33a3f2.png)

But it still accepts the suggestion when I press `.` or `)`.

![vscode-issue](https://cloud.githubusercontent.com/assets/3144427/26013407/388c2f84-3726-11e7-92cf-b463a92de406.gif)

Am I misusing this setting?

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-glacier|Kal|0.0.1|
|uncrustify|LaurentTreguier|1.5.1|
|magoon|Northerntwig|1.1.0|
|theme-darktooth|Poorchop|0.0.2|
|unity-debug|Unity|1.1.0|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|Theme-Monokai-Easylight|davidbabel|1.0.0|
|vs-code-xml-format|fabianlauer|0.1.5|
|Theme-Amy|gerane|0.0.2|
|Theme-Bliss|gerane|0.0.2|
|Theme-Brunette|gerane|0.0.4|
|Theme-Colonoscopy|gerane|0.0.2|
|Theme-Earthsong|gerane|0.0.2|
|Theme-FlatlandDark|gerane|0.0.2|
|Theme-Hail|gerane|0.0.3|
|Theme-monokai-inverse|gerane|0.0.2|
|theme-dusk|gllwy|0.0.7|
|theme-dark-starry-night|jerry|1.0.2|
|theme-onedark-sublime|joshpeng|0.3.6|
|FlatUI|lkytal|1.2.1|
|theme-chester|marcuskaz|0.1.1|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|theme-whitehat|nisimiko|1.22.6|
|mac-classic-theme|nkjoep|0.0.1|
|theme-oceandeep|pierrenel|0.0.1|
|ClassyNaming|reflectiondm|1.0.0|
|vscode-format|ryannaddy|0.0.6|
|sblight|sbovyrin|2.1.1|
|dark-plus-material|vangware|1.0.0|
|gitflow|vector-of-bool|1.1.0|
|agila-theme|whtsky|2.0.1|;

---

Steps to Reproduce:

1. Turn off acceptSuggestionOnCommitCharacter
1. Type an identifier
1. Use . or ) to IGNORE the suggestion
1. Witness the suggestion being all like I'll do what I want you're not the boss of me

**Comment by jrieken** [comment] 2017-05-15 07:56
@scriptorum Can you check if you have a keybinding for `.` or `)` that is specific to C# and accepting a completion? Accept on commit used to be "implemented" with a keybinding

**Comment by scriptorum** [comment] 2017-05-15 17:47
I see a binding to "." under Keyboard Shortcuts:
![image](https://cloud.githubusercontent.com/assets/3144427/26071019/ae97f56e-3974-11e7-85be-a0b83dabac94.png)
If I remove it then `.` no longer accepts suggestions. One down. 

As for the closing paren, I don't see `)` in Keyboard Shortcuts. Where would I find language-specific bindings?

**Comment by jrieken** [comment] 2017-05-16 07:57
> Where would I find language-specific bindings?

To right of this there should be a column `when` listing more information about this

**Comment by scriptorum** [comment] 2017-05-17 00:21
There it is.  Filed under &#8679;0 / &#8679;9 instead of `.`/`)`.

![image](https://cloud.githubusercontent.com/assets/3144427/26133128/f711cfc8-3a72-11e7-82c6-ec18212f8b84.png)

Removing these shortcuts restored the desired behavior. Thanks @jrieken!

**Comment by jrieken** [comment] 2017-05-17 06:57
Thanks. I will follow up with the csharp-folks to use our improved story

**Comment by jrieken** [comment] 2017-05-17 07:05
the issue on the omnisharp side: https://github.com/OmniSharp/omnisharp-vscode/issues/1487. closing this as a dupe of that one now

**Closed by jrieken** 2017-05-17 07:05 UTC
Labels: needs more info, suggest
