### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'activateByEvent' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#47554] opened 2018-04-10 05:50 UTC
Issue Id: <b>619968c2-ea7b-3baf-3336-a087bbee098f</b><br /><br />*Versions* <br />- 1.22.1<br />-  762a3f68106d03a6d033dfd7a28ae8dee5977842<br />*Stack* <br />TypeError: Cannot read property 'activateByEvent' of null<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#423:43 (_activateByEvent)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L423:43 (_activateByEvent))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#411:15 (activateByEvent)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L411:15 (activateByEvent))<br />[/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#608:31 (openConfigFile)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L608:31 (openConfigFile))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#114:59 (run)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/debug/browser/debugActions.ts#L114:59 (run))<br />[/vs/base/common/actions.ts#226:31 (runAction)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/actions.ts#L226:31 (runAction))<br />[/vs/base/common/actions.ts#218:14 (run)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/actions.ts#L218:14 (run))<br />[/vs/base/browser/ui/actionbar/actionbar.ts#163:21 (onClick)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/browser/ui/actionbar/actionbar.ts#L163:21 (onClick))<br />[/vs/base/browser/ui/actionbar/actionbar.ts#142:28](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/browser/ui/actionbar/actionbar.ts#L142:28)<br />    at runCallback (timers.js:672:20)<br />    at tryOnImmediate (timers.js:645:5)<br />    at processImmediate [as _immediateCallback] (timers.js:617:5)<br />

**Comment by alexandrudima** [comment] 2018-04-17 20:43
Duplicate of #48065

**Closed by alexandrudima** 2018-04-17 20:43 UTC
Labels: error-telemetry
