### ISSUE TITLE
Strange mess in the title bar

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#96048] opened 2020-04-24 09:32 UTC
```
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
**Describe the Bug**
With the window open and the terminal maximizing, you can see strange mess in title bar
I catch it while i using [Git Graph addon](https://github.com/mhutchie/vscode-git-graph) but Git Graph support said: _this is a Visual Studio Code bug_. More info: https://github.com/mhutchie/vscode-git-graph/issues/300

**Steps to Reproduce:**

### Video GIF:
![git](https://user-images.githubusercontent.com/30685349/80195429-1a7fa280-861c-11ea-8fba-d9f6f830e897.gif)

### Screen:
![obraz](https://user-images.githubusercontent.com/30685349/80195467-28352800-861c-11ea-8295-b34c4837c942.png)

**Comment by mjbvz** [comment] 2020-04-24 18:30
Duplicate of #94805

Should be fixed in the current insiders build

**Closed by mjbvz** 2020-04-24 18:30 UTC
