### ISSUE TITLE
Incorrect selection

### ISSUE THREAD

**Issue by aleksandrkolesnikov** [microsoft/vscode#74131] opened 2019-05-22 12:28 UTC
![aaa](https://user-images.githubusercontent.com/7703104/58174140-d49cba80-7ca5-11e9-914a-3db77cab9e70.png)
Issue Type: <b>Bug</b>

I have wxs file with many rows (about 7000). There are many similar strings in these rows. When I select part of string it highlight, but not always.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vsc-material-theme|Equ|2.8.2
CppSnippets|har|0.0.14
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
rust|rus|0.6.1

</details>

**Comment by rebornix** [comment] 2019-07-29 23:51
/duplicate of https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aissue+is%3Aopen+find+results+limit we do have a limit of find/word results highlight.

**Closed** 2019-07-29 23:51 UTC
Labels: *duplicate
