### ISSUE TITLE
Vs Code update caused workspace to dissapear

### ISSUE THREAD

**Issue by sitoprvt** [microsoft/vscode#78037] opened 2019-07-27 11:14 UTC
Issue Type: <b>Bug</b>

1. Vs Code automatically updated to the latest version
2. Vs Code opened with a blank workspace
3. Old workspace is completely gone. Can't even find it on my hard drive anymore.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-8320E Eight-Core Processor               (8 x 3222)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (4.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
very-smart-select|clo|0.3.0
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.0
macros|ged|1.2.1
python|ms-|2019.6.24221
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.1
guides|spy|0.9.3

(1 theme extensions excluded)

</details>

**Comment by sitoprvt** [comment] 2019-07-27 11:31
Managed to find some backup information of the workspace in roaming appdata of Vs Code. It says the exact folder where my project (cencored red) was before the update. It does no longer exist now and also is nowhere to find in my recycling bin.

![workspace](https://user-images.githubusercontent.com/49991315/61993874-ad31e780-b072-11e9-998b-c936b1faa88b.png)

**Comment by bpasero** [comment] 2019-08-05 10:45
@sitoprvt that is unfortunate, sorry. But should never store workspaces within the installation directory of VSCode as that directory gets deleted when updating.

//cc @joaomoreno 

Duplicate of https://github.com/microsoft/vscode/issues/76567

**Closed by bpasero** 2019-08-05 10:45 UTC
