### ISSUE TITLE
Unable to close context menu without selecting option

### ISSUE THREAD

**Issue by prryplatypus** [microsoft/vscode#137785] opened 2021-11-24 09:46 UTC
Issue Type: <b>Bug</b>

Steps to repro:
- Open VSCode.
- Open a file/editor.
- Right click on the editor.
- Click outside the context menu that opens or press "ESC".

Expected result: Context menu closes without the need to select an option.

Actual result: Context menu won't close unless you select an option in it.

VS Code version: Code - Insiders 1.63.0-insider (c1f2f40bcd81380bf2e286af64becddada57db88, 2021-11-24T05:33:22.438Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (1.90GB free)|
|Process Argv|--crash-reporter-id 91bb054b-efd3-421a-9ebd-7db9e5ea928c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt3:30397560
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by stagefright5** [comment] 2021-11-24 10:23
For now, I found a workaround.

Press escape when your mouse pointer is on (hover) the context menu

**Comment by hediet** [comment] 2021-11-24 12:24
*From @jrieken:*

This must have regressed with our change here https://github.com/microsoft/vscode/commit/9bd899fabad214ad2385cc2a252a5deb581049e3

I can reproduce with the following steps

* microsoft/vscode in env with custom menus, like web bits or windows
* open `src/vs/base/common/arrays.ts`
* right-click the `arrays.ts` in the explorer, select "Select for Compare"
* right-click into the editor to open its context menu
* click into the editor area
* 🐛 the editor context menu stays, the explorer gained focus

I don't know what's going on but I cannot reproduce when I revert the changes to the focus tracker

**Comment by alexdima** [comment] 2021-11-24 12:44
Fixed via https://github.com/microsoft/vscode/commit/bb7a76bf2b4149d61465de63d94c8a9668bd4135

**Closed by alexdima** 2021-11-24 12:44 UTC
Labels: bug, important, regression
