### ISSUE TITLE
Can't file a bug report with text containing ```

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode#97171] opened 2020-05-07 18:52 UTC
- VSCode Version: 1.44.2
- OS Version: 10.0.19041

Steps to Reproduce:

1. Try and submit this bug report:
![image](https://user-images.githubusercontent.com/18707114/81333119-f29b3080-9058-11ea-83a9-be6b3d2c1269.png)

2. you get this confusing error:
![image](https://user-images.githubusercontent.com/18707114/81333139-faf36b80-9058-11ea-8450-5116f398ba15.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2020-05-07 19:02
Hey @lovettchris, sorry for the confusing error message! Would love any feedback on how to make this message clearer.

When we go to create a new issue, since VSCode doesn't have any authentication details about your GitHub account, we open the issues/new page instead of directly creating an issue. When we open this page, the title and body of the issue are prefilled from a query string in the url. Because of browser url length limits, we sometimes aren't able to open the url if there is too much in the title and body. The data from "enabled extensions" alone can sometimes go over the limit. So, instead we want to still open the page, but copy the data to the clipboard so that you can paste it into the body field.

We've been working on an authenticating to GitHub from VSCode, so in the future it should be possible to avoid this by just directly creating the issue using your account

**Comment by lovettchris** [comment] 2020-05-07 19:16
then the entire form is a lie :-) If you can't sort out the authentication problem then you'd be better off sending me to github much sooner instead of making me fill out this form only to find it was a useless exercise...

**Comment by RMacfarlane** [comment] 2020-05-07 19:25
No need to be rude, if you clicked "OK" on the dialog in the screenshot above, you could paste the information into the issue. The form still serves a purpose of collecting other diagnostic information to send to GitHub, which we would have the same length limitation issues regardless of when we open github

**Comment by RMacfarlane** [comment] 2020-05-07 19:31
There's another feature request open to have a command that just copies this diagnostic info to the clipboard, so with that you could avoid the issue reporter altogether. Will find that issue reference in a bit

**Comment by lovettchris** [comment] 2020-05-07 19:48
Sorry didn't mean to sound rude - see the smiley face...   But anyway, just giving you my user impression having gone down this UX rabbit hole.  Do with it as you like :-)

**Comment by RMacfarlane** [comment] 2020-05-08 00:29
I hadn't eaten lunch when I responded earlier, so maybe I took offense too easily out of hunger 😄 Anyway, thank you for the feedback!

Here's the issue about having a command to file an issue: https://github.com/microsoft/vscode/issues/91108

I'm going to close this as a duplicate of https://github.com/microsoft/vscode/issues/95165, since that tracks using authentication to directly create the issue, which will fix this

**Closed by RMacfarlane** 2020-05-08 00:29 UTC
