### ISSUE TITLE
Allow users to customize which side the panel appears on

### ISSUE THREAD

**Issue by valleybay** [Microsoft/vscode#47132] opened 2018-04-03 10:40 UTC
**Feature Request**
Allow the user to customize which side the panel appears on. This aligns well with the fact that you can pick which side the sidebar appears on. If I choose to have the sidebar on the right, it stacks up with the panel.

**Comment by usernamehw** [comment] 2018-04-03 14:42
Duplicate of #37877

**Closed** 2018-04-04 07:17 UTC
Labels: workbench-layout
