### ISSUE TITLE
Error with identation after copy-pasting

### ISSUE THREAD

**Issue by DMoreira97** [microsoft/vscode#62900] opened 2018-11-10 19:56 UTC
Hello,

While working in html I found an error with the indentation. After doing the process described in 'Steps to Reproduce' the indentation of the text pasted is all wrong. Usually vscode adds an extra tab to the first line, and adds two more tabs to all the other lines.

Steps to Reproduce:
1. Open an html document (with code on it)
2. Select an entire tag
3. Copy it.
4. Paste it inside any other tag.

![imagem](https://user-images.githubusercontent.com/27859403/48305364-2b6c4f00-e521-11e8-9e7b-1ee4f5f6ebc6.png)
![imagem](https://user-images.githubusercontent.com/27859403/48305376-43dc6980-e521-11e8-9f35-3740f00ca777.png)
![imagem](https://user-images.githubusercontent.com/27859403/48305380-548cdf80-e521-11e8-9588-881a175a8240.png)

I would like to solve this bug myself. I am posting it here to see if it really is a bug, and to see if you can help me and tell me where to start.

This issue is similar to this [one](https://github.com/Microsoft/vscode/issues/56826). But this one is written in Portuguese (Br), so it hasn't had any activity. And the indentation of the text pasted is also different.

- VSCode Version: 1.28.2
- OS Version: Windows 10 Home 64 bits

**Comment by glen-84** [comment] 2019-03-23 14:39
Duplicate of #32320. (?)

**Closed** 2019-08-02 19:46 UTC
Labels: *duplicate, editor-autoindent
