### ISSUE TITLE
Notification button goes out of dom when progress changes

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#91682] opened 2020-02-27 12:17 UTC
When verifying https://github.com/microsoft/vscode/issues/91469#issuecomment-591934688, there was once that I clicked the `Cancel` button and nothing happened. I was able to reliably reproduce by holding mouse down, waiting for progress to change and releasing the mouse button.

**Comment by bpasero** [comment] 2020-02-27 13:01
This is because I call List#splice() whenever I update progress. I could not figure out a better way how to directly update progress within a list item as far as I remember. 

/duplicate of https://github.com/microsoft/vscode/issues/50931

**Closed** 2020-02-27 13:01 UTC
Labels: *duplicate

**Comment by bpasero** [comment] 2020-02-27 13:06
I remember why: if you update the message text, the height might change due to wrapping. As such I splice the notification, but maybe there is now a better way with newer API?

Code: https://github.com/microsoft/vscode/blob/4f232ba78f3d7dc673fc2f5bbd041cf990987b67/src/vs/workbench/browser/parts/notifications/notificationsToasts.ts#L211

**Comment by joaomoreno** [comment] 2020-02-27 13:39
@bpasero Actually [this](https://github.com/microsoft/vscode/pull/91594/files#diff-bc80460db7fa6e585859804d50b57039R282) would be exactly what you could use! cc @rebornix

**Comment by bpasero** [comment] 2020-02-27 13:50
@joaomoreno oh nice, will wait for that to land then.
