### ISSUE TITLE
Extensions not loaded when VS code started from admin user in standard user session

### ISSUE THREAD

**Issue by utw4376** [microsoft/vscode#102686] opened 2020-07-16 09:15 UTC
I am using a standard user (ad\MyUser) on W10 x64 Enterprise Eng. When i want to run VS Code as admin I start it as admin user (ad\MyAdm) from the standard user session ("Run as administrator"). Since the update to 1.47.1 this no longer works. The powershell session (neither PS7.0.2 nor Windows Powershell) does not start.

When logging on as MyAdm and then starting VS Code elevated everything works as expected.

The error log is in:
[error.txt](https://github.com/microsoft/vscode/files/4930511/error.txt)

**Comment by andriktr** [comment] 2020-07-16 11:10
+1

**Comment by utw4376** [comment] 2020-07-17 07:09
I can confirm that the issue still exists in 1.47.2

**Comment by andriktr** [comment] 2020-07-17 07:10
Same for me

**Comment by sandy081** [comment] 2020-07-17 09:07
Can you please check if you have any errors in the developer tools console?

- please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Open View… -> Log (Window)

- Are you able to open extensions view and see extensions?
- Please run the command `Developer - Show Running Extensions` and let us know what do you see

**Comment by utw4376** [comment] 2020-07-17 09:29
>   * Help -> Toggle Developer Tools -> Console
Nothing happens. Developer tools do not start.

>   * View -> Open View… -> Log (Window)
Problems: No problems have been detected so far.
Output:  <empty>
Debug Console: <empty>
Terminal: PowerShell 7.0.3... 

> * Are you able to open extensions view and see extensions?
Yes. Both extensions are shown as "Enabled"

> * Please run the command `Developer - Show Running Extensions` and let us know what do you see
Node Debug Auto-attach 1.0.0
Emmet 1.0.0
Git 1.0.0
GitHub 0.0.1
GitHub Authentication 0.0.1
Merge Conflict 1.0.0
Microsoft Account 0.0.1
Search Result 1.0.0

**Comment by sandy081** [comment] 2020-07-17 09:38
Can you please disable `vscode-icons-team.vscode-icons` extension, reload window and try?

**Comment by andriktr** [comment] 2020-07-17 10:45
In my case developer tools shows the following errors for all extensions: 
```
Activating extension 'ms-vscode.azure-account' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4279
```
I also have tried to completely remove  vscode-icons-team.vscode-icons however result remain the same. 

When I run the 'View -> Open View… -> Log (Window)' the output is: 
```
[2020-07-16 14:44:13.409] [renderer1] [error] The "path" argument must be of type string. Received type undefined: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:375:7)
	at Function.Module._nodeModulePaths (internal/modules/cjs/loader.js:590:37)
	at Module.load (internal/modules/cjs/loader.js:777:23)
	at Module._load (internal/modules/cjs/loader.js:693:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:348)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:839)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:940:198)
	at Module.require (internal/modules/cjs/loader.js:820:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:33:205)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:945:34)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:599)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:834:692)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:832:453)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:405)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:83
	at Array.map (<anonymous>)
	at h._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:71)
	at h.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:546)
	at h._activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:833:300)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:843:159
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-07-17 06:28:31.232] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.r.onerror (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:442:141)
```

**Comment by utw4376** [comment] 2020-07-17 10:52
> Can you please disable `vscode-icons-team.vscode-icons` extension, reload window and try?

Same result. No PS session. No Developer Tools. 
Error in Extension Host:

[2020-07-17 12:47:00.501] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:375:7)
	at Function.Module._nodeModulePaths (internal/modules/cjs/loader.js:590:37)
	at Module.load (internal/modules/cjs/loader.js:777:23)
	at Module._load (internal/modules/cjs/loader.js:693:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:348)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:839)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:940:198)
	at Module.require (internal/modules/cjs/loader.js:820:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:33:205)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:945:34)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:599)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:834:692)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:832:453)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:405)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:83
	at Array.map (<anonymous>)
	at h._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:71)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:176
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by sandy081** [comment] 2020-07-17 10:55
Sorry I have no clue. I will wait for @alexdima 's insights here.

**Comment by dbaileyut** [comment] 2020-07-17 15:28
Same stack trace in extension host as above with 1.47.2

**Comment by alexdima** [comment] 2020-07-20 13:02
Very likely duplicate of #102642

**Comment by utw4376** [comment] 2020-07-20 13:41
> Very likely duplicate of #102642

I tend to agree after doing the following test w/ 1.47.2:

- Starting code.cmd from an elevated powershell window. (HOMEPATH and HOMEDRIVE do not exist.)
- The powershell session in vscode does not get started.
- Creating the environment variables HOMEPATH and HOMEDRIVE manually in the powershell window.
- Starting code.cmd from that powershell window.
- The powershell session in vscode gets started.

**Comment by andriktr** [comment] 2020-07-20 14:59
> > Very likely duplicate of #102642
> 
> I tend to agree after doing the following test w/ 1.47.2:
> 
> * Starting code.cmd from an elevated powershell window. (HOMEPATH and HOMEDRIVE do not exist.)
> * The powershell session in vscode does not get started.
> * Creating the environment variables HOMEPATH and HOMEDRIVE manually in the powershell window.
> * Starting code.cmd from that powershell window.
> * The powershell session in vscode gets started.

I can confirm the same.

**Comment by deepak1556** [comment] 2020-07-20 17:24
Thanks @alexdima 

Also thanks for confirming @utw4376 @andriktr , merging to #102642

**Closed by deepak1556** 2020-07-20 17:24 UTC
