### ISSUE TITLE
caret and fold icon are equality!

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#15324] opened 2016-11-11 01:31 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (2583c1d1d2bb5430a899800523781c8d68cf98bb, 2016-11-10T19:19:29.788Z)
- OS Version: Darwin x64 16.3.0

The fold icon and caret are the same. And both enabled make explorer looks ugly.
So when icon theme has fold icons, hide caret.
![](http://o8z0dg641.bkt.clouddn.com/caret.png)

**Comment by leaxoy** [comment] 2016-11-11 01:52
How sublime deal with!
![](http://o8z0dg641.bkt.clouddn.com/sublime.png)

**Comment by aeschli** [comment] 2016-11-11 20:58
What do you mean by 'caret'?

**Comment by aeschli** [comment] 2016-11-23 21:40
Closing until more information is provided.

**Comment by leaxoy** [comment] 2016-11-26 05:32
`Caret` means arrow to indicate folder open or close state.
And the indent of `folder and file icon` confused me. So it's hard to recognize which folder belongs to.
For example:
`main.go` belongs to `example.com` alias `one`.
`main.go` belongs to `list` alias `two`

if `example.com` and `list` both have file. we can recognize those indent.
but if only `example.com` has files. we can't figure out `files` belongs to `example.com` or `list` explicitly.

**Comment by leaxoy** [comment] 2016-11-26 05:34
In sublime, if we use theme third_party, we can hide `arrow` left of `folder icon`, so there is no blurry to recognize which `folder` belongs to for a `file`

**Comment by aeschli** [comment] 2016-11-28 14:44
duplicate of #11762

**Comment by leaxoy** [comment] 2017-01-07 10:16
I have a suggestion on this .
If a theme has folder icon use folder icon only.
If a theme has no folder icon use default folder icon instead.
If no use icon theme, use arrow instead.


![](http://o8z0dg641.bkt.clouddn.com/pad.png)

vs

![](http://o8z0dg641.bkt.clouddn.com/no-pad.png)

**Comment by aeschli** [comment] 2017-01-26 10:00
The indentation is now fixed in the January build

**Closed** 2017-01-26 10:00 UTC
Labels: themes
