### ISSUE TITLE
Unable to connect to VS Code server: Error in request

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#196021] opened 2023-10-19 17:56 UTC
1. Open a repo in a codespace 
2. Checkout a branch that is behind main 
3. Merge main 
4. :bug: I get this error in the logs and the merge doesn't get committed even when there are no conflicts, all incoming files remain staged

```
Auto-merging package.json
hint: Waiting for your editor to close the file... Unable to connect to VS Code server: Error in request.
Error: connect ENOENT /tmp/vscode-ipc-058359e7-b2f2-4143-962d-a4b2f7f39333.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/tmp/vscode-ipc-058359e7-b2f2-4143-962d-a4b2f7f39333.sock'
}
error: There was a problem with the editor 'code --wait'.
Not committing merge; use 'git commit' to complete the merge.
```

**Comment by alexdima** [comment] 2023-12-05 08:05
`code --wait` sounds like vscode is configured as the git commit message editor. Perhaps Codespaces configure this by default.

**Comment by aeschli** [comment] 2023-12-06 16:28
Codespaces sets `GIT_EDITOR=code --wait` which is the used by the git command.

`code` is added by us to the PATH of the integrated terminal. It internally uses an IPC socket to talk to VS Code. This seems to happen here. When trying this myself this works.

**Comment by aeschli** [comment] 2024-01-09 16:01
Closing as I'm not able to reproduce

**Closed by aeschli** 2024-01-09 16:01 UTC
Labels: github-codespaces, code-cli
