### ISSUE TITLE
iconTheme null still shows icons after init and disappears after ~1 sec

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#74356] opened 2019-05-26 13:24 UTC
- VSCode Version: 1.34 stable (`a622c65b2c713c890fcf4fbf07cf34049d5fe758`) and 1.35 insiders (`6b081a9f0089062b2cd105e1f1ab366591291534`)
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Set `"workbench.iconTheme"` to `null`.
2. Reload VS Code window and watch opened editors or side bar file tree you will see icons for about 1 second and after init is done they disappear.

The expected behavior would be to do not show icons at all since I have `null` set.

![icon theme](https://user-images.githubusercontent.com/10441177/58382417-928bb580-7fd2-11e9-8fc0-7cccf5afa1d1.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by svipas** [comment] 2019-05-26 13:25
Tried to do the same in Exploration Build, which is using Electron 4.0.5 and VS Code 1.32.0 and it works fine, there's no such issue.

**Comment by usernamehw** [comment] 2019-05-26 13:31
Duplicate of #73121 ?

**Closed** 2019-05-26 15:52 UTC
Labels: *duplicate
