### ISSUE TITLE
Incorrect bracket highlighting in JSX/TSX files

### ISSUE THREAD

**Issue by 0sdavison** [microsoft/vscode#84281] opened 2019-11-08 15:47 UTC
Issue Type: <b>Bug</b>

With the following code in a `.tsx` file, placing the cursor on line 2 highlights the angle brackets around `<div />` as if they were the enclosing brackets. Placing the cursor on line 4, correctly highlights the curly braces.

```tsx
export const ReactComponent = () => {

  return <div />;

};
```

![image](https://user-images.githubusercontent.com/33670444/68489399-00d8d300-0215-11ea-8ca9-444819510395.png)

![image](https://user-images.githubusercontent.com/33670444/68489429-10581c00-0215-11ea-869c-61408b8d2a32.png)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362
No extensions

**Comment by brpratt** [comment] 2019-11-08 16:50
I'm seeing similar behavior, though this seems to be a problem with JSX in general. Here are some other examples from a fresh `npx create-react-app`:

![Screen Shot 2019-11-08 at 10 49 50 AM](https://user-images.githubusercontent.com/2567752/68495337-98d6bc80-0215-11ea-8f18-5d30fb225561.png)
![Screen Shot 2019-11-08 at 10 50 15 AM](https://user-images.githubusercontent.com/2567752/68495338-98d6bc80-0215-11ea-8a53-2928c0705eab.png)
![Screen Shot 2019-11-08 at 10 50 27 AM](https://user-images.githubusercontent.com/2567752/68495340-98d6bc80-0215-11ea-8b18-0d87c9b37122.png)

**Comment by ThaJay** [comment] 2019-12-02 17:18
The name of this feature is "bracket matching" so this issue did not show up in my initial search, but https://github.com/microsoft/vscode/issues/84537 does indeed look like a duplicate of this issue.

**Closed** 2019-12-05 15:13 UTC
Labels: bug, editor-bracket-matching
