### ISSUE TITLE
CPU usage at 100%

### ISSUE THREAD

**Issue by ivanwitzke** [Microsoft/vscode#24713] opened 2017-04-13 20:25 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.8.0-46-generic (Xubuntu)
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.5|
|ng-template|Angular|0.1.1|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.11.0|
|php-intellisense|felixfbecker|1.1.4|
|package-watcher|GregorBiswanger|0.0.2|
|angular-bootstrap|herrherrmann|4.0.6|
|phpcs|ikappas|0.7.0|
|phpmd|linyang95|1.1.4|
|code-settings-sync|Shan|2.6.2|
|autoimport|steoates|1.2.2|
|nativescript|Telerik|0.6.1|
|vscode-wakatime|WakaTime|1.1.3|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|twig|whatwedo|1.0.2|;

---

After some time with VS Code open, it will start freezing some times and use 100% of CPU (if it's a multicore processor, only one core is at 100%).

**Comment by jrieken** [comment] 2017-04-14 07:15
@ivanwitzke Please htop or a similar tools to get the full command line arguments of the process that runs high. VS Code start many processes and they all identify themselves via their command line args

**Comment by iJaniashvili** [comment] 2017-04-21 06:37
Same for me

* VSCode Version: 1.11.2 (1.11.2)
* OS Version: macOS Sierra 10.12.4
* Extensions:
```
DotJoshJohnson.xml@1.7.0
EditorConfig.EditorConfig@0.9.3
TwentyChung.jsx@0.0.1
WakaTime.vscode-wakatime@1.1.3
abadi199.elm-format@0.1.0
alefragnani.Bookmarks@0.14.1
alefragnani.project-manager@0.15.0
christian-kohler.path-intellisense@1.2.0
dzannotti.vscode-babel-coloring@0.0.4
esbenp.prettier-vscode@0.14.0
flowtype.flow-for-vscode@0.5.0
formulahendry.auto-close-tag@0.3.11
formulahendry.auto-complete-tag@0.0.1
formulahendry.auto-rename-tag@0.0.11
ms-vscode.Theme-TomorrowKit@0.1.4
robertohuertasm.vscode-icons@7.5.1
sbrink.elm@0.8.3
shinnn.standard@0.2.3
slb235.vscode-coffeelint@0.0.2
vscodevim.vim@0.6.17
vsmobile.vscode-react-native@0.3.2
waderyan.gitblame@1.6.0
wayou.vscode-todo-highlight@0.4.15
```

**Comment by iJaniashvili** [comment] 2017-04-21 07:18
Disabling GPU tamed it down `code --disable-gpu`

**Comment by jrieken** [comment] 2017-04-21 07:33
@ivanwitzke Same for you: https://github.com/Microsoft/vscode/issues/24713#issuecomment-294105467

**Comment by iJaniashvili** [comment] 2017-04-21 08:51
@jrieken 

`ps axww | grep Visual`
```
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --database=/var/folders/f6/z_ccbkrn6pq9p7klwfs7b6tc0000gn/T/VSCode Crashes --url=https://ticinocrashreporter.azurewebsites.net/crash --handshake-fd=67

/Applications/Visual Studio Code.app/Contents/MacOS/Electron

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=gpu-process --channel=94660.0.1886989816 --mojo-application-channel-token=1592FD2E6E5E6E87472F7AB2F0672E7E --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=18,20,29,40,48,51,52,56,58,66,67,71,73,75 --gpu-vendor-id=0x8086 --gpu-device-id=0x1927 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x1927

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=E7DE248F9ECCF185767CC14E8F10BF4D --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=D88017C33157BD2AFD06BCEF764607E7 --mojo-application-channel-token=E7DE248F9ECCF185767CC14E8F10BF4D --channel=94660.1.275805372

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=16E4EF316F622BB3DBB1651A67E88B4F --lang=en-US --node-integration=true --hidden-page --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=80009AC022C0060520D813D731748B44 --mojo-application-channel-token=16E4EF316F622BB3DBB1651A67E88B4F --channel=94660.2.916348958

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService

/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --database=/var/folders/f6/z_ccbkrn6pq9p7klwfs7b6tc0000gn/T/VSCode Crashes --url=https://ticinocrashreporter.azurewebsites.net/crash --handshake-fd=59

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/f6/z_ccbkrn6pq9p7klwfs7b6tc0000gn/T/vscode-tscancellation-a2c670122062a74bc660.sock*

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/jani/Library/Caches/typescript --enableTelemetry

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-languageclient/lib/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/server/out/jsonServerMain.js --node-ipc
```

**Comment by jrieken** [comment] 2017-04-21 09:05
@iJaniashvili which of them consumes most CPU/runs at a 100%?

**Comment by jrieken** [comment] 2017-04-24 13:14
Closing because this issue is without actionable information.

**Closed by jrieken** 2017-04-24 13:14 UTC
Labels: needs more info, perf

**Comment by kearnmachine** [comment] 2017-06-30 07:03
running on antergos linux (using MS binary version from aur) 
Version 1.13.1
`code /opt/visual-studio-code/resources/app/out/bootstrap --type=watcherService`
the process also uses about 2G RAM
when i start with `--disable-cpu` the problem is gone.

`        
 *-cpu
          description: CPU
          product: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
          vendor: Intel Corp.
          physical id: 9
          bus info: cpu@0
          version: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
          slot: SOCKET 0
          size: 3184MHz
          capacity: 3800MHz
          width: 64 bits
          clock: 100MHz
          capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt dtherm ida arat pln pts cpufreq
          configuration: cores=4 enabledcores=4 threads=4

*-display
             description: VGA compatible controller
             product: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 06
             width: 64 bits
             clock: 33MHz
             capabilities: msi pm vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: irq:29 memory:f7800000-f7bfffff memory:e0000000-efffffff ioport:f000(size=64) memory:c0000-dffff
`

**Comment by danielcb** [comment] 2017-07-02 14:58
Can confirm the last comment. `code /opt/visual-studio-code/resources/app/out/bootstrap --type=watcherService` uses 130+% cpu and 2+GB RAM constantly.

**Comment by tavriaforever** [comment] 2017-07-03 12:45
+1 
1.13.1

**Comment by aleksei-tkachuk** [comment] 2017-07-05 14:20
The following command "/home/user/.vscode/extensions/ms-vscode.cpptools-0.12.0/bin/Microsoft.VSCode.CPP.IntelliSence.Msvc.linux 22196 1" accordingly to my htop consumes 100% CPU. What is more, there are two instances of this process running on the system while only 1 vscode is running. vscode version 1.13.1

**Comment by richard-a-j** [comment] 2017-07-13 10:56
I also get this on 1.14.

PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
10388 rjones     20   0 2952M 2009M  4092 R 108. 12.6  4h01:56 code /usr/share/code/resources/app/out/bootstrap --type=watcherService

Keeps my CPU nice and toasty.

**Comment by kleinash** [comment] 2017-08-03 22:33
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Ubuntu 16.04
Nvidia GTX 1080 (which I am using and do not want to deactivate) 

Cannot run more than one instance of vscode - one for each virtual env I am busy with. Seems to happen after a while of running everything freezes and get this process off htop: `find -L . -not ( ( -name .git -o -name .svn -o -name . ` Using over 100% of all CPUs and this guy all the way through startup: ` /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=watcherService `

**Comment by idealtitude** [comment] 2017-08-31 06:51
Solved the problem for me: modifying user's settings from:

"C_Cpp.intelliSenseEngine": "Tag Parser"

to

"C_Cpp.intelliSenseEngine": "Default"

High CPU usage (near 100%) when Tag Parser is enabled , but everythings normal when set to Default...

**Comment by Luisetelo** [comment] 2017-09-18 06:53
I'm still having this issue:
`luis     20575 60.6 24.9 3324988 2002568 tty2  Sl+  08:30  10:01 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=watcherService`

After a while the CPU usage is 0% but is still using 2 GB of memory.

```
Version 1.16.0
Commit 787b31c0474e6165390b5a5989c9619e3e16f953
Date 2017-09-06T16:19:37.192Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Ubuntu 16.04.3 LTS 64-bit
```

**Comment by hgx-Obsess10n** [comment] 2017-09-23 18:05
![image](https://user-images.githubusercontent.com/20741943/30775759-b763bb5a-a0cc-11e7-8cce-fa01a0e48d78.png)
emmm...4 rg.exe(D:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules\vscode-ripgrep\bin)

**Comment by jrieken** [comment] 2017-09-25 06:50
fyi @roblourens

**Comment by cdarken** [comment] 2017-10-14 13:07
Same here, on Antergos linux, installed PlatformIo extension that pulled C++ as a dependency. 2 processes at 100%, see screenshot below.

![screenshot from 2017-10-14 16-03-58](https://user-images.githubusercontent.com/1390998/31575935-9752092e-b0f9-11e7-9c6e-e714b63e79cc.png)

**Comment by roblourens** [comment] 2017-10-14 16:59
That's a different issue @cdarken, those processes look to be spawned by the C++ extension. You can open an issue in their repo.

**Comment by Alonski** [comment] 2017-10-20 08:30
I am also getting this issue... It wasn't happening yesterday
![image](https://user-images.githubusercontent.com/452199/31811858-b8b4a10a-b589-11e7-950a-50db0535aba7.png)

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
Handlebars|and|0.2.0
htmltagwrap|bra|0.0.3
path-intellisense|chr|1.4.2
vsc-ember-frost|cie|0.0.2
code-paredit|clp|0.1.1
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
vscode-gist|dba|1.0.0
vscode-npm-script|eg2|0.2.1
vscode-ember|emb|0.1.0
prettier-vscode|esb|0.24.0
tortoise-svn|fan|0.1.1
vsc-ember-cli|fel|0.3.3
beautify|Hoo|1.1.1
continuum|jam|1.2.0
solidity|Jua|0.0.29
vscode-stylefmt|mrm|2.5.0
EmberES6Snippets|pha|2.2.0
vscode-icons|rob|7.15.0
code-settings-sync|Sha|2.8.3
stylelint|shi|0.30.0
slack|soz|0.0.13
code-spell-checker|str|1.4.10
sort-lines|Tyr|1.3.0



Reproduces without extensions: No

So I should go one by one and see which one is causing it?

**Comment by ImJoeHs** [comment] 2017-11-10 07:05
VSCode Version: Code 1.18.0
OS Version: Windows_NT x64 10.0.15063

![image](https://user-images.githubusercontent.com/13445155/32646540-07ad3214-c628-11e7-962b-889629902cfb.png)

Memory usage rases by time, soon it run out all my memory...

**Comment by jackpot1136** [comment] 2017-11-10 07:10
I reported this to security last night they are planning to overload the
system, than choo for the storage safes since they hit the keys. pull the
keys Microsoft
