### ISSUE TITLE
Blinking text in full-screen with 3-way split window

### ISSUE THREAD

**Issue by rturknett** [Microsoft/vscode#53968] opened 2018-07-10 14:40 UTC
Issue Type: <b>Bug</b>

Steps:
1. Open javascript file in editor 
2. Select split editor
3. Select split editor again
4. Enter full-screen mode

Mid 2017 Macbook Pro 13"
Dell P2715Q monitor
Display settings: scaled to "looks like 3360x1890"

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.4.1
prettier-vscode|esb|1.5.0
license-injector|mar|0.0.2
python|ms-|2018.6.0
debugger-for-chrome|msj|4.7.0
remote-vscode|raf|1.1.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-07-11 05:36
Duplicate of https://github.com/Microsoft/vscode/issues/47787

**Closed by bpasero** 2018-07-11 05:36 UTC
Labels: workbench-grid
