### ISSUE TITLE
Clipboard access through Extensions API

### ISSUE THREAD

**Issue by fabiodamasceno** [Microsoft/vscode#4972] opened 2016-04-05 18:27 UTC
- VSCode Version:0.10.11
- OS Version: Windows 10, Mac OSX El Captain

Hi, I'm developing [console-wrapper](https://github.com/fabiodamasceno/vscode-console-wrapper) , that is an extension for javascript console.log (other languages support will be added soon) and I need some access for clipboard content in Extensions API. I think this methods should be enough for most of cases:
- vscode.clipboard.getContent()
- vscode.clipboard.setContent()

Some event handlers should be useful, too, like:

-vscode.clipboard.beforeContentLoad()
-vscode.clipboard.onContentLoad()
-vscode.clipboard.onContentLoaded()

Steps for the extension:
 - user copy some text;
- when ctrl+shift+q text is wrapped with console.log and inserted at below line.

hugs,

**Comment by jrieken** [comment] 2016-04-06 10:15
Closing as duplicate of #217. 

We don't plan to implement that in VS Code but advise to use a node module like https://github.com/xavi-/node-copy-paste. This is to reduce complexity in the VS Code API because otherwise we have to handle/describe all sorts of clipboard data (think of images and other binary data).

**Closed by jrieken** 2016-04-06 10:15 UTC

**Comment by brianwhited** [comment] 2016-06-03 18:19
@jrieken the node-copy-paste module only copies text. This will not work for images. I am attempting to create a markdown extension that will allow the user to copy an image to their clipboard and paste it into their markdown document. When the paste occurs, the extension will save the image to an appropriately named folder and insert the text to display the image when the markdown is compiled. I know this is a closed ticket, but most tickets I have seen in regards to copy/paste reference back to this one.

**Comment by jrieken** [comment] 2016-06-06 08:12
Unsure about that. The [docs](https://github.com/xavi-/node-copy-paste#the-api) about `copy` says

> Takes either a string, array, object, or readable stream.

The last (readable stream) sounds interesting to me

**Comment by JakeGinnivan** [comment] 2016-07-14 02:07
@brianwhited how did you go creating that extension?

**Comment by brianwhited** [comment] 2016-07-14 02:26
@JakeGinnivan I wasn't able to complete this due to not being able to access the clipboard fully. I have not tried since the newest update (1.3) because of time constraints at work. I will be revisiting this shortly. Do you have any suggestions?

**Comment by mushanshitiancai** [comment] 2016-08-21 07:31
@brianwhited I want to create a extension to markdown too!

@jrieken @brianwhited I tried `node-copy-paste`module ,it can't handle image in clipboard(just return empty string).

But I found that there is a useful function in Electron API:

```
clipboard.readImage([type])
Returns the content in the clipboard as a NativeImage.

clipboard.writeImage(image[, type])
Writes image to the clipboard.
```

But not like Atom,VSCode can't access to Electron API,see #3011

So, how to do ?

**Comment by mushanshitiancai** [comment] 2016-08-23 07:26
@brianwhited I post a extension that can paste image from clipboard [Paste Image](https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image)

Because I use applescript to handle image in clipboard, so it only work in MacOS.

**Comment by bgse** [comment] 2016-11-09 21:57
@jrieken The node-copy-paste is not an ideal solution, for example on default Ubuntu installation it will require the user to install xclip.
