### ISSUE TITLE
JavaScript for-loop colouring broken

### ISSUE THREAD

**Issue by TrekkerUK** [Microsoft/vscode#10638] opened 2016-08-17 23:11 UTC
- VSCode Version: Code - Insiders 1.5.0-insider (55168276e4c0b6ec2404ac20af04eeed5f5b1000, 2016-08-17T06:08:10.227Z)
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

This occurs in both the latest nightly and release.

For-loops with a particular condition and arrangement of spaces cause the coloring to break from that point onward. Example code is below and attached screenshot - the last loop breaks.

The format has to be:
- Less then symbol
- No spaces
- Variable (foo, foo.bar. foo['bar'] is okay)
- One or more spaces
- ; character

If you change any one of those, as in the example below, the colouring is fine. It's almost as though it's seeing what looks like the start of an HTML tag and getting confused.

```javascript
for (var i = 0; i <400; i++) { // Start loop
    doSomething();
}

for (var i = 0; i < foo ; i++) { // Start loop
    doSomething();
}

for (var i = 0; i < foo; i++) { // Start loop
    doSomething();
}

for (var i = 0; i <foo; i++) { // Start loop
    doSomething();
}

for (var i = 0; i <foo ; i++) { // Start loop
    doSomething();
}
```

![for-loop colouring](https://cloud.githubusercontent.com/assets/13033095/17756196/649ccb06-64d6-11e6-8d78-30833f8794d2.png)

**Comment by alexandrudima** [comment] 2016-08-18 06:03
@aeschli Assigning to you as this might require a fix on our side. IMHO the `Javascript.tmLanguage.json` grammar should not contain any `jsx-*` rules which are triggered by this sample code.

**Comment by aeschli** [comment] 2016-08-18 07:31
@alexandrudima It's on purpose that for JavaScript we use the TypeScriptReact grammar.
React Native uses the .js extension (not .jsx) and we want it to work out of-the-box.

The issue is a duplicate of #11.

**Closed by aeschli** 2016-08-18 07:31 UTC
