### ISSUE TITLE
Autocomplete gets in the way

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#18740] opened 2017-01-18 15:48 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.1|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.10|

---

Trying to type, `a.`, autocomplete pops up and forces the 1st suggestion `as` when i type `.`

Using an angular cli generated app.

Steps to Reproduce:

![ac](https://cloud.githubusercontent.com/assets/439226/22070895/84142e3a-dd6b-11e6-9800-5d1e57025bd5.gif)

**Comment by mjbvz** [comment] 2017-01-19 02:15
This looks like a duplicate of #17584 to me. We did some work to fix this scenario. You can try it out in 1.9 insiders.

**Closed by mjbvz** 2017-01-19 02:15 UTC
Labels: duplicate, typescript
