### ISSUE TITLE
PWA: Cannot fetch files in a remote repo after going back online

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#141605] opened 2022-01-26 21:16 UTC
Testing #141296

Repro steps:
- Open a remote repo in https://insiders.vscode.dev/
- Go offline, wait for the red status bar + "offline" status to appear
- Try to open some of the files, see the "Failed to fetch" messages
- Go back online, wait for the red status bar to disappear
- Try to open the same files, same "Failed to fetch" messages appear

**Comment by joaomoreno** [comment] 2022-01-27 13:25
Yeah it seems some layer caches the error promises. Two possibilities:

1. Core workbench services @bpasero
2. Remote Repositories extension @joyceerhl

**Comment by joaomoreno** [comment] 2022-01-27 19:33
The problem is not the `Failed to fetch` per se, but rather that some code caches that error when it happens due to being offline but keeps returning it even after going online, when the promise would actually succeed.

**Comment by bpasero** [comment] 2022-01-28 06:34
The console shows this error:

```
  ERR HttpError: Failed to fetch
    at eval (extension.js:117:7584)
    at Su.request (extension.js:119:25450)
    at Su.getBlobContent (extension.js:219:727)
    at Su.getFileContent (extension.js:219:1422)
    at vc.readFile (extension.js:112:14864)
    at Ys.readFile (extension.js:107:27024)
```

The extension is: `https://github.vscode-unpkg.net/GitHub/remotehub/0.23.2022012602/extension/dist/browser/extension.js#vscode-extension:formatted`

**Comment by joyceerhl** [comment] 2022-02-24 03:32
@joaomoreno is spot on, RemoteHub constructs a filetree representing the repo contents where each file has a memoized `getContent` method that returns a promise resolving to the file contents. That's where the stacktrace above is coming from. We need to know when to clear out the memoized promise. We could use some heuristics like refetching the filetree when we see a 'failed to fetch' like the above.

**Comment by meganrogge** [comment] 2022-02-25 17:37
Still reproduces for me
Offline:
![Screen Shot 2022-02-25 at 11 36 22 AM](https://user-images.githubusercontent.com/29464607/155761296-67d314c5-a322-4251-af38-ab9820b2cd90.png)
Back online:
![Screen Shot 2022-02-25 at 11 36 33 AM](https://user-images.githubusercontent.com/29464607/155761314-fcc50f00-7c0a-4dd6-9fa1-153644f1081c.png)

**Closed** 2022-02-25 18:05 UTC
Labels: bug, verification-found, remote, file-io
