### ISSUE TITLE
Variable value hover tooltips in debugger stop working after first hover

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#1804] opened 2016-01-05 22:39 UTC
Didn't see another issue filed for this already so forgive me if I missed it:

In VS Code December release, we've noticed that when you hover over variable names while the debugger is stopped, it works the first time but then it doesn't work again until you resume debugging and it hits a new breakpoint.  Sometimes I see it stop working entirely even across debugging sessions.  I don't see any requests being made to my debug adapter on hover, so I'm guessing this is happening client-side.

**Comment by isidorn** [comment] 2016-01-06 09:42
We are improving the debug hover this milestone  (e.g we are adding a tree for complex variable inspection) so this should get fixed as a part of that.
I will close once I verify this is no longer happening

**Comment by isidorn** [comment] 2016-01-06 12:59
I no longer side this with our new debug hover work

**Comment by daviwil** [comment] 2016-01-06 14:01
Great!  Looking forward to the improvements :)

**Comment by daviwil** [comment] 2016-02-18 18:45
We're actually still experiencing this issue with the PowerShell extension in 0.10.8.  Here's some information from @rkeithhill:

--

I've observed that scope plays some part here. Global scope variables act flakey at first. They maybe show once but not thereafter as long as we're executing in global scope. As soon as I step into a function, the global variables pop debug data tips quite reliably. Unfortunately, I then get no data tips for the variables inside the function I'm executing in. And when there is not a data tip, it is because we never received a variables request from VSCode. Every time we receive a variables request (not related to populating the variables view), a debug data tip appears.

--

Is there some way that we might be returning our variable data wrong which causes the VS Code debug client to react incorrectly to data tip requests?  Let me know if I should file a separate issue for this.

**Comment by rkeithhill** [comment] 2016-02-18 20:51
I would if this could have anything to do with us using `$` in the variable name e.g. `$index`.

**Comment by isidorn** [comment] 2016-02-19 09:07
I just checked if `$` makes a difference on our side and it does not, we still treat `$index` as one word.

Rkeithill is right, the scope plays a big part there, once a user hover over a word we try to find a variable matching that word by going through all the 'non expensive' scopes. If the variable is not in the `non expensive` scopes the hover will not show it

To overcome these issues I suggest you switch to the alternative hover strategy - return [supportsEvaluateForHovers](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L495) as a part of the capabilites response. Then on hover VSCode will not go through the scopes but will always pass the hovered over value to the powershell adapter to be evaluated. This works better in practice if the powershell adapter can somehow guarantee that no dangereous scripts would be executed by accident in this way.

We currently use this approach for node and it works quite well for us.

**Comment by daviwil** [comment] 2016-02-19 15:31
Thanks Isidor!  I haven't been using the capabilities features of the debug protocol yet, so this seems like a good place to start.  We'll give that a shot and see if it helps for us.

**Comment by isidorn** [comment] 2016-02-19 15:34
That should fix this, since the issue explained here are the limitations of our 'scope sniffing' approach.
Closing for now, and we can open a seperate issue if the `supportEvaluateForHovers` does not do the trick for you

**Comment by rkeithhill** [comment] 2016-02-19 17:05
>>   try to find a variable matching that word by going through all the 'non expensive' scopes.

What determines if a scope is expensive?  Higher up the callstack?  Would it matter that we have multiple "top-level" variable containers: Local, Script, Global and Auto?

**Comment by isidorn** [comment] 2016-02-19 18:18
Adapter decides for each scope if it is [expensive](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L564) 
Not sure how powershell defines these, but hover does not sniff inside expensive scopes.

**Comment by rkeithhill** [comment] 2016-02-20 05:39
OK the issue is not related to the scope's `expensive` field as we always set it to `false`.

**Comment by rkeithhill** [comment] 2016-02-20 23:26
What message should I receive if I've implemented `supportsEvaluateForHovers`?  I'm pretty sure I have the initialize request returning the right data e.g.:
```
2/20/2016 4:17:12 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 1,
      "command": "initialize",
      "arguments": {
        "adapterID": "PowerShell",
        "linesStartAt1": true,
        "pathFormat": "path"
      }
    }

2/20/2016 4:17:12 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "initialized",
      "body": null
    }

2/20/2016 4:17:13 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": "1",
      "command": "initialize",
      "success": true,
      "body": {
        "supportsConfigurationDoneRequest": true,
        "supportsFunctionBreakpoints": false,
        "supportsConditionalBreakpoints": false,
        "supportsEvaluateForHovers": true,
        "exceptionBreakpointFilters": null
      }
    }
```

But for hovers I'm still seeing a `variablesRequest` message and the hover tip behavior is still flaky.  I'll get it once for a variable but not a second time and some variables still don't show tips at all.
```
2/20/2016 4:17:30 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 32,
      "command": "variables",
      "arguments": {
        "variablesReference": 74
      }
    }

2/20/2016 4:17:30 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": "32",
      "command": "variables",
      "success": true,
      "body": {
        "variables": [
          {
            "name": "$itemCount",
            "value": "5",
            "variablesReference": 0
          }
        ]
      }
    }
```

**Comment by rkeithhill** [comment] 2016-02-21 00:11
BTW this is what I'm seeing:
![vscodeflakyhovertips](https://cloud.githubusercontent.com/assets/5177512/13199993/a6d059f8-d7f4-11e5-9ce4-28ebd5260df0.gif)
I've noticed that if I use the debug toolbar to step, I don't hardly get any hover tips during debugging.  I believe that is because when I move the cursor off the toolbar down to the code I'm interested in, I move the cursor over something that doesn't have a hover tip (or I'm moving the cursor too fast that it goes away). Anyway, I get a more repeatable experience by not moving the cursor much and using F10/F11 to step the script.

**Comment by isidorn** [comment] 2016-02-22 08:50
@rkeithhill sorry for not mentioning it, but you should use our [alpha](https://vscode-builds.azurewebsites.net/alpha) release, since the evaluate on hover feature is not shipped in our January release. It will be a part of February.
As for the hover tips delay, it is also implemented in the alpha release (there is a 300 ms timeout).

Can you please try it in [alpha](https://vscode-builds.azurewebsites.net/alpha) release and if you still see this strange behaviour I will investigate the underlying issue.

**Comment by rkeithhill** [comment] 2016-02-22 15:32
I don't have access to that site/builds. I have the latest Insiders build but I don't think that's the same.  I can ask @daviwil if he has access to alpha builds.

**Comment by isidorn** [comment] 2016-02-22 15:34
Here's a direct link which you should have access to
https://az764295.vo.msecnd.net/alpha/719730a346c842ea29d8a8fe99016e802e39a819/VSCodeSetup-alpha.exe

**Comment by rkeithhill** [comment] 2016-02-23 18:15
I see what you mean by issues with side-effects.  One of the first things I accidentally hovered over was a `Write-Output` command that requires input and if it is not supplied to the command, the command asks the host to ask the user for the input.  Not a good experience while debugging.  I don't think we are going to be able to use `supportsEvaluateForHovers` safely.

I updated the alpha just a few minutes ago and reverted back to the original 0.4.1 PowerShell extension version.  The flaky behavior is still there.  Tips show once and then not again until I step the debugger.  If there is anything I can do to help you figure out what is going on with this approach, don't hesitate to ask.  When the data hover tips work, they're beautiful.  :-)

**Comment by isidorn** [comment] 2016-02-23 19:08
I will investigate tomorrow / day after, can you just provide the simplest possible PS program for which this easily repros?

**Comment by rkeithhill** [comment] 2016-02-23 19:50
Here's the simplest repro:
```powershell
# Set breakpoint on line 4 (last line) and run.  Hover over $date on
# line 3 multiple times.  Hover tips displays only the first time.
$date = Get-Date"Date is $date"
```
However this might give more insight into which stepping into another scope/stackframe helps:
```powershell
# 1. Set a breakpoint on the last line of the script
# 2. Run the script until it breaks on the breakpoint on `foo 0 5`
# Hover over $date - be careful not to move the cursor over other
# variables that could display a hover tip.  $date should display
# a hover tip.  Move the cursor off and back onto $date - no tip.
# Hover over $proc, also no tip.
# 3. Press F11 to step into function foo.  Hover over $count in the
# function parameter list.  You should see 5, then move the cursor
# off and back onto $count, no tip.  Move over to $startIndex - also
# no tip.  No move the cursor up to $date and $proc (outside the function).
# Now these tips work correctly displaying hover tips every time you move
# over these variables.  Move over $date *inside* the function and note it
# works as well - every time.  Note: PowerShell uses "dynamic" scoping and
# NOT lexical scoping so variables from higher up the call stack are visible
# inside functions further down the call stack.  Weird but true.  :-)
# 4. Continue to step through the foo function to observe only the first
# hover tip from a variable inside the function (except $date) works.

$date = Get-Date
$proc = Get-Process 'Code - Alpha'

function foo($startIndex, $count) {
    $date
    "`$startIndex is $startIndex, `$count is $count"
    for ($i = $startIndex; $i -lt $count; $i++) {
        "`$i is $i"
    }
}

foo 0 5
```

**Comment by isidorn** [comment] 2016-02-25 16:20
Ok so I found the issue looking into the 4 line sample from above. The issue is that the variable `$date` exists in multiple scopes. Because VSCode has no deep language understanding yet, it can not correlate the word that is being hovered over with a scope. Thus when we search through scopes and find multiple matches for `$date` we are not sure which one to show so we show none.

This variable duplication seems to happen to powershell all the time, unlike other languages.
As a workaround the powershell adapter could say that all scopes except the `local` scope are `expensive`, thus the hover will only search in the `local` scope and always find a hover match. We do not use `expensive` for any other functionality except the hover so I think this is fine.

Opinions?

**Closed by isidorn** 2016-02-25 16:20 UTC
Labels: bug, debug

**Comment by daviwil** [comment] 2016-02-25 16:30
Another option could be for VS Code to always take the variable from the earliest scope in the scope list that the adapter returned.  I would think that most adapters would return their scopes with the most local scope first, but maybe there's a language out there that wouldn't play by the same rules.

Could also have some adapter configuration that dictates how to prioritize scopes.  Maybe there could be an extra field on the Scope object which gives a numeric priority order?  In the case that the adapter gave the same value (like 0) for the priority of all scopes, you could just continue with your current behavior of not showing anything since it's not obvious what to show.

**Comment by isidorn** [comment] 2016-02-25 16:32
All good ideas. Though taking the earliest might in some rare cases show the wrong result to the user which might be very confusing.

@weinand opinions?

**Comment by daviwil** [comment] 2016-02-25 16:34
Yep, agreed that it could be problematic.  Would be nice to have some opt-in behavior but I can understand if it would be too much of a special case.

**Comment by rkeithhill** [comment] 2016-02-25 17:22
Yes the earliest (first?) scope "might" not always be the best.  For instance, PowerShell returns `Auto` as the first scope which is a "filtered" view of `Local` variables.  It turns out that would probably be OK but I could see other debugger extensions that might put `Global` first above `Local` not realizing there are implications.  I do like the idea of having a separate field for `lookup order` for hover tips.  That way, display order in the debug view isn't implicitly tied to the lookup order.

FYI I've modified our code to have all other scopes except Local return Expensive=true and that has helped.  However I have found one other bug/issue in the process.  PowerShell is a case-insensitive language and given this method:
```powershell
function Do-Work($workCount, $opt = 'foo')
{
    Write-Output "Doing work..."

    Write-Item $workcount

    Write-Host "Done!"
}
```
I get a hover tip on the first instance of `$workCount` but never on the second instance `$workcount`.  That should work.  Is there a metadata tag somewhere indicating a language is case-insensitive that perhaps we are failing to set?

**Comment by rkeithhill** [comment] 2016-02-25 17:32
Ideally, we would like to have the debugger always search three scopes in order.  First Local scope, then Script scope and finally Global scope.  We have a fourth scope `Auto` that is redundant with `Local` (filtered view of `Local`).  Currently, we always return all variables to VSCode in each of these scopes.  So it isn't very expensive to lookup a variable within each scope.  That lookup is O(1) since variable reference id passed to us is just an index into a `List<>`.

**Comment by isidorn** [comment] 2016-02-25 18:44
Good feedback, @weinand and me will discuss.
As for the moment we are not providing any option that an adapter can specify it is case-insensitive. This is something to add for the future and we should plan for it.

**Comment by weinand** [comment] 2016-02-25 22:20
@rkeithhill @daviwil you might want to consider to do the lookup yourself: enable eval based hover and then in the eval request do the lookup yourself if the `context` == 'hover'.

**Comment by rkeithhill** [comment] 2016-02-25 22:27
@weinand I'll look at this tonight but when I first enabled supportsEvaluateForHover, we wound up evaluating PowerShell commands which blocked because most commands have mandatory input.  This caused the command to ask the debug host to prompt the user for that input.  Now I could implement some code to try to distinguish variables from other things (commands, expressions, etc) but that seems more dangerous to me.  :-)

**Comment by weinand** [comment] 2016-02-25 22:39
@rkeithhill you are using your own implementation of eval. So you are in control what to do in the 'eval' that is used for the hover. Instead of using the normal 'eval' you could lookup the 'expression' in a data structure that you have prepared in the last stopped event (probably the same data structure that the adapter returns in the stacktrace > scope > variables requests). So basically you would mimic what the VS Code UI does, but you have more control over the details.
