### ISSUE TITLE
v1.40.0 Crashing on Startup (Windows 10)

### ISSUE THREAD

**Issue by pipobscure** [microsoft/vscode#84574] opened 2019-11-12 10:18 UTC
The update to electron 6 causes crashing on Windows 10. (I've had this happen with my own electron app as well; updating to electron 7 solved it)

- VSCode Version: v1.40.0
- OS Version: Windows 10

Steps to Reproduce:

1. Update / Install (first updated then tried complete reinstall)
2. Try running (popup "The Window has crashed")

Does this issue occur when all extensions are disabled?: Yes
Happens on a clean install as well!

```
PS C:\Users\UserName> &'C:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\Code.exe'
PS C:\Users\UserName>
 [main 2019-11-12T10:14:36.014Z] update#setState idle
Windows PowerShell[10256]: ../../third_party/electron_node/src/inspector_agent.cc:810: Assertion `(client_) != nullptr' failed.
 1: 00007FF70454C9E2 node::EmitAsyncDestroy+11839202
 2: 00007FF7039D9A96 node::Abort+22
 3: 00007FF7039D9623 node::Assert+131
 4: 00007FF7039E44BD node::inspector::Agent::Connect+253
 5: 00007FF70460C829 uv_udp_set_multicast_loop+457321
 6: 00007FF70460DAA7 uv_udp_set_multicast_loop+462055
 7: 00007FF7039FA294 uv_loop_delete+6724
 8: 00007FF7039FD2E4 node::BootstrapEnvironment+52
 9: 00007FF7039FD24C node::CreateEnvironment+268
10: 00007FF7039F9875 uv_loop_delete+4133
11: 00007FF7039EF185 uv_key_set+28101
12: 00007FF704591409 uv_translate_sys_error+206665
13: 00007FF70396155D uv_fs_get_statbuf+5917277
14: 00007FF702C51879 uv_cond_broadcast+62537
15: 00007FF7032CF879 node::AsyncResource::get_async_id+2248441
16: 00007FF702C7ACD0 uv_cond_broadcast+231584
17: 00007FF702C57FB5 uv_cond_broadcast+88965
18: 00007FF702C582E8 uv_cond_broadcast+89784
19: 00007FF70333B962 node::AsyncResource::get_async_id+2691042
20: 00007FF70458FE4B uv_translate_sys_error+201099
21: 00007FF70395BF67 uv_fs_get_statbuf+5895271
22: 00007FF7040466CF node::EmitAsyncDestroy+6570959
23: 00007FF703699144 uv_fs_get_statbuf+2999876
24: 00007FF703695708 uv_fs_get_statbuf+2984968
25: 00007FF703694964 uv_fs_get_statbuf+2981476
26: 00007FF70369754B uv_fs_get_statbuf+2992715
27: 00007FF7036A5C66 uv_fs_get_statbuf+3051878
28: 00007FF7033414FF node::AsyncResource::get_async_id+2714495
29: 00007FF70395572B uv_fs_get_statbuf+5868587
30: 00007FF70399D1F1 uv_fs_get_statbuf+6162161
31: 00007FF70399D039 uv_fs_get_statbuf+6161721
32: 00007FF703954C5C uv_fs_get_statbuf+5865820
33: 00007FF703954430 uv_fs_get_statbuf+5863728
34: 00007FF700AB6A12 node::InternalCallbackScope::Failed+312674
35: 00007FF70399C68A uv_fs_get_statbuf+6159242
36: 00007FF702478FB0 GetHandleVerifier+635376
37: 00007FF703B24AF1 node::EmitAsyncDestroy+1189873
38: 00007FF703B24B74 node::EmitAsyncDestroy+1190004
39: 00007FF702376BB0 uv_cond_signal+11648
40: 00007FF702385D26 uv_cond_signal+73462
41: 00007FF7023859CC uv_cond_signal+72604
42: 00007FF7023393BC uv_loadavg+855692
43: 00007FF7023865E6 uv_cond_signal+75702
44: 00007FF70235C2CE uv_os_getpid+66926
45: 00007FF70398B38D uv_fs_get_statbuf+6088845
46: 00007FF700EC24DC v8::String::Value::operator*+331020
47: 00007FF702B4668A IsSandboxedProcess+204602
48: 00007FF700EC1CE6 v8::String::Value::operator*+328982
49: 00007FF7006E13BF Ordinal0+5055
50: 00007FF70535D342 node::AsyncResource::CallbackScope::CallbackScope+4046130
51: 00007FFA4D077BD4 BaseThreadInitThunk+20
52: 00007FFA4D8CCED1 RtlUserThreadStart+33
[main 2019-11-12T10:14:36.281Z] [VS Code]: render process crashed!
```

**Comment by pipobscure** [comment] 2019-11-12 13:49
Additional information:

I did `npm install electron` in the VSCode folder followed by `.\node_modules\.bin\electron resources\app\`. This sucessfully launches VSCode. Of course there is some functionality that doesn't work (keyboard shortcuts mainly) but all-in-all it at least starts up.

All of this convinces me that the build against electron v6 is simply broken.

**Is there a way do download a previous version (v1.39) and install that? That way I could at least continue using it until this is actually resolved?**

(on https://code.visualstudio.com I can only find downloads for v1.40 / v1.41 but nothing earlier and the github releases are source-code only which is a pain, because it uses yarn and requires a node >8 & <11 and that's just the stuff I found out quickly. It should be possible to rollback in case of serious error such as this!)

**Comment by rogererens** [comment] 2019-11-12 15:35
There's a menu item on the home page called 'Updates' (between 'Docs' and 'Blog')
On the resulting page (currently https://code.visualstudio.com/updates/v1_40 ) you have a list of months on the left side. I chose 'September 2019', finding a link (on the third line of the page) to revert back to v1.39.2

**Comment by pipobscure** [comment] 2019-11-12 15:41
@rogererens thanks!

Is there anything I can do to help debug this further? I'm fairly sure that it's an electron v6 problem. I'm working on an electron app myself and we had the same issue with v6. I never bothered to debug it though, since upgrading to v7 solved it entirely.

Let me know what I can do to help.

**Comment by bpasero** [comment] 2019-11-13 06:32
We are building exploration builds that use a much newer version of our UI framework (Electron version 7.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration_1.41.0-1573181501_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1.41.0-1573181670.el7.x86_64.rpm)
* Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1573181432.tar.gz)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCodeSetup-x64-1.41.0-exploration.exe)

**Comment by pipobscure** [comment] 2019-11-13 14:54
@bpasero I tried the Windows exploration build; and aside from a few benign warnings (see below) it works perfectly fine.

```
PS C:\Users\DunkelPhilipp> & 'C:\Program Files\Microsoft VS Code Exploration\Code - Exploration.exe'
PS C:\Users\DunkelPhilipp>
 [main 2019-11-13T14:52:44.457Z] update#setState idle
(electron) 'systemPreferences.isInvertedColorScheme()' is deprecated and will be removed. Please use 'nativeTheme.shouldUseInvertedColorScheme' instead.
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
(node:22676) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:22676) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:4780) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:4780) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:4780) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:4780) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

**Comment by pipobscure** [comment] 2019-11-13 15:07
Also (just for completeness sake) I have node v13.1.0 installed on the system; besides that, there's the full configuration report on the system.

[system.txt](https://github.com/microsoft/vscode/files/3841834/system.txt)

**Comment by rogererens** [comment] 2019-11-14 09:15
@bpasero Since I do not have administrative rights on the machine, I can only try such an exploration build if it's a User-version or a portable ZIP-folder.

**Comment by bpasero** [comment] 2019-11-14 10:18
Here you go: https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCodeUserSetup-x64-1.41.0-exploration.exe

**Comment by rogererens** [comment] 2019-11-14 18:53
Still not working for me:

PS C:\Users\r.erens.MOHSA\AppData\Local\Programs\Microsoft VS Code Exploration> & '.\Code - Exploration.exe'
PS C:\Users\r.erens.MOHSA\AppData\Local\Programs\Microsoft VS Code Exploration>
 [main 2019-11-14T17:50:51.818Z] update#setState idle
(electron) 'systemPreferences.isInvertedColorScheme()' is deprecated and will be removed. Please use 'nativeTheme.shouldUseInvertedColorScheme' instead.
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
[main 2019-11-14T17:51:21.821Z] update#setState checking for updates
[main 2019-11-14T17:51:22.551Z] update#setState idle
[main 2019-11-14T17:53:01.533Z] [VS Code]: detected unresponsive

....
This takes ages (i.e. about 6 minutes)...
...

(node:30708) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:30708) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:30708) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:30708) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:36848) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:36848) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information

Just twice did this result in VSC starting up 'normally', showing the Welcome panel.

From the Help -> About menu:
Version: 1.41.0-exploration (user setup)
Commit: fbad8db043f1ef8e3b4031d46057edb5911f92ba
Date: 2019-11-08T02:57:50.817Z
Electron: 7.1.1
Chrome: 78.0.3904.99
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393

And process explorer shows:
![Capture2](https://user-images.githubusercontent.com/907897/68886552-b923e100-0717-11ea-8a2c-5f8870ec7108.PNG)

Toggling the Help -> 'Developer Tools' menu, results in nothing.

But most of the time, this dialog window pops up a lot:
![Capture code exploration](https://user-images.githubusercontent.com/907897/68884962-8fb58600-0714-11ea-8dce-6e84dcdba592.PNG)

Every time I click 'Keep Waiting' another message
[VS Code]: detected unresponsive
appears to show up.

Partly clipped by an 'invisible window'

The task manager shows 6 or 7 Code Exploration processes


And here's an exception and error message in the logging:

[main 2019-11-14T18:47:07.599Z] [uncaught exception in main]: Error: Object has been destroyed
[main 2019-11-14T18:47:07.599Z] Error: Object has been destroyed
    at WebContents../lib/browser/api/web-contents.js.WebContents.send (electron/js2c/browser_init.js:3553:15)
    at IpcMain.<anonymous> (C:\Users\r.erens.MOHSA\AppData\Local\Programs\Microsoft VS Code Exploration\resources\app\out\vs\code\electron-main\main.js:498:593)
(node:39524) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:39524) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:7680) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:7680) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:20320) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:20320) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

HTH,
Roger

**Comment by bpasero** [comment] 2019-11-18 17:22
From the sources of where the crash happens:

https://github.com/nodejs/node/blob/64219741218aa87e259cf8257596073b8e747f0a/src/inspector_agent.cc#L810

**Comment by bpasero** [comment] 2019-11-18 17:25
@pipobscure are you in any way connecting a debugger to VSCode or run a node.js debugger that could connect to VSCode?

**Comment by pipobscure** [comment] 2019-11-18 18:04
Not that I’m aware of, but I am running chrome with the chrome://inspect tab open usually

**Comment by bpasero** [comment] 2019-11-19 06:04
Oh yeah that sounds like it could have an impact!

**Comment by deepak1556** [comment] 2020-03-10 23:30
@pipobscure @rogererens can you confirm if the issue still happens with latest stable `1.43` ? Thanks!

**Comment by rogererens** [comment] 2020-03-11 21:10
It still happens with 1.43.0, yes.
![image](https://user-images.githubusercontent.com/907897/76462963-decda800-63e2-11ea-9aec-a7491aecd97c.png)

**Comment by deepak1556** [comment] 2020-03-11 21:19
@rogererens are you able to obtain any useful stack traces following https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#windows from the unresponsive process ?

**Comment by rogererens** [comment] 2020-03-11 22:00
No, sorry, I do not have administrator rights to run that installer.

**Comment by tehshwann** [comment] 2020-03-28 15:19
Whats the latest here?

**Comment by rogererens** [comment] 2020-03-29 10:55
I downloaded electron v8.2.
Running .\electron.exe -v on the command line does not report its version. I guess I'll have to wait until the Windows Server is updated by IT.

**Comment by andyc56-mso** [comment] 2020-04-22 22:26
I'm using Git for Windows 2.26.2, configured with VSCode as my editor, and if I do a
`git commit --amend`
to edit my most recent commit message and there is no currently-running instance of VSCode, Git launches it with the commit edit message to modify.  If I just close VSCode at this point, I get a whole slew of
`(node:8236) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information`
messages.  If there is a currently-running instance of VSCode when I commit with the --amend option, all is well, and the error message above is not generated.  The corresponding lines in my .gitconfig file are:
`[core]
editor = \"C:\\Users\\Andy\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --wait`

**Comment by rogererens** [comment] 2020-05-08 21:19
I'm able to run the 1.46.0-insider from the VSCode-win32-x64-1.46.0-insider.zip file.

But when I use the VSCodeUserSetup-x64-1.46.0-insider.exe installer, with all checkboxes ticked, the installed executable still hangs after double-clicking the desktop-icon (or choosing from the Start menu).

**Comment by deepak1556** [comment] 2020-05-08 21:46
Sorry for the silence in here, we have updated the steps to obtain crash report without additional tools https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#update

Currently this change is only available with insiders version https://code.visualstudio.com/insiders/ . Install the latest insiders and follow the steps from above but replace `code` with `code-insiders`

**Comment by deepak1556** [comment] 2020-08-28 21:15
Closing this one out based on original author's post, if there is still issue with latest insiders https://code.visualstudio.com/insiders please open new issue. Thanks!

**Closed by deepak1556** 2020-08-28 21:15 UTC
Labels: electron, electron-6-update, fixed-in-electron-7, freeze-slow-crash-leak, upstream
