### ISSUE TITLE
Files Automatically Opening when Searching

### ISSUE THREAD

**Issue by sombrerosheep** [microsoft/vscode#108665] opened 2020-10-14 15:40 UTC
- VSCode Version: 1.50.0 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. `Ctrl + Shift + F` and search for anything
2. If you click on found result in the search list nothing happens (expected)
3. If you move from one result to the next with Up/Down arrows, files begin opening in the editor (Not expected or desired).

This was still present on the insiders build as well.

I don't recall experiencing this before and seems to be a new experience for me; which is why I feel this is a bug report vs feature request. I take wild advantage of keyboard shortcuts and like to keep my hands on the keyboard so "use the mouse" isn't an attractive workaround for me.

A gif below to help explain better:
![vs-code-search-auto-open](https://user-images.githubusercontent.com/9325163/96012003-46c8ee80-0e09-11eb-89d4-039b2d64d329.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2020-10-16 19:28
This is supposed to happen, the bug would actually be that clicking does not open it. Do you see any errors in the developer tools when clicking? (Help > Toggle Developer Tools)

**Comment by roblourens** [comment] 2020-10-16 23:58
Dupe of https://github.com/microsoft/vscode/issues/108579

**Closed by roblourens** 2020-10-16 23:58 UTC
Labels: needs more info
