### ISSUE TITLE
Inconsistent vscode.Uri.fsPath values for the same document

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#10753] opened 2016-08-21 00:50 UTC
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

I noticed an unfortunate interaction between the MS C++ extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) and one of the popular bookmark extensions (https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) where depending on how you open a document you may get different URIs, ex. /foo/x.cpp if you open the document "normally" (selecting it from the explorer panel) vs. ///foo/x.cpp if the document is opened through "search for symbols".

Steps to Reproduce:

0. Write a simple test extension that logs the arguments to vscode.workspace.onDidOpenTextDocument
1. install the C++ extension mentioned above
2. open the same C++ source file
   a. from the project explorer
   b. search for a C++ symbol (Ctrl-T)

**Comment by bpasero** [comment] 2016-08-21 09:36
@jrieken this smells like https://github.com/Microsoft/vscode/issues/9876

**Comment by jrieken** [comment] 2016-08-22 08:17
Yeah - quite likely

**Comment by jrieken** [comment] 2016-08-22 08:43
dupe of #9876

**Closed by jrieken** 2016-08-22 08:43 UTC
Labels: duplicate
