### ISSUE TITLE
Last git Branch is not visible in "Select a ref to checkout"

### ISSUE THREAD

**Issue by comewhatmay** [microsoft/vscode#114148] opened 2021-01-11 12:38 UTC
- VSCode Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:50.160Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT ia32 10.0.19041

The "Select a ref to checkout" list in VS Code does not show my latest created git branch. 
It looks like that this list does show all branches from the remote repro but not the alphabetically last one. 

Bug Example:
I have a branch named "task/561" but only the following is shown in the list:
- origin/master
- origin/task/560

if I add an additional branch "task/542" my list shows this new branch (but not the also existing task/561):
- origin/master
- origin/task/542
- origin/task/560

Steps to Reproduce:

1. Create a new git branch in Azure DevOps e.g. "task/561"
2. Press the button "Synchronize Changes" in the lower left of VS code
3. Press the button "Checkout Branch/Tag" in the lower left of VS code
4. The shown list does not contain the new branch

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by comewhatmay** [comment] 2021-01-11 12:48
Here are some screen shots: 
from VS code:
![image](https://user-images.githubusercontent.com/24809726/104184292-80fb5980-5413-11eb-9472-ac5427fa264c.png)
from git at the command line:
![image](https://user-images.githubusercontent.com/24809726/104184380-a9835380-5413-11eb-82ba-80c9fd6fdaca.png)

**Comment by eamodio** [comment] 2021-01-13 06:27
Duplicate of #112838

**Closed by eamodio** 2021-01-13 06:27 UTC
Labels: *duplicate
