### ISSUE TITLE
Terminal hover tooltips don't disappear

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#144349] opened 2022-03-03 23:05 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.0-insider (Universal)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T03:14:48.052Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

**Steps to Reproduce:**
1. Open Terminal and type a path that exists on disk
2. Hover over the path

**Expected result:**
The 'open folder' hover disappears

**Actual result:**
It stays there until you hover over the tooltip and out. The same happens for urls.

A bisect gave the following range: 93ce4397a2cbc88707c3ed8b34a813b87457568c...bef4dba21f68bbdb8d9f08fe04b2e1858597722b

https://user-images.githubusercontent.com/2737650/156666617-65009f86-2860-4563-bda4-1425b87bf19d.mp4

**Comment by yume-chan** [comment] 2022-03-04 08:51
Duplicate of #144271

**Closed** 2022-03-04 16:37 UTC
Labels: *duplicate
