### ISSUE TITLE
custom ctrl+shift+u can't be binded

### ISSUE THREAD

**Issue by fikseg** [microsoft/vscode#96536] opened 2020-04-29 07:44 UTC
Issue Type: <b>Bug</b>

It is impossible to assign ctrl+shift+u  key combination. It can't be set via standard settings window. If you try to set it via File-> Preferences -> Keyboard Shortcuts you see combination of 'ctrl+shift+unknown'. If you set it via json config file VS code editor has undifined behaviour in case you activate this key combination. In my case after hitting ctrl+shift+u I see 'u' in editor and can't type in normal way, can't move cursor need to press 'Esc' and 'ctlr+z' several times to continue normal typing. Looks like 'special' editor mode activated.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.0.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.55GB (9.24GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.27.1
synthwave-vscode|Rob|0.1.4

</details>

**Comment by alexdima** [comment] 2020-04-29 12:26
AFAIK, caused by the OS.

Duplicate of #81955
Duplicate of #73003

**Closed by alexdima** 2020-04-29 12:26 UTC
Labels: linux
