### ISSUE TITLE
Use empty title bar on macOS

### ISSUE THREAD

**Issue by lutzroeder** [microsoft/vscode#96817] opened 2020-05-02 03:27 UTC
Wondering if it is possible for the IDE to use empty space in the title bar on macOS? The resize icons seem to not be used very often (?) but the empty title bar is taking up valuable screen real estate.

<img width="1535" alt="screenshot" src="https://user-images.githubusercontent.com/438516/80854016-c1020f80-8be9-11ea-9fe9-1f50c4ea07b0.png">

**Comment by lutzroeder** [comment] 2020-05-02 04:09
https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui makes this possible.

Would this make a good feature to support by default vs. overwriting code by an add-in?

**Comment by yume-chan** [comment] 2020-05-02 14:25
Duplicate of #12377

TL;DR, Code team has not decided what's the best way to do it.

Code team also not recommends modifying UI with extensions.

**Closed** 2020-08-09 22:26 UTC
