### ISSUE TITLE
url parse probleme on ref popup 

### ISSUE THREAD

**Issue by yukulele** [Microsoft/vscode#42303] opened 2018-01-29 10:17 UTC
- VSCode Version: 1.19.3
- OS Version: High Sierra

Steps to Reproduce:

1. install `@types/jquery`
2. place mouse over jQuery method on a .ts file to def popup

Does this issue occur when all extensions are disabled?: Yes

url is bad parsed and open with bracket (in my screenshot : https://api.jquery.com/triggerHandler/} )

![capture d ecran 2018-01-29 a 10 47 28](https://user-images.githubusercontent.com/347244/35505216-b2082880-04e5-11e8-8e87-9e6c8fe2230a.png)

**Comment by mjbvz** [comment] 2018-01-29 16:31
Duplicate of https://github.com/Microsoft/TypeScript/issues/16498

**Closed by mjbvz** 2018-01-29 16:31 UTC
Labels: javascript
