### ISSUE TITLE
Add settings with GUI

### ISSUE THREAD

**Issue by Azhe403** [Microsoft/vscode#22576] opened 2017-03-14 03:38 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Add settings with GUI for VS Code

**Comment by indiejames** [comment] 2017-03-17 17:44
It seems like it would be fairly easy to develop a dynamic GUI for this given that all the settings have a declared type. This is how Atom settings work.

**Comment by wangweixuan** [comment] 2017-05-28 06:30
Duplicate of #3355.

**Comment by mjbvz** [comment] 2017-11-09 01:26
Closing as duplicate of  #3355

**Closed by mjbvz** 2017-11-09 01:26 UTC
Labels: duplicate, feature-request
