### ISSUE TITLE
WebviewPanelSerializer creates a WebviewPanel with options that differ from the original

### ISSUE THREAD

**Issue by vorfol** [microsoft/vscode#80034] opened 2019-08-29 06:24 UTC
- VSCode Version: 1.37.0
- OS Version: Windows 10

Steps to Reproduce:

1. Download and build 'webview-sample' from https://github.com/microsoft/vscode-extension-samples
2. Run debugging and create Cat Coding session.
3. Close debugging VS Code
4. Run it again - Cat Coding session is revived but script is disabled by default: counter isn't changing.

The webviewPanel comes in 'deserializeWebviewPanel(webviewPanel: vscode.WebviewPanel, state: any)' with options that is differ from the original and i cannot adjust it.

**Comment by mjbvz** [comment] 2019-08-29 17:44
Duplicate of https://github.com/microsoft/vscode/issues/78203

Fixed for 1.38 and in insiders

**Closed by mjbvz** 2019-08-29 17:44 UTC
