### ISSUE TITLE
Getting "Visual Studio Code has crashed" a few times

### ISSUE THREAD

**Issue by gwynjudd** [Microsoft/vscode#79] opened 2015-11-18 18:15 UTC
The last three days, when I come into work, I get this dialog. Is there an error log or crash dump I can attach that will help to diagnose?

**Comment by bpasero** [comment] 2015-11-19 07:31
@gwynjudd is this happening when you leave Code running over night e.g.?

**Comment by gwynjudd** [comment] 2015-11-19 07:54
Yes that's when I've noticed it. When I login in the morning it has happened.

**Comment by bpasero** [comment] 2015-11-20 20:07
We need to improve our crash handling to find out what the cause of this crash actually is. This is on our backlog.

**Comment by kurotsukikaitou** [comment] 2015-11-23 10:08
Has the same issue. I'm on Windows 10 Pro 64 bit and the Code always stop working around half an hour or so. Well... It's not responding to any input (although the task manager didn't say "Not responding"). But after a while, the Code will show, "... not responding. Are you want to quit or wait?"-like prompt.

**Comment by bpasero** [comment] 2015-11-23 10:18
@kurotsukikaitou are you editing PHP?

**Comment by kurotsukikaitou** [comment] 2015-11-23 10:20
@bpasero Yes I am. Is there any particular issue regarding php editing?

**Comment by bpasero** [comment] 2015-11-23 12:18
Yes, #160

**Comment by bpasero** [comment] 2015-11-26 19:15
Closing as duplicate of #160.

**Closed by bpasero** 2015-11-26 19:15 UTC
Labels: bug
