### ISSUE TITLE
Typescript Code Lens shows nonsensical references in weird places, such as constructor functions

### ISSUE THREAD

**Issue by craxal** [microsoft/vscode#86956] opened 2019-12-13 19:08 UTC
- VSCode Version: 1.41.0
- OS Version: Windows 10

![image](https://user-images.githubusercontent.com/3473026/70825205-c248b200-1d98-11ea-997e-201e321e0dd3.png)

Notice lines 264 and 278. I do not expect these lines to have Code Lens references.

**Comment by pckilgore** [comment] 2019-12-13 19:45
This also happens in javascript.  Fixed by disabling `javascript.referencesCodeLens.enabled`:

![image](https://user-images.githubusercontent.com/2559043/70827409-cc75ab00-1dae-11ea-80bc-7c6c8454573a.png)

**Comment by mjbvz** [comment] 2019-12-13 19:45
Duplicate of #86495

**Closed by mjbvz** 2019-12-13 19:45 UTC
Labels: new release

**Comment by djmisterjon** [comment] 2019-12-14 08:55
Hey @mjbvz , first thanks for your awesome work on vscode.
But this it a very annoying issue, why it close ? is not fixed on my side. (or i need wait a update soon?)

I wrongly thought that the problem came from another API, but after investigation, it seems that it comes from vscode.
https://github.com/greensock/GSAP/issues/344#issuecomment-565693831

I get weird `CodeLens` at places where it should not appear, it breaks the ergonomics of my project!
From my test, we should no see reference here.
![image](https://user-images.githubusercontent.com/24865815/70846184-baceea80-1e24-11ea-893a-4871a826fd34.png)
