### ISSUE TITLE
Vscode does not open

### ISSUE THREAD

**Issue by Quiago** [microsoft/vscode#214518] opened 2024-06-06 22:15 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. I can't open vscode after the new update, other ubunutu user report the same issue
2.

**Comment by GuySartorelli** [comment] 2024-06-06 22:56
Presumed duplicate of https://github.com/microsoft/vscode/issues/214432

**Comment by deepak1556** [comment] 2024-06-07 02:21
Merging to https://github.com/microsoft/vscode/issues/212494

You can start the application with `--use-angle=swiftshader` as workaround until fix is released.

**Closed by deepak1556** 2024-06-07 02:21 UTC
Labels: triage-needed
