### ISSUE TITLE
Issue with font color when using terminal and ssh connection

### ISSUE THREAD

**Issue by igor0511** [Microsoft/vscode#8002] opened 2016-06-22 13:41 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:

1.  Turn on black theme
2. Start integrated temrinal
3. Log in via ssh to some Linux machine (e.g. CentOS)
4. Type ll (ls -l)

Folder names will be unreadable due to green font color and green font background.

By the way, support for public/private key authentication and storing sites would be just great!

Keep going, this editor is really becoming amazing!!
![issue](https://cloud.githubusercontent.com/assets/11991790/16268722/bb77e5dc-388f-11e6-9913-57472e230857.PNG)
!

**Comment by Tyriar** [comment] 2016-06-23 03:55
Duplicate of https://github.com/Microsoft/vscode/issues/7556

**Closed by Tyriar** 2016-06-23 03:55 UTC
Labels: integrated-terminal
