### ISSUE TITLE
Auto close curly brackets for placeholders in template literals JS/TS

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#47244] opened 2018-04-05 14:56 UTC
Issue Type: <b>Feature Request</b>

```javascript
let str = `$|`;
```

1. Type `{` where the cursor is.
2. No closing bracket

Not sure if it's a duplicate of #25314. This one is about template literal (\`), already typed `$` and, after that, brackets.

**Comment by mjbvz** [comment] 2018-04-05 22:29
Duplicate of #25314

**Closed by mjbvz** 2018-04-05 22:29 UTC
Labels: editor, editor-brackets
