### ISSUE TITLE
Include interactiveEditor.editMode in settingsLayout.ts

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#181278] opened 2023-05-01 22:07 UTC
> `[warning] SettingsEditor2: Settings not included in settingsLayout.ts: interactiveEditor.editMode, accessibility.verbosity.diff-editor, accessibility.verbosity.terminal`

**Comment by jrieken** [comment] 2023-05-02 07:45
@rzhao271 can you help me understand what this means and what needs to be done

**Comment by rzhao271** [comment] 2023-05-02 15:27
Duplicate of https://github.com/microsoft/vscode/issues/181084

**Comment by jrieken** [comment] 2023-05-02 15:34
@rzhao271 not a dupe

**Closed** 2023-05-03 16:09 UTC
Labels: debt
