### ISSUE TITLE
Declarative contribution of custom explorers (based on tree models)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12163] opened 2016-09-16 18:02 UTC
Allowing extensions to contribute a file explorer-like viewlet would enable some interesting features such as:
- Outline views that display symbols from the opened file
- Custom file explorers, for example a file explorer that tightly integrates with source control
- Database explorer
- More cool stuff pulled from people's imaginations

Related issues:
- Feature request: symbols tree view https://github.com/Microsoft/vscode/issues/5605
- Feature Request: File Outline View for TypeScript https://github.com/Microsoft/vscode/issues/10788
- Feature Request: SVN Support https://github.com/Microsoft/vscode/issues/206
- Add outline view. https://github.com/Dart-Code/Dart-Code/issues/107
- add functionality to show the type hierarchy https://github.com/Dart-Code/Dart-Code/issues/133

**Comment by joaomoreno** [comment] 2016-09-22 08:23
I'm finding a lot of trouble understanding how the jump from _**declarative contribution of custom explorers (based on tree models)**_ to _**Expose API to create a custom explorer viewlet**_ happened.

It is my strong belief that we should **not** allow extensions to create new viewlets.

I'll go through each of the related issues, one by one:

- #5605, with 30 up votes and currently number 21 on the top up voted feature requests. 
- #10788 seems just to be a duplicate of the previous one.
- #206, with 70 up votes, currently number 7. SVN support would never come as a new viewlet: it would simply appear as a new backend to the existing Git viewlet, fully rebranded as a source control viewlet. In the exact same way that the go debugger coexists with the node debugger in the same viewlet.
- Dart-Code/Dart-Code#107 seems to just be a duplicate of the first one.
- Dart-Code/Dart-Code#133 seems to just be a duplicate of the first one.

In essence, the whole thing seems to be only about symbols tree, so why not just focus on that problem? 

A symbols tree view is seldom used for anything other than **navigation**. Putting it in a viewlet is a preference of few, but likely just wasted space for most. Having it in quick open fashion is what solves it for 90% of the situations: a way to quickly navigate to another type. We already have this in Quick Open, albeit as a flat list. So, let's allow quick open to show items as a tree. Still want a persistent view? Write an extension which renders it in an editor pane and place that on the side of your editor. Want it in the viewlet pane? Let's make the explorer _explore_ more than files.

But [one doesn't simply open the door to our UI kingdom](http://vignette4.wikia.nocookie.net/factpile/images/6/66/Lotr-boromir-1280jpg-b6a4d5_1280w.jpg/revision/latest?cb=20160331232305).

On to my closing arguments:

Throughout this project, the most interesting question that I always seem to go back to is: what differentiates Code from its competition? Following that train of thought I ask myself in what way does an editor differentiate from an IDE? Where can we draw that line? Is Code either or a bit of both?

I come to the conclusion that it's been our ability and willingness to responsibly say **no** to certain feature requests, while obviously providing acceptable alternative solutions, that has made us grow Code successfully.

**Comment by jrieken** [comment] 2016-09-22 08:44
I fully agree on growing existing principles and concepts over introducing new ones. It's clearly harder but IMO yields in a better product. We should keep up the "art of saying 'no'". Or better put in this [HN comment](https://news.ycombinator.com/item?id=12459215): 

> Whoever is in charge certainly has a vision, because this sort of app could easily get wrecked by going in too many directions at once. Keep up the great work and keep on that strategy of not listening to every single person's input ;)

**Comment by MeirionHughes** [comment] 2016-09-22 10:21
So long as you can add whatever content you like into the viewlet, it should be fine. Personally I want to add buttons to the viewlets that can be user/workspace configurable.

**Comment by niieani** [comment] 2016-09-22 15:32
@joaomoreno Regarding your question: "what differentiates Code from its competition", I would have to disagree with your proposed answer. In my view the answer is:

- very fast startup and very responsive down the line (used to be Sublime's prerogative)
- easily extensible using a sane and popular extension language, JavaScript or TypeScript extensions (used to be Atom's prerogative)
- amazing team, which means very fast development and bug-fixing speed (beats Atom by a bit and kills the snail-like Sublime's development speed)
- great stability (used to be Sublime's prerogative)

While "saying **no** to certain feature requests" is definitely an important factor in the development of any product, including VSCode, I don't think it's even a minor differentiating factor for VSCode. In fact, in my view, saying **no** to feature requests is much more about triaging what should be done **now**, and what **later**, not about what should and should never be done. Saying "never" to any feature by extension alienates groups of developers, who wish for certain functionality. Say: "not now, there are more important things to do now!" instead!

But that's just my humble opinion, maybe I'm wrong. :) You do what you must, cause [you're still the best OSS team](https://github.com/Microsoft/vscode/issues/10145#issuecomment-245310694) in my book. 🐝

**Comment by rebornix** [comment] 2016-09-22 16:20
My two cents here: Basically I agree with @joaomoreno 's concern about allowing users to create custom viewlets.

The first time I heard about this plan, the first idea came to my mind is 

> What kind of interesting extensions can I create with this kind of new API?  TODO list, Seven day whether forcase, etc? Can I leverage this API to write another File Explore to replace the original one?

which has nothing to do with the original feature request: Symbols Tree View or Outline View. To some extent, this give people freedom to customize Code and always cultivates creativity but this makes me worried about whether we are doing too much and maybe we should just focus on improving Symbols/Outline navigation.

Secondly, we do have symbols navigation builtin but it took me a long time to find that feature: I was attempt to open files by pressing `Ctrl-O` but my big fingers pressed `Ctrl-Shift-O`,  that's how I found this feature accidently. Not quite sure whether other people find this feature discoverable but to me it's not. So before we think of a new way to help people quick navigate through Symbol Tree View, maybe we need to analyze how frequent `Quick Open Symbol` is used and whether people like it.

**Comment by kieferrm** [comment] 2016-09-22 18:29
There are a few different issues covered in the comments above. So, let me try to fiddle them apart and shed some light on them.

1. Is the description of this item the correct representation of what is happening in the exploration? **Answer**: No, because it states facts rather than posing questions.
1. Will we expose API for custom viewlets in our September release? **Answer**: No.
2. Should we explore if it makes sense to give extensions a way to contribute custom explorers in a declarative way and with minimal API exposure? **Answer**: Yes. There is class of extensions that otherwise will have to misuse existing mechanisms. This exploration is happening in September and will continue in October.
3. If we would end up allowing custom explorers, would we mindlessly let them clutter our UI? **Answer**: No. We can implement proper default behavior about when a custom explorer shows up, how to manage visibility in general, etc.
4. Is the outline view the main motivation for this work? **Answer**: No. A better way to think about it is database explorers.

**Comment by Tyriar** [comment] 2016-09-22 18:39
I clarified the title and issue description, I was leaving it up to an investigate whether it would be an API or contribution (since contributions are part of the API).

**Comment by MeirionHughes** [comment] 2016-09-22 18:43
I'd like to point out that my original request was for facilitating custom buttons on the activity bar (#10709). That was closed in favor of exposing the activity bar api (#8511) which was then closed in favor of this feature-request. How this is down as "custom explorer"... so either this issue should be "Custom viewlet (any content)" or please reopen #8511

**Comment by octref** [comment] 2016-09-22 18:59
@MeirionHughes 

If your case is `npm publish`, wouldn't it be better for you to create a custom quick open using `window.showInputBox`?

This way you can also add `npm install`, `npm install global`, etc.

**Comment by MeirionHughes** [comment] 2016-09-22 19:07
That is just an example. The idea is to allow users to do _rudimentary_ customization of the UI to add command of their choosing to simplify their workflow. 

You mentioned in the other issue that this api would facilitate a) a custom button on the left activity bar that b) opens up a fully customisable viewport on the sidebar. With that that I could create an extension to create a viewport that had cli buttons and information for say Angular-2, Aurelia or React. Aurelia, for example has a cli to add components, converters and custom attributes to a project. Buttons for those could be added with a truly customisable viewport.

**Comment by Tyriar** [comment] 2016-09-22 19:13
@MeirionHughes please don't derail the conversation, I went over in depth why we would not allow arbitrary command through activity bar buttons in https://github.com/Microsoft/vscode/issues/10709#issuecomment-241902257

**Comment by MeirionHughes** [comment] 2016-09-22 20:05
I'm not derailing anything; I'm merely stating what I would do with this feature if it does what #8511 implied (customisable viewports opened by an activity-bar button), which is relevant here as you closed #8511 in favor of this. 

So to clarify, does this issue facilitate adding an activity-bar item, which when clicked will open a custom viewport (like the debug viewport), the content of which is customisable by the extension author to be,  and do, whatever they like?

**Comment by Tyriar** [comment] 2016-09-22 20:10
Examples of what you would be able to implement are in the top issue description; a new button on the activity bar which is linked to a new viewlet (sidebar) that has some tree structure in it. The main thing clarified so far from the discussion is the way in which extensions would register the viewlet (contribution vs API call).

**Comment by dbaeumer** [comment] 2016-09-23 07:24
VS Code is all about supporting the inner development loop of edit, compile, debug & release. Features which are not in that inner loop should IMO not be added to VS Code 'main window', even not as an extension. The only feature I currently miss in that inner loop is testing and this would require another kind of view.

A database explorer is IMO like a Azure storage explorer and for me doesn't belong into the inner loop. And I believe a good database explorer doesn't stop with a 'Explorer' view. It needs a special editor a REPL, ... 

So instead of allowing extension to contribute to the 'main window' we should allow them to open a second render window 'on the same workspace' and support some kind of state sharing between them. An example is propagating the active selection so that a database explorer could evaluate a 'Selected' SQL statement.

I know that this is a lot more work to do (we need a common widget set to get homogenous UI, we need a communication mechanism, ....) then allow contributing a explorer view but it will allow for better extension UI without opening too many doors in the VS Code main window itself.

**Comment by bpasero** [comment] 2016-09-23 12:56
I second what @dbaeumer is saying but would like to add that imho such a tool that opens in a new window should just be a standalone application that I can run even when VS Code is not running or not installed. 

If I decide to have both VS Code and this tool installed at the same time, then I do believe that both should share a set of services for reuse and some kind of UI integration. E.g. it makes sense to have an action in VS Code when editing a SQL script to show a preview of the script in the other tool that was designed for presenting table data.

Overall I would like these apps to have a consistent look and feel. If I look at Office applications, they decided to not put everything into a single application but instead create a brand and set of applications that all share a common look and feel. It seems natural to me that such a concept would also work nicely with developer tools.

**Comment by Tyriar** [comment] 2016-09-25 04:34
@dbaeumer that is just one example of something one could do with such an API, Outline view is just one example that is clearly within the edit portion of your inner development loop.

This is also about extensions contributions, so any such viewlet would be opt-in by a user *who wants it*. The main downside I see in this is that it demands we commit to and maintain the API which may slow development and/or our mobility when it comes to changing the UX.

**Comment by Thaina** [comment] 2016-09-29 01:24
With this feature do you think it possible to extend current explorer?

Such as git explorer extend to support SVN. Instead of separate tab

**Comment by Thaina** [comment] 2016-10-01 12:20
@dbaeumer I think vscode concept of `inner development loop of edit, compile, debug & release` is fine.

But the point is, the code that we want to grab for `edit, compile, debug & release` could be anywhere. It could be json in database. It could be function on azure. It could be html on github.io. And we just want to  edit it remotely instead of download all things into local filesystem

Actually there is whole lot of possibility that the code we want to develop maybe need a custom way to explored. Both on the cloud or deep down in the code

Actually I have one idea and need to use custom explorer and virtual file editor. I want to make extension to edit javascript in html file (It still not support)
I want to make an explorer that read all script and style tag in html, make a symbol explorer for edit those as js and css. But because vscode not support both I need to wait for supporting edit js in html. Instead I could work right now

Your limit of freedom block me from `inner development loop`

**Comment by rmunn** [comment] 2016-10-28 01:19
The use case I want to see, which nobody has mentioned yet, is being able to manage the contents of an F# project file. In C#, file order in the .csproj file doesn't matter, but in F#, the .fsproj file needs to specify the source files *in dependency order*. If you have Model.fs, ViewModel.fs, and View.fs, and View depends on ViewModel which depends on Model, then you must specify Model.fs first in the file, ViewModel.fs second, and View.fs third. Currently when I add a new file to the project, or if I create a new dependency that requires re-ordering the .fsproj file order, I have to edit the .fsproj file myself. This works, but I would far rather be able to just click on the project tree view, right-click on the project icon, and choose "Add new file to project" from a popup menu. Or to reorder a file, I'd like to click on that file in the project tree view and hit Alt+Up or Alt+Down. I don't want to have to edit the .fsproj file, with its ugly XML syntax, by hand -- I'd like the Ionide plugin to be able to provide tools to do it for me. In order to provide those tools, Ionide will need VS Code to support an arbitrary tree view so it can display a tree representation of the .fsproj file.

**Comment by octref** [comment] 2016-11-14 18:25
#14048 has landed on Insider. Doc is coming soon.

**Closed by octref** 2016-11-14 18:25 UTC
Labels: api, feature-request

**Comment by capaj** [comment] 2017-01-05 22:39
@octref how about those docs? Are they somewhere? I'd love to add a new Viewlet on the sidebar(activity bar) but I really don't know how. I tried looking for the code that adds those default 5 items, but could not find it. Could you at least point me to it?

**Comment by Tyriar** [comment] 2017-01-06 00:55
@capaj check out the sample extension here https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample

Take note of the `"enableProposedApi": true` in the package.json, you need this for it to work.

**Comment by octref** [comment] 2017-01-06 01:34
@capaj Some docs are at: https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-explorer-sample/USAGE.md

**Comment by capaj** [comment] 2017-01-06 08:59
@Tyriar awesome sample. I am a little bit confused as to how can I put any arbitrary content in there-so far it seems to be only made for tree explorers-seems weird that you would not allow any arbitrary DOM there. That would be something I'd like to do. This seems overly limiting.

`vscode.window.registerTreeExplorerNodeProvider`

**Comment by octref** [comment] 2017-01-06 09:02
@capaj 
That is as-designed, see:
https://code.visualstudio.com/docs/extensions/our-approach

> VS Code has a very rich extensibility model and there are many ways to extend the tool. However, we do not provide direct access to the underlying UI DOM to extension writers. With VS Code, we’re continually trying to optimize use of the underlying web technologies to deliver an always available, highly responsive editor and we will continue to tune our use of the DOM as these technologies and our product evolve. To maintain performance and compatibility, we run extensions in their own host process and prevent direct access to the DOM. VS Code also includes a built-in set of UI components for common scenarios such as IntelliSense, so that these experiences are consistent across programming languages and extensions and extension developers do not need to build their own.

> We realize that this approach may initially feel restrictive to extension developers. We’re always looking for ways to improve our extensibility model and expand the capabilities available to extensions. We look forward to hearing your feedback and ideas.

**Comment by capaj** [comment] 2017-01-06 09:07
@octref thanks for a link. Did not read that before. This is definitely safer approach. Even if it is quite limiting.
