### ISSUE TITLE
Different colored area on macOS

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#152816] opened 2022-06-22 00:36 UTC
Fired up vscode on my personal m1 mac for the first time in awhile.

Seeing discoloration in the rendering surrounding the area. I cannot see anything in the DOM that would explain this different colored section. I do not see this on my intel macbook which is settings synced to my M1 machine such that all extensions and settings are the same.

<img width="907" alt="black box 1" src="https://user-images.githubusercontent.com/4544166/174918721-9db4dccd-c7a5-429c-9a3a-fce992ba158c.png">
<img width="907" alt="black box 2" src="https://user-images.githubusercontent.com/4544166/174918725-fa31506f-9f5b-42ff-b311-4ea3e2326d53.png">

@deepak1556 I assigned you because I figured this might be an electron thing with rendering feel free to reassign or let me know how I may help debug.

**Comment by MitchLenton** [comment] 2022-07-07 20:50
This happens to me with an intel mac as well. It was fixed by setting `"disable-hardware-acceleration": true` in the `.vscode/argv.json` file.

**Specs**
Intel MacBook Pro
macOS 12.2.1

**Comment by lramos15** [comment] 2022-07-07 20:52
> Issue #154387 was marked as a duplicate of this one, however, I _do_ see the issue on an Intel MacBook. `--disable-gpu` stops the weird rendering from occurring.

I've renamed the issue to discuss both versions of macOS. The reason I named it M1 mac at first is I cannot repro this on my intel mac but can on my M1 machine

**Comment by A-Yaskevich** [comment] 2022-07-07 21:51
> > Issue #154387 was marked as a duplicate of this one, however, I _do_ see the issue on an Intel MacBook. `--disable-gpu` stops the weird rendering from occurring.
> 
> I've renamed the issue to discuss both versions of macOS. The reason I named it M1 mac at first is I cannot repro this on my intel mac but can on my M1 machine

I have Intel MAC, but facing the same problem

**Comment by deepak1556** [comment] 2022-07-08 02:37
Very likely a regression in the disable color correct rendering patch maintained by electron. Confirmation pending.

**Comment by kythuatwebso** [comment] 2022-07-08 06:10
My issues not fix:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/57938377/177927830-a8089c15-7684-4fb1-aabd-25f524ac2804.png">

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/57938377/177927864-bfbaa14b-362b-45bd-b34f-29f0f39af458.png">

**Comment by Kyngo** [comment] 2022-07-08 07:06
> This happens to me with an intel mac as well. It was fixed by setting `"disable-hardware-acceleration": true` in the `.vscode/argv.json` file.
> 
> **Specs** Intel MacBook Pro macOS 12.2.1

I had this enabled and still can see this glitch. M1 Mac Mini here. Can confirm that running `code --disable-gpu` on terminal opens the editor without this glitch.

**Comment by hua03** [comment] 2022-07-08 07:44
#154462

**Comment by hua03** [comment] 2022-07-08 07:52
> > This happens to me with an intel mac as well. It was fixed by setting `"disable-hardware-acceleration": true` in the `.vscode/argv.json` file.
> > **Specs** Intel MacBook Pro macOS 12.2.1
> 
> I had this enabled and still can see this glitch. M1 Mac Mini here. Can confirm that running `code --disable-gpu` on terminal opens the editor without this glitch.

It works for me. I'm intel chip and macOS 10.15.6.

**Comment by its-codetime** [comment] 2022-07-08 16:12
Both of the methods listed above did not work for me. I'm on an intel mac(monterey 12.2.1).
What did work is removing ```"disable-color-correct-rendering": true``` from ```~/.vscode/argv.json``` file and restarting vscode. Now the different coloured patch on the side and bottom is gone.

**Comment by RickyRomero** [comment] 2022-07-08 18:22
I've noticed a situation where this issue doesn't appear which may help the team debug it.

For me, this problem *disappears* when my Mac's display is set to the sRGB color profile (System Preferences > Displays > Display Settings... > Color Profile > sRGB IEC61966-2.1). After relaunching VS Code, the bug doesn't reappear.

So, it appears this issue is indeed related to mismatched color profiles somewhere in the rendering pipeline.

macOS Monterey 12.4 / Apple M1 Max / VS Code 1.69.0

⚠️ **I don't recommend others use this as a solution, as it may prevent accurate color rendering across the entire OS.**

**Comment by shensven** [comment] 2022-07-09 05:14
same problem

**Comment by anthony-ab** [comment] 2022-07-09 07:10
Had the same problem on my M1 macbook air, I had to open the argv.json file (you can use `Shift + CMD + P` and type `Configure Runtime Arguments` to open it) and set this line to false : 

```json
"disable-color-correct-rendering": false
```

(it was on true, maybe by default).

After that, just close your VS Code instance with `CMD + Q` and restart it.

**Comment by BenCully** [comment] 2022-07-11 18:36
> Had the same problem on my M1 macbook air, I had to open the argv.json file (you can use `Shift + CMD + P` and type `Configure Runtime Arguments` to open it) and set this line to false :
> 
> ```json
> "disable-color-correct-rendering": false
> ```
> 
> (it was on true, maybe by default).
> 
> After that, just close your VS Code instance with `CMD + Q` and restart it.

Mac Pro (Late 2013) Intel Xeon + Radeon GPU
Mac OS 12.4
VSCode Version: 1.69.0 (Universal)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9

This worked perfectly for my older Intel Mac

**Comment by xterler159** [comment] 2022-07-11 19:19
Same here. 
Macbook pro with M1 pro 

but @anthony-ab's solution is working so ..

**Comment by fatihgnc** [comment] 2022-07-11 19:52
> Had the same problem on my M1 macbook air, I had to open the argv.json file (you can use `Shift + CMD + P` and type `Configure Runtime Arguments` to open it) and set this line to false :
> 
> ```json
> "disable-color-correct-rendering": false
> ```
> 
> (it was on true, maybe by default).
> 
> After that, just close your VS Code instance with `CMD + Q` and restart it.

I use Macbook Air M1 and this worked perfect for me! Thanks.

**Comment by macCesar** [comment] 2022-07-12 02:08
```json
"disable-color-correct-rendering": false

```

Worked for me on my M1 Mac mini !!!

**Comment by Enubia** [comment] 2022-07-12 06:12
> Had the same problem on my M1 macbook air, I had to open the argv.json file (you can use `Shift + CMD + P` and type `Configure Runtime Arguments` to open it) and set this line to false :
> 
> ```json
> "disable-color-correct-rendering": false
> ```
> 
> (it was on true, maybe by default).
> 
> After that, just close your VS Code instance with `CMD + Q` and restart it.

MacPro 2021
Chip M1 Pro
VSCode Version: 1.69.0 (Universal)

Works perfectly

**Comment by nonrice** [comment] 2022-07-13 13:28
Tried everything offered in the current solution (`force-color-profile`, `disable-color-correct-rendering`). Faded colors issue still persists.

**Comment by bpasero** [comment] 2022-07-13 13:41
@nonrice to clarify, do you see the same when opening https://insiders.vscode.dev/ in Chrome/Edge?

**Comment by nonrice** [comment] 2022-07-13 15:54
Yes, it has the same effect.

**Comment by jdelano0310** [comment] 2022-07-15 09:50
I had the same thing happen using VS Code in a Win 10 Virtualbox, hosted on Windows 10, I turned off 3D acceleration for the VM and that fixed it for me. Ryzen 7 3800X based PC.

**Comment by xenostar** [comment] 2022-07-18 19:27
This is happening again as of this morning for me. Was fixed for a little while.

**Comment by jeremyn** [comment] 2022-07-18 21:25
@jdelano0310 If you're seeing graphical glitches such as I described above in https://github.com/microsoft/vscode/issues/152816#issuecomment-1179023320, please also see issue https://github.com/microsoft/vscode/issues/154705. So far everyone on that issue is using Linux in a VMware guest but maybe the problem you're seeing with Windows+VirtualBox is related.

**Comment by JackyChan** [comment] 2022-07-21 03:40
> Had the same problem on my M1 macbook air, I had to open the argv.json file (you can use `Shift + CMD + P` and type `Configure Runtime Arguments` to open it) and set this line to false :
> 
> ```json
> "disable-color-correct-rendering": false
> ```
> 
> (it was on true, maybe by default).
> 
> After that, just close your VS Code instance with `CMD + Q` and restart it.

Awesome, work for me.

**Comment by eduard-ungureanu** [comment] 2022-07-25 09:25
None of the above options worked for me on a MacBook Air M1, except by editing the file `~/.vscode/argv.json` and commenting out this line of code:
```
"disable-color-correct-rendering": true
```

![Code - argv json — Divi](https://user-images.githubusercontent.com/1719735/180744213-8e6609f6-62c1-412e-b982-9c110d29413b.jpg)

**Comment by barrd** [comment] 2022-08-04 19:36
Fixed in 1.70.0 release Apple Mac, Intel macOS Monterey

**Comment by outaTiME** [comment] 2022-08-04 19:43
Not working for me 🤔

**Comment by RickyRomero** [comment] 2022-08-04 19:45
1.70.0 fixed it for me too!

**Comment by carlosbelardi** [comment] 2022-08-08 17:59
I'm still seeing super faded colors on 1.70.0 on my 16-inch M1 Mac. For context my theme is One Dark Pro Darker, and this is what my `argv.json` file looks like. I've tried other themes and it looks a bit better? So not super sure if the issue is with One Dark Pro

<img width="727" alt="Screen Shot 2022-08-08 at 12 58 08 PM" src="https://user-images.githubusercontent.com/17284633/183482970-da4e6e9f-a316-4849-ba9c-4359589c8ee0.png">

**Comment by Enubia** [comment] 2022-08-12 11:54
> 

Can confirm this behavior, at first glance everything seems fine but if you look close the colors are still messed up. It's just not as present as it was before the release that "fixed" it.

After setting ```"disable-hardware-acceleration": true``` it was fine again.
I removed the setting again and it stayed "fixed", at least for now.

Whatever's causing this, in my case disabling and enabling hardware-acceleration fixed it.

**Comment by jenky** [comment] 2022-08-18 10:11
> I'm still seeing super faded colors on 1.70.0 on my 16-inch M1 Mac. For context my theme is One Dark Pro Darker, and this is what my `argv.json` file looks like. I've tried other themes and it looks a bit better? So not super sure if the issue is with One Dark Pro
> 
> <img alt="Screen Shot 2022-08-08 at 12 58 08 PM" width="727" src="https://user-images.githubusercontent.com/17284633/183482970-da4e6e9f-a316-4849-ba9c-4359589c8ee0.png">
> 
> Not sure how visible it is in these screenshots, but text that should be red looks almost like a rust orange, and the green and blue text also looks very dull/faded compared to how it was about a month ago.
> 
> <img alt="Screen Shot 2022-08-08 at 1 00 23 PM" width="712" src="https://user-images.githubusercontent.com/17284633/183483828-c86004e0-e834-42e8-b71b-34054df6d038.png">
> 
> I first noticed this a few weeks ago, and adding `"disable-hardware-acceleration": true` to my `argv.json` file fixed it, but that's no longer the case

I had the same issue, except that "disable-hardware-acceleration" nor "disable-color-correct-rendering" works for me. Everything was fine in 1.68

**Comment by alxlacayo** [comment] 2022-09-08 05:42
I'm also getting washed out colors on my late 2015 imac

**Comment by kydva** [comment] 2022-09-13 16:02
"disable-hardware-acceleration" and "disable-color-correct-rendering" didn't work for me too.

**Closed** 2022-12-13 13:14 UTC
Labels: bug, upstream, macos, electron, confirmed, electron-18-update
