### ISSUE TITLE
Remove Definitions from References

### ISSUE THREAD

**Issue by esemlabel** [microsoft/vscode#68071] opened 2019-02-07 10:17 UTC
From Intelephence [#171](https://github.com/bmewburn/intelephense/issues/171):

Remove Definition from Reference list, since there are different.
Defined functions or methods should'n appear in reference list, because they'r not references and available from separate menu Go/Peek Definition or within shortcut.

> @[bmewburn](/bmewburn)
Version 1.0 will respect the value of `ReferenceContext.includeDeclaration` which is sent with the `textDocument/references` request. In my tests vscode sends true for this value when finding references so definitions/declarations will be included. Please file an issue against the vscode repo if you think this should be changed.

Similar to #18338, but required for **PHP** as well.

- VSCode Version: 1.30.2
- OS Version: OS X 10.11.6

**Comment by mjbvz** [comment] 2019-02-07 18:34
I don't understand this ask. Can you please provide an example

**Comment by esemlabel** [comment] 2019-02-07 20:16
> I don't understand this ask. Can you please provide an example

Here's an example of sample php code with function definition and 2 calls after.

<img width="454" alt="2019-02-07 21 13 57" src="https://user-images.githubusercontent.com/17903845/52436570-531d8400-2b1d-11e9-8615-9b26fcccaad6.png">

There are 4 actions on functions or methods we can perform to get definition or references from context or with shortcuts, which have to do the following, when placing cursor, for example, under the last `test` occurrence:

1. Go to Definition.
Place cursor under `function test` on line 4.

2. Peek Definition.
Show function definition on line `4` in popup window.

3. Find All References.
List 2 references on line `8` and `11` in Reference Search View in Sidebar.

4. Peek References.
List 2 references on line `8` and `11` in popup window.

But when you want to list all references in sidebar (3) or in popup (4), not only `8` and `11` line will appear in the list, but the line `4` with function definition as well. This is wrong because function definition is not a reference and it should'n appear in the references list.

<img width="461" alt="2019-02-07 22 06 41" src="https://user-images.githubusercontent.com/17903845/52439621-b1019a00-2b24-11e9-8918-612fea0a6ade.png">

The similar problem with TS language were discussed in #18335 and fixed in #18338.
The same problem exists in PHP language right now, so we need fix it as well.

**Comment by jrieken** [comment] 2019-08-29 10:37
closing as duple of #74237

**Closed by jrieken** 2019-08-29 10:37 UTC
Labels: editor-symbols, feature-request, references-viewlet

**Comment by sean-mcmanus** [comment] 2019-09-13 19:46
I assume you marked this as a duplicate of https://github.com/microsoft/vscode/issues/74237 under the intention that "definition" would be considered a "type"?

Specific language extensions themselves could filter out the Definitions if they wanted to and it wouldn't need to be handled by VS Code itself. With the C/C++ extension and in VS, we treat definitions and declarations as just another "confirmed reference" type with no property or filter for defintion, declaration, or usage -- we could add it though: I've filed a feature request at https://github.com/microsoft/vscode-cpptools/issues/4245 .
