### ISSUE TITLE
[html] Support drag-and-drop (using Shift) into HTML file, equivalent to Markdown files

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#181653] opened 2023-05-05 16:49 UTC
Markdown already supports Shift+drag-and-drop for files, with special support for pictures and video (and, [potentially](https://github.com/microsoft/vscode/issues/181652), audio).

HTML should support the same functionality: for pictures, insert an `img` tag, for video a `video` tag, for audio an `audio` tag, and for anything else an `a` tag.

**Comment by mjbvz** [comment] 2023-05-09 18:40
Duplicate of #5772

**Closed** 2023-05-10 07:45 UTC
