### ISSUE TITLE
[Request] Character positions to improve fold text

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#111064] opened 2020-11-20 23:26 UTC
This is similar to https://github.com/microsoft/vscode/issues/50840 , but does not require supporting multiple folding ranges within the same line.  Rather, this request is to accept character positions referring to the first and last lines of existing line-granular folding ranges, used only for the purpose of composing the fold text.

Our provider folds blocks down to a single line.  For example:

```
if (b)
{
}

if (b) {
}

do {
    int i;
} while (b);

{
}
```

Currently fold down to:
```
if (b)...

if (b) {...

do {...

{...
```

Note that some syntax can lead to omitting code that wasn't intended to be folded, or showing unmatched braces.

We also have an issue due to the fact that a range may start or end in the middle of a line.  For example:

```
    if (b) { int i;
    } else {
    }

    {
    int j; } int k;
```

Folds into:

```
if (b) { int i;...
}

{...
```

Suggestion: accept start and end character positions for the folded range, and use them to infer the appropriate text to display before and after the fold.  For example:

```
if (b) { int i;
    int i;
int k; } // comment
```

For the above, we would provide a range of lines 0-2 (all of it), but would indicate start position 8 and end position 7.  VS Code could use this info, and existing colorization information, to build the fold text:

```
if (b) {...} // comment
```

Similarly, it would clean up:

```
do {
    int i;
int kj; } while (b);
```

Such that it's displayed as:

```
do {...} while (b);
```

**Comment by aeschli** [comment] 2020-11-23 07:56
We currently have no plans for inline foldings. It would require some major work on the editor widget side.
Duplicate of https://github.com/microsoft/vscode/issues/50840

**Closed by aeschli** 2020-11-23 07:56 UTC
