### ISSUE TITLE
Enabling "Close all to the left" in tab context menu

### ISSUE THREAD

**Issue by filipesmedeiros** [microsoft/vscode#114859] opened 2021-01-24 13:36 UTC
Hey! First of all, love VS Code!

# Problem

I've seen that an issue with this has been opened, but it was never even answered and it was closed automatically.

I think this is a very simple thing to implement, since it's already present in the Command Palette.

Close all to the left action -> https://github.com/microsoft/vscode/blob/64a14963f7b9a273ebadd51d7efca6cd4604cfd1/src/vs/workbench/browser/parts/editor/editorActions.ts#L506

Adding it to the Palette -> https://github.com/microsoft/vscode/blob/64a14963f7b9a273ebadd51d7efca6cd4604cfd1/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L332

# Solution

Add this action to the tab context menu -> https://github.com/microsoft/vscode/blob/64a14963f7b9a273ebadd51d7efca6cd4604cfd1/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L652
And add here below this also? -> https://github.com/microsoft/vscode/blob/64a14963f7b9a273ebadd51d7efca6cd4604cfd1/src/vs/workbench/browser/parts/editor/editorCommands.ts#L817

**Comment by filipesmedeiros** [comment] 2021-01-24 13:38
Btw I'd love to contribute but the workflow seems a bit more complicated than I have time for right now, so maybe someone who already has contributions  for the repo a bit more streamlined can grab this one easily?

**Comment by yume-chan** [comment] 2021-02-09 06:58
Duplicate of #116165 since that one has a linked pr #116166

**Closed** 2021-03-28 02:35 UTC
Labels: feature-request, workbench-tabs
