### ISSUE TITLE
The program have a high CPU utilization rate and memory!!!

### ISSUE THREAD

**Issue by fwgood** [Microsoft/vscode#37825] opened 2017-11-08 15:27 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.close vsc
2.reopen vsc 

when i delete all plugins,it got right,but before long it reappear again.And it works lag .
![1ekb6a6c5rd wg _n21 gjq](https://user-images.githubusercontent.com/16516811/32556823-68462994-c4db-11e7-8819-3f0d63381c8b.png)

there are my plugins:
![image](https://user-images.githubusercontent.com/16516811/32557163-5492fea8-c4dc-11e7-82b9-c2da3e738fa5.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment] 2017-11-09 06:28
- Are you opening a large project? 
- Are there symlinks in the folder?
- Which version of Windows?

**Comment by fwgood** [comment] 2017-11-09 14:54
![image](https://user-images.githubusercontent.com/16516811/32611221-00a88ae6-c5a0-11e7-8182-74d543a8af9f.png)

- my project and it is small.
- there are many symlinks in the folder named node_modules.
- the windows version is win10(1709) and the vsc version is 1.17.2

**Comment by roblourens** [comment] 2017-11-09 16:51
Ok, this is a duplicate of https://github.com/Microsoft/vscode/issues/35659#issuecomment-338682602. Another workaround is, set `"search.followSymlinks": false`, after updating vscode to 1.18.

**Closed by roblourens** 2017-11-09 16:51 UTC
Labels: freeze-slow-crash, search
