### ISSUE TITLE
Enable/Disable Set of Extension With a Click of a Button

### ISSUE THREAD

**Issue by Laraveldeep** [microsoft/vscode#128086] opened 2021-07-06 23:23 UTC
The choice to enable only the needed set of extensions with a click of a button would be great. 

So depending upon the project, when I select "**enable python project extensions**" will disable all other (PHP/Laravel/Vue, etc.) extensions not needed for the project right now.

Of course, we need a way to **map** the extensions we install to our **custom labels** (or whatever we call that)

**Comment by yume-chan** [comment] 2021-07-07 02:44
Duplicate of #40239

**Closed** 2021-07-07 12:26 UTC
Labels: *duplicate
