### ISSUE TITLE
TypeScript: Debugger runs the .ts file instead of the .js

### ISSUE THREAD

**Issue by jbialobr** [microsoft/vscode#104648] opened 2020-08-14 11:31 UTC
- VSCode Version: 1.48
- OS Version: win10

Steps to Reproduce:

1. Run debugger
Configuration:

```json
  "configurations": [
    {
      "name": "Launch backend",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/src/main/js/index.ts",
      "outFiles": [
        "${workspaceRoot}/dist/src/main/js/index.js"
      ],
```
Actual behavior:

![image](https://user-images.githubusercontent.com/1003909/90245079-4379ac80-de32-11ea-9875-ceb7091f437f.png)

Expected behavior (as in 1.4.7)

![image](https://user-images.githubusercontent.com/1003909/90245111-52f8f580-de32-11ea-8969-652d2c41982c.png)

Does this issue occur when all extensions are disabled?: Yes

It works as expected in the 1.4.7 version.

**Comment by connor4312** [comment] 2020-08-14 15:26
We have a duplicate of this in https://github.com/microsoft/vscode/issues/102873#issuecomment-671631175, however I've been unable to reproduce it. Can you provide more some additional on that thread?

Also, as a workaround, you can also set your `program` to run the compiled file, rather than the source file.

/duplicate

**Closed** 2020-08-14 15:27 UTC
Labels: *duplicate, debug

**Comment by jbialobr** [comment] 2020-08-15 05:14
I am not sure this is a duplicate.
My case works in the 1.47.3 version and the error in 1.48.0 is different:
```
C:\Program Files\nodejs\node.exe .\src\main\js\index.ts
Debugger listening on ws://127.0.0.1:59440/1f30da8f-b785-4778-9df8-7d8df96fde13
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
G:\fakepath\src\main\js\index.ts:1
import * as tracerImport from '@google-cloud/trace-agent';
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Waiting for the debugger to disconnect...
Process exited with code 1
```

When I change the program entry point to the .js file it works. It uses a relative path:
```
C:\Program Files\nodejs\node.exe .\dist\src\main\js\index.js
Debugger listening on ws://127.0.0.1:59755/e19e1611-5182-4f9a-abf3-8c42f5383c3f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
App startup
```

The 1.47.3 version uses the absolute path (in both cases when entry point points to .js and .ts file):
```
C:\Program Files\nodejs\node.exe g:\fakepath\dist\src\main\js\index.js
Debugger listening on ws://127.0.0.1:60005/874dc858-7c02-4b96-b829-9e7edd2ee49f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
App startup
```

**Comment by connor4312** [comment] 2020-08-17 17:15
Followed up in the linked issu

**Comment by fenying** [comment] 2020-08-18 04:32
@connor4312 see this https://github.com/fenying/vscode-ts-debug-failure

**Comment by connor4312** [comment] 2020-08-18 05:08
@fenying you can fix that by removing the second (redundant) item in your `outFiles`. Tracking that bug in the linked issue.

**Comment by fenying** [comment] 2020-08-18 06:17
@connor4312 Thank you, it works.
