### ISSUE TITLE
VSCode locks up during find/replace with regex

### ISSUE THREAD

**Issue by manbearian** [Microsoft/vscode#45782] opened 2018-03-14 16:47 UTC
### Issue Type
Bug

### Description

I'm seeing vscode lock up (become unreponsive) with simpe find/replace window open (^H) and typing regular expression. Exact scenario involves my source code file with several hundred thousand lines of code. I then enter regex with \r\n realize the VSCode doesn't care about Windows line endings and delete the \r\n. If  i then try and retype a \n after the first backslash the UI becomes unresponsive. I suspect its just doing some kind of real time serach and taking a (very very) long time? in any case i waited a minute or so and didn't get a response. I reproed this behavior twice. I'm MS internal and can provid ethe source file to help rerpo.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.17115

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.83GB (7.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0
csharp|ms-|1.14.0

</details>
Reproduces only with extensions

**Comment by rebornix** [comment] 2018-03-20 21:13
Duplicate of https://github.com/Microsoft/vscode/issues/30874

**Closed by rebornix** 2018-03-20 21:13 UTC
Labels: editor, editor-find
