### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by euk-anthonyb** [Microsoft/vscode#36201] opened 2017-10-13 07:50 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Launch the latest version of VS Code on Windows 10
2. When project loads, processes hang up and alerts appear on screen
3. The application is incapacitated
![image](https://user-images.githubusercontent.com/14346320/31535593-8afc758a-aff3-11e7-8e74-07b43788dfac.png)

Reproduces without extensions: Yes/No

**Comment by euk-anthonyb** [comment] 2017-10-13 07:55
Here is a copy of my console log from the vs code developer tools:
[vscode-1507881159896.log](https://github.com/Microsoft/vscode/files/1381782/vscode-1507881159896.log)

**Comment by gosongs** [comment] 2017-10-13 07:57
same to me

![image](https://user-images.githubusercontent.com/27057518/31535806-04a040ec-afc2-11e7-98c6-1e8d4df3f814.png)

**Comment by euk-anthonyb** [comment] 2017-10-13 08:02
:(

I'm returning to Atom to get my work done.

**Comment by egamma** [comment] 2017-10-13 08:08
Can you reproduce the problem when you start with extension disabled `code --disable-extensions`?

**Comment by euk-anthonyb** [comment] 2017-10-13 08:17
I'm not able to disable extensions. I can't run any commands. Not even with 1.17.11 release that I just installed.

![image](https://user-images.githubusercontent.com/14346320/31536575-191bc52a-aff7-11e7-891e-e8249738023a.png)

![image](https://user-images.githubusercontent.com/14346320/31536634-44fd4d08-aff7-11e7-8eed-bc5974b333ad.png)

**Comment by egamma** [comment] 2017-10-13 08:28
@euk-anthonyb sorry I was not clear. I meant when you start code from the command line.
![image](https://user-images.githubusercontent.com/172399/31537077-390c9ba2-b001-11e7-8799-ec6bba4bf82d.png)

**Comment by euk-anthonyb** [comment] 2017-10-13 08:34
Oh, I see.... Tried the command line but nothing happens.

![image](https://user-images.githubusercontent.com/14346320/31537339-a34fb81c-aff9-11e7-91c8-2df4a4a7b6c4.png)

**Comment by FeiX01** [comment] 2017-10-13 08:52
the same issue after run the code --disable-extensions

**Comment by JkVon** [comment] 2017-10-15 12:45
I finally solve  the problome , just add git.exe into the settings.json. (Install the GOW [https://github.com/bmatzelle/gow](url) to use  commend "where git.exe" in cmd.
##
My OS is Win10;
My error was like this: 
![image](https://user-images.githubusercontent.com/22574711/31584809-8aeb791e-b1e8-11e7-8d1d-54b6ba8969ff.png)
##
In my computer ,it was the VSCode cannot detect installed Git  led to the error.

**Comment by bpasero** [comment] 2017-10-16 05:54
@euk-anthonyb @FeiX01 is git.exe on your path? @joaomoreno fyi, not sure if you have heard the extension host crashing when git.exe is not found?

**Comment by joaomoreno** [comment] 2017-10-16 12:44
@bpasero Yes I have a few issues like that though I was never able to reproduce... no matter how hard I try.

**Comment by joaomoreno** [comment] 2017-10-16 12:45
@euk-anthonyb What is the language of your Windows installation?

**Comment by euk-anthonyb** [comment] 2017-10-16 13:32
@bpasero: I've asked IT but I have not yet heard back from them. Is there a quick way to see if git.exe is on my path?

**Comment by euk-anthonyb** [comment] 2017-10-16 13:34
@joaomoreno: My Windows language is English.

**Comment by ravinsinghd** [comment] 2017-10-19 05:10
[Extension host stop working.txt](https://github.com/Microsoft/vscode/files/1397175/Extension.host.stop.working.txt)

facing same problem. attached my console log

**Comment by joaomoreno** [comment] 2017-10-19 08:21
@euk-anthonyb @ravinsinghd @JkVon @gosongs If you open a command prompt, can you show me the values of the following environment variables:

- `ProgramW6432`
- `ProgramFiles(x86)`
- `ProgramFiles`

---

@ravinsinghd Is the issue fixed if you install Git?

**Comment by ravinsinghd** [comment] 2017-10-19 08:51
@joaomoreno I have git installed already. please find the output for the commend
![capture](https://user-images.githubusercontent.com/9314601/31762409-b42cf0ee-b4d8-11e7-84ac-67ecdff46e08.PNG)

**Comment by joaomoreno** [comment] 2017-10-19 08:57
And where is git installed?

If you go into VSCode's installation directory and move away `extensions\git` does the issue still reproduce?

**Comment by ravinsinghd** [comment] 2017-10-19 09:21
you want me to remove this folder?
![capture](https://user-images.githubusercontent.com/9314601/31763803-030f68e6-b4dd-11e7-9b66-9dfa987cd83c.PNG)

**Comment by joaomoreno** [comment] 2017-10-19 09:43
Yes, just move it away temporarily. Then, try to see if the issue comes up.

**Comment by ravinsinghd** [comment] 2017-10-19 21:02
@joaomoreno after moved the git folder that issue not came. i worked almost 8hrs not facing problem.

**Comment by ravinsinghd** [comment] 2017-10-23 03:11
@joaomoreno that issue occur again. i uninstall most of my extensions still it's occur.

**Comment by ravinsinghd** [comment] 2017-10-25 17:32
Did you guys found root cause? In anyway we can help ?
if you want any logs or something I am ready to share. past 2 weeks working with code become horrible experience.

**Comment by joaomoreno** [comment] 2017-10-27 14:02
So. It is definitely the `git` extension right? If the folder is there you have the issue, if it's not then you don't. Right?

Is there any way we can do a remote screen sharing session? Let me know a good time for you.

**Comment by ravinsinghd** [comment] 2017-10-28 10:19
@joaomoreno  I am not sure it's git. because now i don't have git folder still the problem happen.i am happy to share screen. let me suitable time for you and how to share I will share

**Comment by PixelT** [comment] 2017-10-29 10:39
I have this same issue on macOS

**Comment by joaomoreno** [comment] 2017-10-29 21:49
@ravinsinghd How about tomorrow, Monday, October 30 at 07:30 AM UTC? That would be 13:00 in Bangalore.

https://hangouts.google.com/hangouts/_/joaomoreno.com/vscode36201

**Comment by ravinsinghd** [comment] 2017-10-30 04:41
Awesome will connect

**Comment by ravinsinghd** [comment] 2017-10-30 07:32
@joaomoreno i joined in hangout

**Comment by joaomoreno** [comment] 2017-10-30 07:32
Hmmm me too... I don't see you there.

**Comment by joaomoreno** [comment] 2017-10-30 07:32
Can you try again?

https://hangouts.google.com/hangouts/_/joaomoreno.com/vscode36201

**Comment by euk-anthonyb** [comment] 2017-10-30 08:43
Hi guys, I've been out of the office for a while. 

Here are my cmd prompt environmental variables:
![image](https://user-images.githubusercontent.com/14346320/32161654-512ffe7c-bd4e-11e7-9ea8-f711c5b26ba7.png)

**Comment by ravinsinghd** [comment] 2017-10-30 10:39
@joaomoreno as you suggest i am disabling my extensions one by one and checking if the issue happen 
I disabled **Beautify extension**. After that also error happen. so Beautify OK. 

![image](https://user-images.githubusercontent.com/9314601/32166615-683fa64c-bd8c-11e7-831c-284902018035.png)

Next will try disable angular language service

**Comment by joaomoreno** [comment] 2017-10-30 15:02
Bringing in @alexandrudima. People remove the git extension and still have the problem. So this seems to be something else.

@ravinsinghd's crash is an out of memory one.

**Comment by alexandrudima** [comment] 2017-11-01 15:21
@joaomoreno I'm sorry can you point out which of the 5 distinct reports experience a crash after removing the built-in git extension? I can then start a new issue / thread and investigate what is the root cause.

**Comment by joaomoreno** [comment] 2017-11-02 07:16
@euk-anthonyb Can you try out [this build](https://az764295.vo.msecnd.net/insider/14bec536cd355008680893caa2c3f01c8a5c5ebf/VSCode-win32-x64-1.18.0-insider.zip)? Do you still have the same issue?

**Comment by ravinsinghd** [comment] 2017-11-04 13:56
@joaomoreno I can reproduce the problem by enable and disable  [Angular Language Service extension](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template)

**Comment by joaomoreno** [comment] 2017-11-06 14:44
OK @ravinsinghd. Good to know. Please file an issue to that extension. But for now let us focus on @euk-anthonyb's problem.

**Comment by joaomoreno** [comment] 2017-11-10 16:44
Closing as duplicate of #32739

**Closed by joaomoreno** 2017-11-10 16:44 UTC
Labels: freeze-slow-crash, needs more info

**Comment by euk-anthonyb** [comment] 2017-11-16 14:03
I was finally able to get the Insiders app installed (IT had a huge backlog of requests) but unfortunately, it does not fare any better than the standard version. :(

![image](https://user-images.githubusercontent.com/14346320/32895102-d7f376f6-cad6-11e7-8262-f1d3ba895063.png)

![image](https://user-images.githubusercontent.com/14346320/32895108-ddf6f816-cad6-11e7-9e23-78974aed509e.png)

**Comment by euk-anthonyb** [comment] 2017-12-04 14:53
For some strange reason, this version of the Insiders build now works without incident. :)
