### ISSUE TITLE
Variable bebug hovers don't work after optional chaining

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85441] opened 2019-11-23 05:56 UTC
Issue Type: <b>Bug</b>

Trying to hover over properties after optional chaining (`?.`) operator doesn't work
![image](https://user-images.githubusercontent.com/641685/69474191-eada1f00-0d8b-11ea-9bd9-553a1aa94291.png)

//cc @isidorn 

VS Code version: Code - Insiders 1.41.0-insider (599c076d91be1374cf51004cec610f3bcaf4c9cd, 2019-11-22T07:25:24.031Z)
OS version: Windows_NT x64 10.0.19028

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by weinand** [comment] 2019-11-24 15:39
Without real language knowledge it is difficult to deal with these syntax issues...

**Comment by isidorn** [comment] 2019-11-25 10:36
Yes, ideally we would solve this with AST knowledge.
In the meantime we could solve this by improving the expression regex [here](https://github.com/Microsoft/vscode/blob/b8d63e0fcf76f828c7ebb7939afbb58215df0f42/src/vs/workbench/contrib/debug/common/debugUtils.ts#L53)

The problem is that previous thinks it's parent is `diffUris?` which is incorrect.

For now assigning to on deck. If people hit this a lot while self hosting I would be open to some heuristic which fixes this.

**Closed** 2020-07-30 16:45 UTC
Labels: *out-of-scope, bug, debug
