### ISSUE TITLE
vscode intellisense stop working

### ISSUE THREAD

**Issue by 50l3r** [Microsoft/vscode#28417] opened 2017-06-10 10:27 UTC
Intellisense stop working

- VSCode Version: 1.13.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. For example in php/html file starts tiping: <span
2. Nothing appens

![vscode example](https://i.gyazo.com/bc0f0c5e3a94bb9465707641fe40fdd6.gif)

My extensions:

- Alignment
- Angular  1 Javascript and TypeScript Snippets
- Angular Support
- Auto Close Tag
- Auto Rename Tag
- Beautify
- EditorConfig for VS Code
- ESLint
- Git Project Manager
- HTML Snippets
- html tag wrapper
- HTMLHint
- IntelliSense for CSS classes
- jshint
- npm
- npm intellisense
- Output Colorizer
- Path Intellisense
- PHP Debug
- PHP Intellisense
- seti-icons
- Settings Sync
- Theme - Seti Monokai

**Comment by quonic** [comment] 2017-06-10 15:32
Same Version and OS here also have the same issue. It seems to work after starting VSCode, but stops after a few mins. I have ESLind, jshint, and npm intellisense extensions in common with 50l3r

50l3r: Have you tried disabling all hinting extensions, and enabling them one by one to see if one of them are the cause?

**Comment by ssisaias** [comment] 2017-06-11 08:44
It's also happening to me after i've updated. Intellisense works on start up, stops working after few seconds, to not come back working at all. I have just these two extensions bellow installed.

- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Win 10 Latest
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-codemetrics|kisstkondoros|1.7.2|
|Material-theme|zhuangtongfa|2.8.5|;

**Comment by hiepxanh** [comment] 2017-06-12 02:00
the same with me, visual studio on window died

**Comment by quonic** [comment] 2017-06-12 02:13
Disabling the other linters and intellisense extensions didn't seem to help. When intellisense does die Ctrl+Space just shows "Loading..."

**Comment by pdgago** [comment] 2017-06-12 10:57
intellisense stopped working for me on script tags within html files

**Comment by ramya-rao-a** [comment] 2017-06-12 21:45
@quonic, @hiepxanh @pdgago Are you seeing the issue in html files only or any other languages too?

cc @mjbvz

**Comment by equinox** [comment] 2017-06-12 22:00
Potentially the cause: https://github.com/zignd/HTML-CSS-Class-Completion/issues/58

Disabling the extension does make intellisense work again for me. Enabling it again makes it work for a few seconds, then seems to kill off the intellisense again.

**Comment by quonic** [comment] 2017-06-12 22:53
@ramya-rao-a It seems to also happen in Powershell files.

**Comment by pdgago** [comment] 2017-06-13 08:51
For me the problem was caused by the `polymer.polymer-ide` plugin. I disabled it and it's working again. I was having problems with html files.

**Comment by ramya-rao-a** [comment] 2017-06-13 18:18
Closing this issue as the problem was caused by extensions.
Please log an issue in the repo for the extension that is causing this.

**Closed by ramya-rao-a** 2017-06-13 18:18 UTC
Labels: html, new release

**Comment by mahaveer0496** [comment] 2017-07-16 11:35
I'm having this same issue and i dont have that plugin installed....

**Comment by ramya-rao-a** [comment] 2017-07-17 05:21
@mahaveer0496 Do you see the issue in different languages or only 1?

**Comment by mahaveer0496** [comment] 2017-07-17 05:34
I only use VScode for React, React-Native so I can only speak for Javascript :) @ramya-rao-a 
I changed to the previous version ( 1.13.1 ) and everything is back to normal.

**Comment by ramya-rao-a** [comment] 2017-07-17 06:40
cc @mjbvz for auto-completion issues in javascript

**Comment by TheIncorrigible1** [comment] 2017-10-18 15:37
@ramya-rao-a I'm seeing this issue while editing `PowerShell` scripts after VSCode has been up for a long period of time without restart (8+ hrs)

**Comment by ramya-rao-a** [comment] 2017-10-18 18:05
@TheIncorrigible1 Please log an issue in the repo for the Powershell extension that porvides the suggestions.

**Comment by ronak-itility** [comment] 2017-11-01 05:19
Just to log. @50l3r 
For me `Azure Extension Pack`extension was the culprit

**Comment by pquiring** [comment] 2017-11-09 16:29
I'm using C# and intellisense frequently stops working.  F12 stops working.  Sometimes if I restart it works.  Today nothing works.

**Comment by pquiring** [comment] 2017-11-09 20:03
Found a fix.  I opened project alone (not in workspace) and then VSCode performed a restore and then everything started to work again.  Then I can switch back to workspace and it works fine again.

**Comment by hamidmaddi** [comment] 2017-11-12 18:49
I can confirm the same behavior. It works when the app starts and then stops after few minutes.

**Comment by ramya-rao-a** [comment] 2017-11-13 17:22
@hamidmaddi Please share the type of file you are seeing the issue in. C#, js, powershell?
