### ISSUE TITLE
VSCode doesnt launch / start on Windows 10 22H2 32-bit OS

### ISSUE THREAD

**Issue by sravanv123** [microsoft/vscode#166057] opened 2022-11-10 23:25 UTC
Visual Studio Code 32-bit version never gets launched or started on Windows 10 22H2 32-bit OS.
All the latest binaries available in 3 modes System, User Installers, and Zip file doesnt work.
Tried re-instlaling Windows 10 22H2 32 bit OS, but the result is same.
Verified against 1.73, 1.72, 1.71 builds but it never gets launched. 

Is there any solution?

(Some additional info to triage): 
1. VSCode v1.54 or below runs with moderrate speed on Windows 10 32-bit
2. VSCode v1.55 runs very slow, and uses more memory, and is slow compared to earlier versions.
3. Any VSCode version above v1.55 doesnt run on Windows 10 32-bit OS.

**Comment by rzhao271** [comment] 2022-11-11 00:37
What is the output when running from the command line `code --verbose`?

**Comment by sravanv123** [comment] 2022-11-12 00:29
[VSCodeSetup-ia32-1.73.1.txt](https://github.com/microsoft/vscode/files/9993743/VSCodeSetup-ia32-1.73.1.txt)
[VSCodeSetup-ia32-1.54.3.txt](https://github.com/microsoft/vscode/files/9993744/VSCodeSetup-ia32-1.54.3.txt)

**Verbose output for v1.54.3 and v1.73.1 are attached. 
[For v1.73.1 there is no verbose visible, the vscode process did not run]
The installers used are 32-bit System Installers, with same name as that on files attached.**

**Comment by sravanv123** [comment] 2022-11-12 00:30
> What is the output when running from the command line `code --verbose`?
Please review the verbose output attached.

**Comment by bpasero** [comment] 2022-11-12 06:52
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sravanv123** [comment] 2022-11-12 22:47
Insttalled VSCodeSetup-ia32-1.74.0-insider.
Command Line: "Code - Insiders.exe" --verbose
Output to File: No Output [attached VSCodeSetup-ia32-1.74.0-insider.txt]
[VSCodeSetup-ia32-1.74.0-insider.txt](https://github.com/microsoft/vscode/files/9996083/VSCodeSetup-ia32-1.74.0-insider.txt)
exe
It looks that the code.exe insider version also prematurely exited for some reason, didn't run / launch.

**Comment by bpasero** [comment] 2022-11-13 06:08
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by sravanv123** [comment] 2022-11-15 06:19
![image](https://user-images.githubusercontent.com/117953354/201841076-2998ff9c-dc56-4109-bf26-cdcababe7015.png)

There is no crash or minidump visible in the dump folder (screenshot attached).

**Comment by sravanv123** [comment] 2022-11-15 20:08
result is attached, no crash dumps visible.

**Comment by sravanv123** [comment] 2022-11-15 21:52
**### "Code - Insiders.exe" loads into the task manager, and then after a second, it exits.**
There is no crash seen. (Screenshot attached). This is a common situation on many physical machines.
It would be wise to find a solution.

![image](https://user-images.githubusercontent.com/117953354/202032719-d3cbf76f-b90d-40f7-b049-d3ae11622bfd.png)

**Comment by sravanv123** [comment] 2022-11-15 22:38
Even When Windows 10 32 bit is booted with  4-gigabyte tuning feature, enabled, using
BCEdit /set increaseuserva 3072 (3GB User Memory, and 1 GB Kernel Memory)

The result of loading is same, and it is very clear that the Build Image needs optimization if possible, which is an amicable solution.

![image](https://user-images.githubusercontent.com/117953354/202039345-7cc81c7b-2f52-4439-a0ce-e4bb00c93700.png)

**Comment by sravanv123** [comment] 2022-11-16 20:55
Is there any solution possible?

**Comment by sravanv123** [comment] 2022-11-18 20:22
This happens only with Visual Studio Code and not with Visual Studio 2019

**Comment by rzhao271** [comment] 2022-11-21 16:55
"It doesn't run on Physical Machine, but runs on Virtual Machine."
Is the virtual machine also a 32-bit OS with similar specs?
Also, does a [clean reinstall](https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall) work?

**Comment by sravanv123** [comment] 2022-11-30 22:38
> "It doesn't run on Physical Machine, but runs on Virtual Machine." Is the virtual machine also a 32-bit OS with similar specs? Also, does a [clean reinstall](https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall) work?

RAM, CPU Cores are same both on VM and Physical Machine.
However the VM is running in VMWare Player, it wont simulate the exact environment of a Physical Machine.
A Clean install / Uninstall of both VS Code and Windows 10 32 bit didn't solve the problem.
Problem is reproducible on the Physical Machine.

**Comment by sravanv123** [comment] 2022-11-30 22:40
> @sravanv123 please use the batch file to start the application and collect the relevant logs, for ex the commands should be:
> 
> * `bin\code-insiders.cmd --verbose`
> * `bin\code-insiders.cmd --crash-reporter-directory C:\Users\<username>\AppData|Local\Temp\vscode-crashes`

I would try the above again, and attach the output of the same.

**Comment by sravanv123** [comment] 2022-12-01 13:38
> @sravanv123 please use the batch file to start the application and collect the relevant logs, for ex the commands should be:
> 
> * `bin\code-insiders.cmd --verbose`
> * `bin\code-insiders.cmd --crash-reporter-directory C:\Users\<username>\AppData\Local\Temp\vscode-crashes`

The result of these commands is same as explained previously. VSCode just appears in TaskManager and exits in few seconds.
VSCode.exe doesn't crash, loads and unloads quickly, it is clear it doesnt execute normally, prematurely exits for some reason.

There is no vscode-crashes seen in the above path C:\Users\<username>\AppData\Local\Temp\vscode-crashes`

Observation of the directory in temp folder is as below:
====================================
![image](https://user-images.githubusercontent.com/117953354/205066354-7de52194-5e0d-4036-9fd1-8a77cab848a5.png)

**Comment by sravanv123** [comment] 2022-12-01 13:42
> @sravanv123 please use the batch file to start the application and collect the relevant logs, for ex the commands should be:
> 
> * `bin\code-insiders.cmd --verbose`
> * `bin\code-insiders.cmd --crash-reporter-directory C:\Users\<username>\AppData\|Local\Temp\vscode-crashes`

Output of bin\code-insiders.cmd --verbose
============================

![image](https://user-images.githubusercontent.com/117953354/205067575-ad45126a-d8d1-4c08-8cf6-956b34bf25ae.png)

**Comment by sravanv123** [comment] 2022-12-01 13:44
@sravanv123 please use the batch file to start the application and collect the relevant logs, for ex the commands should be:

bin\code-insiders.cmd --verbose
bin\code-insiders.cmd --crash-reporter-directory C:\Users\<username>\AppData\|Local\Temp\vscode-crashes

Output of bin\code-insiders.cmd --crash-reporter-directory C:\Users\<username>\AppData\|Local\Temp\vscode-crashes:
==============================================================================

![image](https://user-images.githubusercontent.com/117953354/205068317-05d7c85f-81aa-4f4b-a473-c4d16f173344.png)

**Comment by sravanv123** [comment] 2022-12-01 13:48
Is there any logs available to identify where the execution of vscode.exe stops?

**Comment by rzhao271** [comment] 2023-12-07 22:14
This issue is out of scope now because VS Code doesn't support Windows 32-bit anymore.

**Closed by rzhao271** 2023-12-07 22:14 UTC
Labels: bug, upstream, freeze-slow-crash-leak, windows, electron, confirmation-pending
