### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by Nebula-2003** [microsoft/vscode#231929] opened 2024-10-22 11:08 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.3

**Steps to reproduce crash**

1. Opened large project
2. Worked for 30 min approx.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 5.15.0-124-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 1177)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|15.39GB (7.65GB free)|
|Process Argv|--crash-reporter-id fc033879-3ef1-4bad-8cf7-f65cb9e5dd84|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sqlite|ale|0.14.1
vscode-toggle-quotes|Bri|0.3.6
bruno|bru|3.1.0
turbo-console-log|Cha|2.10.5
js-auto-backticks|cha|1.2.0
vscode-office|cwe|3.4.3
postgres-sql-tools|dbx|0.0.3
githistory|don|0.6.20
prettier-vscode|esb|11.0.0
restore-terminals|Eth|1.1.8
copilot|Git|1.241.0
copilot-chat|Git|0.21.2
go|gol|0.42.1
todo-tree|Gru|0.0.226
vscode-import-formatter|hen|0.1.8
code-background|Kat|3.0.2
console-log|Lui|0.0.14
mongodb-vscode|mon|1.9.2
remote-containers|ms-|0.388.0
console-flash|NAP|0.1.0
csv-to-table|php|1.4.0
material-icon-theme|PKi|5.11.1
postman-for-vscode|Pos|1.3.0
sqlite-viewer|qwt|0.8.4
LiveServer|rit|5.7.9
case-flip|sol|0.0.4
code-spell-checker|str|3.0.1
icons|tal|3.8.0
pdf|tom|1.2.2
errorlens|use|3.20.0
gitblame|wad|11.1.1
change-case|wma|1.0.0
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by mjbvz** [comment] 2024-10-22 23:20
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!

**Comment by Nebula-2003** [comment] 2024-10-23 04:08
@mjbvz have enabled logging, will update on next crash

**Comment by Nebula-2003** [comment] 2024-11-04 09:41
hi @mjbvz have added ts server logs as requested [tsserver.log](https://github.com/user-attachments/files/17616251/tsserver.log)

**Comment by mjbvz** [comment] 2024-12-10 23:36
Duplicate of https://github.com/microsoft/typescript/issues/60243

**Closed by mjbvz** 2024-12-10 23:36 UTC
Labels: info-needed
