### ISSUE TITLE
MacOS Big Sur + oh my zsh + powerline fonts + visual studio code (vscode) terminal settings

### ISSUE THREAD

**Issue by panwl83** [microsoft/vscode#121044] opened 2021-04-11 11:18 UTC
**befor**
![image](https://user-images.githubusercontent.com/7565525/114302190-82175200-9afa-11eb-82ef-062cf964797a.png)
**after v1.55.1**
![image](https://user-images.githubusercontent.com/7565525/114302154-657b1a00-9afa-11eb-839b-5e07af50c842.png)
Reset terminal.integrated.fontFamily and then set it back to Source Code Pro for Powerline, It can return to normal.But after closing the window and reopening it, there is a problem with the font again

**Comment by IllusionMH** [comment] 2021-04-11 16:44
Looks like duplicate of #120129

Please check if it's still reproducible in Insiders build

**Comment by jedchang** [comment] 2021-04-12 05:42
Same problem
![q](https://user-images.githubusercontent.com/8979857/114345808-f56da200-9b94-11eb-9583-be9b0e0c2441.jpg)

**Comment by meganrogge** [comment] 2021-04-14 15:42
Duplicate of #120129

**Closed by meganrogge** 2021-04-14 15:42 UTC
