### ISSUE TITLE
[css] selector-hover: The first child selector is not nested in tooltip

### ISSUE THREAD

**Issue by trustedtomato** [Microsoft/vscode#22835] opened 2017-03-18 19:36 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.5.1|
|RustyCode|saviorisdead|0.19.1|
|Material-theme|zhuangtongfa|2.1.7|;

---

Steps to Reproduce:

1. Make a new CSS file
2. Create a selector like `.my-class>.my-nested-class>.my-very-nested-class`
3. Hover over the selector

The tooltip looks like:
```
<element class="my-class">
<element class="my-nested-class">
     <element class="my-very-nested-class">
```

While it should be:
```
<element class="my-class">
     <element class="my-nested-class">
          <element class="my-very-nested-class">
```

**Comment by rocifier** [comment] 2017-03-30 08:48
Hi where is the code located for "selector-hovers"? This bug is annoying me and I'd like to have a go at fixing it and doing a pull request if no one is working on it. Are there different code bases for css, less, and sass?

**Comment by aeschli** [comment] 2017-03-30 19:28
It's the same code base. The code is at https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/services/selectorPrinting.ts
'toElement' builds a tree from a selector. The tree corresponds to the structure you see in the hover, with children and siblings.
The best to undertand this is to look at the test cases: https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/test/css/selectorPrinting.test.ts

**Comment by rocifier** [comment] 2017-03-31 01:25
Awesome, thank you so much. I will try to take a look at this tonight.

**Comment by rocifier** [comment] 2017-03-31 08:13
@aeschli can you please provide me with some basic instructions for debugging this test suite?

**Comment by rocifier** [comment] 2017-03-31 09:44
Got it. After making this minor change and using the main version of visual studio so node debug works, I can use the debug task to debug the unit tests. I think I've managed to install my local package into the main code editor so I can see the result more or less as I edit the package. Is this what you do? It seems the tests are going to be quite valuable here.

**Comment by aeschli** [comment] 2017-03-31 13:08
Yes, open the folder in VSCode, set breakpoints, open the debug viewlet, switch to 'Unit Test' and run.
![image](https://cloud.githubusercontent.com/assets/6461412/24551220/fe4e718a-1621-11e7-8ad5-c1e91d72f42e.png)

**Comment by aeschli** [comment] 2017-03-31 13:15
I pushed a fix for the compile issue which was caused by a breaking change in a dependency.

**Comment by rocifier** [comment] 2017-04-01 05:55
Hi, just an update. I have been able to create a single test case which illustrates the problem. I have also added significant unit testing around the MarkedStringPrinter, which is where the problem lies. I will now tackle the implementation details to make all tests pass.

**Comment by rocifier** [comment] 2017-04-01 07:58
Pull request: https://github.com/Microsoft/vscode-css-languageservice/pull/26

**Closed** 2017-04-05 09:02 UTC
Labels: bug, css-less-sass
