### ISSUE TITLE
Can no longer click after this line in keybindings.json

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21760] opened 2017-03-02 11:29 UTC
![image](https://cloud.githubusercontent.com/assets/900690/23505396/d05f99a6-ff43-11e6-8b6b-c1a627f329a9.png)

Whenever I click at the end of line 16 or 17, my cursor does not go to the end. Seems to be related to those decorations inside the editor?

**Comment by bpasero** [comment] 2017-03-02 11:29
![panel-red](https://cloud.githubusercontent.com/assets/900690/23505415/f270c92a-ff43-11e6-9857-71d30818419c.gif)

**Comment by alexandrudima** [comment] 2017-03-02 11:37
Related #21740

**Comment by alexandrudima** [comment] 2017-03-02 14:04
In fact, it is a duplicate of #21740

**Closed by alexandrudima** 2017-03-02 14:04 UTC
Labels: bug, keybindings
