### ISSUE TITLE
"Reopen editor with" leaves duplicate tab open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#114306] opened 2021-01-13 20:09 UTC
- Open readme.md, opens in markdown notebook
- "Reopen editor with" > Text editor
- Now there are two readme.md tabs open, and clicking the second only reopens the first

![image](https://user-images.githubusercontent.com/323878/104505039-31926600-5598-11eb-9811-6d556cf9af8d.png)

**Comment by mjbvz** [comment] 2021-01-13 20:51
Duplicate of #111474

**Closed by mjbvz** 2021-01-13 20:51 UTC
