### ISSUE TITLE
Left/Right Arrows Not Working in Custom Menu Bar

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#99907] opened 2020-06-11 18:17 UTC
Open file menu, use left/right arrow keys

🐛 => does not change top-level menu

**Comment by sbatten** [comment] 2020-06-11 18:48
caused by https://github.com/microsoft/vscode/commit/9d68bd29183970aaf5a41749c4b0ea79155d9c81

**Comment by isidorn** [comment] 2020-06-12 09:09
@sbatten thanks a lot for catching this. Sorry for breaking this, should have tested the custom menu.
I just checked other apps and they actually always navigate via arrows in what visualy makes sense. The visual orientation is mentioned by the screen reader to users so I think it is perfectly fine to go to the previous beahvior and simply revert the commit.

Since this is a regression adding candidate label.

**Comment by isidorn** [comment] 2020-06-16 07:07
Closing as the fix was merged into the release branch.

**Closed** 2020-06-16 07:06 UTC
Labels: bug, candidate, menus
