### ISSUE TITLE
User update on terminal server fails when other users have application open.

### ISSUE THREAD

**Issue by spdkils** [microsoft/vscode#149977] opened 2022-05-19 20:57 UTC
When using Microsoft's Terminal server with user based installs, no single user can update their copy without all users on the server closing code.exe.

Log file shows:
<timestamp> INFO Code.exe is running, wait a bit
<timestamp> INFO Gave up waiting for Code.exe to exit
<timestamp> INFO Kill process if found: xxxxx, Code.exe
<timestamp> WARN Kill error Failed to open process: Access is denied.

Then you get a crash, saying it failed to update.

This is unexpected behavior because we're running the user level install, and no single user should need to kill the process for every user on the server to update.

**Comment by Tyriar** [comment] 2022-05-20 13:07
Can you clarify what this is?

> Microsoft's Terminal server with user based installs

**Comment by spdkils** [comment] 2022-05-23 16:01
Windows Terminal Server, is a multi-user environment virtual desktop server.

Users login to Terminal server via RDP and launch/install their own apps. One of those apps is VSCode.

The VS Code process is running under each individuals user account. As a result user A, can't kill a process for user B because they do not have permissions to do that.

So if user A wants to upgrade VS Code in their own home folder, the default installer tries to kill all code.exe process on the server, and they cannot.

So they are now stuck in that error loop I describe above.

No one can update their own home folder VSCode because the installer does not ignore processes started from other users. (Or maybe, more explicitly it does not check each running process to see if it's the actual file the user is trying to update, ignoring others.)

**Comment by Tyriar** [comment] 2022-05-25 14:16
Oh I see, I don't think we support multi-user servers like this. Moving to @deepak1556, not sure who is best assigned to this.

**Comment by conioh** [comment] 2022-07-29 01:14
Duplicate of #76641.

The current "workaround" is to disable "background updates" using `"update.enableWindowsBackgroundUpdates": false`.

**Comment by deepak1556** [comment] 2022-12-07 04:10
Merging to https://github.com/microsoft/vscode/issues/76641

**Closed by deepak1556** 2022-12-07 04:10 UTC
