### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by goisborges** [microsoft/vscode#114552] opened 2021-01-19 03:14 UTC
Issue Type: <b>Performance Issue</b>

I am running VSCode in my Asus laptop and the screen keeps flickering all the time. It starts a few seconds after I open the software. I am using 2 screens and this issue never happened before with any other software. If I click the screen and start writing the code it kind of go back to normal but it goes weird again after a few seconds. If I don't click the screens it gets worse with time. I have a GeForce Nvidia1650 4Gb, 16gb RAM, Intel i5 9300H. Any solutions for this issue?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.98GB free)|
|Process Argv|--crash-reporter-id 7df45c82-55ef-4f26-a3aa-910cf121d4d5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    73	 14504	code main
    0	    36	   864	   utility
    0	   161	  1680	   window (index.php - Lesson-01 - Visual Studio Code)
    0	   173	  5832	     extensionHost
    0	    12	 10512	     watcherService 
    0	    11	 11212	       console-window-host (Windows internal process)
    0	    67	 15684	     searchService
    0	    22	  3352	   crashpad-handler
    0	    77	  9308	   window (Issue Reporter)
    0	    84	 10700	   shared-process
    0	   115	 16144	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.php - Lesson-01 - Visual Studio Code)
|    Folder (Lesson-01): 1 files
|      File types: php(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|1.0.3484
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244cf:30244300
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt859:30241729

```

</details>

**Comment by goisborges** [comment] 2021-01-19 03:15
![image](https://user-images.githubusercontent.com/61516804/104983411-b63b1500-59da-11eb-88c1-bdad01ede145.png)

**Comment by goisborges** [comment] 2021-01-19 03:18
![vscode issue](https://user-images.githubusercontent.com/61516804/104983645-28135e80-59db-11eb-8c6b-fc6132828400.png)

**Comment by IllusionMH** [comment] 2021-01-19 10:21
Looks like duplicate of #93356

I guess that if issue was closed in November as upstream then it might be fixed in Electron 11 which is in Insiders build https://code.visualstudio.com/insiders/

Could you check if it is still reproducible in Insiders builds?

Workaround: start VS Code with `code --disable-gpu` or more permanent flag https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Closed** 2021-01-27 11:35 UTC
Labels: gpu, needs more info, windows
