### ISSUE TITLE
@gtournie The undo history is unlimited.

### ISSUE THREAD

**Issue by rzw** [microsoft/vscode#104913] opened 2020-08-18 09:53 UTC
@gtournie The undo history is unlimited.

_Originally posted by @alexdima in https://github.com/microsoft/vscode/issues/75606#issuecomment-546419168_

This might be true in theory, but unfortunately, the undo feature is unreliable. 

I will post more when I succeed in provoking this issue. I have *repeatedly* experienced that I can only undo one or two steps. A further undo gives a blank editor screen. Whether it's an intermediate "save as" or opening another file in a new tab... Until now I don't know the reason.

**Comment by isidorn** [comment] 2020-08-18 10:03
This is not a bug report. Please file exact reproducable steps. Thank you

**Comment by rzw** [comment] 2020-08-18 10:45
I completely agree. That's why I stated: "I will post more..." But I am glad about this quick reaction so I did some fiddling around immediately and can actually describe an unexpected behavior – unexpected for me at least.
It's not a bug and perhaps it's documented but...I didn't RTFM. Actually all is fine and quite cool. (But again: unexpected):

1. Open a new file, enter code or lorem ipsum, save the file.
2. Then type somemore, do some editing, save as (new name).
3. Edit stuff and... undo as far as you can

>> Undo will bring you to the state of save as... then the editor goes blank

Open the initial file (Of course it's like you saved it)

**So what about everything you did between "save" and "save as"?**

It's there if you undo in the original file. While the file stays the same, the undo history is appended to the history of the original file with a final (added) delete, so that the file looks like you saved it.



Does this make sense? Perhaps somebody can explain more understandably...

**Comment by nrayburn-tech** [comment] 2020-08-26 04:32
I think that when you use save as to create a file and lose the undo stack is a similar issue to https://github.com/microsoft/vscode/issues/103208. It might be the same problem.

**Comment by alexdima** [comment] 2020-08-30 10:06
Duplicate of #17977

**Closed by alexdima** 2020-08-30 10:06 UTC
Labels: needs more info
