### ISSUE TITLE
Some files appear twice when using TypeScript

### ISSUE THREAD

**Issue by ip** [Microsoft/vscode#41487] opened 2018-01-11 20:57 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
vscode-eslint|dba|1.4.3
json-tools|eri|1.0.2
vscode-json5|mrm|1.0.0

---

For some reasons, files from a particular folder appear twice in search and when opening them other ways (i.e. via "Jump to declaration", clicking in sidebar etc.).

I believe this bug causes these problems as well (they started to appear at the same time):

- TS Server goes crazy - the editor starts reporting tons of random errors and highlight random places in code with red underline
- Debug breakpoints only work on one of two copies of a file (the editor regards them as belonging to different files)

See the screenshots:

![image](https://user-images.githubusercontent.com/1111008/34845640-9cf73c82-f726-11e7-9227-6baef0ba46ce.png)

![image](https://user-images.githubusercontent.com/1111008/34846539-81a97974-f729-11e7-8dce-f9260c00a938.png)

Steps to Reproduce:

Not sure, need to discuss. Probably, this is due to several `tsconfig.json`'s in the project. There are three of them:

```
./tsconfig.json
./build_config/tsconfig.common.json
./src/browserTestbed/tsconfig.json
```

I would greatly appreciate if not a fix, then at least some workaround. Thanks.

Reproduces without extensions: Yes

**Comment by astrism** [comment] 2018-02-21 21:53
No clue whats causing this issue but I had this exact issue, I was able to work around it by recreating my Workspace.

**Comment by frodegil** [comment] 2018-04-30 11:27
Same. For me its annoying. It appears often. At least twice a day. I make changes to a typescript file, then suddenly lots of confusing errors for no reason. I notice that the same file is opened twice. I try to save and close one of them and get a toaster message that content on disk is newer. I accept/reject, closes both views (of the same file) and re-opens it. Sometimes changes are lost and I have to start over again.

**Comment by frodegil** [comment] 2018-05-02 11:13
I read somewhere that /// <reference path="<file path, but with another casing than the file-system>"/> could cause the problem during debugging (gulp-webserver and live-reload). I have now fixed the casing in referenced files to match the files system and will monitor to see if the problem is still there, the next couple of days.

**Comment by mjbvz** [comment] 2018-07-03 22:56
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled? I made some fixes around file casing recently

**Closed** 2018-07-11 05:00 UTC
Labels: needs more info, typescript
