### ISSUE TITLE
[ Feature Request ] Color code search results to match comment text color

### ISSUE THREAD

**Issue by esutton** [Microsoft/vscode#44753] opened 2018-02-28 16:18 UTC
### Use Case

Make it easy to distinguish search results found in **code** versus **comments**.

I often must go through multiple search result hits to find the search result in code I am looking for.

1)  Display comment search results in green ( or whatever the syntax color is for a comment )
2) Displaying non-comment search results in white is fine ( IMO ). 

See screenshot mock-up below:

![screen shot 2018-02-28 at 10 04 55 am](https://user-images.githubusercontent.com/6115047/36798937-94a157c8-1c71-11e8-8590-06303fdbc837.png)

**Comment by roblourens** [comment] 2018-03-06 02:47
Duplicate of #5192

**Closed** 2018-03-06 02:47 UTC
Labels: *duplicate, search
