### ISSUE TITLE
Markdown-specific search for GitHub.dev

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#131105] opened 2021-08-18 16:26 UTC
I've been using GitHub.dev more now that there's a handy shortcut for it. Something I really miss is being able to ctrl+f in readmes for specific content I'm looking for. Today that opens the generic find window that operates on the whole window/editor. I know we don't have control over the native find behavior in browser, but for github.dev could we have a custom "find" implementation in the markdown preview  that supports a common set of scenarios?

**Comment by bpasero** [comment] 2021-08-31 04:21
see https://github.com/microsoft/vscode/issues/125118#issuecomment-857461433 for a quick experiment I did. `window.find` works actually pretty well.

**Comment by mjbvz** [comment] 2021-11-19 23:50
Duplicate of #136473

**Closed by mjbvz** 2021-11-19 23:50 UTC
Labels: feature-request, markdown, webview, web
