### ISSUE TITLE
TypeScript snippets should show up in TypeScript React

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/vscode#32584] opened 2017-08-15 19:12 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
bazel-code|Dev|0.1.8
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.3
tslint|eg2|0.17.0
git-project-manager|fel|1.3.2
auto-rename-tag|for|0.0.14
docthis|joe|0.4.7
contextualduplicate|laf|0.2.0
debugger-for-chrome|msj|3.1.7
vscode-subword-navigation|ow|1.1.5
Align|ste|0.2.0
rewrap|stk|1.4.2
clang-format|xav|1.5.0
vscode-proto3|zxh|0.1.2

(3 theme extensions excluded)

---

**Steps to Reproduce:**

1. Try to make a User Snippet
2. Get prompted to choose a language
3. Choose TypeScript
4. Try to use the snippet in a `.tsx` file

**Expected Results:**

You can share a single snippet across languages.

**Actual Results:**

It appears you need to copy/paste them (which is gross for all the normal reasons that maintaining copy/pasted code is gross).

**Comment by jrieken** [comment] 2017-08-17 07:13
duplicate of #13182

**Closed by jrieken** 2017-08-17 07:13 UTC
Labels: new release, snippets, typescript
