### ISSUE TITLE
Unable to open links to files in Traceback, getting "No file system handle registered" error

### ISSUE THREAD

**Issue by micheusch** [microsoft/vscode#210404] opened 2024-04-15 16:16 UTC
minimal sample attached:
[br.tgz](https://github.com/microsoft/vscode/files/14981523/br.tgz)
Create notebook, import python file
![image](https://github.com/microsoft/vscode/assets/14202226/37feb15c-1f98-4811-8a73-6f2ec9691230)
<br>
click on the ~/my_import.py:2 link to get to location of error and you get
<br>
![image](https://github.com/microsoft/vscode/assets/14202226/8d0d9ea9-d0b9-4402-8e4b-b06053f40aa7)

Possibly duplicate of 170476 that hasn't been touched in one year.

Version: 1.83.1
Commit: unknown
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Embedder: server-distro

**Comment by amunger** [comment] 2024-11-22 23:23
duplicate of https://github.com/microsoft/vscode-jupyter/issues/14563

**Closed by amunger** 2024-11-22 23:23 UTC
