### ISSUE TITLE
Call stack inline actions colors not visible when selected

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96047] opened 2020-04-24 08:49 UTC
1. Start debugging 2 simlple sessions, for example
`console.log('hello')`
2. Notice two sessions shown in the call stack view
3. Click on one so it is selected with a dark blue background 
4. Hover over it -> notice how the actions are not visible 🐛 

This used to work I am pretty sure. As previously the icons would turn white and be nicely visible @misolori did we change something here recently?

![Screenshot 2020-04-24 at 10 46 39](https://user-images.githubusercontent.com/1926584/80193526-3f264b00-8619-11ea-91ab-29245df9cbcb.png)

**Comment by misolori** [comment] 2020-04-24 17:27
This was caused by https://github.com/microsoft/vscode/commit/74401430d2e15c7973bd193d222b23f0aadf580e which came through a pr (https://github.com/microsoft/vscode/pull/94838). I'll re-add the CSS rule to show the icons on white.

**Comment by misolori** [comment] 2020-04-24 17:30
Should be fixed now:

![image](https://user-images.githubusercontent.com/35271042/80240367-937bfb80-8616-11ea-968b-3d461f82d982.png)

**Closed** 2020-04-24 17:29 UTC
Labels: bug, debug

**Comment by isidorn** [comment] 2020-04-24 17:51
@misolori thanks a lot for fixing this.
fyi @robertrossmann

**Comment by robertrossmann** [comment] 2020-04-24 21:16
Ooops sorry! And thanks for fixing this! ❤️
