### ISSUE TITLE
Built in Javascript linter uses wrong prefix in error messages

### ISSUE THREAD

**Issue by gold604** [Microsoft/vscode#67278] opened 2019-01-28 20:46 UTC
Hello everyone, I am new to vscode and I read on [vscode docs](https://code.visualstudio.com/docs/languages/javascript#_linters):

> Error messages will be prefixed (see above [eslint]) by the originator of the message. Error messages from the JavaScript language service are prefixed js.

However when I tried it out myself I have found out that all the errors I got (in .js files) were prefixed with _[ts]_. Is this behavior intended? 

I tried to turn off typescript validation and let only javascript validation be turned on, but the result is same:

```json
{
    "typescript.validate.enable": false,
    "javascript.validate.enable": true
}
```

![image](https://user-images.githubusercontent.com/28358494/51865171-e00a5580-2345-11e9-94b4-953fe570bef8.png)

**Comment by mjbvz** [comment] 2019-01-29 01:22
Duplicate of #59942

**Closed by mjbvz** 2019-01-29 01:22 UTC
Labels: javascript
