### ISSUE TITLE
code --status displays a lot of errors before actual status output

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#183787] opened 2023-05-30 11:31 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2 (installed via snap)
- OS Version: Ubuntu 23.04

Steps to Reproduce:

1. Run `code --status`

```
[79076:0530/132835.062279:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[79103:0530/132835.109953:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79103:0530/132835.110053:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79103:0530/132835.110092:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[79103:0530/132835.113137:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79103:0530/132835.113194:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79103:0530/132835.113230:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[79103:0530/132835.113267:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[79103:0530/132835.114696:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[79114:0530/132835.177975:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79114:0530/132835.178069:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79114:0530/132835.178125:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[79114:0530/132835.181294:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79114:0530/132835.181394:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79114:0530/132835.181472:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[79114:0530/132835.181559:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[79114:0530/132835.183344:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[79134:0530/132835.219654:WARNING:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load swrast driver
Version:          Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS Version:       Linux x64 6.2.0-20-generic
CPUs:             Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 799)
Memory (System):  7.65GB (3.82GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --force-user-env --unity-launch
GPU Status:       2d_canvas:                              unavailable_software
                  canvas_oop_rasterization:               disabled_off
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        disabled_software
                  multiple_raster_threads:                enabled_on
                  opengl:                                 disabled_off
                  rasterization:                          disabled_software
                  raw_draw:                               disabled_off_ok
                  video_decode:                           disabled_software
                  video_encode:                           disabled_software
                  vulkan:                                 disabled_off
                  webgl:                                  unavailable_software
                  webgl2:                                 unavailable_software
                  webgpu:                                 disabled_off

CPU %	Mem MB	   PID	Process
    0	   157	 78834	code main
    0	    39	 78836	   zygote
    0	    63	 78889	     gpu-process
    0	    39	 78837	   zygote
    0	    63	 78875	   utility-network-service
    0	   282	 78906	window [1] (Visual Studio Code)
    0	   118	 78948	shared-process
    0	    71	 78994	     ptyHost
    0	    78	 78949	fileWatcher [1]
    0	   157	 78968	extensionHost [1]
    0	    63	 79018	     electron-nodejs (/snap/code/129/usr/share/code/code --ms-enable-electron-run-as-node /snap/code/129/usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=78968)
``` 

### Expected behaviour: 
Just the status is displayed

### Actual behaviour: 
Lots of errors are displayed before the actual status output

**Comment by deepak1556** [comment] 2023-05-30 15:25
`--status` will enable verbose logs from the runtime as well https://github.com/microsoft/vscode/blob/60bfd19afb29aec3171aef91d72e26eb2263c97f/src/vs/code/node/cli.ts#L191 . @bpasero do you know why runtime logs are enabled in this mode ?

**Comment by bpasero** [comment] 2023-05-30 15:52
I think the real issue here is enabling the electron verbose logging, which is not good I think.

**Comment by Tyriar** [comment] 2023-05-31 21:53
This is fixed for the most part, but certain logs may still appear:

<img width="574" alt="Screenshot 2023-05-31 at 2 52 18 pm" src="https://github.com/microsoft/vscode/assets/2193314/5189780e-72fe-46fa-81bc-b53113c7f7da">

**Comment by bpasero** [comment] 2023-06-01 05:37
Hm, @SimonSiefke could you try your steps again using VS Code insiders: https://code.visualstudio.com/insiders/

@deepak1556 what would cause these low level messages to appear in the output, do you know?

**Comment by deepak1556** [comment] 2023-06-01 06:44
Chromium will always log to stderr for messages that are of severity level `ERROR` or higher https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:base/logging.cc;l=613-630 when no explicit logging destination is provided. If we want to hide these messages, then a better way would be to separate the runtime logs to a separate file destination using `--enable-logging=file --log-file=<path>` https://github.com/electron/electron/blob/main/docs/api/command-line-switches.md#--log-filepath and ignore them for `--status` mode.

**Comment by bpasero** [comment] 2023-06-01 07:42
@deepak1556 could we pass in `/dev/null` unless `--verbose` is used? I am not convinced these messages are helpful, unless maybe we explicitly ask for it.

**Comment by bpasero** [comment] 2023-06-01 08:17
https://github.com/microsoft/vscode/pull/184031 ignores stderr unless `verbose` is used.

**Comment by bpasero** [comment] 2023-06-01 08:48
Can be verified with the build tomorrow (Friday) with the additional changes.

**Comment by joyceerhl** [comment] 2023-06-01 21:03
Now when I run `code-insiders --status` I get no output at all. I get some output with `code-insiders --status --verbose`. Is that the expected behavior?

**Comment by Tyriar** [comment] 2023-06-01 21:17
@joyceerhl you should either a message saying you need to open a window to use this command, or something like this:

<img width="887" alt="Screenshot 2023-06-01 at 2 17 52 pm" src="https://github.com/microsoft/vscode/assets/2193314/fcf1edab-6896-4a9b-95a9-39a7e0160061">

**Comment by joyceerhl** [comment] 2023-06-01 21:20
I'm on Windows and I do not see this message if the app was launched from the taskbar, but I do see this message after launching with the CLI

**Comment by deepak1556** [comment] 2023-06-02 01:46
Yeah we have regressed the behavior on windows. It looks like we only had access to stderr on Windows when launching as `ELECTRON_RUN_AS_NODE` and routing the console output via https://github.com/electron/electron/blob/d818f35ad4ec44c83f21dd3656ef1072e196c34f/shell/app/electron_main_win.cc#L162, internally all node console outputs from the main application process were redirected to stderr. @bpasero I will bring back `stderr` for windows to fix the regression and can investigate why stdout is not available as follow-up.

**Comment by sandy081** [comment] 2023-06-02 06:29
Reopening this as it is not merged into release branch yet.

**Comment by bpasero** [comment] 2023-06-02 08:58
**Verification**
* This needs verification on **macOS**, **Windows** and **Linux**
* have one code insiders window opened
* from the command line run `code-insiders --status`
* verify you see status related output
* verify you do not see Electron/Chrome related output such as `[79076:0530/132835.062279:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present,`

**Comment by andreamah** [comment] 2023-06-02 14:47
verified on windows

**Comment by andreamah** [comment] 2023-06-02 14:50
verified on linux

**Comment by roblourens** [comment] 2023-06-02 16:05
Uh, I see this error

```
$ code-insiders --status
Cannot read properties of null (reading 'on')
```

**Comment by bpasero** [comment] 2023-06-02 19:35
**Verification**
* This needs verification on **macOS**
* have one code insiders window opened
* from the command line run `code-insiders --status`
* verify you see status related output
* verify you do not see Electron/Chrome related output such as `[79076:0530/132835.062279:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present,`

**Closed** 2023-06-02 19:35 UTC
Labels: bug, verification-found, good first issue, candidate, workbench-diagnostics, regression, code-cli

**Comment by meganrogge** [comment] 2023-06-02 19:38
when I run that, I see

```
Cannot read properties of null (reading 'on')
```

as the output

**Comment by joyceerhl** [comment] 2023-06-02 20:28
@meganrogge the next insiders should include the required changes for https://github.com/microsoft/vscode/issues/183787#issuecomment-1574220690
