### ISSUE TITLE
refreshing search results expands collapsed files in search results

### ISSUE THREAD

**Issue by vvavrychuk** [microsoft/vscode#203378] opened 2024-01-24 19:49 UTC
- VS Code Version: 1.85.2

Steps to Reproduce:

1. Open a folder in VS Code that contains some file.
2. In search menu search for some text present in file.
3. Collapse file in search results.
4. Press refresh button.

Problem: collapsed file expands.

https://github.com/microsoft/vscode/assets/152563/588edd00-c712-4033-855b-1156bfe3625b

**Comment by andreamah** [comment] 2024-01-26 18:19
[![Image from Gyazo](https://i.gyazo.com/70cb6ee4f9e740cc163bb6a7d6bfe4d0.gif)](https://gyazo.com/70cb6ee4f9e740cc163bb6a7d6bfe4d0)

Not sure if I can reproduce this on insiders. Does this reproduce on vscode insiders?

**Comment by andreamah** [comment] 2024-01-26 18:27
Nevermind, I had a setting enabled. With default settings, I can see the bug.

**Comment by osortega** [comment] 2024-12-18 00:13
I'm unable to reproduce this issue anymore.
I'll be closing it but @vvavrychuk please feel free to re-open if you are still having this problem

**Closed by osortega** 2024-12-18 00:13 UTC
Labels: bug, search
