### ISSUE TITLE
Go to definition (F12) doesn't work in node_modules with TS

### ISSUE THREAD

**Issue by DominicTobias** [Microsoft/vscode#45409] opened 2018-03-09 14:40 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 7

Steps to Reproduce:

1. Press F12 on an import in a node_module file

Behaviour:

Goes to the Typescript definition same as clicking "Go to Type Definition".

Expected:

Should go to the implementation.

**Comment by mjbvz** [comment] 2018-03-09 20:44
Duplicate of https://github.com/Microsoft/TypeScript/issues/6209 / https://github.com/Microsoft/TypeScript/issues/16792

**Closed by mjbvz** 2018-03-09 20:44 UTC
Labels: javascript
