### ISSUE TITLE
terminal zoom in not working

### ISSUE THREAD

**Issue by Hari1402** [microsoft/vscode#229800] opened 2024-09-26 08:19 UTC
Type: <b>Bug</b>

Hi i eanbled the "Terminal Integrated: Mouse Wheel Zoom"

and tried in the terminal and zoom out to reduce font size and later zoom in  not happening to increase the font size.

Even when i have use the cmd + = to zoom in entire editor in zoomed in. so that case my editor font size very big

<img width="914" alt="Screenshot 2024-09-26 at 1 27 24 PM" src="https://github.com/user-attachments/assets/dc7eca5a-a508-4b90-8c7d-c9a791dc5286">

[](url)

VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|18.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
gitlens|eam|15.5.1
prettier-vscode|esb|11.0.0
go|gol|0.42.1
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
makefile-tools|ms-|0.11.13
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
vs-code-prettier-eslint|rve|6.0.0
yeoman-ui|SAP|1.16.3
app-studio-remote-access|SAP|1.16.0
app-studio-toolkit|SAP|1.16.2
sap-guided-answers-extension|SAP|1.32.15
vscode-ui5-language-assistant|SAP|4.0.73
xml-toolkit|SAP|1.1.0
sap-ux-annotation-modeler-extension|SAP|1.15.0
sap-ux-application-modeler-extension|SAP|1.15.0
sap-ux-fiori-tools-extension-pack|SAP|1.15.0
sap-ux-help-extension|SAP|1.15.0
sap-ux-service-modeler-extension|SAP|1.15.0
vscode-cds|SAP|8.2.0
code-spell-checker|str|3.0.1

</details>

**Comment by meganrogge** [comment] 2024-09-30 19:59
not sure i'm following and I cannot reproduce the problem, thus closing.

**Closed by meganrogge** 2024-09-30 19:59 UTC
