### ISSUE TITLE
TypeScript Call Hierarchy view displays chevron for leaf items with no children in the right pane

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#89565] opened 2020-01-28 22:03 UTC
- VSCode Version: 1.42 Insiders
- OS Version: Windows 10

Found while testing #89386

The right pane list has chevrons (>) for all items even if they can't be expanded. Clicking on the chevron causes it to point down but no children are displayed.

![image](https://user-images.githubusercontent.com/12818376/73309348-ea6c6300-41d6-11ea-8187-bbf2b917b23b.png)

**Comment by jmbockhorst** [comment] 2020-01-28 22:18
I think this is related to #86311.

**Comment by jrieken** [comment] 2020-01-29 08:43
/duplicate of https://github.com/microsoft/vscode/issues/86311

**Closed** 2020-01-29 08:43 UTC
Labels: *duplicate
