### ISSUE TITLE
macOS Big Sur Icon Graphical Error on Low-DPI Display

### ISSUE THREAD

**Issue by KimchiTexMex** [microsoft/vscode#120782] opened 2021-04-08 06:33 UTC
The new Big Sur icon for VS Code seems to be glitched on Low-DPI displays, when sized down over a certain threshold.

I am using an external 27" 1080p external monitor with my MacBook Pro, and noticed that the icon displays improperly when made smaller, especially in the macOS launchpad.

Attached are some files that demonstrate the issue.
![Screen Shot 2021-04-08 at 3 32 53 PM](https://user-images.githubusercontent.com/64060168/113979077-c3e89400-987f-11eb-90db-8b67726da2fd.png)
![Screen Shot 2021-04-08 at 3 33 02 PM](https://user-images.githubusercontent.com/64060168/113979087-c945de80-987f-11eb-9aad-4beb4d2659c4.png)

**Comment by gjsjohnmurray** [comment] 2021-04-08 08:51
/duplicate of #120305 and will be fixed soon in 1.55.1

**Closed** 2021-04-08 09:36 UTC
