### ISSUE TITLE
Coloring issue with Peacock theme?

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#22058] opened 2017-03-06 11:09 UTC
Pls see the following twitter thread: https://twitter.com/AndrewNCassidy/status/837915671761543168

The original Peacock theme from color sublime has no red: http://colorsublime.com/?q=peacock.

Interestingly, the Peacock theme on the market place shows red tokens: https://marketplace.visualstudio.com/search?term=peacock&target=VSCode&sortBy=Relevance

**Comment by alexandrudima** [comment] 2017-03-06 14:11
Duplicate of #22054

**Closed by alexandrudima** 2017-03-06 14:11 UTC
Labels: themes
