### ISSUE TITLE
Unexpected js code format behaviour

### ISSUE THREAD

**Issue by franciscocpg** [Microsoft/vscode#15123] opened 2016-11-07 19:59 UTC
- VSCode Version: 1.7.1
- OS Version:
```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

Steps to Reproduce:

1. Create a file called test.js
2. Past this code `return <span>{amount} fixes</span>;`
3. Press `Ctrl+Shift+I` to format the code.

Then we have `return <span>{amount}fixes</span>;` (the white space between `{amount}` and `fixes` was removed). Why?

**Comment by waderyan** [comment] 2016-11-14 21:55
Duplicate of https://github.com/Microsoft/TypeScript/issues/11619

**Closed by waderyan** 2016-11-14 21:55 UTC
