### ISSUE TITLE
Simple Dialog breaks basename logic and fuzzy matching for recents list.

### ISSUE THREAD

**Issue by phyllisstein** [microsoft/vscode#75914] opened 2019-06-21 20:35 UTC
Hey Coders! I've been thoroughly enjoying the recently added Simple Dialog---but for this one glitch that's been driving me up the wall. The cause of the problem just hit me out of the blue, and I figured I would drop you a note.

The issue is that folders opened via the Simple Dialog are subtly broken when they appear in the Open Recent menu later. Whereas directories added via other methods---dragging and dropping, invoking `code`, etc---are listed with a name and a path, directories added through the Simple Dialog appear to be unnamed:

<img width="619" alt="Screenshot" src="https://user-images.githubusercontent.com/2207980/59948663-cd9ccf80-943e-11e9-85e3-d78b89b59876.png">

The UI glitch I could grumble about and live with, but it got a little maddening when I noticed that Code seems to prioritize items' names when fuzzy-matching recents. It also winds up creating mismatched duplicate entries:

<img width="625" alt="Screenshot" src="https://user-images.githubusercontent.com/2207980/59949285-ad6e1000-9440-11e9-9b62-4e73da607804.png">

I'm still riffling through the repo to confirm, but I think the problem is that Simple Dialog adds a trailing slash to the paths it stashes in Code's `storage.json`:

```diff
--- drag.json	2019-06-21 16:23:45.000000000 -0400
+++ simple.json	2019-06-21 16:23:55.000000000 -0400
@@ -2,10 +2,10 @@
     "id": "openRecentFolder",
     "uri": {
         "$mid": 1,
-        "external": "file:///Users/daniel/Repos/Personal/daniel.sh",
-        "path": "/Users/daniel/Repos/Personal/daniel.sh",
+        "external": "file:///Users/daniel/Repos/Personal/daniel.sh/",
+        "path": "/Users/daniel/Repos/Personal/daniel.sh/",
         "scheme": "file"
     },
     "enabled": true,
-    "label": "~/Repos/Personal/daniel.sh"
+    "label": "~/Repos/Personal/daniel.sh/"
 }
```

I can see how that might break some logic somewhere for extracting a folder's basename as a label.

Doesn't feel like it would call for an involved fix, so I'll keep digging and try to submit a PR. But I'd be grateful for a shove in the right direction. ✨

---

* VSCode Version: `v1.36.0-insider`
* OS Version: macOS 10.14.5

Steps to Reproduce:

1. Open the Simple Menu and navigate to a directory.
2. Press <kbd>Return</kbd>/<kbd>Enter</kbd> in the target directory's root to open it in VS Code.
3. Invoke the "Open Recent..." command to summon the recent items list.
4. :boom:

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2019-06-25 07:42
When you update your insiders version you should see that this is fixed now :) However, you'll need to open the folder without going through recents at least once so that a new recent is added with out the slash.
Duplicate of https://github.com/microsoft/vscode/issues/75847

**Closed by alexr00** 2019-06-25 07:42 UTC

**Comment by phyllisstein** [comment] 2019-06-26 05:53
Lovely! Thanks for the fix, and for the followup. Sorry I missed the dupe 🤦‍♂.
