### ISSUE TITLE
Node process freezes when initiating Webpack Hot Reload for React App in VS Code Debugger for more than 3 times

### ISSUE THREAD

**Issue by sceee** [microsoft/vscode#103498] opened 2020-07-28 15:41 UTC
Issue Type: <b>Bug</b>

We are using react hot reload for a react app.
When starting the node code in the VS Code debugger (old or new JS debugger, does not matter) using the following config
```
{
      "type": "pwa-node",
      "request": "launch",
      "name": "Debug",
      "program": "${workspaceRoot}/myapp.js",
      "preLaunchTask": "build",
      "skipFiles": [
        "<node_internals>/**"
      ],
    },
```
it starts the server and I can make changes to front-end files. React hot Reload notices this and webpack rebuilds the required bundles.
I can do this 3 times - beginning with the 4th change to a file, the node process (of myapp.js) completely freezes and I cannot make it to work again. So I have to stop the "debugging" session and start it again.
Note that there is no debugging involved - the node process is just started via the VS Code Debugger for convenience.

Now, if I execute `node myapp.js` in a regular Windows cmd (outside VS Code), I can make changes via VS Code to front-end files and hot reloading works as expected (unlimited times, never freezes).

So there seem to be an issue when starting the node process via VS Code that makes the process freeze after 3 "hot reload triggers (= 3 changes to files)".

This also happens when installing the preview JS Debugger extension.

Unfortunately, I have no idea how to trace this down further. I already disabled extensions to make sure they do not interfere here but with no luck.
The process explorer - once the node process freezes - shows 0% CPU for the process.
I cannot say for sure, but I feel we never noticed anything like this in previous versions of VS Code.

Is there anything I can do to trace this further down what could cause the issue?

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by weinand** [comment] 2020-07-28 16:26
Does it make a difference if you add a `"console": "integratedTerminal"` to your launch config?

**Comment by sceee** [comment] 2020-07-28 17:26
@weinand thanks for the fast reply and wow. Adding `"console": "integratedTerminal"` indeed makes a difference. After adding this it works again as intended.  Thank you very much.

I'm curious why this works with the `integratedTerminal`...

**Comment by connor4312** [comment] 2020-07-28 20:02
@sceee thanks for filing an issue, this is a duplicate of https://github.com/microsoft/vscode/issues/102254#issuecomment-658247768 which will be fixed in the upcoming VS Code release!

/duplicate

**Closed** 2020-07-28 20:03 UTC
Labels: *duplicate, debug

**Comment by sceee** [comment] 2020-07-28 20:19
@connor4312 ah okay, thanks for fixing it!
