### ISSUE TITLE
File icons are all missing after the recent insider update

### ISSUE THREAD

**Issue by pingshunhuang** [Microsoft/vscode#68473] opened 2019-02-11 23:39 UTC
- VSCode Version: 1.32-insider
- OS Version: Mojave

Steps to Reproduce:

1. Update the insider version
2. All file icons disappear

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment] 2019-02-12 09:26
I'm on
Version: 1.32.0-insider
Commit: 9441f43636a639aaffa28a9c7e6e36151944c8b3
Date: 2019-02-12T06:13:34.951Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic


and I still see file icons.

Also I tested that the update does not make changes to the setting.

Please explain what you exactly see. Are the icon themes still available?

**Comment by pingshunhuangalex** [comment] 2019-02-12 09:44
It happens for both my windows machine at home and Mac at work.

Could be the material theme I'm using. I'll open another ticket in the related repo. Might just be a bad timing if you can't reproduce it. Thanks.

![image](https://user-images.githubusercontent.com/17170199/52626297-006e0e80-2f07-11e9-9fed-718b712db970.png)

**Comment by pingshunhuangalex** [comment] 2019-02-12 09:53
Resolved. It's because the icons in the theme were split into a dedicated extension. Please close this issue. Thanks.

**Comment by sinclairzx81** [comment] 2019-02-12 12:53
@pingshunhuang Are you able to detail the steps to resolve this issue? I am having similar problems after using the material themes. Thanks :+1:

**Comment by sinclairzx81** [comment] 2019-02-12 13:54
@pingshunhuang Brilliant, that worked thanks ! :+1:

**Closed** 2019-02-26 08:43 UTC
Labels: extensions
