### ISSUE TITLE
Have to reload the vscode windows after changing emmet extensions

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29796] opened 2017-06-28 20:34 UTC
Testing #28465

I have `syntaxProfiles.json` like

```
{
    "html": {
        "tag_case": "upper"
    }
}
```

when I change it to `"lower"`, the change doesn't take effect until I restart vscode.

**Comment by ramya-rao-a** [comment] 2017-06-28 22:16
Duplicate of #19253

**Closed by ramya-rao-a** 2017-06-28 22:16 UTC
Labels: emmet
