### ISSUE TITLE
Untitled startup editor takes a long time to open

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#143053] opened 2022-02-14 19:13 UTC
Issue Type: <b>Bug</b>

This is a really annoying thing that started happening after the "Untitled-1" default document thing was added.

After launching a new window (ctrl-shift-N), and then immediately opening the 'Recent...' dropdown (ctrl-N) in the new window... while picking which recent folder to open, in the background, the "Untitled-1" document opens and then the 'Recent...' dropdown *automatically* closes.

This is _extremely_ frustrating. I don't want the "Untitled-1" document, I don't want the dropdown to automatically close in the middle of me using it.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (32.85GB free)|
|Process Argv|--crash-reporter-id 70645636-42ae-4864-b371-1810b42a2956|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2901)|
|Memory (System)|47.66GB (32.85GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.1.3
task-panel|Bit|0.2.0
auto-align|bla|0.0.13
js-codeformer|cms|2.6.1
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
autoscrolldown|fox|1.2.1
csharp-format-usings|gao|0.0.4
copilot|Git|1.7.5003
tab-indent-space-align|j-z|0.0.3
better-cpp-syntax|jef|1.15.13
vscode-nuget-package-manager|jmr|1.1.6
vscode-smart-column-indenter|lmc|0.0.13
react-javascript-to-typescript-transform-vscode|moh|1.10.0
language-gettext|mro|0.2.0
csharp|ms-|1.24.0
dotnet-interactive-vscode|ms-|1.0.3103010
vscode-dotnet-sdk|ms-|0.8.0
vscode-kubernetes-tools|ms-|1.3.6
jupyter|ms-|2022.1.1201831736
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.4
vsliveshare|ms-|1.0.5330
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-commons|red|0.0.6
vscode-xml|red|0.19.0
vscode-yaml|red|1.4.0
edit-with-shell|ryu|1.3.0
bash-beautify|sha|0.1.1
python|tht|0.2.3
php-debug|tia|0.1.6
pdf|tom|1.2.0
vscode-lldb|vad|1.6.10
vscodeintellicode|Vis|1.2.17
better-align|wwm|1.1.6
plsql-language|xyz|1.8.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2022-02-15 07:40
@Spongman just to clarify: you can configure `workbench.startupEditor` in settings to `none` and will no longer get an untitled editor, did you try?

**Comment by Spongman** [comment] 2022-02-15 08:58
@bpasero yeah, that works as a workaround. but the question still remains: why does the opening of the startup document close the active recent files dropdown?

**Comment by bpasero** [comment] 2022-02-15 09:04
@Spongman this is a setting. If you configure `workbench.quickOpen.closeOnFocusLost: false`, it will stay open even when focus looses.

**Comment by Spongman** [comment] 2022-02-15 09:06
but why is the focus lost? a background or default task should be stealing focus from a UI element that the user explicitly requested.

**Comment by bpasero** [comment] 2022-02-15 09:15
@Spongman we put focus into the editor to get a blinking cursor and allow to start typing. Unfortunately that seems to be a race condition to your request of opening the picker.

**Comment by bpasero** [comment] 2022-02-16 08:58
@Spongman anyway, I can measure it takes up to 500ms to open the untitled editor and think we can do better.

@lramos15 I debugged this a bit and noticed that we spend those 500ms resolving the editor for the untitled untyped editor input:

![Recording 2022-02-16 at 09 55 58](https://user-images.githubusercontent.com/900690/154229738-8ea2b883-9776-4229-b5bb-8cd31fb5bb86.gif)

Notice the lag until the editor opens. Somehow I cannot reproduce the same thing when I run Code to open a folder and file:

```
scripts/code.sh ~/Desktop/test-ts ~/Desktop/test-ts/package.json
```

Most time seems to be spend activating file system providers:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/services/editor/browser/editorResolverService.ts#L165

Any clues?

**Comment by bpasero** [comment] 2022-02-16 09:16
Further down I measure it takes `1ms` to activate `file` scheme and `500ms` to activate `untitled` and the source is here:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L196-L200

@jrieken need your brain as well here: any idea why this would be the case? Some theories:
* there is never going to be a `untitled` file system provider because `untitled` is not a registered file system provider
* are we maybe awaiting extensions having loaded in the case where a scheme is not yet known and return early since `file` is registered so early?
* is there any harm in hardcoding a solution for `untitled` that would not activate `untitled`, would that break existing extensions that maybe have been using `onFileSystem:untitled`?

**Comment by lramos15** [comment] 2022-02-16 14:05
@bpasero I'm not sure the resolver needs to wait for file system providers. I added that to solve https://github.com/microsoft/vscode/issues/133892 but it ended up not being the solution so I can remove that line and see if it is any faster.

**Comment by bpasero** [comment] 2022-02-16 14:12
@lramos15 oh yeah that would be great

**Comment by lramos15** [comment] 2022-02-16 14:18
Alright I went ahead and made that change, not sure if you want to wait for @jrieken's input or close the issue.

**Comment by bpasero** [comment] 2022-02-16 14:19
Yup, let's wait for his response and then close the issue out.

**Comment by bpasero** [comment] 2022-02-17 16:53
I wonder if @alexdima change in https://github.com/microsoft/vscode/commit/e356139a1095b92e0a89be34553aeedb24aa78c0#r66905487 actually would help here as well because I find it somewhat unlikely that the `onFileSystem:untitled` has any observers.

**Comment by bpasero** [comment] 2022-02-18 10:01
Hm understood, that does not really explain though why `onFileSystem:file` returns in `1ms` and `onFileSystem:untitled` needs `500ms`.

**Comment by alexdima** [comment] 2022-02-18 10:15
Maybe `IFileService` does not fire an `onWillActivateFileSystemProvider` for the `file` scheme?

**Comment by alexdima** [comment] 2022-02-18 10:22
Actually, it looks like the first `onFileSystem:file` does take a long time. Here is the diff I'm trying:
```patch
diff --git a/src/vs/workbench/services/extensions/common/abstractExtensionService.ts b/src/vs/workbench/services/extensions/common/abstractExtensionService.ts
index 6977fbe0006..254798dc735 100644
--- a/src/vs/workbench/services/extensions/common/abstractExtensionService.ts
+++ b/src/vs/workbench/services/extensions/common/abstractExtensionService.ts
@@ -192,10 +192,17 @@ export abstract class AbstractExtensionService extends Disposable implements IEx
 			(extensionId, extensionKinds, isInstalledLocally, isInstalledRemotely, preference) => this._pickRunningLocation(extensionId, extensionKinds, isInstalledLocally, isInstalledRemotely, preference)
 		);
 
+		let counter = 0;
+
 		// help the file service to activate providers by activating extensions by file system event
 		this._register(this._fileService.onWillActivateFileSystemProvider(e => {
 			if (e.scheme !== Schemas.vscodeRemote) {
-				e.join(this.activateByEvent(`onFileSystem:${e.scheme}`));
+				const id = (++counter);
+				const start = Date.now();
+				const timedPromise = this.activateByEvent(`onFileSystem:${e.scheme}`).then(() => {
+					console.log(`${id}. activateByEvent('onFileSystem:${e.scheme}') took ${Date.now() - start}`);
+				});
+				e.join(timedPromise);
 			}
 		}));
 
```

This is what I get as output:
```
32. activateByEvent('onFileSystem:file') took 2
33. activateByEvent('onFileSystem:file') took 10
34. activateByEvent('onFileSystem:file') took 9
35. activateByEvent('onFileSystem:file') took 0
36. activateByEvent('onFileSystem:file') took 1
37. activateByEvent('onFileSystem:file') took 1
38. activateByEvent('onFileSystem:file') took 1
39. activateByEvent('onFileSystem:file') took 0
40. activateByEvent('onFileSystem:vscode-userdata') took 0
41. activateByEvent('onFileSystem:vscode-userdata') took 0
42. activateByEvent('onFileSystem:file') took 0
43. activateByEvent('onFileSystem:file') took 1
44. activateByEvent('onFileSystem:file') took 0
45. activateByEvent('onFileSystem:file') took 0
46. activateByEvent('onFileSystem:vscode-userdata') took 0
47. activateByEvent('onFileSystem:file') took 1
48. activateByEvent('onFileSystem:file') took 0
49. activateByEvent('onFileSystem:file') took 1
50. activateByEvent('onFileSystem:file') took 0
51. activateByEvent('onFileSystem:file') took 1
52. activateByEvent('onFileSystem:file') took 1
53. activateByEvent('onFileSystem:file') took 1
54. activateByEvent('onFileSystem:file') took 0
55. activateByEvent('onFileSystem:file') took 0
56. activateByEvent('onFileSystem:file') took 0
57. activateByEvent('onFileSystem:file') took 0
58. activateByEvent('onFileSystem:file') took 0
59. activateByEvent('onFileSystem:file') took 1
60. activateByEvent('onFileSystem:file') took 0
61. activateByEvent('onFileSystem:file') took 1
62. activateByEvent('onFileSystem:file') took 1
1. activateByEvent('onFileSystem:vscode-userdata') took 1718
2. activateByEvent('onFileSystem:vscode-userdata') took 1717
3. activateByEvent('onFileSystem:vscode-userdata') took 1717
4. activateByEvent('onFileSystem:vscode-userdata') took 1688
7. activateByEvent('onFileSystem:vscode-userdata') took 1496
13. activateByEvent('onFileSystem:vscode-userdata') took 930
20. activateByEvent('onFileSystem:vscode-userdata') took 880
24. activateByEvent('onFileSystem:vscode-userdata') took 838
25. activateByEvent('onFileSystem:vscode-userdata') took 838
26. activateByEvent('onFileSystem:vscode-userdata') took 838
27. activateByEvent('onFileSystem:vscode-userdata') took 838
28. activateByEvent('onFileSystem:vscode-userdata') took 838
29. activateByEvent('onFileSystem:vscode-userdata') took 837
30. activateByEvent('onFileSystem:vscode-userdata') took 837
31. activateByEvent('onFileSystem:vscode-userdata') took 837
5. activateByEvent('onFileSystem:file') took 1681
6. activateByEvent('onFileSystem:file') took 1654
8. activateByEvent('onFileSystem:file') took 1497
9. activateByEvent('onFileSystem:file') took 1467
10. activateByEvent('onFileSystem:file') took 1432
11. activateByEvent('onFileSystem:file') took 1432
12. activateByEvent('onFileSystem:file') took 936
14. activateByEvent('onFileSystem:file') took 930
15. activateByEvent('onFileSystem:file') took 930
16. activateByEvent('onFileSystem:file') took 930
17. activateByEvent('onFileSystem:file') took 930
18. activateByEvent('onFileSystem:file') took 930
19. activateByEvent('onFileSystem:file') took 882
21. activateByEvent('onFileSystem:file') took 880
22. activateByEvent('onFileSystem:file') took 880
23. activateByEvent('onFileSystem:file') took 857
63. activateByEvent('onFileSystem:file') took 0
64. activateByEvent('onFileSystem:file') took 1
65. activateByEvent('onFileSystem:file') took 0
66. activateByEvent('onFileSystem:file') took 11
67. activateByEvent('onFileSystem:file') took 10
68. activateByEvent('onFileSystem:git') took 598
69. activateByEvent('onFileSystem:git') took 597
70. activateByEvent('onFileSystem:file') took 3
71. activateByEvent('onFileSystem:file') took 2
72. activateByEvent('onFileSystem:file') took 0
```

I'm not sure why later requests resolve sooner than the initial ones 🤔 . But the delay to wait for extension scanning is there also for `onFileSystem:file`.

**Comment by bpasero** [comment] 2022-02-18 10:31
Ah ok thanks for checking, I guess we then have to be really careful where we put code to `await` such a call as in this case it was slowing down opening the untitled editor substantially.

I think this is now understood and can be closed, thanks to Alex investigation.

**Closed by bpasero** 2022-02-18 10:31 UTC
Labels: bug, mitigated, workbench-editor-resolver
