### ISSUE TITLE
Unable to debug TypeScript project after VSCode update.

### ISSUE THREAD

**Issue by virtyaluk** [Microsoft/vscode#7745] opened 2016-06-15 22:14 UTC
- VSCode Version: 1.2.1 / 1.3.0-insider
- OS Version: Win 10 (10240)

My `launch.json`:

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/app.ts",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/js"
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858
        }
    ]
}
```

My `tasks.json`:

``` json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": ["--target", "ES5",
             "--outDir", "js",
             "--sourceMap",
             "--watch",
             "app.ts"],
    "problemMatcher": "$tsc"
}
```

Finally my `app.ts`:

``` js
console.log('foo bar');
```

It throws the error below no matter what I'm putting in `outDir`:

``` sh
Cannot launch program 'd:\Projects\web\training\ts-in-depth\app.ts'; setting the 'outDir' attribute might help.
```

It all worked well before the update.

**Comment by weinand** [comment] 2016-06-16 08:37
@virtyaluk I wasn't able to reproduce your problem on Windows 10.
Could it be that your filesystem at 'd:' is a shared filesystem that is also available via a UNC path?
What version of node.js are you using?

**Comment by ventis07** [comment] 2016-06-16 23:16
I have exactly the same problem for the past 5-8 days and have been battling with it. I'd also like to know how this will be resolved.

**Comment by weinand** [comment] 2016-06-16 23:33
@ventis07 nothing will resolve without reproducible steps or without answers to my question from above. No one in the VSCode team is able to reproduce this problem. So we need your help.

**Comment by ventis07** [comment] 2016-06-16 23:50
https://github.com/Microsoft/vscode/issues/7796 has just the steps that produced the error. If you want i can send you the 4 different project folders and see if you can make any sense of it.

**Comment by weinand** [comment] 2016-06-16 23:53
@ventis07 Could it be that your filesystem at 'd:' is a shared filesystem that is also available via a UNC path?
What version of node.js are you using?

**Comment by ventis07** [comment] 2016-06-16 23:56
I dont really understand the 1st first of your response, can you explain better or tell me what to check in literal terms
The version of node.js is v4.4.4

**Comment by virtyaluk** [comment] 2016-06-17 05:41
@weinand, yes, my project is on D drive.

```sh
C:\Users\virtyaluk
λ node --version
v5.10.0

C:\Users\virtyaluk
λ tslint --version
3.11.0

C:\Users\virtyaluk
λ tsc --version
Version 1.8.9
```

The point is that all worked fine before the update to 1.2.1. Nothing was changed in the configuration. The project is the same. Besides, I go through the steps described in the TypeScript course I'm learning now, and all the configs were taken from the course "Exercise files".

**Comment by weinand** [comment] 2016-06-20 14:17
@virtyaluk I still don't know what node.js version you are using.

Does it make a difference if you change your launch.config as follows:

```json
"program": "${workspaceRoot}/js/app.js",
```

So instead of launching your program from the TypeScript source, it will be launched from the generated JavaScript (which should live in the 'js' subfolder).

**Comment by virtyaluk** [comment] 2016-06-20 18:12
@weinand, as I mentioned earlier I'm using Node `v5.10.0`.

> Does it make a difference if you change your launch.config as follows:
> `"program": "${workspaceRoot}/js/app.js",`

Now I'm getting this:

```sh
Attribute 'program' does not exist ('d:\Projects\web\training\ts-in-depth/js/app.js').
```

It works fine if I'm using `tsc` from command line using arguments from `tasks.json`.

The only workaround for me now is to use more suitable TypeScript editor\IDE so i'm about to use WebStorm instead. Once issues with Code would be fixed I'll switch back.

Thanks!

**Comment by weinand** [comment] 2016-06-20 18:42
@virtyaluk it seems that you did not transpile your TypeScript into JavaScript: there seems to be no app.js in the 'js' directory. Did you run your build task?
Debugging won't work until a JavaScript file has been created.

**Comment by weinand** [comment] 2016-07-05 15:58
@virtyaluk any update on my last question?

**Comment by davidpiber** [comment] 2016-10-19 19:39
I have the same issue, I'm running vs code 1.6.1, on windows 8.1 enterprise edition.
I have a js directory with the compiled js file, here is my launch config file

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node2",
            "request": "launch",
            "program": "${workspaceRoot}/app.ts",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "outFiles": [],
            "outDir" : "${workspaceRoot}/js/app.js"
        },
        {
            "name": "Attach",
            "type": "node2",
            "request": "attach",
            "port": 9229,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outFiles": [],
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        }
    ]
}
![my set up](https://cloud.githubusercontent.com/assets/19769071/19534549/77577c76-9601-11e6-9368-268cfc46b70a.png)

**Comment by weinand** [comment] 2016-10-19 20:04
@virtyaluk if your generated JS files live in the 'js' folder, please use 'outFiles' like this:
```json
"sourceMaps": true,
"outFiles": [ "${workspaceRoot}/js/**/*.js" ]
```
Since `outDir` is deprecated, please remove it.

First try to use this with the old debugger by setting `"type": "node"`.

If that doesn't work, then try to use `"type": "node2"`.

/cc @roblourens

**Comment by ArnasAlex** [comment] 2016-10-19 20:06
Got same issue after updating VS Code.
VS Code 1.6.1
Node 6.5.0

{code}
 "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/server/index.ts",
            "stopOnEntry": false,
            "args": [],
             "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "integratedTerminal",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/dist/server/",
            "outFiles": [
                "${workspaceRoot}/dist/server/**/*.js"
            ]
{code}

Tried various configurations with outDir/outFiles.

*Folder/file structure*
/dist/server/index.js file: 
sourceMappingURL=maps/index.js.map

/dist/server/maps/index.js.map file: 
"sources":["index.ts"]
"sourceRoot":"../../../../server"
"file":"../index.js"

/server/index.ts - initial source file

**Comment by davidpiber** [comment] 2016-10-19 20:37
@virtyaluk, thank you this did the trick for me, this should be included on debugging configurations in MS page :).

**Comment by weinand** [comment] 2016-10-19 22:29
@davidpiber what did the trick for you?
I do not understand what we should document on the "MS page".

**Comment by davidpiber** [comment] 2016-10-20 00:44
changing "outFiles": ["${workspaceRoot}/js/**/*.js"] fixed my isssue.

**Comment by weinand** [comment] 2016-10-20 08:22
@davidpiber are you sure that you are really using the glob pattern: `"${workspaceRoot}/js/*/.js"]`?
I'm asking because that pattern would only find a file named exactly `.js` and nothing else.

**Comment by ricjac** [comment] 2016-12-07 00:47
I'm having the same issue:

When I run "App" from the launch.json file (pressing F5) I get the following message:
`Cannot launch program '/home/Src/site/server/index.ts'; setting the 'outDir or outFiles' attribute might help.`

But I have set the `outFiles` attribute (see the launch.json file below).

I've tried both "type": "node2" and "type": "node".

The "preLaunchTask": "build" runs a Gulp task that transpiles all TS files in "${workspaceRoot}/server/" and outputs to "${workspaceRoot}/dist/server/" 

OS: `Linux ant 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux`
VSCode: 
```
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
```

launch.json file:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "App",
            "type": "node2",
            "request": "launch",
            "program": "${workspaceRoot}/server/index.ts",
            "cwd": "${workspaceRoot}",
            "outFiles": ["${workspaceRoot}/dist/server/**/*.js"],
            "sourceMaps": true,
            "preLaunchTask": "build",
            "env": {
                "NODE_ENV": "production",
                "LOG_LEVEL": "debug"
            }
        }
    ]
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "allowJs": true
  },
  "include": [
    "./server/**/*.ts",
    "./server/**/*.js"
  ]
}
```

**Comment by ricjac** [comment] 2016-12-07 01:28
**Update:** It seems that the source files created using gulp don't allow debug, but when I use tsc, debugging works.

The sourcemap generation in Gulp wasn't setup correctly. After fixing it, it now works

./server/index.ts
```
module.exports = require('./app')();
```

# Using TSC

./dist/server/index.js (**tsc**)
```js
module.exports = require('./app')();
//# sourceMappingURL=index.js.map
```

./dist/server/index.js.map (**tsc**)
```json
{"version":3,"file":"index.js","sourceRoot":"","sources":["../../server/index.ts"],"names":[],"mappings":"AAAA,MAAM,CAAC,OAAO,GAAG,OAAO,CAAC,OAAO,CAAC,EAAE,CAAC"}
```

# Using Gulp

./dist/server/index.js (**gulp**)
```
module.exports = require('./app')();

//# sourceMappingURL=index.js.map
```

./dist/server/index.js.map (**gulp**)
```json
{"version":3,"names":[],"mappings":"","sources":["index.js"],"sourcesContent":["module.exports = require('./app')();\n"],"file":"index.js"}
```

**Comment by bmingles** [comment] 2016-12-12 15:12
@ricjac I see that your outFiles attribute seems to be pointing at a `dist` folder `"outFiles": ["${workspaceRoot}/dist/server/**/*.js"]`, but your `tsconfig.json` doesn't appear to build to that folder. Is there an extra copy step involved post-build? If so, your source maps may no longer map which could cause the issue.

**Comment by bmingles** [comment] 2016-12-12 15:19
In case anyone has tried setting `outFiles` to a glob pattern but still get this error, Make sure that your `tsconfig.json` is actually building source maps and that the output location still maps properly (aka. additional copy steps in build tasks could break the mapping). My issue was simply that I hadn't turned on source maps.

**Comment by Trixt0r** [comment] 2016-12-17 21:03
vscode tells me
`Cannot launch program '${workspaceRoot}\src\main.ts'; setting the 'outDir or outFiles' attribute might help.`
when running my application via F5.

launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Main Process",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/src/main.ts",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd",
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot/app/main.js" ]
        }
    ]
}
```

tsconfig.json:
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "app",
        "rootDir": "src",
        "sourceRoot": "src",
        "baseUrl": "src",
        "experimentalDecorators": true
    },
    "exclude": [
        "app",
        "builds",
        "bundle",
        "css",
        "less",
        "lib",
        "node_modules",
        "templates"
    ]
}
```
My `workspaceRoot`:
![vscode-debug](https://cloud.githubusercontent.com/assets/1076870/21289691/e0b412b2-c4a3-11e6-86e3-95b6ade2837f.PNG)

Source maps are generated with `tsc`.

Setting `"program": "${workspaceRoot}/app/main.js"` in `launch.json` works as expected.

**Comment by weinand** [comment] 2016-12-18 10:12
@Trixt0r does it help if you set outFile like this:
```json
"outFiles": [ "${workspaceRoot}/app/**/*.js" ]
```

**Comment by Trixt0r** [comment] 2016-12-18 10:17
@weinad No does not change anything. Also tested it without having `/app` in the path.

**Comment by weinand** [comment] 2016-12-18 10:39
But you've verified that the generated JavaScript lives under 'app'?

**Comment by Trixt0r** [comment] 2016-12-18 10:46
Yes, as you can see in the screenshot. And the app starts properly if I link `app/main.js` instead of `src/main.ts`.

**Comment by Trixt0r** [comment] 2016-12-18 10:48
I am running this on Windows 10 64bit, btw...

**Comment by weinand** [comment] 2016-12-18 13:54
The only remaining explanation is that you have sourcemaps with incorrect paths.
Please add `"trace": "all"` to your launch config and (if possible) post the output here.

**Comment by Trixt0r** [comment] 2016-12-18 14:42
Added `"trace": "all"` but nothing gets written to the debug console.

main.js.map looks like this:
```
{"version":3,"file":"main.js","sourceRoot":"c:/Users/trixt_000/yame/src/","sources":["main.ts"],"names":[],"mappings":";AAEA,MAAY,IAAI,WAAM,MAAM,CAAC,CAAA;AAG7B,2BAAoD,UAAU,CAAC,CAAA;AAE/D,8BAAgB,2BAA2B,CAAC,CAAA;AAC5C,yBAAmB,sBAAsB,CAAC,CAAA;AAE1C,4BAAsB,4BAA4B,CAAC,CAAA;AAEnD,IAAI,MAAM,GAAG,OAAO,CAAC,UAAU,CAAC,CAAC,MAAM,CAAC;AAExC;;;GAGG;AACH;IACI,MAAM,CAAC,OAAO,CAAC,WAAW,CAAC,CAAC;IAC5B,cAAG,CAAC,IAAI,EAAE,CAAC;IACX,MAAM,CAAC,IAAI,CAAC;AAChB,CAAC;AAED,cAAG,CAAC,WAAW,CAAC,YAAY,CAAC,oBAAoB,CAAC,CAAC;AAEnD,cAAG,CAAC,EAAE,CAAC,OAAO,EAAE;IACZ,4EAA4E;IAC5E,gCAAgC;IAChC,IAAI,OAAO,GAAG,IAAI,wBAAa,CAAC;QAC5B,KAAK,EAAE,GAAG;QACV,MAAM,EAAE,GAAG;QACX,IAAI,EAAE,KAAK;QACX,WAAW,EAAE,IAAI;QACjB,QAAQ,EAAE,KAAK;QACf,WAAW,EAAE,IAAI;QACjB,KAAK,EAAE,KAAK;KACf,CAAC,CAAC;IACH,OAAO,CAAC,WAAW,CAAC,EAAE,CAAC,iBAAiB,EAAE,MAAM,OAAO,CAAC,IAAI,EAAE,CAAC,CAAC;IAChE,OAAO,CAAC,OAAO,CAAC,UAAU,GAAG,IAAI,CAAC,OAAO,CAAC,qBAAG,CAAC,WAAW,EAAE,qBAAqB,CAAC,CAAC,CAAC;IAEnF,IAAI,MAAM,GAAG,IAAI,gBAAM,CAAC,YAAY,EAAE,EAAE,IAAI,EAAE,KAAK,EAAE,IAAI,EAAE,IAAI,EAAE,CAAC,CAAC;IAEnE,MAAM,CAAC,aAAa,CAAC,WAAW,CAAC,IAAI,CAAC,iBAAiB,EAAE;QACrD,IAAI,KAAK,GAAG,GAAG,CAAA;QACf,oEAAoE;QACpE,sCAAsC;QACtC,OAAO,CAAC,WAAW,CAAC,IAAI,CAAC,QAAQ,EAAE,KAAK,CAAC,CAAC;QAC1C,UAAU,CAAC;YACP,OAAO,CAAC,WAAW,CAAC,IAAI,CAAC,CAAC;YAC1B,MAAM,CAAC,aAAa,CAAC,IAAI,EAAE,CAAC;YAC5B,MAAM,CAAC,aAAa,CAAC,QAAQ,EAAE,CAAC;YAChC,EAAE,CAAC,CAAC,OAAO,CAAC,UAAU,EAAE,CAAC;gBACrB,OAAO,CAAC,KAAK,EAAE,CAAC;QACxB,CAAC,EAAE,KAAK,CAAC,CAAC;IACd,CAAC,CAAC,CAAC;IAEH,kBAAO,CAAC,EAAE,CAAC,gBAAgB,EAAE,CAAC,KAAK,EAAE,OAAO,EAAE,EAAE;QAC5C,EAAE,CAAC,CAAC,EAAE,CAAC;YACH,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,kBAAkB,EAAE,EAAE,EAAE,iBAAM,CAAC,cAAc,CAAC,OAAO,CAAC,CAAC,CAAC;QAC9E,IAAI;YACA,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,gBAAgB,EAAE,iBAAM,CAAC,cAAc,CAAC,OAAO,CAAC,CAAC,CAAC;IAC5E,CAAC,CAAC,CAAC;IAEH,kBAAO,CAAC,EAAE,CAAC,gBAAgB,EAAE,CAAC,KAAK,EAAE,OAAO,EAAE,EAAE;QAC5C,EAAE,CAAC,CAAC,EAAE,CAAC;YACH,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,kBAAkB,EAAE,EAAE,EAAE,iBAAM,CAAC,cAAc,CAAC,OAAO,CAAC,CAAC,CAAC;QAC9E,IAAI;YACA,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,gBAAgB,EAAE,iBAAM,CAAC,cAAc,CAAC,OAAO,CAAC,CAAC,CAAC;IAC5E,CAAC,CAAC,CAAC;IAEH,kBAAO,CAAC,EAAE,CAAC,eAAe,EAAE,CAAC,KAAK,EAAE,OAAe,EAAE,EAAU;QAC3D,IAAI,GAAG,GAAG,IAAI,mBAAS,CAAC,OAAO,CAAC,CAAC;QACjC,GAAG,CAAC,EAAE,CAAC,WAAW,EAAE,IAAI,IAAI,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,iBAAiB,EAAE,OAAO,EAAE,IAAI,CAAC,CAAE,CAAC;QAClF,GAAG,CAAC,EAAE,CAAC,UAAU,EAAE,GAAG,IAAI,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,iBAAiB,EAAE,MAAM,EAAE,GAAG,CAAC,IAAI,CAAC,CAAE,CAAC;QACnF,GAAG,CAAC,EAAE,CAAC,eAAe,EAAE,GAAG,IAAI,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,iBAAiB,EAAE,WAAW,EAAE,GAAG,CAAC,MAAM,EAAE,CAAC,CAAE,CAAC;QACjG,GAAG,CAAC,EAAE,CAAC,WAAW,EAAE,MAAM,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,iBAAiB,EAAE,OAAO,EAAE,GAAG,CAAC,MAAM,EAAE,CAAC,CAAE,CAAC;QACxF,GAAG,CAAC,EAAE,CAAC,WAAW,EAAE,CAAC,IAAI,KAAK,CAAC,MAAM,CAAC,IAAI,CAAC,iBAAiB,EAAE,OAAO,EAAE,CAAC,CAAC,CAAE,CAAC;QAC5E,GAAG,CAAC,IAAI,EAAE,CAAC;IACf,CAAC,CAAC,CAAC;IAEH,kBAAO,CAAC,EAAE,CAAC,WAAW,EAAE;QACpB,IAAI,MAAM,GAAG,IAAI,gBAAM,CAAC,YAAY,EAAE,EAAE,IAAI,EAAE,IAAI,EAAE,CAAE,CAAC;IAC3D,CAAC,CAAC,CAAC;AACP,CAAC,CAAC,CAAC;AAEH,cAAG,CAAC,EAAE,CAAC,mBAAmB,EAAE,MAAM,cAAG,CAAC,IAAI,EAAE,CAAC,CAAC"}
```
Where `c:/Users/trixt_000/yame` is my workspace root.

**Comment by Trixt0r** [comment] 2016-12-18 15:00
Okay, I found the problem... now I feel a little bit dumb...

`workspaceRoot` in `"outFiles": [ "${workspaceRoot/app/main.js" ]` is missing the closing braces -.-

Thanks for the help and sorry for the inconvenience.

**Comment by weinand** [comment] 2016-12-19 10:43
@Trixt0r great to hear that this now works for you.

**Closed by weinand** 2016-12-19 10:43 UTC
Labels: debug, needs more info

**Comment by roblourens** [comment] 2017-01-11 20:42
The `**` means 'search files in app/ and in any subdirectory of app/'. `app/*.js` would match only .js files directly under app/.

See the glob syntax here: https://github.com/isaacs/node-glob#glob-primer

**Comment by TitaneBoy** [comment] 2017-01-11 20:46
@roblourens : Oh, ok...Thank you for the quick answer. That's more clear now...  Thank you again  :-)

**Comment by ryanlangton** [comment] 2017-01-18 00:25
Are people actually able to DEBUG the typescript and hit breakpoints when you set the program to main.js instead of main.ts?  Because this is the issue I'm having.  If I point to main.js I can only set breakpoints in the javascript (not the typescript).  My program works and I have the output javascript  AND sourcemaps as expected, but I cannot debug typescript.  @Trixt0r I have the configuration you do.

**Comment by Trixt0r** [comment] 2017-01-18 11:01
@ryanlangton Worked for me with that config. Make sure, you did not copy the invalid version of my config.

**Comment by Kurara** [comment] 2017-02-10 08:12
Why the hell I updated this visual code. I'm in a hurry and I need to launch my project. First, it runs perfectly, after install, I have this in launch.json:

"program":"${workspaceRoot}/node_modules/gulp/bin/gulp.js",

But when I try to launch it it says:

Attribute 'program' does not exist  ('c:\J2EE\apps\EIBWebinfoAng2\gulp').

Where have "/node_modules/gulp/bin/gulp.js" gone?

**Comment by weinand** [comment] 2017-02-10 09:19
@Kurara I have no explanation for this. Could you share your launch config so that I can investigate?

**Comment by Kurara** [comment] 2017-02-10 09:39
of course @weinand 

```
{
            //Name of configuration.
            "name": "Compile glup",
            "type": "node",
            //Workspace relative or absolute path to the program.
            "program":"${workspaceRoot}/node_modules/gulp/bin/gulp.js",
            //Command line arguments passed to the program.
            "args":["build"],
            //Workspace path to the runtime to be debugged.
            "cwd": "${workspaceRoot}",
            //Enviroment variables passed to the program.
            "env":{}, 
            "sourceMaps": true

        },
        {
            //Name of configuration.
            "name": "run server webpack",
            "type": "node",
            //Workspace relative or absolute path to the program.
            "program":"${workspaceRoot}/node_modules/gulp/bin/gulp.js",
            //Command line arguments passed to the program.
            "args":["server"],
            //Workspace path to the runtime to be debugged.
            "cwd": "${workspaceRoot}",
            //Enviroment variables passed to the program.
            "env":{}, 
            "sourceMaps": true
        } 
```
server is a task in gulpfile, but it didn't enter into gulpfile so I don't think is there the problem. Althought I send it to you too:

```
var gulp = require('gulp'),
    rimraf = require('rimraf'),
    plugins = require('gulp-load-plugins')({
        lazy: true
    }),
    runSequence = require('run-sequence');

var paths = {
    dist: 'www',
    bootstrap: 'www/bootstrap' 
};

var fs = require('fs')
var gulpUtil = require('gulp-util');
var foreach = require('gulp-foreach');
var exec = require('child_process').exec;

gulp.task('server', plugins.shell.task([
    'webpack-dev-server --inline --colors --progress --port 3000']));
```

**Comment by weinand** [comment] 2017-02-10 10:00
What version of VS Code are you using? Stable (1.9.1) or Insiders (1.10.0)?

**Comment by Kurara** [comment] 2017-02-10 14:51
1.9.1

**Comment by weinand** [comment] 2017-02-10 15:20
@Kurara Your launch configurations are missing the request type (and this is flagged with a squiggly on the opening curly brace).
Please add `"request": "launch"` to both launch configs.
In 1.9.1 we started to rely on this attribute (but the error message is misleading).

**Comment by Kurara** [comment] 2017-02-10 15:30
Thanks @weinand ! :smile: now it works. Seems it tried to attach to an existing gulp as I didn't write launch :yum:

**Comment by weinand** [comment] 2017-02-10 15:32
I'm already improving the error reporting for this case...

**Comment by zwwtj2014** [comment] 2017-02-11 06:21
hello @weinand ,
vscode 1.9.1 tells me
Cannot launch program '${workspaceRoot}/src/server/search/oauth.ts'; setting the 'outFiles' attribute might help.
when running my application via F5.

but it works well when `.ts, .js, .js.map` in the same directory

:heavy_check_mark: config in lanch.json
```json
{
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/src/server/search/oauth.ts",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "outFiles": [
                "${workspaceRoot}/dist/out-tsc/**/*.js"
            ]
        }
```
Dir：
![image](https://cloud.githubusercontent.com/assets/8098249/22851680/c77389d0-f064-11e6-8b84-f5b616e5be3e.png)

**Comment by weinand** [comment] 2017-02-11 09:23
@zwwtj2014 what are the "sources" and "sourceRoot" entries in "oauth.js.map"?
You can add a `"trace":"sm"` to your launch configuration and share the information messages here.
Or you can try our new experimental node debugger by setting "type" to "node2".

**Comment by tomergev** [comment] 2017-10-13 23:12
I also got this error and I was wondering if anyone can help me because I am constantly using my debugger mode for work. Here is my launch.json file:

`{ // Use IntelliSense to learn about possible Node.js debug attributes. // Hover to view descriptions of existing attributes. // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387 "version": "0.2.0", "configurations": [ { "type": "node", "request": "launch", "name": "Launch Program", "program": "${workspaceRoot}\\bin\\www" } ] }`

And here is the error I have been receiving: Cannot launch program 'c:\PhD-Labs\eight-8\bin\www'; setting the 'outDir or outFiles' attribute might help.
