### ISSUE TITLE
Terminal cursor stays in the same line instead of moving to the bottom

### ISSUE THREAD

**Issue by yhlukhov** [microsoft/vscode#133982] opened 2021-09-28 11:05 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Quite often when stop your server (Ctrl+C), then realize that cursor stays in the same command line instead of moving to the bottom
2. see screenshot attached below
3. <img width="824" alt="2021-09-28_14h01_08" src="https://user-images.githubusercontent.com/1419892/135075408-c337298a-05b8-46ce-a108-27ae331e24a8.png">

**Comment by Tyriar** [comment] 2021-10-19 19:19
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2021-10-19 19:19 UTC
Labels: bug, terminal
