### ISSUE TITLE
Cannot commit when commit message starts with "#IssueNumber ..."

### ISSUE THREAD

**Issue by petval** [microsoft/vscode#84272] opened 2019-11-08 14:19 UTC
Issue Type: <b>Bug</b>

* Open git folder (I have one pulled from GitLab)
* Do some changes and use commit message "#NNN ..." where NNN is the issue number on GitLab
* Try to commit - nothing happens

This is probably not related to Gitlab at all and it started about 10 days ago. 

I must stage the files and then commit in terminal using
git commit -m "#NNN message"
or it works when I use full URL to the gitlab issue in the message

VS Code version: Code - Insiders 1.41.0-insider (fdeb9aa9b8306a2d3da989ccb9d2ad288d0ae347, 2019-11-08T05:28:30.394Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.41GB (19.08GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by IllusionMH** [comment] 2019-11-08 14:51
/duplicate of #84201 Should be fixed in Recovery Release

**Closed** 2019-11-08 14:51 UTC
Labels: *duplicate
