### ISSUE TITLE
`--disable-extension` flag is ignored when used for extension test run

### ISSUE THREAD

**Issue by EduardSergeev** [microsoft/vscode#107526] opened 2020-09-27 05:55 UTC
- VSCode Version: 1.49.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:  
1. Create extension and a test for it which starts VSCode with some built-in extension disabled via `--disable-extension [extension_id]` flag 
2. Try using disabled extension in test
3. Expected behaviour: disabled extension should not be available. Actual: it is alive and kicking.

NB: Extension does get disabled when VSCode is started with `--disable-extension [extension_id]`, but if the same flag is passed to `runTests` from `vscode-test` it seems to be ignored.

I created a sample repo which demostrates the problem: I simply modified your [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample) example which can be found here: [modified helloworld-test-sample](https://github.com/EduardSergeev/vscode-extension-samples/tree/disable-extension/helloworld-test-sample) to demonstrate the problem. Basically it tries to use `--disable-extension` flag to [disable vscode.git extension](https://github.com/microsoft/vscode-extension-samples/compare/master...EduardSergeev:disable-extension#diff-4912574376f996a07d74728363482ef4R28-R29) and then tries to [use git command](https://github.com/microsoft/vscode-extension-samples/compare/master...EduardSergeev:disable-extension#diff-f4bb71cf99e337958fbbad957719caa0R17) in test which is supposed to fail (with `vscode.git` disabled) but it doesn't.  
To see that `vscode.git` doesn't get disabled during the tests run you can also check the logs. I specify a custom [--user-data-dir](https://github.com/microsoft/vscode-extension-samples/compare/master...EduardSergeev:disable-extension#diff-4912574376f996a07d74728363482ef4R31) here so if you run this example with the following command:
```bash
CODE_VERSION=1.49.2 npm test
```
The log file located in `.vscode-test/vscode-1.49.2/udd/logs/[date]T[time]/exthost1/exthost.log` should **not** contain the line:
```text
[date time] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
```
but it does.  
Neither should the log file `.vscode-test/vscode-1.49.2/udd/logs/[date]T[time]/exthost1/output_logging_[date]T[time]/3-Git.log` be created, but it is.  
NB: If you manually start VSCode instance using exactly the same parameters as in this test, i.e.:
```bash
.vscode-test/vscode-1.49.2/VSCode-linux-x64/bin/code --new-window --disable-extension vscode.git --disable-extension vscode.github --extensions-dir .vscode-test/vscode-1.49.2/VSCode-linux-x64/extensions --user-data-dir .vscode-test/vscode-1.49.2/udd --disable-updates --disable-restore-windows --disable-telemetry
```
VSCode behaves as expected, i.e. `vscode.git` git extension is disabled so you will not see the above line in `exthost.log` and the log file `*-Git.log` will not be created.  

If you open source control tab it should look like that:
![image](https://user-images.githubusercontent.com/722409/94357013-77561c00-00d8-11eb-8e73-3df693795050.png)  

While in tests (the last one) it looks like that (git is enabled & active):
![image](https://user-images.githubusercontent.com/722409/94357061-d156e180-00d8-11eb-8dc8-929a893589c0.png)

Does this issue occur when all extensions are disabled?:  
We cannot disable **all** extensions here since we are testing our own extension

**Comment by EduardSergeev** [comment] 2020-09-27 06:46
The bug seems to be platform dependent:  
I added a [build configuration](https://github.com/EduardSergeev/vscode-extension-samples/commit/a153a430859d46ab92901090c5723101262cdf0c) to run it on [all 3 supported platforms](https://github.com/EduardSergeev/vscode-extension-samples/actions/runs/274852557/workflow) and apparently `--disable-extension [extension_id]` flag does work as expected in [tests on Windows](https://github.com/EduardSergeev/vscode-extension-samples/runs/1172013656?check_suite_focus=true#step:4:43) (the test is failing) but doesn't work on [Linux](https://github.com/EduardSergeev/vscode-extension-samples/runs/1172013642?check_suite_focus=true#step:4:49) or [Mac](https://github.com/EduardSergeev/vscode-extension-samples/runs/1172013671?check_suite_focus=true#step:4:55) (all tests are passing)

**Comment by sandy081** [comment] 2020-09-29 20:53
Assigning to @bpasero as it seems an issue with running test env. User confirms that it works when doing the same with VS Code directly.

**Comment by connor4312** [comment] 2021-10-13 21:42
Thanks for the logs and repro. I was able to confirm this is present in 1.49.2, but this appears fixed in the latest 1.61 release.

**Comment by connor4312** [comment] 2021-11-05 18:22
@roblourens to confirm are you test this via F5 or launching via the CLI? I can confirm this repro's in the former case, want to make sure we're seeing the same thing

**Comment by connor4312** [comment] 2021-11-05 19:51
Nevermind, it works for me -- didn't realize the disabled flags weren't passed in the launch.json. Adding those makes it work. Repro steps would be helpful.

**Comment by roblourens** [comment] 2021-11-05 20:09
There is a repo with this set up in the OP, I'm pretty sure I just used that

**Comment by connor4312** [comment] 2021-11-05 21:13
Resolved in DM -- the repro must use the CLI, F5 doesn't have --disable-extensions.

**Closed by connor4312** 2021-11-05 21:13 UTC
Labels: bug, needs more info, extensions-development
