### ISSUE TITLE
Sticky scroll results in cursor moving down several lines

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#205918] opened 2024-02-21 23:09 UTC
Testing #201450 on the latest Insiders on Windows

When the setting `editor.stickyScroll.maxLineCount` is set to 20, the cursor gets "stuck" in the bottom half of the editor even when there isn't that much nesting going on.

1. Navigate to the middle of a long file such as line 1800 of settingsTree.ts in the vscode repo.
2. Place the cursor near the top of the editor.
3. Use the up and down arrow keys, or start typing.
4. :bug: The cursor moves down several lines. On my small screen, it moves to the bottom of the editor right above the terminal.

CC @jcarrus though this behaviour might be by design.

**Comment by aiday-mar** [comment] 2024-02-22 08:34
Hi @rzhao271 thank you for posting this issue. The reason this happens is because when line 1800 is scrolled into position, we currently do not know how many sticky lines would be above this line. If we scroll too high up, and there are many sticky lines, this could hide line 1800. Hence we scroll so that we see 20 lines above the line of interest since 20 is the maximum number of sticky lines that can be shown.

This needs to be changed however, since we should be able to find the actual number of sticky lines that would be visible in the window if line 1800 were to be visible right below the sticky scroll widget.

**Comment by aiday-mar** [comment] 2024-12-12 16:35
duplicate of https://github.com/microsoft/vscode/issues/205918

**Closed by aiday-mar** 2024-12-12 16:35 UTC
Labels: bug, editor-sticky-scroll
