### ISSUE TITLE
Search does not support multiline regular expressions

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#38736] opened 2017-11-19 23:44 UTC
It would be useful to search across multiple files with multiline regular expressions.  Right now you can only do it with single line regexps.  Please add a button to toggle multiline.

**Comment by roblourens** [comment] 2017-11-20 06:21
/duplicate of https://github.com/Microsoft/vscode/issues/13155

**Closed** 2017-11-20 06:21 UTC
Labels: *duplicate, search
