### ISSUE TITLE
doc comment

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#34194] opened 2017-09-12 05:03 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.0
tslint|eg2|1.0.3
rest-client|hum|0.15.2
mssql|ms-|1.1.0
csharp|ms-|1.12.1
typescript-hero|rbb|1.4.1

---

Steps to Reproduce:

1. Annotate a method with a doc comment containing markdown.

2. Hover the method to observe rendered markdown in a hover tip.
![image](https://user-images.githubusercontent.com/5498936/30309259-ae59275a-97cd-11e7-818a-6c8ef967fd46.png)

3. Write some code that invokes the method. When you open parentheses a hover tip will appear containing the same markdown _unrendered_.
![image](https://user-images.githubusercontent.com/5498936/30309263-b42e1d0c-97cd-11e7-926a-3e6aeb872b55.png)

Reproduces without extensions: Yes

**Comment by PeterWone** [comment] 2017-09-12 05:12
Inconsistent rendering of doc comments.
Hovering a member produces a hover tip containing markdown rendered as HTML, per first illustration. 

![image](https://user-images.githubusercontent.com/5498936/30309056-6ce350a8-97cc-11e7-99b9-ae56b5fad644.png)

Typing the member name and opening the argument parentheses produces a hover tip in which the markdown has not been rendered as HTML, per second illustration.

![image](https://user-images.githubusercontent.com/5498936/30308958-e2790caa-97cb-11e7-92aa-57f2799197df.png)

**Comment by PeterWone** [comment] 2017-09-12 05:21
Syntax colouring is also missing.

**Comment by jrieken** [comment] 2017-09-12 08:54
dupe of #11877

**Closed by jrieken** 2017-09-12 08:54 UTC
Labels: extensions, new release
