### ISSUE TITLE
Sidebar is not open permanently

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#77521] opened 2019-07-17 12:45 UTC
#### Description
I always want to keep open sidebar, but everytime:
- if i open vs code with fresh session ( `-N i mean` ) ➡️ sidebar is close  
- if i open file with right click ( `edit with VSCode` ) ➡️ sidebar is close
- if i open new window ( `File > New Window` ) ➡️ sidebar is close
---
Of course, pressing `Ctrl + B` is not a big deal, but if I have to do it every day several times, it is very very frustrating 😞 . Can we do something with this?

Please let me know how I can set sidebar permanently open

---
#### Technical info
```
Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

#### Does this issue occur when all extensions are disabled?
Yes

**Comment by isidorn** [comment] 2019-08-05 12:36
We could introduce an option similar to `workbench.startupEditor`
Though I have no plans to tackle this now, thus leaving it open and assigning to backlog.

An alternative is to save this state globaly and not per workspace, which might make sense. Though it might also break other users behavior.

**Comment by kanlukasz** [comment] 2019-08-07 07:22
Thank you for the information.
I understand and look forward to developing this case. I hope you can do it. 

I think that the option satisfying everyone would be something like:
- `"workbench.startupSidebar"`

with the following options:

- [ ] always _(sidebar will always be open each time on startup)_
- [ ] never _(never show sidebar on startup)_
- [ ] one _(remember state from previous session)_

#### Related tickets:
https://github.com/microsoft/vscode/issues/63354
https://github.com/microsoft/vscode/issues/3742

**Comment by isidorn** [comment] 2019-08-07 08:14
Agree, let's close as duplicate of https://github.com/microsoft/vscode/issues/63354
And you can add your point of view in that issue. Thanks

**Closed** 2019-08-07 08:14 UTC
Labels: *duplicate, under-discussion, workbench-layout
