### ISSUE TITLE
Find in Folder, uses workspace name instead of the folder fspath

### ISSUE THREAD

**Issue by folke** [microsoft/vscode#108773] opened 2020-10-16 06:23 UTC
Version: 1.51.0-insider
Commit: 2ed16d0ce8713a5dfed9729071141be0ccf7fbec
Date: 2020-10-14T05:48:54.391Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

Steps to Reproduce:

1. create a new workspace
2. add a new existing folder to the workspace (for example tmp)
3. open workspace settings (JSON)
4. change the folder name to test
```json
{
  "folders": [
    {
      "name": "test",
      "path": "/home/foo/tmp"
    },
  ]
}
```
5. right click on the folder in the folder tree and choose "find in folder"
6. The "files to include" field will be populated with the workspace folder name instead of the folder fspath

Does this issue occur when all extensions are disabled?: Yes

----

The problematic code is at:
https://github.com/microsoft/vscode/blob/c7c471bdde61781c22ff16497c1d0af5e625f441/src/vs/workbench/contrib/search/browser/search.contribution.ts#L420

it should be something like the following instead:
```js
folders.push(result.stat.isDirectory ? result.stat.resource.fsPath : dirname(result.stat.resource.fsPath));
```

(Fixes https://github.com/folke/vscode-monorepo-workspace/issues/61)

**Comment by roblourens** [comment] 2020-10-16 23:54
This is by design if I understand correctly. It adds `./test` right? That's what you need to search that path.

**Comment by folke** [comment] 2020-10-17 07:32
I don't think this is by design, since the `name` attribute can be anything.

Other actions you can do when right-clicking the workspace folder like:
* Open in Integrated Terminal
* Reveal in Finder

The actions above work as expected and use the fsPath.

With the "Find in Folder", I get the following:
![image](https://user-images.githubusercontent.com/292349/96331180-169f6c80-1010-11eb-940e-48798ec296ce.png)

In the example above, the workspace folder name is `🚀 @splora/api`, but it would be the same issue if it would be called `test`

**Comment by folke** [comment] 2020-10-17 07:34
The relevant code for "Open in Integrated Terminal":
https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/workbench/contrib/externalTerminal/browser/externalTerminal.contribution.ts#L78

**Comment by roblourens** [comment] 2020-10-20 23:57
It's by design because I did design it that way :) the slash is the real issue https://github.com/microsoft/vscode/issues/61297.

I did that because there are cases where people add several folders with the same real folder name, but custom names to distinguish them, and this `./` syntax is special to select a workspace folder. Unfortunately it's then ambiguous with an actual path separator.

You could work around it by putting the absolute path in `files to include`, I know that is an annoying workaround.

**Comment by folke** [comment] 2020-10-21 05:39
I see. Maybe add something like the below to fix it?

```js
let findPath = stat.resource.contains(path.sep) ? stat.resource.fsPath : stat.resource
if (!stat.isDirectory) findPath = dirname(findPath)
```

This way, it will use the resource name when no slashes are in the name, and fspath otherwise.

**Comment by mathmul** [comment] 2020-10-30 08:11
This is still an issue.

`Find in Folder...` fails for any named workspace folders. This is not expected behavior.

## My example

I for one have one workspace per project. Let's say the website is 'company.com'.

Workspace name is 'company.com'.
There are three root folders in that workspace:
|- `c:\laragon\www\company.com`
|- `c:\unfortunately\long\path\to\files\that\are\uploaded\to\developement\server\for\clients\to\see\company.com`
|- `c:\production\www\company.com`

Where folders are named
- `LOCAL\company.com`
- `DEVELOPMENT\company.com`
- `company.com` (for release)
respectively.

Searching in a subfolder `company.com/subfolder` on development server results in `No folder in workspace with name: DEVELOPMENT` while `files to include` is auto-filled with `./DEVELOPMENT/company.com/subfolder`.

#### PS:

*Can someone please explain as well, why one would have to same path as root folder twice, but named differently?*

**Comment by roblourens** [comment] 2020-11-04 18:24
On one hand I would really like to close this as out-of-scope because naming your workspace folder with a / is the same as trying to put a / in a file name. But it keeps coming up and this is apparently something that people really want to do.

I could try to resolve the search path by removing segments one at a time until I find a matching workspace folder. But there is still an inherent ambiguity which is that if you have workspace folders `foo` and `foo/bar`, and I type `./foo/bar/file.txt`, do I want `bar/file.txt` inside `foo` or `file.txt` inside `foo/bar`?

**Closed** 2020-11-12 11:23 UTC
Labels: needs more info
