### ISSUE TITLE
Scrolling past end of document

### ISSUE THREAD

**Issue by ilithium** [Microsoft/vscode#54642] opened 2018-07-19 09:27 UTC
Issue Type: <b>Bug</b>

Open any file in VS code editor (I'm testing with a JavaScript file).

Scroll down. 

In my test cases, even with a short (24 line) file, the vertical scrollbar provides more scroll space than is needed, meaning that if you scroll down, you get a whole screen of empty, without line numbers.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.47GB free)|
|Process Argv|/private/var/folders/sw/nzwsgrd95pq507h7z5kcbxhh00jz5n/T/AppTranslocation/1353F2A6-92DA-4371-81B5-24EA459B7743/d/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1974754|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment] 2018-07-19 09:49
Duplicate of #54641

**Closed by alexandrudima** 2018-07-19 09:49 UTC
Labels: editor
