### ISSUE TITLE
Syntax highlighting in Typescript not handling identifiers that start with var correctly

### ISSUE THREAD

**Issue by kohzihan** [Microsoft/vscode#4620] opened 2016-03-23 16:25 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10 1511

Steps to Reproduce:

In a typescript file, have 
```javascript
let varName = "";
varName = "a";
```

The issue is that the 'var' substring in `varName` is highlighted the way the `var` construct would ordinarily be.

**Comment by kohzihan** [comment] 2016-03-23 17:06
Even worse is if you have ``varName = `...`;``, the rest of the document after the second backtick is colorized incorrectly...

**Comment by aeschli** [comment] 2016-03-24 08:39
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by aeschli** 2016-03-24 08:39 UTC
