### ISSUE TITLE
"Initializing JS/TS Language Features" appears every time I open a JS file

### ISSUE THREAD

**Issue by jacobweber** [Microsoft/vscode#71109] opened 2019-03-25 19:49 UTC
Issue Type: <b>Bug</b>

Every time I open a JS file, I get a CPU spike, and the message "Initializing JS/TS Language Features" in the status bar.

1. Disable all extensions.
2. Quit and re-launch VS Code.
3. Open a JS file. Message appears.
4. Wait for message to disappear.
5. Open another JS file. Message appears again.

Log file ID 3131084527 uploaded.

Result of `code --status`:
```
[78712:0325/124405.130134:WARNING:dns_config_service_posix.cc(174)] dns_config has unhandled options!

Version:          Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS Version:       Darwin x64 18.2.0
CPUs:             Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)
Memory (System):  16.00GB (1.22GB free)
Load (avg):       6, 4, 3
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                unavailable_off
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
   19	    98	 78305	code main
   22	    49	 78306	   gpu-process
   15	   246	 78307	   window (integration/setupTests.js — MyProject)
    0	    49	 78494	     watcherService
    0	    82	 78495	     extensionHost
  100	   934	 78549	       electron_node tsserver.js 
    0	    82	 78550	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 78541	     searchService
    0	    82	 78496	   shared-process
Workspace Stats:
|  Window (foo.js — MyProject)
|    Folder (MyProject): 10326 files
|      File types: svn-base(6131) js(1062) png(848) html(333) flat(306)
|                  class(235) md(196) json(167) xml(161) dex(147)
|      Conf files: package.json(33) jsconfig.json(1) settings.json(1)
|                  tasks.json(1)
```

Not happening for all projects. On the project where I'm seeing it, this is my jsconfig.json:
```
{
  "compilerOptions": {
    "target": "ES6",
    "jsx": "react",
    "module": "commonjs",
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./src/",
    "paths": {
      "*": [
        "*"
      ]
    }
  },
  "include": [
    "src"
  ],
  "exclude": [
	  "node_modules",
	  "build",
	  "tmp",
    "**/node_modules/*"
  ]
}
```

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment] 2019-03-28 02:57
Duplicate of #68896

**Closed by mjbvz** 2019-03-28 02:57 UTC
Labels: javascript
