### ISSUE TITLE
Allow to sort list of opened editors

### ISSUE THREAD

**Issue by gqshell** [Microsoft/vscode#15317] opened 2016-11-10 21:07 UTC
- VSCode Version: 1.7.1
- OS Version: Windows

It looks like you can "drag and drop" to re-sort the "open editors" list manually... but that's pretty tedious.  Can an option be added to have the file list automatically be sorted alphabetically?

Thanks!

**Comment by PunchyRascal** [comment] 2016-11-18 11:00
This is a duplicate of #12453

**Closed** 2017-05-28 15:27 UTC
Labels: explorer-files, feature-request
