### ISSUE TITLE
"Windows PowerShell" message line wrapped when opening integrated terminal

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6733] opened 2016-05-24 08:52 UTC
testing https://github.com/Microsoft/vscode/issues/6654:
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

When opening the integrated terminal I see this:
![2016-05-24 10-45-21](https://cloud.githubusercontent.com/assets/1898161/15497851/0456d484-219d-11e6-98d6-82b086a7ff86.png)

The message "Windows PowerShell" has a very large indent which makes it wrap at the edge of the view port. The native PowerShell console shows the message left aligned:

![2016-05-24 10-51-39](https://cloud.githubusercontent.com/assets/1898161/15497969/85b841d4-219d-11e6-9c19-fc0c836de366.png)

**Comment by Tyriar** [comment] 2016-05-25 18:29
Note that this is less important now with cmd.exe becoming the default (#6886).

This is what the HTML shows:

```
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;W</div>
<div>indows&nbsp;PowerShell</div>
```

**Comment by Tyriar** [comment] 2016-05-25 23:37
The follow data is received from Powershell:

```
"[?25l
[0m[0K
[1G[?25h"`
```

This is the one that adds all the spaces:

```
"[?25l
[64G[?25h"
```

```
"[?25l
Windows PowerShell[0K
Copyright (C) 2016 Microsoft Corporation. All rights reserved.[0K
[0K
[0K
[1G[?25h"
```

**Comment by Tyriar** [comment] 2016-05-25 23:48
Stepped through the code, the second message is `\e[?251\r\e[64G\e[?25h`

`\e[64G` sets the position of the cursor to 64 (ie. 63 as its 0-based)
`\e[?25h` runs: `this.cursorHidden = false;`

**Comment by Tyriar** [comment] 2016-05-25 23:53
We could intercept this message and fix this case, but the greater question is why Powershell would tell us to go to the 64th column. Powershell correctly passes `\e[1G` on most new lines with content.

**Comment by Tyriar** [comment] 2016-05-25 23:58
Compare this to the first message from cmd:

```
"[?25l
[0mMicrosoft Windows [Version 10.0.14342][0K
↵(c) 2016 Microsoft Corporation. All rights reserved.[0K
↵[0K
↵c:\Users\Daniel>[0K
[17G[?25h"
```

**Comment by Tyriar** [comment] 2016-05-25 23:59
@lzybkr sorry to bother you again, but have you got any ideas on this? Powershell seems to be telling our terminal to go to the 64th character for some unknown reason.

**Comment by lzybkr** [comment] 2016-05-26 00:28
PowerShell doesn't generate any VT100, and I don't see any code that sets the cursor position before displaying the logo - so I'm at a loss how that could happen.  The banner message doesn't even start out with any whitespace or newlines.

**Comment by Tyriar** [comment] 2016-05-26 00:48
Maybe it's pty.js doing this then, I'll have a look there thanks.

**Comment by Tyriar** [comment] 2016-05-26 01:17
Looks like this is where it happens, still looking into why: https://github.com/platformio/pty.js/blob/prebuilt/deps/winpty/agent/Terminal.cc#L372

**Comment by Tyriar** [comment] 2016-05-26 18:34
From my digging yesterday it seems like some obscure at the depths of the old version of winpty being used. Moving to backlog for now due to lower priority as well as no time to fix for May.

**Closed** 2017-02-16 20:17 UTC
Labels: bug, integrated-terminal

**Comment by Tyriar** [comment] 2017-02-16 20:20
While I can't reproduce this anymore, I believe this was happening because the shell process did not have dimensions set on start up. To verify:

- Verify powershell prompt doesn't wrap
- Install an extension that uses the terminal API such as Terminal Here and launch the extension terminal to ensure there are no exceptions. The main two cases to check are:
  - The terminal is yet to be created (hide terminal and reload window)
  - The terminal visible
