### ISSUE TITLE
!important not auto-completing correctly

### ISSUE THREAD

**Issue by marcemerson** [microsoft/vscode#120364] opened 2021-04-01 17:41 UTC
Issue Type: <b>Bug</b>

In a .css or .scss file, type " !imp" after a style. For intance you may have:

.country {
     text-transform: uppercase;
}

in your file. Then start typing the " !imp" like so:

text-transform: uppercase !imp;

Then hit the tab key, or click on the suggestiong of "!important" in the auto-complete suggestion from emmet. It will complete the line with the following:

text-transform: uppercase imp !important;

leaving the "imp " before "!important". It only seems to do this with !important, and not other auto-complete values.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id e6b619d1-2028-4ff7-ba25-20310da1aa78|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.9
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
auto-rename-tag|for|0.1.6
vscode-peacock|joh|3.9.1
csharp|ms-|1.23.9
vscode-typescript-tslint-plugin|ms-|1.3.3
cordova-tools|msj|2.2.0
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2
vscode-icons|vsc|11.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30265425
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by lramos15** [comment] 2021-04-01 18:45
duplicate of https://github.com/microsoft/vscode/issues/120245

**Closed by lramos15** 2021-04-01 18:45 UTC
