### ISSUE TITLE
FileSystemProvider: certain workspace folders break the integrated terminal

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#36758] opened 2017-10-23 15:04 UTC
- VSCode Version: Version 1.18.0-insider (1.18.0-insider) 65c08338e4bece35fb53f5a1cdf56d30b7706157, c1be82537d9fda852a258851f48ea78b7fc8a7a3
- OS Version: mac 10.12.6

Steps to Reproduce:
1. Create a `FileSystemProvider`
2. Have a certain provided folder in the workspace
3. Observe that `createTerminal({name: 'foo', shellPath: 'bash', shellArgs: ['-l', '-i']})` fails with this error message:
```
The terminal process command `bash -l -i` failed to launch (exit code: 1)
```
4. Try to open an integrated terminal (`ctrl + ~`) and observe:
```
The terminal process command `/bin/bash -l` failed to launch (exit code: 1)
```

Pretty much every call to `createTerminal` (i.e. trying different programs to run) will fail if certain provided folders are loaded in the workspace. I've not yet found a pattern to which folders cause this issue, but it's consistent for the affected folders. It does not matter which order the folder appears in the workspace (I've unsuccessfully tried setting a local folder as the first in hopes that vscode was trying to pick up the cwd or something from it).

**Comment by siegebell** [comment] 2017-10-23 15:20
I can sometimes see this very briefly appear in the integrated terminal:
```
chdir(2) failed.: No such file or directory
```

**Comment by siegebell** [comment] 2017-10-24 14:37
@jrieken this might also need a "remote" label

**Comment by jrieken** [comment] 2017-10-24 15:31
@Tyriar The terminal might miss a check that the selected workspace folder is a folder on disk, `file`-uri

**Comment by Tyriar** [comment] 2017-10-26 04:30
@jrieken tracked in https://github.com/Microsoft/vscode/issues/17450

**Comment by jrieken** [comment] 2017-10-26 07:35
closing as duplicate of #17450 then

**Closed by jrieken** 2017-10-26 07:35 UTC
Labels: integrated-terminal, remote
