### ISSUE TITLE
TypeScript Syntax Theme Colors Incorrect

### ISSUE THREAD

**Issue by bradenhs** [Microsoft/vscode#35639] opened 2017-10-05 19:29 UTC
VSCode Version: 1.17
OS Version: macOS 10.13

Steps to Reproduce:

1. Open a new file with vscode
2. Set the language to typescript
3. Paste the following:

```javascript
let i = 0;

function shouldBeThisColor() {

}

while(i++ < 12) { }

function butImThisColor() {

}
```

4. Go through a few different themes to see the issue.

![out](https://user-images.githubusercontent.com/22484684/31248385-8d62cae4-a9e1-11e7-921d-6849048ba571.gif)

Both functions should have the same colors applied to them but don't. I think it has something to do with the `i++ < 12` line.

**Comment by mjbvz** [comment] 2017-10-09 15:46
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/526

**Closed** 2017-10-09 15:47 UTC
Labels: bug, grammar, javascript, upstream
