### ISSUE TITLE
AutoSave no longer works

### ISSUE THREAD

**Issue by jwitoszkin** [Microsoft/vscode#21948] opened 2017-03-03 23:49 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|theme-desertex|casualjim|0.0.5|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.6|
|Theme-tonic|gerane|0.0.2|
|Theme-Zenburn|gerane|0.0.3|
|Python-autopep8|himanoa|1.0.2|
|cpptools|ms-vscode|0.10.0|
|java|redhat|0.0.9|
|comment-snippets|Tobiah|0.2.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1.   Set "files.autoSave": "onWindowChange" in settings.json
2.   Make a change to a file and change the window.
3.   The changes are not saved.

The same happens when set to onFocusChange

**Comment by bpasero** [comment] 2017-03-04 07:54
@objectuser @jwitoszkin do you have `editor.formatOnSave` enabled? Does it reproduce with extensions disabled? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces.

@jwitoszkin can you reproduce this all the time?

**Comment by objectuser** [comment] 2017-03-04 14:50
I have `"editor.formatOnSave": false`.

Unfortunately, this seems intermittent for me. I closed Code, ran `code --disable-extensions` and autosave works for both `onWindowChange` and `onFocusChange`. Then closed it out and just ran `code` and all is still well. (I'm verifying just by looking for the circle icon over the editor tab close icon. However, previously it's been easy to verify because _my_ code didn't work, which _never_ happens. :stuck_out_tongue_winking_eye:)

I experienced the same thing the last time I resolved the issue: after restarting Code, the problem went away for a while. Then the problem returned in the same session (i.e., without exiting Code). Next time it happened, I restarted and still had the problem, next time I didn't.

Summary: currently, I'm not able to reproduce the problem, though it happened multiple times yesterday.

**Comment by bpasero** [comment] 2017-03-06 07:33
@objectuser @jwitoszkin I pushed what I hope would fix this issue, can you give it a try from our insiders (nightly) builds and report back if you can still reproduce?

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by willkan** [comment] 2017-03-06 10:59
@bpasero I think your code fix the autoSave bug which I met too

**Comment by bpasero** [comment] 2017-03-06 12:41
@willkan awesome, please let me know if this changes and you get it again even in insiders.

**Closed** 2017-03-06 12:52 UTC
Labels: bug
