### ISSUE TITLE
MoveFile failed; code 183. Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by ritcoder** [Microsoft/vscode#4233] opened 2016-03-15 07:46 UTC
- VSCode Version: Latest as at this post (can't check since it will not run)
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code and wait for a update
2. Ask it to update
3. Error pops up. The file is `askpass.sh`
4. Try deleting the file causing the problem (didn't work on my machine)
5. Click ignore (VS Code Insider no longer runs

<img width="376" alt="2016-03-15 07_11_54-microsoft solitaire collection" src="https://cloud.githubusercontent.com/assets/254737/13770651/8d60098e-ea80-11e5-9727-d05e3d8947aa.png">

This is from the insider channel. When updating the main version, I got the same message, asked it to ignore. Currently, that instance crashes every few minutes. Not sure if the ignore was the cause.

Running from the command line gives the error below
`{ errorCode: 'load',
  moduleId: 'https-proxy-agent',
  neededBy: [ 'vs/base/node/proxy' ],
  detail: { [Error: Cannot find module 'https-proxy-agent'] code: 'MODULE_NOT_FOUND' } }`

**Comment by joaomoreno** [comment] 2016-03-15 08:40
Duplicate of #3560

Please reinstall Code

**Closed by joaomoreno** 2016-03-15 08:40 UTC
Labels: bug, important
