### ISSUE TITLE
Markdown doesn't highlight bold, italic, or inline code with line breaks

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#79064] opened 2019-08-13 18:30 UTC
Version: 1.38.0-insider (user setup)
Commit: ffa22b268f451b5211abbe2d2a47e6b753b55b1a
Date: 2019-08-13T07:27:53.993Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

Markdown syntax highlighting for inline styles is not working when there is a line break present in the text (ie to format code to avoid long lines). The text still renders as entirely italic in the preview, but no coloring appears.

For example, this should be all blue:
![image](https://user-images.githubusercontent.com/2294248/62967376-cce93f80-bdd6-11e9-9415-ba1c7930a0d3.png)

**Comment by mjbvz** [comment] 2019-08-13 20:01
Duplicate of https://github.com/microsoft/vscode-markdown-tm-grammar/issues/36

**Closed by mjbvz** 2019-08-13 20:01 UTC
