### ISSUE TITLE
Debug fails to detect launch targets in remote

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#118199] opened 2021-03-05 12:17 UTC
This is the vscode folder in WSL:

![image](https://user-images.githubusercontent.com/22350/110114521-a5b3e380-7d69-11eb-8e0f-fa06c52077e6.png)

**Comment by isidorn** [comment] 2021-03-05 13:27
I can not reproduce this with Docker + a repository with `launch.json`. Does this only repro for VS Code for you?
Unfortunately docker + VS Code repository does not work for me - I have informed @chmarti and he is investigating this issue.

It smells like some file reading is incorrect and the launch configuration does not get read or a file event is missing.
Best would be to put a breakpoint [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugService.ts#L245) and check what the `debugUx`  context gets set to. It should be `default` but probably for you it gets set to `simple`.

I can also investigate once vscode repo can be opened in docker.

**Comment by isidorn** [comment] 2021-03-05 15:05
@dbaeumer is also seeing this
@sandy081 did we change anything with regards to how configurations are read from a remote in the last couple of days?

**Comment by sandy081** [comment] 2021-03-05 15:14
@isidorn Yes, I changed reading of configuration files to be atomic (#117869)

https://github.com/microsoft/vscode/blob/bc444ac379788b2eb7453f85c16011ececc6fb8b/src/vs/workbench/services/configuration/browser/configuration.ts#L111-L111

@bpasero Does this change affects remote fs operations?

**Comment by isidorn** [comment] 2021-03-05 15:15
I pushed a try to get this fixed, not sure if it helps...
Will know more once I can repro on my machine.

**Comment by bpasero** [comment] 2021-03-05 15:17
The only thing `atomic: true` does is to wait for pending writes to finish and block new writes from starting before that finishes, nothing else.

**Comment by joaomoreno** [comment] 2021-03-08 10:14
@isidorn I can't repro today:

```
Version: 1.55.0-insider (user setup)
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:13:14.184Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by isidorn** [comment] 2021-03-08 10:44
@joaomoreno thanks for letting me know. Maybe @sandy081 pushed something
Would be interesting to see if @dbaeumer still see this

**Comment by dbaeumer** [comment] 2021-03-08 11:21
Works for me today.

**Comment by isidorn** [comment] 2021-03-08 12:52
Then it seems somebody pushed a fix for this. Maybe @sandy081 

Closing and let me know if you see it again and I can reopen.
Thank you and sorry about the breakage

**Comment by dbaeumer** [comment] 2021-03-08 14:45
Still seeing it in a different flow now. Reopening

![cast](https://user-images.githubusercontent.com/1931590/110336588-4aae1500-8025-11eb-8264-25e21b856ed5.gif)

**Comment by dbaeumer** [comment] 2021-03-08 14:46
Still seeing it in a different flow. Will create a screen cast.

**Comment by dbaeumer** [comment] 2021-03-08 14:48
![cast](https://user-images.githubusercontent.com/1931590/110336988-b42e2380-8025-11eb-9af1-e67fe24db629.gif)

**Comment by sandy081** [comment] 2021-03-08 16:31
@isidorn I have not pushed any changes.

**Comment by TylerLeonhardt** [comment] 2021-03-08 17:09
I just found this issue... opened a similar one here:
https://github.com/microsoft/vscode-remote-release/issues/4628

I will dupe that to this one

**Comment by isidorn** [comment] 2021-03-25 14:13
I just tried this following nice steps from https://github.com/microsoft/vscode-remote-release/issues/4628
And I still can not reproduce.

@TylerLeonhardt @dbaeumer @joaomoreno can you still reproduce this issue with latest? If someone can reproduce can you please ping me so we try to do a debugging session together? Thanks!

![Screenshot 2021-03-25 at 15 10 59](https://user-images.githubusercontent.com/1926584/112486677-654df100-8d7c-11eb-807d-ed42f8f61035.png)

**Comment by dbaeumer** [comment] 2021-03-25 15:10
I can't reproduce.

**Comment by isidorn** [comment] 2021-03-25 15:19
Thanks Dirk.
Closing for now. If somebody still sees this please let me know and I will reopen

**Closed by isidorn** 2021-03-25 15:19 UTC
Labels: bug, debug, needs more info
