### ISSUE TITLE
embedded <script> JavaScript code can not trigger VSC's JavaScript language support

### ISSUE THREAD

**Issue by scloudyy** [Microsoft/vscode#6306] opened 2016-05-12 03:13 UTC
- VSCode Version: 1.1.0
- OS Version: windows7

Steps to Reproduce:
1. In .html file, \<script type="text/javascript"\>and I want to write js code in  \<script\>\<script/\> ,but there is no Intellisense or syntax highlighting, is there any way to enable js code support in \<script\>?

**Comment by anyong** [comment] 2016-05-13 23:03
Dupe #1751 ?

**Comment by aeschli** [comment] 2016-05-23 13:48
duplicate of #3995

**Closed by aeschli** 2016-05-23 13:48 UTC
