### ISSUE TITLE
wrong tsx syntax highlight

### ISSUE THREAD

**Issue by clinyong** [Microsoft/vscode#30169] opened 2017-07-06 03:21 UTC
- VSCode Version: 1.13.1
- OS Version: macOS Sierra 10.12.5

wrong syntax

```tsx
import * as React from "react";

export const test = () => (
	WrappedComponent: React.ComponentClass<any>
) =>
class extends React.PureComponent<{}, {}> {

}
```

![image](https://user-images.githubusercontent.com/4192951/27894100-a7681eea-623c-11e7-80a4-73dafa89886c.png)

below is right

```tsx
import * as React from "react";

export const test = () => (WrappedComponent: React.ComponentClass<any>
) =>
class extends React.PureComponent<{}, {}> {

}
```

![image](https://user-images.githubusercontent.com/4192951/27894119-d0594360-623c-11e7-81e9-f328c1cff930.png)

This can be reproduced without extensions. And I am using `Dark+` color theme.

**Comment by mjbvz** [comment] 2017-07-06 20:57
This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/446 which has been marked as won't fix. Unfortunately, properly handling some multi line syntax patterns is very difficult using textmate grammars

**Closed by mjbvz** 2017-07-06 20:57 UTC
Labels: javascript, upstream
