### ISSUE TITLE
Tree view: Grandchildren of collapsed item not updated

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#54315] opened 2018-07-14 16:54 UTC
- VSCode Version: 1.25.1 (also tested in latest insiders build)
- OS Version: Arch Linux x64

Steps to Reproduce:
I have created a little [project](https://github.com/hbenl/vscode-tree-view-bug) demonstrating this bug: 
1. clone the project and run `npm install` and `tsc`
2. start the debugger - a new VS Code window opens containing a custom view called "BUG DEMO"
3. open that custom view and expand all nodes in it - the labels are `Root: 0`, `Child: 0` and `Grandchild: 0`
4. Click on "INCREASE COUNTER" - now the labels are `Root: 1`, `Child: 1` and `Grandchild: 1` (which is correct)
5. Collapse the root node, click "INCREASE COUNTER" and expand the root node again
Now the labels are `Root: 2`, `Child: 2` and `Grandchild: 1` - this is incorrect, the grandchild's label should be `Grandchild: 2`.
You can also see in the Debug console that after clicking "INCREASE COUNTER" the second time and expanding the root node again, only the root and child nodes are fetched, but not the grandchild.

**Comment by sandy081** [comment] 2018-07-15 18:53
Assigned to July milestone for investigation

**Comment by sandy081** [comment] 2018-08-29 15:30
@hbenl Looks like in your code you are using the same id `child` for all nodes. If you are providing an `id` it should be unique. 

`id` is optional and when it is removed the last step increase counter for all elements

**Comment by hbenl** [comment] 2018-08-29 15:40
But I'm only using this `id` for one of the 3 nodes:
```
const grandchildItem : BugDemoTreeItem = {
    id: 'grandchild', [...]
    children: []
};

const childItem: BugDemoTreeItem = {
    id: 'child', [...]
    children: [grandchildItem]
};

const rootItem: BugDemoTreeItem = {
    id: 'root', [...]
    children: [childItem]
};
```

**Comment by hbenl** [comment] 2018-08-29 17:41
I just tried with the latest Insiders build and the bug is still there:
![peek 2018-08-29 19-35](https://user-images.githubusercontent.com/16060807/44804887-fbb8d680-abc2-11e8-82d4-5adbbfd15c4c.gif)
The output in the debug console shows that the three nodes have different IDs `root`, `child` and `grandchild`:
```
Fetching root elements
Fetching 'root'
Fetching children of 'root'
Fetching 'child'
Fetching children of 'child'
Fetching 'grandchild'
Fetching root elements
Fetching 'root'
Fetching children of 'root'
Fetching 'child'
Fetching children of 'child'
Fetching 'grandchild'
Fetching root elements
Fetching 'root'
Fetching children of 'root'
Fetching 'child'
```
 Removing the IDs is not a good workaround as it means that the tree loses its collapsed state on every update:
![peek 2018-08-29 19-40](https://user-images.githubusercontent.com/16060807/44805041-71bd3d80-abc3-11e8-92db-75bfded32559.gif)

**Comment by sandy081** [comment] 2018-08-30 08:57
@hbenl You are right, it is also reproducible with `id` attribute.

**Comment by sandy081** [comment] 2018-09-03 21:32
To Verify:

- Open VS Code on a folder with following structure
```
- Folder A
-- Folder B
--- File C
```
- Expand to see `File C`
- Reveal File C in OS Explorer (Finder/File Explorer)
- Collapse `Folder A` in VS Code file explorer
- Rename `File C` to `File D` Outside VS Code (Finder)
- Refresh the File Explorer Tree in VS Code
- Expand `Folder A` in VS Code
- Verify that Folder B is expanded and showing `File D`

**Closed** 2018-09-11 15:14 UTC
Labels: bug, explorer-custom, tree
