### ISSUE TITLE
When I set the TreeItem collapsibleState in code to 'Collapsed' and after calling 'onDidChangeTreeData' event, it is not refreshed in the UI

### ISSUE THREAD

**Issue by fernandoescolar** [Microsoft/vscode#43879] opened 2018-02-17 08:14 UTC
- VSCode Version: 1.20.1
- OS Version: macOS 10.13.3

Steps to Reproduce:
I'm developing a solution explorer (like in Visual Studio) for vscode. One user ask for a "collapse all" button ([fernandoescolar/vscode-solution-explorer#1](https://github.com/fernandoescolar/vscode-solution-explorer/issues/1)). And I found a solution:
1. In the my custom TreeItem class I have created a function to collapse this item and all its children:
```
public collapse(): void {
	if (this.collapsibleState == vscode.TreeItemCollapsibleState.None) return;
	if (this.children) this.children.forEach(c => c.collapse());
	
	this.collapsibleState = vscode.TreeItemCollapsibleState.Collapsed;
	_onDidChangeTreeData.fire(this);
}
```
2. When I call this method in the root TreeItem, the collapsibleState is set right in the model, but it is not refreshed in the UI.

Notes:
- If I update the label or even if I change the collapsibleState to None, it works great.

**Comment by Gama11** [comment] 2018-03-25 20:02
We've had a "Collapse All" button in the Dependency Explorer of the Haxe extension of a while, and are also experiencing this issue. It broke with the 1.19.0 release.

Removing / adding a single whitespace from each root node's label works as a (pretty ugly) workaround for now.

**Comment by sandy081** [comment] 2018-03-26 09:09
Duplicate of #30918

**Closed** 2018-03-26 09:09 UTC
Labels: *duplicate, explorer-custom
