### ISSUE TITLE
on the one type file, vs code can't  distinguish more type language annotation

### ISSUE THREAD

**Issue by Cacivy** [Microsoft/vscode#14893] opened 2016-11-03 06:09 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.18, akamud.vscode-caniuse-0.5.3, bcmarinacci.theme-material-1.3.0, cssho.vscode-svgviewer-1.2.0, dbaeumer.vscode-eslint-1.0.8, dzannotti.vscode-babel-coloring-0.0.4, HookyQR.beautify-0.5.2, ionutvmi.path-autocomplete-1.1.0, johnpapa.Angular2-1.0.2, liuji-jim.vue-0.1.3, mrmlnc.vscode-jade-snippets-1.0.1, nikhilkumar80.js-patterns-snippets-0.0.5, qinjia.view-in-browser-0.0.3, robertohuertasm.vscode-icons-3.0.6, robinbentley.sass-indented-1.2.0, wcwhitehead.bootstrap-3-snippets-0.0.7, xabikos.JavaScriptSnippets-1.2.0, xabikos.ReactSnippets-1.2.0, zhuangtongfa.Material-theme-1.0.3

Steps to Reproduce:

1. open index.html
2. in style/script tag, ctrl + /, 
```html
<style>
	body {
		margin: 0;
	}
<style>
```
it will be
```html 
<style>
	<!--body {
		margin: 0;
	}-->
</style>
```
I want the result
```html
<style>
	/*body {
		margin: 0;
	}*/
</style>

```

**Comment by rebornix** [comment] 2016-11-03 17:28
A similar issue to https://github.com/Microsoft/vscode/issues/14661

**Comment by alexandrudima** [comment] 2016-11-07 17:19
@Cacivy please update to 1.7.1, the issue is fixed in the stable stream.

**Closed by alexandrudima** 2016-11-07 17:19 UTC
