### ISSUE TITLE
Spaces mishandling after line break display

### ISSUE THREAD

**Issue by Jojaba** [microsoft/vscode#69275] opened 2019-02-23 14:22 UTC
- VSCode Version: 1.31.1
- OS Version: Wndows 10

Steps to Reproduce:

1. Click on menu item "display >Toggle line breaks (english translation from french, sorry if this is not the right item name :/) Alt Z
2. Click again on the same item.

You can see that spaces have been added in your code wich can mess the file display (in my case, html links didn't work). 

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment] 2019-08-02 00:26
@Jojaba sorry for reaching out late. Could you please provide code sample to help troubleshoot?

**Comment by Jojaba** [comment] 2019-08-04 13:59
Sorry, can't reproduce the bug... What happened : when I switched to "Toggle Word Wrap" (in "View" menu) then reswitched to get no line breaks some spaces where added  in the html tags so that these tags where invalid and the content wasn't correctly formatted.
Hope you understood what i meant. Sorry for my poor english...
Regards

**Comment by rebornix** [comment] 2019-08-05 17:58
Thanks, it's a duplicate of https://github.com/microsoft/vscode/issues/47990 .

**Closed** 2019-08-05 17:58 UTC
Labels: *duplicate, needs more info

**Comment by Jojaba** [comment] 2019-08-05 18:06
Yes, that's it! thanks for taking this in account ;)
Regards.
