### ISSUE TITLE
Unable to open 'Settings': Tree element not found: [object Object].

### ISSUE THREAD

**Issue by ig0rkin** [Microsoft/vscode#69142] opened 2019-02-21 13:08 UTC
Issue Type: <b>Bug</b>

1. Open file
2. Open settings in new tab
3. Try to switch beetween them

P.S. Step 4
4. Set file tab as active and try to drag'n'drop 'Settings' tab

AR: Error Unable to open 'Settings': Tree element not found: [object Object].

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
beautify|Hoo|1.4.9
Angular-BeastCode|Mik|7.2.2
vscode-icons|rob|8.2.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2019-02-21 21:56
I can't reproduce this. Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by ig0rkin** [comment] 2019-02-22 10:25
Can't reproduce it today. Maybe I missed some step. I'll reopen this bug if it happens again.

**Comment by jvgille** [comment] 2019-03-12 16:40
I'm getting this too.
1. Open a file.
2. Open settings in new tab.
3. Select a setting such that it has mouse focus.
4. Switch tab to the file.
5. Switch back to settings using ctrl-tab

Immediately after switching back, the settings tab is closed and the error message displays.
If I switch back to settings by clicking the tab, it does not happen. The search box having mouse focus also does not trigger the bug.

The bug persists after disabling all extensions. I'm on version 1.32.1, Ubuntu 16.04.06, x64.

**Comment by roblourens** [comment] 2019-03-12 22:52
Thanks @jvgille, I see the issue.

**Comment by roblourens** [comment] 2019-03-12 23:06
This isn't pretty but we won't fix it in 1.32 because you have to trigger it in a particular way (setting must be focused, ctrl+tab to the settings editor), it's easy to work around or recover from, it doesn't cause data loss or anything like that, and I'm not 100% confident in the fix.

**Closed** 2019-03-12 23:46 UTC
Labels: bug, settings-editor

**Comment by mbedded** [comment] 2019-03-15 05:06
Maybe this is worth a re-opening. With the current version (1.32.3) i have the same error message.

Steps:
- i opened a local textdocument (let's call it "document1.txt")
- F1 > settings
- You are on the settings page now
- As example i change the font size
- CTRL + TAB: I switch to "document1.txt"
- Again CTRL + TAB: Expectation: See settings page. Reality: An error occurs

**Comment by roblourens** [comment] 2019-03-15 05:29
This is only fixed in Insiders, it will be fixed in 1.33.
