### ISSUE TITLE
Limit task output to most recent task only

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#44142] opened 2018-02-21 15:56 UTC
### Issue Type
Feature Request

### Description

I'd like the task output to 1) never show output from more than one task, and 2) not create a new terminal ~~instance~~ panel each time.

Using the "new" option ensures I'm only ever looking at the output for one task, but then I end up with a new terminal instance for every task run.

Using the "shared" option is closest to what I want, but it's rarely/never useful to me to be able to scroll up and see the output from the previous build. In fact, it gets in the way quite often as I scroll up too far and don't realize I'm looking at old task output, not the current task.

Ideally, I'd like the shared option, but have it clear the terminal each time. Adding 'cls' to the batch script I use to build doesn't clear the terminal ~~instance~~ panel.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

**Comment by dbaeumer** [comment] 2018-02-22 10:30
I can add an options to clear the terminal output, however we will not be able to share a terminal over two runs. The reason is that we couldn't find a way to determine whether a terminal is idle or not.  So we don't know when a task has finished.

**Comment by akbyrd** [comment] 2018-02-22 16:49
> I can add an options to clear the terminal output,

Perfect, thanks!


> however we will not be able to share a terminal over two runs

Wait, this is what VSCode already does with presentation.panel = shared.

Are we thinking of different behaviors when we say 'share a terminal'? In my case, I'm referring to the way the shared option doesn't create a new 'tab' in that drop down menu on the top right of the Terminal.

![task output](https://user-images.githubusercontent.com/484784/36551793-0b8942a0-17be-11e8-8855-15719a2eb89f.png)

**Comment by dbaeumer** [comment] 2018-02-23 09:09
The option `shared` shares the panel not the underlying terminal process. So yes, the panel can be shared the underlying terminal process which runs the task is not shared. So if you execute two tasks in a row then the create two terminal processes which both present their output in the same panel.

**Comment by akbyrd** [comment] 2018-02-23 16:14
Gotcha. I was referring to the ability to share the panel. I've updated to original wording to reflect that more accurately.

**Comment by BrianHarris** [comment] 2018-03-06 18:40
This should be supported with "panel": "dedicated" too.

**Comment by alexr00** [comment] 2018-10-22 08:50
@akbyrd, does #61329 solve this for you?

**Comment by alexr00** [comment] 2018-10-22 08:50
@akbyrd, does #61329 solve this for you?

**Comment by akbyrd** [comment] 2018-10-22 15:43
Yea, I think that will solve my problem nicely. Thank you!

**Comment by alexr00** [comment] 2018-10-23 08:18
Duplicate of #30058

**Closed by alexr00** 2018-10-23 08:18 UTC
Labels: feature-request, tasks
