### ISSUE TITLE
Multiple cursor paste pastes contents of all cursors

### ISSUE THREAD

**Issue by jtremback** [Microsoft/vscode#4996] opened 2016-04-06 05:01 UTC
- VSCode Version: 0.10.11
- OS Version: OSX 10.11.3

Steps to Reproduce:
1. Select something with multiple cursors
2. Cut or Copy.
3. Paste, and you will get the contents of all cursors at each cursor.

Sublime Text must have a clipboard per cursor because it will only paste the text that was selected by that cursor when you copied it.

**Comment by alexandrudima** [comment] 2016-04-06 07:56
@jtremback We do the same and it should work.

Is it possible that you change the count of cursors between copy and paste (e.g. you copy with 5 cursors, but then paste with 4 cursors). In other words, if the clipboard has N lines and you have N cursors, each line will go to each cursor. If the counts don't match, then each cursor will get all the content.

Do you have any ideas how to improve in this case?

**Comment by kumarharsh** [comment] 2016-05-16 11:43
@alexandrudima it doesn't work sometimes even when the counts *do* match perfectly. Take this code as a test case:

```
export const Texts = {
  a: {
    name: 'a',
    order: 0,
    label: (
      <FormattedMessage
        id="Phases.aPhase.label"
        defaultMessage="a"
        description="Text for the 'a' state of a object"
      />
    ),
    hint: (
      
    ),
  },
  b: {
    name: 'b',
    order: 1,
    label: (
      <FormattedMessage
        id="Phases.bPhase.label"
        defaultMessage="b"
        description="Text for the 'b' state of a object"
      />
    ),
    hint: (
      
    ),
  },
  c: {
    name: 'c',
    order: 2,
    label: (
      <FormattedMessage
        id="Phases.cPhase.label"
        defaultMessage="Knock-out"
        description="Text for the 'c' state of a object"
      />
    ),
    hint: (
      
    ),
  },
};
```

To see the behaviour, select the **first** `hint: (` text, press <kbd>Ctrl+D</kbd> twice to select the other two `hint: (` text also. Now, press <kbd>Up</kbd> arrow twice to go to the `/>` of the `<FormattedMessage...` JSX element, and position the multi-cursors at the **end** of those lines.

Now, select the whole JSX element, press <kbd>Ctrl+C</kbd>, bring back the cursors to the `hint` part and press <kbd>Ctrl+V</kbd>. All three occurrences are pasted thrice.

**Comment by alexandrudima** [comment] 2016-05-23 20:11
@kumarharsh Thank you! Oh, now I see what you mean, after the `ctrl+c` the clipboard contains:
```
      <FormattedMessage
        id="Phases.aPhase.label"
        defaultMessage="a"
        description="Text for the 'a' state of a object"
      />
      <FormattedMessage
        id="Phases.aPhase.label"
        defaultMessage="a"
        description="Text for the 'a' state of a object"
      />
      <FormattedMessage
        id="Phases.aPhase.label"
        defaultMessage="a"
        description="Text for the 'a' state of a object"
      />
```
Now when pasting, since there are 3 cursors and the clipboard contains 15 lines, all the text goes to all the cursors. I definitely need to think how to improve this, but thank you for clearing it up!

**Comment by kumarharsh** [comment] 2016-05-24 07:08
I ran into another bug today, where I had selected 5 lines using single cursor. Then, when I pasted this selection into 5 different places, vscode distributed one line to each cursor. This is counter-intuitive.

I think under the hood, vscode is mixing up the intents of single and multi-cursor selections, causing these problems.

Normally, I'd expect a text selected by using *single-cursor mode* to be **one entity**, which I can expect to paste in *N* different places. The subtle fact that `N` happens to equal `the number of lines of selected text` should not matter.

**Comment by atombender** [comment] 2016-11-28 17:46
Dupe of #10024?

**Comment by atombender** [comment] 2016-11-28 17:48
@kumarharsh I created a separate issue (#10024) for that case, i.e. when a single clipboard entry gets erroneously split across multiple cursors.

**Closed** 2017-12-14 17:10 UTC
Labels: bug, editor-multicursor

**Comment by alexandrudima** [comment] 2017-12-14 17:16
For verification, please follow the steps in https://github.com/Microsoft/vscode/issues/4996#issuecomment-219406531
