### ISSUE TITLE
Markdown preview doesn't resize properly on zoom (Ctrl++)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#18918] opened 2017-01-20 19:10 UTC
- VSCode Version: `1.9.0-insider` ee9d91c05fa571de56c41383cceee30b05b0a2f6
- OS Version: macOS Sierra `10.12.2`

This also happens on vscode `1.8`

Steps to Reproduce:

1. Open markdown preview
2. Press Ctrl++ to zoom in

![image](https://cloud.githubusercontent.com/assets/641685/22161772/c7e9dfe2-df19-11e6-8050-21fea11d59ec.png)

Its a bit hard to see but the the preview content isn't filling the whole area -- there is a big empty space on both the right and bottom.

**Comment by mjbvz** [comment] 2017-01-20 20:45
Thanks. Closing as a duplicate of #5745 since the MD preview uses a webview

**Closed by mjbvz** 2017-01-20 20:45 UTC
Labels: duplicate
