### ISSUE TITLE
Notebooks cannot be opened on 1.59

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#131040] opened 2021-08-17 21:55 UTC
Issue Type: <b>Bug</b>

Visual Studio Stable version doesn't open notebook (ipynb) files as anything but text.

I get this error in the developer tools console:

```
[vscode.ipynb]: Notebook type 'jupyter-notebook' already used.
```

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (48.37GB free)|
|Process Argv|--crash-reporter-id 2900f695-595f-4fc6-a76e-3da9117b78c6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|8.1.0
python|ms-|2021.9.1137256656-dev
vscode-pylance|ms-|2021.8.2-pre.1
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
typescript-hero|rbb|3.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsdfh931:30280409
vshan820:30294714
vscod805:30301674
bridge0708:30335490
dockerwalkthru:30344881
bridge0723:30353136

```

</details>

**Comment by joyceerhl** [comment] 2021-08-17 22:10
Just reproed this in 1.59. The default builtin ipynb doesn't appear as an option in the Open With... quickpick. I only get this: 
![image](https://user-images.githubusercontent.com/30305945/129807290-ba1ddeb4-27ee-4873-bd91-4fa9e628fc66.png)

**Comment by rchiodo** [comment] 2021-08-17 22:17
@joyceerhl do you get the error in the developer console?

**Comment by joyceerhl** [comment] 2021-08-17 22:25
Yes @rchiodo

**Comment by IanMatthewHuff** [comment] 2021-08-17 22:49
You're seeing this for all files? I don't currently repro this.

**Comment by rchiodo** [comment] 2021-08-17 22:51
Yeah for all ipynb files. I can only use the custom editor.

**Comment by rebornix** [comment] 2021-08-18 05:19
@rchiodo @joyceerhl can you check your settings and see if you have editor associations?

**Comment by rebornix** [comment] 2021-08-18 05:22
> [vscode.ipynb]: Notebook type 'jupyter-notebook' already used.

It seems that some extension registered jupyter-notebook type before the builtin serializer? We had this warning in OSS always but it was from the Jupyter extension previously.

**Comment by joyceerhl** [comment] 2021-08-18 15:00
I uninstalled all extensions and the problem persists

![image](https://user-images.githubusercontent.com/30305945/129922091-904d4e2c-9299-47b1-9d85-b680e9f8ffaf.png)

**Comment by joyceerhl** [comment] 2021-08-18 15:32
It looks like that error message is being logged because the notebook types are cached in globalStorage:

https://github.com/microsoft/vscode/blob/dd98268658431335b853fd58e29a77366ae6fe9f/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L65-L70

If I delete AppData\Roaming\Code\User\globalStorage\state.vscdb (could probably just delete the memento/notebookEditors key), I can open notebooks again and there's no error 

![image](https://user-images.githubusercontent.com/30305945/129927309-bb73f7b1-7a57-4aa8-b90c-4d04a84ddc3b.png)

**Comment by rebornix** [comment] 2021-08-18 15:47
@joyceerhl thanks, I'm not sure how we end up with that state. I tried following steps but didn't reproduce (maybe that explains why most ppl don't have such issue)

* Install old VS Code 1.58
* Install Jupyter
* Open notebooks
* Upgrade VS Code to 1.59
* Notebooks still open

@rchiodo can you try to delete `memento/notebookEditors` and see if it fixes the problem, please don't delete the `state.vscdb` then we can at least do some troubleshoot.

**Comment by rebornix** [comment] 2021-08-18 21:25
Fixed via https://github.com/microsoft/vscode/pull/131108

**Closed by rebornix** 2021-08-18 21:25 UTC
Labels: needs more info, candidate, notebook

**Comment by metazool** [comment] 2021-08-19 08:48
I saw the advice to `delete AppData\Roaming\Code\User\globalStorage\state.vscdb` (search for %appdata% in Windows 10) before the suggestion to just remove the `memento/notebookEditors` key from it (it's a sqlite db?). This did resolve the issue but only after [re-granting workspace trust](https://stackoverflow.com/questions/68417842/vscode-workspace-trust-how-do-i-know-if-workspace-trust-is-affecting-my-extensi) - hope you manage to get the fix into a new release soon!

**Comment by bpops** [comment] 2021-08-23 20:23
I also have this problem; tried uninstalling all extension, reinstalling. No .ipynb files will open as anything other than text, will save as nothing other than .txt file. So that I could do notebook work last week I reverted to 1.58 and had to also reinstall the python extension thereafter. Looking forward to a fix! Thanks for all the work you folks do; love the new notebooks.
