### ISSUE TITLE
Show dirty indicator close to file when tabs are disabled

### ISSUE THREAD

**Issue by metasong** [Microsoft/vscode#22709] opened 2017-03-16 01:55 UTC
show file modified circle on the title of the file when in Zen mode.
currently vscode will show the file modified circle icon in normal model.
![image](https://cloud.githubusercontent.com/assets/5009757/23978370/abd3e07e-0a2e-11e7-90a6-8fb08fd2f1dc.png)

**Comment by bpasero** [comment] 2017-03-16 12:59
@metasong the file dirty indicator is all the way to the right when tabs are disabled.

**Comment by bpasero** [comment] 2017-10-12 16:07
Suggest to close this as dupe of https://github.com/Microsoft/vscode/issues/19531

**Closed by bpasero** 2017-10-12 16:07 UTC
Labels: feature-request, workbench, workbench-tabs
