### ISSUE TITLE
Clicking two "Accept incoming changes" within 1 second causes second change to fail

### ISSUE THREAD

**Issue by lukehutch** [microsoft/vscode#191038] opened 2023-08-22 22:52 UTC
If you have two merge conflicts close together in your document, like this:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/6e0d2202-70ad-42f9-ac9f-0c42cab1152c)

and you click "Accept incoming changes" on both of them, less than 1 second apart, then the second change fails:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/e50860e7-3002-4380-91fe-61b2adb7e4f1)

 - Operating System version: Fedora 38
 - VS Code version: code-1.81.1-1691620770.el7.x86_64

**Comment by chrmarti** [comment] 2023-08-25 10:21
Duplicate of #107821.

**Closed by chrmarti** 2023-08-25 10:21 UTC
Labels: merge-conflict
