### ISSUE TITLE
git revert change error

### ISSUE THREAD

**Issue by lipengjgs** [microsoft/vscode#176601] opened 2023-03-09 06:53 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1.  modify the code from a git repo
2.  click left highlight bar to show local working changes window & click revert change
3.  will generate a lot of useless duplicate code
![revert-change-bug](https://user-images.githubusercontent.com/26566056/223943543-7bf85821-0709-4c6a-bdd8-43ab9b92324f.png)

**Comment by anthonyvdotbe** [comment] 2023-03-10 07:45
I assume this is a duplicate of #176051 and is thus fixed in 1.76.1?

**Comment by dawidd6** [comment] 2023-03-10 08:07
Yep, can confirm it is fixed with the latest release.

**Closed** 2023-03-10 14:33 UTC
