### ISSUE TITLE
Visual Code for Windows 10 doesn't restore all windows. On system fail.

### ISSUE THREAD

**Issue by MichelDiz** [Microsoft/vscode#35383] opened 2017-09-29 14:59 UTC
- VSCode Version: 1.16.1 2017-09-14
- OS Version: Windows 10 1703 Build 15063.608

Steps to Reproduce:

1.Open 3 projects. Separate. Force a turn off of the computer. To simulate a fail of energy or some power accident.
2. Reboot Windows. Reopen the VS code. Just opens one project that wasn't open before. 3 other project was gone.

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-09-30 04:21
@MichelDiz does it change if you configure `"window.restoreWindows": "all"`?

**Comment by MichelDiz** [comment] 2017-09-30 05:12
I'm using it from the beginning - forgot to report it.

**Comment by bpasero** [comment] 2017-09-30 05:23
Yeah, I think a crash like that is hard for us to restore properly because we keep the state of opened windows (and any UI state) only when shutdown happens normally. Related: https://github.com/Microsoft/vscode/issues/12058

**Comment by MichelDiz** [comment] 2017-09-30 06:12
Could do an "instant save" of the state used in each window. Tracking the user environments "live" and caching it. VScode has an "Save automatically" this tracking windows thing could be a native feature instead of a bug.

**Comment by bpasero** [comment] 2018-05-11 11:34
Closing as duplicate of https://github.com/Microsoft/vscode/issues/12058

**Closed by bpasero** 2018-05-11 11:34 UTC
Labels: bug, workbench-electron
