### ISSUE TITLE
Missing rule - Insert space after and before braces when format

### ISSUE THREAD

**Issue by Vadorequest** [Microsoft/vscode#18009] opened 2017-01-02 14:32 UTC
- VSCode Version: 1.8.1
- OS Version: OSX Yosemite

There is a rule `javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets` which allow to add space, but none for `braces`. Or I couldn't find it.

Related to https://github.com/Microsoft/vscode/issues/13401, seems it was possible before but since the behavior has been changed on TS directly, it doesn't seem to exist a way to setup this now for braces only. (the former rule would change the behavior for both braces and brackets, for what I could understand)

**Comment by mjbvz** [comment] 2017-01-03 19:42
I believe this is a duplicate of #18043. @Vadorequest Please let me know if this is not the case.

Thanks

**Closed by mjbvz** 2017-01-03 19:42 UTC
Labels: duplicate, format, javascript

**Comment by Vadorequest** [comment] 2017-01-03 19:48
@mjbvz Then I guess the issue is that there is no example of it in the settings file, that's why I couldn't find it. I guess that's a lack of documentation, rather than a missing feature. :)
