### ISSUE TITLE
Quick Fix shows at wrong position

### ISSUE THREAD

**Issue by taoqf** [microsoft/vscode#112813] opened 2020-12-18 12:51 UTC
- VSCode Version:1.52.1
- OS Version:Debian 4.19.146-1

Steps to Reproduce:

1. Edit a ts
2. Put mouse on a word
3. Quick fix shows at bottom of the words.
4. When I double click the word, the suggestion always blocks me, so I clicked the Quick fix button.

Does this issue occur when all extensions are disabled?: No
And sadly I could close the suggestion, only could delay it, I tried `"editor.quickSuggestionsDelay": 999999999` , nothing changed.
![Peek 2020-12-18 20-47](https://user-images.githubusercontent.com/15901911/102616582-bbeed200-4172-11eb-8922-4258fbc23d20.gif)

**Comment by gjsjohnmurray** [comment] 2020-12-18 13:10
> Does this issue occur when all extensions are disabled?: No

Please try using the new extension bisect command to discover if one of your extensions is causing this.

**Comment by alexdima** [comment] 2020-12-18 13:37
Duplicate of #112391

**Closed by alexdima** 2020-12-18 13:37 UTC
Labels: new release
