### ISSUE TITLE
Regression in 1.41.0: tsc is no longer run correctly when installed as devDependencies

### ISSUE THREAD

**Issue by WillAvudim** [microsoft/vscode#87006] opened 2019-12-15 01:08 UTC
- VSCode Version: 1.41.0
- OS Version: Linux Ubuntu

Steps to Reproduce:

1. Upgrade to 1.41.0
2. Ensure that typescript is not installed globally, only locally in the project as devDependency.
3. CTRL-SHIFT-p -> Tasks: Run Build Task
4. Output produced:

> tsc -p /home/user/p/test_project/tsconfig.json --watch <
> /bin/bash: tsc: command not found
> The terminal process terminated with exit code: 127
> Terminal will be reused by tasks, press any key to close it.

Does this issue occur when all extensions are disabled?: Yes

Downgrade to 1.40.2 fixes the problem.

tasks.json file:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558 
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "option": "watch",
      "problemMatcher": [
        "$tsc-watch"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

**Comment by RMacfarlane** [comment] 2019-12-15 01:30
Closing as a duplicate of https://github.com/microsoft/vscode/issues/86889

**Closed by RMacfarlane** 2019-12-15 01:30 UTC
Labels: new release
