### ISSUE TITLE
Make hover inspector window resizable

### ISSUE THREAD

**Issue by Hypernut** [microsoft/vscode#89455] opened 2020-01-28 13:00 UTC
The hover inspector window that pops up when you hover over a i.e. variable, is always to small for the content and displays scrollbars without any obvious reason.
I would like to have it either

- resize automatically to fit in the content or
- make it resizable or
- have a setting to adjust the standard size

Thanks!

**This issue was closed as "**duplicate**" before, without linking to the alleged "duplicate". So I searched and searched, but could not find any thread matching this. So please elaborate of which thread this is a duplicate or **do not close**.**
Edit: The little bugger is doin it again...

**Comment by IllusionMH** [comment] 2020-01-28 13:16
/duplicate of #56525
I think it will be useful to add your suggestions there.

> So I searched and searched, but could not find any thread matching this.

Yep, happens here. In this case I was able to find it with "is:issue is:open hover resize" query, that don't return too much results.

**Closed** 2020-01-28 13:16 UTC
Labels: *duplicate
