### ISSUE TITLE
Font stopped loading after upgrading to 1.95.

### ISSUE THREAD

**Issue by torgeirsh** [microsoft/vscode#232578] opened 2024-10-30 10:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95
- OS Version: Ubuntu 24.10

My settings.json file contains "editor.fontFamily": "Alegreya", but after upgrading to 1.95, I get a fallback font instead. Other fonts work, so it seems like the setting is being read correctly. The Alegreya font is installed in ~/.local/share/fonts, but shows up correctly in fc-list, the Gnome/GTK font selector, and can be used in other programs. Could the problem be that locally installed fonts don't work in 1.95? Is there a log or something that contains more information? The font loads if I revert to VS Code 1.94.2.

**Comment by ksandrj** [comment] 2024-10-30 10:27
I have same problem on Ubuntu 22.04

**Comment by Abhijith12371** [comment] 2024-10-30 10:46
The issue was resolved after updating the font cache with fc-cache -fv and ensuring the font was installed correctly in the system-wide fonts directory (/usr/share/fonts). After these adjustments, VS Code loaded the Alegreya font as expected. Closing this issue now. Thank you for the guidance!

**Comment by torgeirsh** [comment] 2024-10-30 11:04
@Abhijith12371 If it only works when installed in the system-wide directory, that's still a bug, so the issue shouldn't be closed.

**Comment by shadycuz** [comment] 2024-10-30 12:51
Same issue, fonts were installed into `~/.local/share/fonts` and they are now broken.

**Comment by smoglica** [comment] 2024-10-30 13:08
Same issue with Ubuntu 24.04.1 LTS

**Comment by deepak1556** [comment] 2024-10-30 14:20
Are affected users seeing the issue with snap package or deb package. Please provide the version information from `Help > About`

**Comment by deepak1556** [comment] 2024-10-30 15:09
Very likely regressed with this change https://github.com/microsoft/vscode/commit/2d28c0a79c87c70be93dbe73fe0a18fa12e0e7e9 where we now set `XDG_DATA_HOME` for snaps that overrides the global font config loading. Porting https://github.com/canonical/snapcraft/blob/187187d53d735d6f19dac7f474f321bd4c467f08/extensions/desktop/common/desktop-exports#L297-L340 should help address the issue.

**Comment by jvanatta** [comment] 2024-10-30 18:16
I'm having this issue too. My font installed in `~/.local/share/fonts` no longer works in 1.95. Ubuntu 20.
```
Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 5.15.0-122-generic snap
```

**Comment by shadycuz** [comment] 2024-10-31 01:06
@deepak1556  I'm using snap, I'm not sure what you mean by:
> Porting https://github.com/canonical/snapcraft/blob/187187d53d735d6f19dac7f474f321bd4c467f08/extensions/desktop/common/desktop-exports#L297-L340 should help address the issue.

Is that something users need to do? Or is that just notes about what needs to be done to fix the snap package?

**Comment by deepak1556** [comment] 2024-10-31 08:55
Thanks for confirming, I am able to repro the issue with snap and working on a fix.

@shadycuz that is just notes to self about the cause.

**Comment by alexr00** [comment] 2024-12-05 11:21
I can still repro on the latest insiders. Tested on 1.94 and I couldn't repro there.

**Comment by deepak1556** [comment] 2024-12-06 01:29
@alexr00 can you share the font and steps you have tried. I am unable to repro the issue.

**Comment by alexr00** [comment] 2024-12-06 09:37
Certainly!
- OS is Ubuntu 22.04
- Download the Fira Code font zip from https://github.com/tonsky/FiraCode/releases/tag/6.2 and unzipped using the UI
- I double clicked on each font in the ttf folder and used the "Install" button to install them all
- Opened LibreOffice Writer and tried out the Fira Code font there to make sure it had installed properly
- Set 
```
"editor.fontFamily": "Fira Code",
"editor.fontLigatures": true,
```
but the font wasn't used
- I then restarted checked again, but it still wasn't used.

**Comment by deepak1556** [comment] 2024-12-06 10:10
Thanks for detailed repro, I see the issue.

**Closed** 2024-12-06 10:34 UTC
Labels: bug, verification-found, linux, snap, confirmed, workbench-fonts
