### ISSUE TITLE
Disassembly view: Stepping should reset scroll position

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#129578] opened 2021-07-27 17:29 UTC
Testing #129161

@yuehuang010, @xisui-MSFT

When scrolling the current selected frame out of view if you click to step the viewport should scroll and return to the same position.

**Comment by yuehuang010** [comment] 2021-07-27 17:34
Step should "recenter" the current "yellow" instruction if it is out of
view.  Is this not the case?
The selection is only used for keyboard navigation.

**Comment by lramos15** [comment] 2021-07-27 17:38
> Is this not the case?

It wasn't doing that for me.

**Comment by xisui-MSFT** [comment] 2021-07-27 18:44
@xisui-MSFT will take a look

**Comment by xisui-MSFT** [comment] 2021-07-27 20:17
@lramos15 Unfortunately I wasn't able to repro this. Can you please provide more detailed repro steps?

**Comment by isidorn** [comment] 2021-07-28 07:53
Stepping also works fine for me. And every step should not center the line, that would not be smooth.
It should work just like stepping in an editor, which I think it does today. So I am not 100% sure what is the issue here.

**Comment by lramos15** [comment] 2021-07-28 14:25
What I meant is if you infinitely scroll in the disassembly view then step next it's pretty much to re-position yourself as you've scrolled hundreds of thousands of lines aware from where you were before.

**Comment by isidorn** [comment] 2021-07-28 15:44
Well if I scroll away from the position and step the yellow current line gets revealed. Is this not what you are seeing?

**Comment by lramos15** [comment] 2021-08-04 15:31
![recording (2)](https://user-images.githubusercontent.com/4544166/128209426-45bec3bf-4f9e-43a8-ac81-84bc6b08b60d.gif)
Sorry for my late response. Here's a recording showing that if you scroll upwards and then step next scroll position isn't reset and the yellow current line doesn't get revealed.

**Comment by isidorn** [comment] 2021-08-04 16:09
It usually gets revealed  for me, so this seems like a corner case. @xisui-MSFT can you try to reproduce and investigate?

**Comment by lramos15** [comment] 2021-08-04 16:30
> It usually gets revealed for me, so this seems like a corner case. @xisui-MSFT can you try to reproduce and investigate?

Yeah I think it has to do with scrolling a lot in the infinite scroll

**Comment by xisui-MSFT** [comment] 2021-08-06 00:41
Looks like a mock debug issue. @weinand Can you please change the mock debug so it won't show negative addresses?

**Comment by rzhao271** [comment] 2024-12-19 16:30
Assigning to Connor for further triage

**Comment by connor4312** [comment] 2024-12-19 18:03
This works for me nowadays.

**Closed by connor4312** 2024-12-19 18:03 UTC
Labels: debug, under-discussion
