### ISSUE TITLE
Extension Host Process can be completely overwhelmed by file system event during background builds, and make extensions stop to response user actions 

### ISSUE THREAD

**Issue by lifengl** [microsoft/vscode#194341] opened 2023-09-27 19:04 UTC
VS code extension host can be completely overwhelmed by file watcher events, and during that period of time, extensions will stop responding to user actions.
 
Does this issue occur when all extensions are disabled?: No  

- VS Code Version:  1.82.2
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0

- OS Version: 
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:
1.  Get latest OrchardCore, open workspace on the root of the repo
2. try to use latest C# Dev Kit extension, expand the solution explorer tree
3.  start to clean build the solution, either through the extension or on the command line with a different windows terminal
4. wait build really starts to compile projects (after the initial NuGet restores)
5. try to expand the solution explorer item, it spins forever (will resume only after a long time even build ends)
6. other extension will stop responding in a similar way

Take a CPU profile with vs code built-in development tool, the extension host is completely blocked by file system events.

![image](https://github.com/microsoft/vscode/assets/11638466/800fec40-338a-4807-a16d-0cec11738634)

**Comment by lifengl** [comment] 2023-09-27 19:04
+ @isidorn

**Comment by bpasero** [comment] 2023-09-28 07:09
@lifengl for this case it would probably make sense to exclude more directories from watching via the `files.watcherExclude` setting. Can you find the origins of the large amount of file events and try to configure the setting accordingly? We can think about pushing more patterns to our default exclude list so that it applies to all our users:

https://github.com/microsoft/vscode/blob/aad333b878b4cfce2f4152d48552fb6f980d7daf/src/vs/workbench/contrib/files/browser/files.contribution.ts#L261-L269

**Comment by bpasero** [comment] 2023-09-28 10:20
fyi @jrieken on the perf trace that seems to spend a substantial time in `uri.fsPath`. I call it here:

https://github.com/microsoft/vscode/blob/b792feb9edb70197d220b39cc64fe3bf71b4e88a/src/vs/workbench/api/common/extHostFileSystemEventService.ts#L64-L89

To figure out if the extension provided pattern matches the event path. If you have ideas how to make this more efficient, please let me know. Maybe there could be a "fast" variant of `.fsPath` that still works with our glob library but is less correct since we do not use this path actually in node.js

**Comment by jrieken** [comment] 2023-09-28 10:29
> Maybe there could be a "fast" variant of .fsPath that still works with our glob library but is less correct since we do not use this path actually in node.js

Why do we use `fsPath` to begin with? Isn't `path` the better and more correct approach anyways? Do glob patterns support UNC roots and backward slashes?

**Comment by jrieken** [comment] 2023-09-28 10:44
@lifengl Can you please share the profile that you captured? I don't see this with a similar setup (npm install and watching node_modules) but it might be OS specific. On macOS I see nice, smallish chunks for events that get processed without much blocking

**Comment by bpasero** [comment] 2023-09-28 10:51
@jrieken yeah I think `.path` is fine on Linux and macOS. On Windows here is the difference I observe:
* `c:\foo\bar` becomes `/c:/foo/bar`
* `\\localhost\c$\foo\bar` becomes `/c$/foo/bar`

Our glob lib can deal with backslash vs slash fine, i.e. ignores the difference. But I think the leading `/` and the fact that the UNC authority is not there can be an issue for patterns.

**Comment by lifengl** [comment] 2023-10-02 21:02
I sent CPU profiles captured earlier to you.  it seems to be that Roslyn team chained events, so they may have better ideas on the patterns they have.  During build, lots of output items are .dll/.pdb and other files. The number might be exploded due to projects referencing others are coping referenced output into its own output folder.

I wonder certain limited globbing patterns can be matched more efficiently without converting a file path, especially ones matching file extensions or an exact file name like **/*.cs can be efficiently checked with Uri.  patterns like [BasePath]/**/*.[Extension] might be quite common in real usages.

**Comment by lifengl** [comment] 2023-10-02 21:09
also, another consideration is that fsPath will be called once per-watcher registration, and each time it would create a new string, so when an extension adds many watchers (maybe for different folders), it can grow to be a scalability problem.

**Comment by bpasero** [comment] 2023-10-03 03:49
One relatively easy optimization would be to re-use the same `URI` for each watcher so that the calls to `fsPath` are shared. Looks like we do create a new `URI` for each handler over and over:

https://github.com/microsoft/vscode/blob/ce01d80f8e502994c56de671813462b03b5bdf8b/src/vs/workbench/api/common/extHostFileSystemEventService.ts#L66-L71

**Comment by jrieken** [comment] 2023-10-03 06:47
All optimisations aside we can always have a case in which it is just too much. So, in addition to perf fixes we should emit the events in smaller chunks and "pause" in-between

**Comment by bpasero** [comment] 2023-10-03 09:47
Opened https://github.com/microsoft/vscode/pull/194697 to re-use `Uri` and not `revive` it per-watcher. Maybe in this setup here there are tens or hundreds of file system watchers created by the extension?

We do throttle file events since a long time given other similar issues:

https://github.com/microsoft/vscode/blob/ddf9e9266472c0919e601a1d7a390c8ee0ade355/src/vs/platform/files/node/watcher/parcel/parcelWatcher.ts#L97-L104

This throttling happens at the source where we receive them from `parcel-watcher`. We do add a warning to the logs in case events are throttled. @lifengl can you maybe share your VS Code logs to use so that I can try to find it?

**Comment by jrieken** [comment] 2023-10-03 10:58
> This throttling happens at the source where we receive them from parcel-watcher. We do add a warning to the logs in case events are throttled.

I that case I wonder why the EH stops responding. If the chunks are overly large and the machines not overly slow nothing should be blocked but saturated.

**Comment by jrieken** [comment] 2023-10-03 11:05
> Opened https://github.com/microsoft/vscode/pull/194697 to re-use Uri and not revive it per-watcher, so that only the first user of .fsPath triggers the compute. Maybe in this setup here there are tens or hundreds of file system watchers created by the extension?

That's a good change but I doubt the extension has very many file watchers. 

I am still wondering if we can avoid using and computing `fsPath` to begin with. Can't the glob matcher know cases when it doesn't matter? Like all `*.SUFFIX` or `**/*.SUFFIX` don't need an uri authority, right?

**Comment by jrieken** [comment] 2023-10-03 11:08
Alternative trick/hack to avoid recomputing `fsPath` is to trigger its computation in the file watching process. That will populate the property and make it part of the toJSON and revive cycle

**Comment by bpasero** [comment] 2023-10-03 17:47
> I am still wondering if we can avoid using and computing fsPath to begin with. Can't the glob matcher know cases when it doesn't matter? Like all *.SUFFIX or **/*.SUFFIX don't need an uri authority, right?

I had thought about it, in the end what we really want is `Uri` support in `Glob` to defer `.fsPath` compute as much as possible. We just do not have that capability today.

> Alternative trick/hack to avoid recomputing fsPath is to trigger its computation in the file watching process. That will populate the property and make it part of the toJSON and revive cycle. Also the renderer, which likely also does glob matching, could benefit from that

I like

**Comment by bpasero** [comment] 2023-10-04 04:53
@jrieken https://github.com/microsoft/vscode/pull/194774 makes that happen. I wonder if `UriComponents` could become a smaller object on macOS and Linux where `path` is always (?) the same as `fsPath`:

<img width="517" alt="image" src="https://github.com/microsoft/vscode/assets/900690/a8623f1f-fd68-4a72-aa45-15c79745a16b">

Maybe when `toJSON`, we could check if `path === fsPath` and then drop the `fsPath` property?

**Comment by bpasero** [comment] 2023-10-05 06:56
@lifengl given we fixed this perf issue in insiders, can you try again with insiders and see how performance is for you now?

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jrieken** [comment] 2023-10-05 15:52
> Maybe when toJSON, we could check if path === fsPath and then drop the fsPath property?

I kinda like but dropping would trigger a recompute on the receiving side... It would need some other mechanism

**Comment by bpasero** [comment] 2023-10-11 11:12
Closing until we hear otherwise.

**Closed** 2023-10-11 11:12 UTC
Labels: info-needed, freeze-slow-crash-leak, extension-host, file-watcher
