### ISSUE TITLE
Login feature

### ISSUE THREAD

**Issue by vxba** [Microsoft/vscode#56734] opened 2018-08-18 09:42 UTC
I think vscode need to have a Login feature for sync.

**Comment by nealot** [comment] 2018-08-18 15:10
The issue to follow for this request is https://github.com/Microsoft/vscode/issues/2743.

**Comment by beastdestroyer** [comment] 2018-08-18 16:56
@nealot I'm seeing you everywhere now aren't I? :) I definitely want a login feature soon, though for me it isn't necessary, would be cool everytime I do a hard reset of VSCode (Reset config files, extension settings etc.) I found doing it every so often helps my RAM usage (since it can skyrocket to like 800MB or more with many editors)

**Comment by nealot** [comment] 2018-08-18 18:01
@beastdestroyer Yeah, I really like this editor :D

**Comment by beastdestroyer** [comment] 2018-08-18 18:44
@nealot I started out with N++ when I started web development. My older bro (games designer/developer) started using Sublime Text 3, and so did I. Soon after (like not even a month after I started ST3) I found VSCode and tried it out. Left the others in the dust forever. The End, let VSCode be the Ruler.

**Comment by sandy081** [comment] 2018-08-20 07:14
Duplicate of #2743

**Closed** 2018-08-20 07:14 UTC
Labels: *duplicate
