### ISSUE TITLE
vim in terminal  can not display first line

### ISSUE THREAD

**Issue by foxundermoon** [Microsoft/vscode#7695] opened 2016-06-15 06:47 UTC
- VSCode Version:1.2.1
- OS Version: osx 10.11.4

when i open vim in terminal, it can not display first line.
and some char can not display well.

![vscode_bug](https://cloud.githubusercontent.com/assets/2764106/16070422/d189bf7c-3307-11e6-9eef-69aff98c7a8c.png)

this is web storm style
![webstorm](https://cloud.githubusercontent.com/assets/2764106/16070443/015b8b22-3308-11e6-88c2-9245954fb0ec.png)

**Comment by Tyriar** [comment] 2016-06-15 08:42
@foxundermoon first line displays fine for me, any tips on reproducing?

![image](https://cloud.githubusercontent.com/assets/2193314/16073349/586156e0-329a-11e6-9674-0e572012fa5b.png)

This is the file:

![image](https://cloud.githubusercontent.com/assets/2193314/16073366/67838724-329a-11e6-942a-1924598c4ad3.png)

**Comment by foxundermoon** [comment] 2016-06-15 11:04
@Tyriar 
you try once spf13-vim.
normal vim without any config also fine for me.

it seems  some unicode char display error  lead to missing first line.

**Comment by Tyriar** [comment] 2016-06-15 17:57
@foxundermoon if the unitcode char in question is a full width character then the root cause is an upstream issue. We have changed libraries used but it will still probably happen in insiders. https://github.com/sourcelair/xterm.js/issues/62 will probably fix this.

**Comment by Tyriar** [comment] 2017-04-20 18:26
Closing off as a lot has changed since. If you can still repro this please file the issue against https://github.com/sourcelair/xterm.js

**Closed by Tyriar** 2017-04-20 18:26 UTC
Labels: bug, help wanted, integrated-terminal, upstream
