### ISSUE TITLE
Non-monospace font + visible whitespace + After decorator causes line to "jump"

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#32436] opened 2017-08-14 01:38 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.16257
---

Steps to Reproduce:

1. Use a non-monospace editor font and visible whitespace
2. Use GitLens or VersionLens (or anything that adds an `after` decorator to a line)
3. 🐛 Observe that the line "jumps" when the decorator is applied

![gitlens_linepop](https://user-images.githubusercontent.com/11204251/29243258-18fd6ce6-7f60-11e7-86c8-50d9d8fd083d.gif)

Related issue: https://github.com/eamodio/vscode-gitlens/issues/129

@alexandrudima I'm guessing it has something to do with the fix for https://github.com/Microsoft/vscode/issues/11485 (🤞 that the fix can stay in place)

Reproduces without extensions: No

**Comment by alexandrudima** [comment] 2017-08-14 10:29
Yes, it is a direct result of c6f8a5d80f44008bfa8b0faa4a1a62c376f2bcfd

In this case, the chosen font has different widths for `&rarr;` (&rarr;), `&middot;` (&middot;) and `&nbsp;` (&nbsp;)

A leading tab when whitespace is rendered are e.g. as `&rarr;&nbsp;&nbsp;&nbsp;` (&rarr;&nbsp;&nbsp;&nbsp;).
Four leading spaces when whitespace is rendered are e.g. as `&middot;&middot;&middot;&middot;` (&middot;&middot;&middot;&middot;)
Four regular spaces are e.g. as `&nbsp;&nbsp;&nbsp;&nbsp;` (&nbsp;&nbsp;&nbsp;&nbsp;)

If their widths do not match (which is the case here), we artificially make their widths equal (which is desirable). For #11485, we don't emit artificial widths if a line contains foreign elements. This is the result of that change.

**Comment by eamodio** [comment] 2017-08-14 14:10
@alexandrudima is there any way to only do the width normalization if a `before` decorator is used? Since and `after` doesn't really get/need any benefit from the normalization like the `before` does.

**Comment by eamodio** [comment] 2017-08-15 00:23
@alexandrudima if I turned `containsForeignElements` into an enum or something (none, before, after, both) and plumbed that through so that only `before` decorations would trigger the new behavior is that something that you think would work (and would be acceptable as a PR)?

**Comment by eamodio** [comment] 2017-08-25 02:42
@alexandrudima any thoughts on the proposed "solution" above?

**Comment by alexandrudima** [comment] 2017-08-25 15:09
@eamodio 

I'm not sure why the width affects only `before` decorations and not `after` decorations, so your proposed solution would probably solve this particular issue, but most likely will not fix #32865 , which we've closed as a duplicate of this one. (AFAIK the color boxes use `before` decorations).

**Comment by eamodio** [comment] 2017-08-25 15:22
Ah, sorry -- didn't dig into those other issues. Hrm.

**Comment by alexandrudima** [comment] 2017-09-21 16:12
There are many duplicates coming in, I need to investigate if there's something we can do for Sept.

**Comment by eamodio** [comment] 2017-09-21 16:34
@alexandrudima let me know if I can help in any way

**Closed** 2017-09-27 08:00 UTC
Labels: bug, editor, editor-core
