### ISSUE TITLE
Activity bar icon contributed by an extension is not rendered

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#67101] opened 2019-01-25 08:19 UTC
- install the Browser View extension https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview
- sometimes when you restart the icon is not rendered, see below

![image](https://user-images.githubusercontent.com/172399/51733631-321b5480-2082-11e9-9be3-8d96046e5746.png)

A reload of the window fixes the problem.

**Comment by sandy081** [comment] 2019-01-25 12:18
@egamma I am not able to reproduce it. Is it on stable or insiders? Also were there any extension updates before this happened? When you see this again, can to open developer tools and inspect the element to check the icon url?

**Comment by sandy081** [comment] 2019-02-05 11:03
Closing this as I cannot reproduce this. When it is seen again please provide the icon url from developer tools.

**Closed by sandy081** 2019-02-05 11:03 UTC
Labels: explorer-custom, needs more info
