### ISSUE TITLE
TypeScript DX, Make Type Inside Tooltip Clickable

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#206354] opened 2024-02-27 16:07 UTC
Hi. I want to click on this goddamn `H` type, and vscode to take me to the definition of that type so I can know what the hell it is, so I can fix this goddamn thing. How the hell should I know what the hell `H` is? I don't want to go into the source code and try to find it. Just let me click on the thing and take me there.

![image](https://github.com/microsoft/vscode/assets/44144724/58717a02-fd9a-45eb-9a0e-da95348ff3fd)

**Comment by mjbvz** [comment] 2024-03-13 22:14
Duplicate of https://github.com/microsoft/vscode/issues/195394

**Closed by mjbvz** 2024-03-13 22:14 UTC
