### ISSUE TITLE
jsx attribute suggestion not working

### ISSUE THREAD

**Issue by leonbec** [Microsoft/vscode#44085] opened 2018-02-21 05:07 UTC
- VSCode Version: 1.20.1
- OS Version: windows10

jsx attribute suggestion not working

Steps to Reproduce:
![jsx attr](https://user-images.githubusercontent.com/28700378/36463960-f6f29d32-1731-11e8-9ed9-b3036af775fd.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-02-21 19:56
Duplicate of #40941

**Closed by mjbvz** 2018-02-21 19:56 UTC
