### ISSUE TITLE
bug wordpress sintax

### ISSUE THREAD

**Issue by breitembach** [Microsoft/vscode#34150] opened 2017-09-11 14:46 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
html-class-suggestions|And|1.0.7
ACF-Snippet|ant|1.8.1
vscode-intelephense-client|bme|0.7.2
php-autocomplete|bsc|0.4.2
vscode-html-css|ecm|0.1.8
vscode-great-icons|emm|2.1.15
php-intellisense|fel|1.5.1
auto-close-tag|for|0.5.0
beautify|Hoo|1.1.1
autofilename|Jer|0.1.3
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.2.1
seti-icons|qin|0.1.3
view-in-browser|qin|0.0.5
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
vscode-fileutils|sle|2.6.2
wordpress-snippet|tun|1.1.2
twig|wha|1.0.2
html-css-class-completion|Zig|1.10.0

(2 theme extensions excluded)

---

Steps to Reproduce:

After the wordpress loop the colors is weird but it is not giving problem

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment] 2017-09-12 07:39
@breitembach Can you please add more precise steps and a more precise description? I am not sure what the issue is here

**Comment by breitembach** [comment] 2017-09-12 17:00
@alexandrudima 
this problem is happening after wordpress loop it gets a color as if the code was wrong.

look the image.
https://imgur.com/a/M1nrj

**Comment by aeschli** [comment] 2017-09-13 14:11
@breitembach Please attach the full code sample. What language is that? PHP?

**Comment by breitembach** [comment] 2017-09-14 19:12
put this in your vscode
I'm using php
@aeschli 

  
   <div class="col-md-12 col-sm-7">
      <div class="row">
         <h5 class="bold">
            <?php
               $categories = get_the_category();
               if ( ! empty( $categories ) ) {
                  echo esc_html( $categories[2]->name );   
               }
            ?>
         </h5>
         <?php 
         $args = array(
            'post_type' => 'post',
            'order' => 'ASC',
            'category_name' => 'mostar-pode-gostar',
            'posts_per_page' => -1
         );
         $my_query = new WP_Query( $args );
         if ( $my_query->have_posts() ) {
            while ( $my_query->have_posts() ){
            $my_query->the_post();?>
            <div class="row">
               <div class="col-md-5 col-sm-5 col-xs-4 mgt-20">
               <?php
                  $thumbnail_img = get_field("blog_img");
                  $size = "blog_img_like";
                  $image = wp_get_attachment_image_src( $thumbnail_img, $size);
                  // url = $image[0];
                  // width = $image[1];
                  // height = $image[2];
                  ?>
                  <a href="<?php the_permalink();?>">
                     <img src="<?php echo $image[0]; ?>" alt="<?php the_field("blog_title");?>" class="img-responsive thumbnail-blog-img-like">
                  </a>
               </div>
               
               <div class="col-md-7 col-sm-7 col-xs-8 mgt-20">
                  <div class="row">    
                     <a href="<?php the_permalink();?>">
                        <header class="thumbnail-blog-title-like"><?php the_field("blog_title");?></header>
                     </a>
                  </div> 
               </div>
            </div>
            <?php }
               }
            ?>
      </div>
      
   </div>
</div>

**Comment by roblourens** [comment] 2017-09-18 16:06
This should be fixed in 1.16.1. Download that update and try again, it looks correct for me. If not, it's likely an issue with your theme.

**Closed by roblourens** 2017-09-18 16:06 UTC
Labels: needs more info, new release

**Comment by breitembach** [comment] 2017-09-18 16:32
Got corrected Thanks.
