### ISSUE TITLE
Deleting "folded-in" directory with right-click/delete asks to delete parent folder instead

### ISSUE THREAD

**Issue by horsten** [microsoft/vscode#88988] opened 2020-01-20 17:57 UTC
Issue Type: <b>Bug</b>

This is on a remote SSH folder. Not sure if that matters.

I created a folder "layouts" and under that another "Auth", then I decided to delete "Auth" and put an Auth.tsx directly in "layouts" instead. When I right click "Auth" and choose Delete, it shows a confirmation if I want to delete "layouts" permanently rather than the subdirectory "Auth".

Screenshots:

![vscodebug1](https://user-images.githubusercontent.com/3442409/72748065-964df700-3bb6-11ea-91dc-7e5afddc5447.png)
![vscodebug2](https://user-images.githubusercontent.com/3442409/72748077-99e17e00-3bb6-11ea-9226-f1293b92dcbe.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.15.0-74-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3202)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (19.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: REDACTED.REDACTED.dk|
|OS|Linux x64 4.15.0-74-generic|
|CPUs|QEMU Virtual CPU version 2.5+ (4 x 2294)|
|Memory (System)|5.41GB (1.71GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-react-typescript|inf|1.3.1
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.7
vscode-remote-extensionpack|ms-|0.19.0
debugger-for-chrome|msj|4.12.5
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
jshint|dba|0.10.21
vscode-eslint|dba|2.0.14
vscode-npm-script|eg2|0.3.10
quick-notes|Lia|1.3.2
vscode-cosmosdb|ms-|0.12.0
azure-account|ms-|0.8.8
pdf|tom|0.5.1

</details>

**Comment by IllusionMH** [comment] 2020-01-21 10:44
Cannot reproduce this on Insiders builds on both Windows and Remote - WSL workspaces.
VS Code version: Code - Insiders 1.42.0-insider (d72b2d372f5024a9193b37a3830bbbc459c0ef1b, 2020-01-20T05:33:26.563Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

Could you try to reproduce it on regular Windows workspace?
Is it reproducible in Insiders build https://code.visualstudio.com/insiders/? 
This will help to narrow issue to VS Code, extension or if it was resolved in latest builds.

**Comment by horsten** [comment] 2020-01-21 21:48
I cannot reproduce this myself now, either on local or remote. However I'm positive it happened as described above, and was reproducible consistently during that session. This must depend on some other state, I tried making a file in the deeper directory first and deleting it and a few other things like that which I might have done originally, but no luck triggering it again.

**Comment by joaomoreno** [comment] 2020-01-23 10:10
I also can't seem to repro, unfortunately, though I do believe you! Closing this for now but keeping my eyes open. Let me know if you see this again and are able to repro. Thanks!

**Comment by horsten** [comment] 2020-01-23 12:26
> I also can't seem to repro, unfortunately, though I do believe you! Closing this for now but keeping my eyes open. Let me know if you see this again and are able to repro. Thanks!

Thanks, will do.

**Comment by horsten** [comment] 2020-02-08 22:38
It happened again and this time I was able to repro and capture a video of it. This time the sequence was:

1) Move another file into the parent of the collapsed subfolder
2) Move the only file out of the collapsed subfolder
3) Right click the collapsed subfolder and click Delete

Selecting something else in the tree clears out the problem. That's probably why I couldn't repro last time.

Video here: https://youtu.be/_6171PDhzOI

**Comment by joaomoreno** [comment] 2020-02-10 08:55
@isidorn The problem here is the tree selection, check out the video.

**Comment by isidorn** [comment] 2020-02-11 11:40
Got it. You got mulitple selection in the explorer. With compresed items and multiple selection somehow the context is wrongly computed. Hard to repro, and every time I change the get context code something else breakts -> thus assigning to backlog. And can look into this if more users hit this.

**Comment by isidorn** [comment] 2020-04-07 09:45
I believe we might have fixed this issue. Can anyone reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Closed** 2020-04-14 11:23 UTC
Labels: file-explorer, needs more info
