### ISSUE TITLE
Pop Overs prevent from selecting Code

### ISSUE THREAD

**Issue by KeturahDev** [microsoft/vscode#114548] opened 2021-01-18 22:00 UTC
### Issue: 
The pop ups that appear when hovering the mouse over variables/code appears too quickly, and covers the code that I was about to click on, preventing me from selecting to write or edit.

### Step to reproduce: 
- enable pop-ups
- position variable to click on towards middle of screen
- hover over it with mouse. Pop up should cover variable
- attempt clicking - you will not be able to select the variable

If this box could be moved upwards, or take longer to appear, that would be helpful.

### ScreenShot example: 

I go to hover over goalLookup on line 43

<img width="763" alt="Screen Shot 2021-01-18 at 1 57 03 PM" src="https://user-images.githubusercontent.com/32975967/104966223-32126e80-5995-11eb-880a-ebfa47fb23ce.png">

goalLookup is covered by the pop up, and I cannot click on goalLookup

<img width="888" alt="Screen Shot 2021-01-18 at 1 56 41 PM" src="https://user-images.githubusercontent.com/32975967/104966211-2de65100-5995-11eb-8ad6-321b36df0ebe.png">

**Comment by gjsjohnmurray** [comment] 2021-01-19 05:57
See https://github.com/microsoft/vscode/issues/112736#issuecomment-747923034 for a setting controlling the delay.

**Comment by alexdima** [comment] 2021-01-20 13:24
The hover is positioned a bit too low, appearing on top of the text that is being hovered. Duplicate of https://github.com/microsoft/vscode/issues/112391 . A fix is available on Insiders.

**Closed by alexdima** 2021-01-20 13:24 UTC
