### ISSUE TITLE
vscode API - Copy Paste

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#182472] opened 2023-05-15 06:13 UTC
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=214546&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=d61c32fd-93f0-5126-b44d-dcf4920dede7&l=853

```
4 failing
  1) vscode API - Copy Paste
       Copy with empty selection should copy entire line:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/documentPaste.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  2) vscode API - Copy Paste
       Copy with multiple selections should get all selections:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/documentPaste.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  3) vscode API - Copy Paste
       Earlier invoked copy providers should win when writing values:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/documentPaste.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  4) vscode API - Copy Paste
       Copy providers should not be able to effect the data transfer of another:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/documentPaste.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

```

**Comment by mjbvz** [comment] 2023-05-15 18:30
Duplicate of #182489. Pushed potential fix but will keep an eye out for future failures

**Closed by mjbvz** 2023-05-15 18:30 UTC
Labels: integration-test-failure
