### ISSUE TITLE
Inline Links only work for vscode.d.ts file

### ISSUE THREAD

**Issue by ReiMcCl** [Microsoft/vscode#60156] opened 2018-10-08 16:15 UTC
- VSCode Version: 1.28.0-insider
- OS Version: 

Steps to Reproduce:

1. Create the below file as `vscode.d.ts` and view the functioning comment links.
2. Rename the file to `types.d.ts`, comment links will be removed.

```
export interface Node {
    /**
     * [attribute](#Attribute)
     */
    a: Attribute;
}

export interface Attribute {

}
```

Does this issue occur when all extensions are disabled?: Yes

Working Example: 
![image](https://user-images.githubusercontent.com/12534799/46620808-aeaf1500-cb1d-11e8-9f63-eb18b80690b7.png)

Broken Example:
![image](https://user-images.githubusercontent.com/12534799/46620819-b40c5f80-cb1d-11e8-8e0d-9ca8e1dd7627.png)

**Comment by mjbvz** [comment] 2018-10-11 01:44
Duplicate of #8223

**Closed by mjbvz** 2018-10-11 01:44 UTC
Labels: insiders
