### ISSUE TITLE
Changing the Color Theme breaks Terminal

### ISSUE THREAD

**Issue by martinring** [Microsoft/vscode#7251] opened 2016-06-06 13:16 UTC
- VSCode Version: Version 1.2.0-insider Commit 7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f
- OS Version: Fedora 23

Steps to Reproduce:

1. Open Terminal
2. Change Color Theme

Terminal is then broken until VSCode is restarted

![anim](https://cloud.githubusercontent.com/assets/763861/15823098/7f599b88-2bf9-11e6-83e2-f4bab18fe0de.gif)

**Comment by Tyriar** [comment] 2016-06-06 19:02
I can't reproduce this, at least on latest alpha. Can you try to hit up/down and scroll the mouse wheel to see if you can see the terminal come back? The only theme related issue I'm aware of so far is https://github.com/Microsoft/vscode/issues/6437

**Comment by martinring** [comment] 2016-06-06 19:59
No, I tried that already. Same situation on MacOS.

**Comment by bgse** [comment] 2016-06-07 00:49
I've seen same breakage with the terminal on Win8.1, couldn't find a way to repro at the time though.

@martinring Do you happen to have a bunch of errors on the developer console when terminal breaks by chance?

I'll try to repro with your method on that machine, going to check on my F23 machine as well and report back here.

**Comment by martinring** [comment] 2016-06-07 07:15
@Tyriar @bgse Somehow, I can't reproduce it anymore today. Now it is just not possible to change the color theme, when terminal is in focus as in #6437. Nothing changed since yesterday. Just one reboot. Some astonishing nondeterminim going on here. :D

**Comment by Tyriar** [comment] 2016-06-07 07:17
@martinring there are a few quirky bugs I'm chasing that don't make a lot of sense (#6738), I guess this is one of them :stuck_out_tongue:

**Comment by bgse** [comment] 2016-06-07 07:50
@Tyriar @martinring Same here, no repro on Win8.1, Win10 and F23.

I'd assume there is more to it than just changing the color theme, or could be completely unrelated breakage.

**Comment by forrestab** [comment] 2016-06-29 13:43
I am having the same issue, though it does not occur for me unless I have something like browser-sync running in the terminal and I switch themes. In the Developer Tools, I see the following error: 

![image](https://cloud.githubusercontent.com/assets/2192911/16454076/31e36e88-3ddd-11e6-9745-51afba71436b.png)

```
Cannot set property 'innerHTML' of undefined: TypeError: Cannot set property 'innerHTML' of undefined
    at Terminal.refresh (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\term.js\src\term.js:1704:32)
    at b.setTerminalTheme (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:4:4779)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:4:4368
    at e.invoke (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:21140)
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:22593)
    at o (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:12820)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:99:7930
    at Object.h [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:23:16006)
    at Object.__dirname.undefined.P.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:23:19168)
    at __dirname.undefined.t.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:23:20994)
```

VSCode Version: 1.2.1
OS Version: Windows 7

**Comment by Tyriar** [comment] 2016-06-29 18:48
This should be fixed in the Insiders build, please comment if you have issues on v1.3.0-insiders/v1.3.0+

**Closed by Tyriar** 2016-06-29 18:48 UTC
Labels: bug, integrated-terminal, needs more info
