### ISSUE TITLE
Could not install typings files for JavaScript language features.

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#25779] opened 2017-05-02 14:22 UTC
- VSCode Version: Code - Insiders 1.12.0-insider (aa05dac84b7526550653a861c17b402349cb3bc6, 2017-05-02T00:04:13.700Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.6.2|
|sort-lines|Tyriar|1.2.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.15.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.1.2|
|tslint|eg2|0.12.0|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.3.0|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|project-snippets|rebornix|0.5.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.15.0|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Open a JS file
2. Dialog appears: "Could not install typings files for JavaScript language features. Please ensure that NPM is installed and is in your PATH"

I do have NPM installed, but we install node with NVM (Node Version Manager), which has confused some other plugins (mostly in Sublime Text) that expect a conventional install of Node.

My bash_profile:
````
# source ~/.profile
export LC_CTYPE=en_US.UTF-8
#PS1="\u$ "
export PATH="/usr/local/bin:node_modules/.bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"
# export NODE_PATH=/usr/local/lib/node_modules

export CLICOLOR=1
# export LSCOLORS=GxFxCxDxBxegedabagaced

alias ll='ls -lahG'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

[[ -s ~/.bashrc ]] && source ~/.bashrc


##
# Your previous /Users/stevelombardi/.bash_profile file was backed up as /Users/stevelombardi/.bash_profile.macports-saved_2017-02-13_at_14:15:46
##

# MacPorts Installer addition on 2017-02-13_at_14:15:46: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.
````

**Comment by mjbvz** [comment] 2017-05-03 20:49
This looks like a duplicate of #24961

I've opened https://github.com/Microsoft/TypeScript/issues/15287 on TypeScript to track this upstream. Ideally all the details of how ATA is implemented should be hidden

One possible fix you can try is to move the nvm part to a `.bashrc` file instead of `.bash_profile`: https://github.com/Microsoft/vscode/issues/24961#issuecomment-297774505

**Closed by mjbvz** 2017-05-03 20:49 UTC
Labels: duplicate, javascript
