### ISSUE TITLE
Promise with no error callback

### ISSUE THREAD

**Issue by dolmen** [Microsoft/vscode#25509] opened 2017-04-27 05:43 UTC
- VSCode Version: 1.11.2
- OS Version: Ubuntu 16.04

I got this warning on the console from which I launched VSCode. My computer is a laptop that I frequently put in hibernation and that has issues with restoring wifi on wake up (I frequently have to unload the driver iwlmvm, iwlwifi).

```
WARNING: Promise with no error callback:6
{ exception: 
   Error: net::ERR_INTERNET_DISCONNECTED
       at Error (native),
  error: null,
  promise: 
   { _creator: null,
     _nextState: null,
     _state: 
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: 
      Error: net::ERR_INTERNET_DISCONNECTED
          at Error (native),
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_INTERNET_DISCONNECTED
    at Error (native)
[uncaught exception in main]: Error: net::ERR_INTERNET_DISCONNECTED

Error: net::ERR_INTERNET_DISCONNECTED
    at Error (native)
Error: net::ERR_INTERNET_DISCONNECTED

Error: net::ERR_INTERNET_DISCONNECTED
    at Error (native)
    at Timeout._onTimeout (**REDACTED**/resources/app/out/vs/code/electron-main/main.js:4:15297)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by bpasero** [comment] 2017-04-27 07:45
Could this be the update check we do since it seems to happen from the main process?

**Comment by joaomoreno** [comment] 2017-04-27 08:15
@bpasero `resources/app/out/vs/code/electron-main/main.js:4:15297` points to the `unexpectedErrorHandler`. There are no references to `onUnexpectedError` in `**/electron-main/**` so this could really be coming from anywhere which accesses the internet. After a review of the update code, all promises seem to have error callbacks there.

@dolmen Can you somehow find a reproducible case that we can repeat?

**Comment by dolmen** [comment] 2017-04-30 20:46
> @dolmen Can you somehow find a reproducible case that we can repeat?

No, I can't.

I've reported the issue mainly in hope that diagnostic tools will be improved so that the next time I encounter the issue I can report more info. For example, the date/time of the event is not reported. But this warning is shown in a terminal hidden behind my VSCode window, so I do not see it immediately and I can't correlate the warning to something I have done.

**Comment by joaomoreno** [comment] 2017-05-02 09:12
Got it, will close it for now since nothing breaks. Will keep an eye open for it.

**Closed by joaomoreno** 2017-05-02 09:12 UTC
Labels: needs more info
