### ISSUE TITLE
Disabled line numbers reappear after toggling Zen mode

### ISSUE THREAD

**Issue by joonoro** [microsoft/vscode#78545] opened 2019-08-06 09:06 UTC
- VSCode Version: 1.36.1
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Add the following to user config to disable line numbers in markdown files

```
"[markdown]": {
    "editor.lineNumbers": "off"
},
```

2. Open a markdown file, note that line numbers are disabled as expected
3. Activate Zen mode
4. Deactivate Zen mode
5. Line numbers reappear despite being disabled for markdown files in config

Note that this only happens if you disable line numbers for a specific mode. If line numbers are disabled globally everything works as expected and they never reappear.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2019-08-07 08:59
Thanks for reporting this. The next vscode insiders will have the fix so you can try it out there.

**Comment by crystalfp** [comment] 2019-08-18 17:22
The problem persists in 1.37.1

**Comment by isidorn** [comment] 2019-08-19 15:14
@crystalfp this will only be fixed in the next release, not in 1.37.1
But in 1.38.
It is available currently in vscode insiders so you can use that in the meantime. Thanks

**Comment by isidorn** [comment] 2019-08-28 12:15
@mjbvz  I can not reproduce this with a fresh user data dir on latest insiders.
Please let me know what you are doing differently than me and I will reopen.

![wrap](https://user-images.githubusercontent.com/1926584/63854746-21c3b300-c99e-11e9-8cd7-6d3d6515f915.gif)

**Comment by jrieken** [comment] 2019-08-29 09:43
Yeah, reproduces with @mjbvz's steps. @isidorn You aren't following the steps from the OP, e.g the setting must be specific to markdown

**Comment by isidorn** [comment] 2019-08-29 09:47
@jrieken @mattbierner thanks for catching this. Pushing to next milestone.
@sandy081 how can I get the true value of the configuration setting. Currently I am using

`this.configurationService.getValue('editor.lineNumbers', { resource: model.uri });`

I thought this code snippet will also take care of workspace setting and respect markdown.

**Comment by crystalfp** [comment] 2019-08-29 09:48
The workspace setting seems irrelevant. I have the setting specific to markdown (this is critical) at the user level and the problem is there.

**Comment by isidorn** [comment] 2019-08-29 09:52
@crystalfp please read my comment from above https://github.com/microsoft/vscode/issues/78545#issuecomment-522622112
We are all using vscode insiders

**Comment by crystalfp** [comment] 2019-08-29 09:59
Sorry. I tried to be helpful...

**Comment by isidorn** [comment] 2019-08-29 10:01
No problemo.

**Comment by jeanp413** [comment] 2019-09-02 03:06
> how can I get the true value of the configuration setting. Currently I am using
> 
> `this.configurationService.getValue('editor.lineNumbers', { resource: model.uri });`
> 
> I thought this code snippet will also take care of workspace setting and respect markdown.

The `overrideIdentifier` property is also needed

`this.configurationService.getValue('editor.lineNumbers', { overrideIdentifier: model.getModeId(), resource: model.uri });`

**Comment by sandy081** [comment] 2019-09-02 11:29
@jeanp413 Thanks for pitching in. You are correct `overrideIdentifier` is needed to get language overridden settings.

Instead you can use the following service which takes care of `overrideIdentifier` and `resource` for you.

https://github.com/microsoft/vscode/blob/cd46e5b/src/vs/editor/common/services/resourceConfiguration.ts#L32

**Comment by isidorn** [comment] 2019-09-02 17:49
@jeanp413 @sandy081 thanks. I decided to go with the `overrideIdentifier` since I did not want to introduce a new dependency on that layer.

**Closed** 2019-09-02 17:48 UTC
Labels: bug, verification-found, workbench-zen
