### ISSUE TITLE
Jupyter notebook esta travando e as celulas nao são exibidas

### ISSUE THREAD

**Issue by JackVartanian** [microsoft/vscode#173471] opened 2023-02-05 10:26 UTC
Type: <b>Bug</b>

Jupyter notebook esta travando e as celulas nao são exibidas

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (6.54GB free)|
|Process Argv|--crash-reporter-id bc7708f1-7a80-488e-86a0-584285a69a75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-sql-beautify|cla|0.3.16
el-vsc-product-icon-theme|ElA|0.1.8
copilot|Git|1.71.8269
vscode-pull-request-github|Git|0.59.2023020215
vscode-language-pack-pt-BR|MS-|1.75.2023020109
mssql|ms-|1.17.1
sql-bindings-vscode|ms-|0.3.0
python|ms-|2023.2.0
jupyter|ms-|2023.1.2000312134
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
material-icon-theme|PKi|4.23.1
material-product-icons|PKi|1.4.1
vscode-icons|vsc|12.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by TheProjectsGuy** [comment] 2023-02-05 15:05
I think a part of this issue relates to

https://github.com/microsoft/vscode/issues/173300

**Comment by rebornix** [comment] 2023-02-06 17:25
/duplicate of https://github.com/microsoft/vscode/issues/173590

**Closed by rebornix** 2023-02-06 17:25 UTC
