### ISSUE TITLE
Electron causes high CPU on KDE

### ISSUE THREAD

**Issue by gtzinos** [Microsoft/vscode#30485] opened 2017-07-12 09:04 UTC
Hi,
I downloaded the new stable vs-code version and now i am facing more issues.

1) I don't find my extensions
2) Crash again and again during development
3) My memory and cpu use increased

Please check before push to production.

OS: Windows 10
vs-code: 1.14.0
Shell: 1.6.6

**Comment by macOneOone** [comment] 2017-07-12 09:21
Try those steps:

1. Rollback to previous version.
2. Open and press Update Now.
It should fix because this is OS issue and not VSC it self.

I did and it worked. Hope it has the same effect to you.

**Comment by chrmarti** [comment] 2017-07-12 15:49
@gtzinos Does it freeze immediately after startup? Could you check which process and with what arguments is using much CPU? Does it reproduce when launching with `code --disable-extensions`?

**Comment by dcasella** [comment] 2017-07-12 21:50
@chrmarti  
I'm having the same problems: freeze on startup (can't do anything except clicking on the pop-up "The window is no longer responding"), and 100+% CPU usage (except it's not true).

Starting VSCode with `--disable-extensions` fixes the issue.

`code --list-extensions` output:
```
AlanWalk.markdown-toc
Gimly81.matlab
HookyQR.beautify
Shan.code-settings-sync
Tobiah.comment-snippets
Tyriar.terminal-tabs
Zignd.html-css-class-completion
alefragnani.project-manager
atefth.ruby-on-rails-snippets
bbenoist.QML
bentx.vscode-custom-theme
christian-kohler.path-intellisense
codezombiech.gitignore
dcasella.monokai-plusplus
donjayamanne.python
formulahendry.auto-rename-tag
hoovercj.ruby-linter
itryapitsin.Scala
justusadam.language-haskell
lukehoban.Go
mathiasfrohlich.latexcompile
mattn.Lisp
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.latex
ms-vscode.sublime-keybindings
qinjia.seti-icons
rebornix.prolog
rebornix.Ruby
redhat.java
richie5um2.vscode-sort-json
tomoki1207.pdf
twxs.cmake
yzane.markdown-pdf
```

`htop` processes:
![htop](http://i.imgur.com/zomFXlP.png)

**Comment by dcasella** [comment] 2017-07-12 22:00
DIsabling the extension `atefth.ruby-on-rails-snippets` fixed the issue. [This](https://github.com/Microsoft/vscode/issues/30546) helped, thanks.

**Comment by chrmarti** [comment] 2017-07-12 22:18
@dcasella Does https://github.com/Microsoft/vscode/issues/30449#issuecomment-314666925 help?

**Comment by dcasella** [comment] 2017-07-12 23:04
Downgrading the Typescript version to 2.3.4 doesn't reduce the CPU usage.

However I don't see how the VSCode process is using more than 110% CPU, since I experience no lag at all.

**Comment by chrmarti** [comment] 2017-07-13 03:46
@dcasella What are the command arguments of the process at 110% CPU? This could be #30486 with one of your extensions. That will be fixed in the upcoming 1.14.1.

**Comment by dcasella** [comment] 2017-07-13 10:03
@chrmarti Arguments are just `--unity-launch` after removing the rails snippets extension.

I still experience the 110% CPU usage after disabling all the extensions (`Command Palette > Extensions: Disable All Installed Extensions` > Restart VSCode).  
So I performed a clean install of the Insiders build (I use Stable) and with default settings and no extensions it still shows the process at 110% CPU (with the same arguments as Stable, `--unity-launch`).

If this helps in any way: I'm running KDE (KDE Neon), and only when I open VSCode the process `kded5 [kdeinit5]` goes up to 20% CPU usage from 0%.

**Comment by chrmarti** [comment] 2017-07-13 14:11
@dcasella When you do a `ps ax`, what are the command arguments of the process that consumes so much CPU? VSCode uses multiple processes, the command arguments will tell us which one it is.

**Comment by dcasella** [comment] 2017-07-13 21:15
@chrmarti This is the output for `ps ax --sort=-pcpu | grep /code`:

```
 1972 ?        Rl     8:10 /usr/share/code/code --unity-launch
 2237 ?        Sl     0:03 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=77DEA359DDA3945C2F29B87E092F22C5 --lang=en-US --node-integration=true --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --service-request-channel-token=77DEA359DDA3945C2F29B87E092F22C5 --renderer-client-id=3 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
 2242 ?        Sl     0:01 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=AAF44BD1DDFBDC360CA18BF9276A14D6 --lang=en-US --node-integration=true --hidden-page --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --service-request-channel-token=AAF44BD1DDFBDC360CA18BF9276A14D6 --renderer-client-id=5 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
 2354 ?        Sl     0:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=extensionHost
 2355 ?        Sl     0:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=watcherService
 2033 ?        S      0:00 /usr/share/code/code --type=zygote --no-sandbox
```

The PID of the first process (1972) corresponds with the one that uses the most CPU.

**Comment by chrmarti** [comment] 2017-07-13 22:42
@dcasella What's the %CPU of that process?

**Comment by dcasella** [comment] 2017-07-14 11:15
@chrmarti After updating to 1.14.1, I left VSCode open for a while to see if anything changed.  
Disabling extensions nor downgrading Typescript to 2.3.4 changed the %CPU by max (everytime over 100%).

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
user     11152  114  1.0 1431124 127028 ?      Rl   12:46  15:26 /usr/share/code/code --unity-launch
user     11210  0.2  1.5 1317836 188720 ?      Sl   12:46   0:02 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=854D9FB77CF1998220CA375F454BF2C2 --lang=en-US --node-integration=true --background-color=#1c1c1c --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --service-request-channel-token=854D9FB77CF1998220CA375F454BF2C2 --renderer-client-id=3 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
user     11298  0.1  0.6 1000300 74036 ?       Sl   12:46   0:01 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=extensionHost
user     11155  0.0  0.2 325548 28012 ?        S    12:46   0:00 /usr/share/code/code --type=zygote --no-sandbox
user     11216  0.0  0.7 1049200 89112 ?       Sl   12:46   0:00 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=A12295F8C88B7469DF6A1F060094C403 --lang=en-US --node-integration=true --hidden-page --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --service-request-channel-token=A12295F8C88B7469DF6A1F060094C403 --renderer-client-id=5 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
user     11299  0.0  0.4 910740 51512 ?        Sl   12:46   0:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=watcherService
user     11355  0.0  0.4 920472 56820 ?        Sl   12:47   0:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=searchService

```

I can't figure out if the problem is on my end or not, because VSCode isn't slowing down the PC or crashing or anything.

**Comment by chrmarti** [comment] 2017-07-14 14:14
That's the launch process, not sure why that would use much CPU. @jrieken ?

**Comment by jrieken** [comment] 2017-07-14 14:43
@dcasella Please start vscode like so: `code --prof-start`. It will take a CPU profile on startup and stores on you disk. Please share them here, thanks

**Comment by dcasella** [comment] 2017-07-14 18:10
- VSCode Version: <code>Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)</code>
- OS Version: <code>Linux x64 4.4.0-83-generic</code>
- CPUs: <code>Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4208)</code>
- Memory (System): <code>11.67GB (2.73GB free)</code>
- Memory (Process): <code>254.17MB working set (256.30MB peak, 161.94MB private, 92.23MB shared)</code>
- Load (avg): <code>1, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|32|
|main|app.isReady => window.loadUrl()|181|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|184|
|renderer|require(workbench.main.js)|333|
|renderer|create extension host => extensions onReady()|403|
|renderer|restore viewlet|197|
|renderer|restore editor view state|0|
|renderer|overall workbench load|287|
|main + renderer|start => extensions ready|1174|
|main + renderer|start => workbench ready|1052|

---

[undefined_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1149321/undefined_renderer.cpuprofile.txt)
[af64_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1149323/af64_main.cpuprofile.txt)

**Comment by nick70** [comment] 2017-07-14 23:19
Just updated vscode on osx. 100% cpu usage and it freezes after about 1 second. 1.14.1

**Comment by chrmarti** [comment] 2017-07-14 23:29
@nick70 Could you open a new issue so we can investigate separately? (Use Help > Report Issues)

**Comment by jrieken** [comment] 2017-07-17 07:40
Hm, https://github.com/Microsoft/vscode/issues/30485#issuecomment-315428566 shows a faster than average startup (~1sec). @dcasella Does the CPU usage appear later when doing some specific work?

**Comment by dcasella** [comment] 2017-07-17 11:17
It just sits around 100-120% for the whole time VSCode is open, idle or not.

While VSCode is running, there are two processes that show higher CPU usage than normal:  
`/usr/bin/dbus-daemon --fork --print-pid 5 --print-address 15 --session`  
`kded5 [kdeinit5]` (as stated in https://github.com/Microsoft/vscode/issues/30485#issuecomment-315033659)  
Both of those processes go from a usual 0-2% usage to 20+%.

**Comment by jrieken** [comment] 2017-07-17 13:13
@joaomoreno can you think of anything that runs (crazy) in the main process after we have started?

@dcasella Does this also reproduce with [insiders](https://code.visualstudio.com/insiders)? Iff so I can make you special build with more logging/profiling support

**Comment by dcasella** [comment] 2017-07-17 14:03
Yes, Code Insiders shows roughly the same CPU usage as Code
```
$ ps aux --sort=-pcpu | grep /code

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
user     16046  113  1.1 1779976 137588 ?      Rl   13:18 180:41 /usr/share/code/code --unity-launch
user     10479  113  0.9 1371092 117864 ?      Rl   15:55   0:49 /usr/share/code-insiders/code-insiders --unity-launch
user     10537  4.2  1.7 1456056 208388 ?      Sl   15:55   0:01 /usr/share/code-insiders/code-insiders --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=F63823E51E7BFD174E2D4248D5E723B5 --lang=en-US --node-integration=true --backgr
ound-color=#1E1E1E --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,
3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3
553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --dis
able-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --service-request-channel-token=F63823E51E7BFD174E2D4248D5E723B5 --renderer-client-id=3 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
user     16120  1.2  1.9 1834724 240636 ?      Sl   13:18   1:59 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=60FE14B5EB45394131BAB8B3BFBEE581 --lang=en-US --node-integration=true --background-color=#1c1c1c
 --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,1
2,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3
553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-v
ideo-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --service-request-channel-token=60FE14B5EB45394131BAB8B3BFBEE581 --renderer-client-id=3 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
user     10543  1.0  0.7 1092532 87864 ?       Sl   15:55   0:00 /usr/share/code-insiders/code-insiders --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=65FDA8B6BB6A5D1249C8E8571A9E6249 --lang=en-US --node-integration=true --hidden
-page --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,
15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,35
53;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-
hw-encoding --disable-gpu-compositing --service-request-channel-token=65FDA8B6BB6A5D1249C8E8571A9E6249 --renderer-client-id=5 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
user     10630  0.9  0.5 934684 62480 ?        Sl   15:56   0:00 /usr/share/code-insiders/code-insiders /usr/share/code-insiders/resources/app/out/bootstrap --type=extensionHost
user     16252  0.1  0.7 1065736 96420 ?       Sl   13:18   0:12 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=extensionHost
user     10481  0.0  0.2 325652 27776 ?        S    15:55   0:00 /usr/share/code-insiders/code-insiders --type=zygote --no-sandbox
user     16049  0.0  0.2 325548 27848 ?        S    13:18   0:00 /usr/share/code/code --type=zygote --no-sandbox
user     16127  0.0  0.7 1049200 90128 ?       Sl   13:18   0:00 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=3678E19D7736A9B329EA68DE354C10EB --lang=en-US --node-integration=true --hidden-page --enable-pin
ch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1
,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,
3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disa
ble-gpu-compositing --service-request-channel-token=3678E19D7736A9B329EA68DE354C10EB --renderer-client-id=5 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
user     16253  0.0  0.4 948640 52172 ?        Sl   13:18   0:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=watcherService
```
This is with a clean (no extensions) Code Insiders install.  
I tried running Code Insiders again after closing Code, and the problem still shows.

**Comment by joaomoreno** [comment] 2017-07-17 14:18
@dcasella Do you see the same CPU like activity when executing [raw Electron](https://github.com/electron/electron/releases/download/v1.6.6/electron-v1.6.6-linux-x64.zip)?

**Comment by jrieken** [comment] 2017-07-17 14:21
Also, try starting like this `code --js-flags="--prof"`. Then let it until the high CPU load happens, quit, and find a couple of `isolate-xyz.log` files. Please share them with us

**Comment by dcasella** [comment] 2017-07-17 14:46
@joaomoreno oh wow, yes, it's around 106%!

@jrieken I let it run for around 5 seconds (and rename the files from .log to .txt so I can share them here).  

---

[isolate-0x3392001df000-v8.txt](https://github.com/Microsoft/vscode/files/1152967/isolate-0x3392001df000-v8.txt)
[isolate-0xeef9c6a2000-v8.txt](https://github.com/Microsoft/vscode/files/1152970/isolate-0xeef9c6a2000-v8.txt)

**Comment by jrieken** [comment] 2017-07-17 15:14
Spends most time in libg*

<img width="738" alt="screen shot 2017-07-17 at 17 13 24" src="https://user-images.githubusercontent.com/1794099/28275159-56ba1770-6b13-11e7-93f1-e1f39da01c81.png">

**Comment by joaomoreno** [comment] 2017-07-18 07:51
electron/electron#8455 mentions dbus and KDE.

Can you try running with `ELECTRON_FORCE_WINDOW_MENU_BAR=1`?

**Comment by dcasella** [comment] 2017-07-18 10:52
Running `ELECTRON_FORCE_WINDOW_MENU_BAR=1 code` resolves the issue, so this is the Electron-KDEGlobalMenu bug.  
Thanks for clarifying where the issue is, and sorry this took longer than it should have, I don't use any other Electron apps so I didn't know.

**Comment by joaomoreno** [comment] 2017-07-18 13:13
No worries @dcasella, it's just as good for us to know that this exists.

cc @bpasero @Tyriar

**Comment by mrKimura** [comment] 2017-09-19 20:39
KDE Neon. VSCode 1.16.1
High CPU usage is still present.

**Comment by xgdgsc** [comment] 2017-10-25 01:28
I 'm on archlinux with latest vscode and kde. I tried `ELECTRON_FORCE_WINDOW_MENU_BAR=1 code` it doesn' t work. VScode starts using all of one core after start with no file open. Raw electron and atom doesn't have this issue.

**Comment by xgdgsc** [comment] 2018-01-05 05:33
I checked my problem is actually caused by https://github.com/Microsoft/vscode/issues/3998 , when I open   the folder `/tmp`.

**Comment by bpasero** [comment] 2018-03-17 06:32
Closing as stale as @gtzinos never replied.

**Closed by bpasero** 2018-03-17 06:32 UTC
Labels: bug, electron, freeze-slow-crash, linux, perf, upstream
