### ISSUE TITLE
Window freeze when Split terminal is selected

### ISSUE THREAD

**Issue by nadjioussama** [microsoft/vscode#116274] opened 2021-02-10 07:20 UTC
Issue Type: <b>Bug</b>

I run a developement server (Django, Angular..)
I select Terminal/Split terminal
I close the new Splitted terminal using the bin icon
The window freezes and i have to wait to the diaolog window to apear so i can choose reopen.
Could be only in my machine but it happened many times before
i use Git bash in the terminal

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3991)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.90GB free)|
|Process Argv|--crash-reporter-id ee0b29d1-3fb1-483c-a990-b0c07ec74d4d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|1.3.0
xml|Dot|2.5.1
gitlens|eam|11.2.1
vscode-html-css|ecm|1.9.1
vscode-npm-script|eg2|0.3.15
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
vue-snippets|hol|1.0.4
Angular2|joh|11.0.0
vscode-docker|ms-|1.9.1
mssql|ms-|1.10.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-wsl|ms-|0.53.3
azure-account|ms-|0.9.5
laravel-blade|one|1.25.0
vscode-yaml|red|0.14.0
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by meganrogge** [comment] 2021-02-10 18:07
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

Duplicate of #116095

**Closed** 2021-02-10 18:07 UTC
Labels: *duplicate

**Comment by nadjioussama** [comment] 2021-02-17 07:51
The same bug still exist in version 1.53.2 and in insider version, when one terminal is running a commande and i close another terminal using the bin icon the window freezes (not always but i this is how it happened with me)
