### ISSUE TITLE
IntelliSense: Sorting is weird in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1290] opened 2015-12-14 15:28 UTC
In a TS file type "for" and auto-complete. You will find a 100% match "for" on the top, but the other 100% match from snippets is not there but rather at the end. If we do not sort unified across the various providers, then maybe we should take out snippets from the list and provide another way of completing snippets.

<img width="513" alt="screen shot 2015-12-14 at 19 32 43" src="https://cloud.githubusercontent.com/assets/900690/11789940/8b11967c-a299-11e5-9807-978e36586b09.png">

**Comment by dbaeumer** [comment] 2015-12-14 16:34
@bpasero I think you are talking about different issues here. Can you please create a bug for Joh about the providers. Then I will take this one for the TS specific isse (e.g no complete in literals)

**Comment by bpasero** [comment] 2015-12-14 18:31
@dbaeumer makes sense, I have created https://github.com/Microsoft/vscode/issues/1304 for the issue with object literals and this one I am not sure if it should go to @joaomoreno or @jrieken

**Comment by dbaeumer** [comment] 2015-12-14 19:35
@bpasero Thanks. Starting with Joh.

**Comment by jrieken** [comment] 2015-12-15 08:31
This is because we sort each group of proposals by itself

**Comment by jrieken** [comment] 2015-12-15 08:48
closing as duplicate of #1190

**Closed** 2015-12-15 08:53 UTC
Labels: bug
