### ISSUE TITLE
Python TUI libraries don't react to Arrow Keys with windowsEnableConpty: True. Everything is ok in Windows Terminal

### ISSUE THREAD

**Issue by an-dr** [microsoft/vscode#147009] opened 2022-04-07 14:10 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 10 19042.1526

Steps to Reproduce:

1. clone and install e.g. https://github.com/Textualize/textual
2. run any of the examples (e.g. textual/examples/code_viewer.py)
3. Try to use arrow keys

We wanted to develop a TUI utility in our company, Our main dev tool is VScode, so we want the utility working in the Code's terminal. We tried a lot of libraries:

- https://www.libhunt.com/r/py_cui
- https://github.com/bczsalba/pytermgui
- https://github.com/jwlodek/py_cui
- https://github.com/Textualize/textual
- etc... More here for example https://www.libhunt.com/l/python/topic/tui

We couldn't make any of them work with the default VSCode configuration. They work only with `"terminal.integrated.windowsEnableConpty": false`. Also, everything is working in any terminal app including Windows Terminal.

**Comment by an-dr** [comment] 2022-04-28 09:09
I can provide any extra info if it speeds up the process 😉

**Comment by meganrogge** [comment] 2022-05-02 17:24
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.
/label upstream terminal-conpty windows

**Closed** 2022-05-02 17:24 UTC
Labels: confirmation-pending
