### ISSUE TITLE
[json] improve error analysis on oneOf

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#22287] opened 2017-03-09 10:34 UTC
Adding an (unexpected) `env` attribute to a launch configuration of type `extensionHost` results in the following error: 

![2017-03-08_12-46-29](https://cloud.githubusercontent.com/assets/1898161/23702884/896352b8-03fd-11e7-8913-580cf69480ed.png)

This error is misleading because the value `extensionHost` is flagged as wrong and not the unexpected use of `env`.

If the key value pair `"foo":"bar"` is removed from the `env` structure the error is flagged correctly:

![2017-03-08_12-52-03](https://cloud.githubusercontent.com/assets/1898161/23703044/3a5f4f04-03fe-11e7-8e0f-ca8a2a6ea397.png)

It would help if the `type` attribute could be somehow excluded from the validation so that the validator does not try to assume that the `type` value is incorrect but all other attributes are correct.

The `type` attribute is basically a 'type defining' attribute that should be left alone.

**Comment by aeschli** [comment] 2017-10-11 08:37
duplicate of #32202

**Closed by aeschli** 2017-10-11 08:37 UTC
Labels: feature-request, json
