### ISSUE TITLE
Color picker doesn't want to appear in .html files

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33622] opened 2017-08-31 22:55 UTC
- VSCode Version: 1.15.1
- OS Version: win7x64

Good feature. But it appears only in .css files. Not in .html files inside tag `<style></style>`
Can somebody fix it?

**Comment by aeschli** [comment] 2017-09-01 09:28
duplicate of #32611

**Closed by aeschli** 2017-09-01 09:28 UTC
Labels: html, new release
