### ISSUE TITLE
Intellisense adds `../node_modules/..` to import suggestions

### ISSUE THREAD

**Issue by TomerAmirV** [Microsoft/vscode#54464] opened 2018-07-17 09:57 UTC
- VSCode Version: 1.25.1
- OS Version: Mac OS 10.13.5

Steps to Reproduce:

1. Create a typescript node server
2. try to import an installed class
3. see suggestion:
![screen shot 2018-07-17 at 12 53 53 pm](https://user-images.githubusercontent.com/19464891/42810458-9fdfac36-89c0-11e8-9b8c-5994796cc8cf.png)
4. expected in this case: `import 'QueryFailedError' from module "typeorm"`, meaning without the `../../node_modules` part

This used to work until I upgraded to the latest version. not sure what version I had before

tsconfig file:
```json
{
	"compilerOptions": {
		"baseUrl": "./",
		"rootDir": "./",
		"outDir": "out",
		"module": "commonjs",
		"moduleResolution": "node",
		"target": "es2015",
		"noImplicitAny": false,
		"sourceMap": true,
		"declaration":false,
		"experimentalDecorators":true,
		"emitDecoratorMetadata": true,
		"isolatedModules": false,
		"suppressImplicitAnyIndexErrors": false,
		"lib": ["es6", "dom", "esnext.asynciterable"],
		"types":[
			"node",
			"jest",
			"express",
			"reflect-metadata",
			"supertest"
		]
	},

	"exclude": [
		"node_modules",
		"out",
		"build"
	]
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-07-17 20:50
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-17 20:50 UTC
Labels: javascript
