### ISSUE TITLE
TERMINAL display incorrectly

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/vscode#26055] opened 2017-05-05 16:15 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|ng-template|Angular|0.1.3|
|angulardoc-vscode|AngularDoc|2.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-simpler-icons|davidbabel|1.3.0|
|githistory|donjayamanne|0.2.0|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|EditorConfig|EditorConfig|0.9.3|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|beautify|HookyQR|1.0.2|
|docthis|joelday|0.4.4|
|Angular2|johnpapa|2.2.3|
|refactorix|krizzdewizz|0.3.3|
|vscode-extension-auto-import|moppitz|1.3.3|
|csharp|ms-vscode|1.9.0|
|typescript-javascript-grammar|ms-vscode|0.0.19|
|angular-io-code|NoHomey|0.0.6|
|vscode-docker|PeterJausovec|0.0.13|
|typescript-hero|rbbit|0.12.0|
|vscode-icons|robertohuertasm|7.6.0|
|ts-import-assistance|Sammons|0.0.10|
|code-settings-sync|Shan|2.7.0|
|vscode-autohotkey|slevesque|0.2.0|
|autoimport|steoates|1.2.2|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Execute `View: Toggle Integrated Terminal` to open terminal and open PowerShell by default
2. The console is not display correctly.  All the characters are not aligned correctly.  See screenshot below:

![image](https://cloud.githubusercontent.com/assets/88981/25754129/ba8eaad8-31f0-11e7-878b-8d55972ee3c3.png)

3. When I execute `cls` to clean Terminal, it back to normal.  But when I execute `dir` agin, it can't get expected display format.  Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/88981/25754237/1046b722-31f1-11e7-9e25-1df6d6d22b96.png)

**Comment by zackschuster** [comment] 2017-05-05 16:37
Can confirm from my home desktop (I can upload a screenshot of `yarn install` when I get the chance -- fun stuff). Curiously, I don't see the issue on my work laptop (MacBook Pro 2015), so maybe it's related to screen size or resolution (both computers run Windows)?

**Comment by doggy8088** [comment] 2017-05-05 16:45
Yes, this is really a High DPI screen on my laptop which screen size is 2560x1440.

**Comment by zackschuster** [comment] 2017-05-05 22:39
@doggy8088 ah, i'm seeing the opposite behavior - my laptop is high DPI, while my home computer is standard 1080p. none of the extensions i share with your setup have different versions either.

**Comment by kieferrm** [comment] 2017-05-05 23:11
This is a duplicate of #19665.

**Closed by kieferrm** 2017-05-05 23:11 UTC
