### ISSUE TITLE
CommandPalette git clone crashes vscode

### ISSUE THREAD

**Issue by Jorval** [Microsoft/vscode#56374] opened 2018-08-14 14:58 UTC
Issue Type: <b>Bug</b>

Hey,
first things first: awesome edoitor i ditched atom  ;)  

after updating vscode to 1.26.0 today it crashes everytime i try to git clone a repository.
i invoke the palette and git clone and he asked me for the url.
normaly the next step is vscode asking for a location where to clone, unfortunally it crashes.   
As suggested i tested with all extensions disabled crashes still.  
the only other thing i did today was installing sshfs extension.  

OS: Arch Linux  
Installation Source: aur/visual-studio-code-bin 1.26.0-2 [installed] [699+] [33.95%] [14 Aug 2018]  

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:25:59.521Z)
OS version: Linux x64 4.17.14-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2634)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.58GB (10.75GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Jorval** [comment] 2018-08-14 19:26
i can also confirm a second installation where it happens and it seems the folder/open dialog causes the crash.

my second maschine is my private gamingrig (also arch) and i had vscode 1.25 installed. unfortunally i didn't tried it before the update to 1.26 but now trying to open a folder crashes vscode.

**Comment by Jorval** [comment] 2018-08-14 19:42
starting in a terminal session i got:
``
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Numix/16/status/image-missing.svg: Bildlader-Modul konnte nicht geladen werden: /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /opt/visual-studio-code/glibc/usr/lib/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libxml2.so.2) (gdk-pixbuf-error-quark, 5)
Server response: <?xml version="1.0" encoding="UTF-8"
Abgebrochen (Speicherabzug geschrieben)
``
sorry part i the message is in german ;)
maybe someone can give me a hint, maybe starting code with a static linked lib?
thx

**Comment by bpasero** [comment] 2018-08-15 12:17
@Jorval this could be an issue with our Electron version, can you try this build that uses a newer Electron version: https://az764295.vo.msecnd.net/exploration/e6caa88a0261e72c41c76ab2ff454b8763a19f73/code-exploration-1534224413.tar.gz

**Comment by bpasero** [comment] 2018-08-15 14:58
Duplicate of https://github.com/Microsoft/vscode/issues/55934

**Closed by bpasero** 2018-08-15 14:58 UTC
Labels: electron-2.0.x-update, freeze-slow-crash, needs more info, new release
