### ISSUE TITLE
[themes] Multiline comment always green no matter what theme

### ISSUE THREAD

**Issue by sethen** [Microsoft/vscode#1705] opened 2015-12-30 03:10 UTC
When writing JavaScript, multiline comments are always the color of dark green no matter what theme I am using.  For example:

```
/**
* This is dark green
*/ 
```

I find this rather annoying as I have my own theme that I like to use.  I compiled my TextMate theme and everything ported over okay using `yo code` besides the multiline comment colors.  This theme works correctly in Sublime Text and TextMate, it's just Visual Studio Code that gives me an issue.

Is this a bug?  Is there a way to turn this off?

**Comment by aeschli** [comment] 2016-01-07 15:33
I don't see that. Using Monokai I get brown as color:
![image](https://cloud.githubusercontent.com/assets/6461412/12173735/d5b14e76-b558-11e5-90bb-3e9b4171d9e8.png)

Monokai defines the comment color on scope `comment`.

To debug this, open the dev tools (F1 > Toggle Developer Tools) to see what css rule matches the token:
![image](https://cloud.githubusercontent.com/assets/6461412/12174226/c77f4c88-b55b-11e5-9195-b63d41863c47.png)

**Comment by sethen** [comment] 2016-01-09 03:13
It looks like you just have one asterisk where in this example there are two asterisks.  I think VSCode believes to be something other than a comment maybe.
![darkgreen](https://cloud.githubusercontent.com/assets/1493530/12214076/e8348e08-b654-11e5-8dd4-2ba0c97bcdd0.jpg)

**Comment by sethen** [comment] 2016-01-09 03:14
It looks like you just have one asterisk where in this example there are two asterisks. I think VSCode believes to be something other than a comment maybe.
![darkgreen](https://cloud.githubusercontent.com/assets/1493530/12214091/3ed9372c-b655-11e5-8989-3931e31a166d.jpg)

**Comment by aeschli** [comment] 2016-01-13 15:04
I also tried with 
```
/**
 *
 */
```
Can you try to debug it with the developer tools as I described in the comment above?

**Comment by sethen** [comment] 2016-01-31 19:46
Looks like the double asterisks are using a different CSS class then a single asterisk:
![double-asterisks](https://cloud.githubusercontent.com/assets/1493530/12704445/46b1cece-c829-11e5-984f-79183ac11ff4.jpg)

![single-asterisk](https://cloud.githubusercontent.com/assets/1493530/12704446/46b67bf4-c829-11e5-9b37-257257f08160.jpg)

**Comment by sethen** [comment] 2016-01-31 19:50
Looks like the single asterisk applies the correct class, but the double asterisk does not for whatever reason:
![double-asterisks](https://cloud.githubusercontent.com/assets/1493530/12704473/e0871e78-c829-11e5-8519-dfe6d01c5a7e.jpg)
![single-asterisk](https://cloud.githubusercontent.com/assets/1493530/12704472/e0856d1c-c829-11e5-84a0-259eb20992f6.jpg)

**Comment by aeschli** [comment] 2016-08-08 13:33
Closing as I can't reproduce.

**Closed by aeschli** 2016-08-08 13:33 UTC
Labels: bug, needs more info, themes
