### ISSUE TITLE
Can not set a breakpoint to the right panel, when editor is split in half

### ISSUE THREAD

**Issue by cmario92** [microsoft/vscode#105100] opened 2020-08-20 18:27 UTC
- VSCode Version: 1.49.0-insider
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Split the editor vertically
2. Try to set up a breakpoint to the right panel
3. Verify that the breakpoint is not set

Additional Notes:
Moving the file to the left, original side of the editor, seems to be able to attach a breakpoint.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dalmo3** [comment] 2020-08-21 01:45
Same here, except:

1) It's random; I can't reproduce it.
2) Also happened with the left side editor once, but it's mostly on the right side.

VSCode Version: 1.49.0-insider
OS Version: Windows 10 18363

**Comment by isidorn** [comment] 2020-08-21 08:26
This is fixed in latest vscode insiders.
If you can still repro with latest insiders please let me know and I will reopen. Thanks and sorry about this

**Closed by isidorn** 2020-08-21 08:26 UTC
Labels: debug
