### ISSUE TITLE
Tasks.json schema can not be resolved error

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#64005] opened 2018-11-29 17:43 UTC
Issue Type: <b>Bug</b>

Started seeing this problem when I open my `tasks.json` file on the latest insiders:
> $ref 'definitions/shellConfiguration22' in 'vscode://schemas/tasks' can not be resolved.

AFAIK my tasks.json is pretty simple:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "compile",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "isBackground": true,
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$tsc-watch"
        },
        {
            "type": "npm",
            "script": "lint",
            "problemMatcher": "$tslint5"
        }
    ]
}
```

VS Code version: Code - Insiders 1.30.0-insider (cd5b4d1bb3fc7e509fba077095b2b280b8ff7161, 2018-11-29T06:12:26.485Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
vscode-azureappservice|ms-|0.10.0
python|ms-|2018.11.0-beta
azure-account|ms-|0.7.0
csharp|ms-|1.17.1
vscode-docker|Pet|0.4.0

</details>

**Comment by MilamBardo** [comment] 2018-11-30 12:56
I'm seeing this too.

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-w", "-p", "."],
    "showOutput": "silent",
    "isWatching": true,
    "problemMatcher": "$tsc-watch"
}`

**Comment by alexr00** [comment] 2018-12-03 11:57
Duplicate of #64071

**Closed** 2018-12-03 11:57 UTC
Labels: insiders
