### ISSUE TITLE
MarkDown syntax C++ code segment high-light is broke.

### ISSUE THREAD

**Issue by FilaretKun** [microsoft/vscode#79801] opened 2019-08-26 09:59 UTC
Issue Type: <b>Bug</b>

In '{}' brackets of any C++ code segment, those code won't be highlighted.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
code-runner|for|0.9.14
cpptools|ms-|0.25.0
markdown-preview-enhanced|shd|0.4.3

(14 theme extensions excluded)

</details>

**Comment by MarcelGerber** [comment] 2019-08-28 23:34
Can repro in `c` and `cpp` modes, making sure that `c#` and `java` work as expected:
![image](https://user-images.githubusercontent.com/2641501/63899271-857cc900-c9fc-11e9-87d0-bc54d52bbe15.png)

(To the left, the test markdown document can be seen; on the right there is the cpp file properly highlighted)

<details>
 <summary>Markdown test document</summary>

`````md
Test

```cpp
int id;
void test {
	int num;
}
```

```c
int id;
void test {
	int num;
}
```

```c#
int id;
class Main {
	int num;
}
```

`````
</details>

**Comment by matter123** [comment] 2019-08-28 23:39
@MarcelGerber 
> Edit: running the latest OSS Dev version, without extensions

Do you mean Visual Studio Code Insiders?

**Comment by mjbvz** [comment] 2019-08-28 23:39
This is likely a duplicate of #34525

As far as I can tell, we cannot fix this in VS Code itself; the upstream grammar requires changes

**Closed by mjbvz** 2019-08-28 23:39 UTC
Labels: needs more info

**Comment by MarcelGerber** [comment] 2019-08-29 00:07
Ah, I see. Apparently, there's an upstream fix available that can (hopefully) be incorporated into the next VS Code version.

@FilaretKun If you can't wait for a fix, you can install https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax, which provides you with the latest version of the C++ syntax and fixes this bug.
