### ISSUE TITLE
TypeScript language service died unexpectedly

### ISSUE THREAD

**Issue by bsurendrakumar** [Microsoft/vscode#18348] opened 2017-01-10 05:42 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 3.16.0-4-amd64
- Extensions:

|Extension|Author|Version|
|---|---|---|
|ejs-language-support|QassimFarid|0.0.1|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-yaml-validation|djabraham|0.0.1|
|python|donjayamanne|0.5.2|
|docthis|joelday|0.3.6|
|markdown-table-formatter|josa|0.0.4|
|Go|lukehoban|0.6.52|

---

Steps to Reproduce:

Following error is repeatedly appearing in the editor.

`
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report.
`

**Comment by mjbvz** [comment] 2017-01-10 19:53
Can you share your workspace?

Also, please try setting `"typescript.tsserver.trace": "verbose"` and the restarting VSCode. Open the output panel and select the  `TypeScript` output. This may help us investigate the root cause

**Comment by dipetersen** [comment] 2017-01-12 19:10
I get the same thing.  It is annoying since I don't even use TypeScript.

**Comment by mjbvz** [comment] 2017-01-13 01:35
@dipetersen We use the TypeScript project to power intellisense for both JavaScript and TypeScript.

If you are seeing this problem, please try setting "typescript.tsserver.trace": "verbose" and the restarting VSCode. Open the output panel and share the `TypeScript` output so we can investigate. 

Thanks

**Comment by tomi** [comment] 2017-01-16 12:47
I'm experience the same issue. The language server works for awhile but then just stops working and I need to restart VSCode.

Verbose output from the tsserver can be found from [here](http://pastebin.com/J2WyJYdR)

**Comment by dipetersen** [comment] 2017-01-16 19:37
Output from trace is here:  http://pastebin.com/BzGuhuci

**Comment by bsurendrakumar** [comment] 2017-01-17 04:46
Here is the output trace from my workspace,

http://pastebin.com/T5tkuFAN

**Comment by mjbvz** [comment] 2017-01-17 22:05
Thanks everyone.

I see two errors from these logs: 

* @dipetersen: `TSServer exited with code: 3221226356`
* @bsurendrakumar and @tomi:  `TSServer exited with code: unknown`

@mhegazy Do either of these sound familiar? 

---

As a workaround, you may want to try installing TS 2.1.5. This comes bundled with our latest VSCode 1.9 insiders builds, or you can install it into your workspace using `npm install typescript@2.1.5` and updating the `typescript.tsdk` setting to point to the local install: `"typescript.tsdk": "./node_modules/typescript/lib"`

**Comment by tomi** [comment] 2017-01-20 07:38
I can confirm that the issue doesn't exist anymore with Version 1.9.0-insider (1.9.0-insider)

**Comment by tomi** [comment] 2017-01-20 07:41
I am still getting the error `[Error - 4:56:01 PM] TSServer exited with code: unknown` with the version Version 1.9.0-insider (1.9.0-insider). Tho it doesn't happen constantly anymore, like with the earlier version

**Comment by mhegazy** [comment] 2017-01-21 22:21
@tomi, is there a specific project/file/action that you can associate with the issue? can you share the log file from the server (by setting the [`TSS_LOG`](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)#logging) env var, and starting vscode from the same environment)?

**Comment by neilhoff** [comment] 2017-01-27 16:53
I am getting the same thing and I do not use TypeScript either.  

Is there a way to turn off the warning message?  It keeps sliding down from the top every couple seconds and it is very annoying.

**Comment by mjbvz** [comment] 2017-02-08 02:04
#20081 fixed a few issues that were causing the TS warning message to constantly be displayed

Crashes with exit code `3221226356` were likely due to this bug when trying to open a file stored on Sharepoint: https://github.com/Microsoft/TypeScript/issues/13874 We're working on a fix for this.

Please try out 1.9 and let me know if you are still seeing this issue when not working with a Sharepoint directory. If you are, please collect logs using [`TSS_LOG`](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)#logging) as @mhegazy suggests and open a new issue so that we can track individual problems better.

Thanks

**Closed by mjbvz** 2017-02-08 02:04 UTC
Labels: bug, javascript, needs more info, typescript
