### ISSUE TITLE
Error: Data tree node not found: [object Object]

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#73469] opened 2019-05-08 13:01 UTC
Steps to Reproduce:

1. run out of sources
2. open https://github.com/microsoft/vscode-extension-samples/tree/master/fsprovider-sample
3. run the extension and open an empty folder
4. Run `MemFS: Setup Workspace`
4. Run `MemFS: Create Files`

=> 🐛 in the console you can see:

```
[Extension Host] MemFS says "Hello" (at activate (/Users/bpasero/Development/Microsoft/vscode-extension-samples/fsprovider-sample/out/src/extension.js:6:13))
14:59:40.506 log.js:139   ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:420:23)
    at WorkbenchAsyncDataTree.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:329:35)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:7:58)
```

**Comment by isidorn** [comment] 2019-06-27 14:06
The issue is that I call `tree.setInput` two times due to explorer visibility change and the change in roots. While the second one is in progress, we call `expand` on the tree.
This leaves tree in a bad state.
We could not distill this in a unit test.
Anyways not for endgame, moving to next mielstone

**Comment by isidorn** [comment] 2019-09-04 09:37
@joaomoreno I can still reproduce this with your latest fix. Not sure if we also want to fix this? I think it is a corner case compared to the other issue (thus assigning to on-deck and you can assign back)

**Comment by joaomoreno** [comment] 2019-09-04 15:36
@isidorn I can not reproduce this in `master`.

**Comment by isidorn** [comment] 2019-09-06 12:57
Fixed by joao, can no longer reproduce. Seems like 2 days ago I was testing without the fix.
@bpasero please let us know if you still see this.

**Closed by isidorn** 2019-09-06 12:57 UTC
Labels: bug, file-explorer
