### ISSUE TITLE
Integrated terminal prompt shifting down 

### ISSUE THREAD

**Issue by mnpw** [microsoft/vscode#102502] opened 2020-07-14 15:16 UTC
- VSCode Version: 1.47.0
- OS Version: macOS Catalina 10.15.3
- Shell: `bash`, `zsh` (without custom `.{bash, zsh}rc`)

Steps to Reproduce:

1. Open integrated terminal. <kbd>⌃</kbd>+<kbd>`</kbd>
2. Close integrated terminal. <kbd>⌃</kbd>+<kbd>`</kbd>
3. Open integrated terminal again. <kbd>⌃</kbd>+<kbd>`</kbd>

Prompt shifts down. Newline are not added, shift is caused by VSCode UI itself.  
This happens when 
- VSCode is open in external monitor
- one step zoom is enabled (<kbd>⌘</kbd>+<kbd>=</kbd> once). 

This resolves automatically otherwise.

Does this issue occur when all extensions are disabled?: Yes

![out](https://user-images.githubusercontent.com/13679906/87443291-ed3b0300-c612-11ea-94ca-94be9f28eeda.gif)

**Comment by rzhao271** [comment] 2020-11-04 23:56
Reproduced on WSL

**Comment by rzhao271** [comment] 2020-11-04 23:59
Duplicate of #97808

Or at least, it's another way to cause that rendering glitch.

**Closed by rzhao271** 2020-11-04 23:59 UTC
Labels: bug, confirmed, integrated-terminal
