### ISSUE TITLE
Minimap in floating window changing when main window's zoom changes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#203127] opened 2024-01-23 11:03 UTC
Testing #202922

1. Drag out a floating window.
2. Change the zoom in the main window. See that the minimap on the floating window changes

![Recording 2024-01-23 at 12 01 16](https://github.com/microsoft/vscode/assets/38270282/8ec13915-d9b3-44d1-85c7-cff1c93b97b4)

**Comment by bpasero** [comment] 2024-01-23 16:29
This might be a duplicate of https://github.com/microsoft/vscode/issues/195888

Relevant listener is: https://github.com/microsoft/vscode/blob/39804fae310663346fd29efeb09e68a99bae5e29/src/vs/editor/browser/config/editorConfiguration.ts#L88

**Closed** 2024-01-25 14:04 UTC
Labels: bug, *duplicate, editor-minimap, workbench-auxwindow
