### ISSUE TITLE
markdown preview doesn't show images with whitespace in filename (on Linux)

### ISSUE THREAD

**Issue by BvdP** [Microsoft/vscode#26928] opened 2017-05-19 10:01 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.9.0-0.bpo.2-amd64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.12.0|
|python|donjayamanne|0.6.0|
|vscode-todo-parser|minhthai|1.8.9|
|cpptools|ms-vscode|0.10.4|;

---
I did a search for this issue and found this closed issue: https://github.com/Microsoft/vscode/issues/7898 which seems to be the same problem.

This is obviously for an other version of Code and on an other OS.

Steps to Reproduce:
1. This works fine: `![Test image](images/test_image.svg)` as long as `test_image.svg` exists
2. Replace the underscore with a whitespace and rename the file accordingly, now it just shows `![Test image](images/test image.svg)` in the preview i.e. just the text, no image.

**Comment by mjbvz** [comment] 2017-05-19 21:05
Markdown does not support spaces in image urls. See https://github.com/Microsoft/vscode/issues/11933#issuecomment-249987377

Closing as designed / duplicate of #7871

**Closed by mjbvz** 2017-05-19 21:05 UTC
Labels: as-designed, duplicate, markdown
