### ISSUE TITLE
hover markdown formatting is too spacious

### ISSUE THREAD

**Issue by maxandersen** [Microsoft/vscode#8831] opened 2016-07-07 10:36 UTC
```
The System class contains several useful class fields and methods. It cannot be instantiated. 
 Among the facilities provided by the System class are standard input, standard output, and error output streams; access to externally defined properties and environment variables; a means of loading files and libraries; and a utility method for quickly copying a portion of an array. 
* **Author:**
    * unascribed
* **Since:**
    * JDK1.0
```

becomes:

<img width="744" alt="_extension_development_host__-_app_java_-_my-app" src="https://cloud.githubusercontent.com/assets/54129/16650599/55aa432e-443f-11e6-9cfe-dfd559fa61f3.png">

I would expect something more compact like this:

<img width="786" alt="_extension_development_host__-_preview__test_md__-_my-app_and_extension_ts_-_client_and_new_issue_ _microsoft_vscode" src="https://cloud.githubusercontent.com/assets/54129/16650614/696b31fc-443f-11e6-8fba-9fe6ece46a4d.png">

**Comment by jrieken** [comment] 2016-07-07 10:58
this is what get's generated - we do need more style

```html
<div>The System class contains several useful class fields and methods. It cannot be instantiated.
Among the facilities provided by the System class are standard input, standard output, and error output streams; access to externally defined properties and environment variables; a means of loading files and libraries; and a utility method for quickly copying a portion of an array.</div><ul>
<li><strong>Author:</strong><ul>
<li>unascribed</li>
</ul>
</li>
<li><strong>Since:</strong><ul>
<li>JDK1.0</li>
</ul>
</li>
</ul>
```

**Comment by jrieken** [comment] 2016-07-13 07:47
@joaomoreno Do you happen to know if we apply any styles to `li` tags?

**Comment by joaomoreno** [comment] 2016-07-13 08:05
Not that I know of. But feel free to merge this with #2330

**Comment by jrieken** [comment] 2016-07-13 09:17
ok, closing as dupe of #2330

**Closed by jrieken** 2016-07-13 09:17 UTC
Labels: bug, duplicate, editor
