### ISSUE TITLE
Feature Request: Add Syntax Highlighting for Semantic TypeScript Diagnostics

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#100742] opened 2020-06-22 08:55 UTC
It is very hard to see what is going on given this error message:

![image](https://user-images.githubusercontent.com/2931520/85266629-6a3fe600-b474-11ea-9739-3af963b97f02.png)

If VS Code's markdown support could be used in those semantic diagnostics, types could be put in code blocks. This would increase readability significantly.

![image](https://user-images.githubusercontent.com/2931520/85266762-a115fc00-b474-11ea-9158-574b44271f61.png)

I suggest the following rule:
Treat everything in TS error messages enclosed with ' as code (in the following `$code`). If `$code` is shorter than 15 characters, emit it as `` `$code` ``, otherwise as

    ```ts
    $code
    ```

Of course this makes the assumption that the formatting of types is consistent and typescript does not nest `'` in its error messages. String literal types use `"`.

If you point me to the central code locations that might need to be touched, I can try to create a PR for this.

**Comment by sandy081** [comment] 2020-06-24 04:37
@mjbvz Is this duplicate of https://github.com/microsoft/vscode/issues/54272 ?

**Comment by hediet** [comment] 2020-06-24 07:47
Oh, I assumed displaying markdown in diagnostics was already possible. Additionally to #54272, this would also need concrete changes for the typescript extension to make use of the markdown.

**Comment by mjbvz** [comment] 2020-06-24 19:17
Closing as a duplicate of #54272

@hediet Yes, we would only want to enable highlighting if an extension requests it (such as using markdown code blocks)

**Closed by mjbvz** 2020-06-24 19:17 UTC
