### ISSUE TITLE
[c++] syntax highlighting stops at middle of a file on ruby.h

### ISSUE THREAD

**Issue by yasmise** [Microsoft/vscode#17840] opened 2016-12-27 02:51 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10 Home 14393.576

Steps to Reproduce:

1. Open `include\ruby\ruby.h` of ruby 2.4.0 source code. Link to the archive is [Here](https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.gz).
2. Scroll to line 1810.
3. Highlighting stops at line 1810. Please see this screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/22886576/21488970/f958e9c8-cc28-11e6-9027-3dde375f07e2.gif)

Note:
- Visual Studio 2015 community shows highlighting correctly.
- This issue might be same to #16605.

**Comment by aeschli** [comment] 2016-12-29 01:13
The problem is that the atom/language-c grammar pushes text mate states and does not pop them. We stop tokenizing wen the stack reaches a size of 100.
Each line like `NORETURN(void rb_mod_syserr_fail(VALUE, int, const char*));`
puts the states `meta.parens.c` and `meta.function.c` which are not removed anymore.

It's a duplicate of https://github.com/atom/language-c/issues/155

**Closed by aeschli** 2016-12-29 01:13 UTC
