### ISSUE TITLE
v1.33 Intellisense hangs / stops working in React native Typescript

### ISSUE THREAD

**Issue by changLiuUNSW** [Microsoft/vscode#72583] opened 2019-04-18 23:01 UTC
VSCode Version: 1.33
OS Version: windows 10 x64

Steps to Reproduce:

1. Work on react native javascript code for a few hours
2. Intellisense stops working (the 'Loading' tooltip shows of the intellisense but nothing else)

It works fine after downgrading to 1.32.

here is my log:
[tsserver.log](https://github.com/Microsoft/vscode/files/3096431/tsserver.log)

**Comment by mjbvz** [comment] 2019-04-19 00:45
What version of `@types/styled-components` do you have installed in the project? Try upgrading it to the latest version if it is not on it

**Comment by changLiuUNSW** [comment] 2019-04-19 04:37
I just upgrade ```@types/styled-components``` from ```4.1.14``` to ```4.1.10```. All good now. Thanks @mjbvz.

**Comment by changLiuUNSW** [comment] 2019-04-19 04:42
Just upgraded. All

**Comment by mjbvz** [comment] 2019-04-19 16:55
Thanks for checking.

This is a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391 See that issue for more information about the problem

**Closed by mjbvz** 2019-04-19 16:55 UTC
Labels: javascript, needs more info
