### ISSUE TITLE
problem with extension simple ftp after january 2019 update

### ISSUE THREAD

**Issue by jaroslaw-filipiak** [Microsoft/vscode#68300] opened 2019-02-09 06:19 UTC
Issue Type: <b>Bug</b>

after update january 2019 extension: ftp-simple stop working, after downgrade visual studio code to version from december 2018 extension working good

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (9.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
file-icons|fil|1.0.16
sass-lint|gle|1.0.4
beautify|Hoo|1.4.8
ftp-simple|hum|0.6.9
vscode-apache|mrm|1.2.0
vscode-autoprefixer|mrm|2.2.0
debugger-for-chrome|msj|4.11.1
vetur|oct|0.15.0
live-sass|rit|3.0.0
LiveServer|rit|5.4.0
sass-indented|rob|1.5.1
file-size|zh9|0.1.3

(2 theme extensions excluded)

</details>

**Comment by usernamehw** [comment] 2019-02-09 13:27
/duplicate of https://github.com/humy2833/FTP-Simple/issues/177

**Closed** 2019-02-09 13:27 UTC
Labels: *duplicate, extensions
