### ISSUE TITLE
In new version, all extension with github account can't work with vscode.dev'sredirect

### ISSUE THREAD

**Issue by huge-pancake** [microsoft/vscode#147446] opened 2022-04-14 10:53 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.66.2

- OS Version:Windows 10 21H2 19044.1586 Windows Feature Experience Pack 120.2212.4170.0

When I use Github Copilot or Gitlens and other plugins that require Github login, after the Github login verification is successful, the connection will jump to vscode.dev and jump, then the tab page will disappear, there is no response from vscode, the card is stuck in the status of being logged in.
It might be a problem with my computer, but I would like to provide an “Didn't work?” like the previous login page and give a retry link，and in vscode also has this way's interface，allows us to log in even when we cannot jump normally
(↓↓↓↓↓↓↓↓↓↓↓)
<img width="920" alt="Screenshots 2022-04-14 185203" src="https://user-images.githubusercontent.com/73375859/163377097-7f425271-99db-4bad-b48c-69e189459640.png">
(↑↑↑↑↑↑↑↑↑↑↑)
My temporary solution is: Download low version VSCode and sign in Github, then update to high version.

**Comment by huge-pancake** [comment] 2022-04-14 11:38
I translated it

**Comment by TylerLeonhardt** [comment] 2022-04-14 16:44
@huge-pancake 
I'd like to understand why your browser doesn't redirect correctly to vscode.

What browser are you using?

also this looks like a duplicate of #147104

**Comment by huge-pancake** [comment] 2022-04-15 00:22
Google Chrome 102.0.4997.0 dev 64 bit

**Comment by huge-pancake** [comment] 2022-04-15 00:27
Google Chrome 102.0.4997.0 dev 64bit
VSCode 1.66.2(System Install ; .zip portable mode)
I don't know why, today when I use VSCode System Installed to try sign in Github, it's OK...
Then I try the .zip portable version, it's OK now, too...
Sorry I can't give you any useful info now because they all run well now.

**Comment by huge-pancake** [comment] 2022-04-15 00:36
Please also provide an “Didn't work?” like the previous login page and give a retry link，and in vscode also has this way's interface，allows us to log in even when we cannot jump normally
Maybe sometimes I can't sign in Github again, then I can use the retry url to sign in.

**Comment by TylerLeonhardt** [comment] 2022-04-15 00:37
No problem, @huge-pancake! I'm glad it's working for you now. If it stops working again, please open another issue :)

**Closed** 2022-04-15 00:38 UTC
Labels: needs more info, new release

**Comment by TylerLeonhardt** [comment] 2022-04-15 00:39
I'm closing this because it's a duplicate of #147104
