### ISSUE TITLE
Make an option to ignore "a 'return' statement can only be used within a function body" problem

### ISSUE THREAD

**Issue by EhudKirsh** [microsoft/vscode#144413] opened 2022-03-04 15:51 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: February 2022
- OS Version: Irrelevant

Steps to Reproduce:

1. onkeydown="return NotNeg(event)" onpaste="return NotNeg(event)" ondrop="return NotNeg(event)"
2. Make Sure You Have The Latest Updated Version Of VS Code

The 'Problems' pane will give the problem: "a 'return' statement can only be used within a function body". These functions work perfectly with the 'return' written in and do not work well without it. I uninstalled this version and reinstalled the January 2022 version, as I used it until yesterday, and it worked perfectly without showing this issue.

What I want: I just want an option to right-click on this issue and have the option to ignore it so it doesn't show up, as well as be able to see and edit all ignored issues in some settings.

**Comment by aeschli** [comment] 2022-03-07 09:12
duplicate of #143220

I don't think we need a setting, we just have to fix the issue and not issue a error.

**Closed by aeschli** 2022-03-07 09:12 UTC
Labels: triage-needed
