### ISSUE TITLE
Confusing behavior when moving cursor between lines containing full-width characters and half-width characters

### ISSUE THREAD

**Issue by JieJiSS** [Microsoft/vscode#44357] opened 2018-02-25 13:30 UTC
- VSCode Version: 1.20.1
- OS Version: Microsoft Windows 7 (6.1.7601 Service Pack 1 Build 7601)

Steps to Reproduce:

1. Open a file which contains full-width characters and half-width characters.
2. Use <kbd>↑</kbd> and <kbd>↓</kbd> to move the cursor between lines
If the text is like this:

```
ＡＡＡＡＡＡＡＡ
aaaaaaaaaaaaaa
```

and your cursor is at the end of the first line, you will find out that if you press <kbd>↓</kbd>, the cursor will be right after the 8th `a`, which means that it is at the middle of the second line (instead of after the last `a`). What I want to say is that visually the cursor will move in the horizontal direction even if the user hasn't pressed <kbd>←</kbd> or <kbd>→</kbd>. So, did you designed this behavior intentionally or this is an unexpected behavior?

(Well, I'm a Chinese user and all of the Chinese characters are full-width characters, so for me, this is a quite confusing behavior.)

Does this issue occur when all extensions are disabled?: Yes

**Comment by yh1224** [comment] 2018-03-14 23:32
This issue is also fixed by #44259.

**Comment by alexandrudima** [comment] 2018-03-27 16:29
Duplicate of #22717

**Closed by alexandrudima** 2018-03-27 16:29 UTC
Labels: editor-core, feature-request
