### ISSUE TITLE
Window decorations (close, minimise, maximise) does not match OS

### ISSUE THREAD

**Issue by AnharHussainMiah** [Microsoft/vscode#65784] opened 2018-12-28 17:11 UTC
![wrong_side](https://user-images.githubusercontent.com/13603136/50522524-3ecc7d00-0ac3-11e9-99c2-f5d888f98e2e.png)

Just updated to the latest VSC. and the "close, minimise, maximise" buttons are:

* on the wrong side
* not using the OS decorations (see Firefox highlighted in Green)

How do I change this to use the OS decorations?

**Comment by yume-chan** [comment] 2018-12-29 03:37
I assume you are using Linux because you just say "OS" but not which.

Duplicate of #65241

**Comment by AnharHussainMiah** [comment] 2019-01-03 12:06
@yume-chan apologies, yes it is Linux.

@francoism90 

I can confirm that after setting the `titleBarStyle` to native this rendered as expected, however I do now believe:

* Native should be the default
* There should be some more prominent documentation around CSD, as I could not find out this information even via Google.

**Comment by sbatten** [comment] 2019-02-01 22:06
/duplicate 
https://github.com/Microsoft/vscode/issues/53650

**Closed** 2019-02-01 22:06 UTC
Labels: *duplicate
