### ISSUE TITLE
Dropdown: Missing click events between elements

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#42421] opened 2018-01-30 10:39 UTC
Testing #40589

Seen on Linux.

There's an area between items where no click is registered:

![cap](https://user-images.githubusercontent.com/22350/35561915-1a8bbdb4-05b2-11e8-8b8d-3e2f0474f5e3.gif)

**Comment by joaomoreno** [comment] 2018-01-30 10:42
The area to the right is the scrollbar area. That should be a fix in the scrollbar itself, IMO. If it's not visible, it should `pointer-events: none;`.

**Comment by bpasero** [comment] 2018-01-30 11:02
@cleidigh fyi

**Comment by bpasero** [comment] 2018-01-31 10:54
@joaomoreno I can reproduce the same issue with hover feedback in the breakpoints view.

**Comment by joaomoreno** [comment] 2018-01-31 12:23
@bpasero That's what I said yesterday: this is a problem with the scrollable view.

> That should be a fix in the scrollbar itself, IMO. If it's not visible, it should `pointer-events: none;`.

**Comment by cleidigh** [comment] 2018-02-02 01:51
@joaomoreno 
@bpasero 
back online, just capturing these assignments.

Shall I address this within the scrollbar myself?

**Comment by joaomoreno** [comment] 2018-02-02 08:39
@cleidigh Yeah, I wanted to only mention that I observed it in Linux.

I've extracted the scrollable element bug into https://github.com/Microsoft/vscode/issues/42801, I'll take that one.

I also changed the title to only address the clicking between elements.

**Comment by raygervais** [comment] 2018-03-08 15:09
@cleidigh, if no one is working on this I'd like to take a try at it.
I am not able to reproduce on the latest version of code `February 2018, 1.21` on Windows, will test on Linux tonight and report if this is resolved or not.

Mouse was positioned right at the edge of the selected item, where a scrollbar would be.
![screenshot 2](https://user-images.githubusercontent.com/14265337/37158166-b89d0daa-22b8-11e8-9d23-3491a61a73bd.png)

**Comment by raygervais** [comment] 2018-03-19 22:44
Sorry for the delay, can confirm once `1.21` was updated on Fedora 27 that I was unable to reproduce this issue. Can we close this if it's no longer a bug? @cleidigh any other verification required?

**Comment by cleidigh** [comment] 2018-03-20 04:11
@raygervais 
apologies for my delay !  I cannot directly test Linux especially with the mouse issues so we have to verify with @joaomoreno  ... do you still see this?

**Comment by joaomoreno** [comment] 2018-03-20 08:57
@cleidigh Yeah I can still reproduce it.

**Comment by cleidigh** [comment] 2018-03-20 17:36
@raygervais 
I'm in the middle of a couple other bugs with the drop-down so if you want to start a must that be great.
From @joaomoreno note above:  This started as two issues, the problem with the scrollbar area or just the right of it has been addressed.  The remaining issue is the problem between elements.  Also the problem has to be reproduced on Windows or OS X to understand if it is or is not platform specific.

**Comment by raygervais** [comment] 2018-03-20 17:44
I'll look into this today @cleidigh , @joaomoreno. I must have missed the issue itself while testing. Will be sure not to do so going forward. Will work on Windows and Linux while testing. Thanks for the direction! 👨‍💻

**Comment by cleidigh** [comment] 2018-03-23 21:48
@raygervais 
GoodThatYouCanReproduceItOnWindows.
I agree that there's probably a border or outline or padding that must somehow not be clickable.  My confusion on this is that most parts are fully managed by the list component.  

there's only so many things that we can do with the CSS that I think would be related, just not sure.

**Closed** 2020-11-02 14:03 UTC
Labels: *out-of-scope
