### ISSUE TITLE
"Debug: Attach to Node Process" parses wrong port when IP address is included

### ISSUE THREAD

**Issue by andrewbranch** [Microsoft/vscode#52238] opened 2018-06-18 23:05 UTC
- VSCode Version: 1.24.1
- OS Version: macOS 10.13.6 Beta

**Steps to Reproduce:**

1. In a terminal (internal or external, doesn’t matter), run `node --inspect=0.0.0.0:9229`
2. In VS Code, open the command palette and select "Debug: Attach to Node Process"
3. Observe the dropdown item corresponding to the node process you started in step 1

**Expected result:** the debug port is 9229

**Actual result:** the debug port is 0

Does this issue occur when all extensions are disabled?: Yes

**Screenshot:**

<img width="1078" alt="screen shot 2018-06-18 at 3 47 47 pm" src="https://user-images.githubusercontent.com/3277153/41566447-595c6536-7310-11e8-8437-2d4b78870f37.png">

**Discussion:**

Specifying `--inspect=0.0.0.0:<port>` is common for running node inside Docker and debugging on the host machine (example: #23257).

I'm not sure about other use cases for specifying a host for `--inspect`; I guess theoretically it's possible that the host is remote, and VS Code is only trying to connect its debugger over localhost. But, I would argue that assuming localhost and parsing the port correctly is much better than the status quo.

**Comment by weinand** [comment] 2018-07-02 08:59
duplicate of #46670

**Closed** 2018-07-02 08:59 UTC
Labels: *duplicate, bug, debug
