### ISSUE TITLE
Make variables and callstack to reload asynchronously [feature request]

### ISSUE THREAD

**Issue by wcscmp** [Microsoft/vscode#22807] opened 2017-03-17 20:25 UTC
- VSCode Version: 1.10.2
- OS Version: Ubuntu 14.04

When debugging with gdb doing step over takes a lot of time. Debugger is blocked until variables and call stack is reloaded.

**Comment by isidorn** [comment] 2017-03-20 14:55
Well we fetch variables and the call stack asynchroniously so the whole UI should not be blocked.
However of course that you can not step over until we have the call stack and that you can not inspect variables until those are fetched.

If you only see this slowness for the gdb debugger then I suggest you open this issue on the gdb side and suggest that they mark more Scopes as [`expensive`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1138).
Another thing the gdb debugger can improve is to use [`indexedVariables`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1136) for cases where there are scopes and variables with a large number of children.

I believe VSCode is already doing everything here it can thus closing as designed

**Closed by isidorn** 2017-03-20 14:55 UTC
Labels: debug

**Comment by wcscmp** [comment] 2017-04-28 06:02
Maybe it is debugger specific thing but some debuggers can do a step over before variables are fetched and call stack is known. Can you please allow it to be configurable by debugger plugin?

**Comment by isidorn** [comment] 2017-04-28 07:45
Well call stack has to be known in order for the step to be "done", since the call stack deteremines the step location.
While the variables are fetched asynchrounisly. Namely, you should be able to step while the slow variables request is being completed (shown in the variables tree as a loading spinning icon)
