### ISSUE TITLE
When terminal is focused, selecting test in editor won't focus the editor

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#8237] opened 2016-06-28 04:28 UTC
- VSCode Version: 1.2.1
- OS Version: OS X

Steps to Reproduce:

1. Open terminal 
2. Open a text editor as well
3. Execute a command in terminal 
4. Using mouse make a selection in editor 

Editor is not focused. You have to click on editor again to focus in it

**Comment by bpasero** [comment] 2016-06-28 05:25
I cannot reproduce, @mohsen1 any more details? video / screenshot maybe?

**Comment by mohsen1** [comment] 2016-06-28 05:31
It's actually not just by selecting. Clicking on the editor won't switch the focus either. 

I use [Fish](http://fish.sh/) if that matters.

here is a screencapture:
https://gfycat.com/ImpeccableFluidLabradorretriever

**Comment by bpasero** [comment] 2016-06-28 06:58
@Tyriar can you reproduce?

**Comment by Tyriar** [comment] 2016-06-28 22:43
Duplicate of https://github.com/Microsoft/vscode/issues/7684, fixed in Insiders

**Closed by Tyriar** 2016-06-28 22:43 UTC
Labels: needs more info
