### ISSUE TITLE
Dragging our webview section into the Explorer and collapsing the sections above it breaks the proper positioning in the menu

### ISSUE THREAD

**Issue by jan-supernova** [microsoft/vscode#121163] opened 2021-04-13 08:51 UTC
We are currently dealing with an issue that seems to be related to the use of webview. If we drag our section of the plugin into the left menu in Explorer tab and collapse any section above it, the positioning breaks, which causes the content of our section to overflow the rest of the content in the left menu.

<img width="493" alt="Screenshot 2021-04-13 at 10 50 37" src="https://user-images.githubusercontent.com/52071520/114525102-1b9f4a80-9c46-11eb-9a2b-7f5fcef3c8c4.png">

Changing the horizontal size of the left menu by dragging it seems to temporarily fix this positioning issue.

- VS Code Version: Version: 1.55.1.
- OS Version: macOS Big Sur 11.2.3 (20D91).

Steps to Reproduce:

1. Install the Supernova extension (`supernovaio.pulsar-vsc-extension`).
2. Drag `CURRENT DEVELOPER SESSION` section from Supernova tab anywhere into the Explorer tab.
3. Collapse any section that is above the `CURRENT DEVELOPER SESSION` section.
4. The position gets broken and the section overflows the content in the Explorer tab.
5. If you change the left menu size by dragging it horizontally, the position fixes itself.

Video:

https://user-images.githubusercontent.com/52071520/114523911-0ece2700-9c45-11eb-9fd0-3bb867684484.mov

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2021-04-24 00:12
Duplicate of #110450

**Closed by mjbvz** 2021-04-24 00:12 UTC
