### ISSUE TITLE
Internal terminal connection is lost with error "Cannot read property 'children' of undefined"

### ISSUE THREAD

**Issue by laplacesdemon** [Microsoft/vscode#62503] opened 2018-11-02 20:14 UTC
- VSCode Version: Version 1.28.2 (1.28.2)
- OS Version: macOS 10.14.1 (18B58)

Steps to Reproduce:

It happens randomly. I didn't notice a specific step to reproduce the problem but following are what I usually do
1. Make sure that multiple terminal windows are open (probably 1 window will reproduce the same)
2. Have shortcuts to toggle (focus on) terminal panel and switch to the next and previous terminal window
3. While you're on the editor page use the shortcut to focus on terminal window
4. Terminal becomes unresponsive and the error on the lower right corners displays following: `Cannot read property 'children' of undefined`

Does this issue occur when all extensions are disabled?: ~~Since I don't know how to reproduce it (happens at random) it's difficult to answer this question.~~ Yes, it happened with extensions disabled as well.

**Comment by laplacesdemon** [comment] 2018-11-02 20:14
Please let me know how to get more logs for you to investigate.

**Comment by jerch** [comment] 2018-11-05 19:02
Duplicate of #60447?

@laplacesdemon Could you share the stack trace? (just grab it from devtools)

**Closed** 2018-12-03 18:56 UTC
Labels: integrated-terminal
