### ISSUE TITLE
VS Code ignores any unknown command line options instead of showing an error

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#58630] opened 2018-09-13 19:30 UTC
- VSCode Version: 1.27.2
- OS Version: Windows 10.0.17134.285 x64

Steps to Reproduce:
1. Run `code --foo bar`
2. VS Code launches successfully.

I'd expect giving unknown options to error out so as to catch typos, unsupported options, and what not. To do this we probably need to use the `unknown` option for the minimist parser at [src/vs/platform/environment/node/argv.ts](https://github.com/Microsoft/vscode/blob/dbeeecbaedaf236ccb423685a17b95ee5476fc97/src/vs/platform/environment/node/argv.ts#L16). I guess it should print an error and `process.exit(2)`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ntpttr** [comment] 2018-10-02 02:16
I'd like to give this a shot and assign the issue to myself.

**Comment by ntpttr** [comment] 2018-10-02 03:33
Pull request is available for this here: https://github.com/Microsoft/vscode/pull/59806

**Comment by bpasero** [comment] 2019-10-14 15:02
@aeschli didn't you do this?

**Comment by segevfiner** [comment] 2019-10-15 06:56
@bpasero I think it was decided not to do this because this is how vs code handles supporting Chromium's assortment of CLI flags. (Guess it doesn't have the function to strip them out after it parses them or something similar...)

**Comment by aeschli** [comment] 2019-10-21 09:31
Yes, since September we now warn if an unknown command line argument is used.
Duplicate of #78831

**Closed by aeschli** 2019-10-21 09:31 UTC
Labels: feature-request, workbench-cli
