### ISSUE TITLE
VSCode Main Window is blank

### ISSUE THREAD

**Issue by mdarefull** [Microsoft/vscode#14704] opened 2016-10-29 23:29 UTC
http://stackoverflow.com/questions/40323190/vs-code-main-window-is-blank

I hope you don't mind the fact I've referenced the question at so, my goal is to keep it updated with possible feedback from the community.

**Comment by mdarefull** [comment] 2016-10-30 16:16
I have updated the question with more details at so. I hope this may help find a solution...

**Comment by weinand** [comment] 2016-10-30 22:05
@mdarefull It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by mdarefull** [comment] 2016-10-31 02:46
@weinand I tried it and the exact same problem continues. 
The problem happens every time I open VS Code, it doesn't matter (so far) how I open it: From desktop link, opening a file, from context menu... the result is always that blank window.

Also, a comment on so suggested me a similar approach (removing .vscode folder). 
This is a fresh install, I don't have any extensions nor I have changed any preference. The only difference from a pure fresh install, is that I had a previous version (located inside my user folder) that I manually deleted  the folder (because I missed the installed entry) after I have installed this new version.

The weird thing is that I haven't found any other user with even a similar problem yet...

**Comment by mdarefull** [comment] 2016-10-31 02:51
Of course, after the first installation. I have uninstalled, reinstalled, cleaned the registry, restart the PC... basically everything that has came to my mind... and the same issue persists.

*Sometimes (but very rare), it just opens normally, but still shows several unresponsiveness issues, like when I clicked the user preferences, it took way too long to show them. 
Other times (rare too), after a long wait (from several minutes to several hours) after opened it, it shows the normal window.

Also, it seems that one of the process it opens (probably a very important one because killing it, terminates the main window and close the program), is eating all the CPU (but not the disk nor the network)... maybe some kind of infinite loop?

**Comment by mdarefull** [comment] 2016-10-31 03:02
Also, just to be sure... does VS Code depends on any Windows service? I have the bad habits (sometimes out of necessity) to disable some of them that I'm not using at the moment and it has caused me problems before with applications that needed them but didn't complaint about them being disabled.

**Comment by eyalsk** [comment] 2016-10-31 05:30
@mdarefull Just a thought but you can download the same version of Electron that VSCode uses and see whether it happens there too.

To know the Electron version go to VSCode >> Help >> About >> Shell.

**Comment by bpasero** [comment] 2016-10-31 09:43
@mdarefull Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by mdarefull** [comment] 2016-10-31 19:22
Thanks everyone to the help provided. I will do everything in my hand to pass the checklist and check all the other advice provided. Also, I will install it on other PCs to see if the problem reproduces.

Sadly, this seems that will take a lot of effort, so I can't promise to be quick. 
Let's hope we can find the cause of the problem and that you will be able to fix it so everyone can enjoy a better VS Code.

Go Vs Code and Go Microsoft! :)

**Comment by mdarefull** [comment] 2016-11-04 05:11
@bpasero I haven't had any time to perform the steps yet, anyway, one of them called up for my attention , the one about the previous stable version.
I've uninstalled this version (1.6.1) and installed version (1.5.3). It runs OK. 
I opened it 6 times, always the same similar behavior: 4 process, one of them with high CPU usage at the beggining, stoping eating the CPU right after the main window initializes (goes out from blank state).

I uninstalled it and installed 1.6.1 back. Same issue. I opened it around 10 times, always similar behavior:
4 process, one of them with high CPU usage AT ALL TIME.
Only 2 times the behavior was different:
1- Right after restarting the PC, it opened correctly, anyway, had 6 process running, one of them continued with the High CPU usage at all time, and begins with high disk consumption for a few seconds.
*Also, I'm pretty sure all the times it has started correctly, it begun with high disk consumption for a few seconds.
2- One time, in between the tests, only 2 processes were running, the cpu-eater among them and the VS Code window didn't appeared. After several seconds, the remaining 2 processes started, and the window appeared, anyway, it sill blank.

*Maybe these data is gibberish, maybe it gives an insight on what may be happening. At least, I'm pretty confident about 2 things now.
1 - The problem isn't directly related to my PC but to VS Code, the bottom line, to something that VS Code don't like about my PC.
2 - The problem is in the current version of VS Code ONLY.

I hope to have time soon, in order to properly perform all the steps on the check-list. Please, if you have any update, notify me.

**Comment by mdarefull** [comment] 2016-11-04 05:14
For 1.6.1, the "blank scenarios", memory consumption seemed normal among the 4 processes, averaging 13-15 Mb.
Disk usage was null.
Network was disconnected.
The only "Program Manager" stats that worries me, is the all-time CPU usage of one of the process.

**Comment by bpasero** [comment] 2016-11-04 05:14
@mdarefull are you running Code in a VM?

**Comment by mdarefull** [comment] 2016-11-04 18:36
@bpasero Of course not! I would have mentioned it otherwise. I consider my laptop and its settings to be common, nothing out of the ordinary.

BTW, I made a small mistake, for the version 1.5.3, 7 to 6 process are running, not 4.
Initially, 4 process are running, similar to the 1.6.1 version, with one of them "eating" a lot of CPU. The difference is that the program initializes (main window goes out from the "blank" state), when the "eater" process stops eating CPU and the other 2-3 process starts.

It seems, in the 1.6.1 version, that for some reason, when I open VS Code, 2 processes are created (one of them the eater one) and it starts consuming a lot of CPU, almost immediately, other 2 processes start and then is when the VS Code Main Window appears. At this point, is where version 1.6.1 behaves different from version 1.5.3, when the eater process stops consuming all the CPU, the other 2 processes (or 3) start and the different sections of the window appear (the bar on the left with the explorer, search git,... buttons, the empty untitled doccument, etc...).
This last step, never happens (almost never) on version 1.6.1.

*Even for the rare cases where all the process start at version 1.6.1 and I can see all the different sections on the main window. The "eater" process still consuming all the CPU (it never ends) and some windows malfunction (never opens or have a huge latency), like Preferences/... etc

**Comment by bpasero** [comment] 2016-11-05 06:55
@mdarefull can we try to find out the command line arguments of the high CPU process?

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by bpasero** [comment] 2016-11-16 18:07
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-11-16 18:07 UTC
Labels: freeze-slow-crash, needs more info
