### ISSUE TITLE
Can no longer format code on save

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#71102] opened 2019-03-25 15:50 UTC
Issue Type: <b>Bug</b>

This is not working for me in Version 1.33.0-insider (2019-03-25T06:06:37.427Z)

Saving TS or SCSS file result in no formatting being applied.  In SCSS, for example, saving a file results in these 2 errors being flagged by Stylelint (they used to be "cleaned up") on save:
<img width="604" alt="Screen Shot 2019-03-25 at 11 45 19 AM" src="https://user-images.githubusercontent.com/835148/54933731-96785a00-4ef3-11e9-8bad-4c78629d569d.png">

I can invoke "format document" manually.

In Typescript, I'll get a style warning like this:
<img width="437" alt="Screen Shot 2019-03-25 at 11 46 51 AM" src="https://user-images.githubusercontent.com/835148/54933915-f4a53d00-4ef3-11e9-86f1-865589c740e6.png">

And saving does not fix it.  If I manually invoke "format document", I see this  **every time**
<img width="665" alt="Screen Shot 2019-03-25 at 11 49 39 AM" src="https://user-images.githubusercontent.com/835148/54933979-16062900-4ef4-11e9-9b12-422a941b6255.png">

If I choose Prettier, it formats the code.  But, as I said, format on save does not work after that and every manual format I get asked which formatter to use. (note, this happens no matter which I choose).

VS Code version: Code - Insiders 1.33.0-insider (5688d00dd592a165530a82945c4ade4dad6b01e7, 2019-03-25T06:15:09.139Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|-psn_0_1469802847|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgo|ajh|0.1.0
Bookmarks|ale|10.3.0
project-manager|ale|10.4.0
turbo-console-log|Cha|1.2.17
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
vsc-material-theme-icons|equ|0.12.0
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.13.2
svg|joc|0.1.4
ecdc|mit|1.0.5
HTMLHint|mka|0.6.0
theme-monokai-pro-vscode|mon|1.1.12
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-html-scss|P-d|0.0.42
vscode-versionlens|pfl|0.22.0
polacode|pnp|0.2.2
quicktype|qui|12.0.46
LiveServer|rit|5.5.1
code-settings-sync|Sha|3.2.7
stylelint|shi|0.48.0
rewrap|stk|1.9.1
ayu|tea|0.18.0
vscode-npm-scripts|tra|0.2.1
sort-lines|Tyr|1.8.0
vscode-terminal-here|Tyr|0.1.1
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.2.0

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment] 2019-03-26 08:15
/duplicate of https://github.com/Microsoft/vscode/issues/41882#issuecomment-476285944

**Closed** 2019-03-26 08:15 UTC
Labels: *duplicate
