### ISSUE TITLE
Render whitespaces only when text is selected

### ISSUE THREAD

**Issue by raztd** [Microsoft/vscode#15578] opened 2016-11-16 17:10 UTC
I would like an option to render whitespaces only when text is selected.
Like the default behavior in SublimeText 3

![ws](https://cloud.githubusercontent.com/assets/6805609/20357351/49afa740-ac30-11e6-98f6-aa622967290b.png)

**Comment by ramya-rao-a** [comment] 2016-11-16 18:54
Do you mean the indent guides?

![image](https://cloud.githubusercontent.com/assets/16890566/20361078/193a1360-abeb-11e6-8c9c-4cd4240b9958.png)

**Comment by raztd** [comment] 2016-11-16 20:41
Yes. In VSCode they always appear when "editor.renderWhitespace" is set to "boundary" or "all"

**Comment by Hurtak** [comment] 2016-11-17 11:03
Probably duplicate of https://github.com/Microsoft/vscode/issues/1477

**Comment by ramya-rao-a** [comment] 2016-11-17 18:14
Thanks @Hurtak !

Closing as duplicate of #1477

@raztd Can you upvote #1477 ?

**Closed by ramya-rao-a** 2016-11-17 18:14 UTC
Labels: editor
