### ISSUE TITLE
Go to Definition does not work for Javascript object methods added dynamically.

### ISSUE THREAD

**Issue by danien** [Microsoft/vscode#18248] opened 2017-01-07 04:57 UTC
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2, Windows 10

Steps to Reproduce:

1. Copy the code below into a .js file and open it in VSCode.
2. Hover over method2 to see that it only shows "any" and Go to Definition, Peek Definition, Find all References do not work. It also does not appear in the definition of the "bob" object when hovering over it. However, it does appear in autocomplete.

```
// A simple object constructor function.
function Person() {
    this.method1 = function() {}
}
var bob = new Person();

// Intellisense appears to work for a predefined object method.
// Hovering over the method shows the correct function signature: "(property) Person.method1: () => void".
// Go to Definition, Peek Definition, Find all References work just fine.
// Appears correctly in auto complete.
bob.method1();

// Add an object method dynamically.
// Intellisense appears to work only partially for a dynamically added object method.
// Hovering over the method just shows "any".
// Go to Definition, Peek Definition, Find all References DO NOT work.
// BUT it does appear correctly in auto complete.
bob.method2 = function() {}
bob.method2();

// Add a prototype method dynamically.
// Hovering over the method shows the correct function signature: "(property) Person.method3: () => void".
// Go to Definition, Peek Definition, Find all References work just fine.
// Appears correctly in auto complete.
Person.prototype.method3 = function() {}
bob.method3();
```

**Comment by waderyan** [comment] 2017-01-09 16:27
@danien thank you for opening this issue. 

@bowdenk7 this is an expando limitation correct? 

`method2` is showing for auto complete but only as word completion:

![image](https://cloud.githubusercontent.com/assets/2449568/21773861/730bcfda-d645-11e6-805d-e3b5a8cae943.png)

**Comment by mjbvz** [comment] 2017-01-09 19:44
I believe this is being tracked by https://github.com/Microsoft/TypeScript/issues/10868 on the TS side

Closing since the issue is upstream

**Closed by mjbvz** 2017-01-09 19:44 UTC
Labels: intellisense, intellisense-expando, javascript, upstream
