### ISSUE TITLE
Select multiple tabs via shift key

### ISSUE THREAD

**Issue by mayafrog** [microsoft/vscode#125333] opened 2021-06-02 20:32 UTC
Hi,

I am reopening this as the previous feature requests did not receive enough attention to be put into the backlog.

I think the addition of the feature of being able to select multiple tabs, and then moving them as a group to another editor or right clicking for a context menu to close / move to another editor will significantly help myself, and many other's workflow. Basically all modern browsers have this feature now, and I think its about time that Visual Studio Code gets it too.

Thankyou very much!

**Comment by IllusionMH** [comment] 2021-06-02 22:21
/duplicate of #119327

Upvote that issue and if there are some usecases that are not mentioned in that issue - leave a comment there.

**Closed** 2021-06-02 22:22 UTC
Labels: *duplicate
