### ISSUE TITLE
Can't detect workspace settings change (settings.json)

### ISSUE THREAD

**Issue by cimfalab** [Microsoft/vscode#58409] opened 2018-09-11 06:13 UTC
I have developed a VS Code extension.
And I had a code for listening the user/workspace settings change like:
- vscode.workspace.onDidChangeConfiguration
- IConnection#onDidChangeConfiguration

But the change event of workspace setting is not be fired. (VS Code 1.27.0)
- If I change the settings in the new Settings editor (UI), it is fired. (both user and workspace)
- But if I change the array-typed settings in the settings.json, it is not fired. But user settings change is fired.

Thanks.

**Comment by sandy081** [comment] 2018-09-11 13:34
@cimfalab Not sure if I understand, we have a single event for any configuration change. What do you mean by `it is not fired. But user settings change is fired` ?

**Comment by cimfalab** [comment] 2018-09-11 14:40
@sandy081 a code snippet for the change listener: https://github.com/deepscan/vscode-deepscan/blob/5ec7012cc098dcde6707e90580e7ecec1186b296/deepscan-server/src/server.ts#L157

1. Edit and save USER settings in UI Settings editor
2. My listener (onDidChangeConfiguration) is called

3. Edit and save WORKSPACE settings in UI Settings editor
4. My listener is called

5. Edit and save USER settings in settings.json (after clicking 'Edit in settings.json' in UI Settings editor)
6. My listener is called

7. Edit and save WORKSPACE settings in settings.json (after clicking 'Edit in settings.json' in UI Settings editor)
8. My listener is NOT called

Same with vscode.workspace.onDidChangeConfiguration().

Please let me know if you want to have further information :)

**Comment by cimfalab** [comment] 2018-09-12 15:47
It's an array type like:
`"deepscan.ignoreRules": ["NULL_POINTER"]`

In the above 5 ~ 8 steps, I edited above setting in the settings.json. (Seems UI settings editor does not support direct editing of an array type)
But for the WORKSPACE settings, the listener was not called after saving the setting.

**Comment by sandy081** [comment] 2018-09-13 10:09
@cimfalab I am not able to reproduce it, I created a sample extension that listens to configuration changes and notifies if there is a change to `terminal.integrated.commandsToSkipShell` setting (which is of array type)

```ts
vscode.workspace.onDidChangeConfiguration(e => {
        if (e.affectsConfiguration('terminal.integrated.commandsToSkipShell')) {
            vscode.window.showInformationMessage('Updated');
        }
    });
```

Please see the attached gif, I am being notified when the setting is changed in user and workspace settings


![kapture 2018-09-13 at 12 07 52](https://user-images.githubusercontent.com/10746682/45482218-b6151580-b74d-11e8-96b4-12891418a3cf.gif)

**Comment by cimfalab** [comment] 2018-09-13 10:56
@sandy081 Thank you for your test!
I attached a gif (sorry for low quality) below:
I logged in vscode.workspace.onDidChangeConfiguration and IConnection#onDidChangeConfiguration.

When I edit a value of array in user settings, two events are logged.
But when I edit a value of array in workspace settings, no events are logged.

Oh! I found a special case for me.
I am using VS Code on Windows but my workspace is the network folder linked with Linux via samba.
When I test with another workspace on my local Windows, workspace settings also get notified!
So IMHO, seems like an issue capturing the file system change event on samba/Linux in VS Code.
How do you think and is there a way to handle it?

![test](https://user-images.githubusercontent.com/762690/45483809-0069b700-b78d-11e8-9af1-ac697efa40dd.gif)

**Comment by sandy081** [comment] 2018-09-13 11:05
assigning @bpasero for file system change events

**Comment by bpasero** [comment] 2018-09-13 11:09
There are duplicate issues labeled "file-watcher" around missing events for SAMBA shared. Closing.

**Closed by bpasero** 2018-09-13 11:09 UTC
Labels: needs more info
