### ISSUE TITLE
ElementaryOS: background artifacts

### ISSUE THREAD

**Issue by Caranell** [microsoft/vscode#85789] opened 2019-11-29 01:42 UTC
I have a bug with background colours in editor, similar to #48043 (screenshots attached). I'm facing it in both stable and insiders build, --disable-extensions doesnt help.
![Screenshot from 2019-11-29 06-25-21](https://user-images.githubusercontent.com/9637757/69837942-0903bb80-1273-11ea-8863-933355d1627e.png)
![Screenshot from 2019-11-29 06-30-26](https://user-images.githubusercontent.com/9637757/69837943-0903bb80-1273-11ea-9983-87f039b65d70.png)

- VSCode Version: **1.40.2 and 1.41.0-insider**
- OS Version: **elementary OS 5.0 Juno x86_64**

Steps to Reproduce:

1. Launch vscode

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by IllusionMH** [comment] 2019-11-29 10:54
Can you try to run VS Code with GPU disabled `code --disable-gpu`?

Like duplicate of #84860

See https://github.com/microsoft/vscode/issues/84992#issuecomment-555175745 for instruction to permanently set this runtime argument if `--disable-gpu` helps

**Closed** 2019-12-02 03:37 UTC
Labels: *duplicate, gpu, linux
