### ISSUE TITLE
Git: git@gitlab.com: Permission Denied (publickey) when I press "synchronize changes" button

### ISSUE THREAD

**Issue by ChristianOConnor** [microsoft/vscode#94413] opened 2020-04-03 21:13 UTC
- VSCode Version: 1.43.2
- OS Version: Windows 10 Pro 1909

Steps to Reproduce:

1. Use windows and cmder and have the default terminal set to cmder's bash term. Then have a password protected ~/.ssh/id_ed25519 ssh key file.

Here is my ~/.ssh/config file although I've tried almost every possible setting for this file already.

Host gitlab.com
  HostName gitlab.com
  User git
  IdentityFile ~/.ssh/id_ed25519

2. I have been working on fixing this for 2 entire days now. No matter how I set this up it always says "Git: git@gitlab.com: Permission Denied (publickey)" when I press the synchronize changes button in the lower left corner. I have tried everything including making sure "remote.SSH.showLoginTerminal": is set to "true." and doing almost every possible configuration of ~/.ssh/config. When I run "git pull" or "git push" from the terminal it prompts me for the password to my keyfile and I type the password and it works fine. For some reason whenever I hit that synchronize changes button I get the same error "Git: git@gitlab.com: Permission Denied (publickey)."

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ret394** [comment] 2020-04-03 21:35
> Does this issue occur when all extensions are disabled?: Yes/No

which is it?

**Comment by ChristianOConnor** [comment] 2020-04-03 21:40
> > Does this issue occur when all extensions are disabled?: Yes/No
> 
> which is it?

I just tried disable all extensions and I still get the same error. So "Yes" disabling extensions still gives me the same error.

**Comment by alarr46** [comment] 2020-04-04 13:20
It looks like a duplicate of #13680 : you can find some workarounds there.
I think the easiest way is to start a `ssh-agent` in your terminal, then to start code from the same terminal.

**Comment by joaomoreno** [comment] 2020-04-06 08:18
#13680

**Closed by joaomoreno** 2020-04-06 08:18 UTC
