### ISSUE TITLE
Themeing for editor squiggles background

### ISSUE THREAD

**Issue by stevermeister** [microsoft/vscode#16204] opened 2016-11-29 08:35 UTC
I would like to have custom highlight for errors:
![rxzsp](https://cloud.githubusercontent.com/assets/1526680/20702181/169fa9cc-b617-11e6-9ada-954bb2a9c49f.png)

for example such an aggressive  one:
<img width="150" alt="yahve" src="https://cloud.githubusercontent.com/assets/1526680/20702202/28c9035a-b617-11e6-8003-abc735ae4f7b.png">

Started discussion on [stackoverflow](http://stackoverflow.com/q/40697223/274500) and found that for now VSCode does not have such option.

**Comment by smuuf** [comment] 2016-12-22 23:13
***Please.***

**Comment by pierredewilde** [comment] 2017-02-03 09:10
Green squiggles used for warning messages are hardly visible with dark color themes.

**Comment by davnicwil** [comment] 2017-02-06 09:51
I posted a workaround (hack) on the [stackoverflow thread here](http://stackoverflow.com/a/41039209/1082449) - it works, but I am having to reapply this on every update, and it makes VS Code report itself as corrupted, both of which are pretty inconvenient.

This is a significant accessibility hurdle for colorblind people using VS code. I think any solution to making this configurable should be as low-friction as possible.

For example, please consider just allowing raw css to be specified for the error style, on top of an existing theme, similarly to how this workaround does. If these styles are deeply integrated into the theming and a completely new theme has to be created to change them, this will make it more of a hassle than necessary to tweak the styles, and the themes will not necessarily even be very shareable since different people will want/need slightly different tweaks.

Thanks for all the great work!

**Comment by nixterrimus** [comment] 2017-03-11 00:13
I'd love to have the ability to highlight a whole line when there's an error.  It's so easy to miss an error when scanning through a file.

**Comment by aicccia** [comment] 2017-04-03 09:37
Yes, please add this.

**Comment by gbritting** [comment] 2017-04-19 02:40
Agree with davnicwil "This is a significant accessibility hurdle for colorblind people using VS code."

**Comment by lanegoolsby** [comment] 2017-04-23 04:43
Color blind person here. **_PLEASE_** make this change. The current color is near impossible to see for some of us.

**Comment by bpasero** [comment] 2017-05-21 06:53
Closing as duplicate of https://github.com/Microsoft/vscode/issues/9819

**Comment by davnicwil** [comment] 2017-07-12 13:34
@bpasero this issue isn't really a duplicate of #9819, in my opinion. Changing the color of the squiggles is an improvement, and a welcome change in v1.12, but I also want to add a background highlight to the error. Will there be more properties coming which allow for this?

**Comment by thomstark** [comment] 2018-01-27 21:55
I'd like to be able to put a red background behind the Line Number on the left as well. It's easy to miss an error that is one character long, but if the line number takes a red background, that's impossible to miss.

**Comment by LostNCG** [comment] 2018-04-28 07:06
agree with @thomstark and **Please**

**Comment by tomholub** [comment] 2018-06-11 13:53
I absolutely skip errors all the time, even when I know it's somewhere on the page - just cannot find it.

**Comment by methodbox** [comment] 2019-05-18 00:47
> I absolutely skip errors all the time, even when I know it's somewhere on the page - just cannot find it.

I usually have to use the marker on the scroll bar on the right (red line) to actually find it; it blends in too much.

MS - just make this configurable, like:

```js
{
    "editer.lintConfig": {
        "lintStyle": "x"  //  An alternate style for the squiggle, maybe "squiggle, X's, asterisk, question marks
        "width":  15, //  line width
        "height": 10, //  height of the error design from point to point
        "foreground": "#f50000",
        "background": "rgba(255,105,180, 0.5)"
    }
}
```
It would be nice if we had some real hooks to write extensions for this. This is actually something I'd rather be able to target with an extension vs. just theming. It would be an extension worth the time of creating 🥇

**Comment by methodbox** [comment] 2019-05-19 16:30
You guys have got to checkout this VS Code extension. This is better than I could have imagined to solve this issue:

https://marketplace.visualstudio.com/items?itemName=PhilHindle.errorlens

It's beautiful. Here's an example on a TypeScript Express server I where I have a ton of flags from TS:

![Image of Error Lens](https://ibb.co/bbNWyPL)

**Closed** 2020-11-09 20:58 UTC
Labels: editor-theming, feature-request, themes

**Comment by misolori** [comment] 2020-11-09 21:00
You can now use the following color tokens to highlight the background color of errors/warnings/info in the editor:

- `editorInfo.background`
- `editorWarning.background`
- `editorError.background`

![image](https://user-images.githubusercontent.com/35271042/98583704-a9cb6b00-2279-11eb-9d8b-0a57392f7e7f.png)

**Comment by davnicwil** [comment] 2020-11-10 08:52
@misolori awesome work, thanks for this change!
