### ISSUE TITLE
App colors have shifted slightly in 1.5.3

### ISSUE THREAD

**Issue by TheWox** [microsoft/vscode#116080] opened 2021-02-08 06:26 UTC
- VSCode Version: 1.53
- OS Version: Windows 10

Steps to Reproduce:

1. Preferably use a highly color accurate monitor, and be sure your perception of colors isn't physically impaired in any way.
2. Open a previous version of VS Code eg: 1.52.1. Take a screenshot and paste into an image editing app. 
3. Install and open VS Code 1.53, take a screenshot and paste over the previous screenshot in an image editing app.  
4.  Flick between the two screenshots and notice how the top left VS Code icon is now a lot more desaturated in 1.53. 
5. Look further carefully and see that in fact, all the colours in the app window are now slightly more desturatated and slightly lighter and more dull. 
6. Use a point sample eyedropper tool to check the color values between the images if in doubt, and see how the hex values do not match for the same pixel.

Does this issue occur when all extensions are disabled?: Yes

**Comment by TheWox** [comment] 2021-02-08 06:41
In the attached image I have shown the 1.52.1 on the left and 1.53 on the right. I am using a custom theme in the screenshots (Monokai Pro) however the shifted colors persist regardless of theme used or all extensions being enabled or not.

![Example](https://user-images.githubusercontent.com/26923521/107184410-2c82d400-69e9-11eb-8689-7bd8be140494.png)

**Comment by gjsjohnmurray** [comment] 2021-02-08 13:24
Could this be a consequence of Electron 11?

**Comment by misolori** [comment] 2021-02-08 19:13
@deepak1556 nothing has changed on the theming side, guessing electron related

**Comment by bpasero** [comment] 2021-02-09 10:28
This was reported earlier already: https://github.com/microsoft/vscode/issues/110807

**Comment by rzhao271** [comment] 2021-02-09 20:17
@TheWox I can confirm that in your screenshot, the colours are different, even down to the subpixel rendering.
However, I cannot reproduce the issue locally:

![coldiffnone](https://user-images.githubusercontent.com/7199958/107422286-af7e5a00-6acf-11eb-915f-482907b41286.png)

I'm on a Windows system:
```
Windows 10 Entreprise 20H2 19042.746
Windows Feature Experience Pack 120.2212.551.0
```

And I'm on an sRGB monitor.

Wondering what your settings are?

**Comment by TheWox** [comment] 2021-02-09 20:35
Hey @rzhao271 thanks for following up. I get the dull color shift on both my xps15 (9560) laptop, and on my desktop pc - both of which are affected regardless of any extensions being enabled or not.

My laptop Windows version is:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041

I don't have access to the desktop at the moment, can post that soon as I have it.

**Comment by joaomoreno** [comment] 2021-02-10 08:37
Duplicate of https://github.com/microsoft/vscode/issues/110807

**Closed by joaomoreno** 2021-02-10 08:37 UTC
Labels: electron-11-update
