### ISSUE TITLE
All js completion items has `score:8` 

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#102935] opened 2020-07-20 09:43 UTC
Steps to Reproduce:

1. Open any js files, trigger completion after `PropTypes`:
2. enter `cmd+?`, show the internal completion details:
![image](https://user-images.githubusercontent.com/8640918/87923557-42ae5e80-cab0-11ea-8ecc-735b854b56f7.png)

As you can see in the pic, all completion candidates have `score:8`, which leads all results from my custom extension rank last because "no prefix"
![image](https://user-images.githubusercontent.com/8640918/87923713-7be6ce80-cab0-11ea-91a5-0eb296f55d80.png)

The question is, in this situation, the prefix used to calculate the similarity score can be "." and "no prefix" simultaneously for different extension.

Does this issue occur when all extensions are disabled?: No, with my own completion extension enabled

**Comment by HaoboGu** [comment] 2020-07-20 10:07
Another bad case:

![image](https://user-images.githubusercontent.com/8640918/87926092-c7e74280-cab3-11ea-9017-47c965aa99ca.png)

---
![image](https://user-images.githubusercontent.com/8640918/87926125-d33a6e00-cab3-11ea-8ac8-ddd803e240b0.png)

**Comment by gjsjohnmurray** [comment] 2020-07-20 14:10
When a completion item is open, press Ctrl/Cmd+? to toggle this diagnostic mode.

**Comment by mjbvz** [comment] 2020-07-20 16:41
Duplicate of #101757. See that issues for information about getting out of explain mode

/cc @jrieken

**Comment by mjbvz** [comment] 2020-07-20 16:41
Oh actually

**Comment by HaoboGu** [comment] 2020-07-22 06:26
@jrieken can you please take a look?

**Comment by jrieken** [comment] 2020-08-10 10:24
> The question is, in this situation, the prefix used to calculate the similarity score can be "." and "no prefix" simultaneously for different extension.

Yes - items that select a prefix get a score based on the prefix they define. Items that don't select a prefix don't get a score. This generally works well but can be unfair towards shorter or no prefixes.

**Closed** 2020-08-10 10:24 UTC
Labels: *question, suggest

**Comment by HaoboGu** [comment] 2020-08-13 02:31
> Yes - items that select a prefix get a score based on the prefix they define. Items that don't select a prefix don't get a score. This generally works well but can be unfair towards shorter or no prefixes.

Does the prefix is defined in `filterText`? I've set the `filterText` but it doesn't work

**Comment by jrieken** [comment] 2020-08-13 07:07
The prefix is implicitly defined by the text that `range` property selects
