### ISSUE TITLE
Feature Request - Project-level extensions and snippets

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#8102] opened 2016-06-24 12:48 UTC
- VSCode Version: all
- OS Version: all

We have a custom set of snippets written per-project and would like to include them in the project repo, like our launch.json, tasks.json. Right now we just include the json file and the dev has to copy+paste it into his user snippets, but the snippets are particular to a project, not to all projects.

Also it would be great to have a way to define what extensions a developer should have installed to work on the project. We use several code quality and styling plugins to enforce our custom rules and it would be nice if there was a project definition file to suggest installation of the extensions we define.

**Comment by dbaeumer** [comment] 2016-06-25 19:51
@aeschli can you comment on the snippet request. Can't we define snippets on a workspace folder level.

@chrisdias @seanmcbreen for the workspace folder extension request.

**Comment by seanmcbreen** [comment] 2016-06-29 00:40
A workspace config for extensions is something we are definitely thinking about.

**Comment by rebornix** [comment] 2016-08-08 09:21
I was writing test cases for extensions and those cases share similar format then I thought I should put a snippet in project settings. But unfortunately I found that's not possible right now.

This can be a good extension as well if we expose Snippet management through API.

**Comment by maxdeviant** [comment] 2016-08-19 19:46
I would love to see workspace-level snippets.

**Comment by mpj** [comment] 2016-11-18 09:42
This would indeed be amazing. In fact, I found it really unintuitive that there is marketplace-level snippets, but not project level. Took me quite a while to figure out that it wasn't possible. :P

**Comment by rebornix** [comment] 2016-12-17 18:31
Just for your information, with the new API we added in our latest release 1.8, project/workspace level snippets is now possible. You can use this extension https://marketplace.visualstudio.com/items?itemName=rebornix.project-snippets to share and insert snippets across projects.

**Comment by jdfwarrior** [comment] 2017-03-23 18:17
Does this plugin still work? Unless I'm doing something wrong, it doesn't seem to be doing anything and there is zero information on it (in the README). I created a snippets folder in .vscode and then created a language specified snippets file within there but that file isn't loaded. I can't use the snippets there.

**Comment by rebornix** [comment] 2017-03-23 18:21
@jdfwarrior do you mind sharing me part of your snippet then I can have a good reproduce and see what's blocking you :( I know it's not a reasonable request but look forward to your reply.

**Comment by jdfwarrior** [comment] 2017-03-23 18:25
@rebornix This is all I currently have while testing..

{
  "Print to console": {
    "prefix": "log",
    "body": [
      "console.log('$1');",
      "$2"
    ],
    "description": "Log output to console"
  },

  "Angular Controller": {
    "prefix": "controller",
    "body": [
      "export default class $1 {",
      "  constructor( $2 ) {",
      "    $0",
      "  }",
      "}"
    ],
    "description": "Create new Angular controller"
  }
}

Is there any kind of configuration that needs to be done to make this work?

**Comment by rebornix** [comment] 2017-03-23 18:26
@jdfwarrior the only thing I'm worried about is tab or space , maybe it's similar to https://github.com/rebornix/vscode-project-snippet/issues/4 as your snippet looks reasonable. I'll reach out to you real quick after fixing that.

**Comment by rebornix** [comment] 2017-03-30 18:52
@jdfwarrior I've updated the extension. Please let me know if it fixes your problem.

**Comment by larssb** [comment] 2017-06-29 20:25
@rebornix seems to work after your March 30th update. Thanks.

**Comment by yeluoqiuzhi** [comment] 2017-07-26 03:43
@rebornix  thanks.

**Comment by mattblang** [comment] 2017-12-31 19:17
Just an FYI for anyone who finds this ticket, you can now specify [recommended extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) for the workspace.

**Comment by antoniusostermann** [comment] 2018-02-05 16:57
+1

**Comment by imrvelj** [comment] 2018-02-09 14:42
+1

**Comment by RPDeshaies** [comment] 2018-03-01 16:34
@rebornix I've been using your extension for workspace snippets for quite some time now (thanks BTW) and I was wondering if there was any plan in the timeline to include this behavior directly inside VSCode ?

**Comment by rebornix** [comment] 2018-03-06 04:38
@RPDeshaies I kind of like how it works as an extension by leveraging a couple VSCode API. It's up to @jrieken if we want to move similar feature to Code core.

**Comment by Domvel** [comment] 2018-03-15 16:00
It already works (with an extension)
https://marketplace.visualstudio.com/items?itemName=rebornix.project-snippets
Add a folder `snippets` in your project path `.vscode` and create a json for the langauge you want. e.g. path: `.vscode\snippets\javascript.json`.

**Comment by Seblor** [comment] 2018-04-18 09:40
Any update on a native solution ?

**Comment by lloydjatkinson** [comment] 2018-05-18 10:03
Any updates? Would be very useful.

**Comment by fbehrens** [comment] 2018-08-22 13:03
I stumbled on this and wrongfully expected that a `*.code-snippet` file in `.vscode` folder would be considered.  is that planned ?

**Comment by egamma** [comment] 2018-09-11 08:56
September issue cleansing. 

This is well covered by an extension and we have no plans to bundle this extension with VS Code.

**Comment by egamma** [comment] 2018-09-11 20:31
Reopening... this is not out of scope according to our guidelines https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests

**Comment by jrieken** [comment] 2018-09-21 09:42
Good news: Current [Insiders](https://code.visualstudio.com/insiders/) has a rough version of this already and with *next* [Insiders](https://code.visualstudio.com/insiders/) this will be working. This is how:

* you can put snippets in the `.vscode`-folder of your workspace (but not inside subfolders of that)
* only snippet files with the `.code-snippets` extension are supported
* the insert snippet command and completions show that a snippet is a workspace snippet
* with the configure snippet command you can create workspace snippets

<img width="1224" alt="screen shot 2018-09-21 at 11 38 56" src="https://user-images.githubusercontent.com/1794099/45873543-09611680-bd93-11e8-994b-5ee14485d22f.png">

**Closed** 2018-09-21 13:27 UTC
Labels: feature-request, snippets

**Comment by jdforsythe** [comment] 2018-09-21 14:49
Thank you! This is why we love VS Code

**Comment by ffxsam** [comment] 2018-09-21 14:52
Thanks, team!

**Comment by jrieken** [comment] 2018-09-24 15:11
@Ash258 We are always a little scared of subfolders because there might be many, many...

**Comment by rebornix** [comment] 2018-09-24 15:38
🚀 love this feature, my extension can retire now and I don't need to fix all those issues 😆 . I'll put my name on the test item to ensure they get tested.

**Comment by rebornix** [comment] 2018-09-26 19:30
Went through https://github.com/rebornix/vscode-project-snippet/issues and test cases of [vscode-project-snippet](https://github.com/rebornix/vscode-project-snippet), didn't find any issue at all, the builtin support is solid 👍
