### ISSUE TITLE
Git gutters don't show when you Uppercase a filename

### ISSUE THREAD

**Issue by deejaybill** [Microsoft/vscode#29861] opened 2017-06-29 14:16 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|azurenodeessentials|azuresdkteam|0.2.6|
|vscode-eslint|dbaeumer|1.2.11|
|code-runner|formulahendry|0.6.24|
|beautify|HookyQR|1.1.1|
|minify|HookyQR|0.3.0|
|ftp-sync|lukasz-wronski|0.3.3|
|yo|samverschueren|0.9.3|
|vscode-wakatime|WakaTime|1.1.12|
|vsc-jsonsnippets|wmontalvo|0.1.4|;

---

Git gutter doesn't show when you Uppercase a filename (partial or full)

Steps to Reproduce:

1.Add some code to an existing repository and rename the filename with an Uppercase (in the screenshot app.js -> App.js)
2.The git gutters disappear and the Source Control tab stage the changes with the old filename (app.js instead of App.js)
3. Commit the staged changes
4. Add some code to the renamed file
5. Git gutters doesn't show again but the Working Tree looks good
6. If you rename the files as before (App.js -> app.js) the git gutters appear correctly

![img_003842-2017-06-29 14_16_14](https://user-images.githubusercontent.com/26719977/27691351-101b1720-5ce4-11e7-9b63-a32f7195fc4c.png)
![img_003843-2017-06-29 14_16_52](https://user-images.githubusercontent.com/26719977/27691353-1020fbcc-5ce4-11e7-93a4-a20d6536b508.png)
![img_003844-2017-06-29 14_17_13](https://user-images.githubusercontent.com/26719977/27691352-101ebe34-5ce4-11e7-9d66-87607145b198.png)
![img_003845-2017-06-29 14_17_58](https://user-images.githubusercontent.com/26719977/27691354-1022bac0-5ce4-11e7-9a1a-cc907a242d32.png)
![img_003846-2017-06-29 14_18_07](https://user-images.githubusercontent.com/26719977/27691355-1027515c-5ce4-11e7-95f3-43b5fb3fc9b7.png)
![img_003847-2017-06-29 14_18_56](https://user-images.githubusercontent.com/26719977/27691356-102a7260-5ce4-11e7-807e-68e78cc0784f.png)

**Comment by rianadon** [comment] 2017-07-03 01:09
It seems this is because Windows treats file case insensitively, but git's object storage treats them case sensitively. Therefore, to git only `app.js` exists, while it's `App.js` under Windows.

From what I can tell VS Code executes `git show :App.js` (feel free to correct me if I'm wrong) to retrieve the contents of the file before the modifications, and runs its own diffing internally. However since to git `App.js` doesn't exist, VS Code's diffing treats the file as a new file.

The only solution I can think of would be in the cases that `git show` fails, to query what files git knows about (through `git ls-files`), try to case-insensitively find the current filename in the output of the command, and if it is present use the git-provided filename in the `git show` command.

If no one can think of a better solution I'd be happy to write a PR for this.

**Comment by deejaybill** [comment] 2017-07-03 09:11
I know the difference between Windows and Unix based system about the filename case sensitive but git and vscode are software that run not only in Windows bus also in macOS and Linux. I think due to Windows "limitations" the only case you can't have is two files with these name: app.js and App.js but you have to handle the rename from app.js to App.js for git and the other OS.

**Comment by rianadon** [comment] 2017-07-04 05:15
I'm not sure I understand what you mean.

What I was trying to explain was that because windows treats `app.js` and `App.js` as the same file (so you can't have both as you said), git decides to ignore the rename and thinks that only `app.js` exists, while to windows an `App.js` exists and when Windows tries to query git for `App.js` git's object storage is case sensitive and believes it doesn't exist, hence unless there is a way to make the `git show` command case sensitive whatever fix this issue requires will need to query the case of the files git knows about.

As for the rename there are ways of getting git to recognize this (using `git mv` rather than the filesystem's move which will force git to recognize the rename or [making git treat files case sensitively](https://stackoverflow.com/a/17688308)). I'm not sure whether it would be a good idea for VS Code to stage files as a site effect of `git mv` or to tamper with options. However even if VS Code manages the move in a way that triggers git to recognize the rename it should still handle cases where this is done from outside VS Code.

**Comment by pcblues** [comment] 2017-07-05 10:40
Hi there. I'm new to the vscode codebase and making pull requests. I was thinking something along the lines of git mv as well. Just a quick question: I assume fixes should come with updates to the code, new tests, and maybe a change to the documentation. Should these be in separate pull requests? If so, should they all be associated with this issue? Thanks.

**Comment by BugraC** [comment] 2017-07-11 01:37
Renaming a file creates a new file and removes the old renamed file and makes the new file unstaged. For that reason, unstaged file doesn't show the git gutters. Thus, this is not related to renaming a file with uppercase. Also if you create a new file since it is not staged it doesn't show the git gutters. @joaomoreno I would like to take a look at this but I am not sure what can be done in terms of fixing the issue. Should unstaged files show git gutters?

**Comment by joaomoreno** [comment] 2017-07-11 07:50
Actually, like @BugraC, I'm not so convinced we should do anything. For git this is a simple file move, for which the disappearance of the gutter decorations makes sense. I don't think unstaged files should show gutter decorations and we should definitely not automatically stage anything.

What is interesting for me is that git continues to report the file as lowercase after the rename.

**Comment by pcblues** [comment] 2017-07-11 22:05
I haven't come across a use case for renaming the case of a file where the history isn't wanted to be kept. If I change the case of a filename, it's usually a correction for style rather than a desire to create a new file. Interestingly, the file extensions/git/src/git.ts doesn't include mv in its available commands. If you manually do a git mv on a file after changing the case in vscode, it behaves more how I would want it to in vscode. YMMV.

**Comment by joaomoreno** [comment] 2017-07-12 05:50
> Interestingly, the file extensions/git/src/git.ts doesn't include mv in its available commands. 

Code doesn't need to. The equivalent of `git mv` is achieved by renaming the file and staging the two changes (add, delete). It will appear as a move in the index. That is exactly what you would get with `git mv`: the change is staged.

**Comment by pcblues** [comment] 2017-07-12 11:37
I ran tests to check this:  
- The problem is that on a case-insensitive file system, Code doesn't bring the file name change through to git if only the case of the name is changed.  
- Changing the case of a file in Code is not the same as  _git mv_ on a case-insensitive file system.  
- When you push the changes to a remote repository and clone the repository to a case-sensitive file system, the original case of the file is created. 
- This is going to cause problems eventually. If we made the rename function in Code also call a _git mv_ when the file name change is only different by case, then the record of the case change in the filename will be saved to the repository correctly even if it is done on a case-insensitive file system. (I know this issue is about gutters, but I think it has exposed a real problem in keeping filenames aligned between case-insensitive and case-sensitive file systems)
- I have been looking at how best to do this, and would be happy to try to come up with a pull request if you are interested.

**Comment by joaomoreno** [comment] 2017-07-17 09:14
> The problem is that on a case-insensitive file system, Code doesn't bring the file name change through to git if only the case of the name is changed.

What happens if you rename the file in the Windows Explorer and run `git status`? You'll notice this behaviour isn't related to Code at all. It's not about Code bringing file name changes to git or otherwise.

>  If we made the rename function in Code also call a git mv when the file name change is only different by case, then the record of the case change in the filename will be saved to the repository correctly even if it is done on a case-insensitive file system.

This is a bad idea since it involves automatically staging changes.

**Comment by rianadon** [comment] 2017-07-18 17:07
I agree. Automatic staging of files would be more annoying than helpful and
once you unstage the file it turns back into delete + add operations.

I also have never run into a case where I'd want to change the case of a
filename and not want that tracked by git, and I'd presume that this would
be a fairly rare case.

However not handling untracked filename case changes is an edge case that
VS Code does not handle.

For showing git gutters on files that have been moved but not yet staged, I
wonder if VS Code could use the same algorithm that git uses to turn an add
+ delete into a move upon staging to determine the move operation, and use
that in its diffing.

>

**Comment by pcblues** [comment] 2017-07-18 22:20
OK. Off to find another issue :)

**Comment by alexkrolick** [comment] 2017-10-13 23:46
We've had issues creating files/folders in VSCode on Mac, then building the app on a Linux server. Occasionally half the files in a folder will show up in MyFolder and the rest in myfolder.

**Comment by agm1984** [comment] 2017-11-18 22:39
Here is some sample code that may be relevant here. I came across it for doing fuzzy searches:
``` javascript
const searchTerms = (!opts.caseSensitive) ? new RegExp(term, 'i') : new RegExp(term)
```

The `'i'` option makes it case insensitive.

**Comment by joaomoreno** [comment] 2018-07-06 14:47
Fixed by https://github.com/Microsoft/vscode/pull/49397

**Closed by joaomoreno** 2018-07-06 14:47 UTC
Labels: bug, git, good first issue, help wanted
