### ISSUE TITLE
Terminal lineHeight evaluated as EMs relative to terminal font-size

### ISSUE THREAD

**Issue by huot25** [Microsoft/vscode#10195] opened 2016-08-05 13:53 UTC
- VSCode Version: 1.4
- OS Version: Windows 10 64-Bit

This was working 1.3. I just updated and happen to notice very large spacing between my terminal lines. Setting "editor.lineheight" still evaluates the line height property as points and not EMs.

Steps to Reproduce:
1.  Set "terminal.integrated.lineHeight": 20 ( I also have terminal font size set to 12).
2.  Open terminal panel and execute some commands. 

You should see large spacing between terminal output lines in the panel.

**Comment by huot25** [comment] 2016-08-05 14:10
After additional testing, it looks like the property now only evaluates the integer value. If you supply 1.5 (trying to set the line height to be 1.5 the current font size) only the 1 is evaluated. Wanted to provide any extra info I can to help reproduce and identify the issue.

**Comment by outcoldman** [comment] 2016-09-10 03:05
Another issue is that `editor.lineHeight` expects pixels, and `terminal.integrated.lineHeight` expects EM. Does not seem consistent.

**Comment by Tyriar** [comment] 2016-09-10 04:08
@outcoldman the inconsistency there is because having `lineHeight` be unitless seemed to be the only reliable way to ensure there were no gaps between the lines on a terminal selection. The reason `editor.lineHeight` can get away with it is because it's not using native web selection, this is planned for the terminal coming up though https://github.com/sourcelair/xterm.js/issues/207

**Comment by Tyriar** [comment] 2016-09-10 04:09
But yeah, this is as designed. It could change in the future after virtual selection but for now you multiply it against `fontSize` to get the height in `px`.

**Comment by dennisfoconnor** [comment] 2016-10-11 18:11
@Tyriar Is terminal.intergrated.lineHeight supposed to only accept integers? Shouldn't it accept decimal numbers?

**Comment by Tyriar** [comment] 2016-10-11 20:53
@dennisfoconnor that's a bug that seems to have been in for a while. Moved it to https://github.com/Microsoft/vscode/issues/13542 and pushed a fix. Thanks for the report!

**Closed** 2017-04-03 17:00 UTC
Labels: as-designed, integrated-terminal
