### ISSUE TITLE
Editing one file under two different case insensitive paths

### ISSUE THREAD

**Issue by Radranic** [microsoft/vscode#88007] opened 2020-01-02 19:42 UTC
- VSCode Version: 1.41.0
- OS Version: Windows_NT x64 10.0.18362

NOTE: Windows only because of file system case insensitivity.

Steps to Reproduce:

1. Open a folder that contains at least one sub folder with a file in it
2. Using the explorer panel, open the file from the sub folder in the editor
3. Outside of VSCode, rename the sub folder to a name that differs only by case
4. Using the explorer panel, attempt to open the file from the sub folder again
5. You now have two tabs in the editor for the same file

Expected behavior:
- You only have one tab open for the file as if the folder rename didn't happen.

Side effects that make this more serious:
- You can normally have two copies of a file open in different side by side views. But in this case VSCode doesn't seem to know that it's the same file.
- If you happen to do this and have code formatting tools installed like `gofmt` it gets very bad.
  - When you "Save All" with edits in the file, weird things happen (always bad, not consistent on how bad/what)
  - I'm assuming that this is just a symptom after things have already gone bad and probably doesn't need to be addressed, but it's probably a good reason to fix the root cause.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-01-02 20:51
Perhaps a duplicate of #12448

**Comment by Radranic** [comment] 2020-01-02 21:43
> 
> 
> Perhaps a duplicate of #12448

I should have looked more, sorry. Had been searching based on my saving causing changes in the file and missed the rather large collection.

One thing I did notice when poking at it is that the explorer panel does update the directory name and seems to reload the same way as if you changed the name inside VSCode. The reload just didn't trigger the editor tabs to reload. Not sure if this means there's a potential for an isolated fix there that can be removed once the larger problem is addressed or not.

If it's all related to the `URI.toString()` from #12448 and there's no small scale fix, then thanks for your time looking into it.

**Comment by gjsjohnmurray** [comment] 2020-01-02 21:53
@bpasero is probably best placed to decide whether to close this one as a dup.

**Comment by bpasero** [comment] 2020-01-04 15:15
I would say, this is a duplicate of https://github.com/microsoft/vscode/issues/30240 as well as https://github.com/microsoft/vscode/issues/12448. With https://github.com/microsoft/vscode/issues/30240, the file should simply reopen with the new casing and as such this issue would not show up in the first place.

**Closed** 2020-01-04 15:15 UTC
Labels: *duplicate
