### ISSUE TITLE
cannot resolve the markdown.

### ISSUE THREAD

**Issue by kaiaiz** [Microsoft/vscode#25659] opened 2017-04-29 00:25 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|vscode-icons|robertohuertasm|7.6.0|
|vim|vscodevim|0.6.20|
|Material-theme|zhuangtongfa|2.5.3|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment] 2017-04-29 09:21
@kaiaiz Can you be more specific and include some steps, explaining what you would expect to happen vs what actually happens?

**Comment by mjbvz** [comment] 2017-05-02 17:33
Closing as the issue is not clear

**Closed by mjbvz** 2017-05-02 17:33 UTC
Labels: markdown, needs more info
