### ISSUE TITLE
Debug sidebar improvements

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#58530] opened 2018-09-12 15:55 UTC
Issue Type: UI/Feature Request
This is a continuation of #58445 except it is more inline with the Submitting Bugs and Suggestion guide.

## Debug
This issue details my vision for an improved Debug sidebar. This issue focuses on the UI ASPECT:
- The sections should display some text when there is no debug session currently active, such as: `There are no active debug sessions`
- The Title area where it says `Debug` is a pure mess and looks very rushed. The Dropdown for configuration could probably receive the nice looking dropdown treatment (such as the ones in the titlebar) because it looks much more aesthetically pleasing
  - It could probably also move into its own Section named `Configuration` of the sorts, with perhaps more control over what the user wants to happen. I personally don't have much experience with this menu (only started using it recently to develop extensions in my own time) so I'll leave that idea here.
  - The Start Debug arrow can move to join with the other icons there, and perhaps be a button inside the new section too
![debug](https://user-images.githubusercontent.com/30497573/45377568-e300e580-b5f2-11e8-82f2-8a11e6d6ca1e.png)

**Comment by nealot** [comment] 2018-09-13 10:44
Seems like a duplicate of https://github.com/Microsoft/vscode/issues/56391.

**Comment by weinand** [comment] 2018-09-13 11:00
duplicate of #56391.

**Closed by weinand** 2018-09-13 11:00 UTC
Labels: debug
