### ISSUE TITLE
organizeImports remove import statements on save

### ISSUE THREAD

**Issue by rakshans1** [Microsoft/vscode#49597] opened 2018-05-10 06:15 UTC
- VSCode Version: 1.23.0
- OS Version: Ubuntu  

Steps to Reproduce:

1. Add to  Preference 
```
 "editor.codeActionsOnSave": {
        // "source.organizeImports": true
    },
```
Initial Code 
```javascript

import CourseSingle from './CourseSingle';
import Watchlist from './Watchlist';

const Views = {
  CourseSingle,
  Watchlist,
};

Object.keys(Views).map(key => {
  const view = new Views[key]();
  view.init();
  return null;
});
```
After Save 
```javascript
const Views = {
  CourseSingle,
  Watchlist,
};

Object.keys(Views).map(key => {
  const view = new Views[key]();
  view.init();
  return null;
});
```

On save it removes the import statements

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-05-10 08:29
Duplicate of #49193 

Fixed in insiders

**Closed by mjbvz** 2018-05-10 08:29 UTC
Labels: javascript
