### ISSUE TITLE
A slow startup has been detected. Profiling data attached

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#28589] opened 2017-06-13 07:21 UTC
- VSCode Version: <code>Code - Insiders 1.13.0-insider (64d532ccb681ddbef0039db1effa2949f1993214, 2017-06-01T05:14:13.922Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)</code>
- Memory (System): <code>7.84GB (2.32GB free)</code>
- Memory (Process): <code>169.19MB working set (176.35MB peak, 147.78MB private, 34.36MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|297|
|main|app.isReady => window.loadUrl()|247|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|620|
|renderer|require(workbench.main.js)|855|
|renderer|create extension host => extensions onReady()|21099|
|renderer|restore viewlet|undefined|
|renderer|restore editor view state|undefined|
|renderer|overall workbench load|NaN|
|main + renderer|start => extensions ready|23148|
|main + renderer|start => workbench ready|NaN|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\kumar\c5af_main.cpuprofile.txt`
-`C:\Users\kumar\c5af_renderer.cpuprofile.txt`
[c5af_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1070596/c5af_main.cpuprofile.txt)
[c5af_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1070597/c5af_renderer.cpuprofile.txt)

**Comment by bpasero** [comment] 2017-06-19 07:28
@jrieken looks like some of the numeric values are `undefined` / `NaN`, could that be a regression and we are not reporting correct numbers to our telemetry?

Otherwise the profile has a suspiciously long time spend waiting for the extension host to become ready. @kumarharsh how many extensions do you have installed?

**Comment by kumarharsh** [comment] 2017-06-19 13:05
@bpasero 32 as of now.

**Comment by jrieken** [comment] 2017-06-27 14:47
So, there is surely #22087 in here. It seems that extension discovery is slow but I believe that is just an artifact from bogus measurements. Looking at the problem reveals that your system is doing something outside the JS event loop. No clue what that could be...

<img width="1119" alt="screen shot 2017-06-27 at 16 46 48" src="https://user-images.githubusercontent.com/1794099/27593737-3b7c7694-5b58-11e7-98e8-7a38b7604fb2.png">

**Comment by jrieken** [comment] 2017-06-27 14:47
@kumarharsh Do you see such slow startup every time you start?

**Comment by kumarharsh** [comment] 2017-06-27 16:56
No, I only encountered it once - the time when I posted this issue. Never saw it again.

**Comment by jrieken** [comment] 2017-06-27 17:03
Ok, closing then. Let's keep an eye open but there is little we can do right now

**Closed by jrieken** 2017-06-27 17:03 UTC
Labels: insiders, needs more info, perf-profile
