### ISSUE TITLE
C++ syntax highlighting is not right

### ISSUE THREAD

**Issue by JHSeng** [microsoft/vscode#73993] opened 2019-05-20 13:16 UTC
- VSCode Version: 1.34.0
- OS Version: Manjaro 18.0.4

Steps to Reproduce:

1. I was coding like this (src: https://paste.ubuntu.com/p/dtKxDtx94M/) and the color is not right since line 29.
![Screenshot_20190520_210659](https://user-images.githubusercontent.com/31332409/58024042-e403f280-7b43-11e9-9816-8649e5a05f86.png)

2. When I change "segt[maxn<<2]" into "segt[maxn *4]" (at line 29), it became right again.
![Screenshot_20190520_210709](https://user-images.githubusercontent.com/31332409/58024085-fd0ca380-7b43-11e9-9110-ce499a3120bb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JHSeng** [comment] 2019-05-20 13:17
This bug has never been seen in older version.

**Comment by JHSeng** [comment] 2019-05-20 13:32
I added some code and found colors of some chars still right.
![Screenshot_20190520_213048](https://user-images.githubusercontent.com/31332409/58025288-b79da580-7b46-11e9-89f6-5985303e6cab.png)

**Comment by alexr00** [comment] 2019-05-21 09:26
@JHSeng I can't reproduce this. Do you have any extensions enabled?
![image](https://user-images.githubusercontent.com/38270282/58084470-40eebf80-7bbb-11e9-9fcb-295caa362960.png)

**Comment by matter123** [comment] 2019-05-21 12:55
@alexr00 This is https://github.com/jeff-hykin/cpp-textmate-grammar/issues/141 which was fixed in version v1.8.9

**Comment by alexr00** [comment] 2019-05-21 13:21
Perfect, thank you @matter123. VS Code insiders is now on 1.8.15.

**Closed by alexr00** 2019-05-21 13:21 UTC
Labels: needs more info
