### ISSUE TITLE
File renaming affects import code of other files

### ISSUE THREAD

**Issue by touho** [Microsoft/vscode#55688] opened 2018-08-02 16:56 UTC
- VSCode Version: 1.25.1
- TypeScript Versions: 3.1.0-dev.20180802 and ^2.9.2
- OS Version: Mac OS X High Sierra 10.13.2 (17C88)

Steps to Reproduce:

1. git clone https://github.com/touho/openeditplay.git
2. git checkout 50ec76aaa7ec1c4823be46678f748e911893550c
3. npm i
4. Open project folder with VSCode
5. Open `src/editor/views/popup/Popup.ts`
6. Notice first line `import { ... } from 'redom';`
7. Navigate to `src/util/input.ts` in Explorer view
8. Right click the file and Rename the file. For example `input2.ts`
9. Open `Popup.ts` again (Step 5)
10. Notice that `input.ts` has been refactored correctly, but the first line has changed to:
`import { ... } from '../../../../node_modules/@types/redom/index';`

If I rename a file, imports of other files should not change.

Does this issue occur when all extensions are disabled?: Yes

Since I'm using the code from `node_modules/redom/` and only types from `node_modules/@types/redom`, the project doesn't compile anymore using Rollup. Compile command: `node autobuild.js editor`

My user settings:
```
{
    "git.autofetch": true,
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "editor.insertSpaces": true,
    "editor.minimap.enabled": false,
    "window.zoomLevel": 0,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "files.trimTrailingWhitespace": true,
    "search.useIgnoreFiles": false,
    // Configure glob patterns for excluding files and folders. For example, the files explorer decides which files and folders to show or hide based on this setting.
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/*bundle.js*": true,
        "**/*bundle.es6.js*": true
    }
}
```

**Comment by mjbvz** [comment] 2018-08-03 06:25
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-08-03 06:25 UTC
Labels: typescript
