### ISSUE TITLE
Add an option to link to an account

### ISSUE THREAD

**Issue by MJKSabit** [microsoft/vscode#89226] opened 2020-01-24 13:33 UTC
Please add option to link VS Code with any account ( Let it be google, github, microsoft or others) and so we can store information like which **extension** is used or which **theme** is applied or User customized **settings** so that we can use VS Code with same environment in different platform.
Thank you.
Sorry for my bad English skill.

**Comment by gjsjohnmurray** [comment] 2020-01-24 15:28
/duplicate of #2743 which is part of the January 2020 milestone.

**Closed** 2020-01-24 15:28 UTC
Labels: *duplicate
