### ISSUE TITLE
Images not updated on change using  Remote WSL

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#143988] opened 2022-02-26 00:22 UTC
Doesn't seem to be fixed. I used Remote WSL for this one.

![Recording 2022-02-25 at 12 56 47](https://user-images.githubusercontent.com/2644648/155801833-3cffb69c-f18b-433a-97e4-460530d7a42f.gif)

_Originally posted by @TylerLeonhardt in https://github.com/microsoft/vscode/issues/143291#issuecomment-1051261615_

**Comment by mjbvz** [comment] 2022-02-26 00:23
@bpasero Are the any known issues with the file watcher on Remote WSL? Here's where we setup the file watcher:

https://github.com/microsoft/vscode/blob/1678c27fcd98ba0aeb43e8d51a293e7b35c62d23/extensions/image-preview/src/preview.ts#L146

**Comment by bpasero** [comment] 2022-03-03 06:56
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `Help | Toggle Developer Tools`
* select `Console`
* filter the output by typing `File Watcher` into the filter box
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323290-f3ba6470-dfed-4066-a19c-951395611738.png)

**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by aeschli** [comment] 2022-03-04 13:57
Great writeup @bpasero! This definitely should go into the docs and/or wiki!

**Comment by bpasero** [comment] 2022-03-04 15:28
Good idea, I wrote up https://github.com/microsoft/vscode/wiki/File-Watcher-Issues and it appears in the TOC:

![image](https://user-images.githubusercontent.com/900690/156791746-bc3d8b20-ab1e-4d64-88cd-2eec9438b8e5.png)

**Comment by bpasero** [comment] 2022-04-18 11:28
I cannot reproduce:

![Recording 2022-04-18 at 13 19 47](https://user-images.githubusercontent.com/900690/163801889-b27c05fa-a0ef-473c-909e-ac307d3e00b1.gif)

@TylerLeonhardt can you still?

**Comment by TylerLeonhardt** [comment] 2022-04-19 19:59
My Windows machine is broken unfortunately... I won't really have time to get it back in working order for a bit. Feel free to close this as needs more info or we can leave it for verification during endgame.

**Closed** 2022-04-20 15:09 UTC
Labels: bug, needs more info, file-watcher, remote
