### ISSUE TITLE
No settings autocomplete after update to 1.76.0

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode#175803] opened 2023-03-01 21:22 UTC
Type: <b>Bug</b>

Vscode settings autocomplete stopped working after update to 1.76. I noticed that this is caused by the following setting:
```
"http.systemCertificates": false,
```
When it is enabled, vscode cannot load json schema and reports the following warning:
```
Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.(768)
```

UPD. I completely removed this setting and there still no autocomplete. Looks like this issue is caused by something else

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 6.2.1-arch1-1
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 4700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|15.55GB (10.51GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by shuebner** [comment] 2023-03-09 05:05
My guess is that this is related to JSON schema validation not working in general with 1.76.0 (see #176591)

**Comment by Igorgro** [comment] 2023-03-16 09:11
I can't make a 100% reproduce because it from time to time for unknown reasons: sometimes it is loaded correctly, sometimes not

**Comment by Igorgro** [comment] 2023-04-03 10:54
Still happens in 1.77.0

**Comment by aeschli** [comment] 2023-05-03 20:47
duplicate of #177142

**Closed by aeschli** 2023-05-03 20:47 UTC
