### ISSUE TITLE
Allow to open same folder in multiple windows

### ISSUE THREAD

**Issue by hansyulian** [Microsoft/vscode#5218] opened 2016-04-13 07:37 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Open Visual Studio Code (called window 1)
2. Open D:\Project
3. CTRL-SHIFT-N or File -> New Window (called window 2)
4. In the new window, Open D:\Project again

expected:
New Window, the window 2, will also have the folder D:\Project just like window 1.

Result:
Instead of opening the D:\Project in window 2, it give focus to window 1 and leave window 2 sitll open nothing.

Reason:
1. I am working with multi monitors, at least 2, and 1 monitor will most likely only able to hold 2 tabs at max so that i can compare code within the same project. I will need another window to put the other tab even though it's under the same folder, maybe it's not a problem i i have the same monitor resolution, but currently, i am using one laptop monitor (1366x768) and additional lcd monitor (1920x1080) which give problem if i try to display the editor under resolution (3286x ????) just to compare codes.

2. There is no option to let the editor tab float as independent window

**Comment by bpasero** [comment] 2016-04-27 19:19
Closing as duplicate of #2686

**Closed by bpasero** 2016-04-27 19:19 UTC
Labels: feature-request, files

**Comment by michaelfriedman** [comment] 2017-06-16 16:16
Did this ever get implemented?

**Comment by JeffreyLeeSpokeo** [comment] 2017-08-17 22:51
Yea I like to know the same too because I opened a window and opening the same folder just brings me to the already opened window with the same folder

**Comment by RoyTinker** [comment] 2017-11-13 23:59
If you've landed here from a google search for multi-window support in VSCode, here's the current issue for that (please add a thumbs-up!): https://github.com/Microsoft/vscode/issues/10121
