### ISSUE TITLE
Search text in interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#142748] opened 2022-02-10 17:29 UTC
Is there a way to search text in the output displayed in the interactive window? I could not find a way to do It, although it is a very handy feature.

_Originally posted by @GitHunter0 in https://github.com/microsoft/vscode-jupyter/issues/1444#issuecomment-1034767503_

**Comment by gjsjohnmurray** [comment] 2022-02-23 15:51
Is this a duplicate of #130587?

**Comment by greazer** [comment] 2022-02-28 21:35
Yes, dupe of #130587

**Closed by greazer** 2022-02-28 21:35 UTC
Labels: interactive-window, notebook-find
