### ISSUE TITLE
Web upload: "Replace All" for web file explorer drag and drop upload

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99174] opened 2020-06-02 19:25 UTC
Testing #97714
ref #99074

When re-uploading a folder its tiresome to manually accept replacing every item. This is made worse because the "replace" button moves with each new file.

**Comment by isidorn** [comment] 2020-06-03 09:23
Closing as duplicate of https://github.com/microsoft/vscode/issues/99176
We should handle these two cases similarly

**Closed** 2020-06-03 09:23 UTC
Labels: *duplicate, file-explorer, web
