### ISSUE TITLE
Git not working after upgrade

### ISSUE THREAD

**Issue by emilekberg** [Microsoft/vscode#37981] opened 2017-11-09 19:13 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-mocha|Com|0.1.1
tslint|eg2|1.0.16
csharp|ms-|1.13.0
debugger-for-chrome|msj|3.5.0
material-icon-theme|PKi|2.2.4
shader|sle|1.1.2
shader-toy|ste|0.4.0
unity-tools|Tob|0.1.9
unity-debug|Uni|1.2.1
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. Start Latest VS Code
2. Go to Source Control panel
3. It states: "There are no active source control providers"

Reproduces without extensions: Yes

I tried the workspaces, the first thing i did. not sure if this has something to do with it? Anyhow VS Code does not recognize git as a source control system anymore. At first i thought it was because i was using workspaces with two git repos in them, but it seems not to be caused by that. Any repo does not work.

**Comment by marisvs** [comment] 2017-11-09 19:57
I have exactly the same problem. Before the upgrade to 1.18 git integration was seamless. Now I get the message "There are no active source control providers"

**Comment by sean-mcmanus** [comment] 2017-11-09 22:09
Users reported this with the ms-cpptools extension too, and that reinstall the extension fixed it, so reinstalling the csharp extension may fix this too, although the root cause is some VS Code bug.

**Comment by joaomoreno** [comment] 2017-11-10 09:47
@emilekberg @marisvs  Can you shutdown Code and run it with `code --disable-extensions`?

**Comment by emilekberg** [comment] 2017-11-10 10:19
@joaomoreno the original ticket state, I tried it with this parameter since the ticket template asked me to.

**Comment by joaomoreno** [comment] 2017-11-10 10:36
Can you show me a screenshot?

What folder are you opening? Is it the root of the repository?

**Comment by marisvs** [comment] 2017-11-10 11:55
code screenshot:
![image](https://user-images.githubusercontent.com/22528944/32657444-100ad9be-c616-11e7-9106-9b8cef29256e.png)
windows explorer screenshot:
![image](https://user-images.githubusercontent.com/22528944/32657476-2ead91ae-c616-11e7-9703-ef156b78d515.png)
I am working in the root of the repository as you can see from the second screen shot


I also checked to launch code with : "code --disable-extensions" but problem remains.

**Comment by joaomoreno** [comment] 2017-11-10 14:03
Can you run `Git: Show Git Output`? What's in there?

**Comment by marisvs** [comment] 2017-11-10 14:15
~\Documents\Coding\Cognitive Chess\Reasoning [master +9 ~1 -0 !]> git show
commit e7d566e5b489d1ea09a97e38b52e62c6447e1065

Date:   Mon Nov 6 19:27:24 2017 +0100

    Added Fool's and Scholar's mate

diff --git a/checkmate examples.txt b/checkmate examples.txt
index e7579cf..f3bdb19 100644
--- a/checkmate examples.txt
+++ b/checkmate examples.txt
@@ -59227,3 +59227,5 @@ r3k2r/pp3pbp/2p3p1/3pp3/8/1QP1RP1b/PP1P1PqP/RNB4K w
 2Q1k2r/5ppp/p4n2/3Np3/2p2p2/8/PqP3PP/3R1K2 b
 4Rk2/5Bb1/6Q1/1Pp4p/2r5/7P/5PK1/8 b
 1R6/4Q2p/4pk1q/b4ppP/3PP1P1/B4P2/4K3/7R b
+r1bqkbnr/p1pp1Qpp/1pn5/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR b
+rnb1kbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR w
\ No newline at end of file
diff --git a/checkmate_patterns.json b/checkmate_patterns.json
index 50e2260..cae0f8c 100644
--- a/checkmate_patterns.json
+++ b/checkmate_patterns.json
@@ -28,6 +28,14 @@
             "example": "7k/7R/5N2/8/8/8/8/7K b"
         },
         {
+            "name": "Fool's mate",
+            "near": "----K---x",
+            "square": "d1",
+            "checker": "q",
+            "example": "rnb1kbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR
w",
+            "comment": "must be checked before Back-rank mate"
+        },
+        {
             "name": "Back-rank mate",
             "square": ".1",
             "near": "---[-x]K[-x]--[-x]|---[-x]K[-x][-x]--",
@@ -89,6 +97,15 @@
             "example": "8/8/8/8/6p1/5qk1/7Q/6K1 b"
         },
         {
+            "name": "Scholar's mate",
+            "square": "d1",
+            "near": "----K-cqx-",
+            "checker": "q",
+            "protect": "b",
+            "example":
"r1bqkbnr/p1pp1Qpp/1pn5/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR b",
+            "comment": "must be checked before Damiano's bishop mate"
+        },
+        {
             "name": "Damiano's bishop mate",
             "square": ".1",
             "near":
"[-x]{4}K[-x]cq[-x]{2}|[-x]{4}K[-x]{2}cq[-x]|[-x]{4}K[-x]{3}cq",
~\Documents\Coding\Cognitive Chess\Reasoning [master +9 ~1 -0 !]> git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   checkmate.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Reasoning examples.docx
        Rules.xlsx
        checkmate_patterns - 0.9.json
        checkmate_patterns - Copy.json
        checkmate_patterns_old.json
        known_mate_patterns.txt
        mates_output.xlsx
        output.csv
        output2.csv

no changes added to commit (use "git add" and/or "git commit -a")
~\Documents\Coding\Cognitieve Chess\Reasoning [master +9 ~1 -0 !]>

So after my last commit I have 1 modified file, but that is not reflected
by Code.

2017-11-10 15:04 GMT+01:00 João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment] 2017-11-10 14:19
No, in VS Code, open the Command Palette (<kbd>Ctrl Shift P</kbd>) and run the `Git: Show Git Output` command. It will show you a log view for the git integration. What's in there?

**Comment by marisvs** [comment] 2017-11-10 14:28
Then I get the following output:
[image: Inline afbeelding 1]

2017-11-10 15:20 GMT+01:00 João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment] 2017-11-10 14:32
Please attach the image on GitHub. It doesn't work if you send it via email.

**Comment by marisvs** [comment] 2017-11-10 14:36
![image](https://user-images.githubusercontent.com/22528944/32663035-dca70d06-c62c-11e7-8de1-375c33f07581.png)

**Comment by joaomoreno** [comment] 2017-11-10 15:29
Can you reproduce with the standalone ZIP? https://go.microsoft.com/fwlink/?Linkid=850641

**Comment by marisvs** [comment] 2017-11-10 16:56
After downloading, I extracted the files to a temp directory and executed code.exe.
I was a little surprised to see my latest opened files (so that info is stored centrally?).
The git problem is the same as before. Also git: show output gives the same error message.

**Comment by emilekberg** [comment] 2017-11-10 18:45
yes i get the same behaviour as @marisvs is describing, even with downloaded version. 
Is vs code dependent on external git client now and was not before? because i have not installed any git in windows. but it worked before. Long shot maybe, but something might have changed?

I use my git cli through ubuntu bash terminal.

**Comment by j-cong** [comment] 2017-11-11 19:20
I have same problem. This is the only error from my VS Code's integrated DevTools:

![git is not working - vs code](https://user-images.githubusercontent.com/23460372/32692555-838983a6-c722-11e7-8afc-9f1b6ba1dc4e.jpg)

I'm using "GitHub for Desktop" and its git-bash on Win 8.1

**Comment by parky128** [comment] 2017-11-12 07:51
Same problem here, I have just installed the 64 bit version (1.18, also I am on windows 10) where I previously had the 32 bit one which I uninstalled as instructed prior to installing the 64 bit version. 

I then see the `There are no active source control providers` text displayed in the Source Control pane in VS Code.

I also get the `command 'git.showOutput' not found` toast message at the top of VS Code when opening the `Command Palette (Ctrl Shift P) `and run the `Git: Show Git Output` command 

This has never been an issue previously, I have just tried installing and using the 32 bit version again, but still the error remains

**Comment by emilekberg** [comment] 2017-11-12 11:06
@parky128 @j-cong @marisvs do neither of you have git installed on your machine seperately also? Or is that just me?

**Comment by j-cong** [comment] 2017-11-12 18:01
@emilekberg I don't have separately installed Git, only the one that comes with "Git for Desktop", which is Portable Git as I know. But VS Code's "source control/git" has worked under the same conditions before 1.18.0 release. 
"git.path" in my settings was set to null. I can confirm that after setting it manually, it starts working

**Comment by emilekberg** [comment] 2017-11-12 19:32
@j-cong exactly same scenario as me... There must be some issue with built in github in this version then... :) Let's see when the crew gets back at it.

**Comment by joaomoreno** [comment] 2017-11-13 10:50
Code doesn't work with git which comes with Github for Windows, unfortunately.

Can you install Git from https://git-scm.com/ and see whether that solves the problem?

**Comment by emilekberg** [comment] 2017-11-13 18:18
@joaomoreno your suggested task should solve the problem, as it worked with the external one, however, my setup has worked in EVERY version of vscode except for the latest one, so something must have changed?

**Comment by marisvs** [comment] 2017-11-13 18:31
Same for me. It has always worked without any configuration of either
vscode or git at my side. After upgrade to 1.18 it stopped working.

2017-11-13 19:18 GMT+01:00 Emil Ekberg <notifications@github.com>:

**Comment by joaomoreno** [comment] 2017-11-13 19:10
@emilekberg @marisvs I assume both you guys are in Insiders?

**Comment by vbarinov** [comment] 2017-11-14 13:04
@joaomoreno My git executable wasnt in the system PATH (to be precise it was, but the old one). The problem is, before v. 1.18 VSCode somehow knew how to reach git (in `C:\Users\%username%\AppData\Local\GitHub\PortableGit_%rid%\cmd`) and now it wont. I should mention a reinstall of GitHub git a while ago, so the path probably changed.

Resolved the issue by putting current git path to the system PATH variable.

1.18.0 x64 Stable, Windows_NT x64 10.0.16299

**Comment by robdonn** [comment] 2017-11-14 15:08
Just a note for some that may also have this problem - My `git.exe` was located at the following path:

`C:\\Users\\%username%\\AppData\\Local\\Programs\\Git\\bin\\git.exe`

Adding that to `git.path` in my settings fixed everything.

**Comment by emilekberg** [comment] 2017-11-14 18:26
So i guess a better error message would be needed? since "There are no active source control providers" does not really describe that you might need to install git. 

Also another question i have, i'm trying to keep my windows as clean as possible and put most of my dev applications in Bash. Most works fine, but this seems like a hickup. I guess i'd need to use a window installation as of now?

**Comment by joaomoreno** [comment] 2017-11-15 08:36
https://github.com/Microsoft/vscode/issues/38244#issuecomment-344027257

Please use `git.path` to configure where `git` is located.

I will push it further an bring a message in front of the user if we can't find git and detect this is a git repo: #38393

---

@vbarinov I don't understand how you have this issue, since this change isn't in yet for stable... only for insiders... Are you sure nothing else changed in your system? This really should only happen for Insiders...

**Closed** 2017-11-15 08:37 UTC
Labels: git, needs more info, new release

**Comment by marisvs** [comment] 2017-11-15 08:54
I am not an insider

2017-11-15 9:38 GMT+01:00 João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment] 2017-11-15 09:05
@marisvs If you open a Windows Command Prompt, does `git --version` return a proper version? Is `git.exe` in your `PATH`?

**Comment by marisvs** [comment] 2017-11-15 09:15
no it is not in my path and it never was but, prior to version 1.18, vscode
was still able to launch git commands

2017-11-15 10:06 GMT+01:00 João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment] 2017-11-15 09:23
Oh!!!

https://github.com/Microsoft/vscode/pull/35965

Completely forgot about this. This change explains it. I'll do a better job at reporting this situation to the user in https://github.com/Microsoft/vscode/issues/38394

Thanks for all the info guys, sorry for my bad memory.

**Comment by Hotell** [comment] 2017-12-06 13:41
still doesn't work on OSX High Sierra
code: Version 1.18.1 (1.18.1)

works only when I run Code via ` code --disable-extensions` :-/

**Comment by DavidRayner** [comment] 2017-12-15 08:31
I'm seeing this after upgrading to v1.19.

- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:44.860Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.0.14
perl-syntax|jac|0.0.4
python|ms-|0.9.0
vscode-docker|Pet|0.0.22
(1 theme extensions excluded)

### Output of OUTPUT terminal on startup:
```
Looking for git in: C:\Users\\%username\%\AppData\Local\Programs\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Git installation not found.
```

### Output of `where git` in intergrated after startup:
```
> where git
C:\Users\dr4\AppData\Local\Programs\Git\cmd\git.exe
```
