### ISSUE TITLE
Bug: Tabs in mac (High Sierra) not work

### ISSUE THREAD

**Issue by nicobytes** [Microsoft/vscode#40091] opened 2017-12-12 13:00 UTC
- VSCode Version: 1.18.1
- OS Version: High Sierra

Steps to Reproduce:

1. Open vscode
2. File -> New window
3. Tabs in mac not work

![vscode](http://i.cubeupload.com/d5Dofb.png)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment] 2017-12-13 06:11
Duplicate of https://github.com/Microsoft/vscode/issues/35361

**Closed by bpasero** 2017-12-13 06:11 UTC
Labels: workbench, workbench-tabs
