### ISSUE TITLE
Explorer: some extension commands show up for root

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29162] opened 2017-06-21 06:10 UTC
Looks like some of extension commands show up when right clicking into empty space:

![image](https://user-images.githubusercontent.com/900690/27369617-0dbf1b8e-5659-11e7-8ed1-a435e0292061.png)

I think we need to tweak the resource context for this case. Imho there should be no active resource when right clicking into empty space at least when being in multi root.

**Comment by isidorn** [comment] 2017-06-21 09:34
The problem is that @ziyasal contributes his actions to the `explorer/context` always no matter the resource https://github.com/ziyasal/vscode-open-in-github/blob/master/package.json#L96

Either the extensions should use some `when` clause when contributing actions or we should introduce a brand new `context` only for the root. Something like `explorer/root/context`.

**Comment by ziyasal** [comment] 2017-06-21 09:44
@isidorn, @bpasero Thank you pointing that out, is there any workaround to prevent that before finding proper solution? I'll also have a look at to that asap.

**Comment by bpasero** [comment] 2017-06-21 10:10
@isidorn ah good point, then maybe those actions are actually valid, even though the resource is probably undefined at that time.

**Comment by isidorn** [comment] 2017-06-21 10:30
@ziyasal the first two actions you should contribute only when a user clicks on a file and not on a folder.

Looking into our docs https://code.visualstudio.com/docs/extensionAPI/extension-points I am not sure what is the best `when` clause to capture that, maybe something like `resourceLangeId != undefined`, though @jrieken would be better to give advice on this

Closing this issue since I have pushed some checks on our side that we do not return any argument to the contibuted actions when clicked on empty area

**Closed by isidorn** 2017-06-21 10:30 UTC
Labels: explorer-files, multi-root
