### ISSUE TITLE
TernarySearchTree: Cannot read property '1' of undefined #138284

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#228184] opened 2024-09-11 04:31 UTC
https://dev.azure.com/vscode/VSCode/_build/results?buildId=131237&view=logs&j=f3dd96f0-7bf9-51c6-1e87-22c4cfa2ad69&t=64143725-e422-5a00-94cb-1f22962f3da8&s=96ac2280-8cb4-5df5-99de-dd2da759617d

```
1) Ternary Search Tree
       TernarySearchTree: Cannot read property '1' of undefined #138284 (random):
     
  RangeError: Invalid array length
      at Array.push (<anonymous>)
      at TernarySearchTree._delete (http://localhost:35829/34598d27553151b465cd128fec0102e7/out/vs/base/common/ternarySearchTree.js:396:23)
      at TernarySearchTree.delete (http://localhost:35829/34598d27553151b465cd128fec0102e7/out/vs/base/common/ternarySearchTree.js:384:21)
      at Context.<anonymous> (http://localhost:35829/34598d27553151b465cd128fec0102e7/out/vs/base/test/common/ternarySearchtree.test.js:718:27)
```

**Comment by jrieken** [comment] 2024-12-09 13:57
duplicate of https://github.com/microsoft/vscode/issues/227147

**Closed by jrieken** 2024-12-09 13:57 UTC
Labels: unit-test-failure, web
