### ISSUE TITLE
Focus won't switch to first editor in explorer

### ISSUE THREAD

**Issue by dlong500** [microsoft/vscode#100528] opened 2020-06-18 20:41 UTC
Issue Type: <b>Bug</b>

After opening multiple editors, trying to switch back to the first editor in the list by clicking on the editor in the "Open Editors" explorer pane results in nothing happening.  Focus can be switched among all other open editors, but not to the first one in the list.  See GIF for a better visual representation of the issue.
![vscode-first-editor-issue](https://user-images.githubusercontent.com/430481/85069497-374ed700-b182-11ea-97e8-f2ee15996949.gif)

Note that this occurs whether extensions are active or not.

Is it possible the fix for https://github.com/microsoft/vscode/issues/100175 could be causing it?

VS Code version: Code - Insiders 1.47.0-insider (84f52fe1c0124307046ac0f5443493cda946e60f, 2020-06-17T06:43:38.511Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 2672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.99GB (1.32GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dlong500** [comment] 2020-06-20 15:58
Any updates on this?  I installed vscode insiders on a completely different workstation since I was beginning to doubt my sanity with no one else upvoting or commenting on the report.  I experience the same bug on a clean install of insiders with no extensions.

**Comment by isidorn** [comment] 2020-06-22 08:34
@dlong500 good catch. I can reproduce this.
Also assigning to @joaomoreno since this is probably caused by the fix for #100175

**Comment by isidorn** [comment] 2020-06-23 10:35
This works fine for the first file in the explorer, so the issue might be in the Open Editors view. investigating...

**Comment by isidorn** [comment] 2020-06-23 10:38
Minor issue in the Open Editors view, pushed a fix.
@dlong500 you can try it out with vscode insiders from tomorrow and let us know how it goes. Thanks!

**Closed** 2020-06-23 10:37 UTC
Labels: bug

**Comment by dlong500** [comment] 2020-06-25 21:10
I can confirm this is fixed in the latest insiders release (9b620b291e120caab8292cab38cad10c2b22dffe).  Thanks!

**Comment by isidorn** [comment] 2020-06-26 07:05
@dlong500 awesome. Thanks for letting us know!
