### ISSUE TITLE
On vscode update, download the new version before restart

### ISSUE THREAD

**Issue by alexandruavadanii** [microsoft/vscode#189099] opened 2023-07-07 19:10 UTC
Type: <b>Feature Request</b>

It would be nice if we could download the new artifact in the background before restarting vscode to apply an update.

For example, I'm using vscode Insiders and haven't fully restarted it in a couple of days. Now that 1.81 is out, I have to apply two rounds of "Restart to update" and wait a couple of minutes each time before vscode can be used.

Extension version: 0.103.2023062115
VS Code version: Code - Insiders 1.81.0-insider (31f183271b0d1f24a2052f6eccbb76bdef45d60b, 2023-07-07T05:32:34.809Z)
OS version: Windows_NT x64 10.0.18362
Modes:
Remote OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64

**Comment by joaomoreno** [comment] 2023-07-28 06:55
Duplicate of https://github.com/microsoft/vscode/issues/188174#issuecomment-1652180291

**Closed by joaomoreno** 2023-07-28 06:55 UTC
