### ISSUE TITLE
[json] Unable to format large JSON file

### ISSUE THREAD

**Issue by gajduk-mansystems** [microsoft/vscode#79014] opened 2019-08-13 07:37 UTC
Issue Type: <b>Bug</b>

I have a JSON file that is 5 MB large. When I try to format it nothing happens.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by yoshiask** [comment] 2019-08-13 08:28
VS Code has issues tokenizing large files. The algorithm is not perfect (nor do I know better alternatives). Try using a computer with a better CPU and/or more RAM, as it may help a bit. If you don't have access to a more powerful PC, maybe all you have to do is wait for a while as it does its work.

**Comment by gajduk-mansystems** [comment] 2019-08-13 08:35
![image](https://user-images.githubusercontent.com/33317975/62926958-df9f4c80-bdb5-11e9-87f3-c24192c89c6c.png)
I dont think CPU or memory are the issue. I have used Notepad++ and Atom in the past and both of them could easily format JSON files of similar sizes. It seems to me that that algorithm could use some optimizations.

**Comment by pramit-marattha** [comment] 2019-08-13 08:53
same issue 

![image](https://user-images.githubusercontent.com/37651620/62928259-ef2f8d00-bdd7-11e9-9365-e2748ec3f311.png)

**Comment by alexandrudima** [comment] 2019-08-13 09:31
I could not reproduce with generating a JSON using the following:
```js
const fs = require('fs');

let obj = {};
for (let i = 0; i <103210;i ++) {
	obj[`a${i}`] = 'asdasdadasdasdadasdasdasdasd';
}

fs.writeFileSync('out.json', JSON.stringify(obj));
```

After running "Format Document" it takes some time, but the JSON gets formatted:

![format](https://user-images.githubusercontent.com/5047891/62931005-d74b0f80-bdbd-11e9-9a8c-8edc2a4e8345.gif)

**Comment by gajduk** [comment] 2019-08-13 10:01
I am glad you are looking into this. As you can see already in your example it already takes quite some time, and there is no indication that something is happening. That aside in my case I waited for several minutes!!! and nothing happened. 

I can not post the original JSON  that I have because it has a ton of private data but I can share some patterns that I see: 
1.  it is is nested many levels deep ~ 20, unlike yours which is all on the same level
2.  some values are very long as they represent base64 encoded png files
3.  some values are escaped large json strings so they have a lot of escaped special json characters such as brackets, quotes, commas etc
Here is a modified script to generate such a file:
```
const fs = require('fs');

function randomStringShort() {
    return Math.random().toString(36).substring(7);
}

function randomStringLong() {
    let res = '';
    for (let i = 0; i < 50 ; i++) {
        res += Math.random().toString(36);
    }
    return res;
}

function randomString() {
    if ( Math.random() < 0.05 ) return randomStringLong();
    else                       return randomStringShort();
}


function generateNestedRec(level) {
    if ( level > 20 || Math.random() < 0.35 ) return randomString()
    if ( level > 5  && Math.random() < 0.6 ) return randomString(); // do not generate too much data
    let res = {};
    for (let i = 0; i <5;i ++) {
        if ( level == 1 &&  i > 2 ) {
            res[randomStringShort()] = JSON.stringify(res); // long escaped json string
        }
        else {
            res[randomStringShort()] = generateNestedRec(level+1);
        }
    }
    return res;
}

let obj = generateNestedRec(0);
fs.writeFileSync('out.json', JSON.stringify(obj));
```
Attached is a generated sample file that not only fails to format but actually crashes VS code
[out.txt](https://github.com/microsoft/vscode/files/3496435/out.txt)

**Comment by alexandrudima** [comment] 2019-08-13 11:31
Formatting for me freezes VS Code for a while, but does not lead to a crash:

![image](https://user-images.githubusercontent.com/5047891/62938050-81329800-bdce-11e9-880b-821079f42fd4.png)

Things that can be improved:
- the view model is constructed twice, once as a result of the model content changes, and once as a result of the line numbers width increasing
- bracket matching is not time bound

**Comment by rjk** [comment] 2019-12-12 15:18
I consistently get a crash on a 13MB json file. I'm happy to share it directly with anyone working on this, but can't post it publicly.

**Comment by gajduk-mansystems** [comment] 2019-12-12 15:21
Since Visual Studio Code is way too slow and unstable I set on a search for a formatting tool. Found this gem: [https://www.jsonformatter.io/](https://www.jsonformatter.io/)
It is blazing fast and has never crashed on me. I have put in 50 MB files in and it was able to format them almost instantly. Maybe the people from visual studio code can acquire the code behind it.

**Comment by alexdima** [comment] 2020-01-10 10:13
This file from https://github.com/microsoft/vscode/issues/79014#issuecomment-520772345 is working a lot better for me after the changes from #88405

When I run Format, it takes the language service a while to compute the edits, and once the edits are in, it takes the editor around 1s to apply them (264k edits!!), which I think is reasonable:
![image](https://user-images.githubusercontent.com/5047891/72145091-06c86d00-339a-11ea-95b6-495b884a8fca.png)

@rjk Can you please share with us a JSON file that reproduces crashing

**Comment by rjk** [comment] 2020-01-10 23:28
I just retested now. 

Using 1.40.2 it crashed VSCode when I opened VS Code, opened the JSON file, right-click on document > Format Document. It probably took about 30s after choosing the menu option and crashing. By 'crash' I mean I got a dialog saying VS Code had to close, and I had the option to have it restart. Sorry, took no screenshot. 

Using 1.41.1 with same steps I instead get a message 'Extension host terminated unexpectedly' and there's a 'Javascript heap out of memory' error in devtools. VS Code memory usage got to about 3.8GB.
The first time I restarted extension host and tried again VS Code hung. To do this, after clicking Restart Extension Host I waited till right-click menu included Format Document, clicked it, then it hung. CPU was low ~30% and memory ~1.2GB, but UI unresponsive and I get 'The window is no longer responding' messages (Reopen/Keep Waiting/Close). After about the 3rd/4th one I chose Close. Upon restarting VS Code I was able to replicate the Extension Host crashing but not the VS Code hang. I haven't tried more than once. 

I've emailed the file to you now @alexdima

**Comment by alexdima** [comment] 2020-01-20 14:29
@aeschli The JSON formatter gives 1_400_000 edits for this particular file. In any case, the editor will merge if more than 1_000 edits are applied into a single edit. But a lot of time and memory is wasted to transmit those 1_400_000 edits, to validate the ranges, etc.

Would it be possible to change the JSON formatter to return a single huge change in this case?

**Comment by aeschli** [comment] 2020-01-22 14:59
Fixed by https://github.com/microsoft/vscode/commit/ce31ace9d9e4a67851c0fb4ed5633ebb494f8c6f

**Closed by aeschli** 2020-01-22 14:59 UTC
Labels: editor-wrapping, freeze-slow-crash
