### ISSUE TITLE
Highlighted indent guides disappears on scrolling off screen

### ISSUE THREAD

**Issue by leewilly** [Microsoft/vscode#49769] opened 2018-05-13 05:21 UTC
- **VSCode Version**: 1.23.1
- **OS Version**: macOS High Sierra 10.13.4

**Steps to Reproduce**:

1. Click on opening bracket until highlighted indent guides visible
2. Scroll down all the way off the screen to the closing bracket
3. Indent guide will disappear

4. Click on closing bracket
5. Scroll up all the way off screen to the opening bracket
6. Indent guide still visible

**Does this issue occur when all extensions are disabled?**: Yes

Bug occurs on long nested code when scrolling needed between opening and closing brackets only.

**Comment by usernamehw** [comment] 2018-05-13 17:55
Duplicate of #49173

**Closed** 2018-05-14 09:33 UTC
Labels: new release
