### ISSUE TITLE
Explorer: folders should act like the ones in Finder/Xcode on Mac

### ISSUE THREAD

**Issue by xareelee** [Microsoft/vscode#27148] opened 2017-05-23 16:29 UTC
As a Mac user, I expect all folders act the same behavior just like they do in Finder or Xcode:

1. click the folder: just select the folder (**not expands/collapses it**).
2. click the disclosure triangle: expands/collapses the folder.
3. `option + arrow-right/arrow-left` on a selected folder: expands/collapses all sub-folders in the hierarchy.
4. hold `option` and click the disclosure triangle: just like what `option + arrow-right/arrow-left` do to expands/collapses all sub-folders in the hierarchy.

Current behaviors which I did not expect:

1. Simply clicking the folder will expands/collapses the folder (should just select it).
2. Can't find a familiar way to expands/collapses all sub-folders in the hierarchy (using `option`).

I really do expect that VSCode team can fulfill this expectation in Explorer.

**Comment by roblourens** [comment] 2017-05-23 18:06
The option+click part is covered in #9456. Not sure whether there's an existing issue for the first part.

**Comment by mjbvz** [comment] 2017-11-03 22:46
Yes, 1 is as-designed currently. Clicking and dragging or right clicking will not expand the folder though

Closing as duplicate of #9456 for 2

**Closed by mjbvz** 2017-11-03 22:46 UTC
Labels: duplicate, explorer-files, feature-request
