### ISSUE TITLE
p

### ISSUE THREAD

**Issue by ptoru001** [microsoft/vscode#118152] opened 2021-03-04 23:44 UTC
Issue Type: <b>Performance Issue</b>

vscode wont run anything based on python extensions.

VS Code version: Code 1.54.0 (42e27fe5cdc58539dad9867970326a297eb8cacf, 2021-03-03T02:17:59.499Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.48GB free)|
|Process Argv|--crash-reporter-id 8df700d7-f692-4a2d-b9b0-1d5510f8ddfd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	   131	 13186	code main
    0	    49	 13189	   gpu-process
    0	    33	 13191	   utility
    0	   131	 13196	   shared-process
    0	    33	 13198	     ptyHost
    0	     0	 13290	       /bin/zsh -l
    0	     0	 13319	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   246	 13240	   window (Welcome — cu-nyc-data-pt-05-2020-u-c)
    1	   295	 13241	     extensionHost
    0	    33	 13255	       electron_node languageserver.js 
    0	    16	 13256	       /Users/alfonsotoruno/.vscode/extensions/tabnine.tabnine-vscode-3.2.8/binaries/3.3.82/x86_64-apple-darwin/TabNine --client=vscode --no-lsp=true --client-metadata clientVersion=1.54.0 pluginVersion=3.2.8 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=One Dark Pro vscode-theme-kind=Dark vscode-status-customization=unknown ide-restart-counter=0
    0	    66	 13260	         /Users/alfonsotoruno/.vscode/extensions/tabnine.tabnine-vscode-3.2.8/binaries/3.3.82/x86_64-apple-darwin/TabNine --client=vscode --no-lsp=true --client-metadata clientVersion=1.54.0 pluginVersion=3.2.8 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=One Dark Pro vscode-theme-kind=Dark vscode-status-customization=unknown ide-restart-counter=0 --no_bootstrap
    0	    49	 13264	       electron_node server.js 
    0	    33	 13270	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=13241
    0	    49	 13303	       CodeStream
    0	    49	 13242	     watcherService
    0	    33	 13246	     searchService
    0	    49	 13317	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome — cu-nyc-data-pt-05-2020-u-c)
|    Folder (cu-nyc-data-pt-05-2020-u-c): 3979 files
|      File types: png(1215) md(387) ipynb(270) csv(190) py(134) gitkeep(83)
|                  sql(67) vbs(60) xlsm(55) xlsx(52)
|      Conf files:;
```

</details>
<details><summary>Extensions (94)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
30-seconds-of-code|30-|1.0.0
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|13.0.3
project-manager|ale|12.0.1
All-Autocomplete|Ati|0.0.23
vscode-django|bat|1.3.0
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
multi-cursor-case-preserve|Car|1.0.5
codestream|Cod|10.6.1
gitignore|cod|0.6.0
macros|ctf|0.0.4
vscode-eslint|dba|2.1.14
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
code-runner|for|0.11.2
cursoruler|fre|0.0.4
vscode-pull-request-github|Git|0.23.1
better-cursors|Gru|0.0.4
todo-tree|Gru|0.0.201
beautify|Hoo|1.5.0
vscode-settings-cycler|hoo|1.0.1
d3-js-snippets|Hri|1.0.0
output-colorizer|IBM|0.1.2
easy-snippet|inu|0.6.2
customize-ui|ioc|0.1.51
monkey-patch|ioc|0.1.12
vscode-essentials|jab|1.5.0
search-editor-apply-changes|jak|0.1.1
hungry-delete|jas|1.6.0
vscode-text-pastry|jkj|1.2.0
vscode-peacock|joh|3.9.1
vscode-map-preview|jum|0.5.8
chat|kar|0.35.0
vscode-format-context-menu|lac|1.0.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vsls-whiteboard|los|0.0.12
MagicPython|mag|1.1.0
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
vscode-language-babel|mgm|0.0.30
git-graph|mhu|1.29.0
vscode-checkpoints|mic|1.3.1
dotenv|mik|1.0.1
vs-rest-api|mkl|3.0.1
csharp|ms-|1.23.9
mssql|ms-|1.10.1
anaconda-extension-pack|ms-|1.0.1
gather|ms-|2021.3.0
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.3.0
jupyter|ms-|2021.3.619093157
resharper9-keybindings|ms-|1.1.0
vsliveshare|ms-|1.0.3912
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.23.0
gremlins|nho|0.26.0
webapplicationservices-language-server|Opa|6.12.2
polacode|pnp|0.3.4
vscode-css-peek|pra|4.1.0
java|red|0.75.0
vscode-yaml|red|0.16.0
explorer-exclude-vscode-extension|Red|1.2.0
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|0.4.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
vscode-multiclip|sle|0.1.5
extension-api|spy|0.3.2
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
control-snippets|svi|1.9.1
tabnine-vscode|Tab|3.2.8
html-preview-vscode|tht|0.2.5
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
codetour|vsl|0.0.44
gistfs|vsl|0.2.2
jinja|who|0.0.8
local-history|xyz|1.8.1
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.15
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30265443
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-03-04 23:54
/duplicate of #118126 and responses there indicate the issue is being actively worked on. Expect a fix in the 1.54.1 February Recovery release.

**Closed** 2021-03-04 23:55 UTC
Labels: *duplicate
