### ISSUE TITLE
Getting Typescript errors that didn't occur before the last update.

### ISSUE THREAD

**Issue by al-odonnell** [Microsoft/vscode#48301] opened 2018-04-20 20:06 UTC
Issue Type: <b>Bug</b>

I am getting typescript errors when I load documents.  However, the errors can be different or non-existent the next time I start VS Code depending on what documents I open first, what documents are already open, etc.  

Take just these two lines that I have in many files:
```ts
import React from 'react';
import PropTypes from 'prop-types';
```

I will see an error on 'react' and 'prop-types' in one file but not another.  If I open again with different files loaded, the same error may not occur in the same files.
```
[ts]
Could not find a declaration file for module 'react'. 'c:/Users/user/Development/Solutions-Development/Project/node_modules/react/index.js' implicitly has an 'any' type.
```

In some of the files that are open, I may see just the 'react' line with the error, but in other I'll see both.  I'll see errors as if prop-types wasn't imported, but in another similar file, no errors.  If I load again and reopen the file, I may not see the error again.

This seemed to start with the latest release of VS Code.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|Memory (System)|15.67GB (8.11GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
jshint|dba|0.10.18
vscode-eslint|dba|1.4.8
javascript-ejs-support|Dig|0.2.3
githistory|don|0.4.0
gitlens|eam|8.2.2
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.3.0
debugger-for-chrome|msj|4.3.0

</details>

**Comment by mjbvz** [comment] 2018-04-20 20:26
A few questions:

1. Does this happen in vscode insiders?
1. Have you configured a custom version of TS in your workspace?
1. Do you have a `tsconfig.json`?
1. Did you install `@type/react`?

**Comment by al-odonnell** [comment] 2018-04-20 20:41
1.  I don’t have vscode insiders,  I could try it if you think it may fix the issues.
  2.  I have not configured any custom version of typescript
  3.  No tsconfig.json
  4.  I have tried installing @type/react, but get different results.  Have not needed it in the past – did something change?  I get a similar error with prop-types, but that error occurs sporadically across the files.

Thanks for the help.

______________________________________________________
Al O'Donnell

**Comment by mjbvz** [comment] 2018-04-20 20:46
Yes try configuring a tsconfig. Typings would have never worked properly without installing `@types/react` so I' don't know what you were seeing before

**Comment by al-odonnell** [comment] 2018-04-25 21:05
Hello Matt,

I did everything you suggested.

However, there is something very strange going on.  I have a number of files open.  When I close and reopen, the file last opened is shown and produces Problems.  When I navigate to the other open files, I get no errors.  Now if I close and reopen with a different file active, that file will have Problems and the one that had Problems before shows no Problems.   I have no clue what is going on.

Prior to the recent update, I had no issues like this.

______________________________________________________
Al O'Donnell

**Comment by mjbvz** [comment] 2018-04-27 21:03
Thanks. Closing since it seems like the issue has been resolved or was caused by an extension

**Closed by mjbvz** 2018-04-27 21:03 UTC
Labels: javascript, needs more info
