### ISSUE TITLE
Multi-line comments could be collapsed to a single line 

### ISSUE THREAD

**Issue by SPDUK** [microsoft/vscode#110015] opened 2020-11-05 12:11 UTC
Multi-line comments take up 2 lines if you indent them "properly", but only 1 if you indent them incorrectly.
Shouldn't it just always take up 1 line?

**An example of a typical multi-line comment in a .`js` file:** 
![image](https://user-images.githubusercontent.com/33531423/98239138-67471d00-1f5f-11eb-8fbe-7ca0bf7f8e0b.png)

**What it looks like collapsed (takes up 2 lines):** 
![image](https://user-images.githubusercontent.com/33531423/98239158-70d08500-1f5f-11eb-86e2-14c4316de0dd.png)

**An example of what a multi-line comment looks like if you indent the end of the comment:**

![image](https://user-images.githubusercontent.com/33531423/98239229-880f7280-1f5f-11eb-8791-9ec0f6a3958e.png)

**What it looks like collapsed (only takes up 1 line):** 
![image](https://user-images.githubusercontent.com/33531423/98239274-965d8e80-1f5f-11eb-8b9e-9e9b702175c5.png)

In Webstorm a multi-line comment will always collapse down to a single line: 
![image](https://user-images.githubusercontent.com/33531423/98239323-affed600-1f5f-11eb-92e4-2d38864455e8.png)

![image](https://user-images.githubusercontent.com/33531423/98239340-b9883e00-1f5f-11eb-8039-93a5755d3419.png)

**Comment by mjbvz** [comment] 2020-11-05 19:38
Duplicate of https://github.com/microsoft/TypeScript/issues/35611

**Closed by mjbvz** 2020-11-05 19:38 UTC
