### ISSUE TITLE
feature request - filter folders in explorer view

### ISSUE THREAD

**Issue by raxim1** [Microsoft/vscode#34754] opened 2017-09-21 13:49 UTC
In every project in node, you have hundreds of folders under node_modules.

Next to the "Explorer" name at the top of the opened project (or project name or open editors) i would create a filter input text field.
What the filter tag would do, if you enter more than 3 character, it would filter all the directory and files according to their names, and show only the filtered ones with the related folder structures.

In the existing search panel it would be good, if the folder structure would remain, not just showing files purely.

It would be very efficient, at the moment, i'm looking ionic-angular folder on my workspace, and it's the 100th folder under node_modules. It's very cumbersome and hard to scroll. (as to drag the scroll, you need to be very-very precise, the scroll steps is too thin on hundreds of folders)

Extension manager filter is a good example for it.

**Comment by eamodio** [comment] 2017-09-22 03:23
This is a duplicate of https://github.com/Microsoft/vscode/issues/4763

**Closed** 2017-09-22 04:44 UTC
Labels: explorer-files
