### ISSUE TITLE
Splitted terminal resize display error

### ISSUE THREAD

**Issue by clem744** [microsoft/vscode#77579] opened 2019-07-18 14:45 UTC
Issue Type: <b>Bug</b>

When you use the mouse to resize one of the splitted terminal part, the text do not move, the previouse display is'nt erased and the new display overwrite 
the previous without cleared it.

In simple words, the two splitted terminal's display fuse when resized

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics (8 x 2037)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|13.71GB (4.18GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.6.24221

</details>

**Comment by clem744** [comment] 2019-07-18 14:55
![bug_vscode](https://user-images.githubusercontent.com/44908545/61467923-c05efc00-a97c-11e9-9eec-e4f94e40b8d4.png)
![bug_vscode_2](https://user-images.githubusercontent.com/44908545/61467947-c9e86400-a97c-11e9-94aa-2383fe451d3b.png)

**Comment by clem744** [comment] 2019-07-18 14:56
![bug_vscode_3](https://user-images.githubusercontent.com/44908545/61468076-fef4b680-a97c-11e9-98dd-a0154a0a2a4d.png)

**Comment by clem744** [comment] 2019-07-19 09:53
They are pottentially two thongs to adjust:

The first one is the fact that some newline ('\n') pop when you resized the splitted terminal.
The second one must be an error in the framerate display.

For exemple, when you use 'clear', sometimes some line persist on the terminal
![vs_code_bug_4](https://user-images.githubusercontent.com/44908545/61526937-aaecdf00-aa1b-11e9-81d9-babef8bb17a0.png)
.
(On the right side of the screen shot)

**Comment by clem744** [comment] 2019-07-30 14:42
![vscode_BUG](https://user-images.githubusercontent.com/44908545/62138790-854bb980-b2e8-11e9-9a5a-d1206dab98e3.png)

Also, they are some errors when you use some unicode characters:
In this exemple, I didn't press the spacebar, and this bug exist only on vscode and is not on my default terminal. The caracter was obtained using (ctrl+Maj+u , 2795 ,  enter)

**Comment by Tyriar** [comment] 2019-08-10 15:04
Closing as designed, when you resize the terminal and it goes into the prompt the shell redraws the shell over multiple lines, resizing back doesn't clear out the old wrapped lines and move the cursor up though. This happens in other terminals too.

Most unicode issues are due to https://github.com/xtermjs/xterm.js/issues/1709

**Closed by Tyriar** 2019-08-10 15:04 UTC
Labels: integrated-terminal
