### ISSUE TITLE
Source control stuck

### ISSUE THREAD

**Issue by js-writer** [microsoft/vscode#171923] opened 2023-01-21 17:31 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: Windows

Steps to Reproduce:

1. Start computer. Open fresh vscode.
2. Source control icon stuck on loading and doesn't show changes even if there are some.
3. To get rid of it I need to reload vscode or use Fetch from dropdown list because fetch in console doesn't help.

![image](https://user-images.githubusercontent.com/5675915/213874433-82b9c196-e28a-41df-b2ac-db16c5562f29.png)

**Comment by VedAustin** [comment] 2023-01-22 03:45
This is a buggy version .. a few things are broken

**Comment by js-writer** [comment] 2023-01-23 18:54
I had this also in previous versions.

**Comment by lszomoru** [comment] 2023-01-24 14:11
@js-writer, we are showing a progress indicator while scanning the folder/workspace for possible git repositories. Is there a chance that this is a large workspace and it just takes a long time for the initial repository discovery to complete? What is the value of the `git.repositoryScanMaxDepth` setting? Also could you please share the contents of [the git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)? Thanks!

**Comment by js-writer** [comment] 2023-01-25 18:43
No, does are small projects. And no matter how long I wait progress indicator doesn't disappear.
git.repositoryScanMaxDepth is set to 1.
Logs:
![image](https://user-images.githubusercontent.com/5675915/214654201-a2b0b11b-8e08-4f4f-bf78-a64168bb1422.png)

**Comment by lszomoru** [comment] 2023-01-26 16:52
@js-writer, are you able to reproduce the issue if you start VS Code as `code --disable-extensions`? Thanks!

**Comment by js-writer** [comment] 2023-01-26 19:01
Ok I did and have the same result:
![image](https://user-images.githubusercontent.com/5675915/214925944-87e0a273-be00-4e1b-a157-a8d4290c29bd.png)

**Comment by lszomoru** [comment] 2023-01-27 16:43
@js-writer, are you able to reproduce the same behaviour using [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by js-writer** [comment] 2023-01-27 17:10
Yes.
Same issue:
![image](https://user-images.githubusercontent.com/5675915/215150484-12149914-1215-41b0-8f7f-98f93ed44bf9.png)

**Comment by lszomoru** [comment] 2023-01-27 19:23
@js-writer, puzzling. Could you please try the following:
* Close all windows of VS Code Insiders
* From a terminal run `code-insiders --log trace`
* Open the folder/workspace containing the git repository
* Wait for 2 minutes, and share the contents of the git output window

**Comment by VedAustin** [comment] 2023-01-27 19:59
> @js-writer, are you able to reproduce the same behaviour using [VS Code Insiders](https://code.visualstudio.com/insiders/)?

VS code insiders seems to work for me and it is my new default version.

**Comment by js-writer** [comment] 2023-01-28 20:15
@lszomoru Here:
![image](https://user-images.githubusercontent.com/5675915/215288855-128fa2ab-1403-4d07-beac-cbbfcb99edde.png)

**Comment by lszomoru** [comment] 2023-03-28 09:32
@js-writer, thank you very much for sharing the logs, and apologies for not getting back to you on this. The logs show that there is a "Status" operation that starts which show the progress but for some reason the operation never completes. I will investigate the code and see what could be the reason behind that, and update the issue with my findings.

**Comment by js-writer** [comment] 2023-04-07 06:22
@lszomoru thx for replay. I think the problem was because I had old git version on my pc. After update everything is working fine. Unfortunately I don't know which version of git I had.
Thank you for support.

**Comment by js-writer** [comment] 2023-05-11 16:49
@sergeybaklanov my version is `2.40.0.windows.1`

**Comment by sergeybaklanov** [comment] 2023-05-11 19:24
I updated git to version 2.40.0 but still have this problem. When I try to implement some interface or extend some class source control goes to infinity update.

**Comment by arieller** [comment] 2023-05-12 13:06
Same issue for me, can't even format a saved file with prettier. Something broke hard
![image](https://github.com/microsoft/vscode/assets/32339430/3064ce5b-c491-47cf-90fd-2e585bf0e57a)
![image](https://github.com/microsoft/vscode/assets/32339430/e8f62bbd-4cbc-4101-8624-d26b15473a8e)

**Comment by lszomoru** [comment] 2023-05-17 13:50
@sergeybaklanov, could you please use the steps described [here](https://github.com/microsoft/vscode/issues/171923#issuecomment-1406973203) and share the contents of the git output window. Hopefully that will help us track down the root cause of the issue.

@arieller, it seems that in your case Prettier is trying to format the document. Could you please try to disable the Prettier extension and see if you are still able to reproduce the problem? Thank you!

**Comment by sergeybaklanov** [comment] 2023-05-18 07:25
@lszomoru 
User@WIN-2BVQ3PFI2R7 MINGW64 ~
$ code-insiders --log trace
bash: code-insiders: command not found

**Comment by lszomoru** [comment] 2023-06-06 14:47
@sergeybaklanov, do you have VS Code Insiders installed?
Could you please try running `code --log trace` from the Terminal instead?

**Comment by lszomoru** [comment] 2024-12-10 08:57
Closing as the requested logs were never provided to further investigate the issue.

**Closed by lszomoru** 2024-12-10 08:57 UTC
Labels: bug, info-needed, git
