### ISSUE TITLE
Path separator issue when Drag & Drop

### ISSUE THREAD

**Issue by nao20010128nao** [microsoft/vscode#117331] opened 2021-02-23 08:37 UTC
- VS Code Version: 1.53.2
- OS Version:
    - Local: Windows 10 (10.0.19041)
    - Remote: Ubuntu 20.04.2 LTS (GitHub Codespace and my own VPS)

# Steps to Reproduce:

1. Open VSCode's `Explorer` and `Terminal`
1. Drag any file from VSCode's `Explorer` to `Terminal`
2. See text being pasted in `Terminal`

Does this issue occur when all extensions are disabled?: No. disabling any other extensions than `Remote Connection`s won't fix this issue.

# Description
While you are accessing a Linux computer using `Remote Connection` from **Windows**, Local and Remote have different directory separator. (with the same system, this is not problem at all)

When you DD a file from VSCode's `Explorer` to `Terminal`, directory separator from **Local Windows computer** (`\`) is used, which is different from **Remote Linux computer** (`/`).
In Windows, directory separator is backslash, but it is used for escape character in Bash or some other *nix shell.

Here's a screenshot tried this:
![image](https://user-images.githubusercontent.com/10355528/108817644-91e6df80-75fb-11eb-9a64-517d93f3e64c.png)

# Expected
For example, when you DD'ed a file named `CONTRIBUTING.md`, should paste like `/home/codespace/workspace/ytdl-patched/CONTRIBUTING.md` .

# Actual
With the same example above, pastes `\home\codespace\workspace\ytdl-patched\CONTRIBUTING.md` .

**Comment by meganrogge** [comment] 2021-02-24 20:55
Duplicate of #109895

**Closed** 2021-02-24 20:55 UTC
Labels: *duplicate
