### ISSUE TITLE
 <semantic> TypeScript Server Error (3.8.3)

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#94185] opened 2020-04-01 16:26 UTC
Issue Id: <b>90f97e90-0b64-756e-dbbe-a77101e9129d</b><br /><br />*Versions* <br />- 1.43.2<br />-  5996fb81591e92fd0c547dc45e3f0350026d5962<br />-  6cf3dd97465b2f4f666b66758991d720e003b0f4<br />-  708b019bb4e20f07cf89df9f1d943af3d38d7a70<br />-  78a4c91400152c0f27ba4d363eb56d2835f9903a<br />-  b7bfce30be3c30aa2c33fbe94fe82b81d4105668<br />-  e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c<br />-  fc14315c37f3017af937270532ae2adfbdb6b45f<br />-  fe22a9645b44368865c0ba92e2fb881ff1afce94<br />-  1876b51870e30e9ba8f35dc0dcfaf49a3799a8ef<br />-  1df23554b2e3d5f1efc6fbc76ee61d3f7f186c6d<br />-  3943d614597f9f7c384846613d417e97ea6d5ab4<br />-  798481c7978af034b054e14ace4e471e7a83f665<br />-  b0791e5236f462fbb785e9a00319705607cefb9d<br />-  b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0<br />-  c47d83b293181d9be64f27ff093689e8e7aed054<br />-  cfb0aa1e08f59a56c246925e075ac6d6bd19bb18<br />-  efd7548df65de8e775015b67863190e6bd4934fc<br />-  073a24de05773f2261f89172987002dc0ae2f1cd<br />-  64b65cf8e401cb98d4ddfc8324cb6635ff6fc2ed<br />-  c0eea2a712471a4d242d15704cfa968241d63280<br />-  2f3fe9c9c36f935ec83113ef749d1a62ff7d07b6<br />-  9579eda04fdb3a9bba2750f15193e5fafe16b959<br />-  d1c48c103cabc6e729f59787c0b9c86fb3d39e73<br />-  ef75c4bb445e5021065cf0012cfa2c66e55bfa16<br />-  0926b534553f3ff2f0cff0a741550a97df199706<br />-  ae08d5460b5a45169385ff3fd44208f431992451<br />-  5d18ad4c5902e3bddbc9f78da82dfc2ac349e908<br />-  13b38d2a494612ace32c4fb878824d6329d4c51e<br />-  d7d1147d6b764a48b789000c03088ee9afabcd8a<br />*Stack* <br />Error: <semantic> TypeScript Server Error (3.8.3)<br />Cannot read property 'languageServiceRefCount' of undefined<br />TypeError: Cannot read property 'languageServiceRefCount' of undefined<br />    at releaseDocumentWithKey (tsserver.js:112241:13)<br />    at Object.releaseDocument (tsserver.js:112236:20)<br />    at tsserver.js:135319:45<br />    at Object.forEach (tsserver.js:167:30)<br />    at Proxy.dispose (tsserver.js:135318:20)<br />    at InferredProject.Project.close (tsserver.js:139542:38)<br />    at InferredProject.close (tsserver.js:140420:40)<br />    at ProjectService.removeProject (tsserver.js:141660:25)<br />    at ProjectService.cleanupAfterOpeningFile (tsserver.js:143206:30)<br />    at ProjectService.applyChangesInOpenFiles (tsserver.js:143404:26)<br />    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)<br />    at tsserver.js:146003:88<br />    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)<br />    at IOSession.Session.executeCommand (tsserver.js:146003:33)<br />    at IOSession.Session.onMessage (tsserver.js:14602<br />

**Comment by mjbvz** [comment] 2020-04-02 17:41
Duplicate of https://github.com/microsoft/TypeScript/issues/36453

**Closed by mjbvz** 2020-04-02 17:41 UTC
