### ISSUE TITLE
Problem tab shows problems but not listing any

### ISSUE THREAD

**Issue by kpinel** [Microsoft/vscode#66802] opened 2019-01-20 10:11 UTC
Issue Type: <b>Bug</b>

After the application has been open for a few hours, the tab still reports issues but there are none listed.
![image](https://user-images.githubusercontent.com/875143/51437849-778cfa00-1cef-11e9-8854-cf18fd1af312.png)

No error is displayed and the only log with errors is Log (Window), 7 hours after a successful start.
[2019-01-20 19:57:11.430] [renderer1] [error] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/home/kevin/Documents/PowerShell/Exchange/o365/Provisioning/Helpers", query: "", fragment: ""}: Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/home/kevin/Documents/PowerShell/Exchange/o365/Provisioning/Helpers", query: "", fragment: ""}
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:132:15
    at t.e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:132:795)
    at new t (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:134:369)
    at t.e.with (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:133:521)
    at Object.t.dirname (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:154:444)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4691:942)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:957:244)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:872:762)
    at e.insertItemInDOM (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:439:931)
    at e.render (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:439:260)
    at e.onScroll (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:444:192)
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:189:532)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:419:443
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:189:512)
    at t._setState (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:294:581)
    at t.setScrollDimensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:292:697)
    at t.setScrollDimensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:421:710)
    at e.layout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:438:592)
    at e.layout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:879:962)
    at i.e.layout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:961:900)
    at t.layout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4699:654)
    at o.t.showComposite (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5151:901)
    at o.t.doOpenComposite (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5149:463)
    at o.t.openComposite (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5148:977)
    at o.openPanel (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5201:39)
    at HTMLAnchorElement.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4252:408)
The current workaround is to close and re-open the window

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 1277)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (2.32GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-PSStackoverflow|Dou|0.0.2
csharp|ms-|1.17.1
PowerShell|ms-|1.10.2

</details>

**Comment by sandy081** [comment] 2019-01-29 23:12
@kpinel Can you please provide any steps to reproduce this?

**Comment by kpinel** [comment] 2019-01-30 11:39
@sandy081 Unfortunately, no It has just been happening and it has happened again on opening VS Code. I don't recall it happening on my Windows machine so it could be a Linux issue.
This line containing *Check-DomainController...* should show up as a warning as it is using an unapproved verb. It would seem like it is being picked up but there is nothing in the problem window
![image](https://user-images.githubusercontent.com/875143/51978523-22fb3300-24d6-11e9-9077-a0abee13045a.png)
Again, the log (window) on start. The error seems to be the same as before
[2019-01-30 21:23:43.507] [renderer1] [info] standard startup
[2019-01-30 21:24:21.545] [renderer1] [error] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/home/kevin/Documents/PowerShell/Exchange/o365/Provisioning/Legacy Scripts", query: "", fragment: ""}: Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/home/kevin/Documents/PowerShell/Exchange/o365/Provisioning/Legacy Scripts", query: "", fragment: ""}
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:132:15
    at t.e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:132:795)
    at new t (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:134:369)
    at t.e.with (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:133:521)
    at Object.t.dirname (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:154:444)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4691:942)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:957:244)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:872:762)
    at e.insertItemInDOM (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:439:931)
    at e.render (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:439:260)
    at e.onScroll (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:444:192)
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:189:532)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:419:443
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:189:512)
    at t._setState (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:294:581)
    at t.setScrollDimensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:292:697)
    at t.setScrollDimensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:421:710)
    at e.layout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:438:592)
    at e.layout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:879:962)
    at i.e.layout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:961:900)
    at t.layout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4699:654)
    at o.t.showComposite (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5151:901)
    at o.t.doOpenComposite (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5149:463)
    at o.t.openComposite (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5148:977)
    at o.openPanel (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5201:39)
    at HTMLAnchorElement.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4252:408)
[2019-01-30 21:25:30.986] [renderer1] [error] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/home/kevin/Documents/PowerShell/Exchange/o365/Provisioning/Legacy Scripts", query: "", fragment: ""}: Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/home/kevin/Documents/PowerShell/Exchange/o365/Provisioning/Legacy Scripts", query: "", fragment: ""}
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:132:15
    at t.e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:132:795)
    at new t (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:134:369)
    at t.e.with (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:133:521)
    at Object.t.dirname (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:154:444)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4691:942)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:957:244)
    at e.renderElement (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:872:762)
    at e.insertItemInDOM (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:439:931)
    at e.render (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:439:260)
    at e.onScroll (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:444:192)
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:189:532)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:419:443
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:189:512)
    at t._setState (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:294:581)
    at t.setScrollDimensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:292:697)
    at t.setScrollDimensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:421:710)
    at e._runner (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:437:557)
    at e.execute (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:233:858)
    at o (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:234:49)

this seems related but unsure as to whether they had the same visual issues
https://github.com/Microsoft/vscode/issues/58566

**Comment by sandy081** [comment] 2019-02-05 14:18
@jrieken Looks like the maker's resource is not having a scheme. I thought we do not let invalid URIs to enter?

**Comment by jrieken** [comment] 2019-02-05 14:37
We warn on the extension host side, we explode on the main side... We should probably be more strict by now...

**Comment by sandy081** [comment] 2019-02-05 15:17
I will try to repro it and see whether we are allowing it or not on ext host side.

**Comment by jrieken** [comment] 2019-02-08 15:44
```
[error] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/home/kevin/Documents/PowerShell/Exchange/o365/Provisioning/Helpers", query: "", fragment: ""}:
```

🔝 that's the culprit. @kpinel with what extension/on what files is that happening?

**Comment by jrieken** [comment] 2019-02-08 17:04
@sandy081 I have pushed a change that enforces strict uri creation

**Comment by jrieken** [comment] 2019-02-11 11:36
and I have pushed the revert for that... @eamodio strict uris break GitLens and while we have revert the change for now, be warned. Will have stricter uris, esp disallow empty uris. Ideas

* `Uri.parse('')` will always throw
* `Uri.parse('/some/path')` will warn you and create fake a `file`-uri, e.g `file:///some/path`, because that's closest to what we think we wanna achieve
* `Uri.parse('/some/path', {strict: true} )` will throw

**Comment by eamodio** [comment] 2019-02-12 21:31
@jrieken is this just for `parse` calls? I've looked through GitLens' usages and I'm not sure why there should be any failures. Do you have an example that fails? or is there something I can turn on to test things with strict on?

**Comment by jrieken** [comment] 2019-02-13 07:34
Yeah, it comes via `parse`, without strict or anything. It seems to be an empty uri, e.g. `Uri.parse('')`, and today that causes a warning to be printed on the console.

**Comment by jrieken** [comment] 2019-02-13 07:53
@eamodio this is the stack trace that I am seeing

```
[Extension Host] Here is the error stack:  Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
	at _validateUri (/Users/jrieken/Code/vscode/out/vs/base/common/uri.js:25:23)
	at new URI (/Users/jrieken/Code/vscode/out/vs/base/common/uri.js:128:17)
	at new gitUri_GitUri (/Users/jrieken/.vscode-oss-dev/extensions/eamodio.gitlens-9.5.0/dist/extension.js:1:242882)
	at Module.<anonymous> (/Users/jrieken/.vscode-oss-dev/extensions/eamodio.gitlens-9.5.0/dist/extension.js:1:409930)
	at i (/Users/jrieken/.vscode-oss-dev/extensions/eamodio.gitlens-9.5.0/dist/extension.js:1:279)
	at /Users/jrieken/.vscode-oss-dev/extensions/eamodio.gitlens-9.5.0/dist/extension.js:1:1078
	at Object.<anonymous> (/Users/jrieken/.vscode-oss-dev/extensions/eamodio.gitlens-9.5.0/dist/extension.js:1:1089)
	at Object.<anonymous> (/Users/jrieken/.vscode-oss-dev/extensions/eamodio.gitlens-9.5.0/dist/extension.js:3:3)
	at Module._compile (internal/modules/cjs/loader.js:711:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
```

**Comment by eamodio** [comment] 2019-02-14 16:03
@jrieken The issue should be fixed in GitLens 9.5.1. sorry for that issue

**Comment by jrieken** [comment] 2019-02-26 11:32
Moving this to March

**Comment by jrieken** [comment] 2019-03-04 11:25
There is now

* `Uri.parse(value: string, strict: boolean)` and when using `strict` an error is thrown when no `scheme` can be parsed
* when not being strict we default to the `file` scheme and we print a trace message

**Closed by jrieken** 2019-03-04 11:25 UTC
Labels: bug, error-list, uri
