### ISSUE TITLE
format typescript

### ISSUE THREAD

**Issue by ltaitFactorymind** [Microsoft/vscode#56802] opened 2018-08-20 08:36 UTC
Issue Type: <b>Bug</b>

There is no document formatter for 'typescript'-files installed.

VS Code version: Code - Insiders 1.27.0-insider (00649474f2e43a84c61ddbbbc356060257328372, 2018-08-20T05:19:14.319Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
tslint|eg2|1.0.36
beautify|Hoo|1.3.2
jbockle-format-files|jbo|1.0.2
notepadplusplus-keybindings|ms-|1.0.2
PowerShell|ms-|1.8.3

</details>

**Comment by mjbvz** [comment] 2018-08-20 09:17
Duplicate of #56792

**Closed by mjbvz** 2018-08-20 09:17 UTC
Labels: typescript
