### ISSUE TITLE
Settings sync fails

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#101680] opened 2020-07-03 14:28 UTC
Issue Type: <b>Bug</b>

I woke up my work Mac today and it said settings was turned off "from another device" which I don't recall doing.  I tried re-enabling it, re-login to last login used and get error 

```
Error while starting Sync: GET request 'https://vscode-sync.trafficmanager.net/v1/resource/settings/latest' failed because of too many requests (429).
```

VS Code version: Code - Insiders 1.47.0-insider (376d9d9d785ccca128fdbb16f001446d0ad64d32, 2020-07-03T10:26:01.724Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|-psn_0_8484887|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|1.6.2
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
ng-template|Ang|0.1000.2
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.1.4
vscode-eslint|dba|2.1.5
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
todo-tree|Gru|0.0.177
rainbow-csv|mec|1.7.0
ecdc|mit|1.3.0
HTMLHint|mka|0.8.0
theme-monokai-pro-vscode|mon|1.1.17
js-debug-companion|ms-|1.0.2
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|12.0.0
angular-component-extension|oni|0.0.14
vscode-versionlens|pfl|1.0.8
quicktype|qui|12.0.46
format-html-in-php|rif|1.6.2
code-settings-sync|Sha|3.4.3
rewrap|stk|1.12.0
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.1.1
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.1.0

(3 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-07-03 16:19
Looks like duplicate of #101504

There were previous issues, but that has more discussions and info.

**Closed** 2020-07-06 07:08 UTC
Labels: *duplicate
