### ISSUE TITLE
Display bug in the main menu in the software.

### ISSUE THREAD

**Issue by m0535541178** [microsoft/vscode#159803] opened 2022-09-01 20:30 UTC
Type: <b>Bug</b>

In the latest update, the window action icons in Windows (close minimize and expand) hide part of the top menu in the software, and prevent access to the file tab.
![1](https://user-images.githubusercontent.com/88253247/188007903-db675a6d-802a-461c-aed2-b2a5f8743791.png)

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by Orenico10** [comment] 2022-09-01 22:20
same issue here, I didn't see this issue ticket was open before I opened mine so there is a duplicate one

**Comment by mjbvz** [comment] 2022-09-01 22:21
Duplicate of #159813 (newer but has a more descriptive title)

**Closed by mjbvz** 2022-09-01 22:21 UTC
Labels: new release
