### ISSUE TITLE
Ctrl/Shift Click Should/Did Open a New Window from Recent 

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode#99458] opened 2020-06-05 14:55 UTC
In previous versions of VSCode Shift or Ctrl Click in the File -> Recent Folders menu would open the folder in a new window. This cool feature has disappeared in recent weeks.

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. File -> Recent
2. Ctrl/Shift Click a recent folder
3. Folder should open in a new window - this USED to work

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-06-05 15:10
/duplicate of #76173

Please provide your cases to that thread if something is missing

**Closed** 2020-06-05 15:11 UTC
Labels: *duplicate

**Comment by cawoodm** [comment] 2020-06-05 19:10
@IllusionMH - Erm.. how can this be a duplicate of an issue filed in 2019 if it was working until a few weeks ago and we update vscode weekly??

**Comment by IllusionMH** [comment] 2020-06-05 19:31
@cawoodm I'm sorry. Apparently it actually worked worked but not in cases when I tried last time.

Looks like it is still duplicate but of #97237 which already fixed in Insiders builds.

You can check Insiders build https://code.visualstudio.com/insiders/ or wait [till next week](https://code.visualstudio.com/insiders/) for stable 1.46 release
