### ISSUE TITLE
Separated color themes for different windows?

### ISSUE THREAD

**Issue by 599316527** [Microsoft/vscode#66268] opened 2019-01-09 08:53 UTC
When there are more than one vscode window opened, I'm always confused which window belongs to which folder or project. If there is an option to set color themes for different opened windows temporarily, it's would be more efficient for me to find out the right one which I want to focus on among opened vscode windows.

**Comment by qcz** [comment] 2019-01-09 08:59
What about this extension?
https://marketplace.visualstudio.com/items?itemName=stuart.unique-window-colors

**Comment by RMacfarlane** [comment] 2019-01-09 18:40
Duplicate of https://github.com/Microsoft/vscode/issues/44268

**Closed by RMacfarlane** 2019-01-09 18:40 UTC
