### ISSUE TITLE
In GitHub Codespaces, after copying a file in Explorer, I can only paste that file in Jupyter notebook

### ISSUE THREAD

**Issue by jim-du** [microsoft/vscode#191741] opened 2023-08-30 06:09 UTC
Repro steps:

1. Open GitHub Codespaces, in the Explorer select a file, and press Ctrl-C (or right click - Copy) to copy it.
2. Switch to another tab or application, and copy some random text.
3. Return to Codespaces, and open a Jupyter notebook. When I press Ctrl-V in a markdown or code block, it will paste **the file I copied in step 1**, instead of the text I copied later.
4. Copy some text inside the Jupyter notebook itself, and the clipboard functionality returns to normal.

I can reproduce this in both stable and insider versions.

Not sure if it's relevant, but I installed the Jupyter extension.

Version: 1.82.0-insider
Commit: ebd67244fb2da33ab078bb2baa96106fda29f336
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203
Embedder: codespaces

**Comment by mjbvz** [comment] 2023-08-30 16:18
I believe the root cause is that on web, resource that are copied aren't written to the real clipboard but instead stored in internal state (this is because the web apis don't support writing to the clipboard in this way)

https://github.com/microsoft/vscode/blob/5413247e57fb7e3d29cd36f08266005fe72bbde4/src/vs/platform/clipboard/browser/clipboardService.ts#L154

This means that when you switch to another app and copy some text, VS Code still incorrectly remembers that you have a resource copied and continues using that instead

Not sure how best to workaround this or if the web clipboard api support what we need yet

**Comment by nlvw** [comment] 2023-08-30 20:51
This is probably also related to [https://github.com/microsoft/vscode/issues/185466](https://github.com/microsoft/vscode/issues/185466) which was reported to be fixed in 1.80.0 but for me is still broken in 1.80.2

**Comment by bpasero** [comment] 2023-08-31 08:08
This really sounds the same as https://github.com/microsoft/vscode/issues/185466

I can reproduce the issue. When we copy to clipboard from the explorer we seem to call into this method:

https://github.com/microsoft/vscode/blob/9293e05e89108972c3c70a9326bd454b2a2ea8d3/src/vs/platform/clipboard/browser/clipboardService.ts#L153-L155

And then when you paste into the editor we call `readResources`:

https://github.com/microsoft/vscode/blob/9293e05e89108972c3c70a9326bd454b2a2ea8d3/src/vs/editor/contrib/dropOrPasteInto/browser/copyPasteController.ts#L419

I am not able to reproduce this issue when e.g. pasting into a search input field, so I think this is specific to how the editor handles pasting. I am not sure why this would not reproduce everywhere though.

**Comment by bpasero** [comment] 2024-04-25 08:05
Quite sure this is fixed.

**Closed by bpasero** 2024-04-25 08:05 UTC
Labels: bug, editor-clipboard, confirmed, web
