### ISSUE TITLE
scroll bar choppy

### ISSUE THREAD

**Issue by ebmarquez** [Microsoft/vscode#56366] opened 2018-08-14 14:11 UTC
Issue Type: <b>Bug</b>

Open a powershell file example.psm1.
This contains a single function.
Scroll editor up and down using a touch pad on a first party device.  (SP5)

VS Code version: Code - Insiders 1.26.0-insider (207ace21dfec3dccab52f1296a3880ac7644c978, 2018-08-10T06:49:26.279Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.19.0
githistory|don|0.4.2
gitlens|eam|8.5.4
git-project-manager|fel|1.6.1
prettify-json|moh|0.0.3
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
PowerShell|ms-|1.8.2
vsliveshare|ms-|0.3.535
vscode-docker|Pet|0.1.0
vscode-ansible|vsc|0.3.1
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-08-14 17:05
Duplicate of https://github.com/Microsoft/vscode/issues/13612

**Closed by bpasero** 2018-08-14 17:05 UTC
Labels: editor
