### ISSUE TITLE
vscode 卡死

### ISSUE THREAD

**Issue by bierenjiadehaizi** [Microsoft/vscode#63105] opened 2018-11-14 08:42 UTC
Issue Type: <b>Bug</b>

vscode 使用过程中有规律的卡死

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.37GB free)|
|Process Argv|F:\tuojing\hangzhou\nginx-1.12.2\html\oss-web|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.9
vscode-language-pack-zh-hans|MS-|1.29.2
vetur|oct|0.13.0
vscode-css-peek|pra|2.1.0
vue-vscode-snippets|sdr|1.3.0
background|sha|1.1.19
css-auto-prefix|spo|0.1.7
guides|spy|0.9.2

</details>

**Comment by joseph1125** [comment] 2018-11-14 15:11
Use English next time, duplicate of #62970

**Comment by roblourens** [comment] 2018-11-16 04:55
Please upgrade to 1.29.1 and let me know if this still happens.

**Closed by roblourens** 2018-11-16 04:55 UTC
Labels: freeze-slow-crash, new release
