### ISSUE TITLE
Scroll via CTRL+Up/Down should clamp caret position

### ISSUE THREAD

**Issue by jankrassnigg** [microsoft/vscode#88247] opened 2020-01-07 23:08 UTC
Issue Type: <b>Bug</b>

In Visual Studio when you scroll by holding CTRL+Up/Down keys, the position of the caret is clamped to the currently visible text area. For instance when you scroll down in a document, the caret will stay where it is as long as it doesn't leave the screen, but once it would leave the screen at the top, it will be pushed down to stay in the visible text area. This is extremely useful, as once you stop scrolling, the caret is at least very close to what you are currently looking at and it can be put to the desired position quickly.

In Visual Studio Code, however, the caret stays where it is all the time, even if it ends up off screen by CTRL+Up/Down scrolling. Consequently, when you stop scrolling and then press up/down once more to move the caret, the view area jumps back to the caret position, discarding the scroll position that was just selected. This renders scrolling via CTRL+Up/Down much less useful, as the only way to not lose the scroll position, is to grab the mouse and click into the current view area, before doing anything else via keyboard that may adjust the caret position and reset the view there.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexdima** [comment] 2020-01-17 20:44
Duplicate of #59247

---

You can use the `editorScroll` command in your `keybindings.json`:

e.g.

```
{
	"key": "ctrl+up",
	"when": "editorTextFocus",
	"command": "editorScroll",
	"args": {
		"to": "up", // 'up', 'down'
		"by": "line", // 'line', 'wrappedLine', 'page', 'halfPage'
		"value": 1, // number of units to move
		"revealCursor": true
	}
}
```

**Closed** 2020-01-17 20:45 UTC
Labels: editor-core

**Comment by jankrassnigg** [comment] 2020-01-17 21:06
Great, that's exactly what I want! IMO this should be the default setting, though ;-)

**Comment by alexdima** [comment] 2020-01-17 21:14
@jankrassnigg Perhaps this should be a part of the Visual Studio keymap extension. Can you please open an issue against https://github.com/rebornix/vscode-vs-keybindings ?

**Comment by jankrassnigg** [comment] 2020-01-17 21:17
You mean https://github.com/rebornix/vscode-vs-keybindings/issues/33 ? :D
