### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by riturajbarhgoojer** [Microsoft/vscode#47463] opened 2018-04-09 07:39 UTC
We have written the needed data into your clipboard because it was too large to
Issue Type: <b>Bug</b>

 Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
C:\Users\rituraba>node -v
v8.9.4

Not able to debug the nod app , after upgrading the node versio 6 to 8 .

Launch.Json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "protocol": "inspector",
            "program": "${workspaceFolder}\\server.js"
        }
    ]
}
```

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q8400  @ 2.66GHz (4 x 2660)|
|Memory (System)|6.96GB (1.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
sublime-babel-vscode|jos|0.2.9
csharpfixformat|Leo|0.0.66
csharp|ms-|1.14.0
mono-debug|ms-|0.15.8
node-debug2|ms-|1.19.4
al-formatter|ras|2.1.0

(2 theme extensions excluded)

</details>
 send. Please paste.

**Comment by weinand** [comment] 2018-04-09 08:17
duplicate of #45957

**Closed by weinand** 2018-04-09 08:17 UTC
