### ISSUE TITLE
New title and menu bar glitch on minimize and maximize buttons

### ISSUE THREAD

**Issue by panchalkalpesh** [Microsoft/vscode#60794] opened 2018-10-12 15:41 UTC
- VSCode Version: 1.28.1
- OS Version: Windows 10 Pro (version 1709)
- OS Build: 16299.665

Additional Info:

> Version: 1.28.1 (system setup)
> Commit: 3368db6750222d319c851f6d90eb619d886e08f5
> Date: 2018-10-11T18:13:53.910Z
> Electron: 2.0.9
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64

### Steps to Reproduce:

1. Open VS Code
2. Hover on either minimize or maximize button

Does this issue occur when all extensions are disabled?: **Yes**

### Screenshots:

**Color theme: Dark (Visual Studio)**

Window Active State
![bug1](https://user-images.githubusercontent.com/1808686/46878906-8f143700-ce12-11e8-93a0-9edd9d438c96.PNG)

Hover on minimize button
![bug2](https://user-images.githubusercontent.com/1808686/46879032-e4504880-ce12-11e8-84e2-16b5143c0ba6.PNG)

Hover on maximize button
![bug3](https://user-images.githubusercontent.com/1808686/46879045-eadec000-ce12-11e8-9851-9a8fd1ca4893.PNG)

**Color theme: Light (Visual Studio)**

Window Active State
![bug4](https://user-images.githubusercontent.com/1808686/46879216-6b052580-ce13-11e8-826f-665b6b3c653e.PNG)

Hover on minimize button
![bug5](https://user-images.githubusercontent.com/1808686/46879219-6ccee900-ce13-11e8-9276-23b11745546a.PNG)

Hover on maximize button
![bug6](https://user-images.githubusercontent.com/1808686/46879229-6f314300-ce13-11e8-9704-05cfc33620f3.PNG)

**Comment by sbatten** [comment] 2018-10-18 17:34
I believe this is a duplicate of #60430

**Closed by sbatten** 2018-10-18 17:34 UTC
Labels: new release
