### ISSUE TITLE
touchbar run debug buttons disappear after update

### ISSUE THREAD

**Issue by karunstha** [microsoft/vscode#123105] opened 2021-05-06 10:27 UTC
Issue Type: <b>Bug</b>

There used to appear a run and a debug play icon on the touchbar before the latest update. But now there seems to be a glitch. I get the text autocomplete options in my touch bar while I'm in the editor. But when I go to the problems tab in the buttom, the play and debug buttons shows up for a few milliseconds and then disappear. Please fix. I have the macbook pro m1.

VS Code version: Code 1.56.0 (Universal) (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin arm64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 3|
|Memory (System)|8.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 451631c9-20d5-4769-a404-53f22330ace7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
GetterAndSetterGenerator|afm|1.0.3
vscode-django|bat|1.6.0
dart-code|Dar|3.22.0
flutter|Dar|3.22.0
githistory|don|0.6.16
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
git-project-manager|fel|1.7.1
bloc|Fel|5.6.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
cpptools|ms-|1.3.1
awesome-flutter-snippets|Nas|2.0.4
bootstrap4-vscode|the|6.1.0
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by isidorn** [comment] 2021-05-06 11:52
@karunstha thanks for letting us know. What I see is that if the focus is in the editor the debug touch bar is not there. However if I click on the explorer for example and move focus out of the Editor then the debug run button appears. Is this what you are seeing as well?

Seems like a duplicate of https://github.com/microsoft/vscode/issues/106541
Thus also assigning to @deepak1556 since this seems to have regressed

fyi @bpasero

**Comment by deepak1556** [comment] 2021-05-06 12:10
Sorry about this regression, the patch seems to have been accidentally removed in the internal builds.

**Comment by isidorn** [comment] 2021-05-06 12:23
@deepak1556 no worries, however this might be worth to be a candidate. If the fix is low risk.
Not having it as a candidate is also fine I think.

**Comment by deepak1556** [comment] 2021-05-06 12:49
Getting the fix in time for candidate might not be possible, hence I put it up for regular milestone task.

**Comment by isidorn** [comment] 2021-05-06 14:42
@deepak1556 thanks. Yeah fixing for May works perfectly for me

**Comment by karunstha** [comment] 2021-05-06 16:24
> @karunstha thanks for letting us know. What I see is that if the focus is in the editor the debug touch bar is not there. However if I click on the explorer for example and move focus out of the Editor then the debug run button appears. Is this what you are seeing as well?
> 
> Seems like a duplicate of #106541
> Thus also assigning to @deepak1556 since this seems to have regressed
> 
> fyi @bpasero


Yes that is whats happening. I did not face this problem until the latest update that automatically got installed today.

**Comment by deepak1556** [comment] 2021-05-17 01:35
This is fixed in latest insiders.

\closedWith d17d7ca46cc166b156e91c6205465d7f01826189

**Closed by deepak1556** 2021-05-17 01:35 UTC
Labels: regression, workbench-touchbar
