### ISSUE TITLE
Pasting of files in the project directory in vscode.

### ISSUE THREAD

**Issue by rachit2501** [microsoft/vscode#102242] opened 2020-07-11 19:24 UTC
Ability to paste any file in the project directory, where the file was copied from somewhere, outside of vscode. Currently, we need to open the file manager to this type of copying.

**Comment by IllusionMH** [comment] 2020-07-12 04:03
/duplicate of #164

Also see more info in #89862

**Closed** 2020-07-12 04:04 UTC
Labels: *duplicate
