### ISSUE TITLE
[URGENT] "There are task errors. See the output for details." when providing dynamic tasks

### ISSUE THREAD

**Issue by ivankravets** [Microsoft/vscode#68999] opened 2019-02-19 19:29 UTC
- VSCode Version: 1.32.0-insider#a75cf6e4b4317de0bf38284af255bdf0089deb68
- OS Version: macOS

# Description

[PlatformIO IDE for VSCode](https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide) uses dynamic tasks provider. Every time when a user modifies project configuration, we "dispose" previous `TaskProvider` and provide a new one with updates tasks. See https://github.com/platformio/platformio-vscode-ide/blob/develop/src/tasks.js#L127:L144

It has worked for 6-8 months without any issues. Last time users have started to report different issues, see https://community.platformio.org/t/in-vsc-task-window-always-popping-up-error-no-handler-found/6511/

I've just tried to investigate this issue. It seems that a few latest VSCode releases have broken TaskProvider. So, if we "dispose" previous TaskProvider and register a new, VSCode will complain about "Error: No handler found". Actually, all tasks work without any problems. We see them in UI. Just this "fake" warning window.

# Steps to Reproduce

1. let provider = vscode.tasks.registerTaskProvider(...)
2. provider.dispose()
3. provider = vscode.tasks.registerTaskProvider(...)

Now, try to run any tasks. You will see this error/warning.

# Does this issue occur when all extensions are disabled?

Yes

**Comment by alexr00** [comment] 2019-02-20 08:40
Duplicate of #68486

**Closed** 2019-02-20 08:41 UTC
Labels: *duplicate, tasks
