### ISSUE TITLE
Feature Request: dynamically set "owner" for Watcher\background Tasks .

### ISSUE THREAD

**Issue by gerane** [microsoft/vscode#22242] opened 2017-03-08 19:13 UTC
When using a watcher task to run actions, sometimes you may only want to run an action against that single file instead of the entire project. The problem is that if you have existing matched problems, this will erase existing problem matches since they share the same "owner" property. This issue is referencing this problem #1397

For these types of tasks it would be beneficial to allow the "owner" property to be dynamically set via matcher. One way this could be achieved is via a Pattern Matcher. Using the tsc example from the [Documentation](https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks) it might look something like below.

```json
{
    "version": "0.1.0",
    "command": "tsc",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "watch",
            "args": ["--watch"],
            "isBackground": true,
            "problemMatcher": {
                "fileLocation": "relative",
                "pattern": {
                    "regexp": "^([^\\s].*)\\((\\d+|\\,\\d+|\\d+,\\d+,\\d+,\\d+)\\):\\s+(error|warning|info)\\s+(TS\\d+)\\s*:\\s*(.*)$",
                    "file": 1,
                    "location": 2,
                    "severity": 3,
                    "code": 4,
                    "message": 5,
                    "owner": 1
                },
                "watching": {
                    "activeOnStart": true,
                    "beginsPattern": "^\\s*\\d{1,2}:\\d{1,2}:\\d{1,2}(?: AM| PM)? - File change detected\\. Starting incremental compilation\\.\\.\\.",
                    "endsPattern": "^\\s*\\d{1,2}:\\d{1,2}:\\d{1,2}(?: AM| PM)? - Compilation complete\\. Watching for file changes\\."
                }
            }
        }
    ]
}
```

This just sets the "owner" as the  matched File and removed the "owner" property from  "problemMatcher". This would make it where only problems matched to that file would be cleared when the watcher triggers again.

EDIT: Adding a few gifs showing an example use case.

## Pester Unit Tests - Watcher Runs all Tests

![watchproject](https://cloud.githubusercontent.com/assets/6662208/23720637/d4b794d4-0404-11e7-9091-ad26772f8555.gif)

## Pester Unit Tests - Watcher Runs only Tests for edited file

![singlererun](https://cloud.githubusercontent.com/assets/6662208/23720351/1a7bd0f8-0404-11e7-8b7d-5610740b6eeb.gif)
.

**Comment by alexr00** [comment] 2019-10-10 10:24
Duplicate of https://github.com/microsoft/vscode/issues/1397 since this issue is an implementation detail of that issue.

**Closed** 2019-10-10 10:25 UTC
Labels: *duplicate, feature-request, help wanted, tasks
