### ISSUE TITLE
When use snippets, autocomplete(IntelliSense) won't work

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#93759] opened 2020-03-30 14:25 UTC
Issue Type: <b>Bug</b>

VS
![image](https://user-images.githubusercontent.com/24863266/77923490-17bbb700-72d5-11ea-80aa-938ebad55fae.png)

VS Code
![image](https://user-images.githubusercontent.com/24863266/77923565-328e2b80-72d5-11ea-871c-b2a3ed766a9d.png)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|1.21.15
python|ms-|2020.3.69010
unity-tools|Tob|1.2.3
material-theme|zhu|3.2.4

</details>

**Comment by IllusionMH** [comment] 2020-03-30 15:37
As mentioned in issue suggested by bot:

/duplicate of #89997, which points to the `editor.suggest.snippetsPreventQuickSuggestions` setting.

**Closed** 2020-03-30 15:38 UTC
Labels: *duplicate
