### ISSUE TITLE
Input randomly doesn't work in quick pick and editors

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228232] opened 2024-09-11 13:08 UTC
This has happened once yesterday and once today for me. I open any quick pick (quick search, command palette), type and nothing happens.

In console I see:

![Image](https://github.com/user-attachments/assets/d3499865-8bc7-45c2-b23b-fb92bacd2325)

The same happens when typing into the editor.

I can't get much more information unfortunately since input is very broken. Reloading the window does fix it. I'm guessing it's related to editcontext, even though that setting is disabled.

**Comment by aiday-mar** [comment] 2024-09-11 14:26
Concerning the control+home, control+end issue, when I enable trace level logging, I see the following too in the dev tools:

`TRACE KeybindingService#dispatch ⌘↑ [ No matching keybinding ]`

Not sure if this is somehow related to the edit context, I will investigate

**Comment by aiday-mar** [comment] 2024-09-11 15:49
Initial investigation when the setting is disabled shows that the context key textInputFocus is not updated after the hidden div receives focus. Since the context key value is false, the context keys are evaluated as false and the command is not run. Have to investigate more.

**Comment by aiday-mar** [comment] 2024-09-12 09:16
So after some investigation I have figured out why the input does not work when the setting is enabled. It has to do with the `textInputFocus` context key not being updated correctly.

You mention you saw this happen when the setting is disabled. Do you recall if after you disabled the setting you reloaded the window before seeing this issue? Perhaps it could be the hot reload I added does not work correctly and you were essentially seeing the same error as when the setting is enabled.

**Comment by aiday-mar** [comment] 2024-09-12 09:22
I will keep an eye out for this issue and check if this happens when the setting is disabled

**Comment by aiday-mar** [comment] 2024-09-12 15:04
I have merged two PRs that tackle focusing issues with the edit context:

https://github.com/microsoft/vscode/pull/228348
https://github.com/microsoft/vscode/pull/228325

I suspect the issue you saw is related to incorrect focusing too. Since I was not able to reproduce the issue without the setting enabled, let me know if you still see this happening starting from tomorrow's Insiders.

**Comment by aiday-mar** [comment] 2024-11-04 08:34
This will be closed as this issue is no longer seen

**Closed by aiday-mar** 2024-11-04 08:34 UTC
Labels: important
