### ISSUE TITLE
Multi-cursor editing misplacement

### ISSUE THREAD

**Issue by hectorqin** [microsoft/vscode#82196] opened 2019-10-10 03:05 UTC
- 版本: 1.39.0
- 提交: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
- 日期: 2019-10-09T06:57:43.593Z
- Electron: 4.2.10
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Press `⌘F2` to select all occurrences of current word
2. Press `->` / `<-` to adjust placement. Some cursors are in the wrong place.

Does this issue occur when all extensions are disabled?: Yes

**Comment by hectorqin** [comment] 2019-10-10 03:10
[Gif](https://file.io/AD82NQ)

**Comment by alexandrudima** [comment] 2019-10-10 07:36
Multiple columns work on the wrapped space, not on the original space ... Duplicate of #26393

**Closed by alexandrudima** 2019-10-10 07:36 UTC
