### ISSUE TITLE
Save All No Longer Working in v1.57

### ISSUE THREAD

**Issue by bastecklein** [microsoft/vscode#126133] opened 2021-06-12 15:13 UTC
Just got the update to v1.57, and the "Save All" function is now always grayed out, no matter what.  In addition, the app no longer seems to mark on the left explorer sidebar which files have been modified.  This is on the M1 Mac edition of VS Code, on an M1 Macbook Air.  

This issue is pretty significant on a large complicated workspace.

**Comment by ArturoDent** [comment] 2021-06-12 20:05
It doesn't appear to be happening on W10.

**Comment by bastecklein** [comment] 2021-06-12 20:55
This problem seems to be intermittent, and I have not been able to determine how to accurately reproduce it.  Just a bit ago, the Save All function was again gone, but this time I switched to a different window (MS Edge) then switched back to VS Code, and Save All reappeared.  I did not change anything else.  I am wondering if it has something to do with the re-drawing of the menu in Electron, and maybe switching windows triggers it to set the menu again?  I will post again if I notice any other patterns.

**Comment by thekeogh** [comment] 2021-06-14 03:48
I got the same issue here on `1.57` also. I've seen the **Save All** function enabled once... kinda randomly. The rest of the time it's incorrectly disabled.

I currently have no way to replicate as well... I'll update here if I find how to replicate this.

**Comment by ease** [comment] 2021-06-14 13:52
It's very annoying. Can confirm it on:
Version: 1.57.0
OS: Darwin x64 20.5.0 (MacOS Big Sur 11.4)

**Comment by Vannevelj** [comment] 2021-06-14 14:10
I'm seeing the same thing on my Windows & Mac.

![image](https://user-images.githubusercontent.com/2777107/121905941-89d5bb80-cd22-11eb-8b49-aeca0f1392b1.png)

![image](https://user-images.githubusercontent.com/2777107/121906016-9ce88b80-cd22-11eb-9494-59cfdc082ab1.png)

**Comment by mvoorberg** [comment] 2021-06-14 17:34
Same problems on Ubuntu 20.04 LTS

Save All stopped working after the update to 1.57.0. 

Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.14-050814-generic snap

**Comment by davidbfrogman** [comment] 2021-06-17 14:28
Same Problem

**Comment by bpasero** [comment] 2021-06-20 07:25
@sbatten could this be related to your menu changes? I can easily reproduce:
* open a window (no dirty files)
* File > Save All is disabled (expected)
* make files dirty
* action is still disabled

We register the action with a precondition that seems to work when I tested (i.e. the state updates):

https://github.com/microsoft/vscode/blob/a476c9d4f08ea6d59b1d9b87f13d2e60c960253b/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L633-L633

**Comment by random-internet-guy** [comment] 2021-06-21 03:12
Just going to add a "Me too" to this. Can't reproduce. Seems to work once and then not again. Restart fixes it
Version: 1.58.0-insider
Commit: 7dea6d7402b55671410a129661cad24b55aed9f4

**Comment by sbatten** [comment] 2021-06-21 16:41
@bpasero yes, when the top level entries change the menu change listeners get orphaned and not updated in the native menu. pushed a fix in insiders. should probably take as a candidate if we have another recovery.

**Closed** 2021-06-21 16:40 UTC
Labels: important, menus, regression

**Comment by JF0001** [comment] 2021-07-03 21:35
Will there be a patch to solve this issue? Also experiencing it on Ubuntu 20.04.

**Comment by JF0001** [comment] 2021-07-09 14:29
Thank you @gjsjohnmurray
