### ISSUE TITLE
Extension host terminated unexpectedly 3 times within the last 5 minutes.

### ISSUE THREAD

**Issue by Kotpes** [microsoft/vscode#176733] opened 2023-03-10 07:42 UTC
Type: <b>Bug</b>

Extension host terminated unexpectedly 3 times within the last 5 minutes.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 12, 11|
|Memory (System)|64.00GB (1.41GB free)|
|Process Argv|--crash-reporter-id 7bc38f73-b002-495b-aeac-670400608fc2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.11
better-toml|bun|0.3.2
vscode-eslint|dba|2.4.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
codespaces|Git|1.13.10
copilot|Git|1.77.9225
raythis|Goo|1.1.0
vscode-graphql|Gra|0.8.6
vscode-graphql-syntax|Gra|1.1.0
styled-components-snippets|jon|0.10.0
syntax-project-pbxproj|mar|0.1.3
web-accessibility|Max|0.2.83
dotenv|mik|1.0.1
vscode-dotnet-runtime|ms-|1.6.0
makefile-tools|ms-|0.6.0
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5834
vscode-react-native|msj|1.10.2
color-highlight|nau|2.5.0
vscode-jest|Ort|5.2.3
vscode-yaml|red|1.12.1
vscode-styled-components|sty|1.7.5
vscode-gradle|vsc|3.12.6
vscode-icons|vsc|12.2.0
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
pythonb192:30669360
funwalk2cf:30682975

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:17
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:17 UTC
Labels: freeze-slow-crash-leak, extension-host
