### ISSUE TITLE
100%+ CPU usage from "Code Helper". 

### ISSUE THREAD

**Issue by lukasz-formela** [Microsoft/vscode#72002] opened 2019-04-09 14:53 UTC
Issue Type: <b>Performance Issue</b>

From my research it can be something about "files.watcherExclude".

After running my VSCode instance ( many files in the folder that I open with it ) the fans start to roll out that 6k RPM and CPU goes to 100% usage. 

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.66GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    98	   284	code main
    0	    98	   390	   gpu-process
    0	    98	   423	   shared-process
    0	   377	  1132	   window (Settings — Projects)
    0	     0	  1133	     /bin/bash -l
    0	    66	  1137	     watcherService
    0	    98	  1411	   window (Issue Reporter)
    0	     0	  1413	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings — Projects)
|    Folder (Projects): more than 25639 files
|      File types: php(11366) png(5538) js(1741) scss(1128) css(894) svg(526)
|                  md(434) gif(414) eps(340) json(321)
|      Conf files: gulp.js(27) makefile(9) settings.json(1) package.json(1);
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-lint|ada|0.1.8
conflict-squeezer|ang|1.0.1
vagrant|bbe|0.5.0
vscode-tailwindcss|bra|0.1.16
gitlens|eam|9.6.0
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
html-slim-scss-css-class-completion|gen|1.5.14
beautify|Hoo|1.4.11
githd|hui|2.1.0
html-tag-wrapper|hwe|0.2.3
composer|ika|0.7.1
code-beautifier|mic|2.2.1
live-sass|rit|3.0.0
LiveServer|rit|5.5.1
laravel-artisan|rya|0.0.25
git-merger|sha|0.4.1
highlight-matching-tag|vin|0.9.1

(1 theme extensions excluded)

</details>

**Comment by lukasz-formela** [comment] 2019-04-09 15:40
<img width="670" alt="Zrzut ekranu 2019-04-9 o 17 40 00" src="https://user-images.githubusercontent.com/48242560/55814319-8a44ed00-5aee-11e9-9a3c-a973c55c8058.png">

Was worth a shot but sadly didn't help.
In two minutes after opening VS code it goes to 4th density mode.

**Comment by lukasz-formela** [comment] 2019-04-09 15:45
https://github.com/Microsoft/vscode/issues/3998#issuecomment-474293025

I added the suggested temp folder but still there's no change.
`**/tmp/**`

**Comment by steveoOn** [comment] 2019-04-10 04:19
the same issue happened in my macOS 10.14.4, vscode version 1.33.0, now I can only use the old version 1.32.3 and disabled the automatic update. Tried "files.watcherExclude" but nothing changed.

**Comment by soorajvnair** [comment] 2019-04-10 05:44
Yes. Same here. Switched to an insiders build, works fine.

**Comment by bpasero** [comment] 2019-04-10 08:39
![image](https://user-images.githubusercontent.com/900690/55864524-fb32e600-5b7c-11e9-8b13-096e0391cdec.png)

**Comment by lukasz-formela** [comment] 2019-04-10 08:46
A little additional info:
If there is a chance to see what changed with last update (i don't mean
changes overall, but to my instancje of vs studio- like a log/historyczne
what was added with update).
It all started with me updating VS Code.

śr., 10.04.2019, 10:41 użytkownik Benjamin Pasero <notifications@github.com>
napisał:

**Comment by jrieken** [comment] 2019-04-10 08:47
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by gi** [comment] 2019-04-10 18:16
Hey all, I had the same issue after upgrading to version 1.33, but after letting the program run for a little while, the CPU usage is now back to normal.

**Comment by lukasz-formela** [comment] 2019-04-11 13:08
> Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions. Thanks.

What if: 
[Public-<name>:~ <name>$ code --inspect-extensions=9993
-bash: code: command not found] ?

**Comment by ddzy** [comment] 2019-04-13 10:00
> Issue Type: Performance Issue
> 
> From my research it can be something about "files.watcherExclude".
> 
> After running my VSCode instance ( many files in the folder that I open with it ) the fans start to roll out that 6k RPM and CPU goes to 100% usage.
> 
> VS Code version: Code 1.33.0 ([0dd516d](https://github.com/Microsoft/vscode/commit/0dd516dd412d42323fc3464531b1c715d51c4c1a), 2019-04-04T15:11:32.076Z)
> OS version: Darwin x64 18.5.0
> 
> System Info
> Process Info
> Workspace Info
> Extensions (18)

Same issue([#67150](https://github.com/Microsoft/vscode/issues/67150))

**Comment by Chazie9** [comment] 2019-04-15 05:20
I'm having the same issue with Version 1.33.0 (1.33.0), MacOS: Version 10.13.6  I am running multiple, but CPU is 133 and spikes to 220 sometimes....

**Comment by jrieken** [comment] 2019-04-15 07:33
same info needed: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by lukasz-formela** [comment] 2019-04-15 07:33
Small update: 
Overheating starts when 'Initializing JS/TS language features'.
I'll try to follow @jrieken instructions.

**Comment by jrieken** [comment] 2019-04-15 07:38
❗️ and everyone update to 1.33.1 first, there has been an issue with TS/JS which might have caused this

**Comment by lukasz-formela** [comment] 2019-04-15 08:17
> ❗️ and everyone update to 1.33.1 first, there has been an issue with TS/JS which might have caused this

Updated today, still experiencing the issue occuring. 


Here's the file you asked for: 
[CPU-20190415T081025.506Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/3079080/CPU-20190415T081025.506Z.cpuprofile.txt)

**Comment by jrieken** [comment] 2019-04-15 08:28
@lukasz-formela What is your list of installed extensions? (`code --list-extensions`)

**Comment by lukasz-formela** [comment] 2019-04-15 08:38
As listed below:
```
adamwalzer.scss-lint
akamud.vscode-theme-onedark
angelomollame.conflict-squeezer
bbenoist.vagrant
bradlc.vscode-tailwindcss
eamodio.gitlens
ecmel.vscode-html-css
formulahendry.auto-close-tag
gencer.html-slim-scss-css-class-completion
HookyQR.beautify
huizhou.githd
humao.rest-client
hwencc.html-tag-wrapper
ikappas.composer
michelemelluso.code-beautifier
octref.vetur
oderwat.indent-rainbow
ritwickdey.live-sass
ritwickdey.LiveServer
ryannaddy.laravel-artisan
shaharkazaz.git-merger
vincaslt.highlight-matching-tag
```

**Comment by jrieken** [comment] 2019-04-15 09:57
> A remark: I remember code being stuck with scss files at some point while opening big project.

That sounds reasonable, the CPU profile point to S?CSS parsing and it will then be one your installed extensions (maybe scss-lint). There is nothing we can do here, except asking you file an issue against the extension.

**Comment by GeorgiosP** [comment] 2019-04-17 13:37
code helper seems to be consuming 100% of cpu with no extensions included. 😕

**Comment by jrieken** [comment] 2019-04-17 14:04
I am closing this as caused by extension because the only actionable [provided information](https://github.com/Microsoft/vscode/issues/72002#issuecomment-483153725) is from @lukasz-formela and the profile showed that this is an extension. 

Unfortunately, other me-too-comments without further information aren't actionable.

**Closed** 2019-04-17 14:04 UTC
Labels: *caused-by-extension, needs more info
