### ISSUE TITLE
Don't Expand Collapsed Code on Format

### ISSUE THREAD

**Issue by TylerStacie2005** [Microsoft/vscode#51101] opened 2018-06-04 18:47 UTC
Issue Type: <b>Feature Request</b>

When I format code with ctrl-k ctrl-f, it would be nice if the code that was formatted didn't automatically get expanded.  I keep things I'm not working on collapsed, and formatting expands it all again.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

**Comment by aeschli** [comment] 2018-09-17 10:27
duplicate of #54266

**Closed by aeschli** 2018-09-17 10:27 UTC
Labels: needs more info
