### ISSUE TITLE
Command to maximize current view vertically

### ISSUE THREAD

**Issue by akshaal** [Microsoft/vscode#69837] opened 2019-03-05 11:30 UTC
A command to collapse all views inside the sidebar (Explorer) except the currently focused one. Useful, for example, when the vertical space is limited but you still want to use both files and outline views.

**Comment by sandy081** [comment] 2019-03-06 09:00
Duplicate of https://github.com/Microsoft/vscode/issues/48201

**Closed** 2019-03-06 09:00 UTC
Labels: *duplicate, explorer-custom
