### ISSUE TITLE
I hope vscode can index javascript functions in html files

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5518] opened 2016-04-20 00:45 UTC
We known the sublime can index javascript functions in html files but vscode can not index javascript functions in html files.

**Comment by mjbvz** [comment] 2016-11-18 22:29
Closing this as a duplicate of #3465, which tracks supporting intellisense and other language features for js inside of html script tags.

**Closed by mjbvz** 2016-11-18 22:29 UTC
Labels: duplicate, feature-request, js
