### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by cpertile** [microsoft/vscode#134061] opened 2021-09-28 21:32 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.0-dev.20210927

**Steps to reproduce crash**
1. Open VSCode with extension "Typescript and Javascript Language Features enabled" and any React repo cloned
2. Wait

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:56697:22)
    at getPropertyOfType (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:57347:24)
    at tryGetQualifiedNameAsValue (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:49165:26)
    at resolveEntityName (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:49222:133)
    at getSymbolOfPartOfRightHandSideOfImportEquals (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:49145:24)
    at getTargetOfImportEqualsDeclaration (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:48614:28)
    at getTargetOfAliasDeclaration (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:48964:28)
    at resolveAlias (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:49013:30)
    at resolveSymbol (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:49003:67)
    at mergeSymbol (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:47375:42)
    at c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:47490:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:47488:20)
    at mergeSymbol (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:47399:21)
    at c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:47490:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:47488:20)
    at initializeTypeChecker (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:84454:21)
    at Object.createTypeChecker (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:47152:9)
    at Object.getTypeChecker (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:113871:79)
    at synchronizeHostData (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:158641:21)
    at Object.getProgram (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:158762:13)
    at AutoImportProviderProject.Project.updateGraphWorker (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:163770:53)
    at AutoImportProviderProject.Project.updateGraph (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:163699:42)
    at AutoImportProviderProject.updateGraph (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:164544:70)
    at Object.updateProjectIfDirty (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:165181:45)
    at InferredProject.Project.getPackageJsonAutoImportProvider (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:164319:32)
    at InferredProject.Project.updateGraph (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:163737:26)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:165876:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:167565:26)
    at c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:167839:97
    at Object.flatMap (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:519:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:167839:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:168997:46)
    at c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:170928:88
    at IOSession.Session.executeWithRequestId (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:170919:28)
    at IOSession.Session.executeCommand (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:170928:33)
    at IOSession.Session.onMessage (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:170954:35)
    at Interface.<anonymous> (c:\Users\Cleberson\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20210927\node_modules\typescript\lib\tsserver.js:173559:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.18GB free)|
|Process Argv|--crash-reporter-id 35adcf57-b496-448a-bc4d-1efefc27b27f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
node-essentials|afr|1.1.0
atlascode|atl|2.9.1
color-info|bie|0.7.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.25
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
vscode-pull-request-github|Git|0.30.0
vscode-styled-components|jpo|1.6.6
dotenv|mik|1.0.1
vscode-typescript-next|ms-|4.5.20210927
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.10.0
fabric8-analytics|red|0.3.3
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
rocketseatreactjs|roc|3.0.2
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
JavaScriptSnippets|xab|1.8.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791

```

</details>

**Comment by mjbvz** [comment] 2021-09-29 00:12
Duplicate of https://github.com/microsoft/TypeScript/issues/45874

**Closed by mjbvz** 2021-09-29 00:12 UTC
