### ISSUE TITLE
extensions viewlet: Clicking uninstall seems broken

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#67393] opened 2019-01-29 12:03 UTC
Testing #66910

- install eamodio.remotehub
- restart code and open from console with `code-insiders --folder-uri remotehub://github/Micorosoft/vscode-nls`
- in the explorer, note that the title shows `VSCODE-NLS (REMOTEHUB)`
- install the `aeschli.remotehub-companion` [vsix (remove zip file extension)](https://github.com/Microsoft/vscode/files/2807533/remotehub-companion-0.0.1.vsix.zip). It contains only a `resourceLabelFormatters` contribution, which is a dynamic contribution point
- reload (I filed issue #67389 for that)
- explorer label has already changed to `VSCODE-NLS (GI*)`, that means the contribution has received a delta
- in the extensions viewlet  click 'uninstall' on the remotehub-companion extension
- all buttons go away, no sign that the extension is removed

- ~~explorer label still shows `VSCODE-NLS (GI*)` (probably a duplicate of #67391)~~

**Comment by sandy081** [comment] 2019-01-29 14:37
Strike-out last line as it is not related to this issue

**Comment by sandy081** [comment] 2019-01-29 16:57
Actually this is duplicate of #66931

**Closed** 2019-01-29 16:57 UTC
Labels: *duplicate, bug, extensions
