### ISSUE TITLE
Remember all UI state even when reopening window without workspace

### ISSUE THREAD

**Issue by brenthuisman** [Microsoft/vscode#207] opened 2015-11-19 12:41 UTC
Currently, reopen files behaviour is slightly weird. If no folders are open, no files are reopened upon restart of VSC. If a folder is open, any files that are opened, inside the opened folder or not, are reopened upon restart of VSC.

I would like to see VSC reopen files, regardless the opened folder count. Should probably be settable in the preferences, I can imagine not everyone is interested in this behaviour.

**Comment by bpasero** [comment] 2015-11-19 12:54
Fair request.

**Comment by PooLP** [comment] 2015-11-19 13:36
+1

**Comment by nchammas** [comment] 2015-12-02 03:23
Not sure about the scope of this issue, but I have a related problem. Let me know if I should report it in a separate issue.

If I have multiple projects open in VS Code (e.g. 2 separate windows, each with a folder loaded) and I restart VS Code (e.g. due to an update), only the last project that was opened gets automatically reloaded.

I think it should be on VS Code to completely restore the UI state after a restart. Chrome, for example, does this--it reloads both the correct number of windows, as well as the correct tabs within each window.

I understand from the discussion in #264 that there is some issue with restoring state for standalone files that are opened (as opposed folders), but in my case it was 2 folders that were open.

I'm running Code 0.10.3 on OS X.

**Comment by bpasero** [comment] 2015-12-02 06:37
@nchammas you can enable restoring of all windows through the `window.reopenFolders` setting. Set it to `all` and you should be all set.

**Comment by nchammas** [comment] 2015-12-02 16:59
Oh snap. Good call--that did the job. :+1:

**Comment by nemo22** [comment] 2016-04-21 10:37
So if  no folders are open, opened files are not reopened after restart VSC? A bit dumb.

**Comment by bpasero** [comment] 2016-04-21 10:41
Yes, only if you open a folder we remember all UI state.

**Comment by fperez** [comment] 2016-07-13 01:59
I've been bit by this already several times, as a reload (from an extension update) loses all my non-workspace-associated open files. It's kind of driving me crazy, as extension updates are very frequent.

I understand the association with workspaces, but I am also using vscode a lot as a "regular" text editor, calling it up from the cmd line to open files all over my filesystem.  It's a fantastic general-purpose editor in addition to a project-oriented IDE, but this issue gets in the way of that usage pattern.

Thinking out loud possible solutions: how about having a "mock" workspace, tied to a special internal name (not on the filesystem) that would simply record all open paths as absolute?  This would be the "dump bucket" for all other open files, and could be restored as a group.  I'd be OK if the restored individual files, on reopen, all get sent to a single window (to avoid the complexities of tracking them per-window).  

Just a thought.  In any case, great job overall with VSCode, I'm loving it!

**Comment by ranjan-ranjan** [comment] 2016-10-13 03:45
Duplicate: https://github.com/Microsoft/vscode/issues/101

**Comment by Tyriar** [comment] 2016-11-04 20:12
@ranjan-ranjan not technically, this however will probably be a pre-requisite to hot-exit working for empty workspaces https://github.com/Microsoft/vscode/issues/13733

**Comment by Tyriar** [comment] 2016-11-14 18:08
Right now folder workspaces record the state of the editors in local storage under the `storage://workspace/<path>/memento/workbench.editors.files.textfileeditor` key.

Empty workspaces have a similar prefix in local storage: `storage://workspace/__$noWorkspace__memento/`, but `workbench.editors.files.textfileeditor` is not recorded. This is likely the case because there is only a single empty workspace key and multiple windows writing that sort of data to the same key would be very messy. It's also noteworthy to call out there is no slash after `__$noWorkspace__`, I imagine this was an oversight in the original implementation.

One solution for enabling this is to generate a random hash to be known as the workspace identifier and move the workspace storage to ``storage://workspace/__$noWorkspace__/<hash>/`. Evicting the entries would be the main difference to folder workspaces as they only need to be retained if there are backups to restore or if `"window.reopenFolders": "all"` is set.

Making `IWorkspace` exist for empty workspaces, putting the ID in `IWorkspace.uid` and making `IWorkspace.resource` optional could be done to accomplish this, this would probably have a lot of associated changes required that currently rely on `IWorkspaceContextService.getWorkspace` being falsy to check if it's an empty workspace.

@bpasero is this the approach you would take? Any details I'm missing about the current situation?

/cc @chrmarti (interest)

**Comment by bpasero** [comment] 2016-11-15 05:29
Well you take `workbench.editors.files.textfileeditor` as the UI state, but the reality is that there are an unlimited number of more UI state keys that contribute to the overall UI state. One reason for not supporting this is the fact that you can have multiple windows without workspace associated and then you need to start inventing identifiers.

We should also not forget that the majority of users actually likes the fact that the window opens empty. I remember once that I was always restoring the previously opened file (even for empty workspaces) and that caused an outrage by people that hated it.

**Comment by chrmarti** [comment] 2016-11-15 15:07
Since restoring previously opened files when opening on a folder is accepted as the right thing to do, there should be a large number of users who would prefer the same without opening on a folder. Did removal of that not trigger any reactions? I still feel we don't necessarily understand the not-open-on-folder case well, because we tend to not use it that way.

**Comment by brenthuisman** [comment] 2016-11-15 15:10
@chrmarti The behavior was never present.

The use case is simple: remember (all) UI state when opening VSC, independent of the open number of folders.

**Comment by bpasero** [comment] 2016-11-15 15:37
@chrmarti all I can say is that we once had a bug where we would always reopen the last used file even in the empty workspace case and I got lots of issues for such behaviour. I agree that it is hard to say if that is the majority. Though I must also say that this does not seem one of the highest voted issues so far, so maybe people got used to it.

**Comment by Tyriar** [comment] 2016-11-15 18:08
@bpasero reopening the last file and not the rest is a little different to restoring the entire state. Here is how some other editors work for this case:

- **Sublime**: *Always* restore the previous state when a folder is not opened.
- **Atom** (1.11.2): When you open a file in Atom the folder is automatically added as a "project folder", so it seems to be a little awkward to get a state where you have a file but not the folder open. When you remove the project folder after opening a file, the state *will not* be restored.

**Comment by bpasero** [comment] 2016-11-15 18:33
@Tyriar this was from a time where we did not have any tabs, so for most users it did not make a big difference if we restored just one file or multiple files because it looked pretty much the same.

I suggest to put the decision to restore an empty workspace with all its UI state behind a setting that is disabled by default. It will be enabled as soon as we detect the case of a hot exit, because that is a requirement to not loose any data.

Once we are more comfortable with the approach we can try to run an experiment on some users to enable this by default and see how it goes.

No matter how we decide, we need a solution that allows to persist UI state per window and not per workspace. There are several scenarios I can think of:
* you want to persist the UI state for one ore multiple window without workspace (= this empty case)
* you want to persist the UI state for a window that has multiple workspaces open (popular feature request)
* you want to persist the UI state for 3 windows that all have the same workspace open (another popular feature request)

Also, the solution needs to support a migration path for our current UI state association per workspace.

**Comment by brenthuisman** [comment] 2016-11-15 18:43
@bpasero For calling vscode with a filename I would expect it to restore all state + open the file outside of any workspaces, unless its part of a project already opened.

**Comment by chrmarti** [comment] 2016-11-16 16:30
@bpasero On your question about opening a single file: I think users who enable the setting would expect their 'state' of open files and windows to be preserved in all cases, including this one. You'd probably want to remember the MRU list of windows, so we can use that to decide in which window to open the file.

**Comment by BobbyBabes** [comment] 2016-12-14 14:25
Creating one folder named ``Empty`` (for example; or named JABOF) which will always be empty. And then opening that folder together with my ``bunch-of-files-from-all-over-the-place`` works for me as a workaround.
When I need to open a project folder, with files, I just do that in a new VSC window.

JABOF === Just A Bunch Of Files.

**Comment by weeblr** [comment] 2016-12-19 14:58
Hi

Just adding my voice here to find a way to achieve this: now that hot exit is there, I finally got to switch to VSCode as my go-to editor for all random files on my various machines, only to discover that those files would vanish when vscode is exited/restarted.

All editors and IDEs I have used in recent years restore states, just because it is so common to keep working on something after a break, a computer restart, whatever...

Rgds

**Comment by Jonatino** [comment] 2016-12-19 20:15
@weeblr agreed. This should be a feature of any modern text editor. Hopefully they get the chance to add it soon 😄

**Comment by BobbyBabes** [comment] 2016-12-20 06:18
Hot exit doesn't save a history of file changes per file. Dirty or not. A restart, followed by Ctrl+z on a dirty file, brings back nothing.
(Atom does. Ctrl+z restores changes even after multiple restarts. Even when the file was not dirty.)

**Comment by Tyriar** [comment] 2016-12-20 06:49
@BobbyBabes that's tracked here https://github.com/Microsoft/vscode/issues/15135

**Comment by BobbyBabes** [comment] 2016-12-20 07:32
@Tyriar Thanks I've just subscribed to that issue.

**Comment by NitroG42** [comment] 2017-01-18 10:14
As said before, this is really weird to see after a relaunch one file still open (because modified and not saved), and the others closed. It feels inconsistant for the user, even if  people that come here knows why it's like that.

**Comment by ZENN0N** [comment] 2017-03-21 06:39
Starting to wonder this is a case of an issue getting made too broad. I.e. 
> "Remember **all UI state** even when reopening"

(which makes it complex/hard/more work)


When all most people want is a simple 
`"window.reopenFiles": "all"`
option

**Comment by brenthuisman** [comment] 2017-03-21 08:53
That is in fact how this issue started ;)

**Comment by freMea** [comment] 2017-03-29 13:43
I love **Code** but this thing is driving me crazy. All I want to set is when starting **Code**: restore last state, that is the window as I left it when last exit with groups, tabs (all of them), last caret position for every file, everything ! (no more nor less). Or just at least, if I could save the current state in a session that I could restore when I need it. Both should be possible and it is a legitimate user expectation from such an code editor.

Currently, when I'm just using Code as a daily text editor to open some bunch of code files from miscellaneous places and no folder is open, even with

    "window.reopenFolders": "all"
    "files.hotExit": "onExit",

only the dirty/unsaved files will be restored. All others are to be opened one by one via the recent files menu.

Very annoying since there is no easy workaround like sessions management.

Please add an command line argument to force to restore last state like `--restore` then a setting to control the restore last state feature like `"window.restorePreviousState"` with these options:

- on : restore only if those command line arguments are not used [-n, -g, _file_, _folder_, -d]
         or if those arguments are used in conjunction with `--restore` : [-g, _file_, _folder_]
- off : always off except if launched with `--restore`
- force : like if it were launched with `--restore`

 `--restore` would be always ignored if [-n, -d] exist.

I hope to see something like that in a very next future.

Current setup: v1.10.2 on Win 10 x64 pro.

**Comment by agbernard** [comment] 2017-04-13 05:33
Really need this - I just discovered this wonderful piece of software and am ready to drop sublime for it, but I rely on this feature of sublime pretty heavily.

**Comment by ltongues** [comment] 2017-04-24 09:38
I agree, this would be a really nice feature. Please fix this. Thanks!

**Comment by Stoo42** [comment] 2017-04-26 01:52
Same deal - having to open a dummy empty folder just so that it remembers the random bunch of files I always have open is a bit of a dirty workaround. Like @agbernard I use this feature of Sublime, and am looking to switch all my editing to VSCode, but this feature that a lot of other advanced text editors have surely isn't _that_ hard to put into VSCode?

**Comment by Offbeatmammal** [comment] 2017-05-18 01:57
at the moment I'm working on a project that's just a couple of files and an output file. I have them open in split view. unlike other apps on macOS when I restart (or even if I close/reopen Code to refresh a plugin or apply an update) it doesn't reload my UX as it was before ... seems inconsistent with how I expect things to work on Mac

**Comment by cossio** [comment] 2017-05-22 21:11
Sometimes I have multiple files from multiple folders open, and probably from different projects. I would like to restore this state when I reopen vscode.

**Comment by thedarkfalcon** [comment] 2017-05-31 23:35
I have been waiting for this feature for over a year and it still hasn't been implemented T_T

Most other code text editors I have used have this functionality. I use NP++ as my primary editor because I absolutely need this functionality.  I have attempted to switch to VSC but this missing functionality is a deal breaker. One of the main reasons I wanted to swap to VSC as my primary text editor is because it has better lexers than are available in NP++ (yaml, json, etc).

**Comment by cossio** [comment] 2017-06-01 16:11
Maybe there is a complication with this issue that we are not seeing?

But what is the problem with simply remembering all open windows, files and folders?

**Comment by thedarkfalcon** [comment] 2017-06-01 21:40
I think how VSC implemented "workspaces" has made making this simple request unworkable. I'm not sure about sublime and all them, but NP++ stores all its cache/temp files etc in %appdata% (or another folder you specify). I think VSC makes a workspace file in the workspace (i.e. folder) that the user opens. If they don't open a folder, there is no workspace :( Why this doesn't just fallback to being stored in %appdata% I really don't know.. 

Even where reopening workspaces is implemented fully for VSC I don't think its as complete as other editors. i.e. it doesn't retain undos etc. I can close and reopen NP++ and its like I didn't even close it. All my "new 1" through to "new 17" unsaved files restore, all their history, caret positions, line bookmarks, word highlights/marks, for all my tabs restore. Its great for when windows forces you to restart for installing updates.

**Comment by snys98** [comment] 2017-06-06 07:31
How about just making a "default workspace folder" in the installation directory?

**Comment by bpasero** [comment] 2017-06-10 08:54
I started to look into this and have some ideas how to make it work. It would probably involve introducing a new setting `window.reopenWindows` which deprecates `window.reopenFolders` that we have today. Possible values could be:
* `none`: always start empty (same as `window.reopenFolders: none`)
* `last`: restore last active window (folder or empty window)
* `folders`: restore only folder windows (same as `window.reopenFolders: all` today)
* `all`: restore all empty and folder windows

**Comment by gandaldf** [comment] 2017-06-10 10:42
@bpasero I think it's good!

**Comment by BobbyBabes** [comment] 2017-06-10 11:14
I have a question about the `last` value. Would that always be the window I close VSC from (with `Ctrl+Q` on Linux.) ?
Which would mean that I would always have to navigate first to the window I want to be `last`, before hitting `Ctrl+Q` ?
I'm not criticising. Just asking for my understanding.

**Comment by bpasero** [comment] 2017-06-10 16:46
@BobbyBabes yes, last active would be the last window that had focus before closing. If you quit from one window that has focus, that window would be restored.

**Comment by BobbyBabes** [comment] 2017-06-10 17:21
OK. I was asking because the first time I read its description, I interpreted it as "restore from last time". But that didn't sound meaningful because it would restore the exact same windows and editor tabs time after time.
Thanks!

**Comment by thedarkfalcon** [comment] 2017-06-12 03:22
@snys98 a workspace in the installation directory is a bad idea. Running in a windows environment, to make changes in program files directory you need to be running as administrator. I wouldn't want to have open a text editor in administrator mode just for that purpose. _%appdata%_ would be a much more appropriate place for a magical (fake) workspace.

**Comment by bpasero** [comment] 2017-06-13 06:25
This will be available in tomorrows insider.

**Closed** 2017-06-13 06:25 UTC
Labels: feature-request, workbench

**Comment by BobbyBabes** [comment] 2017-06-13 10:08
@bpasero Is that a newspaper?

**Comment by bpasero** [comment] 2017-06-13 11:57
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by BobbyBabes** [comment] 2017-06-13 12:32
@bpasero I was just kidding. The last 2 words sound like a newspaper name. Sorry! Should have added a smilie.

**Comment by bpasero** [comment] 2017-06-13 14:00
:]

**Comment by chrmarti** [comment] 2017-06-16 18:55
@bpasero Should the old setting be honored if it is set? I have `"window.reopenFolders": "all"` and just 'lost' all windows through a restart which used to preserve them.

**Comment by bpasero** [comment] 2017-06-17 05:09
@chrmarti great catch, I had a bug in my migration code 👍

**Comment by aaccioly** [comment] 2017-07-10 11:36
Hi @bpasero. Just double checking, in the insiders preview looks like the new option is `window.restoreWindows` right? 

@BobbyBabes mentioned option (`last`) is probably the new default (now called `one`)? 

It is working fine. My only problem with the current version - and I'm not sure if it this is directly related - is that if I have some dirty files and open a new folder they are not carried forward. Instead VS Code displays a Prompt asking if I want to save the file. That happens even with `"files.hotExit": "onExitAndWindowClose"`.

I would expect unsaved files to be there after opening a new folder. 

If I switch between two folders or if I close a folder and open it again everything works as expected (i.e., previous unsaved files are kept). The problem only manifests itself when no folder is currently open in the editor.

**Comment by aaccioly** [comment] 2017-07-10 12:17
Another problem is that I'm not getting the expected behavior with:

```javascript
{
    "window.restoreWindows": "all",
    "files.hotExit": "onExitAndWindowClose"
}
```

Assume that I have two windows open, each pointing to a different folder. If I right click Visual Studio Code Icon and select "Close all windows".

 I would expect both windows to be restored the next time I launch vscode, instead I'm getting either an empty window or only one of the two previously open windows.

**Comment by bpasero** [comment] 2017-07-10 17:22
@aaccioly can you file this as separate issue, it seems unrelated.

**Comment by aaccioly** [comment] 2017-07-11 09:10
Hi @bpasero, ok, will do.

**Comment by bpasero** [comment] 2017-07-11 16:41
I would argue that "Close All Windows" should not restore the windows because you are actually closing all of them. In the same way if you close a single window we would never restore it.

If you use File > Exit the windows will restore properly and that is the intent of the `window.reopenWindows` setting.

**Comment by zaichang** [comment] 2017-07-25 09:46
@bpasero Just wanted to thank you for adding this feature, it was one of my biggest gripes with VS Code before since I work with multiple windows some of which has files from different locations. Hunting them down and re-opening them every time VS Code restarts was a pain!

**Comment by BobbyBabes** [comment] 2017-07-25 14:30
^^
This!

**Comment by BobbyBabes** [comment] 2017-07-26 10:17
@bpasero This is more of a question than an issue.

Situation:
```
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```
```
"uname --all" output:
Linux designbox 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux`
```
```
Preferences: `"window.restoreWindows": "all"`
```
```
One VSC window with a project folder opened. All files saved.
One VSC window with just a bunch of files opened. Some with unsaved changes.
Ctrl+Q to close all VSC windows and quit VSC.
```
**Reopening** VSC (as per the title of this issue) works as expected. Both windows are restored with all files.
Ctrl+Q again.

Then double-clicking a source file in the file manager, opens one VSC window with just the double-clicked file.
Ctrl+Q again.
Start VSC, and one window opened with just the one file, double-clicked from the file manager.
I restored the initial 2 windows with Ctrl+N, followed by Open recent.

I had expected that, after opening the 2 VSC windows, the source file (double clicked from the file manager) would be added to one of the 2 VSC windows. And that that window would be pushed to the foreground.
Similar to what happens when there are already VSC windows opened, and you then double-click a source file from the file manager.

So my question is : is this intentional, and should I therefore open a request for this behaviour to be added ?

**Comment by Curros** [comment] 2017-08-09 09:57
Hi everyone, I'm trying to change from Sublime to VS Code so keep the old files is important for me , but I just install the version: 1.15.0-insider, and I'm not able to find the property "window.reopenWindows".
I do have "window.restoreWindows": "all". And of course, is not restoring all the files previously opened.

@bpasero any suggestions? (tks in advance!)

**Comment by bpasero** [comment] 2017-08-11 14:21
@BobbyBabes yeah that seems like a separate issue to me, you seem to want to restore your context if you start Code via the icon and ignore sessions where you opened code with a specific file. I think it should be reported as such.

Today we simply restore your last session, no matter how you got there (e.g. by clicking the icon or opening a file).

@Curros the setting is now called `"window.restoreWindows": "all"`. If it does not work please report a new issue with steps how to reproduce.

**Comment by BobbyBabes** [comment] 2017-08-11 16:58
@bpasero Thanks for clearing that up. I'm opening a new request issue right after.

**Comment by aethelberht** [comment] 2017-09-15 17:36
@bpasero 
> Today we simply restore your last session, no matter how you got there (e.g. by clicking the icon or opening a file).

Are you saying the current intended behavior is to restore all open editors, both clean and dirty, regardless of whether VS Code is launched by the icon or launched by opening a file? Because it seems to me that the `"window.restoreWindows": "all"` setting is only applying to the former.

**Comment by bpasero** [comment] 2017-09-16 04:20
No, when you open a file into a window, then we do not restore the other editors.
