### ISSUE TITLE
vscode not adhering to my syntax highlighting in settings.json unless I open the file and edit one of the colors

### ISSUE THREAD

**Issue by cjolivier01** [microsoft/vscode#101422] opened 2020-06-30 15:37 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open any rermote project
2. Syntax coloring is the default, all other settings appear to be ok
3. edit "editor.background": "#000000", by removing a zero, then saving (screen turns red) then re-adding the zero and saving
4. syntax highlighting is enabled

Does this issue occur when all extensions are disabled?: Yes/No
Not locally, but with only remote ssh plugin enabled, it occurs when I connect to the remote host with all other plugins disabled.  It does this on multiple AWS server/project roots.

**Comment by aeschli** [comment] 2020-07-01 09:51
What theme do you have configured? Is it set in the user settings or the (remote) workspace settings?

(maybe a duplicate of #101433)

**Comment by cjolivier01** [comment] 2020-07-01 13:36
Default Dark+ how do I tell where it's set? It isn't in my settings.json, but when I tab through preferences "Workbench: Color Theme", it shows up on 
It does not say "Modified in..." on any of the tabs.
"Color customization" says "modified in workspace"
![image](https://user-images.githubusercontent.com/11234557/86250210-28462c80-bb65-11ea-869e-fec7b8251b74.png)

**Comment by cjolivier01** [comment] 2020-07-01 13:38
I tried changing the workspace config to "Visual Studio Dark" so that it weas different from "User", but that didn't help.

**Comment by aeschli** [comment] 2020-07-02 10:07
You use the default theme (otherwise it would have a blue bar next to the settings).

> `edit "editor.background": "#000000", by removing a zero, then saving (screen turns red) then re-adding the zero and saving
Where did you do this? User settings or workspace settings?

To open the user settings JSON, run `Preferences: Open User Settings (JSON)`
To open the workspace settings JSON, run `Preferences: Open Workspace Settings (JSON)`

**Comment by cjolivier01** [comment] 2020-07-02 12:47
only settings i ever usually edit are in workspace .vscode/settings.json

**Comment by aeschli** [comment] 2020-07-02 13:13
Ok, that's the workspace settings.

The bug that you are seeing is https://github.com/microsoft/vscode/issues/101433. It's fixed in the latest insiders.

**Comment by cjolivier01** [comment] 2020-07-02 18:47
I installed 1.47.0-insider and the problem did not go away. I even uninstalled and reinstalled everything clean.

**Comment by aeschli** [comment] 2020-07-03 06:54
Ok, sorry for that, the commit got delayed, bit is in now. Please try with Monday's update.

**Closed by aeschli** 2020-07-03 06:54 UTC
Labels: needs more info
