### ISSUE TITLE
Please provide an option to copy without coloring

### ISSUE THREAD

**Issue by m-ghaoui** [Microsoft/vscode#27200] opened 2017-05-24 14:11 UTC
- VSCode Version: 

Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:20:36.315Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063

Steps to Reproduce:

1. Open a file with syntax highliting (.json, C#, whatever)
2. Paste it into rich text app like Outlook, Teams, Skype for Business whatever.

You get something like this:

![image](https://cloud.githubusercontent.com/assets/481297/26407494/9a7558c8-409b-11e7-9f3d-554b271075f8.png)

This is highly annoying. Please provide an option to copy **without** colors.

**Comment by m-ghaoui** [comment] 2017-05-24 14:20
I did a search for this issue but nothing came up. Googling "Visual Studio code coloring syntax highlighting" gave me a lot of Visual Studio links but no hints as to how to control this in VSCode.

Sorry if this issue has been reported already.

**Comment by yfdyh000** [comment] 2017-05-24 14:26
Duplicate of #21071.

**Closed** 2017-05-24 16:53 UTC
Labels: duplicate
