### ISSUE TITLE
Extensions Details and Changelog views scroll bar broken after Zoom In/Out

### ISSUE THREAD

**Issue by meboev** [Microsoft/vscode#20961] opened 2017-02-20 22:47 UTC
- VSCode Version: Code - Insiders 1.10.0-insider (64801727521592cf5fe64fd911b1efe41b1ea732, 2017-02-20T07:13:27.765Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open VS Code (does not matter if its window is maximized or non-maximized)
2. Open Extensions > Popular Extensions
3. Open a random extension
4. Press Ctrl + = (Zoom In)
5. The 'Details' and 'Changelog' views's scroll bars are not properly positioned (far right and bottom of the window)
6. The opposite disposition appears also on 'Zoom Out'
7. The same problem happens on those non-zero zoom levels with some extension's views. For example: 'Annotator'

![image](https://cloud.githubusercontent.com/assets/2070752/23144091/fd62d184-f7cd-11e6-9a0e-af23fc870448.png)

![image](https://cloud.githubusercontent.com/assets/2070752/23144103/0fbfbc98-f7ce-11e6-9ea6-9e52f61dc373.png)

![image](https://cloud.githubusercontent.com/assets/2070752/23144123/37fe1204-f7ce-11e6-88ea-04938791a5a2.png)

![image](https://cloud.githubusercontent.com/assets/2070752/23144139/4d81b59a-f7ce-11e6-968d-52bf8fd70512.png)

**Comment by jrieken** [comment] 2017-02-21 07:50
dupe of #5745

**Closed by jrieken** 2017-02-21 07:50 UTC
