### ISSUE TITLE
open editors can't rename file name

### ISSUE THREAD

**Issue by Tongmyong** [Microsoft/vscode#55306] opened 2018-07-28 16:42 UTC
- VSCode Version:1.81.1
- OS Version:win 10

Steps to Reproduce:

1.Open a file in any place, such as a.txt on desktop 
2.and then this file will appear in the file list of the "open editors"
3.When you click the right button on the file, there is no function to rename the file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2018-08-03 12:40
This can be done in the explorer.
In the open editors view by designe we decided not to allow this.
We could consider opneing the open editros view to extensions so each extension can contribute actions here, but I believe there is already an issue for this. Thus closing this one as designed.

@kieferrm just fyi I own the explorer and open editors so assign issues like this to me in the future - thanks a lot!

**Closed** 2018-08-03 12:41 UTC
Labels: as-designed, feature-request
