### ISSUE TITLE
扩展宿主意外终止

### ISSUE THREAD

**Issue by kindywu** [Microsoft/vscode#40490] opened 2017-12-19 07:33 UTC
![image](https://user-images.githubusercontent.com/6177365/34145620-ddd7b586-e4d1-11e7-98ac-6b4be850e189.png)

![image](https://user-images.githubusercontent.com/6177365/34145645-f3fd7cce-e4d1-11e7-89e5-7fc868bb5fca.png)

- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
go-builder-help|ans|2.1.2
tslint|eg2|1.0.24
phpunit|ema|2.1.1
php-debug|fel|1.12.1
php-intellisense|fel|2.1.0
php-pack|fel|1.0.1
vstortoise|flo|1.1.1
beautify|Hoo|1.1.1
Go|luk|0.6.69
Kotlin|mat|1.3.0
python|ms-|0.9.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.0.0
vetur|oct|0.11.5
typescript-hero|rbb|1.8.0
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment] 2017-12-19 10:26
duplicate of https://github.com/buehler/typescript-hero/issues/363

**Closed by weinand** 2017-12-19 10:26 UTC
