### ISSUE TITLE
Extension not deactivating after tests are run

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode#96090] opened 2020-04-21 20:12 UTC
Hi. It appears the extension is not deactivating after tests are run. This could imply context subscriptions are also not dispose'd. This could lead to really unexpected results when running tests in CI environments. 

Reproduction steps:

1. `git clone https://github.com/microsoft/vscode-test.git`
2. `cd vscode-test`
3. `npm i`
4. `cd sample`
5. `npm i`
6. `code .`
7. Make the following changes to activate the extension in the tests, and to add a log message to the `deactivate` method:

```diff
diff --git a/sample/package.json b/sample/package.json
index eb8772a..3b0470c 100644
--- a/sample/package.json
+++ b/sample/package.json
@@ -10,9 +10,9 @@
                "Other"
        ],
        "activationEvents": [
-               "onCommand:extension.helloWorld"
+               "*"
        ],
-       "main": "./out/src/extension.js",
+       "main": "./out/sample/src/extension.js",
        "contributes": {
                "commands": [
                        {
diff --git a/sample/src/extension.ts b/sample/src/extension.ts
index 1f714f5..16d9cf7 100644
--- a/sample/src/extension.ts
+++ b/sample/src/extension.ts
@@ -23,4 +23,6 @@ export function activate(context: vscode.ExtensionContext) {
 }

 // this method is called when your extension is deactivated
-export function deactivate() {}
+export function deactivate() {
+       console.log('DEACTIVATE');
+}
```
8. Run `npm run compile`
9. Run `npm test`

You'll see the message "Congratulations, your extension "vscode-test-ext" is now active!" is logged in the terminal, but "DEACTIVATE" is not.

**Comment by octref** [comment] 2020-04-24 19:53
It seems to be the cause is that `deactivate` is not called when you run VS Code CLI with `--extensionDevelopmentPath` and `--extensionTestsPath`, so I'm moving it to here.

**Comment by 928PJY** [comment] 2021-02-04 02:18
@alexdima so is there any workaround on this issue?

**Comment by pablocabrera85** [comment] 2021-08-13 14:33
Hi @alexdima, we are also currently affected by this issue. 

All our pipelines are not hanging because of this issue. 

We can work around it in our runTest script, but the problem is our extension is also consumed by other teams so this also affects their pipelines.

Do you know when this issue will be tackled?

**Comment by alexdima** [comment] 2022-04-07 20:27
Fixed via https://github.com/microsoft/vscode/commit/80e81c66c0be5f54008bf8f36f978e18acc480bc

**Closed by alexdima** 2022-04-07 20:27 UTC
Labels: bug, extension-host, extensions-development

**Comment by aeschli** [comment] 2022-04-28 17:12
In addition to the steps above, I changed `runTest.ts` to
```
		const extensionDevelopmentPath = path.resolve(__dirname, '../../../');
		const extensionTestsPath = path.resolve(__dirname, './suite');

		const testWorkspace = path.resolve(__dirname, '../../../test-fixtures/fixture1');

		/**
		 * Use Insiders release for testing
		 */
		await runTests({
			version: 'insiders',
			extensionDevelopmentPath,
			extensionTestsPath,
			launchArgs: [testWorkspace]
		});
		
```
to only run against insiders. Unfortunately, I don't see the `DEACTIVATED` printed:
```
Found existing install in /home/martin/workspaces/vscode-test/sample/.vscode-test/vscode-linux-x64-insiders. Skipping download
[45216:0428/190317.724840:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2022-04-28T17:03:17.891Z] window#load: attempt to load window (id: 1)
[main 2022-04-28T17:03:17.901Z] update#ctor - updates are disabled by the environment
[main 2022-04-28T17:03:17.953Z] ExtensionHostStarterWorker created
[main 2022-04-28T17:03:18.689Z] window#load: window reported ready (id: 1)
[main 2022-04-28T17:03:18.868Z] Starting extension host with pid 45425 (fork() took 10 ms).
[main 2022-04-28T17:03:18.871Z] ExtensionHostStarterWorker.start() took 21 ms.
Loading development extension at /home/martin/workspaces/vscode-test/sample
Congratulations, your extension "vscode-test-ext" is now active!
Unexpected token H in JSON at position 0

  Extension Test Suite 1
Unexpected token H in JSON at position 0
    ✓ Sample test
  1 passing (84ms)
[main 2022-04-28T17:03:19.942Z] Waiting for extension host with pid 45425 to exit.
[main 2022-04-28T17:03:19.981Z] Extension host with pid 45425 exited with code: 0, signal: null.
Exit code:   0
Done

```

**Comment by aeschli** [comment] 2022-04-28 17:15
Adding a sleep to deactivate, shows that deactivate is called. Just the console.log doesn't make it through.

**Comment by alexdima** [comment] 2022-04-29 08:49
> Adding a sleep to deactivate, shows that deactivate is called. Just the console.log doesn't make it through.

:+1: thank you for verifying. The `console.log` is serviced via the ext host renderer socket and we can't guarantee it makes it to the renderer process to be printed. If a debugger would be attached, then the debugger would see the `console.log`.
