### ISSUE TITLE
On save the entire file is formatted differently than settings

### ISSUE THREAD

**Issue by AdamLeBlanc** [Microsoft/vscode#19984] opened 2017-02-05 17:01 UTC
- VSCode Version: 1.9.0
- OS Version: OSX

Steps to Reproduce:

1. Have editor set to 2 spaces for tabs
2. Save a *.js file that is following the 2 spaces rule
3. The tabbing is changed to 4 spaces

Also note, this is my settings file at the moment:

```
{
    // layout
    "workbench.sideBar.location": "right",
    // font
    "editor.fontFamily": "ubuntu mono, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontSize": 14,
    "editor.renderWhitespace": "boundary",
    // viewport
    "editor.wrappingColumn": 350,

    // formating
    "editor.detectIndentation": false,
    "editor.tabSize": 2,
    "editor.formatOnType": false, // not sure on this one


    // autocomplete
    "editor.acceptSuggestionOnEnter": false,

    // cursor
    "editor.cursorBlinking": "blink",


    // Eslint
    "eslint.run": "onType",
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "window.zoomLevel": 0,
    "files.associations": {
        "*.js": "javascript"
    },
    "editor.tabCompletion": false,
    "vsicons.projectDetection.autoReload": true,
    "[javascript]": {

    }
}
```

**Comment by bpasero** [comment] 2017-02-05 18:14
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by AdamLeBlanc** [comment] 2017-02-09 08:19
I ran disabled all the extensions, and the problem was still there. When I restarted VS code for the 12th time or so again the problem was gone. I'm not really sure what would cause that 😕

**Comment by jrieken** [comment] 2017-02-09 09:38
There is known issue with TypeScript/JavaScript loosing it file to project association. My guess is that it's that unless @mjbvz knows more about it

**Comment by alexblack** [comment] 2017-02-14 18:40
Is there a workaround? Vscode is mangling all my files when I save.

**Comment by alexblack** [comment] 2017-02-14 18:42
Hmm, this only started with 1.9 (maybe 1.9.1?), but it goes away when I disable extensions `code --disable-extensions` gonna try to narrow down which extension it is

**Comment by alexblack** [comment] 2017-02-14 18:46
Seems to be caused by https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter for me

**Comment by jrieken** [comment] 2017-02-15 07:56
Thanks for getting back to us. Closing this issue as being caused by an extensions. Please get in touch with that extension author. Happy Coding

**Closed** 2017-02-23 22:30 UTC
Labels: caused-by-extension
