### ISSUE TITLE
JSX Formatting issue

### ISSUE THREAD

**Issue by philipwhite** [Microsoft/vscode#46781] opened 2018-03-27 23:26 UTC
Issue Type: <b>Bug</b>

This snippet from the meteor tutorial does not get formatted cleanly. Note especially the ending label tag.
```
render() {
        return (
            <div className="container">
                <header>
                    <h1>Todo List ({this.props.incompleteCount})</h1>
                    <label className="hide-completed">
                        <input
                            type="checkbox"
                            readOnly
                            checked={this.state.hideCompleted}
                            onClick={this.toggleHideCompleted.bind(this)}
                        />
                        Hide Completed Tasks
          </label>
                    <AccountsUIWrapper />

                    <form className="new-task" onSubmit={this.handleSubmit.bind(this)} >
                        <input
                            type="text"
                            ref="textInput"
                            placeholder="Type to add new tasks"
                        />
                    </form>
                </header>

                <ul>
                    {this.renderTasks()}
                </ul>
            </div>
        );
    }
```

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.40GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by mjbvz** [comment] 2018-03-28 04:33
Thanks. This has the same root cause as https://github.com/Microsoft/TypeScript/issues/20766

Closing as upstream

**Closed by mjbvz** 2018-03-28 04:33 UTC
Labels: formatting, javascript, upstream
