### ISSUE TITLE
Shared profile feature request

### ISSUE THREAD

**Issue by mconners** [Microsoft/vscode#27135] opened 2017-05-23 12:31 UTC
A great feature would be to have a profile stored in the cloud so that whenever installing/using VSCode on a new machine, it's easy to keep my plugins, editor settings consistent.

Thanks.

**Comment by yfdyh000** [comment] 2017-05-23 15:00
Duplicate of #7311.

**Comment by roblourens** [comment] 2017-05-23 17:52
Thanks @yfdyh000

**Closed by roblourens** 2017-05-23 17:52 UTC
Labels: duplicate
