### ISSUE TITLE
VS Code should support span-based text markers

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#1959] opened 2016-01-12 15:17 UTC
For .NET debugging, we have a number of spots where it can be confusing what the line-based text markers used by VS Code are actually pointing at. There are various language features in C# that commonly result either in multiple statements on a single line or in multi-line statements. Some of these such as setting a breakpoint inside of a lambda can be pretty confusing today because the editor markers (current statement, breakpoint bound) just show the line where things are happening instead of the text range. Thus there is no way to tell quite where you are stopped, or where the breakpoint is actually set.

I would suggest supporting both text markers that highlight an entire line, and text markers that highlight a text span ([begin-line,begin-col]->[end-line,end-col]).

**Comment by weinand** [comment] 2016-01-14 10:54
CC @weinand

**Comment by Peter-Juhasz** [comment] 2016-03-29 20:21
Currently the whole concept is incorrect or incomplete. You place breakpoints onto a **statement** and not onto a line. A line can contain multiple statements, and lines are only presentation features of the source code (at least in most of the languages).

**Comment by weinand** [comment] 2016-03-29 20:24
@Peter-Juhasz correct. We accept PRs that fix this!

**Comment by isidorn** [comment] 2017-04-13 08:29
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/8851 which is on our april plan

**Closed by isidorn** 2017-04-13 08:29 UTC
Labels: debug, feature-request
