### ISSUE TITLE
Insert Snippets using it's prefix stop working on version 1.10.1

### ISSUE THREAD

**Issue by joaosamouco** [Microsoft/vscode#21733] opened 2017-03-02 09:13 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.8|
|vscode-docker|PeterJausovec|0.0.12|
|theme-oceanic-next-italic|SintrumIT|1.1.14|
|vscode-theme-onedark|akamud|1.3.1|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.1.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|prettier-vscode|esbenp|0.9.0|
|theme-onedark-sublime|joshpeng|0.3.6|
|VS-code-vagrantfile|marcostazi|0.0.4|
|atom-keybindings|ms-vscode|2.0.0|
|debugger-for-chrome|msjsdiag|2.5.5|
|theme-base16-ocean-dark|viatsko|1.0.0|;

---

Steps to Reproduce:

1. Open file
2. Try to use previously working snippet

Snippets are not detected as they were in the previous version.

**Comment by jrieken** [comment] 2017-03-02 09:22
@joaosamouco Can you provide more details please? 

* Is that a snippet you have manually created or one you have gotten via an extension?
* In what language does this happen? Any, a specific one?
* Does this happen everywhere in the file or only in certain places, like inside jsx-tags or inside comments?
* When you say 'Snippets are not detected as they were' does that mean they don't show anymore and they still show but don't insert anymore.

Last, please attach a sample of the code in which you want to insert a snippet and at best also the snippet which you want to insert

**Comment by joaosamouco** [comment] 2017-03-02 09:32
* Manually created snippet
* Markdown language
* Everywhere in the file
* They don't show up in the "IntelliSense tooltip" and they are not autocompleted

I've tried with different files, empty ones and in the middle of existing ones. Nothing works if I try to insert a snippet using it's prefix.

I've tested and they work properly with `CMD+SHIFT+P`->Insert Snippet->Select Snippet

**Comment by jrieken** [comment] 2017-03-02 09:50
What is the prefix? Can you share the snippet with me?

**Comment by joaosamouco** [comment] 2017-03-02 09:54
Sure.

```json
{
	"Issue report": {
		"prefix": "issue",
		"body": [
			"## Summary",
			"",
			"${1:How would you describe the bug in less than 60 characters? It should quickly and uniquely identify a bug report as well as explain the problem, not your suggested solution.\n\n**Example**: Selecting CFF crashes the Web Application.}",
			"",
			"## Component",
			"",
			"${2:In which sub-part of the software does it occurs?\n\n**Example**: `jscrambler-parser`}",
			"",
			"## Configuration",
			"",
			"${3:Everything that might influence the current behavior but it's not directly related to the issue.\n\n**Example**:\n* Jscrambler 4.0\n* Ultimate Plan}\n* ApplicationId: XXX",
			"",
			"## Description",
			"",
			"${4:The extended details of your problem report.}",
			"",
			"## Steps to Reproduce",
			"",
			"${5:Minimized, easy-to-follow steps that will trigger the bug.\n\n**Example**:\n1. Open Jscrambler WebApp\n2. Create a new application\n3. Select Control Flow Flattening}",
			"",
			"## Actual Results",
			"",
			"${6:What the application did after performing the above steps.\n\n**Example**: The application crashed.}",
			"",
			"## Expected Results",
			"",
			"${7:What the application should have done, if the bug was not present.\n\n**Example**: Should change status of Control Flow Flattening}",
			"",
			"## Additional Information",
			"",
			"${8:Information that might be useful to the developer that will try to solve your issue.\n\n**Example**: API response is not the one that WebApp is expecting.}"
		]
	}
}
```

**Comment by jrieken** [comment] 2017-03-02 10:05
hm, I cannot reproduce with that snippet. Do you have any snippet specific settings for IntelliSense, like `"editor.snippetSuggestions": "none"`. Can you try with F1 > Insert Snippet?

![screen shot 2017-03-02 at 11 03 53](https://cloud.githubusercontent.com/assets/1794099/23502388/fcb40142-ff37-11e6-98f7-2004817970c5.png)

**Comment by joaosamouco** [comment] 2017-03-02 10:32
I have no specific settings for IntelliSense.

* It is working if I the command palette and go to `Insert Snippet`.
* It works if I start typing the prefix and press `CTRL+Space` to for suggestions to open.
* It **does not** work when I start typing the prefix and wait for the suggestions box to open by itself. This worked perfectly on the previous version. 

A colleague of mine is able to reproduce the issue on his machine using the same snippet.

**Comment by jrieken** [comment] 2017-03-02 11:33
Ok, understood. What happened is that we disabled 24x7 IntelliSense for Markdown files by default. Often people were complaining that eager suggestions while typing text is confusion. Therefore we now only show IntelliSense when explicitly asked for (ctrl+space). This is https://github.com/Microsoft/vscode/issues/19733 and if you disagree with the new defaults, please comment there. 

To restore the old behaviour, add this to your `settings.json`
```json
	"[markdown]": {
		"editor.quickSuggestions": true
	}
```

**Comment by jrieken** [comment] 2017-03-02 11:34
closing this issue as designed because this was changed on purpose via #19733.

**Closed by jrieken** 2017-03-02 11:34 UTC
Labels: needs more info, snippets

**Comment by joaosamouco** [comment] 2017-03-02 11:37
Awesome. Thanks for the information. Definitely agree with this change.

👍
