### ISSUE TITLE
Cannot access SemiLight weight of Cascadia Code

### ISSUE THREAD

**Issue by aaronbell** [microsoft/vscode#103565] opened 2020-07-29 15:38 UTC
- VSCode Version: VS Code 1.47.3 & Insiders 1.48.0
- OS Version: Mac OS 10.14.2 & Windows 10

Steps to Reproduce:

1. Install the [Cascadia Code](https://github.com/microsoft/cascadia-code/releases/tag/v2007.01) TTF.
2. Open VS Code Settings page and search for "Font Weight"
3. Dropdown does not allow user to select "350" for SemiLight

The [OpenType specification](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#usweightclass) lists 'commonly-used' font weights, but *any* value between 1 and 1000 are actually considered valid. Use of a usWightClass of 350 for SemiLight is extremely common, including Microsoft's own Segoe UI SemiLight. VSCode should therefore support selection of "350". At current, users are not able to access Cascadia Code's SemiLight weight in VSCode. Other Microsoft products, such as Windows Terminal, are able to access this font weight without issue. 

Additionally, as Cascadia Code is a variable font, users can (and should) be able to access any weight value between 200 and 700. I would suggest that, in addition to a drop down, you also enable "custom" values to be entered.

**Comment by IllusionMH** [comment] 2020-07-29 16:32
/duplicate of #101467 which has PR available, but no feedback from the team. 

Just in case: you can use any text value e.g. `"350"` which will show warning, but works as expected

**Closed** 2020-07-29 16:32 UTC
Labels: *duplicate

**Comment by aaronbell** [comment] 2020-07-29 16:43
Oh, thanks! I didn't find your issue when I searched.
