### ISSUE TITLE
for typescript , alt+shift+f ,format the file ,   the code get disorder 

### ISSUE THREAD

**Issue by athinboy** [Microsoft/vscode#37015] opened 2017-10-27 02:35 UTC
- VSCode Version:
版本 1.17.2
提交 b813d12980308015bcd2b3a2f6efa5c810c33ba5
日期 2017-10-16T13:59:46.104Z
Shell 1.7.7
渲染器 58.0.3029.110
Node 7.9.0
架构 x64

-OS Version: win10 Professional

for typescript , alt+shift+f ,format the file ,   the code get disorder : some functions has been move !
I worry for some function mistake .

extension list:

2017/08/06  12:06    <DIR>          abusaidm.html-snippets-0.1.0
2017/10/21  16:54    <DIR>          alefragnani.project-manager-0.22.0
2017/10/26  09:54    <DIR>          bajdzis.vscode-database-1.2.0
2017/08/29  07:46    <DIR>          christian-kohler.npm-intellisense-1.3.0
2017/09/06  08:51    <DIR>          codezombiech.gitignore-0.5.0
2017/10/21  16:54    <DIR>          DavidAnson.vscode-markdownlint-0.11.0
2017/07/17  13:57    <DIR>          dbaeumer.jshint-0.10.15
2017/10/24  20:25    <DIR>          dbaeumer.vscode-eslint-1.4.0
2017/09/06  08:51    <DIR>          donjayamanne.git-extension-pack-0.1.3
2017/09/02  13:37    <DIR>          donjayamanne.githistory-0.2.3
2017/08/29  07:44    <DIR>          donjayamanne.python-0.7.0
2017/07/10  13:33    <DIR>          DotJoshJohnson.xml-1.9.2
2017/10/21  16:57    <DIR>          eamodio.gitlens-5.7.1
2017/10/21  16:54    <DIR>          eg2.tslint-1.0.12
2017/10/21  16:54    <DIR>          eg2.vscode-npm-script-0.3.1
2017/07/10  13:34    <DIR>          eriklynd.json-tools-1.0.2
2017/10/09  09:11    <DIR>          esbenp.prettier-vscode-0.24.0
2017/09/08  09:28    <DIR>          felipecaputo.git-project-manager-1.4.0
2017/10/26  09:43    <DIR>          formulahendry.code-runner-0.8.2
2017/10/09  09:10    <DIR>          goessner.mdmath-2.0.7
2017/08/14  08:34    <DIR>          HookyQR.beautify-1.1.1
2017/10/17  15:49    <DIR>          jchannon.csharpextensions-1.3.0
2017/07/15  16:40    <DIR>          jmrog.vscode-nuget-package-manager-1.1.4
2017/10/24  20:25    <DIR>          johnpapa.angular2-2.10.0
2017/10/17  15:50    <DIR>          josephwoodward.vscodeilviewer-0.0.1
2017/10/17  15:49    <DIR>          k--kato.docomment-0.0.17
2017/10/24  20:25    <DIR>          KnisterPeter.vscode-github-0.23.0
2017/10/17  08:50    <DIR>          Leopotam.csharpfixformat-0.0.38
2017/07/19  08:41    <DIR>          lucasschejtman.vscode-typesearch-0.2.1
2017/08/29  07:44    <DIR>          magicstack.magicpython-1.0.12
2017/09/05  14:25    <DIR>          manuth.markdown-converter-0.0.10
2017/08/06  11:37    <DIR>          MariusAlchimavicius.json-to-ts-1.5.3
2017/07/06  21:21    <DIR>          mdickin.markdown-shortcuts-0.8.1
2017/09/06  08:52    <DIR>          michelemelluso.gitignore-1.0.1
2017/09/23  09:18    <DIR>          mkaufman.htmlhint-0.4.0
2017/09/23  16:23    <DIR>          ms-mssql.mssql-1.2.0
2017/10/16  10:07    <DIR>          ms-vscode.azure-account-0.1.3
2017/09/02  11:47    <DIR>          ms-vscode.csharp-1.12.1
2017/10/11  08:59    <DIR>          ms-vscode.js-atom-grammar-0.1.14
2017/09/18  09:04    <DIR>          ms-vscode.typescript-javascript-grammar-0.0.24
2017/09/08  09:28    <DIR>          ms-vsts.team-1.122.0
2017/10/21  16:54    <DIR>          msjsdiag.debugger-for-chrome-3.4.0
2017/08/14  08:31    <DIR>          peakchen90.open-html-in-browser-0.0.2
2017/10/21  16:54    <DIR>          PeterJausovec.vscode-docker-0.0.20
2017/10/26  15:08    <DIR>          rbbit.typescript-hero-1.6.0
2017/10/21  16:54    <DIR>          redhat.java-0.12.0
2017/10/26  14:57    <DIR>          remimarsal.prettier-now-1.4.9
2017/07/01  15:37    <DIR>          sodatea.velocity-0.1.0
2017/08/29  07:44    <DIR>          tht13.python-0.2.3
2017/09/29  16:08    <DIR>          xabikos.javascriptsnippets-1.5.0
2017/10/21  16:54    <DIR>          yzhang.markdown-all-in-one-0.11.0
2017/10/26  16:19    <DIR>          ziyasal.vscode-open-in-github-1.2.9

**Comment by mjbvz** [comment] 2017-10-27 03:59
Does this reproduce if you disable all of your extensions? If it does, please share some example code that demonstrates this problem when you format it

**Comment by athinboy** [comment] 2017-10-30 02:17
@mjbvz  thanks,i will try !

**Comment by mjbvz** [comment] 2017-11-03 20:57
Closing this as possibly caused by extension. We also cannot investigate this further without more information about what is going wrong

**Closed by mjbvz** 2017-11-03 20:57 UTC
Labels: format, needs more info, typescript
