### ISSUE TITLE
Please add a button for "Reveal in Side Bar"

### ISSUE THREAD

**Issue by Defcon0** [microsoft/vscode#115970] opened 2021-02-06 12:59 UTC
Hello,

at first I'd like to thank you for the great job done with VS Code. It's a really great IDE so far :-)

Only one thing bothers me a bit. I just moved from PhpStorm and immediately the feature "Auto-Reveal", i.e. the automatic scrolling of the side bar to the file (tab) currently active, drove me crazy :-) So I deactivated the functionality and found out there's a "reveal in side bar" function when I click right on the tab. I put it on a shortcut so I can live with that.

But what would be way better would be an (optional?) button for "reveal in side bar", ideally in the position shown in the screenshot (see below).

Would that be possible?

Thanks in advance!

Bye Defcon0

![screen](https://user-images.githubusercontent.com/1485098/107118816-7f427b80-6883-11eb-876f-f1278fa2e1cf.png)

**Comment by gjsjohnmurray** [comment] 2021-02-06 16:08
I'm guessing the response will be "No". But if #108271 gets implemented it would be possible for you to build an extensionthat gives you what you want.

cc @isidorn

**Comment by Defcon0** [comment] 2021-02-06 18:10
Too bad :-( It would make things way easier concerning shifting from php storm.

**Comment by yume-chan** [comment] 2021-02-07 02:31
But it's possible here

![image](https://user-images.githubusercontent.com/1330321/107134709-7dce8d00-692f-11eb-909b-542dec7b3399.png)

Using [Reveal](https://marketplace.visualstudio.com/items?itemName=smulyono.reveal) extension

**Comment by Defcon0** [comment] 2021-02-07 12:51
Thanks for the hint. I installed the extension and subscribed to https://github.com/microsoft/vscode/issues/108271 .

I guess then this ticket can be closed unless @isidorn has a different opinion.

**Comment by isidorn** [comment] 2021-02-08 09:30
Agree with everything said here. Let's close as duplicate of #108271

**Closed by isidorn** 2021-02-08 09:30 UTC
