### ISSUE TITLE
VS Code just reverted a file, losing a whole day of work

### ISSUE THREAD

**Issue by d07RiV** [Microsoft/vscode#40267] opened 2017-12-15 07:18 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
prettier-vscode|esb|1.0.0
flow-for-vscode|flo|0.7.3
sublime-babel-vscode|jos|0.2.9
debugger-for-chrome|msj|4.0.0

---

I work on the same folder (on external hard drive) from two PCs. I made a lot of changes to a certain file at home, then the next day I come to work, plug in my drive, start my development server (which showed the latest version of my app), and start up VS code. It starts with three open files. I make a small change to one of them and save, and the app stops working. Then I realize that the rest of that file is a very early version that I had made a lot of changes to, so obviously it doesn't work with the rest of the app anymore.

How did it manage to pull out such an early version (even earlier than I had when I left work last night), and then used it to overwrite the current version without a warning? VS Code was not running that whole time, I literally just started it up. I don't have these files under version control.

**Comment by bpasero** [comment] 2017-12-15 07:31
@Tyriar very likely our backup strategy here was restoring a different version from the second computer compared to the first.

I think the only real fix here is to support to run Code portable and have the backups directory travel with it.

**Comment by Tyriar** [comment] 2017-12-15 14:52
@d07RiV sorry to hear about the loss of work but your flow is a little strange. The way the hot exit feature works is that it keeps track of unsaved files when you exit. When one of these backups is stored it will always be restored when the session is restored. What must have happened was you modified the file and didn't save it in the older version, so when you reopened the folder it restored the file and you didn't notice.

I'll close this off as a duplicate of better portable support https://github.com/Microsoft/vscode/issues/329 as @bpasero suggested, but in the meantime I suggest you to:

- Use source control, you get private git repos for free with GitHub and BitBucket. You're asking for trouble if you do not use source control.
- Disable hot exit, add this to your settings: `"files.hotExit": "off"`

**Closed by Tyriar** 2017-12-15 14:52 UTC
Labels: hot-exit
