### ISSUE TITLE
Status bar fails to show entries with priorities that cannot be serialised

### ISSUE THREAD

**Issue by eduardoribeiro** [microsoft/vscode#133317] opened 2021-09-17 09:34 UTC
Issue Type: <b>Bug</b>

I can't see anymore, on status bar, the current branch I'm working on, the file formatting, prettier results, language detected, or any other extension that might show info on status bar... which make the status bar pretty much useless. 

VS Code version: Code - Insiders 1.61.0-insider (Universal) (a0af58197e4a1d3e82fbe3048e0549e622d19f4f, 2021-09-17T05:13:49.338Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 7aaeb67d-ffb6-4d8f-b482-6745655cbda0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.4.0
cucumberautocomplete|ale|2.15.1
vscode-apollo|apo|1.19.4
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.25
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
html-slim-scss-css-class-completion|gen|1.7.8
vscode-pull-request-github|Git|0.30.0
vscode-react-typescript|inf|1.3.1
RelativePath|jak|1.4.0
vscode-peacock|joh|3.9.1
vscode-mdx|Jou|0.2.3
vscode-styled-components|jpo|1.6.6
chat|kar|0.35.0
vscode-gutter-preview|kis|0.27.1
react-javascript-to-typescript-transform-vscode|moh|1.10.0
vscode-edge-devtools|ms-|1.3.1
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.9.1001240917
jupyter-keymap|ms-|1.0.0
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.6.1
syncing|non|3.1.0
convert-css-in-js|pau|1.1.3
material-icon-theme|PKi|4.10.0
prisma-insider|Pri|31.0.81
vscode-thunder-client|ran|1.9.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
code-settings-sync|Sha|3.4.3
svg-preview|Sim|2.8.3
vscode-stylelint|sty|0.86.0
react-redux-es6-snippets|tim|2.1.0
vscode-icons|vsc|11.6.0
quokka-vscode|Wal|1.0.400
vscode-icons-mac|way|7.25.3
yarn-ui|xqc|0.1.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
00j7a122:30294756
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vssur157:30367808

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-17 09:40
Please paste a screenshot.

Please also use the `Start Extension Bisect` command to check if one of your extensions is causing this.

**Comment by stephenlaughton** [comment] 2021-09-17 16:10
I ran `Start Extension Bisect` and by default VSCode Insiders was not able to determine the extensions which were causing an issue. After running it again with the extensions pane open and observing which extensions were disabled during the `Start Extension Bisect` steps, I could manually confirm that `quokka-vscode` and `wallaby-vscode` (both by the same vendor WallabyJS) were causing the issue for me!

All that being said, the output of `Start Extension Bisect` was not able to sort this out automatically so that may be a separate issue @gjsjohnmurray

**Comment by gjsjohnmurray** [comment] 2021-09-17 19:04
> All that being said, the output of `Start Extension Bisect` was not able to sort this out automatically so that may be a separate issue @gjsjohnmurray

pinging @jrieken about this.

**Comment by drewkht** [comment] 2021-09-17 21:23
Can confirm I was experiencing this problem as well in VS Code `1.61.0-insider` the , and it occurred immediately after I moused over this "info" icon and clicked "Pin to Status Bar":

![image](https://user-images.githubusercontent.com/36053052/133854837-e7b0007b-f545-458d-ad97-822f52b7ab78.png)

That caused the entire status bar to become blank except for the "problems" icons on the far left. I tried reloading the window, closing/reopening VS Code, and closing/reopening the project folder but those didn't help. 

Running `Start Extension Bisect` confirmed that it was being caused by my `quokka.js` extension as mentioned by @stephenlaughton . The process of disabling/enabling that extension appears to have fixed the issue for now, as everything's back to normal at this point.

**Comment by smcenlly** [comment] 2021-09-17 23:37
I'm from the Wallaby team. We create [Quokka.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode) and [Wallaby.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode) that were causing a problem in the latest Code-Insiders.

The issue is related to this commit: https://github.com/microsoft/vscode/commit/d3ac6b8d261bf17c0041ce56737d784baee32f68. More specifically, this was the source of the crash: https://github.com/microsoft/vscode/blob/d3ac6b8d261bf17c0041ce56737d784baee32f68/src/vs/workbench/browser/parts/statusbar/statusbarModel.ts#L321

Previously, we were creating the status bar with:

```typescript
window.createStatusBarItem(vscode.StatusBarAlignment.Left, Number.NEGATIVE_INFINITY);
```

We fixed the problem in our extensions by changing to:

```typescript
window.createStatusBarItem(vscode.StatusBarAlignment.Left, -100);
```

I'm not really sure why this caused the crash as `(typeof Number.NEGATIVE_INFINITY)` is still a number. Regardless of extension fault (or not), I guess ideally the sort code should at least not crash the status bar out entirely because of an extension (i.e. it should ignore / gracefully handle this case).

**Comment by bpasero** [comment] 2021-09-20 08:44
Underlying issue is that even though `Infinity` is a valid type as far as our API goes, when this value is serialised to the workbench side, it ends up being `null` because we use JSON for serialisation and that does not support `Infinity`. 

Looks like `Infinity` can be replaced with `1e99999` and `-Infinity` can be replaced with `-1e99999` and it ends up as the right type in the end. I can also add another check for `NaN`.

**Closed** 2021-09-20 09:21 UTC
Labels: bug, workbench-status
