### ISSUE TITLE
Test edit sessions: Continue Edit Session doesn't find the correct directory

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#153572] opened 2022-06-28 18:18 UTC
Testing #153386

When I try to `Continue Edit Session` in a GitHub Repository in a browser and select a local copy in my file explorer, it isn't able to find it. The path to my vscode local clone is `C:\Users\andreamah\Documents\vscode`. 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/31675041/176253924-47bab1f4-6d74-48b0-b2dc-df45715d42f5.png">

**Comment by bpasero** [comment] 2022-06-30 04:36
Yes, not possible.

**Comment by joyceerhl** [comment] 2022-08-24 18:27
Fixed with https://github.com/microsoft/vscode/commit/ed78fe5771e2406e1a928239ce2f065f521d4f31, we can't offer this in web due to browser limitations so we disabled it there. Duplicate of https://github.com/microsoft/vscode/issues/156345

**Closed by joyceerhl** 2022-08-24 18:27 UTC
Labels: feature-request
