### ISSUE TITLE
Can't type due to cramped text. - Issues after the update.

### ISSUE THREAD

**Issue by Suzal3579** [Microsoft/vscode#19957] opened 2017-02-05 04:23 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-dracula|dracula-theme|1.2.5|
|theme-etinum|euntaik|0.1.3|
|ruby|groksrc|0.0.6|
|beautify|HookyQR|0.7.3|
|theme-material-theme|jprestidge|1.0.1|
|theme-chromodynamics|lei|1.0.8|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.9|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|
|language-pde|Tobiah|0.1.21|

---

![screenshot 62](https://cloud.githubusercontent.com/assets/16387512/22623685/c59c6784-eb88-11e6-8c43-9fa102c162eb.png)

**Comment by dan-silver** [comment] 2017-02-05 05:59
This might be a duplicate of #19755

**Comment by Suzal3579** [comment] 2017-02-05 07:26
@dan-silver  yeah, I do think this is the same issue (Except: he's on mac and I'm on windows, he mentioned only CS Files and for me it's for every file opened). 

I couldn't wait for the fix so I installed a older version. If you find this solved please do inform me. Thanks!

**Closed** 2017-02-05 09:02 UTC
