### ISSUE TITLE
Cannot install extension return error "end of central directory record signature not found"

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#35511] opened 2017-10-03 04:10 UTC
_From @teguh-satriya on October 3, 2017 1:22_

## Environment data
VS Code version:  VS Code 1.16.1
Python Extension version:  0.7.0
Python Version:  3.6.2
OS and version:   Windows 10 Enterprise version 1511

## Actual behavior
Error msg `end of central directory record signature not found` popping out when installing extension

## Steps to reproduce:  
- Search extension and push install button

## Logs
Output from ```Console window``` (Help->Developer Tools menu)
```
workbench.main.js:sourcemap:28 end of central directory record signature not found: Error: end of central directory record signature not found,    
at C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:183:14,    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:618:5,    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\fd-slicer\index.js:32:7,    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)
e.doShow @ workbench.main.js:sourcemap:28
e.show @ workbench.main.js:sourcemap:28
(anonymous) @ workbench.main.js:sourcemap:29
r @ workbench.main.js:sourcemap:28
e._emitToSpecificTypeListeners @ workbench.main.js:sourcemap:28
e._emitEvents @ workbench.main.js:sourcemap:28
(anonymous) @ workbench.main.js:sourcemap:28
r @ workbench.main.js:sourcemap:28
e._emitToBulkListeners @ workbench.main.js:sourcemap:28
e._emitEvents @ workbench.main.js:sourcemap:28
e.emit @ workbench.main.js:sourcemap:28
(anonymous) @ workbench.main.js:sourcemap:28
v @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_chainedError @ workbench.main.js:sourcemap:28
n @ workbench.main.js:sourcemap:28
v @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_error @ workbench.main.js:sourcemap:28
e.doRequest.n.TPromise.t.handlers.(anonymous function) @ workbench.main.js:sourcemap:28
e.onMessage @ workbench.main.js:sourcemap:28
(anonymous) @ workbench.main.js:sourcemap:28
e.invoke @ workbench.main.js:sourcemap:28
e.fire @ workbench.main.js:sourcemap:28
(anonymous) @ workbench.main.js:sourcemap:28
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

```

_Copied from original issue: DonJayamanne/pythonVSCode#1264_

**Comment by joaomoreno** [comment] 2017-10-04 07:07
Duplicate of #34730

**Closed by joaomoreno** 2017-10-04 07:07 UTC
Labels: extensions
