### ISSUE TITLE
TypeScript language service dies when you have an untitled file open.

### ISSUE THREAD

**Issue by trivett** [microsoft/vscode#88558] opened 2020-01-13 15:34 UTC
It appears that having an open untitled unsaved file breaks TypeScript features.

Desired behavior: One should be able to have an unsaved file in memory without losing all the valuable features of VS Code and TypeScript that we know and love. 

Steps to Reproduce: 

- Create a new untitled file (cmd/ctrl + n) in a TS project
- Wait just a moment while watching the TypeScript service output
- Observe that the TS language server has died and the IDE is stuck in a loop of "Initializing JS/TS Language features

Issue Type: <b>Bug</b>

- Create a new untitled file (cmd/ctrl + n) in a JS/TS project
- Wait a moment
- Observe that the TS language server has died and the IDE is stuck in a loop of "Initializing JS/TS Language features

output on my machine from the TS server:

```
[Trace  - 15:28:28.590] <semantic> Event received: projectLoadingStart (0).
Data: {
    "projectName": "tsconfig.json",
    "reason": "Creating possible configured project for untitled:^Untitled-1 to open"
}
[Trace  - 15:28:28.591] <semantic> Response received: updateOpen (2). Request took 25982 ms. Success: false . Message: Error processing request. Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at ProjectService.updateNonInferredProjectFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137442:43)
    at ProjectService.addFilesToNonInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137332:22)
    at ProjectService.updateRootAndOptionsOfNonInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137480:22)
    at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137416:22)
    at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137356:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137361:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138186:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:107
    at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:565:30)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139271:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Trace  - 15:28:28.593] <semantic> Sending request: geterr (3). Response expected: yes. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "/Users/vincentpaultrivett/linen/node/src/loom-get-applications/getData.js",
        "/Users/vincentpaultrivett/linen/node/src/loom-get-applications/LoomGetApplications.d.ts",
        "/Users/vincentpaultrivett/linen/node/src/loom-get-applications/filteringHelpers.ts",
        "/Users/vincentpaultrivett/linen/node/src/loom-get-applications/index.test.js",
        "untitled:^Untitled-1"
    ]
}
[Info  - 15:28:28.593] Killing TS Server
[Info  - 15:28:28.716] TSServer exited
[Info  - 15:28:28.716] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 15:28:28.719] <syntax> Forking...
[Info  - 15:28:28.725] <syntax> Starting...
[Info  - 15:28:28.727] <semantic> Forking...
[Info  - 15:28:28.743] <semantic> Starting...
[Trace  - 15:28:28.746] <semantic> TypeScript Server: trying to cancel ongoing request with sequence number 3
[Trace  - 15:28:28.752] <semantic> Sending request: configure (0). Response expected: no. Current queue length: 0
Arguments: {
    "hostInfo": "vscode",
    "preferences": {
        "providePrefixAndSuffixTextForRename": true,
        "allowRenameOfImportPath": true
    }
}
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 7, 6|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-opennewinstance|chr|0.0.6
path-intellisense|chr|1.4.2
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
relative-import|sai|1.3.1
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.6.0
highlight-matching-tag|vin|0.9.6

(1 theme extensions excluded)

</details>

**Comment by trivett** [comment] 2020-01-13 15:43
I looked around a little for similar errors but haven't found one.

**Comment by mjbvz** [comment] 2020-01-13 21:12
Duplicate of https://github.com/microsoft/TypeScript/issues/35914

Can you please try [updating to the latest TypeScript version](https://github.com/microsoft/TypeScript/issues/35914#issuecomment-569557495) and letting us know on the upstream issue if that fixes the problem

**Closed by mjbvz** 2020-01-13 21:12 UTC
Labels: typescript

**Comment by trivett** [comment] 2020-01-14 14:37
Thank you mjbvz, I will watch that issue, apologies for not turning it up. I tried the nightly TS extension for the sake of experiment, but the error remained after a refresh. For now I am disabling the `"files.defaultLanguage": "javascript",` setting and avoiding the error.
