### ISSUE TITLE
Color boxes not showing for LESS variables specifically

### ISSUE THREAD

**Issue by tylrlw** [microsoft/vscode#92532] opened 2020-03-11 23:41 UTC
Issue Type: <b>Bug</b>

In a document formatted for LESS, the following does not show color boxes like it does if the hex codes are listed somewhere else. This is different before today. There was an update that was just installed for VSCode that may have broke this.

@1: #F1FFDB;
@2: #B5E8A8;
@3: #DEE7A8;
@4: #F9BB4F;
@5: #F58513;

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
githistory|don|0.6.2
prettier-vscode|esb|3.20.0
minify|Hoo|0.4.3
applescript|idl|0.18.1
vscode-edit-csv|jan|0.2.6
json2csv|kha|0.0.1
es6-css-minify|olb|3.3.2
json-template|sto|0.3.1
vscode-icons|vsc|10.0.0

(1 theme extensions excluded)

</details>

**Comment by tylrlw** [comment] 2020-03-12 00:15
Here is another example that shows hex colors are being treated differently.
<img width="847" alt="Screen Shot 2020-03-11 at 5 14 07 PM" src="https://user-images.githubusercontent.com/62081831/76475382-e037aa00-63bb-11ea-9fe5-9c60f804fe78.png">

**Comment by octref** [comment] 2020-03-12 19:44
Duplicate of #92417

**Closed by octref** 2020-03-12 19:44 UTC
Labels: new release
