### ISSUE TITLE
Slow response when system is offline

### ISSUE THREAD

**Issue by moostad** [Microsoft/vscode#1000] opened 2015-12-04 04:20 UTC
When system is connected to network but don't have access to internet (just local network) navigation, move , copy , rename in directories and files become very slow. it's happening periodically and seems  like it's waiting for kind of timeout. 

![image](https://cloud.githubusercontent.com/assets/10362398/11582160/2d796f30-9a60-11e5-8695-5b25929a2ed3.png)

**Comment by bpasero** [comment] 2015-12-04 09:23
@moostad when this happens can you open chrome tools (Help > Toggle Developer Tools), open the Profile tab and run a CPU profile to see where the time is spend?

**Comment by moostad** [comment] 2015-12-04 10:32
@bpasero I don't see any problem in CPU profile (or most likely I'm not qualified to read it) but I can send it to you if it can help. the only thing I noticed is every time that's happening two error will print in console.

1: Error: getaddrinfo ENOTFOUND vortex.data.microsoft.com vortex.data.microsoft.com:443 at errnoException (dns.js:25:10) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

2: Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:80 at errnoException (dns.js:25:10) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by jrieken** [comment] 2015-12-04 10:52
btw - this is issue #1000 :tada:

**Comment by bpasero** [comment] 2015-12-04 10:55
@moostad if you are able to capture a CPU profile when the explorer shows the spinning progress you can send it to me.

I think the ENOTFOUND is from our telemetry reporting. @SofianHn any chance this could slowdown operations? We don't send telemetry sync do we?

**Comment by SofianHn** [comment] 2015-12-04 18:51
@bpasero we don't sent telemetry sync, those errors are expected to be on the console. I just tried to reproduce it with no luck. 

@moostad please try disable telemetry as described [here](https://code.visualstudio.com/Docs/supporting/FAQ#_how-to-disable-crash-reporting) and let us know if you see any difference.

**Comment by moostad** [comment] 2015-12-04 20:38
@bpasero here's the CPU profile.
[CPU-20151204T235311.cpuprofile.zip](https://github.com/Microsoft/vscode/files/52466/CPU-20151204T235311.cpuprofile.zip)

**Comment by moostad** [comment] 2015-12-05 00:19
@SofianHn I disabled telemetry for about an hour and problem solved and as soon as I enabled that again, I get spinning progress 4 times in less than 10 minutes.

**Comment by SofianHn** [comment] 2015-12-05 01:17
Interesting...thanks @moostad for the quick response. I am guessing you are on Mac, after being offline for a while please run `open $TMPDIR/appInsights-node` from the terminal and verify what exists in this directory. You should see a bunch of json files, I am interested how many and what's their sizes. 

@bpasero I verified that the caching mechanism by AppInsights is [async](https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Sender.ts#L147). My guess now that it might be writing to the disk too often which might be causing this issue. I will take it from here.

**Comment by moostad** [comment] 2015-12-05 02:22
@SofianHn I will send those information later however I'm not sure that have anything to do with io because I don't get spinning when system is disconnected from network (wifi is off) it's happening only when my mac is connected to the network without internet. I guess when it's see getaway that try to connect to website and block everything until get timeout. that's when I get spinning.

p.s. I have no problem to read and listening English but writing and speaking is another story, so sorry about my poor english.

**Comment by moostad** [comment] 2015-12-05 08:28
This time I tried on Ubuntu to be sure it's not OS/Device related, it's happening but not as often and not as long as Mac. maybe because it has much more power then the Mac (2x raid0 SSD for OS, 12 core CPU, 32 GB ram). here's the list of files

Total size: 1.5 MB
Count : 43

```bash
  45K Dec  5 11:16 1449301590361.ai.json
  21K Dec  5 11:16 1449301607507.ai.json
  44K Dec  5 11:17 1449301669096.ai.json
 8.0K Dec  5 11:18 1449301685054.ai.json
  28K Dec  5 11:18 1449301701515.ai.json
  28K Dec  5 11:18 1449301722262.ai.json
  14K Dec  5 11:19 1449301741035.ai.json
  18K Dec  5 11:19 1449301757832.ai.json
 5.4K Dec  5 11:19 1449301776224.ai.json
  65K Dec  5 11:20 1449301804942.ai.json
  54K Dec  5 11:20 1449301820250.ai.json
  19K Dec  5 11:20 1449301854519.ai.json
  17K Dec  5 11:21 1449301877099.ai.json
  26K Dec  5 11:21 1449301897507.ai.json
  16K Dec  5 11:21 1449301913055.ai.json
  20K Dec  5 11:22 1449301928942.ai.json
  18K Dec  5 11:22 1449301946785.ai.json
  46K Dec  5 11:22 1449301975527.ai.json
  23K Dec  5 11:23 1449301990779.ai.json
  43K Dec  5 11:23 1449302007367.ai.json
  52K Dec  5 11:23 1449302031358.ai.json
  15K Dec  5 11:24 1449302047260.ai.json
  46K Dec  5 11:24 1449302067154.ai.json
  41K Dec  5 11:24 1449302082161.ai.json
  54K Dec  5 11:25 1449302107280.ai.json
  37K Dec  5 11:25 1449302122366.ai.json
  17K Dec  5 11:25 1449302142179.ai.json
  35K Dec  5 11:25 1449302159539.ai.json
  34K Dec  5 11:26 1449302182334.ai.json
 5.4K Dec  5 11:26 1449302198281.ai.json
  25K Dec  5 11:26 1449302215101.ai.json
  38K Dec  5 11:27 1449302231171.ai.json
  25K Dec  5 11:27 1449302248680.ai.json
  35K Dec  5 11:27 1449302264804.ai.json
  19K Dec  5 11:28 1449302280982.ai.json
  66K Dec  5 11:28 1449302299938.ai.json
  69K Dec  5 11:28 1449302315167.ai.json
  37K Dec  5 11:28 1449302330401.ai.json
  31K Dec  5 11:29 1449302349368.ai.json
 9.5K Dec  5 11:29 1449302369790.ai.json
 6.8K Dec  5 11:29 1449302399153.ai.json
  80K Dec  5 11:30 1449302418946.ai.json
  22K Dec  5 11:30 1449302433991.ai.json

```

**Comment by SofianHn** [comment] 2015-12-05 20:39
thanks @moostad for the clarification and the list of files. The update rate and the size of files seems reasonable to me, writing 3 small files a minute should not be a problem. Now that IO is less likely to have caused this, I will work on producing the case with network and without internet to see what might be going wrong here. 

You english is great btw, we really appreciate working with us to get this issue fixed.

**Comment by SofianHn** [comment] 2015-12-11 17:48
The electron folks confirmed the issue on their side. Until this issue get fixed in electron and we get the new build, the workaround is to disable telemetry.

**Comment by egamma** [comment] 2015-12-16 10:04
We will not update to a new electron build for the December update. Therefore I'm moving the milestone to January.

The work around for how to disable telemetry is document here: https://code.visualstudio.com/Docs/supporting/FAQ#_how-to-disable-telemetry-reporting

**Comment by joaomoreno** [comment] 2016-02-24 16:40
Nothing happened in February for this. Ping @SofianHn

**Comment by SofianHn** [comment] 2016-03-16 00:36
I pinged in the upstream, still waiting

**Comment by egamma** [comment] 2016-03-17 14:45
We will not update to a new electron for March, shifting to April

**Comment by bpasero** [comment] 2016-04-22 13:53
This is super super bad, I just hit this while in transit. We have to do something about it for April, it feels you are sitting in front of a web browser that tries to connect to the file that is on disk.

**Comment by bpasero** [comment] 2016-04-22 13:54
@Microsoft/vscode to get some attention and maybe collect ideas. We could maybe:
* take out telemetry from the critical path of opening a file
* detect that the system is offline and just not try to connect (Electron has APIs for this)

**Comment by jrieken** [comment] 2016-04-22 13:58
+2 the telemetry service should not run in the main thread but like search and fs watch in a separate process

**Comment by jrieken** [comment] 2016-04-22 13:59
as an easy workaround we can use a `setTimeout` trick to get off the critical path

**Comment by bpasero** [comment] 2016-04-22 16:45
I find it surprising that every call to telemetry gets send to the appenders right away. I would have at least expected some kind of buffering and batching. Adding some way of buffering with timeouts at the point where we collect these events seems like a good thing to do anyway.

Still, for the actual network access I think we should just turn off network access when we detect we are [offline](https://github.com/electron/electron/blob/master/docs/tutorial/online-offline-events.md).

**Comment by jrieken** [comment] 2016-04-22 17:04
> I find it surprising that every call to telemetry gets send to the appenders right away.

I think that's fair. The appenders are the ones that know what debouncing strategy to apply. However, the telemetry service should guard itself against evil/slow appenders.

**Comment by bpasero** [comment] 2016-04-23 11:03
Looking into what application-insights module does it seems they do buffering, however I find it weakly implemented (https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Channel.ts#L64). 

Basically they seem to:
* collect events and add them to a buffer
* install a timeout of some seconds before sending the buffer
* if the buffer has more than 250 items inside, just send directly

Given the DNS lookup might take a long time I think what happens is that the buffer gets filled up to 250 and then it would just get send directly instead of waiting for the other timeout to finish.

Adding our own setTimeout(0) at https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/aiAdapter.ts#L145 seems like one way to get off the critical path of opening an editor.

Thinking more about the issue I have to agree that we need to move telemetry reporting into a separate process because no matter how smart we get, the blocking issue will always be an issue on the renderer side.

**Closed** 2016-05-10 12:40 UTC
Labels: bug, important
