### ISSUE TITLE
Weird behaviour on mac

### ISSUE THREAD

**Issue by zafarale** [microsoft/vscode#118793] opened 2021-03-12 06:11 UTC
Hi Guys,
             I have been using vs code for a while, struck by this bug see attachement.
![Screenshot 2021-03-12 at 06 07 46](https://user-images.githubusercontent.com/6916905/110899733-8aad1a80-82f9-11eb-827b-2bffb236a39c.png)

**Comment by IllusionMH** [comment] 2021-03-12 12:46
Looks like duplicate of #106429

See https://github.com/microsoft/vscode/issues/110379#issuecomment-725614150 for possible workaround (to avoid `--disable-gpu`)

**Closed** 2021-03-12 17:27 UTC
Labels: *duplicate
