### ISSUE TITLE
Open With shows blank file in the place of the original file

### ISSUE THREAD

**Issue by cefn** [Microsoft/vscode#31284] opened 2017-07-23 20:41 UTC
# Issue

The issue seems to be to do with the .desktop file distributed with 'code' requesting that 'code' be launched with file URIs which it can't handle. It should have an Exec argument of %F not %U

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
python|don|0.6.9
cpptools|ms-|0.12.1

---

Steps to Reproduce:
1. Navigate to a folder on an LXDE Ubuntu Desktop
2. Use right-click menu to choose 'Open With' Visual Studio Code
3. Code editing window opens showing no code at all, even when file contains 1k of code
4. Turns out that it has opened a file called like /home/user/file:/home/user/folder/source.py since its .desktop file incorrectly requests a file:// URI which it can't handle

I edited the /usr/share/applications/code.desktop to add the --disable-extensions flag, then shut down and relaunched from the finder. The same problem presents.

Reproduces without extensions: Yes 

# Workaround

I modified the /usr/share/applications/code.desktop file to fix the issue by changing the Exec line to read as follows...

```
Exec=/usr/share/code/code %F
``` 

...instead of the original which read...

```
Exec=/usr/share/code/code --unity-launch %U
```

After this, the issue went away.

**Comment by isidorn** [comment] 2017-07-24 07:43
I am not sure if you had some extension which would modify that file, but we do not write --unity-launch by default. Closing as caused by extension

**Comment by cefn** [comment] 2017-07-24 10:17
Surprised to see this issue closed. Please inspect the contents of the .deb file distributed from https://code.visualstudio.com/ before asserting that an extension is responsible.

Sorry to report that @isidorn is not correct and the issue should not be closed for this reason. 

The code.desktop file is part of the distribution and the notion that an extension could be responsible for this error anyway is surprising. The .desktop file is installed as part of the Debian install process.

Inspecting code_1.14.2-1500506907_amd64.deb
shows a nested data.tar.xz archive 
inside of this archive is the offending file code.desktop under ```/./usr/share/applications/``` with exactly the invocation I described.

**Comment by isidorn** [comment] 2017-07-24 12:28
Thanks for providing more infor, reopening as you suggested

**Comment by Tyriar** [comment] 2017-07-24 17:15
Duplicate of https://github.com/Microsoft/vscode/issues/25987

**Closed by Tyriar** 2017-07-24 17:15 UTC
Labels: new release, workbench
