### ISSUE TITLE
The width of a Chinese charactor should be 2.

### ISSUE THREAD

**Issue by adf0001** [Microsoft/vscode#41537] opened 2018-01-12 16:08 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3

---

Steps to Reproduce:

1. Change config to show Tab
	"editor.renderWhitespace": "all",

2. Input "a" + Tab + "a". This is ok.

3. Next line, Input a Chinese charactor such as "就" + Tab + "a". The alignment of last "a" is fail.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2018-03-01 10:59
Duplicate of #22832

**Closed by alexandrudima** 2018-03-01 10:59 UTC
Labels: extensions
