### ISSUE TITLE
Launching tasks fails when cwd is utilized

### ISSUE THREAD

**Issue by LoeDK** [microsoft/vscode#106988] opened 2020-09-18 07:43 UTC
- VSCode Version:
code-insiders/stable 1.50.0-1600363724 amd64
- OS Version:
Ubuntu 18.04

Steps to Reproduce:
1. create a launch task that utilizes "${file}"

Expectation:
"${file}" is absolute: `/home/user/.../file.ext`

Actual Result:
"${file}" is `~/...`

In my case, this leads to errors because `~/` cannot be resolved by that process.

Does this issue occur when all extensions are disabled?: Yes

**Comment by LoeDK** [comment] 2020-09-18 07:45
@alexr00 this may be related to your latest fix.

**Comment by alexr00** [comment] 2020-09-18 08:02
Duplicate of https://github.com/microsoft/vscode/issues/106877

**Comment by alexr00** [comment] 2020-09-18 08:14
Looks like I missed a spot...

**Closed** 2020-09-18 08:40 UTC
Labels: bug, variable-resolving
