### ISSUE TITLE
Please ID the extension sent the global message

### ISSUE THREAD

**Issue by ryh** [Microsoft/vscode#24681] opened 2017-04-13 13:09 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|swift|Kasik96|0.0.2|
|material-icon-theme|PKief|2.0.3|
|jsx|TwentyChung|0.0.1|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.2|
|vscode-babel-coloring|dzannotti|0.0.4|
|weex|jaylinwang|0.4.0|
|Go|lukehoban|0.6.59|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|Theme-TomorrowKit|ms-vscode|0.1.4|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|node-modules-resolve|naumovs|1.0.2|
|vetur|octref|0.5.6|
|laravel-blade|onecentlin|1.8.1|
|laravel5-snippets|onecentlin|1.3.4|
|vuehelper|oysun|0.1.0|
|vue-beautify|peakchen90|2.0.4|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.5.1|
|vue-color|staychan|0.0.3|
|vscode-react-native|vsmobile|0.3.2|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1.update some extension, restart the vscode, there is some warnning message, **quote**:

> <span class="message-left-side" title="There are many bugs in the extension, please do not use it, the better choice is vetur. 这个插件存在许多BUG，请不要使用，一个好的选择是安装vetur https://marketplace.visualstudio.com/items?itemName=octref.vetur">There are many bugs in the extension, please do not use it, the better choice is vetur. 这个插件存在许多BUG，请不要使用，一个好的选择是安装vetur https://marketplace.visualstudio.com/items?itemName=octref.vetur</span>

2. **BUT** I cannot find which extension sent this message, and extensions can mess around with this message API.

**SO:** please add special id (itemName for example)to the message html node, or display in front  of the message as well.

**Comment by jrieken** [comment] 2017-04-13 13:24
dupe of #21302

**Closed by jrieken** 2017-04-13 13:24 UTC

**Comment by alexsasharegan** [comment] 2017-04-25 15:08
@ryh I just wanted to say, the plugin causing this is vue-beautify. You can dig into your extensions by visiting `$HOME/.vscode/extensions/` (at least that's how it is on Mac).

**Comment by LouisaNikita** [comment] 2017-07-31 08:32
@ryh when you use both vetur and vue-beautify,vetur will send this message~

you may want to use the formmatter in vue-beautify , actually, vetur have the formmatter with `cmd+shift+f`~so i think maybe there is some conflicts between them ~

**finally**, vetur is enough, its no need to install vue-beautify

**Comment by ryh** [comment] 2017-07-31 09:52
@LouisaNikita vue-beautify and vetur is not what I was talking about.. Keep to the subject.
