### ISSUE TITLE
PTP panning support on windows

### ISSUE THREAD

**Issue by vikrampraveen** [Microsoft/vscode#42798] opened 2018-02-02 08:05 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.17083
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
howdoi|kub|0.1.3
MagicPython|mag|1.0.12
python|ms-|2018.1.0
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
java|red|0.18.1
vscode-java-debug|vsc|0.5.0

---

Steps to Reproduce:

1. Two finger scroll is very jerky 
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment] 2018-02-02 08:31
Duplicate of #13612

**Closed by alexandrudima** 2018-02-02 08:31 UTC
