### ISSUE TITLE
[BUG]version 1.27 can't open file!

### ISSUE THREAD

**Issue by WilliamHuge** [Microsoft/vscode#58026] opened 2018-09-06 02:26 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.I singing a song and coding my code, suddenly, vs code alert the msg what It is updating.The result  that is not work. 
![image](https://user-images.githubusercontent.com/40257445/45131313-f3622c00-b1be-11e8-96f1-c54e433df6f4.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2018-09-06 02:31
Duplicate of #58020

**Closed by mjbvz** 2018-09-06 02:31 UTC

**Comment by GreenHand-Ben** [comment] 2018-09-06 06:10
I am the same question. Are you ready now?
