### ISSUE TITLE
Base64 and line column limitation?

### ISSUE THREAD

**Issue by liquid8d** [Microsoft/vscode#27988] opened 2017-06-04 01:29 UTC
In this recent version, I noticed that some longer base64 encoded strings didn't allow me to pan to the end of the line. When opening the file, the line wrap is turned on, when I turn line wrap off, I cannot navigate to the end of those lines using the arrow keys. I believe the data is still all there, just causes navigation issues. It seems perhaps this is a limitation in the number of columns? The color coding does not display the same as other shorter lines, so I don't know if it isn't recognized properly or just isn't displaying all of the data.

I have included a sample of one giving me trouble.
[base64-vscode-issue.zip](https://github.com/Microsoft/vscode/files/1050057/base64-vscode-issue.zip)

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.18.0|
|json-tools|eriklynd|1.0.2|
|vscode-auto-open-markdown-preview|hnw|0.0.4|;

---

Steps to Reproduce:

1. load the base64.html included in the zip in this VSCode version.
2. The line including the base64 data when line wrapping is turned off cannot be navigated to using the arrow keys.

**Comment by alexandrudima** [comment] 2017-06-06 06:39
This is not a regression. This is a limitation of our not having horizontal virtualization (in the same way we have vertical virtualization). We don't have horizontal virtualization because we leave it up to the browser to run the font layouting. 

In other words:
* when there is a large line, and word wrapping is off, we must *paint* the entire line since we cannot virtualize it because we didn't implement the Unicode layouting rules in JS (i.e. we don't know where bi-di text is, etc. etc.)
* if the line is very large, this will cause freezes, depending on the line size.
* in the case of such files (which are dominated by long lines), we forcefully go to word wrap on and an explicit user gesture is needed to turn off word wrap.
* additionally, we stop rendering a line after 10k characters and render "..." to indicate that there is more text. The cursor and all editing operations function normally on the extra characters, but they do not get rendered.
* the current recommendation is to turn on word wrapping if the intent is to edit past the 10k limit or change the limit via the "hidden" setting `"editor.stopRenderingLineAfter"` which is equal to 10000 by default, but which can be changed to -1 to never stop rendering.

**Comment by alexandrudima** [comment] 2017-11-27 12:59
Duplicate of #7772

**Closed by alexandrudima** 2017-11-27 12:59 UTC
Labels: bug, editor-rendering
