### ISSUE TITLE
Save as: incorrect file extension for unsupported file types

### ISSUE THREAD

**Issue by joshuaavalon** [microsoft/vscode#28425] opened 2017-06-10 15:29 UTC
- VSCode Version: 1.13.0
- OS Version: Win 10

Steps to Reproduce:

1. Open a not support file type but still a text file (e.g. `a.xyz`)
2. Save as a `b.xyz` by enter **b** in the save file field. (File type show as Plain Text)
3. If the destination does not have a .txt file, it will save as `b.xyz`. But if the destination have a .txt file, it will save as `b.txt`

**Comment by qoyyim** [comment] 2017-10-18 07:28
- VSCode Version: 1.17.1
- OS Version: Mac OS Sierra

it happened on VSCode for Mac too

**Comment by ta1111** [comment] 2018-08-25 12:14
I meet same question when I tried to save `*.in`.
How can I fix it?

**Comment by geckojsc** [comment] 2018-10-02 22:50
On a related note, I get kinda lost when saving a new empty file because I can't see which other code files are in the directory, unless I manually change the type to 'All files \*.\*'
![image](https://user-images.githubusercontent.com/569607/46381223-ad0cc980-c6a5-11e8-9574-8650f9760689.png)

**Comment by mstenemo** [comment] 2018-11-30 09:33
I have same issue, and I think my issue with ti would be solved if the default was "all files" instead of plain text. Is it possible to change this setting as a user?

**Comment by zulrang** [comment] 2019-07-17 00:11
I cannot believe this is still an issue after two years.  Just took a moment to figure out why all my .py files were .py.txt.

**Comment by rmobis** [comment] 2019-07-28 04:47
Apparently this is disabled _by design_ inside Electron, to safeguard it from adding `*.*` to the file name, as can be seen in [`shell/browser/ui/file_dialog_win#L206`](https://github.com/electron/electron/blob/34c4c8d5088fa183f56baea28809de6f2a427e02/shell/browser/ui/file_dialog_win.cc#L206).


```cpp
// By default, *.* will be added to the file name if file type is "*.*". In
// Electron, we disable it to make a better experience.
// ...
for (size_t i = 0; i < filterspec.size(); ++i) {
	if (std::wstring(filterspec[i].pszSpec) != L"*.*") {
		// SetFileTypeIndex is regarded as one-based index.
		dialog->SetFileTypeIndex(i + 1);
		dialog->SetDefaultExtension(filterspec[i].pszSpec);
		break;
	}
}
```

There has to be a way though, because many other programs can do it. I'll try and test if this issue actually happens later, but I'll have to build my own Electron as well I think.

**Comment by bpasero** [comment] 2019-10-09 18:40
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Closed by bpasero** 2019-10-09 18:40 UTC
Labels: electron, upstream
