### ISSUE TITLE
Better font style for CodeLens actions

### ISSUE THREAD

**Issue by gkmngrgn** [microsoft/vscode#79113] opened 2019-08-14 12:30 UTC
When I started using Visual Studio Code, I didn't know that the CodeLens actions are clickable. I'm still getting similar feedback from my friends about it because they ignore the gray fonts directly and confess they're solving the conflicted codes manually. I mean cut & paste, or delete the codes.

![image](https://user-images.githubusercontent.com/72323/63021031-e7d3b680-be9f-11e9-940e-f45c2c795c43.png)

I'm sorry I have no idea how we can show them clearly with keeping the current appearance. Maybe choosing a different font color is enough. If you don't think to do anything about this topic, you can close it directly.

**Comment by iansan5653** [comment] 2019-08-14 14:33
Some concepts:
![image](https://user-images.githubusercontent.com/2294248/63029594-d4642380-be7e-11e9-8b17-d4036f7e218d.png)

Also note in my screenshot how the clickable actions are exactly the same style as the non-clickable file info from Gitlens at the top.

Personally I prefer the second one with the border, but I think just adding an underline helps too.

**Comment by jrieken** [comment] 2019-08-14 15:51
/duplicate of https://github.com/microsoft/vscode/issues/16038

**Closed** 2019-08-14 15:51 UTC
Labels: *duplicate, editor-code-lens

**Comment by iansan5653** [comment] 2019-08-14 16:01
@jrieken I'd say this is not a duplicate. That issue is about customizing the font style in general. This one is about making the actionable items more clearly actionable.
