### ISSUE TITLE
Command line arguments not working as expected

### ISSUE THREAD

**Issue by aniljava** [Microsoft/vscode#15435] opened 2016-11-13 22:36 UTC
As per, issue #6484 (closed), the command line arguments such as -h, should work with the
current version of VS Code. But does not work as expected in normal ubuntu installation.

Binary being used:

        /usr/bin/code -> /usr/share/code/bin/code

- VSCode Version:

        Version 1.7.1
        Commit 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
        Date 2016-11-03T13:46:46.244Z
        Shell 1.3.8
        Renderer 52.0.2743.82
        Node 6.5.0

- OS Version:

       Distributor ID:  Ubuntu
       Description: Ubuntu 16.04.1 LTS
       Release: 16.04
       Codename:    xenial

Steps to Reproduce:

    code --user-data-dir=/ws/linux/config/vscode/ /root/.bashrc
    code --user-data-dir=/ws/linux/config/vscode/ --help
    code --user-data-dir=/ws/linux/config/vscode/ /var/logs

None of the above shows any help or open path as expected.

**Comment by aniljava** [comment] 2016-11-14 08:57
Updates:

After a short digging around, either the main executable at  `/usr/share/code/bin/code` is
ignoring other arguments, including --user-data-dir when `ELECTRON_RUN_AS_NODE=1` is
present. Or `$VSCODE_PATH/resources/app/out/cli.js` is supressing or not using the other args.

When the bash startup script, `/usr/share/code/bin/code` is used, there is no effect of
arguments including path to open as well as other args like --help. The user-data-dir is
not created when `--user-data-dir` is passed.

Whereas, when the main executable (`/usr/share/code/code`) is used, it looks like the
arguments are passed and processed correctly. path to open, --new-window, -r are working
as expected. But i guess the absence of `$VSCODE_PATH/resources/app/out/cli.js`, is
causing causing the writing back to starting shell fail. Following errors are shown when
using main executable.

    bash: cannot set terminal process group (-1): Inappropriate ioctl for device
    bash: no job control in this shell

**Comment by joaomoreno** [comment] 2016-11-14 09:09
Strange. I just tried, but failed to reproduce. We'd need to debug the CLI code on your machine. Any chance that it's a VM you could send us?

**Comment by aniljava** [comment] 2016-11-14 09:21
Not a vm. But if there are switches or edits that i can do to enable trace, i can run with trace on and share the output.  I also tried `apt-get remove --purge code` and used the tar.gz version, same problem.

Any chances that there might be a conflict with existing electron installation ?

**Comment by joaomoreno** [comment] 2016-11-14 09:45
Interesting. Could be. Try the insiders version, since it's a completely separate product: http://code.visualstudio.com/insiders

**Comment by aniljava** [comment] 2016-11-14 09:57
I think i found the root cause, can you share your startup script, may be we are using
different version that it is working on your end.

The script is shifting and throwing away all args when used as root to check --user-data-dir.

    if [ "$(id -u)" = "0" ]; then
        while test $# -gt 0
        do
            if [[ $1 == --user-data-dir=* ]]; then
                DATA_DIR_SET=1
            fi
            shift
        done
        if [ -z $DATA_DIR_SET ]; then
            echo "It is recommended to start vscode as a normal user. To run as root, you must specify an alternate user data directory with the --user-data-dir argument." 1>&2
            exit 1
        fi
    fi

Just submitted a pull request with changes that retains and passes the commandline args.

**Comment by joaomoreno** [comment] 2016-11-14 10:27
Great to know. Moving this to @Tyriar, he should know the details of that script. 👍 

Great work, thanks for the effort! 🍻

**Comment by Tyriar** [comment] 2016-11-14 18:19
Fixed in https://github.com/Microsoft/vscode/pull/15448

**Closed by Tyriar** 2016-11-14 18:19 UTC
Labels: bug, linux

**Comment by roblourens** [comment] 2016-12-08 18:18
Verified: `sudo code --user-data-dir=./codedir --help` ignores `--help`. `sudo code-insiders --user-data-dir=./codedir --help` does not ignore it.
