### ISSUE TITLE
Icons in source control panel are not aligned properly

### ISSUE THREAD

**Issue by alekseyt** [microsoft/vscode#88556] opened 2020-01-13 15:26 UTC
- VSCode Version: 1.40.2
- OS Version: Ubuntu 14.04

![image](https://user-images.githubusercontent.com/993454/72267576-f843b500-3628-11ea-8fee-6a3480ca1d70.png)

Steps to Reproduce:

1. Create a repo
2. Add a file
3. Commit
4. Add another file
5. Change file from step 2
6. Select both files for commit

Actual result: "+" icons on selected files are misaligned relatively to each other.
Expected result: icons at the same horizontal position, so it's easier to click any of them and harder to misclick other icons.

Additional info: i think it's due to right-aligned "M" and "U" of different width, which is not a big deal, but apparently it's influencing alignment of "+". I've also checked insiders build for Linux and as far as i can see, this is still reproducible.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment] 2020-01-13 16:05
Yep, that't because of width difference between `M` and `U` which control width of decorator, and actions block are pushed to it, so it there is difference in width, icons would be miss aligned.
However there is another state - count of errors in file that will shift icons even more even if `M`/`U` would be aligned.
![image](https://user-images.githubusercontent.com/1312662/72271225-2e843300-362f-11ea-9cbe-b7e3eab48eaf.png)

**Comment by misolori** [comment] 2020-01-21 19:56
As @IllusionMH has pointed out, there are various decorators that could push the icons further to the left (depending the context). Closing this as-designed as this is expected behavior.

If you are wanting to perform bulk actions, you can always select multiple files and right-click to act on your selection.

**Closed by misolori** 2020-01-21 19:56 UTC
