### ISSUE TITLE
Update 1.12.1 Broke OTB JSDoc Creation

### ISSUE THREAD

**Issue by ciabaros** [Microsoft/vscode#26257] opened 2017-05-09 03:30 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Right before the update to 1.12.1, in a standard .js file, I tried to generate JSDoc with "/**" + [Enter] above a function, and all of the @param elements were pre-created.
2. I updated to 1.12.1, and doing the exact same thing ("/**" + [Enter] above a function) results in just the bare JSDoc comment structure with no @param or any other elements auto-created.

BEFORE 1.12.1 Update:
/** + [Enter] did this:
```
/**
 * @param p1
 * @param p2
 */
function( p1, p2 ) { }
```

AFTER 1.12.1 Update:
/** + [Enter] does this:
```
/**
 * 
 */
function( p1, p2 ) { }
```

**Comment by mjbvz** [comment] 2017-05-09 04:01
This is a duplicate of #25959. It should be fixed in the latest insiders builds and we are looking into shipping the fix in VSCode 1.12.2 as well

**Closed by mjbvz** 2017-05-09 04:01 UTC
Labels: duplicate
