### ISSUE TITLE
Can't create files with name which include characters that have command set with them. like L, A 

### ISSUE THREAD

**Issue by jrishabh55** [Microsoft/vscode#40019] opened 2017-12-11 12:12 UTC
- VSCode Version: Latest Insider Build
- OS Version: Windows 10

Steps to Reproduce:
1.  Click new file icon in the file viewer
2.  Type the name in box `blade`

`L` will focus out and `A` will create a new file instead of being typed

**Comment by jrishabh55** [comment] 2017-12-11 17:25
#Update
Copy and paste in name is not working either. 
`Crtl + C` or `Crtl + V`

**Comment by joaomoreno** [comment] 2017-12-12 08:59
This is a duplicate of other issues. Fixes are already in `master`.

Do you use the VIM extension?

**Closed by joaomoreno** 2017-12-12 08:59 UTC
Labels: file-explorer, insiders

**Comment by jrishabh55** [comment] 2017-12-13 07:47
No i don't use VIM extension, Yes i understand i had this issue couple of builds before as well but then it came up again in the last build. now is fixed again in this build 

Fixed in
Version 1.19.0-insider
Commit 951f5a20fc820e32a65ca05bb87af86f65027470
Date 2017-12-12T21:32:54.471Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
