### ISSUE TITLE
Option to disable file explorer jump to current file.

### ISSUE THREAD

**Issue by Growiel** [Microsoft/vscode#3800] opened 2016-03-08 03:01 UTC
At the moment, whenever you focus one of the editors, the file explorer jumps to the location of said file, however, it should stay wherever I left it last. Run case:

1) Open a file in editor 1.
2) Open a file in editor 2.
3) Navigate to new file in explorer.
4) Realize I want to open it in editor 1.
5) Focus editor 1.
6) File explorer jumped to editor 1's file.
7) Navigate _again_ to my new file.
8) Open new file.

if there's a way to do this already I'm all ears, I've look through the doc and shortcuts, couldn't find anything.

**Comment by bpasero** [comment] 2016-03-08 10:11
dupe of #3062

**Closed by bpasero** 2016-03-08 10:12 UTC
