### ISSUE TITLE
VS code server for WSL failed to start

### ISSUE THREAD

**Issue by GuyLandry98** [microsoft/vscode#142417] opened 2022-02-07 16:35 UTC
Issue Type: <b>Bug</b>

After the upgrade to release 1.64.0, VS code is unable to access the WSL server anymore.  This was working before the upgrade to 1.64.0 and no changes in configurations to either VS code or WSL have been done.

I have the Remote Development extension installed.

The WSL2 is using Ubuntu-20.04 and is running, as shown by the following in a Windows power shell:
PS C:\> wsl --list --running
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)

Also, opening a linux terminal is working, and I am able to run various linux commands normally.

Error message: " VS Code Server for WSL failed ot start. No messages received for 90s Check WSL terminal for more details."

From Terminal output:
[2022-02-07 15:40:11.721] Resolving wsl+ubuntu-20.04, resolveAttempt: 1
[2022-02-07 15:40:11.752] Starting VS Code Server inside WSL (wsl2)
[2022-02-07 15:40:11.752] Extension version: 0.64.2
[2022-02-07 15:40:11.752] Windows build: 18363. Multi distro support: available. WSL path support: enabled
[2022-02-07 15:40:11.752] No shell environment set or found for current distro.
[2022-02-07 15:40:12.188] WSL daemon log file: 
[2022-02-07 15:40:12.190] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 -e sh -c "[ -d ~/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2022-02-07 15:40:12.260] Probing result: x86_64
[2022-02-07 15:40:12.260] No server install found in WSL, needs linux-x64
[2022-02-07 15:40:12.260] Downloading server on client side to C:\Users\xxx\AppData\Local\Temp\vscode-remote-wsl\5554b12acf27056905806867f251c859323ff7e9\vscode-server-stable-linux-x64.tar.gz.
[2022-02-07 15:40:12.260] https://update.code.visualstudio.com/commit:5554b12acf27056905806867f251c859323ff7e9/server-linux-x64/stable
[2022-02-07 15:40:33.613] Unable to download server on client side: Error: Request downloadRequest failed with message: connect ETIMEDOUT 152.199.4.33:443. Will try to download on WSL side.
[2022-02-07 15:40:33.613] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 5554b12acf27056905806867f251c859323ff7e9 stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=3842954554-1902633027 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms'
[2022-02-07 15:40:33.822] Setting up server environment: Looking for /home/xxx/.vscode-server/server-env-setup. Not found.
[2022-02-07 15:40:33.822] WSL version: 5.10.16.3-microsoft-standard-WSL2 Ubuntu-20.04
[2022-02-07 15:40:33.822] Updating VS Code Server to version 5554b12acf27056905806867f251c859323ff7e9
[2022-02-07 15:40:33.822] Removing previous installation...
[2022-02-07 15:40:33.822] Installing VS Code Server for x64 (5554b12acf27056905806867f251c859323ff7e9)
[2022-02-07 15:40:33.822] Downloading:     
[2022-02-07 15:42:04.316] VS Code Server for WSL failed to start. No messages received for 90s
[2022-02-07 15:42:04.316] For help with startup problems, go to
[2022-02-07 15:42:04.316] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2022-02-07 15:42:04.323] WSL Daemon exited with code 0

Note the content of vscode-remote-wsl\555... shows the tar.gz file is size 0, with a time stamp of a few minutes ago:

PS C:\Users\xxx\AppData\Local\Temp\vscode-remote-wsl\5554b12acf27056905806867f251c859323ff7e9> dir

    Directory: C:\Users\xxx\AppData\Local\Temp\vscode-remote-wsl\5554b12acf27056905806867f251c859323ff7e9
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2022-02-07  10:40 AM              0 vscode-server-stable-linux-x64.tar.gz_1644248412261

The site update.code.visualstudio.com is reachable from WSL/linux

~$ curl -Is https://update.code.visualstudio.com
HTTP/1.1 200 Connection established
Proxy-Agent: Fortinet-Proxy/1.0

HTTP/1.1 200 OK
Content-Length: 24
Content-Type: text/plain; charset=utf-8
Vary: Origin
request-context: appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c
X-Powered-By: Express
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Source-Commit: d511c8a222df1cabfdeb1fcc018c44dac4a7f884
Date: Mon, 07 Feb 2022 16:14:07 GMT

And is also reachable from the Windows side. 
I get the "Hello from VS Code!" using Microsoft Edge.

The IP address 152.199.4.33 mentioned in the error message at [2022-02-07 15:40:33.613] can be reached from the client side (Powershell)

PS C:\> ping 152.199.4.33
Pinging 152.199.4.33 with 32 bytes of data:
Reply from 152.199.4.33: bytes=32 time=21ms TTL=47

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Connection to 'WSL: Ubuntu-20.04' could not be established  VS Code Server for WSL failed to start. No messages received for 90s
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (25.09GB free)|
|Process Argv|--crash-reporter-id 5a37b615-9284-4e2e-ab87-0a4eb4fb8a3b|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu-20.04' could not be established  VS Code Server for WSL failed to start. No messages received for 90s
Check WSL terminal for more details.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710cf:30416617
vscscmwlcmc:30433760

```

</details>

**Comment by aeschli** [comment] 2022-02-07 17:20
Duplicate of https://github.com/microsoft/vscode/issues/142201

**Comment by GuyLandry98** [comment] 2022-02-07 17:25
I can confirm that the issue is with 1.64.0.

I have replaced my installation with 1.63.2.  At start up VS code said it needed to have WSL server installed, and do I want to install it.  I click yes, and everything came up and is working correctly.

**Comment by cyancirrus** [comment] 2022-02-14 16:49
@GuyLandry98 if it's only vscode 1.64.0, click "close remote connection" after you open vscoe on the windows side --it looks like the remote connection/server instance needs to be refreshed

**Comment by GuyLandry98** [comment] 2022-02-14 20:59
Upgrading to 1.64.2 has resolved the problem for me.
I did not have to do "close remote connection" as suggested.

**Closed** 2022-02-21 16:31 UTC
