### ISSUE TITLE
Extensions publish do not warn/error on invalid extensionDependencies

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12907] opened 2016-09-28 17:19 UTC
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04
#12647

I published an extension without errors with the following extensionDependencies:

``` js
    "extensionDependencies": [
        "Tyriar.sort-lines@1.0.0",
        "Tyriar.lorem-ipsum"
    ]
```

It published fine but when installed it only installs `Tyriar.lorem-ipsum`.

**Comment by sandy081** [comment] 2017-11-20 11:36
Added a warning for invalid identifiers, but not for non-existing one.

**Comment by mjbvz** [comment] 2017-12-05 22:30
@sandy081 I see the entry now marked in vscode

<img width="272" alt="screen shot 2017-12-05 at 2 28 15 pm" src="https://user-images.githubusercontent.com/12821956/33634314-9cffef56-d9c8-11e7-9b89-25296d0c7fb1.png">

Two questions about the expected behavior though:

- Should `"Tyriar.sort-lines@1.0.0"` generate warnings or errors when you run `vsce publish` on the command line?
- Should entries for non-existant packages such as `"nonsuch.package"` generate errors?

**Comment by sandy081** [comment] 2017-12-07 08:49
@mjbvz 

> Should "Tyriar.sort-lines@1.0.0" generate warnings or errors when you run vsce publish on the command line?

Yes, it does not allow

> Should entries for non-existant packages such as "nonsuch.package" generate errors?

VSCE will publish them as new extensions if does not exist. I am not showing any squiggles for non-existent packages. It is just for invalid identifiers.

**Comment by mjbvz** [comment] 2017-12-07 23:50
Ok, I'm still allowed to vsce publish an extension with errors for `"Tyriar.sort-lines@1.0.0"`  using vsce 1.35.0

Reopening

**Comment by sandy081** [comment] 2017-12-08 08:25
@mjbvz I see what you mean. Currently VSCE only validates extension names not extension dependencies. I meant this in my above comment. Sorry, I was not clear.

Fix here is to show only squiggles for invalid extension dependencies. 

Created an issue in VSCE to validate extension dependencies while publishing - https://github.com/Microsoft/vscode-vsce/issues/227

Since you confirmed the squiggles, I am closing this as verified.

**Closed by sandy081** 2017-12-08 08:25 UTC
Labels: bug, extensions, verification-found
