### ISSUE TITLE
On startup, only have menu bar and status bar at top

### ISSUE THREAD

**Issue by ChadMcCaffery** [microsoft/vscode#117920] opened 2021-03-01 19:58 UTC
Issue Type: <b>Bug</b>

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (22.78GB free)|
|Process Argv|--crash-reporter-id 5e7fed8b-d57d-47d5-b701-62d0c82bb2ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.2
markdown-mermaid|bie|1.9.2
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
gitlens|eam|11.2.1
vscode-test-explorer|hbe|2.19.5
vscode-favorites|how|1.8.3
vscode-simple-icons|Lau|1.13.5
node-module-intellisense|lei|1.5.0
rainbow-csv|mec|1.8.1
azure-pipelines|ms-|1.183.0
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
remote-containers|ms-|0.158.0
azure-account|ms-|0.9.6
azurecli|ms-|0.5.0
powershell-preview|ms-|2021.2.1
vs-keybindings|ms-|0.2.0
unique-window-colors|stu|1.0.51
vscode-xslt|szu|0.2.0

</details>

## Repro Steps
This has only happened twice, so I don't have any repro steps yet. I think it might be that VS Code isn't playing nice with Windows docking behavior? [Win]+[Up/Dn Arrow]  :thinking:

## Screenshot
![image](https://user-images.githubusercontent.com/22089594/109550289-ef5bb000-7a83-11eb-8e56-147f55c800b3.png)

**Comment by ChadMcCaffery** [comment] 2021-03-01 20:04
Just discovered that this looks like #114459

**Comment by IllusionMH** [comment] 2021-03-01 20:43
This one actually looks like duplicate of #116542

Do you see any errors in you use **Help** > **Toggle Developer Tools**?

Are you able to reproduce this issue in Insiders builds? https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment] 2021-03-02 06:33
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed** 2021-03-09 11:32 UTC
Labels: needs more info
