### ISSUE TITLE
Terminal random missing first character because parsing data " $[K[1C" [[13,36,27,91,75,27,91,49,67]]

### ISSUE THREAD

**Issue by quyenvsp** [microsoft/vscode#187804] opened 2023-07-13 08:27 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0 (user setup)
- OS Version: Windows 11 10.0.22631
- Git bash for Windows: 2.41.0.windows.1

Steps to Reproduce:

1. type `gitk --all` in terminal
2. it will random sometime missing first character -> `itk --all`
3. check terminal trace log showing `parsing data "
$[K[1C" [[13,36,27,91,75,27,91,49,67]]`

```
2023-07-13 15:07:52.341 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:07:52.341 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:07:52.341 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:07:52.341 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
2023-07-13 15:07:52.354 [trace] terminalMultiLineLinkDetector#detect text ["$"]
2023-07-13 15:07:52.354 [trace] terminalLocalLinkDetector#detect text ["$"]
2023-07-13 15:07:52.355 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:07:53.113 [debug] sending data "g" [[103]]
2023-07-13 15:07:53.129 [debug] parsing data "
$[K[1C" [[13,36,27,91,75,27,91,49,67]]
2023-07-13 15:07:53.187 [debug] sending data "i" [[105]]
2023-07-13 15:07:53.208 [debug] parsing data "i" [[105]]
2023-07-13 15:07:53.297 [debug] sending data "t" [[116]]
2023-07-13 15:07:53.315 [debug] parsing data "t" [[116]]
2023-07-13 15:07:53.392 [debug] sending data "k" [[107]]
2023-07-13 15:07:53.423 [debug] parsing data "k" [[107]]
2023-07-13 15:07:54.395 [trace] terminalMultiLineLinkDetector#detect text ["$ itk"]
2023-07-13 15:07:54.395 [trace] terminalLocalLinkDetector#detect text ["$ itk"]
2023-07-13 15:07:54.395 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:07:54.546 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:07:54.546 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:07:54.546 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:07:54.546 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
2023-07-13 15:09:57.693 [trace] terminalMultiLineLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:57.694 [trace] terminalLocalLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:57.694 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:09:58.312 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:58.312 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:58.312 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:09:58.313 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
2023-07-13 15:09:58.432 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:58.432 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:58.433 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:09:58.433 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
2023-07-13 15:09:58.472 [trace] terminalMultiLineLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:58.472 [trace] terminalLocalLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:58.473 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:09:59.339 [trace] terminalMultiLineLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:59.339 [trace] terminalLocalLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:59.340 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:09:59.353 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:59.353 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:59.353 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:09:59.353 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
```
![2023-07-13_150933](https://github.com/microsoft/vscode/assets/35319492/efb01a1e-71d4-4c45-ac87-a3d8edbcb000)

**Comment by meganrogge** [comment] 2023-07-24 14:22
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-07-24 14:22 UTC
