### ISSUE TITLE
Is it Possible to add live collaborative editing?

### ISSUE THREAD

**Issue by techsin** [Microsoft/vscode#36932] opened 2017-10-25 19:02 UTC
Something like this would be very cool.

Say, I want to get other people to work with me on a project, live... no github etc. 
Think Google docs, where multiple people can start typing on the same page.

I'm a host, and I share my url through slack. 

My friend gets the url, clicks it and it opens up vscode on his side.

And now his Vscode is directly connected to my workfolder.

- He can bring files his files into my workspace by drag and drop into sidebar, which actually copies file into my computer.
- He can run terminal commands in his vscode terminal, and  they run on my computer. 
- He can run browser within vscode and go to localhost, which works because VScode is sort of like virtual desktop connected to him via P2P, and i can see him as scroll and click things as if it was me.
- If we both are editing same file, then his cursor is visible in my file and it live updates the file as does mine on his side.
- if person is editing a different file, then on sidebar file gets highlighted by color of person editing it
- voice chat

If this can be done, It'd be possible to Pair Program like never before. Not even for remote purposes. Just sitting across the table working on one codebase.

It'd be revolutionary and awesome. 

Please add this feature.

**Comment by mmorrell** [comment] 2017-10-25 19:05
Use a VNC/Teamviewer-like solution. Way too feature rich for a lightweight code editor.

**Comment by techsin** [comment] 2017-10-25 19:10
Google doc is lightweight and it has this, so @mmorrell i dont think having this makes editor heavy, it's invisible feature that is only active when user wishes to engage in it.

**Comment by techsin** [comment] 2017-10-25 19:11
Google docs is light weight, and yet it has live collaborative editing.

**Comment by jamesgecko** [comment] 2017-10-25 19:43
I doubt we'll get it in the main editor, but that sounds like an amazing idea for plugin. It'd take a huge amount of work to implement.

**Comment by ravshansbox** [comment] 2017-10-25 20:17
Maybe an extension candidate?

**Comment by techsin** [comment] 2017-10-26 01:02
I've not built VScode ext before. But it'd need to simulate workspace and that makes me think that it'd be more of a core feature.

**Comment by techsin** [comment] 2017-10-26 01:03
also i think this has a wrong tag, workbench, should be feature request.

**Comment by Calinou** [comment] 2017-11-16 12:39
This issue is probably a duplicate of https://github.com/Microsoft/vscode/issues/15916?

**Comment by bpasero** [comment] 2017-11-16 18:06
And see: https://code.visualstudio.com/blogs/2017/11/15/live-share

**Closed** 2017-11-16 18:05 UTC
Labels: feature-request, workbench
