### ISSUE TITLE
Old casing returns when clicking onto editor header

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#113277] opened 2020-12-22 08:21 UTC
* I have used the TS refactoring to extract a class into a separate file, it created `src/vs/workbench/contrib/outline/browser/OutlineViewState.ts` (upper-case `O`)
* I renamed the file file to `outlineViewState.ts`, closed all editors
* The name appears correctly in the explorer
* The name appears correctly in a new editor
* 🐛 The name changes to its old casing when clicking into the title (see video)

https://user-images.githubusercontent.com/1794099/102866075-ff796280-4436-11eb-9052-cf7e32555bd7.mov

**Comment by bpasero** [comment] 2021-01-04 11:30
I tried with a more minimal repro, excluding TS refactoring:
* created `OutlineViewState.ts`
* renamed (from explorer) to `outlineViewState.ts`
* closed all editors
* clicked on `outlineViewState.ts` in explorer
* clicked on title to bring up quick pick and selected the file again

=> the casing does not change.

Does that reproduce?

**Comment by jrieken** [comment] 2021-01-04 11:36
> I tried with a more minimal repro, excluding TS refactoring:

Why? Didn't my steps reproduce this?

**Comment by bpasero** [comment] 2021-01-04 12:51
@jrieken here is what I try to reproduce without luck:

![recording](https://user-images.githubusercontent.com/900690/103537028-e390aa80-4e93-11eb-90d9-8203810338b7.gif)

**Comment by jrieken** [comment] 2021-01-04 13:33
🤷 hm... I did write those steps from my memories, so there might be something missing. Tho, the recording is real, no deep fake

**Comment by bpasero** [comment] 2021-01-04 13:42
Ok, I will try to reproduce a bit more and check in code how this could happen, but might have to close this if I cannot.

**Comment by m417z** [comment] 2021-01-16 10:09
I noticed this issue as well. Here's a simple way to reproduce the issue.

![QITQiHvEfd](https://user-images.githubusercontent.com/4129781/104809100-81209e00-57f3-11eb-81a2-8919ccdf4e37.gif)

**Comment by bpasero** [comment] 2021-01-16 11:59
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by m417z** [comment] 2021-01-16 12:13
I wasn't able to reproduce it with an insider build, looks like it was fixed.

**Comment by bpasero** [comment] 2021-02-01 09:53
I was able to reproduce this, though not exactly like the video shows, here is what can happen:
* you open a file in one casing and it is added to history
* you rename the file to same name but different case
* we likely miss a file event in this case (file watchers often have issues with renames to same name but different case)
* as such the history entry does not update
* when you open from history you get back the previous casing

I pushed a change to let our history listen to internal file operations as well. With those we can track renames and properly update the entry to the proper case.

Interestingly this broke a while ago when we adopted canonical resources because I think we used to close and reopen the editor even when just the case changes but we no longer do so.

**Closed by bpasero** 2021-02-01 09:53 UTC
Labels: bug, workbench-editors

**Comment by jrieken** [comment] 2021-02-25 12:50
@bpasero Any idea how to verify this? Looked into the change as well but that seems non-minimal wrt to the described fix

**Comment by bpasero** [comment] 2021-02-25 13:10
Yeah https://github.com/microsoft/vscode/issues/113277#issuecomment-770728139 has steps how I noticed it related to the fact that the editor history was not updating itself from editor move events.

**Comment by alexr00** [comment] 2021-02-26 15:05
After rename, the file is no longer in my history list. Intentional?
1. Open file. Make sure it's not in preview.
2. In the Explorer view, change the case of a letter in file name.
3. Close the file.
4. ctrl+p to open the file
5. I expected to see the file at the top of my recent files, but it wasn't in my recent files at all. I had to search for the file.

**Comment by bpasero** [comment] 2021-02-26 15:22
![recording (1)](https://user-images.githubusercontent.com/900690/109319156-d7e7b180-784e-11eb-89a5-c21c5ce365b5.gif)

I am not seeing an issue here.

**Comment by alexr00** [comment] 2021-02-26 15:47
@bpasero I think you're not seeing the issue because you are clicking in the text document. If you don't click in the text document, do you see the issue?

**Comment by alexr00** [comment] 2021-02-26 15:51
![Uploading recording (45).gif…]()

**Comment by bpasero** [comment] 2021-02-26 16:02
No I even see this working fine when I don't click into the editor. Do your steps reproduce on a Unix system?

**Comment by alexr00** [comment] 2021-02-26 16:27
No, my steps do not repro on a Unix system.
