### ISSUE TITLE
"No quick fixes available" in problem popup is noise

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [microsoft/vscode#86933] opened 2019-12-13 14:43 UTC
If there was a quick fix, I would see it. It's redundant to explicitly state that there are no quick fixes.

Visual clutter:
![image](https://user-images.githubusercontent.com/302938/70807871-811fc480-1dcf-11ea-8fa3-728e86cde0d9.png)

It would be better like this:
![image](https://user-images.githubusercontent.com/302938/70807884-87ae3c00-1dcf-11ea-9a11-ba1b6b9eb8a1.png)

VSCode Version: 1.41.0

**Comment by mjbvz** [comment] 2019-12-13 18:44
The initial reason for this: it looks sort of weird if there is a progress spinner while we compute quick fixes and then the spinner just disappears without any feedback

**Comment by misolori** [comment] 2019-12-13 18:50
Also, it's for giving users an indication that there are no fixes. If it were left blank then users might think it's broken and not know why it doesn't show. So I'd say this is by design.

**Comment by mjbvz** [comment] 2019-12-13 19:38
Agreed, closing as by-design

**Closed by mjbvz** 2019-12-13 19:38 UTC
Labels: editor-code-actions, new release, ux

**Comment by Vlad-Shcherbina** [comment] 2019-12-13 21:30
@mjbvz, I agree that disappearing spinner is a concern, and your solution is a valid one. I think slightly better solutions exist, but perhaps it's not worth it to spend effort and complexity budget on this. However, if you are interested, I'd be happy to share my thoughts.

------

@misolori, you are optimizing for a rare scenario to the detriment of a common scenario (hopefully problems are significanly less likely than a simple lack of quick fixes).
Besides, "No quick fixes available" also could be incorrectly interpreted as an error message.

**Bad**
![image](https://user-images.githubusercontent.com/302938/70829177-0fab3a80-1dfe-11ea-8c98-f1035e68fb1c.png)

**Good**
![image](https://user-images.githubusercontent.com/302938/70829198-18037580-1dfe-11ea-8944-b4533102bb89.png)
