### ISSUE TITLE
Allow extensions to get TextDocument character encoding

### ISSUE THREAD

**Issue by Dickurt** [Microsoft/vscode#11690] opened 2016-09-08 13:35 UTC
Currently I am writing an extension that reads (part of) the active document and writes the file's content to an external file. The content of the external file will then be altered, after which the content will be put back into the original file (active document).

The issue here is that there is no way to be absolutely sure which character encoding the external file uses. So, when trying to read from the external file, the encoding has to be guessed. This is not very reliable, of course. The same goes for writing to that file.

So, in code this looks like:

```
var fs = require('fs');

// [...]

var activeDocumentContent = vscode.window.activeTextEditor.document.getText();
fs.writeFileSync('myfile.txt', activeDocumentContent, {encoding: 'utf8'});

// [...] do stuff to the external file

fs.createReadStream('myfile.txt', {encoding: 'utf8'});
```

It would be great if there was a way to get the document's encoding, like so, for example:

`vscode.window.activeTextEditor.document.getEncoding();`

The workaround at the moment is to use a package that detects character encodings.

**Comment by ramya-rao-a** [comment] 2016-09-08 18:55
Duplicate of #824 
@Dickurt upvote #824 to give it more support

**Closed by ramya-rao-a** 2016-09-08 18:55 UTC

**Comment by Dickurt** [comment] 2016-09-08 19:14
Couldn't find that one while searching. Will continue there.
Thanks for the link!
