### ISSUE TITLE
Incorrect automatic import path for React in JavaScript projects

### ISSUE THREAD

**Issue by gpoole** [microsoft/vscode#146297] opened 2022-03-30 05:44 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0-insider (Universal)
- OS Version: macOS 12.2.1 (21D62)

Steps to Reproduce:

1. Create a new Next.js project using `npx create-next-app@latest` (which is using React 17.0.2)
2. Open the project and type a React function such as `useState`

The suggestions all point to `react/cjs/react.production.min`, `react/cjs/react.production` or `react/cjs/react.development`.

Same problem as https://github.com/microsoft/TypeScript/issues/47601 but this is a JavaScript project, not a TypeScript project.

**Comment by mjbvz** [comment] 2022-03-30 07:00
Please try upgrading your TS version as covered in the linked issue: https://github.com/microsoft/TypeScript/issues/47601#issuecomment-1021599387

**Comment by gpoole** [comment] 2022-03-30 23:03
It does fix the problem but there's no issue open I can see tracking this for JavaScript projects specifically in VSCode and it's still present in the latest Insiders. Do you have an issue open that people can follow for tracking the underlying problem or which VSCode version it's going to be fixed in please?

**Comment by mjbvz** [comment] 2022-03-30 23:42
Thanks for testing. TypeScript powers VS Code's JS intellsense too so this is a duplicate of that linked issue

It will be fixed when we pick up the new TS version (or you can use the nightly TS extension until then)

**Closed by mjbvz** 2022-03-30 23:42 UTC
Labels: needs more info
