### ISSUE TITLE
The chinese file name is garbled when searching

### ISSUE THREAD

**Issue by Greyh4t** [microsoft/vscode#138386] opened 2021-12-03 04:04 UTC
Open the project in the vscode, and turn on the "Enable indexing" mode in the search function. At this time, the Chinese file name will be garbled in the search result, And cannot jump to the file after clicking the search result
In addition, my browser is in Chinese mode

![无标题](https://user-images.githubusercontent.com/8017380/144543416-71f91958-2b0a-452f-94c5-1457fcc34f44.png)

![无标题](https://user-images.githubusercontent.com/8017380/144544002-66beceb7-f01a-4873-8c2b-41e8e29ed4a6.png)

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Embedder: github.dev

**Comment by gjsjohnmurray** [comment] 2021-12-03 05:36
Maybe #135077

**Comment by Greyh4t** [comment] 2021-12-03 05:43
> Maybe #135077

It’s not the same, my file content is utf-8, and the file content is not garbled, just the file title is garbled. files.encoding of vscode is UTF-8

**Comment by yume-chan** [comment] 2021-12-03 06:22
Duplicate of #136276, or maybe a regression, because https://github.com/microsoft/vscode/issues/136276#issuecomment-964717244 says it was fixed in 1.62.

**Comment by Greyh4t** [comment] 2021-12-03 06:31
> Duplicate of #136276, or maybe a regression, because [#136276 (comment)](https://github.com/microsoft/vscode/issues/136276#issuecomment-964717244) says it was fixed in 1.62.

I tested https://github.com/imba-tjd/test2 in 1.62.3, and the problem still exists

**Comment by gjsjohnmurray** [comment] 2021-12-03 11:22
Does the problem also happen if you use https://insiders.vscode.dev/ instead?

**Comment by Greyh4t** [comment] 2021-12-03 11:48
> Does the problem also happen if you use https://insiders.vscode.dev/ instead?

No, at https://insiders.vscode.dev/ it working fine

![image](https://user-images.githubusercontent.com/8017380/144597721-8e72115c-2409-4da5-89dc-46463bc23a07.png)

**Comment by gjsjohnmurray** [comment] 2021-12-03 12:07
So it should be fine in 1.63 which is expected to release later this week.

**Closed** 2021-12-09 12:43 UTC
