### ISSUE TITLE
DAP's progress events do not show on status bar if they end within 500ms

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#101405] opened 2020-06-30 13:14 UTC
I switched some progress events over to the DAP ProgressStartEvent recently but discovered that there's a delay of 500ms before these progress events appear:

https://github.com/microsoft/vscode/blob/5de3aa7eace377f095000787129534a11b54734f/src/vs/workbench/contrib/debug/browser/debugProgress.ts#L49

And although the ProgressEndEvent takes a "final message", it's never used by VS Code.

The result is that short-lived progress messages (for example hot reloading an app) the message is never shown to the user (this has come up a few times - for example https://github.com/Dart-Code/Dart-Code/issues/2597).

It feels like a debug adapter should have some control over this - right now I need to decide between:

- Doing nothing and having users confused about whether the hot reload ran
- Put a fake delay of 500ms in before sending the `ProgressEndEvent` - this makes the progress visible, but it's delayed by half a second which is also confusing
- Switching back from DAP requests to using my own custom events and displaying my own progress

I think it would be better if the delay was removed (and left to the DA), reduced, or DAP-provided and the `ProgressEndEvent's` final message was displayed for a short period after it arrived.

(cc @isidorn - delay was added in a47badb3d682b079e59e3f852f5bffdd29377915)

**Comment by isidorn** [comment] 2020-06-30 13:26
Correct, we intentionaly introduced a delay so that short running progress would not "spam" the user.
This was a design decision by @weinand and me.
However we could give more control to the debug extension over this. I am open to ideas.

**Comment by DanTup** [comment] 2020-06-30 13:38
IMO if the DAP is sending a progress event, it's probably something useful to the user. If there are a lot of things going on in quick succession, they should probably be a single progress ID which would just update the text anyway. I think the faster the user has feedback that something is happening after they pressed a button, the better.

I think regardless of the delay, if the `ProgressEndEvent` has a `message`, it should be updated and shown for at least some short period (that seems to be what the DAP spec suggests would happen) - although it may also look better if the spinner was hidden for that final message (since when I tried implementing this manually, it looked weird to have a spinner alongside a message saying "Hot reload complete"!).

**Comment by weinand** [comment] 2020-06-30 14:38
I agree with @DanTup that dropping the final message if the progress ends before the 500ms delay isn't helpful.

Dan's proposal in the previous comment makes sense to me:
- keep the delay and show no progress if the progress ends before the 500ms.
- but if `ProgressEndEvent` has a message, then show it.

**Comment by isidorn** [comment] 2020-06-30 14:39
Assigning to June to investigate more tomorrow.

**Comment by weinand** [comment] 2020-06-30 14:43
@isidorn since the current behavior is neither new nor a regression, I don't think that we have to rush this into the June release. But if the change is **low-risk** you can try...

**Comment by isidorn** [comment] 2020-06-30 14:46
Agree. Assigned it to june just for investigation. Only if the change is low-risk we will do it.

**Comment by DanTup** [comment] 2020-06-30 14:48
I'm planning on shipping a fix today that moves back off the DAP progress to my own (but implemented to more closely match how the DAP progress works) so no need to rush this on my account - I can move back over once it's done.

(that said, while using the message from the finished event would be better, the 500ms delay still feels very long to me - if it's kept, would it be a concern to shorten it to something much lower?)

**Comment by weinand** [comment] 2020-06-30 15:26
I agree, 500ms is too long. I think initially I proposed 300ms

**Comment by DanTup** [comment] 2020-06-30 16:34
Is there a reason it can't be really short (like 50-100ms)? Is it really likely DAs are going to spam it? (they can already spam it by just using their own events, as they did up until now). The longer the delay between a user pressing something and them seeing feedback, the less attractive using this API is because it makes things feel slower.

I also think the DAP spec should give some guidelines here - if DA authors assume they should do their own debouncing (which some editors may assume), that will introduce a delay. If VS Code then adds *another* delay, it'll be even slower. It makes it hard for DA authors when clients behave differently, so I think the spec should guide them in the same direction.

**Comment by weinand** [comment] 2020-06-30 17:11
In my proposal the delay does not affect the appearance of the progress end message.
If there is an end message, it comes immediate (even before the delay).

So the following is not true:
> The longer the delay between a user pressing something and them seeing feedback, the less attractive using this API is because it makes things feel slower.

**Comment by DanTup** [comment] 2020-06-30 17:28
> If there is an end message, it comes immediate (even before the delay).
>
> So the following is not true:
> 
> > The longer the delay between a user pressing something and them seeing feedback, the less attractive using this API is because it makes things feel slower.

That's true for an operation that completes quickly, but not for one that doesn't. For example, say a hot reload usually takes 50ms. They'll be used to pressing Save and seeing the "Hot reload completed!" message after around 50ms.

However, in the case where the hot reload takes longer (say 1s), it would still be the full delay period before they saw anything at all. While 300ms is probably short enough that they won't go hitting Save again, it's still a noticable delay if they're used to seeing something appear much quicker.

> We just have to avoid that every tiny operation triggers the whole progress UI to appear which results in lots of flicker.

I understand this - but the current design feels compromising for good extensions (that want immediate feedback, but will use the progress sparingly) in order to prevent this. How about making the debounce optional but enabled by default? This would allow DA to provide immediate feedback when it works better (like Hot Reload) but still generally prevent flicker?

**Comment by DanTup** [comment] 2020-07-01 11:17
Btw - I had [this feedback](https://github.com/Dart-Code/Dart-Code/issues/2597#issuecomment-652204865) suggesting the status bar notifications may not be obvious enough (in Dart/Flutter we used to show full notification statuses when performing things like hot reload).

I'd still like to move over to the DAP messages (because there are other editors using this debug adapter, even though it wasn't written with that in mind initially), but maybe there could be some control over this (not necessarily in DAP, but maybe in VS Code for a user to control whether these notifications are status bar or expanded by default?).

I think progress messages tend to fall into two fairly distinct categories:

- things like "Analyzing...", where we want to show something is happening, but it's not directly related to what the user is doing
- things like hot reload/launching/building - something specifically started by the user and that they are waiting for to complete

The first ones probably never want to be expanded by default, but the second type I think could (it's something I'd like myself - sometimes when I press F5 to launch my extension when working on it, I wonder why nothing is happening, and the only indication is "Building..." in the status bar - I'd rather the expanded notification).

**Comment by isidorn** [comment] 2020-07-01 12:46
Nothing for endgame, moving it out of this milestone

We are open for PR that fix this
Code pointer https://github.com/microsoft/vscode/blob/f9c46ad5538e19396ef125ca0ba5e1b700873686/src/vs/workbench/contrib/debug/browser/debugProgress.ts#L28

**Closed** 2020-11-02 18:05 UTC
Labels: *out-of-scope, debug, under-discussion

**Comment by DanTup** [comment] 2020-11-02 18:09
>  If you disagree and feel that this issue is crucial

I don't think it's crucial, but it seems a little weird the API lets you send a progress message and then an "end" message, but neither will appear if the total duration was under half a second.

I moved Dart back to using custom messages and its own progress notifications instead of the standard ones now (which makes the experience worse for other DAP clients because they don't get them). Users don't like not seeing these progress notifications to know that something like a hot reload occurred and completed.
