### ISSUE TITLE
Fluent design theme

### ISSUE THREAD

**Issue by Chandrawk27** [microsoft/vscode#88021] opened 2020-01-03 02:27 UTC
Issue Type: <b>Feature Request</b>

I am tired of trying various types of themes available in the extension. At the moment I have not found another interesting theme. Looks like if VS Code makes the theme "fluent design" will look attractive, cool and elegant.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by misolori** [comment] 2020-02-03 18:50
Duplicate of #26572

**Closed by misolori** 2020-02-03 18:50 UTC
Labels: feature-request, themes
