### ISSUE TITLE
Issue reporter cannot report issues

### ISSUE THREAD

**Issue by wolf99** [microsoft/vscode#97378] opened 2020-05-09 22:59 UTC
Issue Type: <b>Bug</b>

Any time I have used the issue reporter from VSCode, upon clicking the "Preview on GitHub" button it reports:

![image](https://user-images.githubusercontent.com/281700/81486970-ee396800-9250-11ea-90bb-89cf0523acb6.png)

I think I don't have a huge list of extensions (relatively speaking) to list to be included so maybe _aby_ list of extensions results in too large a message?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.1
todo-tree|Gru|0.0.174
plantuml|jeb|2.13.8
python|ms-|2020.4.76186
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.27.1
material-icon-theme|PKi|4.1.0
java|red|0.61.0
vscode-xml|red|0.11.0
glassit|s-n|0.2.0
code-settings-sync|Sha|3.4.3
vscode-checkstyle|she|1.3.2
code-spell-checker|str|1.8.0
open-in-browser|tec|2.0.0
shellcheck|tim|0.9.0
shell-launcher|Tyr|0.4.1
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.10.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.3

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2020-05-10 02:26
See https://github.com/microsoft/vscode/issues/60237#issuecomment-428259472

**Comment by RMacfarlane** [comment] 2020-05-13 22:00
Yeah, the url length limit is unfortunately very easy to hit, it's 2045 characters total. 

I want to get rid of this dialog entirely by being able to use GitHub account info and directly create the issue instead: https://github.com/microsoft/vscode/issues/95165

I'm going to close this since this is currently expected behavior, but this is on the radar as something to improve

**Closed by RMacfarlane** 2020-05-13 22:00 UTC
