### ISSUE TITLE
[JavaScript] `var` is colored as a keyword even if it is a part of variable name

### ISSUE THREAD

**Issue by vladimir-kotikov** [Microsoft/vscode#3738] opened 2016-03-05 12:43 UTC
![image](https://cloud.githubusercontent.com/assets/3857604/13547555/f566763e-e2e8-11e5-92a3-ac69cad667fa.png)

**Comment by Nimzozo** [comment] 2016-03-05 13:07
what theme are you using @vladimir-kotikov ?

**Comment by vladimir-kotikov** [comment] 2016-03-05 13:50
This particular theme is `Monokai` from VS Code insiders. But it is displayed this way with a couple of other themes (incl. `Dark+`, `Red` and `Solarized light`)

**Comment by Nimzozo** [comment] 2016-03-05 14:51
There is no such problem with Dark (Visual Studio) theme.

**Comment by Tyriar** [comment] 2016-03-05 18:29
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by Tyriar** 2016-03-05 18:29 UTC
