### ISSUE TITLE
Could not load welcome page

### ISSUE THREAD

**Issue by nagarjunr** [microsoft/vscode#125522] opened 2021-06-04 15:37 UTC
Issue Type: <b>Bug</b>

Similar to this: https://github.com/microsoft/vscode/issues/124386

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.22GB free)|
|Process Argv|--crash-reporter-id a8de8d03-2d32-4831-9b44-1298b213416c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.12.0
vscode-blink-mind|awe|0.0.10
vscode-django|bat|1.6.0
vscode-eslint|dba|2.1.20
bootstrap-4-cdn-snippet|eve|1.12.0
cortex-debug|mar|0.3.12
git-graph|mhu|1.30.0
vscode-azureappservice|ms-|0.22.0
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.13.0
vscode-dotnet-runtime|ms-|1.1.0
vscode-aks-tools|ms-|0.0.8
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
debugger-for-chrome|msj|4.12.12
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
vscode-yaml|red|0.19.2
LiveServer|rit|5.6.1
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.14
azure-iot-edge|vsc|1.24.0
azure-iot-toolkit|vsc|2.16.6
azure-iot-tools|vsc|0.3.0
vscode-iot-device-cube|vsc|0.3.0
vscode-iot-workbench|vsc|0.16.0
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30312182
vscod805:30301674

```

</details>

**Comment by misolori** [comment] 2021-06-04 19:31
Duplicate of #124386

**Closed by misolori** 2021-06-04 19:31 UTC
