### ISSUE TITLE
React Intellisense Bug

### ISSUE THREAD

**Issue by xuqingkai666** [Microsoft/vscode#41123] opened 2018-01-04 01:54 UTC
- VSCode Version: 1.19.1
- OS Version: windows 7

Steps to Reproduce:

1. at the setting tab ,

``
"emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
``

2. and in the .js or .jsx file，

3.
#### without one space ,i can't get any Intellisense 
![_vscode2](https://user-images.githubusercontent.com/30168674/34547251-c36f2b60-f134-11e7-8d3d-808e0beeb538.png)
4.
#### but in the end of  div tag ,give it one space ,i can get Intellisense .i think it's a bug  
![_vscode3](https://user-images.githubusercontent.com/30168674/34547253-c7e454cc-f134-11e7-89f1-30e6c5047330.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2018-01-04 01:55
Duplicate of #40941

**Closed by mjbvz** 2018-01-04 01:55 UTC
Labels: javascript
