### ISSUE TITLE
Strange cut and paste behavior

### ISSUE THREAD

**Issue by RandomString123** [Microsoft/vscode#42543] opened 2018-01-30 21:01 UTC
- VSCode Version: 1.19.3
- OS Version: Windows 10

The below example is for Julia when I thought it was that extensions causing the problem.  Since then I have also tried with this basic typescript to get the same behavior.
```ts
function test(arg1,
              arg2,
              arg3) {
    alert("yay");                
}
```
If you put this code into a Julia file
```julia
function Test(param1:Any
              param2: Any
              Param3:Any)
    printf("Happy Stuff")
end
````
And then copy and paste it into another file vscode mushes everything to the left.  Notice the printf line now has no indentation and the  params moved left one. 
```julia
function Test(param1:Any
    param2: Any
    Param3:Any)
printf("Happy Stuff")
end
```

However if you copy and paste the code below which is formatted as vscode wants to format it by default, then the code remains unchanged after the paste.
```julia
function Test(param1:Any
    param2: Any
    Param3:Any)
    printf("Happy Stuff")
end
````

Does this issue occur when all extensions are disabled?: No, However this does happen when I have no extensions installed but run code without the --disable-extensions flag.

**Comment by alexandrudima** [comment] 2018-01-31 11:26
This is something you could turn off via `editor.autoIndent`

**Comment by RandomString123** [comment] 2018-01-31 13:06
That does work to fix the editor from re-formatting the code.  

However, the reason I noticed it is the horrible job the auto-indent does at indenting the code.  It decides that the correct indention for the method body is left justified.  I don't know of anyone who would say this is the correct indention of this code.
```ts
function test(arg1,
    arg2,
    arg3) {
alert("yay");
}
```

**Comment by rebornix** [comment] 2018-09-19 23:31
Duplicate of #30859 , let's track it there.

We don't have good support for auto indentation of multiple line of expressions, right now you can disable auto indent by `editor.autoIndent` and use a formatter which supports this style.

**Closed** 2018-09-19 23:31 UTC
Labels: *duplicate, bug, editor-autoindent
