### ISSUE TITLE
[jade/pug] Block Expansion (nested tags) syntax highlighting broken

### ISSUE THREAD

**Issue by Tenrys** [Microsoft/vscode#65983] opened 2019-01-03 16:58 UTC
- VSCode Version: 1.30.1
- OS Version: Windows_NT x64 10.0.17763 (1809)

![](https://tenrys.pw/ShareX/2019/Jan/eGGv.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tenrys** [comment] 2019-01-03 20:23
This also seems to be happening... 

![](https://tenrys.pw/ShareX/2019/Jan/zFyi.gif)

**Comment by alexr00** [comment] 2019-01-07 15:22
This issue was moved to davidrios/pug-tmbundle#28

**Comment by neilsoult** [comment] 2019-01-17 18:44
@alexr00 that repo hasn't been updated in 2+ years... Is there a possibility of fixing this for vscode some other way?

**Comment by alexr00** [comment] 2019-01-21 09:00
If you can find another repo that more frequently maintained then I could consider changing to pull the grammar in from a new repo.

**Comment by neilsoult** [comment] 2019-01-22 21:54
@alexr00 great, I will try my best to fork the repo and begin improvements focused on vscode. Can you provide any guidance on how I could create a development environment using a new pug grammar repo/file/bundle on a local machine? The original repo only has instructions on how to use it with Sublime Text and Textmate.

**Comment by alexr00** [comment] 2019-01-23 14:48
I think the easiest way is probably to create an extension from the grammar using the steps [here](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#converting-an-existing-textmate-grammar). Then you can easily test out your changes by running your extension.

**Comment by neilsoult** [comment] 2019-01-25 00:58
@alexr00 thanks for your help, I've started to do some simple exploration and testing, but I've found some inconsistencies, as the grammar seems to work fine in TextMate ( which, as I understand it, it what the grammar files are written for ). So I was wondering, are we absolutely positive that this is indeed a problem with the grammar, and not with VSCode's interpretation / integration with textmate language? After all, if this was a bug with the actual grammar, I would expect to find the syntax highlighting problem in TextMate 2, as well as in VSCode. Since that doesn't appear to be the case, can you help suggest how I can confirm that it is indeed a problem with the grammar file itself?

**Comment by neilsoult** [comment] 2019-01-25 01:20
To follow up, here is what it the [sample.pug](https://github.com/neilsoult/pug-grammar-extension/blob/master/test_pugs/sample.pug) file looks like in both VSCode (dracula theme) and TextMate 2 (default theme)
VSCode:
![screen shot 2019-01-24 at 5 15 02 pm](https://user-images.githubusercontent.com/5273521/51718829-e0c88200-1ffb-11e9-9be9-36f9d736e847.png)
TextMate 2:
<img width="919" alt="screen shot 2019-01-24 at 5 15 37 pm" src="https://user-images.githubusercontent.com/5273521/51718838-ed4cda80-1ffb-11e9-99f9-79b098809863.png">

**Comment by alexr00** [comment] 2019-01-25 11:39
@neilsoult thank you for the additional investigation! I checked the grammar from https://github.com/davidrios/pug-tmbundle in another editor and you are right, it does not appear to be a problem with the grammar. Instead it looks to be an issue with VS Code textmate.

**Comment by msftrncs** [comment] 2019-02-05 08:03
The Jade grammar may suffer from the same issue(s).

**Comment by alexr00** [comment] 2019-03-22 10:25
Closing in favor of the upstream vscode-textmate issue.

**Closed by alexr00** 2019-03-22 10:25 UTC
Labels: upstream
