### ISSUE TITLE
SVGs stretch

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140389] opened 2022-01-10 07:05 UTC
![image](https://user-images.githubusercontent.com/900690/148728759-8c783db6-66ab-47be-a000-5c71da55c70e.png)

**Comment by IllusionMH** [comment] 2022-01-10 12:04
/duplicate of #140400
Marking as duplicate as @joaomoreno already interacted with that issue and set assignment/release.

**Closed** 2022-01-10 12:05 UTC
Labels: *duplicate
