### ISSUE TITLE
tsserver is locking files

### ISSUE THREAD

**Issue by bouchepat** [Microsoft/vscode#29132] opened 2017-06-20 19:22 UTC
I'm developing a Meteor.js application. In the last week, I've been experiencing multiple errors (randomly: ENOTEMPTY, EPERM, EBUSY) during the building process of the app while Visual Code open.

The .meteor folder is included to the **files.exclude**; this is to prevent visual code to scan the files created by meteor during the building process (which would slow down the build process). But this does not seems to work as the code.exe process spikes up during the building process. 
I'm suspecting Visual Code scans the files that Meteor creates and manipulates which triggers the errors.

There are no error when Visual Code is closed.

My understanding is if a folder is marked as to be excluded (files.exclude), then Visual Code should not try to access those files. Please, correct me if I'm wrong.

Issue also referenced: 
#https://github.com/meteor/meteor/issues/8801
![screenshot](https://user-images.githubusercontent.com/18633763/27351694-11f86648-55b3-11e7-99d3-338e58cca06a.jpg)

Any help would be appreciated.

**Comment by bpasero** [comment] 2017-06-21 04:44
@bouchepat there is still a file watcher running that might access those files when they change, there is currently no way to prevent this.

**Comment by Devidian** [comment] 2017-06-21 08:21
I'm currently experiencing the same issues, i often have to close vscode when (re) starting meteor to get it running without issues. When its once running, vscode can stay open until meteor has to rebuild (refreshes work).
Didn't find any solution yet :(

**Comment by enkol** [comment] 2017-06-21 13:20
I'm experiencing similar issues with Ember-CLI apps and it's broccoli build folder /tmp.
On build (in console, outside of vscode), i can watch Code.exe spike from 0.1 to 20% CPU usage once files get created in the /tmp folder (folder empty beforehand).
The same happens on live-rebuilds. Sometimes broccoli sporadic fails here with file permission errors, maybe because Code opened the file at that time? Same issue on build cleanup, where temporary files fail to get cleaned (deleted).

My build times increased a lot lately, assumingly to this issue. I had way faster build times before, that's why i started to look into what's happening on build.
I don't have a clear date, from which on it got worse, probably with Codes April or May release.

My workspace settings are:
```json
{
  "editor.tabSize": 2,
  "files.exclude": {
    "**/.git": true,
    "**/tmp": true
  },
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/docs": true,
    "**/dist": true,
    "yarn.lock": true
  },
   "files.watcherExclude": {
    "**/tmp/**": true,
    "**/dist/**": true,
    "**/bower_components/**": true,
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true
  },
  "eslint.enable" : true,
  "javascript.validate.enable": false,
  "emmet.syntaxProfiles": { "handlebars": "html" }
}
```
After adding `"javascript.validate.enable": false`, i at least got rid of validation errors for files in /tmp , so it seemes that the built-in validator didn't respect the exclude settings at all.

Disabling the eslint addon didn't help, so that shouldn't be the problem origin (also i've an .eslintignore).

**Comment by bouchepat** [comment] 2017-06-21 14:13
Thanks @bpasero, was there any changes recently the way VS code scans the files?
I noticed the errors have severely increased in the last week or 2. 

Also, to add to @enkol; up until now I never closed VS code when building the app and noticed the build process was taking minutes with VS open and it's down to seconds with VS close.

**Comment by bpasero** [comment] 2017-06-21 17:04
Not sure. Can you find out which process is locking the files? That would help.

**Comment by bouchepat** [comment] 2017-06-21 21:00
See below, there are multiple processes Code.exe, I'm not sure how from there I can pass on more information on the culprit.

Here are some observations:

During the **first** build attempt, notice the Memory (135,268 K). Exception **ENOTEMPTY** thrown.
![image](https://user-images.githubusercontent.com/18633763/27405777-c8bb96fa-5687-11e7-865b-88ec5b88e6d6.png)

During the **second** build attempt (without closing VS between first and second attempt), notice the Memory (422,812 K). Exception **ENOTEMPTY** thrown.
![image](https://user-images.githubusercontent.com/18633763/27405895-28d56b56-5688-11e7-9cdc-214f29a5dd20.png)

**After** the **second** build attempt, notice the Memory (626,104 K). The build attempt lasted twice as long as the first attempt.
![image](https://user-images.githubusercontent.com/18633763/27406031-8fc17c9c-5688-11e7-8212-86ff70ee62ba.png)

It seems that the memory keeps increasing during the builds and never get empty if an exception is thrown.

If there is more information needed, let me know how to get it and I'll be happy to pass it on.

**Comment by bpasero** [comment] 2017-06-22 04:18
I was hoping you could use a tool like https://technet.microsoft.com/en-ca/sysinternals/bb896655.aspx?f=255&MSPPError=-2147217396 to find out which process in VS Code is locking the file resources. 

This issue seems very similar to https://github.com/Microsoft/vscode/issues/28013

**Comment by enkol** [comment] 2017-06-22 12:34
For me it is the process ``"C:\Program Files (x86)\Microsoft VS Code\Code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\utils\electronForkStart" "c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useSingleInferredProject --enableTelemetry --cancellationPipeName \\.\pipe\vscode-tscancellation-c4a82e1c70b64ae6ea38-sock*`` which takes so much CPU time once Ember-CLI's broccoli build creates it's temp files.

![code_cpu](https://user-images.githubusercontent.com/4593776/27431813-170ffaf0-574e-11e7-91b1-d200546f1286.png)

SysInternals procmon.exe logs hundreds of thousands file access actions of Code on that time (PID of the above mentioned process) for files in broccoli's build folder `\tmp`, which is on all possible exclude lists (see [previous comment](https://github.com/Microsoft/vscode/issues/29132#issuecomment-310076085)). Most CreateFile calls are "read attributes", "generic read" and "execute/traverse" with shared mode "read, write, delete".
But there are also some "excute/traverse" ones with only "read, write", which may cause my "can't delete folder/file" errors on broccoli builds?
Also, there are additional tries for every .js file to also read attributes of .ts, .tsx, .d.ts and extension less files with the same name).

I wasn't yet able to catch concrete handles in a case where i get file access errors on a broccoli build. Because i haven't found a good way to catch that exact moment with a tool like handle.exe (which displays "at the monent you run it" information). A logging procmon heavily slows down the build process and therefore may change timings of actions that could cause problems otherwise.
But i think it's some kind of: broccoli fails to delete a temp folder with not_empty error, because a beforehand delete_all_contents failed to delete some files/folders, which i assume are opened elsewhere and Code comes in mind because of it's CPU spikes at that time and all it's file actions within the tmp folder.

**Comment by bouchepat** [comment] 2017-06-22 16:40
Same as @enkol, 

During build, CPU spikes:
![image](https://user-images.githubusercontent.com/18633763/27445387-6432e0c4-572e-11e7-89ea-7de36c617263.png)

This is after the error is thrown, CPU back to normal but memory has not gone down:
![screenshot 2017-06-22 09 33 29](https://user-images.githubusercontent.com/18633763/27445329-332564ac-572e-11e7-9536-1747b39e1b5d.png)

**Comment by enkol** [comment] 2017-06-23 09:29
Maybe this is somewhat related to #26247. In my case of Ember-CLI, the broccoli build tool uses a lot of symlinks in the `tmp` folder, which can point to files in folders outside `tmp`, mostly files in `node_modules`. Even though, i have both `tmp` and `node_modules` in files.watcherExclude.

**Comment by enkol** [comment] 2017-06-23 09:55
I just got a file located in the `tmp` folder listed in search results, despite the fact that i have `tmp` in files.exclude and search.exclude is documented as "Inherits all glob patterns from the files.exclude setting.".
Doing the same search just again resulted in having the file not listed anymore. So there might be some issue with exclude settings not correctly working sometimes?

**Comment by brucejo75** [comment] 2017-06-23 14:02
Dunno if this might help...

I had modified my default settings for `files.exclude`, `search.exclude` and `files.watcherExclude` at File->Preferences->Settings.

This seemed to work at reducing my build times but later I noticed that they started slowing down again.

At this point I noticed that a `.vscode` directory showed up at the root of my project.  In that directory was `settings.json`.  `settings.json` had different settings than what I had set in my defaults.

Once I set the exclusions in my project level `settings.json` my builds went back to excluding the directories from the VS Code.

**Comment by enkol** [comment] 2017-06-23 14:29
@brucejo75 Thanks for your input! 
I have my exclude settings already in the workspace settings (the ones in the projects .vscode folder). With File->Preferences->Settings you get to see both, your local user settings and the current workspace settings (switchable top right).

**Comment by brucejo75** [comment] 2017-06-23 14:44
D'oh!  Thanks @enkol!  I probably had written out my project setting myself (maybe unwittingly).

**Comment by brucejo75** [comment] 2017-06-23 19:49
I just noticed something.  I often put my computer to sleep.  On my last wake up from sleep, the build was consuming a fair amount of CPU for `code.exe` during the build.  I do not recall having that happening previously.

I closed and restarted VS Code and now the CPU load from `code.exe` has gone back down.

Does VS Code do special initialization on wake up?

**Comment by Dogyunjeong** [comment] 2017-06-27 01:10
I have same issue.
I had first 'npm isnstall error' after meteor run #28013 .  Then I solve it with closing vscode.
Meteor Can't start when vscode is opened. Meteor Can't refresh after modifying startup code as well.

**Comment by s-devaney** [comment] 2017-07-04 19:11
Same issue here. Seems to have started with the latest stable release of VSCode.

**Comment by mjbvz** [comment] 2017-07-07 23:07
I believe this is a duplicate of #28593

Please try out the [latest vscode insiders build](https://code.visualstudio.com/insiders) and let me know if you still see this issue

**Closed by mjbvz** 2017-07-07 23:07 UTC

**Comment by enkol** [comment] 2017-07-12 15:24
For me, it looks like the problemis partially fixed.
I did not get any permission errors on build, with VSCode 1.14.
But the tsserver process still seems to watche my tmp folder, despite having it on all known exclude lists ([see comment 310366877](https://github.com/Microsoft/vscode/issues/29132#issuecomment-310366877)).
This slows down my build process quite a bit.
