### ISSUE TITLE
Not able to stage the files from the version control manager of VS code

### ISSUE THREAD

**Issue by siddhrajcrest** [microsoft/vscode#182156] opened 2023-05-11 06:08 UTC
I am trying to add files to stage from the VSM of VS code, but sometimes it is showing the buttons as disabled in the VSM
[Image](https://prnt.sc/0Snk2VMtoCae)

Don't know if I am doing something wrong or what
but please look at it and give reply so that we as community can solve this issue
Thankyou

**Comment by inkychris** [comment] 2023-05-11 08:23
I'm experiencing the same thing since updating to 1.78.1 from (I think) 1.78.0.

**Comment by gjsjohnmurray** [comment] 2023-05-11 10:22
/duplicate of #181154 which is fixed in upcoming 1.78.2

**Closed** 2023-05-11 10:22 UTC
Labels: *duplicate
