### ISSUE TITLE
Smooth scrolling does not work. Windows 10. 4k screen

### ISSUE THREAD

**Issue by intruder04** [microsoft/vscode#97209] opened 2020-05-08 04:30 UTC
I enabled smooth scrolling in settings but it is still choppy.
Using Windows 10, 4k screen.

**Comment by alexdima** [comment] 2020-05-08 13:42
This is very likely a duplicate of #35711 if the Display Scaling in Windows is configured at anything else than 100% or 200%

**Closed by alexdima** 2020-05-08 13:42 UTC
Labels: needs more info
