### ISSUE TITLE
Expanding collapsed function causes text to be selected

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#29891] opened 2017-06-29 21:35 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:11:49.606Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Write:
```ts
function f() {
    1;
}

function g() {
    2;
}
```
2. Collapse all.
3. Put cursor on `f`.
4. Expect `function g`.
5. `f() {` becomes selected text.

Reproduces without extensions: Yes
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:11:49.606Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Write:
```ts
function f() {
    1;
}

function g() {
    2;
}
```
2. Collapse all.
3. Put cursor on `f`.
4. Uncollapse `function g`.
5. `f() {` becomes selected text.

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-08-10 15:29
duplicate of #31446

**Closed by aeschli** 2017-08-10 15:29 UTC
Labels: editor, insiders
