### ISSUE TITLE
the iframe webpage can't call acquireVsCodeApi 

### ISSUE THREAD

**Issue by specialgirlgotoheaven** [microsoft/vscode#94260] opened 2020-04-02 08:09 UTC
VSCode Version: 1.14.1
OS Version: mac
Steps to Reproduce:

		const url = "http://seto.gicp.net/test.html";
		const webview = vscode.window.createWebviewPanel("danmaku", "Danmaku",
			vscode.ViewColumn.One, { enableScripts: true });
webview.webview.html = `
		<html>
		<head>
			<script>
			const vscode = acquireVsCodeApi();
			function test(){
				vscode.postMessage({
					command: 'token',
					token: '🐛  hahaha'
				});
			}
			</script>
		</head>
		<body>
		<button onclick="test();">haha</button>
		</body>
		</html>`;

This is working for local html.
		webview.webview.html = ``<!DOCTYPE html >
    <html lang="en">
    <head>
    <head>
    <style>
      body, html
        {
          margin: 0; padding: 0; height: 100%; overflow: hidden;
        }
        .vscode-light {
            background: #fff;
        }
    </style>
  </head>
  <body>
      <iframe class="vscode-light" id= "iframetest" width="100%" height="100%" src="http://remote.yx.mail.netease.com:9500/muses/index.html#/resource/list" frameborder="0" >
    </frameset>
  </body>
  </html>`;
This is not working for remote html(the iframe webpage), the function acquireVsCodeApi  is undefined

**Comment by specialgirlgotoheaven** [comment] 2020-04-02 08:11
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [vscode.postMessage bug? (#89694)](https://www.github.com/microsoft/vscode/issues/89694)

it does not solved

**Comment by mjbvz** [comment] 2020-04-02 17:39
Duplicate of #94266

**Closed by mjbvz** 2020-04-02 17:39 UTC
