### ISSUE TITLE
SASS/SCSS autocomplete doesn't work

### ISSUE THREAD

**Issue by vasily-kowalev** [Microsoft/vscode#42885] opened 2018-02-03 13:53 UTC
Hello. I faced such problem: autocomplete in SASS and SCSS files doesn't work, although the official website says the opposite. For SCSS, this is all that begins with the "@" symbol: mixin, function, inlcude, and for SASS autocompletion doesn't work completely.
OS: Windows 7 x64.
VS Code: 1.19.3.

In SASS:
![image](https://user-images.githubusercontent.com/10310491/35767492-391043f0-08fe-11e8-88e5-9aa7dcadada1.png)
In SCSS:
![image](https://user-images.githubusercontent.com/10310491/35767519-85dbb566-08fe-11e8-9117-4bdca314e173.png)
Import works in SCSS:
![image](https://user-images.githubusercontent.com/10310491/35767545-01ded33c-08ff-11e8-8333-1e801d11416a.png)
Variables work in SCSS:
![image](https://user-images.githubusercontent.com/10310491/35767572-a5f31848-08ff-11e8-9a11-cc5751216e00.png)

My attempts to solve this:
- Installed Ruby, installed package "Sass 3.5.5";
- Installed Node.js with npm, installed package "node-sass@4.7.2";
- Installed extensions:
  - Atom Sass Snippet;
  - Richa's SCSS Snippets;
  - Sass;
  - SCSS IntelliSense;
  - scss-scan.

I tried to combine this extensions in different ways - nothing helps.
If disable all this extensions situation worsens:
In SASS:
![image](https://user-images.githubusercontent.com/10310491/35767563-5a37df42-08ff-11e8-8de8-49987de5968c.png)
In SCSS:
![image](https://user-images.githubusercontent.com/10310491/35767568-80ee4fae-08ff-11e8-93d8-9deb2ef17b22.png)

Here there is some extra info, may it helps.
<details>
  <summary>Other extensions</summary>

- AutoFileName;
- Code Spell Cheker;
- jshint;
- One Monokai Theme;
- Python;
- Python for VS Code;
- Regex Previewer;
- Russian - Code Spell Cheker;
- SVG Viewer;
- View in Browser.

</details>
<details>
  <summary>My "User configuration"</summary>

```
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.minimap.enabled": false,
    "editor.scrollBeyondLastLine": false,
    "html.format.indentInnerHtml": true,
    "html.suggest.angular1": false,
    "css.lint.idSelector": "warning",
    "css.lint.important": "warning",
    "css.lint.zeroUnits": "warning",
    "scss.lint.duplicateProperties": "warning",
    "scss.lint.idSelector": "warning",
    "scss.lint.important": "warning",
    "scss.lint.zeroUnits": "warning",
    "editor.wordWrap": "on",
    "workbench.colorTheme": "One Monokai",
    "extensions.ignoreRecommendations": true,
    "files.autoSave": "afterDelay",
    "git.path": "D:\\Programs\\Git\\cmd\\git.exe",
    "cSpell.language": "en,ru,en-GB,en-US",
    "cSpell.enabledLanguageIds": [
        "c",
        "cpp",
        "csharp",
        "go",
        "handlebars",
        "html",
        "javascript",
        "javascriptreact",
        "json",
        "latex",
        "markdown",
        "php",
        "plaintext",
        "python",
        "restructuredtext",
        "scss",
        "text",
        "typescript",
        "typescriptreact",
        "yml"
    ],
    "jshint.options": {
        "devel": true,
        "globalstrict": true,
        "esversion": 6,
        "jquery": true,
        "node": true,
    },
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Python",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "pythonPath": "${config:python.pythonPath}",
                "program": "${file}",
                "cwd": "${workspaceRoot}",
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ]
            },
            {
                "name": "Python: Attach",
                "type": "python",
                "request": "attach",
                "localRoot": "${workspaceRoot}",
                "remoteRoot": "${workspaceRoot}",
                "port": 3000,
                "secret": "my_secret",
                "host": "localhost"
            },
            {
                "name": "Python: Terminal (integrated)",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "pythonPath": "${config:python.pythonPath}",
                "program": "${file}",
                "cwd": "",
                "console": "integratedTerminal",
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit"
                ]
            },
            {
                "name": "Python: Terminal (external)",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "pythonPath": "${config:python.pythonPath}",
                "program": "${file}",
                "cwd": "",
                "console": "externalTerminal",
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit"
                ]
            },
            {
                "name": "Python: Django",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "pythonPath": "${config:python.pythonPath}",
                "program": "${workspaceRoot}/manage.py",
                "cwd": "${workspaceRoot}",
                "args": [
                    "runserver",
                    "--noreload",
                    "--nothreading"
                ],
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput",
                    "DjangoDebugging"
                ]
            },
            {
                "name": "Python: Flask (0.11.x or later)",
                "type": "python",
                "request": "launch",
                "stopOnEntry": false,
                "pythonPath": "${config:python.pythonPath}",
                "program": "fully qualified path fo 'flask' executable. Generally located along with python interpreter",
                "cwd": "${workspaceRoot}",
                "env": {
                    "FLASK_APP": "${workspaceRoot}/quickstart/app.py"
                },
                "args": [
                    "run",
                    "--no-debugger",
                    "--no-reload"
                ],
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ]
            },
            {
                "name": "Python: Flask (0.10.x or earlier)",
                "type": "python",
                "request": "launch",
                "stopOnEntry": false,
                "pythonPath": "${config:python.pythonPath}",
                "program": "${workspaceRoot}/run.py",
                "cwd": "${workspaceRoot}",
                "args": [],
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ]
            },
            {
                "name": "Python: PySpark",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "osx": {
                    "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
                },
                "windows": {
                    "pythonPath": "${env:SPARK_HOME}/bin/spark-submit.cmd"
                },
                "linux": {
                    "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
                },
                "program": "${file}",
                "cwd": "${workspaceRoot}",
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ]
            },
            {
                "name": "Python: Module",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "pythonPath": "${config:python.pythonPath}",
                "module": "module.name",
                "cwd": "${workspaceRoot}",
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ]
            },
            {
                "name": "Python: Pyramid",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "pythonPath": "${config:python.pythonPath}",
                "cwd": "${workspaceRoot}",
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "args": [
                    "${workspaceRoot}/development.ini"
                ],
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput",
                    "Pyramid"
                ]
            },
            {
                "name": "Python: Watson",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "pythonPath": "${config:python.pythonPath}",
                "program": "${workspaceRoot}/console.py",
                "cwd": "${workspaceRoot}",
                "args": [
                    "dev",
                    "runserver",
                    "--noreload=True"
                ],
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ]
            },
            {
                "name": "Server",
                "type": "python",
                "request": "launch",
                "stopOnEntry": false,
                "pythonPath": "${config:python.pythonPath}",
                "program": "${workspaceRoot}/runserver.py",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ]
            }
        ]
    },
}
```

</details>

**Comment by aeschli** [comment] 2018-02-05 13:49
duplicate of https://github.com/Microsoft/vscode/issues/41929

**Closed by aeschli** 2018-02-05 13:49 UTC
