### ISSUE TITLE
Encode guess sometimes incorrectly

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#52132] opened 2018-06-17 18:09 UTC
Issue Type: <b>Bug</b>

Encode guess is very convenient in most time.
But sometime it doesn't work well.
[test.txt](https://github.com/Microsoft/vscode/files/2109229/test.txt)
The file above, VS Code thinks it's encoding is Windows 1252
![image](https://user-images.githubusercontent.com/20079289/41510692-1b611986-7237-11e8-871f-490f5544dc11.png)
And the text displayed abnormally.
![image](https://user-images.githubusercontent.com/20079289/41510754-e7cabb30-7237-11e8-9dd8-82e0fff991fc.png)
Actually, it is encoded in GBK/GB 18030 (GB 18030 is the substitute of GBK).
![image](https://user-images.githubusercontent.com/20079289/41510757-f5206014-7237-11e8-8edd-99efd8eab39b.png)
So, VS Code doesn't detect the right encoding.
Here's a similar issue.
https://github.com/Microsoft/vscode/issues/24195
 
VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.53GB (2.63GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\Max\Desktop\新建文本文档.txt|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
minibex-lang|ama|0.0.4
vscode-language-pack-zh-hans|MS-|1.24.3

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-09-11 16:26
Duplicate of https://github.com/Microsoft/vscode/issues/33720

**Closed by bpasero** 2018-09-11 16:26 UTC
Labels: file-encoding, upstream
