### ISSUE TITLE
Unexpected "The 'Docker' extension is recommended for this file type."

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#102634] opened 2020-07-15 20:01 UTC
Issue Type: <b>Bug</b>

This is coming up at odd times during debugging.  It doesn't say what file type it's talking about, but I currently have a .ts file open while debugging.  I don't have any docker-related files in this project.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/6913354/87590091-1a32f880-c69b-11ea-9b6a-28424b95a7fe.png">

VS Code version: Code - Insiders 1.48.0-insider (3bc3f95dbc0434fd88bc3ae99b8aca8b281fc622, 2020-07-13T21:48:58.997Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
todo-tree|Gru|0.0.178
vscode-dotnet-runtime|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by 9at8** [comment] 2020-07-15 20:14
duplicate of #102553

**Closed by 9at8** 2020-07-15 20:14 UTC
