### ISSUE TITLE
Changing language mode in diff view does not persist the mode for the file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3821] opened 2016-03-08 09:23 UTC
1. Create two new files test1, test2
2. Compare them and change the mode of those files in the diff view, for example to `javascript`
3. The mode nicely changes for both files in the diff view
4. However, I would expect that when I open those files in a regular view the `javascript` mode is persisted. It is not, only one of those files has `javascript`, the other still has `plain text`

Related to #2932

**Comment by bpasero** [comment] 2016-03-08 11:19
@isidorn I believe one of the two files was not in working files? if a file is closing we do not persist the mode and you have to reset it. I cannot reproduce when both files are in working files.

**Closed by bpasero** 2016-03-08 11:19 UTC
Labels: bug
