### ISSUE TITLE
VSS has color issues when Windows HD Color is turned on

### ISSUE THREAD

**Issue by tinne** [microsoft/vscode#105090] opened 2020-08-20 15:04 UTC
Issue Type: <b>Bug</b>

Start Windows system settings using a 10-bit HDR display (here: Acer XV273K), select Display, select (on multi display setups) the display using HDR, turn on “Playback HDR Games and App”. Run Visual SourceSafe and enjoy the colors.

Interestingly, the screen shot attached has the problem at hand removed - appearantly the image resolution conversion of the screen shot tool converts it to 8-bit color and removes the problem:

![screen shot](https://user-images.githubusercontent.com/1666549/90788900-8d690380-e306-11ea-9410-d92c6baa47dc.png)

Thus, I add a photography of the screen (and the integrated bug tool, for what its's worth) to illustrate the issue:

![photography](https://user-images.githubusercontent.com/1666549/90788892-8a6e1300-e306-11ea-9461-cb3fd07bd760.png)

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (18.89GB free)|
|Process Argv|*file name deleted*|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-yaml-preamble|bie|0.0.4
githistory|don|0.6.9
gitlens|eam|10.2.2
docker-explorer|for|0.1.7
gc-excelviewer|Gra|3.0.40
docker-linter|hen|0.5.0
reg|ion|1.0.1
eml|lei|0.4.0
vscode-docker|ms-|1.5.0
remote-wsl|ms-|0.44.4
powershell|ms-|2020.6.0
oracle-plsql|myc|1.0.3
biosyntax|rea|0.0.9
java|red|0.65.0
vscode-hexdump|sle|1.7.2
vscode-docker-registry-explorer|Tqr|0.1.3
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.12.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.1
vscode-maven|vsc|0.24.1
markdown-pdf|yza|1.4.4

</details>

**Comment by gjsjohnmurray** [comment] 2020-08-20 15:54
/duplicate of #88491

Please try with the [Insiders build](https://code.visualstudio.com/insiders), which uses Electron 9. Insiders can coexist with Stable.

**Closed** 2020-08-20 15:54 UTC
Labels: *duplicate
