### ISSUE TITLE
Editor Typescript formatting on new line error

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/vscode#25253] opened 2017-04-24 22:00 UTC
- VSCode Version:
```
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:01:14.464Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open new tab
2. Set syntax to Typescript
3. Add this
```ts
class Smth {

  constructor() {/**/}
}
```
4. Put cursor at the end of `constructor` line and press enter
5. See that line with `constructor` lost it's indentation and cursor has wrong position on new line (there is should be 2 spaces before cursor)
![image](https://cloud.githubusercontent.com/assets/1944061/25360555/50481d5e-2952-11e7-939f-5aee463144c4.png)

Cant reproduce with any other indentation than 2 spaces or without comment block inside constructor brackets (have `{ /* */ }` in real app to prevent tslint empty block warning).

**Comment by mjbvz** [comment] 2017-04-24 22:16
I'm unable to reproduce this. What extensions do you have installed? Can you please try running code with the `--disable-extensions` command line flag to see if one of those is causing this

**Comment by artaommahe** [comment] 2017-04-24 22:39
@mjbvz same with `--disable-extensions`, installed
![selection_501](https://cloud.githubusercontent.com/assets/1944061/25361620/ff733f48-2957-11e7-876f-76748e8f8082.png)

**Comment by mjbvz** [comment] 2017-04-24 22:43
Ok, I've confirmed this issue. Looks like our indentation rules for JS/TS are confused by this case. 

As a workaround, you should be able to run `Format Document` to restore the proper indentation. Setting `	"editor.formatOnType": true` may also help by formatting automatically

**Comment by axefrog** [comment] 2017-06-29 20:34
Possibly related: #29886

**Comment by rebornix** [comment] 2017-11-21 22:40
Already fixed by @mjbvz .

**Closed by rebornix** 2017-11-21 22:40 UTC
Labels: bug, editor-autoindent, javascript, typescript
