### ISSUE TITLE
 Expand selection, a level to not include quotes

### ISSUE THREAD

**Issue by Noitidart** [Microsoft/vscode#27984] opened 2017-06-03 22:44 UTC
- VSCode Version: 1.12.2 (1.12.2)
- OS Version: macOS 10.12.5 

Steps to Reproduce:

1. Type a string without quotes: `"this is a string"`
2. Place cursor in between `i` and `s` of the word `is`
3. Press Ctrl + Cmd + Shift + Right - it will expand to include the quotes

Expected results:

If we expand the selection when there are quotes around it, the selection gets expanded to include the quotes. Can we please get a level before the quotes. So if I my cursor is in the middle of a string surrounded by quotes, if I expand once it will just get what is within the quotes, expanding a second time then includes the quotes. This is how it worked on my other editors before I moved to VSCode.

**Comment by jrieken** [comment] 2017-06-06 07:52
dupe of #4795

**Closed by jrieken** 2017-06-06 07:52 UTC
Labels: feature-request
