### ISSUE TITLE
Broken non-alphabetical shortcuts with non-US keyboards

### ISSUE THREAD

**Issue by nighto** [Microsoft/vscode#16522] opened 2016-12-05 17:31 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 7

Instead of accepting non-alphabetical keys positions for keyboard shortcuts bindings, application only accepts original keys positions on US keyboard layout.

Steps to Reproduce:

1. Consider brazilian portuguese ABNT 2 keyboard layout, more specifically the position of <kbd>[</kbd> and <kbd>]</kbd> keys:
![brazilian portuguese ABNT 2 keyboard layout](http://s2.glbimg.com/hlQMZ_E87B3DB_96rVuO_pY2Yy8=/695x0/s.glbimg.com/po/tt2/f/original/2016/06/21/900px-kb_portuguese_brazilsvg_.png)
2. Trying to use code folding shortcut <kbd>Ctrl+[</kbd> and <kbd>Ctrl+]</kbd> doesn't work, but rather <kbd>Ctrl+´</kbd> and <kbd>Ctrl+[</kbd>, which are the original keys position on US layout.

**Comment by alexandrudima** [comment] 2016-12-06 10:18
@nighto What shortcuts does vscode render in the `F1` list for code folding for your keyboard layout? Is pressing those keys not functioning?

i.e.:

![image](https://cloud.githubusercontent.com/assets/5047891/20921664/775ab0ac-bba5-11e6-8cd1-c5dece865ec2.png)

I suggest a quick read of our documentation: https://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts

Here is also a document describing troubleshooting in this area: https://github.com/Microsoft/vscode/wiki/Troubleshooting-Keybindings

**Comment by nighto** [comment] 2016-12-06 18:00
It shows <kbd>`</kbd> and <kbd>[</kbd>, indeed.

![fold and unfold shortcuts in pt-br](http://i.imgur.com/YrcCyLt.png)

In my opinion it should be with <kbd>[</kbd> and <kbd>]</kbd> regardless of the keyboard layout, for better understanding of online documentation.

**Comment by alexandrudima** [comment] 2016-12-07 16:24
In this case, I believe you'd want VS Code to ship with different default keybindings, based on keyboard layout. Duplicate of #1240

**Closed by alexandrudima** 2016-12-07 16:24 UTC
Labels: needs more info

**Comment by nighto** [comment] 2016-12-07 17:51
Awesome, thanks for pointing to the correct issue.
