### ISSUE TITLE
Images Aspect Ratio wrong when zooming

### ISSUE THREAD

**Issue by SoleSensei** [Microsoft/vscode#62032] opened 2018-10-29 11:13 UTC
Issue Type: <b>Bug</b>

Hi,

when zooming `.png` image in vscode tab previewer - aspect ratio breaks.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
path-autocomplete|ion|1.12.0
vscode-graphviz|joa|0.0.1
python|ms-|2018.9.1
cpptools|ms-|0.19.0
vscode-icons|rob|7.27.0
pdf|tom|0.3.0

</details>

**Comment by SoleSensei** [comment] 2018-10-29 11:15
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [image zoom didn't work (#61050)](https://www.github.com/Microsoft/vscode/issues/61050)
Yes, the same problem. But that issue closed. And marked as resolved.

**Comment by mjbvz** [comment] 2018-10-29 19:00
Duplicate of #61050 

Try the insiders builds

**Closed by mjbvz** 2018-10-29 19:00 UTC
