### ISSUE TITLE
Markdown preview/notebooks not rendering LaTeX in lists. 

### ISSUE THREAD

**Issue by hsong7273** [microsoft/vscode#141105] opened 2022-01-20 21:20 UTC
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.63.2
- OS Version: Windows 10.0.19043 Build 19043

LaTeX expressions in markdown documents or markdown notebook cells do not get rendered when they are in a html list.
Ex.
**Does not render**
```md
<ul> 
<li> $f(x)=\int 2x \frac{1}{4}$ </li>
</ul>
```

**Renders**

```
$f(x)=\int 2x \frac{1}{4}$
```
Both cases work in jupyter notebooks. This may end up being a feature request rather than an issue.

Steps to Reproduce:
1.  Write LaTeX expression in a list in a markdown document or notebook cell
2. Preview markdown or run markdown cell

**Comment by mjbvz** [comment] 2022-01-21 00:10
Duplicate of #130149 (which was closed because it did not received any additional feedback)

Math works fine inside of markdown lists. How Jupyter lab and other tools handle math is not very well specified to my knowledge. Our current handling is consistent with most markdown language extensions, which don't touch the contents of raw html tags

**Closed by mjbvz** 2022-01-21 00:10 UTC
