### ISSUE TITLE
[html] trigger completion for attribute values

### ISSUE THREAD

**Issue by Airkro** [Microsoft/vscode#40067] opened 2017-12-12 04:37 UTC
`Emmet` is cool, but still can't do everything. there is too many html attributes and possible values.

`Atom` can use `Emmet` and `Intellisense` in the same time. But for now, none of VSCode extension can do that.

![-1](https://user-images.githubusercontent.com/12206891/33867034-eb59a946-df34-11e7-9a45-e6f8d17851ec.jpg)

**Comment by ramya-rao-a** [comment] 2017-12-12 07:44
I see the same coming from the in built html extension in VS Code

<img width="643" alt="screen shot 2017-12-11 at 11 43 15 pm" src="https://user-images.githubusercontent.com/16890566/33872783-22585d6a-decd-11e7-9fba-e427036fb2d7.png">

**Comment by ramya-rao-a** [comment] 2017-12-12 07:45
If you see any other examples that the built in html extension doesn't achieve, feel free to re-open this issue.

**Comment by Airkro** [comment] 2017-12-12 08:28
@ramya-rao-a

My fault, Atom seen not a good example. I mean: 
When I use buildin Intellisense（or use Emmet），Intellisense not show in second time.

![1](https://user-images.githubusercontent.com/12206891/33874194-db2021d0-df58-11e7-8705-9b33a3b1de92.gif)

That mean:
If I use vscode buildin Intellisense to input a html attribute name, I can't use it again to input html attribute value.

**Comment by Airkro** [comment] 2017-12-12 08:38
![2](https://user-images.githubusercontent.com/12206891/33874755-da61be50-df5a-11e7-9f93-b9682d704de4.gif)

**Comment by ramya-rao-a** [comment] 2017-12-12 17:56
Ok, then this is about triggering intellisense as soon one of the completion items has been selected, instead of waiting for a type event or one of the trigger characters?

**Comment by Airkro** [comment] 2017-12-13 01:10
Right, creating statement `method="get"` in HTML.

In vscode, I have to type `method`  `=` `enter`.
But there too many editor can do it with `met` `enter`

**Comment by jrieken** [comment] 2017-12-13 08:40
dupe of https://github.com/Microsoft/vscode/issues/34565

**Comment by usernamehw** [comment] 2017-12-13 09:11
@jrieken  How is this a duplicate of closed issue if it is not implemented.
In 1.19: 
✅ CSS - after completion of property trigger successfully invokes
❌HTML - after completion of property it doesn't automatically show autocomplete

**Comment by jrieken** [comment] 2017-12-13 09:14
You are right... It shouldn't have come to me because the infrastructure is there but it needs to be adopted by extensions

**Closed** 2017-12-13 15:40 UTC
Labels: feature-request, html
