### ISSUE TITLE
[Safari] ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#135833] opened 2021-10-26 07:39 UTC
* use notebooks (GHINB) with Safari and vscode.dev
* notice that the console shows messages like these `ResizeObserver loop completed with undelivered notifications.`
* this the explainer for what it means: https://webkit.org/blog/9997/resizeobserver-in-webkit/

**Comment by bpasero** [comment] 2022-04-06 17:34
Spams integration tests too which are not using Safari:

```
[39068:0406/193033.440693:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://0u27uoto7fg3gdq3mrs61725gra26d5q980dl5hkb3esod69e2h3/index.html?id=5156f4ab-f232-46b6-97d1-be3341b9762d&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
[39068:0406/193033.458009:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://0u27uoto7fg3gdq3mrs61725gra26d5q980dl5hkb3esod69e2h3/index.html?id=5156f4ab-f232-46b6-97d1-be3341b9762d&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
[39068:0406/193033.624411:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://01th8mi84h7nmkh2h1p8mqhjvi0rrbdra11piidcl5utdpkpaes7/index.html?id=eeedb452-71c3-49a9-8f94-1305114f77e1&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
[39068:0406/193033.841324:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://19bf8622nu8lgh94g9feiai8fgqk4ln2rsf0ng608jf5mn7i8rt3/index.html?id=df9131a3-5901-469f-a526-580481e57bea&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
[39068:0406/193033.857652:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://19bf8622nu8lgh94g9feiai8fgqk4ln2rsf0ng608jf5mn7i8rt3/index.html?id=df9131a3-5901-469f-a526-580481e57bea&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
[39068:0406/193034.091039:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://13rtg7s716eq859t9lrk2sd3r81qinpce5sk96sa4eiu5ous7hdq/index.html?id=ff2507e0-81bb-4d35-9389-36daf4842d98&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
[39068:0406/193034.376229:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://1771td3s6oo4h49ep0fk563d9a8pur4clk1aho5ts0od1sug2hqo/index.html?id=477efadc-5694-4cfa-9f59-831e031d91b6&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
[39068:0406/193035.505759:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://1b46lj21rqm991p9a2dmd7ra0ehvmsd3sqkcb0mjn1o153stee11/index.html?id=dd349363-f4e0-47a7-8074-f60f51f23a61&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
```

**Comment by rebornix** [comment] 2022-12-08 20:06
/duplicate of https://github.com/microsoft/vscode/issues/154358 and should already be fixed.

**Closed by rebornix** 2022-12-08 20:06 UTC
Labels: debt, safari, notebook-layout
