### ISSUE TITLE
Opening git changes of large package-lock.json causes hang up for several minutes

### ISSUE THREAD

**Issue by ahmadalibaloch** [microsoft/vscode#138142] opened 2021-11-30 11:24 UTC
Issue Type: <b>Bug</b>

Open a package-lock.json or any other large file (I have 80,000+ lines) in a git enabled project and after that laptop/computer fan will start on high speed and git related tasks like undo commit, commit or track untrack changes will not work and feels like it has hung up.
All the menus in vs code also become on responsive.

PS: also reported earlier. https://github.com/microsoft/vscode/issues/77276

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.11.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz (12 x 3853)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|30.97GB (14.40GB free)|
|Process Argv|--unity-launch --crash-reporter-id 44af355b-6de5-47d4-885a-7704cae9634c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
foam-vscode|foa|0.16.0
copilot|Git|1.7.4016
remotehub|Git|0.18.0
google-home-ide|Goo|0.0.1
gc-excelviewer|Gra|3.0.44
beautify|Hoo|1.5.0
rest-client|hum|0.24.6
vscode-edit-csv|jan|0.6.4
vscode-markdown-notes|kor|0.0.24
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-css-peek|pra|4.2.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
vscode-scss-formatter|sib|2.3.2
markdown-links|tch|0.8.0
sapling|tea|1.2.0
vscode-status-bar-format-toggle|tom|3.0.0
vscode-icons|vsc|11.7.0
vscode-wakatime|Wak|17.1.0
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890
vscexrecpromptt2:30404948
vscop804cf:30404767
vscop341:30404997

```

</details>

**Comment by qbikez** [comment] 2021-12-07 08:33
There's also an issue for generic git speed: #134921

**Comment by ahmadalibaloch** [comment] 2021-12-07 11:11
Edit / More Info: It actually needs me to restart the VS Code to solve the problem after restart and before restart I need to close the package-lock.json. I am using Insider build of Vs Code and the problem seems to be fixed: https://github.com/microsoft/vscode/issues/134921

**Comment by lszomoru** [comment] 2022-01-04 11:59
@ahmadalibaloch, sorry for not getting back to you on this until now.
Are you saying that the performance issues are addressed in the latest Insiders release?

**Comment by ahmadalibaloch** [comment] 2022-01-04 12:24
@lszomoru  Yes I face no issues in Insiders Releases. I am using Insider version due to this problem for 2 months now. The stable release still has this issue, I checked about 2 weeks ago.

**Comment by lszomoru** [comment] 2022-01-04 12:27
@ahmadalibaloch, that is interesting. Are you having the same extensions installed both in Stable and Insiders? 
Are you able to reproduce the problem is you start the latest version of Stable with `code --disable-extensions`?

**Comment by ahmadalibaloch** [comment] 2022-01-04 12:50
@lszomoru Just checked with `code --disable-extensions` on stable release and got no problem dealing with package-lock.json and other files in a comparatively large project with 100+ files. The problem could be with GitLens I think. I have that extension related to git.
![image](https://user-images.githubusercontent.com/1916642/148061585-62e79896-b5ed-456e-8f84-d61476888646.png)

**Comment by lszomoru** [comment] 2022-01-04 14:27
This does hint towards a culprit extension. One thing to try would be to start VS Code stable normally and just disable the GitLens extension and see if that helps. If that does not help, you can use [the extension bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to track down the offending extension.

**Comment by ahmadalibaloch** [comment] 2022-01-04 23:34
With the above release I am not getting any problem even with Gitlens on. Everything is working fine for me.

**Comment by lszomoru** [comment] 2022-01-05 10:34
Thanks for the update. Glad to hear that everything is working as expected.

**Closed by lszomoru** 2022-01-05 10:34 UTC
Labels: git, perf
