### ISSUE TITLE
Watch tasks not reconnecting/restarting in WSL

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#156363] opened 2022-07-26 20:50 UTC
Testing #155349

I used the compile task in https://github.com/Microsoft/vscode-python, and set
```json
{
    "task.experimental.reconnection": true
}
```
in remote settings. The compile task simply disappeared on Windows reload.

**Comment by meganrogge** [comment] 2022-08-02 19:12
believe this is a duplicate of #156899, so will have been fixed

**Closed by meganrogge** 2022-08-02 19:12 UTC
Labels: tasks, confirmation-pending

**Comment by roblourens** [comment] 2022-08-24 00:19
If it's a duplicate, you can tag it as such so it doesn't get verified twice
