### ISSUE TITLE
VSCode deletes all my changes!

### ISSUE THREAD

**Issue by unional** [microsoft/vscode#168003] opened 2022-12-04 00:41 UTC
- VS Code Version: 1.73.1
- OS Version: Windows 11

Steps to Reproduce:

Obviously this is not easily reproducible. But I want to mention it so that people are aware that this can happen.

I'm making changes and there are many new files created.
The issue happens when I was renaming one of the folders (not the one with changes) and it stuck as usual.
In Windows, this happens a lot. It could be some VSCode or extension process holds file locks so the rename got stuck.
Most of the time, I have to completely quite VSCode, and do the rename either through terminal or through file explorer.
This time, after I renamed the folder and open VSCode again,
The files I was working on are all gone.
Git only detects changes at the root level, and the files that I have deleted:

![image](https://user-images.githubusercontent.com/3254987/205468213-8bab9ca1-7791-4a79-82d7-6088d5d992d7.png)

The files under `packages/jest` is where the new files should have been. But right now it is a completely empty folder.

The rename folder I was trying to do is renaming `scenarios/simple-repo` to `scenarios/ts-esm`.

Now I have to redo the work I was doing in the last few hours.....

**Comment by lramos15** [comment] 2022-12-05 14:34
Are the steps closing VS Code, renaming from the terminal, and then re-opening VS Code. I haven't seen this myself personally so I'm trying to reproduce it on my end.

**Comment by unional** [comment] 2022-12-05 17:58
I don't think you can easily repro it.

> Are the steps closing VS Code, renaming from the terminal, and then re-opening VS Code

That's the alternative workaround, not the repro step.
What happen was working inside VSCode, trying to rename file/folder, copy and paste, etc. and eventually it got frozen/stuck trying to do the rename.

I have also experienced that when copying and pasting the file/folder, the UI does not update until I click on the refresh button:

![image](https://user-images.githubusercontent.com/3254987/205708303-6b24e513-a0d4-43fa-b397-ccd54f895ef5.png)

This happens a few times with the latest VSCode. I didn't experience that in older release

**Comment by lramos15** [comment] 2022-12-05 19:43
Thanks for the info. I'm not able to reproduce this, so without suitable reproduction steps I won't be able to fix this. I'll close this for now, but thank you for recording it so I remember that this is a possible issue and can investigate if we continue to get reports.

**Closed by lramos15** 2022-12-05 19:43 UTC
