### ISSUE TITLE
[Re-add feature] VS Code search file directory without collapsing it

### ISSUE THREAD

**Issue by Luehang** [microsoft/vscode#230666] opened 2024-10-07 00:38 UTC
VS Code is my favorite editor but lately there was been updates that are messing it up.  I never really write these issues but here it is. I want the file directory search to have the old settings where I can search the directory without collapsing as that is a lot more helpful.  I don't know why it was removed.  People complaining?  Or something no one uses based on data?  Lately, these new releases are messing with some of these features that I use and many use. It's removing things that are good.  Like in the past, the short keys to enable file directory search that I had look up.  Improving user experience or just making it harder to use?

**Comment by gjsjohnmurray** [comment] 2024-10-07 02:39
If I understand you correctly you are asking for the highlight-matches mode of Explorer Find to be reinstated. If so, this sounds like a duplicate of https://github.com/microsoft/vscode/issues/230586#issuecomment-2395208192

Pinging @benibenj and @andreamah

**Comment by Luehang** [comment] 2024-10-07 02:58
Yeah.  I agree with that issue thread.  The highlight match without collapsing the folders is a lot more helpful and I use it a lot.  The new release doesn't have that option and the new feature is a hit and miss on finding the folders or files I want.  If you can add that feature again it would help a lot.  Thanks.

**Comment by benibenj** [comment] 2024-10-23 09:38
Closing as duplicate.
FYI we are planning on improving find in the explorer in November

**Closed by benibenj** 2024-10-23 09:38 UTC
