### ISSUE TITLE
Opening VSCode or Saving File with it causes Disk memory hog

### ISSUE THREAD

**Issue by iamRusty** [Microsoft/vscode#6407] opened 2016-05-17 01:41 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10 Home Premium

Steps to Reproduce:

1. Open VSCode or open a file with VSCode
2. Save file

When opening VSCode, it causes the Service Host: Local System (Network Restricted) process to use most of the Disk until it reaches 100%. After some time, svchost's disk usage would go normal. When you save a file, or save an edit of a file, svchost will eat most Disk, again.

![capture](https://cloud.githubusercontent.com/assets/7788765/15308776/5345d8d6-1c13-11e6-92ec-18f1e1d9f7d4.PNG)

**Comment by bpasero** [comment] 2016-05-17 08:06
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by iamRusty** [comment] 2016-05-17 08:18
I tried opening code without extensions but the issue still persists.

**Comment by bpasero** [comment] 2016-05-17 08:53
Does this reproduce on all folders opened? Does it reproduce when you just open a file without opening a folder?

**Comment by bpasero** [comment] 2016-05-22 09:01
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-05-22 09:01 UTC
Labels: needs more info
