### ISSUE TITLE
cannot collapse `switch () case "":` statements in JavaScript

### ISSUE THREAD

**Issue by raydlevel5** [Microsoft/vscode#51697] opened 2018-06-12 13:44 UTC
Issue Type: <b>Bug</b>
After the most recent update, I cannot collapse `switch () case "":` statements.

More specifically, `switch` can be collapsed, but `case "":` cannot.  This worked prior to an update I just applied.  This has happenened once before after an update.  

Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.49GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.0
mssql|ms-|1.3.1

</details>

**Comment by mjbvz** [comment] 2018-06-12 16:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/23380

See [Syntax aware folding enabled by default for JS/TS](https://code.visualstudio.com/updates/v1_24#_syntax-aware-folding-enabled-by-default-for-jsts) part of release notes for details and info on how to revert to old behavior

**Closed by mjbvz** 2018-06-12 16:48 UTC
Labels: new release

**Comment by vavachi** [comment] 2018-07-11 09:01
"typescript.experimental.syntaxFolding": false not found in  V1.25
