### ISSUE TITLE
'Move editor in right group' command is confusing

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50664] opened 2018-05-29 12:06 UTC
Testing #50458

- pick the 'three rows' layout
- open some editors in each group
- Use the 'Move editor in right group' command

There's no right group here, so maybe better: 'Move editor in next group'

**Comment by aeschli** [comment] 2018-05-29 12:17
Hm, there's already a command 'Move editor in next group'...

**Comment by bpasero** [comment] 2018-05-29 12:42
@aeschli do you mean this command:

![image](https://user-images.githubusercontent.com/900690/40659398-7568f4f0-634e-11e8-90db-804e8a3c535d.png)

?

The idea is to move the currently active editor into the editor group to the right if there is one.

**Comment by aeschli** [comment] 2018-05-30 07:29
@bpasero Yes, that command. 
When using that command in 'three rows' layout will move the editor one group below.
So I guess it should do nothing if there isn't a right group, or maybe better create a group on the right.

**Comment by bpasero** [comment] 2018-05-30 07:47
@aeschli yes it should not do anything if there is no group to the right. This relies on the grid widget giving me the right neighbour groups which is currently broken. We have bugs to track that, so I will close this as duplicate of https://github.com/Microsoft/vscode/issues/50679 which shares the same underlying issue.

**Closed by bpasero** 2018-05-30 07:47 UTC
Labels: workbench-grid
