### ISSUE TITLE
Notebook toolbar covers the terminal panel

### ISSUE THREAD

**Issue by chardon55** [microsoft/vscode#192284] opened 2023-09-06 00:29 UTC
Type: <b>Bug</b>

1. Use a VS Code with Jupyter Notebook rendering support
2. Open a notebook
3. Open built-in terminal panel
4. Maximize the panel

Extension version: 1.0.17
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 6.4.12-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 3343)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|13.51GB (7.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by rebornix** [comment] 2023-10-06 22:31
/duplicate of https://github.com/microsoft/vscode/issues/179671

**Closed by rebornix** 2023-10-06 22:31 UTC
Labels: bug, notebook-layout
