### ISSUE TITLE
Open Editors: middle mouse closes and opens editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79786] opened 2019-08-26 06:20 UTC
Steps to Reproduce:

1. open some editors in multiple groups
2. middle-click into the non-active group editor in the open editors view

=> 🐛 the editor closes but also opens the next editor in the list

I would expect the editor to close and not open.

@isidorn pushed a workaround, please check: https://github.com/microsoft/vscode/commit/b032304497183709c76861b19bf405b17afc992a

**Comment by isidorn** [comment] 2019-08-26 07:50
@bpasero thanks, I will check it in the afternoon (since currenly I do not have a mouse).

**Comment by isidorn** [comment] 2019-08-26 13:58
I can not reproduce the issue with Insiders from 3 days ago which does not contain your fix
However your fix looks good, and looking at the code and analysing the behavior on my machine I am just lucky that `onDidOpen` fires first, and only latter the onMiddleClick fires. So for me first I open it which is a no-op, and then the middleClick comes which closes it resulting in a correct behavior at the end.
However your fix is good, since it covers this case when the events come in the opposite order.
Thus closing

![lala](https://user-images.githubusercontent.com/1926584/63695610-5c501300-c819-11e9-9b2f-b3c5a9723697.gif)

**Closed by isidorn** 2019-08-26 13:58 UTC
Labels: bug
