### ISSUE TITLE
Copy and paste of cells causes "non-unique cell id" error.

### ISSUE THREAD

**Issue by liganega** [microsoft/vscode#167951] opened 2022-12-02 16:14 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

As the title suggests, when I copy and paste a cell, the generated cell has the same id as the original one. 

This only happens with jupyter extension for VS Code while the original jupyter notebook server (installed by Anaconda) automatically changes the id of a copied cell. 

So it's a reasonable conclusion that the problem should definitely have something to do with the jupyter extension, not with the original jupyter notebook server.

### VS Code Version

1.73.1

### Jupyter Extension Version

v2022.9.1303220346

### Anaconda Version (if applicable)

Anaconda3-2022.05

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment] 2022-12-02 17:44
Vs code doesn't create Cell IDs for cells that it creates, but the jupyter notebook web UI will, and it looks like that gets duplicated because we just copy whatever is in the meta-data.

**Comment by amunger** [comment] 2022-12-02 17:45
@liganega - I assume that you are seeing this error in the jupyter UI? (not within vs code)

**Comment by liganega** [comment] 2022-12-02 18:52
First, VS Code **DOES** create cell IDs. 

Although the error was found by another tool (jupyter book), the creation of Cell IDs was checked by Vim with the source code( with metadata) after copy-and-paste (C-V combination) in VS Code. 

The same thing was checked with the original jupyter notebook, but, as I said before, new IDs are created, also checked by Vim with the source code.

As @amunger said, the C-V combination duplicates everything in the metadata, but this happens only in VS Code, not with jupyter notebook.

**Comment by liganega** [comment] 2022-12-02 19:00
One more thing. 

About duplicated IDs, VS Code does not complain, but jupyter notebook does.

**Comment by rebornix** [comment] 2022-12-14 22:35
/duplicate of https://github.com/microsoft/vscode/issues/103881, we should not copy metadata it seems.

**Closed by rebornix** 2022-12-14 22:35 UTC
Labels: bug, notebook-ipynb, notebook-clipboard
