### ISSUE TITLE
[scss] Option to remove scss functions from property autocomplete

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#12986] opened 2016-09-29 09:09 UTC
- VSCode Version: 1.51
- OS Version: Sierra

![image](https://cloud.githubusercontent.com/assets/2827047/18947829/eae40254-8634-11e6-813d-fb57ea8d7221.png)

This type of behaviour is highly unpractical, since in 99.9% of cases I want to select a css property. Either group scss functions after css properties or add an option to turn them off.

**Comment by druellan** [comment] 2016-10-21 14:46
I think part of the problem is related to the lack of context based on some properties.
For example, `color` looks crowded, but options are relevant:
![2016-10-21_11h36_15](https://cloud.githubusercontent.com/assets/6965667/19602449/ae4b39d8-9783-11e6-93af-d62649987bdc.png)

But on `margin-top` seems that many options are invalid for that particular property:
![2016-10-21_11h37_14](https://cloud.githubusercontent.com/assets/6965667/19602466/ba31c442-9783-11e6-8c6b-13799e7d524b.png)

@mrmlnc Hi! Are you working on the current scss implementation? Perhaps you can quick check this?

**Comment by mrmlnc** [comment] 2016-10-21 14:57
Hello, @druellan,

Sorry, but I don't see what you mean. You talking about SCSS IntelliSense extension?

**Comment by druellan** [comment] 2016-10-21 15:47
Hi @mrmlnc No, the current built-in implementation is doing this without any extension. Sorry if this is not your area.

**Comment by mrmlnc** [comment] 2016-10-21 15:53
@druellan, I am not an employee of Microsoft or member VS Code team 😄 I just love this project and trying to help him.

**Comment by druellan** [comment] 2016-10-21 15:57
Oh, sorry about the ping then (BTW, I'll take note for that SCSS IntelliSense extension!).

**Comment by mrmlnc** [comment] 2016-10-21 16:12
`SCSS IntelliSense` is an alternative [vscode-less](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-less) to SCSS. I'm working on it now.

**Comment by aeschli** [comment] 2016-10-21 19:05
I agree that we should filter the functions by the return type. We have the type information for all properties, so it shouldn't be very hard to implement. Unfortunately I'm busy with other stuff, but I'm happy to provide help if someone wants to give it a try. The code is inhttps://github.com/Microsoft/vscode-css-languageservice/blob/master/src/services/scssCompletion.ts.

**Comment by mrmlnc** [comment] 2016-10-21 21:36
@aeschli, @druellan, I'll try to resolve this issue at the weekend.

**Comment by BergkampHUN** [comment] 2017-01-27 13:06
Any update for this issue?
Every time I try to write 'display: block;' with b or bl it suggests me the 'blue()' function.
Same for the 'none' value with 'nth()'.
![screen shot 2017-01-27 at 14 04 24](https://cloud.githubusercontent.com/assets/5220961/22371817/95f02d04-e499-11e6-86d9-b024875b0b57.png)

**Comment by aeschli** [comment] 2017-04-21 17:43
I pushed a fixed that adds more filtering. The remaining functions that don't return a specific type are sorted to the end.

**Closed by aeschli** 2017-04-21 17:43 UTC
Labels: css-less-sass, feature-request
