### ISSUE TITLE
Dubious minimized multi-line diagnostic rendering in Problems view 

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#69473] opened 2019-02-26 18:05 UTC
- VSCode Version:  1.32.0-insider (7d0c9e6fa0bedcf71bdae86c02611b65362795a3)
- OS Version: macOS 10.14.3

Steps to Reproduce:
We're working on producing user-friendly error messages for XML (See https://github.com/redhat-developer/vscode-xml/issues/91#issuecomment-467531576), so this is an unreleased WIP. Anyways:

1. Diagnostic returned like:
```
[Trace - 12:49:35 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/fbricon/Dev/projects/lsp4xml/pom.xml",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 6,
                    "character": 2
                },
                "end": {
                    "line": 6,
                    "character": 5
                }
            },
            "severity": 1,
            "code": "cvc-complex-type.2.4.a",
            "source": "xml",
            "message": "Invalid element name:\n - foo\n\nOne of the following is expected:\n - parent\n - name\n - description\n - url\n - inceptionYear\n - organization\n - licenses\n - developers\n - contributors\n - mailingLists\n - prerequisites\n - modules\n - scm\n - issueManagement\n - ciManagement\n - distributionManagement\n - properties\n - dependencyManagement\n - dependencies\n - repositories\n - pluginRepositories\n - build\n - reports\n - reporting\n - profiles\n\nError indicated by:\n {http://maven.apache.org/POM/4.0.0}\nwith code:"
        }
    ]
}
```
2. In the problems view, when the diagnostic message is folded, it becomes completely unreadable
<img width="1380" alt="screen shot 2019-02-26 at 12 22 06 pm" src="https://user-images.githubusercontent.com/148698/53435572-1da2e280-39c7-11e9-8e52-3fc131332738.png">

Does this issue occur when all extensions are disabled?: Probably

**Comment by fbricon** [comment] 2019-02-26 18:07
It'd probably make more sense to either
- show the 1st line only, add ellipsis
- remove line breaks, add ellipsis

**Comment by sandy081** [comment] 2019-02-27 15:17
Duplicate of https://github.com/Microsoft/vscode/issues/67273

**Closed** 2019-02-27 15:17 UTC
Labels: *duplicate, error-list
