### ISSUE TITLE
Wrong highlight with Notebooks & Python

### ISSUE THREAD

**Issue by PabloBotas** [microsoft/vscode#131627] opened 2021-08-25 10:28 UTC
Does this issue occur when all extensions are disabled?: If I disable all extensions I can not work with Jupyter notebooks. This question does not apply. Active extensions are: Jupyter, Pylance and Python.

- VS Code Version:
    - Version: 1.59.1 (user setup)
    - Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
    - Date: 2021-08-19T11:56:46.957Z
    - Electron: 13.1.7
    - Chrome: 91.0.4472.124
    - Node.js: 14.16.0
    - V8: 9.1.269.36-electron.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:
Sorry but I can not describe a series of steps. When working with notebooks, VS Code will highlight things that are simply not correct. When selecting a word, it will highlight areas where that word is not located. Find and replace is also buggy.

See image for reference: The `per_algorithm` part is highlighted as not used while it the `case_stats` should. The underline of print and return are also wrong.

![imagen](https://user-images.githubusercontent.com/12137767/130773852-e9b746d0-72cf-4311-b16d-0b7b1af8e596.png)

What can I do?
Thanks!

**Comment by rebornix** [comment] 2021-08-30 21:40
cc @rchiodo

**Comment by rchiodo** [comment] 2021-08-30 21:43
This should be a dupe of https://github.com/microsoft/vscode-jupyter/issues/6333 which was fixed in the python extension. The next release of VS code should address this.

**Closed by rchiodo** 2021-08-30 21:43 UTC
