### ISSUE TITLE
allow repositioning of the tooltips that pop up with code hints

### ISSUE THREAD

**Issue by bobmagicii** [Microsoft/vscode#10720] opened 2016-08-19 20:25 UTC
allow telling vscode to always put tooltips underneath the cursor and not above it. this is because when you are trying to write code that references code above it covers what you are trying to read, and its sooooooo bloody annoying such that i just turn all intellisense/help/tips/whatever off.

for example this code where i am attempting to fill in an SPRINTF function by seeing the tokens i used above to know what order to add my arguments...

![screen shot 2016-08-19 at 3 21 19 pm](https://cloud.githubusercontent.com/assets/881944/17823185/da388260-6620-11e6-85dc-5d398649871a.png)

the problem is this happens instead...

![screen shot 2016-08-19 at 3 20 03 pm](https://cloud.githubusercontent.com/assets/881944/17823193/e79236c2-6620-11e6-91af-5c55237edeeb.png)

![z](https://cloud.githubusercontent.com/assets/881944/17823256/29abd946-6621-11e6-9de4-9cb638a187f7.jpg)

**Comment by joaomoreno** [comment] 2016-08-22 08:19
Duplicate of #7984

**Closed by joaomoreno** 2016-08-22 08:19 UTC
