### ISSUE TITLE
Profile keeps coming back after deleting it

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#223378] opened 2024-07-23 20:08 UTC
Testing #223080

Not sure how best to repro it, let me know if you need more info. No errors in devtools console.

https://github.com/user-attachments/assets/af73c75b-2fdd-4b28-9d9c-98c51f3a5049

**Comment by connor4312** [comment] 2024-07-23 20:11
I notice this log in settings sync whenever I see the profile reappear:

```
2024-07-23 13:09:51.402 [info] Auto Sync: Triggered by Activity
2024-07-23 13:09:51.402 [info] Sync started.
2024-07-23 13:09:51.549 [error] Error: Profile with Untitled name already exists
    at /var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:111:45354
    at m.F (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:111:45655)
    at m.createProfile (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:111:45076)
    at Object.call (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:47:5329)
    at y.s (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:45:6820)
    at y.q (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:45:6275)
    at P.value (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:45:5584)
    at i.B (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:41:743)
    at i.C (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:41:815)
    at i.fire (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:41:1034)
    at MessagePortMain.ee (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:36:48761)
    at MessagePortMain.emit (node:events:519:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/browser_init:2:102131)
2024-07-23 13:09:51.549 [error] profiles: Profile with Untitled name already exists
2024-07-23 13:09:51.550 [info] Syncing profile. empty
2024-07-23 13:09:51.550 [info] Syncing profile. ext-profile
2024-07-23 13:09:51.550 [info] Sync done. Took 149ms
2024-07-23 13:09:51.551 [info] Profiles: Created profile 'Untitled<'.
2024-07-23 13:09:53.602 [info] Auto Sync: Triggered by Activity
2024-07-23 13:09:53.602 [info] Sync started.
2024-07-23 13:09:53.723 [error] Error: Profile with Untitled name already exists
    at /var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:111:45354
    at m.F (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:111:45655)
    at m.createProfile (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:111:45076)
    at Object.call (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:47:5329)
    at y.s (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:45:6820)
    at y.q (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:45:6275)
    at P.value (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:45:5584)
    at i.B (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:41:743)
    at i.C (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:41:815)
    at i.fire (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:41:1034)
    at MessagePortMain.ee (/var/lib/snapd/snap/code-insiders/1694/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:36:48761)
    at MessagePortMain.emit (node:events:519:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/browser_init:2:102131)
2024-07-23 13:09:53.723 [error] profiles: Profile with Untitled name already exists
2024-07-23 13:09:53.724 [info] Syncing profile. empty
2024-07-23 13:09:53.724 [info] Syncing profile. ext-profile
2024-07-23 13:09:53.724 [info] Sync done. Took 122ms
```

**Comment by sandy081** [comment] 2024-07-24 06:08
@connor4312 I am not able to reproduce the issue. Does this happen even when settings sync is on?

**Comment by sandy081** [comment] 2024-07-25 06:25
Can you please enable trace log level and share the settings sync log?

**Comment by connor4312** [comment] 2024-07-26 17:05
Unfortunately after turning trace log on and reloading, the deletion actually worked, so I'm no longer in this state 😕

**Comment by sandy081** [comment] 2024-07-29 07:22
Thats very unfortunate. Its very difficult to investigate and fix if there is no repro. I am sorry that I have to close this. I would request to have the trace log enabled always and provide the logs if you see the issue again. Thanks.

**Closed by sandy081** 2024-07-29 07:22 UTC
Labels: info-needed, settings-sync, user-profiles
