### ISSUE TITLE
terminal repeat bug

### ISSUE THREAD

**Issue by 2670961598** [microsoft/vscode#228311] opened 2024-09-12 06:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0
- OS Version: windows enterprise 21h2

Steps to Reproduce:

1. there is some output in the terminal, and this output fills up the terminal window.At this point, using the mouse wheel to scroll down is not possible.
2. Then, use the mouse to drag the top edge of the terminal downward, compressing a certain number of lines, but don't release the mouse. Drag it back up, and at this point, some blank lines will appear at the bottom of the terminal.
At this point, scroll up a certain distance using the mouse wheel, ensuring that the right side is not at the bottom of the terminal.
3. At this point, continuously click and hold the top edge of the terminal with the mouse, dragging it up and down to constantly change the terminal's size. A large amount of repeated information and blank lines will then appear in the terminal.

**Comment by meganrogge** [comment] 2024-09-12 14:39
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Comment by 2670961598** [comment] 2024-09-13 01:06
the vision i used is the latest vision.



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 12, 2024 14:46 PM
To: ***@***.***&gt;;
Cc: "Ye ***@***.******@***.***&gt;;
Subject: Re: [microsoft/vscode] terminal repeat bug (Issue #228311)




 
Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.93.0. Please try upgrading to the latest version and checking whether this issue remains.
 
Happy Coding!

**Closed** 2024-09-13 15:43 UTC
Labels: upstream, windows, terminal-conpty
