### ISSUE TITLE
Port forwarding for remote-ssh doesn't notice closed socket on server side

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode#192627] opened 2023-09-08 20:54 UTC
Type: <b>Bug</b>

Since the 1.82.0 update, using port forwards for remote SSH development has been extremely difficult for me, as the port forwarding system doesn't seem to notice when a socket is closed on the server side.

This leads to my client application running on the local side (generally Chrome) sending packets (e.g. GET requests) into the port forward (which shows up in `netstat` as `ESTABLISHED` still from chrome to Code, but those packets seem to be dropped into the bit bucket as the socket from the vscode-server to my application is closed (in `TIME_WAIT`) on the server (remote development machine). This causes HTTP requests to time out (very ... verry ......... sloooooooooowly) which severely hampers being able to get anything done.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:18.759Z)
OS version: Linux x64 6.2.0-32-generic
Modes:
Remote OS version: Linux x64 5.10.0-25-cloud-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.18GB (22.54GB free)|
|Process Argv|--unity-launch --crash-reporter-id f628f52a-51ea-40c8-aedd-0af9d4a6bd9f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: gdm.mgabeler-lee|
|OS|Linux x64 5.10.0-25-cloud-amd64|
|CPUs|AMD EPYC 7B13 (16 x 2449)|
|Memory (System)|31.36GB (17.60GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.1
vscode-peacock|joh|4.2.2
remote-ssh|ms-|0.106.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
rewrap|stk|1.16.3
errorlens|use|3.13.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.19.0
markdown-preview-github-styles|bie|2.0.2
markdown-yaml-preamble|bie|0.1.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
EditorConfig|Edi|0.16.4
vscode-typescript-exportallmodules|eli|2.6.0
prettier-vscode|esb|10.1.0
terraform|has|2.27.2
bash-ide-vscode|mad|1.39.0
uuid-generator|net|0.0.5
vscode-commons|red|0.0.6
vscode-yaml|red|1.14.0
vscode-workspace-switcher|sad|1.15.3
code-spell-checker|str|3.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by Ashesh3** [comment] 2023-09-09 09:23
Possible duplicate of https://github.com/microsoft/vscode/issues/192521

**Comment by connor4312** [comment] 2023-09-11 21:39
This does appear to duplicate the linked issue

**Closed by connor4312** 2023-09-11 21:39 UTC
Labels: bug, remote-explorer, ssh, new release
