### ISSUE TITLE
Copy function fails over dangling symbolic links

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111621] opened 2020-12-01 13:42 UTC
Testing #111250

- Drag and Drop two folders into explorer
- Chooses to copy folders

![Kapture 2020-12-01 at 14 37 18](https://user-images.githubusercontent.com/10746682/100747810-d0954100-33e2-11eb-9d75-701757fcc4f9.gif)

- At the end only one folder is copied

![image](https://user-images.githubusercontent.com/10746682/100748137-3f729a00-33e3-11eb-9145-049a3ab17942.png)

**Comment by isidorn** [comment] 2020-12-03 15:01
I can only reproduce this when dragging two large folders like you do in your gif. 
The issue here is that I pass two `ResourceFileEdits` to the `BulkEditService`. `BulkEditService` probably passes them in parallel to the `FileService` and it seems like the `FileService` can not handle moving all these resources in parallel. I think the `FileService` can not handle these parallel operations because I believe in the past I was on purpose calling it sequantally to work around this.

Moving to next milestone since it is fine to fix in debt week.

First also assgning this to @jrieken 
fyi @bpasero 

We shuold figure out if `FileService` can fix this on its end or we need to do a workaround and if yes on what layer?

**Comment by bpasero** [comment] 2020-12-03 15:46
A bug in file service would be very surprising to me, I am sure users do a lot of copy/paste in the explorer while selecting multiple folders, no?

**Comment by isidorn** [comment] 2020-12-03 16:11
@bpasero yes, but that was sequantial up until this release. Now we also do that in parallell. 
I tried and I could not reproduce this issue if I just copy paste from the Explorer using the same folders...

**Comment by bpasero** [comment] 2020-12-03 16:19
Oh ok, didn't know.

**Comment by sandy081** [comment] 2020-12-03 19:21
> but that was sequantial up until this release. Now we also do that in parallell.

Just want to double check if this parallel behaviour breaks any existing flows?

**Comment by isidorn** [comment] 2020-12-03 19:22
Hopefully not, that is why there was a couple of test plan items and why we did this 2 weeks ago in insiders. So far there hasn't been other issues than this.

**Comment by bpasero** [comment] 2020-12-04 06:39
The only scenario where I see this breaking is when the target to copy into is overlapping. I doubt that a user could trigger this though.

**Comment by jrieken** [comment] 2020-12-11 14:01
Unassigning myself since bulk edit is just forwarding those operations

**Comment by pmpetit** [comment] 2020-12-31 07:13
Hi,
for your information, i have moved 2 folders using drap and drop. Only 1 was moved. and it was empty after moving !
so i lost all my tf files.....

**Comment by isidorn** [comment] 2021-01-22 09:45
I can repro this quite easily and I believe the issue is that if a an error happens deep down in the `fileService` the `fileService` does not continue to copy the rest of the large folder.

Repro steps
1. Open finder, and select `vscode` and `vscode-distro` and drag and drop them into VS Code
2. Notice how just the `vscode` folder got partially copied, there is an error in the console

I would expect that the `fileService` continous copying even if an error happens for some file.
@bpasero can you maybe look into this from the `fileService` side please?

```
 ERR EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/Users/isidor/Development/vscode/extensions/node_modules/.bin/tsc'
    at Object.createFileSystemProviderError (file:///Users/isidor/Development/vscode/out/vs/platform/files/common/files.js:63:31)
    at DiskFileSystemProvider.toFileSystemProviderError (file:///Users/isidor/Development/vscode/out/vs/platform/files/node/diskFileSystemProvider.js:533:28)
    at DiskFileSystemProvider.copy (file:///Users/isidor/Development/vscode/out/vs/platform/files/node/diskFileSystemProvider.js:390:28)
    at async FileService.doMoveCopy (file:///Users/isidor/Development/vscode/out/vs/platform/files/common/fileService.js:517:21)
    at async FileService.copy (file:///Users/isidor/Development/vscode/out/vs/platform/files/common/fileService.js:495:26)
    at async WorkingCopyFileService.doMoveOrCopy (file:///Users/isidor/Development/vscode/out/vs/workbench/services/workingCopy/common/workingCopyFileService.js:134:36)
    at async CopyOperation.perform (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/bulkEdit/browser/bulkFileEdits.js:107:27)
    at async BulkFileEdits.apply (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/bulkEdit/browser/bulkFileEdits.js:342:36)
    at async BulkEdit._performFileEdits (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/bulkEdit/browser/bulkEditService.js:86:13)
    at async BulkEdit.perform (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/bulkEdit/browser/bulkEditService.js:69:21)
    at async BulkEditService.apply (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/bulkEdit/browser/bulkEditService.js:164:17)
    at async file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/explorerService.js:118:17
```

**Comment by bpasero** [comment] 2021-01-22 12:53
Yeah, would be great to have a unit test for this that reproduces it.

**Comment by bpasero** [comment] 2021-01-25 06:57
This is actually a bug in our `copy` function when a symbolic link is encountered that is dangling.

**Closed** 2021-01-25 07:15 UTC
Labels: bug, file-explorer

**Comment by bpasero** [comment] 2021-01-25 07:16
Opened https://github.com/microsoft/vscode/issues/114881 to track supporting symlinks.

**Comment by isidorn** [comment] 2021-01-25 08:29
@bpasero thanks for looking into this and for fixing

**Comment by bpasero** [comment] 2021-01-25 08:46
@isidorn I am not sure though why the one copy operation would cause the other to stop, that is maybe something you could look into after my fix went in. Maybe you still copy in sequence?

**Comment by isidorn** [comment] 2021-01-25 12:48
From multiple drag and drop operations I create one `BulkEdit`. Though probably somewhere there is code that canceles the rest of the bulkEdit if one part fails. I can investigate more
