### ISSUE TITLE
Enable additional folding regions to be specified in settings.json

### ISSUE THREAD

**Issue by jasper-zanjani** [microsoft/vscode#119802] opened 2021-03-24 15:53 UTC
Although many language extensions offer great folding support, extension authors can't be expected to cover all cases for highly extensible syntaxes like Markdown, which has a fantastic [extension](https://github.com/yzhang-gh/vscode-markdown). If additional folding regions could be specified in settings.json using a syntax similar to that available for [language configuration](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding), it would greatly expand the ability of users to customize their environment.

Example specification of a folding region that could support [pymdownx](https://github.com/facelessuser/pymdown-extensions)-style tabs (I actually don't know how to specify that the next unindented line should terminate the folding region).
```json
{
  "folding": {
    "markers": {
      "start": "=== \".*\""
    }
  }
}
```

**Comment by aeschli** [comment] 2021-03-24 16:32
duplicate of https://github.com/microsoft/vscode/issues/36002

**Closed by aeschli** 2021-03-24 16:32 UTC
