### ISSUE TITLE
Markdown Preview right side display problem with zoom

### ISSUE THREAD

**Issue by michaelteter** [Microsoft/vscode#22042] opened 2017-03-06 02:46 UTC
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Open a markdown file
2. cmd k v to open a markdown preview
3. cmd + or cmd - to zoom in or out

At zoom 0, it looks normal.  At zoom -1, the scroll bar is missing and the right side of long lines is cut off.  At zoom +1 the window area and scroll bar are shifted inside the workspace frame, leaving a gap.

**zoom 0**
<img width="101" alt="zoom0" src="https://cloud.githubusercontent.com/assets/411964/23595051/0d72bde0-021f-11e7-9cda-5cd52e39c83a.png">

**zoom -1**
<img width="73" alt="zoom-1" src="https://cloud.githubusercontent.com/assets/411964/23595055/1545af6e-021f-11e7-8faf-15cb878b860b.png">

**zoom +1**
<img width="182" alt="zoom 1" src="https://cloud.githubusercontent.com/assets/411964/23595056/187ba5c6-021f-11e7-83ae-05d460d4c99a.png">

**Comment by mjbvz** [comment] 2017-03-06 03:57
Duplicate of #5745

**Closed by mjbvz** 2017-03-06 03:57 UTC
Labels: duplicate, webview
