### ISSUE TITLE
macOS High Sierra: parts of the UI not rendering

### ISSUE THREAD

**Issue by EagleEYErus** [Microsoft/vscode#35527] opened 2017-10-03 13:36 UTC
- VSCode Version: 1.16.1
- OS Version: macOS High Sierra 10.13

Steps to Reproduce:

Interface crashes when I open a file in the project folder tree.
<img src="https://user-images.githubusercontent.com/15634499/31127750-60e44d88-a858-11e7-9842-0e07d65bb563.png">

Reproduces without extensions: Not Tested

**Comment by isidorn** [comment] 2017-10-03 13:46
Can you reproduce this with vscode insiders?
https://code.visualstudio.com/Insiders/

**Comment by EagleEYErus** [comment] 2017-10-03 14:21
@isidorn I will try, but I have not yet understood the sequence of steps to cause the crash. This happens randomly.

**Comment by isidorn** [comment] 2017-10-03 14:30
@EagleEYErus without the sequence of steps there is not much we can do

**Comment by chasegiunta** [comment] 2017-10-04 02:21
I’ve also recently had this begin happening after update to High Sierra, though it’s not specific to opening a file in tree. Completely random. It also appears to happen on other electron apps (Slack) though I haven’t been able to track down an electron issue for it anywhere yet.

**Comment by chasegiunta** [comment] 2017-10-04 02:34
@EagleEYErus are you using an external monitor by chance? Is it high dpi?

**Comment by bpasero** [comment] 2017-10-04 04:45
@chasegiunta does it make a difference if you run "`code --disable-gpu`" from the command line?

**Comment by elijnzaad** [comment] 2017-10-04 08:07
I've experienced similar problems since upgrading to High Sierra. After a while the screen goes to a screen like EagleEYErus's. The after a minute or so it gradually comes back to life. I am using a MacBook Pro with a 4K external monitor, but I've experienced the same problems while not using the monitor.

Running "open Visual\ Studio\ Code.app --args --disable-gpu" from the terminal seems to have fixed the problem. It is running trouble-free for about an hour now.

**Comment by bpasero** [comment] 2017-10-04 08:50
@EagleEYErus @elijnzaad does it run any better with our insiders build (NOT using `--disable-gpu`): http://code.visualstudio.com/Download#insiders

**Comment by elijnzaad** [comment] 2017-10-04 09:21
No, it doesn't.

**Comment by bpasero** [comment] 2017-10-04 09:32
@elijnzaad sorry, bad link: https://code.visualstudio.com/insiders/

**Comment by elijnzaad** [comment] 2017-10-04 09:40
I'm sorry, but the insiders build does have the same problem as the production build. It didn't take me more than 2 minutes. The screenshot shows the first thing I did, which is adjusting the user settings.
![screen shot 2017-10-04 at 11 38 56](https://user-images.githubusercontent.com/2039732/31169407-cd2efc18-a8f8-11e7-9fef-ab38d5db4398.png)

**Comment by EagleEYErus** [comment] 2017-10-04 09:41
@chasegiunta I did not use external monitors at the time the error was received. The first time a bug appeared on the MacOS High Sierra on the MacBook Air 13' 2013. For one development session, UI crashed several times. Then I ran into this problem yesterday on my iMac 27' late 2013. Then I tried to cause the error intentionally, but I did not find the sequence of steps, although it arose again when I changed the application window, but when I tried to repeat these actions nothing happened. I do not remember exactly, but the discord also seemed to give out this crash.

**Comment by EagleEYErus** [comment] 2017-10-04 09:44
@elijnzaad UI after the crash was restored only once otherwise I had to restart the application

**Comment by EagleEYErus** [comment] 2017-10-04 09:46
@elijnzaad Don't you have extensions for the insider version?

**Comment by bpasero** [comment] 2017-10-04 09:49
@EagleEYErus @elijnzaad does this only reproduce on external monitor or also on the macbook pro screen? for external monitor, are they 4k/5k monitors?

**Comment by elijnzaad** [comment] 2017-10-04 09:50
@EagleEYErus I actually hadn't done anything in the insider build. I downloaded it, started it and selected Preferences -> User settings from the menu. That's all, no extensions.

**Comment by EagleEYErus** [comment] 2017-10-04 09:56
@bpasero I did not use external monitors during the crash, and, as I wrote above, the maximum resolution of all the devices I use is 2560x1440

**Comment by elijnzaad** [comment] 2017-10-04 09:59
@bpasero I did use a Philips BDM4037U 4K external monitor. I'm currently running VSCode without the external monitor on a MacBook Pro (Retina, Mid 2012), Graphics NVIDIA GeForce GT 650M 1 GB
Intel HD Graphics 4000 1536 MB. So far no problems yet.

**Comment by EagleEYErus** [comment] 2017-10-04 10:14
@bpasero This screenshot I made on iMac 27-inch (2560 x 1440) late 2013
3.4 GHz Intel Core i5
NVIDIA GeForce GTX 775M 2 ГБ

**Comment by elijnzaad** [comment] 2017-10-04 10:15
@bpasero Yes, I'm running VSCode Insider without --disable-gpu and without the external monitor. No problems yet.

**Comment by EagleEYErus** [comment] 2017-10-04 15:27
@bpasero Again, this error occurred a few hours ago on iMac, UI crashed when I changed tab and recovered in a few seconds.

**Comment by bpasero** [comment] 2017-10-04 15:40
@EagleEYErus so this issue goes away after some second back to a functional UI, is that true?

**Comment by EagleEYErus** [comment] 2017-10-04 15:56
@bpasero Last time, yes, but not always.

**Comment by bpasero** [comment] 2017-10-04 16:12
Can someone capture a video when this happens and attach it? I would just like to understand how this surfaces.

**Comment by EagleEYErus** [comment] 2017-10-04 16:30
@bpasero I found an excerpt from my stream
https://clips.twitch.tv/AbnegateEndearingAnisePRChase

**Comment by chasegiunta** [comment] 2017-10-04 17:10
If it's relevant for graphic driver issues, using MBPro Retina (Late 2013) NVIDIA GeForce GT 750M 2 GB / Intel Iris Pro 1536 MB. High Sierra - using a High DPI external display, but happens on both screens.

Does go away after some 2-30 seconds. Typically hovering the mouse over the UI helps after some time. Hiding / Minimizing the window and bringing back has no effect in resolving.

Just started today but will report back if I continue to see the issue when running with `--disable-gpu`.

**Comment by bpasero** [comment] 2017-10-05 04:22
@EagleEYErus thanks. It looks awfully like https://github.com/Microsoft/vscode/issues/25934 which was fixed by a Chrome fix we took in where the GPU buffer was running our of memory. 

Does it help to set `"editor.disableTranslate3d": true` ?

**Comment by bpasero** [comment] 2017-10-05 07:31
@EagleEYErus @chasegiunta @elijnzaad here are a couple of things to try out to see if it improves the situation:
* configure `"editor.disableTranslate3d": true`
* run `code --disable-gpu-rasterization`
* run `code --disable-mac-overlays`
* run `code --force_integrated_gpu`

**Comment by elijnzaad** [comment] 2017-10-05 07:49
@bpasero VSCode 1.16.1 with ```"editor.disableTranslate3d": true``` is running fine for an hour now (on the 40-inch Philips monitor).

**Comment by elijnzaad** [comment] 2017-10-05 07:51
@bpasero Would you like us to try out the flags one-by-one to see which one does the trick?

**Comment by bpasero** [comment] 2017-10-05 08:21
@elijnzaad yeah that would be nice. Thanks for doing this.

**Comment by EagleEYErus** [comment] 2017-10-05 08:51
@bpasero Is it normal that the VSCode says that the property `editor.disableTranslate3d` was not found: "Unknown configuration setting"

**Comment by bpasero** [comment] 2017-10-05 09:01
@EagleEYErus sorry for that, I forgot that we took out the setting `disableTranslate3d` some releases ago. Still, the test with the other command line flags would be interesting to do.

**Comment by EagleEYErus** [comment] 2017-10-05 09:19
@bpasero  Well, I'll try now with the flag `code --disable-gpu-rasterization`. After restarting the VSCode, does the app start without flags in normal mode?

**Comment by bpasero** [comment] 2017-10-05 09:36
@EagleEYErus no unfortunately not, these flags need to be provided on startup. I fear there would not even be a simple way for us to make this configurable via settings...

**Comment by elijnzaad** [comment] 2017-10-05 09:41
@bpasero code 1.16.1 --disable-gpu-rasterization runs fine so far. Will now try --disable-mac-overlays

**Comment by EagleEYErus** [comment] 2017-10-05 11:09
@bpasero worked with the flag `--disable-gpu-rasterization` for about an hour and a half, everything worked well too. Will try `code --force_integrated_gpu`

**Comment by elijnzaad** [comment] 2017-10-05 11:32
@bpasero code 1.16.1 -disable-mac-overlays does run with the major blackouts, but it is more sluggish and sometimes it makes the windows flicker. This is not my favourite options so far. Will now try --force_integrated_gpu

**Comment by EagleEYErus** [comment] 2017-10-05 11:36
@bpasero `code --force_integrated_gpu` start and immediately crash
https://user-images.githubusercontent.com/15634499/31225380-7d35d492-a9da-11e7-935c-9f28c55122aa.png

**Comment by elijnzaad** [comment] 2017-10-05 11:55
@bpasero Confirmed. --force_integrated_gpu causes problems on my system as well.

**Comment by bpasero** [comment] 2017-10-05 13:25
@EagleEYErus @elijnzaad and whats the exact hardware this is on (e.g. which hardware model and year?). Maybe this issue only shows up for very specific GPUs.

I am now also on high sierra and so far have not seen any issues.

**Comment by elijnzaad** [comment] 2017-10-05 13:31
@bpasero  
Laptop:
MacBook Pro (Retina, Mid 2012), 
Processor 2,6 GHz Intel Core i7, 
Memory 16Gb RAM 1600 Mhz DDR3, 
Graphics NVIDIA GeForcte GT 650M 1 GB, Intel HD Graphics 4000 1536Mb

Monitor:
2017 Philips BDM4037U 40-inch 4K, running at 30Ghz connected via HDMI

**Comment by EagleEYErus** [comment] 2017-10-05 13:44
@bpasero 
iMac:
iMac (27-inch, Late 2013),
Processor 3,4 GHz Intel Core i5,
Memory 16Gb 1600 MHz DDR3,
Graphics NVIDIA GeForce GTX 775M 2Gb

MacBook:
MacBook Air (13-inch, Mid 2013),
Processor 1,3 GHz Intel Core i5,
Memory 4Gb 1600 MHz DDR3,
Graphics Intel HD Graphics 5000 1536Mb

On both computers, I encountered a crash

**Comment by chasegiunta** [comment] 2017-10-05 14:17
Macbook Pro (Retina, Late 2013)
Processor 2.3 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3
Graphics NVIDIA GeForce GT 750M 2 GB, Intel Iris Pro 1536 MB

Late to the replies here, but as the others have echoed, it doesn't occur with `--disable-gpu` . Will attempt the other flags today.

**Comment by elijnzaad** [comment] 2017-10-05 14:22
@bpasero VSCode 1.16.1 seems to be running fine without any flags on my iMac 5K 27inch late 2014, 4Ghz Intel Core i7, 32Gb 1600MHz DDR3, AMD Radeon R9 M290X 2GB. So perhaps you are right in thinking that it is hardware related.

**Comment by bpasero** [comment] 2017-10-05 15:14
At first I was thinking it could be the integrated GPU on the Macs, but given https://github.com/Microsoft/vscode/issues/35527#issuecomment-334469117 on an iMac where afaik there is only a single GPU, this theory seems wrong. 

So far the only pattern I can see that it happens with Macs before 2014'ish.

**Comment by EagleEYErus** [comment] 2017-10-06 14:18
@bpasero I don't know if this information will be useful, but I just got exactly the same problem in the discord

<img src="https://user-images.githubusercontent.com/15634499/31282163-5792c840-aaba-11e7-8519-2e4cc6dbb61e.png">

**Comment by chasegiunta** [comment] 2017-10-06 14:32
I also experience it in Slack (another Electron app).

**Comment by EagleEYErus** [comment] 2017-10-06 14:44
@chasegiunta can there be an error in the electron?

**Comment by chasegiunta** [comment] 2017-10-06 14:48
@EagleEYErus I would assume so. Though _there could potentially be_ some steps that apps like vscode could take to remedy them.

**Comment by EagleEYErus** [comment] 2017-10-06 15:11
@chasegiunta hope so

**Comment by trumbitta** [comment] 2017-10-06 16:34
I managed to **somehow** get it to work again by:

- downgrading to 1.16.1
- waiting for 1.17 to be ready for installation again
- **rebooting High Sierra**
- done

**Comment by trumbitta** [comment] 2017-10-07 12:01
Now that I re-read my own comment, it reminds me of when playing DAoC at some early version you had to reboot the PC every few hours because artefacts would start popping all over the screen and wouldn't go away. It ended up being an issue with some video buffer and rebooting would clean it.

Also, @bpasero , my MBP is from < 2014 too.

**Comment by nktka** [comment] 2017-10-08 12:06
Same occurs to me in chrome, in addition to VSCode. 
I have mid 2012 non-retina macbook pro + external hiDPI monitor.

**Comment by EagleEYErus** [comment] 2017-10-08 12:46
@bpasero @nktka 

> Same occurs to me in chrome, in addition to VSCode.

Maybe the problem is in chromium or v8 and macOS High Sierra because electron and Chrome use it both.

**Comment by bpasero** [comment] 2017-10-10 10:40
Reported this to Electron as https://github.com/electron/electron/issues/10736

**Comment by chasegiunta** [comment] 2017-10-10 14:22
@bpasero Appreciate the help. It may be even higher than them. I've noticed the same issue in Chrome a couple times over the past few days (it's very apparent that it happens _way more_ in Electron apps for some reason). So, potentially a Chromium issue? Though, as I mentioned before, hopefully there's some steps to alleviate it in Electron or vscode. Thanks for the report.

**Comment by mrazahasan** [comment] 2017-10-12 14:30
i am unable to code on Visual studio because Visual studio code UI is destroyed when i open it on my mac Sierra v: 10.12.6
my screen resolution is: 1600 : 1200
attached is the screenshot
![vs code ui bug](https://user-images.githubusercontent.com/6910569/31501432-b0e769a0-af83-11e7-89e9-10b3ea66cb81.png)

**Comment by Jasonlhy** [comment] 2017-10-12 20:38
Surprisingly, after I upgrade my MacBook Air 2011 to High Sierra. vscode 1.17.1 works fine.

![screen shot 2017-10-13 at 4 34 20 am](https://user-images.githubusercontent.com/1687930/31517942-27d1f2f0-afd0-11e7-962c-97b33291b6dc.png)

![screen shot 2017-10-13 at 4 32 19 am](https://user-images.githubusercontent.com/1687930/31517949-2c8f024c-afd0-11e7-8d29-894b9d748be0.png)

**Comment by EagleEYErus** [comment] 2017-10-12 20:43
@Jasonlhy yesterday or the day before yesterday I caught a few UI crashes for one development session on my device

**Comment by chasegiunta** [comment] 2017-10-12 21:16
This is above vscode, and likely even Electron. Anyone stumbling upon this issue and wants to echo their troubles, you can do so at https://github.com/electron/electron/issues/10736 or better yet on the Chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=773705

**Comment by bpasero** [comment] 2017-10-25 13:39
If anyone seeing this issue could report back if it still reproduces with this insider build: https://az764295.vo.msecnd.net/insider/7dec12f226bc98992bc8413340ea28281f6e94a0/VSCode-darwin-insider-unsigned.zip

Thanks!

**Comment by mrazahasan** [comment] 2017-10-25 16:49
@bpasero nupz still UI not rendering properly. Its electron problem i guess. :(

**Comment by bpasero** [comment] 2017-10-25 17:00
@mrazahasan I think you might be seeing something else, so far I thought this issue would only manifest on macOS high sierra.

**Comment by bpasero** [comment] 2017-10-26 12:15
@EagleEYErus @chasegiunta ping

**Comment by brosner** [comment] 2017-10-26 14:19
@bpasero I have been following this issue and have been experiencing it myself. I can confirm today's insider update is showing very positive signs of a fix. I have not yet seen the issue yet. I will continue to use it and see if it crops up as it is mostly random. One case that caused the issue for me *before* updating was with vigorous window resizing and I don't see it after updating.

**Comment by bpasero** [comment] 2017-10-26 15:34
@brosner awesome, thanks

**Comment by chasegiunta** [comment] 2017-10-26 15:47
@bpasero Would love to test this out today if there's an easy way to reliably bring all my extensions & settings into Insiders. Can I ask what potential fixes were made? Checking for GPU and/or device type and conditionally disabled GPU?

**Comment by bpasero** [comment] 2017-10-26 16:28
@chasegiunta the fix disables certain GPU features when a NVIDIA GPU is detected.

For syncing, maybe try https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by stenmuchow** [comment] 2017-10-27 11:24
Every time I update OSX i get such crap... Im gonna try the insider update and see what happens. Remember when OSX made good softwear? Nah - me neither :(

**Comment by stenmuchow** [comment] 2017-10-27 11:33
@bpasero the insider install via the link you shared seems stable - for now. 

https://puu.sh/y8nTO/404f2c44ee.png

**Comment by stenmuchow** [comment] 2017-11-02 09:13
After using insiders for the last 5 days i confirm no more strange problems. Will this be moved to the regular @code or do i continue to use insiders? @bpasero

**Comment by bpasero** [comment] 2017-11-02 09:32
@stenmuchow thanks for the confirmation. Yes, the "fix" will go into stable. It is not a real fix of the underlying problem, rather we disable certain GPU features on certain hardware. So I would still like to keep this open and see if a real fix lands. The real fix might actually require Apple to fix something in High Sierra, so it might not even be possible to fix it in Electron.

**Comment by mehulkar** [comment] 2017-11-04 19:44
Another piece of info that I didn't see in this thread on quick glance... after the glitches happened, I quit VSCode and then can't reopen it. It crashes immediately on launch. It's in that state right now. This has happened once before and a reboot fixed the issue. Let me know if I can get you any more info before I reboot! (I tried launching through CLI with some of the flags mentioned in this post, but it still crashes on launch immediately). I'll wait till tomorrow to reboot my machine and use a diferent editor till then.

**Comment by stuartaccent** [comment] 2017-11-09 13:01
just for info and sorry if u already know all this. 

Have OSX 10.13.1 with NVIDIA GeForce GTX 660M 512 MB and just downloaded nvidias own drivers from https://www.tonymacx86.com/nvidia-drivers. So far all glitches have gone for any app using electron. Im a happy man again :)

**Comment by trumbitta** [comment] 2017-11-09 13:11
@stuartaccent how come NVIDIA provides official drivers via tonymacx86.com?

**Comment by stuartaccent** [comment] 2017-11-09 13:15
thats just a page with links ie: https://images.nvidia.com/mac/pkg/378/WebDriver-378.10.10.10.20.107.pkg

**Comment by bpasero** [comment] 2017-11-16 06:52
Closing, since our workaround is in and Chrome has fixed this meanwhile, we just need to pick it up in one of our future Electron updates.

**Closed by bpasero** 2017-11-16 06:52 UTC
Labels: electron, mac, needs more info, upstream

**Comment by sledsworth** [comment] 2017-11-17 03:03
Did this ever actually get ‘fixed’ or is the fix still disabling hardware on Macs with Nvidia cards?

**Comment by stenmuchow** [comment] 2017-11-17 08:38
Seems updating NVIDIA drivers has given my machine a more stable feel... Using like from @stuartaccent
