### ISSUE TITLE
unable to install extensions

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#8915] opened 2016-07-08 09:02 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.4.0-28-generic

Steps to Reproduce:

1.  View => Extensions
2.  ... => Show Popular Extensions
3. Select an Item 
4. then Click [install]
5. No response

**Comment by qsimpleq** [comment] 2016-07-08 09:23
Same problem

**Comment by CJStroud** [comment] 2016-07-08 12:14
I have the same issue with Fedora 23

**Comment by baltth** [comment] 2016-07-08 12:27
Same on Ubuntu 16.04 LTS

**Comment by seemsindie** [comment] 2016-07-08 13:05
same here on arch

**Comment by assertnotnull** [comment] 2016-07-08 13:46
I have that problem too on Mint 17.3

**Comment by stupid-beard** [comment] 2016-07-08 14:33
I have the same problem on Debian Jessie, installed from the .deb. A friend who used the zip says it works fine for him.

**Comment by draeron** [comment] 2016-07-08 15:39
same issue with CentOS 7, upgraded with rpm, extensions used to work in previous version.

**Comment by Tyriar** [comment] 2016-07-08 16:51
Duplicate of https://github.com/Microsoft/vscode/issues/8859

**Closed by Tyriar** 2016-07-08 16:51 UTC
