### ISSUE TITLE
Update service stuck 

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#214306] opened 2024-06-05 07:34 UTC
From @jrieken:

> Every once in a while I keep seeing this. It just says Downloading… for ~10 minutes and then no update is available

![image](https://github.com/microsoft/vscode/assets/22350/bff1fca7-3bee-482d-b690-8673631c2463)

```log
2024-06-04 00:30:23.686 [info] update#setState idle
2024-06-04 01:40:51.157 [info] update#setState checking for updates
2024-06-04 01:40:51.987 [info] update#setState idle
2024-06-04 02:47:45.152 [info] update#setState checking for updates
2024-06-04 02:47:45.836 [info] update#setState idle
2024-06-04 03:51:56.146 [warning] No ptyHost heartbeat after 6 seconds
2024-06-04 03:51:56.146 [info] update#setState checking for updates
2024-06-04 03:51:56.716 [info] update#setState idle
2024-06-04 05:01:46.160 [info] update#setState checking for updates
2024-06-04 05:01:46.950 [info] update#setState downloading
2024-06-04 06:57:36.124 [warning] No ptyHost heartbeat after 6 seconds
2024-06-04 08:15:12.346 [warning] No ptyHost heartbeat after 6 seconds
2024-06-04 08:32:17.777 [error] UpdateService error: The request timed out.
2024-06-04 08:32:17.778 [info] update#setState idle
```

**Comment by joaomoreno** [comment] 2024-06-05 07:34
This seems to happen because the machine wakes up for a short period of time from a good night's sleep.

**Comment by jrieken** [comment] 2024-06-05 07:41
dupes https://github.com/microsoft/vscode/issues/203289

**Comment by rzhao271** [comment] 2024-12-19 22:39
Closing as duplicate of https://github.com/Microsoft/vscode/issues/203289

**Closed by rzhao271** 2024-12-19 22:39 UTC
Labels: bug, install-update, macos
