### ISSUE TITLE
[Feature] Project Centennial - Windows Store

### ISSUE THREAD

**Issue by dihmandrake** [Microsoft/vscode#19887] opened 2017-02-03 23:29 UTC
In my opinion it would be great if one could just download Visual Studio Code from the Windows Store (Easier install and background updates). Furthermore, Microsoft would commit more to their own technologies and platform.

**Comment by mjbvz** [comment] 2017-02-03 23:35
Duplicate of #10759

**Closed by mjbvz** 2017-02-03 23:35 UTC
Labels: duplicate
