### ISSUE TITLE
Monaco: JSON format replaces space with tab indentation

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8459] opened 2016-06-28 22:33 UTC
Testing #8210 
- Monaco Version: 0.5.3
- Browser Version: Safari 9.1.1

Not sure if this is just "as designed".

Steps to Reproduce:
1. Open JSON file with only spaces as indentation
2. Format -> spaces are replaced with tabs

**Comment by aeschli** [comment] 2016-06-29 07:01
If you have `"editor.detectIndentation": true` (which is the default), the editor should detect that you use spaces and show it in the status line.
From what I understand and observe, that is what the formatter gets and uses. I can't reproduce what you are seeing.

@chrmarti What did the status line show for you?

**Comment by chrmarti** [comment] 2016-06-29 15:37
I did this in the standalone Monaco editor as part test item #8210. There does not appear to be a status bar or user editable settings in that case.

**Comment by aeschli** [comment] 2016-06-29 19:07
How did you 'open' a JSON file?

**Comment by chrmarti** [comment] 2016-06-29 21:45
Ack, I wasn't precise: I pasted some JSON into the editor. It reproduces when I:
- Open http://localhost:8080/monaco-editor/test/
- Switch template to 'sample JSON'
- Find/replace all tabs with four space
- Format all
-> Spaces are replaced with tabs

**Comment by aeschli** [comment] 2017-02-07 10:09
The indentation is detected based on the original content, and not reevaluated once the content changes. Changing the indentation is done through explicit commands.
Closing as the JSON formatter does the right thing. It applies the indentation strategy (tabs/spaces) it gets as argument

**Closed by aeschli** 2017-02-07 10:09 UTC
Labels: json
