### ISSUE TITLE
I can't input git commit message

### ISSUE THREAD

**Issue by chenwen97** [microsoft/vscode#114620] opened 2021-01-20 08:57 UTC
When I use source control panel, I use Chinese input method in commit information. Occasionally, I can't input in the process of input, and the input content has a black background

**Comment by chenwen97** [comment] 2021-01-20 08:58
Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)

**Comment by yume-chan** [comment] 2021-01-20 10:36
Duplicate of #112621

Please wait for next release, or try Insiders Channel (https://code.visualstudio.com/insiders/)

**Comment by yume-chan** [comment] 2021-01-20 10:37
> Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)

One issue for one problem please.

**Closed** 2021-01-20 15:47 UTC
Labels: *duplicate
