### ISSUE TITLE
User settings doesn't update after uninstalling theme

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#40802] opened 2017-12-25 06:41 UTC
Hello,

As the team doesn't response to my prev issue, also closed that and I can not open that again, so here is another one.

    VSCode Version: 1.19.0
    OS Version: Windows 10 x64

Steps to Reproduce:

    Install any theme (let's say Atom One Dark)
    Set "Atom One Dark" (using Ctrl + K + T or menu) as main theme
    VSCode added "workbench.colorTheme": "Atom One Dark" to Settings section
    Without changing theme, uninstall "Atom One Dark"
    "workbench.colorTheme": "Atom One Dark" remains in settings section

Please don't add `as-designed` tag.
You can ask user about removing the entry in setting section or leave that to user (manually removing or whatever).

As user/developer I think it's a bug.

**Comment by aeschli** [comment] 2018-01-11 10:32
duplicate of #40346. We can discuss it further there.

**Closed by aeschli** 2018-01-11 10:32 UTC
Labels: themes
