### ISSUE TITLE
Breakpoints cannot be removed

### ISSUE THREAD

**Issue by chrisgitrepo** [Microsoft/vscode#38115] opened 2017-11-11 12:33 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
EditorConfig|Edi|0.11.1
LogFileHighlighter|emi|1.2.0
dotenv|mik|1.0.0
vscode-icons|rob|7.17.0

I can only remove one breakpoint before all others become unresponsive. I can close the file, and reopen it, then remove another breakpoint, but once again the others become unresponsive before I have to close the file and repeat.

Steps to Reproduce:

1. Place several beakpoints
2. remove more than one breakpoint

Reproduces without extensions: Yes/No

**Comment by weinand** [comment] 2017-11-11 16:41
duplicate of #37880

**Closed by weinand** 2017-11-11 16:41 UTC
Labels: debug, new release
