### ISSUE TITLE
Problem updating VSCode Ubuntu 19.1

### ISSUE THREAD

**Issue by eric-naguras** [microsoft/vscode#86872] opened 2019-12-13 04:38 UTC
Get:1 http://packages.microsoft.com/repos/vscode stable InRelease [3,959 B]
Hit:2 https://deb.nodesource.com/node_12.x eoan InRelease                                                                                                                                      
Get:3 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [156 kB]                                                                                                           
Err:3 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages                                                                                                       
  File has unexpected size (156056 != 156065). Mirror sync in progress? [IP: 13.76.190.189 80]
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000

**Comment by RMacfarlane** [comment] 2019-12-13 06:26
Duplicate of https://github.com/microsoft/vscode/issues/86858

**Closed by RMacfarlane** 2019-12-13 06:26 UTC
Labels: install-update
