### ISSUE TITLE
Remote - SSH extension try to map local port zero

### ISSUE THREAD

**Issue by AlexBu** [microsoft/vscode#73440] opened 2019-05-07 23:21 UTC
Issue Type: <b>Bug</b>

1. connect to a remote host specified from ~/.ssh/config
2. the connection stopped with message "Could not establish connection to "xxx". Illegal argument: port".
With the full log in "OUTPUT" window, I can see the extension try to map remote port 42007 to local port 0, while port 0 is invalid.

SSH Resolver called for "ssh-remote+aliyun"
SSH Resolver called for host: aliyun
Setting up SSH remote "aliyun"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-117-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> New release '18.04.2 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> Welcome to Alibaba Cloud Elastic Compute Service !
> 
> mesg: ttyname failed: Inappropriate ioctl for device
> bash: cannot set terminal process group (7824): Inappropriate ioctl for device
> bash: no job control in this shell
> Found existing installation...
> mesg: ttyname failed: Inappropriate ioctl for device
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> ebaaff07-47c7-4d23-ad0e-65c0dd7d2fc6==42007==
"install" terminal command done
Received install output: ebaaff07-47c7-4d23-ad0e-65c0dd7d2fc6==42007==
Server is listening on port 42007
Spawning tunnel with: ssh  aliyun -N -L localhost:0:localhost:42007
Spawned SSH tunnel between local port 0 and remote port 42007
Waiting for ssh tunnel to be ready
Tunneling remote port 42007 to local port 0
Resolving "ssh-remote+aliyun" to "localhost:0", attempt: 1
Illegal argument: port
Tunnel(42007) stderr: Bad local forwarding specification 'localhost:0:localhost:42007

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:21:48.884Z)
OS version: Darwin x64 18.2.0

Fetching remote diagnostics for 'SSH: aliyun' failed: Illegal argument: port

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_22820290|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH: aliyun' failed: Illegal argument: port

</details>Extensions: none

**Comment by mjbvz** [comment] 2019-05-08 00:12
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/216

**Closed by mjbvz** 2019-05-08 00:12 UTC
