### ISSUE TITLE
parenthesis at the end of file when using ctrl + click to open in browser

### ISSUE THREAD

**Issue by dimdam** [microsoft/vscode#89864] opened 2020-02-02 17:51 UTC
- VSCode Version:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.0-1-MANJARO
- OS Version:
Manjaro Linux 
Steps to Reproduce:

1. ctrl + click to fire up a web browser window using for example an index.php file

Does this issue occur when all extensions are disabled?: Yes

![Screenshot_20200202_194509](https://user-images.githubusercontent.com/7516919/73612521-319e8d80-45f5-11ea-85d6-269718300dfc.png)

**Comment by gjsjohnmurray** [comment] 2020-02-02 23:18
Maybe a duplicate of #89766

**Comment by alexdima** [comment] 2020-02-03 14:42
@dimdam Where do you click the link? In the editor or in the built-in terminal? What is the exact link text?

**Comment by dimdam** [comment] 2020-02-03 17:01
@alexdima I am clicking it in the built-in terminal. i am attaching a file,you can actually see that in the underlined link it includes the right parenthesis :
![Screenshot_20200203_185900](https://user-images.githubusercontent.com/7516919/73673565-80acf700-46b7-11ea-802f-fdd37fcd744f.png)

**Closed** 2020-02-04 14:21 UTC
Labels: integrated-terminal
