### ISSUE TITLE
Column selection with CJK character

### ISSUE THREAD

**Issue by ziofat** [Microsoft/vscode#9025] opened 2016-07-10 12:46 UTC
- VSCode Version: 1.3.0
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Copy and paste the following Chinese, Japanese and English sentences to VS code.
```
人人生而自由，在尊严和权利上一律平等。
すべての人間は、生まれながらにして自由であり、かつ、尊厳と権利と について平等である。
All human beings are born free and equal in dignity and rights.
```
The sentences above are official translation of UDHR.
2. Use Shift + Alt + Click to select columns.

The behavior is:
![vscode](https://cloud.githubusercontent.com/assets/8521174/16713563/c33558c8-46ee-11e6-9c17-5a962782a5de.gif)

CJK characters are usually have double width than other characters. So visually the column of CJK characters and English characters are not same. When I use column selection to select CJK/English mixed codes this issue will affect the result.

The expected behavior is like what Sublime Text does:
![sublime](https://cloud.githubusercontent.com/assets/8521174/16713579/e4b0cce8-46ef-11e6-932e-df92c4453f4a.gif)

**Comment by kieferrm** [comment] 2016-08-02 05:19
Duplicate of #9989.

**Closed by kieferrm** 2016-08-02 05:19 UTC
