### ISSUE TITLE
Removing several commands from commandsToSkipShell has no effect

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#11257] opened 2016-08-30 22:25 UTC
Testing #11137
- VSCode Version:1.5.0
- OS Version:Windows 7

Steps to Reproduce:

1. Add default terminal.integrated.commandsToSkipShell
2. Remove workbench.action.terminal.copySelection, Ctrl+Shift+C still copies selected text
3. Remove workbench.action.terminal.toggleTerminal, Ctrl+` still toggles terminal panel
4. Remove workbench.action.terminal.kill, Ctrl+Shift+` still creates new terminal

Perhaps I don't understand how this is supposed to work.

**Comment by octref** [comment] 2016-08-31 00:12
Also tested in Win 10 and Ubuntu 16.04. Same behavior.

**Comment by gregvanl** [comment] 2016-08-31 03:46
On Mac OS, removing editor.action.toggleTabFocusMode and workbench.action.quickOpen also don't seem to have any effect.

**Comment by Tyriar** [comment] 2016-09-01 19:07
Duplicate of #11256

**Closed by Tyriar** 2016-09-01 19:07 UTC
Labels: integrated-terminal
