### ISSUE TITLE
DebugConfigurationProvider: support to return "compounds"

### ISSUE THREAD

**Issue by atian25** [microsoft/vscode#37193] opened 2017-10-31 00:30 UTC
- VSCode Version: 1.17.2
- OS Version: Mac

1. `DebugConfigurationProvider` should support `compounds`
2. allow hidden or sort order at debug configuration drop list.

![image](https://user-images.githubusercontent.com/227713/32151329-173d54f8-bcea-11e7-9e84-ee2975af8e04.png)

We only want to show user: `Egg Debug` and `Egg Debug with brk`(which is compounds)

so feature request is either provide a hidden property for `"Egg Master", "Egg Agent", "Egg Worker"`, or `compounds` should show at top. 

```js
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Debug",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run", "debug" ],
      "console": "integratedTerminal",
      "restart": true,
      "protocol": "auto",
      "port": 9999
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Master",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run", "debug", "--", "--inspect-brk" ],
      "console": "integratedTerminal",
      "restart": true,
      "protocol": "inspector",
      "port": 9229
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Egg Agent",
      "restart": true,
      "protocol": "inspector",
      "port": 5800
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Egg Worker",
      "restart": true,
      "protocol": "inspector",
      "port": 9999
    }
  ],
  "compounds": [
    {
      "name": "Egg Debug with brk",
      "configurations": [ "Egg Master", "Egg Agent", "Egg Worker" ]
    }
  ]
}
```

move from https://github.com/Microsoft/vscode/issues/34668#issuecomment-340322958

**Comment by philliphoff** [comment] 2019-03-18 16:59
@weinand The linked issue #50605 was closer to my scenario but was closed as a dupe of this one.  I would like to be able to resolve a single debug configuration from `launch.json` into multiple debug configurations.  That is, I would like the option of `DebugConfigurationProvider.resolveDebugConfiguration()` returning an array of `DebugConfiguration` objects, including ones which may not exist in launch.json (i.e. that are completely generated).

This would be useful in cases where there is an orchestration of processes that need to be performed before it is known how many and which processes are to be debugged.

**Closed** 2019-10-14 16:09 UTC
Labels: *out-of-scope, api, debug, feature-request
