### ISSUE TITLE
Allow Customization for Intellisense Icons

### ISSUE THREAD

**Issue by everdrone** [Microsoft/vscode#31383] opened 2017-07-25 11:59 UTC
Right now it doesn't seem possible to change the Intellisense icon set,
would be **GREAT** if we could.

![intellisense](https://user-images.githubusercontent.com/22671061/28570837-43540ea6-7140-11e7-9405-27adedee2acf.PNG)

**Comment by mjbvz** [comment] 2017-07-26 04:30
Duplicate of #27764

**Closed by mjbvz** 2017-07-26 04:30 UTC
Labels: duplicate
