### ISSUE TITLE
code-alpha --install-extension errors are in JSON

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6796] opened 2016-05-24 13:21 UTC
Testing #6099
```
> code-alpha --install-extension vscode-css-formatter
{ responseText: '{"$id":"1","innerException":null,"message":"The query supplied was not valid, one of the filters contained an error. The fully qualified name MUST contain a \'.\' between the publisher and extension names.","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.InvalidExtensionQueryException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"InvalidExtensionQueryException","errorCode":0,"eventId":3000}',
  status: 500,
  getResponseHeader: [Function],
  readyState: 4 }
```

Having the error as JSON is uncommon. Should be a human readable string.
If structured error messages are useful, maybe add a extra option to the command that defines the resonse format.

**Comment by joaomoreno** [comment] 2016-05-24 14:04
Duplicate of #6761

**Closed by joaomoreno** 2016-05-24 14:04 UTC
Labels: duplicate
