### ISSUE TITLE
Open file in editor directly when clicking a file from terminal

### ISSUE THREAD

**Issue by hailin84** [microsoft/vscode#144534] opened 2022-03-07 01:42 UTC
Under remote development, if you click a file from terminal(eg, after ls command)，Vscode will try to open a file named the one you just clicked. Actually, the absolute path of the file is already known, So why not open it directly in the editor? 

I think that would be very useful. Please consider it.

**Comment by shwao** [comment] 2022-04-13 13:53
Are you talking about this new behavior? 

![Screenshot 2022-04-13 at 15 48 44](https://user-images.githubusercontent.com/63549997/163195403-4607abe2-92e1-408e-a716-2d4d921b5d76.png)

I CMD + Clicked on the underlined path `src/shared/store/media/reducer.test.ts` and it used to open the file directly since its obvious which file it is. But since a few days or weeks (idk exactly) it opens this menu for me to select the file from a list of files with similar paths.

Its pretty annoying and id really like the old behavior back.

If you are talking about something different let me know so i can open a separate issue.

**Comment by hailin84** [comment] 2022-06-02 09:21
> Are you talking about this new behavior?
> 
> ![Screenshot 2022-04-13 at 15 48 44](https://user-images.githubusercontent.com/63549997/163195403-4607abe2-92e1-408e-a716-2d4d921b5d76.png)
> 
> I CMD + Clicked on the underlined path `src/shared/store/media/reducer.test.ts` and it used to open the file directly since its obvious which file it is. But since a few days or weeks (idk exactly) it opens this menu for me to select the file from a list of files with similar paths.
> 
> Its pretty annoying and id really like the old behavior back.
> 
> If you are talking about something different let me know so i can open a separate issue.

Yes, it is. I prefer old behavior too.

**Comment by Tyriar** [comment] 2022-06-02 14:29
@hailin84 what is the working directory of the terminal you're in? The current expected behavior is to open the file directly if you cwd is the folder containing `src`, otherwise a workspace search will happen.

**Comment by shwao** [comment] 2022-06-03 07:40
I, obviously, don't know for him but in my example the working directory of the terminal is the folder containing `src`.

**Comment by Tyriar** [comment] 2022-06-03 10:48
@shwao hmm ok, I'll try investigate this next month.

**Comment by hailin84** [comment] 2022-06-08 09:41
> @hailin84 what is the working directory of the terminal you're in? The current expected behavior is to open the file directly if you cwd is the folder containing `src`, otherwise a workspace search will happen.

For me, mostly, it's project home folder(src's parent folder).

**Comment by Tyriar** [comment] 2022-06-09 17:05
Can reproduce on Windows:

![image](https://user-images.githubusercontent.com/2193314/172904246-6bed78e6-5c44-4ae4-809a-23ee4605da70.png)

**Comment by alexr00** [comment] 2022-06-30 12:57
I can still reproduce this in the latest insiders. I ctrl+clicked on "package.json"

![image](https://user-images.githubusercontent.com/38270282/176682502-aeae9914-40d4-47f6-9b08-4c854efc9840.png)

**Comment by Tyriar** [comment] 2022-06-30 14:48
I can repro but only in a Windows remote (Windows -> Window), not a WSL remote (Windows -> Linux).

**Comment by Tyriar** [comment] 2022-06-30 15:00
With file structure:

```
package.json
src/package.json
src2/package.json
```

Clicking a `src/package.json` link:

![image](https://user-images.githubusercontent.com/2193314/176709795-b803f24a-8f36-4a02-8b85-121201a000d2.png)

The expectation here is to open `src/package.json` immediately without the search because while `src2/package.json` matches a search it does not match the folder prefix.

**Comment by Tyriar** [comment] 2022-06-30 15:12
Moving to July as it's only for Windows remotes. Also spotted this one: https://github.com/microsoft/vscode/issues/153832

**Comment by alexr00** [comment] 2022-07-28 12:04
I can still repro the issue from https://github.com/microsoft/vscode/issues/144534#issuecomment-1171187717.
Windows -> Windows remote
Version: 1.70.0-insider (system setup)
Commit: b4d5b4ed69af953901051b1f049851b9dca3563e
Using my cloned version of the tree-view extension sample as the open folder and running `ls` in the terminal. 
Tried with shell integration on and off.

**Comment by Tyriar** [comment] 2022-08-11 13:42
@alexr00 I can't reproduce this:

![Recording 2022-08-11 at 06 37 24](https://user-images.githubusercontent.com/2193314/184146206-de94a779-7b68-475f-ba3f-525578d0a052.gif)

I saw this related minor issue https://github.com/microsoft/vscode/issues/157903, but I think this issue is fixed.

**Closed by Tyriar** 2022-08-11 13:42 UTC
Labels: bug, verification-found, terminal-links

**Comment by alexr00** [comment] 2022-08-11 14:02
I'm still seeing it with the insiders from today.

**Comment by Tyriar** [comment] 2022-08-11 15:37
@alexr00 that would be the reason then, there could be a few reasons for that. There may be a warning in your console, or are you using powershell 5?

**Comment by alexr00** [comment] 2022-08-12 08:30
My powershell version is 7.2.5.
I have this error in the pty log:
```
[2022-08-11 16:07:02.456] [ptyhost] [warning] Shell integration cannot be enabled for executable "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" and args undefined
```

**Comment by rzhao271** [comment] 2022-08-25 21:59
Verified. Here's the Powershell profile I have:
```json
"terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        }
```
Powershell 7 for me is at `C:\Program Files\PowerShell\7\pwsh.exe`.
Windows Powershell is at `%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe`.
I wonder whether the profile is picking up Windows Powershell by accident?
