### ISSUE TITLE
Highlight Updated git files and folders on sidebar

### ISSUE THREAD

**Issue by Petermuturi** [Microsoft/vscode#36465] opened 2017-10-18 06:49 UTC
I believe this is a very useful tool for visualization of tracking the files one is updating or adding on a huge application, unlike all files and folders having the same shade of color.

**Comment by fredrikaverpil** [comment] 2017-10-18 09:36
Duplicate of #178?

**Comment by jrieken** [comment] 2017-10-18 09:47
Yeah, closing

**Closed by jrieken** 2017-10-18 09:47 UTC
Labels: workbench
