### ISSUE TITLE
Incorrect highlighting in TypeScript

### ISSUE THREAD

**Issue by jiripospisil** [Microsoft/vscode#35989] opened 2017-10-10 16:37 UTC
- VSCode Version: 1.17.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create a `.ts` file with the following:

```typescript
do {

} while(foo++ < 20);

function bar() {

}
```
2. Notice that the `function` keyword is not highlighted properly. It seems to be caused by the postfix unary operator `++`.

![image](https://user-images.githubusercontent.com/20820/31398537-928c0452-ade9-11e7-87c8-6b7ab27ff1bc.png)

![image](https://user-images.githubusercontent.com/20820/31398546-97d69ada-ade9-11e7-80c9-c91d72aac4c9.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-10-10 16:39
Duplicate of #35768

Should already be fixed in today's insiders build

**Closed by mjbvz** 2017-10-10 16:39 UTC
Labels: duplicate, grammar, typescript
