### ISSUE TITLE
Quickfix doesn't work when clicked

### ISSUE THREAD

**Issue by ninankara** [microsoft/vscode#76947] opened 2019-07-09 08:16 UTC
There is quick fix mark on my code. 

Usually when I clicked one of the solution, such as import, the import code line is appeared. 
But recently I got this problem. the quick fix is not working. The solution doesn't appear anywhere.

![Screenshot](https://i.imgur.com/Q5yefUj.png)

as screenshot above, I tried to click import, but the import library for List didn't appear

**Comment by Nutellaeis** [comment] 2019-07-09 11:15
I have the same Problem. I tried a complete re-install and wipe of AppData. Still not working.

**Comment by mjbvz** [comment] 2019-07-09 17:23
Duplicate of #76851

**Closed by mjbvz** 2019-07-09 17:23 UTC
Labels: javascript
