### ISSUE TITLE
bad formatting in typescript errors popup

### ISSUE THREAD

**Issue by luisrudge** [Microsoft/vscode#16115] opened 2016-11-27 12:01 UTC
- VSCode Version: 1.7.2
- OS Version: win10

![image](https://cloud.githubusercontent.com/assets/941075/20648235/64ce9c06-b488-11e6-9dd3-28227439007d.png)

**Comment by waderyan** [comment] 2016-11-28 20:04
Duplicate of https://github.com/Microsoft/TypeScript/issues/11335

**Closed by waderyan** 2016-11-28 20:04 UTC
