### ISSUE TITLE
[Extension] Support custom context menu

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#5322] opened 2016-04-15 10:00 UTC
Is there a plan to support custom context menu? like:
https://atom.io/docs/api/v1.7.1/ContextMenuManager
or
http://wiki.eclipse.org/Menu_Contributions#menu

Thanks. I am looking forward to that.

**Comment by egamma** [comment] 2016-04-15 10:51
Duplicate of #3192

**Closed by egamma** 2016-04-15 10:51 UTC
