### ISSUE TITLE
Is it a good idea to allow sync user settings & extensions across computers?

### ISSUE THREAD

**Issue by mysterytony** [Microsoft/vscode#39842] opened 2017-12-07 01:51 UTC
As tittle, would it be nice to allow export some sort of manifest file that contains user settings and extensions so it can be imported by another vscode to automatically adjust all settings and install the extensions?

**Comment by mjbvz** [comment] 2017-12-07 02:08
duplicate of #2743

**Closed by mjbvz** 2017-12-07 02:08 UTC
Labels: extensions
