### ISSUE TITLE
Unexpected token in JSON error for any file opened

### ISSUE THREAD

**Issue by cantiero** [microsoft/vscode#102601] opened 2020-07-15 14:35 UTC
System Info:
MacOSX 10.14.6

CPUs | Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 1, 2, 2
Memory (System) | 8.00GB (0.30GB free)
Process Argv | --disable-extensions
Screen Reader | no
VM | 0%

VSCode: 
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Open VSCode
2. Try o open ANY fiile
3. Only for a particular project of mine, no file will be opened and an error message appears in the bottom right corner: `Unable to open '[file name]': Unexpected token t in JSON at position 4694.`
4. The "Unexpected token t in JSON at position 4694" part is exactly the same for all files I try to open.

Opening VSCode with the --verbose flag, will create this log when trying to open the files:

[2856:0715/104628.039337:INFO:CONSOLE(1670)] "%cTRACE color: #888 telemetry/workbenchActionExecuted [object Object]", source: file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[2856:0715/104628.039782:INFO:CONSOLE(1670)] "%cTRACE color: #888 telemetry/editorClosed [object Object]", source: file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[2856:0715/104628.039895:INFO:CONSOLE(1670)] "%cTRACE color: #888 telemetry/editorOpened [object Object]", source: file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[2856:0715/104628.044227:INFO:CONSOLE(2947)] "Unable to open 'buildspec.yml': Unexpected token t in JSON at position 4694.", source: file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (2947)
[2856:0715/104628.061719:INFO:CONSOLE(1670)] "%cTRACE color: #888 telemetry/editorClosed [object Object]", source: file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)

Does this issue occur when all extensions are disabled?: Yes

Complete output log:
[log.txt](https://github.com/microsoft/vscode/files/4925938/log.txt)

I checked if this could have something to do with some local vscode configuration json file because:
1. It only happend in one project folder.
2. Produces exactly the same error for all files in this folder.

settings.json is the only file in .vscode folder. I removed all its contents and nothing changes.

This is the complete list of installed extensions:
Cronos87.yaml-symbols
QassimFarid.ejs-language-support
SirTori.indenticator
alefragnani.numbered-bookmarks
christian-kohler.path-intellisense
ckolkman.vscode-postgres
clinyong.vscode-css-modules
cssho.vscode-svgviewer
dbaeumer.vscode-eslint
dbalage.vscode-stylesheet-formatter
donjayamanne.githistory
eamodio.gitlens
firefox-devtools.vscode-firefox-debug
howardzuo.vscode-favorites
humao.rest-client
iampeterbanjo.elixirlinter
JamesBirtles.svelte-vscode
kungfoowiz.cssSuggestions
luwenjiechn.nunjucks-vscode-snippets
marclipovsky.string-manipulation
mjmcloug.vscode-elixir
mohd-akram.vscode-html-format
mrmlnc.vscode-postcss-sorting
msjsdiag.debugger-for-chrome
Prisma.vscode-graphql
redhat.vscode-yaml
ronnidc.nunjucks
ruiquelhas.vscode-lowercase
ryanlaws.toggle-case
sainoba.px-to-rem
Shan.code-settings-sync
sibiraj-s.vscode-scss-formatter
sleistner.vscode-fileutils
tomoki1207.vscode-input-sequence
tuxtina.json2yaml
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
waderyan.gitblame
xabikos.ReactSnippets
zhuangtongfa.material-theme

**Comment by aeschli** [comment] 2020-07-16 08:00
Bottom right corner. Is it a error notification? Can you add a screenshot?
It does also show with extensions disabled?
Anything interesting in the log files? (Command `Developer: Show Logs...`. `Window` and `Extension Host`)

**Comment by cantiero** [comment] 2020-07-16 21:53
Hi! Yes, it's an error notification. Here you go:
![image](https://user-images.githubusercontent.com/22422447/87726411-55b1ed80-c795-11ea-9c14-d7d61fe5adcb.png)

Yes, disabling all extensions still shows the same error.

The logs from verbose mode with extensions disabled are these: [log.txt](https://github.com/microsoft/vscode/files/4934368/log.txt).

Not opening in verbose mode`Show Logs.... Window:` is clear and `Show Logs.... Extension Host` has this:
```
[2020-07-16 18:44:23.465] [exthost] [info] extension host started
[2020-07-16 18:44:23.768] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:json"}
[2020-07-16 18:44:23.769] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2020-07-16 18:44:23.777] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:json"}
[2020-07-16 18:44:23.777] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/extension-editing/dist/extension
[2020-07-16 18:44:23.793] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:json"}
[2020-07-16 18:44:23.793] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
[2020-07-16 18:44:23.964] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onLanguage:json"}
[2020-07-16 18:44:23.964] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2020-07-16 18:44:24.906] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"onLanguage:json"}
[2020-07-16 18:44:24.907] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/npm/dist/npmMain
[2020-07-16 18:44:24.940] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:typescript"}
[2020-07-16 18:44:24.940] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension
[2020-07-16 18:44:25.066] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-07-16 18:44:25.066] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2020-07-16 18:44:25.071] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-07-16 18:44:25.071] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/dist/extension
[2020-07-16 18:44:25.103] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-07-16 18:44:25.103] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2020-07-16 18:44:25.266] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":true,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"*"}
[2020-07-16 18:44:25.266] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js
[2020-07-16 18:44:25.287] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-07-16 18:44:25.287] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-07-16 18:44:25.294] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":true,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"*"}
[2020-07-16 18:44:25.294] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-07-16 18:44:25.427] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-07-16 18:44:25.428] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/search-result/dist/extension.js
[2020-07-16 18:44:26.237] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-07-16 18:44:26.237] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/equus/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js
[2020-07-16 18:44:26.485] [exthost] [info] eager extensions activated```

**Comment by jappareti** [comment] 2020-07-21 17:33
I'm having this same issue. I disabled all extensions and deleted the the `.vscode` folder for the project that I'm having issues with. I see the same log in `--verbose` mode for the `workbench.desktop.main.js` file:

```
[23728:0721/102633.398036:INFO:CONSOLE(1670)] "%cTRACE color: #888 telemetry/workbenchActionExecuted [object Object]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[23728:0721/102633.398373:INFO:CONSOLE(1670)] "%cTRACE color: #888 telemetry/editorOpened [object Object]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[23728:0721/102633.400615:INFO:CONSOLE(2947)] "Unable to open 'styles.css': Unexpected token , in JSON at position 4639.", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (2947)
```

<img width="561" alt="Screen Shot 2020-07-21 at 10 32 57 AM" src="https://user-images.githubusercontent.com/1170323/88087324-91560a00-cb3d-11ea-84db-5e70dae55897.PNG">


```
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

**Comment by jappareti** [comment] 2020-07-21 17:41
Update: I was able to resolve the issue by uninstalling / reinstalling VS Code.

**Comment by cantiero** [comment] 2020-07-22 12:22
The workaround I found is to open VSCode at the folder immediatelly above the one presenting this issue. It works, but it results in a suboptimal experience, specially in searching and managing git.

@aeschli this issue is marked as "needs more info". Is there anything else I can do to provide better context? Please, let me know. Thanks!

**Comment by aeschli** [comment] 2020-08-11 12:22
duplicate of https://github.com/microsoft/vscode/issues/102251.

Can you try if https://github.com/microsoft/vscode/issues/102251#issuecomment-671912942 works as work around?

**Closed by aeschli** 2020-08-11 12:22 UTC
Labels: needs more info
