### ISSUE TITLE
Code crashes / slows down after a period of time

### ISSUE THREAD

**Issue by gushie** [Microsoft/vscode#2024] opened 2016-01-14 15:30 UTC
After using VS Code for a while, it gets slower and slower. I notice it particularly when it attempts to auto-complete. 

It will then sometimes crash. It may crash whilst I'm using it. It may crash when I haven't used it for sometime but using another window. It may crash if I leave the PC overnight. It may crash if I only used it for a very short amount of time and the slowdown above hadn't occurred.

Looking at the Windows Task Manager does not show it using any more memory at this time (it peaks at around 38MB and never goes above 1% CPU although is usually at 0%). The PC has plenty of resources/memory free.

Unfortunately I can't find a pattern. It is worse now though than it was when it first started occurring several releases ago.

I just get a dialog "Visual Studio has crashed. We are sorry for the inconvenience! Please restart Visual Studio Code." and no other indication as to the cause.

Code v0.10.6, issue has occurred since around v0.3
Windows 8.1, i7-4770 with 16GB RAM. SSD disk.
Git repository contains over 39,000 files across folders at various levels deep. These are mostly HP BASIC .BAS (OpenVMS files which we maintain on Windows) plus bespoke 4GL files.
I don't use any of the git functionality within Code, I do commits etc externally.
I use Ctrl+E frequently to find/open files. 
Shift+Ctrl+B runs a windows .bat file to transfer and compile the code
settings.json:  "editor.insertSpaces": true, "files.trimTrailingWhitespace": true

**Comment by Tyriar** [comment] 2016-01-14 23:49
Probably a duplicate of https://github.com/Microsoft/vscode/issues/508

**Comment by Elusive138** [comment] 2016-01-15 06:41
> Looking at the Windows Task Manager does not show it using any more memory at this time (it peaks at around 38MB

Add the "Commit Size" column and check that. The default memory column is only private working set.

**Comment by bpasero** [comment] 2016-01-15 11:25
Yeah, #508

**Closed by bpasero** 2016-01-15 11:25 UTC

**Comment by gushie** [comment] 2016-01-15 12:07
I see this is now marked as a duplicate, but just to follow up from @Elusive138, I've now added the commit size to the task manager and I see it does increase over time (regardless of whether I'm using Code or not).
It's currently at 300MB and rising. Code has only had a little use this morning.
