### ISSUE TITLE
Typescript experimentalDecorators compiler flag not honored in VSCode

### ISSUE THREAD

**Issue by arciisine** [Microsoft/vscode#7654] opened 2016-06-14 11:30 UTC
- VSCode Version: 1.3.0-insiders
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Configure typescript to use decorators
2. Create a simple decorator usage
3. See VSCode indicate that experimentalDecorators are not enabled

My `tsconfig.json` is as follows:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators" : true
  },
  "files": [
    "test.ts"
  ]
}
```

And `test.ts` is
```typescript
function Verbose() {
  return (t:any) => t;
}

@Verbose()
export class Test {}
```

Typescript compiles the files fine, without error, but vs code seems to think that the experimentalDecorators flag is not enabled, and marks every usage site as a warning.

![image](https://cloud.githubusercontent.com/assets/1264175/16041112/5b0c2a56-31f9-11e6-8f13-2a8c033b41ec.png)

**Comment by dbaeumer** [comment] 2016-06-15 06:56
Moving to TS. TS team please note that the current insider build is still using 1.8.10. So the behavior should be the same with 1.2.x

**Comment by dbaeumer** [comment] 2016-06-15 06:57
This issue was moved to Microsoft/TypeScript#9178

**Closed by dbaeumer** 2016-06-15 06:57 UTC

**Comment by akanieski** [comment] 2016-07-24 22:52
I ran into this when I open a root folder that contains TS project for client and TS project for server (File-> Open Folder .. `/root`). The root has no tsconfig file. VSCode does not respect the tsconfig in each respective project folder (`/root/server/tsconfig.json` and `/root/client/tsconfig.json`). It is expecting a tsconfig to be in the root of the folder opened in VSCode (`/root/tsconfig.json`).

When I open another instance of VSCode and open the `/root/client` or `/root/server` folder the decorator warning goes away, as it should.

Is this by design? I'm not sure i'd expect it to find the nearest tsconfig.json in local folder or above.

I hope I'm making sense :-P

**Comment by dbaeumer** [comment] 2016-08-04 11:02
This is by design. When you open a TS file it takes the nearest tsconfig.json file relative to the TS file you opened.

**Comment by akanieski** [comment] 2016-08-04 11:12
What if I have a project where there will be shared code between front and backend?

Andrew Kanieski
andrew.legacy@gmail.com
Mobile 1-862-266-4878




On Thu, Aug 4, 2016 at 7:03 AM -0400, "Dirk Bäumer" <notifications@github.com> wrote:












This is by design. When you open a TS file it takes the nearest tsconfig.json file relative to the TS file you opened.

**Comment by dbaeumer** [comment] 2016-08-04 13:05
Then you can either have three folders share, client, server or if you have npm have share as an npm module and depend on it from client and server.

**Comment by akanieski** [comment] 2016-08-04 13:09
Understood. I was staying away from seperate modules since project still in storming/forming stage. 
If I went with the 3 folders approach where would I put the tsconfig? In the root? Or one for each folder? If one in each folder that's when I found this issue. (Still need to try from another machine)



On Thu, Aug 4, 2016 at 9:06 AM -0400, "Dirk Bäumer" <notifications@github.com> wrote:












Then you can either have three folders share, client, server or if you have npm have share as an npm module and depend on it from client and server.
