### ISSUE TITLE
Unable to copy deleted text in compare editor when viewing in inline mode

### ISSUE THREAD

**Issue by nvmkpk** [Microsoft/vscode#33161] opened 2017-08-25 15:49 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.3.1
ng-template|Ang|0.1.4
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
file-icons|fil|1.0.5
rest-client|hum|0.15.2
debugger-for-phantomjs|ira|0.1.1
Angular1|joh|0.2.0
theme-dark-plus-contrast|k3a|0.1.101
csharp|ms-|1.12.1
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.1.8
debugger-for-edge|msj|0.4.1
python|tht|0.2.3

---

Steps to Reproduce:

1. Open a git repository
2. Delete some lines in a non-empty file
3. Go to source control sidebar
4. Click on the modified file
5. Click 'More' button on the top right of the editor window
6. Click 'Switch to Inline View'
7. Try moving cursor into the red lines using keyboard or mouse

Reproduces without extensions: Yes

**Comment by kevintbrown** [comment] 2018-04-12 19:36
Seeing the same issue on VisualStudio.com which also uses the Monaco editor.

https://developercommunity.visualstudio.com/content/problem/230720/unable-to-select-text-from-removed-lines-in-pr-inl.html?childToView=233033#comment-233033

**Comment by alexandrudima** [comment] 2018-09-22 12:47
Duplicate of #8226

**Closed by alexandrudima** 2018-09-22 12:47 UTC
Labels: diff-editor, feature-request
