### ISSUE TITLE
Don't work live preview in split-editor

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#17592] opened 2016-12-20 07:38 UTC
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/3082812/21341374/45fe62f8-c69d-11e6-85ba-c91e5e5964e1.png)

- OS Version: win7 pro

Steps to Reproduce:

1. Open HTML file;
2. Press `Ctrl+Shift+V`;
3. Press `Ctrl+\`;
4. Close preview in 1st panel, what would happen as in the screenshot;
![image](https://cloud.githubusercontent.com/assets/3082812/21341512/eab9b658-c69d-11e6-8200-571b5b50db5a.png)

5. Change HTML file in 1st panel;
6. Preview is not updated.

PS:
1. If I don't used splitted code editor, then this scenario is work;
2. And this scenario working on a Linux for embed in html scripts and styles: https://github.com/Microsoft/vscode/issues/16081

**Comment by egamma** [comment] 2016-12-20 09:22
The command `CTRL+SHIFT+V` is bound to the command `markdown.showPreview` it appears that it happens to also show the preview for an .html file, but the preview is not updated in the case of a .html file.

//FYI @aeschli support for previewing html should be contributed by the html extension. See also #17595

**Comment by vorov2** [comment] 2016-12-20 14:01
Could be nice if different preview modes would be triggered by the same shortcut and if a preview is not available for a particular mode display an appropriate message in a preview pane.

**Comment by aeschli** [comment] 2017-01-10 03:02
CTRL+SHIFT+V is implemented by markdown and tries to open any document type in preview, regardless of markdown or not.
IMO that needs to be fixed and the preview story needs some more thoughts. I guess if html would do the same as markdown, we'd end up with two preview actions. @jrieken your thoughts?

**Comment by jrieken** [comment] 2017-01-10 09:12
I remember that we allow for all kinds of files to be previewed, however it seems like the markdown extension doesn't listen to changes for none MD-files and consequently the derived-preview resource isn't updated

**Comment by IgorNovozhilov** [comment] 2017-01-10 17:22
@jrieken, now previews of html files working on `Linux` and doesn't working on `Windows`

here: https://github.com/Microsoft/vscode/issues/16081, I described that not only works for linked files

ver:
![image](https://cloud.githubusercontent.com/assets/3082812/21816642/e7f5a4f6-d771-11e6-9a2d-70bf0a57f814.png)

**Comment by mjbvz** [comment] 2017-03-23 21:07
Closing this as part of #17595

The markdown preview does not update preview for non-markdown files by design. Once we have a preview story for html, I believe that we should disable the markdown preview for non markdown files

**Closed by mjbvz** 2017-03-23 21:07 UTC
Labels: html, markdown
