### ISSUE TITLE
typescript serivce crashed more than 5 times

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#131034] opened 2021-08-17 19:46 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.59.0
Commit: 379476f
Date: 2021-08-04T23:13:20.182Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.4.0-80-generic

Steps to Reproduce:

1. Start VS Code
2. Get Error

This seems similar to https://github.com/microsoft/vscode/issues/130573, but I was told to re-file it separately here.  Even with all extensions disabled, and using the latest (downloaded this morning) Insiders VS Code ... I still get the error.

Happy to provide any further details.

**Comment by mjbvz** [comment] 2021-08-17 20:13
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by machineghost** [comment] 2021-08-17 20:48
I did all that, but all I see at the start of my Typescript output is this (repeated a lot):

[Info  - 20:46:21.411] Starting TS Server 
[Info  - 20:46:21.411] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 20:46:21.414] <syntax> Forking...
[Info  - 20:46:21.438] <syntax> Starting...
[Info  - 20:46:21.440] <semantic> Forking...
[Info  - 20:46:21.458] <semantic> Starting...
[Info  - 20:46:33.839] TSServer exited. Signal: SIGPIPE

I don't see anything about a log file.  I *did* add:

   {
      "typescript.tsserver.log": "verbose", // <===== this line
     "compilerOptions": {
       "jsx": "react",
       "baseUrl": ".",

and I restarted ... but no error log message

**Comment by u9520107** [comment] 2021-08-18 00:58
I also had similar issues. In the end I enabled the "disable automatic type acquisition" option in settings. It's been fairly stable after that.
Without enabling this, sometimes vscode would continue to eat up more and more ram on my macOS 10.15 until the system becomes unstable and reboots. It's been working fine for the past 2 days since I enabled this as well.

**Comment by mjbvz** [comment] 2021-08-18 23:15
@machineghost It looks like there's something wrong with your install/machine where the server never even starts (`SIGPIPE`)

What specific linux flavor and VS Code install version are you using?

**Comment by machineghost** [comment] 2021-08-19 19:46
My VS Code details are in the original post (Version: 1.59.0), and I'm running Linux Mint 20.2.

**Comment by mjbvz** [comment] 2021-10-04 21:07
I'm not sure how to investigate this further. `SIGPIPE` suggests there is something wrong with communication between the TypeScript server and VS Code. However we don't see many other reports of this (only #95362 and there's not a lot of evidence of many of these crashes in telemetry) It could be a  permissions issue with a specific type of installation but there's just not enough context to know anything for sure

Closing as not-reproducible given the low number of hits we're seeing

**Closed by mjbvz** 2021-10-04 21:07 UTC
Labels: needs more info
