### ISSUE TITLE
Minimise doesn't work

### ISSUE THREAD

**Issue by James-Livesey** [Microsoft/vscode#65492] opened 2018-12-20 14:11 UTC
Issue Type: <b>Bug</b>

Minimising the window doesn't work when run in Crostini on ChromeOS.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.14.67-07156-gc116f2c8c400

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|4.84GB (2.97GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1

</details>

**Comment by bpasero** [comment] 2018-12-21 11:57
@James-Livesey are you using standard settings with the custom title?

**Comment by James-Livesey** [comment] 2018-12-21 12:04
Yeah, both maximise and close work but not minimise.

**Comment by sbatten** [comment] 2018-12-21 15:18
@James-Livesey please try changing your `window.titleBarStyle` to `native`

**Comment by James-Livesey** [comment] 2018-12-22 11:08
It does minimise in `native` as expected, just not in `custom`.

**Comment by DavidFrahm** [comment] 2019-01-16 15:30
Just noting that with the recent change in default settings to `window.titleBarStyle:custom`, this issue is now impacting all new Chrome OS installs.

**Comment by DavidFrahm** [comment] 2019-01-16 15:32
This issue is duplicate of #64165

**Comment by sbatten** [comment] 2019-01-16 18:47
Thanks @DavidFrahm

**Closed by sbatten** 2019-01-16 18:47 UTC
