### ISSUE TITLE
Define global settings which apply to all profiles

### ISSUE THREAD

**Issue by RoyalFoxy** [microsoft/vscode#174825] opened 2023-02-20 09:52 UTC
I would like if there was a way to define global settings that apply to all profiles unless overwritten. I thought of two way this could be achieved.

1. You could make it that the user settings aka the default settings.json is applied to all profiles and all profiles inherit the contents of the the default profiles settings unless overwritten.
2. You could create a third settings.json added to the default settings.json and the profile specific ones which inherits settings that are applied to all profiles aswell as the default profile.

I think this could save some headaches of copy pasting settings when changing them e.g. when defining default formatters aka prettier for java- and typescript when you have a vue and a react profile and you would have to copy the setting sinbetween or when customizing your theme of choice to suit your needs more.

This would also allow to have a more compact profile settings.json as from my experience so far there are only a few settings I change from the default if any at all and mostly just have different extensions installed for those profiles.

**Comment by anthonyvdotbe** [comment] 2023-02-21 12:34
This is a duplicate of #156144, isn't it?

**Closed** 2023-02-21 19:53 UTC

**Comment by sandy081** [comment] 2023-03-29 10:41
/duplicate

https://github.com/microsoft/vscode/issues/176813
