### ISSUE TITLE
command 'emmet.expandAbbreviation' not found

### ISSUE THREAD

**Issue by edDimensi** [Microsoft/vscode#37557] opened 2017-11-02 22:17 UTC
- VSCode Version: 1.17.2
- OS Version: Manjaro kde 17.0.6 fresh install

Steps to Reproduce:

1. Start code
2. Try use emmet.
![screenshot_20171103_011447](https://user-images.githubusercontent.com/11390039/32352961-76ff9a7a-c034-11e7-8f40-f87be2639f4c.png)

![screenshot_20171103_011605](https://user-images.githubusercontent.com/11390039/32352992-9d174172-c034-11e7-95bd-4f07f57dff6a.png)

![screenshot_20171103_011642](https://user-images.githubusercontent.com/11390039/32353013-b347f5a4-c034-11e7-9f55-50a815428c68.png)

If i do some spaces in document, emmet start working.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment] 2017-11-02 23:39
Thanks for reporting @edDimensi 

This is a duplicate of #36267

You can find the fix in the Insiders build which you can get from https://code.visualstudio.com/insiders
Or you can wait for release of VS Code 1.18 next week

**Closed by ramya-rao-a** 2017-11-02 23:39 UTC
Labels: emmet
