### ISSUE TITLE
Long branch name shows wrong icon

### ISSUE THREAD

**Issue by jpauley-veem** [microsoft/vscode#86491] opened 2019-12-06 19:44 UTC
Issue Type: <b>Bug</b>

On the source control tab, I have Source Control: GIt. Under Source Control Providers, I have 4 providers. For one of the providers, I have a long branch name. Instead of seeing the 'synchronize changes' icon, I see the '...' icon. When I click on this icon, the '...' rotate like the proper icon should.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
vscode-quick-select|dba|0.2.8
flow-for-vscode|flo|1.5.0
vscode-flow-ide|gca|1.2.0
vscode-pull-request-github|Git|0.13.0
debugger-for-chrome|msj|4.12.2

</details>

![Screen Shot 2019-12-06 at 2 44 07 PM](https://user-images.githubusercontent.com/42551841/70351421-e5261400-1836-11ea-9564-bd3bfcf4f6ff.png)

**Comment by IllusionMH** [comment] 2019-12-06 21:43
/duplicate of #85685

Should be already in Insiders build https://code.visualstudio.com/insiders/ and should be in Stable next week

**Closed** 2019-12-06 21:43 UTC
Labels: *duplicate
