### ISSUE TITLE
Organize Imports removes imports referenced with ES2015 object shorthand syntax

### ISSUE THREAD

**Issue by MarcelMichau** [Microsoft/vscode#49172] opened 2018-05-04 04:45 UTC
Issue Type: <b>Bug</b>

// Before Organize Imports

```javascript
import { someFunction, someOtherFunction } from '../somewhere';

const someObject = {
   someFunction,
   someAlias: someOtherFunction
};
```

// After Organize Imports:

```javascript
import { someOtherFunction } from '../somewhere'; // someFunction is removed

const someObject = {
   someFunction,
   someAlias: someOtherFunction
};
```

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (5.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
react-pure-to-class-vscode|ang|1.1.4
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.1.1
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.47
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.4
carbon-now-sh|eri|1.1.1
prettier-vscode|esb|1.3.1
auto-rename-tag|for|0.0.15
css2react|got|0.0.6
vscode-styled-components|jpo|0.0.18
mssql|ms-|1.3.1
csharp|ms-|1.14.0
vscode-icons|rob|7.23.0
code-spell-checker|str|1.6.10
vscode-import-cost|wix|2.6.2
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by evan-scott-zocdoc** [comment] 2018-05-04 06:02
I'm also seeing it remove ones like:

```js
import React from 'react';
```

**Comment by mjbvz** [comment] 2018-05-04 17:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/23308

Should already be fixed in vscode insiders

**Closed by mjbvz** 2018-05-04 17:48 UTC
Labels: new release
