### ISSUE TITLE
Formatting HTML inserts newline before end-style tag

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode#159508] opened 2022-08-29 23:06 UTC
Type: <b>Bug</b>

Press Shift-Option-F (on Mac) to format an HTML file containing this:

```html
<!doctype html>
<html>
    <head>
        <style>
            p {
                color: black
            }
        </style>
    </head>
</html>
```

I get this:

```html
<!doctype html>
<html>
    <head>
        <style>
            p {
                color: black
            }

        </style>
    </head>
</html>
```

Happens despite using the setting `"html.format.extraLiners": ""`.

My full settings:

```json
{
    "editor.codeLens": false,
    "editor.folding": false,
    "editor.quickSuggestions": {
        "comments": "off",
        "other": "off",
        "strings": "off"
    },
    "explorer.openEditors.visible": 0,
    "files.insertFinalNewline": true,
    "git.autofetch": true,
    "go.editorContextMenuCommands": {
        "testAtCursor": true,
        "testFile": true,
        "testPackage": true
    },
    "go.enableCodeLens": {
        "references": false,
        "runtest": false
    },
    "go.formatTool": "goimports",
    "go.toolsManagement.autoUpdate": true,
    "gopls": {
        "ui.semanticTokens": true
    },
    "html.format.extraLiners": "",
    "html.format.indentHandlebars": true,
    "html.format.indentInnerHtml": true,
    "html.format.wrapLineLength": 0,
    "workbench.editor.untitled.hint": "hidden",
    "workbench.startupEditor": "newUntitledFile"
}
```

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|. --crash-reporter-id eb1623a8-9d11-4cf3-a88f-63713e940c9e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.9.0
githistory|don|0.6.19
go|gol|0.35.2
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.40
fish-vscode|sky|0.2.1
gitblame|wad|9.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by aeschli** [comment] 2022-08-30 08:43
duplicate of https://github.com/microsoft/vscode/issues/156639

**Closed by aeschli** 2022-08-30 08:43 UTC
