### ISSUE TITLE
Terminal all weird when running gulp task

### ISSUE THREAD

**Issue by rafaelramalho19** [Microsoft/vscode#26086] opened 2017-05-05 22:07 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|vscode-caniuse|akamud|0.5.3|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-instant-markdown|dbankier|1.1.0|
|vscode-hapijs-snippets|deerawan|2.0.0|
|githistory|donjayamanne|0.2.0|
|pgsql|doublefint|0.0.7|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.1.2|
|LogFileHighlighter|emilast|1.1.1|
|file-icons|file-icons|1.0.3|
|sass-lint|glen-84|0.0.4|
|vue-snippets|hollowtree|0.1.1|
|webcomponent-generator|jeremyrajan|1.0.1|
|svg|jock|0.0.6|
|docthis|joelday|0.4.4|
|svgpreview|kisstkondoros|0.2.0|
|quicktask|lkytal|2.6.1|
|code-beautifier|michelemelluso|1.7.2|
|vscode-csscomb|mrmlnc|4.0.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|chai-snippets|nwhatt|0.1.0|
|vetur|octref|0.6.5|
|vscode-icons|robertohuertasm|7.6.0|
|sass-indented|robinbentley|1.4.1|
|stylelint|shinnn|0.24.0|
|svg-snippets|sidthesloth|1.0.0|
|language-stylus|sysoev|1.6.0|
|vscode-todo-highlight|wayou|0.4.18|
|html-css-class-completion|Zignd|1.1.0|;

---
Hello, first of all, I want to thank everyone for this awesome text editor.

Since the last update, my terminal seems to have a really weird formatting when running gulp tasks.
Here's a screenshot illustrating this issue: https://snag.gy/tdx2u4.jpg
Steps to Reproduce:

1. Open new terminal 
2. Run a gulp task that has a big output length

**Comment by kieferrm** [comment] 2017-05-05 22:39
This is a duplicate of #19665.

**Closed by kieferrm** 2017-05-05 22:39 UTC
