### ISSUE TITLE
Flickering when choosing theme from svg

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#135600] opened 2021-10-21 21:48 UTC
From @bamurtaugh 

- Get started
- Click between themes in svg
- :bug: Flickering, sometimes click doesn't stick

![recording (52)](https://user-images.githubusercontent.com/25310137/137556413-5db99b87-4388-4047-adce-7021acf96713.gif)

**Comment by JacksonKearl** [comment] 2022-04-18 19:31
Duplicate of #134214

**Closed by JacksonKearl** 2022-04-18 19:31 UTC
Labels: bug, polish, web, getting-started, vscode.dev
