### ISSUE TITLE
VSCode .env parser does not handle environment variables with `=` properly

### ISSUE THREAD

**Issue by lasse-aasmot-nhy** [microsoft/vscode#206787] opened 2024-03-04 11:44 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0 , 019f4d1419fbc8219a181fab7892ebccf7ee29a2, x64
- OS Version: Windows 10 Enterprise, 10.0.19045 Build 19045

Loading the workspace `.env` file loads an environment variable with a `=` in it. This means that it fails to parse things like Connection strings.

Temporary workaround is to disable the environment loading feature (for my case, using python environments, by applying the `  "python.terminal.activateEnvironment": false` setting)

Steps to Reproduce:

1. create workspace
2. create `.env` file
3. write the line `connectionstring=Endpoint=some.endpoint;etc=etc;` in said `.env` file. Use a valid connection string to e.g. an Azure Eventhub, or a local database, or w/e to verify.
4. Running your code snippets no longer works in the integrated terminal as the VSCode .env parser seems to not read the env file correctly. It works fine in OS native terminals (cmd, PS etc) for Python and TypeScript code, so this is probably an issue with the VSCode env file parser

**Comment by karrtikr** [comment] 2024-03-05 06:11
This is actually an issue on VS Code. Closing as duplicate of https://github.com/microsoft/vscode/issues/197603, please like/comment that to raise priority.

**Closed by karrtikr** 2024-03-05 06:11 UTC
Labels: triage-needed
