### ISSUE TITLE
VS Code doesn't recognize the JS Date method toGMTString()

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [microsoft/vscode#150217] opened 2022-05-23 20:05 UTC
The IDE doesn't recognize the Date object's `toGMTString()` method in JavaScript, even though said method is actually completely valid

I am using the last version of Visual Studio Code as of May 23, 2022

**Comment by mjbvz** [comment] 2022-05-23 20:18
Duplicate of https://github.com/microsoft/TypeScript/issues/13622

We don't suggest this method because it is deprecated: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString

**Closed by mjbvz** 2022-05-23 20:18 UTC
