### ISSUE TITLE
Persist git branches that have been recently checked out

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18231] opened 2017-01-06 18:03 UTC
I use "Git: Checkout" a lot and it would be really useful to have a section of recent branches at the top, like how cmd+p always has "recently opened" above all file results.

**Comment by anirudhrb** [comment] 2017-08-10 10:18
Is someone working on this? I wanna try this. I am new to the code so I'll need some pointers.

**Comment by gagangupt16** [comment] 2017-09-17 19:27
1. Should it be based on a config?
2. Should entire list be sorted by commit date?
3. If no, should n or less number of most recent branches be shown and then alphabetical?
4. If no, what should be listing strategy?

**Comment by ohana54** [comment] 2017-12-06 19:35
I'm creating a PR for this (still WIP)

**Comment by BrianJFeldman** [comment] 2018-03-09 01:04
Has there been any updates on this issue, the team and I were just talking about this today?

**Comment by ohana54** [comment] 2018-03-09 16:18
I'm so sorry for the delay, a colleague was supposed to push this forward and I guess it was forgotten.
I cleaned up what I had and submitted a PR, it should be a good start.

**Comment by flaw600** [comment] 2018-06-27 01:57
@ohana54 has this been completed?

**Comment by ohana54** [comment] 2018-06-27 08:42
@flaw600 waiting for review on my PR

**Comment by joaomoreno** [comment] 2018-07-05 09:08
Closing as dupe of https://github.com/Microsoft/vscode/issues/38507

**Closed by joaomoreno** 2018-07-05 09:08 UTC
Labels: feature-request, git, good first issue, help wanted
