### ISSUE TITLE
Only column breakpoints should show inline bp indicator

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21950] opened 2017-03-04 00:56 UTC
My debug adapters return column locations of BPs, even when a column BP wasn't set. As a result, my code ends up full of bp indicators:

![image](https://cloud.githubusercontent.com/assets/323878/23574308/012b089c-0032-11e7-80df-20126fa22b62.png)

Should we
- only show the column indicators when the user set a column bp
- show the column indicators unless there is only whitespace before that position
- or leave it up to the debug adapter to return a column or not

**Comment by chrisdias** [comment] 2017-03-07 04:54
I'm seeing lots of red dots in regular development of a TypeScript based extension.  Seems like they appear after I step across a line with multiple statements. Its easy to do, all you need is a for loop and you are in this state.

**Comment by isidorn** [comment] 2017-03-07 16:58
After discussing with @weinand we believe that it is best to do what we already specified in the previous milestone in this [comment](https://github.com/Microsoft/vscode/issues/14784#issuecomment-279981392)

In short the debug adapter is in charge what breakpoint should he transform into a column brekapoint. Thus an adapter should not add a column to a regular breakpoint if it is not a column breakpoint. Due to this assigning to @roblourens 

@chrisdias are you talking about brekapoints or the yellow top stack frame decoration. If you are talking about red brekapoints please file a bug with reproducable steps and file it to me since for that scenario we use

**Comment by chrisdias** [comment] 2017-03-07 19:22
https://github.com/Microsoft/vscode/issues/22172

**Comment by roblourens** [comment] 2017-03-08 05:15
This line: makes it look like the column breakpoints should be ignored already. Is that changing? https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L964

**Closed** 2017-03-08 10:10 UTC

**Comment by isidorn** [comment] 2017-03-08 11:01
@roblourens my mistake. I was accidently adding a column to a breakpoint when user edits a file.

And yes that line is not supposed to change I just forgot about it. So it is fine for your adapter to return columns if it did not recieve columns.
And the adapter is in charge if it wants to diable column support by potentially always returning `column: undefined`
