### ISSUE TITLE
Editor on Mac OS X should support System Find/Replace keyboard commands

### ISSUE THREAD

**Issue by sivy** [Microsoft/vscode#654] opened 2015-11-25 19:14 UTC
As a Mac developer, I expect my editor to support system-wide find/replace commands. I often work from a terminal, select some text, ⌘-E to use for Find, then switch to en editor and ⌘-G to Find Next. This is broken (unimplemented but _feels_ broken) in Code.

![screen shot 2015-11-25 at 12 11 16 pm](https://cloud.githubusercontent.com/assets/70188/11407075/c187f7c2-936d-11e5-9e65-01d92fb3c364.png)

At a minimum I would expect to see 
- Find...
- Find Next
- Find Previous
- Replace
- Replace Next
- Use Selection For Find
- Use Selection For Replace

**Comment by alexandrudima** [comment] 2015-11-26 11:22
@joaomoreno @weinand I'm not familiar at all with system-wide find/replace mechanics on OS X.

Is the text to find going to some system specific location? (is it like a clipboard mechanism?) Can this be accessed from electron?

**Comment by joaomoreno** [comment] 2015-11-26 13:05
Wow, first time I hear about this, it's very interesting! [Found this](https://github.com/atom/atom/issues/4650). I'd label this one `upstream`.

**Comment by rhires** [comment] 2015-12-18 19:34
Or at least allow a configurable set for Mac OS style keyboard shortcuts, so that way people who might use the same tool on both MS and Mac platforms can keep the shortcuts the same in both places.

**Comment by bpasero** [comment] 2017-01-05 07:37
Seems to be a dupe of https://github.com/Microsoft/vscode/issues/11233

**Closed by bpasero** 2017-01-05 07:37 UTC
Labels: feature-request, upstream
