### ISSUE TITLE
integrated terminal doesn't redraw correctly

### ISSUE THREAD

**Issue by jrood** [Microsoft/vscode#7192] opened 2016-06-03 16:05 UTC
- VSCode Version: 1.2.0 - Insider
- OS Version: Windows 7

Steps to Reproduce:

1. Resize the terminal to be very narrow so that some text gets cut off
2. Resize it back to normal size
3. See that the text is either still cut off or drawn in a weird way

notice how "All rights reserved" is not redrawn
![a](https://cloud.githubusercontent.com/assets/6615558/15784997/b43e3768-297a-11e6-9293-2ceaa827ac71.png)
![b](https://cloud.githubusercontent.com/assets/6615558/15784996/b4382ab2-297a-11e6-87fd-fad43f1229ec.png)
![c](https://cloud.githubusercontent.com/assets/6615558/15784998/b4482f34-297a-11e6-8297-d9926aa638b7.png)

**Comment by jrood** [comment] 2016-06-03 21:51
I wouldn't be surprised if this was a term.js bug

**Comment by Tyriar** [comment] 2016-06-04 07:08
@jrood it is, we're likely moving to another lib in the next version

**Comment by Tyriar** [comment] 2016-07-05 17:54
Duplicate of https://github.com/Microsoft/vscode/issues/8336

**Closed by Tyriar** 2016-07-05 17:54 UTC
Labels: bug, integrated-terminal
