### ISSUE TITLE
Drag And Open Folder

### ISSUE THREAD

**Issue by StephenChips** [Microsoft/vscode#62886] opened 2018-11-10 08:49 UTC
I hope we can drag and open a folder(directory) just like we can drag and open a file in vscode, so that we don't need to open the software first, then look up the menu, and search for the directory in explorer, at last, open a folder.

**Comment by isidorn** [comment] 2018-11-12 08:48
This works fine for me. If this does not work for you let me know what you are doing differently and make sure to try to reproduce using vscode insiders https://code.visualstudio.com/insiders/
If vscode is not open, dragging a folder on top of it also works for me

Closing this, will reopen if you provide more details

![draganddrop](https://user-images.githubusercontent.com/1926584/48336087-cbc88d80-e65f-11e8-9f24-23bafe5b96e6.gif)

**Closed by isidorn** 2018-11-12 08:48 UTC
