### ISSUE TITLE
Can not paste into terminal

### ISSUE THREAD

**Issue by Dekeyras** [Microsoft/vscode#8972] opened 2016-07-08 20:08 UTC
- VSCode Version: 1.3.0
- OS Version: Windows 10

Steps to Reproduce: 

1. Open terminal in editor
2. Right click in terminal window

Expected: 
Context menu shows

Actual:
No context menu. Ctrl+V does not paste so there is no way to mark or paste into the terminal.

**Comment by eladcandroid** [comment] 2016-07-10 10:55
Also here. (Fedora 24)

**Comment by Tyriar** [comment] 2016-07-11 17:51
Duplicate of #6451

**Closed by Tyriar** 2016-07-11 17:51 UTC
