### ISSUE TITLE
Endless download save dialogs

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86100] opened 2019-12-03 15:31 UTC
Version: 1.41.0-insider (user setup)
Commit: 97855786a014be2440751b038b373c3726e11fe8
Date: 2019-12-03T05:40:39.806Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

- open a remote WSL window
- clone https://github.com/eclipse/eclipse.jdt.ui.git
- select `org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text` and choose `Download` from the context menu
- Save dialog appears. The name says `root` (it is the name of the root folder of workspace folder).
- press cancel
- the Save dialog appears again. Again with `root`
Same after cancel.

When I hit this first (not sure which folder I selected), I gave up after clicking 20 times on cancel and had to to kill VSCode.

-> Should cancel after the first cancel
-> Should have a better suggested name than 'root'

**Comment by isidorn** [comment] 2019-12-03 15:38
The cancel should cancel all the download dialogs, to get out of this bad experience.
As for a better suggested name - I believe there is already an issue for this. And that I can tackle separatly.

**Comment by aeschli** [comment] 2019-12-03 15:40
I had `"explorer.compactFolders": true`, not sure if this relevant

**Comment by isidorn** [comment] 2019-12-03 15:43
Should not be relevant.

**Comment by aeschli** [comment] 2019-12-05 15:27
There are still many download dialog when selecting an item that contains compact folders:
- in the explorer, set the selection on org.eclipse.jdt.junit.runtime - src -org\eclipse\jdt\internal\junit\runner
- Move the mouse over jdt, open the context menu and run `Download'
- On the first dialog press 'Cancel'. Next dialog shows up.
Maybe same problem as https://github.com/microsoft/vscode/issues/86408.

**Comment by isidorn** [comment] 2019-12-05 16:09
The issue with single selection triggering mulit downloads is duplicate of #86408
The issue that the first cancel does not stop the other dialogs is this one and it is fine to reopen. However not something for last day of endgame, puhsing out to next milestone. Thanks!

**Closed** 2020-01-21 15:45 UTC
Labels: bug, file-explorer, verification-found
