### ISSUE TITLE
Minor highlighting bug in JS/TS template strings

### ISSUE THREAD

**Issue by tarekis** [Microsoft/vscode#32773] opened 2017-08-18 10:33 UTC
- VSCode Version: 1.14.2
- OS Version: Ubuntu 16.04 x64

Dot notations and similar special characters used in code (brackets, commas) inside template strings are highlighted with the string highlighting color instead of proper highlighting color.

Code *inside* template strings:
![selection_034](https://user-images.githubusercontent.com/16593597/29455354-2a18ffbc-8411-11e7-8907-72831711f1ee.png)
![selection_035](https://user-images.githubusercontent.com/16593597/29455357-2bdc7176-8411-11e7-9344-a584e3f4ca6f.png)

Code *outside* template strings:
![selection_036](https://user-images.githubusercontent.com/16593597/29455416-5a233164-8411-11e7-98c1-45e4d000d6ae.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-08-18 21:57
I believe the root cause is that we failed to reset colorization for template expressions in jsx and tsx files.  Please try out the next insiders build fixes this issue

**Comment by roblourens** [comment] 2017-08-31 21:15
I still see a difference in some themes. This is "Red":

![image](https://user-images.githubusercontent.com/323878/29945643-d3f7d8b0-8e56-11e7-8ecf-36b11e8791ae.png)

"string" is applied:
![image](https://user-images.githubusercontent.com/323878/29945655-e1a9c9aa-8e56-11e7-9ee7-86f6783142de.png)

**Comment by roblourens** [comment] 2017-08-31 21:16
How people use that theme, I will never understand.

**Comment by mjbvz** [comment] 2017-08-31 21:20
Yes, the solution requires a per-theme fix. I only covered vsdark and vslight this iteration. Will investigate doing the same for our other built-in themes next iteration

**Comment by roblourens** [comment] 2017-08-31 21:24
Oh I see. Yeah I see it fixed in those themes.

**Comment by mjbvz** [comment] 2017-09-20 00:44
With 33ec299b85bf38bc824c3138147ca70d5affd5f2, this should now be fixed for all built-in themes

**Closed by mjbvz** 2017-09-20 00:44 UTC
Labels: bug, grammar, javascript, themes, typescript
