### ISSUE TITLE
when expression about terminal tabs not working well

### ISSUE THREAD

**Issue by Y-Sindo** [microsoft/vscode#123089] opened 2021-05-06 08:39 UTC
Issue Type: <b>Bug</b>

When I have multiple tabs in terminal, `terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus`  is always true even when my focus is on editor. This makes me unable to use key `delete`  in the editor to delete a char as there is a default key binding workbench.action.terminal.killInstance for `delete` when: terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.32GB free)|
|Process Argv|--crash-reporter-id 4c4271d5-8fc3-4011-bb76-d1a1f4d219c3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.25.1
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
azure-account|ms-|0.9.8
powershell|ms-|2021.2.2
prettyxml|Pra|0.7.2
vscode-yaml|red|0.18.0
code-spell-checker|str|1.10.2
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30267464
vshan820:30294714
vscus158cf:30286554

```

</details>

**Comment by meganrogge** [comment] 2021-05-06 14:33
Duplicate of #123040

**Closed** 2021-05-06 14:34 UTC
Labels: *duplicate, new release
