### ISSUE TITLE
recreating: vscode app becomes unresponsive in editor although menus work #41426

### ISSUE THREAD

**Issue by arrowplum** [Microsoft/vscode#47160] opened 2018-04-03 19:00 UTC
Re-creating bug #41426 that was not fixed but was closed and locked.

current status: same as before unresponsive app that is running, menu items can be selected but main window has blocks that dissapear if clicked on and is otherwise frozen.. 

$ code --status
ATTENTION: default value of option force_s3tc_enable overridden by environment.

Version:          Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:30.761Z)
OS Version:       Linux x64 4.13.0-37-generic
CPUs:             Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (4 x 3095)
Memory (System):  7.55GB (0.33GB free)
Load (avg):       0, 0, 1
VM:               100%
Screen Reader:    no
Process Argv:     /usr/share/code/code --unity-launch
CPU %   Mem MB     PID  Process
    1      108    3123  code main
    0       23    3126     zygote
    2      317    3164       window (ldap_ee.c - all (Workspace) - Visual Studio Code)
    2      131    3352         extensionHost
    0       46    3678           electron_node server.js 
    0       46    3693           electron_node jsonServerMain.js 
    0       23    3721           /home/joem/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.Extension.linux
    0       23    3876             /home/joem/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 3721 0
    0       23    6601           /home/joem/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.Extension.linux
    0       15   93334             /home/joem/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 6601 5
    0        8   94914             /home/joem/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 6601 6
    0        0   63913           git fetch
    0        0   63914             ssh git@github.com git-upload-pack 'citrusleaf/aerospike-client-python.git'
    0        0   63950           git fetch
    0        0   63951             ssh git@github.com git-upload-pack '/citrusleaf/aerospike-client-c'
    0       85    3353         watcherService
    0       39    3372         terminal
    0        0    3388           /bin/bash
    0       62    3598         searchService
    0       39    6364         terminal
    0        0    6371           /bin/bash
    0       93    3167       shared-process
    1       85    3153     gpu-process
Workspace Stats:
|  Window (ldap_ee.c - all (Workspace) - Visual Studio Code)
|    Folder (aerospike-server-enterprise): 1122 files
|      File types: c(349) h(329) lua(76) filters(27) vcxproj(27) config(23)
|                  html(21) md(14) mk(11) gitignore(11)
|      Conf files: makefile(38) cmake(8) sln(3)
|    Folder (aerospike-server): 2604 files
|      File types: h(617) o(488) c(400) d(226) 0(59) cc(57) lua(45) in(30)
|                  sh(22) gitignore(17)
|      Conf files: makefile(25) cmake(8) sln(4) launch.json(2)
|                  settings.json(1) tasks.json(1)
|    Folder (openldap): 7248 files
|      File types: c(4994) h(485) txt(263) in(191) conf(120) 1(97) ldif(85)
|                  cpp(59) 5(50) sdf(46)
|      Conf files: makefile(46)
|    Folder (ldapper): 32 files
|      File types: ldif(17) c(7) json(2) swp(1) zip(1)
|      Conf files: launch.json(1) makefile(1)
|    Folder (joemconfigs): 7 files
|      File types: conf(6) supp(1)
|      Conf files:
|    Folder (aerospike-client-java): 1117 files
|      File types: class(471) html(296) java(284) lua(17) jar(10) xml(8) md(7)
|                  properties(6) jsp(4) js(1)
|      Conf files:
|    Folder (aerospike-client-python): 669 files
|      File types: h(299) py(202) c(52) o(52) lua(24) rst(10) conf(4) deb(4)
|                  txt(4) md(3)
|      Conf files:
|    Folder (test): 11637 files
|      File types: lua(5103) sh(3262) conf(141) py(136) xml(91) txt(79)
|                  html(50) java(47) c(46) yml(38)
|      Conf files: makefile(13) csproj(1) sln(1)
|    Folder (aerospike-tests-python): 341 files
|      File types: py(292) lua(22) yaml(16) c(2) yml(1) gitignore(1) sh(1)
|      Conf files: makefile(2)
|    Folder (aerospike-mod-lua): 124 files
|      File types: h(31) c(24) o(23) lua(21) mk(4) json(2) xcscmblueprint(2)
|                  vcxproj(2) filters(2) props(2)
|      Conf files: launch.json(1) makefile(1) sln(1)

**Comment by arrowplum** [comment] 2018-04-03 19:02
no it is not covered by that issue, @vscodebot

**Comment by roblourens** [comment] 2018-04-04 01:07
He asked if you tried the `--disable-gpu` flag that helps with issues like this, did you?

**Comment by arrowplum** [comment] 2018-04-18 01:49
@roblourens yes, and I said so in the message just before the one he left then that whole conversation was locked so I couldn't re-say it. 

Now you have asked again and closed it but it is a real issue that is repeatable *unless* I use the --disable-gpu flag. 

I don't understand, is this not a bug? It is not like I am whining to you about a feature or something.

**Comment by arrowplum** [comment] 2018-04-18 01:50
please re-open.

**Comment by arrowplum** [comment] 2018-04-18 01:50
I do not think I have any more info to give.

**Comment by bpasero** [comment] 2018-04-18 17:04
Very likely a duplicate of issues such as https://github.com/Microsoft/vscode/issues/40009 if `--disable-gpu` fixes it.

**Closed by bpasero** 2018-04-18 17:04 UTC
Labels: gpu, needs more info
