### ISSUE TITLE
Code Helper using almost 100% CPU

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#31328] opened 2017-07-24 15:02 UTC
- VSCode Version: 1.14.2
- OS Version: macOS Sierra 10.12.6

I touched my mac and I felt it's hot, checked "Activity Monitor" and I saw "Code Helper" was using a lot of CPU (almost 100%). I was using only 1 window. I even killed process and closed VSC, but it was the same. I can close it, kill process and when I open VSC "Code Helper" again will take almost 100% CPU. After start it reaches about 180% CPU and it drops to ~100%.

As I tested, if you open VSC and you don't focus on it everything is OK. But if you open it and you press mouse click on VSC "Code Helper" goes crazy.

I can cook eggs on my mac 😄 

Extensions:

- PeterJausovec.vscode-docker
- arcticicestudio.nord-visual-studio-code
- dbaeumer.vscode-eslint
- esbenp.prettier-vscode
- formulahendry.auto-close-tag
- formulahendry.auto-rename-tag
- formulahendry.code-runner
- joelday.docthis
- msjsdiag.debugger-for-chrome
- robertohuertasm.vscode-icons
- xabikos.JavaScriptSnippets
- ziyasal.vscode-open-in-github

**I tried with and without extensions and it was the same!**

[7d48_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1170206/7d48_main.cpuprofile.txt)
[7d48_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1170207/7d48_renderer.cpuprofile.txt)

**Comment by bsvipas** [comment] 2017-07-24 16:07
I restarted mac, but it's the same...

**Comment by mjbvz** [comment] 2017-07-24 17:52
Can you please get the full command line arguments of the code helper process by running:

```
ps aux | grep PID_FROM_ACTIVITY_MONITOR
```

in the terminal

**Comment by bsvipas** [comment] 2017-07-25 07:55
@mjbvz Right now everything seems okey. I don't know why, but Code Helper isn't using a lot of CPU. When it will be same again I will post it.

**Comment by bsvipas** [comment] 2017-07-25 12:08
@mjbvz Tested, same happens on Insiders.

![image](https://user-images.githubusercontent.com/30043375/28571319-13ecd296-714b-11e7-8fb0-12d0c75fddf6.png)

`
bsvipas          17424 100.0  3.5  3807600 594064   ??  R     3:03PM   2:10.98 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap --type=watcherService
`

**Comment by mjbvz** [comment] 2017-07-26 04:53
@Tyriar Assigning you since I remember you mentioned working the watcher service at one point

@bsvipas Does this happen for any folder you open or just one specifically? Make sure to manually kill the high cpu code helper process before trying to open a new folder

**Comment by Tyriar** [comment] 2017-07-26 04:56
Looks like it's the old watcher service.

**Comment by bsvipas** [comment] 2017-07-26 07:35
@mjbvz I don't know, I tried only on one folder. I killed it I even restarted the mac and it was the same. Right now I'm not using VS Code, because I can't, I'm afraid my mac will burn since I'm programming a lot of time.

**Comment by bsvipas** [comment] 2017-07-26 15:12
Right now Code Helper process CPU dropped. I think it happens randomly, I don't know how produce it.

**Comment by hatrabbit** [comment] 2017-07-28 00:22
This issue has been ongoing for me with both standard and Insider builds, with or without plugins. I filed a ticket against the Insider build a couple of weeks back including a process sample. I'm happy to do that again if need be. Sadly, I'm not able to run Code with this issue still present, as the impact on battery life is too great. My typical workspaces are 1) a folder containing a dozen small to medium-sized git repos 2) a large git repo with submodules 3) An assortment of random smallish git repos, one per window. One thing I have observed (which may be of no consequence) is that closing one window almost always resolves the issue temporarily, regardless of which window/workspace I close. If I limit myself to a single window, I don't have the issue at all (so far - I wouldn't swear to it) . I hope this is helpful in some way.

Cheers

**Comment by Tyriar** [comment] 2017-07-28 15:47
@hatrabbit could you try adding this setting?

```js
"files.useExperimentalFileWatcher": true
```

**Comment by hatrabbit** [comment] 2017-07-28 17:48
@Tyriar Trying it now.

**Comment by hatrabbit** [comment] 2017-07-28 18:13
@Tyriar Sorry, no change. I did restart Code after I added the setting. I'm hovering at ~70%cpu with 3 workspaces open.

**Comment by Tyriar** [comment] 2017-07-28 18:43
@hatrabbit did you do a full restart via cmd+q or File > Exit? Approximately how many files are in the workspaces?

**Comment by hatrabbit** [comment] 2017-07-31 17:55
@Tyriar Yes, I did. And my current workspaces have ~3300 and ~19600 files, but I've had the same issue with some that had as few as 200-300 files.

**Comment by Tyriar** [comment] 2017-07-31 18:39
@bpasero any ideas?

**Comment by bsvipas** [comment] 2017-08-01 15:05
Any news on this? Because sometimes everything is good and sometimes it feels my mac will burn...

**Comment by richardj-bsquare** [comment] 2017-08-04 07:58
This is the same issue as has been reported before and closed (#24713). It's always on large repositories, where it needs to watch a helluva lotta files; it's a cross-platform issue too (Linux and Mac at least it seems).

**Comment by hatrabbit** [comment] 2017-08-04 19:30
@richardj-bsquare I respectfully disagree for the following reasons:
1) It's a new behavior - I used Code for a good year without seeing this kind of CPU usage. It would have been a deal breaker on day one.
2) The issue seems to crop up far more often with multiple windows/workspaces open. If I open my ~large repos in the same workspace by opening the parent folder, I have no such problem.
3) I can reproduce the problem with small repositories (<300 files)

It's also worth saying I wouldn't report this if I didn't really love VS Code. It's freaking great.

Thanks

**Comment by RobotJiang** [comment] 2017-08-09 13:02
I think it was caused by files in node_modules folder.

**Comment by bpasero** [comment] 2017-08-11 07:28
@bsvipas which folder are you opening with VS Code, is it a very large folder?

**Closed** 2017-08-18 08:00 UTC
Labels: file-watcher, needs more info

**Comment by bsvipas** [comment] 2017-08-27 12:53
@bpasero Yes it's large project with a lot of node_modules and bower_components. This issue is still in 1.5 version.

**Comment by bsvipas** [comment] 2017-08-27 13:06
I know how to fix it. You need to add folders to the `files.watcherExclude` or/and enable `    files.useExperimentalFileWatcher`.

**Comment by Tyriar** [comment] 2017-08-27 16:17
@bsvipas that's good news, the old file watcher will eventually be deprecated/removed in favor of the experimental one, also files.watcherExclude is provided to work around these sorts of performance problems if you don't need to watch a big portion of the files. I think we can leave this closed. 👍

**Comment by lcx-seima** [comment] 2017-08-28 02:15
@bsvipas Manually exclude node_modules in `files.watcherExclude` works for me(OSX energy cost from hundreds down to 30). Only enable `files.useExperimentalFileWatcher` seems nothing changed. 😂

**Comment by bsvipas** [comment] 2017-08-28 05:40
@lcx-seima For me `files.watcherExclude` works really good, but I also exclude some folders just in case.

**Comment by jmaister** [comment] 2017-09-18 09:43
Using 1.16.1. Still with the same problem.

Modified files.watcherExclude and enabled files.useExperimentalFileWatcher. CPU at constant 25% and 2GB of RAM.

It is unusable.

**Comment by bsvipas** [comment] 2017-09-18 09:47
@jmaister I'm using project with a lot of modules, files and so on and everything is fine for me. Maybe you configured badly `files.watcherExclude`. Also remember do the same for search exclude.

**Comment by shimjudavid** [comment] 2017-10-06 05:49
This is what worked for me - update the user settings of VSCode- 

   "files.useExperimentalFileWatcher": true,
   "files.exclude": {
    "**/.git": true,
    "**/.DS_Store": true,
    "**/node_modules": true,
    "**/node_modules/**": true
},
"search.exclude": {
    "**/node_modules": true
},
"files.watcherExclude": {
    "**/node_modules/**": true
},
