### ISSUE TITLE
Do not show dropdown for disabled extension if there is only one choice enabled

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14373] opened 2016-10-25 09:14 UTC
Testing #14288 

Imho when the user can only make one choice, just run this action and do not show me the dropdown. This allows to speed up toggling enablement for many extensions 👍 

![image](https://cloud.githubusercontent.com/assets/900690/19679966/2a30d7ec-9aa4-11e6-9a5a-f101867b4136.png)

**Comment by bpasero** [comment] 2016-10-25 09:39
I think this also applies to clicking on "Disable" from an empty workspace.

**Comment by sandy081** [comment] 2016-10-26 15:21
This is fixed in Extensions viewlet by #14379 

This is still applicable in Extension editor

**Comment by sandy081** [comment] 2017-01-10 10:56
Duplicate of #16440

**Closed by sandy081** 2017-01-10 10:56 UTC
Labels: extensions
