### ISSUE TITLE
Run tasks from NPM Script Explorer using Horizontal Terminal Splitting

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#49737] opened 2018-05-12 07:20 UTC
Basically I want a feature for running tasks from NPM Script Explorer using Horizontal Terminal Splitting :)

**Comment by egamma** [comment] 2018-05-14 08:52
@dbaeumer the tasks API is used to execute an npm script. As far as I know there is no API exposed by tasks for how the tasks is run in the terminal. To add this support for npm scripts would require some support from the Tasks API first. Makes sense?

**Comment by dbaeumer** [comment] 2018-05-15 08:06
@egamma makes sense.

**Comment by alexr00** [comment] 2018-12-21 14:53
Duplicate of #47265

**Closed** 2018-12-21 14:54 UTC
Labels: *duplicate, api, feature-request, tasks
