### ISSUE TITLE
unable to remove extension from the update extension list, getting error "Cannot find the extension".

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5514] opened 2016-04-19 23:21 UTC
- VSCode Version: 1.0.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open any folder which contains ts project.
2. Click on extension update icon from status bar to get info about extension to be updated.
3. Try to uninstall any previously installed extension by clicking on remove extension icon from update extension list.
![image](https://cloud.githubusercontent.com/assets/17735796/14658704/cce7f5fe-064a-11e6-8beb-51b18dce655c.png)

**Note: I am able to uninstall extension from installed extension list.**

Actual: Getting error message while trying to remove extension from update window. 
![image](https://cloud.githubusercontent.com/assets/17735796/14658587/c6f31314-0649-11e6-89e6-32eeb56525d8.png)
Expected: User should be able to uninstall extension if he doesn't want to update. 

Dev tool error log message:

**workbench.main.js:91 Could not find extension: Error: Could not find extension,    at c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\electron-main\sharedProcessMain.js:7:30783,    at Object.p [as _notify] (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\electron-main\sharedProcessMain.js:5:1987),    at Object.__dirname.undefined.N.enter (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\electron-main\sharedProcessMain.js:5:5149),    at __dirname.undefined.t.Class.define._run (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\electron-main\sharedProcessMain.js:5:6975),    at __dirname.undefined.t.Class.define._completed (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\electron-main\sharedProcessMain.js:5:6416),    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)e.doShow @ workbench.main.js:91**

**Comment by joaomoreno** [comment] 2016-04-20 07:08
Duplicate of #4970

**Closed by joaomoreno** 2016-04-20 07:08 UTC
Labels: v-test
