### ISSUE TITLE
Go To Definiton & Find All References not working

### ISSUE THREAD

**Issue by trohat** [Microsoft/vscode#37713] opened 2017-11-06 15:48 UTC
Hi!
Command Go To Definition and some similar commands (like e.g. Find All References) do not always work. There is a picture below, from when they are not working. (Its from the beginning of the file.) On some other places (like lower in the same file) they do work properly.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063

Extension|Author (truncated)|Version
githistory|don|0.2.3
LiveServer|rit|3.0.0
markdown-preview-enhanced|shd|0.3.0

Reproduces without extensions: Yes, it reproduces

![go_to_def](https://user-images.githubusercontent.com/30416457/32449287-719d6d34-c311-11e7-8ea0-83369d5fb30f.png)

Some code to reproduce:
this.initializeCastPlayer();
  this.initializeLocalPlayer();
};
CastPlayer.prototype.initializeLocalPlayer = function() {
  this.localPlayer = document.getElementById('video_element');
  this.localPlayer.addEventListener('loadeddata', this.onMediaLoadedLocally.bind(this));
};

**Comment by mjbvz** [comment] 2017-11-06 16:57
Please share a complete code snippet that shows the definition of `CastPlayer` as well

**Comment by trohat** [comment] 2017-11-08 09:38
I found some code on the GitHub, which is similar to mine, and functions Go To Definition and Find All References on initializeCastPlayer and initializeLocalPlayer in the constructor do not work as they do not in my code.
Here is the link:
https://github.com/auino/chromecast-web-viewer/blob/master/script.php

**Comment by trohat** [comment] 2017-11-08 16:44
If you need more code to test, this example code gives no results on Find All References on getToken on line 90.
https://github.com/firebase/quickstart-js/blob/master/messaging/index.html
(it was line 95 in the example, it got reformatted after pasting into VSC)

![find_all_ref](https://user-images.githubusercontent.com/30416457/32561399-74aae21c-c4ac-11e7-88b6-17d67ff62b2e.png)

**Comment by mjbvz** [comment] 2017-11-08 18:40
@trohat Are you working in a plain js file or in a html script block?

**Comment by hielfx** [comment] 2017-11-09 10:15
Since v1.18 update the 'go to definition' always displays 'No definition found for __'

**Comment by trohat** [comment] 2017-11-09 12:02
@mjbvz I work in a plain js file.

**Comment by mjbvz** [comment] 2017-11-09 18:33
Duplicate of https://github.com/Microsoft/TypeScript/issues/18171

For ES5 classes, we currently don't understand what `this` refers to when in the constructor function. TypeScript powers our JavaScript intellisense so we need an upstream fix for this

Closing as upstream

**Closed by mjbvz** 2017-11-09 18:33 UTC
Labels: javascript, needs more info, upstream

**Comment by trohat** [comment] 2017-11-14 08:37
Ok, thank you for your answers!
