### ISSUE TITLE
Path gets blacked on hover in terminal if hoverHighlightBackground is opaque

### ISSUE THREAD

**Issue by AnilSonix** [microsoft/vscode#97521] opened 2020-05-11 16:02 UTC
- VSCode Version: 1.46.0-Insider
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open any folder or workspace
2. Open terminal
3. Navigate to any nested directories.
4. Hover over the path in the terminal.
5. The path becomes black.

Does this issue occur when all extensions are disabled?: No

![normal](https://user-images.githubusercontent.com/14151192/81583354-e0a9ec80-93ce-11ea-8475-2a5c5ab77a96.jpg)
![error](https://user-images.githubusercontent.com/14151192/81583358-e273b000-93ce-11ea-92bc-d59a03f4006f.jpg)

**Comment by Tyriar** [comment] 2020-05-11 17:41
I'm guessing you have a non-transparent color set as `editor.hoverHighlightBackground` in your theme.

**Comment by AnilSonix** [comment] 2020-05-12 00:57
How can I override it ?

**Comment by Tyriar** [comment] 2020-05-14 12:45
This setting:

```
"workbench.colorCustomizations": {
  "editor.hoverHighlightBackground": "#ff000080"
}
```

**Comment by AnilSonix** [comment] 2020-05-17 06:24
Thank you 👍

**Comment by dsifford** [comment] 2020-05-22 12:39
Following the instructions you provided @AnilSonix I still cannot reproduce this.

**Comment by Tyriar** [comment] 2020-05-26 15:09
The proper fix for this to draw the highlight under the text probably needs https://github.com/xtermjs/xterm.js/issues/1852 to happen. We could do a workaround to make the color partially transparent if it's detected as opaque.

**Comment by dsifford** [comment] 2020-05-26 15:19
Cool, thanks for the update @Tyriar 

Just went ahead and merged @AnilSonix's workaround in dracula theme for the time being. I was finally able to repro on my end :+1:

**Comment by ChrisPapp** [comment] 2020-05-27 01:46
Can I work on this?

**Comment by AnilSonix** [comment] 2020-05-27 07:00
Should I close this issue now ?
( I'm newbie )

**Comment by Tyriar** [comment] 2020-06-01 18:20
@ChrisPapp I'll have to do a quick fix on this to squeeze it in for this release.

**Comment by ChrisPapp** [comment] 2020-06-01 18:26
@Tyriar I have made a quick fix myself. I can push it now and you can take a look.

**Comment by Tyriar** [comment] 2020-06-01 18:27
@ChrisPapp if it's ready now, sure! 👍

**Closed** 2020-06-01 22:39 UTC
Labels: bug, integrated-terminal
