### ISSUE TITLE
Syntax coloring gets messed up after mixing brackets and slashes.

### ISSUE THREAD

**Issue by olivermue** [Microsoft/vscode#15626] opened 2016-11-17 07:59 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

Take an existing .ts file and insert the following code:
```typescript
  private showPartyColors() {
    let foo = true ? (2 / 4) : (3 / (2 - 8));
    let bar = console.log('I am red, cause I am upset!');
    // here the code party is fully underway (42) ...
    let baz = (3 / 5) / 7;
    let haveParty = console.log('Now coloring of all code below this function is partially wrong.');
  }

  private mySeriousFunction(myParam: number, another: string){
    console.log('Seems I still have a hangover.');
  }
```
The current result is
![image](https://cloud.githubusercontent.com/assets/17193431/20380690/e2d0781e-aca3-11e6-8ce9-92270a00b739.png)

**Comment by ramya-rao-a** [comment] 2016-11-17 18:44
This duplicate of #15334 which got moved to https://github.com/Microsoft/TypeScript-TmLanguage/issues/356

**Closed by ramya-rao-a** 2016-11-17 18:44 UTC
