### ISSUE TITLE
Disable tab end line

### ISSUE THREAD

**Issue by hoangnamitc** [Microsoft/vscode#37201] opened 2017-10-31 03:30 UTC
Hellow everyone, 

I try search but not result. **Please help me how to disable pointer tab end line code:**

DEMO

![image](https://user-images.githubusercontent.com/7042462/32206295-d701de48-be26-11e7-99a9-80d11852eb87.png)

![image](https://user-images.githubusercontent.com/7042462/32206269-bb492940-be26-11e7-8cbf-2ae39452b021.png)

![image](https://user-images.githubusercontent.com/7042462/32206351-15bc0da2-be27-11e7-96cb-1f49cf9bc847.png)

Thanks !

**Comment by octref** [comment] 2017-10-31 22:45
You should report this bug to the php extension that you are using. I'm guessing https://github.com/felixfbecker/php-language-server

**Comment by felixfbecker** [comment] 2017-11-01 01:12
This is an emmet suggestion, not something from the PHP extension.

**Comment by hoangnamitc** [comment] 2017-11-01 01:13
![image](https://user-images.githubusercontent.com/7042462/32255668-7f47ad70-bedc-11e7-956b-4ba0090fdfeb.png)

**Comment by hoangnamitc** [comment] 2017-11-01 01:15
@octref  Please support me :(

**Comment by ramya-rao-a** [comment] 2017-11-01 02:07
@hoangnamitc You want to remove final tabstop that appears at the end of the snippet ?
Or you want to remove the comment?

**Comment by hoangnamitc** [comment] 2017-11-01 02:10
@ramya-rao-a Thanks for reply !

I want to remove final tabstop that appears at the end of the snippet.

**Comment by ramya-rao-a** [comment] 2017-11-01 02:21
In that case, this is a duplicate of #33491
Please follow that thread.
There are no fixes at the moment, but I am working on it.

**Closed by ramya-rao-a** 2017-11-01 02:21 UTC
Labels: emmet

**Comment by ramya-rao-a** [comment] 2017-11-02 01:04
@hoangnamitc I have put in a fix which should be available in Insiders coming out on 2nd Nov.
You can get the Insiders build from https://code.visualstudio.com/insiders

Can you please help with testing this out?
Try a couple of different Emmet abbreviations, especially ones with multiple tabstops

**Comment by hoangnamitc** [comment] 2017-11-02 01:18
Is there an option to disable tabstop?
When try in file *.html is working good. but I try in the file *.php is not good. 
same as above.

**Comment by ramya-rao-a** [comment] 2017-11-02 05:36
Are you using the same snippet in html and php and finding difference between the two?

**Comment by hoangnamitc** [comment] 2017-11-02 06:39
Confirm this version fixed tabstop working exactly.

![image](https://user-images.githubusercontent.com/7042462/32312933-f173c838-bfd2-11e7-90bf-263d09a2110b.png)


P/S: But how long wait to version offical :(

**Comment by ramya-rao-a** [comment] 2017-11-02 15:21
The stable build for 1.18 will be released sometime next week.
