### ISSUE TITLE
Task input variables always show default value instead of remembering the last value

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#72944] opened 2019-04-27 01:55 UTC
- VSCode Version: 1.33.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Create a tasks.json file with a task that uses an input variable of say "promptString" and set it's default value to something.
2. Invoking the script for the first populates with the default value - good so far.
3. Change the value to something else.
4. Invoke the task again and it gives the default instead of the last value entered.  That is very annoying.

If this is the defined behavior of `default` then maybe we need another field `initialDefault` or something like that that provides a default when there is no stored value.

Perhaps I'm spoiled by using picker UI for debug launch configs.  Those remember state even between VSCode invocations IIRC.
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by cmeyertons** [comment] 2019-05-09 14:12
+1 for this -- the input variables for tasks are fantastic but it would be huge if it could just remember my last selection

**Comment by Springrbua** [comment] 2019-07-31 09:39
I would vote for a boolean field `rememberValue`, since this behavior is also needed, when no `default` is specified.

In my case, I have a build or run-task which get's the project name as a parameter. When I am working on a specific project, I usually need to build / run it several times. In this case, it would be cool, if the last entered value is used as a default.  
In my opinion this value could be cleared on exit, similar to the `${string_prompt}` in `Eclipse Launch Configuration`s

**Comment by ChaosinaCan** [comment] 2019-10-08 18:33
It would be nicer to have this built into VS Code, but since it's not yet, I wrote an extension that I think does what you want: https://marketplace.visualstudio.com/items?itemName=spadin.memento-inputs

**Comment by alexr00** [comment] 2019-10-16 14:11
duplicate of https://github.com/microsoft/vscode/issues/65066

**Closed by alexr00** 2019-10-16 14:11 UTC
Labels: feature-request, tasks
