### ISSUE TITLE
Telemetry not being disabled

### ISSUE THREAD

**Issue by Laphro** [Microsoft/vscode#16131] opened 2016-11-28 06:31 UTC
- VSCode Version: 1.7.2
- OS Version: Linux, Windows.

Steps to Reproduce:
1. Disable Telemetry.

I have disabled telemetry as described in the [FAQ](https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting). I have set the following properties in the settings:

```
"telemetry.enableCrashReporter": false,
"telemetry.enableTelemetry": false
```

Now despite of this, when I log my network traffic (with Wireshark) I can see that Visual Studio Code periodically contacts vortex.data.microsoft.com. This is a known server used for telemetry purposes. I have opted out of the telemetry and information is still sent, why? What information is exchanged? 

The FAQ describes:
> If you don’t wish to send usage data to Microsoft, you can set the telemetry.enableTelemetry setting to false.

To me this means that no telemetry connections should be made, because I would assume that continuous connections to the server can still easily be used to collect information for product usage tracking even if no actual private data is being collected by the application itself.

**Comment by seanmcbreen** [comment] 2016-12-01 21:28
We use our telemetry to help understand how to make the product better – in fact a good example of this right now is some work we are doing to improve performance.  So, we appreciate it when users opt to send us telemetry.  
 
That said there are times when people don’t want to do that and you bring up a good point – today we continue to send events stating that a user has `opted out` and nothing else i.e. no usage data is sent.  Here is the test to ensure that is all we send... 
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/telemetry/common/telemetryService.ts#L103
 
But we don’t need to do that and I don’t think it’s what you expect as a user – so we will stop sending anything i.e. even the `opt out` event 😄   Look for a change there soon.
 
Thanks for bringing this to our attention and I hope you enjoy working with VS Code.  

I'll close the issue for now but please fell free to reopen if this is not sufficient.

Sean McBreen – VS Code Team Member

**Closed by seanmcbreen** 2016-12-01 21:28 UTC

**Comment by bsr203** [comment] 2017-02-22 17:02
Hi,

I used to get offline warning, with a stack that it cannot reach `vortex.data.microsoft.com`. Now, I disabled `telemetry` through the setting

```
"telemetry.enableCrashReporter": false,
"telemetry.enableTelemetry": false
```

after the restart, within 20 seconds, I get the same warning, but a different stack. It doesn't have any log on contacting `vortex.data.microsoft.com`, but

```

workbench.main.js:100 The Internet connection appears to be offline.
e.doShow	@	workbench.main.js:100
e.show	@	workbench.main.js:100
(anonymous function)	@	workbench.main.js:141
e.invoke	@	workbench.main.js:30
e.fire	@	workbench.main.js:30
(anonymous function)	@	workbench.main.js:35
y	@	workbench.main.js:32
_progress	@	workbench.main.js:32
y	@	workbench.main.js:32
_progress	@	workbench.main.js:32
t.handlers.(anonymous function)	@	workbench.main.js:35
e.onMessage	@	workbench.main.js:35
(anonymous function)	@	workbench.main.js:35
e.invoke	@	workbench.main.js:30
e.fire	@	workbench.main.js:30
(anonymous function)	@	workbench.main.js:35
e.invoke	@	workbench.main.js:30
e.fire	@	workbench.main.js:30
r	@	workbench.main.js:34
emitTwo	@	events.js:106
emit	@	events.js:191
```

what else need to avoid detecting offline!!!

**Comment by CoeJoder** [comment] 2017-05-29 11:23
Mid 2017, VS Code still tracking?  Sticking with Sublime Text for now.

**Comment by CooperSystems** [comment] 2017-06-17 08:21
Yeah I was just about to install this but saw the 'data' thing in the terms and service.

I'm cutting windows out of my life for becoming spyware, was going to give VSCode a chance because it's open source. But not if it's just another foothold into the same old game

**Comment by jens1o** [comment] 2017-06-17 09:59
Is that real team? I thought opting out means I'm opt out...

**Comment by kieferrm** [comment] 2017-06-30 18:05
@bsr203 the message you see comes from the autoupdater. It checks if a newer version of VS Code is available by comparing the commit hash. You can disable it by setting `update.channel` to `none` in your settings. In case you have extensions installed, you would also see another message caused by the attempt to see if any of the extensions you have installed was updated in the marketplace.

When you have set `telemetry.enableCrashReporter` and `telemetry.enableTelemetry` to `false` no telemetry or crash data is sent to any server.

**Comment by bsr203** [comment] 2017-07-06 11:38
@kieferrm that make sense. I will try disabling `update.channel`. thank you.

**Comment by delsvr** [comment] 2017-10-30 04:28
For the record,

Even with:

```
"telemetry.enableCrashReporter": false,
"telemetry.enableTelemetry": false,
"update.channel": "none"
"extensions.autoUpdate": false
```

I still see connection attempts by Visual Studio Code to `marketplace.visualstudio.com` and `vortex.data.microsoft.com`.

**Comment by jens1o** [comment] 2017-10-30 07:37
:(

That's not I'm expecting, although the first url requested is kind of valid, since you only want to disable automatic update, which means that `Code` is still searching for them.

**Comment by seanmcbreen** [comment] 2017-11-15 06:22
Hi,

I saw a comment re: this in twitter right now - so wanted to do a quick update...

I'm pretty sure we [VS Code Core] are doing the right thing here and we would love any pointers (all code is OSS).  

To be very clear we want to do the right thing (hence my prior comments) and we think we have no gaps.  

At the same time there is a chance an extensions send telemetry and that could be the issue here (we are also working hard to ensure any extension created by our team, other teams and others in general do the right ting).  But we don't control all of their code - or the world :)

Net, net - if there is a gap help us find it - we don't think we have one but if we do we will close it.
Sean

**Comment by jens1o** [comment] 2017-11-15 12:56
@seanmcbreen We're not talking about that telemetry is bad, but instead, we think that opting out, means, that **we do not send ANY analytic**. I don't care about your analytic, and you need to accept that, so I only want communication to the Microsoft servers when it is needed(e.g. installing extensions or looking for updates). I do not want to send any further signals.

(Hoping that anyone responds to this)
