### ISSUE TITLE
'spawn ENOTDIR' error when including a file in 'Find in Files'

### ISSUE THREAD

**Issue by nachocab** [microsoft/vscode#63226] opened 2018-11-15 17:00 UTC
Issue Type: <b>Bug</b>

1. Open 'Find in Files'
2. Add a file to 'files to include'
3. Search for something

It doesn't give an error when you provide a folder, but if you provide a file, it won't work.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 7, 9|
|Memory (System)|16.00GB (1.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
replace-smart-characters|DrM|0.0.2
output-colorizer|IBM|0.1.2
rmd|nac|0.0.1
vscode-paste-and-indent|Rub|0.0.8
html-snippets|abu|0.2.1
Bookmarks|ale|9.2.0
snapshot-tools|asv|0.2.2
unique-lines|bib|1.0.0
vscode-selection-extended|cg-|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
transformer|dak|1.6.0
vscode-eslint|dba|1.7.0
vscode-quick-select|dba|0.2.7
githistory|don|0.4.3
gitlens|eam|8.5.6
sort-lines-by-selection|ear|0.0.3
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
php-debug|fel|1.12.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
macros|ged|1.2.1
pug2html|gin|0.0.5
gc-excelviewer|Gra|2.1.26
vscode-import-formatter|hen|0.1.8
githd|hui|2.0.0
nbpreviewer|jit|1.0.0
nearley|kar|1.0.3
wordcounter|kir|1.4.0
graphql-for-vscode|kum|1.12.1
rainbow-csv|mec|0.8.0
dotenv|mik|1.0.1
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
highlight-dodgy-characters|nac|1.0.0
nacho|nac|0.1.0
run-external|nac|0.1.2
select-paragraph|nac|0.1.1
color-highlight|nau|2.3.0
vetur|oct|0.13.0
vscode-code-outline|pat|0.2.1
material-icon-theme|PKi|3.6.0
markdown-preview-theme-one-dark|rae|0.0.1
subtle-brackets|raf|3.0.0
partial-diff|ryu|1.4.0
exchange-selection-start-end|san|2.0.0
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.2.0
markdown-preview-enhanced|shd|0.3.11
vscode-fileutils|sle|2.13.3
vscode-hexdump|sle|1.7.2
guides|spy|0.9.2
rewrap|stk|1.9.1
language-stylus|sys|1.10.0
open-in-browser|tec|2.0.0
hipsum|thi|1.0.7
tmlanguage|Tog|0.9.0
vscode-input-sequence|tom|0.2.0
wordpress-snippet|tun|1.1.5
sort-lines|Tyr|1.7.0
es-quotes|vil|0.2.6
vscode-react-native|vsm|0.6.18
gitblame|wad|2.6.0
wallaby-vscode|Wal|1.0.100
change-case|wma|1.0.0
cursor-align|yo1|1.0.4
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details>

**Comment by nachocab** [comment] 2018-11-15 17:03
![screen shot 2018-11-15 at 18 03 10](https://user-images.githubusercontent.com/27538/48568916-c3db4880-e900-11e8-9a0b-352f1268a421.png)
![screen shot 2018-11-15 at 18 03 17](https://user-images.githubusercontent.com/27538/48568918-c63da280-e900-11e8-8298-7e78627efa77.png)

**Comment by roblourens** [comment] 2018-11-15 22:09
This doesn't support searching individual files at the moment

**Comment by IvanLinos** [comment] 2018-11-20 11:50
Could we have a "Recent Locations" dropdown in the "files to include" box for those who are using this many times? Something like this will do the trick:

![findinfiles-recentlocations](https://user-images.githubusercontent.com/23552631/48771844-c9e77580-ecc2-11e8-9e51-ba978fcd7256.png)

**Comment by roblourens** [comment] 2019-10-09 02:39
Duplicate of https://github.com/microsoft/vscode/issues/48958

**Closed by roblourens** 2019-10-09 02:39 UTC
Labels: feature-request, search
