### ISSUE TITLE
TypeScript Import Snippet Autocomplete Initial Position

### ISSUE THREAD

**Issue by Domvel** [Microsoft/vscode#45273] opened 2018-03-08 10:13 UTC
Since the last few updates of vs code, the autocomplete (CTRL + SPACE) in a import Snippet Handlebars `{  }` initialize the position to the import-snippet. 
Sounds correctly. But in this way, I excpected (and was in earlier vs code versions) to initilize on poistion index 0 of the autocomplete (intellisense) list.
This should triggered when the user opens the autocomplete`import { here } from './great-stuff'`. To select a module without to input some text. 

Actual:
![import-snippet](https://user-images.githubusercontent.com/35452565/37145514-5a7f1462-22c1-11e8-9414-2be65e2b0d96.png)

Expected:
![import-snippet-ok](https://user-images.githubusercontent.com/35452565/37145694-d5a721ac-22c1-11e8-935b-9338c5a626d6.png)

Issue Type: Improvement
Language: TypeScript

Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Datum 2018-03-07T11:04:09.886Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur ia32

**Comment by mjbvz** [comment] 2018-03-08 10:33
Duplicate of #41060

Set `"editor.suggestSelection": "first"` to always select the first item

**Closed by mjbvz** 2018-03-08 10:33 UTC
Labels: javascript
