### ISSUE TITLE
Avoiding extension host shut down on opening folder

### ISSUE THREAD

**Issue by jumattos** [microsoft/vscode#75720] opened 2019-06-18 18:52 UTC
I am working on a VS code extension that shows remote files. We invoke the `openFolder` command using our own file system provider (powered by the cloud).

The problem is that the command shuts down the extension host process. VS Code then can't find our file system provider, and the file explorer is not loaded correctly. If the user waits a couple of seconds and collapse/expand the file explorer view, the files show up as expected.

Right now, we simply reload the file explorer once the extension is up and running again. This is not ideal, since it takes quite a bit of time and doesn't prevent the failure from happening.

``` typescript
// The next line ensures the file explorer will be loaded correctly
vscode.commands.executeCommand('workbench.files.action.refreshFilesExplorer');
```

How can we work around this? Could we have the option of opening a folder without shutting down the extension host?

**Comment by isidorn** [comment] 2019-06-19 10:22
@jumattos on what activation events does your extension activate? Is your extension open source if yes can you please give a pointer to the GitHub repository.
Extension host shuting down when we open a new folder is designed behavior. Right @bpasero ?
The issue here it seems is that your extension is not ready early enough when the explorer tries to resolve files.

Are you opening a folder which has a Scheme which is tied to your file system provider?

Can you provide reproducable steps using your extension?

**Comment by bpasero** [comment] 2019-06-19 12:28
@isidorn when a folder is opened, the following process are going down and restart:
* renderer process
* extension host process
* any spawned process (such as file watcher, search).

You can try this out easily by:
* open VSCode
* hit the reload command (`Cmd+R`)
* processes will go down and restart

**Comment by jumattos** [comment] 2019-06-19 18:48
> On what activation events does your extension activate?

```
"activationEvents": [
    "*"
],
```

> Is your extension open source if yes can you please give a pointer to the GitHub repository.

Not open source, unfortunately, but I can share with Microsoft employees if needed.

> Are you opening a folder which has a Scheme which is tied to your file system provider?

Yes. We have a `RemoteFileProvider` which implements `vscode.FileSystemProvider`.

**Comment by jumattos** [comment] 2019-06-19 18:51
Since our extension loads on startup already, I don't see a way of having it ready when the explorer tries to resolve the files. Any suggestions?

**Comment by isidorn** [comment] 2019-06-20 08:09
@jumattos  What is your extension and what are the exact steps to reproduce this?
So I can try this on my machine and see what is going on.

Also your extensions shuold be ready since you activate on "*", so when the explorer tries to resolve the files your FileSystemProvider should be registered. Now I need your extension and steps to confirm all of this. If this is not possible I can give you code pointers so you do some debugging. Let me know what works better for you

**Comment by jumattos** [comment] 2019-06-20 22:15
> What is your extension and what are the exact steps to reproduce this?

Our extension is not yet released (we are on private preview + dogfooding). I will send you a link privately, please refrain from sharing.

Yesterday my team and I digged around a little further and found that the extension works on version 1.33.1 of VS Code, but not on the latest version.

Steps to reproduce:
1. Clone a repository that is set up for our extension (e.g. [spring-petclinic](https://github.com/arjun27/spring-petclinic))
1. Open the folder on VS Code
1. Go to the [GitHub Pull Requests](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) extension
1. Sign in to GitHub
1. Open "All" to see all pull requests open
1. Right click the only pull request available
1. Choose "View Remote Files"
1. You will be prompted to login to our extension (let me know if you have any trouble during that step)
1. You will be taken to the Remove Files view. The file explorer will not load correctly
1. Collapse/expand the file explorer after a couple of seconds. That should be enough to trigger refresh, and the files will show up as expected

**Comment by isidorn** [comment] 2019-06-21 14:54
@jumattos thanks for the repro steps.
I have pushed a potential fix for your issue, however I could not verify that it fixes it since I can not log in. If you want to verify if it work just run vscode out of source and try it out (just copy over your extension and the gh pr extension to your user dir /.vscode-oss-dev/extensions).
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run
Or you can wait for monday until we release a new insiders which will have the fix

As for the login issue I have pinged you on Teams for more details.

In case you want to investigate more on our side, here are some code pointers and tips:
F1 > developer tools > sources > put a brekapoint [here](https://github.com/Microsoft/vscode/blob/2955dbfa8efaa1cb51c00be72fb1761f0e54fbd1/src/vs/workbench/contrib/files/common/explorerService.ts#L103)
Try to figure out if the `onDidChangeFileSystemProviderRegistrations` is fired as expected and if the recursive refresh is fired
The code is not that complex. Basically when a new file system provide is regsitered (which should be the case for you) we should refresh the whole tree by firing an event from the explorerService.
That event is handled [here](https://github.com/Microsoft/vscode/blob/2955dbfa8efaa1cb51c00be72fb1761f0e54fbd1/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L430). And it should recursivly refresh the whole tree.

**Comment by isidorn** [comment] 2019-06-26 13:48
I am closing this since I pushed a fix.
Please let me know if you still see this and I can reopen this issue.

**Closed by isidorn** 2019-06-26 13:48 UTC
Labels: file-explorer, needs more info

**Comment by jumattos** [comment] 2019-06-26 19:53
Sorry for the late reply. The fix seems to have worked for most of our use cases. The ones that are not working right now probably have some other cause that I will have to investigate. Thanks for your help! 😊

**Comment by isidorn** [comment] 2019-06-27 07:56
Thanks for letting me know. Adding verified label.
Once you find the other cases with repro steps please open a new issue and ping me on it - thank you very much.
