### ISSUE TITLE
File Exclusion W/ "when" Not Working on Windows 

### ISSUE THREAD

**Issue by alexchro93** [microsoft/vscode#117689] opened 2021-02-25 16:49 UTC
Version: 1.53.2
OS: Windows 10 20H2 Build 19042.804

My files.exclude setting is configured as below and does not hide any *.js or *.map.js from either the Explorer or Search.

```
"files.exclude": {
  "**/.git": true,
  "**/.svn": true,
  "**/.hg": true,
  "**/CVS": true,
  "**/.DS_Store": true,
  "**/*.js": {
    "when": "$(basename).ts"
  },
  "**/**.js.map": {
    "when": "$(basename).ts"
  },
}
```

Explorer is still showing these files...

![image](https://user-images.githubusercontent.com/12327432/109186803-4c432780-775f-11eb-9caa-c1305d95c7e8.png)

Search is still showing these files...

![image](https://user-images.githubusercontent.com/12327432/109186931-6b41b980-775f-11eb-84b0-2e6ab3b5c965.png)

**Comment by isidorn** [comment] 2021-02-26 07:16
I think this is simply not supported for `files.exclude` so marking as feature request.
Thought @bpasero might know more

**Comment by bpasero** [comment] 2021-02-26 07:21
@isidorn that should work, we use a pattern like that in our workspace settings to hide derived resources:

https://github.com/microsoft/vscode/blob/909e129d6f510282cc4a2b9cb12257a128c93c7e/.vscode/settings.json#L8-L10

**Comment by isidorn** [comment] 2021-02-26 07:37
@bpasero I can actually reproduce this not working on Windows, on macOS it seems to work.
Since this also does not work for the quick pick I would think that the issue is in our `glob` matching. And since it is on windows only it is probably related to separators.

**Comment by bpasero** [comment] 2021-02-26 08:32
@isidorn there should be no platform differences and I cannot reproduce this issue, otherwise our Windows devs would see JS files in the build folder.

@alexchro93 I think you should review https://code.visualstudio.com/docs/typescript/typescript-compiling#_hiding-derived-javascript-files and see if you can still reproduce then.

**Comment by alexchro93** [comment] 2021-02-26 13:19
@bpasero thanks, I missed that this only applies to sibling files, which I'm assuming mean two files in the same directory.

For example, given the following settings:

`{
  "files.exclude": {
    "**/*.js": {
      "when": "$(basename).ts"
    },
  },
}`

If hello.ts and hello.js are in the same directory hello.js is hidden:

![image](https://user-images.githubusercontent.com/12327432/109305183-5cb0dc00-780b-11eb-803b-c25a0974b328.png)

but if i move hello.ts to a different folder (still in the workspace) hello.js is not hidden:

![image](https://user-images.githubusercontent.com/12327432/109305062-32f7b500-780b-11eb-9e90-a95d1d5b2a74.png)

I was expecting any js file with matching ts to be hidden, but looks like they must be in same directory.

**Comment by bpasero** [comment] 2021-02-26 13:22
Yes, this is specifically for derived resources in the same hierarchy.

**Closed by bpasero** 2021-02-26 13:22 UTC
Labels: feature-request
