### ISSUE TITLE
icons are not working in vscode insider and report issues under help is also not working 

### ISSUE THREAD

**Issue by nanivijay** [Microsoft/vscode#23588] opened 2017-03-29 17:05 UTC
- VSCode Version: 1.11.0-insider
- OS Version: windows 10 (15150.1001)

![image](https://cloud.githubusercontent.com/assets/5945591/24466795/03e6e152-1467-11e7-83f9-fea717c23297.png)
![image](https://cloud.githubusercontent.com/assets/5945591/24474201/b00f95d2-1480-11e7-9c3e-4d4ae2604b20.png)

**Comment by DaFri-Nochiterov** [comment] 2017-03-29 19:21
Can confirm icons not working
![image](https://cloud.githubusercontent.com/assets/10401817/24472294/647fcb5e-14ef-11e7-956b-6892c8e5ed48.png)
![image](https://cloud.githubusercontent.com/assets/10401817/24472304/6cbee3fe-14ef-11e7-8551-1e036bbeb3b1.png)

**Comment by aeschli** [comment] 2017-03-29 20:27
Please only one problem per issue. Missing icons is a duplicate of #23346.
Can you file a separate issue for the bug filing problem?

**Closed by aeschli** 2017-03-29 20:27 UTC
