### ISSUE TITLE
I got an error when I use cmd to run vscode on Windows10

### ISSUE THREAD

**Issue by Wangxiz** [Microsoft/vscode#49302] opened 2018-05-06 11:11 UTC
I got an error when I use cmd to run vscode on windows10 as follow:
```
Error: Failed opening file C:\Users\XXX\AppData\Roaming\Code\logs\20180506T185427\main.log for writing: No such file or directory
    at RotatingLogger (E:\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at Object.t.createSpdLogService (E:\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:217:588)
    at E:\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:493:687
    at Object.v [as _notify] (E:\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:82:572)
    at Object.enter (E:\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:85:924)
    at n.Class.derive._oncancel._run (E:\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:87:719)
    at n.Class.derive._oncancel._completed (E:\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:87:160)
    at Server.<anonymous> (E:\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:162:331)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1290:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[main 18:54:28] update#setState idle
[main 18:54:58] update#setState checking for updates
[main 18:54:59] update#setState idle
```

- VSCode Version: 1.23.0
- OS Version: Windows10 April 2018 Update

Steps to Reproduce:

1. Open an cmd(Windows cmd or third-party tool like Cmder);
2. Run `Code.exe` or `Code.exe filename` in the cmd;

**EDIT**: You will get the error at the first time you run `Code.exe`, but will not get another error again in the same instance of VS Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment] 2018-05-07 08:18
@Wangxiz What is your Windows user name?

**Comment by suzengyi** [comment] 2018-05-08 03:32
Same Problem，user name is garbled

**Comment by Wangxiz** [comment] 2018-05-08 06:10
my user name is "Xizao Wang"

**Comment by sandy081** [comment] 2018-05-09 12:41
@Wangxiz May I know if there are any special characters in the user name part of the following path

`C:\Users\**XXX**\AppData\Roaming\Code\logs\20180506T185427\main.log`

**Comment by Wangxiz** [comment] 2018-05-11 02:42
@sandy081 I am sorry the path `C:\Users\XXX\AppData\Roaming\Code\logs\20180506T185427\main.log` is gone, and it seems that I can't trigger this bug again...

**Comment by Wangxiz** [comment] 2018-05-11 06:05
@sandy081 Ohhh...I think I must have mistaken what you meant, but there are no special characters in XXX, and in fact, it's just "Xizao Wang".

**Comment by sandy081** [comment] 2018-05-15 08:37
Closing this as user is not able to reproduce anymore. Please reopen if it occurs again and provide us the details.

**Closed by sandy081** 2018-05-15 08:37 UTC
Labels: needs more info

**Comment by UweBoehme** [comment] 2018-06-05 13:56
Having a username with a german "ö".
```DEGUGGING-KONSOLE
Error: Failed opening file C:\Users\XXXöXXX\AppData\Roaming\Code\logs\20180605T154355\exthost7.log for writing: No such file or directory
extensionHostProcess.js:385
    at RotatingLogger (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at Object.t.createSpdLogService (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:385:293)
    at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:429:241)
    at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:738:825)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:745:480
    at <anonymous>
```
each time I try to start my extension in debuggng mode.

**Comment by sandy081** [comment] 2018-06-05 16:23
@UweBoehme your issue is related to this - 47883
