### ISSUE TITLE
Something is wrong with intergrated terminal on Windows 7 + git bash

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#52774] opened 2018-06-24 22:09 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open vscode
2. Start 3 parallel build tasks one by one
3. Switch between tasks in terminal

Actual result: first terminal works fine, second terminal is blank, third terminal might be blank or not. When terminal is blank, i think it actually works, it's just blank, but scroll bar changes size and position and i can press any key when build is finished to close this terminal.

I looked into other issues/suggestions on GitHub and configured `"terminal.integrated.rendererType": "dom",` - this seemingly helps, i didn't see this bug anymore.

My shell is git bash: `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",`. Didn't reproduce in 1.23.1.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
nightswitch-lite|gha|2.1.0
cpptools|ms-|0.17.5
vscode-todo-highlight|way|0.5.12

(1 theme extensions excluded)

</details>

**Comment by alekseyt** [comment] 2018-06-24 22:16
Additional info: this is what appears in js console when this happens:

```
[uncaught exception]: TypeError: Cannot read property 'beginFrame' of undefined index.js:41
```
```
TypeError: Cannot read property 'beginFrame' of undefined index.js:44
    at TextRenderLayer.onGridChanged (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\renderer\TextRenderLayer.js:143:24)
    at TextRenderLayer.t._measureRenderTime.n.onGridChanged (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3159:883)
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\renderer\Renderer.js:154:60
    at Array.forEach (native)
    at Renderer._renderRows (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\renderer\Renderer.js:154:28)
    at RenderDebouncer._innerRefresh (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\utils\RenderDebouncer.js:29:14)
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\utils\RenderDebouncer.js:24:88
```
```
C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\renderer\TextRe…:143 Uncaught TypeError: Cannot read property 'beginFrame' of undefined
    at TextRenderLayer.onGridChanged (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\renderer\TextRenderLayer.js:143:24)
    at TextRenderLayer.t._measureRenderTime.n.onGridChanged (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3159:883)
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\renderer\Renderer.js:154:60
    at Array.forEach (native)
    at Renderer._renderRows (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\renderer\Renderer.js:154:28)
    at RenderDebouncer._innerRefresh (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\utils\RenderDebouncer.js:29:14)
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\utils\RenderDebouncer.js:24:88
```

**Comment by Tyriar** [comment] 2018-06-27 14:52
Duplicate of https://github.com/Microsoft/vscode/issues/36913 - you should use the rendererType setting.

For the exception that's fixed in latest

**Closed by Tyriar** 2018-06-27 14:52 UTC
Labels: integrated-terminal
