### ISSUE TITLE
Askpass.js error  , Canno't commit with ssh sign ,

### ISSUE THREAD

**Issue by issam-seghir** [microsoft/vscode#168173] opened 2022-12-06 14:18 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.1
- OS Version:  21H2 (OS Budd 190442075)
Steps to Reproduce:

- ssh service state :
Status  | Name  |    DisplayName |
| --- | --- | --- |
Running  | ssh-agent  |     OpenSSH Authentication Agent |

- ssh key in ssh agent 

![image](https://user-images.githubusercontent.com/74573675/205932930-ce3446c4-ef6e-4860-afd3-c4c8e5fc130e.png)

###  GUI
![](https://i.imgur.com/5Y3kY8Z.gif)

![image](https://user-images.githubusercontent.com/74573675/205932222-af924b81-6dc6-42f2-89b3-1bfcd747924c.png)

### Vscode terminal
![image](https://user-images.githubusercontent.com/74573675/205936203-9b76bd6a-2fdf-4c6c-95f6-ac21772c8729.png)

## In PowerShell outside vscode  (expected behavior )

![image](https://user-images.githubusercontent.com/74573675/205932416-ed20ac18-2ed5-4d9a-90d8-31f4833b1f63.png)

**Comment by Issam-seghir** [comment] 2023-01-19 07:46
> @Issam-seghir, are you trying to sign you commit using your SSH key? Does the SSH key have a passphrase? Is the SSH key associated with a hardware key?

- are you trying to sign you commit using your SSH key
Yes
- Does the SSH key have a passphrase?
Yes
- Is the SSH key associated with a hardware key ?
No

**Comment by lszomoru** [comment] 2023-01-19 08:17
@Issam-seghir, thanks for getting back to me on this. I was wondering if this has ever worked in the past. Were you ever able to sign your commits in VS Code using your SSH? Trying to understand whether this is a regression that was recently introduced or whether this is something that never worked. Thanks!

**Comment by Issam-seghir** [comment] 2023-01-19 10:51
@lszomoru 
- I'm trying to sign a commit with ssh  (with a passphrase) for the first time in Vscode in version `1.73.1 ` ( so I have no experience with ssh in the past in Vscode ) 
and I face this problem which you see here and the same problem still exists in the last version today `1.74.3`

- I can only confirm that the problem only occurs when the SSH key have a passphrase

**Comment by Issam-seghir** [comment] 2023-01-21 11:20
> I have the same problem when trying to commit in GUI. I see that VS Code only supports GPG or X.509 sign keys.

 Vs code must support sign commit with SSH see  : [September 2022 : support for ssh-keys  with a passphrase](https://code.visualstudio.com/updates/v1_72#_add-support-for-ssh-keys-with-a-passphrase:~:text=Add%20support%20for%20SSH,Git%20operation%20is%20performed)

**Comment by DreamHollow** [comment] 2023-02-26 15:19
Exact same problem here.

I had a similar problem to this when using VS-Code with my Linux Mint (Cinnamon) system, but I managed to fix it.
Now I can't for the life of me remember what I did.

VS Code Git controls don't work at all for Linux Mint (XFCE) under the exact same circumstances at this user posted here.

Anyone know what causes this?
I haven't found a single reliable solution yet.

**Comment by lszomoru** [comment] 2023-12-12 09:32
Close as duplicate of https://github.com/microsoft/vscode/issues/179517

**Closed by lszomoru** 2023-12-12 09:32 UTC
Labels: bug, git
