### ISSUE TITLE
IntelliSense

### ISSUE THREAD

**Issue by 0lucs0** [microsoft/vscode#144909] opened 2022-03-11 13:26 UTC
Issue Type: <b>Performance Issue</b>

IntelliSense keeps loading for a long time, this happens as long as I have the "node_modules" folder in the project I am working on, if I remove this folder everything works normally.

Besides that, if I want to format the code of a file, create, delete a folder or file, it takes too long.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.84GB (1.55GB free)|
|Process Argv|--crash-reporter-id 84d682cc-dda7-4fee-a5ac-d9cc2d38969d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	  8556	code main
    0	    39	  2096	   utility-network-service
    0	    79	  3664	   issue-reporter
    0	   223	  6224	   gpu-process
    0	   213	 12752	   window (ScheduleAppointment.tsx - vtex.io-component-schedule-appointment-prodynamics - Visual Studio Code)
    0	   173	 13304	   window (vtex.store-components.css - Prodynamics-VTEX-B2C-MX - Visual Studio Code)
    0	   114	 15468	   shared-process
    0	    75	  3764	     fileWatcher
    0	    76	  8040	     fileWatcher
    0	    87	  9944	     ptyHost
    0	    61	  8972	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 10068	       console-window-host (Windows internal process)
    0	    61	 11600	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 13120	       console-window-host (Windows internal process)
    0	   342	 16096	   extensionHost
    0	    88	  3944	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\admin\.vscode\extensions\graphql.vscode-graphql-0.3.41\out\server\server.js --node-ipc --clientProcessId=16096
    0	    72	  7088	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\admin\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=16096
    1	   139	 15124	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\admin\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js --node-ipc --clientProcessId=16096
    1	   144	 15224	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\admin\AppData\Local\Temp\vscode-typescript\af30bd33a60d7e27b2fb\tscancellation-d7c21a004c8b2b556b63.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    89	 12656	       "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/admin/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/admin/AppData/Local/Microsoft/TypeScript/4.6 --enableTelemetry --typesMapLocation "c:/Users/admin/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation
    0	    73	 17120	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\admin\.vscode\extensions\pucelle.vscode-css-navigation-1.13.2\client\node_modules\vscode-languageclient\lib\utils\electronForkStart c:\Users\admin\.vscode\extensions\pucelle.vscode-css-navigation-1.13.2\server\out\server.js --node-ipc --clientProcessId=16096
    0	    74	 20752	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16096
    0	   114	 21592	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\admin\AppData\Local\Temp\vscode-typescript\af30bd33a60d7e27b2fb\tscancellation-7869a35307f070872349.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    26	 19860	   crashpad-handler
    0	   330	 25160	   extensionHost
    0	    75	 12296	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=25160
    0	    75	 16848	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=25160
    0	    87	 18404	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\admin\.vscode\extensions\graphql.vscode-graphql-0.3.41\out\server\server.js --node-ipc --clientProcessId=25160
    0	    73	 20280	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\admin\.vscode\extensions\pucelle.vscode-css-navigation-1.13.2\client\node_modules\vscode-languageclient\lib\utils\electronForkStart c:\Users\admin\.vscode\extensions\pucelle.vscode-css-navigation-1.13.2\server\out\server.js --node-ipc --clientProcessId=25160
    0	    72	 23348	     "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\admin\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=25160
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ScheduleAppointment.tsx - vtex.io-component-schedule-appointment-prodynamics - Visual Studio Code)
|  Window (vtex.store-components.css - Prodynamics-VTEX-B2C-MX - Visual Studio Code)
|    Folder (vtex.io-component-schedule-appointment-prodynamics): 82 files
|      File types: ts(19) sample(13) json(9) md(3) tsx(3) eslintrc(2) js(2)
|                  lock(2) editorconfig(1) eslintignore(1)
|      Conf files: package.json(2) tsconfig.json(1)
|    Folder (Prodynamics-VTEX-B2C-MX): 508 files
|      File types: jsonc(128) css(124) png(49) json(48) jpg(27) html(10)
|                  svg(3) editorconfig(2) gitignore(2)
|                  prettierignore(2)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vtexio-intellisense|Age|0.2.21
css-snippets|Aji|1.0.1
vtex-snippets|bre|0.3.3
simple-react-snippets|bur|1.2.6
emmet-jss|car|1.0.0
path-intellisense|chr|2.8.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
common-media-queries|dio|0.1.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.4
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.3.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
gitkraken-authentication|git|1.0.3
vscode-graphql|Gra|0.3.41
vscode-heroku|iva|1.2.6
pwa-tools|joh|0.1.0
vscode-pwa|may|0.7.0
git-graph|mhu|1.30.0
vscode-autoprefixer|mrm|3.0.1
notepadplusplus-keybindings|ms-|1.0.7
vsliveshare|ms-|1.0.5418
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.9.2
color-highlight|nau|2.5.0
indent-rainbow|ode|8.2.2
lowlight-go-errors|oha|1.2.4
material-icon-theme|PKi|4.14.1
vscode-css-peek|pra|4.2.0
vscode-css-navigation|puc|1.13.2
vscode-xml|red|0.19.1
markdown-preview-enhanced|shd|0.6.2
js-jsx-snippets|sky|11.0.0
lorem-ipsum|Tyr|1.3.1
highlight-matching-tag|vin|0.10.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.20

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc008:30440022
pythonvspyt640:30450904
vscscmwlcmt:30438805
vscgsvid1:30447480
pynewfile477:30450038

```

</details>

**Comment by mjbvz** [comment] 2022-03-11 19:01
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by 0lucs0** [comment] 2022-03-11 20:31
No, with the extensions disabled everything works fine. The extension that caused this problem was "VTEX IO Intellisense. Thanks

**Comment by mjbvz** [comment] 2022-03-11 20:49
Thanks for confirming. Closing as caused by that extension then

**Closed by mjbvz** 2022-03-11 20:49 UTC
Labels: needs more info, new release
