### ISSUE TITLE
Extensões

### ISSUE THREAD

**Issue by gabrielgasparini** [Microsoft/vscode#57900] opened 2018-09-04 20:50 UTC
Issue Type: <b>Bug</b>

Eu procuro por extensões como 'Laravel' e nada é encontrado.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.71GB (1.26GB free)|
|Process Argv|C:\Users\gabri\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment] 2018-09-04 20:53
Duplicate of #57851

**Closed by mjbvz** 2018-09-04 20:53 UTC
