### ISSUE TITLE
Tab to AutoComplete in TypeScript Files Doesn't Work

### ISSUE THREAD

**Issue by pjlamb12** [Microsoft/vscode#19455] opened 2017-01-26 18:20 UTC
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2 Sierra

Steps to Reproduce:

1. Set auto completion with tab to true
2. Open a TypeScript File
3. Try to use tab to auto complete something from IntelliSense

In TypeScript files, a tab is inserted instead of completing the IntelliSense suggestion.

**Comment by mjbvz** [comment] 2017-02-03 23:46
I'm unable to reproduce this issue. @pjlamb12: 

* Do you have any extensions installed? Does this happen if you launch code with `--disable-extensions`?
* Do you have any custom keybindings? 
* Does this show up in any other file types or just TypeScript?

Thanks

**Comment by mjbvz** [comment] 2017-02-07 22:56
Closing as we need more information.

@pjlamb12 Please try VSCode 1.9. If you still see this issue, please provide the above info so that I can investigate.

Thanks

**Closed by mjbvz** 2017-02-07 22:56 UTC
Labels: intellisense, needs more info, typescript

**Comment by pjlamb12** [comment] 2017-03-02 22:03
@mjbvz sorry for taking so long to get back to you.

So, the issue that I described above still occurs only in TS files but the tab to complete does work if I disable extensions. But I'm not sure why, with extensions enabled, tab to complete works with javascript files.

**Comment by pjlamb12** [comment] 2017-04-10 17:24
@mjbvz I finally got around to looking at this, and it looks like an extension was causing the issue. The extension is jakethashi.vscode-angular2-emmet, which adds Emmet functionality to the TypeScript files. When I removed that extension, it started working as expected again.
