### ISSUE TITLE
Accessible Buffer not read out by NVDA

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186444] opened 2023-06-27 21:18 UTC
Testing #186218

* turn on NVDA
* chat a bit with Copilot
* alt+f1

<img width="2085" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/40a61486-8b76-45c2-9503-2e4d7efd5c5f">

You can see nothing is read out and moving my cursor around the buffer nothing is read out either.

**Comment by meganrogge** [comment] 2023-06-27 21:21
@TylerLeonhardt if you move your cursor around in a normal editor, does it read the contents of that?

**Comment by TylerLeonhardt** [comment] 2023-06-27 21:27
It says "unknown"

**Comment by meganrogge** [comment] 2023-06-27 21:30
Ah ok, so that means there's an issue with the screen reader config - not specific to the accessible view. That makes sense as the accessible view is just a monaco editor, so inherits all of the screen reader content from there.

**Comment by meganrogge** [comment] 2023-06-27 21:31
Sometimes when the speech viewer is shown, screen reader behavior goes awry. Could you try without that?

**Comment by TylerLeonhardt** [comment] 2023-06-27 21:37
I have closed the speech viewer and reloaded the window but the same issue happens.

**Comment by meganrogge** [comment] 2023-06-27 21:57
Since we cannot debug screen readers in VMs, I will close this. Pls reopen if it reproduces on a machine where NVDA works when in a normal editor.

**Closed by meganrogge** 2023-06-27 21:57 UTC
Labels: info-needed
