### ISSUE TITLE
node and node2 should support evaluateName field

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#22945] opened 2017-03-21 09:30 UTC
Currently VSCode uses this [ugly heuristic](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L280) to get the parent chain of a variable. We need to get rid of this heuristic since VSCode should be language agnostic and we already have a [field in our protocol](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1168) that represents this.

I suggest that node and node2 start supporting this. Once we have that we can notify other debug adapter writers about this field with the goal of droping this heuristic in April.

An example where this field is used: adding a variable from the variables view to a watch list or copying a variable value to the clipboard(we first evaluate it using the parent chain)

**Comment by roblourens** [comment] 2017-04-08 03:29
node2 has supported this for awhile. Nothing is new right?

**Comment by isidorn** [comment] 2017-04-10 08:31
Great Rob. 
Yes, nothing is new. I was only pushing for getting rid of the ugly heurstic linked in the above comment.

@weinand can we simply drop the heuristic and state to debug adapters if they want to support `add to watch` and `copy value` actions they have to support `evaluateName` field?

**Comment by weinand** [comment] 2017-04-10 08:34
@isidorn we should announce in the April release that we will drop the legacy code in May.

**Comment by isidorn** [comment] 2017-04-10 08:42
I have added it to the release notes to not forget about it later. Then I will remove the heuristic in May.

**Comment by weinand** [comment] 2017-04-10 08:53
'legacy' does not yet support evaluateName.

**Comment by weinand** [comment] 2017-04-21 13:10
duplicate of #14846

**Closed by weinand** 2017-04-21 13:10 UTC
Labels: debt, debug
