### ISSUE TITLE
allThreadsContinued not respected

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33839] opened 2017-09-05 11:03 UTC
_From @DatGuyJonathan on August 31, 2017 22:0_

I'm working on a debugger extension that supports multiple stopped threads. When the user clicks 'continue', the debug adapter (DA) handles continueRequest with the backend and responds to VS Code with allThreadsContinued = false. The backend will eventually notify DA that the thread has finished, so DA sends a ThreadEvent with reason 'exited' to VS Code.

If I have multiple stopped threads and perform 'continue' on one of them, VS Code removes all the threads from the call stack view. My workaround is to send a stopped event to VS Code for every thread that the DA knows about, but that seems expensive because the DA will have to handle stackTraceRequest for threads that haven't changed.

Is that workaround the expected behavior from DA?

Here are the versions I'm working with:
VS Code: 1.15.0
vscode-debugadapter & vscode-debugprotocol: 1.22.0

_Copied from original issue: Microsoft/vscode-debugadapter-node#130_

**Comment by weinand** [comment] 2017-09-05 11:03
I will move this to VS Code, since the issue is about a client implementation problem.

**Comment by isidorn** [comment] 2017-09-06 08:05
The `ThreadEvent` with reason exited will only remove one thread which can be seen [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L298)

@DatGuyJonathan I believe the only issue you are seeing is that the `continue` event continues all threads. This is expected default behavior, in order to only continue one thread please send a `ContinuedEvent` with [`allThreadsContinued = false`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L106)

Closing this as designed. Let me know if things still do not work for you and I will reopen. Also be sure to try with latest [vscode insiders](https://code.visualstudio.com/insiders). Thanks

**Comment by DatGuyJonathan** [comment] 2017-09-07 22:49
Thanks for the prompt response @isidorn . I use `allThreadsContinued: false` as seen [here](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts#L245). It is not in a ContinuedEvent, but rather in the response of continueRequest because the protocol says ContinuedEvent is not required. I can still repro the issue if I send a ContinuedEvent and also with the latest vscode-insiders.

**Comment by isidorn** [comment] 2017-09-08 08:33
@DatGuyJonathan ok in that case we have two options
1. You give me the steps how to setup your debugger on my mac machine
2. You run vscode out of source as specified [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) you add your extension to the out of source setup and place a breakpoint in these locations and let me know what you find out
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L314
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L204
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L271

**Comment by DatGuyJonathan** [comment] 2017-09-08 21:54
@isidorn , I was using zero-based thread IDs which made clearThreads() in debugModel.ts remove all threads when I continue or thread-exit the first stopped thread.
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L616

I can fix this on my side to use one-based ID. Maybe that if-statement should be updated as well :)

**Comment by isidorn** [comment] 2017-09-12 09:19
@DatGuyJonathan that if statement should be updated :)

**Closed** 2017-09-12 09:23 UTC
Labels: bug, debug

**Comment by weinand** [comment] 2017-09-29 09:48
Verified by code inspection.
