### ISSUE TITLE
There is an extra % in my Terminal output.

### ISSUE THREAD

**Issue by OOOHA** [microsoft/vscode#114715] opened 2021-01-21 16:50 UTC
Issue Type: <b>Bug</b>

I use code runner to run my C file.
There are always got a % at the and of the output.
Every time I launch VS code my terminal always looks like
%
username@user'sMacBook-Pro Program%

It looks very different form the old version Mac OS.
It was like cd/file's place/.......
It shouldn't start from a %.
I'm using Big Sur 11.1

 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id 3f12e0b1-128d-4528-9fb3-29fc2b9c754f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|12.1.4
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
c-cpp-compile-run|dan|1.0.13
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.1.3
vscode-html-css|ecm|1.9.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
git-project-manager|fel|1.7.1
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.2
vscode-javac|geo|0.2.37
vscode-tree-sitter|geo|0.1.26
vscode-pull-request-github|Git|0.22.0
go|gol|0.21.0
go-nightly|gol|2021.1.2021
todo-tree|Gru|0.0.196
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.5
flutter-tree|mar|1.0.0
git-graph|mhu|1.28.0
Angular-BeastCode|Mik|10.0.3
vscode-clang|mit|0.2.3
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
vscode-pylance|ms-|2021.1.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3484
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
debugger-for-chrome|msj|4.12.11
java|red|0.74.0
LiveServer|rit|5.6.1
document-tree|sac|1.0.1
code-spell-checker|str|1.10.2
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
windows-terminal|Tyr|0.6.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
vstes627:30244334
pythonvspyt875:30247033

```

</details>

**Comment by meganrogge** [comment] 2021-01-21 19:18
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by OOOHA** [comment] 2021-01-22 07:42
/label "needs more info" integrated-terminal

settings json
{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "vscode-icons",
    "code-runner.runInTerminal": true,
    "window.zoomLevel": 2,
    "C_Cpp.updateChannel": "Insiders",
    "python.jediEnabled": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.errors.incompleteClasspath.severity": "ignore",
    "todo-tree.tree.showScanModeButton": false,
    "code-runner.saveFileBeforeRun": true,
    "cSpell.language": "en,en-US",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "python.languageServer": "Pylance"
}
<img width="549" alt="截圖 2021-01-22 下午3 38 13" src="https://user-images.githubusercontent.com/45551120/105461360-132f1780-5cc8-11eb-958f-1ebd05f6cb1b.png">
<img width="510" alt="截圖 2021-01-22 下午3 38 37" src="https://user-images.githubusercontent.com/45551120/105461365-14f8db00-5cc8-11eb-9e47-ebb5f7736639.png">
<img width="1106" alt="截圖 2021-01-22 下午3 38 56" src="https://user-images.githubusercontent.com/45551120/105461369-162a0800-5cc8-11eb-9297-53f12c696a13.png">



Are these information enough? 
Or should I add more.

**Comment by meganrogge** [comment] 2021-01-22 18:02
when did this start happening for you?

**Comment by OOOHA** [comment] 2021-01-23 08:01
It starts from December 2020 after I update my laptop.

Before it should just look like 
<img width="341" alt="截圖 2021-01-23 下午4 01 08" src="https://user-images.githubusercontent.com/45551120/105572772-38895780-5d94-11eb-9f2c-d3fcbb28a41c.png">

**Comment by meganrogge** [comment] 2021-01-25 17:29
what happens if you change the renderer type and font?

**Comment by OOOHA** [comment] 2021-01-28 14:40
It's still there, can't solve the problem.
Any other recommend way to solve it?

**Comment by meganrogge** [comment] 2021-01-28 17:16
looks like this is a duplicate of #69636 , you can try the suggestions found there.

**Closed** 2021-01-28 17:16 UTC
Labels: *duplicate, integrated-terminal
