### ISSUE TITLE
Accessibility: Lag when reading a long file using the NVDA screen reader

### ISSUE THREAD

**Issue by yncat** [microsoft/vscode#120797] opened 2021-04-08 08:25 UTC
Issue Type: <b>Bug</b>

(1) make a 1100-line text file which contains "1" to "1100" separated by a newline. The content does not matter; it just needs to be longer than 1000 lines.
(2) Open the file using Visual Studio Code.
(3) Go to the 999th line and try to read the previous and next lines by using up / down arrows. There is a 500 to 700ms lag approximately here.
(4) Go to the 1001st line. There is no lag at all. 
(5) Same can be applied at line 1999 to 2001, line 2999 to 3001 and so on.
(6) Note: Changing editor.accessibilityPageSize to 1 seems to eliminate the lag, but my understanding is that it is a temporary solution.

VS Code version: Code - Insiders 1.56.0-insider (bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a, 2021-04-07T12:30:14.880Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.28GB free)|
|Process Argv|--crash-reporter-id 4cbda999-3df6-44c7-a9cd-c0f42279cba9|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment] 2021-04-08 18:09
@yncat thanks a lot for letting us know. This is discussed here https://github.com/microsoft/vscode/issues/41423

My question for you, if you add `editor.accessibilityPageSize: 200` to your settings do you still see the lag?
If yes, what seems to be the largest number for which you do not see the lag

Also thanks for using Insiders 👏

**Comment by yncat** [comment] 2021-04-09 02:50
Hello @isidorn . Thank you for your response!

First of all, if this issue needs to be discussed at #41423, please let me know.

I tested the performance with different page sizes. Here are what I've found so far:
Note: I'm setting the page size to a certain value, then trying cursor movement near the boundary of the pages (line 498 to 502 when page size is 500).
- the lag is almost not noticeable until page size / line 500.
- As the value goes higher than 500, it starts to lag. Increase of the latency is obvious while I haven't noticed any performance issues when testing with 1 to 500.

I've also read the previously discussed issues. Is it correct that the latency is still caused by the textarea performance issue of Chromium?

I can still efficiently use VSCode by adjusting the page size option, so there's no urgent problem here. However, if the page size option will be deprecated in the near future, I would like the issue to be addressed before completely dropping the setting.

**Comment by isidorn** [comment] 2021-04-09 09:49
Yeah, let's continue the discussion there  #41423 and let's close this one as a duplicate.
Yes, latency is still caused by https://bugs.chromium.org/p/chromium/issues/detail?id=1076525

Due to this issue, we will actually not deprecate the pageSize setting. Once that issue gets fixed, we will remove it.
I was just asking these questions to find a good default for the pageSize setting, currently it is 500.

**Closed by isidorn** 2021-04-09 09:49 UTC
Labels: accessibility, under-discussion
