### ISSUE TITLE
vscode no response with specified comment format

### ISSUE THREAD

**Issue by chengleiwang** [microsoft/vscode#76919] opened 2019-07-09 01:34 UTC
Issue Type: <b>Bug</b>

1. save this comment into a file  /***************************** Don't support in 8.0 start**************************************/
2. issue blackspace or tab key at the begging of this comment.
3. vscode will crash.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-54-generic
Remote OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Ubuntu-dev|
|OS|Linux x64 4.15.0-54-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 800)|
|Memory (System)|15.47GB (5.00GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Ubuntu-dev|
|OS|Linux x64 4.15.0-54-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 800)|
|Memory (System)|15.47GB (5.00GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cudacpp|kri|0.1.1
vscode-docker|ms-|0.6.4
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.8
vscode-remote-extensionpack|ms-|0.15.0
code-gnu-global|aus|0.2.2
bazel-code|Dev|0.1.9
gitlens|eam|9.8.2
python|ms-|2019.6.22090
cpptools|ms-|0.24.0
cmake|twx|0.0.17

</details>

**Comment by matter123** [comment] 2019-07-09 04:28
This should be fixed in the upstream textmate grammar with version v1.12.15 of https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax.

Vscode 1.36.1 should fix the issue. Alternatively, if you want the fixe immediately, install the Better C++ Syntax extension.

**Comment by alexr00** [comment] 2019-07-09 07:47
As @matter123 said!
Duplicate of #76774
We rolled back the C++ grammar version match 1.35 so this will be fixed in 1.36.1. It is also already fixed in Insiders.

**Closed by alexr00** 2019-07-09 07:47 UTC
