### ISSUE TITLE
Wrong YAML syntax highlighting

### ISSUE THREAD

**Issue by iatsiuk** [Microsoft/vscode#69171] opened 2019-02-21 21:13 UTC
- VSCode Version: 1.31.1
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Create a new YAML file
2. Paste this [test.yml.zip](https://github.com/Microsoft/vscode/files/2891325/test.yml.zip) file

Preview of the current syntax highlighting:
<img width="580" alt="screen" src="https://user-images.githubusercontent.com/24681814/53202075-3eb5ad00-362e-11e9-865a-a29b08e02a67.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by iatsiuk** [comment] 2019-02-21 21:19
Please take a look at the color of `-H 'Content-Type:` (line 4) and at the color of closing curly brace (line 7).

**Comment by iatsiuk** [comment] 2019-02-21 21:26
Preview of the syntax highlighting from sublime text 3:
<img width="438" alt="screenshot 2019-02-21 at 23 25 09" src="https://user-images.githubusercontent.com/24681814/53202773-07480000-3630-11e9-8e7c-1dabbc14bd3f.png">

**Comment by mhubig** [comment] 2019-02-26 19:02
Same problem here, VS Code rendering a gitlab-ci.yml file vs Atom rendering the same file:
<img width="1071" alt="screenshot 2019-02-26 19 58 26" src="https://user-images.githubusercontent.com/219704/53438810-ff59d880-3a00-11e9-9adc-1c7f2b001e53.png">
<img width="1070" alt="screenshot 2019-02-26 19 58 32" src="https://user-images.githubusercontent.com/219704/53438809-fec14200-3a00-11e9-9012-e46b18f66c10.png">

**Comment by alexr00** [comment] 2019-03-22 12:12
duplicate of #50140

**Closed** 2019-03-22 12:12 UTC
Labels: *duplicate, grammar
