### ISSUE TITLE
Restart to Update does not return

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#42835] opened 2018-02-02 16:48 UTC
### Issue Type
Bug

### Description

In the last couple of weeks I had 3 occassions in which "Restart to Update" did not return. I don't have any reproducible case yet. However, what I observed is:

- When Code is not coming up and I run `htop`, I see that a squirrel update process is running.
- I can not kill the process. I.e. when I kill it, it immediately respawns.
- When I restart VS Code, I get the old version. I get notified about an available update, and when I restart it  doesn't come up. I.e. I can not get out of that state, once I'm in it.
- When I reboot my machine (and afterwards no squirrel update process is running) I can update successfully.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (7636a7d6f7d2749833f783e94fd3d48d6a1791cb, 2018-02-02T11:14:28.251Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|3, 6, 3|
|Memory (System)|16.00GB (8.29GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_249917|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by joaomoreno** [comment] 2018-02-02 17:01
Never seen this before. The process just stays there? No CPU usage? Does it always reproduce? Did you install something new in your system lately? Maybe some antivirus?

**Comment by kieferrm** [comment] 2018-02-02 17:51
- The squirrel process just sits there. No CPU usage.
- If I kill it, and it immediately respawns.
- Once I'm in that state, yes it plays out as described, but it does not happen on every update.

**Comment by qiangli** [comment] 2018-08-29 18:44
Noticing the ghost vscode process only now on Activity Monitor. The update never returned for me since day one, thought that's the way it is; I had to restart manually.
I could not kill the process either, only way is to reboot.
on macOS Sierra v 10.12.6

**Comment by joaomoreno** [comment] 2018-09-27 13:28
@kieferrm Has this been an issue still?

**Comment by joaomoreno** [comment] 2018-12-12 14:45
@ghprince That was https://github.com/Microsoft/vscode/issues/64739

Closing this one.

**Closed by joaomoreno** 2018-12-12 14:45 UTC
Labels: bug, install-update, mac
