### ISSUE TITLE
Smooth Scrolling Enabled but...

### ISSUE THREAD

**Issue by svzax** [microsoft/vscode#96998] opened 2020-05-05 13:51 UTC
Issue Type: <b>Bug</b>

I have checked smooth scrolling in the settings, and I have seen that "editor.smoothScrolling": true, but when I scroll sometimes it is sometimes smooth, even though smooth scrolling is active.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.84GB (8.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
material-icon-theme|PKi|4.1.0
java|red|0.61.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment] 2020-05-06 15:50
@svzax Can you please provide reproducible steps?

**Comment by svzax** [comment] 2020-05-07 00:21
I have found this problem, and this has not only happened to me. The
problem is in Windows 10 scaling.

If the scaling is at 100% then smooth scrolling will work perfectly. Beyond
that, smooth scrolling does not work at all.

I have tested, scaling at 125%, 150%, and 170% on the FHD monitor, and
smooth scrolling does not work.

**Comment by alexdima** [comment] 2020-05-07 08:29
Thank you for the extra information. Duplicate of #35711

**Closed by alexdima** 2020-05-07 08:29 UTC
Labels: needs more info
