### ISSUE TITLE
The settings menu has gone

### ISSUE THREAD

**Issue by Mossop** [microsoft/vscode#75006] opened 2019-06-06 17:40 UTC
Issue Type: <b>Bug</b>

On the latest insider build the menu item to get to settings has vanished. I can still get to it through the command palette.

VS Code version: Code - Insiders 1.36.0-insider (7a5bca9fafbbb23de289179be95e9c4832540c02, 2019-06-06T11:36:26.351Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 20, 36|
|Memory (System)|32.00GB (10.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|1.9.0
vscode-html-css|ecm|0.2.0
backticks|fra|1.4.0
vscode-webidl|keq|0.0.1
python|ms-|2019.5.18678
remote-ssh|ms-|0.42.0
remote-ssh-edit|ms-|0.42.0
remote-ssh-explorer|ms-|0.42.0
cpptools|ms-|0.23.1
idl|myt|0.3.1
autotrim|Nat|1.0.6
material-icon-theme|PKi|3.8.0
rust|rus|0.6.1
vscode-hexdump|sle|1.7.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-06-06 18:07
Duplicate of #74949

**Closed by mjbvz** 2019-06-06 18:07 UTC
