### ISSUE TITLE
VSCode UI Right click overflow bug

### ISSUE THREAD

**Issue by Jonatthu** [Microsoft/vscode#54908] opened 2018-07-23 22:23 UTC
- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set Settings "window.titleBarStyle": "custom",
2. Right click almost in the bottom of vscode on a file with code

![vscodebug](https://user-images.githubusercontent.com/3742176/43106061-ed6c64ec-8e8b-11e8-819f-b78a4bdf186f.jpg)

**Comment by sbatten** [comment] 2018-07-26 16:58
duplicate of #52533

**Closed by sbatten** 2018-07-26 16:58 UTC
Labels: workbench-title
