### ISSUE TITLE
VS Code , MacOS External Monitor Flickering

### ISSUE THREAD

**Issue by Rahkovsky** [microsoft/vscode#75205] opened 2019-06-10 15:23 UTC
Issue Type: <b>Bug</b>

Hi,
My problem is VC Code flickering. 

I am using MacOS and VS Code and Mac Os. I am using external monitor hooked via HDMI. My monitor is LG 34UD79-B. 

I looked at all dicussions. I tried:
 code --ignore-gpu-blacklist
code --disable-gpu
And I added in settings.json:
"editor.disableTranslate3d": true 

Though the VS Code does not recognize this setting. 

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (10.05GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
shell-format|fox|6.0.0
python|ms-|2019.5.18875

</details>

**Comment by egamma** [comment] 2019-06-11 07:11
@deepak1556 could this be an electron issue?

**Comment by deepak1556** [comment] 2019-10-07 21:34
Duplicate of https://github.com/microsoft/vscode/issues/74098

**Closed** 2019-10-07 21:34 UTC
Labels: *duplicate
