### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by piotrpalek** [microsoft/vscode#139797] opened 2021-12-27 10:55 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1. Opened latest vscode

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`/home/awpeter/.vscode-server/data/logs/20211227T114724/exthost1/vscode.typescript-language-features/tsserver-log-K5qhuU/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at resolveEntityName (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49461:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49413:24)
    at getTargetOfImportEqualsDeclaration (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:48865:28)
    at getTargetOfAliasDeclaration (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49232:28)
    at resolveAlias (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeSymbol (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47648:21)
    at /home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeModuleAugmentation (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47753:17)
    at initializeTypeChecker (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:85046:25)
    at Object.createTypeChecker (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Object.getProgram (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/home/awpeter/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.25GB free)|
|Process Argv|--crash-reporter-id 20cbf34e-c344-48ee-b99e-4d71ab5bca8f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (5 x 2208)|
|Memory (System)|5.81GB (0.79GB free)|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
auto-close-tag|for|0.5.12
vscode-glimmer-syntax|lif|1.0.5
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.202.4
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-ssh-explorer|ms-|0.56.0
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
slim|sia|0.1.2
mdx|sil|0.1.0
vscode-autohotkey|sle|0.2.2
highlight-matching-tag|vin|0.10.1
vim|vsc|1.21.8
vscode-ruby|win|0.28.0
vscode-tailwindcss|bra|0.7.1
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
dart-code|Dar|3.27.2
flutter|Dar|3.27.0
vscode-eslint|dba|2.2.1
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
vscode-power-mode|hoo|2.2.0
generate-index|kin|0.2.0
template-string-converter|meg|0.5.3
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.1
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
synthwave-vscode|Rob|0.1.10
slim|sia|0.1.2
svelte-vscode|sve|105.4.2
docker|vsc|1.0.0
yaml|vsc|1.0.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30414010
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by piotrpalek** [comment] 2021-12-27 11:03
seems to be similar to https://github.com/microsoft/vscode/issues/139787

**Comment by IllusionMH** [comment] 2021-12-28 06:58
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

**Closed** 2021-12-28 06:59 UTC
Labels: *duplicate
