### ISSUE TITLE
Go To Definition centers the definition in the editor viewport

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#22882] opened 2017-03-20 14:37 UTC
This is generally cool, but if the definition of a symbol (function, for example) is _taller_ than the editor view, its function declaration stays off-editor.

![kapture 2017-03-20 at 15 36 54](https://cloud.githubusercontent.com/assets/22350/24104682/1b56bd8e-0d83-11e7-8275-d9c5dc7e2478.gif)

**Comment by eamodio** [comment] 2017-03-22 20:06
Somewhat related when opening the references (via CodeLens), if the peek UI it too tall it scrolls off the top rather than the bottom.

![mar-22-2017 16-06-08](https://cloud.githubusercontent.com/assets/641685/24218383/85110918-0f19-11e7-856a-d940d2dbe072.gif)

**Comment by mjbvz** [comment] 2017-04-06 23:57
Adding @jrieken on this since this issue is not specific to TS/JS. I may try adding a workaround in our TS extension, similar to what is discussed in #23924

I think the expected behavior here would be:

* If the defined range is shorter than the screen, center it when you go to the definition
* Otherwise, show the first line of the range on the first visible line of the editor

**Comment by jrieken** [comment] 2017-04-24 09:29
actually a dupe of https://github.com/Microsoft/vscode/issues/22896

**Closed by jrieken** 2017-04-24 09:29 UTC
Labels: bug, editor-contrib
