### ISSUE TITLE
I suspect typescript is having trouble with multiple tsconfig files in one window

### ISSUE THREAD

**Issue by ubershmekel** [Microsoft/vscode#32583] opened 2017-08-15 19:10 UTC
I think the crashing started after installing `vetur`.

- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|4.3.3
LogFileHighlighter|emi|1.1.1
flow-for-vscode|flo|0.7.1
terraform|mau|0.0.16
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.2
vetur|oct|0.9.3
java|red|0.8.0
bash-debug|rog|0.1.0
vscode-hexdump|sle|1.4.0
gitblame|wad|2.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment] 2017-08-16 13:31
@ubershmekel Please provide more information. Sample project, what do you see, what do you expect.

**Comment by ubershmekel** [comment] 2017-08-16 18:44
I got these errors in vs code:

> The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. [Close]

> The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. [Report Issue]

I clicked `Report Issue` which created this github issue. Note there is no "Dismiss" button - it practically forces you to visit the github issue creation page.

This is what appears in the `Output` window.

```
[Error  - 11:09:08 AM] 'getApplicableRefactors' request failed with error.
Error: Service died.
    at TypeScriptServiceClient.serviceExited (/Users/yuval/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:400:32)
    at ChildProcess.childProcess.on (/Users/yuval/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:311:30)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 11:09:50 AM] TSServer exited
[Info  - 11:09:50 AM] Using tsserver from: /Users/yuval/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 11:09:50 AM] Forking TSServer
PATH: /Users/yuval/Library/Python/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS
[Info  - 11:10:33 AM] TSServer exited
[Info  - 11:10:33 AM] Using tsserver from: /Users/yuval/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 11:10:33 AM] Forking TSServer
```

I was later able to get this output as well:

```vetur initialized
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::AbstractCode>) [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::internal::Factory::NewJSFixedArrayIterator(v8::internal::Handle<v8::internal::FixedArray>) [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: v8::internal::Factory::NewJSFixedArrayIterator(v8::internal::Handle<v8::internal::FixedArray>) [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: v8::internal::compiler::SourcePositionTable::Print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: v8::internal::compiler::SourcePositionTable::Print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::compiler::SourcePositionTable::Print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::compiler::SourcePositionTable::Print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Users/yuval/Downloads/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0xcd6004843a7
15: 0xcd60048474d
16: 0xcd600ac1bc6
17: 0xcd600a6f08c
18: 0xcd600a6f8e5
19: 0xcd600c3a612
[Info  - 11:22:51 AM] Connection to server got closed. Server will restart.```

My machine has 16GB physical memory and only 11.35 is used when this happened.

I tried to reproduce the issue a few ways. Copying the code workspace did not reproduce the typescript server crash, it did reproduce the vue server crash. I'm giving up on figuring this one out. I'll just stick to react and flow for this project. Feel free to close this issue. Thanks.

**Comment by mjbvz** [comment] 2017-08-17 17:42
Thanks for the quick followup. 

If this only repos when you have `Veture` enabled, please try filing an issue against that extension. Closing this issue as caused by extension. Please let me know if you hit this bug again with extensions disabled.

**Closed by mjbvz** 2017-08-17 17:42 UTC
Labels: caused-by-extension, new release
