### ISSUE TITLE
my code space is not loading my files

### ISSUE THREAD

**Issue by L1NM** [microsoft/vscode#196164] opened 2023-10-21 13:08 UTC
ADD ISSUE DESCRIPTION HERE

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Embedder: codespaces

 my code space is opening but it is not loading my directories or even a terminal

**Comment by hlovdal** [comment] 2023-10-21 18:14
There is not very much information to help understand what the problem is. Could you attach screenshots with what you got and describe hos those differ from what you expected?

**Comment by lramos15** [comment] 2023-12-15 18:12
Closing due to lack of updated info

**Closed by lramos15** 2023-12-15 18:12 UTC
Labels: info-needed
