### ISSUE TITLE
Can't open the vscode on CentOS & Arch that was due to lack of the libXss.so.1 

### ISSUE THREAD

**Issue by ClaireKang** [Microsoft/vscode#15325] opened 2016-11-11 02:07 UTC
- VSCode Version: 1.7.1
- OS Version: CenOS7; Arch

Steps to Reproduce:

1. Download the vscode(.rpm or .tar.gz) and try to open the vscode
2. Open the vscode with the Command

Expected:
The vscode can be open correctly.

Actual:
The vscode can't be open. when I tried open it with command, it pop up a following error message:
![vscode](https://cloud.githubusercontent.com/assets/20184768/20201828/e21e5326-a7f5-11e6-8a62-23cb280c3b8b.PNG)

Investigation:
The issue can reproduce on CentOS and Arch, I tried install the libXss.so.1 with the 'sudo yum install libXScrnSaver libXScrnSaver-devel' in cmd, and I tried to open the vs, it can be open normally.

**Comment by polygotdev** [comment] 2016-11-11 03:27
@ClaireKang to satisfy the library requirement of ```libXss.so.1``` for the ```x86_64``` architecture, try:
```
sudo yum install libXScrnSaver.x86_64
```

**Comment by Tyriar** [comment] 2016-11-11 05:18
Thanks @polygotdev. Also we recommend installing via the community maintained AUR repository for Arch Linux https://aur.archlinux.org/packages/visual-studio-code/

Closing this as a duplicate of https://github.com/Microsoft/vscode-docs/issues/369

**Closed by Tyriar** 2016-11-11 05:18 UTC

**Comment by kenrachynski** [comment] 2016-11-17 04:38
I just ran into this on a fresh RHEL7 installation and noticed that vscode 1.7.1 x86_64 is asking for i686 dependencies instead of x86_64 dependencies and all the x86_64 dependencies were already installed anyway.

**Comment by polygotdev** [comment] 2016-11-17 20:44
hey @kenrachynski 

It should be taken care of in the next release. A run-thru on RedHat 7.2 illustrated below:

```bash
[mockbuild@localhost Downloads]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

[mockbuild@localhost Downloads]$ ls
code-insiders-1.8.0-1479385401.el7.x86_64.rpm

[mockbuild@localhost Downloads]$ sudo rpm -ivh code-insiders-1.8.0-1479385401.el7.x86_64.rpm 
[sudo] password for mockbuild: 
Preparing...                          ################################# [100%]
Updating / installing...
   1:code-insiders-1.8.0-1479385401.el################################# [100%]


[mockbuild@localhost Downloads]$ code --version
bash: code: command not found...


[mockbuild@localhost Downloads]$ code-insiders --version
1.8.0-insider
043310affe454f94c665494b77818c1425cbe8db


```

**Comment by kenrachynski** [comment] 2016-11-17 23:14
Alright, I'll wait for 1.8 to hit the public

**Comment by kwmiebach** [comment] 2017-03-15 13:28
On debian 8 (and probably ubuntu), to satisfy the library requirement of libXss.so.1 try:

`sudo apt install libxss1`
