### ISSUE TITLE
macOS 10.12: background artifacts

### ISSUE THREAD

**Issue by realmx** [Microsoft/vscode#11533] opened 2016-09-05 09:27 UTC
- VSCode Version: 1.5.0-insider
- OS Version: macOS Sierra 10.12 Beta

Steps to Reproduce:

1. see screenshot
<img width="586" alt="111" src="https://cloud.githubusercontent.com/assets/6071313/18243497/da304e7c-738d-11e6-89d0-4cbaac386e72.png">
<img width="284" alt="222" src="https://cloud.githubusercontent.com/assets/6071313/18243504/df6ffe5a-738d-11e6-9fe8-ca2acb2e9f67.png">
<img width="1920" alt="333" src="https://cloud.githubusercontent.com/assets/6071313/18243508/e2b580d0-738d-11e6-865c-9fdb7a03793d.png">
<img width="1920" alt="444" src="https://cloud.githubusercontent.com/assets/6071313/18243511/e786e784-738d-11e6-9df5-9b667f4a9400.png">

**Comment by bpasero** [comment] 2016-09-05 15:12
This looks like an upstream issue with VS Code. We plan to update our Electron version and hopefully the Chrome update within improves situation for macOS 10.12.

**Comment by bpasero** [comment] 2016-09-14 10:05
@realmx we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment] 2016-09-14 10:05
@realmx we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by realmx** [comment] 2016-09-14 13:31
@bpasero not repaired 🙄
![111](https://cloud.githubusercontent.com/assets/6071313/18514046/9434457c-7ac2-11e6-8f99-a27521e75ef9.png)
![222](https://cloud.githubusercontent.com/assets/6071313/18514054/97a701ae-7ac2-11e6-9cdb-d5efb7d72c2a.png)

**Comment by bpasero** [comment] 2016-09-14 14:20
Crazy. And this is with latest Sierra I guess?

**Comment by realmx** [comment] 2016-09-14 15:57
@bpasero yes yes

**Comment by bpasero** [comment] 2016-09-23 05:33
@realmx running with `--force-gpu-rasterization` from command line should fix it. Closing as duplicate of https://github.com/Microsoft/vscode/issues/12473

**Closed by bpasero** 2016-09-23 05:33 UTC
Labels: bug, electron-update, upstream
