### ISSUE TITLE
"folder" codicon doesn't show up in tree view

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#119028] opened 2021-03-15 23:44 UTC
- VS Code Version: 1.55.0-insider
- OS Version: Darwin x64 20.3.0

Steps to Reproduce:

When using `ThemeIcon('folder')` as a tree item's `iconPath`, the folder icon doesn't appear. This isn't the case for other codicons.

<img width="205" alt="Screen Shot 2021-03-15 at 4 39 33 PM" src="https://user-images.githubusercontent.com/22795803/111235252-83ae3280-85ad-11eb-9c1f-0abf6b90573f.png">

Here's a simple extension that demonstrates this: https://github.com/wwlorey/icon-example

Does this issue occur when all extensions are disabled?: N/A

**Comment by alefragnani** [comment] 2021-03-16 04:02
Hi @wwlorey ,

Does the **File Icon Theme** you have selected on VS Code, has a `folder` icon (take a look at Explorer)? 

I mean, by default you can choose between `None`, `Minimal` and `Seti` file icon themes, but only `Minimal` has a `folder` icon. So, if your current setting is defined to `None` or `Seti` (or any other theme that don't have a folder icon), those _folder TreeItems_ will not show any icon at all.

Hope this helps

**Comment by isidorn** [comment] 2021-03-16 07:55
Looks like duplicate of https://github.com/microsoft/vscode/issues/119050
Let's close and continue the discussion there

**Closed by isidorn** 2021-03-16 07:55 UTC
