### ISSUE TITLE
unable to open any file to edit

### ISSUE THREAD

**Issue by tehyflax** [microsoft/vscode#95629] opened 2020-04-19 08:45 UTC
Issue Type: <b>Bug</b>

'assertion failed:argument is undefined or null',
'cannot read property other of null' type errors

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment] 2020-04-19 09:16
Do you have any extensions installed? If yes, please retest after disabling them all.

**Comment by chrmarti** [comment] 2020-04-20 11:40
@tehyflax Could you check if there is anything in the console? (`Help` > `Toggle Developer Console`)

(Similar to #95572.)

**Comment by bpasero** [comment] 2020-04-20 14:24
Sounds like https://github.com/microsoft/vscode/issues/94931

**Comment by alexdima** [comment] 2020-04-25 13:37
Duplicate of #94931. 

The workaround is to install [VS Code Insiders](https://code.visualstudio.com/insiders/) and then open the file at `C:\Users\[your-name]\AppData\Roaming\Code\User\settings.json` and remove any settings that were set to be `null`.

**Closed by alexdima** 2020-04-25 13:37 UTC
Labels: needs more info

**Comment by darksparks999** [comment] 2020-05-07 15:04
I did a fresh install of VSCode 1.44.2.  Worked fine.  Then I added the C/C++ extension.  After a few minutes, I started receiving the "cannot read property other of null" errors when attempting to open or create files.  Opened settings.json, found that editor.quickSuggestions was set to NULL.  Removed it and all is working properly.

Clearly the editor.quickSuggestions entry was added and set to NULL by the C/C++ extension.  FYI!

**Comment by alexdima** [comment] 2020-06-04 12:09
@sean-mcmanus Can you please double check that the C++ extension is not writing `"editor.quickSuggestions": null` to user settings?

**Comment by sean-mcmanus** [comment] 2020-06-04 18:23
@alexdima @darksparks999 Our C/C++ extension makes no reference to "quickSuggestions" at all. See https://github.com/microsoft/vscode-cpptools/tree/master/Extension (last time we did was 2017). The closest thing we have in package.json is
```
    "configurationDefaults": {
      "[cpp]": {
        "editor.wordBasedSuggestions": false,
        "editor.suggest.insertMode": "replace"
      },
      "[c]": {
        "editor.wordBasedSuggestions": false,
        "editor.suggest.insertMode": "replace"
      },
      "[Log]": {
        "editor.wordWrap": "off"
      }
    }
```
Let us know if you know of something else we may be doing incorrectly.

**Comment by alexdima** [comment] 2020-06-04 18:30
This issue is mostly resolved since VS Code now does start up correctly even with this setting set to null, but it would have been good to find out who is writing `"editor.quickSuggestions": null` to user settings. Thank you for checking that it was not your extension!
