### ISSUE TITLE
SCM - selected repository is not restored

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161947] opened 2022-09-27 11:37 UTC
**Steps:**
* open a multi root workspace with at least 2 repositories
* from the changes view select the first repo
* reload window and verify the changes view still has first repo selected
* switch to another profile
* switch back

=> 🐛 2 repositories are selected

![image](https://user-images.githubusercontent.com/900690/192515338-a885bbdf-effb-4c6e-a5c5-3c3d041c4124.png)

It seems to work fine once in the second profile the first repo is selected.

**Comment by sandy081** [comment] 2022-09-27 17:05
It seems like the selection state of repositories is stored in profile scope. Hence after switching profiles, the selection got reset.

**Comment by bpasero** [comment] 2022-09-28 04:16
Yeah that is possible that I had a case where I went back from the testing profile to my default profile where I saw 2 repositories selected in my default profile, so something is fishy.

**Comment by lszomoru** [comment] 2024-12-20 13:57
Duplicate of https://github.com/microsoft/vscode/issues/183823

**Closed by lszomoru** 2024-12-20 13:57 UTC
Labels: bug, scm
