### ISSUE TITLE
Pressing configure excludes button presents another configure excludes button

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21215] opened 2017-02-22 21:42 UTC
#21037

Pressing this:

![image](https://cloud.githubusercontent.com/assets/2193314/23233721/9385282e-f904-11e6-9e3a-35cb82253be3.png)

Presents:

![image](https://cloud.githubusercontent.com/assets/2193314/23233731/9a95e41e-f904-11e6-89bf-d4deccd841e3.png)

I've already committed to configuring them, why do I need to press it twice?

**Comment by mjbvz** [comment] 2017-02-23 19:49
This is not a regression. This has been the flow for a while now but should be improved. Moving to March

**Comment by mjbvz** [comment] 2017-04-20 23:40
After looking through this again, I believe the intention behind this design was to show the user more information about the error and what they need to do. Hovering over the status bar item to find out the details was not very discoverable. 

I'm unsure what a good alternative approach would be here. If we just open the `tsconfig.json` and don't display any message when a user clicks on this item status bar, it may not be clear to the user what they need to do. My vote would be to try to open the `tsconfig` if it exists and also display a error/message inside of it indicating what to fix

**Comment by Tyriar** [comment] 2017-04-21 16:18
> My vote would be to try to open the tsconfig if it exists and also display a error/message inside of it indicating what to fix

That might be better.

**Comment by roblourens** [comment] 2017-06-28 21:00
How do I get that "configure excludes" message to show up? Is it only for very large workspaces?

**Comment by mjbvz** [comment] 2017-06-28 21:17
Yes, try creating a `jsconfig.json` that includes `node_modules` for a large project. A config file like this should do it:

```
{
    "exclude": []
}
```

**Comment by roblourens** [comment] 2017-06-28 21:21
Shouldn't it open the jsconfig if that exists? Now it only shows the message and doesn't open the jsconfig.

**Comment by mjbvz** [comment] 2017-06-28 21:38
Sorry, I didn't specify the expected behavior very well here. Opening the jsconfig automatically was a pretty annoying experience, so now, when the `configure excludes` is triggered, you should see a warning message about this. Clicking the warning message should open the `jsconfig`

**Comment by roblourens** [comment] 2017-06-28 21:44
You're describing the opposite of what I thought - that previously you have to click twice to get to the jsconfig, and that now it should open the jsconfig automatically after the first click.

That's what I see in stable (I click the status bar, then click the button in the message bar). In Insiders, I click the status bar then see it open a warning message with no button to open the jsconfig.

**Comment by mjbvz** [comment] 2017-06-28 21:58
Yes you are correct. This is not doing the correct thing when you click on the status bar. It should try to open the config file if one exists

**Comment by mjbvz** [comment] 2017-06-29 01:38
Moving to july as I want more expose in insiders and the issue is not very high priority

**Closed** 2017-08-02 19:33 UTC
Labels: feature-request, javascript, typescript, ux, verification-found, verification-needed
