### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2904] opened 2016-02-10 20:02 UTC
Issue Id: <b>86637fe9-38db-b0c2-7bfa-cf7e40c002e9</b><br /><br />*Versions* <br />- 0.10.8<br />*Stack* <br />TypeError: Cannot read property 'className' of null<br />[/vs/base/browser/dom.ts#L65:20 (_findClassName)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/browser/dom.ts#L65:20 (_findClassName))<br />[/vs/base/browser/dom.ts#L172:1 (toggleClass)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/browser/dom.ts#L172:1 (toggleClass))<br />[/vs/editor/contrib/suggest/browser/suggestWidget.ts#L650:2 (SuggestWidget.setState)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L650:2 (SuggestWidget.setState))<br />[/vs/editor/contrib/suggest/browser/suggestWidget.ts#L576:9 (SuggestWidget.onEditorBlur)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L576:9 (SuggestWidget.onEditorBlur))<br />[/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1448:0 (call)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/winjs.base.raw.js#L1448:0 (call))<br />[/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />

**Comment by joaomoreno** [comment] 2016-02-24 15:45
Duplicate of #3133

**Closed by joaomoreno** 2016-02-24 15:45 UTC
Labels: error-telemetry
