### ISSUE TITLE
Text cursor disappears after autocomplete mouse selection

### ISSUE THREAD

**Issue by robertomulabi** [Microsoft/vscode#38693] opened 2017-11-18 17:50 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Type something until the autocomplete popup appears.
2. Select an item in the autocomplete popup using the mouse.

![vscode-autocomplete-cursor-bug](https://user-images.githubusercontent.com/3865454/32983155-a4de2552-cc77-11e7-9390-c83c6f51f3c6.gif)

After the selection is inserted into the document, the text cursor disappears. Pressing random keys doesn't change the document in any visible way. I have to mouse click in the document for the text cursor to reappear.

Using only the keyboard for making autocomplete selections works as expected: the text cursor is never lost.

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-11-18 19:22
This is fixed in Insiders, but I can't find the other issue. @ramya-rao-a?

**Closed** 2017-11-18 19:22 UTC
Labels: editor, editor-core, new release

**Comment by ramya-rao-a** [comment] 2017-11-19 19:41
Duplicate of #36087
And yes, the fix is in the Insiders build.
