### ISSUE TITLE
On-premise Marketplace

### ISSUE THREAD

**Issue by raveious** [microsoft/vscode#73628] opened 2019-05-12 01:09 UTC
For organizations that would like to develop internal extensions, or organizations with VSC installed on machines in an offline/air-gaped environment, is there any way there could be an on-premise marketplace for extensions? Then there could be a configuration setting that allowed for directing VSC to search this on-premise marketplace in addition to, or even instead of, the existing online extension marketplace.

**Comment by mjbvz** [comment] 2019-05-13 16:56
Duplicate of #21839

**Closed by mjbvz** 2019-05-13 16:56 UTC
Labels: extensions
