### ISSUE TITLE
dataloss with vscode.openFolder

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5799] opened 2016-04-26 09:08 UTC
#5338

* start with `yo code` sample
* change the command such that it opens a new workspace in the same folder
* start the debuggee
* make sure auto-save is off and make a chance such that a file is dirty
* run the command that opens a new folder
* ⚡ I don't get asked to save and lose my chance

**Comment by bpasero** [comment] 2016-04-26 10:54
Closing as designed because we want the extension development lifecycle to be so fast that you do not get prompted for saving. This is also useful for our CI tests that tear down even with dirty buffers without confirmation.

**Closed by bpasero** 2016-04-26 10:54 UTC
Labels: bug, important
