### ISSUE TITLE
Add editor.selectionborder

### ISSUE THREAD

**Issue by FrancisVila** [microsoft/vscode#90807] opened 2020-02-17 09:31 UTC
A number of issues refer to this feature, but they all seem to have been closed.
The following image illustrates the problem. Here editor.selectionhighlightborder works, but not editor.selectionBorder. 

![image](https://user-images.githubusercontent.com/23334974/74640373-bbab3200-516f-11ea-9161-e1527c997a6d.png)

- The currently seleted item is the AAFFAA of editor.selectionBorder. It is **_not bordered_**, when this is where you want to point out the current selection, which is the most important item in the editor: **_where things will happen if you hit keys on the keyboard_**. 
- The AAFFAA of editor.selectionHighlightBorder **is** bordered. This is important, but much less than editor.selectionborder. It's there to say "hey, the one you've got selected isn't the only one, if you're thinking of editing this one, don't forget all the rest". 

Requested feature: Make editor.selectionBorder work as expected

**Comment by aeschli** [comment] 2020-02-18 09:55
`editor.selectionborder` does not exist as a color yet. We have #30793 as a request for it

**Comment by aeschli** [comment] 2020-02-18 09:55
duplicate of #30793

**Closed by aeschli** 2020-02-18 09:55 UTC
