### ISSUE TITLE
Does not show directory paths when importing

### ISSUE THREAD

**Issue by buffos** [Microsoft/vscode#54287] opened 2018-07-13 23:25 UTC
We have written the needed data int
Issue Type: <b>Bug</b>

Since I installed the new "current user" only for windows, when  I import and do something like `import X from '../ etc'` previously after the ../ it showed me the available directories or files to choose from. Now they are not there.

VS Code version: Code - Insiders 1.26.0-insider (023b51bcc6204cc9bb9ca7752f764a3396401ec7, 2018-07-13T05:18:24.347Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (18.20GB free)|
|Process Argv|C:\Users\buffo\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\buffo\Code\react\lrn - burger.builder\burger.builder|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-el|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
vscode-custom-css|be5|2.7.1
solargraph|cas|0.17.5
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
racket|Dmy|1.2.0
githistory|don|0.4.1
jupyter|don|1.1.4
xml|Dot|2.3.1
es7-react-js-snippets|dsz|1.8.3
gitlens|eam|8.4.1
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
flow-for-vscode|flo|0.8.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
sml|fre|0.0.18
JSDocTagComplete|Hoo|0.0.2
vscode-ghc-mod|hoo|1.2.0
language-haskell|jus|2.5.0
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
vscode-pugbeautify|mrm|1.0.2
python|ms-|2018.6.0
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
Go|ms-|0.6.84
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.0
vscode-docker|Pet|0.0.27
Ruby|reb|0.18.0
java|red|0.28.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.24.0
markdown-preview-enhanced|shd|0.3.5
code-spell-checker|str|1.6.10
language-stylus|sys|1.9.2
vscode-status-bar-format-toggle|tom|1.4.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2
vscode-react-native|vsm|0.6.12
quokka-vscode|Wal|1.0.133
wallaby-vscode|Wal|1.0.92
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.7.2
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-07-16 18:31
Duplicate of #54267

Should be fixed in the latest builds

**Closed by mjbvz** 2018-07-16 18:31 UTC
Labels: typescript
