### ISSUE TITLE
the new c++ highlight is bad. some variables turn blue and some not

### ISSUE THREAD

**Issue by tkj666** [Microsoft/vscode#71875] opened 2019-04-07 07:49 UTC
Issue Type: <b>Feature Request</b>

'operator' lost its colour, too

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

**Comment by vsamy** [comment] 2019-04-08 04:18
Same here, lot of hightlight has changed.

VS Code version: Code 1.33.0
OS Version: Windows 10 Pro for Workstation 10.0.17134

**Comment by alexr00** [comment] 2019-04-09 09:56
Duplicate of #71821

**Closed** 2019-04-09 09:57 UTC
Labels: *duplicate, new release
