### ISSUE TITLE
Editor autoscrolls when Cursor Surrounding Lines enabled

### ISSUE THREAD

**Issue by ferenczy** [microsoft/vscode#128012] opened 2021-07-05 16:42 UTC
Issue Type: <b>Bug</b>

When the "_Cursor Surrounding Lines_" setting is set to a non-zero value, every time an editor tab is being activated (by selecting the tab or using the <kbd>Ctrl</kbd>+<kbd>Tab</kbd> keyboard shortcut), the editor automatically scrolls upwards, no matter the current location of the text cursor.

**Steps to reproduce:**

1. Open the _Settings_
2. Set "_Cursor Surrounding Lines_" to 5 lines
3. Set "_Cursor Surrounding Lines Style_" to default
4. Open a file containing more lines than fit the screen
5. Scroll to the very last line of the file (you don't need to move the text cursor, its position doesn't have any impact on the issue, it may be anywhere, it's enough to move just the view using the scrollbar)
6. Press <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to switch back to the _Settings_ tab
7. Press <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to switch back to the opened file
8. The editor automatically scrolls 5 lines up so (if the text cursor was on the last line, is not on the visible screen anymore)
9. Repeat steps 6 and 7 multiple times, after each iteration, the editor scrolls 5 lines up until it reaches the beginning of the file

The number of lines the editor scrolls by doesn't always match the "_Cursor Surrounding Lines_" setting. When I set it to 160, the editor scrolled in a 157-line file to the following lines (the initial topmost visible line was 114): 92, 70, 48, 26, 4, and 1. It seems the maximum step is 22 lines, even if you set it to more.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (3.90GB free)|
|Process Argv|--no-proxy-server --crash-reporter-id 45da9a36-c0f1-48a0-984a-b5e997f7a6fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
markdown-toc|Ala|1.5.6
Bookmarks|ale|13.1.0
project-manager|ale|12.2.0
docs-view|bie|0.0.9
bracket-pair-colorizer-2|Coe|0.2.1
markdown-table-prettify|dar|3.4.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.17
xml|Dot|2.5.1
overtype|DrM|0.4.0
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
vs-sharper|ese|0.2.0
vscode-github-notifications-bell|fab|2.3.1
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.5
vscode-pull-request-github|Git|0.27.1
go|gol|0.26.0
output-colorizer|IBM|0.1.2
reg|ion|1.0.3
vscode-nuget-package-manager-improved|max|2.1.0
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
csharp|ms-|1.23.12
powershell|ms-|2021.6.2
color-highlight|nau|2.3.0
vscode-json-editor|nic|0.3.0
indent-rainbow|ode|7.5.0
linesinfostatusbar|pet|0.0.3
material-icon-theme|PKi|4.8.0
vscode-data-preview|Ran|2.3.0
code-stats-vscode|riu|1.0.18
trailing-spaces|sha|0.3.1
avro|str|0.5.0
code-spell-checker|str|1.10.2
code-spell-checker-czech|str|0.1.7
markdown-memo|svs|0.3.9
markdown-links|tch|0.8.0
vscode-icons|vsc|11.5.0
vscode-wakatime|Wak|13.0.0
change-case|wma|1.0.0
unsaved-files-vscode|wra|2.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30323119

```

</details>

**Comment by alexdima** [comment] 2021-07-06 07:00
Duplicate of https://github.com/microsoft/vscode/issues/126178 . Please update to `1.57.1`

**Closed by alexdima** 2021-07-06 07:00 UTC

**Comment by ferenczy** [comment] 2021-07-22 22:53
Sorry for the duplicate. I can confirm that the version `1.57.1` has fixed the issue. 👍 Thanks!
