### ISSUE TITLE
SCM: Option for gutter decoration ignore whitespace

### ISSUE THREAD

**Issue by howar31** [microsoft/vscode#60594] opened 2018-10-11 06:10 UTC
The whitespaces are shown as changes in gutter decoration in editors:

![image](https://user-images.githubusercontent.com/880459/46783945-cb865b00-cd5e-11e8-8acd-ab7d574f2a2a.png)

I usually use `git diff -w` in the daily work and think it'll be great if there's an option for ignoring whitespace changes.

I've only found the setting diffEditor.ignoreTrimWhitespace which seems like it is only worked for Diff Editor not for Editors.

**Comment by joaomoreno** [comment] 2018-10-11 09:34
Unfortunately this is a technical limitation. These whitespace changes are used for computations in range staging commands. There's no easy way to remove them now.

**Comment by nextgensparx** [comment] 2018-11-09 19:57
Did this change recently? The gutter decoration used to follow the diff editor's setting for ignoring whitepace and worked great.
The gutter decorations are pretty useless to me now that they always show whitespace changes. I almost always just see one big vertical line since I often make indentation changes.

**Comment by sam97** [comment] 2019-01-02 05:59
@joaomoreno Any idea about the timeline for this issue? It's not a crucial feature, sure, but it'll be nice to have it.

**Comment by siphomateke** [comment] 2021-12-09 21:13
Looks like this was fixed in 98f5bf9b9bea2fe075d3b07fbf0edf5b3576e08b (see #130956) and this issue can be closed :tada:

**Closed** 2021-12-10 10:10 UTC
Labels: help wanted, feature-request, scm

**Comment by lszomoru** [comment] 2022-01-24 14:32
Making as duplicate of https://github.com/microsoft/vscode/issues/130956
