### ISSUE TITLE
editor.formatOnType Removes Spaces in JSDocs

### ISSUE THREAD

**Issue by aight8** [Microsoft/vscode#23241] opened 2017-03-26 17:39 UTC
- VSCode Version: 1.10.2
- OS Version: all

Steps to Reproduce:

![issues vscode vscode-space](https://cloud.githubusercontent.com/assets/1138623/24333560/6e739286-125a-11e7-809e-65e6ed1ecbbc.gif)

This behaviour bother me since a while, while writing code docs so I finally decided to create an issue for it.
It were nice if there were an option which aware of the initial space in the code doc blocks. How we see in the screencast is already an auto-creation functionality of the blocks, so this functionality would be definitely a part of the vscode core.

In almost every cases the space before any text there - so this extra key press can be avoided.

This appears:
- After initial code doc creation
- After line break
- Extra: If press delete on pos. 0 of a line and the before block line is an empty code block line (aware of space because it can be auto deleted if trailing spaces are removed automatically)

# EDIT

I found out this is an issue which only appear if ```editor.formatOnType``` option enabled! Any chance to fix this anyway if stick on this option?

**Comment by axefrog** [comment] 2017-08-19 21:41
Confirmed after trying to track down the issue myself; the problem only occurs if `editor.formatOnType` is set to `true`.

**Comment by mjbvz** [comment] 2017-12-01 23:02
Seems to be fixed in latest vscode insiders builds that use TS 2.6.2. Let me know if you are still able to reproduce this

**Closed by mjbvz** 2017-12-01 23:02 UTC
Labels: bug, javascript, typescript
