### ISSUE TITLE
Ctrl-C does not break processes in `zsh` terminal

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode#179066] opened 2023-04-03 22:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0-insider (Universal)
- OS Version: macOS Ventura 13.2.1

Steps to Reproduce:

1. Open VS Code - Insiders
2. Create new `zsh` terminal
3. Start a long-running process
4. Type Ctrl-C

Expected:

Process breaks.

Actual:

Terminal shows `^C` and process continues.  Also, curiously, the `zsh` terminal now has the default label `kernel_task` (whereas the `bash` shell has the label `bash`).

<img width="852" alt="Screenshot 2023-04-03 at 15 10 55" src="https://user-images.githubusercontent.com/6402946/229638380-f29666d2-ec25-421e-a250-216813a126d2.png">

> Note: this only seems to happen in a `zsh` shell (which was my default up until last week when this started happening). If I use the `bash` shell, Ctrl-C works as expected. Also, Ctrl-C works as expected in a `zsh` shell in iTerm2.

**Comment by tamuratak** [comment] 2023-04-03 22:27
Duplicate of https://github.com/microsoft/vscode/issues/178693

**Closed** 2023-04-03 23:40 UTC
