### ISSUE TITLE
Double clicking inside commit message input field causes currently selected file in changes group to be opened and focused

### ISSUE THREAD

**Issue by varadero** [microsoft/vscode#112070] opened 2020-12-08 08:52 UTC
- VSCode Version:
Version: 1.52.0-insider (user setup)
Commit: 6026ab576dc6a4fbb8e255241a364816f42464c5
Date: 2020-11-23T05:56:29.761Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

[OK] [Copy]
- OS Version:
 Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open a git-managed project
2. Change some of the files and save it
3. Click on 'Source control (CTRL+SHIFT+G)' - you will see a list with changed files
4. Click on some of the files in the Changed list - diff window will open on the right - you can now close the diff window
5. Type some commit message
6. Double click some of the commit message words to select it

What happens:
Just after the entire double-clicked word is selected, the currently selected file in Changes list is opened on the right and gets the focus - at this point the user expects to simply edit its commit message word selection but actually it changes the content of the file.

If you click on the empty area in Changes list (just below the last file) so you clear its selection, now the double click inside commit message input field works as expected - it selects the double clicked word and focus remains there.

Does this issue occur when all extensions are disabled?: Unknown

**Comment by eamodio** [comment] 2020-12-08 16:47
Duplicate of https://github.com/microsoft/vscode/issues/110751

**Closed** 2020-12-08 16:47 UTC
Labels: *duplicate
