### ISSUE TITLE
Option to change the font of the vscode App Window

### ISSUE THREAD

**Issue by dipsonu10** [microsoft/vscode#136427] opened 2021-11-04 10:47 UTC
# Attribute values are immutable If is it possible to add option to choose as per the user 
using the debugger, I got 

<img width="960" alt="Screenshot 2021-11-04 160458" src="https://user-images.githubusercontent.com/65275144/140299974-cb2ce9a4-a1bd-4fce-94e7-2b0568332884.png">

## elements like the
<img width="952" alt="Screenshot 2021-11-04 160257" src="https://user-images.githubusercontent.com/65275144/140300045-e7e88adf-6c33-4f4f-8778-d8e39b3b73ff.png">

not necessary but many IDE's have option to change it 😃

**Comment by dipsonu10** [comment] 2021-11-04 10:48
got this in file
c:/Users/DipankarDas/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.css

**Comment by gjsjohnmurray** [comment] 2021-11-04 11:08
Did you try the `editor.fontFamily` setting?

**Comment by dipsonu10** [comment] 2021-11-04 11:10
Yes it only changes the editor fontFamily

**Comment by dipsonu10** [comment] 2021-11-04 11:12
# changing from the developer tools
![image](https://user-images.githubusercontent.com/65275144/140303949-50bbbf6a-1c6b-4488-8705-d600e74e4a0a.png)

**Comment by gjsjohnmurray** [comment] 2021-11-04 11:15
> Yes it only changes the editor fontFamily

Then the title you gave to this issue is ambiguous because it says "editor window".

**Comment by dipsonu10** [comment] 2021-11-04 11:16
O sorry but I didn't know what the property name is

**Comment by IllusionMH** [comment] 2021-11-04 13:38
Looks like duplicate of #519 and #26128

**Comment by joyceerhl** [comment] 2021-11-05 02:02
Duplicate of https://github.com/microsoft/vscode/issues/519

**Closed by joyceerhl** 2021-11-05 02:02 UTC
