### ISSUE TITLE
Theme can not change the Color of the sidebar

### ISSUE THREAD

**Issue by alex-marmot** [Microsoft/vscode#5399] opened 2016-04-16 18:06 UTC
- VSCode Version: 1.0.0
- OS Version: Mac 10.11.4

Steps to Reproduce:

1. Change the theme to Solarized Dark.
2. The SideBar still black.

**Comment by Tyriar** [comment] 2016-04-16 23:38
Duplicate of https://github.com/Microsoft/vscode/issues/1231

**Closed by Tyriar** 2016-04-16 23:38 UTC
