### ISSUE TITLE
Include @types from typings

### ISSUE THREAD

**Issue by sant123** [Microsoft/vscode#15922] opened 2016-11-22 21:37 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 8.1

Steps to Reproduce:

1. Download oracledb `npm i oracledb`
2. Init a package.json
3. Asign a type with jsdoc into a var

``` javascript
/** @type { IConnectionAttributes } */
var config = require("./config");
```

You can notice there's no intellisense with this interface from oracledb typings.

![image](https://cloud.githubusercontent.com/assets/7959437/20542933/d964d5d6-b0d1-11e6-8dbb-60ce65ff03d6.png)

``` typescript
interface IConnectionAttributes {
    user?: string;
    password?: string;
    connectString: string;
    stmtCacheSize?: number;
    externalAuth?: boolean;
    /** If not passed, "default" will be used. */
    poolAlias?: string;
}
```

**Comment by mjbvz** [comment] 2016-11-23 00:02
Thanks for the report. Do you notice this problem with any other packages (oracledb is a pain to install and seems to require me registering with oracle in order to get the "Oracle Instant Client")

![nov-22-2016 16-01-59](https://cloud.githubusercontent.com/assets/12821956/20546869/f39dd376-b0cc-11e6-9d56-18809add0f54.gif)

Also, do you import `IConnectionAttributes`? TypeScript will not pick up the types unless you do this. Here's what I did for express:

```js
import express from 'express'

/**
 * @type {express.Application}
 */
var app;
```

**Comment by sant123** [comment] 2016-11-23 04:37
@mjbvz thanks to you for answering. 😄 Sure, I've tested with express and it works as expected according with your example, however it only works with ES2015 import/export feature, but not with Common.js. Running this code will raise an exception.

Here I show you the behavior with Common.js against ES2015.

![ata example](https://cloud.githubusercontent.com/assets/7959437/20551267/400121de-b10c-11e6-963a-d062f6ecc799.gif)

**Comment by mjbvz** [comment] 2017-04-04 01:44
After looking at this again, this looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/11825 or https://github.com/Microsoft/TypeScript/issues/14056 We're tracking these on the TypeScript side.

As you noted, the workaround currently is to use an import pattern instead of `var x = require(...)`

**Closed by mjbvz** 2017-04-04 01:44 UTC
Labels: javascript, typescript, upstream

**Comment by MicahZoltu** [comment] 2017-04-10 20:07
Unfortunately, using the import pattern only works if you are writing (or transpiling from) ES2015.  I have been unable to find a workaround that works with ES5.
