### ISSUE TITLE
cls command in terminal does not clear 

### ISSUE THREAD

**Issue by AdrianMolecule** [microsoft/vscode#207623] opened 2024-03-13 19:03 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. print something > 100 lines to vsc terminal
2. click in terminal and type cls
3. scroll up and see the content is still present

**Comment by meganrogge** [comment] 2024-03-13 20:12
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-03-13 20:12 UTC
