### ISSUE TITLE
Sticky scroll does not show diff background colours

### ISSUE THREAD

**Issue by Kroc** [microsoft/vscode#185277] opened 2023-06-15 21:07 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.0-insider
- OS Version: Win10 x64 2022H2

When scrolling, the sticky scroll does not inherit the background colours of the diff (those lines are part of the diff, and should be green).

Before scroll: 

![image](https://github.com/microsoft/vscode/assets/142650/8fa354c0-d74f-45e6-a6b6-1ff9a6a2d37c)

After scroll:

![image](https://github.com/microsoft/vscode/assets/142650/1909efda-1cdd-4c9a-9357-16652c4d87cd)

**Comment by aiday-mar** [comment] 2023-07-13 13:35
Hi, thanks for filing the issue. An issue has been opened which aims to add all kinds of decorations to sticky scroll, not just background diff colors, but also highlights, code lens text, indentation guides. You may track and upvote the issue here: https://github.com/microsoft/vscode/issues/187834

**Comment by aiday-mar** [comment] 2023-12-05 08:30
/duplicate of https://github.com/microsoft/vscode/issues/187834

**Closed by aiday-mar** 2023-12-05 08:30 UTC
Labels: feature-request, editor-sticky-scroll, editor-sticky-scroll-decorations
