### ISSUE TITLE
Backtick shortcut in terminal stopped working

### ISSUE THREAD

**Issue by eyaleizenberg** [Microsoft/vscode#68388] opened 2019-02-11 07:16 UTC
- VSCode Version: Version 1.31.0
- OS Version: Mac OS 10.14

Steps to Reproduce:

1. I have the following keyboard mapping:
```
    "key": "` a",
    "command": "workbench.action.togglePanel"
```
2. It used to work when the focus was either on the terminal or on the editor itself.
3. Following the last update, it still works when the focus is on the editor. However, if the focus is on the terminal, it just prints "` a".
4. This is the same for other shortcuts I have which involve backtick and the terminal.

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment] 2019-02-11 13:56
This might be related to the recent change to `terminal.integrated.commandsToSkipShell`: https://code.visualstudio.com/updates/v1_31#_improvements-to-commandstoskipshell-setting

Make sure you have this in your settings.json:

```jdon
{
  "terminal.integrated.commandsToSkipShell": [
    "workbench.action.togglePanel"
  ]
}
```

**Comment by eyaleizenberg** [comment] 2019-02-11 14:04
@Tyriar That didn't help 😢

**Comment by Tyriar** [comment] 2019-02-11 14:09
@alexandrudima maybe some change to the keybinding system? I'm not familiar with this form `"key": "` a"`

**Comment by Tyriar** [comment] 2019-02-11 14:10
@alexandrudima maybe some change to the keybinding system? I'm not familiar with this form:

```
"key": "` a"
```

**Comment by alexandrudima** [comment] 2019-02-11 14:49
@Tyriar Nothing changed in the keybindings system.

That means the key that produces `` ` `` is pressed without any modifier, followed by the key that produces `` a `` without any modifier.

``"cmd+` cmd+a"`` means `` cmd+` `` chorded to `` cmd+a ``.
``"alt+` alt+a"`` means `` alt+` `` chorded to `` alt+a ``.
``"` a"`` means `` ` `` chorded to `` a ``.

**Comment by alexandrudima** [comment] 2019-02-11 14:51
I can reproduce the issue, when defining the keybinding:
```
{
	"key": "` a",
	"command": "workbench.action.togglePanel"
}
```

When focus is in the editor, this will reveal the panel. When focus is in the terminal, `` `a `` is taken as input to the terminal.

**Comment by Tyriar** [comment] 2019-02-11 14:57
@alexandrudima thanks for the help, didn't think you could have chords without modifiers.

In that case, I don't understand why this was working before due to https://github.com/Microsoft/vscode/issues/44764. I just verified that this is indeed a regression as the keybinding works in 1.29.1, but the current behavior seems correct to me; chords shouldn't work at all in the terminal unless they naturally avoid being sent to the terminal, such as ctrl+shift+a. Closing as duplicate of #44764

**Closed by Tyriar** 2019-02-11 14:57 UTC
Labels: mac
