### ISSUE TITLE
Typescript - Quick fix (lightbulb) - Renamed file to lowercase characters

### ISSUE THREAD

**Issue by deylin** [Microsoft/vscode#73161] opened 2019-05-02 07:35 UTC
Issue Type: <b>Bug</b>

I renamed a Typescript file in my angular project, just replacing the uppercase characters to lower case equivalent. Now when I open the file and start editing, at random moments the old file with the uppercase characters pops up in a new tab!?

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (1.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.26.1
Angular2|joh|7.1.4
windowsiot|ms-|0.0.20
mssql|ms-|1.6.0
python|ms-|2019.4.12954
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
powershell|ms-|1.12.1
vsliveshare|ms-|1.0.91
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1

</details>

**Comment by deylin** [comment] 2019-05-02 14:13
I have permanently deleted the file and recreated it, but this does not solve the issue.

The problem pops up when use the '**Quick fix**' (or lightbulb) for **Typescript**. Selecting an existing declaration will add this to the old file (with upper case charaters)

**Comment by deylin** [comment] 2019-05-02 14:19
Also, error checking (red squillies with hover information) is also messed up. Have to close and reopen the file for correct checking...

**Comment by mjbvz** [comment] 2019-05-02 16:40
Duplicate of #71990

**Closed by mjbvz** 2019-05-02 16:40 UTC
Labels: typescript
