### ISSUE TITLE
Inconsistent behavior when cutting and pasting line with no selection

### ISSUE THREAD

**Issue by acls** [Microsoft/vscode#16341] opened 2016-12-01 20:17 UTC
- VSCode Version: 1.8.0-insider
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Put cursor on a word with no text selected (over 1234)
  ```
  ab
  1234
  ab
  ```
2. Cut the line (ctrl+x)
```
ab
ab
```
3. Focus a different text editor tab and then return focus to original tab (ctrl+tab twice)
4. Move the cursor to the middle of a word (right arrow key)
5. Paste the line (ctrl+v)
```
ab
a1234
b
```

Expected: original text.

Pasting should work the same as if the tab hadn't changed. Cutting and pasting a line in the same file works, but if the tab changes then it pastes in the middle of the word instead of the beginning of the line.

**Comment by kaiwood** [comment] 2016-12-02 09:13
Interesting bug, can confirm. It behaves this way only if emptySelectionClipboard is used. If one **selects** the line **plus** the line ending on the next line, it works correctly from the start. The need for a tab change smells like an event handler doesn't get triggered. The paste command behaves as if the cursor is at the beginning of the line.


BUT:

@acls I think it's the other way around. The outcome you describe after switching the tabs is the correct one.

If you cut the whole line, you (should) have basically something like `1234\n` in the clipboard. And if you then put the cursor between `a` and `b` to paste it should start the pasting exactly where your cursor is positioned, with this as a correct result:

    ab
    a|1234\n
    b

Your expected original text should be the result if you start to paste at the beginning of the line.

**Comment by acls** [comment] 2016-12-02 17:26
Cutting and pasting a line without a selection should behave differently than selecting the whole line, at least it does in other editors I've used recently (Visual Studio, Sublime Text, Atom). They paste the line above the current line, regardless of the cursor position. And the cursor position doesn't change.

Since it works that way in other major editors and it works that waya before changing tabs, I would think that that was the intended behavior. Actually, I just noticed, the cursor moves to the line beginning after pasting, so it only half works. But half working is still better than having to manually move to the beginning, which involves 1 or 2 extra key presses depending on cursor position.

I don't think it's because of an event handler not triggering, or at least I don't think it should depend on event handlers. VS and Sublime (but not Atom) work the same when cutting from one window and pasting into a different window. VS even works if the program is closed and reopened or if Windows is restarted(using a clipboard manager to save the clipboard). So it seems like metadata should be stored with the cut text. That way pasting doesn't rely on knowing the state when it was cut. Something like copying from a browser. A text editor will just paste just the text, but a document editor (LibreOffice, Word) will paste the html. Using metadata could also be a possible fix for other similar bugs (#4996, #10024, #11007).

**Comment by acls** [comment] 2016-12-07 23:52
I looked more into how Visual Studio handles this. It adds the `Text` format type with the copied/cut text and, as a flag, it adds the `VisualStudioEditorOperationsLineCutCopyClipboardTag` format type. When pasting it handles things depending on whether the flag exists or not.

Since vscode is running in electron, it doesn't have the luxury of setting whatever format types it wants. But it can set [multiple format types](https://github.com/electron/electron/blob/master/docs/api/clipboard.md#clipboardwritedata-type). It could repurpose either the RTF or HTML(example shows both) to store the flag. When pasting in programs that use those types, the flag wouldn't alter the visual appearance, but in vscode it would signal the state when the copy/cut took place.

```
clipboard.write({
  text: '1234\n',
  rtf: '{\\rtf1\\VisualStudioEditorOperationsLineCutCopyClipboardTag 1234\\par }',
  html: '<div data-visualstudioeditoroperationslinecutcopyclipboardtag><div/>1234<br/>',
})
```

Not sure if this will even work or if it's too big of a hack to pass code review. Just making some suggestions. Also, the RTF value works in WordPad, but causes nothing to be pasted in LibreOffice. I don't know RTF, so I'm sure there's a better way to format it.

**Comment by alexandrudima** [comment] 2016-12-08 08:32
Yes, the textAreaHandler (per editor view instance) remembers the last "line-cut" text and uses that to take a hint that the paste should be a "line-paste". This should probably be changed to a static.

**Comment by acls** [comment] 2016-12-08 16:52
It'd be nice to have it work across instances, but working across tabs should be good enough.

It would also be nice if the cursor position didn't change after pasting, but looking at line 68 of cursorTypeOperations, it seems like that was on purpose?

**Comment by alexandrudima** [comment] 2017-12-14 10:29
Duplicate of #5639

**Closed by alexandrudima** 2017-12-14 10:29 UTC
Labels: bug, editor-clipboard
