### ISSUE TITLE
Errors with  dialog box (open file, open directory, save as )

### ISSUE THREAD

**Issue by Kylinking** [Microsoft/vscode#24364] opened 2017-04-09 12:57 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.16170
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-node-readme|bengreenier|1.0.7|
|GBKtoUTF8|bukas|0.0.2|
|vscode-wxml|coderfee|0.1.9|
|vscode-express|Compulim|0.0.5|
|vscode-npm-source|dkundel|1.0.0|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|we-app-vscode|emeryao|0.6.0|
|beautify|HookyQR|1.0.2|
|NodeAssertionSnippets|jaymorrow|0.1.0|
|vscode-exec-node|miramac|0.4.1|
|node-modules-resolve|naumovs|1.0.2|
|emoji|Perkovec|0.0.3|
|partial-diff|ryu1kn|0.2.0|
|vscode-hexdump|slevesque|1.2.1|
|expresssnippet|vladmrnv|0.1.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---
Steps to Reproduce:

1. click File option in the title bar
2. choose "Open File" , "Save as" or "Open Directory" 
3. the dialog box doesn't appear.

**Comment by chrmarti** [comment] 2017-04-10 05:02
Is there anything in the devtools' console? (Help > Toggle Developer Tools)

**Comment by chrmarti** [comment] 2017-04-10 05:04
Does this always occur or only in some cases? Could start with `code --disable-extensions` and confirm the problem is still there?

**Comment by bpasero** [comment] 2017-04-10 05:16
@Kylinking with other tools do the dialogs open without issues?

**Comment by Kylinking** [comment] 2017-04-10 12:44
I have tried serveral applications with the same operations. There may be some problems with the latest Windows preview version. It looks like a general problem with dialog operations in some third applications, even the Microsoft series( VS and VSC).

**Comment by bpasero** [comment] 2017-05-14 08:04
Closing as this is not under our control.

**Closed by bpasero** 2017-05-14 08:04 UTC
Labels: explorer-files, needs more info, upstream
