### ISSUE TITLE
Invalid tab spacing when line contains chars with different char width (kana, kanji etc)

### ISSUE THREAD

**Issue by teplofizik** [Microsoft/vscode#39249] opened 2017-11-28 11:57 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
VHDL|msh|0.0.2
omnipascal|Wos|0.15.0

Tab positions invalid, if there are chars with different width before tab. Japanese kana, kanji etc

Now:
![image](https://user-images.githubusercontent.com/15154072/33318225-00ec93e4-d44b-11e7-86cb-5b6d9f26c402.png)
![image](https://user-images.githubusercontent.com/15154072/33317829-7af239ca-d449-11e7-8938-43a43378d397.png)

Settings:
![image](https://user-images.githubusercontent.com/15154072/33317845-86422006-d449-11e7-8d1f-6adcb16a03aa.png)

Expected:
![image](https://user-images.githubusercontent.com/15154072/33318387-8840fb6e-d44b-11e7-8193-3bce1af22a70.png)

---

Steps to Reproduce:

1. Set tab size 8 or above ("editor.tabSize": 10) and no replacing tabs with spaces ("editor.insertSpaces": false)
2. Create new file
3. Enter text with chars with similar width: "La	La	La"
4. Enter text with chars with different width: "古事記	La	La"

Reproduces without extensions: Yes

**Comment by yh1224** [comment] 2018-03-03 11:08
This issue is also fixed by #44259.

**Comment by alexandrudima** [comment] 2018-03-05 11:26
Duplicate of #22832

**Closed by alexandrudima** 2018-03-05 11:26 UTC
Labels: editor, editor-rendering, feature-request
