### ISSUE TITLE
顶栏一直出现警告

### ISSUE THREAD

**Issue by wenyang12** [Microsoft/vscode#22194] opened 2017-03-08 06:19 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|better-merge|pprice|0.5.1|
|vsc-tasks|walli|0.9.0|;

---

Steps to Reproduce:

1.更新了vs到1.10.1
2.更新好后打开vs然后有扩展提示更新，再次更新了githistory
3.然后顶栏就一直出现警告，一直闪，无法点击关闭警告
4.警告的内容为“在过去5分钟内,TypeSrcipt 语言服务意外终止了5次”

**Comment by King66** [comment] 2017-03-08 06:31
Infinite loop of "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."

It seems many users have reported this issue......

**Comment by ydcoming** [comment] 2017-03-08 13:58
小伙子,你的文件杀毒软件删除了 你找回来就可以了

**Comment by ydcoming** [comment] 2017-03-08 14:01
你的杀毒软件删除了 vscode的ts服务的那个js文件  你找回来就可以了

**Comment by mjbvz** [comment] 2017-03-08 22:13
Yes, this is likely a duplicate of #20496.

Please try reinstalling VSCode to fix this

**Closed by mjbvz** 2017-03-08 22:13 UTC
Labels: duplicate, typescript
