### ISSUE TITLE
Cannot open code on last version 1.90

### ISSUE THREAD

**Issue by ZauJulio** [microsoft/vscode#214498] opened 2024-06-06 18:24 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90
- OS Version: EndeavourOs (Arch based)

```
Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:43:07.605Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.9.3-zen1-1-zen
```

Steps to Reproduce:

![image](https://github.com/microsoft/vscode/assets/49128655/e83969ca-ba4c-48b6-8b55-166a80f3253d)

1. install `yay -S visual-studio-code-bin'
2. try open instance

**Comment by tolgacangoz** [comment] 2024-06-06 18:26
I have the same issue in Ubuntu 24.04 with the latest version of VS Code. It says "GPU process isn't usable. Goodbye." at the last line. If I add `--in-process-gpu` flag, it seems to work.

**Comment by ZauJulio** [comment] 2024-06-06 18:28
I managed to open it using `--verbose`, a friend managed it with `--in-process-gpu`
But this process runs using a lot of resources

**Comment by ZauJulio** [comment] 2024-06-06 18:28
> I have the same issue in Ubuntu 24.04 with the latest version of VS Code. It says "GPU process isn't usable. Goodbye." at the last line. If I add `--in-process-gpu` flag, it seems to work.

Thank you, I used it too, it worked perfectly

**Comment by podzit** [comment] 2024-06-06 19:14
If you use snap code try to revert on old version:
sudo snap revert code

**Comment by flof** [comment] 2024-06-06 19:18
> If you use snap code try to revert on old version: sudo snap revert code

Thanks, this is a workaround for now.

**Comment by dejan2609** [comment] 2024-06-06 20:44
Same issue occurs for me (Ubuntu 24.04 /  VS Code 1.90). 

`sudo snap revert code` workaround mentioned above (that reverts VS Code to 1.89.1) works for me.

**Comment by dejan2609** [comment] 2024-06-06 20:52
One more thing: just a few days ago IntelliJ IDEA team solved issue that manifested in a same way.

You may want to research these two tickets: 
 - https://youtrack.jetbrains.com/issue/IJPL-59368/IDE-crashes-due-to-chrome-sandbox-is-owned-by-root-and-has-mode-error-when-IDE-is-launching-the-JCEF-in-a-sandbox 
 - https://youtrack.jetbrains.com/issue/IJPL-59369/Crash-when-previewing-a-Markdown-document

**Comment by GuySartorelli** [comment] 2024-06-06 22:55
Duplicate of https://github.com/microsoft/vscode/issues/214432

**Comment by Resonanz** [comment] 2024-06-07 01:28
UBUNTU

Download previous version here:
https://update.code.visualstudio.com/1.89.1/linux-deb-x64/stable

Manual install:
sudo dpkg -i code_1.89.1-1715060508_amd64.deb

How did Mickeysoft release such a badly broken version 1.90? Such superpowers !!!

**Comment by deepak1556** [comment] 2024-06-07 02:18
Merging to https://github.com/microsoft/vscode/issues/212494

You can start the application with `--use-angle=swiftshader` as workaround until fix is released.

**Closed by deepak1556** 2024-06-07 02:18 UTC
