### ISSUE TITLE
Improve the test message view for multi-line messages

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#138389] opened 2021-12-03 06:44 UTC
Currently we use the test message view to show the stacktrace when a Java test case fails. The problem is, most commonly, the stacktrace have plenty of lines. From the customer surveys, some of them say that it's hard to read and edit the code in the meantime because the view occupies a big area.

Here are some ideas in my mind:

##### Before
![屏幕截图 2021-12-03 112701](https://user-images.githubusercontent.com/6193897/144557543-b9842cdf-65ab-48cb-aa86-6437f063ddc4.png)

##### After

![屏幕截图 2021-12-03 113339](https://user-images.githubusercontent.com/6193897/144557555-ad048650-1f39-4f9b-a689-ea145ae2f655.png)

#### When VS Code detects that the messages are more than X lines, collapse it and render a button to toggle the overflow part out or off

Something like this:
![屏幕截图 2021-12-03 133412](https://user-images.githubusercontent.com/6193897/144557565-330a7ced-ea7a-473e-a1b6-c9e081822585.png)

**Comment by connor4312** [comment] 2021-12-13 23:11
I'm guessing for these screenshots you're putting two line breaks between each line?

You can also create a MarkdownString that supports HTML and add line breaks, like so:

```
const str = new vscode.MarkdownString(messageLines.join("<br>"));
str.supportHtml = true;
const message = new vscode.TestMessage(str);
```

> When VS Code detects that the messages are more than X lines, collapse it and render a button to toggle the overflow part out or off

I'm not clear on the benefit of this versus having the message be scrollable as it is today. Is the scroll region too large for your users' liking, or is there another reason?

**Comment by jdneo** [comment] 2021-12-14 04:39
Thank you!

Previously I was using `markdownString.appendText('\n')` to add a line break; Now I replaced it to `markdownString.appendMarkdown('<br/>')` and it looks better now:
![image](https://user-images.githubusercontent.com/6193897/145928256-5e9d0f72-7c45-4ead-b643-95ab958541d5.png)

> Is the scroll region too large for your users' liking, or is there another reason?

We get some feedback that in order to get enough information from the diff view, users will expand the height and thus occupies the area in editor. But I guess this problem should be somehow mitigated with the power of html support in Markdown string. I can release this in next version and see if we still get feedback like that.

**Comment by connor4312** [comment] 2021-12-14 17:53
Sounds good. I also made the "open external" button on the peek toolbar open the Markdown Preview for markdown messages, which will make that a good experience for users who want to view a full screen representation of the message.

By the way, I notice that in the message you have it seems like a diff view would be appropriate. Do you use the markdown preview solely so that a stacktrace can be displayed?

**Comment by jdneo** [comment] 2021-12-15 01:50
> Do you use the markdown preview solely so that a stacktrace can be displayed?

There is another diff view. But that's a good suggestion I should remove the beginning expecting/sctual messages to save more area.
![image](https://user-images.githubusercontent.com/6193897/146108152-ea131bbb-827c-411c-8769-321ac20211d9.png)

**Comment by jdneo** [comment] 2021-12-16 11:25
@connor4312 I tried the peek button but seems not working when it's a markdown string.


https://user-images.githubusercontent.com/6193897/146363207-c1b59a35-c7cf-413e-9248-ed02f35ad5df.mp4

**Comment by connor4312** [comment] 2021-12-16 19:46
@jrieken this appears to be because the test message is not marked as synced, this is throwing:

https://github.com/microsoft/vscode/blob/d33e3d2fbcdd15553a529b7fbc0ae303b91a170c/src/vs/workbench/api/browser/mainThreadDocuments.ts#L244

I think this is because the message is initially opened in a simple widget (the embedded code editor), which is not synced. However I'm not entirely clear on why the second opening succeeds. The inconsistent first and second opening behavior smells fishy so thought you may be interested.

To reproduce, apply this diff to the test-provider-sample in the vscode extension samples, then run the failing test and hit the "open external" icon:

```diff
diff --git a/test-provider-sample/src/testTree.ts b/test-provider-sample/src/testTree.ts
index 2414023..0a2e393 100644
--- a/test-provider-sample/src/testTree.ts
+++ b/test-provider-sample/src/testTree.ts
@@ -107,7 +107,9 @@ export class TestCase {
     if (actual === this.expected) {
       options.passed(item, duration);
     } else {
-      const message = vscode.TestMessage.diff(`Expected ${item.label}`, String(this.expected), String(actual));
+      const str = new vscode.MarkdownString("html:<br>" + "world<br>".repeat(30));
+      str.supportHtml = true;
+      const message = new vscode.TestMessage(str);
       message.location = new vscode.Location(item.uri!, item.range!);
       options.failed(item, message, duration);
     }
```

And while I have you, is there a recommended way to make this work? 🙂

**Comment by jrieken** [comment] 2021-12-20 11:15
> And while I have you, is there a recommended way to make this work? 🙂 My naive thought would be that if there's an existing simple text model when an extension opens a URI, then the simple marker should be removed in some way.

No, my understanding is that this [cannot change](https://github.com/microsoft/vscode/blob/36fdeed3b5b4136607e45e4b75334b23b517c313/src/vs/editor/common/model/textModel.ts#L343) after the fact. A new model is needed or you create "real" text model to begin with. I am not very familiar with the simple editor but I know that the SCM input box is a simple (simpler?) text editor with a model that makes it into the extension host. In my head (without checking the code) you should be able to create a simple editor, create a real model, set the mode to the simple editor

**Closed** 2021-12-29 23:30 UTC
Labels: feature-request, verification-needed, testing

**Comment by jdneo** [comment] 2022-01-06 07:00
Hi @connor4312, 

Just tried the peek view and it works well now.

But I found two new problem:

1. In the peek view, the cursor style is wrong when it comes to a link
2. In the 'open external' view, nothing happens when clicking on the link


https://user-images.githubusercontent.com/6193897/148342204-a6794435-451f-4268-baa9-43f19384bed9.mp4

**Comment by connor4312** [comment] 2022-01-07 22:32
I fixed the former. I don't think we can fix the latter unless we support command links in markdown preview, which doesn't seem to exist at the moment. @mjbvz thoughts?

**Comment by jdneo** [comment] 2022-01-10 01:25
> Though command links in markdown preview could be neat, we could have links in the release notes (when read in VS Code) that actually turn on or go to the new features.

That looks great! Hope we can have this supported!

**Comment by mjbvz** [comment] 2022-01-11 21:59
@connor4312 Command links are disabled in rendered markdown by default. You can set `isTrusted` to enable them

If you enable this, make sure to sanitize the markdown to make sure only your commands are rendered

**Comment by connor4312** [comment] 2022-01-11 23:13
@mjbvz it looks like `markdown.showPreview` only takes `DynamicPreviewSettings`, which don't include a trusted boolean. Is there a different approach I should use in that case?

**Comment by mjbvz** [comment] 2022-01-11 23:27
Are you using the full markdown preview? Not `vscode.MarkdownString`? If so, no we don't support commands in the markdown preview

**Comment by connor4312** [comment] 2022-01-11 23:45
Yea. I show the markdown message inline in the peek view, but have a button to open it in a full editor. For example, messages with expected/actual results are shown in a diff editor.

**Comment by rchiodo** [comment] 2022-01-26 22:34
Connor do you have verification steps for this? Thanks.

**Comment by connor4312** [comment] 2022-01-26 22:45
Marking verified with @jdneo's feedback
