### ISSUE TITLE
Error when typing in Korean

### ISSUE THREAD

**Issue by jinkyu-mirrappa** [microsoft/vscode#194668] opened 2023-10-02 22:38 UTC
Type: <b>Bug</b>

I can't write sentences because consonants and vowels come out as if they were typed randomly when typing in Korean

VS Code version: Code 1.82.3 (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T10:51:22.294Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7730U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (7.62GB free)|
|Process Argv|--crash-reporter-id adb8dde1-4dfa-4e5c-9449-9d6b3a642230|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
multi-cursor-case-preserve|Car|1.0.5
vscode-markdownlint|Dav|0.52.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.3.0
vscode-html-css|ecm|1.13.1
vsc-material-theme|Equ|33.10.5
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-ko|MS-|1.82.2023091309
vscode-edge-devtools|ms-|2.1.3
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.30.1
LiveServer|rit|5.7.9
html-to-css-autocompletion|sol|1.1.2
vscode-icons|vsc|12.5.0
vim|vsc|1.26.0
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
3ch9d444:30846783
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmpsinfo:30842941
dsvsc015:30845448

```

</details>

**Comment by tamuratak** [comment] 2023-10-02 23:01
Might be duplicate of VSCodeVim/Vim/issues/8570

**Comment by KOR-Believer** [comment] 2023-10-16 04:51
In my opinion, this issue seems to be related to the display language.

https://github.com/microsoft/vscode/issues/193017
I was experiencing the above issue, so I manually changed Configure display language to `ko`.

The UI was applied normally. 
However, a Korean input error similar to the issue in the current post occurred.

**Comment by aiday-mar** [comment] 2024-09-05 11:32
Hi to better assist you, could you please give examples where this happens with a screen recording. Could you please indicate what you are typing and the keyboard type you are using? Thank you.

**Closed** 2024-09-13 11:26 UTC
Labels: info-needed, windows, editor-input-IME
