### ISSUE TITLE
Typing Korean in an editor and then clicking will duplicate the character that was being typed

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13818] opened 2016-10-16 03:22 UTC
- VSCode Version: Code - Insiders 1.7.0-insider (bbda59212ba3c603addfaa4854b35801fe04d92e, 2016-10-14T06:21:38.227Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04
- Extensions: EditorConfig.EditorConfig-0.3.3, Tyriar.lorem-ipsum-1.0.0, Tyriar.terminal-tabs-0.0.6, Tyriar.theme-glacier-0.0.10, cssho.vscode-svgviewer-1.2.0, felipecaputo.git-project-manager-0.1.15, gerane.Theme-Wombat-0.0.2, ms-vscode.csharp-1.4.1, ms-vscode.typescript-javascript-grammar-0.0.4, peterjuras.fontsize-shortcuts-1.0.0, redhat.java-0.0.5, ryu1kn.annotator-0.10.1

Steps to Reproduce:
1. Install Korean IME (I was using "Korean (Hangul) (IBus)")
2. Activate IME
3. Type a character, eg. `a` -> `ㅁ`
4. Click the editor, the `ㅁ` will become `ㅁㅁ`

**Notes**
- This _does not_ happen with the Japanese IME, presumably because Korean characters take multiple keystrokes for a single character.
- This appears to happen on Chrome, `textarea`s as well except the click will put the character where the cursor clicked, not at the end.

**Comment by Tyriar** [comment] 2016-10-16 04:19
This may be the IME I'm using.

**Comment by alexandrudima** [comment] 2016-10-24 16:50
If this reproduces in Chrome's vanilla `textarea`s then please file an issue against Chromium.

**Comment by omusil24** [comment] 2017-01-27 15:40
This is AFAIK caused by the IME/IBus or something because it happens to me in other editors as well, e.g. Pluma (Gedit), Mousepad etc., except there instead of duplicating the character, it "cuts" the character I was writing and "pastes" it where I clicked. In Chrome it does the duplication...

**Comment by alexandrudima** [comment] 2017-11-24 14:42
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Closed by alexandrudima** 2017-11-24 14:42 UTC
Labels: editor-ime, upstream
