### ISSUE TITLE
VS Code Remote WSL extension does not work with Unique characters in usernames.

### ISSUE THREAD

**Issue by Strifewind** [microsoft/vscode#79255] opened 2019-08-15 23:37 UTC
- VSCode Version: 1.37.1
- OS Version: Windows 10 v.1809

Steps to Reproduce:

1. Create a new user account on a windows install with an apostrophe. (e.g Brian O'Grady)
2. Go through steps on running a remote WSL server.
3. Run Code . from the WSL terminal

Does this issue occur when all extensions are disabled?: Yes

Bellow is a screen capture of the error when it occurred. 

![image](https://user-images.githubusercontent.com/12420545/63133580-c398d800-bf7a-11e9-9871-99a3334615ea.png)

**Comment by aeschli** [comment] 2019-08-20 10:14
duplicate of https://github.com/microsoft/vscode-remote-release/issues/1098

**Closed by aeschli** 2019-08-20 10:14 UTC
Labels: new release
