### ISSUE TITLE
Webview panel tabs sometimes get closed two times per the keyboard stroke (Cmd+W)

### ISSUE THREAD

**Issue by raqystyle** [microsoft/vscode#188669] opened 2023-07-24 11:47 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.80.1 (Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771)
- OS Version: macOS (13.4.1 (c) (22F770820d))

**Steps to Reproduce:**

1. Download the Postman extension and login
2. Start opening and closing tabs using your keyboard.
4. Notice that sometimes, more than one tab is closed per keystroke (<kbd>Cmd + W</kbd>)

Here's a demo (the issue is visible in the beginning and in the end of the recording):

https://github.com/microsoft/vscode/assets/1846484/3131fc95-f78e-4cdb-b9a5-a354bec247c8

Here's another clip with keystrokes:

https://github.com/microsoft/vscode/assets/1846484/c20a110a-b81a-4feb-b3c1-ccd2846e1aad

As suggested by @r3m0t in a thread (https://github.com/microsoft/vscode-discussions/discussions/709), I logged the keyboard interactions. Here is the log output for when the "double closing" is happening:

```
2023-07-24 13:19:29.269 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
2023-07-24 13:19:29.270 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
2023-07-24 13:19:29.270 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2023-07-24 13:19:29.327 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyW, keyCode: 87, key: w
2023-07-24 13:19:29.327 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyW, keyCode: 53 ('W')
2023-07-24 13:19:29.327 [info] [KeybindingService]: | Resolving meta+[KeyW]
2023-07-24 13:19:29.328 [info] [KeybindingService]: \ From 4 keybinding entries, matched workbench.action.closeActiveEditor, when: no when condition, source: built-in.
2023-07-24 13:19:29.328 [info] [KeybindingService]: + Invoking command workbench.action.closeActiveEditor.
2023-07-24 13:19:29.333 [info] [KeybindingService]: / Dispatching keybinding triggered via menu entry accelerator - cmd+w
2023-07-24 13:19:29.333 [info] [KeybindingService]: | Resolving meta+[KeyW]
2023-07-24 13:19:29.334 [info] [KeybindingService]: \ From 4 keybinding entries, matched workbench.action.closeActiveEditor, when: no when condition, source: built-in.
2023-07-24 13:19:29.334 [info] [KeybindingService]: + Invoking command workbench.action.closeActiveEditor.
2023-07-24 13:19:29.381 [info] [KeybindingService]: + Storing single modifier for possible chord meta.
2023-07-24 13:19:29.427 [info] [KeybindingService]: + Clearing single modifier due to other key up.
2023-07-24 13:19:47.318 [info] [KeybindingService]: / Soft dispatching keyboard event
2023-07-24 13:19:47.319 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
```
... compared to the logs of when a single tab is closed correctly:
```
2023-07-24 13:24:41.889 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
2023-07-24 13:24:41.889 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
2023-07-24 13:24:41.889 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2023-07-24 13:24:41.962 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyW, keyCode: 87, key: w
2023-07-24 13:24:41.962 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyW, keyCode: 53 ('W')
2023-07-24 13:24:41.962 [info] [KeybindingService]: | Resolving meta+[KeyW]
2023-07-24 13:24:41.962 [info] [KeybindingService]: \ From 4 keybinding entries, matched workbench.action.closeActiveEditor, when: no when condition, source: built-in.
2023-07-24 13:24:41.962 [info] [KeybindingService]: + Invoking command workbench.action.closeActiveEditor.
2023-07-24 13:24:42.011 [info] [KeybindingService]: + Storing single modifier for possible chord meta.
2023-07-24 13:24:42.045 [info] [KeybindingService]: + Clearing single modifier due to other key up.
```
As you can see in the first excerpt, the `workbench.action.closeActiveEditor` is invoked two times, and the second time `triggered via menu entry accelerator`.

**Comment by mjbvz** [comment] 2023-08-08 21:39
Duplicate of #173674

**Closed by mjbvz** 2023-08-08 21:39 UTC
