### ISSUE TITLE
Show the number of lines in selection on the status bar

### ISSUE THREAD

**Issue by madhu-rapolu** [microsoft/vscode#111838] opened 2020-12-03 19:35 UTC
When I select some text in the editor, I see only the number of characters selected. But I want to see how many lines are in that selected text. Surprisingly, many editors do not have that feature. I had made updates to Programmers' Notepad and jEdit for this to happen and this feature has been enormously handy for me.

As a simple use case, you have a long list of vegetable names, each name on a line,  in your editor. I select top 12 lines. How many items have I selected? I should be able see that info on the status bar.

**Comment by yume-chan** [comment] 2020-12-04 03:11
Duplicate of #51450

I'm thinking of making a "full featured" status bar cursor/selection indicator replacement extension but I don't think I have enough time.

**Closed** 2020-12-04 21:19 UTC
Labels: *duplicate
