### ISSUE TITLE
Drop-down menu not appearing after clicking Manage icon while previewing Markdown file

### ISSUE THREAD

**Issue by jmsnavarro** [Microsoft/vscode#68501] opened 2019-02-12 08:30 UTC
- VSCode Version: 1.32.0-insider, 1.31.0
- OS Version: Windows 7  (6.1.7601)

Steps to Reproduce:
1. Preview a markdown file
2. Click Manage icon
   
   ![image](https://user-images.githubusercontent.com/17264947/52622134-08688700-2ee4-11e9-8e5d-d75909d6bf9c.png)

3. Click any of the following will not open the drop-down menu at the top-center of the app
   - Command Pallet
   - User Snippets
   - Color Theme
   - File Icon Theme

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-02-12 19:36
Duplicate of #68019

**Closed by mjbvz** 2019-02-12 19:36 UTC
Labels: bug, markdown, webview, workbench-menu
