### ISSUE TITLE
intellisense in html files

### ISSUE THREAD

**Issue by yussica** [Microsoft/vscode#4800] opened 2016-03-30 14:47 UTC
- VSCode Version:0.10.11
- OS Version:OS X 10.10.5

When I edit a html file with some javascript code, there is no intellisense. But the previous version does have the intellisense. For instance, I typed 'aler', vscode would popup a list to choose. In the latest version html file only intellisense html tags

**Comment by aeschli** [comment] 2016-03-31 08:39
duplicate of #3465

**Closed by aeschli** 2016-03-31 08:39 UTC
Labels: html
