### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted

### ISSUE THREAD

**Issue by MAQ7** [Microsoft/vscode#24581] opened 2017-04-12 08:31 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-npm-source|dkundel|1.0.0|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|code-runner|formulahendry|0.6.15|
|terminal|formulahendry|0.0.7|
|live-html-previewer|hdg|0.0.1|
|vscode-angular2-emmet|jakethashi|1.0.11|
|Angular2|johnpapa|2.2.3|
|node-module-intellisense|leizongmin|1.3.0|
|vscode-extension-auto-import|moppitz|1.3.3|
|vscode-less|mrmlnc|0.6.2|
|node-modules-resolve|naumovs|1.0.2|
|vscode-icons|robertohuertasm|7.5.1|
|bootstrap4-vscode|thekalinga|2.3.3|
|theme-monokai-black|vip32bit|0.1.0|
|expresssnippet|vladmrnv|0.1.0|
|html-less-class-completion|wangkechun|0.0.6|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1. unknown
2.

**Comment by mjbvz** [comment] 2017-04-12 21:13
A few questions:

* Do you see any other messages or just the warning/error about TypeScript not being restarted?
* Are you using a custom `typescript.tsdk` setting?
* Does this happen for all projects you open, or only some projects?
* Does it happen if you disable extension? Try launching code with `--disable-extensions`

Can you also try collecting the TypeScript server logs:

1. In VSCode 1.11, add a setting`"typescript.tsserver.log": "verbose"`
2. Reload VSCode and reproduce the issue
3. Run the `Open TS Server Log file command`
4. Share the output from there.

Log collection may not actually work in this case since TypeScript is crashing on boot. Let me know if this is the case

Thanks

**Comment by MAQ7** [comment] 2017-04-14 06:52
_Do you see any other messages or just the warning/error about TypeScript not being restarted?_
**no other messages**.

_Are you using a custom typescript.tsdk setting?_
**no**

_Does this happen for all projects you open, or only some projects?_
**yes**

_Does it happen if you disable extension? Try launching code with --disable-extensions_
**Still appears after disabling all extensions.**

TypeScript server log command did not produce any output.

**Comment by MAQ7** [comment] 2017-04-15 06:48
please notice that I updated vs code to 1.11.2 and still facing the same issue.

**Comment by mjbvz** [comment] 2017-04-17 23:05
Let's try the old method of log collection then:

From a command line, run:

Windows:
```
set TSS_LOG=-level verbose -file c:\tmp\tsserver.log
code 
```

Reproduce the problem in VSCode and then share the `tsserver.log` file found in ` c:\tmp\tsserver.log`



If you still don't see anything there, instead try:

* 1. Set `"typescript.tsserver.trace": "verbose",` in your user settings
2. Restart VSCode and reproduce the problem
3. Open the output pane and share the output from `TypeScript`


 > **⚠️Warning:** The TypeScript log/trage may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

Thanks

**Comment by ibrahimduran** [comment] 2017-04-27 18:05
I'm having the same issue too. I've tried setting `typescript.tsserver.trace`, `typescript.tsserver.log` to `verbose` and running code with env variable: `TSS_LOG="-level verbose -file ~/tss.log"` but I'm not able to see any logs.

Stacktrace:
```
shell.ts:475
Service died.: Error: Service died.
    at Object.keys.forEach (/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:622:45)
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:621:37)
    at ChildProcess.childProcess.on (/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:435:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by MAQ7** [comment] 2017-04-28 12:29
That did not work for me either. However, I figured out the root cause of this issue for me. I think that the issue is in the value for  "typescript.tsdk" in the user settings inside settings.json
I remember that I changed because the windows path format C:\Users\username\......\typescript\lib was giving error "invalid escape character". So, I changed it just to get rid of this error message and that introduced this issue. 
I set it back to the old value and now I am not getting this issue anymore. But, the windows path format is not accepted and VSCode gives a Warning message: typescript\lib does not point to a valid tsserver install. Falling back to bundled TypeScript version.

What should be the value for "typescript.tsdk" in the user settings?

**Comment by MAQ7** [comment] 2017-04-29 11:57
Alright, it works fine now. Either set  "typescript.tsdk": "./node_modules/typescript/lib" which refers to the local installation for the current project. 
Or,  using the double slash to refer to the global installation "typescript.tsdk": "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib".

**Comment by mjbvz** [comment] 2017-04-29 18:49
Glad you found a solution. Here's more information about configuring the typescript.tsdk setting: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions On windows, you can use windows style paths as long as the backslashes are escaped. This is a quirk of the json format that we use to store settings. For workspace local tsdk settings, I recommend using unix style paths

Closing since it sounds like the issue has been resolved

**Closed by mjbvz** 2017-04-29 18:49 UTC
Labels: bug, freeze-slow-crash, javascript, needs more info, typescript
