### ISSUE TITLE
Selection length of 4 byte Unicode characters is incorrectly calculated

### ISSUE THREAD

**Issue by Daninet** [microsoft/vscode#62286] opened 2018-10-31 13:51 UTC
Issue Type: <b>Bug</b>

Reproduction:

1. Create new file
2. Copy this character there: 𠜎
This is a 4 byte Unicode character.
3. Select all
4. On right side of the status bar it shows '2 selected' in place of 1 selected. Column number is also wrong.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexandrudima** [comment] 2019-10-18 15:24
Duplicate of #34497

**Closed by alexandrudima** 2019-10-18 15:24 UTC
Labels: bug, workbench-status
