### ISSUE TITLE
Error on shorcut with VSCODE using the mouse logitech MX

### ISSUE THREAD

**Issue by pookdeveloper** [microsoft/vscode#81578] opened 2019-09-28 07:24 UTC
I use the mouse logitech MX, I have shorcuts when I click in one button to close one tab of window, but when I click it paste the clipboard first before closing the window, only pass in visual code not in other app   see this video please:

https://www.loom.com/share/2d593730134e44929d0db150de146ff4

There are more people with the same problem

https://support.logi.com/hc/en-us/community/posts/360034878813-key-assignment-error?page=1#community_comment_360008852314

Thanks

**Comment by alexandrudima** [comment] 2019-10-10 10:57
Duplicate of #80804

**Closed by alexandrudima** 2019-10-10 10:57 UTC
Labels: editor-clipboard, feature-request, keybindings, mac
