### ISSUE TITLE
Refactoring broken in TypeScript files with uppercase characters in filename

### ISSUE THREAD

**Issue by pbaer** [Microsoft/vscode#40682] opened 2017-12-22 00:19 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
search-node-modules|jas|1.2.0
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.0.0

---

Steps to Reproduce:

1. Have a file with an uppercase name, e.g. Foo.ts
2. Put the cursor on an identifier and press F2 to rename it to some other name.

Result:

1. Sometimes (I don't know how to consistently repro this, it always happens with certain files but if I create a new file from scratch this does not repro), a second tab with the lowercase foo.ts will show up in the IDE - there are now TWO tabs for the same file! One using the uppercase Foo.ts, the other the lowercase foo.ts.
2. If autosave was OFF, then this refactoring operation leads to corruption in the file - the refactored name shows up garbled, in the wrong place in the file, etc.
3. If autosave was ON, then the first refactoring appears to work fine, but subsequent ones lead to the same corruption as described in #2.

Reproduces without extensions: Yes

**Comment by pbaer** [comment] 2017-12-22 18:58
I've been trying to narrow down the repro steps for this. It's very strange. I have one existing file in my workspace that I can 100% consistently repro with, but I can't manually repro it with a newly created file.

And the repro only occurs when the file in question is called Node.ts. If I rename it to say Node2.ts, the problem does not repro. It does not repro if I create another file in another folder called Node.ts, or another file in the same folder with a different name. I've tried nuking my git repo and recreating it, renaming the project root directory, none of it makes a difference.

**Comment by pbaer** [comment] 2017-12-22 19:29
Other things I've tried: nuking my temp folder and the %USERPROFILE%\AppData\Roaming\Code folder, didn't help.

**Comment by mjbvz** [comment] 2017-12-22 19:31
@pbaer Try closing all editors and then restarting VS Code. I think we may be getting into a bad state where we cache the incorrect editor path after a file's casing has changed

**Comment by pbaer** [comment] 2017-12-22 20:06
Yes, I've tried that. Also, I'm not the only person on my project who can repro this - others enlisted in the same repo are seeing the same problem.

We've confirmed we see the same behavior on the same set of files. What they all have in common is that a) the first character of the file name is capitalized (most of our files are all lowercase) and b) they were added to our repo "a while ago" (this seems to be a weak correlation, as there are some exceptions)

**Comment by pbaer** [comment] 2017-12-22 20:26
Just found a 100% repro. It's changing the casing that triggers this behavior, somehow:

1. Add a file named Foo.ts that contains:

class Something {
    public foo(left: number, right: number) {
    }
}

2. Close the file in VSCode
3. Outside VSCode, rename the file to foo.ts
4. Open the file in VSCode
5. Use F2 to rename the left parameter name to something else

Result:

- The refactoring doesn't apply
- Another tab with the old name, Foo.ts, pops up behind foo.ts
- Subsequent attempts to refactor will eventually result in file corruption

**Comment by ttamminen** [comment] 2017-12-29 08:03
Just letting you know that I have encountered the same issue but in my case, I changed only the filename (in the Code).

I also have a TypeScript project like Mr. @pbaer. I had some import statements that referred to the old lowercase name, I wonder if that could cause something.

![image](https://user-images.githubusercontent.com/1038081/34432365-33fd0998-ec7f-11e7-9b51-28e5b6ee98ee.png)

**Comment by pbaer** [comment] 2018-01-02 17:45
Glad that I'm not the only one seeing this. Though FWIW, I don't see a link between the casing of the import statements and which files exhibit this problem (and note that my repro scenario above doesn't involve importing Foo.ts anywhere).

**Comment by mjbvz** [comment] 2018-01-04 18:59
Root caused by #12448

@bpasero I now realized #12448 is behind a number of TS/JS issues. Any progress on this, or are there any TS extension specific workarounds we could try? The core problem is that we trust that the document uris  vscode hands us are the real, case-sensitive file paths. Neither the ts extension or the ts server it seems has logic to understand that `FOO.ts` and `foo.ts` are in-fact the same file

**Comment by bpasero** [comment] 2018-01-05 06:55
@mjbvz not much progress because the underlying issue is that node.js does not provide a fast way to find out if 2 file paths are the same. If you look at [`realcaseSync`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/extfs.ts#L418) you can see a user-land implementation of this which is slow for obvious reasons (you basically call `readdir` for each path segment). 

If you only call this once for a refactoring it may be feasible to include this code in the TS extension and use it to compare 2 paths.

**Comment by mjbvz** [comment] 2018-01-05 21:40
Thanks @bpasero! Refactoring is perhaps the most noticeable impact but the bug does also causes problems for other JS/TS features such error reporting, rename, and go do definition. I've been bitten by that a few times and only been able to get back into a good state by closing all editors and clearing the quick open history

A refactoring specific fix may still be worth doing though, either using something like `realcaseSync` or adding logic to check if the refactoring's changed file path matches the currently opened file case-insentiviely when creating the refactoring `WorkspaceEdit`. (Also, I think all current refactoring only touch the current file, so we could leverage that)

@mhegazy @andy-ms Any thoughts on the issue? Has TS faced a similar problem?

**Comment by mhegazy** [comment] 2018-01-05 23:52
> Has TS faced a similar problem?

yes. and given the lake of a fast way to get the actual path, we have a rather limited support for flagging path mismatches under `--forceConsistentCasingInFileNames`; it checks that all references in the code (import statements basically) use the same casing, and not the name of the file on disk.

I wounder if `--forceConsistentCasingInFileNames` would help flagging places where the wrong filename is referenced differently.

**Comment by mjbvz** [comment] 2018-06-21 17:22
This should be fixed in the latest insiders builds. If you still see this issue, please open a new issue with repo steps and I'll take another look

**Closed by mjbvz** 2018-06-21 17:22 UTC
Labels: bug, typescript
