### ISSUE TITLE
TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45556] opened 2018-03-12 06:53 UTC
From https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=b1e80686-71f3-2933-67b2-0edb530508ec

```
TypeError: Cannot read property 'value' of null
/vs/workbench/services/extensions/electron-browser/extensionService.ts#357:16 (onComplete)
/vs/base/common/winjs.base.raw.js#1579:0 (then)
/vs/workbench/services/extensions/electron-browser/extensionService.ts#356:41 (_activateByEvent)
/vs/workbench/services/extensions/electron-browser/extensionService.ts#348:64 (onComplete)
/vs/base/common/winjs.base.raw.js#1183:0 (_notify)
/vs/base/common/winjs.base.raw.js#865:0 (enter)
/vs/base/common/winjs.base.raw.js#1081:0 (_run)
/vs/base/common/winjs.base.raw.js#1049:0 (_completePromise)
/vs/base/common/async.ts#286:7 (open)
/vs/workbench/services/extensions/electron-browser/extensionService.ts#446:35
```

**Comment by vscodeerrors** [comment] 2018-03-14 22:24
Here is another similar callstack 

TypeError: Cannot read property 'value' of null<br />[TypeError: Cannot read property 'value' of null](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/srcTypeError: Cannot read property 'value' of null)<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1579:0 (then)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1579:0 (then))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent))<br />[/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call))<br />[/vs/base/common/event.ts#L142:15 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L142:15 (fire))<br />[/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode))<br />[/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />

**Comment by vscodeerrors** [comment] 2018-03-14 22:31
Here is another similar callstack 

TypeError: Cannot read property 'value' of null<br />[TypeError: Cannot read property 'value' of null](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/srcTypeError: Cannot read property 'value' of null)<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1579:0 (then)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1579:0 (then))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent))<br />[/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call))<br />[/vs/base/common/event.ts#L142:15 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L142:15 (fire))<br />[/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode))<br />[/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />

**Comment by vscodeerrors** [comment] 2018-03-14 22:32
Here is another similar callstack 

TypeError: Cannot read property 'value' of null<br />[TypeError: Cannot read property 'value' of null](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/srcTypeError: Cannot read property 'value' of null)<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1579:0 (then)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1579:0 (then))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent))<br />[/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call))<br />[/vs/base/common/event.ts#L142:15 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L142:15 (fire))<br />[/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode))<br />[/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />

**Comment by vscodeerrors** [comment] 2018-03-14 22:56
Here is another similar callstack 

TypeError: Cannot read property 'value' of null<br />[TypeError: Cannot read property 'value' of null](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/srcTypeError: Cannot read property 'value' of null)<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1579:0 (then)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1579:0 (then))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent))<br />[/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call))<br />[/vs/base/common/event.ts#L142:15 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L142:15 (fire))<br />[/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode))<br />[/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />

**Comment by vscodeerrors** [comment] 2018-03-14 23:00
Here is another similar callstack 

TypeError: Cannot read property 'value' of null<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#357:16 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1579:0 (then)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1579:0 (then))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#356:41 (_activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:41 (_activateByEvent))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#341:15 (activateByEvent)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L341:15 (activateByEvent))<br />[/vs/workbench/services/mode/common/workbenchModeService.ts#135:26 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/mode/common/workbenchModeService.ts#L135:26 (call))<br />[/vs/base/common/event.ts#142:15 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L142:15 (fire))<br />[/vs/editor/common/services/modeServiceImpl.ts#157:25 (_getOrCreateMode)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L157:25 (_getOrCreateMode))<br />[/vs/editor/common/services/modeServiceImpl.ts#148:15 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/editor/common/services/modeServiceImpl.ts#L148:15 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#865:0](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L865:0)<br />

**Comment by vscodeerrors** [comment] 2018-03-15 19:33
Here is another similar callstack 

TypeError: Cannot read property 'value' of null<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#357:16 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#914:0 (enter)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L914:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#1081:0 (_run)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1081:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#1054:0 (reject)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1054:0 (reject))<br />[/vs/workbench/services/extensions/electron-browser/extensionHost.ts#315:4](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L315:4)<br />

**Comment by vscodeerrors** [comment] 2018-03-15 19:34
Here is another similar callstack 

TypeError: Cannot read property 'value' of null<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#357:16 (onComplete)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L357:16 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#914:0 (enter)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L914:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#1081:0 (_run)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1081:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#1044:0 (_chainedError)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1044:0 (_chainedError))<br />[/vs/base/common/winjs.base.raw.js#749:0 (onError)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L749:0 (onError))<br />[/vs/base/common/winjs.base.raw.js#1222:0 (_notify)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1222:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#914:0 (enter)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L914:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#1081:0 (_run)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1081:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#1054:0](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/winjs.base.raw.js#L1054:0)<br />

**Comment by alexandrudima** [comment] 2018-03-29 13:03
Duplicate of #43477

**Closed by alexandrudima** 2018-03-29 13:03 UTC
Labels: error-telemetry
