### ISSUE TITLE
"Could not find the task..." error when using a `.code-workspace` file.

### ISSUE THREAD

**Issue by JaneySprings** [microsoft/vscode#192041] opened 2023-09-02 12:32 UTC
Hello. I created a debugger for .NET apps. It's requires a `preLaunchTask: "dotnet-meteor: Build"` in the launch.json. This task is always provided by `vscode.TaskProvider` (TaskScope.Workspace):
https://github.com/JaneySprings/DotNet.Meteor/blob/main/src/VSCode.Extension/tasks/build.ts

If you are **not using** a `code-workspace` file, then you can create a `launch.json` file and run the debug. 
But if you **use** the `code-worksapce` file, then when you run the debug you will get the error:
<img width="303" alt="image" src="https://github.com/microsoft/vscode/assets/48021947/45b268d9-74e2-44a2-9718-425be47579fa">

in the debug, I see that VSCode requests a task and receives a response, but the error still occurs:
https://github.com/microsoft/vscode/assets/48021947/cdac4035-1cc6-4184-afc6-5255b6bb0be0

Does this issue occur when all extensions are disabled?: Yes

Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z (3 wks ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

**Comment by meganrogge** [comment] 2023-09-29 21:37
I cannot reproduce in insider's - it's possible this was fixed in the past month. Could you pls verify if it's working for you?

**Comment by JaneySprings** [comment] 2023-09-30 08:25
Hi! I tried on сode-Insiders version, but nothing changes :(
I created a simple extension where you can reproduce this bug:
https://github.com/JaneySprings/VSCodeLaunchBug

It also contains two folders:
https://github.com/JaneySprings/VSCodeLaunchBug/tree/main/SimpleFolder - folder with `launch.json`
https://github.com/JaneySprings/VSCodeLaunchBug/tree/main/SimpleFolderWorkspace - folder with `code-workspace`

https://github.com/microsoft/vscode/assets/48021947/5b164fef-0ae4-4c79-b83c-f9bd7fe96119

**Comment by meganrogge** [comment] 2023-10-20 17:43
thanks for the repro, but it looks like the type being used is invalid here
 
![Image](https://github.com/microsoft/vscode/assets/29464607/a395d9e9-c8a6-488c-af3e-86401d547c65)

**Comment by meganrogge** [comment] 2023-10-20 17:44
In your repro, where is `Test: task` defined? I think that's the issue.

**Comment by meganrogge** [comment] 2023-10-20 17:46
See it is working here when the task has been defined.

https://github.com/microsoft/vscode/assets/29464607/1ffaf51b-c4aa-4e09-89d2-f8aa9c57310c

**Comment by meganrogge** [comment] 2023-10-20 17:46
I get the same error when launching from the simple folder for that reason.

![Image](https://github.com/microsoft/vscode/assets/29464607/bfb55dba-4098-4ae0-9b71-e1e6bc03c2f8)

**Closed by meganrogge** 2023-10-20 17:46 UTC
Labels: bug, tasks, confirmed

**Comment by JaneySprings** [comment] 2023-10-20 17:58
@meganrogge it's work when task defined. But why is it not necessary to create `tasks.json` for a simple folder? Is this definitely not a bug?

**Comment by meganrogge** [comment] 2023-10-20 18:01
The task has to be defined somewhere - whether in the workspace file or the tasks.json for us to know what to run.
