### ISSUE TITLE
[feature] "Go To Inheritor" or "Go To Derived Symbols"

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#109711] opened 2020-10-30 00:14 UTC
Suppose I have a `BaseClass`. It would be nice to be able to go to any places in the code inherit from `BaseClass`.

F.e., if I see `BaseClass` in the code, I could run `Go To Inheritors` (or something similarly named) and see all sub classes, and navigate to them.

It'd also be sweet to be able to `Go To Inheritor Reference Sites` or similar, to be able to see all places that use `BaseClass` in any inherited fashion (so for example instead of just navigating to code like `class SubClass extends BaseClass`, it would also show locations for code like `const s = new SubClass`, `const a = new SubClass2`, etc).

This would great improve code navigation. 

For more example of the idea, here's the same question for Visual Studio:

- https://stackoverflow.com/questions/282377

Someone pointed to Resharper which adds a feature similar to the `Go To Inheritor` feature I just described (but not the `Go To Inheritor Reference Sites`):

- https://www.jetbrains.com/help/resharper/Navigation_and_Search__Go_to_Inheritor.html

**Comment by jrieken** [comment] 2020-10-30 07:43
/duplicate of https://github.com/microsoft/vscode/issues/47126

**Closed** 2020-10-30 07:44 UTC
Labels: *duplicate, editor-symbols
