### ISSUE TITLE
Can't navigate from terminal compilation error output to code editor.

### ISSUE THREAD

**Issue by fabio-510** [microsoft/vscode#79567] opened 2019-08-21 11:16 UTC
Issue Type: <b>Bug</b>

Possibly related to and old finalized issue: https://github.com/microsoft/vscode/issues/58256

Also tested on insiders (no extensions): 1.38.0-insider
Using typescript version 3.5.3

1. Open an empty folder.
2. Create a test.ts file with the following code:
```
export class test {
    private data;

    public constructor(){
        
    }
}
```
3. In the integrated terminal (powershell v5.1.18362.145) run:
```
tsc -init
tsc -p tsconfig.json
```
4. Try to navigate to compilation error using Ctrl+Click on the output:
```
test.ts:2:13 - error TS7008: Member 'data' implicitly has an 'any' type.

2     private data;
              ~~~~

Found 1 error.
```

Expected to have the file highlighted on Ctrl (like when this was working) and on Ctrl+Click open it in the code editor.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (12.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|1.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.1
template-generator-vscode|Den|0.4.1
gitlens|eam|9.9.3
vscode-element-helper|Ele|0.5.6
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|1.9.0
vscode-test-explorer|hbe|2.14.2
rest-client|hum|0.22.0
kubernetes-snippets|ipe|0.1.9
vue-autoimport|ish|1.0.2
jenkinsfile-support|ivo|0.4.4
cypher-query-language|jak|1.0.2
docthis|joe|0.7.1
solidity|Jua|0.0.58
azure-pipelines|ms-|1.155.0
azurerm-vscode-tools|msa|0.6.0
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.18.0
vscode-azurestorage|ms-|0.7.1
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.2
python|ms-|2019.8.30787
remote-wsl|ms-|0.39.2
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
notepadplusplus-keybindings|ms-|1.0.3
powershell|ms-|2019.5.0
vscode-node-azure-pack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.2
team|ms-|1.149.2
vetur|oct|0.22.2
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.4.1
sass-indented|rob|1.5.1
vscode-jest-test-adapter|rtb|0.2.0
jenkinsfile-support|sec|0.1.0
indenticator|Sir|0.6.0
element-ui-snippets|SS|0.3.5
autoimport|ste|1.5.3
azure-iot-toolkit|vsc|2.10.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|2.4.2

(2 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-08-21 15:55
Looks like duplicate of #22772

Problem is with files in root folder. If your files will be in e.g. `src` folder it would work just fine because path will be like `serc/test.ts:2:13` which can be detected as path and converted to link.

**Comment by fabio-510** [comment] 2019-08-22 15:22
Yes, that's exactly the case. Unfortunately in my case (although not reflected in the example) it is a little bit more complex than simply moving everything to a new subfolder, but at least I know why.

@IllusionMH The issue you refer is quite old. Is there any chance this has any plans on being addressed in near future?

**Comment by Tyriar** [comment] 2019-08-22 16:05
This is indeed a duplicate of https://github.com/microsoft/vscode/issues/22772, I've been contemplating removing the link verification all together for a long time due to cases like this and https://github.com/microsoft/vscode/issues/79547 but haven't pulled the trigger as it would result in a degraded experience though as so many things could be a file.

**Comment by fabio-510** [comment] 2019-08-23 14:19
Maybe a setting that defaults to true? performLinkVerification: false

**Closed** 2019-10-09 18:39 UTC
Labels: *duplicate, integrated-terminal
