### ISSUE TITLE
Adding more file icons per file type  (.toml and .jl)

### ISSUE THREAD

**Issue by musm** [Microsoft/vscode#72964] opened 2019-04-27 17:12 UTC
For some reason I am missing file types for two languages I use regularly:
`.toml` and `.jl` (julia) languages. 

This is how they currently render
![image](https://user-images.githubusercontent.com/4319522/56852829-01032800-68ee-11e9-8f6a-10a06287bae8.png)

There are satisfactory icons provided in several packages for these file types. Can we please update the icon list to include these languages. 

Thanks.

**Comment by aeschli** [comment] 2019-04-29 09:19
Is this in the Windows file explorer, or inside VSCode?
If it is inside VSCode, please file an issue against the icon theme that you are using.

**Comment by musm** [comment] 2019-04-29 13:59
This is in the windows file explorer.

**Comment by musm** [comment] 2019-04-29 16:49
In other words, it's indeed a vscode and not a package issue.

**Comment by musm** [comment] 2019-05-02 20:49
https://github.com/be5invis/vscode-iconset/blob/master/src/file.julia.svg may be used for julia

**Comment by musm** [comment] 2019-05-02 20:50
cc @misolori   since you worked on this.

**Comment by misolori** [comment] 2019-05-04 04:02
Thanks for the suggestion and we'll keep that in mind. Closing this as we don't want issues for each file type. See https://github.com/Microsoft/vscode/issues/60699#issuecomment-429208011.

**Closed by misolori** 2019-05-04 04:02 UTC
Labels: needs more info

**Comment by musm** [comment] 2019-05-06 19:31
Ok, but then which issue is tracking the missing  file types that need addition?
For example the `.toml` icon is surely a bug, since it's displaying the vscode icon.  While the others are requests.

**Comment by misolori** [comment] 2019-05-06 22:01
@musm not every single file type has a preview icon, we've kept the list small to the top ~30 file types so far.

For the bug, this appears to be a windows file system issue (we've seen this reported before) that we don't have steps to fix/clear the cache. For example, I am not able to reproduce:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/35271042/57257909-abc2c700-700f-11e9-82cb-cc9ad5193f7e.png">

<img width="197" alt="image" src="https://user-images.githubusercontent.com/35271042/57257813-62727780-700f-11e9-9147-08c3b4428754.png">
