### ISSUE TITLE
QuickFix menu filter & select by typing

### ISSUE THREAD

**Issue by timeuser** [microsoft/vscode#175774] opened 2023-03-01 18:23 UTC
It would be nice to be able to filter and select the options from the QuickFix popup menu by typing, similar to how the Command Palette works. As it is I can only move up and down with the arrow keys or select an option with the mouse. Same would apply to other popup menus like Suggest.

**Comment by mjbvz** [comment] 2023-03-01 18:53
Duplicate of #157719

**Closed by mjbvz** 2023-03-01 18:53 UTC
Labels: editor-code-actions
