### ISSUE TITLE
BUG: Intermittent bug, ocassionally instead of the configured default shell, opens terminal with PowerShell

### ISSUE THREAD

**Issue by GeorgeWL** [microsoft/vscode#144825] opened 2022-03-10 09:56 UTC
Does this issue occur when all extensions are disabled?: Unsure

- VS Code Version: 1.65.1
- OS Version: 10.0.19044 Build 19044

Steps to Reproduce:
Difficult to reproduce as it's an intermittent bug, only see it happen 1/10 times that I open the terminal
1. Open vscode on a project set to use a different shell as the default (I use Git Bash for Windows)
2. ocassionally, less than 1/10th of the time, the wrong shell opens, opening Powershell
3. when this happens it also runs powershell for the configured launch task in my tasks.json, breaking the script which only works in bash

**Comment by IllusionMH** [comment] 2022-03-10 14:23
Looks like duplicate of #142425

Do you see this only when VS Code is launched or when you create new terminals?

**Closed** 2022-03-10 14:37 UTC
Labels: *duplicate, new release

**Comment by GeorgeWL** [comment] 2022-03-11 09:48
> Looks like duplicate of #142425
> 
> Do you see this only when VS Code is launched or when you create new terminals?

only on launch yeah, never seen it happen any other time
