### ISSUE TITLE
No way to show Problems Panel, only toggle

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#31690] opened 2017-07-28 22:48 UTC
Our extension wants to show the problems panel (only the 1st time a particular issue occurs, to give visibility to the problem so users don't miss it), but calling the command workbench.actions.view.problems causes the problems panel to disappear if it's already showing. Can you provide a way to show and not just toggle the Problem panel (or get the view state so we can skip the toggle if it's already showing).

Without this improved API, we're going to do a showInformationMessage with a "Toggle Problems Panel" button, which is obviously not an ideal experience.

**Comment by Gama11** [comment] 2017-07-28 23:54
Potential duplicate of https://github.com/Microsoft/vscode/issues/11399

**Comment by sean-mcmanus** [comment] 2017-07-28 23:56
Yeah, looks like a duplicate. I searched but I didn't find that for some reason.

**Comment by rebornix** [comment] 2017-07-31 18:05
@sean-mcmanus let's track it in #11399 thanks!

**Closed by rebornix** 2017-07-31 18:05 UTC
Labels: error-list
