### ISSUE TITLE
Markdown injecting an extra backtick

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186669] opened 2023-06-29 21:14 UTC
![Recording 2023-06-29 at 14 12 08 (1)](https://github.com/microsoft/vscode/assets/2644648/8b46787f-bf26-4262-91d9-b1b57e59138b)

Steps:
* Add a single back tick at the start of a sentence
* move the cursor to the end of the sentence
* type backtick
* 🐛 2 backticks are inserted

This didn't use to be the case, I feel...

**Comment by mjbvz** [comment] 2023-07-18 23:14
This was very likely regressed by 703a75da38519117da44e2b0a3b56200db56d756. However we really should support autoclosing single and triple backticks

**Comment by weartist** [comment] 2023-07-19 01:31
I'll try to fix this

**Comment by SaadMahm00d** [comment] 2023-07-25 23:51
I'd love to take a crack at this one!

**Comment by jonschlinkert** [comment] 2023-08-23 00:47
Is there a way to override the default behavior? The changes in https://github.com/microsoft/vscode/commit/703a75da38519117da44e2b0a3b56200db56d756 have been a source of frustration. I have to delete the extra backticks every time, and I write a lot of documentation, so it's all day lol.

**Comment by mandrie** [comment] 2023-09-20 15:31
@SaadMahm00d  or @mjbvz - what build is this fixed in? Just updated to latest regular/GA build and I still see both this problem and related code block ``` problem. I am constantly manually deleting backticks :(

**Comment by mjbvz** [comment] 2023-09-20 15:51
@mandrie The issue is still open

**Comment by EXHades** [comment] 2023-10-13 10:56
same issue as https://github.com/microsoft/vscode/issues/192414 ?

**Comment by Kirlac** [comment] 2023-10-28 09:41
For anyone still having issues with this who wants to disable it until MS fixes the issue, you can simply remove a couple of lines from the JSON config to effectively revert the PR that added them: https://github.com/microsoft/vscode/pull/184532

The file is in the application install directory. For me this was in the following locations:
Win11: `%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\extensions\markdown-basics\language-configuration.json`
MacOS: `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-basics/language-configuration.json`

Just open the file and delete one or both of the following lines from the `"autoClosingPairs"` array to turn off this behaviour (for me it was around line 14):
```
{ "open": "`", "close": "`" },
{ "open": "```", "close": "```" }
```

**Comment by wdhongtw** [comment] 2024-06-28 11:06
Just a remainder, this issue was already fixed earlier and probably can be closed. :D

- commit: 6e2ea0ed2756722d1e46caae50c8f3a8f5f427b3

**Comment by mjbvz** [comment] 2024-07-02 18:40
Thanks @wdhongtw 

yes looks fixed in my testing

**Comment by mjbvz** [comment] 2024-07-02 18:40
Thanks @wdhongtw 

yes looks fixed in my testing

**Closed by mjbvz** 2024-07-02 18:40 UTC
Labels: bug, help wanted, markdown, editor-autoclosing
