### ISSUE TITLE
VS Code leaves behind files in /tmp/

### ISSUE THREAD

**Issue by vojtechkral** [Microsoft/vscode#54925] opened 2018-07-24 08:46 UTC
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.17.2-1-ARCH

Steps to Reproduce:

1. Run VS Code for a while with some extensions installed
2. Look in `/tmp/`

VS Code seems to leave files like these in `/tmp/`:

    /tmp/d08bec0a-11df-4301-b5f4-38a4545aa6a7
    /tmp/3d2bc3ac-c9f5-4b24-be2f-f3a72fb0ca89

Upon inspection, each of these turns out to be a zip file containing a vs code extension contents. I assume it's a downloaded updated version of an extension. Right now I only have the two listed above but if I don't delete them by hand they accumulate and there can be dozens of those, consuming both space and namespace in `/tmp/`.

It would be nice if VS Code:

1. Had it's own subdirectory in `/tmp/` instead of putting its files in the root
2. Deleted those files once it no longer needs them

Does this issue occur when all extensions are disabled?: Yes
Apparently disabled extensions are updated too so this happenes when extensions are disabled as well.

**Comment by vojtechkral** [comment] 2018-07-24 08:47
@vscodebot Goddamnit, I swear I tried search for this problem...

**Comment by mjbvz** [comment] 2018-07-24 18:05
Closing as duplicate of #53110

**Closed by mjbvz** 2018-07-24 18:05 UTC
Labels: extensions

**Comment by vojtechkral** [comment] 2018-07-25 08:32
@mjbvz That one is also closed, though... One of the two should stay open...
