### ISSUE TITLE
Add Zoom region when the user hover regions into the minimap

### ISSUE THREAD

**Issue by javierlopezdeancos** [microsoft/vscode#76586] opened 2019-07-04 10:20 UTC
The minimap could show a circle region Zoom when the cursor hovers this region in minimap.

**Comment by rebornix** [comment] 2019-07-17 23:52
@javierlopezdeancos can you help elaborate more about what's *circle region Zoom*?

**Comment by javierlopezdeancos** [comment] 2019-07-18 06:44
Yep sure, let me do some designs and sketch about my idea

**Comment by javierlopezdeancos** [comment] 2019-07-19 10:46
![feature](https://user-images.githubusercontent.com/1202463/61530015-2b630e00-aa23-11e9-97b6-1a0b41f6c0da.png)

**Comment by rebornix** [comment] 2019-07-19 16:50
@javierlopezdeancos thanks ;)

**Comment by rebornix** [comment] 2019-07-26 22:56
/duplicate of https://github.com/microsoft/vscode/issues/40048

**Closed** 2019-07-26 22:56 UTC
Labels: *duplicate, editor-minimap, feature-request
