### ISSUE TITLE
4th and 5th mouse buttons paste, which isn't intended.

### ISSUE THREAD

**Issue by jakearchibald** [microsoft/vscode#83635] opened 2019-10-30 08:27 UTC
Issue Type: <b>Bug</b>

I have a Logitech MX master, and I have the 4th & 5th mouse buttons mapped to the keystroke `` cmd+` `` and `` shift+cmd+` `` respectively. This means, on OSX, these buttons cycle through the windows of an app. This is done via the "Logi Options" app.

However, in VSCode, pressing these buttons also triggers 'paste'. This only happens in VSCode, it doesn't happen in other apps. It also happens with extensions disabled.

I wouldn't expect these buttons to trigger 'paste'.

VS Code version: Code - Insiders 1.40.0-insider (31f577ec88dc96ad2028699fb597b19022224b46, 2019-10-30T05:36:49.155Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 3|
|Memory (System)|16.00GB (1.53GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by alexandrudima** [comment] 2019-10-31 09:34
Duplicate of #80804

I believe this is an issue with the driver of this specific mouse. I think I saw on their marketing page that the mouse contains clipboard-like functionality and perhaps that is misbehaving... Please read through #80804 , there is also a thread on their forum..

**Closed by alexandrudima** 2019-10-31 09:34 UTC

**Comment by jakearchibald** [comment] 2019-10-31 15:51
Ah, sorry I didn't find the other issue.
