### ISSUE TITLE
Builtin console rendering broken for Pry, certain other interactive tools via SSH

### ISSUE THREAD

**Issue by mistydemeo** [microsoft/vscode#121508] opened 2021-04-16 21:03 UTC
- VS Code Version: 1.55.2
- OS Version: 11.2.3

Attempting to open the Ruby REPL Pry in the VS Code terminal while connected to a server via SSH will result in garbage ANSI escape codes being printed to stdin. This also reproduces in other tools that are built on top of Pry, such as the Rails console. It looks like it might be a response to a query of the cursor position.

This is fixed in Insiders. I haven't identified the specific fix but if it's possible to backport that to a stable release, it would be very helpful. I don't think this is a bug in the SSH extension because I'm using the same version in both stable and Insiders (0.65.3) and it only reproduces in stable.

I'm not entirely sure when this started, but I've seen other reports within the past two weeks. It likely started sometime in late March. Sample: https://stackoverflow.com/questions/66893720/rails-console-populates-with-strange-characters-in-visual-studio-code

Steps to Reproduce:

1. Launch an SSH connection to a remote project.
2. Open the console.
3. Launch `pry` or `rails console`.

![image](https://user-images.githubusercontent.com/780485/115083677-9d001280-9ebc-11eb-9101-6e413a2ba110.png)

Expected behaviour:

Entering text works fine.

Actual behaviour:

Each line contains some stray ANSI escape codes in stdin.

Does this issue occur when all extensions are disabled?: No (because the SSH extension is mandatory)

**Comment by kumi-ryu** [comment] 2021-04-21 08:00
I have the same symptoms.
But it's not Pry, it's Irb.

In Insiders (1.56) I think the symptoms are gone.

**Comment by meganrogge** [comment] 2021-04-22 20:57
Duplicate of #120352

**Closed** 2021-04-22 20:57 UTC
Labels: *duplicate, bug, integrated-terminal
