### ISSUE TITLE
Code Unreadable

### ISSUE THREAD

**Issue by MARCTELLY** [microsoft/vscode#225085] opened 2024-08-07 19:54 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92
- OS Version:  MacOs 14.5

my code on vs code has become humanly impossible to read after starting an update to version v1.92.
I've disabled all extensions, restarted the computer or even changed the encoding but the problem remains. 
I downgraded the version to be able to work.
![Uploading Screenshot 2024-08-07 at 21.53.47.png…]()

**Comment by IllusionMH** [comment] 2024-08-09 00:01
Your screenshot didn't load.

I would guess that it might be duplicate of #224115
Is you have same problem - check comments that suggest possible workarounds and CLI arguments to try

**Closed** 2024-08-16 11:24 UTC
Labels: info-needed
