### ISSUE TITLE
-n and --new-window flags do not seem to be working

### ISSUE THREAD

**Issue by lukebatchelor** [Microsoft/vscode#25609] opened 2017-04-28 08:23 UTC
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. open an instance of code from the command line `code .`
2. open a second instance of code for the same directory using the `--new-window` flag (`code --new-window .`

I seem to get the same window again. These flags are documented [here](https://code.visualstudio.com/docs/editor/command-line)

I get this same behaviour when debugging an extension locally

```
{
    "name": "Launch Extension",
    "type": "extensionHost",
    "request": "launch",
    "runtimeExecutable": "${execPath}",
    "args": ["--new-window", "/Users/lbatchelor/test-directory", "--extensionDevelopmentPath=${workspaceRoot}" ],
    "stopOnEntry": false
},
```

**Comment by yfdyh000** [comment] 2017-05-23 16:08
It's working (`code` vs `code -n`) but it seem not work for repetitive workspaces.

**Comment by yfdyh000** [comment] 2017-05-24 15:41
Duplicate of #2686.

**Comment by chrmarti** [comment] 2017-05-24 17:02
Indeed, thanks @yfdyh000 .

**Closed by chrmarti** 2017-05-24 17:02 UTC
