### ISSUE TITLE
Editor doesn't scroll when extending selection to the right

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23644] opened 2017-03-30 07:05 UTC
* mac
* open a file that requires h-scrolling
* navigate to a work close the right border
* press <kbd>Shift+Alt+ArrowRight</kbd> to extend the selection word by word
* 🐛 the editor scroll horizontally

![mar-30-2017 09-02-27](https://cloud.githubusercontent.com/assets/1794099/24491524/fdce4cc6-1527-11e7-9be7-b6e24c887196.gif)

**Comment by alexandrudima** [comment] 2017-03-30 07:11
Duplicate of #23354

**Closed by alexandrudima** 2017-03-30 07:11 UTC
