### ISSUE TITLE
In-consistent syntax hightening in Markdown for C lang

### ISSUE THREAD

**Issue by nainardev** [microsoft/vscode#109249] opened 2020-10-23 16:42 UTC
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 6.3.9600 

![Screenshot (1012)](https://user-images.githubusercontent.com/59839368/97029343-ecebc580-157a-11eb-93fd-9d66c3d6f771.png)
## Steps to Reproduce:
1. Write some code in C with comments in markdown, source and preview markdown
## Issues: 
> Terms: source - a.c; md - C.md; md preview - Preview C.md
* No difference in syntax highlighting between `_Bool` and `bool` in md preview but present in source
* Wrong syntax highlighting for `#include` in md preview but correct in others
* Comment at the end of `#include` is rendered wrong in md preview
* Wrong syntax highlighting for arguments & comment at the EOL for `printf` in md
* No syntax highlighting for function body of `int main()` in md, but works if that code block included only function body (see 1st code block in md)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-10-23 18:17
Duplicate of #34525

**Closed by mjbvz** 2020-10-23 18:17 UTC
