### ISSUE TITLE
Weird cursor behavior

### ISSUE THREAD

**Issue by towry** [Microsoft/vscode#19920] opened 2017-02-04 09:57 UTC
- VSCode Version: 1.9.0 (1.9.0)
- OS Version: macOS Sierra, 10.12.2 (16C67)

After I upgrade VScode to the latest version (1.9.0), there is a weird cursor behavior while I am typing.

<img width="338" alt="2017-02-04 5 49 57" src="https://cloud.githubusercontent.com/assets/8279858/22617537/d4300e3a-eb02-11e6-8467-660a277cf897.png">

<img width="295" alt="2017-02-04 5 50 25" src="https://cloud.githubusercontent.com/assets/8279858/22617539/d83c9eee-eb02-11e6-99dc-579d15e6bf5e.png">

The cursor always behind one character in the current line. If I move cursor backward one character, then it becomes what the second picture shows.

Is it a feature or something else? It's weird.

**Comment by gansai** [comment] 2017-02-04 10:23
I tried to reproduce this by downloading latest VSCode - 1.9.0.
OS - Windows 7 - version 6.1.7601

I am not able to reproduce this issue.

**Comment by towry** [comment] 2017-02-04 10:31
@gansai OS Version info updated, I use macOS.

**Comment by gansai** [comment] 2017-02-04 10:39
ok. There is a cursor feature, which can be used to add text or perform editing simultaneously on multiple lines. This can be activated by using either keyboard shortcut  or by navigating to Selection -> Add Cursor Above (Alt+Ctrl+Up) or Add Cursor Below ( Alt+Ctrl + Down )  or Add Cursors to line ends ( Alt+Shift+I ).

But, since I dont have a Mac, I cannot check the behavior. But added above details about cursor feature. Still, not sure, how 's' gets added if cursor is moved backward, as you mentioned.

**Comment by towry** [comment] 2017-02-04 11:05
@gansai I just find out that it might be can reproduced on comment string.

![2017-02-04 7 02 20](https://cloud.githubusercontent.com/assets/8279858/22617988/9c44191c-eb0c-11e6-995e-d7a3de528178.png)

**Comment by eduardonunesp** [comment] 2017-02-05 00:05
VSCODE Version 1.9.0 (1.9.0)
macOS Sierra 10.12.2

Same issue here, the cursor is very weird, looks like it is one caracter after the real position.

![screen shot 2017-02-04 at 22 03 07](https://cloud.githubusercontent.com/assets/582516/22622605/0bd2607c-eb26-11e6-8e8b-393b3924019b.png)

**Comment by eduardonunesp** [comment] 2017-02-05 00:14
Tested with VSCODE Version 1.8.1 and it's ok

**Comment by chelexey** [comment] 2017-02-06 13:30
VSCode v.1.9 / macOS Sierra, 10.12.3 
- same issue

**Comment by alexandrudima** [comment] 2017-02-06 14:00
Duplicate of #19808

-- the fix is already on the insiders channel and I would be very happy if you could confirm that it resolves the issue for you.

We will cherry-pick the fix in the upcoming 1.9.1 release

**Closed by alexandrudima** 2017-02-06 14:00 UTC

**Comment by eduardonunesp** [comment] 2017-02-07 09:39
Tested with Insiders version and seems fine the issue is gone
