### ISSUE TITLE
Feature request `"explorer.sortOrder": "filesFirstOnlyInNested"` and `"explorer.sortOrderByPath"`

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#170019] opened 2022-12-26 02:08 UTC
Hi
We have something like this:

```json
"explorer.sortOrder": "filesFirst"
```

Can we have something like this too:

```json
"explorer.sortOrder": "filesFirstOnlyInNested"
```

So, de difference is, only the root folders and their files and folder will be affected.

---

Also, I think it would be awesome if we were able to use and change this config option for different paths. For example:

```json
"explorer.sortOrderByPath": {
  "./": "default",
  "./*": "filesFirst",
  "./blah": "default",
  "./blah/blah": "mixed"
}
```

That's all. Thanks

**Comment by lramos15** [comment] 2022-12-27 17:07
There's many explorer sort requests and I think the only way to resolve them is by some sort of API which allows extensions to completely customize sort behavior. Closing as duplicate of https://github.com/microsoft/vscode/issues/27286

**Closed by lramos15** 2022-12-27 17:07 UTC
