### ISSUE TITLE
Grid: provide a proper way to find a neighbour group

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50679] opened 2018-05-29 14:50 UTC
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

Give the following state (View > Editor Layout > Grid):

![image](https://user-images.githubusercontent.com/2193314/40666530-d220ef70-6314-11e8-97db-ba2fd845b448.png)

Running `View: Focus Right Editor Group` ends up focusing the editor group below:

![image](https://user-images.githubusercontent.com/2193314/40666582-f2325650-6314-11e8-980c-0d0b3c1f2ac3.png)

**Comment by Tyriar** [comment] 2018-05-29 14:53
This also applies to focus left editor group.

**Comment by bpasero** [comment] 2018-05-29 16:23
@joaomoreno as discussed, ideally the gridwidget can provide this functionality of finding the next group. My logic is currently not taking into account that the root orientation can be different. As such, I can reproduce this issue by:
* entering grid layout
* flipping the editor layout once
* triggering the action `View: Focus Right Editor Group`

(it may also reproduce without the flipping if the root orientation is already in the order to reproduce)

**Comment by bpasero** [comment] 2018-06-01 09:09
This landed and can be verified with the Focus Group Up/Down/Left/Right commands. @Tyriar maybe you could do that since you know how it behaves e.g. in terminals.

Build: [macOS](https://az764295.vo.msecnd.net/insider/08cacfaa32ca6ca092b901c013e910192d88ea1f/VSCode-darwin-insider-unsigned.zip)

**Closed by bpasero** 2018-06-01 09:09 UTC
Labels: bug, workbench-grid

**Comment by aeschli** [comment] 2018-06-01 14:03
Very nice!
