### ISSUE TITLE
Visual Studio Code & node.js: Debugger exits without error message on "utils.format"

### ISSUE THREAD

**Issue by mindruptive** [Microsoft/vscode#2484] opened 2016-01-28 09:24 UTC
Node 5.3, VS Code 0.10.6, Windows 8.1

- node.js application logging debug output to the console.
- Running it as "node myApp.js" works fine: The app runs and all the "console.log" statements are correctly printed to  stdout resp. stderr. 
- Running it as "node debug myApp.js" worsk fine, too.
- When I launch the same "myApp.js" in VS Code, the debuger exits (shuts down the app) on the first "console.log('Logging a complex object: %O', myComplexObject)". It does not print any error messages.
- Narrowing down the error, I found out that "util.format()" with a complex object causes the problem, not the logging itself.

**Comment by weinand** [comment] 2016-01-29 09:57
@mindruptive that seems to be a problem in node 5.3. Node 5.3 is crashing on this program:
```js
var myComplexObject = { name: "foobar" };
console.log('Logging a complex object: %O', myComplexObject);
```
I could reproduce this with node-inspector too. Run the program from the command line:
```
node --debug-brk bug2484.js
```
and then attach node-inspector. Stepping over the console.log will make it crash.
This does not happen with node 5.5 (but the program will not terminate either).

Closing because this issue is not VS Code related.

**Closed by weinand** 2016-01-29 09:57 UTC
Labels: debug

**Comment by mindruptive** [comment] 2016-01-29 13:47
Thanks weinand,

it happens with node 5.5, too but regardless of VSC. Could reproduce it even by starting the commandline debugger and stepping through with "next".

`var util = require("util");

var obj = { 1: "fasdadsaas", 2: "safsdafdsafsadfad" };

var message = util.format("Format the object: %O", obj);

var i = 1;`

Thanks for the hint!
mind

**Comment by weinand** [comment] 2016-01-29 13:49
@mindruptive since you have a small reproducible snippet, I suggest to file a bug against node: https://github.com/nodejs/node/issues

**Comment by mindruptive** [comment] 2016-01-29 13:53
Thanks, I will.
Best
m
