### ISSUE TITLE
Horizontal panel header colour conflicts with colour for indicating focus

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#3274] opened 2016-02-23 09:45 UTC
We should change the colour of the header from blue to the same colour as the title bars inside each viewlet.

Opened while testing #3246

**Comment by isidorn** [comment] 2016-02-23 10:16
Setting to Feb for discussion

**Comment by isidorn** [comment] 2016-02-24 13:37
Actually dupe of #2300
I set that one to feb so we can discuss it in our bug triage

**Closed by isidorn** 2016-02-24 13:37 UTC
Labels: debug
