### ISSUE TITLE
files.autoGuessEncoding doesn't always work for files opened during vscode startup

### ISSUE THREAD

**Issue by jcegh** [microsoft/vscode#225135] opened 2024-08-08 13:24 UTC
Type: <b>Bug</b>

<b>Steps to reproduce:</b>

1. Create file "Test.js" encoded in windows1252, with following content:
```js
// This file is a test file for encodings
// é
```
2. Use the following vscode settings:
```json
{
    "files.autoGuessEncoding": true,
    "files.candidateGuessEncodings": [
        "utf8", "windows1252"
    ]
}
```
3. Start vscode, then open Test.js: the encoding is correctly guessed as windows1252.
4. While the file is still opened, close vscode, then start it again: the Test.js file is automatically reopened at startup, but this time vscode incorrectly uses the wrong encoding, and the accented character displays as <?>.

<b>Remarks:</b>
* The issue also happens if while no vscode instance is running, the file is opened with the explorer's right-clic menu "Open with vscode".
* The file sometimes briefly shows up with the correct encoding before quickly switching to utf8.
* The issue can be reproduced with files whose extension is `.js`, `.lua`, `.py` for example, but when the extension is `.txt` the issue disappears.
* The issue is reproducible even with all extensions disabled.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|27.81GB (8.81GB free)|
|Process Argv|D:\\Windows1252.js --crash-reporter-id a0e9d6c8-5e06-430e-a767-f64d61c61b73|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|15.2.3
vscode-xml|red|0.27.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccplti:31103428
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by bpasero** [comment] 2024-08-08 15:59
I cannot reproduce.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jcegh** [comment] 2024-08-08 19:07
Just tried the insider build. At first I thought I couldn't reproduce. Then I realized there was no syntax highlighting. With the default install of the insider build, with the autoGuessEncoding settings added, I observe this behaviour:
* If I open Test.js in an already running instance of vscode:
  - The language is correctly guessed as Javascript.
  - The encoding is correctly guessed as windows1252.
* If Test.js is automatically opened on startup because it was opened when vscode was closed:
  - The language is incorrectly guessed as plaintext. This somehow doesn't happen for me with the non-insider build, so this might be a regression?
  - The encoding is correctly guessed as windows1252, but that's because as I mentioned in the issue, the encoding problem doesn't reproduce with plaintext files. I'm pretty sure if the insider build correctly used javascript as the language on startup, the encoding would be wrong. Also, if I manually change the language from plaintext to javascript, the encoding immediately switches from to utf8.

The insider build failure to use the correct language when the file is opened on startup also happens with a Lua file.

**Comment by bpasero** [comment] 2024-08-09 04:02
Yes, there was a bug that I think is now fixed when we release a new insiders today, please try again then.

**Comment by bpasero** [comment] 2024-08-09 06:29
I am actually now able to reproduce, and think I have a fix!

**Closed** 2024-08-09 07:32 UTC
Labels: bug, file-encoding, confirmed

**Comment by jcegh** [comment] 2024-08-12 14:04
Tried the latest insiders build. Works great, thanks a lot!
