### ISSUE TITLE
Markdown preview: Code block has two-toned background

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#53278] opened 2018-06-28 22:54 UTC
Issue Type: <b>Bug</b>

Found while verifying https://github.com/Microsoft/vscode/issues/52710

When using a code block in a markdown document, the block has a darker background around the block, and then a lighter margin, regardless of theme:
![screen shot 2018-06-28 at 3 47 26 pm](https://user-images.githubusercontent.com/3672607/42064307-9ad1ded8-7aea-11e8-8120-63c8e4ae56df.png)

Previously the background was all the same color:
![screen shot 2018-06-28 at 3 52 40 pm](https://user-images.githubusercontent.com/3672607/42064480-53dbcd58-7aeb-11e8-87e4-2bb0ca68357d.png)

VS Code version: Code - Insiders 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:11:09.274Z)
OS version: Darwin x64 17.4.0

**Comment by mjbvz** [comment] 2018-06-28 22:58
Thanks. Duplicate of #53246. Just checked in fix

**Closed by mjbvz** 2018-06-28 22:58 UTC
Labels: markdown
