### ISSUE TITLE
Problem with this font ("Operator Mono Light" doenst show italic letters on comments like before)

### ISSUE THREAD

**Issue by unlimitD** [Microsoft/vscode#28908] opened 2017-06-16 19:20 UTC
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1.After installling this version of vscode(1.13.1)  my "Operator Mono Light" font doesnt show italic letters in comments. 
vscode v1.12 //Italic
vscode v1.13 //normal

**Comment by alexandrudima** [comment] 2017-06-19 07:23
Possible duplicate of #8108

**Comment by alexandrudima** [comment] 2017-11-24 14:52
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Closed by alexandrudima** 2017-11-24 14:52 UTC
Labels: font-rendering, upstream
