### ISSUE TITLE
New asWebviewUri API breaks old existing behavior

### ISSUE THREAD

**Issue by abist** [microsoft/vscode#84543] opened 2019-11-12 01:12 UTC
Issue Type: <b>Bug</b>

Two issues -

1. The new asWebviewUri API function breaks the previous existing behavior. Context - https://github.com/microsoft/vscode-mssql/issues/1277.  If it helps, I'm using this function to set `<base href>` for the html to access some css files and images. The css also contains data URI's for `svg`'s, which don't show up any more.

2. Toggle developer tools or developer tools for webviews stopped working altogether, so it's very hard to debug this issue on my side too. Individual issue for that - https://github.com/microsoft/vscode/issues/84340

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (49.99GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|8.0.2
pascal-formatter|ale|2.2.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|10.1.1
tslint|eg2|1.0.44
innosetup|idl|1.2.0
vscode-azurefunctions|ms-|0.19.1
mssql|ms-|1.7.1
python|ms-|2019.10.41019
azure-account|ms-|0.8.4
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
vsliveshare|ms-|1.0.950
debugger-for-chrome|msj|4.12.1
vscode-scope|yiw|0.0.21

</details>
our clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment] 2019-11-12 22:33
1. Please provide a link to example code with steps to reproduce the issue

2. This sounds unrelated to this api. Please keep following up on #84340

**Comment by abist** [comment] 2019-11-12 22:43
@mjbvz We were using inline svg's in the webview and it seems that the webview doesn't support utf8 format. We fixed the issue by switching to base64 inline svg's.

**Comment by mjbvz** [comment] 2019-11-12 22:47
So this issue is fixed?

The webview supports utf8 just fine and we are using it for the built-in markdown preview. Can you explain the problem and share example code? Also inline resources should not have anything to do with `asWebviewUri`

**Comment by abist** [comment] 2019-11-12 22:49
https://github.com/microsoft/vscode-mssql/blob/master/src/controllers/webviewController.ts#L101

I added this line with the new WebviewUri function. I assumed this would work by itself, but only when we switched to base64 svg's did they start showing up.

**Comment by mjbvz** [comment] 2019-11-12 22:55
That doesn't sound right but since everything is working now I'm closing this 

If you have an minimal example of it not working, please share so we can investigate

**Closed by mjbvz** 2019-11-12 22:55 UTC
Labels: needs more info, webview
