### ISSUE TITLE
VSCode 1.8.0 on CentOS 7.2 can't install or browse extension

### ISSUE THREAD

**Issue by liaoya** [Microsoft/vscode#17524] opened 2016-12-19 09:59 UTC
- VSCode Version: 1.8.0-1481651903
- OS Version: CentOS 7.2.1511

Steps to Reproduce:

1. Update to 1.8 from 1.7.2
2. Can't search or browse extension, but I downgrade to 1.7.2, these extension functions work again.

**Comment by Tyriar** [comment] 2016-12-19 23:31
Are there any errors in the console? (Help > Toggle Developer Tools)

**Comment by liaoya** [comment] 2016-12-20 02:32
Today I update to 1.8.1 and the same issue.

I find the following error in the console:
Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_CONNECTION_TIMED_OUT
An unknown error occurred. Please consult the log for more details.

My desktop is behind the firewall and I set http.proxy in settings.json. The VSCode on Windows with the same proxy configuration can search and browse the extension. The Linux can't.

**Comment by dfroze** [comment] 2016-12-29 12:59
I am guessing I have something similar to this. Just got a new computer, installed vscode 1.8.1, added proxy (tried without as well), no extensions available. 
In console I get:

> Failed to load resource: net::ERR_CONNECTION_REFUSED
An unknown error occurred. Please consult the log for more details

Where can i find this log to check the details?

**Comment by joaomoreno** [comment] 2017-01-03 14:40
Duplicate of #17574

**Closed by joaomoreno** 2017-01-03 14:40 UTC
Labels: extensions, linux, needs more info, proxy
