### ISSUE TITLE
TreeView.reveal after TreeDataProvider.refresh

### ISSUE THREAD

**Issue by angelozerr** [microsoft/vscode#114149] opened 2021-01-11 12:48 UTC
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows_NT x64 10.0.17763

I recreate the existing issue https://github.com/microsoft/vscode/issues/96089 since I have the same problem with the treeview API (refresh the treeview and try to reveal an item after the refresh). The only solution which is working is to call the treeview#reveal inside a setTimeout which is not a robust solution.

@alexr00 suggested in https://github.com/microsoft/vscode/issues/96089#issuecomment-619832600 to try to detect end refresh and call treeview#reveal in the getChildren but without success. 

@alexr00 could you give me a sample code to detect this end refresh please.

IMHO I think treeview should give the capability to detect the end refresh with an event.

**Comment by alexr00** [comment] 2021-11-10 15:35
duplicate of https://github.com/microsoft/vscode/issues/96089

**Closed by alexr00** 2021-11-10 15:35 UTC
