### ISSUE TITLE
Find & Replace dialog displaces content in editor

### ISSUE THREAD

**Issue by vrrajkum** [Microsoft/vscode#56228] opened 2018-08-12 18:34 UTC
Issue Type: <b>Bug</b>

1. Open the find & replace dialog (Ctrl + F) with a scrollable file open and scrolled to the top.

2. Scroll down so that the beginning of the file is no longer visible.

3. Scroll back up and the beginning of the file will be displaced by the find & replace dialog.  https://i.imgur.com/YalR6qQ.gifv

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 2591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.9.1
beautify|Hoo|1.3.2
live-sass|rit|3.0.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.25.0
vscode-react-native|vsm|0.6.13

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2018-09-04 23:33
Duplicate of https://github.com/Microsoft/vscode/issues/28390, let's track it there.

**Closed** 2018-09-04 23:33 UTC
Labels: *duplicate, editor, editor-find
