### ISSUE TITLE
Documentation hover disappears too easily

### ISSUE THREAD

**Issue by JackKenney** [microsoft/vscode#113255] opened 2020-12-22 00:03 UTC
When highlighting methods and reading the documentation if it's multiple lines it's very hard to be precise enough with scrolling to see the last line. As soon as it hits the bottom, the page scrolls and the box disappears.

**Comment by alexdima** [comment] 2020-12-22 09:56
Duplicate of #112373

**Closed by alexdima** 2020-12-22 09:56 UTC
