### ISSUE TITLE
Allow an extension to revert and close an editor even if dirty

### ISSUE THREAD

**Issue by Moniarchy** [microsoft/vscode#77438] opened 2019-07-16 01:37 UTC
VSCode Version: 1.36.1
VSCode Insiders Version: 1.37.0-insider
OS Version: Windows 10

We are implementing untitled files support for Live Share (previously untitled files could not be followed into or co-edited), and we have a scenario in which we cannot figure out what is happening.

**Before reproing the scenario, you will need to start and join a Live Share session. Here are the steps for setting up a session:**
- Install Live Share in both of the VS Code editors that you will be using with the VSIX located here: \\scratch2\scratch\mowillia
- Once Live Share is installed, click the "Live Share" status bar item. It will open a browser window and prompt you to sign in with either a Microsoft or GitHub account.
- Sign in. In the browser window, you will see a message that says "Ready to collaborate!"
- Return to VS Code, where you should see an information message that says "Invitation link copied to clipboard! Send it to anyone you trust or click "More info" to learn about secure sharing."
- In the command palette in the second VS Code window, type "Live Share: Join Collaboration Session", and press enter. The invitation link should automatically appear in the box. Press enter again to join the session.
- On a successful join, both the host and the guest will receive another information message saying that the guest has joined the session.
 
**The scenario is the following (gif attached)**:
-	Host: open untitled file, type something
-	Guest: opens the file as well, sees content as we type
-	Host: closes untitled file (and sends a message to the guest to notify). 
-	Guest: At this point, guest fires a deleted event to the file system provider. We also perform clean-up on the co-editing resources for that URI. The editor now shows a (deleted) mark next to the file name, as expected.
-	Host: Open a new untitled file (it will have the same name as the previous one – Untitled-1), and type something (also, we send a message to the guest to notify of the change)
-	Guest: Fires a created event to the file system provider, with the same URI that we used previously for the deleted file
Expected: Guest IDE will call the file system provider stat and readFile, and refresh the contents of the editor.
Actual: Guest IDE does not invoke the file system provider.
 
We need some guidance or help with debugging this issue. We spent about 2 days trying different approaches to make the file system provider call us back but we were not successful. This might be a side effect of the way we interact with the editor in LiveShare and also of the fact that URIs and editors are reused on the guest for untitled files.
A good starting point would be if you could point us to a good spot in the VSCode code base where the IDE handles the file system provider events and decides to call stat() and readFile().

We have already tried simulating this behavior with the MemFS sample, which works as expected. When we try to extrapolate to Live Share, we are broken again. The big question for us is what are we doing wrong in LiveShare such that we break that scenario. We tried several things, like making sure the correct metadata is set on the files and making sure the same order of calls to the fs provider is respected in the sample vs our code. Nothing seemed to make a difference.
 
Any other help or ideas are appreciated.

![UntitledFiles](https://user-images.githubusercontent.com/18104615/61259021-29e8cb80-a72d-11e9-87d7-fd3dc3b5717f.gif)

**Comment by Moniarchy** [comment] 2019-07-16 01:38
cc @alexandrudima as per the email thread.

**Comment by alexandrudima** [comment] 2019-07-17 13:52
I can reproduce the same behaviour with MemFS. 

So I think this is just how the workbench works:
**If you have an unsaved file, and the file is deleted on disk, the file is kept in the editor and annotated with `(deleted)`. If the file is then added on disk, the unsaved file is still kept in the editor. Data loss is prevented...**

- Clone and open https://github.com/microsoft/vscode-extension-samples/tree/master/fsprovider-sample
- MemFS: Setup Workspace (reload window)
- MemFS: Create Files
- Open `file.txt` and make changes
- MemFS: Delete “file.txt”
- MemFS: Add “file.txt”

After the last step the "dirty" content is shown in the editor:

![Kapture 2019-07-17 at 15 39 47](https://user-images.githubusercontent.com/5047891/61380341-7822d980-a8a9-11e9-857b-e16ea432b0f7.gif)

By adding a bit of logging, here is what I see in the LiveShare case:
```
readFile vsls:/~untitled/Untitled-1
stat vsls:/~untitled/Untitled-1
vsls:/~untitled/Untitled-1 - ADDED
vsls:/~untitled/Untitled-1 - UPDATED
stat vsls:/~untitled/Untitled-1
stat vsls:/
readdir vsls:/
stat vsls:/.vscode
readFile vsls:/~untitled/Untitled-1
stat vsls:/~untitled/Untitled-1
stat vsls:/~untitled/Untitled-1
writeFile vsls:/~untitled/Untitled-1
stat vsls:/~untitled/Untitled-1
vsls:/~untitled/Untitled-1 - DELETED
stat vsls:/~untitled/Untitled-1
vsls:/~untitled/Untitled-1 - ADDED
vsls:/~untitled/Untitled-1 - UPDATED
```

and here is what I see in the MemFS case:
```
readFile memfs:/file.txt
stat memfs:/file.txt
memfs:/ - UPDATED
memfs:/file.txt - DELETED
stat memfs:/file.txt
stat memfs:/
readdir memfs:/
memfs:/file.txt - ADDED
memfs:/file.txt - UPDATED
stat memfs:/
readdir memfs:/
```

The relevant log statements are after the `ADDED` event and the log statements match. The MemFS one shows a stat for the root but that is because the FS is shown in the explorer and I think the explorer triggers that.

Here is the diff I applied to get those log statements:
[patch.diff.txt](https://github.com/microsoft/vscode/files/3402162/patch.diff.txt)

**Comment by kieferrm** [comment] 2019-07-17 14:16
I don’t see this behavior when running the exact same steps on my macOS. We might see platform specific behavior here or a raise condition.

**Comment by jrieken** [comment] 2019-07-22 08:10
@kieferrm Any chance that you use the `workbench.editor.closeOnFileDelete` setting? Afaik this is a feature: when a file is deleted on disk we keep editors open to allow you to save them elsewhere. For untitled files this might not be the right thing to do tho

**Comment by jrieken** [comment] 2019-07-22 08:13
To work around the editor-being-reused issue it should be enough to use a random name for the untitled file, like `untitled-fe3`, `untitled-9a5` etc... However, I believe editors still won't close (data prevention)

**Comment by bpasero** [comment] 2019-08-10 11:28
I think https://github.com/microsoft/vscode/issues/50969 is quite related. It is true that we typically never close a document that is dirty, even if the document got deleted.

As a workaround, we have a command `workbench.action.revertAndCloseActiveEditor` that will cause any dirty active editor to close without prompting any dialog to the user. 

If that is not sufficient, I can think of having a new API command for extensions to close a document with a provided URI in that manner. Let me know.

**Comment by bpasero** [comment] 2019-08-26 06:59
Closing as per https://github.com/microsoft/vscode/issues/77438#issuecomment-520141564

**Closed by bpasero** 2019-08-26 06:59 UTC
Labels: api, feature-request
