### ISSUE TITLE
[Web] - No run on markdown still autodetects markdown

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129740] opened 2021-07-29 01:47 UTC
Testing #129436

Tested doesn't run on markdown, continues to detect markdown.

**Comment by TylerLeonhardt** [comment] 2021-07-29 16:52
This is a duplicate of #129739 only because my suspicion is that the expected behavior of the setting was confusing.

**Closed by TylerLeonhardt** 2021-07-29 16:52 UTC
