### ISSUE TITLE
vscode question （there hava a picture）

### ISSUE THREAD

**Issue by Paparazzijie** [Microsoft/vscode#33142] opened 2017-08-25 10:23 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.
![image](https://user-images.githubusercontent.com/24708291/29710337-628f548e-89c2-11e7-90b2-bca0d25d9f47.png)

**Comment by Tyriar** [comment] 2017-08-25 22:19
Duplicate of https://github.com/Microsoft/vscode/issues/32739

**Closed by Tyriar** 2017-08-25 22:20 UTC
Labels: new release
