### ISSUE TITLE
QuickInputButton svg icon is not working

### ISSUE THREAD

**Issue by lanten** [microsoft/vscode#87717] opened 2019-12-26 10:49 UTC
- VSCode Version: 1.41.1
- OS Version: macOS 10.15.1 (19B88)

This is my problem when developing the extension

code: 
```ts
const inputBox = vscode.window.createInputBox()
inputBox.buttons = [
  {
    iconPath: Uri.file(global.ctx.asAbsolutePath('assets/icons/folder.dark.svg')),
    tooltip: 'tooltip',
  },
]
```

When I use png, it works, this may be a bug

- code ref: https://github.com/lanten/create-item-by-template/blob/2.0/src/core/before-create.ts#L72
- svg file: https://github.com/lanten/create-item-by-template/blob/2.0/assets/icons/folder.dark.svg

**Comment by lanten** [comment] 2019-12-26 16:14
I think I found the reason

I tried using developer tools add style to the  `a.action-label.codicon.quick-input-button-icon-1` element ：`background-size: 100%;`, the svg icon is worked.

![image](https://user-images.githubusercontent.com/16203518/71482391-468d4180-283d-11ea-8842-47b9854924ea.png)

But I can't find where the source code is
Hope to resolve this soon

**Comment by misolori** [comment] 2020-01-02 19:45
@latel using our [quick input sample (`multiStepInput`)](https://github.com/Microsoft/vscode-extension-samples/tree/master/quickinput-sample), I am unable to reproduce this issue:

![image](https://user-images.githubusercontent.com/35271042/71688742-4f0ddc80-2d55-11ea-989a-50fb8ae1082f.png)


Can you please provide a sample repo with this issue that we can inspect?

**Comment by lanten** [comment] 2020-01-03 03:00
I created examples in this [repo](https://github.com/lanten/input-buttons-repo) now

**Comment by misolori** [comment] 2020-01-03 05:28
The problem here is that your SVG icons are not sized correctly, [please see our API docs](https://code.visualstudio.com/api/references/contribution-points#Command-icon-specifications):

> Icons should be 16x16 with a 1 pixel padding (image is 14x14) and centered.
> <img src="https://code.visualstudio.com/assets/api/references/contribution-points/command-icons.png">

[Your icon is 200x200](https://raw.githubusercontent.com/lanten/input-buttons-repo/master/src/icons/back.dark.svg):

```svg
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg t="1577409030146" class="icon" viewBox="0 0 1024 1024" version="1.1" 
  xmlns="http://www.w3.org/2000/svg" p-id="3049" 
  xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200" fill="#c5c5c5">
  <defs>
    <style type="text/css"></style>
  </defs>
  <path d="M708.64 284.15H278.41l96-96a32 32 0 0 0-45.25-45.25L178.7 293.35a37.19 37.19 0 0 0 0 52.6l150.48 150.48a32 32 0 1 0 45.25-45.25l-103-103h437.21c49.58 0 96.38 19.49 131.77 54.88s54.88 82.19 54.88 131.77-19.49 96.38-54.88 131.77-82.19 54.88-131.77 54.88H351.29a32 32 0 0 0-32 32 32 32 0 0 0 32 32h357.35c137.86 0 250.66-112.79 250.66-250.66-0.01-137.87-112.8-250.67-250.66-250.67z" p-id="3050"></path>
</svg>
```

When I resize your icons the icons appear normally:

![image](https://user-images.githubusercontent.com/35271042/71708496-b30cc100-2da6-11ea-9875-632c0fb0f5e6.png)

Please re-size your icons accordingly, will close this as `as-designed`

**Closed by misolori** 2020-01-03 05:28 UTC
Labels: needs more info
