### ISSUE TITLE
code --install-extension fails when ~/.config/Code/User/ does not exist

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/vscode#7510] opened 2016-06-10 01:33 UTC
- VSCode Version: 1.2
- OS Version: Debian Jessie

Steps to Reproduce:
A fresh install doesn't have this directory. Or just remove it to test.
```
rm -rf ~/.config/Code/User
```
2. Try installing any extension.
```
code --install-extension ms-vscode.csharp
Error: watch /home/vscode/.config/Code/User ENOENT
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1323:19)
    at Object.fs.watch (fs.js:1351:11)
    at new e (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:1245)
    at m (/usr/share/code/resources/app/out/vs/code/node/cli.js:4:11378)
    at t._createInstance (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:7605)
    at t._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:8580)
    at t._getOrCreateServiceInstance (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:7766)
    at /usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:7122
    at Array.map (native)
```

Found while working on https://github.com/ctaggart/rusty-vscode/issues/16.

**Comment by joaomoreno** [comment] 2016-06-13 09:25
Duplicate of #7505

**Closed by joaomoreno** 2016-06-13 09:25 UTC
