### ISSUE TITLE
The typographical errors of the terminal text go after leaved and cutting back

### ISSUE THREAD

**Issue by tfhnia** [Microsoft/vscode#22435] opened 2017-03-11 03:21 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|sublime-keybindings|ms-vscode|2.0.1|;

---

Steps to Reproduce:

1. Switch to the terminal.
2. Type a line command, this command needs to be executed for a long time, and to be able to output multiple lines of text.
3. leave the terminal, switch to other applications. 
4. And then return to the terminal, you will find the terminal text layout error.
>Note that this terminal is win10 under powershell

**Comment by ramya-rao-a** [comment] 2017-03-11 07:31
Can you provide screenshots?

**Comment by Tyriar** [comment] 2017-03-17 02:55
Closing as a duplicate of https://github.com/Microsoft/vscode/issues/19665, @tfhnia let me know if that doesn't match your issue.

**Closed by Tyriar** 2017-03-17 02:55 UTC
Labels: integrated-terminal, needs more info
