### ISSUE TITLE
Minimal width for editor tabs

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#30680] opened 2017-07-14 07:54 UTC
I want to be able to customize the minimum width for editor tabs, to improving the number of tabbed pages on small monitor.

Options ideas:
1. Favicon only (perhaps cool only, may by keyboard to navigate; Best if can be achieve with extensions).
2. Customize min width, overflow only when will be less than this width.
3. Customize min number of characters on tabs, like 3 characters on head and other characters be hidden while overflow. `...` and duplicate name path hints need to be considered. Use hover to see the tooltips.
4. Based on the above, allow hover to expand a tab.
5. Refer to many extensions for tabbed browsers.

Related issue: #29953, #28431.

**Comment by boydy12** [comment] 2017-08-16 10:16
+1

**Comment by zhichl** [comment] 2017-10-05 00:27
+1

**Comment by VampiRUS** [comment] 2017-10-13 12:08
+1

**Comment by mattapperson** [comment] 2017-10-17 13:53
+1

**Comment by lhrolim** [comment] 2017-11-14 11:41
+1

**Comment by bpasero** [comment] 2017-11-17 07:48
/duplicate of https://github.com/Microsoft/vscode/issues/17775

**Closed** 2017-11-17 07:48 UTC
Labels: *duplicate, feature-request, workbench-tabs
