### ISSUE TITLE
`Ctrl+Shift+E` cannot hide the resource manage panel

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#48878] opened 2018-04-28 07:03 UTC
Issue Type: <b>Bug</b>

In windows system, we use `Ctrl+Shift+E` to open the hiden resource manage panel, but we cannot hide the panel by `Ctrl+Shift+E`, other panels have the same problem.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

**Comment by yume-chan** [comment] 2018-04-28 08:49
duplicate of #19400

You can add two keybindings to achieve your demand:

````json
    {
        "command": "workbench.view.explorer",
        "key": "ctrl+shift+e",
        "when": "!explorerViewletFocus"
    },
    {
        "command": "workbench.action.toggleSidebarVisibility",
        "key": "ctrl+shift+e",
        "when": "explorerViewletFocus"
    }
````

also for the search viewlet: `"when": "searchViewletVisible"`

sadly there is no `when` clause for the other two views.

**Comment by yume-chan** [comment] 2018-04-28 08:56
sorry I forgot about the `activeViewlet` `when` clause.

relates: #17722

```` json
    {
        "command": "workbench.view.explorer",
        "key": "ctrl+shift+e",
        "when": "activeViewlet != 'workbench.view.explorer'"
    },
    {
        "command": "workbench.action.toggleSidebarVisibility",
        "key": "ctrl+shift+e",
        "when": "activeViewlet == 'workbench.view.explorer'"
    },
    {
        "command": "workbench.view.scm",
        "key": "ctrl+shift+g",
        "when": "activeViewlet != 'workbench.view.scm'"
    },
    {
        "command": "workbench.action.toggleSidebarVisibility",
        "key": "ctrl+shift+g",
        "when": "activeViewlet == 'workbench.view.scm'"
    },
````

**Comment by liwangqian** [comment] 2018-04-29 03:47
thanks！

**Closed** 2018-04-29 03:48 UTC
