### ISSUE TITLE
Pressing . selects the first option in the context menu even before it's opened

### ISSUE THREAD

**Issue by Swazimodo** [Microsoft/vscode#66868] opened 2019-01-21 21:56 UTC
Issue Type: <b>Bug</b>

In my react app typing 'this.' will automattically type 'this.UNSAFE_componentWillMount.'. You then have to delete everything after 'this'. After this happens you can press period and you then get the context menu like it should have done initially.

![autocomplete for the loss](https://user-images.githubusercontent.com/10536879/51500889-ff751180-1d8c-11e9-94b3-2c892c05d508.gif)

However, this only appears to happen if you type fast. I slowed down a little while doing some further testing and it did not happen.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (14.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summ

**Comment by jrieken** [comment] 2019-01-22 15:59
This is because of the `"editor.acceptSuggestionOnCommitCharacter"`-setting. This is what happens

* typing `this` starts suggesting and the best match is UNSAFE_componentWillMount
* pressing `.`, with having the aforementioned setting, accepts that suggestion *and* insert the dot. 

<img width="489" alt="screenshot 2019-01-22 at 07 56 34" src="https://user-images.githubusercontent.com/1794099/51547478-3eea3f00-1e1b-11e9-93bd-30070cde49cc.png">

Turning the setting to `false` will get you out of this.

**Comment by jrieken** [comment] 2019-01-22 19:59
Looks like you have the `this` suggestion atop then. Not sure why...

<img width="521" alt="screenshot 2019-01-22 at 11 58 57" src="https://user-images.githubusercontent.com/1794099/51561833-1c691d80-1e3d-11e9-82ed-f2e2e7dab431.png">

**Comment by jrieken** [comment] 2019-01-22 22:20
Adding @mjbvz, it seems that the `this` suggestion disappears while typing...

**Comment by alexch** [comment] 2019-02-01 01:47
In JavaScript, when I type <kbd>c</kbd><kbd>y</kbd><kbd>.</kbd><kbd>g</kbd><kbd>e</kbd><kbd>t</kbd><kbd>(</kbd> and then look at the screen I should see `cy.get(`. Instead I (sometimes!) see `crypto.getRandomValues(` instead.

This is an #a11y issue; the suggestion menu should not select or fill anything until/unless I press <kbd>↓</kbd> while it's up. Any setting that *takes control away from the user* and types extra characters that they did not intend is a bad default setting, and the fact that this behavior is timing-dependent is even more maddening.

Also, the `editor.acceptSuggestionOnCommitCharacter` sounds like it's intended to type the **selected** suggestion and a dot when I press <kbd>↓</kbd><kbd>.</kbd>, which is actually desirable behavior; the advice to disable `editor.acceptSuggestionOnCommitCharacter` is more of a workaround than a solution since it disables .-to-accept in all cases, not just this overly-aggressive autocomplete scenario.

Shall I file a new issue for this setting being flipped by default?

**Comment by mjbvz** [comment] 2019-02-21 01:40
@Swazimodo Do you still see this problem in the latest vscode insiders builds when you fully type out `this.`?

I've opened https://github.com/Microsoft/TypeScript/issues/30012 to track why `this` is not suggested first when you type out `thi` or `th`, but I can't reproduce the original error in a new `create-react-app` project

**Comment by mjbvz** [comment] 2019-03-07 00:56
I'm closing this issue as I can't repo the issue when fully typing out `this.`. Microsoft/TypeScript#30012  tracks the root cause of `this` completions not being properly sorted before you fully type out `this`.

**Closed by mjbvz** 2019-03-07 00:56 UTC
Labels: bug, needs more info, suggest
