### ISSUE TITLE
The Explorer font is too small to set size

### ISSUE THREAD

**Issue by jsonvot** [Microsoft/vscode#29702] opened 2017-06-28 04:54 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|project-manager|alefragnani|0.18.1|
|vscode-refresh-html|bajdzis|0.0.2|
|vscode-html-css|ecmel|0.1.7|
|vscode-great-icons|emmanuelbeziat|2.1.8|
|php-debug|felixfbecker|1.10.1|
|auto-rename-tag|formulahendry|0.0.14|
|beautify|HookyQR|1.1.1|
|crane|HvyIndustries|0.3.6|
|output-colorizer|IBM|0.1.1|
|easy-icons|jamesmaj|0.3.1|
|autofilename|JerryHong|0.1.3|
|format-indent|Kasik96|1.3.0|
|string-manipulation|marclipovsky|0.1.0|
|PowerShell|ms-vscode|1.4.1|
|vuehelper|oysun|0.1.0|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.10.1|
|indenticator|SirTori|0.4.2|
|guides|spywhere|0.8.3|
|JavaScriptSnippets|xabikos|1.4.1|
|Material-theme|zhuangtongfa|2.8.9|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1.The Explorer font is too small to set size.
2.Want to set the Explorer font size freely.

**Comment by oyeanuj** [comment] 2017-10-19 03:27
I wasn't sure if this also includes nav dropdowns, so I thought I'd add this screenshot here. Let me know if this comment should be a separate bug.

An ability to increase the font size, and line height would help in the readability and scannability of the dropdown.

<img width="600" alt="screen shot 2017-10-18 at 6 48 29 pm" src="https://user-images.githubusercontent.com/9633371/31752974-b62a93a6-b442-11e7-9f6a-567f031171ba.png">

Thank you!

**Comment by smlombardi** [comment] 2017-10-31 18:08
I've seen posts mentioning using "zoom" for this but, personally, I'd rather just set a font size.

**Comment by isidorn** [comment] 2017-11-17 14:10
Duplicate of https://github.com/Microsoft/vscode/issues/519

**Closed** 2017-11-17 14:10 UTC
Labels: *duplicate, feature-request, file-explorer
