### ISSUE TITLE
Orphaned quote crashes Sass

### ISSUE THREAD

**Issue by spritestack** [Microsoft/vscode#17166] opened 2016-12-14 11:15 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open a new document
2. Set language mode to Sass
3. Type a quote mark " or '  and delete the closing quote if it's auto added.
Any line of text with an orphaned quote mark will do.
4. Move cursor to column 1 (start of the line) and press TAB.

Desired behaviour:
Pressing TAB should indent the text regardless of valid code etc.

The problem:
VSCode seems to freeze.

**Comment by kieferrm** [comment] 2016-12-14 19:21
The problem is caused by emmet.

**Comment by ramya-rao-a** [comment] 2016-12-14 19:30
https://github.com/emmetio/emmet/issues/396

**Comment by ramya-rao-a** [comment] 2016-12-14 19:51
Happens if you press TAB anywhere inside the block

**Comment by ramya-rao-a** [comment] 2017-02-01 01:39
Closing as duplicate of #8135

**Closed by ramya-rao-a** 2017-02-01 01:39 UTC
Labels: bug, emmet, freeze-slow-crash, upstream
