### ISSUE TITLE
Display duplicate content after terminal resizing

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#222015] opened 2024-07-18 03:57 UTC
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.18363

https://github.com/user-attachments/assets/64f2795a-a351-4ef0-9aae-90ceaf249b96

1. resize
2. mouse scroll

**Comment by meganrogge** [comment] 2024-07-18 18:45
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by tisilent** [comment] 2024-07-19 00:29
Version: 1.92.0-insider (user setup)
Commit: 65a6a2f783dbc87fb3b1408c6a9b3e8d455a60a2
Date: 2024-07-18T05:04:30.247Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.18363

Resize until the scrollbar appears.
![1！1](https://github.com/user-attachments/assets/f5db0b1c-0c85-440c-9848-6b30631e59d0)

**Comment by meganrogge** [comment] 2024-07-19 15:32
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed** 2024-07-27 11:24 UTC
Labels: info-needed, upstream, windows, terminal-conpty

**Comment by Dhairya-007** [comment] 2024-07-30 07:14
Hello There , I have been facing same issue , its not reproduced in windows terminal but occurring in vscode terminal

i am only writing one time but when i am resizing the terminal size it then duplicate like this
![Screenshot 2024-07-30 123916](https://github.com/user-attachments/assets/3730d3f1-ef30-4884-9ff6-a03cd337e89c)

 please look into this

**Comment by lahan212** [comment] 2024-08-11 14:38
same issue, for terminal vscode (powershell, git bash, cmd) always duplicate after resizing

**Comment by wsVIC** [comment] 2024-08-20 17:18
same. while windows terminal is ok
