### ISSUE TITLE
"All Exceptions" doesn't de-activate after unchecking it

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#25095] opened 2017-04-20 20:11 UTC
- VSCode Version: 1.12.0-Insiders
- OS Version: Windows

Steps to Reproduce:

1. Launch Extension: I used our cpptools extension.
2. Select the All Exceptions breakpoints option and have some exception trigger.
3. Uncheck the All Exceptions option.

Bug: It keep breaking on All Exceptions until I stop debugging.

**Comment by mjbvz** [comment] 2017-04-20 22:33
This issue was moved to Microsoft/vscode-cpptools#652

**Comment by sean-mcmanus** [comment] 2017-04-20 22:34
@mjbvz No, this is a bug with VS Code's javascript debugging. This repros without the cpptools extension installed. I'm using VS Code to debug the cpptools extension.

**Comment by mjbvz** [comment] 2017-04-20 22:42
Ok, so you are debugging your cpp extension with the extension debugger? Not debugging code with the cpp extension?

**Comment by sean-mcmanus** [comment] 2017-04-20 22:43
Yes, I do Launch Extension with our cpptools extension workspace for typescript debugging.

**Comment by weinand** [comment] 2017-04-20 23:14
duplicate of https://github.com/Microsoft/vscode-node-debug/issues/135

**Closed by weinand** 2017-04-20 23:14 UTC
Labels: debug
