### ISSUE TITLE
[Feature request] Toolbar functionality (custom or extend exist)

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#36526] opened 2017-10-19 06:03 UTC
It will be great to have possibility to create custom toolbar similar way like in atom - https://atom.io/packages/tool-bar

Or (imo better solution) possibility to extend current toolbar with user defined action / icons

![](https://i.imgur.com/EWMgqQ8.png)

**Comment by mjbvz** [comment] 2017-10-19 17:08
Duplicate of #33609

**Closed by mjbvz** 2017-10-19 17:08 UTC
Labels: duplicate
