### ISSUE TITLE
VS Code always get the first keyboard layout for shortcuts and screencast

### ISSUE THREAD

**Issue by alexhausen** [microsoft/vscode#114592] opened 2021-01-19 20:21 UTC
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Ubuntu 20.04.1 LTS (Linux x64 5.8.0-38-generic)
Gnome: 3.36.8, X11

Also tested on version 1.53.0-insider with the same result.

**Steps to Reproduce:**
1. Have 2 keyboard layouts configured on Linux, the **first** should be non-US,_eg_ Portuguese (Brazil), the **second** one should be English (US).
2. Select the second keyboard layout "en"
2. Open VSCode and execute both `Developer: Toggle Screencast Mode` and `Developer: Toggle Keyboard Shortcuts Troubleshooting`
3. Open a new file and type the key `Ctrl+\` on your keyboard

**Expected result:**
Screencast bar displays `Ctrl+\` and command `Go to bracket` is executed.

**Actual result:**
Screencast bar displays `Ctrl+]` and command `Indent Line` is executed, rendering the tab character (or spaces).

Keyboard Shortcuts Troubleshooting output when pressing `Ctrl+\`:
```
[2021-01-19 16:53:37.225] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2021-01-19 16:53:37.225] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-01-19 16:53:37.225] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched.
[2021-01-19 16:53:37.405] [renderer1] [info] [KeybindingService]: | Resolving ctrl+[Backslash]
[2021-01-19 16:53:37.406] [renderer1] [info] [KeybindingService]: \ From 1 keybinding entries, matched editor.action.indentLines, when: editorTextFocus && !editorReadonly, source: built-in.
[2021-01-19 16:53:37.407] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Backslash, keyCode: 220, key: \
[2021-01-19 16:53:37.407] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Backslash, keyCode: 88 ('\')
[2021-01-19 16:53:37.407] [renderer1] [info] [KeybindingService]: | Resolving ctrl+[Backslash]
[2021-01-19 16:53:37.408] [renderer1] [info] [KeybindingService]: \ From 1 keybinding entries, matched editor.action.indentLines, when: editorTextFocus && !editorReadonly, source: built-in.
```

- **Note**: it may be easier to reproduce: pressing `;` key renders `;` character correctly but displays character `ç` in screencast bar.
- 
Keyboard Shortcuts Troubleshooting output when pressing `;`:
```
[2021-01-19 16:42:08.779] [renderer1] [info] [KeybindingService]: | Resolving [Semicolon]
[2021-01-19 16:42:08.779] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2021-01-19 16:42:08.780] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Semicolon, keyCode: 186, key: ;
[2021-01-19 16:42:08.780] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Semicolon, keyCode: 80 (';')
[2021-01-19 16:42:08.781] [renderer1] [info] [KeybindingService]: | Resolving [Semicolon]
[2021-01-19 16:42:08.781] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
```
- **Workaround**: changing layout order on Gnome (first "en" then "pt") fixes the shortcut behavior.

![vscode-1611087520082](https://user-images.githubusercontent.com/11004802/105088428-a1ae5980-5a7a-11eb-851e-dcb63eb6340e.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment] 2021-01-20 12:43
Duplicate of #24166

**Closed by alexdima** 2021-01-20 12:43 UTC
