### ISSUE TITLE
I removed the "Show features and extensions using this account" option and have added timestamps showing when an extension last accessed the account in "Manage Trusted Extensions".

### ISSUE THREAD

**Issue by AniketDon** [microsoft/vscode#103718] opened 2020-07-31 18:27 UTC
I removed the "Show features and extensions using this account" option and have added timestamps showing when an extension last accessed the account in "Manage Trusted Extensions".

Preferences sync is not listed there, it's only extensions. We can show which account is being used by preferences sync by exploring a richer accounts UI: https://github.com/microsoft/vscode/issues/97168

_Originally posted by @RMacfarlane in https://github.com/microsoft/vscode/issues/96367#issuecomment-628281488_

**Comment by RMacfarlane** [comment] 2020-08-03 03:21
@AniketDon I'm going to go ahead and close this as a duplicate of https://github.com/microsoft/vscode/issues/97168. If this is a different feature request, please include more details. Thanks!

**Closed by RMacfarlane** 2020-08-03 03:21 UTC
