### ISSUE TITLE
Folding: Unable to fold empty function

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/vscode#3251] opened 2016-02-22 12:55 UTC
I'm on commit 9f6d389 (master) to check out the folding stuff and I really like it! :)

I noticed it isn't possible to fold empty regions like the interface below and the empty function. The fold arrow doesn't appear. Is this by design? There isn't that much to fold, only some newlines so it isn't a big issue though.

ps. I'm using TypeScript

```
interface test {

}

function name(params:type) {
    
}
```

**edit** If it is by design, feel free to close

**Comment by tht13** [comment] 2016-02-22 15:16
Currently folding is done by indentation as that is generally the best language agnostic method to group code sections. 

It would be nice to have an option to provide identifiers (i.e `{` and `}` ) for what should be folder.
A contribution attribute already exists here `contributes.languages.configuration` which points to a languages configuration file. This could contain folding instructions

**Comment by aeschli** [comment] 2016-02-24 14:39
duplicate of #3349

**Closed by aeschli** 2016-02-24 14:39 UTC
Labels: feature-request
