### ISSUE TITLE
Uppercase short cut is not working in ubuntu 18.04

### ISSUE THREAD

**Issue by sachinshah114** [microsoft/vscode#70450] opened 2019-03-14 06:43 UTC
I have add short-cut key in vscode. I'm using 1.32.2 version. I have checked this in windows os and it is working well but same setting is not working in ubuntu 18.04. Is os related issue ? 

Need : When I select any text and I press Ctrl + shift + U text should convert into uppercase. 

![Screenshot from 2019-03-14 12-10-35](https://user-images.githubusercontent.com/30370879/54336582-7672ac00-4652-11e9-9465-94b42db9f7d6.png)

**Comment by roblourens** [comment] 2019-03-14 17:10
Please see this wiki page for tips to provide as many details as possible: https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

**Comment by sachinshah114** [comment] 2019-03-18 07:12
I didn't get enough help from above link. 
When I select any text and execute keyboard shortcut instead of make string in uppercase it removes my strign and type 'u'.

**Comment by sachinshah114** [comment] 2019-03-18 07:13
If this is not a bug then can you please tell me the steps to perform this operation. So based on that I can cross check my settings too.

**Comment by varshard** [comment] 2019-03-24 02:14
@sachinshah114 Look like the default uppercase short cuts aren't saved by default, despite being shown as default short cuts.

I had to reassign the same key combination myself to make it work.

**Comment by varshard** [comment] 2019-03-24 02:24
@roblourens @alexandrudima Let's me provide additional information. On Ubuntu some keybinidng that involve multipel ctrl combination (ie: close all tabs: ctrl+k ctrl+w) aren't working by default despite being shown on `Keyboard Shortcuts` page that they are already assigned to the specific command.

I had to re-assign key binding to the specific key myself to make it work.

Steps to repeat.
1. Install VS Code on Ubuntu.
1. Go to "Keyboard Shortcuts" and search for "File: Open Folder" command. Keybinding for the command should show `ctrl + k ctrl+o` as its keybinding.
1. Press `ctrl + k ctrl + o` to open folder browser dialog. *Nothing happen*.

Workaround
1. Assign keybindings that aren't working by default yourself with the same key as shown by default.

**Comment by varshard** [comment] 2019-04-27 08:30
@roblourens @alexandrudima  If I want to try to look into the source of this issue myself. How or where should I start looking into?

**Comment by alexandrudima** [comment] 2019-05-09 10:31
@sachinshah114 @varshard 
What does VS Code detect when you press the desired key combination? 
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Closed** 2019-05-27 10:15 UTC
Labels: linux, needs more info

**Comment by varshard** [comment] 2019-06-01 07:38
@alexandrudima It detected keys as I typed. The problem is that they aren't set up by default as they should. ie: `workbench.action.closeAllEditors`: Ctrl + K Ctrl + W isn't working, even though it's appeared as assigned by default.

I had to assign the same key myself to make it work.

Weird, I remove the keybinding that I've assigned and now they key is working. Guess it's fixed by an update.
