### ISSUE TITLE
High CPU overload after update to VSCode 1.19.1

### ISSUE THREAD

**Issue by pwaykole** [Microsoft/vscode#41058] opened 2018-01-02 21:36 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
run-current-test|asv|0.1.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
gitlens|eam|7.2.0
prettier-vscode|esb|1.0.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
vscode-flow-ide|gca|1.2.0
debugger-for-chrome|msj|4.0.0
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7
es6-mocha-snippets|spo|0.0.5
react-redux-es6-snippets|tim|2.1.0
vscode-import-cost|wix|2.6.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.7.0

(2 theme extensions excluded)

---

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2018-01-02 22:02
Please follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to provide more information about this issue

**Comment by pmbanugo** [comment] 2018-01-03 11:13
I'm experiencing the same thing and it decreases my battery at a very fast rate.

**Comment by MikeB2012** [comment] 2018-01-03 15:29
Since upgrade, when I launch VS Code I get 100% CPU usage.  VS Code shows 35 processes running with four windows open.  When I run "code --status" I get the following:

PS C:\Program Files\Microsoft VS Code> code --status

[main 10:26:17 AM] SyntaxError: Unexpected token  in JSON at position 1754
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:132:413)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by kostasmanionis** [comment] 2018-01-03 16:26
@pwaykole Had the same issue, found out that disabling `vscode-import-cost` solves that issue, see https://github.com/wix/import-cost/issues/47. I can see that you're using the same extension, are you sure you can reproduce it with extensions disabled?

**Comment by mjbvz** [comment] 2018-01-03 16:44
Thanks! Closing as caused by extension.

#41105 tracks the `code --status` issue

**Closed by mjbvz** 2018-01-03 16:44 UTC
Labels: needs more info

**Comment by shahata** [comment] 2018-01-17 19:36
Issue is fixed in import-cost version 2.6.2, sorry for the trouble...
