### ISSUE TITLE
vscode-mysql extension broke in insiders 1.28.0

### ISSUE THREAD

**Issue by mckennatim** [Microsoft/vscode#58300] opened 2018-09-09 16:58 UTC
- VSCode Insiders Version:  1.28.0
- OS Version: windows 7 
MYSQL extension version: vscode-mysql 0.3.0

The recent version of insiders seems to break my favorite extension  It actually can run queries but the results window comes up blank. Weirdly, extension settings has its header showing but details is empty.

vscode-mysql works fine on vscode regular 1.27.1

**Comment by mjbvz** [comment] 2018-09-10 06:32
Duplicate of #58203

**Closed by mjbvz** 2018-09-10 06:32 UTC
Labels: extensions
