### ISSUE TITLE
Undo after save would move the cursor to first line rather than the place of last changes

### ISSUE THREAD

**Issue by zinechant** [Microsoft/vscode#46841] opened 2018-03-28 12:31 UTC
- VSCode Version: 1.21.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open a file with more than one screen.
2. Edit. Save. Undo
3. The cursor would first be moved back to the first line.

Does this issue occur when all extensions are disabled?: No

**Comment by alexandrudima** [comment] 2018-03-28 13:57
Duplicate of #46208

**Closed by alexandrudima** 2018-03-28 13:57 UTC
Labels: editor, editor-core
