### ISSUE TITLE
Clear screen is not working correctly in the Integrated Terminal

### ISSUE THREAD

**Issue by suvjunmd** [Microsoft/vscode#15672] opened 2016-11-17 20:08 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 10.0.14393 x64

Steps to Reproduce:

1. Open Integrated Terminal
2. Write help
3. Write cls

The terminal history is not being cleared. Instead it is just scrolled down.

![cls](https://cloud.githubusercontent.com/assets/11020536/20405539/3190a1a4-ad12-11e6-9eb4-2c3e1e5f5214.gif)

**Comment by ramya-rao-a** [comment] 2016-11-17 20:53
Closing as duplicate of #11249

**Closed by ramya-rao-a** 2016-11-17 20:53 UTC
