### ISSUE TITLE
Workbench navigation commands stop working inside WebView when switching to another editor and back

### ISSUE THREAD

**Issue by infokiller** [microsoft/vscode#137167] opened 2021-11-14 15:53 UTC
Issue Type: <b>Bug</b>
CC @mjbvz 
This is a follow-up to #119076

- Open a vanilla VSCode with no settings and extensions:
```sh
code --user-data-dir /tmp/vscode-repro-nav --disable-extensions
```
- Set the following keybindings:
```json
[
  {
    "key": "f1",
    "command": "workbench.action.navigateLeft"
  },
  {
    "key": "f2",
    "command": "workbench.action.navigateRight"
  }
]
```
- Open some file, say `test.py`
- Use `workbench.action.splitEditorRight` to split the editor to the right
- Use `update.showCurrentReleaseNotes`  to open the Release Notes WebView
- Click with the mouse inside the Release Notes WebView
- Type <kbd>F1</kbd> from the WebView to navigate to the left editor: it works following 6e5b172
- Navigate in the **right** editor group (where the Release Notes WebView are open) to the file `test.py` with the keyboard (for example using <kbd>Ctrl+Tab</kbd>)
- Navigate back to the Release Notes WebView with the keyboard (for example using <kbd>Ctrl+Tab</kbd>)
- Type <kbd>F1</kbd> from the WebView to navigate to the left editor: it no longer works

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.14.16-hardened1-1-hardened
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled_force<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|94.00GB (3.33GB free)|
|Process Argv|--enable-gpu-rasterization --user-data-dir /tmp/vscode-test-data-dir --folder-uri /tmp/vscode-test-repo --disable-extensions --crash-reporter-id 1a24c498-5487-42be-8c72-40410e66ca6b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by mjbvz** [comment] 2022-05-11 23:41
I can't reproduce this on MacOS with the current insiders build. Possibly fixed by c485c00298d3341d16539554ee66f6dace15811f

Closing for verification

**Closed by mjbvz** 2022-05-11 23:41 UTC
Labels: webview
