### ISSUE TITLE
VSCode does not respect trailing slashes in gitignore entries

### ISSUE THREAD

**Issue by samuela** [Microsoft/vscode#38270] opened 2017-11-14 02:10 UTC
- VSCode Version: 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7)
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Write a gitignore with a folder excluded like `__pycache__/`.
2. Observe that the `__pycache__/` folder has not been marked as ignored by VSCode but is ignored by git.
3. Replace `__pycache__/` in your gitignore with `__pycache__`.
4. Observe that the `__pycache__/` folder has now been marked as ignored.

Reproduces without extensions: Yes

![screen shot 2017-11-13 at 6 09 18 pm](https://user-images.githubusercontent.com/226872/32759339-d4febee6-c89d-11e7-8ca6-4592ff5d03b2.png)
![screen shot 2017-11-13 at 6 09 34 pm](https://user-images.githubusercontent.com/226872/32759340-d51a2cf8-c89d-11e7-8326-6245183245a2.png)

**Comment by jrieken** [comment] 2017-11-14 07:38
> Observe that the __pycache__/ folder has not been marked as ignored by VSCode but is ignored by git.

VS Code doesn't interpret the ignore-file. Instead we call `git check-ignore` with the files that are to be rendered. So, please run this on the terminal: `git check-ignore __pycache__/` and `git check-ignore __pycache__`

**Comment by samuela** [comment] 2017-11-14 08:26
Regardless of whether I have `__pycache__` or `__pycache__/` in my .gitignore I get

```
$ git check-ignore __pycache__/
__pycache__/
$ git check-ignore __pycache__
__pycache__
```

**Comment by samuela** [comment] 2017-11-14 20:21
Also,

```
$ git --version
git version 2.13.6 (Apple Git-96)
```

**Comment by jrieken** [comment] 2017-11-15 09:18
Funky.... I am on git 2.14.1 and things just work fine. Can you try again with latest insiders as we did make a few other fixes in that area.

![nov-15-2017 10-17-00](https://user-images.githubusercontent.com/1794099/32827980-28c622d4-c9ee-11e7-866f-d0216ccc3c32.gif)

**Comment by samuela** [comment] 2017-11-15 10:12
@jrieken Ah ok, it works as expected on Insiders.

**Comment by jrieken** [comment] 2017-11-15 11:28
Awesome.... I am closing this as a dupe of #37857 which made sure when calling git we talk to it like a machine, not like a human

**Closed by jrieken** 2017-11-15 11:28 UTC
Labels: file-decorations, needs more info, new release
