### ISSUE TITLE
Remove border in editor right hand side over scrollbar

### ISSUE THREAD

**Issue by zhaomiing** [Microsoft/vscode#17506] opened 2016-12-19 03:39 UTC
- VSCode Version: 1.80
- OS Version: macOS 10.12.2

**Comment by bpasero** [comment] 2016-12-19 19:28
@zhaomiing can you attach a screenshot of what you mean?

**Comment by zhaomiing** [comment] 2016-12-20 02:10
@bpasero thanks for your reply. of course
this is what scrollbar looks like in preview mode
![image](https://cloud.githubusercontent.com/assets/6185738/21335683/7600059e-c69b-11e6-8ba7-f1a808a73680.png)
and this in edit mode
![image](https://cloud.githubusercontent.com/assets/6185738/21335674/659bf97e-c69b-11e6-92b9-5b1e81e944f6.png)
as you can see the white border was distracting.

**Comment by bpasero** [comment] 2016-12-20 05:55
@zhaomiing what is the "preview mode"?

**Comment by zhaomiing** [comment] 2016-12-20 06:36
well forget about the 'preview mode'. 
It seems like VSCode could remember files it ever opened or edited, and scrollbar will always like the 2nd screenshot on these files. But if you preview a new file VSCode has never known the scrollbar was like the 1st screenshot. I'm not sure if this's the actual logic but it behaves like this.

**Comment by bpasero** [comment] 2016-12-20 06:42
We seem to show the border as long as we have a marker to show there. I also agree that the border is distracting and wonder if we cannot just remove it always.

**Comment by cor** [comment] 2017-01-17 13:14
Any updates on this yet? This, along with the blue status bar (#1884) are the only things that keep this editor from looking really great.

**Comment by alexandrudima** [comment] 2017-01-21 01:11
Duplicate of #5099

**Closed by alexandrudima** 2017-01-21 01:11 UTC
Labels: editor
