### ISSUE TITLE
acceptSuggestionOnEnter will start new line when typed whole word

### ISSUE THREAD

**Issue by songtm** [Microsoft/vscode#26109] opened 2017-05-06 09:40 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jetjet-theme|JohnyGeorges|0.12.0|
|unity-debug|Unity|1.2.0|
|unity-snippets|YclepticStudios|0.1.2|
|Bookmarks|alefragnani|0.14.1|
|csharp|ms-vscode|1.9.0|
|guides|spywhere|0.7.0|
|vscode-lua|trixnz|0.5.0|;

---

Steps to Reproduce:
set  "editor.acceptSuggestionOnEnter": true
1. type the exact word which is in the suggestion list(such as "using" )
2.press the enter key
it will not accept the suggestion but start a new line, but if you press the tab key it will accept the suggestion.

**Comment by jrieken** [comment] 2017-05-08 07:35
This is a dupe of https://github.com/Microsoft/vscode/issues/24420. The have tweak the enter behaviour to insert a newline when suggestions popped up automatically (24x7 IntelliSense, not via ctrl+space) and when the selected suggestion doesn't make a text edit. We have done this because user complained about the Enter-key being "stolen". If you disagree with this change, please comment here, where we collect the feedback for this feature: https://github.com/Microsoft/vscode/issues/24420

**Closed by jrieken** 2017-05-08 07:35 UTC
Labels: duplicate
