### ISSUE TITLE
Emmet does not autocomplete when press tab or enter

### ISSUE THREAD

**Issue by zhangta** [microsoft/vscode#177549] opened 2023-03-18 04:11 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2
- OS Version: Windows10 22H2 19045

https://user-images.githubusercontent.com/415229/226083879-87eace4a-ee5d-4493-bad5-ff1f4382819f.mp4

Please watch this video, thanks.

**Comment by lishujun5** [comment] 2023-03-18 11:06
same issue +1

**Comment by geril2207** [comment] 2023-03-19 21:02
Same bug, first suggestion from list sometimes just not selected

**Comment by lishujun5** [comment] 2023-03-20 01:47
Why is it such a serious basic bug that no one responds in time?

**Comment by geril2207** [comment] 2023-03-20 07:14
> Why is it such a serious basic bug that no one responds in time?

Even if they respond in time, the fix will be released in the next update (1.76.3 or 1.77). U can downgrade vscode by selecting one of the versions https://code.visualstudio.com/updates/1_76 If you choose to downgrade vscode you probably should disable auto update in settings ` "update.mode": "none"`

**Comment by lishujun5** [comment] 2023-03-20 07:31
> > Why is it such a serious basic bug that no one responds in time?
> 
> Even if they respond in time, the fix will be released in the next update (1.76.3 or 1.77). U can downgrade vscode by selecting one of the versions https://code.visualstudio.com/updates/1_76 If you choose to downgrade vscode you probably should disable auto update in settings ` "update.mode": "none"`

I have downgraded the version to 1.75 and  it recovers. thanks

**Comment by aeschli** [comment] 2023-03-22 10:39
Duplicate of https://github.com/microsoft/vscode/issues/173387

**Closed by aeschli** 2023-03-22 10:39 UTC
