### ISSUE TITLE
JSDoc header block breaks indentation

### ISSUE THREAD

**Issue by SomervilleTom** [microsoft/vscode#164897] opened 2022-10-28 15:30 UTC
Does this issue occur when all extensions are disabled?: I don't know. I'm using the "Remote SSH" extension, and so all of the JS files I'm editing are on a remote system. That's an AWS EC2 instance running Rocky Linux V8.6.

- VS Code Version:
```
Version: 1.69.0 (system setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.18363
```

See [JSDoc standard](https://jsdoc.app/).

Adding a JSDoc class or method header breaks indention in the rest of a JS file -- an extra leading space is added to each line.

When refactoring to copy multiple methods and headers from one file to another, a properly-formatted JSDoc header at the top of the copied code breaks the indentation of the entire paste.

Steps to Reproduce (single header and method):

This reproduces the issue for a single header and method.

1. Enter jsdoc method header:

    ```
    /**
     * Answers a personaHash for the given userID
     */
    ```
2. Copy left-aligned JS method:

    ```
    const personaHashForUserID = (userID) => {
      return userIDPersonaHash[userID];
    }
    ```

3. Paste JS fragment after JSDoc

    VSC will improperly add a single space indent to the first line of the copied method. This has the effect of aligning the first line of the pasted code with the "*" in the block comment terminator.

    ```
    /**
     * Answers a personaHash for the given userID
     */
     const personaHashForUserID = (userID) => {
      return userIDPersonaHash[userID];
    }
    ```

A temporary work-around is to terminate each JSDoc header with an extra "*", as follows:

```
/**
 * JSDoc header with extra '*' in block comment terminator
**/
```

This fixes the VSC code formatting problem but violates the JSDoc standard.

VSC should behave properly while editing JS files with JSDoc headers.

**Comment by mjbvz** [comment] 2022-10-28 19:49
Duplicate of #121004

**Closed by mjbvz** 2022-10-28 19:49 UTC
