### ISSUE TITLE
User settings/config reset/wiped/empty on zooming

### ISSUE THREAD

**Issue by chibicode** [Microsoft/vscode#56168] opened 2018-08-10 19:50 UTC
- VSCode Version: 1.25.1 
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. On launch, **before the UI even fully loads**, immediately press my custom keybinding to invoke `workbench.aciton.zoomIn` about 4 times (as quickly as possible).
2. VS Code says "needs to restart to apply settings"
3. While the dialog was open, the theme was reset to the default theme.
4. When I clicked restart, it reopened but the config setting was wiped out completely.

<img width="468" alt="screen shot 2018-08-10 at 12 46 58 pm" src="https://user-images.githubusercontent.com/992008/43978253-7e4c5efa-9c9b-11e8-94cf-d5c9bc48ce5e.png">

### Related Issues

This looks like the same issue as https://github.com/Microsoft/vscode/issues/26381, which is now locked (reported by @motebotic @jrieken @alexandrudima @bpasero). I saw this issue as well: https://github.com/Microsoft/vscode/issues/25427 (by @sandy081) but is also locked.

I did NOT set any of `window.titleBarStyle, window.nativeTabs, update.channel, telemetry.enableCrashReporter`.

### Enabled Extensions

- Atom Keymap
- Auto Comment Blocks
- bluloco-light
- Bookmarks
- Bracket Pair Colorizer
- carbon-now-sh
- Debugger for Chrome
- Document This
- ESLint
- File Utils
- GitLens — Git supercharged
- Go
- GraphQL
- Night Owl
- npm Intellisense
- Open in GitHub, Bitbucket, Gitlab, VisualStudiocom !
- Path Intellisense
- Prettier - Code formatter
- pyre-vscode
- Python
- React Native Tools
- Ruby
- Settings Sync
- Sort JSON objects
- TSLint
- Vetur
- VS Live Share
- vscode-icons
- vscode-styled-components
- XML Tools

**Comment by chibicode** [comment] 2018-08-10 19:57
I'm wondering if this is a race condition problem. I've invoked `workbench.aciton.zoomIn` **immediately** after the editor launch like 4 times, while the UI is not even done loading.

**Comment by sandy081** [comment] 2018-08-13 13:31
Duplicate of #47763

**Closed** 2018-08-13 13:31 UTC
Labels: *duplicate, config, settings-editor
