### ISSUE TITLE
Double click on any word continue the selection instead of just selecting one word only

### ISSUE THREAD

**Issue by CodingCreate101** [microsoft/vscode#146976] opened 2022-04-07 05:36 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Darwin x64 21.1.0

```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.1.0
```
Steps to Reproduce:
1. Double tap on any word
2. Immediately move the cursor
3. You will see that the selection continues to happen (not all the time, but most of the time)

Expected:
This didn't happen before. 

Double click should select the word and do nothing.

Video for reference - 

https://user-images.githubusercontent.com/13194757/162126668-3b95199a-71bf-42f7-a5be-9d96383583f6.mov

**Comment by alexdima** [comment] 2022-04-07 08:25
Duplicate of https://github.com/microsoft/vscode/issues/146486

**Closed by alexdima** 2022-04-07 08:25 UTC
Labels: macos
