### ISSUE TITLE
Cannot Disable Sticky Hover 

### ISSUE THREAD

**Issue by archer003** [microsoft/vscode#229320] opened 2024-09-22 22:58 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Linux, Arch

**Steps to Reproduce:**

1. use these settings: "editor.hover.sticky": false, "editor.hover.delay": 0, "editor.hover.hidingDelay": 0
2. hover over some code so that a hover panel appears, for example hovering a line of CSS shows something from MDN 
3. move mouse cursor over the hover

expected: hover panel disappears
actual: hover panel is still shown, as if editor.hover.sticky were true

**Additional Info:**

I don't know when exactly this problem began, but it has been a while. I think a few months. I typically use the newest stable vscode within a week or two of it releasing.

Sometimes, it works correctly for a while after launching or restarting vscode. But after a few minutes, the problem appears again.

**Workaround:**

If anyone else is looking for an immediate fix, I quickly figured one out after I was very irritated by this today. 
1. Use the "Custom CSS and JS Loader" extension.
2. Inject the following CSS:
```
div.overflowingContentWidgets div[widgetid="editor.contrib.resizableContentHoverWidget"]:hover {
	display: none !important;
}
```
After doing so, my hover works correctly and smoothly again.

**Comment by archer003** [comment] 2024-10-09 14:15
I updated to version 1.94.1.

The bug is still present. I checked with all extensions disabled.

My workaround still works.

**Comment by archer003** [comment] 2024-11-06 12:49
I updated to version 1.95.1.

The bug is still present. I checked with all extensions disabled.

I found a clue about the cause. Initially, when opening a new vscode instance, hovering works correctly. When I hover over a color code in CSS, it brings up a sticky color selector. Afterwards, all hovers are sticky until I launch a fresh vscode instance again.

**Comment by aiday-mar** [comment] 2024-12-09 16:20
Hi thank you for filing this issue. I am not able to reproduce this issue on our nightly Insiders release. We have made some improvements both to the hover and the color decorators recently. Do you see this issue on the latest daily release?


https://github.com/user-attachments/assets/b4c45c9d-b4bf-4c17-8278-f7e41a14d7b0

**Comment by archer003** [comment] 2024-12-09 17:30
I tried a daily build and it seems fixed.

Thanks for looking into it.

Version tried:

Version: 1.96.0-insider
Commit: b18e7a700033b39ed2c3975759b6327c8205f958
Date: 2024-12-08T16:04:45.916Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.10.10-zen1-1-zen

**Comment by aiday-mar** [comment] 2024-12-09 18:02
Thank you for confirming. I will close this issue.

**Closed by aiday-mar** 2024-12-09 18:02 UTC
Labels: info-needed, editor-hover
