### ISSUE TITLE
Colors are missing

### ISSUE THREAD

**Issue by RyderKishan** [microsoft/vscode#92562] opened 2020-03-12 09:47 UTC
Issue Type: <b>Bug</b>

There has been some changes in the colors. Even i switch to any new themes the original colors renders, Then the wrong colors comes. I tried re installing.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|16.00GB (2.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
vscode-docker|ms-|1.0.0
vscode-icons|vsc|10.0.0

(1 theme extensions excluded)

</details>

**Comment by dhulme** [comment] 2020-03-12 10:11
Do you mean in syntax highlighting? I've noticed this in JS

![image](https://user-images.githubusercontent.com/1234671/76510654-d8264b80-6449-11ea-88b2-e7c56ab27e3d.png)

'Promise' used to be highlighted

**Comment by gjsjohnmurray** [comment] 2020-03-12 12:13
/duplicate of #90379

As a workaround you could disable semantic highlighting

**Closed by gjsjohnmurray** 2020-03-12 12:13 UTC
Labels: *duplicate, new release

**Comment by dhulme** [comment] 2020-03-12 16:32
I'm a bit confused, was this an intended change? Or a regression in the latest release? The linked issue was closed 20 days ago?

**Comment by gjsjohnmurray** [comment] 2020-03-12 19:34
Open issue is #91090

**Comment by gjsjohnmurray** [comment] 2020-03-12 19:40
Even better, #92308
