### ISSUE TITLE
Notebook, "save as" not working

### ISSUE THREAD

**Issue by perdigao1** [microsoft/vscode#122833] opened 2021-05-03 08:05 UTC
Issue Type: <b>Feature Request</b>

Try to create a new python workbook by doing Ctrl+shift+P Jupyter->Create a new blank workbook. A new notebook is created with name Untitled...ipynb.
Write on the notebook (or not write) and then try File->Save as , Nothing happens

Expected: A dialog prompting user to choose a filename

Tested, VS code on Linux Xubuntu

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 4.15.0-142-generic

**Comment by rebornix** [comment] 2021-05-03 15:50
@perdigao1 can you share a screen shot of the notebook you are using (it can be a blank one).

**Comment by perdigao1** [comment] 2021-05-03 17:34
Hi,

Please see attached
![Opera Snapshot_2021-05-03](https://user-images.githubusercontent.com/13090219/116910946-327dff00-ac3e-11eb-8b30-e48993886d8c.png)

**Comment by bpasero** [comment] 2021-05-21 11:36
Duplicate of https://github.com/microsoft/vscode/issues/121974

**Closed** 2021-05-29 11:33 UTC
Labels: needs more info, workbench-untitled-editors
