### ISSUE TITLE
Regions in Powershell scripts do not function as expected

### ISSUE THREAD

**Issue by kendalf1** [Microsoft/vscode#17091] opened 2016-12-12 21:03 UTC
- VSCode Version:1.7.2
- OS Version: 10

Steps to Reproduce:

1. Using #region and the #endregion, creates collapsible sections of code in most powershell ISE's.  This does not work in VS Code.

**Comment by aeschli** [comment] 2016-12-13 08:48
duplicate of #10900

**Closed by aeschli** 2016-12-13 08:48 UTC
