### ISSUE TITLE
The Enter key and the Backspace key react very slowly

### ISSUE THREAD

**Issue by suning2012** [Microsoft/vscode#71125] opened 2019-03-26 02:28 UTC
Issue Type: <b>Bug</b>

回车键(enter)  退格键(backspace) 反应很慢

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
html-snippets|abu|0.2.1
autofoldyeah|bob|1.0.6
wechat-snippet|Cha|0.4.10
vscode-wxml|cod|0.1.9
dakara-foldplus|dak|1.3.2
vscode-markdownlint|Dav|0.25.1
jshint|dba|0.10.20
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
EditorConfig|Edi|0.13.0
we-app-vscode|eme|0.8.0
prettier-vscode|esb|1.8.1
beautify|Hoo|1.4.11
ftp-sync|luk|0.3.9
vscode-exec-node|mir|0.5.1
vscode-language-pack-zh-hans|MS-|1.32.4
python|ms-|2019.2.5558
cpptools|ms-|0.22.1
Go|ms-|0.9.2
vetur|oct|0.17.1
simple-ftp|Ous|0.0.1
vuehelper|oys|0.1.0
tslint-vue|pro|1.5.6
minapp-vscode|qiu|1.13.0
vue-vscode-snippets|sdr|1.3.0
markdown-preview-enhanced|shd|0.3.13
language-stylus|sys|1.11.0
vue-docs|tit|1.0.1
vscode-fold-level|vik|0.0.11
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.2.0

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment] 2019-03-26 07:16
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by weinand** [comment] 2019-04-01 17:45
no reply -> closing

**Closed by weinand** 2019-04-01 17:45 UTC
Labels: needs more info
