### ISSUE TITLE
How to make the file tab of workbench to show the number on the left of the file name?

### ISSUE THREAD

**Issue by clixiang** [Microsoft/vscode#56071] opened 2018-08-09 09:58 UTC
How to make the file tab of workbench to show the number on the left of the file name?

for example:

![](https://raw.githubusercontent.com/clixiang/clixiang.github.io/master/2018/07/25/java/using-vscode/3333336.png)

**Comment by bpasero** [comment] 2018-08-09 10:26
Currently not possible. Duplicate of https://github.com/Microsoft/vscode/issues/43437

**Closed by bpasero** 2018-08-09 10:26 UTC
