### ISSUE TITLE
Allow us to define width of the find widget

### ISSUE THREAD

**Issue by skyhirider** [microsoft/vscode#76795] opened 2019-07-07 09:42 UTC
The width of the find widget (Ctrl+F) can be changed by dragging the mouse.

Could you add a setting under Text Editor -> Find that would allow us to set the default size of the widget?

I would prefer it to start maximized (100% width) instead of having to drag it.

Or have it dynamically expand as more text is typed into it.

**Comment by rebornix** [comment] 2019-07-26 22:54
/duplicate of https://github.com/microsoft/vscode/issues/15727

**Closed** 2019-07-26 22:54 UTC
Labels: *duplicate, editor-find, feature-request
