### ISSUE TITLE
Request feature - h + v - view mode split in to 4 screen. 

### ISSUE THREAD

**Issue by office-work-account** [Microsoft/vscode#29754] opened 2017-06-28 13:04 UTC
Wishlist feature:
Split screen into 4 peace.

**Comment by ZombieProtectionAgency** [comment] 2017-06-28 19:10
I think this is covered by #14909.

**Comment by office-work-account** [comment] 2017-07-24 12:00
4 or more. VSC is based up on web technology - why not use CSS property,  `{ display: grid } ` for instance?

**Comment by ZombieProtectionAgency** [comment] 2017-07-24 14:40
@office-work-account I dont think they have a major problem with display besides deciding how overflow and widths should behave. Currently it looks like most of the code is built around the assumption that you only have 3 sections in the same direction which means this implementation would require a rework in all logic that deals with the workspace.

**Comment by office-work-account** [comment] 2017-08-02 12:18
So 4 or more it's being able to show when it's written ext. by the independent developer.

**Comment by office-work-account** [comment] 2017-09-21 13:46
Now VSC support... 3 window. 2 Vectrical on Right and one Horizontal on Left... :)
Screen bellow (No photo edit)
https://s26.postimg.org/6d9c6fuk9/Zrzut_ekranu_w_2017-09-21_15-43-30.png

**Comment by bpasero** [comment] 2017-11-16 17:14
Closing as duplicate of many other issues.

**Closed by bpasero** 2017-11-16 17:14 UTC
Labels: feature-request, workbench
