### ISSUE TITLE
Having multiple windows open eats up cpu resources.

### ISSUE THREAD

**Issue by brianmwadime** [Microsoft/vscode#23077] opened 2017-03-23 07:39 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|html-symbols|DiegoMolina|0.0.2|
|nativescript|Telerik|0.6.1|
|vscode-nsp|adambaldwin|1.0.1|
|vscode-caniuse|akamud|0.5.3|
|vscode-tidyhtml|anweber|1.3.0|
|django-snippets|bibhasdn|1.1.0|
|cjsx|crisward|0.0.6|
|vscode-svgviewer|cssho|1.4.0|
|vscode-coffeescript-snippets|diniremix|0.0.2|
|python|donjayamanne|0.6.0|
|vscode-coffeescript-preview|drewbarrett|0.1.4|
|vscode-coffeescript-eval|eheitherd|1.0.0|
|vs-code-xml-format|fabianlauer|0.1.4|
|sass-lint|glen-84|0.0.3|
|angular-bootstrap|herrherrmann|4.0.6|
|vscode-map-preview|jumpinjackie|0.4.2|
|vscode-circleci|jvandyke|0.1.2|
|HTMLHint|mkaufman|0.3.3|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.10.4|
|csharp|ms-vscode|1.8.0|
|jscs|ms-vscode|0.1.9|
|latex|ms-vscode|0.1.3|
|mono-debug|ms-vscode|0.15.3|
|debugger-for-chrome|msjsdiag|2.7.0|
|debugger-for-ios-web|msjsdiag|0.1.2|
|require-complete|sensourceinc|0.0.3|
|vscode-coffeelint|slb235|0.0.2|
|cordova-tools|vsmobile|1.2.7|
|vscode-react-native|vsmobile|0.3.1|
|debug|webfreak|0.17.0|;

---

Steps to Reproduce:

1. Open multiple projects
2. Eats up CPU, laptop starts to heat up.

**Comment by sean-mcmanus** [comment] 2017-03-23 15:38
Our cpptools extension is a likely contributor, but it's likely "by design". Setting `"C_Cpp.addWorkspaceRootToIncludePath": false` should fix it, assuming your c_cpp_properties settings aren't causing an issue. You can also kill the Microsoft.VSCode.Cpp.Extenion process. You can file an issue at https://github.com/Microsoft/vscode-cpptools/issues .

**Comment by rebornix** [comment] 2017-03-23 20:57
@brianmwadime can you confirm if you are running into the issue @sean-mcmanus mentioned above?

**Comment by brianmwadime** [comment] 2017-03-24 07:40
@rebornix it looks like @sean-mcmanus was right.
I just uninstalled the plugin and so far I'm able to open multiple project windows without an issue anymore.
I'll file an issue on vscode-cpptools repo as well.

Thanks guys!

**Comment by aeschli** [comment] 2017-03-27 19:36
I'm closing the issue then

**Closed by aeschli** 2017-03-27 19:36 UTC
Labels: caused-by-extension, needs more info
