### ISSUE TITLE
JSON at position 17219

### ISSUE THREAD

**Issue by Armourgigs** [microsoft/vscode#103664] opened 2020-07-30 21:55 UTC
Issue Type: <b>Bug</b>

Unable to open 'index.html': Unexpected token : in JSON at position 17279.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:31:37.228Z)
OS version: Windows_NT ia32 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) CPU N270   @ 1.60GHz (2 x 1596)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.99GB (0.42GB free)|
|Process Argv|C:\Users\Salvation GTT\Pictures\SALVATION\My Codes\HTML & CSS|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
project-manager|ale|11.1.0
turbo-console-log|Cha|1.4.0
bracket-pair-colorizer-2|Coe|0.2.0
my-nbpreviewer|col|1.2.2
jupyter|don|1.1.5
vscode-html-css|ecm|0.2.3
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
vscode-firefox-debug|fir|2.9.0
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
vscode-auto-open-markdown-preview|hnw|0.0.4
vsc-python-indent|Kev|1.10.1
python|ms-|2020.7.96456
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
LiveServer|rit|5.6.1
jupyter-notebook-vscode|sam|0.0.2
autoimport|ste|1.5.3
NbConverter|yig|1.4.0

(1 theme extensions excluded)

</details>

**Comment by Armourgigs** [comment] 2020-07-30 22:00
![Screenshot (7)](https://user-images.githubusercontent.com/66418871/88978690-1b2d7200-d2b8-11ea-872f-b94d40c275b0.png)
Here is a screenshot showing the issue I just reported above...

**Comment by NotWearingPants** [comment] 2020-07-31 05:59
Try running VSCode with `code --disable-extensions` to temporarily disabled all your extensions. Does the problem still occur?

**Comment by gjsjohnmurray** [comment] 2020-07-31 06:09
Also see #102251 #102601 #98536 for some suggestions.

**Comment by aeschli** [comment] 2020-08-11 12:22
duplicate of https://github.com/microsoft/vscode/issues/102251.

Can you try if https://github.com/microsoft/vscode/issues/102251#issuecomment-671912942 works as work around?

**Closed by aeschli** 2020-08-11 12:22 UTC
