### ISSUE TITLE
Feature Request: Please add a switch that would allow "editor.action.blockComment" to comment out empty lines as well

### ISSUE THREAD

**Issue by Glober777** [microsoft/vscode#78546] opened 2019-08-06 09:20 UTC
Often times when I need to temporarily comment out a block of code, the next thing I'd like to do on it, is to hide it by collapsing. The problem is that whenever the commented block has empty lines the "editor.action.blockComment" command skips those, hence the commented block ends up being split up into a number of separate comment blocks, requiring me to collapse each one individually.

**Comment by rebornix** [comment] 2019-08-06 17:58
/duplicate of https://github.com/microsoft/vscode/issues/65109

**Closed** 2019-08-06 17:58 UTC
Labels: *duplicate, editor-commands, feature-request
