### ISSUE TITLE
Toggling explorer when file comparison is open "select-opens" second comparison file

### ISSUE THREAD

**Issue by wrummler** [Microsoft/vscode#45775] opened 2018-03-14 15:06 UTC
Issue Type: <b>Bug</b>

1. Open a folder.
2. Open the explorer.
3. Right-click a file and "Select for Compare".
4. Right-click another file and "Compare with Selected".
5. Close the explorer.
6. Open the explorer.

Expected: Editors remain as-is from step 5 to step 6.

Actual: The "select-open" editor (the editor that has italic title font and gets auto-opened when you click on a file in the explorer) opens (or reopens) with the content of the file from step 4.

It's slightly more painful when you haven't "pinned" open the comparison editor, since the comparison is then still in the "select-open" editor, which gets nuked and replaced with the contents of that one file.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|Memory (System)|15.91GB (8.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.2
ng-template|Ang|0.1.9
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.14.0
xml|Dot|1.9.2
gitlens|eam|8.1.1
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.2.2
fortran|Gim|0.2.0
mssql|ms-|1.3.0
python|ms-|2018.2.1
csharp|ms-|1.14.0
team|ms-|1.122.0
debugger-for-chrome|msj|4.2.0
java|red|0.20.0
rust|rus|0.4.0
rewrap|stk|1.8.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2
plsql-language|xyz|1.1.2

</details>
Reproduces without extensions

**Comment by bpasero** [comment] 2018-03-14 15:30
@isidorn feel free to close as designed, we do this intentionally to return to the context of the explorer.

**Comment by isidorn** [comment] 2018-03-14 16:28
@bpasero I just tried this and I agree with the user this is not nice behavior in this case. However the more general case is that you are looking at the diff in git view and are coming to the explorer. In that case you want to quickly get rid of the open diff. Due to that closing as designed
Here's the actual code that is responsible for this behavior https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L378

**Closed** 2018-03-14 16:29 UTC
Labels: as-designed, file-explorer

**Comment by wrummler** [comment] 2018-03-14 16:50
I agree with this explanation. Thanks for the review guys.
