### ISSUE TITLE
Key chords break keybindings

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16498] opened 2016-12-05 11:46 UTC
No steps yet, but since today keybindings stop working when using Zen mode

**Comment by jrieken** [comment] 2016-12-05 11:49
This is what the context looks like

```
"{
   "_contextId": 4,
   "inQuickOpen": false,
   "inDebugMode": false,
   "globalMessageVisible": false,
   "editorIsOpen": true,
   "inZenMode": true,
   "config.editor.insertSpaces": false,
   "config.editor.detectIndentation": true,
   "config.editor.roundedSelection": true,
   "config.editor.scrollBeyondLastLine": true,
   "config.editor.wordWrap": false,
   "config.editor.quickSuggestions": true,
   "config.editor.parameterHints": true,
   "config.editor.autoClosingBrackets": true,
   "config.editor.formatOnType": true,
   "config.editor.suggestOnTriggerCharacters": true,
   "config.editor.acceptSuggestionOnEnter": true,
   "config.editor.emptySelectionClipboard": true,
   "config.editor.wordBasedSuggestions": true,
   "config.editor.tabCompletion": true,
   "config.editor.selectionHighlight": true,
   "config.editor.mouseWheelZoom": false,
   "config.editor.fontLigatures": true,
   "config.editor.hideCursorInOverviewRuler": false,
   "config.editor.renderControlCharacters": false,
   "config.editor.renderIndentGuides": false,
   "config.editor.codeLens": true,
   "config.editor.folding": true,
   "config.editor.glyphMargin": true,
   "config.editor.useTabStops": true,
   "config.editor.trimAutoWhitespace": true,
   "config.editor.stablePeek": false,
   "config.editor.formatOnSave": true,
   "config.diffEditor.renderSideBySide": true,
   "config.diffEditor.ignoreTrimWhitespace": true,
   "config.diffEditor.renderIndicators": true,
   "config.http.proxyStrictSSL": true,
   "config.telemetry.enableTelemetry": true,
   "config.telemetry.enableCrashReporter": true,
   "config.search.exclude.**/node_modules": true,
   "config.search.exclude.**/bower_components": true,
   "config.search.exclude..build/**": true,
   "config.search.exclude.out*/**": true,
   "config.search.exclude.i18n/**": true,
   "config.search.exclude.extensions/**/out/**": true,
   "config.search.quickOpen.includeSymbols": false,
   "config.files.exclude.**/.git": true,
   "config.files.exclude.**/.svn": true,
   "config.files.exclude.**/.hg": true,
   "config.files.exclude.**/.DS_Store": true,
   "config.files.exclude..git": true,
   "config.files.exclude..build": true,
   "config.files.trimTrailingWhitespace": true,
   "config.files.insertFinalNewline": true,
   "config.files.watcherExclude.**/.git/objects/**": true,
   "config.files.watcherExclude.**/node_modules/**": true,
   "config.files.hotExit": true,
   "config.explorer.openEditors.dynamicHeight": true,
   "config.explorer.autoReveal": false,
   "config.explorer.enableDragAndDrop": true,
   "config.problems.autoReveal": true,
   "config.git.enabled": true,
   "config.git.autorefresh": true,
   "config.git.autofetch": true,
   "config.git.enableLongCommitWarning": true,
   "config.git.allowLargeRepositories": false,
   "config.git.confirmSync": false,
   "config.terminal.integrated.fontLigatures": false,
   "config.terminal.integrated.cursorBlinking": false,
   "config.terminal.integrated.setLocaleVariables": true,
   "config.debug.allowBreakpointsEverywhere": false,
   "config.debug.openExplorerOnEnd": false,
   "config.workbench.editor.showTabs": false,
   "config.workbench.editor.showTabCloseButton": true,
   "config.workbench.editor.showIcons": true,
   "config.workbench.editor.enablePreview": true,
   "config.workbench.editor.enablePreviewFromQuickOpen": true,
   "config.workbench.quickOpen.closeOnFocusLost": true,
   "config.workbench.settings.openDefaultSettings": false,
   "config.workbench.statusBar.visible": true,
   "config.workbench.activityBar.visible": true,
   "config.window.openFilesInNewWindow": true,
   "config.window.restoreFullscreen": false,
   "config.window.fullScreenZenMode": false,
   "config.window.showFullPath": false,
   "config.emmet.triggerExpansionOnTab": true,
   "config.extensions.autoUpdate": true,
   "config.css.validate": true,
   "config.scss.validate": true,
   "config.less.validate": true,
   "config.html.format.enable": true,
   "config.html.format.indentInnerHtml": false,
   "config.html.format.preserveNewLines": true,
   "config.html.format.indentHandlebars": false,
   "config.html.format.endWithNewline": false,
   "config.html.suggest.angular1": true,
   "config.html.suggest.ionic": true,
   "config.html.suggest.html5": true,
   "config.json.format.enable": true,
   "config.php.validate.enable": true,
   "config.typescript.disableAutomaticTypeAcquisition": false,
   "config.typescript.check.workspaceVersion": false,
   "config.typescript.check.tscVersion": false,
   "config.typescript.useCodeSnippetsOnMethodSuggest": false,
   "config.typescript.validate.enable": true,
   "config.typescript.format.enable": true,
   "config.typescript.format.insertSpaceAfterCommaDelimiter": true,
   "config.typescript.format.insertSpaceAfterSemicolonInForStatements": true,
   "config.typescript.format.insertSpaceBeforeAndAfterBinaryOperators": true,
   "config.typescript.format.insertSpaceAfterKeywordsInControlFlowStatements": true,
   "config.typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
   "config.typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
   "config.typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
   "config.typescript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
   "config.typescript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
   "config.typescript.format.placeOpenBraceOnNewLineForFunctions": false,
   "config.typescript.format.placeOpenBraceOnNewLineForControlBlocks": false,
   "config.javascript.validate.enable": true,
   "config.javascript.format.enable": true,
   "config.javascript.format.insertSpaceAfterCommaDelimiter": true,
   "config.javascript.format.insertSpaceAfterSemicolonInForStatements": true,
   "config.javascript.format.insertSpaceBeforeAndAfterBinaryOperators": true,
   "config.javascript.format.insertSpaceAfterKeywordsInControlFlowStatements": true,
   "config.javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
   "config.javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
   "config.javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
   "config.javascript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
   "config.javascript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
   "config.javascript.format.placeOpenBraceOnNewLineForFunctions": false,
   "config.javascript.format.placeOpenBraceOnNewLineForControlBlocks": false,
   "config.dart.debugSdkLibraries": false,
   "config.dart.debugExternalLibraries": false,
   "config.dart.setIndentation": true,
   "config.dart.insertArgumentPlaceholders": true,
   "config.dart.showTodos": true,
   "config.dart.reportAnalyzerErrors": true,
   "config.dart.allowAnalytics": true,
   "config.dart.checkForSdkUpdates": true,
   "config.dart.runPubGetOnPubspecChanges": true,
   "config.python.linting.enabled": true,
   "config.python.linting.prospectorEnabled": false,
   "config.python.linting.pylintEnabled": true,
   "config.python.linting.pep8Enabled": false,
   "config.python.linting.flake8Enabled": false,
   "config.python.linting.pydocstyleEnabled": false,
   "config.python.linting.mypyEnabled": false,
   "config.python.linting.lintOnTextChange": true,
   "config.python.linting.lintOnSave": true,
   "config.python.linting.pylamaEnabled": false,
   "config.python.formatting.formatOnSave": false,
   "config.python.autoComplete.addBrackets": false,
   "config.python.workspaceSymbols.enabled": true,
   "config.python.workspaceSymbols.rebuildOnStart": true,
   "config.python.workspaceSymbols.rebuildOnFileSave": true,
   "config.python.unitTest.promptToConfigure": true,
   "config.python.unitTest.nosetestsEnabled": false,
   "config.python.unitTest.pyTestEnabled": false,
   "config.python.unitTest.unittestEnabled": false,
   "config.python.terminal.executeInFileDir": false,
   "config.python.jupyter.appendResults": true,
   "config.tslint.enable": true,
   "config.tslint.validateWithDefaultConfig": false,
   "config.tslint.ignoreDefinitionFiles": true,
   "config.tslint.autoFixOnSave": false,
   "config.gutterpreview.showimagepreviewongutter": true,
   "config.go.buildOnSave": true,
   "config.go.lintOnSave": true,
   "config.go.vetOnSave": true,
   "config.go.useDiffForFormatting": true,
   "config.go.useCodeSnippetsOnFunctionSuggest": false,
   "config.go.formatOnSave": true,
   "config.go.coverOnSave": false,
   "config.go.gocodeAutoBuild": true,
   "config.go.autocompleteUnimportedPackages": true,
   "config.csharp.suppressDotnetInstallWarning": false,
   "config.csharp.suppressDotnetRestoreNotification": false,
   "config.omnisharp.useMono": false,
   "config.omnisharp.autoStart": true,
   "config.launch.configurations.0.stopOnEntry": false,
   "config.launch.configurations.0.sourceMaps": true,
   "config.launch.configurations.1.stopOnEntry": true,
   "config.launch.configurations.2.sourceMaps": true,
   "config.launch.configurations.3.sourceMaps": true,
   "config.launch.configurations.4.sourceMaps": true,
   "config.launch.configurations.5.sourceMaps": true,
   "config.launch.configurations.6.sourceMaps": true,
   "config.launch.configurations.7.sourceMaps": true,
   "config.launch.configurations.8.sourceMaps": true,
   "config.tasks.isShellCommand": true,
   "config.tasks.tasks.0.isBuildCommand": true,
   "config.tasks.tasks.0.isWatching": true,
   "config.tasks.tasks.2.isTestCommand": true,
   "resource": {
      "scheme": "file",
      "authority": "",
      "path": "/Users/jrieken/Code/vscode/src/vs/editor/contrib/codelens/browser/codelens.ts",
      "fsPath": "/Users/jrieken/Code/vscode/src/vs/editor/contrib/codelens/browser/codelens.ts",
      "query": "",
      "fragment": "",
      "external": "file:///Users/jrieken/Code/vscode/src/vs/editor/contrib/codelens/browser/codelens.ts",
      "$mid": 1
   },
   "resourceScheme": "file",
   "resourceFilename": "codelens.ts",
   "resourceLangId": "typescript",
   "textCompareEditorVisible": false,
   "editorId": "vs.editor.ICodeEditor:1",
   "editorFocus": true,
   "editorTextFocus": true,
   "editorTabMovesFocus": false,
   "editorReadonly": false,
   "editorHasMultipleSelections": false,
   "editorHasSelection": false,
   "findWidgetVisible": false,
   "findInputFocussed": false,
   "markersNavigationVisible": false,
   "parameterHintsVisible": false,
   "parameterHintsMultipleSignatures": false,
   "renameInputVisible": false,
   "acceptSuggestionOnEnter": true,
   "suggestWidgetVisible": false,
   "suggestWidgetMultipleSuggestions": false,
   "suggestionSupportsAcceptOnKey": false,
   "accessibilityHelpWidgetVisible": false,
   "referenceSearchVisible": false,
   "breakpointWidgetVisible": false,
   "inSnippetMode": false,
   "hasSnippetCompletions": false,
   "editorLangId": "typescript",
   "editorHasCompletionItemProvider": true,
   "editorHasCodeActionsProvider": true,
   "editorHasCodeLensProvider": true,
   "editorHasDefinitionProvider": true,
   "editorHasHoverProvider": true,
   "editorHasDocumentHighlightProvider": true,
   "editorHasDocumentSymbolProvider": true,
   "editorHasReferenceProvider": true,
   "editorHasRenameProvider": true,
   "editorHasSignatureHelpProvider": true,
   "editorHasDocumentFormattingProvider": true,
   "editorHasDocumentSelectionFormattingProvider": true
}
```

**Comment by isidorn** [comment] 2016-12-05 12:03
This can easily be reproed by not being in zen mod and pressing 'cmd + K' after that all shortcuts get ignored.

For @jrieken scenario it happens by pressing `esc` while in zen mode and then other shortcuts get ignored. This is coming from the fact that zen mode uses 'esc' as a chord to get in a mode where 'esc' exits zen mode (in the end double esc exit zen mode).

assigning also to @bpasero @sandy081  since @jrieken mentioned you were chaning how the contexts work in the workbench

**Comment by bpasero** [comment] 2016-12-05 12:19
@jrieken any chance you had settings opened with the new side by side editor showing both default settings and settings.json?

**Comment by bpasero** [comment] 2016-12-05 12:24
Here is the difference I am seeing from insiders to stable:
* start fresh with no editors open
* press Ctrl/Cmd+K
* press backspace

=> stable: you see a message that chord is invalid
=> insiders: the chord is not quit and you stay in chord mode

Given that there is no editor involved in this setup, I am not sure this could be caused by any change from either me or @sandy081 (preferences editor et. al).

@alexandrudima any clues?

**Comment by bpasero** [comment] 2016-12-05 14:26
This is caused by https://github.com/Microsoft/vscode/commit/77df19537b7ba79f7f05a9efa86481f9abcd42ae

@Tyriar moving to you

**Comment by Tyriar** [comment] 2016-12-05 15:37
Looking into this first thing today.

**Comment by Tyriar** [comment] 2016-12-05 18:11
I pushed this in due to the critical nature, reopening and assigning to @alexandrudima for a review. The issue was that we didn't continue on with the `resolve` return value even if it was resolved to `null`. Previously it's only ignored when it's the modifier case.

**Comment by alexandrudima** [comment] 2016-12-06 08:08
LGTM

**Closed by alexandrudima** 2016-12-06 08:08 UTC
Labels: bug, important

**Comment by jrieken** [comment] 2016-12-08 10:56
verified with the step from https://github.com/Microsoft/vscode/issues/16498#issuecomment-264837631
