### ISSUE TITLE
Leading or trailing spaces detected but not handled

### ISSUE THREAD

**Issue by RusimbiP** [microsoft/vscode#108180] opened 2020-10-06 13:14 UTC
- VSCode Version: 1.49.3
- OS Version: Ubuntu 20.4

Steps to Reproduce:

1. Open vscode and create a file with trailing or leading spaces. Or both of them.
2.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by RusimbiP** [comment] 2020-10-06 13:15
![Screenshot from 2020-10-06 15-08-57](https://user-images.githubusercontent.com/54870069/95206277-cb52b600-07e6-11eb-94a0-e8db42561027.png)

**Comment by RusimbiP** [comment] 2020-10-06 13:22
This is a problem when you can't find the file during import only to realize(after a certain amount of time) that you added on space at the file while creating it. Thank you!

**Comment by IllusionMH** [comment] 2020-10-06 15:14
Not sure what do you mean by "handled"? Stripping them?

If spaces allowed by system you'll see warning, VS Code shouldn't prevent users from creating these files if they are allowed by system.
![image](https://user-images.githubusercontent.com/1312662/95219919-95b9c700-07fe-11eb-9d00-0b25cfc2216b.png)

Not stripping them is intentional see #12013 and #50631

**Comment by JacksonKearl** [comment] 2020-10-06 17:05
Closing as a duplicate of the issues @IllusionMH cited.

**Closed by JacksonKearl** 2020-10-06 17:05 UTC
Labels: new release
