### ISSUE TITLE
How To intellisense code of file by user writed.

### ISSUE THREAD

**Issue by NathanLi** [Microsoft/vscode#25056] opened 2017-04-20 04:01 UTC
- VSCode Version: 1.11.2
- OS Version: macOS Sierra

VSCode can intellisense code by typings. But how to intellisense code in workspace?

**Comment by mjbvz** [comment] 2017-04-20 21:14
This issue is unclear to me. Please provide additional information such as:

* What is going wrong
* What is the expected behavior
* What are the steps to reproduce the issue

**Comment by NathanLi** [comment] 2017-04-21 09:33
I'm developing js app.  The intellisense of vscode is great. 
But it's not prompt the variable name of another file at same fold.
Just like behavior in Atom.

**Comment by mjbvz** [comment] 2017-04-24 18:31
Please provides a code example and a description of what is not working as expected

**Comment by mjbvz** [comment] 2017-05-01 19:53
Closing as the issue is not clear / too broad.

@NathanLi Please open new issues to track any specific errors or limitations you notice for JS intellisense

**Closed by mjbvz** 2017-05-01 19:53 UTC
Labels: needs more info
