### ISSUE TITLE
User snippets don't work inside JSX template

### ISSUE THREAD

**Issue by trongthanh** [Microsoft/vscode#20664] opened 2017-02-15 15:38 UTC
- VSCode Version: 1.9.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. I created following snippet to quickly generate a component tag in JSX template (in the language JavaScript and JavaScript React )

```json
{
    "FormattedMessage": {
        "prefix": "fmsg",
        "body": [
            "<FormattedMessage id=\"${1:message-id}\"",
            "	tagName=\"${2:span}\"",
            "	defaultMessage=\"${3}\"",
            "	values={{",
            "		${0}",
            "	}}",
            "/>"
        ],
        "description": "react-intl <FormattedMessage>"
    },
}
```

2. In a React .js file, if I place my caret inside other JSX tags and type `fmsg` and tab, it automatically complete as `<fmsg></fmsg>`.
  If I place my caret NOT inside any JSX tags, the prefix `fmsg` completes to full snippet body as expected.

I also tried to add that snippet in language files HTML and XML, but it still doesn't complete in JSX templates.

**Comment by mjbvz** [comment] 2017-02-15 21:44
@jrieken, @alexandrudima, @aeschli This looks like #19954. What was the outcome of that discussion for snippets in general inside of jsx/tsx?

**Comment by jrieken** [comment] 2017-02-16 07:44
I cannot reproduce. Typing `fmsg` and hitting Tab expands the snippet for me. Are you running with a special emmet configuration? What does IntelliSense show when hit Cmd+Space instead of Tab after `fmsg`?

![feb-16-2017 08-43-09](https://cloud.githubusercontent.com/assets/1794099/23011946/feb895da-f423-11e6-8bf2-51063294b746.gif)

**Comment by trongthanh** [comment] 2017-02-16 11:21
Hi,

I just reset VSCode to default (deleted `~/.vscode` and `/Users/thanh/Library/Application\ Support/Code`) and try the snippet and it still won't work inside JSX template. See attached screen record.

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/234226/23019153/7eb16826-f473-11e6-81ba-3a9e073e57a8.gif)

When entering **Ctrl+Space** (you meant this, NOT Cmd+Space, right?), it show no suggestions (shown in the screen record as well)

BTW, my colleague who uses VSCode on Linux also experiences the same issue.

**Comment by trongthanh** [comment] 2017-02-16 11:42
Just found out a **workaround**.

I turned this on: 

```js
{
   // Insert snippets when their prefix matches. Works best when 'quickSuggestions' aren't enabled.
  "editor.tabCompletion": true
}
```

And it works when I just hit TAB. 
However, this is not obvious since the above option is off by default.

**Comment by jrieken** [comment] 2017-02-16 13:57
Yeah, that the unhappy conflict about the tab key. The problem is that emmet, IntelliSense, and Tab Completion both fight over that key. Especially when `quickSuggestion` are enabled (default, IntelliSense as you type) the tab key is bound to inserting the suggestion. That is the reason we have tab completion disabled by default.

**Comment by jrieken** [comment] 2017-02-16 13:59
Closing this as designed because we have decided to have give IntelliSense a higher priority then tab completion. Mostly for historical reasons as tab completion came in pretty late.

**Closed by jrieken** 2017-02-16 13:59 UTC
Labels: javascript, needs more info, snippets
