### ISSUE TITLE
Undo/Redo not working in search bar.

### ISSUE THREAD

**Issue by m-garg** [Microsoft/vscode#10126] opened 2016-08-04 13:57 UTC
- VSCode Version: 1.3.1 (1.3.1)
- OS Version: OS X El Capitan (10.11.4)

Steps to Reproduce:

- In any opened file, press Cmd + f.
- Type something.
- Cmd + z to undo what you typed last in the search bar.
- "Undo" action applied on the opened file instead of search input field.

When in focus, undo-redo should work in search bar, as copy-paste do.

**Comment by aeschli** [comment] 2016-08-04 18:41
That works on Linux/Ubuntu, but not on OSX.

**Comment by alexandrudima** [comment] 2016-08-05 08:27
Most likely it is the menu stealing the keybinding

**Comment by FabianLauer** [comment] 2016-08-11 17:06
Isn't this a dupe of #151?

**Comment by alexandrudima** [comment] 2016-08-12 07:34
Yes, let's track in #151

**Closed by alexandrudima** 2016-08-12 07:34 UTC
Labels: bug, mac
