### ISSUE TITLE
Undo after save on JSON files navigates to end of file

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#71432] opened 2019-03-29 03:08 UTC
Issue Type: <b>Bug</b>

Does not happen in stable. Still repros if all extensions are disabled.

1) Open a JSON file
2) Make any change
3) Save
4) Undo
!) cursor navigates to the bottom of the file, gets extremely annoying

![weird undo](https://user-images.githubusercontent.com/6913354/55206848-2db00c80-5195-11e9-826e-332efc9c723f.gif)

VS Code version: Code - Insiders 1.33.0-insider (f5044f0910e4aa7e7e06cb509781f3d56e729959, 2019-03-28T16:20:44.233Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43
vscode-antlr4|mik|2.1.1
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.0
azure-account|ms-|0.8.0
csharp|ms-|1.18.0
vscode-typescript-tslint-plugin|ms-|1.0.0
azurerm-vscode-tools|msa|0.5.0
vscode-docker|Pet|0.6.1

</details>

**Comment by alexandrudima** [comment] 2019-04-01 06:50
@StephenWeatherford Can you please share your settings? I cannot reproduce:

![Kapture 2019-04-01 at 8 49 51](https://user-images.githubusercontent.com/5047891/55308474-2883e380-545b-11e9-887a-d0e1be65576c.gif)

**Comment by StephenWeatherford** [comment] 2019-04-01 22:39
Okay, so it repros only when this setting is on:
```
"editor.formatOnSave": true,
```

It also doesn't seem to repro with all editors.  Try deleting one or more characters out of any string value, then save and undo.

**Comment by alexandrudima** [comment] 2019-04-02 10:22
@StephenWeatherford Still no luck in reproducing. I'm using `"editor.formatOnSave": true` and deleting characters in a string value, then saving, then undoing:

![Kapture 2019-04-02 at 12 21 32](https://user-images.githubusercontent.com/5047891/55395462-e5e90680-5541-11e9-9611-395e6770f194.gif)

**Comment by StephenWeatherford** [comment] 2019-04-04 23:31
I still see this, stable and insiders, Mac and Windows.  What do you need from me?  It appears that there's an extra item pushed onto the undo stack that shouldn't be there.

**Comment by alexandrudima** [comment] 2019-04-09 14:16
@jrieken You mentioned something today about formatting on save not picking up the editor in some cases ?

**Comment by jrieken** [comment] 2019-04-09 14:20
@StephenWeatherford This might be https://github.com/Microsoft/vscode/issues/71707. Please try to reproduce with next (tomorrows) insiders build: https://code.visualstudio.com/insiders/

**Comment by jrieken** [comment] 2019-04-30 13:13
optimistically closing as dupe

**Closed** 2019-04-30 13:13 UTC
Labels: needs more info

**Comment by StephenWeatherford** [comment] 2019-04-30 18:10
Does seem to be fixed, thanks!
