### ISSUE TITLE
Comment Line Command Causes Syntax Errors Inside JSX Elements

### ISSUE THREAD

**Issue by cihancil** [Microsoft/vscode#22811] opened 2017-03-17 22:34 UTC
If I use "cmd+k cmd+k" to comment single line on JS code inside JSX element VS Code fails to commenting code.

Before commenting:
<img width="175" alt="screen shot 2017-03-18 at 01 28 05" src="https://cloud.githubusercontent.com/assets/9278709/24065184/f2ccb70a-0b71-11e7-86e7-13bdbff81fe5.png">

When I comment the line. It now has a syntax error 
<img width="230" alt="screen shot 2017-03-18 at 01 28 15" src="https://cloud.githubusercontent.com/assets/9278709/24065187/f62f92e6-0b71-11e7-87de-1b9e6e2939c9.png">

- VSCode Version: 1.10.2
- OS Version: macOS Sierra 10.12.2

**Comment by mjbvz** [comment] 2017-03-21 00:37
Thanks. I believe this is a duplicate of #20874, which is not specific to spread operators

**Closed by mjbvz** 2017-03-21 00:37 UTC
Labels: duplicate, javascript, languages basic, typescript
