### ISSUE TITLE
Automatically type at closing tag

### ISSUE THREAD

**Issue by sharmagtu** [microsoft/vscode#88743] opened 2020-01-16 08:49 UTC
Issue Type: <b>Bug</b>

so sometimes it types along when we write something. eg when we write in <div >and add some class in it like <div class-"anything"> it writes at the closing tag too automatically. eg </div class="anything">. I thought it was by mistake but few more people have also told me about the same error. i hope you got it what i'm trying to say.

VS Code version: Code - Insiders 1.42.0-insider (980d8ef1371b14e80162d88e88f45e15f8632070, 2020-01-14T09:07:36.433Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 3825U @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.18.0
LiveServer|rit|5.6.1

</details>

**Comment by TriMoon** [comment] 2020-01-16 10:07
@sharmagtu 
- Please re-edit your post and place the actual code(s) inside back-ticks, looks like ' but is cursive, so github will display it correctly see just above [GitHub-flavored-markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).\
eg: `<div class="blabla"></div>`

As-is now it is not clear what you mean to me and i guess same goes to other people... :wink:

**Comment by IllusionMH** [comment] 2020-01-16 11:23
/needsMoreInfo
Could you fix markup?

Also I would guess that it's duplicate of #87067

**Comment by gjsjohnmurray** [comment] 2020-01-16 11:23
@sharmagtu search for the tag [mirror-cursor](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Amirror-cursor) to see current issues relating to this [new 1.41 feature](https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor). And if none of the open issues seems to match your case please post exact repro steps so @octref can investigate.

**Closed** 2020-05-11 11:23 UTC
Labels: editor-synced-region, needs more info
