### ISSUE TITLE
When opening "WSL" files, vscode cannot remember which files were opened last time

### ISSUE THREAD

**Issue by frei-x** [microsoft/vscode#98307] opened 2020-05-21 08:27 UTC
- VSCode Version: 1.45.0(system setup)
- OS Version: windows10 19628.1

Steps to Reproduce:

1. Open '\\WSL$\Ubuntu 16.04\home\JH' and open some more files
2. Close vscode, and then open it,
It doesn't remember the last file it opened

Does this issue occur when all extensions are disabled?: Yes

When opening WSL files, vscode cannot remember which files were opened last time,
(the last opened file cannot be opened automatically)

**Comment by frei-x** [comment] 2020-05-21 11:34
save workspace. feasible

**Comment by aeschli** [comment] 2020-10-14 20:26
duplicate of https://github.com/microsoft/vscode/issues/107111

@frei-x This should be fixed in the latest, can you give it a try?

**Closed by aeschli** 2020-10-14 20:26 UTC
Labels: WSL, remote

**Comment by frei-x** [comment] 2020-10-15 12:31
> duplicate of #107111
> 
> @frei-x This should be fixed in the latest, can you give it a try?
thank you
