### ISSUE TITLE
Insiders - can't select top menu at edge of screen due to padding pixel

### ISSUE THREAD

**Issue by AshSimmonds** [microsoft/vscode#150170] opened 2022-05-23 10:31 UTC
Issue Type: <b>Bug</b> (or maybe new unwanted feature)

1 - try to select top menu with mouse at edge of screen

![top menu issue](https://i.redd.it/bc2z1k9y97191.gif)

This still works fine in vanilla VSCode.

VS Code version: Code - Insiders 1.68.0-insider (c0769274fa136b45799edeccc0d0a2f645b75caf, 2022-05-23T05:17:12.256Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.93GB free)|
|Process Argv|C:\\GitHub\\space-03-astro_01 --crash-reporter-id aacb8121-be3d-4361-af2e-7d658f576ba7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
astro|app|0.1.148
astro-vscode|ast|0.19.0
vscode-tailwindcss|bra|0.8.4
npm-intellisense|chr|1.4.1
vscode-markdownlint|Dav|0.47.0
dendron|den|0.95.1
dendron-markdown-shortcuts|den|0.12.1
dendron-paste-image|den|1.1.0
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.25
gitpod-desktop|git|0.0.34
customize-ui|ioc|0.1.61
monkey-patch|ioc|0.1.16
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
vscode-yaml|red|1.7.0
svelte-vscode|sve|105.16.1
tailwind-snippets|Zar|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvsnew555:30438690
vscscmwlcmt:30465136
cppdebug:30492333
vsclangdf:30492506

```

</details>

**Comment by daviddossett** [comment] 2022-05-23 14:57
I wouldn't consider this a bug, but it's on my list to explore how to make the full vertical height o the titlebar count as the hit area for the button now that we have this new styling.

**Comment by AshSimmonds** [comment] 2022-05-23 15:02
Yeah I don't consider it a bug, more an introduced stylistic choice which
represents poor UX.

**Comment by daviddossett** [comment] 2022-05-23 15:18
Here's a roughly similar experience on GH. This is basically what I'll be attempting to do:

![CleanShot 2022-05-23 at 08 17 26](https://user-images.githubusercontent.com/25163139/169852177-43c538f0-27d7-440f-a476-7e91ce9d0f23.gif)

**Comment by hsupu** [comment] 2022-06-11 03:57
The bug is released as 1.68.0, without any config to revert..

**Comment by daviddossett** [comment] 2022-06-12 23:00
This is being addressed in #150250.

**Comment by infinnie** [comment] 2022-06-27 03:59
Seems that this isn’t yet solved in 1.69.0 Insiders. I still could replicate the problem.

**Comment by daviddossett** [comment] 2022-06-27 17:47
Looks to have regressed somehow. Will take a look.

**Closed** 2022-06-27 18:21 UTC

**Comment by daviddossett** [comment] 2022-06-28 16:51
@sbatten is that possible?

**Comment by sbatten** [comment] 2022-06-28 17:23
@daviddossett yes very possible, that would align with notepad in terms of presentation, but also means the menu can appear directly under your mouse click given the larger hit box. I can make this change today if its preferred.

**Comment by daviddossett** [comment] 2022-06-28 17:36
The top and bottom margin in the menu probably eliminates most if not all of that problem, right? Would be great to try on a branch if it's a quick change.

<img width="357" alt="CleanShot 2022-06-28 at 10 35 35@2x" src="https://user-images.githubusercontent.com/25163139/176246883-0f99f32c-0c4f-4a0f-9038-4023fd672d9f.png">

**Comment by a1291762** [comment] 2022-07-15 02:42
FWIW: This is working for me in 1.69.1 which is the stable version apparently released 2 days ago.
Ubuntu using code from snap, stable channel.
The "highlight" does not extend to the top of the maximised window, but the click target does.
![image](https://user-images.githubusercontent.com/327162/179136423-a20bf7a2-7484-463f-ba15-fd0ba832fe0e.png)

**Comment by infinnie** [comment] 2022-07-15 03:44
> FWIW: This is working for me in 1.69.1 which is the stable version apparently released 2 days ago. Ubuntu using code from snap, stable channel. The "highlight" does not extend to the top of the maximised window, but the click target does. ![image](https://user-images.githubusercontent.com/327162/179136423-a20bf7a2-7484-463f-ba15-fd0ba832fe0e.png)

This is the intended behavior.
