### ISSUE TITLE
Regression: pressing enter at the end of a commented creates a new _commented_ line

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#233186] opened 2024-11-06 11:43 UTC
Repro: 

1. Write a commented line 
2. Go the end of that commented line and press enter to create a new line 
3. :bug: See that new line is commented (but in stable, the newly created line is not commented)

**Comment by aiday-mar** [comment] 2024-11-06 15:21
Hi thanks for filing this issue. Yes so this is as a result of a change that was merged yesterday which was to add a line comment on the next line when pressing Enter from inside of a line comment. I think this should be disabled when we press Enter at the end of a line comment however. I will fix this.

**Comment by ulugbekna** [comment] 2024-11-06 16:19
@aiday-mar extra data: I think a comment should also _not_ be inserted when the new line is created using the command `editor.action.insertLineAfter` -- eg vim has a keybinding to create a newline and currently it creates a newline with `// ` at the beginning of the line regardless where my cursor is (and this's an important keybinding in vim)

**Comment by aiday-mar** [comment] 2024-11-06 16:36
I see, I am currently not able to reproduce this behavior. I tested with VS Code Neovim where the keybinding is `o` in vim mode, and pressing it does not seem to add line comment at the beginning of the next line even when the cursor is inside of a line comment.

**Closed** 2024-11-06 16:45 UTC
Labels: bug, editor-autoindent
