### ISSUE TITLE
DiffEditorWidget.setModel: Original model is null.

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1983] opened 2016-01-13 12:02 UTC
Do some changes, open some files, try to view the changes in the diff view. Only started happening today (vscode cf459844188555d540353402b6849c2d91c05289). I occassionaly get the following:

![screen shot 2016-01-13 at 13 01 44](https://cloud.githubusercontent.com/assets/1926584/12293739/d3186c52-b9f5-11e5-9ab2-a1d838cae5d9.png)

**Comment by joaomoreno** [comment] 2016-01-13 14:12
Duplicate of #1986

**Closed by joaomoreno** 2016-01-13 14:12 UTC
Labels: bug, git, important
