### ISSUE TITLE
Show unverified function breakpoints in debug viewlet

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3388] opened 2016-02-24 08:46 UTC
Testing #2832

I have a breakpoint on `if (_key === key) {` and I've added a function breakpoint for `console.log`. The breakpoint for `if (_key === key) {` is hit, but the console.log near the end is not hit.

I tried clicking `Reapply all breakpoints` which did not help in this case.

``` javascript
function Safe(_key) {
    var _locked = true;
    var _value = null;

    this.unlock = function(key) {
        if (_key === key) {
            _locked = false;
        }
        return;
    };

    this.lock = function() {
        _locked = true;
    };

    Object.defineProperty(this, 'value', {
        get: function() {
            if (_locked) {
                console.log('thief detected!');
                process.exit(0);
            }
            return _value;
        },

        set: function(value) {
            if (_locked) {
                console.log('thief detected!');
                process.exit(0);
            }
            _value = value;
        }
    });
}

var safe = new Safe('mySecretPassword');

safe.unlock('mySecretPassword');
safe.value = 3;
console.log(safe.value);
safe.lock();


```

**Comment by weinand** [comment] 2016-02-24 09:00
@alexandrudima console.log is not a global function, so it is not supported by node. Global functions are something like "setTimeout" or this:

```
// global function
foo = function(n) {
	return n;
}
```
The problem is, that the debugger UI does not seem to show errors for function breakpoint.

**Comment by alexandrudima** [comment] 2016-02-24 09:03
ok, sorry my bad, would be nice to get a warning or something

**Comment by weinand** [comment] 2016-02-24 09:22
@alexandrudima I just debugged this and the problem with "console.log" is that it is a native function. The debug adapter returns this error nicely, but it is not shown in the UI:

![2016-02-24 10-19-32](https://cloud.githubusercontent.com/assets/1898161/13280806/666c586e-dae0-11e5-9b1d-1db82f94ebb3.png)

**Comment by alexandrudima** [comment] 2016-02-24 09:25
But now, with the previous comment, I am confused. So I can set a function breakpoint for `setTimeout` (which is a native function), but not for `console.log` which is also a native function? I would expect in case of native functions the program to stop at the call site.

**Comment by weinand** [comment] 2016-02-24 09:38
@alexandrudima setTimeout is not a a native function:

![2016-02-24 10-30-42](https://cloud.githubusercontent.com/assets/1898161/13281042/c0a67692-dae1-11e5-92f8-260e5a1ef2d4.png)

It lives in timers.js.

Node behaves like this (even if this does not match our expectation).
Node's function breakpoints are weak, but since we have no other debug adapter that implements that part of the protocol, we can only test it with node-debug.

**Comment by alexandrudima** [comment] 2016-02-24 10:27
oh, ok, sorry my bad again.

**Comment by isidorn** [comment] 2016-03-07 10:30
Assigning to @bgashler1 so he can work on some initial designs for this

**Comment by bgashler1** [comment] 2016-03-10 00:54
Here are some options.  Please let me know your thoughts.

I also took a stab at making it more intuitive to **deactivate all breakpoints** and to visually make it more clear how that's different from **enable** or **disable** breakpoints.

## 1) Icon for breakpoint type; keep current UX
A) Show all breakpoints
![01 show all](https://cloud.githubusercontent.com/assets/11839736/13655642/ba4e0bb8-e615-11e5-917c-57bd3879b351.png)

B) show only non-standard breakpoints
![show-only-non-standard-breakpoints](https://cloud.githubusercontent.com/assets/11839736/13655749/af50a436-e616-11e5-8aa4-18e80e56a5f2.png)


## 2) Same as 1, but more intuitive to deactivate all breakpoints
![03 hierarchy-uncheck-02](https://cloud.githubusercontent.com/assets/11839736/13655675/04d5a060-e616-11e5-9751-a9bcd07dd5f6.gif)

## 3) 
![04 divide-breakpoints-and-add-toggle](https://cloud.githubusercontent.com/assets/11839736/13655718/62894342-e616-11e5-9029-a8268d5597b8.gif)

**Comment by isidorn** [comment] 2016-03-10 09:16
@bgashler1  Great work! For 3) we already have a visual toggle to deactivate, the only new thing here is the seperator for brakpoints - exception breakpoints and that you put breakpoitns on top. Right?

I personally like 1A the best and would like to try it out. The only thing that worries me is that all that red might draw the unnecessery attention of a user. Maybe we show this decorations only when a debug session is active - otherwise not show anything (same as we do now).

2) Not a big fan of this idea

3) Like it

@weinand @bpasero opinions?

**Comment by bpasero** [comment] 2016-03-10 10:47
Cool stuff. I think it would be nice to visually separate exception breakpoints from the rest! I also think if we chose to show the breakpoint logo we should do it for all breakpoints, but I would have to see it in action to tell for sure. I also wonder if the checkbox should come first and then the icon?

**Closed** 2018-02-15 15:03 UTC
Labels: debug, feature-request, ux

**Comment by isidorn** [comment] 2018-02-15 15:09
We now show the state of breakpoins via icons in the viewlet.
I have opened an additional item for the function breakpoint icon https://github.com/Microsoft/vscode/issues/43763

![screen shot 2018-02-15 at 16 02 14](https://user-images.githubusercontent.com/1926584/36263116-b15a2c9e-1269-11e8-917f-c5d3502f4728.png)
