### ISSUE TITLE
Source hIghlight in javascript is broken while parsing regex with double quotes

### ISSUE THREAD

**Issue by mykola-mokhnach** [microsoft/vscode#90864] opened 2020-02-18 07:49 UTC
- VSCode Version: 1.42.1
- OS Version: Mac OS 10.15.3

Steps to Reproduce:

1. Load appium-adb npm module into vscode from https://github.com/appium/appium-adb
2. Open the file https://github.com/appium/appium-adb/blob/master/lib/tools/adb-commands.js in the edtor
3. Scroll to the line https://github.com/appium/appium-adb/blob/68a62e860990b1cae7a768be415378de115f6841/lib/tools/adb-commands.js#L1901
: 
```
  if (!/\bresult=-1\b/.test(output) || !/\bdata="{/.test(output)) {
    log.debug(output);
    throw new Error('Cannot retrieve SMS list from the device. ' +
      'Check the server log for more details');
  }
```

<img width="548" alt="regex" src="https://user-images.githubusercontent.com/7767781/74714793-94199f80-522b-11ea-8a7a-63869e18153e.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2020-02-18 10:10
The problem actually starts before the double quotes. The first regex in the if statement is scoped incorrectly too. It's the `!/` that's causing problems.

**Comment by alexr00** [comment] 2020-02-18 10:11
Looks like you're not the only one to find this @mykola-mokhnach. Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed** 2020-02-18 10:12 UTC
Labels: *duplicate
