### ISSUE TITLE
api to detect installed NotebookOutputRenderer

### ISSUE THREAD

**Issue by AnWeber** [microsoft/vscode#123884] opened 2021-05-14 12:06 UTC
Is there an Api planned for detecting NotebookOutputRenderer installed in vscode? 

I would have the following requirements for this interface:

* Determine if a specific mime(type) is supported of a NotebookOutputRenderer. It should be noted that the mimeType does not necessarily have to correspond to the mime of the NotebookOutputRenderer. Currently, the display of only one renderer per mimetype is supported and extensions therefore fall back to custom mimetype (x+application/rest-book).  
* Checking in which way the content of the mimetype has to be passed. As possible types I would suggest string, UInt8Array and an object with {apiName, version}.
	For example, for the NotebookOutputRenderer of 'application/json' an object is expected instead of a string. For the NotebookOutputRenderer of 'image/png' a Base64 string is expected instead of a Buffer/UInt8Array.

Use case is the sending of Rest/Http calls in the Notebook interface like extensions [rest-book](https://marketplace.visualstudio.com/items?itemName=tanhakabir.rest-book) or [httpbook](https://marketplace.visualstudio.com/items?itemName=anweber.httpbook) are supporting. The response should then be rendered in a NotebookCellOutput with a NotebookOutputRenderer determined by Content-type of the response. Since arbitrary responses are possible, it would be desirable to dynamically determine valid NotebookOutputRenderer mimes or fallback to a default NotebookOutputRenderer. 

The use case can also be solved by means of an own extension api (like [httpbook](https://github.com/AnWeber/httpbook/blob/main/src/extension/extensionApi.ts#L89)), but for this each NotebookOutputRenderer must be explicitly connected to the NotebookController (some glue code is necessary)

**Comment by RandomFractals** [comment] 2021-05-17 04:41
I briefly discussed this with @tanhakabir when we were exploring ideas to add a rich [DataGridView](https://github.com/tanhakabir/rest-book/issues/88) and [MapView](https://github.com/tanhakabir/rest-book/issues/89) output renderers for tabular data files and different geo data formats.

I believe what's missing is the UI to set the default output renderer based on the cell output mime type, so we can install many data grid and map renderers for geo data, and have our preferences set which renderer we'd like to use as default.

**Comment by AnWeber** [comment] 2021-05-17 06:06
@RandomFractals thanks for the hint to iterate all package.json, Unfortunately, this option is not generally implementable. The information which transfer format is expected is missing. In addition, I lack the possibility to recognize whether the connection is desired/ allowed by the creator of the NotebookOutputRenderer (license).

**Comment by RandomFractals** [comment] 2021-05-17 10:53
@AnWeber I am not sure what you mean by that last (license) part. If an extension that provides custom output renderer is published and installed, by design it will be used for cell output display. Extension authors can add their license when they publish. Sounds like a whole different topic. Plus all vscode extensions are free at the moment. Extension devs can add additional licensing terms, UI and rendering restrictions if they would like to monetize them.

Maybe I cobbled too much in my followup. I just thought that you brought up a good point that we actually discussed with Tanha, and hopefully the other pieces I shared provide more context, and describe what I see missing in support of custom renderers and current built-in vscode notebooks UX.

**Comment by jrieken** [comment] 2021-05-18 11:55
> @RandomFractals thanks for the hint to iterate all package.json, Unfortunately, this option is not generally implementable. The information which value format (string, UInt8Array, custom) is missing. 

This is an interesting challenge. Today, we also don't know what format a renderer expects and kinda assume that it accepts all formats as long as the mime type matches. Having said that, we do want to reduce the amount of possible types to `string` and `Unit8Array` (see https://github.com/microsoft/vscode/issues/120063#issuecomment-839802617) and maybe we should be more strict and only allow bytes...

**Comment by RandomFractals** [comment] 2021-05-18 12:31
@jrieken I think it would be best to support both `string` and `UInt8Array` for text and binary data formats. Otherwise, we'd have to transform xml, csv, and other text formats to bytes just to load them and conver back to strings. `UInt8Array` is perfect for images that are not svg, arrow data, etc. IMO

**Comment by jrieken** [comment] 2021-05-18 13:20
> @jrieken I think it would be best to support both string and UInt8Array for text and binary data formats. Otherwise, we'd have to transform xml, csv, and other text formats to bytes just to load them and convert back to strings. UInt8Array is perfect for images that are not svg, arrow, excel data, etc. IMO

I tend to agree but the lines are very blurry. Today, images are often transported as text, e.g `data:image/png;base64,<....>` and plain text can easily be transported as bytes. I guess it is mostly driven by how you receive the data. 

I do agree that we should avoid unnecessary data conversions like `string` to `bytes` and back to `string`. However, this yields a slippery slope into supporting JSON-objects which go `{...}` to `string` (via JSON.stringify) and back to `{...}` (via JSON.parse). At the lowest level we are sending bytes, primitive types like `string` are transformed to bytes, and objects are stringified and the resulting string is transformed to bytes.

I think the bottom line is that a renderer must support all possible representations (Unit8Array, string, (maybe) object) and do the conversion by itself. There is currently no way to say "I renderer SVG but only when presented as Unit8Array". A renderer is expected to figure this out and that makes me think that the Unit8Array is the simplest API

**Comment by RandomFractals** [comment] 2021-05-18 13:31
as the least common denominator, yes. 

I would still prefer to have both and figure out the rest from mime type and value type I get to avoid bytes <-> string conversion steps. I think it would be best if we look at common mitme types and see kind of document/output they produce: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

There is a clear binary and text general document types there. Just saying would make my job easier for the custom rich renderers I am looking to build when you go GA, and also based on my experience with data preview and geo data viewer extensions that support a variety of tabular and geo data formats, both binary and text.

**Comment by jrieken** [comment] 2021-05-18 13:37
>  I think it would be best if we look at the common mime types and see kind of document/output they produce: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

Would that mean `text/<XYZ>` mime types must use `string` and others must use `Unit8Array` or can renderers & extensions still decide? Should we care and do some kind of validation or should we just pass through the data as-is?

**Comment by RandomFractals** [comment] 2021-05-18 13:41
I would say at the least pass the cell output as is for the renderer to look up the mime type it supports and figure it out. I think main goal should be to avoid unnecessary data conversions first, and then do validations if you'd like for the common mime types.

**Comment by jrieken** [comment] 2021-05-18 13:53
Currently, we are done when we have selected a renderer. We expect it to render something and now we need to make renderer-authors aware of the different data formats. For instance, I have a regular [expression renderer](https://github.com/jrieken/vscode-regex-notebook/blob/master/src/regexper/main.js#L23-L24) and that I have only ever executed and tested with `string`. It's written with the assumption of the output value being `string` but any other extension can create valid output items that look like this: `{ mime: 'application/x.regexp', value: Buffer.from("Hello+") }`

**Comment by RandomFractals** [comment] 2021-05-18 14:05
then it's up to your renderer to decide how you want to handle it.

Even better example:

I am starting to work on https://github.com/RandomFractals/vscode-leaflet extension and output render this week.

That extension and output renderer will render maps with leaflet for `geojson` and `topojson` to begin with.

Renderers will have to do some validation of their input values. In ext. case, I will have to run checks if what I get even has the geometry collection for me to render.

I hope that helps.

**Comment by jrieken** [comment] 2021-05-18 14:22
> then it's up to your renderer to decide how you want to handle it.

I do agree but I wonder how to make the API more fail-safe. How do I get you to think about the different shapes in which output can be presented to you? Maybe it happens when making the `value`-property more strict, e.g. once `NotebookCellOutputItem#value` isn't `any` or `unknown` anymore it might not be a problem anymore

**Comment by connor4312** [comment] 2021-05-18 15:52
I don't think that an API to know which renderers are installed is the right way to approach this. Renderers are extensible, and a user could install a 3rd party renderer that your extension knows nothing about.

Some other ideas:

- We say `NotebookCellOutputItem#value` always needs to be a string and optimize transfer, by gzipping for example--a gzipped 1KB base64 string  is only 3% larger than the original byte length
- In the output we type the data like `Uint8Array | string` to force consumers to renderers with it

**Comment by RandomFractals** [comment] 2021-05-18 16:21
well, we still need that Renderer picker. see above.

**Comment by AnWeber** [comment] 2021-05-18 19:52
> well, we still need that Set Default Renderer for mime type picker

I agree. But I would also like to be able to simply change this at any time. That's why I would always show all of them, but use the default for the initial display.

> Maybe it happens when making the `value`-property more strict

I would prefer a more strict api. At the moment it is possible to pass a buffer and you get a JSON object with UInt8Array in NotebookOutputRenderer, a Date is converted to an ISO String. Happy little accidents are the result. Better typing would make the api more clear. Since a conversion is already taking place, which may then be omitted, no further overhead could arise.

I see another problem with the MetaData. With these currently settings for the NotebookOutputRender can be passed. These may not be passed in another NotebookController. Maybe a additional api for the NotebookOutputRenderer would be necessary to access configuration settings.

**Comment by RandomFractals** [comment] 2021-05-18 20:24
that's the idea behind setting the default renderer per mime type. you see all installed and pick one to always use initially for that mime type. the list part is already there per my beta tests.

**Comment by AnWeber** [comment] 2021-05-23 18:48
I like the updated notebook api. 

I wonder if it makes sense that the NotebookOutputRenderers support a regex specification for the mime. In this case I could automatically provide a fallback renderer for most output formats and special renderers can intervene directly. Example would be an Http Response with application/geo+json. An extension can render this using simple JSON renderer. If a map renderer is available it should win over the fallback.

**Comment by RandomFractals** [comment] 2021-05-23 22:54
we'll test it out this week: https://github.com/RandomFractals/vscode-leaflet/issues/8

pretty sure, I'd like to set my default renderer for `application/geo+json` mime type to the new leaflet map view I'll be adding, and use the built-in `json` data response view as described here: https://github.com/tanhakabir/rest-book/issues/85#issuecomment-828896165

**Comment by RandomFractals** [comment] 2021-05-24 03:27
well, it would help if these notebook papercuts had some visuals. I'll be adding a leaflet map tomorrow, but here is a pic where I would like to be able to choose what renderer I want to use as the default based on mime type. I might actually have json and leaflet map view in mine so there is not much switching via pickers to view both ...

![leaflet-output-renderer](https://user-images.githubusercontent.com/656833/119292461-0ee31e80-bc16-11eb-9ec3-567735874a80.png)

**Comment by RandomFractals** [comment] 2021-05-24 03:52
P.S.: @jrieken and @connor4312: renderer api and code gen. template look much better now. I'll just watch you update them in other places to keep up. Thanks!

**Comment by AnWeber** [comment] 2021-05-24 19:53
@jrieken The creation of NotebookCellOutputItem is greatly simplified, but it would be helpful to provide a 3rd optional parameter metaData.

**Comment by RandomFractals** [comment] 2021-05-25 20:39
that was fast & I can see my bytes there now. Thanks @jrieken & @bpasero for tagging us on those updates. I think the renderer api looks good now for adding some rich visualizations to cell outputs with it.

**Comment by RandomFractals** [comment] 2021-05-25 21:54
potentially related for notebook renderer ext. devs to explore: https://github.com/microsoft/vscode/issues/123601

**Comment by RandomFractals** [comment] 2021-05-25 22:29
linking theming here too for other renderer ext. devs to use: https://github.com/microsoft/vscode/issues/107985

**Comment by jrieken** [comment] 2021-05-27 14:11
Closing since we have finished the conversion to bytes and removed the old API. 

Unsure if a separate issue for default renderer for mime-type (https://github.com/microsoft/vscode/issues/123884#issuecomment-843532823) already exists or not. Iff not it should be created 😄

**Closed by jrieken** 2021-05-27 14:11 UTC
