### ISSUE TITLE
Irregular whitespace in task terminal output on Windows

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#76152] opened 2019-06-26 06:18 UTC
While testing #76016 on Windows.

`task.json` used:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
			"label": "One",
			"type": "shell",
			"command": "echo 1",
			"problemMatcher": [],
			"dependsOrder": "sequence",
			"dependsOn":[
				"Two",
				"Three"
			]
		},
		{
			"label": "Two",
			"type": "shell",
			"command": "echo 2",
			"problemMatcher": []
		},
		{
			"label": "Three",
			"type": "shell",
			"command": "echo 3",
			"problemMatcher": [],
			"dependsOrder": "sequence",
			"dependsOn": [
				"Four",
				"Five"
			]
		},
		{
			"label": "Four",
			"type": "shell",
			"command": "echo 4",
			"problemMatcher": []
		},		
		{
			"label": "Five",
			"type": "shell",
			"command": "echo 5",
			"problemMatcher": []
		}
    ]
}
```

This generates the following output with irregular whitespace inbetween:

![dw2rsLO4BI](https://user-images.githubusercontent.com/4674940/60155604-ea445900-97ea-11e9-8ffb-03244f238b13.gif)

**Comment by alexr00** [comment] 2019-06-26 07:28
@kieferrm what version of Windows are you using?

**Comment by kieferrm** [comment] 2019-06-26 07:34
> `Microsoft Windows [Version 10.0.17763.107]`

**Comment by alexr00** [comment] 2019-06-26 09:08
This is the good old winpty bug. Duplicate of #57803

**Closed** 2019-06-26 09:08 UTC
Labels: *duplicate
