### ISSUE TITLE
TypeScript lenguage service taking too long and using 10GB+ memory

### ISSUE THREAD

**Issue by KinIcy** [microsoft/vscode#88778] opened 2020-01-16 15:53 UTC
Issue Type: <b>Bug</b>

1. Open a TypeScript project
2. Open a IntelliSense autocomplete (Ctrl+Space)

After the second or third time that IntelliSense is open, vscode starts to use 10GB+ ram, had to kill the process otherwise it would block my PC.

![image](https://user-images.githubusercontent.com/10891866/72540080-5b626100-384e-11ea-8d69-ba5bfa94d383.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.5.9
npm-intellisense|chr|1.3.0
scala|dal|0.0.5
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.14
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
mips|kda|0.0.5
vscode-sshfs|Kel|1.16.3
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|0.9.0
python|ms-|2020.1.58038
remote-wsl|ms-|0.41.7
cpptools|ms-|0.26.2
vscode-typescript-tslint-plugin|ms-|1.2.3
autodocstring|njp|0.4.0
vetur|oct|0.23.0
awesome-vhdl|puo|0.0.1
maude|sir|1.0.0
rewrap|stk|1.9.1
code-spell-checker|str|1.7.20

</details>

**Comment by mjbvz** [comment] 2020-01-16 19:44
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by KinIcy** [comment] 2020-01-16 20:48
I wasn't able to reproduce it on the insider's build with all extensions disabled.

**Comment by mjbvz** [comment] 2020-01-16 22:00
Thanks for checking. Duplicate of #85919 I believe

**Closed by mjbvz** 2020-01-16 22:00 UTC
Labels: needs more info
