### ISSUE TITLE
git bash terminal clears terminal on command execution

### ISSUE THREAD

**Issue by dubbha** [microsoft/vscode#88270] opened 2020-01-08 09:25 UTC
Issue Type: <b>Bug</b>

- set integrated terminal to git bash
- run any command, e.g. yarn install
- terminal gets cleared, until execution is finished, nothing visible
- after the excution input prompt is visible again, but not the execution result

Currently happening on 1.41/1.42-nightly and Windows 10.0.17763, but it's been the same for me since at least Windows 10.1809. Everything is fine on Windows 7 though.

Version: 1.42.0-insider (user setup)
Commit: cba31b819ea99836daf51cee56299348e9c6d20b
Date: 2020-01-08T05:39:25.874Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

VS Code version: Code - Insiders 1.42.0-insider (cba31b819ea99836daf51cee56299348e9c6d20b, 2020-01-08T05:39:25.874Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

![vscode_git_bash](https://user-images.githubusercontent.com/16776066/71966030-8a068900-3209-11ea-815d-999d7d751919.gif)

**Comment by connor4312** [comment] 2020-01-08 15:50
Does this happen when you run the command outside of VS Code's integrated terminal?

**Comment by dubbha** [comment] 2020-01-14 11:34
> Does this happen when you run the command outside of VS Code's integrated terminal?
Um.. Yes, it does (and it's a surprise to me). Seems to be a yarn/bash issue, not a vscode terminal.

**Comment by connor4312** [comment] 2020-01-14 15:14
Okay, thanks for checking. I'll close the issue as it doesn't seem to be caused by VS Code.

**Closed** 2020-01-14 15:14 UTC
Labels: *as-designed, integrated-terminal, needs more info
