### ISSUE TITLE
[feature request] - Ability to filter problems per root folder in a MR workspace

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode#64481] opened 2018-12-06 04:57 UTC
v1.29.1

I have analyzed the Problems bar and I'm missing some features:

1) To be able to filter by projects - (multi-project workspace - some of them might be unrelated and the list can be very long) - however, I see that I can filter by project folder
2) Filter by Warnings / Error / TODO message - for the last one I'm using a separate TODO tree plugin
If the TODO would be highlighted also, it won't be necessary to use any external plugin.
3) Problems should be arranged in a tree-like system (showing folders) - or similar what the Todo  Tree plugin is doing (switch between a flat and a hierarchical tree with a button at the top). I had 1500 warnings in my workspace and simply it was too much to read next to the errors and TODO-s, and missed the benefit of the whole Problem tab.
The tree-like system can be filterable.

I have no idea how to type in "info" in a relation of a folder or project. It's not a regex field.

Can you make a PR on these suggestion pls, as it's not that usable at the moment?

**Comment by fssrepository** [comment] 2018-12-06 12:05
@sandy81

Especially the closed bug was quite important:

v1.29.1

![image](https://user-images.githubusercontent.com/45578746/49564601-68f7a880-f924-11e8-8c98-149e8b093b4e.png)

I have a multi-root workspace and I would have liked to filter out info/error/todo for a particular project
1) I have entered **'error, **/server'** - and warnings have been shown up
2) I have entered 'info' - warnings have been shown up even if I have different TODO-s with different info icon - in combination with '**/server' is the same
3) entered 'warn' which showed me the warnings at the beginning, but also looked for text warning in my TODO info-s

![image](https://user-images.githubusercontent.com/45578746/49564771-07840980-f925-11e8-83ad-ad5d25e64df1.png)

The problem filtering is not that intuitive and I have placed some suggestion on it - #64481

I can filter out a project **'/server'**, but I cannot filter out **'/server, info'**

That's why it's raised in a different bug, as it's not a feature request.

There is a non-intuitive feature, that you can put 'info' in a filter bar. So it's showing several examples that it's not working properly, or not in an expected way.

**Comment by fssrepository** [comment] 2018-12-06 12:13
Tree explorer:

At the moment the problem is showing a flat tree - showing files independently, what I wanted to say in relation to the filter bar it would be nice if there would be a switch button, so you can view a hierarchical tree which showings the folder structure (packages) also, so you can go inside and see the java classes.

**Comment by sandy081** [comment] 2018-12-07 10:17
@fssrepository Request you mentioned in this [comment](https://github.com/Microsoft/vscode/issues/64481#issuecomment-444849805) is a duplicate of #47354. 

I see your requirement to have a tree explorer here. But you can always go to file explorer for this kind of information right? May I know what is missing in the file explorer which you need?

**Comment by fssrepository** [comment] 2018-12-14 14:48
We are talking about the Problem tab, not the file explorer, can I filter in the file explorer for "info" type of message, or "error" or "warn"?

To create a  button row on that tiny place is one solution, the second is that to make the problem's filter bar to be able to get half regex, half type, or something similar.

**Comment by sandy081** [comment] 2018-12-16 19:34
@fssrepository #47354 covers the requirement of filtering by type. 

So you want to see a tree that is similar to file explorer but showing those only have problems? This will help you grouping the files by package (for example) in case of java project?

**Comment by fssrepository** [comment] 2018-12-16 21:30
Yes, exactly, however, my initial problem was that in a multi-root workspace, I would have liked to group by project also (filter "error/warn/info" messages by project name), or some nice solution for it. So the #47354 does not cover the multi-root criteria.

**Comment by sandy081** [comment] 2019-11-08 08:29
Changed the title to reflect to what is required.

**Closed** 2020-03-16 00:51 UTC
Labels: error-list, feature-request
