### ISSUE TITLE
Running any command in terminal makes vscode sluggish for seconds

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#110903] opened 2020-11-19 02:02 UTC
- VSCode Version: 1.51.1, 1.52.0-insider
- OS Version: macOS 11.0.1

Steps to Reproduce:

1. Launch VSCode with all extensions disabled and type in strings in an empty document and everything looks normal
2. Open VSCode terminal and run any command (e.g. `vim`)
3. Type in characters continuously in the document, and a couple of seconds later there's a sluggish moment for a number of seconds.
4. Exit the vim in the terminal and type characters in the editor, the same happens.
5. Re-etner the vim and type in characters continuously in the vim editor, the same happens.

![Kapture 2020-11-19 at 09 54 44](https://user-images.githubusercontent.com/4662568/99611221-3af6ca80-2a4e-11eb-8a85-2ec152be74c9.gif)

This does not occur when I was using previous versions or latest version on Ubuntu. Looks like it is specific to macOS 11.0.1?

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2020-11-19 17:08
Duplicate of #110683

**Closed by meganrogge** 2020-11-19 17:08 UTC
