### ISSUE TITLE
editor.action.addSelectionToNextFindMatch does not work when regex is used in the find filters

### ISSUE THREAD

**Issue by Zetxus** [microsoft/vscode#186149] opened 2023-06-26 10:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: Windows 11, 10.0.22621 Build 22621

Steps to Reproduce:

1. Start with a file that contains a match to the regex, for an example
```ts
const test = {
  color: '#fff',
  backgroundColor: '#000'
};
```
2. Write a selection query that includes regex. For an example `^\s*\w*color:` (and of course enable the regex filter - "Use Regular Expression")
3. Trigger `editor.action.addSelectionToNextFindMatch`

Current behavior:

The find window's filters(Match case, Match whole word, Use Regular Expression) will flash to indicate the input is used however the next match will **not** be added to the selection.

Expected behavior:

The next regex match gets added to the current one.

Not sure if this is intended as I couldn't find anything about it in the docs or in the existing issues but it doesn't seem to be as the non-regex filter approach properly marks the next occurrence, making the above behavior inconsistent.

**Comment by h8nor** [comment] 2023-08-16 11:08
Sorry, has it #165216 been fixed?

**Comment by amunger** [comment] 2023-12-14 00:06
duplicate of https://github.com/microsoft/vscode/issues/107090

**Closed by amunger** 2023-12-14 00:06 UTC
Labels: bug, editor-find
