### ISSUE TITLE
Scrolling using touch pad is very choppy.

### ISSUE THREAD

**Issue by vikrampraveen** [Microsoft/vscode#36464] opened 2017-10-18 06:44 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.17008
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
MagicPython|mag|1.0.12
cpptools|ms-|0.13.1
csharp|ms-|1.12.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-18 07:38
duplicate of #13612

**Closed by mjbvz** 2017-10-18 07:38 UTC
Labels: duplicate, extensions, new release
