### ISSUE TITLE
Add real time collaborate function

### ISSUE THREAD

**Issue by Andrewyg** [Microsoft/vscode#28671] opened 2017-06-14 00:02 UTC

**Comment by ramya-rao-a** [comment] 2017-06-14 01:11
@Andrewyg Can you add some details about your ask?

**Comment by Andrewyg** [comment] 2017-06-14 06:48
As this is a feature request I would like something like [Firepad](http://firepad.io) that different people has different color of cursor and have a real time collaborate function

You can have a demo [here](http://edit.andrewyg.net/#demo) and if you want to see the collab function open it in a normal tab and incognito tab and select some word and type some word you'll see the function that I'm requesting.

**Comment by jens1o** [comment] 2017-06-15 22:12
That would be quite nice! But I'm not sure whether Microsoft can provide it itself.

**Comment by mjbvz** [comment] 2017-11-03 22:39
Duplicate of #15916

**Closed by mjbvz** 2017-11-03 22:39 UTC
Labels: duplicate, feature-request, workbench
