### ISSUE TITLE
Weird auto-formatting while editing a twig template file.

### ISSUE THREAD

**Issue by frost-byte** [Microsoft/vscode#10814] opened 2016-08-23 01:52 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 10 Home, 1607

Steps to Reproduce:

1.  Edit a .twig file
2.  Try to adjust the formatting - line breaks and spaces around curly braces, % (symbols used by twig)
3.  Save the file. (can be triggered by editing other parts of the file as well)

![vscode_twig](https://cloud.githubusercontent.com/assets/852776/17877601/704bfc08-68b2-11e6-88e7-485335d3d2d2.gif)

Apparently this was caused by the TWIG pack extension.  Uninstalling it has removed the behavior. 
https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-twig-pack

**Comment by sandy081** [comment] 2016-08-23 08:08
@frost-byte As you mentioned that it caused by TWIG pack extension, we would probably get the fix in the extension. Closing this here.

**Closed by sandy081** 2016-08-23 08:08 UTC
