### ISSUE TITLE
Integrated terminal does not measure character width correctly

### ISSUE THREAD

**Issue by ZeroRin** [microsoft/vscode#154056] opened 2022-07-04 08:32 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.68.1
- OS Version: Windows_NT x64

It seems that the integrated terminal does not measure character width according to current font. 
I noticed this while using `tqdm` in python, which by default draws progress bar with block characters `U+2588` to `U+258F`. The module treats these elements as half-width characters and so does my default font, but the terminal seems to count them as full width characters and start a new line before reaching the right edge of the terminal as a result.
Here is a simple example:
![image](https://user-images.githubusercontent.com/14952735/177115201-05437191-2260-4d80-b5bb-331da44e46f0.png)

**Comment by meganrogge** [comment] 2022-07-05 18:43
what version of windows are you on? we cannot reproduce, indicating it's likely an issue w conpty and will be fixed when your windows version is updated

**Comment by ZeroRin** [comment] 2022-07-06 05:54
Thanks for reply.
The laptop encountering this problem is on version 1809. I've just tested on my own PC (21H1) and failed to reproduce it, so it seems likely.
Sadly, this laptop belongs to my company, and I cannot update the computer by myself. Are there any suggestions about any workarounds?

**Comment by meganrogge** [comment] 2022-07-06 14:30
unfortunately this is not something we can control

**Closed by meganrogge** 2022-07-06 14:30 UTC
Labels: needs more info
