### ISSUE TITLE
VS Code repo workspace settings has warnings

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#47291] opened 2018-04-06 08:18 UTC
I observed that settings in VS Code project has warnings

- Unknown configuration settings
  - [ ] `lcov.path` - @alexandrudima 
  - [ ] `lcov.watch` - @alexandrudima 
- Accessing window scoped settings (when opened VS Code in MR Workspace)
  - [ ] `files.associations` - @bpasero 
  - [ ] `typescript.tsdk` - @mjbvz  
  - [ ]  `emmet.excludeLanguages` - @ramya-rao-a 

![image](https://user-images.githubusercontent.com/10746682/38409935-9d3e00c8-3983-11e8-95b4-5e89e67accff.png)

IMO this should be clean as code as it is shared.

Some of the settings are not applied when opened in Workspace which I think is not good. Either we should remove them or make them resource scoped settings.

**Comment by sandy081** [comment] 2018-04-06 08:25
I see they are valid when you open just the folder, but it kind of prevent us to self host on MR right. I might be missing some settings getting applied when using MR. For eg., `typescript.tsdk` this will not run the same typescript server as the team when using MR. I would have to manually configure it.

**Comment by bpasero** [comment] 2018-04-06 08:35
@sandy081 yes I agree but then the real fix is to make more settings folder settings supported.

**Comment by sandy081** [comment] 2018-04-06 08:47
@bpasero Agreed. This is one of the suggestions I made

> Some of the settings are not applied when opened in Workspace which I think is not good. Either we should remove them or make them resource scoped settings.

**Comment by bpasero** [comment] 2018-04-06 08:58
Created https://github.com/Microsoft/vscode/issues/47298 for that purpose.

**Comment by alexandrudima** [comment] 2018-04-06 10:45
@sandy081 

There is no way to have folder specific settings outside of the folder, so where can I define these folder-specific settings for the test coverage extension ?

**Comment by sandy081** [comment] 2018-04-06 11:04
@alexandrudima Since we use the settings from lcov extension, shall we recommend in this workspace recommendations?

May be adopt the lcov extension to be multiroot aware and make these settings resource scoped?

**Comment by ramya-rao-a** [comment] 2018-04-10 23:27
@sandy081 The emmet related setting only gets added when the integration tests are run. They are not checked in to the repo. So it shouldnt matter here.

**Comment by ramya-rao-a** [comment] 2018-04-23 17:45
I've updated the unit tests that add the emmet settings to the workspace to use global settings instead. So you shouldnt be seeing the emmet settings in the workspace settings anymore

**Comment by mjbvz** [comment] 2018-05-01 17:50
The tsdk one is by design since there can only be a single typescript server for the entire workspace (not one per root). I think the warning that the setting cannot be applied now makes sense for this case

**Comment by alexandrudima** [comment] 2018-05-02 07:55
@sandy081 

* I don't have time to invest in LCOV now, so:
  * I don't want LCOV to be a recommended extension.
  * I don't want to adopt multi-root in any way.
* I want to be able to continue using LCOV how I am using it now.
* I need to customize this extension with settings.

What are my options?

**Comment by sandy081** [comment] 2018-05-02 09:37
I do not see any options other than living with warnings 😞

**Closed** 2018-05-02 09:38 UTC
Labels: under-discussion
