### ISSUE TITLE
Allow middle mouse button to be bound in keyboard shortcuts

### ISSUE THREAD

**Issue by poodle-chowder** [microsoft/vscode#43794] opened 2018-02-16 01:28 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Change keybinding for a shortcut
2. Click middle mouse button when prompted for a key combination

(feature request) Not technically a key, but it could be useful if bound like one. Example: middle mouse click to go to definition.

**Comment by duane** [comment] 2018-06-26 22:32
This would also be highly useful on linux for overriding middle mouse click from paste -> anything else (...even with editor.selectionClipboard is false).

**Comment by carstenhag** [comment] 2018-08-24 20:50
Being able to define all mouse clicks would be nice. Especially for something like https://github.com/James-Yu/LaTeX-Workshop/issues/716

**Comment by sk8ersteve** [comment] 2019-08-04 18:12
> This would also be highly useful on linux for overriding middle mouse click from paste -> anything else (...even with editor.selectionClipboard is false).

My understanding is that in Linux, this middle-click functionality is coded into Xorg, so it would not be trivial for VSCode to have this functionality. 

My issue is that VSCode currently maps multi-line select to the middle mouse button which behaves very weirdly when I actually try to use it.

**Comment by atomi** [comment] 2019-08-04 23:42
In Linux Mint both Chrome and Firefox are able to bind middle click to page scroll.

**Comment by ThiefMaster** [comment] 2019-08-14 13:28
Is there any extension available right now to use middle click for jumping to the definition? I'm very used to this from pycharm etc..

**Comment by adabru** [comment] 2019-10-17 11:29
@poodle-chowder , I think this is a duplicate of https://github.com/microsoft/vscode/issues/3130 ?

**Comment by git-xbits** [comment] 2019-10-18 18:42
I really need this functionality too, I'm migrating from Android Studio  to VSCode, and I go to defition with middle mouse click, and VSCOde don't have plugins to this or duplicate with ctrl + D.

Please consider to implement this functionality.

**Comment by drygiel** [comment] 2019-11-08 16:40
This prevents me from using VS Code :( I so much get used to navigate though the code by just clicking on the class names...

**Comment by Shahaed** [comment] 2020-01-29 00:14
![](https://media.giphy.com/media/xUOwFZmWUC2QDHKu4M/giphy.gif)

**Comment by XeonG** [comment] 2020-03-13 11:03
When will this be added already!?!... it opens up at number of much more easier shortcuts especially with mmb+modifier key.... like commonly used ones like ctrl+shiftf+f12 ...I mean I use 'find all references' all the time, would be so much better bound to mmb+modifier,

**Comment by danielsamuels** [comment] 2020-04-16 10:51
For those of you who are looking for a short term fix for this, I've created an [AutoHotkey](https://www.autohotkey.com/) script which provides middle-click Go To Definition behaviour:

```
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
#IfWinActive ahk_exe Code.exe
MButton::
Send,{Click}{F12}
return
```

Copy the above contents into a file named `vscode-f12-go-to-definition.ahk` and run it. You'll see a green H icon in your systray which shows it's running.

**Comment by lynxnathan** [comment] 2020-05-27 17:34
Tip: you can a use a software like [BetterTouchTool](https://folivora.ai/) for mouse / touchpad / touchbar on mac:

![better touch tool screenshot with two assigned mouse shortcuts to vscode for navigation controls](https://d.pr/i/uHc4se+)

**Comment by 1C0D** [comment] 2020-09-18 21:16
simplicity for most commun things is not part of the program really
uncomment you search you don't find comment this is mad shortcut hey take your pils

**Comment by 1C0D** [comment] 2020-09-18 21:21
shortcut are so messy that ok bye. middle mouse button to select a line is not so much to ask. 3 tonnes of messy shortcuts

**Comment by chipnertkj** [comment] 2020-10-22 17:44
do you guys not have a keyboard?

**Comment by drygiel** [comment] 2020-10-22 20:38
@chipnertkj In all other IDEs I can click on a class name with `MMB` and navigate to the reference **WITHOUT** touching a keyboard - using ONE hand only. But this is how it looks in VS Code:

![image](https://user-images.githubusercontent.com/1775021/96927191-fdd30300-14b6-11eb-9f07-23698a4d7561.png)

**Comment by chipnertkj** [comment] 2020-10-23 14:43
You can just navigate to it without your hand ever leaving the keyboard. Just think about how much time that can save you. I get that it'd be a useful feature for people who aren't used to keyboard navigation and I agree that it indeed should be a feature, but since it doesn't seem like we're getting it anytime soon - why don't you try it out?

**Comment by chenasraf** [comment] 2020-11-03 10:28
> You can just navigate to it without your hand ever leaving the keyboard. Just think about how much time that can save you. I get that it'd be a useful feature for people who aren't used to keyboard navigation and I agree that it indeed should be a feature, but since it doesn't seem like we're getting it anytime soon - why don't you try it out?

But a lot of us are going through the code with the mouse because we quickly navigate between definition trees. We can't not keep our hands on the keyboard if we didn't have it there to begin with. You're losing the point

**Comment by gjsjohnmurray** [comment] 2020-12-07 07:21
> @poodle-chowder , I think this is a duplicate of #3130 ?

Thanks @adabru

/duplicate

**Closed** 2020-12-07 07:22 UTC
Labels: *duplicate, feature-request, keybindings

**Comment by eriegz** [comment] 2020-12-21 02:14
Hey VS Code employees, could you perhaps have your triage bot include a link to whatever issue this one supposedly duplicates?

**Comment by levpaul** [comment] 2020-12-29 05:54
@eriegz - it's #3130 which was mentioned above
