### ISSUE TITLE
Cannot swich language in integrated terminal

### ISSUE THREAD

**Issue by reklatsmasters** [microsoft/vscode#118628] opened 2021-03-10 12:17 UTC
- VS Code Version: 1.54.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Start vscode
2. Open integrated terminal
3. Try to switch language, it doesn't work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2021-03-29 15:12
Duplicate of #116926

**Closed** 2021-03-29 15:17 UTC
Labels: *duplicate, bug, integrated-terminal
