### ISSUE TITLE
Code folding takes too long to activate and acting weird

### ISSUE THREAD

**Issue by ivanwitzke** [Microsoft/vscode#47962] opened 2018-04-16 13:16 UTC
Issue Type: <b>Bug</b>

Most of the times, it takes over 30s to the code folding to start working on my files, in any language (js, html, css...). Also, sometimes it folds in wrong spots (wrong place)... Right now I'm changing it back to identation based folding to see if anithing changes, because it worked normal before the last update.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 2139)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (0.51GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.3.0
vscode-wakatime|Wak|1.2.0
project-manager|ale|0.25.0
vscode-eslint|dba|1.4.8
apacheconf-snippets|eim|1.1.9
vscode-apache|mrm|1.1.1
vetur|oct|0.11.7
trailing-spaces|sha|0.2.11
gitflow|vec|1.1.2
vuetify-vscode|vue|0.1.7

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2018-04-18 20:01
This is likely the TypeScript language server starting up. Folding ranges are only provided once the language support is up.

How long does it take to see validation errors on JS files?

**Comment by aeschli** [comment] 2018-06-06 14:04
duplicate of #51225

**Closed by aeschli** 2018-06-06 14:04 UTC
Labels: editor-folding, needs more info
