### ISSUE TITLE
All Extensions Disabled After Update

### ISSUE THREAD

**Issue by wgv-srsedate** [microsoft/vscode#82615] opened 2019-10-15 15:09 UTC
Issue Type: <b>Bug</b>

I have about 80 different extensions installed in VSCode, all of them enabled and functioning.

When VSCode is updated, whether automatically or manually, all extensions are disabled upon startup.  Options to enable them are grayed out.  This affects all extensions.  Restarting the computer does not help.  Re-installing the update does not help.

My only option is to re-install the older version of VSCode, which resolves the issue, but I am now unable to use any of the newer versions.  This starting happening with 1.39.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
angular-schematics|cyr|1.27.0
vscode-markdownlint|Dav|0.31.0
vscode-simpler-icons|dav|1.6.5
whitespace-plus|dav|0.0.5
vscode-eslint|dba|1.9.1
docs-yaml|doc|0.2.4
angular-extension-pack|dog|7.2.0
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
vscode-great-icons|emm|2.1.47
auto-rename-tag|for|0.1.0
todo-tree|Gru|0.0.160
vscode-test-explorer|hbe|2.14.6
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.2.0
docthis|joe|0.7.1
Angular2|joh|8.1.1
refactorix|kri|0.3.6
json-to-ts|Mar|1.5.5
Angular-BeastCode|Mik|8.0.10
import-sorter|mik|3.3.1
ts-barrelr|mik|1.3.0
azure-pipelines|ms-|1.157.4
vscode-azureappservice|ms-|0.16.0
vscode-azurefunctions|ms-|0.19.0
vscode-azurestorage|ms-|0.7.2
vscode-azureterraform|ms-|0.2.4
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
windowsiot|ms-|0.0.20
vscode-kubernetes-tools|ms-|1.0.4
mssql|ms-|1.6.0
python|ms-|2019.10.41019
vscode-ai|ms-|0.6.6
remote-wsl|ms-|0.39.9
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
cpptools|ms-|0.25.1
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
typescript-javascript-grammar|ms-|0.0.53
vscode-azureextensionpack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.2
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.7.0
azure-hdinsight|msh|1.1.7
debugger-for-chrome|msj|4.12.0
vscode-react-native|msj|0.12.1
vscode-jest|Ort|3.0.2
quicktype|qui|12.0.46
java|red|0.50.0
vscode-yaml|red|0.5.3
vscode-jest-test-adapter|rtb|0.2.0
vscode-coverage-gutters|rya|2.4.0
code-spell-checker|str|1.7.18
move-ts|str|1.11.5
usql-vscode-ext|usq|0.2.15
vscodeintellicode|Vis|1.1.9
application-insights|Vis|0.4.2
azure-iot-edge|vsc|1.17.0
azure-iot-toolkit|vsc|2.11.0
azure-iot-tools|vsc|0.3.0
vscode-arduino|vsc|0.2.27
vscode-iot-device-cube|vsc|0.1.1
vscode-iot-workbench|vsc|0.10.15
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by roblourens** [comment] 2019-10-15 16:56
/duplicate of https://github.com/microsoft/vscode/issues/82359

**Closed** 2019-10-15 16:56 UTC
Labels: *duplicate, new release
