### ISSUE TITLE
Add posibility for a language to define indentation settings

### ISSUE THREAD

**Issue by peterbourgon** [microsoft/vscode#2765] opened 2016-02-06 15:35 UTC
This is a followup from [vscode-go/#191](https://github.com/Microsoft/vscode-go/issues/191).

Go uses tabs for indention, and spaces for alignment. When I open a .go file and press tab, for example selecting a block of text and tabbing to indent, spaces are inserted instead. I can't think of a situation when I want the tab key to insert spaces in a .go file. Can the autodetection algorithm be improved in this case?

(As an aside, thanks for this project! I'm really enjoying it so far.)

**Comment by egamma** [comment] 2016-02-06 15:40
Can you pls add a .go file as an example where the guessing was wrong? As you describe it, go files should have tabs and the guessing should pick tabs as well.

**Comment by peterbourgon** [comment] 2016-02-06 16:04
```go
package main

func main() {
	println("hello")
}
```

Note the tab literal prefixing println. Position the cursor after the final closing }, press enter twice, and type

```
func foobar() {
```

and press enter. You'll get

```
func foobar() {
····_
}
```

i.e. the autoindent will be with spaces.

**Comment by peterbourgon** [comment] 2016-02-06 16:13
And GIF form! When I save, `gofmt` (actually `goimports`) is automatically applied, which is why you see the spaces turn into tabs.

![image](http://g.recordit.co/5dRXp1O01f.gif)

**Comment by egamma** [comment] 2016-02-06 16:44
Thanks for all the steps, but I cannot reproduce this in the [insider build](https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/).

See below, only tabs are inserted with the settings shown on the right.

Assigning to @alexandrudima may be something changed since 0.10.6.

![tabs](https://cloud.githubusercontent.com/assets/172399/12867826/9bc88140-ccf8-11e5-8ed2-42e2090c47af.gif)

**Comment by peterbourgon** [comment] 2016-02-06 18:08
OK! I'll test on the next release.

**Comment by egamma** [comment] 2016-02-10 12:02
@alexandrudima mentioned to me that the issue still exist. I'm must have tried on an older version.

**Comment by alexandrudima** [comment] 2016-02-22 23:11
@peterbourgon @egamma Currently, `"auto"` indentation settings are evaluated only once, on file open. So if the file is indented with spaces when it is opened, the guess will be to insert spaces. Further edits that bring in more tabs in a file are not taken into account until the file is closed (from the working files view) and the file is reopened.

**Comment by peterbourgon** [comment] 2016-02-23 17:20
@alexandrudima Go files are always indented with tabs, aligned with spaces. So, given your description of the algorithm, I would expect Code to detect tab indentation when opening Go files. — But I suggest a different heuristic: that "auto" always evaluate to tabs-for-indent when opening `.go` files, superseding file content analysis.

**Comment by alexandrudima** [comment] 2016-02-24 10:40
@peterbourgon I am sorry for the bad behaviour. We currently don't have per-file type settings, but there is something great that we work with: `.editorconfig`.

http://editorconfig.org/

And the VSCode plugin:

https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by peterbourgon** [comment] 2016-02-24 13:25
Thanks for the comment. No need to apologize. An extension like that is probably inappropriate to use for Go, as in Go there is nothing to configure: the language strictly defines valid code format rules, including but not limited to tabs for indentation.

**Comment by alexandrudima** [comment] 2016-03-17 12:18
Changed the title. According to @peterbourgon all .go files should always be indented with tabs, the go compiler cannot compile files indented with spaces. I guess this is similar to yaml, where yaml processors cannot handle files indented with tabs.

**Comment by peterbourgon** [comment] 2016-03-17 12:41
> the go compiler cannot compile files indented with spaces

To be clear, it will compile, but it is not canonical format.

**Comment by alexandrudima** [comment] 2016-03-17 13:15
The [Go language spec](https://golang.org/ref/spec) does not seem to touch on the topic of preferring tabs vs spaces for indentation, it simply defines them as whitespace and then defines the semantics of whitespace while parsing source code.

If I understood how this works, the go compiler ships with a formatter that prefers tabs, which is great.

But given this is not specified in the language, and the compiler can compile files indented with spaces (as per the language spec), I'm not sure what you would expect VSCode to do special regarding .go files.

**Comment by peterbourgon** [comment] 2016-03-17 13:28
> If I understood how this works, the go compiler ships with a formatter that prefers tabs, which is great.

It's much stronger than "prefers" — it's more like canon. To some order of approximation, zero percent of Go code in the wild has any other format than the canonical gofmt style. I understand this is different than many other programming ecosystems.

> I'm not sure what you would expect VSCode to do special regarding .go files.

When VSCode encounters a .go file, it should use tabs for indentation, and spaces for alignment within that file. This behavior should not be configurable, nor should it rely on the user installing/configuring an external plugin. Concretely, if this doesn't happen, Go users of VSCode (using the excellent vscode-go plugin) will observe indentation spaces replaced with tabs every time they save their files. Bad UX.

**Comment by alexandrudima** [comment] 2016-03-17 13:36
Maybe this is something the Go extension could do.

@lukehoban This snippet in the go extension would ensure all .go files use tabs and not spaces:
```
vscode.window.onDidChangeActiveTextEditor((editor) => {
	if (editor && editor.document.languageId === 'go' && editor.options.insertSpaces) {
		editor.options = {
			insertSpaces: false
		};
	}
});
```

**Comment by peterbourgon** [comment] 2016-03-17 13:37
Would be happy with that!

**Comment by eromoe** [comment] 2016-12-29 07:11
I'd like make html,js ,css, scss , json  in size 2, others in 4, I use https://github.com/tzvetkoff/sublime_stupid_indent in sublime,  maybe vscode can take a similar way like that.

**Comment by alexandrudima** [comment] 2017-05-29 11:05
This can be done via language specific settings. e.g.:

![screen shot 2017-05-29 at 13 04 50](https://cloud.githubusercontent.com/assets/5047891/26547443/6b569804-446f-11e7-8527-455b869728e4.png)

**Comment by aeschli** [comment] 2019-10-28 14:47
Marking as fixed based on comment https://github.com/alexandrudima

**Closed by aeschli** 2019-10-28 14:47 UTC
Labels: feature-request, languages-basic
