### ISSUE TITLE
Task: "Configure task" does nothing when no `tasks.json` is present 

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#94017] opened 2020-03-31 18:08 UTC
Version: 1.44.0-insider
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:22:34.682Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

Testing #93746

![image](https://user-images.githubusercontent.com/4033249/78060071-c3015600-733f-11ea-8501-b661c35c446a.png)

In a folder without `tasks.json`. `Run Tasks` -> "No configured tasks. Configure tasks..." does nothing.

**Comment by alexr00** [comment] 2020-04-01 08:30
duplicate of https://github.com/microsoft/vscode/issues/93925

**Closed by alexr00** 2020-04-01 08:30 UTC
