### ISSUE TITLE
Idk but it says Typescript died 5 times in 5 mins

### ISSUE THREAD

**Issue by faker007** [microsoft/vscode#141037] opened 2022-01-20 01:57 UTC
Issue Type: <b>Bug</b>

Idk but it says Typescript died 5 times in 5 mins

Thanks for your support, Typescript Team!
from S.Korea.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (2.59GB free)|
|Process Argv|. --crash-reporter-id 68cfd0b1-e5c1-416f-abed-f3ca00a2dd24|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|11.7.0
prettier-vscode|esb|9.1.0
auto-rename-tag|for|0.1.9
copilot|Git|1.7.4688
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.1
code-spell-checker|str|2.1.4
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by faker007** [comment] 2022-01-20 01:59
Actually, I guess It does't seem like a problem, but I got gut feeling of rebooting, all problem solver

**Comment by mjbvz** [comment] 2022-01-21 00:18
Closing since it sounds like you are no longer able to reproduce this issue? Let me know if that's not the case

**Closed by mjbvz** 2022-01-21 00:18 UTC
