### ISSUE TITLE
Should breadcrumbs should be hidden in webview editors?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81774] opened 2019-10-01 16:55 UTC
#81698

I think it just ends up being an empty rectangle at the top of the editor

![image](https://user-images.githubusercontent.com/2193314/65983074-98d2e800-e431-11e9-8ab0-6973b09377b7.png)

**Comment by Tyriar** [comment] 2019-10-01 17:24
It's empty for me because I have this setting:

```
"breadcrumbs.filePath": "off"
```

When it's on it looks like this:

![image](https://user-images.githubusercontent.com/2193314/65984880-8d81bb80-e435-11e9-8205-eec05e78ae33.png)

Maybe breadcrumbs should only show when there is text to display?

**Comment by jrieken** [comment] 2019-10-02 07:26
/duplicate of https://github.com/microsoft/vscode/issues/56327

**Closed** 2019-10-02 07:26 UTC
Labels: *duplicate, breadcrumbs
