### ISSUE TITLE
NPM scripts explorer should detect configured tasks

### ISSUE THREAD

**Issue by bam** [Microsoft/vscode#49197] opened 2018-05-04 09:48 UTC
- VSCode Version: 1.23.0
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Create package.json with 3 scripts
2. Task -> Configure tasks...
3. Select 1 of detected scripts from NPM and press Enter
4. tasks.json will be created with the configured task
5. Open NPM scripts explorer.

*Actual behaviour*: there are only 2 scripts (excluded script from configured task)

*Expected behaviour*: there are all 3 NPM scripts in explorer

**Comment by egamma** [comment] 2018-05-07 08:07
This is a duplicate of #48831 that is targeted for May.

**Closed** 2018-05-07 08:07 UTC
Labels: new release
