### ISSUE TITLE
Build related terminals do not restore on reload

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122171] opened 2021-04-26 06:53 UTC
Steps to Reproduce:

1. have tabs enabled
2. run our default build task (it opens 2 terminals)
3. apply insiders update

=> 🐛  the terminals do not restore

**Before**
![image](https://user-images.githubusercontent.com/900690/116040898-ded34a80-a66c-11eb-8352-301100576d74.png)

**After**
![image](https://user-images.githubusercontent.com/900690/116040418-4b017e80-a66c-11eb-9860-c144bb54b961.png)

//cc @alexr00 I wonder if we actually terminate these terminals on shutdown?

**Comment by alexr00** [comment] 2021-04-26 07:49
Since there is work required from tasks to handle this, we currently deliberately don't restore terminals that belong to tasks. Duplicate of https://github.com/microsoft/vscode/issues/117408

**Closed by alexr00** 2021-04-26 07:49 UTC
