### ISSUE TITLE
Using key chord when file tree is focused triggers file highlighting

### ISSUE THREAD

**Issue by pedro-pedrosa** [Microsoft/vscode#68171] opened 2019-02-07 21:24 UTC
Issue Type: <b>Bug</b>

When focusing the file tree pane, hitting the "Save all" chord `Ctrl+K`-`S` triggers the file highlighting feature when the `S` key is pressed, making it impossible to use the chord.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
csharp|ms-|1.17.1
vscode-docker|Pet|0.5.2

</details>

**Comment by kieferrm** [comment] 2019-02-07 23:52
As a temporary work-around you can disable highlight/filtering in the tree. Change the setting `Workbench > List: Keyboard Navigation` to `simple` or in json:

```json
"workbench.list.keyboardNavigation": "simple"
```

**Comment by joaomoreno** [comment] 2019-02-08 09:21
@pedro-pedrosa I can't reproduce. We have code in place which avoids conflicts with chord commands. Can you send me a screen recording of the issue?

**Comment by pedro-pedrosa** [comment] 2019-02-08 09:43
Currently set to highlight.

`"workbench.list.keyboardNavigation": "highlight"`

Anything else you'd like me to check?

**Comment by pedro-pedrosa** [comment] 2019-02-08 09:48
If I change it to simple it both triggers the chord and selects a file. If I change it to filter, it doesn't trigger the chord and starts filtering the file tree, same behaviour as highlight.

**Comment by IllusionMH** [comment] 2019-02-08 12:21
I'm able to reproduce this issue in latest Insiders build.

1. Click on any file in Explorer
1. Press Ctrl + K - status bar shows `(Ctrl + K) was pressed waiting for second key of chord...`
1. Press any key - it is added to highlight, status bar still shows `(Ctrl + K) was pressed waiting for second key of chord...`

I have `"workbench.list.keyboardNavigation": "highlight"` in settings.

If I switch it to `"simple"` than I see next behavior:
1. Press Ctrl + K - status bar shows `(Ctrl + K) was pressed waiting for second key of chord...`
1. Press `s` - all edited files saved, status bar is cleared **and** file/folder starting with `s` is focused

VS Code version: Code - Insiders 1.32.0-insider (1c50a87561055485d93a3961160902308497f1e3, 2019-02-08T06:16:17.233Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (18.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by heihachi88** [comment] 2019-02-11 06:02
I've noticed one more thing:

1. If i focus terminal window, and press ⌘K, ⌘S - nothing happens, even if i just press ⌘K i don't see the message `⌘K was pressed waiting for second key of chord...`, but if i press ⌘R, then i see the message i mentioned above, but ⌘R, Shift+R doesn't work.
2. if i focus editor window itself, then all keybindings do work.
3. if i focus explorer window, then ⌘K, ⌘S work, but ⌘R, Shift+R doesn't work, it instead highlighting the root folder:

![image](https://user-images.githubusercontent.com/5739191/52547904-d6c4c280-2df4-11e9-895b-2aa4f2d421a8.png)

**Comment by heihachi88** [comment] 2019-02-11 07:01
Just checked my keybindings:

![image](https://user-images.githubusercontent.com/5739191/52549359-f233cb80-2dfc-11e9-9613-827b2a0b3114.png)

As you can see, the `When` column is empty, so it means these keybindings should fire independent of focused area, e.g. text editor, terminal, explorer. Clearly a bug in 1.31 version.

**Comment by alexandrudima** [comment] 2019-02-11 15:43
I can confirm. Steps:
* define new keybinding, e.g.:
```
{
    "key": "ctrl+k s",
    "command": "actions.find"
}
```
* focus the explorer
* press `ctrl+k`
* the first part of the chord is entered
* press `s`
* the tree begins to highlight 's'.

![image](https://user-images.githubusercontent.com/5047891/52574169-fd4a2400-2e1b-11e9-8d85-815635f3782e.png)

---

The workaround provided by [kieferrm](https://github.com/Microsoft/vscode/issues/68171#issuecomment-461639865) works for me, which is to define in `settings.json`:

```
"workbench.list.keyboardNavigation": "simple"
```

**Comment by heihachi88** [comment] 2019-02-12 06:31
`"workbench.list.keyboardNavigation": "simple` - it's just a workaround? Thing won't change in the future regards this setting?

**Comment by pedro-pedrosa** [comment] 2019-02-12 09:02
Disabling features is not a workaround.

**Comment by joaomoreno** [comment] 2019-02-20 15:36
I can repro this on Windows, but not on macOS and Linux.

**Comment by joaomoreno** [comment] 2019-02-21 15:57
@alexandrudima Check this out:

![image](https://user-images.githubusercontent.com/22350/53182391-b0273880-35f9-11e9-8c60-bd2a77161af1.png)

Ctrl-F17?! :thinking:

**Comment by joaomoreno** [comment] 2019-02-21 16:02
@alexandrudima Found the issue. I was passing a raw `KeyboardEvent` to `softDispatch` which was resolving to that `ctrl+F17` keypress. As soon as I wrapped it around `StandardKeyboardEvent`, I got the correct behavior:

![image](https://user-images.githubusercontent.com/22350/53182734-625f0000-35fa-11e9-96dd-6018ebba915a.png)

I'll close this with that fix... but you might want to look into it.

**Closed** 2019-02-21 16:04 UTC
Labels: bug, tree

**Comment by alexandrudima** [comment] 2019-02-21 16:57
@joaomoreno That is crazy, I didn't realize TS would find those to be compatible... Thanks for the heads up. I've pushed 2ff5d6bec9c0406cf49359a0a92d8a382609b8ef which makes it more obvious and found another bad usage :/ https://github.com/Microsoft/vscode/commit/2ff5d6bec9c0406cf49359a0a92d8a382609b8ef#diff-2203e613237f08bd954dd0a758dfffb4R360
