### ISSUE TITLE
Severe slowdown of Markdown preview

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#32396] opened 2017-08-12 22:33 UTC
- VSCode Version: Code - Insiders 1.16.0-insider (f1a3bc4f714123eaff5e15ad976d7f403cc1bfa2, 2017-08-11T05:16:53.568Z)
- OS Version: Windows_NT x64 10.0.16251
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.0.2
vscode-eslint|dba|1.2.11
coldfusion|ili|0.0.10
wordcount|ms-|0.1.0
htmlescape-vscode-extension|ray|0.0.4
spellchecker|swy|1.2.13

---

I noticed that Markdown preview is incredibly slow for me now - sometimes taking near a minute to render. It seems to be a "one time per doc" issue as if I close the preview and open it up again, it works well, but previewing a new Markdown file is slow again.

I'm using files from my blog - here is one example: https://github.com/cfjedimaster/raymondcamdendotcom/blob/master/content/post/2017/08/09/career-advice-for-a-new-web-dev.md

**Comment by mjbvz** [comment] 2017-08-16 23:34
I'm having trouble reproducing this on a windows machine. A few questions:

1. Does the latest insiders build still show this problem? 
1. If you disable all extensions, does this still occur?
1. If you get rid of the script block in the document, does the problem still occur?

Thanks

**Comment by cfjedimaster** [comment] 2017-08-17 12:29
Updated and it went away. Thank you. :) Found a new bug though. ;)

**Comment by cfjedimaster** [comment] 2017-08-17 12:32
Actually - I'm going to stay here as I think it may be related. Please tell me if not and I'll refile. 

So the initial issue I saw is definitely fixed. One thing I do a lot (and it bugs the heck out of me but honestly it is my fault, not VSC) is this:

Open a MD file.
Click preview.
Open a second MD file.

And I forgot the preview had focus. So the second MD file opens in the second ... block? Whatever it is.

So I just did that. I closed the second MD file in the second block and I noticed the preview was gone. Instead, there was a loading style widget on top. It's like the preview "lost" the view and had to rerender, and that took like 5-10 seconds. I can try recording a video if that would help.

**Comment by mjbvz** [comment] 2017-08-17 23:04
Yes, please try recording a short video or providing more detailed repo steps. I could not reproduce this issue

**Comment by cfjedimaster** [comment] 2017-08-18 18:46
So - the problem has gotten worse. I'm now getting extension host crashes. But here is a video.

https://www.screencast.com/t/cRMHoSlj94E

Going to try w/ extensions disabled too.

**Comment by cfjedimaster** [comment] 2017-08-18 18:59
Ok, so testing w/ all extensions disabled and it is working correctly. I'm using "Markdown Preview Github Styling" - I bet that is the issue. Going to re-enable it and see if it comes back.

**Comment by mjbvz** [comment] 2017-08-18 18:59
@cfjedimaster Yes, please try disabling extensions and seeing if the issue still reproduces. Also, can you please post the video somewhere that does not require Flash to view

**Comment by cfjedimaster** [comment] 2017-08-18 19:01
Sorry - Jing was the quickest solution I could find.

So woah... get this. I believe it may be a spell checker extension!

**Comment by cfjedimaster** [comment] 2017-08-18 19:03
Yep. This is the extension causing issues (I believe) - https://marketplace.visualstudio.com/items?itemName=swyphcosmo.spellchecker. Going to file a bug report them. Thanks for hearing me out.

**Comment by mjbvz** [comment] 2017-08-18 19:48
Ok, thanks for the quick followup. Closing as caused by extension

**Closed by mjbvz** 2017-08-18 19:48 UTC
Labels: caused-by-extension, insiders, markdown, needs more info
