### ISSUE TITLE
Custom titlebar menu opens on click

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#56947] opened 2018-08-22 00:01 UTC
Issue Type: <b>Bug</b>

Currently, the top level menu in the custom titlebar opens a submenu in response to a click event.

Correct behaviour under Windows is to open a submenu in response to a mousedown event. Compare the native top level menu, which opens submenus on a mousedown event.

Note that this implies that menu item invocation should triggered by mouseup rather than click, which is also not currently correctly implemented.

Version: 1.27.0-insider
Commit: 07796186d388044595cd101c49378c7cd48b350b
Date: 2018-08-21T08:48:57.835Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

VS Code version: Code - Insiders 1.27.0-insider (07796186d388044595cd101c49378c7cd48b350b, 2018-08-21T08:48:57.835Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (9.93GB free)|
|Process Argv|C:\Users\PeterWone\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.4.0
csharp|ms-|1.15.2

</details>

**Comment by sbatten** [comment] 2018-08-27 20:19
duplicate of #52907

**Closed by sbatten** 2018-08-27 20:19 UTC
Labels: integrated-terminal
