### ISSUE TITLE
Dutch keyboard layout: ctrl-` is displayed wrong

### ISSUE THREAD

**Issue by bluecrowbar** [Microsoft/vscode#24178] opened 2017-04-07 06:28 UTC
In the Keyboard Shortcuts window, typing ctrl-` shows up as ctrl+[IntlBackslash], which displays as ctrl-§. I use a Dutch Apple keyboard.

Steps to Reproduce:

Keyboard Shortcuts window. Weirdly, typing ctrl-` shows up as ctrl+[IntlBackslash], which displays as ctrl-§. I use a Dutch keyboard.

1. open the Keyboard Shortcuts window
2. click + in front of a line to open the window where you can enter a shortcut
3. type ctrl-`

- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- no extensions

**Comment by jsynowiec** [comment] 2017-04-07 09:01
Duplicate of #24186, Tracking in #24086

**Comment by alexandrudima** [comment] 2017-04-10 08:53
@bluecrowbar This might be an issue in our native node module that reads the keyboard layout. Could you please do the following:

* open an editor
* run `F1 > Developer: Inspect Keyboard mappings`
* save the output to a file
* attach it here.

**Comment by bluecrowbar** [comment] 2017-04-10 17:17
Out of the box, my Mac with Dutch keyboard is set to the 'ABC' layout. There's also a 'Dutch' layout. I've attached both files.

[Dutch-ABC.txt](https://github.com/Microsoft/vscode/files/910878/Dutch-ABC.txt)
[Dutch-NL.txt](https://github.com/Microsoft/vscode/files/910879/Dutch-NL.txt)

**Comment by alexandrudima** [comment] 2017-04-28 12:35
Let's track in #24153. Investigation in https://github.com/Microsoft/vscode/issues/24153#issuecomment-297986346

**Closed by alexandrudima** 2017-04-28 12:35 UTC
Labels: keybindings, keyboard-layout, mac, needs more info
