### ISSUE TITLE
Cursor jumps to editor from commit box

### ISSUE THREAD

**Issue by AsadSaleh** [microsoft/vscode#111919] opened 2020-12-05 01:26 UTC
Issue Type: <b>Bug</b>

If I have a blocked text in my commit message box and want to delete it, suddenly the cursor jumps to the openned editor and deletes it instead of deleting the commit message.

This hapens if I want to commit using the VsCode source control while opening a side-by-side file comparison.

Step by step:
1. Create a change in any file
2. Try to commit it using VsCode source control, enter commit message
3. Before commiting, try to double click on a text to select it, then try to delete it

Expected result:
The selected text of the commit message will get deleted

Actual result:
The text in my currently opened editor gets deleted

Guess:
From my observasion, when I double clicked the text, the focus goes from the commit box to the currently opened editor. Is this the intended behavior?

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id c62494e9-7ba9-4fb4-beae-7b55f77f1013|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.17.0
flutter|Dar|3.17.0
gitlens|eam|11.0.6
prettier-vscode|esb|5.8.0
go|gol|0.19.0
dotenv|mik|1.0.1
awesome-flutter-snippets|Nas|2.0.4
quicktype|qui|12.0.46
java|red|0.72.0
vscode-yaml|red|0.13.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.12.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.26.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2020-12-05 02:00
/duplicate of #111496 which is fixed in Insiders and will appear in the next Stable which is due next week.

**Closed** 2020-12-05 02:01 UTC
Labels: *duplicate
