### ISSUE TITLE
While typing a git commit message in Japanese, the IME froze and wouldn't let me type

### ISSUE THREAD

**Issue by adneskuo** [microsoft/vscode#114734] opened 2021-01-22 02:39 UTC
Issue Type: <b>Bug</b>

1. Setting git / autorefresh = true
2. Type in the commit message field in the source control view in Japanese.
3. If the IME is open (typing, converting, etc.) and git reloads, you will not be able to type.

I have to relaunch VS Code or reopen it in a new window to fix it.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 3.10.0-693.17.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (22.51GB free)|
|Process Argv|--crash-reporter-id d44c31e2-0edc-430e-bf86-700edf60640a|
|Screen Reader|no|
|VM|25%|

|Item|Value|
|---|---|
|Remote|SSH: 10.37.10.22|
|OS|Linux x64 3.10.0-693.17.1.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3674)|
|Memory (System)|23.35GB (1.60GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vbscript|Dar|1.0.4
classic-asp|ili|0.0.4
better-cpp-syntax|jef|1.15.5
autoconf|mae|0.1.0
Kotlin|mat|1.7.1
vscode-language-pack-ja|MS-|1.52.2
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
emacs-mcx|tut|0.24.1
vscode-json|and|1.5.0
xml|Dot|2.5.1
git-graph|mhu|1.28.0
vscode-language-pack-ja|MS-|1.52.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0-insiders2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341

```

</details>

**Comment by congyaqwq** [comment] 2021-01-22 02:47
I have the same situation.

**Comment by tamuratak** [comment] 2021-01-22 02:57
Duplicate of #112621

**Comment by adneskuo** [comment] 2021-01-22 03:12
So we have to wait until the stable release in February..

**Closed** 2021-01-22 08:21 UTC
