### ISSUE TITLE
Integrated terminal: add floating mode

### ISSUE THREAD

**Issue by n8crwlr** [microsoft/vscode#114813] opened 2021-01-23 05:56 UTC
Please add floating mode to the integrated terminal. It is not necessary waste so much space in h or v. You can lock functions like multiple terminals in floating mode to make it easier. A useful option for opacity when not in focus would be very useful too, second an option to minimize after x seconds when not in focus.

I would like it very much,

Thx.

**Comment by meganrogge** [comment] 2021-01-25 17:31
Duplicate of #10121

**Closed by meganrogge** 2021-01-25 17:31 UTC
Labels: *duplicate
