### ISSUE TITLE
mac os x 10.11.2 open 0.10.5 crash

### ISSUE THREAD

**Issue by lovexiaov** [Microsoft/vscode#1572] opened 2015-12-22 10:15 UTC
when I open 0.10.5, it is crashed.

what I have do:
I have deleted the old config folder ~/.vscode
<img width="1028" alt="2015-12-22 18 09 29" src="https://cloud.githubusercontent.com/assets/5959755/11953028/e053edda-a8d7-11e5-8f76-d50389c5cef6.png">

**Comment by Onlytanya** [comment] 2015-12-22 10:55
'start up code with a english-us keyboard layout' will solve this problem.
you can see this. #1463

**Comment by bpasero** [comment] 2015-12-22 10:57
Duplicate of #1463

**Closed by bpasero** 2015-12-22 10:57 UTC
