### ISSUE TITLE
VSCode doesn't respect font scaling for menus (GNOME)

### ISSUE THREAD

**Issue by bayger** [microsoft/vscode#101989] opened 2020-07-09 11:20 UTC
Issue Type: <b>Bug</b>

All elements of the UI are scalled improperly. If you set the font scalling to 1.2 times in Gnome Tweaks this scale is not applied to the UI including menus (popup and main menu). There is a workaround to set scalling inside VSCode (Ctrl-+), but this doesn't apply to menus for some reason.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.4.0-7634-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 2870)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.60GB (7.25GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sbatten** [comment] 2020-07-09 16:03
This would be on the electron side since linux is using native

**Comment by bayger** [comment] 2020-07-19 20:20
Perhaps, but I noticed something else. The UI is scaled when the font scaling is set to 1.25 or more. Any value that is less than that is simply ignored. Weird.

**Comment by hg6658** [comment] 2023-04-11 16:45
Can you please tell me which part of code should I focus on inorder to resolve this issue?

**Comment by c0sta** [comment] 2023-12-01 20:52
While I was investigating this issue I couldn't reproduce this behavior, I am not sure if I did the steps correctly, but here's a small video changing the font scale through Gnome Tweaks.

<details><summary>VS Code info</summary>
<p>

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.1.41
</p>
</details> 


[Screencast from 2023-12-01 15-16-34.webm](https://github.com/microsoft/vscode/assets/36762964/cdf8bfc6-5f1a-47f7-9777-91e58a026de0)

**Comment by deepak1556** [comment] 2023-12-12 05:13
I am unable to repro the issue with latest stable using native titlebar, closing as resolved.

**Closed by deepak1556** 2023-12-12 05:13 UTC
Labels: bug, upstream, linux, good first issue, electron, menus, confirmed
