### ISSUE TITLE
PHP typing greater-than sign

### ISSUE THREAD

**Issue by tovbaev** [Microsoft/vscode#39290] opened 2017-11-29 02:16 UTC
After typing greater-than sign in PHP file, intellisense suggestion list pops up automatically, and so, when press 'Enter' key, the first suggested PHP global variable in the list is typed. Is there any configuration options to set the suggestion list manually using the keyboard shortcut? ex: "Ctrl + ."   . Otherwise, to press "Esc" key each time after greater-than sign is very inconvenient.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
php-debug|fel|1.12.1
phpcs|ika|0.7.0
sublime-keybindings|ms-|3.0.3
team|ms-|1.122.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment] 2017-11-29 05:42
/duplicate of https://github.com/Microsoft/vscode/issues/37919

**Closed by roblourens** 2017-11-29 05:42 UTC
Labels: *duplicate, php
