### ISSUE TITLE
Don't automatically change carriage return.

### ISSUE THREAD

**Issue by leowinchester** [microsoft/vscode#77965] opened 2019-07-26 01:27 UTC
Sometimes we don't want vs code automatically change the carriage return, otherwise when submit code, we get more differences than what we wanted, visual studio community have a choice you can make when file with different type of carriage return inside(unix, windows), but seems vs code make the choice for you.

**Comment by alexandrudima** [comment] 2019-08-07 15:31
Duplicate of #127

**Closed by alexandrudima** 2019-08-07 15:31 UTC
Labels: editor-core, feature-request
