### ISSUE TITLE
Add context information when making signature help requests

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34737] opened 2017-09-21 08:29 UTC
This is the other half of https://github.com/Microsoft/vscode/issues/752

**Comment by Gama11** [comment] 2018-05-20 13:35
Is there any timeline on this? We could use this to fix some bugs in the Haxe extension / language server.

**Comment by mjbvz** [comment] 2018-07-26 22:18
Duplicate of #54972

**Closed by mjbvz** 2018-07-26 22:18 UTC
Labels: api, editor-contrib, feature-request
