### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by WuQic** [microsoft/vscode#106651] opened 2020-09-14 12:18 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200913

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `main`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13450:55)
    at getTextOfNode (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13475:16)
    at Object.declarationNameToString (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13787:66)
    at getDisplayName (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39842:53)
    at declareSymbol (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39956:111)
    at bindExportsPropertyAssignment (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:42066:17)
    at bindWorker (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41762:29)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41651:13)
    at bindExpressionStatement (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40716:13)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40201:21)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40247:21)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27565:21)
    at bindEachChild (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bindContainer (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at visitNode (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27644:24)
    at bindEachChild (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at Object.forEach (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at visitNodes (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27440:24)
    at Object.forEachChild (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27618:24)
    at bindEachChild (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at Object.forEach (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindCallExpressionFlow (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41077:21)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40229:21)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at maybeBind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40936:21)
    at bindBinaryExpressionFlow (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40884:25)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40213:21)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at bindExpressionStatement (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40716:13)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40201:21)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40241:21)
    at bindContainer (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at bindSourceFile (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39708:17)
    at Object.bindSourceFile (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39647:9)
    at initializeTypeChecker (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:77643:20)
    at Object.createTypeChecker (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:43696:9)
    at Object.getTypeChecker (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:104892:79)
    at synchronizeHostData (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:145287:21)
    at Proxy.getProgram (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:145369:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:150226:53)
    at ConfiguredProject.Project.updateGraph (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:150159:42)
    at ConfiguredProject.updateGraph (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:151093:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:152797:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:153695:44)
    at /home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:154018:97
    at Object.flatMap (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:154018:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:155037:46)
    at /home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:156910:88
    at IOSession.Session.executeWithRequestId (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:156901:28)
    at IOSession.Session.executeCommand (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:156910:33)
    at IOSession.Session.onMessage (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:156934:35)
    at Interface.<anonymous> (/home/sugo/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:159150:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.32GB free)|
|Process Argv|--crash-reporter-id b57340d3-2d94-412e-8ab3-35c16391bd0b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|Memory (System)|7.77GB (4.34GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|Memory (System)|7.77GB (4.34GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|Memory (System)|7.77GB (4.34GB free)|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
stylus|Ala|0.0.4
vscode-weapp-api|cod|0.1.8
vscode-wxml|cod|0.1.9
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.0.0
we-app-vscode|eme|0.8.0
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
pegjs-syntax|fut|0.1.1
sublime-babel-vscode|jos|0.2.10
vscode-jade-snippets|mrm|1.0.1
vscode-docker|ms-|1.5.0
vscode-language-pack-zh-hans|MS-|1.49.1
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.10
ejs-language-support|Qas|0.0.1
code-settings-sync|Sha|3.4.3
highlight-matching-tag|vin|0.9.9
ReactSnippets|xab|2.4.0
material-theme|zhu|3.8.7
typings-installer|ben|0.2.0
git-easy|bib|1.11.0
java-run|cao|1.1.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
wxml-vscode|cny|0.1.2
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
vscode-generate-getter-setter|DSK|0.5.0
java-debug|DSn|0.0.2
docthis-customize-tags|dwe|0.4.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
json-tools|eri|1.0.2
prettier-vscode|esb|5.6.0
code-runner|for|0.11.0
go|gol|0.16.2
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
path-autocomplete|ion|1.15.0
vscode-redux-devtools|jin|1.0.2
json-to-ts|Mar|1.7.5
vscode-language-babel|mgm|0.0.29
git-graph|mhu|1.26.0
vscode-fileheader|mik|0.0.2
prettify-json|moh|0.0.3
react-javascript-to-typescript-transform-vscode|moh|1.10.0
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.5.0
vscode-language-pack-zh-hans|MS-|1.49.1
python|ms-|2020.8.108011
vscode-pylance|ms-|2020.9.4
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|4.1.20200913
autotrim|Nat|1.0.6
color-highlight|nau|2.3.0
node-modules-resolve|nau|1.0.2
vetur|oct|0.27.3
vscode-wechat|qin|0.0.6
java|red|0.66.0
pegjs-language|Sir|0.1.0
language-stylus|sys|1.11.0
vsprettier|tee|1.0.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
gitblame|wad|5.0.0
codedox|wig|1.3.1
html2jade|wma|0.2.0
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.4
project-tree|zhu|0.3.0

</details>

**Comment by mjbvz** [comment] 2020-09-14 18:19
Duplicate of https://github.com/microsoft/TypeScript/issues/40513

**Closed by mjbvz** 2020-09-14 18:19 UTC
Labels: new release
