### ISSUE TITLE
Perf profile

### ISSUE THREAD

**Issue by dprice** [Microsoft/vscode#27070] opened 2017-05-22 12:40 UTC
I opened VSCode Insiders and updated four out-of-date extensions but did not reload. There was also an update to VSCode and I selected Restart. Upon restarting, this exception occurred.

Here's the stacktrace:

- VSCode Version: <code>Code - Insiders 1.13.0-insider (06e162bb2913ce6dd394bd01c7dc4be9a7aa5991, 2017-05-22T05:14:07.368Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)</code>
- Memory (System): <code>31.64GB (24.02GB free)</code>
- Memory (Process): <code>166.55MB working set (211.10MB peak, 146.25MB private, 33.24MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|203|
|main|app.isReady => window.loadUrl()|1094|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|531|
|renderer|require(workbench.main.js)|1460|
|renderer|create extension host => extensions onReady()|2152|
|renderer|restore viewlet|1734|
|renderer|restore editor view state|2326|
|renderer|overall workbench load|3477|
|main + renderer|start => extensions ready|6448|
|main + renderer|start => workbench ready|6777|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\derek.price\803f_main.cpuprofile.txt
[803f_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1018810/803f_main.cpuprofile.txt)
[803f_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1018809/803f_renderer.cpuprofile.txt)

`
-`C:\Users\derek.price\803f_renderer.cpuprofile.txt`

**Comment by bpasero** [comment] 2017-05-22 13:37
I think this is not a crash but performance report.

**Comment by dprice** [comment] 2017-05-22 13:43
Not exactly sure. VSCode kindly asked to post on its behalf and I did as I was told. :)

**Comment by jrieken** [comment] 2017-05-22 14:13
Thanks, this is a dupe of https://github.com/Microsoft/vscode/issues/24884. Spawning processes on your system is quite slow for our app (~1sec)

**Closed by jrieken** 2017-05-22 14:13 UTC
Labels: perf-profile
