### ISSUE TITLE
Hard line breaks being inserted

### ISSUE THREAD

**Issue by ethanone1** [microsoft/vscode#74700] opened 2019-05-31 22:26 UTC
Issue Type: <b>Bug</b>

Some setting keeps putting hard line breaks in my code every time I edit a line. Compeletly unnecessary since I have soft wrap turned on. Not sure if this is a bug or a feature, but I'd like it to stop. I tried increasing wrap setting from 80 to 160, but it did not improve the problem.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
apex-autocomplete|chu|0.2.13
bracket-pair-colorizer-2|Coe|0.0.28
indent4to2|Com|0.1.2
vscode-eslint|dba|1.9.0
jupyter|don|1.1.5
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|2.3.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|9.8.1
prettier-vscode|esb|1.9.0
rest-client|hum|0.21.3
forcecode|Joh|3.16.0
visualforce|Joh|1.0.2
uncrustify|Lau|2.17.0
MagicPython|mag|1.1.0
vscode-duplicate|mrm|1.2.1
mssql|ms-|1.6.0
python|ms-|2019.5.17517
debugger-for-chrome|msj|4.11.3
salesforcedx-vscode|sal|45.15.1
salesforcedx-vscode-apex|sal|45.15.1
salesforcedx-vscode-apex-debugger|sal|45.15.1
salesforcedx-vscode-apex-replay-debugger|sal|45.15.1
salesforcedx-vscode-core|sal|45.15.1
salesforcedx-vscode-lightning|sal|45.15.1
salesforcedx-vscode-lwc|sal|45.15.1
salesforcedx-vscode-visualforce|sal|45.15.1
lightning-component-snippets|Ter|1.0.6
vscodeintellicode|Vis|1.1.6
quokka-vscode|Wal|1.0.222
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment] 2019-06-03 07:15
Does this reproduce with all extensions disabled?

**Comment by ethanone1** [comment] 2019-06-03 15:18
It does.

Thanks,
Ethan


Ethan Granger
Chief Technology Officer
4900 North Scottsdale Road, Suite 3000
Scottsdale, Arizona 85251
o|480.483.8100 egranger@landadvisors.com

[cid:LAO_Signature_ca1a909a-d387-4484-a62e-8227261b089b.png]<https://landadvisors.com/>

**Comment by mjbvz** [comment] 2019-06-03 23:42
What language is this for?

**Comment by ethanone1** [comment] 2019-06-04 00:06
Python, but I’m wondering if there is a setting that just wraps lines and isn’t language specific.

This only started in the past week. There was an annoying popup about installing a pylinter and I kept ignoring it and finally thought I’d try it, but I don’t have a pylinter in my extensions, so I don’t know if it is part of intellicode or not.  Also could be related to an update as a few other things have changed. So there was both an update and this pylinter popup in the past week that are likely culprits.

Thanks,
Ethan


Ethan Granger
Chief Technology Officer
4900 North Scottsdale Road, Suite 3000
Scottsdale, Arizona 85251
o|480.483.8100 egranger@landadvisors.com

[cid:LAO_Signature_ca1a909a-d387-4484-a62e-8227261b089b.png]<https://landadvisors.com/>

**Comment by ethanone1** [comment] 2019-06-04 00:15
BTW, whatever is doing this, is also moving my library import statements around. It always moves them to the top and there are a couple that I need to load later in the script (rather annoying).

Thanks,
Ethan


Ethan Granger
Chief Technology Officer
4900 North Scottsdale Road, Suite 3000
Scottsdale, Arizona 85251
o|480.483.8100 egranger@landadvisors.com

[cid:LAO_Signature_ca1a909a-d387-4484-a62e-8227261b089b.png]<https://landadvisors.com/>

**Comment by ethanone1** [comment] 2019-06-04 00:27
I figured out where to set the linting and it seems I’m unable to disable it as per this article:
https://code.visualstudio.com/docs/python/linting


Thanks,
Ethan


Ethan Granger
Chief Technology Officer
4900 North Scottsdale Road, Suite 3000
Scottsdale, Arizona 85251
o|480.483.8100 egranger@landadvisors.com

[cid:LAO_Signature_ca1a909a-d387-4484-a62e-8227261b089b.png]<https://landadvisors.com/>

**Comment by mjbvz** [comment] 2019-06-04 00:43
Are you sure this happens when you disable all extensions, including the python one? We do not with builtin python support or a python linter

**Comment by ethanone1** [comment] 2019-06-04 03:38
I’ll try again with the extensions disabled and let you know.

Thanks,
Ethan


Ethan Granger
Chief Technology Officer
4900 North Scottsdale Road, Suite 3000
Scottsdale, Arizona 85251
o|480.483.8100 egranger@landadvisors.com

[cid:LAO_Signature_ca1a909a-d387-4484-a62e-8227261b089b.png]<https://landadvisors.com/>

**Comment by egamma** [comment] 2019-06-04 19:56
@ethanone1 any update? If it doesn't reproduce with the Python extension disabled, then please file the issue against the python extension.

**Comment by ethanone1** [comment] 2019-06-04 20:21
Yeah, after testing this morning with all extensions off, I think it is an extension. I had disabled them on first submittal, but perhaps I hadn’t restarted VS code, which might have not fully disabled it.

Thanks,
Ethan


Ethan Granger
Chief Technology Officer
4900 North Scottsdale Road, Suite 3000
Scottsdale, Arizona 85251
o|480.483.8100 egranger@landadvisors.com

[cid:LAO_Signature_ca1a909a-d387-4484-a62e-8227261b089b.png]<https://landadvisors.com/>

**Comment by mjbvz** [comment] 2019-06-04 20:35
Thanks. Closing this as caused by extension. Please file an issue / question against the extension that is causing this behavior

**Closed by mjbvz** 2019-06-04 20:35 UTC
Labels: needs more info
