### ISSUE TITLE
g++.exe: fatal error: no input files

### ISSUE THREAD

**Issue by heysujal** [microsoft/vscode#126161] opened 2021-06-13 07:59 UTC
- VS Code Version: 1.57.0
- OS Version: Windows 10
 

Steps to Reproduce:

1. Create any C++ file with space between words . For example: hello world.cpp
2. Run it using code runner.
3. Same file runs without any error if I remove space from the file name. For example hello_world.cpp or helloworld.cpp

Before(with space in file name):
![With spaces](https://user-images.githubusercontent.com/55016909/121799683-13b25580-cc4b-11eb-89a6-8e4cbf0e2941.png)

After (without space in file name):
![Without Spaces](https://user-images.githubusercontent.com/55016909/121799734-5aa04b00-cc4b-11eb-8e0b-384dc758d27a.png)

**Comment by yume-chan** [comment] 2021-06-16 09:17
Duplicate of formulahendry/vscode-code-runner#248

**Closed** 2021-07-06 21:39 UTC
