### ISSUE TITLE
Commenting out collapsed HTML text only comments 1st line

### ISSUE THREAD

**Issue by idevtech** [Microsoft/vscode#43791] opened 2018-02-15 23:40 UTC
### Issue Type
Bug

### Description

1. Enter a block of HTML where there is nesting, e.g., div.../div
2. Collapse block using "-" in sidebar
3. Highlight first line (only visible) of HTML
4. CTRL K+C to comment

Result: Only the first line is commented, not all the HTML that was collapsed and hidden.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz (2 x 2660)|
|Memory (System)|2.00GB (0.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|60%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.3
debugger-for-chrome|msj|4.1.0
vetur|oct|0.11.7
live-sass|rit|1.2.0
LiveServer|rit|3.2.0
html-css-class-completion|Zig|1.16.2

</details>
Reproduces without extensions

**Comment by aeschli** [comment] 2018-02-16 08:15
duplicate of https://github.com/Microsoft/vscode/issues/34388

**Closed by aeschli** 2018-02-16 08:15 UTC
Labels: editor, editor-contrib
