### ISSUE TITLE
VS freezing every five minutes on CSS file

### ISSUE THREAD

**Issue by ioma8** [Microsoft/vscode#11862] opened 2016-09-12 07:25 UTC
- VSCode Version:  1.5.1
- OS Version: Windows 7

My VS Code freezes on my computer every five minutes when working with larger CSS file (~100kb). Only way to resolve this is to run Windows Task Manager, kill whole VSC and then start again. This bug unfortunately makes VSC for me unusable, as it highly frustrates me having to restart my editor every 5 minutes, lose last position, recent changes in file etc. Might I help by providing some kind of log? Pleas give me instructions to help you if possible.

Steps to Reproduce:
1. Open CSS file of approc 100 kb in VSC
2. Keep working for about 5 minutes. Then VSC totally freezes. Cursor stops at position, window does not respond to any kind of input.

Yes, VSC after another 2 minutes show dialog "Keep waiting/reopen." However no matter which option I select, the apps keep being frozen. "Reopen button" only hides the dialog but does not restart the app. Has to be done throught Windows Task manager.

Note: the menu bar is responding when application is frozen. Only the editor part does not respond and cursor is stuck.

![image](https://cloud.githubusercontent.com/assets/6624752/18427772/84138292-78ca-11e6-8541-6907cc624236.png)

**Comment by Koarakuma** [comment] 2016-09-12 07:45
I concur with the issue! For me it is editing any file, even the user preferences file with no folder open. If I start writing something, it only takes like 10 seconds before the editor freezes completely. Menu bar is responsive but clicking on any options does nothing. Clicking on wait does not resolve the issue. Clicking on restart does nothing. Clicking on Close closes the App sucessfully.
Versión: 1.5.1
OS: Windows 7

**Comment by samspade** [comment] 2016-09-12 07:53
VSCode Version: 1.5.1
OS Version: Windows 7 Enterprise SP1

I came here to post the same thing. 

I'm working on 266KB file on a windows network folder. \\path\to\folder\file.css, but the same thing happens when editing on my C: drive. 

The editor halts, the menus are still accessible, but the majority (editor related, do not work). The Toggle Developer Tools is still available.

**Comment by ioma8** [comment] 2016-09-12 09:18
My suspiction is that it might have something to do with redrawing the colored preview boxes near color statements in CSS files, as in my exp they tend to be bugging few moments before the app freezes. Eg my screenshot in this issue.

**Comment by aeschli** [comment] 2016-09-13 10:29
I set the color decorator limit to 500 (no limit before, that was clearly a bug).
If you see this bug, can you check out task manager and see which process is running wild?
I'd need the command line parameters of that process (add the 'command line' column in the task manager).

**Comment by samspade** [comment] 2016-09-13 14:43
Hi Aeschli, 

I downloaded insiders and everything is working fine for me. I haven't had any hangs at all.

**Comment by aeschli** [comment] 2016-09-13 16:58
The change I made today will be in tomorrows insider build. If all works with the current, even better.

**Comment by ioma8** [comment] 2016-09-23 16:30
Still freezes,
aeschli, as requested I am sending "command line" dump from task manager when the editor is frozen.

Hope this gets solved soon. :(

![vs_freeze](https://cloud.githubusercontent.com/assets/6624752/18793609/cedac7d2-81bb-11e6-992f-7660faf97b19.png)

**Comment by ioma8** [comment] 2016-10-08 09:17
Hello. The freezing still happens and this makes me unable to use this piece of software even thought I would love to! I am very saddened. Please can something be done about this?
I am attaching process manager screenshot of Code to help you with solving this.

![error1](https://cloud.githubusercontent.com/assets/6624752/19211968/db7bc688-8d48-11e6-997d-4c681d9b52b0.png)
![error2](https://cloud.githubusercontent.com/assets/6624752/19211967/db7a63f6-8d48-11e6-8151-77f3fee9a76e.png)

**Comment by aeschli** [comment] 2017-02-21 09:50
I think we found the issue, thank to everyone for being patient. It would be great if you could verify the fix in the latest [insiders](https://code.visualstudio.com/insiders) build.

Closing as duplicate of #19840

**Closed by aeschli** 2017-02-21 09:50 UTC
Labels: freeze-slow-crash
