### ISSUE TITLE
[A11y] Keyboard focus is not automatically moved to toast notification

### ISSUE THREAD

**Issue by Benjin** [microsoft/vscode#81786] opened 2019-10-01 17:46 UTC
Environment Details:
Application Name: Visual Studio Code
Application Version: 1.38.1 (user setup)
Commit: b37e54
Electron: 4.2.10
Node.js: 10.11.0
OS: Windows_NT x64 10.0.18362

Repro steps:
1. Go to Extensions
2. Pick any ol' extension (confirmed on Java Extension Pack)
3. Use keyboard to select "Install" button
4. Hit <Enter> on keyboard

Expectation:
Keyboard focus is moved to the resulting toast, allowing me to dismiss or take action.

Reality:
Keyboard focus stays in the main editor window, where it was before.  Difficult or impossible to tab to the resulting toast.

**Comment by isidorn** [comment] 2019-10-02 08:31
Assignign to next milestone to investigate then.

**Comment by isidorn** [comment] 2019-10-25 09:54
I just tried this out and I disagree.
Notificatinos are something that is in the background and they should definentely not steal focus.

If every notification was stealing focus, then the user can be distributed all the time by random spam notifications from extensions. And this would lead to a very bad exeperience.

I am closing this as caused by extension and my recommendation is that the Java Extension Pack should use a modal dialog, and not a notificatino if the extension wants to focus to be switched to that and the user to be interupted.
I hope this makes sense, but all the API is there and it is up to the extension to decide which dialog should steal focus (use modal) and which not (use notifications)

**Closed** 2019-10-25 09:54 UTC
Labels: *caused-by-extension, accessibility, under-discussion, workbench-notifications
