### ISSUE TITLE
Remote debugging: Breakpoints ignored, they are "set but not bound"

### ISSUE THREAD

**Issue by KerimG** [Microsoft/vscode#53961] opened 2018-07-10 13:20 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10
- Node version on remote host: 8.11.3
- Node version on local host: 8.11.1

Steps to Reproduce:

1. Start node debug session on remote host with ``node --inspect-brk=9229 index``
2. Attach to remote debug session with VS Code via the following debug configuration
```JavaScript
{
      "type": "node",
      "request": "attach",
      "protocol": "inspector",
      "name": "Attach to Remote",
      "address": "192.168.1.201",
      "stopOnEntry": false,
      "port": 9229,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/home/kerimg/code",
      "sourceMaps": true
    }
```
3. Once attached, set breakpoint
4. Breakpoint looks like a gray ring instead of a red dot
5. Continue execution (F5)
6. Breakpoint is ignored.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment] 2018-07-10 13:38
duplicate of #53785

**Closed** 2018-07-10 13:39 UTC
Labels: *duplicate, debug
