### ISSUE TITLE
VS Code main window is blank in version 1.27.0

### ISSUE THREAD

**Issue by vndevil** [Microsoft/vscode#58093] opened 2018-09-06 16:32 UTC
- VSCode Version: 1.27.0
- VSCode Insiders Version: 1.27.0
- OS Version: Windows 8.1

I was update Visual Studio Code from 1.26 to 1.27.0 and have error blank when open VS Code. I was try some way to resolve this issue but it didn't working:

1. Uninstall VS Code and reinstall version 1.27.0
2. Setting the compatibility with windows 8 in VsCODE shortcut.
3. Right-click on Shortcut and add --disable-gpu to Target: "C:\Program Files\Microsoft VS Code\Code.exe" --disable-gpu
4. Does this issue occur when all extensions are disabled?: Yes

[https://i.stack.imgur.com/ypvtC.jpg](url)
[https://i.imgur.com/eU282KY.jpg](url)

Is there some way to fix this issue??
Thanks

**Comment by KamranMackey** [comment] 2018-09-06 16:42
Your issue's already been fixed in the 1.27.1 patch release, so update to that.

**Comment by mjbvz** [comment] 2018-09-06 16:59
Duplicate of #57982. Should be fixed in recovery build

**Closed by mjbvz** 2018-09-06 16:59 UTC
