### ISSUE TITLE
vscode 1.56 breaks extension sftp

### ISSUE THREAD

**Issue by mguptawork** [microsoft/vscode#123834] opened 2021-05-14 00:37 UTC
Does this issue occur when all extensions are disabled?: Yes/No - It's an error in the extension sftp due to the upgrade.

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install sftp plugin by liximomo (It's the most popular sftp plugin)
2. uploading a file from your local machine to the remote machine throws an error. It says local file not found, even if it's successfully uploaded.
3. Multiple users are facing this issue:
    1. https://github.com/liximomo/vscode-sftp/issues/915
    2. https://stackoverflow.com/questions/67506693/vscode-error-no-such-file-sftp-liximomo-extension/67524099#67524099

**Comment by gjsjohnmurray** [comment] 2021-05-14 04:55
/duplicate of #122325

1.56 shipped a newer version of nodejs. IMO the extension author needs to fix this or someone needs to fork and fix it there.

**Closed** 2021-05-14 04:55 UTC
Labels: *duplicate, new release
