### ISSUE TITLE
"Select All Occurrences" is not selecting all of matches in large files (stops at 1000)

### ISSUE THREAD

**Issue by FrenchBen** [Microsoft/vscode#7201] opened 2016-06-03 23:44 UTC
- VSCode Version: 1.1.1
- OS Version: 10.11.4

Steps to Reproduce:
1. Open a 3MB file with some repeating text at each line (`The quick brown fox jumps over the lazy dog`
2. Highlight a word such as `quick`
3. Do a multi-cursor select (CMD+SHIFT+L)
4. Edit `quick` to say `slow`
5. Notice that not all lines were changed :( (stops at line 999 of a 35,397 line file)

**Comment by russgalloway** [comment] 2017-04-07 20:14
I've been experiencing the same.  I think I noticed it in past verions, but recently needed to do this again several times while throwing together some quick and dirty mock data and am seeing the same behavior at exatly 1000 cursors.

- VSCode Version: 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39 2017-04-06T13:57:52.556Z)
- OS Version: OS X El Cap 10.11.6

Steps to Reproduce:

Open a file like...
https://gist.githubusercontent.com/russgalloway/9345f5365bb5101d3c81c4902922c5d9/raw/f1787e73cbab7d4cef2726aa1da8fa0cf4dea6e4/vscode-multicursor-1000-cursors-issue-sample-data.json
...that has something you can match with (to repro this exactly) 1000 cursors.

Say, for instance, I wanted to update all the JSON objects in an array all at once by replacing `key` with `id` ...

1. Place your cursor inside one of the `"key"` strings, press `CMD`+`D` to select the whole word `key`
1. Press `CMD`+`F` to search the current document
1. Press `ALT`+`ENTER` to select all instances of `key`
1. Cursor to the beginning of `key`, hold `SHIFT` and cursor right 3 times to select all characters in all instances of `key`
1. Type `i` then `d`

At first all instances of `key` are changed to `i`, but the first cursor is removed, leaving 999 cursors remaining with all the `i`s that were typed selected
When `d` is typed, the lower 999 `i`s are changed to `d`

Since the first cursor was removed leaving 999, you can continue to type without a problem.

**Comment by PunchyRascal** [comment] 2017-07-12 13:42
I am not sure if my problem is related, but a very similar issue exists with regular serach&replace (Ctrl+H). 
- 'replace all' doesn't do anything
- 'single replace' replaces an occurrence not highlighted by the search (first 1000 occurrences)

**Comment by ToMakeSense** [comment] 2017-08-10 16:49
[ #496](https://github.com/Microsoft/vscode/issues/496)

**Comment by Mischala** [comment] 2017-08-30 21:59
Line 173 of [findModel.ts](https://github.com/Microsoft/vscode/blob/e070afceabc88e57190697c9a79dc3ab3a98d3d5/src/vs/editor/contrib/find/common/findModel.ts) references a "MATCHES_LIMIT",  that is a constant, set on line 70 of the same file.

This appears to be the root of the problem...
I'm currently at work, but when I get home i'll play with this constant.
I expect the reason this limit exists is to stop "Bad Searches"  like searching for "s" or whitespace from running forever and locking up the app.

**Comment by alexandrudima** [comment] 2017-09-28 09:56
Duplicate of #5887

**Closed by alexandrudima** 2017-09-28 09:56 UTC
Labels: editor-1000-limit, editor-core, editor-multicursor, feature-request
