### ISSUE TITLE
Wrong path is set in workspaceFolder variable

### ISSUE THREAD

**Issue by SPRESENSE** [microsoft/vscode#144827] opened 2022-03-10 10:18 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.1
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Create a workspace with 2 folders
2. Add same task.json file (Details of task.json file is described in Detail section) to multiple folders
3. Run task and check output

**Detail description**
It seems that the `workspaceFolder` variable has been set to the wrong path since VSCode version 1.65.x.
My workspace contains two folders(folder1, folder2), each with the exact same task.json file that consists of the following task.json file.

<pre>
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Task1",
            "type": "shell",
            "dependsOrder": "sequence",
            "dependsOn": [
                "Task2" 
            ],
            "command": "echo task1 ${workspaceFolder}" 
        },
        {
            "label": "Task2",
            "type": "shell",
            "command": "echo task2 ${workspaceFolder}" 
        }
    ]
}
</pre>
With this task configuration, when Task1, the task for folder2, is executed, the `workspaceFolder` is displayed as `folder1`, as shown in the following image.
![VSCode_Version1 65 1](https://user-images.githubusercontent.com/41312067/157639013-4666c69c-2823-4475-a399-03618cedaa63.png)

Prior to Versoin 1.64.2, `folder2` was displayed as `workspaceFolder` as expected as shown in the following image.
![VSCode_Version1 64 2](https://user-images.githubusercontent.com/41312067/157639165-be89370a-83ad-4fb3-84cd-0c2e68f213c8.png)

I think this is happening when a task with the same name is defined in task.json in multiple folders, and it is specified as "dependsOn".

I would like to manage and use the same task.json file in multiple folders, so could you please revert to the behavior as in version 1.64.2?

**Comment by alexr00** [comment] 2022-03-10 13:48
duplicate of https://github.com/microsoft/vscode/issues/144761

**Closed by alexr00** 2022-03-10 13:48 UTC
Labels: new release
