### ISSUE TITLE
Add API to find out if an extension is being debugged or not

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#19034] opened 2017-01-23 15:04 UTC
An extension can find out if it runs in debug mode by analysing the arguments passed to node:
```js
const debug = process.execArgv.filter(v => v.indexOf('--debug') === 0).length > 0;
```

It would be nice to have a real API for this. 

/cc @dbaeumer @daviwil @jrieken

**Comment by bpasero** [comment] 2017-01-23 15:28
@weinand would that be https://github.com/Microsoft/vscode/issues/10272 ?

**Comment by daviwil** [comment] 2017-01-23 15:36
The `vscode.env.sessionId` workaround definitely works in my case because I need to know when I'm in "development mode" regardless of whether being debugged or not.  However, might still be nice to have some official API which gives us that info and also allows us to distinguish between being debugged or not.

**Comment by daviwil** [comment] 2017-01-23 15:38
Also would be nice to know if it was my extension being replaced by `--extensionDevelopmentPath` so that I don't change my behavior if I'm not working with my own local extension build.

**Comment by connor4312** [comment] 2020-05-06 18:52
Depending on the exact scenario, the API in https://github.com/microsoft/vscode/issues/95926 may solve this issue. It tells the extension whether it's in development mode, but this does not necessarily mean it's being debugged (you can run tests and use the --extensionDevelopmentPath without having a debugger attached).

**Comment by connor4312** [comment] 2020-09-08 19:14
Closing as a dupe of the linked proposal, which is now implemented. Please let me know if that doesn't work for you.

**Closed** 2020-09-08 19:14 UTC
Labels: *duplicate, api, debug, feature-request
