### ISSUE TITLE
Show whitespace differences button does nothing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142198] opened 2022-02-04 14:51 UTC
![Recording 2022-02-04 at 06 51 01](https://user-images.githubusercontent.com/2193314/152549581-28272a95-80ca-46f2-b1c6-4519df44365a.gif)

**Comment by alexdima** [comment] 2022-02-24 19:34
Duplicate of https://github.com/microsoft/vscode/issues/136971

**Closed by alexdima** 2022-02-24 19:34 UTC
