### ISSUE TITLE
[PHP] 0.10.8 refactor, variable heightlights and code intelligence

### ISSUE THREAD

**Issue by bingzheyuan** [Microsoft/vscode#2828] opened 2016-02-09 08:53 UTC
1. Variables are not hightlighted(dark theme) and code intelligence is not triggered for local variable, they were fine in 0.10.6
2. Variable refactor is broken, it now affects variable with same starting string. It was fine in 0.10.6 <br/>
![refactor](https://cloud.githubusercontent.com/assets/5099742/12911333/1aa1d230-cf12-11e5-86a1-85b36d05d24d.JPG)
3. Variable selection still includes the trailing "-", as I recall there's a fix for that. <br/>
![selection](https://cloud.githubusercontent.com/assets/5099742/12911396/aa54955c-cf12-11e5-95b8-9ce926c3b208.JPG)<br/>
I am working on Win7 x64.

**Comment by Morgy93** [comment] 2016-02-09 10:45
Was just about to post the same thing for php variable highlighting on Dark (Visual Studio) theme. It worked with the previous version.

**Comment by aeschli** [comment] 2016-02-09 11:54
(1.) By design, the Dark (Visual Studio) theme only has a very few colors. I fixed that and had to remove the color for variable. If you like the color, use the new Dark+ default theme.

Code assist seems to work from me. I used this example
```php
<?php

public function demo{
    $variable1 = 9;
    $variableB->C = 9;
    assert($variable11);
}
>
```
(2.) You are right, I have to investigate
(3.) This got fixed for February

**Comment by chiangf** [comment] 2016-02-09 19:57
I think (2) happens on javascript as well (so it might be for all languages)

**Comment by bingzheyuan** [comment] 2016-02-10 08:06
Is it also possible that we keep variable refactor within the function scope instead of the whole file?

**Comment by aeschli** [comment] 2016-02-10 08:48
@bingzheyuan You are asking for deeper PHP support with real language understanding. It's not something we, the core VS Code team, will be able to provide. We lack deeper PHP knowledge and the resources. We are actually hoping someone from the community would be interested of implementing a more sophisticated PHP extension.

**Comment by bobmajdakjr** [comment] 2016-02-10 09:54
yall need to assign a new guy to this. aeschli is fighting for some reason. closed another report I opened claiming its not true even when I had before and after screenshots.

**Comment by bobmajdakjr** [comment] 2016-02-19 21:18
the screenshots from the closed thread.

before:

![31b9d640-cf3d-11e5-87f5-96d6fdf70fa5](https://cloud.githubusercontent.com/assets/881944/13189241/c8d3852c-d71b-11e5-816b-fc714823f6c3.PNG)

after:

![c47d4910-cf3a-11e5-9aff-ac090974fbe5](https://cloud.githubusercontent.com/assets/881944/13189245/cf76e1bc-d71b-11e5-831e-8960327426cf.PNG)

i have a few machines i keep refusing to update now because the Dark Not Plus changed >_>

when it comes to visual assets like themes, you shouldn't just change them ever. you should only ever add new ones or fix bugs. not remove features.

**Comment by aeschli** [comment] 2016-02-22 13:38
@bobmajdakjr Bod, did you try switching to the Dark+ theme? It's FIle > Preferences > Color Theme.

**Comment by bobmajdakjr** [comment] 2016-02-26 01:42
yes dark+ works as intended. what i'm qqing about is having broke dark not plus instead of just adding dark+ and leaving the previous alone.

**Comment by aeschli** [comment] 2016-02-26 07:53
https://code.visualstudio.com/Updates#_editor tries to explain the motivation behind the changes. Sorry for back and forth in the recent months, but we hope we now have a solution for both classic VS users as well as users that the classic VS theme is too limited. And there's always lots of other themes to pick from.

**Comment by bingzheyuan** [comment] 2016-03-14 09:04
Tested again on version 0.10.10, code intelligence is still not triggered for local variables.
![0 10 10](https://cloud.githubusercontent.com/assets/5099742/13739558/2177025e-e9cc-11e5-98a9-f3f48e9d58ce.gif)

**Comment by aeschli** [comment] 2016-03-17 10:35
I looked at (2)
For PHP we offer only 'Change All Occurrences' which looks at the current selection and finds occurrences based on the current settings of the 'Find' widget. It's basically find/replace, without the find widget.
If you want to replace only full words, then you have to open the find widget and check the 'whole words' settings. That setting is persistent and then also 'Change All Occurrences' with follow this setting. There's also a keybinding shortcut (Alt+w) to toggle that while word settings without the need to open the find widget 
Some other languages have a real 'rename symbol' support. We don't have that for PHP. 

I'm closing this issue: (1) is expected, it has to do with the design of our themes: Use the Dark plus themes if you like variable highlighting
(3) got fixed a while ago.

**Closed by aeschli** 2016-03-17 10:35 UTC
Labels: php

**Comment by bingzheyuan** [comment] 2016-03-18 08:14
@aeschli how about the code intelligence problem in the last reply? It was fine in v0.10.6 and get lost since v0.10.8.

**Comment by Morgy93** [comment] 2016-03-18 08:38
@bingzheyuan You need to adjust this little setting to make it work again: https://github.com/Microsoft/vscode/issues/4355#issuecomment-197921835

**Comment by aeschli** [comment] 2016-03-18 10:28
The variables intellisense issue is #3815. It will be fixed in the March release.

**Comment by bingzheyuan** [comment] 2016-03-21 08:32
@Morgy93 That wasn't my question but your comment is very helpful as well, thanks.
@aeschli OK, then no more problem about this issue now, thanks for the great work.
