### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by sshanzel** [microsoft/vscode#88346] opened 2020-01-09 08:45 UTC
We have written the needed data into you
Issue Type: <b>Bug</b>

I'm working now in a React App which i haven't been doing for quite some time. Now intelli-sense doesn't work for it. The File Association is JavaScript React. I've tried removing all the extensions, then add one by one, es6 snippets, etc. Still nothing happens. I've tried re-installing VS Code but no luck. 

This is a fresh project using CRA. I've opened my different projects, it just doesn't work on my React Projects. A simple Vanilla JS Project works perfectly fine.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (13.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
node-snippets|chr|1.0.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.0.13
es7-react-js-snippets|dsz|2.5.0
prettier-vscode|esb|3.18.0
vscode-azureappservice|ms-|0.16.2
azure-account|ms-|0.8.8
debugger-for-chrome|msj|4.12.4
LiveServer|rit|5.6.1
autoimport|ste|1.5.3

</details>

**Reverting back to 1.40.2 has worked for me temporarily. Disabled auto-updates.**

**Comment by mjbvz** [comment] 2020-01-09 22:17
Where is your code stored? Somewhere besides the `c:` drive?

**Comment by sshanzel** [comment] 2020-01-09 23:21
It resides in a different drive. Specifically `D:` while the VS Code is at `C:` drive.

**Comment by mjbvz** [comment] 2020-01-09 23:27
Duplicate of https://github.com/microsoft/TypeScript/issues/35512

To workaround this, upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2020-01-09 23:27 UTC
Labels: javascript, needs more info

**Comment by sshanzel** [comment] 2020-01-09 23:30
Yeah based from what i have observed it runs a process endlessly some for initializing and some is updating, both are for ts and js things. Thanks a lot for the feedback. Will try the work around later and give some info if something comes up.

**Comment by sshanzel** [comment] 2020-01-12 04:52
It worked! Thanks!
