### ISSUE TITLE
Signature help pop up persist on screen after move cursor to new line and they are duplicated.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#39959] opened 2017-12-09 11:55 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.3.9600
                      Windows 8.1 & Linux Ubuntu 16.04 Gnome 3
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.3

---

Steps to Reproduce:

1. npm install electron, jquery and angular@1.6.6
2. create main.js, write code from https://electronjs.org/docs/tutorial/quick-start , when you are writing loadURL section, sometimes tooltips persist on screen after move cursor to new line.

Reproduces without extensions: Yes

- [x] signature help persist after move cursor to new line

- [ ] signature helps are duplicated

**Comment by ramya-rao-a** [comment] 2017-12-11 19:42
Please provide screenshots

**Comment by Mlocik97-issues** [comment] 2017-12-12 11:03
![screenshot_27](https://user-images.githubusercontent.com/31345346/33881219-659bf1b0-df34-11e7-842a-9fd53b632cea.png)
![screenshot_28](https://user-images.githubusercontent.com/31345346/33881220-65bd8ec4-df34-11e7-8232-0f289163c78d.png)
![screenshot_29](https://user-images.githubusercontent.com/31345346/33881221-65dd718a-df34-11e7-953b-4618af646be7.png)
![screenshot_30](https://user-images.githubusercontent.com/31345346/33881222-65fd794e-df34-11e7-89f0-ba2f7e05d541.png)

**Comment by Mlocik97-issues** [comment] 2017-12-12 11:05
Also more tooltips overlaps

**Comment by ramya-rao-a** [comment] 2017-12-12 19:00
@Mlocik97-issues  The overlap between the suggestion widget and the signature help widget is covered in #32511

@joaomoreno This issue is about the Signature help persisting in the new line

**Comment by Mlocik97-issues** [comment] 2017-12-12 19:12
and also, tooltips are duplicated (2x)
![screenshot_39](https://user-images.githubusercontent.com/31345346/33903465-c23966ca-df78-11e7-8fb5-ae615f60ceed.png)
![screenshot_40](https://user-images.githubusercontent.com/31345346/33903467-c25bb950-df78-11e7-931a-13dbe3058410.png)

1/2 is the same as 2/2



On pictures up, are 1/4 and 3/4 the same,.. and 2/4 and 4/4 are the same.

**Comment by ramya-rao-a** [comment] 2017-12-12 19:33
`join` takes in any number of paths. So no matter how many parameters you enter, the signature help will say the same thing. That is as designed

**Comment by Mlocik97-issues** [comment] 2017-12-12 19:38
n, I think, if you press ↓ on second slide is written the same text as on first slide. And it's useless.

**Comment by ramya-rao-a** [comment] 2017-12-12 19:55
cc @mjbvz for the actual contents of the signature help

**Comment by joaomoreno** [comment] 2017-12-13 09:12
> @joaomoreno This issue is about the Signature help persisting in the new line

This is as designed. The [API](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2696) lets each language decide what happens when the cursor changes.

**Comment by mjbvz** [comment] 2017-12-13 19:19
Yes, the signature help persistence is by-design

@Mlocik97-issues Can you please run `Peek definition` on `join` in `path.join`. I suspect we are pulling in two definitions from somewhere

**Comment by Mlocik97-issues** [comment] 2017-12-13 21:25
![screenshot_46](https://user-images.githubusercontent.com/31345346/33963232-8bdf2bb4-e054-11e7-9a38-db35d2c9e23c.png)
![screenshot_47](https://user-images.githubusercontent.com/31345346/33963233-8c020080-e054-11e7-8268-412e8a6741b9.png)
![screenshot_48](https://user-images.githubusercontent.com/31345346/33963234-8c25ccf4-e054-11e7-9f28-066f0eb723f2.png)
![screenshot_49](https://user-images.githubusercontent.com/31345346/33963235-8c49c6ea-e054-11e7-858b-3daf44e6ecd6.png)

**Comment by mjbvz** [comment] 2018-04-17 22:55
I believe this is a a duplicate of https://github.com/Microsoft/TypeScript/issues/22106 which itself was closed as a duplicate of https://github.com/Microsoft/TypeScript/issues/1150

Closing as upstream

**Closed by mjbvz** 2018-04-17 22:55 UTC
Labels: typescript, upstream
