### ISSUE TITLE
Getting started actions should account for actions from the UI

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#118274] opened 2021-03-05 23:27 UTC
![image](https://user-images.githubusercontent.com/35271042/110185392-0faea600-7dc7-11eb-960b-26d77164eb59.png)

1. Create codespace
2. Terminal is open by default
3. Navigate to "Ports" view
4. 🐛  Getting started displays the "view ports" step as incomplete

I didn't use any commands and the "port" view was already moved into my panel. Also, I had already ran actions in the terminal as well so that step should checked.

fyi @digitarald

**Comment by JacksonKearl** [comment] 2021-03-29 18:57
It only checks off by running the command right now, so if you open it from the UI it wont (but if you use the keybinding it should). Since we now support manually clicking the item to check it off do you think we need to also have a way to listen in to clicks for automated checking off?

**Comment by misolori** [comment] 2021-03-29 19:50
Ideally it would check off no matter what route you take, that gives you a nice overall experience. When I went through this step, it felt like a bug that it wasn't checked after I navigated to it.

**Comment by digitarald** [comment] 2021-03-30 03:41
In cases where the UI is already visible I also thought to use `when` clauses to hide the task. The buttons for those cases will always be a bit awkward, as the click will not have any visible reaction; and the user already has found the UI without help from the walkthrough.

Alternatively, a task could also highlight a related UI element; something we discussed in the past that makes it easier to use walkthroughs for UI tours.

**Comment by misolori** [comment] 2021-03-30 04:18
I don't think we want to hide items when they are visible, in my case the terminal was already open and then I clicked on the "Ports" panel. It's more about providing different avenues for the user to complete the task.

**Comment by digitarald** [comment] 2021-03-30 04:22
Right, I was mixing up issues here! Agreed that these kind of UI tasks should still be checked off even when not using the given command.

**Comment by misolori** [comment] 2021-03-30 04:36
Created https://github.com/microsoft/vscode/issues/120147 to track exploring hints, with I discussed with Kai today

**Comment by JacksonKearl** [comment] 2021-05-04 01:56
Duplicate of #122570

**Closed by JacksonKearl** 2021-05-04 01:56 UTC
Labels: bug, getting-started, under-discussion
