### ISSUE TITLE
Can't run as different user unless installing system version

### ISSUE THREAD

**Issue by andrefecto** [microsoft/vscode#67553] opened 2019-01-30 15:04 UTC
- VSCode Version: 1.30.2
- OS Version: Windows 10, 1803 and Windows 10 1809

Steps to Reproduce:

1. Shift+Right Click on VSCode 
2. Click "Run As Different User" (The UAC Prompt will not show as it's supposed to.)

Does this issue occur when all extensions are disabled?: Yes

I ran this on my normal laptop, running Windows 10 1809. Uninstalled VSCode and deleted all related files about 5 times thinking it was me. Finally ran it on my admin jump box which is running Windows 10 1803 and never had VSCode installed on it. I downloaded the newest version from the website and it still doesn't work. I can run all other programs as a different user just fine, that's why I think it's a VSCode bug.

EDIT: Also just tested and can't even click "Run As Administrator"

EDIT 2: Also tested forcing the runas through powershell window and it doesn't launch as the desired user. Command was:  `runas /netonly /user:<desired_Username_Here> "C:\Users\<current_user_name_here>\AppData\Local\Programs\Microsoft VS Code\Code.exe"`

**Comment by bpasero** [comment] 2019-01-31 13:33
Without any logs this will be hard to track down.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by andrefecto** [comment] 2019-01-31 13:39
@bpasero are you not able to reproduce this on your side? I was even just able to reproduce this by creating a local account on my computer and doing runas with that account. I can launch all other programs as this local user just fine but VSCode does not give you the prompt.

**Comment by bpasero** [comment] 2019-01-31 14:48
Ok so this seems to be related to installing on system vs user level.

**Comment by mevin-e** [comment] 2019-09-22 19:08
Got the same issue

**Comment by joshgrib** [comment] 2020-02-05 15:00
I also have this issue, I was able to get around it on Windows by giving the second account full control of everything in my `Users` folder. Not an ideal solution but I was trying to use a second account of mine with elevated domain permissions, so it works for this use case

**Comment by andrefecto** [comment] 2020-02-05 15:05
> 
> 
> I also have this issue, I was able to get around it on Windows by giving the second account full control of everything in my `Users` folder. Not an ideal solution but I was trying to use a second account of mine with elevated domain permissions, so it works for this use case

I got around this by installing the system version of VSCode rather than the user version. Give that a try so you don't have to give your other user full control of all users.

**Comment by joshgrib** [comment] 2020-02-05 16:25
@andrefecto Sorry I meant the folder for my account within the `Users` folder, so it shouldn't affect any other users (it's still just me on this machine though)

**Comment by deepak1556** [comment] 2020-04-21 00:29
This is an issue with chromium that is fixed internally, there is a backport in progress https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/211032?_a=overview

**Comment by mammuthus** [comment] 2020-09-23 09:02
Could you share a solution please? The same issue. Link is not available for me (access denied)

**Comment by rndadhdman** [comment] 2020-10-20 13:50
I had this same problem today after the 2004 update. I had to reinstall to resolve. Version 1.50

**Comment by mammuthus** [comment] 2021-12-21 16:57
Same issue on the latest stable 1.63.2. Reinstalling as system version didn't help.

**Comment by deepak1556** [comment] 2022-12-12 14:28
Fix mentioned in https://github.com/microsoft/vscode/issues/67553#issuecomment-616879764 is only for de-elevating when application is started as admin to support sandbox scenarios. It is unrelated to this issue.

This issue is technical limitation on the chromium runtime given how its user data directory is laid out in the User profile. Closing as `out-of-scope` and system installer is the solution for these scenarios.

**Closed by deepak1556** 2022-12-12 14:28 UTC
Labels: bug, install-update, windows, upstream-issue-fixed, chromium
