### ISSUE TITLE
Code Outline : a exportDefaultExpression does't show outline properly

### ISSUE THREAD

**Issue by IWANABETHATGUY** [microsoft/vscode#95100] opened 2020-04-13 08:32 UTC
- VSCode Version:1.44.0
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 18.7.0

Steps to Reproduce:

1. use vscode inter typescript version which is 3.8.3
2. open a test.js file , and input code as below
```js
export default {
  a: 'string',
  b: 2,
  c () {
    
  }
}
```
3. a exportExpression outline is looks like
![image](https://user-images.githubusercontent.com/17974631/79105445-3e80ef80-7da3-11ea-855d-041b849de004.png)

when i change  the typescript version to `3.7.5`
the outline show below, i think this may be better, but i am not sure if this is a typescript bug or vscode's.
![image](https://user-images.githubusercontent.com/17974631/79105368-185b4f80-7da3-11ea-98fb-027222312055.png)
`大纲` is outline

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-04-13 19:34
Duplicate of https://github.com/microsoft/TypeScript/issues/37877

**Closed by mjbvz** 2020-04-13 19:34 UTC
