### ISSUE TITLE
When trying to autocomplete styled-components, vscode loads cpu and refuses to prompt

### ISSUE THREAD

**Issue by hazratgs** [Microsoft/vscode#71794] opened 2019-04-05 11:56 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:
Just see the vscode behavior: https://www.youtube.com/watch?v=75o7zWyB0rk&feature=youtu.be

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment] 2019-04-05 14:32
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by mjbvz** [comment] 2019-04-05 19:08
Duplicate of #71751 

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for possible workarounds

If that doesn't solve the issue for you, please open a new issue

**Closed by mjbvz** 2019-04-05 19:08 UTC
Labels: extensions, needs more info
