### ISSUE TITLE
Stuck sometimes in Windows 10

### ISSUE THREAD

**Issue by Yahampath** [Microsoft/vscode#37634] opened 2017-11-04 03:57 UTC
I'm using VS Code for Laravel projects. Sometimes VS Code stuck for no reason and take a wile for resume. Im sure RAM isn't a problem.

I guess this happen after new release.

- 1.17.2
- Windows 10 Pro

Steps to Reproduce:

1. Open too many tabs
2. Minimize or go to browser or something.
3. Maximize VS Code. 

No

**Comment by bpasero** [comment] 2017-11-06 14:26
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2017-11-15 18:21
Any update?

**Comment by Yahampath** [comment] 2017-11-16 07:25
@bpasero Yes. i guess that happen because phpcs plugin. because when we don't close or restart vs for a while. phpcs not working properly.

**Comment by Yahampath** [comment] 2017-11-16 08:16
@bpasero Nop. I tried several times. but it doesn't  reproduce.

**Comment by bpasero** [comment] 2017-11-16 10:10
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2017-11-16 10:10 UTC
Labels: bug, freeze-slow-crash
