### ISSUE TITLE
Font Size palava

### ISSUE THREAD

**Issue by zeecaptchaatyou** [microsoft/vscode#171455] opened 2023-01-17 01:06 UTC
Type: <b>Performance Issue</b>

I can't increase the font size of the extentions panel beside the editor. Each time I try to increase it,my laptop's fon't size keeps increasing. I have tried re-installation and worked around the settings. Nothing seems to work and I've never been so frustrated.
![image](https://user-images.githubusercontent.com/118500314/212787834-dcc273ed-fadf-4036-b048-8b1417cd0fc1.png)

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.15.0-57-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.65GB (2.00GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9ddbf590-be6a-49db-9d9f-614f313056d4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   164	 11615	code main
    0	    47	 11620	   zygote
    0	   117	 11652	     gpu-process
    0	    47	 11621	   zygote
    0	     8	 11623	     zygote
    1	    86	 14602	       issue-reporter
    0	    63	 11666	   utility-network-service
    0	   251	 11687	   window (Settings - Projects - Visual Studio Code)
    0	   149	 11723	   shared-process
    0	    70	 11748	     ptyHost
    0	    70	 11784	     fileWatcher
    0	     0	 14795	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 14796	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   149	 11735	   extensionHost
    0	   110	 11855	     /usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/06991db0c061142234bf/tscancellation-b04ddd42657ecf37c8ed.tmp* --globalPlugins @vsintellicode/typescript-intellicode-plugin,ms-vsintellicode-typescript --pluginProbeLocations /home/zeecaptcha/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.30,/home/zeecaptcha/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.30 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	   117	 11856	     /usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/06991db0c061142234bf/tscancellation-7b4ebe3834a612470ae7.tmp* --globalPlugins @vsintellicode/typescript-intellicode-plugin,ms-vsintellicode-typescript --pluginProbeLocations /home/zeecaptcha/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.30,/home/zeecaptcha/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.30 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    86	 11885	       /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/zeecaptcha/.cache/typescript/4.9 --enableTelemetry --typesMapLocation /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	    78	 12695	     /usr/share/code/code --ms-enable-electron-run-as-node /home/zeecaptcha/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.6/dist/server/server.js --node-ipc --clientProcessId=11735
    0	   110	 13665	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=11735
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - Projects - Visual Studio Code)
|    Folder (Projects): 9 files
|      File types: html(4) json(1) css(1) js(1)
|      Conf files: launch.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.7.0
vscode-django|bat|1.10.0
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
html-snippets|gey|0.2.3
vscode-picture|Jak|1.0.0
vsc-python-indent|Kev|1.18.0
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
azure-dev|ms-|0.3.0
vscode-azureappservice|ms-|0.24.5
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
vscode-azurestorage|ms-|0.15.0
vscode-azurevirtualmachines|ms-|0.6.2
vscode-cosmosdb|ms-|0.19.2
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.2
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2023.1.917
vscode-node-azure-pack|ms-|1.1.1
autodocstring|njp|0.6.1
java|red|1.13.0
html5-boilerplate|sid|1.1.1
ejs-snippets|Tao|0.1.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.3
HTML5-extension-pack|wal|1.0.0
jinja|who|0.0.8
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
f6dab269:30613381
fim-prod:30623723

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment] 2023-01-17 16:16
Duplicate of #168336

**Closed by mjbvz** 2023-01-17 16:16 UTC
Labels: triage-needed
