### ISSUE TITLE
Slow scrolling and general usability

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9517] opened 2016-07-20 05:29 UTC
From @juol in #9197

VSC 1.3.1
OS X 10.10.3

Very slow scrolling and general usability.
All extensions uninstalled.

The slow down is most noticeable in the editor window. Scrolling and moving the caret as well as any selection operations.

When the 1.3.1 update came through the other day the update bar at the top of the editor window stuttered and scrolled down in a few jerky steps.

Expanding a file tree of moderate size is also slow.

It has this behavior regardless of what directory or project I open.

Love VSC and this slow down seems to be pretty rare.
Keep up the great work guys!

Thanks.

**Comment by sandy081** [comment] 2016-07-20 05:31
@jrieken Assigning this to you since @alexandrudima is on vacation.

**Comment by jrieken** [comment] 2016-07-20 07:47
It sounds like an issue with a text mate grammar.. @juol Does this happen in a special file, like a special JavaScript files or all TypeScript files, or does this happen with all sort of files?

**Comment by janhartmann** [comment] 2016-07-20 08:14
I just recently experienced very bad performance with scrolling and navigating between files. Almost so much I might be using another editor soon. :-)

Version: 1.4.0-insider
Date: 2016-07-20

**Comment by jrieken** [comment] 2016-07-20 08:17
@janhartmann [Same question](https://github.com/Microsoft/vscode/issues/9517#issuecomment-233870425) for you

**Comment by janhartmann** [comment] 2016-07-20 08:22
Oh, sorry - I just did a quick Google search for performance problems in VSCode and did not notice your comment.

I am working with JavaScript (ES6) files (.js) files - currently working with file approx. 180 lines long. 

Let me know if you need any more information.

**Comment by janhartmann** [comment] 2016-07-20 08:24
I just noticed that the performance is fine after a save, but after having written more than 10-20 characters (intellisense popping up), removing text, etc. performance slows down greatly. I can try record a video if you need.

**Comment by jrieken** [comment] 2016-07-20 08:27
Ok - since I suspect a grammar issue, can you do one or both of the following:

* pick a file in which this happens and press `F1` > `Reload Window`
* press `F1`, select `Toggle Developer Tool`
* select the `Profiles` tab and start  to `Collect JavaScript CPU Profile`
* scroll a for a little (~30 seconds)
* in the dev tools stop profiling, save the data, and share it here 

or (iff possible) point me to the file(s) in which this happens

**Comment by janhartmann** [comment] 2016-07-20 08:30
You only want basic scrolling, no editing of files?

**Comment by janhartmann** [comment] 2016-07-20 08:36
Attached is basic scrolling where I could reproduce the performance issue.

[CPU-20160720T103444.txt](https://github.com/Microsoft/vscode/files/373173/CPU-20160720T103444.txt)

**Comment by jrieken** [comment] 2016-07-20 08:36
Thanks. The rule is to do as little as possible to show the slow down.

**Comment by jrieken** [comment] 2016-07-20 08:48
hm... it seems like the time is spend in native "browser" code like `getBoundingClientRect` and `insertAdjacentHtml`. Do you use an extension that adds many decorations like squiggles, extra text, etc to the editor text?

**Comment by janhartmann** [comment] 2016-07-20 08:53
I only have 1 extension installed: [Document This](https://github.com/joelday/vscode-docthis). Not really using it to be honest, so I can uninstall.

I am working on a Openlayers map application which is running in a separate Chrome browser. Not that I know if that should have any influence?

**Comment by jrieken** [comment] 2016-07-20 09:11
Shouldn't be that extension... Does you the _Activity Monitor_ show a VS Code or other process running high?

**Comment by janhartmann** [comment] 2016-07-20 09:22
Not really, there is 7 small and minor instances running of VS Code in my process manager, but maximum of 0-2% CPU power used and around ~20 MB. of memory used on each.

**Comment by juol** [comment] 2016-07-20 22:02
Hi there,

slowdown seems to be regardless of what's open.

I'll have a bit of time this weekend to dig a little deeper.

Thanks

**Comment by jrieken** [comment] 2016-07-21 12:49
@juol Great - getting a pref trace as describes [here](https://github.com/Microsoft/vscode/issues/9517#issuecomment-233882958) will help me

**Comment by alexandrudima** [comment] 2016-08-16 13:34
@janhartmann I've taken a look over the CPU profile you have attached and it seems something is definitely going wrong. The time to paint a frame on your machine appears to be around 60-80ms, which is roughly 10x of what it should be, even on older machines (less beefy CPUs).

Is there anything special about your setup that we should be aware of? 4K monitors, power save mode in the battery, any other software that would mess with the Chromium we're running on? Did VSCode ever run smoothly for you, is this a regression caused by an update? Does this reproduce when you're not working on your Openlayers project. Can you reproduce the slowness inside the editor at https://microsoft.github.io/monaco-editor/ (when visiting that page in Chrome).

**Comment by janhartmann** [comment] 2016-08-17 08:03
@alexandrudima, thanks for the investigation - I have some news to share. 

My CPU usage has "nothing" to do with VSCode. The issues appear that my Openlayers project running in another Chrome instance has some advanced drawing features which was not optimized. This has a tremendously impact on my CPU usage, but once I removed the continuing drawing animation, the performance issues were gone. 

I still find it a bit strange that another instance of Chrome has the effect on VSCode.

**Comment by alexandrudima** [comment] 2016-08-17 09:50
That is weird. I think two separate Chromium-based apps should not interact whatsoever, but I don't really know. At least for me, Chrome and VSCode do not appear to interact.

@juol Any more input from you, otherwise I will close this issue

**Comment by alexandrudima** [comment] 2016-09-14 17:15
@janhartmann @juol 
Do you have a laptop with a touchscreen?

**Comment by janhartmann** [comment] 2016-09-14 17:25
Yes. Leveno X1 carbon - issue is still a bit present to be honest

**Comment by alexandrudima** [comment] 2016-09-14 17:41
👍  let's track in this case in #12036

Please also see electron/electron#7208

**Closed by alexandrudima** 2016-09-14 17:41 UTC
Labels: bug, freeze-slow-crash, needs more info

**Comment by tdm9040** [comment] 2017-01-25 19:34
I have a WPF xaml file that is ~ 4000 lines long and the scrolling is very jerky and quite slow with delays of up to several seconds before moving.

**Comment by alexandrudima** [comment] 2017-01-25 20:05
@tdm9040 It would be awesome if you could share the file with us or share a file very similar that reproduces the slowness -- in a separate/new issue. We have found that each case can be quite different.
