### ISSUE TITLE
Scrollbar minimap/scroll bar doens't respond to touch screen dragging

### ISSUE THREAD

**Issue by DeXtmL** [microsoft/vscode#33234] opened 2017-08-28 05:02 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Surface Pro 4 Win10 x64 Latest update

---

Steps to Reproduce:

1. Open a large code document so that the scroll bar and the minimap appear
2. Use touch screen to drag the minimap focus area or the scroll bar.

result:
the dragging has no effect. the page doesn't scroll and the scroll bar doesn't move.

**Comment by MiladMohebnia** [comment] 2019-03-21 10:41
I'm on ubuntu 18 using VSCODE V1.31 and the issue is the same .. can't scroll minimap with touch.
I usually use the touch scroll to present code to persons.
It works on other editors.

**Comment by RMacfarlane** [comment] 2019-10-08 23:38
Duplicate of https://github.com/microsoft/vscode/issues/47771, this feature will be available in the next version of VSCode. Thanks!

**Closed by RMacfarlane** 2019-10-08 23:38 UTC
Labels: editor-minimap, feature-request, windows
