### ISSUE TITLE
[MacOs]Support 'look up' by force touch in MacOs

### ISSUE THREAD

**Issue by micsama** [microsoft/vscode#138701] opened 2021-12-09 05:43 UTC
It is reasonable that the right-click menu does not have the ‘look up’ in the system menu. But I want to allow the "Look up" function of MacOS to be called by  force touch on touchpad。

**Comment by yume-chan** [comment] 2021-12-09 06:12
Duplicate of #31047

**Comment by micsama** [comment] 2021-12-09 09:42
> Duplicate of #31047

Sorry for that，but can it be fixed?

**Closed** 2021-12-14 20:14 UTC
Labels: *duplicate
