### ISSUE TITLE
Regression: dvorak-qwerty commands keyboard layout no longer works correctly

### ISSUE THREAD

**Issue by darknoon** [Microsoft/vscode#23986] opened 2017-04-06 05:17 UTC
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|flow-for-vscode|flowtype|0.5.0|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1. Press command-s key on keyboard, should save
2. Action is Open not save :(

Started happening when I updated to the latest version

**Comment by darknoon** [comment] 2017-04-06 05:18
Seems to dup #23964

**Comment by darknoon** [comment] 2017-04-06 05:22
Appears related to work on https://github.com/Microsoft/vscode/issues/17521

**Comment by gyzerok** [comment] 2017-04-06 07:35
Are there any way to workaround it or downgrade VSCode to the previous version meanwhile?

**Comment by alexandrudima** [comment] 2017-04-06 22:20
Workaround: switch VS Code to dispatch based on key code again. Add the following setting:
`"keyboard.dispatch": "keyCode"` and restart VS Code

---

I would really like to understand your setup. I'm sorry for the breakage, I am really trying to get this right. Could you please explain like I'm five how to get into your setup, and what key combination fails. It would also help to attach here what our C++ node module detects (open an editor, press `F1 > Developer: Inspect Keyboard Mappings` save the output to a file and attach here).

**Comment by alexandrudima** [comment] 2017-04-06 22:57
Duplicate of #23964

**Closed by alexandrudima** 2017-04-06 22:57 UTC

**Comment by darknoon** [comment] 2017-04-06 23:07
@alexandrudima thanks a lot for following up with the workaround! after I set that setting, my keybindings are working again!

**Comment by darknoon** [comment] 2017-04-06 23:10
@alexandrudima I understand this is a little confusing. It's a keyboard layout that AFAIK doesn't exist on windows. Basically, it's Dvorak except when you're holding down the command (⌘) key, where it reverts back to qwerty. This is done because all of the key commands in macOS are designed ergonomically rather than by what the letter is. 

So it would defeat the purpose of DVORAK if your commands had their ergonomics messed up by it, so I used this hybrid (which has been supported since ancient times on mac os classic etc).

**Comment by crwang** [comment] 2017-04-08 14:32
I'm getting the same thing on my Mac.

When I used windows, I used to use this: https://github.com/bradfeehan/Dvorak-QWERTY-Ctrl to do the same thing that the Mac supports for their Dvorak-Qwerty keyboard setup.
