### ISSUE TITLE
Open in Terminal for folder does not work with Ubuntu

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#32188] opened 2017-08-09 13:46 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (2c3e2c291c515619f64e7c9cddf14c565b7f3d92, 2017-08-08T21:31:44.273Z)
- OS Version: Windows_NT x64 10.0.16251
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
coldfusion|ili|0.0.10
wordcount|ms-|0.1.0
htmlescape-vscode-extension|ray|0.0.4
spellchecker|swy|1.2.13

---

Steps to Reproduce:

1. Right click on a folder and select open in terminal
2. Opens in /home/ray

I would expect it to be /mnt/c/projects/foo (or some such, the location of my folder)

**Comment by Tyriar** [comment] 2017-08-18 19:51
Duplicate of https://github.com/Microsoft/vscode/issues/32717

**Closed by Tyriar** 2017-08-18 19:51 UTC
Labels: insiders, integrated-terminal
