### ISSUE TITLE
Missing prompt

### ISSUE THREAD

**Issue by JHeLiu** [Microsoft/vscode#58039] opened 2018-09-06 06:53 UTC
For example, I use the CDN accelerated JS library, it does not prompt,
The JS library that references your own project locally does not prompt either.

`<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>`
`<script src="./js/jquery.min.js"></script>`

It's because of the package hints that will be quoted for me

Although I am not a front-end, I am doing a back-end. Currently, Visual Studio 2017 is enough for me, but I will also write some front-end frameworks. Sometimes I find that VS CODE is lightweight, but its tips are especially unwise, maybe you have arranged After development, I want to remind you that this feature is too important.

At this time, I can only use Visual Studio 2017 or domestic development tools.
Because I think the front-end workers think too much about this feature!

**Comment by aeschli** [comment] 2018-09-06 15:58
@JHeLiu What do you mean by 'does not prompt'?

**Comment by JHeLiu** [comment] 2018-09-07 06:43
@aeschli  Sorry, maybe I can't express it clearly. You can take a look at the picture below. I really want VS CODE to have such a function.

**This is the VS CODE development tool**

![vscod1](https://user-images.githubusercontent.com/15246138/45202463-b0ca4d80-b2ab-11e8-957c-66f80e8d4a3f.gif)

**This is the Visual Studio 2017 development tool**

![vs2017](https://user-images.githubusercontent.com/15246138/45202496-c93a6800-b2ab-11e8-9aec-4e4c9408c082.gif)

**This is a domestic hbuilder development tool.**
![hb1](https://user-images.githubusercontent.com/15246138/45202625-33530d00-b2ac-11e8-977d-d05ad8a63ce1.gif)

**Comment by aeschli** [comment] 2018-09-10 06:57
ok, understood, we currently don't fetch scrips from script tags

duplicate of #26338

**Closed by aeschli** 2018-09-10 06:57 UTC
Labels: html, javascript
