### ISSUE TITLE
Feature: Add Folder to project

### ISSUE THREAD

**Issue by codehakase** [Microsoft/vscode#26219] opened 2017-05-08 15:38 UTC
- VSCode Version: 1.12.1
- OS Version: 16.04 LTS

I'd really like a Add Folder to Project feature just like in Atom, you can open multiple folders in the same window, and working from them. In my version of VSCode, when i use the open folder option, it opens a new instance of VSCode. Please this would a nice feature to add.

**Comment by egamma** [comment] 2017-05-08 18:13
Duplicate of #396

**Closed by egamma** 2017-05-08 18:13 UTC
Labels: duplicate
