### ISSUE TITLE
[VS Code Insiders] Debug Console shows exit error and doesn't WriteLine after restart (C#)

### ISSUE THREAD

**Issue by jramsay** [Microsoft/vscode#61005] opened 2018-10-15 21:30 UTC
Version: 1.29.0-insider (user setup)
Commit: 628740747496bc1f36c83d70f208b7fd85afc86b
Date: 2018-10-15T05:17:41.965Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS Version: Windows 10

Note: This is possibly a issue with the _C# for Visual Studio Code_ extension.  It only occurs on Insiders though and not Stable and I have the same C# extension on both:  (1.16.2)

Steps to Reproduce:

1. Open a basic C# console app on Insiders 
2. Set a breakpoint on Console.WriteLine("Hello World!") and start debugging
3. Step Over and notice the Debug Console works correctly.
4. Restart (Ctrl+Shift+F5) the debug session 
5. Notice that the following error message in the Debug Console:
The program '[24136] ConsoleApp118.dll' has exited with code -1 (0xffffffff) and the "Hello World" is not written to the Console after you step over

![image](https://user-images.githubusercontent.com/8161247/46979580-d571cc00-d086-11e8-8498-e4fc4273b6d3.png)

**Comment by isidorn** [comment] 2018-10-16 09:44
Thanks for the nice steps. I investigated and can not fully reproduce your issue
I see the error message: `has exited with code -1` but I also nicely see the `Hello World` message. 
I have tried both on OS X and windows and I see the same behavior.

As for the error message my asumption is that message was always being reported by the C# extension, however now on restart we are clearing the console a bit earlier and thus the message persists.
To verify: you can use vscode stable the C# extension and simply debug and stop debugging an app by clicking the Red Stop button - my assumption is that you will also see this error message.

@gregg-miskelly did you have other users reporting this? Can you also reproduce?

**Comment by gregg-miskelly** [comment] 2018-10-16 23:35
@jramsay I think either you are missing something from your repro steps, or I am not understanding them, as from the screen capture it looks like you are now at the line after Console.Writeline, but I am assuming when you restart, you should actually be stopping at the breakpoint again, right?

@isidorn's explanation for why the 'The program ... has exited' error message would stick around - the debugger would print that when we terminated the target process as part of the restart. But I don't have any idea why the 'Hello World' line wouldn't show up if you really are stopped on the line after Console.WriteLine. I can see if I can reproduce once I understand your repro steps.

**Comment by isidorn** [comment] 2019-03-14 16:03
Closing as I do not plan to fix this on our side (and good steps are missing for me at least)

**Closed by isidorn** 2019-03-14 16:03 UTC
Labels: debug, needs more info
