### ISSUE TITLE
Copy & Paste a file in the sidebar doesn't work anymore

### ISSUE THREAD

**Issue by crewone** [microsoft/vscode#100912] opened 2020-06-24 07:29 UTC
Issue Type: <b>Bug</b>

As of today, the insiders build doesn't allow a file in the workspace pane on the sidebar to be copied-and-pasted to create a copy of that file. 

Not using keys (CTRL-C/V) and not using the context menu.

VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (16.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|25.01GB (22.42GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
bracket-pair-colorizer-2|Coe|0.1.4
auto-close-tag|for|0.5.7
nullish-coalescing-operator-grammar|Lev|0.0.1
vscode-xslt-snippets|mar|0.1.0
remote-wsl|ms-|0.44.4
js-debug-companion|ms-|1.0.2
debugger-for-chrome|msj|4.12.8
material-icon-theme|PKi|4.2.0
seti-icons|qin|0.1.3
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|10.1.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.2
go-outliner|766|0.1.20
Bookmarks|ale|11.3.0
atlascode|atl|2.6.3
vscode-twig-pack|baj|1.1.0
auto-align|bla|0.0.13
vscode-intelephense-client|bme|1.4.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
go-nightly|gol|2020.6.1809
beautify|Hoo|1.5.0
php-cs-fixer|jun|0.1.154
twig-language-2|mbl|0.9.1
vscode-language-babel|mgm|0.0.27
php-docblocker|nei|2.1.0
vscode-yaml|red|0.8.0
sass-indented|syl|1.8.6
errorlens|use|3.1.1
vscodeintellicode|Vis|1.2.8
better-align|wwm|1.1.6

(1 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2020-06-24 08:04
Duplicate of #100797. Please do a search before filing new issues.

**Closed** 2020-06-24 08:39 UTC
Labels: *duplicate
