### ISSUE TITLE
[Typescript] getting error when set 'experimentalAsyncFunctions' to true

### ISSUE THREAD

**Issue by moostad** [Microsoft/vscode#2154] opened 2016-01-21 16:37 UTC
I'm not sure it's related to #608 or not but typescript compiler stop working when i add experimentalAsyncFunctions to tsconfig.json file.

![ww](https://cloud.githubusercontent.com/assets/10362398/12486887/dc8a4316-c079-11e5-9bbc-79dc5fbaef56.gif)

**Comment by dbaeumer** [comment] 2016-01-22 08:02
@moostad from the message it looks like the plugin host got in trouble. Is this reproducible for you. If so, is the code some public so that we can try to reproduce this locally.

@alexandrudima does the plugin host error message ring a bell.

**Comment by alexandrudima** [comment] 2016-01-22 10:52
From the partial error message, it is not clear to me if the tsserver crashes and we report that error, or if the entire extension host crashed.

**Comment by moostad** [comment] 2016-01-22 13:15
@dbaeumer my apology, Ignore that message box, that's happened once on recording when I pushed shortcut-key for "Reload Window". The issue that I'm referring to is different and to be clear i check that in two different machine (Mac and Windows) with two different project.
cc @alexandrudima 

![wwe](https://cloud.githubusercontent.com/assets/10362398/12511203/ba2aebbc-c124-11e5-9365-0bb6f31fba42.gif)

**Comment by moostad** [comment] 2016-01-22 14:16
@dbaeumer I just add very simple repository for this issue. just clone https://github.com/moostad/vscodeTypescriptAsync and check ```app.tsx```

**Comment by dbaeumer** [comment] 2016-01-25 10:27
@moostad Thanks for the repository. Now I see your problem. Since TS 1.7.x (which is bundled with VSCode 0.10.6) async await is an official feature and the flag got removed. However that should not make the tsserver to fail so drastically. 

Moving to the TypeScript team since there is nothing VSCode can do about it.

**Comment by dbaeumer** [comment] 2016-01-25 10:29
This issue was moved to Microsoft/TypeScript#6609

**Closed by dbaeumer** 2016-01-25 10:29 UTC
