### ISSUE TITLE
Infinite loop of "The TypeScript language service died unexpectedly"

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#9215] opened 2016-07-13 14:45 UTC
- VSCode Version: 1.3.1
- OS Version: Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:
1. Uninstall VSCode
2. Install VSCode
3. Navigate to an empty directory
4. Open VSCode
5. Create a new file `empty.ts`

The error message "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report." repeatedly pops up.
My `settings.json` is an empty object.

The problem can be solved by adding `"typescript.tsdk": "C:\\Program Files\\nodejs\\node_modules\\typescript\\lib"` to `settings.json`. My global `tsc --version` is `2.0.0`.

**Comment by dbaeumer** [comment] 2016-08-02 13:03
@andy-ms where did you get 2.0.0 from. npm install typescript@2.0.0 doesn't install any usable typescript package.

**Comment by andy-ms** [comment] 2016-08-02 14:08
`2.0.0` was the version installed by `npm install -g typescript@next` back when I wrote this issue.
I just removed "typescript.tsdk" from my settings and an empty project is now working, but I'm still sporadically getting the above error. Is there anything I can do in such a situation to detect what caused it?

**Comment by dbaeumer** [comment] 2016-08-03 13:50
@andy-ms does a non empty file work. If so does the status line in the right corner give some hint about the TS version used ?

And just to be super sure. You neither have a tsdk setting in the user nor in the workspace settings.

**Comment by andy-ms** [comment] 2016-08-03 15:38
The workspace was just created (there is no `.vscode`, so there are no workspace settings. The status line just says "TypeScript". If I change the language to "TypeScript React" it still has this problem.
![screenshot](https://cloud.githubusercontent.com/assets/19274678/17371645/852e539e-5955-11e6-9e00-dee0d9011f43.jpg)

**Comment by dbaeumer** [comment] 2016-08-04 14:13
@andy-ms I have no clue why this happens since this works for me without problems. Did you choose a special install location for VS Code ? If not does `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib` exist with a similar content ?

![capture](https://cloud.githubusercontent.com/assets/1931590/17405075/6b339f80-5a5e-11e6-8189-687fef5c8351.png)

**Comment by andy-ms** [comment] 2016-08-04 14:19
Yes, that folder exists for me with the same files listed.

**Comment by dbaeumer** [comment] 2016-08-04 14:22
OK. if you add a workspace setting and restart code afterwards do you still see the problem ?

```json
     "typescript.tsdk": "C:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib"
```

**Comment by andy-ms** [comment] 2016-08-04 14:25
Yes, with that as the only line in my `settings.json` (besides `{` and `}`) I still get the error.

**Comment by dbaeumer** [comment] 2016-08-08 10:27
@andy-ms I have no idea what is going on. You have the correct version of the tsserver. Do you still see this with VS Code 1.4. If so, can I give you instruction on how to debug this?

**Comment by andy-ms** [comment] 2016-08-08 12:47
I still get it with 1.4. I'd be happy to try debugging it.

**Comment by dbaeumer** [comment] 2016-08-09 10:26
Thanks for offering your help. You need to do the following:

- install VS Code insider so that you have a second independent instance (https://code.visualstudio.com/insiders)
- create a new empty workspace folder and open a command prompt on it. Start code from the command prompt using `code.cmd --debugPluginHost`
- start the insider build
- go to the debug viewlet and press the configure icon on the top to create a launch.json config file.
- change the port in the Attach section to 5870
```json
{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5870,
			"address": "localhost",
			"restart": false,
			"sourceMaps": false,
			"outDir": null,
			"localRoot": "${workspaceRoot}",
			"remoteRoot": null
		}
```
- select the attach debug configuration from the drop down.
- press the green arrow to attach
- no open the file: `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js` in the insider build
- set a breakpoint on line 172 and 176 (assuming using code 1.4)
- create a new TS in code and wait until the breakpoint gets hit.
- which breakpoint gets hit and if 172 what exception are you receiving ?

**Comment by dbaeumer** [comment] 2016-08-09 12:51
@andy-ms is your workspace on a mounted SharePoint WebDav folder. If so this is a dup of https://github.com/Microsoft/vscode/issues/3860

**Comment by andy-ms** [comment] 2016-08-09 13:01
I see line 176 getting hit (this is the one after `childProcess.on('exit'`) and `err` is 7. (My sample directory is on my own hard drive, not sharepoint.)

**Comment by dbaeumer** [comment] 2016-08-09 13:33
That means the node process exits with error number 7. Still no clue why :-(

**Comment by andy-ms** [comment] 2016-08-09 13:52
Despite the message, the error happens within a few seconds of running `code .` (where vscode was not already open) in the previously-created directory with just an empty `a.ts` in it.

**Comment by dbaeumer** [comment] 2016-08-16 15:08
@andy-ms. Very strange :-(. 

The easiest to track this down is to run and debug VS Code from source. How to do so is documented here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source.

Would you be willing to set this up. Otherwise I will add additional options to the next build to ease this.

**Comment by andy-ms** [comment] 2016-08-23 16:04
Sorry, but I was unable to build on Windows (using the latest c++ devtools from visual studio gives errors with oniguruma) and the problem does not happen on linux, so it'll have to wait until the next build.

**Comment by dbaeumer** [comment] 2016-08-25 14:02
@andy-ms that looks like the problem we started seeing when upgrading the C/C++ tooling with VS Update 3. We have worked around it by updating the node-gyp package npm is using to version 3.4.0. (We are currently blocked from upgrading npm itself to >=3.9, the latest comes with the fixed node-gyp.).

**Comment by dbaeumer** [comment] 2016-11-15 19:24
@andy-ms can you still reproduce thus ?

**Comment by Sayan751** [comment] 2016-12-02 10:26
@dbaeumer I am also facing the same issue. I have noticed that if VS Code is ran as administrator, the problem goes away. In every other case, it goes into the infinite loop. 

I am using VS Code v1.7.2, Node v5.9.0, tsc v2.0.10 on WIndows 10.

**Comment by dbaeumer** [comment] 2016-12-05 08:49
@Sayan751 strange. Works for me using an non administrator account. 

One idea to better understand this is the following:

- can you install TS somewhere else on your disk where you have read / write access using npm install typescript@2.0.10
- use the `typescript.tsdk` setting to point VS Code to that TS installation. E.g. `"typescript.tsdk": "C:/tmp/node_modules/typescript/lib"`

Does that help?

**Comment by andy-ms** [comment] 2016-12-05 14:49
I can't reproduce this any more with VSCode 1.7.2. I just get a message "Info | Version mismatch! global tsc (2.2.0-dev.20161118) != VS Code's language service (2.0.10). Inconsistent compile..."

**Comment by dbaeumer** [comment] 2016-12-06 09:52
@andy-ms the version mismatch points to the fact that your global tsc version is 2.2.0-dev.20161118 and the VSC version is 2.0.10. Since you don't have the tsdk setting pointing to 2.2.0-dev.20161118 it might happend that running tsc in the terminal produces different errors than the language service inside VS Code (because they are different version). You can disable that check by pressing the 'Don't check again' button.

**Comment by Sayan751** [comment] 2016-12-08 07:04
@dbaeumer I confirm, that this helps. Thank you for that. 
>use the typescript.tsdk setting to point VS Code to that TS installation. E.g. "typescript.tsdk": "C:/tmp/node_modules/typescript/lib"

I think this is the workaround for now.

**Comment by dbaeumer** [comment] 2016-12-08 11:26
@Sayan751 good to hear. Now we need to understand why TS is not running from the installation directory. Is there anything special. Have you installed VS Code into a special location ?

**Comment by Sayan751** [comment] 2016-12-08 11:36
@dbaeumer I can't remember changing any default option during installation. On my machine the installation path is "C:\Program Files (x86)\Microsoft VS Code\Code.exe"

**Comment by dbaeumer** [comment] 2016-12-08 11:53
@Sayan751 is there anything in the TypeScript Output Channel (Ctrl+Shift+U) select TypeScript from the drop down?

**Comment by Sayan751** [comment] 2016-12-08 12:11
@dbaeumer When I use the default `typescript.tsdk` location, I get the following error messages in TypeScript Output repetitively:

```
[Info  - 1:03:42 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Error - 1:03:43 PM] TSServer exited with code: 1
[Info  - 1:03:43 PM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Error - 1:03:43 PM] TSServer exited with code: 1
```

However, when I override the default `typescript.tsdk` with local typescript inside node_modules, the error message goes away, and it simply says:
```
[Info  - 1:03:44 PM] Using tsserver from location: C:\Path\To\My\Code\node_modules\typescript\lib\tsserver.js
```
and along with that the infinite loop of the pop-up stops.

**Comment by dbaeumer** [comment] 2016-12-08 13:21
@Sayan751 could you do the following in advance:

- open a terminal (e.g. PowerShell)
- set the environment variable `TSS_LOG="-level verbose -file c:\tmp\server.log"` (in PowerShell `$env:TSS_LOG="-level verbose -file c:\tmp\server.log"`). Adopt the file location accordingly
- start VS Code from the terminal using code command

Can you provide the content of the log file.

**Comment by Sayan751** [comment] 2016-12-09 07:05
@dbaeumer Please find the logs attached.

[vs-code log.zip](https://github.com/Microsoft/vscode/files/641449/vs-code.log.zip)

**Comment by dbaeumer** [comment] 2016-12-09 10:20
@Sayan751 surprisingly there is nothing that points to a crash in the log. If I give you instructions would you be able to debug this a little. I have no clue why this is happening.

**Comment by dbaeumer** [comment] 2016-12-09 10:22
@mhegazy and idea how we could find out why the tsserver exits without being ask to do so.

**Comment by Sayan751** [comment] 2016-12-09 11:45
@dbaeumer I would like to debug this. However, it may take some time to get back you. Additionally also attaching some latest logs.
[logs.zip](https://github.com/Microsoft/vscode/files/642049/logs.zip)

**Comment by dbaeumer** [comment] 2016-12-12 11:17
@Sayan751 thanks for the logs. Will have a look. When you have time to help me with that please ping.

**Comment by Sayan751** [comment] 2016-12-16 07:09
@dbaeumer ping

**Comment by mjbvz** [comment] 2017-02-07 20:50
Closing since it sounds like the original issue has been resolved.

If you seeing a similar problem with VSCode 1.9+, please open a new bug and we will investigate.

Thanks

**Closed by mjbvz** 2017-02-07 20:50 UTC
Labels: javascript, needs more info, typescript
