### ISSUE TITLE
terminal charecters displayed white after sys suspend

### ISSUE THREAD

**Issue by AliHaidar110** [microsoft/vscode#113445] opened 2020-12-26 12:24 UTC
![Screenshot from 2020-12-26 14-26-14](https://user-images.githubusercontent.com/64657659/103151412-98d1ad00-4786-11eb-8330-63f8a5cc3736.png)
Issue Type: <b>Bug</b>

run vs-code
open terminal
suspend system
re-enter the system
problem: the terminal is white not showing any writings and while typing whit blocks are displayed with no charecters

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 3262)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.69GB (0.50GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id c68cf35d-d1b1-4202-ba71-cf314ae33946|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.8.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by meganrogge** [comment] 2020-12-27 20:55
Hi what do you mean by "suspend system"? I'm not able to reproduce this

**Comment by YalandHong** [comment] 2020-12-28 10:04
I think it's possibly a duplicate of #69665

**Comment by meganrogge** [comment] 2020-12-30 03:52
Duplicate of #69665

**Closed** 2020-12-30 03:52 UTC
Labels: *duplicate, integrated-terminal, needs more info
