### ISSUE TITLE
TypeScript and JavaScript Language Features v1.0.0 Built-in extension failure

### ISSUE THREAD

**Issue by syllik** [microsoft/vscode#132462] opened 2021-09-06 13:11 UTC
Issue Type: <b>Bug</b>

> When any JS-based project opened, build-in core extension TypeScript and JavaScript Language Features v1.0.0 fails after initialization.
> Occurs after vscode update to 1.6.0
> The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv|--crash-reporter-id 73fd32ce-a593-4014-ae48-b2aa32b68812|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|2.3.0
atlascode|atl|2.9.1
vscode-node-readme|ben|3.0.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
vscode-jest-runner|fir|0.4.44
vscode-pull-request-github|Git|0.30.0
vscode-styled-components|jpo|1.6.6
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
graphql|mqu|0.1.2
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
markdown-preview-enhanced|shd|0.6.0
addDocComments|ste|0.0.8
code-spell-checker|str|2.0.4
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn420:30356812
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-06 14:15
Please use the `Start Extension Bisect` command to check whether the crash is being caused by any of your other extensions.

**Comment by syllik** [comment] 2021-09-06 15:43
Same problem when all extensions is disabled
After stopping bisect cmd,  shows `The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.
`

![image](https://user-images.githubusercontent.com/9326239/132239353-dafda791-9418-41dc-9ecb-6ffc50fa0006.png)
![image](https://user-images.githubusercontent.com/9326239/132240363-bf91b0d4-9996-4b71-b69a-7e7d11e2a573.png)

due to Log (Extenstions Host) i can't found any errors, seems like extension is working, but annoying message repeating

**Comment by DmitrijStr** [comment] 2021-09-06 15:56
Same issue on VS Code 1.60.0 Ubuntu 20.04.3 without any extension

**Comment by machineghost** [comment] 2021-09-09 16:10
Yet another "me too".  Also why were all the other "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes." closed without resolution?

**Comment by mjbvz** [comment] 2021-09-09 16:39
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment] 2021-09-09 16:41
@machineghost Please open a separate issue. There are "duplicate" issues because crashing is super generic symptom with any number of different root causes

**Comment by machineghost** [comment] 2021-09-09 16:47
As I said in my edit I (seemingly) got my editor fixed ... but surely you can agree that it's not some massive cosmic coincidence that there are suddenly a ton of Typescript failure tickets right?  They must share some underlying root cause.

**Comment by mjbvz** [comment] 2021-09-16 19:41
Closing as not actionable without more information from the original poster

**Closed by mjbvz** 2021-09-16 19:41 UTC
