### ISSUE TITLE
Support a path included space character for clickable link in terminal window

### ISSUE THREAD

**Issue by fujitatakesh** [microsoft/vscode#115479] opened 2021-01-31 01:29 UTC
I'm using ONLY VSCode for Windows. It's very useful of my works. It saves a half of time. I have a coffee time on the left time.
I noticed it gave me a quarter time that VSCode supported clickable link including space character in terminal window.
If I click "C:\Program Files\~" file for one click, I can have a cookie and coffee. Thank you.

Steps to reproduce.
Step1: Open terminal window on VSCode for Windows.
Step2: Type "C:\Program Files\Microsoft" with double quotes.
Step3: Move mouse pointer over the path with Ctrl key.
Step4: Check underlined.

**Comment by meganrogge** [comment] 2021-02-01 17:02
Duplicate of #114885

**Closed** 2021-02-01 17:02 UTC
Labels: *duplicate
