### ISSUE TITLE
Any SSH File system extension will crash VS Code in a similar way - Buffer() is deprecated @ console.ts:137

### ISSUE THREAD

**Issue by Simba98** [microsoft/vscode#116260] opened 2021-02-10 03:54 UTC
- VS Code Version & OS Version:
VS Code Version: 1.53.1 (user setup)
Submit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:29:42.785Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
Steps to Reproduce:

1. Install a SSH File System extension.
2. Try to connect it, and the extension will launch SSH.
3. VS Code will crash. I tried _SSH FS_, _SSH Client_, they are popular extensions, and all of them will crash VS Code in a similar way.
4. I opened the developer tool, as following shows.
![image](https://user-images.githubusercontent.com/7941967/107462137-68a76780-6b96-11eb-9410-924e4033c2cb.png)
The copyright of this file shows it belongs to Microsoft code.
5. Here is the console message.
![image](https://user-images.githubusercontent.com/7941967/107462210-92f92500-6b96-11eb-9ae0-c4c61a90b361.png)
(node:15060) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
b @ console.ts:137

Does this issue occur when all extensions are disabled?: No, but I still guess this issue due to VS code. Because I tried several SSH extensions, and all have similar problem.

**Comment by Simba98** [comment] 2021-02-10 04:01
A call stack has been tracked and as the following screenshot shows.
![image](https://user-images.githubusercontent.com/7941967/107462735-bb355380-6b97-11eb-8319-bd2f0e7b4c90.png)

**Comment by Simba98** [comment] 2021-02-10 08:03
Moreover, I tried to downgrade VS Code, crash disappeared.

I downgrade to:
Version: 1.52.1 (user setup)
Submit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by scriptninja** [comment] 2021-02-11 08:10
I suspect this is a duplicate of #114362, which has some notes on what's been found regarding the underlying problem in Electron 11

**Comment by alexr00** [comment] 2021-02-11 13:14
@scriptninja thanks for dropping that link in. 

@deepak1556 it seems like this is likely caused by an electron 11 issue: https://github.com/electron/electron/issues/27673

**Comment by deepak1556** [comment] 2021-02-11 21:39
Thanks for the issue pointer, the fix will be backported to the electron 11 branch and will get it into our next release.

**Closed** 2021-02-23 00:26 UTC
Labels: electron, electron-11-update, freeze-slow-crash-leak, upstream-issue-fixed

**Comment by MJimitater** [comment] 2021-04-08 06:51
This issue seems fixed. However, I got a similar error message ([-1617863769299.zip](https://github.com/microsoft/vscode/files/6276627/-1617863769299.zip)), but Im not working with any SSH file system extension. How does this relate?
