### ISSUE TITLE
The terminal process command `C:\Windows\sysnative\cmd.exe` failed to launch (exit code: 1)

### ISSUE THREAD

**Issue by zheung** [Microsoft/vscode#20100] opened 2017-02-07 07:17 UTC
- VSCode Version: 1.9.0
- OS Version: Win10 64Bit

Steps to Reproduce:

1. Open `Integrated Terminal`

I tried to reinstall Code but still cannot open the terminal.

Then I found that it only happened when I install on the default path
`C:\Program Files (x86)\Microsoft VS Code`

`C:\Code` or `C:\Program Files (x86)\Code` is ok
and portable version is ok too.

**Comment by Tyriar** [comment] 2017-02-07 21:15
Can you post your settings.json file?

**Comment by zheung** [comment] 2017-02-08 00:23
> // 将设置放入此文件中以覆盖默认设置
{
	"editor.fontFamily": "Source Code Pro Medium, 微软雅黑",
	"editor.fontSize": 15,
	"editor.insertSpaces": false,
	"search.exclude": {
		"**/node_modules": true,
		"**/bower_components": true,
		"**/.svn": true,
		"**/application/assets/echarts": true,
		"**/application/assets/extjs": true,
		"**/ext": true,
		"**/.sencha": true,
		"**/build": true
	},
	"editor.scrollBeyondLastLine": false,
	"editor.renderWhitespace": "boundary",
	"editor.glyphMargin": true,
	"editor.fontLigatures": true,
	"files.trimTrailingWhitespace": true,
	"files.exclude": {
		"**/.git": true,
		"**/.svn": true,
		"**/.DS_Store": true,
		"**/node_modules": true,
		"**/.vscode": false,
		"**/assets": false
	},
	"update.channel": "none",
	"window.zoomLevel": 0,
	"editor.detectIndentation": false,
	"editor.renderIndentGuides": true,
	"workbench.sideBar.location": "right",
	"git.confirmSync": false,
	"terminal.integrated.shell.windows": "C:\\Windows\\Sysnative\\cmd.exe",
	"terminal.integrated.fontFamily": "Source Code Pro Medium, 微软雅黑",
	"terminal.integrated.fontLigatures": true,
	"terminal.integrated.fontSize": 15,
	"eslint.validate": [
		"javascript",
		"javascriptreact"
	],
	"eslint.options": {
		"configFile": "C:\\Code\\.eslintrc.json"
	},
	"editor.wordWrap": false
}

**Comment by zheung** [comment] 2017-02-08 00:33
before reinstall i haved deleted `.vscode\extensions` and `Roaming\Code` folder.

path with `system32\\cmd.exe`, `syswow64\\cmd.exe`, powershell and `git\\bash.exe` both show the same error...

**Comment by Tyriar** [comment] 2017-02-08 01:11
Not really sure what this could be. It's particularly strange that you say the location of the VS Code install impacts the repro, @joaomoreno any ideas?

**Comment by joaomoreno** [comment] 2017-02-08 08:11
Super odd, no clue. 😕

**Comment by patoncrispy** [comment] 2017-02-10 11:51
I've had the same issue running `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"`. My config is pretty simple:

```
{
    "editor.fontFamily": "Inconsolata",
    "editor.fontWeight": "500",
    "editor.fontSize": 15,
    "editor.lineHeight": 22,
    "editor.fontLigatures": true,
    "editor.rulers": [100],
    "editor.insertSpaces": true,
    "editor.autoClosingBrackets": true,
    "extensions.autoUpdate": true,
    "window.zoomLevel": 0,
    "eslint.autoFixOnSave": true,
    "editor.tabSize": 2,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"
  }
```

That path is what I get from `where bash`.

**Comment by patoncrispy** [comment] 2017-02-10 11:52
Also I have VSCode installed in default location. Haven't tried moving it...

**Comment by Tyriar** [comment] 2017-02-10 18:31
@patoncrispy if you have bash WSL installed (ie. it launched in a regular cmd window) and you're on 64-bit Windows then the recommended path for bash on windows is `C:\\Windows\\sysnative\\bash.exe`

**Comment by joseph1125** [comment] 2017-02-18 12:42
I also encounter this issue and tried cmd, git bash, both are not working, it is weird after updating to version 1.9.0. Properly reconsider the decision moving back to Atom / Sublime Text.

My settings
`{
    "editor.wrappingColumn": 0,
    "git.confirmSync": false,
    "editor.fontFamily": "Inconsolata, Noto Sans CJK TC",
    "window.showFullPath": true,
    "editor.fontSize": 16,
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe"
}`

**Comment by joseph1125** [comment] 2017-02-18 12:55
I believe that this problem mainly occurs if the visual studio code is installed in a Trad Chinese and Simplified Chinese Windows. However, changing the language of Windows afterwards won't work.

**Comment by Tyriar** [comment] 2017-04-21 19:30
This can be caused by running VS Code in compatibility mode which may happen if you've upgraded your OS. @zheung let me know if that resolves your issue.

**Closed by Tyriar** 2017-04-21 19:30 UTC
Labels: integrated-terminal, needs more info

**Comment by zheung** [comment] 2017-04-22 00:52
thanks, it works. what a concealed setting

**Comment by Tyriar** [comment] 2017-04-24 18:39
@zheung perfect, I've since added it to the documentation on the website so hopefully that will help people
