### ISSUE TITLE
When using ctrl+d (addSelectionToNextFindMatch) on a repeated character, it extends selection

### ISSUE THREAD

**Issue by RoscoP** [Microsoft/vscode#21932] opened 2017-03-03 20:31 UTC
- VSCode Version: 1.10.1
- OS Version: Windows 7 (patched up)

Steps to Reproduce:

1. Write a document with repeated characters EG: AAAbbbcccA
2. Select first character of repeated sequence, hit ctrl+d
3. Note the select expands instead of singularly selecting the next character, next ctrl+d will not find a single character, but the double character version
![vscode-addselectiontonextfindmatch](https://cloud.githubusercontent.com/assets/5105596/23567890/3869ec80-000d-11e7-87da-e5efd7354641.gif)

**Comment by alexandrudima** [comment] 2017-03-06 11:17
Touching selections get merged. Duplicate of #11150

**Closed by alexandrudima** 2017-03-06 11:17 UTC
Labels: editor-multicursor
