### ISSUE TITLE
VSCode freezes when closing Cmder as Integrated Terminal on Win10

### ISSUE THREAD

**Issue by joshpeng** [microsoft/vscode#88102] opened 2020-01-05 10:07 UTC
- VSCode Version: 1.41.1
- OS Version: Windows 10 1909
- Cmder Version: 1.3.13

Steps to Reproduce:

Configure `settings.json` as per https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cmders-shell-with-the-terminal-on-windows with:
```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": ["/K", "C:\\Cmder\\vendor\\init.bat"]
```

1. Start Code
2. `Ctrl + ~` to open integrated terminal
3. Close the terminal via the kill trash can icon without hiding the terminal ever <-- Code is now frozen and requires a reopen

Oddly enough, if you happen to minimize the integrated terminal before restoring it. A trash can kill of it now will work just fine. If you submit any commands in the terminal prior to trash can killing it, it will freeze Code too. It seems to only work if you hide/unhide the terminal right before killing it with no commands inbetween.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment] 2020-01-05 12:18
Duplicate of #71966

With upstreams: https://github.com/microsoft/terminal/issues/1810 & https://github.com/microsoft/node-pty/issues/375

**Closed** 2020-01-06 17:31 UTC
Labels: *duplicate, integrated-terminal
