### ISSUE TITLE
Looking for someone to help build a twig code formatting extension (beautifier)

### ISSUE THREAD

**Issue by bgarrant** [Microsoft/vscode#37514] opened 2017-11-02 11:57 UTC
We the increasing number of twig CMS's out there, we are in need of a twig code beautifier to be able to use Visual Studio Code.  None of the existing solutions for VSC works with twig code format.  The solutions out there for Sublime Text and Atom work perfectly (https://github.com/rareyman/HTMLBeautify and https://github.com/Glavin001/atom-beautify), so there should be no reason why we cant get this to work in VSC.  The existing options for VSC all remove the line breaks incorrectly for the twig tags.

https://github.com/HookyQR/VSCodeBeautify/issues/163
https://github.com/HookyQR/VSCodeBeautify/issues/176

After trying to fork a js-beautify extension without success, I decided maybe it was time to see if anyone out there could help us.  These are the current options that may be able to be forked and made to work with twig.

https://github.com/HookyQR/VSCodeBeautify
https://marketplace.visualstudio.com/items?itemName=HexcodeTechnologies.vscode-prettydiff
https://github.com/Unibeautify/vscode

Can anyone either help contribute to get twig supported in these extensions, or at least quote a price to build an extension so we can see if possibly a few twig users will help pay for the development?

**Comment by aeschli** [comment] 2017-11-09 17:30
duplicate of #25444

Looking at atom-beautify, it seems to use prettydiff as the formatter for twig files.
So I'd suggest to use the prettydiff extension.
https://marketplace.visualstudio.com/items?itemName=HexcodeTechnologies.vscode-prettydiff

**Closed by aeschli** 2017-11-09 17:30 UTC
Labels: extension-candidate

**Comment by mblode** [comment] 2017-11-14 13:01
I have finally solved the issue of formatting Twig in VSCode!
Over the past week I have put together a VSCode extension to include everything you would need in a Twig extension: https://marketplace.visualstudio.com/items?itemName=mblode.twig-language

This includes a WORKING Twig file formatter using PrettyDiff with a similar implementation as Atom-Beaitify. Moreover, my plugin includes syntax highlighting and language support, snippets and information on hover for Twig. Hopefully this fixes all of your issues with VSCode and Twig. If you run into a problem, simply open an issue on GitHub. 
Thanks and happy coding :)

P.S. Hi bgarrant, this is a message for anyone else still trying to find a solution.
