### ISSUE TITLE
Cannot fold code block with different style comments

### ISSUE THREAD

**Issue by tomfriwel** [Microsoft/vscode#38489] opened 2017-11-16 09:00 UTC
For I use other editor do some special tasks, the double slash is from the first one in each row when I use ***Comment shortcut***. But this comment sytle is not same with VSCode.

So, if I want fold the code block with these comments, I must comment these comments again and again in VSCode.

Just look at the pictures below:

<img width="218" alt="screen shot 2017-11-16 at 16 49 45" src="https://user-images.githubusercontent.com/11268235/32882171-18631358-ca79-11e7-9eaf-3ae9b00db708.png">
<img width="227" alt="screen shot 2017-11-16 at 16 49 55" src="https://user-images.githubusercontent.com/11268235/32882172-18a16310-ca79-11e7-8335-dd2f634055c7.png">

**Comment by roblourens** [comment] 2017-11-16 18:29
duplicate of https://github.com/Microsoft/vscode/issues/3422

**Closed by roblourens** 2017-11-16 18:29 UTC
