### ISSUE TITLE
Terminal path uses incorrect drive letter casing

### ISSUE THREAD

**Issue by MartinSvarrer** [Microsoft/vscode#10177] opened 2016-08-05 08:13 UTC
- VSCode Version: 1.4
- OS Version: Microsoft Windows [Version 10.0.10586] 

Steps to Reproduce:

1. Open Terminal (or use the Open in command prompt in explorer - has same issue)
2. Drive letter casing is wrong in the path.

My drive letter in windows is uppercase `C`, but cmd displays in this case a lowercase `c`.

Actual result: `c:\Users\msc\Programming>`
Expected result: `C:\Users\msc\Programming>`

This is inconvenient as I often run node tools from the terminal, and not all node tools are case insensitive.

**Comment by Tyriar** [comment] 2016-08-05 18:28
Duplicate of https://github.com/Microsoft/vscode/issues/9448

**Closed by Tyriar** 2016-08-05 18:28 UTC
