### ISSUE TITLE
IntelliSense problems if `Flow` plugin is used

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#24974] opened 2017-04-18 20:43 UTC
- VSCode Version: 1.11.2
- OS Version: Linux Ubuntu 16.04

Hello, I opened issue here https://github.com/flowtype/flow-for-vscode/issues/97 and they said it's VS Code problem, maybe anyone can take attention on that? This plugin is very good, because it improves IntelliSense and we don't need to use `.ts` files to have improved IntelliSense, but the problem is, it somehow duplicates suggestions and some of them arranges to the end or at the middle which is really bad, but still is it better to have this with improved IntelliSense. I know `Flow` and `TypeScript` not the best friends since VS Code using `TypeScript` it makes zero sense to you for trying to fix it, but it will be very cool from your side.

P.S. If someone are lazy to check issue on `Flow` plugin which is above I can post here all the content from the issue I opened.

Thank you.

**Comment by orta** [comment] 2017-04-18 20:59
To save you digging around this is basically https://github.com/Microsoft/vscode/issues/15738 and https://github.com/Microsoft/vscode/issues/17068

**Comment by mjbvz** [comment] 2017-04-18 21:01
Thanks @orta! Yes, #17068 tracks allowing built-in extensions to be disabled.

Closing as a duplicate of #17068

**Closed by mjbvz** 2017-04-18 21:01 UTC
Labels: duplicate
