### ISSUE TITLE
VSCode Stuck

### ISSUE THREAD

**Issue by budhalantara** [Microsoft/vscode#63038] opened 2018-11-13 16:46 UTC
Issue Type: <b>Bug</b>

VSCode stuck after Update on October 2018 (v1.29).
please Fix this issue.
Thanks

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (4.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.9
jquery-snippets|Hri|1.0.0

</details>

**Comment by jrieken** [comment] 2018-11-13 17:12
so, what version are using? 1.29 or 1.28?

**Comment by SupersonicCasualties** [comment] 2018-11-13 17:36
I believe we are having the same issue, with me after the update today VSCode froze about 4 times, something about 6h of use, with it asking to close the window or reopen, with me tho it's version 1.29, I don't know how to debug VSCode exceptions such as this and would be happy to help

**Comment by spaceghoul** [comment] 2018-11-13 19:42
Also experiencing this with 1.29.0 on Mac OS High Sierra with only theme extension enabled. VSCode stops responding to interactions from mouse or keyboard and sometimes eventually becomes responsive again but usually I am having to kill it via the OS force quit. This has happened several times since the update to 1.29.0.

**Comment by di3663** [comment] 2018-11-14 02:42
I got the same issue every ten minutes, it's definitely a bug in 1.29.0.
Or all releases? occurs before, but not so frequently.

**Comment by neildom** [comment] 2018-11-14 02:44
I am also experiencing the “The window is no longer responding” dialogue since upgrading to 1.29.0. Initially I thought it was due adding the "terminal.integrated.experimentalBufferImpl": "TypedArray" setting but vscode still freezes after I removed this setting. I am using Windows 10 Version 1803

**Comment by WhipeeDip** [comment] 2018-11-14 07:33
Also experiencing this after updating. Version 1.29.0 on Windows 10 x64 1809.

**Comment by jrieken** [comment] 2018-11-14 08:03
/duplicate of https://github.com/Microsoft/vscode/issues/62970

**Closed** 2018-11-14 08:03 UTC
Labels: *duplicate, needs more info
