### ISSUE TITLE
Expand file link support to import statements in Javascript

### ISSUE THREAD

**Issue by nkalvi** [microsoft/vscode#91850] opened 2020-03-01 15:15 UTC
Please expand [file link](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_create-or-open-a-file) (quickly open a file or image or create a new file by moving the cursor to the file link and using Ctrl+click) support to `import` etc. in Javascript files and `<script>` blocks.

**Comment by sportshead** [comment] 2020-03-02 04:16
Currently opening the file is ok, but I think the problem is creating files. I'll work on a fix

**Comment by mjbvz** [comment] 2020-03-02 19:29
Duplicate of https://github.com/microsoft/TypeScript/issues/15146

**Closed by mjbvz** 2020-03-02 19:29 UTC
