### ISSUE TITLE
Allow logical file names

### ISSUE THREAD

**Issue by omeijer** [Microsoft/vscode#51068] opened 2018-06-04 07:24 UTC
It seems that VScode always use absolute file names in the browser and even in the rest of the API.
However it would be nice if we also allow logical file names. We have several other tools that cannot handle 
the case when the logical and physical file names are different. 
For example perforce really cannot handle this and forces us to keep changing the client over and over again.

If we somehow could switch between absolute or logical file names all this trouble will go away and
the tool will be much more usable from our point of view.

Just to be sure here is way I mean with logical and physical files/directories.

Logical name: /u/omeijer/src
Physical name: /remote/disk1/omeijer/src

**Comment by bpasero** [comment] 2018-06-04 08:06
@omeijer sorry I am having trouble to understand what issue you are seeing and what you suggest?

**Comment by omeijer** [comment] 2018-06-04 08:46
I'm not sure how VScode actually determines the complete path to a file.
I have the feeling that "readlink -f <file>" is used under the hood as always all links have been resolved.
This seems like a logical way to do however not all tools do it in a similar matter so this is causing havoc fur us.

Our IT department made sure that the /u link always points the the correct physical disk for all users.
So /u/omeijer in my case refers to /remote/disk1/omeijer.
VScode will always show me the /remote/disk1/omeijer tree and as a result also all extensions will handle all files names this way.
I would like to have a switch so we maintain the actual links so my tree will look like /u/omeijer.
That way all of our other tools keep working as they have been design to also work that way.

**Comment by bpasero** [comment] 2018-06-04 09:01
@omeijer thanks, I think this would qualify as a duplicate of https://github.com/Microsoft/vscode/issues/18837

As a workaround what you can do is craft a workspace file that looks like this:

```json
{
	"folders": [
		{
			"path": "<absolute path to the folder as symlink>"
		}
	]
}
```

Then save it as `workspace.code-workspace` file and open it via `File > Open Workspace`.

**Closed by bpasero** 2018-06-04 09:01 UTC
Labels: needs more info

**Comment by omeijer** [comment] 2018-06-04 09:33
I don't understand how this workspace.code-workspace file needs to work.
So let me try to give you an example how my environment looks:
With links:
/u/omeijer/catsSDE/35
Without links:
/remote/catsnl01/omeijer/catsSDE/35

Now these are directories with literally thousands of files and directories under them.

Your workspace file tells me that I need to specify an absolute path as a symlink.
This sort of is in conflict with it self. Either you have the absolute path with all the links resolved
or you don't.

You you give me an example how you would specify this given the above information?
