### ISSUE TITLE
Extremely slow on startup

### ISSUE THREAD

**Issue by ThakkarHitesh** [Microsoft/vscode#69560] opened 2019-02-27 22:11 UTC
My VS Code is extremely slow on start up. It takes about 55-65 seconds to start up before I can do do anything in it. The VS Code window doesn't appear up until about 30 seconds and then it take another 25-30 seconds to load. Not sure what's happening here. I did try to disable all installed extension but that didn't help so I don't think any installed extensions are causing this issue. 

It started happening couple of months ago. It only happens on the startup. 

Here is my "Startup Performance" 
## System Info

* Code: 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60)
* OS: win32(10.0.15063)
* CPUs: Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz(4 x 2208)
* Memory(System): 15.93 GB(6.12GB free)
* Memory(Process): 218.09 MB working set(224.04MB peak, 191.66MB private, 42.68MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                    | Duration | Process          | Info                                     |
| ------------------------------------------------------- | -------- | ---------------- | ---------------------------------------- |
| start => app.isReady                                    | 59       | [main]           | initial startup: true                    |
| nls:start => nls:end                                    | 0        | [main]           | initial startup: true                    |
| require(main.bundle.js)                                 | 110      | [main]           | initial startup: true                    |
| app.isReady => window.loadUrl()                         | 263      | [main]           | initial startup: true                    |
| require & init global storage                           | 41       | [main]           | initial startup: true                    |
| window.loadUrl() => begin to require(workbench.main.js) | 20456    | [main->renderer] | NewWindow                                |
| require(workbench.main.js)                              | 499      | [renderer]       | cached data: YES                         |
| init global storage                                     | 17       | [renderer]       | -                                        |
| require workspace storage                               | 4        | [renderer]       | -                                        |
| require & init workspace storage                        | 39       | [renderer]       | -                                        |
| init workspace service                                  | 11       | [renderer]       | -                                        |
| register extensions & spawn extension host              | 490      | [renderer]       | -                                        |
| restore viewlet                                         | 33       | [renderer]       | workbench.view.explorer                  |
| restore panel                                           | 0        | [renderer]       | -                                        |
| restore editors                                         | 380      | [renderer]       | 1: workbench.editors.untitledEditorInput |
| overall workbench load                                  | 522      | [renderer]       | -                                        |
| workbench ready                                         | 21869    | [main->renderer] | -                                        |
| extensions registered                                   | 22105    | [renderer]       | -                                        |

## Extension Activation Stats

| Extension                             | Eager | Load Code | Call Activate | Finish Activate | Event                                                                                        |
| ------------------------------------- | ----- | --------- | ------------- | --------------- | -------------------------------------------------------------------------------------------- |
| vscode.debug-auto-launch              | true  | 5         | 0             | 322             | *                                                                                            |
| vscode.emmet                          | true  | 3         | 1             | 321             | *                                                                                            |
| vscode.git                            | true  | 24        | 5             | 929             | *                                                                                            |
| vscode.merge-conflict                 | true  | 4         | 2             | 319             | *                                                                                            |
| alefragnani.numbered-bookmarks        | true  | 10        | 2             | 317             | *                                                                                            |
| christian-kohler.path-intellisense    | true  | 24        | 1             | 316             | *                                                                                            |
| eamodio.gitlens                       | true  | 23        | 1             | 1156            | *                                                                                            |
| EditorConfig.EditorConfig             | true  | 35        | 17            | 298             | *                                                                                            |
| esbenp.prettier-vscode                | true  | 112       | 11            | 287             | *                                                                                            |
| joelday.docthis                       | true  | 87        | 0             | 287             | *                                                                                            |
| karyfoundation.comment                | true  | 6         | 1             | 286             | *                                                                                            |
| ms-vscode.csharp                      | true  | 629       | 9             | 13349           | workspaceContainsTimeout:*.csproj,*.sln,*.csx,*.cake,**/*.csproj,**/*.sln,**/*.csx,**/*.cake |
| robertohuertasm.vscode-icons          | true  | 93        | 1             | 285             | *                                                                                            |
| slevesque.vscode-multiclip            | true  | 2         | 0             | 285             | *                                                                                            |
| streetsidesoftware.code-spell-checker | true  | 179       | 0             | 866             | *                                                                                            |
| waderyan.gitblame                     | true  | 32        | 6             | 279             | *                                                                                            |
| WallabyJs.quokka-vscode               | true  | 4         | 67            | 212             | *                                                                                            |
| vscode.extension-editing              | false | 15        | 1             | 211             | onLanguage:typescript                                                                        |
| vscode.markdown-language-features     | false | 81        | 4             | 6               | onLanguage:markdown                                                                          |
| vscode.typescript-language-features   | false | 17        | 194           | 18              | onLanguage:typescript                                                                        |
| eg2.tslint                            | false | 61        | 6             | 12              | onLanguage:typescript                                                                        |
| pmneo.tsimporter                      | false | 5         | 2             | 10              | onLanguage:typescript                                                                        |

## Raw Perf Marks

```
Name	Timestamp	Delta	Total
main:started	1551304808182	0	0
main:appReady	1551304808241	59	59
willLoadMainBundle	1551304808245	4	63
didLoadMainBundle	1551304808355	110	173
willRequireSQLite	1551304808378	23	196
main:willInitGlobalStorage	1551304808378	0	196
didRequireSQLite	1551304808385	7	203
willSetupSQLiteSchema	1551304808388	3	206
didSetupSQLiteSchema	1551304808417	29	235
main:didInitGlobalStorage	1551304808419	2	237
main:loadWindow	1551304808504	85	322
renderer/started	1551304828928	20424	20746
willShowPartsSplash	1551304828934	6	20752
didShowPartsSplash	1551304828934	0	20752
willLoadWorkbenchMain	1551304828960	26	20778
didLoadWorkbenchMain	1551304829459	499	21277
main/startup	1551304829459	0	21277
willInitWorkspaceService	1551304829486	27	21304
willInitGlobalStorage	1551304829486	0	21304
willInitWorkspaceStorage	1551304829489	3	21307
willRequireSQLite	1551304829490	1	21308
didRequireSQLite	1551304829494	4	21312
willSetupSQLiteSchema	1551304829497	3	21315
didInitWorkspaceService	1551304829497	0	21315
didInitGlobalStorage	1551304829503	6	21321
didSetupSQLiteSchema	1551304829528	25	21346
didInitWorkspaceStorage	1551304829528	0	21346
willStartWorkbench	1551304829529	1	21347
willRestoreEditors	1551304829656	127	21474
willRestoreViewlet	1551304829656	0	21474
willResolveExplorer	1551304829670	14	21488
LifecyclePhase/Ready	1551304829687	17	21505
didRestoreViewlet	1551304829689	2	21507
willLoadExtensions	1551304829797	108	21615
didRestoreEditors	1551304830036	239	21854
LifecyclePhase/Restored	1551304830036	0	21854
didStartWorkbench	1551304830051	15	21869
didResolveExplorer	1551304830075	24	21893
extensionHostReady	1551304830283	208	22101
didLoadExtensions	1551304830287	4	22105
LifecyclePhase/Eventually	1551304832539	2252	24357
```

**Comment by usernamehw** [comment] 2019-02-28 00:37
Possible duplicate of #56644

**Comment by rebornix** [comment] 2019-02-28 01:00
@ThakkarHitesh can you try a custom build with Electron 4 to see if this problem is fixed https://github.com/Microsoft/vscode/issues/56644#issuecomment-448104616 ?

**Closed** 2019-03-04 13:52 UTC
Labels: *duplicate, needs more info, perf-profile
