### ISSUE TITLE
Tab Size ignored on code auto format  (intermittent)

### ISSUE THREAD

**Issue by supoved** [Microsoft/vscode#16264] opened 2016-11-30 11:01 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 3.13.0-101-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|puppet|Borke|0.3.0|
|jslint|ajhyndman|1.2.1|
|vscode-eslint|dbaeumer|1.1.0|
|Angular1|johnpapa|0.1.16|
|debugger-for-chrome|msjsdiag|2.2.2|
|vscode-icons|robertohuertasm|4.0.2|
|code-spell-checker|streetsidesoftware|0.12.0|

---

Steps to Reproduce (intermittent):

I have not figured out what steps exactly causing issue to happen, but I encounter it 5-6 times a day.

1. set user preferences: "editor.tabSize": 2,
2. unknown action
3. auto format file
4. file will be formatted with 4 spaces instead of 2

Observations: 
- issue happens on single file, other opened files are not affected
- pressing TAB creates correct (2 spaces) indentation
- closing file doesnt fix it, only closing whole studio

**Comment by chrmarti** [comment] 2016-11-30 17:11
@supoved Is this with JavaScript files?

**Comment by supoved** [comment] 2016-12-02 08:49
@chrmarti yes, it happens in js files.

**Comment by supoved** [comment] 2016-12-02 08:53
@jrieken I have this issue happening on one of the files at the moment. I can collect any state information, if you tell me what exactly you need. Thou I still have no idea what exactly needs to happen to cause it, just randomly happens and stays until vs code is closed and reopened.

**Comment by chrmarti** [comment] 2016-12-02 20:20
@waderyan Might be #15316?

**Comment by supoved** [comment] 2016-12-08 13:45
Seems to be the duplicate of #15316.
Just some additional info it seems the bug happens only on functions with ES6 notation.
`() => {
...
}`
and not affecting
`function() {
...
}`

**Comment by waderyan** [comment] 2016-12-10 00:06
Closed as duplicate of #15316. 

@supoved thanks for moving your comment to that issue.

**Closed by waderyan** 2016-12-10 00:06 UTC
Labels: format, javascript
