### ISSUE TITLE
Creating a new profile fails as vscode doesn't register options 

### ISSUE THREAD

**Issue by celestialcato** [microsoft/vscode#225387] opened 2024-08-12 08:30 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1
- OS Version: Windows 11 23H2 22631.3880

Steps to Reproduce:

1. Select new profile from settings menu -> profile.
2. Remove any of the default checkmarks under "Choose what to configure in your Profile:" or pick any item from "Copy from" list.
3. All checkmarks are now gone and can't be selected again. Profile creation fails with the message "The profile should contain at least one configuration." 

I was able to reproduce the bug on my local installation of vscode, new installation of vscode in Windows sandbox and in vscode.dev

Here's a video of the bug:

https://github.com/user-attachments/assets/9bae8180-f6c3-46e4-a82d-14a669ec70dd

**Comment by gjsjohnmurray** [comment] 2024-08-12 10:03
/duplicate of #224788 which offers a workaround

**Closed** 2024-08-12 10:03 UTC
Labels: *duplicate, triage-needed, new release
