### ISSUE TITLE
TS Server fatal error:  Cannot read properties of undefined (reading 'charCount')

### ISSUE THREAD

**Issue by Austin-Garlick** [microsoft/vscode#231073] opened 2024-10-10 22:51 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.3

**Steps to reproduce crash**

1. Just working with .ts files
2. and the error appeared in the corner

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.59GB (3.33GB free)|
|Process Argv|. --enable-proposed-api genuitecllc.codetogether --crash-reporter-id d45ffe7d-275c-4d8a-94aa-886333b7a132|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.2
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
gc-excelviewer|Gra|4.2.62
rainbow-csv|mec|3.12.0
csdevkit|ms-|1.11.14
csharp|ms-|2.50.25
vscode-dotnet-runtime|ms-|2.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.8
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|5.11.1
r|REd|2.8.4
LiveServer|rit|5.7.9
firacode|Sey|2.2.1
even-better-toml|tam|0.19.2
pdf|tom|1.2.2
cmake|twx|0.0.17
vscode-icons|vsc|12.9.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31151523
controlgs:31153265
5fd0e150:31155592

```

</details>

**Comment by mjbvz** [comment] 2024-10-29 20:39
Duplicate of https://github.com/microsoft/typescript/issues/60118

**Closed by mjbvz** 2024-10-29 20:39 UTC
