### ISSUE TITLE
HTML <script> tags containing HTML are not rendered with syntax colourization any longer

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vscode#25931] opened 2017-05-04 21:00 UTC
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:18:34.633Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|swagger-viewer|Arjun|1.4.0|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.12.0|
|vscode-firefox-debug|hbenl|0.12.1|
|typelens|kisstkondoros|1.4.1|
|swagger-doc-viewer|mimarec|1.0.4|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|vs-keybindings|ms-vscode|0.1.3|
|azurerm-vscode-tools|msazurermtools|0.3.4|
|debugger-for-chrome|msjsdiag|3.1.1|
|swaggitor|qnsolutions|0.1.1|
|qub-msbuild|qub|0.6.3|
|swagger-linter|vscode|0.6.0|;

---

Steps to Reproduce:

1. Create an HTML file containing the following:
<!DOCTYPE html>
<html>
<head>
    <title>Sample App</title>
    <meta charset="utf-8">
</head>
<body>
<h1>Hello World</h1>
<script type="text/html" id="doc-dialog">
    <div class="modalDialogBody" style="width: 200px;height: 200px; color: white; background-color: black;">
        <span>Text in the dialog</span>
    </div>
</script>
</body>
</html>

2. Notice that the text within the <script></script> block is not rendered with colourization, whereas the html outside the script element is.

**NOTE: Started to occur in 1.12.0, did not occur in 1.11.0.**

**Comment by mjbvz** [comment] 2017-05-04 21:07
Duplicate of #25920. We're looking into the problem

**Closed by mjbvz** 2017-05-04 21:07 UTC
Labels: duplicate
