### ISSUE TITLE
High RAM and CPU usage

### ISSUE THREAD

**Issue by kaygeeklaas** [microsoft/vscode#84585] opened 2019-11-12 12:05 UTC
- VSCode Version:
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0

- OS Version:
OS: Windows_NT x64 10.0.18362
8gig RAM
Intel Core i5

Steps to Reproduce:
Every time i start coding, in just seconds my **CPU** usage hits the **90%** mark and my **RAM** **1.7gig** even though i have one project/tab open, when i check my task manager visual studio code is the culprit as this causes the application to be less responsive and very slow, seconds after i have stopped coding my CPU  goes back to normal and the RAM that one open project/tab uses also goes back to about **600mb**. The problem started after the VERSION 1.39 and i thought it was a bug VS team would fix but in version 1.40 the problem seems to persist

Does this issue occur when all extensions are disabled?: Yes
Except for Node Debug which does not want to disable as it gives me the following message

> Cannot disable extension 'Node Debug'. Extension 'Node Debug (legacy)' depends on this.

**Comment by IllusionMH** [comment] 2019-11-12 13:20
> Does this issue occur when all extensions are disabled?: Yes
Except for Node Debug which does not want to disable as it gives me the following message

You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled` which should reload VS Code window disable all extensions at once

**Comment by rebornix** [comment] 2019-11-12 21:25
Please provide more info per https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by rbasto1** [comment] 2019-11-14 12:30
I'm affected by the same issue. I'm not sure about the RAM part, since I wasn't tracking how much RAM the process needed before, but since 1.39 my CPU fan has been constantly on high speed when I code. I've tried using it in a session with ">Developer: Reload Window With Extensions Disabled" and the problem persists. Task monitoring shows process "code" as the highest consumer of CPU time.
I've also downgraded to TypeScript 3.6 to see if 3.7 was part of the problem but still CPU stayed high, so it appears the issue is isolated to vscode.
It only uses CPU cycles while actually coding though. Keeping a vscode window open in the background does not seem to drag CPU time.

OS: Linux 5.3.0-22 Ubuntu 19.10 eoan

Thanks!

**Comment by abellynow** [comment] 2019-11-14 13:37
I have this issue as well and have had for quite a while. In my case it seems to accumulate. So a freshly started instance of VSCode feels pretty snappy (relatively but see below for CPU utilization) but after a while typing, scrolling and moving the cursor is extremely laggy and sometimes stop being interactive at all for a couple of seconds. `top` then says the laggy instance of VSCode uses >125%CPU.

Doing the ">Developer: Reload Window With Extensions Disabled" improves it slightly (at least at first, but then again just a reload would probably do that) but scrolling through a C++ file still takes >65% CPU which feels a bit over the top on an Intel i7.

With the `cpptools` extension enabled scrolling through a C++ file consumes >95% CPU in the "fresh" state and >125% in the "laggy" state.

The C++ file used is about 700 lines of code so nothing extreme.

Main coding language: C++
Extensions: cpptools
OS: Linux 5.0.0-32 Ubuntu 18.04.2
CPU: Intel i7-8850H

**Comment by hyarionh** [comment] 2019-11-29 07:17
I believe this is due to a bug in tsserver.js that has been introduced since 1.40.x.  I've given more information in #85777.  

Essentially it's not abiding by the memory limit and after a while something goes wrong and it rapidly using up 100% RAM and 100% of a CPU core.  When this happens VSCode will feel "slow", "sluggish" and intellisense will either stop working or be very slow.

Everything appears to work fine in VSCode 1.39.2.

**Comment by solodon4** [comment] 2020-01-16 09:57
I see the same on Mac OS (Catalina):
```
PID    COMMAND      %CPU TIME     #TH   #WQ  #PORTS MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS         %CPU_ME %CPU_OTHRS UID  FAULTS    COW   MSGSENT    MSGRECV   SYSBSD     SYSMACH   CSW
99398  Microsoft.VS 92.5 33:36.62 15/1  0    29     148M-  0B     19M    99375 99386 running  *0[1]          0.00000 0.00000    501  642515+   253   10874      5398      125242959+ 37643+    2698844+
```
Just opening C++ folder with some sub-projects

**Comment by egamma** [comment] 2020-09-15 20:14
@diamondhat since this is happening with a C++ project, please report the issue against the C++ extension.

**Comment by egamma** [comment] 2020-11-05 08:16
Closing - the original issue doesn't provide sufficient information to act on the performance problems.

The follow-up performance comments are appreciated, but they should be filed as separate issues following the https://github.com/microsoft/vscode/wiki/Performance-Issues guidelines.

**Closed by egamma** 2020-11-05 08:16 UTC
