### ISSUE TITLE
Open js file always alert a WARN!!

### ISSUE THREAD

**Issue by jadestrong** [Microsoft/vscode#19999] opened 2017-02-06 02:17 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.13.2|
|tagged-comment|alefragnani|0.3.0|
|vscode-standardjs|chenxsan|1.0.8|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-yaml-validation|djabraham|0.0.1|
|python|donjayamanne|0.5.8|
|tortoise-svn|fantasytyx|0.1.1|
|Theme-Humane|gerane|0.0.2|
|vscode-emacs|hiro-sun|0.1.1|
|beautify|HookyQR|0.7.3|
|docthis|joelday|0.3.6|
|ionic1-snippets|justinjames|1.0.1|
|center-editor-window|kaiwood|2.0.2|
|csharp|ms-vscode|1.6.2|
|vscode-icons|robertohuertasm|7.1.2|
|dark-plus-material|vangware|0.2.1|

---

Steps to Reproduce:

1. Open JavaScript file will report `The TypeScript language service died unexpectedly 5 times in the last 5 Minutes infinite loop` .
2.  Always report `The path c:\Program Files(x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib doesn't point to a valid tsserver install.Fa...`

**Comment by mjbvz** [comment] 2017-02-06 20:22
From the symptoms, this looks like a duplicate of #19814. In that case, some antivirus program was deleting VSCode's TypeScript server files. Reinstalling VSCode should fix this.

If you see this again, please add the `typescript` path mentioned in the error message to the exemption list for the antivirus program. You can also bring your own version of TypeScript: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Closed by mjbvz** 2017-02-06 20:22 UTC
Labels: duplicate, javascript, typescript
