### ISSUE TITLE
Debug console doesn't print program output

### ISSUE THREAD

**Issue by tetsuo** [microsoft/vscode#103834] opened 2020-08-03 14:04 UTC
- VSCode Version: 1.47.3
- OS Version: macOS Catalina 10.15.5
- Node.js Version: 12.6.2

Steps to Reproduce:

1. Create a `launch.json` file with the default contents:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/main.js"
    }
  ]
}
```
2. Create a `main.js` file with a single `console.log` statement

```javascript
console.log(1)
```

3. Launch the program (`main.js`). Debug console outputs:

```
Debugger attached.
Waiting for the debugger to disconnect...
Process exited with code 0
```

If I add a `debugger` or `setTimeout` in `main.js`, it works normally.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by tetsuo** [comment] 2020-08-03 14:08
This problem doesn't seem to occur when `outputCapture` is set to `std`

**Comment by isidorn** [comment] 2020-08-03 14:39
Works for me. Can you reproduce with vscode insiders?

![Screenshot 2020-08-03 at 16 38 46](https://user-images.githubusercontent.com/1926584/89194560-d2233980-d5a7-11ea-9560-4afb7b3ae0b5.png)

**Comment by tetsuo** [comment] 2020-08-03 16:14
I have only this version of VScode installed. For me, it doesn't work. Sometimes it does, 1 out of 30 tries I can see the output.

![Screen-Recording-2020-08-03-at-1](https://user-images.githubusercontent.com/50026/89203578-136e1600-d5b5-11ea-9041-c1aa140fe5d2.gif)

**Comment by isidorn** [comment] 2020-08-03 16:19
Forwarind to @connor4312 as he owns the js-debug and this is coming from the debug estension

**Comment by connor4312** [comment] 2020-08-03 16:22
This was fixed in  https://github.com/microsoft/vscode-js-debug/commit/02f9147456d23bdda8f81c55679060af995b2b1f and available in the nightly build: https://github.com/microsoft/vscode-js-debug#nightly-extension

/duplicate

**Closed** 2020-08-03 16:28 UTC
Labels: *duplicate, debug, needs more info
