### ISSUE TITLE
Reveal In File Explorer opens a window for each nested folder

### ISSUE THREAD

**Issue by javskd** [microsoft/vscode#110353] opened 2020-11-10 22:00 UTC
- VSCode Version: 1.51.0
- OS Version: Windows 10.0.19041

Steps to Reproduce:

1. Create a nested folder (such as this one created by cmake) 
![image](https://user-images.githubusercontent.com/66739850/98738297-7d951480-2375-11eb-8988-49543ba94ec3.png)
2. Select the folder by clicking on it
3. Right click on empty space in the explorer tab (not directly on the folder), and choose Reveal In File Explorer

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2020-11-10 22:15
I think your problem is related to step 3. What happens if you just right click on the folder and choose Reveal In File Explorer?

I'm not able to reproduce this. Could you pls try the above and attach a [gif](https://gifcap.dev/)?

**Comment by isidorn** [comment] 2020-11-11 08:56
@meganrogge thanks for trying out. However I can reproduce this on my mac.
The trick is to have a compact folder selected, and click on an empty explorer area to repro

**Comment by isidorn** [comment] 2020-12-04 10:59
Had to revert his commit, thus reopening and assigning to backlog since this is not such a big issue

**Closed** 2021-02-02 12:59 UTC
Labels: *out-of-scope, bug, file-explorer
