### ISSUE TITLE
Keyboard shortcut editor.action.selectHighlights selects only first 999 matches

### ISSUE THREAD

**Issue by coe-jeubanks** [Microsoft/vscode#11973] opened 2016-09-13 18:00 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:
1. Create a file with more than 999 examples of a text string (e.g. 2,000 lines containing "This is a line").
2. Highlight a word or phrase, and to highlight all matches, press ctrl+shift+l (or whatever editor.action.selectHighlights has been mapped to).

Only the first 999 matches will be selected. This is a problem when working with large files.

**Comment by Bill-Stewart** [comment] 2016-09-13 20:35
Just wondering if `editor.action.changeAll` (default `ctrl+f2`) has the same behavior?

**Comment by coe-jeubanks** [comment] 2016-09-13 21:37
Yes, editor.action.changeAll exhibits the same behavior. I realized after posting this issue that it's likely an arbitrary cutoff for performance purposes. To be my go-to text editor, however, VS Code really needs to add the ability to edit large files. I hope that's on the horizon.

**Comment by Bill-Stewart** [comment] 2016-09-13 21:41
Or at least make it user configurable...

**Comment by coe-jeubanks** [comment] 2016-09-13 21:47
I should note that the regular Replace function (ctrl+H) replaces as many matches as it can find in the file. In the Find dialog box, it shows "1 of 999+", and the ToolTip says "Only the first 999 results have been highlighted, but all Find operations work on the entire text". Seems to me this philosophy should be extended to editor.action.selectHighlights and editor.action.changeAll operations.

**Comment by Bill-Stewart** [comment] 2016-09-16 21:51
Related to https://github.com/Microsoft/vscode/issues/7577 ?

**Comment by ToMakeSense** [comment] 2017-07-19 02:44
Related to [#7201](https://github.com/Microsoft/vscode/issues/7201), all kinds of  _999 Issues_.

**Comment by ToMakeSense** [comment] 2017-08-16 17:30
@alexandrudima I think I have find the reazon for this bug:
1. see this  issues [#15778](https://github.com/Microsoft/vscode/issues/15778)
**Ctrl+F** then **Alt+Enter** will work for "editor.action.selectHighlights"

2. But **ctrl+shift+L** does't. Look at the settings
![image](https://user-images.githubusercontent.com/6244148/29376085-f7b936e0-82e9-11e7-83ac-ecbfb9e82e35.png)
![image](https://user-images.githubusercontent.com/6244148/29376140-2d55a856-82ea-11e7-87a0-787d43055361.png)
I think the **ctrl+shift+L** should bind to **editor.action.selectAllMatches** when **editorTextFocus** or **editorFocus**

**Comment by Mischala** [comment] 2017-08-30 22:09
So, I wrote about this in #7201 but its worth mentioning here.
> Line 173 of findModel.ts references a "MATCHES_LIMIT", that is a constant, set on line 70 of the same file.
> This appears to be the root of the problem.
> I expect the reason this limit exists is to stop "Bad Searches" like searching for "s" or whitespace from running forever and locking up the app.

**Comment by alexandrudima** [comment] 2017-09-28 09:57
Duplicate of #5887

**Closed by alexandrudima** 2017-09-28 09:57 UTC
Labels: bug, editor-1000-limit, feature-request
