### ISSUE TITLE
Use default Format options in Extensions

### ISSUE THREAD

**Issue by kasik96** [Microsoft/vscode#940] opened 2015-12-02 19:48 UTC
Hi, i writing an extension to VS Code, but i dont find any way to be able use VS Code Formating on my Strings (Like HTML and JS Format separatly). Any plans to add it?

**Comment by alexandrudima** [comment] 2015-12-03 10:41
@jrieken Would this be enabled by the commanding work?

**Comment by jrieken** [comment] 2015-12-03 11:14
Unsure if I understand correctly. @kasik96 Do you want to be able to format a substring of a document, e.g. a string literal inside a JS file, or do you want to contribute a formatter for that targets string literals?

**Comment by kasik96** [comment] 2015-12-03 11:37
Ok, example of my use:
I make a PHP Format, but lot of people use HTML with PHP in it. So first i use my PHP Format and after it on the same String(etc. Code i wrote) i want to use VS Code native HTML format. But i dont find any way to use VS Code HTML format on String.


Best regards,
--
Martin Kaše
+420 776 819 817 | kasemartin@icloud.com | www.kasemartin.cz

**Comment by jrieken** [comment] 2015-12-03 12:49
In theory with the updating release you will be able to invoke the  `vscode.executeFormatDocumentProvider`-command to get all format edits for a given document but it will recurse it yourself again. So be cautious with that. 

Despite, I believe the proper way to address this is using scopes. That is when registering your php formatter you can say: _this is for php-files and the php-portion of html files_ with a `DocumentSelector` like this `['php', { language: 'html', scope: 'php.scope'}]`. 

This issue is related (maybe a dup) of #580.

**Comment by jrieken** [comment] 2015-12-03 12:51
Also related (maybe dup) of #719

**Comment by jrieken** [comment] 2015-12-03 12:52
@alexandrudima @aeschli Mixed modes are a topic we should figure out how to handle

**Comment by mjbvz** [comment] 2017-11-08 23:26
Duplicate of #14447

See [this comment](https://github.com/Microsoft/vscode/issues/14447#issuecomment-262736975) for more information about the issue

**Closed by mjbvz** 2017-11-08 23:26 UTC
Labels: duplicate, feature-request
