### ISSUE TITLE
Release notes view loads at top

### ISSUE THREAD

**Issue by str** [microsoft/vscode#95446] opened 2020-04-16 12:56 UTC
When loading a release notes tab, scroll down to read the content,  then opening a file tab to see how things work, when I return to the release notes tab, the content reloads, moving the scroll to the top, and I need to find again where I was reading, making it very hard to apply changes like config flags.

- VSCode Version: 1.44.1
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Open "help -> release notes"
2. Scroll down 
3. Open any other file
4. Return to the "release notes" tab

The "release notes" tab scroll should be where you left it. Instead, it's reset to the top

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-04-16 12:59
/duplciate of #94945 and related to #27498

**Comment by IllusionMH** [comment] 2020-04-16 13:05
/duplicate of #94945 and related to #27498

(sorry for second message, type in first didn't trigger bot)

**Closed** 2020-04-16 13:05 UTC
Labels: *duplicate
