### ISSUE TITLE
VScode default terminal defaults to powershell even after chaning

### ISSUE THREAD

**Issue by DevUt** [microsoft/vscode#132387] opened 2021-09-05 12:30 UTC
Issue Type: <b>Bug</b>

When we run open any folder the default terminal is powershell, even extensions are executing on powershell. But if we open a terminal it would open the one we changed to (in my case cmd).
Also in C/C++
After compilation the program is being runned in powershell, even though my default terminal is something else.
This is happening since the last update 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.45GB free)|
|Process Argv|--crash-reporter-id c414595e-a8a9-4a36-a92f-ac5b56f91dbf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
competitive-programming-helper|Div|5.8.7
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
android-system-tools|fli|0.0.2
code-runner|for|0.11.5
msys2|fou|0.9.0
latex-workshop|Jam|8.20.2
better-cpp-syntax|jef|1.15.6
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4761
java|red|0.81.0
LiveServer|rit|5.6.1
rust|rus|0.7.8
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
snippet-creator|wwa|1.1.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn420:30356812
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by xon52** [comment] 2021-09-05 12:54
Git Bash is also no longer recognised and I am rather upset. There is an option for the new profiles format for "Git Bash" but a) it doesn't do anything, and b) cannot be defaulted to.

![image](https://user-images.githubusercontent.com/30713944/132127516-c5e21196-e034-48d1-bec7-96d3943db900.png)

**Comment by gjsjohnmurray** [comment] 2021-09-05 13:25
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-05 13:26 UTC
Labels: *duplicate, new release
