### ISSUE TITLE
VS Code stopped showing images and text below and above it

### ISSUE THREAD

**Issue by bhaswata08** [microsoft/vscode#171613] opened 2023-01-18 13:48 UTC
Type: <b>Bug</b>

VS Code stopped showing images and text below and above it in jupyter notebooks. 

~~~
# 1. Why do we need measures of spread and centrality?

Motivation: Summarize Big data

![image.png](attachment:image.png)

* Drawing plots can give a good visual summary
* In some situations, we want an even more succinct summary(describe the data in a single/ few numbers)

Use summary statistics for quantitative data
* Measures of centrality: mean, median, mode
* Measures of spread: range, variance, standard deviation, IQR
* Percentiles: quartiles, quintiles, deciles
~~~

code snippet such as this shows a blank cell. 

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.71GB free)|
|Process Argv|--user-data-dir C:\\Users\\MSI uSER\\AppData\\Roaming\\.anaconda\\navigator\\.anaconda\\navigator\\Code --crash-reporter-id ce9b9eb6-5bf2-4dc1-89cb-a1d39797086a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.67.7944
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.13
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.72.0
azure-account|ms-|0.11.2
code-spell-checker|str|2.14.0
usql-vscode-ext|usq|0.2.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
89544117:30613380
fim-prod:30623723
2i9eh265:30646982

```

</details>

**Comment by mjbvz** [comment] 2023-01-19 00:41
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12568

**Closed by mjbvz** 2023-01-19 00:41 UTC
