### ISSUE TITLE
How to hide the information displayed on the left side?

### ISSUE THREAD

**Issue by yanyu2015** [microsoft/vscode#192860] opened 2023-09-12 10:01 UTC
```
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

I'm using a .py file and running my code using "run selected code in interactive window" (which opens a notebook on the right side), but in the latest version of VS Code, when my program outputs an error message, a bunch of file link information is displayed on the right side, as shown in the image below:
![image](https://github.com/microsoft/vscode/assets/11142054/8603c6d8-42a2-4494-9144-5b8a4f5f38c4)
![image](https://github.com/microsoft/vscode/assets/11142054/d99258ad-2ff6-4e7d-b20c-07b1742b5b60)

So, how can I hide this information and get back to the previous display format?
My screen width is not sufficient to display such wide content, and they are so long and redundant that I can't determine which line of code is causing the issue.

**Comment by amunger** [comment] 2023-09-12 18:03
duplicate of https://github.com/microsoft/vscode/issues/192605
this is a regression in 1.82, I'm working on getting the fix out.

**Closed by amunger** 2023-09-12 18:03 UTC
