### ISSUE TITLE
comments are not premitted in json

### ISSUE THREAD

**Issue by fawdlstty** [Microsoft/vscode#40611] opened 2017-12-21 01:36 UTC
- VSCode Version: last version
- OS Version: win10

Steps to Reproduce:

1. 打开任意一个json文件，包括//注释或者/**/注释
2.注释下面将会出现一条红色的波浪线，提示内容为“Comments are not premitted in JSON”

Reproduces without extensions: Yes/No

**Comment by KamasamaK** [comment] 2017-12-21 03:31
This is not a bug and is addressed in the [release notes](https://code.visualstudio.com/updates/v1_19#_json-with-comments).

**Closed** 2017-12-21 09:51 UTC
Labels: as-designed
