### ISSUE TITLE
JavaScript IntelliSense doesn't recognize "this" inside the functions of literal objects

### ISSUE THREAD

**Issue by n-peugnet** [Microsoft/vscode#28071] opened 2017-06-05 22:51 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-light|anoff|1.0.3|
|path-intellisense|christian-kohler|1.4.2|
|vscode-npm-script|eg2|0.2.0|
|ejs-language-support|QassimFarid|0.0.1|
|seti-icons|qinjia|0.1.3|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|theme-setimonokai|SmukkeKim|0.0.1|
|language-pde|Tobiah|0.1.21|;

---

``` JavaScript
var test = {
	truc: 'bidule',
	methode() {
		return this.truc;
	}
}
```
in this example, "this" is not referenced as the current object ("test") but as "any" in IntelliSense

**Comment by mjbvz** [comment] 2017-06-05 23:39
Thanks. This is a duplicate of https://github.com/Microsoft/TypeScript/issues/16184

**Closed by mjbvz** 2017-06-05 23:39 UTC
Labels: duplicate, javascript, upstream
