### ISSUE TITLE
Commit amend loses multiline format in commit message

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#40295] opened 2017-12-15 13:01 UTC

**Comment by pmiossec** [comment] 2018-01-24 23:54
I think that when this issue will be addressed, some more work must me done to improve "amend" feature ergonomy.

I think we should be able, with vscode, to amend only the commit message. At the moment, we **must** commit changes in the same time.

I also think that we should not use the command palette to edit the commit message like it's done at the moment...

I propose that:
* we first decide that we will amend the commit
* then, if the commit message field is empty, it is filled with the commit message of the commit that will be amended. (I don't exactly know what to do If there is already something entered. Perhaps we could have an option to do either "nothing", or appened the previous commit message on a new line)
* the user is then able to change the commit message (this solve this issue because you can enter a multiline commit message 😄 )
* when commiting, the commit is amended

PS: we could add an option somewhere to "stop" amending the commit if the user decide not to do it in the end....

**Comment by cavehill** [comment] 2018-01-29 12:07
Any idea when this fix will be implemented?

Thanks!

**Comment by dantman** [comment] 2018-04-02 01:58
If you need a workaround, this works beautifully in the integrated terminal:
```bash
EDITOR="code -w" git commit --amend
```

I actually put this in my `~/.bash_profile`:
```bash
if [ ! -z "$VSCODE_IPC_HOOK" ]; then
	# Use vscode as the editor for things like Git when run from within vscode's integrated terminal
	export EDITOR="code -w"
fi
```

Now every time I do git things like `git commit --amend` from within the integrated terminal vscode itself is used as the editor for commit messages. I can edit within vscode with all the syntax highlighting and special functionality. Then just save and close the tab to finish the commit.

**Comment by segevfiner** [comment] 2018-10-07 19:57
Atom's implementation of this is quite nice. It has an amend checkbox which brings the "commit to be amended" commit message, and files, into the UI. This allows you to remove files from the commit by "unstaging" (Not sure what this does in the underlying Git repository) them in the UI, and you can edit the commit message using the same UI as a normal commit. Avoiding a problem like this.

**Comment by danielo515** [comment] 2019-01-28 19:34
Still an issue in 2019. I miss some input from the VSCode team...

**Comment by LenzGr** [comment] 2019-02-27 13:00
Just stumbled over this one myself several times now. Any update/feedback on this one? It's cumbersome having to switch to a shell to run `git commit --amend` to maintain the formatting...

**Comment by Wiz1999** [comment] 2019-04-29 17:36
Any update?

**Comment by coffenbacher** [comment] 2019-06-16 17:20
This pretty much breaks amend functionality for my team, it would be really great if this gets fixed eventually.

**Comment by ADIX7** [comment] 2019-07-17 16:11
Any info on this?

**Comment by pmiossec** [comment] 2019-07-19 13:13
I just see that the [GitPod service](https://www.gitpod.io/) which use the [theia editor](https://github.com/theia-ide/theia) (which is based on VSsCode) is doing it very well!

If that inspired someone to do it...And perhaps even get some code from the project...

**Comment by gabeschine** [comment] 2019-08-13 21:23
I am also running into this bug. Would really appreciate un-breaking the amend flow!

**Comment by Shaun-Cox** [comment] 2019-10-17 18:21
Another vote that this get fixed.  I ammend my commit all the time until merge and I hate losing the newlines in my commit message.

**Comment by jorhett** [comment] 2019-10-17 19:42
It appears that @joaomoreno will spend hours identifying reports from all the other people annoyed by this, but nobody will spend an hour to fix it

**Comment by aureliojargas** [comment] 2019-11-27 16:13
A quick update on @dantman nice [workaround](https://github.com/microsoft/vscode/issues/40295#issuecomment-377836065). At least on my machine (Windows 10, VS Code using Git Bash as the terminal), the `VSCODE_IPC_HOOK` env variable is not defined. But I have `TERM_PROGRAM=vscode`. So that's what's working for me:

```bash
if test "$TERM_PROGRAM" = vscode; then
    # Use vscode as the editor for things like Git when run from within vscode's integrated terminal
    export EDITOR="code -w"
fi
```

**Comment by jorhett** [comment] 2019-12-01 22:38
@jrial The only person here "lashing out" is you. I made a simple statement in roughly a dozen words that does nothing more than reflect the facts visible to anyone who reads the issue.

And to answer the core of your point, no really I don't see the "measurable improvement" -- I see months of effort put in colors and icons, while fairly basic Git usage is 1/4 to 1/3 implemented AT BEST. We are trying very hard to make use of VS Code, but nearly every day to day operation forces people back to the CLI. IMHO, why bother?

The fact that critical and common Git usage scenarios are all broken, and years go by without even acknowledgement of the issue further proves my point. It's a pretty toy, but until they care about doing Git operations correctly and easily it's functionally useless.

**Comment by jorhett** [comment] 2019-12-01 22:43
@jrial said it best
> 2. There's a perfectly good workaround: the git CLI, or another graphical git frontend.

If you've found this issue because this annoys you, you're gonna find a dozen more like it. Everyday common Git functionality is broken or not implemented in VS Code. The developers won't even acknowledge or update the issues, but they'll ream you for daring to speak up about them. As he said, if you use Git you should find something different.

**Comment by orgads** [comment] 2020-01-29 21:55
I pushed a fix proposal.

**Comment by mix3d** [comment] 2020-04-16 18:58
> I pushed a fix proposal.

link to the PR?

**Comment by pmiossec** [comment] 2020-04-16 19:12
@mix3d the notification just before the comment?

**Comment by devanshj** [comment] 2020-05-17 21:20
I have a gift for ya'll xD

![](http://g.recordit.co/db6BhR4mxd.gif)

**Comment by mix3d** [comment] 2020-05-17 21:36
> I have a gift for ya'll xD

Yussss!

**Comment by jorhett** [comment] 2020-05-17 21:37
When does it land?

**Comment by devanshj** [comment] 2020-05-17 21:39
> THANK YOU!!! When does it land?

YOU'RE WELCOME!!! Idk depends when it gets merged, once thats done probably will be available nightly. In stable it will probably land in month-end afaik

**Comment by jrial** [comment] 2020-05-18 06:27
> I have a gift for ya'll xD

Yay! And it's not even my birthday!

One question though: the input box for regular commits treats an <Enter> as a newline, and <Ctrl>+<Enter> submits (aka commits). I notice that your solution uses a different scheme: <Shift>+<Enter> for newline and <Enter> commits. I take it there was no way to preserve the original behaviour?

**Comment by devanshj** [comment] 2020-05-18 15:49
> One question though: the input box for regular commits treats an Enter as a newline, and Ctrl+Enter submits (aka commits). I notice that your solution uses a different scheme: Shift+Enter for newline and Enter commits. I take it there was no way to preserve the original behaviour?

Comparison with regular commit ui won't be fair because it's not a solution to this issue per se but it's an feature for the `showInputBox` api ie the quick pick ui which treats enter as submit so it would be better to keep it like that for multiline also.

**Comment by jrial** [comment] 2020-05-18 20:55
> Comparison with regular commit ui won't be fair because it's not a solution to this issue per se but it's an feature for the `showInputBox` api ie the quick pick ui which treats enter as submit so it would be better to keep it like that for multiline also.

Ah, so this is an intermediate solution then? Not dissing your work, btw. Obviously I'm happy with the improvement. Just curious about where this particular issue is ultimately headed.

**Comment by devanshj** [comment] 2020-05-18 21:10
> Ah, so this is an intermediate solution then?

Umm no? I have also stated in the proposal on why what you're suggesting is a bad idea. You can back your suggestion and explain it there. Also I'll make myself more clear: I'm saying it's a bad idea because the api will be used by other extensions in other scenarios too, so designing the behavior keeping how git extension would use it won't be fair.

> Not dissing your work, btw. 

Dw you're good

>  Just curious about where this particular issue is ultimately headed.

According to me I think the proposed user experience is good enough which would solve the current issue, ultimately it would be whatever the vscode team agrees to.

**Comment by danielo515** [comment] 2020-05-20 11:09
I think that a good workaround would be to add another amend option to VSCode that uses `--no-edit`. Most of the time, I don't want to edit the commit message and this will preserve the line breaks.

**Comment by heartacker** [comment] 2020-08-07 12:48
Close to 3 years,......
I think that it will be better that user click `amend` that vscode copy the last-commit message to the commit-input-box. that user can edit again or just click `cmomit` continue.

**Comment by heartacker** [comment] 2020-08-07 13:01
here is another way is that using cli to execute `git commit --amend` ,then git-scm.exe will open the last commit-msg with vscode(`git config --global core.editor "code --wait"`),then edit,save,close.
if using gerrit. remind that delete the `chang-id` before
![image](https://user-images.githubusercontent.com/1876302/89647553-50f1dc80-d8f0-11ea-913e-4235c250da8a.png)

**Comment by orgads** [comment] 2020-08-07 13:06
You should *not* delete Change-Id. This is how gerrit associates your commit with the change entity.

**Comment by heartacker** [comment] 2020-08-07 13:12
> You should _not_ delete Change-Id. This is how gerrit associates your commit with the change entity.

seem that every commit will generate a new chang-id. if not there are two changeids in the commit-msg. To seek the answers to authority

**Comment by orgads** [comment] 2020-08-07 13:31
If this happens to you, something is wrong with your commit-msg hook...

**Comment by heartacker** [comment] 2020-08-07 13:37
> If this happens to you, something is wrong with your commit-msg hook...

Do you mean that I don't need to delete the change-ID, It will keep the ID after Amend? thank for you remind

**Comment by orgads** [comment] 2020-08-07 13:44
Exactly

**Comment by heartacker** [comment] 2020-08-07 15:42
> Close to 3 years,......
> I think that it will be better that user click `amend` that vscode copy the last-commit message to the commit-input-box. that user can edit again or just click `cmomit` continue.

perfect example in Visual Studio ~Code~
![amend_vs](https://user-images.githubusercontent.com/1876302/89662990-70e0ca80-d907-11ea-8c46-116f432240ac.gif)

**Comment by bit7** [comment] 2020-08-26 21:35
Oh my God!  This hasn't been fixed yet?  The code that must need to change to fix this must be a nightmare!

**Comment by Aure77** [comment] 2020-09-30 09:26
Still an issue in 2020 ! This bug has been reported in 2017...

**Comment by msftwindowslinux** [comment] 2020-10-03 00:04
I've got a scrappy PR to add a `git.amendNoEdit` option that enables `--no-edit` when amending (and also skips the prompt for a commit message).

It would be great to get some direction on if/how something like this could be deemed an acceptable solution, because I think this is much needed for gerrit users as the current behavior clobbers the `Change-Id`s every time.

**Comment by hboshnak** [comment] 2020-11-04 06:41
Ended here after the same ugly experience with the git->amend in VSCode.
For what more important issues we talk when we can't work with git normally, this is embarrassing.
Only stupid arguments why not mandatory to-do, without some sort of organization and planning of the improvement.
Greeting to the guys who however made some push in this directions: @msftwindowslinux , @devanshj 
But as I see, even when some people are made their trial to do it, the corporate- envisioned process of will kill their enthusiasm. 
@jrial What's your role here man, some sort of VIP of just playing interesting? As I see only the later...

**Comment by jerivas** [comment] 2020-11-04 13:01
What a horrible comment. Mentioning people just to dump sarcasm and vitriol on them. This is not the way to motivate the maintainers to look into this issue.

**Comment by hboshnak** [comment] 2020-11-05 12:19
Hello Ed,
comment is already deleted. Wrote my feelings but mabe was rude, really.
Thanks for the corrective action.
Best regards,
Huben

**Closed** 2020-11-10 12:54 UTC
Labels: bug, git

**Comment by joaomoreno** [comment] 2020-11-10 12:56
When running `Commit (Amend)` there are two cases:

- Commit input box is empty: old message is preserved
- Commit input box has value: that value is used as an amend commit message

If you'd like to edit the old commit message, you can always run `Undo Last Commit` and do it. For any other use cases, this will help: https://github.com/microsoft/vscode/pull/95266

**Comment by alexrussell** [comment] 2020-11-10 13:46
> - Commit input box is empty: old message is preserved

Aha, right, so for my use-case (doing a `--no-edit` style amend), I have to stage the files, run `Commit (Amend)` and then delete the auto-populated text from the single-line input (thus appearing to commit with an empty message) and then it'll do what I want. (I have just confirmed this, it seems to do it.)

Bit of an odd user experience, but I'm just happy I can do this 👍

**Comment by joaomoreno** [comment] 2020-11-10 15:20
@alexrussell With the changes I just pushed, you don't need to delete any auto populated text, since you won't even be prompted for any input at all. Running `Commit (Amend)` will just complete without asking you anything.

**Comment by mix3d** [comment] 2020-11-10 18:59
But what if you WANT to amend the commit message?

**Comment by mix3d** [comment] 2020-11-10 19:01
Also, of the original request items:
>I think we should be able, with vscode, to amend only the commit message. At the moment, we must commit changes in the same time.

**Comment by alexrussell** [comment] 2020-11-10 19:59
> @alexrussell With the changes I just pushed, you don't need to delete any auto populated text, since you won't even be prompted for any input at all. Running `Commit (Amend)` will just complete without asking you anything.
> 
> This will be released in the next insiders.

Ahh cool. And yeah, I said I confirmed that it worked but actually I think I was mistaken. So that tallies up with you saying it wasn't released yet! I look forward to my next insiders build then. Thanks @joaomoreno!

**Comment by joaomoreno** [comment] 2020-11-11 09:06
> But what if you WANT to amend the commit message? I do this sometimes to fix typos, add something about the file I forgot to add to the commit, etc.

As I said: run `Git: Undo Last Commit`. This will put your last message in the commit input box, properly formatted. Then, just commit again.

> I think we should be able, with vscode, to amend only the commit message. At the moment, we must commit changes in the same time.

The same applies, simply run `Git: Undo Last Commit`, edit your message and commit again.

**Comment by grigorig** [comment] 2020-11-11 09:17
Cool. This sounds like a good compromise. Thanks for the change. The messed up commit message formatting on amend hit me more than once.
