### ISSUE TITLE
Find all references show line/column instead of line content

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#157536] opened 2022-08-08 17:04 UTC
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/876920/183473419-fd734dad-4a89-412c-9310-7701356f29c9.png">

I'm doing find all reference on `BackLayerWebview#deltaCellOutputContainerClassNames` but in the peek view one entry is rendered as `file:line:col` instead of line text.

**Comment by jrieken** [comment] 2022-08-15 13:30
@rebornix Can you reproduce this reliably? The only time this should happen is when a reference cannot be resolved: it points to a file that doesn't exist or to a line that's empty etc pp. Unfortunately with TypeScript this happens a lot because their file watching isn't that great.

**Comment by rebornix** [comment] 2022-08-15 16:38
@jrieken I only saw this once and a rerun of the command fixes the problem.

> Unfortunately with TypeScript this happens a lot because their file watching isn't that great

Feel free to close this issue since it's an known issue

**Comment by jrieken** [comment] 2022-08-16 06:26
Alright, closing then. What you see is unhappy but the fallback case in-case the language server returns foul results. fyi @mjbvz

**Closed by jrieken** 2022-08-16 06:26 UTC
Labels: info-needed, editor-symbols
