### ISSUE TITLE
Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#31115] opened 2017-07-20 09:23 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. have a html file
```
<script>
    function xx() { //xx }
</script>
```

![1](https://user-images.githubusercontent.com/11925432/28410350-fbe06f7a-6d6f-11e7-93f1-be76e3a04020.jpg)

2. put cursor into "xx"

HTML Language Server:
```
Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined
  Code: -32603 
```

**Comment by glitchedmob** [comment] 2017-07-28 20:30
I'm having this same issue in VSCode version 1.14.2 on Kubuntu 17.04

**Comment by ganorberg** [comment] 2017-07-29 21:37
Same issue when clicking on comment in script tag on HTML file. Latest version of VSCode on macOS 10.11.6

[Error - 2:35:45 PM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined
  Code: -32603

**Comment by abc45628** [comment] 2017-08-02 00:47
same issue on vscode1.14.2 and win 10 1703

**Comment by aeschli** [comment] 2017-08-02 14:14
duplicate of #30774

**Closed by aeschli** 2017-08-02 14:14 UTC
Labels: html

**Comment by xjy666** [comment] 2017-08-09 09:53
How do you solve this problem?

**Comment by torrencj** [comment] 2017-08-09 18:20
I have this too. Latest version of VSCode on macOS 10.12.3.

**Comment by JohnHillegass** [comment] 2017-08-24 22:33
I am also experiencing this issue on Mac 10.12.6 in Version 1.15.1
