### ISSUE TITLE
Smoketest failure: verifies problems view and verifies settings

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#126668] opened 2021-06-18 10:18 UTC
These failures are preventing us from getting a green build. 

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Language Features
           verifies problems view:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-warning' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:177:19)
      at async Code.waitForElement (/__w/1/s/test/automation/out/code.js:258:16)
      at async Context.<anonymous> (out/areas/languages/languages.test.js:24:13)

  2) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Language Features
           verifies settings:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:177:19)
      at async Code.waitForElement (/__w/1/s/test/automation/out/code.js:258:16)

```

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=123818&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=41d9f3a8-af10-5350-1c03-229d27a4a1b6

**Comment by alexr00** [comment] 2021-06-18 10:25
Maybe duplicate of https://github.com/microsoft/vscode/issues/126658?

**Comment by sandy081** [comment] 2021-06-18 11:59
I just tried running them locally with dev and insiders and I cant reproduce any failures.

I think @aeschli owns these language features tests, hence assigning to him.

Pinging @lszomoru in case if he has any insights.

**Comment by aeschli** [comment] 2021-06-18 12:00
duplicate of https://github.com/microsoft/vscode/issues/126658

**Closed by aeschli** 2021-06-18 12:00 UTC
Labels: important, smoke-test-failure
