### ISSUE TITLE
Apps crash occasionally when writing output to integrated terminal if Win 10 Fall Creators Update is installed

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#38068] opened 2017-11-10 15:09 UTC
This one is quite tough. 
Today it was almost impossible for me to use the integrated terminal and build tasks in VSCode. Some tools occasionally crashed when they were run inside the integrated terminal. The tools randomly stopped writing their output while some others aborted with a "Disk full" error. This happened everytime when the tools were writing a lot of output to the integrated terminal.
I tested them intensively in standalone powershell and cmd windows: They worked as expected. They only crashed when running inside the integrated terminal.

My first thought was that it had something to do with the latest update of VSCode so I downgraded to the September release but it showed the same odd behaviour.

Then I uninstalled the Windows 10 Fall Creators Update which I installed last night. Now everything works fine again.

I guess this is more an issue in Windows than in VSCode but it's quite strange that different applications crash only when they run in the integrated terminal. That's why I post it here. Maybe you have an idea what could have changed in the Windows API that causes this effect. And I guess you might be interested in having applications behave identically regardless the terminal in which they are being run.

I've managed to create a test project that (almost) always crashed when running in the integrated terminal. It will print 100k lines of output to the terminal. You can find it here: https://github.com/Wosi/Print100kLines

Steps to reproduce (hopefully):
  - Install VSCode to a Windows 10 machine with the Fall Creator's Update
  - Run Print100kLines.exe in the integrated terminal -> It crashed on my system
  - Run the same application in any other terminal and it will work fine

**Comment by Tyriar** [comment] 2017-12-15 17:47
@bitcrazed possible problem with FCU?

**Comment by bitcrazed** [comment] 2017-12-15 19:06
Thanks for the ping. @zadjii_msft is giving it a quick look.

**Comment by zadjii-msft** [comment] 2017-12-15 20:47
Hey all,

Took a look at this. I can confirm that it's happening with both VsCode and Hyper on 16299. Fortunately however, there's a change that's already been checked in that has a fix for this. I don't have the link to a particular GH issue that describes the original issue handy, though if I recall correctly it had something to do with WriteConsoleA getting re-written slightly. 

It should be going out to Insiders soon, but with the holidays, it'll probably be closer to the end of janurary before this makes it all the way up the tree.

**Comment by Tyriar** [comment] 2017-12-18 16:37
@zadjii-msft is this the same? https://github.com/Microsoft/console/issues/40

**Comment by zadjii-msft** [comment] 2017-12-18 16:39
Yep that looks like the one!

**Closed** 2017-12-28 20:55 UTC
Labels: bug, integrated-terminal, upstream, windows
