### ISSUE TITLE
Uninstalling Chrome debugger extension leaves commands in command palette

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#67401] opened 2019-01-29 13:15 UTC
Issue Type: <b>Bug</b>

Found while testing https://github.com/Microsoft/vscode/issues/67298

Install Debugger for Chrome extension
Don't activate the extension
Uninstall the extension
See that the extension has been uninstalled since the install button is now active in the extension viewlet
View command palette - note that chrome extension commands are still visible:

![image](https://user-images.githubusercontent.com/1704059/51910664-d0335580-23c7-11e9-8564-6a13ccbd5401.png)

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:20:23.551Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (3.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.27
python|ms-|2018.8.0
azure-account|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
test-search-rg|rob|0.0.3

</details>

**Comment by alexandrudima** [comment] 2019-01-30 14:19
Duplicate of #67504

**Closed** 2019-01-30 14:19 UTC
Labels: bug, extensions
