### ISSUE TITLE
Feature request: There's no default formatting for CSS files when pressing shift+alt+f

### ISSUE THREAD

**Issue by vkWeb** [Microsoft/vscode#34545] opened 2017-09-17 16:37 UTC
- VSCode Version: 1.16.0
- OS Version: Windows 10 Pro

Steps to Reproduce: 
Just press the default formatting shortcut **shift+alt+f** in a CSS file. You'll notice that the shortcut won't work for it.

Reproduces without extensions: Yes

Though we can get formatting by using beautify extension but I think every code editor must have CSS formatting in-built. It was quite disappointing. I hope it'll be resolved in coming updates.

**Comment by yume-chan** [comment] 2017-09-18 08:42
Duplicate of #19166

**Closed** 2017-09-18 10:13 UTC
Labels: css-less-sass, new release
