### ISSUE TITLE
Emmet suggests input:Nan when input. is typed

### ISSUE THREAD

**Issue by AlekseyPopov5** [microsoft/vscode#107578] opened 2020-09-28 11:35 UTC
Issue Type: <b>Bug</b>

write as html: "<div class="center">
  <div>
    <h1><span>Введите имя статьи:</span></h1>
  </div>
  <div>
    <input class="newPageName" type="text" placeholder="Введите имя статьи" />
  </div>
</div>
<style>
  .center {
    padding: 0 auto;
  }
  .center h1{
      text-align: center;
  }
  .center input.newPageName
</style>"

while typing 'input.new...' we can see emmet help window with 'Nanew...'

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.97GB (4.42GB free)|
|Process Argv|--crash-reporter-id f1ce2376-3e36-4bf1-9095-e04352135027|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-standardjs|che|1.3.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
gitlens|eam|10.2.2
LogFileHighlighter|emi|2.9.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
vscode-firefox-debug|fir|2.9.1
vscode-npm|fkn|3.3.0
vscode-gutter-preview|kis|0.26.2
vs-color-picker|lih|1.0.0
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
debugger-for-chrome|msj|4.12.11
vscode-css-peek|pra|4.0.0

(1 theme extensions excluded)

</details>

**Comment by rzhao271** [comment] 2020-10-05 21:39
Duplicate of #105697

**Comment by rzhao271** [comment] 2020-11-16 18:33
Deduplicating since this only occurs in HTML files

**Comment by abhiajju** [comment] 2021-02-05 06:29
@rzhao271 can you please give some clarity on this issue. I would like to contribute here.
I have a VS code setup with **Version: 1.53.0** and I am not able to repro the Nan issue here

**Comment by rzhao271** [comment] 2021-02-05 17:45
@abhiajju the issue is that if you type `<style>input.</style>` manually into an HTML file, after typing `input.` you'll notice `input: .;` is suggested. That suggestion should not happen, because we're not in an actual CSS body.

**Comment by rzhao271** [comment] 2021-03-01 21:26
\closedWith 5aeafe2

**Comment by roblourens** [comment] 2021-03-24 23:52
I see this: 

![image](https://user-images.githubusercontent.com/323878/112398385-522a1b00-8cc1-11eb-8396-b33f2bf6d0fb.png)

Is that the issue still?

**Comment by rzhao271** [comment] 2021-03-25 15:00
Not exactly, but I'll reopen it still.

**Closed** 2021-04-05 16:11 UTC
Labels: bug, emmet, good first issue
