### ISSUE TITLE
Feature request: Mac line ending selector

### ISSUE THREAD

**Issue by DexterHaslem** [microsoft/vscode#31286] opened 2017-07-23 22:04 UTC
Currently, the UI has two line ending settings:
- LF - Unix
- CR LF - Windows

However, there is a third type of line ending that crops up occasionally, sometimes called 'mac' line endings, it's just CR. Please consider adding it to the list for easy conversion.

**Comment by mjbvz** [comment] 2019-10-09 20:51
Duplicate of #35797 (which is newer but has more votes)

**Closed by mjbvz** 2019-10-09 20:51 UTC
Labels: editor-core, feature-request
