### ISSUE TITLE
Delete Permanently doesn't delete permanently

### ISSUE THREAD

**Issue by CoconutMacaroon** [microsoft/vscode#133214] opened 2021-09-16 03:49 UTC
Does this issue occur when all extensions are disabled?: I haven't tried without extensions, but AFAIK, extensions don't modify the Delete file dialog

- VS Code Version: `1.60.0 (user setup)`
- OS Version: Windows 10, 21h1 (OS Build 19043.1202), using VS Code inside of WSL2 Ubuntu 20.04 LTS

Steps to Reproduce:

1. Create a file (I named it `HelloWorld.java`, but the name and contents shouldn't matter)
2. Navigate to the Explorer tab on the right (the list of files)
3. Right-click on `HelloWorld.java` and click on `Delete Permanently
![image](https://user-images.githubusercontent.com/45187468/133545854-715c2455-a30e-4ecd-aa6e-25a18ccba260.png)
4. Observe the displayed window

Delete permanently is wrong. Even after selecting `Delete` on the dialog above, I can still undo the delete by doing <kbd>CTRL + Z</kbd>.

Expected behavior:
Undoing the delete with <kbd>CTRL + Z</kbd> doesn't undo the delete.

Suggested Fix:
Either make it actually permanently delete, or update the dialog to just say delete

**Comment by TarunavBA** [comment] 2021-09-16 04:11
> Does this issue occur when all extensions are disabled?: I haven't tried without extensions, but AFAIK, extensions don't modify the Delete file dialog
> 
> * VS Code Version: `1.60.0 (user setup)`
> * OS Version: Windows 10, 21h1 (OS Build 19043.1202), using VS Code inside of WSL2 Ubuntu 20.04 LTS
> 
> Steps to Reproduce:
> 
> 1. Create a file (I named it `HelloWorld.java`, but the name and contents shouldn't matter)
> 2. Navigate to the Explorer tab on the right (the list of files)
> 3. Right-click on `HelloWorld.java` and click on `Delete Permanently
>    ![image](https://user-images.githubusercontent.com/45187468/133545854-715c2455-a30e-4ecd-aa6e-25a18ccba260.png)
> 4. Observe the displayed window
> 
> Delete permanently is wrong. Even after selecting `Delete` on the dialog above, I can still undo the delete by doing CTRL + Z.
> 
> Expected behavior:
> Undoing the delete with CTRL + Z doesn't undo the delete.
> 
> Suggested Fix:
> Either make it actually permanently delete, or update the dialog to just say delete

@CoconutMacaroon it itself says that **You can undo the delete by undo command**. So there's nothing wrong with it.

**Comment by CoconutMacaroon** [comment] 2021-09-16 04:14
@TarunavBA Yes, but what I mean is `permanently delete` and `can restore` are two different things. The dialog should be consistent in saying if the file will be deleted forever. Either the file is `permanently delete`d, or `You can restore this file`, but the dialog shouldn't say both, when they are mutually exclusive.

**Comment by TarunavBA** [comment] 2021-09-16 04:18
Yea I agree with you it should say only `delete` not `permanently delete`.

**Comment by CoconutMacaroon** [comment] 2021-09-16 04:30
I'll try to confirm this with the latest Insider build of VS Code, with no extensions, tomorrow, and report back.

**Comment by gjsjohnmurray** [comment] 2021-09-17 04:59
I think the difference between Delete and Delete Permanently is that the former should use the OS trashcan, so the file can be recovered independently of VS Code's undo mechanism.

**Comment by CoconutMacaroon** [comment] 2021-09-17 16:31
Perhaps on Windows..., but AFAIK, WSL2 (Ubuntu) doesn't have a trash can

**Comment by JacksonKearl** [comment] 2021-09-23 18:55
duplicate of https://github.com/microsoft/vscode/issues/117621

**Closed by JacksonKearl** 2021-09-23 18:55 UTC

**Comment by CoconutMacaroon** [comment] 2021-09-23 20:04
> duplicate of #117621

I disagree. The linked issue refers to the actual behavior. I'm simply proposing changing the dialog.

**Comment by JacksonKearl** [comment] 2021-09-24 01:11
I'd rather not remove the "permanently" verbiage, as the file will not be recoverable if something happens to the undo stack.
