### ISSUE TITLE
syntax highlight not working version 0.10.10

### ISSUE THREAD

**Issue by Mirodil** [Microsoft/vscode#3801] opened 2016-03-08 04:04 UTC
syntax highlight not working at all, 
"var", "import", "from" and so on

**Comment by XiSmartElf** [comment] 2016-03-08 05:07
same for me

**Comment by massimocode** [comment] 2016-03-08 14:07
I have the same issue. Var is not highlighted in JS but it is highlighted in TS.

**Comment by tstpierre** [comment] 2016-03-08 15:05
#3791

**Comment by aeschli** [comment] 2016-03-09 09:35
duplicate of https://github.com/Microsoft/vscode/issues/3903

**Closed by aeschli** 2016-03-09 09:35 UTC
