### ISSUE TITLE
Deleting text of a python code when large text is selected from mid body to first character issue

### ISSUE THREAD

**Issue by sagarduwal** [microsoft/vscode#57062] opened 2018-08-23 07:08 UTC
Issue Type: <b>Bug</b>

Deleting text of a python code when large text is selected from mid body to first character issue. When I select the text from around middle of the body text at about line 130 /270, and press Ctrl + Shift + Home, and then press Del key, it wont work, but it deselects the text.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.13.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (1 x 2807)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.83GB (0.11GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
composer-support-client|Hyp|0.19.12
prettier-vscode|esb|1.6.1
python|ms-|2018.7.1

</details>

**Comment by sbatten** [comment] 2018-09-24 23:06
@sagarduwal Does this issue still reproduce for you? I am unable to reproduce it even with the above extensions enabled. If so, does it still reproduce with extensions disabled?

**Comment by rebornix** [comment] 2020-11-04 23:00
Closing as there is no more info provided.

**Closed by rebornix** 2020-11-04 23:00 UTC
Labels: editor-contrib, needs more info
