### ISSUE TITLE
Selecting left to right gives different completion results than right to left

### ISSUE THREAD

**Issue by markknol** [Microsoft/vscode#31200] opened 2017-07-21 09:54 UTC
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Select text from left to right and trigger completion
2. Notice options in completion (only one option)
3. Select text from right to left and trigger completion
4. Notice options in completion  (multiple options)

![vscode-selection](https://user-images.githubusercontent.com/576184/28457717-815b5e34-6e07-11e7-91a6-be021a8a606b.gif)

I'm not very used to vscode yet, but it feels weird that the direction of the selection makes a difference for the completion results. Double clicking (which I mostly do to select a text) seems to the same select from left to right. 

I don't get the completion results in both cases, its somewhat pointless to show the same thing if there is one result. But the other results give me almost everything in the context without selecting what I have right now.

Expected result:

* I would expect both to have the full context options
* I would expect both to have the current selection also selected in the completion (in this case the completion menu should scroll down and select "UIButton").

Reproduces without extensions: Haven't tried. I use vshaxe 1.9.0, but also seems to happen in typescript.

**Comment by ramya-rao-a** [comment] 2017-07-27 05:19
@markknol Completions in VS Code are triggered for the position of the cursor and not the selected text. 

When you select text from left to right, the cursor is at the end of `GotoSceneOnTap`. That position is sent to the registered completion provider which does a look back to get the complete word and then use it to provide completions.

The list shown is always filtered based on what is already typed. Since there are no other completions starting with the word `GotoSceneOnTap`, you get just 1 entry

When you select text from right to left, the cursor is just before `GotoSceneOnTap`. That position is sent to the registered completion provider. Since there is no text at that position, all possible results are given in the completion.

Any reason why you don't just trigger completions without selection?

**Comment by Gama11** [comment] 2017-07-27 05:23
I think the use case here is the following:

- double-click a word to select it
- request completion with Ctrl+Space
- _replace_ the current word with another completion entry by selecting it

Several other IDEs (for instance IntelliJ) support this.

**Comment by ramya-rao-a** [comment] 2017-07-27 05:44
Like this?

![suggest](https://user-images.githubusercontent.com/16890566/28655944-d2371172-7253-11e7-99c5-3e6722abfac4.gif)

**Comment by Gama11** [comment] 2017-07-27 06:27
@ramya-rao-a Exactly - the problem is that that only works for right-to-left selections, not left-to-right ones.

**Comment by ramya-rao-a** [comment] 2017-07-27 06:53
Well, That's because completions depend on the position of the cursor and not selection as mentioned before.

@jrieken any thoughts on the feature request that completions be provided at the beginning of a selection?

**Comment by markknol** [comment] 2017-07-27 10:29
@ramya-rao-a thanks for your reply. I replace lot of stuff by selecting the text. Maybe in that case if you double click a text, the cursor should be on a different location? I understand the internals make this happen, as a user this feels off.

**Comment by ramya-rao-a** [comment] 2017-12-11 23:06
@jrieken Thoughts?

**Comment by jrieken** [comment] 2017-12-12 09:01
Dislike. The selection-end is more clearly marked (by the cursor) and going to the start seems very confusing to me

**Comment by jrieken** [comment] 2018-09-11 09:05
Closing as-designed and as related to #10266

**Closed by jrieken** 2018-09-11 09:05 UTC
Labels: suggest, under-discussion
