### ISSUE TITLE
tab键快速写代码有问题

### ISSUE THREAD

**Issue by dongkang1993** [Microsoft/vscode#22923] opened 2017-03-21 03:05 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-html-css|ecmel|0.0.33|
|mithril-emmet|FallenMax|0.6.1|
|beautify|HookyQR|1.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|vscode-icons|robertohuertasm|7.4.0|
|D3Snippets|yoyo|0.1.11|;

---

Steps to Reproduce:

1.！+tab键
2.script +tab键此时script不自动闭合，调到title一栏

**Comment by rebornix** [comment] 2017-03-21 16:29
@dongkang1993 it would be great if you can provide a video or gif describing what's happening :)

**Comment by astar55** [comment] 2017-03-22 11:17
I found a fix for this issue. The problem is that when you try to use emmet on ! or a, the snippet controller does not accept the snippet so when you try to emmet another thing afterwards, the cursor just bounces around. 
Applying `SnippetController.get(this._editor).acceptSnippet();` to the function `onAfterEmmetAction()` in `\src\vs\workbench\parts\emmet\node\editorAccessor.ts` will fix the issue. 
```
	public onAfterEmmetAction(): void {
		// If there were any edits in this "transaction", push an undo stop after them
		if (this._hasMadeEdits) {
			this._editor.pushUndoStop();
		}
		SnippetController.get(this._editor).acceptSnippet();
	}
```

**Comment by ramya-rao-a** [comment] 2017-03-22 22:51
@dongkang1993 @astar55 I think this is the same as #5427. Can you read through #5427 and confirm?

**Comment by astar55** [comment] 2017-03-23 00:23
it is the same as #5427

**Comment by ramya-rao-a** [comment] 2017-03-29 04:58
Closing as duplicate of #5427

**Closed by ramya-rao-a** 2017-03-29 04:58 UTC
Labels: needs more info
