### ISSUE TITLE
Integrated terminal cannot scroll

### ISSUE THREAD

**Issue by kunalbhagawati** [Microsoft/vscode#10404] opened 2016-08-10 18:41 UTC
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04 64 using i3 Tiling Window Manager
- HP dv6 (laptop) trackpad 

Steps to Reproduce:

1. Open the integrated terminal.
2. `cat` a long file
3. The terminal does not scroll.

**Comment by Tyriar** [comment] 2016-08-11 20:05
Are you on oh-my-zsh?

**Comment by Tyriar** [comment] 2016-09-06 18:38
Duplicate of #7817

**Closed by Tyriar** 2016-09-06 18:38 UTC
Labels: integrated-terminal, needs more info
