### ISSUE TITLE
Auto-update breaks VSCode installation when connectivity is lost

### ISSUE THREAD

**Issue by danieljanes** [microsoft/vscode#110131] opened 2020-11-07 07:35 UTC
- VSCode Version: 1.51.0
- OS Version: Windows 10 2004 / WSL2 with Ubuntu 18.04

Steps to Reproduce:

1. Start VSCode from the WSL2 command line with bad internet connectivity (i.e., not stable)
2. If there is an update available, VSCode removes the existing installation, then downloads the new version, and installs it
2. If the connection drops right after the previous installation was removed (while downloading the new version) then VSCode cannot be started any more. Below is the command line output for a successful update, the step where the update procedure can break the installation is indicated with `<===`, but I experienced the described failure case before.

```
$ code .
Updating VS Code Server to version fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Removing previous installation...
Installing VS Code Server for x64 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c)
Downloading: 100% <===
Unpacking: 100%
Unpacked 1694 files and folders to /home/daniel/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c.
```

A better approach would be to immediately start the existing installation, download the new version in the background, and replace the existing version on the next start of VSCode.

This would fix two issues:
- The installation cannot break due to bad connectivity (this is especially relevant, for example, on train rides where the connectivity changes frequently)
- VSCode would start instantly without the user having to wait for the download to complete, which can take quite a while, especially on slow connections

Somewhat related to #9539 (but the focus of #9539 seems to be more on the usability of update notifications)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2020-11-09 14:54
It's not possible to run an older server with a new client. So when you see the download, it's already too late as your client has been updated.
What we would need is that the normal VSCode updater also downloads the required servers are the same time. For that we would have the know what servers are needed (x64, amd, ...).

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/3839

**Closed by aeschli** 2020-11-09 14:54 UTC
Labels: new release
