### ISSUE TITLE
We have mitigated the issue at **2020-10-27 13:50:00 UTC**. Could you please re-enable settings sync and let me know if you are still seeing any errors. I will follow up with our Azure partner teams to get to the bottom of the reason why the App Service instance has gotten into a bad state. Apologies for the inconvenience.

### ISSUE THREAD

**Issue by lucamauri** [microsoft/vscode#109655] opened 2020-10-29 08:45 UTC
We have mitigated the issue at **2020-10-27 13:50:00 UTC**. Could you please re-enable settings sync and let me know if you are still seeing any errors. I will follow up with our Azure partner teams to get to the bottom of the reason why the App Service instance has gotten into a bad state. Apologies for the inconvenience.

_Originally posted by @lszomoru in https://github.com/microsoft/vscode/issues/108635#issuecomment-717262640_

**Comment by lucamauri** [comment] 2020-10-29 08:46
@lszomoru please note the issue is not solved. Please refer the original issue to see further error notification _after_ 2020-10-27.

Thanks

**Comment by lszomoru** [comment] 2020-10-29 09:10
@lucamauri, looking at the service-side telemetry and will be updating the original issue.

**Comment by lszomoru** [comment] 2020-10-29 11:30
Closing as duplicate of #108635

**Closed by lszomoru** 2020-10-29 11:30 UTC
