### ISSUE TITLE
SQL Syntax Highlighting not working when escaping strings

### ISSUE THREAD

**Issue by jeasonstudio** [Microsoft/vscode#45541] opened 2018-03-12 03:21 UTC
- VSCode Version: Version 1.21.0-insider (1.21.0-insider)
- OS Version: macOS 10.13.3

Steps to Reproduce:

```bash
$ code-insiders --disable-extensions <my-project>
```

![image](https://user-images.githubusercontent.com/17971291/37264237-3621073c-25e7-11e8-9520-a39794ae273a.png)

Does this issue occur when all extensions are disabled?: Yes

Locked issue: #39822

**Comment by aeschli** [comment] 2018-03-12 11:21
duplicate of https://github.com/Microsoft/vscode-mssql/issues/955

**Closed by aeschli** 2018-03-12 11:21 UTC
Labels: extensions
