### ISSUE TITLE
VSCode Autocomplete 'Loading...'

### ISSUE THREAD

**Issue by HarryBilney** [microsoft/vscode#87770] opened 2019-12-27 12:38 UTC
- VSCode Version: Insider 1.42
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code (my version)
2. Auto complete is stuck on 'Loading...' when I do ctrl+space

Does this issue occur when all extensions are disabled?: Yes

I'm creating a react app, I've got a .jsx file for a component and the basic auto complete (imrc for import and cc to create a class) just don't work anymore. I haven't updated or changed my version at all. Was working a few days ago and haven't used vscode since. When I do ctrl+space to trigger the autocomplete, all I get is 'Loading...'

Any ideas?

I've searched around the internet for an answer but none of the solutions fix it for me :(

**Comment by vuongggggg** [comment] 2019-12-28 07:10
I use create-react-app and get the same problem. Always `Loading...` even language server has been started.

**Comment by HarryBilney** [comment] 2019-12-28 11:33
I use create-react-app too and that’s how I’m getting the ‘Loading...’
thing. No idea why as create-react-app is normally fine

**Comment by HarryBilney** [comment] 2019-12-28 22:47
![image](https://user-images.githubusercontent.com/57139561/71550267-fee4f200-29c3-11ea-94c2-4899f6fb5ae0.png)
This is what I get in the dev console

**Comment by mjbvz** [comment] 2019-12-29 23:41
Is your code stored on a network drive or non c letter drive?

**Comment by HarryBilney** [comment] 2019-12-29 23:42
Kinda, it’s in a partition of my c drive, labelled d drive

**Comment by mjbvz** [comment] 2019-12-30 00:13
Thanks. This is a duplicate of https://github.com/microsoft/TypeScript/issues/35512 then.

Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) to workaround this problem

**Closed by mjbvz** 2019-12-30 00:13 UTC
Labels: javascript, needs more info

**Comment by nicolopezuruguayo** [comment] 2020-01-28 12:04
> Thanks. This is a duplicate of [microsoft/TypeScript#35512](https://github.com/microsoft/TypeScript/issues/35512) then.
> 
> Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) to workaround this problem

It worked ! after weeks searching the solution, now vscode is running smoothly

**Comment by bselpin** [comment] 2020-02-05 05:28
> Thanks. This is a duplicate of [microsoft/TypeScript#35512](https://github.com/microsoft/TypeScript/issues/35512) then.
> 
> Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) to workaround this problem
It worked too! very beautiful solution!
