### ISSUE TITLE
Provide stronger visual indication that extension installation was successful

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#67404] opened 2019-01-29 13:30 UTC
Issue Type: <b>Bug</b>

Testing #67263:

After installing a new extension (e.g. "Azure Account"), I'm now missing some indication that the installation was successful. Previously a "Reload Window" was required. Now there is no Reload and the only visible UI change is the tiny "Install" button turning into an "Uninstall" button.
 It would help if the Extension viewlet would automatically show the "installed Extensions" after an Install.

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:14:22.700Z)
OS version: Linux x64 4.15.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.89GB (3.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-account|ms-|0.8.0
vscode-typescript-tslint-plugin|ms-|0.4.0

</details>

**Comment by sandy081** [comment] 2019-01-29 13:39
Duplicate of #66931

**Closed** 2019-01-29 13:39 UTC
Labels: *duplicate
