### ISSUE TITLE
Automatic language detection is a nuisance for git commit messages

### ISSUE THREAD

**Issue by r-owen** [microsoft/vscode#132696] opened 2021-09-08 22:37 UTC
Issue Type: <b>Bug</b>

I'm using the latst VSCode on a Python package and git commit messages keep showing up as Python formatted, due to the automatic language detection. This is annoying.

I tried updating my Preferences to add an entry to Files: Associations as follows, but it doesn't help:
Item=COMMIT_EDITMSG
Value=plaintext

I would love to know how to disable this feature. I don't want it, and this bug makes it disruptive.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (9.45GB free)|
|Process Argv|../ts_idl --crash-reporter-id 0ce2be71-8c13-481c-af4d-534ecfe66fa9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.0
statusbarerror|Joe|0.4.0
bracket-peek|jom|1.4.2
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30363604

```

</details>

**Comment by r-owen** [comment] 2021-09-08 22:42
I think the problem is that the automatic detection is overriding the manual association, because when the git commit message has no obvious source code in it then the file type correctly shows as "Git Commit Message" instead of Python code.

Note that I have git configured to show all differences in the git commit message.

**Comment by sdutoit** [comment] 2021-09-09 03:22
You can turn this off using the `Workbench > Editor: Language Detection` setting. But I agree the underlying problem should be fixed in that the automatic detection shouldn't override filename-based associations!

**Comment by TylerLeonhardt** [comment] 2021-09-09 14:13
Duplicate of #132173

**Closed** 2021-09-09 14:13 UTC
Labels: *duplicate
