### ISSUE TITLE
The Suggest tooltip - expand more has Overlapping Text

### ISSUE THREAD

**Issue by wcampospro** [microsoft/vscode#110149] opened 2020-11-07 17:46 UTC
When pressing dot/period in C# and getting the Suggest menu, you get the suggestion, the suggestions text is fine but the **More** section on the right has overlapping text.
This overlapping text depends on the Font Selected for the code and the size.

![BugReport](https://user-images.githubusercontent.com/16523949/98447939-a307f100-20dd-11eb-9182-e5ead625fc9f.png)

As you can see in the image, the text on the right tends to overlap vertically.

**Comment by jrieken** [comment] 2020-11-09 08:04
> This overlapping text depends on the Font Selected for the code and the size.

And what font and size did you choose? Also, did you adjust the line height via `editor.suggestLineHeight`?

**Comment by jrieken** [comment] 2020-11-09 08:05
/duplicate of https://github.com/microsoft/vscode/issues/110172

**Closed** 2020-11-09 08:05 UTC
Labels: *duplicate, needs more info, suggest
