### ISSUE TITLE
Indentation breaks after closing curly brackets in JSX

### ISSUE THREAD

**Issue by paprikman** [microsoft/vscode#97506] opened 2020-05-11 13:31 UTC
- VSCode Version: 1.46.0-insider
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create an element in JSX return\render
2. Open curly bracket inside of it, then close it, for example:
```javascript
return (
  <h2>{}</h2>
)
```
![indent_issue](https://user-images.githubusercontent.com/57448756/81566534-72f0c700-93b4-11ea-9619-449bcea3da2f.gif)

3. The code indentation in this line will be broken (see gif for better explanation). No changes to the indent are expected at this stage. The issue is still present with setting `"editor.formatOnType": false`. The issue does not take place if you type something before closing the brackets, like so:
```javascript
<h2>{props.someProp}</h2>
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-05-11 22:13
Duplicate of #90897

**Closed by mjbvz** 2020-05-11 22:13 UTC
