### ISSUE TITLE
Webview overlays suggest widget

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148415] opened 2022-04-29 08:26 UTC
* safari (?)
* side bar to the right
* preview a MD file
* trigger suggest in SCM input
* the suggest widget is behind the webview

<img width="878" alt="Screenshot 2022-04-29 at 09 58 25" src="https://user-images.githubusercontent.com/1794099/165909801-31cb6cad-09c8-4e28-939c-ac4509c5a0ca.png">

**Comment by jrieken** [comment] 2022-12-02 14:36
This like an issue with how the SCM viewlet uses the editor? The capture shows again Safari, but you see that suggest shows on top of the preview but the hover doesn't out-flow

<img width="1104" alt="Screenshot 2022-12-02 at 15 34 49" src="https://user-images.githubusercontent.com/1794099/205316840-14033613-4b66-4ba8-8e3e-eaf974f0f7c5.png">

**Comment by lszomoru** [comment] 2024-12-13 16:10
Duplicate of [#109221](https://github.com/microsoft/vscode/issues/109221)

**Closed by lszomoru** 2024-12-13 16:10 UTC
Labels: bug, scm, safari
