### ISSUE TITLE
Git gutter breaks when filename case changes

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#48714] opened 2018-04-25 21:07 UTC
Create a file and commit it to Git. Change the file's case, even just one letter, so that Test.js becomes test.js, for instance.

Then restart VSC, just to be sure. Open the test.js file. Modify it. No Git gutters will appear.

**Comment by joaomoreno** [comment] 2018-04-26 06:27
@garyking Which OS are you on?

**Comment by garyking** [comment] 2018-04-26 16:57
I'm on Mac OS X 10.13.3.

**Comment by blunket** [comment] 2018-05-13 18:11
seems like a duplicate of #29861

**Closed** 2018-07-06 14:46 UTC
Labels: bug, git, help wanted
