### ISSUE TITLE
Workspace trust dialog when reloading with untitled notebooks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#125318] opened 2021-06-02 17:42 UTC
https://github.com/microsoft/vscode/issues/124844

- Run `code-insiders fromcli.github-issues`
- Reload the window
- Get a trust prompt

Strangely, doesn't happen with untitled notebooks that I get from the "New github issues notebook" command

![image](https://user-images.githubusercontent.com/323878/120527355-18dfec80-c38f-11eb-86e4-ce001ecda4db.png)

FYI see https://github.com/microsoft/vscode/issues/125317

**Comment by lszomoru** [comment] 2021-06-03 16:00
Based on the screenshot, the workspace seems to be trusted so I was wondering:
1. Have you changed the setting so that the empty window is trusted by default?
2. Do you already have a trusted workspace opened in the VSCode instance?
3. Are you creating the new file in a location that is already trusted?

**Comment by roblourens** [comment] 2021-06-03 17:40
1. I only have `"security.workspace.trust.enabled": true`
2. This workspace is trusted
3. It's an untitled file so I guess the location shouldn't matter. It just has a name

**Comment by sbatten** [comment] 2021-06-04 02:35
@roblourens I was trying to repro this.

My conditions:
1. I have the vscode repo opened which is trusted
2. from integrated terminal, I run `code-insiders fromcli.github-issues`
3. no prompt because the file is "created" in the vscode repo (the path of the open editor has a full path)
4. reload 
5. still no prompt

Where the file is "created" is important. If I do this where the path to the new notebook is outside of the workspace and not trusted, I get a prompt on initial open but not reload.

**Comment by lszomoru** [comment] 2021-06-04 16:00
Spoke with @roblourens, and our currently theory is that the workspace in which he saw the issue was in a bad state due to  https://github.com/microsoft/vscode/issues/125317. We are closing this issue until https://github.com/microsoft/vscode/issues/125317 gets resolved, and will reopen in case the issue is still present after that.

**Closed by lszomoru** 2021-06-04 16:00 UTC
Labels: bug, workspace-trust
