### ISSUE TITLE
Cannot copy deleted text from the inline diff editor

### ISSUE THREAD

**Issue by zmicx** [Microsoft/vscode#37895] opened 2017-11-09 08:07 UTC
Setting "diffEditor.renderSideBySide": false,  when I Compare the code diff, old code desn't copy
![image](https://user-images.githubusercontent.com/26269444/32594664-d7d8aa16-c567-11e7-88e9-9cb54e1acdfe.png)

**Comment by alexandrudima** [comment] 2017-11-23 16:55
Duplicate of #33161

**Closed by alexandrudima** 2017-11-23 16:55 UTC
Labels: diff-editor, feature-request
