### ISSUE TITLE
Slow Execution of Git commands

### ISSUE THREAD

**Issue by 0xScratch** [microsoft/vscode#214876] opened 2024-06-11 13:20 UTC
Type: <b>Performance Issue</b>

After the latest update, the execution of git commands have become way slow than it was before. 
Suppose, if I am staging my changes, or making commits...It takes time!

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.57GB free)|
|Process Argv|. --crash-reporter-id 074ec000-84c5-453a-b0a3-04ab81ea8bd3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   115	  3248	code main
    0	   677	  4208	extensionHost [1]
    0	    93	  1832	     "C:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=4208
    0	    91	  4668	     electron-nodejs (server.js )
    0	    91	 11736	     electron-nodejs (eslintServer.js )
    0	    91	 15096	     electron-nodejs (serverMain.js )
    0	    95	 23300	     "C:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-language-features\server\dist\node\workerMain" --node-ipc --clientProcessId=4208
    0	   170	  7000	   gpu-process
    0	    51	 12996	   utility-network-service
    0	   118	 14492	shared-process
    2	   102	 20220	window [2] (Issue Reporter)
    0	    90	 20548	ptyHost
    0	     5	 24112	     "C:\Program Files\Git\bin\bash.exe" --init-file "c:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	    15	 28624	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --init-file "c:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	     7	 27988	     conpty-agent
    0	    91	 24592	fileWatcher [1]
    0	    30	 29016	   crashpad-handler
   11	   359	 30696	window [1] (README.md - Web3_Security - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (README.md - Web3_Security - Visual Studio Code)
|    Folder (Web3_Security): 154 files
|      File types: sol(77) js(30) json(8) md(3) gitignore(2) txt(2)
|      Conf files: package.json(2);
```

</details>
<details><summary>Extensions (97)</summary>

Extension|Author (truncated)|Version
---|---|---
golangwithdidi|ald|0.0.1
ng-template|Ang|18.0.0
astro-vscode|ast|2.10.2
vscode-django|bat|1.15.0
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
solidity-lang|Con|1.6.0
doxdocgen|csc|1.4.0
postcss|css|1.0.9
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|2.4.4
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
dotenv-vscode|dot|0.28.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
copilot|Git|1.200.0
copilot-chat|Git|0.16.0
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.89.2024053108
go|gol|0.41.4
todo-tree|Gru|0.0.226
ink-analyzer|ink|0.1.31
vscode-env|Iro|0.1.0
plantuml|jeb|2.18.1
better-cpp-syntax|jef|1.17.2
vscode-text-pastry|jkj|1.3.1
solidity|Jua|0.0.174
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.29.1
vscode-edge-devtools|ms-|2.1.5
autopep8|ms-|2024.0.0
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.372.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-js-profile-flame|ms-|1.0.9
vsliveshare|ms-|1.0.5918
gremlins|nho|0.26.0
autodocstring|njp|0.6.1
vscode-jest|Ort|6.2.5
vscode-solidity-inspector|Pra|1.3.0
gotestexplorer|pre|0.1.13
quicktype|qui|23.0.170
vscode-thunder-client|ran|2.24.11
java|red|1.31.0
r|REd|2.8.4
ethereum-remix|Rem|0.0.12
LiveServer|rit|5.7.9
rust-analyzer|rus|0.4.1994
vs-code-prettier-eslint|rve|6.0.0
icons|tal|3.8.0
even-better-toml|tam|0.19.2
ayu|tea|1.0.5
graphviz-interactive-preview|tin|0.3.5
solidity-visual-auditor|tin|0.2.0
vscode-ethover|tin|0.0.7
vscode-inline-bookmarks|tin|0.1.0
vscode-solidity-flattener|tin|0.0.11
vscode-solidity-language|tin|0.0.7
cmake|twx|0.0.17
vscode-mdx|uni|1.8.8
errorlens|use|3.18.0
vscode-lldb|vad|1.10.0
learn-vim|vin|0.0.28
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0
vim|vsc|1.27.3
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
commandlist|yam|1.1.0
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideot:31016892
chatpanelt:31048053
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by DeveloperCharles** [comment] 2024-06-11 14:39
I encountered the same problem. Somebody knows the causes and solutions, help please!

I'll share infos from my side, hope it can be help.

my git version
![68b44537251e45f0eca4bceaaa2a859](https://github.com/microsoft/vscode/assets/34536912/3583e379-f0af-4cf9-9d5e-81ab86bc3399)

my node version
![0ba044d906dc81738da0e25aa9ab64e](https://github.com/microsoft/vscode/assets/34536912/7c641442-e9ef-49ee-b5bf-d9ad20075820)

and all above version info has a weired code `orting)\x1b[0m\x0d\x0a$`...
maybe this relates to the root cause?

**Comment by jmezadev** [comment] 2024-06-11 15:45
Same problem here. It only happens in GIT bash

Version info:

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by 0xScratch** [comment] 2024-06-11 15:59
Thanks @DeveloperCharles and @jmezadev for confirming that you're experiencing the same issue as well. Pretty sure, there be other devs who be facing it too and might not noticed that. Feels like the latest version has something to do with it...
Any additional comments from other devs will definitely increase the visibility of this issue, which will highlight its significance to the VS Code development team!

**Comment by 0xScratch** [comment] 2024-06-11 16:03
Although a similar issue showed up here -> #212090

**Comment by lszomoru** [comment] 2024-06-18 09:50
Closing as duplicate of https://github.com/microsoft/vscode/issues/212090

**Closed by lszomoru** 2024-06-18 09:50 UTC
