### ISSUE TITLE
Some regex in Find freeze VS Code

### ISSUE THREAD

**Issue by johnnytemp** [microsoft/vscode#74868] opened 2019-06-05 04:39 UTC
Remark: Since all patterns in #30874 doesn't hangs in my test, I open a new issue because the internal bug should be different.

- VSCode Version: 1.34.0
- OS Version: Windows

Steps to Reproduce:

1. Open a saved Xxx.php file with this content:
<pre>
&lt;?php

function f1() {
    $x = "nullif(greatest(if(x.xxxxxxxxxxxxxxxxxxxx >= xxxxxxxxxxxxxxxxxxxx, '0', xxxxxxxxxxxxxxxxxxxx), xxxxxxxxxxxxxxxxxxxx, ifnull(max(xxxxxxxxxxxxxxxxxxxx), '0')), '0') as xxxxxxxxxxxxxxxxxxxx";
}
</pre>
2. Copy the text `if ?\(([^(),]+|\(([^()]+|\([^()]*\))*\))*,` to clipboard. (The pattern find SQL if(x,y,z) function)
3. Ctrl-F to focus on Find dialog, enable the regex & match case options only.
4. Ctrl-V to paste the clipboard pattern to find.
5. VS Code immediately freeze. Must force quit. (or sometimes it may popup a dialog whether want to Reopen VS Code.)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment] 2019-07-26 00:56
/duplicate of https://github.com/microsoft/vscode/issues/30874

**Closed** 2019-07-26 00:56 UTC
Labels: *duplicate, editor-find
