### ISSUE TITLE
is outputChannel support color?

### ISSUE THREAD

**Issue by hanfengcan** [Microsoft/vscode#40740] opened 2017-12-23 03:06 UTC
console.log(data) can support color
but outputChannel can't ?

![image](https://user-images.githubusercontent.com/4559753/34316452-f05189b0-e7d0-11e7-8952-38c368454f14.png)

**Comment by weinand** [comment] 2017-12-23 10:01
duplicate of https://github.com/Microsoft/vscode/issues/571

**Closed** 2017-12-23 10:01 UTC
Labels: *duplicate
