### ISSUE TITLE
Remove CtrlCmd+W keybinding to close window when no editors are opened

### ISSUE THREAD

**Issue by graham-sportsmgmt** [microsoft/vscode#54492] opened 2018-07-17 16:41 UTC
This could be viewed a duplicate of [this Feature Request](https://github.com/Microsoft/vscode/issues/50671), but I'm reopening it as a bug for two reasons:

1. Based on the last comment, I don't believe that the assigned developer completely understood the issue, and
2. I am adding more specific details that would classify it as a bug.

I frequently use `Ctrl + W` to close the active editor.  When there are no open Windows (i.e. editor tabs) pressing `Ctrl + W` closes the Workspace (i.e. the entire VS Code application) which is not the behavior I want.

In the Keyboard Shortcuts menu there are default bindings for `Ctrl + W` to "Close Window" and `Ctrl + K + F` to "Close Workspace".

In Version 1.25.1 when there are no open editors, pressing `Ctrl + W` (wrongly) assumes that I wanted to issue a `Ctrl + K + F` / Close Workspace command.  In this situation the desired behavior is no action as:

1. There are no open Windows, and 
2. The Workspace is not a Window according to the semantics defined in Keyboard Shortcuts.

This could be fixed by either disabling Close Workspace on `Ctrl + W` or adding a configuration option that lets me control the behavior of `Ctrl + W` when no editors are open.

**Comment by bpasero** [comment] 2018-07-17 19:34
@graham-sportsmgmt just add this to your keybindings file and it should be OK:

```json
{
	"key": "ctrl+w",
	"command": "workbench.action.closeActiveEditor"
}
```

**Comment by graham-sportsmgmt** [comment] 2018-07-17 20:44
That's what the default keybindings.json already has:

`{ "key": "ctrl+w",                "command": "workbench.action.closeActiveEditor" }`

Could you please read my post again and let me know which parts need clarification?  I'd like to make sure you understand the issue but your comment makes me believe you don't.

**Comment by bpasero** [comment] 2018-07-18 04:40
@graham-sportsmgmt can you please just do what I said in https://github.com/Microsoft/vscode/issues/54492#issuecomment-405701768 and then see if that fixes your issue and if not we can continue the discussion?

**Comment by graham-sportsmgmt** [comment] 2018-07-18 04:45
Yes, after adding that line ctrl+w does not close the Workspace.

This bug requests that as the default behavior without needing to edit keybindings.json.

**Comment by bpasero** [comment] 2018-07-18 04:55
@graham-sportsmgmt but closing the Window when pressing `Ctrl+W` is a pretty standard behaviour I would say for applications. And for that reason we make keybindings configurable. I do not think we would change this behaviour.

**Comment by graham-sportsmgmt** [comment] 2018-07-18 04:57
It's common for web browsers, but web browsers aren't IDE's.

**Comment by orgads** [comment] 2019-04-11 05:35
I agree. I hit this bug too often.

Ctrl-W is common for closing a tab or a document in MWI applications, but it is very uncommon for closing the application itself, except browsers which are closed when the last tab is closed. In VS Code there is a preference for that: `window.closeWhenEmpty`, but if it is not set I expect the application to just ignore Ctrl-W.

For example, MS Office apps close the active document on Ctrl-W, but they don't quit.

I vote for changing the default behavior.

**Comment by 9527KGG** [comment] 2019-07-27 19:00
+1 for default behavior. Current behavior is just annoying.

**Comment by leidegre** [comment] 2019-10-01 07:02
The utter insanity och having `ctrl+w` close VS Code by default, has to end. It isn't a browser. I know we can configure ourselves out of this situation but common, this is annoying.

**Comment by pnavarrc** [comment] 2019-10-21 18:28
I tried setting the keybinding as suggested [here](https://github.com/microsoft/vscode/issues/54492#issuecomment-405701768) without success, editing the keyboard shortcut preferences worked for me though (I just set a shortcut that I won't use)

![image](https://user-images.githubusercontent.com/114084/67232175-a3abe780-f3f5-11e9-8720-e9ee37f6c46d.png)

Maybe there could be a more prominent setting to toggle this behaviour? I'm not sure about what should be the default, but making the setting more accessible would help.

**Comment by georgyfarniev** [comment] 2019-11-28 08:02
Hello, this is super annoying I often close my vs code with all running tasks by accidentally press Ctrl+W. A heritage of electron :)

**Comment by georgyfarniev** [comment] 2019-11-28 08:07
See https://github.com/electron/electron/issues/5951

**Comment by houh60** [comment] 2019-12-17 20:11
Hi "graham-sportsmgmt", the answer is simple. You don't have to change anything. You just need to

1. go to "settings" (the gear wheel), 
2. then to go "Keyboard Shortcuts", 
3. then type in "ctrl+w", 
4. then select it (the command would be "Close Window"), 
5. and then press the "delete" key. 
6. done

The above-given way will solve your problem. 

I'm like you about that. I use the "ctrl+w" shortcut very, very often. But when no files were open, the "ctrl+w" shortcut would close VSCode completely! I hate that! 

So I deleted the whole "Close Window" line. And now the "ctrl+w" shortcut only closes files, not the whole VSCode, which will stay open as long as you want.

**Comment by LordScree** [comment] 2019-12-18 09:53
IMO @houh60 has the answer.

I appreciate that @graham-sportsmgmt asked for the _default behaviour_ to be amended, but VSCode is a highly configurable editor.

The simple tweak to the keybindings, as stated by @houh60 resolves this issue. And if you're using an extension like Settings Sync to persist your settings across your different machines, you'll never have to worry about it again.

**Comment by skupjoe** [comment] 2020-01-06 09:42
+1 that this should be default behavior!

**Comment by houh60** [comment] 2020-01-06 21:55
Yes. But some may not know it until they are told. I didn't know until I searched. 
Good luck to everyone.
    On Monday, January 6, 2020, 03:42:53 AM CST, Joseph Skupniewicz <notifications@github.com> wrote:  
 
 
+1 that this should be default behavior!

**Comment by JayEn84** [comment] 2020-01-21 10:47
I'd also prefer the proposed behaviour that VSCode will not be closed when I (accidently) hit Ctrl+W while no editor is open.

In addition to that, I would also like to use Ctrl+Shift+W to close all editors instead of closing the application. (I know this is what Ctrl+K+W does, but I'm used to Ctrl+Shift+W from other applications.)

**Comment by JayEn84** [comment] 2020-01-21 11:03
I also expected this would be the default behaviour when I switched to VSCode. Thanks @houh60 for sharing his solution. I also deleted the corresponding line, so everything's fine for me now.

(In addition to that, I also deleted the "close window" command for "Ctrl+Shift+W" and then edited the command for closing all editors (originally Ctrol+K+W) to "Ctrl+Shift+W". It's actually the same reason - I'm used to Ctrl+Shift+W from other applications.)

I found this thread on Github after I didn't find any setting inside VSCode and then explicitly searched for a solution here. So before searching here, I opened the VSCode settings (Ctrl+,) and found the "Window" section. Over there, I can decide whether closing the last editor should also close the whole window.

![grafik](https://user-images.githubusercontent.com/4518738/72799465-92b58100-3c45-11ea-9a89-87884ab91fc0.png)

I'm sure I'm not the only one who checked those settings in order to change the Ctrl+W behaviour. Therefore, I would like to propose to extend this setting, so everyone can define their desired behaviour over there as an alternative to changing the default behaviour.

**Comment by y4code** [comment] 2020-06-04 03:52
remove `Eclipse Keymap `extension works for me, when i open java project, vscode  installed `Eclipse Keymap` automatically. Don't know why

**Comment by tronster** [comment] 2020-10-27 12:48
Echoing what has been said or voted on by many above: please make not closing the application the default behavior with control+W.

It's likely some developers may just live with the behavior and not seek out a solution.  (It's been a few months until I decide to search around and see if I could fix this behavior.)  There's likely thousands of developers who've come across this thread over the past three years, found the workaround, and left after applying it.  But from those who have stuck around to share their thoughts, it looks like there is a strong trend from the community which sees the existing default behavior as more of a hindrance than a help.

For those advocating not changing the default but instead to follow the instructions in remove the closing behavior - the same ease of configuration, that has been expressed, would be true for those who want to configure it back to the current behavior.  

An easy win would be to change the default to what the community outlined above.  The minority, who want the legacy closing behavior, would just need to reconfigure it to close the APP when no windows are open and CTRL+W is pressed.

**Comment by bitwes** [comment] 2020-11-11 16:19
Echoing @tronster's echo of all things to be echoed.  I also finally got around to googling this after accidentally closing  everything too many times.  I feel it should be the default behavior.

**Comment by orgads** [comment] 2020-11-12 05:18
According to the release notes, this looks solved. https://code.visualstudio.com/updates/v1_51#_prevent-accidental-close

**Comment by tronster** [comment] 2020-11-12 12:21
@orgads, that would be great. Taking a look using 1.51 (and then 1.51.1) and it doesn't appear to be in there.  Or at least it's not enabled by default and is not a setting in "File > Preferences > Settings".

**Comment by shakefu** [comment] 2021-02-10 20:17
![image](https://user-images.githubusercontent.com/1046227/107566239-7e6a5c00-6b99-11eb-9d56-3655b8847b46.png)
In the current version the default behavior is still to close the Workspace Window when you are relentlessly smashing Cmd+W (or Ctrl+W I assume). 
It can be changed by removing the "Close Window" keyboard shortcut. There still remains a Cmd+Shift+W shortcut for closing the Workspace Window, which seems fine. 
This should really still be the default.

**Comment by christhomas** [comment] 2021-03-12 11:22
This is still a bug in 2021. This issue is so simple, why hasn't it been fixed yet?

**Comment by kartikeytewari** [comment] 2021-04-02 19:24
I was also having the same issue. adding this in keybindings.json file helps:

 {
        "key": "cmd+w",
        "command": "-workbench.action.closeWindow",
        "when": "!editorIsOpen && !multipleEditorGroups"
 }

This will close active editor by cmd+w . But will not close the vscode window when no editor is open.

**Comment by nparoski** [comment] 2021-04-13 07:28
@kartikeytewari solution works like a charm, if you are on windows just change `"key":cmd+w"` to `"key":ctrl+w"`

**Comment by christhomas** [comment] 2021-04-20 09:19
I mean, it's lovely that we can all edit our configurations. But can somebody at microsoft just make this the default already. I think 90+% of people want this behaviour as default on mac. I don't know anybody who would do it another way. The majority way must be the default way.

**Comment by bpasero** [comment] 2021-04-26 05:09
Given I got https://github.com/microsoft/vscode/pull/121988 assigned, I have spend a bit of time figuring out what operating systems recommend with regards to standard keyboard shortcuts. The choice of `Ctrl+W` (on Windows, Linux) and `Cmd+W` on macOS to close editors and the window (when no tab is opened) was not copied from browsers, but rather other text editors I looked at when we started with VSCode a long time ago. I still see other text editors (that share the same pattern of allowing to operate without tabs opened) use the same keyboard shortcuts for closing an editor and the window that we do.

I think the frustration in this issue stems from the fact that one keyboard shortcut is assigned to both closing a tab as well as closing the window which means that rapidly closing editors will potentially close the window by accident.

On **macOS** the standard keyboard shortcut for closing the window is actually `Cmd+W`. As for closing a document inside the application, it seems to be `Cmd+Shift+W`. To quit the application, it is `Cmd+Q`. Source: [Apple HIG](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/)

![image](https://user-images.githubusercontent.com/900690/116030483-e76f5500-a65b-11eb-9677-effc30a674c3.png)

On **Windows** there does not seem to be a dedicated keyboard shortcut to close a Window. But it looks like `Ctrl+F4` should be used to close a tab and `Alt+F4` to exit the application and/or close the window. Source: [Windows HIG](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/dnacc/guidelines-for-keyboard-user-interface-design)

![image](https://user-images.githubusercontent.com/900690/116030549-12f23f80-a65c-11eb-8ec4-d3532aba08cc.png)

Finally, on **Linux**, it looks like `Alt+F4` is for closing a window and `Ctrl+Q` to quit. `Ctrl+W` should be used to close a tab. Source: [Ubuntu HIG](https://help.ubuntu.com/stable/ubuntu-help/keyboard-nav.html.en) and [Gnome HIG](https://developer.gnome.org/hig/stable/keyboard-input.html.en)

![image](https://user-images.githubusercontent.com/900690/116030745-90b64b00-a65c-11eb-963d-65a679ba963e.png)
![image](https://user-images.githubusercontent.com/900690/116030768-9e6bd080-a65c-11eb-89fe-b089aabf740f.png)
![image](https://user-images.githubusercontent.com/900690/116030780-a3c91b00-a65c-11eb-867e-43265a78236e.png)

As such, I think a PR to resolve this issue should resolve it properly on each platform and not just remove the associated keybinding entirely. At the same time, I feel it could be frustrating for users to remove `Ctr+W`/`Cmd+W` to close an editor tab simply because we have been running with that keybinding for such a long time. So may I suggest this:
* **Windows**
   * Close Tab: `Ctrl+W` and `Ctrl+F4`
   * Close Window: `Alt+F4`
   * Quit: `<unassigned>`
* **Linux** 
   * Close Tab: `Ctrl+W`
   * Close Window: `Alt+F4`
   * Quit: `Ctrl+Q`
* **macOS**
   * Close Tab: `Cmd+W`
   * Close Window: `Cmd+W` (if no editor is opened)
   * Quit: `Cmd+Q`

I realise that at least on macOS this still means the same keyboard shortcut is bound to closing editors and closing windows. The original issue was not reported against macOS it seems, so addressing the other platforms seems good to me. On macOS specifically I believe that removing `Cmd+W` might be equally frustrating for new/existing users.

Thoughts?

**Comment by orgads** [comment] 2021-04-26 05:56
@bpasero Thank you for the thorough investigation.

All the bindings you wrote **already exist**, and of course I didn't touch them. What I removed is only the conditional key binding when no editor is open. If a user really wants this shortcut, it can be configured in the key bindings. The entry still exists, it's just not assigned with any binding.

**Comment by kartikeytewari** [comment] 2021-04-26 06:12
@bpasero I believe a better default keybinding for mac can be:
Close Tab: `Cmd+W`
Close Window: `Cmd+shift+W` 
Quit: `Cmd+Q`

This seems to be a better default because people can then close all the open files without accidentally closing the window. Also, since keybindings can be changed, people who like it the old way can simply change it to what they seem fit.

**Comment by orgads** [comment] 2021-04-26 06:18
I read the previous comments now, and noticed that a setting for confirmation was added, but it doesn't really work. This would be better than my proposal. Do you know what's missing for it to work?

**Comment by orgads** [comment] 2021-04-26 06:30
I pushed a new proposal, but can't test it currently. Can one of you test please?

**Comment by bpasero** [comment] 2021-04-26 07:53
@orgads I think you might want to read through https://github.com/microsoft/vscode/issues/14710 which is the associated issue for having a confirmation on quit and in https://github.com/microsoft/vscode/issues/14710#issuecomment-708509598 for example I found that the solution is not so easy as it might seem. Let's keep the issue around a confirmation independent from this issue here for now, ok?

@kartikeytewari we actually already bind `CtrlCmd+Shift+W` as keybinding to close window, even when editors are opened. 

I did not find that all the keybindings of my proposal were assigned, so I pushed a commit to have `Alt+F4` by default close the window on Linux + Windows  (`Ctrl+Shift+W` is assigned as secondary keybinding still).

As for changing the default of `Ctrl/Cmd+W` we will do a bit of UX discussion around this topic in the team before making a move.

**Comment by orgads** [comment] 2021-04-26 07:59
You don't need to assign Alt+F4. It is assigned by the window manager anyway.

**Comment by bpasero** [comment] 2021-05-03 12:46
With https://github.com/microsoft/vscode/commit/2126be633119f4f1f7fa3048abc874ef7760a906#diff-04d484897c02ce699521b4995d3d26d35ed572a2073e38fb3f5d2785f4f02366L51-L60, `Ctrl/Cmd+W` no longer runs the "Close Window" command when no editor is open.

**Closed by bpasero** 2021-05-03 12:46 UTC
Labels: feature-request, keybindings

**Comment by artdiniz** [comment] 2021-05-26 20:37
Hey, I know the issue is now closed, but I really want to point out my [Quit Control](https://marketplace.visualstudio.com/items?itemName=artdiniz.quitcontrol-vscode) extension. I think it solves this issue really well. 
I hate/love the default behavior. I'm really used and like to type `Cmd+W` on an empty window to close the window. But I too like fast typing `Cmd+W` to close all tabs, and hate it when it closes my window by mistake. 

So what my extension does is to prompt if the window is going to be closed. It's not a blocking prompt, it's a quick pick menu, easily skippable. User can just press `Enter` to confirm the close action or press `Esc` to dismiss.

**Comment by artdiniz** [comment] 2021-05-26 20:42
Another thing, @bpasero, will my extension be able to bind its commands to the `Alt+F4` keybinding with those new changes? I wasn't able to do it previously 🤔

**Comment by shamelesscookie** [comment] 2021-05-31 11:22
Unpopular opinion, but I actually liked the original behavior (CMD+W closes the window when no editors are open).

I had to set the following in `keybindings.json` to get the old behavior back:

```
{
  "key": "cmd+w",
  "command": "workbench.action.closeWindow",
  "when": "!editorIsOpen && !multipleEditorGroups"
}
```

**Comment by ednl** [comment] 2021-06-11 03:29
@bpasero "On macOS specifically I believe that removing Cmd+W might be equally frustrating for new/existing users." -- Completely agree, and very frustrating, yes.

This has now been thrown out in 1.57. I think it is wrong to break default/standard/recommended MacOS behaviour based on feedback of what seem to be overwhelmingly Win/Linux users, and expect the user to restore standard MacOS behaviour by editing config files. I did not ask for this, and I expect MacOS apps to behave like MacOS apps should.

**Comment by bpasero** [comment] 2021-06-11 06:11
> I did not ask for this, and I expect MacOS apps to behave like MacOS apps should.

Well, that would result in a change that is imho even worse: `Cmd+W` to close the window and `Cmd+Shift+W` to close a tab (see https://github.com/microsoft/vscode/issues/54492#issuecomment-826505242). I didn't want to push that onto everyone, that is why we settled with what we have now. 

Did I misunderstand the Apple HIG in this case?

**Comment by shamelesscookie** [comment] 2021-06-11 08:03
> Did I misunderstand the Apple HIG in this case?

The original VSCode behavior was “more correct”. In a web browser, for example, having many tabs open, Cmd+W will close the active tab unless you are on the only tab, in which case Cmd+W closes the window. It’s the same behavior as Ctrl+W on Windows. So this change makes VSCode an outlier which is causing confusion.

I agree it is misbehaving now and also believe it should be reverted. At least the default behavior should have been unchanged, but perhaps instead a new setting to easily toggle this behavior should have been added to appease people like OP who don’t like the standard operating system behavior.

**Comment by bpasero** [comment] 2021-06-11 08:20
I don't think VSCode should be compared to a web browser though and that was the original complaint leading to this change too: VSCode can run perfectly fine without tabs opened, while a web browser cannot stay open when the last tab closes. For a web browser the tab is essentially the window and the window cannot show without a tab. VSCode can have no tabs opened, so the window can exist without any tab opened.

**Comment by shamelesscookie** [comment] 2021-06-11 08:29
Yes, but the question is not "what will VS Code do when you issue a close command with one tab open" then question is "What will VS Code do when issue a close command and nothing is open".

The new behavior is not normal in any OS. No one is suggesting that VS Code close when the last editor is closed. We are suggesting that when no editor is open, and THEN another close command is issued, that the window be closed.

**Comment by orgads** [comment] 2021-06-11 08:36
I agree that VS Code should not be compared to a browser.

When using a browser, when you close the last tab, you're done. On VS Code you have an open workspace, and you typically still work on this project, even after you closed all the editors. I'm personally used to pressing Ctrl-W and holding it until all the editors are closed. I was very surprised when the editor was closed. No other *editor* I'm aware of behaves this way. For example, Notepad++.

**Comment by bpasero** [comment] 2021-06-11 08:40
> We are suggesting that when no editor is open, and then ANOTHER close command is issued, that the window be closed

But this was exactly the frustration not only a lot of users had but even in the team: when you rapidly close tabs you might accidentally close the entire window because you continued to issue the "Close Editor" command when no editor was opened and that would close the window.

**Comment by shamelesscookie** [comment] 2021-06-11 08:48
Windows is certainly inconsistent. Ctrl+W varies from app to app (things like Explorer, Notepad, and web browsers all allow you to close the window when there's nothing left to do).

If people are adamant that the Windows behavior take a "do not close" stance, I can at least understand that because it's case-by-case. But it's unquestionably incorrect behavior on Mac to allow Cmd+W to close tabs but prevent it from closing a window.

**Comment by ednl** [comment] 2021-06-11 09:32
@bpasero:
> Did I misunderstand the Apple HIG in this case?

I think so, yes. As I understand it and [as I read it](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/), it means that Cmd-W closes one active window, Cmd-Shift-W closes multiple windows (all associated with one document), Opt-Cmd-Shift-W closes all open windows of the app. The latter two seem to be somewhat outdated recommendations back from when apps used to have multi-document interfaces.

I tested this with the single-document interfaces of the Xcode IDE from Apple and the editors Coda and Nova from Panic; all three close documents with Cmd-W, leave the app window open after the last document is closed, then close the app window for another Cmd-W (but not quit the app, which is Cmd-Q).

**Comment by bpasero** [comment] 2021-06-11 09:58
> I tested this with the single-document interfaces of the Xcode IDE from Apple and the editors Coda and Nova from Panic; all three close documents with Cmd-W, leave the app window open after the last document is closed, then close the app window for another Cmd-W (but not quit the app, which is Cmd-Q).

Great, I was about to test that. I think we should push a change then for macOS specifically to revert it there. Will investigate as part of our recovery release.

**Comment by bpasero** [comment] 2021-06-11 12:19
Recovery issue: https://github.com/microsoft/vscode/issues/126042

**Comment by CalumFormby** [comment] 2021-06-11 13:14
I preferred being able to use ctrl + w to close the application. This is really annoying now. Alt + F4 doesn't really work for me since I have a keyboard which requires you to hold the FN button to be able to use the F keys.

**Comment by shamelesscookie** [comment] 2021-06-11 13:23
> 
> 
> I preferred being able to use ctrl + w to close the application. This is really annoying now. Alt + F4 doesn't really work for me since I have a keyboard which requires you to hold the FN button to be able to use the F keys.

@CalumFormby you can override the new behavior.

1. Hit Ctrl+Shift+P to open the command palette.
2. Search for "Open Keyboard Shortcuts (JSON)"
3. Paste the following:

```
[
  {
    "key": "ctrl+w",
    "command": "workbench.action.closeWindow",
    "when": "!editorIsOpen && !multipleEditorGroups"
  }
]
```

**Comment by MartinRJ** [comment] 2021-06-12 18:32
This was not a valid bug, but a default/standard behaviour.
Please stop treating feature requests as bugs. This project needs better QA, quite obviously.

**Comment by ryanhiebert** [comment] 2021-06-13 21:38
Lots of people here are not liking this change, that's understandable, not everyone will be happy. I read this in the changelog, and audibly said "yes! thank you!". Thank you, vscode team!

Closing a workspace is sufficiently different action than closing a window that it should be a different keystroke. Re-opening a workspace is sufficiently more annoying than re-opening a file that this footgun should be avoided by default. I often found myself closing several terminals that I did not want to close, simply for pressing this button one too many times when closing open files.

**Comment by CalumFormby** [comment] 2021-06-14 08:23
@shamelesscookie Awesome, thanks for that :)

**Comment by ednl** [comment] 2021-06-14 15:57
> Closing a workspace is sufficiently different action than closing a window that it should be a different keystroke. Re-opening a workspace is sufficiently more annoying than re-opening a file that this footgun should be avoided by default.

@ryanhiebert I can understand having Ctrl-W removed for closing the workspace in Win/Linux because closing the window also quits the app and you have to re-start it, possibly using the mouse. But Cmd-W on Mac works the same in every app: it closes the window *but does not quit the app* which even remains active. So re-opening it is just another keystroke away (e.g. Cmd-O to open or Cmd-N for new file which in this case only re-opens the window). In any case, it looks like they will leave out Ctrl-W but reinstate Cmd-W in the next update, so that will probably, hopefully, maximise the number of happy people.

**Comment by ryanhiebert** [comment] 2021-06-14 16:27
> So re-opening it is just another keystroke away (e.g. Cmd-O to open or Cmd-N for new file which in this case only re-opens the window).

I am on a Mac. I love my Mac. I really like that closing windows does *not* close the application.

But closing tabs in bulk should not end in closing my workspace, which is far more than just a collection of tabs. As I mentioned, I regularly run terminals. Sometimes these are environments that are a bit annoying to set up.

It sounds to me like you think command+w should close the workspace. I disagree, but I can make sense of that, from the standpoint of consistency with other applications. I can't make sense of thinking that closing an editor and closing a workspace should share the same keystroke.

Thanks for the cmd k+w hint, I'm glad it exists. Sharing this shortcut between wildly different app-specific contexts is still an obvious footgun that would be wise to avoid, imo. Having a command that doesn't explode your workspace because you pressed the keystroke that closes a single editor still seems like an importantly better user experience to me. Requiring users to avoid common usage patterns because those patterns will make their workspace evaporate unintentionally seems like a less than optimal default experience.

**Comment by ednl** [comment] 2021-06-14 19:43
Sounds to me like you never really use Cmd-W to close a window, only ever to close tabs. If that's the case, I think I may never convince you! Which is fine.

I do think the right decision is to conform to Apple Human Interface guidelines and act the same as any other app on MacOS, also Xcode for instance, and have Cmd-W *by default* always close the currently active "window" whether that's an editor tab or the workspace window. If you want non-standard behaviour like in this release (i.e. Cmd-W never closes the Vscode window) then you can define that in the settings by adapting #issuecomment-859578980

**Comment by beantowel** [comment] 2021-06-15 02:36
Now in vscode 1.57.0, Cmd-W can't close an empty window.

**Comment by ryanhiebert** [comment] 2021-06-15 03:30
@ednl: Actually, I do close the window frequently via cmd-w. Sometimes intentionally, sometimes not. I also think that cmd-shift-w being the exclusive way to close the project window entirely is preferable.

I find no particular precedent for how to decide this interface. The HIG guidelines, as far as I can tell, don't say how to handle tabs at all, though it seems likely that I've missed it, since I'd have guessed they would have extended them as they applied them to their own applications that have tabs.

Safari, finder, and others that I can think of are importantly dissimilar to vscode in that closing the final tab in those applications *also* closes the window. There is no sufficient purpose for keeping the window open once all the tabs have closed in those applications, but that is most certainly *not* the case in this application. I think you'll agree with that, since I do not think you're advocating that the window itself should be closed along with the final tab.

A precedent worth considering is that the command to close the window is cmd+shift+w (except when the tab and the window are one and the same). You can think of it like "close all tabs", but that is constrained to one window, and importantly, the menu clearly assigns the shortcut to "close window".

That's my reasoning. One final word of caution from me. When you say "the right decision is to conform to Apple Human Interface guidelines", I totally agree. But I haven't found any word about this distinct case, so I must draw on other precedent to find what seems like the most natural application of the principals it has laid out.

We disagree on what is most natural, and that's perfectly okay. I believe the way you're applying the HIG to this case is reasonable, but suboptimal. However, the way your statement about the HIG comes across to me as suggesting that yours is the only possible way to apply the HIG to this situation. While I don't hope to have convinced you that my preference is optimal, I do hope that you understand that unless and until this case is clarified in the HIG, there are indeed other reasonable applications of the HIG than your preference, and that the behavior as implemented is one of them.

**Comment by gavinr** [comment] 2021-06-15 04:12
How am I supposed to close all tabs in a workspace and the workspace if I have three files open?

Before this change: `Ctrl-W-W-W-W` (5 keystrokes)

After this change: `Ctrl-W-W-W`, `Alt-F4` (6 keystrokes plus a hand movment)

Is there a more efficient way?

**Comment by uxjw** [comment] 2021-06-15 06:22
> How am I supposed to close all tabs in a workspace and the window if I have three files open?
> 
> Before this change: `Ctrl-W-W-W-W` (5 keystrokes)
> 
> After this change: `Ctrl-W-W-W`, `Alt-F4` (6 keystrokes plus a hand movment)
> 
> Is there a more efficient way?

On Mac, Shift-CMD-W will now close the window and all its' tabs. Try Shift-Ctrl-W on Windows

**Comment by ednl** [comment] 2021-06-15 09:02
@ryanhiebert Yes, it is my interpretation of the HIG, but I think it is the right one ;) You are right: the HIG hasn't been updated with explicit reference to tabs as used by single-document interface apps (as opposed to what was the norm: multiple separate windows in a multi-document interface). See my earlier comment at https://github.com/microsoft/vscode/issues/54492#issuecomment-859446692

I agree on browsers being different. But Xcode and other editors like Panic's Coda and Nova behave like what I think is the norm: close tabs one by one, then close the app window.

**Comment by ryanhiebert** [comment] 2021-06-15 11:36
> I agree on browsers being different. But Xcode and other editors like Panic's Coda and Nova behave like what I think is the norm: close tabs one by one, then close the app window.

Xcode at least is significant precedent. After my last comment, I did open Xcode and saw that it worked that way. I think my preference would be better, but :shrug:. I'm not familiar with the other editors personally. Good talking with you!

**Comment by gavinr** [comment] 2021-06-15 13:03
> Try Shift-Ctrl-W on Windows

`Shift-Ctrl-W` closes the window but not the tabs (next time you open the window, the tabs are still oen). So using that it's still:

---

Before this change: `Ctrl-W-W-W-W` (5 keystrokes)

After this change: `Ctrl-W-W-W`, `Alt-F4` (6 keystrokes plus a hand movment)
- or:
  - `Ctrl-W-W-W`, `Shift-Ctrl-W` (7 keystrokes)

**Comment by julian3xl** [comment] 2021-06-17 08:12
This change is a shame, you've changed the common behaviour we've been using on mac for 30 years

**Comment by mxcl** [comment] 2021-06-17 15:11
I’m not sure why this is even a discussion, the standard Mac behavior is simple:

* ⌘W closes tabs
* ⌘W closes windows
    * **If closing the Window would cause something bad to happen, prompt the user with a dialog to confirm they want this**

VSCode is a pretty good Mac app, but this decision suggests you should hire a Mac UX person for consultation.

**Comment by ednl** [comment] 2021-06-17 16:27
@julian3xl @mxcl Apparently this is going to be reversed for Mac in the next update, see https://github.com/microsoft/vscode/issues/54492#issuecomment-859541726

**Comment by merschformann** [comment] 2021-06-18 04:39
Not a Mac person, but still preferring prior behavior. Thank you for the workaround @shamelesscookie .

**Comment by Ulrikop** [comment] 2021-06-18 16:09
I'm a Linux user and I'm also confused about the new behavior.

especially with multiple opened windows it was good to close just the current window with ctrl + w if no tab was opened and close all windows with ctrl + q

**Comment by ryanhiebert** [comment] 2021-06-18 16:19
> If closing the Window would cause something bad to happen, prompt the user with a dialog to confirm they want this

@mxcl @ednl. I think that this suggestion, if implemented well, would alleviate my challenges with the previously existing behavior that prompted this change in the first place. I'm not sure how well vscode can detect whether terminals and other things (perhaps extensions?) that might be important to the user and annoying to recreate are open, but if that could be done reliably, I would drop my objection to `⌘ W` closing the project.

I still think that `⇧ ⌘ W` would be an excellent shortcut for closing the window and all tabs even if there are terminals and other things open, without the prompt for the user to confirm the action. I'm not sure if it previously worked that way or not (since I'm now using the newer behavior and can't check), but it should. I'd use it now that I know it and have thought about it.

**Comment by artdiniz** [comment] 2021-06-18 18:34
> If closing the Window would cause something bad to happen, prompt the user with a dialog to confirm they want this

I really think that's the best UI possible, and that's the reason why I made [QuitControl extension](https://marketplace.visualstudio.com/items?itemName=artdiniz.quitcontrol-vscode). Pressing `Enter` after `Cmd + W` to confirm window close and `Esc` or any other interaction to dismiss it is such a no-brainer. I couldn't live without it 😅

**Comment by samvdkris** [comment] 2021-06-19 19:16
I feel like this should maybe be an easy setting instead of a keybind that users have to configure themselves (similar to the existing "close when empty" setting)?

In my opinion, CTRL+W to close the window when no tabs are left is the logical thing to do, but I can certainly see why it could be annoying if done unintentionally (never had it happen, but fair enough).

I can also see why people who are annoyed by this would look through the settings first before adding a custom keybind. But changing the default behavior was a bit unnecessary.

And lastly, I really don't think this should've been a bug report. Reopening the linked feature request issue asking for an easy setting is one thing, but this is *not a bug*. It's a deliberate choice, that (in my opinion) better fits the text editor-like style of VS Code.

**Comment by merschformann** [comment] 2021-06-19 22:17
FWIW:

To me it seems like prior behavior was also more in line with Ubuntu at least (don't want to generalize for the whole Linux world). _gedit_, _gnome file manager_, _gnome terminal_ and of course the browsers close the window with or after closing the last tab.
(for gnome terminal the default key binding is obviously slightly different though - `ctrl+shift+w`)

I like the behavior for applications which I usually have open in multiple windows with multiple tabs each. `ctrl+q` does of course not work (as it also closes other windows) and yet another shortcut seems redundant. (this totally is a personal opinion / style of course)

As a former Windows user I understand that these key bindings may not be familiar. Therefore, not sure what the default behavior should be and also not sure whether different behavior on different OS is great (I for one work on multiple platforms). ¯\\\_(ツ)\_/¯ 
However, it would at least be great to have an easier switch for converting to prior behavior - not only on Mac.
(still thankful for @shamelesscookie's workaround though, so, I am happy =) - but that's not an intuitive solution).
