### ISSUE TITLE
code hints blurred

### ISSUE THREAD

**Issue by prayjourney** [microsoft/vscode#110505] opened 2020-11-12 17:24 UTC
- VSCode Version: 1.51.0
- OS Version: win10.2004

Steps to Reproduce:
1. write any code
2. trigger code hint and the code hints blurred, like below
![2020-11-13_010931](https://user-images.githubusercontent.com/15311937/98973430-b1776200-254e-11eb-94a3-23424976f82c.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2020-11-13 02:15
Looks like it's super small, can you try to [resize the suggest widget](https://code.visualstudio.com/updates/v1_51#_resizable-suggestions) and see if it's still blurred?

**Comment by prayjourney** [comment] 2020-11-13 02:34
> Looks like it's super small, can you try to [resize the suggest widget](https://code.visualstudio.com/updates/v1_51#_resizable-suggestions) and see if it's still blurred?

I tried, still like this
![搜狗截图20201113102548](https://user-images.githubusercontent.com/15311937/99021112-eb6e5580-259a-11eb-9ef0-cdb9779705fa.png)
and I also tried this method[Editor window becomes super-blurry #44168](https://github.com/microsoft/vscode/issues/1896#issuecomment-269544361), it's still blurred

**Comment by prayjourney** [comment] 2020-11-13 02:41
> Looks like it's super small, can you try to [resize the suggest widget](https://code.visualstudio.com/updates/v1_51#_resizable-suggestions) and see if it's still blurred?

老哥，看上面的照片，代码提示部分糊了，但是具体提示的小窗口，代码提示窗口可以拖动设置大小，但是仍然是糊的，具体的提示是显示okay的。之前禁止了所有的插件，显示情况也是这样，有点郁闷啊。。。

**Comment by yume-chan** [comment] 2020-11-13 03:49
左边列表也是可以拖动调整大小的

**Comment by prayjourney** [comment] 2020-11-13 04:36
> 左边列表也是可以拖动调整大小的

拖动没有用，拖动了还是显示模糊...

**Comment by jrieken** [comment] 2020-11-13 15:11
/duplicate of https://github.com/microsoft/vscode/issues/110078

**Closed** 2020-11-13 15:12 UTC
Labels: *duplicate, suggest
