### ISSUE TITLE
Tab not quite as expected when using snippets within snippets

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#5751] opened 2016-04-25 12:26 UTC
- VSCode Version: Version 1.0.1-insider (1.0.1-insider) - 85f337ee0851a464d5459ce9a354d05f94f0b9a4
- OS Version: OSX Yosemite 10.10.5

See animated gif below (sorry for resolution!):
![animated gif](http://i.giphy.com/xT1XGLJFhjDh4A97zO.gif)

I am not sure if the tab button should continue switching between the outer snippet's placeholders, or if it should respect the inner snippet's placeholders until ESC is pressed, at which point it returns to the outer snippet's context?

**Comment by alexandrudima** [comment] 2016-04-27 13:25
@massimocode The snippets are not stacking (i.e. if you are in snippet mode and insert a new snippet the new snippet now takes over and pressing Escape leaves snippet mode entirely).

Can you please share the exact snippets you are running so I can debug what's going on?

**Comment by alexandrudima** [comment] 2016-10-27 20:28
Closing after a number of days without a reply.

**Comment by massimocode** [comment] 2016-10-28 07:53
Hey sorry I had been really busy and totally forgot about this issue. Sure, my snippets are here:

```
	"It": {
		"prefix": "iii",
		"body": [
			"it('$1', () => {",
			"    $2",
			"});"
		]
	},
	"Expect to have been called with exactly": {
		"prefix": "etc",
		"body": [
			"expect($1).to.have.been.calledWithExactly($2);"
		]
	},
```

**Comment by massimocode** [comment] 2016-10-28 07:53
The issue still exists in the latest version:
- VSCode Version: Code - Insiders 1.7.0-insider (5bafcdb3d67b29b1f4667a3f497ac05a41dde667, 2016-10-25T06:11:16.069Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.0.8|
|githistory|donjayamanne|0.1.0|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|typescript-javascript-grammar|ms-vscode|0.0.6|
|vscode-subword-navigation|ow|1.1.5|
|Ruby|rebornix|0.10.1|
|vscode-icons|robertohuertasm|3.0.6|
|annotator|ryu1kn|0.10.1|
|wallaby-vscode|WallabyJs|1.0.28|

**Comment by alexandrudima** [comment] 2016-10-31 11:29
Steps:

* complete snippet `iii`
* tab
* complete snippet `etc`
* editor is not in snippet mode at the end.

**Comment by jrieken** [comment] 2017-05-09 16:46
closing this as dupe of #24855

**Closed by jrieken** 2017-05-09 16:46 UTC
Labels: bug, snippets
