### ISSUE TITLE
Editor Very Dark or Dim with HDR

### ISSUE THREAD

**Issue by deathernater** [microsoft/vscode#102526] opened 2020-07-14 20:03 UTC
Issue Type: <b>Bug</b>

When Windows HDR color is enabled on my HDR desktop monitor, Visual Studio Code's windows appear very "dim" or dark.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0

</details>

**Comment by IllusionMH** [comment] 2020-07-14 20:13
/duplicate of #88491

See https://github.com/microsoft/vscode/issues/88491#issuecomment-589527628 for worakround

**Closed** 2020-07-14 20:13 UTC
Labels: *duplicate, new release
