### ISSUE TITLE
Is any setting for always expanding all outline section level?

### ISSUE THREAD

**Issue by V0idk** [microsoft/vscode#58095] opened 2018-09-06 16:47 UTC

**Comment by roblourens** [comment] 2018-09-06 18:07
I don't understand the question, please provide more details.

**Comment by zoehneto** [comment] 2018-12-04 19:38
Adding an expand all button as requested in #54941 might also be a workaround for this issue.

**Comment by zachvalenta** [comment] 2019-03-07 23:57
@zoehneto 

* Agree 100%; structured text (Markdown docs with a few levels of nesting) is exactly how I ended up at this issue
* Personally I'd prefer 'expand all' as a setting; mouse interaction would kill the "quick glance what's happening in this document" utility of an outline

**Comment by niderhoff** [comment] 2020-01-14 08:59
> @zoehneto
>     * Personally I'd prefer 'expand all' as a setting; mouse interaction would kill the "quick glance what's happening in this document" utility of an outline

As a fix for now, you can try CTRL+SHIFT+O which will also give you a "quick glance" without using the mouse :)

**Comment by niderhoff** [comment] 2020-01-14 09:02
Also I want to note that there is a bug sometimes with the "expand all" button that is implemented now from #54941 where the outline is collapsed completely, but the button doesn't recognize that and only offers a choice to "collapse all" which renders the button useless until you manually expand the outline using the tree nodes.

**Comment by jrieken** [comment] 2020-10-06 08:48
/duplicate of https://github.com/microsoft/vscode/issues/53262

Closing as dupe of https://github.com/microsoft/vscode/issues/53262 - if we add setting they will allow for collapsing and expanding

**Closed** 2020-10-06 08:48 UTC
Labels: *duplicate, feature-request, outline
