### ISSUE TITLE
QuickPickItem: support for showing file icons

### ISSUE THREAD

**Issue by igorskyflyer** [microsoft/vscode#128589] opened 2021-07-13 22:45 UTC
I am not sure if I missed something, I've been through the API docs and couldn't find anything about this feature and I have searched the Issues but couldn't find relevant ones. I am wondering if it is already possible to get the icons from the current file icon theme - needed for consistency - from an extension? Either as SVGs or if applicable `ThemeIcon`objects since the use case would be to use the icons inside labels of `QuickPickItems`.

If it's not available, are there any plans for such feature? Thank you.

**Comment by aeschli** [comment] 2021-07-15 07:20
We have file icon themes and product icon themes.

You can reference product icons and use them at various places (wherever ThemeIcon's are applicable) https://code.visualstudio.com/api/references/icons-in-labels

File icons are mapped to specific resources (by name, extension, or language) by the file icon theme and don't have a specific name to be referenced.

We allow a custom `TreeView` to define a `resourceUri` for the `TreeItem`. It that's set the item will get the icon that matches that the given resource.

We don't have a similar API for QuickPickItem. Please file an issue if that's what you need.

**Comment by igorskyflyer** [comment] 2021-07-19 18:19
Yes, @aeschli I am aware of that and I am actually already using Product Icons, what I meant - sorry if I wasn't clear enough - when we enable `files.simpleDialog.enable` we get a QuickPick that uses the icons from current file icon theme (see image).
Are there ways of getting those icons to appear in an extension's custom QuickPick or are those private?

![simple-dialog](https://user-images.githubusercontent.com/20957750/126207429-785f6d10-b0a7-46c4-8d1e-c69004689fab.png)

**Comment by TylerLeonhardt** [comment] 2021-07-20 13:39
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/59826.

Its definitely something I want to light up for extension authors. I know @eamodio wants this too 😁

I'm gonna close this in favor of the existing issue but please let me know if I got it wrong.

**Closed** 2021-07-20 13:39 UTC
Labels: quick-pick

**Comment by igorskyflyer** [comment] 2021-07-20 15:14
@TylerLeonhardt we all do! 😁 To be honest, I was thinking of making a PR here and trying to implement that myself but my laptop is *very* low-spec so it's a no for me. 😰 I guess I'll wait for you guys. 😅
