### ISSUE TITLE
wrapping long lines when comparing files

### ISSUE THREAD

**Issue by Sigurd-Angenent** [Microsoft/vscode#47847] opened 2018-04-13 19:36 UTC
Sometimes I have to compare two text files with long lines (e.g. latex files written by coauthors).  The side by side file comparison would be easier to read if long lines were wrapped.

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment] 2018-04-16 13:09
Duplicate of #11387

**Closed by alexandrudima** 2018-04-16 13:09 UTC
Labels: diff-editor, editor, editor-core
