### ISSUE TITLE
cursor placed automatically into closing tag

### ISSUE THREAD

**Issue by artistry-intelligence-solutions** [microsoft/vscode#89022] opened 2020-01-21 11:47 UTC
- VSCode Version: _1.41.1_
- OS Version: _Win 10 Home v1903_

Steps to Reproduce:

1. copy a string to paste into a html file tag such as an a class into a div
2. paste the class into opening tag and _VS Code_ adds the class into closing tag as well

### Result
`<p class="center-text"></p class="center-text">`

instead of

`<p class="center-text"></p>`

**Comment by IllusionMH** [comment] 2020-01-21 12:02
/duplicate of #87067

you can use `"html.mirrorCursorOnMatchingTag": false` to disable cursor mirroring.

**Closed** 2020-01-21 12:02 UTC
Labels: *duplicate
