### ISSUE TITLE
After installing VS the logo doesn't show up

### ISSUE THREAD

**Issue by whatsupbro** [Microsoft/vscode#25123] opened 2017-04-21 05:12 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment] 2017-04-21 21:17
The issue is unclear to me

Please describe the expected behavior and the actual behavior, along with any repo steps. Screenshots would also be helpful

**Comment by mjbvz** [comment] 2017-05-01 19:50
Closing since there is not enough info to investigate this

**Closed by mjbvz** 2017-05-01 19:50 UTC
Labels: needs more info
