### ISSUE TITLE
cannot insert a <div>, automatically corrects to </div>

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#80600] opened 2019-09-10 00:40 UTC
Mac and Windows
Insiders and 1.38 Stable
All extensions disabled

This looks like a regression.

Consider the following HTML:

``` html
<!DOCTYPE html>
<html>
<head>
</head>

<body>
    <div>
         <!-- put cursor here, type in "<div>" then press enter result is "</div>"  -->
    </div>
</body>
</html>
```

If you put the cursor inside the first `<div>` and then try to create another div:

![image](https://user-images.githubusercontent.com/1487073/64575368-4a499680-d328-11e9-813a-21c1c45023a3.png)

And then press enter, the result is `</div>`.

![image](https://user-images.githubusercontent.com/1487073/64575378-5a617600-d328-11e9-8f71-f3a650cc1066.png)

In 1.37.1 stable, i get what i expect:

![image](https://user-images.githubusercontent.com/1487073/64575405-8d0b6e80-d328-11e9-8d57-b70e77435034.png)

**Comment by octref** [comment] 2019-09-10 01:56
It's a bug, not a regression. I can repro in 1.37 as well. @aeschli fyi.

**Comment by chrisdias** [comment] 2019-09-10 02:23
hmmm i can't repro this in 1.37.1 so i'll upload a video. also we can sit together tomorrow.

**Comment by octref** [comment] 2019-09-10 02:42
I see. My repro was wrong.

It seems auto-closing (`editor.insertSnippet` API) would cancel suggest widget in 1.37.1, but not in latest.

**Comment by chrisdias** [comment] 2019-09-10 03:19
here's a video of 1.37.1, then insiders, then 1.38.0:

![div](https://user-images.githubusercontent.com/1487073/64581391-c2bb5200-d33e-11e9-8333-bed0e61f341b.gif)

**Comment by jrieken** [comment] 2019-09-10 13:27
Like caused by fixing https://github.com/microsoft/vscode/issues/26012 (which I think is still a good fix)

**Closed** 2019-09-10 15:19 UTC
Labels: candidate, regression
