### ISSUE TITLE
download page is broken.

### ISSUE THREAD

**Issue by Pyxelx** [Microsoft/vscode#62428] opened 2018-11-02 01:36 UTC
Can't access the download page to download the program, at all.
Seems the entire update domain is down for the matter.

![chrome_2018-11-01_21-36-10](https://user-images.githubusercontent.com/31185937/47889021-28d17180-de1e-11e8-8bf2-0611c8266ec9.png)

**Comment by mjbvz** [comment] 2018-11-02 01:44
Duplicate of #62427

**Closed by mjbvz** 2018-11-02 01:44 UTC
Labels: install-update
