### ISSUE TITLE
iPadOS: layout breaks with many search results

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120615] opened 2021-04-06 08:45 UTC
When I used iPadOS on Codespaces I often ended up with the search view breaking up with a scrollbar appearing when I got many search results.

Steps are pretty much: run searches with many results from the search viewlet.

Filing this issue here as a reminder to investigate and to you Isi, since you are assigned.

**Comment by isidorn** [comment] 2021-04-06 12:19
Thanks for filling I can look into this once I setup my iPad.

**Comment by isidorn** [comment] 2021-04-12 13:57
I can reproduce this, but for me it is not that Layout is breaking, but that the whole view freezes.
Also I can reproduce this just with Safari, iPad is not needed.

So easy steps for me:
1. yarn web
2. open it in Safari
3. Search for "a"

The whole tab freezes

fyi @roblourens

**Comment by bpasero** [comment] 2021-04-12 15:20
I see the freezing as well, but I also see the layout breaking together. Check this where e.g. the search input field is gone:

![Screenshot 2021-04-12 at 17 19 37](https://user-images.githubusercontent.com/900690/114418999-54421400-9bb3-11eb-80a8-46e52c43076e.png)

I was running a few searches, a couple of them large.

**Comment by roblourens** [comment] 2021-04-12 23:41
The layout issue is because `height: 100%` is just not doing the right thing, I think due to being inside a flex item, like https://stackoverflow.com/questions/15381172/how-can-i-make-flexbox-children-100-height-of-their-parent but I can't get anything else to work in Safari. Will hack on it some more.

The hang I think is because the list is sized wrong, causing us to render a ton of results offscreen.

**Comment by isidorn** [comment] 2021-04-26 13:02
Unaasigning myself, let me know if I can help though.

**Comment by JacksonKearl** [comment] 2022-04-08 22:24
Maybe fixed by #145996.

**Comment by JacksonKearl** [comment] 2022-04-08 22:33
Actually I can't repro on Desktop or iPad on stable. Can anyone else repro?

**Comment by roblourens** [comment] 2022-04-08 23:12
Seems likely that the Safari bug was fixed.

**Closed by roblourens** 2022-04-08 23:12 UTC
Labels: bug, search, web, safari, ios-ipados
