### ISSUE TITLE
Could not run on CentOS 7 with x2go

### ISSUE THREAD

**Issue by nabroyan** [Microsoft/vscode#25611] opened 2017-04-28 09:01 UTC
I have installed the latest version of VS Code on CnetOS 7. 
However when I try to run VS Code, it loads for some time trying to open, but then nothing happens, no errors, nothing.
I have tried to installed both trough rpm package and zipped files, but got the same result in both cases.

I'm using x2go to connect to my CentOS 7.

**Comment by nabroyan** [comment] 2017-04-28 09:02
When I run /usr/share/code/code --verbose, I get

{ Error: ENOENT: no such file or directory, open '/qt_home/nabroyan/.config/Code/storage.json'
    at Error (native)
    at Object.fs.openSync (original-fs.js:640:18)
    at Object.fs.readFileSync (original-fs.js:508:33)
    at e.load (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:142090)
    at e.getItem (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:141653)
    at e.handleUpdated (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:173039)
    at new e (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:172940)
    at v (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:13686)
    at t._createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:158694)
    at t._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:159669)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/qt_home/nabroyan/.config/Code/storage.json' }
[main 5:01:27 AM] Starting VS Code in verbose mode
[main 5:01:27 AM] from: /usr/share/code/resources/app
[main 5:01:27 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }

**Comment by Tyriar** [comment] 2017-05-01 20:54
@nabroyan can you paste in the output of this:

```
ls -la ~/.config/Code
```

**Comment by nabroyan** [comment] 2017-05-02 06:47
Sure. Here it is

total 9
drwxr-xr-x+  4 nabroyan Dev  5 Apr 28 05:00 .
drwx------+ 15 nabroyan Dev 18 Apr 28 04:03 ..
srwxr-xr-x+  1 nabroyan Dev  0 Apr 28 05:00 1.11.2-main.sock
drwxr-xr-x+  2 nabroyan Dev  2 Apr 26 08:48 CachedData
drwxr-xr-x+  2 nabroyan Dev  2 Apr 26 08:48 User

**Comment by Tyriar** [comment] 2017-05-02 21:45
@nabroyan does the folder also have the right permissions? I'm expecting this:

```
❯ ls -la ~/.config/
...
drwxr-xr-x  7 daniel daniel 4096 Apr  4 11:07 Code
```

I'm not sure why this would happen outside of permissions problems. You could try creating the file and seeing if that fixes the issue:

```
touch ~/.config/Code/storage.json
```

**Comment by nabroyan** [comment] 2017-05-03 07:01
@Tyriar  I get this kind of output when checking permissions for the folder

> drwxr-xr-x+  4 nabroyan Dev     5 Apr 28 05:00 Code

I have tried to create a storage.json file, but I get another error. When I run /usr/share/code/code --verbose, I get

> SyntaxError: Unexpected end of JSON input
>     at e.load (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:142082)
>     at e.getItem (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:141653)
>     at e.handleUpdated (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:173039)
>     at new e (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:172940)
>     at v (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:13686)
>     at t._createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:158694)
>     at t._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:159669)
>     at t._getOrCreateServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:158855)
>     at Object.get (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:156957)
>     at ee (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:303991)
> [main 2:58:14 AM] Starting VS Code in verbose mode
> [main 2:58:14 AM] from: /usr/share/code/resources/app
> [main 2:58:14 AM] args: { _: [],
>   help: false,
>   h: false,
>   version: false,
>   v: false,
>   wait: false,
>   w: false,
>   diff: false,
>   d: false,
>   goto: false,
>   g: false,
>   'new-window': false,
>   n: false,
>   'unity-launch': false,
>   'reuse-window': false,
>   r: false,
>   performance: false,
>   p: false,
>   'prof-startup': false,
>   verbose: true,
>   logExtensionHostCommunication: false,
>   'disable-extensions': false,
>   disableExtensions: false,
>   'list-extensions': false,
>   'show-versions': false,
>   nolazy: false }

**Comment by Tyriar** [comment] 2017-05-15 20:52
Maybe storage.json needs to be well formed, try changing its contents to `{}`

**Comment by nabroyan** [comment] 2017-05-16 08:47
After changing, when I run
`~$ /usr/share/code/code --verbose I get`

```
[main 4:41:00 AM] Starting VS Code in verbose mode
[main 4:41:00 AM] from: /usr/share/code/resources/app
[main 4:41:00 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }

```

**Comment by Tyriar** [comment] 2017-05-16 17:20
I suspect this is a duplicate of https://github.com/Microsoft/vscode/issues/3451, basically we don't support remoting very well just yet. There is a work around https://github.com/Microsoft/vscode/issues/3451#issuecomment-293017881 that might work.

**Closed by Tyriar** 2017-05-16 17:20 UTC
Labels: linux, needs more info
