### ISSUE TITLE
windows: cannot use ctrl+click to navigate to ./index.css mentioned in index.tsx (create-react-app with typescript)

### ISSUE THREAD

**Issue by sohrabsaran** [microsoft/vscode#117954] opened 2021-03-02 07:29 UTC
Issue Type: <b>Bug</b>

Run 'npx create-react-app react-typescript-app --template typescript'
Go to index.tsx
Try to navigate to index.css.
Navigation does not work.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (20.51GB free)|
|Process Argv|--crash-reporter-id 14178864-911d-4e17-802b-3a047c0c4788|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
htmlhint|ctf|0.0.1
vscode-eslint|dba|2.1.14
git-extension-pack|don|0.1.3
githistory|don|0.6.14
gitlens|eam|11.2.1
fold-unfold-all-icone|Fer|0.0.3
path-autocomplete|ion|1.17.1
vscode-go-to-file|jac|0.0.1
tws|jki|1.0.1
vscode-peacock|joh|3.9.1
regionfolder|map|1.0.12
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.603412351
back-n-forth|nic|3.1.0
jsdoc-live-preview|Per|2.0.0
vscode-css-peek|pra|4.1.0
vscode-css-navigation|puc|1.10.3
blank-line-organizer|rin|0.1.5
es6-string-html|Tob|2.1.0
errorlens|use|3.2.4
code-navigation|vik|0.2.0
file-size|zh9|1.0.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425

```

</details>

**Comment by mjbvz** [comment] 2021-03-02 16:46
Duplicate of https://github.com/microsoft/TypeScript/issues/41861

**Closed by mjbvz** 2021-03-02 16:46 UTC
