### ISSUE TITLE
Variables starting with "let" or "var" break highlight.

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/vscode#3794] opened 2016-03-08 00:31 UTC
Variable names starting with `let` or `var` when placed after the first parameter break the syntax highlight. Note: I'm in a typescript file.

	var let2 = 0;
	var f = function(a,b,c){};
	f(0,let2,'test');	//breaks
	
	var var2 = 0;
	var f = function(a,b,c){};
	f(0,var2,'test');	//breaks
	
	var function2 = 0;
	var f = function(a,b,c){};
	f(0,function2,'test');	//works
	
renders as

![](http://puu.sh/nyCrO.png)

**Comment by corbinu** [comment] 2016-03-09 10:55
I am seeing the same thing in ES6 template strings such as:
```
let test = {
   "name": `${name.variant}`
});

**Comment by aeschli** [comment] 2016-03-09 11:01
Caused by https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

Will be fixed in the March release.

**Closed by aeschli** 2016-03-09 11:01 UTC
