### ISSUE TITLE
scss syntax highlighting problem

### ISSUE THREAD

**Issue by issam-seghir** [microsoft/vscode#196511] opened 2023-10-24 22:26 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.1
- OS Version: 22H2 19045.3570 windows 10 pro

The syntax highlighting feature is not working for `@inculde`, `@use`, and `@container`, and neither is the new CSS features like custom selectors.
![image](https://github.com/microsoft/vscode/assets/74573675/a8c0d6da-7997-471f-b5df-2db390c3d14d)

![image](https://github.com/microsoft/vscode/assets/74573675/71204ed4-c719-4be4-bd12-5a73d06299e0)

**Comment by alexr00** [comment] 2023-12-07 10:24
@issam-seghir can you share a copy/pastable code snippet I can use to repro the issue?

**Comment by issam-seghir** [comment] 2023-12-07 13:57
```scss
p {
	font-size: $text-lg;
	font-weight: $font-normal;
	line-height: 1.75rem;
	color: $text-primary-200;

	&.tag {
		@include pseudo("", 0.5em, 0, -1.5rem) {
			@include circle(13px);
			background-color: currentcolor;
		}
		width: fit-content;
		margin: 0 auto 3rem;
		font-weight: $font-bold;
		color: $text-secondary-100;
	}
       @include pseudo("", -20%, 0, -20%, 0, "after") {
			@include sizer(calc(100% + 5rem));
					z-index: 1;
					background-image: linear-gradient(rgb(5 3 8 / 0%) 74%, #050308 91%);
	}

	@include sizer(11.375rem);
	
       @container (width < 400px) {
					top: -12.3rem;
				}
}
```

**Comment by alexr00** [comment] 2023-12-11 11:02
`@include` looks ok, but `@container` is not recognized:

<img width="671" alt="image" src="https://github.com/microsoft/vscode/assets/38270282/78b656e1-38e1-483a-b882-cccf11ae2351">

**Comment by issam-seghir** [comment] 2023-12-11 15:47
in my experience is not work for include and mixins , i use the default theme so the theme is not the problem

**Comment by alexr00** [comment] 2023-12-12 08:51
Marking as a duplicate of https://github.com/microsoft/vscode/issues/81038 to be tested again once we find a new scss grammar.

**Closed by alexr00** 2023-12-12 08:51 UTC
Labels: info-needed
