### ISSUE TITLE
SCM badge has no number

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#199392] opened 2023-11-28 16:54 UTC
1. Merge main while on a topic branch
2. Have conflicts and many changes (here I have 125 changes)
3. :bug: SCM view badge is blue with no number

<img width="326" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/07c8f17e-e2c9-4ca0-9240-af467c12cfdc">

**Comment by lszomoru** [comment] 2023-11-28 20:40
Will let @sandy081 chime in on this one.

**Comment by sandy081** [comment] 2023-11-29 09:56
> I think this is as designed, else the badge would have to get too big. Does the tooltip show the actual value?

That's right. Since there is not enough space to render 3 digits, we show a badge without number.

**Comment by lszomoru** [comment] 2023-11-29 10:31
Closing as by design.

**Closed** 2023-11-29 10:31 UTC
Labels: *as-designed
