### ISSUE TITLE
High cpu load with code 1.55, no issue with 1.51

### ISSUE THREAD

**Issue by dingetje** [microsoft/vscode#122988] opened 2021-05-05 08:59 UTC
- VS Code Version: 1.55.2
Also tried code-insiders-1.56.0-1620169491.el8.x86_64.rpm, same result

- OS Version: Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
Linux smt8-01 3.10.0-862.3.2.el7.x86_64 #1 SMP Tue May 15 18:22:15 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. upgrade code from 1.51 to 1.55.2
2. launch code with all extensions disabled

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/609871/117117820-45a0e400-ad90-11eb-935b-97be1e1c2c76.png)

The workspace contains several C++ project, I cannot share. Let me know how I can collect more information.

**Comment by dingetje** [comment] 2021-05-05 09:13
The load is so high that the code GUI is completely unusable. This issue occurs on a Virtual Machine with a single CPU, hosted on a Thinkpad T470 running Win10.

![image](https://user-images.githubusercontent.com/609871/117119808-d7a9ec00-ad92-11eb-8a8a-4feaf62396b7.png)

**Comment by dingetje** [comment] 2021-05-05 09:19
This is the result after launching with 'code --disable-extensions'

![image](https://user-images.githubusercontent.com/609871/117120367-877f5980-ad93-11eb-89f9-bdcefddddc60.png)

The GUI is completely unresponsive and I need to kill -9 the code process.

**Comment by dingetje** [comment] 2021-05-05 09:23
Downgrading to 1.51 resolves the issue.

`sudo yum remove code`
`sudo yum localinstall code-1.51.1-1605051791.el7.x86_64.rpm `

**Comment by deepak1556** [comment] 2021-05-05 12:05
Can you provide the output of `code --verbose`, very likely duplicate of https://github.com/microsoft/vscode/issues/115784. Can you also confirm if you have gcc-5 or higher toolchain installed on your system.

**Comment by dingetje** [comment] 2021-05-05 12:27
I think you are correct. I've followed the instructions at https://github.com/microsoft/vscode/issues/115784#issuecomment-817187000 and now code 1.55 seems to work.

No gcc-5 toolchain installed.

Do you still need the output of `code --verbose`?

**Comment by deepak1556** [comment] 2021-05-06 04:48
Nope all good, thanks for confirming.

/duplicate https://github.com/microsoft/vscode/issues/115784

**Closed by deepak1556** 2021-05-06 04:48 UTC
Labels: needs more info
