### ISSUE TITLE
Various svg icons missing

### ISSUE THREAD

**Issue by tforster** [microsoft/vscode#77007] opened 2019-07-09 17:49 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open VSCode 1.36.0 and a project folder
2. Dirty a file
3. Click Source Control Icon in Activity Bar
4. Rollover "Changes" heading and observe: No icon for "Stage all changes" but the tooltip appears in the correct location and clicking does indeed stage all changes
5. Install AWS Toolkit extension and observe: A gap in the Activity Bar where the icon is supposed to appear. The blank region is clickable and will open the AWS sidebar

Reverted to 1.35.1 and everything worked as expected. Tried 1.37.0 (Insiders) and same problem. Just got promped to upgrade to 1.36.1 and same problem.

Some console errors

```
GET vscode-remote://wsl%2Bubuntu/home/tforster/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-0.2.1/media/aws-logo.svg net::ERR_NOT_IMPLEMENTED
GET vscode-remote://wsl%2Bubuntu/home/tforster/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/extensions/git/resources/icons/dark/open-file-mono.svg net::ERR_NOT_IMPLEMENTED
```

There are numerous other similar errors all related to missing icons. The icons are present in the folders indicated in the error messages.

Does this issue occur when all extensions are disabled?: Hard to tell since this disables the Git provider and AWS extension so StR can't be executed.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18932
Remote OS version: Linux x64 4.19.43-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.19GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/tforster/dev/GeekHacks/Poqueio/Poqueio.wiki --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.43-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|14.47GB (13.84GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|0.2.1
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
plantuml|jeb|2.11.1
docthis|joe|0.7.1
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.17
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|2.4.0
html-css-class-completion|Zig|1.19.0
better-comments|aar|2.0.5
bracket-pair-colorizer|Coe|1.0.61
auto-close-tag|for|0.5.6
vscode-peacock|joh|2.4.0
vscode-docker|ms-|0.6.4
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.8
vscode-remote-extensionpack|ms-|0.15.0
code-settings-sync|Sha|3.3.1

(1 theme extensions excluded)

</details>

**Comment by misolori** [comment] 2019-07-09 22:36
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/687

**Closed by misolori** 2019-07-09 22:36 UTC
Labels: new release
