### ISSUE TITLE
Cannot read property 'onError' of undefined

### ISSUE THREAD

**Issue by ptorres11** [Microsoft/vscode#58789] opened 2018-09-17 08:06 UTC
- VSCode Version: 1.28.0 Insider
- OS Version: Windows 10 Pro

Steps to Reproduce:

I'm trying to publish Dynamics Nav Extension with docker 18.06.1-ce-win73 (19507) and I get this error. This setup was working fine on Friday. Docker status is OK.

**Comment by jsacapdev** [comment] 2018-09-17 09:34
I am getting the same behaviour.

```
Version: 1.28.0-insider (user setup)
Commit: cd9d71a31f731baf17330a84448c3efdeabc873f
Date: 2018-09-17T05:20:06.620Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

I am creating a dotnet core project:
1. mkdir testproj
2. cd testproj
3. dotnet new console
4. open in insiders
5. build in vscode
6. run in vscode

```
Cannot read property 'onError' of undefined
```

csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

</Project>
```

also happens with:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

</Project>

```

**Comment by workmonitored** [comment] 2018-09-17 20:06
I have the same problem. However in my case, vscode - user space disappeared so I had to do a reinstall. I am guessing my overzealous security people are either removing user installed programs on my windows machine.

**Comment by octref** [comment] 2018-09-17 21:08
@ptorres11 By "publish Dynamics Nav Extension", are you publishing a VS Code extension, or are you performing some action with the "Dynamics Nav Extension"? If it's the latter case, please open an issue with "Dynamics Nav Extension".

@workmonitored Did you recently update the install from a system installer to a user install? https://code.visualstudio.com/updates/v1_26#_user-setup-for-windows

**Comment by ptorres11** [comment] 2018-09-17 21:16
Sorry for my explanation. I’m publishing a VSCode extension for Microsoft Dynamics NAV on Docker. I can publish same code on VSCode stable version perfectly. When I try to publish it with Insiders, it throw this error even before ask for credentials

**Comment by octref** [comment] 2018-09-17 21:34
@ptorres11 Just to make sure we are on the same page:
- Are you publishing a **VS Code extension for Dynamics Nav** using https://code.visualstudio.com/docs/extensions/publish-extension?
- Or, are you publishing something using the Dynamics Nav extension?

In the first case, there shouldn't be any difference between stable and insider. In the latter case, you should open issues for the extensions for the packages you are using. This seems to be the one: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by jtsom** [comment] 2018-09-18 00:09
Seeing a similar issue just trying to run and debug a C# app: #58847

**Comment by ptorres11** [comment] 2018-09-18 08:11
@octref Got it, for me it's the second case. But it seems there are some user with similar issue, so I'm not sure because extension with same version works fine with stable VSCode.

**Comment by octref** [comment] 2018-09-18 17:05
Marking as duplicate of #58847. You can also try to report this issue to the extension you are using.

**Closed by octref** 2018-09-18 17:05 UTC
Labels: needs more info

**Comment by ptorres11** [comment] 2018-09-19 13:52
Solved on latest update
