### ISSUE TITLE
Diff viewer does not recognize indentation if that's the only change

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode#146833] opened 2022-04-04 16:56 UTC
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

The diff viewer (that you can get to from the Source Control tab on the sidebar) does not recognize indentation as a change. Thus:
1. Lines that have only changed indent levels are not shown as having changed.
2. "Stage Selected Ranges" thus results in broken code, because it will not see these changes.

## Steps to reproduce:

1. Create a python file with the following code:
```
x = 5
```
2. Commit the new file.
3. Add an if statement so that the file looks like this:
```
if True:
    x = 5
```
4. Look at the diff viewer. `if True:` is highlighted, but `x = 5` is not. Select the two lines on the right pane, right-click, and choose "Stage Selected Ranges"
5. Look at the diff for the staged change. You'll see:
```
if True:
x = 5
```
(Which will not run, of course.)

5. Unstage the changes, go back to the original file, and change `5` to `7`. Now the diff viewer recognizes the change to the numeral and also the indentation, so "Stage Selected Ranges" works.

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: true
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.4.0-104-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3450)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|62.79GB (40.48GB free)|
|Process Argv|--unity-launch --crash-reporter-id 38ca9e16-da98-40ee-9bd0-3e01a29abbc8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by alexdima** [comment] 2022-04-05 18:09
This is controlled by a setting called `diffEditor.ignoreTrimWhitespace`. You can set that to `false` to get the behavior you desire. Also, you can press this button in the top right corner of a diff editor:
<img width="37" alt="image" src="https://user-images.githubusercontent.com/5047891/161821760-fc9e7335-b987-44cf-a612-f1606848774f.png">

**Comment by shaperilio** [comment] 2022-04-05 20:11
Thanks @alexdima - you don't think this is a bug if a setting on a diff breaks code? Particularly now that the ticket has been moved to vscode-python?

**Comment by alexdima** [comment] 2022-04-05 20:27
@shaperilio The setting `diffEditor.ignoreTrimWhitespace` influences the way in which differences between two files is displayed. It does not affect per se the contents of the files. So the setting itself is not causing any code breakage. 

But I think your point is that indentation plays a critical role in python and VS Code users should not ignore trim whitespace when diffing python? I agree with you, but we still allow users who want to ignore trim whitespace to ignore it. It is the same principle we use when allowing users to type in the editor illegal programs, the tool respects what the user wants to do.

**Comment by shaperilio** [comment] 2022-04-05 21:49
I guess my point is that it's not just "influencing the way the differences are displayed", because staging a range of lines that includes an indentation change fails to include the change in indentation **but only if that's the only difference in that line**.

In Python, spaces on the left are always important; I think the diff tool should be aware that users may want to ignore white space differences unless they are actually indentation differences (and thus they affect the code).

I cannot imagine, for example, a C diff tool having an option to ignore curly braces.

**Comment by hello-smile6** [comment] 2022-04-05 21:55
Ignoring indentation would also be an issue for neofetch, as logos could be accidentally indented.

**Comment by alexdima** [comment] 2022-04-05 22:14
I see. The ask is that "Stage selected ranges" should stage the shown text, not the rendered diff (which is a presentation and is influenced by `diffEditor.ignoreTrimWhitespace`).

**Comment by shaperilio** [comment] 2022-04-05 22:23
Yes. I think staging something different than is shown is not great either, so I also think `diffEditor.ignoreTrimWhitespace` should be aware that indentation whitespace in Python should never be ignored.

**Comment by joaomoreno** [comment] 2022-04-07 12:21
This is very tricky. When git was extracted to an extension it was forced to only have access to what the diff decorations reports. So, git itself doesn't run any diff algorithm. Rather it just gets those diffs from the UI and works with them.

@alexdima We'd need to have `diffEditor.ignoreTrimWhitespace` as a pure view thing only, but still have the underlying model of diffs contain all changes with whitespace, so git would have access to them. Any thoughts?

**Comment by joaomoreno** [comment] 2022-04-07 12:22
Duplicate of #63397, but feel free to comment here @alexdima

**Closed by joaomoreno** 2022-04-07 12:22 UTC
Labels: git, under-discussion
