### ISSUE TITLE
cannot read property 'trim' of null 

### ISSUE THREAD

**Issue by jianh1994** [microsoft/vscode#73870] opened 2019-05-17 08:26 UTC
Issue Type: <b>Bug</b>

vscode remote-ssh ，when  press 'F5', there are a error 'cannot read property 'trim' of null 

VS Code version: Code - Insiders 1.35.0-insider (a69d0f8b218498e22b7c3a0f76926cc6322e6106, 2019-05-17T05:18:13.839Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-142-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: myServer|
|OS|Linux x64 4.4.0-142-generic|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 3799)|
|Memory (System)|31.29GB (6.90GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|7.0.0
vscode-filesize|mkx|2.1.2
python|ms-|2019.4.12954
vscode-yaml|red|0.4.0
markdown-preview-enhanced|shd|0.3.13
guides|spy|0.9.3
bracket-pair-colorizer|Coe|1.0.61
vscode-language-pack-zh-hans|MS-|1.34.2
anaconda-extension-pack|ms-|1.0.1
remote-containers|ms-|0.53.0
remote-ssh|ms-|0.37.0
remote-ssh-edit|ms-|0.37.0
remote-ssh-explorer|ms-|0.37.0
remote-wsl|ms-|0.35.0
vscode-remote-extensionpack|ms-|0.14.0

(1 theme extensions excluded)

</details>

**Comment by Thitho007** [comment] 2019-05-17 09:43
Same error with Extension: Remote - WSL
Version: 1.35.0-insider (user setup)
Commit: a69d0f8b218498e22b7c3a0f76926cc6322e6106
Date: 2019-05-17T05:18:13.839Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Last update breaks something when start Debugging by pressing 'F5' key

**Comment by chihuai** [comment] 2019-05-17 10:05
Same error with Extension: Remote - WSL

Version: 1.35.0-insider (user setup)
Commit: a69d0f8b218498e22b7c3a0f76926cc6322e6106
Date: 2019-05-17T05:18:13.839Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by bcxpro** [comment] 2019-05-17 10:24
Same error with Extension: Remote - SSH
Trying to debug in python.

Version: 1.35.0-insider (user setup)
Commit: a69d0f8b218498e22b7c3a0f76926cc6322e6106
Date: 2019-05-17T05:18:13.839Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by serioustk** [comment] 2019-05-17 13:35
Same error with Extension: Remote - Container
Trying to debug in python.

Version: 1.35.0-insider (user setup)
Commit: a69d0f8b218498e22b7c3a0f76926cc6322e6106
Datum: 2019-05-17T05:18:13.839Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17763

**Comment by bcxpro** [comment] 2019-05-17 15:41
Duplicate of #73867

**Closed** 2019-05-20 07:13 UTC
Labels: *duplicate
