### ISSUE TITLE
`focusedView` gets stuck on `workbench.view.search` when search is not open or focused

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#195270] opened 2023-10-10 16:20 UTC
Type: <b>Bug</b>

When the search view is the last focused view the side bar and the sidebar is toggled closed `focusView` is left set to `workbench.view.search` which breaks keybindings.

Steps to reproduce:
* Press `Ctrl+Shift+F` to open the serach view
* Press `Ctrl+B` to toggle the side bar
* Inspect context keys
* Notice `focusedView == "workbench.view.search"`

Expected outcome
* `focusedView == ""`

In this gif I first show the `Alt+B` works to toggle editor maximized state, which relies on `focusedView` not being set. Then I toggle the sidebar with the search view active. Then I attempt to use `Alt+B` again and it no longer works.

![focusedView Bug](https://github.com/microsoft/vscode/assets/484784/e8edcb49-8168-47d3-8c74-4c17f65d560c)

One workaround is to toggle the panel to force `focusedView` to update.

VS Code version: Code - Insiders 1.84.0-insider (55d1cfea45b665bb54e46d11bd3ccddf9e66108b, 2023-10-09T06:11:57.204Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper PRO 3945WX 12-Cores      (24 x 3993)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.86GB (24.53GB free)|
|Process Argv|--crash-reporter-id 2860e056-a3df-4573-a10a-18ca229997c6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv1:30786205
pythonmypywwcf:30841057
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiagcf:30842813
pythonmypyd1cf:30850306
pythoncet0cf:30848248

```

</details>

**Comment by andreamah** [comment] 2023-10-23 23:39
Hmm, I can't seem to repro this on my machine. Do you have any other keybindings that may be contributing `alt+b`? I tried to repro by checking context keys (focusedView was properly unset when search was closed) and also setting an action to run on empty context (which worked once I closed the search view).

**Comment by akbyrd** [comment] 2023-10-24 04:06
I'm unable to repro after updating Insiders to 2f32f0edae007ddd03699c325a451184c4c5e89b. Looks like some snuck a fix in already :)

**Comment by akbyrd** [comment] 2024-04-25 05:44
I'd like to bump this issue if at all possible. This is a significant workflow impediment that occurs multiple times a day for me. Keybindings are based on context and broken keybindings are a major issue, imo. Jiggling panels until things start working again can be highly frustrating.

The default bindings don't use `focusedView` in a way that is likely to be problematic, but for users with custom keybindings this is an important context key. I have 20 keybindings that use it.

**Comment by osortega** [comment] 2024-12-18 19:47
I'm not able to reproduce this anymore, given that the issue is pretty old I will be closing it.
https://github.com/user-attachments/assets/3ffe1605-908c-4e1a-829d-68c7d6033146

Please feel free to reopen and ping me if you are still having problems

**Closed by osortega** 2024-12-18 19:47 UTC
Labels: bug, search, confirmed
