### ISSUE TITLE
sftp  bug

### ISSUE THREAD

**Issue by swarmchen** [Microsoft/vscode#51317] opened 2018-06-07 08:36 UTC
Issue Type: <b>Bug</b>

bug
![image](https://user-images.githubusercontent.com/14236693/41087975-d3301ab8-6a70-11e8-9744-393c6e53a57b.png)

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.22GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
cssrem|cip|0.0.3
vscode-eslint|dba|1.4.12
vue-snippets|hol|0.1.7
beautify|Hoo|1.3.0
sftp|lix|1.1.11
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
vscode-language-pack-zh-hans|MS-|1.24.3
mssql|ms-|1.3.1
python|ms-|2018.5.0
Go|ms-|0.6.82
sublime-keybindings|ms-|4.0.0
php-docblocker|nei|1.6.0
vetur|oct|0.12.5
vscode-icons|rob|7.23.0
ftp-kr|rua|1.3.16
vue-vscode-snippets|sdr|1.3.0
markdown-preview-enhanced|shd|0.3.5
python|tht|0.2.3

(7 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2018-06-07 12:05
duplicate of #51289

**Closed by aeschli** 2018-06-07 12:05 UTC
Labels: new release
