### ISSUE TITLE
`editorScroll` command speed differs from `to:up` and `to:down` with `editor.smoothScrolling`

### ISSUE THREAD

**Issue by daninsky1** [microsoft/vscode#128956] opened 2021-07-18 17:42 UTC
Issue Type: <b>Bug</b>

The user defined keybiding editorScroll command with arg property  "' to': 'up'" repeats slower than "'to':'down'". The key combination doesn't seems to have influence.
[edit]
I tested it further, and found what triggers this behavior is the conjunction of this keybinding with the setting smooth scrolling :
"editor.smoothScrolling": true,
Windows and Linux versions have the same behavior.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3398)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|14.60GB (9.04GB free)|
|Process Argv|--unity-launch --crash-reporter-id a2f61383-00ae-43db-bb37-ddaf37ddfcf3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
vscode-language-babel|mgm|0.0.31
cpptools|ms-|1.5.1
LiveServer|rit|5.6.1
ninja|sur|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by alexdima** [comment] 2021-08-17 13:24
@daninsky1 I could not reproduce. I tried with the following keybindings:
```
{ "key": "alt+up", "command": "editorScroll", "args": {"to": "up","by": "line"} },
{ "key": "alt+down", "command": "editorScroll", "args": {"to": "down","by": "line"} },
```
The scroll speed appears similar to me for both keybindings.

**Comment by daninsky1** [comment] 2021-08-17 21:20
> @daninsky1 I could not reproduce. I tried with the following keybindings:
> 
> ```
> { "key": "alt+up", "command": "editorScroll", "args": {"to": "up","by": "line"} },
> { "key": "alt+down", "command": "editorScroll", "args": {"to": "down","by": "line"} },
> ```
> 
> The scroll speed appears similar to me for both keybindings.

I tested it further, and found what triggers this behavior is the conjunction of this keybinding with the setting smooth scrolling :
`"editor.smoothScrolling": true,`
Windows and Linux versions have the same behavior.

**Comment by alexdima** [comment] 2021-08-23 10:44
I can reproduce a slowdown. On my macOS computer, scrolling down went 114 lines down in 10s, while scrolling up went 100 lines up in 10s.

**Comment by ygoe** [comment] 2021-09-27 16:51
Not sure if my case is special. My issue was closed as duplicate of this one. Windows 10 here. On two completely different and unrelated machines but with the same VSCode user configuration.

Scrolling down a document of 114 lines: 4.5 seconds
Scrolling up again: 13 seconds

This is a major slowdown by the factor 3!

**Closed** 2022-12-11 21:51 UTC
Labels: bug, editor-scrollbar
