### ISSUE TITLE
Duplicate suggestions (Python) 

### ISSUE THREAD

**Issue by vistatest** [microsoft/vscode#74651] opened 2019-05-31 01:38 UTC
1. Using VSCode with IntelliSense, Python language server and pyright extensions.
2. Seeing most entries in auto-completion suggestions duplicate.

I saw comments in similar issues in the past that this is by design, extensions should cooperate, etc.

Could VSCode just apply unique to the list of suggestions? I.e., after all extensions gave their suggestions, remove duplicates from the final list.
If duplicates differ only by extra information provided when (i) in a circle is clicked,
please, generate a single suggestion with several informational (i) on the same line.

**Comment by jrieken** [comment] 2019-05-31 16:57
/duplicate of https://github.com/microsoft/vscode/issues/45864

**Closed** 2019-05-31 16:57 UTC
Labels: *duplicate, suggest

**Comment by vistatest** [comment] 2019-05-31 17:10
This issues is mis-labeled - it should be labeled as a bug and not as a suggestion.
