### ISSUE TITLE
VSCode 1.8.1. HTML bad automatic identation

### ISSUE THREAD

**Issue by pedrojfpereira** [Microsoft/vscode#18739] opened 2017-01-18 15:06 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. VSCODE 1.8.1 is making bad automatic HTML code identation
2. VSCODE 1.7.1 had better automatic HTML code indentation

**Comment by schmuli** [comment] 2017-01-18 15:31
This is probably because of js-beautify: beautify-web/js-beautify#1103

**Comment by mjbvz** [comment] 2017-01-19 02:32
@pauloppenheim  Can you please provide some example code that show this problem? Also, please try running VSCode with `--disable-extensions` to make sure an extension is not the root cause

Thanks

**Comment by aeschli** [comment] 2017-01-19 15:57
likely a duplicate of #17849.
@pauloppenheim Do you have any style or event handler attributes?

**Comment by aeschli** [comment] 2017-01-30 15:32
Closing due to lack of more information. Please have a look at the latest [insiders](https://code.visualstudio.com/insiders) where #17849 is fixed and where jsbeautify has been updated.

**Closed by aeschli** 2017-01-30 15:32 UTC
Labels: html, needs more info

**Comment by HookyQR** [comment] 2017-02-10 22:35
This is a legit issue. See the link provided by @schmuli. It's a js-beautify bug. I've submitted a PR to fix it, but (once it's accepted) VS Code will need to apply the fix to the included module. (Under the html language server)

**Comment by HookyQR** [comment] 2017-02-10 22:58
I've implemented the fix directly in [beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify). So if you want proper formatting first, install or upgrade that extension.
