### ISSUE TITLE
Visual Studio Code always opens Powershell by default regardless of default profile setting

### ISSUE THREAD

**Issue by jakewaxman** [microsoft/vscode#132506] opened 2021-09-07 02:46 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60
- OS Version: Window 10

Steps to Reproduce:

1. Install fresh copy of VS Code
2. Start VS Code
3. Terminal/New Terminal
4. Down Arrow in Terminal pane / Select Default Profile / Git Bash (or anything else)
4. Close VS Code
5. Start VS Code
6. Powershell opens in terminal pane
7. Check Down Arrow in Terminal pan Git Bash is labelled default
![2021-09-06 22_45_42-Greenshot](https://user-images.githubusercontent.com/233683/132276403-6caa38b4-cf55-4c1c-a064-a15104de3fea.png)

**Comment by akbaryahya** [comment] 2021-09-07 04:22
It also happened in 1.61.0, we want to use git because we want to run bash,sh script : /

**Comment by gjsjohnmurray** [comment] 2021-09-07 04:41
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-07 04:42 UTC
Labels: *duplicate
