### ISSUE TITLE
open on files opened by vscode causes "Operation not permitted" in files VScode isn't using, closing vscode fixes it

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#73947] opened 2019-05-18 19:53 UTC
Issue Type: <b>Bug</b>

## To reproduce:

Open vscode on a folder.

Attempt to use the filesywtem call 'open' on a file in that folder, while vscode is running

## What happens:

A bunch of warnings and failures, until vscode is terminated and the problem goes away

![image](https://user-images.githubusercontent.com/172594/57974384-01ec1e80-79af-11e9-91d4-6748a50f8b9f.png)

## What should happen:

vscode should not affect opening files, particularly files that are not being edited.

## Details

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18898

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (8.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
prettier-vscode|esb|1.9.0
svelte-vscode|Jam|0.9.1
powershell|ms-|1.12.1
vscode-typescript-tslint-plugin|ms-|1.0.0

</details>

**Comment by mikemaccana** [comment] 2019-05-18 19:59
@vscodebot you're wrong as usual, this is nothing to do with the integrate terminal.

**Comment by mjbvz** [comment] 2019-05-21 17:52
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mikemaccana** [comment] 2019-05-24 15:14
I did try, but wasn't able to reproduce on Insiders. Happy to close until / if it coms up again. 

Does this issue sound like something that has been fixed?

**Comment by mjbvz** [comment] 2019-05-24 23:31
Likely duplicate of https://github.com/microsoft/TypeScript/issues/29407

**Closed** 2019-05-24 23:30 UTC
Labels: needs more info
