### ISSUE TITLE
Intellisense doesn't work immediately for new .js file added via File -> New File (or Ctrl + N) but does for files added via Explorer

### ISSUE THREAD

**Issue by sophistyx** [Microsoft/vscode#13135] opened 2016-10-02 16:38 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. Install the Node typings for the current project
2. Create new JavaScript file (foo.js) by clicking on the New File button in Explorer
3. Enter the code  - var http = require('http) and then http.   (note the intellisense works correctly.
4. Create another new JavaScript file (bar.js) using the File -> New File (or Ctrl + N) option
5. Repeat step 2. above.  There is no intellisense.
6. Close and then reopen bar.js.  Intellisense now works for bar.js

**Comment by waderyan** [comment] 2016-10-03 21:35
@sophistyx thank you for opening this issue. I have recreated this on my machine following the steps provided. 

@dbaeumer what are your thoughts? Is there a unique action with New File that TS Server isn't picking up or possibly we're not sending it to them.

**Comment by dbaeumer** [comment] 2016-10-04 10:12
@waderyan  There is nothing special. What would help is enabling tracing to see if we sent a correct open notitfication to the tsserver. If we do there is not reason why code complete shouldn't work.

**Comment by waderyan** [comment] 2016-10-06 13:37
Steps from #13190 as reported by @alanwei0 and seconded by @russpenska. 

1. create a new file
2. set language mode to 'javascript' and save with a name, 'untitle-1.js'
3. input some word, for example: 'webso', there's no suggestion list shown. 
4. close the file and reopen it, input 'webso' again, suggestion is shown, over.
5. i can reproduce it every time.

<img width="336" alt="screen shot 2016-10-04 at 2 43 56 pm" src="https://cloud.githubusercontent.com/assets/3991105/19064628/0d163e36-8a41-11e6-9aa1-6d9b1da7d0d2.png">

Here is my recreation of this on Mac with Insiders 1.6.

![intellisensenotlightingup](https://cloud.githubusercontent.com/assets/2449568/19154421/51eda3ce-8b8f-11e6-8174-5ad7b1a628b2.gif)

Notice, that with tracing enabled I see nothing lighting up in for the TS server until after I save the file.

**Comment by dbaeumer** [comment] 2016-10-07 08:55
@waderyan this is a know issue we can't solve. The tsserver doesn't handle in memory buffers. For it to work the file must exist on disk and have the proper extension. So before we can address this TS has to address the buffer issue which they are aware of. The lack of the buffer support is also the reason why we don't have JS code complete in HTML anymore :-)

**Comment by waderyan** [comment] 2016-10-10 15:57
@mhegazy do you have an open issue to address the above? I can close this issue and reference this issue in the open issue if you do. 

I did a quick search but could not find anything.

**Comment by mhegazy** [comment] 2016-10-10 20:22
@dbaeumer we believe it should be working correctly in `typescript@insiders`. The [`openRequest` command](https://github.com/Microsoft/TypeScript/blob/ea56522f80605048bce31004a1bcb770613b2402/src/server/protocol.d.ts#L667-L678) accepts an optional `fileContent`, that you can pass through, along with the scriptKind.

As for the HTML mapped buffers. this should be supported using the same command. you will need to send the server the contents of the script blocks after stripping out HTML tags, and set the scriptKind to `JS`.

If you run into problems please let us know and we can investigate more.

**Comment by dbaeumer** [comment] 2016-10-11 08:00
@mhegazy we sent the fileContent since the property is available to the tsserver (I guess that was around 1.8.x). Do you mean with typescript@insiders the 2.0.6 or the 2.1 branch.

**Comment by mhegazy** [comment] 2016-10-11 15:34
I mean 2.0.6.

**Comment by dbaeumer** [comment] 2016-10-12 09:06
@mhegazy but how should this work then. The protocol defines the OpenRequestArgs as FileRequestArgs which have a required property `file: string;`. Is this property not needed anymore. From my understanding this value is used in many maps in the server to find the file again. And in the case of a buffered file we don't have a file name. Should we randomly generate one?

**Comment by mhegazy** [comment] 2016-10-12 17:27
We use the file extension to determine the scriptKind, if you specify one in the request, it will be used instead. as for the file name, i am assuming you have some name for this buffer, be it a guid, or some temp file location.

**Comment by dbaeumer** [comment] 2016-10-13 10:09
We have a URI. Will that work. I know that the tsserver uses a lot of path.* function on the filename and I am not sure what the result is if I pass in a URI.

**Comment by mhegazy** [comment] 2016-10-17 16:57
should work as well. if not it is a bug that we need to fix.

**Comment by dbaeumer** [comment] 2016-10-17 18:44
@mhegazy great. Will look into this in November.

**Comment by dbaeumer** [comment] 2017-01-23 20:21
@mjbvz assigning to you. I know you started work on this.

**Comment by mjbvz** [comment] 2017-02-01 21:50
This should be fixed in 1.9 since we now support intellisense for untitled ts and js files. Please give it a try and let me know if you still see issues around this scenario.

**Closed by mjbvz** 2017-02-01 21:50 UTC
Labels: intellisense, javascript
