### ISSUE TITLE
Provide a way to dismiss notification messages programmatically

### ISSUE THREAD

**Issue by cait1inhennessy** [microsoft/vscode#50232] opened 2018-05-21 16:37 UTC
In the Live Share extension for VSCode, we notify the host when someone requests to join the collaboration session:
![capture](https://user-images.githubusercontent.com/16658549/40318330-150c2738-5cd9-11e8-9a57-1e7c6e5254a8.PNG)
If the joiner cancels their request before the host has responded, we would like to remove the notification on the host's side.  For it to remain visible is misleading, because if the host clicks either button, nothing will happen.  Could you provide a close method that would allow us to remove the notification message?

Corresponding Live Share bug: [https://github.com/MicrosoftDocs/live-share/issues/439](url)

**Comment by eamodio** [comment] 2018-06-02 15:01
Duplicate of https://github.com/Microsoft/vscode/issues/48960

**Closed** 2020-03-16 00:43 UTC
Labels: api, feature-request, workbench-notifications
