### ISSUE TITLE
Poor performance on large resolution

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#9432] opened 2016-07-18 10:40 UTC
Version: VSCode Insiders.
Latest OS X

I have a secondary monitor plugged into my MacBook pro which has 3840 x 2160 pixels. I have my resolution set to 2560 x 1440.

When I resize vscode to use the full size of the screen, there is about ~300ms - ~500ms of lag when editing a medium size file (~300 LOC in a TypeScript file). I haven't tried to compare this performance with smaller and larger files, however I have noticed that editing an empty file is much faster.

I'm not sure how I can provide more information, but do let me know if you need anything else.

**Comment by jayphelps** [comment] 2016-07-28 19:46
On my 4K, 3840x2160 monitor when the window is full width/height:

* Start up until able to type in new file: about 8 seconds.
* New file is about 1 sec.
* Typing has a noticeable lag, but less than a 1 sec.

For comparison, Sublime 3 takes less than 1 sec to start, new files are near instant, no discernible typing lag.

**Comment by jayphelps** [comment] 2016-07-28 20:03
Because my timings were just guesses, I recorded a bunch of Timeline profiles for you to get more accurate info from.

I'm not sure if it's possible to record a Timeline of the entire start up process. The closest thing I can think of is just using ⌘+R inside the Timeline, which seemingly does a soft refresh.

I've recorded that along with creating a new file and typing. 

[timelines.zip](https://github.com/Microsoft/vscode/files/389245/timelines.zip)

**Comment by bpasero** [comment] 2016-08-05 15:24
@OliverJAsh maybe you could also attach some profile traces?

**Comment by OliverJAsh** [comment] 2016-08-05 15:33
Sure, I would be happy to help! Do you mean a timeline recording? How do I
do that?

**Comment by bpasero** [comment] 2016-08-08 15:18
Profile would be great:

![image](https://cloud.githubusercontent.com/assets/900690/17484833/0e561d66-5d8c-11e6-8058-f810faca53b9.png)

**Comment by OliverJAsh** [comment] 2016-08-08 15:26
I'm not quite sure how to open the dev tools from within the app? I'm not running Electron?

**Comment by bpasero** [comment] 2016-08-08 15:38
@OliverJAsh Help > Toggle Developer Tools should do it 👍

**Comment by OliverJAsh** [comment] 2016-08-11 13:48
@bpasero Here's the CPU profile you requested, hope it helps :-) Anything else I can do to help? I would love to help fix this [CPU-20160811T144733.cpuprofile.zip](https://github.com/Microsoft/vscode/files/413347/CPU-20160811T144733.cpuprofile.zip)

**Comment by bpasero** [comment] 2016-08-11 13:54
Thanks for the trace, I do not see anything suspicious though, so the time is not spend in any of our code it seems, rather likely in the rendering in Chrome.

**Comment by OliverJAsh** [comment] 2016-08-11 14:00
That makes sense! Do you think there's room for further rendering optimisations? I'm sure you've done a bunch already.

**Comment by bpasero** [comment] 2016-08-11 14:01
I would first try to see how it works when we update to a newer electron version that comes with Chrome 52 (we are now on 49). That might have an impact. In the end this is an upstream issue so we can only fix it by updating our upstream versions which is planned for this milestone but has a risk of being pushed out to September.

**Comment by bpasero** [comment] 2016-08-11 14:02
@OliverJAsh @jayphelps to clarify, this is with a beta of Mac OS Sierra right?

**Comment by OliverJAsh** [comment] 2016-08-11 14:35
10.11.6 (15G31) for me

**Comment by bpasero** [comment] 2016-08-11 14:42
@OliverJAsh @jayphelps can you see if this also happens with Atom? does it make a difference if you change the resolution of your monitor? does it only reproduce when the width/height of Code is exactly full dimensions of the monitor?

@alexandrudima fyi if you ever heard about this before: typing (or all UI operations) get slow when opening Code on a 4k monitor in full width/height (timeline attached in https://github.com/Microsoft/vscode/issues/9432#issuecomment-236008594).

**Comment by bpasero** [comment] 2016-08-11 14:46
Looks like a known issue in Atom land at least: https://github.com/atom/atom/issues/10518, https://github.com/atom/atom/issues/9561, https://github.com/atom/atom/issues/9724, https://github.com/atom/atom/issues/10644, https://github.com/atom/atom/issues/10750

I am afraid this is not in our hands to fix and really upstream.

**Comment by bpasero** [comment] 2016-09-04 08:57
What seems to help people is to run `code --ignore-gpu-blacklist --disable-gpu-sandbox`

**Comment by bpasero** [comment] 2016-09-14 10:06
@OliverJAsh @jayphelps  we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment] 2016-09-28 09:28
Please reopen if this still happens with our 1.6.0 release.

**Comment by OliverJAsh** [comment] 2016-10-06 14:30
@bpasero Unfortunately I don't see much of an improvement in 1.6.0 (Code Insiders), nor when I'm running `--ignore-gpu-blacklist --disable-gpu-sandbox`. 😒 

Quite difficult to measure the delay here, so I could be wrong, but that's my perception.

**Comment by bpasero** [comment] 2016-10-06 14:32
Sure, we can reopen this.

**Comment by bpasero** [comment] 2016-11-17 08:46
@OliverJAsh we just updated Electron again, was wondering if that helps you: http://code.visualstudio.com/Download#insiders

**Comment by OliverJAsh** [comment] 2016-11-17 09:34
Should I try the latest Insider version?

**Comment by bpasero** [comment] 2016-11-17 11:42
@OliverJAsh yes, it includes a Chrome 53 (from 52) and maybe we are lucky.

**Comment by bpasero** [comment] 2016-11-22 07:12
@OliverJAsh ping

**Comment by OliverJAsh** [comment] 2016-12-15 15:12
Just tested 1.8 and it seems much faster!

**Comment by bpasero** [comment] 2016-12-15 15:15
Good enough to close this?

**Comment by OliverJAsh** [comment] 2016-12-15 15:22
Can we get a second opinion? @jayphelps, perhaps you could give this a test?

**Comment by sampattuzzi** [comment] 2017-03-02 15:44
I seem to be getting slow performance when the window is larger than 1080p. This is on version 1.10

**Comment by sampattuzzi** [comment] 2017-03-02 16:19
Just tried out 1.11 insiders build. Performance trace doesn't seem to be showing anything particularly slow.

**Comment by bpasero** [comment] 2017-04-10 17:09
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by cchamberlain** [comment] 2017-07-31 21:40
![image](https://user-images.githubusercontent.com/424694/28799474-8af107c0-75fd-11e7-8337-8ef0d240aa99.png)

Pretty slow for me on latest insider build (Windows 10) when on high resolution monitors. Running three 1920x1080 monitors at home and two 2560x1440 monitors at work all attached to the same 4k ThinkPad. At home everything is fast. At work, things seem very noticeably slower. Same exact laptop / docking station (model) so feel its a pretty useful test bed if you have anything I should try.

**Comment by norbertes** [comment] 2017-09-08 15:03
@bpasero I had this issue in 1.15 (4k res), just updated to 1.16 and everything works great!

**Comment by biscoe916** [comment] 2017-10-17 15:58
This seems to have gotten worse for me in 1.17. Interestingly, when I switch to max resolution (3840x2160) it seems to be fine, but in the resolution I prefer using (3360 x 1890), it's noticeably laggy. Scroll performance is quite poor, and dragging text selection has a very noticeable delay. 

<img width="274" alt="screen shot 2017-10-17 at 11 55 27 am" src="https://user-images.githubusercontent.com/1865343/31675279-234ec46e-b332-11e7-8c8d-b8ae19173aab.png">
<img width="550" alt="screen shot 2017-10-17 at 11 55 35 am" src="https://user-images.githubusercontent.com/1865343/31675283-25417604-b332-11e7-93b1-6e4a38a14e6f.png">

**Comment by thunderball1** [comment] 2017-10-24 10:19
+1

**Comment by bpasero** [comment] 2017-11-15 14:44
Still happening?

**Comment by barodeur** [comment] 2017-11-24 19:30
I had the same problem with a 4k screen and using a 2560 x 1440 resolution.

<img width="599" alt="u28e590" src="https://user-images.githubusercontent.com/303170/33222228-b7e4f724-d123-11e7-80a8-40381f25530f.png">

I'm using a Nvidia GTX 1080.

**The solution for me was to disable the GPU for code.**

```
code --disable-gpu
```

It's super fluid now.

**Comment by wolfhoundjesse** [comment] 2017-11-28 16:44
@barodeur Your solution didn't work for me. I'm scaling with xrandr to non hiDpi monitors, and it's a disaster. Works lovely on my 15" 4k laptop screen, though.

**Comment by esetnik** [comment] 2017-11-28 18:01
@barodeur I have the same configuration and experiencing the same issue. Using `--disable-gpu` causes the editor flashes and graphical glitches on `1.18.1` but works great on `1.19.0-insider`.

**Comment by dtgriscom** [comment] 2018-01-30 21:58
I'm seeing this with VSC 1.19.3 (1.19.3) on OS X 10.10.5 on a Macbook Pro 15" Retina, driving two external displays. The larger one (where I run VSC in full-screen mode) is a 3840x2160 display, scaled to 3008x1692 (to keep the text from looking like microfiche). From time to time rectangular areas around the insertion point seem to flash in time with the insertion point. Running with --disable-gpu makes it significantly worse. Happy to provide other information upon request.

**Comment by Cryrivers** [comment] 2018-02-04 14:56
`--disable-gpu` makes it better to me. Not sure if it can be set in `User Settings`.

**Comment by mloskot** [comment] 2018-02-27 21:56
This may be multiplatform issue as I'm observing the same problem on Windows 10 (see https://github.com/Microsoft/vscode/issues/26398#issuecomment-369039977) and `--disable-gpu` solves the problem for me (as per https://github.com/Microsoft/vscode/issues/9432#issuecomment-362912516).

**Comment by wooliet** [comment] 2018-03-20 17:39
macOs 10.13.3
monitor 3840 x 2160

Changed scaling from medium (larger font) to maximum (native resolution) and the issue seems to be resolved.

**Comment by Cryrivers** [comment] 2018-03-24 02:38
I'm feeling the performance issue on OS X is caused by High Sierra. Just downgrade to Sierra (10.12.6), everything is working smoothly again.

**Comment by pete-otaqui** [comment] 2018-06-06 18:31
I have found (using a 2017 MacBook Pro running High Sierra with only an external 4k monitor active) that setting the resolution to "best for display", and then a few levels of "zoom out" (Cmd and -) in VS Code ends with the same effective font-size in Code* combined with buttery-smooth performance.  As good as I get with SublimeText (which isn't as feature-rich as Code these days!) at normal zoom and a "more space" display setting.

Obviously everything other than Code seems relatively huge with this setup, but overall I find it works really well for a code-focused session on the computer.

* the font-size I'm after allows: space for three editor panel columns (comfortably showing 80-chars and the minimap) and the left-hand explorer / search / etc panel.

**Comment by Cryrivers** [comment] 2018-06-07 10:06
I feel it is a problem of macOS High Sierra. I've downgraded to Sierra and it runs smoothly with 4K monitors now.

**Comment by scottmas** [comment] 2018-12-29 05:17
I can confirm Wooliet's workaround. The issue seems to occur on OSX when using non-native resolutions where (presumably) the gpu has to do lots of calculations on the fly to downsample everything.

**Comment by ravtakhar** [comment] 2019-03-13 17:19
Running a Dell XPS with a 4k panel and can confirm this is an issue for me as well. Tried all the workarounds presented on this thread and still not getting proper performance.

Scrolling anywhere is choppy and there is noticeable input lag.

**Comment by ravtakhar** [comment] 2019-03-14 00:16
Just installed the latest update, and wow... VS Code is suddenly flying for me. I've never had this smooth of an experience on my laptop. Something else may have triggered a fix?

**Comment by gregtandiono** [comment] 2019-06-16 09:18
> Just installed the latest update, and wow... VS Code is suddenly flying for me. I've never had this smooth of an experience on my laptop. Something else may have triggered a fix?
> 
> EDIT: I've had this issue for 2 years. :(

I'm on an XPS 15 4K, and I'm still suffering from the lag issue with the latest VSCode :(

**Comment by AmirHosseinHmd** [comment] 2019-06-16 20:44
Non-responsible developers that don't care enough about the users having serious problems with the user interface, which is one of the most important aspects of the application.
I'm on a Windows 10 machine (ASUS ZenBook UX510UW) with a 4K display, I have the exact same problem and I posted another issue about it, but no one seems to care...
It's been 3 years, and no one paid any serious attention to this problem and did anything to help fix it. Why?!?!

**Comment by ravtakhar** [comment] 2019-06-16 20:52
Still an issue for me as well. I gave up and stick coding on my desktop as the laptop experience is just too sub-par.  If I HAVE to code on my laptop I end up using Sublime.

**Comment by AmirHosseinHmd** [comment] 2019-06-16 20:54
My JavaScript Profiling:

Opening/closing the sidebar:
[CPU-20190612T150154.zip](https://github.com/microsoft/vscode/files/3280912/CPU-20190612T150154.zip)

Switching tabs and editor groups:
[CPU-20190612T150414.zip](https://github.com/microsoft/vscode/files/3280915/CPU-20190612T150414.zip)

[Sidebar opening/closing about 200ms](https://github.com/microsoft/vscode/issues/75111#issuecomment-501220809) which is obviously too much. Do something, please.

**Comment by AmirHosseinHmd** [comment] 2019-06-16 20:56
It's also worth noting that when I change my resolution from 4K (3840 x 2160) to Full HD (1920 x 1080), VS Code becomes super fast, unsurprisingly.
Please consider working on this frustrating problem.

**Comment by ravtakhar** [comment] 2019-06-16 20:59
@AmirHosseinHmd what's your scaling set to?

**Comment by AmirHosseinHmd** [comment] 2019-06-16 21:10
> @AmirHosseinHmd what's your scaling set to?

It's 250% which is the recommended one by the Windows 10 itself:

![Screenshot](http://s4.picofile.com/file/8363808518/Capture.PNG)

**Comment by gregtandiono** [comment] 2019-06-17 02:15
I think the problem could be Electron itself, not necessarily VSCode. Most Electron apps that I use on my 4K panel seem to share the same lag problem:

- Slack: scroll and typing issue.
- Atom: similar issues to VSCode performance, but it seems to be much worse there.
- Typora: typing delay.

And I can confirm that changing your resolution to FHD (1920 x 1080) will improve the performance drastically, but it’s really annoying to have to keep switching your resolution.

**Comment by AmirHosseinHmd** [comment] 2019-06-17 08:10
> I think the problem could be Electron itself, not necessarily VSCode. Most Electron apps that I use on my 4K panel seem to share the same lag problem:
> 
> * Slack: scroll and typing issue.
> * Atom: similar issues to VSCode performance, but it seems to be much worse there.
> * Typora: typing delay.
> 
> And I can confirm that changing your resolution to FHD (1920 x 1080) will improve the performance drastically, but it’s really annoying to have to keep switching your resolution.
> 
> I think VSCode is _awesome_ and it’s the only viable tool to code on Windows 10 that integrates seamlessly with WSL. Props to the team working hard to provide this software for _free_!

I agree. I use WhatsApp Desktop and I have the same problem with it, and it's also been built with Electron.js. I told this in [my issue](https://github.com/microsoft/vscode/issues/75111) to @jrieken [here](https://github.com/microsoft/vscode/issues/75111#issuecomment-500188157), but [he said you should prove it](https://github.com/microsoft/vscode/issues/75111#issuecomment-501195055)!
Electron.js is cancer! Believe me, no one has a good experience with Electron apps, I don't know why they decided to develop VS Code with Electron.

**Comment by AmirHosseinHmd** [comment] 2019-06-17 10:05
Another point:
When I decrease the size of the VS Code window, it becomes fast again.

**Comment by AmirHosseinHmd** [comment] 2019-06-18 16:33
Is there anyone that can help us with this issue?
@rebornix @jrieken @bpasero

**Comment by ravtakhar** [comment] 2019-06-18 17:27
@AmirHosseinHmd try this

1. Right click Visual Studio Code shortcut
2. Properties
3. Compatibility
4. Change DPI settings
5. Check off "Use this setting to fix scaling problems for this program instead of the one in settings"
6. Make sure the drop-down is set to "I signed in to Windows"

**Comment by AmirHosseinHmd** [comment] 2019-06-18 17:34
> @AmirHosseinHmd try this
> 
> 1. Right click Visual Studio Code shortcut
> 2. Properties
> 3. Compatibility
> 4. Change DPI settings
> 5. Check off "Use this setting to fix scaling problems for this program instead of the one in settings"
> 6. Make sure the drop-down is set to "I signed in to Windows"

I tried it. Unfortunately, it didn't make any difference.
Did this solution work for you?

**Comment by ravtakhar** [comment] 2019-06-18 18:31
It made a difference yes, but it did not completely resolve the problem.

**Comment by AmirHosseinHmd** [comment] 2019-06-18 18:35
> It made a difference yes, but it did not completely resolve the problem.

I don't feel any difference to be honest.
And by the way, does your laptop has an Intel integrated graphics processor?

**Comment by ravtakhar** [comment] 2019-06-19 14:38
I am using integrated graphics and when I set my scaling to over 200 percent the problem no longer exists. I'm wondering if you have outdated drivers.

**Comment by AmirHosseinHmd** [comment] 2019-06-19 14:49
> I am using integrated graphics and when I set my scaling to over 200 percent the problem no longer exists. I'm wondering if you have outdated drivers.

I think that's the reason. It all comes down to the fact that the Intel integrated graphics processor doesn't have enough power to handle animations or some type of GUIs in high-resolution displays.

**Comment by AmirHosseinHmd** [comment] 2019-06-20 14:10
> @OliverJAsh @jayphelps we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.
> 
> You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

Please pay attention to this.

**Comment by gregtandiono** [comment] 2019-06-21 07:51
So, I tried the insiders build, and the overall experience is much smoother. 

- The scrolling has improved, but still a bit laggy.
- Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.

**Comment by AmirHosseinHmd** [comment] 2019-06-21 10:57
> So, I tried the insiders build, and the overall experience is much smoother.
> 
> * The scrolling has improved, but still a bit laggy.
> * Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.

Could you please try opening/closing the sidebar, and switching between tabs and tell us your experience?

**Comment by AmirHosseinHmd** [comment] 2019-06-21 16:29
> So, I tried the insiders build, and the overall experience is much smoother.
> 
> * The scrolling has improved, but still a bit laggy.
> * Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.

I just downloaded and installed the insiders' build, but I don't feel any difference in terms of smoothness at all.

**Comment by ravtakhar** [comment] 2019-06-21 16:35
@AmirHosseinHmd It was time for a laptop upgrade for myself. I understand this isn't a resolution, but I opted a FHD (1080) display just because the saving on battery life, scaling issues, and the overall experience of having a matte vs gloss display. I put the two displays side-by-side and honestly on a laptop I don't see the benefit of pushing 4k pixels.

I don't think this is something that the vscode team will be able to address for you because if you're running other electron apps at full-screen you'll experience the same laggish performance.

**Comment by AmirHosseinHmd** [comment] 2019-06-21 16:53
> @AmirHosseinHmd It was time for a laptop upgrade for myself. I understand this isn't a resolution, but I opted a FHD (1080) display just because the saving on battery life, scaling issues, and the overall experience of having a matte vs gloss display. I put the two displays side-by-side and honestly on a laptop I don't see the benefit of pushing 4k pixels.
> 
> I don't think this is something that the vscode team will be able to address for you because if you're running other electron apps at full-screen you'll experience the same laggish performance.

To be honest, since the first day that I bought my 4K laptop, this problem has been a big pain in the ass for me. It's not just about Electron apps, my whole experience when is sluggish and laggy when I'm on 4K resolution. Windows animations are also laggy.

I posted several issues and questions in the Intel website, Microsoft Feedback Hub, and now the VS Code team, but no one has ever really cared about this.

I still strongly believe that this problem has to do with Intel integrated graphics, which in my opinion, are absolute garbage.

However, I don't know why this problem gets worse in Electron apps, that's why I'm trying to inform the VS Code team and ask them if they can do something about it.

**Comment by gregtandiono** [comment] 2019-06-22 00:52
> > So, I tried the insiders build, and the overall experience is much smoother.
> > 
> > * The scrolling has improved, but still a bit laggy.
> > * Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.
> 
> Could you please try opening/closing the sidebar, and switching between tabs and tell us your experience about them?

**Opening/Closing sidebar** does not do anything for me, performance stays the same.
**Switching tabs** also does not improve performance.

**Comment by gregtandiono** [comment] 2019-06-22 00:53
> > @AmirHosseinHmd It was time for a laptop upgrade for myself. I understand this isn't a resolution, but I opted a FHD (1080) display just because the saving on battery life, scaling issues, and the overall experience of having a matte vs gloss display. I put the two displays side-by-side and honestly on a laptop I don't see the benefit of pushing 4k pixels.
> > I don't think this is something that the vscode team will be able to address for you because if you're running other electron apps at full-screen you'll experience the same laggish performance.
> 
> To be honest, since the first day that I bought my 4K laptop, this problem has been a big pain in the ass for me. It's not just about Electron apps, my whole experience is sluggish and laggy when I'm on 4K resolution. Windows animations (minimizing/maximizing windows, opening/closing task view, etc.) are laggy as well.
> 
> I posted several issues and questions in the Intel website, Microsoft Feedback Hub, and now in the VS Code GitHub repo, but no one has ever really cared about this.
> 
> I still strongly believe that this problem has to do with Intel integrated graphics, which in my opinion, are absolute garbage.
> 
> However, I don't know why this problem gets worse in Electron apps, that's why I'm trying to inform the VS Code team and ask them if they can do something about it.

Maybe you can open up an issue in Electron's repo instead?

**Comment by AmirHosseinHmd** [comment] 2019-06-22 10:45
> > > So, I tried the insiders build, and the overall experience is much smoother.
> > > 
> > > * The scrolling has improved, but still a bit laggy.
> > > * Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.
> > 
> > 
> > Could you please try opening/closing the sidebar, and switching between tabs and tell us your experience about them?
> 
> **Opening/Closing sidebar** does not do anything for me, performance stays the same.
> **Switching tabs** also does not improve performance.

I think I didn't make myself clear. I meant do you experience any kind of lag or slowness when opening/closing sidebar and switching between tabs? Because that's my main problem.

**Comment by AmirHosseinHmd** [comment] 2019-06-22 17:16
@bpasero Would you please take a look at this issue again?

**Comment by gregtandiono** [comment] 2019-06-23 07:42
> > > > So, I tried the insiders build, and the overall experience is much smoother.
> > > > 
> > > > * The scrolling has improved, but still a bit laggy.
> > > > * Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.
> > > 
> > > 
> > > Could you please try opening/closing the sidebar, and switching between tabs and tell us your experience about them?
> > 
> > 
> > **Opening/Closing sidebar** does not do anything for me, performance stays the same.
> > **Switching tabs** also does not improve performance.
> 
> I think I didn't make myself clear. I meant do you experience any kind of lag or slowness when opening/closing sidebar and switching between tabs? Because that's my main problem.

No, didn't experience lag for opening/closing sidebar and switching between tabs.

**Comment by AmirHosseinHmd** [comment] 2019-06-23 09:44
> > > > > So, I tried the insiders build, and the overall experience is much smoother.
> > > > > 
> > > > > * The scrolling has improved, but still a bit laggy.
> > > > > * Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.
> > > > 
> > > > 
> > > > Could you please try opening/closing the sidebar, and switching between tabs and tell us your experience about them?
> > > 
> > > 
> > > **Opening/Closing sidebar** does not do anything for me, performance stays the same.
> > > **Switching tabs** also does not improve performance.
> > 
> > 
> > I think I didn't make myself clear. I meant do you experience any kind of lag or slowness when opening/closing sidebar and switching between tabs? Because that's my main problem.
> 
> No, didn't experience lag for opening/closing sidebar and switching between tabs.

Did you use to experience any lags in those areas (opening/closing sidebar, switching between tabs) before? In the normal build?

**Comment by gregtandiono** [comment] 2019-06-24 03:55
> > > > > > So, I tried the insiders build, and the overall experience is much smoother.
> > > > > > 
> > > > > > * The scrolling has improved, but still a bit laggy.
> > > > > > * Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.
> > > > > 
> > > > > 
> > > > > Could you please try opening/closing the sidebar, and switching between tabs and tell us your experience about them?
> > > > 
> > > > 
> > > > **Opening/Closing sidebar** does not do anything for me, performance stays the same.
> > > > **Switching tabs** also does not improve performance.
> > > 
> > > 
> > > I think I didn't make myself clear. I meant do you experience any kind of lag or slowness when opening/closing sidebar and switching between tabs? Because that's my main problem.
> > 
> > 
> > No, didn't experience lag for opening/closing sidebar and switching between tabs.
> 
> Did you use to experience any lags in those areas (opening/closing sidebar, switching between tabs) before? In the normal build?

I did not experience lag in the normal release build either. Scrolling and typing delay is my issue.

**Comment by bpasero** [comment] 2019-06-24 06:59
@AmirHosseinHmd if you are seeing slowdown on your monitor for other applications, especially Electron applications, I do not think that there is something specific VSCode can do about it. There are some command line things you can give a try, but they are not VSCode but rather Electron specific, e.g. `code --disable-gpu`

**Comment by AmirHosseinHmd** [comment] 2019-06-24 11:07
> > > > > > > So, I tried the insiders build, and the overall experience is much smoother.
> > > > > > > 
> > > > > > > * The scrolling has improved, but still a bit laggy.
> > > > > > > * Typing has improved slightly, as in the lag is still there, but it's not very noticeable for me.
> > > > > > 
> > > > > > 
> > > > > > Could you please try opening/closing the sidebar, and switching between tabs and tell us your experience about them?
> > > > > 
> > > > > 
> > > > > **Opening/Closing sidebar** does not do anything for me, performance stays the same.
> > > > > **Switching tabs** also does not improve performance.
> > > > 
> > > > 
> > > > I think I didn't make myself clear. I meant do you experience any kind of lag or slowness when opening/closing sidebar and switching between tabs? Because that's my main problem.
> > > 
> > > 
> > > No, didn't experience lag for opening/closing sidebar and switching between tabs.
> > 
> > 
> > Did you use to experience any lags in those areas (opening/closing sidebar, switching between tabs) before? In the normal build?
> 
> I did not experience lag in the normal release build either. Scrolling and typing delay is my issue.

Okay, thank you.

**Comment by AmirHosseinHmd** [comment] 2019-06-24 11:15
> @AmirHosseinHmd if you are seeing slowdown on your monitor for other applications, especially Electron applications, I do not think that there is something specific VSCode can do about it. There are some command line things you can give a try, but they are not VSCode but rather Electron specific, e.g. `code --disable-gpu`

Thank you for your response.
However, I think that it would be nice if you tell us what you think about this problem yourself?
Is it all about Electron you can't do anything for VS Code? Or VS Code can actually be better in terms of smoothness in future updates? Because I think I'm not the only one suffering from this problem.

**Comment by bpasero** [comment] 2019-06-24 12:12
> However, I think that it would be nice if you tell us what you think about this problem yourself?
I think that the problem is present but not well understood, nor easy to fix without substantial investment. From my memories when I briefly switched to a 4k monitor I perceived a drop in performance (e.g. scrolling) that was bad enough for me (personally) to stick with a 2k monitor (this was on macOS).

> Is it all about Electron.js and you can't do anything for VS Code? Or VS Code can actually be better in terms of smoothness in future updates? Because I think I'm not the only one suffering from this problem.
I can not answer this question. I think there are probably certain limits in place with the technology we are using (web rendering).

**Closed** 2019-07-01 12:19 UTC
Labels: electron, freeze-slow-crash, gpu, needs more info, upstream
