### ISSUE TITLE
When merging a GitHub PR, the commit message is empty

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#97717] opened 2020-05-13 14:31 UTC
Issue Type: <b>Bug</b>

When using VS Code to merge a PR, using the squash method, unlike GitHub itself, VS Code does not populate the commit message box with the commit message(s) in the PR.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.6.8-200.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3382)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|31.28GB (5.68GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.6.0
gitlens|eam|10.2.1
vscode-pull-request-github|Git|0.16.0
jenkins-pipeline-linter-connector|jan|1.2.0
vscode-github|Kni|0.30.3
rpm-spec|Lau|0.2.3
autoconf|mae|0.1.0
vscode-docker|ms-|1.2.0
python|ms-|2020.5.78807
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.28.0
vscode-yaml|red|0.8.0
jenkins-jack|tab|1.0.1
shellcheck|tim|0.9.0
code-navigation|vik|0.2.0
vim|vsc|1.14.2

</details>

**Comment by IllusionMH** [comment] 2020-05-13 16:10
/duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1444

**Closed** 2020-05-13 16:10 UTC
Labels: *duplicate
