### ISSUE TITLE
preLaunchTask : looping 

### ISSUE THREAD

**Issue by marcopogo81** [Microsoft/vscode#24667] opened 2017-04-13 10:06 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|0.3.0|
|typescript-hero|rbbit|0.12.0|;

if preLaunchTask is configured will never stop to run the task configured.The debuuger try to start but the preLaunchTask configured it's restarted.
No matter which  task you run.

---

Steps to Reproduce:

1. **set to package.json a script like** 
```json
"scripts": {
    "compile": "grunt build"
}
```
This grunt task is using grunt-copy  and grunt-ts to copy static resources and compile *.ts

2. **set  tasks.json like**
```json
{
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "echoCommand": true,
    "tasks": [
        {
            "taskName":"compile",
            "args":["run","compile"]
        }
    ]
}
```
3. set the launch.json like
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program in DEVELOPMENT",
            "preLaunchTask": "**compile**",

            "program": "${workspaceRoot}/dist/main.js",
            "outFiles": ["${workspaceRoot}/dist/**/*.js"],
            "args":["env=development"]
        }
    ]
}
```

**Comment by isidorn** [comment] 2017-04-13 13:37
Assigning to april to investigate

**Comment by isidorn** [comment] 2017-04-27 14:32
@marcopogo81 This scenario works for me.
Can you please provdie a bit more details. What does not seem to work?
You are not using a watching task? But the task always seems to start again and again when you try to start debugging?

**Comment by isidorn** [comment] 2017-05-09 09:34
Closing until more details are provided

**Comment by lsantos10** [comment] 2017-05-24 23:20
I can reproduce this using Github [DebugProtractorTypeScript](https://github.com/vovikdrg/DebugProtractorTypeScript)

**Comment by isidorn** [comment] 2017-05-29 10:22
@lsantos10 thanks. Reopening and assigning to June to look into it

**Comment by isidorn** [comment] 2017-06-06 14:25
@lsantos10 I tried reproducing using the repository you provided and could not. The task finishes but the debug fails to start (to an unrelated reason that I do not have everything setup)
Can you let me know how did you setup the repository or can you reproduce with some other repository?

![screen shot 2017-06-06 at 16 24 52](https://cloud.githubusercontent.com/assets/1926584/26834109/af79a34e-4ad4-11e7-9813-c98a6aa68feb.png)

**Closed** 2017-06-13 14:31 UTC
Labels: debug, needs more info
