### ISSUE TITLE
[regression] Recent list on mac doc doesn't includes folders anymore

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57272] opened 2018-08-27 14:31 UTC
Since a few days the recent list in the doc context menu shows almost no entries and seems to show files only. It used to show folder (that I have opened in the past) and files

<img width="467" alt="screen shot 2018-08-27 at 16 30 04" src="https://user-images.githubusercontent.com/1794099/44665568-7db7cc80-aa16-11e8-8479-c10f2051867f.png">

**Comment by bpasero** [comment] 2018-08-27 15:20
@jrieken the list is driven by the list of recently opened files/folders/workspaces and this list can get cleared, e.g. if you run `File > Recently Opened > Clear Recently Opened`. Can you check the menu entries to see if they match?

Then, whats the contents of this for you:
* open /Users/bpasero/Library/Application Support/Code - Insiders/storage.json
* find the contents under the `openedPathsList` key

**Comment by jrieken** [comment] 2018-08-27 15:27
<img width="1125" alt="screen shot 2018-08-27 at 17 26 48" src="https://user-images.githubusercontent.com/1794099/44668716-6ed51800-aa1e-11e8-895c-7cdaa4fb5833.png">

yep, files, folders and workspaces in there

**Comment by jrieken** [comment] 2018-08-27 15:30
excerpt from `storage.json` (there are a few more but no errors or such)

```
"openedPathsList": {
        "workspaces2": [
            "file:///Users/jrieken/Code/_samples/virtual",
            "file:///Users/jrieken/Code/vscode",
            "file:///Users/jrieken/Code/vscode-nls-dev",
            "file:///Users/jrieken/Code/gulp-tsb",
            "file:///Users/jrieken/Code/vscode-docs",
            "file:///Users/jrieken/Code/collab/vscode-loader",
            "file:///Users/jrieken/Code/vscode-distro",
            {
                "id": "2fe8841ab3a022a03af35d4afa32766d",
                "configPath": "/Users/jrieken/Code/collab/CollabRemoteHub.code-workspace"
            },
            "file:///Users/jrieken/.vscode-insiders/extensions/ms-vscode.powershell-1.8.3/logs/1534861262-8424461e-55d4-452d-aec7-06d0b5e523bb1534861259950",
            "file:///Users/jrieken/Code/vscode/build/perf",
            "file:///Users/jrieken/Code/vscode-perf-canary",
            "file:///Users/jrieken/Code/vscode-nls-dev-loader",
            "file:///Users/jrieken/Code/_samples/ConsoleAppDnx",
            "file:///Users/jrieken/Code/vscode-nls",
            "file:///Users/jrieken/Code/vscode-tools/extensions",
            "file:///Users/jrieken/Code/collab/VSCodeBeautify",
            "file:///Users/jrieken/Code/collab/node",
            "file:///Users/jrieken/Code/vscode-uri",
            "file:///Users/jrieken/Code/_samples/dummy-extension",
            "file:///Users/jrieken/Code/collab/electron-startup-perf-baseline",
            "remotehub://github.com/Microsoft/vscode/",
            "remotehub://github.com/OmniSharp/omnisharp-roslyn",
            "remotehub://github.com/OmniSharp/omnisharp-roslyn/",
            "remotehub://github.com/OmniSharp/omnisharp-roslyn/src/",
            "remotehub://github.com/OmniSharp/omnisharp-roslyn/test",
```

**Comment by bpasero** [comment] 2018-08-28 09:05
I cannot reproduce this when running out of sources with the provided contents, so this seems to be the same as the reported one.

**Comment by jrieken** [comment] 2018-08-28 09:17
Just saying that this used to work just fine for me and has only stopped to work recently

**Comment by jrieken** [comment] 2018-08-28 09:29
@bpasero So what is the recommendation to get out of this and how could the change from working to broken be caused?

**Comment by bpasero** [comment] 2018-08-28 09:45
@jrieken if you clear recently opened and restart, does it change?

**Comment by jrieken** [comment] 2018-08-28 14:08
> @jrieken if you clear recently opened and restart, does it change?

Nope - clearing doesn't help still shows just files and only very few of those. This works with 1.26.1, so it must be a regression with 1.27.x

**Comment by bpasero** [comment] 2018-08-28 14:52
@jrieken thing is, 1.26.1 and 1.27.x use different application bundle identifiers. The dock contents are (as far as I know) very much bound to the application ID. As an experiment you could try to change the ID (Info.plist) once and then back again to see if that causes some kind of cache to clear.

**Comment by bpasero** [comment] 2018-08-30 16:43
I need someone from Apple to explain to me how this menu works... I double-checked the changes around https://github.com/Microsoft/vscode/blame/a550394f34888639ff7bb3d5b6742babe46d59f5/src/vs/platform/history/electron-main/historyMainService.ts#L71 and there was no change in this milestone, also the implementation looks fine to me (we only add file paths). So this cannot be a regression from this milestone at least.

![image](https://user-images.githubusercontent.com/900690/44866085-81508b00-ac84-11e8-9ff5-f98f322f12d4.png)

**Comment by clshortfuse** [comment] 2019-03-01 15:55
I started having an issue after an insider build up to this commit:

https://github.com/Microsoft/vscode/commit/e02e44464c02d617b98d0a3265bf5efef7794436

Stable version 1.30.1 does not give me an issue.

**Comment by bpasero** [comment] 2019-03-01 17:31
@clshortfuse what are your exact steps to reproduce this? remember to start with an empty list (clear it)

**Comment by clshortfuse** [comment] 2019-03-06 16:02
Well, Clean Recently Open actually fixed it. Now that I did that, the issue went away.

Perhaps an older Electron format is incompatible with a newer one used 1.31.0? I'm sorry I can't be of more help, but at least we know that resetting the history will possibly fix the issue. Now we'd just have to find out why.

I wasn't paying much attention to my list before, but I believe it did have a reference to folder that no longer exists. I'm not sure if that matters.

**Comment by bpasero** [comment] 2019-03-06 16:37
Good hint, I just tried the dock with a deleted folder but it was still working (just not showing the entry for the deleted folder).

**Comment by clshortfuse** [comment] 2019-03-06 17:03
I pulled up a comparison of 1.30.1 vs the commit of Insider version I started having issues with. Mac OS X history was indeed changed:

https://github.com/Microsoft/vscode/compare/dea8705087adb1b5e5ae1d9123278e178656186a...e02e44464c02d617b98d0a3265bf5efef7794436#diff-80efc5fed0d5a0ab6253c65b27c1941b

At a glance, and looking at the changed tests, history can be `null`. Also, there's some interaction with IEnvironmentService and ILabelService (now getSimpleWorkspaceLabel).

I wouldn't be surprised if it's either of the new functions (`getSimpleWorkspaceLabel` or `getPathLabel`) trying to get a label for a workspace folder that has been deleted.

**Comment by bpasero** [comment] 2019-03-06 17:28
I would think that should not have changed much, e.g. for a file/folder we still use its `basename`. 

> At a glance, and looking at the changed tests, history can be null
Where do you see that?

**Comment by clshortfuse** [comment] 2019-03-06 17:41
@bpasero https://github.com/Microsoft/vscode/commit/bec935777767519cca0c7b26e0b548da3ff1925d

From what I'm reading, the change is instead of expecting a string array, it's an Array of `(string | null)`. That's what would lead me to believe there was a format change which leads to a compatibility issue.

There's also the possibility that my history list was faulty in 1.30.1. Perhaps it added an invalid (perhaps `null` value), which 1.31 doesn't produce anymore. Maybe what's happening is that 1.31 is no longer expecting an invalid value in the history and aborting the whole procedure when it does. Darn, now I wish I had saved my history file. :-/

**Comment by bpasero** [comment] 2019-03-07 07:54
@clshortfuse well I do not really see invalid values being added. To check, simply trace any usage of `app.addRecentDocument` in `historyMainService.ts`. This is the call that will add entries to the macOS dock. I only see calls with using `originalFSPath()` that never returns null and would throw an error if it was null in the first place.

This leads me to believing that it is an issue with macOS rather than VSCode.

**Comment by clshortfuse** [comment] 2019-03-07 13:50
@bpasero When I first had the issue I had 1.30.1 stable (with its blue icon) working fine, but 1.31 Insider (green) not adding entries. It would cancel out the possibility of it being an OS issue if, at the same time, on version didn't have an issue while the other did. When I upgraded the stable build past 1.31, then both stopped working.

`this.labelService.onDidRegisterFormatter(() => this._onRecentlyOpenedChange.fire());` was removed.

But _onRecentlyOpenedChange should still be fired eventually by `onWorkspaceSaved`. 

My stable is actually showing some issues right now and I haven't cleared the Recent list.

There are entries in File=>Open Recent lists 5 workspaces and 7 files, while the Dock only lists 2 folders and no files. The 3 that aren't in listed in the dock are because they no longer exists. 

When I opened a new workspace (folder), Recents shows 6, and Dock shows 3. But still, none of the files are being listed in Dock. I haven't cleared anything yet, so we may be able to diagnose something. My guess is Electron/VS thinks the dock is full (reached max entries), but isn't accounting for Mac OS X is filtering out nonexistent folders/files.

**Comment by clshortfuse** [comment] 2019-03-07 14:49
Mac OS X won't add URLs that don't exist to Dock if using `noteNewRecentDocumentURL` which I can confirm is what Electron does: https://github.com/electron/electron/blob/6da939629b490e0a76d7a451bb9fb5ab4a0a1729/atom/browser/browser_mac.mm#L49

VSCode thinks it has reached MAX_ENTRIES simply because it assumes calling `app.addRecentDocument` will guarantee an entry and that's not the case. If you want to add an item that doesn't exist, you have make it a menu item instead, as answered in this [Stackoverflow question](https://stackoverflow.com/questions/3236529/add-to-the-open-recent-menu-an-item-that-doesnt-point-to-a-file).

I still found some peculiarities, but I think checking for the file to exist before adding to the Dock would be the first step.

**Comment by bpasero** [comment] 2019-03-07 15:26
@clshortfuse good point, yeah this could be an explanation for some of the issues we are seeing, not sure if all. Definitely worth to see if we can check the file for existence before adding it.

**Comment by jrieken** [comment] 2019-03-07 15:44
> @jrieken for you, clearing the list of recently opened did not help right?

That's a long time ago... Not sure anymore, I do remember tho that it once recovered after a restart. Currently I am in a state where it shows something which is a mixture of stale and recent files/folders

**Comment by bpasero** [comment] 2019-03-07 16:20
@jrieken stale meaning they are not in the list of recently opened (e.g. from the File menu)?

**Comment by jrieken** [comment] 2019-03-07 16:27
No, file menu is correct but the dock menu is doing something else

**Comment by bpasero** [comment] 2019-03-08 06:24
Ok I think this is the issue we still have no real understanding about. I can at least look into not adding dock entries that do not exist on disk.

**Comment by bpasero** [comment] 2019-03-11 14:46
Pushed a fix to not add paths to the dock that do not exist on disk, this seems to work much better.

**Closed** 2019-03-11 14:46 UTC
Labels: bug, electron, mac, upstream, workbench-history

**Comment by PeterRock** [comment] 2019-04-19 02:25
It can not work again
#69754
