### ISSUE TITLE
Go to definition Peek sometimes hangs UI

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#84726] opened 2019-11-13 18:41 UTC
Issue Type: <b>Bug</b>

When opening the Go to Definition Peek UI for the code below (new code I'm adding), it can take the peek ~10s to show up, and while it is "processing" the entire vscode UI is unresponsive.

![image](https://user-images.githubusercontent.com/641685/68793151-ae375680-061a-11ea-8043-8ceb970bb48d.png)

Here is a trace when opening the peek UI:
[gotodef-peek-open-profile.zip](https://github.com/microsoft/vscode/files/3842853/gotodef-peek-open-profile.zip)

From looking at the profile it looks like `CodeLensContentWidget` is the long pole.

Here is a trace of closing that same peek UI (which also takes a few seconds and hangs the whole UI):
[gotodef-peek-close-profile.zip](https://github.com/microsoft/vscode/files/3842854/gotodef-peek-close-profile.zip)

FYI, I have both references and implementation code lens enabled (as well as GitLens ones). And if I turn off all code lens via `"editor.codeLens": false` then the problem completely goes away

It also seems to only happen with large files (the above was with `lib.dom.d.ts`), and when it happens scrolling in the peek UI is also horribly slow as well.

/cc @jrieken 

VS Code version: Code - Insiders 1.41.0-insider (c408a2c02d78982b1f83819c587c02bb59af9f93, 2019-11-13T06:25:23.355Z)
OS version: Windows_NT x64 10.0.19023

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment] 2019-11-14 05:45
The open-profile seems to lack the JS/Main data. I only see screen shots and rendering info, JS profiles. The close-profile has all the information and it seems that disposing many, many lenses is slow, like the removing of editor view zones.

<img width="726" alt="Screenshot 2019-11-14 at 06 39 39" src="https://user-images.githubusercontent.com/1794099/68829612-8ba04e80-06a9-11ea-8caf-ea40e30321a1.png">

Removing a single view zone takes around 4-5ms which isn't super but still doesn't explain why it adds up to 10 seconds in total

<img width="556" alt="Screenshot 2019-11-14 at 06 43 59" src="https://user-images.githubusercontent.com/1794099/68829787-2731bf00-06aa-11ea-9d37-603fd5a3ce23.png">

**Comment by jrieken** [comment] 2019-11-14 05:51
I can reproduce. It seems that there are about 8700 lenses and that inserting all of them is a little too much...

**Comment by jrieken** [comment] 2019-11-14 07:05
I pushed some tweaks to creating code lens widgets. It now takes roughly 0.5ms to create and insert one where now most time is spent inserting. That still totals to 5-6 seconds because there is soo many lenses. 

Closing is still slow and also much slower than "closing" them by switching tabs. I need to investigate what's the culprit here. 

Ultimately tho we either change the implementation approach, e.g not making space for all lenses at once at the cost of flicker and scroll jank, or we limit the amount of lenses that we show...

**Comment by jrieken** [comment] 2019-11-14 16:49
Adding @alexandrudima for add/remove view zone. Steps to reproduce

**Repo using workbench tabs:**

* open two `lib.d.ts` and in another tab `foo.ts`
* enable typescript reference code lense
* switch from `foo.ts` to `lib.ts` -> ❄️ freeze
* switch bad to `foo.ts` -> fast..

**Repro using peek:**

* in `foo.ts` type `document.createAttribute`
* run peek definition (alt+f12) on `createAttribute` -> ❄️ freeze (the same as above)
* close peek -> ❄️ freeze. This is different from switching tabs because the view is still alive before contributions get disposed, e.g when switching tabs the editor clears all view zones  (editor.setModel/dettachModel) before the code lens controller removes them one by one

**Comment by jrieken** [comment] 2019-11-14 16:57
fyi - https://github.com/microsoft/vscode/commit/9c9b8a9043f4f8eabf9143bbf029743493dd48d3 adds a trick/workaround so that closing peek with many, many code lenses is fast

**Comment by jrieken** [comment] 2019-11-15 07:49
There was some more low hanging fruit in the code lens widget but opening lib.d.ts is still slow. Profiler hints towards `_insertWhitespaceAtIndex`. 
See: [Profile-20191115T084555.json.zip](https://github.com/microsoft/vscode/files/3850349/Profile-20191115T084555.json.zip)

<img width="593" alt="Screenshot 2019-11-15 at 08 38 52" src="https://user-images.githubusercontent.com/1794099/68925449-5c5e1000-0783-11ea-9ea6-bda53276f991.png">

**Comment by alexandrudima** [comment] 2019-11-15 16:22
@jrieken I've now pushed to master changes which make the whitespace insertion/removal very fast.

The new bottleneck shows up in the editor render content widgets, but that is a false positive, that place needs to render some content widgets and forces sync layout by asking them for clientWidth/clientHeight. The editor only asks the visible widgets, but the browser layout takes 500ms because the DOM is now full of thousands of content widgets.

![image](https://user-images.githubusercontent.com/5047891/68958446-6fe19900-07cc-11ea-821b-94c9bb427696.png)

@jrieken Would it be possible to tweak the code lens controller to only have content widgets for the visible code lenses? I've noticed most of them have an empty `&nbsp;` as content.

**Comment by jrieken** [comment] 2019-11-18 09:27
Yeah, today we use [`this._domNode.hasAttribute('monaco-visible-content-widget');`](https://github.com/microsoft/vscode/blob/03ef538d3d6603a2cf9e3d8bebaaa288b243da00/src/vs/editor/contrib/codelens/codelensWidget.ts#L155) to know if a widget is visible or not. However, I just learnt that there is also `monaco-visible-view-zone` - I'll give that a try.

**Comment by jrieken** [comment] 2019-11-18 11:04
This is now in the range of 80-90ms which is still a couple of frames but I'd say fast enough to close this.

**Closed by jrieken** 2019-11-18 11:04 UTC
Labels: editor-code-lens, freeze-slow-crash, perf
