### ISSUE TITLE
"Task cannot be tracked" frustration

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#114933] opened 2021-01-25 17:58 UTC
* use https://github.com/microsoft/vscode-github-issue-notebooks
* run `npm i`
* the project defines an npm script `bundle-all`
* there is a task defined for the bundle-all script
* now, remove this line https://github.com/microsoft/vscode-github-issue-notebooks/blob/4c50e8f23b70dd073c4a181725f38867667e73cd/.vscode/tasks.json#L21
* press F5
* :bug: you get a message about being unable to track a task, that message is really unhelpful

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/1794099/105746050-40392f80-5f3f-11eb-8f59-743a23aac8ae.png">

**Comment by connor4312** [comment] 2021-01-25 18:10
I think this is because you have no problem matchers for the task

But the message could be more helpfulk

**Comment by jrieken** [comment] 2021-01-25 18:11
hm... but I don't want problem matchers...

**Comment by jrieken** [comment] 2021-01-25 18:30
As suggestion, I now added some problem matcher. It did need a reload of the renderer and now I can launch. Tho, I think a that shouldn't be needed at all

**Comment by jrieken** [comment] 2021-01-25 18:30
updates steps: remove this line: https://github.com/microsoft/vscode-github-issue-notebooks/blob/4c50e8f23b70dd073c4a181725f38867667e73cd/.vscode/tasks.json#L21

**Comment by isidorn** [comment] 2021-01-26 10:12
@alexr00 is out this week. We have always been behaving like this.
Thus assigning to February so I look into this in debt week. This experience definetly needs to be improved. Thanks for sharing feedback Joh!

**Comment by weinand** [comment] 2021-02-03 13:22
I've removed the "debug" label because this issue is unrelated to debug.

**Comment by alexr00** [comment] 2021-02-03 14:19
There's a[ long standing feature request](https://github.com/microsoft/vscode/issues/6209) for having background tasks be prelaunch tasks without having a problem matcher. Since background tasks go until they're killed, we don't have anything to trigger off of to say that the task is "done enough". The problem matcher lets us have something to key off of.

**Comment by isidorn** [comment] 2021-02-03 14:21
After discussing with @alexr00 we decided that I improve the message in debug to make sure that the user is aware that a problem matcher is needed.
And I will also offer to Debug Anyway.

I have no better suggestion.
Since there is already an issue for tasks, I will unassing @alexr00

**Comment by isidorn** [comment] 2021-02-04 16:30
@jrieken thanks for nice repro steps.

As discussed in previous comment, I have fine tuned the message and am now offering to "Debug Anyway" if you do not care about problem matchers. Try it out and let me know how it feels now.

![Screenshot 2021-02-04 at 17 26 59](https://user-images.githubusercontent.com/1926584/106923641-9744be80-670e-11eb-84f3-eeedbbff031e.png)

**Comment by weinand** [comment] 2021-02-04 16:54
Wording:
"Make sure to have a problem matcher defined" is still not very helpful because it does not really say what to do.

Could we use something like this:
>"Debug cannot track the completion of prelaunch task 'npm...' because it lacks a 'problemMatcher' property. Please see <link to documentation>".

**Comment by isidorn** [comment] 2021-02-04 17:06
That makes sense. Do we have those docs somewhere?
I would just remove the word 'debug' from that. So Something like
"Cannot track the completion of task 'npm...' because it lacks a 'problemMatcher' property. Please see <link to documentation>" "

**Comment by jrieken** [comment] 2021-02-05 08:27
> Try it out and let me know how it feels now.

Yes, I guess it will make the error easier to understand but I doubt it will not relieve my pain. I simply want to ensure a task is running/has run before debugging and I don't care about problem matching. I don't really understand why that isn't supported

**Comment by isidorn** [comment] 2021-02-05 08:41
Well we want to make sure to offer the user to not debug and fix potential errors before he starts debugging.
Now in this case the task can not be tracked, thus we have no clue about errors. There might be, and there might not be, and the task might still be running we just do not know...

I believe it is better to notify the user that he should set a problem matcher than just silently Debug Anyway.

To improve the experience maybe we could add a checkmark "remember my choice". That way you would have to say Debug Anyway once and it will be saved for this workspace.

**Comment by alexr00** [comment] 2021-02-05 09:16
I don't think we do have documentation for this. I can add it to the "Common Questions" section for tasks. https://code.visualstudio.com/docs/editor/tasks#_common-questions

**Comment by isidorn** [comment] 2021-02-05 09:25
@alexr00 that would be great!

**Comment by alexr00** [comment] 2021-02-05 10:29
Added: https://github.com/microsoft/vscode-docs/blob/master/docs/editor/tasks.md#can-a-background-task-be-used-as-a-prelaunchtask-in-launchjson

**Comment by isidorn** [comment] 2021-02-05 10:34
Lovely!
Does someone know what is the process to have links to docs in VS Code? Do I need to register that URL somewhere?
@weinand @alexr00 might you know?

**Comment by jrieken** [comment] 2021-02-05 11:29
> There might be, and there might not be, and the task might still be running we just do not know...

I'd say that in the absence of a problem matcher there never is errors and I wonder why that isn't supported? This is independent of reporting errors when a matcher exists.

**Comment by jrieken** [comment] 2021-02-09 14:10
re-opening for traction

**Comment by weinand** [comment] 2021-02-09 15:21
Let me try to summarise the problem so that we are all on the same page:

- debug's "preLaunchTask" property expects a task that returns a status on completion. Based on this debug launches the debuggee or not (in case of errors).
- if "preLaunchTask" is set to a **background task**, waiting for the "completion status" is not helpful because it comes too late (or never). Debug detects this case and uses the problem matching of the task as a workaround for detecting when the task is no longer active (and debugging can start). Without a problem matcher, debug cannot "track" the task and doesn't know when to launch the debuggee. Launching the debuggee immediately typically results in a failing debug session because building the debuggee has not yet finished.

@dbaeumer has confirmed this 3 years ago: https://github.com/microsoft/vscode/issues/6209#issuecomment-350994475

We in debug land cannot do much to solve this problem: we could drop the "Task cannot be tracked" message and start launching the debuggee immediately or after waiting for a bit.

Tasks could:
- install an "artificial problem matcher" on background tasks that lack a problem matcher (so that debug's workaround continues to work), or better:
- provide API so that debug can track the activity of a background task.

How should we proceed?

**Comment by jrieken** [comment] 2021-02-09 15:31
> start launching the debuggee immediately or after waiting for a bit.

That's exactly what I am suggesting. My "preLaunchTask" is a background task which has _no_ problem matcher. Instead of making my life complicated debug should start the task and immediately start debugging. No checks, no nothing just a very convenient way of launching a task at the right time

**Comment by weinand** [comment] 2021-02-09 15:36
Having read all the issue around this I don't think that your proposal is a good solution.
Many users complained about the fact that the debug session launch happens immediately before the build has finished.

Why do you want to install a background task as a "preLaunchTask" if it does not run "preLaunch" and is not able to build the debuggee?

**Comment by jrieken** [comment] 2021-02-09 15:44
> Many users complained about the fact that the debug session launch happens immediately before the build has finished.

You mean they complained because they had not configured a problem match and not used a non-background task?

**Comment by weinand** [comment] 2021-02-09 16:40
Yes, a background task with a broken problem matcher that would result in a failing debug launch. Typical symptom is that the first "F5" doesn't work, but all later F5" do work...

**Comment by weinand** [comment] 2021-02-09 16:44
@connor4312 @isidorn @roblourens @alexr00
should we follow @jrieken's proposal to drop the "Task cannot be tracked" alert for background tasks that lack a problem matcher and just launch the debug session immediately?

**Comment by isidorn** [comment] 2021-02-09 16:46
That works for me. We can do the change right now in insiders to get feedback from potentially angry users.

**Comment by connor4312** [comment] 2021-02-09 16:56
A compromise solution could be an "Always Debug Anyway" option (though there are already four options on that button...) which would set a user preference. Would allow still tell users what's happening but give experienced users like Joh a way out.

**Comment by isidorn** [comment] 2021-02-09 17:02
Yeah that was my original proposal in https://github.com/microsoft/vscode/issues/114933#issuecomment-773885163

**Comment by jrieken** [comment] 2021-02-09 17:02
> A compromise solution could be an "Always Debug Anyway" option

A checkbox like "don't ask again _for this task_" might be best compromise

**Comment by connor4312** [comment] 2021-02-09 17:07
Per-task is better, yep.

**Comment by connor4312** [comment] 2021-02-09 17:08
Also, I notice there's a few second delay before the problem matcher prompt is shown. I'm guessing this is debug waiting to see if the process exits with a 0/1 code, but if a task is assigned as `isBackground`, can we skip this?

**Comment by isidorn** [comment] 2021-02-25 13:51
As you suggested I have added a checkbox per task.
Also in case the task `isBackground` I reduced the wait time from 10s to 5s
I have also removed the action "Open Launch.json" to make the choice a bit less daunting and nicer visually (on BigSur when there are 4 actions and a checkbox there is some ugly layout)

Try it out and let me know what you think.


![Screenshot 2021-02-25 at 14 45 26](https://user-images.githubusercontent.com/1926584/109162478-8b31a700-7778-11eb-90ac-bc8e760276d2.png)

**Closed** 2021-02-25 13:51 UTC
Labels: bug, tasks

**Comment by meganrogge** [comment] 2021-02-26 17:31
I followed the exact steps and saw no such dialogue.
