### ISSUE TITLE
Settings sync: Double prompt

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#93810] opened 2020-03-31 00:14 UTC
Issue Type: <b>Bug</b>

1) Sign out of MSA which turns off sync
2) Restart VS Code
3) Turn on sync; walk through the browser flow
4) When prompted for first time sync handling select "Merge"
=> right after I'm prompted whether I want to switch on sync.  I just did, so this is unexpected.
=> this happens in all open windows and is not resolved when I say `yes` in one of the windows

VS Code version: Code - Insiders 1.44.0-insider (13b38d2a494612ace32c4fb878824d6329d4c51e, 2020-03-30T07:30:34.234Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure
Remote OS version: Linux x64 5.0.0-1022-azure

**Comment by RMacfarlane** [comment] 2020-03-31 00:19
Duplicate of https://github.com/microsoft/vscode/issues/93805

**Closed by RMacfarlane** 2020-03-31 00:19 UTC
Labels: bug, settings-sync
