### ISSUE TITLE
Emmet suggest wrong things in SCSS files

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#29270] opened 2017-06-22 15:24 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (a49a42680a4269b79c4e80f6d754bbded03a0593, 2017-06-21T05:15:42.843Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
vscode-eslint|dba|1.2.11
vscode-great-icons|emm|2.1.8
beautify|Hoo|1.1.1
atom-keybindings|ms-|2.0.1
seti-icons|qin|0.1.3
vscode-icons|rob|7.9.0

(2 theme extensions excluded)
---

Steps to Reproduce:

1. Open any SCSS file
2. Try to type "abc" and  then TAB. You'll get an absolutely useless `<abc></abc>`.

I tried to disable Emmet in settings, first only for the SCSS files and then altogether, since Emmet is starting to get into my nerves a bit :)

I tired:
`"emmet.excludeLanguages": [
        "markdown", "scss", "sass", "css"
    ],`

and then:
`"emmet.triggerExpansionOnTab": false`

Help!

**Comment by ramya-rao-a** [comment] 2017-06-22 17:44
Duplicate of #29196

@vvs Sorry about this. It is already fixed in today's Insiders. Thanks for reporting!

**Closed by ramya-rao-a** 2017-06-22 17:44 UTC
Labels: bug, emmet, insiders
