### ISSUE TITLE
TypeScript Language Support silently stops

### ISSUE THREAD

**Issue by bvancea** [Microsoft/vscode#12141] opened 2016-09-16 10:02 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 10 Enterprise, Version 1607

**Steps to Reproduce:**
1. Opened VSCode on a project with around 1-2000 ts/tsx/css files.
2. Used VSCode for around 1 hour
3. Noticed that the Language Support for TypeScript stopped working. This included intellisense, symbols, etc.

**Notes**
The issue goes away after using the 'Reload Window' command.

**Additional information**

Code processes in the process explorer
![code](https://cloud.githubusercontent.com/assets/1050284/18582327/bf000370-7c04-11e6-9406-07d6ddedf3ca.PNG)

Error for the VSCode dev tools
![vscode-intellisense-down](https://cloud.githubusercontent.com/assets/1050284/18582382/07529c64-7c05-11e6-8bea-b57eff04a0aa.PNG)

**Comment by bpasero** [comment] 2016-09-16 10:05
Since I am not sure if this is us or TS, assigning both @dbaeumer and @waderyan

**Comment by waderyan** [comment] 2016-09-16 20:16
@bvancea thank you for opening this issue and for thoroughly giving us information. We have seen issues similar to this but they are hard to reproduce. Can you help me by giving me more information? 

In your settings set `"typescript.tsserver.trace": "verbose"` and then open the output window. You will see the output of the language service and we should see messages before it stops. 

An additional step that would be helpful to us is if you can set `TSS_LOG=-level verbose`. there should be a log file written next to tsserver.js that would have the form of `.log[0-9]+`

The issue I have been tracking manifestations of this behavior is here. https://github.com/Microsoft/TypeScript/issues/10735

**Comment by dbaeumer** [comment] 2016-09-17 12:09
Here is what happened: the tsserver crashed and all open requests very rejected with service died. However the service gets restarted automatically unless it crashes very frequently. In this case we show an message to the user: @bvancea have you seen such a message. When you get into that state again can you let use know the command lines of the running Code.exe processes.

**Comment by bvancea** [comment] 2016-09-19 08:31
@waderyan Thanks for the tips, I will update the log settings and get back to you.

@dbaeumer Some additional information:
- I have not seen any visual notification regarding any tsserver crashes, save for the logging one in the dev tools.
- I am not adding any additional parameters to the Code.exe process.

**Comment by bvancea** [comment] 2016-09-19 11:46
@waderyan Here is the output after updating the "typescript.tsserver.trace" to "verbose".
```
[Trace - 11:42:10 AM] TypeScript Service: canceled request with sequence number 7
[Trace - 11:42:11 AM] TypeScript Service: canceled request with sequence number 8
[Error - 11:43:28 AM] TSServer exited with code: 3
[Info  - 11:43:28 AM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Trace - 11:44:27 AM] TypeScript Service: canceled request with sequence number 6
[Trace - 11:44:35 AM] TypeScript Service: canceled request with sequence number 15
[Trace - 1:06:23 PM] TypeScript Service: canceled request with sequence number 17
[Trace - 1:06:23 PM] TypeScript Service: canceled request with sequence number 16
[Trace - 1:06:29 PM] TypeScript Service: canceled request with sequence number 19
[Trace - 1:06:29 PM] TypeScript Service: canceled request with sequence number 20
[Trace - 1:06:30 PM] TypeScript Service: canceled request with sequence number 21
[Trace - 1:06:32 PM] TypeScript Service: canceled request with sequence number 22
[Trace - 1:07:19 PM] TypeScript Service: canceled request with sequence number 24
[Trace - 1:07:19 PM] TypeScript Service: canceled request with sequence number 23
[Trace - 1:11:53 PM] TypeScript Service: canceled request with sequence number 25
[Trace - 1:17:56 PM] TypeScript Service: canceled request with sequence number 26
[Trace - 1:17:58 PM] TypeScript Service: canceled request with sequence number 27
[Trace - 1:18:00 PM] TypeScript Service: canceled request with sequence number 29
[Trace - 1:18:00 PM] TypeScript Service: canceled request with sequence number 28
[Trace - 1:34:20 PM] TypeScript Service: canceled request with sequence number 31
[Trace - 1:34:49 PM] TypeScript Service: canceled request with sequence number 30
```

Where can I set `TSS_LOG=-level verbose` ? Is it an environment variable?

**Comment by waderyan** [comment] 2016-09-20 17:25
Yes it is an env variable. 

@mhegazy correct me if I am wrong.

**Comment by mhegazy** [comment] 2016-09-20 17:36
yes. you can also specify a file path:

`TSS_LOG=-level verbose -file c:\tmp\server.log`

**Comment by bvancea** [comment] 2016-09-29 08:21
@mhegazy @waderyan sorry for the late response. 

I set the TSS_LOG as instructed, but looking through the file, I don't see anything out of the ordinary. Just Info and Perf entries.

**Comment by waderyan** [comment] 2016-09-29 16:12
@bvancea can you share the file?

**Comment by waderyan** [comment] 2016-11-21 23:08
Closing until more info is given.

**Closed by waderyan** 2016-11-21 23:08 UTC
Labels: needs more info, typescript

**Comment by DerFlatulator** [comment] 2016-11-22 01:44
I don't know if this is the same problem, but here is my output:

TypeScript output within VSCode:

```
[Trace - 12:34:16 pm] Sending request: quickinfo (79). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/path/to/somefile.ts",
    "line": 946,
    "offset": 19
}
[Trace - 12:34:19 pm] TypeScript Service: tried to cancel request with sequence number 79. But request got already delivered.
[Trace - 12:34:22 pm] TypeScript Service: canceled request with sequence number 80
[Trace - 12:34:22 pm] TypeScript Service: canceled request with sequence number 81
[Trace - 12:34:26 pm] TypeScript Service: canceled request with sequence number 82
[Trace - 12:34:26 pm] TypeScript Service: canceled request with sequence number 83
[Trace - 12:34:29 pm] TypeScript Service: canceled request with sequence number 84
[Error - 12:34:30 pm] TSServer exited with code: 3
[Info  - 12:34:30 pm] Using tsserver from location: c:\path\to\node_modules\typescript\lib\tsserver.js
[Trace - 12:38:51 pm] TypeScript Service: canceled request with sequence number 91
[Trace - 12:39:07 pm] TypeScript Service: canceled request with sequence number 92
```

Tail of TSS_LOG:

```
Info 255  Search path: c:/path/to/a/proj/directory
Info 256  Config file name: c:/path/to/tsconfig.json
```
(then nothing)

However, several times in the log I get something like this:

```
Info 25   Config file name: c:/path/to/tsconfig.json
Err 26    Add recursive watcher for: c:/path/to
Info 27   Opened configuration file c:/path/to/tsconfig.json
Err 28    Add watcher for: c:/path/to/dir-a
Err 29    Add watcher for: c:/path/to/dir-b
```
(and so on...)

**Comment by waderyan** [comment] 2016-11-28 20:43
@DerFlatulator looks like you are seeing something similar as this issue - https://github.com/Microsoft/TypeScript/issues/10735

**Comment by mhegazy** [comment] 2016-11-28 20:54
can you share the TSS_LOG file?
