### ISSUE TITLE
Can't open a file by clicking on it if Code is already running.

### ISSUE THREAD

**Issue by BTMike** [Microsoft/vscode#73188] opened 2019-05-02 19:07 UTC
Issue Type: <b>Bug</b>

If I have Code running and I go to a folder and try to open a file by clicking on it, I get a popup error message that says "A second instance of Code is already running as Administrator". The only way I can open the file is to browse to it from the File menu inside Code.

Two things to note here: 
   1) There's no "second instance" running, there's only one.
   2) I don't want to start another instance; I want my file to be opened by the currently running instance.

Steps To Reproduce:
  1) Open Visual Studio Code as Administrator. 
  2) In Windows Explorer, right-click on a file and select "Open with Code".
  3) Observe a Visual Studio Code dialog appears and the file is not opened.

I found this issue that was filed for the same bug THREE YEARS AGO - and it was closed with no resolution or explanation:
  https://github.com/Microsoft/vscode/issues/4514

Other bugs have been filed too but they've all been closed with the excuse "We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate". Not once is a link provided to the "one we already have", so no one can track it.

Come on guys, it has happened on all machines forever and it's extremely easy to reproduce.  There must be some new features you can put hold until this annoying long-standing bug is fixed.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|24.00GB (10.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
coldfusionsymbols|dal|0.0.2
EditorConfig|Edi|0.13.0
cshtml|fir|0.1.3
auto-close-tag|for|0.5.6
beautify|Hoo|1.4.11
coldfusion|ili|1.0.1
vscode-cfml|Kam|0.5.3
csharp|ms-|1.19.0
ColdFusion|Ske|0.0.1

</details>

**Comment by gjsjohnmurray** [comment] 2019-05-02 22:17
@BTMike my reading of #4514 is that the OP closed it [(here)](https://github.com/Microsoft/vscode/issues/4514#issuecomment-199447590) on Mar 21, 2016 because he couldn't repro. He tried again [9 months later](https://github.com/Microsoft/vscode/issues/4514#issuecomment-267705901), but still no repro. Only on [Sep 6, 2017](https://github.com/Microsoft/vscode/issues/4514#issuecomment-327491985) did someone post the significant fact about launching `code` as Administrator. But as neither the OP nor anyone else with sufficient rights reopened it, it got locked by the bot a couple of months later.

> Other bugs have been filed too but they've all been closed with the excuse "We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate". Not once is a link provided to the "one we already have", so no one can track it.

My experience here is that issues closed as duplicates more often than not **do** include pointers to the still-open issue they're considered to be duplicates of.

I believe the "We figured..." message you quote is one added by the bot as a consequence of a "/duplicate" comment added by someone the bot trusts. It may not be smart enough to check that a link to the duplicate was also added.

Anyway, now you've opened this new issue for it I guess it'll get some attention, this time with a high chance of being reproducible.

**Comment by bpasero** [comment] 2019-05-03 06:12
We cannot easily support this scenario: you are running VSCode as admin, which works fine. But then you try to run it again not as admin, because opening a file will just run VSCode as normal user. Since on startup we do some communication to the first instance to prevent starting multiple instances of VSCode, this fails because of permissions (and that is correct behaviour). 

As a workaround you could use the `--user-data-dir` argument from the command line when running as administrator to ensure you can run an instance of VSCode as admin that is isolated from the other. I would also make sure to use `--extensions-dir` to separate extensions too.

Related: https://github.com/Microsoft/vscode/issues/6560

Closing as designed, this is correct behaviour according to the permissions in play here.

**Closed by bpasero** 2019-05-03 06:12 UTC
Labels: workbench-run-as-admin
