### ISSUE TITLE
Webview-related 404 in smoke test output

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137371] opened 2021-11-17 15:41 UTC
I'm seeing the following logged when running smoke tests in CI:

```
Playwright ERROR: HTTP status 404 for https://f54da407-2248-490a-8369-3a794df1f37d.vscode-webview.net/insider/619f88ad7d4aed5cbe0b55e4d2ff89ffed6c71c3/out/vs/workbench/services/extensions/worker/httpWebWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=b0615b4d-b2e0-450e-af17-a6fdbcf698c4
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=143259&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=80

**Comment by mjbvz** [comment] 2021-11-17 18:46
Duplicate of #130027. Not actual  webview related, we're just re-using the `vscode-webview` endpoint here

**Closed by mjbvz** 2021-11-17 18:46 UTC
Labels: smoke-test-failure
