### ISSUE TITLE
After upgrading to the latest version, the background color of the terminal displays abnormally (low probability will display normal)

### ISSUE THREAD

**Issue by FFFrog** [microsoft/vscode#139065] opened 2021-12-14 08:37 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63
- OS Version: MacOS latest

Normal:
![image](https://user-images.githubusercontent.com/85333600/145962862-ed0496af-01fb-40fa-8bc1-f95d0bd30090.png)

Abnormal:
![image](https://user-images.githubusercontent.com/85333600/145962915-738dfef6-6d05-40c1-bead-2068bf6b8d88.png)

**Comment by FFFrog** [comment] 2021-12-14 08:42
![image](https://user-images.githubusercontent.com/85333600/145963510-61e75d5f-a463-46b5-8b76-dcb61748454d.png)

**Comment by jonathan-lauvernier** [comment] 2021-12-15 08:54
Hello, same problem since the last update. The background color of the terminal is no more the same as the one of the editor.

The problem only occurs while opening a new terminal. If I quit vscode and open it again, background color is just fine. But opening a new terminal (or task) will lead to a darker background color.

![Capture d’écran 2021-12-15 à 09 47 57](https://user-images.githubusercontent.com/86971823/146154377-9e70b559-bbb6-4430-b274-dec5146cde92.png)

Theme : One Dark Pro Flat

**Comment by meganrogge** [comment] 2021-12-15 13:45
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by jonathan-lauvernier** [comment] 2021-12-19 10:12
Thank for your answer, but no, it is not fixed in insider build.

Step to reproduce : Launch VSCode insiders, install One Dark Pro theme, choose theme color Flat, open a **new** terminal.

**Comment by meganrogge** [comment] 2021-12-23 04:51
yes I can reproduce it, /duplicate #139389

**Closed** 2021-12-23 04:51 UTC
Labels: needs more info, *duplicate
