### ISSUE TITLE
Preprocessor deactivation color error

### ISSUE THREAD

**Issue by showeye77** [microsoft/vscode#233145] opened 2024-11-06 01:44 UTC
Type: <b>Bug</b>

If preprocessor #define0, if the corresponding deactivation code is annotated, multiple lines appear to be deactivated color even after #endif.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (8.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.5.0
doxdocgen|csc|1.4.0
wordcounter|kir|2.4.4
vscode-language-pack-ko|MS-|1.95.2024103009
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.10
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|5.13.0
translator|scu|1.1.0
cmake|twx|0.0.17
hex-ascii-converter|yrp|0.0.3
ascii-table|zha|1.0.0

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment] 2024-11-19 09:19
Duplicate of upstream issue: https://github.com/jeff-hykin/better-c-syntax/issues/4

**Closed by alexr00** 2024-11-19 09:19 UTC
Labels: grammar, upstream-issue-linked
