### ISSUE TITLE
Weird space in terminal

### ISSUE THREAD

**Issue by lambdacore12** [microsoft/vscode#227671] opened 2024-09-05 07:20 UTC
Does this issue occur when all extensions are disabled?: Yes/No Yes

- VS Code Version: 1.92.2
- OS Version: Windows 11

Steps to Reproduce:

1. Running a simple python script gives a weird unwanted space (that is not code-related):
2. 
![aa](https://github.com/user-attachments/assets/ddd233ae-b21b-41b2-b008-6fba4aa97179)

**Comment by meganrogge** [comment] 2024-09-06 16:26
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-09-06 16:26 UTC

**Comment by lambdacore12** [comment] 2024-09-14 11:48
@meganrogge Hello, please bear with me as I am new to programming.
I tried reproducing it in Windows Termnal (which is powershell) but it works just fine.
Do you have any pointers as to what I should do next?

![image](https://github.com/user-attachments/assets/b6a84ff5-951e-411f-97bc-043b25b25a1c)

**Comment by meganrogge** [comment] 2024-09-14 14:12
Given you cannot reproduce in Windows Terminal, this means it's fixed in a later version of Windows. There's nothing you can do but wait until this version is available for you.

**Comment by lambdacore12** [comment] 2024-09-14 14:17
Oh! In that case, thank you so much for your help!
