### ISSUE TITLE
[FR]Add ability to let extensions pick files + folders

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#24433] opened 2017-04-10 12:23 UTC
- VSCode Version: 1.11.1
- OS Version: 10.12.4

Extensions sometimes need file or folder names to create new files and hence have the need to ask the user for a file/folder name. Currently this is only possible via the input box, which is rather inconvenient. It would be nice if there were APIs for extension writers which trigger the native OS file/folder selection box (just like what "Save As" for editors is using, similar for load file and select folder).

**Comment by jrieken** [comment] 2017-04-10 13:02
dupe of #13807

**Closed by jrieken** 2017-04-10 13:02 UTC
Labels: api
