### ISSUE TITLE
Issue Reporter opens error page when not logged in

### ISSUE THREAD

**Issue by jnwarp** [microsoft/vscode#70343] opened 2019-03-12 22:54 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Log out of Github
2. Open the issue reporter from Help -> Report Issue
3. Fill out a bug report
4. Click Preview on GitHub

Expected behavior:
The window will open a page with the bug information already filled in.

Actual Behavior:
The window opens to a page with an error 500 page. "Ooops!!!" 

Full url for previous bug report:
```
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvscode%2Fissues%2Fnew%3Ftitle%3DPython%2520no%2520name%2520X%2520in%2520module%2520Y%26body%3D%250AIssue%2520Type%253A%2520%253Cb%253EBug%253C%252Fb%253E%250A%250ACreate%2520the%2520following%2520directory%2520structure%253A%250A-%2520example%252F%250A%2520%2520-%2520test%252F%250A%2520%2520%2520%2520-%2520__init__.py%250A%2520%2520%2520%2520-%2520Test.py%250A%2520%2520-%2520__init__.py%250A-%2520test.py%250A%250AUse%2520the%2520following%2520code%253A%250Afrom%2520example.test%2520import%2520Test%250A%250AExpected%2520behavior%253A%250AVS%2520Code%2520will%2520correctly%2520import%2520the%2520local%2520module.%250A%250AActual%2520behavior%253A%250AThe%2520code%2520is%2520marked%2520as%2520having%2520the%2520error%2520%2522No%2520name%2520test%2520in%2520module%2520example%2522.%250A%2520%2520%250A%250AVS%2520Code%2520version%253A%2520Code%25201.31.1%2520%281b8e8302e405050205e69b59abb3559592bb9e60%252C%25202019-02-12T02%253A20%253A54.427Z%29%250AOS%2520version%253A%2520Windows_NT%2520x64%252010.0.17763%250A%250A%253Cdetails%253E%250A%253Csummary%253ESystem%2520Info%253C%252Fsummary%253E%250A%250A%257CItem%257CValue%257C%250A%257C---%257C---%257C%250A%257CCPUs%257CIntel%28R%29%2520Core%28TM%29%2520i7-7700K%2520CPU%2520%2540%25204.20GHz%2520%288%2520x%25204200%29%257C%250A%257CGPU%2520Status%257C2d_canvas%253A%2520enabled%253Cbr%253Echecker_imaging%253A%2520disabled_off%253Cbr%253Eflash_3d%253A%2520enabled%253Cbr%253Eflash_stage3d%253A%2520enabled%253Cbr%253Eflash_stage3d_baseline%253A%2520enabled%253Cbr%253Egpu_compositing%253A%2520enabled%253Cbr%253Emultiple_raster_threads%253A%2520enabled_on%253Cbr%253Enative_gpu_memory_buffers%253A%2520disabled_software%253Cbr%253Erasterization%253A%2520enabled%253Cbr%253Esurface_synchronization%253A%2520enabled_on%253Cbr%253Evideo_decode%253A%2520enabled%253Cbr%253Ewebgl%253A%2520enabled%253Cbr%253Ewebgl2%253A%2520enabled%257C%250A%257CMemory%2520%28System%29%257C15.93GB%2520%288.31GB%2520free%29%257C%250A%257CProcess%2520Argv%257CD%253A%255CDrive%255CProjects%255CPolySEED%255CPython-Doc%255Cchange.py%257C%250A%257CScreen%2520Reader%257Cno%257C%250A%257CVM%257C50%2525%257C%250A%250A%253C%252Fdetails%253E%253Cdetails%253E%253Csummary%253EExtensions%2520%282%29%253C%252Fsummary%253E%250A%250AExtension%257CAuthor%2520%28truncated%29%257CVersion%250A---%257C---%257C---%250Alanguage-x86-64-assembly%257C13x%257C2.2.11%250Apython%257Cms-%257C2019.2.5558%250A%250A%250A%253C%252Fdetails%253E%250A%253C%21--%2520generated%2520by%2520issue%2520reporter%2520--%253E
```

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.31GB free)|
|Process Argv|D:\Drive\Projects\PolySEED\Python-Doc\change.py|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
python|ms-|2019.2.5558

</details>

**Comment by jnwarp** [comment] 2019-03-12 22:55
![image](https://user-images.githubusercontent.com/15384122/54241719-5333e980-44f8-11e9-8cff-c667082c8a07.png)

**Comment by mjbvz** [comment] 2019-05-29 22:07
Actually I can still this this with the generated link: https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvscode%2Fissues%2Fnew%3Ftitle%3Dfdsafas%26body%3D%250AIssue%2520Type%253A%2520%253Cb%253EBug%253C%252Fb%253E%250A%250Afdsafdsafdsafdsaffdsaf%2520dsaffdsafdsafdsafdsaffdsaf%2520%250A%250AVS%2520Code%2520version%253A%2520Code%2520-%2520Insiders%25201.35.0-insider%2520%286964233e81c68f5a5f34e7eb1da0836e1d539f14%252C%25202019-05-29T05%253A18%253A15.943Z%29%250AOS%2520version%253A%2520Windows_NT%2520x64%252010.0.18362%250A%250A%253Cdetails%253E%250A%253Csummary%253ESystem%2520Info%253C%252Fsummary%253E%250A%250A%257CItem%257CValue%257C%250A%257C---%257C---%257C%250A%257CCPUs%257CIntel%28R%29%2520Core%28TM%29%2520i7-4770HQ%2520CPU%2520%2540%25202.20GHz%2520%284%2520x%25202195%29%257C%250A%257CGPU%2520Status%257C2d_canvas%253A%2520enabled%253Cbr%253Echecker_imaging%253A%2520disabled_off%253Cbr%253Eflash_3d%253A%2520enabled%253Cbr%253Eflash_stage3d%253A%2520enabled%253Cbr%253Eflash_stage3d_baseline%253A%2520enabled%253Cbr%253Egpu_compositing%253A%2520enabled%253Cbr%253Emultiple_raster_threads%253A%2520enabled_on%253Cbr%253Enative_gpu_memory_buffers%253A%2520disabled_software%253Cbr%253Erasterization%253A%2520unavailable_off%253Cbr%253Esurface_synchronization%253A%2520enabled_on%253Cbr%253Evideo_decode%253A%2520enabled%253Cbr%253Ewebgl%253A%2520enabled%253Cbr%253Ewebgl2%253A%2520enabled%257C%250A%257CLoad%2520%28avg%29%257Cundefined%257C%250A%257CMemory%2520%28System%29%257C9.72GB%2520%286.32GB%2520free%29%257C%250A%257CProcess%2520Argv%257C%257C%250A%257CScreen%2520Reader%257Cno%257C%250A%257CVM%257C67%2525%257C%250A%253C%252Fdetails%253E%253Cdetails%253E%253Csummary%253EExtensions%2520%2815%29%253C%252Fsummary%253E%250A%250AExtension%257CAuthor%2520%28truncated%29%257CVersion%250A---%257C---%257C---%250Amarkdown-emoji%257Cbie%257C0.0.9%250Amarkdown-yaml-preamble%257Cbie%257C0.0.4%250Avscode-eslint%257Cdba%257C1.9.0%250Avsc-material-theme%257CEqu%257C2.9.0%250Avscode-github-releases-updater%257Cjoa%257C0.17.0%250Aremote-containers%257Cms-%257C0.57.0%250Aremote-ssh%257Cms-%257C0.37.0%250Aremote-ssh-edit%257Cms-%257C0.37.0%250Aremote-ssh-explorer%257Cms-%257C0.37.0%250Aremote-wsl%257Cms-%257C0.36.1%250Avscode-remote-extensionpack%257Cms-%257C0.14.0%250Acpptools%257Cms-%257C0.23.1%250Apowershell%257Cms-%257C2019.5.0%250Avscode-typescript-tslint-plugin%257Cms-%257C1.1.0%250Adebugger-for-chrome%257Cmsj%257C4.11.3%250A%250A%250A%253C%252Fdetails%253E%250A%253C%21--%2520generated%2520by%2520issue%2520reporter%2520--%253E

**Comment by RMacfarlane** [comment] 2021-05-13 19:16
I've been unable to reproduce this now and haven't had any more reports of this, so am going to go ahead and close this.

**Closed by RMacfarlane** 2021-05-13 19:16 UTC
Labels: bug, issue-reporter, verification-found
