### ISSUE TITLE
Alt+F, S doesn't always save

### ISSUE THREAD

**Issue by natewaddoups** [Microsoft/vscode#31484] opened 2017-07-26 23:46 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer|CoenraadS|0.10.7|
|sort-typescript-imports|miclo|1.3.0|
|csharp|ms-vscode|1.11.0|
|debugger-for-chrome|msjsdiag|3.1.6|;

---

Steps to Reproduce:

1. Try to save your changes with hotkeys: press "Alt+F" followed by "S".

Expected results: Your changes are saved and you can continue working.

Actual results: The File menu is still showing, changes are not saved, and subsequent keystrokes will be interpreted as File menu hotkeys.

Workaround #1: Press "S" again. 
Workaround #2: Pause briefly after "Alt+F". The "S" will work the first time.

There seems to be a race condition where the "S" keystroke gets swallowed before the File menu is displayed.

Data loss has led me to develop an Alt+F,S twitch over the years - I do that key combination every few minutes, without thinking about it, in all applications, and have done so for more than a decade. I've never run into this obstacle in other applications, and it is kind of aggravating to trip over this every time I use VS Code.

**Comment by JackTrapper** [comment] 2017-07-28 21:06
It took me about twenty minutes one day to figure out why the web-site was not honoring my updated code file. I know i saved it. Refresh the web-page - old behavior. 

- Save again - `Alt+F S`
- copy to the server

Still not working. I view the file on the server, and it's the old version. Huh, i guess i copied the file to the wrong place.

- copy to the server again.

Still the wrong version. Open the server version *on* the server; its the old version. What the hell. Maybe i forgot to save it

- `Alt+F S`
- copy to server

Server still isn't working.

> *"I know i saved it. And i **swear** i copied it to the right location*

Use Beyond Compare to diff my location version, and the version on the server. They're identical. 

> *How can Beyond Compare say that the two versions match, when i **know** the version on the server is wrong?!*

Look at the comparison inside Beyond Compare; it says that local copy is wrong.  That's not possible, i **know** i saved it! 

- Save again `Alt+F S`

See, no changes picked up by Beyond Compare; the file is current. To prove it i'll make a minor change in the text file, and save it. The file on the disk doesn't change.

> *Is it possible that Code isn't saving?*

- Click **File** menu
- Click **Save**

changes picked up. 

What? Does `Alt+F S` not work?

- Alt+F S
- Alt+F S
- Alt+F S
- Alt+F S

Ohhh, i see. 

They decided to re-implement menus from scratch, rather than using the tried and true Windows menu control used by every other application on the planet.

Oh well.

**Comment by rebornix** [comment] 2017-08-15 17:35
cc @bpasero first to see if he has some ideas about what's happening there.

**Comment by bpasero** [comment] 2017-08-15 17:56
Duplicate of https://github.com/Microsoft/vscode/issues/20696 ?

**Comment by bpasero** [comment] 2017-11-14 17:55
https://github.com/Microsoft/vscode/issues/5556

**Closed by bpasero** 2017-11-14 17:55 UTC
Labels: electron, upstream, workbench-menu
