### ISSUE TITLE
3-way editor doesn't open when opening conflicted file via cmd+click on integrated terminal

### ISSUE THREAD

**Issue by mentero** [microsoft/vscode#157766] opened 2022-08-10 11:34 UTC
Type: <b>Bug</b>

My usual flow is to work with git from an integrated terminal. I often perform `git rebase -i` and then do `git status` to see what conflicts are there. If they are any, I cmd+click on a file to open it in VS Code. For over a month I was sure that the 3-way merge was broken because I just showed raw file when the config was on, and highlighted the changes correctly when the feature was off. Only today I've learned that it actually works OK, but only when the file is opened via the Source Control sidebar view.

Actual Result:
* cmd+click on a conflicted file from integrated terminal opens raw file
* click on a conflicted file from source control view opens 3-way diff

Expected Result:
* cmd+click on a conflicted file from integrated terminal opens 3-way diff
* click on a conflicted file from source control view opens 3-way diff

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id 1559f191-bd50-40ac-9ff1-9a4360ac066b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.11.4
elixir-test-explorer|ada|0.4.0
markdown-mermaid|bie|1.14.3
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.6
vscode-dash|dee|2.4.0
api-blueprint-viewer|dev|0.9.4
xml|Dot|2.5.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.5.0
vscode-todo-plus|fab|4.18.4
code-runner|for|0.11.8
kotlin|fwc|0.2.26
vscode-pull-request-github|Git|0.48.0
gleam-syntax|gle|0.0.13
gc-excelviewer|Gra|4.2.55
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.4
elixirlinter|iam|0.4.1
copy-current-file-path|ion|0.0.3
elixir-ls|Jak|0.10.0
plantuml|jeb|2.17.3
vscode-graphviz|joa|0.0.6
haml|kar|1.4.1
ruby-rubocop|mis|0.8.6
language-gettext|mro|0.2.0
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
data-workspace-vscode|ms-|0.2.2
mssql|ms-|1.15.0
sql-bindings-vscode|ms-|0.2.1
sql-database-projects-vscode|ms-|0.17.2
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.11.5
test-adapter-converter|ms-|0.1.6
ocaml-platform|oca|1.10.7
vetur|oct|0.36.0
erlang|pgo|0.8.4
phoenix|pho|0.1.1
material-icon-theme|PKi|4.19.0
wgsl|Pol|0.1.12
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.9.1
rust-analyzer|rus|0.3.1162
shader|sle|1.1.5
code-spell-checker|str|2.5.4
ayu|tea|1.0.5
errorlens|use|3.6.0
vscode-lldb|vad|1.7.3
beamdasm|Val|1.1.5
vim|vsc|1.23.2
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.15.2

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252

```

</details>

**Comment by lszomoru** [comment] 2022-08-12 12:17
@hediet, could you please help triaging this? Thanks!

**Comment by hediet** [comment] 2022-08-12 12:53
Duplicate of #157691 and #153800

**Closed by hediet** 2022-08-12 12:53 UTC
Labels: merge-editor
