### ISSUE TITLE
Completions not filtering correctly

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#211101] opened 2024-04-23 15:21 UTC
Testing #210394

I got the suggest widget in a bad state at one point, I don't remember how, and I can't seem to repro anymore.

Anything typed past a `-` character did not register in the filter, and pressing `ctrl+space` again would just complete with something not quite right, like git-Alas.

![image](https://github.com/microsoft/vscode/assets/2019016/2439bf94-2aff-464f-91a9-9ecee9fec34d)

**Comment by Tyriar** [comment] 2024-04-24 08:26
I couldn't reproduce this unfortunately. I suspect it's related to some exception that was thrown, if you see it again could you reopen with some logs? I should have asked for logging in the TPI ☹️

**Comment by Tyriar** [comment] 2024-04-24 08:30
Actually I did just see this:

![image](https://github.com/microsoft/vscode/assets/2193314/739ba67c-5d04-4e3f-aa6d-8356982c2361)

No errors in devtools and opening the output panel to check `Terminal` logs ended up fixing the problem due to a resize. Still not sure on a reliable repro but all I was doing was typing `Get-A`

**Comment by Tyriar** [comment] 2024-04-24 08:34
Looks like it's related to shell integration and the PromptInputModel falling over:

![image](https://github.com/microsoft/vscode/assets/2193314/72870973-00d4-4be5-b6b9-4a2570fec16e)
![image](https://github.com/microsoft/vscode/assets/2193314/b7fa7555-01cf-4ca6-b988-eeba9aa86532)

Works when the circle is there:

![image](https://github.com/microsoft/vscode/assets/2193314/53160c76-b8cc-4a97-81f3-6c5e893c1432)

Chances are this will be fixed when https://github.com/microsoft/vscode/issues/211222 is brought back

**Comment by Tyriar** [comment] 2024-12-09 20:57
Seems fixed

**Closed by Tyriar** 2024-12-09 20:57 UTC
Labels: bug, terminal-suggest
