### ISSUE TITLE
VSCode sends search keystrokes to Microsoft even with telemetry disabled

### ISSUE THREAD

**Issue by taoeffect** [Microsoft/vscode#49161] opened 2018-05-04 01:35 UTC
- VSCode Version: Insider build on May 3, 2018
- OS Version: macOS

Steps to Reproduce:

1. Download latest insider build
2. Run
3. Disable telemetry settings and restart VSCode
4. Open a file (or in my case, the settings), and do Command+F to search, and search for something

Does this issue occur when all extensions are disabled?: didn't try

--------

VSCode will attempt to connect to Bing as you search:

![screen shot 2018-05-03 at 8 00 30 pm](https://user-images.githubusercontent.com/138706/39609840-e512426e-4f19-11e8-8fef-3963a8018fa7.jpg)

**Comment by dd86k** [comment] 2018-05-04 03:53
If this can't even be disabled as an internal extension, which I doubt it is, then it's a _major_ issue. No surprise by the confusion made at the the beginning of the VS Code _product_ (not project) regarding licensing (which you mentioned in your toot).

VS Code is my Tool of the Trade, but unfortunately if I have to fork and let aside my current projets, I won't get any happier.

**Comment by darshanrampatel** [comment] 2018-05-04 14:05
Duplicate of #44294

**Comment by roblourens** [comment] 2018-05-04 16:16
Yes, it can be disabled with `"workbench.settings.enableNaturalLanguageSearch": false`

**Comment by marmistrz** [comment] 2018-05-04 18:17
This should definitely be an opt-in!

**Comment by roblourens** [comment] 2018-09-13 01:37
We've tried to address this and other similar issues by making it easier to find settings that control features that involve online features. You can use the `...` menu in the settings UI to find the "Show settings for online services" menu, which will filter the settings list to just those settings.

![image](https://user-images.githubusercontent.com/323878/45461905-4f92e780-b6ba-11e8-8102-6703f7d68f5c.png)

There was some discussion of this here https://github.com/Microsoft/vscode/issues/54354

**Closed by roblourens** 2018-09-13 01:37 UTC
Labels: search, under-discussion

**Comment by sneq0** [comment] 2018-09-13 11:42
Awful, removing it asap

**Comment by roblourens** [comment] 2018-09-13 16:30
To reiterate,

> it can be disabled with "workbench.settings.enableNaturalLanguageSearch": false

**Comment by marmistrz** [comment] 2018-09-13 16:58
How about adding some notification, banner, etc. that such settings exist, and unless changed, data may be sent to Microsoft servers?

That's exactly what Mozilla Firefox does, see its first-run behavior for clarification
