### ISSUE TITLE
Add the ability to choose the user files folder

### ISSUE THREAD

**Issue by Ejoz-geek** [Microsoft/vscode#25017] opened 2017-04-19 13:50 UTC
Please  Add the ability to choose the user files folder

- VSCode Version: 1.11.2
- OS Version: win7 ultimate

Steps to Reproduce:

1.Add the ability to choose the user files folder.
Now it C:\Users\{USERNAME}

**Comment by Ejoz-geek** [comment] 2017-04-19 14:03
P.S.  C:\Users{USERNAME}\AppData\Roaming\Code

**Comment by mjbvz** [comment] 2017-04-19 20:56
Do you mean the folder where user data and extensions are stored?

If so, take a look at the `--user-data-dir` and `--extensions-dir` command line flags. Issue #329 may also be of interest

**Comment by Ejoz-geek** [comment] 2017-04-20 11:52
Please explain more

**Comment by Ejoz-geek** [comment] 2017-04-20 11:54
You understand me correctly

**Comment by mjbvz** [comment] 2017-04-24 18:32
Ok, closing as fixed / duplicate of #329

**Closed by mjbvz** 2017-04-24 18:32 UTC
Labels: needs more info
