### ISSUE TITLE
Undo stack wiped when node debugging

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/vscode#10563] opened 2016-08-15 23:25 UTC
- VSCode Version: 1.3.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Make code change (e.g. var uselessString = "";)
2. Run node debugger (e.g. node --debug-brk app.js;)
3. Stop debugger
4. Attempt to undo 

Apologies if this is considered a repeat of #2908. I'm not sure why debugging would be changing the file outside VS Code

**Comment by alexandrudima** [comment] 2016-08-16 06:55
@ryanvolum Can you help us out and provide more exact steps (preferably the two files `app.js` and `launch.json` so we can reproduce and figure out what exactly is happening and if it is the same as #2908 (file changes on disk). I think the node version would also help.

**Comment by bpasero** [comment] 2016-08-26 10:49
This could be https://github.com/Microsoft/vscode/issues/10932

**Comment by dbaeumer** [comment] 2016-08-30 09:19
Closing since no reply has been received in 2 weeks. @ryanvolum pls ping with steps if you can still reproduce the issue.

**Closed by dbaeumer** 2016-08-30 09:19 UTC
Labels: needs more info

**Comment by stefanpatatu** [comment] 2016-09-13 11:18
I can confirm some version of this bug still exists as of v1.4.0. The bug mostly manifests after I save a file (work on file, CTRL+S, webpack rebuilds (dev-server usually, node v6.5.0), check browser, see everything is broken, realize I have a typo or something, ALT+TAB, then CTRL+Z no longer works). It also manifests randomly (not after file save) sometimes, but especially after CTRL+S-ing.

**Comment by dbaeumer** [comment] 2016-09-13 14:53
@stefanpatatu can you please open a new issue with steps to reproduce it. Best would be a git repository we could clone from. The better the steps are the most likely it is that we can reproduce and fix.
