### ISSUE TITLE
Not responding issue

### ISSUE THREAD

**Issue by sreejith163** [microsoft/vscode#98946] opened 2020-06-01 09:29 UTC
Issue Type: <b>Bug</b>
![Capture](https://user-images.githubusercontent.com/44645054/83395779-88d43380-a418-11ea-897d-a59b885151ad.PNG)

After upgrading windows to new version 2004, VS code is giving not responding issue. 
Tried clearing cachae and unistall, it didn't help.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.96GB free)|
|Process Argv|--folder-uri file:///d%3A/Projects/acr_assist_marval_client|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
vscode-npm-script|eg2|0.3.12
vscode-npm|fkn|3.3.0
beautify|Hoo|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8

</details>

**Comment by joaomoreno** [comment] 2020-06-02 09:23
Does it work if you completely reinstall VS Code?

**Comment by joaomoreno** [comment] 2020-06-02 09:23
@bpasero @deepak1556 Is Windows NT still supported?

**Comment by bpasero** [comment] 2020-06-02 09:31
@joaomoreno the list is here https://code.visualstudio.com/docs/supporting/requirements#_platforms but I think this is just a normal Windows 10 updated to the new 2004 release?

**Comment by sreejith163** [comment] 2020-06-02 09:47
> Does it work if you completely reinstall VS Code?

No, i did it.

**Comment by sreejith163** [comment] 2020-06-02 09:48
> Does it work if you completely reinstall VS Code?

I was using vs code from last 2 years. Problem happened after the new feature update

**Comment by joaomoreno** [comment] 2020-06-02 13:52
Does the issue reproduce if you run with `code --disable-extensions`?

Is there any error in the `Developer: Toggle Developer Tools`? Is there any error when running `code --verbose`?

**Comment by sreejith163** [comment] 2020-06-03 07:30
> Does the issue reproduce if you run with `code --disable-extensions`?
> 
> Is there any error in the `Developer: Toggle Developer Tools`? Is there any error when running `code --verbose`?

yes, its happening even after running with `code --disable-extensions`.
Console in `Developer: Toggle Developer Tools` is empty

**Comment by bpasero** [comment] 2020-06-03 07:34
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sreejith163** [comment] 2020-06-03 08:04
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Yes, still there..

**Comment by bpasero** [comment] 2020-06-03 08:25
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Please use this version. Thanks!

**Comment by sreejith163** [comment] 2020-06-04 06:03
> Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Please use this version. Thanks!


Please find the attached file
[Code - Insiders Crashes.zip](https://github.com/microsoft/vscode/files/4727836/Code.-.Insiders.Crashes.zip)

**Comment by bpasero** [comment] 2020-06-04 06:07
Ok thanks, unfortunately it does not look like a crash dump is actually produced.

**Comment by sreejith163** [comment] 2020-06-05 08:27
> Ok thanks, unfortunately it does not look like a crash dump is actually produced.

Now i am getting issue only few times with vs code insiders edition,
Don't know how it got solved.

**Comment by deepak1556** [comment] 2020-06-09 21:02
@sreejith163 download https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer , once you see the not responding error right click on the code process > Create Dump > Create Full Dump... , you will see many code process, take the process dump from all of them and attach here. Thanks!


![Screenshot (1)](https://user-images.githubusercontent.com/964386/84199337-d7598180-aa59-11ea-899d-45f30f37a293.png)

**Comment by sreejith163** [comment] 2020-06-11 12:48
> @sreejith163 download https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer , once you see the not responding error right click on the code process > Create Dump > Create Full Dump... , you will see many code process, take the process dump from all of them and attach here. Thanks!
> 
> ![Screenshot (1)](https://user-images.githubusercontent.com/964386/84199337-d7598180-aa59-11ea-899d-45f30f37a293.png)

Please find the attached file

**Comment by sreejith163** [comment] 2020-06-11 12:51
> > @sreejith163 download https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer , once you see the not responding error right click on the code process > Create Dump > Create Full Dump... , you will see many code process, take the process dump from all of them and attach here. Thanks!
> > ![Screenshot (1)](https://user-images.githubusercontent.com/964386/84199337-d7598180-aa59-11ea-899d-45f30f37a293.png)
> 
> Please find the attached file

Its around 330 mb. Even after compressing it is around 124mb

**Comment by deepak1556** [comment] 2020-06-11 20:21
In the process explorer when you hover over the code process, it will display the command line arguments of the process, look for the process with `--type=renderer` and `Create Dump -> Create Minidump...`, it should be fine uploading the compressed zip on github.

**Comment by sreejith163** [comment] 2020-06-12 13:48
> In the process explorer when you hover over the code process, it will display the command line arguments of the process, look for the process with `--type=renderer` and `Create Dump -> Create Minidump...`, it should be fine uploading the compressed zip on github.

Please find the attached file
[Code - Insiders (2).zip](https://github.com/microsoft/vscode/files/4771122/Code.-.Insiders.2.zip)

**Comment by deepak1556** [comment] 2020-06-25 07:24
Thanks for providing the minidump. Can you try the latest insiders version and if the issue still happens please create another minidump.

**Comment by sreejith163** [comment] 2020-06-26 07:23
> Thanks for providing the minidump. Can you try the latest insiders version and if the issue still happens please create another minidump.

Still there.. Now its coming most of the times
[Code - Insiders.zip](https://github.com/microsoft/vscode/files/4835590/Code.-.Insiders.zip)

**Comment by sreejith163** [comment] 2020-06-26 07:28
![Annotation 2020-06-26 125720](https://user-images.githubusercontent.com/44645054/85831870-9d53e380-b7ac-11ea-899b-103f2f494864.jpg)

I can see more process running under vscode, when checked in task manager

**Comment by deepak1556** [comment] 2020-06-26 07:32
Can you take a dump of the process with higher CPU usage, run with `--disable-extensions` to neglect extension specific processes.

**Comment by sreejith163** [comment] 2020-06-26 09:08
[Code - Insiders.zip](https://github.com/microsoft/vscode/files/4836019/Code.-.Insiders.zip)
Please find the attached file
![Annotation 2020-06-26 143753](https://user-images.githubusercontent.com/44645054/85840787-b4013700-b7ba-11ea-942b-71ac884ab249.jpg)

**Comment by deepak1556** [comment] 2020-06-26 23:09
Thanks for the dumps, windbg is rejecting the dumps because of mismatched image headers. Which version of vscode insiders did you take the dump from ? `code-insiders --version` should give the info.

Also can you attach the insiders executable you have installed under `C:\Program Files\Microsoft VS Code Insiders`

**Comment by sreejith163** [comment] 2020-06-29 06:12
> code-insiders --version

![Test](https://user-images.githubusercontent.com/44645054/85979123-97087600-b9fd-11ea-8d54-bb20606882f0.jpg)

Executable files are of large size

**Comment by pilcherd** [comment] 2020-07-27 16:04
Did a fix for this get integrated into insider builds? I see "needs more info" tag was removed.  I'm experiencing frequent not responding hangs on 2004 too.

**Comment by deepak1556** [comment] 2020-07-27 16:55
@sreejith163 @pilcherd do you see the freeze with latest insiders ?

**Comment by pilcherd** [comment] 2020-07-29 19:51
> @sreejith163 @pilcherd do you see the freeze with latest insiders ?

I've not tried that. Is there a fix to test in the insider build?  (not seeing a commit reference)

**Comment by deepak1556** [comment] 2020-07-29 21:01
the insiders has been updated to a newer runtime Electron 9.1.0 since this issue was filed, if the issue still happens we can further investigate. Previous investigation with the dump didn't move much because of https://github.com/microsoft/vscode/issues/98946#issuecomment-650443385

**Comment by pilcherd** [comment] 2020-07-29 22:39
@deepak1556 I will try the insiders and let you know. It happens all the time so should be quick to see a difference.

**Comment by sreejith163** [comment] 2020-07-30 04:22
> Did a fix for this get integrated into insider builds? I see "needs more info" tag was removed. I'm experiencing frequent not responding hangs on 2004 too.

The issue is resolved now. I dont get any issue from past few weeks

**Comment by sreejith163** [comment] 2020-08-03 11:45
After updating to version "1.48.0", not responding issue came up. Its hanging everytime.

**Comment by deepak1556** [comment] 2020-08-06 00:50
Sorry about that, we reverted the runtime in master back to Electron 7.

Can you try the exploration build that has a newer runtime https://az764295.vo.msecnd.net/exploration/f0e1fbf4cb8c4c27d6290f0310f5a4d63597cd21/VSCodeUserSetup-x64-1.48.0-exploration.exe

**Comment by pilcherd** [comment] 2020-08-06 02:12
@deepak1556 I'm on the insiders @ 1.48.0 and having no issues, so whatever my issue was must be fixed more generally in the insider builds and not be an electron-based fix.

**Comment by deepak1556** [comment] 2020-08-06 02:15
Thanks for confirming @pilcherd

**Comment by squallstar** [comment] 2020-08-11 12:26
I'm still having this issue every time I try to debug and set breakpoints in a Node.js app. I am using VSCode version 1.47.3 and Windows 10 Pro Version 20H2 (19042.423).

**Comment by deepak1556** [comment] 2020-08-28 20:57
Electron 9 will be available in upcoming stable, closing this.

**Closed by deepak1556** 2020-08-28 20:57 UTC
Labels: fixed-in-electron-9, freeze-slow-crash-leak, windows
