### ISSUE TITLE
Local history timeline entries have incorrect timestamp

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#153730] opened 2022-06-29 17:52 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1/69-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Open user settings.json file in github.dev/microsoft/vscode
2. Open timeline view
3. :bug: see timeline entries from 52 years ago

![image](https://user-images.githubusercontent.com/30305945/176503167-ee2bc4c5-1444-4913-ac14-9181714fbbc0.png)

**Comment by bpasero** [comment] 2022-06-30 04:47
Is this reproducible or a one-off?

**Comment by bpasero** [comment] 2022-07-02 04:51
Looks like the file system provider that is implemented for `vscode-userdata` is not implementing `mtime` properly, I see a value of `4`:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/900690/176986978-2f40c7a2-1d6b-4ae6-bb59-67f92e414727.png">

Moving to @sandy081

**Closed** 2022-07-04 14:35 UTC
Labels: bug, config, web
