### ISSUE TITLE
we are unable to connect marketplace vscode error 

### ISSUE THREAD

**Issue by ddey7** [microsoft/vscode#129879] opened 2021-07-31 04:04 UTC
Does this issue occur when all extensions are disabled?: Yes/No

I cant even download extension

- VS Code Version:
- OS Version:

we are unable to connect marketplace vscode error .  i an dacing this error since last 1yr

**Comment by gjsjohnmurray** [comment] 2021-07-31 05:04
/needsMoreInfo but if you are on certain flavours of Linux (Arch, Manjaro) then the issue is that the distribution modifies VS Code to go to Open VSX for its extensions instead of the Microsoft Marketplace, and doing that produces a CORS failure. Try searching on some of these terms for duplicate issues here, or ask on places where you get support for the distro you're running.

**Comment by maoxuner** [comment] 2021-08-04 05:11
> /needsMoreInfo but if you are on certain flavours of Linux (Arch, Manjaro) then the issue is that the distribution modifies VS Code to go to Open VSX for its extensions instead of the Microsoft Marketplace, and doing that produces a CORS failure. Try searching on some of these terms for duplicate issues here, or ask on places where you get support for the distro you're running.

That's it. I'm using archlinux oss-code.

**Comment by gjsjohnmurray** [comment] 2021-08-04 06:46
Please close this issue.

**Closed** 2021-08-11 11:24 UTC
Labels: needs more info
