### ISSUE TITLE
vscode is claiming that NPM is not in PATH on Linux, but it _is_ in my PATH

### ISSUE THREAD

**Issue by TheChuckster** [Microsoft/vscode#27783] opened 2017-05-31 20:44 UTC
- VSCode Version: 1.12.2
- OS Version: Linux

Steps to Reproduce:

1. Use VSCode to edit JS code on Linux
2. Get this error: "Could not install typings files for JavaScript language features. Please ensure that NPM is installed and is in your PATH"

`npm` IS in my `PATH`:

```
$ which npm
/usr/local/bin/npm
```

I even symlinked the `npm` binary into `/usr/bin` -- did not help. We really need type intellisense to work in VSCode with JS to help prevent careless mistakes in our code.

**Comment by mjbvz** [comment] 2017-05-31 21:59
This is a duplicate of #24961

See [this comment](https://github.com/Microsoft/vscode/issues/24961#issuecomment-305040579) for the workaround we have planned for VSCode 1.13. In the current insiders build, you should be able to set `"typescript.npm"` to point to where you have npm installed to fix this issue

**Closed by mjbvz** 2017-05-31 21:59 UTC
Labels: duplicate
