### ISSUE TITLE
Debug viewlet sizes reset after debug session

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35600] opened 2017-10-04 22:44 UTC
I always have to resize the call stack because it takes up 3/4 of the sidebar. Then its position resets when debugging stops

![oct-04-2017 15-41-55](https://user-images.githubusercontent.com/323878/31203143-9dc09c30-a91a-11e7-8e9b-dfcac47080fd.gif)

**Comment by isidorn** [comment] 2017-10-05 09:01
The position is reseting because a contributed view (loaded scripts) is appearing while debug session is on. I see here two issues
1. The sizes of split views should be preserved if a view is added or removed @sandy081 
2. Loaded scritps views is too agressive and I have to ide it per workspace. Surely we need a way to hide it for all workspaces and imho it should not be shown by default as it is only bringing clutter @weinand 

Assigning to October for discussion.

**Comment by weinand** [comment] 2017-10-25 09:13
@sandy081 it is a bug that the proportions of split views are not preserved if one view changes its visibility (the loaded scripts explorer is **not** added or removed).

**Comment by sandy081** [comment] 2017-10-25 09:58
Easy way to reproduce this 

![kapture 2017-10-25 at 11 57 51](https://user-images.githubusercontent.com/10746682/31992868-ceb718b6-b97b-11e7-89ac-efee7e923e2b.gif)

**Comment by sandy081** [comment] 2017-10-25 10:13
I think above issue is different to this. Hence filed a new one for that/

**Closed** 2017-10-26 09:40 UTC
Labels: bug, debug
