### ISSUE TITLE
The editor leaves empty space above the first line when the search panel is displayed

### ISSUE THREAD

**Issue by gozzoo** [Microsoft/vscode#34875] opened 2017-09-23 09:25 UTC
- VSCode Version: 1.16,1
- OS Version: Windows

Steps to Reproduce: uknown

After I use VSCode for a while sometimes I notice that the editor leaves some empty space above the first line. It happens in all open editors and those I open next.

![image](https://user-images.githubusercontent.com/296970/30771886-e26012b8-a059-11e7-8b26-acc69bc8c3b6.png)

After I restart VSCode everything is back to normal

Reproduces without extensions: Yes/No

**Comment by innerlee** [comment] 2017-09-23 11:04
Are you searching for something when this happens?

**Comment by gozzoo** [comment] 2017-09-23 12:23
Yes, now I tested again and it seems it happens when the search panel is displayed. When it is in replace mode it pushes the text further down:

![image](https://user-images.githubusercontent.com/296970/30773119-e8e3a078-a072-11e7-8ca6-88816f20c8cf.png)

I don't know if this is by design or just a sied effect but it's very weird.

**Comment by yume-chan** [comment] 2017-09-24 13:07
It's by design.

It's introduced in 1.13, here is the [changelog](https://code.visualstudio.com/updates/v1_13#_find-widget).

**Comment by gozzoo** [comment] 2017-09-24 14:32
Is there any setting to switch off this behaviour? Even on a laotop the editor is big enough so that the search panel doesn't cover any of the source code I'm working on.

**Comment by eliashdezr** [comment] 2017-10-03 16:18
I reported the same:
https://github.com/Microsoft/vscode/issues/34495

Would be nice to be able to turn this off.

**Comment by rebornix** [comment] 2017-11-16 23:44
Close this as it's dup of #34495, thanks everyone for your info.

**Closed by rebornix** 2017-11-16 23:44 UTC
Labels: duplicate, editor, editor-find-widget
