### ISSUE TITLE
Goto symbol no longer works with AMD or module pattern with Salsa

### ISSUE THREAD

**Issue by tomi** [Microsoft/vscode#3768] opened 2016-03-07 11:06 UTC
I am testing the latest VS Code insiders build (Version 0.10.10-insider (0.10.10-insider)). With the introduction of the new Salsa JS language service, "Goto symbol" no longer works for JS files with old module pattern (anonymous closure) or with AMD modules. I understand that, as documented, Salsa can't resolve AMD references, but it should recognise the symbols inside the file.

Here's an example how it works in the latest stable build:

![screen shot 2016-03-07 at 12 57 55](https://cloud.githubusercontent.com/assets/10324676/13567580/b645f394-e464-11e5-9499-801bb63e52ec.png)

and here's with Salsa:

![screen shot 2016-03-07 at 12 57 37](https://cloud.githubusercontent.com/assets/10324676/13567577/b413af4e-e464-11e5-8607-a3e1f3225c5c.png)

**Comment by egamma** [comment] 2016-03-07 12:58
This is a duplicate of microsoft/typescript#7134

**Closed** 2016-03-07 12:58 UTC
