### ISSUE TITLE
[Feature request] Auto-hide to terminal on focus lost

### ISSUE THREAD

**Issue by azydevelopment** [Microsoft/vscode#32014] opened 2017-08-04 06:26 UTC
Feature request to enable auto-hide terminal (or technically, the bottom window that has the terminal) feature similar to regular Visual Studio.

Bottom window has a few states it seems:
- minimized
- visible
- expanded (almost filling the main view)

This is a feature request to add a bit that indicates whether that bottom window goes back to the minimized state whenever focus is lost (clicked in some other part of vscode or something)

**Comment by aluanhaddad** [comment] 2017-08-08 18:56
This would be great. I use the terminal to run tests and would find this very useful.

**Comment by Tyriar** [comment] 2017-08-14 21:37
Duplicate of https://github.com/Microsoft/vscode/issues/10952

**Closed by Tyriar** 2017-08-14 21:37 UTC
Labels: integrated-terminal
