### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SanyeGit** [Microsoft/vscode#60268] opened 2018-10-09 09:07 UTC
- Extension Name: emmet
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.15063
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by egamma** [comment] 2018-10-09 10:32
duplicate of #60269

**Closed by egamma** 2018-10-09 10:32 UTC
Labels: new release
