### ISSUE TITLE
Support for JavaScript coming from script tags in HTML

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#96982] opened 2020-05-05 11:50 UTC
I apologize if this issue has already been addressed, but I couldn't find an answer to this searching on vscode's github or google.

Are there any plans to provide support for JavaScript coming from script tags in HTML?

In the meanwhile is there any extension that does this? I couldn't find any.

**Comment by andrecasal** [comment] 2020-05-05 11:52
The issue suggested is not a duplicate.

**Comment by aeschli** [comment] 2020-05-05 19:35
We already have language support for JavaScript in HTML script tags. You get code assist, hovers, validation. What are you looking for?
If it's not working for you, please attach a small code example and describe what you see and what you are expecting.  Additionally a screenshot is helpful too (but please paste the sample code as well!)

**Comment by andrecasal** [comment] 2020-05-06 11:56
Thanks for the reply @aeschli.

Here's what I'm doing:
1. Copy the following to a main.js file.
```
function test() {
	console.log("Testing");
}
```
2. Copy the following to an HTML file in the same folder.
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Document</title>
		<script src="main.js"></script>
	</head>
	<body>
		<script>
			tes...
		</script>
	</body>
</html>
```
3. Notice `tes` doesn't intellisense the `test()` function that's on the `main.js` file.

**Comment by aeschli** [comment] 2020-05-07 09:42
Thanks, now I understand.
That's a duplicate of #26338

**Closed by aeschli** 2020-05-07 09:42 UTC
Labels: needs more info

**Comment by andrecasal** [comment] 2020-05-07 12:34
Ok, thanks! 👍
