### ISSUE TITLE
Make IntelliSense type information clickable

### ISSUE THREAD

**Issue by alexchandel** [microsoft/vscode#122962] opened 2021-05-04 22:03 UTC
When you hover over a variable, VSCode shows type information:

![Screen Shot 2021-05-04 at 4 43 29 PM](https://user-images.githubusercontent.com/637714/117075049-cfea3900-acf9-11eb-99d2-a33bd15bcb18.jpg)
![Screen Shot 2021-05-04 at 4 47 33 PM](https://user-images.githubusercontent.com/637714/117075056-d24c9300-acf9-11eb-95e7-912c588d03b7.jpg)

Although this text is selectable, it is not linked.  Ctrl-clicking `Theme` or `ClassNameMap` does nothing, unlike Ctrl-clicking `Theme` or `ClassNameMap` within the body of a file, which opens their definitions.

Please link up these type information tooltips, so the types can be Ctrl-Clicked.  Often the types one needs to find are deeply buried in unknown reaches of the code, and they aren't always directly referenced in a file.

**Comment by mjbvz** [comment] 2021-05-06 01:15
Duplicate of #75439

**Closed by mjbvz** 2021-05-06 01:15 UTC
