### ISSUE TITLE
'CTRL+P' vs 'File Explorer Sidebar' for opening files.

### ISSUE THREAD

**Issue by JokerDan** [Microsoft/vscode#45595] opened 2018-03-12 14:57 UTC
Two issues found surrounding the opening of files in the palette vs the file explorer.

- VSCode Version: 
Insider Build;
![image](https://user-images.githubusercontent.com/1098786/37290315-cd2317b2-2603-11e8-8dd8-d8400bd61fde.png)

- OS Version:
![image](https://user-images.githubusercontent.com/1098786/37290256-b0ec3056-2603-11e8-80a5-fbfb40ee840a.png)

Steps to Reproduce:

1. CTRL+P
2. Search for file in workspace
3. Open file
4. Open the same file via File explorer
5. Right click tab >> Reveal in side-bar
5a. Only file opened via file explorer works.
5b. Two instances of the same file opened.

Does this issue occur when all extensions are disabled?: Yes

There is some interesting behaviour surrounding the opening of files with the two different methods.

- The 'Right Click Tab >> Reveal in sidebar' command does not work with files opened via the palette.
- Opening a file in the palette, and then again via the side bar will open two documents within the same instance of VSCode pointing to the same file. (Editing one and saving shows in the other, file path is the same, etc.)

I understand the reveal in sidebar not working as there is no element/node:id from the file explorer being stored when the file is opened with the command palette, but the separate documents, could you not just do a quick cycle through all of the open documents looking at their uri.fspath prior to opening, and just switch tab if its already open via either method of attempted file opening?

**Comment by bpasero** [comment] 2018-03-12 15:05
@JokerDan whats the location of that file, is it directly under root?

**Comment by JokerDan** [comment] 2018-03-12 15:13
@bpasero No it is not.

Current workspace folders are as such; (Folder names changed due to company policy, hopefully you still get the gist of it)

```
  "folders": [
    {
      "name": "Product Line 1",
      "path": "C:\\FolderL1\\FolderL2\\ProductLine1\\"
    },
    {
      "name": "Product Line 2",
      "path": "C:\\FolderL1\\FolderL2\\ProductLine2\\"
    },
    {
      "name": "Product Line 3",
      "path": "C:\\FolderL1\\FolderL2\\ProductLine3\\"
    },
    {
      "name": "Product Line 4",
      "path": "C:\\FolderL1\\FolderL2\\ProductLine4\\"
    }
  ],
```

Files in question are in directories such as `C:\FolderL1\FolderL2\ProductLine1\Country\ic\productName` or `C:\FolderL1\FolderL2\ProductLine2\Country\include\subfolder1\fileName`

**Comment by bpasero** [comment] 2018-03-12 16:26
@roblourens @chrmarti I suspect another case where the file path does not match with the explorer casing (again the drive letter maybe?)

**Comment by roblourens** [comment] 2018-03-14 23:15
Probably a dupe of https://github.com/Microsoft/vscode/issues/45141, I suspect that the trailing slashes in your workspace folders will trigger it. See if it works when you remove those?

Left a comment on that issue, take a look.

**Comment by JokerDan** [comment] 2018-03-15 11:45
@roblourens 
Removing the trailing '\\' from the path in my workspace settings for all directories has indeed solved both of the aforementioned issues.

----

I have a follow up, slightly unrelated as it is to do with extensions, but still surrounding the 'Reveal In Side Bar' functionality.

I have an extension that I have written (for an in-house closed source language) which gets all of the 'included' files with syntax such as `include "path.to.includeFile"` and displays them in a treeView as treeViewItems, going into each file, getting their includes and branching down.

My class for the items extends TreeItem and has an additional constructor argument of 'filePath' (absolute path). I use this on a treeView context menu and document context menu command that runs the following function, passing in the stored absolute path or the selected text. (I handle any possible errors prior to opening calling the function, its a pretty predictable syntax/casebase/filepaths, creating the file if it does not exist).

```
function openFile(absFilePath) {
  vscode.workspace.openTextDocument(absFilePath).then((doc) => {
    vscode.window.showTextDocument(doc);
  });
}
exports.openFile = openFile;
```

However, when opening a file this way, right clicking the tab and revealing in explorer works, but not 'Reveal In Side Bar'. What would you recommend doing to get the in-built 'Reveal in Side Bar' command to work?

**Comment by roblourens** [comment] 2018-03-22 06:31
@JokerDan assuming it isn't related to this same issue with the slash, then double check that the path is exactly the same when you call showTextDocument, as it is if you open it from the sidebar yourself. Please open a new issue for it.

**Closed by roblourens** 2018-03-22 06:31 UTC
Labels: search
