### ISSUE TITLE
White pixels

### ISSUE THREAD

**Issue by xxkracklexx** [microsoft/vscode#93644] opened 2020-03-28 10:38 UTC
![download (16)](https://user-images.githubusercontent.com/45408414/77821213-63444a00-70b6-11ea-9f7a-5640127f6106.png)

- VSCode Version: 1.43
- OS Version: Windows

Steps to Reproduce:

1.

2.

Does this issue occur when all extensions are disabled?: Yes

My Specs
Ryzen 7 2700x
 Nvidia geforce gtx 1080
16gb of ram

![yV5asFegQ_izGO9G9-sGUw](https://user-images.githubusercontent.com/45408414/77821272-d8178400-70b6-11ea-819d-dbcbd9293877.png)

**Comment by IllusionMH** [comment] 2020-03-28 11:17
/duplicate of #93356

See for more details and current solution https://github.com/microsoft/vscode/issues/93356#issuecomment-604657278

**Closed** 2020-03-28 11:18 UTC
Labels: *duplicate
