### ISSUE TITLE
DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed

### ISSUE THREAD

**Issue by actarian** [Microsoft/vscode#67945] opened 2019-02-05 21:36 UTC
Issue Type: <b>Bug</b>

(glsl-canvas) When loading local content video in a WebViewPanel created with the vscode Extension Api I get this error message on the debug panel:

MediaError {code: 4, message: "DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed"}

video.src url is correctly loaded through the resource scheme vscode-resource:/

maybe bug is related with the electron chromium version.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|-psn_0_6288895|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
language-maxscript|ate|1.8.3
glsl-canvas|cir|0.2.2
jshint|dba|0.10.20
vscode-eslint|dba|1.8.0
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.3
emoji-code|idl|0.7.2
vscode-language-pack-it|MS-|1.30.2
material-icon-theme|PKi|3.6.2
polacode|pnp|0.2.2
quicktype|qui|12.0.46
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.4
shader|sle|1.1.4

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-02-06 00:05
Duplicate of #54097

We don't ship with ffmpeg so many common audio and video formats are not fully supported

**Closed by mjbvz** 2019-02-06 00:05 UTC

**Comment by actarian** [comment] 2019-02-06 19:37
@mjbvz unfortunately I've tried all the video formats and codecs and all give the same error. so as of today it's not possible to run extensions in vscode that run html video or audio elements.
