### ISSUE TITLE
[terminal] Support Ctrl+C/Ctrl+V shortcuts

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9746] opened 2016-07-26 08:31 UTC
Testing #9723:

With copy/paste in the context menu, I expect also the copy/paste shortcuts to work.
I suggest to copy if there is a selection and send the Ctrl-C sequence to the terminal if there is no selection.

**Comment by Tyriar** [comment] 2016-07-27 18:59
Duplicate of https://github.com/Microsoft/vscode/issues/8818

**Closed by Tyriar** 2016-07-27 18:59 UTC
