### ISSUE TITLE
Split terminal doesn't work

### ISSUE THREAD

**Issue by javid-abd** [Microsoft/vscode#69583] opened 2019-02-28 08:02 UTC
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
OS: Linux x64 4.15.0-29deepin-generic

Does this issue occur when all extensions are disabled?: Yes

I can't split my terminal by clicking Split Terminal icon on terminal. When I click nothing happens. Instead I click new terminal icon, choose from drop-down menu and switch the other terminal which is not so handy.

**Comment by Tyriar** [comment] 2019-03-01 00:28
@javid-abd are there any errors in the console (Help > Toggle Developer Tools) when you try split? How wide is the terminal you're trying to split?

**Comment by javid-abd** [comment] 2019-03-01 05:45
there's no error in the console while clicking split terminal. It looks like the icon is just an UI element with no further functionalities. All I want is to have an equal terminal.

**Comment by Tyriar** [comment] 2019-03-01 19:06
@javid-abd how wide is the terminal when you're trying to split? Can you show a screenshot of the terminal immediately after it failed to split?

**Comment by javid-abd** [comment] 2019-03-01 19:31
recorded

![splitterminal](https://user-images.githubusercontent.com/32272345/53661568-0ccdc780-3c7a-11e9-9be2-a776723bc536.gif)

**Comment by nearwood** [comment] 2019-03-01 20:12
There's an older issue that this is a duplicate of: #69273, but it's less popular and mentions a fix: Install `lsof` or add `initial` to options (not sure what that means).

Can confirm installing `lsof` works.

Version: v1.31.1 (and v1.31.0)
Commit: 1b8e8302
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.8-arch1-1-ARCH

**Comment by javid-abd** [comment] 2019-03-01 20:20
Thanks for help, it worked. Not sure I should close the issue, because it was solved by installing third-party dependency

**Comment by Tyriar** [comment] 2019-03-02 17:03
@nearwood thanks for finding this! We should fallback to `_initialCwd` when `lsof` doesn't exist here:

https://github.com/Microsoft/vscode/blob/622b3d62dd92ea1bcdc7d250e0a7565b018edcee/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L206

**Closed** 2019-03-04 23:44 UTC
Labels: bug, good first issue, help wanted, integrated-terminal
