### ISSUE TITLE
Highlight changed files in a Git repo when folder is open in the Explorer view

### ISSUE THREAD

**Issue by dend** [Microsoft/vscode#9454] opened 2016-07-18 20:04 UTC
- VSCode Version: any
- OS Version: any

If you open a folder in the Explorer view, and the folder is part of a Git repo, highlight files that have changes that are uncommitted. Atom Editor does that today and it adds tremendous value to the workflow.

**Comment by squillace** [comment] 2016-07-18 20:43
Hey @dend, you'll have to explain why the git view, which does exactly this, is insufficient, wouldn't you? I like your idea, but I use git view mostly, not explorer view.

**Comment by dend** [comment] 2016-07-18 20:50
It's not the Git view, it's the explorer view. Atom does this today for highlights of changed files among other files:

<img width="663" alt="capture3" src="https://cloud.githubusercontent.com/assets/1389609/16929895/a39a9752-4cee-11e6-8791-d6c459d22a97.PNG">

**Comment by squillace** [comment] 2016-07-18 21:02
No, I KNOW it's not git view, but that's what git view **does**, so you just want the ability to merge the two views?

**Comment by dend** [comment] 2016-07-19 17:22
@squillace Git view doesn't show all the files, though - just the modified ones.

**Comment by joaomoreno** [comment] 2016-07-21 06:34
Duplicate of #178

**Closed by joaomoreno** 2016-07-21 06:34 UTC
Labels: git
