### ISSUE TITLE
Support "window.titleBarStyle": "custom-inset" setting

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30557] opened 2017-07-13 01:32 UTC
Electron supports another titlebar style called `hiddenInset` ([more about it)](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#hiddeninset).

We currently use the `hidden` style when setting `"window.titleBarStyle": "custom"`, therefor I think we should map `"window.titleBarStyle": "custom-inset"` to `hiddenInset`.

The only use case I can think for this is that it enables to hack the interface into those mockups seen in #12377 (notice the semaphore perfectly lined up with the tabs) without needing to patch vsc itself, just with some CSS using [this extension](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css).

It should be trivial enough to implement, if you want I can help with that.

**Comment by Hypnoes** [comment] 2017-08-14 16:58
That is what I'm thinking! Use frameless window, we can draw a new title-bar, as it can be more customizable. /😄

**Comment by Hypnoes** [comment] 2017-08-14 16:58
That is what I'm thinking! Use frameless window, we can draw a new title-bar, as it can be more customizable. /😄

**Comment by bpasero** [comment] 2017-09-10 07:22
I would rather want us to support https://github.com/Microsoft/vscode/issues/12377 properly without having to use an extension that hacks our CSS. Just adding this new style and forcing users to change their CSS is not a good approach. Closing as duplicate of #12377

**Closed by bpasero** 2017-09-10 07:22 UTC
Labels: feature-request, workbench
