### ISSUE TITLE
Experimental Decorator error even after specifying in tsconfig.json 

### ISSUE THREAD

**Issue by rajeevkumarsharma** [Microsoft/vscode#1730] opened 2016-01-01 15:07 UTC
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noEmitOnError": false,
    "rootDir": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": false,
    "sourceRoot": "",
    "inlineSourceMap": false,
    "inlineSources": false
  },
  "files": [
    "app/app.ts"
  ]
}

It still show error on decorator class

**Comment by dbaeumer** [comment] 2016-01-05 10:23
This works for me using the latest 0.10.6 build. See attached screen shot:

![capture](https://cloud.githubusercontent.com/assets/1931590/12112703/9b69c2f4-b39e-11e5-8103-18c8e2fe45bf.png)

@rajeevkumarsharma pls ping me if you can reproduce using 0.10.6. Steps would be helpful as well.

**Comment by rajeevkumarsharma** [comment] 2016-01-07 06:43
Hi Dirk,

It still persist with 0.10.6 on Linux. Here are some screenshots attacked.

Thanks

![screenshot from 2016-01-07 12 06 20](https://cloud.githubusercontent.com/assets/8169482/12163955/9f7774c8-b537-11e5-9462-4fc0eacf05be.png)
![screenshot from 2016-01-07 12 06 35](https://cloud.githubusercontent.com/assets/8169482/12163956/9f7d5adc-b537-11e5-916e-7c9cb780dd8b.png)

**Comment by dbaeumer** [comment] 2016-01-07 09:00
Duplicates #1740

**Comment by dbaeumer** [comment] 2016-01-07 09:00
Closing

**Comment by mortefos** [comment] 2016-04-12 19:42
This happens to me everytime I add a new (angular 2) file to my project (i have alle the "correct" compiler options set), if i use the files options (which I prefer) instead of the exclude. Reopening vs code fixes the issue, but reopening the editor everytime i add a file is kind of a hassle.

i use vscode 0.10.11

**Comment by SergeySolonko** [comment] 2016-05-20 12:57
+1
Have same problem.

VScode Version 1.1.1 (1.1.1)
MacOS X El Capitan

**Comment by AdamWillden** [comment] 2016-05-20 14:48
I also get the same issue but it is inconsistent (1.1.1 Windows)

**Comment by Mosho1** [comment] 2016-05-22 10:58
+1, (1.1.1 on windows 10)

**Comment by dbaeumer** [comment] 2016-05-23 10:42
Moving to TS team since it still shows up on 1.1.1 which uses 1.8.9 (tsserver)

**Comment by dbaeumer** [comment] 2016-05-23 10:43
This issue was moved to Microsoft/TypeScript#8751

**Closed by dbaeumer** 2016-05-23 10:43 UTC
