### ISSUE TITLE
Issue with tab Indentation

### ISSUE THREAD

**Issue by himaanshu24** [Microsoft/vscode#35302] opened 2017-09-28 07:44 UTC
Not able to work efficiently on VScode since tab setting does not work properly. Even after multiple solutions applied by googling. Now becoming frustrated for such a small issue since every 2 min I have to apply setting using command palette. Please help me to resolve this issue.

Also, when using tab, the width of tab character increases and decreases affecting the indentation of the file, when the cursor is focused on the line.

- VSCode Version:
![image](https://user-images.githubusercontent.com/8476966/30954250-11b543d4-a44d-11e7-8cba-5082952103dd.png)

- OS Version:
![image](https://user-images.githubusercontent.com/8476966/30954281-323186f4-a44d-11e7-8f35-3935e216a8f6.png)

GIF for better understanding:
![vscode_tab_issue](https://user-images.githubusercontent.com/8476966/30954526-1b00a98c-a44e-11e7-96c0-3962f5e75fe6.gif)

![vscode_tab_issue2](https://user-images.githubusercontent.com/8476966/30954731-e17d446c-a44e-11e7-9dc8-dcd2e39dedab.gif)

Steps to Reproduce:

1. Set the tab related setting
2. Edit file and switch tab and come back to the previous tab

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-09-28 08:19
Duplicate of #32436

Workarounds until the fix is published:
* use a monospace font where the width of "→" equals that of a non-breaking space.
* disable render whitespace

**Closed by alexandrudima** 2017-09-28 08:19 UTC
Labels: editor, editor-core

**Comment by himaanshu24** [comment] 2017-09-28 08:27
Thanks, @alexandrudima for the quick response. The issue #32436  which you have pointed is about the width of the tab character. Which effectively cater to my second issue.

Can you also provide some link/issue for the first problem, in which indentation setting changes to "space" from "tab" when switching the files or restarting the VScode even after all setting is applied correctly.

Thanks Again.

**Comment by alexandrudima** [comment] 2017-09-28 08:40
The only reasonable explanation for that is that you are using an extension that changes the indentation settings of the editor instance. But you claim this reproduces without extensions, are you certain the indentation settings get changed when all extensions are disabled?
