### ISSUE TITLE
Keyboard layout inconsistency on Linux

### ISSUE THREAD

**Issue by Deleplace** [microsoft/vscode#126841] opened 2021-06-21 17:16 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Debian 5.10.28 x86_64 GNU/Linux

Steps to Reproduce:

1. Use a computer with a QWERTY (English (US)) keyboard
2. Plug a French AZERTY USB keyboard and select French layout
3. Type the letter A with the French AZERTY keyboard
4. As expected, the correct keyboard is used and an "a" shows up in the current editor
5. Hit the shortcut "Ctrl+A" with the French AZERTY keyboard to select all the text
6. This is incorrectly understood as "Ctrl+Q", which results in VSCode immediately shutting down

Likewise, "Ctrl+Q" is incorrectly recognized as "Ctrl+A".

Some other shortcuts (Ctrl+C, Ctrl+V, etc) work properly because theirs keys have the same position in the layouts QWERTY and AZERTY.

This is not a dupe of #23690 because the layout is correct when typing text, and incorrect when using keyboard shortcuts.

**Comment by alexdima** [comment] 2021-08-20 09:05
This is a duplicate of #23690. That is how #23690 manifests itself. Text input respects the select keyboard layout, while keyboard shortcuts do not. As a workaround you can try `"keyboard.dispatch": "keyCode"` or defining keyboard layout user independent keybindings (e.g. `cmd+[KeyA]`).

**Closed by alexdima** 2021-08-20 09:05 UTC
