### ISSUE TITLE
"Open in Terminal" not working on Fedora

### ISSUE THREAD

**Issue by Coder206** [Microsoft/vscode#4478] opened 2016-03-20 21:29 UTC
- VSCode Version: 0.10.11
- OS Version: Fedora 23 (64 Bit)

Steps to Reproduce:

1. Save work
2. Right click in the toolbar
3. Select "Open in Terminal"

**Comment by Tyriar** [comment] 2016-03-20 23:52
Reproduced. Sometimes it gives the error `spawn ENOTDIP`. It's happening because `x-terminal-emulator` is not in the `PATH` on Fedora.

**Comment by Tyriar** [comment] 2016-03-20 23:53
`x-terminal-emulator` is part of the Debian alternatives system which is why this doesn't work.

**Comment by pflannery** [comment] 2016-03-21 03:26
There is a PR https://github.com/Microsoft/vscode/pull/3495 that allows Linux users to specify a different terminal other than the hard coded `x-terminal-emulator` not sure whether it will be accepted or not though

**Comment by Tyriar** [comment] 2016-03-21 04:00
@pflannery thanks for pointing that out

**Comment by Coder206** [comment] 2016-03-21 19:04
Great thanks Tyriar :)

**Comment by Tyriar** [comment] 2016-04-18 20:57
#3495 fixes this issue, thanks again @pflannery

**Comment by aeschli** [comment] 2016-04-26 17:39
On my freshly installed Fedora 23 install I get the same error as above. That's with VSCode 1.0.1 (April release). Reopening...

**Comment by pflannery** [comment] 2016-04-26 20:05
Just did a fresh install of fedora 23 and it works for me. 
Did you have a workspace open?

This is the vscode version I tested with 

![image](https://cloud.githubusercontent.com/assets/1727302/14832505/8de8dcbc-0bf2-11e6-9402-8a641cd47024.png)

**Comment by aeschli** [comment] 2016-04-26 20:17
I'm on the latest build from today that we use for testing
The dev tools console shows: `shell.ts:415spawn x-terminal-emulator ENOENT: Error: spawn x-terminal-emulator ENOENT`.

```
[aeschli@localhost workspaces]$ which x-terminal-emulator 
/usr/bin/which: no x-terminal-emulator in (/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/home/aeschli/.local/bin:/home/aeschli/bin)
```

Is there anything I need to install or configure first?

**Comment by Tyriar** [comment] 2016-04-27 21:06
The code for that is here https://github.com/Microsoft/vscode/blob/849abd65ebf3e8c0f807e05639e723d16f8e6e3a/src/vs/workbench/parts/execution/electron-browser/terminal.ts#L9, it should yield gnome-terminal if it uses gnome (not sure if Fedora has other flavors). 

I created this to improve the defaults later though I expect it to work https://github.com/Microsoft/vscode/issues/5780

**Comment by Tyriar** [comment] 2016-05-14 02:13
Closing in favor of #5780

**Closed by Tyriar** 2016-05-14 02:13 UTC
Labels: bug, linux
