### ISSUE TITLE
"editor.findMatchHighlightBackground" takes priority over "editor.selectionBackground"

### ISSUE THREAD

**Issue by outofsync42** [microsoft/vscode#157118] opened 2022-08-04 17:32 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: 10 21H2

Steps to Reproduce:

Issue: I cannot see what I have selected with the mouse ("editor.selectionBackground") if it was already highlighted from it being found by CTRL+F search ("editor.findMatchHighlightBackground").

Reproduce: Double click any variable. Press CTRL-F to select to find that variable. All variables of that name are highlighted with the "editor.findMatchHighlightBackground" color. Intuitively if I were to then take the mouse and drag and select that same text with the mouse it should be highlighted with the "editor.selectionBackground" color but it is not. It still has the "editor.findMatchHighlightBackground" color.

Thank you

**Comment by ArturoDent** [comment] 2022-08-05 20:55
One way to fix this is to give the `findMatch` background less opacity.  For example,

`"editor.findMatchHighlightBackground": "#00c3ff30",`  // last two digits are opacity

Then whatever color you set (or none) for `editor.selectionBackground` will be much more obvious.

**Comment by rebornix** [comment] 2022-10-21 02:55
/duplicate of https://github.com/microsoft/vscode/issues/34105

**Closed by rebornix** 2022-10-21 02:55 UTC
Labels: editor-find, under-discussion
