### ISSUE TITLE
V1.9.0 completely broke my node debugging. F5 just does nothing now.

### ISSUE THREAD

**Issue by endevea** [Microsoft/vscode#19921] opened 2017-02-04 10:36 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.5|
|local-history|xyz|1.1.0|

---
This worked perfectly. Upgraded and it is broken. How do downgrade to the last version NOW?
Steps to Reproduce:

1. Launch.json:
```
{
	"version": "1.9.0",
	"configurations": [				
		{			 
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/startup.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development",
				"IMAGO_DEFAULT_DBUSER" : "postgres",
				"IMAGO_DEFAULT_DBHOST" : "127.0.0.1",
				"IMAGO_DEFAULT_DBNAME" : "imago",
				"IMAGO_MASTER_DBHOST" : "127.0.0.1",
				"IMAGO_MASTER_DBNAME" : "master"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		}
	]
}
```

**Comment by CoenraadS** [comment] 2017-02-04 16:24
https://github.com/Microsoft/vscode/releases

**Comment by endevea** [comment] 2017-02-04 17:23
Thanks. Found the binaries ok.

 

1.8.1 works perfectly. 

 

1.9.0 does nothing when hitting F5. No errors appear in the consoles logs, no nodejs process is created in the background (in case, it was hanging), no spinning/waiting cursor.

**Comment by isidorn** [comment] 2017-02-06 10:06
@endevea Does the problem go away if you change the `"type"` in your `launch.json` from `"node"` to `"node2"`? Does the problem still occur if you click the green play button in the debug view.
 Is it possible for you to share your workspace for which we can reproduce this problem? Or can you create a minimalistic repository on github for which this problem can be reproduced?

**Comment by weinand** [comment] 2017-02-06 11:14
@endevea I'm not able to reproduce. What version of node are you using?
Please add a `"trace": "all"` to your launch config and add the debug console output here.

BTW, the green squigglies in your launch config indicate deprecated  attributes.

**Comment by endevea** [comment] 2017-02-06 13:16
Hi Isidor and Andre,

 

I’m under the pump but promise to try and get a reproducible project to play with. 

 

Npm: 3.10

Node: 6.9.1

 

The package.json is attached.

 

Cheers,

 

Michael

**Comment by endevea** [comment] 2017-02-15 01:23
Hi Isidor,

 

Just sat down to create an example workspace, reinstalled 1.9.1 and it works. The recovery point release must have fixed the problem.

 

Sorry, I didn’t get to this sooner.

 

Cheers,

 

Michael

**Comment by isidorn** [comment] 2017-02-15 08:38
Thanks for the update. Thus closing this for now, will reopen if this issue happens to you again in the future and you provide reproducable steps.
Thanks

**Closed by isidorn** 2017-02-15 08:38 UTC
Labels: debug, needs more info
