### ISSUE TITLE
Backspace no longer works when editing markdown files.

### ISSUE THREAD

**Issue by joemaffei** [Microsoft/vscode#44283] opened 2018-02-23 16:28 UTC
Issue Type: Bug

As of the latest update, I'm getting a "command 'markdown.extension.onBackspaceKey' not found." error when editing a markdown file.

VS Code version: Code - Insiders 1.21.0-insider (ce13bb0dabd06981913c46b5a94456647864c2e0, 2018-02-23T05:19:18.064Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|7.89GB (1.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.6
githistory|don|0.4.0
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.1
vscode-firefox-debug|hbe|1.1.0
vscode-styled-components|jpo|0.0.16
vscode-postcss-sorting|mrm|3.0.1
debugger-for-chrome|msj|4.1.0
vscode-icons|rob|7.20.0
trailing-spaces|sha|0.2.11
sort-lines|Tyr|1.4.1
gitblame|wad|2.2.0
markdown-all-in-one|yzh|1.0.5

</details>
Disabling markdown-all-in-one fixes the problem.

**Comment by RMacfarlane** [comment] 2018-02-26 16:42
Duplicate of https://github.com/neilsustc/vscode-markdown/issues/103, there is a workaround given in that issue. For extension specific issues, please file the issue on the extension itself.

**Closed by RMacfarlane** 2018-02-26 16:42 UTC
