### ISSUE TITLE
`Find All References` returns incomplete result while TS lang server is warming up

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#127317] opened 2021-06-28 13:20 UTC
![recording (7)](https://user-images.githubusercontent.com/22350/123643032-4603ab80-d824-11eb-8f45-2780122ba064.gif)

I expected it to only finish loading when finally warm. At least I expected the UI to tell me these are incomplete results, and give me a button to load more once ready.

**Comment by mjbvz** [comment] 2021-07-01 17:23
Duplicate of #100890

I agree we need a better way to signal that the project is still loading since it is easy to miss the spinner in the status bar

**Closed by mjbvz** 2021-07-01 17:23 UTC

**Comment by joaomoreno** [comment] 2021-07-06 12:20
Notice that I didn't miss the spinner. I know it was still warming up. But even during that warm-up phase, and especially so, I never expected the feature to tell me _yup this is the final set of results_ with no indication that it's only a partial set.
