### ISSUE TITLE
Keyboard shortcuts that use alt + some dead key don't work

### ISSUE THREAD

**Issue by pubfnbar** [microsoft/vscode#104488] opened 2020-08-12 12:35 UTC
Issue Type: <b>Bug</b>

I use an Apple Magic keyboard with the standard US keyboard layout, which has [dead keys](https://en.wikipedia.org/wiki/Dead_key) on Alt+e, Alt+i, Alt+n, Alt+u, and Alt+\`. Dead keys produce a certain accent character and then combine that accent with the character you type next (if it's possible to combine those two). I've always mapped arrow keys to Alt+j, Alt+k, Alt+l, and Alt+i in Sublime Text so that i can move the cursor without moving my right hand. But with VS Code, mapping Alt+i to the up-arrow (or rather the _cursorUp_ command) doesn't work (nor does mapping from any other dead key). Pressing Alt+i just produces the `ˆ` accent character no matter what it is mapped to in VS Code.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
toml|be5|0.5.1
rust-analyzer|mat|0.2.273

</details>

**Comment by alexdima** [comment] 2020-09-03 20:56
Duplicate of #41024 . We have done all we can and reported the bug upstream to Chromium.

**Closed by alexdima** 2020-09-03 20:56 UTC
