### ISSUE TITLE
Code navigation highlights the folder inappropriately

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#24256] opened 2017-04-07 18:58 UTC
Test tour for MERN starter kit https://github.com/Microsoft/vscode/issues/22277

- VSCode Version: Insiders 
- OS Version: macOS

Steps to Reproduce:

1. Clone MERN starter kit
2. Open index.js
3. Cmd+click near the bottom of the file to navigate to `server/server`

I expect to have the entire string highlighted, instead the folder is highlighted. 

![image](https://cloud.githubusercontent.com/assets/2449568/24815287/790ab50c-1b89-11e7-902e-0b900236560c.png)

This is confusing as a user. It makes me think I am navigating to the folder and not the file.

**Comment by mjbvz** [comment] 2017-04-07 19:41
I believe this is a duplicate of #10037

**Closed by mjbvz** 2017-04-07 19:41 UTC
Labels: duplicate
