### ISSUE TITLE
`FileSearchProvider` and `TextSearchProvider` broken in 1.93.0 for folders with query parameters

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#227836] opened 2024-09-06 20:58 UTC
My extension's `FileSearchProvider` and `TextSearchProvider` report this error on version 1.93.0 for folders with query parameters in their URI:

```
TypeError: Cannot read properties of undefined (reading 'folder')
```

@andreamah Could this have been caused by your recent work in this area?

- VS Code Version: 1.93.0

**Comment by andreamah** [comment] 2024-09-06 21:00
Hmm. Do the workspace folder queries have URIs? Or is it the URI that is returned for the matching file?

**Comment by isc-bsaviano** [comment] 2024-09-06 21:07
The `options` object does have a folder URI:

```json
{
  "folder": {
    "$mid": 1,
    "fsPath": "/",
    "external": "isfs://iris:user/?mapped%3D0",
    "path": "/",
    "scheme": "isfs",
    "authority": "iris:user",
    "query": "mapped=0"
  },
  "excludes": [
    "**/.git",
    "**/.svn",
    "**/.hg",
    "**/CVS",
    "**/.DS_Store",
    "**/Thumbs.db",
    "**/node_modules",
    "**/bower_components",
    "**/*.code-search"
  ],
  "includes": [],
  "useGlobalIgnoreFiles": false,
  "useIgnoreFiles": true,
  "useParentIgnoreFiles": false,
  "followSymlinks": true,
  "maxResults": 0,
  "session": {
    "a": false,
    "b": null
  }
}
```

However, I see this error in the Developer Tools output:
<img width="1053" alt="Screenshot 2024-09-06 at 5 06 18 PM" src="https://github.com/user-attachments/assets/0d859498-81c3-43f5-8687-7923cdeec9df">

**Comment by andreamah** [comment] 2024-09-06 21:10
Could you try with a workspace that doesn't have a query parameter in the workspace folder URI? I'm assuming that the query info has important info that you need for the search provider?

**Comment by isc-bsaviano** [comment] 2024-09-06 21:14
The workspace I use has one folder with a query parameter, one without. I only saw one error in the Developer Tools. We use the query parameters to filter the files shown in VS Code since the virtual file systems can be large. Here's the file search options for the folder without query parameters:

```json
{
  "folder": {
    "$mid": 1,
    "fsPath": "/",
    "external": "isfs://iris:%sys/",
    "path": "/",
    "scheme": "isfs",
    "authority": "iris:%sys"
  },
  "excludes": [
    "**/.git",
    "**/.svn",
    "**/.hg",
    "**/CVS",
    "**/.DS_Store",
    "**/Thumbs.db",
    "**/node_modules",
    "**/bower_components",
    "**/*.code-search"
  ],
  "includes": [],
  "useGlobalIgnoreFiles": false,
  "useIgnoreFiles": true,
  "useParentIgnoreFiles": false,
  "followSymlinks": true,
  "maxResults": 0,
  "session": {
    "a": false,
    "b": null
  }
}
```

**Comment by andreamah** [comment] 2024-09-06 21:16
Could you try it out with just the workspace folder with no query parameter in its URI? I think I know what's happening (related to https://github.com/microsoft/vscode/issues/227248).

**Comment by isc-bsaviano** [comment] 2024-09-06 21:18
That works

**Comment by andreamah** [comment] 2024-09-09 16:43
We made a change to the API recently so that we do one call to the extension for results for all workspace folders. Then, we try to derive the original workspace folder by using the result's URI. I think that the latter is currently failing with query params - let me try to fix this.

**Comment by andreamah** [comment] 2024-09-09 16:46
Question: do you ever have workspace folders that have the same URI except for the query parameter and/or the fragment?

**Comment by isc-bsaviano** [comment] 2024-09-09 17:05
Yes, we do. The URI authority tells our extension what remote server to connect to, and the query parameters add filtering to limit the scope of documents on the remote server that are part of that VS Code workspace folder. There's no reason why a workspace couldn't contain two folders, both connected to the same remote server but with different filtering options. As of now we do not use the fragment, just query parameters.

**Comment by andreamah** [comment] 2024-09-09 17:10
Hmm okay. @jrieken @mjbvz we probably need to re-think how we're deducing the original workspace folder of a result, since just finding which workspace folder these URIs live relative to seems to not be working for all API adopters.

**Comment by isc-bsaviano** [comment] 2024-09-09 17:18
@andreamah FWIW we've experienced issues with this in the past. See #212363 for a recent, still-open example.

**Comment by jrieken** [comment] 2024-09-09 17:56
> Hmm okay. @jrieken @mjbvz we probably need to re-think how we're deducing the original workspace folder of a result, since just finding which workspace folder these URIs live relative to seems to not be working for all API adopters.

I believe you need to make sure to honor the query-part which isn't the default. I don't really know if or how you do this but the search tree does have support for it (`ignoreQueryAndFragment` argument):
 https://github.com/microsoft/vscode/blob/1349397cf767bda1680b22c095cf18084e71cf43/src/vs/base/common/ternarySearchTree.ts#L306

**Comment by andreamah** [comment] 2024-09-09 17:59
Does the URI need to have the query/fragment, though? For example, if we have the workspace `isfs://iris:user/?mapped%3D0`, does the URI need to look like `isfs://iris:user/foo/bar?mapped%3D0`? 

@isc-bsaviano are you returning the file result URIs with the query attached?

**Comment by isc-bsaviano** [comment] 2024-09-09 18:01
Yes, the returned file URIs contain the query parameters. They only differ from the containing workspace folder URI in the path segment.

**Comment by andreamah** [comment] 2024-09-09 18:19
> They only differ from the containing workspace folder URI in the path segment.

Could you give an example of this? Do you mean that the only difference is the `path` that they have, since the result is in a subfolder of the workspace?

**Comment by andreamah** [comment] 2024-09-10 15:29
> > Hmm okay. [@jrieken](https://github.com/jrieken) [@mjbvz](https://github.com/mjbvz) we probably need to re-think how we're deducing the original workspace folder of a result, since just finding which workspace folder these URIs live relative to seems to not be working for all API adopters.
> 
> I believe you need to make sure to honor the query-part which isn't the default. I don't really know if or how you do this but the search tree does have support for it (`ignoreQueryAndFragment` argument):
> 
> [vscode/src/vs/base/common/ternarySearchTree.ts](https://github.com/microsoft/vscode/blob/1349397cf767bda1680b22c095cf18084e71cf43/src/vs/base/common/ternarySearchTree.ts#L306)
> 
> Line 306 in [1349397](/microsoft/vscode/commit/1349397cf767bda1680b22c095cf18084e71cf43)
> 
>  static forUris<E>(ignorePathCasing: (key: URI) => boolean = () => false, ignoreQueryAndFragment: (key: URI) => boolean = () => false): TernarySearchTree<URI, E> {

if the default is defined using `ignoreQueryAndFragment: (key: URI) => boolean = () => false`, doesn't that mean that this doesn't ignore by default? Seems that it's a function that resolves to false by default. @jrieken

**Comment by jrieken** [comment] 2024-09-10 15:38
Yeah, looks like missed the last update here

**Comment by andreamah** [comment] 2024-09-10 15:48
If the issue isn't with the `TernarySearchTree`, I'll need to try to replicate the scenario to see where the error is. My original assumption was also that it was a `TernarySearchTree` issue.

**Comment by jrieken** [comment] 2024-09-10 15:57
how/where do you use the `TST` for this?

**Comment by andreamah** [comment] 2024-09-13 17:51
I use it here https://github.com/microsoft/vscode/blob/f4a34d0d7a7d1702e36b8e9a929b680c6ed5c6c8/src/vs/workbench/services/search/common/fileSearchManager.ts#L128 

I use `findSubstr` to try to find whether a URI is within a parent folder. Do you know what could be causing the error? 

@isc-bsaviano do you happen to have a small repro project that I can try out to run into the bug?

**Comment by isc-bsaviano** [comment] 2024-09-30 19:38
@andreamah Sorry, I was away for a while. Do you still need help reproducing this?

**Comment by andreamah** [comment] 2024-10-01 16:19
Yes, do you mind putting together a small project that reproduces the issue?

**Comment by isc-bsaviano** [comment] 2024-10-01 19:24
@andreamah Attached is a modified version of the `fsprovider-sample` extension that demonstrates the issue. Here are the steps to reproduce:

1. Download the zip, unzip it, and install the extension VSIX.
2. When not having a workspace opened, run the MemFS Setup Workspace command.
3. Run the MemFS Create Files command.
4. Run the Toggle Developer Tools command.
5. Type `Ctrl-P` to trigger the `FileSearchProvider`.
6. Observe the error message written to the dev tools console. 

[vscode-memfs-0.0.3.vsix.zip](https://github.com/user-attachments/files/17215293/vscode-memfs-0.0.3.vsix.zip)

**Comment by andreamah** [comment] 2024-10-01 23:14
@jrieken When the TST sets `ignoreQueryAndFragment` to false, does `findSubstr` still find roots with the same query parameter?

For example, running this test:
```typescript
	test('TernarySearchTree (URI) - query parameters', function () {
		const trie = new TernarySearchTree<URI, number>(new UriIterator(() => false, () => false));
		const root = URI.parse('memfs:/?q=1');
		trie.set(root, 1);

		assert.strictEqual(trie.get(URI.parse('memfs:/?q=1')), 1);

		assert.strictEqual(trie.findSubstr(URI.parse('memfs:/file.txt?q=1')), 1);
	});
```
Should I expect it to pass?

**Comment by jrieken** [comment] 2024-10-02 06:43
Yes, this is expected to pass because they query part `q=1` is equal in both uris

**Comment by gjsjohnmurray** [comment] 2024-10-02 06:58
Linking to #212436 in case relevant. Even if not it'd be good to get that PR merged as it will fix another issue affecting @isc-bsaviano

**Comment by andreamah** [comment] 2024-10-02 15:10
> Yes, this is expected to pass because they query part `q=1` is equal in both uris

@jrieken it does not pass. I tried it in the TST tests.

**Comment by gjsjohnmurray** [comment] 2024-10-04 13:19
@andreamah please see #230483 for why the urgency of getting this fixed has increased. It now affects Explorer Find on folders that use our extension's FileSystemProvider for which queryparams are often essential to its uris working.

**Comment by andreamah** [comment] 2024-10-04 18:05
That seems not related to having query parameters (?) According to the repro steps, it should happen regardless of having a query parameter?

**Comment by isc-bsaviano** [comment] 2024-10-10 14:10
Hi @andreamah, any updates on this? This issue is forcing a bunch of our end users to be stuck on 1.92.2.

**Comment by andreamah** [comment] 2024-10-10 15:19
@jrieken do you know why the test case in https://github.com/microsoft/vscode/issues/227836#issuecomment-2387244287 fails?

**Comment by andreamah** [comment] 2024-10-19 00:33
Looking more into this, it is likely because the `findSubstr` function moves from start to finish without considering whether the queries and fragments are matching. Therefore, if there is a path segment when the query segment is expected (in the example above), it doesn't return as a match.

https://github.com/microsoft/vscode/blob/c4735bf5cdedcd8e6d58e67500552c2310c9d281/src/vs/base/common/ternarySearchTree.ts#L632-L655

Since I wanted to get a quick fix in for this without impacting the other uses of the TST, I just created a custom implementation that patches up what I need here: https://github.com/microsoft/vscode/pull/231715

**Closed** 2024-10-19 01:34 UTC
Labels: bug, search

**Comment by isc-bsaviano** [comment] 2024-10-21 11:09
/verified in Insiders. Tanks for getting this fixed @andreamah!

**Comment by isc-bsaviano** [comment] 2024-10-22 14:33
Thanks for looking at this @jrieken. 

> Like, is `foo:///some/folder?onlyShow=aaa` a parent of `foo:///some/folder/bbb.txt?onlyShow=aaa`. Should the query component be looked at for the resource (e.g the full url) or for subparts too?

I think the answer to this is yes. VS Code creates child URIs from the results of `readDirectory()` assuming this is true (i.e. it doesn't change the query parameters). You need to query there to identify which workspace folder the file is in.

**Comment by TylerLeonhardt** [comment] 2024-10-23 23:31
marking as verified thanks to @isc-bsaviano!
