### ISSUE TITLE
feature request: markdown support more advance feature, like tasks list

### ISSUE THREAD

**Issue by builden** [Microsoft/vscode#2483] opened 2016-01-28 08:59 UTC
such as:
* `[TOC]`
* task list `- [x]`
* flowchart [http://adrai.github.io/flowchart.js/]
* sequence-diagrams [http://bramp.github.io/js-sequence-diagrams/]

**Comment by bpasero** [comment] 2016-01-29 08:26
duplicate of #2175

**Closed by bpasero** 2016-01-29 08:26 UTC
