### ISSUE TITLE
Difference Editor Scrolls when it shouldn't; makes selection very difficult

### ISSUE THREAD

**Issue by bradlitterell** [microsoft/vscode#161877] opened 2022-09-27 02:17 UTC
Type: <b>Bug</b>

Modify a file in git and open the change in the Source Control tab so there are Red/Green segments.

Starting at the right end of a green line, highlight the line with the mouse (click/drag).  slowly drag the mouse past the left side of the line into the line-numbers region.

Expected behavior: the line is highlighted.
Actual behavior: the file quickly scrolls down expanding the highlighted region far beyond what the user intends. 

This is a usage breaking bug.

DOES NOT REPRO ON:
Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

REPRO ON:

VS Code version: Code - Insiders 1.72.0-insider (ba515cdbb48470c116884deb6de17981d341ec06, 2022-09-22T07:20:03.786Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (10.77GB free)|
|Process Argv|--crash-reporter-id 2f3b771b-fd3e-4208-9190-23c3b96edf17|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
code-eol|jef|1.0.12
git-graph|mhu|1.30.0
cpptools|ms-|1.13.0
hide-gitignored|npx|1.1.0
vscode-text-tables|Rom|0.1.5
rewrap|stk|1.16.3
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
markdown-all-in-one|yzh|3.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30568093
vscccc:30564267
pyindex848:30568094

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-09-27 02:40
@alexdima possibly an unintended consequence of your recent drag-scrolling changes.

**Comment by alexdima** [comment] 2022-09-29 16:00
Duplicate of https://github.com/microsoft/vscode/issues/161485 . @bradlitterell the latest insiders already contains a fix.

**Closed by alexdima** 2022-09-29 16:00 UTC
