### ISSUE TITLE
Extension error after update 1.39.0

### ISSUE THREAD

**Issue by spiderix** [microsoft/vscode#82181] opened 2019-10-09 21:28 UTC
Hello after update extensions disabled after start and editor throw error

Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

abstractExtensionService.ts:396 TypeError: Cannot read property '__metadata' of undefined
    at d.readFile.then.e (extensionPoints.ts:55)
_logMessageInConsole @ abstractExtensionService.ts:396
_logOrShowMessage @ abstractExtensionService.ts:410
L.Logger @ extensionService.ts:415
error @ extensionPoints.ts:53
error @ cachedExtensionScanner.ts:366
scanExtensions @ extensionPoints.ts:545
async function (async)
scanExtensions @ extensionPoints.ts:510
_scanExtensionsWithCache @ cachedExtensionScanner.ts:211
async function (async)
_scanExtensionsWithCache @ cachedExtensionScanner.ts:187
_scanInstalledExtensions @ cachedExtensionScanner.ts:281
startScanningExtensions @ cachedExtensionScanner.ts:81
async function (async)
startScanningExtensions @ cachedExtensionScanner.ts:80
_scanAndHandleExtensions @ extensionService.ts:439
_initialize @ abstractExtensionService.ts:102
h.runWhenIdle @ extensionService.ts:140
requestIdleCallback (async)
t.runWhenIdle @ async.ts:695
B._lifecycleService.when.then @ extensionService.ts:139
Promise.then (async)
B @ extensionService.ts:137
_createInstance @ instantiationService.ts:117
_createServiceInstance @ instantiationService.ts:216
_createServiceInstanceWithOwner @ instantiationService.ts:205
_createAndCacheServiceInstance @ instantiationService.ts:194
_getOrCreateServiceInstance @ instantiationService.ts:142
get @ instantiationService.ts:60
initLayout @ layout.ts:207
e.invokeFunction @ workbench.ts:145
invokeFunction @ instantiationService.ts:67
startup @ workbench.ts:139
open @ desktop.main.ts:128
async function (async)
open @ desktop.main.ts:116
t.main @ desktop.main.ts:380
(anonymous) @ workbench.js:33
Promise.then (async)
bootstrapWindow.load.removeDeveloperKeybindingsAfterLoad @ workbench.js:29
e @ bootstrap-window.js:132
t._invokeFactory @ loader.js:1036
t.complete @ loader.js:1046
s._onModuleComplete @ loader.js:1663
s._onModuleComplete @ loader.js:1675
s._resolve @ loader.js:1623
s.defineModule @ loader.js:1274
r @ loader.js:1713
c @ loader.js:791
(anonymous) @ workbench.common.main.ts:120
(anonymous) @ fake:1
t._createAndEvalScript @ loader.js:794
(anonymous) @ loader.js:776
u @ loader.js:889
(anonymous) @ loader.js:905
readFileAfterClose @ internal/fs/read_file_context.js:53
extensionHost.ts:295 [Extension Host] debugger listening on port 55170

**Comment by robert-sulkowski** [comment] 2019-10-10 09:05
same problem, after upgrading to v**1.3.9.0**

after launching, all extensions switch to disabled and the option to enable them is inactive, after reinstallation the extensions works until closing

after start they are disabled again

Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by sjimenez77** [comment] 2019-10-10 11:20
Same problem here after upgrading to v1.39.0.
All extensions are disabled and cannot be anabled. Reinstalling them works until closing. 

Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by dib258** [comment] 2019-10-10 14:24
Same here, even on OSX. All extensions are disabled at start. And if I enable them all, If I close VSC they all get deactivated again...

Version: 1.39.0
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:57:43.593Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

**Comment by sjimenez77** [comment] 2019-10-14 10:29
I have tried to solve this reinstalling VS Code but it did not work. The upgrade to 1.39.1 did not work either. However, the upgrade in my other installation at home in a macOS machine worked well.

**Comment by jrieken** [comment] 2019-10-14 12:17
/duplicate of https://github.com/microsoft/vscode/issues/82359

**Closed** 2019-10-14 12:17 UTC
Labels: *duplicate
