### ISSUE TITLE
Editor restarts after adding first folder to workspace

### ISSUE THREAD

**Issue by pandaniell** [microsoft/vscode#106235] opened 2020-09-07 13:34 UTC
When adding a folder to the workspace, the editor restarts, afterwards you can add folders without restarting, this is annoying when you have multiple console tasks running and you decide to add a folder later on because you have to restart them and change directories when using the split terminal for example

- VSCode Version: 1.48.2
- OS Version: Windows_NT x64 10.0.19041

I am using the `ms-vscode-remote.remote-wsl` extension

Steps to Reproduce:

1. Open any folder
2. File > Add Folder to Workspace

Does this issue occur when all extensions are disabled?: -

**Comment by gjsjohnmurray** [comment] 2020-09-07 14:07
See https://github.com/microsoft/vscode/issues/105285#issuecomment-679079523

**Comment by bpasero** [comment] 2020-09-07 15:37
I think part of it is https://github.com/microsoft/vscode/issues/72529 or maybe all of it. Also I think @aeschli  added the window reload.

**Comment by aeschli** [comment] 2020-11-05 10:28
duplicate of #72529

**Closed by aeschli** 2020-11-05 10:28 UTC
Labels: remote, workbench-multiroot
