### ISSUE TITLE
When renaming a symbol: "Overlapping ranges are not allowed!" (all extensions disabled)

### ISSUE THREAD

**Issue by axefrog** [microsoft/vscode#55606] opened 2018-08-01 20:52 UTC
- VSCode Version: 1.25.1
- OS Version: Windows 10

I have been getting this error showing up ~~intermittently, and though I can't predict when it will happen~~, it is guaranteed to happen after VS Code has been open for a while.

I have a multiroot workspace in which I'm working on a JavaScript project. I often use the "rename" feature, sometimes on a local symbol, and sometimes on an imported or exported symbol. The error has shown up in both cases. Note that the error _only_ happens when I try to rename something, and I can usually rename things for a while before the error first appears. Once it has appeared, it occurs every time until I restart VS Code. When the error shows up, the rename fails to execute, which means I can't ignore the error and rename anyway.

The error is "Overlapping ranges are not allowed!". The error has only been occurring in the last month or so, and I have systematically gone through, disabling extensions I've installed in that time, and extensions that interact with the editor.

~~I've run with extensions disabled, but because the error can take some time to show up, it's hard to draw conclusions from that. I've also been running in verbose mode in order to try and capture some data to report here.~~

~~At the very least, it'd be good to get some advice on how I can figure out which extensions were trying to get involved with whatever led to the error being thrown, because the stack trace doesn't highlight anything obvious to me, the output windows don't show any extension-specific errors or logs that seem relevant, and the process window doesn't show any nonstandard background extensions running either.~~

**Update:** I have ALL extensions currently disabled and I have found a point in my code where this error reliably occurs first time, every time. Unfortunately I can't seem to reproduce it with a simpler project setup. I have updated my various dependencies so that TypeScript 3.0.1 is everywhere, and have tried setting the current TypeScript version in VS Code to both 2.9.2 (VS Code's version) and 3.0.1 (workspace version). The error happens in both cases.

[renderer1.log seems relevant](https://github.com/Microsoft/vscode/files/2251151/renderer1.log) (shows error trace within)

[Here is the console trace log](https://github.com/Microsoft/vscode/files/2251089/trace.log)

[Here is a zip of the tsserver log](https://github.com/Microsoft/vscode/files/2251122/tsserver.zip) (Doesn't show any errors, so probably not an issue there, I guess?)

Stack trace screenshot:

![trace](https://user-images.githubusercontent.com/298883/43547930-0b2f0480-9620-11e8-9a81-cf755c095bd5.png)

Scopes screenshot pieced together from several screenshots while scrolling down:

![scope](https://user-images.githubusercontent.com/298883/43547937-0fd3b170-9620-11e8-88a8-ab929b964eaf.png)

Does this issue occur when all extensions are disabled?: YES

Any assistance would be greatly appreciated.

**Comment by axefrog** [comment] 2018-08-01 22:18
Here is my workspace configuration:

```json
{
  "folders": [
    { "projects\\experiments" },
    { "path": "projects\\meshseed" },
    { "path": "projects\\salix" },
    { "path": "projects\\dataflow-mechanic" },
    { "path": "." },
    { "path": "projects\\config" },
    { "path": "projects\\corelib" },
    { "path": "projects\\propagate" },
    { "path": "projects\\structural" },
    { "path": "projects\\streams" },
    { "path": "projects\\collectable", "name": "collectable (monorepo)" },
    { "path": "projects\\collectable\\packages\\collectable", "name": "collectable (package)" },
    { "path": "projects\\collectable\\packages\\core" },
    { "path": "projects\\collectable\\packages\\list" },
    { "path": "projects\\collectable\\packages\\red-black-tree" },
    { "path": "projects\\collectable\\packages\\map" },
    { "path": "projects\\collectable\\packages\\set" },
    { "path": "projects\\collectable\\packages\\sorted-map" },
    { "path": "projects\\collectable\\packages\\sorted-set" },
    { "path": "projects\\most-core" }
  ],
  "settings": {
    "typescript.tsdk": "C:\\Users\\axefr\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib",
    "typescript.referencesCodeLens.enabled": false,
    "typescript.implementationsCodeLens.enabled": false,
    "git.ignoreLimitWarning": true,
    "[markdown]": {
      "editor.lineHeight": 20.5,
      "editor.letterSpacing": -1,
      "editor.wordWrapColumn": 120,
      "editor.wordWrap": "wordWrapColumn"
    },
  }
}
```

Here are the settings for the workspace root:

```json
{
    "files.exclude": {
        "**/.git": true,
        "projects": true
    },
    "files.watcherExclude": {
        "**/.git/**": true,
        "**/lib/**": true,
        "**/.build/**": true,
        "**/.archive": true,
        "projects": true
    },
    "search.exclude": {
        "**/.git/**": true,
        "**/node_modules": true,
        "**/lib/**": true,
        "**/.build/**": true,
        "**/*.d.ts": true,
        "**/.archive": true,
        "projects": true
    },
    "eslint.enable": true,
    "typescript.tsdk": "node_modules/typescript/lib",
    "editor.tabSize": 2,
    "typescript.referencesCodeLens.enabled": false,
    "typescript.implementationsCodeLens.enabled": false,
    "window.menuBarVisibility": "toggle",
    "git.ignoreLimitWarning": true
}
```

**Comment by axefrog** [comment] 2018-08-04 16:07
More information: There _seems_ to be a correlation between whether there is a jsconfig file in the project. I notice that when I get rid of jsconfig, I can rename things successfully for long periods, but when jsconfig is present, the error shows up quickly. Kind of annoying, because without jsconfig, the auto-import feature seems to want to use my package name even for internal imports, so I'm damned if I do, damned if I don't... anyway, an extra data point for you if nothing else.

**Comment by axefrog** [comment] 2018-08-15 21:04
@isidorn @rebornix Bumping this, as it's 11 days old. Issue still occurs in the latest versions of everything.

**Comment by Simran-B** [comment] 2019-12-18 12:56
@axefrog Can you try the latest [insider build](https://code.visualstudio.com/insiders/) please?

I believe #86935 fixed a secondary issue I ran into while using search & replace with a regular expression and files with Windows line endings. I tried to remove unwanted blank lines between two particular markers using `(\{% markerA.+)\r?\n\r?\n([ ]{4}@markerB)` and substituting it with `$1\n$2`. For some matches, the replace preview did not open and the developer console logged this error:

```
log.ts:196
ERR Overlapping ranges are not allowed!: Error: Overlapping ranges are not allowed!
    at r.applyEdits (file:///C:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:673:874)
    at O._applyEdits (file:///C:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1354:886)
    at O.applyEdits (file:///C:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1354:639)
    at r.pushEditOperation (file:///C:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:620:143)
    at O._pushEditOperations (file:///C:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1354:496)
    at O.pushEditOperations (file:///C:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1353:433)
    at E.applyEditsToPreview (file:///C:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4196:3)
    at file:///C:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4195:690
```

I tested this with VSCode 1.41.0 (Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959).

Using 1.42.0-insider (Commit: 241d4048aabc31db0baed66bb3d58cf3210d981d), the regex does not need the `\r?` anymore and I can no longer reproduce the problem - the replace preview opens fine for all matches.

If your problem is still reproducible in the latest version, then perhaps a similar fix is needed to properly handle Windows line breaks?

**Comment by axefrog** [comment] 2019-12-18 18:16
@Simran-B hi, this issue is over a year old. I don't have the project setup required to test this anymore.

**Comment by rebornix** [comment] 2020-11-05 02:08
Considering we are not seeing this bug reported elsewhere and it's been quite a while since it was originally reported, I'll close it but we can always reopen if anyone sees it again.

**Closed by rebornix** 2020-11-05 02:08 UTC
Labels: bug

**Comment by johncrim** [comment] 2020-11-17 00:17
I'm seeing this too - it's been impacting my work for the last week or so. When I first open VS Code, I can rename typescript tokens, but after a little bit I am seeing "Rename failed to apply edits" as a toast popup, and the following in the log window every time I try to rename anything. Note that I am seeing 2 occurrences of the error message in the log window for each attempted rename:

```
[2020-11-16 16:10:54.082] [renderer1] [error] Error: Overlapping ranges are not allowed!
    at c.applyEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1463:589)
    at P._doApplyEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1497:479)
    at P.applyEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1497:297)
    at m.pushEditOperation (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1327:429)
    at P._pushEditOperations (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1496:281)
    at P.pushEditOperations (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1495:45)
    at m.apply (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3260:808)
    at f.apply (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3263:322)
    at async f._performTextEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6704:204)
    at async f.perform (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6703:663)
    at async S.apply (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6705:301)
[2020-11-16 16:10:54.082] [renderer1] [error] Error: Overlapping ranges are not allowed!
    at c.applyEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1463:589)
    at P._doApplyEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1497:479)
    at P.applyEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1497:297)
    at m.pushEditOperation (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1327:429)
    at P._pushEditOperations (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1496:281)
    at P.pushEditOperations (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1495:45)
    at m.apply (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3260:808)
    at f.apply (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3263:322)
    at async f._performTextEdits (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6704:204)
    at async f.perform (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6703:663)
    at async S.apply (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6705:301)
```

Environment:
```
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

(I'm actually using Node 15.x, but VS Code seems to be using an older version).

My workspace is a number of Angular + Typescript projects, and a few other things. Unlike the original reporter, I don't have any jsconfigs.

One of the recent changes was switching to eslint, so I thought it might be a file locking issue between command-line eslint and VS Code. I'm not sure yet - I have not determined causality, will have to experiment more. At least I have a place to report the issue.

The workaround is to exit VS Code and restart it, and which point I can rename the tokens I need to rename. 20 minutes (or so) later, I can no longer rename tokens.
