### ISSUE TITLE
Javascript docs say use TSD but it is replaced by typings

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#2885] opened 2016-02-10 10:58 UTC
on https://code.visualstudio.com/docs/languages/javascript

"The typings are easily managed using TSD, the TypeScript Definition manager."

But on https://github.com/Definitelytyped/tsd#readme

"DEPRECATED: TSD is deprecated, please use Typings and see this issue for more information."

**Comment by egamma** [comment] 2016-02-10 11:13
This is a duplicate of Microsoft/vscode-docs#145

**Closed by egamma** 2016-02-10 11:13 UTC

**Comment by SteveALee** [comment] 2016-02-10 11:29
Strange. I did search first.

**Comment by egamma** [comment] 2016-02-10 11:30
(it is a PR in the vscode-docs repo and not in the vscode repo)

**Comment by SteveALee** [comment] 2016-02-10 12:12
my bad
