### ISSUE TITLE
Operator Mono not rendering

### ISSUE THREAD

**Issue by diazgilberto** [Microsoft/vscode#28919] opened 2017-06-17 02:30 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|django-html|bibhasdn|1.2.0|
|jupyter|donjayamanne|1.1.3|
|python|donjayamanne|0.6.5|
|file-icons|file-icons|1.0.3|
|vscode-jekyll-snippets|ginfuru|0.8.1|
|language-liquid|neilding|0.0.2|
|advanced-new-file|patbenatar|0.4.3|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:

1. Install Operator Mono fonts in your computer.
2. `cmd+,` and in the USER SETTINGS `"editor.fontFamily: "Operator Mono"`
3. Save and close USER SETTINGS.
![screen shot 2017-06-16 at 9 29 11 pm](https://user-images.githubusercontent.com/9165819/27249422-e123bbec-52da-11e7-88ef-b169d1c69072.png)

If you know Operator Mono, that's not the way should look.

**Comment by alexandrudima** [comment] 2017-06-19 07:23
Possible duplicate of #27473

**Comment by alexandrudima** [comment] 2017-11-24 14:52
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Closed by alexandrudima** 2017-11-24 14:52 UTC
Labels: font-rendering, upstream
