### ISSUE TITLE
Can no longer create new git branch from VS Code

### ISSUE THREAD

**Issue by akulbe** [Microsoft/vscode#24315] opened 2017-04-08 14:39 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.16170
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|json-tools|eriklynd|1.0.2|
|beautify|HookyQR|1.0.2|
|Go|lukehoban|0.6.59|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|Chef|Pendrica|0.6.2|
|Ruby|rebornix|0.10.4|
|vscode-icons|robertohuertasm|7.5.1|;

---

Steps to Reproduce:

1. click on "master" on the Side Bar
2. in the box at the top, you'll see the other branches
3. If the branch you want to create and checkout doesn't exist, there's no longer an option to check it out

<img width="1920" alt="vscode_git_checkout1" src="https://cloud.githubusercontent.com/assets/123279/24829843/5aeb7bec-1c2e-11e7-9a21-73ee9423a9c3.png">
<img width="1920" alt="vscode_git_checkout2" src="https://cloud.githubusercontent.com/assets/123279/24829845/6b707b16-1c2e-11e7-80e6-cf793603ccf5.png">
<img width="1920" alt="vscode_git_checkout3" src="https://cloud.githubusercontent.com/assets/123279/24829848/80eb85da-1c2e-11e7-80c4-21aa8bdfc9a9.png">

**Comment by jsynowiec** [comment] 2017-04-08 14:57
Duplicate of #21439

**Closed** 2017-04-08 17:50 UTC

**Comment by akulbe** [comment] 2017-04-08 18:06
@chrmarti @jsynowiec If this is a duplicate, how do you explain my third screenshot?

**Comment by chrmarti** [comment] 2017-04-10 17:08
@akulbe 1.11 uses a new implementation for Git support that is using the new SCM extension story.
