### ISSUE TITLE
No border on linux mint

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#63238] opened 2018-11-15 19:59 UTC
Issue Type: <b>Bug</b>

In recent versions of vscode-insiders I've noticed that code-insiders windows no longer have a border.
Tested with empty `settings.json` on Linux Mint 18.3.

![vscode_no_border](https://user-images.githubusercontent.com/19274678/48578078-90cb9180-e8cd-11e8-8471-0ff2ccd5356f.jpg)

This shows two vscode-insiders windows that blend into each other with no border. At the bottom of this screenshot is a normal window with the usual border. Vscode does not have this and it can be difficult to tell where the window ends.

VS Code version: Code - Insiders 1.30.0-insider (6ef7e81ec086ced5fb20e904ea405075be474023, 2018-11-14T18:15:46.706Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 910)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (3.57GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sbatten** [comment] 2018-11-21 22:57
@bpasero other distros will still render shadows, I tried ubuntu 16.04. Should we provide an optional border around frameless windows?

**Comment by bpasero** [comment] 2018-11-22 06:41
@sbatten possibly, if you want to. Duplicate of https://github.com/Microsoft/vscode/issues/54507

**Comment by sbatten** [comment] 2018-11-26 18:44
Thanks for recalling

**Closed by sbatten** 2018-11-26 18:44 UTC
Labels: bug, insiders, workbench-title
