### ISSUE TITLE
Blue VSCode logo almost not visible

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/vscode#39318] opened 2017-11-29 14:18 UTC
![code logo](https://user-images.githubusercontent.com/7447285/33379445-6ebc7808-d518-11e7-8b92-d0c611bcf3e7.png)

**Comment by bpasero** [comment] 2017-11-29 14:33
Duplicate of https://github.com/Microsoft/vscode/issues/38353

**Closed by bpasero** 2017-11-29 14:33 UTC
Labels: icon, workbench, workbench-tabs
