### ISSUE TITLE
Don't know the format of jsconfig.json and VSCode doesn't help me

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2445] opened 2016-01-27 13:14 UTC
Testing #2218 

When creating a new file `tsconfig.json` I usually do Ctrl+Space and choose a snippet or some default suggestion and I get a decent `tsconfig` to start with. I'd like the same for `jsconfig`

![image](https://cloud.githubusercontent.com/assets/5047891/12614422/22b060f2-c500-11e5-9217-324f9bce5e37.png)

**Comment by egamma** [comment] 2016-01-27 16:47
caused by #2455

**Comment by aeschli** [comment] 2016-01-28 10:01
fixed by #2446

**Closed by aeschli** 2016-01-28 10:01 UTC
Labels: bug
