### ISSUE TITLE
The code trace location is wrong!

### ISSUE THREAD

**Issue by gwiron** [Microsoft/vscode#27011] opened 2017-05-21 04:28 UTC
When I read the koa source code, I tracked the code and then jumped to a directory where it was the Users/yuantu/library/store/typescript/node_modules!
Hope for restoration!
Ps: then you want to know that the index.d.s file is the js code? I don't understand [tears] Want to learn

email: gw_iron@163.com

**Comment by Tyriar** [comment] 2017-05-21 21:25
It's not clear what you problem is. You can learn about .d.ts files here https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by gwiron** [comment] 2017-05-22 01:29
My question is, let me say the procedure, I don't speak English very well
NPM install koa2 - save
The new file index, js
` ` ` `
/ / index. Js
Let Koa = require (' koa2 ') / / I click on the command + mouse click on koa2 to the cache
` ` `

On 05/22/2017 05:25, Daniel Imms wrote: It's not clear what you problem is. You can learn about .d.ts files here https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Tyriar in #27011: It's not clear what you problem is. You can learn about .d.ts files here https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/27011#issuecomment-302964342"}}}

**Comment by Tyriar** [comment] 2017-05-22 02:46
@mattbierner I'm guessing this is about go to definition going to the TS declaration file?

**Comment by mjbvz** [comment] 2017-05-22 22:05
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/6209 as far as I can tell

We use `.d.ts` files to power our javascript and TypeScript language features without having to analyze the original JavaScript sources

**Closed by mjbvz** 2017-05-22 22:05 UTC
Labels: duplicate, needs more info, upstream

**Comment by gwiron** [comment] 2017-05-23 06:10
yes,this is about go to definition going to the TS declaration file




------------------ 原始邮件 ------------------
发件人: "Daniel Imms";<notifications@github.com>;
发送时间: 2017年5月22日(星期一) 上午10:46
收件人: "Microsoft/vscode"<vscode@noreply.github.com>; 
抄送: "只会偏空想想"<462092795@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Microsoft/vscode] The code trace location is wrong! (#27011)




@mattbierner I'm guessing this is about go to definition going to the TS declaration file?
