### ISSUE TITLE
Console only supports `zh-cn command` in  0.10.13-insider Win10(Chinese-Simplified)? 

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#4785] opened 2016-03-30 03:06 UTC
- VSCode Version: 0.10.13-insider
- OS Version: win10

How can i  switch back to the `English commands` or the console can support both 'English' and 'Chinese'?When i'm coding, I have to switch the IME.
![image](https://cloud.githubusercontent.com/assets/7921431/14130287/67cf555e-f664-11e5-9c1d-072d51adf8d0.png)

![image](https://cloud.githubusercontent.com/assets/7921431/14130295/753ae82a-f664-11e5-8968-a89819e031ac.png)

**Comment by Tyriar** [comment] 2016-03-30 15:59
Duplicate of https://github.com/Microsoft/vscode/issues/4691, thanks for the report :)

**Closed by Tyriar** 2016-03-30 15:59 UTC
