### ISSUE TITLE
Notebook cell loses focuses when notebook is edited from diff view

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#229477] opened 2024-09-24 07:30 UTC
Testing #228393

- For the test I used the following code in a cell:

<details>

<summary>
file
</summary>

data= {}

df = pd.DataFram(data)

data= {}
df = pd.DataFram(data)

data= {}

df = pd.DataFram(data)

data= {}
df = pd.DataFram(data)

data= {}

df = pd.DataFram(data)

data= {}

df = pd.DataFram(data)

data= {}

df = pd.DataFram(data)

data= {}

df = pd.DataFram(data)

data= {}

df = pd.DataFram(data)

data= {}

df = pd.DataFram(data)

data= {}

df = pd.DataFram(data)

</details>

- Stage these changes
- Add the following code on line 16 in the cell:

```
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
```

- View the changes in the diff view 
- Place the cursor at the end of the line with `print(x)`
- Remove the parenthesis on that line
- The cell loses focus and it is no longer possible to continue writing in the cell. Sometimes the cell flickers visibly before losing focus. 🐛

**Comment by aiday-mar** [comment] 2024-09-24 07:47
The flickering and focus losing also happens generally when pasting code into the cell.

**Comment by DonJayamanne** [comment] 2024-09-28 12:06
Duplicate of https://github.com/microsoft/vscode/issues/229489#event-14376957749

**Closed by DonJayamanne** 2024-09-28 12:06 UTC
