### ISSUE TITLE
When pulling new changes, the refresh icon on taskbar does not rotate

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/vscode#168292] opened 2022-12-07 10:27 UTC
Type: <b>Bug</b>

When you pull new changes from upstream, the refresh icon just after branch name use to rotate erlier, but now it does not rotate. Although the pull operation is running in background, there is no way user could know its running because that icon does not rotate anymore. 

VS Code version: Code - Insiders 1.74.0-insider (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T10:17:57.998Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (16.21GB free)|
|Process Argv|--crash-reporter-id 6edee8e6-4cac-4830-af28-fb0942a2568e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
EditorConfig|Edi|0.16.4
codespaces|Git|1.13.2
copilot|Git|1.62.7527
azure-pipelines|ms-|1.208.0
vscode-bicep|ms-|0.13.1
vscode-docker|ms-|1.23.1
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
azure-account|ms-|0.11.2
powershell-preview|ms-|2022.12.0
vscode-jest|Ort|4.6.0
vscode-versionlens|pfl|1.0.10
rust-analyzer|rus|0.3.1309
errorlens|use|3.6.0
vscode-conventional-commits|viv|1.24.4-a2b3c29
vim|vsc|1.24.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by lszomoru** [comment] 2022-12-07 11:25
@ShreyasJejurkar, could you please share the contents of the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)? Thanks!

**Comment by ShreyasJejurkar** [comment] 2022-12-07 11:29
The below icon is after the branch name. 
![image](https://user-images.githubusercontent.com/17148381/206167901-93c9a781-35f6-46e2-9fe8-96ef1507cc56.png)

**Comment by jahuarcristian** [comment] 2022-12-07 11:32
Yes deposito a cuenta

**Comment by lszomoru** [comment] 2022-12-07 11:40
@ShreyasJejurkar, would you be able to provide a recording using https://gifcap.dev as I am unable to reproduce the problem. In my case the icon is spinning while the operation is running. Thank you very much!

**Comment by lszomoru** [comment] 2022-12-12 08:44
Closing as duplicate of #168216.

**Closed by lszomoru** 2022-12-12 08:44 UTC
Labels: bug, info-needed, git
