### ISSUE TITLE
VS Code crashes when trying to open terminal by dragging.

### ISSUE THREAD

**Issue by Cryonayes** [microsoft/vscode#111951] opened 2020-12-05 21:37 UTC
Issue Type: <b>Bug</b>

This bug causes vs code to crash when trying to open terminal tab by dragging from the bottom. Tested with all the extensions disabled and still works.

Steps to reproduce:

1) Focus terminal, I did it from Ctrl + Shift + P menu
2) Close terminal by clicking close icon
3) Close visual studio and re-open it
4) Try to open terminal by dragging from the bottom, it crashes

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

Extensions: none

**Comment by meganrogge** [comment] 2020-12-06 00:13
Duplicate of #111463

**Closed** 2020-12-06 00:14 UTC
Labels: *duplicate, integrated-terminal
