### ISSUE TITLE
Bug about seting breakpoints

### ISSUE THREAD

**Issue by tonyxwz** [Microsoft/vscode#38172] opened 2017-11-13 01:04 UTC
When I debug python using Python extension, if I add a line before a breakpoint, the breakpoint cannot be toggled off. I guess this bug is from vscode itself rather than python extension.

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-markdownlint|Dav|0.11.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
tslint|eg2|1.0.21
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
mdmath|goe|2.0.7
vscode-firefox-debug|hbe|0.17.0
beautify|Hoo|1.1.1
latex-workshop|Jam|3.6.1
Go|luk|0.6.67
hg|mrc|1.2.3
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.0
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
Ruby|reb|0.15.0
vscode-icons|rob|7.17.0
RustyCode|sav|0.19.1
cmake|twx|0.0.17
cmake-tools|vec|0.10.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment] 2017-11-13 09:19
duplicate of #37880

**Closed by weinand** 2017-11-13 09:19 UTC
Labels: debug, new release
