### ISSUE TITLE
Custom view: Clicking on expansion triangle also runs command

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44727] opened 2018-02-28 10:19 UTC
Issue Type: <b>Bug</b>

Testing #44364

I cannot change the expansion state without running the command.

VS Code version: Code - Insiders 1.21.0-insider (3fec61014742dec894b3a31cdf8556bf533cb0e1, 2018-02-28T06:08:46.169Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir=tmp/user --extensions-dir=tmp/ext|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by sandy081** [comment] 2018-02-28 14:54
Duplicate of #34130

**Closed by sandy081** 2018-02-28 14:54 UTC
Labels: *duplicate, explorer-custom, insiders
