### ISSUE TITLE
Scanning folder for git repositories

### ISSUE THREAD

**Issue by Dejin1** [microsoft/vscode#173831] opened 2023-02-08 16:19 UTC
Type: <b>Bug</b>

When logging onto a git repo that I have been logging onto for awhile now it suddenly gets stuck "Scanning folder for git repositories"

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-693.11.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.10GB free)|
|Process Argv|--crash-reporter-id f73a455e-9d2d-4763-a7a4-c67b764134cf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.30.29|
|OS|Linux x64 3.10.0-693.11.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6334 CPU @ 3.60GHz (6 x 3591)|
|Memory (System)|5.67GB (3.20GB free)|
|VM|100%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.2.0
vscode-icons|vsc|12.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by rainbar** [comment] 2023-02-09 01:29
I have the same problem after updating to 1.75.0, all the projects in my workspace shows 'no .git folder found', even I add the .git folder manually, it doesn't work. After trying so many methods online, I chose a easy way, back to 1.74.3, **IT WORKED**

**Comment by lszomoru** [comment] 2023-02-09 09:46
@Dejin1, @rainbar, apologies for the inconvenience. Based on the information shared, I believe that this is a duplicate of https://github.com/microsoft/vscode/issues/173226. This issue has already been fixed in Insiders and will be included in the first Stable recovery scheduled for this week. In case you are still able to reproduce this issue after installing `1.75.1` please feel free to reopen the issue. Thank you!

**Closed by lszomoru** 2023-02-09 09:46 UTC
