### ISSUE TITLE
Move files with intellisense

### ISSUE THREAD

**Issue by sir-marc** [Microsoft/vscode#18085] opened 2017-01-04 08:20 UTC
- VSCode Version: 1.8.0
- OS Version: Windows 7

Steps to Reproduce:

1. Move a File into an other folder in project

Is there a way of moving files without having to update dozens of files afterwards manually?
If i rename a file, the editor opens all files linked to that file with a proposed change. Is this possible for moving files, too? https://github.com/Microsoft/vscode-tips-and-tricks/issues/34

**Comment by sandy081** [comment] 2017-01-04 09:15
May I know what kind of project are you using (Javascript, typescript.. ?).. I think renaming a file functionality is done by extension.. can you please also let us know if you have any such extensions. Thanks.

**Comment by sir-marc** [comment] 2017-01-04 09:24
I'm working with typescript.
Renaming of files works fine (without extensions). My Question was, if this funcionality also works for moving files.

**Comment by sandy081** [comment] 2017-01-04 09:55
@sir-marc I wonder why renaming of files is not working. I do not see any associated files opens during file rename. Reason I am asking was we do not support this and if it is coming from an Extension you need to ask the extension author about the functionality.

**Comment by sir-marc** [comment] 2017-01-04 10:05
Renaming files works fine.
The problem is in moving files. Not renaming them.
I dont use any extensions for either of those.
If I rename a file with f2, it opens all referencing files and changes the import statement and waits for me to save it.
But if i move the file, nothing happens. I would expect to also open all referencing files with a suggested change in the import statement.

**Comment by sandy081** [comment] 2017-01-04 10:09
@sir-marc As I said, we do not support renaming of files by opening all referencing files and changing import statement is not in built behavior. Can you please open `Extensions` view and show us what extensions are installed and running?

**Comment by sir-marc** [comment] 2017-01-04 10:12
strange, this works for me just fine. Anyway: my extensions:
Debugger for chrome
Material Theme
TortoiseSVN
TSLint
Typescript Importer (for auto suggesting imports while typing)
vscode-icons

**Comment by sir-marc** [comment] 2017-01-04 10:19
oh I think i had something wrong in my mind. It's obviously not working. Stupid me.
Nevertheless those two features would be handy while developing typescript (or other typed languages)

**Comment by sandy081** [comment] 2017-01-04 10:21
Can you please disable all extension using the following command and retry renaming the file.
![image](https://cloud.githubusercontent.com/assets/10746682/21639350/ce8b747a-d26f-11e6-823e-99fbe2967366.png)

I suspect this behavior is coming from one of the installed extensions (may be Typescript importer).

**Comment by mjbvz** [comment] 2017-02-04 00:59
Closing since I suspect this is caused by an extension.

@sir-marc, please try disabling extensions and let us know if you still see this issue.

Thanks

**Closed by mjbvz** 2017-02-04 00:59 UTC
Labels: caused-by-extension, javascript, typescript

**Comment by sir-marc** [comment] 2017-02-04 01:01
it's not an issue, it's a enhancement request :)
It would be nice, if typescript would recognize when I rename a file or when I move it around
