### ISSUE TITLE
Cursor keeps moving to open bracket tag {

### ISSUE THREAD

**Issue by yuvaraj119** [Microsoft/vscode#52158] opened 2018-06-18 07:36 UTC
Issue Type: <b>Bug</b>

when I press enter button and two times tab and other multiple scenarios the cursor goes to initial open { bracket. I am not able to write the code.

VS Code version: Code - Insiders 1.25.0-insider (777c8e57e0eb1cbffb87a57ffd4f9c3d274f9429, 2018-06-18T05:15:57.671Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (8.26GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
es7-react-js-snippets|dsz|1.8.3
gitlens|eam|8.3.5
react-native-react-redux|EQu|1.9.0
flow-for-vscode|flo|0.8.1
sublime-babel-vscode|jos|0.2.10
react-native-snippet|jun|0.4.3
intellij-idea-keybindings|k--|0.2.24
Angular-BeastCode|Mik|6.0.17
debugger-for-chrome|msj|4.6.0
java|red|0.26.0
vscode-icons|rob|7.23.0
nativescript|Tel|0.7.4
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
vscode-react-native|vsm|0.6.11

</details>

**Comment by changavila** [comment] 2018-06-18 07:38
I have the same issue with the recent update. Its a very annoying bug.

**Comment by kevva** [comment] 2018-06-18 07:39
I'm also getting this using VSCode Insiders.

![kapture 2018-06-18 at 9 38 28](https://user-images.githubusercontent.com/709159/41523756-72448d06-72db-11e8-8e72-9e49361d8aef.gif)

**Comment by yuvaraj119** [comment] 2018-06-18 08:00
I think the issue is fixed now i am not getting this issue.

**Comment by WoodyWoodsta** [comment] 2018-06-18 08:56
@kevva Mind letting us know how to disabled outline? I'm not quite able to find it in the settings.

**Comment by vvs** [comment] 2018-06-18 08:57
Also #52167

Looks like a common problem with the latest Insiders build.

**Comment by jrieken** [comment] 2018-06-18 09:12
/duplicate of https://github.com/Microsoft/vscode/issues/52080

**Closed** 2018-06-18 09:12 UTC
Labels: *duplicate, outline
