### ISSUE TITLE
Need launch config option to disable multiple debug consoles

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#62419] opened 2018-11-01 21:45 UTC
Using debug consoles for multi-process debugging is painful in many situations.

We need a launch config flag to turn this off (and Cluster and multi process debugging should disable multiple debug consoles).

**Comment by isidorn** [comment] 2018-11-02 08:48
I think this makes sense and as you say it should be launch config, not a vscode setting since it depends on the launch configuration.
The following names we already use in launch configs: console, internalConsoleOptions.
What would be the name of the new setting and do we make it a boolean or string in case it needs more tuning in the future.
The simplest one is `multiConsole: true|false`, but let's first decide on how to solve https://github.com/Microsoft/vscode/issues/62420 and see what you think of my suggestion

**Comment by isidorn** [comment] 2018-11-12 14:48
After discussions we decided to only add this as a compound configuration option.
Naming still to be decided.
We have also decided to wait for user feedback after the stable launch before we take any action here.

**Comment by tzachshabtay** [comment] 2018-12-06 14:37
Adding my feedback from #64445 here as it was deleted as a duplicate of this one. What I would like to see is that the dropdown on the debug console for selecting processes will be multi-selection and not single-selection (i.e a list of checkboxes) so that I can check/uncheck the processes for which I'll see output.

**Comment by isidorn** [comment] 2019-01-11 11:51
@weinand do we want to do this this milestone?
If yes, here's my proposal:
We introduce a top level compound configuration which would control this, for example:

```json
"compounds": [
        {
            "name": "Compound",
            "multiConsole": true,
            "configurations": ["Server", "Client"]
        }
    ]
```

So when the compound is launched if multiConsole is false we will put all output in one console.

Feedback on naming and wheter this is a boolean or string is welcome.

Downside of this approach is that it will not be possible to do this when launching multiple independedt debug configurations.

Related launch configuration attribute is named `internalConsoleOptions` - on when to open it.
So we could also call this `internalMultiConsole`.

**Comment by tzachshabtay** [comment] 2019-01-11 13:59
@isidorn, but with your suggestion I'll need to restart everytime I want to change the view. With my suggestion you can change the view while the app is running. And with my suggestion there's no need to add any config.

**Comment by isidorn** [comment] 2019-01-22 15:11
Not convinced we need this.
Pushing out of this milestone
@weinand let me know if you would like this for this milestone and I can look into it. Also check out my proposel from above

**Comment by weinand** [comment] 2019-08-15 09:05
We definitely need this. But probably not as a launch config attribute but an option on the debug API (e.g. method `startDebugging`).

**Comment by isidorn** [comment] 2019-08-15 10:13
@weinand that makes sense since I believe the use case is for sessions that are "auto-started".
You can add it to the API and then I can adopt it in the REPL.

**Closed** 2019-09-19 14:05 UTC
Labels: debug, debug-console, feature-request

**Comment by isidorn** [comment] 2019-09-19 14:23
To verify:

1. Write an extension that uses vscode.proposed.d.ts
2. Use the `startDebugging` api to start multiple sessions and make sure to pass [`DebugSessionOptions`](https://github.com/Microsoft/vscode/blob/a9c67d8b82fdf6693258d6342dbf827928d261fb/src/vs/vscode.proposed.d.ts#L638) with both DebugConsoleMode and verify that new sessions get created in a new or a previous Debug Console (you will see a drop down in debug console title to differentiate)

**Comment by isidorn** [comment] 2019-09-19 14:34
Here's an example `extension.ts` I used for verifying.
In the second window you just need a Launch Config and Launch Config 2 launch configurations to verify.

```typescript
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "sept-extension" is now active!');
    let t = 0;
    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        console.log('hey there');
        t++;
        if (vscode.workspace.workspaceFolders) {
            vscode.debug.startDebugging(vscode.workspace.workspaceFolders[0], t <= 1 ? 'Launch Program' : 'Launch Program 2', {
               consoleMode: vscode.DebugConsoleMode.MergeWithParent,
               parentSession: vscode.debug.activeDebugSession
            });
        }
    });

    context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

**Comment by aeschli** [comment] 2019-10-03 16:07
@isidorn When I try the code above with ( `t <= 1 ? 'Launch Program Foo' : 'Launch Program Bar'`) I get 2 debug consoles.
![image](https://user-images.githubusercontent.com/6461412/66144066-78a95180-e608-11e9-9a9f-c2e6b192bf41.png)

Is that the expected result?

**Comment by isidorn** [comment] 2019-10-03 19:39
If you passed consoleMode: vscode.DebugConsoleMode.MergeWithParent, then you shuold not get two debug sessions, it should just be one. I can also investigate, just let me know if you pass the proper option.

**Comment by aeschli** [comment] 2019-10-04 07:22
I works, the problem I had was that the first debug session has already ended.
