### ISSUE TITLE
feature-request: Lock display of (multiple) SCM providers

### ISSUE THREAD

**Issue by vrachels** [Microsoft/vscode#35343] opened 2017-09-28 23:18 UTC
- VSCode Version: 1.17.0-insider
- OS Version: win10

On the latest scm repository view, I understand that you can select multiple repositories to get the previously implemented multi-view.  However, the selection is constantly being removed, requiring reselecting of the scm providers.

It would be nice to be able to lock the scm to be selected such that it remembers that lock the next time vscode is launched, or in the other cases I've had when it 'forgets'
a small lock/unlock icon-button in the entry in providers list and/or the top level bar of the particular provider would be a nice UX, but even an entry in the `...` list would be fine.

**Comment by joaomoreno** [comment] 2017-09-29 09:45
> However, the selection is constantly being removed, requiring reselecting of the scm providers.

When exactly is the selection being removed? When you restart Code only?

**Comment by vrachels** [comment] 2017-09-29 19:28
I can definitely confirm it clears the selection on restart.  I haven't been able to use insiders recently because of other bugs, though, so can't confirm any other times.  It might have just been that, and I had to restart a lot due to the other issues.

**Comment by joaomoreno** [comment] 2017-10-02 08:52
Alright, closing as duplicate of #35036

**Closed by joaomoreno** 2017-10-02 08:52 UTC
Labels: needs more info, scm
