### ISSUE TITLE
Copy Relative Path

### ISSUE THREAD

**Issue by xialvjun** [microsoft/vscode#85801] opened 2019-11-29 05:50 UTC
Issue Type: <b>Feature Request</b>

There should be two Copy Relative Path.
One is relative to current project.
One is relative to current focused file.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

**Comment by gjsjohnmurray** [comment] 2019-11-29 07:06
/duplicate of #53435

Try holding the Alt key down when you trigger the context menu (e.g. Alt+Right Click)

**Closed** 2019-11-29 07:06 UTC
Labels: *duplicate, new release

**Comment by xialvjun** [comment] 2019-11-29 07:15
@gjsjohnmurray Not the same. My wish is to get `Copy Relative Path To Current Opening File` rather than `Copy Relative Path To Current Project`.

There should be two Copy Relative Path.
One is relative to current project.
One is relative to current focused file.

**Comment by gjsjohnmurray** [comment] 2019-11-29 11:04
My guess is the VSCode team will suggest this should be done by an extension rather than added as a core feature. Pinging @bpasero as I know he has created [a similar extension](https://marketplace.visualstudio.com/items?itemName=rssowl.copy-relative-path-posix). He also has the power to reopen this and add to Backlog Candidate if appropriate.
