### ISSUE TITLE
Incorrect scrollbar in the top menu.

### ISSUE THREAD

**Issue by berhalak** [microsoft/vscode#139292] opened 2021-12-16 13:45 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.1
- OS Version: Windows 10 and Ubuntu 20.04

Top menu is showing scrollbar when it is not needed.

Steps to Reproduce:

1. Open VSCode in any folder (without any extensions).
2. Click the File Menu.
3. Scrollbar appears that is larger then the menu, and when it is not needed.

![image](https://user-images.githubusercontent.com/11277225/146382615-9cd48a01-4913-4403-9740-a01171cd9bd4.png)

**Comment by gjsjohnmurray** [comment] 2021-12-16 14:04
/duplicate of #138110 and fixed in upcoming 1.63.2

**Closed** 2021-12-16 14:05 UTC
Labels: *duplicate, new release
