### ISSUE TITLE
The image displays wrongly:

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#189986] opened 2023-08-08 22:53 UTC
Expected behavior:
Displaying image information like this is the expected behavior:
Edge browser preview results:
![image](https://github.com/microsoft/vscode/assets/54253524/a4f1ea1e-070a-4ca0-a843-5b0f4067da56)

VisualStudio preview results:
![image](https://github.com/microsoft/vscode/assets/54253524/a7311ede-c1df-4402-beaa-ca763fac5b86)
The strange thing is that `Visual Studio 2022 17.6` Markdown can also successfully load the image!

Interllij IDEA preview results:
![image](https://github.com/microsoft/vscode/assets/54253524/bd3d2e93-c55c-41f4-a4d3-b7b70e673791)

VSCode preview results:
![image](https://github.com/microsoft/vscode/assets/54253524/a4f1ea1e-070a-4ca0-a843-5b0f4067da56)

Unexpected behavior:
Failure to display image information like this is unexpected behavior:
Error message:
![B7f8323a52d194ea3846065a97bdd52c0638252336025866076_20230718-073306-image](https://github.com/microsoft/vscode/assets/54253524/eb1f71f0-c0d1-4232-95a6-2e191ae4c9ba)

Image actual address:
https://c0.jdbstatic.com/samples/y3/y3Vvv_l_9.jpg

Windows 10 | 11
VSCode 1.81 | 1.82

**Comment by mjbvz** [comment] 2023-08-08 22:57
Duplicate of #188555

We explained why this is happening: https://github.com/microsoft/vscode/issues/188555#issuecomment-1667977710

It does not seem to be a bug in VS Code

**Closed by mjbvz** 2023-08-08 22:57 UTC

**Comment by zhouxinghong** [comment] 2023-08-08 23:04
So, do you have a solution to this problem?

**Comment by zhouxinghong** [comment] 2023-08-08 23:17
So, do you have a solution to this problem?
From the above image preview results, you can clearly see that all editors including browsers can display this type of image. If you think this is a design decision of VSCode, then I think this image processing engine is not well designed and has major flaws , need to be further revised and perfected.
