### ISSUE TITLE
VSCode can't detect Gulp tasks

### ISSUE THREAD

**Issue by blachawk** [Microsoft/vscode#47764] opened 2018-04-12 17:10 UTC
I'm on WIndows 10
I'm running Visual Studio Code 1.22.1
I have node v8.10.0 installed
I have npm 5.8.0 installed
I have gulp@3.9.1 installed

Based on [Visual Studio Codes instructions: Step 3: Run the gulp default task ](https://code.visualstudio.com/docs/languages/css)I have followed this to the T, but VSCode is failing on me when I click **F1** and then **Tasks:Run Task**

The following output is produced in the output window...

```
Auto detecting gulp for folder scss failed with error: Error: Command failed: gulp --tasks-simple --no-color
```
In addition to this error, what the heck is task-simple--no-color??????????????

**Comment by dbaeumer** [comment] 2018-04-13 08:32
This works for me without any problems. 

![capture](https://user-images.githubusercontent.com/1931590/38724904-e12199a8-3f05-11e8-99e8-016cf2efa31a.png)

Can you provide me with a GitHub repository that I can clone to reproduce your problem.

--task-simple & --no-color are command line args for gulp to list available task in a simple format with coloring.

**Comment by blachawk** [comment] 2018-04-13 14:01
Thanks for confirming that @dbaeumer.  I'll have time on Monday to create a repository for you to clone. I wish I knew what I was doing wrong...but this is a good start.

**Comment by sethstha** [comment] 2018-05-22 05:29
Hi @blachawk 

What version of Gulp are you using. Recently I had the same issue and found there were 2 version of gulp installed.

You can look over the issue here #30570

**Comment by blachawk** [comment] 2018-05-22 09:47
You hit the mark!  can't believe I overlooked that as a reason.  Thsnk you so much @sethstha

**Comment by dbaeumer** [comment] 2018-05-22 09:59
@sethstha thanks for helping here.

@blachawk OK to close the issue?

**Comment by sethstha** [comment] 2018-05-23 04:44
Great, That works. Thanks :)

**Comment by dbaeumer** [comment] 2018-05-23 08:11
Closing the issue then.

**Closed by dbaeumer** 2018-05-23 08:11 UTC
Labels: needs more info, tasks
