### ISSUE TITLE
High DPI: Laggy Unresponsive Scrolling on OSX

### ISSUE THREAD

**Issue by Andrew1431** [microsoft/vscode#26398] opened 2017-05-10 15:22 UTC
- VSCode Version: 1.12.1
- OS Version: macOS Sierra Version 10.12

Steps to Reproduce:

1. Open a file
2. Scroll (I'm using magic touch pad, but same happens with regular touch pad on mac)

When I first found out about vs code, this issue was there. A patch was released that fixed the laggy scrolling issues. Seems to have come back now. It's so bad I can't even scan through a 200 line class and find methods.

**Comment by alexandrudima** [comment] 2017-05-10 15:59
@Andrew1431 

* Can you reproduce when running with `code --disable-extensions` ?
* Is this a regression from 1.11 ? (We have updated our Electron version)
* Does this happen with any file (even `.txt` files ?)
* Do you by any chance use VS Code on a monitor with a large resolution ?

**Comment by Andrew1431** [comment] 2017-05-10 19:32
Thank you @alexandrudima,

1) Happens with `.txt` files. (Seems the whole file explorer is laggy too, the whole editor is cludgey)
2) What do you mean a regression from 1.11? (It seems to me it was, but it could have been earlier when it started happening.)
3) Yes sir, I am running it on a 4k monitor. With multiple vs code windows open (2, each with large projects). Never had this issue though before. (Aside from the first time I tried vscode).
4) The whole editor is rendering slowly, even while dragging the sidebar, using arrows, and scrolling by any means.
5) How do you run mac apps with parameters :P I'll get back to you on this one. (`code --disable-extensions`)

**Comment by Andrew1431** [comment] 2017-05-10 19:36
5. No, --disable-extensions makes no difference!

**Comment by alexandrudima** [comment] 2017-05-10 20:08
Thank you @Andrew1431 , I think this might be a known electron issue. @bpasero will know more.

**Comment by weinand** [comment] 2017-05-10 20:11
@Andrew1431 does it make a difference if you set the setting "editor.disableTranslate3d" to true?

**Comment by Andrew1431** [comment] 2017-05-10 20:14
![image](https://cloud.githubusercontent.com/assets/9736372/25919152/c38bb17c-359b-11e7-9279-e7c2ee8e99c1.png)

**Comment by weinand** [comment] 2017-05-10 20:16
Yes, this is an unofficial setting. You'll have to restart VS Code for changes to take effect.

**Comment by Andrew1431** [comment] 2017-05-10 21:16
Ah, with the setting there, it still made no difference!

**Comment by weinand** [comment] 2017-05-10 21:33
Does it make a difference if you set the "window.zoomLevel" to 0?

**Comment by Andrew1431** [comment] 2017-05-10 21:45
No sir, tried all zoom sizes. Tried different themes, no themes, no plugins, no anything :P

**Comment by bpasero** [comment] 2017-05-11 05:11
I have also seen this. @Andrew1431 can you try to reproduce with our 1.11 release just to see if this is really Electron update related? You can get it from here: https://az764295.vo.msecnd.net/stable/6eaebe3b9c70406d67c97779468c324a7a95db0e/VSCode-darwin-stable-unsigned.zip

**Comment by Andrew1431** [comment] 2017-05-11 11:36
Thanks @bpasero that version works for me. I'll just use this until this issue is resolved :)

**Comment by bpasero** [comment] 2017-05-11 12:04
Unfortunately it looks like the electron update made performance worse (especially around scrolling) on high-DPI monitors.

**Comment by bpasero** [comment] 2017-05-12 08:26
@Andrew1431 does it make a difference (using 1.12) when you start with the following flags (please try setting either one, and both at the same time):
- `code --high-dpi-support=true`
- `code --force-device-scale-factor=1` (can you also try `--force-device-scale-factor=2`)

**Comment by Andrew1431** [comment] 2017-05-15 19:14
I will get back to you later this week with those results! ^

**Comment by solon** [comment] 2017-05-18 20:38
@bpasero I have the same issue. I'm running VSCode on a high-DPI monitor at 3008 x 1692 resolution.  
Here's a [screenshot](http://d.bri.so/ADpg0/4BxqP75e) showing the display settings. 

I tried those three flags and the only setting that reduces the lagginess is 
`code --force-device-scale-factor=1`, although it also has the effect of making the UI somewhat more blurry.

**Comment by jdatskuid** [comment] 2017-05-30 18:33
I'm noticing similar issues.

    MacBook Pro (Retina, 15-inch, Late 2013)
    NVIDIA GeForce GT 750M 2048 MB
    Intel Iris Pro 1536 MB

    Dell P2715Q - 27" IPS LED Monitor ‑ 4K UHDTV (2160p)

Monitor is scaled to 3360x1890. When at standard zoom of 0, there's a lot of flickering whenever I move the mouse. When zoomed in, large portions of the display are completely blank.

`code --disable-extensions` had no effect
`code --high-dpi-support=true` had no effect
`code --force-device-scale-factor=1` had no effect
`code --force-device-scale-factor=2` has no effect

Interestingly, the problem does not appear until I open a project. The default window with recent projects does not flicker.

**Comment by Andrew1431** [comment] 2017-05-30 18:50
@jdatskuid kind of sounds like a different issue than what we're reporting here, we're just get framerate issues in our scrolling, or atleast that's all I'm reporting here.

**Comment by jdatskuid** [comment] 2017-05-30 18:59
@Andrew1431 After consistent experience for over an hour, the flickering and partial rendering issues seem to have suddenly resolved. I made no change, so I have no explanation to offer.

**Comment by ardhitama** [comment] 2017-10-13 01:58
Is there any light regarding this?

**Comment by mloskot** [comment] 2018-02-27 21:54
I'm experiencing very poor performance of VSCode on Windows 10 installed on Dell XPS 13 9360 laptop with HighDPI/high resolution screen **3200x1800**

```
code --status
Version:          Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)
Memory (System):  15.89GB (11.56GB free)
```

Having no extension installed, I open folder with a bunch of C++ files, open a file and sometimes I have to wait 5-10 seconds until I can scroll. I see no particular process occupying CPU, in fact I see no suspicious CPU consumption.

Running `code --disable-gpu` solves the problem!

**Comment by markedwards** [comment] 2018-05-11 17:18
I experience this issue on a new LG 4K display.  Scrolling is just a little laggy.  Its not a deal-breaker, but it is annoying.  Only happens when scaling the display.  When using Default resolution, or when setting to max resolution, scrolling is normal.

**Comment by vedmant** [comment] 2018-05-20 18:47
Scrolling is little bit laggy even on Macbook Air, PhpStorm if to compare doesn't have laggy scrolling.

**Comment by nemtsov** [comment] 2018-07-06 05:53
I have the same issue with a late 2013 Mac Book Pro (NVIDIA GeForce GT 750M 2048 MB, Intel Iris Pro 1536 MB): scrolling, switching tabs, moving group dividers all lag. I've found that there are two workarounds:
  1. Either run `code --disable-gpu`
  2. Or force the use of `Intel Iris Pro` (with the `gfxCardStatus` app)

---

`code --status` with `--disable-gpu` on `GeForce GT750M` (smooth; no noticeable lag):
```
Version:          Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)
Memory (System):  16.00GB (1.05GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-gpu
GPU Status:       2d_canvas:                    unavailable_software
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                unavailable_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	   229	  7495	code main
    0	   328	  7504	   window (AppMap.vue — mono)
    0	    98	  7507	     extensionHost
    0	   131	  7511	       electron_node vueServerMain.js
    0	   131	  7513	       electron_node electronForkStart.js tsserver.js
    0	    49	  7528	         electron_node typingsInstaller.js tsserver.js typesMap.js
    0	    98	  7514	       electron_node eslintServer.js
    0	    49	  7508	     watcherService
    0	    82	  7526	   shared-process

Workspace Stats:
|  Window (AppMap.vue — mono)
|    Folder (mono): 100 files
|      File types: js(44) vue(31) sql(8) html(3) yml(2) json(2) prettierrc(1)
|                  gitignore(1) md(1) css(1)
|      Conf files: package.json(1)
```

`code --status` without flags on `GeForce GT750M` (the lag is noticeable):
```

Version:          Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)
Memory (System):  16.00GB (0.78GB free)
Load (avg):       3, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron
GPU Status:       2d_canvas:                    unavailable_software
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                unavailable_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	    82	  7865	code main
    0	    49	  7874	   gpu-process
    0	   410	  7876	   window (AppMap.vue — mono)
    0	   131	  7879	     extensionHost
    0	   180	  7883	       electron_node vueServerMain.js
    0	   164	  7884	       electron_node electronForkStart.js tsserver.js
    0	    66	  7902	         electron_node typingsInstaller.js tsserver.js typesMap.js
    0	   115	  7885	       electron_node eslintServer.js
    0	    49	  7880	     watcherService
    0	    82	  7897	   shared-process

Workspace Stats:
|  Window (AppMap.vue — mono)
|    Folder (mono): 100 files
|      File types: js(44) vue(31) sql(8) html(3) yml(2) json(2) prettierrc(1)
|                  gitignore(1) md(1) css(1)
|      Conf files: package.json(1)
```

`code --status` with `--disable-gpu` on `Intel Iris Pro` (smooth; no noticeable lag):

```
Version:          Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)
Memory (System):  16.00GB (3.14GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-gpu
GPU Status:       2d_canvas:                    unavailable_software
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                unavailable_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	   229	  8245	code main
    0	   410	  8254	   window (AppMap.vue — mono)
    0	   131	  8257	     extensionHost
    0	   180	  8261	       electron_node vueServerMain.js
    0	   164	  8262	       electron_node electronForkStart.js tsserver.js
    0	    66	  8279	         electron_node typingsInstaller.js tsserver.js typesMap.js
    0	   115	  8263	       electron_node eslintServer.js
    0	    49	  8258	     watcherService
    0	    82	  8269	   shared-process

Workspace Stats:
|  Window (AppMap.vue — mono)
|    Folder (mono): 100 files
|      File types: js(44) vue(31) sql(8) html(3) yml(2) json(2) prettierrc(1)
|                  gitignore(1) md(1) css(1)
|      Conf files: package.json(1)
```

`code --status` without flags on `Intel Iris Pro` (smooth; no noticeable lag):
```
Memory (System):  16.00GB (3.44GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron
GPU Status:       2d_canvas:                    unavailable_software
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                unavailable_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    1	    98	  8133	code main
    0	    49	  8142	   gpu-process
    0	   410	  8143	   window (AppMap.vue — mono)
    0	    98	  8148	     extensionHost
    0	   180	  8153	       electron_node vueServerMain.js
    0	   164	  8155	       electron_node electronForkStart.js tsserver.js
    0	    66	  8172	         electron_node typingsInstaller.js tsserver.js typesMap.js
    0	    82	  8156	       electron_node eslintServer.js
    0	    49	  8149	     watcherService
    0	    82	  8163	   shared-process

Workspace Stats:
|  Window (AppMap.vue — mono)
|    Folder (mono): 100 files
|      File types: js(44) vue(31) sql(8) html(3) yml(2) json(2) prettierrc(1)
|                  gitignore(1) md(1) css(1)
|      Conf files: package.json(1)
```

**Note**: `--disable-extensions` made no difference.

**Comment by strangelooper** [comment] 2018-07-09 14:43
code --disable-gpu worked for me too. Is there a permanent fix to this problem?

**Comment by kallebornemark** [comment] 2018-07-16 00:19
Even with `--disable-gpu`, scrolling on my MBP14 is way, way less smooth than in Sublime.

**Comment by freemanoid** [comment] 2018-07-16 15:19
I have the same problem on mac os, macbook pro 2015 15" with dedicated GPU and external 4k 27" monitor.

I work on 3008x1692 scaled resolution in displays settings and in this mode vscode is lagging and freezing from time to time. The best way to check this for me is to swipe between desktops or made new files with cmd + N.

I've tried to rerun vscode with `--disable-extensions` mode and it didn't help. 
`--disable-gpu` option makes the vscode interface flicks with white color like this (I have yellow background)
![image](https://user-images.githubusercontent.com/180154/42766816-1a8b518a-8924-11e8-8908-6a14809e1a46.png)

Decreasing the size of the window to about 1/4 of the whole screen helps. Reducing the resolution of the monitor to 1920x1080 helps as well.

```
code --status

Version:          Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)
Memory (System):  16.00GB (0.83GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron
GPU Status:       2d_canvas:                    enabled
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    1	    82	 55831	code main
    0	    66	 55832	   gpu-process
    0	   229	 55835	   window (settings.json — ssr_service (Workspace))
    0	   115	 55926	     extensionHost
    0	    98	 55933	       electron_node jsonServerMain.js
    0	    49	 55927	     watcherService
    0	    98	 55931	   shared-process
```

I can provide any other information that can help to resolve the issue. I love to use vscode but it's really hard to do with external monitor.

**Comment by madig** [comment] 2018-12-31 14:14
I just installed VSCode 1.31.0-insider and scrolling on my MacBook Pro Mid 2017 (2,3 GHz Intel Core i5, Intel Iris Plus Graphics 640 1536 MB) on macOS 10.14.2 is much snappier!

**Comment by MartyMaro** [comment] 2019-01-09 19:35
> I just installed VSCode 1.31.0-insider and scrolling on my MacBook Pro Mid 2017 (2,3 GHz Intel Core i5, Intel Iris Plus Graphics 640 1536 MB) on macOS 10.14.2 is much snappier!

Wow this was noticeable on the 2017 model? So big hopes for me that it will be better on the next update.

**Comment by itspauloroberto** [comment] 2019-09-20 18:22
after running `code --disable-gpu` worked as a charm for me. running vs-code on mac osx on a MacBook Air.

before that it was a lot laggy to scroll, even with smooth scrolling. by the way i think low ram left is also a issue.

`
Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)
--
GPU Status | 2d_canvas: disabled_softwareflash_3d: disabled_softwareflash_stage3d: disabled_softwareflash_stage3d_baseline: disabled_softwaregpu_compositing: disabled_softwaremultiple_raster_threads: disabled_offnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: disabled_offrasterization: disabled_softwareskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: disabled_softwareviz_display_compositor: disabled_offwebgl: disabled_offwebgl2: disabled_off
Load (avg) | 2, 2, 2
Memory (System) | 8.00GB (0.88GB free)
Process Argv | --disable-gpu
Screen Reader | no
VM | 0%
`

**Comment by bpasero** [comment] 2019-10-09 18:39
Given https://github.com/microsoft/vscode/issues/15211 we think about allowing to configure Chrome command line flags to be used on each startup. Is there a particular command line flag that makes the situation better for this issue? Then we can add it to the list of supported flags.

**Comment by itspauloroberto** [comment] 2019-10-09 23:21
I have to say that my affirmation before isnt true at all. because i got the problem again, this time even the disable-gpu argument does not solve. I dont know what to do anymore.

**Comment by bpasero** [comment] 2019-10-10 04:14
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by raiskila** [comment] 2019-10-10 04:36
I suffer from low FPS scrolling in VS Code on Mac (Mojave and Catalina) after switching to a 5K high DPI display, and it's significantly improved by `--disable-gpu`.

I compared the current VS Code insiders build to the exploration build you linked (with `--disable-extensions` and an empty configuration file) but couldn't tell any difference in scrolling performance. Both builds suffer from prohibitively laggy scrolling without `--disable-gpu`, and it's improved by setting the flag.

**Comment by bpasero** [comment] 2019-10-10 05:13
@deepak1556 isn't this something you are looking into for E6?

**Comment by raiskila** [comment] 2019-10-10 05:47
Just to add some more data points from my machine, it seems to be kind of a subtle problem. Small scroll increments (say, five lines up and down) with the trackpad tend to be very smooth once VS Code has "seen" a particular part of a file/UI view. It's as if that part is "in cache". The lag arrives when scrolling to a new part of the file or when viewing a file the first time. Small files that fully fit on screen tend not to have laggy scrolling.

Scrolling through large files isn't happening at 60 fps with `--disable-gpu` either, but the scrolling performance seems to be more consistent/predictable, less jerky, and thus less jarring to the eyes when that flag is set. I.e. the performance is more like it was before I upgraded to a high DPI display.

**Comment by itspauloroberto** [comment] 2019-10-11 22:00
Well, i can see a slighty improvement about the scrolling when using the visual code studio exploration, but not very much, still dont solves the problem.

It gets A LOT worse when i try to run `code-exploration --disable-gpu` it becomes unusable.

**Comment by richardstefun** [comment] 2019-12-03 10:38
I found out that disabling 'C/C++ IntelliSense' by Microsoft vastly improves performance while viewing big cpp files. It's still not 60 FPS like on Sublime Text, but it's at least somehow useable.
When I scroll using mouse wheel, it's not choppy at all.

**Comment by PhilippRott** [comment] 2020-01-29 21:09
Same problem with vscode 1.41.1 on Ubuntu Mate 18.04 4k monitor - if I scale the vscode window to 1920x1080 - no scroll problem. bigger size of the window slower scrolling. 

In developer mode - most time wast on rendering and scripting. 
All --disable parameters did not make any change of performance.

Tested full screen on eclipse with same files - no performance problems.

**Comment by raiskila** [comment] 2020-01-30 05:54
As I've discovered on my machine (2018 MBP with eGPU), the problem is simply that VSCode can't handle high pixel resolutions.

Full screen on a display with 5120x2880 resolution, the performance with GPU rendering is unacceptable due to really significant lag and FPS drops, although small scroll increments work smoothly at 60 fps. With CPU rendering, the FPS is consistent but too low.

At a medium window size CPU is fast enough and consistent. At small window sizes both CPU and GPU rendering seem to work flawlessly.

**Comment by zajo** [comment] 2020-02-28 01:00
I've found that setting font antialiasing to "antialiased" helps a little bit (and is arguably the correct setting for highres displays). HTH.

(I'm using vscode on a MBP with 3 external vertical monitors, two of them are 4k. Scrolling is sluggish and unresponsive. This is definitely a vscode problem because web browsers run silky smooth.)

**Comment by martpie** [comment] 2020-03-05 10:36
Can we help in any way to get this issue resolved? Can we send HAR files to someone or something?

**Comment by richardstefun** [comment] 2020-03-08 20:14
> I've found that setting font antialiasing to "antialiased" helps a little bit (and is arguably the correct setting for highres displays). HTH.
 This helps a LOT on my 2015 MBP 13

**Comment by Stakker** [comment] 2020-05-11 08:00
Hi. Just adding my two cents here

I have a 2013 MBP (Nvidia GPU). I mostly use VS Code on an external *low* DPI screen (1080p), but it behaves the same way on the internal Retina screen too. Window size makes no difference.

I also tried changing font rendering settings but none made any difference, including disabling AA completely. I downloaded the exploration build but didn't notice a difference.

I also tried --disable-gpu, and it *may* be slightly better, but it's a bit difficult to tell.

It's far from the worst scrolling I've seen (it's not Xamarin). It is good enough to be usable, but it is not as perfectly smooth as Sublime Text is on this very same machine. It stutters, it's jittery.

I'm using Magic Mouse and the Smooth Scrolling setting doesn't have an effect.

I'm happy to help with testing, if needed!

**Comment by Stakker** [comment] 2020-05-11 08:21
VS Code scrolling also uses a whole lotta CPU. Here's how the two processes roughly look on average while scrolling continuously:

Default settings: Code Helper (Renderer) 55%, Code Helper (GPU) 45%
With --disable-gpu: Code Helper (Renderer) 70%, Code Helper (GPU) 15%.

In comparison, Sublime Text has one process that uses just 22% of CPU (and it's 100% smooth).

**Comment by zajo** [comment] 2020-06-13 22:49
Any more suggestions on how to resolve this? All other programs work fine, giant Web browser windows scrolling is smooth as silk, vscode renders at ~2 fps, disabling GPU acceleration brings that up to ~4 fps. I can help diagnose the problem, please ping me if you need more info.

Here is my config:

Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by runemadsen** [comment] 2020-06-17 08:27
I just tried switching from Atom to VS Code, and scrolling is also laggy for me. It just don't feel that I'm fully in control of the file as I'm scrolling down the page, and it's preventing me from adopting VS Code. 

MacBook Air (Retina, 13-inch, 2018)
1,6 GHz Dual-Core Intel Core i5
8 GB 2133 MHz LPDDR3
External DELL U2720Q Display 27 inch display

**Comment by Adejair** [comment] 2020-08-11 16:38
I have same problems, my mac config is same equals @runemadsen

**Comment by mkozjak** [comment] 2020-09-10 12:41
Pretty bad scrolling experience here on Apple MacBook Air Retina 2018:
```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```
Have double the RAM @runemadsen has.

**Comment by runemadsen** [comment] 2020-11-30 11:41
This issue is definitely still a problem. There's a clear difference in scrolling quality between Atom and VS Code. VS Code feels like it's not quite following along with my mouse movements, and it makes me dizzy. This is independent of hardware since I've upgraded my Mac twice and the problem persists.

**Comment by ardhitama** [comment] 2020-11-30 12:00
Mine solved by using simpler color calibration LUT. Was using large LUT produced by DisplayCal, reverting back to Spyder's solved it.

**Comment by madig** [comment] 2020-11-30 12:08
@ardhitama holy crap, switching back to the factory color profile also fixes this for me! Gotta recalibrate simply this time. Thanks!

**Comment by Stakker** [comment] 2020-11-30 12:58
Color calibration? :-D Happy to hear it works for you, but I'm already using the default profile(s) :-/

**Comment by alvarlagerlof** [comment] 2020-12-21 15:07
I'm also having trouble to the point that I am considering buying a new computer. I'm hovering at just over 20fps according to Quartz Debug

**Comment by Ed1123** [comment] 2021-01-09 03:01
Same problem. Even my 10 years old Dell with a 1st gen Core i5 run the same html file smoother than my new MBP.

**Comment by ianberdin** [comment] 2022-05-05 08:26
It is still laggy.
I tried everything below:
`"disable-hardware-acceleration": true`,
`code --disable-extensions`,
`code --high-dpi-support=true`,
`code --force-device-scale-factor=1 `, // it makes smoother, yet blured.
`code --force-device-scale-factor=2 `.

iMac 27-inch 5k 2017.
CPU: 4.2 GHz i7.
GPU: Radeon Pro 580 8GB.
TrackPad.

**Comment by Ir1d** [comment] 2022-06-13 15:15
I still face this issue

**Comment by deepak1556** [comment] 2022-12-08 06:42
Closing since newer runtime versions have improved scrolling behavior, this will be evergreen as runtime improves scroll performance.

**Closed by deepak1556** 2022-12-08 06:42 UTC
Labels: upstream, electron, trackpad/scroll
