### ISSUE TITLE
ts: No error for invalid default import w/o tsconfig.json

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/vscode#17480] opened 2016-12-18 09:52 UTC
- VSCode Version: 1.9.0-insider (typescript@2.1.4/2.2.0-dev20161218)
- OS Version: Windows 10 64

Steps to Reproduce:

1. Create an empty directory
2. Add a single `.ts` file with the following text.
3.  ```ts
    declare module 'commonjs' {
        export = class { };
    }

    declare module '' {
        import commonjs from 'commonjs';
    }
    ```
    Note that no errors are displayed
3. Create a file named tsconfig.json
4. Note that the following error is reported `Module ''commonjs'' has no default export.`

The example code is deliberately contrived to provide a minimal repro, but the behavior itself is observable across source and declaration files whenever there is no tsconfig.json file present. 
This is also the case in subdirectories of the open directory when a parent directory contains a `tsconfig.json` file _excluding_ the file containing the incorrect code.

If a `tsconfig.json` file is added, even if its contents are invalid JSON, the error is correctly reported.

**Comment by mjbvz** [comment] 2016-12-19 22:35
I believe this is by design. Let me explain.

When no `tsconfig.json` exists, we create a inferred TypeScript project. This inferred project sets a few default TypeScript compiler configurations, including `"allowSyntheticDefaultImports": true` and `"module": "CommonJS"`. `allowSyntheticDefaultImports` is what suppresses the `no default export` error in this case. These defaults were selected in order to cover the largest number of use cases and provide a better editor experience.

When you create a `tsconfig.json`, we now use that to configure the project. This overrides all the default values we previously supplied by VSCode, to instead fallback on  the defaults that TypeScript itself provides. And by default, TypeScript sets `allowSyntheticDefaultImports` to false, which is why you see the error. You would see the same error if you ran `tsc` directly without configuring the `tsconfig.json`.

I recommend that you explicitly provide a `tsconfig.json` and configure `allowSyntheticDefaultImports` and `module` as needed. Please let me know if that is unclear or you have any questions.

Thanks

**Comment by aluanhaddad** [comment] 2016-12-20 17:28
@mjbvz I am aware of those settings, which is precisely why I filed the issue here instead of on the TypeScript repo.

Specifically see this issue https://github.com/Microsoft/TypeScript/issues/10895
It says that the default is to set `"allowSyntheticDefaultImports": true` by default for JavaScript, not TypeScript sources. The reasoning in that issue is that JavaScript projects are often using Babel which performs this sort of translation.

**Comment by aluanhaddad** [comment] 2016-12-23 17:57
@egamma based on the discussion in Microsoft/TypeScript#10895 it seems like this was only intended to apply to inferred JavaScript projects.

**Comment by egamma** [comment] 2016-12-25 17:05
@aluanhaddad @mjbvz here is some history

Setting `allowSyntheticDefaultImports: true` was only intended to be the default for JavaScript projects to simplify the setup. When we simplified the project setup so that you get better defaults without a jsconfig/tsconfig.json we lost this distinction and we now always enable it now by default. I can see that this can be confusing/inconsistent when you do TypeScript development. 

@mjbvz I suggest to investigate whether we can only set `allowSyntheticDefaultImports` for JavaScript and not TypeScript projects.

**Comment by aluanhaddad** [comment] 2016-12-25 17:14
@egamma Thank you very much for clarifying and for providing the historical context around the current behavior.

**Comment by mjbvz** [comment] 2017-04-11 23:27
It is not possible to specify separate default configs for loose js vs ts files. Without a tsconfig or jsconfig, JS and TS files are loaded into to the same implicit project which shares our default config. This is by-design

As noted in the original issue, if you run into this problem while working in a TypeScript project, just create a `tsconfig`. This will override the default `allowSyntheticDefaultImports` config value and also let VSCode know that it should treat all TS files in the workspace as part of a single, well-defined project

Closing as by-design

**Closed by mjbvz** 2017-04-11 23:27 UTC
Labels: as-designed, javascript, typescript

**Comment by aluanhaddad** [comment] 2017-04-12 03:16
@mjbvz Thank you for looking into this further. Also, thank you for taking the time to explain why a fix is not possible.
