### ISSUE TITLE
Crashes after click several times on refresh on side bar

### ISSUE THREAD

**Issue by oscarojeda** [Microsoft/vscode#69451] opened 2019-02-26 12:46 UTC
Issue Type: <b>Bug</b>

Crashes after click several times quickly on refresh on side bar

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (7.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
tslint|eg2|1.0.43
Angular-BeastCode|Mik|7.2.4
debugger-for-chrome|msj|4.11.2

</details>

**Comment by rebornix** [comment] 2019-02-26 18:09
Duplicate of https://github.com/Microsoft/vscode/issues/68424

**Closed** 2019-02-26 18:09 UTC
Labels: *duplicate
