### ISSUE TITLE
Feature Request: planned support for Q#?

### ISSUE THREAD

**Issue by alongalky** [Microsoft/vscode#40644] opened 2017-12-21 12:21 UTC
Microsoft recently released their [Quantum Development Kit](https://marketplace.visualstudio.com/items?itemName=quantum.DevKit), which looks amazing but is unfortunately only available for VS / Windows.

Are there plans to release a VS Code compatible version of it? I would love to see it.

**Comment by weinand** [comment] 2017-12-21 13:34
Duplicate of https://github.com/Microsoft/Quantum/issues/16

**Closed by weinand** 2017-12-21 13:34 UTC
