### ISSUE TITLE
Zoomed in after update to 1.49

### ISSUE THREAD

**Issue by bergwerf** [microsoft/vscode#108123] opened 2020-10-05 14:46 UTC
- VSCode Version: 1.49.3
- OS Version: Debian 10

Steps to Reproduce:

1. Install VSCode 1.48.2 and take a screenshot
2. Install VSCode 1.49.3 and take a screenshot

Does this issue occur when all extensions are disabled?: Yes

After updating to 1.49 the whole window got zoomed in by some tiny amount, and all icons became burry (it also feels like the code font is less comfortable to read now). I have tried resetting the zoom level and zooming in and out. I am very surprised this issue has (apparently) not happened to anyone else yet. Here are two screenshots from before and after the issue. I searched the HTML for some hidden CSS scale transformation, but couldn't find anything. I think it is unlikely this is caused by hardware, since the entire view is scaled.

![vscode_1 48](https://user-images.githubusercontent.com/4458965/95094457-37231900-072a-11eb-8707-afa513259caa.png)

![vscode_1 49](https://user-images.githubusercontent.com/4458965/95094477-3be7cd00-072a-11eb-97cc-af062865d029.png)

**Comment by bergwerf** [comment] 2020-10-05 14:56
The zoom level to approximately return the the previous scale is `-0.861`. At this level the icons are not blurry, and text rendering is better.

**Comment by bergwerf** [comment] 2020-10-05 15:03
Wow I finally fixed this. It turns out the new Chromium has some silly way of guessing your device pixel ratio, and guessed mine wrong (chromium itself was blurry too). I have to launch with `--force-device-scale-factor=1`. Perhaps code could add this as setting (I don't know if chromium is going to fix this anytime soon).

**Comment by deepak1556** [comment] 2020-10-08 07:09
Can you check if the issue is resolved with our exploration builds that has newer chromium runtime

* [Snap](https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration-1600880002.snap)
* [Deb](https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration_1.50.0-1600879342_amd64.deb)
* [Unsigned Archive](https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration-x64-1600879613.tar.gz)

**Comment by grigorig** [comment] 2020-10-09 19:33
@bergwerf This also seems to fix #106540. Nice! It looks like Chromium tries to do some fancy fractional scaling, and sharp text rendering doesn't really cooperate with that. Forcing the scale to 2 however looks sharp, too.

It would be cool if we could use this option in argv.json.

**Comment by deepak1556** [comment] 2020-10-09 19:56
@bergwerf @grigorig since this is an issue with chromium, can you open a bug at https://bugs.chromium.org/p/chromium/issues/list , you can use https://vscode-web-test-playground.azurewebsites.net/?enter=true as an example. I want to make sure the bug is captured by chromium team. Thanks!

**Comment by bergwerf** [comment] 2020-10-09 23:35
@deepak1556 That makes sense, only I am not really interested in endless debugging on my end (which is more or less my experience with these types of bugs). Since this should affect plenty of users I expect Chromium will pick it up sooner or later (or perhaps already did), and `--force-device-scale-factor` is a fine workaround for me :).

**Comment by deepak1556** [comment] 2020-10-22 18:02
Closing this out, as there is nothing actionable at the moment. If we can report the issue to chromium, can reopen.

**Closed by deepak1556** 2020-10-22 18:02 UTC
Labels: chromium, needs more info, zoom
