### ISSUE TITLE
Breakpoints with conditions

### ISSUE THREAD

**Issue by xerosugar** [microsoft/vscode#79804] opened 2019-08-26 10:48 UTC
Issue Type: <b>Feature Request</b>

- Can breakpoints be made a little bit bigger, so they're easier to click?
- Should the breakpoint menu have an option for 'Remove conditions'?

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment] 2019-08-27 07:54
1. We could make the breakpoint icons bigger once we allow customisiation of our icons. Which @misolori is working on I believe
2. I think that would lead to clutter. Currently you have Edit Breakpoint and you can just clear the expression

Anyways closing 2 as designed, and 1 should be a duplicate of making all icons customisable.

**Closed by isidorn** 2019-08-27 07:54 UTC
Labels: debug
