### ISSUE TITLE
Preset of extensions

### ISSUE THREAD

**Issue by severusDude** [microsoft/vscode#97755] opened 2020-05-13 21:36 UTC
### Feature
Feature to save, and load a preset of extension that is enabled, additionally, it can also manipulate the extension setting set up by the user. So there will be an option to load a preset from the extensions menu.

**Comment by sandy081** [comment] 2020-05-18 12:19
/duplicate

There is a duplicate of this issue already. I would request to go through the issues tagged with `extension` label and `feature request`.

**Closed** 2020-05-18 12:20 UTC
Labels: *duplicate
