### ISSUE TITLE
Directory name shows up twice in shell status line

### ISSUE THREAD

**Issue by aig787** [Microsoft/vscode#28359] opened 2017-06-09 15:37 UTC
- VSCode Version: Version 1.13.0 (1.13.0)
- OS Version:
- Prezto Theme: zstyle ':prezto:module:prompt' theme 'agnoster'

Steps to Reproduce:

1. Open integrated terminal
2. Navigate to any directory

Integrated terminal:
![screen shot 2017-06-09 at 8 32 56 am](https://user-images.githubusercontent.com/4955443/26982853-9e3acc2c-4cee-11e7-847d-389418abcc07.png)

iTerm2:
![screen shot 2017-06-09 at 8 34 41 am](https://user-images.githubusercontent.com/4955443/26982857-a0c7ddd6-4cee-11e7-8aca-78bc66428b9b.png)

**Comment by utsav91** [comment] 2017-06-09 15:41
I am facing the same issue :\

https://stackoverflow.com/questions/44460239/vs-code-integrated-terminal-shows-path-twice

**Comment by hjones2199** [comment] 2017-06-09 17:38
Same problem when using zsh powerline, but when I switch to bash shell with default $PS1 variable this doesnt occur.

**Comment by alexsasharegan** [comment] 2017-06-09 18:13
Same issue. Using zsh on vscode Version 1.13.0 (1.13.0)

![vscode-bug](https://user-images.githubusercontent.com/16269252/26988515-9e5e4740-4d04-11e7-8e57-aad4e4499de5.gif)

**Comment by milosbunijevac** [comment] 2017-06-09 23:12
Same.

**Comment by DarthOstrich** [comment] 2017-06-09 23:44
Same Issue

**Comment by AaronSum** [comment] 2017-06-10 10:05
Same here

**Comment by TomasDuda** [comment] 2017-06-12 12:29
Dupe of #26038.

**Comment by ramya-rao-a** [comment] 2017-06-12 18:15
Thanks @TomasDuda 

Closing as duplicate

cc @Tyriar

**Closed by ramya-rao-a** 2017-06-12 18:15 UTC
Labels: new release
