### ISSUE TITLE
code actions to fix problems doesn't work by mouse click

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode#78713] opened 2019-08-08 16:12 UTC
Issue Type: <b>Bug</b>

1. **hover** on the error and select `quick fix`.
2. click the quick fix actions and it doesn't work.

but if you use combo `Ctrl+.` and select some `quick fix` action,it will work.

don't know why??

I thought this is not an extentsion bug,it shows everywhere.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
gitlens|eam|9.9.3
beautify|Hoo|1.5.0
python|ms-|2019.8.29288
cpptools|ms-|0.24.1
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.8.1
java|red|0.47.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by JoeyRxy** [comment] 2019-08-08 16:14
when i use code-insiders version,there's no problem.

it's funny.

**Comment by Hexman768** [comment] 2019-08-09 00:00
Have you tested for this issue against multiple languages and files or just all in the same file?

**Comment by JoeyRxy** [comment] 2019-08-09 16:32
> Have you tested for this issue against multiple languages and files or just all in the same file?

many languages.

and i use another computer,this didn't happen.

I have uninstall the vscode,including delete the .vscode and other folders.But it doesn't make any difference.

**Comment by Hexman768** [comment] 2019-08-10 01:14
Did these other computers have the same operating system? What are the differences between the machines?

**Comment by JoeyRxy** [comment] 2019-08-10 01:45
os:win10

today I try another computer,and it works.

Don't know why.Now I install the .zip version,hope it can uninstall completely if the problem shows again.

**Comment by Hexman768** [comment] 2019-08-10 05:09
When you say it works, do you mean that you no longer see the defect? When
you attempt the uninstall, let me know, thanks!

Sincerely,.
Zachary Pedigo

**Comment by JoeyRxy** [comment] 2019-08-11 13:40
@Hexman768 I use another computer which is totally new,and yes,the `fix problem` works by mouse-click.

at the computer the bug shows,I have reinstalled vscode.when I uninstall it,I first execute the uninstall program,then delete some folders whose name contains "vscode",just like some tutorials for clear uninstallation.

I don't think it uninstall clearly(but i don't know how),so that the bug shows when i reinstall vscode.

**Comment by mjbvz** [comment] 2019-08-12 17:53
Duplicate of #77018

Should be fixed in 1.37

**Closed by mjbvz** 2019-08-12 17:53 UTC
