### ISSUE TITLE
CONTROL-C does not terminate process

### ISSUE THREAD

**Issue by PaoloTCS** [microsoft/vscode#178894] opened 2023-04-01 16:16 UTC
Type: <b>Bug</b>

Created a django project, then python manage.py runserver.  Runs fine.  Then tried CONTROL-C (once) no response, (twice) just echos. Had to exit with ...sudo lsof -t -i tcp:8000 | xargs kill -9. 

VS Code version: Code - Insiders 1.78.0-insider (f31dffc7f9b93a1cdef21243ec30dea7d489a615, 2023-03-31T01:49:42.343Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.28GB free)|
|Process Argv|--crash-reporter-id 6506fe60-4c4f-4c15-8a92-d89ace907083|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
django-html|bib|1.3.0
python-environment-manager|don|1.0.4
gitlens|eam|13.4.0
vscode-html-css|ecm|1.13.1
code-runner|for|0.12.0
geniebuilder|Gen|0.2.6
codespaces|Git|1.14.3
copilot|Git|1.78.9758
gc-excelviewer|Gra|4.2.57
todo-tree|Gru|0.0.224
haskell|has|2.2.2
language-haskell|jus|3.6.0
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
dotnet-interactive-vscode|ms-|1.0.4172011
vscode-edge-devtools|ms-|2.1.1
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.18.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
isort|ms-|2023.9.10861010
python|ms-|2023.7.10901017
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.289.0
azure-account|ms-|0.11.3
azurecli|ms-|0.5.0
sqltools|mtx|0.27.1
phoityne-vscode|pho|0.0.29
java|red|1.16.0
LiveServer|rit|5.7.9
autoimport|ste|1.5.4
vscode-djaneiro|the|1.4.2
haskelly|UCL|0.5.5
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.10
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30659908
pythonb192:30661256
defaultazurewalk:30687958
pythonms35:30671666
j16hj152:30680472
57b77579:30687741
pythonclientmv:30700173

```

</details>

**Comment by tamuratak** [comment] 2023-04-01 22:20
Duplicate of  #178693

**Closed** 2023-04-03 15:01 UTC
Labels: triage-needed
