### ISSUE TITLE
Useful error message should be given when uninstall extension

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#26504] opened 2017-05-12 03:30 UTC
- VSCode Version: 1.12.1
- OS Version: Microsoft Windows [Version 10.0.15063]

Steps to Reproduce:

1. Install extension attached with command line `code --install-extension vscode-arduino-0.2.1.vsix`
[vscode-arduino-0.2.1.zip](https://github.com/Microsoft/vscode/files/994978/vscode-arduino-0.2.1.zip)
2. Open vscode to make sure the extension is enabled
3. Remain vscode open, and uninstall the extension with command line `code --uninstall-extension vsciot-vscode.vscode-arduino`
4. See the error message

The error message is `[ [ [ , , , , , , , , , , , , , , [Object] ], [ , , [Object] ] ] ]`

![snipaste20170512_112134](https://cloud.githubusercontent.com/assets/1621293/25981197/47f9f08e-3706-11e7-92e6-faf6fab7eefc.png)

**Comment by joaomoreno** [comment] 2017-05-12 07:56
Can you check the contents of `~/.vscode/extensions`? Was the extension uninstalled?

**Comment by Sneezry** [comment] 2017-05-15 06:01
**Figure 1:** After I installed the extension, I checked vscode to confirm the extension is enabled, and I can find the extension in `~/.vscode/extensions` folder.
![1](https://cloud.githubusercontent.com/assets/1621293/26044347/4eb5fc70-3976-11e7-803d-99300d5c6ef6.png)

**Figure 2:** I uninstalled the extension remaining vscode open, I can see the error, and the extension is still in  `~/.vscode/extensions` folder.
![2](https://cloud.githubusercontent.com/assets/1621293/26044408/baaf370c-3976-11e7-9377-493fd89a89cf.png)

**Figure 3:** Then I restart vscode without doing anything, the extension is removed from `~/.vscode/extensions` folder.
![3](https://cloud.githubusercontent.com/assets/1621293/26044424/d5b249c2-3976-11e7-893c-dce8a50963c7.png)

**Comment by joaomoreno** [comment] 2017-05-17 12:12
I could repro in stable, but I believe this is a dupe of another issue I fixed last week, since I can't repro in Insiders.

Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by Sneezry** [comment] 2017-05-18 09:23
I can confirm that the issue has been fixed in Insider release. Could you provide more information when will this issue be fixed in stable release? Thanks.

**Comment by joaomoreno** [comment] 2017-05-19 09:40
Early June.

**Closed by joaomoreno** 2017-05-19 09:40 UTC
Labels: needs more info
