### ISSUE TITLE
Unable set Ctrl+/ for Toggle Line Comment

### ISSUE THREAD

**Issue by diogoca** [Microsoft/vscode#24218] opened 2017-04-07 12:06 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-70-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.4|;

---

Steps to Reproduce:

1. Go to Keyboard Shortcuts
2. Search "Toggle Line Comment"
3. Try to set CTRL + /

Keybinding will bind: CTRL + unknown

Ps: On previous update was working... My keyboard is Wireless Keyboard 800 with Ç letter

**Comment by chrmarti** [comment] 2017-04-07 15:07
Which keyboard layout is this?

**Comment by rafaelcneves** [comment] 2017-04-07 18:20
The same here.
And if I add this manually throws an error to me.
![image](https://cloud.githubusercontent.com/assets/421754/24813767/b4ac780e-1ba5-11e7-9dae-b30e7eca1686.png)

**Comment by alexandrudima** [comment] 2017-04-10 08:37
@rafaelcneves You might be suffering from a different issue. Please open a separate issue and include your keyboard layout. I can then proceed to analyze what is going on under the respective keyboard layout.

@diogoca 

### Can you please let us know what your keyboard layout is?
### What scan code do we receive from Electron when you press this key combination?
 - open Preferences > Keyboard Shortcuts
 - click on `keybindings.json`
 - on the right hand side editor click on Define Keybinding
 - press the key combination that has a problem
 - hover with the mouse over the input box
 
![image](https://cloud.githubusercontent.com/assets/5047891/24852340/62543a40-1dd7-11e7-8b4e-b9be991d1eb9.png)

**Comment by diogoca** [comment] 2017-04-10 11:28
@alexandrudima yeah

Keyboard layout: Portuguese (Brazilian) 

![image](https://cloud.githubusercontent.com/assets/692065/24859363/97f414b0-1dc6-11e7-9030-f92c776168c7.png)

Scan code from Electron (pressed CTRL + /)

![image](https://cloud.githubusercontent.com/assets/692065/24859554/74096e1e-1dc7-11e7-9fbb-2e9a7697b7e5.png)

**Comment by alexandrudima** [comment] 2017-04-10 11:56
@diogoca Thank you for following through. I cannot reproduce on Ubuntu 16.04 using the same keyboard layout.

I get `code: Slash, keyCode: 191, key: /` and not `code: IntlRo, keyCode: 191, key: Unidentified`. What linux distribution are you using? Are you using Linux installed on real hardware and connected with a keyboard or are you using some sort of remoting software?

**Comment by alexandrudima** [comment] 2017-04-10 14:58
Duplicate of #24147 -- IntlRo should not map to `KeyCode.Unknown`.

**Closed by alexandrudima** 2017-04-10 14:58 UTC
Labels: keybindings, keyboard-layout, linux, needs more info

**Comment by diogoca** [comment] 2017-04-10 17:04
Hi,

sb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

Real hardware with [wireless keyboard](https://www.microsoft.com/accessories/pt-br/d/wireless-keyboard-800). I think that Linux is using native remote software, once that I did not install any other software.

**Comment by rafaelcneves** [comment] 2017-04-10 17:46
@alexandrudima I'm sorry, but It's unlikely to be a different issue.. I have the same keyboard layout of @diogoca, and if I try to do the same of him I got the same issue..
![screenshot from 2017-04-10 14-38-24](https://cloud.githubusercontent.com/assets/421754/24874720/0a193612-1dfc-11e7-91a5-96ed88aab449.png)

**Comment by diogoca** [comment] 2017-04-11 14:18
https://github.com/Microsoft/vscode/issues/24147#issuecomment-292553461 fix that...
