### ISSUE TITLE
Auto Indent doesn't outdent

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29722] opened 2017-06-28 08:55 UTC
re #29492

See recording, the line indents but doesn't outdent when moving down (it weirdly does when moving up). I do have omnisharp-vscode installed and running.  

![jun-28-2017 10-53-54](https://user-images.githubusercontent.com/1794099/27628740-44be73fe-5bf0-11e7-91e5-c5599c313980.gif)

```cs
using System;
using System.Threading.Tasks;

namespace ConsoleApplication
{

    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            System.Console.WriteLine();
            System.Console.WriteLine();
        }

        static void Bar()
        {

            var task = new Task(() =>
            {
                var work = 1234;
            });


            Task.WaitAny(new Task[] { task });

            Console.WriteLine('\0');
            var foo = true;
        }
    }
}


```

**Comment by rebornix** [comment] 2017-06-28 23:03
Shares the same root cause for https://github.com/Microsoft/vscode/issues/29669 . We don't have indentation rules yet. The reason that you see the indent is our bracket logic. I know it looks weird as it behaves like half support of auto indent. But we may not want to rush in a simple indentation rules for C# language at this moment.

BTW, I'll call out which languages have indentation rules set and let extension authors know they can now add indentation rules to their exts.

**Comment by jrieken** [comment] 2017-06-29 06:56
Should we maybe use stupid line move when there are no indentation rules?

**Comment by rebornix** [comment] 2017-06-29 14:44
@jrieken yes, your suggestion is better in this case.

**Comment by rebornix** [comment] 2017-11-21 22:53
For C# language, we don't have indentation rules or onEnter rules, then even if the autoindent is on, moving lines will not try to be smart 

![norules-nosmartmove](https://user-images.githubusercontent.com/876920/33101064-a2a906e8-cecb-11e7-9826-ce3321dc929c.gif)

Close this for now. If we have issues with C# indentation (when there are rules for it), we then talk about them in new issues.

**Closed by rebornix** 2017-11-21 22:53 UTC
Labels: bug, editor-autoindent
