### ISSUE TITLE
Snippets not working on Insiders version

### ISSUE THREAD

**Issue by damir-sirola** [Microsoft/vscode#41380] opened 2018-01-10 08:34 UTC
- VSCode Version: 1.20.0-insider (2018-01-09)
- OS Version: macOS High Sierra 10.13.2

Steps to Reproduce:

1. Install any extension for snippets
2. Try to use snippets - they are not showing in autocomplete list

Does this issue occur when all extensions are disabled?: Not applicable, I use snippets provided by extension

Note: I have both insiders and regular version which have completely the same setup (synced via Settings Sync extension) and everything works fine on the regular version.

Let me know if you need any more info.

**Comment by jrieken** [comment] 2018-01-10 16:38
duplicate of #41207

**Closed by jrieken** 2018-01-10 16:38 UTC
Labels: extensions, insiders
