### ISSUE TITLE
css

### ISSUE THREAD

**Issue by PandaDesigner** [microsoft/vscode#205713] opened 2024-02-20 16:32 UTC
Type: <b>Bug</b>

The ability to complete CSS is lost and it is not resolved even by reinstalling, at least on Mac it does not work

VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 98b08ba7-bf05-48ba-99a8-d68f8898b750|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (110)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
react-vsc-essentials|agu|1.0.0
TabOut|alb|0.2.2
aws-toolkit-vscode|ama|2.10.0
tailwindcss-extension-pack|and|1.1.4
html-end-tag-labels|ant|1.0.0
vs-code-css-comments|ash|1.0.5
astro-vscode|ast|2.7.5
tailwind-docs|aus|2.1.0
emojisense|bie|0.10.0
file-browser|bod|0.2.11
vscode-tailwindcss|bra|0.10.5
vscode-toggle-quotes|Bri|0.3.6
simple-react-snippets|bur|1.2.7
prettier-vscode-standard|bys|0.22.1
turbo-console-log|Cha|2.10.4
vscode-css-modules|cli|0.5.1
gitignore|cod|0.9.0
postcss|css|1.0.9
vscode-markdownlint|Dav|0.54.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
vscode-go-syntax|dun|0.0.18
bracket-pair-toggler|dzh|0.0.3
css-flexbox-cheatsheet|dzh|3.3.4
css-initial-value|dzh|0.2.6
tailwindcss-highlight|ell|2.0.0
prettier-vscode|esb|10.1.0
nest-essentials|Est|0.0.6
nestjs-snippets-for-vscode|Est|0.1.0
comment-anchors|Exo|1.10.4
git-project-manager|fel|1.8.2
figma-vscode-extension|fig|0.3.3
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vscode-nesttypeorm|fuh|1.7.3
vscode-pull-request-github|Git|0.80.1
gitpod-desktop|git|0.0.164
live-sass|gle|6.1.2
go|gol|0.41.0
go-nightly|gol|2024.2.1618
vscode-graphql|Gra|0.9.1
vscode-graphql-syntax|Gra|1.3.2
activitusbar|Gru|0.0.47
prettier-eslint-typescript|hb4|1.0.5
headwind|hey|1.7.0
bootstrap-intellisense|hos|1.1.10
easy-snippet|inu|0.7.5
hungry-delete|jas|1.7.0
better-dockerfile-syntax|jef|1.0.2
vscode-colorize|kam|0.11.1
auto-comment-blocks|kev|1.0.1
glass-theme-doyle|Kra|2.6.0
graphql-for-vscode|kum|1.15.3
vs-color-picker|lih|1.0.0
tailwind-sass-syntax|mac|1.3.0
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
goto-next-previous-member|mis|0.0.6
vscode-open-in-sourcetree|mor|0.6.0
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.29.0
vscode-language-pack-es|MS-|1.85.2024021409
remote-containers|ms-|0.346.0
remote-ssh|ms-|0.109.2024021915
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
go-doc|msy|1.0.1
console-flash|NAP|0.1.0
particle-vscode-pack|par|1.16.14
particle-vscode-snippets|par|1.16.14
convert-css-in-js|pau|1.1.3
translate-it|pho|1.9.0
material-icon-theme|PKi|4.34.0
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.4.1
prisma|Pri|5.10.0
vscode-css-navigation|puc|1.14.0
quicktype|qui|12.0.46
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
vs-code-prettier-eslint|rve|6.0.0
partial-diff|ryu|1.4.3
smart-css-autocomplete|sai|1.5.3
svg-preview|Sim|2.8.3
html-to-css-autocompletion|sol|1.1.2
vscode-stylelint|sty|1.3.0
prettier-plus|svi|4.2.2
sass-indented|syl|1.8.29
railway-vscode|Tec|0.1.24
lorem-ipsum|Tyr|1.3.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.7.0
mui-snippets|vsc|1.0.1
console-ninja|Wal|1.0.287
quokka-vscode|Wal|1.0.627
wallaby-extension-pack|Wal|1.0.1
wallaby-vscode|Wal|1.0.371
JavaScriptSnippets|xab|1.8.0
vsmarketplace-badges|Xua|1.0.3
vscode-surround|yat|1.5.0
snippets-next-13|yuz|0.2.1
vscode-css-intellisense|zen|0.4.0

(31 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
a89i1917:30961429
7j2b6412:30967274
ccp2r3:30958157

```

</details>

**Comment by aeschli** [comment] 2024-02-21 14:58
Does it reproduce with all extension disabled?
Is the language mode of the editor (shown in the status bar) `css`?

Please provide a small sample....

**Comment by aeschli** [comment] 2024-12-10 16:13
Closing due to lack of reproducible steps

**Closed by aeschli** 2024-12-10 16:13 UTC
