### ISSUE TITLE
Title Case Command

### ISSUE THREAD

**Issue by fingerskier** [Microsoft/vscode#72143] opened 2019-04-11 14:56 UTC
I would like a 'Title Case' command that capitalizes the first letter of each word in a selected string.

e.g.:  the quick, sleek ninny-muggins.

Title Case command would alter to this:

The Quick, Sleek Ninny-Muggins.

Leaving punctuation and spaces as-is.

**Comment by alexwhitman** [comment] 2019-04-11 15:48
The `change-case` extension will do just that. https://github.com/wmaurer/vscode-change-case

**Comment by jmbockhorst** [comment] 2019-04-12 00:28
This feature has been added already (#70990) and should come in the April update. Also related to #70858.

**Comment by aeschli** [comment] 2019-04-12 08:47
duplicate of #70990

**Closed by aeschli** 2019-04-12 08:47 UTC
