### ISSUE TITLE
Feature Request - border around active or inactive selection

### ISSUE THREAD

**Issue by greggb** [Microsoft/vscode#41908] opened 2018-01-20 14:54 UTC
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (d21e6a3e388897a2250cb10ae897b6481e0bd61d, 2018-01-19T07:10:59.044Z)</li>
	<li>OS Version: Darwin x64 17.4.0</li>
	<li>Extensions: none
(1 theme extensions excluded)</li>
</ul>

---
I'm finding it difficult to find my current active selection when there are multiple matching symbols. The highlighting of matching symbols is a helpful feature, but once I double click it would be helpful to set a border around the active selection or matching symbols so I can find the selection more easily as I scan the code.

I've tried tweaking just about every highlight combination with `colorCustomizations`, but haven't been able to get something that works well.

Steps to Reproduce:
Using all default settings and colors this is what currently displays:

**Single click on word**
<img width="404" alt="screen shot 2018-01-20 at 9 43 27 am" src="https://user-images.githubusercontent.com/514026/35184664-ba7a9b68-fdc6-11e7-890a-a21bd8b2d5ab.png">

**Double click on word**
<img width="405" alt="screen shot 2018-01-20 at 9 43 46 am" src="https://user-images.githubusercontent.com/514026/35184670-c58f190c-fdc6-11e7-899d-b7703c44bf17.png">

Notice without the cursor you can't tell which word is selected and will change when typing. Depending on the user's theme the cursor may be very subtle.

![wordselect](https://user-images.githubusercontent.com/514026/35184757-ad7129a4-fdc7-11e7-9c01-a2a36b1f249d.gif)

If I've missed a setting please let me know.

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2018-02-16 11:13
duplicate of #30793

**Comment by aeschli** [comment] 2018-02-16 11:13
duplicate of #30793

**Closed by aeschli** 2018-02-16 11:13 UTC
Labels: editor-rendering, feature-request
