### ISSUE TITLE
Graphics / window only 3/4 of display when VSCode launched

### ISSUE THREAD

**Issue by BillDietrich** [microsoft/vscode#67006] opened 2019-01-23 18:19 UTC
When launching VSCode, I have it always starting in full-screen mode (VSCode window uses whole display).  Sometimes, maybe 1 in 30 times, it doesn't paint the right-hand 1/4 of the display, letting the desktop background show.  See attached screenshot.  If I bring some other app to foreground, then bring VSCode to foreground again, it paints the whole screen correctly.

Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-43-generic

Does this issue occur when all extensions are disabled?: Yes

System:    Host: laptop1 Kernel: 4.15.0-43-generic x86_64 bits: 64 Desktop: Cinnamon 4.0.9 Distro: Linux Mint 19.1 Tessa 
Machine:   Type: Portable System: Dell product: Inspiron N5010 v: A11 serial: <root required> 
           Mobo: Dell model: 0WXY9J v: A11 serial: <root required> BIOS: Dell v: A11 date: 01/06/2011 
CPU:       Topology: Dual Core model: Intel Core i3 M 370 bits: 64 type: MT MCP L2 cache: 3072 KiB 
           Speed: 1467 MHz min/max: 931/2394 MHz Core speeds (MHz): 1: 1077 2: 1202 3: 1447 4: 1378 
Graphics:  Device-1: Intel Core Processor Integrated Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel Ironlake Mobile v: 2.1 Mesa 18.0.5 

![screenshot from 2019-01-22 18-14-37](https://user-images.githubusercontent.com/36999178/51627784-81a73680-1f43-11e9-8c2c-4c6cd95a5026.png)

**Comment by sbatten** [comment] 2019-01-23 18:46
do you have any other apps based on electron that you can get this to reproduce? https://electronjs.org/apps I was unable to reproduce this behavior, myself.

**Comment by sbatten** [comment] 2019-01-23 18:47
fyi @bpasero

**Comment by bpasero** [comment] 2019-01-24 08:06
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by BillDietrich** [comment] 2019-01-24 13:20
I tried launching via "code" on CLI, then quitting.  Did that about 15 times before the bug occurred again.  An interesting thing: even though I had other windows covering up the desktop, what showed was the desktop background again (just as shown in the image I posted for this bug), not any of the other app windows that were covering the desktop.

I will see if I can try the insider build.

**Comment by BillDietrich** [comment] 2019-01-24 14:41
Can't reproduce it, using:

Version: 1.31.0-insider
Commit: 50854c0a705745bbf50982fab3c30fd6bd1f7b19
Date: 2019-01-24T10:16:12.982Z
Electron: 3.1.0
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-43-generic

I tried launching VSCode about 200 times, in various configurations of open file-editors and the two extensions I use.  Couldn't make the problem happen.  I'll use insider as my daily driver from now on, will keep checking.

**Comment by BillDietrich** [comment] 2019-01-25 08:43
Okay, I've nailed how to reproduce the problem.  It happens on the first launch of VSCode after system boot.  Did it three times in a row this morning, using insiders build.

**Comment by sbatten** [comment] 2019-01-25 18:08
@bpasero looks like it isn't fixed in latest electron if @BillDietrich can now reproduce with latest insiders

**Comment by BillDietrich** [comment] 2019-01-25 20:54
Just installed an update of code-insiders, problem still happens, first time I run insiders after booting, starting up with window maximized.  Now my insiders About says:

Version: 1.31.0-insider
Commit: 9fe48f15b1a252a0e9e1ef5975301203baf10b8a
Date: 2019-01-25T08:13:32.146Z
Electron: 3.1.0
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-43-generic

**Comment by BillDietrich** [comment] 2019-01-28 08:18
I was about to say that the problem hasn't happened the last couple of mornings when I booted the system and ran insiders.  Not sure what's changed.  Still have:

Version: 1.31.0-insider
Commit: 9fe48f15b1a252a0e9e1ef5975301203baf10b8a
Date: 2019-01-25T08:13:32.146Z
Electron: 3.1.0
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-43-generic

I will try the exploration build.

**Comment by bpasero** [comment] 2019-01-28 08:22
OK

**Comment by BillDietrich** [comment] 2019-01-28 09:56
Okay, still using insiders,  problem still happens, my insiders version now is:

Version: 1.31.0-insider
Commit: 1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c
Date: 2019-01-28T06:14:17.311Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-43-generic

I'm starting to think this is related to internet access, but I can't quite nail it down.  It's something like:
- if ethernet cable is plugged in, VPN working, 1st launch of VSCode gives problem
- if ethernet cable is pulled out, 1st launch of VSCode is okay
- not sure about case where ethernet is plugged in, VPN is turned off so no network access, I seemed to get inconsistent results, there may be other variables

**Comment by bpasero** [comment] 2019-01-28 10:03
@BillDietrich the version I posted is called "Code Exploration" and is using yet a newer version of our UI framework, can you also try that? See https://github.com/Microsoft/vscode/issues/67006#issuecomment-458023382 for download links.

**Comment by BillDietrich** [comment] 2019-01-28 10:13
Problem still happens with:

Version: 1.31.0-exploration
Commit: 37818ac3597b4afda264b05226b0b77fb8e85f41
Date: 2018-12-13T07:37:56.224Z
Electron: 4.0.0-beta.9
Chrome: 69.0.3497.106
Node.js: 10.11.0
V8: 6.9.427.24-electron.0
OS: Linux x64 4.15.0-43-generic

![screenshot from 2019-01-28 11-10-28](https://user-images.githubusercontent.com/36999178/51829335-9f7eed80-22ed-11e9-834a-87b1b05637a1.png)


There's an update for exploration in the Update Manager, I'm going to apply that and test again.

**Comment by BillDietrich** [comment] 2019-01-28 10:21
Problem still exists in:

Version: 1.31.0-exploration
Commit: 2af86da220e2b4c213d8b81ec5232e37e015054b
Date: 2019-01-24T12:06:06.974Z
Electron: 4.0.2
Chrome: 69.0.3497.106
Node.js: 10.11.0
V8: 6.9.427.24-electron.0
OS: Linux x64 4.15.0-43-generic

**Comment by BillDietrich** [comment] 2019-01-28 11:02
Another piece of info: it seems if a CLI (terminal) window is the foreground window when I launch code-exploration for the first time after booting, the problem does not happen.  If a GUI window for another application (KeePassXC, in my case) is the foreground window when I launch code-exploration for the first time after booting, the problem DOES happen.

I tried launching it via code-exploration typed into CLI window, problem never happened.  Tried launching via Start menu with CLI window in foreground, problem didn't happen.  Tried launching via Start menu with KeePassXC window in foreground, problem happens.  I'm rebooting between each of these tries, so it's a slow process.

I don't see any error messages in CLI window when I launch from CLI.  Is there any debug-output or logging mode I can turn on, for VSCode or electron ?

**Comment by BillDietrich** [comment] 2019-01-28 11:50
Did some more testing, with inconsistent results.  Problem still occurs in cases where I have not launched KeePassXC, so it's not specific to that app.  Problem happened once when I booted and didn't launch any other apps, had a bare desktop when I launched code-exploration.  But another time doing same, problem did not occur.  Saw problem occur when I had booted and then launched only ShowFoto, then code-exploration.  Tried twice with launching only Gimp and then code-exploration, problem didn't happen either time.  So, anyway, it's not specific to some other particular app.

**Comment by BillDietrich** [comment] 2019-03-06 08:02
Update: haven't seen this problem in about 2 weeks now, using code-exploration.  Maybe something fixed it.  Will keep watching out for it.

**Comment by BillDietrich** [comment] 2019-05-15 15:52
Hasn't happened since February or so.  I've been using the exploration version.

**Comment by bpasero** [comment] 2019-07-01 06:27
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-07-01 06:27 UTC
Labels: electron, fixed-in-electron-4.0.x, upstream
