### ISSUE TITLE
No progress indicator when installing VSIX

### ISSUE THREAD

**Issue by dlebu** [Microsoft/vscode#40257] opened 2017-12-15 04:46 UTC
VSCode Version: Insiders 1.19.0
    OS Version: MacOS

Steps to Reproduce:

    Install an extension from vsix

Expected: Progress Indicator until the success message shows up
Actual: No Progress Indicator.

@ramya-rao-a

**Comment by egamma** [comment] 2017-12-18 14:46
@dlebu discussed it with @sandy081 and the plan is to show progress in the status bar as some other extensions (e.g. C#) do it when they download and install additional code.

**Comment by sandy081** [comment] 2018-01-29 20:33
Duplicate of #41759

**Closed** 2018-01-29 20:33 UTC
Labels: *duplicate, extensions, feature-request
