### ISSUE TITLE
auto-opening brackets after auto-completion of a function

### ISSUE THREAD

**Issue by MrOxMasTer** [microsoft/vscode#173231] opened 2023-02-03 01:09 UTC
I would like to suggest an idea. In VScode there is such a setting as javascript.suggest.completeFunctionCalls . It helps with autocomplete to immediately put both parentheses and parameters, but I don't need them. I don't need hints, and autocomplete parentheses will be very useful. So that you have an autofill function and parentheses with a carriage in the middle. There was a similar request: https://github.com/microsoft/vscode/issues/109997 . There, by example, a person shows what exactly is needed.

**Comment by MrOxMasTer** [comment] 2023-02-03 01:12
I do not know why this was not implemented, although it would be very convenient. Maybe there are some extensions that solve this problem?

**Comment by mjbvz** [comment] 2023-02-06 22:13
Closing as a duplicate of https://github.com/microsoft/vscode/issues/109997. There wasn't enough interest in this feature for us to prioritize implementing it, but an extension could potentially add this

**Closed by mjbvz** 2023-02-06 22:13 UTC
