### ISSUE TITLE
Ability to define extension profiles per project

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#69742] opened 2019-03-03 15:58 UTC
希望能够一次选择,在当前目录或是当前项目中可以禁用的扩展.
因为我安装了很多扩展,比喻vue,react,php,python等等,
如果我在使用vue开发项目时,在提示功能会有很多不属于vue的提示.
我在开发react的时候,会有很多其它的扩展增加了提示,导致我输入代码时无法正确选择我要的结果.经常会干扰了我的意图.所以希望能加一个选项,或是能够根据当前目录的结构或框架,自动检测或是提示建议我可以在本工作空间中禁用的扩展,防止各种提示功能都出来了. 
![11](https://user-images.githubusercontent.com/10474968/53697810-4b958600-3e10-11e9-9b66-1090c4c79cb3.png)
![22](https://user-images.githubusercontent.com/10474968/53697811-4b958600-3e10-11e9-9826-8c8b415a29a9.png)

**Comment by rebornix** [comment] 2019-03-04 00:28
It's saying listing extensions activated for current file and then users can easily disable some of them in batch.

**Comment by sandy081** [comment] 2019-03-04 08:55
May I know why user wants the list of active extensions on current file?

**Comment by lifetin** [comment] 2019-03-04 08:59
> It's saying listing extensions activated for current file and then users can easily disable some of them in batch.

You're partly right.
JS can exist in react, vue, or typescript

**Comment by buxiaoyang** [comment] 2019-03-04 13:30
This is an improvement request and the description follows in English:
"
_I want to be able to select extensions that can be disabled in the current directory or in the current project at one time.
Because I installed a lot of extensions, like VUE, reaction, PHP, Python, etc.
If I am using VUE to develop a project, there will be many prompts that are not part of VUE in the prompt function.
When I was developing the reaction, there were a lot of other extensions that added hints that caused me to incorrectly select the results I wanted when I entered the code. It often interferes with my intentions. So I hope to add an option or be able to automatically detect or suggest extensions that I can disable in this workspace based on the structure or framework of the current directory, preventing various prompts from coming out._
"

**Comment by sandy081** [comment] 2019-03-05 15:41
@lifetin You can go to extensions viewlet and disable the extensions you want. Is not it enough?

**Comment by lifetin** [comment] 2019-03-07 15:59
> @lifetin您可以转到扩展视图并禁用所需的扩展名。还不够吗？

不够的, 我需要一次禁用多个,一个个的禁用,太费时间了.
如果我安装了30-40个扩展,适用不同开发语言的扩展,有java,python,js,html,css,flutter,php,mysql等等
我把当前项目中不需要的扩展禁用,我要花不少时间,vscode本身就是为了提高工作效率的.如果不禁用当前项目不用的扩展,会慢很多,所以这是个非常重要的功能. 
最好是能增加禁用的选项.
我创建一个设置的选项,名称为vue ,然后我就选择关于vue中的扩展在这个项目中用,
我再创建一个java的选择,然后我把关于java的扩展选择.,
,这样自动禁用了暂时用不到的扩展.
然后每个项目可以根据一键选择我要开启的扩展.
这是个很棒的功能.望支持

-----------------------------------------------------------------------------------------------


Not enough. I need to disable more than one at a time. It's too time consuming.

If I install 30-40 extensions for different development languages, such as java, python, js, html, css, flutter, php, mysql, etc.

I disable unnecessary extensions in the current project. It takes me a lot of time. vscode itself is to improve work efficiency. If you do not disable unnecessary extensions in the current project, it will be much slower, so this is a very important function.

It's best to add disabled options.

I create a setting option named vue, and then I choose to use the extension in Vue in this project.

I'll create a choice for java, and then I'll make an extension choice for java.

This automatically disables temporarily unused extensions.

Then each project can choose the extension I want to open according to one key.

It's a great feature. Look for support.

**Comment by lifetin** [comment] 2019-03-10 09:33
今天我现在是用flutter 开发 app, 但是下面的这些扩展我暂时用不到了,我要一个个的手动来禁用它.
![66](https://user-images.githubusercontent.com/10474968/54083100-68731180-435a-11e9-91d3-5541602c4e67.png)

明天我要用vue开发项目,我又要把不是vue的扩展一个个来禁用.
![55](https://user-images.githubusercontent.com/10474968/54083088-33ff5580-435a-11e9-82f0-5bd8cb7e5d94.png)

后天我要用php开发,然后我又要把不用php的扩展一个个来禁止,

这样的体非常糟糕

---------------------------------------------------------------------------------------------------------
en:

Today I'm using flutter to develop apps, but I don't need the following extensions for the time being. I need to disable them manually one by one.

Tomorrow I'm going to develop projects with vue, and I'm going to disable extensions that aren't Vue one by one.

The day after tomorrow I'm going to develop with php, and then I'm going to ban php-free extensions one by one.

**Comment by sandy081** [comment] 2019-03-11 11:29
So you want to create a extension profiles and apply these profiles to the workspace?

**Comment by lifetin** [comment] 2019-03-11 11:46
> So you want to create a extension profiles and apply these profiles to the workspace?

如果能全局一键设置最好. 选择当前项目的环境,然后可以自由配置它的扩展.工作区的扩展,和这个可能没有什么关系
---------------------------------------------------------------------------------
If you can set the global one key best. Select the environment of the current project, then you can freely configure its extension. The extension of the workspace, and this may have nothing to do with

**Comment by sandy081** [comment] 2019-03-15 14:48
Duplicate of https://github.com/Microsoft/vscode/issues/57548

**Closed** 2019-03-15 14:49 UTC
Labels: *duplicate, extensions, feature-request

**Comment by lifetin** [comment] 2019-03-15 14:57
我觉得会多种开发语言的人，绝对会出现这样的问题。扩展安装多了，假如有100个，我换一个环境就要禁用多余的80个，这工作量太大了。
--------------------------------------------------------
I think people who can develop many languages will definitely have such problems. Extension installed more, if there are 100, I will change the environment to disable the excess 80, which is too much work.
