### ISSUE TITLE
VS Code Does Not Detect </body>

### ISSUE THREAD

**Issue by AlperSal** [microsoft/vscode#101198] opened 2020-06-27 20:43 UTC
Issue Type: <b>Bug</b>

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    *<*
</body>
</html>
```
As I show in ** this angel bracket seems red and it doesnt allows me to write code. When I write "<" the first recommendation is /body and when I choose another recommandation it just writes it like that --> "<h1" (No closing Angel bracket, no /h1, nothing).
I did test it on my brothers computer and it isnt a specific problem. It happens on my brothers pc too. I hope you guys can find a solution.

Video: https://streamable.com/r64h2f (Additional info on video)

"SoRy foR bAD EnglAnd."

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

Extensions: none

**Comment by AlperSal** [comment] 2020-06-27 20:50
And, I did unins VS Code and delete settings, extensions etc.

**Comment by crisz** [comment] 2020-06-27 22:31
I think this is not a bug, but it's the expected behavior. The autocomplete is just trying to be useful as much as it knows, and at that moment, closing the last opened tag is the most meaningful thing to do.
Also the "No closing angle bracket" is expected, it's made to let you type attributes. If it closed immediately the bracket, then you had to press `arrow left` or `backspace` most of the time (the cases where you don't need attribute is a minority)

**Comment by AlperSal** [comment] 2020-06-27 22:42
About 7 months ago. I was using VS Code and it was fine. There wasn't anything like that. But there is a another problem. When I choose another recommendation VS doesn't end it. So it is a big time lose for writing. There is 2 problem for me. If you don't see first one as a problem it should be 1 problem for you.

**Comment by AlperSal** [comment] 2020-06-28 16:51
Today I tried writing code again and now I did understand VS Code doesn't recognize *any* closing tags. For example in this code;
<body>
<div>"<"</div> (When I put a angel bracket anywhere VS automatically recommends </tag> and makes a red highlight. When I choose another reccommendation for example "div" it makes it like that -- "  <div   ")
</body>

Please help!

**Comment by aeschli** [comment] 2020-06-29 12:26
The bracket is red as it's invalid to have a `<` alone in the HTML content. Of course you are in the middle of writing more code, so you can ignore the red color.

The completion keeps the tag open as you might want to add attributes. Once you are done with attribute, pressing '>' will close the tag.

**Comment by aeschli** [comment] 2020-06-29 12:27
![html](https://user-images.githubusercontent.com/6461412/86005182-95967800-ba14-11ea-8aae-63f625a8da85.gif)

**Comment by AlperSal** [comment] 2020-06-30 10:40
Hmm... It is more logical. Thanks for reply. Have a nice day!

**Closed** 2020-06-30 10:40 UTC
