### ISSUE TITLE
Automatic insertion of parens doesn't interact nicely with completions, results in duplicated characters

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#26012] opened 2017-05-05 09:54 UTC
- VSCode Version:  1.11.2
- OS Version: Windows 10

Assume the following code (cursor is where the `|` is):

```dart
foo() {
}


main() {
  fo|
}
```

Completion is returning `foo()`. If the user continues to type `o(` then the `o` and `(` are "subtracted" from the completion client-side by Code (it doesn't send another request to the completion provider). This works great; however since typing the `(` auto-inserts a `)` if the user then uses the completion, they will end up with:

```dart
main() {
  foo()) // <-- two closing parens
}
```

There's an animation showing a slightly different version or this at https://github.com/Dart-Code/Dart-Code/issues/285

I can't see how the completion provider can fix this, since Code has taken over completion at this point (it's filtering and reducing the completion text client-side). I think the best thing would be for Code to subtract any auto-inserted characters from the end of the completion text in the same way it's removing the typed characters from the start.

Eg, when the user types the `(`:
1. Filter the completion list by the `(`
2. Remove the `(` from the completion text to be inserted, and adjust the range accordingly
3. Because a character was auto-inserted after the cursor, subtract that character from the end of the insertion text (and adjust the range) if it's the same character

I think 1 & 2 already happen, I think 3 would make sense to fix this.

**Comment by jrieken** [comment] 2017-05-05 12:56
@alexandrudima Is there a way I can halt electric brackets for a moment?

**Comment by alexandrudima** [comment] 2017-05-10 16:31
@jrieken I'm not 100% sure what you mean. 

The code for handling typing is at `typeWithInterceptors` -- https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/controller/cursorTypeOperations.ts#L547

The cursor goes into that if the `source` of the `type` command is `keyboard`.

Would you want in the `onWillType` to cancel the editor's processing of `type` ?

**Comment by alexandrudima** [comment] 2018-04-18 17:35
ping @jrieken What do you want in terms of editor API here ?

**Comment by jdneo** [comment] 2018-08-27 06:41
There is another issue about the same thing: https://github.com/redhat-developer/vscode-java/issues/503.

**Comment by jrieken** [comment] 2018-09-13 10:11
This is related to #10266 but the automatic bracket force you into this situation...

**Comment by TylerLeonhardt** [comment] 2019-05-18 16:31
Pulling a Python example from #70786. The root cause there was that snippets and auto closing pairs don't play nice together. 

Snippet:
```json
{
    "listcompPy": {
        "prefix":"[x for x in",
        "body":[
            "[x for x in range(1,20) if x%2==0 ]"
        ]
    }
}
```
typing `[x` results in a single extra bracket at the end:
```python
[x for x in range(1,20) if x%2==0 ]]
```

**Closed** 2019-08-26 13:50 UTC
Labels: bug, suggest

**Comment by jdneo** [comment] 2019-08-28 02:06
Thank you @jrieken for the fix. I tried in the Insider version it works like a charm!

![demo](https://user-images.githubusercontent.com/6193897/63820361-8883a500-c97b-11e9-9456-6e740f650696.gif)

**Comment by jrieken** [comment] 2019-08-28 07:54
> The Python example listed above does not work still.

It depends. Trigger IntelliSense, type `[x` (and get `[x]`), select snippet, all good. However, when you type `[x` (makes `[x]`), trigger suggest now (or auto trigger based on typing `x`, select snippet and the `]` isn't nuked. That's https://github.com/microsoft/vscode/issues/10266 which is about overriding text (to the right) which was there *before* (not *while*) suggestions show.
