### ISSUE TITLE
Import action stopped working with 1.26 update

### ISSUE THREAD

**Issue by dericgw** [Microsoft/vscode#57164] opened 2018-08-24 16:56 UTC
- VSCode Version: 1.26.1
- OS Version: OSX 10.13.6

Before upgrading to the latest version of VSCode, I could place the cursor on the line of a class/component/function that needed to be imported and when I pressed the quickfix keyboard shortcut, the contextual menu would have an item to import the missing module. This no longer happens.

![screen recording 2018-08-24 at 11 49 am](https://user-images.githubusercontent.com/34040106/44597245-93b65a80-a794-11e8-810e-b641fd4a107b.gif)

In the case above, this is a named import which used to work especially well. VS Code has always had some issues with default exports, and for good reason, but named exports used to always work well. I attempted this same thing with the Insiders and it performs the same. 

I looks like #56332 is a similar case, but that was specifically about Typescript. I am using Javsacript which should behave *similar*.

**Comment by mjbvz** [comment] 2018-09-05 18:30
Yes, duplicate of #56332. The same TypeScript engine powers VSCode's Javascript and typescript support

Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2018-09-05 18:30 UTC
Labels: javascript
