### ISSUE TITLE
GFM table formatter not working

### ISSUE THREAD

**Issue by archzhu** [Microsoft/vscode#30130] opened 2017-07-05 13:20 UTC
as title

- VSCode Version: 1.13.1 (1.13.1)
- OS Version: MacOs 10.12.5

**Comment by mjbvz** [comment] 2017-07-05 15:22
What extension are you using to format the table? Can you try filing the issue against that extension

**Comment by mjbvz** [comment] 2017-07-10 23:42
Closing as the issue is not clear. @archzhu Please provide some repo steps and more information about the expected behavior

**Closed by mjbvz** 2017-07-10 23:42 UTC
Labels: markdown, needs more info
