### ISSUE TITLE
What the hell is going with tsserver?

### ISSUE THREAD

**Issue by Rc85** [microsoft/vscode#73077] opened 2019-04-30 12:03 UTC
Every 30 min or so, vscode would use CPU up to 50% - 100% for like, 3 - 5 min. This causes everything to slow down like suggestions and auto closing tags. I open up the process explorer in vscode under the Help menu, and I see electron_node tsserver.js hogging up all the CPU.

This is where I finally found the location of the tsserver.log on Windows and upon going to that directory, I see a 3GB+ tsserver.log file. Not gonna bother skimming through 3GB of logs.

When it started another log, it was almost 1 GB when I first opened it. Looking at some of the latest timestamps, there are semanticDiag and syntaxDiag events on files in my project that aren't even opened or barely ever opened.

What the hell is going on? Tsserver has been slowing down vscode for like the past month.

Edit - In the last 30 minutes of using vscode, I noticed the CPU usage for electron_node tsserver is jumping to 30% whenever it starts writing those semanticDiag and syntaxDiag events to the log. I notice this because my suggestion and auto closing slows down to 5 - 7 seconds. When that happened, I open the tsserver.log and the CPU goes back to 0, possibly because it cannot write to an opened file.

**Comment by treet** [comment] 2019-04-30 14:10
I'm experiencing the same problem, CPU usage jumps to 50%-100% CPU even if I haven't touched vscode for a while. I haven't confirmed it's related to tsserver, but the I have ts files in the workspace.

**Comment by Rc85** [comment] 2019-04-30 14:32
> I'm experiencing the same problem, CPU usage jumps to 50%-100% CPU even if I haven't touched vscode for a while. I haven't confirmed it's related to tsserver, but I have Typescript files in the workspace.

When you notice the CPU jump, open the process explorer under vscode Help menu and you will see if it's related to tsserver or not.

**Comment by mjbvz** [comment] 2019-04-30 17:41
What VS Code version and OS are you on?

/needsMoreInfo

**Comment by Rc85** [comment] 2019-04-30 20:27
> What VS Code version and OS are you on?
> 
> /needsMoreInfo

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

I wish I could post the log but it's too big.

**Comment by mjbvz** [comment] 2019-05-01 17:40
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Also, you can run `code --upload-logs` from the command line to securely share the log file. Or if you can share you project, we can try to repo this.

**Comment by dziugasmeskauskas** [comment] 2019-05-01 20:03
@mjbvz Same issues for me, also experiencing it on the insiders build.

**Comment by agDmitry** [comment] 2019-05-02 10:31
I think i have a similar problem.

Steps to reproduce:
* Open from 2 to 10 *.ts files.
* Make an error in some file, so TS can stumble upon it and go crazy. Sometimes just editing is enough.

CPU goes 100%. When i am hovering on any variable/type definition/anything, the floating window content goes like this: "Loading..." -> "Shows definition" -> "Loading..." -> "Shows definition" -> ...

It looks like race-condition to me.

When i fix error that i made previously, sometimes tsserver stops its infinite cycle of computing of whatever it was computing. It's 50/50.

TS - 3.4.3
VSCode - 1.33.1
OS - Manjaro Linux

**Comment by mjbvz** [comment] 2019-05-02 16:36
If you are not @Rc85 and seeing performance problems, please open a new issue

**Comment by mjbvz** [comment] 2019-05-14 01:11
I'm closing this as more information is needed from the original poster. My best guess from the available information is that this is a duplicate of https://github.com/microsoft/TypeScript/issues/31341

To check this, please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)

**Closed by mjbvz** 2019-05-14 01:11 UTC
Labels: needs more info, typescript
