### ISSUE TITLE
Crash on any new file save (Ubuntu 18.04)

### ISSUE THREAD

**Issue by AlexanderKeijzer** [microsoft/vscode#179140] opened 2023-04-04 13:14 UTC
Type: <b>Bug</b>

1. Open VSCode
2. Save any new file (e.g. ctrl+n, ctrl+s)
3. Hard crash of VSCode

Also occurs with extensions disabled.

Tail of output when running with --verbose:
```
[main 2023-04-04T13:07:53.062Z] [DialogMainService]: request to acquire file dialog lock {
  defaultPath: '/home/akeijzer/Untitled-1',
  filters: [
    { name: 'All Files', extensions: [Array] },
    { name: 'Plain Text', extensions: [Array] },
    { name: 'Batch', extensions: [Array] },
    { name: 'BibTeX', extensions: [Array] },
    { name: 'C', extensions: [Array] },
    { name: 'C#', extensions: [Array] },
    { name: 'C++', extensions: [Array] },
    { name: 'Clojure', extensions: [Array] },
    { name: 'CoffeeScript', extensions: [Array] },
    { name: 'CSS', extensions: [Array] },
    { name: 'CUDA C++', extensions: [Array] },
    { name: 'Dart', extensions: [Array] },
    { name: 'Diff', extensions: [Array] },
    { name: 'Docker', extensions: [Array] },
    { name: 'F#', extensions: [Array] },
    { name: 'Go', extensions: [Array] },
    { name: 'Groovy', extensions: [Array] },
    { name: 'Handlebars', extensions: [Array] },
    { name: 'HLSL', extensions: [Array] },
    { name: 'HTML', extensions: [Array] },
    { name: 'Ignore', extensions: [Array] },
    { name: 'Ini', extensions: [Array] },
    { name: 'Java', extensions: [Array] },
    { name: 'JavaScript', extensions: [Array] },
    { name: 'JavaScript JSX', extensions: [Array] },
    { name: 'JSON', extensions: [Array] },
    { name: 'JSON with Comments', extensions: [Array] },
    { name: 'Julia', extensions: [Array] },
    { name: 'Julia Markdown', extensions: [Array] },
    { name: 'LaTeX', extensions: [Array] },
    { name: 'Less', extensions: [Array] },
    { name: 'Log', extensions: [Array] },
    { name: 'Lua', extensions: [Array] },
    { name: 'Makefile', extensions: [Array] },
    { name: 'Markdown', extensions: [Array] },
    { name: 'Objective-C', extensions: [Array] },
    { name: 'Objective-C++', extensions: [Array] },
    { name: 'Perl', extensions: [Array] },
    { name: 'Perl 6', extensions: [Array] },
    { name: 'PHP', extensions: [Array] },
    { name: 'PowerShell', extensions: [Array] },
    { name: 'Properties', extensions: [Array] },
    { name: 'Pug', extensions: [Array] },
    { name: 'Python', extensions: [Array] },
    { name: 'R', extensions: [Array] },
    { name: 'Razor', extensions: [Array] },
    { name: 'reStructuredText', extensions: [Array] },
    { name: 'Ruby', extensions: [Array] },
    { name: 'Rust', extensions: [Array] },
    { name: 'SCSS', extensions: [Array] },
    { name: 'Search Result', extensions: [Array] },
    { name: 'ShaderLab', extensions: [Array] },
    { name: 'Shell Script', extensions: [Array] },
    { name: 'SQL', extensions: [Array] },
    { name: 'Swift', extensions: [Array] },
    { name: 'TeX', extensions: [Array] },
    { name: 'TypeScript', extensions: [Array] },
    { name: 'TypeScript JSX', extensions: [Array] },
    { name: 'Visual Basic', extensions: [Array] },
    { name: 'XML', extensions: [Array] },
    { name: 'XSL', extensions: [Array] },
    { name: 'YAML', extensions: [Array] },
    { name: 'No Extension', extensions: [Array] }
  ],
  title: 'Save As'
}
[main 2023-04-04T13:07:53.066Z] [DialogMainService]: new file dialog lock created {
  defaultPath: '/home/akeijzer/Untitled-1',
  filters: [
    { name: 'All Files', extensions: [Array] },
    { name: 'Plain Text', extensions: [Array] },
    { name: 'Batch', extensions: [Array] },
    { name: 'BibTeX', extensions: [Array] },
    { name: 'C', extensions: [Array] },
    { name: 'C#', extensions: [Array] },
    { name: 'C++', extensions: [Array] },
    { name: 'Clojure', extensions: [Array] },
    { name: 'CoffeeScript', extensions: [Array] },
    { name: 'CSS', extensions: [Array] },
    { name: 'CUDA C++', extensions: [Array] },
    { name: 'Dart', extensions: [Array] },
    { name: 'Diff', extensions: [Array] },
    { name: 'Docker', extensions: [Array] },
    { name: 'F#', extensions: [Array] },
    { name: 'Go', extensions: [Array] },
    { name: 'Groovy', extensions: [Array] },
    { name: 'Handlebars', extensions: [Array] },
    { name: 'HLSL', extensions: [Array] },
    { name: 'HTML', extensions: [Array] },
    { name: 'Ignore', extensions: [Array] },
    { name: 'Ini', extensions: [Array] },
    { name: 'Java', extensions: [Array] },
    { name: 'JavaScript', extensions: [Array] },
    { name: 'JavaScript JSX', extensions: [Array] },
    { name: 'JSON', extensions: [Array] },
    { name: 'JSON with Comments', extensions: [Array] },
    { name: 'Julia', extensions: [Array] },
    { name: 'Julia Markdown', extensions: [Array] },
    { name: 'LaTeX', extensions: [Array] },
    { name: 'Less', extensions: [Array] },
    { name: 'Log', extensions: [Array] },
    { name: 'Lua', extensions: [Array] },
    { name: 'Makefile', extensions: [Array] },
    { name: 'Markdown', extensions: [Array] },
    { name: 'Objective-C', extensions: [Array] },
    { name: 'Objective-C++', extensions: [Array] },
    { name: 'Perl', extensions: [Array] },
    { name: 'Perl 6', extensions: [Array] },
    { name: 'PHP', extensions: [Array] },
    { name: 'PowerShell', extensions: [Array] },
    { name: 'Properties', extensions: [Array] },
    { name: 'Pug', extensions: [Array] },
    { name: 'Python', extensions: [Array] },
    { name: 'R', extensions: [Array] },
    { name: 'Razor', extensions: [Array] },
    { name: 'reStructuredText', extensions: [Array] },
    { name: 'Ruby', extensions: [Array] },
    { name: 'Rust', extensions: [Array] },
    { name: 'SCSS', extensions: [Array] },
    { name: 'Search Result', extensions: [Array] },
    { name: 'ShaderLab', extensions: [Array] },
    { name: 'Shell Script', extensions: [Array] },
    { name: 'SQL', extensions: [Array] },
    { name: 'Swift', extensions: [Array] },
    { name: 'TeX', extensions: [Array] },
    { name: 'TypeScript', extensions: [Array] },
    { name: 'TypeScript JSX', extensions: [Array] },
    { name: 'Visual Basic', extensions: [Array] },
    { name: 'XML', extensions: [Array] },
    { name: 'XSL', extensions: [Array] },
    { name: 'YAML', extensions: [Array] },
    { name: 'No Extension', extensions: [Array] }
  ],
  title: 'Save As'
}
(code:20701): GLib-GIO-ERROR **: 15:07:53.206: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
[0404/150753.218231:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218296:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218305:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218318:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218326:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218339:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218347:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218355:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218363:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218377:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218386:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218406:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218418:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218432:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218439:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218447:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218458:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218464:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218470:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218476:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218502:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218533:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218539:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218548:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218553:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218559:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218564:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218572:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218580:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218589:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218597:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218605:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218613:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218622:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218633:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218647:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218658:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218665:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218674:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218686:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218694:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218703:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218711:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218719:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218751:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218760:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218768:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218778:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218788:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218803:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218846:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218856:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218864:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218872:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218880:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218894:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218905:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218913:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218929:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218959:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218973:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.218991:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243848:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243867:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243878:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243886:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243896:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243903:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243922:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243930:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243943:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243951:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243970:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243983:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.243997:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244007:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244019:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244030:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244039:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244049:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244076:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244086:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244097:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244106:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244116:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244124:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244133:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244141:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244151:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244159:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244169:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244178:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244187:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244196:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244222:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244231:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244240:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244248:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244257:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244266:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244275:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244283:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244321:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244331:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244406:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244417:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244428:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244438:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244460:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244469:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244479:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244487:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244496:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244504:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244515:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244527:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244537:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244546:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244555:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244563:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244573:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244581:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244590:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244599:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244608:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244618:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244628:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244639:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244651:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244659:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244671:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244679:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244688:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244697:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244706:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244714:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244725:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244734:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244751:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244760:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244779:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244788:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244797:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244805:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244814:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244822:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244833:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244843:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244853:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244862:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244925:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244936:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244947:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244965:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244976:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244984:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.244996:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245004:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245018:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245027:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245046:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245056:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245126:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245136:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245147:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245156:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245167:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245176:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245186:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245194:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245203:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245211:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245240:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245251:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245267:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245276:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245286:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245294:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245323:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245334:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245390:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245401:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245423:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245432:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245441:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.245450:ERROR:process_memory_range.cc(75)] read out of range
[0404/150753.248256:ERROR:directory_reader_posix.cc(42)] opendir /home/akeijzer/.config/Code/Crashpad/attachments/a9fc42fb-5b61-4f29-b1c9-a3fd5406ae93: No such file or directory (2)
```

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:05:35.165Z)
OS version: Linux x64 5.4.0-146-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3463)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|15.51GB (9.37GB free)|
|Process Argv|--no-sandbox --disable-extensions --crash-reporter-id 92027e04-4eea-42c9-9aaf-6a0f88a0e67b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsccsb:30677849
pythonb192:30669360
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-04-04 16:41
Maybe #178780 which the upcoming 1.77.1 should resolve.

**Comment by deepak1556** [comment] 2023-04-04 22:28
Yup this is a duplicate of https://github.com/microsoft/vscode/issues/178780, merging to it.

**Closed by deepak1556** 2023-04-04 22:28 UTC
Labels: triage-needed
