### ISSUE TITLE
Feature request: Sublime like display of folders

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#1212] opened 2015-12-11 22:26 UTC
...to have a better visual separation from files

**Comment by Tyriar** [comment] 2015-12-11 23:47
Do you mean adding icons? https://github.com/Microsoft/vscode/issues/211

**Comment by neilyoung** [comment] 2015-12-12 07:31
Right. Duplicate of #211. Can be closed then

**Comment by egamma** [comment] 2015-12-12 16:02
closing as duplicate of #211 as requested, thanks.

**Closed by egamma** 2015-12-12 16:02 UTC
