### ISSUE TITLE
prompt (working path part) print double times in Terminal (oh-my-zsh)

### ISSUE THREAD

**Issue by clor09** [Microsoft/vscode#28289] opened 2017-06-09 05:23 UTC
- VSCode Version: 1.13.0
- OS Version: Debian 9.0

Steps to Reproduce:

1.  install zsh & oh-my-zsh
2.  in .zshrc set ZSH_THEME='agnoster' (you may install this theme first)
3.  change current shell to zsh.(or reload .zshrc if you are in zsh)

click on the terminal, the path part would dispear and show again, ...

![screenshot_20170609_131604](https://user-images.githubusercontent.com/20962135/26962032-ebd4135e-4d15-11e7-8419-d66cb382b84f.png)

**Comment by michelkaporin** [comment] 2017-06-09 07:26
Duplicate of #26038

**Closed by michelkaporin** 2017-06-09 07:26 UTC
Labels: new release
