### ISSUE TITLE
Automatically collapse "import" block in files.

### ISSUE THREAD

**Issue by MartinSGill** [Microsoft/vscode#20802] opened 2017-02-17 12:20 UTC
On larger projects you can end up with 10 or more lines of "import ... ;" statements at the top of a file.

It would be really great if vscode could detect if the there's a huge block of import statements at the top of a file and treat them as a collapsible region, and automatically collapse that region when you open a file.

At it's simplest I would define an "import block" as

1. The only lines above the first "import" statement are comments or empty lines
1. Line matches "^import\b" 
1. Line is an empty line
1. Line is a comment
1. The end of the block is the first non-empty, non-comment line that does not match "^import\b" 

It might also be worth having a minimum size before imports are treated as a block/region. E.g. 3 or more lines.

**Comment by aeschli** [comment] 2017-02-21 14:47
Right now folding is purely indentation based. What you are asking is language aware folding.
That's #3422

**Comment by mjbvz** [comment] 2017-03-02 02:50
Reopening to track the TypeScript/JavaScript specific part of this request from #21632

**Comment by testerez** [comment] 2017-12-16 17:37
I wonder if it could be achieved by an extension...

**Comment by mjbvz** [comment] 2018-03-26 22:55
Depends on https://github.com/Microsoft/TypeScript/issues/22419

**Comment by mjbvz** [comment] 2018-05-10 21:27
Thanks @aeschli. Folding of imports is now in vscode with d8e552057526c33a94b07e423b2df186e156dbba

Initial folding state is language independent so I'm assigning this issue over to you now. Let me know if there is any js/ts specific work that needs to be done

**Comment by aeschli** [comment] 2018-05-29 06:38
duplicate of #40338

**Closed by aeschli** 2018-05-29 06:38 UTC
Labels: editor-folding, feature-request, javascript, typescript
