### ISSUE TITLE
Notebook cursor visible when entering edit mode 

### ISSUE THREAD

**Issue by NickiForte** [microsoft/vscode#141907] opened 2022-01-31 22:43 UTC
When entering edit mode in a .ipynb notebook, the view is always shifted sich that the top of the cell is in the middle of the screen. If the cell is long and the cursor is at the bottom of the cell, the cursor is not visible when entering edit mode. One would expect the view to always be adjusted such that the cursor is visible when entering edit mode.

**Comment by eXotech-code** [comment] 2022-02-01 07:34
You have a typo in the 14th word of your comment. "sich" should be "such".

**Comment by eXotech-code** [comment] 2022-02-01 07:47
Whenever I am trying to edit a cell my view gets shifted to wherever the cursor is at the moment. Can you add more details about the type of block you were trying to edit when this issue happened? Maybe I will be able to reproduce this issue on my machine having this info to work with.

**Comment by NickiForte** [comment] 2022-02-01 09:22
For me, whenever I am in command mode of the notebook and press enter, activating the keyboard shortcut command "notebook.cell.edit", the view is automatically shifted to the top of the cell, regardless of where the cursor is.

**Comment by NickiForte** [comment] 2022-02-01 09:24
And I was just trying to edit a normal code block.

**Comment by eXotech-code** [comment] 2022-02-01 09:36
I tried to use the default shortcut to edit the code block but the view automatically scrolled to where my cursor was before I closed the edit mode. I then changed my keybinding for edit mode but I still couldn't reproduce your issue.

**Comment by NickiForte** [comment] 2022-02-01 11:03
This is very strange. I have no idea why mine is behaving differently.

**Comment by eXotech-code** [comment] 2022-02-01 12:16
I think you should wait until someone else tries to reproduce this issue. What OS did you encounter this issue in? I tried to reproduce this on macOS Monterey 12.1 and couldn't do it. Maybe this issue is connected somehow to the Electron's renderer and how it works on different operating systems.

**Comment by NickiForte** [comment] 2022-02-01 12:28
I have been using macOS Monterey 12.2. But yeah, let's see if someone else also manages to reproduce this issue.

**Comment by eXotech-code** [comment] 2022-02-01 12:34
I have one question for you just out of curiosity. What is your hardware?

**Comment by NickiForte** [comment] 2022-02-01 13:22
I'm running on a macbook pro, 13 inch. 1,4 GHz Quad-Core Intel Core i5

**Comment by eXotech-code** [comment] 2022-02-01 13:34
I am using the MacBook Air with M1. This means that I am running Visual Studio Code on a different processor architecture. l don't think that this issue is hardware related, but this is the only difference that I have found between our setups so it is a possibility.

**Comment by ShafinKhadem** [comment] 2022-02-02 18:17
I have tried fixing this issue in #142026. As I didn't notice this issue, I created a duplicate issue #142025 with steps to reproduce, which I have closed now. @NickiForte please change 'visible' to 'invisible' in this issue's title.

**Comment by ShafinKhadem** [comment] 2022-02-02 18:22
This issue is a duplicate of #141489

**Closed** 2022-02-02 18:37 UTC
