### ISSUE TITLE
Issues with "Jump to definition" CSS links introduced in August release

### ISSUE THREAD

**Issue by juanpablob** [microsoft/vscode#59046] opened 2018-09-20 14:50 UTC
- VSCode Version: 1.27.2
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Create a CSS file called `hello-world.scss/css`
2. Create another CSS file, and put `@import 'hello-world.scss`
3. After ⌘/Ctrl + clicking the path, you'll get this error: `Unable to open 'hello-world': File not found (file:///fakepath/css/hello-world).`

While naming `hello_word.scss` don't trigger any error. As I can guess, the regex in charge is missing filenames with dashes in between.

Cheers!

**Comment by octref** [comment] 2019-05-09 17:57
Duplicate of #58204.

**Closed by octref** 2019-05-09 17:57 UTC
Labels: bug, css-less-scss
