### ISSUE TITLE
Terminal switcher

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#118028] opened 2021-03-03 10:13 UTC
Hi, I'm proposing a ***terminal switcher*** 

**Request is:**

1. An UI similar to Ctrl-R (recent projects) to list and **filter active terminals**; icons can show each's type (bash, powershell, cmd etc). (the item has the current command or path on the first row and the name & terminal type on the second raw)
2. Allow **the first entry to be: "Create new"** and the rest of the items to have **an x button to close corresponding terminal** (a second edit button near to the close one would be useful to edit the terminal names easily)
3. Allow colored terminal prompt icons for easy visual identification on terminal window and list entries. 
4. Allow alt-tab style switching between terminals with a shortcut similar in behavior with Ctrl-R.
5. **Add an input box (will become label on no focus) near current terminals list dropdown (on terminal panel) to allow naming a terminal**
6. **Save terminals on vscode exit & restore** for the respective folder/project
7. Allow horizontal scroll in terminal

**Filtering** would be on the given name or terminal path or command.
Icon on list item entry shows terminal type.

**Comment by meganrogge** [comment] 2021-03-05 22:39
Duplicate of #45444

**Closed** 2021-03-05 22:46 UTC
Labels: *duplicate, feature-request, integrated-terminal

**Comment by LucaGabi** [comment] 2021-03-09 14:52
I think this is more detailed ticket on how the terminal switcher would be more useful keeping existing UI patterns in vscode. Would this not be better to replace the mentioned duplicate 45444 ?
