### ISSUE TITLE
VSCode freezes with integrated terminal

### ISSUE THREAD

**Issue by DemianD** [Microsoft/vscode#52335] opened 2018-06-19 14:05 UTC
Issue Type: <b>Bug</b>

Since a week of two I'm facing an issue with the Integrated Terminal in VSCode.

When working with the Integrated Terminal, and the executed command is outputting a lot of data, VSCode freezes.

This way I forced a freeze (maybe some steps can be omitted):
1. Create a SSH session to a VM from the Integrated Terminal.
2. Create a dummy C-file, and compile with `gcc dummy.c -o dummy.o -static`
3. cat dummy.o
4. VSCode should freeze completely.
5. When clicking on the Editor, wait a few minutes. After a few minutes you may be able to type again.
6. Click again on the Integrated Terminal, it freezes again.

https://youtu.be/PK39vWyUHzU

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.64GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
vscode-jest|Ort|2.8.0
ReactSnippetsStandard|Tim|1.1.0
jsx|Twe|0.0.1
lorem-ipsum|Tyr|1.2.0
snapshot-tools|asv|0.0.7
code-gnu-global|aus|0.2.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
sql-formatter|cym|1.0.2
vscode-eslint|dba|1.4.12
xml|Dot|2.3.1
vscode-style-formatter|dwe|1.0.0
gitlens|eam|8.4.0
prettier-vscode|esb|1.5.0
code-runner|for|0.9.3
sublime-babel-vscode|jos|0.2.10
8051|jun|0.1.0
vscode-gutter-preview|kis|0.12.2
VS-code-vagrantfile|mar|0.0.7
rainbow-csv|mec|0.4.1
ecdc|mit|0.12.0
vscode-scss|mrm|0.6.2
python|ms-|2018.5.0
cpptools|ms-|0.17.4
Go|ms-|0.6.83
laravel-blade|one|1.18.0
vscode-versionlens|pfl|0.21.1
vscode-icons|rob|7.23.0
react-redux-es6-snippets|tim|2.1.0
vscode-import-cost|wix|2.7.1
clang-format|xav|1.6.2
markdown-pdf|yza|1.2.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment] 2018-06-19 19:53
Can you share your settings.json file?

**Comment by DemianD** [comment] 2018-06-20 05:57
Hi @Tyriar 

settings.json:

```
{
  "window.zoomLevel": 0,
  "editor.mouseWheelZoom": false,
  "vsicons.projectDetection.disableDetect": true,
  "workbench.iconTheme": "vscode-icons",
  "prettier.eslintIntegration": true,
  "C_Cpp.errorSquiggles": "Enabled",
  "C_Cpp.intelliSenseEngineFallback": "Disabled",
  "[javascript]": {
    "editor.tabSize": 2
  },
  "[json]": {
    "editor.tabSize": 2
  },
  "[javascriptreact]": {
    "editor.tabSize": 2
  },
  "vsicons.dontShowNewVersionMessage": true,
  "extensions.ignoreRecommendations": true,
  "blade.format.enable": true,
  "go.formatTool": "gofmt",
  "gitlens.keymap": "none",
  "gitlens.advanced.messages": {
    "suppressCommitHasNoPreviousCommitWarning": false,
    "suppressCommitNotFoundWarning": false,
    "suppressFileNotUnderSourceControlWarning": false,
    "suppressGitVersionWarning": false,
    "suppressLineUncommittedWarning": false,
    "suppressNoRepositoryWarning": false,
    "suppressResultsExplorerNotice": false,
    "suppressShowKeyBindingsNotice": true
  },
  "liveshare.features": "experimental",
  "files.associations": {
    "*.toml": "json"
  },
  "gitlens.historyExplorer.enabled": true,
  //"search.useIgnoreFiles": false,
  "editor.minimap.enabled": false,
  "markdown-pdf.printBackground": false,
  "markdown-pdf.displayHeaderFooter": false
}
```

If you need more information, let me know

**Comment by Tyriar** [comment] 2018-06-20 08:01
Looks like this is a duplicate of https://github.com/xtermjs/xterm.js/issues/1515

**Closed by Tyriar** 2018-06-20 08:01 UTC
Labels: integrated-terminal, needs more info
