### ISSUE TITLE
Task error messages

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#139160] opened 2021-12-15 03:49 UTC
I had the vscode build task running and wanted to restart it. I did what I usually do

- ctrl+D in each task terminal to kill the process
- cmd+shift+B to start the default build task

When I press cmd+shift+B I get these two notifications

![image](https://user-images.githubusercontent.com/323878/146119138-a0373696-a93e-46fa-aec6-554182434d3e.png)

There is no task output:

![image](https://user-images.githubusercontent.com/323878/146119166-72e27aaf-d083-4c39-a966-a454b22a1ac9.png)

And there are no tasks running:

![image](https://user-images.githubusercontent.com/323878/146119203-c2e745e1-3065-4a45-aad6-e69357887e6c.png)

**Comment by alexr00** [comment] 2021-12-15 07:38
Duplicate of https://github.com/microsoft/vscode/issues/139089

**Closed by alexr00** 2021-12-15 07:38 UTC
