### ISSUE TITLE
Install extensions under proxy problem

### ISSUE THREAD

**Issue by jacorachan** [Microsoft/vscode#954] opened 2015-12-03 09:05 UTC
I have set up my corporate proxy as explained on the documentation:

![Proxy settings](http://i.imgur.com/Cv44idX.png)

But every time that I try to download an extension with `ext install extensionname`, it fails with this error:

![connection error](http://i.imgur.com/WI0oQWA.png)

**Comment by joaomoreno** [comment] 2015-12-03 12:35
Duplicate of #69

**Closed by joaomoreno** 2015-12-03 12:35 UTC

**Comment by jacorachan** [comment] 2015-12-03 16:35
Thanks @joaomoreno
