### ISSUE TITLE
folder or file delete freezes vscode

### ISSUE THREAD

**Issue by cropr** [Microsoft/vscode#73125] opened 2019-05-01 11:28 UTC
- VSCode Version:  1.33.1
- OS Version:  Ubuntu 19.04   Linux x64 5.0.0.13-generic-snap
- using KDE as window environmen

Steps to Reproduce:

1. Delete a file or a  folder by right clicking in file explorer

Does this issue occur when all extensions are disabled?: Yes

Output of:  

```
code --verbose

...
[21920:0501/131550.722871:INFO:CONSOLE(1408)] "%cTRACE", source: file:///snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1408)
[21920:0501/131603.038366:INFO:CONSOLE(1408)] "%cTRACE", source: file:///snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1408)
[21920:0501/131603.039781:INFO:CONSOLE(1408)] "%cTRACE", source: file:///snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-05-01T11:16:04.551Z] update#checkForUpdates, state =  idle
[main 2019-05-01T11:16:04.552Z] update#setState checking for updates
[main 2019-05-01T11:16:04.555Z] update#setState idle
[main 2019-05-01T11:16:04.555Z] telemetry/update:notAvailable { explicit: false }
[main 2019-05-01T11:16:33.096Z] [VS Code]: detected unresponsive
Gtk-Message: 13:16:33.130: GtkDialog mapped without a transient parent. This is discouraged.
[main 2019-05-01T11:16:33.130Z] telemetry/windowerror { type: 1 }
...

```

**Comment by RMacfarlane** [comment] 2019-05-01 16:58
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/54493

**Closed by RMacfarlane** 2019-05-01 16:58 UTC
Labels: freeze-slow-crash
