### ISSUE TITLE
The integrated terminal is firing the windows console host with high CPU percentage

### ISSUE THREAD

**Issue by cesaraaron** [Microsoft/vscode#18424] opened 2017-01-11 23:31 UTC
- VSCode Version: Both 1.8.1 & 1.9.0-insider
- OS Version: Windows 10 insider build 15002

Steps to Reproduce:

1. Open the integrated terminal... that is it, the wch uses almost all the cpu until I close it.

I hadn't had this issue till my pc got updated this morning on that build.

**Comment by Tyriar** [comment] 2017-01-11 23:54
This is happening on stable 1.8.1 as well? Which process exactly is using up all the CPU?

**Comment by cesaraaron** [comment] 2017-01-11 23:59
conhost.exe

The issue has to be with the last windows insider build I think.

**Comment by Tyriar** [comment] 2017-01-12 00:04
What are your terminal-related settings and the shell you're using?

**Comment by cesaraaron** [comment] 2017-01-12 00:11
No related options, the default one _cmd_, I even tried disabling all extensions and deleting my settings and still the same.

**Comment by Tyriar** [comment] 2017-01-12 00:17
Does launching powershell fix the CPU problem?

```js
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
```

**Comment by cesaraaron** [comment] 2017-01-12 00:23
Yep.

**Comment by cesaraaron** [comment] 2017-01-12 00:47
Well, looks like it's an issue of the system itself -I tried running the integrated of phpstorm and got the same.

The insider team broke down something I guess.

**Comment by bitcrazed** [comment] 2017-01-12 01:36
@cesaraaron Are you running cmd or PowerShell or Bash in your console? 

If you're running Bash, there's a known issue in Insider build #15002 in which Bash/WSL eats a CPU core while Bash is running: https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15002

**Comment by cesaraaron** [comment] 2017-01-12 02:10
No, I'm not running neither bash nor powershell inside those apps (and I'm only getting this high cpu in the conhost.exe when I'm running commands inside an application, in their own interfaces all consoles behave properly).

This problem began exactly after the pc updated to the 15002, so I think that has something to do.

**Comment by cesaraaron** [comment] 2017-01-12 02:17
@bitcrazed 

Edit.

I do having troubles with the bash in it's own application/process (not before the 15002 update though), on this case isn't the conhost.exe that goes to hell, it's the system.exe process
![boceto](https://cloud.githubusercontent.com/assets/20180899/21874383/4ab720a6-d83a-11e6-8591-3321a9c7ea9f.png)

But that is an issue besides the one that causes the high cpu on conhost.exe I guess (since the cmd not the bash if the one that causes that)

**Comment by bitcrazed** [comment] 2017-01-12 22:55
@cesaraaron Having a hard time reproducing the issue you describe:

![image](https://cloud.githubusercontent.com/assets/961950/21911708/d6320140-d8d6-11e6-9dd8-82783d3cebd4.png)

Could I ask you to close down all apps on your PC, esp. all consoles, then open Task Manager & VS Code only. Snap them side by side and let your machine idle for a short while. Now open VSCode's integrated terminal & watch the CPU.

If after a few secs the CPU is still pegged at 100%, we'll probably ask you to capture a trace to find out what's up.

**Comment by cesaraaron** [comment] 2017-01-14 18:28
Sorry for the delay response.

Yesterday updated to the build 15007, still the same, followed your instructions and the conhost.exe only gets pegged at 50% -indefinitely btw, only when I open the integrated terminal, or when I open a program that uses the conhost in I don't know what way -Sublime Text fires it in the same way, guess is some custom extension.

I used the process monitor to capture for a few seconds the state when the vscode is with and without the integrated terminal open.
[Logfile.zip](https://github.com/Microsoft/vscode/files/706137/Logfile.zip)

**Comment by bitcrazed** [comment] 2017-01-17 21:04
Hey @cesaraaron - thanks for getting back to me. We are investigating sparse reports of ConHost eating a core on a few people's machines but are struggling to find a repro.

Could I ask you to:

1. Shut down your PC
2. Count to 10
3. Re-start your PC & login
4. Before running anything else, open VS Code and start the integrated shell

If doing this causes ConHost to consume significant CPU resources, let me know.

If not, take whatever steps you would normally take that triggers the unexpected behavior & share those steps here.

Also, if you could let us know as much detail about:

* The type of device you're using (CPU, memory, storage space, free & type, wifi/ethernet, etc.)
* What build of Windows 10 you're using?
* Specific settings and/or other config (e.g. locale)?
* What other apps do you have running in the background?
* Anything else you think may be relevant.

Many thanks in advance.

**Comment by bitcrazed** [comment] 2017-01-17 21:07
Looping-in @miniksa & @paulcam206 for visibility.

**Comment by jongalloway** [comment] 2017-01-17 22:51
I can repro. 

- Shut down for 20 seconds, started up, launched VS Code and started integrated shell. 
- CPU immediately jumps, conhost pegs 1 of 4 cores pegged (sustained ~25% cpu total, fan on high).
- Close VS Code, cpu usage drops
- Wait 30 seconds
- Launch [hyper](http://hyper.is) which also hosts terminal via [node-pty](https://github.com/Tyriar/node-pty) and see exact same behavior (high cpu, fan on high) until closing.

Specs:
- [Surfacebook 512GB/17](https://www.microsoftstore.com/store/msusa/en_US/pdp/productID.5072761900)
- Windows 10 15007
- EN-US, pretty much default settings
- Only startup apps running - OneDrive, OneDrive for Business, Docker for Windows
- Not domain joined or running MSIT build

**Comment by bitcrazed** [comment] 2017-01-18 00:49
Okayyy ... We managed to grab Jon in his hotel in London, have him VPN into Microsoft's corporate network whereupon one of our dev's hooked up a remote debugger to examine Jon's machine.

The long and the short of it is that this issue was caused by the Console's painting algorithm calling [ValidateRect()](https://msdn.microsoft.com/en-us/library/windows/desktop/dd145194(v=vs.85).aspx) to mark a region of the screen as "painted". However, in some scenarios, this mechanism introduced painting-related issues.

We'd actually already modified the code to handle painting using a [BeginPaint()](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183362(v=vs.85).aspx) / [EndPaint()](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162598(v=vs.85).aspx) approach instead. This is why we were unable to repro locally - our versions of the console were calling the newer BeginPaint() / EndPaint() based routine instead of the ValidateRect() approach.

This fix is currently queued up in our build system and should make it into a future Insider build, possibly next-week's build.

Many thanks to @cesaraaron and to @jongalloway for your help and assistance in tracking-down this issue.

**Comment by miniksa** [comment] 2017-01-18 00:51
@bitcrazed. "One of our devs..." PSHAW. It was totally me. :P

**Comment by bitcrazed** [comment] 2017-01-18 00:53
I didn't want to infer that you might also have been the source of the original issue @miniksa ... but since you've offered up this morsel of information .... ;)

**Comment by miniksa** [comment] 2017-01-20 17:32
This wasn't in today's 15014 Insiders build, but it should be in next week's build. (Anything 15016+).

And yeah, of course I broke it. :P

**Comment by bitcrazed** [comment] 2017-01-20 18:36
ROFL 😊 Thanks!

Rich.

**Closed** 2017-02-23 04:52 UTC
Labels: integrated-terminal, perf, windows
