### ISSUE TITLE
Add support for `typescript.tsdk` option on folder level

### ISSUE THREAD

**Issue by e965** [microsoft/vscode#200751] opened 2023-12-13 14:50 UTC
Situation - I want to use a new [yarn berry](https://yarnpkg.com/getting-started) with [PnP](https://yarnpkg.com/features/pnp), but unfortunately I can't do it in the way I'm used to. The way I'm used to it is that I have one workspace where all the projects I'm working on are stacked like folders (I think it's called "multi-root workspace").

For PnP to work properly, I need to set the Typescript version from the sdk, but unfortunately I can only do that if I open each project as a separate workspace, which is inconvenient. 

![image](https://github.com/microsoft/vscode/assets/18071040/b0b9a74f-85c1-4b7d-82f1-7a6baf5a3204)

I wish the seetting that controls this (`typescript.tsdk`) had support at the folder level, not the entire workspace.

**Comment by mjbvz** [comment] 2023-12-14 01:00
Duplicate of #81205. Still not worth it IMO for the complexity it adds

**Closed by mjbvz** 2023-12-14 01:00 UTC

**Comment by e965** [comment] 2023-12-14 11:41
@mjbvz however, the problem does exist. And it's at least 4 years old, judging by the issue you attached. Why not keep the issue open so you don't forget about it?
Perhaps in the future the team can revisit this issue and figure out how to make better use of the TS language server.
