### ISSUE TITLE
Go to definition doesn't work properly when there are multiple definitions

### ISSUE THREAD

**Issue by saimageshvar** [microsoft/vscode#80555] opened 2019-09-09 11:10 UTC
- VSCode Version: 1.38.0
- OS Version: ubuntu 16.04 LTS
I am using ruby extension to have intellisense and go to defintions
When there are multiple definitions for a method, while clicking on go to definition and choosing the file from the mini popup that appears, it doesn't work if I choose the definition in the same file. It works fine if I choose definitions given in other files.

Does this issue occur when all extensions are disabled?: Can't reproduce since go to definition works on ruby extension

**Comment by jrieken** [comment] 2019-09-09 13:41
/duplicate of https://github.com/microsoft/vscode/issues/80362

**Closed** 2019-09-09 13:42 UTC
Labels: *duplicate
