### ISSUE TITLE
open two same file

### ISSUE THREAD

**Issue by 307914070** [Microsoft/vscode#59669] opened 2018-09-29 09:24 UTC
1、in one folder  I hava a javascript file, name is "WikiAPI.ts"
2、when I open it, and edit it, 
3、when syntax error, I open error list and click it.
4、can open two file， one is "WikiAPI.ts"  another is "WikiApi.ts"

**Comment by mjbvz** [comment] 2018-09-29 19:34
Duplicate of #51184. The editor can get into this bad state on case-insensitive file systems

**Closed by mjbvz** 2018-09-29 19:34 UTC
