### ISSUE TITLE
elapsed time

### ISSUE THREAD

**Issue by raspblueberrypi** [microsoft/vscode#81839] opened 2019-10-02 12:37 UTC
I would be pleased if it displays elapsed time(how long a task ran) from program execution to the end.

**Comment by Tyriar** [comment] 2019-10-02 15:18
Do you mean how long VS Code is running or how long a task ran for or something else?

**Comment by raspblueberrypi** [comment] 2019-10-04 08:20
how long a task ran

**Comment by alexr00** [comment] 2019-10-08 10:10
duplicate of https://github.com/microsoft/vscode/issues/67094

**Closed by alexr00** 2019-10-08 10:10 UTC
Labels: feature-request, tasks
