### ISSUE TITLE
Support "Move to a different file" refactoring

### ISSUE THREAD

**Issue by carpben** [microsoft/vscode#91819] opened 2020-02-29 15:59 UTC
I mostly work with Typescript. Currently VSCode supports "Move to new file" refactoring for declarations. However, I'm usually looking to move a declaration to an existing file, rather than create a new one. I can of course cut-paste it, but then I will also need to update imports manually. I would love to see a "Move to a different file" feature. Such an option will be added to the context menu. After selecting it, user will choose a file he wants to append the declaration to. Upon file selection, the expression will be appended to the end of the file, and all imports will be updated.

**Comment by mjbvz** [comment] 2020-03-02 19:27
Duplicate of https://github.com/microsoft/TypeScript/issues/29988

**Closed by mjbvz** 2020-03-02 19:27 UTC

**Comment by carpben** [comment] 2020-03-02 20:21
Somewhat surprised that this feature request lives in the Typescript repository, am I missing anything?
