### ISSUE TITLE
No Variables context menus in web

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#107310] opened 2020-09-23 17:20 UTC
- open the playgound
- install Mock debug 1.44.1
- "debug" test.md
- open context menu on variable "local_i"

Observe: no action "Toggle between..."

<img width="892" alt="2020-09-23_19-12-54" src="https://user-images.githubusercontent.com/1898161/94046888-8e8fc380-fdd1-11ea-873b-f5ed83b264b5.png">

In desktop VS Code the action shows up:

<img width="754" alt="2020-09-23_19-14-00" src="https://user-images.githubusercontent.com/1898161/94046755-6738f680-fdd1-11ea-88ff-8ff602535c86.png">

**Comment by isidorn** [comment] 2020-09-23 17:30
Works for me

Here are my steps:
1. Go to https://vscode-web-test-playground.azurewebsites.net/?enter=true
2. Install mock debug
3. Create launch.json for the mock debug to debug file.md
4. Start debugging -> context menu action appears on `local_i` variable

![Screenshot 2020-09-23 at 19 28 46](https://user-images.githubusercontent.com/1926584/94047911-05798c00-fdd3-11ea-9dfd-1ca75d246370.png)

**Comment by isidorn** [comment] 2020-09-23 17:33
I do see a different problem:
When I start debugging a mock debug session the file does not get opened and I get the following error
Do you see this?

![Screenshot 2020-09-23 at 19 33 01](https://user-images.githubusercontent.com/1926584/94048313-9e100c00-fdd3-11ea-87bf-1ee90fa09da3.png)

**Comment by weinand** [comment] 2020-09-23 21:51
I'm starting debugging without a launch.json but with the debug button in the editor's tool bar.
If I create a launch config, the context menu shows up.

The menu contribution's "when" clause is this:
```js
"when": "debugConfigurationType == 'mock' && debugProtocolVariableMenuContext == 'simple'"
```
Most likely this is a problem with the `debugConfigurationType` not being set correctly in case the debug session is started from the editor tool bar via the "debug.startdebugging" API.

I will look into the other problem you've mentioned.

**Comment by isidorn** [comment] 2020-09-24 13:49
Please use the following context key `debugType == 'mock'`. Since that is the one that trackes the focused debug session and which mock debug wantes here.

`debugConfigurationType` should only be used for the last selected debug configuration.
And since you do not have a launch.json configuration this is undefined.
We might want to change this, but I would not in order to not break some existing behavior.

So closing as designed.
I would change the `debugConfigurationType` if other adapters also hit this

**Closed by isidorn** 2020-09-24 13:49 UTC
Labels: debug

**Comment by weinand** [comment] 2020-09-24 14:03
@isidorn After changing the context variable to `debugType` this works fine now.
I've release Mock debug 1.44.2 with the fix.

**Comment by isidorn** [comment] 2020-09-24 14:21
Great, thanks!
