### ISSUE TITLE
icon api support file suffix

### ISSUE THREAD

**Issue by li1234yun** [microsoft/vscode#156769] opened 2022-08-01 01:24 UTC
Now the icon api does not support file suffix. But some file suffix represents different file type, like `go test` file that suffixs with `_test.go` etc. Maybe you can consider to support the icon api feature?

https://github.com/vscode-icons/vscode-icons/issues/3104

**Comment by aeschli** [comment] 2022-08-24 09:44
We have https://github.com/microsoft/vscode/issues/12493 to have full pattern support. I understand you are asking for a more limited feature (just prefix), but both pattern and prefix are equally difficult to implement given the way we chose to do the matching of icons to file name entry.

I'm marking this as duplicate of https://github.com/microsoft/vscode/issues/12493

**Closed by aeschli** 2022-08-24 09:44 UTC
