### ISSUE TITLE
Keybinding table row flashing background

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122141] opened 2021-04-25 18:04 UTC
Issue Type: <b>Bug</b>

While scrolling in the keybindings editor, the background color of a cell can change in an unpreditable way.

https://user-images.githubusercontent.com/876920/116004094-0a472e00-a5b6-11eb-9758-063afd23b3f6.mov

VS Code version: Code - Insiders 1.56.0-insider (Universal) (0310f02dc5d834bb3a7cc421ea5374aec8d011f1, 2021-04-23T05:12:49.229Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (5.58GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by usernamehw** [comment] 2021-04-25 19:15
Maybe the reason is https://github.com/microsoft/vscode/pull/118125/commits/79096af47550074181901344f5cbc7bb61027ea6. I remember making a pull request to change striped effect generation to use CSS which had a very similar effect.

**Comment by sandy081** [comment] 2021-07-28 14:32
Yeah this is the root cause - https://github.com/microsoft/vscode/commit/79096af47550074181901344f5cbc7bb61027ea6. As you scroll, nodes are removed from DOM the background changes for the given row because of `nth-child(even)` css trick.

Assigning to @joaomoreno to see if he has better suggestion than reverting above change.

**Comment by joaomoreno** [comment] 2021-09-06 13:00
Oh cool finding!

**Closed** 2021-09-06 14:37 UTC
Labels: bug, keybindings-editor, table
