### ISSUE TITLE
Feature request , option to open Files externally

### ISSUE THREAD

**Issue by Jeyanthinath** [Microsoft/vscode#31329] opened 2017-07-24 15:23 UTC
I am working with a python as well as excel sheet generation ,it would be great if there is an **option to open excel sheet externally** from vscode **_because excel sheet is not supported in vscode_**

**Comment by mjbvz** [comment] 2017-07-24 17:47
Duplicate of #12235

Try these extensions:

- https://marketplace.visualstudio.com/items?itemName=lfurzewaddock.vscode-opn  - customizable open

- https://marketplace.visualstudio.com/items?itemName=sandcastle.vscode-open - Open with default for os

**Closed by mjbvz** 2017-07-24 17:47 UTC
Labels: duplicate, workbench
