### ISSUE TITLE
GitHub Authentication redirect window says Signing In to null...

### ISSUE THREAD

**Issue by amankkg** [microsoft/vscode#97390] opened 2020-05-10 06:00 UTC
- VSCode Version: 1.45.0
- OS Version: Ubuntu 20.04

**Steps to Reproduce:**

1. Within VSCode trigger GitHub OAuth browser dialog
2. Successfully sign in using GitHub account
3. Observe instructions step #3 as in an attachment

**Actual behavior:**
> 3. Click **Signing in to null...** in the status bar.

**Expected behavior:**
> 3. Click **Signing in to GitHub...** in the status bar.

**Does this issue occur when all extensions are disabled?** Yes, it is not related to VSCode itself

![Screenshot from 2020-05-09 16-18-24 (2)](https://user-images.githubusercontent.com/3933028/81491845-b8c66600-92b4-11ea-8e7b-49e8f84b8546.png)

**Comment by RMacfarlane** [comment] 2020-05-11 23:36
Duplicate of https://github.com/microsoft/vscode/issues/96368

**Closed by RMacfarlane** 2020-05-11 23:36 UTC
Labels: new release
