### ISSUE TITLE
Show index.* files at the top of any folder in Explorer panel

### ISSUE THREAD

**Issue by youbastard** [microsoft/vscode#108452] opened 2020-10-10 14:28 UTC
I would love an option to change the sorting behavior of files in the Explorer Panel, specifically to place any index file (js|ts|html|css...) at the top of a folder directory, for convenience and aesthetic reasons. Given that index files have special consideration when using `import` and `require` statements they should also (optionally) have some priority in the directory structure.

**Comment by isidorn** [comment] 2020-10-20 13:55
Closing as duplicate of more explorer sorting options.
Thouhg we will probably not tackle this exact request.

**Closed** 2020-10-20 13:55 UTC
Labels: *duplicate
