### ISSUE TITLE
Extraneous padding between editor text & minimap/scrollbar

### ISSUE THREAD

**Issue by Metaception** [Microsoft/vscode#43604] opened 2018-02-13 18:34 UTC
### Issue Type
Bug

### Description

There is extra padding between the editor text and the minimap/scrollbar. Despite there being enough space for more characters in the available space, a horizontal scrollbar appears. More testing shows there to be 16px padding between the editor text and the minimap/scrollbar.

![image](https://user-images.githubusercontent.com/15968032/36167091-8e15f48a-10ec-11e8-84f7-6cb2b604a278.png)

Additionally, workarounds described in #28653 to hide the scrollbar increases the extra padding by the width of the scrollbar, making it impossible to recover horizontal space even if the scrollbar is hidden.

If this is intentional, I request an option to remove this padding.

Tested on a completely clean install with default settings. Same result with minimap on/off, scroll bar on/off, and different windows size.

**Steps to Reproduce:**

1. Insert characters on a single line until the characters approaches the minimap/scrollbar
2. When there is less than 16px of space remaining, a horizontal scrollbar appears despite there being sufficient space for more characters

### VS Code Info

VS Code version: Code 1.20.0
OS version: Windows_NT x64 10

Extensions: none
Reproduces without extensions

**Comment by alexandrudima** [comment] 2018-02-15 10:07
This is intentional. The idea is that it is uncomfortable to type at the right edge of the editor without some padding. 

https://github.com/Microsoft/vscode/blob/3efe22f1558b85ff3381ab7d3e76d501314f14dc/src/vs/editor/common/viewLayout/viewLayout.ts#L21

**Comment by Metaception** [comment] 2018-02-16 00:38
Is there some sort of secret setting to disable/control the amount of padding like in #12543 or ideally some kind of official option in the roadmap?

Also, I am guessing this takes into account the 14px scrollbar, which is why hiding the scrollbar with CSS doesn't recover horizontal space.

**Comment by alexandrudima** [comment] 2018-02-16 14:48
No, at this time, this is a constant and not a runtime option (hidden or otherwise). PR welcome, we could make it a "hidden" option, similar to `editor.lineDecorationsWidth`.

**Comment by alexandrudima** [comment] 2018-04-27 12:42
Duplicate of #43208

**Closed by alexandrudima** 2018-04-27 12:42 UTC
Labels: editor-rendering, feature-request
