### ISSUE TITLE
After upgrading to Ver. 1.47.0, search feature stopped working

### ISSUE THREAD

**Issue by nm123github** [microsoft/vscode#102884] opened 2020-07-19 02:33 UTC
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0 (Catalina Ver. 10.15.5)

Steps to Reproduce:

Open VSCode and try searching for anything. I just see the blue progress bar moving and a clock icon on the search bar. Attaching a video of the same. If we've previously opened the file the search seems to work for that file, but for unopened files it does not.

![vscodesearch_example](https://user-images.githubusercontent.com/8527474/87885985-67caa080-c9ce-11ea-9741-fa1cfde16a9d.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2020-07-20 23:53
Can you tell me whether there are any errors in the dev tools console (Help > Toggle Developer Tools)

Also, can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by nm123github** [comment] 2020-07-21 00:59
Below is the output from Developer console (when i start up the workspace).
![image](https://user-images.githubusercontent.com/8527474/88000445-7f7b5500-cab2-11ea-84e7-43069392e64a.png)

I clear the console, and try to search for something. Noticed this warning, whenever i try to search for anything "IPC "Search" crashed with exit code null and signal SIGABRT".
![image](https://user-images.githubusercontent.com/8527474/87999933-2bbc3c00-cab1-11ea-9d18-811e491c07e7.png)
I do notice some errors/warnings on startup, let me know if you'd like me to send over those too.

Same issue with the insiders edition.

**Comment by geauxtigers** [comment] 2020-07-23 04:03
I am having the same issue.  I cannot search extensions since the upgrade but my errors are different.  Another oddity is that since the update I cannot got to github website on chrome or ff but luckily I can on Edge.

**Comment by roblourens** [comment] 2020-07-23 04:31
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

@deepak1556 does the first error in the screenshot mean anything to you?

**Comment by deepak1556** [comment] 2020-07-23 04:47
Based on the error log in devtools, the root cause is same as https://github.com/microsoft/vscode/issues/100118

might wanna check if there is `export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/` set https://github.com/microsoft/vscode/issues/100118#issuecomment-647888790

**Comment by geauxtigers** [comment] 2020-07-23 05:27
@roblourens I downloaded the insiders' build and can search extensions on that version.  The dev console output has output shown in the attached file.  I looked in the directory where the files were expected to be located, however the only files in that directory were workbench.html and workbench.js

![vscode](https://user-images.githubusercontent.com/8951542/88254273-61605100-cc7a-11ea-924a-2d300f638529.PNG)

**Comment by nm123github** [comment] 2020-07-23 08:19
@deepak1556 unsetting DYLD_LIBRARY_PATH worked for me.

From what i gathered, mysql is shipping protobuf which is causing this issue. Is there a fix planned so that we don't need to comment out export of DYLD_LIBRARY_PATH?

**Comment by deepak1556** [comment] 2020-07-23 08:53
Glad to know it helped, as for a more proper fix you should follow up with the homebrew package. There is nothing vscode can do here.

Closing this as duplicate of https://github.com/microsoft/vscode/issues/100118

**Closed by deepak1556** 2020-07-23 08:53 UTC
Labels: needs more info

**Comment by nm123github** [comment] 2020-07-23 08:57
Thanks @deepak1556 . Does this mean vscode search will have issues on any machine where protobuf is installed? Just trying to understand the issue so that i can follow up with the right folks.

**Comment by deepak1556** [comment] 2020-07-23 09:15
> Does this mean vscode search will have issues on any machine where protobuf is installed?

No, the issue will happen only when mysql library > 8.0.18 is in the dyld path, the protobuf library it ships with has some unmet symbols by /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib . The solution is to either remove the library from the dyld path or build the library with system protobuf.
