### ISSUE TITLE
Focus editor when using Find Widget

### ISSUE THREAD

**Issue by jsunsawyer** [microsoft/vscode#71467] opened 2019-03-29 20:43 UTC
After typing in the search field, pressing `enter`, `cmd + g`, or `cmd + shift +g` should focus the current editor that is being searched.

Currently, the Find Widget keeps the focus, so the user is required to put the focus back in the editor before they can update any text.

With this change, users can always put the focus back in the editor with `cmd + f`.

**Comment by atiris** [comment] 2019-04-01 07:45
I think the expected functionality of the Find Panel is not described in the User's Guide. So you can't tell if a particular Find Panel behavior is wrong or not.

The requirement to write basic rules on how the Find Panel working I entered here: [Find Panel in the Guide](<https://github.com/Microsoft/vscode/issues/70210>). So far, I have no response whether this is a good idea or not. Also, some behaviors seem like a bug to me, but without Find panel definition I can't say for sure. I think they (vscode programmers) will recommend you using ESC :smile: which is not what I except like best practice of using Find panel.

In your case (and in ideal world) I would expect:

- ENTER => Finding next occurrence, Find panel has still focus. (working)
- SHIFT + ENTER => Finding previous occurrence, Find panel has still focus. (working)
- CTRL + ENTER => Silngle occurrence confirmation, document get focusing, Find panel is closed. (not working, it's more intuitive to me than using ESC)
- ALT + ENTER => All confirmation. All occurences are selected, cursor is multiplied, document has focus, Find panel is closed. (partially works, Find panel is not closed)

Anyway, I think it is first necessary to agree on the Find panel behavior and write these requirements into the user's guide.

**Comment by atiris** [comment] 2019-04-02 05:59
Clear, you need option to close the Find panel after searching (replace actual ENTER and ESC sequence only with ENTER). And I would like to describe the behavior of the Find panel, because now I do not know if the correct behavior of the Find Panel is to find and close it (like you would), and the current behavior is wrong or it is as designed.

**Comment by berliner** [comment] 2019-07-15 13:35
Coming from a Textmate 2 and Sublime background, I definitely find it counter-intuitive that the focus is not on the editor after doing a search. When I search for something, then I generally want to interact with the found string, either copying it, deleting it, changing it, or whatever, but the place where I most definitely don't need to do any more work is in the search field. So having to hit ESC after searching, is adding a couple of hundreds of extra key hits per day to my workflow.

**Comment by atiris** [comment] 2019-07-15 15:39
I created a request to discuss the functionality of the Find Panel [Find panel documentation is missing](<https://github.com/microsoft/vscode-docs/issues/2873>). @berliner please, contribute also to that request, if you have a better view of how to design the entire Find Panel functionality...

For me, it is intuitive (Notepad ++ in Windows, Geany in Linux) that pressing Enter will find the next occurrence of the search term, but the panel will not close because I do not expect to find the one occurrence that I search for immediately. Therefore, it is more natural for me to go through the individual occurrences with Enter. The use of ESC to confirm selection is significantly non-intuitive. Since using ESC, I would expect to close the panel and return the original selection (not the last item found). I would expect something like CTRL + ENTER to confirm selected occurrence (like in ALT + ENTER for all occurrences is being used).

**Comment by berliner** [comment] 2019-07-15 16:06
@atiris Not sure that I will find the time to work on the proposal you linked too.

But some quick remarks anyway. In most editors you can use a different shortcut to loop through all found occurrences of a string, on a Mac it's usually CMD-g (and SHIFT-CMD-g for reverse loops). I have set this up in my vscode too for the shortcut `editor.action.nextMatchFindAction`, so this gives me your intended behaviour (looking for further occurrences because the one you're looking for is probably not the first one found). The main difference is that you can use that shortcut in the editor and the cursor automatically jumps to the next found match, enabling you to directly interact with the match.

If you look at bit at behaviours of search fields all over the web, you'll probably find that keeping the focus in the search bar is rather the exception than the rule. I don't mind this behaviour in word processors or excel-type programs, but code editors should focus on minimising key strokes.

The current behaviour feels in sync with how this is often implemented on Linux (no idea about Windows), but coming from an environment with a stronger emphasis on UX and workflows (as the Mac has been, though arguably in decline, bot of those points my personal view, let's not start a discussion about this ;)) it just doesn't seem like the best solution. TextMate really does an amazing job at this, if you get a chance, try it out for a little while.

**Comment by rebornix** [comment] 2019-10-25 01:00
Thanks all for your contribution. I understand the ask for focusing the editor after searching but I don't think we are going to make the change considering how many users will be affected by that. With https://github.com/microsoft/vscode/pull/63176 merged and another shortcut CMD+G, you can search selections without losing focus and if you use the Find Widget to type in new queries, once the focus goes into the editor, you can use CMD+G to navigate in the editor.

**Closed** 2019-10-25 01:00 UTC
Labels: *out-of-scope, editor-find, under-discussion

**Comment by jsunsawyer** [comment] 2019-10-25 16:12
What's the more common thing that users do next after searching using the find widget? That's what should drive this decision.

What does keeping the user focused on the find widget really offer? Let's say a user doesn't find what they're searching for and wants to search for something else. Does leaving them focused on the find widget save them any time? They need to clear out their previous search by either deleting their previous search with backspace, selecting all text then typing, or entering the find widget hotkey, which selects all the search text anyway.

It just feels clunky right now. If this isn't going to be addressed simply because people are used to its clunky behavior, an option for those who prefer that the editor is focused upon searching would be greatly appreciated.

**Comment by jsunsawyer** [comment] 2019-11-11 17:46
@rebornix Seeing some of the features that were added in 1.40.0, I'm having a hard time understanding why improvements to the find widget are considered out-of-scope.

You introduced an option to set the background color of the active activity bar indicator. I use the find widget constantly. 

Please consider re-opening this issue, as I don't believe that it should be marked as out-of-scope.

**Comment by francois-m** [comment] 2020-04-29 11:48
I finally found a solution for giving the focus back to the editor after search (Ctrl+F): just map the Enter/F3 keys to the "workbench.action.focusLastEditorGroup" command, which will occur after the default mappings for "editor.action.nextMatchFindAction".

Add these mappings to your keybindings.json (edit it with command "Open Keyboards Shortcuts (JSON)":

    {
        "key": "enter",
        "command": "workbench.action.focusLastEditorGroup",
        "when": "editorFocus && findInputFocussed"
    },
    {
        "key": "f3",
        "command": "workbench.action.focusLastEditorGroup",
        "when": "editorFocus && findInputFocussed"
    }

**Comment by Binly42** [comment] 2022-01-28 07:45
now we can use `workbench.action.focusActiveEditorGroup`
