### ISSUE TITLE
workbench.main.js

### ISSUE THREAD

**Issue by xyq153596** [Microsoft/vscode#17280] opened 2016-12-15 09:21 UTC
workbench.main.js:132 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.0.6|
|jquerysnippets|donjayamanne|0.0.1|
|vue|liuji-jim|0.1.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|
|debugger-for-chrome|msjsdiag|0.4.8|
|sass-indented|robinbentley|1.1.0|
|JavaScriptSnippets|xabikos|1.1.0|
|ReactSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment] 2016-12-15 22:30
I believe this is a duplicate of #17208 which @alexandrudima  addressed with 4747f1c2250a82cffca26152f487f2a612ba622d

Please let me know if this is not the case, and provide a complete call stack + list of repo steps so that we can investigate.

Thanks

**Closed by mjbvz** 2016-12-15 22:30 UTC
