### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by aseph8083** [microsoft/vscode#140192] opened 2022-01-06 02:55 UTC
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57011:22)
    at getPropertyOfType (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57671:24)
    at resolveESModuleSymbol (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49817:54)
    at getTargetOfNamespaceImport (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49236:28)
    at resolveAlias (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at getSymbol (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47838:38)
    at resolveNameHelper (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48131:34)
    at resolveName (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48114:20)
    at resolveEntityName (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49453:42)
    at resolveEntityName (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49461:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49413:24)
    at getTargetOfImportEqualsDeclaration (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48865:28)
    at getTargetOfAliasDeclaration (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49232:28)
    at resolveAlias (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49271:67)
    at mergeSymbol (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47624:42)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47737:20)
    at mergeSymbol (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47648:21)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47737:20)
    at mergeModuleAugmentation (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47753:17)
    at initializeTypeChecker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:85046:25)
    at Object.createTypeChecker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47395:9)
    at Object.getTypeChecker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114404:79)
    at synchronizeHostData (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159898:21)
    at Object.getProgram (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168762:44)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:97
    at Object.flatMap (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170260:46)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172184:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172219:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by IllusionMH** [comment] 2022-01-06 09:27
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

**Closed** 2022-01-06 09:28 UTC
Labels: *duplicate

**Comment by 98DE9E1F** [comment] 2022-01-06 13:08
we have same problem 

`<semantic> TypeScript Server Error (4.6.0-dev.20220101) Cannot read property 'flags' of undefined TypeError: Cannot read property 'flags' of undefined at getPropertyOfObjectType (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:57057:22) at getPropertyOfType (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:57727:24) at resolveESModuleSymbol (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49830:54) at getTargetOfNamespaceImport (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49015:28) at getTargetOfAliasDeclaration (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49249:28) at resolveAlias (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49294:30) at getSymbol (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:47849:38) at resolveNameHelper (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:48142:34) at resolveName (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:48125:20) at resolveEntityName (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49466:42) at getTargetOfAliasLikeExpression (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49223:29) at getTargetOfExportAssignment (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49212:28) at getTargetOfAliasDeclaration (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49259:28) at resolveAlias (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49294:30) at resolveSymbol (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49284:67) at resolveExternalModuleSymbol (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49776:36) at getTargetOfNamespaceExportDeclaration (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49199:28) at getTargetOfAliasDeclaration (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49261:28) at resolveAlias (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49294:30) at resolveSymbol (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:49284:67) at mergeSymbol (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:47635:42) at /Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:47750:47 at Map.forEach (<anonymous>) at mergeSymbolTable (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:47748:20) at initializeTypeChecker (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:85133:21) at Object.createTypeChecker (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:47406:9) at Object.getTypeChecker (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:114662:79) at synchronizeHostData (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:160340:21) at Object.getProgram (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:160461:13) at ConfiguredProject.Project.updateGraphWorker (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:165476:53) at ConfiguredProject.Project.updateGraph (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:165405:42) at ConfiguredProject.updateGraph (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:166398:63) at ProjectService.createLoadAndUpdateConfiguredProject (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:168122:25) at ProjectService.assignProjectToOpenedScriptInfo (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:169205:44) at /Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:169545:97 at Object.flatMap (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:502:25) at ProjectService.applyChangesInOpenFiles (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:169545:41) at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:170703:46) at /Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:172636:88 at IOSession.Session.executeWithRequestId (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:172627:28) at IOSession.Session.executeCommand (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:172636:33) at IOSession.Session.onMessage (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:172662:35) at Interface.<anonymous> (/Users/bingguo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20220101/node_modules/typescript/lib/tsserver.js:175267:31) at Interface.emit (events.js:315:20) at Interface._onLine (readline.js:337:10) at Interface._normalWrite (readline.js:482:12) at Socket.ondata (readline.js:194:10) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
`
