### ISSUE TITLE
Command for focusing on file explorer is broken

### ISSUE THREAD

**Issue by tomasaschan** [microsoft/vscode#86990] opened 2019-12-14 13:23 UTC
Issue Type: <b>Bug</b>

After the latest update, the command for focusing on the file explorer view seems to be broken. Neither the shortcut I previously had defined (Ctrl+Shift+E) nor manually finding the command in the command menu (Ctrl+Shift+P, search for "file explorer" and pick the command "File: Focus on File Explorer") does anything.

There is a command that seems like it's doing the same thing: "Explorer: Focus on Folders View", but the shortcut I had configured for the old command was not carried over to the new one.

VS Code version: Code - Insiders 1.42.0-insider (d4789ac7c9d9f73865ca92f8b1d67be5d5a4c283, 2019-12-13T05:37:13.458Z)
OS version: Windows_NT x64 10.0.19037
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|Memory (System)|5.96GB (2.45GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
haskell-linter|hoo|0.0.6
hoogle-vscode|jca|0.0.7
language-haskell|jus|2.6.0
github-actions-vscode|Oma|2.7.0
rust|rus|0.7.0
crates|ser|0.4.7
haskero|Van|1.3.1
stylish-haskell|vig|0.0.10
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.41.5
vscode-remote-extensionpack|ms-|0.19.0
scala|sca|0.3.8

</details>

**Comment by tomasaschan** [comment] 2019-12-14 13:29
After some more digging around in my config, I think my confusion is because the "View: Show Explorer" command (which was the one I really had bound to `Ctrl+Shift+E`) previously used to put focus in the folder explorer, too, but now doesn't.

Also, @vscodebot mislabelled this. I might have had the integrated terminal focused when I reported the issue, but the issue is not related to the terminal.

**Comment by isidorn** [comment] 2019-12-16 09:35
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/86883
However leaving up to @sbatten to close as duplicate if needed, because if not it is caused by the viewlet refactoring

**Comment by sbatten** [comment] 2019-12-16 15:09
yes this appears to fixed in the latest insiders. closing as duplicate of #86883

**Closed by sbatten** 2019-12-16 15:09 UTC

**Comment by rob2d** [comment] 2019-12-27 18:58
this issue keeps appearing every few months -- is there anything that is leading to it happening over and over again that could possibly be prevented? It's a huge productivity drain to reach for that 100x per day every few weeks and have to remember "oh right -- have to Ctrl+Shift+P because this is broken", then traverse github to find the random issues keep getting closed.
