### ISSUE TITLE
Log items are under console groups

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91439] opened 2020-02-25 18:36 UTC
Refs: https://github.com/microsoft/vscode/issues/91095

Maybe I'm implementing something wrongly, but it seems like console messages aren't getting grouped.

Test code:

```
console.log("This is the outer level");
console.group();
  console.log("Level 2");
  console.group();
    console.log("Level 3");
  console.groupEnd();
  console.log("Back to level 2");
console.groupEnd();
console.log("Back to the outer level");
```

![](https://memes.peet.io/img/20-02-e647fc23-d7bc-47f2-8e0d-39a5cc0c9911.gif)

DAP logs: https://gist.github.com/connor4312/7dc9e917bd802e4950087363f9ed5b75

js-debug patch if you want to take this for a spin:

```patch
diff --git a/src/adapter/threads.ts b/src/adapter/threads.ts
index 815b028..6c93366 100644
--- a/src/adapter/threads.ts
+++ b/src/adapter/threads.ts
@@ -900,7 +900,7 @@ export class Thread implements IVariableStoreDelegate {
   ): Promise<Dap.OutputEventParams | undefined> {
     switch (event.type) {
       case 'endGroup':
-        return;
+        return { category: 'stdout', output: '', group: 'end' };
       case 'clear':
         return this._clearDebuggerConsole();
     }
@@ -954,10 +954,18 @@ export class Thread implements IVariableStoreDelegate {
       variablesReference = undefined;
     }
 
+    const group =
+      event.type === 'startGroup'
+        ? 'start'
+        : event.type === 'startGroupCollapsed'
+        ? 'startCollapsed'
+        : undefined;
+
     return {
       category,
       output,
       variablesReference,
+      group,
       source: uiLocation ? await uiLocation.source.toDap() : undefined,
       line: uiLocation ? uiLocation.lineNumber : undefined,
       column: uiLocation ? uiLocation.columnNumber : undefined,

```

**Comment by weinand** [comment] 2020-02-26 10:10
Looks like a duplicate of #91416

**Closed** 2020-02-26 12:01 UTC
Labels: *duplicate, bug, debug
