### ISSUE TITLE
Colorization break when using typeof statement in function return type

### ISSUE THREAD

**Issue by daxaymakwana** [microsoft/vscode#118410] opened 2021-03-08 07:52 UTC
- VS Code Version: 1.54.1
- OS Version: Linux x64 4.15.0-136-generic

Defining return type of function using `typeof` keyword of Typescript will break syntax colorization of as displayed in below image.
![Screenshot from 2021-03-08 13-20-43](https://user-images.githubusercontent.com/36629241/110290758-26e0d400-8011-11eb-84a4-90d948bad7a9.png)

Steps to Reproduce:

1. Open new file and select language mode as Typescript
2. Copy and Paste below code.
```
export function data(d: { a: number }): typeof d {
    const a = 10;
    return { a: a + d.a };
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2021-03-08 16:56
Duplicate of issue moved to https://github.com/microsoft/TypeScript-TmLanguage/issues/858

**Closed** 2021-03-08 19:18 UTC
Labels: *duplicate, new release
