### ISSUE TITLE
Inconsistancy between md highlighting and preview

### ISSUE THREAD

**Issue by pcd444** [microsoft/vscode#159973] opened 2022-09-03 06:26 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Create md file
2. paste following
ab|cd
--|--
ef\\\\\\\\| |gh
3. open preview
4. Observe difference between highlighting and preview

[highlighting](https://imgur.com/a/iV4J8N4)
[preview](https://imgur.com/a/DdoUdiL)

As you can see the highlighting makes it seem like there should be two raw backslash characters, but in the preview there is only one and one of the vertical slash characters has been escaped. I don't know which is right but they should agree.

Also other md renderers do it a different way.

**Comment by mjbvz** [comment] 2022-09-06 15:32
Duplicate of #91279

**Closed by mjbvz** 2022-09-06 15:32 UTC

**Comment by pcd444** [comment] 2022-09-14 21:28
I don't belive this is a duplicate of the linked issue. The linked issue seems to be about the syntax highlighting of code snippets in the preview. This issue is that the syntax highlighting of the markdown code in the markdown editor is different from how the markdown is interpreted by the preview. In the raw MD code

ab\|cd
--|--
ef\\\\\\\\| |gh

The series of slashes \\\\\\\\ are all highlighted orange. This implies that it should end up as 2 plaintext slashes in render. But when you look at the preview there is only one slash and somehow the table divide character "|" has been escaped.
