### ISSUE TITLE
IntelliSense tooltip is not growing with more and larger text

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#7488] opened 2016-06-09 17:18 UTC
- VSCode Version: 1.2.0
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. Make the font size larger than default in user settings
2. Write code that causes IntelliSense to raise a tooltip
3. Notice the truncated text due to the tooltip not growing to fit the content

### Repro screenshot

![image](https://cloud.githubusercontent.com/assets/1445483/15939179/9f25fee6-2e44-11e6-877d-38051a02f9e2.png)

**Comment by joaomoreno** [comment] 2016-07-13 15:06
Duplicate of #2465

**Closed by joaomoreno** 2016-07-13 15:06 UTC
Labels: bug
