### ISSUE TITLE
Debugger incorrectly escapes arguments with trailing back slashes

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#73099] opened 2019-04-30 19:42 UTC
@Rots commented on [Sun Apr 28 2019](https://github.com/Microsoft/vscode-python/issues/5504)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): 2019.4.11987
- OS and version: Win 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.2 64bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): na
- Relevant/affected Python packages and their versions: na

## Expected behaviour

All the arguments from the `launch.json` are passed to the lauched file as specified.
I.e. The output should be list of 3 items: program and two arguments in the example below.

## Actual behaviour

The arguments get mungled up, when space and trailing backslash is used.
Only two items are produced in the list: program and 'merged' args

## Steps to reproduce:

example.py:
```
import sys
print (sys.argv)
```

launch.json:
```
        {
            "name": "Argument handling issue example",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "args": ["C:\\path to\\arg1\\","arg2"],
            "console": "integratedTerminal"
        },
```

Run the launch configuration with the example.py.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Empty
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
extensionHost.ts:215 Extension Host
extensionHost.ts:216 Debugger attached.
```

Output of integrated terminal:

```
PS C:\Users\XXX> cd 'c:\Users\XXX'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Python37\python.exe' 'c:\Users\XXX\.vscode\extensions\ms-python.python-2019.4.11987\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '49818' 'c:\Users\XXX\example.py' 'C:\path to\arg1\' 'arg2'
['c:\\Users\\XXX\\example.py', 'C:\\path to\\arg1" arg2']
```

**Comment by DonJayamanne** [comment] 2019-04-30 19:43
## Note, this is not a Python Extension issue

**Comment by isidorn** [comment] 2019-04-30 20:38
No plans to fix this in the next couple of milestones.
Code pointer if you would like to investigate more and potentially provide a PR
https://github.com/Microsoft/vscode/blob/a30ca29b8b4a8a848b27fc55631cf3a4f3f7f85c/src/vs/workbench/contrib/debug/electron-browser/debugService.ts#L254

Checkout where the `args` array in the `configuration` does not get escaped.

**Comment by Rots** [comment] 2019-05-03 20:48
Thanks, to help the issue forward I did some investigation. I'm pretty sure at least part of the issue is here:
https://github.com/Microsoft/vscode/blob/a30ca29b8b4a8a848b27fc55631cf3a4f3f7f85c/src/vs/workbench/contrib/debug/node/terminals.ts#L348-L352

The trailing backslash in `s` probably escapes the closing quote.
I'd expect anyone familiar with the tooling could easily create a failing unit test for the `prepareCommand` function to demonstrate the issue.

**Closed** 2019-05-24 14:50 UTC
Labels: bug, debug

**Comment by weinand** [comment] 2019-05-24 14:56
Two bugs here:
- With Powershell if a quoted argument contains a backslash before the ending quote (e.g. `'foo\'`) the quote is treated literally and results in `foo'` being passed. The fix is to detect this case and double (escape) the backslash.
- For bash-like shells, backslashes are now escaped with another backslash.
