### ISSUE TITLE
Performance Report + CPU Profile

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#22173] opened 2017-03-07 19:23 UTC
@bpasero 

Original issue: #20830 

- VSCode Version: <code>Code - Insiders 1.11.0-insider (5e9357bd5111eacf2b8fb39455c8afb5a42d632f, 2017-03-07T07:12:52.583Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)</code>
- Memory (System): <code>3.88GB (1.42GB free)</code>
- Memory (Process): <code>127.68MB working set (135.20MB peak, 105.72MB private, 27.04MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>50%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|49|
|main|app.isReady => window.loadUrl()|573|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2978|
|renderer|require(workbench.main.js)|6265|
|renderer|create extension host => extensions onReady()|3190|
|renderer|restore viewlet|0|
|renderer|restore editor view state|823|
|renderer|overall workbench load|8958|
|main + renderer|start => extensions ready|20998|
|main + renderer|start => workbench ready|18895|

---

[0a40_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/825510/0a40_main.cpuprofile.txt)
[0a40_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/825511/0a40_renderer.cpuprofile.txt)

Extensions:
*Couldn't provide it in the current state, because `Help > Report Issues` does nothing... But basically, it's like this(but any extension had been updated):*

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|Bookmarks|alefragnani|0.11.0|
|vscode-color|anseki|0.2.3|
|cdn-list|AryanMann|1.0.0|
|color-info|bierner|0.2.1|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.6|
|githistory|donjayamanne|0.1.5|
|EditorConfig|EditorConfig|0.3.4|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.2|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.10|
|vscode-firefox-debug|hbenl|0.8.8|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|GitHubIssues|HookyQR|0.1.2|
|composer|ikappas|0.5.0|
|docthis|joelday|0.4.0|
|to-data-uri|kieferrm|0.1.1|
|Go|lukehoban|0.6.53|
|copy-github-url|mattlott|0.1.0|
|font-awesome-codes-html|medzhidov|0.0.4|
|hex-rgba-converter|medzhidov|1.0.3|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|vscode-css-peek|pranaygp|1.2.4|
|dark-win16-theme|rbukovansky|0.0.4|
|vscode-hexdump|slevesque|1.1.4|
|vscode-gulp|tanato|0.0.4|
|highlight-trailing-white-spaces|ybaumes|0.0.2|
|intelligence-change-case|zhengxiaoyao0716|1.1.0|

**Comment by jrieken** [comment] 2017-03-08 08:50
wow, `_readFromDomElement` takes *11seconds* 😱

**Comment by jrieken** [comment] 2017-03-08 08:52
We have seen this issue already in other profiles, tho never that bad. Closing this a dupe of https://github.com/Microsoft/vscode/issues/22090. Thanks for reporting, stay patient as we work on a fix.

**Closed by jrieken** 2017-03-08 08:52 UTC
Labels: perf-profile, windows

**Comment by jrieken** [comment] 2017-03-09 15:58
@jens1o We have pushed a fix for the issue. Since the original behaviour was different on our machines we would like to see the effect on your machine. Can you please use latest insiders (from today on) and start it via `code-insider --prof-start`. That would help us verify this issue. Thanks and Happy Coding!

**Comment by jens1o** [comment] 2017-03-09 16:51
It's really fast... Wow. Thank you. And yes, I'd installed many fonts, since I am really a font freak.

**Comment by jrieken** [comment] 2017-03-10 07:52
Great! Thanks for getting back to us
