### ISSUE TITLE
Firing onDidChangeTreeData for a contributed tree causes the tree to jump to show that node centred in the view

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#77569] opened 2019-07-18 10:40 UTC
If you fire `onDidChangeTreeData` on a contributed tree node, the view jumps to place that node centred in the scrollable view, which is really jarring (it does not animate).

I've tweaked the sample "test" view to illustrate this here:

https://github.com/DanTup/vscode_repro_tree_jumping

```ts
view.onDidChangeSelection((e) => {
	if (e.selection && e.selection.length === 1)
		prov.onDidChangeTreeDataEmitter.fire(e.selection[0]);
});
```

If you run the sample and open the Test view, clicking on any node will cause it to jump to the middle. The reason for firing is the change is so that updates to the node will be reflected in the tree - it's not expected that it would jump around like this.

This happens both in stable and insiders.

**Comment by hbenl** [comment] 2019-07-20 13:49
May be related to #70707

**Comment by alexr00** [comment] 2019-07-30 09:28
Thank you for the easy example. I can see the cause. It is a duplicate of https://github.com/microsoft/vscode/issues/70707

**Closed** 2019-07-30 09:29 UTC
Labels: *duplicate, bug, explorer-custom
