### ISSUE TITLE
Multiline parameter list for lambda/arrow function loses syntax highlighting

### ISSUE THREAD

**Issue by mikehaas763** [Microsoft/vscode#30543] opened 2017-07-12 20:19 UTC
- VSCode Version: 1.14.0
- OS Version: Sierra 10.12.5

Steps to Reproduce:

1. Write some typescript in a typescript file like
```typescript
  const func = (
    foo: any,
  ) => '';
```

2. See that there's missing syntax highlighting
3. Screenshots given below

![image](https://user-images.githubusercontent.com/2096573/28138068-77320570-671d-11e7-80ce-fdfa26393d24.png)

![image](https://user-images.githubusercontent.com/2096573/28138130-b162bafa-671d-11e7-8c3d-a4b87356f133.png)

![image](https://user-images.githubusercontent.com/2096573/28138140-b902d394-671d-11e7-8b8e-6075c9a07431.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-07-12 20:22
This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/481 which has been marked wontfix. See [this comment](https://github.com/Microsoft/TypeScript-TmLanguage/issues/481#issuecomment-311740997) for more details

**Closed by mjbvz** 2017-07-12 20:22 UTC
Labels: new release, typescript, upstream
