### ISSUE TITLE
[tsx]syntax highlighting problem

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#35321] opened 2017-09-28 15:01 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.0.4
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.10.1
vscode-icons|rob|7.14.0
vscode-react-native|vsm|0.4.2

---
![tsx1](https://user-images.githubusercontent.com/24318019/30973875-ceff1d22-a4a0-11e7-8c76-8abcb46cf227.png)
![tsx2](https://user-images.githubusercontent.com/24318019/30973889-d71768f2-a4a0-11e7-8234-e4c8f1d395cd.png)

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-09-29 17:46
Please share the text source of this code along with the screenshots.

**Comment by shizengzhou** [comment] 2017-09-29 23:30
[index.zip](https://github.com/Microsoft/vscode/files/1345902/index.zip)

**Comment by mjbvz** [comment] 2017-09-30 16:09
Thanks @shizengzhou 

This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/481. The issue has been wontfixed upstream due to ambiguities with multiline parsing in this case

Closing as upstream

**Closed by mjbvz** 2017-09-30 16:09 UTC
Labels: duplicate, grammar, javascript
