### ISSUE TITLE
Need an easier way to find/remove settings that are set to its default value in settings.json

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#211743] opened 2024-04-30 19:16 UTC
When I try to clean up my settings.json, I had a hard time to find and remove the settings that are set to its default value. It would be great if vscode could dim those settings and provide a code action to remove all of them.

**Comment by rzhao271** [comment] 2024-04-30 22:13
Duplicate of https://github.com/microsoft/vscode/issues/165589

**Closed by rzhao271** 2024-04-30 22:13 UTC
