### ISSUE TITLE
Collapsed cell text in interactive window incorrect

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#129579] opened 2021-07-27 17:32 UTC
Testing #129288

1. Open a file and run a few cells to get the interactive viewlet up
2. In the interactive viewlet, run the `pwd` command a few times
3. 🐛 The wrong preview text shows for the command. It's not consistent either:

![Screencap demo](https://user-images.githubusercontent.com/7199958/127200772-5d7b2b8a-984e-408e-9215-85a568d51e2c.gif)

**Comment by rebornix** [comment] 2021-07-27 23:33
/duplicate of https://github.com/microsoft/vscode/issues/129551.

**Closed** 2021-07-27 23:34 UTC
Labels: *duplicate, interactive-window
