### ISSUE TITLE
VS Code locks directory while open

### ISSUE THREAD

**Issue by imjoeco** [Microsoft/vscode#71340] opened 2019-03-28 04:38 UTC
Issue Type: <b>Bug</b>

While running a gulp build task in the embedded terminal, the build directory is occasionally locked by VS Code resulting in an "EPERM: operation not permitted" error. Running the same command in a seperate PowerShell session as adminstrator while VS Code is open results in the same series of errors, and I'm denied access from even manually deleting the build folder.

However, once I close VS Code and re-run the gulp task in the same separate PowerShell session, it runs as expected. These errors happen any time VS Code is open. If I have to restart my gulp task, I have to close VS Code for it to work as I always get the same EPERM errors with it running and never any errors with it closed. In addition to the headache of losing my current file edit states on close to get things working in PowerShell, I cannot use the embedded terminal for running the gulp task like I was able to before. 

As far as I'm aware, this issue started with an update on or around the 9th of February, not sure which version though.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
tslint|eg2|1.0.43
beautify|Hoo|1.4.11
glassit|s-n|0.1.4
vim|vsc|1.2.0

(1 theme extensions excluded)

</details>

**Comment by Alexander-Taran** [comment] 2019-03-29 10:01
I observe the same behavior and suspect TS language server
while having a project with @types open in vs code
running `npm ci` in the project fails with:
```console
npm WARN prepare removing existing node_modules/ before installation
npm ERR! path C:\projectFolder\node_modules\@types
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\projectFolder\node_modules\@types'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\projectFolder\node_modules\@types']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\projectFolder\node_modules\@types'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\repos\\projectFolder\\node_modules\\@types' },
npm ERR!   isOperational: true,
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\repos\\projectFolder\\node_modules\\@types\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\repos\\projectFolder\\node_modules\\@types' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
```

**Comment by jlowcs** [comment] 2019-03-29 17:08
This seems to be a duplicate of https://github.com/Microsoft/vscode/issues/71221

**Comment by Tyriar** [comment] 2019-03-30 03:11
https://github.com/Microsoft/TypeScript/issues/29407

**Closed by Tyriar** 2019-03-30 03:11 UTC
Labels: integrated-terminal
