### ISSUE TITLE
Electron 16: electron downloader looses `Info.plist` file

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137437] opened 2021-11-18 11:37 UTC
Steps to Reproduce:

1. `git co electron-16.x.y`
2. `yarn`
3. `scripts/code.sh`

```
[1118/123330.347204:FATAL:electron_main_delegate_mac.mm(71)] Unable to find helper app
zsh: trace trap  scripts/code.sh
```

The underlying issue seems to be that `Info.plist` file does not appear in `.build/electron/Code - OSS.app/Contents` but I verified that it is there in the `~/Library/Caches/electron` zip, so it somehow gets lost when massaging?

I made sure to be on latest node.js 16.13.0 (macOS ARM).

![image](https://user-images.githubusercontent.com/900690/142408304-7fdea588-c729-45d4-bc14-a296928f4e7f.png)

**Comment by bpasero** [comment] 2021-11-18 11:37
Please advice how to diagnose this further.

**Comment by bpasero** [comment] 2021-11-18 12:04
Reproduces in GH CI: https://github.com/microsoft/vscode/runs/4250822106?check_suite_focus=true

**Comment by deepak1556** [comment] 2021-11-18 12:43
I am able to repro the issue on my end after a couple of tries of deleting `.build/electron`, `~/Library/Caches/electron` and running `scripts/code.sh`.

@joaomoreno the problem is isolated to `patchInfoPlist` section https://github.com/joaomoreno/gulp-atom-electron/blob/master/src/darwin.js#L392, basically the end callback of this `es.through` function https://github.com/joaomoreno/gulp-atom-electron/blob/698e30e6dd8fae6495ddb4323a3ac52804a8d0b7/src/darwin.js#L224-L280 is called before info.plist read is finished at https://github.com/joaomoreno/gulp-atom-electron/blob/698e30e6dd8fae6495ddb4323a3ac52804a8d0b7/src/darwin.js#L95 leading to an early termination with null file contents.

**Comment by joaomoreno** [comment] 2021-11-22 12:12
Can you try gulp-atom-electron@1.32.1? Fix: https://github.com/joaomoreno/gulp-atom-electron/commit/3c98f9b7c1501eebedfd99cfeda25b212943e874

**Comment by deepak1556** [comment] 2021-11-22 14:04
Verified the fix, thanks @joaomoreno

**Comment by deepak1556** [comment] 2021-11-22 14:06
Fixed in https://github.com/microsoft/vscode/commit/dee69dc8078b0ddf2fc4d5538d446c937d8d5cb9

**Closed by deepak1556** 2021-11-22 14:06 UTC
Labels: bug, verified, electron-16-update
