### ISSUE TITLE
Opening the find/replace dialog causes editor text to become blurry

### ISSUE THREAD

**Issue by Mehgugs** [Microsoft/vscode#51800] opened 2018-06-13 21:03 UTC
Issue Type: <b>Bug</b>

When I open the find/replace dialog the editor text becomes blurry until closed/restarted.

Tested with different themes and extensions disabled.
Reloading the editor does not fix/reset the issue only fixes if you restart it.

![picture of the bug occurring](https://i.imgur.com/TjfREQg.png)

ShareX capture of it occuring:
https://streamable.com/wze59

VS Code version: Code - Insiders 1.25.0-insider (583f1e4934c5fd3b62c2ca5bf177c728b31b9605, 2018-06-13T05:18:10.709Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Mehgugs** [comment] 2018-06-14 16:03
After some further playing around it seems to occur when opening *any* dialog except the top menu bar (File Edit Selection etc...).

**Comment by bpasero** [comment] 2018-06-15 05:16
@Mehgugs seems to be a duplicate of https://github.com/Microsoft/vscode/issues/51789

**Closed by bpasero** 2018-06-15 05:16 UTC
Labels: editor, editor-contrib
