### ISSUE TITLE
Clicking tree item in custom view executes command twice

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode#77677] opened 2019-07-19 21:59 UTC
Issue Type: <b>Bug</b>

Repro steps:
1. Install any azure extension (for example [storage](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage))
1. Make sure you're logged out (use command palette command to sign out if necessary)
1. Click the "Create a Free Azure Account" tree item
![Screen Shot 2019-07-19 at 2 50 00 PM](https://user-images.githubusercontent.com/11282622/61567626-0ecfd180-aa35-11e9-8cb0-e9583cef2b36.png)

Expected:
It opens browser once

Actual:
It opens browser twice

_Only repros on insiders, not stable._ Could be related to https://github.com/microsoft/vscode/issues/76998. If I click the tree item another time (aka when it's already selected) it only opens once.

VS Code version: Code - Insiders 1.37.0-insider (628bdedf671d3230fc76982fae845875a6f6c0da, 2019-07-19T08:10:27.295Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
azurerm-vscode-tools|ms-|0.6.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
azure-account|ms-|0.8.4
csharp|ms-|1.21.0
vscode-typescript-tslint-plugin|ms-|1.2.2
sort-lines|Tyr|1.8.0

</details>

**Comment by alexr00** [comment] 2019-07-29 12:18
Duplicate of #77418

**Closed by alexr00** 2019-07-29 12:18 UTC
Labels: bug, tree, workbench-views
