### ISSUE TITLE
Docker extension creates new terminal session with no console view: VS Code 1.17 new release

### ISSUE THREAD

**Issue by Kenya-West** [Microsoft/vscode#35822] opened 2017-10-08 10:08 UTC
- VSCode Version: 1.17
- OS Version: Windows 10 Creators Update
- Terminal: Powershell

Steps to Reproduce:

1. Download and install VS Code 1.17
2. Download and install Docker extension
3. Create dockerfile and go F1 > `Docker: Build` or `Docker: Run`
4. It creates another terminal session with no console view like this:
![vs_code_docker_no_console_view_terminal_1](https://user-images.githubusercontent.com/12271104/31315846-b7c26408-ac5b-11e7-9700-2b3b23f727e8.png)

Reproduces without extensions: No. requires Docker extension

Extensions list:
```
abusaidm.html-snippets
Angular.ng-template
christian-kohler.npm-intellisense
chrmarti.regex
CoenraadS.bracket-pair-colorizer
cssho.vscode-svgviewer
donjayamanne.githistory
ecmel.vscode-html-css
eg2.tslint
eg2.vscode-npm-script
formulahendry.auto-rename-tag
ginie.pug2html
HookyQR.beautify
humao.rest-client
humy2833.ftp-simple
joelday.docthis
johnpapa.Angular2
kisstkondoros.typelens
moppitz.vscode-extension-auto-import
mrmlnc.vscode-jade-snippets
ms-vscode.PowerShell
msjsdiag.debugger-for-chrome
PeterJausovec.vscode-docker
pflannery.vscode-versionlens
rubbersheep.gi
Shan.code-settings-sync
thekalinga.bootstrap4-vscode
ziyasal.vscode-open-in-github
```

I encountered this problem on two machines, both has same Windows and VS Code configuration and same project.

This problem has appeared after 1.17 update, no problem on previous version.

**Comment by pvginkel** [comment] 2017-10-09 13:34
The Rust extension does the same when you e.g. do a Cargo build. It'll open a new terminal every time. After the first one, the new ones don't show the terminal.

If you switch to e.g. the Output tab and then back to the Terminal tab, it does show the terminal.

If you delete the opened terminals until you've closed all of them and then do a new build, it'll render it correctly again. If you then do a second one, it won't show it again.

**Comment by chrisdias** [comment] 2017-10-09 16:51
@Kenya-West If you resize the terminal pane (make it taller or shorter), do the contents of the terminal appear?

**Comment by Kenya-West** [comment] 2017-10-10 00:58
> If you switch to e.g. the Output tab and then back to the Terminal tab, it does show the terminal.

@pvginkel thanks! This helped.


> If you resize the terminal pane (make it taller or shorter), do the contents of the terminal appear?

@chrisdias this also helped. Thanks!

So, OK. There are two workarounds, but when are developers gonna fix the bug? Does this bug happen only on Windows or on any platform?

**Comment by chrisdias** [comment] 2017-10-10 01:49
@Tyriar dupe of https://github.com/Microsoft/vscode/issues/34554?

**Comment by Kenya-West** [comment] 2017-10-10 02:33
Tried this one `code --args --disable-gpu` or `code --disable-gpu`: https://github.com/Microsoft/vscode/issues/35915#issuecomment-335209105 - didn't help.
DevTools say nothing.

**Comment by Tyriar** [comment] 2017-10-10 15:17
Duplicate https://github.com/Microsoft/vscode/issues/35728

**Closed by Tyriar** 2017-10-10 15:17 UTC
Labels: duplicate, integrated-terminal
