### ISSUE TITLE
AnyCode does not work in github.dev

### ISSUE THREAD

**Issue by jmarolf** [microsoft/vscode#142879] opened 2022-02-11 21:05 UTC
AnyCode does not work in github.dev

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4863.0 Safari/537.36 Edg/100.0.1163.0
Embedder: github.dev

Message: Request initialize failed with message: WebAssembly is not defined

**Comment by jrieken** [comment] 2022-02-21 09:54
/duplicate of https://github.com/microsoft/vscode-anycode/issues/22

**Closed** 2022-02-21 09:54 UTC
