### ISSUE TITLE
<enter> in an empty debug console produces 'undefined'

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11350] opened 2016-08-31 23:00 UTC
Start a Node debug session and press enter when the repl is empty - it should only try to eval when there's text to eval.

**Comment by isidorn** [comment] 2016-09-01 05:59
This was actually requested by @daviwil here https://github.com/Microsoft/vscode/issues/5773
Since some debug scenarios require this empty string to be evaluated I would prefer to leave like it is, since it does not have any big impact on node imho. Thus closing as designed. 

Can reopen if you provide good arguments why should this trump the powershell case

**Closed by isidorn** 2016-09-01 05:59 UTC
Labels: bug, debug
