### ISSUE TITLE
suggest details have no scrollbar

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2277] opened 2016-01-26 10:03 UTC
![screen shot 2016-01-26 at 11 03 52](https://cloud.githubusercontent.com/assets/1794099/12577709/842de4b0-c41c-11e5-819e-c1415cde7247.png)

**Comment by joaomoreno** [comment] 2016-01-26 10:15
Duplicate of #1928

**Closed by joaomoreno** 2016-01-26 10:15 UTC
