### ISSUE TITLE
Safari: Change popup blocker workaround to use a real link to open normaly

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#166257] opened 2022-11-14 08:19 UTC
`Cmd` + `Click` on a link in a markdown file opens new window in Safari. When I `Cmd` + `Click` a link on a webpage, it opens in a new tab. Can we align with that? (I guess this is `env.openExternal()`'s behavior.)

Version: 1.74.0-insider
Commit: ef415578d1b1019db585718968a303eeca4b8979
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Embedder: github.dev

**Comment by jrieken** [comment] 2022-12-06 13:43
@chrmarti Do you mean clicking inside markdown preview?

**Comment by chrmarti** [comment] 2022-12-09 09:06
Clicking in the markdown source and the preview both open a new window.
<img width="805" alt="image" src="https://user-images.githubusercontent.com/9205389/206665446-26d16509-2cc0-4f56-b631-940d37a33ff4.png">

**Comment by jrieken** [comment] 2022-12-09 11:24
So, this actually works when having pop-ups allowed (via Safari > Website settings) but not from the dialog. I believe the embedder is showing this message and doing the actual open. Assigning to @bpasero but I am actually unsure who owns this

**Comment by bpasero** [comment] 2022-12-09 15:19
To prevent popup blockers from blocking open requests, we [inform the user and offer](https://github.com/microsoft/vscode/blob/7aee64835fb7aeef89770bfd3cafdaeab4e37c12/src/vs/workbench/browser/window.ts#L184) a "Open" button to try again. We then just call this method:

https://github.com/microsoft/vscode/blob/7aee64835fb7aeef89770bfd3cafdaeab4e37c12/src/vs/base/browser/dom.ts#L1136

I can see how changing it to `window.open(url, '_blank')` opens a tab, but I am not sure the consequences. I believe Alex introduced it and we are all using it in a few places so I am not convinced we should change it here and behave different than the other locations.

**Comment by alexdima** [comment] 2022-12-11 11:40
The problem is that when using `window.open`, the opened page will have access to the opener page via `window.opener`. The opened page can then mess with the opener page and redirect it to a malicious / phishing page. When you return to the opener page, you might fall for a phishing attack because you might think the page is trusted. This used to be a much bigger problem because all pages opened directly by users via `<a target="_blank">` would be susceptible to this attack. But that has been recently addressed with [browsers changing their defaults for <a> elements](You can read more about it [here](https://mathiasbynens.github.io/rel-noopener/).).

But the problem remains for `window.open`, the opened page has access by default to the opener page. The suggested solution is to use the [`noopener` argument in the `windowFeatures` parameter](https://developer.mozilla.org/en-US/docs/Web/API/Window/open). According to MDN, using `noopener` should not be treated as a popup request:

> <img width="736" alt="image" src="https://user-images.githubusercontent.com/5047891/206900931-ec48f543-12b1-4481-add7-140960f77629.png">

It seems that Safari decides to treat such a call as a popup request and, once allowed, will open a new window. IMHO this is a Safari bug. Not sure what's the best way to open an issue against Safari nowadays cc @digitarald .

@bpasero I can't think of any other JS workaround. Maybe one idea would be to create an invisible `<a>` element that aligns perfectly on top of the dialog "Open" button (or change the "Open" button to be an `<a>` element) and then users end up clicking that `<a>` natively and no JS is involved. It looks like Safari will open `<a href="..." target="_blank">` correctly by default in a new tab without an opener.

**Comment by bpasero** [comment] 2022-12-12 07:30
@alexdima super nice analysis and I think as such worthy to keep open as issue, even though the change will be ugly: `Dialog` is a very generic component and `Button` is a part of it with well established accessibility rules and API, so the `link` workaround is ugly, but necessary in this case, I agree. On top of that, we seem to have logic to sometimes call into `windowOpenPopup` if we trust the link?

An alternative would be to somehow embed the link in the text of the dialog, but it looks like we do not allow that (tried with Markdown syntax).

**Comment by alexdima** [comment] 2022-12-12 13:17
https://github.com/microsoft/vscode/pull/136383 introduced `windowOpenPopup`, it looks like it has something to do with the auth flow, so I assume only trusted links should be opened using that.

**Comment by bpasero** [comment] 2024-12-20 08:04
No plans to change this, closing.

**Closed by bpasero** 2024-12-20 08:04 UTC
Labels: feature-request, dialogs, web, safari
