### ISSUE TITLE
Language: Javascript vs Language: Javascript React breaks context menu

### ISSUE THREAD

**Issue by DelvarWorld** [Microsoft/vscode#2055] opened 2016-01-16 01:09 UTC
Context menu with Javascript:

![screen shot 2016-01-15 at 5 09 27 pm](https://cloud.githubusercontent.com/assets/79215/12369371/bf56a236-bbaa-11e5-81fb-0f3e51b3981b.png)

Context menu with Javascript React:

![screen shot 2016-01-15 at 5 08 56 pm](https://cloud.githubusercontent.com/assets/79215/12369366/b1f47d0c-bbaa-11e5-90c9-bea1a2957660.png)

**Comment by jrieken** [comment] 2016-01-18 10:41
duplicate of #140

**Closed by jrieken** 2016-01-18 10:41 UTC
Labels: js
