### ISSUE TITLE
Editor cursor positioning mess-up after zooming out on linux

### ISSUE THREAD

**Issue by webarchymeta** [Microsoft/vscode#26414] opened 2017-05-10 21:14 UTC
- VSCode Version: 1.12.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. Click View/Zoom Out once (from 100% zooming level).
2. Double click a word in a document or type in a character.

The selected region is not the word one tried to select. Or the character is not at the position of the cursor.

**Comment by alexandrudima** [comment] 2017-05-11 06:49
Duplicate of #26151 

Workarounds until the fix is released:
* change the zoom level, then **close and start again** VS Code
* or use the setting `"editor.disableMonospaceOptimizations": true`

**Closed by alexandrudima** 2017-05-11 06:49 UTC
