### ISSUE TITLE
Ctrl+V to paste sometimes deletes text

### ISSUE THREAD

**Issue by sjc-gh** [microsoft/vscode#146541] opened 2022-04-01 12:39 UTC
Pasting copied text over selected target text actually deletes the text instead.  This only seems to happen if the line containing the selected target text is using Typescript string interpolation.

For example, suppose I have the following function in a .ts file:

```
  function reportBug(): void {
    console.log(`${Date.now()} [MyClass.someFunction] - Some source text to copy.`);
    console.log(`${Date.now()} [MyClass.someFunction] - Some destination for copied text.`);
  }
```

If I select and copy the text "Some source text to copy.", select the text "Some destination for copied text.", then hit Ctrl+V to paste, I expect:

```
  function reportBug(): void {
    console.log(`${Date.now()} [MyClass.someFunction] - Some source text to copy.`);
    console.log(`${Date.now()} [MyClass.someFunction] - Some source text to copy.`);
  }
```

But instead I get:

```
  function reportBug(): void {
    console.log(`${Date.now()} [MyClass.someFunction] - Some source text to copy.`);
    console.log(`${Date.now());
  }
```

If I hit hit Ctrl+Z after the paste, it seems to undo some deletion and show what I pasted.

If however my original function did not include the interpolation placeholder:

```
  function reportBug(): void {
    console.log(`[MyClass.someFunction] - Some source text to copy.`);
    console.log(`[MyClass.someFunction] - Some destination for copied text.`);
  }
```

Then the paste works as expected.

VS Code info:

> Version: 1.65.2 (system setup)
> Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
> Date: 2022-03-10T14:33:55.248Z
> Electron: 13.5.2
> Chromium: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19042

\- Steve

**Comment by tanhakabir** [comment] 2022-04-01 16:26
Thanks! Would mind sharing a gif or video of what you see?

**Comment by sjc-gh** [comment] 2022-04-01 16:54
Hello -

Sure, see the attached short clip.  In it I select the text "Some source text to copy." in line 4 and hit Ctrl+C to copy.  Then I select the text "Some destination for copied text." in line 5 and hit Ctrl+V to paste.  Instead of replacing the selected text with the copied text, it appears to actually delete all the text up to and including the closing curly brace for the interpolation placeholder.  If I hit Ctrl+Z to 'undo', then line 5 does match line 4 as I would expect.  It seems two operations are happening and stored in the undo stack - the paste (which works correctly), then an unexpected trim of the string.

Let me know if you need any more information!

https://user-images.githubusercontent.com/102807231/161307508-58b1f835-ba5f-4ec2-967e-a6c42c284abe.mp4

**Comment by jonasska** [comment] 2022-04-06 12:13
Hi, 
I also have been affected by this issue when working on **TypeScript** projects. 

Version: 1.66.0 (system setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.18363

All other extensions were disabled.
![pasteParameter](https://user-images.githubusercontent.com/42681582/161971902-1274e25c-d6c8-40ab-8cc8-cfb9581d8a01.gif)
![pasteText](https://user-images.githubusercontent.com/42681582/161972016-f19d1e23-051a-420b-865b-de0474b85518.gif)

**Comment by jdunham2** [comment] 2022-04-18 19:35
Hello! Thanks for your help with this. Just wanted to add the issue persists with vscode on mac

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z (1 wk ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.3.0

I have the same behavior as **jonasska**  where undo brings the pasted content back.

**Comment by yume-chan** [comment] 2022-04-21 16:41
Duplicate of Microsoft/TypeScript#48006

**Closed** 2022-04-21 16:54 UTC
Labels: *duplicate
