### ISSUE TITLE
Bad ui font rendering in linux

### ISSUE THREAD

**Issue by jcbritobr** [microsoft/vscode#191428] opened 2023-08-28 02:14 UTC
Please, enhance font-weight for ui in linux. In editor I can fix it, but in UI is not possible.
If there is a workaround, please type below.

![image](https://github.com/microsoft/vscode/assets/6579862/070b5466-bf6f-45f3-ab0e-d2efb3266aa9)

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.11-200.fc38.x86_64

**Comment by bpasero** [comment] 2023-08-28 14:10
I think this would be a duplicate of https://github.com/microsoft/vscode/issues/519. You can change the font for the editor though.

**Closed** 2023-08-28 14:13 UTC
Labels: info-needed
