### ISSUE TITLE
Terminal rendering with a fixed size

### ISSUE THREAD

**Issue by median-dxz** [microsoft/vscode#163997] opened 2022-10-19 08:17 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
版本: 1.73.0-insider (user setup)
提交: 7ea2788a43a4c35d8da63a419725ba2485de395b
日期: 2022-10-19T05:28:16.879Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
沙盒化: Yes

- OS Version: 
版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎10/‎27
操作系统版本	22000.1098
体验	Windows 功能体验包 1000.22000.1098.0

It looks like the terminal renders at a fixed size rather than fitting the viewport.

I have tried to restart VSCode, restart Windows and disable all the extensions, but all of that doesn't fix it.

If there is any further information needed, pls let me know.

Steps to Reproduce:

Just open the terminal:

![image](https://user-images.githubusercontent.com/33348142/196632176-c18c03ad-e5d1-4d77-ba7c-6635896d12ba.png)

What can we get from the capture above is that all the canvas element were set to [640*480]. And I recently have used the a dual screen in two monitor, maybe it have any relationship with this problem?

**Comment by yume-chan** [comment] 2022-10-19 10:37
Duplicate of #163991

**Comment by meganrogge** [comment] 2022-10-19 15:20
already fixed with https://github.com/microsoft/vscode/commit/d105e09d00411a18c99b09be2359487e898f157b

which you'll see in insider's tomorrow

**Closed by meganrogge** 2022-10-19 15:20 UTC
