### ISSUE TITLE
intellisense  not working for ReactJS

### ISSUE THREAD

**Issue by Yogeshraj** [microsoft/vscode#89804] opened 2020-01-31 17:47 UTC
Issue Type: <b>Bug</b>

intellisense not working for reactjs alone, but working fine for react native.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.10240

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.0
flutter|Dar|3.8.0
es7-react-js-snippets|dsz|2.5.0
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|32.4.0
vsc-material-theme-icons|equ|1.1.3
graphql-for-vscode|kum|1.15.3
python|ms-|2020.1.58038
vscode-react-native|msj|0.14.0
LiveServer|rit|5.6.1
vscode-icons|vsc|9.7.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.4.0
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-01-31 19:04
/needsMoreInfo

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Yogeshraj** [comment] 2020-02-01 06:11
![1](https://user-images.githubusercontent.com/6562779/73587908-9966b280-44e7-11ea-8c69-2c40dbaa2d53.png)

i even tried after removing all extensions. no suggestions from intellisense for JS

**Comment by Yogeshraj** [comment] 2020-02-04 06:23
@mjbvz any update on this?

**Comment by mjbvz** [comment] 2020-02-12 22:00
Thanks for testing. I'm closing this since it works in insiders. The current VS Code insiders builds includes a new TS version (3.8) which fixes issues that could be causing issues like this

Until VS Code 1.43 is released, you can upgrade VS Code to to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2020-02-12 22:00 UTC
Labels: needs more info
