### ISSUE TITLE
Vscode insider background color bug

### ISSUE THREAD

**Issue by nicmr** [Microsoft/vscode#52099] opened 2018-06-16 09:45 UTC
Issue Type: <b>Bug</b>

1. Download latest code-insiders update
  * the issue didn't occur before updating, not sure which version I had before though
2. Open any source file
3. The background will be split in a part with the correct color and a darker shade
4. Clicking on a line will highlight the background around it / change the shade of grey
![A screen cast illustrating the issue](https://media.giphy.com/media/8YQeOQXGQYCVPdht2r/giphy.gif)

Expected behaviour: background should have the same color at all times. I believe the brighter shade is the correct color.

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:18:22.133Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor (12 x 1287)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.68GB (11.04GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
theme-monokai-pro-vscode|mon|1.1.8

</details>

Launched with `code --disable-extensions` to check.
Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-06-16 17:07
Duplicate of https://github.com/Microsoft/vscode/issues/48043

**Closed by bpasero** 2018-06-16 17:07 UTC
Labels: electron-update
