### ISSUE TITLE
Message on console when manually editing url in links, withing html file

### ISSUE THREAD

**Issue by RobertoMD** [Microsoft/vscode#15713] opened 2016-11-18 09:12 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.7.2|

---

Steps to Reproduce:

1. Open any html file that includes links
2. Edit the href value of an existing link and delete some random characters of the url. The output console shows this message for the category "HTML Language Server" 

![2016-11-18 10_06_09- index html - visual studio code](https://cloud.githubusercontent.com/assets/7143188/20424609/0f7c8208-ad77-11e6-9410-1a6e404639c9.png)

**Comment by aeschli** [comment] 2016-11-20 20:04
duplicate of #15018

**Closed by aeschli** 2016-11-20 20:04 UTC
