### ISSUE TITLE
disabled extension causes overridding extension to not load (even after uninstall)

### ISSUE THREAD

**Issue by martinlippert** [Microsoft/vscode#25702] opened 2017-04-30 16:10 UTC
- VSCode Version: 1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e

- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. install extension via vsix file
2. disable the extension (set to disabled - always from the extension UI)
3. open the extension project in workspace
4. press F5 to launch runtime instance with extension from workspace

=> the extension from the workspace is not enabled, because the installed version of the extension is disabled.

This should not be the case from my point of view. The launched extension should always be enabled.

This gets worse if you uninstall the extension (via the extension UI) while it is disabled. After uninstallting and reloading the window (or restarting code completely), the behavior stays the same. The extension in the runtime instance is disabled and there is no way to re-enable it (since there is no entry for it showing up in the extension UI).

The only solution here is to re-install the extension from a vsix file (it is still disabled after this), enable it again, then uninstall it again.

**Comment by sandy081** [comment] 2017-11-22 10:40
Duplicate of #26734

**Comment by sandy081** [comment] 2017-11-24 12:25
This is not a duplicate of #26734 but similar and shows a different scenario. Hence removing dup.

**Closed** 2017-11-24 12:27 UTC
Labels: bug, extensions

**Comment by sandy081** [comment] 2017-11-24 12:28
Yes, developed extensions should have priority and not considered to be disabled during development.
