### ISSUE TITLE
Notebook cell selection color changes when mouseup occurs outside the editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115127] opened 2021-01-26 19:20 UTC
Testing #114969

Not sure why this would happen, maybe monaco doesn't think it's focused?

![recording (48)](https://user-images.githubusercontent.com/2193314/105893769-57702f80-5fc8-11eb-9729-4ad61fc145c2.gif)

**Comment by rebornix** [comment] 2021-02-05 03:39
Weird, it's very likely the textarea is not focused

**Comment by rebornix** [comment] 2021-08-05 02:57
We have fixes for the cell focus recently and I'm not able to reproduce this in latest Insiders. Closing for now.

**Closed by rebornix** 2021-08-05 02:57 UTC
Labels: bug, notebook
