### ISSUE TITLE
Perl: broken syntax highlighting in certain regexp expressions

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#96024] opened 2020-04-24 02:15 UTC
- VSCode Version: 1.44.2
- OS Version: Arch Linux - visual-studio-code-bin (Microsoft binary)

Steps to Reproduce:

1. `$val =~ y{/+}{_-};`
2. ![image](https://user-images.githubusercontent.com/611746/80167883-22e9c600-85a7-11ea-84da-ddccfd41cad8.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by alexr00** [comment] 2020-04-27 09:23
Duplicate of https://github.com/textmate/perl.tmbundle/issues/33

**Closed by alexr00** 2020-04-27 09:23 UTC
