### ISSUE TITLE
希望看到用户同步功能

### ISSUE THREAD

**Issue by ruixinMRK** [Microsoft/vscode#38276] opened 2017-11-14 03:25 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

.因为我会在不同的电脑使用vscode，所以我希望可以增加一个用户登录功能，可以把同一个账号中配置和插件同步起来。就不用我每次都去挨个增加插件

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
vscode-eslint|dba|1.4.3
vscode-jasmine-es5|dee|1.0.1
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
vscode-postcss-sorting|mrm|3.0.1
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
better-less|rad|0.4.3
vscode-icons|rob|7.17.0
stylelint|shi|0.30.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

Reproduces without extensions: Yes/No

**Comment by brunnerh** [comment] 2017-11-14 03:58
I would recommend the extension [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync), which synchronizes both settings and installed extensions.

**Comment by mjbvz** [comment] 2017-11-14 16:51
Duplicate of #2743

Try using the Settings sync extension @brunnerh linked to

**Closed by mjbvz** 2017-11-14 16:51 UTC
Labels: duplicate, new release
