### ISSUE TITLE
iPad OS trackpad scroll / mouse wheel support 

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#106232] opened 2020-09-07 12:50 UTC
pls see https://github.community/t/ipados-trackpad-doesn-t-scroll/130414

**Comment by rebornix** [comment] 2020-09-14 21:26
It's a bug in webkit which doesn't sent out the right events when scrolling on the trackpad https://bugs.webkit.org/show_bug.cgi?id=210071

**Comment by VincentDondain** [comment] 2020-09-28 19:58
@rebornix could you update the issue's title to capture that it's not only impacting trackpad support but also mouse wheel? I do not have the permissions to do that (: 

Also, it is my understanding this is the main issue tracking this work (we're also tracking it on the Codespaces side).

**Comment by rebornix** [comment] 2020-09-30 23:43
@VincentDondain thanks, I updated the title.

**Comment by VincentDondain** [comment] 2020-10-23 15:28
Comment from Apple on 2020-10-21 (hopefully fix soon).

> Also, do know that while I can't comment on the timing of fixes, I am absolutely aware of this and know that it is important.

**Comment by VincentDondain** [comment] 2021-02-19 18:13
Hey @rebornix, it looks like the WebKit issue is now fixed: https://bugs.webkit.org/show_bug.cgi?id=210071#c34

However, I just tried on iPadOS 14.5 beta 2 and the scrolling on iPad still doesn't work. So either the fix isn't yet in iPadOS or we need some changes in VSCode.

**Comment by huw** [comment] 2021-02-19 23:45
As in [cdr/code-server#1455](https://github.com/cdr/code-server/issues/1455), you either need to scroll a little bit to hide the URL bar, or to add your Codespace to your home screen.

**Comment by isidorn** [comment] 2021-04-09 16:26
I have commented on the webkit issue so we get clarity on when should this get fixed https://bugs.webkit.org/show_bug.cgi?id=210071

Also the scrolling is butter smooth with the latest update, so that improved. But the external mouse scroll still does not work.

**Comment by isidorn** [comment] 2021-04-13 14:58
I have updated to latest iPadOS 14.5 beta 7 and I can verify that the issue is indeed fixed. However there are still two minor issues:
* Mouse wheel scroll works in the editor only when the editor is focused
* Mouse wheel scroll does not work outside of the editor. For example in the list

@rebornix might there be some custom editor code that is handling this which we need in more places? Might this code depend on the editor having focus?

**Comment by Dids** [comment] 2021-04-13 15:05
@isidorn Curious if you've tried it in Safari with the address bar hidden, or as a PWA (Share -> Add to Home)?

So far this has been the only way I've personally been able to get scrolling working on iPadOS 14.5, even in the list view.

**Comment by isidorn** [comment] 2021-04-13 15:16
@dids thanks for tip, yes hiding the address bar would allow to scroll both the list view and the editor.

**Comment by joaomoreno** [comment] 2021-06-01 14:29
> * Mouse wheel scroll does not work outside of the editor. For example in the list

In 14.5 it seems to work, but only if the focus is outside the list. 🤷

**Comment by fuchanglin** [comment] 2021-07-15 10:17
iPadOS 15 beta 3.
Trackpad scroll works only when is address bar is hidden and the screen size >= 3/4 landscape, when the split size is half and half or less, even with the hidden address bar the scroll is not working.

**Comment by maciej** [comment] 2021-09-26 01:26
Observation:
On my 3rd gen 11’ iPad Pro with Magic Keyboard running iPadOS 15 the issue manifests itself only when keyboard “Shortcuts” are disabled. When the setting is enabled I did not see the issue (so far during limited testing).

Setting:
![Screenshot 2021-09-26 at 03 25 02](https://user-images.githubusercontent.com/9706/134790035-196a2df5-17fd-4e06-9ade-3ae3262b363f.png)

**Comment by vavdoshka** [comment] 2021-10-01 22:28
> Observation: On my 3rd gen 11’ iPad Pro with Magic Keyboard running iPadOS 15 the issue manifests itself only when keyboard “Shortcuts” are disabled. When the setting is enabled I did not see the issue (so far during limited testing).
> 
> Setting: ![Screenshot 2021-09-26 at 03 25 02](https://user-images.githubusercontent.com/9706/134790035-196a2df5-17fd-4e06-9ade-3ae3262b363f.png)

same here, 12.9 5th gen, Safari - when "Shortcuts" enabled I have this annoying keyboard "helper" in the bottom of the screen but scroll does work. This helper causes vscode to shrink.
When "Shortcuts" disabled the scroll from touch bar / mouse just does not work.

In chrome scroll works with both enabled/disabled "Shortcuts" but there is a huge grey space filler at the bottom causing the vscode to shrink a little, and chrome has relevatively big address/tab bar comparing to safari also which makes the experience slightly worse.

**Comment by vavdoshka** [comment] 2021-10-09 11:54
however the scroll does work when when vscode is working as shortcut app (Home Screen).
To do so open the vscode in browser -> "add to Home Screen".

**Comment by burkeholland** [comment] 2021-11-30 19:49
IPad 12.9 fifth generation
iPad OS15.1

Scrolling in the file explorer works but only if the focus is not on the sidebar. Changing the Safari tab layout has no effect and neither does adding the keyboard shortcuts.

**Comment by taiya** [comment] 2022-01-03 20:26
Problem persists on iPadOS 15.0.2, e.g. scrolling pubs.json is broken (even when in focus):
https://github1s.com/taiya/taiya.github.io/blob/HEAD/pubs.json

I am going to try the PWA solution mentioned above.

**Comment by fuchanglin** [comment] 2022-07-07 23:50
The scrolling (by Magic keyboard's trackpad) failed in both PWA and normal mode on iPadOS 16 beta 3, make it hard to use now.

**Comment by lplassman** [comment] 2022-08-06 01:41
This issue still exists on iPadOS 16 beta 4.

**Comment by bartlettpsj** [comment] 2022-09-14 04:12
Interestingly Gitpod works fine.

**Comment by DAmisonSSG** [comment] 2022-09-30 17:25
On iOS 16 I have found that if you enable the shortcuts in the keyboard setting it does work

However this gives the white bar at the bottom.

If you go back to the keyboard setting and disable the hortcuts the white bar will go away and scroll will still work

Main downside you have to do this eveytime you open the app

This was accessing vscode in a pwa homescreen shortcut

**Comment by hzcheng** [comment] 2023-01-29 10:16
Try this: https://github.com/microsoft/vscode/issues/164220#issuecomment-1407241276

**Comment by hediet** [comment] 2023-02-20 17:05
I can verify:
* onwheel does not work (neither for the editor nor for lists, unless some editor is focused)
* this code sample does not work (https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onwheel_addeventlistener)
* when pinning vscode.dev as PWA, onwheel does work

=> This is clearly an upstream issue.

**Comment by huw** [comment] 2023-02-21 00:19
This has been completely fixed for me in iPadOS 16.4 Beta 1, including with Shortcuts off. I would move to close once 16.4 releases and someone else can verify.

**Comment by vinerz** [comment] 2023-03-13 21:07
Just updated to iPadOS 16.4 Beta 3 and I can also confirm that it is working @huw, but now I've got a double cursor (the iPadOS and the VSCode one on top of each other). The scrolling is fully functional in CodeSpaces and code-server, might as well be fixed in VSCode Remote Tunnels.

If I give the editor panel focus by clicking on it, I can only see the VSCode cursor.
Once I scroll, the native cursor appears and doesn't go away until it loses focus.

It works nonetheless! Awesome to see it finally working on my iPad after struggling for so long.

**Comment by hediet** [comment] 2023-03-14 13:44
I also upgraded my iPad to iPadOS 16.4 Beta 3 and can confirm as well that the trackpad can now be used to scroll lists and text.

> but now I've got a double cursor (the iPadOS and the VSCode one on top of each other)

I don't see this though, can you share a screenshot?

**Comment by vinerz** [comment] 2023-03-14 17:38
@hediet sure! Here goes a screen capture:

https://user-images.githubusercontent.com/1482034/225091030-352c6b59-94a5-4097-8eaa-e1b4222cd483.mov

**Comment by hediet** [comment] 2023-03-15 11:45
Isn't this the expected behavior?

**Comment by TylerLeonhardt** [comment] 2024-12-17 03:03
This issue (the trackpad scrolling) appears to be fixed - tested on 18.2. Closing this issue and leaving #177277 for the double cursor issue.

**Closed by TylerLeonhardt** 2024-12-17 03:03 UTC
Labels: upstream, web, upstream-issue-linked, ios-ipados
