### ISSUE TITLE
When in preview mode of a Markdown file, keep preview mode when browsing to a link (local at least)

### ISSUE THREAD

**Issue by danuw** [Microsoft/vscode#20819] opened 2017-02-17 16:40 UTC
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. In the explorer, open a Readme.md file
2. When file opens, click the preview
3. When markdown is rendered in HTML format, click a link that opens a new .md file

Expected:
-> we are "navigated" to the preview version of the MD file

Actual:
-> the file is opened in edit mode - text is markdown notation

**Comment by mjbvz** [comment] 2017-02-17 19:54
Duplicate of #19339

**Closed by mjbvz** 2017-02-17 19:54 UTC
Labels: duplicate, markdown
