### ISSUE TITLE
Signature help does not underline the parameter name properly

### ISSUE THREAD

**Issue by qutreson** [Microsoft/vscode#40080] opened 2017-12-12 09:30 UTC
VSCode Version: 1.18.1 & 1.19.0-insider
OS Version: Win10

Steps to Reproduce:

1. See discussion below

Reproduces without extensions: Yes

**Bug description:**

I found out an issue related to the underlining of the name parameter in the signature help when the name is a substring of the parameter type.

In our AL extension, we declare methods as follows:
```
    procedure MyMethod(MyParameterName : MyParameterType);
    begin
          // my code logic goes here
    end;
```
What we send back from our extension to VS Code to generate the signature help is the whole signature and the names of the parameters of the method without any style formatting.

When it works correctly, we have something like below where the name is properly underlined:
![image](https://user-images.githubusercontent.com/31541422/33876263-4db1ea82-df25-11e7-8085-e7c434c155a4.png)

However, if the parameter name is a substring of the parameter type, then the signature help underlines this substring in the parameter type instead of the name.
![image](https://user-images.githubusercontent.com/31541422/33876381-a3f72470-df25-11e7-800c-0d2c925b15f7.png)

**Actual**: Part of the parameter type is underlined when the parameter name is a substring of the parameter type.
**Expected**: The parameter name is underlined correctly also when the parameter name is a substring of the parameter type.

Thanks,

Quentin

**Comment by jrieken** [comment] 2017-12-13 08:40
dupe of #18782

**Closed by jrieken** 2017-12-13 08:40 UTC
Labels: insiders
