### ISSUE TITLE
--max-memory does not work - as expected

### ISSUE THREAD

**Issue by obiwanjacobi** [Microsoft/vscode#69638] opened 2019-03-01 07:21 UTC
Done.

Not Done - No Time.

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
16 GB memory installed

Steps to Reproduce:

1. Open a really large file. I tried to open a 1.6 GB xml (don't ask ;-).
2. VS-code reports it need more memory (excellent - nothing wrong with this). 
3. Click restart with 4096MB. 
  - nothing happens. I would expect it would restart with the new setting.
4. Start code again and retry 1 get 2 again. Now configure settings. Ok so it says it is set to 4096 MB.
  - close window and retry loading (1) -> get 2 again.
5. Goto command prompt, (navigate to folder that contains file.)
6. code --max-memory 4096
7. open file => get 2 again.

Does this issue occur when all extensions are disabled?: Yes/No
Not Done - No Time - would not expect extensions to have a say in this...?

**Comment by usernamehw** [comment] 2019-03-01 08:24
Possible duplicate of #68279

**Comment by rebornix** [comment] 2019-03-01 23:16
It's fixed in Insiders and will be released next week in 1.32

**Closed** 2019-03-01 23:16 UTC
Labels: *duplicate
