### ISSUE TITLE
TypeScript Import Suggestion Doesn't work anymore

### ISSUE THREAD

**Issue by MrDesjardins** [Microsoft/vscode#47092] opened 2018-04-02 17:09 UTC
Issue Type: <b>Bug</b>

In a TypeScript project, when I am typing a new type, it usually suggests me to import the missing import. However, since the update of vscode-insider I do not have any suggestion. I have to manually add the import.

VS Code version: Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:10:29.002Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4396081|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
vscode-wakatime|Wak|1.1.26
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
gitlens|eam|8.2.0
tslint|eg2|1.0.28
vscode-codemetrics|kis|1.14.0
python|ms-|2018.3.1
vscode-subword-navigation|ow|1.2.0
java|red|0.21.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.6.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-04-02 19:00
Do you mean the quick fix lightbulb that adds the import, or auto imports that get added when you accept a completion?

**Comment by MrDesjardins** [comment] 2018-04-02 20:13
There is no lightbulb to add the import.

**Comment by mjbvz** [comment] 2018-04-02 20:35
Duplicate of #47002. Should be fixed in the next insiders build

**Closed by mjbvz** 2018-04-02 20:35 UTC
Labels: insiders, needs more info
