### ISSUE TITLE
Extension Host terminated unexpectedly

### ISSUE THREAD

**Issue by danofsatx** [Microsoft/vscode#59983] opened 2018-10-04 16:50 UTC
[ExtensionHost-1538671642891.log](https://github.com/Microsoft/vscode/files/2447284/ExtensionHost-1538671642891.log)
Issue Type: <b>Bug</b>

Extension host is crashing every time the window is brought into focus.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_114716|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
puppet-vscode|jpo|0.12.0

</details>

**Comment by Tyriar** [comment] 2018-10-04 17:02
Try closing all windows and launching with `code --disable-extensions`, this is typically related to problems with specific extensions.

**Comment by carlocardella** [comment] 2018-10-09 16:32
My Extension Host was crashing due on an out of memory exception (console log attached), since I was seeing some other weird behaviors with other extensions I have deleted my local extension folder (C:\Users\carlo\\.vscode) and restored my config using shan.code-settings-sync, and the crash seems to be gone

[-1539099125320.log](https://github.com/Microsoft/vscode/files/2461317/-1539099125320.log)

**Comment by joaomoreno** [comment] 2018-10-10 07:06
Good to know that the crash is gone.

cc @alexandrudima @bpasero

**Closed by joaomoreno** 2018-10-10 07:06 UTC
Labels: extension-host, needs more info

**Comment by carlocardella** [comment] 2018-10-10 13:06
I did not open the issue, I was merely offering a solution that worked for me in a similar scenario, maybe @danofsatx should confirm the problem is solved before closing this?
