### ISSUE TITLE
"Restart (Ctrl + Shift + F5)" Button Does Not Work

### ISSUE THREAD

**Issue by edujr1** [microsoft/vscode#85386] opened 2019-11-22 13:51 UTC
Issue Type: <b>Bug</b>

Clicking the restart button ends the project instead of restarting

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
numbered-bookmarks|ale|6.2.1
bracket-pair-colorizer|Coe|1.0.61
mustache|daw|1.1.1
wpy-beautify|doi|2.0.10
gitlens|eam|10.2.0
vue-snippets|hol|0.1.11
vscode-peacock|joh|3.2.0
chat|kar|0.29.0
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.16.1
vscode-docker|ms-|0.8.2
vscode-language-pack-pt-BR|MS-|1.40.2
mssql|ms-|1.7.1
azure-account|ms-|0.8.7
vsliveshare|ms-|1.0.1293
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.1
WebTemplateStudio-dev-nightly|WAS|0.0.1929801
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment] 2019-11-22 14:41
@edujr1 what debugger extension are you using?

**Comment by edujr1** [comment] 2019-11-22 14:42
I use the native Nodejs debugger

**Comment by pucumt** [comment] 2019-11-27 05:14
> @edujr1 what debugger extension are you using?

I have the same issue, even if I disabled all the extensions.

**Comment by pucumt** [comment] 2019-11-27 05:15
After update to 1.40.2, still the same issue.

**Comment by isidorn** [comment] 2019-11-27 10:21
This works just fine for me
![restart](https://user-images.githubusercontent.com/1926584/69715071-e608c880-1107-11ea-8748-cf0717e66f35.gif)


1. What are you doing differently than me
2. Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
3. If yes, can you share your repository for which you can always reproduce this

**Comment by pucumt** [comment] 2019-11-28 02:29
![vscode](https://user-images.githubusercontent.com/11862714/69772059-d5208b80-11c9-11ea-990b-624f0dbabdef.gif)

Still not work.
Even the code so simple!

**Comment by isidorn** [comment] 2019-11-28 09:28
There might be something with the nodeJs debugger (which I can not reproduce), assigning to @roblourens and @connor4312 to investigate further.

**Comment by weinand** [comment] 2019-11-28 11:06
@pucumt how does your launch configuration (launch.json) look like?

**Comment by pucumt** [comment] 2019-11-29 02:32
` "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\app.js"
        }
    ]`
It is 100 percent fail yesterday. But it is work sometimes today.
If you cannot reproduce it, it might be really my personal issue.

I will check more of my local enviroment.
Thank you very much!

**Comment by pucumt** [comment] 2019-11-29 02:36
Another configuration with 'cwd'
```
{
    // Use IntelliSense to find out which attributes exist for node debugging
    // Use hover for the description of the existing attributes
    // For further information visit https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}\\app.js",
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "port": 9229
        }
    ]
}
```

**Comment by pucumt** [comment] 2019-11-29 03:10
I have removed  some extionsions, and it indeed work. I am not sure which extension to make it fail,  but I removed flutter/dart extension and all markdown extension.

Thank you very much!

**Comment by weinand** [comment] 2019-11-29 09:00
@pucunt I suggest that you enable extensions one-by-one to find the extension that causes the problem. If successful please file an issue against the faulty extension.

**Comment by weinand** [comment] 2019-11-29 09:01
@edujr1 are you able to reproduce the problem after disabling all extensions?

**Comment by andrhevictor** [comment] 2019-11-29 14:37
In my case, I have to double click the "Restart" button to restart debugging. Is this the expected behavior?

Sorry to ask this here, I didn't want to register another issue for a simple question.

**Comment by weinand** [comment] 2019-11-29 19:23
@andrhevictor do you mean "double click" or "clicking twice"?

**Comment by andrhevictor** [comment] 2019-11-29 19:27
> @andrhevictor do you mean "double click" or "clicking twice"?

Sorry, clicking twice.

**Comment by weinand** [comment] 2019-11-29 20:18
@andrhevictor which debugger are you using?

**Comment by andrhevictor** [comment] 2019-11-29 21:39
> @andrhevictor which debugger are you using?

harbour-dbg.

The `launch.json` is the following:
```json
{
  "version": "0.2.0",
  "configurations": [
      {
          "type": "harbour-dbg",
          "request": "launch",
          "name": "Launch",
          "program": "${workspaceFolder}\\Executable",
          "stopOnEntry": false,
          "terminalType": "none",   
          "preLaunchTask": "Compile",   
          "postDebugTask": "",
          "workingDir": "${workspaceFolder}\\",
          "sourcePaths": [
              "${workspaceFolder}\\"
          ]
      }
  ]
}
```

**Comment by weinand** [comment] 2019-11-29 22:08
@andrhevictor please file this question/issue against harbour-dbg. Only they know how "restart" should behave.

**Comment by pucumt** [comment] 2019-12-01 05:30
I don't know which extension it is, but only disable the extension is not enough, must uninstall it. (actually I don't remember all the extensions that uninstalled by me)

**Comment by comjun04** [comment] 2019-12-07 07:31
I also get into this problem.
Disabling extensions **Not Working**
Uninstalling ALL extensions **Not Working**
Update `node.js` from `v10.16.0` to `v12.13.1`(latest LTS) **also Not Working**

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (4.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by elahmo** [comment] 2019-12-07 15:15
I have the same issue.

This is the output from the log:

```[2019-12-07 16:14:31.204] [renderer1] [error] timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2798:1003)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2798:434
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2796:536)
    at async R.terminate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5173:637)
    at async q.restartSession (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5197:851)```

**Comment by weinand** [comment] 2019-12-09 09:50
Does it make a difference if you disable the Liveshare extension?

**Comment by weinand** [comment] 2019-12-09 09:57
I tried to faithfully reconstruct your setup but I wasn't able to reproduce the issue:

![2019-12-09_10-49-20 (1)](https://user-images.githubusercontent.com/1898161/70426042-a41a4380-1a72-11ea-9251-382e5c1279fe.gif)

What version of node.js are you using?

**Closed** 2019-12-16 21:10 UTC
Labels: debug, needs more info

**Comment by SushKenyNeosoft** [comment] 2020-01-16 07:36
> In my case, I have to double click the "Restart" button to restart debugging. Is this the expected behavior?
> 
> Sorry to ask this here, I didn't want to register another issue for a simple question.

Worked for me too!

**Comment by elahmo** [comment] 2020-01-16 10:06
+1

This is a rather odd solution, but it works :D

**Comment by weinand** [comment] 2020-01-16 10:30
@isidorn could you please try to reproduce this issue (or provide additional insights).
I could not reproduce this.

**Comment by schperplata** [comment] 2020-01-28 11:43
@weinand I am struggling with the very same issue, and it is really a step-back in terms of productivity. How can I help?
This are what logs show on my restart action request:
![image](https://user-images.githubusercontent.com/8736111/73260648-a07d8000-41ca-11ea-95e6-8448b746ec84.png)

**Comment by isidorn** [comment] 2020-01-28 11:52
@schperplata  Yeah seems like the debug extension could not handle the restart request. If you are not using node please consider filling the issue against the extension. If you are using node please file a new issue with exact steps in this repo. Thanks

**Comment by schperplata** [comment] 2020-01-28 13:14
I've already reported it [here](https://github.com/microsoft/vscode/issues/85386). Than I closed it to remove duplicated issues. Now I guess you want me to create an issue in python extension repo or is ptvsd OK?

This 'wrong-repo-go-and-create-it-again-elsewhere' approach is driving me crazy, just saying.
