### ISSUE TITLE
Horizontal scrolling even with line wrapping

### ISSUE THREAD

**Issue by ygoe** [microsoft/vscode#166150] opened 2022-11-11 21:24 UTC
Type: <b>Bug</b>

This long line scrolls to the right and also wraps shortly after it. It should not scroll.

```html
			<style>
				.slider.gradient
				{
					--slider-range-background: linear-gradient(to right, #6ee02c/**#6ee02c**/ 0px, #6ee02c/**#6ee02c**/ 130px, #e5d824/**#e5d824**/ 160px, #e5d824/**#e5d824**/ 210px, #ed5725/**#ed5725**/ 240px, #ed5725 100%);
				}
			</style>
```

You can already see how the text continues behind the vertical scroll bar at the right side.

![grafik](https://user-images.githubusercontent.com/868315/201432853-b01ac1ef-b7d9-441d-bdb6-b02fc023e633.png)

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (7.05GB free)|
|Process Argv|--folder-uri file:///c%3A/Web/frontfire2 --crash-reporter-id 1b00a758-578c-4b77-a258-fe145c18e004|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-solution-explorer|fer|0.7.4
vscode-todo-highlight|jgc|2.0.4
ecdc|mit|1.8.0
vscode-language-pack-de|MS-|1.73.11090923
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.6.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.20
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
cpptools|ms-|1.12.4
remote-explorer|ms-|0.0.2
vscode-nuget-gallery|pat|0.0.24
platformio-ide|pla|2.5.5
better-pageup-pagedown|rus|0.0.1
jinjahtml|sam|0.19.0
trailing-spaces|sha|0.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce2:30605431
3d0df643:30608728
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by alexdima** [comment] 2022-11-25 21:09
Duplicate of #32856

**Closed by alexdima** 2022-11-25 21:09 UTC
