### ISSUE TITLE
Reopening a git repo in a container results in repository being marked as unsafe

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172470] opened 2023-01-25 22:13 UTC
![image](https://user-images.githubusercontent.com/30305945/214703339-6f9ca48d-4813-4040-8ec3-698ec67c0c2b.png)

**Comment by lszomoru** [comment] 2023-01-26 08:44
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/7628.

**Closed by lszomoru** 2023-01-26 08:44 UTC
