### ISSUE TITLE
markdown editor and preview ui issues

### ISSUE THREAD

**Issue by martypdx** [Microsoft/vscode#9357] opened 2016-07-15 16:14 UTC
- VSCode Version: Version 1.3.1 (1.3.1)
- OS Version: OSX 10.11.4

A. Syntax highlighting fails after first backtick in second physical line of text 

Steps to Reproduce:
1.  Type this text into `md` file:
```
Here is some text with 
`back-ticks` in second line and `this` won't highlight
```
2. The first back-ticked word is highlighted, but second isn't

B. md preview view looses zoom

Steps to Reproduce:
1. Preview a markdown doc via `cmd`+`shift`+`V`
2. Press `cmd`+`+` to zoom in (multiple times to see #5)
3. Click another tab
4. Click back to preview, zoom is reset
5. Pressing `cmd`+`+` zooms to one more than originally zoomed level of #2

**Comment by mjbvz** [comment] 2016-09-27 20:41
The first issue looks like a duplicate of #11906 This should be fixed in the latest insider builds.

I'm also unable to the zoom issue. Can you please try the latest insiders build and let me know if this still repos. Thanks.

**Closed by mjbvz** 2016-09-27 20:41 UTC
Labels: duplicate, markdown, not-reproducible

**Comment by martypdx** [comment] 2016-10-21 16:01
@mjbvz I'm on `Version 1.6.1 (1.6.1)` and preview zoom issue is worse, there's no work-around to correct the frames:

![image](https://cloud.githubusercontent.com/assets/478864/19605056/f46b6f6c-976c-11e6-8eb0-66df3df343ca.png)

**Comment by martypdx** [comment] 2016-10-28 16:02
@mjbvz can you reopen this? It makes the Markdown Preview feature rather unusable for presentation.

**Comment by mjbvz** [comment] 2016-10-28 17:13
@martypx The zoom issue is a being tracked by #5745 (see other linked issues such as #12921 and #12824 too)

**Comment by martypdx** [comment] 2016-10-28 17:14
makes sense, thx
