### ISSUE TITLE
Intellisense autocomplete does not work well for JS

### ISSUE THREAD

**Issue by akontsevich** [Microsoft/vscode#31233] opened 2017-07-21 23:05 UTC
- VSCode Version: 1.4.2
- OS Version: Linux 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
1. Created simple bot app with node js (code mentioned below). Auto-complete works fine in line 22 for `session` parameter. 
2. However does not work in line 29 for `session` parameter (in ReceiveMessage() function) even with JSDoc definitions.

```
var restify = require('restify');
var builder = require('botbuilder');

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});

// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

// Listen for messages from users 
server.post('/api/messages', connector.listen());

// Receive messages from the user and respond by echoing each message back (prefixed with 'You said:')
var dialog = require("./rootdialog")
var bot = new builder.UniversalBot(connector, function (session) {
    session.send("You said: %s", session.message.text);
});

/**
 * @param {Session} {session}
 */
function ReceiveMessage(/*Session*/session) {
    session.send("You said: %s", session.message.text);    
}
```

**VS Code for Node.js Development Quickstart Pack** extension installed, does not work without it as well.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-07-21 23:06
Where is the type `Session` defined? Is it coming from one of the imported libraries?

**Comment by akontsevich** [comment] 2017-07-21 23:11
Yes it comes with botbuilder:
`npm install --save botbuilder`

Defined in file: `node_modules/botbuilder/lib/botbuilder.d.ts`

**Comment by mjbvz** [comment] 2017-07-23 00:59
Try using the module name when referencing types:

```js
/**
 * @param {builder.Session} session
 */
function ReceiveMessage(/*Session*/session) {
    session.send("You said: %s", session.message.text);    
}
```

Also try [enabling JavaScript type checking](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files) to track down undefined type references

**Comment by akontsevich** [comment] 2017-07-23 01:17
Both does not work: `[js] can not find name Session` or `[js] can not find name builder`.

**Comment by mjbvz** [comment] 2017-07-25 00:59
Looks like https://github.com/Microsoft/TypeScript/issues/11825

These patterns should work:

```js
import * as builder from 'botbuilder';

/**
 * @param {builder.Session} session
 */
function ReceiveMessage(session) {
    session.send("You said: %s", session.message.text);    
}
```

or

```js
const {Session} = require('botbuilder');

/**
 * @param {Session} session
 */
function ReceiveMessage(session) {
    session.send("You said: %s", session.message.text);    
}
```

Closing as upstream

**Closed by mjbvz** 2017-07-25 00:59 UTC
Labels: javascript, upstream

**Comment by akontsevich** [comment] 2017-07-25 07:47
Thanks! Works.

**Comment by akontsevich** [comment] 2017-08-14 03:04
`const { IConversationUpdate } = require('botbuilder');` does not work for IConversationUpdate object for some reason.

 And if I make
`import * as builder from 'botbuilder';`
then get error in app.js: `Unexpected token import` for 
`var dialog = require("./rootdialog")`
where all of above exists. Any other solution?

**Comment by akontsevich** [comment] 2017-10-08 18:16
Guys, please reopen this bug as the issue was not solved!

**Comment by mjbvz** [comment] 2017-10-13 21:04
@akontsevich https://github.com/Microsoft/TypeScript/issues/11825 is tracking the issue with `const { IConversationUpdate } = require('botbuilder');`

The unexpected token one seems unrelated. Do this reproduce with all extensions disabled?

**Comment by akontsevich** [comment] 2017-10-13 21:23
Yes, reproducible. 
`        /** @param {Session} session */`
Still does not work. Works fine in IntelliJ - will stay on it for now.
