### ISSUE TITLE
Settings Sync Bugs and Bad UX

### ISSUE THREAD

**Issue by justingolden21** [microsoft/vscode#133031] opened 2021-09-13 20:48 UTC
I just wanted to bring this to your attention so others don't have to bang their head against the wall for an hour like I have.

I switched computers and opened VS code, with an internet connection, and even after a while my extensions were not synced, even though I believe I was signed in before. I searched far and wide for getting extensions synced and only found out how to turn on settings sync and how to manage different versions of extensions stored in the cloud.

After a while of searching, I finally noticed the "1" badge next to the default profile icon on the bottom right

![image](https://user-images.githubusercontent.com/30274440/133152941-39c0be38-1d09-4d70-a8ec-96113dd79eaa.png)

I clicked it and went to sign in with GitHub.

After loading for a bit, I got this error:

![image](https://user-images.githubusercontent.com/30274440/133153237-74fd47d6-5f92-4586-a763-bfa42cb7f6f4.png)

The thing with this error is, I get it *every single time* I sign in *for the first time* on a computer. across multiple computers, operating systems, etc. I assume there exist people who don't encounter this error on their first sign in attempt, but this is definitely a bug that should be looked into.

I also encountered this:

![image](https://user-images.githubusercontent.com/30274440/133153074-6730f89a-c655-4717-b30b-fd1094addd8c.png)

As well as the famous chrome dino despite having internet.

After a few more attempts, I finally got a "success" message:

![image](https://user-images.githubusercontent.com/30274440/133153825-6c9f54a5-3fa8-4574-914f-1efc78058b68.png)

Except... it wasn't a success.

Notifications in VS code, which went away after a few seconds:

![image](https://user-images.githubusercontent.com/30274440/133152743-7c3e2fef-0793-4cca-86d4-4acc699c637e.png)

I've been at it for almost an hour and still can't get it to sign in or anything, I've tried copying the url but "signing into github..." doesn't appear anywhere in the status bar and I can't find anywhere to enter the auth token.

I've had shabby internet, but it's still good enough to consistently google something, and yet I encounter all of these problems. Even with perfect internet, the UX of syncing extensions and the bugs regarding the first sign in attempt should definitely be looked into, especially considering how big this feature is in VS code.

I hope this documentation is through enough to help fix these bugs and UX issues. Thank you in advance, and I love VS code and would love to see it continue to improve.

**Comment by justingolden21** [comment] 2021-09-13 20:57
I restarted the computer, got the same error the first time, and again the second time it said success and then prompted me in vs code to open from the browser signing in, I did, and now it's infinitely loading in the task bar again. I saw "signing in with github..." in the status bar, and when I clicked it I got the same undefined error as shown above. I've tried everything and signing in is impossible. It says "success" but still manages to fail. Thanks in advance.

**Comment by justingolden21** [comment] 2021-09-13 21:02
I restarted the computer and tried again, same thing. I restarted a third time and same again.

First time I got the first error above I get on every device. Second time, I get a success, but then I get the error "cancelled" in VS code and then a prompt to open with the VS code URL handler. I do so and it loads forever in my taskbar. Last time it went for over half an hour. I'm unable to kill this process (hence restarting the entire computer). I saw "signing into github..." in the status bar, and when I click it I get the same "undefined" error as shown above. It is impossible for me to sign in to VS code and it's been well over an hour now. Please assist.

**Comment by justingolden21** [comment] 2021-09-13 21:05
![image](https://user-images.githubusercontent.com/30274440/133156127-2f2c3219-cc81-4a9d-9fbc-03320be0006a.png)

**Comment by sandy081** [comment] 2021-09-17 07:56
It seems related to log in, hence assigning to @TylerLeonhardt

**Comment by justingolden21** [comment] 2021-09-20 20:03
Still encountering this issue

Found a new error message though

![image](https://user-images.githubusercontent.com/30274440/134067502-92e80b8b-28bc-4af6-895a-b439f8d97885.png)

@TylerLeonhardt thank you

**Comment by TylerLeonhardt** [comment] 2021-10-04 18:08
Your new issue is a duplicate of this:
https://github.com/microsoft/vscode/issues/130640

Your original issue is a duplicate of this:
https://github.com/microsoft/vscode/issues/108304

I'm going to close this as a dupe but it'll be linked to those issues so we'll be able to reference it because you added a ton of good info.

**Closed by TylerLeonhardt** 2021-10-04 18:08 UTC
