### ISSUE TITLE
Add sticky header for programming langs

### ISSUE THREAD

**Issue by spacegoing** [Microsoft/vscode#18974] opened 2017-01-21 12:37 UTC
From emacs' sticky func mode:

> [Displays a header line that shows the declaration line of the function or tag on the topmost line in the text area. This allows you to keep that declaration line in view at all times, even if it is scrolls off the “top” of the screen.](https://www.gnu.org/software/emacs/manual/html_node/semantic/Sticky-Func-Mode.html)

I rely on this mode heavily. Jetbrains' IDEs like Pycharm and IntelliJ also have similar functionalities. I hope you can add this to vscode:D

**Comment by dbaeumer** [comment] 2017-01-21 15:05
@jrieken FYI.

**Comment by alexandrudima** [comment] 2017-11-23 14:20
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Comment by spacegoing** [comment] 2017-11-23 14:37
@alexandrudima Please reconsider this issue. Other than emacs, all Jetbrains' products have this feature. This feature is extremely helpful when the file is large.

**Comment by jrieken** [comment] 2017-11-23 16:15
This is likely a dupe of https://github.com/Microsoft/vscode/issues/9418

**Comment by alexandrudima** [comment] 2017-11-24 08:46
Let's continue tracking in #9418

**Closed by alexandrudima** 2017-11-24 08:46 UTC
Labels: editor, feature-request
