### ISSUE TITLE
More info while downloading a file via ssh

### ISSUE THREAD

**Issue by Onur-Kurum** [microsoft/vscode#132417] opened 2021-09-06 04:01 UTC
During an ssh connection, if I download a large file from the server (using the explorer panel, right click on a file, Download), all I can see is "Downloading" in status bar at the bottom. A bit more basic information such as speed, ETA would be very useful, especially with large files.

**Comment by roblourens** [comment] 2021-09-09 20:02
You have Explorer now right @JacksonKearl?

**Comment by JacksonKearl** [comment] 2021-09-09 20:22
I have explorer. Explorer is just calling out to file service. (cc @bpasero) I don't know of a good datasource for speed/eta, seems like something the SSH extension would need to provide, probably with some new API.

**Comment by bpasero** [comment] 2021-09-10 05:19
@JacksonKearl this is a duplicate of https://github.com/microsoft/vscode/issues/111580. In web the upload/download progress is a lot more detailed because the assumption is that the operation takes longer. But agree that it should ideally be aligned in both cases.

**Closed** 2021-09-10 19:01 UTC
Labels: feature-request, *duplicate, file-io
