### ISSUE TITLE
SourceControl plugin exception

### ISSUE THREAD

**Issue by AlphaHans** [microsoft/vscode#225473] opened 2024-08-13 07:35 UTC
Type: <b>Bug</b>

After I updated, sourcecontrol was very slow and I was unable to view all repository modifications. Everything was ok until I updated vscode. I suspect that pulling the history records is too slow and cannot be displayed. My sourcecontrol interface keeps showing loading.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900K (32 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.75GB (29.57GB free)|
|Process Argv|--crash-reporter-id 3265ebc5-a347-4093-b4a4-d3b119dc20d5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-14900K (32 x 0)|
|Memory (System)|31.22GB (28.22GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
vscode-gn|npc|1.1.0
git-easy|bib|1.11.0
gitignore|cod|0.9.0
githistory|don|0.6.20
gitlens|eam|15.2.3
vscode-clangd|llv|0.1.29
gn-format|Mar|0.0.1
vscode-language-pack-zh-hans|MS-|1.92.2024080709
java|red|1.33.0
code-spell-checker|str|3.0.1
vscode-decompiler|tin|0.1.0
jar-viewer|wma|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-08-13 07:39
Did you try the setting `"scm.showHistoryGraph": false` that the release notes mention?

**Comment by AlphaHans** [comment] 2024-08-14 09:53
> Did you try the setting `"scm.showHistoryGraph": false` that the release notes mention?

Thanks for your reply, it worked after I turned it off. 

Maybe it's the same as I guessed, because the pulling speed of the history record is too slow and it cannot be displayed?

**Comment by lszomoru** [comment] 2024-08-19 14:31
Closing as duplicate of https://github.com/microsoft/vscode/issues/224517

**Closed by lszomoru** 2024-08-19 14:31 UTC
