### ISSUE TITLE
-w options is not working as expected in Windows git config

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#4214] opened 2016-03-14 23:54 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Windows-10

Steps to Reproduce:

1. Try code-alpha -w on windows, it works as expected. 
2. Setup vscode to be the default git config editor as described in #4006
3. run `git config --global -e`

Expected:
Code opens the git config to edit

Actual:
```
/c/Program Files (x86)/Microsoft VS Code Alpha/bin/code-alpha: line 7: realpath:
 command not found
/c/Program Files (x86)/Microsoft VS Code Alpha/bin/code-alpha: line 10: ./Code -
 Alpha.exe: No such file or directory
error: There was a problem with the editor 'code-alpha --wait'.

```

**Comment by SofianHn** [comment] 2016-03-14 23:56
When code is already opened, the -w config is not opening another window, it's simply existing. Not sure if this is a separate issue or by design.

**Comment by bpasero** [comment] 2016-03-15 15:06
@SofianHn I cannot reproduce on my windows 10 but this looks like an issue with the script we use for launching if I see the errors, moving to @joaomoreno 

I will open a separate issue that -w does not work on Windows when already running.

**Comment by joaomoreno** [comment] 2016-03-15 15:12
@SofianHn Which version of git do you have in Windows? If under 2.0, update it and try again. If it works, just close this.

**Comment by SofianHn** [comment] 2016-03-15 17:23
Updated git and worked as expected

**Comment by joaomoreno** [comment] 2016-03-15 19:09
OK. Let's maybe add a warning on Windows to update the git to 2.0.

**Comment by joaomoreno** [comment] 2016-03-18 14:25
Verification: when having git <= 2.0.0 users should get a warning to update git.

**Comment by SofianHn** [comment] 2016-03-18 21:12
I did not

**Comment by isidorn** [comment] 2016-03-19 09:42
It's not relevant to the git editor. If you have git < 2 in your path you should get a nice warning on startup. Reloading the window won't do, you need to shutdown Code and start it back up.

**Closed by isidorn** 2016-03-19 09:42 UTC
Labels: bug, important

**Comment by joaomoreno** [comment] 2016-03-29 12:35
There was definitely a problem with this. Git's version might be something like `1.9.5.msysgit.2` which makes `semver` barf. Pushed fix to master and release.

**Comment by joaomoreno** [comment] 2016-03-29 12:35
@isidorn verify by installing git 1.9.5

**Comment by isidorn** [comment] 2016-03-29 14:28
I now get a nice warning to install git > 2.0
