### ISSUE TITLE
The search settings widget is obstructed by the sticky scroll

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [microsoft/vscode#160428] opened 2022-09-08 15:50 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Press <kbd>Alt</kbd><kbd>C</kbd> (or your hotkey for `toggleFindCaseSensitive`)
2. Observe this thingie popping up in the top-right corner of the editor:
    ![image](https://user-images.githubusercontent.com/69473580/189167018-38e0f6dc-6e1c-4aa3-bdee-5760063fb8fa.png)
3. Now enable the sticky scroll and press the hotkey again.
4. Observe that this widget isn't visible anymore. Apparently, the sticky scroll is displayed on top of it.

The search settings widget should be displayed on top of the sticky scroll, not the other way around.

**Comment by gnowland** [comment] 2022-09-08 18:29
Duplicate of #159034

**Comment by rzhao271** [comment] 2022-09-08 20:06
Duplicate of https://github.com/microsoft/vscode/issues/159034

**Closed by rzhao271** 2022-09-08 20:06 UTC
