### ISSUE TITLE
Windows Installer Icon - Insiders

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#35435] opened 2017-09-30 18:21 UTC
It's normally crisper than this

![image](https://user-images.githubusercontent.com/1051190/31048413-6d45caf4-a5d1-11e7-88fb-f66862679719.png)

**Comment by Studio384** [comment] 2017-10-02 12:18
For me it has alays been so uncharp. I always guessed it is because of scaling, tho.

Perhaps it is time to start looking into a better installer since the installer was mentioned as the cause of this low resolution image. Like Atom and GitHub Desktop use, for example.

**Comment by chrisdias** [comment] 2017-10-05 21:47
closing, we are not going to change the icon in setup.

**Closed by chrisdias** 2017-10-05 21:47 UTC
Labels: icon
