### ISSUE TITLE
IntelliSense dies, code helper at 100% CPU usage

### ISSUE THREAD

**Issue by DLevai94** [Microsoft/vscode#32532] opened 2017-08-15 09:55 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.8
react-native-react-redux|EQu|1.1.0
material-icon-theme|PKi|2.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
es7-react-js-snippets|dsz|0.5.2
vscode-babel-coloring|dza|0.0.4
flow-for-vscode|flo|0.7.1
auto-close-tag|for|0.4.3
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
debugger-for-chrome|msj|3.1.7
color-highlight|nau|2.3.0
highlight-matching-tag|vin|0.4.4
vscode-react-native|vsm|0.4.1
vscode-todo-highlight|way|0.5.8

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open

Reproduces without extensions: IntelliSense works but CPU usage is still high

**Comment by miaojiuchen** [comment] 2017-08-16 01:47
after update, VSCODE keep using cpu, don't know what happend
![image](https://user-images.githubusercontent.com/9482138/29344030-bd9377e6-8267-11e7-99c6-02597db9da9f.png)

**Comment by miaojiuchen** [comment] 2017-08-16 02:01
after I terminate the code process, several process called "find" started, and they take away all my CPU usage...... 

![image](https://user-images.githubusercontent.com/9482138/29344313-7d12c6f2-8269-11e7-8ea3-ab619113d8dc.png)

wait about 1 minute, these process quit and every thing looks fine

![image](https://user-images.githubusercontent.com/9482138/29344369-d58b072c-8269-11e7-94ab-1f5ea504355d.png)

**Comment by miaojiuchen** [comment] 2017-08-16 02:17
I found a issue, the same situation
https://github.com/Microsoft/vscode/issues/18033

**Comment by mjbvz** [comment] 2017-08-16 17:44
@DLevai94 Please check the full arguments of the process with the high cpu usage. Either run 

```
ps aux | grep -i code
```

in the terminal and look at the process with the high cpu usage, or use Activity Monitor to get the `pid` of the process and run:

```
ps aux PID
```

**Comment by mjbvz** [comment] 2017-08-16 17:45
@miaojiuchen Please open a new issue for the problem you are seeing. High cpu usage issues often have different root causes

**Comment by miaojiuchen** [comment] 2017-08-17 03:21
@mjbvz After I reinstall vscode and clear all extensions, the problem disappeared, thanks

**Comment by DLevai94** [comment] 2017-08-17 12:23
@mjbvz thanks for your help. At this time, I can't reproduce it. Maybe some update fixed it, but if I can, I'll check it.

**Comment by mjbvz** [comment] 2017-08-17 17:44
Ok, closing this issue for now. Please post more information if you see this again and we can reopen this to investigate further

**Closed by mjbvz** 2017-08-17 17:44 UTC
Labels: javascript, needs more info, new release

**Comment by DLevai94** [comment] 2017-08-24 21:02
it came again.
result of `ps aux PID`:
`davidlevai 89720  99.1  0.1  3283240  11068   ??  R    Wed10AM 893:44.15 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.a`

**Comment by tonghuashuo** [comment] 2017-09-04 04:04
I'm experiencing the same problem. after coding for a while code intellisense disappears. fans of my macbook start to run like crazy. CPU usage off the chart by an 'Code Helper'.

Kill the 'Code Helper' and things return to normal soon. reload vscode and it works fine for a while and then all start again. this happens in both stable & insider version.

Seems to be a problem with extensions. Tried disable some of them but none helped. Don't know which one to blame. Any way to tell which extension is causing this? so I can provide more useful information to help locate the problem.

PS: Output of `ps aux` looks normal. not much useful information. any other suggestions on how I can help?
