### ISSUE TITLE
Preferences/Settings/"Tab Size" option and "Insert Spaces" option not working as expected

### ISSUE THREAD

**Issue by vcrobe** [microsoft/vscode#172171] opened 2023-01-24 14:28 UTC
Type: <b>Bug</b>

**Steps to reproduce**

1- Install VSCode (portable version)
2- Install C# for VS Code extension
3- Create a C# console app using the CLI
4- Open the project folder in VSCode
5- Go to File/Preferences/Settings
6- In the "User" settings set:
        a) Editor: Tab Size to 3
        b) Editor: Render Whitespace to "all"
        c) Editor: Insert Spaces to "false" (unchecked)
        d) Editor: Detect Indentation to "false" (unchecked) 

7- In the "Workspace" settings set:
        a) Editor: Tab Size to 4
        b) Editor: Render Whitespace to "selection" (default)
        c) Editor: Insert Spaces to "true" (checked) (default)
        d) Editor: Detect Indentation to "false" (unchecked) 

When I close the the settings this is what is stored in the settings.json file

```
{
	"editor.detectIndentation": false
}
```

It's storing only the non default values so when I press tab the tab size is 3 and it's not inserting spaces!

And the whitespaces are all rendered all the time. In this case they must be rendered only when a selection is made!

**Solution**

When creating/modifying the settings.json VSCode must analyze the hierarchy of settings (Folder, Workspace, User) to determine what values must be stored in the file.

Currently I'm working on a solution with four projects. Two of them use whitespaces the others use tabs. **I had to switch to Visual Studio because it's using the User settings instead the folder settings.** So all files of all projects are stored using spaces in all cases.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (11.94GB free)|
|Process Argv|--crash-reporter-id 56c2c980-cc45-4989-bfa8-01a52976173f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.25.2

</details>

**Comment by rzhao271** [comment] 2023-03-21 15:53
A workaround for now is manually editing the workspace JSON setting files.
Adjusting the workspace setting away from the default value and back to the default value again should also save the setting into the workspace JSON setting file.

Potential duplicate of #58038

**Comment by rzhao271** [comment] 2023-05-25 22:32
Closing as a duplicate of https://github.com/microsoft/vscode/issues/58038

**Closed by rzhao271** 2023-05-25 22:32 UTC
Labels: settings-editor, under-discussion
