### ISSUE TITLE
Hash does not reliably go to line in Go to file...

### ISSUE THREAD

**Issue by HaveSpacesuit** [microsoft/vscode#128876] opened 2021-07-16 20:46 UTC
Issue Type: <b>Bug</b>

Open the Go to file... input box. Type a partial file name followed by # and a line number. The file opens, but the cursor is not always navigated to the line number given.

This is regularly reproducible for me in larger projects.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (16.12GB free)|
|Process Argv|--crash-reporter-id 9d722a95-7d61-4158-9691-550c2baf45dd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.0.1
vscode-nuget-package-manager|jmr|1.1.6
svg|joc|1.4.7
vscode-scss|mrm|0.10.0
csharp|ms-|1.23.13
debugger-for-chrome|msj|4.12.12
vscode-subword-navigation|ow|1.2.0
rescuetime|Res|1.0.1
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by IllusionMH** [comment] 2021-07-17 11:22
/duplicate of #128518
Please upvote that issue and provide additional details if needed

**Closed** 2021-07-17 11:22 UTC
Labels: *duplicate, new release
