### ISSUE TITLE
Redirect settings.json to custom setting files

### ISSUE THREAD

**Issue by alinaimi** [microsoft/vscode#178342] opened 2023-03-26 02:38 UTC
**settings.json** could get lengthy and become too burdensome to manage. A good solution is to break it down into individual setting .json files.

e.g. a setting file can be included in main **settings.json** using:

`"launch": { "RedirectSection": "settings/setting-dbg.json" }`

**Comment by IllusionMH** [comment] 2023-03-26 03:36
Looks like duplicate of #15909

**Closed** 2023-03-27 22:20 UTC
Labels: *duplicate
