### ISSUE TITLE
JSDoc and TypeScript IntelliSense support for @link inline tag

### ISSUE THREAD

**Issue by couven92** [Microsoft/vscode#57495] opened 2018-08-29 11:28 UTC
[Use JSDoc: {@link}](http://usejsdoc.org/tags-inline-link.html) defines the `@link`, `@linkplain` and `@linkcode` tags in JavaScript and TypeScript JSDoc-style documentation comments.

As can be seen in the screenshot below the IntelliSense tooltip does not recognize the presence of the `@link` tag correctly.

![image](https://user-images.githubusercontent.com/8759693/44784076-ad88e080-ab8c-11e8-9f07-bec2f183ce24.png)

The following describes how the different usages of `@link` **should** be rendered:

* `{@link https://github.com/Microsoft/vscode}`   
   https://github.com/Microsoft/vscode
* `[Microsoft/vscode]{@link https://github.com/Microsoft/vscode}`  
   [Microsoft/vscode](https://github.com/Microsoft/vscode)
* `{@link https://github.com/Microsoft/vscode|Microsoft/vscode}`  
   [Microsoft/vscode](https://github.com/Microsoft/vscode)
* `{@link https://github.com/Microsoft/vscode Microsoft/vscode}`  
   [Microsoft/vscode](https://github.com/Microsoft/vscode)

Thus the following example from [Use JSDoc: {@link}#Examples](http://usejsdoc.org/tags-inline-link.html#examples)

``` js
/**
 * See {@link MyClass} and [MyClass's foo property]{@link MyClass#foo}.
 * Also, check out {@link http://www.google.com|Google} and
 * {@link https://github.com GitHub}.
 */
```

should render in the VS Code Intellisense tootip as:

> See [MyClass](MyClass) and [MyClass's foo property](MyClass#foo). Also, check out [Google](http://www.google.com) and [GitHub](https://github.com)

Using the `@linkplain` tag instead of `@link` should suppress link colouring and make the link text appear as normal text.

Using the `@linkcode` tag instead of `@link` should make the link appear in a monospace font (as if the entire Link was wrapped inside an HTML `<code></code>` tag.

[Use JSDoc: {@link}](http://usejsdoc.org/tags-inline-link.html) also states that the link target can be a namepath instead of a URL. Ideally, IntelliSense should suggest all known symbols in the current scope when writing the `@link` tag. When written, the namepath should support go-to-definition and find-all-references behaviour.

**Comment by mjbvz** [comment] 2018-09-04 18:58
Duplicate of https://github.com/Microsoft/TypeScript/issues/16498

**Closed by mjbvz** 2018-09-04 18:58 UTC
