### ISSUE TITLE
Unable to and keybinding to Tasks: Run Task in Linux

### ISSUE THREAD

**Issue by KG32** [microsoft/vscode#110633] opened 2020-11-14 13:26 UTC
- VSCode Version: 1.51.1
- OS Version: Ubuntu 20.04.1 LTS

Steps to Reproduce:

1. Open Keyboard Shortcuts
2. Missing available binding for Tasks: Run Task

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2020-11-16 09:40
Duplicate of https://github.com/microsoft/vscode/issues/108051#issuecomment-704126485

You can add a keyboard shortcut for it, it just doesn't show in the UI.

**Closed by alexr00** 2020-11-16 09:40 UTC
