### ISSUE TITLE
Allow multiple peek/references widget or store history

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#24745] opened 2017-04-14 06:27 UTC
It would be very helpful to allow more than one set of references / location list / peek widget to be shown at the same time.

For example, in this image I'm looking at all `IpcMessage` derived types. If I want to look at the references of `IpcQuit`, the derived type reference view is closed and cannot be easily retrieved (especially if I've navigated to a separate part of the code base).

![image](https://cloud.githubusercontent.com/assets/356714/25035103/6147f1f2-20a0-11e7-81ee-806728818338.png)

**Comment by jrieken** [comment] 2017-04-14 07:07
dupe of #6857

**Closed by jrieken** 2017-04-14 07:07 UTC
