### ISSUE TITLE
Typescript errors disappear from typescript file when file is opened

### ISSUE THREAD

**Issue by svankirk** [microsoft/vscode#81389] opened 2019-09-24 19:00 UTC
Problem:

vscode will not display some typescript errors inline.  With source files closed if you compile the project it finds errors as expected and shows them in the task window.  It also reports them in the 'problems' tab of the console.  As soon as you open the file, certain problems gets dropped from the 'problems' tab and the editor shows no error.  
![errormissing](https://user-images.githubusercontent.com/3734797/65541656-febbee80-deca-11e9-8c41-6ff9feea7420.png)

Steps to Reproduce:

1.  Compile or compile and watch a typescript program.  There are a whole class of errors which do not show up.  This code demonstrates it 
```
class test {
}
test[1] 
```
2.  The error shows up in the compile window and the problem window.
3.  Open up the source file:  the problem disappears from the problem window and does not show up inline in the editor.

System:
This error occurs on current release and on the latest insider release with no extentions.  I have reproduced it with empty settings files.

Version: 1.39.0-insider (system setup)
Date: 2019-09-24T05:26:22.699Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment] 2019-09-24 19:21
@svankirk Looks like VSCode uses configuration with `"noImplicitAny": false`.
Do you have several config files in workspace?
What TS version are you using in VSCode: built-in 3.6 or from local `node_modules` that you are using for compilation?

As soon as file opened Problems entries will be replaced with recent information from opened file and therefore can be different if different versions of TS and/or configurations are used in VSCode and CLI or different configurations.

**Comment by svankirk** [comment] 2019-09-24 20:18
I don't have any local version of typescript in local `node_modules`   Just in case, I removed typescript globally and then uninstalled and re-installed vscode .  It still happens.

**Comment by svankirk** [comment] 2019-09-24 20:27
Okay, thank you!   I moved back to a single `tsconfig.json` and adjusted my tasks accordingly.  Everything now seems to be working as expected.   I would still consider this a bug.

**Comment by IllusionMH** [comment] 2019-09-24 20:47
Not If you had custom names for TS configuration instead of `tsconfig.json` then VS Code won't detect it since it only uses that name.
However there is feature request #12463 that will allow to specify exact path to config. Also you can check for workarounds some posted there.

**Comment by mjbvz** [comment] 2019-10-23 22:20
Thanks @IllusionMH. That sounds like the root cause of the original issue.

Closing as by-desig but #12463 would improve support. You can also run `TypeScript: Go to project configuration` to check what project VS Code considers the current file to be in

**Closed by mjbvz** 2019-10-23 22:20 UTC
