### ISSUE TITLE
anytime i try to open a folder VS crashes to destkop

### ISSUE THREAD

**Issue by DrBlackross** [microsoft/vscode#231762] opened 2024-10-19 22:33 UTC
Type: <b>Bug</b>

installed via snap, and deb... same thing on both. i can not open a folder from the file menu, the welcome screen, etc.... i have to right click a folder and select "open with..." then select VS and open the folder.

this version though is installed via snap

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.11.4-1-liquorix-amd64 snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor (16 x 3344)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 2, 1|
|Memory (System)|15.55GB (13.29GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 6cc12527-91f2-4d2e-b962-4df68595375a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Arduino|moo|0.0.4
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.9
cpptools-extension-pack|ms-|1.3.0
vscode-serial-monitor|ms-|0.13.1
platformio-ide|pla|3.3.3
java|red|1.35.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-arduino-community|vsc|0.7.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1:31157159
showchatpanel:31153267
5fd0e150:31155592
dwcopilot:31162478
iconenabled:31158251

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-10-20 01:53
/duplicate of https://github.com/microsoft/vscode/issues/230454

**Closed** 2024-10-20 01:53 UTC
Labels: *duplicate
