### ISSUE TITLE
HP ClickPad scrolling makes VSCode get stuck for 2-5 seconds

### ISSUE THREAD

**Issue by paritosh149** [Microsoft/vscode#49093] opened 2018-05-03 06:50 UTC
Issue Type: <b>Bug</b>

I am using VScode version 1.22.2 on my HP ProBook 440 G4. This laptop has clickpad with factory installed drivers and touch related software. Whenever, I try to scroll up or down in VSCode windows, using the click pad two finger gesture, VSCode gets stuck for 2-5 secs.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.43GB (2.08GB free)|
|Process Argv|d:\Program Files\Microsoft VS Code\Code.exe D:\demo\mydemo|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.12.1
vscode-eslint|dba|1.4.8
vsc-material-theme|Equ|2.0.1
prettier-vscode|esb|1.3.1
diff-tool|jin|0.0.1
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
vscode-icons|rob|7.23.0
open-in-browser|tec|1.1.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-05-04 04:41
Duplicate of https://github.com/Microsoft/vscode/issues/13612

**Closed by bpasero** 2018-05-04 04:41 UTC
Labels: freeze-slow-crash
