### ISSUE TITLE
vscode getting slower and slower

### ISSUE THREAD

**Issue by taoqf** [Microsoft/vscode#45952] opened 2018-03-16 06:05 UTC
- VSCode Version:1.21.0
- OS Version:Debian

with upgrade time and time again, it's getting slower and slower now. 
I do remember vscode was slower then sublime text, but faster than atom,
but now, you see, it's getting more and more close to vs.

**Comment by r3nya** [comment] 2018-03-16 08:00
Hi @taoqf 
Maybe you use a lot of plugins … ?

**Comment by taoqf** [comment] 2018-03-16 09:01
Maybe you are right. I will try remove as much plugins as possible and see if it will speed up.

**Comment by r3nya** [comment] 2018-03-16 09:04
@taoqf it was helpful for me. :)

**Comment by jrieken** [comment] 2018-03-16 09:10
@taoqf That's not nice to hear but it's also little information that you are providing here. Please check with our wiki here: https://github.com/Microsoft/vscode/wiki/Performance-Issues. That should help you narrow down in which area performance is getting lost.

**Comment by taoqf** [comment] 2018-03-17 06:50
after removing some plugins, it's getting better. thanks.

**Comment by taoqf** [comment] 2018-03-21 07:55
It's getting worse now,  cpu keeps high, even 100%, and memory increasing after I open my project.
Now I have disabled all the extensions, this issue still exist.

**Comment by taoqf** [comment] 2018-03-21 08:00
when start code using `--status`, I find the `watcherService`
100	  1203	 14053	       watcherService

**Comment by taoqf** [comment] 2018-03-21 10:26
https://raw.githubusercontent.com/taoqf/taoqf.github.io/master/CPU-20180321T155359.cpuprofile

**Comment by taoqf** [comment] 2018-03-22 02:22
@Tyriar Will you plz take a look at this? I think it may be a bug.

**Comment by Tyriar** [comment] 2018-03-22 16:52
@taoqf does the folder you have open have a recursive symlink by chance? There was a 100% CPU bug that I fixed recently for this. Could you try reproducing in the Insiders build? https://code.visualstudio.com/insiders/

**Comment by taoqf** [comment] 2018-03-23 00:45
probably, I used [cnpm](https://github.com/cnpm/cnpm)
```sh
npm i -g cnpm
cnpm i
cnpm test
```

**Comment by taoqf** [comment] 2018-03-23 00:59
It must be.
I tried npm
it's ok

**Comment by taoqf** [comment] 2018-03-23 00:59
When will this be released?

**Comment by taoqf** [comment] 2018-03-23 01:17
insiders works great

**Comment by Tyriar** [comment] 2018-03-23 17:27
The next version will be released in the next 2-3 weeks.

**Comment by taoqf** [comment] 2018-03-24 00:18
Thanks

**Comment by taoqf** [comment] 2018-03-31 01:34
Version:          Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:12:59.181Z)
OS Version:       Linux x64 4.9.0-6-amd64
CPUs:             Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 1796)
Memory (System):  11.63GB (2.29GB free)
Load (avg):       3, 3, 2
VM:               0%
Screen Reader:    no
Process Argv:     /usr/share/code-insiders/code-insiders ./

CPU %   Mem MB     PID  Process
    4      107   24191  code-insiders main
    0       24   24195     zygote
   12      238   24240       zygote
    1       83   24294         extensionHost
    0       48   24421           electron_node tslintServer.js
    3       95   29615           electron_node htmlServerMain.js
   99      155   31180           electron_node electronForkStart.js tsserver.js
    3       48   31183             electron_node typingsInstaller.js tsserver.js typesMap.js
    0       48   24296         watcherService
    0       48   27597         searchService
    0       83   24246       zygote
    3       71   24230     gpu-process

Is this OK?

**Comment by taoqf** [comment] 2018-04-03 10:58
@Tyriar  try this

```sh
git clone git@github.com:taoqf/sample.git
cd sample
cnpm i
code-insiders ./
```

`top`

  PID | USER | PR | NI | VIRT | RES | SHR | S | %CPU | %MEM | TIME+ COMMAND
-------|---------|------|----|--------|-------|-------|----|----------|-----------|------------------------
 2728 | taoqf  | 20 |  0 | 1566312 | 699336 |  36704 | R | 96.1 | 5.7 |  3:08.94 code-insiders

and `code-insiders --status`

```sh
➜  sample git:(master) code-insiders --status

Version:          Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T14:36:39.526Z)
OS Version:       Linux x64 4.9.0-6-amd64
CPUs:             Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 1672)
Memory (System):  11.63GB (4.12GB free)
Load (avg):       4, 3, 2
VM:               0%
Screen Reader:    no
Process Argv:     /usr/share/code-insiders/code-insiders ./
CPU %   Mem MB     PID  Process
    5      107   13228  code-insiders main
    0       24   13242     /usr/share/code-insiders/code-insiders --type zygote --no-sandbox
   12      274   13285       /usr/share/code-insiders/code-insiders --type zygote --no-sandbox
    9       71   13336         extensionHost
    2       48   13451           electron_node tslintServer.js
   93      167   13452           electron_node electronForkStart.js tsserver.js
    5       48   13482             electron_node typingsInstaller.js tsserver.js typesMap.js
    3       48   13337         watcherService
    2       95   13290       /usr/share/code-insiders/code-insiders --type zygote --no-sandbox
    2       71   13273     gpu-process

Workspace Stats:
|  Window (sample.ts - sample - Visual Studio Code - Insiders)
|    Folder (sample): 6 files
|      File types: ts(2) json(2) gitignore(1) js(1)
|      Conf files: package.json(1) tsconfig.json(1)
```

The most important thing is, there is no typescript's intellisense, even I could not use F12 to locate the type definition.

**Comment by Tyriar** [comment] 2018-04-03 18:10
@taoqf that problem is related to typescript which isn't my area, so I've unsubscribed 😃

**Comment by mjbvz** [comment] 2018-04-05 22:45
@taoqf Can you please try collecting the tsserver log:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Open the output panel and go to the  `TypeScript` section. At the very top, look for a message that says: `TSServer log file:`  followed by the path to the log file. Open that log file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by taoqf** [comment] 2018-04-07 08:31
@mjbvz You can do more test using [this sample](https://github.com/taoqf/sample)

```sh
npm i -g cnpm
git clone git@github.com:taoqf/sample.git
cd sample
cnpm i
code-insiders ./
```

**Comment by taoqf** [comment] 2018-04-10 05:07
@mjbvz Do you still focus on this?

**Comment by taoqf** [comment] 2018-04-10 10:30
@mjbvz seems version `1.23.0-insider 609c4ba1e7abc39952ef5fb7f3a22c0be0349efe x64` works fine for me.

**Comment by mjbvz** [comment] 2018-04-10 17:58
Ok, possibly caused by https://github.com/Microsoft/TypeScript/issues/23183

Let me know if you hit this issue again in insiders

**Closed by mjbvz** 2018-04-10 17:58 UTC
Labels: javascript, needs more info, typescript

**Comment by taoqf** [comment] 2018-04-11 01:56
Thanks
