### ISSUE TITLE
Emmet with JS files (JSX) is not working.

### ISSUE THREAD

**Issue by admmasters** [Microsoft/vscode#4962] opened 2016-04-05 13:28 UTC
- VSCode Version: Version 0.10.14-insider (0.10.14-insider)
- OS Version: OSX 10.11.4

Steps to Reproduce:
1. Type `div>` within the editor in a JS file (JSX)
2. Emmet does not expand to `<div></div>` as expected.

Note:
This does work if explicitly using a jsx file with "Javascript React" as a language, but then you are missing features like jump to symbol etc that you get with "Javascript".

**Comment by egamma** [comment] 2016-04-06 08:24
>This does work if explicitly using a jsx file with "Javascript React" as a language,

this is the recommended way to do it, we do not want to enable emmet by default in JS.

>Then you are missing features like jump to symbol etc that you get with "Javascript".

this should not be the case, since the same language service/parser is used for .js and .jsx files. Can you add a snippet that illustrates the problem.

**Comment by egamma** [comment] 2016-04-13 18:28
@admmasters ping?

**Comment by Phisherman** [comment] 2016-05-06 19:16
Is there an option to enable emmet in JS files? The jsconfig.json doesn't seem to have an option. It's annoying to change every time the language mode to `JavaScript React` to be able to use Emmet.

**Comment by msudgh** [comment] 2016-09-28 11:26
Put bellow line into your user settings, most probably that will work.
`
        "emmet.syntaxProfiles": {
                "javascript": "html"
        }
`

**Comment by sillero** [comment] 2016-10-11 16:16
`"emmet.syntaxProfiles": { "javascript": "jsx" }` did the trick
it properly expands with the jsx notation (`class` -> `className`, `for` -> `htmlFor`, ...)

**Comment by admmasters** [comment] 2016-11-04 11:25
Confirmed - great work, thank you!

**Comment by johnpeele** [comment] 2016-12-28 16:54
Confirmed as well! - @sillero's suggestion worked for me.

Visual Studio Code - v1.8.1
Mac OS X - v10.11.6

**Comment by Cipher-geek-Studios** [comment] 2017-01-10 11:19
Thanks overwriting the setting page helped me thanks.
 `"emmet.syntaxProfiles": { "javascript": "html" }`

**Comment by danfma** [comment] 2017-01-11 03:00
Hey guys, this doesn´t work for tsx files. I tried with typescript, typescriptreact and javascript.

```json
"emmet.syntaxProfiles": {
	"javascript": "jsx",
	"typescript": "jsx",
	"typescriptreact": "jsx"
}
```

**Comment by vernondegoede** [comment] 2017-01-14 15:30
@johnpeele Did you set any other options to get this working properly? Typing `div` and pressing tab results in inserting `HTMLDivElement`

However, typing `div.test` results in `<div className="test"></div>`.

**Comment by yogeshlonkar** [comment] 2017-01-17 04:39
for HTML code in tsx file (Inside render's return) I can't get single quote attributes by setting
```
"emmet.syntaxProfiles": {
    "typescriptreact": {
        "attr_quotes": "single"
    }
}
```
this doesn't work. But If i put below in settings it works
```
"emmet.syntaxProfiles": {
    "xml": {
        "attr_quotes": "single"
    }
}
```
is it expected behavior?

**Comment by johnpeele** [comment] 2017-01-17 15:54
@vernondegoede Here are my Emmet settings:

```
"emmet.syntaxProfiles": {
    "javascript": "jsx",
    "xml": {
        "attr_quotes": "single"
    }
}
```

Here is a screencap of me using tab expansion in a `.js` file:
![kapture 2017-01-17 at 10 52 23](https://cloud.githubusercontent.com/assets/84169/22027830/0e1a8e54-dca3-11e6-98cb-eb0144350113.gif)

I am also using the [Sublime Babel grammar](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) for my JSX files.

**Comment by vernondegoede** [comment] 2017-01-19 07:20
@johnpeele Thank you so much! This works like a charm.

**Comment by admmasters** [comment] 2017-02-08 10:37
@danfma have you managed to get emmet expansion working in tsx?

**Comment by admmasters** [comment] 2017-02-08 10:38
@egamma this doesn't seem to be working with tsx.

**Comment by cAstraea** [comment] 2017-02-10 09:42
How can I add more ? 
Doing something like
"emmet.syntaxProfiles": {
    "javascript": "jsx,vue",
.....} 
doesn't seem to work

**Comment by egamma** [comment] 2017-02-10 16:31
>@danfma have you managed to get emmet expansion working in tsx?

Strictly speaking it is a separate issue, but I've reopened this one.

**Comment by ramya-rao-a** [comment] 2017-02-10 17:43
> for HTML code in tsx file (Inside render's return) I can't get single quote attributes 

@yogeshlonkar This issue was tracked in #16354 where you can read more about it. The fix is in the latest VS Code 1.9. Please give that a try.

> Typing div and pressing tab results in inserting HTMLDivElement However, typing div.test results in <div className="test"></div>.

@vernondegoede The HTMLDivElement is coming from autocomplete. Currently when you hit TAB, and there are suggestions in the completion items, then the selected suggestion gets expanded, emmet doesn't even get a chance to come in and play. #1952 is tracking this kind of problem. Please up vote and chime in there. As a workaround, you can press ESC to escape the suggestion and then press TAB so that emmet expansion can take place, or assign a different keybinding for emmet.

> How can I add more ?

@cAstraea At the moment you cannot map more than a single language mode. Can you open a separate issue and elaborate your use case?

@admmasters Emmet expansions are working fine in .tsx files. For it to work in .ts files you need to either map "typescript" to "jsx" in emmet.syntaxProfiles or change language mode to tyspescriptreact

**Comment by caiolopes** [comment] 2017-02-14 17:04
The feature "updateTag" is not working when language mode is JavaScript React, only HTML.. And it is so useful for adding a class, etc, in an already existing component.

**Comment by ramya-rao-a** [comment] 2017-02-15 05:01
@caiolopes I can repro that. Pardon me, I am new to emmet. Is this is regression? Was it ever working before?

**Comment by caiolopes** [comment] 2017-02-15 12:58
@ramya-rao-a Here is a screencast.. I don't know if it was ever working before.. But actually it is working if the language mode is HTML.
![emmet-vscode-updatetag](https://cloud.githubusercontent.com/assets/4184169/22975291/5580037e-f36d-11e6-825c-c5ce546be008.gif)

**Comment by ramya-rao-a** [comment] 2017-02-20 19:43
Created separate issue for the problem with Update Tag feature with jsx. #20953 
Closing this current issue as emmet expansion works just file for jsx and tsx and we haven't heard back anything supporting otherwise

**Closed by ramya-rao-a** 2017-02-20 19:43 UTC
Labels: javascript, needs more info

**Comment by orangemooncreative** [comment] 2017-06-01 20:02
does anyone have an idea why even after updating my emmet syntax profile my class expansion is class and not className? here is a gif of my settings and my expansion.
http://cloud.orangemooncreative.com/401H2z3c2G0T

**Comment by ramya-rao-a** [comment] 2017-06-01 22:22
First off, thanks for trying out the new emmet @orangemooncreative 

The className issue is being tracked here: https://github.com/emmetio/expand-abbreviation/issues/2

**Comment by ramya-rao-a** [comment] 2017-06-01 23:14
@orangemooncreative The className issue is fixed with https://github.com/Microsoft/vscode/commit/02783b149c99cc6e8b7f066d4660cec0d4c361d6 and you should be able to see the fix in tomorrow's insiders

**Comment by ramya-rao-a** [comment] 2017-08-10 17:03
Hey All,

From VS Code 1.15 onwards, please use `emmet.includeLanguages` instead of `emmet.syntaxProfiles` to get Emmet abbreviation expansion features in your language of choice.

We are making this move because of the confusion around what `emmet.syntaxProfiles` setting was originally meant for i.e [Customizing final output](https://docs.emmet.io/customization/syntax-profiles/) and what it became i.e enabling emmet in new languages.

Please read more on this at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

**Comment by MrZhang123** [comment] 2017-08-11 02:49
@ramya-rao-a Hi , I use VS Code 1.15 , I set the emmet
```
"emmet.includeLanguages": {
    "javascript": "javascriptreact",
}
```
but in my reactjs file , i use emmet to click Tab ,  but it not work , how to fix it ?

**Comment by ramya-rao-a** [comment] 2017-08-11 06:57
@MrZhang123 Do you have `editor.quickSuggestions` disabled? If not, then you should have been able to get emmet abbreviation in the suggestion list. Selection it will expand the abbreviation.

Read [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) for more on this

**Comment by bigkrp** [comment] 2017-08-11 07:52
After update to x64 emmet stop to support custom components
![default](https://user-images.githubusercontent.com/11586744/29205026-028bf866-7e83-11e7-97bb-d46d28f9f46f.JPG)

When i tried tab - nothing happens. But befor installation x64 version of visual code - it worked well

**Comment by EQuimper** [comment] 2017-08-11 16:12
Get same problem, all was working before this version and now emmet break with my component. I did the change like you say in the docs but ...

**Comment by ramya-rao-a** [comment] 2017-08-11 18:33
Follow the issue number 32243 for the tab issue.

Emmet suggestions for simple words that are not abbreviations themselves will not show up. Otherwise you will end up with emmet suggestion for every word you type.

`MyComponent>Text` will expand to the below though
```
<MyComponent>
    <Text></Text>
</MyComponent>
``

**Comment by EQuimper** [comment] 2017-08-11 20:00
@ramya-rao-a It's still not work. I mean just even the simple MyComponent. I don't know if this is the tab don't work but I add the 

```
"emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
``` 

But that still not work. Maybe I miss something. I read the other issue but nothing really help.

**Comment by ramya-rao-a** [comment] 2017-08-11 20:39
@EQuimper Did you try `MyComponent>Text`? Have you disabled `editor.quickSuggestions` ?

Tab for emmet is now available in the VS Code Insiders build. You can try it from https://code.visualstudio.com/insiders

**Comment by EQuimper** [comment] 2017-08-11 21:08
I just did and install insiders and remove the quicksuggestions and don't work.

```
// Place your settings in this file to overwrite the default settings
{
  "editor.fontSize": 14,
  "editor.tabSize": 2,
  "editor.fontFamily": "Monaco",
  // "editor.fontFamily": "Hasklig",
  "editor.wordWrapColumn": 80,
  "editor.fontLigatures": true,
  "editor.snippetSuggestions": "top",
  "editor.minimap.enabled": true,
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.DS_Store": true,
    "**/node_modules": true,
    "**/.idea": true,
    "**/.vscode": false,
    "**/yarn.lock": true,
    "**/tmp": true
  },
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true,
    "**/tmp": true
  },
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
    // "javascript": "javascript"
  },
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/.git": true,
    "**/.DS_Store": true,
    "**/tmp": true,
    "**/coverage": true,
    "**/ios": true,
    "**/android": true,
    "_build": true,
    "deps": true
  },
  "files.trimTrailingWhitespace": true,
  "html.suggest.html5": true,
  "npm-intellisense.scanDevDependencies": true,
  "stylelint.enable": true,
  // "typescript.check.tscVersion": false,
  "window.zoomLevel": 0,
  "terminal.integrated.shell.osx": "/bin/zsh",
  "javascript.validate.enable": false,
  "extensions.autoUpdate": true,
  "terminal.integrated.fontSize": 13,
  "terminal.integrated.cursorStyle": "line",
"sync.gist": "95e4cfd731754a9c023d59c0538fa6e6",
"sync.lastUpload": "",
"sync.autoDownload": false,
"sync.autoUpload": false,
"sync.lastDownload": "2017-08-11T20:58:30.447Z",
"sync.forceDownload": false,
"sync.anonymousGist": false,
  "color-highlight.markerType": "outline",
  "vsicons.projectDetection.disableDetect": true,
  "vsicons.dontShowNewVersionMessage": true,
  "fileHeaderCommentHelper.languageConfigs": {
    "language_javascript": {
      "template": [
        "/**",
        " * Project: $(projectName)",
        " * File: $(currentFile)",
        " * Author: Emanuel Quimper",
        " */"
      ]
    }
  },
  // "workbench.welcome.enabled": false,
  "workbench.iconTheme": "material-icon-theme",
  "material-icon-theme.showUpdateMessage": false,
"sync.host": "",
"sync.pathPrefix": "",
  "eslint.autoFixOnSave": true,
  "editor.formatOnSave": false,
  "editor.renderIndentGuides": true,
  "prettier.singleQuote": true,
  "prettier.printWidth": 80,
  "prettier.trailingComma": "all",
  "prettier.semi": true,
  "prettier.useTabs": false,
  "prettier.bracketSpacing": true,
"sync.quietSync": false,
  "files.associations": {
    "*.gohtml": "html"
  },
  "git.enableSmartCommit": true,
  "flow.useNPMPackagedFlow": true,
"sync.askGistName": false,
  "extensions.ignoreRecommendations": true,
  "editor.autoIndent": true,
  // "emmet.showExpandedAbbreviation": "never",
  "editor.quickSuggestions": false
}
```

**Comment by ramya-rao-a** [comment] 2017-08-11 21:12
@EQuimper Set `emmet.triggerExpansionOnTab` to `true to get tab working. Sorry forgot to mention that in the previous comment.

You don't have to set `editor.quickSuggestions` to `false`. If you set that to `true` then you will see emmet in suggestion list as well where you can see the preview for the expanded value

**Comment by EQuimper** [comment] 2017-08-11 21:16
Good work with that thank you :)

**Comment by goncy** [comment] 2017-08-12 07:04
Like is commented on this update https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0

```An important change is that the Tab key is no longer the dedicated keyboard shortcut for expanding Emmet abbreviations. Instead, Emmet abbreviations will now appear in the suggestion list. They can be selected like any other smart completion and on selection, the abbreviation will be expanded.

This may take some getting used to but we think you'll see the benefits of Emmet abbreviations being treated as suggestions or smart completions. You can still bind any keyboard shortcut (other than Tab key) to the editor.emmet.action.expandAbbreviation command or use Emmet: Expand Abbreviation from the Command Palette.```

So, if you want to mantain the old behavior (for example, for autocompleting JSX components), you have to go to `preferences > keyboard shorcuts`, find `Emmet: Expand abbreviation` and map it to tab, like this:

![image](https://user-images.githubusercontent.com/6494462/29238835-2b48b9fa-7f3d-11e7-8521-e24f3ef4876b.png)

There you go :)

**Comment by ramya-rao-a** [comment] 2017-08-12 18:18
@goncy Mapping to tab that way in VS Code 1.15 has problems of its own as there is no fallback to the real tab (indenting) when there is no valid emmet abbreviation to expand.

For example, with that setting you will never be able to just tab expecting an indent. You will end up getting warning message that says something like "Running emmet failed.. ".

Here are your options
- If on VS Code 1.15 use emmet from suggestions, bind any other keyboard shortcut (other than tab)  for the emmet expand command
- If on VS Code 1.16 Insiders build (you can get it from https://code.visualstudio.com/insiders), then set `emmet.triggerExpansionOnTab` to `true`. The appropriate fallback for tab exists.

We really wanted to move away from using tab for emmet due to the problems it brings for non emmet users. But there has been feedback requesting the tab->emmet feature back, and so it is now available in the latest Insiders

**Comment by tuoxiansp** [comment] 2017-08-16 06:12
This works for me.
```json
{
        "key": "tab",
        "command": "editor.emmet.action.expandAbbreviation",
        "when": "suggestWidgetVisible"
}
```

**Comment by MrZhang123** [comment] 2017-08-17 07:38
@tuoxiansp how to setting this ?

**Comment by tuoxiansp** [comment] 2017-08-17 07:42
@MrZhang123

**Comment by ramya-rao-a** [comment] 2017-08-17 15:55
@tuoxiansp I wouldn't suggest to do that. You will not be able to select anything from the suggestion list using tab if you do that I believe

**Comment by tuoxiansp** [comment] 2017-08-18 08:32
@ramya-rao-a 
Yeah, it's not the elegant way.

**Comment by MrZhang123** [comment] 2017-08-19 07:38
@ramya-rao-a the new version 1.15.1 fix it , that's great😁

**Comment by rmichnik** [comment] 2017-08-21 23:50
This did the trick:

"emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },

VSCode: 1.15.0
Macos: 10.12.6 (16G29)

**Comment by MrZhang123** [comment] 2017-08-22 01:42
@rmichnik you need update new version 1.15.1 , this bug fixed

**Comment by fpigeonjr** [comment] 2017-08-31 04:47
thanks @rmichnik. Confirmed working on macOSX and VSCode 1.15.1

**Comment by antoniandre** [comment] 2017-09-12 03:22
I have the config "emmet.triggerExpansionOnTab": true and I replaced the tab key in keybindings with ctrl+e (like in ST3) so I can keep my tab key to tab :)

**Comment by EQuimper** [comment] 2017-09-12 04:14
It's only me or the first component I can tab and get the autocomplete, but the second one who is inside this the other one never work. Before all was perfect but now ...

**Comment by ramya-rao-a** [comment] 2017-09-12 04:27
@EQuimper That looks wrong but I can't repro. Can you log a new issue with repro steps?
The video helps but I need the exact steps and the keys you pressed

**Comment by bullyork** [comment] 2017-09-15 03:53
VScode Version 1.16 
the setting key has changed
so you should setting it as follows

"emmet.includeLanguages": {
        "javascript": "jsx",
        "xml": {
            "attr_quotes": "single"
        }
    },

**Comment by beholderrk** [comment] 2017-09-15 10:23
@EQuimper same problem.
https://drive.google.com/open?id=0B36wDAJfXOa0LVoySzV5MkZKblE

**Comment by ramya-rao-a** [comment] 2017-09-15 16:26
@beholderrk Can you upgrade to 1.16 and see if you still have the issue?
@EQuimper Are you on 1.15.1 too?
@bullyork The right hand side should be `javascriptreact` in your setting for `emmet.includeLanguages`

**Comment by EQuimper** [comment] 2017-09-15 16:31
No i'm on the insiders version @ramya-rao-a v17

```
{
  // Place your settings in this file to overwrite the default settings
  "editor.fontSize": 18,
  "editor.tabSize": 2,
  "editor.fontFamily": "Operator Mono",
  // "editor.fontFamily": "Inconsolata",
  // "editor.fontFamily": "Menlo",
  "editor.wordWrapColumn": 80,
  "editor.fontLigatures": true,
  "editor.snippetSuggestions": "top",
  "editor.minimap.enabled": true,
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.DS_Store": true,
    "**/node_modules": true,
    "**/.idea": true,
    "**/.vscode": false,
    "**/yarn.lock": true,
    "**/tmp": true
  },
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true,
    "**/tmp": true
  },
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/.git": true,
    "**/.DS_Store": true,
    "**/tmp": true,
    "**/coverage": true,
    "**/ios": true,
    "**/android": true,
    "_build": true,
    "deps": true
  },
  "files.trimTrailingWhitespace": true,
  "html.suggest.html5": true,
  "npm-intellisense.scanDevDependencies": true,
  "stylelint.enable": true,
  // "typescript.check.tscVersion": false,
  "window.zoomLevel": 0,
  "terminal.integrated.shell.osx": "/bin/zsh",
  "javascript.validate.enable": false,
  "extensions.autoUpdate": true,
  "terminal.integrated.fontSize": 13,
  "terminal.integrated.cursorStyle": "line",
  "sync.gist": "95e4cfd731754a9c023d59c0538fa6e6",
  "sync.lastUpload": "",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.lastDownload": "2017-08-11T20:58:30.447Z",
  "sync.forceDownload": false,
  "sync.anonymousGist": false,
  "color-highlight.markerType": "outline",
  "vsicons.projectDetection.disableDetect": true,
  "vsicons.dontShowNewVersionMessage": true,
  "fileHeaderCommentHelper.languageConfigs": {
    "language_javascript": {
      "template": [
        "/**",
        " * Project: $(projectName)",
        " * File: $(currentFile)",
        " * Author: Emanuel Quimper",
        " */"
      ]
    }
  },
  // "workbench.welcome.enabled": false,
  "workbench.iconTheme": "material-icon-theme",
  "material-icon-theme.showUpdateMessage": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "eslint.autoFixOnSave": true,
  "editor.formatOnSave": false,
  "editor.renderIndentGuides": true,
  "prettier.singleQuote": true,
  "prettier.printWidth": 80,
  "prettier.trailingComma": "all",
  "prettier.semi": true,
  "prettier.useTabs": false,
  "prettier.bracketSpacing": true,
  "sync.quietSync": false,
  "files.associations": {
    "*.gohtml": "html"
  },
  "git.enableSmartCommit": true,
  "flow.useNPMPackagedFlow": true,
  "sync.askGistName": false,
  "extensions.ignoreRecommendations": true,
  "editor.autoIndent": true,
  // "emmet.showExpandedAbbreviation": "never",
  // "editor.quickSuggestions": false,
  "emmet.triggerExpansionOnTab": true,
  "workbench.startupEditor": "newUntitledFile",
  "vscode_custom_css.imports": [
    "file:///Users/equimper/coding/customStuff/custom.css"
  ],
  "workbench.colorTheme": "One Monokai"
}
```

**Comment by ramya-rao-a** [comment] 2017-09-15 18:23
@EQuimper I copied all your settings and I still can't repro.
Can you run `code-insiders --disable-extensions` and then see if you can still repro?
It might be the case that some other extension is interfering.

**Comment by EQuimper** [comment] 2017-09-18 15:08
@ramya-rao-a So have test with the disable extensions options and all work. Which kind of extensions can interfering with emmet ? :)

**Comment by EQuimper** [comment] 2017-09-18 15:29
Ok now work after disable this extensions https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode

**Comment by beholderrk** [comment] 2017-09-19 08:17
@ramya-rao-a @EQuimper wow thanks! The problem was precisely in this extention.

**Comment by ramya-rao-a** [comment] 2017-09-21 22:29
@EQuimper @beholderrk Add the below in your settings and Emmet should work as expected inside the nested tag when using the babel extension
```
"emmet.includeLanguages": {
      "jsx-sublime-babel-tags": "javascriptreact"
  }
```

**Comment by EQuimper** [comment] 2017-09-22 15:46
@ramya-rao-a thank you :)
