### ISSUE TITLE
How to add indentation guide lines?

### ISSUE THREAD

**Issue by XianwuLin** [Microsoft/vscode#5299] opened 2016-04-15 05:43 UTC
- VSCode Version: 0.10.11
- OS Version: win10 x64

I am a python programmer, and I wan't to add indentation guide lines like this:
![ indentation guide lines](http://wesbos.com/wp-content/uploads/2013/07/ss-2013-07-24-at-4.02.52-PM.png)

What should I do? or what plug-ins can achieve this effect?

Thanks a lot

**Comment by egamma** [comment] 2016-04-15 06:53
Duplicate of #2192.

There is an extension https://marketplace.visualstudio.com/items?itemName=spywhere.guides.

**Closed by egamma** 2016-04-15 06:53 UTC

**Comment by nojvek** [comment] 2016-05-23 16:11
The extension is awesome, but should this be part of the core installation? 

Seems like a feature that should be baked in by default? Notepad++ and sublime both have it.

Or are there plans to bundle some plugins by default in VSCode?

**Comment by XianwuLin** [comment] 2016-05-27 05:21
thanks, solve my problem.
