### ISSUE TITLE
Cannot edit more than 10000 lines in "column edit mode"

### ISSUE THREAD

**Issue by olibraun** [microsoft/vscode#80324] opened 2019-09-04 15:05 UTC
Hello everyone,
I am having trouble editing a large file with a "column cursor".

- VSCode Version: 1.37.1
- OS Version: Windows 10 (10.0.17763)

Steps to Reproduce:

1. Open a file with more than 10000 lines
2. Try to create a "column cursor"/"multiline cursor", i.e. try to edit all lines at once.
3. A message stating "The number of cursors has been limited to 10000."

![image](https://user-images.githubusercontent.com/29063670/64267101-14766d80-cf36-11e9-869e-28fcb5176a36.png)

How can I fix this in order to edit the entire file?

**Comment by rebornix** [comment] 2019-09-04 20:30
duplicate of https://github.com/microsoft/vscode/issues/60713

**Closed** 2019-09-04 20:30 UTC
Labels: *duplicate

**Comment by olibraun** [comment] 2019-09-05 05:55
@rebornix I agree that this is a duplicate of issue #60713
Thank you for pointing this out.

However, the duplicate issue does not contain a fix - merely a statement akin to "this is as designed".
I think this issue is ciritical because I want to keep using VSCode for my work and a task such as editing a large file is quite common.
In addition, I see no reason why the limitation described in this issue should be necessary.

Please reconsider creating a fix or an option to increase the number of cursors.
