### ISSUE TITLE
Support release notes in the Outline view

### ISSUE THREAD

**Issue by legowerewolf** [microsoft/vscode#232605] opened 2024-10-30 13:40 UTC
![Image](https://github.com/user-attachments/assets/7aac4192-a83b-4f87-aab0-59c6f1ccfbba)

I want the Outline panel to have a table of contents (like Markdown files do, for example) when I'm looking at the release notes.

**Comment by mjbvz** [comment] 2024-10-30 20:54
Duplicate of #148889

**Closed** 2024-12-10 23:32 UTC
Labels: feature-request, markdown, outline
