### ISSUE TITLE
can get output of activeTextEditor of vscode as html?

### ISSUE THREAD

**Issue by Arshiamidos** [microsoft/vscode#79395] opened 2019-08-18 14:14 UTC
sorry guys but it's unanswered question , can you help me?

https://github.com/microsoft/vscode/pull/66418

**Comment by gjsjohnmurray** [comment] 2019-08-18 17:46
/duplicate of your own question at https://github.com/microsoft/vscode/pull/66418#issuecomment-522332617

Please look for follow up there, and be patient.

**Closed** 2019-08-18 17:46 UTC
Labels: *duplicate
