### ISSUE TITLE
Crash after resuming from sleep

### ISSUE THREAD

**Issue by ciaranschutte** [Microsoft/vscode#8837] opened 2016-07-07 14:27 UTC
- VSCode Version: 1.2.1
- OS Version: 10.10.5

Steps to Reproduce:

1. Put Mac to sleep
2. Resume next day, VSCode has crashed

**Comment by Spown** [comment] 2016-07-08 05:44
#6417

**Comment by joaomoreno** [comment] 2016-07-08 08:01
Closing as duplicate of #6417

**Closed by joaomoreno** 2016-07-08 08:01 UTC
