### ISSUE TITLE
DEBUG CONSOLE AUTO SCROLL DOWN

### ISSUE THREAD

**Issue by antillgrp** [microsoft/vscode#131999] opened 2021-08-31 18:40 UTC
DEBUG CONSOLE AUTO SCROLL DOWN

DEBUG CONSOLE AUTO SCROLL DOWN

**Comment by IllusionMH** [comment] 2021-08-31 19:10
/needsMoreInfo

Please provide correct description of issue or request

**Comment by lramos15** [comment] 2021-09-07 15:07
Closing as duplicate of #117674 feel free to correct me if I'm wrong and we can revisit this issue.

**Closed** 2021-09-07 15:07 UTC
Labels: needs more info
