### ISSUE TITLE
[Insiders] installing an extension via command line failure

### ISSUE THREAD

**Issue by jramsay** [Microsoft/vscode#59375] opened 2018-09-25 20:12 UTC
Version: 1.28.0-insider (user setup)
Commit: fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66
Date: 2018-09-25T05:31:33.193Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS: Windows 10

Steps to Reproduce:

1. Attempt to install the VS Live Share extension via the command line in insiders (our CI tests use this set up) fails with the following:

code-insiders --install-extension "C:\Users\jasonra.REDMOND\Desktop\vsliveshare-0.3.733-insiders.vsix"
**diagnostic_channel_1.channel.unsubscribe is not a function**

It installs successfully on stable:

>code --install-extension "C:\Users\jasonra.REDMOND\Desktop\vsliveshare-0.3.733-insiders.vsix"
[createInstance] extensionManagementService depends on downloadService which is NOT registered.
Extension 'vsliveshare-0.3.733-insiders.vsix' was successfully installed!

**Comment by sandy081** [comment] 2018-09-26 08:58
Duplicate of #59212

**Closed** 2018-09-26 08:58 UTC
Labels: *duplicate, extensions
