### ISSUE TITLE
Search does not work with folder names having square brackets

### ISSUE THREAD

**Issue by sneko** [microsoft/vscode#171411] opened 2023-01-16 11:29 UTC
- VS Code Version: Version: 1.74.3
- OS Version: MacOS Ventura

With the new Next.js v13 and its `appDir` structure they use the folder structure to manage routes, so it's likely a lot of folders look like:
- `(noEffectOnRouter)`
- `[dynamicParameterId]`

(for routes like `/(private)/users/[userId]/page.tsx`)

But with square brackets the `vscode` search is totally broken and just ignores the folder and nested folders.

Steps to Reproduce:

1. Create 3 level of folders, create a file with `hello` as content in the deepest folder
2. The 2nd level folder must be named `[exampleId]`
3. Search on the 1st level folder for `hello` content

Any idea to workaround this?

Thank you,

**Comment by gjsjohnmurray** [comment] 2023-01-16 13:58
Does https://github.com/microsoft/vscode/issues/168715#issuecomment-1345409463 help?

**Comment by sneko** [comment] 2023-01-16 14:03
@gjsjohnmurray manually adding this into `files to include` to escape works.

But when clicking from the files tree, I don't want to waste time adding workaround 2*X times (if X nested folders with square brackets).

<img width="528" alt="image" src="https://user-images.githubusercontent.com/8195958/212695985-eb250aa4-0a4f-4bab-9012-d50c7eed33d2.png">

**Comment by gjsjohnmurray** [comment] 2023-01-16 14:10
The fields are interpreted as glob patterns. PR #166318 proposes escaping the special characters when that context menu transfers the path into the field.

**Comment by davidnx** [comment] 2023-01-26 13:16
Duplicate of #82415

**Closed** 2023-02-03 19:03 UTC
Labels: bug, search
