### ISSUE TITLE
(WinKey + .) input bug

### ISSUE THREAD

**Issue by workHardCS** [microsoft/vscode#115969] opened 2021-02-06 12:55 UTC
Issue Type: <b>Bug</b>

hi, when i try to use (WinKey + . )  the emojis/symbols wont show after i click them until i will close the  (WinKey + . ) window.
it not the same as other txt editors.
is this bug?

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

**Comment by benc-uk** [comment] 2021-02-12 13:50
I have the same problem

This is a regression in v1.53 as it used to work just fine

**Comment by alexdima** [comment] 2021-02-15 08:54
@workHardCS @benc-uk I cannot reproduce. This works fine for me:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/107924777-cca1a580-6f73-11eb-9e25-289801ab8ff6.gif)

**Comment by benc-uk** [comment] 2021-02-15 09:00
It really doesn't work here!

![Video_2021-02-15_085812](https://user-images.githubusercontent.com/14982936/107925365-4170e180-6f6c-11eb-85fb-41cdf93836bb.gif)

**Comment by workHardCS** [comment] 2021-02-20 16:08
> It really doesn't work here!
> 
> No emoji you enter will appear until after you close the dialog, this is only affecting VS Code
> 
> ![Video_2021-02-15_085812](https://user-images.githubusercontent.com/14982936/107925365-4170e180-6f6c-11eb-85fb-41cdf93836bb.gif)

the same with me

**Comment by buster95** [comment] 2021-02-25 14:26
same when I put emoji using `Win + . `, it's really really slow

**Comment by alexdima** [comment] 2021-02-25 14:44
I can reproduce in Stable, but not anymore in Insiders.

### stable reproduces:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/109169441-1a8e8880-7780-11eb-8fc9-cc7d5ae93ba5.gif)

### insiders works OK:.

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/109169644-4f9adb00-7780-11eb-8012-86e4b036a138.gif)

So this will be fixed with our new stable release or you can try using insiders from https://code.visualstudio.com/insiders/

**Closed by alexdima** 2021-02-25 14:44 UTC
Labels: needs more info, windows
