### ISSUE TITLE
Cannot exit visual studio

### ISSUE THREAD

**Issue by pulkitsinghal** [Microsoft/vscode#11117] opened 2016-08-29 16:47 UTC
- VSCode Version: `1.4.0`
- OS Version: `10.11.6 (15G31)`

Steps to Reproduce:

1. Open Terminal
2. run `code .`
3. quit visual studio
4. dock still shows icon and cannot `force quit`, it even blocks restart because process cannot be killed but there are no more processes named `code` or `code helper` in the `Activity Monitor`

<img width="95" alt="screenshot 2016-08-29 11 54 29" src="https://cloud.githubusercontent.com/assets/821963/18059613/6114bea0-6ddf-11e6-9bc3-458d545045d5.png">

**Comment by bpasero** [comment] 2016-08-30 04:29
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by pulkitsinghal** [comment] 2016-08-31 00:44
@bpasero - thank you for your response.

1. I tried from terminal with: `code --disable-extensions`
1. I exited with `Code > Quit Visual Studio Code`
1. But I still have the same problem
<img width="185" alt="screen shot 2016-08-30 at 7 43 42 pm" src="https://cloud.githubusercontent.com/assets/821963/18112024/116594f4-6eea-11e6-8d10-f808535cd658.png">

**Comment by bpasero** [comment] 2016-08-31 04:33
Can we try with our insider release?

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment] 2016-09-06 05:38
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-09-06 05:38 UTC
Labels: bug, needs more info, workbench
