### ISSUE TITLE
Debug Console issues when moved out of its own container

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109129] opened 2020-10-22 04:09 UTC
Update: changing to just be about the Debug Console
See https://github.com/microsoft/vscode/issues/109129#issuecomment-714210374 & https://github.com/microsoft/vscode/issues/109129#issuecomment-714645260

--- 

Smaller:
![image](https://user-images.githubusercontent.com/641685/96823358-58f2f000-13fa-11eb-9999-e538f8a82e01.png)

Larger:
![image](https://user-images.githubusercontent.com/641685/96823442-86d83480-13fa-11eb-99dc-d291ef8eb94c.png)

I think I'd prefer the full-width omnipresent filter box, regardless of the view width. Or make the filter box wider in the header and change the breakpoint so that it "wraps" only when its much smaller.

**Comment by eamodio** [comment] 2020-10-22 04:11
FYI, the Debug console doesn't have the same behavior -- its filter box is always in the header, and IMO too small.

![image](https://user-images.githubusercontent.com/641685/96823711-1251c580-13fb-11eb-888a-d056af8cd1f2.png)

/cc @isidorn

**Comment by isidorn** [comment] 2020-10-22 10:37
Yeah we just did not implement the resize in the debug console, as I was not super happy with how it behaves in Problems atm.
Default size of debug console filter we can increase. Currently it is 300px. What do you think would be a better fit?

**Comment by eamodio** [comment] 2020-10-22 17:28
300px looks good, but its only 300px once you start searching:

![image](https://user-images.githubusercontent.com/641685/96908214-4fa16c00-146a-11eb-8e8d-f804fc8c3afe.png)

You can also see above that the "badge" (showing x of x), is too big for the input (maybe the input can be expanded by a few pixels as well -- because it feels so tight.

It also seems like the filter box and the dropdown are too close and maybe a pixel off (or a pixel too big/small)

![image](https://user-images.githubusercontent.com/641685/96907693-96429680-1469-11eb-966c-7c32db8edf55.png)

And it breaks down further when smaller

![image](https://user-images.githubusercontent.com/641685/96907738-a6f30c80-1469-11eb-91c2-07a5c0d1eea2.png)

**Comment by sandy081** [comment] 2020-10-23 07:39
/duplicate

https://github.com/microsoft/vscode/issues/93584

**Comment by sandy081** [comment] 2020-10-23 07:40
Marking this as duplicate of existing issue for problems view. Please feel free to reopen for debug

**Closed** 2021-02-02 12:50 UTC
Labels: *out-of-scope, bug, debug
