### ISSUE TITLE
All Extensions become disabled after restarting

### ISSUE THREAD

**Issue by gtim108** [microsoft/vscode#130219] opened 2021-08-05 23:40 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60
- OS Version: Fedora 34

Steps to Reproduce:

1. Install Visual Studio Code Insiders v1.60
2. Start it.
3. All extensions are disabled
4. Can't enable them. But can uninstall, then install an extension. But it become disabled again after VSCode restart

**Comment by fiftythreejb** [comment] 2021-08-05 23:44
It seems that there may be an issue with several extensions not working with the update.
https://github.com/mkloubert/vscode-deploy-reloaded/issues/186?_pjax=%23repo-content-pjax-container

**Comment by jcamachott** [comment] 2021-08-05 23:47
Ok so I reverted to 1.58.2 but the only extension I got an error for was DeployReloaded. I was able to uninstall and reinstall, and it was enabled but gave me an error.

**Comment by antonblock** [comment] 2021-08-06 18:01
I'm seeing this too, all 23 extensions I have installed are disabled after upgrading. Switching to VS Code stable 1.59.0 unblocked me

**Comment by GavinRay97** [comment] 2021-08-06 18:45
Also seeing this, happened after `v1.60` auto-update.
Will try to post as much info as possible.

- I have ~80 extensions
- Most of them are in some sort of weird state where they can be neither enabled, or disabled
	- It's like if someone flipped a boolean to `2`
	- Will attach video showing the arbitrary ability to enable a small number of them
- OS Info:
	- ```
	  Edition	Windows 11 Home
	  Version	21H2
	  Installed on	‎7/‎11/‎2021
	  OS build	22000.120
	  Experience	Windows Feature Experience Pack 1000.22000.120.0
	  ```
- VS Code Insiders Info:
	- ```
	  Version: 1.60.0-insider (user setup)
	  Commit: 49af1cbe00271ac2ea36cfc5f7352fe31a7b0094
	  Date: 2021-08-06T06:41:50.275Z
	  Electron: 13.1.7
	  Chrome: 91.0.4472.124
	  Node.js: 14.16.0
	  V8: 9.1.269.36-electron.0
	  OS: Windows_NT x64 10.0.22000
	  ```

<details>
  <summary>CLICK TO SHOW LIST OF EXTENSIONS INSTALLED</summary>

```sh
rayga@DESKTOP-88A51E5 MSYS ~/.vscode-insiders/extensions
$ ls | tail -n 1000

ajshort.include-autocomplete-0.0.4/
asf.apache-netbeans-java-12.4.301/
augusterame.zls-vscode-1.0.4/
bradlc.vscode-tailwindcss-0.6.13/
bradymholt.pgformatter-1.17.0/
chad.nord-operator-theme-1.0.0/
dineug.vuerd-vscode-0.9.1/
dlasagno.wal-theme-1.0.4/
editorconfig.editorconfig-0.16.4/
esbenp.prettier-vscode-8.1.0/
fernandoescolar.vscode-solution-explorer-0.4.4/
fwcd.kotlin-0.2.23/
gavinray.reascript-0.0.5/
github.copilot-1.3.2277/
github.github-vscode-theme-4.1.1/
github.vscode-pull-request-github-0.29.0/
golang.go-nightly-2021.8.423/
grapecity.gc-excelviewer-3.0.42/
hbenl.vscode-test-explorer-2.20.4/
heybourn.headwind-1.7.0/
humao.rest-client-0.24.5/
ibm.output-colorizer-0.1.2/
ionide.ionide-fsharp-5.5.5/
ionide.ionide-fsharp-5.6.0/
ionide.ionide-fsharp-5.7.0/
ionide.ionide-fsharp-5.7.1/
ionutvmi.spacegray-vscode-1.2.6/
joaomoreno.github-sharp-theme-1.7.0/
koihik.vscode-lua-format-1.3.8/
llvm-vs-code-extensions.vscode-clangd-0.1.12/
matklad.rust-analyzer-0.3.618/
mhutchie.git-graph-1.30.0/
mikestead.dotenv-1.0.1/
ms-azuretools.vscode-docker-1.15.0/
ms-dotnettools.csharp-1.23.14/
ms-python.python-2021.5.746022950-dev/
ms-python.python-2021.5.768185786-dev/
ms-python.python-2021.6.854437722-dev/
ms-python.python-2021.6.944021595/
ms-python.python-2021.7.981196274-dev/
ms-python.python-2021.8.1060463485-dev/
ms-python.python-2021.8.1102490946/
ms-python.vscode-pylance-2021.4.3/
ms-python.vscode-pylance-2021.5.3-pre.1/
ms-python.vscode-pylance-2021.5.4-pre.1/
ms-python.vscode-pylance-2021.6.2/
ms-python.vscode-pylance-2021.6.3/
ms-python.vscode-pylance-2021.7.2/
ms-python.vscode-pylance-2021.7.7/
ms-python.vscode-pylance-2021.8.0/
ms-toolsai.jupyter-2021.6.751425733/
ms-toolsai.jupyter-2021.6.773625886/
ms-toolsai.jupyter-2021.6.775948001/
ms-toolsai.jupyter-2021.6.832913620/
ms-toolsai.jupyter-2021.6.834931520/
ms-toolsai.jupyter-2021.6.856262935/
ms-toolsai.jupyter-2021.6.859827477/
ms-toolsai.jupyter-2021.6.879154572/
ms-toolsai.jupyter-2021.7.942275039/
ms-toolsai.jupyter-2021.7.945818462/
ms-toolsai.jupyter-2021.7.960048241/
ms-toolsai.jupyter-2021.7.963708582/
ms-toolsai.jupyter-2021.7.967360642/
ms-toolsai.jupyter-2021.8.1081660962/
ms-toolsai.jupyter-2021.8.1091682718/
ms-toolsai.jupyter-2021.8.1195043623/
ms-vscode.cmake-tools-1.7.0/
ms-vscode.cmake-tools-1.7.2/
ms-vscode.cmake-tools-1.7.3/
ms-vscode.cpptools-1.2.2-insiders2/
ms-vscode.cpptools-1.5.1/
ms-vscode.cpptools-themes-1.0.0/
ms-vscode.makefile-tools-0.2.1/
ms-vscode.makefile-tools-0.2.2/
ms-vscode.test-adapter-converter-0.1.2/
ms-vscode.vscode-typescript-next-4.3.20210420/
ms-vscode.vscode-typescript-next-4.3.20210422/
ms-vscode.vscode-typescript-next-4.4.20210511/
ms-vscode.vscode-typescript-next-4.4.20210518/
ms-vscode.vscode-typescript-next-4.4.20210519/
ms-vscode.vscode-typescript-next-4.4.20210525/
ms-vscode.vscode-typescript-next-4.4.20210616/
ms-vscode.vscode-typescript-next-4.4.20210622/
ms-vscode.vscode-typescript-next-4.4.20210624/
ms-vscode.vscode-typescript-next-4.4.20210801/
ms-vscode.vscode-typescript-next-4.4.20210802/
ms-vscode.vscode-typescript-next-4.4.20210803/
ms-vscode.vscode-typescript-next-4.4.20210805/
ms-vscode-remote.remote-containers-0.167.0/
ms-vscode-remote.remote-containers-0.170.0/
ms-vscode-remote.remote-containers-0.190.0/
ms-vscode-remote.remote-containers-0.191.0/
ms-vscode-remote.remote-wsl-0.53.2/
ms-vscode-remote.remote-wsl-0.56.0/
ms-vscode-remote.remote-wsl-0.58.2/
navelpluisje.reaper-0.3.10/
nimsaem.nimvscode-0.1.25/
octref.vetur-0.34.1/
oracle-labs-graalvm.graalvm-0.5.9/
pflannery.vscode-versionlens-1.0.9/
quicktype.quicktype-12.0.46/
redhat.java-0.80.2/
redhat.vscode-commons-0.0.6/
redhat.vscode-microprofile-0.3.0/
redhat.vscode-quarkus-1.9.0/
redhat.vscode-xml-0.17.0/
redhat.vscode-yaml-0.18.0/
redhat.vscode-yaml-0.19.0/
redhat.vscode-yaml-0.22.0/
richardwillis.vscode-gradle-3.6.1/
scala-lang.scala-0.5.4/
scalameta.metals-1.10.8/
serayuzgur.crates-0.5.8/
serayuzgur.crates-0.5.9/
sterin.msbuild-tools-0.0.12/
sumneko.lua-1.21.2/
sumneko.lua-2.0.1/
sumneko.lua-2.0.2/
sumneko.lua-2.0.3/
sumneko.lua-2.3.4/
takumii.markdowntable-0.6.0/
tamasfe.even-better-toml-0.14.2/
tangzx.emmylua-0.3.49/
tiehuis.zig-0.2.5/
timonwong.shellcheck-0.15.2/
twxs.cmake-0.0.17/
usernamehw.errorlens-3.4.0/
visualstudioexptteam.vscodeintellicode-1.2.14/
vscjava.vscode-java-debug-0.35.0/
vscjava.vscode-java-dependency-0.18.6/
vscjava.vscode-java-pack-0.18.2/
vscjava.vscode-java-test-0.31.0/
vscjava.vscode-maven-0.32.1/
vscjava.vscode-maven-0.32.2/
wallabyjs.quokka-vscode-1.0.357/
wallabyjs.quokka-vscode-1.0.358/
wallabyjs.quokka-vscode-1.0.363/
wallabyjs.quokka-vscode-1.0.364/
wallabyjs.quokka-vscode-1.0.365/
wallabyjs.quokka-vscode-1.0.367/
wallabyjs.quokka-vscode-1.0.380/
wallabyjs.quokka-vscode-1.0.386/
wallabyjs.quokka-vscode-1.0.389/
webfreak.code-d-0.23.0-beta.2/
whizkydee.material-palenight-theme-2.0.2/
will-stone.plastic-7.3.0/
yzhang.markdown-all-in-one-3.4.0/
zhuangtongfa.material-theme-3.11.3/
```
</details>

<details>
  <summary>CLICK TO SHOW USER SETTINGS JSON</summary>

```json
{
  "extensions.autoUpdate": true,

  // EDITOR
  "editor.formatOnSave": true,
  "editor.suggestSelection": "first",
  "editor.tabSize": 2,
  "editor.semanticHighlighting.enabled": true,
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.organizeImports": true
  },
  // "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook"
  },
  "git.path": "C:\\Program Files\\cmder\\vendor\\git-for-windows\\cmd\\git.exe",

  // C/C++
  "cmake.configureOnOpen": false,

  "C_Cpp.updateChannel": "Insiders",
  "C_Cpp.intelliSenseEngine": "Disabled",
  "C_Cpp.default.cppStandard": "c++20",
  "C_Cpp.clang_format_style": "WebKit",
  "clangd.onConfigChanged": "restart",
  "clangd.checkUpdates": true,

  "clangd.path": "C:\\Program Files\\LLVM\\bin\\clangd.exe",
  "clangd.arguments": ["--fallback-style=WebKit"],
  "clangd.semanticHighlighting": true,
  "clangd.serverCompletionRanking": true,

  "cmake.buildDirectory": "${workspaceFolder}/build/${buildKit}/${buildType}",
  "cmake.copyCompileCommands": "${workspaceFolder}/compile_commands.json",

  // C#
  "csharp.semanticHighlighting.enabled": true,
  "omnisharp.enableImportCompletion": true,
  "omnisharp.enableRoslynAnalyzers": true,
  "omnisharp.organizeImportsOnFormat": true,

  // D
  "serve-d.trace.server": "verbose",
  "d.servedPath": "C:\\Users\\rayga\\AppData\\Roaming\\code-d\\bin\\serve-d.exe",
  "d.argumentSnippets": true,
  "d.dmdPath": "ldmd2",
  "d.enableDMDImportTiming": false,
  "d.stdlibPath": [
    "C:\\D\\dmd-2.095.1\\src\\druntime\\import",
    "C:\\D\\dmd-2.095.1\\src\\phobos"
  ],
  "d.dubCompiler": "ldc2",
  "d.servedReleaseChannel": "nightly",
  "d.dcdClientPath": "C:\\Users\\rayga\\AppData\\Roaming\\code-d\\bin\\DCD\\bin\\dcd-client.exe",
  "d.dcdServerPath": "C:\\Users\\rayga\\AppData\\Roaming\\code-d\\bin\\DCD\\bin\\dcd-server.exe",

  // LUA
  "emmylua.codeLens": true,
  "Lua.hint.enable": true,
  "Lua.hint.setType": true,

  // GO
  "go.editorContextMenuCommands": {
    "addImport": true,
    "addTags": true,
    "benchmarkAtCursor": true,
    "debugTestAtCursor": true,
    "fillStruct": true,
    "generateTestForFile": true,
    "generateTestForFunction": true,
    "generateTestForPackage": true,
    "playground": true,
    "removeTags": true,
    "testAtCursor": true,
    "testCoverage": true,
    "testFile": true,
    "testPackage": true,
    "toggleTestFile": true
  },
  "go.enableCodeLens": {
    "references": true,
    "runtest": true
  },
  "go.toolsManagement.autoUpdate": true,

  // JS/TS
  "typescript.tsserver.experimental.enableProjectDiagnostics": true,
  "js/ts.implicitProjectConfig.checkJs": true,
  "prettier.semi": false,

  // NIM
  "nim.logNimsuggest": true,

  // PYTHON
  "pylance.insidersChannel": "daily",
  "python.analysis.typeCheckingMode": "basic",
  "python.formatting.blackPath": "C:\\Users\\rayga\\.local\\bin\\black.exe",
  "python.insidersChannel": "daily",
  "python.languageServer": "Pylance",
  "python.venvPath": "~/.cache/pypoetry/virtualenvs/",
  "jupyter.insidersChannel": "daily",
  "jupyter.themeMatplotlibPlots": true,
  "notebook.kernelProviderAssociations": [
    {
      "kernelProvider": "ms-toolsai.jupyter",
      "viewType": "jupyter-notebook"
    }
  ],

  // RUST
  "rust-analyzer.updates.channel": "nightly",
  "rust-analyzer.procMacro.enable": true,
  "rust-analyzer.cargo.features": [],
  "rust-analyzer.cargo.loadOutDirsFromCheck": true,
  "rust-analyzer.cargo.allFeatures": true,

  // SHELL
  "shellcheck.enableQuickFix": true,

  // SQL
  "pgFormatter.commaBreak": true,

  // TAILWIND
  "tailwindCSS.experimental.showPixelValues": true,

  // ZIG
  "zigLanguageClient.path": "C:/Zig/zls-windows-x86_64_0.1.0/zls.exe",
  "zigLanguageClient.debugLog": true,

  // VS CODE TERMINAL CONFIG
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.fontFamily": "Hack NF",

  "terminal.explorerKind": "external",
  "terminal.integrated.environmentChangesIndicator": "on",
  "terminal.integrated.experimentalUseTitleEvent": true,
  "terminal.integrated.localEchoExcludePrograms": [
    "vim",
    "vi",
    "nano",
    "tmux",
    "micro"
  ],

  "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell"
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": []
    },
    "Git Bash": {
      "source": "Git Bash"
    },
    "x64 Native Tools Command Prompt for VS 2019": {
      "path": "cmd.exe",
      "args": [
        "/k",
        "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat && start \"\" \"%PROGRAMFILES%\\Git\\bin\\.exe\" --login"
      ]
    }
  },

  // UI THEME
  "oneDarkPro.editorTheme": "oneDarkPro",

  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[lua]": {
    "editor.defaultFormatter": "Koihik.vscode-lua-format"
  },
  "[markdown]": {
    "editor.defaultFormatter": "yzhang.markdown-all-in-one"
  },
  "[sql]": {
    "editor.defaultFormatter": "bradymholt.pgformatter"
  },
  "[typescript]": {
    "editor.autoClosingBrackets": "always",
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.autoClosingBrackets": "always",
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[yaml]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "C_Cpp.default.cStandard": "c17",
  "workbench.tree.renderIndentGuides": "always",
  "editor.largeFileOptimizations": false,
  "C_Cpp.experimentalFeatures": "Enabled",
  "vetur.experimental.templateInterpolationService": true,
  "[zig]": {
    "editor.defaultFormatter": "AugusteRame.zls-vscode"
  },
  "notebook.cellToolbarLocation": {
    "default": "right",
    "jupyter-notebook": "left"
  },
  "pythonPreview.stackFrameHeader.fontSize": 12,
  "pythonPreview.typeLabel.fontSize": 10,
  "pythonPreview.stackAndHeapHeader.fontSize": 12,
  "pythonPreview.retVal.fontSize": 10,
  "pythonPreview.pyStdout.fontSize": 12,
  "pythonPreview.showAllFrameLabels": true,
  "pythonPreview.printOutputDocs.fontSize": 10,
  "pythonPreview.legend.fontSize": 10,
  "pythonPreview.langDisplay.fontSize": "12",
  "pythonPreview.heapObject.fontSize": 12,
  "pythonPreview.fontSize": 14,
  "pythonPreview.codeFooterDocs.fontSize": 10,
  "pythonPreview.code.lineHeight": 1,
  "pythonPreview.code.fontSize": "13",
  "C_Cpp.default.windowsSdkVersion": "10.0.19041.0",
  "security.workspace.trust.untrustedFiles": "open",
  "C_Cpp.clang_format_fallbackStyle": "WebKit",
  "editor.fontFamily": "Consolas",
  "terminal.integrated.profiles.linux": {
    "bash": {
      "path": "bash"
    },
    "zsh": {
      "path": "zsh"
    },
    "fish": {
      "path": "fish"
    },
    "tmux": {
      "path": "tmux",
      "icon": "terminal-tmux"
    },
    "pwsh": {
      "path": "pwsh",
      "icon": "terminal-powershell"
    },
    "sh": {
      "path": "/bin/sh"
    }
  },
  "typescript.updateImportsOnFileMove.enabled": "always",
  "files.exclude": {
    "**/.classpath": true,
    "**/.project": true,
    "**/.settings": true,
    "**/.factorypath": true
  },
  "graalvm.installations": ["/graalvm-ce-java11-21.2.0-dev"],
  "terminal.integrated.env.windows": {
    // "PATH": "c:\\GraalVM\\graalvm-ce-java16-21.2.0-dev\\bin;C:\\Users\\rayga\\Projects\\tmp\\llvm-project\\llvm-13.0.0-msbuild-vs2019-x64-rel\\bin;C:\\Program Files\\LLVM\\bin;XXXC:\\Program Files\\AdoptOpenJDK\\jdk-15.0.1.9-hotspot\\bin;C:\\GraalVM\\graalvm-ce-java11-21.2.0-dev\\bin;C:\\Program Files (x86)\\Embarcadero\\Studio\\20.0\\bin;C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\20.0\\Bpl;C:\\Program Files (x86)\\Embarcadero\\Studio\\20.0\\bin64;C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\20.0\\Bpl\\Win64;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Csound6_x64\\bin;C:\\Program Files\\ffmpeg\\ffmpeg-4.3.1-2020-11-19-full_build\\bin;C:\\Program Files\\cmder;C:\\Program Files\\Git\\cmd;C:\\Users\\rayga\\AppData\\Roaming\\Python\\Python38\\Scripts;C:\\Users\\rayga\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\Go\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Meson\\;C:\\Program Files\\xmake;C:\\Program Files (x86)\\IncrediBuild;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Library\\Swift-development\\bin;C:\\Library\\icu-67\\usr\\bin;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\bin;C:\\Users\\rayga\\scoop\\apps\\nodejs\\current\\bin;C:\\Users\\rayga\\scoop\\apps\\nodejs\\current;C:\\Users\\rayga\\scoop\\shims;C:\\D\\LDC 1.26\\bin;C:\\Ruby30-x64\\bin;C:\\Users\\rayga\\.cargo\\bin;C:\\Users\\rayga\\.poetry\\bin;C:\\Users\\rayga\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\rayga\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\Users\\rayga\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\;C:\\Users\\rayga\\AppData\\Local\\Programs\\Python\\Python38\\;C:\\Users\\rayga\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\rayga\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;C:\\Users\\rayga\\.local\\bin;C:\\Users\\rayga\\AppData\\Roaming\\Python\\Python38\\Scripts;C:\\Users\\rayga\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Users\\rayga\\go\\bin;C:\\msys64\\mingw64\\bin;C:\\XXXProgram Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin;C:\\XXXProgram Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\x86_64-w64-mingw32\\bin;C:\\XXXUsers\\rayga\\.nimble\\bin;C:\\Program Files\\CMake\\bin;C:\\Users\\rayga\\xmake;C:\\Users\\rayga\\Projects\\vcpkg;C:\\XXXQt\\6.0.2\\mingw81_64\\bin;C:\\Users\\rayga\\.dotnet\\tools;C:\\Zig\\zig-windows-x86_64-0.8.0-dev.2272+d98e39fa6;C:\\GNAT\\2021\\bin;C:\\D\\dmd-2.096.0\\windows\\bin64;C:\\Users\\rayga\\.dotnet\\tools;C:\\Program Files\\Gradle\\gradle-6.8.3\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\VC\\Tools\\Llvm\\x64\\bin\\13;C:\\Users\\rayga\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Neovim\\bin;C:\\Qt\\Qt5.12.10\\5.12.10\\msvc2017_64\\bin;C:\\Users\\rayga\\.dotnet\\tools;C:\\scala3-3.0.1-RC1\\bin;",
    "GRAALVM_HOME": "/graalvm-ce-java11-21.2.0-dev",
    "JAVA_HOME": "c:\\GraalVM\\graalvm-ce-java16-21.2.0-dev"
  },
  "java.home": "C:\\GraalVM\\graalvm-ce-java16-21.2.0-dev",
  "maven.terminal.customEnv": [
    {
      "environmentVariable": "JAVA_HOME",
      "value": "C:\\GraalVM\\graalvm-ce-java16-21.2.0-dev"
    }
  ],
  "netbeans.verbose": true,
  "files.watcherExclude": {
    "**/.bloop": true,
    "**/.metals": true,
    "**/.ammonite": true
  },
  "terminal.integrated.env.linux": {
    "GRAALVM_HOME": "/graalvm-ce-java11-21.2.0-dev",
    "JAVA_HOME": "/graalvm-ce-java11-21.2.0-dev",
    // "PATH": "/graalvm-ce-java11-21.2.0-dev/bin:/vscode/vscode-server-insiders/bin/x64/e1161be26874f0d39a5b9cdeb2c5fbfd4f83bb80-insider/bin:/graalvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/gradle/gradle-7.1/bin"
  },
  "graalvm.home": "/graalvm-ce-java11-21.2.0-dev",
  "netbeans.jdkhome": "/graalvm-ce-java11-21.2.0-dev",
  "redhat.telemetry.enabled": true,
  "java.implementationsCodeLens.enabled": true,
  "java.referencesCodeLens.enabled": true,
  "java.saveActions.organizeImports": true,
  "java.signatureHelp.enabled": true,
  "java.import.gradle.java.home": "c:\\GraalVM\\graalvm-ce-java16-21.2.0-dev",
  "metals.fallbackScalaVersion": "3.0.2-RC1",
  "maven.executable.path": "C:\\Program Files\\apache-maven-3.8.1\\bin\\mvn",
  "metals.superMethodLensesEnabled": true,
  "editor.inlineSuggest.enabled": true,
  "github.copilot.enable": {
    "*": false,
    "yaml": false,
    "plaintext": false,
    "markdown": false
  },
  "editor.autoClosingBrackets": "always",
  "quarkus.tools.alwaysShowWelcomePage": false,
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "java.configuration.runtimes": [],
  "java.maven.downloadSources": true,
  "java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",
  "diffEditor.ignoreTrimWhitespace": false,
  "workbench.colorTheme": "Plastic",
  "security.workspace.trust.enabled": false
}
```

</details>

https://user-images.githubusercontent.com/26604994/128557089-aeebda74-193b-4483-b062-4f5011e9d884.mp4

**Comment by gtim108** [comment] 2021-08-08 00:47
In my case it was tkrkt.linenote-1.2.1 extension. When I removed in on disk everything works fine.

**Comment by MrMuMu** [comment] 2021-08-08 08:26
I am having this issue as well. Extra information: closing and opening vscode multiple times can **sometimes** load some of the extension.

Side question: how to downgrade insider version on windows?

**Comment by Mesteery** [comment] 2021-08-08 12:41
You can install the latest 1.59.0 insider (which doesn't have bugs with extensions) : https://update.code.visualstudio.com/1.59.0-insider/win32/insider. You only have to install this.

**Comment by ansaso** [comment] 2021-08-08 12:42
Having this issue on M1 Big Sur 11.5 too. On the bright side I had forgotten how snappy vscode could be without extension bloat.

**Comment by misolori** [comment] 2021-08-09 15:35
I had a somewhat similar issue where upon launching the update, everything got reset (views, preferences, etc.) but my extensions/settings remained the same (yet settings sync was turned off). So for me it was a loss of state, not sure if they are related

**Comment by disco0** [comment] 2021-08-10 01:07
Will be filing an issue at the relevant repo, but for others with this the problem extension for me was `sumneko.lua-2.3.6`.

Reinstalled it, and confirmed a new window failed to load extensions—had zero errors in any Log output except this possibly relevant one in the Window log:

``` log
[2021-08-09 17:53:51.305] [renderer1] [error] Cannot read property 'message' of undefined: TypeError: Cannot read property 'message' of undefined
    at k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:23948)
    at k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:24226)
    at k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:24226)
    at k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:24226)
    at k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:24226)
    at k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:24226)
    at k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:24226)
    at Function._replaceNLStrings (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:24329)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1490:23077
```

**Comment by GavinRay97** [comment] 2021-08-10 22:42
@disco0 
> Will be filing an issue at the relevant repo, but for others with this the problem extension for me was `sumneko.lua-2.3.6`.

I also had this extension.

It may be coincidence, but I:
- Uninstalled `sumneko.lua`
- Ran the `Reload window` command from Command Palette
- Everything was still broken
- Closed VS Code Insiders
- When doing this, it launched an auto-update
- When I opened it again, it is now fixed

So it could have been that update, or could have been needing to uninstall `sumneko.lua` and fully close + reopen.

But now it works!

**Comment by clynker** [comment] 2021-08-11 14:38
I was running into this same issue on VS Code Insiders (all extensions disabled) and while researching the issue locally I noticed an error was being thrown due to some sort of 'translation' issue of strings from the `sumneko.lua` extension.

In case it's not a coincidence that we both mentioned the same extension and we both had the "all extensions disabled issue", [this bug](https://github.com/microsoft/vscode/commit/568c51aff0700672a4187de02e03169d8b6cba78#r54535843) may be related and [this recent code change](https://github.com/microsoft/vscode/commit/12a1d1f9cb0c4e2b7894466e1878e6f3899408d9) may have resolved the issue?

I still have the `sumneko.lua` extension and after an auto-update of vscode (commit: `49af1cbe00271ac2ea36cfc5f7352fe31a7b0094`), extensions seem to be up and running as expected.

**Comment by sandy081** [comment] 2021-08-17 13:48
All of you who are seeing extensions disabled in the extensions view, can you please open dev tools console and see if there are any errors?

**Closed** 2021-08-25 11:29 UTC
Labels: needs more info

**Comment by Mesteery** [comment] 2021-08-25 11:31
> All of you who are seeing extensions disabled in the extensions view, can you please open dev tools console and see if there are any errors?

This has been resolved for me since a few versions already.

**Comment by evanjmg** [comment] 2021-09-22 09:26
Happens to me on 1.60 - please fix this!!!
