### ISSUE TITLE
Port forward port visibility default

### ISSUE THREAD

**Issue by DaanKorver** [microsoft/vscode#207696] opened 2024-03-14 10:54 UTC
I would like to have the ability to set the default setting of port visiblity when forwarding a port in VSCode. I use this on a daily basis and its just really tedious to have to right click every time I forward a port. 

![image](https://github.com/microsoft/vscode/assets/30351629/d7fc58b1-7bca-48fe-872a-7022224d2e11)

**Comment by alexr00** [comment] 2024-03-14 11:53
Are you using GitHub Codespaces?
Either way, it's duplicate of https://github.com/microsoft/vscode-remote-release/issues/6363. Though if you're not using Codespaces then if we add the feature for other remotes then you would benefit.

**Closed by alexr00** 2024-03-14 11:53 UTC
