### ISSUE TITLE
Extension host veto is registered multiple times on restart

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#183778] opened 2023-05-30 10:16 UTC
Testing #183534

- Open a folder that has a image in an empty profile say T1
- Install Luna Paint Extension
- Edit the image using Luna Paint and do not save
- Switch the profile to another profile say T2
- A dialog is shown ✅  and press OK

🐛 Image is saved

**Comment by bpasero** [comment] 2023-05-30 14:50
![Recording 2023-05-30 at 16 50 00](https://github.com/microsoft/vscode/assets/900690/2c9d187c-78a6-435a-932a-b3bf9d40fe47)

The save is expected, but I am not seeing any dialog. How is it for you?

**Comment by bpasero** [comment] 2023-05-30 15:05
I see that for some images (JPEG) a quick picker opens asking for the quality to save and for others (PNG) you do not get asked. I wonder if you saw an issue with JPEG?

**Comment by bpasero** [comment] 2023-05-30 15:10
There seems to be an actual issue with JPEG in this flow, adding @mjbvz and @Tyriar . Steps:
* have 2 profiles, one has Luna Paint
* open a JPEG in the profile that has Luna Paint
* make it dirty
* switch to the other profile
* you get asked to put in quality
* do that (accept the default)

=> 🐛 somehow the save fails even though I would expect it to work. We call it from here:

https://github.com/microsoft/vscode/blob/60bfd19afb29aec3171aef91d72e26eb2263c97f/src/vs/workbench/api/browser/mainThreadCustomEditors.ts#L118-L127

```
ERR Canceled: Canceled
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js:20:24
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:660:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:836:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:800:37)
    at MutableToken.cancel (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/cancellation.js:47:35)
    at CancellationTokenSource.cancel (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/cancellation.js:94:29)
    at Object.cancel (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js:34:24)
    at MainThreadCustomEditorModel.saveCustomEditor (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/api/browser/mainThreadCustomEditors.js:472:32)
    at MainThreadCustomEditorModel.save (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/api/browser/mainThreadCustomEditors.js:452:41)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/api/browser/mainThreadCustomEditors.js:69:65
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/api/browser/mainThreadCustomEditors.js:76:19
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:660:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:836:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:800:37)
    at NativeExtensionService._doStopExtensionHostsWithVeto (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:517:30)
    at NativeExtensionService.stopExtensionHosts (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:491:25)
    at UserDataProfileManagementService.enterProfile (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/userDataProfile/browser/userDataProfileManagement.js:97:51)
    at UserDataProfileManagementService.switchProfile (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/userDataProfile/browser/userDataProfileManagement.js:91:24)
    at async ActionRunner.runAction (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/actions.js:114:13)
    at async ActionRunner.run (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/actions.js:106:17)
    at async NativeContextMenuService.runAction (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/contextmenu/electron-sandbox/contextmenuService.js:203:17)
```

**Comment by bpasero** [comment] 2023-05-30 15:10
Oh, the stack hints to profiles. @sandy081 can you check!

**Comment by Tyriar** [comment] 2023-05-30 17:19
Nothing particularly special about the jpeg flow on my end, just that it can take a lot longer to resolve. All saving has to go via the extension host so it's all async. Let me know if it looks like I'm doing something wrong.

**Comment by sandy081** [comment] 2023-05-31 07:30
@bpasero Profiles component is stopping the extension host that is needed when switching profiles. Hence it is in the stack.

**Comment by sandy081** [comment] 2023-05-31 07:33
> The save is expected, but I am not seeing any dialog. How is it for you?

I am seeing the following dialog when I switch profiles. 

![image](https://github.com/microsoft/vscode/assets/10746682/7b49fdf3-ede4-48ac-b167-104f26e37eb2)

After pressing OK. Image is saved.

**Comment by Tyriar** [comment] 2023-05-31 13:37
@bpasero @mjbvz this actually sounds like the fine behavior to me, saving a jpeg is lossy so if we don't know the quality you want to save it with it could be considered data loss. If a custom editor cannot save then switching profiles should not be possible if it requires a reload imo.

In this case I just throw on the webview side which is returning a promise to the exthost:

```ts
        if (imageQuality === undefined) {
          throw new Error('Quality not selected');
        }
```

Something I could do is force hot exit in this case, but I don't think I get any signal that the request to save is because of a reload.

**Comment by bpasero** [comment] 2023-05-31 13:42
@Tyriar but the `save` call never returns, that is the issue I am reporting here. If I cancel anything in the process of saving, the call should return `false`.

**Comment by Tyriar** [comment] 2023-05-31 14:20
I haven't verified, but I'm guessing that's an issue on my end with the promise not rejecting from a throw on the other process https://github.com/lunapaint/vscode-luna-paint/issues/186

**Comment by bpasero** [comment] 2023-06-01 17:08
I think the `cancel` error originates from here:

https://github.com/microsoft/vscode/blob/4137aa15f55c5ec3777daf6684908f64b439f6aa/src/vs/workbench/api/browser/mainThreadCustomEditors.ts#L623

It is not so easy for me to reproduce though I think it requires multiple rounds of EH restarts.

**Comment by bpasero** [comment] 2023-06-01 17:11
**Steps:**
* use the hex editor extension from us (`ms-vscode.hexeditor`)
* open a file as hex editor make a change and select "Restart EH" from command palette
* close the editor
* open it again and make a change again
* select to restart EH and see the error:

<img width="319" alt="image" src="https://github.com/microsoft/vscode/assets/900690/d034858e-0fbd-41a5-a7c9-73dd0d37284e">

**Comment by bpasero** [comment] 2023-06-02 06:11
Debugging this I see how `mainThreadCustomEditors` is instantiated twice after EH restart. This seems to happen for all `mainThreadXY` 🤯

**Comment by bpasero** [comment] 2023-06-02 06:40
Hm, it seems standard behaviour that `mainThreadXY` gets instantiated multiple times on EH restart, I could not bisect it to a recent change. I will push a fix for this particular issue but still think that we might need to follow up.

**Closed** 2023-06-02 08:45 UTC
Labels: bug, candidate, custom-editors

**Comment by bpasero** [comment] 2023-06-02 08:55
**Verification:**
* have HEX editor extension installed (https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor)
* open a text file as HEX editor
* make changes, do not save
* from the command palette pick the command to restart the extension host
* notice how the HEX editor saves
* close the HEX editor
* open the HEX editor again on the same file
* make changes, do not save
* from the command palette pick the command to restart the extension host
* 🏁 you should not see an error dialog

**Comment by sandy081** [comment] 2023-06-02 12:40
Verified but using Luna Paint extension with images
