### ISSUE TITLE
Stop telling me that I can change the default shell

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#69960] opened 2019-03-07 14:52 UTC
Issue Type: <b>Bug</b>

The "You can change the default terminal shell" notification seems to open for every new terminal. I suggest to show it at most once.

VS Code version: Code - Insiders 1.32.0-insider (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T10:06:48.833Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|24.00GB (13.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.8.0

</details>

**Comment by Tyriar** [comment] 2019-03-08 20:40
There's a don't show again button though?

**Comment by chrmarti** [comment] 2019-03-11 08:27
I think users not happy with the (or any) default will understand that there might be a setting to change it to their preference, also without a notification.

**Comment by Tyriar** [comment] 2019-03-11 14:31
I don't think we should show and assume someone read it and knows how to action it in the future. Maybe they're busy and they don't want to action it right away so they dismiss. This is an existing pattern of using don't show again in the gear menu isn't it?

![image](https://user-images.githubusercontent.com/2193314/54131456-9b0b2180-43cf-11e9-95fb-dbae67030791.png)

If user sets `terminal.integrated.windows.shell` then the notification won't show.

**Comment by Tyriar** [comment] 2019-03-11 17:25
> Why does this setting need a notification advertising it?

Because people had a lot of trouble configuring this on Windows, so for Windows only there's a command that detects shells and their correct paths and configures it without going to settings. The number of people using sysnative incorrectly or linking another wrong executable feels like it's gone down a lot since I added this.

**Comment by Tyriar** [comment] 2019-03-22 18:29
Closing as designed for now

**Closed by Tyriar** 2019-03-22 18:29 UTC
Labels: integrated-terminal, under-discussion
