### ISSUE TITLE
React JSX code completion unfiltered

### ISSUE THREAD

**Issue by wolfgangmeyers** [Microsoft/vscode#46345] opened 2018-03-22 13:46 UTC
- VSCode Version: 1.21.1
- OS Version: Mac OSX 10.13.3
Typescript version 2.7.2

Steps to Reproduce:

1. Author a react component in a .tsx file
2. use ctrl+space to trigger code completion

Only react component properties should show, but many others show as well.

**Comment by wolfgangmeyers** [comment] 2018-03-22 13:47
![image](https://user-images.githubusercontent.com/1783800/37774194-d1b3da00-2d9c-11e8-93f6-806adfbed14f.png)

**Comment by mjbvz** [comment] 2018-03-22 18:25
Duplicate of #43812

**Closed by mjbvz** 2018-03-22 18:25 UTC
Labels: javascript
