### ISSUE TITLE
Native Notebooks - Green Check on Clear all Outputs

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#121986] opened 2021-04-23 05:15 UTC
- VS Code Version: 1.56.0

Steps to Reproduce:

1. Open notebook make some cells with outputs and run them. 
2. Clear all outputs

Actual Behavior: 

Green check remains in the cell status bar.
![image](https://user-images.githubusercontent.com/19276747/115821520-c71f6c00-a3b7-11eb-8afd-74a8c2233834.png)

*This experience is extra strange if you delete the code before you clear the outputs 😄
![image](https://user-images.githubusercontent.com/19276747/115821663-09e14400-a3b8-11eb-9743-6a037309f348.png)

Expected Behavior: 
 
Green check to be gone, same way execution count is wiped.

**Comment by roblourens** [comment] 2021-04-29 16:07
Duplicate of https://github.com/microsoft/vscode/issues/122645

**Closed by roblourens** 2021-04-29 16:07 UTC
