### ISSUE TITLE
Selecting a line when file is auto-updating causes to scroll down near to the end of file

### ISSUE THREAD

**Issue by Iconoclasming** [Microsoft/vscode#4486] opened 2016-03-21 05:04 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:
1. Something outside is writting to the file, and the changes are auto-updated by VSCode (in my case: my app is writting something to the log file every 1-2 seconds);
2. Start selecting a line in this file when VSCode adds new lines.

**Comment by bpasero** [comment] 2016-03-21 09:05
Not sure if we can be better here, have to investigate.

**Comment by bpasero** [comment] 2016-03-24 06:50
I can reproduce, @alexandrudima I am not sure what I am doing wrong here, in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileTracker.ts#L254 I am restoring the view state after loading the contents of the file, but the view state is the one captured a few lines before.

**Comment by bpasero** [comment] 2017-03-03 09:18
I cannot reproduce anymore and might have been fixed with my changes around updating models from external file events.

**Closed by bpasero** 2017-03-03 09:18 UTC
Labels: bug, editor, editor-core, workbench
