### ISSUE TITLE
full Screen Shortcut key does not work

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#12553] opened 2016-09-24 06:21 UTC
- VSCode Version: 1.5.3
- OS Version: win 10

Steps to Reproduce:

1. in app.js file press f5
2. now if I press f11, vscode does not go to fullscreen but if I manuall go to fullscreen from view menu it works. same if I want to close full screen mode by pressing f11, it does not work. I have to stop debugger and then f11 works.

**Comment by alefragnani** [comment] 2016-09-25 13:29
Hi @khaled-hossain-code , 

I had the same issue 30 min ago. Just noticed that it's happening because `F11` is also assigned to `Step Into` (debug view).  I don't know if VS Code team is already aware of, but until there, you could change one of the `keybindings` to avoid conflict.

Hope this helps.

**Comment by Emeryao** [comment] 2016-09-25 17:01
@alefragnani intresting shortcut key conflict between `Visual Studio` and `Browser`

**Comment by chrmarti** [comment] 2016-09-26 19:52
F11 is assigned to fullscreen on Windows.

**Comment by isidorn** [comment] 2016-09-26 19:58
As designed. We have decided to use F11 for full screen while not in a debug session, and for step into while you are debugging. Being aligned with other debugging experiences where F11 is step into is preferable to being able to F11 to full screen during a debug session.

In order to work around this please change your user keybindings.

**Closed by isidorn** 2016-09-26 19:58 UTC
Labels: bug, debug
