### ISSUE TITLE
can't select deleted code in diff editor opened by click diff decorations gutter

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#106734] opened 2020-09-15 08:00 UTC
```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
Steps to Reproduce:

1.open a git repository and open a file that is controlled by git
2.remove some code
3. click the diff decoration gutter
4. try to select the deleted code but can't

![Snipaste_2020-09-15_15-55-11](https://user-images.githubusercontent.com/41773861/93196017-776f2700-f77c-11ea-9495-aeb78bff8c76.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexdima** [comment] 2020-09-16 10:53
Duplicate of #8226

**Closed by alexdima** 2020-09-16 10:53 UTC
