### ISSUE TITLE
Provide consistent "normal", "before" and "after" decorations

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#89722] opened 2020-01-30 15:49 UTC
There are some "[normal](https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions)" decorations that for some reason are not available for "[before](https://code.visualstudio.com/api/references/vscode-api#ThemableDecorationAttachmentRenderOptions)" and "[after](https://code.visualstudio.com/api/references/vscode-api#ThemableDecorationAttachmentRenderOptions)" decorations, for example `borderRadius` and `borderStyle`.

I think for consistency whatever decorations are supported for normal text should also be supported for before/after decorations, with the exception of before/after themselves in order to avoid recursive decorations.

Also not having consistent decorations breaks a few narrow use cases, for example I wanted to highlight hex colors by adding a border to them and then also adding before/after blocks with the same color, and I wanted the whole thing to have a border radius, I can't do it because border radius is not settable for before/after decorations.

**Comment by usernamehw** [comment] 2020-01-30 17:33
Possible duplicate of #68845

**Comment by alexdima** [comment] 2020-01-31 10:03
Let's track in #68845

**Closed by alexdima** 2020-01-31 10:03 UTC
