### ISSUE TITLE
When organize JavaScript import, I lost alias imports

### ISSUE THREAD

**Issue by Luchanso** [Microsoft/vscode#49109] opened 2018-05-03 09:42 UTC
When organize import, I lost alias imports 

- VSCode Version: 1.22.2 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9 x64
- OS Version: macOS 10.13.4 (17E199)

Steps to Reproduce:

1. Typewrite code:
```js
import { Component } from 'react';
import { test as secondTest } from 'second-test';
import test from 'test';

class TestClass extends Component {
    constructor() {
        test();
        secondTest();
    }
}

new TestClass();
```
2. Cmd + Shift + P
3. Choose: `JavaScript: Organize Imports`
4. After you will miss this line:
```
import { test as secondTest } from 'second-test';
```

Gif preview:
![vscode](https://user-images.githubusercontent.com/2098777/39569779-e9eb2292-4ece-11e8-9185-e584cd78ee76.gif)

Does this issue occur when all extensions are disabled?: Yes, I was try run with flag`--disable-extensions`

**Comment by mjbvz** [comment] 2018-05-03 15:53
Duplicate of #48346

**Closed by mjbvz** 2018-05-03 15:53 UTC
Labels: javascript
