### ISSUE TITLE
[folding] Stuck expandable collapsed piece of code 

### ISSUE THREAD

**Issue by juanmahernandez** [microsoft/vscode#93033] opened 2020-03-19 17:59 UTC
Issue Type: <b>Bug</b>

1. Edit any powershell (.ps1) file that has functions
2. Shrink/Collapse some of the functions without edit anything of the file (to make it easy to read)
3. Start editing the file w/o expanding collapsed pieces of code.
4. Save
5. Try to expand the pieces of code previously collapsed/shrinked. (In my case I can't either collapse or expand any piece of code of the file anymore)

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.65GB (2.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.4.2
project-templates|can|1.2.0
vscode-eslint|dba|2.1.1
githistory|don|0.6.3
xml|Dot|2.5.0
gitlens|eam|10.2.1
spfx-snippets|eli|1.9.0
prettier-vscode|esb|3.20.0
lintlens|ghm|2.8.0
todo-tree|Gru|0.0.169
diff-tool|jin|0.0.1
vscode-codemetrics|kis|1.24.0
vscode-kanban|mkl|1.27.1
easy-less|mrc|1.6.3
vscode-azurefunctions|ms-|0.21.0
csharp|ms-|1.21.14
azure-account|ms-|0.8.8
powershell|ms-|2020.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
markdown-checkbox|PKi|1.6.0
prettier-now|rem|1.4.9
vscode-adaptivecards|tom|2.0.0
code-template-tool|yua|0.6.1

</details>

**Comment by aeschli** [comment] 2020-03-26 19:53
duplicate of https://github.com/microsoft/vscode/issues/75726

**Closed by aeschli** 2020-03-26 19:53 UTC
