### ISSUE TITLE
Copying from a desktop app into vscode doesn't copy all text on Linux

### ISSUE THREAD

**Issue by tmds** [Microsoft/vscode#30246] opened 2017-07-07 11:55 UTC
- VSCode Version: 1.13.1
- OS Version: Fedora 25

Steps to Reproduce:

1. wget http://norvig.com/big.txt
2. gedit big.txt
3. select all text and copy
4. create a new file in vscode and paste

The copied text is truncated. Note: gedit prints a message on console:
```
(gedit:665): Gdk-WARNING **: Error writing selection data: Error writing to file descriptor: Broken pipe
```

Reproduces without extensions: Yes.

The behavior also occurs when copying from a terminal into vscode. When copying from chrome into vscode, the content is not truncated.

**Comment by alexandrudima** [comment] 2017-08-10 08:26
@tmds Can you reproduce this also when copying from gedit or the terminal into Chrome? (we are relying on Electron/Chromium to provide us with the text to paste, so I suspect any bugs w.r.t. the pasted content being clipped would be reproducible when pasting in Chromium). 

(I could not reproduce this on OSX)

**Comment by tmds** [comment] 2017-08-10 08:37
@alexandrudima the bug reproduces when pasting in chrome.

**Comment by alexandrudima** [comment] 2017-08-10 08:49
Ok, in this case, may I kindly ask you to report the issue to Chromium at https://bugs.chromium.org/p/chromium/issues/list and follow up here with a link to it.

**Comment by tmds** [comment] 2017-08-10 08:59
https://bugs.chromium.org/p/chromium/issues/detail?id=754170

**Comment by alexandrudima** [comment] 2017-11-24 14:52
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Closed by alexandrudima** 2017-11-24 14:52 UTC
Labels: editor, linux, upstream
