### ISSUE TITLE
SCSS lint doesn't support CSS modules

### ISSUE THREAD

**Issue by fronteed** [Microsoft/vscode#15473] opened 2016-11-14 17:28 UTC
- VSCode Version: 1.7.1
- OS Version: OS X

SCSS lint doesn't support `:global` from CSS modules https://github.com/css-modules/css-modules 
http://take.ms/KvmIM

**Comment by aeschli** [comment] 2016-11-16 08:37
duplicate of #14539

**Closed by aeschli** 2016-11-16 08:37 UTC
Labels: css-less-sass, feature-request
