### ISSUE TITLE
TS service immediately dies at boot if an invalid file is opened as TS filetype

### ISSUE THREAD

**Issue by jakub-g** [microsoft/vscode#133515] opened 2021-09-21 10:52 UTC
**TypeScript Version:** 4.4.3
**VSCode version:** 1.61.0 Insiders
**System: MacOS Big Sur, 32GB RAM**
**tsserver.log**: [check gist](https://gist.github.com/jakub-g/0b5c2e4e073cde4391b895339618ce85)

**Steps to reproduce crash**
1. create a plaintext file that contains some JS/TS code but is not valid TS. Example:
```

marks.push(...marksForName);

Argument of type 'PerformanceEntry' is not assignable to parameter of type 'PerformanceMark'.
```
2. cmd-shift-p -> change language mode -> typescript
⚠️ Observe TS service dying 5 times

3. restart vscode
⚠️ Observe TS service dying 5 times directly at boot  

Errors:
```
The TypeScript language service died 5 times right after it got started
TS Server fatal error: Debug Failure 
```

## How did this happen?

What triggered this for me is that since vscode 1.59.0, vscode tries to auto-detect file type if default type is not set. The defaults are (`files.defaultLanguage: ""`, `workbench.editor.languageDetection: true`) so the auto-detection is enabled. Then I copy-pasted a typescript error log into a new file. The file looks typescriptish enough to be detected as TS, but it's just a log file. 

Since it's not a valid TS, the TSC gets confused. But it's unexpected that it crashes.

**Comment by matschaffer** [comment] 2021-09-22 01:28
I tried this both in a `thingie.txt` file as well as dropping it inline into https://github.com/elastic/kibana/blob/master/x-pack/plugins/monitoring/public/url_state.ts and neither caused a crash. 

Code was highlighted as incorrect in the ts file as expected

<img width="848" alt="Screen Shot 2021-09-22 at 10 27 23" src="https://user-images.githubusercontent.com/690/134269082-7ebd22f6-5352-4696-abd3-f0a9809e241d.png">

Here's my vscode version. My typescript server is on an ssh remote which may introduce some variance. 

Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by matschaffer** [comment] 2021-09-22 01:34
Oh, I forgot the step to switch the .txt file to typescript. This hasn't cause a crash yet, but it does seem to have sent my typescript server into a long loading cycle and my code highlighting in other files isn't happening.

```
matschaffer@workstation-matschaffer:~/code/kibana$ tail -f /home/matschaffer/.vscode-server/data/logs/20210921T150919/exthost5/vscode.typescript-language-features/tsserver-log-3s109o/tsserver.log | grep projectLoadingStart
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/home/matschaffer/code/kibana/src/plugins/vis_types/timeseries/tsconfig.json","reason":"Creating project referenced in solution /home/matschaffer/code/kibana/x-pack/plugins/monitoring/tsconfig.json to find possible configured project for /home/matschaffer/code/kibana/x-pack/plugins/monitoring/public/application/thingie.txt to open"}}
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/home/matschaffer/code/kibana/src/plugins/visualizations/tsconfig.json","reason":"Creating project referenced in solution /home/matschaffer/code/kibana/x-pack/plugins/monitoring/tsconfig.json to find possible configured project for /home/matschaffer/code/kibana/x-pack/plugins/monitoring/public/application/thingie.txt to open"}}
```

Seems like it's scanning all the projects in the (quite large) kibana repo space for potential completions.

Could be you're hitting something like this that eventually exhausts resources?

**Comment by matschaffer** [comment] 2021-09-22 01:39
Ah, and looks like it died eventually. Not seeing a clear error regarding _why_ in the end of the previous log file.

```
Info 81001[01:35:23.553] FileWatcher:: Added:: WatchInfo: /home/matschaffer/code/kibana/x-pack/plugins/cases/public/containers/mock.ts 500 undefined Project:  WatchType: Closed Script info
Info 81002[01:35:23.559] FileWatcher:: Added:: WatchInfo: /home/matschaffer/code/kibana/x-pack/plugins/cases/public/containers/configure/mock.ts 500 undefined Project:  WatchType: Closed Script info
Info 81003[01:35:23.568] DirectoryWatcher:: Added:: WatchInfo: /home/matschaffer/code/kibana/x-pack/plugins/translations 1 undefined Project: /home/matschaffer/code/kibana/x-pack/plugins/observability/tsconfig.json WatchType: Failed Lookup Locations
Info 81004[01:35:23.568] Elapsed:: 0.007964000105857849ms DirectoryWatcher:: Added:: WatchInfo: /home/matschaffer/code/kibana/x-pack/plugins/translations 1 undefined Project: /home/matschaffer/code/kibana/x-pack/plugins/observability/tsconfig.json WatchType: Failed Lookup Locations
Info 81005[01:35:23.569] FileWatcher:: Added:: WatchInfo: /home/matschaffer/code/kibana/x-pack/plugins/translations/translations/ja-JP.json 500 undefined Project:  WatchType: Closed Script info
(END)
```

That last line is a 3MB JSON file though https://github.com/elastic/kibana/blob/master/x-pack/plugins/translations/translations/ja-JP.json

so wondering if maybe the tsserver process OOMed trying to load that. Will watch the new process and see if maybe it dies at the same place.

**Comment by matschaffer** [comment] 2021-09-22 01:41
In the typescript output I see this which does seems to indicate crashing:

```
[Info  - 01:35:35.846] <semantic> Log file: /home/matschaffer/.vscode-server/data/logs/20210921T150919/exthost5/vscode.typescript-language-features/tsserver-log-JpE6Gq/tsserver.log
[Info  - 01:35:35.846] <semantic> Forking...
[Info  - 01:35:35.862] <semantic> Starting...
[Info  - 01:40:39.113] TSServer exited. Signal: SIGABRT
```

**Comment by matschaffer** [comment] 2021-09-22 01:52
Yeah, same place

```
matschaffer@workstation-matschaffer:~/code/kibana$ tail -n1 /home/matschaffer/.vscode-server/data/logs/20210921T150919/exthost5/vscode.typescript-language-features/tsserver-log-3s109o/tsserver.log Info 81005[01:35:23.569] FileWatcher:: Added:: WatchInfo: /home/matschaffer/code/kibana/x-pack/plugins/translations/translations/ja-JP.json 500 undefined Project:  WatchType: Closed Script info
matschaffer@workstation-matschaffer:~/code/kibana$ tail -n1 /home/matschaffer/.vscode-server/data/logs/20210921T150919/exthost5/vscode.typescript-language-features/tsserver-log-JpE6Gq/tsserver.log
Info 81005[01:40:26.773] FileWatcher:: Added:: WatchInfo: /home/matschaffer/code/kibana/x-pack/plugins/translations/translations/ja-JP.json 500 undefined Project:  WatchType: Closed Script info
```

So not sure if it's the same case for @jakub-g but I'm thinking the loose txt file is triggering a global scan, that eventually finds the massive translation json and OOMs the node process. 

https://github.com/nodejs/node/issues/12271#issuecomment-304503509 mentions that SIGABRT would be the expected on an OOM.

Will see if I can find a way grab stdout to confirm and perhaps give it more memory.

**Comment by matschaffer** [comment] 2021-09-22 01:57
Hey, got it !

<img width="469" alt="Screen Shot 2021-09-22 at 10 57 17" src="https://user-images.githubusercontent.com/690/134271380-90c4bf46-0055-4528-acd3-cbdfbad143ea.png">

**Comment by matschaffer** [comment] 2021-09-22 02:06
Looks like we explicitly include the file. I pinged the author to find out why. In the mean time I found the `typescript.tsserver.maxTsServerMemory` setting so trying that set to `2048` to see if that helps the situation.

**Comment by matschaffer** [comment] 2021-09-22 02:21
Still got an abrt. Trying 4096.

While debugging I also noticed that there are two processes that get started by https://github.com/microsoft/vscode/blob/e802791cf1df891aa81c7f57dc4ca57d54c0282a/extensions/typescript-language-features/src/tsServer/spawner.ts#L65-L66

Both of the them get the same memory setting. But this VM has plenty of room so 8gb worth of tsserver is fine for now :)

I'll see if I can isolate which one is OOMing and keep digging for stdout info to confirm the OOM.

**Comment by matschaffer** [comment] 2021-09-22 02:27
```
[Info  - 02:17:15.601] <semantic> Log file: /home/matschaffer/.vscode-server/data/logs/20210921T150919/exthost5/vscode.typescript-language-features/tsserver-log-uWzy2o/tsserver.log
[Info  - 02:17:15.601] <semantic> Forking...
[Info  - 02:17:15.623] <semantic> Starting...
```

```
matschaffer@workstation-matschaffer:~/code/kibana$ grep ja-JP.json /home/matschaffer/.vscode-server/data/logs/20210921T150919/exthost5/vscode.typescript-language-features/tsserver-log-uWzy2o/tsserver.log | grep WatchType
Info 78220[02:20:49.520] FileWatcher:: Added:: WatchInfo: /home/matschaffer/code/kibana/x-pack/plugins/translations/translations/ja-JP.json 500 undefined Project:  WatchType: Closed Script info
```

So looks like it's the semantic process that I saw dying on the 3MB json file.

`"typescript.tsserver.maxTsServerMemory": 4096` seems to have gotten me over the hump.

**Comment by matschaffer** [comment] 2021-09-22 02:37
In the end RSS handed at 3.4G so guess that explains why 4096 worked out

```
top - 02:34:56 up 11:49,  0 users,  load average: 0.39, 0.45, 1.09
Tasks:   2 total,   0 running,   2 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.0 us,  0.7 sy,  0.0 ni, 98.1 id,  0.1 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :  64315.4 total,  21354.8 free,  17243.9 used,  25716.8 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  46419.6 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                   
 350300 matscha+  20   0 4038512   3.4g  30640 S   4.0   5.4   5:36.04 /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node --max-old-space-size=+ 
 350293 matscha+  20   0  672852 126836  32948 S   0.0   0.2   0:02.43 /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node --max-old-space-size=+ 
```

That big pid is the `semantic` process (I used `top -c -p $(pgrep -d',' -f tsserver.js)` to watch memory of both).

```
matscha+  350300 35.6  5.4 4038652 3569360 ?     Sl   02:17   5:31 /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node --max-old-space-size=4096 /home/matschaffer/code/kibana/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1003/d2b723acee7fa9d14688/tscancellation-64ca2fc688ffb66bc363.tmp* --logVerbosity verbose --logFile /home/matschaffer/.vscode-server/data/logs/20210921T150919/exthost5/vscode.typescript-language-features/tsserver-log-uWzy2o/tsserver.log --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
```

So good news is that node at least doesn't pre-allocate memory. In the end I'm using just shy of 4GB memory for tsserver work and everything (code highlighting, switching invalid ts txt to ts mode, code navigation) seems pretty happy.

**Comment by matschaffer** [comment] 2021-09-22 02:38
@mjbvz my recommendation would be to make the OOM easier to see and provide an option (maybe on the crash message toast) to set `typescript.tsserver.maxTsServerMemory` to some higher value.

**Comment by matschaffer** [comment] 2021-09-22 02:45
@jakub-g check your output>typescript for sigabrt. If you're getting the same, you might be hitting the same thing where some project file is pushing the tsserver beyond node's default 512MB limit.

**Comment by mjbvz** [comment] 2021-10-11 19:39
Closing as we need more information from the original poster. I can't reproduce this with the current file snippet

**Closed by mjbvz** 2021-10-11 19:39 UTC
Labels: needs more info, typescript, freeze-slow-crash-leak
