### ISSUE TITLE
Selection of change in git view

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#24207] opened 2017-04-07 09:43 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-71-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.4.0|
|githistory|donjayamanne|0.2.0|
|phpunit|emallin|1.0.0|
|php-intellisense|felixfbecker|1.1.4|
|text-transform|florianloch|0.1.0|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|theme-dark-starry-night|jerry|1.0.2|
|vscode-simple-icons|LaurentTreguier|1.0.1|
|Go|lukehoban|0.6.59|
|vscode-todo|MattiasPernhult|0.8.0|
|vs-keybindings|ms-vscode|0.1.3|
|vscode-docker|PeterJausovec|0.0.13|
|material-icon-theme|PKief|2.0.3|
|better-merge|pprice|0.5.1|
|swaggitor|qnsolutions|0.1.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|2.3.9|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1. have some files with changes
2. go to git view
3. click on a file under "CHANGES", so a diff view shows up
4. click on the + beside the filename under "CHANGES"

- The file is lifted up to "STAGED CHANGES", but not selected anymore.
- The diff view is still showing but missing the diff information

**Comment by joaomoreno** [comment] 2017-04-07 15:12
Not much we can do about the selection since the SCM resource is really gone.

The diff view is unfortunate and is a regression from old behaviour, definitely. We can try to fix that.

**Comment by joaomoreno** [comment] 2017-11-23 13:39
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Closed by joaomoreno** 2017-11-23 13:39 UTC
Labels: bug, git
