### ISSUE TITLE
Autocomplete is super frustrating

### ISSUE THREAD

**Issue by rchande** [Microsoft/vscode#41977] opened 2018-01-22 16:42 UTC
We received this customer report for the C# extension for VS Code and it's not clear what we are doing to cause this behavior. We aren't setting sort text. Is this an issue with the VS Code matching algorithm?

Copied from https://github.com/OmniSharp/omnisharp-vscode/issues/1971

vscode version: Version 1.19.0-insider (1.19.0-insider)

c# extension version: 1.13.1

Steps to Reproduce:

Problem:

For whatever reason, my autocomplete has the incredibly frustrating habit of choosing the SECOND item in the list, rather than the first. As you could imagine, this drives me insane.

Here's a picture:

![image](https://user-images.githubusercontent.com/167745/35199000-2af92df6-feac-11e7-9039-70ff500550db.png)

`depth` is a parameter; I have no idea what the other thing even is. VSCode happily selects the first thing until I type the "h" in depth, then it switches to the second option. WHY?! It makes no sense. This kind of thing happens all the time. I can't see why you would EVER want to select the second item in the dropdown!

I'm filing this bug in this repo because I have used vscode with TypeScript for ages and never had this problem, so I assume that it lies on the C# autocomplete side.

**Comment by usernamehw** [comment] 2018-01-22 17:26
Possible duplicate of https://github.com/Microsoft/vscode/issues/41060

**Comment by jrieken** [comment] 2018-01-23 08:41
@rchande please try latest insiders and get back to us with how you like it

**Closed** 2018-01-23 08:41 UTC
Labels: *duplicate

**Comment by rchande** [comment] 2018-01-23 15:56
Thanks @jrieken.

**Comment by johnfn** [comment] 2018-01-24 20:08
@jrieken 

This is better on the latest version of Insiders, but it's definitely not fixed. e.g. `new ` will randomly complete to `nameof`, although this happens less than 10% of the time.
