### ISSUE TITLE
File watcher fails on Centos with GNOME

### ISSUE THREAD

**Issue by jacdavis** [Microsoft/vscode#937] opened 2015-12-02 17:59 UTC
1) Install centos 7
2) Install gnome
3) start x
4) open vscode
5) open a folder
6) Try to use debug configuration icon to create launch.json
EXPECTED: works
ACTUAL: fails to populate list of available debug adapters.

**Comment by isidorn** [comment] 2015-12-04 12:02
If you manually create a `launch.json` file does that work?
Do you see some errors in the console - `command palette` > `developer: toggle developer tools` 
Do you see a list of debug environments in the quick open, and once you pick the file does not get created?

I do not think we officialy support centos 7 gnome setup https://code.visualstudio.com/docs/supporting/requirements

**Comment by isidorn** [comment] 2015-12-08 15:41
Closing for now since there is not enough info.
Once provided will reopen.

**Comment by jacdavis** [comment] 2015-12-08 16:51
1) Manually creating the configuration does not work
2) There is nothing in the console.

**Comment by isidorn** [comment] 2015-12-09 09:16
There is nothing in the console so it is probably missing file events on Centos as @bpasero suggested.
Giving to you Ben

**Comment by bpasero** [comment] 2015-12-09 09:19
@jacdavis can you run with "--verbose" and open the dev console to see file events being printed when the file is created? I suspect file events are not working. Alternatively, if the file is there does a restart show the launch configuration eventually?

**Comment by jacdavis** [comment] 2015-12-10 15:24
I don't see anything in the dev console when running with --verbose

**Comment by bpasero** [comment] 2015-12-10 15:51
@jacdavis when you change a file outside of VS Code does the explorer show you the changes? E.g. try with deleting a file or duplicating one that is inside your workspace and showing in the explorer.

**Comment by jacdavis** [comment] 2015-12-10 19:20
@bpasero - the file does update. There is still nothing in the debug console. I do occaisionally see this error in the console code was launched with:
==== JS stack trace =========================================

Security context: 0x2d4d801b45d1 <JS Object>
    1: JSONSerialize(aka JSONSerialize) [native json.js:~120] [pc=0x170ee0355b1d] (this=0x2d4d801041b9 <undefined>,G=0x2d4d80105c59 <String[1]: 1>,j=0x128a245f7681 <an Arguments with map 0x327185009d21>,v=0x128a245f7639 <JS Function (SharedFunctionInfo 0x2d4d80188c41)>,w=0x128a245f7619 <JS Array[1]>,x=0x2d4d80104291 <String[0]: >,y=0x2d4d80104291 <String[0]: >)
    2: SerializeObject(aka Serial...

**Comment by bpasero** [comment] 2015-12-10 20:17
Thats weird, you should get something like this when running "code --verbose" and opening the dev tools (Help > Toggle Developer Tools):

![image](https://cloud.githubusercontent.com/assets/900690/11727308/7bca5992-9f83-11e5-998e-1d924986d85a.png)

**Comment by jacdavis** [comment] 2015-12-10 20:34
No, I'm not seeing that. Would you like me to share out my vhd?

Sent from my Windows Phone
________________________________

**Comment by bpasero** [comment] 2015-12-14 18:34
@jacdavis I should be able to set this up in my parallels. Can you share the ISO to install what you have?

**Comment by jacdavis** [comment] 2016-01-08 21:46
I believe it came from here: http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Everything-1511.iso

**Comment by bpasero** [comment] 2016-03-30 10:38
I cannot reproduce.

**Closed by bpasero** 2016-03-30 10:38 UTC
Labels: bug
