### ISSUE TITLE
Extensions in Marketplace

### ISSUE THREAD

**Issue by poojadiyo** [Microsoft/vscode#57929] opened 2018-09-05 03:39 UTC
Issue Type: <b>Bug</b>

Cannot Search Extenstion in Marketplace. 

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.33GB free)|
|Process Argv|C:\Users\Pooja Dobariya\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by poojadiyo** [comment] 2018-09-05 03:44
Sorry, I didn't get any relevant solution from it.

**Comment by Deltatiger** [comment] 2018-09-05 03:47
@poojadiyo Until the market place servers are restored we cannot install / search for extensions. This has been down from yesterday.

**Comment by poojadiyo** [comment] 2018-09-05 03:56
@Deltatiger thanks for your information.

**Comment by alexytiger** [comment] 2018-09-05 04:13
thank you also.

**Comment by Deltatiger** [comment] 2018-09-05 05:07
Everything is up and running now. Seems an entire data center went down due to lightning storm and this data center must have hosted the marketplace data. I am able to search for extensions now.

**Comment by mjbvz** [comment] 2018-09-05 06:39
Duplicate of #57851

**Closed by mjbvz** 2018-09-05 06:39 UTC
