### ISSUE TITLE
vscode-test does not run with version 1.46 on AWS EC2 instance

### ISSUE THREAD

**Issue by ChristophNiehoff** [microsoft/vscode#100375] opened 2020-06-17 10:25 UTC
- VSCode Version: 1.46
- OS Version:  CentOS 7 (AWS EC2)  (centos-release-7-7.1908.0.el7.centos.x86_64, Kernel:  3.10.0-1062.18.1.el7.x86_64)

I am running vscode-test extension tests in a Jenkins pipeline on an AWS EC2 instance. Before the release of 1.46 these ran without problems. With version 1.46 (and also insiders) `vscode-test.runTests()` just "freezes" and does not start any tests for hours. Pinning to version 1.45.1 lets the tests run smoothly.

Every 60min the following lines are logged:
```
02:38:32  [90m[main 2020-06-17T00:38:29.946Z][0m update#setState checking for updates
02:38:32  [90m[main 2020-06-17T00:38:30.018Z][0m update#setState idle
```

My test setup is as described in the [testing extensions documentation](https://code.visualstudio.com/api/working-with-extensions/testing-extension) and my Jenkins setup is essentially:
```
pipeline {
    environment {
        DISPLAY = ":99.0"
    }

    stages {
        stage ('build extension') {
            [...]
        }

        stage ('run unit tests') {
            steps {
                dir('vscode/extension') {
                    // start virtual display
                    // this is needed by vscode-test, see https://code.visualstudio.com/api/working-with-extensions/continuous-integration
                    sh '/usr/bin/Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &'
                    sh 'npm run test'
                }
            }
        }
    }
}

```
Do you need more information?

**Comment by ChristophNiehoff** [comment] 2020-06-17 10:28
On my laptop (running Ubuntu 19.10) the tests run without problems (using version 1.46).

**Comment by chrstsmth** [comment] 2020-06-22 22:35
I am experiencing this as well.

My behaviour looks to be largely the same: All tests work locally, but `1.46.0` and `insiders` hang when run using a Jenkins pipeline. The pipeline currently tests against `1.41.0`, `1.42.1`, `1.43.2`, `1.44.0`, `1.45.0`, `1.46.0` and `insiders`. Only `1.46.0` and `insiders` present this issue.

One minor difference in the output I am seeing...
`1.46.0` hangs with a slightly different message:
```
[main 2020-06-22T20:42:24.941Z] update#setState checking for updates
[main 2020-06-22T20:42:24.962Z] update#setState available for download
```
However, `insiders` hangs with the same message:
```
[main 2020-06-09T21:35:52.317Z] update#setState checking for updates
[main 2020-06-09T21:35:52.339Z] update#setState idle
```

I tried playing with `settings.json`, hoping that disabling updates might fix the issue. These settings didn't seem to help though.
```
"update.mode": "none",
"update.enableWindowsBackgroundUpdates": false,
"extensions.autoCheckUpdates": false,
"extensions.autoUpdate": false
```

**Comment by chrstsmth** [comment] 2020-07-20 17:18
Duplicate of https://github.com/microsoft/vscode/issues/99492

**Closed** 2020-11-04 08:07 UTC
Labels: *duplicate
