### ISSUE TITLE
Add setting to configure if saving non-dirty file should touch the file

### ISSUE THREAD

**Issue by shelbyspeegle** [microsoft/vscode#41812] opened 2018-01-18 13:42 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.4
cpptools|ms-|0.14.6

---

Steps to Reproduce:

1. check timestamp of a file (`getShedStructure.js`).
2. open file
3. save file with no changes
3. check the file timestamp.
actual: the file's timestamp is updated after saving with no changes.
expected: the file's timestamp is not updated because nothing changed.

i'm trying to switch from Webstorm to VS Code, and Webstorm does not do this. I am not sure about Atom.

![jan-18-2018 06-27-21](https://user-images.githubusercontent.com/7694692/35100345-c1b90004-fc18-11e7-95ae-5e35b690da34.gif)

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2018-01-18 13:50
@shelbyspeegle this actually works "as designed" for the reason you state: some people want to trigger file watchers by saving even if the file is not dirty.

Maybe we need a setting for this.

**Comment by shelbyspeegle** [comment] 2018-01-18 13:58
@bpasero thank you for your quick reply.

that is a great point. i think a setting could be useful.

could you elaborate on the most common scenario for why someone would want to trigger a file watcher for an unmodified file?

**Comment by shelbyspeegle** [comment] 2018-01-18 13:59
would you accept a PR for adding this setting?

if so, could you give me a reference to a file i could look at or documentation on adding a setting?

**Comment by bpasero** [comment] 2018-01-18 14:17
> could you elaborate on the most common scenario for why someone would want to trigger a file watcher for an unmodified file?

Yes, to trigger a reload of the server for testing without having to make a change.

> would you accept a PR for adding this setting?

Sure, why not. The touch() happens [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L690) and a configuration setting could make this conditional.

**Comment by lonix1** [comment] 2018-08-07 04:39
This is not how it works in other IDEs (as well as Visual Studio proper). Every app of any distinction does not work this way. I'm sure the number of people who want this peculiar behavior is much less than those that don't - *a file should only be saved/touched if it was actually dirty*.

If the only way to deal with this is to have an option, that is fine. But this is not a minor matter, it's a complete nuisance for the exact reason given that it is "by design" - every save triggers watcher reloads that shouldn't occur.

Like I said in my [related issue](https://github.com/Microsoft/vscode/issues/54651), surely vscode should not save in these cases:
- file hasn't changed
- undo buffer is empty (i.e. file was changed but the change was reverted, so file is in fact unchanged)

**Comment by bpasero** [comment] 2018-08-07 05:05
> every save triggers watcher reloads that shouldn't occur

Well, that is your opinion. There are many users that actually want exactly this behaviour and asked for it. As such, an option is the only way out imho.

**Comment by lonix1** [comment] 2018-08-07 06:05
You're right it's my opinion - but although I'm not sure I'm nonetheless quite convinced, that I'm in the majority on this. I can't think of another major app that works this way, including Visual Studio.

But I agree with you and the OP that this should be an option, there shouldn't be breaking changes for current users.

**Comment by christopherkang** [comment] 2018-10-05 19:05
Could we close this and reopen later if necessary? I don't think the issue fits in the roadmap / has garnered enough votes currently.

**Comment by joshunger** [comment] 2018-10-05 19:12
@christopherkang what's the benefit of closing? Where do you view the current roadmap and issues ranked by votes? What's the criteria?

**Comment by joshunger** [comment] 2018-10-05 19:31
@christopherkang I don't have the data on how many users prefer one way or the other but @lonix1 had good comments above.

**Comment by christopherkang** [comment] 2018-10-05 19:36
I think that's fair and @bpasero pointed out its need for server refresh. Also, this issue is contingent upon getting a contributor.... could we get a help-wanted tag added? Would this issue be easy to fix (maybe we could make it a good "first time" issue)?

**Comment by edjroot** [comment] 2018-10-13 19:09
+1. By the way, aren't there less "hacky" ways to trigger server reloads? Surely you can do it in the aforementioned editors?

**Comment by Vlad-Shcherbina** [comment] 2019-07-24 12:23
For discoverability, linking the old issue where saving unchanged files was requested: #7470.
Hope the linkback will show up there even though that issue is locked.

I totally agree this behavior should be optional, if present at all.

**Comment by think2011** [comment] 2019-10-01 03:00
Can anyone help?

**Comment by lakhanbaheti** [comment] 2020-03-06 07:02
Is this issue been fixed?
If yes, whats the new setting to handle it.

**Closed** 2020-03-22 08:44 UTC
Labels: feature-request, file-io
