### ISSUE TITLE
"Go to Definition" broken in last update OSX version

### ISSUE THREAD

**Issue by contreras-jorgev** [Microsoft/vscode#3880] opened 2016-03-08 20:15 UTC
Editing node.js (JavaScript) files (after opening a folder), where a file requires another module (same folder), if you want to see the definition of a symbol (F12 or right-lick "Go to Definition") stopped working with latest update Version 0.10.10 (0.10.10)

I use this feature frequently. It used to work fine.

**Comment by alexwarren** [comment] 2016-03-08 20:20
I'm seeing the same issue here (editing code at https://github.com/textadventures/quest/tree/v6). It worked fine before the update.

I'm using requirejs. I tried adding a `jsconfig.js` file, setting `module` to `amd`, but that didn't help.

**Comment by egamma** [comment] 2016-03-10 09:29
@contreras-jorgev I you have no jsconfig.json for your project then this is a duplicate of: Microsoft/TypeScript#7292

**Comment by egamma** [comment] 2016-03-10 09:31
@alexwarren I'm sorry, but `amd` module resolution is currently not supported by Salsa. Duplicate of https://github.com/Microsoft/TypeScript/issues/6942

**Closed by egamma** 2016-03-10 09:31 UTC

**Comment by contreras-jorgev** [comment] 2016-03-10 17:07
Just to clarify, since you closed the issue: after the move to Salsa,
module resolution while working with node.js modules will not work? (I am
not familiar with  amd )

This may be a show stopper for me. I was so happy with VS Code, I may need
to go back to SublimeText

**Comment by egamma** [comment] 2016-03-16 17:52
@contreras-jorgev 
Sorry, I wasn't clear Salsa fully supports node module resolution and it is more robust than it was before. Commonjs is the default module type, but I still recommend that you create a jsconfig.json, then you can easily leverage .d.ts files to get Intellisense for existing node modules. Pls see https://code.visualstudio.com/docs/runtimes/nodejs.
