### ISSUE TITLE
Add setting for default end of line sequence

### ISSUE THREAD

**Issue by kpobococ** [Microsoft/vscode#1546] opened 2015-12-21 16:11 UTC
I am using VSC on Windows while developing for Linux-based webserver. Also, several people on my team are using Macs. It is very annoying for us to switch end of line sequence for each new file. It would be great if there was a user setting to ensure all new files are created with a certain eol sequence.

**Comment by bpasero** [comment] 2015-12-23 16:18
@alexandrudima fyi

**Comment by glen-84** [comment] 2016-01-15 16:26
+1 I keep forgetting to manually switch the EOLs.

**Comment by dennis-krischok** [comment] 2016-01-28 14:45
This would be great!

**Comment by PEKTOP** [comment] 2016-02-09 21:04
+1

**Comment by egamma** [comment] 2016-02-21 10:33
closing as a dupe of #2957 (it has some more feedback), but anyways we want to address this for the Feb update.

**Closed by egamma** 2016-02-21 10:33 UTC
Labels: editor, feature-request
