### ISSUE TITLE
Search bug, some files are not searching for text.

### ISSUE THREAD

**Issue by clvr024** [microsoft/vscode#195351] opened 2023-10-11 09:53 UTC
Type: <b>Bug</b>

"I have four files, and there's a piece of text that exists in all four of them. If I don't open the files, only one file shows search results. However, when I open all four files, I can successfully retrieve results from all four files."

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (16.54GB free)|
|Process Argv|--crash-reporter-id 0cfe7a0f-3de7-4169-8377-753f52e94371|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
v2ex-playground|cha|1.5.0
xml|Dot|2.5.1
tortoise-svn|fan|0.1.1
remotehub|Git|0.62.0
code-eol|jef|1.0.12
vscode-leetcode|Lee|0.18.1
vscode-language-pack-zh-hans|MS-|1.83.2023101109
vscode-dotnet-runtime|ms-|1.8.0
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
azure-repos|ms-|0.38.0
hexeditor|ms-|1.9.12
remote-repositories|ms-|0.40.0
vscode-yaml|red|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by clvr024** [comment] 2023-10-12 08:46
The issue has been identified, and it's due to encoding problems. The default encoding is UTF-8, so if a file is in a different encoding, it won't be searchable. Is it possible to set multiple default encodings?

**Comment by clvr024** [comment] 2023-10-12 09:03
Alternatively, when searching, use 'Auto Guess Encoding' to open files and retrieve their content (not sure about the performance of this method)

**Comment by andreamah** [comment] 2023-10-23 23:41
I think this is a /duplicate of https://github.com/microsoft/vscode/issues/68237

**Closed by andreamah** 2023-10-23 23:41 UTC
