### ISSUE TITLE
Renaming symbols with F2 not working for JavaScript in HTML

### ISSUE THREAD

**Issue by PiotrNap** [microsoft/vscode#107064] opened 2020-09-19 14:02 UTC
- VSCode Version: 1.49.1
- OS Version: 10.15.6 

Steps to Reproduce:

1. Open Vs-code, make a new html file with a <script> tag.
2. Put some code into it e.g
```
<script>
  export default {
    data: function randomName(params) {
      return {
        params,
      };
    },
    methods: {
      onUpdate: () => randomName(),
    },
  };
</script>
```

Does this issue occur when all extensions are disabled?: Yes

When I try to change the symbol name/s (randomName) I'm getting 'No result.' information window at the bottom right.
Tried to restart the vs-code, but without any results.

**Comment by aeschli** [comment] 2020-09-21 09:29
duplicate of https://github.com/microsoft/vscode/issues/31141

**Closed by aeschli** 2020-09-21 09:29 UTC
Labels: new release
