### ISSUE TITLE
Allow extensions to contribute default task types

### ISSUE THREAD

**Issue by aaronfranke** [microsoft/vscode#66308] opened 2019-01-10 00:22 UTC
![Build Task Templates](https://user-images.githubusercontent.com/1646875/50937778-38cf8800-1443-11e9-9d61-83d699f987cb.png)

Currently, when I press Ctrl+Shift+B and click "Configure Build Task..." then "Create tasks.json from template", the only options are `MSBuild`, `maven`, `.NET Core`, and `Others`. 

I would like to be able to easily create a build task template for my Mono projects. .NET Core does not have the full feature-set of Mono or .NET Framework yet, and even if it did, I still have existing projects using Mono that I'd like to edit with VS Code. Please add this feature!

**Comment by alexr00** [comment] 2019-01-10 09:17
The best way to solve this would be to allow extensions to contribute build task templates. Currently you can hand write your own build tasks, but having contributable templates would be better.

**Comment by alexr00** [comment] 2020-11-09 14:41
duplicate of https://github.com/microsoft/vscode/issues/10742

**Closed by alexr00** 2020-11-09 14:41 UTC
Labels: feature-request, tasks
