### ISSUE TITLE
Errormessages on Javascript Comments inside HTML Docs in Output-Console

### ISSUE THREAD

**Issue by Neohiro79** [Microsoft/vscode#32542] opened 2017-08-15 12:04 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
vscode-caniuse|aka|0.5.3
vscode-javascript-snippet-pack|aka|0.1.5
numbered-bookmarks|ale|0.10.0
project-manager|ale|0.19.0
copy-relative-path|ale|0.0.1
workbench|and|0.1.6
imagepreview|buz|0.5.1
jshint|dba|0.10.15
stuck-overflow|dge|0.1.9
vscode-new-file|dku|3.1.1
json-tools|eri|1.0.2
auto-close-tag|for|0.4.3
live-html-previewer|hdg|0.2.0
minify|Hoo|0.3.0
rest-client|hum|0.15.1
crane|Hvy|0.3.8
autofilename|Jer|0.1.3
diff-tool|jin|0.0.1
format-indent|Kas|1.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
VBScript|lug|0.0.2
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.3.3
vscode-apache|mrm|1.1.1
PowerShell|ms-|1.4.1
wordcount|ms-|0.1.0
smartpaste|reb|0.0.3
vscode-filter-json|ric|1.0.0
vscode-icons|rob|7.12.0
whitespace|san|0.0.4
todotasks|san|0.5.0
stylelint|shi|0.28.0

---

Steps to Reproduce:

1. just make a <script></script> Tag inside any html document
2. just start to make 'comments' in there aka // or /**/
3. click in one of those commented lines:

each time an errormessages will be triggered in Output-Console:
[Error - 14:02:02] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined
  Code: -32603 

4. this won't happen if it is a .js file.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment] 2017-08-15 14:55
duplicate of #30774

**Closed by aeschli** 2017-08-15 14:55 UTC
Labels: new release

**Comment by Neohiro79** [comment] 2017-08-15 17:41
Will it be solved in the next release ?
