### ISSUE TITLE
I want to develop a form for submitting information about the current page。Is there any solution？

### ISSUE THREAD

**Issue by xyxuyao** [Microsoft/vscode#33352] opened 2017-08-29 09:18 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment] 2017-08-29 10:42
Please provide more details

**Comment by xyxuyao** [comment] 2017-08-30 02:19
I want to extend a vscode plug-in。
A plug-in like this：
![issue](https://user-images.githubusercontent.com/13941855/29852428-980d3574-8d6c-11e7-9aa2-03138837e6a9.png)

**Comment by jrieken** [comment] 2017-08-30 06:57
Thanks. Duplicate of #1833

**Closed by jrieken** 2017-08-30 06:57 UTC
Labels: needs more info
