### ISSUE TITLE
Can't call any snippet inside double quotes

### ISSUE THREAD

**Issue by pietrobp** [Microsoft/vscode#38952] opened 2017-11-22 12:56 UTC
When i was creating my snippets for php in vscode i've noticed that i can't call a snippet inside double quotes , for example , i have a anchor <a href=""></a> and i would like to use my snippet echo inside the href , but i can't because inside the double quotes i cant call the snippet.

- VSCode Version: 1.18
- OS Version: macOS 10.13.1

Steps to Reproduce:

1. Try to call a snippet inside double quotes.

**Comment by wireseeker** [comment] 2017-11-23 08:09
Same issue here ++

I've tried it on
Windows 10 - Windows 7 - Windows 8.1

a serious problem needs to be fixed as soon as possible.

**Comment by jrieken** [comment] 2017-11-23 08:14
> that i can't call a snippet inside double quotes , for example 

Please provide a complete code snippet

**Comment by wireseeker** [comment] 2017-11-23 16:53
here is a simple example for javascript.

```
var test = 'you cant call snippet here';
test += "you cant call snippet here";
alert("or here");
console.log("or even here");
```
not working at all in any double quotes!

**Comment by jrieken** [comment] 2017-11-23 16:56
still, no. 

<img width="883" alt="screen shot 2017-11-23 at 17 55 45" src="https://user-images.githubusercontent.com/1794099/33183296-8e83cdbc-d077-11e7-9d82-54a96a054f6b.png">

**Comment by wireseeker** [comment] 2017-11-23 16:57
this is so strange not working for me at all.

**Comment by wireseeker** [comment] 2017-11-23 17:04
![sketch](https://user-images.githubusercontent.com/33924401/33183571-080fa63e-d081-11e7-9584-183d71b3479b.png)

hmmm not working for me...

**Comment by jrieken** [comment] 2017-11-23 17:10
you are not describing what are are trying. you are just saying things and attaching screen shots. please attach reproducible steps of what you are doing, step by step

**Comment by wireseeker** [comment] 2017-11-23 17:16
I just wrote a double quotes then I've typed a code and snippet didn't work.
I didn't press any special keys or shortcuts like ctrl + space

for example I want to type
`alert("alert()");`

but when I try
`alert("al");`
snippet isn't working..

**Comment by jrieken** [comment] 2017-11-24 08:16
still not good steps by my I am confident is this #32201. closing as dupe

**Closed by jrieken** 2017-11-24 08:16 UTC
Labels: needs more info

**Comment by IamJinzo** [comment] 2018-01-07 01:43
`"jinzo": {
    "prefix": "jinzo",
    "body": [
        "jinzo_snippet_example"
    ],
    "description": "Test snippet."
    }`

Here is a GIF

https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1515087542/t47zkrdvihytnbm8ctbm.gif

This isn't dupe. 
The bug is still apparent in recent releases.

**Comment by IamJinzo** [comment] 2018-01-07 01:45
This isn't dupe.
The bug is still apparent in recent releases.
`
"jinzo": {
    "prefix": "jinzo",
    "body": [
        "jinzo_snippet_example"
    ],
    "description": "Test snippet."
    }
`
Here is a GIF
![t47zkrdvihytnbm8ctbm](https://user-images.githubusercontent.com/33924401/34645701-17bd1a36-f35d-11e7-9f31-6ea52c93d8a4.gif)
