### ISSUE TITLE
The menubar cannot be switched to the compact mode when the native titlebar is on

### ISSUE THREAD

**Issue by popov895** [microsoft/vscode#118217] opened 2021-03-05 14:40 UTC
- VS Code Version: 1.54.1
- OS Version: GNOME 3.38.4 X11 (Fedora 33)

The menubar cannot be switched to the compact mode (moved to the Activity Bar) when the native titlebar is on.

![Screenshot from 2021-03-05 16-06-33](https://user-images.githubusercontent.com/24252473/110130149-6325f180-7dd1-11eb-8984-b3dab6ae94e5.png)

Steps to Reproduce:

1. Go to the Settings
2. For **window.titleBarStyle** option, select **native**
3. For **window.menuBarVisibility** option, switch between **classic** and **compact**

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2021-03-05 15:06
Just in case - it's not a bug - it's mentioned behavior of this setting.
![image](https://user-images.githubusercontent.com/1312662/110132756-2f000000-7dd4-11eb-843e-d8d2d712d029.png)

**Comment by popov895** [comment] 2021-03-05 15:22
Oh, my fault, I didn't notice it. Can you make a compact menubar for native titlebar as well?

**Comment by sbatten** [comment] 2021-03-05 18:33
closing as duplicate of https://github.com/microsoft/vscode/issues/114764

**Closed by sbatten** 2021-03-05 18:33 UTC
Labels: new release
