### ISSUE TITLE
A loop which forces user to read extension details from start if he dare to switch another tab.

### ISSUE THREAD

**Issue by PranavBhattari** [microsoft/vscode#73648] opened 2019-05-13 04:53 UTC
Issue Type: <b>Bug</b>

When i read some process in some extension and go to another tab to do something, than that previous reading section will disappear and moves to top section where which i read already.

This is soooo annoying. Why this thing even exist?

I should be where i left. I don't what to read it from start again.

I am trying to do something and VScode is forcing user to read extension details again from start. Not from where he left. 

Fix this. Its killing my vibe. I have to reapeat scrolling again and again and again. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 1216)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|7.70GB (3.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
html-snippets|abu|0.2.1
vscode-browser-preview|auc|0.5.4
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.8.2
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.0.15
debugger-for-chrome|msj|4.11.3
polacode|pnp|0.3.2
LiveServer|rit|5.6.1
vscode-icons|vsc|8.6.0
quokka-vscode|Wal|1.0.212
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by gjsjohnmurray** [comment] 2019-05-13 07:38
Looks like a /duplicate of #27498

**Closed** 2019-05-13 18:08 UTC
Labels: *duplicate
