### ISSUE TITLE
Automatic change of closing tag upon change of opening tag #feature-request #editor

### ISSUE THREAD

**Issue by lordstanius** [Microsoft/vscode#39611] opened 2017-12-05 08:36 UTC
When editing opening tag in HTML is would be nice if the closing tag would follow the change automatically. For example, let's say we want to change `<div>` to `<p>` and start by changing opening tag from:
```html
<div>Some text</div>
```
to 
```html
<p>Some text</div>
```
we have to change closing tag manually. Please allow automatic change of closing tag on change of opening tag.

**Comment by aeschli** [comment] 2017-12-05 12:21
duplicate of #28026

**Closed by aeschli** 2017-12-05 12:21 UTC
Labels: html
