### ISSUE TITLE
IntelliSense adds braces to attribute names in TSX

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#47345] opened 2018-04-06 18:16 UTC
Issue Type: <b>Bug</b>

Create a tsx file and add a new React component class
```
class ScrollBar extends React.Component {
    public render(): React.ReactNode {
        return <div id="test"></div>;
    }
}
```
After `id` attribute, type <kbd>Space</kbd>, then type `class`, then use <kbd>Tab</kbd> to select `className`. IntelliSense will insert `{className}`.

If previous attribute already has braces, e.g. `id={this.props.id}`, then IntelliSense won't incorrectly add braces to next attribute name.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|1.8.0
gitlens|eam|8.2.0
tslint|eg2|1.0.28
vscode-firefox-debug|hbe|1.1.4
vscode-csscomb|mrm|5.2.2
vscode-less|mrm|0.6.3
mssql|ms-|1.3.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.3.0
vscode-docker|Pet|0.0.26
vscode-icons|rob|7.22.0

</details>

**Comment by mjbvz** [comment] 2018-04-06 18:35
Duplicate of #47112

**Closed by mjbvz** 2018-04-06 18:35 UTC
Labels: javascript
