### ISSUE TITLE
Untitled editors should not restore when user confirmed to not save

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29572] opened 2017-06-27 10:45 UTC
testing #29249

* open a no-workspace-window, create a new untitled file, type something
* create another no-workspace-window
* in the task bar select 'Close All Windows'
* from the first window you get prompted to save those files (that I find always unexpected)
* say not to save 
* reopen VS Code
* :bug: a no-workspace-window is created with an untitled but *empty* file

![jun-27-2017 12-46-20](https://user-images.githubusercontent.com/1794099/27584007-b2f8d0ea-5b36-11e7-82d4-e8fd906e9321.gif)

**Comment by bpasero** [comment] 2017-06-27 14:18
@jrieken as for the fact that you get asked to save, I think the issue here is that "Close All Windows" literally goes to each window and closes it as opposed to "File > Exit". By default, if you close a window with dirty files we ask to save the data unless this is the last Window. There is a setting `hot.exit: onExitAndWindowClose` that can be enabled to control this, but it does not seem to be supported for empty workspaces (as in this case). @Tyriar can maybe comment more on this.

Back to the issue: I think what happens is expected. All windows are closed and you start Code again. If there is no UI state from previous sessions we simply open an empty untitled file, assuming that you want to type something. 

It looks like @chrmarti introduced a new setting to control this behaviour (`"workbench.startupEditor": "none"` can be used to start even without untitled file).

**Comment by jrieken** [comment] 2017-06-27 14:25
> simply open an empty untitled file, assuming that you want to type something.

Don't think so because it opens two untitled but empty files when I create two empty files in the first window. 
![jun-27-2017 16-24-24](https://user-images.githubusercontent.com/1794099/27592671-49a2ca28-5b55-11e7-98d6-10443afab322.gif)

**Comment by Tyriar** [comment] 2017-06-27 16:55
> There is a setting hot.exit: onExitAndWindowClose that can be enabled to control this, but it does not seem to be supported for empty workspaces (as in this case). @Tyriar can maybe comment more on this.

The reason `onExitAndWindowClose` does not work for untitled folders is because it's more difficult to know when to restore them. The idea behind this setting is that the user knows they're closing changes associated with a folder, if they want them again they can go and open up the folder.

Now consider the following scenario:

1. Open empty workspace A
1. Open empty workspace B
1. Make changes to B and close it
1. Open empty workspace C
1. Make changes to C and close it
1. Close A
1. Open VS Code

What is restored at this point? We could restore all empty workspaces (even if widnow.restoreWindows !== all) which could see potentially many windows opening if the user hasn't closed the last VS Code window in a long time, this is a particular problem on macOS as this may only happen when they restart the operating system. Another way we could handle this is to expose some way of restoring old empty workspaces via the file menu/command, also not particularly intuitive.

The simplest solution to both of these problems is to be more strict around closing empty workspaces.

---

On the actual issue, in an ideal world closing all windows like this would trigger a exit rather than a window close. Perhaps we can intercept it somehow?

**Comment by bpasero** [comment] 2017-06-28 09:51
I can reproduce also when a folder is opened. The issue is that on shutdown we ask the user for confirmation but do not close the untitled editors that are opened and as such restore them on next statup. This does not happen when hot-exit is turned off because then we do not restore untitled inputs.

**Closed** 2017-08-15 06:37 UTC
Labels: bug, workbench
