### ISSUE TITLE
Suggestion: Support when for viewContainers contribution

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#48704] opened 2018-04-25 18:39 UTC
Suggest to support `when` clause for `viewContainers` contributions. This would let an extension author contribute a configuration that would let the user control if they want the explorer to be in a new view or in the default Explorer view.

**Comment by sandy081** [comment] 2018-05-09 07:17
@chrisdias Can't you use the `when` clause on the view to show/hide in explorer and custom views container?

**Comment by eamodio** [comment] 2018-05-09 13:26
But just having the view contributed to the container causes the container to show up even if the view(s) are hidden. I brought this issue up on the main viewcontainers when it was being added.

**Comment by vbfox** [comment] 2018-05-10 18:48
@eamodio I asked for the auto-hiding if the container contains nothing here #49145 let's hope we get a way or another to hide empty activities

**Comment by sandy081** [comment] 2018-05-15 08:33
@eamodio Yes, view container will be empty in such cases and I am thinking to hide view container if there are no views are registered or all registered views are hidden by `when` clause.

If agreed, I would make this and #49145 as duplicates

**Comment by vbfox** [comment] 2018-05-15 09:05
Having reflected a little more about it, I think #49145 (hiding when no views are visible inside) could be better than a when cause.

I like the `when` clause direct approach but the problem is that activities are shared between extensions (Azure ones for example do that) and any direct interaction mean that multiple extensions might need to collaborate. (If an extension for language A decide to hide the `test` activity, other languages contributing to it would have their views hidden..).

**Comment by sandy081** [comment] 2018-05-28 15:02
Duplicate of #49145

**Closed** 2018-05-28 15:02 UTC
Labels: *duplicate, explorer-custom, under-discussion
