### ISSUE TITLE
STGR + P with non-existing workspace folder error appears

### ISSUE THREAD

**Issue by DerHerrGammler** [Microsoft/vscode#43655] opened 2018-02-14 12:04 UTC
`spawn c:\Program Files\Microsoft VS Code\resources\app\node_modules\vscode-ripgrep\bin\rg ENOENT`
This error appears when I try to open some files with `strg + P` in a workspace with non-existing wokrspace folder. I can open my files with `strg + p` but every time this error appears.

- VSCode Version: 1.20.0
- OS Version: Win7 and Win10

Steps to Reproduce:

1. Strg + P
2. Open Some file in a workspace with non-existing workspace folder

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2018-02-14 18:35
/duplicate of https://github.com/Microsoft/vscode/issues/42219

**Closed** 2018-02-14 18:35 UTC
Labels: *duplicate, search
