### ISSUE TITLE
Strange behaviours of formatting in Visual Studio Code

### ISSUE THREAD

**Issue by chengtie** [Microsoft/vscode#18618] opened 2017-01-16 17:59 UTC
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2

The shortcut `shift+alt+f` is used to format the whole document (without having to select anything), and `cmd+k cmd+f` is used to format the selection.

```
{ "key": "shift+alt+f",           "command": "editor.action.formatDocument",
                                     "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly" },
{ "key": "cmd+k cmd+f",           "command": "editor.action.formatSelection",
                                     "when": "editorHasDocumentFormattingProvider && editorHasSelection && editorTextFocus && !editorReadonly" },

```
My experiments show that formatting html does not work well in some cases. For instance,

1)

```
<span>
    <span>{{post.title}}</span>
    <div>posted by</div>
</span>

```
will be formatted to

```
<span>
    <span>{{post.title}}</span>
<div>posted by</div>
</span>
```
2)
```
<form style="margin-top:30px;">
    <div>abc</div>
</form>
```
will be formatted to
```
<form style="margin-top:30px;">
<div>abc</div>
</form>
```
Does anyone know what's happening here? Are they bugs?

**Comment by aeschli** [comment] 2017-01-19 10:42
duplicate of #17849

**Closed by aeschli** 2017-01-19 10:42 UTC
Labels: html

**Comment by chengtie** [comment] 2017-01-19 10:54
@aeschli Is my first example related to `style` property as well? So it can be fixed by [e9f15e6](https://github.com/Microsoft/vscode/commit/e9f15e6495cbe91e30186410b9c5885c12da22f0) as well?

**Comment by chengtie** [comment] 2017-01-19 11:03
@aeschli I just downloaded `Visual Studio Code - Insiders`, it does fix my second example, whereas it does not fix my first example. I am going to open another issue just for that.

**Comment by aeschli** [comment] 2017-01-19 11:07
Sorry, the first issue is different and an issue of the [jsbeautifier](https://github.com/beautify-web/js-beautify) that is the underlying formatter. Please file a bug there.
Second is #17849.

Please always file separate issues for each problem you detect.

**Comment by chengtie** [comment] 2017-01-19 11:14
OK, I just opened [an issue in js-beautify](https://github.com/beautify-web/js-beautify/issues/1113)
