### ISSUE TITLE
standalone editor in Safari: cursor off at the end of long lines

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19222] opened 2017-01-24 15:52 UTC
testing #19061:

- change font in the standalone editor to 'courier'
- open `monaco-editor/test/index.html` in Safari
- added this line:
```js
//012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123
```
- zoomed in one level (View > Zoom In)
- scrolled to the far right

Observe: 
placing the cursor is always off by about four character positions

**Comment by alexandrudima** [comment] 2017-01-26 13:43
Many thanks!

Pushed a change that makes the editor not use the FastRenderedViewLine on Safari (same as Firefox).

Before this change:
Changing the zoom level would leave the editor positions permanently mis-aligned with the text until a browser reload occurs.

After this change:
Changing the zoom level leaves the editor positions mis-aligned for the lines that are already painted and until they are painted again (i.e. scrolled out of view and scrolled back in, or changed in any way, etc.)

After this change, the behaviour in Safari is similar to the behaviour in Firefox, transforming this issue into a duplicate of Microsoft/monaco-editor#337

**Closed by alexandrudima** 2017-01-26 13:43 UTC
Labels: bug, mac

**Comment by joaomoreno** [comment] 2017-01-27 09:27
Verified that this is a dupe of Microsoft/monaco-editor#337
