### ISSUE TITLE
built-in TypeScript Format not working for minified files

### ISSUE THREAD

**Issue by sdwarwick** [Microsoft/vscode#23829] opened 2017-04-02 22:04 UTC
- VSCode Version: 1.10.2
- OS Version: windows 10

Steps to Reproduce:

1.  we have a very large auto-generated javascript library that needs to be uncompressed/beautified. loading it in vscode, the first "line" is over 300,000 characters.   After attempting to use "Format Document",  the code looks as follows:

![image](https://cloud.githubusercontent.com/assets/7736675/24591381/ea8da06e-17cd-11e7-9045-59793b0cfaf1.png)

2.  using npm install js-beautify version 1.6.12  we get:

![image](https://cloud.githubusercontent.com/assets/7736675/24591392/33729d8e-17ce-11e7-9bec-931532f0a3f5.png)

3.  this is similar to what we get using the beautify function in notepad++

![image](https://cloud.githubusercontent.com/assets/7736675/24591399/4d27c9de-17ce-11e7-9c0e-d7abe66eae08.png)

4.  due to the huge size of this library and its connection to an internal program,  I can't really post it for validation.   In notepad++,  this file is 55,000 lines long after decompression.

I see no settings that would impact this, and am wondering if it is purely an issue of having js-beautify updated in vscode, if that is what you use. 

let me know if there is something else I can do to help

**Comment by mjbvz** [comment] 2017-04-03 18:36
Thanks. I can reproduce this using other minified files, such as https://code.jquery.com/jquery-3.2.1.min.js

**Comment by mjbvz** [comment] 2017-04-04 00:40
Confirmed that VSCode seems to do the correct thing, so the issue is upstream. This looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10126

**Closed by mjbvz** 2017-04-04 00:40 UTC
Labels: format, javascript, typescript, upstream

**Comment by sdwarwick** [comment] 2017-04-04 01:04
not exactly, as the syntax highlighting is also broken.  do you get the sense that the plan is to provide a solution that mimics what we see in other editors,  or something different?

**Comment by mjbvz** [comment] 2017-04-04 01:10
@sdwarwick We intentionally disable syntax highlighting on very long lines. This is not language specific @alexandrudima may be able to provide more context on the reasons for this

The expected behavior for Microsoft/TypeScript#10126 is that we better match what other editors output. Until then, extensions may be able to provide a better experience for minified js files

**Comment by alexandrudima** [comment] 2017-04-04 09:18
@sdwarwick We disable syntax highlighting for lines over 20k chars long.

The root cause is our usage of TM Grammars, that are based on regular expressions to match certain regions of the line and generate syntactic tokens. Very skilled grammar authors can write grammars containing regular expressions that have no problem over such long strings, but we have found that is not really the case, as most grammar authors test their grammars on regular source code (i.e. not minified).

We have therefore proceeded to assume that a line over 20k chars is probably generated and not intended for manual editing (before a beautification). The line can still be edited, it's just syntax highlighting that is turned off for it.

**Comment by sdwarwick** [comment] 2017-04-04 09:38
Thanks for the information.  I really hope that we get a solution to unpacking minified code, as now I have to jump to notepad++ to get a readable file..

**Comment by alexandrudima** [comment] 2017-04-04 13:24
@sdwarwick There appears to already be a plugin doing that -- just search the marketplace for `es-beautifier`. I haven't used it, but it seems do to exactly what you need

**Comment by sdwarwick** [comment] 2017-04-04 14:08
thanks! I will. still hoping that vscode can catch up with the rest of the pack in this area without this kind of extra work
