### ISSUE TITLE
The search box and page format

### ISSUE THREAD

**Issue by sorinpopescu** [Microsoft/vscode#43306] opened 2018-02-09 10:59 UTC
### Issue Type
Bug

### Description

If you open a file (I tested in php file) 
- stay on top of the file
- press search key - CTRL + F
- leave the search box open
- scroll the page
- scroll back
- you will see that there is a space (search box height) between the editor top and first line

![image](https://user-images.githubusercontent.com/2951110/36024624-f9935bf0-0d98-11e8-8c8c-999c8cb119a9.png)

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|15.89GB (7.88GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.5
githistory|don|0.4.0
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.1
auto-close-tag|for|0.5.5
vscode-apache|mrm|1.1.1
sublime-keybindings|ms-|3.0.3
vscode-code-outline|pat|0.0.12
highlight-matching-tag|vin|0.4.4

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by rebornix** [comment] 2018-09-05 23:46
Duplicate of https://github.com/Microsoft/vscode/issues/28390

**Closed** 2018-09-05 23:47 UTC
Labels: *duplicate, search-replace
