### ISSUE TITLE
Can you make it potarble？

### ISSUE THREAD

**Issue by switchy1** [Microsoft/vscode#26497] opened 2017-05-11 23:40 UTC
Everything is in the only  one folder.just like this:    https://github.com/garethflowers/vscode-portable

**Comment by egamma** [comment] 2017-05-12 06:27
// @seanmcbreen @kieferrm @chrisdias

**Comment by evandrocoan** [comment] 2017-07-16 09:33
Possible duplicate of:

1. https://github.com/Microsoft/vscode/issues/329 Portable version!

**Comment by kieferrm** [comment] 2017-08-08 22:40
Right. Duplicate of #329.

**Closed by kieferrm** 2017-08-08 22:40 UTC
Labels: feature-request
