### ISSUE TITLE
Cell highlight doesn't show for rendered cells

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122912] opened 2021-05-04 10:39 UTC
* open a notebook with code cell and MD cells
* open quick outline
* navigate through quick outline
* notice how MD cells don't get the yellow background

**Comment by rebornix** [comment] 2021-05-05 16:22
/duplicate of https://github.com/microsoft/vscode/issues/122890.

**Closed** 2021-05-05 16:22 UTC
Labels: *duplicate, notebook, notebook-markdown
