### ISSUE TITLE
No keyboard equivalent of Ctrl/Cmd +Click when multi selecting

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42578] opened 2018-01-30 23:54 UTC
Testing #41473

Ctrl/Cmd+Click is used to mutli select non consecutive items
There is no keyboard equivalent for this.

In #1023 @Tyriar suggests to use `Ctrl+Space` for this

**Comment by Tyriar** [comment] 2018-01-31 00:23
I think ctrl+space is a windows and linux(?) thing, we should do whatever feels natural on the platform.

**Comment by ramya-rao-a** [comment] 2018-01-31 00:37
I was testing on Windows and use of arrows followed by Ctrl+Space seems to be the norm

**Comment by usernamehw** [comment] 2018-01-31 07:46
Duplicate of #41527 ?

**Closed** 2018-01-31 08:52 UTC
Labels: *duplicate
