### ISSUE TITLE
"Go to Next Error or Warning" across files

### ISSUE THREAD

**Issue by pragmascript** [Microsoft/vscode#20172] opened 2017-02-08 05:53 UTC
There should be an option to have 
"Go to Next Error or Warning" `editor.action.marker.next`  and "Go to Previous Error or Warning" `editor.action.marker.prev`
work across different files so it would jump to the file of the error. 
So it would work the same way as clicking the same error in the problems view.

**Comment by jrieken** [comment] 2017-02-10 08:46
dupe of https://github.com/Microsoft/vscode/issues/14783

**Closed by jrieken** 2017-02-10 08:46 UTC
Labels: error-list, feature-request
