### ISSUE TITLE
While Using macOS Sierra's Chinese IME, the first letter can not be in the right position (i18n)

### ISSUE THREAD

**Issue by acbetter** [Microsoft/vscode#18545] opened 2017-01-14 11:58 UTC
- VSCode Version: 1.8.1 (1.8.1)
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. While Using Chinese IME, the first letter can not be in the right position.
<img width="710" alt="screen shot 2017-01-14 at 18 55 47" src="https://cloud.githubusercontent.com/assets/13360124/21954601/b5daeefa-da90-11e6-94b7-e6b5044bb6c5.png">
2. When I input the second letter, everything goes right.
<img width="706" alt="screen shot 2017-01-14 at 18 55 54" src="https://cloud.githubusercontent.com/assets/13360124/21954610/03db2fca-da91-11e6-9b39-9671204cc24c.png">
3. When I delete the second letter, it's inconceivable!
<img width="707" alt="screen shot 2017-01-14 at 18 56 02" src="https://cloud.githubusercontent.com/assets/13360124/21954620/631317aa-da91-11e6-84de-0b6cf3f5fb10.png">
4. This bug don't exist in other app like Google Chrome, PyCharm and so on.
<img width="705" alt="screen shot 2017-01-14 at 19 44 02" src="https://cloud.githubusercontent.com/assets/13360124/21954633/e48fe948-da91-11e6-978b-41c9d2bc2451.png">
5. My IME is Pinyin - Simplified. I have tried other Chinese IME like SougouInput and QQ Pinyin, but the bug always exists.
<img width="668" alt="screen shot 2017-01-14 at 19 46 09" src="https://cloud.githubusercontent.com/assets/13360124/21954639/1e1a7f7a-da92-11e6-8be1-800e7eacfaed.png">
6. While using Vertical Orientation...
<img width="708" alt="screen shot 2017-01-14 at 19 52 54" src="https://cloud.githubusercontent.com/assets/13360124/21954671/17335d02-da93-11e6-94ec-74ec2f474e23.png">

**Comment by alexandrudima** [comment] 2017-01-21 13:59
Duplicate of #356.

**Closed by alexandrudima** 2017-01-21 13:59 UTC
Labels: editor
