### ISSUE TITLE
vscode highlighting cyrillic text in python after update

### ISSUE THREAD

**Issue by David-Valters** [microsoft/vscode#138836] opened 2021-12-10 09:51 UTC
Issue Type: <b>Bug</b>

vscode highlighting cyrillic text in python after update
![зображення](https://user-images.githubusercontent.com/46930139/145554017-99911709-df43-427d-8076-20e6371d4ec6.png)

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.21GB free)|
|Process Argv|--crash-reporter-id be0b0f59-8dd2-4c90-a681-c72299200122|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
jsonviewer|cci|1.2.2
doxdocgen|csc|1.3.2
code-runner|for|0.11.6
todo-tree|Gru|0.0.214
better-cpp-syntax|jef|1.15.10
vscode-language-pack-ru|MS-|1.63.2
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.3
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.4
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5196
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2021-12-10 11:33
Probably #138767

/assign @hediet

**Comment by IllusionMH** [comment] 2021-12-10 11:38
This is part of https://code.visualstudio.com/updates/v1_63#_unicode-highlighting because letters looks like `p` and `e`. See post on how to disable highlight ambiguous characters.

UPS. @gjsjohnmurray Not not sure if it's related to #138767 (if there is locale set) or just confusing for user who might not read updates post.

**Comment by hediet** [comment] 2021-12-10 12:40
@David-Valters you can hover on the highlight and adjust the settings.

Closing as duplicate of #138767, which describes the feature request to use the OS locale rather than VS Code locale.

**Closed by hediet** 2021-12-10 12:40 UTC
Labels: new release
