### ISSUE TITLE
JavaScript Intellisense breaks when the solidty compiler is required.

### ISSUE THREAD

**Issue by MartinNikolovMarinov** [Microsoft/vscode#51758] opened 2018-06-13 11:51 UTC
After a few hours of fruitless browsing, I decided to ask for some help.
Every time I require 'solc' it seems to break the JavaScript intellisense for the entire project.
It's better explained through this GIF :

![lost_intellisense](https://user-images.githubusercontent.com/7342117/41349221-dd4a1746-6f17-11e8-8cca-02d87234846a.gif)

The log output from `tsserver` that I think is relevant  - [log.txt](https://github.com/Microsoft/vscode/files/2097933/log.txt) . You can see `Maximum call stack size exceeded`, and a stack trace that means nothing to me.

* VSCode:
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:37:01.579Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

* OS:
Linux Mint 18.3 Cinnamon 64-bit
Cinnamon Version 3.6.7
Linux Kernel 4.13.0-45-generic

Does this issue occur when all extensions are disabled?: Yes
This could be a problem only on Linux, I haven't tested or reproduced on other machines.
Forgot to mention - the only dependency in `package.json` is solc.

**Comment by mjbvz** [comment] 2018-06-13 17:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/24762

**Closed by mjbvz** 2018-06-13 17:18 UTC
Labels: javascript
