### ISSUE TITLE
Emmet Go to matching pair not working

### ISSUE THREAD

**Issue by dstpierre** [microsoft/vscode#98719] opened 2020-05-28 11:02 UTC
Issue Type: <b>Bug</b>

When editing an HTML file say

```html
<div>
  <div id="level2"></div>
</div>
```

Placing the cursor on the /div at line:3 or the first div at line:1 and doing CTRL+SHIFT+p than Emmet Go to matching pair does not move the cursor.

In fact nothing happen, cursor stays on the div.

VS Code version: Code - OSS 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-17T22:31:53.325Z)
OS version: Linux x64 5.6.14-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3490)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.57GB (10.19GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
elm-ls-vscode|elm|0.10.2
elixir-ls|Jak|0.4.0
csharp|ms-|1.21.18
Go|ms-|0.14.3

</details>

**Comment by greggman** [comment] 2020-07-25 16:49
It doesn't work for me either in JavaScript. Testest with extensions off. Seems like the feature is completely broken.

Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

**Comment by rzhao271** [comment] 2020-10-05 21:35
Cannot reproduce on 1.49.3.
@dstpierre I know it's been months, but I'm wondering whether you can go over those steps again and see if it's fixed on your end, after updating Code?

**Closed** 2020-10-14 11:28 UTC
Labels: emmet, needs more info

**Comment by dstpierre** [comment] 2020-10-14 12:25
@rzhao271 yes I can confirm it's working now, thanks.
