### ISSUE TITLE
editor.rulers not showing when zoomed out

### ISSUE THREAD

**Issue by rtpaulino** [Microsoft/vscode#20246] opened 2017-02-09 02:44 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:21:13.228Z)
- OS Version: Linux x64 4.8.0-37-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.5|
|python|donjayamanne|0.5.8|

---

Steps to Reproduce:

1. Installed lastest version of vscode (1.9.0)
2. File > Preferences > Settings
3. Included: "editor.rulers": [80]`
4. Zoom out
5. The ruler disappear.

Running on Kubuntu 16.10.

**Comment by ianrenauld** [comment] 2017-03-09 18:00
I see the same with version 1.10.2 on Mac.

If I Zoom out once, my ruler disappears.  If I close the pane on the left (Explorer/Search/Git) the ruler reappears.

Also if I zoom out once more, the rule reappears as well, regardless if the left pane is present or not.

**Comment by rimselis** [comment] 2017-04-10 11:24
Same as @ianrenauld on 1.11.1 on Mac Sierra

If I resize the left pane, the ruler "blinks". I'm guessing the line is "too narrow" at some sizes, if that makes sense

![vscode_20246](https://cloud.githubusercontent.com/assets/9070560/24859426/348ddc52-1df9-11e7-82a0-9d3f53343f80.gif)

**Comment by Slaiyer** [comment] 2017-04-14 09:30
I use `"window.zoomLevel": -1`. In addition to rulers, some indentation guides go missing as well:
![341f4e8e-1eb4-11e7-8070-b9c5e31f00ef](https://cloud.githubusercontent.com/assets/1776970/25039767/19f81c2c-2123-11e7-916f-bdd290d568dc.png)

**Comment by alexandrudima** [comment] 2017-04-26 12:38
Duplicate of #9634

**Closed by alexandrudima** 2017-04-26 12:38 UTC
