### ISSUE TITLE
Git - Capitilization in Workspace folder causes issues with staging line changes

### ISSUE THREAD

**Issue by hyltonw** [microsoft/vscode#223337] opened 2024-07-23 15:35 UTC
Type: <b>Bug</b>

Steps:
1. Have files under a workspace in a nested folder
2. change the captilization in the folder name
3. make multiple changes in a file under the nested folder
4. Using the working tree, stage one line of change in the file

Actual:
- The single line is not staged and remains in the working tree
- The entire file is staged as a change

Expected:
- The single line is staged, and no longer shows up in the working tree 

This doesn't happen if instead you stage the entire file.

![VSCodeStaging](https://github.com/user-attachments/assets/c327ec6b-80c1-4d46-b948-fa9a2e74e72c)

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (15.74GB free)|
|Process Argv|--crash-reporter-id ef17c697-4473-4518-a4d7-a4690485c5c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.9.0
gitlens|eam|15.2.0
prettier-vscode|esb|10.4.0
githooks|lak|2.1.1
js-debug-nightly|ms-|2024.7.2217
color-highlight|nau|2.8.0
copy-json-path|nid|0.4.0
material-icon-theme|PKi|5.7.0
quicktype|qui|23.0.170
vscode-yaml|red|1.15.0
code-spell-checker|str|3.0.1
pretty-ts-errors|Yoa|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
pythonrstrctxt:31093869

```

</details>

**Comment by hyltonw** [comment] 2024-07-23 17:53
Along with this the source control tab will show duplicate changed files under the same circumstances. 

![Screenshot 2024-07-23 135131](https://github.com/user-attachments/assets/46e8d9d5-3074-4ff5-b5c9-35f6f4585978)

These both show the same pending changes, and if I stage one of them the other still shows as having outstanding changes. Attempting to stage this second duplicate file does nothing.

**Comment by lszomoru** [comment] 2024-12-12 08:23
Closing as duplicate of [#220541](https://github.com/microsoft/vscode/issues/220541)

**Closed by lszomoru** 2024-12-12 08:23 UTC
Labels: bug, git
