### ISSUE TITLE
Extra padding on top when FindAndReplace widget is opened.

### ISSUE THREAD

**Issue by dragfire** [Microsoft/vscode#40981] opened 2017-12-31 10:16 UTC
- VSCode Version: 1.19.1
- OS Version: 10.12.6

When I open Find widget, there is an extra padding on top. It is shown only when I scrolled up.
![find_low](https://user-images.githubusercontent.com/6277978/34460832-8241914c-ee40-11e7-93f8-9b1cd31ebaa2.gif)
I don't know if it is the intended behaviour or not. It just feels weird.  

Here is what I got when I tinkered around with the source code. 
![find_low_2](https://user-images.githubusercontent.com/6277978/34460851-0fb835b2-ee41-11e7-9ee1-4ee71cf84a94.gif)
I was expecting something like this, this one kind of feels right.

**Comment by usernamehw** [comment] 2017-12-31 14:41
Duplicate of https://github.com/Microsoft/vscode/issues/28390

**Closed** 2018-01-02 14:28 UTC
Labels: *duplicate
