### ISSUE TITLE
No support for PowerShell #Region collapse/expand

### ISSUE THREAD

**Issue by mvanders** [Microsoft/vscode#23798] opened 2017-04-01 16:07 UTC
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

When opening PowerShell code, I cannot collapse/expand #Region XXX which is very annoying when reading lots of blocks of code...

**Comment by aeschli** [comment] 2017-04-03 07:42
duplicate of #4285

**Closed by aeschli** 2017-04-03 07:42 UTC
