### ISSUE TITLE
Errors are not cleared after closing the typescript file

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#61683] opened 2018-10-24 08:42 UTC
- Open a ts file
- Generate some errors (do not save the file)
- Problems view show errors
- Close the file and choose not to save
🐛 Errors are still shown

**Note:** Debugged that typescript is not clearing the diagnostics.

**Comment by mjbvz** [comment] 2018-10-24 22:45
Duplicate of #59363

**Closed by mjbvz** 2018-10-24 22:45 UTC
