### ISSUE TITLE
Latest Update To 1.48 Broken Semantic Highlighting?

### ISSUE THREAD

**Issue by KevinJ1978** [microsoft/vscode#104650] opened 2020-08-14 12:19 UTC
Issue Type: <b>Bug</b>

The console.log color in Javascript has gone back to being blue (Dark Mode) instead of green after the update to 1.48.  This bug was introduced back in February, but could be fixed by disabling semantic highlighting ("editor.semanticHighlighting.enabled": false,).

Reverting back to 1.47 has fixed this.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Zaseth** [comment] 2020-08-14 12:25
In Javascript:
![image](https://user-images.githubusercontent.com/24899039/90249023-087b7700-de3a-11ea-9fa1-b3d37766d7e4.png)

**Comment by resetus** [comment] 2020-08-14 16:40
Hi, a have this problem too **v1.48.0**, JS, `semanticHighlighting: false`

**Comment by MidSpike** [comment] 2020-08-14 17:43
I am also experiencing this issue since updating to `1.48.0`
I have `semanticHighlighting` set to `false` in my settings.

Expectation in JavaScript: `console` should be a different color than a random variable

**Comment by Divlo** [comment] 2020-08-15 23:58
Same problem here, I have `"editor.semanticHighlighting.enabled": false` in my settings.json and `console` is blue but it should be green. Any workaround until there is a fix ?

**Comment by Wavekip** [comment] 2020-08-17 07:00
Same problem here.  `"editor.semanticHighlighting.enabled": false` not work at vscode version **1.48.0**, but it work good before version **1.48.0**

**Comment by aeschli** [comment] 2020-08-17 08:47
This was a change to the TypeScript grammar:
https://github.com/microsoft/vscode/commit/a877e0528e916644982b179ea6a18229bec9a519

**Comment by Divlo** [comment] 2020-08-17 09:17
Alright, there should be an option in settings.json, to revert it back like in 1.47. @aeschli

**Comment by mjbvz** [comment] 2020-08-17 19:16
Duplicate of #104616

**Closed by mjbvz** 2020-08-17 19:16 UTC

**Comment by ret394** [comment] 2020-09-01 18:18
not only is https://github.com/microsoft/vscode/issues/104616 a duplicate, but is a quality thread, good read about software dev.

thanks
