### ISSUE TITLE
"Implement interface XYZ" - invalid result, missing newline

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57211] opened 2018-08-25 21:06 UTC
- Have this code

```ts
import { IDataSource } from 'vs/base/parts/tree/browser/tree';

export class MyDataSource implements IDataSource {

}
```

- Run "Implement interface IDataSource" on the class
- Result:

```ts
export class MyDataSource implements IDataSource {
	getId(tree: ITree, element: any): string {
		throw new Error('Method not implemented.');
	}	hasChildren(tree: ITree, element: any): boolean {
		throw new Error('Method not implemented.');
	}
	getChildren(tree: ITree, element: any): TPromise<any> {
		throw new Error('Method not implemented.');
	}
	getParent(tree: ITree, element: any): TPromise<any> {
		throw new Error('Method not implemented.');
	}
	shouldAutoexpand?(tree: ITree, element: any): boolean {
		throw new Error('Method not implemented.');
	}


}
```

`hasChildren` needs a newline before it, and colorization is broken (not sure if it's syntactically valid or not?)

**Comment by mjbvz** [comment] 2018-09-04 21:01
Duplicate of https://github.com/Microsoft/TypeScript/issues/26550

**Closed by mjbvz** 2018-09-04 21:01 UTC
