### ISSUE TITLE
Syntax Highlighting strange

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#4302] opened 2016-03-16 11:13 UTC
- VSCode Version: Version 0.10.11 (0.10.11)
- OS Version: OS X 10.10.5

Steps to Reproduce:

1) Write code as screenshot below

<img width="1280" alt="screen shot 2016-03-16 at 11 12 11" src="https://cloud.githubusercontent.com/assets/3898363/13810500/145a3a76-eb68-11e5-9410-7e1eb4a8edd9.png">

2) Observe strange highlighting on variable names

**Comment by aeschli** [comment] 2016-03-16 14:14
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by aeschli** 2016-03-16 14:14 UTC
