### ISSUE TITLE
Release 1.5 Quick Open never finishes and Activity Monitor shows high CPU

### ISSUE THREAD

**Issue by jpconsi** [Microsoft/vscode#12047] opened 2016-09-14 21:14 UTC
- VSCode Version: 1.5.2
- OS Version: Max OSX 10.11.5

Steps to Reproduce:

1. In Visual Studio Code editor, Command P.  Type in a file to search for.  It searches but never finishes.  
2. Open Activity Monitor and it shows find using high cpu 80% and Code Helper using 120%.  

3.  Have to force quit find and Code Helper in order to recover. 

Note: In prior versions I was using Command E and it worked great.  In version 1.5.1 that was taken away so I had to start using Command P and it has never worked the same. 

![image](https://cloud.githubusercontent.com/assets/531028/18530280/d4e2dcec-7a9e-11e6-801e-66b57ddf6e89.png)

**Comment by chrmarti** [comment] 2016-09-15 15:10
@jpconsi There is a performance regression in 1.5.x when there are large excluded folders which is fixed with #11874 in the 'insiders' build. Let me know if that fixes it if you get a chance to give the insiders build a try.

Might also be a combination of issues you see, marking as duplicate of #11963.

**Closed by chrmarti** 2016-09-15 15:10 UTC
Labels: duplicate

**Comment by jpconsi** [comment] 2016-10-03 14:54
I tried code insider 1.6.0  and it still consumes heavy cpu and never finishes.  See below screen shot
![image](https://cloud.githubusercontent.com/assets/531028/19041807/9121e49a-8957-11e6-916d-0f767927eff5.png)


![image](https://cloud.githubusercontent.com/assets/531028/19041793/7dfc3046-8957-11e6-9e05-2b710b98a866.png)

**Comment by jpconsi** [comment] 2016-10-03 15:15
Ran this command:  time (find -L . -type f|wc -l); echo $?
 3572161

real	6m6.056s
user	0m5.891s
sys	1m49.988s

The above was with regular VS Code.

Below is with Insider VS Code. Note, I have no excluded files defined user settings on the VS Code Insider.  

time (find -L . -type f | wc -l); echo $?
 9700987

real	9m37.093s
user	0m13.694s
sys	3m26.524s

**Comment by jpconsi** [comment] 2016-10-03 15:20
Here is a screen shot of a search for "auth" 
![image](https://cloud.githubusercontent.com/assets/531028/19042770/523fc5f4-895b-11e6-8071-36e0879a87c2.png)

**Comment by chrmarti** [comment] 2016-10-03 15:24
@jpconsi Thanks for letting me know. Did you run the `time (find ...)` commands while in your project's folder? It tells us how many files are in your current folder and the two numbers (3.5 millions vs. 9.7 millions) are not the same.

**Comment by jpconsi** [comment] 2016-10-03 16:28
Reading the other post.  I ran ps aux| grep <pid> of the code helper that was taking high cpu.  Found that it was fileWatcher.  I had already had many files paths excluded.  This is my final version that seems to be keeping CodeHelper (fileWatcher) from running over 100% cpu.  Originally, I had "**/node_modules":true   I find that it does not work.  I had to add ** at the end as shown in the below example.

"files.watcherExclude": {
         "**/node_modules/**": true,
         "**/node-server/**": true,
        "**/*.js": true,
        "**/*.js.map": true,
        "**/tmp/**": true,
        "**/dist/**": true,
        "**/*.config": true,
        "**/*.css" : true,
        "**/*.svg" : true,
        "**/*.scss" : true,
        "**/*.json" : true,
        "**/*.d.ts" : true,
        "v1.0/tmp/**" : true,
         "**/.git": true,
        "**/.hg": true,
        "**/.DS_Store": true
    },

**Comment by jpconsi** [comment] 2016-10-03 16:52
@chrmarti I did not realize what the time (find ...  thing was doing)  I have multiple projects so I ran that on any project I was in.  Below is the largest project.   
real	9m20.653s
user	0m12.609s
sys	3m4.477s

**Comment by chrmarti** [comment] 2016-10-03 17:05
What do your `"files.exclude"` and `"search.exclude"` settings look like? `"files.watcherExclude"` is only applied to the automatic pick-up of changes on disk, not the QuickOpen functionality.

Btw., you can use single backticks to include the patterns within text and tripple backticks to include the patterns as a block. (See `Code` tab: https://guides.github.com/features/mastering-markdown/#examples)
