### ISSUE TITLE
Maximizing with new custom title bar places window in wrong position

### ISSUE THREAD

**Issue by matkateresa** [Microsoft/vscode#52694] opened 2018-06-22 14:49 UTC
- VSCode Version: 1.25.0-insider
- OS Version: Windows 10 Education 1803

Steps to Reproduce:

1. Maximize and maximize your window in a sequence and the bug should occur 

gif with the problem here https://i.gyazo.com/c794e06fde86bfa3f5fc6e32ca038d1c.mp4
sorry for the resolution but you should be able to see what's happening 

As you can see it places the window over my taskbar and it disappears after i minimize and maximize it again

Does this issue occur when all extensions are disabled?: Yes

**Comment by iansan5653** [comment] 2018-06-22 15:42
This only seems to happen every other time you maximize the window.

**Comment by yume-chan** [comment] 2018-06-23 03:14
Duplicate of #52265

**Closed** 2018-06-25 10:48 UTC
Labels: *duplicate
