### ISSUE TITLE
Mac: File events broken at random times

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5819] opened 2016-04-26 12:28 UTC
- VSCode Version: Alpha - e77003fd6ca90d944feb572b54fc1d122d91d704
- OS Version: El Capitan

Steps to Reproduce:

1. Open any file in vscode
2. Make changes to that file outside of vscode, vscode is not picking up changes

File events seem to be completely broken for me, as git is also not picking up file event changes

**Comment by bpasero** [comment] 2016-04-26 12:44
@isidorn next time please run with "code-alpha --verbose" so that we can see the raw file events.

**Comment by bpasero** [comment] 2016-04-26 14:56
Still happening. Idea is to provide a flag to bring file watcher into debug mode so that we can debug this.

**Comment by bpasero** [comment] 2016-04-27 05:05
@isidorn today please do this:
* run code from command line with `--debugBrkFileWatcherPort=6868`
* this will cause the file watcher to break on first line so you need to attach a debugger to have file events
* start an insider build as debugger on vscode workspace
* set a breakpoint into https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/watcher/unix/chokidarWatcherService.ts#L51
* attach to the debug port
* make changes in the alpha instance and verify the breakpoint is hit
* remove the breakpoint, work as usual until file events stop working

Once file events dont work anymore, please check if the breakpoint is hit after all. If not, can you set breakpoints into the chokidar library, e.g. into `fsevents-handler.js#68` where the raw events from the native fsevents library hit chokidar library?

Btw it seems that the debug port survives when you change the folder in VSCode, so you have to keep in mind to reattach the debuger.

Note: Do not open more than one window in this scenario because the port will be used for the second window and that can only fail.

**Comment by isidorn** [comment] 2016-04-27 09:55
Got it, will do it today. However signing is broken and unsigned is not working due to #5542
@joaomoreno are there some updates with signing?

**Comment by joaomoreno** [comment] 2016-04-27 10:15
@isidorn First I've heard of it.

**Comment by isidorn** [comment] 2016-04-27 15:35
@bpasero ok tried this scenario. Once I attach to the watcher from VSCode insider I see that it is stopped in bootstrap.js, when I say continue I still do not get file events in VSCode alpha.
Also I can not get those breakpoints to hit, and file events just do not work.

**Comment by isidorn** [comment] 2016-04-28 13:46
@bpasero I now have a theory that this was always happening because of the casing. I am always navigating back and forth using `open recent`, and if the wrong case path once gets in your history you are **doomed** as some might say.
So I believe this is a dupe of wrong casing makes file watching broken on mac

**Comment by bpasero** [comment] 2016-04-29 06:31
@isidorn happy to hear that, I will fix the issue in May, so closing as duplicate of https://github.com/Microsoft/vscode/issues/5904

**Closed by bpasero** 2016-04-29 06:31 UTC
Labels: bug, important, needs more info
