### ISSUE TITLE
Chrome debug process left lying around

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19209] opened 2017-01-24 14:32 UTC
OS X
refs: https://github.com/Microsoft/vscode/issues/19110

1. Take the latest chrome debug vsix from [here](https://github.com/Microsoft/vscode/issues/19110#issue-202734053)
2. Install it in insiders and open vscode repository, choose launch vscode
3. Notice how the debugger can not attach - this is captured in a different bug
4. Stop the debug session, click on stop twice - this should kill the debug extension
5. Activity monitor - however the chrome extension is still running with 100% cpu as a code helper

Assigning to @weinand since he authored this [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L493) and @roblourens  since his extension seems to go into a weird state

![screen shot 2017-01-24 at 15 31 28](https://cloud.githubusercontent.com/assets/1926584/22251178/32726cca-e24a-11e6-8e6a-443b54279769.png)

**Comment by roblourens** [comment] 2017-01-24 16:27
Dupe of https://github.com/Microsoft/vscode-chrome-debug/issues/333

**Closed by roblourens** 2017-01-24 16:27 UTC
Labels: bug, debug

**Comment by isidorn** [comment] 2017-01-24 18:02
@weinand but should we still be able to kill the process even though if it is in a bad state right? We can not rely on extensions always being in a good state, we should always be able to kill them
