### ISSUE TITLE
Format of HTML document collapses the structural view

### ISSUE THREAD

**Issue by PandiyanCool** [Microsoft/vscode#17267] opened 2016-12-15 08:14 UTC
- VSCode Version: 1.8
- OS Version: Windows 7

Steps to Reproduce:

1. Enter the following code in html document
```
<div>
    <div>
        <div style="font-size: 12px;"> Hello there!
             </div>
    </div>
</div>
```
2. Format the document (Alt+Shift+F)
It provides following format.

```
<div>
    <div>
        <div style="font-size: 12px;"> Hello there!
</div>
</div>
</div>
```

Format document is properly working for me on v1.7.2 which I have in my another machine.

**Comment by mjamin** [comment] 2016-12-15 08:51
Can confirm similar issues, e.g.

```
<div>
    <div></div>
</div>
```

is formatted fine. When adding a style attribute to the container div, the result is not properly intended:

```
<div style="color:black">
<div></div>
</div>
```

**Comment by PandiyanCool** [comment] 2016-12-15 08:56
@mjamin Yes that's right.

**Comment by mobilemancer** [comment] 2016-12-15 10:47
Seems that the style tag is breaking HTML formatting after the element it's used on, whatever element it's used on (even on custom elements).

**Comment by aeschli** [comment] 2016-12-29 03:36
duplicate of #17849

**Closed by aeschli** 2016-12-29 03:36 UTC
