### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:8087

### ISSUE THREAD

**Issue by yangbing007** [Microsoft/vscode#17982] opened 2017-01-01 11:26 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment] 2017-01-02 05:58
Since there is no reproduce steps and no description of what happened, we can't tell what's happening there. Close it first and reopen it when the description is there.

**Closed by rebornix** 2017-01-02 05:58 UTC
