### ISSUE TITLE
Support creating new folder in simple file dialog

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#94531] opened 2020-04-06 12:27 UTC
Currently I cannot use the open folder dialog to open a new folder, this is my preferred way to open a new folder in Windows and it doesn't work with the custom dialog:

![image](https://user-images.githubusercontent.com/2193314/78558246-1d2e6b00-77c7-11ea-9141-93fdd4031a83.png)

**Comment by alexr00** [comment] 2020-04-06 14:48
Duplicate of https://github.com/microsoft/vscode/issues/71425

**Closed by alexr00** 2020-04-06 14:48 UTC
