### ISSUE TITLE
ENH: Please add `editor.action.inlineSuggest.acceptNextLine` similar to existing `editor.action.inlineSuggest.acceptNextWord`

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/vscode#173962] opened 2023-02-09 16:02 UTC
The newly announced feature `editor.action.inlineSuggest.acceptNextWord` is nice, together with the Copilot extension.

It would be nice if there was a corresponding `editor.action.inlineSuggest.acceptNextLine` command to more quickly accept parts of long suggestions.

I often get Copilot suggestions that are a dozen lines or more. Sometimes, I just want the first 4. Right now, this means accepting all and deleting 8 lines. If the issue #173960 wasn't there, I could accept 40 words, but this is also not quite as nice as just accepting 4 lines in one go.

I've also commented here: https://github.com/community/community/discussions/46874

**Comment by docwilco** [comment] 2023-03-02 13:40
Also, please make `undo` into `undoWord` and add a `undoLine`. That would make the accepting very smooth.

**Comment by hediet** [comment] 2023-04-14 18:44
/duplicate of https://github.com/microsoft/vscode/issues/173209

**Closed by hediet** 2023-04-14 18:44 UTC
Labels: feature-request, inline-completions
