### ISSUE TITLE
Feature-Request: Ability to Login to Microsoft to Sync settings across all computers (Like in Visual Studio Pro)

### ISSUE THREAD

**Issue by CryptoJones** [Microsoft/vscode#18226] opened 2017-01-06 15:36 UTC
- VSCode Version: Any
- OS Version: Any

Would like to be able to login to my Microsoft account and sync my VS Code Settings across all my installations. This is done in Visual Studio Pro.

**Comment by pavankumarkatakam** [comment] 2017-02-15 08:07
I'm also thinking this feature like if we download new vscode and login it should sync extensions, preferences etc.

**Comment by shanalikhan** [comment] 2017-05-07 19:10
Have you guys tried this extension
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by yfdyh000** [comment] 2017-05-23 14:59
Duplicate of #7311.

**Comment by bpasero** [comment] 2017-06-03 07:36
https://github.com/Microsoft/vscode/issues/2743

**Closed by bpasero** 2017-06-03 07:36 UTC
