### ISSUE TITLE
Cannot Move Folder

### ISSUE THREAD

**Issue by hexxone** [microsoft/vscode#190816] opened 2023-08-19 21:27 UTC
Type: <b>Bug</b>

1. Open Project
2. Try to move Folder
3. It loads forever and fails

![image](https://github.com/microsoft/vscode/assets/5312542/3557d6a1-ecfc-43e6-b40e-7120d17c738c)

4. Close Vscode
5. Open Vscode
6. Try to move Folder
7. It loads forever and fails

Sadly I cannot share the project itself.
But this has been happening on multiple occasions now.

Moving the file with explorer still works.

If it happens one one of my personal public projects again, I will add another comment / edit this one.

Possible related to <https://github.com/microsoft/vscode/issues/184145> because it is the exact same error message.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (44.27GB free)|
|Process Argv|--crash-reporter-id 35f367c9-e674-4e64-9fb9-6b8694ff912a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
classdiagram-ts|Ale|0.1.67
nugetpackagemanagergui|ali|2.0.6
tsl-problem-matcher|amo|0.6.2
vscode-color-picker|Ant|0.0.4
assemblyscript-lang|bat|0.3.2
vscode-intelephense-client|bme|1.9.5
solargraph|cas|0.24.0
npm-intellisense|chr|1.4.4
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
vscode-wasm|dts|1.4.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
vscode-typescript-exportallmodules|eli|2.6.0
prettier-vscode|esb|10.1.0
vscode-firefox-debug|fir|2.9.8
dotnet-test-explorer|for|0.7.8
visual-nuget|ful|0.2.1
vscode-yarn|gam|2.1.0
vscode-codeql|Git|1.8.10
go|gol|0.39.1
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
vscode-computercraft|Jac|1.1.1
jbockle-format-files|jbo|3.4.0
vscode-wasm-syntax-lite|jcm|0.3.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vsc-python-indent|Kev|1.18.0
linecounter|lyz|0.2.7
react-typescript-boilerplate|Mag|0.2.2
Kotlin|mat|1.7.1
rainbow-csv|mec|3.7.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.26.0
vscode-language-pack-de|MS-|1.81.2023081609
csharp|ms-|2.0.376
vscode-dotnet-runtime|ms-|1.7.0
vscode-edge-devtools|ms-|2.1.3
vscode-kubernetes-tools|ms-|1.3.13
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.30
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.3
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
live-server|ms-|0.4.9
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.1
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5877
material-icon-theme|PKi|4.29.0
sqlite-viewer|qwt|0.3.13
webgl-glsl-editor|rac|1.3.6
java|red|1.21.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
synthwave-vscode|Rob|0.1.15
shopify-liquid|sis|3.2.2
shader|sle|1.1.5
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.53.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
volar|Vue|1.8.8
vscode-ruby|win|0.28.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by lramos15** [comment] 2023-08-21 14:49
I will close as duplicate of #184145 as I believe it is the same. If once #184145 is fix it is still broken we can revisit

**Closed by lramos15** 2023-08-21 14:49 UTC
