### ISSUE TITLE
VSCode opens off-screen

### ISSUE THREAD

**Issue by robinsh** [Microsoft/vscode#35148] opened 2017-09-26 17:33 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.0.0
yaml|ada|0.0.9

---

Steps to Reproduce:

I have a Surface tablet with two external monitors. This problem has popped up recently, because it used to work and now it doesn't. I don't know if it's a problem with Windows or with VSCode. It affects VSCode and PowerShell ISE.

1. Open VSCode.
2. Drag the window to one of the external monitors.
3. Close VSCode. 

Next time you open it, it will be off the screen and you won't be able to see it. I know it's off-screen because when you click on the icon a couple of times, you can see it minimizing it and then reopening it off-screen. 

To make it appear again, you have choices.
1. Disconnect the external monitors, at which point Windows moves all open Windows to the Surface tablet. Reconnect the external monitors and move all the windows back to where they were. 
2. Make sure the window is selected, click Alt+Space, M, then use the arrows to move it down until you can see it. 

Also, you can make sure you drag the last open VSCode window back to the Surface tablet before closing it. Then next time you open it, it will appear there and you can drag it back to the external monitor. 

Reproduces without extensions: Yes/No
I don't know. Seems hard to believe that a YAML extension would cause a problem with the application showing up within the screen boundaries.

**Comment by asmundwego** [comment] 2017-10-12 08:36
This is still an issue for me. I have a Dell ZBook laptop with external monitor in addition to the built-in laptop monitor. If I close VS Code on the external monitor, the next time I open it, the position is not the same, and usually parts of window is outside screen.

**Comment by robinsh** [comment] 2017-10-12 16:42
@asmundwego It is still an issue for me as well.

**Comment by bpasero** [comment] 2017-10-13 04:51
@asmundwego @robinsh to be clear, you are seeing the window not restoring at the proper location right? You are not seeing it "off" screen (= invisible)?

**Comment by robinsh** [comment] 2017-10-16 18:03
For me, it is "off screen", i.e. invisible. To get it back, I have to either disconnect the external monitors, at which point Windows moves all open windows to the Surface tablet, or use Alt-Space + M, and then use the cursor keys to move the screen down.

Steps to repro: 1. Open VS Code, move it to one of the external monitors. 2. Close VS Code. 3. Open VS Code, it's off screen. 

I have a Surface 4 Pro tablet connected to two external monitors using a docking station. (Had the same problem with the tablet connected to just one external monitor.)

**Comment by bpasero** [comment] 2017-10-17 04:00
@robinsh ok so your problem seems to be different from what I had in mind where you would start in a multi monitor setup, close VS Code, disconnect the external monitors (or actually change their arrangement) and then start VS Code again. 

Your case seems to be that the position of VS Code changes just by restarting VS Code and without doing anything with the monitors, is that right? If so, does it change anything if you move the window to the upper left corner of one monitor (not maximized), e.g. making it a quarter the size of the monitor and then restart? Does it only partially get offscreen?

**Comment by felubra** [comment] 2017-10-17 13:26
This issue seems related with different display DPIs.
I have a laptop with:
- Embeded 1080p display set to 125% DPI scaling
- External 1080p monitor set to 100% DPI scaling.
When the two displays have the same DPI setting, the issue does not happen, i.e. the window positioning is not off screen when opening the VS Code.

**Comment by bpasero** [comment] 2017-10-17 14:52
@felubra can you clarify what you mean with "off screen" exactly: is the entire window no longer visible or just parts of the window outside the screen?

**Comment by bpasero** [comment] 2017-10-17 14:53
@robinsh I just tried to reproduce your issue, have a similar setup (1 SurfaceBook, 2 external monitors) and could not. Could you tell me your setup in more detail, specifically:
* monitor arrangement
* resolutions of monitors
* exact steps

**Comment by felubra** [comment] 2017-10-17 16:08
@bpasero just parts of the window but in a new test, with a created test user, I've noticed that the window goes futher away after each start of VS Code, going completely completly off-screen after some starts.

**Monitor arrangement**: two, side by side. In the follow image,  "1" is the embeded screen, "2" is the external one, both are setup at 1920x1080 resolution.
![image](https://user-images.githubusercontent.com/25326257/31674114-bf540506-b33f-11e7-94f5-757def91066a.png)

**Steps to reproduce**:

1. Set-up the two monitors with different DPI scales, one at 125% (main), another at 100% (external).
2. Open VS Code, the window should be at the center of the main monitor desktop, in restored state (not maximized).
3. Move the window to the center of external's desktop, keep window in restored state.
4. Close VS Code
5. Open VS Code: the editor window is at the external monitor desktop, not at the center or already partially off-screen.
6. Close VS Code.
7. Open VS Code: the window is futher away of the center, or completely off-screen.

After the step 5, you could alternatively create a new window (menu File > New Window)
In my case I've notice the the window goes up and to the right after each start.

**Comment by robinsh** [comment] 2017-10-17 19:39
![monitor_setup](https://user-images.githubusercontent.com/14022760/31685355-7eac4886-b337-11e7-9115-7b927174e4bd.png)
This is my monitor setup. The surface tablet is set to scale 200%. Resolution is 2736x1824. 
The external monitors are 1920x1080, scale is 100%.

I've already given the exact steps twice. They really are that simple. 

re: Your case seems to be that the position of VS Code changes just by restarting VS Code and without doing anything with the monitors, is that right? **YES.**
If so, does it change anything if you move the window to the upper left corner of one monitor (not maximized), e.g. making it a quarter the size of the monitor and then restart? Does it only partially get offscreen?  --> **Nope, completely off screen. But hey, it's on the left of that monitor. So it seems the problem may just be on the y-axis, and not the x-axis. In this case, anyway.**

**Comment by bpasero** [comment] 2017-10-18 15:13
Thanks, I can reproduce the issues and believe they are all caused by https://github.com/Microsoft/vscode/issues/36122 which I am closing this one as duplicate of. Bottom line is that I am setting coordinates for a window and they end up outside of the monitor.

**Closed by bpasero** 2017-10-18 15:13 UTC
Labels: bug, needs more info, workbench
