### ISSUE TITLE
Terminal shows no content

### ISSUE THREAD

**Issue by thomaspeng90s** [microsoft/vscode#117333] opened 2021-02-23 08:48 UTC
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Ctrl+Shift + ` Open a Terminal
2. The terminal does not display any content
3. Toggle Developer Tools and it  shows : ERR A system error occurred (ENOENT: no such file or directory, scandir 'C:\Users\**\AppData\Local\Microsoft\WindowsApps'): Error: ENOENT: no such file or directory, scandir 'C:\Users\**\AppData\Local\Microsoft\WindowsApps'

Does this issue occur when all extensions are disabled?: Yes

It worked well weeks ago. I didn't upgrade my system or vscode.
And I have reinstall VS Code several times but it didn't help anything.

![terminal](https://user-images.githubusercontent.com/25027712/108819325-ae801900-75f5-11eb-9771-f18be38a4d53.png)
![ERROR](https://user-images.githubusercontent.com/25027712/108819412-ca83ba80-75f5-11eb-9439-4e58bd27fc52.png)

**Comment by meganrogge** [comment] 2021-02-24 20:53
what do you have `terminal.integrated.cwd` set to?

**Comment by thomaspeng90s** [comment] 2021-02-25 03:26
> what do you have `terminal.integrated.cwd` set to?

I never set my terminal.intergrated.cwd
![image](https://user-images.githubusercontent.com/25027712/109098418-413ac800-775c-11eb-948b-2806e06ee667.png)

**Comment by blopez2010** [comment] 2021-02-25 15:30
That is happening to me as well, I don't like powershell as terminal and yesterday I went to change it to GitBash. Since then, I'm not able to run neither GitBash or rollback to Powershell.

Steps:

1. Ctrl + ,
2. Open settings as json.
3. Replaced the content from `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",` with `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",`
4. Closed vscode and reopened.
5. Waiting to fully load vscode.
6. Finally got the same error as @thomaspeng90s  is having.
7. Then I went to https://code.visualstudio.com/docs/editor/integrated-terminal for documentation.
8. Applied the steps for Git Bash.
9. Closed vscode and reopen it.
10. Same error.

I tried to rollback to powershell, closing vscode and reopen it with no luck.

I the Log (Window) tab this is what I got

```
[2021-02-25 08:25:15.835] [renderer1] [error] cannot open file:///c%3A/Code/Web/next-js/bower.json. Detail: Unable to read file 'c:\Code\Web\next-js\bower.json' (Error: Unable to resolve non-existing file 'c:\Code\Web\next-js\bower.json'): Error: cannot open file:///c%3A/Code/Web/next-js/bower.json. Detail: Unable to read file 'c:\Code\Web\next-js\bower.json' (Error: Unable to resolve non-existing file 'c:\Code\Web\next-js\bower.json')
    at file:///C:/Users/BLopez/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:109144
[2021-02-25 08:25:25.734] [renderer1] [error] Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at Object.r [as parseHex] (file:///C:/Users/BLopez/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3:150962)
    at Function.fromHex (file:///C:/Users/BLopez/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3:147221)
    at q.getArgs (file:///C:/Users/BLopez/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:978:8253)
    at q.onUpdate (file:///C:/Users/BLopez/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:978:7803)
    at new q (file:///C:/Users/BLopez/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:978:6397)
    at ee.activate (file:///C:/Users/BLopez/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:978:9112)
    at e.loadAddon (C:\Users\BLopez\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1:74708)
    at e.loadAddon (C:\Users\BLopez\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1:80554)
    at Jt._createXterm (file:///C:/Users/BLopez/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2638:89477)
```

Same as @thomaspeng90s I have never set the `terminal.intergrated.cwd`.

This is what I got, please let me know if you need anything else from my end.

**Comment by meganrogge** [comment] 2021-02-26 19:07
Are you sure your path to bash.exe exists here?
`"C:\\Program Files\\Git\\bin\\bash.exe"`

**Comment by thomaspeng90s** [comment] 2021-02-27 01:47
> I think both of your errors are caused by incorrect paths to the shell. What happens if you remove that setting, so it goes with the default path?
> 
> and @thomaspeng90s, what is your `"terminal.integrated.shell.windows"` set to?

The editor told me that "Unknown Configuration Setting"  when I tried to set "terminal.integrated.shell.windows" 
![image](https://user-images.githubusercontent.com/25027712/109371630-c3ec9000-78e0-11eb-970d-c150d44a38b8.png)

**Comment by blopez2010** [comment] 2021-02-27 02:11
@meganrogge I have checked the location of git-bash exists in that path and it does. Also, tried to remove the node, restart vscode and same error is thrown.

**Comment by meganrogge** [comment] 2021-03-01 16:39
Duplicate of #117123

**Closed** 2021-03-01 16:39 UTC
Labels: *duplicate, needs more info
