### ISSUE TITLE
Editor does not respond properly to horizontal scrolling with mouse.

### ISSUE THREAD

**Issue by keyboarder** [microsoft/vscode#110093] opened 2020-11-06 16:18 UTC
Issue Type: <b>Bug</b>

Unlike most other programs (Office products, Visual Studio Pro, browsers), Visual Studio Code does not scroll horizontally using the mouse.  It only accepts the scrollbar clicking or keyboard arrows.
It seems to be ignoring messages for horizontal scrolling.  There is no obvious reason why Visual Studio Code should not behave as expected.  It's a basic windows behavior.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (4.67GB free)|
|Process Argv|C:\Users\cperkins\Documents\KM Technology\ERA --crash-reporter-id 5af3c744-1b27-47a1-8639-6260070c21b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.5
cpptools|ms-|1.1.0

</details>

**Comment by alexdima** [comment] 2020-11-06 20:25
@keyboarder When using Shift+mouse wheel, VS Code will scroll horizontally. What gesture do you do exactly for horizontal scrolling that does not work? Do you have a special mouse with two mouse wheels? (one for horizontal scrolling?)

**Comment by keyboarder** [comment] 2020-11-06 23:35
Logitech Options has a "pan" gesture which allows using the mouse movement to reposition the document horizontally and vertically simultaneously.  There is also a Scroll Left and Scroll Right gesture that can be assigned individually to various buttons and movement.  Similar behavior has been available forever on Windows (although technically uncertain if it was all through Logitech's drivers).  As already mentioned, this behavior works in many, many other applications.

Sometimes the horizontal scroll will sudden jump just one time, but then never move again.  So it apparently receiving the message, but just not processing it properly.

The Shift+wheel is better than nothing, but rather annoying and requires both hands.

**Comment by alexdima** [comment] 2020-11-20 15:31
Duplicate of #84136

**Closed by alexdima** 2020-11-20 15:31 UTC
Labels: needs more info
