### ISSUE TITLE
Test platform specific extensions - Publishing to multiple targets

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#134066] opened 2021-09-28 22:56 UTC
Testing #133868

Let's say I want to publish my extension to `darwin-x64`, `linux-x64` and `win32-x64`, is there a way I can do that as a `vsce` one-liner? Or do I need to run `vsce publish <platform>` multiple times?

**Comment by joaomoreno** [comment] 2021-09-29 08:00
Dupe of an internal issue. Closing for now.

**Closed by joaomoreno** 2021-09-29 08:00 UTC
