### ISSUE TITLE
Cannot persist / load GitHub Authentication SignIn Token to macOS Ventura Beta 2 Keychain

### ISSUE THREAD

**Issue by alexanderniebuhr** [microsoft/vscode#152964] opened 2022-06-23 11:11 UTC
Issue Type: <b>Bug</b>

Using the latest macOS 13.0 Beta (22A5286j), I experience an issue / bug that reloading Window or restarting logs me out of all the extensions, e.g. Copilot, Settings Sync, Github Issues & Pull Request. 

VS Code version: Code - Insiders 1.69.0-insider (668c538b8d2fec1258ed786ae212124d6d68023c, 2022-06-23T05:16:19.393Z)
OS version: Darwin arm64 22.0.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 39, 28|
|Memory (System)|64.00GB (40.71GB free)|
|Process Argv|--crash-reporter-id 092694b8-f2ad-4473-8608-b513d685cc96|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
iconify|ant|0.3.3
vscode-eslint|dba|2.2.2
gitlens-insiders|eam|2022.6.2205
prettier-vscode|esb|9.5.0
copilot-labs|Git|0.1.176
copilot-nightly|Git|1.30.6180
vscode-pull-request-github|Git|0.44.0
better-shellscript-syntax|jef|1.1.0
i18n-ally|lok|2.8.1
vscode-docker|ms-|1.22.0
remote-containers|ms-|0.240.0
vscode-github-issue-notebooks|ms-|0.0.119
material-icon-theme|PKi|4.18.1
fortnite-vscode-theme|sdr|1.3.0
svelte-vscode|sve|105.17.0
windicss-intellisense|voo|0.23.5

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506
c4g48928:30513948

```

</details>

**Comment by Athayde3586** [comment] 2022-06-23 11:43
A asked y'all nicely

**Comment by rotu** [comment] 2022-06-24 03:12
I'm experiencing the same. Same log messages, also on the MacOS Beta.

**Comment by und3fined** [comment] 2022-06-24 06:50
I have same issue. Any way for fix it?

**Comment by alexanderniebuhr** [comment] 2022-06-24 07:06
I tried to login with a different Macbook and transferring the token manually to the keychain. Even this made it possible to get a prompt, it still breaks with the same error. Therefore I expect some changes in the behaviour the keychain is working, and VSCode might to adapt. :(

**Comment by TylerLeonhardt** [comment] 2022-06-24 17:24
I'm suspicious of this new Passkeys feature in Ventura:
![image](https://user-images.githubusercontent.com/2644648/175611303-964fb6ca-8ac2-4a0e-b281-c35b1a356379.png)

which mentions iCloud Keychain...

I don't have a machine with Ventura on it, but we use http://github.com/atom/node-keytar for this interaction so we should get an issue going there.

**Comment by phyllisstein** [comment] 2022-06-24 21:50
I was seeing the same thing on Ventura. Troubleshooting attempts that didn't work:

* Deleting VSCode's GitHub auth in Keychain Access, then signing in again.
* Disconnecting VSCode from my authorized apps on GitHub, then signing in again.
* Clearing VSCode's caches in `~/Library/Application Support/Code`, then signing in again.

**Comment by TylerLeonhardt** [comment] 2022-06-25 01:47
if you have nodejs installed, you can run this simple one-liner to see if the problem is how your keychain is setup:

```
npx @emacs-grammarly/keytar-cli find-creds -s vscode-insidersvscode.github-authentication
```
This is using the following open source package: https://github.com/emacs-grammarly/keytar-cli

What you should get is something like this:
```js
[
  {
    account: 'github.auth',
    password: '....... longggg string ......'
  }
]
```
> NOTE: on macOS I got a system prompt to allow this process to access the keychain... that may or may not be the case for you

If that succeeds, then the problem is possibly in vscode.

If that _does_ complain, then we'll need a fix in keytar itself.

**Comment by rotu** [comment] 2022-06-25 03:44
@TylerLeonhardt I can both get and set values with keytar-cli and they do show up in the Keychain Access utility.

**Comment by rotu** [comment] 2022-06-25 04:04
In addition to the error message initially reported in the "GitHub Authentication" output, I'm seeing this in "Log (main)":

> [2022-06-24 23:03:25.187] [main] [warning] Error attempting to set a password:  Password is required.
> [2022-06-24 23:03:25.388] [main] [warning] Error attempting to set a password:  Password is required.
> [2022-06-24 23:03:25.592] [main] [warning] Error attempting to set a password:  Password is required.

**Comment by Fudoshiki** [comment] 2022-06-25 05:28
@TylerLeonhardt

![Screenshot 2022-06-25 в 10 28 06](https://user-images.githubusercontent.com/4083992/175759706-1045a151-da0f-4995-9e62-ca1df0bd909d.png)

**Comment by alexanderniebuhr** [comment] 2022-06-25 10:31
> If that succeeds, then the problem is possibly in vscode.

> @TylerLeonhardt I can both get and set values with keytar-cli and they do show up in the Keychain Access utility.

Being the same behaviour as @rotu. Using suggested package `keytar-cli`, gives the following outputs
```
alexanderniebuhr@Alexanders-MBP ~ % npx @emacs-grammarly/keytar-cli find-creds -s vscode-insidersvscode.github-authentication     
[ { account: 'github.auth', password: 'ASD' } ]
alexanderniebuhr@Alexanders-MBP ~ % npx @emacs-grammarly/keytar-cli set-pass -s vscode-insidersvscode.github-authentication -a github.auth -p TEST
Successfully set the password for github.auth@vscode-insidersvscode.github-authentication!
alexanderniebuhr@Alexanders-MBP ~ % npx @emacs-grammarly/keytar-cli find-creds -s vscode-insidersvscode.github-authentication
[ { account: 'github.auth', password: 'TEST' } ]
```

Even using the package `atom/node-keytar` in a demo project works. Therefore I really think there is some issue in VSCode. Can we get some higher priority on this?

**Comment by rotu** [comment] 2022-06-25 21:59
@TylerLeonhardt I can't even figure out how to debug this. Building and running VSCode from source does not load the `vscode.github-authentication` extension. How do I a debugger on this in OSS VSCode?

**Comment by TylerLeonhardt** [comment] 2022-06-25 22:28
@rotu it's because there's nothing in OSS that uses auth.

You can debug it by either side-loading a GH extension (download VSIX on [the marketplace](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) and then in OSS go to the extension pane and hit the three dots to Install from VSIX)

Or just add a [SecretStorage](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) usage in any of the built in extensions. Secrets is in the [ExtensionContext](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext)

**Comment by rotu** [comment] 2022-06-26 04:28
So far no dice. It seems the OSS version works just fine with persisting authentication. Unlike the distributed VSCode (both stable and insiders), OSS is able to write to the system keychain.

**Comment by alexanderniebuhr** [comment] 2022-06-26 10:44
@rotu so using a version you built from source of this repo does work, while the distributed version (which I thought is also built from the repo) does not work?

**Comment by rotu** [comment] 2022-06-26 12:40
@alexanderniebuhr that is correct.

**Comment by alexanderniebuhr** [comment] 2022-06-26 13:19
Knowing this, I wonder if this could be a problem with App Signing. Since the distributed one is probably signed differently.

@TylerLeonhardt, what do you think? Any update from VSCode Team?

**Comment by alexanderniebuhr** [comment] 2022-06-26 17:41
Not sure if that works, but some output if running VSCode with `--verbose` flag

```
[main 2022-06-26T17:35:44.762Z] menubarService#updateMenubar 1
[2567:0626/193545.621575:INFO:CONSOLE(602)] "%cTRACE color: #888 onWillActivateByEvent:  onAuthenticationRequest:github", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[2567:0626/193545.623188:INFO:CONSOLE(602)] "%cTRACE color: #888 DialogService#show The extension 'GitHub Copilot Nightly' wants to sign in using GitHub.", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[main 2022-06-26T17:35:49.776Z] app#handleURL:  REPLACED_FOR_PRIVACY {
  originalUrl: 'REPLACED_FOR_PRIVACY'
}
[main 2022-06-26T17:35:49.777Z] app#handleURL: windowOpenableFromProtocolLink =  undefined
[main 2022-06-26T17:35:49.822Z] ExtensionUrlTrustService#isExtensionUrlTrusted There are no configured trusted keys
[2567:0626/193549.827670:INFO:CONSOLE(602)] "%cTRACE color: #888 CommandService#executeCommand workbench.getCodeExchangeProxyEndpoints", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[main 2022-06-26T17:35:50.033Z] menubarService#updateMenubar 1
[main 2022-06-26T17:35:50.641Z] Error attempting to set a password:  Password is required.
[main 2022-06-26T17:35:50.809Z] update#checkForUpdates, state =  idle
[main 2022-06-26T17:35:50.810Z] update#setState checking for updates
[main 2022-06-26T17:35:50.847Z] Error attempting to set a password:  Password is required.
[main 2022-06-26T17:35:51.052Z] Error attempting to set a password:  Password is required.
[main 2022-06-26T17:35:51.094Z] update#setState idle
[2567:0626/193551.266835:INFO:CONSOLE(602)] "%cTRACE color: #888 Settings Sync: Getting accounts for microsoft", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[2567:0626/193551.276541:INFO:CONSOLE(602)] "%cTRACE color: #888 onWillActivateByEvent:  onAuthenticationRequest:github", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[2567:0626/193551.280980:INFO:CONSOLE(602)] "%cTRACE color: #888 Settings Sync: Updated accounts for microsoft", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[2567:0626/193551.281380:INFO:CONSOLE(602)] "%cTRACE color: #888 Settings Sync: Getting accounts for github", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[2567:0626/193551.283427:INFO:CONSOLE(602)] "%cTRACE color: #888 Settings Sync: Updated accounts for github", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[2567:0626/193551.284187:INFO:CONSOLE(602)] "%cTRACE color: #888 onWillActivateByEvent:  onAuthenticationRequest:github", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[2567:0626/193551.600546:INFO:CONSOLE(602)] "%cTRACE color: #888 CommandService#executeCommand setContext", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[2567:0626/193552.018763:INFO:CONSOLE(31)] "%cTRACE color: #888 [code cache cleanup]: Starting to clean up old code cache folders.", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (31)
[2567:0626/193552.020051:INFO:CONSOLE(31)] "%cTRACE color: #888 [storage cleanup]: Starting to clean up storage folders.", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (31)
[2567:0626/193552.020889:INFO:CONSOLE(31)] "%cTRACE color: #888 [storage cleanup]: Deleting workspace storage folder 1655991696632.", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (31)
[2567:0626/193552.020932:INFO:CONSOLE(31)] "%cTRACE color: #888 [storage cleanup]: Deleting workspace storage folder 1656264779296.", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (31)
[2567:0626/193552.021956:INFO:CONSOLE(31)] "%c  ERR color: #f33 [uncaught exception in sharedProcess]: A system error occurred (EACCES: permission denied, unlink '/Users/alexanderniebuhr/Library/Application Support/Code - Insiders/User/workspaceStorage/1655991696632/state.vscdb.backup'): Error: EACCES: permission denied, unlink '/Users/alexanderniebuhr/Library/Application Support/Code - Insiders/User/workspaceStorage/1655991696632/state.vscdb.backup'", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (31)
```

**Comment by alexanderniebuhr** [comment] 2022-06-26 18:09
Okay, I found an interesting workaround. Using the x64 Intel published version of VSCode stable, does save and load successfully from the keychain.

@rotu @phyllisstein @und3fined could you verify that for your case too?

If that is true, it seams that there is something broken with the Apple Silicon version :/

**Comment by rotu** [comment] 2022-06-27 00:39
Also, if you're in need of a workaround, the [Settings Sync Extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) appears to still work

**Comment by rotu** [comment] 2022-06-27 03:25
Alright @TylerLeonhardt I made some progress but I think I'm at the end of my debugging abilities, and the problem lies in the native `vscode-encrypt` service. I think the issue is here, where `await this.encryptionService.encrypt` is getting a valid JSON object but returning `""`:

https://github.com/microsoft/vscode/blob/c22cb87311b5eb1a3bf5600d18733f7485355dc0/src/vs/workbench/api/browser/mainThreadSecretState.ts#L83-L84

It seems like the EncryptionService

**Comment by und3fined** [comment] 2022-06-27 03:27
@alexanderniebuhr thank for workaround. It's auth worked, but VS Code sloooowwww with Intel version.
 I'll use VS Code (arm) until it fixed or Zed/Fleet released. Maybe i'll never comeback VSCode, if Zed/Fleet release

**Comment by rotu** [comment] 2022-06-27 03:48
@alexanderniebuhr @und3fined, I found an even better workaround!
Simply remove the encryption module:
```
rm -rf /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-encrypt
```

**Comment by und3fined** [comment] 2022-06-27 04:05
@rotu Wow. it's magic =))

Note: Allow update/deteled app on `Privacy & Security` > `App Management`
With backslash command:
```
rm -rf /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-encrypt
```

**Comment by alexanderniebuhr** [comment] 2022-06-27 05:47
@rotu your workaround does not work for me.

**Comment by rotu** [comment] 2022-06-27 09:43
> @rotu your workaround does not work for me.

@alexanderniebuhr, are you still using the insiders build? If so, remove vscode-encryption from that app package instead

**Comment by alexanderniebuhr** [comment] 2022-06-27 10:56
> remove vscode-encryption from that app package instead

well it allows to safe the token, but it still loses it on reload. But thanks for your help debugging this. Hope we get a fix soon.

**Comment by rotu** [comment] 2022-06-27 11:30
> This workaround worked for me as well, but I wonder what are the consequences of this change to the app.

Not much, I think. Keychain is a secure storage mechanism so the additional encryption seems redundant.

**Comment by und3fined** [comment] 2022-06-27 12:00
> > This workaround worked for me as well, but I wonder what are the consequences of this change to the app.
> 
> Not much, I think. Keychain is a secure storage mechanism so the additional encryption seems redundant.

I think, it's a layer of defense against other extensions

**Comment by TylerLeonhardt** [comment] 2022-06-27 21:06
Thanks for all the info so far! It's been very helpful. We will be investigating this issue next week since we've already started our VS Code release process.

**Comment by brianpham93** [comment] 2022-06-29 15:33
> @alexanderniebuhr @und3fined, I found an even better workaround! Simply remove the encryption module:
> 
> ```
> rm -rf "/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-encrypt"
> ```

yesss it works for me as well

**Comment by bketelsen** [comment] 2022-06-30 00:42
workaround worked for me. I was close to throwing the whole computer out the window :)

**Comment by TylerLeonhardt** [comment] 2022-06-30 00:47
ahh the price of early adoption :)

Just keep in mind that you will need to remove this every time VS Code updates...(daily on insiders, weekly-ish on stable) and once we figure out why `vscode-encrypt` isn't working on this platform and it starts to work again, you'll need to relog in to everything because we are expecting what's stored in the keyring to be decryptable by `vscode-encrypt`.

**Comment by rotu** [comment] 2022-06-30 02:48
> Just keep in mind that you will need to remove this every time VS Code updates…

This is true. Hopefully this issue is resolved at the root soon. Unfortunately VS Code is not open source or else this would be fixable by the community.

> you'll need to relog in to everything

I don’t think so. it looks like the logic can handle unencrypted credentials.

**Comment by alexanderniebuhr** [comment] 2022-06-30 06:10
> price of early adoption

I generously wonder why the encryption breaks on Ventura. If it used x64-specific stuff, it would have been damaged before on Apple Silicon, and I can't recall that I had read something about the deprecation of encryption-related things in the release notes by Apple. I might miss some, hidden changes.

@TylerLeonhardt to get this back in this thread. The Workaround only works in Stable for me; Insider stays broken even after applying. That could be due to a corrupted installation while debugging, but it could also hint that there are some other caveats to check for macOS Ventura.

**Comment by alexanderniebuhr** [comment] 2022-07-06 17:27
@TylerLeonhardt can we see the fix on the latest Insiders? Or is there any particular reason you closed this?

**Comment by alexanderniebuhr** [comment] 2022-07-06 18:20
Great. I will verify the solution and let you know!

**Comment by alexanderniebuhr** [comment] 2022-07-11 11:56
@TylerLeonhardt actually can't verify on the latest insider. [(others report this too)](https://github.com/microsoft/vscode/issues/154420#issuecomment-1179719817)

**I actually wonder why you have closed an issue, which is not verified fixed.** I suggest reopening this issue and waiting for verification of users before closing it again.

**Comment by deepak1556** [comment] 2022-07-11 12:10
@alexanderniebuhr thanks for verifying, we are aware of the issue as well. Currently tracked in https://github.com/microsoft/vscode/pull/154762 

The issue was closed as part of fix in the module and another side effect is for our release bot to track fixes shipped in a certain insider version so that certain github actions can work https://github.com/microsoft/vscode-github-triage-actions. Issue will be closed to signal for verification and if issue persists then it will be reopened for further investigation.

**Comment by rotu** [comment] 2022-07-11 16:08
@alexanderniebuhr not even sure why this issue is tracked on GitHub, since neither the buggy code nor the fix is part of the open-source codebase.

**Closed** 2022-07-12 10:00 UTC
Labels: bug, confirmed, authentication, :apple: si

**Comment by Dids** [comment] 2022-07-12 13:15
Shouldn't this issue be closed when it's confirmed fixed?

The merged fix seems to only apply to the arm64 build of VSCode, however this issue also happens on the universal insider builds, which either means that universal builds need a similar fix, _or_ the issue is still there.

**Comment by DestroyerXyz** [comment] 2022-07-16 17:50
Any ETA on this coming to stable? @deepak1556

**Comment by und3fined** [comment] 2022-07-19 07:57
Problem fixed with Sync with Github account.
But Copilot not work. It's required re-auth.

**Comment by Dids** [comment] 2022-07-20 18:56
> Problem fixed with Sync with Github account. But Copilot not work. It's require re-auth.

Are you still seeing this? Because I thought the same at first too, but now it seems intermittent, as it at least stays logged in for longer periods of time now, regardless of how many times VSCode is (re)opened.

**Comment by rstolpe** [comment] 2022-07-22 06:47
@gjsjohnmurray Is this solved in the latest insider build?
