### ISSUE TITLE
SCM diffs no longer open in preview mode

### ISSUE THREAD

**Issue by EthanRutherford** [Microsoft/vscode#26471] opened 2017-05-11 15:58 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|contextualduplicate|lafe|0.2.0|
|csharp|ms-vscode|1.9.0|
|seti-icons|qinjia|0.1.3|;

---

Steps to Reproduce:

1. Make changes to a source controlled file (i.e. git)
2. Open diff viewer from source control tab

In previous versions of vscode, following the steps above would open the diff view in "preview mode", and the tab would only be "kept" (i.e. in the event that you open another preview tab) if you double click or edit. It seems that a change was made recently that makes diffs always open as kept tabs rather than previews, which makes reviewing changed files before staging bloat the editor with diff tabs that must be manually closed.
If this change was intended, I'd appreciate at least having a setting that I can use to prefer opening diffs in preview mode again.

**Comment by eamodio** [comment] 2017-05-12 03:37
This is a duplicate of https://github.com/Microsoft/vscode/issues/26184

**Closed** 2017-05-12 07:56 UTC
