### ISSUE TITLE
Auto Format setting(s)

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#2591] opened 2016-01-31 21:36 UTC
Could you please add a setting for where the brace gets placed when autoformat runs.

When the auto format runs it moves the brace to a new line. This is very annoying to me.

**Comment by aeschli** [comment] 2016-02-01 10:21
@TheColorRed For which language?

**Comment by TheColorRed** [comment] 2016-02-01 14:49
It is doing it for C#, but it would be nice if it could be changed for any language that supports formatting.

**Comment by TheColorRed** [comment] 2016-02-01 14:55
Also, it auto formats everything in the block as well, and then I have to go back and manually format all the blocks back to how I like it.

**Comment by jrieken** [comment] 2016-02-01 16:30
duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/26

**Closed by jrieken** 2016-02-01 16:30 UTC
