### ISSUE TITLE
JavaScript IntelliSense doesn't working after starting up VSCode for a few seconds

### ISSUE THREAD

**Issue by ccloli** [microsoft/vscode#64192] opened 2018-12-03 08:37 UTC
Issue Type: <b>Bug</b>

When startup VSCode with specific workspace, IntelliSense will start loading, and when it finishes, autocomplete will start working and showing suggestions. But after a few seconds, it stops giving suggestions on all JavaScript files, but still working on some other types (like CSS) and working on other workspaces.

Disabling all the extensions doesn't work, and no errors showing on VSCode output tab or Chromium Devtool.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

Screenshot:
- Steps GIF:
![vscode](https://user-images.githubusercontent.com/8115912/49361891-19449180-f718-11e8-804c-1b00eb0b0963.gif)
- Not working on JavaScript:
![image](https://user-images.githubusercontent.com/8115912/49362128-e222b000-f718-11e8-8b0d-1592de0d540a.png)
- But at the same time it works on CSS:
![image](https://user-images.githubusercontent.com/8115912/49362175-08e0e680-f719-11e8-912e-2ec1bf086e55.png)
- And works on other workspaces:
![image](https://user-images.githubusercontent.com/8115912/49362401-a63c1a80-f719-11e8-9c36-adfccc67b192.png)

VSCode Output tab:

- Tasks: no output
- Extensions: no output
- TypeScript: 
   ```
    [Info  - 4:24:16 PM] Using tsserver from: c:\Program Files\Microsoft VS 
    Code\resources\app\extensions\node_modules\typescript\lib
    [Info  - 4:24:16 PM] Forking TSServer
    [Info  - 4:24:16 PM] Started TSServer
    ```
- Log (Extension Host):
    ```
    [2018-12-03 16:24:15.276] [exthost] [info] extension host started
    [2018-12-03 16:24:15.303] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
    [2018-12-03 16:24:15.303] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\debug-auto-launch\dist\extension
    [2018-12-03 16:24:15.310] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
    [2018-12-03 16:24:15.310] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\dist\extension
    [2018-12-03 16:24:15.326] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
    [2018-12-03 16:24:15.326] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main
    [2018-12-03 16:24:15.505] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
    [2018-12-03 16:24:15.505] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\dist\extension
    [2018-12-03 16:24:15.515] [exthost] [info] eager extensions activated
    [2018-12-03 16:24:15.517] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onLanguage:javascript"}
    [2018-12-03 16:24:15.517] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension
    [2018-12-03 16:24:35.526] [exthost] [info] ExtensionService#_doActivateExtension vscode.css-language-features {"startup":false,"activationEvent":"onLanguage:css"}
    [2018-12-03 16:24:35.526] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\client\dist\cssMain
    ```
- Log (Main):
    ```
    [2018-12-03 16:24:13.386] [main] [info] update#setState idle
    [2018-12-03 16:24:43.386] [main] [info] update#setState checking for updates
    [2018-12-03 16:24:43.969] [main] [info] update#setState idle
    ```
- Log (Shared):
    ```
    [2018-12-03 16:24:17.301] [sharedprocess] [info] main {"machineId":"3091ac8bc15d871863b7eead8b6fce247dcb66a87f9d29f2a09f7f16dc0202d0"}
    [2018-12-03 16:24:18.835] [sharedprocess] [info] Scanned user extensions: 11
    [2018-12-03 16:24:18.857] [sharedprocess] [info] Scanned user extensions: 11
    [2018-12-03 16:24:18.885] [sharedprocess] [info] Scanned user extensions: 11
    [2018-12-03 16:24:19.082] [sharedprocess] [info] Scanned system extensions: 71
    [2018-12-03 16:24:19.101] [sharedprocess] [info] Scanned system extensions: 71
    [2018-12-03 16:24:57.312] [sharedprocess] [info] Starting to clean up unused language packs.
    [2018-12-03 16:29:18.904] [sharedprocess] [info] Scanned user extensions: 11
    ```
- Log (Window):
    ```
    [2018-12-03 16:24:15.414] [renderer1] [info] no standard startup: panel is active
    ```

**Comment by ccloli** [comment] 2018-12-03 08:45
VSCode settings.json:
```js
{
    "workbench.statusBar.feedback.visible": false,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": [
        "--login",
        "-i"
    ],
    "terminal.external.windowsExec": "C:\\Program Files\\Git\\bin\\bash.exe --login -i",
    "terminal.integrated.cursorBlinking": true,
    // "terminal.integrated.experimentalRestore": true,
    "terminal.integrated.setLocaleVariables": true,
    "git.autofetch": true,
    "editor.smoothScrolling": true,
    "files.autoSave": "onFocusChange",
    "search.location": "sidebar",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.detectIndentation": true,
    "git.confirmSync": false,
    "workbench.colorCustomizations": {
        "statusBar.background": "#007acc"
    },
    "workbench.colorTheme": "Monokai",
    // "editor.quickSuggestions": {
    //     "other": true,
    //     "comments": false,
    //     "strings": true
    // },
    "cssModules.camelCase": true
}
```

**Comment by aprather51** [comment] 2018-12-03 17:12
+1 with @ccloli I am having exact same issues here.

**Comment by mjbvz** [comment] 2018-12-03 21:33
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ccloli** [comment] 2018-12-04 03:03
@mjbvz I've done a clean VSCode installation (1.29.1) and can still reproduce the bug. Then I tried VSCode insiders (1.30.0-insider, 9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096), looks like the bug is disappeared in both zip and a clean installation, and installing all the extensions and setting the same `settings.json` works fine. So maybe the bug is fixed in insiders.

![image](https://user-images.githubusercontent.com/8115912/49416176-14cdb680-f7b4-11e8-9378-83dcec6a4b01.png)

**Comment by sanmaopep** [comment] 2019-01-05 05:50
ctrl+shift+p "Restart TS server" will help me when JavaScript Intellisense doesn't work. 
Maybe because "TS server" is too busy and restarting it will work it out again?

**Comment by mjbvz** [comment] 2019-05-24 23:45
Closing this as it sounds like it was fixed a few iterations back based on the comment

**Closed by mjbvz** 2019-05-24 23:45 UTC
Labels: extensions, needs more info
