### ISSUE TITLE
Terminal > Integrated > Default Location broken

### ISSUE THREAD

**Issue by mccarvell** [microsoft/vscode#138761] opened 2021-12-09 14:18 UTC
Issue Type: <b>Bug</b>

When you change the setting:
Terminal > Integrated > Default Location to "editor" it opens the terminal in a normal tab. After the last update, when you drag this terminal tab re-arrange or split the view, the terminal is blank.

MacOS

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:18.361Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id 6fda4f89-b0cf-4784-9654-352364f1b182|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.7.3
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
todo-tree|Gru|0.0.214
vetur|oct|0.35.0
svelte-vscode|sve|105.6.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3c:30407761

```

</details>

**Comment by meganrogge** [comment] 2021-12-10 17:57
duplicate of #138770

**Closed by meganrogge** 2021-12-10 17:57 UTC
Labels: bug, *duplicate, confirmed, new release
