### ISSUE TITLE
Bug Report: Full Word Match Functionality in Global Search Malfunctions When Searching Chinese in VS Code

### ISSUE THREAD

**Issue by Hardtodefine** [microsoft/vscode#226237] opened 2024-08-22 09:27 UTC
Type: <b>Bug</b>

Issue Summary:
When using the global search in VS Code to search for Chinese characters, the "Match Whole Word" option fails to work as expected. Even with this option enabled, search results include partial matches. Upon navigating to one of the incorrectly matched files, the results list removes that file and refreshes, indicating that it should not have appeared in the first place.

Steps to Reproduce:

Perform a global search in VS Code for Chinese characters.
Enable the "Match Whole Word" option.
Notice that non-whole word matches still appear in the search results.
Click on a file in the search results list that contains a partial match.
Observe that after opening the file, the results list removes it and refreshes.
Close the file and turn off the "Match Whole Word" option.
Open the first file that contains the non-whole word match from the results.
Close the file and turn on the "Match Whole Word" option again.
Expected Behavior:
With the "Match Whole Word" option enabled, only exact whole word matches should be returned in the search results, and the results should not include partial matches at any point.

Actual Behavior:
Non-whole word matches are included in the search results, which causes an inconsistent experience when navigating between search results and files. Opening a file that contains a non-whole word match causes the results list to update and remove the incorrect match.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz (8 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (1.07GB free)|
|Process Argv|--crash-reporter-id 1dea0a33-cac2-48d0-87b9-8f8f20ebfca2|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|15.3.1
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.92.2024081409
synthwave-vscode|Rob|0.1.15
vscode-mdx|uni|1.8.10
volar|Vue|2.0.8

</details>

**Comment by Hardtodefine** [comment] 2024-08-22 09:33
First turn off the whole word match switch to search for Chinese, open the first file (the file must contain search results that do not match the whole word match), then close this file, and then turn on the whole word match switch
...gpt totally screwed up my translation fake love from gpt

**Comment by andreamah** [comment] 2024-09-03 18:45
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/27280
/duplicate https://github.com/microsoft/vscode/issues/27280

**Closed** 2024-09-03 18:46 UTC
Labels: *duplicate
