### ISSUE TITLE
settings.json should auto-complete currently used color in color customizations instead of red

### ISSUE THREAD

**Issue by geekley** [microsoft/vscode#119020] opened 2021-03-15 21:43 UTC
In `settings.json`, when selecting a field for `workbench.colorCustomizations` or `editor.tokenColorCustomizations` that has a color value, then auto-completion inserts the red color value automatically `#ff0000` so you can replace it with the color you want.
Please make it so it completes with the currently used color for that field, instead of red.

**Why?**
1. It's quite difficult to find the currently used color. For example, I wanted to change `gitDecoration.modifiedResourceForeground`, but I had to look at the source code, and in this case it wasn't obvious that it's actually getting the value from the git extension source, not from the color theme I'm using.
2. Sometimes you want to make a small adjustment, or an adjustment that would be consistent with the color palette (e.g. change hue while keeping same level of brightness and saturation). For that, you need to know the current value of the color, and it shouldn't be so difficult to find it.
3. I believe having this practical way of finding out the current value of a color setting would be a great help to color theme developers as well.

**Comment by aeschli** [comment] 2021-03-15 22:39
I wouldn't change the `red` code completion, but it would be good to have a hover that shows the current value.

**Comment by usernamehw** [comment] 2021-03-16 07:38
Possible duplicate of #25633

I use `Developer: Generate Color Theme From Current Settings` when searching for color value.

**Comment by aeschli** [comment] 2021-03-16 08:46
Thanks @usernamehw !

Marking as duplicate of  #25633

**Closed by aeschli** 2021-03-16 08:46 UTC
