### ISSUE TITLE
Render Markdown of JSDoc 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#17414] opened 2016-12-16 19:33 UTC
_From @waderyan on November 11, 2016 22:34_

_From @mohsen1 on November 7, 2016 18:37_

- VSCode Version: 1.7.1
- OS Version: macOS

I'm expecting 

```ts
/**
 * This is foo
 * Foo is great! Use it like this:
 * 
 * ```ts
 * const foo = new Foo(); 
 * ```
 */
function Foo() {

}


var f = new Fo
```

I was expecting my Markdown to be rendered here: 

![screen shot 2016-11-07 at 10 35 41 am](https://cloud.githubusercontent.com/assets/543633/20070625/f73a3fb8-a4d5-11e6-93f2-393b0d057e2f.png)

_Copied from original issue: Microsoft/vscode#15117_

_Copied from original issue: Microsoft/TypeScript#12185_

**Comment by waderyan** [comment] 2016-12-16 19:33
_From @Emeryao on November 10, 2016 6:32_

the code above works fine and the jsdoc displayed as markdown in a .ts file on insiders build :

```
Version 1.8.0-insider
Commit ce6d57875ab53309204cf12dc54d74956221cfc1
Date 2016-11-09T08:48:03.700Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
OS Windows 10 14393.447
```

**Comment by waderyan** [comment] 2016-12-16 19:33
I am seeing the issue. 

![image](https://cloud.githubusercontent.com/assets/2449568/20232257/cf4ed33a-a81b-11e6-9b69-2572bc5b38c2.png)

This is a good feature request.

**Comment by waderyan** [comment] 2016-12-16 19:33
_From @DanielRosenwasser on November 11, 2016 23:23_

Given that VS Code already does custom styling for quick info, and renders other markdown within it, I don't think that this should be an issue on TS.

![image](https://cloud.githubusercontent.com/assets/972891/20233235/b9f94bb2-a822-11e6-85a6-b480c998ff3f.png)

**Comment by waderyan** [comment] 2016-12-16 19:33
@dbaeumer is this something that should be done on the VS Code side? I will move the issue back if so.

**Comment by waderyan** [comment] 2016-12-16 19:33
_From @mhegazy on November 14, 2016 21:49_

We do return the text of the comment. @dbaeumer if you can spot the problem with the output we can trace it from there and fix it.

**Comment by waderyan** [comment] 2016-12-16 19:33
_From @dbaeumer on November 15, 2016 1:35_

There are two different issue here:
- the one rendering it as markdown in the editor. This is a grammar problem which is owned by TS. 
- the one in the hover / code complete is a Code issue. To fix we need to create a marked String by parsing the strings we get from the TS server.

**Comment by waderyan** [comment] 2016-12-16 19:33
_From @mhegazy on December 15, 2016 20:39_

For the first issue, TM grammar issues are tracked under https://github.com/Microsoft/TypeScript-tmlanguage, for the second, it should be tracked by a VSCode issue.

**Comment by waderyan** [comment] 2016-12-16 19:33
_From @mhegazy on December 15, 2016 20:39_

closing for now. @waderyan we need to port this back to VSCode.

**Comment by waderyan** [comment] 2016-12-16 19:33
Will do. Thanks!

**Comment by mjbvz** [comment] 2016-12-16 22:31
Closing as a duplicate of #1920

**Closed by mjbvz** 2016-12-16 22:31 UTC
Labels: duplicate, intellisense, javascript
