### ISSUE TITLE
Javascript line continuation characters not syntax highlighted

### ISSUE THREAD

**Issue by jlynch630** [Microsoft/vscode#1464] opened 2015-12-19 01:26 UTC
When writing a JS string like, `"foo\`
                                                `bar"`
VS Code will only highlight the first line.
This only seems to happen in the latest version, 0.10.5
![image](https://cloud.githubusercontent.com/assets/1965320/11910479/61aa63e8-a5ac-11e5-9d36-887197a70c00.png)

**Comment by Johnaka** [comment] 2016-01-11 17:39
![screenshot 25 2](https://cloud.githubusercontent.com/assets/11838212/12241282/24f3ea80-b8b4-11e5-8e6f-4ad948a1015a.png)

**Comment by aeschli** [comment] 2016-01-12 09:39
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/40
(JavaScript and TypeScript use the same tokenizer)

**Closed by aeschli** 2016-01-12 09:39 UTC
Labels: bug
