### ISSUE TITLE
TypeScript multiple errors display problem

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#15428] opened 2016-11-13 17:30 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (fb8939b09460ff9fbd40d39056b54c88d5aad9c8, 2016-11-11T13:12:38.741Z)
- OS Version: Darwin x64 16.1.0

---

If the project has multiple errors, for example:
![image](https://cloud.githubusercontent.com/assets/1723815/20247494/9f64822e-a99b-11e6-9afd-f255aa1e537a.png)

and you scroll down a little bit and start working on fixing one by one, then often times the following happens which is pretty disruptive:

1. You click the error to go to it
2. You fix the error
3. You want to click next error in the error list
4. (this step is an issue) - errors will dissapear for some time (will change to 0 ERRORS or some smaller number) and then it will come back to (ORGINIAL_NUMBER_OF_ERRORS-1)
5. Scroll will jump

Seems like maybe vscode could wait a little bit till entire compilation finish and all the errors come back (from tsc or tsserver)

Here are 3 screenshots:
![image](https://cloud.githubusercontent.com/assets/1723815/20247536/b4e76070-a99c-11e6-9b20-cb11d152091a.png)

![image](https://cloud.githubusercontent.com/assets/1723815/20247539/bc780056-a99c-11e6-9113-fc43767ee30d.png)

![image](https://cloud.githubusercontent.com/assets/1723815/20247560/18e30480-a99d-11e6-9f06-b0b22c01df29.png)

**Comment by dbaeumer** [comment] 2016-11-15 01:21
@sandy081 assigning to you. The TS extension reports errors for a file in a batch. So there is not reason that the count and the list jumps. It could be @jrieken as well if the marker service is not smart in that regard.

**Comment by sandy081** [comment] 2016-12-07 20:52
Will do initial investigation to know the root cause

**Comment by pocesar** [comment] 2017-02-13 07:54
having this problem on insiders, also the errors "stick" even after the file has been changed, and it's pointing to a wrong location, the error was originally in line 38 

![vscode](https://cloud.githubusercontent.com/assets/461084/22875063/5606a1e8-f1a8-11e6-8e75-92481943e729.jpg)

**Comment by sandy081** [comment] 2017-02-27 14:52
Problems view listens to Markers service changes and displays Diagnostics provided by Marker service.

@jrieken Any idea what's happening here in Marker service or is it coming down from the Extension ?

**Comment by jrieken** [comment] 2017-02-27 15:08
@pocesar @normalser Do you guys have a task like `tsc` configured that computes these diagnostics?

**Comment by pocesar** [comment] 2017-02-27 16:14
@jrieken yes, I have a watching Typescript build task. but it doesn't matter if I stop it, the errors remains indefinitely until I reload the window

**Comment by jrieken** [comment] 2017-02-27 16:43
@dbaeumer does that ring a bell?

**Comment by pocesar** [comment] 2017-02-27 22:46
![image](https://cloud.githubusercontent.com/assets/461084/23383457/3c7d4a3c-fd25-11e6-8772-4475b54608a1.png)
![image](https://cloud.githubusercontent.com/assets/461084/23383470/4c0f2326-fd25-11e6-890d-780f9e360a7f.png)

although my settings have noEmitOnError, the problems tab doesn't seem to understand that it already compiled successifully

**Comment by dbaeumer** [comment] 2017-02-28 09:18
@jrieken no bell.

@pocesar could you do the following. Start VS Code close all editors. Restart VS Code and then start the build command (Ctrl+Shift+B). Will you see double errors ? Then open the file that results in double errors. Will they appear.

**Comment by pocesar** [comment] 2017-02-28 17:57
@dbaeumer yes, the errors disappears for like 2-3 seconds, then return

**Comment by pocesar** [comment] 2017-03-01 01:11
![image](https://cloud.githubusercontent.com/assets/461084/23441727/d00d4f30-fe02-11e6-89b7-8b566ce9f624.png)
![image](https://cloud.githubusercontent.com/assets/461084/23441737/de12cd6c-fe02-11e6-8b40-21e2c495c57b.png)

now the errors are stuck so hard that the editor won't even recognize the new errors

**Comment by dbaeumer** [comment] 2017-03-01 14:28
@pocesar just to be sure. The errors don't show up after build (Ctrl+Shift+B). They do show up after opening the file.

**Comment by pocesar** [comment] 2017-03-01 17:20
yes, unless the file was saved with the error, otherwise, it doesn't show up

**Comment by dbaeumer** [comment] 2017-03-02 11:24
OK. Then this is either a TS extension or the problem view. @mjbvz can you please follow up with @pocesar to see if this is a TS server problem.

**Comment by mjbvz** [comment] 2017-04-04 22:57
@pocesar Can you please try upgrading the VSCode 1.10 and collecting the tsserver trace. Here's how to do this:

* Set  `"typescript.tsserver.trace": "verbose"`
* Relaod vscode and reproduce the problem
* Go to the output panel and share the output from the `typescript` section

Thanks

**Comment by mjbvz** [comment] 2017-04-12 01:03
Closing as we need more info to investigate this.

@pocesar, if you are still seeing this in VSCode 1.11, please provide the TypeScript server trace so that we can try to track down what the root cause of this issue may be

**Closed by mjbvz** 2017-04-12 01:03 UTC
Labels: bug, error-list, needs more info, typescript

**Comment by pocesar** [comment] 2017-04-12 16:22
@mjbvz the problem is I don't know how to reproduce it everytime, it seems random, but the problem is still  happening in 0.12 insiders
