### ISSUE TITLE
Difficult regex search makes VSC unresponsive

### ISSUE THREAD

**Issue by Flamefire** [microsoft/vscode#98076] opened 2020-05-18 10:12 UTC
- VSCode Version: 1.45.1
- OS Version: Linux Mint 19

Steps to Reproduce:

1. Search for `(\w+)* \w+ = new \1` in all files of a project

Note the accidentally typed star.
VSC CPU usage goes up to 100% periodically showing "The window is no longer responding".
While reopening the window would (likely) be possible this will loose all unsaved progress.

IMO a running search should not crash the whole window but either auto-abort the search after some time or ask the user to abort the search when it seemingly hangs instead of reopening the whole window.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-05-18 11:25
Are you using Find in Files and not search widget inside of editor?

Do you have any open editors (especially Untitled or files not from workspace)? It looks like duplicate of #30874 because in case of open tabs it might use JS match instead of ripgrep.

Does it happen if you close all editors and perform same search in Find in Files?

**Comment by Flamefire** [comment] 2020-05-18 11:40
>Are you using Find in Files and not search widget inside of editor?

Find in files (CTRL+SHIFT+F)

> Do you have any open editors (especially Untitled or files not from workspace)

Yes, as mentioned some of them are even unsaved which makes this bug horrible. Nothing from outside the workspace or new ones

I can confirm this happens as soon as any editor is open, even with ones from the workspace and no changes.

BTW: Any advice on how to cancel the hanging process without loosing my unsaved files?

**Comment by IllusionMH** [comment] 2020-05-18 11:55
I don't think that JS provides any option to add timeout for RegExp and only option will be to move search in editors off the main thread (which, I assume, will have performance hit for all searches in editors because of data transfer between threads)

See https://github.com/microsoft/vscode/issues/61076#issuecomment-545197180

/cc @rebornix

**Comment by Artemis21** [comment] 2020-05-19 09:59
I've had this problem with the search-in-file also. Any regex like `(foo|)` freezes it, which is annoying as I often type that while changing a longer regex, eg `(foo|bar)` --> `(foo|bar|bat)`.

**Comment by roblourens** [comment] 2020-05-20 13:13
Dupe of https://github.com/microsoft/vscode/issues/30874, and @IllusionMH's comment is correct. Would like to someday investigate using a different regex engine for search via wasm.

**Closed by roblourens** 2020-05-20 13:13 UTC

**Comment by Flamefire** [comment] 2020-05-20 13:26
Thanks!

FWIW: I could just click "Close" on the hang message and after restart my modified files were still there and could be saved.
