### ISSUE TITLE
Text/images overlap on Extensions details page

### ISSUE THREAD

**Issue by Xavi007** [microsoft/vscode#111956] opened 2020-12-06 03:05 UTC
- VSCode Version: 1.51.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Go to Extensions page like Remote-Containers
2. Scroll the page under Details section

[After scrolling][Extensions page](https://www.dropbox.com/s/m6n0i7lm0xscyrr/Screenshot%20from%202020-12-06%2008-13-51.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by NaveenKumarMN20** [comment] 2020-12-06 15:54
Faced the same issue with windows.

- OS: **Windows 10**
- VSCode: **Version: 1.51.1**

![vscode text overlap](https://user-images.githubusercontent.com/25030929/101285010-05e9c680-3809-11eb-960e-44cd03386d43.PNG)

**Comment by jeanp413** [comment] 2020-12-07 14:30
I think this is a duplicate of #107104 which is already fixed in insiders and will be available in the November release
@Xavi007 @NaveenKumarMN20 can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by NaveenKumarMN20** [comment] 2020-12-08 01:06
@jeanp413 **Thanks for the update**, Checked with **vscode insiders build**, i was not able to reproduce the issue.
![image](https://user-images.githubusercontent.com/25030929/101423597-7c78e800-391f-11eb-93ae-023fdbb72d66.png)

**Closed** 2020-12-08 07:28 UTC
Labels: needs more info
