### ISSUE TITLE
No syntax highlighting for JS functions

### ISSUE THREAD

**Issue by Velds** [Microsoft/vscode#8610] opened 2016-07-01 10:20 UTC
**Sysinfo**
- VSCode Version: 1.2.1
- OS Version:  Win10

**Steps to Reproduce**

1.  Use any defined function
2.  Observe no syntax highlighting

**Example**

```
const thisFunction = () => {
	return new Promise((resolve, reject) => {
		resolve('Works!')
	})
}

thisFunction.then((res) => {
	console.log(res)
}).catch(console.error)
```

I would expect there to be highlighting on the function call block, but VS code just colors the entire thing as white, as shown here (the syntax is set to JS):
![2016-07-01 14_48_04- untitled-1 - wandbook - visual studio code](https://cloud.githubusercontent.com/assets/7088852/16519904/5b6f9a62-3f9d-11e6-9858-4b4662392517.png)

**Comment by egamma** [comment] 2016-07-01 10:31
@Velds what theme are you using? Did you try the VSCode Dark/Light+ themes?

**Comment by Velds** [comment] 2016-07-01 10:46
@egamma I have the same issue for Dark/Light and Dark+/Light+, as well as every other theme installed by default.

**Comment by egamma** [comment] 2016-07-01 16:29
@Velds The grammar we are using for JS doesn't color function and variable references in JS files.
If you want this, then we just made another grammar available as an extension. Can you please give it a try: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar

**Comment by egamma** [comment] 2016-07-01 16:29
@aeschli fyi

**Comment by Velds** [comment] 2016-07-01 17:20
@egamma Seems odd that the default grammar doesn't support what is (imo) pretty standard functionality.  The js-atom-grammar extension works well, thank you.

**Comment by glen-84** [comment] 2016-07-01 18:13
Duplicate of #3886.

**Closed** 2016-07-14 20:57 UTC
