### ISSUE TITLE
Virtual document seems to stay open long after only TextEditor is closed

### ISSUE THREAD

**Issue by Ptival** [microsoft/vscode#133054] opened 2021-09-14 03:51 UTC
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0

I need to run some action when a text editor is closed, and for some reason this has become **very** complicated after the deprecation of `onDidCloseTextEditor`.

Supposedly you're now supposed to use `onDidChangeVisibleTextEditors`. I have code like this:

```typescript
vscode.window.onDidChangeVisibleTextEditors(visibleEditors => {
  // Not sure how to compare TextEditors, and the doc is lacking...
  if (!visibleEditors.some(e => e.document.uri.toString() === targetEditor.document.uri.toString())) {
    if (targetEditor.document.isClosed) {
      // Cleanup
    }
  }
})
```

But `isClosed` evaluates to `false` when I close the related text editor. Even switching tabs to make this handler fire again shows `isClosed` set to `false` minutes after the text editor is gone.

I am not sure whether the document is still considered open. If so, is there a way to indicate to VSCode that the document should be closed when that editor is closed? (It's not a text document, just some virtual document created with my own scheme via `registerTextDocumentContentProvider` and `openTextDocument`).

Not sure if this will reproduce, but the code is more or less:

```typescript
class MyContentProvider implements vscode.TextDocumentContentProvider {

	static scheme = 'my-scheme'

	private _lastResult = ''
	private _onDidChangeEmitter = new vscode.EventEmitter<vscode.Uri>()
	onDidChange = this._onDidChangeEmitter.event

	dispose() {
		this._onDidChangeEmitter.dispose()
	}

	provideTextDocumentContent(_uri: vscode.Uri): string {
		return this._lastResult
	}

	update(uri: vscode.Uri, s: string): void {
		this._lastResult = s
		this._onDidChangeEmitter.fire(uri)
	}

}

// And then in my extension activation:

	const runWatchProvider = new MyContentProvider()

	context.subscriptions.push(
		runWatchProvider,
		vscode.workspace.registerTextDocumentContentProvider(
			MyContentProvider.scheme,
			runWatchProvider,
		),
	)

	const uri = vscode.Uri.parse(`${MyContentProvider.scheme}:whatever`, true)

	const doc = await vscode.workspace.openTextDocument(uri)

	const myEditor = await vscode.window.showTextDocument(doc, {
		preserveFocus: true,
		preview: false,
		viewColumn: vscode.ViewColumn.Beside,
	})

	vscode.window.onDidChangeVisibleTextEditors(visibleEditors => {
		// Not sure how to compare TextEditors, and the doc is lacking...
		if (!visibleEditors.some(e => e.document.uri.toString() === myEditor.document.uri.toString())) {
			if (myEditor.document.isClosed) {
				// This never happens!
			}
		}
	})

```

I just need a way to trigger some action when that text editor is closed, it seems like a reasonable ask of an IDE!

**Comment by jrieken** [comment] 2021-09-14 07:37
/duplicate of https://github.com/microsoft/vscode/issues/15178

**Comment by jrieken** [comment] 2021-09-14 07:39
Use `onDidCloseTextDocument` to know that a document (not editor) has been closed. The editor will decide when to close documents and that's not always when an editor is closed. For the latter there is #15178 which is about exposing the tab-model (which is different from open editors)

**Closed by jrieken** 2021-09-14 07:39 UTC
