### ISSUE TITLE
An error occurred while loading the image

### ISSUE THREAD

**Issue by thatgamingguy789** [microsoft/vscode#87862] opened 2019-12-30 02:20 UTC
I added a file, SOL.jpg, however the image does not load and instead I receive "An error occurred while loading the image".

**Comment by shogerr** [comment] 2019-12-30 05:35
Hey @thatgamingguy789, do you think you could provide the steps you took to create this issue, and potentially a screenshot of what the error looks like?

**Comment by mjbvz** [comment] 2020-01-06 23:41
Closing as not actionable without steps to reproduce

**Closed by mjbvz** 2020-01-06 23:41 UTC
Labels: needs more info
