### ISSUE TITLE
Windows not responding

### ISSUE THREAD

**Issue by subrat09-subrat** [microsoft/vscode#181666] opened 2023-05-05 20:54 UTC
Type: <b>Bug</b>

When i start my vs code there is a pop up window showing window isn't responding what to do?

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz (8 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (8.39GB free)|
|Process Argv|--crash-reporter-id 7b88fb0d-b8ab-4c4e-b5e5-4e66bc6b87b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
settings-repository|Kat|1.0.4
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052
pythongtdpath:30731978

```

</details>

**Comment by tamuratak** [comment] 2023-05-08 00:50
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by ulugbekna** [comment] 2023-05-08 10:50
Likely duplicate of #178733 

Please, see https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Closed by ulugbekna** 2023-05-08 10:50 UTC
Labels: triage-needed, new release
