### ISSUE TITLE
 Inconsistent tree: can't override leaf with branch.

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#82582] opened 2019-10-15 12:57 UTC
Issue Id: <b>19ccb527-7281-4d32-47a8-9399a9ece1ec</b><br /><br />*Versions* <br />- 1.39.1<br />-  9df03c6d6ce97c6645c5846f6dfa2a6a7d276515<br />-  c8252b63f547674d2faf361d4181bb76b0b5f81a<br />-  5cd3b2abc98ebc8c8e226f0cd95a9bca93e2b4ad<br />*Stack* <br />Error: Inconsistent tree: can't override leaf with branch.<br />[/vs/base/common/resourceTree.ts#140:11 (add)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/base/common/resourceTree.ts#L140:11 (add))<br />[/vs/workbench/contrib/scm/browser/repositoryPanel.ts#451:13 (onDidSpliceGroup)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/contrib/scm/browser/repositoryPanel.ts#L451:13 (onDidSpliceGroup))<br />[/vs/workbench/contrib/scm/browser/repositoryPanel.ts#428:37 (call)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/contrib/scm/browser/repositoryPanel.ts#L428:37 (call))<br />[/vs/base/common/event.ts#580:15 (fire)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/base/common/event.ts#L580:15 (fire))<br />[/vs/workbench/api/browser/mainThreadSCM.ts#48:20 (splice)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/browser/mainThreadSCM.ts#L48:20 (splice))<br />[/vs/workbench/api/browser/mainThreadSCM.ts#223:10 ($spliceGroupResourceStates)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/browser/mainThreadSCM.ts#L223:10 ($spliceGroupResourceStates))<br />[/vs/workbench/api/browser/mainThreadSCM.ts#365:11 (apply)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/browser/mainThreadSCM.ts#L365:11 (apply))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#398:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L398:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#383:31 (_invokeHandler)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L383:31 (_invokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#299:18 (_receiveRequest)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L299:18 (_receiveRequest))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#226:9 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L226:9 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#101:41](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L101:41)<br />    at c<br />

**Comment by joaomoreno** [comment] 2019-10-16 13:47
Dupe of already fixed candidate.

**Closed by joaomoreno** 2019-10-16 13:47 UTC
