### ISSUE TITLE
"Your First Extension" example only works with powershell as integrated shell in Windows 10

### ISSUE THREAD

**Issue by phloose** [microsoft/vscode#84991] opened 2019-11-17 12:48 UTC
- VSCode Version: 1.40.1 (user setup)
- OS Version: Windows 10 Education 1909

When trying out the example from https://code.visualstudio.com/api/get-started/your-first-extension on Windows 10 hitting F5 has no effect and doesn't open the `extension development host` when powershell **is not** set as shell executable for the `npm: watch` task or **is not** the default shell used in the terminal. It simply does say `building extension` forever and nothing happens, no error, simply nothing. In the task tab it shows the command `> Executing task: npm run watch <` but it doesn't seem that it is run. By manually typing this command in that specific tab the extension host opens finally, but i don't think that this is the intended behaviour.

My edited `tasks.json`:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "watch",
            "problemMatcher": "$tsc-watch",
            "isBackground": true,
            "presentation": {
                "reveal": "never",
                "echo": true
            },
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "shell": {
                    "executable": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
                }
            }
        }
    ]
}
```
I think that should be mentioned on that page espcially for windows users trying out this tutorial. The tutorial itself is very simple but if opening the extension host doesn't work it is useless and prevents new developers from creating extensions.

**Comment by octref** [comment] 2019-11-18 19:12
I can repro this with:

- `npm i typescript`
- Create a `package.json` like below

```json
{
  "dependencies": {
    "typescript": "^3.7.2"
  },
  "scripts": {
    "foo": "tsc --version"
  }
}
```

- Create a `tasks.json` like below

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "foo",
            "problemMatcher": []
        }
    ]
}
```

With WSL set as default shell: Run this task. I would expect it to complete, but in the task output I get "The terminal process terminated with exit code: 1" with no other information.

With PS set as default shell: Run this task. It shows below error:

```
PS C:\Users\octref\Desktop\foo> npm run foo

> @ foo C:\Users\octref\Desktop\foo
> tsc --version

'tsc' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ foo: `tsc --version`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ foo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\octref\AppData\Roaming\npm-cache\_logs\2019-11-18T19_06_41_219Z-debug.log
```

I remember both worked as some point in the past. IMO the NPM task should handle these.

**Comment by alexr00** [comment] 2019-11-19 09:00
Couple questions/thoughts:
- @phloose what are you using as your integrated shell? I tried cmd and it worked. I tried wsl and it didn't (I'm looking into that now, I agree it should work).
- @octref You are seeing some other problem. As far as I know `tsc` isn't added to your Windows path by default, so if you run `tsc --version` from any terminal it won't work. Your project is missing something, because when I make the same `foo` task in the "Your First Extension" example with powershell it works.
```
> Executing task: npm run foo <


> helloworld@0.0.1 foo C:\Users\alros\Documents\testyo\helloworld
> tsc --version

Version 3.7.2

```

**Comment by alexr00** [comment] 2019-11-19 09:34
In addition to the above question, @phloose what is the exact version number of Windows that you have? This is starting to look like an change in WSL behavior since I'm seeing one version of 1909 show zero output from `wsl -e` and a slightly later version of 1909 still show output from `wsl -e`.

@phloose can you also try opening a regular cmd.exe and running `wsl.exe -e npm --version` (assuming you have npm, otherwise pick a different command that you know works on your system and provides some output). Do you get any output from that?

**Comment by phloose** [comment] 2019-11-19 09:54
> what are you using as your integrated shell? I tried cmd and it worked. I tried wsl and it didn't (I'm looking into that now, I agree it should work).

I am using cmd.exe as my integrated shell. Without this

```json
"options": {
                "shell": {
                    "executable": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
                }
            }
```
it doesn't work when cmd.exe **is explicitly set** in settings.json. 

> can you also try opening a regular cmd.exe and running wsl.exe -e npm --version (assuming you have npm, otherwise pick a different command that you know works on your system and provides some output). Do you get any output from that?

I never mentioned that i tried the tutorial with WSL :-) but i will try your suggestion when i get back home.

**Comment by alexr00** [comment] 2019-11-19 09:57
@phloose no need to try wsl then since that will be a different problem! Let's focus on the task not working with cmd.exe.

**Comment by alexr00** [comment] 2019-11-19 10:03
@phloose Can you try adding this setting `"terminal.integrated.windowsEnableConpty": false`, closing your integrated terminals, then trying the F5 again?

**Comment by phloose** [comment] 2019-11-19 10:04
@alexr00 will try that when i am back home! Thanks for investigating this issue!

**Comment by h2s0109** [comment] 2019-11-19 14:54
I also in the same situation. 
there is only a "Building" message in the status bar.
![image](https://user-images.githubusercontent.com/21095801/69156784-5079a180-0b27-11ea-9c80-c99531e00e8c.png)
I found the  temporary two workaround
1. when I kill the terminal after pushing the F5, It works.
2. Delete the tasks.

**Comment by octref** [comment] 2019-11-19 15:27
@alexr00 

> tsc --version from any terminal it won't work.

If I have a devDependency which installs a binary into `node_modules/.bin`, npm scripts should prefer it over a global install, correct?

So my expectation when setting up the task is VS Code would be running `npm run foo`, instead of the literal content `tsc --version`, on the CLI for me.

**Comment by alexr00** [comment] 2019-11-19 15:46
@octref  Yes, it is running `npm run foo`, but it seems like something isn't setup fully in your project since `npm run foo` isn't finding tsc. The npm task from @phloose is running nicely with powershell, which is very different from what you are seeing. The npm task with powershell just runs `powershell.exe -Command npm run foo`.

@h2s0109 If you open the terminal that your task is running in, what is the output from the task? Can you share the output?

**Comment by h2s0109** [comment] 2019-11-19 15:46
this is my terminal. 
![image](https://user-images.githubusercontent.com/21095801/69161848-190ef300-0b2f-11ea-875e-349df2a361a9.png)
![image](https://user-images.githubusercontent.com/21095801/69161917-3643c180-0b2f-11ea-841b-500abc1aee25.png)

**Comment by h2s0109** [comment] 2019-11-19 15:50
the watch doesn`t work.
but when I execute the compile it works.
![image](https://user-images.githubusercontent.com/21095801/69162250-b10cdc80-0b2f-11ea-8750-420565d580f7.png)
![image](https://user-images.githubusercontent.com/21095801/69162259-b4a06380-0b2f-11ea-8137-922b8df09d3c.png)

**Comment by alexr00** [comment] 2019-11-19 15:55
@h2s0109 thanks for the screen shots! You are seeing https://github.com/microsoft/vscode/issues/46373 
From : https://github.com/microsoft/vscode/issues/84685#issuecomment-555437362

The problem is that the typescript problem matcher is not localizable. So: 
```
[下午4:44:28] Starting compilation in watch mode...

[下午4:44:31] Found 0 errors. Watching for file changes.
```
You have some characters before the timestamp there that the `$tsc-watch` problem matcher can't deal with. I'm sad to say I see two options that are probably not ideal for you:
- Change your system language to a language that the `$tsc-watch` problem matcher can handle, such as English or another that formats the time as HH:MM:SS AM/PM.
- Modify the problem matcher to suite your needs better. You can use the following as a starting point, but you'll need to change the `beginsPattern` and `endsPattern` regexp to match your timestamp format since this one uses the English matching timestamp format:
```
"problemMatcher": {
				"base": "$tsc-watch",
				"background": {
					"beginsPattern": {
						"regexp": "^\\s*(?:message TS6032:|\\[?\\d{1,2}:\\d{1,2}:\\d{1,2}(?: AM| PM| a\\.m\\.| p\\.m\\.)?(?:\\]| -)) File change detected\\. Starting incremental compilation\\.\\.\\."
					  },
					  "endsPattern": {
						"regexp": "^\\s*(?:message TS6042:|\\[?\\d{1,2}:\\d{1,2}:\\d{1,2}(?: AM| PM| a\\.m\\.| p\\.m\\.)?(?:\\]| -)) (?:Compilation complete\\.|Found \\d+ errors?\\.) Watching for file changes\\."
					  }				
				}
			},
```

**Comment by h2s0109** [comment] 2019-11-19 16:01
**Thanks for your support now it works.!!!**
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "watch",
            "problemMatcher": {
				"base": "$tsc-watch",
				"background": {
					"beginsPattern": {
						"regexp": "^\\s*(?:message TS6029:|\\[?\\d{1,2}:\\d{1,2}:\\d{1,2}(?: 오전| 오후| a\\.m\\.| p\\.m\\.)?(?:\\]| -)) File change detected\\. Starting incremental compilation\\.\\.\\."
					  },
					  "endsPattern": {
						"regexp": "^\\s*(?:message TS6029:|\\[?\\d{1,2}:\\d{1,2}:\\d{1,2}(?: 오전| 오후| a\\.m\\.| p\\.m\\.)?(?:\\]| -)) (?:Compilation complete\\.|Found \\d+ errors?\\.) Watching for file changes\\."
					  }				
				}
			},
            "isBackground": true,
            "presentation": {
                "reveal": "never",
                "echo": true
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

**Comment by phloose** [comment] 2019-11-20 11:52
> Can you try adding this setting `"terminal.integrated.windowsEnableConpty": false`, closing your integrated terminals, then trying the F5 again?

@alexr00 Something odd happened and i don't know WHY this works now... Regardless of that winpty setting you proposed it works now with cmd.exe as integrated shell (and without that specific tasks.json option). Very weird, i tried it several times with this configuration last friday until i found out after 2 hours that i can use powershell for a task to make it work. 

During my attempts to make it work today it still didn't work in the way that the tsc problemMatcher sometimes was not able to match the output of the npm watch task and so the extensionhost didn't open.... 

At the moment i am a bit puzzled why this behaves so strange...

I have to say that if add shell arguments with `terminal.integrated.shellArgs.windows` i doesn't work (I use [cmder](https://cmder.net/) as console emulator which needs to be activate with the /k switch). But last friday i tested it also without these arguments and it didn't work... 

Are tasks or extensionhost settings cached somewhere?

**Comment by alexr00** [comment] 2019-11-20 14:12
@phloose
- The task will run with powershell or with cmd ✔
- The problem matcher still isn't working ❌
    Can you share the output of your task?
- You are using cmder for `terminal.integrated.shell.windows`
    Tasks doesn't explicitly support cmder. If it works, cool. If it doesn't, you should use a different shell for tasks with `terminal.integrated.automationShell.windows`. 
- You are changing `terminal.integrated.shellArgs.windows`.
    Using the `automationShell` setting above will cause tasks to ignore this settings, which is almost certainly what you want.

**Comment by phloose** [comment] 2019-11-20 14:24
@alexr00 i didn't know about that setting! Thanks for letting me know! Is it somewhere mentioned in the docs?

>     The problem matcher still isn't working ❌
>       Can you share the output of your task?

There is nothing different to the output when it successfully runs in powershell, i suppose i maybe did not close my shells... atm i cannot reproduce it. Will try the setting you pointed me to!

**Comment by alexr00** [comment] 2019-11-20 14:28
Docs: https://code.visualstudio.com/Docs/editor/tasks#_can-a-task-use-a-different-shell-than-the-one-specified-for-the-integrated-terminal

**Closed** 2019-11-20 14:29 UTC
Labels: needs more info, tasks

**Comment by octref** [comment] 2019-11-20 16:48
@alexr00 Can you advise (or just push a change) how should I modify https://github.com/microsoft/vscode-extension-samples/blob/master/helloworld-test-sample/.vscode/tasks.json so it would work best on Windows?

**Comment by alexr00** [comment] 2019-11-21 08:43
@octref It works great on Windows for me now. In general, unless your tasks are complicated or your setup is unusual, task don't need any special treatment for Windows.
