### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by BeiJiXingYu** [microsoft/vscode#73318] opened 2019-05-06 02:54 UTC
Issue Type: <b>Performance Issue</b>

使用中cpu占用率会突然升高至90%以上，关闭VScode后恢复正常

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (3.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
cssrem|cip|0.0.7
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|1.8.2
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
vscode-nginx-conf-hint|han|0.1.0
beautify|Hoo|1.5.0
weex|jay|0.4.0
docthis|joe|0.7.1
svn-scm|joh|1.48.1
prettify-json|moh|0.0.3
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
vscode-language-pack-zh-hans|MS-|1.32.4
mssql|ms-|1.5.0
js-atom-grammar|ms-|0.1.14
debugger-for-chrome|msj|4.11.3
vetur|oct|0.19.5
es6-css-minify|olb|2.6.0
vuehelper|oys|0.1.0
vscode-versionlens|pfl|0.23.0
material-icon-theme|PKi|3.7.0
vscode-css-peek|pra|2.2.0
vscode-jsp|pth|0.0.2
view-in-browser|qin|0.0.5
sass-indented|rob|1.5.1
vscode-nginx|sha|0.6.0
language-stylus|sys|1.11.0
ayu|tea|0.18.0

(2 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment] 2019-05-06 03:29
Hey @BeiJiXingYu , can you follow the guide here to try to diagnose the problem? https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by zehawki** [comment] 2019-05-06 16:25
Its impossible to use VS Code like this. Can we have a solution please. Pretty please. High CPU usage issue has been pointed out so many times now at SO, github, reddit and so on. 

1. Nearly constant CPU usage of close to 40%. I'm doing nothing on VS Code right now, still the constant CPU usage.

![image](https://user-images.githubusercontent.com/8095144/57239326-31af3400-7049-11e9-9a58-f5d663037104.png)

2. Every time I type, the CPU usage spikes, 

![image](https://user-images.githubusercontent.com/8095144/57239461-92d70780-7049-11e9-9a71-b33f7d9575ba.png)

3. Periodically it will reach 80 - 90% and just stay there till I close VS Code and then the rigmarole starts again.

NO extensions are enabled.

**Comment by zehawki** [comment] 2019-05-06 16:27
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    93	 54260	code main
    1	    66	 41424	   window (Issue Reporter)
    0	   293	 42488	   window (● location_card.js - ne_frontend (Workspace) - Visual Studio Code)
    0	    13	 50572	     electron-crash-reporter
    0	    89	 53220	     extensionHost
   27	   981	 65512	       electron_node tsserver.js 
    0	    44	 44940	         electron_node typingsInstaller.js typesMap.js 
    0	    38	 58528	     watcherService
    0	    33	 62268	     searchService
    0	   255	 62388	   gpu-process
    0	    72	 64456	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● location_card.js - ne_frontend (Workspace) - Visual Studio Code)
|    Folder (ne_frontend): more than 29294 files
|      File types: js(14399) ts(6350) json(2504) md(1882) map(859) png(230)
|                  yml(205) svg(201) flow(198) mjs(162)
|      Conf files: package.json(1384) tsconfig.json(52) makefile(28)
|                  webpack.config.js(10) tslint.json(7) grunt.js(4) gulp.js(3)
|                  settings.json(2);
```

</details>
Extensions: none

**Comment by RMacfarlane** [comment] 2019-05-06 17:08
Thanks for the additional info @zehawki, from the process info it looks like the typescript server is what's using high CPU for you. Are you in a workspace that has `@types/styled-components` installed? Please make sure it's the latest version (see this [issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391))

@BeiJiXingYu can you also include process information?

**Comment by zehawki** [comment] 2019-05-10 08:39
> Are you in a workspace that has @types/styled-components installed?

Sorry, a bit of a stupid question - how do I check that? I've not installed any package for this, neither is it in my package.json. But could it have come in via a library, e.g. like this https://material-ui.com which I'm using. Where can I check? Thanks.

**Comment by LeoLozes** [comment] 2019-05-17 10:23
I'm having the same issue, the `electron_node tsserver.js` process uses 20-30% of the CPU constantly. 
I'm using `material-ui` as well.
I already had the same issue and [fixed it before](https://github.com/microsoft/vscode/issues/71751#issuecomment-480126916) but this should be fixed without having to do this manually every time.

**Comment by mjbvz** [comment] 2019-05-17 16:54
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by LeoLozes** [comment] 2019-05-17 17:26
@mjbvz I don't recall having this issue with the latest insider build. I had it with the last and current VS Code releases, and I fixed it both times with the workaround I linked.

**Comment by mjbvz** [comment] 2019-05-22 22:53
Closing as we need more information from @BeiJiXingYu

IF you are still seeing performance issues in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/), please open a new issue

**Closed by mjbvz** 2019-05-22 22:53 UTC
Labels: needs more info, perf
