### ISSUE TITLE
Cannot save setting to setting.json and keybindings.json if they are symlink. (Windows and Linux)

### ISSUE THREAD

**Issue by 9527KGG** [Microsoft/vscode#72392] opened 2019-04-16 07:19 UTC
- VSCode Version: 1.33.1
- OS Version: Ubuntu 18 LTS and Windows 10 ENT

Steps to Reproduce:

On Windows, I use this cmd to create symlink:
mklink %APPDATA%\Code\User\keybindings.json %USERPROFILE%\\.xxx\keybindings.json
mklink %APPDATA%\Code\User\settings.json %USERPROFILE%\\.xxx\settings.json

On Linux, I use this cmd to create symlink:
ln -s $HOME/.xxx/settings.json $HOME/.config/Code/User/settings.json
ln -s $HOME/.xxx/keybindings.json $HOME/.config/Code/User/keybindings.json

On both OS, I tried to change font size from 14 to 13. Bot VS Code prompt error saying the change to json file cannot be saved.

Does this issue occur when all extensions are disabled?: Yes, not plug related.

**Comment by 9527KGG** [comment] 2019-04-16 07:21
.xxx\keybindings.json is a file in git repro. However, I don't think it's related to git, because notepad can open/save the change.

**Comment by 9527KGG** [comment] 2019-04-16 07:22
I don't think it's the same as this one, https://github.com/Microsoft/vscode/issues/37591, since I can repro the issue on both OS.

**Comment by mittalyashu** [comment] 2019-04-16 07:39
As far I know symlink only allows you to read data not write data. 🤔

**Comment by 9527KGG** [comment] 2019-04-16 16:45
> As far I know symlink only allows you to read data not write data. 🤔

no. it's writable.

on Linux, 

touch 1.txt
ln -s 1.txt 1

1 can be changed/saved by any text editor. And 1.txt will have the change.

**Comment by roblourens** [comment] 2019-04-17 03:25
I think that this is the same as https://github.com/Microsoft/vscode/issues/37591#issuecomment-341669901, it just exists on both platforms.

You may be able to work around this if the whole User folder is a symlink to another folder.

**Comment by 9527KGG** [comment] 2019-04-17 03:31
Thanks. But "User folder" has many files which I don't care (don't want to keep in git.)

**Comment by roblourens** [comment] 2019-04-17 15:46
Add them to `.gitignore`?

**Comment by 9527KGG** [comment] 2019-04-17 17:28
Thanks. Should work. But I would say it's a workaround instead of a solution.

**Comment by sandy081** [comment] 2019-04-25 09:09
@bpasero I use file service to do the changes, any reason why it is not working in this case?

**Comment by bpasero** [comment] 2019-04-25 09:43
I cannot reproduce when I tried on macOS with links. On Windows, the way you create symbolic links for files is not supported by node.js, so that is expected. I do not think there is an issue with VSCode here.

**Comment by sandy081** [comment] 2019-04-25 10:02
@bpasero Assigning it to you as it is related to file service.

**Closed** 2019-04-25 10:15 UTC
Labels: *not-reproducible
