### ISSUE TITLE
editor.wordBasedSuggestions in HTML

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#7552] opened 2016-06-11 01:50 UTC
- VSCode Version: 1.2.0
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Ideally, the same suggested word to all languages, not only for languages ​​specify. For bringing "`editor.`" Tended to generalize the function. If it were a specific language being could be, for example: "`html.wordBasedSuggestions`", “`java.wordBasedSuggestions`”, “`javascript.wordBasedSuggestions`”.

If possible, I would like this feature was available in HTML, among others, working similarly to Plain Text and Markdown.

1- Suggest words that are not tag.
2- Suggest words between the head and body tags and the tag inside. Between both not show suggestion.

![1](https://cloud.githubusercontent.com/assets/19866231/15982252/4e1d3c92-2f59-11e6-9dbd-ce9e104e1ad2.PNG)

3- Have option to enable and disable to suggest so they are digitas. (How in Plain Text by typing only one letter). But only between tags (eg: `<h1> </ h1>` ).
Configuration suggestion: "`html.wordBasedSuggestionsAutomatic: true or false`".

![2](https://cloud.githubusercontent.com/assets/19866231/15982259/6c69e998-2f59-11e6-903a-0576e7afb0e0.PNG)

4- Have the option to turn on and off to "force the suggestion" with the shortcut `Ctrl + Space` (How in Plain text when not typed the letter or how it works in Markdown) within tags (eg: `<h1> < / h1>`). Configuration suggestion: "`html.wordBasedSuggestionsforced: true or false`".

![3](https://cloud.githubusercontent.com/assets/19866231/15982273/bec306ca-2f59-11e6-82a4-e05a186e2dbc.PNG)

5- Following the idea to number 4, within quotation marks (" "), but typing the first letter plus the shortcut `Ctrl + Space` to be able to show up the suggestion when there is no standard suggestion. Configuration suggestion: "`html.wordBasedSuggestionsforced: true or false`".

![4](https://cloud.githubusercontent.com/assets/19866231/15982275/d03d1e4a-2f59-11e6-99e8-04e3403c8f78.PNG)

For "`html.wordBasedSuggestionsAutomatic: true or false`" and "`html.wordBasedSuggestionsforced: true or false`" work "`html. wordBasedSuggestions `"must be as true.

Best suggestions are welcome..

**Comment by jrieken** [comment] 2016-09-27 12:33
closing as dupe of #10819 which is a little easier to understand and has more use-cases

**Closed by jrieken** 2016-09-27 12:33 UTC
Labels: feature-request, suggest

**Comment by Tekbr** [comment] 2016-09-28 14:49
-- Sorry for the English, I used Google Translator --

@jrieken Ok, sorry for English. Like that word suggestion based on previously typed words happen in any language, and in different situations, as I tried to show the images.

**Comment by jrieken** [comment] 2016-09-28 15:25
Yes - that what #10819 is about.
