### ISSUE TITLE
Selected text color is the same as the text color itself

### ISSUE THREAD

**Issue by Kopacb007** [microsoft/vscode#123154] opened 2021-05-06 15:44 UTC
Issue Type: <b>Bug</b>

Since the last update, any input textbox (ex. Cmd+F to search some text) has this visual problem:
The selected text is unreadable because the color of the selection is the same as the text color itself.

VS Code version: Code 1.56.0 (Universal) (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin arm64 20.3.0
Remote OS version: Windows_NT x64 10.0.19041
Remote OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Ipernet|
|OS|Windows_NT x64 10.0.19041|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.94GB (8.42GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Ipernet|
|OS|Windows_NT x64 10.0.19041|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.94GB (8.42GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
vscode-remote-extensionpack|ms-|0.20.0
sublime-keybindings|ms-|4.0.9
vscode-icons|vsc|11.4.0
alignment|ann|0.3.0
path-intellisense|chr|2.3.0
indent4to2|Com|0.1.2
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
vstortoise|flo|1.2.2
vscode-drawio|hed|1.4.0
beautify|Hoo|1.5.0
svn-scm|joh|2.13.5
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.3
vscode-filesize|mkx|3.1.0
prettify-json|moh|0.0.3
vetur|oct|0.33.1
vscode-paste-and-indent|Rub|0.0.8
sass-indented|syl|1.8.16

</details>

**Comment by IperStan** [comment] 2021-05-06 15:47
Apologies for the lack of screenshots in the first comment
 
![image](https://user-images.githubusercontent.com/43338672/117327521-fabbc500-ae92-11eb-87d9-495b503921ee.png)

![image](https://user-images.githubusercontent.com/43338672/117327666-2474ec00-ae93-11eb-8fe7-2748ddf1a7b8.png)

**Comment by Kopacb007** [comment] 2021-05-06 15:49
Apologies for the lack of screenshots in the first comment
 
![image](https://user-images.githubusercontent.com/43338672/117327521-fabbc500-ae92-11eb-87d9-495b503921ee.png)

![image](https://user-images.githubusercontent.com/43338672/117327666-2474ec00-ae93-11eb-8fe7-2748ddf1a7b8.png)

**Comment by JacksonKearl** [comment] 2021-05-06 19:46
@misolori do you know of any changes to coloring here?

**Comment by misolori** [comment] 2021-05-07 13:16
@JacksonKearl haven't seen any known changes for selection. This also doesn't appear in other themes.

**Comment by misolori** [comment] 2021-05-09 17:17
Closing as duplicate of #123044

**Closed by misolori** 2021-05-09 17:17 UTC
Labels: new release
