### ISSUE TITLE
Terminal List Dropdown shows blank for the first time

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/vscode#27030] opened 2017-05-21 14:57 UTC
- VSCode Version: 1.12.2
- OS Version: Windows Insider Build 16199

Steps to Reproduce:

1. Launch VSCode.
2. Press **Ctrl + `** to view Terminal.
3. Press on the **+** button next to the Terminal list dropdown for New Terminal (_You may press it several times_). New Terminal(s) shows up.
4. Press on the down arrow in the Terminal list dropdown. 
    **Expected Result** : The dropdown list should display list of Terminals.
    **Actual Result** : The dropdown list is blank. (_Although the height of the dropdown list is proportional to the number of Terminals_) 
5. Click elsewhere to dismiss the dropdown list.
6. Press on the down arrow in the Terminal list dropdown again.
7. The drop down list **now** shows the list of Terminals properly.

**Comment by KillyMXI** [comment] 2017-11-22 01:43
Got this too:
![](https://i.imgur.com/ZLQQxiD.png)

I also got it in debug profiles dropdown once (no screenshot unfortunately). There it was like dropdown content was shown with a big margin, and the dropdown itself was with overflow: hidden -- just a part of first item was visible at the bottom of otherwise empty dropdown.

**Comment by KillyMXI** [comment] 2017-11-22 01:54
Ah. Must be a duplicate of #25700.

**Comment by bpasero** [comment] 2017-12-08 06:47
Yeah it is.

**Closed by bpasero** 2017-12-08 06:47 UTC
Labels: bug, integrated-terminal
