### ISSUE TITLE
provide a config don't change eol

### ISSUE THREAD

**Issue by alianZhen** [microsoft/vscode#108711] opened 2020-10-15 06:49 UTC
I need a new eol config.

Sometimes I don't want to change lines eol.Just keep 2 kinds of eol in one file.

Is it possible?Or you can tell me how to implement.I don't know how to implement it.
![image](https://user-images.githubusercontent.com/27906971/96086878-8bca4f00-0ef5-11eb-91df-4e127184236c.png)

**Comment by alexdima** [comment] 2020-10-15 08:46
Duplicate of #127

**Closed** 2020-10-15 08:46 UTC
