### ISSUE TITLE
When saving, it always shows error "EBUSY: resource busy or locked"

### ISSUE THREAD

**Issue by Timber-wanglu** [Microsoft/vscode#30781] opened 2017-07-15 23:54 UTC
When saving a file, it always shows an error "EBUSY: resource busy or locked", and i have tried to create many files and save them, most of them cannot be saved because of this error. 
![default](https://user-images.githubusercontent.com/27400465/28243395-5ec4954a-69fa-11e7-9969-8a60e879c49c.PNG)

**Comment by bpasero** [comment] 2017-07-16 17:28
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Timber-wanglu** [comment] 2017-07-17 06:28
I found that running 'taskkill /IM Microsoft.VSCode.CPP.IntelliSense.Msvc.exe /F' when saving failed can solve this problem. Maybe the extension caused this problem.

**Comment by bpasero** [comment] 2017-07-17 09:05
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2017-07-17 09:05 UTC
Labels: needs more info, workbench

**Comment by Joshfindit** [comment] 2017-07-21 11:10
I don't get this **all** the time, but I am getting it consistently.

(Potentially) important bits:
- Working with `.html` files while they are also open in Chrome (edit > save > reload)
- Typically I can edit, save, and refresh the file a few times until it stops saving.
    *The first fix that worked was to make a copy in the filesystem, delete the original (which has no 'in use' errors), then rename the copy to replace it*
- Running on a Win 7 SP1 64bit corporate workstation (with Trend Micro Officescan)
- Running without Admin privileges by using the portable zip
- Installed only 1 extension ever: `sftp`
- Disabled the extension after reading this thread this morning: same issue
- Uninstalled it: same issue
- ran `code --disable-extensions`: same issue
