### ISSUE TITLE
Allow merging in external `tasks.json` files (and other workspace configuration)

### ISSUE THREAD

**Issue by jseward** [Microsoft/vscode#69236] opened 2019-02-22 18:33 UTC
I would like to setup a project that has nice `vscode` support on the first pull.

ex. 

- `settings.json` has project specific `file.associations` setup.
- `tasks.json` has project specific tasks.

One solution would be to add `.vscode` folder to the root of the project. But...
1. doesn't look great if this in the root git repo, supposed to be a hidden folder.
2. some tasks need user specific variables. ex. path to `llvm`. Could potentially use environment variables but would rather not.

The desired solution would be if users could specify external `tasks.json` (or `settings.json`) to merge in, with variables.

**Comment by alexr00** [comment] 2019-02-25 09:38
Duplicate of #43151, since that functionality would enable this too.

**Closed** 2019-02-25 09:38 UTC
Labels: *duplicate, tasks
