### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by monsterdynamics** [microsoft/vscode#106648] opened 2020-09-14 11:21 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200913

**Steps to reproduce crash**
1. Happend after directly starting VS code where a .tsx was already active (not sure if relevant but happend after an upgrade from Ubunut 19.04 to 20.04)

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13450:55)
    at getTextOfNode (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13475:16)
    at Object.declarationNameToString (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13787:66)
    at getDisplayName (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39842:53)
    at declareSymbol (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39956:111)
    at bindExportsPropertyAssignment (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:42066:17)
    at bindWorker (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41762:29)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41651:13)
    at bindExpressionStatement (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40716:13)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40201:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40247:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27565:21)
    at bindEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bindContainer (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at visitNode (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27644:24)
    at bindEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at bindCallExpressionFlow (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41078:21)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40229:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at bindExpressionStatement (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40716:13)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40201:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40247:21)
    at bindContainer (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40134:17)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at bindIfStatement (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40543:13)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40178:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40247:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27565:21)
    at bindEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bindContainer (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at Object.forEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at visitNodes (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27440:24)
    at Object.forEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27634:21)
    at bindEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindCallExpressionFlow (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41081:21)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40229:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27529:21)
    at bindEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindVariableDeclarationFlow (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40974:13)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40222:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at Object.forEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at visitNodes (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27440:24)
    at Object.forEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27690:24)
    at bindEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27688:21)
    at bindEachChild (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40241:21)
    at bindContainer (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at bindSourceFile (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39708:17)
    at Object.bindSourceFile (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39647:9)
    at initializeTypeChecker (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:77643:20)
    at Object.createTypeChecker (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:43696:9)
    at Object.getTypeChecker (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:104892:79)
    at synchronizeHostData (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:145287:21)
    at Proxy.getProgram (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:145369:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:150226:53)
    at ConfiguredProject.Project.updateGraph (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:150159:42)
    at ConfiguredProject.updateGraph (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:151093:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/sina/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:152797:25)
```

**Comment by mjbvz** [comment] 2020-09-14 18:19
Duplicate of https://github.com/microsoft/TypeScript/issues/40513

**Closed by mjbvz** 2020-09-14 18:19 UTC
