### ISSUE TITLE
Unable to install any extension on macOS 10.15.5

### ISSUE THREAD

**Issue by JoeCianflone** [microsoft/vscode#98760] opened 2020-05-28 19:38 UTC
- VSCode Version: latest 
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. Update your system to latest macOS
2. Try to install anything

Does this issue occur when all extensions are disabled?: Yes/No ...

I've deleted Code and even `rm -Rf` the `Code` folder in `Application Support` but even after doing that, and reinstalling the latest version of VSCode I cannot install any extension. 
![Screen Shot 2020-05-28 at 3 37 18 PM](https://user-images.githubusercontent.com/989648/83185537-24a02f80-a0f9-11ea-9b72-c7d0f088261b.png)

Also, I had extensions installed but they were gone...which is what lead me to this point. By gone I mean VSCode did not load them.

**Comment by ibrunodev** [comment] 2020-05-28 19:54
Same problem here.

![Screenshot from 2020-05-28 16-54-25](https://user-images.githubusercontent.com/54270340/83187069-f2e09600-a103-11ea-97de-c1c26d524c0a.png)

**Comment by JoeCianflone** [comment] 2020-05-28 19:58
I just tried giving VSCode full disk access to my mac...figured maybe it was a permission issue on my end or something specific to 10.15.5 or something silly. Still won't install anything.

**Comment by IllusionMH** [comment] 2020-05-28 20:35
/duplicate of #98726

Just checked on Windows and update with fix already available.

**Closed** 2020-05-28 20:36 UTC
Labels: *duplicate
