### ISSUE TITLE
Issue when renaming <div> in JSX

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#24404] opened 2017-04-10 07:18 UTC
From: https://twitter.com/vireliam/status/851151401010987009

![image](https://cloud.githubusercontent.com/assets/172399/24850008/9d09b0f6-1dce-11e7-8187-ad322d468b94.png)

**Comment by mjbvz** [comment] 2017-04-11 01:13
Sounds concerning but I can't reproduce this issue in a simple project. I'm following up with poster to see if they can provide a small sample file/project that shows this problem

**Comment by mjbvz** [comment] 2017-04-17 18:38
Closing as we need more information to investigate. If anyone can reproduce this, please try running code with all extensions disabled `code --disabled-extensions` and sharing an example file/project that demonstrates this problem

**Closed by mjbvz** 2017-04-17 18:38 UTC
Labels: javascript, needs more info, typescript
