### ISSUE TITLE
VSCode UI thread stops responding for half second every couple seconds

### ISSUE THREAD

**Issue by abirck** [Microsoft/vscode#9864] opened 2016-07-27 17:25 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Try editing a file with VSCode (tried HTML & TS files and both exhibit same problem)

This started happening after I installed VS2015 Update 3 (because VSCode kept wanting .NET Core 1.0 SDK or whatever it's called). It continues happening after I uninstalled VS2015 though.

I used a free screen recorder to show the issue but it's not the best. Hopefully it should give you an idea. First I try just holding down arrow to scroll through the file. You can see the freeze & jump. Then I try continuously typing. Again freeze then jump. This makes using VSCode VERY painful. Please let me know if there is any debugging info I can provide.

I cannot include a avi file with this bug report but it is available in this https://drive.google.com/file/d/0B_bS6TUeSpxpNDBsTFB2dlRBamM/view?usp=sharing

**Comment by richarddavenport** [comment] 2016-07-27 18:08
Might need to upload the video to youtube/dropbox/google drive and make it public.

**Comment by kieferrm** [comment] 2016-08-01 14:57
@alexandrudima any debug info @abirck can send us?

**Comment by alexandrudima** [comment] 2016-08-02 13:13
@abirck That is definitely not good, sorry about that!

Can you please do a CPU profile:
* Help > Toggle Developer Tools
* Profiles tab
* Collect JavaScript CPU Profile
* Start
* ... do the action you were doing
* Stop
* Save as a .txt file / compress as zip and drop in here

**Comment by abirck** [comment] 2016-08-02 19:55
Here's the CPU profile I collected. Thanks!

[VSCodeCPUProfile.zip](https://github.com/Microsoft/vscode/files/397986/VSCodeCPUProfile.zip)

**Comment by alexandrudima** [comment] 2016-08-12 10:07
@abirck Thank you for the cpu profile. It actually looks alright, so I'm thinking the freeze does not come from our JavaScript. 

The pauses could be caused by the main process (I'm unsure how to debug that -- @bpasero any ideas) or by the gpu process.

Does launching code with `code --disable-gpu` help in any way?

**Comment by bpasero** [comment] 2016-08-12 10:21
@abirck maybe also check if there is any process that runs high (there are several processes below Code.exe, so maybe use a tools like process monitor to find them all).

**Comment by abirck** [comment] 2016-08-12 15:43
Running 'code --disable-gpu' solved the issue! Is there more info I can collect to figure out why it happened in the first place?

**Comment by alexandrudima** [comment] 2016-08-15 09:21
@abirck I believe it is an issue in Chromium or in your GPU driver or in the interaction between the two. You can try to reproduce if you get similar behaviour when running Chrome, in which case you can file an issue against them at https://bugs.chromium.org/p/chromium/issues/list

Maybe you can post here your GPU make and/or driver so folks having similar issues can find this issue and discover the `--disable-gpu` flag...

Given that `--disable-gpu` fixes the issue, there is no actionable item on our side, so I will close this issue for now.

**Closed by alexandrudima** 2016-08-15 09:21 UTC
Labels: editor, freeze-slow-crash, needs more info, upstream
