### ISSUE TITLE
Use checkmark in the menu for Toggle Minimap

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33520] opened 2017-08-30 14:15 UTC
Extracted from https://github.com/Microsoft/vscode/issues/33456

From @chrisdias 

---

It makes me wonder, why are these all "Toggle"? Why aren't they check marks of on or off, like `File | AutoSave`.

**Comment by alexandrudima** [comment] 2017-08-30 14:16
The root cause (at least for the editor specific ones) is that they depend on which editor is focused. Since we have language specific selectors, one can enable minimap in certain file types and disable it in certain file types. We would then need to make the menus update on editor focus change.

fyi @bpasero

**Comment by Tekbr** [comment] 2017-10-19 17:11
-- Sorry for the English, I used Google Translator --

Hello @alexandrudima  and @bpasero !!

Would not this be a duplicate of #14986? The difference here asks for a single item. And at #14986 I say to have at all possible.

Thoughts? 🤔

**Closed** 2017-10-20 07:43 UTC
Labels: feature-request, menu
