### ISSUE TITLE
HighLight JSON inside of JavaScript files

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#43917] opened 2018-02-18 07:27 UTC
- VSCode Version: 1.20.1
- OS Version: Mac OS High Sierra 10.13.3

Steps to Reproduce:

Make a JSON inside of JavaScript files or paste the following

```js
const config = {
	scripts: {
		default: {
			description: "Run Electron App",
			script: "electron dist/index.js"
		},
		dev: {
			main: {
				default: {
					description: "Transpile Main Process",
					script: "webpack --config webpack.main.config.js"
				},
				watch: {
					description: "Transpile Main Process & Watch For Changes",
					script: `nps "dev.main --watch"`
				}
			},
			renderer: {
				default: {
					description: "Transpile Renderer Process",
					script: "webpack --config webpack.renderer.config.js"
				},
				watch: {
					description: "Transpile Main Process & Watch For Changes",
					script: `nps "dev.renderer --watch"`
				}
			},
			all: {
				default: {
					description: "Clean 'dist/' & transpile all files",
					script: series(cleanDist, concurrent.nps("dev.main", "dev.renderer"))
				}
			}
		}
};
```

Does this issue occur when all extensions are disabled? Yes

<img width="1194" alt="json" src="https://user-images.githubusercontent.com/16436270/36349359-f6440e7c-14aa-11e8-9a8c-4d0c5f298976.png">

**Comment by egamma** [comment] 2018-02-18 13:18
Cannot reproduce given the snippet provided above, please include the full code so that we can reproduce it. 

![image](https://user-images.githubusercontent.com/172399/36352259-8218bc26-14b6-11e8-89b4-b7aff8710f0d.png)

**Comment by deadcoder0904** [comment] 2018-02-18 15:31
Wholly hell. Ohh no I deleted it (no version control) but I was using [nps](https://github.com/kentcdodds/nps) & inside `package-scripts.js` all the content was there.

I'll give different content though which doesn't work.

```js
const npsUtils = require('nps-utils') // not required, but handy!

module.exports = {
  scripts: {
    default: 'node index.js',
    lint: 'eslint .',
    test: {
      // learn more about Jest here: https://facebook.github.io/jest
      default: 'jest',
      watch: {
        script: 'jest --watch',
        description: 'run in the amazingly intelligent Jest watch mode'
      }
    },
    build: {
      // learn more about Webpack here: https://webpack.js.org/
      default: 'webpack',
      prod: 'webpack -p',
    },
    // learn more about npsUtils here: https://npm.im/nps-utils
    validate: npsUtils.concurrent.nps('lint', 'test', 'build'),
  },
}
```

Checkout `"watch"` & `"build"` below.

<img width="781" alt="vscode" src="https://user-images.githubusercontent.com/16436270/36353631-bb4d6d74-14ee-11e8-9abe-6687085b66e8.png">

**Comment by egamma** [comment] 2018-02-18 16:51
@deadcoder0904 hmm...Still works for me. Do you have extensions installed that affect the coloring? What is the language that is shown in the bottom right corner?

![image](https://user-images.githubusercontent.com/172399/36354413-3dbcb726-14d4-11e8-9698-24a3fbbdc6da.png)

**Comment by deadcoder0904** [comment] 2018-02-18 17:24
Its `JavaScript React` for my `.js` files. Dark+ also doesn't work. No theme changes the way it is looking in my earlier screenshots. These are [the extensions](https://gist.github.com/deadcoder0904/4a0ab12b0a9541470e0e604bf71e272a) I'm using.

**Comment by egamma** [comment] 2018-02-19 15:38
Can you please confirm that this problem happens also happens when you have all extensions disabled.
How does this example  https://github.com/Microsoft/vscode/issues/43917#issuecomment-366529358 look for you when you are using the Dark+ theme.

**Comment by deadcoder0904** [comment] 2018-02-19 17:56
After disabling all extensions, it looks [like yours](https://github.com/Microsoft/vscode/issues/43917#issuecomment-366529358)

**Comment by egamma** [comment] 2018-02-20 07:27
@deadcoder0904 I went through your extensions and I speculate that this one is the one causing the problem: `vscode-babel-coloring` I don´t think it is needed any more since the JS colorizer has much improved. 

Since it isn´t an issue in VS Code I´ll close this issue.

**Closed by egamma** 2018-02-20 07:27 UTC
Labels: needs more info, new release

**Comment by deadcoder0904** [comment] 2018-02-20 08:33
Thanks I deleted the extension & styling looks good 🙌
