### ISSUE TITLE
vscode filters out valid completions of Azure resource types when matching in middle of a non-capitalized type

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#127581] opened 2021-06-29 22:44 UTC
From https://github.com/Azure/bicep/issues/3368

REPRO:

(Note: I don't think installing Bicep itself is necessary to repro, but let me know if you need more instructions. Also, I can provide instructions to build from scratch if needed.)

1) install https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-bicep extension (currently v0.4.63)
2) new file
3) set language to Bicep, wait for lang server to finish loading
4) type:

resource foo farms

EXPECTED: Completions should include Microsoft.Web/serverfarms
ACTUAL: It is filtered out:
![image](https://user-images.githubusercontent.com/6913354/123876402-25a12300-d8f0-11eb-86b0-0d4fa586ccb2.png)
![image](https://user-images.githubusercontent.com/6913354/123876427-2d60c780-d8f0-11eb-8e6c-c2418e560a8d.png)
![image](https://user-images.githubusercontent.com/6913354/123876436-33ef3f00-d8f0-11eb-83c0-422c9237696d.png)

NOTE: If the completions source is changed so that "Microsoft.Web/serverFarms" is in the list instead of ".../serverfarms", then typing "farms" will show Microsoft.Web/serverFarms" does show up.

It could make sense that serverfarms might show up lower in priority, but it doesn't seem to make sense that it's completely filtered out, especially since such completely non-contiguous character matches as this show up:
![image](https://user-images.githubusercontent.com/6913354/123876669-934d4f00-d8f0-11eb-8f65-18469fa9236d.png)

**Comment by jrieken** [comment] 2021-06-30 06:45
/duplicate of https://github.com/microsoft/vscode/issues/53715

**Closed** 2021-06-30 06:46 UTC
Labels: *duplicate, suggest
