### ISSUE TITLE
vscode can't maintain text highlight when line comment selected text over multiple lines with keyboard shortcut

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#32259] opened 2017-08-10 21:10 UTC
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. select multiple lines of code
2. use `ctrl+/` to perform single line comment on the selected text, and see that text highlight is incorrect at start of the resultant string.

Reproduces without extensions: Yes

Screenshot:
![image](https://user-images.githubusercontent.com/4483325/29192241-50d76494-7de6-11e7-87a9-41299233513c.png)

**Comment by rebornix** [comment] 2017-08-15 18:46
@r3wt it would be great if you can provide a gif then we can know what's the original selection and what's the result.

**Comment by r3wt** [comment] 2017-08-21 02:02
@rebornix my ssd failed last friday. but, i am still able to reproduce the issue, now on 

**OS**:`ubuntu budgie-remix 16.0.4.3`

**Comment by alexandrudima** [comment] 2017-10-26 08:32
Duplicate of #5964 . Fixed in 1.17

**Closed by alexandrudima** 2017-10-26 08:32 UTC
Labels: editor, editor-contrib
