### ISSUE TITLE
VSCode Terminal GUI interface having lines merged issue 

### ISSUE THREAD

**Issue by venkatch189** [microsoft/vscode#223829] opened 2024-07-26 08:28 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.1
- OS Version: Microsoft Windows 11 Enterprise

Steps to Reproduce:
I'm using Cypress framework to run Test Automation cases and noticed terminal lines merged/duplicated. issue happening in both VM's (was power on all the times) and personal laptop
1.  Close VS Code after test cases run and shutdown. Seen the following issue when open VSCode after login again
2. Run cases and disconnect VM, same kind of issue after connect to VM again

![image](https://github.com/user-attachments/assets/fdbd35e1-712c-43f9-b4bd-5fafa7e453dc)

**Comment by meganrogge** [comment] 2024-07-26 17:18
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed** 2024-12-10 13:25 UTC
Labels: upstream, windows, terminal-conpty
