### ISSUE TITLE
PR description page looks weird with maximized panel?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#87480] opened 2019-12-20 22:31 UTC
- Open a PR description
- Maximize the panel
- See strange overflow

![image](https://user-images.githubusercontent.com/323878/71296681-508edc00-2335-11ea-8db8-773de89682d5.png)

**Comment by roblourens** [comment] 2019-12-20 22:31
Or @mjbvz for webview

**Comment by sbatten** [comment] 2019-12-20 23:09
probable dupe of https://github.com/microsoft/vscode/issues/83209

**Closed** 2019-12-20 23:10 UTC
Labels: *duplicate
