### ISSUE TITLE
Searching for a setting returns hits on non-contiguous letters

### ISSUE THREAD

**Issue by manndave** [Microsoft/vscode#18814] opened 2017-01-19 21:55 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|lorem-ipsum|Tyriar|1.0.0|

---

Steps to Reproduce:

1. Open Workspace Settings
2. Search for the word 'color' (without quotes)

Expected result is any hits of the term with the letters in succession and contiguous.  

Actual result is any setting where the letters c-o-l-o-r occur anywhere in the setting or its comment, so long as they are in order.  For example, here is one result:
// **Co**ntrols the **l**ocation of the sidebar. It can either show on the left **or** right of the workbench.

Highlighted colors from the result are shown in bold above.

**Comment by sandy081** [comment] 2017-01-20 07:46
Duplicate of #16700

**Closed by sandy081** 2017-01-20 07:46 UTC
Labels: duplicate
