### ISSUE TITLE
Disabling Smooth Scrolling doesn't work for the Extensions Information viewport

### ISSUE THREAD

**Issue by charbelnicolas** [microsoft/vscode#125423] opened 2021-06-03 18:05 UTC
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.56.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Open VS Code
2. Open the Extensions panel (Ctrl + Shift + X)
3. Click on any extension available
4. Go to the extension "Details" or "Changelog" tab and scroll
5. Smooth scrolling is still present even though it has been disabled in settings.

Expected behavior:

The extension information viewport should obey the editor smooth scrolling setting. 

This is the extension information viewport I'm referring to:

![20210603_122950](https://user-images.githubusercontent.com/14960414/120721884-5a0df480-c494-11eb-9c67-1fc036dcfce6.png)

**Comment by sandy081** [comment] 2021-06-04 09:57
@mjbvz Is this related to web views?

**Comment by mjbvz** [comment] 2021-06-10 03:38
Possibly caused by our switch to iframe based webviews instead of electron webviews

@deepak1556 Let me know if  you know of any ways  to disable smooth scrolling inside an iframe

**Comment by deepak1556** [comment] 2021-09-28 01:07
Sorry @mjbvz missed your comment on this one, it is not possible to disable smooth scrolling for a frame but can be done for a page. This requires new api from Electron that allows setting the following [preference](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/common/web_preferences/web_preferences.h;l=126)

If the user likes to disable smooth scrolling for entire application then they can launch with `--disable-smooth-scrolling`

**Comment by charbelnicolas** [comment] 2021-09-28 01:42
> If the user likes to disable smooth scrolling for entire application then they can launch with `--disable-smooth-scrolling`

I just tried launching VS Code with the --disable-smooth-scrolling and it didn't do anything, so I guess smooth scrolling is here to stay! (Unfortunately...)

**Comment by deepak1556** [comment] 2021-09-28 04:10
The flag only controls animation for user input scrolling, if the application is performing its own programmatic scrolling then the flag has no effect.

@mjbvz I do see that we handle the scroll for webview 
<img width="551" alt="Screen Shot 2021-09-28 at 13 06 33" src="https://user-images.githubusercontent.com/964386/135021851-4d1ddce6-6729-4d07-b147-17f680b0f346.png">
is there a control for scroll animations there ?

**Comment by charbelnicolas** [comment] 2021-09-28 04:53
--disable-smooth-scrolling works, sorry for saying it didn't earlier, it was my mistake, thank you.

**Comment by mjbvz** [comment] 2021-10-04 21:12
Ok, I'm going to close this since from the comments it seems like this is working as expected using the `--disable-smooth-scrolling` flag

**Closed by mjbvz** 2021-10-04 21:12 UTC
Labels: feature-request, webview, electron
