### ISSUE TITLE
No GH auth after update/restart

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#105950] opened 2020-09-02 14:43 UTC
Issue Type: <b>Bug</b>

I restarted my insiders for update. Afterwards I had lost my GH signing:

![image](https://user-images.githubusercontent.com/4674940/91998159-bec2d580-ecef-11ea-9ee2-e90e53bdbc21.png)

I had the following entries in the GH Auth log. These errors keep coming until I reload the window. After window reload everything is back to normal.

[Error  - 14:34:47.25] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:35:17.28] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:35:47.40] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:36:17.51] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:36:47.62] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:37:17.74] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:37:47.85] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:38:17.101] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:38:47.112] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:39:17.124] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:39:47.138] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:40:17.152] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:40:47.166] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:41:17.175] Getting token failed: Error: UNIX[No such file or directory]
[Error  - 14:41:47.187] Getting token failed: Error: UNIX[No such file or directory]

VS Code version: Code - Insiders 1.49.0-insider (00754e4babebc9ee5aa881234bc16366c4f32aa9, 2020-09-02T05:43:25.834Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.33GB free)|
|Process Argv|--crash-reporter-id d4b72415-0109-45b3-a1a7-967fdd12f0f4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.61GB (2.28GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.3.0
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.5.0
remote-containers|ms-|0.138.0
remote-ssh-edit-nightly|ms-|2020.8.19620
remote-ssh-nightly|ms-|2020.8.19620
remote-wsl|ms-|0.44.5
azure-account|ms-|0.9.2
vscode-github-issue-notebooks|ms-|0.0.49
vsonline|ms-|1.0.2739
material-icon-theme|PKi|4.2.0
vscode-ruby|win|0.27.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-pull-request-github-insiders|Git|2020.8.39781
rainbow-csv|mec|1.7.1
hexeditor|ms-|1.2.1
vscode-github-issue-notebooks|ms-|0.0.49
vscode-markdown-notebook|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.2.3

(3 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment] 2020-09-02 16:49
Upstream: https://github.com/atom/node-keytar/issues/147

**Comment by RMacfarlane** [comment] 2021-05-13 16:32
Closing as a duplicate of https://github.com/microsoft/vscode/issues/115525

**Closed by RMacfarlane** 2021-05-13 16:32 UTC
Labels: authentication, bug, upstream
