### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by skumar1996** [microsoft/vscode#139119] opened 2021-12-14 18:14 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1. Open VScode
2. Error pops up "The TypeScript language service died 5 times right after it got started. The service will not be started. Source: Typescript and Javascript Features (Extension).

**TS Server Log**
`c:\Users\Sagar\AppData\Roaming\Code\logs\20211214T191134\exthost1\vscode.typescript-language-features\tsserver-log-phSStK\tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:57011:22)
    at getPropertyOfType (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:57671:24)
    at resolveESModuleSymbol (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49817:54)
    at getTargetOfNamespaceImport (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49236:28)
    at resolveAlias (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49281:30)
    at getSymbol (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47838:38)
    at resolveNameHelper (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:48131:34)
    at resolveName (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:48114:20)
    at resolveEntityName (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49453:42)
    at resolveEntityName (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49461:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49413:24)
    at getTargetOfImportEqualsDeclaration (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:48865:28)
    at getTargetOfAliasDeclaration (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49232:28)
    at resolveAlias (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:49271:67)
    at mergeSymbol (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47624:42)
    at c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47737:20)
    at mergeSymbol (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47648:21)
    at c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47737:20)
    at mergeModuleAugmentation (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47753:17)
    at initializeTypeChecker (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:85046:25)
    at Object.createTypeChecker (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:47395:9)
    at Object.getTypeChecker (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:114404:79)
    at synchronizeHostData (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:159898:21)
    at Object.getProgram (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:168762:44)
    at c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:169102:97
    at Object.flatMap (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:170260:46)
    at c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:172184:28)
    at IOSession.Session.executeCommand (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:172193:33)
    at IOSession.Session.onMessage (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:172219:35)
    at Interface.<anonymous> (c:\Zenjob\company_web_app\node_modules\typescript\lib\tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (11.13GB free)|
|Process Argv|--crash-reporter-id 1dd54252-04eb-49d0-a3c3-878770ff98bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.0
vscode-intelephense-client|bme|1.8.0
bracket-pair-colorizer-2|Coe|0.2.2
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
fortranbreaker|eki|0.0.4
vscode-great-icons|emm|2.1.79
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.34.1
terraform|has|2.17.0
vscode-styled-components|jpo|1.7.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
remote-containers|ms-|0.209.6
cpptools|ms-|1.7.1
vscode-typescript-next|ms-|4.6.20211213
vscode-yaml|red|1.2.2
autoimport|ste|1.5.4
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
javagetstartedt:30391933
vsaa593cf:30376535
vsena315:30406435
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-12-14 18:47
/assign @mjbvz 

Looks like a duplicate of #138794 but in this one the TS version reports 4.5.4 and the VS Code is 1.63.1, which I was expecting to have fixed that.

**Comment by skumar1996** [comment] 2021-12-14 18:48
Thanks for looking into it guys!

**Comment by fobin** [comment] 2021-12-15 21:01
I had same issue with TS version 4.5.4 and VS Code 1.63.1.

**Comment by skumar1996** [comment] 2021-12-16 23:07
@fobin were you able to fix it?

**Comment by fobin** [comment] 2021-12-17 04:11
@skumar1996 No. I downgraded to 1.62 and it works with that.

**Comment by IllusionMH** [comment] 2021-12-21 09:19
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

TS teams need a way to reproduce this issue. Please provide code that can help to reproduce this crash in issue linked above.

**Closed** 2021-12-21 09:19 UTC
Labels: *duplicate

**Comment by fobin** [comment] 2021-12-21 09:22
I think it's actually fixed in this pull request: https://github.com/microsoft/TypeScript/pull/47183
