### ISSUE TITLE
Multiple directory trees in the EXPLORER

### ISSUE THREAD

**Issue by akinuri** [microsoft/vscode#100380] opened 2020-06-17 11:38 UTC
When working on a project (that uses a framework), I usually go up and down in the directory tree a lot. This, after some time, becomes tedious and inefficient. It would be better to have multiple directory trees in the Explorer.

Currently, I see four sections in the `Explorer`: `Open Editors`, Directory Tree, `Outline`, and `Timeline`. There's only one directory tree. Why not multiple?

I usually have 100+ lines (dirs, files) in the directory tree. I'd like to be able to create multiple directory trees using a directory that's in the main directory.

For example, an example (CodeIgniter) project:

```
project/
    application/
        controllers/
        models/
        views/
    assets/
    system/
    uploads/
```
While the main directory tree shows the whole `project`, I could create a second directory tree for, say, `project/application/controllers`. A third one for `project/assets`, and so on. Having a tree/window that just monitors a specific directory would help a lot.

**Comment by gjsjohnmurray** [comment] 2020-06-17 12:11
Are you aware of [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces)?

**Comment by akinuri** [comment] 2020-06-17 14:21
Nope, I was not. I did take a quick look, and it doesn't really meet my expectations. It's useful for adding another (sub or external) folder to the _same_ directory tree (just realized that the section's name is `Folders`). In other words, the directory that I added will still be affected by the open/close actions on the above directories (in the `Workspace`). I still have to scroll up and down (or toggle directories).

It would be better to create a new `Folders` section that I can keep open/visible. This way, I can scroll up and down in the main `Folders` while the second `Folders` still appear visible/unaffected by the changes (toggles) in the main tree.

I know I might be nitpicking here, but I know how much this tires me. So I just wanted to share my thoughts, and if it's sensible, see it implemented :)

**Comment by gjsjohnmurray** [comment] 2020-06-17 14:59
I also find [this extension](https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-favorites) a useful and lightweight way of giving myself shortcuts to subfolders within the `Folders` tree.

1. Install extension.
2. Right-click on subfolder and choose `Add to Favorites`.
3. Repeat for other subfolders.

To jump:
1. Expand `FAVORITES` panel.
2. Right-click on the entry you want, then choose `Reveal in Side Bar`.

**Comment by akinuri** [comment] 2020-06-17 15:50
Yea, that helps. I searched for similar extensions, and it seems "Favorites" is a thing. I saw a several of them (tested few) and they might get the job done. Although some lack vital features, and one has an issue when removing from favorites (removes all). Might open issues in their repositories.

Knowing that this can be _fixed_ via extensions is somewhat acceptable. So, in light of that, would expecting a (general) solution from VS Code, eventually, be sensible?

Whatever the case, eventually, I might need to look into the Extension API, myself :)

**Comment by isidorn** [comment] 2020-06-22 08:00
Closing as duplicate of working sets and other File-Explorer feature requests which you can find in our repository.

**Closed** 2020-06-22 08:00 UTC
Labels: *duplicate

**Comment by akinuri** [comment] 2020-06-22 09:34
I searched for [(open) issues with the file-explorer label](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Afile-explorer+is%3Aopen+). There are 105 of them. Checked all the titles (twice), and the content of some of them (the ones with a relative/descriptive title to mine). Could not find a duplicate. The closest I could find was about using seperators between workspace folders (to improve the management).

Also, I took a quick look at the [closed issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Afile-explorer+label%3Afeature-request+is%3Aclosed+), but there are many (584). Checked the titles in the first few pages. Again, nothing.

I'd like to keep track of the progress on this, so I think the duplicate/original issue should be mentioned.
