### ISSUE TITLE
Java try-catch color display problem

### ISSUE THREAD

**Issue by Power-tile** [microsoft/vscode#85258] opened 2019-11-21 01:30 UTC
Issue Type: <b>Bug</b>

In the try-catch argument in Java, when I use the operator | to catch for different exception types, the color gets weird when a new line is inserted in the middle of the exception sequences.

try {
    process();
} catch (Exception1 | Exception2 | Exception3
             | Exception4 | Exception5) { // this is where it gets weird - the catch became yellow and only two of the Exception classes became green
    // handle the exception
}

![图片](https://user-images.githubusercontent.com/44731563/69292604-8a3ecb00-0c41-11ea-83ce-e92e3e729e15.png)
// a screenshot of this problem

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.63GB free)|
|Process Argv|C:\Users\Power_tile\Desktop\COMP2001 Programs\20191120\null-undefined.js|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|8.0.3
pascal-formatter|ale|2.2.0
xml|Dot|2.5.0
matlab|Gim|1.4.0
remote-wsl|ms-|0.40.3
cpptools|ms-|0.26.1
powershell|ms-|2019.11.0
team|ms-|1.161.0
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.1
java|red|0.53.1
vscodeintellicode|Vis|1.2.0
vscode-arduino|vsc|0.2.28
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1

</details>

**Comment by gjsjohnmurray** [comment] 2019-11-21 04:45
Please report this on the repo of the java extension that you are using.

**Comment by alexr00** [comment] 2019-11-22 08:44
Duplicate of https://github.com/atom/language-java/issues/205

**Closed by alexr00** 2019-11-22 08:44 UTC
