### ISSUE TITLE
Cannot push to git repository

### ISSUE THREAD

**Issue by BjornS96** [microsoft/vscode#144431] opened 2022-03-04 18:38 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: February 2022 (version 1.65)
- OS Version: Windows 10

Steps to Reproduce:

1. Save code
2. Click on commit
3. Type in message and press enter
4. Sync Changes
5. Error: fatal: 'o' does not appear to be a git repository

**Comment by xmatthias** [comment] 2022-03-06 13:48
I encounter the same - this seems to have been introduced in 1.65.0 - as it used to work perfectly fine before this update.

**Comment by maartenvantjonger** [comment] 2022-03-09 21:14
Same here with vscode version 1.65.1 on Windows 11.

Pulling through the UI causes the same error message and shows this in the Git log:
```
git pull --tags o igin/181258720_dashboard_query_performance [50ms]
fatal: 'o' does not appear to be a git repository
```

Meanwhile, a `git pull` in the terminal works fine and `git remote` returns `origin`.

**Comment by lszomoru** [comment] 2022-03-10 16:08
Sorry about that. This was [a regression](https://github.com/microsoft/vscode/issues/144205) that was indeed introduced in `1.65`.
The issue has already been fixed in Insiders, and will be part of the next recovery release.

**Comment by lszomoru** [comment] 2022-03-10 16:08
Closing as duplicate of https://github.com/microsoft/vscode/issues/144205.

**Closed by lszomoru** 2022-03-10 16:08 UTC
Labels: bug, git
