### ISSUE TITLE
Global wordWrap setting ignored by markdown

### ISSUE THREAD

**Issue by dcarapic** [microsoft/vscode#76401] opened 2019-07-01 11:16 UTC
Issue Type: <b>Bug</b>

The markdown files (*.md) disregard the global editor.wordWrap and editor.wordWrapColumn. If I manually add the same settings to the [markdown] file type then they are respected.

This does not work:
```
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 180
```

This works:
```
    "[markdown]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 180,
        "editor.quickSuggestions": false
    },
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 180
```

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.27GB free)|
|Process Argv|C:\Dload\M7 67.md|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
vscode-firefox-debug|hbe|1.8.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
docomment|k--|0.1.8
csharp|ms-|1.20.0
vsliveshare|ms-|1.0.471
debugger-for-chrome|msj|4.11.6
indent-rainbow|ode|7.4.0
code-spell-checker|str|1.7.17
vscode-icons|vsc|8.8.0

</details>

**Comment by dcarapic** [comment] 2019-07-01 11:17
Here is my full global settings.json (there are no local settings), I was simply editing a standalone .md file:

```
{
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "materialTheme.fixIconsRunning": false,
    "window.zoomLevel": 1,
    "gitlens.codeLens.enabled": false,
    "gitlens.currentLine.enabled": false,
    "gitlens.hovers.currentLine.over": "line",
    "git.enableSmartCommit": true,
    "workbench.tree.indent": 18,
    "explorer.confirmDelete": false,
    "editor.codeLens": false,
    "csharp.referencesCodeLens.enabled": false,
    "gitlens.defaultDateFormat": "DD.MM.YYYY HH:mm",
    "gitlens.defaultDateShortFormat": "DD.MM.YYYY",
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "prettier.jsxBracketSameLine": true,
    "prettier.printWidth": 120,
    "prettier.tabWidth": 4,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "editor.tabCompletion": "on",
    "editor.snippetSuggestions": "bottom",
    "workbench.iconTheme": "vscode-icons",
    "breadcrumbs.enabled": true,
    "explorer.confirmDragAndDrop": false,
    "debug.console.fontSize": 12,
    "workbench.list.horizontalScrolling": true,
    "[markdown]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 180,
        "editor.quickSuggestions": false
    },
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 180
}
```

**Comment by mjbvz** [comment] 2019-07-11 01:12
This feature is working as expected. Markdown provides default setting `editor.wordWrap` settings as a language specific setting, so you have to use `"[markdown]": { ... }` to override it

Adding @roblourens to see if we can improve  settings UI in some way to make this more clear

**Comment by roblourens** [comment] 2019-07-11 01:13
Got to improve this as well https://github.com/microsoft/vscode/issues/74195

**Comment by mjbvz** [comment] 2019-07-11 01:19
Thanks. Closing as duplicate of that issue then

**Closed by mjbvz** 2019-07-11 01:19 UTC
Labels: editor-wrapping
