### ISSUE TITLE
Raw HTML visible on Menu Items with custom title bar when using Keyboard shortcut

### ISSUE THREAD

**Issue by st0le** [Microsoft/vscode#58231] opened 2018-09-07 23:47 UTC
- VSCode Version: 
Version: 1.28.0-insider (user setup)
Commit: a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4
Date: 2018-09-07T05:20:29.346Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:

Steps to Reproduce:

1. Use your mouse to highlight any Menu Bar ( [See here](https://i.imgur.com/tYyhFpk.png) ) For instance File Menu
2. Try to use Alt+F, HTML tags seen on Menu items [see here](https://i.imgur.com/eaQ1YMh.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2018-09-07 23:49
Duplicate of #58156

**Closed by mjbvz** 2018-09-07 23:49 UTC
