### ISSUE TITLE
Extensions viewlet gets cleared on workspace folder add

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35133] opened 2017-09-26 14:42 UTC
1. Open extensions viewlet -> notice installed extensions shown and recommendations
2. Explorer -> add new workspace folder
3. Back to extensions viewlet -> it is completely emtpy

Once I search for something and cancel the search the extensions viewlet gets healthy

**Comment by sandy081** [comment] 2017-09-27 12:27
Duplicate of #35189

**Closed by sandy081** 2017-09-27 12:27 UTC
Labels: bug, extensions, multi-root

**Comment by isidorn** [comment] 2017-09-27 13:06
@sandy081 my issue is older 😭

**Comment by sandy081** [comment] 2017-09-27 13:36
Yeah...I noticed it after attaching the fix to the newer one. :(
