### ISSUE TITLE
Test as file name - tasks.json build with g++ gives errors

### ISSUE THREAD

**Issue by loopholer** [Microsoft/vscode#52723] opened 2018-06-23 11:03 UTC
- VSCode Version:1.24.1
- OS Version:windows 10 pro version 1803 osbuild 17134.112

Steps to Reproduce:

1. Pre-requisites: add MinGW
2. Add c++ tools extension to vscode
3. Create a file Test.cpp
#include <iostream>

int main(){
std::out << "Hello world!";
return 0;
}

add c_cpp_properties.json with path to library
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:MinGW/bin/gcc.exe",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}

add tasks.json

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build Test",
            "type": "shell",
            "command": "echo Hello; g++ -g Test.cpp",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

Does this issue occur when all extensions are disabled?: No

Errors to build and never works, complains about path or g++ not found.

**Comment by dbaeumer** [comment] 2018-06-25 07:19
@TomSputz thanks for your help here. I will mark as needs more info. I agree that without a reproducible test case there is little we can do.

**Comment by loopholer** [comment] 2018-06-25 11:09
Hey guys

I'd love to help more - I will send some more info with regards to this to
be reproducible.

kind regards

AP

**Comment by alexr00** [comment] 2019-01-04 10:48
Closing since this has had the needs more info tag for six months.

**Closed by alexr00** 2019-01-04 10:48 UTC
Labels: needs more info, tasks
