### ISSUE TITLE
JS/TS Language Service Crashed

### ISSUE THREAD

**Issue by laurenhamel** [microsoft/vscode#213484] opened 2024-05-25 20:49 UTC
Type: <b>Bug</b>

This is happening when opening VS Code as well as restarting/reloading the extension host.

![image](https://github.com/microsoft/vscode/assets/24446243/cff44fad-8b54-4698-b576-23df40af4367)

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|141, 94, 77|
|Memory (System)|8.00GB (1.02GB free)|
|Process Argv|--crash-reporter-id fdbae21d-12d9-41ef-8e4e-169fd9aa597e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
solis|caz|1.1.0
project-manager|ale|12.8.0
vscode-apollo|apo|1.20.0
vscode-zipfs|arc|3.0.0
color-info|bie|0.7.2
markdown-mermaid|bie|1.23.0
vscode-intelephense-client|bme|1.10.4
vscode-toggle-quotes|Bri|0.3.6
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
indent4to2|Com|0.1.2
vscode-eslint|dba|2.4.4
vscode-dash|dee|2.4.0
vscode-notes|dio|1.2.1
doppler-vscode|dop|0.0.5
xml|Dot|2.5.1
gitlens|eam|15.0.4
vscode-html-css|ecm|2.0.9
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
vscode-projects-plus|fab|1.24.0
figma-vscode-extension|fig|0.3.5
file-icons|fil|1.1.0
vscode-jest-runner|fir|0.4.73
shell-format|fox|7.2.5
openssl-configuration-file|gee|0.0.1
vscode-github-actions|git|0.26.2
vscode-graphql|Gra|0.9.3
vscode-graphql-syntax|Gra|1.3.6
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
output-colorizer|IBM|0.1.2
error-gutters|Igo|1.0.1
fontawesome-autocomplete|Jan|1.3.1
batch-rename-extension|Jan|0.0.6
svg|joc|1.5.3
vscode-colorize|kam|0.11.1
vscode-gutter-preview|kis|0.31.2
chmod-command|lab|0.0.1
regionfolder|map|1.0.22
code-coverage|mar|1.12.0
template-string-converter|meg|0.6.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
remote-containers|ms-|0.362.0
atom-keybindings|ms-|3.3.0
brackets-keybindings|ms-|0.1.1
live-server|ms-|0.4.13
vscode-typescript-next|ms-|5.5.20240505
vsliveshare|ms-|1.0.5918
vscode-react-native|msj|1.13.0
color-highlight|nau|2.8.0
vscode-drawio-plugin-mermaid|nop|0.1.5
indent-rainbow|ode|8.3.1
vscode-jest|Ort|6.2.5
java|red|1.30.0
vscode-coverage-gutters|rya|2.11.1
vscode-spotify|shy|3.2.1
velocity|sod|0.3.0
some-sass|Som|3.1.4
vscode-open-in-gitfork|spa|1.0.3
vscode-taskexplorer|spm|2.13.2
vscode-stylelint|sty|1.4.0
sass-indented|syl|1.8.29
open-in-browser|tec|2.0.0
vscode-mermaid-editor|tom|0.19.1
lorem-ipsum|Tyr|1.3.1
sort-lines|Tyr|1.11.0
tab-groups|usa|2.1.1
explorer|vit|0.10.7
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
todoist|way|0.5.0
twig|wha|1.0.2
pretty-ts-errors|Yoa|0.5.4
markdown-all-in-one|yzh|3.6.2
json|Zai|2.0.2
file-size|zh9|1.0.0
swig-tpl|zha|0.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvptcf:31049071
a69g1124:31058053
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by dumorando** [comment] 2024-05-26 04:45
same here

**Comment by laurenhamel** [comment] 2024-05-27 18:17
Adding some additional context here and a quick fix for anyone in the meantime needing to recover TS language support. I was running `yarn@4.2.2` with `typescript@5.4.5` in PnP mode plus `.yarn/sdks/typescript` installed, which seems to be incompatible with the lates VS Code version. Downgrading back to `nodeLinker: node-modules` in my `.yarnrc.yml` resolves this issue in the meantime.

**Comment by toast-ts** [comment] 2024-05-28 01:01
It seems that `typescript.tsserver.experimental.useVsCodeWatcher` was enabled by default somehow which is causing the Language Server to continuously crash, setting it to false worked.

Source: https://github.com/yarnpkg/berry/issues/6270#issuecomment-2096753753

**Comment by mjbvz** [comment] 2024-06-17 20:37
Closing as caused by yarn. See upstream issue for details: https://github.com/yarnpkg/berry/issues/6270

**Closed by mjbvz** 2024-06-17 20:37 UTC
Labels: upstream-issue-linked
