### ISSUE TITLE
Time zone error

### ISSUE THREAD

**Issue by xiaopangzia** [microsoft/vscode#108721] opened 2020-10-15 08:45 UTC
版本: 1.51.0-insider (user setup)
提交: a522f37e37735c0cbe7244680250ef73d9054dd1
日期: 2020-10-15T06:39:34.462Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20236
![image](https://user-images.githubusercontent.com/29044591/96099341-b3c1ae80-0f05-11eb-8f8e-6a4a8f6aa841.png)

**Comment by fbricon** [comment] 2020-10-15 14:16
Insider build happened at 06:39GMT, which is 14:39 CST, so about 2h before the OP's screenshot. Seems legit.

**Comment by xiaopangzia** [comment] 2020-10-16 01:14
> Insider build happened at 06:39GMT, which is 14:39 CST, so about 2h before the OP's screenshot. Seems legit.

There is no problem with the time, but it seems that there is no overtime area, resulting in display errors

**Comment by chrmarti** [comment] 2020-10-16 07:05
The timestamp is in UTC using the ISO 8601 format: https://en.wikipedia.org/wiki/ISO_8601. The thought behind using that format is that it is easier to determine if two builds are the same when their timestamps use the same format independent of the user's timezone. Closing as this is by design.

**Closed by chrmarti** 2020-10-16 07:05 UTC
