### ISSUE TITLE
intergrated terminal bug , can't input chinese. 

### ISSUE THREAD

**Issue by macaddr** [Microsoft/vscode#9438] opened 2016-07-18 13:24 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.open vscod any dir ,named with english.
2.ctrl+~ ,open intergated terminal (cmd).
3.try to input chinese

**Comment by Tyriar** [comment] 2016-07-18 16:49
Duplicate of #7045

**Closed by Tyriar** 2016-07-18 16:49 UTC
Labels: integrated-terminal
