### ISSUE TITLE
Mac accessibility: extraneous speech and sound while typing

### ISSUE THREAD

**Issue by pitermach** [microsoft/vscode#131866] opened 2021-08-29 17:36 UTC
Issue Type: <b>Bug</b>

1. Turn on VoiceOver (command-F5)
2. Make a new file in VSCode.
3. Start typing

Expected: Depending on your keyboard echo settings you may either hear every letter and word as you type or nothing at all.

Actual: Every time you type or backspace a character, voiceOver plays the sound indicating that a menu opened. More annoyingly, it also repeats the label and contents of the editor. This behavior may get masked with the character echo, but if you change it to words or nothing (can be done quickly by pressing ctrl-option-V or from the VoiceOver utility) it becomes very apparent.

Some more notes I observed:

- This seems to happen in almost every text field, including any editor or even the issue reporter's title and steps to reproduce fields.
- The issue only seems to happen if you're editing at the very end of the file. Typing on any other line appears to work normally.
- I'm experiencing this on Monterey Public Beta 5, but also managed to reproduce it on Big Sur. I first became aware of this after a friend told me he was having issues also on the beta. However, before I started testing this I hadn't ran code in a long time and before it updated to the latest insider version, it seemed to behave normally. 
- Trying out previous versions, the latest 1.60 is affected, as well as the current stable (1.59.1). Going back to the June update (1.58) the issue isn't present, so it was probably introduced in 1.59.

VS Code version: Code - Insiders 1.60.0-insider (8dbad73de575e47e127c8b1a4324f2b61257fbdc, 2021-08-27T21:35:45.901Z)
OS version: Darwin arm64 21.0.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 3|
|Memory (System)|16.00GB (0.92GB free)|
|Process Argv|--crash-reporter-id 1ae7a807-017d-4644-b8ae-55d2a0e3e805|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
love|bsc|0.3.6
lua|sum|2.3.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824:30353183
javagetstartedt:30350119
pythonvspyt187:30356034
pydsgsc2:30356658

```

</details>

**Comment by pitermach** [comment] 2021-09-01 17:12
Update: I just asked someone to check if this happens on Big Sur, and it does. So this is definitely not a Monterey specific bug.

**Comment by isidorn** [comment] 2022-01-20 13:59
@pitermach I apologise for the slow response on this issue, this somehow fell through the cracks.
This is great feedback that we really value, however this feels like a duplicate of https://github.com/microsoft/vscode/issues/140220

I have commented there with the latest since we are acutally right now investigating this issue with our friends from VoiceOver.

Since that issue already has the discussion going I suggest you also chime in there and I will close this issue as a duplicate. If you believe this is not a duplicate please let me know and I will reopen this one.

I am also really interested in other potential issues that you hit with VS Code + VoiceOver. Please let us know! Thanks

**Closed by isidorn** 2022-01-20 13:59 UTC
Labels: accessibility
