### ISSUE TITLE
My vs code  keeps on restarting extensions 

### ISSUE THREAD

**Issue by Clifftech123** [microsoft/vscode#176611] opened 2023-03-09 07:58 UTC
Type: <b>Bug</b>

Since yesterday my vs code extensions  have been restarting .it seems every 6 minutes it restarts 
My vs code  keeps on restarting extensions 

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.43GB (1.74GB free)|
|Process Argv|--crash-reporter-id c362a714-6c5b-4421-94fc-27441794844d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|3.0.2
codesnap|adp|1.3.4
tailwind-docs|aus|2.0.0
vscode-tailwindcss|bra|0.9.7
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
bracket-pair-toggler|dzh|0.0.3
gitlens|eam|13.3.2
vscode-html-css|ecm|1.13.1
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.10.4
mithril-emmet|Fal|0.7.7
code-runner|for|0.12.0
copilot|Git|1.77.9225
live-sass|gle|6.0.3
vscode-graphql|Gra|0.8.6
vscode-graphql-execution|Gra|0.1.8
vscode-graphql-syntax|Gra|1.1.0
todo-tree|Gru|0.0.224
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
pubspec-assist|jer|2.3.2
vscode-gutter-preview|kis|0.30.0
ts-error-translator|mat|0.8.0
vscode-language-babel|mgm|0.0.37
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.2.0
graphql|mqu|0.1.2
vscode-docker|ms-|1.24.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.20
powershell|ms-|2023.2.1
vscode-typescript-next|ms-|5.1.20230308
explorer-exclude|Pet|1.3.2
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.24.0
vscode-thunder-client|ran|2.5.0
vscode-yaml|red|1.12.1
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
es7-react-js-snippets|rod|1.9.3
markdown-preview-enhanced|shd|0.6.8
js-jsx-snippets|sky|11.0.1
code-spell-checker|str|2.19.0
sass-indented|syl|1.8.26
ayu|tea|1.0.5
errorlens|use|3.7.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
material-ui-snippets|vsc|3.3.8
console-ninja|Wal|0.0.81
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.6

(22 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
vsccsb:30677849
pythonb192:30669360
funwalk2:30676043

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-09 09:12
Please use the `Start Extension Bisect` to try and discover which of your extensions is causing this.

**Comment by isidorn** [comment] 2023-03-15 11:24
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:24 UTC
Labels: info-needed, freeze-slow-crash-leak, extension-host
