### ISSUE TITLE
"Compare Selected" doesn't work if the new title bar style is enabled

### ISSUE THREAD

**Issue by awesomegithubusername** [Microsoft/vscode#56464] opened 2018-08-15 11:08 UTC
Issue Type: <b>Bug</b>

1-User Settings
      {
        "window.titleBarStyle": "custom"
      }
2-Select 2 files.
3-"Compare Selected".
4-Expected behavior : the files are compared with each other.
5-Actual result : nothing happens.
6-If the setting is removed, the comparison works.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

**Comment by sbatten** [comment] 2018-08-15 15:14
duplicate of #56225

**Closed by sbatten** 2018-08-15 15:14 UTC
Labels: new release
