### ISSUE TITLE
How to enable breadcrumbs only for custom editor

### ISSUE THREAD

**Issue by sathya-1994** [microsoft/vscode#146098] opened 2022-03-26 08:22 UTC
We can enable/disable file location bar(Breadcrumbs) in vscode using settings(setting >breadcrumbs).
![image](https://user-images.githubusercontent.com/59145404/160231077-f963e1ea-9557-457d-b3a0-e001ac23034a.png)

**Screenshot:**
![image](https://user-images.githubusercontent.com/59145404/160231025-4320b714-8ff5-45bb-83a7-6f2bb39aea0b.png)

Requirement:
**"breadcrumbs.enabled": false** option will enable/disable Breadcrumbs for all editors. I want to disable Breadcrumbs for my custom editor but I need Breadcrumbs for other editors. 

Is this feature is available in vscode(configure breadcrumbs, font etc  specific to custom editors) ? If yes, where we can configure it?

**Comment by mjbvz** [comment] 2022-03-28 20:16
Duplicate of #146067

**Closed by mjbvz** 2022-03-28 20:16 UTC

**Comment by sathya-1994** [comment] 2022-03-29 10:26
@mjbvz ,

Even though [#146067](https://github.com/microsoft/vscode/issues/146067) is not a bug, we have to fix it. We are using custom editors to show diagram but breadcrumbs acts like window's system explorer and we can open any file in a custom editor and diagrams will be lost.

Font size, font type etc we configure at global level(common for all editors) but we will have many use cases where we have to configure each custom editors based on requirement.

So, vscode show allow us to contribute these fileds in package.json(inside custom editor's contribution).
