### ISSUE TITLE
Set word wrapping as default

### ISSUE THREAD

**Issue by jcade** [microsoft/vscode#126395] opened 2021-06-15 15:37 UTC
Due to some lines of code being longer than the window, especially when you paste code in to edit, I would like to see that "word wrap" be set as a default to make the code readable.  I am still fairly new to VSCode so digging in the menu to try to find it was a pain.  

Last night was a good example, I needed to edit something real quick that I copied out of an email program and did not have the time to dig to turn on Word Wrap so I had got back to Dreamweaver to do my edits.

**Comment by carlocardella** [comment] 2021-06-15 15:43
Can you try to enable Word Wrap in Settings?

![image](https://user-images.githubusercontent.com/5784415/122083440-bd155a80-cdb5-11eb-81dc-931a6cd3f86e.png)

**Comment by IllusionMH** [comment] 2021-06-15 15:46
Have you tried to open Settings editor and search for `Word wrap` in search field?
It is already possible to configure in settings editor and also toggle on the fly with `>View: Toggle Word Wrap` command.

No need to make it default - just check existing settings.

**Comment by jcade** [comment] 2021-06-15 18:02
I did and it works. My goal is to have it open as default. I had it set but
went away, it had been a little bit since I used it last. Maybe an update
reset it to off??

Thanks for your help.

Jeff

**Comment by carlocardella** [comment] 2021-06-15 18:05
There are reports of setting files getting erased, maybe that's what happened to you? 
https://github.com/microsoft/vscode/issues/125970

**Comment by jcade** [comment] 2021-06-15 18:39
That is a good possibility, I have not used it enough to say yes or no
unfortunately.

-Jeff

**Comment by jcade** [comment] 2021-06-15 18:41
> Have you tried to open Settings editor and search for `Word wrap` in search field?
> It is already possible to configure in settings editor and also toggle on the fly with `>View: Toggle Word Wrap` command.
> 
> No need to make it default - just check existing settings.

Yes, that works, just didn't stick the last time.

**Comment by sandy081** [comment] 2021-06-16 14:13
/duplicate

Seems duplicate of #125970

@jcade Please open the settings file and see what settings you have there.

**Closed** 2021-06-16 14:14 UTC
Labels: *duplicate
