### ISSUE TITLE
Inline Chat Widget: Prompt box Submit `More...` action flickers when pressed

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208569] opened 2024-03-25 08:40 UTC
Testing #208414

The `More...` action shows the submenu for a fraction of a second before disappearing again when clicked. The submenu correctly shows in panel chat.

![Code_-_Insiders_cetnhNy5ZP](https://github.com/microsoft/vscode/assets/44439583/1315bdb8-3884-4489-ae22-45e513c620fc)

**Comment by jrieken** [comment] 2024-03-25 09:11
We shouldn't have this drop down menu in inline chat

**Comment by jrieken** [comment] 2024-03-27 09:33
This is the problem: https://github.com/microsoft/vscode/blob/6f287b276e83fda5a6a66757ffa81511e98a7560/src/vs/workbench/contrib/inlineChat/browser/inlineChatZoneWidget.ts#L73-L77

**Comment by jrieken** [comment] 2024-03-27 09:33
caused by https://github.com/microsoft/vscode/pull/187736

**Comment by jrieken** [comment] 2024-03-27 17:29
Moving to April for more cleanup

**Closed** 2024-03-28 12:07 UTC
Labels: bug, verified, inline-chat
