### ISSUE TITLE
VSCode removes "Run with PowerShell" from Windows Explorer context menu

### ISSUE THREAD

**Issue by JustinWebDev** [microsoft/vscode#94582] opened 2020-04-07 02:24 UTC
- VSCode Version:  latest
- OS Version:  Win10 v1909

We need an open issue for this issue (the super vscodebot is super aggressive in closing issues before they are fixed).  And this issue really needs to be fixed!

ref:
https://github.com/microsoft/vscode/issues/64815
https://github.com/PowerShell/vscode-powershell/issues/692
https://github.com/Microsoft/vscode/issues/6387

The cmds for 'edit in ISE' and 'run with PS' are missing missing on the PS context menu.

**Comment by joaomoreno** [comment] 2020-04-07 05:36
Did you install the PowerShell extension?

**Comment by JustinWebDev** [comment] 2020-04-08 00:06
Yes, if you are talking about the MS extension
https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell

**Comment by joaomoreno** [comment] 2020-04-08 07:25
So, and what do you mean by clobbers? Can you show me a screenshot of the issue?

**Comment by JustinWebDev** [comment] 2020-04-08 23:13
Sorry, don't have a screenshot.  Besides, it wouldn't show what _used_ to be there!
For what I mean, see issue https://github.com/microsoft/vscode/issues/64815 noted in this issue.
Let me add that the cmd for 'edit in ISE' is also missing.

**Comment by joaomoreno** [comment] 2020-04-09 08:15
Does it add any actions? Or just removes that one?

**Comment by JustinWebDev** [comment] 2020-04-09 23:47
Not specifically for PS files.  You were involved with the previously filed issues.  I don't understand all the questions as if this is new to you.

**Comment by joaomoreno** [comment] 2020-04-14 15:59
It is because I cannot reproduce.

Please explain what you observe in your machine? What changed exactly in the menu?

**Comment by JustinWebDev** [comment] 2020-04-15 01:15
The two Windows out-of-the box cmds for PS1 files are gone:   'edit in ISE' and 'run with PS'
On one machines these cmds are never on the context menu.  On another machine sometimes they appear.

**Comment by hatclub** [comment] 2020-04-20 01:25
Can confirm this behaviour. However, so can this entire thread here dating back to windows 8; https://answers.microsoft.com/en-us/windows/forum/all/run-with-powershell-missing-from-explorer-context/f2280225-55ae-4e0c-9619-564c4b588489, and it doesn't require vscode to manifest itself I'm not really sure it's a VSCode issue but some sort of voodoo to do with the o/s default notepad association.

Essentially it seems that if the default/last editor is not Notepad, "Run with Powershell" goes missing from the context menu. If you've never looked in the context menu before you changed the default editor for powershell files, you wouldn't know, as you'd have never seen it.

I have recorded a screencast of this behaviour on a brand new 19H1 install of W10 - default behavior with notepad as editor, then changing association to wordpad, then to notepad, then install vscode, install PS plugin, open VSCode various different ways, prove "Run with powershell" still there until I change association to vscode, then finally back to notepad.
https://www.screencast.com/t/73uCaJxfkHfS

I don't even know if this is truly a bug rather than a win+notepad "feature" for ps1 files. I also have no idea who we'd send this to if it was - uservoice would be a total waste of time for this as it probably only affects a handful of users. 

Could vscode perhaps insert it's own "Run with powershell" context item when it's the default editor to replace the Notepad one?

**Comment by JustinWebDev** [comment] 2020-04-20 23:09
Great info, hatclub.  I noticed something else:  The file icon changes to the PS cmd icon (solid dark blue icon).  The default launch action (aka, double-click) changes to execution (same as "Run with Powershell"), I guess) instead of open in Notepad.  The "Edit" cmd (which mean 'edit in ISE') is removed.  There are several changes that take place, but I don't know what or when it exactly happens.

**Comment by hatclub** [comment] 2020-04-20 23:34
> The file icon changes to the PS cmd icon (solid dark blue icon). The default launch action (aka, double-click) changes to execution (same as "Run with Powershell"), I guess) instead of open in Notepad. 

It does? When? I didn't see that (did I?)

**Comment by JustinWebDev** [comment] 2020-04-20 23:45
To be clear, I didn't mean in the video you posted.  I was referring to my experience on my machine.  Maybe PS got associated with PS1s, and I just need to re-associate with Notepad?  I'll try it out tomorrow.

**Comment by nneul** [comment] 2020-05-08 14:20
I can confirm on my box, the instant I did an "Open with -> Notepad", the run with powershell options came back. Didn't have to do anything to set a permanent association or anything, just that one manual open was enough.

**Comment by nneul** [comment] 2020-05-08 14:21
And correspondingly, the moment I 'Open with Code' - the options go away.

**Comment by joaomoreno** [comment] 2020-05-18 08:38
This has been fixed in the latest Windows 10 update, according to https://github.com/microsoft/vscode/pull/97414#issuecomment-629693994

**Closed by joaomoreno** 2020-05-18 08:38 UTC
Labels: bug, help wanted, windows
