### ISSUE TITLE
Cannot rename javascript variable in html file

### ISSUE THREAD

**Issue by DRL9** [Microsoft/vscode#32081] opened 2017-08-07 07:00 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-css-formatter|aes|0.0.2
vscode-refresh-html|baj|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
python|don|0.7.0
vscode-npm-script|eg2|0.2.0
auto-rename-tag|for|0.0.14
matlab|Gim|0.5.0
search-node-modules|jas|1.1.1
vetur|oct|0.9.3
vuehelper|oys|0.1.0
es6-mocha-snippets|spo|0.0.2
nodejs-extension-pack|wad|0.1.9
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. Edit in html file
2. Input code in `<script>` as follow:
```js
var foo='a';
console.log(foo)
``` 
3. Select `foo`, and press `F2` to rename it, nothing happen.
4. right click mouse, there no rename option in menu. 

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-08-08 13:12
duplicate of #31141

The workaround is to use 'Change all occurrences'

**Closed by aeschli** 2017-08-08 13:12 UTC
Labels: html, javascript
