### ISSUE TITLE
Cannot install vsix from command line

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#62845] opened 2018-11-09 11:29 UTC
Issue Type: <b>Bug</b>

A regression from 1.28.2:
![image](https://user-images.githubusercontent.com/9205389/48260220-ec53d600-e41a-11e8-9093-9e0d3b83077f.png)

VS Code version: Code - Insiders 1.29.0-insider (9a2d095fd017e9ea129ca6e136e869e49290a4ba, 2018-11-08T17:48:13.168Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.98GB (3.14GB free)|
|Process Argv|--extensions-dir tmp\exts|
|Screen Reader|yes|
|VM|100%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-account|ms-|0.6.0

</details>

**Comment by sandy081** [comment] 2018-11-12 14:47
It is not a regression.. In the second case, there is a prompt for user which is not working in windows. If you have same extensions set up in stable, you would see the same.

Duplicate of https://github.com/Microsoft/vscode/issues/59481

**Closed by sandy081** 2018-11-12 14:47 UTC
Labels: extensions, insiders
