### ISSUE TITLE
Shell script syntax highlighting error

### ISSUE THREAD

**Issue by fmercier** [Microsoft/vscode#45609] opened 2018-03-12 18:11 UTC
Issue Type: <b>Bug</b>

1. Create a new file
2. Select Language shell script (Bash)
3. Enter the snippet

```
#!/bin/bash
CONT=`cat <<-END1 | wc -l
    line1
    line2
END1`
if [ $CONT -gt 1 ] ; then
 echo "the word echo must be highlighted in white and if /then in blue"
fi
```

Expected: 
The 3 last lines must be highlighted as a new statements
This issue has already be reported 6 month aggo as Issue #33034 but is still not corrected.
vi editor on Linux do highlight correctly!

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|15.88GB (4.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.13.0

</details>
Reproduces without extensions

**Comment by aeschli** [comment] 2018-03-13 07:53
duplicate of https://github.com/atom/language-shellscript/issues/109

**Closed by aeschli** 2018-03-13 07:53 UTC

**Comment by fmercier** [comment] 2018-03-13 16:48
A bit surprised to see this existing defect to be indicated as duplicate of atom/language-shellscript#109 which is closed and itself be a duplicate of atom/language-shellscript#86 (open) which is said as unfixable ! (Oct 27, 2017)

**Comment by aeschli** [comment] 2018-03-13 20:42
Do you disagree that it's a dup of atom/language-shellscript#109 ?

**Comment by fmercier** [comment] 2018-03-14 09:16
I do not disagree it's a duplicate of  atom/language-shellscript#109, but indicating it as a duplicate of a closed issue doesn't show in the root issue the importance of the resolution. This problem prevent using VSCode for professional shell script; it has been reported at least 7 month ago and no solution has been provided so far.

**Comment by aeschli** [comment] 2018-03-14 20:16
The shellscript grammar is maintained and developed by a different open source project ( atom/language-shellscript) . I don't know the details why this is hard or even impossible to fix, so please ask there.
