### ISSUE TITLE
Assign shortcut to commands from command panel

### ISSUE THREAD

**Issue by phdoerfler** [Microsoft/vscode#67053] opened 2019-01-24 12:00 UTC
I would like to be able to assign keyboard shortcuts directly from the command panel.
It already shows existing keyboard shortcuts were set. An icon at that place for commands without a set shortcut that would jump to the keyboard shortcuts configuration with the correct command selected would be neat.

![image](https://user-images.githubusercontent.com/163428/51676706-b8c72780-1fd7-11e9-8b0c-f7cc257009c8.png)

**Comment by chrmarti** [comment] 2019-01-27 14:17
We'd need a way to do this without making the UI 'noisy' for the common case of picking a command.

**Comment by bpasero** [comment] 2019-01-28 07:31
@sandy081 are we not having a duplicate of this issue somewhere?

**Comment by sandy081** [comment] 2019-01-28 13:36
Duplicate of #27716

**Closed** 2019-01-28 13:36 UTC
Labels: *duplicate, feature-request, keybindings, quick-pick
