### ISSUE TITLE
VSCode never starts the second time

### ISSUE THREAD

**Issue by sr105** [Microsoft/vscode#7927] opened 2016-06-21 13:53 UTC
- VSCode Version: 1.2.1 fe7f407b95b7f78405846188259504b34ef72761
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Download VSCode
2. Unzip
3. Run (from Finder or Alfred)
4. Quit
5. Run (never opens, crashes on start-up)

     6/21/16 9:40:09.385 AM com.apple.xpc.launchd[1]: (com.microsoft.VSCode.445792[5119]) Service exited with abnormal code: 1

6. Go back to step 1 and you can run it once.

Interestingly, I can run it from the terminal over and over again.

    open Visual\ Studio\ Code.app

I had it in ~/Applications and thought that might be the issue, but after moving it to /Applications, I get the same behavior. It's happened I think for a couple versions. I only run it once every 2 weeks or so. Also, if it helps, I have had my laptop crash while VSCode was opened in case you can think of any kind of corrupted application state data that might do this.

My guess is something to do with my .bash_profile.

**Comment by dbaeumer** [comment] 2016-06-22 08:33
@joaomoreno starting with you because of the reference to the .bash_profile

**Comment by joaomoreno** [comment] 2016-06-22 08:41
Strange that it works with `open Visual\ Studio\ Code.app` but not double click.

When it is running, can you install the `code` shortcut in the `PATH` (<kbd>F1</kbd>, `Install 'code' command in PATH`), quit and then try running it with `code` from your terminal?

**Comment by sr105** [comment] 2016-06-22 12:26
I installed the code command and it works (repeatedly). Is there a way to get more debugging output on startup? 

It's really strange. After running it with code and open, It opened once from Finder, but then it stopped again. Also, yesterday, I saw this behavior. It failed to open from the terminal with a specific path, but only at first. I'm beginning to suspect some other issue and these are all just coincidences.

**open ~/Applications/Visual\ Studio\ Code.app/        failed to start
open ~/Applications/Visual\ Studio\ Code.app/        failed to start**
cd ~/Applications/
open Visual\ Studio\ Code.app/        started
cd ..
open Applications/Visual\ Studio\ Code.app/        started
open /Users/hchapman/Applications/Visual\ Studio\ Code.app/        started
**open ~/Applications/Visual\ Studio\ Code.app/        started**

**Comment by joaomoreno** [comment] 2016-06-22 13:39
How about trying to delete **all** copies of Visual Studio Code and trying all over?

**Comment by sr105** [comment] 2016-06-22 14:06
I guess I've almost done exactly that. I just haven't emptied the Trash.

Deleted the app, emptied the trash, unzipped a new copy of the app. Same behavior. It always starts the first time after being replaced. Then, it never (almost never) starts from Finder again.

**Comment by sr105** [comment] 2016-06-22 14:31
I tried downloading, building, and running 1.2.1. I'm getting an error when I try to run. In summary, I did the following:

 ```
git clone https://github.com/Microsoft/vscode.git
 cd vscode/
 git checkout -b issue_7927 fe7f407b95b7f78405846188259504b34ef72761
 pyenv local 2.7.8
  ./scripts/npm.sh install
 npm run watch
```

and in another terminal: `./scripts/code.sh`

Here's the terminal output from the clone, build, and run watch window along with the output of runnung code.sh along with the console errors produced.


[vscode_clone_build.txt](https://github.com/Microsoft/vscode/files/328096/vscode_clone_build.txt)
[vscode_run_and_errors.txt](https://github.com/Microsoft/vscode/files/328095/vscode_run_and_errors.txt)

**Comment by sr105** [comment] 2016-06-22 14:40
In the following error and specifically this path `/private/tmp/com.apple.launchd.0E1Ci88ccO/ServiceProcessSocket/code-oss-dev-dev-38ba65.sock`, ServiceProcessSocket is not a directory, but is a socket itself.

```
silver:vscode hchapman$ ls -la /private/tmp/com.apple.launchd.0E1Ci88ccO/ServiceProcessSocket
srw-rw-rw-  1 hchapman  staff  0 Jun 20 22:31 /private/tmp/com.apple.launchd.0E1Ci88ccO/ServiceProcessSocket
```

```
silver:vscode hchapman$ ./scripts/code.sh
Error: listen EACCES /var/folders/7b/vbjdcfb515q7fs6vyq73_rbm0000gn/T/
COM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS/USERS/HCHAPMAN/LIBRARY/APPLICATION_SUPPORT/GOOGLE/CHROME_SOCKET=/private/tmp/com.apple.launchd.0E1Ci88ccO/ServiceProcessSocket/code-oss-dev-dev-38ba65.sock
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at /Users/hchapman/Desktop/vscode/out/vs/base/parts/ipc/node/ipc.net.js:104:20
    at new Promise_ctor (/Users/hchapman/Desktop/vscode/out/vs/base/common/winjs.base.raw.js:1901:17)
    at Object.serve (/Users/hchapman/Desktop/vscode/out/vs/base/parts/ipc/node/ipc.net.js:101:16)
    at setup (/Users/hchapman/Desktop/vscode/out/vs/code/electron-main/main.js:139:30)
    at setupIPC (/Users/hchapman/Desktop/vscode/out/vs/code/electron-main/main.js:185:16)

```

**Comment by joaomoreno** [comment] 2016-06-22 18:42
Oh I think your last output just gave us a hint... This looks **very** suspicious:

```
Error: listen EACCES /var/folders/7b/vbjdcfb515q7fs6vyq73_rbm0000gn/T/
COM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS/USERS/HCHAPMAN/LIBRARY/APPLICATION_SUPPORT/GOOGLE/CHROME_SOCKET=/private/tmp/com.apple.launchd.0E1Ci88ccO/ServiceProcessSocket/code-oss-dev-dev-38ba65.sock
```

Might be related to both #7644 and #7343.

Let me ask you to do something for me. When you get Code open, run the following inside the Developer Tools:

```es6
const electron = "/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron";
const cp = require('child_process');
const env = Object.assign({}, process.env, {
    ATOM_SHELL_INTERNAL_RUN_AS_NODE: '1',
    ELECTRON_NO_ATTACH_CONSOLE: '1'
});
const command = `'${electron}' -p 'JSON.stringify(process.env)'`;
const result = cp.spawnSync(process.env.SHELL, ['-ilc', command], {
    detached: true,
    stdio: ['ignore', 'pipe', process.stderr],
    env,
    encoding: 'utf8'
});
const strip = s => s.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');

try {
    console.log(JSON.parse(strip(result.stdout)));
} catch (e) {
    console.log(e);
}
```

Let me know what you get.

**Comment by sr105** [comment] 2016-06-22 20:03
It choked on `JSON.parse`.

```
SyntaxError: Unexpected token 
    at Object.parse (native)
    at <anonymous>:18:22
    at Object.InjectedScript._evaluateOn (<anonymous>:878:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:811:34)
    at Object.InjectedScript.evaluate (<anonymous>:667:21)
```

 However, I just ran that manually like so:

```
silver:~ hchapman$ cd Applications/Visual\ Studio\ Code.app/Contents/MacOS/
silver:MacOS hchapman$ ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 ELECTRON_NO_ATTACH_CONSOLE=1 ./Electron -p 'JSON.stringify(process.env)'
```

The json environment is attached.
[electron_env_json.txt](https://github.com/Microsoft/vscode/files/328672/electron_env_json.txt)

**Comment by joaomoreno** [comment] 2016-06-22 20:07
Awesome, it's definitely related to those other issues. What about this one? You'll get an array of numbers, just gimme those:

```es6
const electron = "/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron";
const cp = require('child_process');
const env = Object.assign({}, process.env, {
    ATOM_SHELL_INTERNAL_RUN_AS_NODE: '1',
    ELECTRON_NO_ATTACH_CONSOLE: '1'
});
const command = `'${electron}' -p 'JSON.stringify(process.env)'`;
const result = cp.spawnSync(process.env.SHELL, ['-ilc', command], {
    detached: true,
    stdio: ['ignore', 'pipe', process.stderr],
    env
});

console.log(result.stdout.slice(0, 100));
```

**Comment by sr105** [comment] 2016-06-22 20:08
```
[27, 93, 49, 51, 51, 55, 59, 82, 101, 109, 111, 116, 101, 72, 111, 115, 116, 61, 104, 99, 104, 97, 112, 109, 97, 110, 64, 115, 105, 108, 118, 101, 114, 46, 108, 111, 99, 97, 108, 7, 27, 93, 49, 51, 51, 55, 59, 67, 117, 114, 114, 101, 110, 116, 68, 105, 114, 61, 47, 85, 115, 101, 114, 115, 47, 104, 99, 104, 97, 112, 109, 97, 110, 47, 65, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 115, 47, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111]
```

**Comment by joaomoreno** [comment] 2016-06-22 20:12
Thanks man, it's definitely a duplicate of #7343. I'll close it here and let's continue discussion over there. I'll look for a fix and will ask you to try it out soon. :+1:

**Closed by joaomoreno** 2016-06-22 20:12 UTC
Labels: needs more info, workbench

**Comment by sr105** [comment] 2016-06-22 20:14
Thanks!
