### ISSUE TITLE
Intellisense and File Save Takes Longer Time

### ISSUE THREAD

**Issue by tea-scripts** [microsoft/vscode#150093] opened 2022-05-21 18:43 UTC
Issue Type: <b>Performance Issue</b>

Issue began suddenly when I started working on NodeJS projects. At first the intellisense suggestions were working perfectly but now it shows up with longer waiting time even though I have manually tried to set the "Quick Suggestion Delay" to 1ms.

When I work on plain Vanilla JS or with just one JavaScript file there is no delay. 

My NodeJs file is only 45MB.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.40GB free)|
|Process Argv|--crash-reporter-id 7d1fd959-857f-4268-aabd-2b0aa98249ff|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   134	 16832	code main
    0	   124	  4812	   shared-process
    0	    90	 16296	     ptyHost
    0	     6	  2808	       console-window-host (Windows internal process)
    0	    70	  9792	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 15664	         C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	    36	 18324	           "C:\Program Files\nodejs\\node.exe"  "C:\Users\timmi\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" start
    0	     5	 12788	             electron_node app.js 
    0	    29	 18536	               electron_node nodemon.js app.js 
    0	    46	  3492	                 "C:\Program Files\nodejs\node.exe" app.js
    0	    87	 19592	     fileWatcher
    0	    87	 20000	     fileWatcher
    0	    78	  9344	   utility-network-service
    1	    93	 12164	   issue-reporter
    0	   362	 13636	   extensionHost
    0	   134	  3132	     "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\timmi\AppData\Local\Temp\vscode-typescript\1aa2d70a4b7295695898\tscancellation-2c28124bc5b477c7f224.tmp* --globalPlugins typescript-styled-plugin --pluginProbeLocations c:\Users\timmi\.vscode\extensions\styled-components.vscode-styled-components-1.7.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    83	 16740	     "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\timmi\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js --node-ipc --clientProcessId=13636
    0	   274	 17824	     "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\timmi\AppData\Local\Temp\vscode-typescript\1aa2d70a4b7295695898\tscancellation-5ec76c413cc2b074a39f.tmp* --globalPlugins typescript-styled-plugin --pluginProbeLocations c:\Users\timmi\.vscode\extensions\styled-components.vscode-styled-components-1.7.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	   100	 18340	       "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/timmi/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/timmi/AppData/Local/Microsoft/TypeScript/4.6 --enableTelemetry --typesMapLocation "c:/Users/timmi/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation
    0	    83	 19992	     "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\timmi\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=13636
    0	   240	 14108	   window (products.js - starter - Visual Studio Code)
    0	    75	 14616	   crashpad-handler
    0	   194	 19424	   window (products.js - node-express-course-main - Visual Studio Code)
    0	   247	 19792	   gpu-process
    0	   357	 20364	   extensionHost
    0	   279	 10036	     "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\timmi\AppData\Local\Temp\vscode-typescript\c7c9e88065597616262a\tscancellation-a35403c316032dc345fd.tmp* --globalPlugins typescript-styled-plugin --pluginProbeLocations c:\Users\timmi\.vscode\extensions\styled-components.vscode-styled-components-1.7.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	   101	 10064	       "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/timmi/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/timmi/AppData/Local/Microsoft/TypeScript/4.6 --enableTelemetry --typesMapLocation "c:/Users/timmi/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation
    0	    83	 14028	     "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\timmi\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=20364
    0	   131	 17804	     "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\timmi\AppData\Local\Temp\vscode-typescript\c7c9e88065597616262a\tscancellation-cc359b7c755b718549fd.tmp* --globalPlugins typescript-styled-plugin --pluginProbeLocations c:\Users\timmi\.vscode\extensions\styled-components.vscode-styled-components-1.7.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    83	 19516	     "C:\Users\timmi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\timmi\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js --node-ipc --clientProcessId=20364
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (products.js - starter - Visual Studio Code)
|  Window (products.js - node-express-course-main - Visual Studio Code)
|    Folder (starter): 20 files
|      File types: js(8) json(3) env(1) gitignore(1) md(1)
|      Conf files: package.json(1)
|    Folder (node-express-course-main): 750 files
|      File types: js(365) json(57) gitignore(23) css(23) html(21) jpeg(20)
|                  MD(14) txt(10) svg(6) png(6)
|      Conf files: package.json(23);
```

</details>
<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.8.4
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
vscode-html-css|ecm|1.12.2
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
fluent-icons|mig|0.0.17
dotenv|mik|1.0.1
python|ms-|2022.6.2
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-wsl|ms-|0.66.3
cpptools|ms-|1.9.8
vsliveshare|ms-|1.0.5561
vsliveshare-audio|ms-|0.1.91
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.17.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.4
sass-indented|syl|1.8.19
errorlens|use|3.5.0
highlight-matching-tag|vin|0.10.1
quokka-vscode|Wal|1.0.474
JavaScriptSnippets|xab|1.8.0
five-server|yan|0.1.4
vscode-preview-server|yui|1.3.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by mjbvz** [comment] 2022-05-22 02:51
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by tea-scripts** [comment] 2022-05-22 06:40
Yes it does.

**Comment by tea-scripts** [comment] 2022-05-22 08:09
All these happens whenever I'm working on a NodeJs Project folder no matter how small the size is.

**Comment by tea-scripts** [comment] 2022-05-22 21:36
Is there anything I can do at the moment asides from the suggested steps? @mjbvz

**Comment by mjbvz** [comment] 2022-05-23 16:52
> My NodeJs file is only 45MB.

Do you mean your project is 45MB? Hopefully you don't have a single 45MB JS file :)

Please share a project that demonstrates the issue so we can investigate

**Comment by tea-scripts** [comment] 2022-05-23 20:09
My bad I meant my folder is currently 45MB. 
[Here's a link to the Repo](https://github.com/tea-scripts/NodeJS-Course-Projects)
You can try opening the folder that starts with "04" then you can proceed to the starter files then test out other numbered folders or in any order.

**Comment by mjbvz** [comment] 2022-05-23 22:15
Sorry but I can't access that repo. Is it private?

**Comment by tea-scripts** [comment] 2022-05-24 00:10
It’s now open. I had some secret keys and access tokens present. Kindly check now. Thank you

**Comment by mjbvz** [comment] 2022-05-24 17:37
Thanks. Based on the project's use of mongoose, this issue looks like a duplicate of https://github.com/Automattic/mongoose/issues/10349 ( and https://github.com/microsoft/TypeScript/issues/48517)

**Closed by mjbvz** 2022-05-24 17:37 UTC
Labels: needs more info
