### ISSUE TITLE
Ask confirmation if the key binding will overwrite an existing one while adding a new keybinding

### ISSUE THREAD

**Issue by khalyomede** [Microsoft/vscode#49037] opened 2018-05-02 09:22 UTC
### Issue Type
Feature Request

### Description

While adding a new key binding to configure a shortcut, it would be great if a confirm box ask for confirmation if the key binding the user is trying to add would overwrite an existing one. 

Might save few seconds trying to remove the key binding because it broke an existing one.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-39-generic

**Comment by sandy081** [comment] 2018-05-03 08:33
Duplicate of https://github.com/Microsoft/vscode/issues/24396

**Closed** 2018-05-03 08:33 UTC
Labels: *duplicate
