### ISSUE TITLE
Contributed activity's busy icon fails to display after resetting containing TreeView's badge state

### ISSUE THREAD

**Issue by kirksl** [microsoft/vscode#165181] opened 2022-11-01 18:09 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.72.2
- OS Version: Windows 10 (19044.2130)

Steps to Reproduce:

1. Create a VSCode extension
2. Contribute a View within an Activity https://github.com/kirksl/karate-runner/blob/master/package.json#L71-L90
4. Create a TreeView within Activity View https://github.com/kirksl/karate-runner/blob/master/src/providerKarateTests.ts#L31
5. Show progress indicator on View https://github.com/kirksl/karate-runner/blob/master/src/commands.ts#L478-L482
6. Notice that busy icon shows for Activity's badge
7. Repeat Steps 1-3 only and return here
8. Set TreeView badge to a value > 0
`this.treeView.badge = { tooltip: 'Failures', value: 1 };`
9. Notice Activity badge is set to value of 1
10. Show progress indicator on View again https://github.com/kirksl/karate-runner/blob/master/src/commands.ts#L478-L482
11. Notice that busy icon does not show now for Activity's badge
12. Clear badge per API documentation https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L10502-L10505
`this.treeView.badge = undefined`
14. Notice that an error is thrown
`Cannot read properties of undefined (reading 'value')`
15. Clear badge per undocumented method
`this.treeView.badge = { tooltip: '', value: 0 };`
16. Notice that numbered badge on Activity is removed
17. Show progress indicator on View again https://github.com/kirksl/karate-runner/blob/master/src/commands.ts#L478-L482
18. Notice busy icon does not show now for Activity's badge

Expectations
1. Clearing Activity badge per documentation in Step 11 works
2. Clearing Activity badge enables busy icon to work as it did in Step 5

**Comment by alexr00** [comment] 2022-11-02 15:55
> 1. Clearing Activity badge per documentation in Step 11 works

Duplicate of https://github.com/microsoft/vscode/issues/162900

> 2. Clearing Activity badge enables busy icon to work as it did in Step 5

Progress should take precedence over the number badge. Looks like we got the priority wrong. Fix coming soon.

**Comment by kirksl** [comment] 2022-11-02 17:00
Thank you @alexr00 appreciate the fast turnaround.

**Closed** 2022-11-03 19:13 UTC
Labels: bug

**Comment by aeschli** [comment] 2022-12-01 10:24
Verified that progress takes precedence over the number badge
