### ISSUE TITLE
Extensions can add context value (metadata) to editors

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#109130] opened 2020-10-22 05:09 UTC
The basic idea is to let the extensions be able to register some metadata to the editors/documents, and can be consumed by others.

### Example

In Java, a source file may have the following metadata:

- hasMain: indicates if the source file as a `main()` method
- isTest: indicates if the source file has test cases

Then, based on the metadata, the shortcuts in the editor toolbar can be executed with different behavior:
![image](https://user-images.githubusercontent.com/6193897/96827216-9fcaff00-1467-11eb-9637-3dad628e9de6.png)

- If `hasMain` is true, run the Java Application
- If `isTest` is true, run the test cases
- If both are true, ask user which kind of execution he want to launch.

**Comment by connor4312** [comment] 2020-10-22 16:53
You can use the [setContext](https://code.visualstudio.com/api/extension-guides/command#using-a-custom-when-clause-context) command to set a context keys for open text documents. For example, you can set a context key `hasMainMethods` to an array of the open document URIs that have a main method, and then have the "when" clause be something like `resource in hasMainMethods`. Let us know if that doesn't work for you.

**Comment by jdneo** [comment] 2020-10-23 07:50
Hi @connor4312, that does help to some extent. But we still have problems on consuming the context value.

Since currently there is no way to get the context value in the code, in order to handle with the different combination of the two booleans, we have to register different commands which represent each combination.

**Comment by connor4312** [comment] 2020-10-23 16:39
Alternately, you could have a "tracker" class internally that sets the context and provides a way to read the different states when a single command is called

**Comment by jdneo** [comment] 2020-10-24 01:10
Yes it's feasible in just one extension, considering the collaboration with multiple extensions, things will be much complicated. Different extensions need to contribute different metadata to the "tracker". And the "tracker" extension needs to expose the commands/apis for register context and consume context.

It will be great if the VS Code itself can support these commands/apis. Just like the context value in the tree view nodes.

**Comment by jrieken** [comment] 2020-10-27 07:33
/duplicate of https://github.com/microsoft/vscode/issues/10471

**Closed** 2020-10-27 07:34 UTC
Labels: *duplicate, api, context-keys
