### ISSUE TITLE
Source control project collapses after staging a file

### ISSUE THREAD

**Issue by nelsonec87** [microsoft/vscode#113656] opened 2021-01-01 11:51 UTC
Issue Type: <b>Bug</b>

Open a folder with multiple repos.
Make changes in all of them.
In the Source control panel, add one file to staging.

The project then just collapses and another one expands.

This started fairly recently.

![vscode bug](https://user-images.githubusercontent.com/3801502/103438181-16763c80-4c0f-11eb-8ef7-7cce755289b4.gif)

VS Code version: Code - Insiders 1.53.0-insider (4a875e23d20b64504a818834f3fa4c40adb8d480, 2020-12-21T12:33:38.481Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.82GB (3.16GB free)|
|Process Argv|--crash-reporter-id 72e692eb-6116-45d3-b610-a669715f316a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
custom-window-zoom|cra|1.1.4
gitlens|eam|11.1.0
tslint|eg2|1.0.44
dotenv|mik|1.0.1
vscode-docker|ms-|1.9.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
angular2-inline|nat|0.0.17
vscode-scss-formatter|sib|2.0.5
vscode-ansible|vsc|0.5.2

</details>

**Comment by eamodio** [comment] 2021-01-08 17:12
Duplicate of https://github.com/microsoft/vscode/issues/112487

**Closed by eamodio** 2021-01-08 17:12 UTC
