### ISSUE TITLE
Mac Code Helper high CPU usage

### ISSUE THREAD

**Issue by asnow003** [Microsoft/vscode#70586] opened 2019-03-15 18:27 UTC
Issue Type: <b>Performance Issue</b>

Open VS Code
Use it for a little bit.
Code complete stops working and starts killing my computer CPU.

Issue occurs after briefly using the editor...then the code help stops working and my CPU is pegged and my computer fans start running on high.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 5|
|Memory (System)|32.00GB (12.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   23	   131	 58102	code main
    6	    98	 58103	   gpu-process
    0	    98	 58444	   shared-process
    5	   328	 58663	   window (authenticationService.ts — Teamspace-Web)
    0	   131	 58664	     extensionHost
    0	    66	 58682	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=58664
  368	  2163	 58745	       electron_node tsserver.js 
    0	    66	 58746	         electron_node typingsInstaller.js typesMap.js 
    0	    66	 58665	     watcherService
    0	    33	 58732	     searchService
    0	    66	 58743	   window (Issue Reporter)
    0	     0	 58748	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (authenticationService.ts — Teamspace-Web)
|    Folder (Teamspace-Web): more than 28656 files
|      File types: ts(9790) js(5224) html(4437) map(4392) json(976) png(903)
|                  svg(628) scss(585) cs(203) gzip(199)
|      Conf files: package.json(49) tsconfig.json(15) csproj(7) sln(6)
|                  gulp.js(4) webpack.config.js(3) tslint.json(3)
|                  launch.json(2) grunt.js(2) tasks.json(1)
|                  settings.json(1)
|      Launch Configs: node(14) chrome;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.4.9
debugger-for-chrome|msj|4.11.3

</details>

**Comment by roblourens** [comment] 2019-03-15 19:55
Please look at these tips to provide as much info as possible: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu

**Comment by roblourens** [comment] 2019-03-15 19:56
Thanks, I will close it as a dupe of https://github.com/Microsoft/vscode/issues/70587

**Closed by roblourens** 2019-03-15 19:56 UTC
Labels: needs more info, new release
