### ISSUE TITLE
macOS's Touch bar shows word suggestions instead of debug buttons

### ISSUE THREAD

**Issue by stijnfrishert** [microsoft/vscode#106541] opened 2020-09-12 10:40 UTC
- VSCode Version: 1.49.0
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. Open a project in VSCode with a launch.json already set up
2. Click on the text editor to give it focus
3. No _Run_ and _Run without debugger_ buttons (two triangles) in the touch bar
4. Select the left side bar, giving it focus
5. The _Run_ and _Run without debugger_ buttons show up.

It used to be the case these buttons always showed. Is it a conscious decision to hide these when editing text? Not a very convenient way of working, to have to click on the sidebar first.

Does this issue occur when all extensions are disabled?: Yes

**Comment by philipmat** [comment] 2020-09-13 14:44
I can confirm this issue. I didn't have this issue on 1.48 and now the Touch Bar buttons get replaced by predictive text suggestions, even when in debug mode, if the focus is with the text editor.

```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
```

**Comment by leonkong** [comment] 2020-09-14 12:44
I have found the same issue on 1.49 on my macOS. But it works well on 1.48.

**Comment by isidorn** [comment] 2020-09-16 10:10
Thanks for filling this, but I can not really reproduce this.
My steps:
1. I open VS Code with Explorer view open
2. After some time (2 seconds) the `Run` and `Run without debugger` buttons appear in the touch bar

So I do not have to open the debug view.

What we changed this milestone is that these touch bar entries are disabled for the first 2 seconds while the debugger extensions are still not there.

If you use https://code.visualstudio.com/insiders/ can you still reproduce the issue (that the debug touch bar items never appear, unless you open the Debug view)

**Comment by philipmat** [comment] 2020-09-16 12:45
Happens with Insiders too:

When the focus is on Explorer:
![image](https://user-images.githubusercontent.com/709928/93338809-68c25780-f7f0-11ea-9a16-82f972c20218.jpeg)

When the focus is in the text editor:
![image](https://user-images.githubusercontent.com/709928/93338932-95766f00-f7f0-11ea-97e0-560ad28ca3f2.jpeg)

**Comment by isidorn** [comment] 2020-09-16 12:58
But if you click on the `>` next to the `I` character the play button should appear. Right?
So this has nothing to do with timing. The issue is that macOS with latest Electron seems to decide to show word suggestions in the touch bar when editor is focused.
Is there maybe an open Electron issue for this? @deepak1556 
fyi @bpasero

**Comment by philipmat** [comment] 2020-09-16 13:28
Indeed it does!  
And it seems to stay that way even as other editor windows are opened.

![image](https://user-images.githubusercontent.com/709928/93343800-8d213280-f7f6-11ea-89b1-9adcab6d2b3c.jpeg)

**Comment by deepak1556** [comment] 2020-09-16 14:12
> The issue is that macOS with latest Electron seems to decide to show word suggestions in the touch bar when editor is focused.

Yeah this is due to the previous fix being reverted in https://bugs.chromium.org/p/chromium/issues/detail?id=1024914#c11 

@isidorn if you read that bug thread, there is lack of examples for vscode need to hide suggestions when `autocorrect=off and spellcheck=false`, might wanna pop up there and add your reason ? specifically in response to https://bugs.chromium.org/p/chromium/issues/detail?id=1024914#c9 . Thanks!

**Comment by bpasero** [comment] 2020-09-16 14:31
@deepak1556 is this maybe the cause for https://github.com/microsoft/vscode/issues/106495 too?

**Comment by isidorn** [comment] 2020-09-16 14:36
@deepak1556 thanks for the pointer. However that issue is "retired", should I just open a new duplicate issue or what is the best thing to do here?

**Comment by stijnfrishert** [comment] 2020-09-16 14:47
Thanks for taking this up, @isidorn! The arrow key does solve the problem, hopefully the issue itself can be fixed over on Electron's side then. :)

**Comment by deepak1556** [comment] 2020-09-16 15:37
@isidorn yup opening a new bug with more details as to why this is a problem for vscode and linking to the old chromium bug would do. Thanks!

@bpasero yup this is the root cause for the other issue.

**Comment by isidorn** [comment] 2020-09-16 15:53
I have opened this issue on the Chromium side https://bugs.chromium.org/p/chromium/issues/detail?id=1128972

**Comment by TheAlmightyBob** [comment] 2020-09-17 18:03
What I'm seeing is that while the debug "play" button still appears if the text editor has focus and the keyboard suggestions are collapsed via the arrow button, if you actually _start debugging_, the debug controls (pause, step, etc) _only appear if the debug pane has the focus_.

**Comment by isidorn** [comment] 2020-09-18 07:58
After discussion with @deepak1556 we would have to fix this issue on the electron side.

@TheAlmightyBob the issue is related when the editor has focus, if you are interested in more details please ready my comments from above. thanks.

**Comment by goda** [comment] 2020-09-18 11:59
For me pressing the arrow character on the Touch Bar does not bring back the debug buttons while the editor is active. As mentioned in #106948 I get this view:
![](https://user-images.githubusercontent.com/480738/93522577-b2e62e80-f8ff-11ea-9668-80689a8383a4.png)

The only way to bring them back is to have the side bar in focus.

**Comment by canpoyrazoglu** [comment] 2020-09-29 18:07
I can also confirm that this bug persists on Code 1.49.2. (and I also realized how much I really used the step buttons on Touch Bar when debugging)

**Comment by deepak1556** [comment] 2020-09-29 18:13
This will be fixed in tomorrow's insider and upcoming stable `1.50`

**Closed by deepak1556** 2020-09-29 18:13 UTC
Labels: debug, electron-9-update, upstream-issue-linked, workbench-touchbar

**Comment by bpasero** [comment] 2020-09-30 10:31
Maybe if someone from the people on this issue could verify with todays insider build.

**Comment by goda** [comment] 2020-09-30 12:36
> Maybe if someone from the people on this issue could verify with todays insider build.

Downloaded insider build and I've verified that the issue is no longer present on my machine. 

Version: 1.50.0-insider
Commit: 0c50e1db17168a738235bd7e5c02b9f05ea5df59
Date: 2020-09-30T06:45:45.996Z (5 hrs ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0

**Comment by bpasero** [comment] 2020-09-30 12:46
Thanks!

**Comment by canpoyrazoglu** [comment] 2020-10-04 05:47
Yup, I got the 1.50.0 insider and I can confirm that the bug is fixed. Thanks!
