### ISSUE TITLE
toggle blockcomment

### ISSUE THREAD

**Issue by wlccgp3** [Microsoft/vscode#34872] opened 2017-09-23 08:08 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (b86108e54b31572d0f9678ffbd14f9ee8d3b3780, 2017-09-21T05:15:52.338Z)
- OS Version: Linux x64 4.9.0-deepin11-amd64

vscode is only append blockcomment when i code javascript, it don't toggle blockcomment when click keyboard shortcuts again. 
sorry for my poor english

**Comment by yume-chan** [comment] 2017-09-24 13:23
你是指不选中任何东西的时候，按第一下 Toggle Block Comment 的时候会插入一个空的块注释，但是立即再按一下 Toggle Block Comment 不会删除这个块注释？

Do you mean that when these is nothing being selected, press Toggle Block Comment will insert a blank block comment, but immediately press Toggle Block Comment again will not delete this block comment?

**Comment by alexandrudima** [comment] 2017-09-25 10:45
Duplicate of #34618

**Closed by alexandrudima** 2017-09-25 10:45 UTC
Labels: bug, editor, insiders
