### ISSUE TITLE
Ability to edit the label in a treeview

### ISSUE THREAD

**Issue by gplumb** [microsoft/vscode#117502] opened 2021-02-23 23:19 UTC
As a vscode extension author, I'd like to be able to specify if a vscode.TreeItem can be renamed and for the treeview control to support this on "selection | F2" in the same manner as nodes in the explorer treeview.  The option to do this wholesale at tree level would be welcome, but for the ultimate flexibility (and the particular use-cases I have in mind), being able to independently dictate which node can be renamed at vscode.TreeItem level is an important requirement to capture.

![TreeviewRename](https://user-images.githubusercontent.com/741350/108920379-78aa5700-762c-11eb-8df0-4f888f9e5ad2.png)

I appreciate that the model here is a PULL model (by design), but this functionality doesn't have to violate that.  By raising an event against the TreeViewProvider that provides the node identifier, along with it's old and new label values, there would be enough flexibility for developers to reflect changes in any underlying datatypes or systems.

**Comment by alexr00** [comment] 2021-02-24 10:17
Feature request here is to support an input box in extension trees. Duplicate of https://github.com/microsoft/vscode/issues/97190

**Closed** 2021-02-24 10:18 UTC
Labels: *duplicate
