### ISSUE TITLE
Change Local Address Port

### ISSUE THREAD

**Issue by Escarnope** [microsoft/vscode#192681] opened 2023-09-09 21:33 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.82.0
- OS Version:  Windows 10

Steps to Reproduce:

1. Connect to remote via SSH
2. Start service (I'm using Adonis dev server [npm run dev])
3. Forward Ports

I want to change a forwarded port, before updating to the latest version I was able to

I want remote:1234 to be localhost:whatever instead of being forced to do localhost:1234

The option to change local port is missing

Before:
![Before](https://i.imgur.com/9OoE38K.png)

Now:
![Now](https://i.imgur.com/YQVUWwO.png)

**Comment by alexr00** [comment] 2023-09-11 10:38
I still see the "Change Local Address Port" option in the context menu for SSH. Can you share a screenshot of the full Ports view in you example where it isn't working?

**Comment by alexr00** [comment] 2023-09-11 10:50
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/8933

**Closed by alexr00** 2023-09-11 10:50 UTC
Labels: info-needed, new release
