### ISSUE TITLE
`editor.autoClosingDelete` does not seem to work when set to `auto`

### ISSUE THREAD

**Issue by sulaysumaria** [microsoft/vscode#120959] opened 2021-04-09 18:24 UTC
- VS Code Version:
```Version: 1.55.1 (Universal)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T18:22:52.186Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0
```
- OS Version:
```
MacOS 11.2.3 (20D91)
```

Steps to Reproduce:

1. Open vscode.
2. Create a new js file
3. Type Following: `()`
4. Try and remove `(`.
5. Expected: `)` should also be removed. But it is not when `editor.autoClosingDelete` is set to `auto` (default value)
6. Changing `editor.autoClosingDelete` to `always` works.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment] 2021-05-06 09:15
@sulaysumaria I cannot reproduce. When I hit backspace, the closing bracket gets removed for me:

https://user-images.githubusercontent.com/5047891/117273251-41da9380-ae5c-11eb-8e6f-aa1df4598380.mp4

**Closed** 2021-05-13 11:28 UTC
Labels: needs more info
