### ISSUE TITLE
Autocomplete inserts newline when it should not

### ISSUE THREAD

**Issue by tylerb** [Microsoft/vscode#26669] opened 2017-05-15 18:38 UTC
- VSCode Version: Version 1.12.1 (1.12.1)
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Create an identifier
2. Type the whole word of that identifier
3. Press return to dismiss the autocomplete box
4. A newline is inserted instead of the box simply being dismissed

![screen recording 2017-05-15 at 12 38 pm](https://cloud.githubusercontent.com/assets/70804/26073202/5ba55d78-396b-11e7-9afb-d9dcd20b378d.gif)

**Comment by jrieken** [comment] 2017-05-16 07:40
dupe of https://github.com/Microsoft/vscode/issues/24420. See https://github.com/Microsoft/vscode/issues/24420#issuecomment-300413716 for a discussion and a workaround

**Closed** 2017-07-24 10:29 UTC
