### ISSUE TITLE
Column guide

### ISSUE THREAD

**Issue by james-cxx** [Microsoft/vscode#2651] opened 2016-02-02 19:55 UTC
I do a fair bit of editing in Markdown, and I like to hard-wrap blocks of text at column 120 (as opposed to the visual wrapping that happens in VSCode based on the editor.wrappingColumn setting).  

It would be really helpful to have a visual guide at a user-defined column number.  This visual guide would affect nothing, it would merely appear as a faintly visible vertical line that shows where the specified column is, such as column 120.  That way, when I'm writing large blocks of text, I don't have to constantly look down to the column number indicator to see where I should be hard-wrapping the text.

**Comment by egamma** [comment] 2016-02-02 20:00
duplicate of #1673

**Closed by egamma** 2016-02-02 20:00 UTC

**Comment by james-cxx** [comment] 2016-02-02 20:07
My apologies.  I did make an effort to do a search, but I did not find #1673.  Thanks for the heads-up.

**Comment by egamma** [comment] 2016-02-02 20:23
no problem at all.
