### ISSUE TITLE
No Error Hint?

### ISSUE THREAD

**Issue by jlocca** [microsoft/vscode#58123] opened 2018-09-06 21:48 UTC
![vs-code-no-error-hint](https://user-images.githubusercontent.com/16841852/45186793-87de8580-b1e3-11e8-95bf-88232598a598.jpg)
Issue Type: <b>Bug</b>

I am surprised / disappointed that VSC does not give me a visual warning (next to the line numbers) to tell me that I made an error. I had pasted an opening UL tag directly after another opening UL tag, yet VSC did not bring any attention to the error. 

Is there a setting I can activate in order to get this kind of feedback from VSC? 

**Thank you.**

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.53GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_33197991|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|0.3.0
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.4.2
code-runner|for|0.9.4
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.4.2
material-icon-theme|PKi|3.5.3
vscode-css-peek|pra|2.1.0
code-spell-checker|str|1.6.10
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2019-10-09 15:58
duplicate of #23199

**Closed by aeschli** 2019-10-09 15:58 UTC
