### ISSUE TITLE
tsc not found after upgrading to 1.41

### ISSUE THREAD

**Issue by paulbuying** [microsoft/vscode#86889] opened 2019-12-13 08:24 UTC
Issue Type: <b>Bug</b>

Running the default build task is broken after upgrading to 1.41. Also checking or changing the Typescript version is gone from the Command-Shift-P menu.

/bin/bash: tsc: command not found
The terminal process terminated with exit code: 127

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.68GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
vscode-npm-script|eg2|0.3.9
json-tools|eri|1.0.2
vscode-npm|fkn|3.3.0
search-node-modules|jas|1.3.0
terraform|mau|1.4.0
vscode-docker|ms-|0.9.0
json-organizer|rin|0.0.4
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.6.1

(1 theme extensions excluded)

</details>

**Comment by paulbuying** [comment] 2019-12-13 17:37
Same as @johnspurlock, I'm also working with a local `./node_modules/.bin` instead of a global `tsc`.

**Comment by alexr00** [comment] 2019-12-17 10:45
@mjbvz stepping through the typescript extension code, I can see that the local tsc is used. However, when I just run with out debugging then the global tsc is used.

**Comment by alexr00** [comment] 2019-12-17 11:02
So long as I have tsc in my workspace folder under node_modules/.bin, then it works fine for me. Can anyone who's seeing this issue provide a full sample or repository?

**Comment by paulbuying** [comment] 2019-12-17 11:10
I have multiple repos and all of them work with a local `tsc` (in `./node_modules/.bin`), so for me the issue is about the local `tsc` case, not about the global one. I'd like to help here, but I can't post a whole repo. What is smaller than everything and would also help here?

**Comment by alexr00** [comment] 2019-12-17 12:02
Duplicate of https://github.com/microsoft/vscode/issues/85753

**Closed** 2019-12-17 12:02 UTC
Labels: *duplicate
