### ISSUE TITLE
Delete unused should not remove unused method input parameters

### ISSUE THREAD

**Issue by jkristia** [Microsoft/vscode#51478] opened 2018-06-08 18:02 UTC
Issue Type: <b>Bug</b>

I really like the new 'remove unused' feature for removing unused imports and variables.

However, I don't think it should remove unused parameters from methods. For instance if you have an angular click event handler where you pass the $event and a second parameter, but really only use the second parameter. In this case the code was changed from

public myClickHandler(e: any, mydata: MyDataType) { ... }

was changed to 

public myClickHandler(mydata: MyDataType) { ... }

since e was never used, and the code is now broken - with no warnings, and if you happen to not cover this particular event in a unit test you wont notice until you manually test the UI.

Maybe we can have an option to only remove all unused imports and variables, but leave unused parameters alone ?

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (17.89GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
ng-template|Ang|0.1.9
gitlens|eam|8.3.4
tslint|eg2|1.0.30
rest-client|hum|0.18.4
vs-color-picker|lih|0.7.0
python|ms-|2018.5.0
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.5.0

</details>

**Comment by ritwickdey** [comment] 2018-06-10 10:16
Yep! This should not be on callback functions.

For an example:
 
![image](https://user-images.githubusercontent.com/18099464/41200604-613d9ef6-6cc5-11e8-8632-b502bc580698.png)


I can't remove the `req` variables.

**Comment by mjbvz** [comment] 2018-06-12 02:21
Duplicate of https://github.com/Microsoft/TypeScript/issues/24303

Fixed in typescript@next

**Closed by mjbvz** 2018-06-12 02:21 UTC
Labels: new release
