### ISSUE TITLE
Accidental literal substitution in regex search for some matches (CRLF line endings)

### ISSUE THREAD

**Issue by Simran-B** [microsoft/vscode#87247] opened 2019-12-18 11:39 UTC
**Version:** 1.42.0-insider
**Commit:** 241d4048aabc31db0baed66bb3d58cf3210d981d
**Date:** 2019-12-17T10:**43:**45.626Z
**Electron:** 6.1.6
**Chrome:** 76.0.3809.146
**Node.js:** 12.4.0
**V8:** 7.6.303.31-electron.0
**OS:** Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Download and unzip test files: [issue87247.zip](https://github.com/microsoft/vscode/files/3978213/issue87247.zip)
2. Open the folder in VSCode
3. Open search (Ctrl+Shift+F)
4. Enter `(^.+)(\n\{% aqlexample)` as search phrase, enable regex search, replace by `$1\n$2`
5. It finds 16 results in 2 files:
   ![image](https://user-images.githubusercontent.com/7819991/71081903-657e3a80-2190-11ea-85e9-650ebb1a7a43.png)
6. Note the first 3 matches in `graphs-traversal.md` and click on the first to open the replace preview. Instead of inserting a blank line above `{% aqlexample`, it tries to do a literal substitution?
   ```diff
    Examples:
   -
   -{% aqlexample examplevar="examplevar" type="type" query="query" bind="bind" result="result" %}
   +$1
   +$2 examplevar="examplevar" type="type" query="query" bind="bind" result="result" %}
   ```
7. Click on the 4th match for that file. The replace preview shows the insertion of a blank line as expected:
   ```diff
    #### Filtering edges on the path
   +
    {% aqlexample examplevar="examplevar" type="type" query="query" bind="bind" result="result" %}
   ```
8. Click on the sole match for `examples-join.md` and see the 3 messed up matches disappear from the result list for the other file.
9. Click on refresh and they will re-appear.

![bug87247](https://user-images.githubusercontent.com/7819991/71083326-0bcb3f80-2193-11ea-82e3-834abe2cb84f.gif)

Note: I can observe this behavior with CRLF line endings, but not LF line endings.

Does this issue occur when all extensions are disabled? Yes

**Comment by roblourens** [comment] 2019-12-20 00:11
This works if you change the `\n` to `\r\n` or `\r?\n` right? This replacement is a gap in our newline normalization.

**Comment by Simran-B** [comment] 2019-12-21 00:32
I observe the same behavior as I described with `(^.+)(\r?\n\{% aqlexample)` (optional CR).

With a mandatory CR - `(^.+)(\r\n\{% aqlexample)` - things get even weirder. The three erroneous matches do not show (good), but if I click on a match from `graphs-traversals.md` to open the replace preview followed by a click on a match from `examples-join.md`, then all matches of the former disappear.

A click on refresh brings back the 12 matches of `graphs-traversals.md`, but the entry for `examples-join.md` then disappears. Another click on refresh brings back all matches.

![bug87247_2](https://user-images.githubusercontent.com/7819991/71300028-b9a43d00-2391-11ea-9828-9ca2182d81ec.gif)

Changing the replace string to `$1\r\n$2` doesn't change the behavior (it actually tries to insert literal `\r`).

**Comment by roblourens** [comment] 2020-01-02 19:38
Yeah, this is because the editor normalizes newlines to \n, so `\r\n` won't match anymore when the file is opened in the editor. Search works differently whether a file is opened or not, leading to weird bugs like this.

**Comment by connor4312** [comment] 2020-11-14 00:03
I dove into this some more. I'm not sure it's line endings. We normalize the regex and pass `(^.+)(\r?\n\{% aqlexample)` to ripgrep. This actually matches `Examples:\r\n\r\n{% aqlexample`... which it should not. May be a rg bug rather than a VS Code bug.

**Comment by Simran-B** [comment] 2020-11-14 00:40
> This actually matches `Examples:\r\n\r\n{% aqlexample`... which it should not.

Hm, not sure if I follow. Should the matches be rather like this?
1. `Examples:\r\n`
2. `\r\n{% aqlexample`

Or do you mean that `^.+` should not match line breaks? Not sure about that. Since there is a `\n` in the regex, multiline search is enabled. Does that change the meaning of `.` to include line breaks?

**Comment by connor4312** [comment] 2020-11-16 19:27
Yeam `(^.+)(\r?\n\{% aqlexample)` should require, to the best of my understanding:

- The start of a line,
- followed by 1 or more _non-linebreak_ characters
- followed by exactly one LF or CRLF
- followed  by `{% aqlexample`

Ripgrep says this matches `Examples:\r\n\r\n{% aqlexample`, which is not correct.

**Comment by roblourens** [comment] 2022-12-13 22:29
rg has the `--crlf` flag which makes `$` able to match CRLF. But with this flag, `.` still matches `\r`, and that seems wrong. `--crlf` sounds like a bit of a hack in rg for `$` specifically. You could file an issue on the ripgrep repo for this. 

We could also work around it on our end by rewriting `.` to `[^\r\n]`, similar to how we rewrite `\n` already, and I think that would fix it.

**Comment by Simran-B** [comment] 2022-12-15 15:17
According to https://www.regular-expressions.info/dot.html#linebreak, there is no consensus on what is a line break character other than `\n`. It varies from one character to the full list of Unicode whitespace characters...

The `--crlf` option seems like it _could_ also control the `.` behavior but doesn't at the moment. It's a workaround on rg's side (replacing `$` with `(?:\r??$)`), not a regex engine feature, so you may as well rewrite the expressions in VSCode as a workaround.

@connor4312 wrote that `(^.+)(\r?\n\{% aqlexample)` would match `Examples:\r\n\r\n{% aqlexample`. I can **not confirm** that with VSCode v1.72.0. Searching and replacing all matches without having any files open only replaces the empty line and the  `{% aqlexample` string in my test but leaves `Examples:` untouched. The same goes for `(^.+)(\n\{% aqlexample)`. The `Examples:` line is only replaced if I use `\r?\n\r?\n` or `\n\n` in the regex. So it seems like there is only the odd behavior caused by the CRLF vs. LF mismatch but no additional bug.

**Comment by osortega** [comment] 2024-12-20 19:03
Duplicate of https://github.com/microsoft/vscode/issues/172882
Closing this one in favor of that one

/duplicate

**Closed by osortega** 2024-12-20 19:03 UTC
Labels: bug, search, confirmed
