### ISSUE TITLE
Accidentally wrote a regex that froze VSCode

### ISSUE THREAD

**Issue by rudi-c** [microsoft/vscode#87288] opened 2019-12-18 22:38 UTC
Steps to Reproduce:

1. Wrote the following regex in VSCode: `getValueOrNull\(([^)]*),([^)]*)*\)[^:]`. This caused VSCode to freeze and become unresponsive.

I think the issue might be the double * next to each other. For context, I wasn't looking to write an adverserial regex. I wanted to write a regex that searches for all instances of the `getValueOrNull` function that take two parameters, and I put the * in the wrong place. When I moved it, the intermediate step of having two * next to each other caused VSCode to freeze.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2019-12-19 00:22
/duplicate of #30874 and may other issues

Two `*` most likely a root cause of the issue. See https://github.com/microsoft/vscode/issues/30874#issuecomment-315861140 for more details

**Closed** 2019-12-19 00:22 UTC
Labels: *duplicate
