### ISSUE TITLE
Can't call sendText API or paste into terminal with long text

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#38137] opened 2017-11-12 01:34 UTC
- VSCode Version: Code 1.18.0
- OS Version: Darwin x64 17.3.0

I just found out that I can't call `terminal.sendText` with a text as long as the following one, because it gets cropped:

```
echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo"
```

I found out about this issue because I'm coding a little function that given N paths it opens them in a new VSC window as an unnamed workspace, and for doing so it's building a command that looks like this: `code path1 && code --add path2 && (...) code --add pathN`. 

I can't even split this particular command into smaller ones because of https://github.com/Microsoft/vscode/issues/38138. 

Why is there even this limitation?

**Comment by Tyriar** [comment] 2017-12-15 19:06
How long does the path get before it starts to truncate? Is there a pattern to it?

**Comment by fabiospampinato** [comment] 2017-12-18 15:04
The only pattern I can see is that the text gets cropped after 1018 characters, but only if that's the very first text being sent to the terminal, otherwise it works fine.

**Comment by Tyriar** [comment] 2018-11-30 20:11
Also happens with pasting apparently https://github.com/Microsoft/vscode/issues/63613

**Comment by stevenr3** [comment] 2019-06-03 23:24
I think this bug is preventing "CMake: Compile File" from working for me. Selecting this command just switches to the TERMINAL window and nothing happens. If I try pasting the command line in manually (1562 chars long) nothing happens. If I paste the command in 2 pieces, it  works as expected. Windows 7.

**Comment by DougPlumley** [comment] 2019-06-28 19:27
Downstream impacts using VS Code for Python development, definitely makes it challenging to use VS Code for me. :(

**Comment by nickcorona** [comment] 2019-07-30 14:21
Why is this issue being closed? This bug makes coding in Python impractical. You can't send any decently long script to a Python REPL because of it.

**Comment by nickcorona** [comment] 2019-07-30 14:23
Any update on this?

**Comment by jrounds** [comment] 2019-09-11 15:40
I had all these errors (there is a family of pasting to python terminal) as of about June/July, but just retested with August update and none of them replicate (did 3 of them).  For example the big paste 99 lines of python bug report replicated for me in June/July, but now it does not.

Did these get quitely get fixed somewhere?  Anyway. Send text to terminal bugs seem to have went away for me.


E.g. send text to terminal works just fine for me with this:


```
def test():
    print("0 test line.")
    print("1 test line.")
    print("2 test line.")
    print("3 test line.")
    print("4 test line.")
    print("5 test line.")
    print("6 test line.")
    print("7 test line.")
    print("8 test line.")
    print("9 test line.")
    print("10 test line.")
    print("11 test line.")
    print("12 test line.")
    print("13 test line.")
    print("14 test line.")
    print("15 test line.")
    print("16 test line.")
    print("17 test line.")
    print("18 test line.")
    print("19 test line.")
    print("20 test line.")
    print("21 test line.")
    print("22 test line.")
    print("23 test line.")
    print("24 test line.")
    print("25 test line.")
    print("26 test line.")
    print("27 test line.")
    print("28 test line.")
    print("29 test line.")
    print("30 test line.")
    print("31 test line.")
    print("32 test line.")
    print("33 test line.")
    print("34 test line.")
    print("35 test line.")
    print("36 test line.")
    print("37 test line.")
    print("38 test line.")
    print("39 test line.")
    print("40 test line.")
    print("41 test line.")
    print("42 test line.")
    print("43 test line.")
    print("44 test line.")
    print("45 test line.")
    print("46 test line.")
    print("47 test line.")
    print("48 test line.")
    print("49 test line.")
    print("50 test line.")
    print("51 test line.")
    print("52 test line.")
    print("53 test line.")
    print("54 test line.")
    print("55 test line.")
    print("56 test line.")
    print("57 test line.")
    print("58 test line.")
    print("59 test line.")
    print("60 test line.")
    print("61 test line.")
    print("62 test line.")
    print("63 test line.")
    print("64 test line.")
    print("65 test line.")
    print("66 test line.")
    print("67 test line.")
    print("68 test line.")
    print("69 test line.")
    print("70 test line.")
    print("71 test line.")
    print("72 test line.")
    print("73 test line.")
    print("74 test line.")
    print("75 test line.")
    print("76 test line.")
    print("77 test line.")
    print("78 test line.")
    print("79 test line.")
    print("80 test line.")
    print("81 test line.")
    print("82 test line.")
    print("83 test line.")
    print("84 test line.")
    print("85 test line.")
    print("86 test line.")
    print("87 test line.")
    print("88 test line.")
    print("89 test line.")
    print("90 test line.")
    print("91 test line.")
    print("92 test line.")
    print("93 test line.")
    print("94 test line.")
    print("95 test line.")
    print("96 test line.")
    print("97 test line.")
    print("98 test line.")
    print("99 test line.")
    print("0 test line.")
    print("1 test line.")
    print("2 test line.")
    print("3 test line.")
    print("4 test line.")
    print("5 test line.")
    print("6 test line.")
    print("7 test line.")
    print("8 test line.")
    print("9 test line.")
    print("10 test line.")
    print("11 test line.")
    print("12 test line.")
    print("13 test line.")
    print("14 test line.")
    print("15 test line.")
    print("16 test line.")
    print("17 test line.")
    print("18 test line.")
    print("19 test line.")
    print("20 test line.")
    print("21 test line.")
    print("22 test line.")
    print("23 test line.")
    print("24 test line.")
    print("25 test line.")
    print("26 test line.")
    print("27 test line.")
    print("28 test line.")
    print("29 test line.")
    print("30 test line.")
    print("31 test line.")
    print("32 test line.")
    print("33 test line.")
    print("34 test line.")
    print("35 test line.")
    print("36 test line.")
    print("37 test line.")
    print("38 test line.")
    print("39 test line.")
    print("40 test line.")
    print("41 test line.")
    print("42 test line.")
    print("43 test line.")
    print("44 test line.")
    print("45 test line.")
    print("46 test line.")
    print("47 test line.")
    print("48 test line.")
    print("49 test line.")
    print("50 test line.")
    print("51 test line.")
    print("52 test line.")
    print("53 test line.")
    print("54 test line.")
    print("55 test line.")
    print("56 test line.")
    print("57 test line.")
    print("58 test line.")
    print("59 test line.")
    print("60 test line.")
    print("61 test line.")
    print("62 test line.")
    print("63 test line.")
    print("64 test line.")
    print("65 test line.")
    print("66 test line.")
    print("67 test line.")
    print("68 test line.")
    print("69 test line.")
    print("70 test line.")
    print("71 test line.")
    print("72 test line.")
    print("73 test line.")
    print("74 test line.")
    print("75 test line.")
    print("76 test line.")
    print("77 test line.")
    print("78 test line.")
    print("79 test line.")
    print("80 test line.")
    print("81 test line.")
    print("82 test line.")
    print("83 test line.")
    print("84 test line.")
    print("85 test line.")
    print("86 test line.")
    print("87 test line.")
    print("88 test line.")
    print("89 test line.")
    print("90 test line.")
    print("91 test line.")
    print("92 test line.")
    print("93 test line.")
    print("94 test line.")
    print("95 test line.")
    print("96 test line.")
    print("97 test line.")
    print("98 test line.")
    print("99 test line.")
 







{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}

#this worked in send text to bash too
#echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo" && echo "foo"
```

**Comment by Tyriar** [comment] 2019-09-11 16:05
Maybe one of the recent updates to node-pty could have affected it, would be interested to hear if the issue if fixed for others in the latest version (with platform info).

**Comment by Tyriar** [comment] 2019-10-08 15:29
I can no longer reproduce, if you still experience this issue please make sure you're testing on the latest insiders version and note your OS/version and how you reproduced the issue.

**Comment by Tyriar** [comment] 2020-05-08 13:13
From https://github.com/microsoft/vscode/issues/87183

> I'm sure there is a solution, it's just not something I'm focusing on at the moment. If anyone wants to investigate this, I suspect the problem lies inside the node-pty component which manages the connection between VS Code and the process inside the terminal, either in how it's created and/or socket limitations when writing.
> 
> Related: #59135

**Comment by jrounds** [comment] 2020-05-08 17:38
You can see I commented on sept 19, 2019 that this was gone because at the time I tested all three versions of bug reports on this and none of them did it and prior to that all 3 were bugs for me.

As of May 7th 2020 the python test in sept 19th, 2019 comment is back. 

Not sure what changed.  However the original issue on this bug report works correctly for me still (unable to reproduce)

The python version of this bug is able to be reproduce.  The bash version is not able to be reproduced.

I tried to reopen it as a new bug report pointing to the original python version but it was closed in favor of this one.  The original python version is:
https://github.com/microsoft/vscode/issues/71105


So summary just going off original posted steps to recreate:

**As of May 7th, 2020:**
#71105 bug _can_ be recreated by me
#38187 bug _cannot_ be recreated by me.

**Version info**
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z (1 day ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by gowerc** [comment] 2020-05-11 17:17
Hey @jrounds ,   

Just to say that I am experiencing this issue in bash (well zsh to be precise) as I put in my duplicated ticket here #96973

version:
1.45.0
d69a79b73808559a91206d73d7717ff5f798f23c
x64
Mac OS Mojave 10.14.6

**Comment by jrounds** [comment] 2020-05-11 19:27
Oh you are right.

I did your test and echo line 37 is mangled with echo line 38.

**Comment by gowerc** [comment] 2020-05-12 11:38
@Tyriar ,  I know you have already said this is not a focus area at the moment but just thought I would add that this issue does make it hard to use vscode for interactive development work (in my case R and Python) where you may have long classes/functions. Hoping it would be possible at some point to get some attention to this issue !  (I would try look into it myself but I do not know any of the code base nor node/javascript )

**Comment by Tyriar** [comment] 2020-05-12 12:12
@gowerc why not save a .py file and run that instead?

**Comment by gowerc** [comment] 2020-05-12 13:55
Hey @Tyriar, I would invite others to comment as well but for me I work mostly on data science type projects where interactive exploration of data and development of code is super important where you need to see and play with intermediate objects. Once completed most programs will be run  as a .py  / .R file.   

Custom classes / functions can be saved into separate files and loaded via `import` or `devtools::load()` but this can be a bit of a faff if your code was originally small enough to be a single file and you didn't have any intention of styling it as a module/package.

**Comment by diazdc** [comment] 2020-05-12 14:26
@gowerc I also work in a data science related field (bioinformatics) and this issue is the only thing keeping me from switching from Sublime Text to VS Code. I do hope more people chime in so it can get resolved. Platforms like RStudio and Spyder have had this functionality since their inception, but are unfortunately tied to a single language.

**Comment by jrounds** [comment] 2020-05-12 15:51
> @gowerc why not save a .py file and run that instead?

I work in data science, and typically when I am operating this way I am writing the .py file for long term use on a remote machine and/or just trying to get to result as rapidly as possible on a remote machine.

In your scenario, I would have to commit, push, pull on a remote machine, rerun, and carefully isolate the state of the environment I wanted to test or let it run, see what line number broke, go to my code fix the line number, commit, push, pull, rerun.  See what line number broke, go to my code fix the line number, commit, push, pull, rerun.

Or I can open competitor IDE, send  to terminal until I get to the tricky stuff to write, and code line by line until the .py file is correct, and commit, push pull, rerun once because I interactively verified the code works the first time.

That is why.

**Comment by jrounds** [comment] 2020-05-13 19:08
I cared enough about this to start reverting vscode versions, and I thought with a little bit of care I could help some by treating it like a by-hand regression testing.  

Regarding the test at https://github.com/microsoft/vscode/issues/96973

This version has the correct behavior:

##  Feb

*File*  https://update.code.visualstudio.com/1.43.2/darwin/stable

*Version Info*

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0


*Result*

```bash
(base) <user>$ echo "hello, world"  # 036 
hello, world
(base) <user>$ echo "hello, world"  # 037 
hello, world
(base) <user>$ echo "hello, world"  # 038 
hello, world
(base) <user>$ echo "hello, world"  # 039 
hello, world
(base) <user>$ echo "hello, world"  # 040 
hello, world
(base) <user>$ echo "hello, world"  # 041 
hello, world
(base) <user>$ echo "hello, world"  # 042 
hello, world
(base) <user>$ echo "hello, world"  # 043 
```

## March
The March file does not have the correct behavior. 

*File* https://update.code.visualstudio.com/1.44.2/darwin/stable

*Result*
Same unexpected behavior result reported in #96973

## April
The April file does not have the correct behavior.

*File* https://update.code.visualstudio.com/1.45.0/darwin/stable

*Result* 
Same unexpected behavior result reported in #96973

**Comment by gowerc** [comment] 2020-05-14 15:21
Hey @jrounds & @diazdc  I've found a workaround that solves this problem (though I stress its a workaround so would be great to get an official solution).

The extension R  ( ikuyadeu.r by Yuki Udeda) has the command r.runSelectionInActiveTerm which seems to be able to run any length of text without issue in the active terminal.  I just bound this command to `ctrl+enter` and I can now use this for all my development (sh + python + R) :) 

keybindings.json : 
```
    {
        "key" : "ctrl+enter",
        "command" : "r.runSelectionInActiveTerm"
    }
```

**Comment by shaunc** [comment] 2020-06-08 04:51
I seem to be getting this when running a shell task (which runs python behave) -- output is truncated when there is a lot of it. (which is just when I need it -- I turn on some diagnostic so I can debug, and suddenly the whole test case output is truncated :/)

**Comment by Tyriar** [comment] 2020-06-08 12:34
I simply cannot reproduce this on my Macbook using Catalina 10.15.4 (Darwin 19.4.0). I can paste and run selected many times the amount that is pasted in here.

**Comment by Tyriar** [comment] 2020-06-08 12:39
Linux (via WSL2) works fine too:

![recording (14)](https://user-images.githubusercontent.com/2193314/84031223-26b08c80-a94a-11ea-8a4c-c0ed65d5da06.gif)

And here's Windows which has PowerShell throw exceptions about the line being too long, it still appears to send all the text correctly though.

![recording (15)](https://user-images.githubusercontent.com/2193314/84031362-611a2980-a94a-11ea-8287-bad08bf1369b.gif)

**Comment by Tyriar** [comment] 2020-06-08 12:40
Anyone still experiencing this please share your OS+version, perhaps this was an old Mac/Linux upstream bug that has since been fixed?

**Comment by jrounds** [comment] 2020-06-08 15:01
System Version:	macOS 10.14.6 (18G3020)
  Kernel Version:	Darwin 18.7.0

But note my post above it goes away for me in older versions of vscode on this same OS.  I guess that could still be consistent with an upstream bug =/

**Comment by mmc1718** [comment] 2020-06-09 01:06
I am having this issue, I am using Windows 10 version 1903 (build 18362.836) and the latest version of VScode (1.45.1)

I can paste long text fine, I just can't print it to terminal, when i do it cuts off midway. I have tried changing the Text Output Limit in the Python extension settings but it doesn't make a difference. It prints fine when I run in the Python terminal outside of VScode.

**Comment by gowerc** [comment] 2020-06-09 10:11
I've still got this issue :(

![image](https://user-images.githubusercontent.com/8447209/84135249-a9684300-aa41-11ea-931e-ce3fe4b9bc1c.png)


Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Mojave 10.14.6 (18G4032)

**Comment by DougPlumley** [comment] 2020-07-17 15:20
@Tyriar I'm happy to connect with you to troubleshoot this if it would be helpful.

**Closed** 2020-08-11 15:19 UTC
Labels: bug, integrated-terminal

**Comment by Tyriar** [comment] 2020-08-11 15:23
I'm still not able to reproduce and just worked through the issue with @DougPlumley and it looks like we came up with a solution. Unfortunately it involves timeouts and magic numbers as it appears the underlying issue is some race condition around writing to file descriptors in either node.js or Linux. The workaround involves disallowing "large writes" (> 50 chars) and instead spacing them out (by 5ms). I see at least someone reproduced the issue in [Windows as well](https://github.com/microsoft/vscode/issues/38137#issuecomment-640967380) which may be something else, but regardless the workaround to space out writes also applies there.

Thanks @DougPlumley!

**Comment by connor4312** [comment] 2020-09-03 17:02
Marking verified since it seems to work for me on Linux, OSX, and Windows, though I see there were reproduction issues historically...

**Comment by Tyriar** [comment] 2020-09-03 17:04
@connor4312 yeah I could never repro this. @DougPlumley it would be great if you could tell us if it's working now for you on Insiders.

**Comment by jrounds** [comment] 2020-09-03 17:27
Looks like insider works again for me (same test mentioned above).


Version: 1.49.0-insider
Commit: 8c9b4015feb0297d99c8051c35e85d208ffe83e3
Date: 2020-09-03T05:43:53.229Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Comment by DougPlumley** [comment] 2020-09-03 17:35
> @connor4312 yeah I could never repro this. @DougPlumley it would be great if you could tell us if it's working now for you on Insiders.

I can't reproduce it anymore even if I massively scale up to 10K+ characters, this is awesome!  Thank you!

**Comment by stevenr3** [comment] 2020-09-03 20:05
It still doesn't work for me on Win7 - there is still some threshold above which can't be pasted into Terminal:
Short selection works:
![image](https://user-images.githubusercontent.com/5964598/92161687-0dee3f00-ee85-11ea-8cf2-0a0c7370a972.png)
Long selection doesn't work (nothing appears in Terminal window):
![image](https://user-images.githubusercontent.com/5964598/92161759-28c0b380-ee85-11ea-824b-a911b38181dd.png)

Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by Tyriar** [comment] 2020-09-03 20:44
@stevenr3 you're using VS Code stable, not [insiders](https://code.visualstudio.com/insiders/).

**Comment by stevenr3** [comment] 2020-09-03 21:37
@Tyriar Thanks - I had no idea about insiders.
I just retested with today's insiders build and it works great. 
I can now paste long text into terminal, and most importantly for me, cmake compile active file now works :+1: 

Version: 1.49.0-insider (user setup)
Commit: e2f63c9013a2b55db2d593d45b8c8aecdbe70f25
Date: 2020-09-03T17:27:16.893Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 6.1.7601
