### ISSUE TITLE
rg.exe take all cpu

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/vscode#36414] opened 2017-10-17 12:14 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
autofoldyeah|bob|1.0.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
vscode-svgviewer|css|1.4.3
vue-peek|dar|1.0.2
vscode-eslint|dba|1.3.2
python|don|0.7.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.2.1
phpunit|ema|2.1.1
json-tools|eri|1.0.2
tortoise-svn|fan|0.1.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
auto-close-tag|for|0.5.1
auto-rename-tag|for|0.0.14
webpack-snippets|gog|0.0.3
vue-snippets|hol|0.1.5
emoji-code|idl|0.3.0
phpcs|ika|0.7.0
webpack|jer|2.0.2
php-namespace-resolver|Meh|0.8.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.3.1
vuejs-extension-pack|mub|0.2.1
php-docblocker|nei|1.3.2
vetur|oct|0.9.11
material-icon-theme|PKi|2.2.2
vscode-css-peek|pra|1.3.1
CSSLint|ray|0.0.3
sass-indented|rob|1.4.4
vue-vscode-snippets|sdr|1.0.3
markdown-preview-enhanced|shd|0.2.9
stylelint|shi|0.30.0
guides|spy|0.9.0
vscode-todo-highlight|way|0.5.11
vscode-import-cost|wix|2.5.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.11.0

---

Steps to Reproduce:

1.git clone https://github.com/googlearchive/flipjs
2.cd flipjs
3.code .
4.npm i
5.reopen flipjs

![2017-10-16_101813](https://user-images.githubusercontent.com/12824616/31664355-af75a9f4-b377-11e7-8ce9-600bbfde5db8.png)
![2017-10-16_101833](https://user-images.githubusercontent.com/12824616/31664356-afb7f57a-b377-11e7-9a3a-b3919fbc0f8e.png)

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment] 2017-10-17 21:25
Are you using cnpm (or similar that uses symlinks) by chance?

**Comment by deepkolos** [comment] 2017-10-18 02:23
@chrisbenti yes , i use cnpm

**Comment by chrisbenti** [comment] 2017-10-18 03:53
Probably looking for @chrmarti

**Comment by chrmarti** [comment] 2017-10-19 14:59
Duplicate of #35659. Using `cnpm install --by=npm` to install a new `node_modules` folder should work around it.

**Closed by chrmarti** 2017-10-19 14:59 UTC
Labels: needs more info, search
