### ISSUE TITLE
Feature request: Inlay Hints for return values for all languages

### ISSUE THREAD

**Issue by calebdiaz** [microsoft/vscode#152605] opened 2022-06-19 23:18 UTC
Inlay Hints for return values for all languages, or at least JS/TS, Python, Golang, Lua etc
show additional information inline with the source code. 

hints for

types of local variables
(return) types of chained expressions
This is already implemented but some extensions for specific languages, but it would be much better as a vscode feature for all programming languages.

**Comment by mjbvz** [comment] 2022-06-20 20:47
Duplicate of #152599

**Closed by mjbvz** 2022-06-20 20:47 UTC
