### ISSUE TITLE
Button to disable excludes in quickopen

### ISSUE THREAD

**Issue by nesl247** [microsoft/vscode#59982] opened 2018-10-04 16:50 UTC
In PhpStorm, WebStorm, etc. the ability to search for a file, object, etc. does not limit you to only non-excluded files. 

![image](https://user-images.githubusercontent.com/1037526/46489579-c6ac2f00-c7d3-11e8-9029-63b94f1211ba.png)

As you can see, there is the "Include non-project items" checkbox. This is never checked by default. It would be great if VS Code implemented this feature. By default, we don't want to show classes from composer libraries for example, but we do need to be able to search them on occasion.

This should be added for symbol and file search.

**Comment by roblourens** [comment] 2018-10-04 18:02
We have considered a toggle button for whether to apply the exclude settings

**Comment by nesl247** [comment] 2018-10-04 18:29
Please make it work like Jetbrain's dialog though in that if you press the same combination again, it triggers the checkbox.

**Comment by roblourens** [comment] 2018-10-05 14:20
I think this needs some ux work and discussion on our side, I'm not really convinced it's needed.

**Comment by roblourens** [comment] 2018-10-05 14:20
But thanks for your enthusiasm :)

**Comment by nesl247** [comment] 2018-10-05 14:36
Can you explain why you aren’t convinced it’s needed? How do you deal with this situation, which I would imagine impacts almost every user.

**Comment by roblourens** [comment] 2018-10-05 16:34
I'm sure this is useful for some users but our quick open UI is very simple and lightweight and I'd like to keep it that way if at all possible

**Comment by cdmihai** [comment] 2019-06-12 20:22
I run into this limitation a lot. My build produces a lot of stuff, and I often want to browse the build artifacts:
- test results. I can do a recursive search string, and that UI lets me ignore .gitignore. But sometimes I also want to go to specific test result files via `go to file`, and can't
- my build also produces test data, which I want to browse from time to time. I know exactly what the file name is, but I have to use the command line because I can't quickly jump to it via vscode

**Comment by roblourens** [comment] 2019-10-09 23:07
Duplicate of https://github.com/microsoft/vscode/issues/15604

**Closed by roblourens** 2019-10-09 23:07 UTC
Labels: feature-request, search
