### ISSUE TITLE
Universal Format Selection As Language

### ISSUE THREAD

**Issue by cjudd** [Microsoft/vscode#21371] opened 2017-02-24 15:29 UTC
I have several scenarios where I have multiple language types in a single file such as plain text or markdown where I would like to format just a selected code block. For example, I might be in markdown and want to just change the code block section using the json or xml formatter. Today, I have to change the entire language to that language of json or xml, use the format select and switch it back to markdown. I would love to be able to tell it to format selection as a specific language format.

- VSCode Version: 1.9.1
- OS Version: OS X El Capitan

Steps to Reproduce:

1. Create a markdown file.
2. Create a code section using 
```
{"languages":["javascript","java", "sql", "xml"]}
```
3. Select the line just containing the json code and try to format it.

**Comment by aeschli** [comment] 2017-02-27 08:25
The markdown extension has to either embed a JSON formatter or call the JSON extension with a virtual document.

**Comment by mjbvz** [comment] 2017-02-28 00:21
This is related to #639 and seems like a duplicate of #14447. We don't have a good story for managing mixed language files and I don't think that the markdown extension should be in the business of handling json formatting specifically. @aeschli Has there been any further discussion of supporting this type of mixed language scenario?

**Comment by aeschli** [comment] 2017-02-28 08:30
My comment https://github.com/Microsoft/vscode/issues/14447#issuecomment-262736975 is still my thinking after my experience on HTML.

**Comment by cjudd** [comment] 2017-02-28 19:31
I don't feel like my request is the same as #14447. I am not asking to format the whole file and determine and format different languages appropriately. I know that is a difficult problem. I am just asking if a manual selection is made that a user can format just the selection as the format they want. A particular use case, if an author is writing a programming book in markdown and they have code examples in Java, JavaScript, HTML, etc they can manually format as the desired selection rather than changing the entire file format to format the selection and switch back to markdown.

**Comment by jrieken** [comment] 2017-06-27 15:24
closing as dupe of #27073

**Closed by jrieken** 2017-06-27 15:24 UTC
Labels: feature-request, format
