### ISSUE TITLE
I downloaded microsoft vs code version 1.66.2 but due to some issues kept reinstalling it again and again and now suddenly while deleting vs code through 'unins000' some files including "code" couldnt be deleted and a pop up said that these files can be deleted manually but when i tried to delete them  it said that it couldnt be deleted because the files open in microsoft visual studio code and thus like this 4 files are now in the folder which i am unable to delete. i have tried downloading vs code again and merging it with previous folder but that didnt did any thing. Pls help as i am unable to find any soln for it anywhere

### ISSUE THREAD

**Issue by sarth2006** [microsoft/vscode#148473] opened 2022-04-30 09:03 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by sarth2006** [comment] 2022-04-30 09:09
> Does this issue occur when all extensions are disabled?: Yes/No
> no extension was disabled
> * VS Code Version: 1.66.2
> * OS Version:
> 
> Steps to Reproduce:

**Comment by mjbvz** [comment] 2022-09-09 21:59
Closing as the issue is unclear

Please follow [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) to submit a proper issue report. This should include:

- What are you trying to do?
- What went wrong?
- Steps to reproduce the problem

**Closed by mjbvz** 2022-09-09 21:59 UTC
Labels: triage-needed
