### ISSUE TITLE
Variable name can not be `constructor` or `__proto__`

### ISSUE THREAD

**Issue by minggo** [Microsoft/vscode#3655] opened 2016-03-03 06:49 UTC
I am writing a debugger adapter, and i found if the variable name is `constructor`, then it can not be displayed in Variable view.

<img width="273" alt="variable-issue" src="https://cloud.githubusercontent.com/assets/488203/13486777/fd5b5aee-e14e-11e5-91e4-7abd33414363.png">

And the return value is `[{"name":"constructor","value":"Function","variablesReference":1009}]`

**Comment by isidorn** [comment] 2016-03-03 08:51
On the vscode side we are not doing anything special with the variable names since VSCode is language agnostic.
What adapter are you using, do you use something on top of node-debug?
Assigning to @weinand since he might have an idea

**Comment by minggo** [comment] 2016-03-03 08:58
This is my own adapter, and the view is the client view. The `launch.json` of the client view is

```javascript
{
    "version": "0.2.0",
    "debugServer": 4711,

    "configurations": [{
        "name": "mock test",
        "request": "launch",
        "type": "node",
        "request": "attach",
        "port": "5086",
        "stopOnEntry": false
    }
}
```

**Comment by weinand** [comment] 2016-03-03 09:08
@isidorn I can easily reproduce. Since the response object is OK, I suspect that somewhere in the UI the variable name 'constructor' is stored as an object property which collides with the JavaScript reserved name 'constructor'. I remember we had this issues already with the variable names "__prototype__". IIRC you had to prefix variable name to avoid the clash.

![2016-03-03 10-04-03](https://cloud.githubusercontent.com/assets/1898161/13489525/d485707c-e127-11e5-88d8-87eb5d396a5b.png)

**Comment by weinand** [comment] 2016-03-03 09:23
@isidorn variables with the name `__proto__` don't work either.

**Comment by minggo** [comment] 2016-03-03 09:26
@weinand 
Yep, it also met `__proto__` issue too.

**Comment by weinand** [comment] 2016-03-29 11:49
@isidorn Today I was running again into the problem that I cannot inspect the "__proto__" property in VS Code. Could you please consider to use Maps for storing variables? Those don't suffer from the problem that some variable names collide with some builtin object properties in JavaScript.

**Closed** 2016-03-30 10:19 UTC
Labels: bug, debug, important
