### ISSUE TITLE
Latest update broke some stuff

### ISSUE THREAD

**Issue by DetroitWhiskey136** [microsoft/vscode#130337] opened 2021-08-07 21:59 UTC
Issue Type: <b>Bug</b>

Some things I noticed last night after vscode updated.

I have CMD set as my default integrated terminal, however powershell is still what opens... not sure if there's a new setting I have to set but this is rather annoying.

Most of my extensions appear to be installed however none of them are loaded, I found a way around this by uninstalling them then installing again, but even this janky way does not resolve the issue entirely because the change does not persist between sessions.

VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:41:50.275Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (25.32GB free)|
|Process Argv|--crash-reporter-id 12d919ce-67a8-4866-bd8c-471946253d31|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
Bookmarks|ale|13.1.0
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
codestream|Cod|11.0.13
supersharp|cra|0.1.4
vscode-eslint|dba|2.1.23
npm-browser|den|1.1.0
fivem-lua|dha|1.0.1
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
flow-for-vscode|flo|1.9.1
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.29.0
todo-tree|Gru|0.0.213
output-colorizer|IBM|0.1.2
discord-vscode|icr|5.7.0
easy-snippet|inu|0.6.3
customize-ui|ioc|0.1.54
monkey-patch|ioc|0.1.15
vscode-essentials|jab|1.6.0
hungry-delete|jas|1.6.0
search-node-modules|jas|1.3.0
intellij-idea-keybindings|k--|1.4.5
ts-debug|kak|0.0.6
rn-full-pack|kel|0.7.0
vscode-format-context-menu|lac|1.0.4
jsdoc|lll|1.0.3
asm-code-lens|maz|1.8.1
vscode-language-babel|mgm|0.0.31
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.5.1
vsliveshare|ms-|1.0.4673
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.6.0
color-highlight|nau|2.4.0
gremlins|nho|0.26.0
vetur|oct|0.34.1
cargo|pan|0.2.3
vscode-print|pdc|0.9.8
explorer-exclude-vscode-extension|Red|1.2.0
LiveServer|rit|5.6.1
react-snippets|run|0.1.3
rust|rus|0.7.8
crates|ser|0.5.9
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
jsdoc-view|shi|0.0.5
code-spell-checker|str|1.10.2
lua|sum|2.3.4
control-snippets|svi|1.9.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
codetour|vsl|0.0.58
gistfs|vsl|0.3.0
gitblame|wad|8.1.0
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1
vscode-intelli-refactor|ypr|0.1.2
linkerscript|Zix|1.0.2
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30348854
dockerwalkthru:30348713

```

</details>

**Comment by DetroitWhiskey136** [comment] 2021-08-07 22:02
would appear the second issue has already been reported, #130333

**Comment by gjsjohnmurray** [comment] 2021-08-07 22:04
First is duplicate of #130268

**Comment by DetroitWhiskey136** [comment] 2021-08-07 22:04
oh you are correct i'll close this then

**Closed** 2021-08-07 22:04 UTC
