### ISSUE TITLE
clicking readme on the install menu closes installation pane

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5092] opened 2016-04-08 11:38 UTC
- VSCode Version:1.8.2
- OS Version:ubuntu 15.10

Steps to Reproduce:

1. ctrl +shift + p open the pane
2. type ext install
3. search for extensions and click one of their readme button
4. the pane will close after clicking

**Comment by joaomoreno** [comment] 2016-04-08 14:19
Duplicate of #637

**Closed by joaomoreno** 2016-04-08 14:19 UTC
