### ISSUE TITLE
Request textDocument/documentLink failed with message: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by doncullen** [Microsoft/vscode#15185] opened 2016-11-08 16:20 UTC
- VSCode Version:  1.7.1
- OS Version:  Ubuntu 16.10

Steps to Reproduce:

1.   Open any HTML file that wasn't produced by VSC
2.   Error displays.

Error:
> [Error - 10:14:18 AM] Request textDocument/documentLink failed.
>   Message: Request textDocument/documentLink failed with message: Path must be a string. Received undefined
>   Code: -32603 

Notes: 
Wrote a simple HTML file that included Javascript code and CSS code in VSC, got no error.  Saved it, closed VSC, and opened a new VSC session with all extensions enabled, then opened that same file I created earlier, no error.  So it appears it only occurs with files that was not created by VSC. 

Ran VSC via terminal `code --disable-extensions` and tried opening file that was not created by VSC, same error.  So it's definitely not an extension. 

I've included screenshot of error.

![screenshot_20161108_101743](https://cloud.githubusercontent.com/assets/2024899/20107001/a1894650-a59c-11e6-8baa-2d689d3da773.png)

**Comment by charlesgiroux** [comment] 2016-11-08 17:53
Having the same issue.

OS: Windows 10 pro 64bit

It happens not only with files created by another text editor, but also if I create a new file and copy/paste from another editor/source.

**Comment by aeschli** [comment] 2016-11-08 18:01
duplicate of #15018.

I you can add a source example with the problematic src attribute that would be great

**Closed by aeschli** 2016-11-08 18:01 UTC

**Comment by dbussiere** [comment] 2017-03-08 15:57
same problem here

**Comment by YJChan** [comment] 2017-04-23 14:26
having same problem here, after update some of my extension. But did some testing, like disable those extension, problem still exist. I'm using elementary os loki. vs code v1.11.
