### ISSUE TITLE
Using Ctrl+Mouse wheel to zoom image jumps from 10% to 1010%

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#42445] opened 2018-01-30 11:34 UTC
Testing https://github.com/Microsoft/vscode/issues/42130

Testing under Windows, Surface Book with external mouse.

**Comment by mjbvz** [comment] 2018-02-01 01:12
Sounds like a duplicate of #42486

Please try out the next insiders build. I adjusted how zooming scales over all and adjusted the sensitivity

**Closed by mjbvz** 2018-02-01 01:12 UTC
Labels: *duplicate
