### ISSUE TITLE
Multiple accounts in sync state

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#96610] opened 2020-04-29 16:31 UTC
Re #96226

* Turn on Preference Sync, login with a new GitHub account A
* Turn off Preference Sync
* Turn on Preference Sync, login with a new Microsoft account B
* Turn off Preference Sync
* Turn on Preference Sync, login with a new GitHub account C
* Turn off Preference Sync
* Turn on Preference Sync, login with a new Microsoft account D
* Turn off Preference Sync
* Click the Account Gear icon, choose the account C, sign out --> warning, account C is now used by Preference Sync. Escape.
* Click the Account Gear icon, choose the account D, sign out --> warning, account D is now used by Preference Sync. Escape.

It's confusing to me why both Microsoft and GitHub account is in sync state.

**Comment by RMacfarlane** [comment] 2020-05-11 23:53
Duplicate of https://github.com/microsoft/vscode/issues/96358

**Closed by RMacfarlane** 2020-05-11 23:53 UTC
