### ISSUE TITLE
Git modifications should be selectable

### ISSUE THREAD

**Issue by maoschanz** [microsoft/vscode#132790] opened 2021-09-09 18:59 UTC
let's say i've edited a paragraph, and suddenly i want to revert a small part of it. Only a small part, i don't want to lose my entire work. So i preview the changes (with a click on the colored side of the editor):

- On a good editor, i could select the part i want in the preview to copy it, close the preview, and paste it where i need within my current work
- But for some reason here there is only a textview where selection is impossible. For some reason it's possible to copy the entire thing to my clipboard, but not just the bit of it i need.

Would it be possible to make this modal textview useful and usable?

**Comment by IllusionMH** [comment] 2021-09-09 19:22
I think it's basically duplicate of #8226 (please upvote it if it's same problem)

In the meantime you can use lightbulbs that appear when you hover at the edge and select copy line or all deleted section.
See https://github.com/microsoft/vscode/issues/8226#issuecomment-528103843 for example.

**Closed** 2021-09-09 19:38 UTC
