### ISSUE TITLE
`Terminal: Run Selected Text In Active Terminal` runs only first line in IPython

### ISSUE THREAD

**Issue by ply** [Microsoft/vscode#57392] opened 2018-08-28 12:08 UTC
Issue Type: <b>Bug</b>

**Steps to reproduce:**
 - run `ipython` in integrated terminal
 - select more than one line of python code in editor
 - run action `Terminal: Run Selected Text In Active Terminal`

**Expected result:** all lines executed.

**Current result:** executes only first line of selection.

**Note:** it works as expected with bare `python`.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 15.6.0

**Comment by Tyriar** [comment] 2018-08-30 14:18
Can you post a screenshot or the text selected and what happens in the terminal?

**Comment by ply** [comment] 2018-08-30 19:33
Sure :)
![screenshot](https://user-images.githubusercontent.com/1458183/44874673-3c385300-ac9c-11e8-9cbc-a66a03ca3bbc.png)

**Comment by Tyriar** [comment] 2018-08-30 22:59
I suspect this is a bug with `ipython` eating the keypresses while print(1) is running. It could also be related to how the terminal emulation works on Windows and in that case this can be closed as a duplicate of https://github.com/Microsoft/vscode/issues/45693

**Closed by Tyriar** 2018-08-30 22:59 UTC
Labels: integrated-terminal, needs more info
