### ISSUE TITLE
Cannot download vscode for extension testing from URL "https://vscode-update.azurewebsites.net/api/releases/stable"

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vscode#62429] opened 2018-11-02 01:40 UTC
Probably related to #62427 

- VSCode Version: ^1.26.0
- OS Version: Windows 10

Steps to Reproduce:

[View results from one of our builds here.](https://vscode-python.visualstudio.com/VSCode-Python/_build/results?buildId=1827&view=logs)

1. Download sources for vscode-python. `C:\dev> git clone git@github:Microsoft/vscode-python`
2. CD into the vscode-python dir. `C:\dev> cd vscode-python`
3. Run npm CI. `C:\dev\vscode-python> npm ci`

Post-install step will fail with 502.

Does this issue occur when all extensions are disabled?: Yes

Pertinent log failure from Azure DevOps pipeline:

```
2018-11-02T00:59:22.0699680Z Error installing vscode.d.ts: Error: Request returned status code: 502
2018-11-02T00:59:22.0699739Z Details: <!DOCTYPE html>
2018-11-02T00:59:22.0699799Z <html>
2018-11-02T00:59:22.0699848Z <head>
2018-11-02T00:59:22.0699902Z <title>Error</title>
2018-11-02T00:59:22.0699960Z <style>
2018-11-02T00:59:22.0700007Z     body {
2018-11-02T00:59:22.0700064Z         width: 35em;
2018-11-02T00:59:22.0700116Z         margin: 0 auto;
2018-11-02T00:59:22.0700175Z         font-family: Tahoma, Verdana, Arial, sans-serif;
2018-11-02T00:59:22.0700239Z     }
2018-11-02T00:59:22.0700287Z </style>
2018-11-02T00:59:22.0700341Z </head>
2018-11-02T00:59:22.0700387Z <body>
2018-11-02T00:59:22.0700559Z <h1>An error occurred.</h1>
2018-11-02T00:59:22.0700792Z <p>Sorry, the page you are looking for is currently unavailable.<br/>
2018-11-02T00:59:22.0700847Z Please try again later.</p>
2018-11-02T00:59:22.0700908Z <p>If you are the system administrator of this resource then you should check
2018-11-02T00:59:22.0700971Z the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
2018-11-02T00:59:22.0701034Z <p><em>Faithfully yours, nginx.</em></p>
2018-11-02T00:59:22.0701081Z </body>
2018-11-02T00:59:22.0701129Z </html>
2018-11-02T00:59:22.0701163Z 
2018-11-02T00:59:22.0701218Z npm verb lifecycle python@2018.10.0-beta~postinstall: unsafe-perm in lifecycle true
2018-11-02T00:59:22.0701673Z npm verb lifecycle python@2018.10.0-beta~postinstall: PATH: C:\npm\prefix\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\a\1\s\node_modules\.bin;C:\hostedtoolcache\windows\node\8.11.2\x64;C:\Users\VssAdministrator\AppData\Roaming\Python\Python37\Scripts;C:\hostedtoolcache\windows\Python\3.7.0\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.0\x64;C:\agents\2.141.1\externals\git\cmd;C:\tools\mingw64\bin;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\Java\jdk1.8.0_181\bin;C:\npm\prefix;C:\hostedtoolcache\windows\Ruby\2.5.0\x64\bin;C:\Go1.11\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files (x86)\Subversion\bin;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps
2018-11-02T00:59:22.0702200Z npm verb lifecycle python@2018.10.0-beta~postinstall: CWD: D:\a\1\s
2018-11-02T00:59:22.0702278Z npm info lifecycle python@2018.10.0-beta~postinstall: Failed to exec postinstall script
2018-11-02T00:59:22.0702347Z npm verb teardown shutting down workers.
2018-11-02T00:59:22.0702405Z npm info teardown Done in 0.002s
2018-11-02T00:59:22.0702467Z npm verb stack Error: python@2018.10.0-beta postinstall: `node ./node_modules/vscode/bin/install`
2018-11-02T00:59:22.0702532Z npm verb stack Exit status 1
2018-11-02T00:59:22.0702596Z npm verb stack     at EventEmitter.<anonymous> (C:\npm\prefix\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
2018-11-02T00:59:22.0702672Z npm verb stack     at emitTwo (events.js:126:13)
2018-11-02T00:59:22.0702730Z npm verb stack     at EventEmitter.emit (events.js:214:7)
2018-11-02T00:59:22.0702804Z npm verb stack     at ChildProcess.<anonymous> (C:\npm\prefix\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2018-11-02T00:59:22.0702868Z npm verb stack     at emitTwo (events.js:126:13)
2018-11-02T00:59:22.0702923Z npm verb stack     at ChildProcess.emit (events.js:214:7)
2018-11-02T00:59:22.0702994Z npm verb stack     at maybeClose (internal/child_process.js:925:16)
2018-11-02T00:59:22.0703057Z npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2018-11-02T00:59:22.0703119Z npm verb pkgid python@2018.10.0-beta
2018-11-02T00:59:22.0703168Z npm verb cwd D:\a\1\s
2018-11-02T00:59:22.0703219Z npm verb Windows_NT 10.0.14393
2018-11-02T00:59:22.0703288Z npm verb argv "C:\\hostedtoolcache\\windows\\node\\8.11.2\\x64\\node.exe" "C:\\npm\\prefix\\node_modules\\npm\\bin\\npm-cli.js" "ci"
2018-11-02T00:59:22.0703422Z npm verb node v8.11.2
2018-11-02T00:59:22.0703470Z npm verb npm  v6.4.1
2018-11-02T00:59:22.0703516Z npm ERR! code ELIFECYCLE
2018-11-02T00:59:22.0703568Z npm ERR! errno 1
2018-11-02T00:59:22.0703625Z npm ERR! python@2018.10.0-beta postinstall: `node ./node_modules/vscode/bin/install`
2018-11-02T00:59:22.0703684Z npm ERR! Exit status 1
2018-11-02T00:59:22.0703729Z npm ERR! 
2018-11-02T00:59:22.0703780Z npm ERR! Failed at the python@2018.10.0-beta postinstall script.
2018-11-02T00:59:22.0703858Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-11-02T00:59:22.0703914Z npm verb exit [ 1, true ]
2018-11-02T00:59:22.0703967Z npm timing npm Completed in 40774ms
2018-11-02T00:59:22.0703999Z 
2018-11-02T00:59:22.0704047Z npm ERR! A complete log of this run can be found in:
2018-11-02T00:59:22.0704112Z npm ERR!     C:\npm\cache\_logs\2018-11-02T00_59_21_888Z-debug.log
```

**Comment by Pyxelx** [comment] 2018-11-02 01:41
this is related to my issue and afew others
@ https://github.com/Microsoft/vscode/issues/62428

the download domains are completely broken/down at the moment.

**Comment by d3r3kk** [comment] 2018-11-02 01:41
Note: The URL gets redirected to https://update.code.visualstudio.com/api/releases/stable if you paste it into a browser.

Thanks for looking into this!

**Comment by Pyxelx** [comment] 2018-11-02 01:42
hope they fix this soon. was looking to download stable but can't due to the domains being down.

**Comment by mjbvz** [comment] 2018-11-02 01:44
Duplicate of #62427

**Closed by mjbvz** 2018-11-02 01:44 UTC
