### ISSUE TITLE
Allow extensions to run custom terminals

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#8078] opened 2016-06-24 00:31 UTC
For the [julia](https://github.com/JuliaEditorSupport/julia-vscode) extension, I'd like to be able to add a julia terminal to VS code so that we could have the julia REPL inside VS code.

I think this could be pretty simple: essentially my extension would just need some way to tell VS code that it should add one more terminal window, and allow me to specify a command line that starts that julia terminal.

Bonus points would be if I could for example start that terminal in a hidden state, so the julia process would start, the output would already be captured by the terminal, but the panel would not be visible. And the maybe provide an API that allows my extension to toggle the visibility of the panel, or something like that.

**Comment by Tyriar** [comment] 2016-06-24 07:07
Duplicate of https://github.com/Microsoft/vscode/issues/547

**Closed by Tyriar** 2016-06-24 07:07 UTC

**Comment by davidanthoff** [comment] 2016-06-24 15:46
Ah, thanks, I didn't see that one! Could you add the integrated-terminal to #547? I missed #547 because I only looked through all the integrated-terminal issues for duplicates.

**Comment by Tyriar** [comment] 2016-06-24 18:02
@davidanthoff done :smiley:
