### ISSUE TITLE
Add a setting to not save before running a debug config

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#117080] opened 2021-02-19 19:48 UTC
There exists a setting `task.saveBeforeRun` which controls whether all files are saved before running a task.
There should be a similar setting for when starting a debug session - `debug.saveBeforeRun`.

I ran into this and at first couldn't figure out why some of my files which I intentionally left unsaved, kept getting auto-saved.

I think this is the relevant code:
https://github.com/microsoft/vscode/blob/5d2c9bf29962533f37f34c36c58d4628a5c895a4/src/vs/workbench/contrib/debug/browser/debugService.ts#L282-L287

I think the same options of `always`/`prompt`/`never` should suffice, but we could also have `onlyCurrentFile` or something, or `onlyWorkspace` (since the files I had problems with weren't part of my workspace).

**Comment by isidorn** [comment] 2021-02-22 08:15
Duplicate of https://github.com/microsoft/vscode/issues/114890

**Closed by isidorn** 2021-02-22 08:15 UTC
Labels: debug
