### ISSUE TITLE
cant fold block comment

### ISSUE THREAD

**Issue by efa91** [Microsoft/vscode#59173] opened 2018-09-23 03:02 UTC
Issue Type: <b>Bug</b>

i usually write endpoints like this, but after vscode update coming, i cant fold comments.

not works, example:
```
/**
 *
 * NOT WORKS
 *
 * @api {PUT} /cars/:carId cars update
 * @apiName Cars
 * @apiGroup Cars
 * @apiVersion 1.0.0
 */
app.put('/:carId', updateHandler);
```

------------------------------

but the feature fold comment will work if I put block comments on the function.
works, example:
```
  /**
   *
   * THIS WORKS
   * @param {*} travellerId 
   */
  async detail(travellerId) {
  }
```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.0.0

**Comment by aeschli** [comment] 2018-09-24 19:11
That's TypeScript, correct?

**Comment by mjbvz** [comment] 2018-09-24 21:31
Duplicate of https://github.com/Microsoft/TypeScript/issues/22732

**Closed by mjbvz** 2018-09-24 21:31 UTC
Labels: editor, editor-folding
