### ISSUE TITLE
Menu does not automatically close when it loses focus: a less important error

### ISSUE THREAD

**Issue by freezestudio** [Microsoft/vscode#68313] opened 2019-02-09 14:46 UTC
- VSCode Version: 1.31.0
- OS Version: windows 10

Steps to Reproduce:

1. Open the Help menu and select the release notes.
2. Expand any menu again
3. Any click, right click, or select operation on this content page will not automatically close the open menu.

Does this issue occur when all extensions are disabled?: Yes

**Comment by freezestudio** [comment] 2019-02-09 14:53
Do not repeat with the above questions

**Comment by mjbvz** [comment] 2019-02-12 01:29
Duplicate of #68335 I believe

**Comment by mjbvz** [comment] 2019-02-12 01:30
Actually will keep open to make sure this is resolved by the fix

**Closed** 2019-02-13 19:01 UTC
Labels: webview
