### ISSUE TITLE
An invalid file that an extension tried to open will continue to be loaded every time a folder is launch

### ISSUE THREAD

**Issue by poshcodebear** [microsoft/vscode#92110] opened 2020-03-05 20:10 UTC
Version: 1.43.0-insider (system setup)
Commit: b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0
Date: 2020-03-05T00:59:24.612Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Problem: A blank editor with an invalid path opens every time you open a folder if you had that folder open when an extension previously tried to open this invalid file.  You can close the file, but it will reappear every time you reopen that folder going forward.

Initially noticed in 1.42.1, confirmed in current build of Insiders

Steps to Reproduce:

WARNING: I recommend performing these steps while you have VSCode opened to an empty throw-away directory as I don't know any way to undo this once done.  If you do it with no folder or workspace open, it will affect your empty editor and I don't know if there's a way to get rid of it short of reinstalling.

1. Install the extension `vscode-journal`
Note: there is a weird bug in that extension handling variables in paths; this is not a report for _that_ bug, but that is the only way I know to trigger the bug I'm reporting
2. Add the following setting to user settings: `"journal.base": "~/OneDrive/Documents/Journal"`
Note: I don't know if the path needs to be valid to work or not; probably not, but I've not tested with a completely invalid path
3. Reload the window
4. Attempt to open the journal for "today" by pressing Ctrl+Shift+J and select the "Today" entry; you should get an error that it failed to open the entry
Note: this should work with any entry you try to open as well
5. Reload the window again; you should now have a blank open editor pointing to a file that does not exist with an invalid path

Every time you open this folder going forward, regardless of closing the editor or changes to settings or extensions (including removing all extensions and all settings), that editor will open with it.

Does this issue occur when all extensions are disabled?: Yes

I discovered this issue while trying to find a way to get the journal to save to a spot using the home variable so I could place it in my OneDrive and have it sync to multiple systems where my username is different (I use Settings Sync).  I've found a different way to make that work for me, but these bogus editors will not go away.

![image](https://user-images.githubusercontent.com/6439773/76021265-d86a9800-5ed9-11ea-9b84-b8d5bc35d86a.png)
An example of two such files that now load every single time I open my `ps` folder; I'm not able to get rid of them

**Comment by bpasero** [comment] 2020-03-06 06:49
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by poshcodebear** [comment] 2020-03-06 18:53
I mean, I literally uninstalled every extension (which I mentioned in my description), but I just went ahead and ran Insiders with --disable-extensions (even though it currently has zero installed) and the file still pops up.

I don't know of a way to replicate this issue without using an extension, but the fact that this invalid file persists in opening every single time you re-open the folder (or empty window if you did the above steps without anything open), even though you closed the folder (or windows without any folder loaded) with the invalid file already closed suggests this is a bug in Code itself.  It should not be persisting a file that was not open when you closed the editor, especially not in such a way that you can never get rid of it short of uninstalling.

Even if this is solely caused by a misbehaving extension, it persisting after all extensions and all settings are removed would mean that Code is allowing extensions to do something that it shouldn't.

As it is, I've done everything I can think of to get rid of these files that keep popping up every time I open my main development environment, to the point that I'm tempted to either move my environment to a different location or completely reinstall Code.

**Comment by bpasero** [comment] 2020-03-07 06:52
Is the file dirty or not? VSCode is always restoring files that are not saved because of unsaved data.

**Comment by poshcodebear** [comment] 2020-03-09 17:34
I believe they are marked dirty, it does ask if I want to save when I close them out.  That said, they don't actually exist on disk, and the paths to them are invalid; also, I'm closing them before closing the window or folder, so it should not be trying to restore them at that point.

**Comment by bpasero** [comment] 2020-03-10 06:56
@poshcodebear to clarify, you close the dirty editor, you get a dialog and you select "Don't Save" and the editor closes, but comes back after reload?

If that is true, can you see if anything gets logged to the developer tools "Console" when you do Help > Toggle Developer Tools when you do these steps?

**Comment by poshcodebear** [comment] 2020-03-10 17:08
I didn't see anything when I launched, so I was going to try to replicate it with a fresh install...only to learn it survives reinstall.  So, I uninstalled again and hunted down any straggler folders and found ~/AppData/Roaming/Code - Insiders remains, so I renamed it and reinstalled, which eliminated the bad file loading.

So, I took a look at what was different, and under storage.json, it had the following entries:
```json
"windowsState": {
        "lastActiveWindow": {
            "folder": "file:///e%3A/temp/bugtest",
            "backupPath": "c:\\Users\\<redacted>\\AppData\\Roaming\\Code - Insiders\\Backups\\3aedb62919e93be762075179e673cb14",
            "uiState": {
                "mode": 1,
                "x": 2398,
                "y": 186,
                "width": 1024,
                "height": 768
            }
        },
        "openedWindows": []
    },
    "openedPathsList": {
        "workspaces3": [
            "file:///e%3A/temp/bugtest"
        ],
        "files2": []
    },
    "pickerWorkingDir": "E:\\temp"
```

Okay, so far so good...I went and checked under Backups and found two folders, the one listed above and another that I'm assuming is launched with a blank window.  Each had two folders, an empty one named `vscode-userdata` and one called `untitled` with a single file with a long hex name (`594a4a9d82a277a899d4713a5b08f504`, both were named the same) and no extension, containing the following:

```markdown
untitled:c%3A%5CProgram%20Files%5CMicrosoft%20VS%20Code%20Insiders%5C~%5COneDrive%5CDocuments%5CJournal%5C2020%5C03%5C05.md
# Thursday, March 5, 2020

## Tasks

## Notes


# Thursday, March 5, 2020

## Tasks

## Notes
```

So, I'm not sure what mechanism creates these entries or is supposed to remove them, but apparently, once they're created, they don't go away.

I kept digging.

I managed to recreate the issue _without_ using any extensions this time by basically replicating the changes it made to `storage.json` and `Backups/workspaces.json`, creating the folders under `Backups`, and adding the file with the long hex name and the code as I posed inside it.

This successfully replicated the issue, and this copy of VSCode Insiders now launches with this invalid file every single time.  The only way to get rid of it is manually scraping it out of the storage.json and Backups directory.

Here's something interesting: I watched the folder when I launched and it created a _new_ long hex file in the Backups folder alongside the long hex file name (this one was named `79b5a6f61a846b41bc7c91c9b1cd6163`, though I don't think that part is particularly important) containing a single line: `untitled:/c%3A%5CProgram%20Files%5CMicrosoft%20VS%20Code%20Insiders%5C~%5COneDrive%5CDocuments%5CJournal%5C2020%5C03%5C05.md%0D`.  When I closed the file without saving, _that_ file gets removed, but _not_ the other one, which is why it's coming back every time: it never seems to clear the file out of Backups.

However it gets there, it certainly should not _stay_ there.

At this point, I feel like I've provided ample details for you to replicate the issue on your side and you'd probably be a lot better equipped to troubleshoot this than I would (I'm mostly a PowerShell jockey so we're quite far outside my lane here).  If you're having trouble replicating my issue, I'll be happy to help with that, but at this point I really think that should be the focus here.

**Comment by bpasero** [comment] 2020-03-11 06:22
Thanks, great analysis. I will try to reproduce as well. I wonder if this could be some artifact of a very old version of VSCode starting with this bad path and then a newer version of VSCode hashing the path in a different way so that we fail to remove this entry. This would be something I cannot easily fix. Could it be that you recently updated from an very old version?

**Comment by poshcodebear** [comment] 2020-03-11 17:06
I've had both installs (prod and Insiders) on this PC since at least late 2017, and prod at least has been regularly updated since I use VSCode pretty much daily.  As mentioned, I was able to replicate this with a fresh reinstall of Insiders.  The only thing I can think of that might cause this in that way is if the extension mentioned manually created these files rather than letting VSCode handle it internally (I can't say that is or isn't the case) and uses an older format.  That extension's latest update was last September, but it's been around since 2016 so if they coded it to behave that way they may never have changed it.

I doubt that's the problem, but again, I can't say for sure.

**Comment by bpasero** [comment] 2020-03-11 17:13
@poshcodebear yeah I mean if someone manually crafts these URIs on disk you can easily trick the workbench into behaving like that. But that would not happen typically. If you can reproduce this without tampering with the backup folder manually, it would point to an actual bug I would say, but it seems you cannot.

**Comment by bpasero** [comment] 2020-03-17 07:06
I am able to reproduce and I just verified that the hash for the file path `c:\\Program Files\Microsoft VS Code Insiders\~\OneDrive\Documents\Journal\2020\03\05.md` is `e2ba18c811a33385284e499bfe7998e8` and not `594a4a9d82a277a899d4713a5b08f504`. As such, the only backup we discard when you close the dirty editor is the other one and the original one remains. 

We could in theory build more protective measures around it but since you seem to be the only user of all to hit this I would tend to close this as designed. I do not see how this can happen in normal ops because only VSCode should compute these hashes.

**Closed by bpasero** 2020-03-17 07:06 UTC
Labels: under-discussion, workbench-hot-exit

**Comment by PairedPrototype** [comment] 2020-03-18 14:58
I've also been seeing this issue recently, for roughly a week to maybe 2 weeks, but only just found the time to look into it. From what I remember, it started happening to me after using the Live Share extension.

I tried launching Code with the `--disable-extensions` flag but gave no luck. After briefly reading some of the previous comments here I tried to remove the `windowsState` entry in the `%userprofile%\AppData\Roaming\Code\storage.json` but that didn't work. So I tried it again but also renamed the `%userprofile%\AppData\Roaming\Code\Backups` directory and that appears to have fixed the issue for me without reinstalling or removing any extensions.

**Comment by bpasero** [comment] 2020-03-18 15:13
If you can distill steps to reproduce that would be great. Imho this should not happen for normal VSCode use, but I am not sure if LiveShare is possibly writing to the backup location.

One change that did happen from before: we used to simply discard all backups on shutdown if there were no more backups. We no longer do that though, so there is an increased chance that a stale backup could survive.

**Comment by bpasero** [comment] 2020-03-28 12:08
I ended up actually fixing this via https://github.com/microsoft/vscode/issues/92962
