### ISSUE TITLE
tsserver.js using 100% of CPU

### ISSUE THREAD

**Issue by LeeCampbellr** [Microsoft/vscode#71954] opened 2019-04-08 19:01 UTC
Issue Type: <b>Performance Issue</b>

Whenever I open a Gatsby.js project and run gatsby develop the electron_node tsserver.js process takes 100% of the CPU. I read some github issues and deleted my typescript 3.4 cache folder and that resolved it for about an hour then it starts again. It immediately turns on my fans and drains my battery

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    98	  2479	code main
    3	   164	  2481	   gpu-process
    0	    66	  2519	   shared-process
    0	   426	 18698	   window (contact.js — Development)
    0	     0	 18699	     /bin/bash -l
    0	   131	 18702	     extensionHost
    0	   295	 18704	       electron_node tsserver.js 
    0	    66	 18722	         electron_node typingsInstaller.js typesMap.js 
    0	    66	 18707	       electron_node eslintServer.js 
    0	    33	 18703	     watcherService
    0	    33	 23995	     searchService
    0	   295	 23622	   window (gulpfile.js — infinitymkt)
    0	     0	 23623	     /bin/bash -l
    0	    98	 23626	     extensionHost
    0	    66	 23631	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=23626
    0	    33	 23847	       electron_node eslintServer.js 
   99	   197	 23849	       electron_node tsserver.js 
    0	    66	 23852	         electron_node typingsInstaller.js typesMap.js 
    0	    66	 23871	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=23626
    0	    33	 23627	     watcherService
    0	    33	 23638	     searchService
    0	    66	 24003	   window (Issue Reporter)
    0	     0	 24004	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (gulpfile.js — infinitymkt)
|  Window (contact.js — Development)
|    Folder (Development): 441 files
|      File types: json(182) js(101) jpg(95) webp(18) png(16) md(8) woff(3)
|                  eot(3) css(2) ttf(2)
|      Conf files: package.json(1)
|    Folder (infinitymkt): 1077 files
|      File types: jpg(781) png(148) php(38) DS_Store(30) js(25) scss(22)
|                  svg(14) woff(4) woff2(4) json(4)
|      Conf files: package.json(2) gulp.js(1) webpack.config.js(1);
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|10.5.1
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-yarn|gam|1.6.0
diff-tool|jin|0.0.1
vscode-styled-sort|joh|0.0.7
vscode-styled-components|jpo|0.0.26
auto-comment-blocks|kev|1.0.1
vscode-titlebar-less-macos|leh|1.9.1
vscode-language-babel|mgm|0.0.22
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.11.3
convert-css-in-js|pau|1.1.3
material-icon-theme|PKi|3.7.0
vscode-icons|vsc|8.5.0

(1 theme extensions excluded)

</details>

**Comment by askilondz** [comment] 2019-04-08 19:32
Same issue on my angular/typescript application. Git in the editor is hanging. Delaying on commits and pushes if not processing them at all.

**Comment by mjbvz** [comment] 2019-04-08 20:42
Duplicate of #71886

**Closed by mjbvz** 2019-04-08 20:42 UTC
Labels: new release
