### ISSUE TITLE
No Intellisense for globally installed JavaScript modules

### ISSUE THREAD

**Issue by d4mr** [Microsoft/vscode#51639] opened 2018-06-11 20:22 UTC
Intellisense and suggestions do not work for modules that are installed globally using `npm install -g`.
It only works if the module is listed in the `package.json` file at the root of the project folder.

**Comment by mjbvz** [comment] 2018-06-12 02:04
Duplicate of https://github.com/Microsoft/TypeScript/issues/20401 which is a duplicate of https://github.com/Microsoft/TypeScript/issues/8760

The recommendation is to always have dependencies listed in the local `package.json`

**Closed by mjbvz** 2018-06-12 02:04 UTC
Labels: javascript
