### ISSUE TITLE
Visual Studio Crash when 'Open Folder'

### ISSUE THREAD

**Issue by dhruvajoshi8** [Microsoft/vscode#11592] opened 2016-09-06 15:35 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 10 - Version 1511

Visual Studio Code crashes when trying to open any New folder . Below is the error i get - 

![image](https://cloud.githubusercontent.com/assets/22031266/18280048/66106818-7475-11e6-8ced-28896a41d074.png)

Steps to Reproduce:
1. Go to File -> Open Folder

I tried looking into various issues reported here. Though could not find any solution to this particular problem. Can somebody please help?

Thanks in advance!

**Comment by ugurozturk** [comment] 2016-09-07 00:08
Same version of VS code and Windows but i dont have the problem. 
btw : I have only "Open With Code" what do you mean about the steps.

**Comment by bpasero** [comment] 2016-09-07 04:09
@dhruvajoshi8 does the crash happen after you selected a folder or before the folder dialog opens?

**Comment by dhruvajoshi8** [comment] 2016-09-07 17:09
@bpasero The folder dialog opens successfully. The crash happens after I select a folder,

**Comment by dhruvajoshi8** [comment] 2016-09-07 17:12
@ugurozturk/All Below are the snapshots - 

![image](https://cloud.githubusercontent.com/assets/22031266/18321575/2d5dc826-754c-11e6-968e-d3f25bdc6707.png)


![image](https://cloud.githubusercontent.com/assets/22031266/18321594/3abd4bb8-754c-11e6-8258-3d5c7e512a89.png)


![image](https://cloud.githubusercontent.com/assets/22031266/18321607/453e5d8e-754c-11e6-8a51-cda9d2a21862.png)


Thanks!

**Comment by bpasero** [comment] 2016-09-07 17:50
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dhruvajoshi8** [comment] 2016-09-10 04:11
@bpasero Thanks for your input. However, I still face the same issue after executing from command prompt by disabling the extensions.

**Comment by bpasero** [comment] 2016-09-10 05:55
@dhruvajoshi8 does it reproduce when you try with our insiders release too? 
We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by dhruvajoshi8** [comment] 2016-09-10 06:15
@bpasero Already tried with the insider version 1.5.1.0. Gets reproduced!

**Comment by dhruvajoshi8** [comment] 2016-09-10 06:28
Also, I get the below error when i open a file.

![image](https://cloud.githubusercontent.com/assets/22031266/18408449/c7156eda-774d-11e6-83e3-0888f0125dcf.png)

**Comment by bpasero** [comment] 2016-09-10 07:13
@dhruvajoshi8 can you run "code --verbose" from the command line and attach the output until you see the crash happening. Also please open the dev tools console (Help > Toggle Developer Tools) to see if output is printed.

I think both cases are interesting: Try once with a crash when opening a folder and once when opening a file that leads to the extension host crash.

**Comment by dhruvajoshi8** [comment] 2016-09-10 08:22
@bpasero 

Below are attachments for the case where i re-created the '**Open Folder issue**' as per above procedure -

The crash continuously happens as i navigate through Developer Tools 

![image](https://cloud.githubusercontent.com/assets/22031266/18409070/6173f1d6-775d-11e6-8fda-df871f379ff4.png)


![image](https://cloud.githubusercontent.com/assets/22031266/18409077/6fb1ccf0-775d-11e6-92db-c5afed3869fe.png)


The Source for console - 

![image](https://cloud.githubusercontent.com/assets/22031266/18409086/823db53c-775d-11e6-9fce-0861d6626bcd.png)


Below is what i get on the prompt during the crash -
![image](https://cloud.githubusercontent.com/assets/22031266/18409093/9c0d31cc-775d-11e6-9c33-d962517e4549.png)


Prompt after i close the application - 

![image](https://cloud.githubusercontent.com/assets/22031266/18409103/b3cdc2ae-775d-11e6-83aa-3a66110b67a6.png)


I will attach the other case(Open File) in a separate comment.
Thanks!

**Comment by dhruvajoshi8** [comment] 2016-09-10 08:31
Below are attachments for the case where i re-created the '**Open File issue**' as per above procedure -

![image](https://cloud.githubusercontent.com/assets/22031266/18409168/e2df67ea-775e-11e6-92d2-ef589a580b3f.png)

![image](https://cloud.githubusercontent.com/assets/22031266/18409169/e94875e0-775e-11e6-9144-8f804a93fbf7.png)

![image](https://cloud.githubusercontent.com/assets/22031266/18409176/05bc0926-775f-11e6-866d-7fd08104a929.png)

Thanks!

**Comment by bpasero** [comment] 2016-09-12 05:23
@dhruvajoshi8 sorry the screenshots are too blurry, I cannot see anything. Can you redo the ones for the console to see what kind of output there is?

**Comment by dhruvajoshi8** [comment] 2016-09-13 06:28
@bpasero Below is the source code for error in console log for the 'Open Folder Issue' -

![image](https://cloud.githubusercontent.com/assets/22031266/18463579/c986091a-79a8-11e6-9c84-4ed6cd303020.png)


 Below is the console log for the 'Open File Issue' -
![image](https://cloud.githubusercontent.com/assets/22031266/18463615/0a092c4c-79a9-11e6-8f43-2d9b7d380734.png)

Hopefully these are clear enough :)

Please let me know if any more information required.

Thanks!

**Comment by dhruvajoshi8** [comment] 2016-09-13 06:32
I have tried this tool with the same version and same OS version on a different machine. It works!

Could these be because of my Hardware configuration(since i do not have the best config in market)? 
I have a Sony Vaio i3 3rd Gen, 2GB RAM.

But i think this config should be enough. Please feel free to share your views.

Thanks!

**Comment by bpasero** [comment] 2016-09-13 08:08
Adding more people to this (@alexandrudima, @joaomoreno, @jrieken) to get more ideas.

@dhruvajoshi8 did you ever run Code as administrator maybe? I wonder if this could also be related to file permissions.

**Comment by joaomoreno** [comment] 2016-09-13 08:27
@dhruvajoshi8 If you open Windows's `Event Viewer` do you see any Code specific errors in there?

**Comment by bpasero** [comment] 2016-09-13 08:31
@dhruvajoshi8 can you 
* close Code
* open the file `C:\Users\<name>\AppData\Roaming\Code\User\settings.json` with another editor
* add `"telemetry.enableCrashReporter": false`
* save
* open a command line
* set ELECTRON_ENABLE_STACK_DUMPING=true
* run code from the command line `code --verbose`
* send us the output you see when it crashes

**Comment by mrmlnc** [comment] 2016-09-13 08:57
My 2 cents.

Recently, while working on a project for the terminals (Windows) we caught the bug with Electron and NW.js, which kills the process of rendering  (even with [Electron API Demos app](https://github.com/electron/electron-api-demos)). This was due to problems with Hardware configuration.

Try any application built on the Electron to exclude a problem with Electron. For example, Atom.

**Comment by bpasero** [comment] 2016-09-13 09:01
@mrmlnc well but he can still use VS Code as long as no file is opened...

**Comment by alexandrudima** [comment] 2016-10-27 20:40
@dhruvajoshi8 any improvements with our latest version (or the insiders build?) -- we no longer connect to the shared process on extension host startup.

**Comment by DrYSG** [comment] 2016-12-06 23:00
@mrmlnc Do you might telling me what your launch.json looks like to intergrate with NW.js

**Comment by bpasero** [comment] 2016-12-07 05:25
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by joaomoreno** [comment] 2016-12-07 07:52
Closing, waiting on @dhruvajoshi8's reply.

**Closed by joaomoreno** 2016-12-07 07:52 UTC
Labels: freeze-slow-crash, needs more info, workbench
