### ISSUE TITLE
Problems View - add option to restrict to current viewed file

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#31973] opened 2017-08-03 12:47 UTC
I have seen people request the option (opt-in) to have the problems include the summary for all files. I was wondering if you could also add an option to restrict the PROBLEMS output and count in the status bar to only the currently edited file (not all opened ones).

I have several different scripts opened and would find it much cleaner to see errors for a single file. Many thanks for considering this!

**Comment by fbricon** [comment] 2017-11-06 15:12
Having the option to enable problems filtering on currently focussed editor would be very convenient for Java projects with massive amounts of warnings

**Comment by sandy081** [comment] 2017-11-27 13:49
Duplicate of #7248

**Closed** 2017-11-27 13:50 UTC
Labels: *duplicate, error-list, feature-request
