### ISSUE TITLE
about screen

### ISSUE THREAD

**Issue by dev336** [microsoft/vscode#211954] opened 2024-05-03 14:49 UTC
Type: <b>Bug</b>

ok so some time when i scrool on my code or i don't know may be ill do any thing im getting some sort of white strings kind of thig on my sceen and that thing dont happns where we code but like navbar and side covers with that kind of thing and i have make sure that its not a issue of my screen so i think im getting some kind of bug may be 

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.75GB (4.61GB free)|
|Process Argv|--crash-reporter-id 4b8585f1-f6d6-451f-90d5-f4bcbde64dea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-end-tag-labels|ant|1.0.0
askia-qexml-generator-extension|Ask|1.0.1
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.45.15272
profiler-php-vscode|DEV|1.45.15272
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.19.9
java|red|1.30.0
LiveServer|rit|5.7.9
bootstrap-class-autocomplete|tor|1.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
![IMG-20240503-WA0010](https://github.com/microsoft/vscode/assets/168844509/4d2ee68c-7178-49de-98e7-de52edc76354)
![IMG-20240503-WA0012](https://github.com/microsoft/vscode/assets/168844509/4399cab1-65f6-491b-abbd-c56c2a6849c5)
![IMG-20240503-WA0013](https://github.com/microsoft/vscode/assets/168844509/cb5417dd-68a0-487c-97cc-bf46ba93ade5)
![IMG-20240503-WA0014](https://github.com/microsoft/vscode/assets/168844509/be4f2fb7-9949-431e-80f0-6baa6f00c078)
![IMG-20240503-WA0015](https://github.com/microsoft/vscode/assets/168844509/209261c2-2094-4912-b91c-1c00a6bdafd5)

vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp1r3:30993539
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by roblourens** [comment] 2024-05-03 19:43
Not clear what you're seeing- a screenshot or better description would help

**Comment by IllusionMH** [comment] 2024-05-03 22:45
Looks like duplicate of #210863 , #124226

See https://github.com/microsoft/vscode/issues/210863#issuecomment-2084209796 for possible workaround.

**Comment by dev336** [comment] 2024-05-04 04:12
> Not clear what you're seeing- a screenshot or better description would help

https://github.com/microsoft/vscode/issues/210863#issue-2255472432   same prob as this

**Closed** 2024-05-04 04:33 UTC
Labels: info-needed, triage-needed, new release

**Comment by dev336** [comment] 2024-05-04 07:13
> Looks like duplicate of #210863 , #124226
> 
> See [#210863 (comment)](https://github.com/microsoft/vscode/issues/210863#issuecomment-2084209796) for possible workaround.

thanks a lot bro
