### ISSUE TITLE
terminal panel padding top is too large

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#163806] opened 2022-10-17 03:39 UTC
![image](https://user-images.githubusercontent.com/41773861/196084303-aca9407c-2035-47d4-820a-72f62e0fff51.png)

```
Version: 1.73.0-insider (Universal)
Commit: 7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c
Date: 2022-10-14T05:18:26.756Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

**Comment by adarshcodes** [comment] 2022-10-17 06:34
I would like to fix this. Can you assign this to me please?

**Comment by Tyriar** [comment] 2022-10-17 11:01
This is by design, the terminal is bottom aligned in the panel and it looks like there isn't quite enough room to fit another row in.

**Closed by Tyriar** 2022-10-17 11:01 UTC
