### ISSUE TITLE
SCM: Show changes in tree-like format

### ISSUE THREAD

**Issue by Huachao** [microsoft/vscode#14582] opened 2016-10-27 07:37 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 10 10.0.14393

Steps to Reproduce:
1. I just want we could have an extra option to allow user to display git changes no matter stage or not in tree view, not only list all of them like now.

**Comment by joaomoreno** [comment] 2016-10-27 09:08
#178

**Comment by langdonx** [comment] 2017-01-10 13:13
@joaomoreno This doesn't seem like a duplicate of the referenced issue...

 - #178 talks about the color of the file in the list
 - #14582 (this one) asks to display the changes in a tree view instead of a flat list

Can it be re-opened/considered?  I find it much easier to look through changes in a tree (the same way I see my files in VS Code's Explorer and the same way Visual Studio shows them in Team Explorer>Changes).

**Comment by josundt** [comment] 2017-02-03 16:02
I also want this 👍

**Comment by karlis-repsons** [comment] 2017-06-10 10:12
I wished to add an example of why I would currently avoid vsCode clutter with console:
![image](https://user-images.githubusercontent.com/27850284/27001895-376a6954-4ddd-11e7-9773-208ef1144c1c.png)
In this case, I just wished to check if there is nothing in changes besides the items visible in red in console.

Visual Studio Community has tree view, which could be taken as a good example. It distinguishes between staged and not staged files. Of course, I would like vsCode to do the same.

**Comment by DGolubets** [comment] 2017-11-13 14:09
+1 here
I like going through my git changes before I make a pull request, to see if I forgot to remove some files, comments, debug code, etc. But doing so on a flat list of files is hard.

**Comment by levani** [comment] 2017-11-27 07:28
Question: Is this doable with an extension? I'm not yet familiar with extension api but if it can be accomplished with an extension I will try to works on this...

**Comment by AlexeyRipenko** [comment] 2018-01-08 11:11
+1.
If you have changes in multiple folders and there are a lot of changes it becomes too hard to navigate.
I like how it has been implemented for Visual Studio Team Explorer (for instance, VS 2017)

**Comment by shadilahham** [comment] 2018-01-12 10:47
+1
I also like the way IntelliJ implements this. Would be a great feature to have.

**Comment by allenyllee** [comment] 2018-03-14 02:20
That's say, if I want to add all the file changes under python_RL2/, shown as below, currently I have to manually select them all. Is there a quicker way to do this? Which like tree view select or path filter select?

![](https://screenshotscdn.firefoxusercontent.com/images/46be665f-4ef5-4133-b3af-a36be29f02fc.png)

**Comment by aoancea** [comment] 2018-03-20 18:25
When will this be implemented as it's open since 2016 :)

**Comment by dcbarans** [comment] 2018-03-22 19:26
+1.  Can we at least organize the changes by full path instead of filename?

**Comment by leonardochaia** [comment] 2018-04-03 13:55
+1 this is a reall need.

**Comment by andersgb1** [comment] 2018-05-07 07:29
+1

**Comment by artemjackson** [comment] 2018-05-07 12:38
+

**Comment by korndev** [comment] 2018-05-08 04:55
+1

**Comment by garu57** [comment] 2018-05-11 12:50
+1

**Comment by lukas15442** [comment] 2018-05-18 17:51
+1

**Comment by francesco-carrella** [comment] 2018-06-11 10:40
+1

**Comment by hxibrahim** [comment] 2018-06-11 10:58
+1

**Comment by xrlim** [comment] 2018-06-11 12:43
+1

**Comment by cilerler** [comment] 2018-06-11 13:01
# PLEASE stop posting `+1` and use the 👍 on the initial post at top 
so owners can actually see how many people wants this feature.  _(I'm surprised that they still couldn't realize how important this feature is)_

**Comment by microhaxo** [comment] 2018-09-10 18:03
FIX IT!

**Comment by kwiesmueller** [comment] 2018-09-24 13:01
I started to use https://www.sublimemerge.com/ since it came out last week because I lacked a good visual solution on linux.
It is unbelievable disapointing how such a crucial but simple feature did not make it into vscode for so long.
Especially as a Golang developer I really need this because we use a checked in vendor directory causing a few hundreds of thousand changes when updating them.
I don't get how the vscode team can work with the current state as node_modules are in no way better.

Could somebody from the team at least provide a statement on where the problem resides?  I am barely a frontend dev and can't really imagine the complexity as there already is tree views in vscode.
I would do it myself if I could...

**Comment by gulshan** [comment] 2018-09-24 13:18
The [GitLens extension](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) can be an option for those who badly want this.

**Comment by andersgb1** [comment] 2018-10-12 07:59
> The [GitLens extension](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) can be an option for those who badly want this.

Unfortunately, the GitLens explorer only provides a "view" to the changed files. There are no Git actions (staging, committing, etc.) like in the built-in Source Control sidebar.

**Comment by ragvri** [comment] 2018-10-22 10:55
Has this feature be resolved already?

**Comment by kleber-swf** [comment] 2018-11-14 14:09
Usually I want to see the files in a tree view when I need to make a partial commit, like the content of one or more folders. It's hard to select each file, even with shift and stuff.

While this feature isn't ready, I'm using GitKraken or the good and old git command line tool: `git add folder/*`. If you focus the "Source Control" tab after this command you'll see the entire folder inside the "Staged Changes" area. It's not the best solution, but save me some time.

**Comment by UziTech** [comment] 2018-12-27 16:35
@andersgb1 I created a PR to add (un)staging an entire folder for [gitlens #600](https://github.com/eamodio/vscode-gitlens/pull/600)

![gitlens](https://user-images.githubusercontent.com/97994/50486652-933b0400-09c0-11e9-940b-07ce32518fc0.png)

**Comment by andersgb1** [comment] 2018-12-28 09:14
> @andersgb1 I created a PR to add (un)staging an entire folder for [gitlens #600](https://github.com/eamodio/vscode-gitlens/pull/600)

Very, very nice, @UziTech!

**Comment by nash-ye** [comment] 2019-02-23 21:25
Almost 2 years passed and no visible solution yet!
Any plans or extensions to implement this?

**Comment by UziTech** [comment] 2019-02-24 01:41
@nash-ye [gitlens](https://github.com/eamodio/vscode-gitlens/pull/600) allows you to stage files in a tree view

**Comment by nash-ye** [comment] 2019-02-24 08:06
> @nash-ye [gitlens](https://github.com/eamodio/vscode-gitlens/pull/600) allows you to stage files in a tree view

Thanks for pointing this out, it does indeed, I have hid the default SCM window, switching to GitLens.

**Comment by josundt** [comment] 2019-02-25 11:07
I think this should be considered as a core VsCode feature.
It also means one more place to utilize VsCode's new and improved "treeview" UI component (the one used in the file explorer).

**Comment by jmbockhorst** [comment] 2019-04-13 18:03
I have done some exploration into supporting this feature.

Is this the general idea?

![tree](https://user-images.githubusercontent.com/44308390/56083586-7b12b780-5dec-11e9-9cfa-210b00ac34e2.png)

**Comment by UziTech** [comment] 2019-04-13 19:26
I think it would be better to reduce the number of folders to ones that have multiple files/folders in the in the view. (similar to what github does for empty directories)

something like:
![image](https://user-images.githubusercontent.com/97994/56084365-c1b9df00-5df7-11e9-8fad-25ef4ce865ca.png)

The main point of making this a tree view format is so you can stage entire folder instead of only having the option to stage each file separately or stage all files.

**Comment by kwiesmueller** [comment] 2019-04-13 20:32
I agree with @UziTech 
The first screenshot would be a little too verbose and shows too much information that could be combined.

**Comment by jmbockhorst** [comment] 2019-04-13 20:39
@UziTech Thanks for the input. I came up with something like this.

![tree](https://user-images.githubusercontent.com/44308390/56085028-575a6c00-5e02-11e9-8e90-a5e6e712ca28.png)

**Comment by invis87** [comment] 2019-04-26 07:13
Sorry fo stupid question, but how I turn on TreeView for PullRequest changes for example?

**Comment by jmbockhorst** [comment] 2019-04-26 13:20
@invis87 I added a setting called "Show changes as a tree view" under Features -> SCM. You have to build it from my [branch](https://github.com/jmbockhorst/vscode/tree/scmTree) if you want to test it.

**Comment by rs1496** [comment] 2019-05-08 09:34
@jmbockhorst i am not able to see "Show changes as a tree view" under Features -> SCM in VS Code. Can you please help me to find out.
![SCM Tree View](https://user-images.githubusercontent.com/47417358/57365180-39ceb700-71a2-11e9-8d73-7eb01e010d4d.PNG)

**Comment by dmrickey** [comment] 2019-05-16 14:34
Is there a PR for this already?  What are the chances of it being included any time soon?

**Comment by jmbockhorst** [comment] 2019-05-16 14:38
I haven’t opened a pull request yet. Still working on the context menus and commands.

**Comment by eightnoneone** [comment] 2019-05-24 15:31
@jmbockhorst Would this tree view honor the `workbench.tree.indent`? It's a big accessibility benefit for some visual impairments. Thanks for the work on this feature in general.

**Comment by jmbockhorst** [comment] 2019-05-25 17:00
@eightnoneone Yes, this tree would honor the tree indent setting as well.

**Comment by jmbockhorst** [comment] 2019-05-25 21:41
I have finished adding the context menus and actions for the tree view. This includes the ability to stage and unstage an entire directory.

![contextMenus](https://user-images.githubusercontent.com/44308390/58374862-9b658400-7f0b-11e9-97d7-3bfd37e5aae6.gif)

![actions](https://user-images.githubusercontent.com/44308390/58374868-c059f700-7f0b-11e9-9d38-1542a2937c68.gif)

I think the next step would be a way to distinguish whether a change is staged or not, because right now there is no way to tell in the tree view. Let me know what you guys think.

**Comment by eightnoneone** [comment] 2019-05-25 23:14
Would it make sense to have the tree populate under the existing "Changes" and "Staged Changes" top level sections as they do now? Showing the subordinate lists in trees.

**Comment by jmbockhorst** [comment] 2019-05-26 01:01
That is an option for sure, but I would be worried about it being too cluttered and redundant.

**Comment by lucaritossa** [comment] 2019-05-26 05:37
As @ghost mentioned in this [post](https://github.com/microsoft/vscode/issues/14582#issuecomment-495959174)
Visual Studio Community could be a valid example. It distinguishes between staged and not staged files using 2 separate tree

**Comment by eightnoneone** [comment] 2019-05-26 14:09
Pros/cons I'm seeing on the two approaches:

1. The two top level sections of "Staged Changes" and "Changes"
   * similar to existing views
   * could get cluttered when all expanded, 
   * collapse gets less length for whole dirs changed
2. A single tree with filters for the states **A**dded, **M**odified, **U**ntracked etc.
   * could cover many use-cases of 'i need less clutter'. _Remember, my signal is your noise._
   * departure from existing view structure/behavior. Add to index doesn't remove from changed list (unless correct filter is on)

**Comment by jmbockhorst** [comment] 2019-05-26 14:18
I looked at how Visual Studio Community does this, and I think it would work fine to have separate trees for the stages. It would also keep it consistent across Visual Studio products. 

Also, how I have it now, it still shows the status (A, M, U), but that does not distinguish whether a file is staged or not.

**Comment by lmcarreiro** [comment] 2019-05-26 18:48
Is it working with a big list of changes too? Today it shows only the top 5000 files. Try removing `node_modules` from `.gitignore` and renaming the `src` folder.

Maybe if there are too much files, it could default to show the folders collapsed. If not, would be fine to show the folders expanded.

**Comment by jmbockhorst** [comment] 2019-05-27 15:59
I have finished the work to have separate trees for each resource group (Changes, Staged Changes). I think it is working nicely. Staging, unstaging, and discarding changes all works on directories as you would expect in each group. 

![multipleTrees](https://user-images.githubusercontent.com/44308390/58430241-2f4f6100-806e-11e9-9bc1-cc07b7ac7a4a.gif)

**Comment by jmbockhorst** [comment] 2019-05-27 16:08
@lmcarreiro I tested it like you said and it still works a big list of changes, it just shows the big tree. I like the idea of collapsing the a folder with too many files in it, just not sure how and when to best do that.

**Comment by eightnoneone** [comment] 2019-05-27 16:32
@jmbockhorst That looks really nice. I agree there's a threshold of a sane list to show before assuming one should start with a collapsed view. Is a "collapse all" icon like in the workspace tree view a reasonable feature-creep addition here? If it's a long list, It would give the user the option to start from the top and work through a tree in an ordered fashion. Best would be separate ones on Changes and Staged Changes.

**Comment by gjsjohnmurray** [comment] 2019-05-28 09:45
@jmbockhorst does your exploration add twisties to the Resource Groups (i.e. CHANGES and STAGED CHANGES)? I recently opened #74280 because I'd like to do that for a source control provider implemented in one of our extensions. @joaomoreno linked my issue to this one and closed it.

**Comment by jmbockhorst** [comment] 2019-05-28 14:41
@gjsjohnmurray Currently it does not, but it is something that could be added fairly easily.

**Comment by gjsjohnmurray** [comment] 2019-05-28 14:51
@jmbockhorst thanks. I assume the changes you're proposing take account of how the SCM viewlet is generic, with Git being just one user of the generic framework. My #74280 request was to have expand/collapse of the resource groups implemented at the framework level so anything plugging into it gets the benefit.

**Comment by shane-smith** [comment] 2019-07-03 05:49
This would be very nice to have. It's one of the main features I still miss from PHPStorm. The Gitlens extension for VS Code does have a similar view, so I started using that this week as a workaround as I had to work through a few hundred files and progressively stage & commit directory-by-directory.

**Comment by elgandoz** [comment] 2019-08-10 12:18
Given the working example above, is there a way to currently activate this feature?

**Comment by cspwizard** [comment] 2019-09-16 06:27
@jmbockhorst nice job! Looks fantastic. 
When we could use this feature?

**Comment by elgandoz** [comment] 2019-09-18 23:01
I just noticed this issue appear as work in progress for the Sep 2019 iteration cycle as "Adopt compressed trees in the SCM view" https://github.com/microsoft/vscode/issues/80591

**Comment by joaomoreno** [comment] 2019-09-20 15:30
Fixed by https://github.com/microsoft/vscode/commit/95d7625a2769bd3c7debdc69953e4e3900c448fd

![scm](https://user-images.githubusercontent.com/22350/65339369-4f320400-dbcc-11e9-9c93-7e92bc6e11dd.gif)

This will roll out next monday on the Insider build. Let me know any feedback!

**Closed by joaomoreno** 2019-09-20 15:30 UTC
Labels: feature-request, scm
