### ISSUE TITLE
accepting intellisense item dismisses inline completion

### ISSUE THREAD

**Issue by juihanamshet1** [microsoft/vscode#163481] opened 2022-10-12 21:39 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.0
- OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Install the Intellicode Completions extension
2. Open a typescript file and type `console.l`, you will see `log` selected in the Intellisense menu. You will also see `log("")` show up as an inline completion
3. Hit tab to accept the Intellisense item. You will see the inline completion go away. 

![vscode-insiders-suggestwidget-bug](https://user-images.githubusercontent.com/86270736/195453082-8004d8da-cc66-4dac-adde-afd2ca2a5fc9.gif)

cc @hediet

**Comment by juihanamshet1** [comment] 2022-10-12 21:41
This issue potentially is related to this one https://github.com/microsoft/vscode/issues/163431

**Comment by juihanamshet1** [comment] 2022-10-12 22:25
I did some digging and looks like this PR introduced this bug - https://github.com/microsoft/vscode/commit/9b0ae4dd79e05597cefa4e411e144a21e2fc7ceb 

I tested this by building Code-OSS with head at commit bdd63955e5b (#163293) which was made right before the above-mentioned commit. I see expected behavior as below. 
![vscode-insiders-suggestwidget-bug-2](https://user-images.githubusercontent.com/86270736/195459168-c1e436b4-b183-4866-9bf3-544b6580940d.gif)

**Comment by juihanamshet1** [comment] 2022-10-20 21:00
@hediet I was able to repro this bug in the simple extension with the code you provided. I used VS Code Insiders latest version. 

I used the same code you gave me but if you want to look at it, here's the branch - https://github.com/juihanamshet1/vscode-extension-samples/tree/juih/dev/163481-repro

Here's the GIF of the repro
![intellisense-inline-repro](https://user-images.githubusercontent.com/86270736/197057000-78b4d5c3-9259-4b4d-8ada-3deb5117d3fd.gif)

Something that I noticed while debugging this is that the commit() function on line 510 in inlineCompletionModel.ts doesn't get called when I hit Tab.

**Comment by juihanamshet1** [comment] 2022-10-21 16:42
Checked out the latest main and the undo bug has been fixed, thank you :) 

I saw this new bug with the intellisense + inline completion interaction - documenting it below. It's reproducible in the sample extension that I posted in the previous message. 

![new-tab-bug](https://user-images.githubusercontent.com/86270736/197246413-53964c8c-39c6-42a9-9007-81446d69f3da.gif)

**Comment by hediet** [comment] 2022-10-26 09:30
Unfortunately, I cannot reproduce :(

![Code_-_OSS_sRlWI0Yg0N](https://user-images.githubusercontent.com/2931520/197989194-ff854f6c-b421-4402-bc66-bf8fcfc65ebc.gif)

![Code_-_OSS_3jDbrHC0RE](https://user-images.githubusercontent.com/2931520/197990333-040b99b2-7b68-4aea-9fab-6aebe6438c39.gif)

> Tabbing "assert" did not trigger any of the registered editor commands associated with Tab. 

This sounds like the context key was not set correctly and is probably also the cause of the bug I ran into when I shared my screen. Maybe this got fixed by the a fix in the suggest widget.

**Comment by juihanamshet1** [comment] 2022-10-26 15:10
This was fixed in the latest Insiders, thank you! 
![tab-intellisense-inline-working](https://user-images.githubusercontent.com/86270736/198064602-dff86470-6d2d-4665-9e92-adb31139d20a.gif)

**Closed** 2022-10-28 17:09 UTC
Labels: bug, inline-completions
