### ISSUE TITLE
Why cannot toggle word wrap in a diff editor?

### ISSUE THREAD

**Issue by frankhan12345** [microsoft/vscode#110798] opened 2020-11-17 11:38 UTC
Issue Type: <b>Feature Request</b>

Why VS code cannot toggle word wrap in a diff editor?

As I know, this function can be found in notepad++ with its plugin "Compare". 

When writing codes such as latex files, this function is really useful, since there are often many words in one line. If word cannot be wrapped in a diff editor, it will be extremely difficult to check the changes between two tex files.

Thanks in advance!

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment] 2020-11-17 12:02
/duplicate of #11387 which is coming in the next release

**Closed** 2020-11-17 12:03 UTC
Labels: *duplicate
