### ISSUE TITLE
Visual Studio code  SLOW to startup and use.

### ISSUE THREAD

**Issue by Steve423** [Microsoft/vscode#49129] opened 2018-05-03 15:21 UTC
- VSCode Version: 1.22.2
- OS Version: Windows 2012

Steps to Reproduce:

1. Downloaded code yesterday. Installed it on Windows 2012 server. Extremely SLOW to open VSCode
   ( maybe 5 or more minutes) and SLOW response to use VSCode ( maybe 3 or more minutes).
   I noticed there are copies of VSCode running in Task manager.

2. Visual studio code "installers" is even SLOWER than  "visual studio code". All of the attached info
    was done on "Visual Studio code".

Does this issue occur when all extensions are disabled?: Yes/No  -YES
[vs_code_error_msg_Startperformance_perform.txt](https://github.com/Microsoft/vscode/files/1971459/vs_code_error_msg_Startperformance_perform.txt)
[vs_code_startup_performance.txt](https://github.com/Microsoft/vscode/files/1971460/vs_code_startup_performance.txt)
[VS_code_status.txt](https://github.com/Microsoft/vscode/files/1971461/VS_code_status.txt)
![task_mgr_vs_code](https://user-images.githubusercontent.com/19346211/39585001-5eb7d748-4eb9-11e8-8b34-c8ba4e21c1a2.jpg)

Code-status

C:\Program Files\Microsoft VS Code>code --disable-extensions

C:\Program Files\Microsoft VS Code>
[main 9:02:30 AM] update#setState idle
[main 9:03:00 AM] update#setState checking for updates
[main 9:05:27 AM] update#setState idle

C:\Program Files\Microsoft VS Code> code --status

C:\Program Files\Microsoft VS Code>
Collecting CPU and memory information. This might take a couple of seconds.

Version:          Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04
-12T16:38:45.278Z)
OS Version:       Windows_NT x64 6.2.9200
CPUs:             Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (1 x 2600)
Memory (System):  14.00GB (11.68GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Program Files\Microsoft VS Code\Code.exe --disable-extensio
ns

[main 9:16:20 AM] RangeError: Maximum call stack size exceeded
    at Array.join (native)
    at Object.t.pad (C:\Program Files\Microsoft VS Code\resources\app\out\vs\cod
e\electron-main\main.js:52:587)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:636)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
    at Array.forEach (native)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-
main\main.js:197:811)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-mai
n\main.js:197:838
---------------------

Startup Performance Measurement
actions.ts:314 OS: win32 (6.2.9200)
actions.ts:315 CPUs: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (1 x 2600)
actions.ts:316 Memory (System): 14.00GB (11.71GB free)
actions.ts:317 Memory (Process): 164.61MB working set (208.48MB peak, 141.36MB private, 38.43MB shared)
actions.ts:318 VM (likelyhood): 0%
actions.ts:319 Initial Startup: true
actions.ts:320 Screen Reader Active: false
actions.ts:321 Empty Workspace: true
actions.ts:329 

(index)TopicTook (ms)0"[main] start => app.isReady"321"[main] nls:start => nls:end"02"
[main] app.isReady => window.loadUrl()"647763"[renderer] window.loadUrl() => 
begin to require(workbench.main.js)"5834"[renderer] require(workbench.main.js)"8305"[renderer] 
create extension host => extensions onReady()"1235976"[renderer] 
restore viewlet"07"[renderer] restore editor view state"698"[renderer] overall workbench load"17559"------------------------------------------------------"10"[main, renderer] start => extensions ready"19164211"[main, renderer] start => workbench ready"68195Array(12)

---------
VSCode Startperformance ( Not sure about this, so I included it.)

Error received from starting extension host
(anonymous) @ extensionService.ts:152
extensionService.ts:153 timeout
(anonymous) @ extensionService.ts:153

timeout
(anonymous) @ extensionService.ts:153

log.ts:171   ERR Cannot read property 'value' of null: TypeError: Cannot read property 'value' of null
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2854:779
    at n.Class.derive._creator.then (file:///C:/Program Files/Microsoft VS 
	
	
	[Extension Host] Error: connect ENOENT \\.\pipe\vscode-65ab3471-43d9-4cbf-8583-6a840e33e537-sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
t.log @ console.ts:136
extensionService.ts:377 

Extension host terminated unexpectedly. Code:  0  Signal:  null
w._onExtensionHostCrashed @ extensionService.ts:377
notificationsAlerts.ts:39 

Extension host terminated unexpectedly.
e.onDidNotificationChange @ notificationsAlerts.ts:39

**Comment by bpasero** [comment] 2018-05-04 06:58
@Steve423 this machine has a single CPU right?

**Comment by Steve423** [comment] 2018-05-04 11:55
Yes a  single CPU.

**Comment by bpasero** [comment] 2018-05-06 04:30
Duplicate of https://github.com/Microsoft/vscode/issues/34396

**Closed by bpasero** 2018-05-06 04:30 UTC
Labels: perf
