### ISSUE TITLE
Cursor duplicate when inserting deadkey

### ISSUE THREAD

**Issue by IAMISSAM** [microsoft/vscode#143957] opened 2022-02-25 13:23 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.64.2 (Universal) (f80445acd5, 2022-02-09T22:00:58.347Z)
- OS Version: macOS 12.2.1

Steps to Reproduce:

1. When I insert a dead key in vscode like ^ or `, a strange duplicated cursor appears (AZERTY keyboard)

https://user-images.githubusercontent.com/26183901/155722411-7006e9e3-ccff-4b31-8ec4-3cc3d32c21df.mov

**Comment by alexdima** [comment] 2022-02-25 14:28
Duplicate of #142811. A fix is already available in [our latest insiders](https://code.visualstudio.com/insiders/).

**Closed by alexdima** 2022-02-25 14:28 UTC
