### ISSUE TITLE
Git Bash as terminal freezes constantly

### ISSUE THREAD

**Issue by danielannan17** [microsoft/vscode#144016] opened 2022-02-26 19:23 UTC
Issue Type: <b>Bug</b>

When I'm using GitBash it randomly freezes.

Steps to reproduce consistently (Others other ways too).
1. Set Git Bash as default terminal
2. Open a new terminal
3. Type something to confirm its working
4. Click the + icon to add a new terminal
5. Type something in that new terminal
6. Click bin icon for the new terminal to delete it
7. Can no longer type in the first terminal

Extra info - I've installed oh my zsh in my git bash following this guide but this bug only affects vscode, doesnt affect the Git Bash or the Windows Terminal App
https://www.youtube.com/watch?v=SE1UtrtH9mo

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by meganrogge** [comment] 2022-02-28 02:03
When this happens, can you toggle the shared process and see if there's a log stating the pty has been disconnected?

**Comment by danielannan17** [comment] 2022-03-01 19:43
There's no change stating that and there's also no in the process explorer

**Comment by gwte** [comment] 2022-05-06 09:35
I have the exact same issue. Not only does the previous terminal usually stops working after opening a new one, current terminal also constantly freezes, requiring recreation of it and rendering the whole feature basically unusable. 

Running:
Windows 10 Enterprise version 21H2 OS build 19044.1645
Git: Git-2.36.0-64-bit
VSCode:  1.67
Shell: zsh 5.8 with oh-my-zsh (master (0f2715b))

Worth noting I have the same issue in latest InteliJ IDEA - but not in Git Bash itself.

Is there anything I can provide to help resolve this, happy to!

**Comment by Anduh** [comment] 2022-05-06 10:16
Interesting, I have essentially the same setup as @gwte and experienced Git Bash freezing in both VSCode & with Windows Terminal.

Happened just as I was updating my git bash to use oh-my-zsh [following these instructions](https://dominikrys.com/posts/zsh-in-git-bash-on-windows/#installing-oh-my-zsh), but unsure if the freezing was started just before the switch to zsh.

The common thread seems to be git bash & zsh, and not necessarily VS Code.

**Comment by meganrogge** [comment] 2022-05-06 16:29
@Anduh thanks for the investigation. 

>I have essentially the same setup as @gwte and experienced Git Bash freezing in both VSCode & with Windows Terminal.

That suggests it's an issue with conpty, so closing this as we cannot control that. When it's fixed in conpty, it will be fixed in VSCode.

**Closed by meganrogge** 2022-05-06 16:29 UTC
Labels: needs more info

**Comment by gwte** [comment] 2022-05-09 07:45
I have opted out of conpty with: 

Terminal › Integrated: Windows Enable Conpty
Whether to use ConPTY for Windows terminal process communication (requires Windows 10 build number 18309+). Winpty will be used if this is false.

And can still reproduce the issue.

**Comment by gwte** [comment] 2022-05-24 07:43
> @Anduh thanks for the investigation.
> 
> > I have essentially the same setup as @gwte and experienced Git Bash freezing in both VSCode & with Windows Terminal.
> 
> That suggests it's an issue with conpty, so closing this as we cannot control that. When it's fixed in conpty, it will be fixed in VSCode.

@meganrogge would it be possible to think about a workaround? 
If https://github.com/microsoft/terminal/issues/1810 is the cause, there has been no progress there for over a year...

This is a really annoying issue, that hampers VS Code usage on what I believe is quite common setup for developers on Windows.

**Comment by Anduh** [comment] 2022-05-25 11:10
Yeah, a workaround would be great, the "opt out of conpty" didn't work for me either.

Considering trying out WSL as a workaround.
