### ISSUE TITLE
debug console shows REPL results and console.log output in wrong order

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79196] opened 2019-08-15 10:44 UTC
evaluating `var i = 0; console.log(++i); ++i;` in the REPL shows output in the wrong order.

**Comment by isidorn** [comment] 2019-08-15 14:06
I can reprouce this nicely.

Debug adapter is returning results in the correct order the issue is on the vscode side.
The issue is that we have an object that represents the user input and the evaluation output together. Due to these two being tied together it is not possible for any output to appear between them.
Now to think about it I am not sure what was the design decision to go with this "double object" approach. But it seems like it does not make a lot of sense.
Due to this we are also hitting a limitation that if an evaluate takes too long we do not show the input.

So the fix for this would be to use seperate objects in the model for input and evaluate output.

**Comment by pavelfeldman** [comment] 2019-08-20 15:47
Top-level await is another use case for this. When we say `await fetch('/')`, source expression is not visible until we get the response. Async operations are meant to take long and having synchronous console logs in between of evaluation and result is also expected.

**Comment by dgozman** [comment] 2019-09-04 22:41
@isidorn Is someone actively working on this? I see it is added to the milestone and don't want to interfere. I have a rough version of the fix for this, and wonder whether it makes sense to contribute a PR? Thanks a lot!

**Comment by isidorn** [comment] 2019-09-05 08:30
@dgozman I planned to look into this next week and I have not started coding yet.
However if you have a PR which contributes a nice fix I would be very interested to see it. So maybe you can create it with what you have and we can start a discussion there.
I wonder if you tackled this like I suggested to split the "double objects" in the REPL model in two, or you found another fix. Anyways we can discuss in the PR - thanks a lot!

**Closed** 2019-09-10 09:56 UTC
Labels: bug, debug

**Comment by dgozman** [comment] 2019-09-18 23:39
I found that there is still an issue here related to issue #33822: simple evaluation result is shown before a complex console.log output due to async processing of DAP `output`. I will look into fixing this.

Repro: evaluating `console.log({foo: 'bar'}); 123` shows `123` followed by `Object {foo: "bar"}`.

**Comment by isidorn** [comment] 2019-09-19 08:28
@dgozman yeah, the cause is exactly what you mentioned, the `output` event comes asyncly.
Not sure how to easily fix this without introducing some order to the incoming messages. Looking forward to seeing your approach.
