### ISSUE TITLE
High contrast mode doesn't revert with Windows 11

### ISSUE THREAD

**Issue by javierdlg** [microsoft/vscode#140461] opened 2022-01-10 22:49 UTC
Issue Type: <b>Bug</b>

I enabled Aqua high contrast mode for Windows 11 and after reverting it without closing VS code, it didn't revert to the non-contrast theme. I restarted the computer and VS Code but the application doesn't revert to non-high contrast mode. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (41.58GB free)|
|Process Argv|--crash-reporter-id d43f4fdf-978c-4d8c-aa8f-48432a90cccb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.17
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
py55gd98:30419165

```

</details>

**Comment by javierdlg** [comment] 2022-01-10 22:50
Here's a screenshot of what it looks like. You can see VS in normal theme in the background:
![image](https://user-images.githubusercontent.com/2334756/148851350-e6000415-4497-4df5-aeda-5fe645625829.png)

**Comment by IllusionMH** [comment] 2022-01-11 00:00
Looks like duplicate of #138548

**Closed** 2022-01-11 06:34 UTC
Labels: triage-needed
