### ISSUE TITLE
User Snippets add extra unneeded characters

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#26551] opened 2017-05-12 12:09 UTC
- VSCode Version: 1.12+
- OS Version: MacOS

Steps to Reproduce:

1. add this javascript snippet in user snippet (there are tab in it) : 
```
	"function () =>": {
		"prefix": "function () =>",
		"body": [
			"($1) $2=> {",
			"	$3",
			"}"
		],
		"description": "Créer une function fléchée"
	},
```
2. invoke it

You will get something like that, with an extra comma :
![snippet](https://cloud.githubusercontent.com/assets/5599375/25997462/63e91c50-371c-11e7-8d21-1e6f62592c3c.gif)

**Comment by jrieken** [comment] 2017-05-15 07:30
The problem is that there is the tab-character in your snippet (preceding `$3`). We have updated our parser to be more strict and will ship a better variant early this week. In short, use `\t` for inserting tabs

**Comment by jrieken** [comment] 2017-05-15 07:31
closing as dupe of https://github.com/Microsoft/vscode/issues/25938

**Closed by jrieken** 2017-05-15 07:30 UTC
Labels: question
