### ISSUE TITLE
Weird error notification when checking for updates when clock is out of sync

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#94013] opened 2020-03-31 17:57 UTC
![image](https://user-images.githubusercontent.com/35271042/78059062-170b3b00-733e-11ea-8863-03e3910fe518.png)

I opened my parallels Windows VM that hasn't been turned on in a month and when I tried to check for updates i kept getting this weird error. Turns out my clock had reset back to the last time I had used it and after syncing the time that update service started working. However, I had never seen this error message before and it would be great if this was more human and less 🤖 .

**Comment by joaomoreno** [comment] 2020-04-01 05:50
If this is really related to the clock, the issue is somewhere deep in Chrome or Window's network stack, since none of our code depends on the clock. Closing it as it seems a very infrequent occurrence.

**Closed by joaomoreno** 2020-04-01 05:50 UTC
