### ISSUE TITLE
VS Code does not update the program in a custom installation path.

### ISSUE THREAD

**Issue by kbumsik** [Microsoft/vscode#25772] opened 2017-05-02 10:36 UTC
- VSCode Version: 1.10.1 and previous, 
- OS Version: Windows 10 Pro Insider Preview, x64

I installed VS Code in a custom path, `C:\Office`. When I update the program the new version of VS Code is installed in `C:\Program Files (x86)\Microsoft VS Code`.

Steps to Reproduce:

1. Install VS Code in `C:\Office`.
2. Update VS Code when it ask me to update it to a newer version.
3. The updater will install the program in a default path, `C:\Program Files (x86)`, while it does not ask me anything about the installation path.
4. Now I have two VS Code installed in the system, the one is in `C:\Office\Microsoft VS Code` and the other is in `C:\Program Files (x86)\Microsoft VS Code`. 
5. When I open `C:\Office\Microsoft VS Code\Code.exe` it will ask me to update the program again because the program remains in the same version.

**Comment by mjbvz** [comment] 2017-05-02 14:54
Thanks for the report. Updates for other install locations falls under #329 which tracks a portable version of VSCode.

Closing as a duplicate of #329

**Closed by mjbvz** 2017-05-02 14:54 UTC
Labels: duplicate, feature-request
