### ISSUE TITLE
ini file with unmatched quotes stops highlighting

### ISSUE THREAD

**Issue by pedro-w** [Microsoft/vscode#23658] opened 2017-03-30 10:06 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|clojure|avli|0.5.3|
|vscode-svgviewer|cssho|1.4.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.0|
|svg-snippets|sidthesloth|1.0.0|;

---

I am unsure if there is a formal spec for .ini files or what the VSCode implementation is working to, but if I have a value with an unmatched double quote, the syntax colouring goes wrong in subsequent lines.

Steps to Reproduce:
---

1. Open an ini file with an unmatched double quote (this is an example from teraterm)
2. See highlighting
![Example](https://cloud.githubusercontent.com/assets/22172519/24499167/ae396d88-1538-11e7-8530-35ec630b09f5.jpg)

**Comment by aeschli** [comment] 2017-03-31 07:43
duplicate of #21804

**Closed by aeschli** 2017-03-31 07:43 UTC

**Comment by pedro-w** [comment] 2017-03-31 07:55
Thanks for your swift response. This is not quite a duplicate of the issue now in textmate/ini.tmbundle#3 - that is for apostrophes ' and this is for double quotes ".
