### ISSUE TITLE
Add bidi bracket support (enable LayoutNG)

### ISSUE THREAD

**Issue by ebraminio** [microsoft/vscode#78867] opened 2019-08-10 14:11 UTC
As [this](https://github.com/Microsoft/vscode/issues/65648#issuecomment-520146687) vscode doesn't support bidi brackets. What is that? http://www.unicode.org/notes/tn39/

Sample code: "سشی (شسی)"
Actual:
![image](https://user-images.githubusercontent.com/833473/62822831-1b5fc980-bb9e-11e9-83e9-7d09c9460970.png)

Expected:
![image](https://user-images.githubusercontent.com/833473/62822832-23b80480-bb9e-11e9-8a12-65b5d51a996c.png)

LayoutNG which is enabled in Chrome 76 will enable this for text in html, test this `data:text/html;charset=utf8,"%D8%B3%D8%B4%DB%8C (%D8%B4%D8%B3%DB%8C)"` (put it in address bar) when LayoutNG experiment is enabled and disabled in `about:flags` of Chrome (which in Chrome 76 may is default enabled) but I don't think that helps here as AFAIK monaco uses a different and internal bidi code.

**Comment by gggin** [comment] 2019-09-25 03:23
can we show bidi control charactor in text editor? for easy edit words. like U+202A U+202B U+202C

**Comment by alexandrudima** [comment] 2019-10-25 12:55
This specific case works in Insiders, so it is fixed by our adoption of Electron v6.

**Comment by alexandrudima** [comment] 2019-10-25 18:49
Very interesting, this all depends on rendering whitespace or not ...

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/67596396-eb6d9e80-f768-11e9-864b-7bc67c57f332.gif)

**Comment by zspitz** [comment] 2020-01-28 18:34
@ebraminio @alexdima  I'm using VS Code 1.41.1, with Electron 6.1.5 (not Insiders) and the brackets are still rendered improperly when **Render Whitespace** is not selected.

Without **Render Whitespace**:
![image](https://user-images.githubusercontent.com/312166/73293865-58cc1800-420d-11ea-8c6c-b1ba784aab74.png)

With **Render Whitespace**:
![image](https://user-images.githubusercontent.com/312166/73293948-7b5e3100-420d-11ea-9e4a-613facce3c60.png)

**Comment by zspitz** [comment] 2020-02-04 13:31
@ebraminio @alexdima I can confirm the difference between when **Render Whitespace** is selected or not, on both release (1.41.1) and insiders (1.42.0-insiders).

But there is another difference: when **Render Whitespace** is selected, the word order is swapped.

![vs code bidi behavior](https://user-images.githubusercontent.com/312166/73745191-25344500-475b-11ea-9c56-dfd1f94242bd.gif)

(The Unicode spec uses the convention of lowercase letters for LTR scripts and uppercase for RTL. I'm following that here. Also, the actual sequence of the characters is in alphabetical order: `ABCD`, even if in an RTL script it would be displayed `DCBA`.)

I think there are a two distinct issues here:

1. **Paragraph direction** -- VS Code has no notion of RTL at the paragraph level. Therefore, when **Render Whitespace** is off, neutral characters such as spaces within the RTL text take on the surrounding direction: RTL. The words thus get rendered in their proper (RTL) order:

        HGFE DCBA
        RRRRRRRRR

    But neutral characters at the beginning or end of the paragraph are treated as LTR, because the paragraph end is always LTR in VS Code. (`\n` represents a single newline character.)

        _DCBA_\n
        LRRRRLL

    Therefore (again, when **Render Whitespace** is off(, the brackets within the RTL text are treated as RTL (and identified as part of a [bracket pair](http://www.unicode.org/reports/tr9/#Resolving_Neutral_Types)), but the brackets at the beginning or end of the paragraph are resolved to LTR.

        (HGFE (DCBA
        LRRRRRRRRRR

    The same thing happens with `"`, as in @ebraminio 's [original post](https://github.com/microsoft/vscode/issues/78867#issue-479271156):

        "DCBA) DCBA)"
        LRRRRRRRRRLL

2. **'Render Whitespace' uses an LTR character** -- I suspect that the character used for spaces in **Render Whitespace** is an LTR character, which ends up like this:

        "DCBA (DCBA)"
        LRRRRLLRRRRL

    but this is also incorrect, because now the RTL run is split into two by the LTR space-representing character; the opening parenthesis follows suit and becomes LTR, so now it's in the same direction as the closing parenthesis. But the words are swapped, like so:

        DCBA HGFE
        RRRRLRRRR

    instead of

        HGFE DCBA
        RRRRRRRRR

**Comment by ebraminio** [comment] 2020-03-16 04:22
Bad idea on closing the issue, #65648 was its parent issue with enough 'stars', separated it to make it clear what developers should do thus the action encourages mixing the issues.

**Comment by alexdima** [comment] 2020-03-30 09:09
I have a bit more understanding now after my fix for #90019. LayoutNG fixes several bidi rendering issues, irrespective of what we do.

So, when using Chromium + LayoutNG, `"سشی (شسی)"` renders correctly without any code change on our side:
![image](https://user-images.githubusercontent.com/5047891/77895041-74d45000-7276-11ea-9b3f-a013c709a53b.png)

But for #88873 , we actually run VS Code with LayoutNG disabled because of https://bugs.chromium.org/p/chromium/issues/detail?id=1043471 . Thus, our current rendering is:
![image](https://user-images.githubusercontent.com/5047891/77895272-d2689c80-7276-11ea-9515-476a299dbbbf.png)

Thiss can be verified by removing this line: https://github.com/microsoft/vscode/blob/80cd0ee564caed53f0a7f9fe8fba5b781cbbf12d/src/main.js#L179

cc @bpasero @deepak1556

**Comment by deepak1556** [comment] 2020-03-31 04:39
Here is the fix chromium landed for layoutNG https://chromium-review.googlesource.com/c/chromium/src/+/1837435 , we can try adopting it for non-layoutNG codepath to fix this issue.

**Comment by ebraminio** [comment] 2020-03-31 05:39
Having filed two of the bugs linked on the patch there, that was less about bidi bracket itself but some other bracket related issue thus enabling LayoutNG in vscode should be first priority I believe.

**Comment by alexdima** [comment] 2020-03-31 13:46
@deepak1556 I will explore next milestone a different way to mitigate #88873 ... It would mean for us to move away from `::before`, `::after` pseudo elements in those editor decorations. If that works OK, then we should be fine to enable LayoutNG again. So I would like to first try that before trying to bring in the patch.

**Comment by deepak1556** [comment] 2020-08-28 21:00
The fix will be available in upcoming stable release.

**Closed by deepak1556** 2020-08-28 21:00 UTC
Labels: editor-RTL, editor-rendering, fixed-in-electron-9, upstream
