### ISSUE TITLE
editor.showFoldingControls -> always didn't work on Linux

### ISSUE THREAD

**Issue by PureDarkChoco** [Microsoft/vscode#35958] opened 2017-10-10 06:26 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (dcd1aa35dfa590b4a528e1ab55e957002f430f17, 2017-10-10T05:22:10.911Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.3
file-icons|fil|1.0.5
auto-close-tag|for|0.5.1
ftp-sync|luk|0.3.3
color-highlight|nau|2.3.0
highlight-words|rsb|0.0.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1. "editor.showFoldingControls": "always" didn't work on Linux
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment] 2017-10-10 08:47
duplicate of #35839

**Closed by aeschli** 2017-10-10 08:47 UTC
Labels: extensions
