### ISSUE TITLE
Different tsconfig lookup behaviour between tsc and tsserver

### ISSUE THREAD

**Issue by tkrotoff** [Microsoft/vscode#716] opened 2015-11-26 18:37 UTC
Context: you can add all your .d.ts files inside tsconfig.json instead of writing `/// <reference path="my.d.ts" />` in each .ts file (way better).
It works fine with `tsc`.

Unfortunately it does not always work with vscode.

Example: https://github.com/tkrotoff/vscode-tsconfig.conf-issue
[test/tsconfig.json](https://github.com/tkrotoff/vscode-tsconfig.conf-issue/blob/master/test/tsconfig.json) references files outside its directory and vscode fails while `tsc` is fine with it.

![screen shot 2015-11-26 at 19 16 56](https://cloud.githubusercontent.com/assets/643434/11429150/4f3fc188-9474-11e5-81fa-11fe3e735b0b.png)

**Comment by dbaeumer** [comment] 2015-11-30 10:02
@tkrotoff when running tsc in the src directory it will only compile Foo.ts since the tsconfig.json file inside the src directory only lists that file. If you run the tsc command inside the test folder it will use the tsconfig.json from there.

If you open the Foo.spec.ts file we try to find a tsconfig.json file to use. The rule the tsserver uses is to look for the first tsconfig.json file in the parent directory chain. We discussed whether we should have a mapping to tell VSCode which tsconfig.json file to use for which ts file but that seemed unnecessary complicated. 

If you move you Foo.spec.ts file into the test folder and update the tsconfig.json file accordingly everything should work as expected. 

In general VSCode is using the tsserver from https://github.com/Microsoft/TypeScript and the tsconfig.json lookup behavior is defined in the tsserver. I will move the issue to the TypeScript repository since a fix for this needs to be implemented in the tsserver.

**Comment by dbaeumer** [comment] 2015-11-30 10:05
Adjusted the title to reflect the problem in TS land. To reproduce do the following after cloning the example:

* cd test
* tsc -p .

Observe: the Foo.spec.ts file is compiled nicely

Try to open Foo.spec.ts in a editor like Sublime or VSCode. The tsserver always picks the tsconfig.json file in the src directory using its defined lookup rules.

**Comment by dbaeumer** [comment] 2015-11-30 10:06
This issue was moved to Microsoft/TypeScript#5828

**Closed by dbaeumer** 2015-11-30 10:06 UTC
