### ISSUE TITLE
Maximixed VS Code dragged and droped to new monitor doens't properly maximizes

### ISSUE THREAD

**Issue by naeemullah** [microsoft/vscode#75808] opened 2019-06-20 02:06 UTC
Issue Type: <b>Bug</b>

Steps:
- Working with two monitors
- Open and maximize vscode in one monitor
- Now drag from the vscode title bar and drop on top of the second monitor screen (to move to other monitor in maximized mode)
- The vscode will maximize but with a gap on top (see screenshot)
- Once restored and maximized again in the same monitor, the gap goes away and it maximises properly

![vscode-error](https://user-images.githubusercontent.com/2527081/59813153-d664a700-9353-11e9-9071-ee785255bcda.png)

Regards,
Naeem Khan

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yume-chan** [comment] 2019-06-21 03:31
Duplicate of #52265

It's a problem of Windows itself and had been addressed in Windows 10 1809, so Electron and Code team decided to not workaround it for the old version of Windows you are using (1803).

**Closed** 2019-06-24 06:49 UTC
