### ISSUE TITLE
do not popup autosuggest window when there is only one suggestion and editor.inlineSuggest.enabled and editor.suggest.showSuggestionPreview are both true

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#144564] opened 2022-03-07 08:04 UTC
Requirement: <Title says it all.>

Reason:

A popup window is distracting. In this case it adds absolutely no value. It rather distracts (sometimes even forces me to press escape to dismiss it.) 

This will improve my code writing flow. 
I think in general, most developers 'in the flow' will like this feature.

**Comment by jrieken** [comment] 2022-03-07 09:22
closing as /duplicate of https://github.com/microsoft/vscode/issues/126375

**Closed** 2022-03-07 09:23 UTC
Labels: *duplicate
