### ISSUE TITLE
Codelens text is not visible unless mouse is clicked in the document

### ISSUE THREAD

**Issue by snnsnn** [microsoft/vscode#112374] opened 2020-12-12 21:15 UTC
- VSCode Version:
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:43:50.597Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-54-generic snap

- OS Version:
Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-54-generic
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 62,8 GiB of RAM
Graphics Processor: AMD VERDE

Codelens text is not shown unless mouse is clicked. Moving mouse around has no effect.

Here is the screencast I took:

![codelens demo](https://user-images.githubusercontent.com/16473630/101994910-359c4100-3cd7-11eb-8a85-de8603313c8a.gif)

Steps to Reproduce:

Actually it was working as expected untill Vscode became unresponsive and I terminated it via system monitor/process table by killing all instances of `code`. When I restarted it, release notes for 1.52.0 was on display. It behaved as in the gif then on, even after several reloads and computer restart. I checked all codelens related settings on, still no change.

Here is the CodelensProvider: 

```typescript
import { CancellationToken, CodeLens, CodeLensProvider, EventEmitter, Range, TextDocument } from 'vscode';

export class CodelensProvider implements CodeLensProvider {
  private _onDidChangeCodeLenses: EventEmitter<void> = new EventEmitter<void>();

  public constructor() {
    this._onDidChangeCodeLenses.fire();
  }

  public provideCodeLenses(document: TextDocument, token: CancellationToken): CodeLens[] | Thenable<CodeLens[]> {
    const lenses = [];
    for (let i = 0; i < 5; i++) {
      const range = new Range(i, i, i, i);
      lenses.push(new CodeLens(range));
    }
    return lenses;
  }

  public resolveCodeLens(codeLens: CodeLens, _token: CancellationToken) {
    codeLens.command = {
      title: `Example Code Lens`,
      tooltip: "Tooltip provided by sample extension",
      command: "codelens-sample.codelensAction",
    };
    return codeLens;
  }
}
```

And I registered it for all languages on activation:

```typescript
const codelensProvider = new CodelensProvider(new Range(0, 0, 0, 0));
languages.registerCodeLensProvider("*", codelensProvider);
```

Does this issue occur when all extensions are disabled?:
Yes, nothing changes.

**Comment by jrieken** [comment] 2020-12-14 08:56
> Codelens text is not shown unless mouse is clicked. Moving mouse around has no effect.

Cannot reproduce. Works for me without mouse interaction and btw it is very, very unlicked due to the mouse because there no such code like "update after click". Are you sure you extension is responsive and not blocked by another extension which then would prevent resolvingCodeLens from being called successfully?

**Comment by snnsnn** [comment] 2020-12-16 10:20
@jrieken Hi,

Here is the development repo for the code I use: https://github.com/snnsnn/vscode-aid-extension. It has launch script to run in debug mode and npm scripts, I also added `aid-1.0.0.vsix` to repo in case you want to try it.

What extension does is, listens for `onDidChangeTextEditorSelection`  and updates itself accordingly to be above the active line. As you see in the gif below, codelens is not visible after line change, unless focus is moved to another window (firefox) and returned back.

![demo](https://user-images.githubusercontent.com/16473630/102335124-8c886b80-3fa0-11eb-8d61-4d81f519cd3a.gif)

**Comment by jrieken** [comment] 2020-12-16 10:32
So, this is not good: https://github.com/snnsnn/vscode-aid-extension/blob/6aae721c8ab2236b8cc5c63bc0d4be0c44fef710/src/CodelensProvider.ts#L28

It seems that your provider doesn't resolve code lenses in some cases and that's a problem. It should esp not rely on the active editor to resolve code lenses because code lenses can be resolved without the document showing in an editor. 

Please change your provider so that it always returns a valid code lens and then check if your problem still exists

**Closed** 2020-12-23 11:39 UTC
Labels: code-lens, needs more info
