### ISSUE TITLE
Provide a way to close/supress all notifications

### ISSUE THREAD

**Issue by nertim** [Microsoft/vscode#42121] opened 2018-01-24 21:53 UTC
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. open any large C# solution with unresolved dependencies
2. have to click 'close' for all the warning/info/etc.

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/493476/35359143-d0e3fe18-010d-11e8-99a1-27a1ff062db0.png)

**Comment by mjbvz** [comment] 2018-01-25 00:06
Duplicate of #22388

**Closed by mjbvz** 2018-01-25 00:06 UTC
Labels: extensions
