### ISSUE TITLE
Switching editor groups multiple times from Markdown preview locks keyboard input

### ISSUE THREAD

**Issue by David-Else** [microsoft/vscode#110948] opened 2020-11-19 13:30 UTC
Open a markdown preview and keep switching between it and the document using `ctrl-1` `ctrl-2` and soon it will stop on the preview and you will be unable to use ANY keyboard shortcut to escape. This is an accessibility nightmare as the only way out I can find is to use a mouse to take over.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 4.18.0-193.28.1.el8_2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3462)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.50GB (0.23GB free)|
|Process Argv|--disable-extensions --no-sandbox --crash-reporter-id 24ebaa02-ef6c-4068-a0ae-9ad3f3922375|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by mjbvz** [comment] 2020-11-19 20:15
Duplicate of #110276

**Closed by mjbvz** 2020-11-19 20:15 UTC
