### ISSUE TITLE
outline click on symbol cause open new empty file

### ISSUE THREAD

**Issue by yaboroda** [Microsoft/vscode#51312] opened 2018-06-07 08:27 UTC
Issue Type: <b>Bug</b>

It concider new feature Outline with php files. With json and js files it works correctly.

With php It correctly shows list of symbols and "follow cursor" option works. But when i click on symbol it open new empty file instead of set cursor to clicked symbol.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.16.12-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2732)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.75GB (0.41GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
activitusbar|Gru|0.0.12
code-settings-sync|Sha|2.9.2
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
folder-indexing|ast|0.2.0
vscode-twig-pack|baj|1.0.0
markdown-preview-github-styles|bie|0.1.2
auto-close-tag|for|0.5.6
compareit|in4|0.0.2
case-sensitive-add-next|jac|0.0.6
center-editor-window|kai|2.1.1
php-symbols|lin|2.1.0
hg|mrc|1.2.3
vscode-apache|mrm|1.1.1
python|ms-|2018.5.0
php-docblocker|nei|1.6.0
vscode-yaml|red|0.0.12
highlight-matching-tag|vin|0.4.4
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment] 2018-06-07 14:14
/duplicate of https://github.com/Microsoft/vscode/issues/51297

**Closed** 2018-06-07 14:14 UTC
Labels: *duplicate, new release
