### ISSUE TITLE
Print your code feature?

### ISSUE THREAD

**Issue by genx128** [microsoft/vscode#96261] opened 2020-04-27 13:50 UTC
Issue Type: <b>Feature Request</b>

I have been noticing that there is no native print option. Why? I may want to print my code and look at it on paper to help find bugs or plan code away from the computer. Can we please have a native print feature added?  

VS Code version: Code - Insiders 1.45.0-insider (0778354f3a6a2c21b7f738a5e6b02e2f1c765e73, 2020-04-27T05:39:56.514Z)
OS version: Darwin x64 19.4.0

**Comment by alexr00** [comment] 2020-04-27 14:12
Duplicate of https://github.com/microsoft/vscode/issues/5953

**Closed by alexr00** 2020-04-27 14:12 UTC
