### ISSUE TITLE
TSDoc codeblocks mangle the @ sign

### ISSUE THREAD

**Issue by freshgum-bubbles** [microsoft/vscode#185018] opened 2023-06-13 13:35 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.0 (Insiders)
- OS Version: Windows 11 Pro, 22H2

Steps to Reproduce:

1. Use a codeblock in TSDoc, as follows:
```ts
/**
 * ```
 * @Test() class A {}
 * ```
 */
```

Expected Result: It renders correctly, without the `@` symbol being interpreted as me
wanting to use a specific TSDoc function.

Actual Result:
![image](https://github.com/microsoft/vscode/assets/85623267/021dbaa1-089b-4c88-b2f9-ce8f067234b7)

**This isn't a new issue by any means.**
It was publicly reported back in 2020: https://github.com/microsoft/tsdoc/issues/216
However, the user was told to post it here.  
I can't find any pre-existing issues for the above problem.

**Comment by mjbvz** [comment] 2023-06-13 16:16
Duplicate of https://github.com/microsoft/TypeScript/issues/49273

**Closed by mjbvz** 2023-06-13 16:16 UTC
