### ISSUE TITLE
Restore all windows after "Close All Windows" is triggered if configured

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#30377] opened 2017-07-11 08:25 UTC
- VSCode Version: 1.13.1
- ProductName: Mac OS X
- ProductVersion: 10.12.5
- BuildVersion: 16F73

```json
"window.reopenFolders": "all"
```
Is not working properly, because if I close all VS Code windows and I open again VS Code I get empty window, I call it untitled project, because there's nothing.

**Comment by bsvipas** [comment] 2017-07-11 08:29
On Linux Ubuntu everything was OK, if I close VS Code with my for e.g. folder 'test' and I open again VS Code, VS Code remembers it and opens my folder 'test', but on Mac something is wrong, because if I close my for e.g. folder 'test' and open again VS Code, VS Code doesn't remembers it and opens untitled project.

**Comment by bsvipas** [comment] 2017-07-11 08:33
Okey, I get it, if I close VS Code with cmd + Q when it remembers my last folders, but if close it just with X it doesn't so I don't know if it's still a problem or no.

**Comment by aaccioly** [comment] 2017-07-11 09:14
Hi @bpasero , I guess that this is the same as when we right click the icon and select "Close all Windows" in Issue #207. Same problem with `window.restoreWindows": "all"` in insiders build.

**Comment by bpasero** [comment] 2017-07-11 16:42
I would argue that "Close All Windows" should not restore the windows because you are actually closing all of them. In the same way if you close a single window we would never restore it.

If you use File > Exit the windows will restore properly and that is the intent of the window.reopenWindows setting.

**Comment by fr43nk** [comment] 2017-07-12 07:04
Ok, I can see your concern but actually I don't close vscode that way :) Perhaps it's possible to add a configuration option, to restore the windows, if I choose "close all windows" from the  windows taskbar.

**Comment by aaccioly** [comment] 2017-07-12 07:53
>  I don't close vscode that way :) 

This. I wasn't even aware that there was such an opinion, plus the fact that it behaves differently than when we directly close the window is weird.

When I have a single window I close it by pressing the X button. When I enable the "restore tabs" behaviour all editors and browsers that I can think of restore all tabs. When dealing with "Close All Windows" I would expect the same behaviour.

**Comment by jvmonjo** [comment] 2017-09-26 13:21
Not sure if it is the same problem but I can reproduce the problem under Linux (Gnome):

- Version 1.16.1
- Commit 27492b6bf3acb0775d82d2f87b25a93490673c6d
- Date 2017-09-14T16:26:20.018Z
- Shell 1.7.3
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

I have configured:

`
"window.restoreWindows" : "one"
`
But I get an empty window when I reopen FROM DASH BAR. If I open VS Code through app search (Windows Key) everything is properly restored

**Closed** 2017-11-14 13:11 UTC
Labels: feature-request, workbench
