### ISSUE TITLE
Fix strict null errors for encoding.ts and storage.ts

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#62072] opened 2018-10-29 18:24 UTC
* revert https://github.com/Microsoft/vscode/commit/42d4374c8bd3e197398ed681a45fa2b9b9d33478
* run strict null checks, get this tons of errors in unrelated files

**Comment by mjbvz** [comment] 2018-10-29 20:40
This was caused by ec8eb95d700b60059289da5187359d9f5a7716a5 that introduced an include for  'vs/base/node/pfs' into `storage`. `pfs` is not strict null checked so it cannot be included in strict null checked files like `storage`.

Too late in October to fix strict null errors in `encoding`. Moving to November and adding a few other possible owners to this issue

**Closed** 2018-11-05 19:42 UTC
Labels: engineering
