### ISSUE TITLE
Extension host not working

### ISSUE THREAD

**Issue by qmaruf** [microsoft/vscode#176589] opened 2023-03-09 04:51 UTC
Type: <b>Bug</b>

Extension host terminated unexpectedly 3 times within the last 5 minutes.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 5.15.0-051500-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.39GB (9.50GB free)|
|Process Argv|--unity-launch xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--crash-reporter-id 7454aeeb-c148-47fa-be4c-7b3b5360bff2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.20
gitlens|eam|13.3.2
git-project-manager|fel|1.8.2
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.60.0
vscode-edit-csv|jan|0.7.3
pre-commit-vscode|Mar|0.1.0
git-graph|mhu|1.30.0
autopep8|ms-|2022.2.0
flake8|ms-|2023.4.0
pylint|ms-|2023.4.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.20
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
vscode-yaml|red|1.12.1
code-navigation|vik|0.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsccsb:30677849
vscodedisable:30660115
funwalk2:30676043
pythonms35:30680984

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:24
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:24 UTC
Labels: freeze-slow-crash-leak, extension-host
