### ISSUE TITLE
Bug with git commit --amend

### ISSUE THREAD

**Issue by kostyabushuev** [microsoft/vscode#75848] opened 2019-06-20 15:02 UTC
- Version: 1.36.0-insider
- Commit: c3fe2d8acde04e579880413ae4622a1f551efdcc
- Date: 2019-06-20T05:15:32.670Z
- Electron: 4.2.4
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Linux x64 4.18.0-20-generic

Hello
I have bug with `git commit --amend` from UI

Steps to Reproduce:

1. Add file to index, write message and commit. This message has line breaks
![Screenshot from 2019-06-20 19-33-15](https://user-images.githubusercontent.com/31274471/59859285-e43b1c00-9395-11e9-9d1f-ba191ff11eea.png)

2. Then, after changed file you can use `git commit --amend`.
![Screenshot from 2019-06-20 19-34-51](https://user-images.githubusercontent.com/31274471/59859333-f61cbf00-9395-11e9-9705-4dd99c5c9bc8.png)

3. But now we have the bug. New message doesn't have line breaks.
![Screenshot from 2019-06-20 19-40-06](https://user-images.githubusercontent.com/31274471/59859389-0df44300-9396-11e9-8105-fc0e76e3b194.png)

All extensions were disabled.

**Comment by gjsjohnmurray** [comment] 2019-06-21 11:30
Duplicate of #40295

**Closed** 2019-06-24 06:46 UTC
Labels: git
