### ISSUE TITLE
Missing completions for code action kinds

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194121] opened 2023-09-26 10:22 UTC
Testing #194077

I am missing completions for code action kinds when authoring the `notebook.codeActionsOnSave` setting. As soon as a provider is register we do know its kinds and we can update the JSON schema accordingly. This will greatly improve the configuration experience because today configuration is manual/magic. You need to rely on well known or documented code action kinds and copy-paste them

Steps

* use lastest GHINB from `joh/civic-tahr`
* open a GHI notebook
* configure notebook code actions for saving

**Comment by mjbvz** [comment] 2023-09-27 17:01
Duplicate of #161284

**Closed by mjbvz** 2023-09-27 17:01 UTC
