### ISSUE TITLE
Pasting ñ á é í ó ú wrong

### ISSUE THREAD

**Issue by mrbianchi** [microsoft/vscode#96494] opened 2020-04-28 23:29 UTC
steps to reproduce:
copy https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/spanish.txt
paste it into vcode

the chars looks equals but they aren't, try ctrl + f and type che char, it won't find it in the list 
you too can try open the saved file with another editor or browser

**Comment by alexdima** [comment] 2020-04-29 12:06
@mrbianchi  I don't understand what the problem is. When I copy e.g. `acción` from the file you have provided and paste it to VS Code, I see `acción` rendered fine:

![image](https://user-images.githubusercontent.com/5047891/80594054-9a45ac80-8a22-11ea-81ea-34d3db0f40e9.png)

**Comment by mrbianchi** [comment] 2020-04-29 12:32
> @mrbianchi I don't understand what the problem is. When I copy e.g. `acción` from the file you have provided and paste it to VS Code, I see `acción` rendered fine:
> 
> ![image](https://user-images.githubusercontent.com/5047891/80594054-9a45ac80-8a22-11ea-81ea-34d3db0f40e9.png)

the chars looks equals but they aren't, try ctrl + f and type the char in the find field by your own, it won't find it in the list

**Comment by mrbianchi** [comment] 2020-04-29 17:22
Then when I use the keyboard to write ó in chrome to find the char , chrome is normalizing the .txt and/or my typed char making it to match, but the file has an invalid char? That could be affirmative I think, because testing with saveing the file or copying the tiped ó from chrome to VS Code I don't find the error.

So now I think that it isn't a VS Code error, probably is a BIP39 error and I will open the issue there.

Your explanation was very useful, thanks.

**Comment by alexdima** [comment] 2020-04-30 08:04
The search feature built into Chrome is very fuzzy. For example, when I search for `o` it matches both `ó`s. Here is a screenshot:

![image](https://user-images.githubusercontent.com/5047891/80686916-c9632900-8ac9-11ea-8a44-ed4e90e448d7.png)

I guess that makes sense given they are a web browser and people might be opening pages written in a language that users might not have a keyboard layout for, etc.

I will close this issue on our side, because we work as designed.

**Closed by alexdima** 2020-04-30 08:04 UTC
Labels: needs more info
