### ISSUE TITLE
.NET Console.ReadLine() gets incorrect encoding in VSCode integrated terminal

### ISSUE THREAD

**Issue by darkthread** [microsoft/vscode#208015] opened 2024-03-18 14:34 UTC
Type: <b>Bug</b>

Use these code to reproduce the issue:

```cs
Console.WriteLine(
$"Input = {Console.InputEncoding.EncodingName}");
Console.WriteLine(
$"Output = {Console.OutputEncoding.EncodingName}");
Console.Write("Copy and input `中文-English-テスト` to test: ");
var input = Console.ReadLine();
Console.WriteLine($"Text from ReadLine() = {input}");
```
The symptom is that when running the Console.ReadLine() command in the integrated terminal interface, it fails to correctly read Chinese characters and displays garbled output. This issue occurs when using PowerShell [1], bash [2], and Cmd [3]. However, when directly using Cmd.exe [4] or PowerShell [5], the input is read and displayed as expected.

![image](https://github.com/microsoft/vscode/assets/572199/fa9d7bfd-87dc-4539-a9b9-69b11ac8df0e)

I reproduced the issue on VSCode versions 1.87.1 and 1.87.2 on Windows 11.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
add-reference|adr|1.0.2
asp-net-core-switcher|adr|2.0.2
blazor-snippet-pack|adr|2.6.1
csharp-to-typescript|adr|1.12.1
libman|adr|1.0.1
namespace|adr|1.1.2
terminal-commands|adr|1.0.5
toggle-hidden|adr|1.0.2
user-secrets|adr|2.0.1
vscode-sqlite|ale|0.14.1
markdown-mermaid|bie|1.22.0
path-intellisense|chr|2.8.5
gitignore|cod|0.9.0
vscode-eslint|dba|2.4.4
netcore-editorconfiggenerator|dog|0.2.0
netcore-extension-pack|dog|1.10.0
netcore-snippets|dog|6.0.3
quicktype-refresh|dog|1.0.2
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.8
monkey-c|Gar|1.0.10
copilot|Git|1.174.0
copilot-chat|Git|0.13.1
go|gol|0.41.2
rest-client|hum|0.25.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|1.0.0
csharpextensions|kre|1.7.3
git-graph|mhu|1.30.0
vscode-bicep|ms-|0.26.54
vscode-docker|ms-|1.29.0
csdevkit|ms-|1.4.29
csharp|ms-|2.22.3
vscode-dotnet-runtime|ms-|2.0.2
vscodeintellicode-csharp|ms-|0.1.26
aks-devx-tools|ms-|0.1.2
vscode-kubernetes-tools|ms-|1.3.15
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.8
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.0.0
remote-explorer|ms-|0.4.3
vs-keybindings|ms-|0.2.1
vscode-nuget-gallery|pat|0.0.24
vscode-versionlens|pfl|1.9.2
platformio-ide|pla|3.3.3
java|red|1.28.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
markdown-preview-enhanced|shd|0.8.13
msbuild-project-tools|tin|0.6.0
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
gitblame|wad|10.10.0
vscode-todo-highlight|way|1.0.5
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
jchc7451:30973076

```

</details>

**Comment by meganrogge** [comment] 2024-03-25 21:01
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-03-25 21:01 UTC
