### ISSUE TITLE
Debugging NodeJS with ES6 modules pops up a new tab on breakpoint

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#45750] opened 2018-03-14 10:46 UTC
- VSCode Version: 1.21.0
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

1. Use node version 9.8.0
2. fire up a project with --experimental-modules flag
3. Set a breakpoint

Does this issue occur when all extensions are disabled?: Yes

Image attached of issue. A new tab pops up when the breakpoint is hit saying 'read-only core module (skipped by 'skipFiles').

![screen shot 2018-03-14 at 5 46 00 pm](https://user-images.githubusercontent.com/9585787/37397967-97e0240c-27af-11e8-8696-1a17e91359a7.png)

**Comment by isidorn** [comment] 2018-03-14 11:04
Not sure what is unexpectated behavior here. Assinging to @roblourens since this is coming from node2 debug adapter
fyi @weinand

**Comment by roblourens** [comment] 2018-03-15 03:58
Duplicate of https://github.com/Microsoft/vscode-node-debug2/issues/158 and https://github.com/Microsoft/vscode-node-debug2/issues/157

**Closed by roblourens** 2018-03-15 03:58 UTC
Labels: debug, feature-request
