### ISSUE TITLE
[css] show styles found in html

### ISSUE THREAD

**Issue by sqnkov** [Microsoft/vscode#15965] opened 2016-11-23 14:45 UTC
Is it possible to have classes that are declared only in the markup to be shown trough intellisense in our styles?

Is it possible for the class caching to **_listen_** for added/removed classes from both the styles and markup instead of this happening @ startup or doing it manually?

![image of class caching](http://i.imgur.com/O7NjEUW.gif)

Right now the exact opposite is possible through the [**HTML CSS Class Completion plugin**](https://github.com/Zignd/HTML-CSS-Class-Completion) , but it will be great if one can do the opposite as well. Meaning - when I type a dot in a stylesheet, intellisense should pop-up a list with all the available classes in my html, which do not exist in my current styles.

I know this is more like an IDE feature, but I would love to hear Your opinions about it.

Thanks in advance!

**Comment by aeschli** [comment] 2016-11-23 18:31
We currently have no plans to go across files in CSS and HTML.

**Comment by aeschli** [comment] 2017-12-04 16:45
duplicate of #28442

**Closed by aeschli** 2017-12-04 16:45 UTC
Labels: css-less-sass, feature-request
