### ISSUE TITLE
intellisense for nodejs not working

### ISSUE THREAD

**Issue by justakgupta** [microsoft/vscode#78702] opened 2019-08-08 12:39 UTC
Issue Type: <b>Feature Request</b>

Intellisense support for nodejs is not working in my VS code app. Details below.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.1.7601

**Comment by IllusionMH** [comment] 2019-08-08 14:19
Are you sure it is feature request and not a Bug?

> Details below.

There is only VS Code and OS versions.
Could you provide actual details about extensions, project setup and what actually doesn't work (how you observe this).

/needsMoreInfo

**Comment by mjbvz** [comment] 2019-09-23 21:53
Closing as more information is needed from the original poster to investigate this

**Closed by mjbvz** 2019-09-23 21:53 UTC
Labels: needs more info
