### ISSUE TITLE
How to show button fold code (-) and (+) by default?

### ISSUE THREAD

**Issue by ttn10** [Microsoft/vscode#16369] opened 2016-12-02 10:18 UTC
Hi, please check this image :)
http://i.imgur.com/AeAPvv3.png

**Comment by chrmarti** [comment] 2016-12-02 20:30
Not sure what the question is, please clarify. You can enable/disable folding with the `"editor.folding"` setting.

**Comment by mrmlnc** [comment] 2016-12-02 20:44
@chrmarti, I think that @ttn10 has in mind: show `[-]` and `[+]` buttons always without mouse Hover.

**Comment by ttn10** [comment] 2016-12-03 02:33
Yes, i want to always  show `[-]`, current `[-]` show only via hover
default, `[+]` always show when user click to `[-]`

**Comment by alexandrudima** [comment] 2016-12-13 10:11
fyi @aeschli

**Comment by aeschli** [comment] 2016-12-13 11:26
duplicate of #3911

**Closed by aeschli** 2016-12-13 11:26 UTC
Labels: editor-folding, feature-request, ux
