### ISSUE TITLE
formating html bug in <script></script> tag

### ISSUE THREAD

**Issue by ladyrick** [Microsoft/vscode#39405] opened 2017-12-01 08:07 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
cpptools|ms-|0.14.3
vetur|oct|0.11.3

---

Steps to Reproduce:

1. Add a ```<script>``` tag with both "src" attr and a few space as inner text, like
```<script src="test.js">        </script>```. Make sure they are all in one line.
2. Format the html.
3. Then you would see that the ```<script src="test.js">``` is gone. Only ```</script>``` left.

Reproduces without extensions: Yes.
By the way, I made a gif to show this bug.
![gif](https://user-images.githubusercontent.com/10379994/33473472-8b8f3c8c-d6b1-11e7-9311-59b792e4bf78.gif)

**Comment by aeschli** [comment] 2017-12-01 08:57
duplicate of #36574, fixed in 1.19

**Closed by aeschli** 2017-12-01 08:57 UTC
Labels: html
