### ISSUE TITLE
Can't edit with VSCode

### ISSUE THREAD

**Issue by YSHIDM** [Microsoft/vscode#12857] opened 2016-09-28 03:38 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.Backspace键不能删除只是左移光标
2.回车键只能换行

**Comment by octref** [comment] 2016-09-28 04:57
Please use English for reporting issues. Thanks.

As for the issue, do you have Vim extension installed?

**Comment by octref** [comment] 2016-09-29 16:38
Translation:

Steps to Reproduce:

1. Backspace key only moves cursor to left, not deleting anything.
2. Enter key only goes to next line.

**Comment by joaomoreno** [comment] 2016-09-30 08:15
Does it reproduce with `--disable-extensions`?

**Comment by octref** [comment] 2016-10-04 22:32
Closing as this is exactly Vim behavior.

If this isn't the cause feel free to reopen.

**Closed** 2016-10-04 22:32 UTC
Labels: caused-by-extension
