### ISSUE TITLE
Visual studio code intellisense set to javascript lower version

### ISSUE THREAD

**Issue by akvaliya** [Microsoft/vscode#43200] opened 2018-02-08 11:26 UTC
I am using visual studio code 1.20.0

I am not sure when but after some updates vs code intellisense is giving ES6 output in every js file.

I am developing angularjs project & i simply don't want to use es6.

Currently i am getting below code using intellisense.

    for (let index = 0; index < array.length; index++) {
        const element = array[index];
        
    }
    
    array.forEach(element => {
        
    });

I want it like it was before. Like below

    for (var index = 0; index < array.length; index++) {      
    }
    
    array.forEach(function(element) {
        
    });

How can i set javascript to lower version. I have **not added any plugin** in my workspace.

Can anyone tell me how to achieve this.

**Comment by mjbvz** [comment] 2018-02-08 18:44
Duplicate of #37842

We upgraded our small set of built-in snippets to target es6 because this is what most developers are now working in. If you want to write es5 directly, please look in the marketplace for an extension that supplies es5 js snippets or create your own snippets.

**Closed by mjbvz** 2018-02-08 18:44 UTC
Labels: javascript
