### ISSUE TITLE
Toolbar buttons do not have names with Accessibility Insights, JAWS or Narrator

### ISSUE THREAD

**Issue by keford** [microsoft/vscode#147346] opened 2022-04-13 05:51 UTC
Issue Type: <b>Bug</b>

1. Install and launch Accessibility Insights for Windows.
2. Open VS Code and move keyboard focus to the toolbar.
3. Press Shift+F9 to have Accessibility Insights show details for the item with focus.
4. Run Narrator, ensuring Scan Mode is off and move through the toolbar buttons.

Result:
At steps 3 and 4 the buttons on the toolbar are nameless.

Note:
As far as I can tell, the buttons are using the title tag to create their accessible names.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.93GB free)|
|Process Argv|--crash-reporter-id c1b0fa0a-6432-4d9f-b2d7-f53fdca10025|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-04-13 06:34
Looks like a duplicate of #146658 which just got fixed. Can you test with today's build of Insiders?

**Closed** 2022-04-13 08:55 UTC
Labels: accessibility, *duplicate, new release
