### ISSUE TITLE
[View] Extensions board is broken after Code update

### ISSUE THREAD

**Issue by quangkieu** [microsoft/vscode#97851] opened 2020-05-14 22:21 UTC
Issue Type: <b>Bug</b>

After I update Visual Studio Code, the Extenstion views is broken, it could not list or search for any extensions but most of enabled extions that I am using is still function. I did not test all enabled extension.

Even when using "Disable all extensions" and restart still have the same problem.

This is error that I got from Developer Tool
Failed to load resource: net::ERR_FILE_NOT_FOUND    file:///C:/Users/<username>/.vscode/extensions/vscode-icons-team.vscode-icons-10.1.1/icons/default_undefined.undefined

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|19%|
</details><details><summary>Extensions (92)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vbscript-language-server-client|and|1.1.0
vscode-tidyhtml|anw|1.10.0
atlascode|atl|2.6.0
vagrant|bbe|0.5.0
xml2json|bui|1.2.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.1.3
transformer|dak|1.6.0
vbscript|Dar|1.0.4
markdown-table-prettify|dar|2.4.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-command-runner|edo|0.0.113
tslint|eg2|1.0.44
LogFileHighlighter|emi|2.8.0
prettier-vscode|esb|4.7.0
pine-script-syntax-highlighter|ex-|1.0.1
cshtml-tm|fir|1.0.0
git-extensions-for-vs-code|for|1.1.2
auto-rename-tag|for|0.1.2
code-runner|for|0.10.0
vbnet|gor|1.0.2
vscode-guid|hea|1.4.19
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
highlight-icemode|ice|0.0.6
ilspy-vscode|ics|0.7.11
classic-asp|ili|0.0.4
reg|ion|1.0.1
align-by-regex|jan|1.0.4
csharpextensions|jch|1.3.1
plantuml|jeb|2.13.9
better-dockerfile-syntax|jef|1.0.2
docomment|k--|0.1.9
VS-code-vagrantfile|mar|0.0.7
vscode-xslt-snippets|mar|0.1.0
git-graph|mhu|1.22.0
ecdc|mit|1.3.0
vscode-docker|ms-|1.2.0
csharp|ms-|1.21.18
vscode-edge-devtools|ms-|1.0.7
mssql|ms-|1.9.0
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.28.0
mono-debug|ms-|0.15.8
powershell|ms-|2020.4.0
vscode-github-issue-notebooks|ms-|0.0.22
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2169
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
vscode-json-transform|oct|0.1.2
indent-rainbow|ode|7.4.0
codemap|ole|1.11.2
vscode-subword-navigation|ow|1.2.0
material-icon-theme|PKi|4.1.0
Csharp-ASPNETCore|rah|1.11.0
ruby|reb|0.27.0
java|red|0.61.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.8.0
vscode-sort-json|ric|1.18.0
aspnet-helper|sch|0.6.4
code-settings-sync|Sha|3.4.3
vba|sky|2.8.0
vscode-zipexplorer|sle|0.3.1
vba|spe|1.4.0
vba-snippets|spe|1.0.1
code-spell-checker|str|1.8.0
unique-window-colors|stu|1.0.51
prettier-plus|svi|4.0.1
poor-mans-t-sql-formatter-vscode|Tao|1.6.10
asp-net-core-vs-code-extension-pack|tem|1.0.3
html-preview-vscode|tht|0.2.5
json2yaml|tux|0.2.0
transpose|v4r|0.0.5
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-icons|vsc|10.1.1
vscode-ruby|win|0.27.0
change-case|wma|1.0.0
any-swap|wol|0.1.3
yog-plantuml-highlight|Yog|0.0.5
material-theme|zhu|3.6.1

(8 theme extensions excluded)

</details>

**Comment by sandy081** [comment] 2020-05-15 14:30
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by quangkieu** [comment] 2020-05-15 17:43
After I submit the issue, I wait for a while +15 mins and the extensions menu is function again.
After more time troubleshooting, I find that it related to a big inetpub/wwwroot + Program Files (x86) folders on a remote Network File Share (3+ GB, 20k+ files) that I have in workplace file
Using Task Explorer, not Task Manager, I trace the open file handles of one Code Process and see that it open handle to each extensions folder duplicate 5+ times
But occasionally, it would open and close handles to children files at that remote folders in batch of 5/6 handles at a time
But the file explorer view panel already populated and expand full.
Against, I using the clean version without user extensions. I also did a reinstall of Code

My theory is that Code is try to scan each files in workspace and its either have higher priority or triggered (in queue) compare to the request for local installed extensions
I might did not noticed it before today. Or it was much faster that did not make me notice

I tried to using the file watcher exclude but I am sure if I setup correctly as symptom still persist
I might try file search exclude next.
I also try disable the git build-in extension.
 

So here is my suggestion

- UI/UX async operation queue should have higher priority compare to background scanning
- Improve remote speed but I think this is a Stretch
- Using Windows Offline Cache or Code Cached for faster scan between sessions.

**Comment by quangkieu** [comment] 2020-05-15 17:44
The error before seem unrelated to this.

**Comment by sandy081** [comment] 2020-05-18 10:38
I am sorry if I understand the root cause and the suggestion. Are you saying that some scanning operation is blocking the UI update?

**Comment by quangkieu** [comment] 2020-05-19 17:11
Hey @sandy081, from my troubleshooting, that there some activity scanning my big wwwroot blocking the ux update list of installed extensions. Even though my Explorer panel file list already done updating

**Comment by sandy081** [comment] 2020-05-20 15:23
> that there some activity scanning my big wwwroot 

What is this activity and is this done by VS Code?

**Comment by quangkieu** [comment] 2020-05-20 18:05
Sorry but i do not know which operation was it but i only know that one of the vscode process open file handles to that folder

**Comment by quangkieu** [comment] 2020-05-21 22:30
Mostly because I do not know how to get a better trace/log for this of which operation was this.

**Comment by sandy081** [comment] 2020-05-27 12:59
> that there some activity scanning my big wwwroot blocking the ux update list of installed extensions.

Assigning to @bpasero as the user mentions the activity is scanning the folder

**Comment by bpasero** [comment] 2020-05-27 14:58
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by quangkieu** [comment] 2020-06-05 23:05
```
Version:          Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS Version:       Windows_NT x64 10.0.19041
CPUs:             Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)
Memory (System):  15.91GB (4.48GB free)
VM:               19%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    1      103    5124  code main
    0       61    2884     electron-crash-reporter
    1      104    6168     shared-process
    0      221   13928     window (settings.json)
    0      216   25648       extensionHost
    0       69    1732         electron_node server.js
    0       76    4992         electron_node languageserver.js
    0       73    9788         electron_node server.js
    0       85   15032         "C:\Program Files\AdoptOpenJDK\jre-14.0.1.7-hotspot\bin\java" -DwatchParentProcess=false -noverify -Xmx64M -XX:+UseG1GC -XX:+UseStringDeduplication -cp c:\Users\[user]\.vscode\extensions\redhat.vscode-xml-0.11.0\server\org.eclipse.lemminx-0.11.1-uber.jar org.eclipse.lemminx.XMLServerLauncher
    0       11   18864           console-window-host (Windows internal process)
    0       92   19956         C:\Users\[user]\AppData\Local\Programs\VSCode\Code.exe c:\Users\[user]\AppData\Local\Programs\VSCode\resources\app\extensions\json-language-features\server\dist\jsonServerMain --node-ipc --clientProcessId=25648
    0       81   23952         electron_node serverMain.js
    0       99   28372         electron_node server.js
    0       67   15120     utility
    0      217   19504     window (Lonza (Workspace) - Lonza.code-workspace)
    0        6    5092       console-window-host (Windows internal process)
    0       85    7676       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0       74   22300       searchService
    0       78   23328       watcherService
    0      198   24004       extensionHost
    0       47    4912         c:\Users\[user]\.vscode\extensions\ms-dotnettools.csharp-1.22.0\.razor\rzls.exe -lsp --trace 0
    0       11   27248           console-window-host (Windows internal process)
    0        5    8700         "C:\Program Files\Git\cmd\git.exe" status -z -u
    0        5    2836           git.exe status -z -u
    0       11   28660           console-window-host (Windows internal process)
    0       59   12740         "C:\Program Files\AdoptOpenJDK\jre-14.0.1.7-hotspot\bin\java" -DwatchParentProcess=false -noverify -Xmx64M -XX:+UseG1GC -XX:+UseStringDeduplication -cp c:\Users\[user]\.vscode\extensions\redhat.vscode-xml-0.11.0\server\org.eclipse.lemminx-0.11.1-uber.jar org.eclipse.lemminx.XMLServerLauncher
    0       11   24188           console-window-host (Windows internal process)
    0       72   13008         electron_node serverMain.js
    0        5   13400         "C:\Program Files\Git\cmd\git.exe" check-ignore -v -z --stdin
    0       11   21812           console-window-host (Windows internal process)
    0        5   27408           git.exe check-ignore -v -z --stdin
    0       71   14740         electron_node languageserver.js
    0       95   21036         C:\Users\[user]\AppData\Local\Programs\VSCode\Code.exe c:\Users\[user]\AppData\Local\Programs\VSCode\resources\app\extensions\json-language-features\server\dist\jsonServerMain --node-ipc --clientProcessId=24004
    0       73   22224         electron_node server.js
    0       95   23848         electron_node server.js
    0       69   25096         electron_node server.js
    0      179   24592     gpu-process

Workspace Stats:
|  Window (Lonza (Workspace) - Lonza.code-workspace)
|    Folder (SC_): 163 files
|      File types: xslt(27) vb(25) dll(21) xml(17) html(14) wib(13) vbs(7)
|                  patch(3) wsd(3) asmx(2)
|      Conf files:
|    Folder (DispenseTransfer): 343 files
|      File types: cs(64) dll(62) scc(29) pdb(21) gif(14) wsdl(13) map(13)
|                  txt(11) config(9) cache(6)
|      Conf files: csproj(3) sln(1)
|    Folder (SC): 926 files
|      File types: xslt(135) dll(127) vb(125) log(92) xml(90) html(70) wib(65)
|                  vbs(27) wsd(11) asmx(10)
|      Conf files:
|    Folder (wwwroot): more than 21005 files
|      File types: gif(4966) aspx(2851) htm(2347) xml(1988) log(1145) jpg(916)
|                  js(907) wib(791) dll(558) png(291)
|      Conf files: package.json(1) tslint.json(1) tsconfig.json(1)
|    Folder (Syncade4): 3723 files
|      File types: dll(834) wib(428) log(313) xslt(245) vb(239) pdf(190)
|                  sql(180) xml(176) html(140) png(99)
|      Conf files: sln(1) csproj(1)
```

Well here is my status report from the comment.
Sorry for the late reply

**Comment by quangkieu** [comment] 2020-06-11 01:14
@bpasero @sandy081 I wonder if the last info is helpful?

**Comment by bpasero** [comment] 2020-06-11 07:36
I am not seeing any process in that list that consumes a lot of CPU or memory.

**Comment by quangkieu** [comment] 2020-06-11 19:32
So after I open this workspace, I switch to extension tab right away, and execute that status command.
But the result from extension tab return before the status command and both take a very long time like half an hour on timer.
![image](https://user-images.githubusercontent.com/4308312/84430925-6dc3a980-abf8-11ea-9ec5-e8e2de84a4c2.png)
Above is the picture to show which process that took a long time doing IO process.

**Comment by bpasero** [comment] 2020-06-12 06:08
@quangkieu to be clear, you are not seeing any performance issue unless you switch to the extensions tab, it only starts to get slow then?

**Comment by quangkieu** [comment] 2020-06-16 02:49
In summary, yes, only the extension view is having performance when I first open this workspace. 
The extension tab would return to normal after the first 30(s) mins of delay after open this workspace.
So for context, the text editor view of the file document, folder/file tree does not have this performance problem

**Comment by sandy081** [comment] 2020-06-17 16:06
@quangkieu How many extensions you have installed? Can you please try with a fresh extensions directory. To do so start code from cli using `code --extensions-dir <path> --verbose` . Also open shared process log in your Output panel and share the log with us.

**Comment by quangkieu** [comment] 2020-06-18 04:53
Wow, the extension tab could be open right away after running vscode using that command. Not just that run but next run using desktop shortcut.
[Here](https://gist.github.com/quangkieu/baf6cf8b92be02a17696e71412e66eb0#file-vscode_issues_97851) is my gist of the trace

**Comment by sandy081** [comment] 2020-06-19 09:20
Is this trace with performance issue or without performance? If not can you please provide the trace with performance issue?

**Comment by quangkieu** [comment] 2020-06-22 02:44
Hey @sandy081, I do not have a trace when problem occurs. It seem like the command that you mentioned earlier resolved my issues. I am not sure what create hiccup on my setup but defined extensions folder in command like that make all subsequent run, even after restart resolve the extension menu right away when I open that big workspace

**Comment by sandy081** [comment] 2020-06-24 04:33
Ok, good to know that your issue got resolved. Since the issue cannot be reproduced closing this.

Please reopen it if you see it again with asked information.

**Closed by sandy081** 2020-06-24 04:33 UTC
Labels: needs more info
