### ISSUE TITLE
Unwanted behavior due to mouse position

### ISSUE THREAD

**Issue by glhfior** [microsoft/vscode#134253] opened 2021-10-01 00:48 UTC
Open the File menu and place the mouse cursor on the "Preferences" option.

Hit [Esc] twice to close the file menu.

Attempt to save the current file via [Alt][F][S] (not the [Ctrl][S] shortcut).

The mouse position prevents the normal behavior of initiating the save and instead leave the mouse hovering over Preferences

**Comment by yume-chan** [comment] 2021-10-01 03:34
Duplicate of #110594

**Closed** 2021-10-01 06:50 UTC
Labels: *duplicate
