### ISSUE TITLE
SplitLinesCollection error

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#43798] opened 2018-02-16 02:15 UTC
### Issue Type
Bug

### Description

Not sure how I ended up in this state but now the terminal is unusable. I had split the terminal once.

```
  ERR SplitLinesCollection: attempt to access a 'newer' model: Error: SplitLinesCollection: attempt to access a 'newer' model
    at e._ensureValidState (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1104:726)
    at e.convertModelPositionToViewPosition (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1113:246)
    at e.convertModelPositionToViewPosition (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1103:706)
    at e._setPosition (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:744:656)
    at e.setPosition (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:744:911)
    at t.setWidgetPosition (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:741:1004)
    at t.layoutContentWidget (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1795:103)
    at t.layoutContentWidget (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1798:996)
    at e.update (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1878:611)
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1881:634
```

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T06:08:32.814Z)
OS version: Darwin x64 16.7.0

Reproduces without extensions

**Comment by Tyriar** [comment] 2018-02-16 13:38
That error is about the editor and shouldn't have affected the terminal splits. I'll keep a look out for the splits being corrupted, the code is still changing a lot.

**Comment by alexandrudima** [comment] 2018-03-06 09:56
Duplicate of #29033

**Closed by alexandrudima** 2018-03-06 09:56 UTC
Labels: bug, editor
