### ISSUE TITLE
The markdown preview is not interpreting checkboxes [ ]

### ISSUE THREAD

**Issue by joaopedro** [Microsoft/vscode#26750] opened 2017-05-16 13:17 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.2|
|xml|DotJoshJohnson|1.7.0|
|beautify|HookyQR|1.0.2|
|ecdc|mitchdenny|0.10.3|
|vscode-icons|robertohuertasm|7.7.0|
|vscode-sql-beautify|sensourceinc|0.0.4|;

---

Steps to Reproduce:

1.create a md file
2.add a checkbox i.e. [ ] item1
3.preview the markdown file

In the preview pane the item1 line appears as **[ ]item1**. Is this the expected preview for checkboxes?

**Comment by SpirosKar** [comment] 2017-05-16 13:34
The checkbox [ ] is future added by GitHub on they products, it's not part of the default markdown implementation.
I like to see that future added.

**Comment by mjbvz** [comment] 2017-05-16 18:00
@SpirosKar is correct. We plan to make the markdown preview extensible though.  Seehttps://github.com/Microsoft/vscode/issues/10367#issuecomment-292361527 for a preview

Closing as a duplicate of #10367

**Closed by mjbvz** 2017-05-16 18:00 UTC
Labels: duplicate
