### ISSUE TITLE
"The specified task cannot be tracked" before debugging

### ISSUE THREAD

**Issue by YangHanlin** [microsoft/vscode#75777] opened 2019-06-19 14:08 UTC
Issue Type: <b>Bug</b>

After having today's update of VSCode installed, I cannot succesfully debug my C/C++ program any more.

**Steps to reproduce:**

1. Navigate to a file that needs ro run preLaunchTask before debugging, such as a `.cpp` file;
2. Press `F5` or select `Debug > Start debugging` to start debugging.

**Expected:**

The task (in the case of `.cpp` file, it is to compile the current file) that should be run before launching is successfully executed, and the program is launched for debugging.

**Actual:**

There pops up a dialog that reads

> The specified task cannot be tracked.

And the task that should be run are actually not executed.

**Additional info:**

When I have not installed this update and everything works well, the terminal panel will pop up and it can be seen that the tasks are being run. However, after this update, when I start debugging, the terminal panel does not pop up, which may indicate that the task needed are actually not being run.

I almost disabled all the extensions (only leaving the language pack and the `cpptools` extension) and the problem still occurs.

VS Code version: Code - Insiders 1.36.0-insider (6520c22b83c0b6f168ba7de3309ffab42281e905, 2019-06-19T05:19:10.147Z)
OS version: Windows_NT x64 10.0.18917

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.36.0
cpptools|ms-|0.24.0-insiders

</details>

**Comment by isidorn** [comment] 2019-06-19 14:12
@alexr00 can you please look into this?

**Comment by YangHanlin** [comment] 2019-06-19 14:30
This issue may be the duplicate of #75774.

**Comment by alexr00** [comment] 2019-06-20 08:05
@YangHanlin What happens if run the task from the command palette?

**Comment by alexr00** [comment] 2019-06-20 08:39
Also, what does your launch.json and tasks.json look like? I created a C++ project, added a build task, and added a launch config that uses the build task as a preLaunch task. It all works as expected for me. If you have a repo I can clone to reproduce that would really help.

My task:
```
{
            "label": "build",
            "type": "shell",
            "command": "msbuild",
            "args": [
                "project.vcxproj",
                "/property:GenerateFullPaths=true",
                "/t:build",
            ],
            "group": "build",
            "problemMatcher": "$msCompile"
        }
```
My launch config:
```
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "Debug\\project.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "preLaunchTask": "build"
        }
```

**Comment by YangHanlin** [comment] 2019-06-20 08:43
@alexr00 If I attempt to run the task from the Command Palette, the task will not be executed either, and the terminal panel does not pop up as well. (I did not disable the extension *cpptools*, as I set the problem matcher as `$gcc` which can only be recognized by this extension.) This behavior is the same as described in #75774, therefore I think this issue is a duplicate of it.

**Comment by YangHanlin** [comment] 2019-06-20 08:46
@alexr00 I will try to reproduce it and pack them into a repo. Please wait a minute.

**Comment by YangHanlin** [comment] 2019-06-20 09:25
@alexr00 I have reproduced the error again and packed the necessary files into the repository [YangHanlin/vscode-troubleshooting](https://github.com/YangHanlin/vscode-troubleshooting).

I can confirm that the same problem occurs in this directory with the current Insiders build, and it works well with the stable build (`1.35.1`) of VSCode.

You can reproduce the error by:
1. Clone the repo;
2. Open the directory in VSCode;
3. Navigate to the file `hello-world.cpp` and attempt to start debugging or run the task `Compile current file`.

Note that I am using `g++` and `gdb` in Mingw-w64 as my toolchain. I am sorry that I don't know how to modify the configuration to use MSVC :-(

**PS:** During the time I tried to set up this repo, the VSCode received another update. Unfortunately, the tasks cannot run either after the update; and more unfortunately, **as I attempt to start debugging, VSCode will not show the error dialog; instead, VSCode will close without any warning or error message.**

**Comment by alexr00** [comment] 2019-06-21 13:16
Yes, this is a duplicate of #75774

**Closed** 2019-06-21 13:16 UTC
Labels: *duplicate, needs more info
