### ISSUE TITLE
Keeps re-opening closed editors

### ISSUE THREAD

**Issue by samdenty** [microsoft/vscode#221498] opened 2024-07-11 18:37 UTC
Does this issue occur when all extensions are disabled?: Think so

- VS Code Version: 1.92.0-insider (Universal) Commit: c37f4a49e28831cec1aec1af0f626edaada1f7ce
- OS Version: Macos Sonoma

Steps to Reproduce:

1. Open a new editor with no contents and don't save it
2. Close it
3. It's re-opened again even though you closed it

This is the callstack to the openEditors method being called straight after it was closed:

<img src="https://github.com/microsoft/vscode/assets/13242392/7cf468de-d017-47dd-a8f1-010142d88094" height="250">

https://github.com/microsoft/vscode/assets/13242392/0356bc90-5f58-4bab-8267-27efb797315a

**Comment by impicek** [comment] 2024-07-18 14:34
I have the same issue on 1.91.1 version, OS Windows_NT x64. 
Closing vscode and deleting files from \AppData\Roaming\Code\Backups  helps - after reopening vscode when I close a file it doesn't reopen anymore.

**Comment by bpasero** [comment] 2024-07-26 14:40
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by samdenty** [comment] 2024-07-26 22:52
@bpasero i added a screenshot to the description (but didn't point out why if was significant). Here's the stack showing it the re-opening coming directly from the closeEditors call.

![CleanShot 2024-07-26 at 23 51 21@2x](https://github.com/user-attachments/assets/482b8228-ee55-4ce6-89d7-067d88c05411)

**Comment by samdenty** [comment] 2024-07-26 22:53
I can try without extensions though

**Comment by bpasero** [comment] 2024-07-27 05:43
Please do.

**Comment by impicek** [comment] 2024-07-29 06:20
Issue stooped occur in my installation. I didn't do anything special... :/ 
list of active extensions that were updated in last two weeks: 
- oracle developer tools 
- gitlens
- cody ai 
- project manager for java
- .net install tool
- live preview

**Closed** 2024-07-29 09:19 UTC
Labels: info-needed
