### ISSUE TITLE
TypeScript, mocha, chalk doesn't output color to debug console?

### ISSUE THREAD

**Issue by bill-mybiz** [Microsoft/vscode#4755] opened 2016-03-29 15:56 UTC
In my 0.10.11 version, chalk console logging using chalk works. In the 0.10.12-insider version it doesn't.

- VSCode Version: 0.10.12-insider
- OS Version: Windows 10
- Language: TypeScript 1.8.9, Node 4.1.1, Mocha 2.3.4, 
- Launch: 
```
		{
			"name": "[WP] test",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
			"stopOnEntry": false,
			"args": [
                "test.bundle.js",
				"--no-timeouts",
                "--max_old_space_size=2048",
				"--colors"
			],
			"cwd": "${workspaceRoot}/bin-webpack/test",
			"runtimeExecutable": null,
			"runtimeArgs": [],
			"env": {},
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/bin-webpack/test"
		},
```
Steps to Reproduce:
1. `import chalk = require('chalk');`
2. `console.log(chalk.magenta('some text'));`

**Comment by bill-mybiz** [comment] 2016-03-29 15:58
![lost coloring](https://cloud.githubusercontent.com/assets/1253349/14114626/37212472-f59d-11e5-8428-cdb85cdf027d.png)

**Comment by Tyriar** [comment] 2016-03-29 16:38
Duplicate of https://github.com/Microsoft/vscode/issues/571

**Comment by bill-mybiz** [comment] 2016-03-29 16:45
Hi @Tyriar! I appreciate the quick response. Does that really apply if it works in 0.10.11 already but does not work in the 0.10.12-insiders version?

**Comment by Tyriar** [comment] 2016-03-29 17:26
@bill-mybiz oh sorry, misread, didn't think it was a regression?

**Comment by bill-mybiz** [comment] 2016-03-29 18:34
@Tyriar Yeah I think I would consider it a regression, but I'm not sure if it would be a regression in VS Code per se or if it's something that breaks chalk and possibly others. I just know that for tracing asynchronous code, the console coloring has been a Godsend as I'm able to match interspersed log entries extremely efficiently.

**Comment by dbaeumer** [comment] 2016-03-30 07:45
@bpasero I think this is the output window.

**Comment by bpasero** [comment] 2016-03-30 07:46
https://github.com/Microsoft/vscode/issues/4616

**Closed by bpasero** 2016-03-30 07:46 UTC
Labels: bug
