### ISSUE TITLE
Git: cannot undo a change in this folder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27901] opened 2017-06-02 07:54 UTC
Steps to Reproduce:

1. have a folder `super cool stuff" ---?!?!() sdäü*`
2. add a file
3. from git viewlet undo

=> nothing happens

Output:
```
git clean -f -q -- /Users/bpasero/Development/monaco/super cool stuff" ---?!?!() sdäü*/tsfmt.json
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
```

**Comment by joaomoreno** [comment] 2017-06-27 14:04
This reproduces with a folder simply named `?`.

**Comment by s7aesis** [comment] 2017-08-25 15:26
I followed the steps on Windows 10, and could not reproduce the problem. Clicking undo deleted the file out of the `?` folder.

**Comment by munumafia** [comment] 2017-10-12 19:24
Guessing that it's due to `?` being a special character on a Unix command line, so they question mark is probably being interpreted by the shell instead of being passed to Git. I just ran `git clean -f -q -- /Users/sean/Documents/Projects/testing/\?/.keepme` from zsh and my test file got removed.

Is anyone opposed to me picking this issue up and tackling it? I would think it would be a relatively straightforward fix.

**Comment by munumafia** [comment] 2017-10-12 22:37
This is weird, it looks like `git clean` is behaving differently depending on whether a directory with a question mark in the name is committed or not. If it's not committed, then something like `git clean -f -q -- /Users/sean/Documents/Projects/testing/?/keepme` does absolutely nothing, but as soon as I commit `keepme` and add a different file, then something like `git clean -f -q -- /Users/sean/Documents/Projects/testing/?/keepme2` works.

Starting over, if I create a new test repository and then create a directory named `test` with a single file in it, `git clean` works just fine even without the directory being part of the commit history.

**Comment by joaomoreno** [comment] 2017-11-23 14:15
https://github.com/Microsoft/vscode/issues/24434

**Closed by joaomoreno** 2017-11-23 14:15 UTC
Labels: bug, good first issue, help wanted, scm
