### ISSUE TITLE
bug on the option 'editor.bracketPairColorization.enabled'

### ISSUE THREAD

**Issue by h4l-yup** [microsoft/vscode#134185] opened 2021-09-30 06:50 UTC
Does this issue occur when all extensions are disabled?: No (because it needs vue extension)

- VS Code Version: 1.60.2 (Universal)
- OS Version: Darwin x64 20.4.0

Steps to Reproduce:

1. set the option `"editor.bracketPairColorization.enabled": true`
2. make a `sample.vue` file like below

```vue
<template>
    <div class="row">
        <input ref="key"
                v-model="key"
                class="col q-pr-md"
                label="key"
                outlined
                dense
                :hint="warningMessage"
                :rules="[
                    val => !!val,
                    val => /^[\w-]+?$/.test(val) || 'invalid character in Key'
                ]"
                @blur="checkDeviceKey"
        />
    </div>
</template>
```

3. '<>' brackets are colorized in the template tag but it seems like that > bracket in the js arrow function is treated as closing bracket of html tag

![image](https://user-images.githubusercontent.com/28913065/135400855-4f2bc9f8-52a0-4de9-a9f1-a5c1ca71f93f.png)

While I have used the `bracket pair colorizer 2` extension, it did not colorize '<>' brackets.
Maybe it needs more detailed options like which kind of brackets to be colorized

**Comment by hediet** [comment] 2021-09-30 07:19
> While I have used the bracket pair colorizer 2 extension, it did not colorize '<>' brackets.´

<...> is now removed by default in latest VS Code insiders.
Duplicate of #132476.

**Closed by hediet** 2021-09-30 07:19 UTC
