### ISSUE TITLE
"Deleted from disk" showing when file is restored

### ISSUE THREAD

**Issue by vnbrs** [Microsoft/vscode#33193] opened 2017-08-26 16:52 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
javadebugger|don|0.1.3
python|don|0.7.0
code-runner|for|0.7.1
vscode-javac|geo|0.0.46
Go|luk|0.6.63
mssql|ms-|1.1.0
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.1.8
java|red|0.8.0
vscode-icons|rob|7.12.0
standard|shi|0.2.3

---

Steps to Reproduce:

1. Create a file (⌘N)
2. Type some content in this file and save it (⌘S)
3. Edit the file and do not save it
4. Delete the file you just opened using Finder (⌘delete) and note that 'deleted from disk' shows up in the tab that the file is open in VS Code.
5. Restore the deleted file using Finder (⌘Z)
6. The 'deleted from disk' label still visible even if you edit the file and save it again.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment] 2017-08-27 15:28
Duplicate of https://github.com/Microsoft/vscode/issues/29766

**Closed by Tyriar** 2017-08-27 15:28 UTC
Labels: new release, workbench
