### ISSUE TITLE
Alt-H2 Preview and Syntax Highlighting Issues

### ISSUE THREAD

**Issue by bwarring24** [Microsoft/vscode#11849] opened 2016-09-11 18:15 UTC
- VSCode Version: 1.5.1
- OS Version: Windows 10 Pro Insider Preview: Build 14915

Steps to Reproduce:

1. Create a new markdown file
2. Apply dash line under desired text

```
My Header
---------
```

Preview renders the font size correctly, but does not display a solid line under the text. Also the dashes ( - ) do not get highlighted via the Markdown syntax highlighting.

```
My Header
=========
```

The above works as it should.

**Comment by mjbvz** [comment] 2016-09-22 17:53
For the rendering of headers, you can use whatever css you like in the preview: https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css In this case, you'd want a css rule that adds a bottom border for `h2` elements.

The editor syntax coloring of the underline alt header style is tracked by #9784. Closing this issue as a duplicate of that issue, but please let me know if you have any trouble getting the h2 preview rendering working.

Thanks

**Closed by mjbvz** 2016-09-22 17:53 UTC
Labels: duplicate, markdown
