### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: e:/node_modules/@nestjs/common/index.d.ts linked to nonexistent file //wesley-dell/TRABALHOS/UNIFIQUE/node_modules/@nestjs/common/index.d.ts

### ISSUE THREAD

**Issue by wmenezes2020** [microsoft/vscode#182856] opened 2023-05-18 11:05 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment] 2023-05-18 11:06
/duplicate of https://github.com/microsoft/vscode/issues/182196

**Closed** 2023-05-18 11:06 UTC
Labels: invalid
