### ISSUE TITLE
Stuck inline suggestion

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147108] opened 2022-04-08 18:13 UTC
This has happened a couple times today so it must be a new thing. Both times when I had an inline suggestion or copilot suggestion and triggered the suggest widget manually. The only way to get it to go away is to switch editors
![Recording 2022-04-08 at 11 12 04](https://user-images.githubusercontent.com/323878/162498434-a5aa3671-9e23-4574-b1b1-4f0b341e340b.gif)
.

Pressing escape didn't do anything

**Comment by jrieken** [comment] 2022-04-12 10:00
Something on the console? I'd expect this to be some kind of error/exception case which leads to failure in clean-up and not frequent asking of inline suggestions

**Comment by hediet** [comment] 2022-04-12 10:24
Yes, this is most likely a decoration that is not removed. I'll investigate.

**Comment by roblourens** [comment] 2022-04-18 21:59
Happened again, and the suggest widget was not involved
![Recording 2022-04-18 at 14 58 37](https://user-images.githubusercontent.com/323878/163884284-1c16bd4c-65b1-4c3c-8c72-d7f59b9d914f.gif)

**Comment by hediet** [comment] 2022-04-19 14:57
Do you have reproduction steps?
I cannot explain this bug...
As soon as the cursor leaves the line, all decorations should be cleaned up.

**Comment by roblourens** [comment] 2022-04-19 17:00
Nope. Just have seen it randomly a few times. If it would help to debug after it's in this state, you can tell me where to set a breakpoint

**Comment by andrewbranch** [comment] 2022-04-28 17:56
I’ve been experiencing this with Copilot pretty frequently. Unfortunately I can’t quite figure out how to reproduce reliably, but it seems to be most likely to happen when I’m moving back and forth between lines a lot, editing mid-expression, as opposed to typing linearly. 

![image](https://user-images.githubusercontent.com/3277153/165816818-10a09ebc-45f1-4390-8e90-5eb252a2cc12.png)

**Comment by andrewbranch** [comment] 2022-04-28 18:03
It’s on a roll right now. It feels like maybe there’s sometimes a conflict between the completions preview and the decoration added by Copilot?

<img width="368" alt="image" src="https://user-images.githubusercontent.com/3277153/165817321-95a96724-06b1-47b7-a29a-42af0d3e8c35.png">

**Comment by hediet** [comment] 2022-04-29 08:36
Can you hover over both inline suggestions? What happens?
Also, can you check the dev tool logs? Thanks :)

**Comment by andrewbranch** [comment] 2022-05-02 18:08
I’ll check if I see it happen again. I believe at the time I hovered them and nothing happened, but I can’t be 100% sure.

**Comment by hediet** [comment] 2022-06-02 08:18
Were you able to reproduce? We did some changes that might have fixed this.

**Comment by andrewbranch** [comment] 2022-06-02 16:22
I haven’t seen it since I last chimed in. Would guess it’s fixed 👍

**Comment by hediet** [comment] 2022-06-02 17:02
Closed by https://github.com/microsoft/vscode/commit/1c8ffe98e90c8c9d17eebd6321418d484e323b72.

**Closed by hediet** 2022-06-02 17:02 UTC
Labels: bug, needs more info, important, inline-completions, ghost-text
