### ISSUE TITLE
"Code Helper" process x 4-5 instances, using up 99.8% of cpu, running on OSX

### ISSUE THREAD

**Issue by fivefishstudios** [Microsoft/vscode#24787] opened 2017-04-14 16:50 UTC
There's a process called "Code Helper" (sometimes as many as 4 instances) that's taking up 99.6% of my CPU. Running on OSX. 

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|Angular2Tests|MarinhoBrandao|0.7.3|
|html-css-class-completion|Zignd|1.0.3|
|open-html-in-browser|coderfee|0.0.6|
|angular2-snippets|danwahlin|1.0.15|
|classic-asp|ilich8086|0.0.2|
|easy-icons|jamesmaj|0.3.1|
|Angular1|johnpapa|0.1.16|
|web-browser|masonicboom|0.0.1|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-css-peek|pranaygp|1.2.4|
|view-in-browser|qinjia|0.0.5|
|aspnet-helper|schneiderpat|0.6.3|;

---

Steps to Reproduce:

1. Run Visual Studio Code
2. Open Activity Monitor, look at %cpu and load eaten up by "Code Helper"

**Comment by rphlmr** [comment] 2017-04-16 09:59
I have the same issue.
These processus continue running even after we quit VSCode.

The only solution is to execute `killall -KILL  "Code Helper"` after we quit VSCode.
Working on VSCode became hard because these processus slowdown VSCode :(

**Comment by rphlmr** [comment] 2017-04-16 10:05
On Activity Monitor, check the PID of the process
Then execute `ps ax | grep PID` where PID is the PID process.
You'll see what extension is consuming your ressources.

I guess it is `schneiderpat.aspnet-helper-0.6.3` like me :p

**Comment by jrieken** [comment] 2017-04-18 08:14
> On Activity Monitor, check the PID of the process
Then execute ps ax | grep PID where PID is the PID process.

@fivefishstudios Please do this

**Comment by fivefishstudios** [comment] 2017-04-18 08:19
~$ ps ax | grep 20404
20404   ??  R     85:07.87 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/rueloquindo/.vscode/extensions/schneiderpat.aspnet-helper-0.6.3/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/rueloquindo/.vscode/extensions/schneiderpat.aspnet-helper-0.6.3/server/server.js --node-ipc
21099 s000  S+     0:00.00 grep 20404

Yes, it's schneiderpat.aspnet

**Comment by jrieken** [comment] 2017-04-18 08:22
closing as dupe of https://github.com/schneiderpat/aspnet-helper/issues/7 then

**Closed by jrieken** 2017-04-18 08:22 UTC
Labels: needs more info
