### ISSUE TITLE
Mac: sticky drag feedback in some cases

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17157] opened 2016-12-14 09:00 UTC
Unsure if it repos, but this is what I have done: Dragged a file from the desktop to the trash bin and crossed VS Code. 

![screen shot 2016-12-14 at 09 59 31](https://cloud.githubusercontent.com/assets/1794099/21175747/2f77792e-c1e4-11e6-93a5-6a1c4420da80.png)

**Comment by bpasero** [comment] 2016-12-14 09:48
I have heard bug like this only on Windows so far where I can reproduce more easily. I am not able to reproduce this on Mac though no matter how hard I try.

**Comment by bpasero** [comment] 2017-04-19 08:48
Closing (clean up), no plans to work on this.

**Closed by bpasero** 2017-04-19 08:48 UTC
Labels: bug, workbench
