### ISSUE TITLE
Weird bug in settings.json that adds commas in newlines when changing tab to User Settings

### ISSUE THREAD

**Issue by odomosis** [microsoft/vscode#74287] opened 2019-05-24 14:57 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I don't know how it started and if I can reproduce it or not but here is what is happening: (Please refer to the pictures below. They are in the order of the narration here.)
1. I had settings open in .json format in the tab called "User Settings", while I had settings open in non-.json format in the tab called "Settings".
2. I closed VSCode day before yesterday in this state.
3. I opened VSCode today. Did nothing else, but suddenly I noticed that the "PROBLEM" counter at the bottom says 2. 
4. I click on the issue that is there and suddenly my non-.json "Settings" tab name gets changed to "settings.json" and the contents are the also the settings in .json format with two commas, each in its own line, at the very end of this "settings.json" tab file (as can be seen in the screenshots below).
[So, to clarify, I already have my settings open in the .json format in the tab called "User Settings" in the screenshot. And my non-.json "Settings" tab changes to a "settings.json" tab AFTER clicking the issue that the "PROBLEM" tab showed. What is curious is, typically, VSCode does NOT allow me to open two instances of settings in .json format and redirects me to that already open one. Thus, this is weird to me.]
5. Now, with my editor window in this state, everytime I click on the "User Settings" tab, the "PROBLEM" counter increases by 2 (as can be seen in the pictures below). I have noticed that the problem counter which was an even number till now, is now an odd number (25) and has stopped increasing upon going to the "User Settings" tab.

Other interesting things I noticed:
1. I opened a python file in another tab. Switching to that tab did not increase the "PROBLEM" counter.
2. Usually, in VSCode, when you are in the settings in .json format, the top-right has a button displayed that allows you to open settings in a non-.json format (says "Open Settings"). Similarly, if you are in the settings in non-.json format, that button changes to another button in the same place, that allows you to open the settings in .json format (says "Open Settings (JSON)"). In my tab called "settings.json" none of the buttons exist (only "Split Editor Right" button exists), while the appropriate "Open Settings" button is still visible in the "User Settings" tab.
3. I can't backspace or delete those commas. If I try to "Ctrl+X" them, it says "Cannot edit in read-only editor".

I'll add more things as I find them. This isn't a life threatening bug, but it's just annoying and curious.

Thank you. Please ask me if you have any other things you'd like to know.

UPDATE1: I closed VSCode and reopened it and this issue is now gone. No more "PROBLEMS". It is all clean. Will try reproducing it if I can.

![Annotation 2019-05-24 105413](https://user-images.githubusercontent.com/50924749/58336767-5a3d7900-7e12-11e9-914a-6f32f8fe38a9.jpg)
![untitled_LI (2)](https://user-images.githubusercontent.com/50924749/58336194-49403800-7e11-11e9-9f46-dfab5bd301e0.jpg)
![untitled1_LI](https://user-images.githubusercontent.com/50924749/58336280-6ecd4180-7e11-11e9-8ff8-e4302ae97c62.jpg)
![untitled2_LI](https://user-images.githubusercontent.com/50924749/58336285-72f95f00-7e11-11e9-93dd-f2e629ba749e.jpg)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.4.12954
octave|toa|0.0.3

</details>

**Comment by sandy081** [comment] 2019-06-03 12:52
Looks like `settings.json` is not a file on disk but it is an in-memory default settings resource generated by VS Code. This is generated when opening split json settings editor. This should not have any errors generated. 

@roblourens Any idea about this? I do not know what is the current stand on supporting split json editor and whether we are up for maintaining it? If we are not I would suggest to close this issue.

**Comment by roblourens** [comment] 2019-06-03 23:35
My guess would have been the settings autofixing code that inserts missing commas. It really looks like that... However I deleted that in April so it's not in the 1.34 release. So then I have no idea.

@odomosis can you tell me if it happens again? I also can't reproduce it. And if it is specific to the split JSON editor somehow then I consider the split editor deprecated anyway...

**Comment by odomosis** [comment] 2019-06-04 13:28
Hi @sandy081 and @roblourens ! Thank you for your response. No, I haven't encountered this again and haven't been able to reproduce it. It seems it was a one-time thing. Maybe it'll pop up again. I have a feeling it might.
And yes, it was specific to only those two tabs (i.e. "User Settings" and "Settings"). I don't know if it had anything to do with the split JSON editor (the split window that opens when you try to edit the settings in .json format, right?) though because I didn't open it at that time (as is visible in the screen shots, the split JSON editor is not open).
I'll keep this updated in case it ever happens again. Thanks once again.

**Comment by sandy081** [comment] 2019-06-05 06:33
Thanks @odomosis. I will close it until then.

**Closed by sandy081** 2019-06-05 06:33 UTC
