### ISSUE TITLE
VS code on mac accessibility of moving by line threw code

### ISSUE THREAD

**Issue by tayarndt** [microsoft/vscode#73667] opened 2019-05-13 12:51 UTC
Issue Type: <b>Bug</b>

1. open a vs code document.
2. Turn on voiceover with the command cmd F5.
3. Now, as you go threw the document, every once in a wile voiceover reads the top line of the file again. Or, it may read another line from earlier on in the file.

4. if there are new lines in the file, voiceover will read new line new line and the text. The kicker is it will read new new line and the text the amount of timnes the new line was pressed. For example, lets say i have a file with 3 new lines for a new sec tion of code then voiceover will read the next block of text 3 times.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|33%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.2
vscode-pandoc|Dou|0.0.8
markdown-converter|man|1.1.2
python|ms-|2019.4.12954
vscode-qt-for-python|sea|0.3.0
python|tht|0.2.3
pyqt-integration|zho|0.2.0
markdown-html|zhy|0.1.8

</details>

**Comment by tayarndt** [comment] 2019-05-13 15:23
This is a duplicate  issue and can't figure out how to delete  it.

**Comment by chrmarti** [comment] 2019-05-13 18:25
@tayarndt Which issue is it a duplicate of?

**Closed by chrmarti** 2019-05-13 18:25 UTC
Labels: editor-contrib
