### ISSUE TITLE
When in Windows, do as Windows does aka store settings/extensions in %APPDATA% or %LOCALAPPDATA%

### ISSUE THREAD

**Issue by MicahZoltu** [Microsoft/vscode#7035] opened 2016-05-31 02:05 UTC
- VSCode Version: 1.1.1
- OS Version: 10

Steps to Reproduce:
1. Install VS Code.
2. Install one or more extensions.
3. Notice that there is a `.vscode` folder in your user directory.

In Windows, the root of the user directory is _NOT_ the right place to store application settings.  This is a very common convention in Linux but Windows != Linux and not all Windows users want to pretend they are running Linux.  In windows the correct location for application settings is `%APPDATA%` and the correct location for extensions is `%LOCALAPPDATA%` or `%PROGRAMDATA%` (depending on level of security consciousness).

To avoid a flame war, I want to be clear that this issue isn't debating _why_ `C:/Users/<username>/.<appname>` is the wrong place for these files, it is only asserting that Microsoft has very clearly documented the _right_ place for settings files and VSCode does not follow it.  If the authors of VSCode have consciously decided to go against the long-running convention established by the OS authors then I won't press on the issue (though I think that would be a silly decision for VSCode).  I am submitting this issue under the assumption that the authors didn't realize there was an established convention (very common in open source projects) and did what was familiar to them.

**Comment by Tyriar** [comment] 2016-05-31 03:01
Related to https://github.com/Microsoft/vscode/pull/5570; we are probably moving these directories soon.

**Comment by Tyriar** [comment] 2016-05-31 03:02
cc @bpasero @joaomoreno

**Comment by rebornix** [comment] 2016-05-31 03:05
@Tyriar will we save user preferences in roaming data for Windows sync up?

**Comment by joaomoreno** [comment] 2016-05-31 08:02
Totally agree. We need an owner for this story that just implements it right for all platforms. Not only implements the change but migration as well.

- Windows: `%APPDATA%`
- Linux: `.vscode`
- OSX: `~/Library/Application\ Support`

**Comment by bpasero** [comment] 2016-05-31 08:21
Note that %APPDATA% on Windows seems to be the "Roaming" folder, so you potentially end up roaming extensions and settings around.

**Comment by rebornix** [comment] 2016-05-31 08:55
Extensions should go with `%LOCALAPPDATA%` but it would be great if we can have an extension list manifest file stored in `%APPDATA%` which roams, then notify users if there is newly added/deleted extension on other machines.

**Comment by Tyriar** [comment] 2016-05-31 14:29
@rebornix why would we separate them? Is it bad to roam things potentially as big as extensions or something?

**Comment by rebornix** [comment] 2016-05-31 14:56
@Tyriar yes it's not a good idea to roam big data, per TechNet's documentation about app data roaming https://technet.microsoft.com/en-us/library/cc766489(v=ws.10).aspx , data (or data change) larger than 20 megabytes or more might cause delays in user logons. 

Windows Application guideline also suggests not to roam large set of data, https://msdn.microsoft.com/en-us/library/windows/apps/hh465094.aspx . Of course, our app is not a Windows Application, but I think they share the same design principal. 

So the last question is, are our extensions data too large? IMHO, they are sometimes too large and our extension development toolchain leads to this situation. When we package our extension into vsix, we don't have a good way to separate source code files and other dependencies (like test files, dev dependencies, node_modules), we always put a bunch of unused files in the extension vsix package. Take Go extension for example

![image](https://cloud.githubusercontent.com/assets/876920/15678865/67843156-2782-11e6-8ea3-19cbf8835c85.png)

The test folder is not necessary, most files from node_module packages are not necessary either. But our current toolchain can't help people easily avoid this kind of file duplication, which finally makes extension packages too large.

**Comment by Tyriar** [comment] 2016-05-31 15:03
So something like `%APPDATA%/extensions.json` and `%LOCALAPPDATA%/extensions/` would eventually be ideal, with the extensions from `extensions.json` maybe downloading automatically on launch?

**Comment by rebornix** [comment] 2016-06-01 02:24
@Tyriar yup it's the expected behavior the system will do. The extension json file is synced by the system automatically so I suggest we detect its change and the real extension list and notify users about the change, let them decide whether to sync the extensions on the new machine.

**Comment by Tyriar** [comment] 2016-07-06 22:23
@Zoltu I'd appreciate your feedback on the Windows portion of #3884

**Comment by felixfbecker** [comment] 2016-07-07 07:01
@Zoltu Wow, finally someone who also embraces Windows' program storage conventions. One question though, what is the exact difference between `%APPDATA%` and `%APPDATALOCAL%`?

**Comment by Zoltu** [comment] 2016-07-07 15:03
@felixfbecker `Local` doesn't get copied over the network when on a domain and roaming profiles are enabled.  When on a domain, `Roaming` is copied to a central server on logout and pulled down again on login.  Because of this, you generally want to keep `Roaming` small but `Local` can be big.

**Comment by Tyriar** [comment] 2016-11-14 03:59
Closing this in favor of #3884, moved the extension manifest discussion to #15442.

**Closed by Tyriar** 2016-11-14 03:59 UTC
Labels: debt, feature-request, windows
