### ISSUE TITLE
Snippet list does not render correctly

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#3348] opened 2016-02-23 16:42 UTC
#3159

When looking through the snippet list I get some strange rendering.  

There are definitely 5 snippets in the list but only 4 show up until I arrow through the complete set of 5.  Once I did that the list rendered correctly.  I would not have known there were 5 items if the sample screenshot did not show 5 (vs the 4 I could see).

I also saw some other partial rendering issues such as the double up in the image below.

![screen shot 2016-02-23 at 8 33 12 am](https://cloud.githubusercontent.com/assets/1051190/13258726/31611f42-da09-11e5-8eef-aa890f663929.png)

**Comment by joaomoreno** [comment] 2016-02-23 16:48
Duplicate of #3022

**Closed by joaomoreno** 2016-02-23 16:48 UTC
Labels: bug, important
