### ISSUE TITLE
Heavy Resource usage

### ISSUE THREAD

**Issue by Looserof7** [Microsoft/vscode#21417] opened 2017-02-25 14:31 UTC
- VSCode Version:visual-studio-code-oss 1.9.1-1
- OS Version:Linux looserof7 4.4.51-1-MANJARO #1 SMP PREEMPT Thu Feb 23 21:39:40 UTC 2017 x86_64 GNU/Linux

Explanation:
Desktop Environment:- KDE
Enabled Extensions : GO

Vscode was really eating up all of my resources,
Screenshot's Included: 
1.While using Vscode (just changing cursor position up and down, I'm ain't even typing something)
2. After closing Vscode

Vs-code was using almost 76% of my cpu resources, It's too much, I thought it was light-weight.
[Click_here for Screen Shots](https://drive.google.com/open?id=0Bw1lzCYKRpNqX1laV0JmbXlhOUU)
other application which were opened while taking these screenshots:
1. Firefox,
2.Okular (Pdf viewer)
3.System Monitor

I'm sure these aren't using too much of my CPU resources as I wasn't using them(atmost 5%)
Where as vs-code is using too much while I'm not using it.
In above included screenshot( While using vs-code) to the left where CPU-usage is around 40%.

Need any further information, happy to help.

**Comment by roblourens** [comment] 2017-02-25 19:44
Can you run this command while vscode is running so we can see which processes are responsible?

`ps -eo pcpu,user,pid,command | grep Code | grep "^\s*[1-9]"`

**Comment by Looserof7** [comment] 2017-02-25 20:41
`ps -eo pcpu,user,pid,command | grep Code | grep "^\s*[1-9]"`

`93.4 loosero+  2147 /opt/VSCode-OSS/code-oss
 8.4 loosero+  2181 /opt/VSCode-OSS/code-oss --type=renderer --no-sandbox --primordial-pipe-token=95843332DB21ACD1924833001C59B9EB --lang=en-US --node-integration=true --background-color=#1E1E1E --enable-pinch --num-raster-threads=2 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --mojo-channel-token=2D3600EDE4771EA844787B4E7F0546AD --mojo-application-channel-token=95843332DB21ACD1924833001C59B9EB --channel=2147.0.1602250161 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd`

**Comment by roblourens** [comment] 2017-02-25 20:54
Thanks. It looks like you built this yourself (code-oss), does it happen when you run an official build?
Does it only do that when you move the cursor around, or all the time?

**Comment by Looserof7** [comment] 2017-02-25 21:27
I have built it from arch aur package available over [here](https://aur.archlinux.org/packages/visual-studio-code-oss/)

I use Manjaro which is based on arch linux, so I need to compile it in order to install.

While scrolling or typing anything in vscode increases my CPU usage from 30 - 40 %,
If I'm not using vscode but opened it, it uses 30 - 40 % of my cpu

So if I'm using vscode, cpu- usage is around 70-80%.

I will install in some other distribution and I will update my response, but it takes time because I need to install some other distribution, which supports deb or rpm

**Comment by Looserof7** [comment] 2017-02-25 21:40
All details related to memory allocation of this particular process from my system-monitor is pasted in this [gist](https://gist.github.com/Looserof7/8516c815be1bd4fa100e7e4bef37f4ef)

**Comment by roblourens** [comment] 2017-02-25 22:11
Ok, we don't test on that OS, so I don't think we can guarantee perf. But it would be helpful if you open chrome devtools and check for errors in the console, and also take a CPU profile while it's using high CPU.

**Comment by Tyriar** [comment] 2017-02-25 23:48
@Looserof7 I believe the .tar.gz at https://code.visualstudio.com/Download should run, can you try repro on that using Arch?

**Comment by Looserof7** [comment] 2017-02-26 18:10
I'm sorry for the delay I will try it and post results ASAP

**Comment by Tyriar** [comment] 2017-03-01 18:48
@Looserof7 can you repro after closing all windows and then launching with `code --disable-extensions`? Also by reduced how much do you mean? Typically idle should sit around 0-1% CPU in my experience.

**Comment by PriceKiller** [comment] 2017-03-07 18:08
Did you enable kde's newly featured global menubar? If so, that could be a cause.

**Comment by Looserof7** [comment] 2017-03-08 09:57
Yes I have enabled kde global menu-bar, I will give all the necessary details once I have some free time, I'm going to a remote where internet is not going to be available, so It may take 5 days for me to come back and give all the details.
I will see whether the problem is due to extensions or due to Kde global menu.

**Comment by PriceKiller** [comment] 2017-03-08 11:16
I also run visual-studio-code official binary (from AUR) on my machine (archlinux x86_64 plasma5.9). 
 When I enable the global menu, the usage of my cpu increase sharply.
When I run  `journalctl -r`,
The information:
`plasmashell[641]: Unhandled property update "children-display"`
is generated repeatively.
And the menus for the application on the global menu bar is totally useless.
Similarly, all the electron application suffers ( which should be the matter of atom ).
A similar issue on electron project has indicated that it is a bug:
[https://github.com/electron/electron/issues/8455](url)

**Comment by amitguptagwl** [comment] 2017-03-17 06:33
I'm on Ubuntu 14 and facing the similar issue. When I start vscode

1. it takes few mins to open
2. Then my laptop start behaving very slow
3. Then after sometime I need to restart my laptop.

On the other hand, if I use sublime (don't want to compare) for the same repo, it opens quickly and laptop works as expected.

I have 8gb RAM.

**Comment by kkeri** [comment] 2017-03-22 16:42
I had a very similar issue on Windows 7. One of the running VS Code processes notoriously ate up memory.

Solution: my temp directory was unavailable. It was redirected to a RAM disk which silently disappeared due to some misconfiguration. I have changed TEMP and TMP environment variables and VS Code now works properly. I hope this helps to locate the problem.

**Comment by Tyriar** [comment] 2017-04-21 19:41
Closing since there was no follow up from OP

**Closed by Tyriar** 2017-04-21 19:41 UTC
Labels: linux, needs more info, perf

**Comment by ChALkeR** [comment] 2017-07-12 10:11
This is most likely caused by https://github.com/electron/electron/issues/8455 (judging by the symptoms and globalmenu usage).

_Adding a link again, as the link in https://github.com/Microsoft/vscode/issues/21417#issuecomment-285015019 is broken atm._
