### ISSUE TITLE
SCM conflict with extension: SVG Viewer

### ISSUE THREAD

**Issue by JohnCido** [Microsoft/vscode#34879] opened 2017-09-23 15:02 UTC
- VSCode Version: 1.16.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Install Extension: SVG Viewer
2. Open SCM and there's a message says "No available SCM (没有可用的源控件)"

Reproduces without extensions: No

**Comment by JohnCido** [comment] 2017-09-25 05:51
![svg viewer conflict](https://user-images.githubusercontent.com/7105485/30793974-1e22910e-a18b-11e7-9fd7-b7c3d2fcd42b.gif)
Also confirmed that after enabled SVG Viewer and open SCM panel. There's no output in developer tool console.

**Comment by joaomoreno** [comment] 2017-09-25 12:44
I can't reproduce this. But this sounds like the extension blocks other extensions from executing at all. You should not get any language features in any language. Closing as duplicate of https://github.com/cssho/vscode-svgviewer/issues/35

**Closed by joaomoreno** 2017-09-25 12:44 UTC
Labels: new release, scm
