### ISSUE TITLE
Startup Editor

### ISSUE THREAD

**Issue by AdelMoustafa** [Microsoft/vscode#72332] opened 2019-04-15 11:10 UTC
Issue Type: <b>Bug</b>

I've set Workbench: Startup Editor to newUntitledFile and yet when I close the application and start it up again nothing opens.

Note: It was working properly before the last update.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.82GB (3.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.18.0

</details>

**Comment by aeschli** [comment] 2019-04-15 12:56
duplicate of https://github.com/Microsoft/vscode/issues/71837

This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed by aeschli** 2019-04-15 12:56 UTC
Labels: new release
