### ISSUE TITLE
Share settings with Microsoft account

### ISSUE THREAD

**Issue by eByte23** [Microsoft/vscode#10114] opened 2016-08-04 05:40 UTC
Add ability to login to VSCode with Microsoft account to sync visual studio settings across devices and Visual Studio '15 and VSCode

This would allow you to the keep track of previously installed("Owned") extensions like apps.
Sync user settings (switchable on/off)
Sync entire User Environment. Install all extension that have been synced and all settings, themes etc..

**Comment by pcgeek86** [comment] 2016-09-01 14:47
Dupe of #9999?

**Comment by mbeckenbach** [comment] 2016-10-26 12:40
I would like to vote 100 times for this. :-)

**Comment by tauqeerhassan** [comment] 2016-11-06 18:20
Me too :)

**Comment by yinonov** [comment] 2016-11-07 11:43
yes this is certainly a missing feature i keep on searching for. 
surprised it wasn't "born" with it as older visual studio versions partialy supported sync by account (at least with Visual Studio Team Services)

**Comment by neovive** [comment] 2016-11-14 16:40
JetBrains editors like IntelliJ/WebStorm offer a simple export/import via a flat file. Perhaps the ability to export/import a JSON file would work without the need to connect. Almost like running npm install to install dependencies for nodejs project.

**Comment by MaelstromCdn** [comment] 2016-12-27 22:50
This would be awesome! I'd also settle for the ability to set the location of the settings file so I could sync with something like OneDrive or Dropbox.

**Comment by zigmo** [comment] 2017-05-14 00:42
I had the experience right now after reinstalled windows. I was automatically looking for a login to reinstall all extensions and restore all my settings. Would be awesome to have this functionality.

**Comment by webceyhan** [comment] 2017-05-25 10:30
It was a must from the beginning but somehow missed until now.

Also a great opportunity for Microsoft to extend their dev network through the live account.

**Comment by bpasero** [comment] 2017-06-03 07:36
https://github.com/Microsoft/vscode/issues/2743

**Closed by bpasero** 2017-06-03 07:36 UTC
Labels: feature-request
