### ISSUE TITLE
UI: Sidebar Items gets force reordered

### ISSUE THREAD

**Issue by Jarrku** [microsoft/vscode#195766] opened 2023-10-17 08:00 UTC
Type: <b>Bug</b>

Seems like my sidebar items are force reordened to their  order when right clicking the bar to enable/disable bars. When dragging an icon, its gets reset to that order.

![CleanShot 2023-10-17 at 09 59 12](https://github.com/microsoft/vscode/assets/7694752/a4681489-458e-4540-8474-a847d604b8aa)

VS Code version: Code - Insiders 1.84.0-insider (f1c3b1dcf85e3b6ddb24b7dce0e4b122e8ce6233, 2023-10-17T05:45:00.205Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 9e8f29d5-de44-4f3a-a5ef-a25d03bcdf8f|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
markdown-preview-github-styles|bie|2.0.3
vscode-tailwindcss|bra|0.10.1
npm-intellisense|chr|1.4.5
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.4.0
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
vscode-google-translate|fun|1.4.13
vscode-graphql|Gra|0.8.19
vscode-graphql-syntax|Gra|1.2.2
vscode-peacock|joh|4.2.2
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.27.0
playwright|ms-|1.0.16
remote-containers|ms-|0.315.1
live-server|ms-|0.4.11
vsliveshare|ms-|1.0.5883
vscode-versionlens|pfl|1.9.0
vscode-thunder-client|ran|2.13.5
vscode-yaml|red|1.14.0
vscode-mdx|uni|1.4.0
errorlens|use|3.14.0
vscode-icons|vsc|12.5.0
fig|wit|0.0.7
vscode-import-cost|wix|3.3.0
pretty-ts-errors|yoa|0.5.2
vscode-open-in-github|ziy|1.3.6
grammarly|znc|0.22.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30859590
pythonregdiag:30859652
pyreplss2:30858576
pythonmypyd1:30859725
pythoncet0:30859736

```

</details>

**Comment by sbatten** [comment] 2023-12-20 22:05
I believe this issue is a dupe of a closed bug around that time and should now be resolved, sorry if it still repros, can you re-open the issue.

**Closed by sbatten** 2023-12-20 22:05 UTC
