### ISSUE TITLE
it is a BUG in 1.42 create new file not use highlights

### ISSUE THREAD

**Issue by guyuewuren** [microsoft/vscode#86971] opened 2019-12-14 05:02 UTC
- VSCode Version:1.42
- OS Version:windows 10 The latest version

Steps to Reproduce:

1.create a new file
2.Then save to a php file or html file

Does this issue occur when all extensions are disabled?: yes

it not to use file highlights,need to close and open the file

**Comment by lucasAmarall** [comment] 2019-12-14 05:29
Hello, are you sure about it? Do you are using some deep extension like `customize UI` or `vibrancy`? 
I was with the same problem some days ago but I was using visual code insiders, are you using this one too?

**Comment by guyuewuren** [comment] 2019-12-14 05:37
Yes, I'm sure .I also use this one .
![QQ截图20191214133705](https://user-images.githubusercontent.com/15320333/70844091-e11d7600-1e76-11ea-89c0-58debd78a09e.png)

**Comment by lucasAmarall** [comment] 2019-12-14 05:52
Yeah, now this is more clear for me, It's happening because you have no extensions to formate or highlight it, please check if you have the correct extensions installed and activated in your vs code.
Fist of all please create a new file but with fewer lines, vs code has one system to disable highlights on code if it can do your computer slower and I could see that this file is big.

**Comment by guyuewuren** [comment] 2019-12-14 06:45
no,it is a new BUG in 1.42,It hasn't appeared before，It's not that the file is too big, also not that I didn't install  extensions, the software comes with it.The first time I create a new file, add content, and save the file, it is not highlighted. When I close and reopen the file, it will be highlighted

**Comment by sarahkittyy** [comment] 2019-12-15 04:08
I can confirm this, it's an issue with file associations not working after creating a new file.

**Comment by bpasero** [comment] 2019-12-16 17:02
Oh, this is only in insiders.

**Comment by bpasero** [comment] 2019-12-16 17:19
This was a regression from a change I recently pushed with the rationale that saving an untitled file should carry over the selected language mode to the target. This only makes sense if the selected language mode is not "plaintext".

**Comment by RMacfarlane** [comment] 2020-01-15 23:53
@bpasero I'm still seeing this issue - if I create a new untitled file and then save it with a different file extension, the language mode doesn't change. Should I open a new issue or do you want to reuse this one?

Version: 1.42.0-insider
Commit: 33c79d5ad447956814a2a3658029dffb9e28bae6
Date: 2020-01-15T08:53:57.100Z

**Comment by bpasero** [comment] 2020-01-16 05:26
@RMacfarlane steps?

**Comment by RMacfarlane** [comment] 2020-01-16 16:42
1. Change `files.defaultLanguage` setting to `markdown`
2. Cmd+n to open new untitled file
3. Paste some typescript
4. Save the file with a `.ts` extension

Editor is still in `markdown` language mode. After closing and reopening the editor, the language mode changes to typescript.

**Closed** 2020-01-17 07:36 UTC
Labels: bug, confirmed, important, regression
