### ISSUE TITLE
Flickering underline for URLs

### ISSUE THREAD

**Issue by nisimjoseph** [microsoft/vscode#113814] opened 2021-01-05 11:43 UTC
1. be inside a JSON file make sure you have another Tab with any other file.
2. have one key with URL and one with text.
3. select the value of the key text.
4. go to the other tab and go back using Ctrl+Tab in keyboard.
5. the URL key value underline will flicker until you remove the selection.

https://user-images.githubusercontent.com/2305992/103642575-01294700-4f5c-11eb-85b1-4506b197f412.mov

**Comment by rzhao271** [comment] 2021-01-08 19:03
Duplicate of #76642

**Closed by rzhao271** 2021-01-08 19:03 UTC
