### ISSUE TITLE
Stop restarting extension host when root folders change

### ISSUE THREAD

**Issue by manuth** [Microsoft/vscode#66936] opened 2019-01-22 17:49 UTC
## Info
- VSCode Version: 1.31.0
- OS Version: Windows 10 Build 1809

## Steps to Reproduce:
1. Create an extension using [vscode-generator-code](https://github.com/Microsoft/vscode-generator-code)
2. In a test-file open up a workspace-folder using `vscode.workspace.updateWorkspaceFolders`

***extension.test.ts
```ts
suite(
    "Example",
    () =>
    {
        suiteSetup(
            async () =>
            {
                await new Promise(
                    (resolve, reject) =>
                    {
                        workspace.onDidChangeWorkspaceFolders(
                            () =>
                            {
                                resolve();
                            });

                        if (
                            !workspace.updateWorkspaceFolders(
                                0,
                                (workspace.workspaceFolders || []).length,
                                { name: "Test", uri: Uri.file(tempDir.FullName) }))
                        {
                            reject();
                        }
                    });
            });

        test("Example", () => true);
    });
```

## Expected Behavior
According to the Extension API VSCode should just restart and the extension-tests should continue running.

## Actual Behavior
VSCode restarts as expected but it also restarts the extension-Tests which causes an endless loop.
![image](https://user-images.githubusercontent.com/7085564/51554740-4985f200-1e76-11e9-8aea-355144ab3ce5.png)

**Comment by bpasero** [comment] 2019-01-23 09:36
Good patch. Happy for help if someone wants to chime in.

**Comment by manuth** [comment] 2019-01-23 14:37
Alright I just created a new branch for you to reproduce the error:
https://github.com/manuth/MarkdownConverter/tree/testrunner-issue

The error occurs when you start the debug-target called "Launch Tests".

**Comment by bpasero** [comment] 2019-01-23 15:59
@manuth does it also reproduce when you run "npm run test" from the command line of the extension folder?

**Comment by manuth** [comment] 2019-01-23 16:16
Sadly I can't start the extension-tests from the console.
I'm getting an error which says "Rejected cached data from file" repeatedly after `./vscode-test/Code.exe` started.

**Comment by manuth** [comment] 2019-01-23 16:32
Oh I'm sorry - I forgot to mention I created a separate branch for reproducing the issue.
You need to `git checkout testrunner-issue`.

**Comment by bpasero** [comment] 2019-01-23 16:49
Thanks, it reproduces.

**Comment by bpasero** [comment] 2019-01-30 16:34
I fixed the endless loop. Unfortunately we currently do not support testing across extension host restarts, so I will close this issue. In the future we will try to prevent an extension host restart, but this needs a bit more time to settle.

**Comment by manuth** [comment] 2019-01-30 16:42
So do you plan to let one set up and swap workspace-folders without having the Extension Host restarted?

**Comment by bpasero** [comment] 2019-01-30 17:00
@manuth yes, the fact that we restart the extension host currently is bad and we only do it because `rootPath` is API that was never ready for multi root. Hence, when this value changes we restart the extension host to stay compatible. But I think we need to revisit that.

**Comment by dbaeumer** [comment] 2019-02-01 11:58
I tested this under Windows using the branch in the manuth/MarkdownConverter@testrunner-issue and it still make the launched test instance to consume full CPU on the renderer.

**Comment by bpasero** [comment] 2019-02-01 12:10
Yeah I think its no use in fixing this area, rather we should simply stop restarting the extension host when root folders change.

**Comment by aeschli** [comment] 2019-02-22 15:46
@bpasero I reverted your fix as _autoStart is 'isRestart'.
Instead disabled restart if we are in tests (which hopefully we can enable soon also when not in tests)
See 14f25a610224cea1b7fc97da63ad2304951f60a5 and 46dd91dd01ed98054a7aa1abdb106b5e6c1c072d

Closing as the example above no longer endless loops (but still don't works as reload is necessary in single folder mode (storage paths change)

**Closed by aeschli** 2019-02-22 15:46 UTC
Labels: debt, extensions, workbench-multiroot

**Comment by bpasero** [comment] 2019-02-22 16:22
Well yeah, but I think we should not even restart even when not running tests...

**Comment by manuth** [comment] 2019-03-04 22:07
My example is getting stuck now and the debugger still seems to restart.
Is that to be expected?
