### ISSUE TITLE
Test: Finalized data transfer files api

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153404] opened 2022-06-28 00:23 UTC
Test for #147481

- [x] Mac @weinand
- [x] Linux @roblourens
- [x] Windows @justschen 

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23153404%0A%0A&assignees=mjbvz)

---

## Overview

The new `dataTransferFiles` API lets extensions access the contents of  files that are dropped into VS Code from external applications

## Testing
To get started, checkout this branch of the extension samples: https://github.com/microsoft/vscode-extension-samples/tree/drop-file-transfer

There are two extension samples you should use:

- `drop-on-document`
- `tree-view-sample`

I've added example code showing the `dataTransferFiles` API in both of them. 

Some scenarios to test:

1. Try dragging and dropping files into VS Code and confirm you can access the file contents 
1. Check the file `.name` and `.uri` properties for the file items. 

**Known limitations:**

- You cannot create a `FileDataTransfer` yourself
- We currently do not create files if you are dragging within VS Code. We may add this in the future but right now the intention is that this API is for reading external files

**Comment by weinand** [comment] 2022-06-28 15:19
@mjbvz I'm having a hard time to get this to work.
Is it correct that I have to use the shift modifier when drag-and-dropping files into a plain text document in order to get a files list inserted? Is there anything else I have to do?

I can hit breakpoints in the ReverseTextOnDropProvider and FileNameListOnDropProvider, and I see that a SnippetString is correctly built, but no text is inserted in the document.

I see this error in the console:

<img width="1016" alt="CleanShot 2022-06-28 at 17 18 59@2x" src="https://user-images.githubusercontent.com/1898161/176217068-f2890ee0-838a-4c62-9675-35edd17806ce.png">

**Comment by mjbvz** [comment] 2022-06-28 15:48
Sorry about that @weinand.  I forogt to push an update to that branch. Pushing that now

**Comment by weinand** [comment] 2022-06-28 15:53
@mjbvz and for the tree-view-sample I see an unknown proposed API:

<img width="236" alt="CleanShot 2022-06-28 at 17 52 09@2x" src="https://user-images.githubusercontent.com/1898161/176224698-d6ec3682-72e4-484e-a8ba-bf48218fb8b6.png">

**Comment by mjbvz** [comment] 2022-06-28 15:56
@weinand  That should be ok to ignore for testing but I'll push an update. The API has finalized

**Comment by weinand** [comment] 2022-06-28 16:00
@mjbvz thanks, the drop-on-document sample seems to work now.

**Comment by sadasant** [comment] 2022-06-28 17:47
@mjbvz At the moment I don't have access to a Linux environment. I'm asking around to make sure this issue is assigned to someone else.

**Comment by justschen** [comment] 2022-06-28 18:24
@mjbvz I'm not sure what the intended behavior here is, but when dragged in from the explorer, it only drops in the last item selected when multiple files are selected vs. when dropped in from OS.

![Recording 2022-06-28 at 11 14 34](https://user-images.githubusercontent.com/54879025/176254926-18a6c6b4-ef87-47eb-b60f-2c735ce5b943.gif)

Here's what I see when debugging - the `uris` is only of length one and it seems like the path is all the selected files appended together.

`path:  "/C:/Users/Justin Chen/Desktop/New folder/text1.txtC:/Users/Justin Chen/Desktop/New folder/text2.txtC:/Users/Justin Chen/Desktop/New folder/text3.txtC:/Users/Justin Chen/Desktop/New folder/text4.txtC:/Users/Justin Chen/Desktop/New folder/text5.txt"`

![image 1](https://user-images.githubusercontent.com/54879025/176255358-852bea28-cdb9-42a1-b17f-488e39ab11af.png)

**Comment by weinand** [comment] 2022-06-28 19:54
@mjbvz is the idea of the "tree-view-sample" to only allow drag-and-drop within that tree and/or does it support drops from outside?
If it only accepts drops from within, then issue #153535 is invalid.

**Comment by mjbvz** [comment] 2022-06-29 18:29
Yes the sample just logs the contents of dropped files to the dev tools. It does not handle the drop

**Comment by roblourens** [comment] 2022-06-29 18:43
But the tree-view-sample is supposed to log when I drag from the external file explorer onto the tree? Because the `sources` DataTransfer is empty and nothing is logged

**Comment by mjbvz** [comment] 2022-06-29 19:26
@roblourens Currently you also need to add the mime types of the files you want to receive to `dropMimeTypes`. So `image/png` for example. 

I'll update our code to support the special `files` type that lets you handle any type of file

**Comment by mjbvz** [comment] 2022-06-29 20:58
@roblourens You should now be able to use:

```
	dropMimeTypes = ['application/vnd.code.tree.testViewDragAndDrop', 'text/uri-list', 'files'];
```

To get all dropped files. 

@justschen I think that you are running into #152836. Will see if we can workaround that for this iteration

**Closed** 2022-06-30 21:38 UTC
Labels: testplan-item
