### ISSUE TITLE
Markdown Preview

### ISSUE THREAD

**Issue by Hiroki-Soeno** [Microsoft/vscode#26272] opened 2017-05-09 06:56 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.9.0|
|pdf|tomoki1207|0.2.0|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1. The following sentences are described by Markdown.
`こんな__文章__だとしっかり__プレビュー__されない`
2. If you have double-byte characters after `__aaa__`, your character will not be bold.

**Comment by mjbvz** [comment] 2017-05-09 18:04
Thanks. The bug is that `文章` and `プレビュー` are not bolded in the markdown preview, correct?

I believe this is by design. The [common mark spec for strong emphasis](http://spec.commonmark.org/0.27/#emphasis-and-strong-emphasis) requires `__` be surrounded by whitespace or punctuators.  This is also why `b` in this string is not rendered as bold text:

```markdown
a__b__c
```

This is also consistent with github's rendering:

> a__b__c

Closing as-designed

**Closed by mjbvz** 2017-05-09 18:04 UTC
Labels: as-designed, markdown
