### ISSUE TITLE
Application top menu does not unhide in Zen Mode when mouse is at top

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#16795] opened 2016-12-07 07:46 UTC
- VSCode Version: Insiders
- OS Version: Linux (Ubuntu)

test item #15647

Steps to Reproduce:

1. Enter Zen Mode on Ubuntu
2. Note that you cannot get your OS top app bar back (e.g. File, View, Help...) when hovering at the top of the screen like you can on Mac (or on Linux when not in Zen Mode).

<img width="1440" alt="screen shot 2016-12-06 at 11 44 15 pm" src="https://cloud.githubusercontent.com/assets/11839736/20959110/12ed8d74-bc0e-11e6-9752-be4f0bbf5230.png">

Should be able to see this when mouse is at top, so it's easy to discover how to get out of Zen Mode.

<img width="339" alt="screen shot 2016-12-06 at 11 46 52 pm" src="https://cloud.githubusercontent.com/assets/11839736/20959155/486367ee-bc0e-11e6-80fa-002db5efb6d4.png">

**Comment by isidorn** [comment] 2016-12-07 09:36
This is the default behavior when you go into full screen mode on linux. So we already had this concept when a user eneterd full screen -> so we are not introducing anything new.

I am not worried about people being trapped in zen mode since double esc gets out and since restarting vscode does not preserve zen mode.

Due to the above closing as designed

**Closed by isidorn** 2016-12-07 09:36 UTC
Labels: linux
