### ISSUE TITLE
Can't turn off Word Wrap

### ISSUE THREAD

**Issue by idiodabble** [microsoft/vscode#138570] opened 2021-12-07 04:44 UTC
Issue Type: <b>Bug</b>

In a fresh install of Windows 11 and VSCode:

1. Open .txt doc
2. Turn off word wrap just for that one file from the View menu
3. Go to File > Preferences > Settings and turn off word wrap
4. Close and re-open the file or close and re-open the editor. Either way, word wrap disappears

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

This seems similar to the following issue:
https://github.com/microsoft/vscode/issues/134486

But that issue was logged for the View command not persisting; mine doesn't even persist for the Preferences > Settings change.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.59GB (56.41GB free)|
|Process Argv|--crash-reporter-id 6c7e7078-f621-4645-a795-a32334556b4a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by alexdima** [comment] 2021-12-15 15:29
@idiodabble I think this might be a duplicate of https://github.com/microsoft/vscode/issues/119947 . Are you by any chance opening a file which has more than 50% of its content lies on lines with the length > 10k ?

**Closed** 2021-12-23 11:26 UTC
Labels: needs more info, editor-wrapping
