### ISSUE TITLE
Inline change review: being able to select and copy deleted code

### ISSUE THREAD

**Issue by pmiossec** [Microsoft/vscode#42123] opened 2018-01-24 23:16 UTC
In the [Inline change review](https://code.visualstudio.com/updates/v1_18#_inline-change-review) feature introduced in v1.18,  I want to be able to select and copy the lines of code that are deleted (the ones displayed with the red background.)

It is sometimes useful when you want to partly revert some changes...

- VSCode Version: >=1.18
- OS Version: Windows 7 & 10

Steps to Reproduce:

1. Updates some lines
2. Open the `Inline change review` in the gutter
3. You are unable to select and copy the lines marked "deleted" (but are able to select/copy the added lines)

**Comment by usernamehw** [comment] 2018-01-25 08:48
Duplicate of https://github.com/Microsoft/vscode/issues/8226

**Closed** 2018-01-25 10:05 UTC
Labels: *duplicate, editor, editor-core
