### ISSUE TITLE
Cannot remote development over SSH after upgrade

### ISSUE THREAD

**Issue by gameliee** [microsoft/vscode#196041] opened 2023-10-19 20:41 UTC
Type: <b>Bug</b>

I was using remote-ssh to access my server, it had worked very well. But after a update to the newest version, vscode keep connecting->connected and then disconnected, over and over again

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 21.6.0
Modes:
Connection to 'SSH: abc' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 9, 9|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id 55308c57-7792-4339-897e-ea782b495d57|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: abc' could not be established  Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pyreplss1:30865275
pythoncet00cf:30859750
h48ei257:30866288
pythontbext0cf:30864173

```

</details>

**Comment by ductai199x** [comment] 2023-10-20 14:26
potentially a duplicate of this issue here, no answers yet from vscode team as of now: https://github.com/microsoft/vscode/issues/195617

**Comment by rebornix** [comment] 2023-10-20 17:50
This is a duplicate of https://github.com/microsoft/vscode/issues/195617 and we are working on a fix now. Let's track this in https://github.com/microsoft/vscode/issues/195617, thank you!

**Closed by rebornix** 2023-10-20 17:50 UTC
Labels: *duplicate
