### ISSUE TITLE
Imports are updated for all my files with the wrong path

### ISSUE THREAD

**Issue by inkubux** [Microsoft/vscode#52675] opened 2018-06-22 11:52 UTC
Since yesterday my vscode is trying to hard to update my imports but it ends up failing and puts a a path to a typescript cache.

I'll be glad to  help provide useful information but the behavior seems quite random. It happened to me 3 times yesterday. It even gos as far to update require from my webpack files...

![capture d ecran 2018-06-22 a 07 26 29](https://user-images.githubusercontent.com/342110/41775282-562815f2-75f1-11e8-86a1-5cfc81e86167.png)

I did not change these 173 files.. only one or 2..

![capture d ecran 2018-06-22 a 07 30 00](https://user-images.githubusercontent.com/342110/41774566-3c570a14-75ee-11e8-88cf-bb251e94deeb.png)

I also see a bunch of insider helpers running.. there might be a rogue one in there that does nasty stuff in the background.

<img width="1117" alt="capture d ecran 2018-06-22 a 07 34 38" src="https://user-images.githubusercontent.com/342110/41774696-dfc13b52-75ee-11e8-96cd-ca598118f930.png">

Even though it should not try to update imports on file I haven't touched and certainly not on npm dependencies.

- VSCode Version: Version 1.25.0-insider (1.25.0-insider) c5c7d43b65bcbbb3851fbd972fad077631c707e3

- OS Version: OSX 10.13.4

Steps to Reproduce:
The first time I did.
1. Open vscode play with files 
2. git pull from the command line
3. All pulled files imports a rewritten with a path like this ` import React, { PureComponent } from '../../../../../../../Library/Caches/typescript/2.9/node_modules/@types/react';`

Does this issue occur when all extensions are disabled?: Yes/No
It does not happen enough to be able to tell (enough is pretty relative here as 3 times last day)

**Comment by inkubux** [comment] 2018-06-23 22:55
It happened again after a complete new install no plugins just by renaming a file on my project, it did rename all my imports in the project with "'../../../../../../../Library/Caches/typescript/2.9/node_modules/@types/*"

I disabled auto import renaming for now.

**Comment by mjbvz** [comment] 2018-06-25 23:21
Duplicate of https://github.com/Microsoft/TypeScript/issues/24914

Will add workaround to prevent this on the VS Code side

**Comment by SMotaal** [comment] 2018-07-07 22:52
This is happening for me since updateImportsOnFileMove with latest public release. 

Here is the closest thing to a repo which I know will cause `import express from 'express'` to become `from '../../../../Library/Caches/typescript/2.9/node_modules/@types/express'` when you move "http-server" in and out of "modules/server/lib" affecting "types.d.ts" and others under "modules/server".

[sample-workspace-v0.0.0.zip](https://github.com/Microsoft/vscode/files/2173154/sample-workspace-v0.0.0.zip)

**Comment by rikur** [comment] 2018-07-08 01:53
Keeps happening to me as well, horrible! I'll figure out how to downgrade.

**Comment by JacksonKearl** [comment] 2018-07-08 17:04
@mjbvz is this expected?

**Comment by pushbuttons** [comment] 2018-07-09 04:16
Same behaviour since updating to 1.25.0 in macOS 10.12.6

**Comment by ZSkycat** [comment] 2018-07-09 12:08
This is the problem I have encountered.

tsconfig.json
```json
{
    "compilerOptions": {
        "rootDir": ".",
        "outDir": "./dist",
        "target": "esnext",
        "module": "esnext",
        "moduleResolution": "node",
        "baseUrl": ".",
        "paths": {
            "src/*": ["./src/*"]
        },
        "sourceMap": true,
        "jsx": "preserve",
        "experimentalDecorators": true,
        "strict": true,
        "suppressImplicitAnyIndexErrors": true,
        "types": [],
    },
    "file": [
        "./node_modules/vue-router/types/vue.d.ts",
        "./node_modules/vuex/types/vue.d.ts",
    ],
    "include": [
        "./src/**/*",
    ],
}

```

![image](https://user-images.githubusercontent.com/20368649/42449529-98e19c22-83b3-11e8-84a9-3efc910528b4.png)
![image](https://user-images.githubusercontent.com/20368649/42449531-9c365fde-83b3-11e8-80b9-8b8f03846aa7.png)

**Comment by mjbvz** [comment] 2018-07-09 16:18
Duplicate of Microsoft/TypeScript#24914

Let me know if you see this in VSCode insiders when using TS 3.0

**Closed by mjbvz** 2018-07-09 16:18 UTC
Labels: bug, javascript, verification-found

**Comment by JacksonKearl** [comment] 2018-07-09 17:13
@mjbvz should we add another workaround/do we know why the previous one isn't catching these cases?

**Comment by twhoff** [comment] 2018-07-10 14:18
yeah this is making me crazy... how do we fix it?

**Comment by scottmas** [comment] 2018-07-10 20:32
Yeah, this just happened. Updated all my React imports everywhere in my project to ```
import React from "../../../../Library/Caches/typescript/2.9/node_modules/@types/react/../../Library/Caches/typescript/2.9/node_modules/@types/react";
```. Had to manually go through and revert the changes. Was a super pain. 
. Had to manually

**Comment by mikecargal** [comment] 2018-07-13 20:52
Seeing the same issue (I'm not even using typescript.  (other than some obvious implicit thing with VSCode)) .   Every few minutes, dozens (sometimes 100+) of files show up as opened and changed in VSCode.  Most (oddly, not all) have this breaking change on the import statements.

Very frustrating, VSCode just about unusable with this behavior.

**Comment by mjbvz** [comment] 2018-07-13 20:58
This should be fixed in VS Code insiders. You can also upgrade your workspace to use TypeScript 3.0 (or TS 2.9.1) by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)
