### ISSUE TITLE
Multi Target debug - ECONNREFUSED with Console - integrated terminal

### ISSUE THREAD

**Issue by nroberts1** [Microsoft/vscode#40298] opened 2017-12-15 13:46 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.5.0

---

Multiple launch.json setups ran together fail with "Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9228" for any configs with:
`"console": "integratedTerminal"`

Example:
```json
"version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Editor",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "debug"
            ],
            "port": 9228,
            "cwd": "${workspaceFolder}/Editor",
            "console": "integratedTerminal"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Engine",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "debug"
            ],
            "port": 9229,
            "cwd": "${workspaceFolder}/engine",
            "console": "integratedTerminal"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Applications",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "debug"
            ],
            "port": 9227,
            "cwd": "${workspaceFolder}/applications",
            "console": "integratedTerminal"
        }
    ],
    "compounds": [
        {
            "name": "All Servers",
            "configurations": ["Editor", "Engine", "Applications"]
        }
    ]
}
```
Took a while to narrow the error down to this setup. Each application individually runs ok but when ran together I get the error. 

I'm guessing "console": "externalTerminal" maybe my answer but struggling to find an example of setting this up.
Reproduces without extensions: Yes

**Comment by nroberts1** [comment] 2017-12-15 13:56
Got the external terminal working:

launch.json
`"console": "externalTerminal"`

and 

settings.json
`"terminal.external.osxExec": "Terminal.app",`

This is working fine. Would be interested to know if multiple internal terminals could be made to work though.

**Comment by weinand** [comment] 2017-12-15 14:10
duplicate of #37589

**Closed by weinand** 2017-12-15 14:10 UTC
Labels: bug, debug
