### ISSUE TITLE
Backtick shortcut issue - macos - italian layout

### ISSUE THREAD

**Issue by ptkdev** [microsoft/vscode#136580] opened 2021-11-06 18:41 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62
- OS Version: macos monteray - italian keyboard

Hi, the latest version of vscode switched backtick shortcut (on macos - italian layout)

**from**: `option + \`
**to**: `option + 9`

Why? In other ide or apps the shortcut for backtick is `option + \` but in vscode no.

NOTE: backtick is ` symbol

**Comment by alexdima** [comment] 2021-11-10 15:22
@ptkdev I don't believe we had any change that could influence the typing of `` ` `` under the Italian keyboard layout. Also on my machine, with the Italian keyboard layout,  <kbd>option</kbd>+<kbd>[Digit9]</kbd> produces `` ` ``, while <kbd>option</kbd>+<kbd>[Backslash]</kbd> produces `` ¶ ``.

This is not a change that shipped with VS Code, because I can reproduce this also in VS Code 1.61, and also with TextEdit, Word, and Chrome, and this is also reflected in the Apple keyboard viewer:
  

https://user-images.githubusercontent.com/5047891/141140604-bd8198b3-cc58-4a91-99eb-ad466f333636.mp4

**Comment by ptkdev** [comment] 2021-11-10 19:19
@alexdima ok, but you not use italian keyboard in the video.

**Comment by ptkdev** [comment] 2021-11-10 19:38
Ok, but with physical keyboard (macos monteray - italian - macbook pro m1) result is this:

https://user-images.githubusercontent.com/442844/141181582-9da725cd-e555-4935-b508-729b16476050.mp4

**Comment by ptkdev** [comment] 2021-11-10 19:39
@alexdima Ok, but with physical keyboard (macos monteray - italian - macbook pro m1) result is this:

https://user-images.githubusercontent.com/442844/141181582-9da725cd-e555-4935-b508-729b16476050.mp4

**Comment by AliShadman95** [comment] 2021-11-10 20:47
@alexdima same problem here with macos monteray - italian - Macbook Pro M1


https://user-images.githubusercontent.com/50172746/141190708-81b0b206-4084-46ea-aa4d-f00b2aa42313.mp4

**Comment by alexdima** [comment] 2021-11-10 21:01
Thank you for your videos. This might be a problem specific to monteray, as I cannot reproduce on macOS Big Sur when trying with an ISO keyboard (just like yours, but with the Swiss labels printed on it)

https://user-images.githubusercontent.com/5047891/141192726-8e399d40-a584-4d46-a9df-ce425e980133.mp4

.

**Comment by alexdima** [comment] 2021-11-10 21:17
Here's a workaround that might work, but I cannot guarantee because I can't troubleshoot what you're seeing:

```
{ "key": "alt+[Backquote]", "command": "type", "args": {"text":"`" }, "when": "textFocus" }
```

You might need to use `[IntlBackslash]` instead of `[Backquote]`, I am not sure.

cc @deepak1556 this might be caused by our fixing of Chromium's `[IntlBackslash]` / `[Backquote]` swap but it looks to be a problem only on monteray.

**Comment by superandrew** [comment] 2021-11-14 21:08
same problem here (took me a while to figure out it wasn't some project or vs code setting). I could swear it worked until some days ago. But when I checked on my macbook the problem was there as well. Very unfortunate.

**Comment by superandrew** [comment] 2021-11-14 21:10
@alexdima how should we use that workaround? in settings.json?

**Comment by superandrew** [comment] 2021-11-14 22:45
Hi, I was pretty sure it wasn't monterey. Because I had monterey far before this problem occurred. The problem is triggered because github copilot extension has this keybinding mapped for the suggestion (alt+`). Once uninstalled the extension, vs code returns to normal. So I think this issue should be created on github's copilot repository, if exists.

**Comment by superandrew** [comment] 2021-11-15 06:31
I posted the feedback here https://github.com/github/feedback/discussions/7712

**Comment by alexdima** [comment] 2021-12-03 15:54
I have finally installed monterey and could try again with it. I still cannot reproduce:

https://user-images.githubusercontent.com/5047891/144631940-a10c5547-72dc-4735-b62d-0cf72c42a1cd.mp4

@ptkdev @AliShadman95 Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `` option+` ``. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help. 

Also, can you please try to disable all your extensions?

**Comment by superandrew** [comment] 2021-12-03 15:55
@alexdima it was a conflict with github copilot's keyboard shortcut

**Comment by alexdima** [comment] 2021-12-03 16:04
:+1: Then I will optimistically close the issue.

**Closed by alexdima** 2021-12-03 16:04 UTC
Labels: needs more info, macos, keyboard-layout
