### ISSUE TITLE
Why are there 2 suggestions in Peek definition

### ISSUE THREAD

**Issue by axelnormand** [Microsoft/vscode#29173] opened 2017-06-21 08:20 UTC
- VSCode Version: 1.13.1
- OS Version: CentOS

Steps to Reproduce:

1. Create a simple React component in es6 and Flow

![image](https://user-images.githubusercontent.com/96266/27373976-16fad1d0-5662-11e7-8f9e-45a0eb364750.png)

2. ctrl+click on the es6 import from another file brings me to the "export default" line
3. Then ctrl+click on the export default brings up Peek with 2 identical definitions

![image](https://user-images.githubusercontent.com/96266/27374027-456b3b4a-5662-11e7-85ce-f600cac4d32c.png)

Is there a way for the initial Go To definition to skip the export default and go straight the the class definition line?

Also why are there 2 definitions in the Peek window? I'd prefer to turn the Peek off in this case as its quite annoying.

Many thanks for a wonderful IDE btw.

**Comment by mjbvz** [comment] 2017-06-21 21:08
We'll jump right to the definition if there is only a single implementation.

We don't have native support for flow. What extension are you using here? If you comment out the flow typings and change the filetype to JavaScript, do you still see this issue?

**Comment by mjbvz** [comment] 2017-06-29 01:15
Closing as we need more information to investigate this. I believe this may be caused by an extension since we don't ship with builtin flow support

**Closed by mjbvz** 2017-06-29 01:15 UTC
Labels: caused-by-extension, javascript, needs more info

**Comment by axelnormand** [comment] 2017-06-30 10:07
Sorry been out of the country. 
Thanks for the response. It must be the flow typed plugin. 
Will try what you suggested and perhaps liaise with the flow plugin author.
