### ISSUE TITLE
Integrated Terminal window is non-responsive

### ISSUE THREAD

**Issue by jgemmaEIS** [Microsoft/vscode#33447] opened 2017-08-29 19:55 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
file-templates|brp|1.2.0
vs-keybindings|ms-|0.1.7

---

Steps to Reproduce:

1. Go to View|Integrated Terminal
2. Click into the terminal's editor window and that white outlined box becomes filled-in and you can't type anything.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment] 2017-08-29 20:48
@jgemmaEIS you likely have an invalid shell path. Try adding this to your settings.json file:

```js
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
```

**Comment by jgemmaEIS** [comment] 2017-08-30 12:58
Mine is currently set to "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
changing it to "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe" does not fix the issue.

**Comment by Tyriar** [comment] 2017-08-30 15:09
Hmm, are there any errors in the devtools console? (Help > Toggle Developer Tools)

**Comment by jgemmaEIS** [comment] 2017-08-30 15:31
I'm completely new to VS Code, so I'm not exactly sure why the dev tools would help.
I'm just trying to type in the terminal window.

**Comment by Tyriar** [comment] 2017-08-30 15:39
@jgemmaEIS if exceptions in the terminal were the cause, they should show up in the console.

**Comment by jgemmaEIS** [comment] 2017-08-30 15:51
This has been an issue from the day I installed VS code (5 days ago), but now all of a sudden it is working.  I changed nothing.

**Comment by Tyriar** [comment] 2017-08-30 15:55
@jgemmaEIS strange, please follow up if you see it again.

**Comment by jgemmaEIS** [comment] 2017-08-30 18:40
It just did it again.  I closed the app this morning and just reopened it.  Non-responsive.  The dropdown list contains just "1:cmd".  When it worked this morning it contained "1:poweshell"

**Comment by Tyriar** [comment] 2017-08-30 18:50
Do you still have `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",` in your settings?

**Comment by jgemmaEIS** [comment] 2017-08-30 18:57
No.  Like I said before, it made no difference for me so I removed it.
I still have the default:
  "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",

**Comment by jgemmaEIS** [comment] 2017-08-30 18:58
Now when I "Open Folder...", the explorer tree is empty and the terminal shows "1:powershell"

**Comment by rkeithhill** [comment] 2017-10-25 04:55
This is happening to me as well on 1.17.2:

![image](https://user-images.githubusercontent.com/5177512/31981117-50fc0fe8-b90e-11e7-817a-6b80d3da7e17.png)

**Comment by rkeithhill** [comment] 2017-10-25 05:05
Interestingly, the PowerShell terminal in today's VSCode Insiders drop is working fine.  Go figure.

**Comment by Tyriar** [comment] 2017-10-26 03:58
@rkeithhill that issue was introduced in 1.17.0 and fixed in 1.17.2 😃

**Comment by rkeithhill** [comment] 2017-10-26 04:05
But I'm using 1.17.2.  That said, this doesn't happen on all my system.  Just this laptop (running Windows 10 FCU).

**Comment by rkeithhill** [comment] 2017-10-28 18:53
Yes, I'm using the 64-bit client but today I can't repro that issue.  FYI I use the default shell (PowerShell) on Windows.

**Closed** 2017-12-26 19:25 UTC
Labels: *not-reproducible, integrated-terminal, needs more info
