### ISSUE TITLE
Menu: Application icon is improperly laid out

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54540] opened 2018-07-18 07:34 UTC
Look at the application icon in the following GIF:

![peek 2018-07-18 09-33](https://user-images.githubusercontent.com/22350/42866739-ba2b0952-8a6d-11e8-9285-bb6c5ec6b7ad.gif)

**Comment by yume-chan** [comment] 2018-07-18 08:38
Duplicate of #52920

**Closed** 2018-07-18 09:37 UTC
Labels: workbench-menu
