### ISSUE TITLE
Update to Chokidar v3

### ISSUE THREAD

**Issue by paulmillr** [microsoft/vscode#77143] opened 2019-07-10 21:27 UTC
Hey! I wonder which steps would it take to:

1. Update to chokidar v3
2. Drop `vscode-chokidar` and `vscode-fsevents` packages.

Chokidar v3 incorporates a lot of improvements. We've decreased RAM consumption on large directories by a huge amount; and reduced dependency count by a factor of 13. All releases are signed now. See my blog post: [Chokidar 3: How to save 32TB of traffic every week with one NPM package](https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/)

Chokidar v3 requires nodejs 8 and higher. Unsure if that's good with vscode?

BTW, i'm keeping an eye on the Linux issue Ben mentioned.

cc @bpasero

**Comment by bpasero** [comment] 2019-07-11 06:58
Hi @paulmillr, yes totally want to update and drop our custom forks. 

I do not think there is something blocking for us to move to version 3. However, one thing I was hoping gets resolved, still seems to be an issue: https://github.com/paulmillr/chokidar/issues/860 (and the predecessor https://github.com/paulmillr/chokidar/issues/447).

Any thoughts? This is the cause of one of our most upvoted watcher issues: https://github.com/microsoft/vscode/issues/3998

**Comment by paulmillr** [comment] 2019-07-11 19:59
For mac, I think the issue has been resolved if a user has fsevents. 

For linux, i’ll dive into it.

**Comment by bpasero** [comment] 2019-07-12 05:48
@paulmillr I tested specifically on macOS (version 3.0), were there any changes that came in recently that could have an impact? Maybe you check both OS.

**Comment by paulmillr** [comment] 2019-07-18 04:44
@bpasero check out [the chokidar v2 vs v3 benchmarks](https://jsmonk.github.io/chokidar-benchmarks/) — there were definitely some massive improvements across all platforms.

**Comment by ashthespy** [comment] 2019-08-02 15:25
https://github.com/paulmillr/readdirp/issues/99#issuecomment-517095541 is a possible blocker for this, as VS Code also runs on `node v10.11.0` currently.

**Comment by paulmillr** [comment] 2019-08-02 16:04
Bigints are supported since 10.2 or so, I don't think this is a root cause of the issue.

**Comment by ashthespy** [comment] 2019-08-02 17:07
Cross linking - https://github.com/electron/electron/pull/15323 is the actual blocker.

**Comment by bpasero** [comment] 2019-08-06 08:30
@ashthespy your comment in https://github.com/paulmillr/readdirp/issues/99#issuecomment-517779724 seems to suggest that this is fixed in Electron 4? VSCode is using Electron 4 since 2 months.

**Comment by ashthespy** [comment] 2019-08-06 08:48
> 
> 
> @ashthespy your comment in [paulmillr/readdirp#99 (comment)](https://github.com/paulmillr/readdirp/issues/99#issuecomment-517779724) seems to suggest that this is fixed in Electron 4? VSCode is using Electron 4 since 2 months.

Initially https://github.com/paulmillr/readdirp/issues/99#issuecomment-517095541 seemed to suggest that it was a Node v10 vs v12 issue, but we did indeed figure out it's an electron issue. 
So this isn't a blocker any more!

**Comment by paulmillr** [comment] 2019-08-14 14:05
readdirp-3.1.2 is out with the fix for Electron.

**Comment by bpasero** [comment] 2019-08-26 06:55
@paulmillr if we can get https://github.com/micromatch/anymatch/pull/34 in, that would reduce our needed forks from 2 to 1. In order to get to 0 though we need to allow to set the options from chokidar too, or just hardcode the `{ dot: true }` option.

**Comment by paulmillr** [comment] 2019-08-26 10:37
Easy

**Comment by paulmillr** [comment] 2019-08-30 01:46
@bpasero chokidar@master now uses anymatch@3.1 with `dot: true` by default.

**Comment by bpasero** [comment] 2019-08-30 05:31
@paulmillr awesome, thanks a ton!! once that is out on NPM we can drop all our forks 🚀

**Comment by paulmillr** [comment] 2019-08-30 11:13
@bpasero could you try how master works meanwhile?

**Comment by bpasero** [comment] 2019-08-30 12:13
@paulmillr my first testing with `master` looks good in terms of respecting ignore patterns with a leading "." so I think from that point of view, this change looks good to us. 

Still have to do some regression testing to see if events are coming in as before. If you know anything I should watch out for, let me know. We currently only use the watcher on macOS and Linux.

**Comment by bpasero** [comment] 2019-08-30 12:20
Looks like https://github.com/paulmillr/chokidar/issues/855#issuecomment-526580079 needs to be reopened, I see it in our tests too.

**Comment by bpasero** [comment] 2019-08-30 15:06
...I am not happy with the new performance on Linux. It seems better on macOS, but not on Linux in my testing. Will follow up in an issue.

**Comment by paulmillr** [comment] 2019-09-16 19:10
chokidar v3.1 is up!

**Comment by bpasero** [comment] 2019-09-17 06:33
via https://github.com/microsoft/vscode/pull/81028

**Closed by bpasero** 2019-09-17 06:33 UTC
Labels: debt, file-watcher

**Comment by paulmillr** [comment] 2019-10-01 02:44
@bpasero let's update to 3.2, just released this

**Comment by bpasero** [comment] 2019-10-01 05:24
Will do next week, we close for endgame.
