### ISSUE TITLE
Introduce incremental expression selection

### ISSUE THREAD

**Issue by guy-kdm** [Microsoft/vscode#12220] opened 2016-09-18 14:20 UTC
Hi guys, 
This really has a ton of use cases. It allows you to select the expression the cursor is on and with each extra press expand the selection to the containing expression. Say the cursor is on a variable named 'foo' in statement 'bar' in block 'foobar' - it will first select 'foo' then 'bar', then 'foobar', ext... This might be complicated to implement but incredibly useful. :)

**Comment by jugglingcats** [comment] 2016-11-10 08:27
This is incredibly useful and I find it hard to live without it. For reference in the Intellij products this is Ctrl+W

**Comment by Maxhodges** [comment] 2017-08-06 18:56
@guy-kdm  I'm not sure if we are talking about the same thing, because Shift+Alt+LeftArrow only extends the selection left or right (it doesn't expand up the node tree).

I'm documented my request here with animated gifs to show the expected behavior
#32069

**Comment by alexandrudima** [comment] 2017-11-23 10:50
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Closed by alexandrudima** 2017-11-23 10:50 UTC
Labels: editor, feature-request

**Comment by Maxhodges** [comment] 2017-11-23 13:43
hi @alexandrudima this issue continues to annoy me and makes me much less productive. Since you have implemented the feature, perhaps this should be labeled as a bug and not a feature request. Then maybe the team would give it a higher priority--since someone did take the time to implement it (they just didn't get it right yet).

**Comment by alexandrudima** [comment] 2017-11-23 15:33
Let's continue discussion in #4795
