### ISSUE TITLE
(Linux, V1.3) Cannot install extensions

### ISSUE THREAD

**Issue by interactiveblueprints** [Microsoft/vscode#9063] opened 2016-07-11 09:28 UTC
- VSCode Version: 1.3.0-1467909982
- OS Version: Linux Mint 17.3 (Ubuntu 14.04 based)

Steps to Reproduce:

1. Install version 1.2
2. Update to version 1.2.1
3. Update to version 1.3
4. Click extension icon
5. Search for "eslint" (for example)
6. Click on "install"
7. Nothing happens, but errors show in Developer tools.

Error in developer tools:

shell.ts:416 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ shell.ts:416(anonymous function) @ shell.ts:318e.onUnexpectedError @ errors.ts:73u @ errors.ts:88(anonymous function) @ winjs.base.js:43(anonymous function) @ winjs.base.js:38
winjs.base.js:45 WARNING: Promise with no error callback:46
winjs.base.js:46 Object {exception: null, error: Error: Cannot read property 'call' of undefined, promise: i.C…s.d…e._oncancel, handler: undefined, id: 46…}
winjs.base.js:45 WARNING: Promise with no error callback:47
winjs.base.js:46 Object {exception: null, error: Error: Cannot read property 'call' of undefined, promise: i.C…s.d…e._oncancel, handler: undefined, id: 47…}

It seems that version 1.2 was called visual-studio-code and version 1.3 is called code so both are installed simultaneously. Removing version 1.2 does not make a difference.

Workaround: 
1. Remove version 1.3, 
2. Install version 1.2.1 & start application
3. ctrl-P, type ?  (typing ext install directly will not work)
4. select "Extension install"
5. Search & install the wanted extensions
6. close application
7. Install version 1.3
8. Extensions are installed and working

**Comment by weinand** [comment] 2016-07-11 10:15
duplicate of https://github.com/Microsoft/vscode/issues/8859

**Closed by weinand** 2016-07-11 10:15 UTC
