### ISSUE TITLE
Disable live code analysis easily and on selected files

### ISSUE THREAD

**Issue by JoseAngel-MAD** [microsoft/vscode#183551] opened 2023-05-26 14:38 UTC
Type: <b>Feature Request</b>

Hello!

Visual Studio Code is wonderful and works great! Thank you!

May I ask for the ability to disable live code analysis EASILY within the app's main menu, maybe with a single right-click or keyboard shortcut?
Having the option to disable the live code analysis ONLY on selected files and on all files would be a great new feature.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

**Comment by gjsjohnmurray** [comment] 2023-05-26 15:47
> live code analysis

Please clarify what you mean by "live code analysis".

**Comment by JoseAngel-MAD** [comment] 2023-05-27 07:59
You are right. Live code analysis is not the correct name of the feature.

I mean Type Checking JavaScript

https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript


After reading the docs, it is said that I can opt individual files out of
type checking with a // @ts nocheck comment at the top of the file.
Am I getting this right?

If disabling type checking on single files is as simple as stated, please
remove this issue and excuse me.

Thank you and my apologies.

**Comment by mjbvz** [comment] 2023-12-05 17:09
Duplicate of #199246

**Closed by mjbvz** 2023-12-05 17:09 UTC
