### ISSUE TITLE
Cannot read property 'length' of undefine

### ISSUE THREAD

**Issue by v2beta** [Microsoft/vscode#34847] opened 2017-09-22 14:51 UTC
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 Error processing request. Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:8537:18)
    at Object.getSuggestionForNonexistentSymbol (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:19526:95)
    at Object.getActionsForCorrectSpelling [as getCodeActions] (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:73108:38)
    at /Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:72832:33
    at Object.forEach (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:1293:30)
    at Object.getFixes (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:72831:16)
    at /Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:76581:35
    at Object.flatMap (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:1525:25)
    at Object.getCodeFixesAtPosition (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:76579:23)
    at IOSession.Session.getCodeFixes (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:82554:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:81476:61)
    at /Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:82698:88
    at IOSession.Session.executeWithRequestId (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:82689:28)
    at IOSession.Session.executeCommand (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:82698:33)
    at IOSession.Session.onMessage (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:82718:35)
    at Interface.<anonymous> (/Users/selcuk/Documents/casemanagement/node_modules/typescript/lib/tsserver.js:83804:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

**Comment by mjbvz** [comment] 2017-09-22 17:35
Duplicate of https://github.com/Microsoft/TypeScript/issues/18390

**Closed by mjbvz** 2017-09-22 17:35 UTC
Labels: duplicate, typescript, upstream
