### ISSUE TITLE
When using node.exe in the VS Code terminal, a bug is encountered.

### ISSUE THREAD

**Issue by lanrengm** [microsoft/vscode#230794] opened 2024-10-08 11:04 UTC
Does this issue occur when all extensions are disabled?:  Yes

- VS Code Version: 
版本: 1.94.0 (system setup)
提交: d78a74bcdfad14d5d3b1b782f87255d802b57511
日期: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: Windows 10 22H2
- CPU: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz   2.90 GHz

Steps to Reproduce:

1. Copy this code:
![image-20241008183114198](https://github.com/user-attachments/assets/c31c9f7b-1b3c-4f35-9c2b-fe7ceea893e2)

```js
m = new Map([
	[1,2],
	[3,4]
]);
iter = m.entries();
```

2. Run `node` in the VSCode terminal (using cmd.exe), right-click the mouse, and paste the code in the terminal:

node version: v20.15.0

![image-20241008175839647](https://github.com/user-attachments/assets/b8fa4948-449d-4116-985e-3bd54734e534)

It's only happening in VS Code terminal; the system Command Prompt terminal is normal.

The bug does not occur when pasting this code:

```js
m = new Map([[1,2],[3,4]]);
iter = m.entries();
```

**Comment by meganrogge** [comment] 2024-10-14 15:18
can you describe the bug in words?

**Comment by meganrogge** [comment] 2024-10-14 15:18
IE expectation vs actual

**Comment by lanrengm** [comment] 2024-10-19 06:24
When there are multiple lines of arrays in the code, pasting the code will cause the brackets at the end of the statement in the next line of the array to appear incorrectly in the previous line, causing the code to run incorrectly.

When pasting quickly and continuously, the probability of bugs appearing is very high.

**Comment by lanrengm** [comment] 2024-10-19 06:25
> can you describe the bug in words?

When there are multiple lines of arrays in the code, pasting the code will cause the brackets at the end of the statement in the next line of the array to appear incorrectly in the previous line, causing the code to run incorrectly.

When pasting quickly and continuously, the probability of bugs appearing is very high.

**Comment by lanrengm** [comment] 2024-10-19 06:54
```js
m = new Map([
	[1,2],
	[3,4]
]);
iter = m.entries();
```

I tried it again just now, copying the code above, right-clicking and pasting it into the VSCode Command Prompt, and the error immediately appeared.

The brackets of the second statement appeared before the output of the first statement.

VSCode CMD:

![Image](https://github.com/user-attachments/assets/e180a727-2b74-4e99-9f52-bffa012e0628)

VSCode PowerShell:

![Image](https://github.com/user-attachments/assets/c1c92211-f376-4ea5-b85c-cf7e715d9998)

Apparently it's not cmd , ps and node 's fault, because no matter how many times I try, they are all normal in the OS:

System CMD:

![Image](https://github.com/user-attachments/assets/072d5e09-78fd-4c48-9142-4bcb67abdd29)

System PowerShell

![Image](https://github.com/user-attachments/assets/bc0f737a-7d4d-4f65-a853-023650b6bd3e)

**Comment by Tyriar** [comment] 2024-12-11 20:38
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-11 20:38 UTC
Labels: terminal-input
