### ISSUE TITLE
Extensions install from marketplace copy item - prompt or install automatically

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#24113] opened 2017-04-06 17:47 UTC
All versions \ OS

When user selects an extension from marketplace and copies install link, does Control+P, Paste, Enter
the extension tops the list in the sidebar and the user has to go through the install and restart.

Since the user already knows the extension and the intent to install it, why not do it automatically?
or at least add an option to allow this. Right now with the new list widget. it actually takes many
keystrokes and tab stops to install the extension (partially a problem of having to tab stop
back to the selected item to access the install button (going to post an improvement on that as well)

Suggested solutions:
- if the user pastes marketplace install link , install and prompt for restart
- same as above but prompt for install/restart
- add flag -f as example to force install immediately
- add user setting eg: always install on marketplace link command

**Comment by joaomoreno** [comment] 2017-04-07 07:26
Duplicate of #20289. This issue intends to just have a click-to-install link in the Marketplace itself.

**Closed by joaomoreno** 2017-04-07 07:26 UTC
Labels: feature-request
