### ISSUE TITLE
Navigation does not work for typing (not in search box) in folder explorer view 

### ISSUE THREAD

**Issue by akrohit** [Microsoft/vscode#17386] opened 2016-12-16 10:07 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|0.2.14|
|python|donjayamanne|0.5.0|
|xml|DotJoshJohnson|1.6.0|
|tslint|eg2|0.7.1|
|Theme-GitHubCleanWhite|gerane|0.0.2|
|beautify|HookyQR|0.6.2|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-fsharp|Ionide|2.13.2|
|Ionide-Paket|Ionide|1.4.0|
|Go|lukehoban|0.6.51|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.4.0|
|java|redhat|0.0.7|
|vscode-icons|robertohuertasm|4.1.0|
|yo|samverschueren|0.9.1|
|Spell|seanmcbreen|0.9.1|
|code-settings-sync|Shan|2.3.8|
|vim|vscodevim|0.4.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Open any folder in VS code
2. In the File explorer, type any first few characters of folder name. (not in the search box).

Issue:
1. Navigation does not work for typing in folder explorer view

Expectation:
1. It should work as FileExplorer handle the input. Typing few character should navigate to the folder. This would really help a lot.

**Comment by kieferrm** [comment] 2016-12-17 15:05
Duplicate of #10026.

**Closed by kieferrm** 2016-12-17 15:05 UTC
