### ISSUE TITLE
none-html tag show in suggestion list as emmet abbr

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#160111] opened 2022-09-05 16:13 UTC
In jsx:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/188487352-47f354bb-e737-4bc0-a373-d09fa86829ae.png">

In html:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/188487463-640dbc2f-d5f5-4338-94b6-5cb94e3eeeae.png">

Expected behavior:

jsx should behavior like in html.

```
Version: 1.72.0-insider (Universal)
Commit: d17726fe4beae5abe87ba9e9429cd298be8b53c4
Date: 2022-09-05T05:18:52.074Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

**Comment by rzhao271** [comment] 2022-09-06 17:42
Duplicate of https://github.com/microsoft/vscode/issues/51537

**Closed by rzhao271** 2022-09-06 17:42 UTC
