### ISSUE TITLE
enhanced proxy support => more flexible getRemoteServerRootPath()

### ISSUE THREAD

**Issue by jhgoebbert** [microsoft/vscode#153679] opened 2022-06-29 12:30 UTC
**Introduction**
The newly introduced possibility of https://github.com/microsoft/vscode/pull/147311 and https://github.com/microsoft/vscode/pull/148707 allow VSCode to respect the full-path of its URL if it matches the pattern `https//<myserver>/<quality>-<commit>/`. One server can now serve multiple versions of VSCode - that is great!

**Feature request**
This would get an even broader use-case if the function [getRemoteServerRootPath()](https://github.com/microsoft/vscode/blob/main/src/vs/platform/remote/common/remoteHosts.ts#L34) could also allow to be less fixed to a specific pattern and instead **just return the full url root-path** as it is known from the current url.

**Use-Case**
We would like to run VSCode behind a configurable-http-proxy ([JupyterHub](https://jupyterhub.readthedocs.io/en/stable/)) in combination with the [jupyter-server-proxy](https://jupyter-server-proxy.readthedocs.io) + [plugin](https://github.com/FZJ-JSC/jupyter-openvscodeserver-proxy) which allows to proxy arbitrary local ports (like localhost:3000) to an extended URL of the running JupyterLab session.

With a logged in user a common URL to access VSCode/OpenVSCode running on localhost:3000 would for example look like this
`https://jupyter-jsc-staging.fz-juelich.de/user/j.goebbert.fz-juelich.de/de47c0193b364c36b9da34e681f14911/openvscodeserver`
which depends on the user-id and some hash and therefore changes with every new login & user.

Hence, in this example the function [getRemoteServerRootPath()](https://github.com/microsoft/vscode/blob/main/src/vs/platform/remote/common/remoteHosts.ts#L34) would need to return `/user/j.goebbert.fz-juelich.de/de47c0193b364c36b9da34e681f14911/openvscodeserver` to make the full setup work fine.

![image](https://user-images.githubusercontent.com/9266792/176434786-148fe0f8-72be-44da-8007-b0fbf29e7da0.png)

**Links**
To some extend this is linked to the issue https://github.com/gitpod-io/openvscode-server/issues/320

**Comment by jhgoebbert** [comment] 2022-06-29 12:32
These are the errors from the current VSCode version:
![image](https://user-images.githubusercontent.com/9266792/176436869-774263ed-cce7-46fb-9aa4-9f2f9e4aa26d.png)
The root path (yellow marked) is simply not respected (red underlines)

**Comment by eware-godaddy** [comment] 2022-08-05 05:26
I'm also having this exact issue, and would like to run this behind a jupyterhub proxy.

**Comment by kathoef** [comment] 2022-09-27 09:50
Just briefly citing my related comment from https://github.com/gitpod-io/openvscode-server/issues/320 below.

> I also stumbled across this problem... maybe one should mention that there is also a Visual Studio Code distribution [code-server](https://github.com/coder/code-server), which has [patches applied](https://github.com/coder/code-server/blob/3264187419abc0e3c6c1519af55223be5702c9e8/patches/base-path.diff) (see also [these search results](https://github.com/coder/code-server/search?q=baseUrl)) that make Visual Studio Code accessible on arbitrary base URLs, i.e. behind reverse proxies such as [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy). I think, I will be using that one for now.

**Comment by aeschli** [comment] 2022-11-04 08:52
duplicate of https://github.com/microsoft/vscode/issues/165391

**Closed by aeschli** 2022-11-04 08:52 UTC
