### ISSUE TITLE
"editor.wordWrap": "off" does not work 

### ISSUE THREAD

**Issue by skaegi** [Microsoft/vscode#21801] opened 2017-03-02 16:43 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.3.0|;

---

Steps to Reproduce:

1. Open a file with very long lines
2. No matter what editor.wordWrap is in your settings the line wraps at your viewport

This makes it basically impossible to work with some files. This worked in 1.10.0 so is a regression

**Comment by Tekbr** [comment] 2017-03-02 17:05
- VSCode Version: Code 1.10.1(653f873) and 1.11.0-insider (0bc62d1)
- OS Version: Windows 10

I have the same problem.

![wordwrap](https://cloud.githubusercontent.com/assets/19866231/23518007/d3fc534e-ff50-11e6-868a-d5aa5dfae3ad.gif)


It looks like the same is not updating the settings file.

![wordwrap2](https://cloud.githubusercontent.com/assets/19866231/23518011/d64715f8-ff50-11e6-84c4-4d44020899de.gif)

**Comment by xavadu** [comment] 2017-03-07 09:34
no working for me as well with (running in Ubuntu 16.04), it stop to work in the latest update when the name of the wrap preference was changed and have to set "off" instead of -1 :

```
Version 1.10.1
Commit 653f8733dd5a5c43d66d7168b4701f94d72b62e5
Date 2017-03-02T00:47:58.633Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

**Comment by alexandrudima** [comment] 2017-03-07 15:02
Related: #21552

As a guard against freezes (caused by our non being able to virtualize horizontally), we try to identify "minified" files. (i.e. think minified CSS, minified JS, etc.). We forcefully word wrap minified files.

On the insiders channel, the Toggle Word Wrap Action is able to unwrap these files. There is also an undocumented `"editor.wordWrapMinified": false` setting that works for now on the insiders channel.

We need to think how to better align the two desires:
* first, our desire to not "freeze" while rendering huge lines
* secondly, the end-user desire to never wrap

**Comment by xavadu** [comment] 2017-03-10 11:08
Thanks for the explanation and the undocumented solution, but for me `"editor.wordWrapMinified": false` is not working anyway (and it is marked as a unknown configuration setting)

**Closed** 2017-03-27 21:31 UTC
Labels: bug, editor-wrapping

**Comment by alexandrudima** [comment] 2017-03-27 21:33
* bumped up the minified line limit to 10k chars, so a file will be identified as minified if more than 50% of its characters lie on lines longer than 10k chars.
* added a primary editor action that shows up in this case:
![image](https://cloud.githubusercontent.com/assets/5047891/24379077/be0ecea0-1345-11e7-90fb-cdd3b069c4c4.png)

**Comment by michelkaporin** [comment] 2017-03-29 09:38
@alexandrudima the button is there and it does its work. However there are some wrong things going on, thus not putting 'verified' now.

1. UI does not allow to enable wrapping again through the same button (we've discussed it during the meeting, so I assume it's on your to-do list). Also, Ctrl+Z does not work for me to wrap it back (this should be current way to do it, as you said during discussion). Maybe it's because I've tested with very long minified file (https://code.jquery.com/jquery-3.2.0.min.js)

2. If I have two minified files opened in my editor, and disable word-wrapping for one of them, the second one also automatically unwraps.

**Comment by alexandrudima** [comment] 2017-03-29 12:23
@michelkaporin 

1. Yes, the button disappears, I create a separate item to make the button "stick around" (#23562). Ctrl+Z is undo and would undo the edits on a buffer (i.e. would not undo the toggle word wrap).

2. Created #23561

**Comment by isidorn** [comment] 2017-03-30 13:21
Adding verified since @michelkaporin tested and the flows found alex extracted into seperate issues

**Comment by Tekbr** [comment] 2017-03-30 19:54
-- Sorry for the English, I used Google Translator --

@alexandrudima  @isidorn  @michelkaporin If I understood correctly, when I use <kbd>Alt</kbd> +<kbd> Z</kbd>, does it only have effects for the file I'm open and not for the whole editor, as it did before? It is?

Sorry, but I think that's a regression.

Maybe another shortcut to just wordwrap this file.

I still prefer that <kbd>Alt</kbd> + <kbd>Z</kbd> affect the whole editor (on or off) rather than a single file.

**Comment by Download** [comment] 2017-04-12 08:37
> This makes it basically impossible to work with some files. This worked in 1.10.0 so is a regression

Suffering from this  :(

I was just really getting into VSCode because (after some getting used to it) I was loving it's multi-line editing features and was using them to edit SQL.

Now with latest release (just updated it again hoping it was solved) there is no way I can get it to work anymore in some projects.... I can't figure out why but at some point the editor just starts wrapping and there is no way to make it stop. I spend **hours** trying all combinations of settings just to get it to stop the wrapping but the only way I found that will work for a while is creating an entirely new project  :(

For me this breaks VSCode so bad I had to stop using it and switch back to Notepad++

It says here this issue is closed but why am I still seeing it?
