### ISSUE TITLE
Make lines matching pattern folded by default

### ISSUE THREAD

**Issue by emattias** [Microsoft/vscode#72086] opened 2019-04-10 15:31 UTC
I would like for vscode to fold lines that contain executions of a certain function (in my example the function `css` or maybe the logic can be: lines  that match the pattern `css({`. The pattern/functions can be set manually in vscode settings).

So for example for this React component:

```jsx
import { css } from 'emotion';

function MyReactComponent() {
  return (
    <div
      className={css({
        background: 'green',
        color: 'white',
        borderRadius: 2,
        minWidth: 10,
        minHeight: 10,
        lineHeight: '10px',
        alignContent: 'center',
        justifyContent: 'center',
        display: 'inline-flex',
        marginRight: 5,
      })}
    />
  );
}
```

I would like the line containing the execution of the `css` function to be folded by default, so that it would look something like:

```jsx
import { css } from 'emotion';

function MyReactComponent() {
  return (
    <div
      className={css({...})}
    />
  );
}
```

**Comment by Gama11** [comment] 2019-04-10 15:35
Seems like functioanlity an extension could provide if there was an API to expand/collapse specific folding regions programatically (which seems is not possible atm https://github.com/Microsoft/vscode/issues/45393#issuecomment-373956113). There's quite a few other use cases for that as well, for instance hiding the imports and/or license headers of files by default.

**Comment by aeschli** [comment] 2019-04-11 10:12
duplicate of https://github.com/Microsoft/vscode/issues/40338

**Closed by aeschli** 2019-04-11 10:12 UTC
Labels: editor-folding
