### ISSUE TITLE
Multi-repo workspace breaks when adding a top-level repo

### ISSUE THREAD

**Issue by CobusKruger** [Microsoft/vscode#73221] opened 2019-05-03 10:02 UTC
Issue Type: <b>Bug</b>

I have a multi-project workspace.  The folder structure looks like this:

```
MainProject
|-Deployment
|  |-Database *
|  |-Services *
|-Framework
|  |-core *
|  |-components *
```
And so on. In this structure, all the folders marked with an asterisk have their own repo.

Initially I added each repo to the workspace file and I could then see a list of repos on my Git panel, each with changes listed etc. Perfect!

Then I added the workspace file itself to source control. Since it is located in MainProject (and there were a few other files I needed to add), I initialized a new repo in MainProject.

Now I only see the repo in MainProject and all the others are simply not shown at all. The workspace folders still look like they did, but the Git panel only knows about the top-level repo.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (3.08GB free)|
|Process Argv|C:\Dev\src\Citazen\Citazen.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
ng-template|Ang|0.1.11
vscode-combine-scripts|Bat|2.0.3
githistory|don|0.4.6
gitlens|eam|9.6.3
Angular-BeastCode|Mik|8.0.6
azure-pipelines|ms-|1.147.2
vscode-azureappservice|ms-|0.14.0
vscode-azurefunctions|ms-|0.17.0
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.2
mssql|ms-|1.6.0
azure-account|ms-|0.8.2
azurecli|ms-|0.4.5
Go|ms-|0.10.2
powershell|ms-|1.12.1
vscode-node-azure-pack|ms-|0.0.6
vscode-typescript-tslint-plugin|ms-|1.0.0
wordcount|ms-|0.1.0
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.6.0
debugger-for-chrome|msj|4.11.3
angular-console|nrw|7.4.19
vscode-docker|Pet|0.6.1
azure-iot-toolkit|vsc|2.6.0

</details>

**Comment by gjsjohnmurray** [comment] 2019-05-03 10:52
Possible duplicate of #67252

**Closed** 2019-05-06 09:46 UTC
Labels: git
