### ISSUE TITLE
"cls" command only clears visible area of the integrated terminal

### ISSUE THREAD

**Issue by sajibsrs** [Microsoft/vscode#10636] opened 2016-08-17 21:59 UTC
- VSCode Version: 1.4
- OS Version: Win 10 x64

Steps to Reproduce:

"cls" (clear screen command) only clears the visible are of the integrated terminal not everything from the beginning. If you scroll up you can still see previous executed commands.

**Comment by Tyriar** [comment] 2016-08-18 07:21
Duplicate of https://github.com/sourcelair/xterm.js/issues/106

**Closed by Tyriar** 2016-08-18 07:21 UTC
