### ISSUE TITLE
"The Typescript language service died" running on a network drive through Linux smb

### ISSUE THREAD

**Issue by ole1986** [Microsoft/vscode#4232] opened 2016-03-15 07:39 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

(does not need a step or maybe when opening a JS file)

Receiving "Warn: The Typescript language service died unexpectedly 5 time in the last 5 Minutes. Please consider to open a bug report." ... and it does not stop showing me the popup.

![vscode-bug-typescript-died](https://cloud.githubusercontent.com/assets/4850116/13770719/5130332c-ea89-11e5-9690-e7df6f5301a3.PNG)

**Comment by egamma** [comment] 2016-03-15 08:12
@ole1986 can you please check whether this the same setup as in this issue: https://github.com/Microsoft/vscode/issues/3860?

**Comment by ole1986** [comment] 2016-03-15 09:20
strange thing is after I fully rebooted the system it is gone (until now)

**Comment by egamma** [comment] 2016-03-15 13:05
Is your workspace very large and has lots of .js files?

**Comment by ole1986** [comment] 2016-03-15 13:52
Actually not! I just added one new js file via the "New File" button...and it was empty.. then the warning appeared. After adding some text it still pops up. So I restarted the whole machine.. Than it was gone.

**Comment by egamma** [comment] 2016-03-15 15:15
Is the workspace on a sharepoint/webdav mounted volume as in #3860?

**Comment by ole1986** [comment] 2016-03-15 17:15
No, but on a network drive through Linux smb

**Comment by egamma** [comment] 2016-03-16 13:33
If the same setup works on a local folder, then this looks like the node issue described here https://github.com/Microsoft/vscode/issues/3860#issuecomment-194963793

**Comment by waderyan** [comment] 2016-12-09 23:15
@ole1986 are you still seeing a similar issue today? Closing this assuming its fixed in later versions. If the problem is persisting then please ping me and I'll reopen.

**Closed by waderyan** 2016-12-09 23:15 UTC
Labels: javascript

**Comment by jpalo** [comment] 2017-01-24 09:15
I'm still getting this on SharePoint WebDAV. Strange thing is that server.log is pretty much empty, and there is new ti* log file being generated on each time error message reappears at the top in VSCode (once every few seconds).

[Log](https://1drv.ms/u/s!AiTYXZ3f7ZUni4cjvx5rIfBGjpomkw)
