### ISSUE TITLE
Cannot split editor from markdown preview

### ISSUE THREAD

**Issue by Ludonope** [Microsoft/vscode#50975] opened 2018-06-01 21:53 UTC
- VSCode Version: 1.23.1
- OS Version: Arch Linux 4.16.12

VSCode allow to split the screen by dragging a tab on one side of the editor. When doing so with a Markdown Preview tab, it doesn't work.

Steps to Reproduce:

1. Open a folder with VSCode
2. Create a dummy markdown file
3. Set the language mode as `Markdown`
4. Save the file
5. Right click the file in the explorer and select `Open Preview`
6. Grab the Preview tab and move it on the left or right side to split the screen, but nothing will happen.
7. However if you do the same with the dummy markdown file, it will work

Does this issue occur when all extensions are disabled?: Yes (this is a fresh new install)

**Comment by mjbvz** [comment] 2018-06-01 22:02
duplicate of #25854

**Closed by mjbvz** 2018-06-01 22:02 UTC
Labels: markdown
