### ISSUE TITLE
Drag and drop Notebook cells broken

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#119657] opened 2021-03-23 17:30 UTC
- VS Code Version: 1.55.0-insider
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Create a new Jupyter Notebook
2. Insert a new Markdown cell 
3. Set some text in the Markdown cell
4. Try to drag the Markdown cell to be above the default code cell already there

The first half of this gif shows how trying to drag another Markdown cell seems to "fix" the problem and the second half shows the bug:
![recording (21)](https://user-images.githubusercontent.com/12758612/112190842-9d113900-8bc2-11eb-99ba-c47fb79ea24a.gif)

**Comment by rebornix** [comment] 2021-03-24 02:01
@tanhakabir can you try if you can reproduce with explicit setting `"notebook.experimental.useMarkdownRenderer": false`?

**Comment by rebornix** [comment] 2021-03-24 02:03
actually /duplicate of https://github.com/microsoft/vscode/issues/119604

**Closed by rebornix** 2021-03-24 02:03 UTC
Labels: bug, notebook
