### ISSUE TITLE
Sort order in file explorer is strange

### ISSUE THREAD

**Issue by Stone-Zeng** [Microsoft/vscode#51434] opened 2018-06-08 08:47 UTC
- VSCode Version: 1.24.0
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. Open a folder with some files. Their names are

```
uni034.glyph
uni035.glyph
uni33C.glyph
uni33D.glyph
uni35C.glyph
```
2. Set the option `"explorer.sortOrder"` to be `"default"` in workspace settings.

3. Then we can see that

![image](https://user-images.githubusercontent.com/18233088/41148238-1049a37c-6b3b-11e8-8066-65f2b0312a1f.png)

They are not sorted in the *natural* order as shown above, and it seems that `0` in file names is ignored.

I notice that ubuntu will sort the file as the same order here, but I don't know whether they are related:

![image](https://user-images.githubusercontent.com/18233088/41148400-7cd3f89e-6b3b-11e8-8859-c1e445496e63.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2018-06-08 13:28
Closing as duplicate of #27286

**Closed by isidorn** 2018-06-08 13:28 UTC
Labels: new release
