### ISSUE TITLE
Russian keyboard layout: hotkeys don't work

### ISSUE THREAD

**Issue by ws-fegon** [Microsoft/vscode#24194] opened 2017-04-07 08:58 UTC
Can't use some shortcuts while system keyboard layout is not english

- VSCode Version: 1.11.1
- OS Version: 10.12.4

Steps to Reproduce:

1. change system keyboard language to Russian (for example)
2. use any hotkeys (for example `"key": "cmd+S"`) and you can't save document while you not change shortcut in keybinding.json `"key": "cmd+[KeyS]"`
![2017-04-07 11 52 45](https://cloud.githubusercontent.com/assets/6111214/24792965/c4c1fc04-1b88-11e7-9ec7-4172131b5bf9.png)

**Comment by alexandrudima** [comment] 2017-04-10 16:38
Duplicate of #24057 (i.e. just checked that the fix for Linux covers the OSX case as well)

**Closed by alexandrudima** 2017-04-10 16:38 UTC
Labels: candidate, important, keybindings, keyboard-layout, mac
