### ISSUE TITLE
Default paste into Markdown from OneNote is image

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#181882] opened 2023-05-09 12:39 UTC
Copy pasting regular text from a OneNote page now pastes an image:

https://github.com/microsoft/vscode/assets/22350/d62dbcf2-c479-4e9e-9df8-f3b7f42f1312

I only found a way out of this by completely disabling the feature with `editor.pasteAs.enabled` set to `false`.

Should we provide user-level defaults (ie "always prefer text")?

**Comment by mjbvz** [comment] 2023-05-09 18:23
Duplicate of #181886

**Closed by mjbvz** 2023-05-09 18:23 UTC
