### ISSUE TITLE
Go to definition broken in latest version of VS Code (1.5) + older TypeScript

### ISSUE THREAD

**Issue by DavidRigglemanININ** [Microsoft/vscode#11766] opened 2016-09-09 12:15 UTC
- VSCode Version: 1.5
- OS Version: OS X Yosemite

Steps to Reproduce:
1. Open up project
2. Click the cursor over a method
3. Click F12 to try to go to definition and nothing happens
4. Switch to using VS Code 1.4 and repeat steps 1-3 and everything works as expected

This feels like a really bad bug as it makes the latest version of VS Code pretty much unusable for me unless there is some workaround that I'm not aware of. Also, it would be nice if there was an official download source to downgrade to a prior version. Fortunately, I found one in my trash this time, but I will definitely be disabling auto update because of this for future releases.

**Comment by joebehymer** [comment] 2016-09-09 14:35
I'm a team member of Davids.  We're still using TS 1.6.  If we select to use 1.6 at the popup during start, we get no code completion/navigation.  If we select to use 1.8 everything works.

**Comment by ramya-rao-a** [comment] 2016-09-09 18:55
@waderyan Do you know if we support back compat for typescript versions?

**Comment by waderyan** [comment] 2016-09-09 19:01
hey @DavidRigglemanININ thank you for opening this issue. 

I broke off your other request into its own issue - https://github.com/Microsoft/vscode/issues/11796

This issue falls into TypeScript language service, so I will migrate to them.

**Comment by waderyan** [comment] 2016-09-09 19:02
@ramya-rao-a yes you can use different TypeScript versions. See docs [here](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions).

**Comment by waderyan** [comment] 2016-09-09 19:02
This issue was moved to Microsoft/TypeScript#10821

**Comment by waderyan** [comment] 2016-09-12 20:46
@dbaeumer this is the issue we have discussed over mail. I have recreated the issue using TS 1.6.0-dev.20150825. 

Code is as follows. 

Person.ts

```typescript
class Person {

    constructor(private name: string) {}
}

export default Person;
```

test.ts

```typescript
import * as p from './Person';
```

When using TS 1.8 and above I can do Go To Definition by right clicking on `p` in `test.ts`.

**Comment by tdekoekkoek** [comment] 2016-09-15 18:13
this version feels very broken to me.  No more for loop code completion.  no Command-e.  Command-p find shows too many results.  How do I go back a version?

**Comment by chrmarti** [comment] 2016-09-16 17:15
@tdekoekkoek Could you open a separate issue for cmd+p showing too many results? (The [announcement](http://code.visualstudio.com/updates/July_2016) for 1.4 has links near the top to the 1.4 downloads if you want to go back to that.)

**Comment by SamiSammour** [comment] 2016-09-16 18:24
This one bad version of vs code, I will go back to 1.4.
This problem occurred also in JavaScript.
Current status: looking for an alternative editor.

**Comment by dbaeumer** [comment] 2016-09-27 12:35
I tested this under VS Code 1.4 and 1.6.0-dev.20150825 doesn't work there either. None of the requests send to the tsserver return. So there is something seriously broken with that version of TS. 

@DavidRigglemanININ @joebehymer in 1.5.x we added behavior that asks you whether you want to use the local TS version in our workspace instead of the bundled one. Could it be that with < 1.5.0 you always used the bundled version (which was 1.8.10) and only in your external tools used 1.6.0. This would explain why it stopped working with 1.5.x.

**Comment by DavidRigglemanININ** [comment] 2016-09-29 11:58
So somehow things seem to be working again on 1.5.3. Maybe somewhere along the line I told VS Code to use 1.8 by accident (or rather omitted one click to keep using 1.6). If there's any I can do to verify versions, let me know. I guess the above scenario you mentioned could be a possible explanation. It doesn't look like we 1.6 hardcoded in the settings.json file, just in our package.json config

**Comment by dbaeumer** [comment] 2016-09-29 12:14
This explains it then. If you don't have typescript.tsdk in the settings.json pointing to the local 1.6 TS then VS Code always used 1.8.10 for code complete, error checking, ...

@DavidRigglemanININ please be aware that VS Code 1.6 will ship with TS 2.0.3 in the box. So you might see additional errors since the compiler got more precise. If you need to go back to 1.8.10 then you can install 1.8.10 on your machine (must not be in the workspace to not conflict with 1.6 TS) and use typescript.tsdk to point to the 1.8.10 version

I will close the issue.

**Closed by dbaeumer** 2016-09-29 12:14 UTC
Labels: typescript

**Comment by tdekoekkoek** [comment] 2016-09-29 13:02
I'm really not sure this should be closed.  What I had was a working version of VSCode and then it does an automatic update which I didn't ask for and then is no longer working.  Should I have to go hunting down which version of typescript is running or change a setting in a config file I've never touched before?  Shouldn't there be some warning?  All I know right now is that prior versions of VSCode worked better than my current version and also standard shortcuts that I have been used to using like Command+E disappeared.

**Comment by dbaeumer** [comment] 2016-10-03 09:35
@tdekoekkoek your issue is very likely not cause by a dev version of a TSServer. Can you please open a separate issue with steps to reproduce them. Mixing problems in one issue is always very complicated since it will lead to the fact that we never can close an issue :-)

**Comment by DavidRigglemanININ** [comment] 2016-10-03 12:07
I'm not sure that the point made by @tdekoekkoek isn't valid. The symptoms are exactly the same issue I had and I agree with his point. On an upgrade, things should just work and existing behavior should not be broken. If some new prompt to select a TS version is added, and choosing one option breaks functionality, then that needs to be made much more obvious to the end user (like a warning as mentioned). Also, I'm a little unclear on where use of the dev version of TSServer comes in. Prior to my upgrade to VS Code 1.5, I was using TS 1.6.2. Did the new version of VS Code somehow bundle the dev version of 1.6 and then present it as an option to the end user? That doesn't feel right? Also, given we didn't even have the config file point to to 1.6 (typescript.tsdk was set to null), how did VSCode even know to suggest that. Does it look at the package.json file, where we do have TS 1.6.2 specified.

**Comment by dbaeumer** [comment] 2016-10-04 10:38
@tdekoekkoek complained about several things containing Command e and Command p not working. These two are not powered by TypeScript and therefore a different version of the TS compiler can hardly break them. We do take is problems serious so. That is why I ask him to file a separate issue.

Regarding your specific issue: yes we do look into the node_modules folder now to see if we can find an installed TypeScript. If this is different from the one we bundle then we show the message. 

In the past we didn't which confused a lot of people. They for example install TypeScript in their workspace or even got the version to use via a generator (e.g. for example Angular) however we didn't honor that. We decided against automatically using the one out of the workspace since it might cause a different set of problems. 

So prior to the upgrade you used TypeScript 1.8.10 but I guess you were assuming you used 1.6-dev-xxx. When you decided to use 1.6-dev things stopped to work since that version of the tsserver isn't functional at all (it doesn't work with 1.4.x either).

I see your point but all I can think of improving this is to make it more clear in the message which version you used before. Would it helped if we would told you that you used 1.8.10 before? 

In general I think making you aware of this 'misconfiguration' is the right thing to do. And in your specific example choosing 1.8.10 would have kept you in your 'previous' state in which everything worked.
