### ISSUE TITLE
Improve Latex parsing by Katex in VSCode

### ISSUE THREAD

**Issue by ajunanka** [microsoft/vscode#168496] opened 2022-12-08 18:27 UTC
I'd like to reopen [this issue](https://github.com/microsoft/vscode/issues/135261). I have a Jupyter Notebook with some markdown cells that have Latex commands inside. I discovered that some Latex commands cannot be rendered. 

The following code will fail to render the equation properly using Jupyter notebooks in VSCode:
```

<a name="3.5"></a>
### 3.5 Gradient for regularized logistic regression

In this section, you will implement the gradient for regularized logistic regression.


The gradient of the regularized cost function has two components. The first, $\frac{\partial J(\mathbf{w},b)}{\partial b}$ is a scalar, the other is a vector with the same shape as the parameters $\mathbf{w}$, where the $j^\mathrm{th}$ element is defined as follows:

$$\frac{\partial J(\mathbf{w},b)}{\partial b} = \frac{1}{m}  \sum_{i=0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)})  $$

$$\frac{\partial J(\mathbf{w},b)}{\partial w_j} = \left( \frac{1}{m}  \sum_{i=0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)}) x_j^{(i)} \right) + \frac{\lambda}{m} w_j  \quad\, \mbox{for $j=0...(n-1)$}$$
```

The error: 
![image](https://user-images.githubusercontent.com/9882162/206536133-596d9c97-4b05-4b67-97c0-19d35eb73331.png)

**Comment by mjbvz** [comment] 2022-12-08 19:20
Duplicate of #135261

Also see https://github.com/KaTeX/KaTeX/issues/2050

**Closed by mjbvz** 2022-12-08 19:20 UTC
