### ISSUE TITLE
Markdowns overlap the side panes when a terminal is maximized

### ISSUE THREAD

**Issue by sadjadanzabizadeh** [microsoft/vscode#129185] opened 2021-07-22 13:18 UTC
Issue Type: <b>Bug</b>

When maximizing a terminal window, if a Jupyter notebook is open, the markdown cells are rendered over the side panes (e.g. explorer pane) and you cannot click on the panes, as well.

**Normal layout**
![image](https://user-images.githubusercontent.com/32469424/126644979-2d93d87c-7910-4690-ab4f-85013e6c6817.png)

**When terminal is maximized**
![image](https://user-images.githubusercontent.com/32469424/126645150-0bd991ae-0139-4244-a95c-572b5d12624b.png)

Extension version: 2021.8.1054968649
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.78GB free)|
|Process Argv|--crash-reporter-id 97601edd-e8a3-474e-811e-0dfa1d806a13|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306cf:30340756
bridge0708:30335490

```

</details>

**Comment by jeanp413** [comment] 2021-07-22 22:05
duplicate of #128491

**Closed** 2021-07-27 01:21 UTC
