### ISSUE TITLE
Multiline Snippets are non-functional

### ISSUE THREAD

**Issue by mpearon** [Microsoft/vscode#26491] opened 2017-05-11 20:41 UTC
- VSCode Version:  **1.12.1**
- OS Version:  **Windows 10 v1607 build 14393.1066**

Until just recently (last update?), multiline snippets were useable, but now that appears to not be the case.  Here is an example of a broken snippet that previously worked:

```
     "Author Comment": {
		"prefix": "Author",
		"body": [
			"<#",
			"	Author:		${Author:Matthew A. Pearon}",
			"	Date:		${Date:yyyy-MM-dd HH:mm}",
			"	Keywords:	${Keywords:Keywords}",
			"	Parameters:	${Parameters:Parameters}",
			"#>"
		],
		"description": "Insert Author Comment Block"
	}
```

When used, it now just return this:
```
<#

,

```

I will be able to attach a gif to this post later.

**Comment by jrieken** [comment] 2017-05-12 07:10
dupe of https://github.com/Microsoft/vscode/issues/25938.

**Closed by jrieken** 2017-05-12 07:10 UTC
