### ISSUE TITLE
Git panel showing "Incoming/Outgoing" for repo which doesn't have any upstream

### ISSUE THREAD

**Issue by mercury233** [microsoft/vscode#224539] opened 2024-08-02 03:41 UTC
Type: <b>Bug</b>

I'm using git full locally on some folders, won't push or pull, so I don't want vscode to show "Incoming/Outgoing" on those folders.

1. `git init` on a new folder
2. Create 2 commits or more
3. Open this folder in vscode
4. Open the Source Control panel
5. There shouldn't show "Incoming/Outgoing", but it do.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
ccplc:31103425
pythonrstrctxtcf:31103194
wkspc-ranged-t:31107835

```

</details>

**Comment by lszomoru** [comment] 2024-08-02 10:04
@mercury233, thank you very much for the feedback. The behaviour that you are describing is by design since if your branch does not have a remote, the commits are being considered as "outgoing commits" and they are being shown in the history graph.

**Comment by anthonyvdotbe** [comment] 2024-08-06 18:09
Same here. I think #218263 could help: it would be great if I could disable the graph for "fully local repos", while having it enabled by default.

**Comment by lszomoru** [comment] 2024-12-20 16:31
Closing this issue as the "Incoming/Outgoing" section has been removed.

**Closed by lszomoru** 2024-12-20 16:31 UTC
Labels: scm, under-discussion
