### ISSUE TITLE
npm ci fails due to files being kept open by vscode

### ISSUE THREAD

**Issue by biltongza** [Microsoft/vscode#72535] opened 2019-04-18 08:40 UTC
Issue Type: <b>Bug</b>

I am working on an angular project, and whenever I need to run an `npm ci` to pull new packages added by my colleagues, I have to close vscode for the command to succeed because vscode keeps files in `node_modules` opened and locked, and part of the npm ci process is to remove the `node_modules` folder.
```
D:\git\PlatformWeb\ClientApp [qa ≡]> npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! path D:\git\PlatformWeb\ClientApp\node_modules\@angular-devkit\build-angular
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\git\PlatformWeb\ClientApp\node_modules\@angular-devkit\build-angular'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'D:\git\PlatformWeb\ClientApp\node_modules\@angular-devkit\build-angular']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\git\PlatformWeb\ClientApp\node_modules\@angular-devkit\build-angular'
npm ERR!      type: 'OperationalError',
npm ERR!      '$error': '$error',
npm ERR!      cause:
npm ERR!       { errno: -4048,
npm ERR!         code: 'EPERM',
npm ERR!         syscall: 'unlink',
npm ERR!         path:
npm ERR!          'D:\\git\\PlatformWeb\\ClientApp\\node_modules\\@angular-devkit\\build-angular' },
npm ERR!      isOperational: true,
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'D:\\git\\PlatformWeb\\ClientApp\\node_modules\\@angular-devkit\\build-angular' },
npm ERR!   isOperational: true,
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'D:\\git\\PlatformWeb\\ClientApp\\node_modules\\@angular-devkit\\build-angular\'',
npm ERR!   type: 'OperationalError',
npm ERR!   '$error': '$error',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'D:\\git\\PlatformWeb\\ClientApp\\node_modules\\@angular-devkit\\build-angular' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\logan.dam\AppData\Roaming\npm-cache\_logs\2019-04-18T08_32_23_715Z-debug.log
```

To be sure it isn't an extension (which I initially thought it was) I reloaded my window with extensions disabled and I experienced the same results.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (7.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

____________________
With extensions enabled:

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (7.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1.11
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
gitlens|eam|9.6.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
node-modules-navigation|geg|0.0.2
angular-cli-task-provider|Gen|1.3.2
angular2-switcher|inf|0.2.0
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
node-module-intellisense|lei|1.5.0
Angular-BeastCode|Mik|8.0.1
vscode-scss|mrm|0.6.2
azure-account|ms-|0.8.2
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.67
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
stylelint|shi|0.48.0
vscode-icons|vsc|8.5.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

</details>

**Comment by jalovatt** [comment] 2019-04-18 15:23
Experiencing the same issue. It's particularly fun when reviewing PRs for updated packages, as I have to restart VS Code for each one even if I haven't actually done anything or opened any files.

**Comment by mjbvz** [comment] 2019-04-18 17:33
duplicate of https://github.com/Microsoft/TypeScript/issues/29407

**Closed by mjbvz** 2019-04-18 17:33 UTC
