### ISSUE TITLE
Fonts are rendered with periodic subpixel blurring instead of being pixel-hinted

### ISSUE THREAD

**Issue by mitsukuri** [Microsoft/vscode#4622] opened 2016-03-23 17:53 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 7 x64 SP1

Initially I commented about it in #2043, but I guess it's worth opening a new issue.

Something is wrong with font rendering in VS Code, font widths seem to be fractional or hinting is not respected (I might be using the wrong term). Compare these renderings of the same string in Visual Studio 2015 and in VS Code:

![renderings](https://cloud.githubusercontent.com/assets/14021464/13882491/af7a64de-ed36-11e5-8628-93249701f326.png)
Notice how vertical elements periodically loose pixel hintning and become blurry and then sharp again, and that VS Code renders the sample string one pixel shorter than VS2015.

Steps to Reproduce:
1. Set some strongly hinted font (I use Envy Code R) in settings.json
2. Type any string long enough to see vertical lines of symbols becoming progressively blurrier.

**Comment by fitojb** [comment] 2016-03-24 16:35
Seems related to this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=534732

**Comment by balupton** [comment] 2017-03-03 03:21
possible dupe of #15181 ?

**Comment by balupton** [comment] 2017-03-03 03:47
also possible dupe of #1896

**Comment by balupton** [comment] 2017-03-03 03:52
Found a solution over at https://github.com/Microsoft/vscode/issues/1896#issuecomment-283858289

**Comment by bpasero** [comment] 2017-04-10 17:08
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by alexandrudima** [comment] 2017-11-24 14:37
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Closed by alexandrudima** 2017-11-24 14:37 UTC
Labels: electron, font-rendering, upstream
