### ISSUE TITLE
Hold for speech - releasing keys resets streaming

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#203298] opened 2024-01-24 09:36 UTC
Testing #203012
1. Press and hold `cmd+I`
2. Specify the instruction using voice but do not release `cmd+i` when you are done
3. Wait for the response to start streaming in
4. Release `cmd+I` and observe how streaming resets (0:12) in the video below

https://github.com/microsoft/vscode/assets/3372902/16c37d0b-b50f-4156-a0c9-b4f58c6b3c94

**Comment by jrieken** [comment] 2024-01-24 18:13
related/same as https://github.com/microsoft/vscode/issues/203189

**Comment by jrieken** [comment] 2024-01-25 10:51
actually /duplicate of https://github.com/microsoft/vscode/issues/203189

**Closed by jrieken** 2024-01-25 10:51 UTC
Labels: bug, inline-chat
