### ISSUE TITLE
Ctrl + C on blank lines

### ISSUE THREAD

**Issue by husseinalhammad** [Microsoft/vscode#55243] opened 2018-07-27 13:58 UTC
Hello,

I've initially asked about this on Twitter:
https://twitter.com/hus_hmd/status/1022176410973204480

Current default behaviour:

- (A) **Ctrl + C on a line with code (no text selection):** copies the whole line
- (B) **Ctrl + C on a blank line (no text selection):** copies the empty line

I would love to be able to do (A), but disable (B). 

The closest setting for this is `editor.emptySelectionClipboard`. Setting it to `false` disables (B), but prevents me from using (A) forcing me to select the whole line to copy it.

**Comment by husseinalhammad** [comment] 2018-09-21 09:06
Hello @ramya-rao-a 

I don't do it intentionally. Since the `C` and the `V` keys are next to each other (in QWERTY keyboards at least), every now and then when I attempt to paste something on a blank line I accidentally click `C` instead of `V` so whatever I initially have in my clipboard gets overwritten by a blank line.

**Comment by ramya-rao-a** [comment] 2018-09-21 17:15
Got it, thanks.

**Comment by usernamehw** [comment] 2018-09-23 11:41
An extension:  https://marketplace.visualstudio.com/items?itemName=usernamehw.do-not-copy-empty

@ramya-rao-a , can you unlock that issue: #11112, so I can put a link to the extension, since not everybody happy there and they basically want the same thing as described in this issue.

**Comment by ramya-rao-a** [comment] 2018-09-23 20:33
@usernamehw I don't believe the extension is the right solution for this problem when it can so easily be solved in the product itself.

I believe we can add this fix as a default. 

Would you like to send a PR?
- The fix would be in the [clipboard.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/clipboard/clipboard.ts) file
- If there is no selection and the line is empty, then we shouldn't copy to clipboard

**Comment by rebornix** [comment] 2018-09-23 20:40
thanks @ramya-rao-a  for the investigation and proposal, sounds good to me. Things to take care of carefully is lines with only leading whitespaces and multi cursors.

**Comment by usernamehw** [comment] 2018-09-23 20:40
IDK, similar issue got `out-of-scope` 5 days ago: #44221

If you will accept PR, then I can try.

**Comment by usernamehw** [comment] 2018-09-23 20:46
How should it work on a line with leading whitespaces/tabs?
```
    text
    |
    text
```

1. Do not copy
1. Copy

**Comment by usamedin** [comment] 2018-11-08 12:48
I would like to fix this this issue, how to i assigne this issue to me?

**Comment by ramya-rao-a** [comment] 2018-11-08 17:30
@usamedin There is already an open Pull Request addressing this issue, I would suggest to look for another issue to fix.

**Comment by usamedin** [comment] 2018-11-08 21:58
@ramya-rao-a thanks but then, the status shouldn't be OPEN.

**Comment by ramya-rao-a** [comment] 2018-11-08 22:21
The PR hasnt been merged yet, so the issue is open.

Perhaps, we can remove the help-wanted label, since the PR is already open.

**Closed** 2018-11-12 19:51 UTC
Labels: editor-clipboard, feature-request
