### ISSUE TITLE
Formatting code does not work for me anymore !

### ISSUE THREAD

**Issue by HamadaBrest** [Microsoft/vscode#37145] opened 2017-10-30 13:47 UTC
- VSCode Version: 1.17.2
- OS Version: Ubuntu 16

Formatting code does not work for me anymore !

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-10-30 17:22
What language? Can you please provide some steps to reproduce this issue

**Comment by HamadaBrest** [comment] 2017-10-31 09:32
@mjbvz Javascript, React JS .. Ctrl+Shift+i Doesn't work anymore, I tried it even manually, nothing happen

**Comment by mjbvz** [comment] 2017-11-01 00:05
So you have tried using the `Format Document` command, and that also doesn't work. If you disable all of your extensions and restart VS Code, do you still see this issue?

**Comment by HamadaBrest** [comment] 2017-11-01 10:19
I disabled all my extensions and restarted my computer, guess what, it works again :) thank you

**Comment by mjbvz** [comment] 2017-11-02 18:02
Ok. If you see this issue again, please try tracking down the extension that caused this and opening an issue against them

Closing as caused by extension

**Closed by mjbvz** 2017-11-02 18:02 UTC
Labels: caused-by-extension

**Comment by HamadaBrest** [comment] 2017-11-03 09:45
Copy that
