### ISSUE TITLE
Random prompts to turn sync off

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode#93891] opened 2020-03-31 11:40 UTC
Issue Type: <b>Bug</b>

For a while now, I keep getting (seemingly) random prompts to turn sync off. Hitting "Cancel" in the dialog takes me through the flow to enable sync again.

![image](https://user-images.githubusercontent.com/406937/78021956-6ceadd80-7354-11ea-8920-fbe33fc9ac8b.png)

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|-psn_0_7091907|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-browser-preview|auc|0.6.3
markdown-preview-github-styles|bie|0.1.6
LinkCheckMD|bla|0.3.1
better-toml|bun|0.3.2
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-npm-source|dku|1.0.0
binary-plist|dni|0.4.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
code-runner|for|0.9.17
vscode-pull-request-github|Git|0.15.0
rest-client|hum|0.23.2
customize-ui|ioc|0.1.34
monkey-patch|ioc|0.1.7
bats|jet|0.1.7
ReplaceWithNewline|jma|0.0.1
docthis|joe|0.7.1
vscode-peacock|joh|3.6.0
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.2
vscode-azureappservice|ms-|0.16.4
vscode-azurefunctions|ms-|0.21.0
vscode-azurestorage|ms-|0.9.0
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.15
vscode-edge-devtools|ms-|1.0.7
vscode-aks-tools|ms-|0.0.4
vscode-kubernetes-tools|ms-|1.1.1
python|ms-|2020.3.69010
remote-containers|ms-|0.109.0
remote-ssh-edit-nightly|ms-|2020.3.42660
remote-ssh-nightly|ms-|2020.3.42660
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
Go|ms-|0.13.1
powershell|ms-|2020.3.0
vscode-node-azure-pack|ms-|0.0.10
vscode-typescript-next|ms-|3.9.20200329
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1847
vsonline|ms-|1.0.1889
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.5
debugger-for-chrome|msj|4.12.6
color-highlight|nau|2.3.0
gremlins|nho|0.15.1
vscode-ts-markdown-to-playground|Ort|1.1.0
quicktype|qui|12.0.46
ruby|reb|0.27.0
vscode-yaml|red|0.7.2
vscode-sort-json|ric|1.18.0
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.8.0
code-spell-checker-german|str|0.1.4
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
gistfs|vsl|0.0.65
vscode-wakatime|Wak|4.0.0
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.27.0
material-theme|zhu|3.2.5

</details>

**Comment by jrieken** [comment] 2020-03-31 12:28
When auth failed on my linux box, than I saw the same

**Comment by lumaxis** [comment] 2020-03-31 12:45
I _think_ it might be due to 500 error responses? At least I saw logs related to that but wasn't able to establish a clear correlation.

**Comment by lumaxis** [comment] 2020-03-31 12:49
Related to that, the issue seems to appear in multiple of my VS Code windows but not all of them.

**Comment by RMacfarlane** [comment] 2020-04-01 17:01
Closing as a duplicate of https://github.com/microsoft/vscode/issues/94174 since there is more discussion there

**Closed by RMacfarlane** 2020-04-01 17:01 UTC
