### ISSUE TITLE
code . command not working in wsl environment

### ISSUE THREAD

**Issue by Mohtelsayed** [microsoft/vscode#228882] opened 2024-09-17 20:59 UTC
Type: <b>Bug</b>

Here is the output after running the command "VSCODE_WSL_DEBUG_INFO=true code .":
+ COMMIT=38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION:WT_PROFILE_ID:
+ wslpath -m /mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/mohte/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/mohte/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\mohte\.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.3
+ [ -n c:\Users\mohte\.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.3 ]
+ wslpath -u c:\Users\mohte\.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.3
+ WSL_CODE=/mnt/c/Users/mohte/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh
+ /mnt/c/Users/mohte/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 stable /mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code/Code.exe code .vscode-server .
+ [ -z .vscode-server ]
+ [ .vscode-server = .vscode-insiders ]
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/mtelsaye/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu ]
+ AUTHORITY=wsl+Ubuntu
+ dirname /mnt/c/Users/mohte/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh
+ /mnt/c/Users/mohte/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslDownload.sh 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 stable /home/mtelsaye/.vscode-server/bin
+ [ ! -d /home/mtelsaye/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 ]
+ RC=0
+ [ 0 -eq 100 ]
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.IP1asY
+ env
+ dirname /mnt/c/Users/mohte/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/c/Users/mohte/AppData/Local/Programs/Microsoft VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/mohte/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.IP1asY VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION:WT_PROFILE_ID: /home/mtelsaye/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/bin/remote-cli/code .
/mnt/c/Users/mohte/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh: 68: /home/mtelsaye/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/bin/remote-cli/code: not found
+ exit 127

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'WSL: Ubuntu' could not be established  VS Code Server for WSL closed unexpectedly.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.85GB free)|
|Process Argv|--crash-reporter-id c5f9e7d8-be74-4a0d-86a0-d23c7ec8483a|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu' could not be established  VS Code Server for WSL closed unexpectedly.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
fje88620:31121564

```

</details>

**Comment by devmuppet** [comment] 2024-09-20 08:13
![image](https://github.com/user-attachments/assets/4f45e800-86c4-41f5-837f-f6b3ed371a29)
![image](https://github.com/user-attachments/assets/4e02563a-9993-4a8f-a29f-151abcc7d124)
just tried manually pointing to the windows exe in my bash profile... i got prompted to then open in wsl and got the above errors :(

**Comment by devmuppet** [comment] 2024-09-20 08:47
ok managed to do a dirty workaround... 

seems theres 2 extension paths after the upgrade: 

C:\Users\user\.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.2 <-- empty
C:\Users\user\.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.2 <-- path but hasnt been picked up in the wslclient.sh script

so i just renamed the .3 folder to .2 and working again. 

Crap fix but im not bothering to edit the code if its going to be patched later

**Comment by devmuppet** [comment] 2024-09-20 09:35
seems to be a bug with the commit version of the server package? 

```
✘-INT SrcCodes:~/jenkins-casc [backups|✚ 1]> VSCODE_WSL_DEBUG_INFO=true code .
+ COMMIT=38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu5 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION:WT_PROFILE_ID:
+ wslpath -m /mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/doylea/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/doylea/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\doylea\.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.3
+ [ -n c:\Users\doylea\.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.3 ]
+ wslpath -u c:\Users\doylea\.vscode\extensions\ms-vscode-remote.remote-wsl-0.88.3
+ WSL_CODE=/mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh
+ /mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 stable /mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/Code.exe code .vscode-server .
+ [ -z .vscode-server ]
+ [ .vscode-server = .vscode-insiders ]
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/doylea/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu5 ]
+ AUTHORITY=wsl+Ubuntu5
+ dirname /mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh
+ /mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslDownload.sh 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 stable /home/doylea/.vscode-server/bin
+ [ ! -d /home/doylea/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 ]
+ RC=0
+ [ 0 -eq 100 ]
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.kVPrJx
+ env
+ dirname /mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu5 VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.kVPrJx VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION:WT_PROFILE_ID: /home/doylea/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/bin/remote-cli/code .
/mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts/wslCode.sh: 68: /home/doylea/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/bin/remote-cli/code: not found
+ exit 127
```

i extracted the following script args from the above output:

```
COMMIT=38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
QUALITY=stable
WIN_CODE_CMD=/mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/Code.exe
APP_NAME=code
SERVERDATAFOLDER=.vscode-server

```
and tried to see if i could run the scripts to see what was going on: 

```
doylea@SrcCodes:/mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts$ ./wslCode.sh 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 stable "/mnt/c/Users/doylea/AppData/Local/Programs/Microsoft VS Code/Code.exe" code .vscode-server
Updating VS Code Server to version 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Removing previous installation...
Installing VS Code Server for Linux x64 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40)
Downloading: 100%
Unpacking: 100%
Unpacked 1765 files and folders to /home/doylea/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.

doylea@SrcCodes:/mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts$ code .
doylea@SrcCodes:/mnt/c/Users/doylea/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.3/scripts$

```
Et voilà

@Mohtelsayed - this fixed code . in wsl for me. 

@roblourens - not sure where in the scripts thats happening but its a little workaround for now.

**Comment by rvalavi** [comment] 2024-10-04 02:09
The above approach didn't work for me! But the following did:
https://stackoverflow.com/questions/78557357/vs-code-remote-to-wsl-bin-code-server-not-found

Just simply remove or rename the `38c31bc77e0dd6ae88a4...` folder in `~/.vscode-server/bin/` then relaunch code. It will download the code server and and runs.

**Comment by opsarno** [comment] 2024-10-12 02:32
Same issue.

**VS Code Server for WSL closed unexpectedly. Check WSL terminal for more details.**

```bash
[2024-10-12 02:24:10.856] Extension version: 0.88.4
[2024-10-12 02:24:10.856] L10N bundle: none
[2024-10-12 02:24:10.897] authorityHierarchy: wsl+rockylinux
[2024-10-12 02:24:10.897] WSL extension activating for a local WSL instance
[2024-10-12 02:24:10.917] Resolving wsl+rockylinux, resolveAttempt: 1
[2024-10-12 02:24:10.917] NodeExecServer run: C:\WINDOWS\System32\wsl.exe --status
[2024-10-12 02:24:10.973] WSL feature installed: true (wsl --status)
[2024-10-12 02:24:10.974] NodeExecServer run: C:\WINDOWS\System32\wsl.exe --list --verbose
[2024-10-12 02:24:11.027] 3 distros found
[2024-10-12 02:24:11.028] Starting VS Code Server inside WSL (wsl2)
[2024-10-12 02:24:11.028] Windows build: 22631. Multi distro support: available. WSL path support: enabled
[2024-10-12 02:24:11.028] Scriptless setup: false
[2024-10-12 02:24:11.029] No shell environment set or found for current distro.
[2024-10-12 02:24:11.141] WSL daemon log file: 
[2024-10-12 02:24:11.144] Probing if server is already installed: if [ -d ~/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427 ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf 'alpine-'; fi; if [ -s ~/.vscode-server/bin/legacy-mode ]; then printf 'legacy-'; fi; uname -m;
[2024-10-12 02:24:11.144] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d RockyLinux -e sh -c if [ -d ~/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427 ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf 'alpine-'; fi; if [ -s ~/.vscode-server/bin/legacy-mode ]; then printf 'legacy-'; fi; uname -m;
[2024-10-12 02:24:11.265] Probing result: install-found x86_64
[2024-10-12 02:24:11.266] Server install found in WSL
[2024-10-12 02:24:11.266] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d RockyLinux sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 384ff7382de624fb94dbaf6da11977bba1ecd427 stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=1470669485-3535114544-1666293151-4283553120 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
[2024-10-12 02:24:11.440] Setting up server environment: Looking for /root/.vscode-server/server-env-setup. Not found.
[2024-10-12 02:24:11.440] WSL version: 5.15.153.1-microsoft-standard-WSL2 RockyLinux
[2024-10-12 02:24:11.440] WSL-shell-PID: 735
[2024-10-12 02:24:11.440] Node executable: /root/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/node
[2024-10-12 02:24:11.440] Starting server: /root/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/bin/code-server --host=127.0.0.1 --port=0 --connection-token=1470669485-3535114544-1666293151-4283553120 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all
[2024-10-12 02:24:11.442] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2024-10-12 02:24:11.444] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d RockyLinux -e kill 735
[2024-10-12 02:24:48.710] Download in background is enabled
```

**Comment by opsarno** [comment] 2024-10-12 02:39
Fix step

```bash
rm -rf ~/.vscode-server

cd /path/myproj

code .
Installing VS Code Server for Linux x64 (384ff7382de624fb94dbaf6da11977bba1ecd427)
Downloading: 100%
Unpacking: 100%
Unpacked 1763 files and folders to /root/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427.
Looking for compatibility check script at /root/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/bin/helpers/check-requirements.sh
Running compatibility check script
Compatibility check successful (0)
```

**Comment by aeschli** [comment] 2024-10-30 16:00
I fixed the problem with the incomplete installs. Duplicate of https://github.com/microsoft/vscode-remote-release/issues/9838

**Closed by aeschli** 2024-10-30 16:00 UTC
