### ISSUE TITLE
Theme: Background color at line-numbers

### ISSUE THREAD

**Issue by Agetorp** [Microsoft/vscode#1074] opened 2015-12-07 13:38 UTC
At first I thought this was a problem with the theme Solarized Dark, but it appears to be the same problem with most themes (not "Dark" or "Light").

The problem (albeit a small problem) is that when I for example paste several lines in a row, the background color at the line-numbers changes after some lines, as seen on line 1239 on the screenshot. The amount of lines needed to create show this fault differs.

<img width="612" alt="screen shot 2015-12-07 at 14 36 44" src="https://cloud.githubusercontent.com/assets/7148640/11628150/05bf70d8-9cf0-11e5-8b59-9e8e9b83ddf3.png">

OS X 10.11 (15A284)
VsCode: v0.10.3    

Reproduce:
1. Open any file with code
2. Select all
3. Copy
4. Spam paste until it occurs (anywhere from 50-1500 lines in my experience)

Is it possible that the problem has to do with transparent colors?

**Comment by egamma** [comment] 2015-12-07 22:50
Duplicate of #841 that is fixed in the latest.

**Closed by egamma** 2015-12-07 22:50 UTC
