### ISSUE TITLE
Hyperfluid colon when looking at map?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5848] opened 2016-04-26 15:19 UTC
Not sure why we add an extra ":" for watching a map?

![image](https://cloud.githubusercontent.com/assets/900690/14823490/08c68f12-0bd3-11e6-947f-c9db7ded02f2.png)

**Comment by isidorn** [comment] 2016-04-26 15:50
Because that is just the how we show all variables in the variables view. name: Type
The 0.99 is the name but it does not have a type, it is still represented to vscode as a variable, and vscode is not aware of this trick that the debug adapter does (chunking a big map into smaller parts)

Closing as designed

**Closed by isidorn** 2016-04-26 15:50 UTC
Labels: debug
