### ISSUE TITLE
'Checking For Updates...' is grayed out and an update message is never shown on Windows

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#25632] opened 2017-04-28 17:07 UTC
- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:13:08.212Z)
- OS Version: Windows_NT ia32 10.0.16179
---

Often on Windows (most of the time, but I don't think 100%), I find that I never get the update notification that an update is ready. And when I go to look at the Help menu, the `Checking For Updates...` item is grayed out and no matter how long I wait it never seems to recover until I completely restart vscode. Once I restart vscode and wait a bit (30s or more) then it will show the update notification.

This might be related to: https://github.com/Microsoft/vscode/issues/17159 but I don't get any crash or anything -- just the lack of update notification.

This also only seems to happen with the auto-update, not if I manually choose `Check For Updates...`

**Comment by joaomoreno** [comment] 2017-05-02 09:05
Are you behind a proxy? Does it happen after the computer wakes from sleep or something like that?

**Comment by eamodio** [comment] 2017-05-02 12:59
Not behind a proxy. It could be related to sleep - I'll try to note that the next time it happens.

**Comment by eamodio** [comment] 2017-05-08 07:28
I'm pretty sure the last time this happened my computer didn't go to sleep between me opening code and running into the issue.

**Comment by joaomoreno** [comment] 2017-05-08 09:58
It happened again, since?

**Comment by eamodio** [comment] 2017-05-08 13:42
Yeah, happened with the last insiders build last night. I do a lot of extension development/debugging maybe it is related to that?

**Comment by joaomoreno** [comment] 2017-05-09 07:17
When it happens, can you check the contents of `%TEMP%\vscode-update`?

**Comment by eamodio** [comment] 2017-05-09 11:26
Will do

**Comment by eamodio** [comment] 2017-05-09 14:49
Of course the update last night worked fine!

**Comment by eamodio** [comment] 2017-05-12 03:34
OK -- happened again -- this time my PC was sleeping (with vscode open) and the `Check For Updates...` is stuck.  I checked the `vscode-update` folder and it is completely empty.

**Comment by eamodio** [comment] 2017-05-16 14:07
Happened a couple more times -- definitely sleep related.

**Comment by joaomoreno** [comment] 2017-05-17 10:24
@egamma Also saw this.

**Comment by reversi-fun** [comment] 2017-06-14 04:41
I also encountered this issue.
VSCode Version: Code - Insiders 1.14.0-insider (bbcd10a, 2017-06-13T05:13:35.880Z)

related issues report is
https://github.com/Microsoft/vscode/issues/28681

**Comment by levani** [comment] 2017-07-12 06:17
I'm behind a proxy on windows 10 and also experienced this. Disabling the proxy seems to fixed it. Was trying to update from vscode 1.13.1

**Comment by smorzhov** [comment] 2017-07-14 08:29
Experienced the same issue. It occurs after waking the PC from sleep mode. Reopening vs code window solves the problem.
Windows 10 with creators update, vs code v1.14.0

**Comment by Geeprox** [comment] 2017-09-05 10:02
Experienced the same issue +1. Reopening vs code window is useless...
Windows 7, behind a proxy, vs code v1.15.0

**Comment by radu-v** [comment] 2017-09-07 07:13
Not having this issue anymore.

Version 1.16.0-insider
Commit 787b31c0474e6165390b5a5989c9619e3e16f953
Date 2017-09-05T21:00:35.399Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Windows 10 Enterprise (on Windows 8.1 Enterprise didnt have it either with this version)

**Comment by steelwil** [comment] 2017-09-11 06:06
I am using the` http_proxy/https_proxy` environmental variables and I am getting this issue. I have just rebooted and have this issue now on both my machines. It does not matter whether manually choose `Check For Updates...` or not. 

I do not see a link to Sleep mode.

I checked the contents of  `%TEMP%\vscode-update` and found the following in there:
`CodeSetup-stable-b8cd5b9556d8b70ea560d35b903422363f6c5c40.exe`
deleting and restarting VSCode made no difference.

My feeling is that it has something to do with the proxy, but everything else is working. Maybe it is trying to use the system Internet Options with in my case is using a configuration script.

I have been manually doing updates of late. (My Linux installs at home have no issues, but then again I do not have a proxy there)

Windows 7 and 10.
Version 1.16.0
Architecture x64

**Comment by david-russo** [comment] 2017-09-13 14:56
I've been having the same issue for at least the last couple major versions, regardless of the PC sleeping. I'm behind a proxy, though extension update checking and installation work fine, and I seem to recall the application's update feature also working in the past.

Additionally, I find that while the "Checking for Updates..." process is running, checking for extension updates can't occur (the menu item is available, but does nothing), so to accomplish that I need to restart Code and quickly check for extension updates before the automatic application update check kicks in and stalls.

Inside my `%TEMP%\vscode-update` directory I found an installation file for v1.14.0, dated 2017-07-13.

Windows 7, VS Code 1.15.1.

**Comment by lpeteet** [comment] 2017-09-27 15:17
I am having the same issue with version 1.16.1 and Windows 10 x64.
Keeps showing "Checking for Updates..." and it is grayed out.

**Comment by mayureshs** [comment] 2017-10-05 17:17
Me too, I am having the same issue with version 1.16.1 and Windows 10 x64. I am behind a corporate proxy. Keeps showing "Checking for Updates..." and it is grayed out.

**Comment by rdean716** [comment] 2017-11-07 13:52
I have been having this issue as well; I am behind a proxy that limits connectivity to known user agent strings.  After tracing with Fiddler, I can see that code's connection through our proxy is being blocked due to the user-agent string.  Maybe this will help others.

**Comment by Stanzilla** [comment] 2017-11-07 14:23
There are two parts to this issue, one is people behind proxies and the other where the update check gets stuck when you put a PC to standby/wake it.

**Comment by joaomoreno** [comment] 2018-01-31 15:10
Not great: https://github.com/electron/electron/issues/9849

**Comment by mattacosta** [comment] 2018-02-01 10:48
Wait... I don't see how that applies. In my sequence of events, if there is an update available, then it downloads successfully and I restart VS Code (so connection events must have been handled properly). If not, then the connection for the update check should have ended almost immediately. Therefore it would be highly unlikely that my system went to sleep in the middle of a virtually instantaneous check, almost everyday, for several months...

**Comment by Stanzilla** [comment] 2018-02-01 16:40
Yeah that seems different. My issue is more like that Electron does not manage to build up a connection in the first place after resuming from standby.

**Comment by joaomoreno** [comment] 2018-02-02 08:32
@mattacosta @Stanzilla You wake from sleep and the badge is there spinning and stays forever, correct?

**Comment by Stanzilla** [comment] 2018-02-02 19:41
@joaomoreno the menu item yeah, like this: https://i.imgur.com/NRrPsZq.png

**Comment by joaomoreno** [comment] 2018-02-05 08:03
OK so we're in the same page.

**Comment by mattacosta** [comment] 2018-02-05 10:28
I was able to reproduce this using the 1.19.3 release, just like @Stanzilla, but I have NOT been able to do it using the latest insiders build. This may have inadvertently been fixed at some point?

**Comment by joaomoreno** [comment] 2018-02-07 16:14
@mattacosta That is for sure. I came to this issue especially because I refactored that Code and hoped to have caught a bit more errors. But I could definitely reproduce electron/electron#9849. Because of this, we get the disconnection even way too late (~10 minutes). But its does come.

**Comment by mattacosta** [comment] 2018-02-08 03:31
Sounds like multiple issues with the same symptom. Since the "no connection" part is solved, maybe that "connection interrupted" electron one should be a separate follow-up, especially since it probably affects other components too (like an extension download).

**Comment by hervehobbes** [comment] 2018-02-09 07:13
Hello,

I solved the problem by removing some "wrap around" plugins (I'm not behind a proxy and my PC is never in sleep mode, I really turn it off every day)

**Comment by joaomoreno** [comment] 2018-02-09 09:21
@eamodio @egamma @mattacosta Let me know if you stop seeing this issue in the insiders build.

**Comment by eamodio** [comment] 2018-02-09 14:08
To be honest I haven't seen it in a long time.

**Comment by mattacosta** [comment] 2018-02-09 23:32
I also haven't seen it since last week when I re-enabled sleep mode.

**Comment by MauricioFarias** [comment] 2018-07-23 14:14
I found a workaround to this issue adding "update.enableWindowsBackgroundUpdates": false. 
Hope this works for you. I'm behind a corporative proxy too.

**Comment by joaomoreno** [comment] 2018-08-02 10:46
@MauricioFarias That is another issue. I will close this for now.

**Closed by joaomoreno** 2018-08-02 10:46 UTC
Labels: bug, electron, install-update, upstream, windows
