### ISSUE TITLE
Word based suggestions not working in functions/quotes

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#139559] opened 2021-12-21 06:39 UTC
**Does this issue occur when all extensions are disabled?:**
Yes

**VS Code and OS Version:**
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Steps to Reproduce:**
![777](https://user-images.githubusercontent.com/30685349/146883388-e5187cdc-97e7-462b-9d40-f258c3d097ce.gif)

**Comment by jrieken** [comment] 2022-01-05 08:04
Please provide all files in source, no GIFs! 

Also retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by kanlukasz** [comment] 2022-01-05 08:38
### Steps to Reproduce:

1. Download fresh VSCode portable from official [source](https://code.visualstudio.com/docs/?dv=winzip)

2. Unpack, create empty `data` directory, run

3. Select `Extensions View > ... > Disable all Installed Extensions` _(either way, nothing is installed because it's a fresh install)_

4. Reload Window

5. Open empty folder

6. Create two files - `from.php` & `to.php`

7. The contents of the `from.php` file:
```
<?php

$name = 'Bartholomew';

function getName(string $name): string
{
    return $name;
}
```

8. The contents of the `to.php` file:
```
<h1></h1>

<?php

getName('');

$name2 = '';
```

9. VSCode Settings:
```
{
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
    "editor.wordBasedSuggestionsMode": "allDocuments"
}
```

10. Now let's open and leave both files open and try to start typing the name 'Bartholomew' in the blanks in the file `to.php`.
As you will notice, autosuggestion will work between the `h1` tag, but will not work in `getName('');` function and in the `$name2 = '';` variable

---

Above I have written everything in the form of text and sources, but for the sake of clarity, I am attaching a short GIF with the result of these actions again:
![vsvsvs22](https://user-images.githubusercontent.com/30685349/148186550-e44ea4c0-a4ea-4b73-b8ac-0e4adb31240f.gif)

**Comment by jrieken** [comment] 2022-01-05 09:37
> Select Extensions View > ... > Disable all Installed Extensions (either way, nothing is installed because it's a fresh install)

No, you need to use `--extensions-dir <folder>` because user data is separate from extensions. So, please do that and confirm if you still see this. I don't, e.g I don't see `Bartholomew` being suggested inside the h1-tag nor the string. This is likely because another extension provides completions which are then all filtered. In that case you don't see textual suggestion (see https://github.com/microsoft/vscode/issues/21611)

**Comment by kanlukasz** [comment] 2022-01-05 10:07
I'm not sure if I understand correctly what you mean user data is separate from extensions.

I run VSCode from command line with:
`"C:\Users\username\Desktop\vscode\Code.exe" --extensions-dir="C:\Users\username\Desktop\vscode\data\extensions"`
but nothing has changed

---

![image](https://user-images.githubusercontent.com/30685349/148199304-a416e18a-eca0-4862-8245-9358d886c016.png)

---
![image](https://user-images.githubusercontent.com/30685349/148199428-70bd527d-a968-47b6-8177-c606a06e818e.png)

---

**PS.:**

**My portable installation looks like this:**
![image](https://user-images.githubusercontent.com/30685349/148198329-673c8c70-2f81-41c7-887e-639495b9c039.png)

---

**In the `data` directory that I created, I have:**
![image](https://user-images.githubusercontent.com/30685349/148198391-e6557bc5-ec54-4361-9259-4f38827db0fc.png)
The above directories were created automatically

---

**Extenions directory is empty:**
![image](https://user-images.githubusercontent.com/30685349/148198575-92fbd958-005c-4f60-bb07-41259648ae79.png)


---


If you want, I can install VSCode using the System Installer on another computer that has never had VsCode installed and check it again 🤷‍♂️

**Comment by jrieken** [comment] 2022-01-05 10:47
Sorry, I misread the very first step. You are doing it right but I still don't understand why I am not seeing any word suggestions...

**Comment by kanlukasz** [comment] 2022-01-05 10:49
Do your VSCode settings look the same as mine? I mean:

```
{
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
    "editor.wordBasedSuggestionsMode": "allDocuments"
}
```

**Comment by jrieken** [comment] 2022-01-05 10:52
Yes, this is what I see ⬇️ So, basically I always get suggestions from the built-in php extension and that mutes word bases suggestions

https://user-images.githubusercontent.com/1794099/148205948-3ce029e8-f627-46db-a932-73b7f0278881.mov

**Comment by kanlukasz** [comment] 2022-01-05 11:03
Thanks for sharing the screen.
Note that you are typing `Bar` or `bart` between `h1`. I can confirm that it doesn't actually prompt in this case, but if you type `Bart` it will work

See on my screen below:
![vsvsvs2233](https://user-images.githubusercontent.com/30685349/148207357-a94c6939-b32e-498e-84db-ea17ef8a6a63.gif)

**Comment by jrieken** [comment] 2022-01-05 14:15
> Note that you are typing Bar or bart between h1. I can confirm that it doesn't actually prompt in this case, but if you type Bart it will work

Thanks for clarifying - indeed with the `bart` prefix it works. It seems that the builtin php extension doesn't something with any shorter prefix which suppresses word based suggestions. 

I wasn't always able to reproduce what you see but after starring at the code I found a race condition - sometimes snippets would suppress completions (which isn't meant to ever happen). I will push a change now and would ask you to try again with next/tomorrows insiders build

**Comment by jrieken** [comment] 2022-01-07 07:50
@kanlukasz Can you give this a try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by Ciantic** [comment] 2022-01-07 15:16
This happened to me too, but it works in the insiders!

However it still shows those two #region things there, even though I have `php.suggest.basic: false`:

![image](https://user-images.githubusercontent.com/64731/148564432-c0151fa8-13dc-4936-ac71-8356bff9647c.png)

I don't know where it pulls those ones.

**Comment by jrieken** [comment] 2022-01-07 15:43
Ok, thanks for clarifying. Closing. Too eager snippets are tracked here: https://github.com/microsoft/vscode/issues/140039

**Closed by jrieken** 2022-01-07 15:43 UTC
Labels: snippets, suggest
