### ISSUE TITLE
Automatically indent "end" for ruby code

### ISSUE THREAD

**Issue by philipgiuliani** [Microsoft/vscode#2272] opened 2016-01-26 09:27 UTC
In VSCode 0.10.6 the "end" in ruby doesn't gets indented after writing it. It should be handled like the brackets in Javascript.

Left: VSCode, Right: Atom (Gif. Reload to see it again)
![indentation](https://cloud.githubusercontent.com/assets/5446019/12576889/3594f97e-c417-11e5-9006-71117fa4de04.gif)

**Comment by markediez** [comment] 2016-02-21 07:42
I'm guessing this will come in the next release?

**Comment by markediez** [comment] 2016-04-14 17:29
Any update on this?

**Comment by kyleect** [comment] 2016-06-09 20:54
+1 for this feature

**Comment by Tyriar** [comment] 2016-06-10 05:19
@rebornix does your ruby extension do this?

**Comment by rebornix** [comment] 2016-06-10 12:32
Firstly we have snippets in my ruby extension so each time you type `def` you will get correctly indented `end`. So it's likely a workaround.

Secondly, I think we have this auto indenting feature but unluckily I found it not working right now. I'll let you guys know when I have more info, then this issue can be treated as external.

**Comment by rebornix** [comment] 2016-06-13 08:13
I'm trying to support correct indentation as Atom does, and find following interesting difference between VS Code, Atom and TextMate.

TextMate documents `increaseIndentPattern` and `decreaseIndentPattern` at https://manual.macromates.com/en/appendix . `increaseIndentPattern` matches a starting line and any lines after it will have an additional indentation, this functionality is handled correclty in all editors.

But when we come to `decreaseIndentPattern`, we are running into some problems. The documenation in TextMate site is not that clear, when a line matches `decreaseIndentPattern` regex, should we unindent the current line or lines after? IMHO, it should be current line as any previous line has additional indentation and it's the right time to unindent. This is also how Atom does it.

However, in our implementation as below

```
/**
  * Describes indentation rules for a language.
  */
export interface IndentationRule {
	/**
	 * If a line matches this pattern, then all the lines after it should be unindendented once (until another rule matches).
	 */
	decreaseIndentPattern: RegExp;
```

Per comments we put in the definition, we are unindenting lines after but not the current line. I'm not sure if it's the root cause, but this makes `end` never gets correct unindentation.

There is also a long bebate to add `decreaseNextIndentPattern` to Atom in https://github.com/atom/atom/pull/6808 so I think we need to rethink what's the correct behavior of `decreaseIndentPattern`. I'll give TextMate a try once I'm back to my Mac to see what's the default behavior, before that I'd like to hear your voices. @alexandrudima , any thoughts?

**Comment by alexandrudima** [comment] 2016-07-05 09:13
@rebornix I followed https://manual.macromates.com/en/appendix while implementing it. 

I think I got wrong the semantics of `decreaseIndentPattern` (it should probably decrease the current line too).

The implementation is at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/supports/onEnter.ts#L128

To support decreasing the current line indent, the `EnterAction` must be extended with an additional type of `IndentAction`, a new one maybe called `OutdentInclusive` or something and it must be adopted everywhere where `EnterAction` is interpreted.

**Comment by cavneb** [comment] 2016-10-26 15:33
Are there any updates on this? It's the one crutch for developing ruby apps using VS Code

**Comment by just-nobody** [comment] 2016-11-20 22:41
> Are there any updates on this? It's the one crutch for developing ruby apps using VS Code
Lua as well. :(

**Comment by davidanthoff** [comment] 2016-11-22 21:03
For the julia extension we are also waiting for this, would be great if this could be prioritized.

**Comment by surajreddy** [comment] 2016-11-24 20:41
bump.

**Comment by JaredReady** [comment] 2016-11-29 16:39
+1 this is really annoying.

**Comment by nitsujri** [comment] 2016-12-01 09:51
+1 for visibility since this isn't getting any love.

**Comment by BrAmSe** [comment] 2016-12-01 18:19
+1 its time to give some love to this bug

**Comment by rebornix** [comment] 2016-12-02 19:29
My investigation up there https://github.com/Microsoft/vscode/issues/2272#issuecomment-225515268 is kind of misleading. The existing code and logic is correct and necessary. The only thing we didn't take into consideration is modifying indentation while users type.

Right now, our existing logic about `decreaseIndentPattern` is checking whether we should decease the following line if you press `enter`. This makes sense as after you press `enter`, the content after your content becomes a new line, which makes it as `following line`. But to enable this feature, we need to declare the correct `decreaseIndentPattern` for ruby code, I've filed a feature request here https://github.com/Microsoft/vscode/pull/16401. Before that's merged, you can play with my ruby extension but I don't think it will take long.

Another part is actually modifying indentation while users type. Since we are at the end of this iteration and adding this feature to master might affect TypeScript, Ruby and any other potential extension that leverages `decreaseIndentPattern` https://github.com/search?utf8=%E2%9C%93&q=decreaseIndentPattern+vscode&type=Code&ref=searchresults. We don't rush this time but we can have that in recent updates of Insider build.

**Comment by kpollich** [comment] 2017-03-07 18:17
Any updates on this? I'd like to use Visual Studio Code for Ruby projects but this behavior is frustrating coming from other editors.

**Comment by elliotlarson** [comment] 2017-03-24 20:47
Yeah, I just tried to start using VSCode for Ruby development, and I have to say, this is kind of a deal breaker.  This makes just writing basic Ruby code pretty frustrating.  I'm sure it will get fixed at some point.  I'll revisit then.

**Comment by andrewmartin** [comment] 2017-03-25 23:54
+1

**Comment by pedroaliens** [comment] 2017-03-26 22:11
+1

**Comment by surajreddy** [comment] 2017-03-27 17:25
This seems to work for me now after inserting a newline after the end, but it would be good if this happens right after `end` is typed:

![vscode_end](https://cloud.githubusercontent.com/assets/80290/24368997/95a1a6c2-12f0-11e7-89fa-28aa49747a84.gif)

This is still better than what it was before.

**Comment by davidanthoff** [comment] 2017-04-07 16:08
Yes, let me second that request that things should unindent not just on enter, but when then word ``end`` has been typed. We really, really would like to see that for the julia extension as well.

I also think it would be great if this could move to a milestone fairly soon. It is one of the few core areas where VS Code currently lacks behind something like Atom.

**Comment by StanBright** [comment] 2017-04-26 04:52
I started using VSCode 2 days ago, moving from Sublime, and I love it. This, however, is one of the few things that annoy me at the moment...

**Comment by zebogen** [comment] 2017-05-04 15:13
Agreed. I love VS Code thus far, but I'm switching back to Atom for Ruby development just because of this.

**Comment by coleby210** [comment] 2017-05-11 23:51
VSCode is by far my favorite editor, except for this. Would absolutely love to see this implemented.

**Comment by emitchel** [comment] 2017-05-24 15:48
VSCode is awesome, I've gotten around this by Shift+TABing following `end` but VSCode NEEDS to update this.

**Comment by seivan** [comment] 2017-06-14 06:43
Not just indentation, but also highlighting  do/end brackets for languages like `Ruby` or `Elixir` 

It works fine with braces `{ }` but I'd like to see it for `do end` as well.

**Comment by andyferris** [comment] 2017-06-14 23:07
To add my voice, as a newcomer I'm extremely happy with VS Code but this just seems odd. If this works for curly-brace languages, I can't see the logic in not implementing this same behavior for languages which terminate blocks with `end`.

**Comment by rebornix** [comment] 2017-06-19 15:54
You can now set `editor.autoIndent` to `true` in today's Insider to embrace this feature, thank you all for your patience and help on this! Feedback welcome.

**Closed by rebornix** 2017-06-19 15:54 UTC
Labels: feature-request, languages basic

**Comment by PCGeekBrain** [comment] 2017-07-14 23:30
This issue was reintroduced in the latest update

**Comment by blackhaj** [comment] 2017-07-18 03:17
Search for editor.autoIndent in settings and change it to true
