### ISSUE TITLE
Language Code Detection

### ISSUE THREAD

**Issue by Souren09** [Microsoft/vscode#5535] opened 2016-04-20 08:18 UTC
- VSCode Version:1.0.0
- OS Version: windows10.0.10586

Steps to Reproduce:

1. Open file with language code GB2312
2. Detected code is UTF-8.

**Comment by bpasero** [comment] 2016-04-20 09:14
Duplicate of #5388

**Closed by bpasero** 2016-04-20 09:14 UTC
Labels: workbench

**Comment by Hyperdingo** [comment] 2017-07-27 12:13
This setting has been added: **files.autoGuessEncoding**

Will hopefully be true as default soon; https://github.com/Microsoft/vscode/issues/23417
