### ISSUE TITLE
Multi select and tree elements with commands

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#79871] opened 2019-08-27 09:30 UTC
Testing #79819

Tweak the File Explorer view at https://github.com/microsoft/vscode-extension-samples/blob/7b4d139f4b42e6c13fb022f1c8dad5f8179d5ce0/tree-view-sample/src/fileExplorer.ts#L304:

![image](https://user-images.githubusercontent.com/5047891/63759474-e05bd680-c8bd-11e9-9863-2e634e3be1ef.png)

It is not possible to do multi-select because any time I click the items in the File Explorer, the files open. I have tried with shift, alt and cmd.

**Comment by alexr00** [comment] 2019-08-28 08:43
This is actually a duplicate of #79889

**Closed by alexr00** 2019-08-28 08:43 UTC
