### ISSUE TITLE
'Problems' panel not displaying problems

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#61306] opened 2018-10-19 09:37 UTC
Issue Type: <b>Bug</b>

I'm refactoring a Typescript project, and the screen looks as attached. Please let me know what info I can supply beyond those below.

Restarting VSCode removes the issue.

![image](https://user-images.githubusercontent.com/512816/47210486-5be22280-d393-11e8-8aad-bef0181cd80f.png)

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.62GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
vscode-markdownlint|Dav|0.20.0
tslint|eg2|1.0.40
vscode-ionic-snippets|fiv|0.5.3
vscode-scss|mrm|0.6.2

</details>

**Comment by mjbvz** [comment] 2018-10-22 21:46
First, please try upgrading to VS Code 1.28.2 and disable all extensions to make sure one of those is not the root cause.

Then, if this is still occurring, please:

1. In VS Code, run the `Toggle Developer Tools` command. This should open dev tools
1. Open the devtools console.
1. Are there any errors or warning messages printed in there?

**Comment by leegee** [comment] 2018-10-26 10:01
On 1.28.1, with all extensions disabled, it's fine.

**Comment by leegee** [comment] 2018-10-26 10:02
Then again, after re-enabling all extensions, everything is also fine...

**Comment by leegee** [comment] 2018-10-26 10:03
![image](https://user-images.githubusercontent.com/512816/47559920-184d6280-d917-11e8-8513-902b8196f0a6.png)

**Comment by mjbvz** [comment] 2018-10-26 18:47
Thanks. Closing as not-reproducable

**Closed by mjbvz** 2018-10-26 18:47 UTC
Labels: error-list, needs more info, typescript
