### ISSUE TITLE
Can't ctrl+click on paths

### ISSUE THREAD

**Issue by kasvtv** [Microsoft/vscode#50519] opened 2018-05-26 21:19 UTC
- VSCode Version: 1.23.1
- OS Version: W10

Whether it's in SCSS or JS, I cannot ctrl+click on any of my imports in any of my files! I was excited about switching to this editor, but this totally breaks usability for me. Doesn't matter if I use require or import (or @import in scss's case). "Go to definition" also doesn't work as it shows: 

![vscode bug](https://user-images.githubusercontent.com/1628729/40580236-01888240-613b-11e8-8ced-f6e9450f8b2c.png)

Seems like it does not recognize it as a path?

Steps to Reproduce:

1. Import any file through either JS or SCSS
2. Place cursor inside the path string
3. Press F12

Does this issue occur when all extensions are disabled?: Yes!!

PS: I can't see any error messages in the dev console.

**Comment by mjbvz** [comment] 2018-05-29 17:17
Please provide a Javascript example as well. Share both the code (as text) and a description of your project structure

**Comment by aeschli** [comment] 2018-05-30 08:55
SCSS is a duplicate of #29899.

**Comment by kasvtv** [comment] 2018-05-31 20:15
Allright, I have at least found the issue with JavaScript.

I was reworking the architecture of a very old project my employer still had lying around. It had lots of nastyness with many separate files building a global object. So I was calling require(filepath) to a JS file that performed `window.customObject = { ... }` but did not actually export anything. Not sure if this is an actual issue. It was a correct filepath, just something that wasn't exporting any module.

The problem with SCSS imports is still not working. It is very easily replicable:

```
// entry.scss (none of these imports work when hitting F12):
@import 'imported.scss';
@import 'imported';
@import './imported.scss';
@import './imported';
body {
	background-color: $myColor;
}

// imported.scss:
$myColor: #123456;

```

Using the following version:
```
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Problem also exists without any extensions active.

**Comment by mjbvz** [comment] 2018-05-31 21:09
Ok, closing this as a duplicate of #29899 then

**Closed by mjbvz** 2018-05-31 21:09 UTC
Labels: javascript, needs more info
