### ISSUE TITLE
Terminal/Console Broken for ZSH

### ISSUE THREAD

**Issue by ruddra** [Microsoft/vscode#28451] opened 2017-06-11 09:40 UTC
- VSCode Version: 1.13
- OS Version: Ubuntu 16.04
Steps to Reproduce:

1. Open VSCode
2. Open Terminal using "ctrl + ~" or preferable shortcut or just open from `view -> Integrated Terminal`
Now it looks like: 
![screenshot from 2017-06-11 15-36-47](https://user-images.githubusercontent.com/3099861/27009954-0a2c4770-4ebc-11e7-9492-750ca9cd8d95.png)
![screenshot from 2017-06-11 15-36-40](https://user-images.githubusercontent.com/3099861/27009955-0b9dbed6-4ebc-11e7-9b33-be8cbeabfccc.png)

Check the last line the terminal.

**Comment by ajames20** [comment] 2017-06-11 10:11
I am having the same issue.
VS code Version 1.13.0 (1.13.0)
MacOS Version 10.12.5
<img width="1271" alt="screen shot 2017-06-11 at 1 10 01 pm" src="https://user-images.githubusercontent.com/13269277/27010185-50133d44-4ea7-11e7-9cfa-9054414490fc.png">

**Comment by davisshaver** [comment] 2017-06-11 10:47
+1 to this, could it be ZSH related? I am using and looks like all in thread are too. Font is Meslo for Powerline.

**Comment by ruddra** [comment] 2017-06-11 11:15
Could be. I have ZSH installed

**Comment by hawrre** [comment] 2017-06-11 11:24
I have same issue with ZSH and VSCode Version: 1.3 on mac

**Comment by seanmars** [comment] 2017-06-11 12:39
+1, I have same issue with ZSH and VSCode Version: 1.3 on mac

**Comment by rookie1024** [comment] 2017-06-11 22:27
+1, and it's even worse if you have $RPROMPT set.  I'm using zsh v5.1.1 and VS Code v1.13 on Elementary OS Loki

As you can see here, my $RPROMPT (which is just the date and time) has been pushed clear off the terminal:
![image](https://user-images.githubusercontent.com/6175424/27015027-5bfe08c0-4eb9-11e7-857b-842c427ab150.png)

It also kind of freaks out and almost displays it correctly for a split second, and then everything goes wonky every time the terminal redraws itself (e.g. when text is typed or the window is activated).

Furthermore, I'm pretty sure it's not a zsh error because this part of the prompt here:
![screenshot from 2017-06-11 15 17 19 cropped](https://user-images.githubusercontent.com/6175424/27015049-12651db0-4eba-11e7-88e9-faf0856d164a.png)

...should have a space after the Powerline > symbol, as seen here in Terminator:
![image](https://user-images.githubusercontent.com/6175424/27015054-2ee9303e-4eba-11e7-8fb7-b1448a90eb6d.png)

**Comment by charlzyx** [comment] 2017-06-12 02:25
+1 I have same issue with ZSH and VSCode Version: 1.3 on mac

**Comment by ruddra** [comment] 2017-06-12 04:49
We can safely assume that for ZSH, the terminal is broken.

**Comment by happybang** [comment] 2017-06-12 09:51
+1 i  have save issue  on vs code  1.1.3 and zsh

**Comment by burknator** [comment] 2017-06-12 10:48
No issues on macOS 10.12.5, VCode 1.13 and zsh 5.2. Although my theme (`robbyrussell`) doesn't show the current working directory, maybe that's a hint for the cause?

<img width="965" alt="bildschirmfoto 2017-06-12 um 12 44 23" src="https://user-images.githubusercontent.com/26658/27030568-143516b4-4f6d-11e7-97d9-6dd91b28bb0d.png">

**Comment by ramya-rao-a** [comment] 2017-06-12 17:23
Closing as duplicate of #28304

cc @Tyriar

**Closed by ramya-rao-a** 2017-06-12 17:23 UTC
