### ISSUE TITLE
Rename and format document is really slow

### ISSUE THREAD

**Issue by romandvoskin** [Microsoft/vscode#8839] opened 2016-07-07 15:02 UTC
- VSCode Version:1.2.1
- OS Version: Microsoft Windows [Version 6.1.7601]

Slowness is new to this version. No extensions installed. Using Typescript with tsconfig.json like this: 
{
    "compilerOptions": {
        "module": "amd",
        "target" : "es5",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "emitDecoratorMetadata": true,
        "sourceMap": true
    },
    "excludes": [
        "node_modules"
    ]
}

Steps to Reproduce:
1. Highlight a variable and press F2 -> Really slow
2. Highlight code and press Alt+Shift+F -> Really slow

**Comment by CherryMill** [comment] 2016-07-07 22:04
Perhaps, it is not VS Code`s fault but the OS platform, I guess.

**Comment by dbaeumer** [comment] 2016-07-10 10:54
@romandvoskin can you share a project exposing the problem. I tried with a simple example and can't reproduce.

**Comment by venura9** [comment] 2016-11-14 01:36
1.7.1 I still have the same issue. 

use a complex xml with 2000+ lines and give it a go. It takes about 6-10 seconds to see something happening.

**Comment by dbaeumer** [comment] 2016-11-15 01:24
@venura9 can you share your example ?

@waderyan we should enable tracing and see how long the request takes. If it takes most of the time then this needs to be addressed in TS land.

**Comment by waderyan** [comment] 2016-11-21 23:07
Closing until more info is given. Thanks!

**Closed by waderyan** 2016-11-21 23:07 UTC
Labels: needs more info, typescript
