### ISSUE TITLE
VSCode Typescript service stopped

### ISSUE THREAD

**Issue by yueguanyu** [Microsoft/vscode#20537] opened 2017-02-13 10:22 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular2|johnpapa|2.0.0|
|TypeScriptImport|kevinmcgowan|1.17.0|
|vim|vscodevim|0.5.3|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment] 2017-02-13 21:35
I'm guessing this is a duplicate of #20496. See my comment there for how to workaround this

**Closed by mjbvz** 2017-02-13 21:35 UTC
Labels: duplicate, External, needs more info

**Comment by yueguanyu** [comment] 2017-02-15 01:13
Okey, thank you very much, that's helpful~.

________________________________
发件人: Matt Bierner <notifications@github.com>
发送时间: 2017年2月13日 21:35:40
收件人: Microsoft/vscode
抄送: JULIAN; Author
主题: Re: [Microsoft/vscode] VSCode Typescript service stopped (#20537)


I'm guessing this is a duplicate of #20496<https://github.com/Microsoft/vscode/issues/20496>. See my comment there for how to workaround this

―
