### ISSUE TITLE
file:/// scheme folder links don't work in terminal

### ISSUE THREAD

**Issue by jidar** [microsoft/vscode#129457] opened 2021-07-26 20:57 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Linux x64 5.4.0-80-generic

Steps to Reproduce:

1.  open a vscode window
2.  open the embedded vscode terminal
3. type any file path to a path that exists, but prepended with the uri 'file:///' prefix (example: file:////home/somedir)
4.  ctrl+click on that path
6. An error message appears: "Unable to open 'somedir': File is a directory

The expected behavior (opening the directory in vscode) works for regular paths (/home/somedir)

**Comment by bucknerns** [comment] 2021-07-26 20:58
+1

**Comment by meganrogge** [comment] 2021-07-27 16:01
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by meganrogge** [comment] 2021-07-27 16:05
duplicate of #129023

**Comment by bucknerns** [comment] 2021-07-27 23:06
Can we get a little explanation of how this is a duplicate? Seems completely unrelated. 
This is incorrect handling of RFC 8089, RFC 3986 links while the other is failure to handle softlinks while using remote ssh.
The issue here is file:// schema is treated as if it can only be a file while on the posix path it detects file vs directory.

**Comment by Tyriar** [comment] 2021-07-28 12:01
Can reproduce the problem, it should say folder not file:

![image](https://user-images.githubusercontent.com/2193314/127318814-af2e1a07-2c81-413b-a27d-5b6205095b8c.png)
![image](https://user-images.githubusercontent.com/2193314/127318825-4b3d9bda-a3b0-4ea6-949c-493b29eb89b7.png)

**Comment by Tyriar** [comment] 2021-07-28 12:03
Repros on Windows too.

Same thing happens in the editor:

![image](https://user-images.githubusercontent.com/2193314/127319075-4fdfd418-529d-40ab-bf4b-81b54d5eb4b5.png)

**Comment by TylerLeonhardt** [comment] 2021-07-29 20:38
So the link does work... but I guess I expected the underline to include the `file:` bit. It's a nit and I don't feel too strongly about it, but thought I'd mention.
![image](https://user-images.githubusercontent.com/2644648/127562424-61bcf374-d7a5-404f-b0c0-4b78d05950cf.png)

**Comment by meganrogge** [comment] 2021-07-29 21:26
@TylerLeonhardt let's wait until @Tyriar is back for that. I'm considering this verified for now

**Comment by Tyriar** [comment] 2021-12-06 14:43
Problem is back, looks a little different though:

![image](https://user-images.githubusercontent.com/2193314/144866021-6798439f-133b-48b0-9a7d-296ed13c6195.png)

**Comment by Tyriar** [comment] 2021-12-06 22:43
I think the new problem is Windows only

**Closed** 2021-12-10 19:18 UTC
Labels: bug, terminal, windows, terminal-links
