### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by celebjads** [microsoft/vscode#94771] opened 2020-04-09 10:50 UTC
Issue Type: <b>Bug</b>

when i open the vscode it shows this msg , after i click ctrl+shift+p git:clone it shows error

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.26GB (12.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.2
githistory|don|0.6.3
gitlens|eam|10.2.1
git-project-manager|fel|1.7.1

</details>

**Comment by gjsjohnmurray** [comment] 2020-04-09 11:20
If you disable your four enabled extensions, then restart, does "Extension host terminated unexpectedly" message still appear?

If not, re-enable your extensions one at a time, restarting each time. Does that reveal which extension is causing the EH crash?

**Comment by RMacfarlane** [comment] 2020-04-09 16:09
Duplicate of https://github.com/microsoft/vscode/issues/94807

**Closed** 2020-04-09 16:10 UTC
Labels: *duplicate, new release
