### ISSUE TITLE
Cmd+1/2 doesn't focus on the input box of Interactive Window

### ISSUE THREAD

**Issue by nikhbikh** [microsoft/vscode#124788] opened 2021-05-26 02:30 UTC
## Environment data

-   VS Code version: 1.56.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Mac 11.2.3 (20D91)
-   Python and/or Anaconda version: Python 3.7.10, conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

- Focus should return to input box after Ctrl+2.

## Actual behaviour

- Focus does not return to input box.

## Steps to reproduce:

1. Open vscode
2. Open an Interactive Window in the second pane (cmd+ shift + p -> "Jupyter: Create Interactive Window")
3. Toggle between cmd+1 and cmd+2

## GIF of issue
![vscode_bug](https://user-images.githubusercontent.com/25276123/119593550-06faba00-bd8f-11eb-8327-2887918eada0.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

Every time I switch to the Interactive Window, this log appears

<p>
```Info 2021-05-25 19:27:54: Attempting to start a server because of preload conditions ...
```
</p>
</details>

**Comment by pmh722** [comment] 2021-06-04 19:54
Also facing this highly annoying regression in Ubuntu. VSCode version 1.56.2.

**Comment by mjbvz** [comment] 2021-06-07 21:58
@rchiodo Extensions generally need to implement restoring focus in their webviews. Does the interactive window custom editor have logic for this?

**Comment by rchiodo** [comment] 2021-06-07 22:06
@mjbvz it does. Here: 

https://github.com/microsoft/vscode-jupyter/blob/1477c23b240bbf3874a60fc47910f95f5d731c57/src/datascience-ui/interactive-common/textAreaFocusTracker.tsx#L6

At least that code should be setting focus.

**Comment by mjbvz** [comment] 2021-06-07 22:13
@rchiodo  Can you help please investigate to see what specifically isn't working?

**Comment by rchiodo** [comment] 2021-06-07 22:18
I'm looking now to make sure that TextAreaFocusTracker actually gets called. We haven't touched the interactive window in months though - hence why we moved it to vscode instead. But I'll verify our focus handler isn't being called (meaning the webview isn't getting focus)

**Comment by rchiodo** [comment] 2021-06-07 22:19
Haven't tried this time, but last time this repro'd with the cat coding demo after adding a text element and attempting to give it focus like we do in that TextAreaFocusTracker.

**Comment by rchiodo** [comment] 2021-06-07 22:28
Yes the TextAreaFocusTracker does not receive focus when using CMD+1/CMD+2. It does if I click in the webview, but not when using the keyboard.

**Comment by DavidKutu** [comment] 2021-06-10 22:53
A similar issue happens when using a webview with the custom editor (like the webview notebook from the Jupyter extension).

If you're focused on a cell, switch focus with `alt + tab` to another window, and then `` back, the focus on the cell is lost and goes to the menu.

More info here: https://github.com/microsoft/vscode-jupyter/issues/6148

**Comment by kalingibbons** [comment] 2021-06-14 19:13
Did you mean to close both issues without any fix @DavidKutu? It looks like you told the other thread to follow this issue and then closed both with no solutions.

**Comment by Scaleframe** [comment] 2021-06-17 19:11
Getting this same issue on WSL running VSCode version `1.56`  and Python extension version `v2021.6.944021595`. 

Switching to interactive window via keyboard shortcut does not focus within the interactive window itself, just the top level tab. 

> Tabbing once the interactive window is in focus (from a hotkey switch) will tab to other editor groups instead of within the window. 

> If you click on the interactive window with the mouse, tab will then move between components within the window as expected. From here, after 5 or 6 tabs you can get to the input box.  

This is a pretty cumbersome bug as far as workflow effect. If there's anything I can help look at or clarify from this side please let me know. Thanks!

**Comment by FloHu** [comment] 2021-07-02 14:17
I have the same problem. For me even tabbing after focusing the interactive window notebook tab doesn't work. VSCode version `1.57.1` and Python extension version `2021.6.944021595`. Especially when doing exploratory data analysis this slows down things quite a bit since I have to keep reaching for the mouse to inspect variables.

**Comment by duncanmortimer** [comment] 2021-07-22 09:11
I'm having the same issue:

vscode `1.58.0`
python extension version `v2021.7.1053846006`
Mac OSX 11.4

Changing focused editor group via Cmd+1,2,3 doesn't put the cursor into the interactive execution cell (and I so far haven't found any way to access the cell via a keyboard shortcut when the associated group is focused). Thanks.

**Comment by rchiodo** [comment] 2021-07-22 16:33
If you switch to the native version of the interactive window (download the VS code insiders bits), this problem is fixed.

**Comment by pmh722** [comment] 2021-07-22 16:36
> If you switch to the native version of the interactive window (download the VS code insiders bits), this problem is fixed.

How buggy is the "native version"? Is it still in beta?

**Comment by FloHu** [comment] 2021-07-22 16:36
What are the "VS code insiders bits"?

**Comment by rchiodo** [comment] 2021-07-22 16:53
> How buggy is the "native version"? Is it still in beta?

I suppose this is a matter of opinion. We don't have a beta really. Just insiders. Maybe you can call insiders 'beta'. Insiders lets you try it out without having to commit to it yet though.

Insiders is here:
https://code.visualstudio.com/insiders/

You can read more about VS code's processes (which the jupyter extension follows for the most part) here:
https://github.com/microsoft/vscode/wiki/Development-Process

**Comment by pmh722** [comment] 2021-07-22 17:24
> You can read more about VS code's processes (which the jupyter extension follows for the most part) here:
> https://github.com/microsoft/vscode/wiki/Development-Process

Got it. I see at this link that features get released to "Insiders" the week before general launch (the "end game" week). So "native version" should be available in the main version of VS Code next week or so? Thanks!

**Comment by zwangz** [comment] 2021-08-08 10:19
Can confirm this issue is fixed in the new vsc / Jupyter extension update, with or without `"jupyter.enableNativeInteractiveWindow": false`

**Comment by natephysics** [comment] 2021-08-08 11:30
Now begins the countdown to when it makes it into the live build :D

**Comment by pmh722** [comment] 2021-08-11 20:55
Confirmed this is fixed for me on 1.59 with "native" experience. Thank you!

**Comment by mjbvz** [comment] 2021-08-13 01:53
Closing as this seems resolved by the new interactive window

**Closed by mjbvz** 2021-08-13 01:53 UTC
Labels: webview
