### ISSUE TITLE
save all feature is not working 

### ISSUE THREAD

**Issue by chirag8966** [microsoft/vscode#76838] opened 2019-07-08 07:46 UTC
Issue Type: <b>Bug</b>

save all feature is not working in ubuntu after pressing Ctrl + k then s.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.1.9-050109-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2687)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|2.4.0
vscode-typescript-tslint-plugin|ms-|1.2.1
debugger-for-chrome|msj|4.11.6
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.8.0
unique-window-colors|stu|1.0.51
vscode-wakatime|Wak|2.1.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by bpasero** [comment] 2019-07-08 08:16
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by chirag8966** [comment] 2019-07-08 08:43
I tried doing it with all extensions disabled still Ctrl + k chord to S is
not working .

Regards
Chirag Jain
8966062609

**Comment by bpasero** [comment] 2019-07-08 10:24
@chirag64 by default it should be `Ctrl+Shift+S`, did you change it?

![image](https://user-images.githubusercontent.com/900690/60803338-427c4300-a17b-11e9-8bed-278eb60e1858.png)

**Comment by chirag8966** [comment] 2019-07-08 10:58
I am talking about the shortcut of save all without formatting that is Ctrl
+ k chord to S.
[image: save all.png]

Regards
Chirag Jain
8966062609

**Comment by bpasero** [comment] 2019-07-08 11:54
@chirag8966 I cannot reproduce, do you do this?
* open a file
* type to make it dirty
* press Ctrl+K
* release all keys (remove hands from keyboard)
* press S

Does that work?

**Comment by chirag8966** [comment] 2019-07-08 12:22
I did the same exact thing and it is not working. It is working in my
windows machine however not working in my Ubuntu machine.

I have found a workaround to set a new key binding to save all feature.

The issue still remains if the default keybinding is working in windows it
should also work in Ubuntu (Linux).

Regards
Chirag Jain
8966062609

**Comment by bpasero** [comment] 2019-07-08 12:25
@chirag8966 can you try to assign this keybinding to another command to see if the keybinding is broken for you?

**Closed** 2019-07-15 14:21 UTC
Labels: needs more info
