### ISSUE TITLE
terminal cursor position not being updated

### ISSUE THREAD

**Issue by syncMutex** [microsoft/vscode#157073] opened 2022-08-04 06:42 UTC
Issue Type: <b>Bug</b>

I am using ncurses library in C.

when I use `prefresh()` and refresh the pad, it doesn't update the cursor in vscode integrated terminal but it works as expected on other terminals.

current output:

![Capture](https://user-images.githubusercontent.com/59785934/182779071-114cdd2a-d23e-43d4-8a0e-9c2e9754696f.PNG)

note that I have provided 4 spaces after last letter.

expected (works on other terminals):

![Capture_2](https://user-images.githubusercontent.com/59785934/182779272-35467a4b-d779-4d03-a94b-5a5cdadf9459.PNG)

code snippet:

```
while(!quit) {
  c = getch();
  switch(c) {
  case 8:
  case 127:
  case KEY_BACKSPACE:
    if(curs_pos.x <= MIN_CURS_POS) break;
    mvwdelch(window.pad, curs_pos.y, --curs_pos.x);
    wmove(window.pad, curs_pos.y, curs_pos.x);
    break;
  default:
    mvwaddch(window.pad, curs_pos.y, curs_pos.x++, c);
    wmove(window.pad, curs_pos.y, curs_pos.x);
  }
  prefresh(window.pad, window.cur_pos, 0, 0, 0, window.max.y - 1, window.max.x);
}
```

The problem is that `wmove()` and refreshing is not working for some reason.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.94GB free)|
|Process Argv|--crash-reporter-id 402d8481-e1f2-4295-ae37-b0c1062d7c70|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
go|gol|0.35.1
better-cpp-syntax|jef|1.15.19
python|ms-|2022.10.1
vscode-pylance|ms-|2022.8.10
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.4
cpptools-extension-pack|ms-|1.2.0
LiveServer|rit|5.7.5
pdf|tom|1.2.0
cmake|twx|0.0.17
vim|vsc|1.23.2
volar|Vue|0.39.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30534093

```

</details>

**Comment by meganrogge** [comment] 2022-08-08 18:22
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2022-08-08 18:22 UTC
