### ISSUE TITLE
Configure setting to disable icon for "Run Python File In Terminal"

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#132810] opened 2021-08-31 23:03 UTC
### Discussed in https://github.com/microsoft/vscode-python/discussions/16591

<div type='discussions-op-text'>

<sup>Originally posted by **Diogo-Rossi** June 30, 2021</sup>
I would like to revive the discussions microsoft/vscode-python#6921 and microsoft/vscode-python#7034

Now that VS Code limited to 9 icons showing on menu bar, this "play button" takes up space of others icons I prefer.</div>

**Comment by luabud** [comment] 2021-09-09 22:57
I'm transferring this issue because I _think_ we don't have control over this as it's a package.json contribution

**Comment by sbatten** [comment] 2021-09-13 19:56
sounds like a duplicate of https://github.com/microsoft/vscode/issues/46403

**Closed by sbatten** 2021-09-13 19:56 UTC
