### ISSUE TITLE
signatureHelp gives buggy results when one parameter is a subset of another

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#21518] opened 2017-02-27 19:44 UTC
- VSCode Version: 1.9.1, 1.10.0
- OS Version: Windows (probably the Linux/Mac too)

Steps to Reproduce:

1. Install the C++ extension (should be reproduceable with other extensions that implement the signatureHelp protocol).
2. Create a test.cpp file.
3. Enter text: int test(int a, int aa);
4. Save the file.
5. Type: test(

Bug: The results are buggy (see the screenshot) -- it shows "int test(int a, int aint aint aa)" with the 2nd "int a" underlined. It appears to be a VS Code bug. The expected result is "int test(int a, int aa)" with the first "int a" underlined. You get correct results if the paramaters are not a subset of each other. In other words, the bug repros because "int a" is a subset of "int aa". The result we send back to VS Code is:

{
    "jsonrpc": "2.0",
    "id": 19,
    "result": {
        "signatures": [
            {
                "label": "int test(int a, int aa)",
                "parameters": [
                    {
                        "label": "int a"
                    },
                    {
                        "label": "int aa"
                    }
                ]
            }
        ],
        "activeSignature": 0,
        "activeParameter": 0
    }
}

![image](https://cloud.githubusercontent.com/assets/19859882/23376480/179497e6-fce1-11e6-9112-2f0e091a4c58.png)

**Comment by isidorn** [comment] 2017-02-28 08:36
Can you please file this against the C++ extension repository here https://github.com/Microsoft/vscode-cpptools
Thank you

**Comment by sean-mcmanus** [comment] 2017-02-28 13:06
It's not a bug with the C++ extension. We're the developers of the extension. We pass correct JSON info to VS Code and it displays it incorrectly.

**Comment by jrieken** [comment] 2017-02-28 14:11
dupe of #18782

**Closed by jrieken** 2017-02-28 14:11 UTC
