### ISSUE TITLE
NotebookController.asWebviewUri does not return a valid Uri

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#121866] opened 2021-04-21 20:23 UTC
- VS Code Version:
- OS Version:

When using the `NotebookController.asWebviewUri`, the return value doesn't seem to be right.
The scheme is `https`;
Here's the original uri
`file:///Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/tmp/scripts/1b7c1df52b08c78a4d83d56dde9eab9ae8d1661acca0242add77e75e4ada73c6/index.js`

& here's the uri returned by asWebviewUri
`https://file:///Users/donjayamanne/Desktop/Development/crap/docbug/misc/ab.ipynb%20-%20.python392jvsc74a57bd0f27f72f6c6baa0a6a609e16751f265321788b5ae7e7b215313bcb4161465baee./Users/donjayamanne/miniforge3/envs/env1/bin/python./Users/donjayamanne/miniforge3/envs/env1/bin/python.Python%203.9.2%2064-bit%20%28%27env1%27%29.vscode-webview-test.com/vscode-resource/file///Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/tmp/scripts/1b7c1df52b08c78a4d83d56dde9eab9ae8d1661acca0242add77e75e4ada73c6/index.js`

Didn't add comments here https://github.com/microsoft/vscode/issues/121329 as this is a bug & not a discussion item.

@jrieken @rebornix @IanMatthewHuff /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment] 2021-04-22 06:29
> When using the NotebookController.asWebviewUri, the return value doesn't seem to be right.

Unsure what you mean? Does it look funny or isn't it working?

**Comment by DonJayamanne** [comment] 2021-04-22 09:49
> Does it look funny or isn't it working?

Looks funny, and that uri didn't seem to get loaded (I believe I saw 404 in console logs)
I assumed that the uri was incorrect and that's why it never loaded. In the past I've seen a custom scheme instead of `http(s)`
Will validate later again

**Comment by jrieken** [comment] 2021-04-22 14:23
You don't need this for preloads but for other things.

/cc @mjbvz for further insides and correction. We use the [`asWebviewUri`](https://github.com/microsoft/vscode/blob/5390ec0e7c3ce7edece26771223c45d2c45dd70c/src/vs/workbench/api/common/extHostNotebookKernels.ts#L173)-util and for that the controller-handle as uuid

**Comment by DonJayamanne** [comment] 2021-04-22 14:26
> don't need this for preloads but for other things

Fyi, they were not preloads. It was as part of the renderers (ipywidgets)

**Comment by DonJayamanne** [comment] 2021-04-24 20:28
Fixing this https://github.com/microsoft/vscode/issues/121981 seems to have resolved this issue as well.
Please feel free to close this issue.

**Comment by jrieken** [comment] 2021-04-26 06:55
Yeah, closing as dup

/duplicate of #121981

**Closed** 2021-04-26 06:55 UTC
Labels: *duplicate, needs more info, notebook-kernel
