### ISSUE TITLE
Vscode unresponsive when updating npm dependencies(many)

### ISSUE THREAD

**Issue by sfabriece** [Microsoft/vscode#18247] opened 2017-01-07 04:46 UTC
ps: usually the problem doesn't occur if the update is small. Meaning installing one or two packages.

After vscode becomes unresponsive, the only way to reload is to wait for the prompt or kill the vscode process.

- VSCode Version:
1.8.1
- OS Version:
Windows 10

Steps to Reproduce:

find a project with many dependencies.
Open vscode
install the dependencies while code is running

this freezes code and requires a reload after a while

**Comment by sandy081** [comment] 2017-01-09 09:01
@sfabriece I do not understand when you are getting into this state. Can you please update steps in detail like what do you mean running angular-cli project?

**Comment by sfabriece** [comment] 2017-01-09 09:13
@sandy081 updated. Hope it is more clear.

**Comment by sandy081** [comment] 2017-01-09 09:14
@sfabriece I assume you are using integrated terminal in VS Code to install dependencies?

**Comment by sfabriece** [comment] 2017-01-09 10:06
@sandy081 no, I'm using external git-bash to install the dependencies.

**Comment by sandy081** [comment] 2017-01-09 10:20
Can you please try to reproduce by disabling all extensions. There is a command (Search for Disable all installed.. ) in the command pallette to disable all extensions.

- Is this running inside a VM?
- Also profile your CPU to get some information

To create a CPU profile using developer tools in VS Code:
    * select Help > Toggle Developer Tools
    * click on Profiles
    * click the start button
    * do whatever you need to do to get the CPU spin high
    * wait for some time (10-20 seconds should be enough)
    * stop the profiling
    * click the save button and attach the output file to this issue

**Comment by sfabriece** [comment] 2017-01-10 08:33
I can confirm that vscode still requires a reload with extensitions disabled. Working on the cpu profile next.

**Comment by sfabriece** [comment] 2017-01-10 08:43
@sandy081 I've attached the CPU profile. I renamed it to `.txt` to be able to upload it.
[CPU-profile.txt](https://github.com/Microsoft/vscode/files/695605/CPU-profile.txt)

**Comment by sandy081** [comment] 2017-01-10 10:49
@sfabriece Since you are running npm install outside VS Code, I am guessing that your CPU is being occupied mostly by the npm process. Can you check your CPU activity while running npm install and also how active is your system and other applications during this? Can you also provide your system configuration.

Thanks

**Comment by sfabriece** [comment] 2017-01-10 11:23
@sandy081 what exactly do you mean by system configuration?

**Comment by sandy081** [comment] 2017-01-10 11:25
I mean CPU and memory configuration

**Comment by WalterLeinert** [comment] 2017-01-11 11:52
Hi, I have the same problem since several days after installing several extensions. When disabling all extensions no freeze occurs. I will try to find the extension causing the freeze.

**Comment by WalterLeinert** [comment] 2017-01-11 11:57
For me it's the extension "Auto Import" https://marketplace.visualstudio.com/items?itemName=steoates.autoimport; after deactivating it I have no more freezes.

There is one reported issue concerning "freeze". I will (re)open an issue.

Regards, Walter

**Comment by dbaeumer** [comment] 2017-01-16 10:58
@sfabriece I assume you have a JS or TS project. Do you exclude the node_modules folder in the tsconfig / jsconfig.json file.

**Comment by dbaeumer** [comment] 2017-01-23 08:30
The problem with the auto importer is known. 

@sfabriece without any additional information or a setup that demonstrates the problem it is very hard to track this down. I still assume that the node_modules folder is not correctly excluded. 

I will close the issue for now. If additional information is available we will reopen the issue.

**Closed by dbaeumer** 2017-01-23 08:30 UTC
Labels: freeze-slow-crash, needs more info
