### ISSUE TITLE
the VCS is restarting at any time

### ISSUE THREAD

**Issue by danilors** [Microsoft/vscode#35995] opened 2017-10-10 18:01 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-beautifier|mic|1.7.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-11 10:22
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by egamma** [comment] 2017-10-12 09:26
Closing, please reopen with more information.

**Closed by egamma** 2017-10-12 09:26 UTC
Labels: needs more info
