### ISSUE TITLE
View > Explorer, keyboard shortcut not working (Mac)

### ISSUE THREAD

**Issue by clozach** [Microsoft/vscode#18060] opened 2017-01-03 22:23 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.2.0|
|vscode-html-to-elm|Rubymaniac|0.0.2|
|elm-format|abadi199|0.1.0|
|elm|sbrink|0.8.3|
|vim|vscodevim|0.4.10|

---

Steps to Reproduce:

1. Navigate away from Explorer view by clicking on, say, Extensions icon, or typing `shift+cmd+x`
2. Attempt to navigate back to Explorer by typing `shift+cmd+e` as indicated in keybindings.json
   No reaction visible in menu or in current view
3. Open keyboard shortcuts with `cmd+k cmd+s`
4. Customize the View > Explorer shortcut, e.g., `{ "key": "shift+ctrl+e",           "command": "workbench.view.explorer" }`
5. Try the new shortcut, e.g., `shift+ctrl+e`
   > View switches to Explorer, proving that View > Explorer can be accessed with a keyboard shortcut, just not `shift+cmd+e`.
6. Open System Preferences > Keyboard > Shortcuts. Verify that there are no system-level conflicts for ⇧⌘E.

**Comment by slowmove** [comment] 2017-01-03 22:38
It works fine for me though. Tried to disable all the extensions?

**Comment by sandy081** [comment] 2017-01-04 09:41
It also works for me. Can you please try with above suggestion?

**Comment by mjbvz** [comment] 2017-01-12 23:47
Closing as we are unable to reproduce this issue.

@clozach If you are still seeing this after disabling extensions, please let us know

Thanks

**Closed by mjbvz** 2017-01-12 23:47 UTC
Labels: needs more info

**Comment by jhildenbiddle** [comment] 2017-05-07 01:55
Apologies for reviving an closed thread, but I also ran into an issue with the CMD-SHIFT-E shortcut not displaying the Explorer pane. Turns out there was a hotkey conflict with another app I use (Boom 2).

@clozach -- The hotkey conflict may not be displayed in the System Preferences -> Keyboard pane. Try closing other apps (including menubar apps) until the default CMD+SHIFT+E hotkey works in VSCode.

Good luck!

**Comment by clozach** [comment] 2017-05-07 20:02
@jhildenbiddle I also have Boom 2 installed, and never noticed before now that there's a subtle gray-on-gray "Hotkeys" button in that app. Thanks for solving the mystery!

If I used VS Code consistently, I'd now go on to ask why on earth the _Show Explorer_ shortcut doesn't toggle the explorer, but instead just toggles focus. As it is, I never managed the switch from Atom, so I'll leave it up to actual VS Code users to raise, assuming any of you find that behavior as confusing as I do. ;)

**Comment by verpixelt** [comment] 2017-11-16 10:23
Ufff thanks a lot for the Boom 2 hint. Using Boom 3D and had the same issue. Would have never suspected this app to be the trouble maker. That saved me a lot time 🙏
