### ISSUE TITLE
Allow debug config providers to resolve variables (like ${workspaceFolder})

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#49515] opened 2018-05-09 09:09 UTC
I have logic in my DebugConfigurationProvider to invoke the correct debugger based on the users project. To detect the project I have to look in the `cwd` at some files.

If the user doesn't set a `cwd` I just take the current files workspace root and all is good. However, if the users sets the `cwd` with a variable in it (like `${workspaceRoot}`) I can't look in the files unless I resolve this variable myself.

I think there are many variables that are supported here so it doesn't make sense to resolve them myself here; I think we need a way to have Code resolve them using the same logic it usually would when passing them to a DA.

**Comment by isidorn** [comment] 2018-05-09 09:16
@DanTup if I understand correctly you would like the vscode api to expose resolving variables, since currently the debug configuration providers are invoked before the variables get resovled by vscode and that seems to be the issue for you?

**Comment by isidorn** [comment] 2018-05-09 09:35
So for me it seems two solutions would work for you 
1. VSCode exposes API to resolve variables
2. VSCode first subsitutes all variables it knows then calls the debug config provider and then resolves again

I believe option 1 is not on the horizon.
fyi @weinand

**Comment by DanTup** [comment] 2018-05-09 09:44
Option 2 seems good enough for me; and probably wouldn't even require any changes on my site to fix the bugs we're hitting :-)

**Comment by isidorn** [comment] 2018-05-09 09:47
@DanTup not sure if that might provide some unexpected behavior for other debug adapters. Though it makes sense for me.
Let's see what @weinand thinks about this

**Comment by weinand** [comment] 2018-05-09 10:47
@DanTup the DA sees the resolved launch config. Why isn't that sufficient?

**Comment by DanTup** [comment] 2018-05-09 10:54
@weinand I use logic in the `resolve` method to decide which DA to invoke (you suggested this a while ago to handle the different types of project), so I need to know the real value of things like `cwd` before invoking the DA.

**Comment by weinand** [comment] 2018-05-09 11:09
@DanTup I see...
I suggest that you work around that limitation on your side for now. The only variable that makes sense for `cwd` is `${workspaceFolder}` and you have access to its value. 

@isidorn your option 2 breaks every extension that relies on unresolved variables. So this is not an option.

**Comment by isidorn** [comment] 2018-05-09 11:58
Closing then as you can workaorund on your extension end and the two options are out of scope for now

**Closed by isidorn** 2018-05-09 11:58 UTC
Labels: debug, feature-request, under-discussion

**Comment by DanTup** [comment] 2018-05-09 14:07
@weinand That was one example; we also use `program` and that can contain `${file}`. I'll hard-code the ones I can think of for now, but it does seem like there should be a way to handle this?

**Comment by DanTup** [comment] 2018-05-09 14:12
Also, can you confirm that `cwd` should have variables replaced too? In my DA I'm seeing it unresolved (I'm launching the DA as a server inside the resolve method, this is coming through in the args):

<img width="493" alt="screen shot 2018-05-09 at 3 11 28 pm" src="https://user-images.githubusercontent.com/1078012/39819462-6c7e0a00-539b-11e8-82b2-90d1abba4937.png">

**Comment by isidorn** [comment] 2018-05-09 14:52
`cwd` should also have the variables replaced, since we do not treat any of the fields in the launch.json specially. In my simple example this works just fine

If you do not see it replaced please put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L694) and follow the rabitt hole

![screen shot 2018-05-09 at 16 49 53](https://user-images.githubusercontent.com/1926584/39821721-1bec814e-53a9-11e8-9b8e-06df74053cb5.png)

**Comment by DanTup** [comment] 2018-05-11 11:05
I wonder if it's related to using the DebugClient in the test-support package (or spawning the DA myself in the resolve method, in-process). In any case, I'm replacing the tokens manually now and have solved the original issues :-)
