### ISSUE TITLE
[bug] InsertNewLine not working

### ISSUE THREAD

**Issue by pando85** [microsoft/vscode#78797] opened 2019-08-09 12:56 UTC
- VSCode Version:
1.37.0
036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
x64

- OS Version: Linux 4.18.20-1

Steps to Reproduce:

1. Set setting files.insertFinalNewline to True
2. Create new file, add one char and save

Does this issue occur when all extensions are disabled?: Yes

Additional info: If combined with `editor.renderFinalNewline: True` it appears to work correctly.
I tested it with `wc -l <file>`

**Comment by gjsjohnmurray** [comment] 2019-08-09 14:28
@pando85 is this a duplicate of #77633 which you previously logged?

I reproduced what you describe, but AFAIK it's behaving as designed.

The file created in step 2 does contain a final newline when I check it directly. If I open it in VSCode when `editor.renderFinalNewline: false` it correctly doesn't show a line 2.

**Comment by octref** [comment] 2019-08-09 15:41
Seems to be duplicate of #77633.

**Closed by octref** 2019-08-09 15:41 UTC
Labels: *duplicate
