### ISSUE TITLE
Bug: Request vscode/content failed unexpectedly without providing any details

### ISSUE THREAD

**Issue by abdulkareemnalband** [microsoft/vscode#136220] opened 2021-11-01 13:31 UTC
Issue Type: <b>Bug</b>
unable to acquire json schema file for 
```json
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.11/MicrosoftTeams.schema.json"
}
```

```json
{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "768",
	"severity": 4,
	"message": "Unable to load schema from 'https://developer.microsoft.com/json-schemas/teams/v1.11/MicrosoftTeams.schema.json': Request vscode/content failed unexpectedly without providing any details.",
	"startLineNumber": 2,
	"startColumn": 16,
	"endLineNumber": 2,
	"endColumn": 101
}
```

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.27GB free)|
|Process Argv|D:\\repo\\Decisions.Manifests\\manifest.code-workspace --crash-reporter-id e76cb2d5-1b50-447a-a8e6-87a041605cab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.2
ng-template|Ang|12.2.2
angulardoc-vscode|Ang|6.1.3
vscode-pull-request-azdo|ank|0.0.25
meson|asa|1.3.0
vscode-tailwindcss|bra|0.5.10
yaml-symbols|Cro|0.1.1
mustache|daw|1.1.1
vscode-eslint|dba|2.2.2
vscode-dotnet-auto-attach|Den|1.1.1
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
html-in-template-string|enh|0.0.4
prettier-vscode|esb|9.0.0
copy-relative-path-and-line-numbers|ezf|0.3.1
vscode-firefox-debug|fir|2.9.4
vscode-jest-runner|fir|0.4.47
sort-json-array|fvc|3.0.1
todo-tree|Gru|0.0.214
generate-switch-case-for-enum-type|her|0.0.9
rest-client2|hum|0.24.5-alpha.1
plantuml|jeb|2.16.0
Angular2|joh|12.0.0
dotenv|mik|1.0.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-cosmosdb|ms-|0.18.1
csharp|ms-|1.23.16
vscode-edge-devtools|ms-|1.4.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
azure-account|ms-|0.9.9
vscode-typescript-tslint-plugin|ms-|1.3.3
copy-json-path|nid|0.2.0
angular-console|nrw|17.12.2
docthis|oou|0.8.2
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
LiveServer|rit|5.6.1
ngx-translate-zombies|sev|0.0.1
vscode-scss-formatter|sib|2.3.2
code-spell-checker|str|2.0.12
rest-book|tan|4.2.0
generate-translation|thi|0.0.10
html-preview-vscode|tht|0.2.5
vscode-json-stable-stringify|Tra|1.2.1
errorlens|use|3.4.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
clang-format|xav|1.9.0
html-css-class-completion|Zig|1.20.0

</details>

**Comment by aeschli** [comment] 2021-11-01 14:11
duplicate of #127769, fixed for October (1.62).

**Closed by aeschli** 2021-11-01 14:11 UTC
