### ISSUE TITLE
Cannot select text on vscode.dev on iPadOS

### ISSUE THREAD

**Issue by nigow** [microsoft/vscode#221626] opened 2024-07-13 10:57 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1 (VSCode.dev)
- OS Version: iPadOS 17.5.1

Steps to Reproduce:

1. Open a file on vscode.dev
2. Double tap on a word

You can see that the cursor applies from and to the end of a word. The cursor is fixed at the same word (I tried to drag the cursor but it doesn’t extend at all)

https://github.com/user-attachments/assets/1e2731c0-58ad-47da-af39-aed3dcbb22a0

**Comment by TylerLeonhardt** [comment] 2024-12-19 05:51
This appears to be a duplicate of https://github.com/microsoft/vscode/issues/167151#issuecomment-2547453307 I also don't repro the original bug on the latest iPadOS

**Closed by TylerLeonhardt** 2024-12-19 05:51 UTC
Labels: ios-ipados
