### ISSUE TITLE
Problems Panel shows wrong number of diagnostics

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#71309] opened 2019-03-27 18:31 UTC
Version: 1.33.0-insider
Commit: 1afeb46cc4f2856ed6d0759fff85b13647c7ab83
Date: 2019-03-27T16:02:22.809Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

- Clone https://github.com/Microsoft/vscode-extension-samples/tree/master/helloworld-sample
- Run build task
- Delete `e` from `export function deactivate() {}`

Build task shows 1 error:

![image](https://user-images.githubusercontent.com/4033249/55102412-927b4200-5083-11e9-8368-9f18f643b955.png)

Problems Panel shows 2 and 3 errors:

![image](https://user-images.githubusercontent.com/4033249/55102467-ad4db680-5083-11e9-844b-2af85ee69298.png)

How is the 3 calculated?

**Comment by octref** [comment] 2019-03-27 18:33
In my development, my build task outputs 4 errors, I see only 2 in problems panel, but the number is 4:

![image](https://user-images.githubusercontent.com/4033249/55102657-26e5a480-5084-11e9-8edb-c9ab096c1381.png)

![image](https://user-images.githubusercontent.com/4033249/55102672-2ea54900-5084-11e9-9f50-acc744de0b4a.png)

**Comment by sandy081** [comment] 2019-03-27 19:51
Duplicate of #71165

**Closed** 2019-03-27 19:51 UTC
Labels: *duplicate
