### ISSUE TITLE
intellisense doesn't work in html

### ISSUE THREAD

**Issue by cool-delete** [microsoft/vscode#121031] opened 2021-04-11 00:07 UTC
- VS Code Version:1.55.1
- OS Version:wsl2

Steps to Reproduce:

1.Complete the writing of TS file
2.hover class say any

Does this issue occur when all extensions are disabled?: Yes/No
yes

![image](https://user-images.githubusercontent.com/13638610/114287829-cffd6d00-9a9c-11eb-8ab7-7e7440e11d7f.png)

**Comment by aeschli** [comment] 2021-04-12 13:52
The HTML tooling does not follow imports to other files (It is only 'single file')
Duplicate of  #114115

**Closed by aeschli** 2021-04-12 13:52 UTC
Labels: new release

**Comment by cool-delete** [comment] 2021-04-14 03:04
@aeschli 
i not sure what you mean
If I type `myPromise ` in the html file, will vscode prompt the method of this object, such as the then method?

**Comment by aeschli** [comment] 2021-04-14 10:24
The HTML language tooling only looks at what's defined in he html file, it doesn't follow the `script src='./MyPromise.js'` reference.
It's a limitation of our HTML tooling.

**Comment by cool-delete** [comment] 2021-04-14 13:55
ok...this is a terrible feature.😥

**Comment by aeschli** [comment] 2021-04-14 15:25
Not a feature, just a limitation  :-)
