### ISSUE TITLE
maximize panel tray ui issue

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode#92574] opened 2020-03-12 12:29 UTC
- VSCode Version: 1.43.0
- OS Version: Win10 1909

Steps to Reproduce:

1. Open release notes
2. Maximize panel tray

![image](https://user-images.githubusercontent.com/14079228/76521419-30098600-643b-11ea-9d40-5ac9aa7e963e.png)

![image](https://user-images.githubusercontent.com/14079228/76521342-0a7c7c80-643b-11ea-8844-cdf3c7718b32.png)

I'm thinking the semi-circle is this:

![image](https://user-images.githubusercontent.com/14079228/76521350-0cded680-643b-11ea-801a-68e0969c1a6b.png)

![maximize panel tray ui issue](https://user-images.githubusercontent.com/14079228/76521359-11a38a80-643b-11ea-94a7-bc452eaeda7a.gif)

Related issue: https://github.com/microsoft/vscode-java-test/issues/958

It really shows up on that extension:

![image](https://user-images.githubusercontent.com/14079228/76521492-50d1db80-643b-11ea-8171-c1b9ed0f8bd6.png)

And @jdneo [isn't able to reproduce](https://github.com/microsoft/vscode-java-test/issues/958#issuecomment-597396943) it on a MacOS.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-03-13 19:09
Confirmed that I can't repo this on MacOS in VS Code 1.44

**Comment by mjbvz** [comment] 2020-04-14 22:37
Duplicate of #94805 I believe.

Please test the next VS Code insiders build and let me know if you still see this issue

**Closed by mjbvz** 2020-04-14 22:37 UTC
Labels: bug, webview, windows

**Comment by spottedmahn** [comment] 2020-04-15 01:01
>Duplicate of #94805 I believe.

Technically #94805 is a duplicate 😉 but glad it's fixed, thanks!
