### ISSUE TITLE
`terminal.integrated.defaultProfile.linux` does not launch the default terminal profile after startup

### ISSUE THREAD

**Issue by krokyk** [microsoft/vscode#131869] opened 2021-08-29 22:43 UTC
Does this issue occur when all extensions are disabled?: I have only Remote - WSL extension enabled

- VS Code Version: 1.60.0-insider (system setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:
I have VSCode Insider installed in Windows and running remotely in WSL 1

I have this in my code-workspace file:
```
{
  "folders": [
    {
        "path": "../project1"
      },
      {
        "path": "../project2"
      }
  ],
  "settings": {
    "terminal.integrated.profiles.linux": {
        "custom-bash": {
            "path": "bash",
            "icon": "terminal-bash",
            "args": [ "--init-file", "${workspaceFolder}/init.sh" ],
            "overrideName": true
        }
    },
    "terminal.integrated.defaultProfile.linux": "custom-bash",
    "terminal.integrated.cwd": "${workspaceFolder}/../project2"
  }
}
```

1. Have at least 1 terminal open in VSCode
2. Close the VSCode
3. Launch the same workspace again

I expect that when the VSCode is started, the terminal window that is opened automatically (because it's remembered from the last session?) will run the default profile, but that is not the case. It runs bash instead of custom-bash as defined in my workspace. The `terminal.integrated.cwd` option is respected, though. I have seen similar issue #123188 for windows default profile. Can this still be a problem?
![image](https://user-images.githubusercontent.com/15148711/131267329-8b519aa2-0189-4874-a840-38246f90642c.png)

When I then manually open a new terminal, it correctly runs the default profile I have defined. This can be seen also from the correct profile name showing in the list of shells and also from the custom messages contained in `init.sh` file this bash is initialized with.
![image](https://user-images.githubusercontent.com/15148711/131267405-85cec5f9-d5d6-45a8-a00e-91e99040186f.png)

I created a github repo with my test case for 1.60.0 Insider build [here](https://github.com/krokyk/vscode-terminal-testcase/tree/main/test-1.60.0) if you want to check

**Comment by IllusionMH** [comment] 2021-08-30 12:24
/duplicate of #128763 (reproducible not only for remote)

**Closed** 2021-08-30 12:24 UTC
Labels: *duplicate
