### ISSUE TITLE
Windows maximize doesn't work

### ISSUE THREAD

**Issue by Hamzeh75** [microsoft/vscode#84910] opened 2019-11-15 12:21 UTC
My windows 10 version is 1909, I updated vs code today and I have this problem.
Windows maximize doesn't work.
It won't restore the window dimensions when I click to Maximize button, it just makes the window bigger and it doesn't work again at all, even the icon won't change, but when I drag the window to top it will work properly.
Please check the screenshots.

![image](https://user-images.githubusercontent.com/22435603/68942853-cf38ac80-07be-11ea-883a-299f3a943b19.png)
![image](https://user-images.githubusercontent.com/22435603/68942874-dbbd0500-07be-11ea-96d8-6c00ff9405fd.png)
![image](https://user-images.githubusercontent.com/22435603/68943402-5e928f80-07c0-11ea-9524-22475431faeb.png)
![image](https://user-images.githubusercontent.com/22435603/68943420-67836100-07c0-11ea-8da1-4d9e85e1f899.png)

**Comment by IllusionMH** [comment] 2019-11-15 13:18
Probably duplicate of #84343 (as mentioned in https://github.com/microsoft/vscode/issues/84798#issuecomment-554131186)

Could you try Insiders build (https://code.visualstudio.com/insiders/) to see if this issue is fixed there? 
See https://github.com/microsoft/vscode/issues/84343#issuecomment-554202848

**Closed** 2019-11-15 16:21 UTC
Labels: *duplicate
