### ISSUE TITLE
Add a setting to disable mnemonics in the menu so that Alt+F can be bound

### ISSUE THREAD

**Issue by blackmiaool** [Microsoft/vscode#17962] opened 2016-12-31 13:29 UTC
- VSCode Version:
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version:
ubuntu 14.04LTS
Steps to Reproduce:

1. Install plugin "Emacs"
2. Press Alt+f and find the "File" menu is triggered. (expect: Alt+F	Move cursor to previous word)

It contains 
```
{ "key": "alt+f",                 "command": "emacs.cursorWordRight",
                                     "when": "editorTextFocus" },
```
in keybinding.json

I think it's not the plugin's problem. Any advice?

**Comment by rebornix** [comment] 2017-01-01 05:03
@blackmiaool if Code works without this extension, I'll suggest to start investigation from that extension :)

**Comment by blackmiaool** [comment] 2017-01-01 06:12
@rebornix   I tried to disable the plugin and edited config file like this:
// Place your key bindings in this file to overwrite the defaults
```
[
    {
        "key": "alt+f",
        "command": "cursorWordStartLeft",
        "when": "editorTextFocus"
    },
    {
        "key": "alt+b",
        "command": "cursorWordStartLeft",
        "when": "editorTextFocus"
    }
]
```
Then I restarted the vscode and tried them.
I found that the alt+b worked well, and the alt+f triggered the menu "File".

**Comment by rebornix** [comment] 2017-01-02 16:25
`alt+f` is a system keybinding for File Menu I'm afraid.

**Comment by Tyriar** [comment] 2017-01-02 16:56
@alexandrudima do we support overriding the alt menu shortcuts?

**Comment by jaseonline** [comment] 2017-01-03 08:43
@Tyriar Do you mean you want to override the system ALT keybindings? If that's the case, I'm not sure why you would want to break expected behavior. Don't forget that decisions made here should not reflect solely the opinions of the people working on the software, but also those of the end users - many of whom still rely on the system keybindings.

**Comment by jaseonline** [comment] 2017-01-03 08:47
What I would suggest is that if an extension is installed and enabled which requires a certain key binding that is already being used by the system, one solution would be to override the system key binding with that of the enabled extension (at-least that way the user is more likely to be expecting that sort of behavior).

**Comment by Tyriar** [comment] 2017-01-03 17:41
@jaseonline I'm just asking the feature owner what the expected behavior is.

**Comment by jaseonline** [comment] 2017-01-04 04:43
@Tyriar Oh sorry, my bad. I misunderstood.

**Comment by alexandrudima** [comment] 2017-01-21 19:04
It appears it is not possible to bind anything to `alt+f` on Ubuntu because it does not reach the renderer process, the reason being that the `File` menu uses `F` as a mnemonic.

@bpasero can decide if he wants to make menu mnemonics configurable in any way to allow for `alt+f` to reach the renderer process.

https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L298

**Comment by yogan** [comment] 2017-04-07 08:07
Any idea when/if this setting will be merged?

**Comment by bpasero** [comment] 2017-05-08 05:55
Will be available for May.

**Closed** 2017-05-08 05:54 UTC
Labels: feature-request, workbench

**Comment by blackmiaool** [comment] 2017-06-11 03:43
@bpasero   1.13 is released. Does it contain this feature? How can we achieve it now? I tried the [https://marketplace.visualstudio.com/items?itemName=hiro-sun.vscode-emacs](emacs plugin), it still doesn't work (alt-f triggers file menu).

**Comment by bpasero** [comment] 2017-06-11 04:19
@blackmiaool https://code.visualstudio.com/updates/v1_13#_disable-menu-bar-mnemonics
