### ISSUE TITLE
"Renaming files is currently not supported" when renaming a reference on Linux

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#148298] opened 2022-04-27 18:04 UTC
Testing #147738

While discovering https://github.com/microsoft/vscode/issues/148297 I noticed a bug when renaming a markdown reference on Linux.

On Linux (Ubuntu) with the following file:
```
[ref2]

[yes][ref2]

[ref2]: /README.md#deployment
```

Attempt to rename `ref2` on the 2nd line there (`[yes][ref2]`)

Expected:

To be able to rename `ref2` to something else that would update all references

Actual:

"Renaming files is currently not supported"

**Comment by mjbvz** [comment] 2022-04-30 21:08
Are you sure you tested on the latest insiders? This message was from an older build and rename should now work on all platforms

**Comment by mjbvz** [comment] 2022-04-30 21:09
Actually a duplicate of #148301 (same root cause)

**Closed by mjbvz** 2022-04-30 21:09 UTC
