### ISSUE TITLE
Copying/Cutting/Splitting a cell with an image attachment loses the image

### ISSUE THREAD

**Issue by joelostblom** [microsoft/vscode#209455] opened 2024-04-03 04:05 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

If I paste an image into a markdown cell in a notebook, it will be inserted as an image attachment. If I cut/copy/split a cell with such an attachment, the file is lost and it shows up as a broken image after pasting (I'm hitting the shortcuts for copy and paste in the videos below).

https://github.com/microsoft/vscode-jupyter/assets/4560057/02adf32c-c35d-430c-a366-358ccb58e970

Things work as expected in jupyterlab:

https://github.com/microsoft/vscode-jupyter/assets/4560057/fbff4afa-6c9a-4d9a-8c09-3fd9d533f2ec

### VS Code Version

Version: 1.88.0-insider

### Jupyter Extension Version

2024.2.0

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment] 2024-12-12 22:46
/duplicate of https://github.com/microsoft/vscode/issues/200898

**Closed by rebornix** 2024-12-12 22:46 UTC
Labels: bug, notebook-markdown
