### ISSUE TITLE
[ISSUE] Syntax highlighting issue

### ISSUE THREAD

**Issue by Nigelrex** [microsoft/vscode#146028] opened 2022-03-25 06:57 UTC
Issue Type: <b>Bug</b>

create a new class in javascript
```js
// This looks fine till now
class someClass {
  constructor(){}
}
// require that class here
// the issue is below
new someClass();
// this syntax highlighting of someClass looks like a function
```

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.72GB free)|
|Process Argv|--crash-reporter-id ba92e680-4743-4325-882b-39d76648bd58|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
Bookmarks|ale|13.2.4
project-manager|ale|12.5.0
vscode-tailwindcss|bra|0.7.7
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
regex|chr|0.4.0
vscode-github-actions|csc|0.22.0
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
vscode-deno|den|3.11.0
javascript-ejs-support|Dig|1.3.1
githistory|don|0.6.19
gitlens|eam|12.0.5
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
syntax-highlighter|evg|0.5.0
git-project-manager|fel|1.8.2
code-runner|for|0.11.7
codespaces|Git|1.5.7
vscode-pull-request-github|Git|0.38.1
vscode-postfix-ts|ipa|1.9.4
vscode-env|Iro|0.1.0
vscode-git-add-and-commit|iva|2.1.1
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
vscode-live-frame|jev|0.1.1
vscode-github|Kni|0.30.7
vscode-exec-node|mir|0.5.4
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5449
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.14.1
platformio-ide|pla|2.4.3
sqlite-viewer|qwt|0.1.5
vscode-thunder-client|ran|1.14.0
java|red|1.4.0
LiveServer|rit|5.7.5
yet-another-discord-presence|Sat|1.5.4
vscode-standard|sta|2.1.0
html-preview-vscode|tht|0.2.5
errorlens|use|3.4.2
vscodeintellicode|Vis|1.2.17
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.1
vscode-maven|vsc|0.35.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
livereload|zii|0.2.5
linkerscript|Zix|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid1:30447480
pynewfile477:30450038

```

</details>

**Comment by Nigelrex** [comment] 2022-03-25 07:00
The same happens with the web version with no extentions

**Comment by yume-chan** [comment] 2022-03-25 07:52
Desktop: caused by https://marketplace.visualstudio.com/items?itemName=evgeniypeshkov.syntax-highlighter

Web: not sure why semantic highlight was not enabled.

**Comment by Nigelrex** [comment] 2022-03-25 07:53
no i just installed to check if that persists
but still i had the issue without it also

**Comment by yume-chan** [comment] 2022-03-25 08:00
Without:

![image](https://user-images.githubusercontent.com/1330321/160078406-075ae4ef-0c67-49b3-98d4-0b9ce1ddf224.png)

With:

![image](https://user-images.githubusercontent.com/1330321/160078663-1208343d-de66-4a12-96b5-4b8b4c6186bc.png)

Version:

```
Version: 1.66.0-insider
Commit: 2eebd2a0159af379057a58c8bcb519f95bfd6328
Date: 2022-03-23T05:15:24.304Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.2.0
```

---

Then disable all extensions and try again.

**Comment by Nigelrex** [comment] 2022-03-25 08:00
I tries that too, it happens even in the web version without extentions

**Comment by Nigelrex** [comment] 2022-03-25 08:00
![image](https://user-images.githubusercontent.com/75080457/160079122-5bc44337-6eaf-4977-9e8c-bc714e508cc8.png)

**Comment by Nigelrex** [comment] 2022-03-25 08:01
I never used that extension before, I just installed it to see if I can use it as a alternative to this issue

**Comment by Nigelrex** [comment] 2022-03-25 08:13
There is no setting like that in my `settings.json` file.

**Comment by Nigelrex** [comment] 2022-03-25 08:14
Sorry for sending this huge wall
`settings.json`
```json
{
	"better-comments.highlightPlainText": true,
	"bookmarks.saveBookmarksInProject": true,
	"color-highlight.matchWords": true,
	"editor.quickSuggestions": {
		"other": true,
		"comments": true,
		"strings": true
	},
	"editor.autoClosingDelete": "always",
	"editor.bracketPairColorization.enabled": true,
	"editor.matchBrackets": "always",
	"editor.guides.highlightActiveBracketPair": true,
	"editor.autoClosingBrackets": "always",
	"workbench.editor.decorations.colors": true,
	"editor.cursorBlinking": "smooth",
	"editor.cursorSmoothCaretAnimation": true,
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"editor.suggest.showWords": false,
	"editor.hideCursorInOverviewRuler": true,
	"editor.smoothScrolling": true,
	"editor.stablePeek": true,
	"editor.formatOnPaste": true,
	"editor.formatOnType": true,
	"editor.fontLigatures": true,
	"editor.fontFamily": "Cascadia Code",
	"diffEditor.codeLens": true,
	"editor.suggest.preview": true,
	"editor.suggest.snippetsPreventQuickSuggestions": false,
	"editor.formatOnSave": true,
	"editor.quickSuggestionsDelay": 0,
	"editor.wordBasedSuggestions": false,
	"editor.guides.bracketPairs": true,
	"editor.wordWrap": "on",
	"editor.parameterHints.enabled": true,
	"editor.codeActionsOnSave": {
		"source.organizeImports": true
	},
	"editor.linkedEditing": true,
	"editor.parameterHints.cycle": true,
	"editor.tabCompletion": "on",
	"editor.suggestSelection": "first",
	"editor.inlineSuggest.enabled": true,
	"editor.unicodeHighlight.allowedCharacters": {
		"ノ": true
	},
	"editor.guides.bracketPairsHorizontal": true,
	"editor.autoClosingOvertype": "always",
	"editor.autoClosingQuotes": "always",
	"editor.minimap.maxColumn": 60,
	"editor.colorDecorators": true,
	"editor.suggest.showCustomcolors": true,
	"eslint.alwaysShowStatus": true,
	"files.autoGuessEncoding": true,
	"files.insertFinalNewline": true,
	"files.trimFinalNewlines": true,
	"files.autoSave": "afterDelay",
	"github.copilot.enable": {
		"*": true,
		"yaml": true,
		"plaintext": true,
		"markdown": true,
		"enabled": true
	},
	"workbench.list.smoothScrolling": true,
	"workbench.view.alwaysShowHeaderActions": true,
	"workbench.editor.autoLockGroups": {
		"default": true,
		"sqlite-viewer.option": true,
		"workbench.input.interactive": true,
		"interactive": true,
		"workbench.editorinputs.searchEditorInput": true,
		"imagePreview.previewEditor": true,
		"vscode.markdown.preview.editor": true,
		"gitlens.rebase": true,
		"sqlite-viewer.view": true,
		"terminalEditor": true,
		"mainThreadWebview-markdown.preview": true
	},
	"workbench.experimental.layoutControl.enabled": true,
	"workbench.enableExperiments": true,
	"window.autoDetectColorScheme": true,
	"workbench.editor.highlightModifiedTabs": true,
	"search.quickOpen.includeSymbols": true,
	"search.showLineNumbers": true,
	"search.smartCase": true,
	"search.useGlobalIgnoreFiles": true,
	"terminal.integrated.cursorBlinking": true,
	"terminal.integrated.copyOnSelection": true,
	"terminal.integrated.enableBell": true,
	"terminal.integrated.cursorStyle": "line",
	"terminal.integrated.profiles.windows": {
		"Command Prompt": {
			"path": [
				"${env:windir}\\Sysnative\\cmd.exe",
				"${env:windir}\\System32\\cmd.exe"
			],
			"args": [],
			"icon": "terminal-cmd"
		},
		"Git Bash": {
			"source": "Git Bash"
		}
	},
	"terminal.integrated.defaultProfile.windows": "Command Prompt",
	"typescript.inlayHints.parameterNames.enabled": "all",
	"npm-intellisense.packageSubfoldersIntellisense": true,
	"npm-intellisense.showBuildInLibs": true,
	"npm-intellisense.scanDevDependencies": true,
	"prettier.printWidth": 60,
	"prettier.trailingComma": "all",
	"prettier.useTabs": true,
	"prettier.vueIndentScriptAndStyle": true,
	"prettier.withNodeModules": true,
	"security.workspace.trust.untrustedFiles": "open",
	"workbench.iconTheme": "material-icon-theme",
	"standard.autoFixOnSave": true,
	"standard.enableGlobally": true,
	"workbench.quickOpen.preserveInput": true,
	"path-intellisense.extensionOnImport": true,
	"path-intellisense.ignoreTsConfigBaseUrl": true,
	"path-intellisense.showHiddenFiles": true,
	"RPC.problemsText": "- {count} problems found in {workspace}",
	"RPC.debuggingText": "Debugging {file} in {workspace}",
	"RPC.hideFiles": [".env"],
	"npm-intellisense.importQuotes": "\"",
	"javascript.format.insertSpaceBeforeFunctionParenthesis": true,
	"standard.usePackageJson": true,
	"standard.enable": false,
	"javascript.format.insertSpaceAfterConstructor": true,
	"javascript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": true,
	"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true,
	"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,
	"javascript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": true,
	"javascript.referencesCodeLens.enabled": true,
	"javascript.suggest.completeFunctionCalls": true,
	"javascript.referencesCodeLens.showOnAllFunctions": true,
	"typescript.format.insertSpaceAfterConstructor": true,
	"typescript.referencesCodeLens.enabled": true,
	"typescript.suggest.completeFunctionCalls": true,
	"typescript.referencesCodeLens.showOnAllFunctions": true,
	"terminal.integrated.allowMnemonics": true,
	"task.quickOpen.showAll": true,
	"problems.showCurrentInStatus": true,
	"[cpp]": {
		"editor.defaultFormatter": "ms-vscode.cpptools"
	},
	"git.enableSmartCommit": true,
	"git.confirmSync": false,
	"javascript.updateImportsOnFileMove.enabled": "always",
	"files.trimTrailingWhitespace": true,
	"github.copilot.advanced": {
		"enabled": true,
		"enable_on_save": true,
		"enable_on_open": true,
		"enable_on_hover": true,
		"enable_on_selection": true,
		"enable_on_type": true,
		"enable_on_insert": true
	},
	"github.copilot.inlineSuggest.enable": true,
	"editor.minimap.scale": 2,
	"liveFrame.title": "Nigelrex's Webpage Preview",
	"liveFrame.url": "http://localhost:3000",
	"liveFrame.pane": "Active",
	"liveServer.settings.donotVerifyTags": true,
	"liveServer.settings.useLocalIp": true,
	"thunder-client.codeSnippetLanguage": "js-fetch",
	"liveshare.launcherClient": "visualStudioCode",
	"liveshare.accessibility.accessibilityFeaturesEnabled": true,
	"liveshare.accessibility.voice": "en-US-Michelle",
	"liveshare.alwaysFollowHost": true,
	"liveshare.guestApprovalRequired": true,
	"liveshare.presence": true,
	"liveshare.publishWorkspaceInfo": true,
	"editor.codeLensFontFamily": "Cascadia Code",
	"editor.definitionLinkOpensInPeek": true,
	"workbench.editor.enablePreviewFromCodeNavigation": true,
	"workbench.editor.enablePreviewFromQuickOpen": true,
	"terminal.integrated.fontFamily": "Cascadia Code",
	"remote.localPortHost": "allInterfaces",
	"bookmarks.useWorkaroundForFormatters": true,
	"RPC.idleText": "Idle for many centuries",
	"[python]": {
		"editor.defaultFormatter": "ms-python.python"
	},
	"go.autocompleteUnimportedPackages": true,
	"color-highlight.markerType": "foreground",
	"color-highlight.matchRgbWithNoFunction": true,
	"debug.console.acceptSuggestionOnEnter": "on",
	"explorer.experimental.fileNesting.enabled": true,
	"window.newWindowDimensions": "maximized",
	"inlineSQL.dbDriver": "mysql",
	"bookmarks.sideBar.expanded": true,
	"vsintellicode.features.apiExamples": "enabled",
	"deno.suggest.autoImports": false,
	"deno.suggest.names": false,
	"deno.suggest.paths": false,
	"editor.suggest.shareSuggestSelections": true,
	"javascript.suggest.paths": false
}
```

**Comment by yume-chan** [comment] 2022-03-25 08:20
Can you try with `vscode-deno` disabled?

**Comment by Nigelrex** [comment] 2022-03-25 08:22
yep problem fixed!
Thanks

**Comment by yume-chan** [comment] 2022-03-25 08:22
Duplicate of denoland/vscode_deno#486

**Closed by yume-chan** 2022-03-25 08:22 UTC
