### ISSUE TITLE
Theme color for minimap decorations doesn't work?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#78238] opened 2019-07-31 00:35 UTC
Testing #78001

Is this right? It doesn't seem to have any effect.
![image](https://user-images.githubusercontent.com/323878/62174853-3a35a480-b2f0-11e9-8641-8ec5935debcf.png)

**Comment by RMacfarlane** [comment] 2019-10-07 18:11
Duplicate of https://github.com/microsoft/vscode/issues/78398

**Closed by RMacfarlane** 2019-10-07 18:11 UTC
Labels: editor-minimap
