### ISSUE TITLE
The built in bracket pair colorizer does not work correctly with inline PHP code

### ISSUE THREAD

**Issue by db1996** [microsoft/vscode#176358] opened 2023-03-07 10:18 UTC
Type: <b>Bug</b>

Turn on bracket pair colorization.
I have guides -> bracket pairs and "highlight active bracket pair" turned on as well.

It works fine with these: ()
But all of these: {} are red. It's very distracting and looks like you have a bunch of errors in your file.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics          (6 x 2371)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.36GB (4.74GB free)|
|Process Argv|--file-uri file:///c%3A/Users/dylan/.vscode/workspaces/Git/Roan4x4.code-workspace --crash-reporter-id d9c6b7a8-ece8-4a3e-b007-47b19e9aa309|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-intelephense-client|bme|1.9.5
vscode-svgviewer|css|2.0.0
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|13.3.2
auto-rename-tag|for|0.1.10
jquery-snippets|Hri|1.0.0
ftp-simple|hum|0.7.6
php-doc-comment-vscode-plugin|imo|1.6.0
vscode-edit-csv|jan|0.7.3
remotefs|lix|0.0.16
vscode-autohotkey-plus-plus|mar|3.2.0
json|Mee|0.1.2
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-filesize|mkx|3.1.0
vscode-apache|mrm|1.2.0
powershell|ms-|2023.2.1
vscode-thunder-client|ran|2.5.0
vscode-xml|red|0.24.0
format-html-in-php|rif|1.7.0
pdf|tom|1.2.2
vscode-workspace-explorer|tom|1.5.0
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|12.2.0
markdown-all-in-one|yzh|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30669237
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30677850

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-07 10:31
Probably a duplicate of https://github.com/microsoft/vscode/issues/175797 for which a fix is already in Insiders and scheduled to appear in 1.76.1

**Closed** 2023-03-08 09:54 UTC
