### ISSUE TITLE
Pause action tooltip should specify which thread will get paused

### ISSUE THREAD

**Issue by rickwebiii** [Microsoft/vscode#34109] opened 2017-09-11 01:02 UTC
There's no way to distinguish a user request to pause a single thread from a request to pause the entire app. As such, my extension has to degrade to always pausing the whole app, even when the user requests to pause a single thread. If the user presses the global pause button, my debugger receives a threadId. I have no way to distinguish this from the user pausing that thread. PauseArguments shouldn't contain threadId when the user clicks the pause button, indicating to the extension their intent to pause the whole app.

- VSCode Version: 1.15
- OS Version: Any

Steps to Reproduce: 

1. Start a debugger
2. Click the pause button

Expected: The PauseArguments parameter to pauseRequest has no threadId or it's set to null to indicate I should pause the whole app.
Actual: The PauseArguments contains a threadId.

**Comment by isidorn** [comment] 2017-09-12 10:39
I disagree. Currently the whole UX is designed in such a way that is the slave of a focuse process / thread / frame. As such the top actions are always scoped to the current thread (example: step over will always only step over the current thread, not over all of them).
My point is that you should handle every pause as the pause the current thread, we currently do not support a Pause All action, which we could introduce if users ask for it.

Closing as designed
fyi @weinand

**Comment by rickwebiii** [comment] 2017-09-16 01:46
I was expecting the behavior to be like Visual Studio, where after launching or attaching to a process, the pause button in the debug toolbar (break all) pauses all threads. To pause individual threads, the user right clicks in the threads window and selects freeze and thaw.

Not to say that VSCode should behave like VS, but this behavior is surprising. Can you update the tooltip to be more specific as to what the pause button will pause? Also for clarification then, when the user clicks the pause button and has no thread selected in the left window, which thread should the user expect to pause when they click pause?

**Comment by isidorn** [comment] 2017-09-19 08:11
@rickwebiii I agree, we shuold upadate the tooltip to make this clearer

**Comment by isidorn** [comment] 2017-09-19 09:33
After looking into this the problem with the tooltip is that we cannot guess how an adapter is going to behave - if the thread id will be respect or if it will be totaly ignored and all threads will pause (e.g C# adapter).
Due to that I have decided to leave the tooltip as it is for now. But am open for suggestions

**Comment by rickwebiii** [comment] 2017-09-22 22:20
I was always under the impression this button should behave like VS's break all because you don't have to have a thread selected in order to press it. As a user, if I don't have a thread selected, I would expect it to pause the whole app.

If there isn't a thread selected, then which thread the debugger chooses to pause is arbitrary, which is why I was confused.

**Closed** 2017-11-17 15:57 UTC
Labels: *out-of-scope, debug, feature-request
