### ISSUE TITLE
css-language-features - server crashed, hanging vscode terminal shell and crashing webpack server

### ISSUE THREAD

**Issue by r3wt** [microsoft/vscode#76817] opened 2019-07-07 23:17 UTC
Issue Type: <b>Bug</b>

as i was writing some scss, the server crashed while i was typing `box-orient: vertical`. it briefly displayed a typeahead suggestion then crashed. the terminal is hanged and unresponsive, as is webpack server

code i was typing (note: box-orient is an invalid property name, and box is an invalid display value):
```
p.lg {
        display: box;
        box-orient: vertical;

}
```

```js
[Error - 6:12:45 PM] Error while computing completions for file:///e%3A/REDACTED/app/src/styles/layout.scss: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:622043
    at Array.filter (<anonymous>)
    at t.getTermProposals (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:621989)
    at t.e.getCompletionsForDeclarationValue (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:563877)
    at t.e.getCompletionsForExpression (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:573359)
    at t.e.doComplete (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:559045)
    at l.runSafe (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:98344)
    at Immediate.setImmediate [as _onImmediate] (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:139541)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
[Error - 6:13:02 PM] Error while computing completions for file:///e%3A/REDACTED/app/src/styles/layout.scss: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:622043
    at Array.filter (<anonymous>)
    at t.getTermProposals (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:621989)
    at t.e.getCompletionsForDeclarationValue (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:563877)
    at t.e.getCompletionsForExpression (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:573359)
    at t.e.doComplete (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:559045)
    at l.runSafe (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:98344)
    at Immediate.setImmediate [as _onImmediate] (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:139541)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
```

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.66GB free)|
|Process Argv|--folder-uri file:///e%3A/vid2o|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
aio-compiler|azt|2.0.0
php-debug|fel|1.13.0
php-pack|fel|1.0.2
twig-language-2|mbl|0.8.8
cpptools|ms-|0.24.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2019-07-08 10:40
duplicate of https://github.com/microsoft/vscode/issues/76572

**Closed by aeschli** 2019-07-08 10:40 UTC
Labels: new release
