### ISSUE TITLE
Debugger sometimes doesn't focus file in callstack when pausing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#66369] opened 2019-01-11 01:34 UTC
I've seen this from time to time for a while, I can't remember whether there was ever an issue about it. Sometimes I see it a few times in a row, if you never see it, maybe you can give me a debug pointer and I can try to catch it in action.

- Close all open files
- Hit a breakpoint
- See that the file opens, but no frame in the callstack is focused, and the line indicator is green instead of yellow

![image](https://user-images.githubusercontent.com/323878/51007848-09318600-14fe-11e9-88c2-1b6abcce9739.png)

**Comment by isidorn** [comment] 2019-01-11 09:57
First of all I love that you self-hosting on our stuff!
I did not see this.

We are fetching the callstack in two requests, we first get the top stack frame, and than we request for everything else. What is probably happening here is that the top stack frame for some weird reason does not get focussed and we focus the top of the rest.

Here's a code pointer for the focus stack frame function. This should get called after each request https://github.com/Microsoft/vscode/blob/22ce18150c427774abb0e88ce251c3f1319cc6dd/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L756

My suspect is this change, but it should only happen when the top stack frame can not be focussed. Why is that you would have to check (for example top stack frame has `presentationHint === deemphasize`)

https://github.com/Microsoft/vscode/blob/22ce18150c427774abb0e88ce251c3f1319cc6dd/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L617

**Comment by tomrav** [comment] 2019-01-14 09:45
I think I'm running into a similar issue with the insiders version (2019-01-14T06:06:34.818Z). Noticed a couple of strange behaviors that might be related.

If I'm mistaken and they are not related - let me know and I'll open a separate issue.

When attempting to debug code in the IDE, the following happens:
- It will stop on the correct breakpoint, but visually it will display a different file open (from up the stack), this doesn't always happen, and I couldn't figure out what triggers it, but there are just some files/functions that he will not go to visually
- Getting the same behavior when trying to "step into", where logically it works, but it remains in the invoking function, and not the invoked one, again, this happens some of the time
- It shows in the call stack panel that some parts were skipped due to smartStep, I've tried disabling this in my launch config, but it seems to ignore it altogether
- When trying to stop a debugging session, I am required to press the `stop` button twice. The first click appears to do nothing

Examples:

![screen shot 2019-01-14 at 11 34 56](https://user-images.githubusercontent.com/6399886/51105395-8c4e2700-17f1-11e9-8bdd-6550753121d0.png)
![screen shot 2019-01-14 at 11 35 35 1](https://user-images.githubusercontent.com/6399886/51105416-94a66200-17f1-11e9-8d27-5b22d807b42d.png)

**Comment by isidorn** [comment] 2019-01-23 15:04
@roblourens @tomrav thanks for providing details.
I have reverted some fix which I believe has caused this.
Please let me know if you still see this behavior from tomorrow's vscode insiders

Also note - that we will no longer auto focus stack frames which are deemphesized (so if a stack frame is gray it will not get auto focused).

@tomrav there might still be unrelated issues from your description. What you see from tomorrows vscode insiders please file in seperate issues. Thansk a lot

**Comment by tomrav** [comment] 2019-01-23 16:31
I'll be sure to check it out tomorrow, thanks!

**Comment by isidorn** [comment] 2019-01-25 11:32
Closing this and you let me know if you still see this and I will reopen. Thanks!

**Closed by isidorn** 2019-01-25 11:32 UTC
Labels: debug, needs more info

**Comment by tomrav** [comment] 2019-01-27 11:15
Upgraded to the latest version of the insiders edition. Bug still happening.

I can set a breakpoint somewhere in my code, run a test, hit the breakpoint, but just not get transferred to it/stay in the file where I was.

In addition, it appears that right clicking "toggle skipping this file" doesn't have any noticeable effect, and setting `smartStep` to false in my launch config still takes no effect, and I can see `smartStep` being applied to my code (further up the call stack, not 3rd party code, possibly a separate issue)

**Comment by roblourens** [comment] 2019-01-27 19:17
> In addition, it appears that right clicking "toggle skipping this file" doesn't have any noticeable effect, and setting smartStep to false in my launch config still takes no effect, and I can see smartStep being applied to my code (further up the call stack, not 3rd party code, possibly a separate issue)

These are separate issues, please file a new issue with as many details as possible.

**Comment by isidorn** [comment] 2019-01-28 16:35
@tomrav is it possible that you create a repository on GitHub which I could just clone and reproduce this behavior on my machine?

**Comment by tomrav** [comment] 2019-02-07 09:51
@isidorn sorry for the delay in responding, I just checked and this is still happening.
I haven't gotten around to creating a separate repo as I'm not entirely sure what triggers the issue, however the project in which this is happening is open source, so I can provide instructions on how to reproduce the matter. My apologies if this adds unwanted noise.

System info:
- vscode version: Insiders, 2019-02-06T20:59:06.120Z
- os version: OSX 10.12.6 (16G1510)

Steps to reproduce:
1. clone https://github.com/wix/stylable
2. checkout to branch `tom/css-vars`
3. run `yarn`
4. open the project in vscode
5. open the file `./packages/core/src/stylable-utils.ts` and place a debugger on line `351` (`return --${namespace}...`)
6. open `./packages/core/tests/css-vars.spec.ts`, edit line `542` from `it('complex...` to `it.only('complex...`
7. with the same file open, run the task called Mocha current
8. at this point you should be hitting a breakpoint, but without switching context to it

Let me know if I can somehow further simplify this.

**Comment by felixfbecker** [comment] 2019-02-17 18:36
I think I have the same problem - for some reason, the top stack frame is always greyed out and not focused automatically.

![image](https://user-images.githubusercontent.com/10532611/52917390-20c51100-32eb-11e9-8f3a-30fe4c1ee652.png)

I need to manually select the stack frame. When invoking step over, it loses it again and I need to manually select it again, on every step.

![2019-02-17 19 35 37](https://user-images.githubusercontent.com/10532611/52917406-5669fa00-32eb-11e9-8839-8716bf04d2e4.gif)

**Comment by felixfbecker** [comment] 2019-02-17 18:40
Setting `"smartStep": false` worked around the issue for me

**Comment by roblourens** [comment] 2019-02-17 18:56
Yes @felixfbecker follow https://github.com/Microsoft/vscode/issues/68127 for that issue.
