### ISSUE TITLE
File explorer operations are undo when the editor has focus but undo stack is empty

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#111659] opened 2020-12-01 18:42 UTC
Testing #111015

> When the focus is in the editor that the Undo and Redo are applied on the Editor. And that the Explorer is Undone only when the focus is on the Explorer

This might not be true as currently I'm seeing

* Rename a file in the explorer
* Focus the editor
* `cmd+z`
* The file name is reverted, this is because the undo stack in the editor is empty, which makes sense but the focus is not **on the Explorer**

**Comment by isidorn** [comment] 2020-12-02 12:12
I believe this is by design of the Editor. 
Somewhat similar, just the other way around https://github.com/microsoft/vscode/issues/111630

Also assigning to @alexdima since this is Editor behavior and I think we can easily change it to undo only things from the Editor.

The other way to fix this, is to keep this as it is and to change https://github.com/microsoft/vscode/issues/111630
Basically making undo global

@aeschli on thoughts

**Comment by alexdima** [comment] 2020-12-02 12:15
This is consistent with other kind of operations, like a refactoring which renames the file and then typing in the file. At one point, when the focus is in the editor and undoing it will hit the refactoring and will rename the file back. So IMHO this is OK.

**Comment by ghs** [comment] 2021-02-12 11:32
I agree that is consistent with other ops, but sometimes when changing between different app, the focus is lost and undoing something is happening not within the editor but the explorer. Will be great to have some confirmation when changes are made within the explorer or an option within the VSC preferences.

**Comment by isidorn** [comment] 2021-02-12 13:23
We have added a confirmation for destructive undos. Check it out in the latest vscode version.

**Comment by isidorn** [comment] 2021-08-13 10:06
Closing as no changes are planned here.

**Closed by isidorn** 2021-08-13 10:06 UTC
Labels: under-discussion, undo-redo
