### ISSUE TITLE
markdown preview cannot wrap

### ISSUE THREAD

**Issue by kymowang** [Microsoft/vscode#25008] opened 2017-04-19 10:46 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|java-run|caolin|1.1.4|
|java-debug|DSnake|0.0.2|
|java-properties|ithildir|0.0.1|
|java|redhat|0.1.0|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|;

---

Steps to Reproduce:

1. create a new markdown fle
2. insert 3 lines with the same content "x" (just one char)
3. expected: preview displays 3 lines
4. actually: preview displays 1 line

**Comment by masoodusmani** [comment] 2017-04-19 12:29
Add two spaces at the end of the line, or use something like vscode-gfm-preview

**Comment by mjbvz** [comment] 2017-04-19 20:40
We target commonmark markdown and use markdownit for rendering. #22987 tracks adding a setting for breaks (wrapping) in markdown files

Closing as duplicate of #22987. Feel free to submit a PR that adds this feature this

**Closed by mjbvz** 2017-04-19 20:40 UTC
Labels: duplicate
