### ISSUE TITLE
Source Control can't diff my files

### ISSUE THREAD

**Issue by sjoseph7** [microsoft/vscode#141533] opened 2022-01-26 06:41 UTC
Issue Type: <b>Bug</b>

When I look at file diffs in Source Control, the "prev" is an empty file, and the "current" is all content, resulting in a diff that highlights all content as new. This behavior just started in the last few days.

VS Code version: Code - Insiders 1.64.0-insider (be7ec0fed2492d17984ab4e3764fe3f685e6ddc4, 2022-01-21T05:16:11.878Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.62GB free)|
|Process Argv|--crash-reporter-id 7c48af75-bdda-4960-8d71-b75dbea2a233|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-tailwindcss|bra|0.7.6
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.1.0
prettier-vscode|esb|9.1.0
todo-tree|Gru|0.0.215
rest-client|hum|0.24.6
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.19.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2022.1.1001614873
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-wsl|ms-|0.64.2
vscode-typescript-next|ms-|4.6.20220125
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
vscode-versionlens|pfl|1.0.9
live-sass|rit|3.0.0
LiveServer|rit|5.7.4
quokka-vscode|Wal|1.0.440
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vscop804cf:30404767
vscop940:30404999
vsclayoutctrc:30405799
azactmsal:30409287
pythonvspyt640:30426300
vsbas813:30426126

```

</details>

**Comment by lszomoru** [comment] 2022-01-26 09:46
This looks like a regression that was introduced earlier this week but already fixed in the latest `Insiders` release.
Could you please upgrade to the latest Insiders release and reopen the issue if you are still able to reproduce it.

**Closed by lszomoru** 2022-01-26 09:46 UTC

**Comment by sjoseph7** [comment] 2022-01-27 09:21
No longer an issue. Thanks!
