### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT in image editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119613] opened 2021-03-23 14:26 UTC
* use `"webview.experimental.useIframes": true`
* open an image
* notice the error below

```
GET vscode-webview-resource://d92bca1d-43cd-4330-97a4-317e6889d688/file///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/image-preview/media/loading.svg net::ERR_BLOCKED_BY_CLIENT
```

**Comment by mjbvz** [comment] 2021-03-23 15:10
Duplicate of #118181

**Closed by mjbvz** 2021-03-23 15:10 UTC
