### ISSUE TITLE
Weird suggestion completion blinking in settings.json

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#126537] opened 2021-06-16 22:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.  Open user `settings.json`
2. Type  something that produces completions
3. Observe that the completion, presumably the **ghost completion**, is blinking a dark color with unreadable text.
4.  Suggestions in a code editor (e.g., javascript file) does not do this.
5. Also in Insiders only, not Stable. 

![settingsSuggestions](https://user-images.githubusercontent.com/31813701/122300985-511e1980-cebd-11eb-95eb-91ac6721ac56.gif)

Version: 1.58.0-insider (user setup)
Commit: 3e0c442a8ee9fdc037d627d70fe291f72af04cfd
Date: 2021-06-16T05:17:51.956Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.21390

**Comment by hediet** [comment] 2021-06-17 07:11
This is a duplicate of https://github.com/microsoft/vscode/issues/125123.

In todays insiders build, you can set `editor.suggest.previewMode` to `prefix` to get the behavior of the stable release. Note that it suffers the same problem, it is just less likely that the preview is shown.

**Closed** 2021-07-10 18:31 UTC
Labels: bug, inline-completions
