### ISSUE TITLE
Trust badge hides the 'new updates available' badge

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#121068] opened 2021-04-12 05:49 UTC
Please see the screenshot below

![image](https://user-images.githubusercontent.com/172399/114346338-96436980-9b63-11eb-9ee1-20f81f3db7ed.png)

**Comment by sbatten** [comment] 2021-04-12 15:31
Showing both is a bug which we have a duplicate for. Showing trust over update is by design.

**Comment by sbatten** [comment] 2021-04-27 23:24
closing as obsolete, this badge is gone

**Closed by sbatten** 2021-04-27 23:24 UTC
Labels: workspace-trust
