### ISSUE TITLE
Format Document in HTML issue

### ISSUE THREAD

**Issue by StickNitro** [Microsoft/vscode#50147] opened 2018-05-19 06:54 UTC
Issue Type: <b>Bug</b>

When using Shift+Option+F to format an HTML document all elements get placed on a newline, this causes problems where the intention is for the element to be inline with other content.  For example, suppose I have the following HTML:

```
<label for="enableQuizMode" class="Pos(r) M(0) Cur(p) Fw(400) Pstart(8px)">
  Score this question (<strong>enable quiz mode</strong>)
</label>
```

The output result for this will be a `label` whose text will display as `Score this question (**enable quiz mode**)`

When applying Format Document this causes the HTML to get changed to

```
<label for="enableQuizMode" class="Pos(r) M(0) Cur(p) Fw(400) Pstart(8px)">
  Score this question (
  <strong>enable quiz mode</strong>)
</label>
```

And the subsequent output results in a space between the opening bracket and the enclosed text `Score this question ( **enable quiz mode**)`

Is there someway that we could tell Format Document to ignore specific lines as at the moment I have to remember to go back and fix these lines after formatting the HTML document. You can use a comment to tell the browser not to insert a space but this also gets formatted to new lines.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
EditorConfig|Edi|0.12.2
JSDocTagComplete|Hoo|0.0.2
vscode-html-scss|P-d|0.0.42
vscode-docker|Pet|0.0.26
php-formatter|Sop|0.2.4
yaml|ada|0.0.9
sort-imports|ama|5.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitlens|eam|8.3.0
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
php-debug|fel|1.12.3
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
docthis|joe|0.6.0
git-indicators|lam|2.1.1
preview-jsdoc|lud|1.0.3
code-beautifier|mic|2.0.3
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.4.3
color-highlight|nau|2.3.0
typescript-hero|rbb|2.3.2
vscode-icons|rob|7.23.0

</details>

**Comment by aeschli** [comment] 2018-05-22 09:35
duplicate of https://github.com/Microsoft/vscode/issues/43520

**Closed by aeschli** 2018-05-22 09:35 UTC
