### ISSUE TITLE
source control is showing initiate repository after taking update.

### ISSUE THREAD

**Issue by umeshchaudhari9** [microsoft/vscode#95116] opened 2020-04-13 13:37 UTC
- VSCode Version:1.44
- OS Version: Windows 10

Steps to Reproduce:

1. Take update of latest vs code
2. restart VS code.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment] 2020-04-13 15:59
Possible duplicate of https://github.com/microsoft/vscode/issues/94858#issuecomment-612010439, please check the discussion there if you're using Quick Heal

Do you mean VSCode is showing a message telling you to initiate a repository, or is not detecting a repository?

**Closed** 2020-04-21 11:23 UTC
Labels: needs more info
