### ISSUE TITLE
CPU goes 100%

### ISSUE THREAD

**Issue by peacefulseeker** [Microsoft/vscode#71866] opened 2019-04-06 19:06 UTC
Issue Type: <b>Performance Issue</b>

Hey VSCoders,

recently I am experiencing problems with high CPU in one workspace. Especially when I try to go to a definition of local node modules package. Trying to understand what could be the problem, since other projects run just fine.
Can it be connected with file watcher, file or search exclusion within workspace settings?

VS Code version: Code - Insiders 1.34.0-insider (d234937aedcbc265d2272ba5861125293239f9c7, 2019-04-05T05:14:06.827Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (2.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    98	 68438	code-insiders main
    8	    98	 68439	   gpu-process
   13	   295	 68440	   window (Page.js — infogram-frontpage)
    0	     0	 68712	     /bin/bash -l
    0	    66	 68955	       node /usr/local/Cellar/yarn/1.12.3/libexec/bin/yarn.js dev
    0	     0	 68956	         /bin/sh /var/folders/ml/7fh8hsc12799l7tx3sbvfpkh0000gn/T/yarn--1554576937035-0.4920864411067647/node server.js
    0	   213	 68957	           /Users/alexey.vorobyov/.nvm/versions/node/v8.15.0/bin/node server.js
    0	    98	 68724	     extensionHost
  101	   279	 68917	       electron_node tsserver.js 
    0	    66	 68940	         electron_node typingsInstaller.js typesMap.js 
    0	    66	 68921	       electron_node eslintServer.js 
    0	    66	 68929	       electron_node server.js 
    0	    49	 68831	     watcherService
    0	    49	 68920	     searchService
    5	    82	 68946	   shared-process
   52	    66	 68978	   window (Issue Reporter)
    0	     0	 68979	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Page.js — infogram-frontpage)
|    Folder (infogram-frontpage): 105 files
|      File types: js(42) svg(13) png(11) map(10) json(10) yml(3) DS_Store(2)
|                  env(1) md(1) eslintrc(1)
|      Conf files: package.json(1) launch.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|10.4.2
project-manager|ale|10.5.1
copy-relative-path|ale|0.0.2
unique-lines|bib|1.0.0
vscode-toggle-quotes|Bri|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.8.2
vscode-quick-select|dba|0.2.7
javascript-ejs-support|Dig|0.4.4
es7-react-js-snippets|dsz|2.2.1
gitlens|eam|9.5.1
auto-close-tag|for|0.5.6
macros|ged|1.2.1
rest-client|hum|0.21.2
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|0.0.26
expand-region|let|0.1.2
dotenv|mik|1.0.1
quicksnippet|mou|0.0.1
vscode-json5|mrm|1.0.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
copy-file-name|nem|1.0.0
copy-json-path|nid|0.0.5
fix-json|oli|0.1.2
vscode-graphql|Pri|0.1.7
sass-indented|rob|1.5.1
vscode-paste-and-indent|Rub|0.0.8
vscode-sass-format|sas|1.1.6
code-settings-sync|Sha|3.2.8
js-jsx-snippets|sky|0.3.0
vscode-fileutils|sle|2.13.5
guides|spy|0.9.3
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
language-stylus|sys|1.11.0
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by Khaledmnmnh** [comment] 2019-04-06 19:53
I experienced this issue when i add >= 8 projects in a single workspace.
So i fixed this problem by using one project the workspace.

**Comment by mjbvz** [comment] 2019-04-07 05:09
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by peacefulseeker** [comment] 2019-04-08 12:26
**Hey**, @mjbvz.
### Output with enabled extensions 
<img width="1064" alt="Screenshot 2019-04-08 at 15 20 58" src="https://user-images.githubusercontent.com/25010454/55723724-6ad89200-5a12-11e9-9138-0c9c302ecf4e.png">

### Output with disabled extensions
<img width="952" alt="Screenshot 2019-04-08 at 15 23 06" src="https://user-images.githubusercontent.com/25010454/55723821-a2dfd500-5a12-11e9-8501-915d6f383018.png">

**Comment by peacefulseeker** [comment] 2019-04-08 15:07
Okey, seems problem similar to https://github.com/Microsoft/vscode/issues/49885.
When I try to go to file definition, CPU just spikes 100% and stabilises.

Also noticed that after removal of `node_modules` folder, seems CPU goes down.

I have already excluded it from `files.watcherExclude`, `files.exclude` and `search.exclude`

**Comment by peacefulseeker** [comment] 2019-04-08 15:11
Actually CPU goes 100% after opening any file, so after some service/watcher starting on file open.
Before opening any file in workspace everything is ok, even if node server is running in dev environment.

**Comment by mjbvz** [comment] 2019-04-09 22:26
Sounds like https://github.com/Microsoft/vscode/issues/71886

This may be caused by an old version of  `@types/styled-components` @peacefulseeker can you please follow these instructions to see if they fix the issue for you: https://github.com/Microsoft/vscode/issues/71886#issuecomment-481441653

**Comment by peacefulseeker** [comment] 2019-04-11 14:18
Thank you @mjbvz. 
Will take a look after a while. :)

**Comment by peacefulseeker** [comment] 2019-04-14 06:20
@mjbvz, for now seems this https://github.com/Microsoft/vscode/issues/71886#issuecomment-481584323 approach helped me + upgrading the typescript
 globally to version `3.4.3`

**Comment by mjbvz** [comment] 2019-04-15 15:38
Thanks. I'm closing this as a duplicate of  #71886  since it sounds like those steps fixed things

**Closed by mjbvz** 2019-04-15 15:38 UTC
Labels: needs more info
