### ISSUE TITLE
Copying text from various UI elements does not copy to the clipboard (Windows)

### ISSUE THREAD

**Issue by anthroid** [microsoft/vscode#158639] opened 2022-08-19 22:50 UTC
Does this issue occur when all extensions are disabled?: N/A - This issue affects extensions and other non-editor panes containing user-selectable text.

### System information:

`Version: 1.70.2` (system setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
`OS: Windows_NT x64 10.0.19044`

**and**

Version: 1.66.0 (system setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
`OS: Windows_NT x64 10.0.18363`

**but not:**

`Version: 1.70.2` (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
`OS: Darwin arm64 20.6.0`

### Steps to Reproduce:
**Test 1:**
1. Before opening VS Code, copy a small section of text from anywhere (Notepad, browser, etc) to the clipboard.
2. Paste the text somewhere to verify it was copied (back into Notepad, etc).
3. Open VS Code.
4. Open an extension that provides a custom UI pane (anything that uses a tab, but is not a text editor). _Examples: Thunder Client, Git Graph, or any similar UI._
5. Select text from anywhere in the UI that allows it (especially fields where text selection and copy/paste is a core function). _Examples: Thunder Client request URL field, Git Graph commit hash._
6. `Right-click > Copy` the selected text.
7. Open a new editor (or another application, for example Notepad) and paste the text. The original text copied in step 1 will be pasted instead of the text just copied from the extension.

**Test 2:**
1. Open one of the extensions referenced above (Git Graph, Thunder Client, or similar).
2. Open an existing file and drag this tab to the right side of the extension tab (side-by-side with the extension tab).
3. In the tab on the right side, select a word in the text file.
4. With that text selected, switch focus to the extension tab, and select some text from any user-selectable field that presents a `Copy` option when right-clicking.
5. `Right-click > Copy` the selected text.
6. Open a new editor window (or Notepad, etc) and paste. The selected text for the unfocused, not-copied text will be pasted.

Even though the editor on the right did not have focus and another section of text was highlighted in another tab (with focus), and the text was copied directly at its location using the mouse (eliminating the possibility of the wrong tab having focus), the selected text from the _unfocused_ editor was copied to the clipboard instead of the focused text.

This might sound like an extension problem, but it appears it could actually be a VS Code issue for the following reasons:
- Multiple, completely unrelated extensions exhibit the same problem with similar UI elements, only on Windows.
- The problem is not present in the exact same version of VS Code on macOS. The same text within the same tested extension tabs always copies to the clipboard as expected.

Edit:

**Further testing shows the following behavior:**

The same behavior is present when copying text from an extension's page in the extension view:
1. Open a new VS Code window.
2. Open the Extensions sidebar and select any extension to view its detail page. Example: Microsoft C/C++ extension.
3. Select a line of text on the page. Example: "C/C++ for Visual Studio Code"
4. `Right-click > Copy` the selected text.
5. Open a new editor (or Notepad) and paste. Either an empty newline, or your previous clipboard contents will be pasted.

The clipboard works as expected (content is copied and pasted normally) when using the keyboard shortcut `Control-C` to copy the text instead of the right-click menu, so it appears the issues is isolated to the right-click menu action and the `Edit > Copy` menu.

**Comment by anthroid** [comment] 2022-08-19 23:30
Related issues:
https://github.com/rangav/thunder-client-support/issues/439
https://github.com/mhutchie/vscode-git-graph/issues/296#issuecomment-1117500753

**Comment by mjbvz** [comment] 2022-08-23 19:08
Duplicate of #141080

**Closed by mjbvz** 2022-08-23 19:08 UTC
