### ISSUE TITLE
Multi-line template strings can't be collapsed

### ISSUE THREAD

**Issue by Darko** [Microsoft/vscode#57825] opened 2018-09-03 22:19 UTC
- VSCode Version: 1.26.1
- OS Version: MacOS High Sierra 10.13.5

Steps to Reproduce:

1. Using styled-components write a styled component (React) with template strings syntax
2. Try to collapse it, no collapse button

![Bug](https://i.nuuls.com/rk0cC.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Kenny407** [comment] 2018-09-03 22:30
I'm facing the same problem but not only with React. Also with VanillaJS.

**Comment by mjbvz** [comment] 2018-09-04 18:25
Duplicate of https://github.com/Microsoft/TypeScript/issues/23382

**Closed by mjbvz** 2018-09-04 18:25 UTC
Labels: typescript
