### ISSUE TITLE
Set Custom Defaults for all Users

### ISSUE THREAD

**Issue by ThomasRunting** [Microsoft/vscode#29935] opened 2017-06-30 10:53 UTC
I would like to be able to override the default settings for all users on install.
My students need to have the ' "http.proxyStrictSSL": false,' set for them instead of having them do it on every login to there computers. We have a SSL inspection transparent proxy and this is the only way i have been able to get the extensions to install.

All i really want is something like vscodeinstall.exe /s /setdefaults = new defaults.json

**Comment by mjbvz** [comment] 2017-06-30 17:28
Also tracked on https://stackoverflow.com/questions/44837070/set-default-settings-for-all-users-in-vscode

Duplicate of https://github.com/Microsoft/vscode/issues/27972

**Closed by mjbvz** 2017-06-30 17:28 UTC
Labels: duplicate, extensions
