### ISSUE TITLE
Commit Message in the "Source Control" message input box should retain after closing the VSCode

### ISSUE THREAD

**Issue by Soberia** [microsoft/vscode#107307] opened 2020-09-23 14:48 UTC
Commit Message in the "Source Control" message input box should retain after closing the VSCode.
By this way, we can add changelog when developing in process

![image](https://user-images.githubusercontent.com/30440494/94028691-ec6bdd80-fdc8-11ea-8509-4ae53ef186e4.png)

**Comment by mjbvz** [comment] 2020-09-23 17:42
Duplicate of #41232

**Closed by mjbvz** 2020-09-23 17:42 UTC
