### ISSUE TITLE
"aiKey" not allowed

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#76493] opened 2019-07-03 02:18 UTC
Why is this flagged? Did something change in the schema?

In https://github.com/microsoft/vscode-node-debug/blob/master/package.json

![image](https://user-images.githubusercontent.com/323878/60558448-2e10f400-9cfe-11e9-9172-e08ffc7768a7.png)

**Comment by isidorn** [comment] 2019-07-03 08:05
Because the `aiKey` is not something for the public extensions.
This is only for internal extensions and thus we do not want to expose it in the package.json
Apart from that @weinand and me decided that we flag all unkown attributes in the `debuggers` section, more details about that here https://github.com/microsoft/vscode/issues/75887

Since the json schema does not support a non public attribute that is allowed we have decided to live with these warnings.

Due to that closing as designed.
Suggestions on improvment are welcome.

**Closed by isidorn** 2019-07-03 08:05 UTC
