### ISSUE TITLE
[go] Additions to the number literal grammar

### ISSUE THREAD

**Issue by DavidArchibald** [microsoft/vscode#80524] opened 2019-09-08 02:51 UTC
I originally opened https://github.com/microsoft/vscode-go/issues/2735 for Golang as the [number literals introduced in Go 1.13](https://golang.org/doc/go1.13#language) were not given the correct syntax highlighting. This is an upstream feature request for this.

I'm not as sure that this a good fit if this is going to be for *all* of VSCode, but the numbers that were not, treated properly can be shown by creating a file with any sort of syntax highlighting from my testing.

There are several permutations, and [the exact grammar is described here](https://golang.org/ref/spec#Integer_literals), but the main ones can be shown through a snippet such as the following:

```go
// Ok
0xabc
1000000
0x1.0p-1021 // Partially Ok

// Bad
0b1011
0B1011
0Xabc
0o660
0O660

// Imaginary Variants
0b1011i
0xabci
0o660i

// Underscores to Split Digits
1_000_000
```

While this replicates in Github's grammar near identically(save 0X also being formatted correctly), here is an example of what it currently looks like(in Go):

![Example of number literals](https://user-images.githubusercontent.com/19630496/64482381-b485fe00-d1a5-11e9-80cb-d6ef8dec469b.PNG)

This could be a specific issue for just Go, and I've scoped it as much because a mantissa on hexadecimal numbers, for example, is not probably needed for all languages. However as lowercase `0x` hexadecimal numbers appears to be recognized universally(from my testing of random languages), additions could be made to all of VSCode to accommodate uppercase 0X hexadecimal for example, as well as others that'd be valuable.

**Comment by tohjustin** [comment] 2019-09-08 22:01
VSCode currently seems to be using the TextMate grammar files for syntax highlighting: https://github.com/microsoft/vscode/blob/master/extensions/go/syntaxes/go.tmLanguage.json#L3

> ```
> "information_for_contributors": [
>   "This file has been converted from https://github.com/atom/language-go/blob/master/grammars/go.cson",
>   "If you want to provide a fix or improvement, please create a pull request against the original repository.",
>   "Once accepted there, we are happy to receive an update request."
> ],
> ```

I've already pushed a PR to support this change in number literals on https://github.com/atom/language-go side: https://github.com/atom/language-go/pull/175.

Will send an update request here once it gets reviewed & merged. 😅

**Comment by alexr00** [comment] 2019-09-10 10:54
Very nice! I will call this a duplicate of atom/language-go#175 then.

**Closed** 2019-09-10 10:54 UTC
Labels: grammar

**Comment by tohjustin** [comment] 2019-09-17 04:40
Just got a [response](https://github.com/atom/language-go/pull/175#issuecomment-531987881) from the maintainer of the [atom/language-go](https://github.com/atom/language-go) project & seems like they're not going planning to maintain the Go TextMate grammar on their end.

There are some other sources of Go TextMate grammar, but none of them seems to be actively maintained at the moment:
- [rsms/Go.tmbundle](https://github.com/rsms/Go.tmbundle) - last commit on Nov 12, 2009
- [AlanQuatermain/go-tmbundle](https://github.com/AlanQuatermain/go-tmbundle) - last commit on Jul 17, 2013
- [syscrusher/golang.tmbundle](https://github.com/syscrusher/golang.tmbundle) - last commit on Aug 8, 2017

@alexr00 Would [microsoft/vscode](https://github.com/microsoft/vscode) consider maintaining their own copy of the Go TextMate grammar? (I could help port over the changes from my PR in [atom/language-go #175](https://github.com/atom/language-go/pull/175) over here if needed 😅)

**Comment by alexr00** [comment] 2019-09-17 07:47
We prefer to have our grammars come from the community as much as possible so that we don't have to be experts in every language 😊.

If you wanted to try maintaining the grammar yourself, a good starting point would be to make an extension for it and get some users. You can see an example of how to contribute a grammar using an extension here: https://github.com/jeff-hykin/cpp-textmate-grammar/blob/master/package.json
