### ISSUE TITLE
Color profiles other than sRGB cause major performance issues

### ISSUE THREAD

**Issue by farski** [microsoft/vscode#78326] opened 2019-08-01 11:27 UTC
Issue Type: <b>Performance Issue</b>

Performance of the buffer is severly degraded when the system color profile is set to anything other than sRGB. I believe this is related to an underlying issue with Chromium ([821020](https://bugs.chromium.org/p/chromium/issues/detail?id=821020), [791828](https://bugs.chromium.org/p/chromium/issues/detail?id=791828), [989904](https://bugs.chromium.org/p/chromium/issues/detail?id=989904)). There is a workaround in some other Chromium-based apps (e.g., Chrome), which allow the profile off the app to be distinct from the system profile. I have not been able to figure out a way to provide such an override with VS Code. Until the issue with Chromium is fixed, having the ability to set the color profile specifically for VS Code would be extermely helpful.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   131	 69877	code main
    0	    82	 69878	   gpu-process
    0	   197	 69880	   window (radiotopia.fm-hosted_zone.yml — Infrastructure)
    0	    82	 69980	     extensionHost
    0	    49	 69981	     watcherService
    0	    98	 69982	   shared-process
    0	     0	 70086	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	 70084	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (radiotopia.fm-hosted_zone.yml — Infrastructure)
|    Folder (Infrastructure): 133 files
|      File types: yml(79) py(15) md(11) js(11) DS_Store(7) sh(3) json(3)
|                  yaml(1) gitignore(1) xml(1)
|      Conf files:;
```

</details>
Extensions: none

**Comment by bpasero** [comment] 2019-08-05 12:53
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by farski** [comment] 2019-08-06 18:08
I will give it a shot. FWIW this issue is now being [tracked](https://bugs.chromium.org/p/chromium/issues/detail?id=989904) in the Chromium project, and seems like it needs to be fixed there, so if the new version of Electron is still using that, it is likely impacted.

**Comment by bpasero** [comment] 2019-08-07 05:22
Thanks

**Comment by farski** [comment] 2019-08-19 11:41
@bpasero I've confirmed that this issue still occurs with the exploration build,

**Comment by bpasero** [comment] 2019-10-10 06:09
I think this will be fixed with E6.

**Comment by farski** [comment] 2019-10-10 12:38
The root cause in Chromium still hasn't been identified. Is there a change in E6 that will workaround the problem?

**Comment by bpasero** [comment] 2019-10-10 12:48
Oh sorry, I did not see the linked issue. Thanks for doing that!

**Comment by deepak1556** [comment] 2023-12-12 02:27
Closing as upstream marked the issue as [wont fix](https://bugs.chromium.org/p/chromium/issues/detail?id=989904#c20), please check if the issue is present with latest stable.

**Closed by deepak1556** 2023-12-12 02:27 UTC
Labels: bug, upstream, macos, upstream-issue-linked, chromium
