### ISSUE TITLE
Offer creation of folder if it doesn't exist when opening folder

### ISSUE THREAD

**Issue by mhanuszh** [microsoft/vscode#123167] opened 2021-05-06 17:27 UTC
When we trying to open a folder that does not exist, we get this message:
![Screenshot_20210506_192453](https://user-images.githubusercontent.com/5262962/117340084-cea74080-aea0-11eb-8baa-b81a7c48ef58.png)

Instead, VSCode should offer the creation of said folder

**Comment by alexr00** [comment] 2021-05-07 13:14
duplicate of https://github.com/microsoft/vscode/issues/71425

**Closed** 2021-05-07 13:14 UTC
Labels: *duplicate
