### ISSUE TITLE
escape doesn't close find when find option focused

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#94445] opened 2020-04-04 17:22 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Press Find keyboard shorcut.
2. Press <kbd>tab</kbd> to focus one of the find option buttons (e.g. Match Case).
3. Press <kbd>escape</kbd>.

Find widget does not close.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|10.11.0
vscode-css-modules|cli|0.2.3
vscode-eslint|dba|2.1.2
vscode-dash|dee|2.3.0
find-related|eam|0.9.0
gitlens|eam|10.2.1
tslint|eg2|1.0.44
prettier-vscode|esb|4.0.0
vscode-ghc-mod|hoo|1.2.0
search-node-modules|jas|1.3.0
hoogle-vscode|jca|0.0.7
vscode-deno|jus|1.4.0
language-haskell|jus|2.7.0
vscode-duplicate|mrm|1.2.1
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1891
debugger-for-chrome|msj|4.12.6
ruby|reb|0.27.0
vscode-quick-scope|ska|0.2.0
vim|vsc|1.13.1
vscode-ruby|win|0.27.0
material-theme|zhu|3.2.5

(1 theme extensions excluded)

</details>

**Comment by ArturoDent** [comment] 2020-04-05 02:17
<kbd>Shift</kbd>+<kbd>escape</kbd> works (unless you first try <kbd>escape</kbd> which is weird).

But it seems looking at the Keyboard Shortcuts they both should work - they have the same `when` clauses.

**Comment by NotWearingPants** [comment] 2020-07-17 15:41
Found the problem - it's on purpose.
It is part of the code that allows moving between the options with the arrow keys.

If you press escape, it removes the focus from the option:
https://github.com/microsoft/vscode/blob/ff6b1c5984a4c2116a06318f07e871a4169fdb1b/src/vs/base/browser/ui/findinput/findInput.ts#L229-L230

and then it stops the event from triggering any other handlers (like the one that closes the find widget):
https://github.com/microsoft/vscode/blob/ff6b1c5984a4c2116a06318f07e871a4169fdb1b/src/vs/base/browser/ui/findinput/findInput.ts#L235

So it's an easy fix, the question is whether it should be fixed at all, because it looks like it was a UX choice, not a bug.
I also prefer it closing the widget instead of just blurring, so I'll submit a PR and the team can decide if they agree.

The whole relevant code:
https://github.com/microsoft/vscode/blob/ff6b1c5984a4c2116a06318f07e871a4169fdb1b/src/vs/base/browser/ui/findinput/findInput.ts#L212-L238

**Comment by NotWearingPants** [comment] 2020-08-02 07:20
Please consider merging the fix for this @rebornix 
Just because it is "as designed" doesn't mean it should stay this way, this is bad UX.

**Comment by rebornix** [comment] 2020-10-09 23:15
@NotWearingPants agree with you that the current behavior is bad, I pushed a change to focus back the input box when users press escape.

**Closed** 2020-10-09 23:15 UTC
Labels: bug, editor-find, polish
