### ISSUE TITLE
PowerShell Interactive Console Keeps Defaulting to White Text

### ISSUE THREAD

**Issue by HJLBX** [Microsoft/vscode#46397] opened 2018-03-23 07:42 UTC
Issue Type: <b>Bug</b>

I use PowerShell Language Mode in VS Code. That's all I want it for. I want the terminal to emulate the default Windows PowerShell console exactly - every time I launch VS Code. I have it configured to do it. I had only a single profile - 1 - powershell. And every time I launched VS Code, it opened to 1 - powershell.

This issue started immediately after the most recent update. Every time I launch VS Code, it now opens the terminal to PowerShell Integrated Console which uses a white-only typing scheme.

I want to be able to launch Visual Studio Code and have it open to the PowerShell terminal and have that PowerShell use the default console color scheme as-you-type. Meaning different colors for text dependent upon whether they are cmdlets, parameters, variables, etc.

For whatever reason(s), with the PowerShell extension installed, the PowerShell Language Mode selected, the terminal was opening to 1 - powershell which uses the same color scheme as you type as the default PowerShell console, but now it launches, opens to 1, then quickly switches to 2 - PowerShell Integrated Console - which uses only a white typing scheme.

It is really annoying because I am vision-impaired and the white-only lettering scheme of PowerShell Integrated Console just is not helpful. I have tried to figure out how to make it stop, searched online for answers, asked on PowerShell.org, etc but can find no answer.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|Memory (System)|11.92GB (8.92GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.6.0
vscode-icons|rob|7.22.0

</details>
Reproduces only with extensions

**Comment by yume-chan** [comment] 2018-03-23 14:20
Relates with PowerShell/vscode-powershell#535, I hope it will be resolved soon.

Before that, you can always switch back to your normal PowerShell console by selecting it from the dropdown menu above the console.

If you don't need the debugging functionality of PowerShell extension, you actually don't need the "PowerShell Integrated Console" thing, you can disable it from automatically popping up by setting `powershell.integratedConsole.showOnStartup` configuration to `false`.

**Comment by HJLBX** [comment] 2018-03-23 18:11
The powershell.integratedConsole.showOnStartup configuration to false is not working. I already tried. PowerShell Integrated Console keeps loading with the above setting set to false.

Like I stated in my original report, this all started after this most recent update.

Time to uninstall Visual Studio Code.

**Comment by Tyriar** [comment] 2018-03-23 20:45
I'll close this as a duplicate of https://github.com/Microsoft/vscode/issues/45693 and https://github.com/PowerShell/vscode-powershell/issues/535

**Closed by Tyriar** 2018-03-23 20:45 UTC
Labels: integrated-terminal
