### ISSUE TITLE
problem with selecting persian/arabic  charachters in 1.43 release

### ISSUE THREAD

**Issue by Meti27** [microsoft/vscode#92373] opened 2020-03-10 15:34 UTC
vscode : `1.43`
problem with selecting persian/arabic charachters in new release

![Untitled Project](https://user-images.githubusercontent.com/11253027/76329486-e406f600-6301-11ea-8b8e-b229cc063a33.gif)

**Comment by alexdima** [comment] 2020-03-11 07:54
As a workaround, you could use `"editor.renderWhitespace": "none"`.

**Comment by Meti27** [comment] 2020-03-11 14:03
@alexdima  thank you , seems works great.

**Comment by alexdima** [comment] 2020-03-30 08:49
Duplicate of #90019

**Closed by alexdima** 2020-03-30 08:49 UTC
Labels: bug, editor-rendering
