### ISSUE TITLE
Not everything is in English after changing display language (locale) to "en"

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#38740] opened 2017-11-20 03:22 UTC
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

I've changed my locale from "ru" to "en":

![image](https://user-images.githubusercontent.com/24613274/33000589-c0c9c25e-cdb1-11e7-91e3-614bdd22dcb9.png)

restarted VS Code, and almost everything is now in English, except for settings name in the tab:

![image](https://user-images.githubusercontent.com/24613274/33000710-5fea6c6c-cdb2-11e7-9bd7-57ec32280a73.png)

It's the global settings file from here:

`C:\Users\YourName\AppData\Roaming\Code - Insiders\User\settings.json`

**Comment by johnliu2016** [comment] 2017-11-20 07:14
// @lukaschal, unlocalized strings of "Settings" on tab

**Comment by lukaschal** [comment] 2018-03-05 15:15
Strings are not english after changing locale from "RU" to "EN".

**Comment by dbaeumer** [comment] 2018-09-24 12:44
The UI around setting changed a lot and I can't reproduce this in latest. Closing.

Please ping if still an issue.

**Closed** 2018-09-24 12:44 UTC
Labels: *not-reproducible, i18n
