### ISSUE TITLE
VS Code not detecting git repository after update

### ISSUE THREAD

**Issue by DiamondIceNS** [microsoft/vscode#173226] opened 2023-02-02 23:56 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0
- OS Version: Windows 10 Pro (22H2)

Steps to Reproduce:

1. Open VS Code workspace
2. Open Source Control tab in Activity Bar

I have been using VS Code to edit this same project for four years. Just today, after updating to 1.75.0, VS Code no longer recognizes my workspace as a valid Git repository, despite it still having a `.git` folder present.

I disabled all extensions and re-installed VS Code to ensure that my install was not corrupted. I also tried deleting the `.git` folder in the workspace directory and re-cloning it from my origin repository. The problem persists.

Curiously, it seems to be restricted to this one workspace. I have another workspace that I have been editing with VS Code for the same duration of time and it is not affected. VS Code detects the git repository there just fine.

I am convinced it is not a problem with my Git executable or my repository, as when use `git` in my terminal or install the extension GitLens (both of which utilize the same `git.exe` executable as VS Code), neither has any issue interacting with the repository. Only VS Code seems to have this problem.

Here's the output log for the Git service running on the fresh install with no extensions. It's not very illuminating. No errors are thrown.

[git-output.txt](https://github.com/microsoft/vscode/files/10574332/git-output.txt)

**Comment by Attackly** [comment] 2023-02-03 12:15
Had the same problem. 
The Repo was on a Netowrk Share 
Possible Workaround:
Copying the Repo to the Harddrive of the Computer fixed it and recognized it again.

**Comment by lszomoru** [comment] 2023-02-03 12:32
@DiamondIceNS, @Attackly could you please share the screenshot of the "Source Control" view? VS Code `1.75` contains some changes related to [git repository discovery in parent folders](https://code.visualstudio.com/updates/v1_75#_git-repositories-in-parent-folders). Are you still able to reproduce the problem if you set the `git.openRepositoryInParentFolders` to `always` and reload the window?

**Comment by Attackly** [comment] 2023-02-03 12:34
![grafik](https://user-images.githubusercontent.com/91603506/216604841-6d749463-c4af-4f5d-a359-aa022fa5882a.png)

**Comment by lszomoru** [comment] 2023-02-03 12:38
@Attackly, could you please implement the following steps:
1. Close all windows of VS Code
2. From a Terminal window run `code.exe --log trace`
3. Wait for VS Code to load and for the repository not to get discovered
4. Share the contents of [the git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)

**Comment by Attackly** [comment] 2023-02-03 12:44
The log wiith `git.openRepositoryInParentFolders` set to prompt

[git-log-trace.txt](https://github.com/microsoft/vscode/files/10578945/git-log-trace.txt)

**Comment by lszomoru** [comment] 2023-02-03 12:47
@Attackly, could you also please provide the logs with `git.openRepositoryInParentFolders` to `always`. Thanks!

**Comment by Attackly** [comment] 2023-02-03 12:52
Log with `git.openRepositoryInParentFolders` set to Always 
[git-log-trace-with-always.txt](https://github.com/microsoft/vscode/files/10578997/git-log-trace-with-always.txt)

**Comment by lszomoru** [comment] 2023-02-03 12:53
Awesome! Thank you! For the time being please set the setting to always as that will restore the old behaviour. I will further investigate this later today and I will try to get a fix into recovery release that is planned for next week.

**Comment by ryuuji3** [comment] 2023-02-03 15:26
Thank you, the workaround provided worked perfectly for me. 

Just in case it helps;
I was only experiencing this issue when I use a workspace. If I open the folder instead of the workspace, it detects the repo. I suspected it might be related to doing a LiveShare- this only happened after the LiveShare ended for me.

Hope that helps, thanks again.

**Comment by lszomoru** [comment] 2023-02-03 17:06
@ryuuji3, could you please provide more details about the folder structure and the location of the workspace file?

**Comment by ryuuji3** [comment] 2023-02-03 17:12
It's a monorepo but I've placed the workspace file at the root of the monorepo (where the .git folder is). I am using a global .gitignore file to exclude it because IDE artifacts are not included in our repository's .gitignore.

**Comment by kevin-guertin** [comment] 2023-02-03 17:15
I have the same issue with any of my workspaces, but it is fine opening the folder. The workaround also works.

Here is one of my workspace files (personal info redacted) and this is in Linux:
```json
{
	"folders": [
		{
			"path": "../repos/work/PROJECT1"
		},
		{
			"name": "$web",
			"uri": "azurestorage:/$web?resourceId=/subscriptions/XXXX/StorageAccounts/subscriptions/XXXX/resourceGroups/dev/providers/Microsoft.Storage/storageAccounts/XXXX/Blob Containers/$web"
		}
	],
	"settings": {}
}
```

My PROJECT1 has 1 git repo which has a git submodule and that git submodule in turn has its own git submodule. Therefore, my Source Control shows me 3 git repos.

Hope this helps.

**Comment by DiamondIceNS** [comment] 2023-02-03 17:53
Happy to report that the workaround of setting `git.openRepositoryInParentFolders = 'always'` worked for me as well.

Hope that patch comes swiftly. Thank you for your work!

**Comment by DiamondIceNS** [comment] 2023-02-03 18:03
Here is the offending workspace file if it helps:

    {
        "folders": [
            {
                "path": "."
            },
            {
                "path": "..\\<redacted>"
            },
            {
                "path": "..\\<redacted>\\<redacted>"
            },
            {
                "path": "..\\<redacted>\\<redacted>"
            }
        ],
        "settings": {
            "files.eol": "\n"
        }
    }
    
Paths 2 and 3 point to two separate directories covered by the repository I previously reported as functioning and Path 4 points to a directory in a hereto unmentioned third repository.

**Comment by lszomoru** [comment] 2023-02-03 18:15
Thank you all for the information. I am still struggling to reproduce the issue even with a workspace file that contains "path" fields similar to the samples provided above. Are the workspace folders all contained in the same git repository? A minimal sample of the folder structure that you could share would be extremely valuable.

**Comment by jomido** [comment] 2023-02-03 19:14
Thanks for this workaround.

> A minimal sample of the folder structure that you could share would be extremely valuable.

I don't have a minimal example that I've tested for both failure and success (given the workaround), but I do have the following locally:

```
- root repo dir (.git, etc.)
  - frontend dir (JavaScript, so package.json, etc...)
  - backend dir (Python, so requirements.txt, etc...)
```

I have the `frontend dir` open in VS Code.

**Comment by kevin-guertin** [comment] 2023-02-03 19:15
A screenshot may help, though the paths I showed previously should already make this obvious, nonetheless, here it is. All of my Workspace files are in one folder. It only contains workspace files. No repos. The repos are in a folder at the same level as that workspace folder. One of my paths is a network path to an Azure resource, which is not a git repo.

![image](https://user-images.githubusercontent.com/50712250/216686465-3b7bf8ec-47a4-44d1-8e5a-68510b547028.png)

**Comment by lszomoru** [comment] 2023-02-03 19:54
@jomido, thanks for the information. When you opened the "Source Control" view, you should have seen a welcome view similar to the one [here](https://code.visualstudio.com/updates/v1_75#_git-repositories-in-parent-folders). Was that not the case or you just did not switch to the "Source Control" view? The welcome view contains a command to open the git repository from the parent directory.

**Comment by lszomoru** [comment] 2023-02-03 20:09
@kevin-guertin, thank you very much for the screenshot. I believe I have a repro 🎉  Debugging the issue now...

**Comment by DiamondIceNS** [comment] 2023-02-03 20:25
When I do not have the workaround enabled, this what I see in my Source Control view:

![problem](https://user-images.githubusercontent.com/10872887/216702991-2769af95-6600-4eac-8aef-b23c259840db.jpg)

I was not prompted with the shown welcome upon opening my workspace.

With the workaround enabled, this is what I see.

![workaround](https://user-images.githubusercontent.com/10872887/216703188-21500837-c518-41a4-b40a-88517d6ef528.jpg)

The top repository is in the workspace directory, the other two are external. With all Git-related extensions removed, Source Control is the only view available. I believe that's normal?

I wasn't prompted on the aforementioned workspace that "just worked" either, for that matter; which is odd, as it also contains an external git repository. Not gonna complain about something that's still working fine, I guess, but you gotta love bugs that are inexplicably inconsistent...

**Comment by lszomoru** [comment] 2023-02-03 20:56
Thank you all once again for all the information. 

I believe that I was able to track down the issue and created a PR with the potential fix. The problem was caused by the new code path to determine whether a git repository is inside/outside the workspace folder(s). The new code attempts to resolve the workspace folder as it might contain symbolic links before comparing it with the git repository root folder, and I was missing an exception handler. The fix should be included in Monday's Insiders release so I would be really grateful if you want install the build on Monday and confirm that the fix resolves the problem. 

Apologies again for the inconvenience!

**Comment by Jason3S** [comment] 2023-02-04 21:07
@lszomoru,

After removing the deleted workspace folder, things seem to be working, BUT, gutter markers are still missing (the red/blue marks showing which lines were changed). Will that get fixed with your change?

**Comment by lszomoru** [comment] 2023-02-05 09:24
@Jason3S, does any of your workspace folders contain a symbolic link on their path?

**Comment by Jason3S** [comment] 2023-02-05 12:02
@lszomoru,

It is a public repo: https://github.com/streetsidesoftware/cspell

There shouldn't be any symbolic links in the workspace file. But, the workspace paths do NOT start with a `./`.

**Comment by lszomoru** [comment] 2023-02-05 13:38
@Jason3S, could you please confirm that opening the same workspace yields different outcomes when you use VS Code Stable 1.74.3 and VS Code Stable 1.75 and VS Code Insiders 1.76. Just want to narrow down where the problem might be. Thanks!

**Comment by lszomoru** [comment] 2023-02-06 11:03
Today's Insiders release contains the fix for this issue. 
I would really appreciate if you would try it out and confirm that it resolves this issue. Thank you!

```
Version: 1.76.0-insider (Universal)
Commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70
Date: 2023-02-06T05:24:10.821Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by jomido** [comment] 2023-02-06 13:55
> @jomido, thanks for the information. When you opened the "Source Control" view, you should have seen a welcome view similar to the one [here](https://code.visualstudio.com/updates/v1_75#_git-repositories-in-parent-folders). Was that not the case or you just did not switch to the "Source Control" view? The welcome view contains a command to open the git repository from the parent directory.

Apologies for the late response (looks like you've got this sorted, anyhow). When I opened VS Code this morning it had updated to 1.75. I don't think I'll revert back to 1.74.3 to do a check. 

In 1.75 I no longer require the workaround, and the "Source Control" view now appears to be in the correct state, as described above. (I have not used this view on a day-to-day basis, so have nothing to compare it to in an experiential frame of ref.)  In addition, when removing the workaround on 1.75, a toast (inline pop up) on the bottom right of the window renders, asking about a git repo discovered one directory above the working directory. This toast was not appearing 4 days prior.

Thanks for the fix!

**Comment by Jason3S** [comment] 2023-02-06 17:06
> @Jason3S, could you please confirm that opening the same workspace yields different outcomes when you use VS Code Stable 1.74.3 and VS Code Stable 1.75 and VS Code Insiders 1.76. Just want to narrow down where the problem might be. Thanks!

I checked.
- 1.74.3 - works just fine.
- 1.75 VS Code Stable - has issues with git changes not showing.
- 1.76 Insiders - seem to be working.

```
Version: 1.76.0-insider
Commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70
Date: 2023-02-06T05:24:10.821Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: Yes
```

**Comment by UVLabs** [comment] 2023-02-07 10:39
Having the same issue, downgraded for now. There was also a weird issue with my user created snippets (for PHP) only working once and then no longer showing up in the suggestions

**Comment by lszomoru** [comment] 2023-02-08 07:15
@Jason3S, thank you very much for running all the tests. For the same of clarity let's keep this issue scoped to the issue of repository discovery. That particular issue has been fix in Insiders and will be included in the Stable recovery release that is planning for later this week. I will file a separate issue to track the problem related to diff decorators.

**Comment by lszomoru** [comment] 2023-02-08 07:23
Verification steps:
1. Set up the following folder structure, where `foo` and `bar` and both folders containing a git repository
    <img width="364" alt="image" src="https://user-images.githubusercontent.com/3372902/217460632-df7a1754-4dc4-4958-a036-a04d029eeb37.png">
2. Open the `foo` workspace using the workspace file in VS Code `1.75` and the "Source Control" view is empty
3. Open the `foo` workspace using the workspace file in VS Code `1.75.1` and the "Source Control" view should show the two git repositories

**Closed** 2023-02-08 07:39 UTC
Labels: bug, important, git, candidate

**Comment by Jason3S** [comment] 2023-02-08 07:59
@lszomoru,

Thank you for fixing this.

**Comment by Pageboy** [comment] 2023-02-10 11:06
Is this related? The 'Clone Repository' button has gone from the explorer panel.
<img width="317" alt="Screenshot 2023-02-10 at 11 02 07" src="https://user-images.githubusercontent.com/619455/218076841-6396b1a7-91d7-46db-b5ec-ec1eddaa65c4.png">
Above 1.75
<img width="276" alt="Screenshot 2023-02-10 at 10 54 29" src="https://user-images.githubusercontent.com/619455/218077001-2e1195fe-2371-4fcc-874c-141f8fcb13fd.png">
Abobe 1.74

**Comment by Pageboy** [comment] 2023-02-10 12:37
Looks like it moved to here... Hit the Source Control button
<img width="273" alt="Screenshot 2023-02-10 at 12 35 15" src="https://user-images.githubusercontent.com/619455/218093999-125a65f2-8ebb-4bbe-a32f-d4379b719e49.png">

**Comment by AnrDaemon** [comment] 2023-02-12 13:09
What about #112231 sine you are looking at that code already? @lszomoru

**Comment by msdeibel** [comment] 2023-03-22 10:22
I'm seeing this issue after upgrading to 1.77.0

Full version details:
```
Version: 1.77.0-insider (user setup)
Commit: b8e4c550bc87aa1db64e612706ac5238035e9cc2
Date: 2023-03-22T05:22:27.933Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes
```
Setting `git.openRepositoryInParentFolders` to always did not fix it.

**Comment by msdeibel** [comment] 2023-03-22 13:12
My issue was fixed with the installation of

```
Version: 1.77.0-insider (user setup)
Commit: a5bd844beddef8ca5f9ccfdb1bb7b3b4f8e5204e
Date: 2023-03-22T10:38:48.144Z
```
