### ISSUE TITLE
"Format Code" missing in new version

### ISSUE THREAD

**Issue by MeitziQ** [Microsoft/vscode#745] opened 2015-11-27 11:35 UTC
I have old versio 0.7.20 and I open XML file
I can use RMB (Right Mouse button) to "Format Code" for easy reading.

But after I update to 0.10.2 that is not possible anymore.

**Comment by aeschli** [comment] 2015-11-27 16:05
duplicate of #71.
Just FYI, there are two extensions that provide XML formatting

**Closed by aeschli** 2015-11-27 16:05 UTC

**Comment by danielo515** [comment] 2016-11-18 13:08
Sorry for commenting on an old issue, but I'm affected by this issue.
It is happening to me for javascript on version `1.7.1`. I can't do formatCode anymore, the only available option is format document.

Any hint?

**Comment by aeschli** [comment] 2016-11-18 14:48
@danielo515 Please file a separate issue. This issue is about formatting XML.
