### ISSUE TITLE
VSCode Remote runs too many threading on ssh server

### ISSUE THREAD

**Issue by huyp182** [microsoft/vscode#80245] opened 2019-09-03 04:27 UTC
Yesterday, I used VSCode Remote to develop the project on ssh server. In the morning, I cannot sign in my ssh server with my account, this is the error message:
Connection closing...Socket close. 
Connection closed by foreign host.

I sign in the ssh server with root account, and I saw so many vscode-server threadings, they are running the same JavaScript(js) file, and I killed them all, and then, I can sign in my ssh server with my account.

I think you should decrease the number of threadings in VSCode Remote.

**Comment by huyp182** [comment] 2019-09-03 04:28
And I don't know why the threadings were not killed when I disconnected from the ssh server and closed VSCode Remote.

**Comment by roblourens** [comment] 2019-09-04 23:36
Is your host low on memory?

If you see this again, can you try sshing into the host from a normal terminal to see if it works? Also please show the log from Remote-SSH output channel so I can see the full error message.

**Comment by huyp182** [comment] 2019-09-05 08:43
The memory is about 128GB, I think the number of the threadings run by VSCode Remote reached maximum the system allows.

**Comment by huyp182** [comment] 2019-09-05 08:43
I just wonder why the threadings aren't killed when I exit VSCode Remote.

**Comment by roblourens** [comment] 2019-09-05 17:24
VS Code remote's processes should be shut down after a few hours.

For that much memory, it seems likely that there is some extension using lots of memory or leaving processes around.

**Comment by huyp182** [comment] 2019-09-07 10:44
Yes, it's located at ~/.vscode-server/...... I have to go back to PyCharm Professional to use its remote development tool...

**Comment by XiangpengHao** [comment] 2019-09-10 04:15
same issue here, it generates about 70 threads with all other extensions disabled. No error/warning reported from the output. The executables are hashed, so I have no idea what they are doing.

The server has 300+GB memory and 96 threads, running Arch Linux with kernel "5.2.11-arch1-1-ARCH"

vscode version: 
```
Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

remote version: 0.46.0

![image](https://user-images.githubusercontent.com/6504314/64583627-84c22c00-d346-11e9-8b52-de3f32a1f6b3.png)

**Comment by huyp182** [comment] 2019-09-11 04:34
Yes, my situation is the same as his.

**Comment by roblourens** [comment] 2019-09-15 18:11
Which extensions are you both using, and can you show exactly which processes are using that much memory?

**Comment by XiangpengHao** [comment] 2019-09-15 20:24
can you take a look at this issue? https://github.com/microsoft/vscode-cpptools/issues/4222

Basically I only used vscode-cpptools and remote ssh.

vscode remote generates 70+ threads, and vscode-cpptools generates 200+ threads (and they speculate it's caused by vscode itself).

**Comment by huyp182** [comment] 2019-09-16 05:40
I used VSCode Remote and extension "Python" on VSCode Remote

**Comment by kenkit** [comment] 2019-10-15 17:11
I had to clean install my server several times.
I thought it was an issue with ec2 in US west, went all the way to setting up an instance in asia then I figured it was a low memory issue after multiple server lockups.
I use cpptools and cmake

**Comment by xemcerk** [comment] 2019-12-29 15:10
Similar situation here, but seems much more severe!!!

I'm using remote ssh feature and python extension on a host with 128GB memory. Today our administrator of that host told me that Microsoft.python process fire up 12000+ threads, which make him almost reboot the host, and now vscode is kept from that host.

I sincerely hope that you guy can fix it. I wanna keep using vscode other than anything else.

**Comment by xemcerk** [comment] 2019-12-29 15:17
And the experience using remote ssh these days is no good, since the connection failed every few minutes, and I have to retry multiple times. Sometimes even reload the window can't restore the connection.

Not sure whether it's the problem of ssh connection, xshell works fine most of the time.

**Comment by XiangpengHao** [comment] 2019-12-29 16:42
> 
> 
> Similar situation here, but seems much more severe!!!
> 
> I'm using remote ssh feature and python extension on a host with 128GB memory. Today our administrator of that host told me that Microsoft.python process fire up 12000+ threads, which make him almost reboot the host, and now vscode is kept from that host.
> 
> I sincerely hope that you guy can fix it. I wanna keep using vscode other than anything else.

Yep, similar case. My group has explicitly banned vscode because of that.

**Comment by roblourens** [comment] 2019-12-30 18:59
Please file an issue on the python extension for that, thanks.

**Comment by roblourens** [comment] 2019-12-30 19:01
And sorry that you've had this problem, but I haven't seen anything to suggest that VS Code itself is actually doing anything wrong here - I think the problem lies with extensions. I will close this.

**Closed by roblourens** 2019-12-30 19:01 UTC
Labels: freeze-slow-crash, remote

**Comment by fiorenza2** [comment] 2020-01-30 14:25
Appreciate this is closed, but this happens occasionally to me too (usually when I try to open a large data file on the remote in VSCode). The only way I've found to fix this is to kill the `.vscode-server` process in `htop`, and reload the window, at which point RAM usage returns to normal.

**Comment by syagawa** [comment] 2020-02-07 08:50
A similar situation in my environment.

Rails and VSCode remote on Centos7
on vagrant and virtualbox
host windows 10

Log in to Centos from windows host and start Rails.
Then start VSCode on Windows and log in to Centos with Remote-ssh.
And it takes about over 1 minute to read the localhost rails App in Chrome  browser.

When htop is started with Centos, CPU usage became 100%, and more than 30 vscode-server processes are running.
