### ISSUE TITLE
Shell task doesn't finish

### ISSUE THREAD

**Issue by mickeypearce** [Microsoft/vscode#37934] opened 2017-11-09 12:10 UTC
Running background shell task (gulp task with params) doesn't finish. 
Manual termination of task ends in "Assertion failed!" error by widpty.dll program.
Worked in previous version.

- VSCode Version: 1.18.0
- OS Version: Win 7 Enterprise

Steps to Reproduce:

Example tasks.json
`{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "my gulp shell task",
            "command": "gulp --color exportFilesFromDb --env=DEV --file=${file}",
            "isBackground": false
        }
    ]
}`
![image](https://user-images.githubusercontent.com/1925433/32604464-ffa2bc5e-c54d-11e7-9cbb-ecc99ea17106.png)
>task my gulp shell task

>Tasks: Terminate task
![image](https://user-images.githubusercontent.com/1925433/32604532-3a16d960-c54e-11e7-868c-5f02b26408be.png)

**Comment by dbaeumer** [comment] 2017-11-09 13:49
I couldn't reproduce this using a simple gulp file.

@mickeypearce can you provide a GitHub repository that demos this
@Tyriar assigning to you since the crash happens in winpty.dll

**Comment by mickeypearce** [comment] 2017-11-09 14:34
I made a simple demo repository (https://github.com/mickeypearce/vscode-taskproblem) that reproduces error on my machine. Please let me know if you can reproduce.

Screenshot after I run the task:
![image](https://user-images.githubusercontent.com/1925433/32610428-09704160-c563-11e7-9f1f-a602982c57e5.png)

**Comment by tomb-pss** [comment] 2017-11-10 03:39
Having the same issue with a simple task that runs a node script:

test.js:
`console.log("foobar");`

tasks.json:
![tasks](https://user-images.githubusercontent.com/26638278/32641904-901570f2-c60b-11e7-9e84-c7f6ed54dc77.png)

It shows foobar in the terminal but the task never ends. Terminating gives the exact same assertion popup. It just started when upgrading to 1.18.0.

**Comment by dbaeumer** [comment] 2017-11-10 09:57
The problem is that the terminal crashes and doesn't send a final event `onExit` event hence the task system thinks the task is still running. Hence you can't rerun the task.

@Tyriar since more people are seeing this can you please investigate. This might be a candidate for a recovery build.

**Comment by dbaeumer** [comment] 2017-11-10 09:58
Tried to reproduce this using the examples provided but was not able to do so.

**Comment by dbaeumer** [comment] 2017-11-10 11:13
@Tyriar to mitigate this it would help if the terminal service sends and event when the  terminal process crashes  / dies. Then the task service could at least clean up its state and the user could try to run the task again.

**Comment by Tyriar** [comment] 2017-11-10 17:26
I think the not finishing is this https://github.com/Microsoft/vscode/issues/31301

As for the assertion, I would guess it's a race condition related to the process leak fix https://github.com/Tyriar/node-pty/issues/122

https://github.com/Tyriar/node-pty/blob/01f79cfd3a222aaee2977fefde35ef798a921b38/src/windowsPtyAgent.ts#L99

**Comment by Tyriar** [comment] 2017-11-10 21:09
The assertion is actually happening in the new winpty API https://github.com/Tyriar/node-pty/blob/01f79cfd3a222aaee2977fefde35ef798a921b38/deps/winpty/src/libwinpty/winpty.cc#L942

**Comment by Tyriar** [comment] 2017-11-10 21:16
The error occurs when querying `winpty_get_console_process_list` when the pty handle has already been evicted from `ptyHandles`.

**Comment by Tyriar** [comment] 2017-11-10 21:16
Upstream issue: https://github.com/Tyriar/node-pty/issues/158

**Comment by Tyriar** [comment] 2017-11-10 21:54
PR is out https://github.com/Tyriar/node-pty/pull/160

**Closed** 2017-11-11 22:15 UTC
Labels: bug, candidate, important, integrated-terminal, upstream, windows

**Comment by Tyriar** [comment] 2017-11-12 00:41
Since the team had difficulty reproducing the issue, it would be great if someone that can repro could test this build to see if it still occurs: https://az764295.vo.msecnd.net/insider/5676c71a4c02632e14c97aefc049e339848552e6/VSCodeSetup-x64-1.18.0-insider.exe

**Comment by tomb-pss** [comment] 2017-11-12 01:01
That build fixed it for me. Tasks are finishing normally again.

**Comment by alex-smtv** [comment] 2017-11-12 23:02
I had a similar issue and that build also fixed it for me.

**Comment by mickeypearce** [comment] 2017-11-13 07:59
Same here.  It works.

**Comment by mikes-gh** [comment] 2017-11-17 11:23
October Recovery 1.18.1 fixes it for me thanks

**Comment by cwberick** [comment] 2017-11-17 11:56
to me too

**Comment by Tyriar** [comment] 2017-11-17 18:48
Thanks a lot for helping with verification 🙂
