### ISSUE TITLE
Integrated terminal copy doesn't copy all selected

### ISSUE THREAD

**Issue by Swailem95** [Microsoft/vscode#33757] opened 2017-09-03 17:39 UTC
- VSCode Version: 1.15.1
- OS Version: Win 10

Steps to Reproduce:

1. Open an integrated terminal in VSCode.
2. Select something from the terminal that is more than a few words in length and copy it.
3. Paste anywhere.

You'll see that the pasted fragment is generally a lot shorter than the copied fragment. Apparently the copy doesn't copy everything I highlight for some reason.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-09-06 04:00
Some follow ups:

- What shell are you using?
- What text are you copying and what is pasted?
- Can you provide a screenshot of the terminal with the "bad" selection?

**Comment by Swailem95** [comment] 2017-09-06 11:10
@Tyriar 

- Powershell but I get this error with the node shell too. 
- Regular logging and print statements from any file in any language. Nothing I copy is correctly pasted. 
- Here is an example of a simple print statement in Python. 
![img](https://i.imgur.com/65J4v89.jpg)

I copied "hello vscode" but when I pasted it just pasted "hello ". Apparently the copy only copies a shorter chunk of the selection because when I copy one line in a large log, the paste is a lot shorter than my selection which is why the only thing that is working now is that I just copy a huge part of the log, paste it in a new file and then copy the part I want. This really needs to be fixed.

**Comment by Tyriar** [comment] 2017-09-10 15:35
Many parts of the terminal break when you don't use monospace font, this is necessary to maintain good performance. Closing as designed.

**Closed by Tyriar** 2017-09-10 15:35 UTC
Labels: integrated-terminal, needs more info

**Comment by Swailem95** [comment] 2017-09-10 15:45
So it's going to remain broken just because that's not the default font?

**Comment by Tyriar** [comment] 2017-09-11 16:53
It's going to remain broken because it's not a monospace font, you should choose a monospace font.

**Comment by Swailem95** [comment] 2017-09-11 17:04
I really don't understand your logic. VSCode clearly takes customization seriously by allowing users to change settings to their liking but not fixing issues resulting from thematic/visual changes goes against what VSCode is trying to do. 

Might as well ship a fully non-customizable text editor if you don't want to deal with issues arising from customization, especially an issue as big as this one.
