### ISSUE TITLE
Completions do not automatically trigger when using Sogou Input Method

### ISSUE THREAD

**Issue by hengkx** [microsoft/vscode#140205] opened 2022-01-06 08:31 UTC
Issue Type: <b>Bug</b>

eg: tsx, less

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 7|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 6a2f593a-6fdd-42ba-b09b-190bb34c381d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
azure-blockchain|AzB|1.6.2
markdown-preview-github-styles|bie|0.2.0
vscode-tailwindcss|bra|0.7.4
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.1.0
vscode-jest-runner|fir|0.4.47
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.34.2
todo-tree|Gru|0.0.214
vscode-create-saga|hen|0.0.2
output-colorizer|IBM|0.1.2
solidity|Jua|0.0.136
sftp|lix|1.12.10
vscode-language-babel|mgm|0.0.35
code-beautifier|mic|2.3.3
azure-account|ms-|0.9.11
node-debug2|ms-|1.43.0
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.8.1
vetur|oct|0.35.0
vscode-jest|Ort|4.2.1
vscode-versionlens|pfl|1.0.9
polacode|pnp|0.3.4
minapp-vscode|qiu|2.4.6
quicktype|qui|12.0.46
vs-code-prettier-eslint|rve|3.1.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.1
code-spell-checker|str|2.0.14
sass-indented|syl|1.8.18
vscode-icons|vsc|11.8.0
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614
py55gd98:30419165
vscexrecpromp3t3:30407764

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-01-06 09:41
Please use the Start Extension Bisect command to investigate whether one of your extensions is causing your problem.

**Comment by hengkx** [comment] 2022-01-06 10:08
![image](https://user-images.githubusercontent.com/8358236/148366173-1645e3a2-fabc-45db-9e81-8fd67500104f.png)
Thank you very much. 
`vscode-tailwindcss` disabled css working.
Typescript  file IntelliSense not working

**Comment by hengkx** [comment] 2022-01-06 10:22
![Jan-06-2022 18-17-53](https://user-images.githubusercontent.com/8358236/148368013-78a8b690-2d73-45e2-b015-7e50bf77749c.gif)

**Comment by mjbvz** [comment] 2022-01-06 21:47
Please share steps and example code to reproduce the problem 

/neeedsMoreInfo

**Comment by hengkx** [comment] 2022-01-07 01:06
Any open ts or js files cannot work

**Comment by mjbvz** [comment] 2022-01-07 01:12
That's too vague. Please provide specific steps to reproduce the problem and describe the expected behavior

**Comment by hengkx** [comment] 2022-01-07 01:15
![1](https://user-images.githubusercontent.com/8358236/148475172-948bcf2b-8d1a-4938-98ac-cdb46cc471cf.gif)
Please see the gif file. Enter `a` in the ts or js file should have a smart prompt

**Comment by mjbvz** [comment] 2022-01-07 01:17
Your gif shows you have a bunch of extensions enabled.  Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also you should not be using the `Babel JavaScript` language mode. That comes from a very outdated extension

**Comment by hengkx** [comment] 2022-01-07 01:18
I tried again to disable all extensions and the problem still exists

**Comment by hengkx** [comment] 2022-01-07 01:20
![2](https://user-images.githubusercontent.com/8358236/148475609-aee59d42-b896-488b-b240-bd2b10d16422.gif)

**Comment by hengkx** [comment] 2022-01-07 01:21
Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by mjbvz** [comment] 2022-01-07 01:26
Thanks for testing. What are you doing in the gif though? The suggestions show once and then you rapidly keep deleting and inserting `a` before they show again? Describe exactly what isn't working

**Comment by hengkx** [comment] 2022-01-07 01:30
Insert `a` should always IntelliSense

**Comment by hengkx** [comment] 2022-01-07 01:33
![3](https://user-images.githubusercontent.com/8358236/148476634-7bd24646-382f-45a7-9997-2424885d7bbc.gif)
Insert `a` no any IntelliSense

**Comment by mjbvz** [comment] 2022-01-07 01:34
What if you manually trigger IntelliSense with ctrl+space?

**Comment by hengkx** [comment] 2022-01-07 01:36
> What if you manually trigger IntelliSense with ctrl+space?

No effect

**Comment by mjbvz** [comment] 2022-01-07 01:40
Ok, please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

If you can share the log, I can take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by hengkx** [comment] 2022-01-07 01:40
> > What if you manually trigger IntelliSense with ctrl+space?
> 
> No IntelliSense

I disable system shortcut and restart vscode.   Enter ctrl+space
![image](https://user-images.githubusercontent.com/8358236/148477274-1379274c-db93-4b94-bcb4-f0a7e90c6a18.png)

**Comment by hengkx** [comment] 2022-01-07 01:43
> 3\. ypeScript: Open TS Serv

Sorry. Please see the previous reply

**Comment by mjbvz** [comment] 2022-01-07 01:44
So this is caused by your keybindings or some operating system keybinding? If so, please close the issue

**Comment by hengkx** [comment] 2022-01-07 01:45
Why can't it be triggered automatically and need to be triggered manually IntelliSense

**Comment by mjbvz** [comment] 2022-01-07 01:48
Check your keybindings and user configuration to make sure you have not disabled quick suggestions. Then if it still isn't working, collect the logs as I explained

**Comment by hengkx** [comment] 2022-01-07 02:05
[tsserver.log](https://github.com/microsoft/vscode/files/7825816/tsserver.log)
This is log file

**Comment by mjbvz** [comment] 2022-01-07 02:11
That log doesn't show any calls to `completionInfo`. This suggests to me that suggestions are never being triggered at all

Please share your uses settings. Also what keyboard layout are you using?

**Comment by hengkx** [comment] 2022-01-07 02:12
// Place your settings in this file to overwrite the default settings
{
  "files.eol": "\n",
  "javascript.validate.enable": false,
  "git.confirmSync": false,
  "git.enableSmartCommit": true,
  "sync.gist": "a9c3252df9b1cf50938f4a7368813527",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.forceDownload": false,
  "sync.quietSync": false,
  "files.autoSave": "off",
  "explorer.confirmDelete": false,
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "workbench.iconTheme": "vscode-icons",
  "bracket-pair-colorizer-2.colors": [],
  "bracket-pair-colorizer-2.scopeLineCSS": [
    "borderStyle : solid",
    "borderWidth : 1px",
    "borderColor : Orchid",
    "opacity: 1"
  ],
  "bracket-pair-colorizer-2.showHorizontalScopeLine": false,
  "cSpell.ignoreWords": ["devtools", "collapsed"],
  "typescript.updateImportsOnFileMove.enabled": "always",
  "code-runner.clearPreviousOutput": true,
  "code-runner.runInTerminal": true,
  "cSpell.userWords": [
    "alipay",
    "aliyun",
    "antd",
    "appcenter",
    "BIGINT",
    "bodyparser",
    "checkin",
    "codepush",
    "eslintignore",
    "hengkx",
    "hengkx's",
    "hzwl",
    "ibkr",
    "ipfs",
    "longtext",
    "mobx",
    "nestjs",
    "pnls",
    "Popconfirm",
    "preinstall",
    "qiankun",
    "Sider",
    "stylelint",
    "tushare",
    "typeorm",
    "wechat",
    "zhian"
  ],
  "files.associations": {
    "*.cjson": "jsonc",
    "*.wxss": "css",
    "*.wxs": "javascript"
  },
  "minapp-vscode.disableAutoConfig": true,
  "todo-tree.highlights.enabled": true,
  "eslint.format.enable": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "prettier.jsxBracketSameLine": true,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  "markdown-pdf.displayHeaderFooter": false,
  "jestrunner.jestCommand": "npm test --",
  "jest.enableCodeLens": false,
  "workbench.startupEditor": "newUntitledFile",
  "markdown-preview-enhanced.previewTheme": "github-light.css",
  "security.workspace.trust.untrustedFiles": "newWindow",
  "vsicons.dontShowNewVersionMessage": true,
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook"
  },
  "notebook.cellToolbarLocation": {
    "default": "right",
    "jupyter-notebook": "left"
  },
  "less.lint.unknownAtRules": "ignore",
  "[solidity]": {
    "editor.defaultFormatter": "JuanBlanco.solidity"
  },
  "editor.tabCompletion": "on",
  "emmet.triggerExpansionOnTab": true
}

**Comment by hengkx** [comment] 2022-01-07 02:13
I think it may be the problem of Sogou input method. Switching to the system input method is normal

**Comment by mjbvz** [comment] 2022-01-07 02:18
@alexdima @rebornix Can you please follow up since this looks related to input handling?

**Comment by alexdima** [comment] 2022-01-11 20:06
@hengkx Unfortunately, we cannot support all 3rd party input methods, but we offer support for the platform native ones. And in this case the following works for me using [the latest insiders](https://code.visualstudio.com/insiders/):
* I change my input method to "Pinyin - Traditional"
* I open a typescript file with the following content:
```ts
function f() {
    const abc = 3;
    
}
```
* I press `a`
* this causes (as expected) for the IME suggestions to pop up
* I accept `a` by pressing <kbd>Enter</kbd>
* this causes quick suggestions to show up:

https://user-images.githubusercontent.com/5047891/149013427-4d96b3c2-5fdb-4397-886d-22689bb79046.mp4

**Comment by hengkx** [comment] 2022-01-12 00:47
> Unfortunately, we cannot support all 3rd party input methods, but we offer support for the platform native ones. And in this case the following works for me using [the latest insiders](https://code.visualstudio.com/insiders/):
> 
> * I change my input method to "Pinyin - Traditional"
> * I open a typescript file with the following content:

NO. I have switched the English input state when using Sogou input method.It was normal before. Suddenly there was no IntelliSense. I don't know what happened

**Comment by alexdima** [comment] 2022-01-14 12:02
@hengkx This has been improved in the latest insiders, I believe via https://github.com/microsoft/vscode/issues/83428 or https://github.com/microsoft/vscode/pull/139394 . Please [try out the Insiders version](https://code.visualstudio.com/insiders/):

https://user-images.githubusercontent.com/5047891/149512340-7224cfe6-e685-4e59-bbdb-f3fc88eac8be.mp4

**Closed by alexdima** 2022-01-14 12:02 UTC
Labels: needs more info, macos, suggest, editor-input-IME

**Comment by wykun1120** [comment] 2022-01-15 07:40
I have also the same problem. there was no IntelliSense when use the Sogou Input Method, but it's work when I use native input method

**Comment by wykun1120** [comment] 2022-01-15 15:00
I reinstalled Sougou Input Method and vscode worked normal.
@hengkx
