### ISSUE TITLE
Emmet css abbreviation not expanded in style block in html file

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#28039] opened 2017-06-05 13:53 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-reveal|evilz|0.0.9|
|php-intellisense|felixfbecker|1.3.0|
|auto-close-tag|formulahendry|0.4.2|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-icons|robertohuertasm|7.8.1|
|Material-theme|zhuangtongfa|2.8.4|;

---

Steps to Reproduce:
(you can use any css property, this was my first, real-world, live example)
1. Open up https://docs.emmet.io/cheat-sheet/ and search for `d:b`
2. See that emmet usually resolves it to `display: block;`
3. Go to Visual Studio Code
4. Set up your environment:
![image](https://cloud.githubusercontent.com/assets/11234139/26786443/f7769d6a-4a06-11e7-8c98-402b8cd08ec8.png)
5. Type `d:b` and hit `Tab`/`Enter`/...
6. Get this:
![image](https://cloud.githubusercontent.com/assets/11234139/26786496/26ef172a-4a07-11e7-8a7f-960c61eaa870.png)
7. Get worried.

**Comment by jens1o** [comment] 2017-06-05 14:08
I created this issue, because it is not mentioned here: https://github.com/Microsoft/vscode/issues/27697 
Did you missed it?

**Comment by ramya-rao-a** [comment] 2017-06-05 15:04
This works in css/scss/less files, but not inside the `style` block of a html file.
Good catch.

**Comment by ramya-rao-a** [comment] 2017-06-05 17:46
I initially thought that the completion provider for css from emmet does not get called here because the document has the html language mode

But interestingly, the built-in css completion provider does get called.

![image](https://cloud.githubusercontent.com/assets/16890566/26795802/cbfb9436-49db-11e7-9249-ade571ad68e6.png)

@aeschli @jrieken How is that in the above case the built-in css completion provider is called but not the emmet css completion provider?

If the css extension/language server does something special to be able to provide completion items in html file, what do you suggest other extensions who want to do the same do?

**Comment by jrieken** [comment] 2017-06-06 07:56
> How is that in the above case the built-in css completion provider is called but not the emmet css completion provider?

It always depends on the language you are registering for. I'd say that inside `style`-tags we use `css` as language and therefore only call completion item providers that have registered for `css`

**Comment by ramya-rao-a** [comment] 2017-06-07 17:32
@jrieken See https://github.com/Microsoft/vscode/blob/ramyar/emmet-fixes/extensions/emmet/src/extension.ts#L54

I have 2 separate completion providers for html vs css
While inside `style` tag, the one for html gets called and not the css.

should we specify anything else in the DocumentSelector for VS code to use the registered completion provider for embedded languages?

**Comment by jrieken** [comment] 2017-06-08 07:52
Hm, that looks correct... Would require some debugging in `suggest.ts` where we merge the results etc. Is this locally reproducible with those steps?

**Comment by ramya-rao-a** [comment] 2017-06-08 14:10
@jrieken Yes. The changes are in master, so you can try this locally.

**Comment by jrieken** [comment] 2017-06-08 15:53
Funky.. If I press `d` I see completions coming from emmet, also checking what completion provider buckets we have it seems that there are two registered fro CSS.

<img width="615" alt="screen shot 2017-06-08 at 17 48 11" src="https://user-images.githubusercontent.com/1794099/26937974-2c44eeac-4c73-11e7-9b1a-5879a0aec68a.png">

<img width="345" alt="screen shot 2017-06-08 at 17 50 13" src="https://user-images.githubusercontent.com/1794099/26938016-4bbfe9bc-4c73-11e7-973f-b2aa13331b8a.png">

**Comment by ramya-rao-a** [comment] 2017-06-08 16:39
> If I press d I see completions coming from emmet

Yes, that is from emmet. If you expand the docs you will see the preview for the expansion.

In your case above, the completion item is coming from the html completion provider in emmet i.e for `d`  you get `<d>/</d>` where as the css completion provider would have given `display:block`

> also checking what completion provider buckets we have it seems that there are two registered fro CSS.

The first one must be coming from the html extension.
The second one is the html completion provider from emmet. ( I can tell the difference from the trigger chars. For css they would have been just `:`.)
This one should have been the css completion provider from emmet.

> Also, when I invoke suggestions inside an empty rule (remove d) I see this

I dont see that in Insiders but I see that in the locally built VS Code. Weird.. how is that? We dont surface errors from extensions in a non dev env?

**Comment by jrieken** [comment] 2017-06-08 17:45
Ok, now I know what's up. @aeschli Will have all the detail but I remember correctly nested languages aren't surfaced like that. While we have a scope `source.css` inside the html-file we actually treat all contents as html and call into html-providers which then must do the correct thing.

**Comment by ramya-rao-a** [comment] 2017-06-08 18:04
😭

**Comment by ramya-rao-a** [comment] 2017-06-08 18:05
And of course, we don't expose the scope to extensions.

You know this is like the 4th time I get to this crossroads of needing scopes in extensions 😢

**Comment by jens1o** [comment] 2017-06-08 18:25
Why did you decided to split off and make emmet an internal extension?

**Comment by jrieken** [comment] 2017-06-08 18:40
> Or suggestions to extensions on any workaround?

I think @aeschli has a re-usable html parser (on npm) that you could use to figure out if you are in css or not. And then that info will be reliable, not based tokens (see attached screen shot, the css-scope only starts on the next line)

<img width="587" alt="screen shot 2017-06-08 at 20 39 02" src="https://user-images.githubusercontent.com/1794099/26944980-9ee2b824-4c8a-11e7-8bad-2de8db31d042.png">

**Comment by ramya-rao-a** [comment] 2017-06-09 04:24
@jrieken Thanks, the emmet modules has a parser as well which I am using for other emmet features. Will try that.

@jens1o Do you mean to ask why is it internal extension vs external extension? Or why is it an extension at all?

**Comment by jens1o** [comment] 2017-06-09 06:28
@ramya-rao-a internal vs. external, when you have so many problems, why did you decided to switch so fast, even when there are no apis available?

**Comment by ramya-rao-a** [comment] 2017-06-09 15:46
> Why so fast?

@jens1o Well I'd say not fast enough :) The 2 issues with current emmet integration in VS Code as described here: https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list are the main reasons to move to the newer model of using the suggestion list for emmet. Over the past year we have had many users face this issue and moving to the suggestion model was the right move.

> Why internal extension vs external extension?

Emmet has been a feature shipped with VS Code since the beginning. Making it an external extension would require users to install it explicitly. Therefore, the decision for internal vs external.

> Why an extension at all? Why not build it inside VS Code like current emmet?

Emmet features are not core to an editor per say. These are add-ons. And so make sense more as an extension. 

Initially, the way emmet library worked, it was not possible to have it as an extension for VS Code. For Atom, say it was possible because it has a different extensibility model, it is hackable at every level. Now, that @sergeche has modularized the core logic of emmet, we can now have emmet expansion coming from completion providers and rest of the emmet features from an extension.

> Why switch now? Apis are not ready!!!

Unlike @sergeche or many power users of emmet I don't have the luxury of knowing emmet and all its scenarios in and out. Because I don't use emmet at all in my job. That's why I depend on amazing people like you to dogfood the initial implementation and come up with the corner cases where the feature doesn't work. Thanks to the open source model of things, we can do that :) i.e work together to hash out scenarios

As @sergeche suggested here: https://github.com/Microsoft/vscode/issues/27628#issuecomment-306904762, we can still parse the file in an efficient way to get the info we need to solve both this and the linked issue. So even if scope info or the nested language info is not available as apis, we can still do this. 

Worst case scenario, I can easily move the new emmet from the internal extension to VS Code core and make use of the scope info available there. 

Either way, by the end of the June milestone, we are going to have a great emmet experience

**Comment by jens1o** [comment] 2017-06-09 15:53
Wow, thanks for the detailed answer. I'll continue to work with it(and report odd things), to help you. 😋

**Comment by ramya-rao-a** [comment] 2017-06-19 06:18
The fix will be out in the Tuesday's Insiders

**Comment by CnSimonChan** [comment] 2017-06-19 10:13
@ramya-rao-a You only changed the Completion Provider, but not the actions (at least expandAbbreviation action)?

And another problem: You implementation **will** provide emmet in the start tag of a `style` element, because you [set](https://github.com/Microsoft/vscode/blob/6757e57fe839b51597ec344e89696b72e98ec379/extensions/emmet/src/emmetCompletionProvider.ts#L35-L37) the `syntax` to `css` for this tag.

```` HTML
<style |>
````

I'm working on a tool for my team with monaco-editor and trying to backport the new emmet vscode extension to monaco (Now the Completion Provider and expandAbbreviation action just work). I had never used emmet before neither, but now I think the implementation will be very complex: you need to handle normal HTML, in `style` attribute (doesn't need selectors) and in `style` element (need selectors) very differently.

**Comment by sergeche** [comment] 2017-06-19 10:20
@ramya-rao-a you have to check if cursor is not inside `.open` or `.close` tag token to fix the problem that @CnSimonChan pointed.

**Comment by ramya-rao-a** [comment] 2017-06-19 14:57
@CnSimonChan I had another task in mind to consolidate the code between the completion provider and the action which I was planning to do today which would cover your concern. 

And good catch on the `style` tag, will add the check on the tag as well. Will re-open this issue until this is fixed. Thanks for reporting!


@sergeche For now I am using https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/emmetCompletionProvider.ts#L134 for validating the position. I'll take another look at the atom implementation to ensure I have not missed any other cases.

**Comment by ramya-rao-a** [comment] 2017-06-20 01:05
@CnSimonChan With https://github.com/Microsoft/vscode/commit/8902a30b1274623e317b772447f7017884301fe6 you now have the same validations being run and syntax being used by the completion provider and the expand abbreviation action. 
- css inside style element
- no expansions inside the open tag for style element

You bring up another good point about the style attribute. Logged #29066 for the same.

Yes, things are getting complex in this model where a lot of work has moved from emmet to editor.
I am not sure what it takes for the new emmet functionality to be ported to monaco editor, but I can look into it and get back to you.

**Closed by ramya-rao-a** 2017-06-20 01:05 UTC
Labels: bug, emmet, insiders

**Comment by CnSimonChan** [comment] 2017-06-20 06:50
@ramya-rao-a It works very well now, maybe another improvement will be re-parse the content of `<style>` tag as css to provide emmet only for rules.

For monaco, I wrote a minimal compatibility layer to bridge monaco's `IStandaloneCodeEditor` and `IModel` to vscode's `TextEditor` and `TextDocument` , then bridge vscode's `CompletionItemProvider` to monaco one. I'm not familiar with vscode and I can't find any relative code in the repo so maybe I'm doing something redundant.

I have two more question with this extension:

1. My `npm@5` crashed when restoring packages for this extension, it seems the `npm-shrinkwarp.json` file caused the crash, I deleted this file then it restores correctly.

2. Do you have definition files for emmet packages somewhere? I found one in `src` folder but looks like it's for the old all-in-one version. Or you just work with `any`?

**Comment by ramya-rao-a** [comment] 2017-06-20 15:02
>  re-parse the content of <style> tag as css

I gave this a thought, but will not be doing this for the current iteration. Logged #29113 and added a help-wanted label on it.

> npm@5 crashing

Not sure about this. The shrink-wrap is used during shipping time, so not needed during the development phase. Did you try with a lower npm version?

> Definition for emmet modules

Ahhh... This is something I have been needing as well. @sergeche Could you help here ?

**Comment by CnSimonChan** [comment] 2017-06-20 15:27
> Did you try with a lower npm version?

No, I have only 5.

> Definition for emmet modules

I have `noImplicitAny` on so I wrote some definition by myself, just covered the need of the extension (although I'm not very clear about the return type of `html-matcher` and `css-parser`). It's better if someone good at creating type definition can help, but if not I will post it tomorrow (after 10 hours) and hope it can be useful.

**Comment by ramya-rao-a** [comment] 2017-06-26 05:21
Note to verifier:
- Set `emmet.useNewEmmet` to `true`
- You should get css related emmet suggestions inside a <style> block and no suggestions at all inside the open tag of the <style> tag
