### ISSUE TITLE
Broken syntax highlighting for javascript by inline comment

### ISSUE THREAD

**Issue by ViktorQvarfordt** [Microsoft/vscode#57041] opened 2018-08-22 20:01 UTC
- VSCode Version: 1.26.1
- OS Version: Windows 10

Steps to Reproduce:

1. In a window with language mode: Javascript, type what is shown in the picture, and observe how syntax highlighting is broken after the inline comment.
![image](https://user-images.githubusercontent.com/344809/44487345-5cda2a80-a656-11e8-8c9a-82f6c1c0e3f1.png)

As far as I can see, this only happens for an inline comment that follows a declaration, if the inline comment is not followed by two newlines.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Eurkidu** [comment] 2018-08-23 02:41
I found the same problem in #56522

**Comment by mjbvz** [comment] 2018-08-23 08:39
Duplicate of #56522

Should be fixed in next insiders

**Closed by mjbvz** 2018-08-23 08:39 UTC
Labels: javascript
