### ISSUE TITLE
Right-click on folder wants to delete folder

### ISSUE THREAD

**Issue by peterroelants** [microsoft/vscode#131527] opened 2021-08-24 14:53 UTC
Issue Type: <b>Bug</b>

Right-clicking on a folder imidiatly also activates the "Delete" menu option asking to delete the right-clicked folder

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.10.0-1044-oem snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.45GB (41.20GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 5c9a50b9-bd3a-4be9-9291-1eafc0d80ebc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
vscode-css-formatter|aes|1.0.1
vscode-sqlite|ale|0.13.0
toml|be5|0.5.1
gitlens|eam|11.6.0
nbpreviewer|jit|1.2.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.16.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
es6-css-minify|olb|3.3.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
code-spell-checker|str|1.10.2
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn420:30356812

```

</details>

See also: 
![delete](https://user-images.githubusercontent.com/951093/130639298-37d099b2-a1c3-455e-820c-3ebcc1aeeabb.gif)

**Comment by san-coding** [comment] 2021-08-24 15:13
unable to reproduce  on 
`Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:57:20.140Z (5 days ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin arm64 20.6.0`

**Comment by JacksonKearl** [comment] 2021-08-24 18:46
I can reproduce. Requires `window.titleBarStyle: native` and the entry to be a collapsed folder (when multiple folder entries are on the same line because they contain only a single item). Also the item must be towards the bottom of the screen so that the context menu rises upwards. It seems the single click is causing two actions, opening the context menu and triggering whatever entry is underneath the cursor once the context menu appears. 

cc @sbatten and @joaomoreno any ideas here? 

@peterroelants you should be able to get around this by setting `window.titleBarStyle` to `custom`.

**Comment by sbatten** [comment] 2021-08-24 20:10
seems like a dupe of https://github.com/microsoft/vscode/issues/113175

**Closed** 2021-08-24 22:42 UTC
Labels: bug, file-explorer, *duplicate, tree-widget, menus
