### ISSUE TITLE
Emmet completion missing if there errors in file

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44840] opened 2018-03-01 14:46 UTC
Verifying #33115

1.20.1 Shows a completion:

![image](https://user-images.githubusercontent.com/9205389/36850651-a5effc7c-1d67-11e8-8a25-16abb3bb01d2.png)

where 1.21.0-insiders doesn't:

![image](https://user-images.githubusercontent.com/9205389/36850686-b9d68aee-1d67-11e8-9dd4-91131cfa2ed6.png)

Not sure if that intended.

**Comment by ramya-rao-a** [comment] 2018-03-01 18:30
Emmet completions have moved to the css extension in 1.21
The above content has errors and the css extension doesn't provide completions in a position that comes after a place that has errors. In this case there is error in line 3, so all css features stop there.

Closing as by design for now.
We'll see what the user reaction is.

**Comment by ramya-rao-a** [comment] 2018-03-01 20:58
On second thoughts, this might not be desirable.
One advantage of emmet completions is that they work even if css completions don't.
Will revert the move to css extension until we resolve the upstream issue of the css language service not able to parse the complete document when there are errors.

**Closed** 2018-03-01 21:00 UTC
Labels: bug, emmet
