### ISSUE TITLE
OmniSharp will never start under macOS 10.12 Sierra!

### ISSUE THREAD

**Issue by unalone** [Microsoft/vscode#11818] opened 2016-09-10 07:15 UTC
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:27:44.726Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Install C# support
2. Open any project, and the status of OmniSharp will always "Starting..."

**Comment by ramya-rao-a** [comment] 2016-09-11 19:12
@unalone  

- Which extension did you install for the C# support? 
- Did the installation complete successfully? 

This issue should be logged against the extension first. It can be moved back here if the extension owners conclude that the issue is with VS Code.

@joaomoreno Anything we can do from our side before moving this issue to the extension?

**Comment by joaomoreno** [comment] 2016-09-12 07:35
Nope, move it.

**Comment by unalone** [comment] 2016-09-12 08:44
Ok,
The reason for this problem is, the Mono and the DotNet installer doesn’t finish well, so the C# plugin cannot find the mono and dotnet command to use.

To fix it, I have to add the location of dotnet and mono to the PATH env manually, also, I have to install the Beta version mono: 4.6.0.182.

**Comment by ramya-rao-a** [comment] 2016-09-12 17:14
@unalone Closing the issue as resolved

**Closed by ramya-rao-a** 2016-09-12 17:14 UTC
