### ISSUE TITLE
"Open Settings" no longer has a keybinding

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160246] opened 2022-09-07 05:01 UTC
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/900690/188792517-fc657956-0181-46c1-9db3-a92381a7203e.png">

**Comment by gjsjohnmurray** [comment] 2022-09-07 06:20
See also #159875 which I confirmed on Windows but @rzhao271 was unable to reproduce.

**Comment by bpasero** [comment] 2022-09-07 06:24
If I had to guess: https://github.com/microsoft/vscode/commit/3b26f306d8e7373947acd772106047c5dbb20427

**Comment by rzhao271** [comment] 2022-09-07 17:39
Duplicate of #159875

**Closed by rzhao271** 2022-09-07 17:39 UTC
Labels: important, regression
