### ISSUE TITLE
Debug panel hidden if global launch configs but no workspace launch configs

### ISSUE THREAD

**Issue by dwelch2344** [microsoft/vscode#87886] opened 2019-12-30 16:01 UTC
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```
Steps to Reproduce:

1. Create global launch configs in `settings.json` like the following:
```json
// ....
"launch": {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "Jest Current File",
        "program": "${workspaceFolder}/node_modules/.bin/jest",
        "args": [
          "${relativeFile}",
          
          "--no-cache"
        ],
        "console": "integratedTerminal",
        "env": {
          "NODE_ENV": "test"
        },
        "internalConsoleOptions": "neverOpen",
        "skipFiles": [
          "<node_internals>/**"
        ]
      },
      {
        "type": "node",
        "request": "launch",
        "name": "nodemon",
        // "runtimeExecutable": "nodemon",
        // "program": "${workspaceFolder}/${relativeFile}",
        "program": "/Users/welch/.npm-global/bin/nodemon",
        "args": [
          "${relativeFile}"
        ],
        "restart": false,
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen",
        // "protocol": "inspector",
        "env": {
          "NODE_ENV": "localhost"
        }
      }
}, 
// ...
```
2. Observe that they're not available for debug, with the following panel showing up:
<img width="340" alt="missing" src="https://user-images.githubusercontent.com/160142/71589649-db649900-2ae2-11ea-92ce-8c52109a6161.png">

3. Add a local launch config, of any type, and see the global options now available
<img width="366" alt="found" src="https://user-images.githubusercontent.com/160142/71589675-e9b2b500-2ae2-11ea-843b-1d3a9cc6600e.png">

Pretty minor and guessing a simple edge case on a check. Happy to help contribute if someone could point me in the right direction :)

**Comment by isidorn** [comment] 2019-12-31 11:06
Thanks for filling this issue however I can not reproduce with latest vscode insiders.
I believe this is somewhat a duplicate of https://github.com/microsoft/vscode/issues/87324
Which I have fixed. Thus closing as duplicate

@dwelch2344 please let me know if you can reproduce with vscode insiders and I will reopen https://code.visualstudio.com/insiders/

**Closed by isidorn** 2019-12-31 11:06 UTC
Labels: bug, debug
