### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by MISfang** [microsoft/vscode#174315] opened 2023-02-14 07:04 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230210

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-lit-html-plugin`
- `typescript-vue-plugin-forward`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33923:11)
    at parseSimpleUnaryExpression (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33552:16)
    at parseUnaryExpressionOrHigher (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33520:35)
    at parseBinaryExpressionOrHigher (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33438:25)
    at parseAssignmentExpressionOrHigher (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33111:18)
    at parseExpression (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:33077:16)
    at doOutsideOfContext (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30772:12)
    at allowInAnd (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30793:12)
    at parseExpressionOrLabeledStatement (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:34593:24)
    at parseStatement (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:34825:12)
    at parseListElement (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:31544:12)
    at parseList (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:31529:19)
    at parseSourceFileWorker (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30588:24)
    at Object.parseSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30421:20)
    at createSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:30282:21)
    at createLanguageServiceSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:134900:22)
    at acquireOrUpdateDocument (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:131822:26)
    at Object.acquireDocumentWithKey (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:131747:12)
    at getOrCreateSourceFileByPath (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135225:31)
    at Object.getOrCreateSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135205:14)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135137:42
    at Object.getSourceFileWithCache [as getSourceFile] (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:116904:24)
    at findSourceFileWorker (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119236:23)
    at findSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119156:20)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119105:22
    at getSourceFileFromReferenceWorker (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119074:26)
    at processSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:119103:5)
    at processRootFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:118899:5)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:117684:41
    at forEach (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:2308:22)
    at createProgram (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:117684:5)
    at synchronizeHostData (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135161:15)
    at Proxy.getProgram (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:135233:5)
    at ConfiguredProject2.updateGraphWorker (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:171784:41)
    at ConfiguredProject2.updateGraph (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:171721:32)
    at ConfiguredProject2.updateGraph (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:172903:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:174510:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:175601:26)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:175881:64
    at flatMap (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:175881:24)
    at updateOpen (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:177026:29)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:179593:69
    at IpcIOSession.executeWithRequestId (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:179585:14)
    at IpcIOSession.executeCommand (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:179593:29)
    at IpcIOSession.onMessage (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:179635:51)
    at process.<anonymous> (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302100/node_modules/typescript/lib/tsserver.js:181203:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.75.0 (Universal) (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 21.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|59, 71, 91|
|Memory (System)|16.00GB (1.03GB free)|
|Process Argv|--crash-reporter-id c42fef7a-e5b5-480b-a982-505a214e493f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (159)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
node-js-snippet|abd|1.1.3
stylus|Ala|0.0.4
react-hooks-snippets|AlD|1.2.0
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
midway-vscode-plugin|ali|0.8.0
preview-pdf|ana|1.0.0
vscode-json|and|1.5.2
jsx-html-tags|ang|1.0.1
ng-template|Ang|15.1.0
vscode-ant-design-vue-helper|ant|1.0.6
iconify|ant|0.4.2
color-info|bie|0.7.2
lit-html|bie|1.11.1
vscode-styled-jsx|bla|2.1.1
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
cssrem|cip|3.0.2
vscode-css-modules|cli|0.4.2
vscode-redis-client|cwe|6.1.9
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|2.4.0
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
vscode-great-icons|emm|2.1.90
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.5.0
carbon-now-sh|eri|1.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|9.10.4
vscode-highlight|fab|1.7.2
mithril-emmet|Fal|0.7.7
css-stacking-contexts|fel|1.0.15
file-icons|fil|1.0.29
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-yarn|gam|2.1.0
vscode-pull-request-github|Git|0.58.1
jsx-beautify|gog|0.0.5
vscode-graphql|Gra|0.8.5
vscode-graphql-syntax|Gra|1.0.6
todo-tree|Gru|0.0.224
vscode-drawio|hed|1.6.6
headwind|hey|1.7.0
stylus-suggestion|hfc|1.0.6
vue-snippets|hol|1.0.4
rest-client|hum|0.25.1
vscode-react-typescript|inf|1.3.1
vscode-postfix-ts|ipa|1.12.0
search-node-modules|jas|1.3.0
svg|joc|1.5.0
react-native-snippet|jun|0.5.6
vscode-gutter-preview|kis|0.30.0
sequelize-snippets|kvc|1.0.0
px-to-vw|lee|1.0.2
node-module-intellisense|lei|1.5.0
project-tpl|lij|0.0.3
i18n-ally|lok|2.8.1
eslint-rules-zh-plugin|mag|0.2.1
json-to-ts|Mar|1.7.5
git-graph|mhu|1.30.0
code-beautifier|mic|2.3.3
sort-typescript-imports|mic|1.4.1
fluent-icons|mig|0.0.18
formate|Mik|1.2.1
dotenv|mik|1.0.1
vue-volar-extention-pack|Mis|1.1.6
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.2.0
vscode-extension-auto-import|mop|1.3.3
vscode-csscomb|mrm|5.3.2
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.23.3
vscode-language-pack-zh-hans|MS-|1.75.2023020809
makefile-tools|ms-|0.6.0
powershell|ms-|2023.1.0
vscode-typescript-next|ms-|5.0.202302130
vscode-react-native|msj|1.10.0
color-highlight|nau|2.5.0
tslint-vue-tsx|nob|1.0.0
vscode-extension-auto-import|Nuc|1.4.3
indent-rainbow|ode|8.3.1
vue-beautify|pea|2.0.4
material-icon-theme|PKi|4.24.0
material-product-icons|PKi|1.4.1
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.2.0
prisma|Pri|4.10.1
prisma-insider|Pri|31.0.1937
tslint-vue|pro|1.5.6
promise-snippets|pro|0.3.2
view-in-browser|qin|0.0.5
developer-theme-dark|Raj|5.0.0
typescript-hero|rbb|3.0.0
vscode-yaml|red|1.11.0
html-to-jsx|ria|0.0.1
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
nunjucks|ron|0.3.1
vs-code-prettier-eslint|rve|5.0.4
vscode-javascript-booster|sbu|14.0.1
vue-vscode-snippets|sdr|3.1.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.4.1
markdown-preview-enhanced|shd|0.6.7
vue-helper|she|2.4.7
file-tree-generator|Shi|1.1.1
vscode-scss-formatter|sib|2.4.5
indenticator|Sir|0.7.0
js-jsx-snippets|sky|11.0.1
vscode-standard|sta|2.1.3
autoimport|ste|1.5.4
addDocComments|ste|0.0.8
move-ts|str|1.12.0
vscode-stylelint|sty|1.2.3
sass-indented|syl|1.8.24
language-stylus|sys|1.16.0
chinese-color|tai|1.1.5
ayu|tea|1.0.5
open-in-browser|tec|2.0.0
vs-code-node-require|tgr|1.10.2
vscode-snippets|the|0.1.3
stylus-supremacy|thi|2.17.5
react-redux-es6-snippets|tim|2.1.0
altitude-script-language|uca|0.0.3
vscode-choosealicense|ult|0.9.2
codelf|unb|11.7.0
vscode-mdx|uni|1.2.1
errorlens|use|3.7.0
highlight-matching-tag|vin|0.10.1
vscode-js-console-utils|vsc|1.2.2
vscode-icons|vsc|12.2.0
volar|Vue|1.0.24
vscode-typescript-vue-plugin|Vue|1.0.25
sneak-mark|wan|0.0.6
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
eno|Wsc|2.3.53
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
txt-syntax|xsh|0.2.1
vscode-mdx-preview|xyc|0.3.3
axios-snippets|Ygg|1.0.0
markdown-all-in-one|yzh|3.5.0
json|Zai|2.0.2
material-theme|zhu|3.15.6
tslint-snippets|zuo|1.1.0

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30657577
89544117:30613380
pythonsymbol12cf:30657549
2i9eh265:30646982

```

</details>

**Comment by mjbvz** [comment] 2023-02-21 02:27
Duplicate of https://github.com/vuejs/language-tools/issues/2434

As the issue reporter noted, this is likely caused by one of the Vue extensions you have installed. Please following up with the correct extension so that they can investigate and fix this

**Closed by mjbvz** 2023-02-21 02:27 UTC
