### ISSUE TITLE
Display total number of found entries after a search

### ISSUE THREAD

**Issue by sergiofigueras** [Microsoft/vscode#36933] opened 2017-10-25 19:19 UTC
Hello guys,

I've a suggestion and I would like to share with you and get your thoughts on that as well. As vscode is such a versatile code editor, sometimes we also use it as a text editor, since its quite simple, just press Cmd + N and you've a new beauty tab.

But unfortunately, there's one condition on it that I did not seen in Atom, Sublime, or even simple text editors / log stream readers. Its about displaying the total amount of found entries in a search. And as I couldn't find an option to configure it, I'm assuming that its the default behavior of vscode.

It would be nice if users could see the number of found entries on search, but unfortunately it seems that vscode just stops the counting after 999, always displaying a static string "X of 999+ items", instead of this, why not display like "X of 1766 items"?  For example, today, I had to do this twice because I was checking some log files, and I had to open Atom just do to this. And its not the first time for this week. So, maybe other folks also have the same need.

- VSCode Version: 1.16.1
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Create a file with 1000 entries of some string, like " TEST ".
2. Press cmd + f and try to search for " TEST "
3. We can see that a search box is displayed, and it says "X of 999+ items". 
<img width="427" alt="screen shot 2017-10-25 at 4 10 01 pm" src="https://user-images.githubusercontent.com/1733227/32018119-39153850-b99f-11e7-8a5e-e68567bfbf8b.png">

What do you guys thinks about that proposal?

Thanks! :)

**Comment by isidorn** [comment] 2017-10-26 07:42
fyi @alexandrudima

**Comment by alexandrudima** [comment] 2017-10-26 09:52
Duplicate of #496

On the [insiders channel](https://code.visualstudio.com/insiders/) this limit has been bumped to 20k.

**Closed by alexandrudima** 2017-10-26 09:52 UTC
Labels: editor-find-widget
